### ISSUE TITLE
The same link and command download much larger files on Linux than on Windows.

### ISSUE THREAD

**Issue by assassinliujie** [yt-dlp/yt-dlp#10003]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

The same link and command download much larger files on Linux than on Windows.
![image](https://github.com/yt-dlp/yt-dlp/assets/68693675/016c89cc-0a56-42ab-8b72-cc265a1707ec)
![image](https://github.com/yt-dlp/yt-dlp/assets/68693675/123a36c6-fa88-46c6-9dcc-7b2a0ac86fab)
why

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by seproDev** [comment]
You are missing ffmpeg on windows

**Comment by assassinliujie** [comment]
> You are missing ffmpeg on windows
I tried uninstalling ffmpeg on Linux and indeed found it to be the case. I would like to ask if there is any quality difference between the files downloaded in these two ways?

**Comment by assassinliujie** [comment]
> You are missing ffmpeg on windows

I tried uninstalling ffmpeg on Linux and indeed found it to be the case. I would like to ask if there is any quality difference between the files downloaded in these two ways?

**Comment by seproDev** [comment]
Yes. ffmpeg is required for merging split audio and video formats together. Without that, you are limited to 720p on YouTube. Other websites might not even offer premerged formats, so you would end up with two files, one for the audio track and one for the video.
FFmpeg is optional, but [strongly recommended](https://github.com/yt-dlp/yt-dlp?tab=readme-ov-file#dependencies).

**Comment by Black-Semargl** [comment]
```
[info] Available formats for FnnjUMu6PeQ:
22      mp4   1280x720    30  2 │ ≈  5.75GiB
...
623     mp4   2560x1440   60    │ ~ 43.74GiB │ vp09.00.50.08 14921k
308     webm  2560x1440   60    │   28.85GiB │ vp09.00.50.08  9843k
251     webm  audio only      2 │  350.73MiB │ opus       117k 48k
```
