### ISSUE TITLE
"orf:on saves audio track with wrong language" - how to report this properly?

### ISSUE THREAD

**Issue by arminfuerst** [yt-dlp/yt-dlp#10008]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

When downloading files from on.orf.at the audio track is saved with the language code English while (at least in the majority of videos) the audio contains the German track. As the download is working properly and the language can be changed with little effort, none of the issue categories seem to be suitable to report this. What is the proper way of reporting such issues?

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp -vU https://on.orf.at/video/14227263/dok-1-mythos-ungesund-22
[debug] Command-line config: ['-vU', 'https://on.orf.at/video/14227263/dok-1-mythos-ungesund-22']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.05.20.232721 from yt-dlp/yt-dlp-nightly-builds [4ccd73fea] (zip)
[debug] Python 3.11.2 (CPython x86_64 64bit) - Linux-6.1.0-21-amd64-x86_64-with-glibc2.36 (OpenSSL 3.0.11 19 Sep 2023, glibc 2.36)
[debug] exe versions: ffmpeg 6.0.1 (fdk,setts), ffprobe 6.0.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.11.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.46.0, pyxattr-0.8.1, requests-2.28.1, secretstorage-3.3.3, sqlite3-3.40.1, urllib3-1.26.12, websockets-10.4
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Loaded 1803 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.05.20.232721 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.05.20.232721 from yt-dlp/yt-dlp-nightly-builds)
[orf:on] Extracting URL: https://on.orf.at/video/14227263/dok-1-mythos-ungesund-22
[orf:on] dok-1-mythos-ungesund-22: Downloading webpage
[orf:on] dok-1-mythos-ungesund-22: Downloading JSON metadata
[orf:on] dok-1-mythos-ungesund-22: Downloading m3u8 information
[orf:on] dok-1-mythos-ungesund-22: Downloading m3u8 information
[orf:on] dok-1-mythos-ungesund-22: Downloading MPD manifest
[orf:on] dok-1-mythos-ungesund-22: Downloading MPD manifest
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 14227263: Downloading 1 format(s): dash-p0va0br3001851-1+dash-p0aa0br192000-1
[debug] Invoking dashsegments downloader on "https://vod-ww.mdn.ors.at/cms-worldwide_nas/_definst_/nas/cms-worldwide/online/2024-05-22_2015_in_01_Dok-1--Mythos-U_____14227263__o__1355923399__s15643705_hr.smil/manifest.mpd"
[dashsegments] Total fragments: 278
[download] Destination: Dok 1： Mythos Ungesund (2⧸2) [14227263].fdash-p0va0br3001851-1.mp4
[download] 100% of  989.77MiB in 00:02:04 at 7.95MiB/s
[debug] Invoking dashsegments downloader on "https://vod-ww.mdn.ors.at/cms-worldwide_nas/_definst_/nas/cms-worldwide/online/2024-05-22_2015_in_01_Dok-1--Mythos-U_____14227263__o__1355923399__s15643705_hr.smil/manifest.mpd"
[dashsegments] Total fragments: 278
[download] Destination: Dok 1： Mythos Ungesund (2⧸2) [14227263].fdash-p0aa0br192000-1.m4a
[download] 100% of   64.28MiB in 00:00:28 at 2.25MiB/s
[Merger] Merging formats into "Dok 1： Mythos Ungesund (2⧸2) [14227263].mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:Dok 1： Mythos Ungesund (2⧸2) [14227263].fdash-p0va0br3001851-1.mp4' -i 'file:Dok 1： Mythos Ungesund (2⧸2) [14227263].fdash-p0aa0br192000-1.m4a' -c copy -map 0:v:0 -map 1:a:0 -movflags +faststart 'file:Dok 1： Mythos Ungesund (2⧸2) [14227263].temp.mp4'
Deleting original file Dok 1： Mythos Ungesund (2⧸2) [14227263].fdash-p0va0br3001851-1.mp4 (pass -k to keep)
Deleting original file Dok 1： Mythos Ungesund (2⧸2) [14227263].fdash-p0aa0br192000-1.m4a (pass -k to keep)



ffprobe -v error -show_format -show_streams Dok\ 1：\ Mythos\ Ungesund\ \(2⧸2\)\ \[14227263\].mp4  | grep -i language
TAG:language=eng
TAG:language=eng
```

**Comment by bashonly** [comment]
if you add `--embed-metadata` to your download command, does that fix your issue?

**Comment by arminfuerst** [comment]
> if you add `--embed-metadata` to your download command, does that fix your issue?

The language of the audio stream is correct with this parameter, the language of the video is still English:
![image](https://github.com/yt-dlp/yt-dlp/assets/29121472/3947ff37-2b6e-4479-b270-a5ac52f8cbe1)

Is there an additional parameter for the video stream? Omitting the language would also be fine, it's the first time I saw a video stream containing a language.

**Comment by bashonly** [comment]
> it's the first time I saw a video stream containing a language.

That is the metadata set by the site. It is incorrect on their end
