### ISSUE TITLE
Attempt to download from single Patreon membership instead crawls all memberships available to user

### ISSUE THREAD

**Issue by Tarinaky** [yt-dlp/yt-dlp#10013]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a site-specific feature
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

UK

### Example URLs

https://www.patreon.com/killjamesbond/posts
https://www.patreon.com/auntydonna/posts
https://www.patreon.com/lionsledbydonkeys/posts

### Provide a description that is worded well enough to be understood

When attempting to download all episodes of a given Patreon feed (i.e. a single podcast), using the --cookies-from-browser switch to provide the necessary credentials, yt-dlp will instead download *all* memberships available to the user, not just the one desired.

When passing without the cookies parameter, the crawler will access the correct feed (ie episodes of that podcast) but be unable to download anything due to the missing cookie.

Examples:

```yt-dlp "https://www.patreon.com/killjamesbond/posts" --cookies-from-browser firefox
[PatreonCampaign] Extracting URL: https://www.patreon.com/killjamesbond/posts
[PatreonCampaign] killjamesbond: Downloading webpage
Extracting cookies from firefox
Extracted 2556 cookies from firefox
[PatreonCampaign] 95843: Downloading campaign info
[download] Downloading playlist: Diamanda Hagan
[PatreonCampaign] 95843: Downloading posts page 1
[PatreonCampaign] 95843: Downloading posts page 2
[PatreonCampaign] 95843: Downloading posts page 3

ERROR: Interrupted by user

yt-dlp "https://www.patreon.com/killjamesbond/posts"
[PatreonCampaign] Extracting URL: https://www.patreon.com/killjamesbond/posts
[PatreonCampaign] killjamesbond: Downloading webpage
[PatreonCampaign] 6025828: Downloading campaign info
[download] Downloading playlist: Kill James Bond!
[PatreonCampaign] 6025828: Downloading posts page 1
[PatreonCampaign] 6025828: Downloading posts page 2
[PatreonCampaign] 6025828: Downloading posts page 3
[PatreonCampaign] 6025828: Downloading posts page 4
[PatreonCampaign] 6025828: Downloading posts page 5
[PatreonCampaign] 6025828: Downloading posts page 6
[PatreonCampaign] 6025828: Downloading posts page 7
[PatreonCampaign] 6025828: Downloading posts page 8
[PatreonCampaign] 6025828: Downloading posts page 9
[PatreonCampaign] 6025828: Downloading posts page 10
[PatreonCampaign] Playlist Kill James Bond!: Downloading 186 items of 186
[download] Downloading item 1 of 186
[Patreon] Extracting URL: https://www.patreon.com/posts/s3e19-5-northman-104350075
[Patreon] 104350075: Downloading API JSON
ERROR: [Patreon] 104350075: You do not have access to this post
[download] Downloading item 2 of 186
[Patreon] Extracting URL: https://www.patreon.com/posts/s3e19-quiller-103933243
[Patreon] 103933243: Downloading API JSON
ERROR: [Patreon] 103933243: You do not have access to this post
[download] Downloading item 3 of 186
[Patreon] Extracting URL: https://www.patreon.com/posts/s3e18-5-beowulf-103479113
[Patreon] 103479113: Downloading API JSON
ERROR: [Patreon] 103479113: You do not have access to this post
```

If I pass the URI to a specific post/episode to yt-dlp it will download that post/episode - but I want it to crawl an entire membership... Just not every membership I'm subscribed to.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp -vU "https://www.patreon.com/killjamesbond/posts" --cookies-from-browser firefox
[debug] Command-line config: ['-vU', 'https://www.patreon.com/killjamesbond/posts', '--cookies-from-browser', 'firefox']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.04.09 from yt-dlp/yt-dlp [ff0779267] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 4.2.3, ffprobe 4.3.2-2021-02-20-essentials_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.02.02, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.31.0, sqlite3-3.35.5, urllib3-2.2.1, websockets-12.0
[debug] Proxy map: {'no': '192.168.99.100,192.168.99.101'}
Extracting cookies from firefox
[debug] Extracting cookies from: "C:\Users\Tarinaky\AppData\Roaming\Mozilla\Firefox\Profiles\is0bkfnt.default-release\cookies.sqlite"
Extracted 2555 cookies from firefox
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1810 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.04.09 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.04.09 from yt-dlp/yt-dlp)
[PatreonCampaign] Extracting URL: https://www.patreon.com/killjamesbond/posts
[PatreonCampaign] killjamesbond: Downloading webpage
[PatreonCampaign] 95843: Downloading campaign info
[download] Downloading playlist: Diamanda Hagan
[PatreonCampaign] 95843: Downloading posts page 1
[PatreonCampaign] 95843: Downloading posts page 2
[PatreonCampaign] 95843: Downloading posts page 3


ERROR: Interrupted by user
```

**Comment by Tarinaky** [comment]
So I've just realised there's a workaround by finding the campaign id and building a uri like https://www.patreon.com/api/campaigns/6025828...

In case anyone else has a similar problem in future.

**Comment by zackpollard** [comment]
Also experiencing the same behavior, this was working until somewhere between the 21st and 23rd May based on when my scripts stopped working correctly.

**Comment by bashonly** [comment]
someone could try this patch:

```diff
diff --git a/yt_dlp/extractor/patreon.py b/yt_dlp/extractor/patreon.py
index 6c441ff34..efbface4b 100644
--- a/yt_dlp/extractor/patreon.py
+++ b/yt_dlp/extractor/patreon.py
@@ -486,7 +486,8 @@ def _real_extract(self, url):
         campaign_id, vanity = self._match_valid_url(url).group('campaign_id', 'vanity')
         if campaign_id is None:
             webpage = self._download_webpage(url, vanity, headers={'User-Agent': self.USER_AGENT})
-            campaign_id = self._search_regex(r'https://www.patreon.com/api/campaigns/(\d+)/?', webpage, 'Campaign ID')
+            campaign_id = self._search_nextjs_data(
+                webpage, vanity)['props']['pageProps']['bootstrapEnvelope']['pageBootstrap']['campaign']['data']['id']
 
         params = {
             'json-api-use-default-includes': 'false',
```

**Comment by zackpollard** [comment]
> someone could try this patch:
> 
> ```diff
> diff --git a/yt_dlp/extractor/patreon.py b/yt_dlp/extractor/patreon.py
> index 6c441ff34..efbface4b 100644
> --- a/yt_dlp/extractor/patreon.py
> +++ b/yt_dlp/extractor/patreon.py
> @@ -486,7 +486,8 @@ def _real_extract(self, url):
>          campaign_id, vanity = self._match_valid_url(url).group('campaign_id', 'vanity')
>          if campaign_id is None:
>              webpage = self._download_webpage(url, vanity, headers={'User-Agent': self.USER_AGENT})
> -            campaign_id = self._search_regex(r'https://www.patreon.com/api/campaigns/(\d+)/?', webpage, 'Campaign ID')
> +            campaign_id = self._search_nextjs_data(
> +                webpage, vanity)['props']['pageProps']['bootstrapEnvelope']['pageBootstrap']['campaign']['data']['id']
>  
>          params = {
>              'json-api-use-default-includes': 'false',
> ```

Tested this patch and it has fixed the issue! :smile:

**Comment by giacecco** [comment]
Because I get yt-dlp from Homebrew, I am still using stable@2024.05.27, that is old enough for the patch not to have been propagated yet, I guess. It may be interesting, however, to note that @Tarinaky's workaround is not working for me. The URL I am using is `https://www.patreon.com/underdogmusicschool/posts` aka `https://www.patreon.com/api/campaigns/931659`. Will keep an eye on the next stable release.

**Comment by bashonly** [comment]
@giacecco to install from the master branch with homebrew you can do this:

```
brew uninstall yt-dlp
brew update
brew install --HEAD yt-dlp
```
