### ISSUE TITLE
[Feature Request] Limit filename to # of bytes (not characters)

### ISSUE THREAD

**Issue by TowardMyth** [yt-dlp/yt-dlp#1003]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running yt-dlp version **2021.09.02**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description

YT-DLP has a feature to limit the filename length to some number of characters.

Is it possible to limit the **filename length to some number of **bytes** and not characters** too? Non-Latin languages require more than 1 byte to represent a character. For example, Japanese/Korean/Chinese characters require 3 bytes per character.

Use case: for example, EXT4 file systems only allow 255 byte file name limits.

Thank you!

**Comment by pukkandan** [comment]
With https://github.com/yt-dlp/yt-dlp/commit/f5aa5cfbffeea9352ace141707f35c86f5e11b89, you can do `%(title).200B` to limit to 200 bytes instead of `%(title).200s` which normally limits to 200 chars

**Comment by TowardMyth** [comment]
thanks for the quick implementation!
