### ISSUE TITLE
Some TikTok user pages get stuck in an infinite loop

### ISSUE THREAD

**Issue by rebane2001** [yt-dlp/yt-dlp#10033]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [x] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Provide a description that is worded well enough to be understood

Some TikTok user pages get stuck in the "Downloading page x" cycle seemingly infinitely, for example https://www.tiktok.com/@shuxer59

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--ignore-config', 'https://www.tiktok.com/@shuxer59']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.05.26 from yt-dlp/yt-dlp [ae2af1104]
[debug] Lazy loading extractors is disabled
[debug] Python 3.10.12 (CPython x86_64 64bit) - Linux-5.15.0-105-generic-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.02.02, mutagen-1.47.0, requests-2.32.2, secretstorage-3.3.1, sqlite3-3.37.2, urllib3-2.2.1, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1820 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.05.26 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.05.26 from yt-dlp/yt-dlp)
[tiktok:user] Extracting URL: https://www.tiktok.com/@shuxer59
[tiktok:user] shuxer59: Downloading user webpage
[download] Downloading playlist: shuxer59
[tiktok:user] shuxer59: Downloading page 1
[tiktok:user] shuxer59: Downloading page 2
[tiktok:user] shuxer59: Downloading page 3
[tiktok:user] shuxer59: Downloading page 4
[tiktok:user] shuxer59: Downloading page 5
[tiktok:user] shuxer59: Downloading page 6
[tiktok:user] shuxer59: Downloading page 7
[tiktok:user] shuxer59: Downloading page 8
[tiktok:user] shuxer59: Downloading page 9
[tiktok:user] shuxer59: Downloading page 10
[tiktok:user] shuxer59: Downloading page 11
[tiktok:user] shuxer59: Downloading page 12
[tiktok:user] shuxer59: Downloading page 13
[tiktok:user] shuxer59: Downloading page 14
[tiktok:user] shuxer59: Downloading page 15
[tiktok:user] shuxer59: Downloading page 16
[tiktok:user] shuxer59: Downloading page 17
[tiktok:user] shuxer59: Downloading page 18
[tiktok:user] shuxer59: Downloading page 19
[tiktok:user] shuxer59: Downloading page 20
...
```

**Comment by bashonly** [comment]
Workaround: You can add `--lazy-playlist` to your command to download the videos as yt-dlp paginates and then manually interrupt the program with CTRL-C once duplicate videos are being extracted or empty pages are being downloaded.

Notes for devs:

The site's pagination is timestamp-based, and when setting the cursor (timestamp) for to request the next page, the only info we have to go off of is the timestamp of the oldest post from the current page. In the OP's example, requesting with a cursor of the oldest timestamp from the current page yields an identical next page result. I suspect this happens when there is a large gap of time between the most recent 15 posts by the user and the next oldest post; we get 15 posts per page and TT decides that our "oldest timestamp" is closer to the most recent 15 than the next 15 (or less) after the sizeable time gap. If anyone cam validate or debunk this hypothesis that would be appreciated

**Comment by rebane2001** [comment]
Thank you for the quick fix, seems to work great on my side!
