### ISSUE TITLE
Is that a youtube thing, that not all videos with ytsearch are returned and put a limit per search of 1000 items?

### ISSUE THREAD

**Issue by estatistics** [yt-dlp/yt-dlp#10039]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

The first command will find to download 960+ videos from 1st  "ytsearch". In sum, it may download more than 2000. 
The 2nd one will download many additional videos that contain in their title "Gangnam style", if executed after the 1st one. 
I have not seen a ytsearch to return more than 1000 titles. 
So I think, that youtube may put a limit on how many results return?
Then someone may cannot access some videos ever. 
I read somewhere that i can set "datebefore"; to return all videos eg. before 2012? How i can achieve this?

> yt-dlp   --no-warning --max-filesize 800M --username oauth2 --password '' --check-formats  --retries 1000 --fragment-retries 20 --retry-sleep 120 --limit-rate 800k --write-description --download-archive archive.txt -o "%(title)s_[%(id)s].%(ext)s"--reject-title "(walking street|Afternoon Walk|Gangnam Street|GANGNAM, SEOUL|GANGNAM Seoul|shopping|vlog|10 hours|minecraft|Fortnite|Walking from)" --match-filter '!is_live & live_status!=is_upcoming' -- "ytsearch2000:Gangnam" "ytsearch2000:Gangnam style" "ytsearch2000:Gangnam Style" "ytsearch2000:gangnam style" "ytsearch2000:GANGNAM STYLE" "ytsearch30:parody Gangnam" "ytsearch30:parody psy" 

> yt-dlp   --no-warning --max-filesize 800M --username oauth2 --password '' --check-formats  --retries 1000 --fragment-retries 20 --retry-sleep 120 --limit-rate 800k --write-description --download-archive archive.txt -o "%(title)s_[%(id)s].%(ext)s" --reject-title "(walking street|Afternoon Walk|Gangnam Street|GANGNAM, SEOUL|GANGNAM Seoul|shopping|vlog|10 hours|minecraft|Fortnite|Walking from)" --match-filter '!is_live & live_status!=is_upcoming' --  "ytsearch1000:Gangnam flash"

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.05.26.232731 from yt-dlp/yt-dlp-nightly-builds [ae2194e1d] (zip)
[debug] Python 3.11.9 (CPython x86_64 64bit) - Linux-6.1.0-15-amd64-x86_64-with-glibc2.38 (OpenSSL 3.2.2-dev , glibc 2.38)
[debug] exe versions: ffmpeg 6.1.1-4 (setts), ffprobe 6.1.1-4, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.11.0, brotli-1.1.0, certifi-2023.11.17, mutagen-1.46.0, pyxattr-0.8.1, requests-2.31.0, sqlite3-3.45.3, urllib3-1.26.18, websockets-10.4
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Extractor Plugins: TTUser (TikTokUserIE), oauth2 (YoutubeBaseInfoExtractor), oauth2 (YoutubeClipIE), oauth2 (YoutubeConsentRedirectIE), oauth2 (YoutubeFavouritesIE), oauth2 (YoutubeIE), oauth2 (YoutubeMusicSearchURLIE), oauth2 (YoutubeNotificationsIE), oauth2 (YoutubeSearchDateIE), oauth2 (YoutubeSearchIE), oauth2 (YoutubeSearchURLIE), oauth2 (YoutubeTabBaseInfoExtractor), oauth2 (YoutubeTabIE)
[debug] Plugin directories: ['/home/elias/.local/lib/python3.11/site-packages/yt_dlp_plugins']
[debug] Loaded 1820 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.05.26.232731 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.05.26.232731 from yt-dlp/yt-dlp-nightly-builds)
```

**Comment by bashonly** [comment]
Closing in favor of #10059
