### ISSUE TITLE
 Metadata Correction for HLS Stream Video

### ISSUE THREAD

**Issue by ndyanx** [yt-dlp/yt-dlp#10031]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

I’ve successfully downloaded a video from the following HLS stream URL: https://stream4k.embeddrive.net/playlists/1515a3a7-b6ab-43e1-8eab-5141e7641de2/cf.m3u8. The video downloads without any issues, but it does not play back on all media players. Specifically, it works on Windows 11 Media Player but not on VLC.

Upon inspecting the metadata, I found the following:
`{'streams': [{'index': 0, 'codec_name': 'png', 'codec_long_name': 'PNG (Portable Network Graphics) image', 'codec_type': 'video', 'codec_tag_string': '[0][0][0][0]', 'codec_tag': '0x0000', 'width': 1, 'height': 1, 'coded_width': 1, 'coded_height': 1, 'closed_captions': 0, 'film_grain': 0, 'has_b_frames': 0, 'sample_aspect_ratio': '1:1', 'display_aspect_ratio': '1:1', 'pix_fmt': 'rgb24', 'level': -99, 'color_range': 'pc', 'color_space': 'gbr', 'color_transfer': 'iec61966-2-1', 'color_primaries': 'bt709', 'refs': 1, 'r_frame_rate': '25/1', 'avg_frame_rate': '25/1', 'time_base': '1/25', 'disposition': {'default': 0, 'dub': 0, 'original': 0, 'comment': 0, 'lyrics': 0, 'karaoke': 0, 'forced': 0, 'hearing_impaired': 0, 'visual_impaired': 0, 'clean_effects': 0, 'attached_pic': 0, 'timed_thumbnails': 0, 'non_diegetic': 0, 'captions': 0, 'descriptions': 0, 'metadata': 0, 'dependent': 0, 'still_image': 0}}], 'format': {'filename': 'C:/Users/lelis/cf.mp4', 'nb_streams': 1, 'nb_programs': 0, 'format_name': 'png_pipe', 'format_long_name': 'piped png sequence', 'size': '1086672100', 'probe_score': 99}}`
wrong metadata
The metadata indicates that the codec is recognized as ‘png’, which seems to be the root of the playback issue on VLC. I would like to know if there’s a way to correct this during or after the download process.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['--verbose', 'https://stream4k.embeddrive.net/playlists/1515a3a7-b6ab-43e1-8eab-5141e7641de2/cf.m3u8']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.05.20.232721 from yt-dlp/yt-dlp-nightly-builds [4ccd73fea] (pip)
[debug] Python 3.11.3 (CPython AMD64 64bit) - Windows-10-10.0.22631-SP0 (OpenSSL 1.1.1t  7 Feb 2023)
[debug] exe versions: ffmpeg 2023-10-26-git-2b300eb533-full_build-www.gyan.dev (setts), ffprobe 2023-10-26-git-2b300eb533-full_build-www.gyan.dev, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2024.02.02, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.2, sqlite3-3.40.1, urllib3-2.1.0, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1819 extractors
[generic] Extracting URL: https://stream4k.embeddrive.net/playlists/1515a3a7-b6ab-43e1-8eab-5141e7641de2/cf.m3u8
[generic] cf: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[debug] Identified a M3U playlist
[generic] cf: Downloading m3u8 information
[generic] cf: Checking m3u8 live status
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] cf: Downloading 1 format(s): 0
[debug] Invoking hlsnative downloader on "https://stream4k.embeddrive.net/playlists/1515a3a7-b6ab-43e1-8eab-5141e7641de2/cf.m3u8"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 784
[download] Destination: cf [cf].mp4
[debug] File locking is not supported. Proceeding without locking
[download] 100% of    1.01GiB in 00:05:07 at 3.37MiB/s
[debug] ffprobe command line: ffprobe -hide_banner -show_format -show_streams -print_format json "file:cf [cf].mp4"
```

**Comment by bashonly** [comment]
provide an example of this issue that isn't  a piracy link and only then will it be considered something that needs to be fixed
