### ISSUE TITLE
Why reject title filter dont work?

### ISSUE THREAD

**Issue by estatistics** [yt-dlp/yt-dlp#10037]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

> yt-dlp   --no-warning --max-filesize 800M --username oauth2 --password '' --check-formats  --retries 1000 --fragment-retries 20 --retry-sleep 120 --limit-rate 800k --write-description --download-archive archive.txt -o "%(title)s_[%(id)s].%(ext)s" --reject-title "walking street | Afternoon Walk | Gangnam Street | GANGNAM, SEOUL | GANGNAM Seoul | shopping | vlog | 10 hours | minecraft | Fortnite" --match-filter '!is_live & live_status!=is_upcoming' --  "ytsearch2000:Gangnam style" 

However, both  "10 hours" (yt id: 45Vaf7GeNc0) and "Gangnam Street" (yt id: x9RQBPmXpEQ) have been downloaded which both are included in rejected phrases/words that were defined in yt-dlp.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
]
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.04.09 from yt-dlp/yt-dlp [ff0779267] (zip)
[debug] Python 3.11.9 (CPython x86_64 64bit) - Linux-6.1.0-15-amd64-x86_64-with-glibc2.38 (OpenSSL 3.2.2-dev , glibc 2.38)
[debug] exe versions: ffmpeg 6.1.1-4 (setts), ffprobe 6.1.1-4, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.11.0, brotli-1.1.0, certifi-2023.11.17, mutagen-1.46.0, pyxattr-0.8.1, requests-2.31.0, sqlite3-3.45.3, urllib3-1.26.18, websockets-10.4
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Extractor Plugins: TTUser (TikTokUserIE), oauth2 (YoutubeBaseInfoExtractor), oauth2 (YoutubeClipIE), oauth2 (YoutubeConsentRedirectIE), oauth2 (YoutubeFavouritesIE), oauth2 (YoutubeIE), oauth2 (YoutubeMusicSearchURLIE), oauth2 (YoutubeNotificationsIE), oauth2 (YoutubeSearchDateIE), oauth2 (YoutubeSearchIE), oauth2 (YoutubeSearchURLIE), oauth2 (YoutubeTabBaseInfoExtractor), oauth2 (YoutubeTabIE)
[debug] Plugin directories: ['/home/elias/.local/lib/python3.11/site-packages/yt_dlp_plugins']
[debug] Loaded 1810 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
[debug] Downloading _update_spec from https://github.com/yt-dlp/yt-dlp/releases/latest/download/_update_spec
[debug] Downloading SHA2-256SUMS from https://github.com/yt-dlp/yt-dlp/releases/download/2024.05.26/SHA2-256SUMS
Current version: stable@2024.04.09 from yt-dlp/yt-dlp
Latest version: stable@2024.05.26 from yt-dlp/yt-dlp
Current Build Hash: bb2214f4b33d58f9ef0decf0c007c2c3de3f176781ee0222733e50e28e436159
```

**Comment by bashonly** [comment]
it needs to be a valid regex pattern
```
--reject-title "(walking street|Afternoon Walk|Gangnam Street|GANGNAM, SEOUL|GANGNAM Seoul|shopping|vlog|10 hours|minecraft|Fortnite)"
```
