### ISSUE TITLE
Certain youtube videos causing high CPU usage by yt-dlp and not playing on mpv

### ISSUE THREAD

**Issue by Obegg** [yt-dlp/yt-dlp#10042]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

For the past few days I've been trying to play YouTube videos using mpv and it appears some of them won't load, all of the sudden I hear my CPU fan gaining speed and making noise and here's what I see on the task manager:
![ytdlp high usage](https://github.com/yt-dlp/yt-dlp/assets/13978119/418cc63d-9fdb-4001-9b87-21a886c7456e)
So certain YouTube videos won't load, yt-dlp causing high CPU usage, even if I close mpv I also need to close yt-dlp.exe.
But - it does at least mark that video as watched, so that's fine (using [exported cookies files using incognito mode](https://github.com/yt-dlp/yt-dlp/issues/8227#issuecomment-1793513579))

Trying to diagnose it:
I have read the [KNOWN ISSUES/FAQ](https://github.com/yt-dlp/yt-dlp/issues/3766), so I tried updating to master:
```
Current version: stable@2024.05.26 from yt-dlp/yt-dlp
Latest version: master@2024.05.27.042308 from yt-dlp/yt-dlp-master-builds
Current Build Hash: 261aafd5abae1f92ca7e9bb4761e248a0f1746e7d170a46e17b5f0c11639c86c
Updating to master@2024.05.27.042308 from yt-dlp/yt-dlp-master-builds ...
Updated yt-dlp to master@2024.05.27.042308 from yt-dlp/yt-dlp-master-builds
```
it doesn't seem to fix the issue

Using [DNSQuerySniffer](https://www.nirsoft.net/utils/dns_query_sniffer.html) it appears it doesn't even make a DNS request while drag and drop has occurred (from YouTube.com to mpv)
Note: I use Pi-Hole and I also don't see any DNS request there either.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
I have no idea how to securely share logs of yt-dlp (without giving out IPs and stuff) so that's why I don't open an issue.

[debug] Command-line config: ['-v']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.05.26 from yt-dlp/yt-dlp [ae2af1104] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19044-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-115391-g63697d335 (setts)
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.02.02, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.2, sqlite3-3.35.5, urllib3-2.2.1, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1820 extractors
```

**Comment by bashonly** [comment]
> certain YouTube videos won't load, yt-dlp causing high CPU usage

You need show verbose logs of what happens when you try to download these videos with yt-dlp

**Comment by estatistics** [comment]
Because in linux i use mpv too, i have same problem. check the bitrate of video with media info. If it is very high, then check if you have a good SSD, indepdendent high tech graphic card as well a very good cpu. 

Videos with 60mb or more bitrate are lagging even to a good system.

I dont know if this the issue of yours. Maybe it is something else for you.
