### ISSUE TITLE
[Site Request] Put Bandcamp singles into self-titled albums and make them the only track in there instead of leaving it empty/NA

### ISSUE THREAD

**Issue by helpimnotdrowning** [yt-dlp/yt-dlp#1004]
## Checklist

- [x] I'm reporting a site feature request
- [x] I've verified that I'm running yt-dlp version **2021.09.02**
- [x] I've searched the bugtracker for similar site feature requests including closed ones

## Description

I am using this command to download stuff, so thats why I have the extra thumbnails and different output format.
```
yt-dlp -f "(bestaudio[ext*=mp3])" --verbose --force-ipv4 --sleep-requests 1 --sleep-interval 5 --max-sleep-interval 20 --ignore-errors --no-continue --no-overwrites --download-archive archive.log --add-metadata --write-annotations --write-thumbnail --sub-langs all --write-sub --convert-subs srt --compat-options multistreams --merge-output-format mkv --output "%%(uploader)s/%%(album)s/%%(track_number)02d %%(title)s.%%(ext)s" --batch-file "Source - Channels.txt"
```

On Bandcamp, people can release single tracks, and these single tracks can show up on an artists page alongside albums. When downloading these singles, it saves the `album` and `track_number` tags in the metadata as empty, and if you're using it in your output template, it saves replaces them both as NA:
```
W:.
├───NA
│       NA luvbird - for a brighter day.mp3
│       NA luvbird - for a brighter day.jpg
│       NA luvbird - our summer nights.mp3
│       NA luvbird - our summer nights.jpg
│       NA luvbird - sleep tight.mp3
│       NA luvbird - sleep tight.jpg
│       NA luvbird - without u.mp3
│       NA luvbird - without u.jpg
```
My solution is to detect when it is downloading a single track release (and not just downloading one track from an album), and when this is detected, it makes the `album` tag the same as the `title`/`track` and the `track_number` becomes 1.

The solution would turn the above tree into something like this:
```
W:.
├───for a brighter day
│       01 luvbird - for a brighter day.mp3
│       01 luvbird - for a brighter day.jpg
├───our summer nights
│       01 luvbird - our summer nights.mp3
│       01 luvbird - our summer nights.jpg
├───sleep tight
│       01 luvbird - sleep tight.mp3
│       01 luvbird - sleep tight.jpg
├───without u
│       01 luvbird - without u.mp3
│       01 luvbird - without u.jpg
```
where instead of a single getting thrown into the NA folder and getting to be track number NA, it gets to be the only track in a self-titled album.

**Comment by Ashish0804** [comment]
This can be done using 
`-o "%%(uploader)s/%%(album|title)s/%%(track_number|1)02d %%(title)s.%%(ext)s"`
See https://github.com/yt-dlp/yt-dlp#output-template for more info

**Comment by pukkandan** [comment]
@Ashish0804 `%(album|title)s` is wrong. See #899

**Comment by pukkandan** [comment]
With https://github.com/yt-dlp/yt-dlp/commit/7c37ff97d3b95444ece7e7da2da6f03293003df3, `%(album,title)s` will work
