### ISSUE TITLE
Error related to YoutubeIE and lazyextractors

### ISSUE THREAD

**Issue by triplesixman** [yt-dlp/yt-dlp#10049]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Since the May 26th update, lazy extractors no longer work properly. I'm getting an error in the file yt-dlp/yt_dlp/extractor/lazy_extractors.py, which means I have to add "YoutubeIE," to "from ..utils import (" to avoid getting the error.

I use my own script which retrieves the latest release of yt-dlp which I then compile.

The problem has been occurring since the May 26 release, and it happened again with the May 27 release (I don't have a more recent verbose, but the error was exactly the same).

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
root@d7446:~/test# /usr/local/bin/yt-dlp.sh https://youtu.be/YVkUvmDQ3HY -vU
[debug] Command-line config: ['https://youtu.be/YVkUvmDQ3HY', '-vU']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.05.26 from yt-dlp/yt-dlp [ae2af1104] (source)
[debug] Git HEAD: ed274b60b
[debug] Python 3.9.7 (CPython x86_64 64bit) - Linux-5.10.0-28-amd64-x86_64-with-glibc2.31 (OpenSSL 1.1.1w  11 Sep 2023, glibc 2.31)
[debug] exe versions: ffmpeg N-115029-g08781ebe1a-20240430 (setts), ffprobe N-115029-g08781ebe1a-20240430, phantomjs 2.1.1
[debug] Optional libraries: sqlite3-3.34.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Loaded 1819 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.05.26 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.05.26 from yt-dlp/yt-dlp)
Traceback (most recent call last):
  File "/opt/yt-dlp/yt_dlp/__main__.py", line 17, in <module>
    yt_dlp.main()
  File "/opt/yt-dlp/yt_dlp/__init__.py", line 1072, in main
    _exit(*variadic(_real_main(argv)))
  File "/opt/yt-dlp/yt_dlp/__init__.py", line 1062, in _real_main
    return ydl.download(all_urls)
  File "/opt/yt-dlp/yt_dlp/YoutubeDL.py", line 3572, in download
    self.__download_wrapper(self.extract_info)(
  File "/opt/yt-dlp/yt_dlp/YoutubeDL.py", line 3547, in wrapper
    res = func(*args, **kwargs)
  File "/opt/yt-dlp/yt_dlp/YoutubeDL.py", line 1581, in extract_info
    if not ie.suitable(url):
  File "/opt/yt-dlp/yt_dlp/extractor/lazy_extractors.py", line 187, in suitable
    return False if YoutubeIE.suitable(url) else super().suitable(url)
NameError: name 'YoutubeIE' is not defined
```

**Comment by bashonly** [comment]
I cannot reproduce your issue.

> which means I have to add "YoutubeIE," to "from ..utils import (" to avoid getting the error.

This is not correct. Do not edit `lazy_extractors.py` by hand. Always generate it using `make lazy-extractors` or `python3 devscripts/make_lazy_extractors.py`. If you are running from source with lazy extractors, you'll need to do this every time you pull, add/remove extractors, or checkout a different branch.

> I use my own script which retrieves the latest release of yt-dlp which I then compile.

Can you share your script?

From the project root, try running:
```
make clean-all
make lazy-extractors
```

**Comment by triplesixman** [comment]
> I cannot reproduce your issue.
> 
> > which means I have to add "YoutubeIE," to "from ..utils import (" to avoid getting the error.
> 
> This is not correct. Do not edit `lazy_extractors.py` by hand. Always generate it using `make lazy-extractors` or `python3 devscripts/make_lazy_extractors.py`. If you are running from source with lazy extractors, you'll need to do this after every time you update/pull, add/remove/modify extractors, or checkout a different branch/tag/etc.
> 
> > I use my own script which retrieves the latest release of yt-dlp which I then compile.
> 
> Can you share your script?
> 
> From the project root, try running:
> 
> ```
> make clean-all
> make lazy-extractors
> ```

My script: https://pastebin.com/9kctdv8a

I also tried putting "make lazy-extractors" outside the "if" loop, but it didn't solve the problem: https://pastebin.com/P6VLJjc1

**Comment by bashonly** [comment]
try adding these lines at the end, outside of the if/then block
```bash
make clean
PYTHON="${PYENV_PYTHON_PATH}"/python make lazy-extractors 
```

if you are still having trouble, then please also share `/usr/local/bin/yt-dlp.sh`

**Comment by dirkf** [comment]
I wonder how the created `lazy_extractors.py` differ between current and pre 26 May releases (especially since there are no obviously relevant commits since then).
