### ISSUE TITLE
which are the ytsearch operators that i can use eg. AND OR etc.?  

### ISSUE THREAD

**Issue by estatistics** [yt-dlp/yt-dlp#10059]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I have searched and i cant find it. 
which are the ytsearch operators that i can use eg. AND OR etc.?  
or when using "ytsearch100:music video" AND operator is "space"? 

2nd question:
How i can search both in title and deascription for words? 

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
U
[debug] Command-line config: ['-vU']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.05.26.232731 from yt-dlp/yt-dlp-nightly-builds [ae2194e1d] (zip)
[debug] Python 3.11.9 (CPython x86_64 64bit) - Linux-6.1.0-15-amd64-x86_64-with-glibc2.38 (OpenSSL 3.2.2-dev , glibc 2.38)
[debug] exe versions: ffmpeg 6.1.1-4 (setts), ffprobe 6.1.1-4, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.11.0, brotli-1.1.0, certifi-2023.11.17, mutagen-1.46.0, pyxattr-0.8.1, requests-2.31.0, sqlite3-3.45.3, urllib3-1.26.18, websockets-10.4
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Extractor Plugins: TTUser (TikTokUserIE), oauth2 (YoutubeBaseInfoExtractor), oauth2 (YoutubeClipIE), oauth2 (YoutubeConsentRedirectIE), oauth2 (YoutubeFavouritesIE), oauth2 (YoutubeIE), oauth2 (YoutubeMusicSearchURLIE), oauth2 (YoutubeNotificationsIE), oauth2 (YoutubeSearchDateIE), oauth2 (YoutubeSearchIE), oauth2 (YoutubeSearchURLIE), oauth2 (YoutubeTabBaseInfoExtractor), oauth2 (YoutubeTabIE)
[debug] Plugin directories: ['/home/elias/.local/lib/python3.11/site-packages/yt_dlp_plugins']
[debug] Loaded 1820 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
[debug] Downloading _update_spec from https://github.com/yt-dlp/yt-dlp-nightly-builds/releases/latest/download/_update_spec
[debug] Downloading SHA2-256SUMS from https://github.com/yt-dlp/yt-dlp-nightly-builds/releases/download/2024.05.27.232744/SHA2-256SUMS
Current version: nightly@2024.05.26.232731 from yt-dlp/yt-dlp-nightly-builds
Latest version: nightly@2024.05.27.232744 from yt-dlp/yt-dlp-nightly-builds
Current Build Hash: f41345c3206238c52b420abde678f9ee873c8d9a5a1f596be2844be751c0d597
Updating to nightly@2024.05.27.232744 from yt-dlp/yt-dlp-nightly-builds ...
```

**Comment by estatistics** [comment]
i have found that youtube uses these operators. how can these operators used with ytsearch? 
some examples?

>  Part I: YouTube Search Operators
“” [Quotation Marks]
+ [Plus]
– [Minus]
| [Pipe]
OR
() [Parentheses]
$ [Dollar Sign]
#..# [Number Range]
intitle:
allintitle:
description:
before:[date]
after:[date]
* [Wildcard]
#tag

**Comment by bashonly** [comment]
> i have found that youtube uses these operators.

These ones

> how can these operators used with ytsearch?

Have you tried just using them after `ytsearch:` ? e.g. `yt-dlp "ytsearch:seo (john mueller | marie haynes)"`

**Comment by estatistics** [comment]
I have tried the following examples: 

> yt-dlp   --no-warning --max-filesize 800M --cookies-from-browser firefox:/mnt/tmp_ssd/firefox_tmp/default_mine/  --username oauth2 --password '' --check-formats  --retries 1000 --fragment-retries 20 --retry-sleep 120 --limit-rate 800k --write-description --download-archive archive.txt -o "%(title)s_[%(id)s].%(ext)s" --reject-title "(walking street|Afternoon Walk|Gangnam Street|GANGNAM, SEOUL|GANGNAM Seoul|shopping|vlog|10 hours|minecraft|Fortnite|Walking from)" --match-filter '!is_live & live_status!=is_upcoming' --  YTSEARCH


"ytsearch2000:Gangnam +style" which returns 699 results (28 pages)
"ytsearch2000:Gangnam style" which returns 873 results (30 pages)
 "ytsearch2000:(Gangnam +style)" which returns 714 results (29 pages)
"ytsearch2000:Gangnam (+style)" which returns 852 results (30 pages)
 "ytsearch2000:(allintitle:Gangnam style)"  which returns 158 results (21 pages)
 "ytsearch2000:allintitle:Gangnam style"  which returns 750 results (30 pages)

Note that youtube put a limit of 1000 results / 30 pages, and then based on these results, filter them afterwards. This may mean that generic results "Gangnam style" which are returned DO contain both words anywhere in title and description which other results are more strict in filtering?  

However, i cannot understand while the phrase 
 - "Gangnam style" returns many more results which implies that one word will exist side by side with the other one. However, in reality (downloaded files) is not true.
 -  "Gangnam +style" returns much less results which implies that both words can be anywhere in distance in their title. 

I can understand that returned results are based on youtube policies which tries to return "best matches". 
So, do you have any suggestion on that? which is the most correct way to use these filters?

Also, if i need to search in both title and description, with a specific date, how to do it that?

"ytsearch2000:(allintitle:Gangnam style,  description:"Gangnam style", before:2013-01-01)"

**Comment by bashonly** [comment]
are these questions about yt-dlp? or about the youtube website?

**Comment by estatistics** [comment]
I have written my thoughts on how works youtube search, but the questions are about ytsearch. What is the right way to use the filters that youtube provides. So, i am waiting for some answer if you know.
