### ISSUE TITLE
[Feature Request] Derive _date from timestamps

### ISSUE THREAD

**Issue by makeworld-the-better-one** [yt-dlp/yt-dlp#1005]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running yt-dlp version **2021.09.02**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description

It would be helpful for yt-dlp script users if the `release_date` and `upload_date` fields were derived from the `release_timestamp` and `timestamp` ones respectively, when the `_date` ones hadn't been specified but the timestamp ones had. Timezone is a question, I think using converting using the local timezone probably a reasonable default.

**Comment by Ashish0804** [comment]
We already do this
from common.py
```
    upload_date:    Video upload date (YYYYMMDD).
                    If not explicitly set, calculated from timestamp.
```

**Comment by pukkandan** [comment]
Ashish is right, we are already doing this

**Comment by makeworld-the-better-one** [comment]
Sorry, not sure how I didn't see that. Is it done with `release_date` as well?

**Comment by pukkandan** [comment]
yes
