### ISSUE TITLE
[Feature Request] Embed timestamps from youtube comments as chapters

### ISSUE THREAD

**Issue by juligreen** [yt-dlp/yt-dlp#1008]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running yt-dlp version **2021.09.02**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description

A lot of videos don't include timestamps in their description (or include them only later, maybe taken from the comments as happened here: https://www.youtube.com/watch?v=1VW0uaoN5Yc).
I'd like to be able to embed any timestamps from youtube comments as chapters in the downloaded video.

Too avoid cluttering the video too much (multiple comments mentioning the same timestamp) it would probably be useful to merge timestamps that are close too each other (between 2 and 10 seconds I'd guess).

The chapter text would probably include the comment's text next to the timestamp from the first comment mentioning the timestamp.

Another solution would be to only take the timestamps from the comment with the most upvotes or comments above a certain upvote threshold.

I hope this feature is not too out there and thank you for considering it! :)

**Comment by pukkandan** [comment]
I think this is better suited for a third party script to implement rather than something to be added in yt-dlp self and that it's too much beyond the scope of this project. But I'm not closing this yet, since I'd like to hear what others think about it

PS: We are not actually parsing the timestamps from the description. Youtube parses it and makes it available. We only take that data and add chapters using it. For OP's request, we will need to download comments (which we can already do), look at them for matching patterns and then parse chapter timestamps/title from it (probly the hardest part - and however we do it, it will probably end up being buggy).

**Comment by Ashish0804** [comment]
Usually the uploader himself adds the timestamps from popular comments. It's better to pressure the uploader to include timestamps rather than writing multiple scripts for scraping from comments.

The titles in comments will be different aswell.
I agree with pukkandan and it's something that should handled by user and external scripts or just wait for the uploader to add them.

**Comment by coletdjnz** [comment]
I also noticed a little while ago YouTube was testing a timed text feature for comments. Though I don't think this would be useful in this case.

Also could be in the form of subtitles, or something similar to the live chat. If there is an external tool for viewing live chat, then maybe you could to write a script to convert comments with timestamps to live chat format.

But yeah I agree with the others, I think this is out of scope for yt-dlp.

**Comment by juligreen** [comment]
Thanks for the quick reply!

I will try to script this myself as an external program and will post the results here

**Comment by juligreen** [comment]
This is the solution I came up with.
It needs ffmpeg installed and the python library `sortedcontainers`.

You use it like this:
```bash
yt-dlp--extractor-args"youtube:max_comments=300;max_comment_depth=2;comment_sort=top"--write-comments--exec~/Programs/embed_chapters.py<youtube-url>
```

```python
#!/usr/bin/env python3

import json
import os
import re
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Union

from sortedcontainers import SortedDict

video_file = sys.argv[1]

filename = Path(video_file)
dirname = os.path.dirname(filename)
json_name = filename.with_suffix(".info.json")
metadata_name = filename.with_suffix(".metadata")
new_filename = filename.with_suffix(".new.mp4")
final_filename = filename.with_suffix(".mp4")

original_chapters = []
comments = []

with open(json_name) as json_file:
    data = json.load(json_file)
    duration = data["duration"]
    if "chapters" in data:
        original_chapters = data["chapters"]
    comments = data["comments"]


def convert_timestamp_to_seconds(timestamp_list: list[str]) -> int:
    int_timestamp_list = list(map(int, timestamp_list))
    if len(timestamp_list) == 2:
        return int_timestamp_list[0] * 60 + int_timestamp_list[1]
    if len(timestamp_list) == 3:
        return (
            int_timestamp_list[0] * 60 * 60
            + int_timestamp_list[1] * 60
            + int_timestamp_list[0]
        )


timestamp_regex = r"^\s*>?\s?\[?((\d:)?\d{1,2}:\d{1,2})\]?\s?(.*)$"

sorted_comments = SortedDict()


def add_original_video_capters(original_chapters: list[dict[str, Union[str, int]]]):
    if original_chapters:
        for chapter in original_chapters:
            sorted_comments[chapter["start_time"]] = chapter["title"]


def add_to_sorted_comments_dict(timestamp_in_sec: int, comment_text: str):
    for i in range(timestamp_in_sec, timestamp_in_sec + 16):
        if i in sorted_comments:
            return
    sorted_comments[timestamp_in_sec] = comment_text


def generate_metadata_file(comments_dict: SortedDict):
    file_text = ";FFMETADATA1\n\n"
    temp_list = list(comments_dict)
    for index, timestamp in enumerate(temp_list):
        chapter = f"""
[CHAPTER]
TIMEBASE=1/1
START={timestamp}
END={temp_list[index + 1] if index + 1 < len(temp_list) else duration}
title={comments_dict[timestamp]}
"""
        file_text = file_text + chapter
    return file_text


def merge_chapters_into_new_video_file():
    subprocess.check_output(
        [
            "ffmpeg",
            "-i",
            filename,
            "-i",
            metadata_name,
            "-y",
            "-map_metadata",
            "1",
            "-map_chapters",
            "1",
            "-codec",
            "copy",
            new_filename,
        ]
    )


def replace_old_file_with_new():
    os.remove(filename)
    os.remove(metadata_name)
    os.remove(json_name)
    shutil.move(new_filename, final_filename)


add_original_video_capters(original_chapters)
if comments:
    for comment in comments:
        comment_text = comment["text"]
        matches = re.finditer(timestamp_regex, comment_text, re.MULTILINE)
        for match in matches:
            timestamp_list = match.group(1).split(":")
            timestamp_in_sec = convert_timestamp_to_seconds(timestamp_list)
            comment_text = match.group(3)
            add_to_sorted_comments_dict(timestamp_in_sec, comment_text)

    metadata_text = generate_metadata_file(sorted_comments)
    with open(metadata_name, "w") as myfile:
        myfile.write(metadata_text)

    merge_chapters_into_new_video_file()
    replace_old_file_with_new()

```

**Comment by pukkandan** [comment]
rather than using the script with `--exec`, you should instead consider embedding `yt_dlp` in your code and using a pre/postprocessor. That way, you can just use `FfmpegMetadataPP` (--add-metadata) to do the actual embedding and only need to have code for comment parsing

**Comment by pukkandan** [comment]
Out of curiosity, how well does this regex work?

> `r"^\s*>?\s?\[?((\d:)?\d{1,2}:\d{1,2})\]?\s?(.*)$"`

**Comment by juligreen** [comment]
I'd say it works well enough.

It does pick up some timestamps without comments though.

Meaning if there's a comment that starts with a timestamp one the first line but the text commenting on the timestamp is on a following line the resulting chapter will have an empty title.

I don't mind that though

**Comment by pukkandan** [comment]
I am closing this as out of scope

If you ever polish this up and release it, let me know. I'll add it to the wiki (which is being worked on)
