### ISSUE TITLE
how to hide warnings in Python?

### ISSUE THREAD

**Issue by 0xF0CACC1A** [yt-dlp/yt-dlp#10089]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

how to hide warnings in python?
I tried with
```
#!/usr/bin/env python3
from yt_dlp import YoutubeDL
url = "https://acdn.ak-stream-videoplatform.sky.it/secure/hls/2024/05/26/928242/master.m3u8?hdnts=st=1717337831~exp=1717338131~acl=/secure/hls/2024/05/26/928242/*~hmac=173bc3f36631ea24fc8ea8040887f4f4ba3d9fa8888f063f797ad3a727b5dcaa"
params = {'downloader' : 'ffmpeg', 'hlsusempegts': True, 'nowarnings' : True, 'quiet': True, 'noprogress': True}
with YoutubeDL(params) as ydl:
    ydl.download(url)
```
but I stll receive
```WARNING: Live HLS streams are not supported by the native downloader. If this is a livestream, please add "--downloader ffmpeg --hls-use-mpegts" to your command```

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by seproDev** [comment]
Don't guess the parameters, but use `devscript/cli_to_api.py`.
It's `'no_warnings': True`, `'hls_use_mpegts': True`, and `'external_downloader': {'default': 'ffmpeg'}`
