### ISSUE TITLE
[Announcement] Dropping support for py2exe builds

### ISSUE THREAD

**Issue by bashonly** [yt-dlp/yt-dlp#10087]
### What Does This Mean?

1. There will be no more py2exe builds (`yt-dlp_min.exe`) included with yt-dlp releases.
2. The `bundle.py2exe` script used for creating py2exe builds of yt-dlp will be removed from the repository.
3. No support will be provided on this tracker for users trying to bundle their own yt-dlp executables with py2exe.

### Why?

1. ~~py2exe appears to be unmaintained. There have been no new commits since October 2023, and several pressing issues have gone unaddressed on the tracker (examples below).~~ **EDIT:** On 2024.07.22 there was a patch release, 0.13.0.2

2. There was recently a [breaking change](https://github.com/psf/requests/commit/eeafb6ab3a54ab01cbf864d452ea30f5fdb67ce8) to `requests` that resulted in it being [withheld from the py2exe builds of yt-dlp](https://github.com/yt-dlp/yt-dlp/commit/db50f19d76c6870a5a13d0cab9287d684fd7449a). This means that these builds now need to use yt-dlp's deprecated `urllib` request handler instead.

3. The entire purpose of having py2exe builds (in addition to pyinstaller builds) is to provide an executable that doesn't need to unpack its contents to disk. This meant using py2exe with a `bundle_files` value of `0`, which prevents libraries such as `pycryptodome` and `certifi` from being bundled properly. These libraries are optional (but useful) dependencies of yt-dlp that are included in all other build variants. Looking ahead, our py2exe builds would also be incapable of supporting `curl_cffi`.

4. py2exe does not support Python >3.11:
	- https://github.com/py2exe/py2exe/issues/191

5. ~~py2exe is incompatible with `setuptools>=70`~~ **EDIT**: This was fixed in the above-mentioned patch release:
	- https://github.com/py2exe/py2exe/issues/208

### When?

The exact date is TBD.

Ideally, py2exe will continue to work for us until [we drop support for Python 3.8 shortly after its end-of-life date has been reached in October 2024](https://github.com/yt-dlp/yt-dlp/issues/10086). Our entire Windows build workflow will need to be re-evaluated at that point since all Win executables are currently built with Python 3.8, so it seems like a logical endpoint for py2exe support as well.

However, unforeseen breakage to our build workflow (e.g. due to the above-mentioned setuptools incompatibility) could necessitate an earlier discontinuation.

### What Do I Need To Do?

The plan is to migrate all py2exe build users to the Windows PyInstaller-bundled executable (`yt-dlp.exe`), so if you are one of those users, you shouldn't need to do anything besides update yt-dlp like usual.

**Comment by stepstreet** [comment]
I presume this is a good time to bring some light to wasm runtimes. With some effort wasm target would make yt-dlp very portable.

**Comment by albertosottile** [comment]
>` py2exe` has never supported `certifi` (which is why `requests` doesn't work with the builds anymore) or `pycryptodome`. 

I tend to agree with the rest of the comments but kinda disagree with this one. `certifi`, `pycryptodome`, and `requests` are part of the CI of `py2exe`, and all these tests have to be pass before each release. Perhaps you use a more aggressive value of `bundle_files` and that's why you are seeing issues with these packages.

**Comment by bashonly** [comment]
@albertosottile Thanks for pointing this out. I was admittedly a bit foggy on the details of why certain things were excluded / not working in our py2exe builds. Indeed, py2exe is capable of bundling `certifi`/`pycryptodome`/`requests`. And we do use `bundle_files` value of `0`, which is why *our builds* can't support those libraries. The main reason why py2exe builds are offered here is to provide a Windows executable that doesn't need to unpack its contents, so AFAICT using any `bundle_files` value other than `0` would defeat the purpose of these builds.

I have edited point number 3 in the announcement to clarify this, and I apologize for misrepresenting py2exe and misinforming readers of this post.

**Comment by albertosottile** [comment]
Thanks for addressing this. I now understand your reasoning behind PyInstaller since, from your edit, it seems you are aware that PyInstaller indeed unpacks everything to disk at every execution.
