### ISSUE TITLE
How to get youtube topic json list like "https://www.youtube.com/hashtag/marriage/shorts"

### ISSUE THREAD

**Issue by kaixuangh** [yt-dlp/yt-dlp#10100]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

yt-dlp --dump-json "https://www.youtube.com/hashtag/marriage/shorts" > shorts_videos.json

/Users/kaixuan/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
WARNING: [youtube:tab] YouTube said: ERROR - Internal error encountered.
WARNING: [youtube:tab] HTTP Error 500: Internal Server Error. Retrying (1/3)...
WARNING: [youtube:tab] YouTube said: ERROR - Internal error encountered.
WARNING: [youtube:tab] HTTP Error 500: Internal Server Error. Retrying (2/3)...
WARNING: [youtube:tab] YouTube said: ERROR - Internal error encountered.
WARNING: [youtube:tab] HTTP Error 500: Internal Server Error. Retrying (3/3)...
WARNING: [youtube:tab] YouTube said: ERROR - Internal error encountered.
ERROR: Unable to download API page: HTTP Error 500: Internal Server Error (caused by <HTTPError 500: Internal Server Error>)

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
Your probably want to use `--dump-single-json`, and maybe also `--flat-playlist`

I can't reproduce the errors. You'll need to show a **complete** verbose log if you want to troubleshoot those
