### ISSUE TITLE
[NhkRadiru] Unable to download JSON metadata: HTTP Error 404 / NHK

### ISSUE THREAD

**Issue by scineram** [yt-dlp/yt-dlp#10105]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Provide a description that is worded well enough to be understood

I cannot download the program `www.nhk.or.jp/radio/player/ondemand.html?p=7413_01_4008048`. But when I want to save a live stream such as `www.nhk.or.jp/radio/player/?ch=fm` or `www.nhk.or.jp/radio/player/?ch=r2` it works. About a month ago I was able to download a different program `https://www.nhk.or.jp/radio/ondemand/detail.html?p=8748_01` when it was still available on demand. See below for error output.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'www.nhk.or.jp/radio/player/ondemand.html?p=7413_01_4008048']
[debug] User config "/root/yt-dlp.conf": ['--merge-output-format', 'mkv', '--embed-metadata', '--embed-thumbnail', '--parse-metadata', 'description:(?s)(?P<meta_comment>.+)', '--parse-metadata', 'uploader_id:(?s)(?P<meta_description>.+)', '--parse-metadata', ':(?P<meta_synopsis>)', '--parse-metadata', 'playlist_id:(?s)(?P<meta_playlist_id>.+)', '--parse-metadata', 'playlist_title:(?s)(?P<meta_playlist_title>.+)', '--parse-metadata', 'view_count:(?s)(?P<meta_view_count>.+)', '-o', '%(uploader)s/%(title)s [%(id)s].%(ext)s', '-S', 'res,fps,vcodec:av1', '--video-multistreams', '--audio-multistreams', '--embed-subs', '--sub-langs', 'all,-live_chat', '--cookies', 'cookies.txT']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.05.27 from yt-dlp/yt-dlp [12b248ce6]
[debug] Python 3.11.9 (CPython amd64 64bit) - FreeBSD-13.1-RELEASE-p9-amd64-64bit-ELF (OpenSSL 1.1.1t-freebsd  7 Feb 2023, libc 7)
[debug] exe versions: ffmpeg 6.1.1 (setts), ffprobe 6.1.1
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.02.02, mutagen-1.47.0, requests-2.32.2, sqlite3-3.45.1, urllib3-1.26.18, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1820 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.05.27 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.05.27 from yt-dlp/yt-dlp)
[generic] Extracting URL: www.nhk.or.jp/radio/player/ondemand.html?p=7413_01_4008048
WARNING: [generic] The url doesn't specify the protocol, trying with http
[debug] Using fake IP 133.88.173.27 (JP) as X-Forwarded-For
[NhkRadiru] Downloading API config
[NhkRadiru] Extracting URL: http://www.nhk.or.jp/radio/player/ondemand.html?p=7413_01_4008048
[NhkRadiru] 7413_01: Downloading JSON metadata
ERROR: [NhkRadiru] Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: Not Found>)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 734, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/nhk.py", line 714, in _real_extract
    meta = self._download_json(json_url, programme_id)['main']
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 1133, in download_content
    res = getattr(self, download_handle.__name__)(url_or_request, video_id, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 1093, in download_handle
    res = self._download_webpage_handle(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 954, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 903, in _request_webpage
    raise ExtractorError(errmsg, cause=err)

  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 890, in _request_webpage
    return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query, extensions))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 4142, in urlopen
    return self._request_director.send(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/yt-dlp/yt_dlp/networking/common.py", line 117, in send
    response = handler.send(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/yt-dlp/yt_dlp/networking/_helper.py", line 208, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/yt-dlp/yt_dlp/networking/common.py", line 337, in send
    return self._send(request)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/yt-dlp/yt_dlp/networking/_requests.py", line 366, in _send
    raise HTTPError(res, redirect_loop=max_redirects_exceeded)
yt_dlp.networking.exceptions.HTTPError: HTTP Error 404: Not Found
```

**Comment by bashonly** [comment]
cc @garret1317

**Comment by garret1317** [comment]
thanks for the ping bashonly

i noticed that they'd switched to a new API on the website a week or so ago, so I've actually aready got a patch mostly-ready
just didn't see the point of getting it merged when the old one still worked, perhaps that was unwise of me...
give me a bit to clean it up and i'll try get a PR in soonish

**Comment by scineram** [comment]
Can I download the content in another way while this is worked on?

**Comment by garret1317** [comment]
you could clone/download [the branch](https://github.com/garret1317/yt-dlp/tree/nhk-radiru-new-metadata) and run yt-dlp from there with the sh/cmd, or possibly with `python -m yt_dlp` in the directory(?)

**Comment by scineram** [comment]
Thanks. I was able to checkout your branch and download the program as well as the next episode.

**Comment by JLO64** [comment]
> you could clone/download [the branch](https://github.com/garret1317/yt-dlp/tree/nhk-radiru-new-metadata) and run yt-dlp from there with the sh/cmd that's what i do for testing at least

Can confirm it worked. That said, is it just me or are the download speeds slower than before? I can't really compare since I run it from a cron job.

**Comment by garret1317** [comment]
> That said, is it just me or are the download speeds slower than before? I can't really compare since I run it from a cron job.

Seems the same as normal to me, though like you I don't have any way to compare as I don't keep logs.
FWIW the patch doesn't add any new requests, only changes one. And the fragments seem to still be served from a local Akamai presence as normal, with the same length and bitrate.
A tip, if you're not already doing it: I like to use multi-threaded download with `-N`, it makes it much faster. I usually set it to 10, and that gets it "fast enough" for my needs (~800K/s, which mostly saturates my connection- a 2 hour programme downloads in just under a minute).

**Comment by garret1317** [comment]
@scineram @JLO64 the fix has been merged, so you should be able to run `yt-dlp --update-to nightly` and use it in the normal way now :+1:
