### ISSUE TITLE
Rutube playlist fails

### ISSUE THREAD

**Issue by swordsman379** [yt-dlp/yt-dlp#10104]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Russia

### Provide a description that is worded well enough to be understood

Trying to load playlist from Rutube, but yt-dlp fails - says `Unsupported URL`, however in documentation rutube playlists are supported.
My cmd is 
`yt-dlp.exe -vU --flat-playlist http://rutube.ru/plst/308547/`

Nothing changes if I try to force with `--use-extractors rutube:playlist`

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--flat-playlist', 'http://rutube.ru/plst/308547/']
[debug] Encodings: locale cp1251, fs utf-8, pref cp1251, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.05.27 from yt-dlp/yt-dlp [12b248ce6] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-114162-g2129d66a66-20240314 (setts), ffprobe N-114162-g2129d66a66-20240314
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.02.02, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.2, sqlite3-3.35.5, urllib3-2.2.1, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1820 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.05.27 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.05.27 from yt-dlp/yt-dlp)
[generic] Extracting URL: http://rutube.ru/plst/308547/
[generic] 308547: Downloading webpage
[redirect] Following redirect to https://rutube.ru/plst/308547/
[generic] Extracting URL: https://rutube.ru/plst/308547/
[generic] 308547: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] 308547: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://rutube.ru/plst/308547/
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1606, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1741, in __extract_info
  File "yt_dlp\extractor\common.py", line 734, in extract
  File "yt_dlp\extractor\generic.py", line 2514, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://rutube.ru/plst/308547/
```

**Comment by bashonly** [comment]
URL format changed. This fixes it, but there's a probably a better/cleaner way to do it:

```diff
diff --git a/yt_dlp/extractor/rutube.py b/yt_dlp/extractor/rutube.py
index eb12f32fa..9373de284 100644
--- a/yt_dlp/extractor/rutube.py
+++ b/yt_dlp/extractor/rutube.py
@@ -317,7 +317,7 @@ class RutubePersonIE(RutubePlaylistBaseIE):
 class RutubePlaylistIE(RutubePlaylistBaseIE):
     IE_NAME = 'rutube:playlist'
     IE_DESC = 'Rutube playlists'
-    _VALID_URL = r'https?://rutube\.ru/(?:video|(?:play/)?embed)/[\da-z]{32}/\?.*?\bpl_id=(?P<id>\d+)'
+    _VALID_URL = r'https?://rutube\.ru/(?:(?P<plst>plst)/|(?:video|(?:play/)?embed)/[\da-z]{32}/\?.*?\bpl_id=)(?P<id>\d+)'
     _TESTS = [{
         'url': 'https://rutube.ru/video/cecd58ed7d531fc0f3d795d51cee9026/?pl_id=3097&pl_type=tag',
         'info_dict': {
@@ -337,6 +337,8 @@ def suitable(cls, url):
 
         if not super(RutubePlaylistIE, cls).suitable(url):
             return False
+        elif cls._match_valid_url(url).group('plst'):
+            return True
         params = parse_qs(url)
         return params.get('pl_type', [None])[0] and int_or_none(params.get('pl_id', [None])[0])
 
@@ -344,9 +346,13 @@ def _next_page_url(self, page_num, playlist_id, item_kind):
         return self._PAGE_TEMPLATE % (item_kind, playlist_id, page_num)
 
     def _real_extract(self, url):
-        qs = parse_qs(url)
-        playlist_kind = qs['pl_type'][0]
-        playlist_id = qs['pl_id'][0]
+        playlist_id, is_playlist = self._match_valid_url(url).group('id', 'plst')
+        if is_playlist:
+            playlist_kind = 'playlist'
+        else:
+            qs = parse_qs(url)
+            playlist_kind = qs['pl_type'][0]
+            playlist_id = qs['pl_id'][0]
         return self._extract_playlist(playlist_id, item_kind=playlist_kind)
 
 
```

**Comment by swordsman379** [comment]
Ok, I've got it.
But would the patch be integrated to YT-dpl?

**Comment by annalhq** [comment]
> Ok, I've got it. But would the patch be integrated to YT-dpl?

I am still unable to download rutube playlist using yt-dlp, how you managed to download that?

**Comment by swordsman379** [comment]
with that .py I can download playlist from https://rutube.ru/plst/308547/
The only thing with it - it's in reverse order

сб, 17 авг. 2024 г. в 22:01, Annalhq ***@***.***>:

**Comment by bashonly** [comment]
Anyone is free to open a PR with the above patch. Due to some refactoring / changes to `rutube.py` since the patch was originally posted, it may no longer cleanly apply and you'll have to manually make the changes. Test(s) will also need to be added/updated

**Comment by Rnr12345** [comment]
> Ok, I've got it. But would the patch be integrated to YT-dpl?
Hi, can you answer, how you did it? Still can't resolve it. If u can - please, answer to mail: w84work@gmail.com
