### ISSUE TITLE
`--retries infinite` doesn't retry infinitely

### ISSUE THREAD

**Issue by playgithub** [yt-dlp/yt-dlp#10109]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

`--retries infinite` doesn't retry infinitely, but quite when `HTTP Error 403: Forbidden`

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[youtube] KMiIbOkP4yU: Downloading ios player API JSON
[youtube] KMiIbOkP4yU: Downloading player 4b63a6a1
[youtube] KMiIbOkP4yU: Downloading m3u8 information
[info] KMiIbOkP4yU: Downloading 1 format(s): 299+251
[info] There are no subtitles for the requested languages
[download] Destination: 2024-06-04.【マリオカート８ デラックス】.f299.mp4
[download]   3.6% of    5.57GiB at  391.87KiB/s ETA 03:59:41[download] Got error: 7061361 bytes read, 95324895 more expected. Retrying (1/inf)...
Sleeping 3.00 seconds ...
[download] Destination: 2024-06-04.【マリオカート８ デラックス】.f299.mp4
[download]  39.0% of    5.57GiB at  135.69KiB/s ETA 07:18:17[download] Got error: SocksHTTPSConnectionPool(host='rr2---sn-5hne6nzs.googlevideo.com', port=443): Read timed out.. Retrying (2/inf)...
Sleeping 3.00 seconds ...
[download] Destination: 2024-06-04.【マリオカート８ デラックス】.f299.mp4
[download]  41.4% of    5.57GiB at  181.42KiB/s ETA 05:14:52[download] Got error: SocksHTTPSConnectionPool(host='rr2---sn-5hne6nzs.googlevideo.com', port=443): Read timed out.. Retrying (3/inf)...
Sleeping 3.00 seconds ...
[download] Destination: 2024-06-04.【マリオカート８ デラックス】.f299.mp4
[download]  95.6% of    5.57GiB at  336.92KiB/s ETA 12:37ERROR: unable to download video data: HTTP Error 403: Forbidden
```

**Comment by dirkf** [comment]
Only potentially transient errors are retried. RFC 9110 tells you this:
> 15.5.4. 403 Forbidden
>
>The 403 (Forbidden) status code indicates that the server understood the request but refuses to fulfill it. ... The client SHOULD NOT automatically repeat the request with the same credentials. ...

In reality, sites abuse 403 by sending it instead of eg 429 or just because they don't like the look of your face. But that can't be treated as the general case, only something that you can address manually.

**Comment by playgithub** [comment]
I'm using `yt-dlp` with a proxy, and the proxy is not very stable,  it makes sense to retry blindly.
Maybe a shell script is needed.
