### ISSUE TITLE
 Download videos in multiple streams

### ISSUE THREAD

**Issue by qo4on** [yt-dlp/yt-dlp#10111]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I used to use `-n 12` to load video in 12 streams simultaneously, which was significantly faster. Now my usual command that has always worked gives an error:
`yt-dlp --live-from-start --wait-for-video 300 -n 12 --hls-use-mpegts --retries 20 --continue https://www.youtube.com/@.../live -o “0.%(ext)s”`
`ERROR: [generic] '12' is not a valid URL. Set --default-search “ytsearch” (or run yt-dlp “ytsearch:12” ) to search YouTube `
How to download videos in multiple streams now?

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
uppercase `-N`

**Comment by bashonly** [comment]
BTW, if your `-N` value is set too high you'll start getting 401/403 errors with `--live-from-start`. I wouldn't go higher than 4

**Comment by 3a2n** [comment]
Is there a fix for this?
```
yt-dlp --no-live-from-start https://www.youtube.com/watch?v=.... -o "0.%(ext)s"
ERROR: Unable to download video: [WinError 2] The system cannot find the file specified: '0.mp4.part'
```

**Comment by bashonly** [comment]
@3a2n please open a new issue and include complete verbose output
