### ISSUE TITLE
[propose Update pakage] Fedora and Epel

### ISSUE THREAD

**Issue by andykimpe** [yt-dlp/yt-dlp#10118]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

[propose Update pakage] Fedora and Epel Update

I propose an update of yt-dlp for fedora and epel

I am therefore opening this discussion to allow those who wish to react and provide their opinion on this proposed update.

Fedora Rawhide

https://src.fedoraproject.org/rpms/yt-dlp/pull-request/16

Main

https://src.fedoraproject.org/rpms/yt-dlp/pull-request/17

Fedora 40

https://src.fedoraproject.org/rpms/yt-dlp/pull-request/18

Fedora 39

https://src.fedoraproject.org/rpms/yt-dlp/pull-request/19

Epel 9

https://src.fedoraproject.org/rpms/yt-dlp/pull-request/20

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by Grub4K** [comment]
What does this have to do with this repisitory? We do not provide the fedora packages, shouldnt this issue be opened at some fedora repo instead?

**Comment by andykimpe** [comment]
indeed but not everyone necessarily has a developer account it's fedora

while many have a github account

the goal is to allow everyone to contribute their opinion

and also allows you to see if this proposal is suitable

Fedora and a community distribution for their developers, the opinion of the community is therefore extremely important

also Fedora makes the mistake of continuing to maintain youtube-dl and yt-dlp while youtube-dl and obsolete

without keeping yt-dlp up to date on epel

the current version on epel dates from 2023

**Comment by rdamas** [comment]
Doesn't change anything, packaging is up to the distibution maintainers.
https://github.com/yt-dlp/yt-dlp/wiki/Installation#third-party-package-managers

**Comment by andykimpe** [comment]
but there is nothing to change here

I didn't ask to make any changes to the project

but on Fedora's package management system

I only opened a discussion to allow the community to give their opinion, that's all.

in other words already here you are not from the Fedora community

There is no need for you to respond to this discussion

the only thing that could strictly be changed on the project

it's to modify the wiki that you just gave

to add information for Fedora and RHEL



DNF

for RHEL and fork install EPEL Repository

https://docs.fedoraproject.org/en-US/epel/

for Fedora and RHEL install with dnf
`
sudo dnf install yt-dlp`

**Comment by bashonly** [comment]
My two cents:

**Get rid of the `youtube-dl` symlink**. This will only confuse users. The two projects are not equivalent.

> the only thing that could strictly be changed on the project
> it's to modify the wiki that you just gave

You could [open a PR against the wiki](https://github.com/yt-dlp/yt-dlp-wiki/compare) if you want to add Fedora/RHEL installation instructions

**Comment by andykimpe** [comment]
well finally this post is indeed useful, you have just opened an important debate

you indicate that the projects are not equivalent

there are indeed additional options in yt-dlp

but all the options that were available in youtube-dl

are available in yt-dlp without execetion

some options were actually removed from the --help function display and were noted as obsolete

but when I asked the question they told me that this option remains working and that compatibility with the old youtube-dl options would still be guaranteed

so what reason would this no longer be the case

there is no explanation on this subject

one day they said one thing and the next day (so to speak)

have said the opposite, there is a false explanation on this subject

for the wiki I didn't see that it was a different project

but hey I said that as just that so that in the code itself

there is nothing to correct although given what you say

it still remains to be seen

after seeing that 99.9% of people who are RHEL

installed epel by default and that in general have known

the name of the package manager of its distribution

it is not necessarily necessary to indicate it

**Comment by seproDev** [comment]
Differences in default behaviour to youtube-dl are listed here: <https://github.com/yt-dlp/yt-dlp?tab=readme-ov-file#differences-in-default-behavior>

**Comment by bashonly** [comment]
yt-dlp is a fork, not a successor. yt-dlp strives for compatibility with youtube-dl, but it's not always possible, and there are some significant differences in default behavior between the two programs (as sepro linked above.)

It is misleading to "replace" youtube-dl with yt-dlp, IMO. It is not the same package with a different name; it is an entirely different program. I think "replacing" youtube-dl with yt-dlp and adding the symlink is extremely misguided.

**Comment by andykimpe** [comment]
python 3.8 I hadn't seen it, it's overkill

there are Linux distribution versions that have support

in the very long term it can go up to 10 years of support

and some companies pay to extend this support for an additional 3 years

we must therefore take it into account and continue to maintain

an up-to-date version of the project of course but which remains compatible

with the distributions concern this is not the case suddenly

Maybe on the distribution in question I am thinking of RHEL 8.10

the version of python is 3.6.8 patch 62 and the basic support is until 2029 which gives 2032 on extended support

there are companies that need this support in the long term

and who even pays to have this one and who needs to use

on the distributions in question yt-dlp

**Comment by seproDev** [comment]
yt-dlp aligns with the official support for Python versions. In fact, 3.8 support will be dropped in a couple of months when 3.8 no longer receives security updates. See: https://github.com/yt-dlp/yt-dlp/issues/10086

Support for older python versions will not be restored. yt-dlp will not support Python versions over their official support window.
This is standard practice for Python projects. If yt-dlp didn't do this, we would quickly run in to problems with the dependencies we use.

If you run an outdated distro that can't use recent Python versions, you are advised to use the static Linux builds instead.

**Comment by andykimpe** [comment]
so I already see for RHEL 8 it would be necessary to make a package in scl (Software CoLlections) for compatibility there is already python38 and python3.9 in scl

on the other hand RED HAT will probably not publish a version higher than python 3.9

given that development was stopped on May 31, 2024

when the development of CentOS Stream 8 was stopped

only security updates will be published

so even in scl there will be no new version of python 3

it will rather be there especially since it will pose a problem

this also explains why Fedora only put RHEL 9 on epel

without putting RHEL 8 since at their level it does not create and does not use the scl

taking this into account finally edit the wiki

would be necessary I think

I gave you a thumbs up too because you're not wrong

but the distributions which offer this Very Long Term Support (VLTS)

Extended Life-cycle Support (ELS) for RHEL

Expanded Security Maintenance (ESM) for Ubuntu

ESU (Extended Security Update) for Windows

don't think about that
