### ISSUE TITLE
Video is downloaded with different audio language as played in the browser

### ISSUE THREAD

**Issue by arminfuerst** [yt-dlp/yt-dlp#10113]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Germany

### Provide a description that is worded well enough to be understood

This video will be available until July 5th, after this, the links provided will not work anymore.
The German TV station "One" provides some videos in German and English with different links. There is one episode of "Miss Marple" where the download of both links results in a video with the German audio stream while playing the same link in the browser plays the English audio.
1. Working example (1x09)
1a. German: https://www.ardmediathek.de/video/miss-marple/folge-9-das-geheimnis-der-goldmine-teil-1-s01-e09/one/Y3JpZDovL3dkci5kZS9CZWl0cmFnLXNvcGhvcmEtNWJkYjI1MmQtNzIwMS00Y2NkLWI1NTMtZGVhMGU2YTY5MTVl
1b. English: https://www.ardmediathek.de/video/miss-marple/folge-9-das-geheimnis-der-goldmine-teil-1-s01-e09-originalversion/one/Y3JpZDovL3dkci5kZS9CZWl0cmFnLXNvcGhvcmEtY2U3OTcwYjctZDRhZi00NDA5LWFjYWEtOWQyYjg1NTYwZDUz
2. Broken example (1x10)
2a. German: https://www.ardmediathek.de/video/miss-marple/folge-10-das-geheimnis-der-goldmine-teil-2-s01-e10/one/Y3JpZDovL3dkci5kZS9CZWl0cmFnLXNvcGhvcmEtYzc1YmRiY2EtMDMyYi00YTE4LWEzY2MtZDJhNjM3NzliMzlm
2b. English: https://www.ardmediathek.de/video/miss-marple/folge-10-das-geheimnis-der-goldmine-teil-2-s01-e10-originalversion/one/Y3JpZDovL3dkci5kZS9CZWl0cmFnLXNvcGhvcmEtMGU0NzU2NjgtNWY0NS00NjNkLThkNDUtYjZmZjhiY2FjMTRj

Downloading 1a results in a video with German audio -> OK
Downloading 1b results in a video with English audio -> OK
Downloading 2a results in a video with German audio -> OK
Downloading 2b results in a video with German audio -> BROKEN, should be English. 

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp -vU https://www.ardmediathek.de/video/miss-marple/folge-10-das-geheimnis-der-goldmine-teil-2-s01-e10-originalversion/one/Y3JpZDovL3dkci5kZS9CZWl0cmFnLXNvcGhvcmEtMGU0NzU2NjgtNWY0NS00NjNkLThkNDUtYjZmZjhiY2FjMTRj
[debug] Command-line config: ['-vU', 'https://www.ardmediathek.de/video/miss-marple/folge-10-das-geheimnis-der-goldmine-teil-2-s01-e10-originalversion/one/Y3JpZDovL3dkci5kZS9CZWl0cmFnLXNvcGhvcmEtMGU0NzU2NjgtNWY0NS00NjNkLThkNDUtYjZmZjhiY2FjMTRj']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.06.01.232725 from yt-dlp/yt-dlp-nightly-builds [db50f19d7] (zip)
[debug] Python 3.11.2 (CPython x86_64 64bit) - Linux-6.1.0-21-amd64-x86_64-with-glibc2.36 (OpenSSL 3.0.11 19 Sep 2023, glibc 2.36)
[debug] exe versions: ffmpeg 6.0.1 (fdk,setts), ffprobe 6.0.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.11.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.46.0, pyxattr-0.8.1, requests-2.28.1, secretstorage-3.3.3, sqlite3-3.40.1, urllib3-1.26.12, websockets-10.4
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Loaded 1820 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.06.01.232725 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.06.01.232725 from yt-dlp/yt-dlp-nightly-builds)
[debug] Using fake IP 53.193.22.82 (DE) as X-Forwarded-For
[ARDMediathek] Extracting URL: https://www.ardmediathek.de/video/miss-marple/folge-10-das-geheimnis-der-goldmine-teil-2-s01-e10-originalversion/one/Y3JpZDovL3dkci5kZS9CZWl0cmFnLXNvcGhvcmEtMGU0NzU2NjgtNWY0NS00NjNkLThkNDUtYjZmZjhiY2FjMTRj
[ARDMediathek] Y3JpZDovL3dkci5kZS9CZWl0cmFnLXNvcGhvcmEtMGU0NzU2NjgtNWY0NS00NjNkLThkNDUtYjZmZjhiY2FjMTRj: Downloading JSON metadata
[ARDMediathek] 13427897: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 13427897: Downloading 1 format(s): hls-main-3982
[debug] Invoking hlsnative downloader on "https://wdrvod-rwrtr.akamaized.net/i/,/medp/ondemand/de/fsk6/312/3121929/,3121929_57528767,3121929_57528768,3121929_57528766,3121929_57528769,3121929_57528765,.mp4.csmil/index-f5-v1-a1.m3u8"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 372
[download] Destination: Folge 10： Das Geheimnis der Goldmine - Teil 2 (S01⧸E10) - (Originalversion) [13427897].mp4
[download] 100% of    1.42GiB in 00:02:55 at 8.29MiB/s
[debug] ffprobe command line: ffprobe -hide_banner -show_format -show_streams -print_format json 'file:Folge 10： Das Geheimnis der Goldmine - Teil 2 (S01⧸E10) - (Originalversion) [13427897].mp4'
[debug] ffmpeg command line: ffprobe -show_streams 'file:Folge 10： Das Geheimnis der Goldmine - Teil 2 (S01⧸E10) - (Originalversion) [13427897].mp4'
[FixupM3u8] Fixing MPEG-TS in MP4 container of "Folge 10： Das Geheimnis der Goldmine - Teil 2 (S01⧸E10) - (Originalversion) [13427897].mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:Folge 10： Das Geheimnis der Goldmine - Teil 2 (S01⧸E10) - (Originalversion) [13427897].mp4' -map 0 -dn -ignore_unknown -c copy -f mp4 -bsf:a aac_adtstoasc -movflags +faststart 'file:Folge 10： Das Geheimnis der Goldmine - Teil 2 (S01⧸E10) - (Originalversion) [13427897].temp.mp4'
```

**Comment by seproDev** [comment]
Does the video actually play back in English on the website?

**Comment by arminfuerst** [comment]
> Does the video actually play back in English on the website? For me it plays the German audio.

It played back the English audio in my browser.

**Comment by seproDev** [comment]
Oh, I think it depends on the resolution. Full HD and SD play German Audio, while SD 480p and HD-Ready play English audio.

**Comment by arminfuerst** [comment]
I see - so it seems like the site itself is inconsistent...

**Comment by seproDev** [comment]
Yeah, this is an external issue. yt-dlp just gets the files as provided by the site. To work around this, I would download both the Full HD and HD-Ready formats and then with FFmpeg manually combine the streams you want to keep. I think this should be the command:
```
ffmpeg -i fullhd.mp4 -i hdready.mp4 -map 0:v -map 1:a -c copy combined.mp4
```

**Comment by arminfuerst** [comment]
I suggest to close this issue - or would there be any benefit keeping it open?

**Comment by seproDev** [comment]
Yeah, I think there is nothing for us to do here. If someone wants, they can send ARD a message that their encoding pipeline probably has a bug lol
