### ISSUE TITLE
Crunchyroll extractor tries to download jp audio when passing en language format

### ISSUE THREAD

**Issue by YewTreeWeb** [yt-dlp/yt-dlp#10117]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

UK

### Provide a description that is worded well enough to be understood

When downloading a season from Crunchyroll such as https://www.crunchyroll.com/series/GRZJ7QN86/snow-white-with-the-red-hair and passing `-f bv+ba[language*=en]` or `--format bv+ba[language*=en]` the extractor tries to download the Japanese audio first which fails. The English dub does eventually download but yt-dlp finishes with an error due to the failed attempts for the JP audio. Using the link as an example yt-dlp should show 'Downloading 1 of 24' but instead shows 'Downloading 1 of 48'. Once yt-dlp gets to 25 it then starts downloading the episodes.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[download] Downloading item 1 of 48
[crunchyroll] Extracting URL: https://www.crunchyroll.com/watch/G6QWJPGG6
[crunchyroll] G6QWJPGG6: Downloading object info JSON (cms)
[crunchyroll] G6QWJPGG6: Downloading stream info
[crunchyroll] Available hardsub languages: en-US, es-419, pt-BR
[crunchyroll] To extract formats of a hardsub language, use "--extractor-args crunchyrollbeta:hardsub=<language_code or all>". See https://github.com/yt-dlp/yt-dlp#crunchyrollbeta-crunchyroll for more info
[crunchyroll] G6QWJPGG6: Downloading MPD manifest
[crunchyroll] G6QWJPGG6: Invalidating stream token
[crunchyroll] G6QWJPGG6: Downloading chapter info
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
ERROR: [crunchyroll] G6QWJPGG6: Requested format is not available. Use --list-formats for a list of available formats
Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1606, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1762, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1821, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 2955, in process_video_result
    raise ExtractorError(
yt_dlp.utils.ExtractorError: [crunchyroll] G6QWJPGG6: Requested format is not available. Use --list-formats for a list of available formats
```

**Comment by Grub4K** [comment]
This is expected behavior.

A season contains its language variants, so it will try to download every episode of all languages. Since you specified only english audio formats to be downloaded, the requirement fails for episodes of other languages, and an error is thrown.

Use `--match-filters language*=en` to filter the season episode results by language first. Also relevant: #10067

**Comment by october262** [comment]
try this and see if this'll work - yt-dlp --match-title "(english dub)" "https://www.crunchyroll.com/series/GRZJ7QN86/snow-white-with-the-red-hair"
