### ISSUE TITLE
New feature: VTT subtitles to include source URI

### ISSUE THREAD

**Issue by globalcitizen** [yt-dlp/yt-dlp#10126]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

I would like the **vtt** format subtitle/caption output file to include a header that includes the original URL.

Currently the header looks like this:
```
WEBVTT
Kind: captions
Language: en
```

Ideally it should look like this:
```
WEBVTT
Kind: captions
Language: en
URI: https://www.youtube.com/watch?v=2Qz48BZ2HMc
```

The reason for this is that I wish to post-process the output in order to generate links from the transcript/subtitles/caption to the specific portion of video. Currently, the timing information is included and adequate, however the original URI is not included. While I can work around this problem it strikes me as a good feature to have in the output.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--write-auto-sub', '--skip-download', '--sub-lang', 'en', '--sub-format', 'vtt', 'https://www.youtube.com/watch?v=2Qz48BZ2HMc']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version local@2024.06.06.1 [db50f19d7]
[debug] Python 3.12.3 (CPython x86_64 64bit) - Linux-6.6.30-gentoo-dist-x86_64-12th_Gen_Intel-R-_Core-TM-_i5-12400F-with-glibc2.39 (OpenSSL 3.0.13 30 Jan 2024, glibc 2.39)
[debug] exe versions: ffmpeg 6.1.1 (setts), ffprobe 6.1.1
[debug] Optional libraries: certifi-3021.03.16, pycrypto-3.20.0, requests-2.32.1, sqlite3-3.45.3, urllib3-2.2.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Loaded 1820 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.05.27 from yt-dlp/yt-dlp
yt-dlp is up to date (local@2024.06.06.1)
[youtube] Extracting URL: https://www.youtube.com/watch?v=2Qz48BZ2HMc
[youtube] 2Qz48BZ2HMc: Downloading webpage
[youtube] 2Qz48BZ2HMc: Downloading ios player API JSON
[debug] Loading youtube-nsig.e056da8e from cache
[debug] [youtube] Decrypted nsig t72EE214rnW8_KUs => bP_jOdB0FW1KSg
[debug] Loading youtube-nsig.e056da8e from cache
[debug] [youtube] Decrypted nsig FxwGxXgP9iCnBOif => MkxMgfWUD1pbCg
[youtube] 2Qz48BZ2HMc: Downloading m3u8 information
[info] 2Qz48BZ2HMc: Downloading subtitles: en
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 2Qz48BZ2HMc: Downloading 1 format(s): 313+251
Deleting existing file Drone Delivery Fireside Chat @ Santa Monica Airport! [2Qz48BZ2HMc].en.vtt
[info] Writing video subtitles to: Drone Delivery Fireside Chat @ Santa Monica Airport! [2Qz48BZ2HMc].en.vtt
[debug] Invoking http downloader on "https://www.youtube.com/api/timedtext?v=2Qz48BZ2HMc&ei=BiNiZqS1K-W0rtoPkaym4AY&caps=asr&opi=112496729&xoaf=5&hl=en&ip=0.0.0.0&ipbits=0&expire=1717732726&sparams=ip%2Cipbits%2Cexpire%2Cv%2Cei%2Ccaps%2Copi%2Cxoaf&signature=AF5C385713EF0E14D3A29BBA74343D32A36C2F82.4A86B5996E563427A96D555E0AE8E729086AC0B7&key=yt8&kind=asr&lang=en&fmt=vtt"
[download] Destination: Drone Delivery Fireside Chat @ Santa Monica Airport! [2Qz48BZ2HMc].en.vtt
[download] 100% of  305.70KiB in 00:00:00 at 614.28KiB/s
```

**Comment by dirkf** [comment]
The VTT file conforms to a [standard](https://developer.mozilla.org/en-US/docs/Web/API/WebVTT_API) that doesn't allow what you suggest.

The linked URI could be included as a comment of known conventional format, but would have to be escaped (eg, `&` characters).

The specification allows for more or less general text to follow the keyword `WEBVTT` on the header line, but there may be tools and especially user scripts that would fail if a URI were placed there by default. You could massage the standard header, say with a _sed_ 1-liner, in your own workflow.

**Comment by bashonly** [comment]
As dirkf said, this is against webvtt spec, and also yt-dlp just downloads exactly what yt-dlp serves; it doesn't modify it unless you tell it to convert the subs into a different format. This is out-of-scope, but could easily be done with a plugin
