### ISSUE TITLE
Youtube Metadata Chapters and Description

### ISSUE THREAD

**Issue by VisualNodeLLC** [yt-dlp/yt-dlp#10138]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

I'm a student, and it's part of my assignment to make this question. The question is real, though: Is it possible to download chapter information and other metadata associated with videos and audios. Is it possible to download all metadata associated? Thanks!

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by seproDev** [comment]
Yes, chapter data and other metadata like the description is available for YouTube.
Take a look at the output template section of the README: https://github.com/yt-dlp/yt-dlp?tab=readme-ov-file#output-template
Do note that depending on the site, not all metadata may be available. To see all available metadata, I would dump the info json. You can use `-j` / `--write-info-json` for that.

**Comment by bashonly** [comment]
Also, if you want to embed chapters into the video itself, use `--embed-chapters`
