### ISSUE TITLE
Output issue: "s was unexpected at this time."

### ISSUE THREAD

**Issue by jamesdeluk** [yt-dlp/yt-dlp#10131]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

I've just started having an error relating to outputs. Example:
```
> yt-dlp TEXh6W7szh0 -o "%(title)s.%(ext)s"
s was unexpected at this time.
```
This worked until a couple of days ago. I upgraded from 2024.4.9 to 2024.5.27 today, which was when I first noticed this issue, but downgrading hasn't fixed the issue.

Interestingly,
```
> yt-dlp TEXh6W7szh0 -o "%(title)s [%(id)s].%(ext)s"
```
downloads `(id)s].(ext)s.webm`

I played around with escaping:
```
> yt-dlp TEXh6W7szh0 -o "%%(title)%s.%%(ext)%s"
s was unexpected at this time.
> yt-dlp TEXh6W7szh0 -o '%(title)s.%(ext)s'
s was unexpected at this time.
> yt-dlp TEXh6W7szh0 -o "`%(title)`s.`%(ext)`s"
s was unexpected at this time.
> yt-dlp TEXh6W7szh0 -o "%%(title)s.%%(ext)s"
s.%(ext was unexpected at this time.
```
and
`> yt-dlp TEXh6W7szh0 -o "%(title)%s.%(ext)%s"`
downloads `s.s.webm`

This also happens for non-YouTube sites, and providing the full URL, including in quotes.

Without `-o` it downloads with the standard filename format.

Windows 11, tried PowerShell and Cmd.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
Can't provide, as `s was unexpected at this time.` seems to come from Windows, not yt-dlp.
```

**Comment by bashonly** [comment]
Are you writing a batch file / .cmd script? Or are you entering these commands directly into your terminal?

If you are writing a batch file, you need to double the `%`s in the output template or else cmd attempts variable expansion

**Comment by jamesdeluk** [comment]
I've tried both; the commands above were directly into the terminal.

The `.cmd` script uses `%%`s:
```
set /p video_id=Video: 
yt-dlp -f 140,22 %video_id% -o "%%(title)s [%%(id)s] %%(upload_date>%%Y%%m%%d)s.%%(ext)s"
```
Which creates `(id)s] Yd)s.(ext)s` (but only the `140`, as when it starts `22`, it thinks it already exists).

**Comment by bashonly** [comment]
Can you try powershell again? (entering the commands directly into your terminal)

The error output in the OP is not possible in powershell

**Comment by jamesdeluk** [comment]
I have been using PowerShell primarily:
![image](https://github.com/yt-dlp/yt-dlp/assets/27723508/9c7e4b23-2ecb-4842-af23-aa024d824af5)

**Comment by bashonly** [comment]
Are you sure that when you run `yt-dlp` that it is actually executing `yt-dlp.exe`? Or could some script named `yt-dlp` have priority in your PATH?

You could run `where yt-dlp` (in cmd) or `&where.exe yt-dlp` (in powershell) to check

**Comment by jamesdeluk** [comment]
Hmm, possible we're getting somewhere.

I'm using pyenv:
```
> &where.exe yt-dlp
C:\Users\XXX\.pyenv\pyenv-win\shims\yt-dlp
C:\Users\XXX\.pyenv\pyenv-win\shims\yt-dlp.bat
```
Running them directly:
```
> C:\Users\XXX\.pyenv\pyenv-win\shims\yt-dlp TEXh6W7szh0 -o "%(title)s.%(ext)s"
> C:\Users\XXX\.pyenv\pyenv-win\shims\yt-dlp.bat TEXh6W7szh0 -o "%(title)s.%(ext)s"
s was unexpected at this time.
```
(the first one had no output)
For reference, `yt-dlp` is:
```
#!/bin/sh
pyenv exec $(basename "$0") "$@"
```
(hence why it doesn't work)
And `yt-dlp.bat` is:
```
@echo off
chcp 1250 > NUL
call pyenv exec %~n0 %*
```
So could be a pyenv issue?

**Comment by MrSmite** [comment]
In my script (windows) I had to escape the ")

> SET outputFormat=^%%^(title^)s_^%%^(upload_date^)s.^%%^(ext^)s

**Comment by bashonly** [comment]
Yep, it's definitely that pyenv-win issue.

**Comment by joelachankeng** [comment]
For anyone that is still having this issue of getting yt-dlp's output template to work with pyenv, here is a simple fix I was able to implement with Gemini's help. 

1. Locate yt-dlp's directory
```
> &where.exe yt-dlp
C:\Users\XXX\.pyenv\pyenv-win\shims\yt-dlp
C:\Users\XXX\.pyenv\pyenv-win\shims\yt-dlp.bat
```
2. In the same directory, create a new bat file (yt-dlp-tk.bat)
```
@echo off
:: usage: yt-dlp-tk <URL>
:: %~dp0 expands to the Drive and Path of this script (yt-dlp-tk.bat), ending in a backslash.
:: We use it to build the full path to yt-dlp-tk.conf in the same directory.
set "CONFIG_PATH=%~dp0yt-dlp-tk.conf"

:: Execute yt-dlp, explicitly pointing to the local configuration file.
:: The URL argument is passed via "%*"
:: --ignore-config forces this yt-dlp instance to use only the conf files in this directory, instead of the default conf from the home, user, and system configurations.
yt-dlp --ignore-config --config-locations "%CONFIG_PATH%" "%*"
```
3. In the same directory, create a conf file (yt-dlp-tk.conf)
```
--sleep-requests 3
--sleep-interval 1
--max-sleep-interval 3
-o %(uploader)s/%(id)s.%(ext)s
--windows-filenames
--cookies-from-browser firefox
```
4. Run it in the terminal (CMD or Powershell)
`yt-dlp-tk https://www.tiktok.com/@youtube/video/7464780234332622123`

**Comment by joelachankeng** [comment]
If you only want your output template to be in the conf file and want to use other arguments in the terminal, do this:

yt-dlp-tk.bat
```
:: *** FIX: The quotes around "%*" have been REMOVED to allow multiple arguments (like -a and the filename) to be passed separately. ***
yt-dlp --ignore-config --config-locations "%CONFIG_PATH%" %*
```

Run it in the terminal (CMD or Powershell)
`yt-dlp-tk -a .\urls.txt >log.txt 2>&1`
