### ISSUE TITLE
when downloading from youtube some frames get blurred

### ISSUE THREAD

**Issue by theSafdarAwan** [yt-dlp/yt-dlp#10135]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

When downloading from youtube some frames get blurred. Is there some option that i don't know of that will make sure it doesn't get bluured.
I am talking about blur like this. This video is downloaded in `480p`
I have checked on youtube in `480p` setting there is no issue like this.
![image](https://github.com/yt-dlp/yt-dlp/assets/87114084/974a1326-1a3e-4641-8182-d58dfded5144)

Same video in next frames there is no blur.
![image](https://github.com/yt-dlp/yt-dlp/assets/87114084/5ee083dc-a1da-45a0-ad8e-08ab7890e68f)

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.12.30 from yt-dlp/yt-dlp [f10589e34]
[debug] Python 3.11.6 (CPython x86_64 64bit) - Linux-6.5.13-7-MANJARO-x86_64-with-glibc2.38 (OpenSSL 3.2.0 23 Nov 2023, glibc 2.38)
[debug] exe versions: ffmpeg 6.1.1 (setts), ffprobe 6.1.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.12.0, brotlicffi-1.1.0.0, certifi-2023.11.17, mutagen-1.47.0, requests-2.31.0, secretstorage-3.3.3, sqlite3-3.44.2, urllib3-1.26.18
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Loaded 1798 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
[debug] Downloading _update_spec from https://github.com/yt-dlp/yt-dlp/releases/latest/download/_update_spec
Current version: stable@2023.12.30 from yt-dlp/yt-dlp
Latest version: stable@2024.05.27 from yt-dlp/yt-dlp
```

**Comment by seproDev** [comment]
That's just the quality of the 480p file from YouTube. Download a higher resolution if you want better quality.

**Comment by theSafdarAwan** [comment]
> That's just the quality of the 480p file from YouTube. Download a higher resolution if you want better quality.

But why does it blur some parts and it doesn't blur other parts. I have check on youtube with `480p`  setting there is no sissue like this.

**Comment by theSafdarAwan** [comment]
> That's just the quality of the 480p file you downloaded from YouTube. Download a higher resolution if you want better quality. Also, there are different 480p formats available. Check which one you have downloaded and which one is being played on the website.

for reference i have provided the two images in the report.

**Comment by seproDev** [comment]
Okay, then please provide an actual verbose log showing you downloading the 480p video. And show a screenshot of the stats for nerds window of the video being played back in your browser (right click).

**Comment by seproDev** [comment]
> But why does it blur some parts and it doesn't blur other parts

As for this, that is just how video encoding works. I am suspecting that you are downloading a different format than what is being played back in your browser. Either way, a full verbose log and information on what your browser is playing back is needed.

**Comment by bashonly** [comment]
If you right click the Youtube web player you can click "stats for nerds" and see the extact format IDs that are playing in your browser. If you download those formats with yt-dlp they will be exactly what you saw in your browser.
