### ISSUE TITLE
[TV5MONDE] Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: Forbidden>)

### ISSUE THREAD

**Issue by Ottaviocr** [yt-dlp/yt-dlp#10153]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United Kingdom

### Provide a description that is worded well enough to be understood

Downloadind videos from TV5Moinde fail with " HTTP Error 403: Forbidden " . See verbose output. Adding "--cookies-from-browser firefox" doesn't help. I can play the video fine in the browser and it does not require login.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'http://www.tv5monde.com/tv/video/72384-le-journal-de-la-rtbf-edition-du-10-06-24-13h']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version master@2024.06.01.185743 from yt-dlp/yt-dlp-master-builds [db50f19d7] (zip)
[debug] Python 3.11.2 (CPython x86_64 64bit) - Linux-6.1.0-18-amd64-x86_64-with-glibc2.36 (OpenSSL 3.0.11 19 Sep 2023, glibc 2.36)
[debug] exe versions: ffmpeg 5.1.4-0 (setts), ffprobe 5.1.4-0
[debug] Optional libraries: brotli-1.0.9, certifi-2022.09.24, requests-2.28.1, sqlite3-3.40.1, urllib3-1.26.12
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Loaded 1820 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-master-builds/releases/latest
Latest version: master@2024.06.01.185743 from yt-dlp/yt-dlp-master-builds
yt-dlp is up to date (master@2024.06.01.185743 from yt-dlp/yt-dlp-master-builds)
[TV5MONDE] Extracting URL: http://www.tv5monde.com/tv/video/72384-le-journal-de-la-rtbf-edition-du-10-06-24-13h
[TV5MONDE] 72384-le-journal-de-la-rtbf-edition-du-10-06-24-13h: Downloading webpage
ERROR: [TV5MONDE] 72384-le-journal-de-la-rtbf-edition-du-10-06-24-13h: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: Forbidden>)
  File "/home/oc/opt/bin/yt-dlp/yt_dlp/extractor/common.py", line 734, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oc/opt/bin/yt-dlp/yt_dlp/extractor/tv5mondeplus.py", line 99, in _real_extract
    webpage = self._download_webpage(url, display_id)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oc/opt/bin/yt-dlp/yt_dlp/extractor/common.py", line 1182, in _download_webpage
    return self.__download_webpage(url_or_request, video_id, note, errnote, None, fatal, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oc/opt/bin/yt-dlp/yt_dlp/extractor/common.py", line 1133, in download_content
    res = getattr(self, download_handle.__name__)(url_or_request, video_id, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oc/opt/bin/yt-dlp/yt_dlp/extractor/common.py", line 954, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oc/opt/bin/yt-dlp/yt_dlp/extractor/common.py", line 903, in _request_webpage
    raise ExtractorError(errmsg, cause=err)

  File "/home/oc/opt/bin/yt-dlp/yt_dlp/networking/_urllib.py", line 396, in _send
    res = opener.open(urllib_req, timeout=self._calculate_timeout(request))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 525, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 634, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 557, in error
    result = self._call_chain(*args)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 749, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 525, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 634, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 563, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/oc/opt/bin/yt-dlp/yt_dlp/extractor/common.py", line 890, in _request_webpage
    return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query, extensions))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oc/opt/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 4142, in urlopen
    return self._request_director.send(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oc/opt/bin/yt-dlp/yt_dlp/networking/common.py", line 117, in send
    response = handler.send(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/oc/opt/bin/yt-dlp/yt_dlp/networking/_helper.py", line 208, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oc/opt/bin/yt-dlp/yt_dlp/networking/common.py", line 337, in send
    return self._send(request)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/oc/opt/bin/yt-dlp/yt_dlp/networking/_urllib.py", line 401, in _send
    raise HTTPError(UrllibResponseAdapter(e.fp), redirect_loop='redirect error' in str(e)) from e
yt_dlp.networking.exceptions.HTTPError: HTTP Error 403: Forbidden
```

**Comment by bashonly** [comment]
Looks like this may be caused by akamai TLS fingerprinting / anti-bot protection.

Try [installing curl_cffi](https://github.com/yt-dlp/yt-dlp?tab=readme-ov-file#impersonation) and adding `--impersonate chrome` to your command

**Comment by LateLament** [comment]
> Looks like this may be caused by akamai TLS fingerprinting / anti-bot protection.
> 
> Try [installing curl_cffi](https://github.com/yt-dlp/yt-dlp?tab=readme-ov-file#impersonation) and adding `--impersonate chrome` to your command

Works for me. Thx

**Comment by Ottaviocr** [comment]
Can I compile yt-dlp from source with curl_cffi built in? If so, how?

**Comment by Ottaviocr** [comment]
Le mar. 18 juin 2024 à 16:24, bashonly ***@***.***> a écrit :
> You can include it in a pyinstaller build, though. If you're on linux, you can run this from the project root directory:
>
> git checkout master && git pull  # if you want to build from a different branch/tag/commit, skip this
> make clean
> python3 -m venv .venv
> source .venv/bin/activate
> python3 devscripts/install_deps.py -o -i build
> python3 devscripts/install_deps.py -i pyinstaller -i secretstorage -i curl-cffi
> python3 devscripts/update-version.py
> python3 devscripts/make_lazy_extractors.py
> python3 -m bundle.pyinstaller


Thanks. I followed this to the letter, but... where is the binary now?

In my directory I have:

~/git/yt-dlp$ ll
total 772
drwxr-xr-x  3 oc oc   4096 Jun 18 16:38 build/
drwxr-xr-x  4 oc oc   4096 Jun 18 16:38 bundle/
-rw-r--r--  1 oc oc 446073 Jun 18 16:32 Changelog.md
-rw-r--r--  1 oc oc   3271 Jun 18 16:32 Collaborators.md
-rw-r--r--  1 oc oc  37391 Jun 18 16:32 CONTRIBUTING.md
-rw-r--r--  1 oc oc   6364 Jun 18 16:32 CONTRIBUTORS
drwxr-xr-x  3 oc oc   4096 Jun 18 16:36 devscripts/
drwxr-xr-x  2 oc oc   4096 Jun 18 16:39 dist/
-rw-r--r--  1 oc oc   1211 Jun 18 16:32 LICENSE
-rw-r--r--  1 oc oc   7831 Jun 18 16:32 Makefile
-rw-r--r--  1 oc oc   1676 Jun 18 16:32 public.key
-rw-r--r--  1 oc oc   9724 Jun 18 16:32 pyproject.toml
-rw-r--r--  1 oc oc 163630 Jun 18 16:32 README.md
-rw-r--r--  1 oc oc    861 Jun 18 16:32 setup.cfg
-rw-r--r--  1 oc oc  56657 Jun 18 16:32 supportedsites.md
drwxr-xr-x  3 oc oc   4096 Jun 18 16:32 test/
drwxr-xr-x 11 oc oc   4096 Jun 18 16:38 yt_dlp/
-rw-r--r--  1 oc oc     47 Jun 18 16:32 yt-dlp.cmd
-rw-r--r--  1 oc oc    749 Jun 18 16:38 yt-dlp_linux.spec
-rwxr-xr-x  1 oc oc    114 Jun 18 16:32 yt-dlp.sh*

I am not sure which directories were there before running all those commands.

**Comment by bashonly** [comment]
relative path of the bianry should be `dist/yt-dlp_linux`

**Comment by Ottaviocr** [comment]
bashonly ***@***.***> a écrit :
>
> relative path of the bianry should be dist/yt-dlp_linux

Thanks. Using:

/home/oc/git/yt-dlp/dist/yt-dlp_linux -o "%(title)s.%(ext)s" -S
res:900 https://www.tv5monde.com/tv/video/72857-le-journal-de-la-rtbf-edition-du-18-06-24-13h

I was finally able to download this video.

Now a few questions, if you don't mind:

1) Do I have to follow the above procedure (which I just copied and
pasted as I have no idea what it does) every time I want a new version
of yt-dlp?

2) Could the Linux binary theoretically be shipped with curl-cffi by default?

3) If so, can I raise a feature request?

**Comment by bashonly** [comment]
> 1) Do I have to follow the above procedure (which I just copied and pasted as I have no idea what it does) every time I want a new version of yt-dlp?

If you want a binary with curl_cffi included in it, yes. As an alternative, you could install yt-dlp via pipx or with pip (in a virtual environment), which would make updating less painful.

> 2) Could the Linux binary theoretically be shipped with curl-cffi by default?

Theoretically, yes. But practically, it's not possible right now. Our `yt-dlp_linux` binary needs to maintain compatibility with old Linux systems (glibc 2.17), and our current solution to this is shipping a statically linked musllibc binary. curl_cffi doesn't offer musllinux wheels for the version we are currently pinning (0.5.10), but they do for the latest 0.7.x series of releases. The problem is that there has not yet been a stable 0.7.x release of curl_cffi; it has beta/pre-release only so far.

> 3) If so, can I raise a feature request?

Not necessary. We hope to include curl_cffi in the linux binaries at some point in the future, but either we'll need curl_cffi to publish a stable 0.7.0 release (for the musllinux wheels) or we'll need to revamp our whole Linux build flow. It's likely we'll end up doing both. It's going to take time regardless.

**Comment by Ottaviocr** [comment]
@bashonly

Amen to that. Thanks for the assistance.

**Comment by Ottaviocr** [comment]
I have another error now. I am not sure if this is related to this issue.

I have rebuilt yt-dlp using the method in https://github.com/yt-dlp/yt-dlp/issues/10153#issuecomment-2176375903

I now have the binary in /home/oc/git/yt-dlp/dist/yt-dlp_linux compiled with curl-cffi and, as of today, I get a new error " Unable to extract video player loader"

```
$ /home/oc/git/yt-dlp/dist/yt-dlp_linux --impersonate chrome   -v https://www.tv5monde.com/tv/video/73645-le-journal-de-la-rtbf-edition-du-01-07-24-13h
[debug] Command-line config: ['--impersonate', 'chrome', '-v', 'https://www.tv5monde.com/tv/video/73645-le-journal-de-la-rtbf-edition-du-01-07-24-13h']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version local@2024.07.09.1 [bbf84bf55] (linux_exe)
[debug] Python 3.11.2 (CPython x86_64 64bit) - Linux-6.1.0-18-amd64-x86_64-with-glibc2.36 (OpenSSL 3.0.13 30 Jan 2024, glibc 2.36)
[debug] exe versions: ffmpeg 5.1.5-0 (setts), ffprobe 5.1.5-0
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.07.04, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, secretstorage-3.3.3, sqlite3-3.40.1, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1834 extractors
[TV5MONDE] Extracting URL: https://www.tv5monde.com/tv/video/73645-le-journal-de-la-rtbf-edition-du-01-07-24-13h
[TV5MONDE] 73645-le-journal-de-la-rtbf-edition-du-01-07-24-13h: Downloading webpage
ERROR: [TV5MONDE] 73645-le-journal-de-la-rtbf-edition-du-01-07-24-13h: Unable to extract video player loader; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp/extractor/common.py", line 740, in extract
  File "yt_dlp/extractor/tv5mondeplus.py", line 104, in _real_extract
  File "yt_dlp/extractor/common.py", line 1333, in _search_regex

```

If I instead launch the bina

**Comment by bashonly** [comment]
@Ottaviocr that looks like a new/separate issue. Could you add `--write-pages` to your command and send the .dump file that yt-dlp writes into your current working directory?

**Comment by Ottaviocr** [comment]
Le mar. 9 juil. 2024 à 17:03, bashonly ***@***.***> a écrit :
>
> @Ottaviocr that looks like a new/separate issue. Could you add --write-pages to your command and send the .dump file that yt-dlp writes into your current working directory?
>

I was able to download the edition of today with no problems

`/home/oc/git/yt-dlp/dist/yt-dlp_linux  -o "%(title)s.%(ext)s" -S
res:900  --impersonate chrome
https://www.tv5monde.com/tv/video/74191-le-journal-de-la-rtbf-edition-du-10-07-24-13h`

Maybe it was just a temporary fluke? (Parent issue is still ongoing)

**Comment by bashonly** [comment]
@Ottaviocr impersonation support has now been baked into the extractor (so you don't need to manually pass `--impersonate` anymore) and `curl_cffi` has been included in the `yt-dlp_linux` builds (so you don't need to build your own anymore). You can run `yt-dlp --update-to master` to update to a version with these improvements

**Comment by Ottaviocr** [comment]
Still not for me unfortunately:

[debug] Command-line config: ['-vU', 'https://www.tv5monde.com/tv/video/74191-le-journal-de-la-rtbf-edition-du-10-07-24-13h']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version master@2024.07.10.151407 from yt-dlp/yt-dlp-master-builds [9b95a6765] (zip)
[debug] Python 3.11.2 (CPython x86_64 64bit) - Linux-6.1.0-18-amd64-x86_64-with-glibc2.36 (OpenSSL 3.0.13 30 Jan 2024, glibc 2.36)
[debug] exe versions: ffmpeg 5.1.5-0 (setts), ffprobe 5.1.5-0
[debug] Optional libraries: Cryptodome-3.11.0, brotli-1.0.9, certifi-2022.09.24, requests-2.28.1, sqlite3-3.40.1, urllib3-1.26.12
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Loaded 1834 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-master-builds/releases/latest
Latest version: master@2024.07.10.151407 from yt-dlp/yt-dlp-master-builds
yt-dlp is up to date (master@2024.07.10.151407 from yt-dlp/yt-dlp-master-builds)
[TV5MONDE] Extracting URL: https://www.tv5monde.com/tv/video/74191-le-journal-de-la-rtbf-edition-du-10-07-24-13h
[TV5MONDE] 74191-le-journal-de-la-rtbf-edition-du-10-07-24-13h: Downloading webpage
WARNING: [TV5MONDE] The extractor is attempting impersonation, but no impersonate target is available; if you encounter errors, then see  https://github.com/yt-dlp/yt-dlp#impersonation  for information on installing the required dependencies
ERROR: [TV5MONDE] 74191-le-journal-de-la-rtbf-edition-du-10-07-24-13h: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: Forbidden>)
  File "/home/oc/opt/bin/yt-dlp/yt_dlp/extractor/common.py", line 740, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oc/opt/bin/yt-dlp/yt_dlp/extractor/tv5mondeplus.py", line 99, in _real_extract
    webpage = self._download_webpage(url, display_id, impersonate=True)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oc/opt/bin/yt-dlp/yt_dlp/extractor/common.py", line 1188, in _download_webpage
    return self.__download_webpage(url_or_request, video_id, note, errnote, None, fatal, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oc/opt/bin/yt-dlp/yt_dlp/extractor/common.py", line 1139, in download_content
    res = getattr(self, download_handle.__name__)(url_or_request, video_id, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oc/opt/bin/yt-dlp/yt_dlp/extractor/common.py", line 960, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oc/opt/bin/yt-dlp/yt_dlp/extractor/common.py", line 909, in _request_webpage
    raise ExtractorError(errmsg, cause=err)

  File "/home/oc/opt/bin/yt-dlp/yt_dlp/networking/_urllib.py", line 396, in _send
    res = opener.open(urllib_req, timeout=self._calculate_timeout(request))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 525, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 634, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 563, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/oc/opt/bin/yt-dlp/yt_dlp/extractor/common.py", line 896, in _request_webpage
    return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query, extensions))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oc/opt/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 4160, in urlopen
    return self._request_director.send(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oc/opt/bin/yt-dlp/yt_dlp/networking/common.py", line 117, in send
    response = handler.send(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/oc/opt/bin/yt-dlp/yt_dlp/networking/_helper.py", line 208, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oc/opt/bin/yt-dlp/yt_dlp/networking/common.py", line 337, in send
    return self._send(request)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/oc/opt/bin/yt-dlp/yt_dlp/networking/_urllib.py", line 401, in _send
    raise HTTPError(UrllibResponseAdapter(e.fp), redirect_loop='redirect error' in str(e)) from e
yt_dlp.networking.exceptions.HTTPError: HTTP Error 403: Forbidden

**Comment by bashonly** [comment]
you need to use the `yt-dlp_linux` build, not the unix zip (`yt-dlp`)

**Comment by Ottaviocr** [comment]
On Wednesday 10 July 2024, bashonly ***@***.***> wrote:
> you need to use the yt-dlp_linux build, not the unix zip (yt-dlp)

Ah ok, sorry. I didn't know about these new builds. Thanks



-- 
Ottavio Caruso

A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?
A: Top-posting.
Q: What is the most annoying thing in e-mail?

**Comment by Ottaviocr** [comment]
Thanks. I have the right binary and it works for all sites, but now I have a different error from TV5 Monde :

WARNING: [TV5MONDE] Unable to download JSON metadata: HTTP Error 403: Forbidden
ERROR: [TV5MONDE] 2b42dcde-e3b9-4827-db0e-ebb79a18646d: No video formats found!;

Full dump:

```
$ yt-dlp_linux -Uv  https://www.tv5monde.com/tv/video/74213-le-journal-de-la-rtbf-edition-du-11-07-24-13h
[debug] Command-line config: ['-Uv', 'https://www.tv5monde.com/tv/video/74213-le-journal-de-la-rtbf-edition-du-11-07-24-13h']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version master@2024.07.10.194910 from yt-dlp/yt-dlp-master-builds (linux_exe)
[debug] Python 3.11.9 (CPython x86_64 64bit) - Linux-6.1.0-18-amd64-x86_64-with (OpenSSL 3.1.5 30 Jan 2024)
[debug] exe versions: ffmpeg 5.1.5-0 (setts), ffprobe 5.1.5-0
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.07.04, curl_cffi-0.7.0, mutagen-1.47.0, requests-2.32.3, secretstorage-3.3.3, sqlite3-3.44.2, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1834 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-master-builds/releases/latest
Latest version: master@2024.07.10.194910 from yt-dlp/yt-dlp-master-builds
yt-dlp is up to date (master@2024.07.10.194910 from yt-dlp/yt-dlp-master-builds)
[TV5MONDE] Extracting URL: https://www.tv5monde.com/tv/video/74213-le-journal-de-la-rtbf-edition-du-11-07-24-13h
[TV5MONDE] 74213-le-journal-de-la-rtbf-edition-du-11-07-24-13h: Downloading webpage
[TV5MONDE] 74213-le-journal-de-la-rtbf-edition-du-11-07-24-13h: Downloading deferred info
WARNING: [TV5MONDE] Unable to download JSON metadata: HTTP Error 403: Forbidden
ERROR: [TV5MONDE] 2b42dcde-e3b9-4827-db0e-ebb79a18646d: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "yt_dlp/YoutubeDL.py", line 1622, in wrapper
  File "yt_dlp/YoutubeDL.py", line 1778, in __extract_info
  File "yt_dlp/YoutubeDL.py", line 1837, in process_ie_result
  File "yt_dlp/YoutubeDL.py", line 2843, in process_video_result
  File "yt_dlp/YoutubeDL.py", line 1119, in raise_no_formats
yt_dlp.utils.ExtractorError: [TV5MONDE] 2b42dcde-e3b9-4827-db0e-ebb79a18646d: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

**Comment by Ottaviocr** [comment]
Whereas if I use the custom built yt-dlp_linux that I built from git and using --impersonate chrome, I can download this video ok.

**Comment by bashonly** [comment]
can you try running `yt-dlp --update-to bashonly/yt-dlp@2024.07.11.165313` with the `yt-dlp_linux` build, and then try downloading the problematic link **without** `--impersonate chrome`?

**Comment by Ottaviocr** [comment]
@bashonly  All fine with this version of yt-dlp_linux and without using `--impersonate chrome`

**Comment by Ottaviocr** [comment]
Is this going to end up in the master build?
