### ISSUE TITLE
[Youtube] Error downloading playlist

### ISSUE THREAD

**Issue by Pamilg8** [yt-dlp/yt-dlp#10150]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [ ] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

I got an error when I tried to download a playlist from YouTube with YTDLnis (to use YtDlp on android). Tried retrying with cookies and it doesn't work

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
WARNING: [youtube:tab] Preferring "az" translated fields. Note that some metadata extraction may fail or be incorrect.
WARNING: [youtube:tab] unable to extract yt initial data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [youtube:tab] Incomplete yt initial data received. Retrying (1/3)...
WARNING: [youtube:tab] unable to extract yt initial data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [youtube:tab] Incomplete yt initial data received. Retrying (2/3)...
WARNING: [youtube:tab] unable to extract yt initial data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [youtube:tab] Incomplete yt initial data received. Retrying (3/3)...
WARNING: [youtube:tab] unable to extract yt initial data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [youtube:tab] Incomplete yt initial data received; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U. Giving up after 3 retries
ERROR: [youtube:tab] PLRYrvC4-qoFzrIexwbf7LGwbg7OXWuHAy: Unable to recognize tab page; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

**Comment by bashonly** [comment]
provide a verbose yt-dlp log please or else this issue is invalid and will be closed

**Comment by Pamilg8** [comment]
> provide a verbose yt-dlp log please or else this issue is invalid and will be closed

How? What did I do wrong?

**Comment by bashonly** [comment]
you checked these but didn't actually do them

> - [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
> - [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
> - [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by Pamilg8** [comment]
> you checked these but didn't actually do them
> 
> > * [x]  Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
> > * [x]  If using API, add `'verbose': True` to `YoutubeDL` params instead
> > * [x]  Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

I wanted to download a playlist with YTDLnis on android. I don't use ytdlp. This is related to ytdlp. I canceled them

**Comment by bashonly** [comment]
This is a bug tracker for yt-dlp, not YTDLnis.

**Comment by bashonly** [comment]
https://github.com/deniscerri/ytdlnis
