### ISSUE TITLE
[Site Request] Any chance to add support for TikTok users?

### ISSUE THREAD

**Issue by ahm750** [yt-dlp/yt-dlp#1017]
## Checklist

- [x] I'm reporting a site feature request
- [x] I've verified that I'm running yt-dlp version **2021.09.02**
- [x] I've searched the bugtracker for similar site feature requests including closed ones

## Description

Hi, is it possible to add support for fetching the list of videos from a TikTok user URL using the -J and --flat-playlist arguments? 

Example URL: https://www.tiktok.com/@khaby.lame

**Comment by pukkandan** [comment]
> [x] I've searched the bugtracker for similar site feature requests including closed ones

Don't tick fields blindly!!

Closed by #756, #925
