### ISSUE TITLE
bilibili.com TV API implementation

### ISSUE THREAD

**Issue by pha1n0q** [yt-dlp/yt-dlp#10171]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a site-specific feature
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United States

### Example URLs

(4K on the TV API) https://www.bilibili.com/video/BV1qM4y1w716/
(4K on the TV API) https://www.bilibili.com/video/BV1Am411y7iK/
(1080p higher bitrate on the TV API, with multiple 'Ps' in it's video selection — see image below) https://www.bilibili.com/video/BV16s421u7NP/
> ![image](https://github.com/yt-dlp/yt-dlp/assets/88598340/43f47b16-27f6-43c0-9010-8e0b24005a84)

### Provide a description that is worded well enough to be understood

bilibili has a TV version where you can view videos without a watermark. It would be cool to have it's API implemented in yt-dlp!

I know that [BBDown](https://github.com/nilaoda/BBDown), a dedicated bilibili video downloader, has the TV API implemented, but the official release is currently broken (it gives an error when specifying the TV API to be used) — a [fork](https://github.com/Jared-02/BBDown) of it has a working TV API usage however. Maybe this could be useful in seeing how it could be used for yt-dlp?

I also was able to find a [repository](https://github.com/SocialSisterYi/bilibili-API-collect) where they collect bilibili APIs and its usages (maybe this could also be useful? but it's all in Chinese).

I have a bilibili "super big member" account that can be used to test downloading 1080p Premium and higher video that I'm willing to share!

(also when using BBdown, I noticed that the TV API doesn't have FLAC audio quality on supported videos but on the website there is — when implementing the TV API, is it possible to use the WEB/APP API instead to download FLAC audio?)

The bilibili TV app can be downloaded here: https://app.bilibili.com/ (should be named "TV版")

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.bilibili.com/video/BV1qM4y1w716', '--cookies-from-browser', 'firefox']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.05.27 from yt-dlp/yt-dlp [12b248ce6] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22631-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 2024-05-02-git-71669f2ad5-full_build-www.gyan.dev (setts), ffprobe 2024-05-02-git-71669f2ad5-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.02.02, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.2, sqlite3-3.35.5, urllib3-2.2.1, websockets-12.0
[debug] Proxy map: {}
Extracting cookies from firefox
[debug] Extracting cookies from: "C:\Users\[xxx]\AppData\Roaming\Mozilla\Firefox\Profiles\fe6q6sdc.default-release-1692985777565\cookies.sqlite"
Extracted 1398 cookies from firefox
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1820 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.05.27 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.05.27 from yt-dlp/yt-dlp)
[BiliBili] Extracting URL: https://www.bilibili.com/video/BV1qM4y1w716
[BiliBili] 1qM4y1w716: Downloading webpage
[BiliBili] BV1qM4y1w716: Extracting videos in anthology
[BiliBili] 934637444: Extracting chapters
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] BV1qM4y1w716: Downloading 1 format(s): 30127+30280
[debug] Invoking http downloader on "https://upos-hz-mirrorakam.akamaized.net/upgcxcode/56/97/455439756/455439756-1-30127.m4s?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0MvXg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M=&uipk=5&nbs=1&deadline=1718258819&gen=playurlv2&os=akam&oi=415066688&trid=00bfcaee0fbc4d4c8c9699c72b162097u&mid=3493131437738426&platform=pc&og=hw&upsig=78d6ea3074b8859ca28d18b3a41e6377&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,mid,platform,og&hdnts=exp=1718258819~hmac=f2e4808fb7a1d0bc70f2b5582b512ff199859e05c14754fcd2d38864040db8ac&bvc=vod&nettype=0&orderid=0,1&buvid=68C46871-527D-BDB6-A5AC-51892774FCFA38910infoc&build=0&f=u_0_0&agrr=0&bw=2545181&logo=80000000"
[debug] File locking is not supported. Proceeding without locking
[download] Destination: 【8K演示片】B站首发！你的设备还顶得住吗？ [BV1qM4y1w716].f30127.mp4
[download] 100% of  466.04MiB in 00:11:09 at 713.27KiB/s
[debug] Invoking http downloader on "https://upos-sz-mirroraliov.bilivideo.com/upgcxcode/56/97/455439756/455439756_nb2-1-30280.m4s?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0MvXg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M=&uipk=5&nbs=1&deadline=1718258819&gen=playurlv2&os=aliovbv&oi=415066688&trid=00bfcaee0fbc4d4c8c9699c72b162097u&mid=3493131437738426&platform=pc&og=hw&upsig=a145ef4a14f3e0866181b94cd297f299&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,mid,platform,og&bvc=vod&nettype=0&orderid=0,1&buvid=68C46871-527D-BDB6-A5AC-51892774FCFA38910infoc&build=0&f=u_0_0&agrr=0&bw=24769&logo=80000000"
[download] Destination: 【8K演示片】B站首发！你的设备还顶得住吗？ [BV1qM4y1w716].f30280.m4a
[download] 100% of    4.54MiB in 00:00:04 at 1021.09KiB/s
[Merger] Merging formats into "【8K演示片】B站首发！你的设备还顶得住吗？ [BV1qM4y1w716].mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i "file:【8K演示片】B站首发！你的设备还 顶得住吗？ [BV1qM4y1w716].f30127.mp4" -i "file:【8K演示片】B站首发！你的设备还顶得住吗？ [BV1qM4y1w716].f30280.m4a" -c copy -map 0:v:0 -map 1:a:0 -movflags +faststart "file:【8K演示片】B站首发！你的设备还顶得住吗？ [BV1qM4y1w716].temp.mp4"
Deleting original file 【8K演示片】B站首发！你的设备还顶得住吗？ [BV1qM4y1w716].f30127.mp4 (pass -k to keep)
Deleting original file 【8K演示片】B站首发！你的设备还顶得住吗？ [BV1qM4y1w716].f30280.m4a (pass -k to keep)
```

**Comment by c-basalt** [comment]
The credential of Bilibili's mobile-like platforms is token-based, which is different from cookie-based credential that browsers use. Implementing non-browser API requires implementing all the login logic that applies to mobile-like platform to begin with.
Btw, I may have missed it but what is the main benefic of having a TV-version API? There is already up to 8K resolution available to browser when providing cookies:
```cmd
F:\cbasalt-github\yt-dlp>py -m yt_dlp -F https://www.bilibili.com/video/BV1qM4y1w716/ --cookies-from firefox
[BiliBili] Extracting URL: https://www.bilibili.com/video/BV1qM4y1w716/ 
[BiliBili] 1qM4y1w716: Downloading webpage 
Extracting cookies from firefox
Extracted 1191 cookies from firefox 
[BiliBili] BV1qM4y1w716: Extracting videos in anthology 
[BiliBili] 934637444: Extracting chapters 
[info] Available formats for BV1qM4y1w716: 
ID     EXT RESOLUTION FPS │   FILESIZE    TBR PROTO │ VCODEC           VBR ACODEC      ABR 
──────────────────────────────────────────────────────────────────────────────────────────
30216  m4a audio only     │ ≈  1.55MiB    67k https │ audio only           mp4a.40.2   67k
30232  m4a audio only     │ ≈  3.05MiB   133k https │ audio only           mp4a.40.2  133k
30280  m4a audio only     │ ≈  4.54MiB   197k https │ audio only           mp4a.40.2  197k
100022 mp4 682x360     25 │ ≈  4.48MiB   195k https │ av01.0.01M.08   195k video only
30016  mp4 682x360     25 │ ≈  5.18MiB   225k https │ avc1.64001E     225k video only
30011  mp4 682x360     25 │ ≈  7.03MiB   306k https │ hev1.1.6.L120   306k video only
100023 mp4 910x480     25 │ ≈  8.25MiB   359k https │ av01.0.04M.08   359k video only
30032  mp4 910x480     25 │ ≈ 11.60MiB   505k https │ avc1.64001F     505k video only
30033  mp4 910x480     25 │ ≈  5.19MiB   226k https │ hev1.1.6.L120   226k video only
100024 mp4 1364x720    25 │ ≈ 16.50MiB   718k https │ av01.0.05M.08   718k video only
30064  mp4 1364x720    25 │ ≈ 25.61MiB  1114k https │ avc1.640028    1114k video only
30066  mp4 1364x720    25 │ ≈  8.82MiB   384k https │ hev1.1.6.L120   384k video only
100026 mp4 2048x1080   25 │ ≈ 19.80MiB   862k https │ av01.0.08M.08   862k video only
30080  mp4 2048x1080   25 │ ≈ 38.24MiB  1664k https │ avc1.640032    1664k video only
30077  mp4 2048x1080   25 │ ≈ 20.72MiB   902k https │ hev1.1.6.L150   902k video only
100027 mp4 2048x1080   25 │ ≈ 33.34MiB  1451k https │ av01.0.08M.08  1451k video only
30112  mp4 2048x1080   25 │ ≈111.48MiB  4850k https │ avc1.640032    4850k video only
30102  mp4 2048x1080   25 │ ≈ 32.17MiB  1400k https │ hev1.1.6.L150  1400k video only
100029 mp4 4096x2160   25 │ ≈117.52MiB  5113k https │ av01.0.12M.08  5113k video only
30120  mp4 4096x2160   25 │ ≈252.10MiB 10968k https │ avc1.640033   10968k video only
30121  mp4 4096x2160   25 │ ≈112.41MiB  4891k https │ hev1.1.6.L153  4891k video only
100032 mp4 8192x4320   25 │ ≈221.18MiB  9623k https │ av01.0.16M.08  9623k video only
30127  mp4 8192x4320   25 │ ≈466.16MiB 20281k https │ hev1.1.6.L180 20281k video only
```

**Comment by c-basalt** [comment]
I see.
Still, a dedicated downloader, which has the flexibility with login and credential storage, is better for this job.
It is more or less possible to get it implemented in yt-dlp, but compared to the complexity it implies, I don't really feel a partially watermark-free API really worth it.
