### ISSUE TITLE
pipe m3u8 instead of mpegts

### ISSUE THREAD

**Issue by write3371** [yt-dlp/yt-dlp#10179]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

many player does not support seek when playing a mpegts file.

is it possible to pipe with seekable foramt like m3u8 other than mpegts?

instead of using ffmpeg to really download the video that has both video and audio, generate a m3u8 file that has streams of both video and audio and optionally subtitles and send it to the user

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by seproDev** [comment]
As far as I know, this is impossible. How would yt-dlp pipe a m3u8 playlist and its segments separately?
And even if that was possible, how would yt-dlp do that without downloading all the segments in advance/know which segments the player requested?
If your media player supports m3u8 playlists/dash manifests, just take the format URL and open that in your media player.

**Comment by bashonly** [comment]
And as for the original version of the question (before edits), piping as mp4 is not possible either. The mp4 format defaults to writing its container information (including the info that makes seeking possible) at very end of the file, making it not a viable format for streaming/piping.

**Comment by seproDev** [comment]
With yt-dlp itself it is not possible to generate a new dash manifest.
If you want a dash manifest and the site you are downloading from streams through dash, then you can just use the existing mpd instead of generating a new one.
