### ISSUE TITLE
Is it possible to allow a Javascript frontend to stream a video without downloading the full file?

### ISSUE THREAD

**Issue by MichelJonkman** [yt-dlp/yt-dlp#10183]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I want to create a music player with Youtube support but I can't figure out if it's possible. I need to be able to seek in the video as well.

I was thinking about using Tauri, meaning I'll be using a Rust backend and JavaScript/HTML frontend. An alternative would be a PWA but the Youtube stream would probably have to run through a proxy.

Is it possible to use yt-dlp for this? If so, how would I go about doing this?

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by rozari0** [comment]
Yep, pass the stream url to your fronted. (you can get steam url by `yt-dlp -g <url>`)

**Comment by MichelJonkman** [comment]
Alright, thank you very much!
