### ISSUE TITLE
No Audio When download video using -f option

### ISSUE THREAD

**Issue by iomari** [yt-dlp/yt-dlp#10189]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

I'm using the latest version. When ever I download using the -f option to conserve space, the downloaded video has no audio. I'm force to download with no options which always downloads the highest resolution in webm format which is normally to big for me to download.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [x] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '-f', '397', 'https://www.youtube.com/watch?v=jcgfQEbptdo&t=11s']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.05.27 from yt-dlp/yt-dlp (linux_exe)
[debug] Python 3.11.9 (CPython x86_64 64bit) - Linux-6.5.0-35-generic-x86_64-with (OpenSSL 3.1.4 24 Oct 2023)
[debug] exe versions: ffmpeg 6.0 (setts), ffprobe 6.0, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.02.02, mutagen-1.47.0, requests-2.32.2, secretstorage-3.3.3, sqlite3-3.44.2, urllib3-2.2.1, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1820 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.05.27 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.05.27 from yt-dlp/yt-dlp)
[youtube] Extracting URL: https://www.youtube.com/watch?v=jcgfQEbptdo&t=11s
[youtube] jcgfQEbptdo: Downloading webpage
[youtube] jcgfQEbptdo: Downloading ios player API JSON
[debug] Loading youtube-nsig.74204f6c from cache
[debug] [youtube] Decrypted nsig B1dqHP_zj22ijfAb => tYUvMYm2FRpjsg
[debug] Loading youtube-nsig.74204f6c from cache
[debug] [youtube] Decrypted nsig 2yBhIwEFz8KrDlC6 => XA7dh95zpDu4yw
[youtube] jcgfQEbptdo: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[info] jcgfQEbptdo: Downloading 1 format(s): 397
[debug] Invoking http downloader on "https://rr4---sn-huoob-avnz.googlevideo.com/videoplayback?expire=1718470423&ei=t3JtZrKcDOiemLAP1bmu6Aw&ip=102.91.92.242&id=o-AMRiOIo2E9t9tdhGP8pvPEDkb4flX0v-YO3BuKgDGH6a&itag=397&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278%2C394%2C395%2C396%2C397%2C398%2C399&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=2g&mm=31%2C29&mn=sn-huoob-avnz%2Csn-avn7ln7l&ms=au%2Crdu&mv=m&mvi=4&pl=24&initcwndbps=360000&bui=AbKP-1Nr3R3y0ZgORdFRMV69Gdi-CO7-6mrSSuNoT8hVNH-JHf0t_3Tzy9_f9Bd0sg-Ssa86pWejJIw2&spc=UWF9f6HdKUVn4nmeuw1Nwx_gb8wBkI9Y-QivpzBo4QWucDGbBByaSJFX8neF&vprv=1&svpuc=1&mime=video%2Fmp4&ns=-Tb_jrPHwi_9WUeOzLo-7d4Q&rqh=1&gir=yes&clen=353505527&dur=41724.765&lmt=1703910035802757&mt=1718448308&fvip=1&keepalive=yes&c=WEB&sefc=1&txp=543G434&n=XA7dh95zpDu4yw&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cxpc%2Cbui%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cns%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRAIgezhFetxg38WPeujq7CBEE-Xov3wzpErp3LeUrI4y_GwCICvqkbr3JL-9eJDWlfvnxtDHivXwgAEUZVUtq_1iOvCH&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AHlkHjAwRQIgZKZrjZGY-j_wD9edcUj5F3No3Y1TVYpkm-Vfz39c2pcCIQCQFUonDvOWKGxDTKBUWwb0kbA2hpst9wsCQ0SHtnw3SA%3D%3D"
[download] Resuming download at byte 25226052
[download] Destination: Learn Blockchain & Solidity Development   Full Course 2024 [jcgfQEbptdo].mp4
```

**Comment by seproDev** [comment]
There is no audio because you are asking yt-dlp to download format 397, which is a video only format.
You can check all available formats with `yt-dlp -F "URL"`.
If you just want to download a lower resolution version, I would use `yt-dlp -S res:480 "URL"`.

**Comment by iomari** [comment]
here is the output of yt-dlp -F. Please tell me which code I should use. It appeared to me that 397 was mp4 which I thought was audio/video.Not just video.

[youtube] Extracting URL: https://www.youtube.com/watch?v=jcgfQEbptdo&t=11s
[youtube] jcgfQEbptdo: Downloading webpage
[youtube] jcgfQEbptdo: Downloading ios player API JSON
[youtube] jcgfQEbptdo: Downloading m3u8 information
[info] Available formats for jcgfQEbptdo:
ID      EXT   RESOLUTION FPS CH |   FILESIZE   TBR PROTO | VCODEC          VBR ACODEC      ABR ASR MORE INFO
-----------------------------------------------------------------------------------------------------------------------------
sb3     mhtml 48x27        0    |                  mhtml | images                                  storyboard
sb2     mhtml 80x45        0    |                  mhtml | images                                  storyboard
sb1     mhtml 160x90       0    |                  mhtml | images                                  storyboard
sb0     mhtml 320x180      0    |                  mhtml | images                                  storyboard
233     mp4   audio only        |                  m3u8  | audio only          unknown             [en] Default
234     mp4   audio only        |                  m3u8  | audio only          unknown             [en] Default
139-drc m4a   audio only      2 |  242.64MiB   49k https | audio only          mp4a.40.5   49k 22k [en] low, DRC, m4a_dash
139     m4a   audio only      2 |  242.64MiB   49k https | audio only          mp4a.40.5   49k 22k [en] low, m4a_dash
249     webm  audio only      2 |  238.36MiB   48k https | audio only          opus        48k 48k [en] low, webm_dash
250     webm  audio only      2 |  332.17MiB   67k https | audio only          opus        67k 48k [en] low, webm_dash
140-drc m4a   audio only      2 |  643.99MiB  129k https | audio only          mp4a.40.2  129k 44k [en] medium, DRC, m4a_dash
140     m4a   audio only      2 |  643.99MiB  129k https | audio only          mp4a.40.2  129k 44k [en] medium, m4a_dash
251     webm  audio only      2 |  601.74MiB  121k https | audio only          opus       121k 48k [en] medium, webm_dash
602     mp4   256x144     15    | ~  1.84GiB  379k m3u8  | vp09.00.10.08  379k video only
394     mp4   256x144     30    |   79.36MiB   16k https | av01.0.00M.08   16k video only          144p, mp4_dash
269     mp4   256x144     30    | ~  1.41GiB  289k m3u8  | avc1.4D400C    289k video only
160     mp4   256x144     30    |   56.55MiB   11k https | avc1.4D400C     11k video only          144p, mp4_dash
603     mp4   256x144     30    | ~  2.08GiB  428k m3u8  | vp09.00.11.08  428k video only
278     webm  256x144     30    |  103.48MiB   21k https | vp9             21k video only          144p, webm_dash
395     mp4   426x240     30    |  126.21MiB   25k https | av01.0.00M.08   25k video only          240p, mp4_dash
229     mp4   426x240     30    | ~  1.68GiB  346k m3u8  | avc1.4D4015    346k video only
133     mp4   426x240     30    |   96.51MiB   19k https | avc1.4D4015     19k video only          240p, mp4_dash
604     mp4   426x240     30    | ~  2.12GiB  436k m3u8  | vp09.00.20.08  436k video only
242     webm  426x240     30    |  173.27MiB   35k https | vp9             35k video only          240p, webm_dash
396     mp4   640x360     30    |  234.06MiB   47k https | av01.0.01M.08   47k video only          360p, mp4_dash
230     mp4   640x360     30    | ~  3.03GiB  623k m3u8  | avc1.4D401E    623k video only
134     mp4   640x360     30    |  166.03MiB   33k https | avc1.4D401E     33k video only          360p, mp4_dash
18      mp4   640x360     30  2 |  904.19MiB  182k https | avc1.42001E         mp4a.40.2       44k [en] 360p
605     mp4   640x360     30    | ~  3.33GiB  686k m3u8  | vp09.00.21.08  686k video only
243     webm  640x360     30    |  352.96MiB   71k https | vp9             71k video only          360p, webm_dash
397     mp4   854x480     30    |  337.13MiB   68k https | av01.0.04M.08   68k video only          480p, mp4_dash
231     mp4   854x480     30    | ~  3.92GiB  806k m3u8  | avc1.4D401F    806k video only
135     mp4   854x480     30    |  239.54MiB   48k https | avc1.4D401F     48k video only          480p, mp4_dash
606     mp4   854x480     30    | ~  5.39GiB 1110k m3u8  | vp09.00.30.08 1110k video only
244     webm  854x480     30    |  498.31MiB  100k https | vp9            100k video only          480p, webm_dash
22      mp4   1280x720    30  2 | ≈995.57MiB  200k https | avc1.64001F         mp4a.40.2       44k [en] 720p
398     mp4   1280x720    30    |  563.49MiB  113k https | av01.0.05M.08  113k video only          720p, mp4_dash
232     mp4   1280x720    30    | ~  6.06GiB 1248k m3u8  | avc1.4D401F   1248k video only
136     mp4   1280x720    30    |  354.46MiB   71k https | avc1.4D401F     71k video only          720p, mp4_dash
609     mp4   1280x720    30    | ~  7.12GiB 1465k m3u8  | vp09.00.31.08 1465k video only
247     webm  1280x720    30    |  838.24MiB  169k https | vp9            169k video only          720p, webm_dash
399     mp4   1920x1080   30    |  983.24MiB  198k https | av01.0.08M.08  198k video only          1080p, mp4_dash
270     mp4   1920x1080   30    | ~ 16.37GiB 3370k m3u8  | avc1.640028   3370k video only
137     mp4   1920x1080   30    |  931.49MiB  187k https | avc1.640028    187k video only          1080p, mp4_dash
614     mp4   1920x1080   30    | ~ 11.20GiB 2305k m3u8  | vp09.00.40.08 2305k video only
248     webm  1920x1080   30    |    1.25GiB  258k https | vp9            258k video only          1080p, webm_dash
616     mp4   1920x1080   30    | ~ 19.19GiB 3951k m3u8  | vp09.00.40.08 3951k video only          Premium

**Comment by seproDev** [comment]
As you can see, 397 is a 480p av1 video only format
```
397     mp4   854x480     30    |  337.13MiB   68k https | av01.0.04M.08   68k video only          480p, mp4_dash
```
What are you trying to archive?
Do you want the lowest resolution av1 video? Do you want any 480p video? Do you want the smallest possible file?

**Comment by iomari** [comment]
Sorry, I see the error. I need 18 or 22.
Thanks

**Comment by jonathanou** [comment]
@iomari I ran into the same problem but all of the formats with the resolution I wanted was marked "video-only".  I found out I could make yt-dlp download a video stream and an audio stream and merge it automatically by doing something like this:

`yt-dlp -f 397+140 [URL]`

397 is the video-only stream, while 140 is the audio-only stream.

Hope that helps you in the future!

**Comment by SparkyNZ** [comment]
> yt-dlp -f 397+140 [URL]

That seems to download 2 separate .mp4 files for me - one audio, one video. How do you "merge it automatically" ?

**Comment by SparkyNZ** [comment]
"video-only". I found out I could make yt-dlp download a video stream and an audio stream and merge it automatically by doing something like this:
> 
> `yt-dlp -f 397+140 [URL]`

FYI "merge it automatically" requires ffmpeg.exe to be in your path somewhere. Mine merges automatically after doing that. 👍
