### ISSUE TITLE
Efficiently Downloading a Specific Range of a YouTube Video with Synced Audio

### ISSUE THREAD

**Issue by mohasaid** [yt-dlp/yt-dlp#10181]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I'm currently working on a project where I need to download a specific segment of a YouTube video. The requirements are as follows:

- The video and audio need to be in sync.
- The minimum video quality should be 720p.
- The segment doesn't need to be cut at an exact frame but should be reasonably close.
- The whole process should take a maximum of 5 seconds.

I have explored the documentation and tried the following methods:

1) Downloading with `--force-keyframes-at-cuts`:

```bash
yt-dlp --download-sections "*00:32:53.2-00:32:55.5" --force-keyframes-at-cuts <URL>
```

This approach works, but I've noticed that it is too slow., it can take 1 minute to download a range of 2 minutes.

2) Downloading audio and video separately and then merging:

```bash
yt-dlp -f "bestvideo[height>=720]+bestaudio" --download-sections "*00:32:53.2-00:32:55.5" <URL> -o "video.mp4"
ffmpeg -i video.mp4 -i audio.m4a -c:v copy -c:a aac output.mp4
```

Using this method is the fastest way that I could achieve, but the first part of downloading the section of the video takes too much time. Sometimes it takes 10 seconds, other times it takes 5 seconds, it is not deterministic.

Given these requirements and the attempts I've made, is there a more efficient or recommended way to achieve this with yt-dlp? Any tips or specific flags that might help improve the sync and download speed would be greatly appreciated.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
Take your 2nd solution, except don't download the video and audio separately, but add `--compat opt no-direct-merge` to your yt-dlp command so that it will download video and audio in separate steps and then do the merging for you. That's about as efficient as it will get.
