### ISSUE TITLE
Error while downloading HDR video from Ytdlnis app. 

### ISSUE THREAD

**Issue by aransari1** [yt-dlp/yt-dlp#10191]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Provide a description that is worded well enough to be understood

How to fix this error. This error is occurring only while downloading hdr videos in Ytdlnis app. I have raised the issue but they said it's ytdlp issue. 

**ERROR: Postprocessing:   Stream #1:0 -> #0:1 (copy)**

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
--no-quiet --no-simulate --print "after_move:'%(filepath,_filename)s'" -N "25" --retries "99" --fragment-retries "30" --restrict-filenames --trim-filenames "224" --write-thumbnail --convert-thumbnails "jpg" --no-mtime --sponsorblock-remove "selfpromo,preview,sponsor,intro,outro,interaction" --parse-metadata "uploader:^(?P<uploader>.*?)(?:(?= - Topic)|$)" --sponsorblock-mark "all" --embed-chapters --merge-output-format "webm" -S "+hasaud,vcodec:vp9,acodec:opus,vext:webm,aext:opus" -f "334+258/334+ba/334/b" --embed-subs --sub-langs "en-IN,hi" -P "/storage/emulated/0/YTB/Videos" -o "%(title)s - %(uploader)s.%(ext)s" --replace-in-metadata "video:title" ".+" "2020 LG OLED l  The Black 4K HDR 60fps" --replace-in-metadata "video:uploader" ".+" "LG Global" "https://youtu.be/njX2bu-_Vw4"

ERROR: Postprocessing:   Stream #1:0 -> #0:1 (copy)
```

**Comment by seproDev** [comment]
Post a complete versbose log. But I think you are trying to embed aac audio in to a webm, which is impossible.

**Comment by seproDev** [comment]
@Yash1804-bot That is a completely unrelated issue. Your IP is being blocked by Instagram. Nothing we can do. You could pass cookies, but Instagram does not hesitate to ban accounts. So do this at your own risk.

**Comment by seproDev** [comment]
@Yash1804-bot There is no official yt-dlp app. YTDLnis is not made by us.
As I said, your IP is likely blocked by Instragram. Try with a different IP or pass cookies.
