### ISSUE TITLE
[Feature Request] Better .jpg thumbnail quality when converting from .webp

### ISSUE THREAD

**Issue by nicolaasjan** [yt-dlp/yt-dlp#102]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running yt-dlp version **2021.02.19**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description

I've noticed that the conversion of `.webp` thumbnails to `.jpg` is rather lossy.
So I did some experimenting with [this video](https://www.youtube.com/watch?v=fiH9edd25Bc).

With the latest yt-dlp [this thumbnail](https://dl.dropboxusercontent.com/s/k9aqmjkiyfm0bmo/George%20Harrison%20-%20What%20Is%20Life%20%28Official%20Music%20Video%29.1.jpg) is generated (48.1kb).

Then I changed [line 80](https://github.com/pukkandan/yt-dlp/blob/e094cec18c4c7f17396fe6a946c497b5048863c6/youtube_dlc/postprocessor/embedthumbnail.py#L80) in `embedthumbnail.py` to:

`self.run_ffmpeg(escaped_thumbnail_filename, escaped_thumbnail_jpg_filename, ['-q:v', '1', '-bsf:v', 'mjpeg2jpeg'])`
So I added: `'-q:v', '1',`

Now [this thumbnail](https://dl.dropboxusercontent.com/s/s2qvlusblxgstgg/George%20Harrison%20-%20What%20Is%20Life%20%28Official%20Music%20Video%29.2.jpg) is generated (93.4kb).

You can clearly see the [difference](https://dl.dropboxusercontent.com/s/yipt1mib0xhykll/screenshot_jpeg-compression.png) when enlarged (500%).
A lot of artefacts in the left one.

**Comment by pukkandan** [comment]
I am looking into seperating Thumbnail conversion from embedding for #99. I will add this (or atleast add an option for the user to add this) when I complete that.

**Comment by pukkandan** [comment]
Once https://github.com/pukkandan/yt-dlp-dev/commit/5c914d293f265a45d43c696e83e469971df87d87 is merged (I need to test it more), you will be able to use `--ppa "ThumbnailsConvertor:-q:v 1"` to control the converted thumbnail's quality

**Comment by nicolaasjan** [comment]
> Then I changed [line 80](https://github.com/pukkandan/yt-dlp/blob/e094cec18c4c7f17396fe6a946c497b5048863c6/youtube_dlc/postprocessor/embedthumbnail.py#L80) in `embedthumbnail.py` to:
> 
> `self.run_ffmpeg(escaped_thumbnail_filename, escaped_thumbnail_jpg_filename, ['-q:v', '1', '-bsf:v', 'mjpeg2jpeg'])`
> So I added: `'-q:v', '1',`

I see that this code (without `'-q:v', '1',`) now went in `./yt_dlp/postprocessor/ffmpeg.py` ([Line 856](https://github.com/yt-dlp/yt-dlp/blob/a31953b0e69f710f737643cb36b0ca1caf69e04c/yt_dlp/postprocessor/ffmpeg.py#L856))

**Comment by pukkandan** [comment]
I did not change the default quality, but only added the ability for the user to specify the quality with `--ppa "ThumbnailsConvertor:-q:v 1"`. I assumes this was clear from my previous comment

**Comment by nicolaasjan** [comment]
> I did not change the default quality, but only added the ability for the user to specify the quality with `--ppa "ThumbnailsConvertor:-q:v 1"`. I assumed this was clear from my previous comment

Yes that was clear. :)
I only noticed that it's now handled by `ffmpeg.py`.

`--ppa "ThumbnailsConvertor:-q:v 1"` is not possible right now, I guess? (because [pukkandan@5c914d2](https://github.com/pukkandan/yt-dlp-dev/commit/5c914d293f265a45d43c696e83e469971df87d87) isn't merged yet).

**Comment by pukkandan** [comment]
It was merged: https://github.com/yt-dlp/yt-dlp/commit/8fa43c73d83619722c7e30d70247eaa9b7f52810

**Comment by pukkandan** [comment]
> I only noticed that it's now handled by ffmpeg.py.

The thumbnail conversion was previously handled by `EmbedThumbnailPP`. This is why it wasn't possible to specify quality with `--ppa` and why we couldn't convert thumbnail without embedding. Now I separated the conversion code into `FFmpegThumbnailsConvertorPP` which is why the code moved to ffmpeg.py

**Comment by pukkandan** [comment]
I forgot to close this...
