### ISSUE TITLE
Starting a youtube video (playback) with mpv takes above 5 seconds

### ISSUE THREAD

**Issue by geextahslex** [yt-dlp/yt-dlp#10205]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Starting a youtube video (playback) with mpv and yt-dlp takes above 5 seconds on average, is there a way to speed this up?
I don't use yt-dlp to download files only for youtube video playback in 1080p/1440p/4k VP9. 
On discord someone give me this line `--extractor-args "youtube:player_skip=webpage,configs,js;player_client=ios"` but this breaks the seek functionality.

Thank you :)

Information:
I'm on Windows 10 22H2 
latest nightly yt-dlp
mpv v0.38.0

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
As I use yt-dlp only with mpv, I don't know which command is going into yt-dlp
```

**Comment by bashonly** [comment]
No. Most of this startup time is yt-dlp decoding the nsig parameter, which is necessary for web client formats (or else their download speeds will be throttled to 30KB/s). The only alternative is the extractor-args given to you on discord.
