### ISSUE TITLE
nsfw

### ISSUE THREAD

**Issue by octavo** [yt-dlp/yt-dlp#10211]
The user would like to download from all nsfw sites. The user would like to dl all videos from a channel.

**Comment by seproDev** [comment]
Do not delete the issue template.

"all nsfw sites" is also not a valid request. You can open a request for a single site, but not just say all sites should be supported.

**Comment by octavo** [comment]
The user imagines most users would want most sites supported. The user currently wastes a lot of time like this.

**Comment by octavo** [comment]
Start with theporndude.
