### ISSUE TITLE
Downloads from boosty no more works

### ISSUE THREAD

**Issue by martinmikula** [yt-dlp/yt-dlp#10218]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Europe

### Provide a description that is worded well enough to be understood

Videos from Boosty no more works, some time ago I sucessfully downloaded videos from the page by extracting "United video ID" and added it to "http://ok.ru/videoembed/" but now I'm getting error: "The author of this video has not been found or is blocked" But from boosty I still can download the video.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
e:\___down>yt-dlp.exe --cookies cookies.txt  http://ok.ru/videoembed/7968824568349 -vU
[debug] Command-line config: ['--cookies', 'cookies.txt', 'http://ok.ru/videoembed/7968824568349', '-vU']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.06.17.232743 from yt-dlp/yt-dlp-nightly-builds [90c3721a3] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22631-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 6.1.1-full_build-www.gyan.dev (setts), ffprobe 6.1.1-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.06.02, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1823 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.06.17.232743 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.06.17.232743 from yt-dlp/yt-dlp-nightly-builds)
[Odnoklassniki] Extracting URL: http://ok.ru/videoembed/7968824568349
[Odnoklassniki] 7968824568349: Downloading desktop webpage
[Odnoklassniki] 7968824568349: Downloading desktop webpage
[Odnoklassniki] 7968824568349: Downloading mobile webpage
ERROR: [Odnoklassniki] 7968824568349: The author of this video has not been found or is blocked
  File "yt_dlp\extractor\common.py", line 740, in extract
  File "yt_dlp\extractor\odnoklassniki.py", line 252, in _real_extract
  File "yt_dlp\extractor\odnoklassniki.py", line 246, in _real_extract
  File "yt_dlp\extractor\odnoklassniki.py", line 273, in _extract_desktop
  File "yt_dlp\extractor\odnoklassniki.py", line 275, in _extract_desktop
```

**Comment by bashonly** [comment]
Does that URL work in browser?

Have you tried the actual boosty URL?

**Comment by martinmikula** [comment]
The boosty url works. 
The ok.ru/videoembed url does't... same error as from downloader...

**Comment by martinmikula** [comment]
@bashonly Why you closed the bug? boosty is on list of supported pages, and doesn't work... I dont understand...

**Comment by bashonly** [comment]
You said the boosty URL works. Boosty is supported. Manually constructing a URL that doesn't even load in your browser is not supported.

**Comment by martinmikula** [comment]
OK sorry, my fault, i thought that boosty is supported only by creating this "download url", but now i tried to pass a direct boosty url and it works... So thank you very much for your time ....

**Comment by eraction** [comment]
How u can download from boosty? With subscription?
