### ISSUE TITLE
Pond5 403 error

### ISSUE THREAD

**Issue by mikerusuk** [yt-dlp/yt-dlp#10212]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

UK

### Provide a description that is worded well enough to be understood

I don't believe the site is officially supported but I've previously been able to download watermarked clips from pond5.com using the generic extractor.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--cookies', '/Users/Mike/Desktop/ytcookies.txt', '-o', '/Volumes/MT/Cunk QFM/ARCHIVE - SCREENERS/FOOTAGE//Bluesky timelapse.%(ext)s', 'https://www.pond5.com/stock-footage/item/105265362-day-night-cloudy-blue-sky-time-lapse-8k']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.06.17.232743 from yt-dlp/yt-dlp-nightly-builds [90c3721a3] (pip)
[debug] Python 3.10.9 (CPython x86_64 64bit) - macOS-10.15.7-x86_64-i386-64bit (OpenSSL 1.1.1t  7 Feb 2023)
[debug] exe versions: ffmpeg N-106633-g25d3f96db7-tessus (setts), rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.19.0, brotli-None, certifi-2022.12.07, mutagen-1.47.0, requests-2.32.3, sqlite3-3.40.1, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1823 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.06.17.232743 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.06.17.232743 from yt-dlp/yt-dlp-nightly-builds)
[generic] Extracting URL: https://www.pond5.com/stock-footage/item/105265362-day-night-cloudy-blue-sky-time-lapse-8k
[generic] 105265362-day-night-cloudy-blue-sky-time-lapse-8k: Downloading webpage
ERROR: [generic] Unable to download webpage: HTTP Error 403: HTTP Forbidden (caused by <HTTPError 403: HTTP Forbidden>)
  File "/Users/Mike/anaconda3/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 740, in extract
    ie_result = self._real_extract(url)
  File "/Users/Mike/anaconda3/lib/python3.10/site-packages/yt_dlp/extractor/generic.py", line 2383, in _real_extract
    full_response = self._request_webpage(url, video_id, headers=filter_dict({
  File "/Users/Mike/anaconda3/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 909, in _request_webpage
    raise ExtractorError(errmsg, cause=err)

  File "/Users/Mike/anaconda3/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 896, in _request_webpage
    return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query, extensions))
  File "/Users/Mike/anaconda3/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 4141, in urlopen
    return self._request_director.send(req)
  File "/Users/Mike/anaconda3/lib/python3.10/site-packages/yt_dlp/networking/common.py", line 117, in send
    response = handler.send(request)
  File "/Users/Mike/anaconda3/lib/python3.10/site-packages/yt_dlp/networking/_helper.py", line 208, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/Mike/anaconda3/lib/python3.10/site-packages/yt_dlp/networking/common.py", line 337, in send
    return self._send(request)
  File "/Users/Mike/anaconda3/lib/python3.10/site-packages/yt_dlp/networking/_requests.py", line 363, in _send
    raise HTTPError(res, redirect_loop=max_redirects_exceeded)
yt_dlp.networking.exceptions.HTTPError: HTTP Error 403: HTTP Forbidden
```

**Comment by seproDev** [comment]
I get a captcha when accessing the site through the browser. Can you try with passing cookies?

**Comment by mikerusuk** [comment]
Thankyou! I had been using an exported cookies .txt which didn't work but if I pass cookies from chrome with --cookies-from-browser then it does work. Thanks very much!
