### ISSUE TITLE
[tiktok] Found a new way to get information about TikTok videos

### ISSUE THREAD

**Issue by valsoray-dev** [yt-dlp/yt-dlp#10213]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a site-specific feature
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Ukraine (any region)

### Example URLs

https://www.tiktok.com/@nickcheo/video/7376024324995583275

### Provide a description that is worded well enough to be understood

I was developing [my TikTok bot](https://github.com/valsoray-dev/tiktok-telegram-bot) and had an idea: install TikTok app on an emulator and see what kind of requests it sends. That's where I found this.

When after installing the app go to someone's video link, the app sends a request to the URL https://api16-normal-c-useast1a.tiktokv.com/aweme/v1/multi/aweme/detail/.

This link works the same as https://api16-normal-c-useast1a.tiktokv.com/aweme/v1/feed/, only the information is under the `aweme_details` key instead of `aweme_list`. It is also much faster to get information about a single video.

Here is the Python code that executes the HTTP request and retrieves the information. I haven't deleted or edited anything. This is what the application itself sends.
<details>
  <summary>Code</summary>
  
```python
import requests

url = "https://api16-normal-c-useast1a.tiktokv.com/aweme/v1/multi/aweme/detail/"

querystring = {
    "share_link_mode": "0",
    "share_scene": "0",
    "iid": "7379691220551141126",
    "device_id": "7379690547022071302",
    "ac": "wifi",
    "channel": "googleplay",
    "aid": "1233",
    "app_name": "musical_ly",
    "version_code": "350103",
    "version_name": "35.1.3",
    "device_platform": "android",
    "os": "android",
    "ab_version": "35.1.3",
    "ssmix": "a",
    "device_type": "SM-S908E",
    "device_brand": "samsung",
    "language": "en",
    "os_api": "30",
    "os_version": "11",
    "openudid": "4c46c774503965f8",
    "manifest_version_code": "2023501030",
    "resolution": "900*1600",
    "dpi": "240",
    "update_version_code": "2023501030",
    "_rticket": "1718273816183",
    "is_pad": "0",
    "app_type": "normal",
    "sys_region": "US",
    "last_install_time": "1718273808",
    "mcc_mnc": "25503",
    "timezone_name": "Europe/Kiev",
    "carrier_region_v2": "255",
    "app_language": "en",
    "carrier_region": "UA",
    "ac2": "wifi",
    "uoo": "0",
    "op_region": "UA",
    "timezone_offset": "7200",
    "build_number": "35.1.3",
    "host_abi": "arm64-v8a",
    "locale": "en",
    "region": "US",
    "ts": "1718273816",
    "cdid": "39fb5902-bc71-4208-a747-943d8adf36f1",
}

payload = {"aweme_ids": "[7376024324995583275]", "request_source": "0"}
headers = {
    "content-type": "application/x-www-form-urlencoded",
    "User-Agent": "com.zhiliaoapp.musically/2023501030 (Linux; U; Android 11; en_US; SM-S908E; Build/TP1A.220624.014;tt-ok/3.12.13.4-tiktok)",
    # "Accept-Encoding": "gzip",
    "x-ss-stub": "283E030174AB338BE965B69CA020F4E6",
    "x-metasec-event-source": "native",
    "x-tt-dm-status": "login=0;ct=0;rt=7",
    "x-ss-req-ticket": "1718273816184",
    "pns_event_id": "47",
    "sdk-version": "2",
    "passport-sdk-version": "6010290",
    "x-vc-bdturing-sdk-version": "2.3.8.i18n",
    "x-tt-store-region": "ua",
    "x-tt-store-region-src": "did",
    "x-ladon": "0TQZbk4uxQ2DltctzSqlpCS5wNiFZ7dicnkqySjFkaot8mLi",
    "x-khronos": "1718273815",
    "x-argus": "pfIJ2xwIO6Ho5rZkeu+HJYzghEEK4qEA22zpk90ccOFaJo0WJxvU4batIlghDSUyscq1pn6nAJBgHzAjOAr3opbo2gr8inpKW1VT0C7jJuYdGXtXfL3B8PcLB+m+8qgtMl8n1CusUXGFbD/hB9Ek+HTbbF1RufzTi/y2egBh+Gk3er3GxtgxUx4bnVP1rmtpnevm2iqiSJ0WwDe1WTQIuH+KaMB2ea1DtkyLsCRPQAWTbYiG3TElXiN5A3YNJXZTC+nAKmiDIiG6xgaPWTeV0mDydWrCg/CQ9nkaUCNjEdMBUoL4HqBifUQGhCj8XX9o5xaZs7QSnsAsBK3sV+ThDNt2KysqwdpiXPe7JYPDmewuvQi1fNwV7lonHi//flWnnxsncDci4gOq3CAQsEVitzdjI6LQUoW7tejlP6JJ2/y6vPmF4llI7aC6g7frCymwUhUC/Q/FUDrMy1uhY5WhGuPrJ/X5VOpNESOnquW4qHNSorsxQ21C9ycKQZvXKu89kPM=",
    "x-gorgon": "8404f0d300005f1de9dc07392657e3f83e5e6d3284a5dc262b7c",
    "Cookie": "store-idc=maliva; store-country-code-src=did; install_id=7379691220551141126; ttreq=1$02c3b70a7a75b25ed742e911484151dbcba1cd54; passport_csrf_token=b2e58c2d34688d973e1cacf8bbf4d0df; passport_csrf_token_default=b2e58c2d34688d973e1cacf8bbf4d0df; tt-target-idc=useast1a; msToken=BngELOreD4LyxuRZDXDrspUiD8IC_Oboev6AX1hU80ZHoXHMTTNZxnhW5jy_E1TVpM_fx9HY8972YiNLYJTACA4NHC0VJPL5keyDkT3lrUI143uVUIGI54oM; odin_tt=f5598b49ae9879b44e4f6072e7634c8a598d064d5eb31e3f92cecbbee87f0a896d57ce91705e584cd091b16c21a7312d75c74c9ba2f132d4bc67b740af7d7a0d5c9b15c695e336e6dbb6a782f637dd5d",
}

response = requests.post(url, data=payload, headers=headers, params=querystring)

print(response.json())
```
</details>

It is also possible to make a GET request instead of POST. Just need to make `aweme_ids` as part of URL params.
The only headers needed are `Content-Type`, `User-Agent` and `X-Argus` (can be just empty, not tested). I won't say anything about URL parameters, I haven't tested them much.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.tiktok.com/@nickcheo/video/7376024324995583275']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.05.27 from yt-dlp/yt-dlp [12b248ce6]
[debug] Python 3.12.4 (CPython x86_64 64bit) - Linux-6.9.5-zen1-1-zen-x86_64-with-glibc2.39 (OpenSSL 3.3.1 4 Jun 2024, glibc 2.39)
[debug] exe versions: ffmpeg 6.1.1 (setts), ffprobe 6.1.1
[debug] Optional libraries: certifi-2024.06.02, requests-2.32.3, sqlite3-3.46.0, urllib3-1.26.18
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Loaded 1820 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.05.27 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.05.27 from yt-dlp/yt-dlp)
[TikTok] Extracting URL: https://www.tiktok.com/@nickcheo/video/7376024324995583275
[TikTok] 7376024324995583275: Downloading webpage
[debug] [TikTok] Found universal data for rehydration
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 7376024324995583275: Downloading 1 format(s): bytevc1_1080p_707997-1
[debug] Invoking http downloader on "https://v19-webapp-prime.tiktok.com/video/tos/maliva/tos-maliva-ve-0068c799-us/oA0KcASWnpQTMiEzpLifBAwcF6yZHDItIEBwCX/?a=1988&bti=ODszNWYuMDE6&ch=0&cr=3&dr=0&lr=unwatermarked&cd=0%7C0%7C0%7C&cv=1&br=1382&bt=691&cs=2&ds=4&ft=4fUEKMzD8Zmo0Eoo9-4jVbJFppWrKsd.&mime_type=video_mp4&qs=15&rc=NjY7ODU4OWZlZjU8ZDg3ZEBpajhrd2o5cmVoczMzZzczNEBjMS4zYjBeXzIxXl82LmFjYSMuMS5qMmRzNGJgLS1kMS9zcw%3D%3D&btag=e00088000&expire=1718819808&l=202406191155542EE7E9BBC5FDF502F82E&ply_type=2&policy=2&signature=ddabba11b9b4db5517cc053f6c7d9b0a&tk=tt_chain_token"
[download] Destination: Sometimes i get sad [7376024324995583275].mp4
[download] 100% of    4.40MiB in 00:00:01 at 4.09MiB/s
```

**Comment by bashonly** [comment]
> The only headers needed are `Content-Type`, `User-Agent` and `X-Argus` (can be just empty, not tested).

Are you sure that would work reliably? `X-Argus` and `X-Gorgon` are security parameters used to lock down this endpoint. I get an empty response without the security headers / cookies.

**Comment by valsoray-dev** [comment]
> Are you sure that would work reliably? `X-Argus` and `X-Gorgon` are security parameters used to lock down this endpoint. I get an empty response without the security headers / cookies.

In my case, only X-Argus is needed. I tried to make it empty or just put a space - it works, and I get the result. I tried it from my IP and from a VPN in the US.

**Comment by seproDev** [comment]
I was able to replicate your findings in that the signature parameters are currently seemingly not checked.
This still leaves the problems of having users provide their own IID and device ID, as these are checked. The last time the yt-dlp extractor included IIDs they were banned in a short time.

**Comment by bashonly** [comment]
#10216

**Comment by JackFromPremiumdev** [comment]
@valsoray-dev , can you please specify the steps used to find the "aweme_details" endpoint, i did the same as you mentioned using ssl unpinning + burp, but when i click on someone's video i can't intercept the "aweme_details" endpoint !

**Comment by valsoray-dev** [comment]
> @valsoray-dev , can you please specify the steps used to find the "aweme_details" endpoint, i did the same as you mentioned using ssl unpinning + burp, but when i click on someone's video i can't intercept the "aweme_details" endpoint !

My way works half the time.

I'm using a rooted Bluestacks ([tutorial](https://github.com/RobThePCGuy/Root-Bluestacks-with-Kitsune-Mask)). I manage to get this endpoint when I clear all data of Google Play services and TikTok. Then I get the shortened link from the app and paste it into the browser. I am prompted to open the app. A sign appears in the app with two buttons, “Watch and Follow” and “Watch only”. When I select the second button, that endpoint appears in my traffic tracking program. If it didn't work the first time, you can try again.

You can also use this method to generate Install ID and Device ID.

**Comment by JackFromPremiumdev** [comment]
> > @valsoray-dev , can you please specify the steps used to find the "aweme_details" endpoint, i did the same as you mentioned using ssl unpinning + burp, but when i click on someone's video i can't intercept the "aweme_details" endpoint !
> 
> My way works half the time.
> 
> I'm using a rooted Bluestacks ([tutorial](https://github.com/RobThePCGuy/Root-Bluestacks-with-Kitsune-Mask)). I manage to get this endpoint when I clear all data of Google Play services and TikTok. Then I get the shortened link from the app and paste it into the browser. I am prompted to open the app. A sign appears in the app with two buttons, “Watch and Follow” and “Watch only”. When I select the second button, that endpoint appears in my traffic tracking program. If it didn't work the first time, you can try again.
> 
> You can also use this method to generate Install ID and Device ID.

Thankk you for the replay! does the tiktok prompt automatically when pasting a vm.tiktok link in the browser? you stated that you get two option one of them is follow, so you don't just install tiktok , you log in it ?
