### ISSUE TITLE
Facebook Reel d/l : 'No video formats found!'

### ISSUE THREAD

**Issue by t0ben** [yt-dlp/yt-dlp#10227]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

EMEA

### Provide a description that is worded well enough to be understood

Cannot d/l any Reels anymore, tried with stable and GIT.
ERROR: [facebook] 1236746517731698: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-Uv', 'https://www.facebook.com/reel/1236746517731698']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.05.27 from yt-dlp/yt-dlp [12b248ce6]
[debug] Python 3.12.3 (CPython x86_64 64bit) - Linux-6.9.3-3-MANJARO-x86_64-with-glibc2.39 (OpenSSL 3.3.0 9 Apr 2024, glibc 2.39)
[debug] exe versions: ffmpeg 6.1.1 (setts), ffprobe 6.1.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.20.0, brotlicffi-1.1.0.0, certifi-2024.02.02, requests-2.32.3, sqlite3-3.46.0, urllib3-1.26.18
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Loaded 1823 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.05.27 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.05.27 from yt-dlp/yt-dlp)
[facebook:reel] Extracting URL: https://www.facebook.com/reel/1236746517731698
[facebook] Extracting URL: https://m.facebook.com/watch/?v=1236746517731698&_rdr
[facebook] 1236746517731698: Downloading webpage
ERROR: [facebook] 1236746517731698: ; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 1605, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 1761, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 1820, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 2825, in process_video_result
    self.raise_no_formats(info_dict)
  File "/usr/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 1103, in raise_no_formats
    raise ExtractorError(msg, video_id=info['id'], ie=info['extractor'],
yt_dlp.utils.ExtractorError: [facebook] 1236746517731698: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

**Comment by balkisanton** [comment]
Same issue, please fix this. Thank you

**Comment by bashonly** [comment]
extractor needs this patch
```diff
diff --git a/yt_dlp/extractor/facebook.py b/yt_dlp/extractor/facebook.py
index 1d1e0770a..98a1aaca9 100644
--- a/yt_dlp/extractor/facebook.py
+++ b/yt_dlp/extractor/facebook.py
@@ -621,6 +621,8 @@ def parse_graphql_video(video):
                                 'url': playable_url,
                             })
                     extract_dash_manifest(video, formats)
+                    if not formats:
+                        return
 
                     automatic_captions, subtitles = {}, {}
                     is_broadcast = traverse_obj(video, ('is_video_broadcast', {bool}))
```

**Comment by bashonly** [comment]
update to latest nightly

```
yt-dlp --update-to nightly
```

or

```
python -m pip install -U --pre "yt-dlp[default]"
```

or update your AUR package etc

**Comment by biggestsonicfan** [comment]
So I am downloading reels as MP4s but they're actually WEBMs?

`yt-dlp -f "bv*[ext=mp4]+ba[ext=m4a]/b[ext=mp4] / bv*+ba/b" -S "ext" -P "path" --compat-options filename-sanitization -o "[%(id)s] - %(title).200B%(title.201B&…|)s.%(ext)s" [URL]`

https://github.com/yt-dlp/yt-dlp/assets/9744201/dd07da6a-b9ff-484c-9f96-80e9befa603d

**Comment by bashonly** [comment]
@biggestsonicfan It's not a webm. It's av01 video in an mp4 container. Facebook has been experimenting with different encodings of their videos. If you prefer avc/h264, then pass a Firefox user agent with `--user-agent`

**Comment by biggestsonicfan** [comment]
Ah, that did the trick. Thanks much!

**Comment by scrutinizer11** [comment]
I got the same error, word for word. yt-dlp 20240527.

**Comment by seproDev** [comment]
@scrutinizer11 Update to nightly
```
yt-dlp --update-to nightly
```

**Comment by scrutinizer11** [comment]
Thanks, I'll wait for the daily one.

**Comment by seproDev** [comment]
I'm not sure what you mean. Nightly are the daily releases. This has been fixed 5 days ago and is already part of the current nightly releases.

**Comment by scrutinizer11** [comment]
Isn't **yt-dlp -U** supposed to update it?

**Comment by bashonly** [comment]
`yt-dlp -U` will work if you're already on the nightly channel. `yt-dlp --update-to nightly` will update to the nightly channel. We recommend all users to use the nightly channel.

**Comment by scrutinizer11** [comment]
I'm learning about this for the first time. 

So, I'll stick with the stable channel. updating via a single U option has been the way forever.

**Comment by bashonly** [comment]
If you run `yt-dlp --update-to nightly` ONCE, then every time you run `yt-dlp -U` after that you will be updating to the new nightly release. This is what we recommend all users to be doing. "stable" is a misnomer and is actually out-of-date and more bug-ridden than the latest nightly.

**Comment by chx** [comment]
I am running the latest nightly, I still can't download a private reel, I tried with `--user-agent 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:127.0) Gecko/20100101 Firefox/127.0'` as well. Should I open a new issue?

[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.07.13.232701 from yt-dlp/yt-dlp-nightly-builds [150ecc45d] (zip)
[debug] Python 3.10.12 (CPython x86_64 64bit) - Linux-5.15.146.1-microsoft-standard-WSL2-x86_64-with-glibc2.35 (OpenSSL 1.1.1f  31 Mar 2020, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2
[debug] Optional libraries: Cryptodome-3.19.0, certifi-2020.06.20, requests-2.25.1, secretstorage-3.3.1, sqlite3-3.46.0, urllib3-1.26.5
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Loaded 1834 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.07.13.232701 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.07.13.232701 from yt-dlp/yt-dlp-nightly-builds)
[facebook:reel] Extracting URL: https://www.facebook.com/reel/1153199615970750
[facebook] Extracting URL: https://m.facebook.com/watch/?v=1153199615970750&_rdr
[facebook] 1153199615970750: Downloading webpage
ERROR: [facebook] 1153199615970750: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/yt_dlp/YoutubeDL.py", line 1622, in wrapper
    return func(self, *args, **kwargs)

**Comment by seproDev** [comment]
@chx To download private videos, you will need to pass cookies. Either with `--cookies-from-browser` or `--cookies`. If you still run in to problems, please create a new issue.

**Comment by chx** [comment]
Sorry for the noise. I did pass cookies but didn't realize the cookie downloader extension I use broke :/

**Comment by biggestsonicfan** [comment]
Having the issue again where mp4's can't be uploaded as embeds in Discord, and it's about a 50% chance the video/reel will throw a `WARNING: [facebook] unable to extract uploader; please report this issue` and not extract metadata for filename information when using `--cookies-from-browser`. 
Bash script is as follows:
```
#!/bin/bash
yt-dlp --user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:129.0) Gecko/20100101 Firefox/129.0" \
--cookies-from-browser "firefox:/dir/to/firefox/in/windows/from/wsl" \
-f "bv*[ext=mp4]+ba[ext=m4a]/b[ext=mp4] / bv*+ba/b" -S "ext" -P "/output/directory/via/wsl/fb/" \
--compat-options filename-sanitization -o "[%(id)s] - %(title).200B%(title.201B&…|)s.%(ext)s" $1
```
