### ISSUE TITLE
how to download m3u8 by yt-dlp with AES encryption key + IV

### ISSUE THREAD

**Issue by ETapk** [yt-dlp/yt-dlp#10222]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

how to download m3u8 by yt-dlp with AES encryption key + IV

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
What have you tried? Running `yt-dlp "URL"` would be a good place to start

**Comment by ETapk** [comment]
this encryption technique is used in jiocinema voot content

**Comment by bashonly** [comment]
yt-dlp supports jiocinema. Try passing the webpage URL. Show a verbose log if it doesn't work. This issue will be closed if you don't provide a log or more details

**Comment by bashonly** [comment]
> but yt-dlp doesn't support the website.

Yes, [**it does**](https://github.com/yt-dlp/yt-dlp/blob/master/yt_dlp/extractor/jiocinema.py)

**Comment by gohil-mitul** [comment]
@ETapk can you please explain how this script works ? Consider my knowledge in coding as a beginner.
I want to download https://www.jiocinema.com/tv-shows/parichay/3498521 which is nowhere to be found except jio and it cannot be accessed outside India.
Thanks.
