### ISSUE TITLE
yt-dlp can't seek in streams.

### ISSUE THREAD

**Issue by zhouxinghong** [yt-dlp/yt-dlp#10236]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

It is not possible to locate the position of the video during the playback of live streaming video, for example, fast forward, rewind, jump to a certain time period of the video according to the specified time, and other functions.
For example, the following operations:
`yt-dlp -f bestvideo+bestaudio "https://www.youtube.com/watch?v=y6oMutwJQCw" -o - | "F:\tool\Player\mpv.exe" -`
![image](https://github.com/mpv-player/mpv/assets/54253524/f2d341f2-16e0-4882-9ba7-e2b244befdb3)

yt-dlp is a very good video player software, thanks to all of you who keep contributing to the yt-dlp project!🎉👍🏆🌹

Windows 10 19044

mpv v0.38.0-512-gbab9b2cf Copyright © 2000-2024 mpv/MPlayer/mplayer2 projects
built on Jun 20 2024 14:28:45
libplacebo version: v7.349.0 (v7.349.0-rc1-3-g1fd3c7b-dirty)
FFmpeg version: N-115967-g35df214a7
FFmpeg library versions:
libavutil 59.24.103
libavcodec 61.8.100
libavformat 61.3.104
libswscale 8.2.100
libavfilter 10.2.102
libswresample 5.2.100

yt-dlp Latest nightly version

Introduced in version: Video specs are Vertical 4K 60 FPS `https://www.youtube.com/watch?v=y6oMutwJQCw`

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
Windows 10 19044

mpv v0.38.0-512-gbab9b2cf Copyright © 2000-2024 mpv/MPlayer/mplayer2 projects
built on Jun 20 2024 14:28:45
libplacebo version: v7.349.0 (v7.349.0-rc1-3-g1fd3c7b-dirty)
FFmpeg version: N-115967-g35df214a7
FFmpeg library versions:
libavutil 59.24.103
libavcodec 61.8.100
libavformat 61.3.104
libswscale 8.2.100
libavfilter 10.2.102
libswresample 5.2.100

yt-dlp Latest nightly version

Introduced in version: Video specs are Vertical 4K 60 FPS `https://www.youtube.com/watch?v=y6oMutwJQCw`
```

```
C:\WINDOWS\system32>yt-dlp -f bestvideo+bestaudio "https://www.youtube.com/watch?v=y6oMutwJQCw" -o - | "F:\tool\Player\mpv.exe" -
[youtube] Extracting URL: https://www.youtube.com/watch?v=y6oMutwJQCw
[youtube] y6oMutwJQCw: Downloading webpage
[youtube] y6oMutwJQCw: Downloading ios player API JSON
[youtube] y6oMutwJQCw: Downloading m3u8 information
[info] y6oMutwJQCw: Downloading 1 format(s): 315+258
[download] Destination: -
Input #0, matroska,webm, from 'https://rr3---sn-oguesndr.googlevideo.com/videoplayback?expire=1719086629&ei=xdl2Zp-_BcDO2roP99KZ2AY&ip=95.85.94.80&id=o-AADcTyI4Gf1F38zE42QgNLJbTQbPznPrzG_8lqvPKrms&itag=315&aitags=133%2C134%2C135%2C136%2C160%2C242%2C243%2C244%2C247%2C278%2C298%2C299%2C302%2C303%2C308%2C315%2C394%2C395%2C396%2C397%2C398%2C399%2C400%2C401&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=xb&mm=31%2C26&mn=sn-oguesndr%2Csn-npoe7nsr&ms=au%2Conr&mv=m&mvi=3&pl=24&initcwndbps=2026250&bui=AbKP-1N37vmWHXmCD9JOx7U0Q6Mhk8hMEz_6ai6rFNXg45m1obeMXMNcH68_0izicppD_OLtsfeFS073&spc=UWF9f73mCI2EJI5RNxe407U83hRRaAMOXibiKF2ja5ggkpPDv0ylC41LMonl&vprv=1&svpuc=1&mime=video%2Fwebm&ns=Rg7BxhXHLy87rg3ngzzu0yIQ&rqh=1&gir=yes&clen=5004916807&dur=1503.249&lmt=1712377863019563&mt=1719064623&fvip=5&keepalive=yes&c=WEB&sefc=1&txp=4432434&n=VLaFfDQeFiX1pA&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cxpc%2Cbui%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cns%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRQIgRe93vjNvnPMNg8dDIZF-hbfNxYUFP_5sIkZYZxSbWd0CIQCzJf_p_IUG1Un4ODUTnrr8QSfg8H-OSyQ_JEwuhUIJMA%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AHlkHjAwRQIgF3uh4YmTS70E-ynSdUuNBtqrZczOU76rZSOl-8yx67QCIQCnQnXsr_GXJw6LFjsdmfmgCJzYSi2sUIyR1UzF3a3iUw%3D%3D':
  Metadata:
    encoder         : google/video-file
  Duration: 00:25:03.25, start: 0.000000, bitrate: 26635 kb/s
  Stream #0:0(eng): Video: vp9 (Profile 0), yuv420p(tv, bt709), 2160x3840, SAR 1:1 DAR 9:16, 60 fps, 60 tbr, 1k tbn (default)
Input #1, mov,mp4,m4a,3gp,3g2,mj2, from 'https://rr3---sn-oguesndr.googlevideo.com/videoplayback?expire=1719086629&ei=xdl2Zp-_BcDO2roP99KZ2AY&ip=95.85.94.80&id=o-AADcTyI4Gf1F38zE42QgNLJbTQbPznPrzG_8lqvPKrms&itag=258&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=xb&mm=31%2C26&mn=sn-oguesndr%2Csn-npoe7nsr&ms=au%2Conr&mv=m&mvi=3&pl=24&initcwndbps=2026250&bui=AbKP-1N37vmWHXmCD9JOx7U0Q6Mhk8hMEz_6ai6rFNXg45m1obeMXMNcH68_0izicppD_OLtsfeFS073&spc=UWF9f73mCI2EJI5RNxe407U83hRRaAMOXibiKF2ja5ggkpPDv0ylC41LMonl&vprv=1&svpuc=1&mime=audio%2Fmp4&ns=Rg7BxhXHLy87rg3ngzzu0yIQ&rqh=1&gir=yes&clen=72900704&dur=1503.701&lmt=1703058811780795&mt=1719064623&fvip=5&keepalive=yes&c=WEB&sefc=1&txp=5432434&n=VLaFfDQeFiX1pA&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cbui%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cns%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRQIgHO1qW9HNfSjHFRaeqF0Uh4A0y8Keo6r6INBErAQrhWICIQCpngFKDTfo1E91M8YvtXMjgo8SVt6OqG3cHavnuuauNg%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AHlkHjAwRQIgF3uh4YmTS70E-ynSdUuNBtqrZczOU76rZSOl-8yx67QCIQCnQnXsr_GXJw6LFjsdmfmgCJzYSi2sUIyR1UzF3a3iUw%3D%3D':
  Metadata:
    major_brand     : dash
    minor_version   : 0
    compatible_brands: iso6mp41
    creation_time   : 2023-12-20T07:41:32.000000Z
  Duration: 00:25:03.70, start: 0.000000, bitrate: 387 kb/s
  Stream #1:0[0x1](und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, 5.1, fltp, 386 kb/s (default)
      Metadata:
        creation_time   : 2023-12-20T07:41:32.000000Z
        handler_name    : ISO Media file produced by Google Inc.
        vendor_id       : [0][0][0][0]
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #1:0 -> #0:1 (copy)
Output #0, matroska, to 'pipe:':
  Metadata:
    encoder         : Lavf61.3.104
  Stream #0:0(eng): Video: vp9 (Profile 0) (VP90 / 0x30395056), yuv420p(tv, bt709), 2160x3840 [SAR 1:1 DAR 9:16], q=2-31, 60 fps, 60 tbr, 1k tbn (default)
  Stream #0:1(und): Audio: aac (LC) ([255][0][0][0] / 0x00FF), 48000 Hz, 5.1, fltp, 386 kb/s (default)
      Metadata:
        creation_time   : 2023-12-20T07:41:32.000000Z
        handler_name    : ISO Media file produced by Google Inc.
        vendor_id       : [0][0][0][0]
Press [q] to stop, [?] for help
[vost#0:0/copy @ 000001f3cc7ae840] Error submitting a packet to the muxer: Broken pipe
    Last message repeated 1 times
[out#0/matroska @ 000001f3cc6f9980] Error muxing a packet
[out#0/matroska @ 000001f3cc6f9980] Task finished with error code: -32 (Broken pipe)
[out#0/matroska @ 000001f3cc6f9980] Terminating thread with return code -32 (Broken pipe)
[out#0/matroska @ 000001f3cc6f9980] Error writing trailer: Broken pipe
[out#0/matroska @ 000001f3cc6f9980] Error closing file: Broken pipe
[out#0/matroska @ 000001f3cc6f9980] video:24035KiB audio:343KiB subtitle:0KiB other streams:0KiB global headers:0KiB muxing overhead: unknown
size=   24106KiB time=00:00:07.23 bitrate=27302.2kbits/s speed=0.39x
Conversion failed!


ERROR: ffmpeg exited with code 4294967264


C:\WINDOWS\system32>
```

**Comment by bashonly** [comment]
Yes, when you pipe output from yt-dlp it is not seekable. This is expected, since it is a linear stream of video data being piped to your media player. 

If you want seekable video in your player, then either 1. use mpv directly (since it uses yt-dlp under the hood) e.g. `mpv "ytdl://URL"`, or 2. `--print urls` with yt-dlp and pass the direct stream URL(s) to your media player

**Comment by zhouxinghong** [comment]
Thank you very much for your help! 😜🏆👍🎉💗 I don't want to use the mpv "ytdl://URL" method because it's slow and requires waiting for the video to buffer.

I want to use `yt-dlp -f bestvideo+bestaudio "https://xxxxxxx` this way to play the stream directly because it is direct piped and very fast thus not needing to wait for the video to buffer to play the video, which on my computer it is such a satisfying result.

**Comment by bashonly** [comment]
Seeking isn't possible with piped input

**Comment by zhouxinghong** [comment]
Hello! I use this way `yt-dlp -f bestvideo+bestaudio --print "https://www.youtube.com/watch?v=y6oMutwJQCw" -o - | "F:\tool\Player\mpv.exe"` - why the error is always. Can you give example syntax?

**Comment by zhouxinghong** [comment]
Hello! I use this way `yt-dlp -f bestvideo+bestaudio --print "https://www.youtube.com/watch?v=y6oMutwJQCw" -o - | "F:\tool\Player\mpv.exe"` - why the error is always. Can you give example syntax?

Thank you very much!

**Comment by bashonly** [comment]
`mpv "https://www.youtube.com/watch?v=y6oMutwJQCw"`
