### ISSUE TITLE
File naming - %(channel)s results in NA

### ISSUE THREAD

**Issue by swingking03** [yt-dlp/yt-dlp#10249]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I am asking a question about the GUI as that repository is closed. When adding %channel(s) to the filename, it returns NA. This occurred on many links from many channels, so was not isolated to one channel.  

The full filename I am using is
`%(channel)s - %(title)s.%(ext)s`

What am I doing wrong?

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
This tracker does not offer support for any GUI (I don't even know which GUI you are talking about).

If you can reproduce the issue when using directly, please share the verbose output as instructed in the issue template. Otherwise this issue will need to be closed
