### ISSUE TITLE
[BiliBili] Migration to new API with WBI signature

### ISSUE THREAD

**Issue by grqx** [yt-dlp/yt-dlp#10243]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a site-specific feature
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Mainland China (All), anywhere else (Most content except for Bangumis)

### Example URLs

The issue applies to ALL `InfoExtractor`s except for `BilibiliSpaceVideoIE`([bilibili.py:983-1075](https://github.com/yt-dlp/yt-dlp/blob/a8520244b8642880e4d35925e9e49eff94d548de/yt_dlp/extractor/bilibili.py#L983-L1075), it is actually broken) and `BaseIE`s
In form of URL, the issue applies to ALL videos on site BiliBili that doesn't match `https?://space\.bilibili\.com/(?P<id>\d+)(?P<video>/video)?/?(?:[?#]|$)`
Several Examples of API: (__THIS IS URL OF API, NOT URL TO DOWNLOAD__)
https://api.bilibili.com/x/player/wbi/playurl
https://api.bilibili.com/x/space/wbi/arc/search

### What the problem is
To develop a robust and future-proof extractor code, we should prepare for migration to new APIs with WBI signatures. 
### How it could be fixed & How your proposed solution would look like
See this [Document](https://socialsisteryi.github.io/bilibili-API-collect/docs/misc/sign/wbi.html)<sup>[1]</sup>.
[Partial translation of the document, based on ChatGPT Translated result(WIP)](https://gist.github.com/grqx/8c57cb2265031aae7dd512e6295c30a3)

### Other Notes
* <sup>[1]</sup>: __BAC's document on BiliBili APIs__ is written by [SocialSisterYi](https://github.com/SocialSisterYi) under CC-BY-NC 4.0 license.
* I can't figure out anything to put in `Complete Verbose Output`, but it is a required field, so I put the error logs of `BilibiliSpaceVideoIE`([bilibili.py:983-1075](https://github.com/yt-dlp/yt-dlp/blob/a8520244b8642880e4d35925e9e49eff94d548de/yt_dlp/extractor/bilibili.py#L983-L1075)), which tried to use WBI signature but constantly gives error code `-352` (stands for: risk control verification failed(invalid User-Agent or WBI params))
* Detailed examples and discussions on handling these signatures can be found on the [GitHub discussion page](https://github.com/SocialSisterYi/bilibili-API-collect/discussions/920) and the related [issue page](https://github.com/SocialSisterYi/bilibili-API-collect/issues/910).

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://space.bilibili.com/59905809/video']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.05.27 from yt-dlp/yt-dlp (linux_exe)
[debug] Python 3.11.9 (CPython x86_64 64bit) - Linux-5.15.153.1-microsoft-standard-WSL2-x86_64-with (OpenSSL 3.1.4 24 Oct 2023)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.02.02, mutagen-1.47.0, requests-2.32.2, secretstorage-3.3.3, sqlite3-3.44.2, urllib3-2.2.1, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1820 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.05.27 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.05.27 from yt-dlp/yt-dlp)
[BilibiliSpaceVideo] Extracting URL: https://space.bilibili.com/59905809/video
[BilibiliSpaceVideo] 59905809: Downloading JSON metadata
[BilibiliSpaceVideo] 59905809: Downloading page 0
ERROR: [BilibiliSpaceVideo] 59905809: Request is blocked by server (352), please add cookies, wait and try later.
  File "yt_dlp/extractor/common.py", line 734, in extract
  File "yt_dlp/extractor/bilibili.py", line 1073, in _real_extract
  File "yt_dlp/extractor/bilibili.py", line 974, in _extract_playlist
  File "yt_dlp/extractor/bilibili.py", line 1056, in fetch_page
```

**Comment by seproDev** [comment]
I think that is actually being done in https://github.com/yt-dlp/yt-dlp/pull/9117

**Comment by c-basalt** [comment]
Use `--cookies` or `--cookies-from-browser` and try again

**Comment by grqx** [comment]
Solved by extracting cookies again. The previous cookies(not shown in the log) were invalid
