### ISSUE TITLE
ERROR: [vimeo:review] 962044490: Unable to extract clip page config; 

### ISSUE THREAD

**Issue by cacbarbieri** [yt-dlp/yt-dlp#10255]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United States

### Provide a description that is worded well enough to be understood

Only two of 8 videos in this Vimeo folder are giving this error. 

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [x] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--compat-options', 'no-certifi', '--video-password', 'PRIVATE', 'https://vimeo.com/simplyrhino/review/962044490/1d3fc75751']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.06.22.232706 from yt-dlp/yt-dlp-nightly-builds [a8520244b] (win_exe)
[debug] Compatibility options: no-certifi
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22631-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 7.0.1-essentials_build-www.gyan.dev (setts), ffprobe 7.0.1-essentials_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.06.02, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1823 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.06.22.232706 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.06.22.232706 from yt-dlp/yt-dlp-nightly-builds)
[vimeo:review] Extracting URL: https://vimeo.com/simplyrhino/review/962044490/1d3fc75751
[vimeo:review] 962044490: Downloading JSON metadata
[vimeo:review] 962044490: Downloading JSON metadata
[vimeo:review] 962044490: Verifying the password
ERROR: [vimeo:review] 962044490: Unable to extract clip page config; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 740, in extract
  File "yt_dlp\extractor\vimeo.py", line 1284, in _real_extract
  File "yt_dlp\extractor\common.py", line 1333, in _search_regex
```

**Comment by turekm** [comment]
i have the same issue for all private videos

15:54:54 michal@maminka:~/Downloads/delete# ./yt-dlp_linux --version
2024.06.24.232830
16:00:16 michal@maminka:~/Downloads/delete# ./yt-dlp_linux  --verbose  --video-password XYZ  https://vimeo.com/XYZ/review/936160560/32eefb75e4
[debug] Command-line config: ['--verbose', '--video-password', 'PRIVATE', 'https://vimeo.com/XYZ/review/936160560/32eefb75e4']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.06.24.232830 from yt-dlp/yt-dlp-nightly-builds (linux_exe)
[debug] Python 3.11.9 (CPython x86_64 64bit) - Linux-6.9.5-200.fc40.x86_64-x86_64-with (OpenSSL 3.1.5 30 Jan 2024)
[debug] exe versions: ffmpeg 6.1.1 (setts), ffprobe 6.1.1
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.06.02, mutagen-1.47.0, requests-2.32.3, secretstorage-3.3.3, sqlite3-3.44.2, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1823 extractors
[vimeo:review] Extracting URL: https://vimeo.com/XYZ/review/936160560/32eefb75e4
[vimeo:review] 936160560: Downloading JSON metadata
[vimeo:review] 936160560: Downloading JSON metadata
[vimeo:review] 936160560: Verifying the password
ERROR: [vimeo:review] 936160560: Unable to extract clip page config; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp/extractor/common.py", line 740, in extract
  File "yt_dlp/extractor/vimeo.py", line 1284, in _real_extract
  File "yt_dlp/extractor/common.py", line 1333, in _search_regex

**Comment by bashonly** [comment]
Fixed by c1c9bb4adb42d0d93a2fb5d93a7de0a87b6ba884

**Comment by bashonly** [comment]
Oops, my bad.

@tinybug would you be able to share the video password? Then I would hopefully be able to find what's going wrong & fix it.

If you don't want to share the password publicly, you can reach me on discord (same username) or via email:
`bashonly (at) proton mail (d o t) com`

**Comment by turekm** [comment]
for me it is still not working too, sorry i do not want to share video, but bellow there is my workaround which can be used for anyone :)

```
08:31:37 michal@maminka:~/Downloads/yt-dlp# ./yt-dlp_linux --version
2024.07.16
08:32:04 michal@maminka:~/Downloads/yt-dlp#  ./yt-dlp_linux  --verbose  --video-password XYZ  https://vimeo.com/blabla/review/908191123/bffbd3fdsa
[debug] Command-line config: ['--verbose', '--video-password', 'PRIVATE', 'https://vimeo.com/blabla/review/908191123/bffbd3fdsa']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.07.16 from yt-dlp/yt-dlp (linux_exe)
[debug] Python 3.11.9 (CPython x86_64 64bit) - Linux-6.9.8-200.fc40.x86_64-x86_64-with (OpenSSL 3.1.5 30 Jan 2024)
[debug] exe versions: ffmpeg 6.1.1 (setts), ffprobe 6.1.1
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.07.04, curl_cffi-0.7.1, mutagen-1.47.0, requests-2.32.3, secretstorage-3.3.3, sqlite3-3.44.2, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1829 extractors
[vimeo:review] Extracting URL: https://vimeo.com/blabla/review/908191123/bffbd3fdsa
[vimeo:review] 908191825: Downloading JSON metadata
[vimeo:review] 908191825: Downloading JSON metadata
[vimeo:review] 908191825: Submitting video password
ERROR: [vimeo:review] 908191825: Unable to extract clip page config; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp/extractor/common.py", line 740, in extract
  File "yt_dlp/extractor/vimeo.py", line 1297, in _real_extract
  File "yt_dlp/extractor/common.py", line 1333, in _search_regex

08:32:11 michal@maminka:~/Downloads/yt-dlp# 
```

but i found **workaround**

1) open video in firefox and press f12, tab network
2) play video, there are two link xhr (type mp4), one is sound and second is video, stop video
3) copy 2 links (one for video second for sound) and edit them that you delete end of links (delete "&range=2673-91013"
4) use yt-dlp to download these streams (put link into '' like 'https://....' )
5) use ffmpeg to merge two downloaded files 
`ffmpeg -i "2ea6f805-ac8e-4974-8bd2-a76763c6f861_[2ea6f805-ac8e-4974-8bd2-a76763c6f861].mp4" -i "da9f88ec-86a0-4512-baba-258a3f5ea45f_[da9f88ec-86a0-4512-baba-258a3f5ea45f].mp4"  -c:v copy -c:a aac -strict experimental "output.mp4"`

**Comment by bashonly** [comment]
The only way this will be fixed in yt-dlp is if someone is willing to share the video password for their link
