### ISSUE TITLE
How to merge fetched video and audio into one url when yt-dlp uses --get url  

### ISSUE THREAD

**Issue by zhouxinghong** [yt-dlp/yt-dlp#10259]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

yt-dlp how to merge the fetched video and audio into one url when using -f bestvideo+bestaudio --get url , this function is very useful for fetching youtube HD live streams, if it can't be achieved directly this way, is there any other workaround to achieve this? I hope I can get your careful help, thank you very much!

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
No

If your media player supports multiple inputs, you can pass the video URL and the audio URL as separate inputs to it. This is essentially what mpv's ytdl hook does.

This question seems very closely related to #10236. My advice: just pass the youtube URL directly to mpv

**Comment by zhouxinghong** [comment]
I would like to realize this requirement in vlc? Is there a way to do this?

**Comment by bashonly** [comment]
AFAIK it's not possible with VLC

Maybe what you want is format 96 and/or 95, the combined video+audio 1080p and 720p HLS formats, which are available when you pass `--extractor-arg "youtube:player_client=mediaconnect"`

**Comment by zhouxinghong** [comment]
yes !
Is it possible to give a detailed format for using the syntax, for example, the
ytdlp --extractor-arg "youtube:player_client=mediaconnect" xxxx

**Comment by bashonly** [comment]
using your example video url from the other issue:
```
yt-dlp --extractor-arg "youtube:player_client=mediaconnect" -f best --print url "https://www.youtube.com/watch?v=y6oMutwJQCw" | vlc -
```

**Comment by zhouxinghong** [comment]
It can serve the purpose, but the resolution of the live stream is only up to 1080p, is it possible to get a 4k live stream?

**Comment by bashonly** [comment]
No. Resolutions above 1080p are only available as separate video and audio streams

**Comment by zhouxinghong** [comment]
I understand!
Is it possible to raise this as a feature request?

**Comment by bashonly** [comment]
No, we can't change what youtube serves

**Comment by zhouxinghong** [comment]
OK! Thank you very much for your help and answers, teacher!🌹👍🏆😜

**Comment by Lieutenant-L-T-Smash** [comment]
@bashonly

> AFAIK it's not possible with VLC

Yes, it is. I'm using this with a short bash script to stream youtube vids with VLC. It should be possible to write a Windows cmd script to do the same.

VLC has an "experimental" command argument, `--input-slave=`, with which it's possible to play audio and video from separate sources simultaneously and synchronously. 

@zhouxinghong I hope you see this.

**Comment by zhouxinghong** [comment]
@bashonly Thank you very much for your help and guidance! You're very cool 🤞😜🍦🌹

**Comment by Lieutenant-L-T-Smash** [comment]
I used a more complex script to handle my case, but for the record, the following will work with split audio and video:

`yt-dlp -f 'ba,bv' --exec 'vlc --meta-title=%(title)#q --input-slave=%(requested_formats.0.url)#q %(requested_formats.1.url)#q' https://www.youtube.com/watch?v=some_id`

This command only works for exactly one audio and one video stream together. It needs more logic to handle additional items, or the possibility of a combined stream, if the exact number isn't known ahead of time.

**Comment by Lieutenant-L-T-Smash** [comment]
I used a more complex script to handle my case, but for the record, the following will work with split audio and video:

`yt-dlp -f ba+bv --simulate --exec video:'vlc --meta-title=%(title)#q --input-slave=%(requested_formats.0.url)#q %(requested_formats.1.url)#q' https://www.youtube.com/watch?v=some_id`

This command only works for exactly one audio and one video stream together. It needs more logic to handle additional items, or the possibility of a combined stream, if the exact number isn't known ahead of time.

**Comment by zhouxinghong** [comment]
@Lieutenant-L-T-Smash My teacher! This is very, very awesome! 😜🏆🎉👍
