### ISSUE TITLE
Skip downloaded files

### ISSUE THREAD

**Issue by beesuns** [yt-dlp/yt-dlp#10254]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### scenario
I put all the urls in a txt file and use the following line to download all the files.

```C:\Users\name\Videos>yt-dlp.exe -a C:\Users\name\Videos\二级翻译\list.txt```

But something went wrong, the download failed with some of the files downloaded and some not yet.

If I repeat the above line, I believe it will download all the files, including those already exist, which is not what I want.

### request

May I request a feature that can check if the file exist. If yes, skip; if not, continue to download.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by Grub4K** [comment]
`yt-dlp` will try and skip files that already exist, so if the settings didnt change and you are not downloading live streams and are in the same directory it will extract the video to get the title, but not redownload it if the file already exists

**Comment by seproDev** [comment]
If you download large amounts of videos, it is also recommended to use `--download-archive`. That way, all downloaded videos will be recorded by ID, so you don't need to extract them again, saving on time and API requests.
