### ISSUE TITLE
YouTube Music album link not resolved to playlist link

### ISSUE THREAD

**Issue by orenai** [yt-dlp/yt-dlp#10269]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

USA

### Provide a description that is worded well enough to be understood

Using album link for downloading albums is currently broken.
The issue happens because YT-DLP cannot resolve album link (such as https://music.youtube.com/browse/MPREb_Biju2UFlzmN) to playlist link (https://music.youtube.com/playlist?list=OLAK5uy_m9LnI0msIFVz-Px8V4mxuYeKDC0gemgM0) which works fine.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://music.youtube.com/browse/MPREb_Biju2UFlzmN']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.06.24.232830 from yt-dlp/yt-dlp-nightly-builds [f3411af12] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 6.1.1-essentials_build-www.gyan.dev (setts)
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.06.02, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1823 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.06.24.232830 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.06.24.232830 from yt-dlp/yt-dlp-nightly-builds)
[youtube:tab] Extracting URL: https://music.youtube.com/browse/MPREb_Biju2UFlzmN
[youtube:tab] MPREb_Biju2UFlzmN: Downloading API parameters API JSON
[youtube:tab] MPREb_Biju2UFlzmN: Downloading API JSON
ERROR: [youtube:tab] MPREb_Biju2UFlzmN: Failed to resolve album to playlist; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 740, in extract
  File "yt_dlp\extractor\youtube.py", line 4711, in wrapper
  File "yt_dlp\extractor\youtube.py", line 6617, in _real_extract
```

**Comment by Fritz66** [comment]
Works fine for me.
https://files.catbox.moe/s108zg.txt

**Comment by orenai** [comment]
It worked again today. I couldn't find what the cause of the problem was. Sorry for the inconvenience.

**Comment by bashonly** [comment]
No worries. Just Youtube being Youtube.
