### ISSUE TITLE
yt-dlp suddenly downloading in low quality

### ISSUE THREAD

**Issue by imongithub123** [yt-dlp/yt-dlp#10267]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

dylan@Dylans-MacBook-Pro ~ % yt-dlp -o "~/Downloads/%(title)s.%(ext)s" https://youtu.be/UJ7rraMoihMsi=gXvMrPJr_aJ04dT4

[youtube] Extracting URL: https://youtu.be/UJ7rraMoihMsi=gXvMrPJr_aJ04dT4
[youtube] UJ7rraMoihM: Downloading webpage
[youtube] UJ7rraMoihM: Downloading ios player API JSON
[youtube] UJ7rraMoihM: Downloading android player API JSON
[youtube] UJ7rraMoihM: Downloading m3u8 information
[info] UJ7rraMoihM: Downloading 1 format(s): 18
[download] Destination: /Users/dylan/Downloads/Shaq Tried To Dunk For His 50th Birthday And Compared It To Dwight Howard's 2008 Dunk ｜ NBA on TNT.mp4
[download] 100% of   12.80MiB in 00:00:01 at 11.30MiB/s

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
dylan@Dylans-MacBook-Pro ~ % yt-dlp -o "~/Downloads/%(title)s.%(ext)s" https://youtu.be/UJ7rraMoihMsi=gXvMrPJr_aJ04dT4

[youtube] Extracting URL: https://youtu.be/UJ7rraMoihMsi=gXvMrPJr_aJ04dT4
[youtube] UJ7rraMoihM: Downloading webpage
[youtube] UJ7rraMoihM: Downloading ios player API JSON
[youtube] UJ7rraMoihM: Downloading android player API JSON
[youtube] UJ7rraMoihM: Downloading m3u8 information
[info] UJ7rraMoihM: Downloading 1 format(s): 18
[download] Destination: /Users/dylan/Downloads/Shaq Tried To Dunk For His 50th Birthday And Compared It To Dwight Howard's 2008 Dunk ｜ NBA on TNT.mp4
[download] 100% of   12.80MiB in 00:00:01 at 11.30MiB/s
```

**Comment by seproDev** [comment]
Please share a complete verbose log, like the instructions tell you.
If I were to make a guess, you likely don't have ffmpeg installed, so yt-dlp falls back to premerged formats. YouTube recently started removing/limiting access to format 22, which leaves only 18 as the only pre-merged format, which is 360p.

**Comment by imongithub123** [comment]
Last login: Tue Jun 25 16:51:50 on ttys000
dylan@Dylans-MacBook-Pro ~ % yt-dlp -o "~/Downloads/%(title)s.%(ext)s" https://youtu.be/GNTDmcWG5Uwsi=u9rXB-HF_x4kpo-P

[youtube] Extracting URL: https://youtu.be/GNTDmcWG5Uwsi=u9rXB-HF_x4kpo-P
[youtube] GNTDmcWG5Uw: Downloading webpage
[youtube] GNTDmcWG5Uw: Downloading ios player API JSON
[youtube] GNTDmcWG5Uw: Downloading android player API JSON
[youtube] GNTDmcWG5Uw: Downloading player a95aa57a
[youtube] GNTDmcWG5Uw: Downloading m3u8 information
[info] GNTDmcWG5Uw: Downloading 1 format(s): 18
[download] Destination: /Users/dylan/Downloads/Inside The NBA Crew Discuss the Biggest Snubs From NBA75 List.mp4
[download] 100% of   10.72MiB in 00:00:01 at 9.32MiB/s
dylan@Dylans-MacBook-Pro ~ %

**Comment by seproDev** [comment]
That is still not a verbose log.
>  [ ] Run your yt-dlp command with -vU flag added (yt-dlp -vU <your command line>)

**Comment by imongithub123** [comment]
How do I get that? What exactly do I enter?

**Comment by seproDev** [comment]
Just run `yt-dlp -vU <your command line>`
So for your case: `yt-dlp -vU -o "~/Downloads/%(title)s.%(ext)s" https://youtu.be/UJ7rraMoihMsi=gXvMrPJr_aJ04dT4`

**Comment by imongithub123** [comment]
Last login: Tue Jun 25 16:54:37 on ttys000
dylan@Dylans-MacBook-Pro ~ % yt-dlp -vU -o "~/Downloads/%(title)s.%(ext)s" https://youtu.be/UJ7rraMoihMsi=gXvMrPJr_aJ04dT4
[debug] Command-line config: ['-vU', '-o', '~/Downloads/%(title)s.%(ext)s', 'https://youtu.be/UJ7rraMoihMsi=gXvMrPJr_aJ04dT4']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.03.10 from yt-dlp/yt-dlp [615a84447] (zip)
[debug] Python 3.9.6 (CPython arm64 64bit) - macOS-14.3.1-arm64-arm-64bit (LibreSSL 2.8.3)
[debug] exe versions: none
[debug] Optional libraries: sqlite3-3.43.2
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Loaded 1803 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
[debug] Downloading _update_spec from https://github.com/yt-dlp/yt-dlp/releases/latest/download/_update_spec
[debug] Downloading SHA2-256SUMS from https://github.com/yt-dlp/yt-dlp/releases/download/2024.05.27/SHA2-256SUMS
Current version: stable@2024.03.10 from yt-dlp/yt-dlp
Latest version: stable@2024.05.27 from yt-dlp/yt-dlp
Current Build Hash: 5576348930e44102add235c0a032e766f416a507db1dd2c75da833ff21e9fb6c
Updating to stable@2024.05.27 from yt-dlp/yt-dlp ...
ERROR: Unable to write to /usr/local/bin/yt-dlp; try running as administrator
[youtube] Extracting URL: https://youtu.be/UJ7rraMoihMsi=gXvMrPJr_aJ04dT4
[youtube] UJ7rraMoihM: Downloading webpage
[youtube] UJ7rraMoihM: Downloading ios player API JSON
[youtube] UJ7rraMoihM: Downloading android player API JSON
[debug] Loading youtube-nsig.61b3b5e4 from cache
[debug] [youtube] Decrypted nsig R3i-Tw46CKINAhzuTHc => SSpV17faZwWQpQ
[debug] Loading youtube-nsig.61b3b5e4 from cache
[debug] [youtube] Decrypted nsig qIa42-owZLEFgZGG5bO => 0mA058FqBGImDw
[youtube] UJ7rraMoihM: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[debug] Default format spec: best/bestvideo+bestaudio
[info] UJ7rraMoihM: Downloading 1 format(s): 18
[debug] Invoking http downloader on "https://rr1---sn-jvhj5nu-2iae.googlevideo.com/videoplayback?expire=1719370817&ei=4S97Zt2_IuuCkucPx6aMmAk&ip=71.230.121.147&id=o-AMLgIPw3VVhx6maFJlbmb6yApepjQh3EzM18BUX2CoGZ&itag=18&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=VK&mm=31%2C29&mn=sn-jvhj5nu-2iae%2Csn-ab5l6ndr&ms=au%2Crdu&mv=m&mvi=1&pcm2cms=yes&pl=21&initcwndbps=1407500&bui=AbKP-1P_9h5a0aO6WVXDc1TJwTB-zkBzLqs_0Wslnxnv0LsJXarwyiVuF7SrjPNGP-wqUCfG9ChhUWbL&spc=UWF9fy6aZ_OItVNmINz0D1sI2MGHpolOpHmE4f68L84nQwnTwagGXYrcM_Ec&vprv=1&svpuc=1&mime=video%2Fmp4&ns=9qq8pAsId2hGms73lIV_QNAQ&rqh=1&cnr=14&ratebypass=yes&dur=294.220&lmt=1665125415587879&mt=1719348782&fvip=2&c=WEB&sefc=1&txp=5538434&n=SSpV17faZwWQpQ&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cbui%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cns%2Crqh%2Ccnr%2Cratebypass%2Cdur%2Clmt&sig=AJfQdSswRQIgbXu85rMkwj1zPjdbLDjZQFAVXTWw57Ih-HpZlJDofgQCIQCUjaWOzk7jvLtzXGBLi8TtX0gyKL5nmIsHrxlWGWljPg%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lsig=AHlkHjAwRgIhAN8YyfSUOrex3U1eK1i2FiwDJV1nV1eCpZbDQW4v11H_AiEAx6S4XF_kldy4mrI1t6aGcfdUljDiVnkkbBkVSsF1UiA%3D"
[download] Destination: /Users/dylan/Downloads/Shaq Tried To Dunk For His 50th Birthday And Compared It To Dwight Howard's 2008 Dunk ｜ NBA on TNT.mp4
[download] 100% of   12.80MiB in 00:00:01 at 11.79MiB/s
dylan@Dylans-MacBook-Pro ~ %

**Comment by imongithub123** [comment]
How do I install yt-dlp with brew? Thank you so much

**Comment by seproDev** [comment]
After you have brew installed, run the following three commands:
```
sudo rm /usr/local/bin/yt-dlp
brew install yt-dlp
brew install ffmpeg
```
That will:
1. Remove your old yt-dlp version
2. Install yt-dlp with brew
3. Install ffmpeg with brew

**Comment by imongithub123** [comment]
Thank you, though now it is downloading in MKV, how do I go back to MP4?

**Comment by seproDev** [comment]
If you want *a* mp4 file you can add `--merge-output-format mp4`. However, many older programs are incompatible with these mp4 files.

If you want a mp4 file with h264/avc video and aac audio, which should be compatible with nearly everything, add `-S vcodec:avc,res,acodec:aac`. This will, however, limit you to 1080p or lower on YouTube.
The entire command for that would be:
```
yt-dlp -S vcodec:avc,res,acodec:aac "URL"
```

**Comment by imongithub123** [comment]
Last question, how do I use:

yt-dlp -S vcodec:avc,res,acodec:aac "URL"

to make it download do my "downloads" section on Mac?

**Comment by seproDev** [comment]
Add `-P "~/Downloads"`, so
```
yt-dlp -P "~/Downloads" -S vcodec:avc,res,acodec:aac "URL"
```

**Comment by imongithub123** [comment]
you're the man!! thank you
