### ISSUE TITLE
youtube merge error

### ISSUE THREAD

**Issue by namgod99** [yt-dlp/yt-dlp#10261]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Vietnamese

### Provide a description that is worded well enough to be understood

I use this command to download youtube videos
yt-dlp --skip-download --yes-playlist --continue --merge-output-format mp4 --postprocessor-args "-c:v libx264 -c:a aac" -o "D:\Downloads\Movies Youtube\tanlocdinhky\%(title).50s.%(ext)s" -a "D:\Downloads\Youtube Movies\tanlocdinhky.txt"
but Yt-dlp stopped working

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
@echo off

REM Playlist 1
yt-dlp --merge-output-format mp4 --postprocessor-args "-c:v libx264 -c:a aac" -o "Z:\tanlocdinhky\%(title).50s.%(ext)s" -a "Z:\tanlocdinhky.txt"
WARNING: Post-Processor arguments given without specifying name. The arguments will be given to all post-processors
[youtube:tab] Extracting URL: https://www.youtube.com/watch?v=HfN3YBr8IAM&list=PLZ-04jDSlBcFfF8st28fquuzABQNRMauX&index=1&pp=iAQB
[youtube:tab] Downloading playlist PLZ-04jDSlBcFfF8st28fquuzABQNRMauX - add --no-playlist to download just the video HfN3YBr8IAM
[youtube:tab] PLZ-04jDSlBcFfF8st28fquuzABQNRMauX: Downloading webpage
[youtube:tab] Extracting URL: https://www.youtube.com/playlist?list=PLZ-04jDSlBcFfF8st28fquuzABQNRMauX
[youtube:tab] PLZ-04jDSlBcFfF8st28fquuzABQNRMauX: Downloading webpage
[youtube:tab] PLZ-04jDSlBcFfF8st28fquuzABQNRMauX: Redownloading playlist API JSON with unavailable videos
[download] Downloading playlist: Tân Lộc Đỉnh Ký | Phim Cổ Trang Kim Dung Võ Thuật Hay Nhất | Thuyết Minh | Full HD | iPhim MAX
[youtube:tab] PLZ-04jDSlBcFfF8st28fquuzABQNRMauX page 1: Downloading API JSON
WARNING: [youtube:tab] Incomplete data received. Retrying (1/3)...
[youtube:tab] PLZ-04jDSlBcFfF8st28fquuzABQNRMauX page 1: Downloading API JSON
WARNING: [youtube:tab] Incomplete data received. Retrying (2/3)...
[youtube:tab] PLZ-04jDSlBcFfF8st28fquuzABQNRMauX page 1: Downloading API JSON
WARNING: [youtube:tab] Incomplete data received. Retrying (3/3)...
[youtube:tab] PLZ-04jDSlBcFfF8st28fquuzABQNRMauX page 1: Downloading API JSON
WARNING: [youtube:tab] Incomplete data received. Giving up after 3 retries
[youtube:tab] Playlist Tân Lộc Đỉnh Ký | Phim Cổ Trang Kim Dung Võ Thuật Hay Nhất | Thuyết Minh | Full HD | iPhim MAX: Downloading 50 items of 50
[download] Downloading item 1 of 50
[youtube] Extracting URL: https://www.youtube.com/watch?v=HfN3YBr8IAM
[youtube] HfN3YBr8IAM: Downloading webpage
[youtube] HfN3YBr8IAM: Downloading ios player API JSON
[youtube] HfN3YBr8IAM: Downloading player 84314bef
[youtube] HfN3YBr8IAM: Downloading m3u8 information
[info] HfN3YBr8IAM: Downloading 1 format(s): 303+251
[download] Destination: Z:\tanlocdinhky\Tân Lộc Đỉnh Ký - Tập 01 ｜ Phim Cổ Trang Võ Thuật .f303.webm
[download] 100% of    1.30GiB in 00:04:17 at 5.19MiB/s
[download] Destination: Z:\tanlocdinhky\Tân Lộc Đỉnh Ký - Tập 01 ｜ Phim Cổ Trang Võ Thuật .f251.webm
[download] 100% of   30.59MiB in 00:00:07 at 3.83MiB/s
[Merger] Merging formats into "Z:\tanlocdinhky\Tân Lộc Đỉnh Ký - Tập 01 ｜ Phim Cổ Trang Võ Thuật .mp4"
```

**Comment by bashonly** [comment]
Everything looks OK in your log. What do you mean by "stopped working"? Please actually describe the issue, and share **complete verbose output** (add `-vU` to your command)

**Comment by zaqpython** [comment]
![image](https://github.com/yt-dlp/yt-dlp/assets/44115038/70dd0a13-f260-4822-b884-17221d58fd7e)
I have downloaded the video I need, and I have checked the audio video, but why does the merging error still occur? If I put the same code on another server, this problem will not occur. Could you please tell me how to solve this problem
