### ISSUE TITLE
[Mediasite] ERROR: 'str' object has no attribute 'get'

### ISSUE THREAD

**Issue by flanter21** [yt-dlp/yt-dlp#10270]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Provide a description that is worded well enough to be understood

I am trying to download a video "as slides" from mediasite. "As slides" refers to a stream made up of a series of images, which added [here](https://github.com/yt-dlp/yt-dlp/pull/343/). Unfortunately, this no longer seems to work.

I have found through a few URLs, two different errors. I will note though, these are public videos and the ones I want to download are behind Microsoft logins and I'm using the `--cookies-from-browser chrome` but I have confirmed using mitmproxy that it does download the correct json downloaded and that you can extract the video stream and slides from it.

However, I am running into this error: `TypeError: 'NoneType' object is not subscriptable` and for a few public mediasite videos, `AttributeError: 'str' object has no attribute 'get'`.

The solution I envision is that the attributeerror on line 221/typeerror is fixed. 

_For the attributeerror on line 221_
From my reading of the code, it seems that it goes wrong when looking for the json value for `Presentation.Streams.1.VideoUrls.MediaType` for each stream. The code tries to read the `MediaType` value inside the `video_url` variable, which seems to correspond to `Presentation.Streams.1.VideoUrls.MediaType`. However due to a type mismatch, the code cannot access the `MediaType` value that would be nested inside it in the json file. `video_url` is defined using the `url_or_none` function on line 216 [here](https://github.com/yt-dlp/yt-dlp/blob/master/yt_dlp/utils/_utils.py). Could this be turning it into a string? Could you access the elements inside `video_url` using square brackets like is done in other places? eg. line 192

PS - In all the links I've tried, I haven't found "MediaType"s of 'SS' or 'Dash', only 'MP4' even if it is a .ism file (and once I found 'WMV').

_For the typeerror on line 240_
As for the `ERROR: 'NoneType' object is not subscriptable` error on line 240, in the code, it seems that oftentimes, `PlayerLayoutOptions` is set to null and so this line of code will fail. The code should account for this. If you can fix only this latter issue, I would be grateful as I am not running into the attribute error on any of my University's lectures.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output
**https://events7.mediasite.com/Mediasite/Play/a7812390a2d44739ae857527e05776091d** = Version 8.31.0 Build 39
```
[debug] Command-line config: ['-vU', 'https://events7.mediasite.com/Mediasite/Play/a7812390a2d44739ae857527e05776091d']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.06.24.232830 from yt-dlp/yt-dlp-nightly-builds [f3411af12] (darwin_exe)
[debug] Python 3.12.4 (CPython arm64 64bit) - macOS-14.5-arm64-arm-64bit (OpenSSL 3.0.13 30 Jan 2024)
[debug] exe versions: ffmpeg 7.0.1 (setts), ffprobe 7.0.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.06.02, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.45.3, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1823 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.06.24.232830 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.06.24.232830 from yt-dlp/yt-dlp-nightly-builds)
[Mediasite] Extracting URL: https://events7.mediasite.com/Mediasite/Play/a7812390a2d44739ae857527e05776091d
[Mediasite] a7812390a2d44739ae857527e05776091d: Downloading webpage
[Mediasite] a7812390a2d44739ae857527e05776091d: Downloading JSON metadata
ERROR: 'str' object has no attribute 'get'
Traceback (most recent call last):
  File "yt_dlp/YoutubeDL.py", line 1605, in wrapper
  File "yt_dlp/YoutubeDL.py", line 1740, in __extract_info
  File "yt_dlp/extractor/common.py", line 740, in extract
  File "yt_dlp/extractor/mediasite.py", line 221, in _real_extract
AttributeError: 'str' object has no attribute 'get'
```

**https://collegerama.tudelft.nl/Mediasite/Play/86a9ea9f53e149079fbdb4202b521ed21d** = Version 8.28.0 Build 122.
```shell
[debug] Command-line config: ['-vU', 'https://collegerama.tudelft.nl/Mediasite/Play/86a9ea9f53e149079fbdb4202b521ed21d?catalog=fd32fd35-6c99-466c-89d4-cd3c431bc8a4']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.06.24.232830 from yt-dlp/yt-dlp-nightly-builds [f3411af12] (darwin_exe)
[debug] Python 3.12.4 (CPython arm64 64bit) - macOS-14.5-arm64-arm-64bit (OpenSSL 3.0.13 30 Jan 2024)
[debug] exe versions: ffmpeg 7.0.1 (setts), ffprobe 7.0.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.06.02, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.45.3, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1823 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.06.24.232830 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.06.24.232830 from yt-dlp/yt-dlp-nightly-builds)
[Mediasite] Extracting URL: https://collegerama.tudelft.nl/Mediasite/Play/86a9ea9f53e149079fbdb4202b521ed21d
[Mediasite] 86a9ea9f53e149079fbdb4202b521ed21d: Downloading webpage
[Mediasite] 86a9ea9f53e149079fbdb4202b521ed21d: Downloading JSON metadata
ERROR: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "yt_dlp/YoutubeDL.py", line 1605, in wrapper
  File "yt_dlp/YoutubeDL.py", line 1740, in __extract_info
  File "yt_dlp/extractor/common.py", line 740, in extract
  File "yt_dlp/extractor/mediasite.py", line 240, in _real_extract
TypeError: 'NoneType' object is not subscriptable
```

**Comment by bashonly** [comment]
this fixes it:

```diff
diff --git a/yt_dlp/extractor/mediasite.py b/yt_dlp/extractor/mediasite.py
index beb12f8a4..ad7ab27e2 100644
--- a/yt_dlp/extractor/mediasite.py
+++ b/yt_dlp/extractor/mediasite.py
@@ -15,6 +15,7 @@
     url_or_none,
     urljoin,
 )
+from ..utils.traversal import traverse_obj
 
 _ID_RE = r'(?:[0-9a-f]{32,34}|[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12,14})'
 
@@ -212,13 +213,14 @@ def _real_extract(self, url):
                 stream_type, 'type%u' % stream_type)
 
             stream_formats = []
-            for unum, video_url in enumerate(video_urls):
-                video_url = url_or_none(video_url.get('Location'))
+            for unum, video in enumerate(video_urls):
+                video_url = url_or_none(video.get('Location'))
                 if not video_url:
                     continue
...skipping...
                         mpd_id=f'{stream_id}-{snum}.{unum}',
                         fatal=False))
+                elif ext in ('m3u', 'm3u8'):
+                    stream_formats.extend(self._extract_m3u8_formats(
+                        video_url, resource_id,
+                        m3u8_id=f'{stream_id}-{snum}.{unum}',
+                        fatal=False))
                 else:
                     stream_formats.append({
                         'format_id': f'{stream_id}-{snum}.{unum}',
                         'url': video_url,
-                        'ext': mimetype2ext(video_url.get('MimeType')),
+                        'ext': ext,
                     })
 
-            if stream.get('HasSlideContent', False):
-                images = player_options['PlayerLayoutOptions']['Images']
+            images = traverse_obj(player_options, ('PlayerLayoutOptions', 'Images', {dict}))
+            if stream.get('HasSlideContent') and images:
                 stream_formats.append(self.__extract_slides(
                     stream_id=stream_id,
                     snum=snum,
```

**Comment by bashonly** [comment]
regression in add96eb9f84cfffe85682bf2fb85135746994ee8

**Comment by flanter21** [comment]
> this fixes it:
> 
> ```diff
> diff --git a/yt_dlp/extractor/mediasite.py b/yt_dlp/extractor/mediasite.py
> index beb12f8a4..ad7ab27e2 100644
> --- a/yt_dlp/extractor/mediasite.py
> +++ b/yt_dlp/extractor/mediasite.py
> @@ -15,6 +15,7 @@
>      url_or_none,
>      urljoin,
>  )
> +from ..utils.traversal import traverse_obj
>  
>  _ID_RE = r'(?:[0-9a-f]{32,34}|[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12,14})'
>  
> @@ -212,13 +213,14 @@ def _real_extract(self, url):
>                  stream_type, 'type%u' % stream_type)
>  
>              stream_formats = []
> -            for unum, video_url in enumerate(video_urls):
> -                video_url = url_or_none(video_url.get('Location'))
> +            for unum, video in enumerate(video_urls):
> +                video_url = url_or_none(video.get('Location'))
>                  if not video_url:
>                      continue
>                  # XXX: if Stream.get('CanChangeScheme', False), switch scheme to HTTP/HTTPS
>  
> -                media_type = video_url.get('MediaType')
> +                media_type = video.get('MediaType')
> +                ext = mimetype2ext(video.get('MimeType'))
>                  if media_type == 'SS':
>                      stream_formats.extend(self._extract_ism_formats(
>                          video_url, resource_id,
> @@ -229,15 +231,20 @@ def _real_extract(self, url):
>                          video_url, resource_id,
>                          mpd_id=f'{stream_id}-{snum}.{unum}',
>                          fatal=False))
> +                elif ext in ('m3u', 'm3u8'):
> +                    stream_formats.extend(self._extract_m3u8_formats(
> +                        video_url, resource_id,
> +                        m3u8_id=f'{stream_id}-{snum}.{unum}',
> +                        fatal=False))
>                  else:
>                      stream_formats.append({
>                          'format_id': f'{stream_id}-{snum}.{unum}',
>                          'url': video_url,
> -                        'ext': mimetype2ext(video_url.get('MimeType')),
> +                        'ext': ext,
>                      })
>  
> -            if stream.get('HasSlideContent', False):
> -                images = player_options['PlayerLayoutOptions']['Images']
> +            images = traverse_obj(player_options, ('PlayerLayoutOptions', 'Images', {dict}))
> +            if stream.get('HasSlideContent') and images:
>                  stream_formats.append(self.__extract_slides(
>                      stream_id=stream_id,
>                      snum=snum,
> ```

Thank you @bashonly. I've tried the latest build and now it does let me download audio and video. However, it no longer shows the slides (mhtml) as a downloadable format. Is it possible that this could also be fixed. The links given above both have slides, which would found in `Presentation.Streams.0` and is processed by [the function on line 118](https://github.com/yt-dlp/yt-dlp/blob/master/yt_dlp/extractor/mediasite.py#L118).

I believe the issue here is that [line 247](https://github.com/yt-dlp/yt-dlp/blob/master/yt_dlp/extractor/mediasite.py#L247) doesn't account for if the value for `PlayerLayoutOptions` is null, which it seems to usually be.

**Comment by bashonly** [comment]
@flanter21 could you open a new issue about the slides? It is a different issue that would require more investigation; I wasn't able to find a fix while patching the regression / m3u8 extraction.
