### ISSUE TITLE
[MLBTV] IndexError: list index out of range, in mlb.py

### ISSUE THREAD

**Issue by yroyathon** [yt-dlp/yt-dlp#10275]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United States

### Provide a description that is worded well enough to be understood

Using the YT-DLP command on an MLBTV game url no longer works, an error is encountered early just after the downloading json metadata step.  I have tried upgrading yt-dlp to the latest version, which didn't work.  I've tried updating it to the nightly build, which also didn't work.  I get the same error in each case.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '-u', 'PRIVATE', '-p', 'PRIVATE', 'https://www.mlb.com/tv/g747022/v49bf619a-3dfc-407a-be4b-2d27b33d38b2']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.06.24.232830 from yt-dlp/yt-dlp-nightly-builds [f3411af12] (pip)
[debug] Python 3.10.12 (CPython x86_64 64bit) - Linux-6.5.0-35-generic-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.11.0, brotli-1.0.9, certifi-2020.06.20, mutagen-1.45.1, pyxattr-0.7.2, requests-2.32.3, secretstorage-3.3.1, sqlite3-3.37.2, urllib3-2.2.1, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1823 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.06.24.232830 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.06.24.232830 from yt-dlp/yt-dlp-nightly-builds)
[MLBTV] Downloading JSON metadata
[MLBTV] None: Downloading webpage
[MLBTV] Downloading JSON metadata
[MLBTV] Extracting URL: https://www.mlb.com/tv/g747022/v49bf619a-3dfc-407a-be4b-2d27b33d38b2
[MLBTV] 747022: Downloading JSON metadata
ERROR: list index out of range
Traceback (most recent call last):
  File "/home/username/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1605, in wrapper
    return func(self, *args, **kwargs)
  File "/home/username/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1740, in __extract_info
    ie_result = ie.extract(url)
  File "/home/username/.local/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 740, in extract
    ie_result = self._real_extract(url)
  File "/home/username/.local/lib/python3.10/site-packages/yt_dlp/extractor/mlb.py", line 331, in _real_extract
    airing['playbackUrls'][0]['href'].format(scenario='browser~csai'), video_id,
IndexError: list index out of range
```

**Comment by yroyathon** [comment]
for airing in airings:
		if len(airing['playbackUrls']) == 0: continue  #TMP, skip if there are no playbackUrls
		m3u8_url = self._download_json(
				airing['playbackUrls'][0]['href'].format(scenario='browser~csai'), video_id,

**Comment by yroyathon** [comment]
Testing the following changes...
`for airing in airings:
		if len(airing['playbackUrls']) == 0: continue  #TMP, skip if there are no playbackUrls
		m3u8_url = self._download_json(
				airing['playbackUrls'][0]['href'].format(scenario='browser~csai'), video_id,
`

**Comment by yroyathon** [comment]
This seems to patch the issue, I've successfully downloaded 2 new games now with the change in place.  Not knowing the code base at all, I can't say what exactly changed on the MLB side, if this is a good or permanent solution.  I leave it to someone smarter than me to add the 1 line change above to the repo and close out this ticket.

**Comment by bashonly** [comment]
This would be the conventional yt-dlp way to do it:

```diff
diff --git a/yt_dlp/extractor/mlb.py b/yt_dlp/extractor/mlb.py
index 8a693dc0b..898d26afb 100644
--- a/yt_dlp/extractor/mlb.py
+++ b/yt_dlp/extractor/mlb.py
@@ -12,6 +12,7 @@
     traverse_obj,
     try_get,
 )
+from ..utils.traversal import traverse_obj
 
 
 class MLBBaseIE(InfoExtractor):
@@ -326,7 +327,7 @@ def _real_extract(self, url):
             video_id)['data']['Airings']
 
         formats, subtitles = [], {}
-        for airing in airings:
+        for airing in traverse_obj(airings, lambda _, v: v['playbackUrls'][0]['href']):
             m3u8_url = self._download_json(
                 airing['playbackUrls'][0]['href'].format(scenario='browser~csai'), video_id,
                 headers={
```

I would still like to *at least* see what the JSON response looks like before merging that patch though

**Comment by yroyathon** [comment]
I'm happy to help.  So are you saying I should make your proposed change to my local, run it, and then paste some/all of the output?  What particular subset are you looking at, like lines containing or beginning with?  The last time I ran it, it kicked out over 9,000 lines of text.

**Comment by bashonly** [comment]
Sure, you could test it. But I'd also like to see what exactly changed in the site's API response to make sure we're not missing anything. You could share account credentials if you're comfortable with that, or you could just send page dumps (the site's API responses written to files on disk).

If you'd prefer to send page dumps, then add `--write-pages` to your yt-dlp command and yt-dlp will write multiple `.dump` files to your current working directory.

You can send credentials or pagedumps to me via:
 - [discord](https://discord.gg/H5MNcFW63r): username **bashonly**
 - email: bashonly ( a t ) proton mail ( dot ) com

**Comment by yroyathon** [comment]
Ok, I made the change to the for airing statement, and I'm running yt-dlp now with --write-pages.  I'll email you the dump files shortly.

**Comment by sdelafond** [comment]
This unfortunately doesn't seem to fix it for me; running locally from b731fac:

`./yt-dlp.sh -vU --netrc https://www.mlb.com/tv/g745319/v3b0c4d64-eea8-44e2-8eb5-3a834c5e913`:

```
[debug] Command-line config: ['-vU', '--netrc', 'https://www.mlb.com/tv/g745319/v3b0c4d64-eea8-44e2-8eb5-b3a834c5e913']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.05.27 from yt-dlp/yt-dlp [12b248ce6] (source)
[debug] Lazy loading extractors is disabled
[debug] Git HEAD: b731face2
[debug] Python 3.12.4 (CPython x86_64 64bit) - Linux-6.8.12-amd64-x86_64-with-glibc2.38 (OpenSSL 3.2.2 4 Jun 2024, glibc 2.38)
[debug] exe versions: ffmpeg 6.1.1-4 (setts), ffprobe 6.1.1-4
[debug] Optional libraries: Cryptodome-3.20.0, brotlicffi-1.1.0.0, certifi-2024.06.02, mutagen-1.46.0, requests-2.32.3, secretstorage-3.3.3, sqlite3-3.46.0, urllib3-2.0.7, websockets-10.4
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Loaded 1823 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.05.27 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.05.27 from yt-dlp/yt-dlp)
[debug] [MLBTV] Using netrc for mlb authentication
[MLBTV] Downloading JSON metadata
[MLBTV] None: Downloading webpage
[MLBTV] Downloading JSON metadata
[MLBTV] Extracting URL: https://www.mlb.com/tv/g745319/v3b0c4d64-eea8-44e2-8eb5-b3a834c5e913
[MLBTV] 745319: Downloading JSON metadata
[MLBTV] 745319: Downloading JSON metadata
[MLBTV] 745319: Downloading m3u8 information
[MLBTV] 745319: Downloading JSON metadata
[MLBTV] 745319: Downloading m3u8 information
[MLBTV] 745319: Downloading JSON metadata
ERROR: [MLBTV] 745319: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: Not Found>)
  File "/home/seb/vcs/yt-dlp/yt_dlp/extractor/common.py", line 740, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seb/vcs/yt-dlp/yt_dlp/extractor/mlb.py", line 330, in _real_extract
    m3u8_url = self._download_json(
               ^^^^^^^^^^^^^^^^^^^^
  File "/home/seb/vcs/yt-dlp/yt_dlp/extractor/common.py", line 1139, in download_content
    res = getattr(self, download_handle.__name__)(url_or_request, video_id, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seb/vcs/yt-dlp/yt_dlp/extractor/common.py", line 1099, in download_handle
    res = self._download_webpage_handle(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seb/vcs/yt-dlp/yt_dlp/extractor/common.py", line 960, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seb/vcs/yt-dlp/yt_dlp/extractor/common.py", line 909, in _request_webpage
    raise ExtractorError(errmsg, cause=err)

  File "/home/seb/vcs/yt-dlp/yt_dlp/extractor/common.py", line 896, in _request_webpage
    return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query, extensions))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seb/vcs/yt-dlp/yt_dlp/YoutubeDL.py", line 4141, in urlopen
    return self._request_director.send(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seb/vcs/yt-dlp/yt_dlp/networking/common.py", line 117, in send
    response = handler.send(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/seb/vcs/yt-dlp/yt_dlp/networking/_helper.py", line 208, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seb/vcs/yt-dlp/yt_dlp/networking/common.py", line 337, in send
    return self._send(request)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/seb/vcs/yt-dlp/yt_dlp/networking/_requests.py", line 363, in _send
    raise HTTPError(res, redirect_loop=max_redirects_exceeded)
yt_dlp.networking.exceptions.HTTPError: HTTP Error 404: Not Found
```

**Comment by bashonly** [comment]
@sdelafond pull again and try with https://github.com/yt-dlp/yt-dlp/pull/10296/commits/9118c79d9ea1527ad39e4f62a9bc16b43b5f562d

**Comment by sdelafond** [comment]
(looks like the same error, commented in the PR itself)

**Comment by yroyathon** [comment]
Thanks to both of you for the timely fix.
