### ISSUE TITLE
[Youtube] When using operators like bv or b* the video is downloaded without any sound

### ISSUE THREAD

**Issue by nubdienub** [yt-dlp/yt-dlp#10274]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Netherlands

### Provide a description that is worded well enough to be understood

Hello I am facing an issue where I am trying to download Youtube video's in better quality but by doing so (using certain commands) the downloaded video's have no sound.

The reason why I want to user better quality video's is that the default command for downloading:

- .\yt-dlp.exe https://www.youtube.com/watch?v=RH_V4GPsUYA 

Returns me a video **with** sound but with very bad quality. It seems the quality is 480p even though the video on Youtube itself has 1080HD. I have tried playing with the operators a bit like this:

- .\yt-dlp.exe https://www.youtube.com/watch?v=RH_V4GPsUYA -f "bv*"
- .\yt-dlp.exe https://www.youtube.com/watch?v=RH_V4GPsUYA -f "b"
- .\yt-dlp.exe https://www.youtube.com/watch?v=RH_V4GPsUYA -f bv*[height=1080]
-  .\yt-dlp.exe https://www.youtube.com/watch?v=RH_V4GPsUYA -f "bv*[ext=mp4]

And when I download these video's I do get good video quality. But the main problem:

**Not one video that has good video quality, has sound**

So far I am only able to get video AND sound by using the standard download query but this will always return me a video where the quality is poor. Even the text is not readable. This issue occurs with all video's I am trying to download on YouTube. I have ran the update command and my ytdlp is up-to-date. Also tried redownloading the executable.

How do I get both good quality video and sound?

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
.\yt-dlp.exe https://www.youtube.com/watch?v=RH_V4GPsUYA -f bv*[height=1080] -vU
[debug] Command-line config: ['https://www.youtube.com/watch?v=RH_V4GPsUYA', '-f', 'bv*[height=1080]', '-vU']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.05.27 from yt-dlp/yt-dlp [12b248ce6] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22631-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.02.02, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.2, sqlite3-3.35.5, urllib3-2.2.1, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1820 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.05.27 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.05.27 from yt-dlp/yt-dlp)
[youtube] Extracting URL: https://www.youtube.com/watch?v=RH_V4GPsUYA
[youtube] RH_V4GPsUYA: Downloading webpage
[youtube] RH_V4GPsUYA: Downloading ios player API JSON
[debug] Loading youtube-nsig.a95aa57a from cache
[debug] [youtube] Decrypted nsig flIyVToX7r-9WJ0B => yyrMN1iDfRwnhA
[debug] Loading youtube-nsig.a95aa57a from cache
[debug] [youtube] Decrypted nsig JfLA34mvTTjfvQfB => lyQglfcCU5eJDg
[youtube] RH_V4GPsUYA: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[info] RH_V4GPsUYA: Downloading 1 format(s): 248
[debug] Invoking http downloader on "https://rr4---sn-j5pfqpxonuxo-guhe.googlevideo.com/videoplayback?expire=1719446991&ei=b1l8ZuDDOJaN6dsPjpayyA0&ip=62.45.117.56&id=o-ALVCbbZ2mnJ5SNUceiDXFS5uzuamUUJgTg19zv9tLk6K&itag=248&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=R-&mm=31%2C29&mn=sn-j5pfqpxonuxo-guhe%2Csn-5hne6n6l&ms=au%2Crdu&mv=m&mvi=4&pcm2cms=yes&pl=21&initcwndbps=2285000&bui=AbKP-1M-IqsawnPWC8JzZlzP3WOO1BajshpIR8vDtBlAQClLzStDVwPc96grpGUXN95BSnakvr2qGFXI&spc=UWF9f9joYm89qzns6Hno20J3_--iW14fIIK4wNIdWzZBKzGZy5e_Q99gkekD&vprv=1&svpuc=1&mime=video%2Fwebm&ns=fwfB9gl2IRa4K1tTU6TkjBIQ&rqh=1&gir=yes&clen=85715223&dur=428.760&lmt=1695642883442091&mt=1719425101&fvip=1&keepalive=yes&c=WEB&sefc=1&txp=630F224&n=lyQglfcCU5eJDg&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cxpc%2Cbui%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cns%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRQIhALLl3vylhUxnzmhmfh_8Zqrt2YRijIyzeLjf-fJ4-0O5AiAF2boc-ARRMBpxENs1HfKIY72D-_0Dq5xubL-I29noqA%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lsig=AHlkHjAwRAIgH_TO_SqTdGMM6oOWZxfqLtkiRTQDugLXpGJXlsUyaiECIAU3bFVJUd5OYu5bBXy63S-e1TvvXRc4VEIywD5hrXNl"
[debug] File locking is not supported. Proceeding without locking
[download] Destination: Sfeervol UITVAK wordt niet BELOOND ｜ Van Binnenuit [RH_V4GPsUYA].webm
[download] 100% of   81.74MiB in 00:00:03 at 26.76MiB/s
```

**Comment by nubdienub** [comment]
One thing I have noticed when using the -F command it shows me a list of video and audio formats. The best video formats do not have sound so that would make sense why I don't get audio when I get the best video. Is it however, possible to combine the best video with the best audio into one file? As a workaround right now I can download both seperately and work with that but I'd prefer using single files that have both sound and video.

**Comment by Grub4K** [comment]
You need `ffmpeg` to be able to automatically combine video. Download it and either place it in `PATH` or pass the path explicitly.

**Comment by nubdienub** [comment]
Hi Grub4k, I have downloaded ffmpeg (and also ffplay / ffprobe) but I feel I have to do some aditional steps since running a query like this still results me in one mp4 file with no sound:

.\yt-dlp.exe https://www.youtube.com/watch?v=RH_V4GPsUYA -f bv*

This is the output to -F : 

`[info] Available formats for RH_V4GPsUYA:
ID      EXT   RESOLUTION FPS CH │   FILESIZE   TBR PROTO │ VCODEC          VBR ACODEC      ABR ASR MORE INFO
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
sb3     mhtml 48x27        0    │                  mhtml │ images                                  storyboard
sb2     mhtml 80x45        0    │                  mhtml │ images                                  storyboard
sb1     mhtml 160x90       0    │                  mhtml │ images                                  storyboard
sb0     mhtml 320x180      0    │                  mhtml │ images                                  storyboard
233     mp4   audio only        │                  m3u8  │ audio only          unknown             Default
234     mp4   audio only        │                  m3u8  │ audio only          unknown             Default
139-drc m4a   audio only      2 │    2.50MiB   49k https │ audio only          mp4a.40.5   49k 22k low, DRC, m4a_dash
249-drc webm  audio only      2 │    2.14MiB   42k https │ audio only          opus        42k 48k low, DRC, webm_dash
250-drc webm  audio only      2 │    2.61MiB   51k https │ audio only          opus        51k 48k low, DRC, webm_dash
139     m4a   audio only      2 │    2.50MiB   49k https │ audio only          mp4a.40.5   49k 22k low, m4a_dash
249     webm  audio only      2 │    2.10MiB   41k https │ audio only          opus        41k 48k low, webm_dash
250     webm  audio only      2 │    2.60MiB   51k https │ audio only          opus        51k 48k low, webm_dash
140-drc m4a   audio only      2 │    6.62MiB  129k https │ audio only          mp4a.40.2  129k 44k medium, DRC, m4a_dash

251-drc webm  audio only      2 │    4.82MiB   94k https │ audio only          opus        94k 48k medium, DRC, webm_dash
140     m4a   audio only      2 │    6.62MiB  129k https │ audio only          mp4a.40.2  129k 44k medium, m4a_dash
251     webm  audio only      2 │    4.80MiB   94k https │ audio only          opus        94k 48k medium, webm_dash
602     mp4   256x144     13    │ ~  6.69MiB  131k m3u8  │ vp09.00.10.08  131k video only
269     mp4   256x144     25    │ ~  9.45MiB  185k m3u8  │ avc1.4D400C    185k video only
160     mp4   256x144     25    │    5.38MiB  105k https │ avc1.4D400C    105k video only          144p, mp4_dash
603     mp4   256x144     25    │ ~ 10.24MiB  200k m3u8  │ vp09.00.11.08  200k video only
278     webm  256x144     25    │    5.28MiB  103k https │ vp9            103k video only          144p, webm_dash
229     mp4   426x240     25    │ ~ 17.38MiB  340k m3u8  │ avc1.4D4015    340k video only
133     mp4   426x240     25    │   12.01MiB  235k https │ avc1.4D4015    235k video only          240p, mp4_dash
604     mp4   426x240     25    │ ~ 19.97MiB  391k m3u8  │ vp09.00.20.08  391k video only
242     webm  426x240     25    │   10.59MiB  207k https │ vp9            207k video only          240p, webm_dash
230     mp4   640x360     25    │ ~ 39.90MiB  780k m3u8  │ avc1.4D401E    780k video only
134     mp4   640x360     25    │   26.11MiB  511k https │ avc1.4D401E    511k video only          360p, mp4_dash
18      mp4   640x360     25  2 │ ≈ 32.69MiB  640k https │ avc1.42001E         mp4a.40.2       44k 360p
605     mp4   640x360     25    │ ~ 36.80MiB  720k m3u8  │ vp09.00.21.08  720k video only
243     webm  640x360     25    │   17.31MiB  339k https │ vp9            339k video only          360p, webm_dash
231     mp4   854x480     25    │ ~ 71.00MiB 1388k m3u8  │ avc1.4D401E   1388k video only
135     mp4   854x480     25    │   50.63MiB  991k https │ avc1.4D401E    991k video only          480p, mp4_dash
606     mp4   854x480     25    │ ~ 58.62MiB 1146k m3u8  │ vp09.00.30.08 1146k video only
244     webm  854x480     25    │   29.03MiB  568k https │ vp9            568k video only          480p, webm_dash
232     mp4   1280x720    25    │ ~134.14MiB 2623k m3u8  │ avc1.64001F   2623k video only
136     mp4   1280x720    25    │   99.09MiB 1939k https │ avc1.64001F   1939k video only          720p, mp4_dash
609     mp4   1280x720    25    │ ~ 98.04MiB 1917k m3u8  │ vp09.00.31.08 1917k video only
247     webm  1280x720    25    │   49.80MiB  974k https │ vp9            974k video only          720p, webm_dash
270     mp4   1920x1080   25    │ ~260.42MiB 5092k m3u8  │ avc1.640028   5092k video only
137     mp4   1920x1080   25    │  204.96MiB 4010k https │ avc1.640028   4010k video only          1080p, mp4_dash
614     mp4   1920x1080   25    │ ~149.37MiB 2921k m3u8  │ vp09.00.40.08 2921k video only
248     webm  1920x1080   25    │   81.74MiB 1599k https │ vp9           1599k video only          1080p, webm_dash`

**Comment by nubdienub** [comment]
Also tried downloading video and audio seperately with ffmpeg in the same folder as yt-dlp but I am clueless on how to operate ffmpeg with yt-dlp

**Comment by seproDev** [comment]
If you don't provide any `-f` argument yt-dlp will download the bestvideo and bestaudio and merge them with ffmpeg. The default value with ffmpeg installed is `-f bestvideo*+bestaudio/best`.
If that doesn't work please provide a verbose log.

**Comment by nubdienub** [comment]
Thanks seproDev (and Grub4k) the command **-f bestvideo*+bestaudio/best** works and provides me with good quality and audio.

**Comment by seproDev** [comment]
Since that is the default you can just leave out the `-f` altogether. You weren't getting the higher quality versions before due to missing ffmpeg, which causes yt-dlp to switch the default to prefer premerged formats. For youtube that means 360p videos.
yt-dlp should have also been warning you about missing ffmpeg, and thus reduced quality.
