### ISSUE TITLE
Recover licenses associated with a youtube video

### ISSUE THREAD

**Issue by triplesixman** [yt-dlp/yt-dlp#10280]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I used to retrieve the licenses/labels associated with youtube videos, but since the latest youtube update, it's no longer possible to display a video's licenses as it used to be, see screenshot below.

![image](https://github.com/yt-dlp/yt-dlp/assets/44361142/bdc2e51a-186e-4051-b94e-c080f83170a6)

I wonder if anyone has a workaround or other solution to retrieve the labels associated with a youtube video (if any).

Note: It was not possible to retrieve these elements via yt-dlp, I was scrapping the URL with phantomjs.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
Looks like this is essentially the same issue that https://github.com/yt-dlp/yt-dlp/issues/4217#issuecomment-1345691508 is attempting to solve
