### ISSUE TITLE
Can I legally allow users to download audio from YouTube?

### ISSUE THREAD

**Issue by iaseth** [yt-dlp/yt-dlp#10289]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I am sorry but this is not directly related to yt-dlp. But I am still asking it here because there is probably no other community who would know more about this.

I make a paid Desktop application where students can read news, books, practice tests, etc. Some of my users are asking me to have a feature where they can listen to audio from podcasting websites including YouTube. I have used the hidden/documented APIs of these websites, so implementing such a feature won't be difficult. But I was wondering if it is legal?

There are many Online and Desktop apps that allow users to download audio from YouTube or other sites. My app would have a similar feature where user can put in a link and the app will download and play the audio. Do you guys think I can give this feature without getting into trouble?

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
out-of-scope
