### ISSUE TITLE
[youtube:tab] Unable to recognize playlist

### ISSUE THREAD

**Issue by 276562578** [yt-dlp/yt-dlp#10287]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

USA

### Provide a description that is worded well enough to be understood

I want to download a playlist on YouTube, but it tells me that it cannot recognize the playlist. The playlist has been set to public and I have also used cookies
    
### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-F', '--cookies-from-browser', 'chrome', 'https://www.youtube.com/watch?v=QyYSMpCUrEs&list=TLPQMjgwNjIwMjQC9Rpm6seRQg', '-vU']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.05.27 from yt-dlp/yt-dlp [12b248ce6] (debian*)
[debug] Python 3.11.2 (CPython x86_64 64bit) - Linux-6.1.0-15-amd64-x86_64-with-glibc2.36 (OpenSSL 3.0.11 19 Sep 2023, glibc 2.36)
[debug] exe versions: ffmpeg 5.1.4-0 (setts), ffprobe 5.1.4-0, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.02.02, mutagen-1.47.0, pyxattr-0.8.1, requests-2.31.0, secretstorage-3.3.3, sqlite3-3.40.1, urllib3-2.2.1, websockets-11.0.3
[debug] Proxy map: {'no': 'localhost,127.0.0.0/8,::1,*.edu.cn', 'https': 'http://127.0.0.1:7890', 'http': 'http://127.0.0.1:7890', 'all': 'socks5://127.0.0.1:7890'}
Extracting cookies from chrome
[debug] Extracting cookies from: "/home/minecraft/.config/google-chrome/Default/Cookies"
[Cookies] Loading cookie      0/  2087[debug] detected desktop environment: GNOME
[debug] Chosen keyring: GNOMEKEYRING
Extracted 2035 cookies from chrome
[debug] cookie version breakdown: {'v10': 0, 'v11': 2069, 'other': 0, 'unencrypted': 18}
[debug] Request Handlers: urllib, requests
[debug] Loaded 1820 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.05.27 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.05.27 from yt-dlp/yt-dlp)
[youtube:tab] Extracting URL: https://www.youtube.com/watch?v=QyYSMpCUrEs&list=TLPQMjgwNjIwMjQC9Rpm6seRQg
[youtube:tab] Downloading playlist TLPQMjgwNjIwMjQC9Rpm6seRQg - add --no-playlist to download just the video QyYSMpCUrEs
[youtube:tab] TLPQMjgwNjIwMjQC9Rpm6seRQg: Downloading webpage
WARNING: [youtube:tab] Unable to recognize playlist. Downloading just video QyYSMpCUrEs
[youtube] Extracting URL: https://www.youtube.com/watch?v=QyYSMpCUrEs
[youtube] QyYSMpCUrEs: Downloading webpage
[debug] [youtube] Extracted SAPISID cookie
[youtube] QyYSMpCUrEs: Downloading ios player API JSON
[debug] [youtube] Extracting signature function js_5b22937f_105
[debug] Loading youtube-sigfuncs.js_5b22937f_105 from cache
[debug] Loading youtube-nsig.5b22937f from cache
[debug] [youtube] Decrypted nsig 2OO0IqCn2IwQeEG- => gv28cU7pG0MEqw
[debug] Loading youtube-nsig.5b22937f from cache
[debug] [youtube] Decrypted nsig 8ofh6y4IgcAK2pZ0 => Qf9e5nFcIjIG-Q
[debug] [youtube] Extracting signature function js_5b22937f_101
[debug] Loading youtube-sigfuncs.js_5b22937f_101 from cache
[youtube] QyYSMpCUrEs: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[info] Available formats for QyYSMpCUrEs:
```

**Comment by coletdjnz** [comment]
The playlist you linked does not exist.

That looks like a temporary playlist Id, likely your YouTube queue rather than the actual playlist
