### ISSUE TITLE
How to get the download progress

### ISSUE THREAD

**Issue by Kukaina** [yt-dlp/yt-dlp#10288]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I've recently been working on a GUI interface for yt-dlp where I need to get the download progress of a file and show it but I don't know how to do it.The GUI interface I made is shown below
![image](https://github.com/yt-dlp/yt-dlp/assets/149920301/8c0cb63f-a5dd-4a3e-8816-0b6cd62f803c)
I tried to rewrite the download function myself, which solved the problem, but I still wonder if yt-dlp itself has a way to get the download progress

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by rdamas** [comment]
Register a progress hook as described: https://github.com/yt-dlp/yt-dlp#adding-logger-and-progress-hook
