### ISSUE TITLE
bestvideo[height<=if current screen height >= 1080 ? 1080 else 720]: configs: ability to set height according to the current screen size

### ISSUE THREAD

**Issue by vitaly-zdanevich** [yt-dlp/yt-dlp#10299]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Hi, the case: user have laptop with smaller screen and home big computer with big screen - looks like currently there is no way to set dynamic height.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by PlaylistsTrance** [comment]
I doubt complex syntax like this will be added soon, but at the moment you could make use of configuration files.

**Comment by bashonly** [comment]
This is out-of-scope. Just use a different [config file](https://github.com/yt-dlp/yt-dlp#configuration) / command line on each machine
