### ISSUE TITLE
Bitchute has suddenly just stopped working...

### ISSUE THREAD

**Issue by bushnest** [yt-dlp/yt-dlp#10293]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United States

### Provide a description that is worded well enough to be understood

Within the last few hours, Bitchute(www.bitchute.com) has up and changed the layout/design of their site.  As a result of this, yt-dlp no longer works with Bitchute.  Can this issue be fixed at all?  Thx.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp -vU https://www.bitchute.com/video/YaeHvb0bPvHg
[debug] Command-line config: ['-vU', 'https://www.bitchute.com/video/YaeHvb0bPvHg']                 [debug] Encodings: locale utf-8, fs utf-8, pref utf-8, out utf-8, error utf-8, screen utf-8         [debug] yt-dlp version stable@2024.05.27 from yt-dlp/yt-dlp [12b248ce6] (pip)
[debug] Python 3.11.9 (CPython aarch64 64bit) - Linux-4.19.157-perf+-aarch64-with-libc (OpenSSL 3.2.1 30 Jan 2024, libc)
[debug] exe versions: ffmpeg 6.1.1 (setts), ffprobe 6.1.1
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.07.22, mutagen-1.47.0, requests-2.31.0, sqlite3-3.46.0, urllib3-1.26.19, websockets-12.0                                      [debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1820 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.05.27 from yt-dlp/yt-dlp                                                yt-dlp is up to date (stable@2024.05.27 from yt-dlp/yt-dlp)                                         [BitChute] Extracting URL: https://www.bitchute.com/video/YaeHvb0bPvHg
[BitChute] YaeHvb0bPvHg: Downloading webpage
ERROR: [BitChute] YaeHvb0bPvHg: Video is unavailable. Please make sure this video is playable in the browser before reporting this issue.               File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 734, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/yt_dlp/extractor/bitchute.py", line 150, in _real_extract
    self.raise_no_formats(
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 1257, in raise_no_formats
    raise ExtractorError(msg, expected=expected, video_id=video_id)
```

**Comment by wtechgo** [comment]
This issue started with the rollout of BitChute's new UI.
Perhaps they implemented a strategy against downloaders in the same move.

**Comment by bushnest** [comment]
Yeah, that could be one of the reasons why they implemented that whole new layout/design/UI.  The question now is whether or not there's a workaround to it that can be used by yt-dlp.

**Comment by L8LEE** [comment]
I found a way around for now. Open the inspector, click on network, reload the page, scroll up or down until you see a line that has the video identifier followed by .mp4, right click on that line and open in a new tab or copy the url, then download that url instead.

You should end up with a url that looks like this :

https://seed1sjt3.bitchute.com/DmYPimVufu4I/wb7ULyjWp01w.mp4

**Comment by bushnest** [comment]
> I found a way around for now. Open the inspector, click on network, reload the page, scroll up or down until you see a line that has the video identifier followed by .mp4, right click on that line and open in a new tab or copy the url, then download that url instead.
> 
> You should end up with a url that looks like this :
> 
> https://seed1sjt3.bitchute.com/DmYPimVufu4I/wb7ULyjWp01w.mp4

I'll give that a try.  Thanks.

**Comment by wtechgo** [comment]
@pukkandan this is probably important.

**Comment by seproDev** [comment]
Don't ping random people.

As a workaround until someone rewrites the extractor using their new API, this patch can be applied:
```diff
diff --git a/yt_dlp/extractor/bitchute.py b/yt_dlp/extractor/bitchute.py
index c74f34c2a..b816ad50c 100644
--- a/yt_dlp/extractor/bitchute.py
+++ b/yt_dlp/extractor/bitchute.py
@@ -132,7 +132,7 @@ def _make_url(html):
     def _real_extract(self, url):
         video_id = self._match_id(url)
         webpage = self._download_webpage(
-            f'https://www.bitchute.com/video/{video_id}', video_id, headers=self._HEADERS)
+            f'https://old.bitchute.com/video/{video_id}', video_id, headers=self._HEADERS)

         self._raise_if_restricted(webpage)
         publish_date = clean_html(get_element_by_class('video-publish-date', webpage))
 ```

**Comment by wtechgo** [comment]
Test.
