### ISSUE TITLE
yt-dlp Merger error

### ISSUE THREAD

**Issue by zaqpython** [yt-dlp/yt-dlp#10290]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I have downloaded the video I need, and I have checked the audio video, but why does the merging error still occur? If I put the same code on another server, this problem will not occur. Could you please tell me how to solve this problem

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
2024-06-28 16:14:40.557 | INFO     | __main__:download_video:137 - EFGtXEF_w7U
[youtube] Extracting URL: https://www.youtube.com/watch?v=EFGtXEF_w7U
[youtube] EFGtXEF_w7U: Downloading webpage
[info] EFGtXEF_w7U: Downloading subtitles: en
[info] EFGtXEF_w7U: Downloading 1 format(s): 18
Deleting existing file download/EFGtXEF_w7U.en.vtt
[info] Writing video subtitles to: download/EFGtXEF_w7U.en.vtt
[download] Destination: download/EFGtXEF_w7U.en.vtt
[download] 100% of    1.81KiB in 00:00:00 at 8.88KiB/s
[download] Destination: download/EFGtXEF_w7U.mp4
[download] 100% of    1.34MiB in 00:00:01 at 1.05MiB/s
[Merger] Merging formats into "download/EFGtXEF_w7U.mp4"
2024-06-28 16:14:46.407 | ERROR    | __main__:download_video:193 - retry 0 错误 [Errno 2] No such file or directory: 'download/EFGtXEF_w7U.f18.mp4'
[youtube] Extracting URL: https://www.youtube.com/watch?v=EFGtXEF_w7U
[youtube] EFGtXEF_w7U: Downloading webpage
[info] EFGtXEF_w7U: Downloading subtitles: en
[info] EFGtXEF_w7U: Downloading 1 format(s): 18
Deleting existing file download/EFGtXEF_w7U.en.vtt
[info] Writing video subtitles to: download/EFGtXEF_w7U.en.vtt
[download] Destination: download/EFGtXEF_w7U.en.vtt
[download] 100% of    1.81KiB in 00:00:00 at 18.62KiB/s
[download] download/EFGtXEF_w7U.mp4 has already been downloaded
2024-06-28 16:14:51.710 | SUCCESS  | __main__:download_video:184 - video EFGtXEF_w7U download success
```

**Comment by bashonly** [comment]
It looks like you are using an external script. Please either reproduce the issue directly with yt-dlp and provide a **complete verbose** log (as instructed in the issue template). If you are unable to do that, then either provide a minimal reproducible example, or the full source code of the script you're using.

**Comment by bashonly** [comment]
@lljs1955 Not the exact same problem; you are experiencing #7541. It's a bug in older versions of ffmpeg. The solution is to upgrade to ffmpeg 7.0.1 or to the [latest ffmpeg master build](https://github.com/yt-dlp/FFmpeg-Builds/releases/latest). Verbose log is much appreciated
