### ISSUE TITLE
Why don't the cookies I set work?

### ISSUE THREAD

**Issue by Kukaina** [yt-dlp/yt-dlp#10297]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I try to set cookies for download using Python, the code is as follows
```Python
from yt_dlp import YoutubeDL

ydl_opts = {
    'cookies-from-browser':"Chrome"
}
URL = 'https://www.bilibili.com/video/BV1Pb421p77m?vd_source=6a5420e60ed4e7665cd8474ec2132724'
with YoutubeDL(ydl_opts) as ydl:
    ydl.download(URL) 
```
Alternatively I have also tried using the use cookies parameter and exporting cookies using a browser plugin
```Python
ydl_opts = {
    'cookies':'c:\\Users\\HUTAO\\Desktop\\cookie.txt'
}
```
I have even tried adding `--` before the parameter，but they still don’t work，The terminal will prompt `[BiliBili] Format(s) 1080P high bit rate, 1080P high definition, 720P high definition are missing; you have to login or become premium member to download them. Use --cookies-from-browser or --cookies for the authentication. See https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp for how to manually pass cookies`
I have made sure I am logged into this website in my browser

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[BiliBili] Extracting URL: https://www.bilibili.com/video/BV1Pb421p77m?vd_source=6a5420e60ed4e7665cd8474ec2132724 
[BiliBili] 1Pb421p77m: Downloading webpage 
[BiliBili] BV1Pb421p77m: Extracting videos in anthology 
[BiliBili] 1805826227: Extracting chapters 
[BiliBili] Format(s) 1080P 高码率, 1080P 高清, 720P 高清 are missing; you have to login or become premium member to download them. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies 
[info] BV1Pb421p77m: Downloading 1 format(s): 100110+30280 
[download] Destination: 坚持高温下运动，你的身体会发生什么？ [BV1Pb421p77m].f100110.mp4 
[download] 100% of    7.84MiB in 00:00:00 at 22.33MiB/s
[download] Destination: 坚持高温下运动，你的身体会发生什么？ [BV1Pb421p77m].f30280.m4a 
[download] 100% of    5.99MiB in 00:00:00 at 31.36MiB/s
[Merger] Merging formats into "坚持高温下运动，你的身体会发生什么？ [BV1Pb421p77m].mp4" 
Deleting original file 坚持高温下运动，你的身体会发生什么？ [BV1Pb421p77m].f30280.m4a (pass -k to keep) 
Deleting original file 坚持高温下运动，你的身体会发生什么？ [BV1Pb421p77m].f100110.mp4 (pass -k to keep)
```

**Comment by bashonly** [comment]
It's because `'cookies-from-browser':"Chrome"` is not correct. You want this:

```py
ydl_opts = {
    'cookiesfrombrowser': ('chrome', None, None, None),
}
```

**P.S.** Use [**`devscripts/cli_to_api.py`**](https://github.com/yt-dlp/yt-dlp/blob/master/devscripts/cli_to_api.py)
