### ISSUE TITLE
[SUGGESTION] Consider an LTS release

### ISSUE THREAD

**Issue by pirate486743186** [yt-dlp/yt-dlp#1030]
yt-dlp/youtube-dl is not a normal program, it gets obsolete very fast, you can't realistically use a version from 5 years ago. So a bleding edge model leaves some users behind.

The way youtube-dl did "LTS", was by supporting very old  and very new python versions in the same executable. That's a bit... insane IMHO.

I think a more sane approach to LTS is by having an LTS release. Some version gets relatively frozen. Meaning only extractors get backported and the range of python versions each executable supports is much smaller. A variant would be to LTS support only some short list of sites.

The first LTS release, could be derived from the last release of youtube-dl.

I don't think that manpower will be a problem. Once youtube-dl brakes on youtube, yt-dlp will get a huge burst of attention with a large number of PRs.  Ideally, deciding on an LTS release should happen before youtube brakes on youtube-dl. This way, this project collects all the users and devs from youtube-dl and an other fork has no chance of emerging. If this doesn't happen and the LTS is too much of a power drain, you can always kill it prematurely or downscale it. I think, it's worth the try.

**Comment by Ashish0804** [comment]
You are free to fork ytdlp and implement these features, the license is very permissive imo.

**Comment by pukkandan** [comment]
As I already said in #267, this is not happening. Opening new issues about it not going to change my mind. If you don't think there is much additional work in doing this, you are free to just maintain it yourself
