### ISSUE TITLE
Can I change my installation file?

### ISSUE THREAD

**Issue by cedricdu06** [yt-dlp/yt-dlp#10300]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Hello , 
I would like to change the installation path? I am a beginner 
What should I change to put it in home/cedric under debian 12? 

wget https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -O ~/.local/bin/yt-dlp
chmod a+rx ~/.local/bin/yt-dlp # Make executable

Thank you for your help

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
`~` expands to `/home/YOURUSERNAME`

Do you need help adding `/home/cedric/.local/bin` to your PATH? Or please elaborate

**Comment by cedricdu06** [comment]
> Do you need help adding `/home/cedric/.local/bin` to your PATH? Or please elaborate

Yes problem add path

**Comment by bashonly** [comment]
If your primary shell is bash, add this line to the bottom of your `~/.bash_profile` file:
```bash
export PATH="${HOME}/.local/bin:${PATH}"
```
then log out / log back in

**Comment by cedricdu06** [comment]
Thank you for your help, I'll try it in the evening.

**Comment by cedricdu06** [comment]
Hello , 
where should I put this? I am a beginner in debian 12 
Thanks

**Comment by bashonly** [comment]
Run this command (copy and paste it; it MUST have the exact same quoting etc):

```bash
echo 'export PATH="${HOME}/.local/bin:${PATH}"' >> ~/.bash_profile
```

**Comment by cedricdu06** [comment]
Hello 
I have this error 

curl: (23) Failure writing output to destination
chmod: cannot access '/root/.local/bin/yt-dlp': No such file or directory

**Comment by bashonly** [comment]
@cedricdu06 Do not run any of these commands as root! Run them under your user
