### ISSUE TITLE
Crunchyroll Subtitle Downloader

### ISSUE THREAD

**Issue by MrFanservice-png** [yt-dlp/yt-dlp#10309]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Can yt-dlp download Crunchyroll subtitles from premium videos?

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by Tama47** [comment]
```
yt-dlp --ignore-no-formats-error --skip-download --write-sub --sub-langs en-US --username "username" --password "password" "url"
```

**Comment by MrFanservice-png** [comment]
I got ERROR: [crunchyroll] GYZXQ2036: Invalid username and/or password even though I put in the correct username and password.

**Comment by bashonly** [comment]
Username needs to be your email address. This could be an issue with special characters/escaping. Make sure to quote your username/email. Also, omit `--password` from the command and yt-dlp will prompt you to enter it interactively

**Comment by MrFanservice-png** [comment]
Here are the languages of the subtitles. I only want to extract the English and Deutsch ones.
![Screenshot (826)](https://github.com/yt-dlp/yt-dlp/assets/171995610/8f8685e2-c766-41fc-9005-a0b04a7c8f83)

**Comment by bashonly** [comment]
`--write-sub --sub-lang "en.*,de.*"`

**Comment by MrFanservice-png** [comment]
I got this:

`WARNING: [crunchyroll] GYZXQ2036: This episode is for premium members only
[crunchyroll] GYZXQ2036: Downloading chapter info
WARNING: No video formats found!
WARNING: Requested format is not available
[info] There are no subtitles for the requested languages`

**Comment by bashonly** [comment]
if it's premium-only content and you don't have premium it's not gonna work. yt-dlp isn't magic

**Comment by Discgear** [comment]
It appears just trying to download thumbnails or subs spits out 403 error.
