### ISSUE TITLE
[Vimeo] HTTP Error 403 Forbidden / HTTP Error 429 Too Many Requests

### ISSUE THREAD

**Issue by scrutinizer11** [yt-dlp/yt-dlp#10325]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [x] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [x] I'm reporting that yt-dlp is broken on a **supported** site
- [x] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [x] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [x] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [x] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [x] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Europe

### Provide a description that is worded well enough to be understood

Downloading the provided link on the Vimeo platform fails.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-v', '--no-check-certificates', '--no-warnings', '--geo-bypass', 'https://vimeo.com/324146324']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.06.30.232744 from yt-dlp/yt-dlp-nightly-builds [24f3097ea] (darwin_legacy_exe)
[debug] Python 3.10.5 (CPython x86_64 64bit) - macOS-10.9.5-x86_64-i386-64bit (OpenSSL 1.1.1n  15 Mar 2022)
[debug] exe versions: ffmpeg N-101508-ge93403b (setts), ffprobe N-101508-ge93403b
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.06.02, mutagen-1.47.0, requests-2.32.3, sqlite3-3.37.2, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {'https': 'localhost:3128'}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1824 extractors
[vimeo] Extracting URL: https://vimeo.com/324146324
[vimeo] 324146324: Downloading webpage
ERROR: [vimeo] 324146324: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: Forbidden>)
  File "yt_dlp/extractor/common.py", line 740, in extract
  File "yt_dlp/extractor/vimeo.py", line 834, in _real_extract
  File "yt_dlp/extractor/common.py", line 960, in _download_webpage_handle
  File "yt_dlp/extractor/common.py", line 909, in _request_webpage

  File "yt_dlp/extractor/common.py", line 896, in _request_webpage
  File "yt_dlp/YoutubeDL.py", line 4141, in urlopen
  File "yt_dlp/networking/common.py", line 117, in send
  File "yt_dlp/networking/_helper.py", line 208, in wrapper
  File "yt_dlp/networking/common.py", line 337, in send
  File "yt_dlp/networking/_requests.py", line 361, in _send
yt_dlp.networking.exceptions.HTTPError: HTTP Error 403: Forbidden
```

A different configuration:
```bash
[debug] Command-line config: ['--proxy', 'localhost:3128', '--no-check-certificates', '--no-warnings', '--geo-bypass', '--force-overwrites', '--write-subs', '-sub-langs', '(en|ru)-orig,en', '--convert-subs', 'srt', '-S', 'res:1080', '-v', 'https://vimeo.com/324146324']
Type account password and press [Return]: 
```

**Comment by bashonly** [comment]
please don't skip the issue template

**Comment by scrutinizer11** [comment]
All the info in the debugging information that's required anyway. You have the data. I'm just saving my time.

**Comment by bashonly** [comment]
Please complete the rest of it. It's the rules of the tracker.

**Comment by bashonly** [comment]
Anyways, it's TLS fingerprinting anti-bot protection. Passing `--impersonate chrome` (if curl_cffi is available) or downgrading the URL to `http://` works around the issue.

**Comment by bashonly** [comment]
Additional note: Vimeo is discriminating against data center IPs and the above mitigation tactics will not work for affected IPs

**Comment by scrutinizer11** [comment]
After a period when it seemingly subsided, it got back, aggrandized. In the previous yt-dlp version, downgrading the URL to HTTP appeared to cure the issue. In contrast to that and in addition to changing the protocol to HTTP, version 2024.07.05.232716 would only download with the proxy setting removed.

However, the primary reason why this issue breaks all my efforts is that I use yt-dlp in my AppleScript scripts. Running the adapted command from the shell completes successfully, but once I run the same command as the argument to **do shell script** I get:

```applescript
error "ERROR: [vimeo] 324146324: Unable to download JSON metadata: ('Unable to connect to proxy. 
Your proxy appears to only use HTTP and not HTTPS, 
try changing your proxy URL to be HTTP. See:

https://urllib3.readthedocs.io/en/latest/advanced-usage.html#https-proxy-
error-http-proxy', 
SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] 
wrong version number (_ssl.c:997)'))) 
(caused by ProxyError(\"('Unable to connect to proxy. 
Your proxy appears to only use HTTP and not HTTPS, 
try changing your proxy URL to be HTTP. See: 

https://urllib3.readthedocs.io/en/latest/advanced-usage.html#https-proxy-error-http-proxy', 
SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] 
wrong version number (_ssl.c:997)')))\")); 
``` 

I had used the proxy in shell and AppleScript without any complications until June.

**Comment by coletdjnz** [comment]
> After a period when it seemingly subsided, it got back, aggrandized. In the previous yt-dlp version, downgrading the URL to HTTP appeared to cure the issue. In contrast to that and in addition to changing the protocol to HTTP, version 2024.07.05.232716 will only download with the proxy setting removed.
> 
> However, the primary reason why this issue breaks all my efforts is that I use yt-dlp in my AppleScript scripts. Running the adapted command from the shell completes successfully, but once I run the same command as the argument to **do shell script** I get:
> 
> ```applescript
> error "ERROR: [vimeo] 324146324: Unable to download JSON metadata: ('Unable to connect to proxy. 
> Your proxy appears to only use HTTP and not HTTPS, 
> try changing your proxy URL to be HTTP. See:
> 
> https://urllib3.readthedocs.io/en/latest/advanced-usage.html#https-proxy-
> error-http-proxy', 
> SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] 
> wrong version number (_ssl.c:997)'))) 
> (caused by ProxyError(\"('Unable to connect to proxy. 
> Your proxy appears to only use HTTP and not HTTPS, 
> try changing your proxy URL to be HTTP. See: 
> 
> https://urllib3.readthedocs.io/en/latest/advanced-usage.html#https-proxy-error-http-proxy', 
> SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] 
> wrong version number (_ssl.c:997)')))\")); 
> ```
> 
> I had used the proxy and HTTPS in shell and AppleScript without any complications until June.

Your proxy is HTTP and you are incorrectly passing it as HTTPS, which might've worked before (if your yt-dlp was months out of date) due to broken behaviour that treated a HTTPS proxy as HTTP. Now we actually support HTTPS proxy that won't work.

**Comment by scrutinizer11** [comment]
> Your proxy is HTTP and you are incorrectly passing it as HTTPS

My system reports differently.

![Screenshot 2024-07-06_08-00-53-765](https://github.com/yt-dlp/yt-dlp/assets/45983734/474c9f40-516b-4472-b1f2-90271bbf2a10)

 

>Now we actually support HTTPS proxy that won't work.

I didn't understand this sentence.

**Comment by coletdjnz** [comment]
> 
> > Your proxy is HTTP and you are incorrectly passing it as HTTPS
> 
> My system reports differently.
> 
> ![Screenshot 2024-07-06_08-00-53-765](https://github.com/yt-dlp/yt-dlp/assets/45983734/474c9f40-516b-4472-b1f2-90271bbf2a10)
> 
>  
> 
> >Now we actually support HTTPS proxy that won't work.
> 
> I didn't understand this sentence.
> 

Would you be able provide the full verbose output of the command encountering this error pls? Something doesn't add up 🤔

**Comment by scrutinizer11** [comment]
Three configurations via shell in the macOS Terminal:

1. Success

```AppleScript
[debug] Command-line config: ['-v', '--no-check-certificates', '--geo-bypass', '--no-warnings', '--ffmpeg-location', '/usr/local/bin/ffmpeg', '--force-overwrites', '-S', 'res:1080', '-O', '%(title)s', 'http://vimeo.com/324146324']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.07.05.232716 from yt-dlp/yt-dlp-nightly-builds [246911949] (darwin_legacy_exe)
[debug] Python 3.10.5 (CPython x86_64 64bit) - macOS-10.9.5-x86_64-i386-64bit (OpenSSL 1.1.1n  15 Mar 2022)
[debug] exe versions: ffmpeg N-101508-ge93403b (setts), ffprobe N-101508-ge93403b
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.07.04, mutagen-1.47.0, requests-2.32.3, sqlite3-3.37.2, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {'https': 'localhost:3128'}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1832 extractors
[vimeo] Extracting URL: http://vimeo.com/324146324
[vimeo] 324146324: Downloading webpage
[vimeo] 324146324: Downloading JSON metadata
[vimeo] 324146324: Downloading JSON metadata
[vimeo] 324146324: Downloading jwt token
[vimeo] 324146324: Downloading JSON metadata
[vimeo] 324146324: Downloading akfire_interconnect_quic m3u8 information
[vimeo] 324146324: Downloading fastly_skyfire m3u8 information
[vimeo] 324146324: Downloading akfire_interconnect_quic MPD information
[vimeo] 324146324: Downloading fastly_skyfire MPD information
[debug] Sort order given by user: res:1080
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source
[debug] Formats sorted by: hasvid, ie_pref, res:1080(1080.0), quality, fps, hdr:12(7), source, lang, vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 324146324: Downloading 1 format(s): hls-fastly_skyfire-3717+hls-fastly_skyfire-audio-low-Original
Mars Habitat - Full Film
```
2. Failure
```AppleScript
[debug] Command-line config: ['--proxy', 'localhost:3128', '-v', '--no-check-certificates', '--geo-bypass', '--no-warnings', '--ffmpeg-location', '/usr/local/bin/ffmpeg', '--force-overwrites', '-S', 'res:1080', '-O', '%(title)s', 'http://vimeo.com/324146324']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.07.05.232716 from yt-dlp/yt-dlp-nightly-builds [246911949] (darwin_legacy_exe)
[debug] Python 3.10.5 (CPython x86_64 64bit) - macOS-10.9.5-x86_64-i386-64bit (OpenSSL 1.1.1n  15 Mar 2022)
[debug] exe versions: ffmpeg N-101508-ge93403b (setts), ffprobe N-101508-ge93403b
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.07.04, mutagen-1.47.0, requests-2.32.3, sqlite3-3.37.2, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {'all': 'localhost:3128'}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1832 extractors
[vimeo] Extracting URL: http://vimeo.com/324146324
[vimeo] 324146324: Downloading webpage
ERROR: [vimeo] 324146324: Got HTTP Error 403. If you are using a data center IP or VPN/proxy, your IP may be blocked
  File "yt_dlp/extractor/common.py", line 740, in extract
  File "yt_dlp/extractor/vimeo.py", line 862, in _real_extract
```
3. Failure

```AppleScript
[debug] Command-line config: ['-v', '--no-check-certificates', '--geo-bypass', '--no-warnings', '--ffmpeg-location', '/usr/local/bin/ffmpeg', '--force-overwrites', '-S', 'res:1080', '-O', '%(title)s', 'https://vimeo.com/324146324']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.07.05.232716 from yt-dlp/yt-dlp-nightly-builds [246911949] (darwin_legacy_exe)
[debug] Python 3.10.5 (CPython x86_64 64bit) - macOS-10.9.5-x86_64-i386-64bit (OpenSSL 1.1.1n  15 Mar 2022)
[debug] exe versions: ffmpeg N-101508-ge93403b (setts), ffprobe N-101508-ge93403b
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.07.04, mutagen-1.47.0, requests-2.32.3, sqlite3-3.37.2, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {'https': 'localhost:3128'}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1832 extractors
[vimeo] Extracting URL: https://vimeo.com/324146324
[vimeo] 324146324: Downloading webpage
ERROR: [vimeo] 324146324: This request has been blocked due to its TLS fingerprint. Install a required impersonation dependency if possible, or else if you are okay with compromising your security/cookies, try replacing "https:" with "http:" in the input URL. If you are using a data center IP or VPN/proxy, your IP may be blocked.
  File "yt_dlp/extractor/common.py", line 740, in extract
  File "yt_dlp/extractor/vimeo.py", line 863, in _real_extract
```

**Comment by bashonly** [comment]
Key points from the logs:

2.
> If you are using a data center IP or VPN/proxy, your IP may be blocked

3.
> This request has been blocked due to its TLS fingerprint. Install a required impersonation dependency if possible

**Comment by scrutinizer11** [comment]
It didn't take much for me to notice these "key points" either. The problem is how to get it working from my AppleScript scripts. You saw three large logs containing manifestations of some obstruction when direct traffic passes via an insecure connection. However, the obstruction goes when I discard this configuration but only in the shell. 
**The decision-making revolves around telling it to run in the AppleScript environment.** What would you suggest? 

According to the developer of the Squid-based implementation of the proxy in question, that is running in my system, it encodes old-type protocol requests that my system sends out with the newest one. So, I must use it to talk to the world, including Unix binaries that support proxying.

**Comment by scrutinizer11** [comment]
It didn't take much for me to notice these "key points" either. The problem is how to get it working from my AppleScript scripts. You saw three large logs containing manifestations of some obstruction when proxied traffic does not pass via a secure connection. However, the obstruction goes when I discard the original configuration but only in the shell.
The decision-making revolves around telling it to run in the AppleScript environment. What would you suggest without resorting to guesswork?

According to the developer of the Squid-based implementation of the proxy in question, that is running in my system, it encodes old-type protocol requests that my system sends out with the newest one. So, I must use it to talk to the world, including Unix binaries that support proxying.

**Comment by greggblazer** [comment]
TOTALLY As of this Date SOLVED for this Annoying Persistant ERROR even after updating to this dates Latest builds and Nightly builds!

I am not sure how exactly to SHARE this vital information except that anyone can DM me of reach me on my Facebook profile as I am the ONLY GREGG BLAZER in the world on FB. Simple.

Why I am not sharing here?  Glad you asked.. I am SICK and bloody tired of Vimeo and YT being Bloody bASS-TURDS always maing things so stupid to be able to watch off line etc.. 

So IF I put it here and you guys do gues what.. their stupid DEVS just google and then read what you did and bam they screw you lol.

So DM me and happy to share. It is not that hard. I created a FULL PDF Simple SOP guide even a 5 year old can follow even if you have Never installed yt-dlp before! lol
