### ISSUE TITLE
How to pick the <nth> format when not using 'best'

### ISSUE THREAD

**Issue by notevenaperson** [yt-dlp/yt-dlp#10331]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Hi, I'm trying to come with a change to the syntax of this format selection string that makes it pick only **one** format.
```
-f "all[format_note=storyboard]"
```
Currently it downloads sb0, sb1, sb2, etc. I would like to download only one. The manual describes this:

> You can select the n'th best format of a type by using `best<type>.<n>`.  For example, best.2 will select the 2nd best combined format.  Similarly, bv*.3 will select the 3rd best format that contains a video stream.

Perhaps a `.1` would work here, but `all[format_note=storyboard].1` or `all.1[format_note=storyboard]` makes it select nothing. Re-reading that part of the manual, the `<nth>` syntax is only described with respect to the `best` format. Does it not work with the `all` format?
I hope it's clear why I'm trying to do this. Could there be an alternate way to achieve this goal?

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-S', '+size,+br,+res', '-f', 'all.1[format_note=storyboard]', 'TKqlmbZyS6M', '-4', '--ignore-config', '-v', '--no-cache-dir']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.05.27 from yt-dlp/yt-dlp [12b248ce6]
[debug] Python 3.12.3 (CPython x86_64 64bit) - Linux-6.9.4-arch1-1-x86_64-with-glibc2.39 (OpenSSL 3.3.1 4 Jun 2024, glibc 2.39)
[debug] exe versions: ffmpeg 6.1.1 (setts), ffprobe 6.1.1
[debug] Optional libraries: Cryptodome-3.20.0, certifi-2024.06.02, mutagen-1.47.0, requests-2.32.3, sqlite3-3.46.0, urllib3-1.26.18, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1820 extractors
[youtube] Extracting URL: TKqlmbZyS6M
[youtube] TKqlmbZyS6M: Downloading webpage
[youtube] TKqlmbZyS6M: Downloading ios player API JSON
[debug] [youtube] Extracting signature function js_81a0fcab_106
[youtube] TKqlmbZyS6M: Downloading player 81a0fcab
[debug] [youtube] Decrypted nsig sA1_l3O2nXx9t-xp39-p => uOispjhUUsVtSQ
[debug] [youtube] Decrypted nsig Fvy1TfvTht_F1LBGMgxY => L9fQQI61HSRffA
[youtube] TKqlmbZyS6M: Downloading m3u8 information
[debug] Sort order given by user: +size, +br, +res
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, +size, +br, +res, quality, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, asr, vext, aext, hasaud, id
ERROR: [youtube] TKqlmbZyS6M: Requested format is not available. Use --list-formats for a list of available formats
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 1606, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 1762, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 1821, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 2955, in process_video_result
    raise ExtractorError(
yt_dlp.utils.ExtractorError: [youtube] TKqlmbZyS6M: Requested format is not available. Use --list-formats for a list of available formats
```

**Comment by bashonly** [comment]
> Does it not work with the `all` format?

No. `all` will download `all`. Selecting an individual format would defeat the purpose of `all`.

For any format other than storyboards, you could use `best.2` / `bestvideo.2` / `bestaudio.2` etc. But storyboards are considered neither video nor audio by yt-dlp.

Do you actually want the storyboard format? Or are you just using a storyboard format for the sake of the example? If you actually want a storyboard format, then just pass the format id, e.g. `-f sb0` , `-f sb1` etc

**Comment by notevenaperson** [comment]
Thanks for re-labeling as question. Right, I *am* using -f sb0, but because I don't know if *all* extractors call storyboards `sb0` (youtube does but I didn't investigate others), and I want to make sure I select available storyboards, I decided to have a selector using `format_note=storyboard` present, in case sb0 doesn't exist. This is my actual selector expression:
```
-f "sb0/all[format_note=storyboard]"
```
I figure it's unlikely that an extractor uses an unconventional name for a storyboard (a name that is not `sb0`), but otherwise I wanted to make sure the fallback, `all[format_note=storyboard]`, is correct, and I wanted to see that was  possible, and learn more about format selector expressions.

**Comment by notevenaperson** [comment]
It's not a big deal if this isn't possible.

**Comment by bashonly** [comment]
`-f mhtml`
