### ISSUE TITLE
(2024.07.0X) --ignore-no-formats-error combined with the occurrence of no available video formats results in late crash

### ISSUE THREAD

**Issue by notevenaperson** [yt-dlp/yt-dlp#10344]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

The traceback ends in the function sanitize_extension. This makes me think it was possibly introduced by the [recent CVE fix](https://github.com/yt-dlp/yt-dlp/releases/tag/2024.07.01), version 2024.07.01 and 2024.07.02. Adding `--compat-opt allow-unsafe-ext` prevents the crash, pretty much confirming it.

The presence of `--ignore-no-formats-error` in any command line can cause this crash, though it has to be *triggered*. This crash happens if the format is missing and `--ignore-no-formats-error` was used. In effect this happens if a video is private, geoblocked, selecting (`-f`) a non-existing format, etc.

This crash doesn't appear high priority. For one it happens late. The functionality of `--ignore-no-formats-error` is not disrupted. Despite the name of the option, in previous versions where it was working it did not stop exiting with an "ERROR No video formats found!" message (and '1' exit code). --ignore-no-formats-error is "useful for extracting metadata" according to the [docs](https://github.com/yt-dlp/yt-dlp#verbosity-and-simulation-options), and in the log of this crash you'll see the internet shortcut did get created before the crash. The only apparent change is that the error message is not as pretty.

The early exit could break some functionality or prevent some late clean-up(?) steps, but I don't know.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: [--ignore-no-formats-error', '-f', '999', '--write-link', '-qv', '--ignore-config', 'k9edTqPMX_k']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.07.02 from yt-dlp/yt-dlp [93d33cb29]
[debug] Python 3.12.4 (CPython x86_64 64bit) - Linux-6.9.7-arch1-1-x86_64-with-glibc2.39 (OpenSSL 3.3.1 4 Jun 2024, glibc 2.39)
[debug] exe versions: ffmpeg 7.0.1 (setts), ffprobe 7.0.1
[debug] Optional libraries: Cryptodome-3.20.0, certifi-2024.06.02, mutagen-1.47.0, requests-2.32.3, sqlite3-3.46.0, urllib3-1.26.18, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1831 extractors
[youtube] Extracting URL: k9edTqPMX_k
[youtube] k9edTqPMX_k: Downloading webpage
[youtube] k9edTqPMX_k: Downloading ios player API JSON
[debug] Loading youtube-nsig.5352eb4f from cache
[debug] [youtube] Decrypted nsig 0oteMDBnhY-vqmPO-Jd => Dep1PhBXGq7bvQ
[debug] Loading youtube-nsig.5352eb4f from cache
[debug] [youtube] Decrypted nsig FG_7KdCixSySLOYILv4 => X2wnQQ2vbz8NtA
[youtube] k9edTqPMX_k: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
WARNING: Requested format is not available
[info] Internet shortcut (.desktop) is already present
ERROR: argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 1622, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 1778, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 1837, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 3012, in process_video_result
    self.process_info(new_info)
  File "/usr/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 179, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 3475, in process_info
    dl_filename = existing_video_file(full_filename, temp_filename)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 3367, in existing_video_file
    file = self.existing_file(itertools.chain(*zip(map(converted, filepaths), filepaths)),
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 3366, in <lambda>
    converted = lambda file: replace_extension(file, self.params.get('final_ext') or ext, ext)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/yt_dlp/utils/_utils.py", line 2097, in _change_extension
    return f'{filename}.{_UnsafeExtensionError.sanitize_extension(ext)}'
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/yt_dlp/utils/_utils.py", line 5123, in sanitize_extension
    if '/' in extension or '\\' in extension:
       ^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by bashonly** [comment]
Thanks for reporting this. Unfortunately, there isn't enough test coverage for this sector of yt-dlp core code. And our manual testing focused on ensuring files were still able to be downloaded rather than the behavior in the absence of files, so this was missed. Will be fixed by #10345
