### ISSUE TITLE
[vimeo] This request has been blocked due to its TLS fingerprint

### ISSUE THREAD

**Issue by someziggyman** [yt-dlp/yt-dlp#10351]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

anywhere

### Provide a description that is worded well enough to be understood

strange behaviour from Vimeo links today giving errors with "This request has been blocked due to its TLS fingerprint" 
most of the links fail that way. they they seem to work fine for some time, then the issue comes back. Not sure if it's for everyone like that. Decided to report just in case. Tried looking up if there's already and open issue like this - found not. Have been looking by the message from the error. 

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
./yt-dlp -vU -F "https://vimeo.com/74710268"
[debug] Command-line config: ['-vU', '-F', 'https://vimeo.com/74710268']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.07.02 from yt-dlp/yt-dlp [93d33cb29] (zip)
[debug] Python 3.12.2 (CPython arm64 64bit) - macOS-14.5-arm64-arm-64bit (OpenSSL 3.0.13 30 Jan 2024)
[debug] exe versions: phantomjs 2.1.1, rtmpdump 2.4
[debug] Optional libraries: certifi-2024.02.02, sqlite3-3.45.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Extractor Plugins: SamplePluginIE
[debug] Post-Processor Plugins: SamplePluginPP
[debug] Loaded 1934 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.07.02 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.07.02 from yt-dlp/yt-dlp)
[vimeo] Extracting URL: https://vimeo.com/74710268
[vimeo] 74710268: Downloading webpage
WARNING: [vimeo] The extractor is attempting impersonation, but no impersonate target is available; if you encounter errors, then see  https://github.com/yt-dlp/yt-dlp#impersonation  for information on installing the required dependencies
ERROR: [vimeo] 74710268: This request has been blocked due to its TLS fingerprint. Install a required impersonation dependency if possible, or else if you are okay with compromising your security/cookies, try replacing "https:" with "http:" in the input URL. If you are using a data center IP or VPN/proxy, your IP may be blocked.
  File "./yt-dlp/yt_dlp/extractor/common.py", line 740, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "./yt-dlp/yt_dlp/extractor/vimeo.py", line 871, in _real_extract
    raise ExtractorError(
```

**Comment by seproDev** [comment]
It's exactly what the error message says:
> This request has been blocked due to its TLS fingerprint. Install a required impersonation dependency if possible, or else if you are okay with compromising your security/cookies, try replacing "https:" with "http:" in the input URL. If you are using a data center IP or VPN/proxy, your IP may be blocked.


Vimeo has started blocking access based on the TLS fingerprint. They don't block 100% of the requests but also take other things in to account like IP reputation and request frequency. You will either need to use yt-dlp with curl_cffi, or alternatively, you can try the workaround mentioned in the error message.

**Comment by bashonly** [comment]
the [macos pyinstaller-bundled binary](https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp_macos) includes curl_cffi

**Comment by garthhumphreys** [comment]
After reading what @seproDev and @bashonly wrote I followed the steps in the docs and installed the `curl_cffi` dependencies, `pip install "yt-dlp[default,curl-cffi]"` – now it works. Thanks!

**Comment by highschooldropout** [comment]
@bashonly @garthhumphreys 

Can either of you help me out? I'm not super technical but I'm having the same issue described above and apparently also needing to install the proper dependencies. I'm currently on macOS.

**Comment by bashonly** [comment]
@highschooldropout The easiest way will be to install the [official yt-dlp_macos binary](https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp_macos)

To download it, run these commands from your terminal:

```bash
mkdir -p ~/.local/bin
curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp_macos -o ~/.local/bin/yt-dlp
```

Then you'll want to add this directory to your `PATH` environment variable, so that when you run `yt-dlp` in your terminal, the newly downloaded macos binary is what gets executed.

To do that, first you should figure out which shell your terminal uses by default. On newer versions of macOS, it's `zsh`. On older macOS, it's an ancient version of `bash`. Run `echo $SHELL` to determine which.

If you're using zsh, then run this command:
```zsh
echo 'export PATH="${HOME}/.local/bin:${PATH}"' >> ~/.zshrc
```

If bash, then this:
```bash
echo 'export PATH="${HOME}/.local/bin:${PATH}"' >> ~/.bash_profile
```

Make sure to copy/paste verbatim, since the quoting etc needs to be exact.

Then log out and log back in to make sure the changes take effect.

**Comment by highschooldropout** [comment]
> @highschooldropout The easiest way will be to install the [official yt-dlp_macos binary](https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp_macos)
> 
> To download it, run these commands from your terminal:
> 
> ```shell
> mkdir -p ~/.local/bin
> curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp_macos -o ~/.local/bin/yt-dlp
> ```
> 
> Then you'll want to add this directory to your `PATH` environment variable, so that when you run `yt-dlp` in your terminal, the newly downloaded macos binary is what gets executed.
> 
> To do that, first you should figure out which shell your terminal uses by default. On newer versions of macOS, it's `zsh`. On older macOS, it's an ancient version of `bash`. Run `echo $SHELL` to determine which.
> 
> If you're using zsh, then run this command:
> 
> ```shell
> echo 'export PATH="${HOME}/.local/bin:${PATH}"' >> ~/.zshrc
> ```
> 
> If bash, then this:
> 
> ```shell
> echo 'export PATH="${HOME}/.local/bin:${PATH}"' >> ~/.bash_profile
> ```
> 
> Make sure to copy/paste verbatim, since the quoting etc needs to be exact.
> 
> Then log out and log back in to make sure the changes take effect.

Thanks for this.

I did exactly as instructed, using zsh, restarted the computer but the error is persisting.

Is there a way to verify whether or not something is missing?

**Comment by bashonly** [comment]
add `-vU` to your command and copy/paste the complete verbose output here

**Comment by highschooldropout** [comment]
> add `-vU` to your command and copy/paste the complete verbose output here

`echo 'export PATH="${HOME}/.local/bin:${PATH}"' >> ~/.zshrc -vU` comes back with nothing at all.

**Comment by bashonly** [comment]
No, I meant your yt-dlp download command. Do not re-run those installation commands!

**Comment by highschooldropout** [comment]
> No, I meant your yt-dlp download command. Do not re-run those installation commands! You can break things that way.

```
[debug] Command-line config: ['https://vimeo.com/XXXXXXXXX', '-vU']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.07.09 from yt-dlp/yt-dlp [7ead7332a] (pip)
[debug] Python 3.12.4 (CPython arm64 64bit) - macOS-14.5-arm64-arm-64bit (OpenSSL 3.3.1 4 Jun 2024)
[debug] exe versions: ffmpeg 7.0.1 (setts), ffprobe 7.0.1
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.07.04, mutagen-1.47.0, requests-2.32.3, sqlite3-3.46.0, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1834 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.07.09 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.07.09 from yt-dlp/yt-dlp)
[vimeo] Extracting URL: https://vimeo.com/XXXXXXXXX
[vimeo] XXXXXXXXX: Downloading webpage
WARNING: [vimeo] The extractor is attempting impersonation, but no impersonate target is available; if you encounter errors, then see  https://github.com/yt-dlp/yt-dlp#impersonation  for information on installing the required dependencies
ERROR: [vimeo] XXXXXXXXX: This request has been blocked due to its TLS fingerprint. Install a required impersonation dependency if possible, or else if you are okay with compromising your security/cookies, try replacing "https:" with "http:" in the input URL. If you are using a data center IP or VPN/proxy, your IP may be blocked.
  File "/opt/homebrew/Cellar/yt-dlp/2024.7.9/libexec/lib/python3.12/site-packages/yt_dlp/extractor/common.py", line 740, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/yt-dlp/2024.7.9/libexec/lib/python3.12/site-packages/yt_dlp/extractor/vimeo.py", line 863, in _real_extract
    raise ExtractorError(
```

**Comment by bashonly** [comment]
Your homebrew installation is still being executed when you run `yt-dlp`, not the macos binary you downloaded. 

Something went wrong during your installation of the macos binary. To troubleshoot this, I'll need to see the output of the following commands:

```bash
ls ~/.local/bin
echo $PATH
echo $SHELL
cat ~/.zshrc
cat ~/.bash_profile
```

**Comment by highschooldropout** [comment]
1.
`yt-dlp`

2. `/Users/xxxxx/.local/bin:/Users/xxxxx/.local/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Applications/Little Snitch.app/Contents/Components`

3.
`/bin/zsh`

4.
```
export PATH="${HOME}/.local/bin:${PATH}"
export PATH="${HOME}/.local/bin:${PATH}" -vU
```

5.
`cat: /Users/xxxxx/.bash_profile: No such file or directory`

**Comment by bashonly** [comment]
OK, run this command **once** to fix your `.zshrc`/`PATH`:

```zsh
echo 'export PATH="${HOME}/.local/bin:${PATH}"' > ~/.zshrc
```

and I realize that I forgot a step, you need to run this command:

```zsh
chmod +x ~/.local/bin/yt-dlp
```

then you should be good to go

**Comment by highschooldropout** [comment]
> OK, run this command **once** to fix your `.zshrc`/`PATH`:
> 
> ```shell
> echo 'export PATH="${HOME}/.local/bin:${PATH}"' > ~/.zshrc
> ```
> 
> and I realize that I forgot a step, you need to run this command:
> 
> ```shell
> chmod +x ~/.local/bin/yt-dlp
> ```
> 
> then you should be good to go

Thank you! 🙏 It's working now.

I'm glad I didn't do something on my own because there's no way I'd have figured this out.

Appreciate your time.

**Comment by someziggyman** [comment]
@highschooldropout Thanks a lot for sharing this info. While you're here, may I also ask you a quick question. I have a custom yt-dlp build on my flash drive occasionally I'm re-assembling it  for my dad to use) So, it's a bit of a "Frankenstein" with pull requests and fixes that have been implemented in youtube-dl or here, but are not in the main brunch yet. I was trying to build my yt-dlp from source (if it's correct way to call it) but now wanted it to embed it with that curl-cffi thing. Tried to install it via brew but when I'm building my script gives an error saying "curl-cffi is not a fat binary". Looking online - it means that curl-cffi does not include both ARM and intel architectures. If you can give a hint on how to fix this or point me to the right direction on how to embed curl-cffi into yt-dlp I'll be more than grateful. Running all this on M1 Mac.

**Comment by bashonly** [comment]
@someziggyman this is what we do to produce universal2 binaries that include curl_cffi:

https://github.com/yt-dlp/yt-dlp/blob/cc1a3098c00995c6aebc2a16bd1050a66bad64db/.github/workflows/build.yml#L262-L307

**Comment by highschooldropout** [comment]
@bashonly 

Sorry to bother you again. I don't know if this is a separate issue but now I'm seeing (only on some downloads):

`[vimeo] 333026662: Got HTTP Error 403 when using impersonate target "chrome-110:windows-10". If you are using a data center IP or VPN/proxy, your IP may be blocked; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U`

**Comment by bashonly** [comment]
@highschooldropout that issue can be tracked in #10422

**Comment by ewebgh33** [comment]
**If I run pip install "yt-dlp[default,curl-cffi]" will it simply overwrite/update itself?**

I already have yt-dlp installed in `/opt/miniconda3/bin/yt-dlp`. Not sure how it got there in the first place but this is what I get when I ask which `yt-dlp`.

I don't use the MacOS Binaries, also for some reason. The exact reason, I can't recall, maybe as my OS is older (10.13.6). So I installed via terminal in the first place. Current version 2024.07.09.

Or, as I am not using the binaries method, do I need to manually install curl-cffi with pip first, then re-install yt-dlp with the above command?

Thanks

**Comment by bashonly** [comment]
@ewebgh33 curl-cffi will likely not work on macOS versions < 11

**Comment by ewebgh33** [comment]
@bashonly thanks for the tip. That sucks though. :( Not in a position to update at the moment. Will have to figure something else out I guess. There are a couple of websites that will still rip a vimeo link in HD but they're dwindling...

**Comment by bashonly** [comment]
@ewebgh33 as a workaround you can try changing `https:` to `http:` in the url you pass to yt-dlp

**Comment by ewebgh33** [comment]
Yes I have done that too, I was going to post that as a separate issue, that all https seems to not work any more.
I download a couple of things from vimeo each day, and VPN always fails, so I started using non-VPN (not sensitive material, just don't like being tracked). But they must have figured out my IP is pulling stuff not via the UI and added me to their large block list. :(
