### ISSUE TITLE
Unable to install curl_cffi

### ISSUE THREAD

**Issue by levis-ineptias** [yt-dlp/yt-dlp#10356]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I am trying to install `curl_cffi` in order to get around Vimeo's new TLS fingerprinting anti-bot protection. I have run the command `pipx install 'yt-dlp[default,curl_cffi]' --force'`, which gives the output:

```
Installing to existing venv 'yt-dlp'
⚠️  Note: yt-dlp was already on your PATH at /opt/homebrew/bin/yt-dlp
  installed package yt-dlp 2024.7.2, installed using Python 3.12.4
  These apps are now globally available
    - yt-dlp
  These manual pages are now globally available
    - man1/yt-dlp.1
⚠️  Note: '/Users/username-hidden/.local/bin' is not on your PATH environment variable. These apps will not be globally accessible until your PATH is updated. Run `pipx ensurepath` to automatically add it,
    or manually modify your PATH in your shell's config file (e.g. ~/.bashrc).
done! ✨ 🌟 ✨
```

From this output, I understand that `curl_cffi` would have been installed. However, running `yt-dlp --list-impersonate-targets -vU` does not show it.

I intend to use `--impersonate chrome` but I am stuck at `curl_cffi` installation. Any help would be **greatly** appreciated. Thank you.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['--list-impersonate-targets', '-vU']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.07.02 from yt-dlp/yt-dlp [93d33cb29] (pip)
[debug] Python 3.12.4 (CPython arm64 64bit) - macOS-14.5-arm64-arm-64bit (OpenSSL 3.3.1 4 Jun 2024)
[debug] exe versions: ffmpeg 7.0.1 (setts), ffprobe 7.0.1
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.06.02, mutagen-1.47.0, requests-2.32.3, sqlite3-3.46.0, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1831 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.07.02 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.07.02 from yt-dlp/yt-dlp)
[info] Available impersonate targets
Client   OS   Source
---------------------------------------
Chrome   -    curl_cffi (not available)
Edge     -    curl_cffi (not available)
Safari   -    curl_cffi (not available)
```

**Comment by bashonly** [comment]
> ⚠️  Note: yt-dlp was already on your PATH at /opt/homebrew/bin/yt-dlp
> ⚠️  Note: '/Users/username-hidden/.local/bin' is not on your PATH environment variable. These apps will not be globally accessible until your PATH is updated. Run `pipx ensurepath` to automatically add it, or manually modify your PATH in your shell's config file (e.g. ~/.bashrc).

Are you sure that when you run `yt-dlp` the pipx installation is being called instead of the homebrew installation? Did you try running `pipx ensurepath` like the note says?

Another alternative is the [macos pyinstaller-bundled binary](https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp_macos), which includes curl_cffi

**Comment by levis-ineptias** [comment]
Thanks for your response, @bashonly. How do I check which installation is being called when I run `yt-dlp`?

Yes, I did run `pipx ensurepath`, and it returned the following output.

```
/Users/username-hidden/.local/bin has been been added to PATH, but you need to open a new terminal or re-login for this PATH change to take effect. Alternatively, you can source your shell's config file
    with e.g. 'source ~/.bashrc'.

You will need to open a new terminal or re-login for the PATH changes to take effect. Alternatively, you can source your shell's config file with e.g. 'source ~/.bashrc'.
```

I ran `yt-dlp --list-impersonate-targets -vU` in a new Terminal window thereafter but it still returned the same result.

It might be that Homebrew's installation in being called when I run `yt-dlp`. Is there a way I can check? Should I uninstall Homebrew's version of `yt-dlp` and try running the command?

Thank you for your help.

**Comment by bashonly** [comment]
> How do I check which installation is being called when I run `yt-dlp`?

If you run `which yt-dlp` should show the path of the executable that's called when you run `yt-dlp`.  (If `which` isn't available on your system, try `command -v yt-dlp`)

> Should I uninstall Homebrew's version of `yt-dlp` and try running the command?

If you can't get the PATH thing figured out, this would be a surefire way of solving it

**Comment by levis-ineptias** [comment]
Thank you once again for the reply, @bashonly.

Yes, Homebrew's version of yt-dlp is being called when I run `yt-dlp`. `which yt-dlp` gives me:

```
/opt/homebrew/bin/yt-dlp
```

Can I change `yt-dlp` to run from pipx instead of Homebrew? I am not sure how to do this (I guess it requires mentioning the absolute path of pipx's version of yt-dlp when calling `yt-dlp`, but I don't know how to find this path.) Could you please help me out?

Thank you!

**Comment by bashonly** [comment]
> Can I change yt-dlp to run from pipx instead of Homebrew? I am not sure how to do this (I guess it requires mentioning the absolute path of pipx's version of yt-dlp when calling yt-dlp, but I don't know how to find this path.) Could you please help me out?

If `pipx ensurepath` isn't working, then you'll have to manually modify your `PATH` environment variable.

First, you need to figure out which shell your terminal uses by default. On newer versions of macOS, it's `zsh`. On older macOS, it's an ancient version of `bash`. Run `echo $SHELL` to determine which.

If you're using zsh, then run this command:
```zsh
echo 'export PATH="${HOME}/.local/bin:${PATH}"' >> ~/.zshrc
```

If bash, then this:
```bash
echo 'export PATH="${HOME}/.local/bin:${PATH}"' >> ~/.bash_profile
```

Make sure to copy/paste verbatim, since the quoting etc needs to be exact.

Then log out and log back in to make sure the changes take effect.

**Comment by levis-ineptias** [comment]
This did it! Thank you very much, @bashonly!

I am using Z shell, so copying and pasting the Z shell command did it for me. 

Could you please explain what the command is doing? I understand that the command is modifying the `PATH` variable in the Z shell source file. You are adding `/Users/username-hidden/.local/bin` to `PATH`. Is that right?

Is this (`/Users/username-hidden/.local/bin`) where `pipx`'s `yt-dlp` resides? I had a look inside the directory (`ls`) and it contains `yt-dlp`.

Thank you for your help! 😊

**Comment by levis-ineptias** [comment]
Understood, @bashonly. Thank you very much. 🙂
