### ISSUE TITLE
Bug Report: Unable to Extract Video ID from France.tv URL

### ISSUE THREAD

**Issue by yannismxflux** [yt-dlp/yt-dlp#10352]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

France

### Provide a description that is worded well enough to be understood

While attempting to download a video from France.tv using yt-dlp, the extraction process fails with an error message indicating that the video ID cannot be extracted.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp -vU "https://www.france.tv/france-o/archipels/132249-mon-ancetre-l-esclave.html"
[debug] Command-line config: ['-vU', 'https://www.france.tv/france-o/archipels/132249-mon-ancetre-l-esclave.html']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.07.03.232825 from yt-dlp/yt-dlp-nightly-builds [6075a029d] (pip)
[debug] Python 3.11.9 (CPython arm64 64bit) - macOS-14.5-arm64-arm-64bit (OpenSSL 3.3.1 4 Jun 2024)
[debug] exe versions: ffmpeg 7.0.1 (setts), ffprobe 7.0.1
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.07.04, mutagen-1.47.0, requests-2.32.3, sqlite3-3.46.0, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1831 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.07.03.232825 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.07.03.232825 from yt-dlp/yt-dlp-nightly-builds)
[FranceTVSite] Extracting URL: https://www.france.tv/france-o/archipels/132249-mon-ancetre-l-esclave.html
[FranceTVSite] 132249-mon-ancetre-l-esclave: Downloading webpage
ERROR: [FranceTVSite] 132249-mon-ancetre-l-esclave: Unable to extract video ID; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/Users/yannismemmess/miniforge3/envs/ftv-emission/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 740, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yannismemmess/miniforge3/envs/ftv-emission/lib/python3.11/site-packages/yt_dlp/extractor/francetv.py", line 349, in _real_extract
    video_id = self._html_search_regex(
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yannismemmess/miniforge3/envs/ftv-emission/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 1369, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yannismemmess/miniforge3/envs/ftv-emission/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 1333, in _search_regex
    raise RegexNotFoundError(f'Unable to extract {_name}')
```

**Comment by seproDev** [comment]
Does the video play back in your browser? For me, it says, "La vidéo n'est pas disponible" (Video is not available)

**Comment by yannismxflux** [comment]
Yes, by using an account, I am able to watch the video in the browser. I found a temporary solution by parsing the page and using BeautifulSoup to extract a valid URL to download the video. Here is the code:

```python
import requests
from bs4 import BeautifulSoup
import yt_dlp
import re

def get_video_url(page_url):
    response = requests.get(page_url)
    response.raise_for_status()  # Check if the request was successful

    soup = BeautifulSoup(response.text, 'html.parser')
    
    # Find the script tag that contains the video data
    script_tag = soup.find('script', string=lambda x: x and 'FTVPlayerVideos' in x)
    if not script_tag:
        raise ValueError("Could not find the video data in the page.")

    # Extract the video URL
    script_content = script_tag.string
    video_url = None
    
    # Look for the video URL pattern in the script content
    match = re.search(r'"originUrl"\s*:\s*"([^"]+)"', script_content)
    if match:
        video_url = match.group(1).replace("\\/", "/")
    
    if not video_url:
        raise ValueError("Could not find the video URL in the script content.")

    return video_url

def list_formats(video_url):
    ydl_opts = {
        'listformats': True
    }

    with yt_dlp.YoutubeDL(ydl_opts) as ydl:
        ydl.extract_info(video_url, download=False)

def download_video(video_url, format_code):
    ydl_opts = {
        'format': format_code,
        'outtmpl': '%(title)s.%(ext)s'
    }

    with yt_dlp.YoutubeDL(ydl_opts) as ydl:
        ydl.download([video_url])

if __name__ == "__main__":
    page_url = 'https://www.france.tv/slash/deter/saison-1/6191687-si-pres-du-but.html'
    video_url = get_video_url(page_url)
    full_video_url = 'https://www.france.tv' + video_url  # Ensure full URL if needed
    full_video_url = full_video_url.replace('\\/', '/')  # Replace any remaining escape characters

    print(f"Listing formats for video: {full_video_url}")
    list_formats(full_video_url)

    # Replace 'best' with the desired format code from the list of formats
    format_code = input("Enter the format code to download: ")
    print(f"Downloading video from: {full_video_url} in format {format_code}")
    download_video(full_video_url, format_code)
```

### Explanation:

1. **Importing Libraries**: The code starts by importing necessary libraries: `requests` for handling HTTP requests, `BeautifulSoup` from `bs4` for parsing HTML, `yt_dlp` for handling video extraction and downloading, and `re` for regular expression operations.

2. **Function `get_video_url`**: 
    - This function takes a `page_url` as input.
    - It sends an HTTP GET request to the URL and checks if the request was successful.
    - It parses the HTML content of the page to find a specific `<script>` tag containing the video data.
    - It extracts the video URL from the script content using a regular expression.

3. **Function `list_formats`**: 
    - This function takes the `video_url` as input and uses `yt_dlp` to list all available video formats without downloading the video.

4. **Function `download_video`**: 
    - This function takes the `video_url` and a `format_code` as inputs.
    - It uses `yt_dlp` to download the video in the specified format.

5. **Main Execution Block**: 
    - The script specifies a `page_url` of a video.
    - It retrieves the video URL by calling `get_video_url`.
    - It constructs the full video URL if necessary.
    - It lists available formats for the video.
    - It prompts the user to input the desired format code and then downloads the video in that format.

**Comment by seproDev** [comment]
Can you try yt-dlp with `--cookies-from-browser`/`--cookies`?

**Comment by yannismxflux** [comment]
Sorry, I'm a dumbass. Indeed, the link wasn't working anymore because the video was removed. Again, sorry for the wasted time.

I tested on a list of links that I had collected in the previous weeks, and indeed the problem does not come from yt-dlp.
