### ISSUE TITLE
Failed to resolve 'i.ytimg.com' ([Errno -3] 

### ISSUE THREAD

**Issue by AbhishekDas2000** [yt-dlp/yt-dlp#10357]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Provide a description that is worded well enough to be understood

Getting Unable to download video thumbnail 39: <urllib3.connection.HTTPSConnection object at 0x7b7f759ef440>: Failed to resolve 'i.ytimg.com' ([Errno -3] Temporary failure in name resolution)
Even though I have a fast internet connection

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.youtube.com/watch?v=c7VGjq9yp8g']
[debug] System config "/etc/yt-dlp.conf": ['-o', '%(title)s.%(ext)s', '-S', 'res:1080', '--embed-thumbnail', '--embed-metadata', '--embed-info-json', '--embed-subs', '--write-auto-subs', '--compat-options', 'no-keep-subs', '--sub-langs', 'en', '--embed-chapters', '--merge-output-format', 'mkv']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.07.02 from yt-dlp/yt-dlp [93d33cb29] (pip)
[debug] Compatibility options: no-keep-subs
[debug] Python 3.12.3 (CPython x86_64 64bit) - Linux-6.8.0-36-generic-x86_64-with-glibc2.39 (OpenSSL 3.0.13 30 Jan 2024, glibc 2.39)
[debug] exe versions: ffmpeg 6.1.1 (setts), ffprobe 6.1.1
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.07.04, mutagen-1.47.0, requests-2.32.3, sqlite3-3.45.1, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1831 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.07.02 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.07.02 from yt-dlp/yt-dlp)
[youtube] Extracting URL: https://www.youtube.com/watch?v=c7VGjq9yp8g
[youtube] c7VGjq9yp8g: Downloading webpage
[youtube] c7VGjq9yp8g: Downloading ios player API JSON
[debug] [youtube] Extracting signature function js_5352eb4f_105
[debug] Loading youtube-sigfuncs.js_5352eb4f_105 from cache
[debug] Loading youtube-nsig.5352eb4f from cache
[debug] [youtube] Decrypted nsig 0q3xGkHHDWhLmnmKQZy => SA-9wbjNzZdUpA
[debug] Loading youtube-nsig.5352eb4f from cache
[debug] [youtube] Decrypted nsig prJ_B-LfK3rNoJQ-cH_ => snrMYq0jNrhykA
[debug] [youtube] Extracting signature function js_5352eb4f_101
[debug] Loading youtube-sigfuncs.js_5352eb4f_101 from cache
[youtube] c7VGjq9yp8g: Downloading m3u8 information
[info] c7VGjq9yp8g: Downloading subtitles: en
[debug] Sort order given by user: res:1080
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, res:1080(1080.0), quality, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] c7VGjq9yp8g: Downloading 1 format(s): 248+251
Deleting existing file Hacking Behringers Ultranet for a FPGA-based DIY-Audiomixer.en.vtt
[info] Writing video subtitles to: Hacking Behringers Ultranet for a FPGA-based DIY-Audiomixer.en.vtt
[debug] Invoking http downloader on "https://www.youtube.com/api/timedtext?v=c7VGjq9yp8g&ei=dG2HZtfjBtWC9fwP4re2iAI&caps=asr&opi=112496729&xoaf=5&hl=en&ip=0.0.0.0&ipbits=0&expire=1720176612&sparams=ip%2Cipbits%2Cexpire%2Cv%2Cei%2Ccaps%2Copi%2Cxoaf&signature=24A297B06A12E79C61695CE2702319D57BF2460D.4470FA7762B3B0BE1BB76871884E5C897018D49B&key=yt8&kind=asr&lang=en&fmt=vtt"
[download] Destination: Hacking Behringers Ultranet for a FPGA-based DIY-Audiomixer.en.vtt
[download] 100% of  142.46KiB in 00:00:00 at 1.12MiB/s
[info] Downloading video thumbnail 41 ...
WARNING: Unable to download video thumbnail 41: <urllib3.connection.HTTPSConnection object at 0x796b7467b140>: Failed to resolve 'i.ytimg.com' ([Errno -3] Temporary failure in name resolution)
[info] Downloading video thumbnail 40 ...
```

**Comment by AbhishekDas2000** [comment]
This started happening from last night. Otherwise it worked fine

**Comment by bashonly** [comment]
Do you use any sort of network firewall / pihole / adguard / etc?

**Comment by AbhishekDas2000** [comment]
> Do you use any sort of network firewall / pihole / adguard / etc?

I use Cloudfare WARP but I turn it off specifically to use yt-dlp.

**Comment by bashonly** [comment]
what happens when your run `ping -c1 i.ytimg.com`

**Comment by AbhishekDas2000** [comment]
Strangely, the issue resolved itself. Closing it. Thanks for looking into it @bashonly
