### ISSUE TITLE
[Youtube] _UnsafeExtensionError when downloading `--sub-langs de` subtitles for json3, srv1, srv2, srv3

### ISSUE THREAD

**Issue by klaufir216** [yt-dlp/yt-dlp#10360]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Provide a description that is worded well enough to be understood

Reproduce with this command:

```
yt-dlp -vU --skip-download --write-subs --sub-langs de --sub-format json3 https://www.youtube.com/watch?v=b047YVrWOlg
```

Unable to download subtitles due to _UnsafeExtensionError.

The output is for `--sub-format json3`, but there is a similar error for other types of extensions as well. All of the following give the same error:

```
--sub-format json3
--sub-format srv1
--sub-format srv2
--sub-format srv3
--sub-format ttml
```

Currenlty (master@2024.07.03.223542), the only subtitle download that works for `--sub-langs de` is `--sub-format vtt`

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--skip-download', '--write-subs', '--sub-langs', 'de', '--sub-format', 'json3', 'https://www.youtube.com/watch?v=b047YVrWOlg']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version master@2024.07.03.223542 from yt-dlp/yt-dlp-master-builds [6075a029d] (zip)
[debug] Python 3.11.2 (CPython x86_64 64bit) - Linux-6.1.0-18-cloud-amd64-x86_64-with-glibc2.36 (OpenSSL 3.0.13 30 Jan 2024, glibc 2.36)
[debug] exe versions: none
[debug] Optional libraries: certifi-2022.09.24, requests-2.28.1, sqlite3-3.40.1, urllib3-1.26.12
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Loaded 1831 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-master-builds/releases/latest
Latest version: master@2024.07.03.223542 from yt-dlp/yt-dlp-master-builds
yt-dlp is up to date (master@2024.07.03.223542 from yt-dlp/yt-dlp-master-builds)
[youtube] Extracting URL: https://www.youtube.com/watch?v=b047YVrWOlg
[youtube] b047YVrWOlg: Downloading webpage
[youtube] b047YVrWOlg: Downloading ios player API JSON
[youtube] b047YVrWOlg: Downloading player 5352eb4f
[debug] Saving youtube-nsig.5352eb4f to cache
[debug] [youtube] Decrypted nsig wQYLiJBv3JOuC-EERaz => n93HflL2Jf7h1w
[youtube] b047YVrWOlg: Downloading m3u8 information
[info] b047YVrWOlg: Downloading subtitles: de
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
WARNING: ffmpeg not found. The downloaded format may not be the best available. Installing ffmpeg is strongly recommended: https://github.com/yt-dlp/yt-dlp#dependencies
[debug] Default format spec: best/bestvideo+bestaudio
[info] b047YVrWOlg: Downloading 1 format(s): 18
ERROR: The extracted extension ('de.json3') is unusual and will be skipped for safety reasons. If you believe this is an error, please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "/home/admin/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 179, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3267, in process_info
    sub_files = self._write_subtitles(info_dict, temp_filename)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 4324, in _write_subtitles
    sub_filename = subtitles_filename(filename, sub_lang, sub_format, info_dict.get('ext'))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/bin/yt-dlp/yt_dlp/utils/_utils.py", line 1262, in subtitles_filename
  File "/home/admin/bin/yt-dlp/yt_dlp/utils/_utils.py", line 2097, in _change_extension
  File "/home/admin/bin/yt-dlp/yt_dlp/utils/_utils.py", line 5134, in sanitize_extension
yt_dlp.utils._UnsafeExtensionError: unsafe file extension: 'de.json3'
```

**Comment by bashonly** [comment]
Regression in 5ce582448ececb8d9c30c8c31f58330090ced03a

ttml is not impacted. Only json3, srv1, srv2, srv3

**Comment by bashonly** [comment]
update to latest master: `yt-dlp --update-to master@latest`

**Comment by klaufir216** [comment]
Thanks a lot! Working now.
