### ISSUE TITLE
Using bestvideo with bestauido.Havinng problem with ffmeg

### ISSUE THREAD

**Issue by Tboiii-123** [yt-dlp/yt-dlp#10367]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

i have an issue, using only best gives me low quality video and audio but when using bestvideo gives me good quality video but without an audio
and when i combined bestvideo +bestaudio am having an error talking about ffmpeg path

ERROR: You have requested merging of multiple formats but ffmpeg is not installed. Aborting due to --abort-on-error
Failed to download https://youtube.com/shorts/nAD-1ffz6yk?si=gq9e4t2BiO-p9uXl: ERROR: You have requested merging of multiple formats but ffmpeg is not installed. Aborting due to --abort-on-error
PS C:\Users\HP\Desktop\Programming\Python_programming\Django Tutorial\Youtube downloader\youtube_d>
can they be away to use best with high quality video
Please how can i reslove it i wanna use it for my django project

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.07.02 from yt-dlp/yt-dlp [93d33cb29] (pip)
[debug] Python 3.9.6 (CPython AMD64 64bit) - Windows-10-10.0.15063-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2022.09.24, mutagen-1.47.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1831 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.07.02 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.07.02 from yt-dlp/yt-dlp)
```

**Comment by seproDev** [comment]
> [debug] exe versions: none

You don't have ffmpeg installed. Install it by either placing the executable next to `yt-dlp.exe` or in your `PATH`.

**Comment by Tboiii-123** [comment]
Alright,thanks
is  ffmpeg like a package in python as well??

**Comment by seproDev** [comment]
No. It is a program that yt-dlp needs to merge separate video and audio tracks.

**Comment by rdamas** [comment]
yt-dlp even offers builds for ffmpeg: https://github.com/yt-dlp/FFmpeg-Builds

**Comment by dirkf** [comment]
>I've looked through the README

[Readme>Installation>Dependencies>Strongly Recommended](https://github.com/yt-dlp/yt-dlp#user-content-strongly-recommended) (ahem).
