### ISSUE TITLE
Inconsistent file format, either: mp4 or m4v.

### ISSUE THREAD

**Issue by gphg** [yt-dlp/yt-dlp#10373]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Downloaded video file format is not consistent.

I had a download session by passing a channel or playlist contains several video that normally get downloaded into multiple files. It not from YouTube and I won't tell unless asked to.

The download session has ended, but not all video are get downloaded due error eg timeout or too many requests or networking issue or broken. Downloaded video files are saved as .mp4 format.

There are many videos and it bother me to collect errors so I simply rerun the previous download: another download session. Hopefully the downloaded file get skipped and unfinished video continues to be downloaded.

## Expectations

Unfinished download get downloaded in same file format: mp4.

## Problems

Another download session from same input like download in different format: m4v. This causes already downloaded video get downloaded again (duplicate), but in m4v instead mp4.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU']
[debug] Encodings: locale utf-8, fs utf-8, pref utf-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.07.02 from yt-dlp/yt-dlp [93d33cb29] (pip)
[debug] Python 3.11.9 (CPython aarch64 64bit) - Linux-5.15.123-android13-8-00834-gccec15a1eea3-aarch64-with-libc (OpenSSL 3.2.1 30 Jan 2024, libc)
[debug] exe versions: ffmpeg 6.1.1 (setts), ffprobe 6.1.1
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.06.02, mutagen-1.47.0, requests-2.32.3, sqlite3-3.46.0, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1831 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.07.02 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.07.02 from yt-dlp/yt-dl
```

**Comment by bashonly** [comment]
share complete verbose output demonstrating the issue

**Comment by gphg** [comment]
> share complete verbose output demonstrating the issue

Warning NSFW.
```
[debug] Command-line config: ['-vU', 'https://www.iwara.tv/profile/ngon']
[debug] Encodings: locale utf-8, fs utf-8, pref utf-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.07.02 from yt-dlp/yt-dlp [93d33cb29] (pip)
[debug] Python 3.11.9 (CPython aarch64 64bit) - Linux-5.15.123-android13-8-00834-gccec15a1eea3-aarch64-with-libc (OpenSSL 3.2.1 30 Jan 2024, libc)
[debug] exe versions: ffmpeg 6.1.1 (setts), ffprobe 6.1.1
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.06.02, mutagen-1.47.0, requests-2.32.3, sqlite3-3.46.0, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1831 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.07.02 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.07.02 from yt-dlp/yt-dlp)
[iwara:user] Extracting URL: https://www.iwara.tv/profile/ngon
[iwara:user] ngon: Requesting user info
[download] Downloading playlist: Ngon
[iwara:user] ngon: Downloading page 0
[iwara:user] ngon: Downloading page 1
[iwara:user] Playlist Ngon: Downloading 51 items of 51
[download] Downloading item 1 of 51
[iwara] Extracting URL: https://iwara.tv/video/pd1mO2STcrpvsi
[iwara] pd1mO2STcrpvsi: Downloading JSON metadata
[iwara] pd1mO2STcrpvsi: Downloading JSON metadata
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] pd1mO2STcrpvsi: Downloading 1 format(s): Source
[debug] Invoking http downloader on "https://kafka.iwara.tv/view?filename=fdebbab8-4196-4a1e-897f-90b11c6bf04b_Source.mp4&path=2024%2F06%2F26&expires=1720323727&hash=a0bca23017bd9ae5486cc1833d01ba8b4c856df049e09253465771aa01f31220"
[download] Destination: アスナ＆カリンでうさのこのこのここしたんたん  [pd1mO2STcrpvsi].mp4
[download]  16.6% of   71.54MiB at    1.11MiB/s ETA 00:53^C
ERROR: Interrupted by user
```
I had to interrupt it because I don't want to download again and wasted my internet data plan.

**Comment by bashonly** [comment]
can you share the link of a particular video that was duplicated in both m4v and mp4

**Comment by gphg** [comment]
> can you share the link of a particular video that was duplicated in both m4v and mp4

I'm sorry I can't recall it. But it can be reproduced:

1. Download that link until finished or try to interrupt after downloaded several video (mine is more than five)
2. Simulate an unfinished download by delete downloaded video or two
3. Complete the download as designed:
  * Download again with same command and arguments 
  * Execute on same directory as previous one, this will continue unfinished (not 100% download video) and not downloaded one

This is random, rarely download as m4v.

**Comment by bashonly** [comment]
Closing as incomplete; a specific reproducible example is needed, and this issue can be re-opened if one is provided. Developers can't be expected to download GBs of content in the hopes that the issue may randomly present itself.
