### ISSUE TITLE
[twitch] strange behavior of ad segments during live streams, not sure if player or yt-dlp issue

### ISSUE THREAD

**Issue by hadu-boired** [yt-dlp/yt-dlp#10378]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

on embedded yt-dlp for mpc-hc - live streams just freeze during every ad segment, resumes no problem when its over. if i reload the stream at this point, the ad break screen comes up and continues to play at the appropriate time. 

only started after i updated to latest release, not ideal of course since it looks like the stream is dead. maybe a relevant config in the client/extractor?

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
This seems more like a change in ffmpeg behavior than yt-dlp
