### ISSUE TITLE
Consider to make more simple API for extracting comments into separate human readable json file

### ISSUE THREAD

**Issue by AntonSamokat** [yt-dlp/yt-dlp#10384]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

As of now, to extract comments into separate json file need to use quite long complicated command like:

```
yt-dlp --write-comments --print-to-file "after_filter:%(comments)j" "comments.json" --parse-meta "video::(?P<comments>)" -- VIDEO_URL_OR_ID
```

To read generated comments, `comments.json` file needs to be transformed to human readable format with the command like:
```
cat comments.json | jq | less
```
or converted, for example, to HTML format.

As a result, current API for extracting and reading comments is quite complicated. It will be good to make it more simple, more user friendly.

For example, probably need to add some new parameter that will cover all this cases: to extract comments into some separate human readable file. Now `comments.json` file is not human readable because it:
- Does not have formatting (it all in one line)
- Contains encoded not readable non ASCII characters.

Please, consider to make such API enhancement.

Related request:
- [\[Youtube\] Add extra option(s) so that --write-comments only downloads the top few comments, and saves to a separate file · Issue #5466 · yt-dlp/yt-dlp](https://github.com/yt-dlp/yt-dlp/issues/5466)
- [Ability to write comments in HTML format · Issue #9040 · yt-dlp/yt-dlp](https://github.com/yt-dlp/yt-dlp/issues/9040)
- [download comments into separate comments.json file · Issue #2372 · yt-dlp/yt-dlp](https://github.com/yt-dlp/yt-dlp/issues/2372)
- [Consider to make default sorting for comments youtube extractor by "top", not by "new" as default in YouTube UI · Issue #10381 · yt-dlp/yt-dlp](https://github.com/yt-dlp/yt-dlp/issues/10381)

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
> To read generated comments, comments.json file needs to be transformed to human readable format with the command like:

You can print "human-readable" JSON directly from yt-dlp by adding a `#` before the `j`, e.g. 
```
--print-to-file "after_filter:%(comments)#j"
```

> As a result, current API for extracting and reading comments is quite complicated.

Not really. The `--print-to-file` arg above is all you need if you want comments as pretty-printed JSON in a separate JSON file. Sure, it gets slightly complicated if you want to remove the comments from the primary infojson file. But this is to be expected: the more specific your needs are, the more complex your configuration will become. yt-dlp already has these capabilities.

> or converted, for example, to HTML format.

This is out-of-scope for yt-dlp. There are [external scripts](https://gist.github.com/pukkandan/ee737fec64822f2552caf3ca4cbf5db7) that can do this for you.

**Comment by AntonSamokat** [comment]
@bashonly 

> You can print "human-readable" JSON directly from yt-dlp by adding a # before the j
`#` gives better result than "one-line" string but still it is not "human-readable" since it is contains encoded comments like:

```
[
    {
        "id": "UgywbYAO72WyzfoYhPd4AaABAg",
        "parent": "root",
        "text": "\u0412 \u0441\u043e\u0432\u0440\...
    }
]
```
If comments are written to `info.json` then they are in normal text (decoded) but in one-line.

Let's will be call a json file as "human readable" if it meets both conditions:
- Have pretty json formatting (not in one-line)
- Contains decoded (readable) non-ASCII characters.

In this sense now neither `info.json` and `comments.json` created based on `"after_filter:%(comments)#j"` are "human-readable".

Also using `"after_filter:%(comments)#j"` behaves differently than writing comments to `info.json`. Consider case when you want to update all comments for all specified videos. When writing to `info.json` this case is working normally. All `info.json` files for all the videos will be updated (re-written). But when using `"after_filter:%(comments)#j"` re-downloaded comments will be appended to previous ones.
To update them need to specify command for explicit removal of previous files like this:

```
yt-dlp test:youtube --skip-download --get-comments --exec pre_process:"del %(id)s.comments.json" --print-to-file "%(comments)j" "%(id)s.comments.json" --exec "type %(id)s.comments.json"
```
Found this here: [download comments into separate comments.json file · Issue #2372 · yt-dlp/yt-dlp](https://github.com/yt-dlp/yt-dlp/issues/2372#issuecomment-1019573851)

But this command gives error if `comments.json` file is not exist (for case when comments are downloading the first time)

---

Question:
What command now I can use to re-download human-readable comments that is:
- Placed in separate file
- Will not be duplicated in `info.json` file
? 

As I understand needed: 1) somehow to silence error `comments.json` does not exist when there is attempt to delete it for re-downloading comments, 2) somehow to post-process `comments.json` that it will be truly "human-readable" (to decode them with `jq`). Could you help to come up with command for this? 

> But this is to be expected: the more specific your needs are, the more complex your configuration will become.
I think this `get comments` use case is very general for `yt-dlp` like `get video` or `get video description` use cases. This is not some "specific needs".

Also it will be good to consider option for getting only comments (without another video metadata) because now if --write-comments is specified `info.json` is also created as if `--write-info-json` option is also specified. (Although there is some difference in `info.json` result files when `--write-info-json`  option is specified explicitly.) 

Based on all described here as I see API for getting comments now is not simple at all.

**Comment by bashonly** [comment]
yt-dlp is primarily a media downloader, not a metadata downloader. Comprehensive metadata/comments extraction is a bonus feature. A feature such as converting comments to HTML is out-of-scope for this project. There's not much more to say about this.
