### ISSUE TITLE
Consider to make default sorting for comments youtube extractor by "top", not by "new" as default in YouTube UI

### ISSUE THREAD

**Issue by AntonSamokat** [yt-dlp/yt-dlp#10381]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

By default YouTube shows top comments for a video first. This makes sense because in general more upvoted top comments more useful. Now by default comments are extracted for YouTube based on `new` algorithm. 

> comment_sort: top or new (default) - choose comment sorting mode (on YouTube's side)
https://github.com/yt-dlp/yt-dlp#youtube

Now to get comments based on `top` sorting order needs to use the following param:
```
yt-dlp --skip-download --write-comments --extractor-args "youtube:comment_sort=top" -- VIDEO_URL_OR_ID
```
Please, consider to make `top` sorting algorithm as default  for extraction comments.

---

Code with current version of this algorithm: [yt-dlp/yt_dlp/extractor/youtube.py at master · yt-dlp/yt-dlp](https://github.com/yt-dlp/yt-dlp/blob/master/yt_dlp/extractor/youtube.py)

```python
  if expected_comment_count is not None:
      tracker['est_total'] = expected_comment_count
      self.to_screen(f'Downloading ~{expected_comment_count} comments')
  comment_sort_index = int(get_single_config_arg('comment_sort') != 'top')  # 1 = new, 0 = top

  
 sort_text = str_or_none(sort_menu_item.get('title'))
  if not sort_text:
      sort_text = 'top comments' if comment_sort_index == 0 else 'newest first'
  self.to_screen(f'Sorting comments by {sort_text.lower()}')

  
  if expected_comment_count is not None:
      tracker['est_total'] = expected_comment_count
      self.to_screen(f'Downloading ~{expected_comment_count} comments')
  comment_sort_index = int(get_single_config_arg('comment_sort') != 'top')  # 1 = new, 0 = top

  sort_menu_item = try_get(
      comments_header_renderer,
      lambda x: x['sortMenu']['sortFilterSubMenuRenderer']['subMenuItems'][comment_sort_index], dict) or {}
  sort_continuation_ep = sort_menu_item.get('serviceEndpoint') or {}

  _continuation = self._extract_continuation_ep_data(sort_continuation_ep) or self._extract_continuation(sort_menu_item)
  if not _continuation:
      continue

  sort_text = str_or_none(sort_menu_item.get('title'))
  if not sort_text:
      sort_text = 'top comments' if comment_sort_index == 0 else 'newest first'
  self.to_screen(f'Sorting comments by {sort_text.lower()}')
  break
```

Related closed request:
- [\[Youtube\] Add extra option(s) so that --write-comments only downloads the top few comments, and saves to a separate file · Issue #5466 · yt-dlp/yt-dlp](https://github.com/yt-dlp/yt-dlp/issues/5466)
- [download comments into separate comments.json file · Issue #2372 · yt-dlp/yt-dlp](https://github.com/yt-dlp/yt-dlp/issues/2372)

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
There may be scripts or other tools depending on the existing behavior.

If you don't want to specify `--extractor-args "youtube:comment_sort=top"` every time, you can add it to your config file.

**Comment by AntonSamokat** [comment]
@bashonly I understand that this changes actually will change "backwards compatibility". But I cannot imagine who and why can depend on the current behavior. Probably only applications that use `yt-dlp` to extract comments in the current format and then make resorting on their client side with their own based on the same "top" algorithm to show them to the user in usable way. And if they get already sorted based on "top" algorithm comments they logic must not be broken. Let the comments will be sorted the second time. Do we really need to support such backwards compatibility?

OK, imagine that we have to support it.

Then two problems need to be solved.

1. User must know that when he is extracting the comments he will probably get not actually he wanted to get. I mean that the user even do not knew that comments is extracting based on "new" not user friendly algorithm, not based on default in YouTube GUI "top" algorithm.

2. When user will know this (like me) he probably already have downloaded library with videos and comments. How comes to the question: how this comments can be resorted based on "top" "human-readable" algorithm? Do all comments must be re-downloaded? Or required reinventing the wheel with writing user own sorting algorithm to resort all already downloaded files with comments?

With re-downloading comments there are some complications as I described in related request: [Consider to make more simple API for extracting comments into separate human readable json file #10384](https://github.com/yt-dlp/yt-dlp/issues/10384#issuecomment-2213602906)
Reinventing the wheel is not good solution either.
To prevent the similar user problems solution must be found on step 1.

As of now, in `yt-dlp --help` nothing mentioned about comments sorting order:

>     --write-comments                Retrieve video comments to be placed in the
>                                     infojson. The comments are fetched even
>                                     without this option if the extraction is
>                                     known to be quick (Alias: --get-comments)

I think that "top" and "new" modes as described in [readme](https://github.com/yt-dlp/yt-dlp?tab=readme-ov-file#youtube) for `youtube` extractor:

> comment_sort: top or new (default) - choose comment sorting mode (on YouTube's side)

Needs to be also described in help with example how to apply "top" mode: `--extractor-args "youtube:comment_sort=top"`

Also it will be good to add separate option, for example, `write-top-comments-first` (it also can be used just as `write-top-comments`) that will behave as both options: "--write-comments --extractor-args "youtube:comment_sort=top"

This new option will keep backwards compatibility and will not bring complication to the help.

---
Could you advice about the second problem? What can be done for converting already downloaded files with comments with sorting based on "new"? How to resort them based on "top"? Do I need to re-download them? Or may be you have script for sorting comments?

**Comment by coletdjnz** [comment]
It is new by default because youtube does not always provide all comments when sorting by top
