### ISSUE TITLE
Consider to add aliases for all long options based on thier acronym names

### ISSUE THREAD

**Issue by AntonSamokat** [yt-dlp/yt-dlp#10386]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

I have the following general `yt-dlp` `aliases` in my `~/yt-dlp.conf` config file:
```
--alias -V "--version"
--alias wij "--write-info-json"
--alias sd "--skip-download"
--alias ls "--list-subs"
--alias was "--write-auto-subs"
--alias ws "--write-subs"
--alias ams "--audio-multistreams"
--alias wt "--write-thumbnail"
--alias et "--embed-thumbnail"
--alias wd "--write-description"
--alias em "--embed-metadata"
--alias ec "--embed-chapters"
--alias ss "--sleep-subtitles"
--alias da "--download-archive"
--alias wc "--write-comments"
--alias np "--no-progress"
```

Please, consider to add them to out of the box `yt-dlp` configuration. Since they will be useful for everyone.
Also makes sense to consider aliases for all other long options in the similar way. 
If there will be ambiguities for some options then for simplicity this options can be left without aliases. They can be configured on user side according to specific needs.

Related requests:
- [Need short alias for --config-location · Issue #3469 · yt-dlp/yt-dlp](https://github.com/yt-dlp/yt-dlp/issues/3469)
- [add `--format none` as an alias for `--skip-download` · Issue #7397 · yt-dlp/yt-dlp](https://github.com/yt-dlp/yt-dlp/issues/7397)
- [Alias option name conflicts with longer existing option name when placed at the end of command · Issue #9009 · yt-dlp/yt-dlp](https://github.com/yt-dlp/yt-dlp/issues/9009)

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
No. You can define your own aliases, and you have. This is a solved problem.
