### ISSUE TITLE
Approximate file size `~GiB/~MiB` of HLS formats missing in old youtube-dl `--compat-options list-formats --compat-options format-sort -F` formats table.

### ISSUE THREAD

**Issue by barkoder** [yt-dlp/yt-dlp#10385]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

`yt-dlp --compat-options list-formats --compat-options format-sort -F` doesn't show approx. size for HLS formats.

[Approx filesize for -f 22](#1400) at least(not HLS I know), used to show up in the old youtube-dl format. At least until youtube decided to nuke all `itag=22` for all videos on their website.

Please have approx. size for HLS formats also show up in the old youtube-dl format.

I prefer the older youtube-dl formats table due to its smaller byte size.

Thanks!

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] yt-dlp version nightly@2024.07.05.232716 from yt-dlp/yt-dlp-nightly-builds [246911949] (win_exe)

NEW YT-DLP FORMATS TABLE WITH APPROX. SIZE FOR HLS FORMATS

$ yt-dlp -F https://www.youtube.com/watch?v=Oarf76MCrss | grep '^625'
625     mp4   3840x2160   30    | ~244.20MiB 18794k m3u8  | vp09.00.50.08 18794k video only

$ yt-dlp -F https://old.reddit.com/r/PublicFreakout/comments/1dxgpn3/always_be_careful_when_stopping_at_a_red_light_at/ | grep '^hls-2116'
hls-2116      mp4 720x1054    30 | ~  4.04MiB 2117k m3u8  | avc1.4D401F 2117k video only

---------

OLD YOUTUBE-DL FORMATS TABLE MISSING APPROX. SIZE :(

$ yt-dlp --compat-options list-formats --compat-options format-sort -F https://www.youtube.com/watch?v=Oarf76MCrss | grep '^625'
625          mp4        3840x2160   18793k, vp09.00.50.08@18793k, 30.0fps, video only@  0k

$ yt-dlp --compat-options list-formats --compat-options format-sort -F https://old.reddit.com/r/PublicFreakout/comments/1dxgpn3/always_be_careful_when_stopping_at_a_red_light_at/ | grep '^hls-2116'
hls-2116       mp4        720x1054    2116k, avc1.4D401F@2116k, 30.0fps, video only@  0k
```

**Comment by seproDev** [comment]
I guess you want `--compat-options list-formats,format-sort,manifest-filesize-approx`?

**Comment by barkoder** [comment]
Thank you @seproDev . That fixed it.
