### ISSUE TITLE
[youtube] Intermittent HTTP Error 403 during download

### ISSUE THREAD

**Issue by triplesixman** [yt-dlp/yt-dlp#10397]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Provide a description that is worded well enough to be understood

The error is quite annoying since it's random and occurs even when I don't pass any parameters to yt-dlp (no proxy, no deno). The same command executed immediately afterwards works without a hitch. This started several weeks ago.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[4] remote 198.144.145.10
[debug] Command-line config: ['https://youtu.be/OluGXpld5G8', '-f', 'bestaudio', '--proxy', 'http://user:password@localhost:3004/', '--extractor-args', 'youtube:bypass_native_jsi;deno_no_jitless', '-vU']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.07.09 from yt-dlp/yt-dlp [7ead7332a] (source)
[debug] Lazy loading extractors is disabled
[debug] Git HEAD: bbf84bf55
[debug] Python 3.9.7 (CPython x86_64 64bit) - Linux-5.10.0-30-amd64-x86_64-with-glibc2.31 (OpenSSL 1.1.1w  11 Sep 2023, glibc 2.31)
[debug] exe versions: ffmpeg N-116058-g2902ed25b5-20240630 (setts), ffprobe N-116058-g2902ed25b5-20240630, phantomjs 2.1.1
[debug] Optional libraries: sqlite3-3.34.1
[debug] Proxy map: {'all': 'http://user:password@localhost:3004/'}
[debug] Request Handlers: urllib
[debug] Extractor Plugins: NSigDeno (YoutubeIE)
[debug] Plugin directories: ['/opt/yt-dlp/yt_dlp_plugins']
[debug] Loaded 1834 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.07.09 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.07.09 from yt-dlp/yt-dlp)
[youtube+NSigDeno] Extracting URL: https://youtu.be/OluGXpld5G8
[youtube+NSigDeno] OluGXpld5G8: Downloading webpage
[youtube+NSigDeno] OluGXpld5G8: Downloading ios player API JSON
[debug] Loading youtube-nsig.5352eb4f from cache
[debug] [youtube+NSigDeno] Deno command line: deno run /tmp/tmp79f7ef2i
[debug] [youtube+NSigDeno] Decrypted nsig H5qSJ2RwVlHrlGLGJ2z => 4C3MhREB9mnCsw
[debug] Loading youtube-nsig.5352eb4f from cache
[debug] [youtube+NSigDeno] Deno command line: deno run /tmp/tmpx05xouym
[debug] [youtube+NSigDeno] Decrypted nsig uqnMPjZENh2xyLlVg4d => 2ypEw_FFTYvTyQ
[youtube+NSigDeno] OluGXpld5G8: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[info] OluGXpld5G8: Downloading 1 format(s): 251
[debug] Invoking http downloader on "https://rr3---sn-p5qlsn7l.googlevideo.com/videoplayback?expire=1720553291&ei=6zqNZuqdDJ-KkucP2fiKsAM&ip=XXX&id=o-AGbl0D--wlZxRXpNc49VX7y8hWCpLQ2THMXhKZKagZDC&itag=251&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=xO&mm=31%2C26&mn=sn-p5qlsn7l%2Csn-vgqsknzz&ms=au%2Conr&mv=m&mvi=3&pl=25&initcwndbps=3832500&bui=AXc671J3gWSUVG8Pof9v8Ri_JDRhAEu0l1nJArMSJvIJbj_1lmpl9bkEZ55g2wtOPUEAjTiraXM202KI&spc=NO7bAZlQP6E4HmV6K4GA5w7210XBdCBpbN-X3ZxxaTPkPdnhqjobto1sR9Id&vprv=1&svpuc=1&mime=audio%2Fwebm&ns=gjdwfvBsWLM2znfDYU-hyvcQ&rqh=1&gir=yes&clen=1262589&dur=79.381&lmt=1668700885878292&mt=1720531287&fvip=5&keepalive=yes&c=WEB&sefc=1&txp=5318224&n=2ypEw_FFTYvTyQ&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cbui%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cns%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRQIhAIIBKJ-fELLrLyrau48f1NUjjr2ubqD32TD-w2JX1fCjAiBnB8WFn7CZ6x-xMeRjC6QeluiBdzm3nluTTwgI43hiSw%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AHlkHjAwRQIhAOJG70YrPST2VuscIS2Lc6zDFvIBeLDSGDpoT8TvBwGiAiBt12wyiUh6ejtRDhnLOCjHiiyXLUTmKjVesW6kM5Y8Sw%3D%3D"
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/opt/yt-dlp/yt_dlp/networking/_urllib.py", line 396, in _send
    res = opener.open(urllib_req, timeout=self._calculate_timeout(request))
  File "/opt/python/versions/3.9.7/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/opt/python/versions/3.9.7/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/opt/python/versions/3.9.7/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/opt/python/versions/3.9.7/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/opt/python/versions/3.9.7/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/yt-dlp/yt_dlp/YoutubeDL.py", line 3478, in process_info
    success, real_download = self.dl(temp_filename, info_dict)
  File "/opt/yt-dlp/yt_dlp/YoutubeDL.py", line 3198, in dl
    return fd.download(name, new_info, subtitle)
  File "/opt/yt-dlp/yt_dlp/downloader/common.py", line 466, in download
    ret = self.real_download(filename, info_dict)
  File "/opt/yt-dlp/yt_dlp/downloader/http.py", line 369, in real_download
    establish_connection()
  File "/opt/yt-dlp/yt_dlp/downloader/http.py", line 120, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "/opt/yt-dlp/yt_dlp/YoutubeDL.py", line 4160, in urlopen
    return self._request_director.send(req)
  File "/opt/yt-dlp/yt_dlp/networking/common.py", line 117, in send
    response = handler.send(request)
  File "/opt/yt-dlp/yt_dlp/networking/_helper.py", line 208, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/yt-dlp/yt_dlp/networking/common.py", line 337, in send
    return self._send(request)
  File "/opt/yt-dlp/yt_dlp/networking/_urllib.py", line 401, in _send
    raise HTTPError(UrllibResponseAdapter(e.fp), redirect_loop='redirect error' in str(e)) from e
yt_dlp.networking.exceptions.HTTPError: HTTP Error 403: Forbidden
```

**Comment by dirkf** [comment]
Not the problem here but related, [player `b22ef6e7` is being sent with some  new challenges](https://github.com/ytdl-org/youtube-dl/issues/32842) for the built-in `JSInterp`, which will have a similar effect without external JS.

**Comment by bashonly** [comment]
@dirkf Unrelated. The issues with that player have already been patched in yt-dlp 2024.07.09

it was a 3 part fix for dlp: https://github.com/yt-dlp/yt-dlp/commit/6c056ea7aeb03660281653a9668547f2548f194f, https://github.com/yt-dlp/yt-dlp/commit/297b0a379282a15c80d82d51f3757c961db2dae1, https://github.com/yt-dlp/yt-dlp/commit/7ead7332af69422cee931aec3faa277288e9e212

**Comment by UnconsciousBlaringHuman** [comment]
I'm not sure if it'll be of any help but it is still possible to download formats with the `mp4` extension (as opposed to the ones with `webm` extension).

For example:

```
[info] Available formats for RgBYohJ7mIk:
ID      EXT   RESOLUTION FPS CH │   FILESIZE   TBR PROTO │ VCODEC          VBR ACODEC      ABR ASR MORE INFO
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
sb3     mhtml 48x27        1    │                  mhtml │ images                                  storyboard
sb2     mhtml 80x45        1    │                  mhtml │ images                                  storyboard
sb1     mhtml 160x90       1    │                  mhtml │ images                                  storyboard
sb0     mhtml 320x180      1    │                  mhtml │ images                                  storyboard
233     mp4   audio only        │                  m3u8  │ audio only          unknown             [en] Default
234     mp4   audio only        │                  m3u8  │ audio only          unknown             [en] Default
139-drc m4a   audio only      2 │    1.03MiB   49k https │ audio only          mp4a.40.5   49k 22k [en] low, DRC, m4a_dash
139     m4a   audio only      2 │    1.03MiB   49k https │ audio only          mp4a.40.5   49k 22k [en] low, m4a_dash
140-drc m4a   audio only      2 │    2.73MiB  130k https │ audio only          mp4a.40.2  130k 44k [en] medium, DRC, m4a_dash
140     m4a   audio only      2 │    2.73MiB  130k https │ audio only          mp4a.40.2  130k 44k [en] medium, m4a_dash
602     mp4   256x144     12    │ ~  1.57MiB   74k m3u8  │ vp09.00.10.08   74k video only
269     mp4   256x144     24    │ ~  1.61MiB   76k m3u8  │ avc1.4D400C     76k video only
160     mp4   256x144     24    │  276.69KiB   13k https │ avc1.4D400C     13k video only          144p, mp4_dash
603     mp4   256x144     24    │ ~  2.17MiB  103k m3u8  │ vp09.00.11.08  103k video only
229     mp4   426x240     24    │ ~  2.05MiB   97k m3u8  │ avc1.4D4015     97k video only
133     mp4   426x240     24    │  462.91KiB   21k https │ avc1.4D4015     21k video only          240p, mp4_dash
604     mp4   426x240     24    │ ~  3.09MiB  147k m3u8  │ vp09.00.20.08  147k video only
230     mp4   640x360     24    │ ~  4.43MiB  210k m3u8  │ avc1.4D401E    210k video only
134     mp4   640x360     24    │  708.10KiB   33k https │ avc1.4D401E     33k video only          360p, mp4_dash
605     mp4   640x360     24    │ ~  5.74MiB  272k m3u8  │ vp09.00.21.08  272k video only
231     mp4   854x480     24    │ ~  5.11MiB  242k m3u8  │ avc1.4D401E    242k video only
135     mp4   854x480     24    │  968.11KiB   45k https │ avc1.4D401E     45k video only          480p, mp4_dash
606     mp4   854x480     24    │ ~  7.05MiB  334k m3u8  │ vp09.00.30.08  334k video only
232     mp4   1280x720    24    │ ~  5.95MiB  282k m3u8  │ avc1.4D401F    282k video only
136     mp4   1280x720    24    │    1.33MiB   63k https │ avc1.4D401F     63k video only          720p, mp4_dash
609     mp4   1280x720    24    │ ~ 10.54MiB  499k m3u8  │ vp09.00.31.08  499k video only
270     mp4   1920x1080   24    │ ~ 10.53MiB  499k m3u8  │ avc1.640028    499k video only
137     mp4   1920x1080   24    │    3.17MiB  150k https │ avc1.640028    150k video only          1080p, mp4_dash
614     mp4   1920x1080   24    │ ~ 15.45MiB  732k m3u8  │ vp09.00.40.08  732k video only
620     mp4   2560x1440   24    │ ~ 30.35MiB 1438k m3u8  │ vp09.00.50.08 1438k video only
625     mp4   3840x2160   24    │ ~ 67.35MiB 3192k m3u8  │ vp09.00.50.08 3192k video only
```

I had no trouble downloading it in any of these formats, other than the following warnings:
```
λ yt-dlp -f 137+140 https://youtu.be/RgBYohJ7mIk
[youtube+oauth2] Extracting URL: https://youtu.be/RgBYohJ7mIk
[youtube+oauth2] RgBYohJ7mIk: Downloading webpage
[youtube+oauth2] RgBYohJ7mIk: Downloading ios player API JSON
[youtube+oauth2] RgBYohJ7mIk: Downloading player b22ef6e7
WARNING: [youtube+oauth2] RgBYohJ7mIk: nsig extraction failed: Some formats may be missing
         n = yH87kTyGGB7j8G7xW ; player = https://www.youtube.com/s/player/b22ef6e7/player_ias.vflset/en_US/base.js
WARNING: [youtube+oauth2] RgBYohJ7mIk: nsig extraction failed: Some formats may be missing
         n = dBst9mzeK4_aVlpys ; player = https://www.youtube.com/s/player/b22ef6e7/player_ias.vflset/en_US/base.js
```

(I'm using the OAuth plugin, probably the reason for the "+oauth2" at the start)

**Comment by bashonly** [comment]
This issue is **not** tracking 403 errors on EVERY video. If you are experiencing that, then your issue is either #10046 (you are passing cookies and your account has been blocked) or #7860 (your IP has been blocked by Youtube).

**Comment by bashonly** [comment]
@UnconsciousBlaringHuman update yt-dlp

**Comment by UnconsciousBlaringHuman** [comment]
I'd updated on Sunday, didn't even think to check for updates 🙃. That did it. Everything seems to be working perfectly now. Thank you.

**Comment by GizuMoca** [comment]
I can't download format 18.
What should I do?

`
yt-dlp -f 'bestvideo[ext=mp4]'
`

**Comment by drhashes** [comment]
> `format_id=18` is no longer available for download. `format_id=139` `format_id=137` is available for download, but there is no video with audio. What should I do?
> 
> `yt-dlp -f 'bestvideo[ext=mp4]'`

yt-dlp -f 137+bestaudio[ext=m4a]

**Comment by GizuMoca** [comment]
> > `format_id=18` is no longer available for download. `format_id=139` `format_id=137` is available for download, but there is no video with audio. What should I do?
> > `yt-dlp -f 'bestvideo[ext=mp4]'`
> 
> yt-dlp -f 137+bestaudio[ext=m4a]

Thank you for your reply.
`format_id=18`
When I access it, I still get HTTP ERROR 403.

**Comment by drhashes** [comment]
> > > `format_id=18` is no longer available for download. `format_id=139` `format_id=137` is available for download, but there is no video with audio. What should I do?
> > > `yt-dlp -f 'bestvideo[ext=mp4]'`
> > 
> > 
> > yt-dlp -f 137+bestaudio[ext=m4a]
> 
> Thank you for your reply. `format_id=18` When I access it, I still get HTTP ERROR 403.

Do you have the latest 2024.07 version?
yt-dlp --version

If not upgrade with:
yt-dlp -U

**Comment by metalfoxdev** [comment]
Still getting this same issue on SmartTube which uses yt-dlp. NewPipe also seems to be affected...

**Comment by drhashes** [comment]
For me it works but I only tested youtube.

**Comment by ProGamer2508-0** [comment]
@metalfoxdev Tubular is gone too

**Comment by ProGamer2508-0** [comment]
> I would also add that it is clearly another attempt by g00gl3 to block this and other services for as long as possible (which is very obvious)

@foxjaw, already said

**Comment by ProGamer2508-0** [comment]
Invidious should use another service if I remember correctly (but obviously depends on the instance). ytdl *is the service*, so it is not the same as Invidious or NewPipe, and there is very little similar. NewPipe uses instances: most use ytdl

**Comment by Itsaira** [comment]
I downgraded to yt-dlp==2023.7.6 and it's working fine for me now :)

**Comment by Elite** [comment]
I am on the latest nightly, getting issue every few downloads. All downloads from different proxy services.

**Comment by metalfoxdev** [comment]
I feel like that the issue might just be mostly with HTTP DASH streams. I think Invidious does normally use legacy formats by default, I remember having to enable HTTP DASH on some instances. Btw, I did try to DL a video using yt-dlp latest and it did work but I did get an nsig extraction error. I will do some more testing soon and report my findings here.

**Comment by gut1414** [comment]
Also affects 4K Video Downloader, iTubeGo, NewPipe, youtube-dl, yt-dlp, etc, and also some online downloaders. I think Google try to prevent downloading (after some tries on other domains, like antiadblock, detecting YouTube Premium subscriptions with VPN to close subscriptions, etc).

**Comment by bashonly** [comment]
> I did get an nsig extraction error

### If you get any nsig warning or error, it means you need to update to the latest nightly. If you are not using the latest nightly, your experience is irrelevant and do NOT reply to this issue. Only discuss intermittent 403 errors with yt-dlp (not any other app) in this thread.

**Comment by bashonly** [comment]
No

**Comment by Elite** [comment]
@bashonly Hmmm... I thought this change https://github.com/LuanRT/YouTube.js/commit/62ac2f6f32d35fec3c31b5f5d556bd4569fa49f9 reincarnated the Android client once again.

**Comment by bashonly** [comment]
`--extractor-args "player_client=ios"` works around this issue, at the cost of sacrificing some WEB-only formats. (And it will not be effective for age-restricted videos where the TV embedded bypass is needed/used.)

**Comment by CrushedAsian255** [comment]
> --extractor-args "youtube:player_client=ios" works around this issue, at the cost of sacrificing some WEB-only formats. 
is this going to be the solution going forward?

**Comment by triplesixman** [comment]
With https://github.com/yt-dlp/yt-dlp/commit/8b8b442cb005a8d85315f301615f83fb736b967a the error is now replaced by Warning "Webpage contains broken formats (poToken experiment detected). Ignoring initial player response".

Is there currently no way of avoiding this and allowing the download to work properly?



```
[debug] Command-line config: ['https://youtu.be/Ndpryp2OlUQ', '-f', 'bestaudio', '--proxy', 'http://user:password@localhost:3003/', '--extractor-args', 'youtube:bypass_native_jsi;deno_no_jitless', '-vU']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.07.09 from yt-dlp/yt-dlp [7ead7332a] (source)
[debug] Lazy loading extractors is disabled
[debug] Git HEAD: bbf84bf55
[debug] Python 3.9.7 (CPython x86_64 64bit) - Linux-5.10.0-30-amd64-x86_64-with-glibc2.31 (OpenSSL 1.1.1w  11 Sep 2023, glibc 2.31)
[debug] exe versions: ffmpeg N-116058-g2902ed25b5-20240630 (setts), ffprobe N-116058-g2902ed25b5-20240630, phantomjs 2.1.1
[debug] Optional libraries: sqlite3-3.34.1
[debug] Proxy map: {'all': 'http://user:password@localhost:3003/'}
[debug] Request Handlers: urllib
[debug] Extractor Plugins: NSigDeno (YoutubeIE)
[debug] Plugin directories: ['/opt/yt-dlp/yt_dlp_plugins']
[debug] Loaded 1834 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.07.09 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.07.09 from yt-dlp/yt-dlp)
[youtube+NSigDeno] Extracting URL: https://youtu.be/Ndpryp2OlUQ
[youtube+NSigDeno] Ndpryp2OlUQ: Downloading webpage
WARNING: [youtube+NSigDeno] Webpage contains broken formats (poToken experiment detected). Ignoring initial player response
[youtube+NSigDeno] Ndpryp2OlUQ: Downloading ios player API JSON
[youtube+NSigDeno] Ndpryp2OlUQ: Downloading iframe API JS
[youtube+NSigDeno] Ndpryp2OlUQ: Downloading player 820bff3b
[youtube+NSigDeno] Ndpryp2OlUQ: Downloading web player API JSON
WARNING: [youtube+NSigDeno] API returned broken formats (poToken experiment detected). Retrying (1/3)...
[youtube+NSigDeno] Ndpryp2OlUQ: Downloading web player API JSON
[debug] [youtube+NSigDeno] Extracting signature function js_820bff3b_109
[debug] Loading youtube-sigfuncs.js_820bff3b_109 from cache
[debug] Loading youtube-nsig.820bff3b from cache
[debug] [youtube+NSigDeno] Deno command line: deno run /tmp/tmpsuprqb3t
[debug] [youtube+NSigDeno] Decrypted nsig noWDMuvty_PXVmYK => Yzky0KePCKd6zg
[debug] Loading youtube-nsig.820bff3b from cache
[debug] [youtube+NSigDeno] Deno command line: deno run /tmp/tmp6y2l8s62
[debug] [youtube+NSigDeno] Decrypted nsig IMGifbc3VPilquVR => 5SuY2T5sMtJccw
[debug] [youtube+NSigDeno] Extracting signature function js_820bff3b_105
[debug] Loading youtube-sigfuncs.js_820bff3b_105 from cache
[youtube+NSigDeno] Ndpryp2OlUQ: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[info] Ndpryp2OlUQ: Downloading 1 format(s): 251
[debug] Invoking http downloader on "https://rr2---sn-qxo7rn7r.googlevideo.com/videoplayback?expire=1721145359&ei=r0OWZrZwhJfb-A-B5YjwDQ&ip=&id=o-AF11ulvKXfgtwndgbBLuR5zBi0bgFMHzrvgFuS8Ioty1&itag=251&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=5D&mm=31%2C26&mn=sn-qxo7rn7r%2Csn-q4fl6nsk&ms=au%2Conr&mv=m&mvi=2&pl=24&gcr=us&initcwndbps=2607500&bui=AXc671I8ylL5HIYINGd948LUBuMlmzx3dSgm607XMSwViYgpjVJWaRJp8LKrSakZW7yJZG4S-L7KFy6k&spc=NO7bAbd2a9S3jhmZG-29YEj4qNXX0efLU2tm_5qcgBMFd4H9P0C0fpD1uOIh&vprv=1&svpuc=1&mime=audio%2Fwebm&ns=q7u7RA0uQv8HZOwfkd0WStYQ&rqh=1&gir=yes&clen=5064597&dur=287.281&lmt=1714616361129498&mt=1721123359&fvip=5&keepalive=yes&c=WEB&sefc=1&txp=4502434&n=5SuY2T5sMtJccw&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cgcr%2Cbui%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cns%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AHlkHjAwRQIgYUlpuq6bW8IaGsTxuc_kuoqRkDFDrLyCvLNy1G51uvwCIQCAp-lxVcwGXRl1P5ggP8G0MZgIji1XR2r3bkn553rt7A%3D%3D&sig=AJfQdSswRQIhAKbfWlP22aKAGYFQhWNPXGfOxZeHOmLPlR-pZQOGEh5FAiAX5K_Fea-rAvyfPfjhk5q_EwBN3Vj1cvSp8CdCQ0hLag%3D%3D"
[download] Destination: Yelawolf - Till It’s Gone (Official Music Video) [Ndpryp2OlUQ].webm
[download] 100% of    4.83MiB in 00:00:00 at 7.70MiB/s
```

**Comment by seproDev** [comment]
> Is there currently no way of avoiding this and allowing the download to work properly?

But it is, isn't it? The web formats are retried up to three times to get a response without the poToken experiments.

**Comment by triplesixman** [comment]
> > Is there currently no way of avoiding this and allowing the download to work properly?
> 
> But it is, isn't it? The web formats are retried up to three times (or whatever you configured it to) to get a response without the poToken experiments.

Yes, but I mean, what will happen when potoken is required every time? (I don't know much about potoken, but I imagine that youtube could make it so that it's required for every download, from one day to the next)?

**Comment by seproDev** [comment]
With the current code, it would fall back to the iOS formats instead of hard failing with a 403. We are looking in to changing the default player client used: https://github.com/yt-dlp/yt-dlp/pull/10457

**Comment by Muczak** [comment]
Issue:
ERROR: unable to download video data: HTTP Error 403: Forbidden

What’s happening:
YouTube (and some other sites) are blocking requests because they detect yt-dlp as an automated client instead of a regular browser.
This can happen due to missing authentication cookies, invalid headers, or updated site anti-bot checks.
The yt-dlp team has already marked similar cases as “site-bug”.

Fix that worked ✅

Open YouTube in your regular browser and make sure you’re logged in.

Install the extension “Get cookies.txt LOCALLY” (for Chrome/Edge/Firefox).

Export your YouTube cookies as a file named cookies.txt.

Place that cookies.txt in the same folder where yt-dlp or your bot runs.

Run yt-dlp with the cookies file, for example:

yt-dlp --cookies cookies.txt "https://www.youtube.com/watch?v=VIDEO_ID"


Check that the download starts correctly (it should no longer show HTTP 403).

Why this works:
Using cookies makes your yt-dlp requests look exactly like a logged-in browser session, bypassing YouTube’s stricter anti-bot filtering that was recently introduced.

Additional notes:

Always update yt-dlp to the latest version (yt-dlp -U).

If running from a server, make sure its IP isn’t rate-limited or region-blocked by YouTube.

If even cookies don’t fix it, the issue is likely on YouTube’s side and requires a new extractor update in yt-dlp.

Summary:
If you get a 403 error starting around October 2025, downloading your YouTube cookies and adding
--cookies cookies.txt resolves it instantly.
This workaround is confirmed working until yt-dlp releases an official patch for the new YouTube request validation.
