### ISSUE TITLE
[youtube] Endless "Incomplete data received" when downloading playlist

### ISSUE THREAD

**Issue by mpeter50** [yt-dlp/yt-dlp#10394]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Provide a description that is worded well enough to be understood

For certain Youtube playlists the processing of the playlist itself fails.
It is not fatal in the sense that if I dont use `--extractor-retries infinite`, then it can download the videos on the playlist, but for archiving purposes I wouldn't want to use that unless necessary.
An optimal fix would accept the amount of data that youtube has returned, and save that into the appropriate output files.

In the command output I have also included the command that should be able to reproduce the issue, along with an example playlist where this occurs.

#1787 is similar, but that is for downloading comments, this is for playlists.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp --no-config --extractor-retries infinite -vU --simulate https://www.youtube.com/playlist?list=PLYc8xAEfO0PTjG7nVafkLeVxQ5raSJwc8
[debug] Command-line config: ['--no-config', '--extractor-retries', 'infinite', '-vU', '--simulate', 'https://www.youtube.com/playlist?list=PLYc8xAEfO0PTjG7nVafkLeVxQ5raSJwc8']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8 
[debug] yt-dlp version stable@2024.07.07 from yt-dlp/yt-dlp [b337d2989] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.18363-SP0 (OpenSSL 1.1.1k  25 Mar 2021) 
[debug] exe versions: ffmpeg 7.0-full_build-www.gyan.dev (setts), ffprobe 7.0-full_build-www.gyan.dev 
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.07.04, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1834 extractors 
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.07.07 from yt-dlp/yt-dlp 
yt-dlp is up to date (stable@2024.07.07 from yt-dlp/yt-dlp)
[youtube:tab] Extracting URL: https://www.youtube.com/playlist?list=PLYc8xAEfO0PTjG7nVafkLeVxQ5raSJwc8 
[youtube:tab] PLYc8xAEfO0PTjG7nVafkLeVxQ5raSJwc8: Downloading webpage
[youtube:tab] PLYc8xAEfO0PTjG7nVafkLeVxQ5raSJwc8: Redownloading playlist API JSON with unavailable videos 
[download] Downloading playlist: Minecraft Modokkal (1.7.10) 
[youtube:tab] PLYc8xAEfO0PTjG7nVafkLeVxQ5raSJwc8 page 1: Downloading API JSON 
WARNING: [youtube:tab] Incomplete data received. Retrying (1/inf)... 
[youtube:tab] PLYc8xAEfO0PTjG7nVafkLeVxQ5raSJwc8 page 1: Downloading API JSON
WARNING: [youtube:tab] Incomplete data received. Retrying (2/inf)... 
[youtube:tab] PLYc8xAEfO0PTjG7nVafkLeVxQ5raSJwc8 page 1: Downloading API JSON
WARNING: [youtube:tab] Incomplete data received. Retrying (3/inf)... 
[youtube:tab] PLYc8xAEfO0PTjG7nVafkLeVxQ5raSJwc8 page 1: Downloading API JSON
WARNING: [youtube:tab] Incomplete data received. Retrying (4/inf)... 
[youtube:tab] PLYc8xAEfO0PTjG7nVafkLeVxQ5raSJwc8 page 1: Downloading API JSON
WARNING: [youtube:tab] Incomplete data received. Retrying (5/inf)...
[snip]
```

**Comment by bashonly** [comment]
see https://github.com/yt-dlp/yt-dlp/issues/8206#issuecomment-1749945013

closing as dupe

**Comment by mpeter50** [comment]
Oh, thanks!

I'm primarily using infinite retries wherever possible so that its less likely that yt-dlp records a partial archive in an archive file when the errors were caused by network failure.
Would it be possible to make it so that in cases like this, yt-dlp does not record the video in the archive file? The "incomplete data" error type is clear that it is not a network error, so it is probably okay to stop retrying it after a few times.

I guess the answer is "do not use --ignore-errors".
In that case, would it be possible to have an alternate version of it that skips videos that errored, letting the rest be downloaded, and report at the end that there were errored videos? Basically it would be the same best-effort behavior, but without treating errors as success.
I'm mostly using `--ignore-errors` so that I can download lists of videos even when I'm not looking at the progress, so that something weird cannot interrupt the process.

**Comment by bashonly** [comment]
if extraction fails there is zero chance anything will be recorded to your download archive, so `--extractor-retries inf` isn't doing any good there

**Comment by mpeter50** [comment]
> If extraction fails there is zero chance anything will be recorded to your download archive, so --extractor-retries inf isn't doing any good there.

But that does not only affect video extraction, as I understand.

With this playlist when the default 3 tries run out, it will continue with downloading the videos on it, but the playlist metadata wont be recorded. Do you mean that then the videos wouldnt be recorded to the archive file?

**Comment by bashonly** [comment]
The "incomplete data received" during playlist extraction is only a warning triggered by a false positive. You can ignore it
