### ISSUE TITLE
extraction failed: Some formats may be missing

### ISSUE THREAD

**Issue by trrtuuwwwa** [yt-dlp/yt-dlp#10406]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Message error
//www.youtube.com/watch?v=7wQ4MwAPrBg
WARNING: [youtube] BlD6jCGVU4A: nsig extraction failed: Some formats may be missing
         n = BZB-_W2RkcJNAkjZ4 ; player = https://www.youtube.com/s/player/b22ef6e7/player_ias.vflset/en_US/base.js
...
Code running for to years and suddenly this message error appear...
Format selected iny code:

format': 'best[height<720]',

....
Another format audio only no problem

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
//www.youtube.com/watch?v=7wQ4MwAPrBg
WARNING: [youtube] BlD6jCGVU4A: nsig extraction failed: Some formats may be missing
         n = BZB-_W2RkcJNAkjZ4 ; player = https://www.youtube.com/s/player/b22ef6e7/player_ias.vflset/en_US/base.js
```

**Comment by bashonly** [comment]
That's not **complete verbose output**. Add `-vU` to your command and copy/paste the entire output

**Comment by trrtuuwwwa** [comment]
Go fuck your self motherfucker and answer to question without cring
...
You are motherfucker son of bith

**Comment by trrtuuwwwa** [comment]
🤣🤣🤣🤣🖕🖕🖕

**Comment by trrtuuwwwa** [comment]
Motherfucker
