### ISSUE TITLE
FFMpeg not found

### ISSUE THREAD

**Issue by Roxy45l** [yt-dlp/yt-dlp#10410]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

I am using the latest version of the library, but I could not figure out the reason for this error. Videos download slower than before.
My options settings are like this
                            ydl_opts = {
                                'format': 'bestvideo[ext=mp4][vcodec=h264][height=360]+bestaudio[ext=m4a]/best[ext=mp4][vcodec=h264][height=360]/best',
                                'outtmpl': self.filename,
                                'progress_hooks': [self.hook],
                                'proxy': proxy_url
                            }                                                                       

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
youtube  | [youtube] 0VxPtIcmCYw: Downloading webpage
youtube  | [youtube] 0VxPtIcmCYw: Downloading ios player API JSON
youtube  | [youtube] 0VxPtIcmCYw: Downloading player b22ef6e7
youtube  | [youtube] 0VxPtIcmCYw: Downloading m3u8 information
youtube  | WARNING: [youtube] Failed to download m3u8 information: HTTP Error 429: Too Many Requests
youtube  | WARNING: ffmpeg not found. The downloaded format may not be the best available. Installing ffmpeg is strongly recommended: https://github.com/yt-dlp/yt-dlp#dependencies
youtube  | [youtube] Extracting URL: https://www.youtube.com/watch?v=CG713CSmiJw
youtube  | [youtube] 0VxPtIcmCYw: Downloading webpage
youtube  | WARNING: [youtube] Unable to download webpage: <urlopen error [Errno 4] Host unreachable>
youtube  | [youtube] 0VxPtIcmCYw: Downloading ios player API JSON
youtube  | WARNING: [youtube] <urlopen error [Errno 4] Host unreachable>. Retrying (1/3)...
youtube  | [youtube] 0VxPtIcmCYw: Downloading ios player API JSON
```

**Comment by bashonly** [comment]
Here's a breakdown of the warnings/error output:

> youtube  | WARNING: [youtube] Failed to download m3u8 information: HTTP Error 429: Too Many Requests

Your IP has been rate-limited or your IP is blocked from `manifest.googlevideo.com`

> youtube  | WARNING: ffmpeg not found. The downloaded format may not be the best available. Installing ffmpeg is strongly recommended: https://github.com/yt-dlp/yt-dlp#dependencies

You don't have ffmpeg in your PATH

> youtube  | WARNING: [youtube] Unable to download webpage: <urlopen error [Errno 4] Host unreachable>

Network issue. Is something blocking `www.youtube.com`? Can you confirm what you checked below:

> - [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details

And finally, you didn't do this:

> - [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
> - [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below
