### ISSUE TITLE
[InvestigationDiscovery] "This video is only available for registered users. You may want to use --cookies."

### ISSUE THREAD

**Issue by MuncheeMunch** [yt-dlp/yt-dlp#10421]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United States of America

### Provide a description that is worded well enough to be understood

Hello! I'm trying to download a video from the Investigation Discovery website, but I get an error that the video is only available to registered users. This is confusing because the same video plays perfectly fine in my browser without requiring an account. I've tried multiple things, including using --cookies, --source-address, and setting the User-Agent header, but nothing works.

Here's the URL of the video I'm trying to download: https://www.investigationdiscovery.com/video/deadly-influence-the-social-media-murders-investigation-discovery-atve-us/rip-bianca

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
user1@debian:~/Desktop$ yt-dlp -vU -F -S "vbr,abr" "https://www.investigationdiscovery.com/video/deadly-influence-the-social-media-murders-investigation-discovery-atve-us/rip-bianca"
[debug] Command-line config: ['-vU', '-F', '-S', 'vbr,abr', 'https://www.investigationdiscovery.com/video/deadly-influence-the-social-media-murders-investigation-discovery-atve-us/rip-bianca']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.07.10.232707 from yt-dlp/yt-dlp-nightly-builds [705f5b84d] (zip)
[debug] Python 3.11.2 (CPython x86_64 64bit) - Linux-6.1.0-22-amd64-x86_64-with-glibc2.36 (OpenSSL 3.0.13 30 Jan 2024, glibc 2.36)
[debug] exe versions: none
[debug] Optional libraries: certifi-2022.09.24, mutagen-1.46.0, requests-2.28.1, sqlite3-3.40.1, urllib3-1.26.12
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Loaded 1834 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.07.10.232707 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.07.10.232707 from yt-dlp/yt-dlp-nightly-builds)
[InvestigationDiscovery] Extracting URL: https://www.investigationdiscovery.com/video/deadly-influence-the-social-media-murders-investigation-discovery-atve-us/rip-bianca
[debug] Using fake IP 6.158.231.125 (US) as X-Forwarded-For
[InvestigationDiscovery] deadly-influence-the-social-media-murders-investigation-discovery-atve-us/rip-bianca: Downloading JSON metadata
ERROR: [InvestigationDiscovery] deadly-influence-the-social-media-murders-investigation-discovery-atve-us/rip-bianca: This video is only available for registered users. You may want to use --cookies.
  File "/home/user1/.local/bin/yt-dlp/yt_dlp/extractor/common.py", line 740, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user1/.local/bin/yt-dlp/yt_dlp/extractor/dplay.py", line 365, in _real_extract
    return self._get_disco_api_info(url, self._match_id(url), **self._DISCO_API_PARAMS)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user1/.local/bin/yt-dlp/yt_dlp/extractor/dplay.py", line 91, in _get_disco_api_info
    self._process_errors(e, geo_countries)
  File "/home/user1/.local/bin/yt-dlp/yt_dlp/extractor/dplay.py", line 48, in _process_errors
    raise ExtractorError(
```

**Comment by bashonly** [comment]
This fixes it:

```diff
diff --git a/yt_dlp/extractor/dplay.py b/yt_dlp/extractor/dplay.py
index 48eae1088..3110583b2 100644
--- a/yt_dlp/extractor/dplay.py
+++ b/yt_dlp/extractor/dplay.py
@@ -553,6 +553,13 @@ class InvestigationDiscoveryIE(DiscoveryPlusBaseIE):
         'country': 'us',
     }
 
+    def _update_disco_api_headers(self, headers, disco_base, display_id, realm):
+        headers.update({
+            'x-disco-params': f'realm={realm},siteLookupKey={self._PRODUCT}',
+            'x-disco-client': f'WEB:UNKNOWN:{self._PRODUCT}:27.43.0',
+            'Authorization': self._get_auth(disco_base, display_id, realm),
+        })
+
 
 class AmHistoryChannelIE(DiscoveryPlusBaseIE):
     _VALID_URL = r'https?://(?:www\.)?ahctv\.com/video' + DPlayBaseIE._PATH_REGEX
```

**Comment by cobhc2019** [comment]
Hi, having a similar issue here in GB. Videos work fine in my browser, but regardless of asking YT-DLP to request cookies from the browser or fetching the cookies myself I still get the "This video is only available for registered users. You may want to use --cookies." error. I have a paid account with Discovery+ and I'm trying to download non-free videos.

**Comment by bashonly** [comment]
@cobhc2019 can you share complete verbose output, please? Add `-vU` to your command and copy/paste the entire output

**Comment by cobhc2019** [comment]
@bashonly Please see below.

`c:\Users\Stee\Downloads>yt-dlp --cookies-from-browser chrome https://www.discoveryplus.com/gb/video/wheeler-dealers/1976-mercury-capri-mk2 -vU
[debug] Command-line config: ['--cookies-from-browser', 'chrome', 'https://www.discoveryplus.com/gb/video/wheeler-dealers/1976-mercury-capri-mk2', '-vU']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.07.09 from yt-dlp/yt-dlp [7ead7332a] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22631-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.07.04, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {}
Extracting cookies from chrome
[debug] Extracting cookies from: "C:\Users\Stee\AppData\Local\Google\Chrome\User Data\Default\Network\Cookies"
[debug] Found local state file at "C:\Users\Stee\AppData\Local\Google\Chrome\User Data\Local State"
Extracted 1209 cookies from chrome
[debug] cookie version breakdown: {'v10': 1343, 'other': 0, 'unencrypted': 8}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1834 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.07.09 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.07.09 from yt-dlp/yt-dlp)
[DiscoveryPlus] Extracting URL: https://www.discoveryplus.com/gb/video/wheeler-dealers/1976-mercury-capri-mk2
[debug] Using fake IP 6.136.89.117 (US) as X-Forwarded-For
[DiscoveryPlus] wheeler-dealers/1976-mercury-capri-mk2: Downloading JSON metadata
ERROR: [DiscoveryPlus] wheeler-dealers/1976-mercury-capri-mk2: This video is only available for registered users. You may want to use --cookies.
  File "yt_dlp\extractor\common.py", line 740, in extract
  File "yt_dlp\extractor\dplay.py", line 365, in _real_extract
  File "yt_dlp\extractor\dplay.py", line 91, in _get_disco_api_info
  File "yt_dlp\extractor\dplay.py", line 48, in _process_errors`

**Comment by bashonly** [comment]
@cobhc2019 was it working for you in the past? It looks like GB and DE DiscoveryPlus links have been plagued by #2361 for a while.

**Comment by cobhc2019** [comment]
I've only just found out about yt_dlp, so no.

Thanks, I'll monitor things and see what happens.

**Comment by bashonly** [comment]
@cobhc2019 I'm geo-blocked from DiscoveryPlus GB (and don't have a subscription), so I won't be able to work on that without assistance. If you're comfortable with sending me a HAR file of your browser's network requests while loading a video on the site, I would have something to work from. I could walk you through how to do it. 

If you're up for it, contact me on discord (same username) or via email, `bashonly ( a t ) proton mail [d o t] com`

**Comment by DoonGuy** [comment]
Anything happen behind the scenes here? I think I'm experiencing the same issue but with DiscoveryPlus CA. I tried using the patch but it didn't seem to work, though that could be user error. I added the patch @ line 556 of dplay.py, then compiled using the PyInstaller instructions.

```
./yt-dlp https://www.discoveryplus.com/ca/video/cake-wars-food-network-ca/dc-comics --cookies-from-browser firefox -vU
[debug] Command-line config: ['https://www.discoveryplus.com/ca/video/cake-wars-food-network-ca/dc-comics', '--cookies-from-browser', 'firefox', '-vU']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.07.09 from yt-dlp/yt-dlp [7ead7332a] (win_exe)
[debug] Python 3.10.6 (CPython AMD64 64bit) - Windows-10-10.0.22631-SP0 (OpenSSL 1.1.1n  15 Mar 2022)
[debug] exe versions: ffmpeg 2024-04-10-git-0e4dfa4709-full_build-www.gyan.dev (setts), ffprobe 2024-04-10-git-0e4dfa4709-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.07.04, mutagen-1.47.0, requests-2.32.3, sqlite3-3.37.2, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {}
Extracting cookies from firefox
[debug] Extracting cookies from: "C:\Users\(Redacted)\AppData\Roaming\Mozilla\Firefox\Profiles\uyhlspk7.(Redacted)\cookies.sqlite"
Extracted 1241 cookies from firefox
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1834 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.07.09 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.07.09 from yt-dlp/yt-dlp)
[DiscoveryPlus] Extracting URL: https://www.discoveryplus.com/ca/video/cake-wars-food-network-ca/dc-comics
[debug] Using fake IP 6.70.81.43 (US) as X-Forwarded-For
[DiscoveryPlus] cake-wars-food-network-ca/dc-comics: Downloading JSON metadata
ERROR: [DiscoveryPlus] cake-wars-food-network-ca/dc-comics: This video is only available for registered users. You may want to use --cookies.
  File "yt_dlp\extractor\common.py", line 740, in extract
  File "yt_dlp\extractor\dplay.py", line 365, in _real_extract
  File "yt_dlp\extractor\dplay.py", line 91, in _get_disco_api_info
  File "yt_dlp\extractor\dplay.py", line 48, in _process_errors
``` 

I'm up for sending a HAR file, or helping however I can. Just thought I'd check in here first rather than just sending an unexpected DM, especially if it might not be needed.

**Comment by bashonly** [comment]
sure, go ahead and shoot me a DM

**Comment by bashonly** [comment]
@cobhc2019 could you give this PR a try?

- #10471

I've created pre-release builds for testing purposes:

```
yt-dlp --update-to bashonly/yt-dlp@dplay
```

**Comment by cobhc2019** [comment]
Yep, that works now. Thanks!

**Comment by bashonly** [comment]
@cobhc2019 sorry to ask again, but I had to rewrite the PR somewhat due to a logic flaw. When you get a chance, could run `yt-dlp --update-to bashonly/yt-dlp@dplay` again to update to the latest patched build and give it another try?

**Comment by cobhc2019** [comment]
Yep, updated and still working fine!
