### ISSUE TITLE
"This application has requested the Runtime to terminate it in an unusual way." nightly@2024.07.10.232707. New curl_cffi broken on Windows 7.

### ISSUE THREAD

**Issue by barkoder** [yt-dlp/yt-dlp#10426]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Steps to reproduce.

0. Use Windows 7 x64 and get yt-dlp version nightly@2024.07.10.232707

1. `yt-dlp --impersonate="" -F BaW_jenozKc`

2. "This application has requested the Runtime to terminate it in an unusual way."

~~I thought this was only gonna happen in/after October ? #10086~~

EDIT: The problem appeaars to be with the new curl_cffi . Not using `--impersonate=""` does show the formats_table. But now I can't use yt-dlp on websites that necessitate impersonation.

EDIT: The issue does not exist in `nightly@2024.07.09.232843`

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
$ youtube-dl -v --impersonate "" --youtube-skip-hls-manifest --compat-options list-formats,format-sort,manifest-filesize-approx -F -- BaW_jenozKc
[debug] Command-line config: ['-v', '--impersonate=', '--youtube-skip-hls-manifest', '--compat-options', 'list-formats,format-sort,manifest-filesize-approx', '-F', '--', 'BaW_jenozKc']
[debug] yt-dlp version nightly@2024.07.10.232707 from yt-dlp/yt-dlp-nightly-builds [705f5b84d] (win_exe)
[debug] Compatibility options: format-sort, list-formats, manifest-filesize-approx
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-7-6.1.7601-SP1 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.07.04, curl_cffi-0.7.0, mutagen-1.47.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.2, websockets-12.0
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Extractor Plugins: AGB (YoutubeIE), Youtube_AgeGateBypassIE
[debug] Loaded 1835 extractors
[youtube+AGB] Extracting URL: BaW_jenozKc
[youtube+AGB] BaW_jenozKc: Downloading webpage

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
```

**Comment by bashonly** [comment]
Can you confirm that the problem does not exist in https://github.com/yt-dlp/yt-dlp-nightly-builds/releases/tag/2024.07.09.232843 ?

```
yt-dlp --update-to nightly@2024.07.09.232843
```

**Comment by bashonly** [comment]
Can you confirm that the problem does not exist in https://github.com/yt-dlp/yt-dlp-nightly-builds/releases/tag/2024.07.09.232843 ?

```
yt-dlp --update-to nightly@2024.07.09.232843
```

**Comment by barkoder** [comment]
Sorry I should have mentioned. I was using in fact using nightly@2024.07.09.232843 before the update.

**WORKS - nightly@2024.07.09.232843 with curl_cffi-0.5.10**

`$ yt-dlp.exe -v --no-config --proxy socks5h://127.0.0.1:9050 --impersonate="Chrome-110:Windows-10" -F BaW_jenozKc`

    [debug] Command-line config: ['-v', '--no-config', '--proxy', 'socks5h://127.0.0.1:9050', '--impersonate=Chrome-110:Windows-10', '-F', 'BaW_jenozKc']
    [debug] yt-dlp version nightly@2024.07.09.232843 from yt-dlp/yt-dlp-nightly-builds [d2189d3d3] (win_exe)
    [debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-7-6.1.7601-SP1 (OpenSSL 1.1.1k  25 Mar 2021)
    [debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.07.04, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.2, websockets-12.0
    [debug] Proxy map: {'all': 'socks5h://127.0.0.1:9050'}
    [debug] Request Handlers: urllib, requests, websockets, curl_cffi
    [debug] Loaded 1834 extractors
    [youtube] Extracting URL: BaW_jenozKc
    [youtube] BaW_jenozKc: Downloading webpage
    [youtube] BaW_jenozKc: Downloading ios player API JSON
    [debug] Loading youtube-nsig.9ed4a7e1 from cache
    [debug] [youtube] Decrypted nsig CxdNN_Y8acviGKn0 => 5ehLo-AIKNuZrg
    [youtube] BaW_jenozKc: Downloading m3u8 information
    [debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
    [debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
    [info] Available formats for BaW_jenozKc:
    ID      EXT   RESOLUTION FPS CH |   FILESIZE  TBR PROTO | VCODEC         VBR ACODEC      ABR ASR MORE INFO
    --------------------------------------------------------------------------------------------------------------------------------
    sb0     mhtml 48x27       10    |                 mhtml | images                                 storyboard
    233     mp4   audio only        |                 m3u8  | audio only         unknown             [en] Default, IOS
    234     mp4   audio only        |                 m3u8  | audio only         unknown             [en] Default, IOS
    139-drc m4a   audio only      2 |   60.21KiB  49k https | audio only         mp4a.40.5   49k 22k [en] low, DRC, IOS, m4a_dash
    139     m4a   audio only      2 |   60.20KiB  49k https | audio only         mp4a.40.5   49k 22k [en] low, IOS, m4a_dash
    140-drc m4a   audio only      2 |  157.14KiB 130k https | audio only         mp4a.40.2  130k 44k [en] medium, DRC, IOS, m4a_dash
    140     m4a   audio only      2 |  157.16KiB 130k https | audio only         mp4a.40.2  130k 44k [en] medium, IOS, m4a_dash
    269     mp4   256x144     30    | ~ 83.18KiB  68k m3u8  | avc1.4D400C    68k video only          IOS
    160     mp4   256x144     30    |   14.93KiB  12k https | avc1.4D400C    12k video only          144p, IOS, mp4_dash
    230     mp4   640x360     30    | ~205.33KiB 168k m3u8  | avc1.4D401E   168k video only          IOS
    134     mp4   640x360     30    |   29.39KiB  24k https | avc1.4D401E    24k video only          360p, IOS, mp4_dash
    18      mp4   640x360     30  2 |  199.11KiB 165k https | avc1.42001E        mp4a.40.2       44k [en] 360p, WEB
    605     mp4   640x360     30    | ~255.88KiB 210k m3u8  | vp09.00.21.08 210k video only          IOS
    232     mp4   1280x720    30    | ~247.03KiB 202k m3u8  | avc1.4D401F   202k video only          IOS
    136     mp4   1280x720    30    |   59.04KiB  49k https | avc1.4D401F    49k video only          720p, IOS, mp4_dash
    270     mp4   1920x1080   30    | ~484.67KiB 397k m3u8  | avc1.640028   397k video only          IOS
    137     mp4   1920x1080   30    |  286.74KiB 239k https | avc1.640028   239k video only          1080p, IOS, mp4_dash

**FAILS - nightly@2024.07.10.232707 with curl_cffi-0.7.0**

`$ yt-dlp.exe -v --no-config --proxy socks5h://127.0.0.1:9050 --impersonate="Chrome-110:Windows-10" -F BaW_jenozKc`

    [debug] Command-line config: ['-v', '--no-config', '--proxy', 'socks5h://127.0.0.1:9050', '--impersonate=Chrome-110:Windows-10', '-F', 'BaW_jenozKc']
    [debug] yt-dlp version nightly@2024.07.10.232707 from yt-dlp/yt-dlp-nightly-builds [705f5b84d] (win_exe)
    [debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-7-6.1.7601-SP1 (OpenSSL 1.1.1k  25 Mar 2021)
    [debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.07.04, curl_cffi-0.7.0, mutagen-1.47.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.2, websockets-12.0
    [debug] Proxy map: {'all': 'socks5h://127.0.0.1:9050'}
    [debug] Request Handlers: urllib, requests, websockets, curl_cffi
    [debug] Extractor Plugins: AGB (YoutubeIE), Youtube_AgeGateBypassIE
    [debug] Loaded 1835 extractors
    [youtube+AGB] Extracting URL: BaW_jenozKc
    [youtube+AGB] BaW_jenozKc: Downloading webpage
    
    This application has requested the Runtime to terminate it in an unusual way.
    Please contact the application's support team for more information.

I can also reproduce this with the pypi version.

**WORKS - nightly@2024.07.10.232707(pip) with curl_cffi version 0.5.10**

`$ pip --proxy socks5h://127.0.0.1:9050 install -U --pre yt-dlp[default]`

    $ yt-dlp.exe --rm-cache-dir -v --no-config --proxy socks5h://127.0.0.1:9050 --impersonate="Chrome-110:Windows-10" -F BaW_jenozKc
    [debug] Command-line config: ['--rm-cache-dir', '-v', '--no-config', '--proxy','socks5h://127.0.0.1:9050', '--impersonate=Chrome-110:Windows-10', '-F', 'BaW_jenozKc']
    [debug] yt-dlp version nightly@2024.07.10.232707 from yt-dlp/yt-dlp-nightly-builds [705f5b84d] (pip)
    [debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-7-6.1.7601-SP1 (OpenSSL 1.1.1k  25 Mar 2021)
    [debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, curl_cffi-0.5.10, mutagen-1.46.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.1, websockets-12.0
    [debug] Proxy map: {'all': 'socks5h://127.0.0.1:9050'}
    [debug] Request Handlers: urllib, requests, websockets, curl_cffi
    [debug] Extractor Plugins: AGB (YoutubeIE)
    [debug] Plugin directories: ['C:\\Users\\USERNAME\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\yt_dlp_plugins']
    [debug] Loaded 1834 extractors
    Removing cache dir V:\MOBAXT~1\home/.cache\yt-dlp ...
    [youtube+AGB] Extracting URL: BaW_jenozKc
    [youtube+AGB] BaW_jenozKc: Downloading webpage
    [youtube+AGB] BaW_jenozKc: Downloading ios player API JSON
    [youtube+AGB] BaW_jenozKc: Downloading player 9ed4a7e1
    [debug] Saving youtube-nsig.9ed4a7e1 to cache
    [debug] [youtube+AGB] Decrypted nsig Smjhobqj4JUH99Fn => gskrwKTpHn9axw
    [youtube+AGB] BaW_jenozKc: Downloading m3u8 information
    [debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
    [debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
    [info] Available formats for BaW_jenozKc:
    ID      EXT   RESOLUTION FPS CH |   FILESIZE  TBR PROTO | VCODEC         VBR ACODEC      ABR ASR MORE INFO
    --------------------------------------------------------------------------------------------------------------------------------
    sb0     mhtml 48x27       10    |                 mhtml | images                 storyboard
    233     mp4   audio only        |                 m3u8  | audio only         unknown             [en] Default, IOS
    234     mp4   audio only        |                 m3u8  | audio only         unknown             [en] Default, IOS
    139-drc m4a   audio only      2 |   60.21KiB  49k https | audio only         mp4a.40.5   49k 22k [en] low, DRC, IOS, m4a_dash
    139     m4a   audio only      2 |   60.20KiB  49k https | audio only         mp4a.40.5   49k 22k [en] low, IOS, m4a_dash
    140-drc m4a   audio only      2 |  157.14KiB 130k https | audio only         mp4a.40.2  130k 44k [en] medium, DRC, IOS, m4a_dash
    140     m4a   audio only      2 |  157.16KiB 130k https | audio only         mp4a.40.2  130k 44k [en] medium, IOS, m4a_dash
    269     mp4   256x144     30    | ~ 83.18KiB  68k m3u8  | avc1.4D400C    68k video only          IOS
    160     mp4   256x144     30    |   14.93KiB  12k https | avc1.4D400C    12k video only          144p, IOS, mp4_dash
    230     mp4   640x360     30    | ~205.33KiB 168k m3u8  | avc1.4D401E   168k video only          IOS
    134     mp4   640x360     30    |   29.39KiB  24k https | avc1.4D401E    24k video only          360p, IOS, mp4_dash
    18      mp4   640x360     30  2 |  199.11KiB 165k https | avc1.42001E        mp4a.40.2       44k [en] 360p, WEB
    605     mp4   640x360     30    | ~255.88KiB 210k m3u8  | vp09.00.21.08 210k video only          IOS
    232     mp4   1280x720    30    | ~247.03KiB 202k m3u8  | avc1.4D401F   202k video only          IOS
    136     mp4   1280x720    30    |   59.04KiB  49k https | avc1.4D401F    49k video only          720p, IOS, mp4_dash
    270     mp4   1920x1080   30    | ~484.67KiB 397k m3u8  | avc1.640028   397k video only          IOS
    137     mp4   1920x1080   30    |  286.74KiB 239k https | avc1.640028   239k video only          1080p, IOS, mp4_dash

**FAILS - nightly@2024.07.10.232707(pip) with curl_cffi version 0.7.0**

`$ pip --proxy socks5h://127.0.0.1:9050 install -U curl_cffi==0.7.0`

    $ yt-dlp.exe -v --no-config --proxy socks5h://127.0.0.1:9050 --impersonate="Chrome-110:Windows-10" -F BaW_jenozKc
    [debug] Command-line config: ['-v', '--no-config', '--proxy', 'socks5h://127.0.0.1:9050', '--impersonate=Chrome-110:Windows-10', '-F', 'BaW_jenozKc']
    [debug] yt-dlp version nightly@2024.07.10.232707 from yt-dlp/yt-dlp-nightly-builds [705f5b84d] (pip)
    [debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-7-6.1.7601-SP1 (OpenSSL 1.1.1k  25 Mar 2021)
    [debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2024.07.04, curl_cffi-0.7.0, mutagen-1.46.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.1,websockets-12.0
    [debug] Proxy map: {'all': 'socks5h://127.0.0.1:9050'}
    [debug] Request Handlers: urllib, requests, websockets, curl_cffi
    [debug] Extractor Plugins: AGB (YoutubeIE)
    [debug] Plugin directories: ['C:\\Users\\USERNAME\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\yt_dlp_plugins']
    [debug] Loaded 1834 extractors
    [youtube+AGB] Extracting URL: BaW_jenozKc
    [youtube+AGB] BaW_jenozKc: Downloading webpage
    
    This application has requested the Runtime to terminate it in an unusual way.
    Please contact the application's support team for more information.

That's how I knew the problem had something to do with curl_cffi version 0.7.0

**Comment by bashonly** [comment]
pip installation is affected too, hmm. Seems like it could be a problem with `curl_cffi` and older versions of Windows (e.g. 7)

**Comment by bashonly** [comment]
Could you try running this script on your Windows 7 system with `curl_cffi` **0.7.0** installed and share the output:

```py
import curl_cffi

print(curl_cffi.__version__)
session = curl_cffi.requests.Session()
response = session.get('https://www.youtube.com/watch?v=BaW_jenozKc', impersonate='chrome110')
print(response.status_code)
```

(you can copy/paste the above code, save it to `curlcffitest.py`, and run with `python curlcffitest.py`)

**Comment by barkoder** [comment]
> Could you try running this script on your Windows 7 system with curl_cffi 0.7.0 installed and share the output:

    0.7.0
    Traceback (most recent call last):
      File "curlcffitest.py", line 4, in <module>
        session = curl_cffi.requests.Session()
    AttributeError: module 'curl_cffi' has no attribute 'requests'

**Comment by bashonly** [comment]
argh my bad

try this one

```py
import curl_cffi
import curl_cffi.requests

print(curl_cffi.__version__)
session = curl_cffi.requests.Session()
response = session.get('https://www.youtube.com/watch?v=BaW_jenozKc', impersonate='chrome110')
print(response.status_code)
```

**Comment by barkoder** [comment]
0.7.0
    
    This application has requested the Runtime to terminate it in an unusual way.
    Please contact the application's support team for more information.

**Comment by bashonly** [comment]
The next nightly release (publishing in about 3.5 hours) should resolve this issue

**Comment by barkoder** [comment]
Now with [0.7.0 curl-impersonate seemingly fixed on Windows 7](https://github.com/lexiforest/curl-impersonate/issues/72), I would love to test yt-dlp with newer curl_cffi on Windows 7.
