### ISSUE TITLE
Long Start-Up Time for `yt-dlp_macos` (nightly)

### ISSUE THREAD

**Issue by NoNoNo** [yt-dlp/yt-dlp#10425]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

`yt-dlp_macos` (nightly) takes 45 s to load.

https://github.com/yt-dlp/yt-dlp-nightly-builds/releases/download/2024.07.10.232707/yt-dlp_macos

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
❯ time yt-dlp -vU --ignore-config
[debug] Command-line config: ['-vU', '--ignore-config']
[debug] Encodings: locale utf-8, fs utf-8, pref utf-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.07.10.232707 from yt-dlp/yt-dlp-nightly-builds [705f5b84d] (darwin_exe)
[debug] Python 3.12.4 (CPython x86_64 64bit) - macOS-14.5-x86_64-i386-64bit (OpenSSL 3.0.13 30 Jan 2024)
[debug] exe versions: ffmpeg git-2024-07-04-bef77c6c (fdk,setts), ffprobe git-2024-07-04-bef77c6c, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.07.04, curl_cffi-0.7.0, mutagen-1.47.0, requests-2.32.3, sqlite3-3.45.3, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1834 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.07.10.232707 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.07.10.232707 from yt-dlp/yt-dlp-nightly-builds)
yt-dlp -vU --ignore-config  1.18s user 1.38s system 5% cpu 45.165 total

took 45s
```

**Comment by bashonly** [comment]
Can you try https://github.com/yt-dlp/yt-dlp-nightly-builds/releases/tag/2024.07.09.232843 ?

```
yt-dlp --update-to nightly@2024.07.09.232843
```

**Comment by NoNoNo** [comment]
`2024.07.09.232843` loads in 26 s:

```
❯ time ./yt-dlp_macos -v --ignore-config
[debug] Command-line config: ['-v', '--ignore-config']
[debug] Encodings: locale utf-8, fs utf-8, pref utf-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.07.09.232843 from yt-dlp/yt-dlp-nightly-builds [d2189d3d3] (darwin_exe)
[debug] Python 3.12.4 (CPython x86_64 64bit) - macOS-14.5-x86_64-i386-64bit (OpenSSL 3.0.13 30 Jan 2024)
[debug] exe versions: ffmpeg git-2024-07-04-bef77c6c (fdk,setts), ffprobe git-2024-07-04-bef77c6c, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.07.04, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.45.3, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1834 extractors

Usage: yt-dlp_macos [OPTIONS] URL [URL...]

yt-dlp_macos: error: You must provide at least one URL.
Type yt-dlp --help to see a list of all options.
./yt-dlp_macos -v --ignore-config  1.09s user 1.12s system 8% cpu 25.934 total
```

**Comment by NoNoNo** [comment]
### Two random past versions

#### `2024.05.17.232726` loads in 45 s:

```
❯ time ./yt-dlp_macos -v --ignore-config
[debug] Command-line config: ['-v', '--ignore-config']
[debug] Encodings: locale utf-8, fs utf-8, pref utf-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.05.17.232726 from yt-dlp/yt-dlp-nightly-builds [12d8ea824] (darwin_exe)
[debug] Python 3.12.1 (CPython x86_64 64bit) - macOS-14.5-x86_64-i386-64bit (OpenSSL 3.0.11 19 Sep 2023)
[debug] exe versions: ffmpeg git-2024-07-04-bef77c6c (fdk,setts), ffprobe git-2024-07-04-bef77c6c, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.02.02, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.31.0, sqlite3-3.43.1, urllib3-2.2.1, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1803 extractors

Usage: yt-dlp_macos [OPTIONS] URL [URL...]

yt-dlp_macos: error: You must provide at least one URL.
Type yt-dlp --help to see a list of all options.
./yt-dlp_macos -v --ignore-config  1.14s user 1.46s system 5% cpu 44.935 total

took 45s
```

#### `2024.01.22.232713` loads in 39 s:

```
❯ time ./yt-dlp_macos -v --ignore-config
[debug] Command-line config: ['-v', '--ignore-config']
[debug] Encodings: locale utf-8, fs utf-8, pref utf-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.01.22.232713 from yt-dlp/yt-dlp-nightly-builds [a40b0070c] (darwin_exe)
[debug] Python 3.12.1 (CPython x86_64 64bit) - macOS-14.5-x86_64-i386-64bit (OpenSSL 3.0.11 19 Sep 2023)
[debug] exe versions: ffmpeg git-2024-07-04-bef77c6c (fdk,setts), ffprobe git-2024-07-04-bef77c6c, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2023.11.17, mutagen-1.47.0, requests-2.31.0, sqlite3-3.43.1, urllib3-2.1.0, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1819 extractors

Usage: yt-dlp_macos [OPTIONS] URL [URL...]

yt-dlp_macos: error: You must provide at least one URL.
Type yt-dlp --help to see a list of all options.
./yt-dlp_macos -v --ignore-config  0.81s user 1.14s system 5% cpu 38.933 total

took 39s
```

**Comment by bashonly** [comment]
> 2024.05.17.232726 loads in 45 s

The startup time seems to vary a bit randomly then, and doesn't seem to be caused by any changes within the past 2 months. Was there ever a version of the `yt-dlp_macos` executable that didn't give you these long startup times?

**Comment by CrushedAsian255** [comment]
This could be caused by MacOS Notarisation scanning all the files in the folder, does this continue to happen after the first  time(s) you run it?

**Comment by NoNoNo** [comment]
Yes, did run multiple times… Somehow the `2024.07.11.232833` version did get faster with 21 s:

```
❯ /usr/bin/time -l -h -p yt-dlp -v --ignore-config
[debug] Command-line config: ['-v', '--ignore-config']
[debug] Encodings: locale utf-8, fs utf-8, pref utf-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.07.11.232833 from yt-dlp/yt-dlp-nightly-builds [cc1a3098c] (darwin_exe)
[debug] Python 3.12.4 (CPython x86_64 64bit) - macOS-14.5-x86_64-i386-64bit (OpenSSL 3.0.13 30 Jan 2024)
[debug] exe versions: ffmpeg git-2024-07-04-bef77c6c (fdk,setts), ffprobe git-2024-07-04-bef77c6c, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.07.04, curl_cffi-0.7.0, mutagen-1.47.0, requests-2.32.3, sqlite3-3.45.3, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1834 extractors

Usage: yt-dlp [OPTIONS] URL [URL...]

yt-dlp: error: You must provide at least one URL.
Type yt-dlp --help to see a list of all options.
real 21.59
user 1.01
sys 1.13
            63660032  maximum resident set size
                   0  average shared memory size
                   0  average unshared data size
                   0  average unshared stack size
               47923  page reclaims
                2139  page faults
                   0  swaps
                   0  block input operations
                   0  block output operations
                   0  messages sent
                   0  messages received
                   0  signals received
                 832  voluntary context switches
                1106  involuntary context switches
          7183303816  instructions retired
          4031076196  cycles elapsed
              851968  peak memory footprint

took 21s
```

**Comment by NoNoNo** [comment]
> The startup time seems to vary a bit randomly then, and doesn't seem to be caused by any changes within the past 2 months. Was there ever a version of the `yt-dlp_macos` executable that didn't give you these long startup times?

I don’t know of a version of the `yt-dlp_macos` executable that does not have these long startup times; first-time user of the executable, used to run the py script – this runs in under 2 s:

```
❯ /usr/bin/time -l -h -p /usr/local/bin/yt-dlp -v --ignore-config
[debug] Command-line config: ['-v', '--ignore-config']
[debug] Encodings: locale utf-8, fs utf-8, pref utf-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.07.11.232833 from yt-dlp/yt-dlp-nightly-builds [cc1a3098c] (zip)
[debug] Python 3.12.4 (CPython x86_64 64bit) - macOS-14.5-x86_64-i386-64bit (OpenSSL 3.3.1 4 Jun 2024)
[debug] exe versions: ffmpeg git-2024-07-04-bef77c6c (fdk,setts), ffprobe git-2024-07-04-bef77c6c, rtmpdump 2.4
[debug] Optional libraries: certifi-2024.07.04, curl_cffi-0.7.0, pycrypto-3.20.0, sqlite3-3.46.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, curl_cffi
[debug] Loaded 1834 extractors

Usage: yt-dlp [OPTIONS] URL [URL...]

yt-dlp: error: You must provide at least one URL.
Type yt-dlp --help to see a list of all options.
real 1.99
user 1.32
sys 0.30
           110317568  maximum resident set size
                   0  average shared memory size
                   0  average unshared data size
                   0  average unshared stack size
               55624  page reclaims
                2248  page faults
                   0  swaps
                   0  block input operations
                   0  block output operations
                   0  messages sent
                   0  messages received
                   0  signals received
                 293  voluntary context switches
                1500  involuntary context switches
          7171460155  instructions retired
          4541697620  cycles elapsed
            66691072  peak memory footprint
```

**Comment by bashonly** [comment]
> This could be caused by MacOS Notarisation scanning all the files in the folder, does this continue to happen after the first time(s) you run it?

Yeah, this is my best guess too: some sort of Apple security scanning is happening.

`yt-dlp_macos` is a pyinstaller-bundled "onefile" executable, which means every time you execute it, it first needs to unpack its contents (~30-50MB of shared libraries and script files) into a temporary directory before yt-dlp itself is executed. These temp files are cleaned up once the executable has finished, so the security scanning would be invoked on every run, not just the first run.

An alternative would be the `yt-dlp_macos.zip` "onedir" build, where you unpack it yourself into a directory upon installation and no further unpacking is ever needed. The downside with the onedir build is that you can't use `-U`/`--update-to`; you would need to manually download updates from Github.

Another alternative is installing with [homebrew](https://brew.sh). While not an official channel for yt-dlp releases, brew is a very well-managed project that is quick to push updates of yt-dlp. (This is not a viable option if you require yt-dlp to have browser impersonation support via `curl_cffi`, though.)

**Comment by NoNoNo** [comment]
Yeah, makes sense.

So, `yt-dlp_macos` is kind of useless?!

**Comment by seproDev** [comment]
> So, `yt-dlp_macos` is kind of useless?!

There is something about your machine/configuration that is different. You were the first person to report such long startup times I am aware of. On my Mac, it takes ~1.5 seconds.

**Comment by CrushedAsian255** [comment]
I personally just use pip install yt-dlp —pre -U

**Comment by bashonly** [comment]
@NoNoNo just curious, did you make the yt-dlp binary executable by running `chmod +x` ?

**Comment by Y3K** [comment]
Hello, this is happening for me as well.

I updated `yt-dlp` after a long time (due bad SSL certs for YouTube) and whenever I execute the new version it takes about ~10 seconds when it used to be instant-ish before:

```
time yt-dlp --version
2024.08.01
yt-dlp --version  0.72s user 0.21s system 8% cpu 10.705 total
```

Thank you.

**Comment by bashonly** [comment]
@Y3K what was the last version that didn't have the long startup time?

**Comment by Y3K** [comment]
Hello @bashonly , unfortunately I'm not sure and I deleted the previous binary, however I'd ballpark it around 6 months old.

**Comment by bashonly** [comment]
A macOS user on discord was kind enough to try and "bisect" this for us, and found that the slow startup time presented for them in every release going back to `2022.04.08` (at which point we gave up).

Every issue that's been opened on the [pyinstaller tracker](https://github.com/pyinstaller/pyinstaller/issues) about slow startup time (and there are several) has always reached a conclusion of "antivirus/security scanning interference" (or else "don't use `--onefile`", which is not a solution here).

**Comment by antdude** [comment]
Is there no way to whitelist yt-dlp to MacOS Notarisation scanning?

**Comment by boosh** [comment]
Happening to me on Sequoia 15.5, no extra AV/Security software.

```
time yt-dlp --version
2025.07.21

real	0m18.030s
user	0m0.606s
sys	0m0.218s
````

**Comment by ghost** [comment]
> Is there no way to whitelist yt-dlp to MacOS Notarisation scanning?
System Settings > Privacy & Security > Developer Tools > [+] > point at your yt-dlp  
Enabling this option for yt-dlp should minimize the start time., it did for me.

Edit: this is WEIRD! 
I've enabled the Dev option for YT-DLP only once, just for testing purposes. It did indeed cut the initial startup time from about 5 seconds to about an instant. 
BUT!
I've then disabled this option. 
And now, when running yt-dlp, the initial lag is...gone? 
Apparently adding the app there just once and then disabling the option for it resolves the problem?
Removing yt-dlp from that list afterwards changed nothing - it still launches instantly and without delays.

From what I recall, there is a terminal command that enables the Dev Tools option and it should also be possible to add yt-dlp to that list via another terminal command?
Or at least open the System Settings > S&P > Dev Tools window and notify the user that adding yt-dlp to Dev Tools and enabling > disabling the option will resolve the delay?

**Comment by antdude** [comment]
Weird. "System Settings > Privacy & Security > Developer Tools > [+] > point at your yt-dlp" trick didn't help for me. I still had to wait like 30 seconds with my downloaded https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp_macos file in updated macOS Ventura v13.7.6, with my admin level account, in a 2020 13" Intel MBP. :(

**Comment by relikd** [comment]
Dev Tools did **not** work for me either. Also, I doubt the delay has anything to do with Notarization. That is usually a one-time thing and results are cached somehow. Somehow Notarization knows about previously uninstalled and reinstalled apps / binaries. Install via pip does not have this delay but that was expected.

**Comment by bashonly** [comment]
the yt-dlp_macos binary has never been notarized

**Comment by relikd** [comment]
yes, I know, but the Notarization service on macOS still runs and tries to get information. I was refering to the "antivirus/security scanning interference" statement just assuming the Notarization service is what was meant. idk

**Comment by bashonly** [comment]
> That is usually a one-time thing and results are cached somehow

Every time you run `yt-dlp_macos`, it extracts its contents into a new temp directory. It's possible that there is no cache hit because the filepaths and attributes are different every time

**Comment by relikd** [comment]
But the hash of the files and filenames stay the same. If you re-install an app it doesnt matter whether its in the Downloads folder or in /Applications, yet macOS still knows its the same app. I just assume its the same for binaries.

**Comment by bashonly** [comment]
It's still quite a lot of files to hash every time. All the chonky dynamic libraries, and `yt_dlp/extractor` alone is 1000+ files.

**Comment by msikma** [comment]
Strangely, for me the trick of adding yt-dlp to Privacy & Security -> Developer Tools did work. Then I tried to deactivate the fix to see if I could consistently reproduce it, but now I can't *unfix* it.

Previously, on my Macbook Air M1, the stable@2025.10.22 version would take about 9.5s-10s on each usage. The regular yt-dlp_macos binary because I like the ease of self-update.

What I did is I added it to Developer Tools (System Settings, Privacy & Security, Developer Tools — press + and add the yt-dlp binary). However, I also noticed that Terminal wasn't set as developer tool, so I added that as well. After that, it went down to a reasonable time:

```
$ time yt-dlp -v
[debug] Command-line config: ['-v']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2025.11.03.233024 from yt-dlp/yt-dlp-nightly-builds [ffb7b7f44] (darwin_exe)
[debug] Python 3.13.9 (CPython arm64 64bit) - macOS-26.0-arm64-arm-64bit-Mach-O (OpenSSL 3.0.18 30 Sep 2025)
[debug] exe versions: ffmpeg 7.1.1 (setts), ffprobe 7.1.1
[debug] Optional libraries: Cryptodome-3.23.0, brotli-1.1.0, certifi-2025.10.05, curl_cffi-0.13.0, mutagen-1.47.0, requests-2.32.5, sqlite3-3.50.4, urllib3-2.5.0, websockets-15.0.1, yt_dlp_ejs-0.3.0
[debug] JS runtimes: deno-2.5.6
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Plugin directories: none
[debug] Loaded 1842 extractors

Usage: yt-dlp [OPTIONS] URL [URL...]

yt-dlp: error: You must provide at least one URL.
Type yt-dlp --help to see a list of all options.

________________________________________________________
Executed in  754.36 millis    fish           external
   usr time  535.30 millis    0.30 millis  535.00 millis
   sys time  187.42 millis    1.08 millis  186.34 millis
```

However, if I now uncheck either item in Developer Tools, it no longer goes back to the longer startup times. So I'm not sure what even happened. This needs someone to do a really deep dive. But I would suggest trying the method of adding it as Developer Tool, possibly with the Terminal as well.

**Comment by norey** [comment]
Adding both iTerm and yt-dlp to Developer Tools worked for me. Down from 35 secs to 2 secs.

Before:

```
❯ time yt-dlp -v
[debug] Command-line config: ['-v']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2026.03.03 from yt-dlp/yt-dlp [2ecc4c3bc] (darwin_exe)
[debug] Python 3.14.3 (CPython x86_64 64bit) - macOS-13.7.8-x86_64-i386-64bit-Mach-O (OpenSSL 3.0.18 30 Sep 2025)
[debug] exe versions: ffmpeg 8.0.1-tessus (setts), ffprobe 8.0.1-tessus, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.23.0, brotli-1.2.0, certifi-2026.02.25, curl_cffi-0.13.0, mutagen-1.47.0, requests-2.32.5, sqlite3-3.50.4, urllib3-2.6.3, websockets-16.0, yt_dlp_ejs-0.5.0
[debug] JS runtimes: deno-2.5.6
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Plugin directories: none
[debug] Loaded 1864 extractors

Usage: yt-dlp [OPTIONS] URL [URL...]

yt-dlp: error: You must provide at least one URL.
Type yt-dlp --help to see a list of all options.
yt-dlp -v  1.49s user 0.60s system 6% cpu 34.903 total
```

After:

```
❯ time yt-dlp -v
[debug] Command-line config: ['-v']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2026.03.03 from yt-dlp/yt-dlp [2ecc4c3bc] (darwin_exe)
[debug] Python 3.14.3 (CPython x86_64 64bit) - macOS-13.7.8-x86_64-i386-64bit-Mach-O (OpenSSL 3.0.18 30 Sep 2025)
[debug] exe versions: ffmpeg 8.0.1-tessus (setts), ffprobe 8.0.1-tessus, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.23.0, brotli-1.2.0, certifi-2026.02.25, curl_cffi-0.13.0, mutagen-1.47.0, requests-2.32.5, sqlite3-3.50.4, urllib3-2.6.3, websockets-16.0, yt_dlp_ejs-0.5.0
[debug] JS runtimes: deno-2.5.6
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Plugin directories: none
[debug] Loaded 1864 extractors

Usage: yt-dlp [OPTIONS] URL [URL...]

yt-dlp: error: You must provide at least one URL.
Type yt-dlp --help to see a list of all options.
yt-dlp -v  1.40s user 0.53s system 93% cpu 2.061 total
```

This is on a 2017 intel Macbookpro.

**Comment by thunderstatic** [comment]
Is it possible to reopen this issue?
I’m still seeing ~15–20s startup time even for yt-dlp --version on macOS (standalone binary, arm64).
```
time yt-dlp -v --version
2026.03.17
yt-dlp -v --version  1,12s user 0,33s system 8% cpu 17,925 total
```

**Comment by bashonly** [comment]
> Is it possible to reopen this issue?

IMO it wouldn't be appropriate to reopen the issue, since there isn't really anything that can be done about it on yt-dlp's end.

As a user, you can do this: https://github.com/yt-dlp/yt-dlp/issues/10425#issuecomment-3485768912

Alternatively, you can use the `yt-dlp_macos.zip` release instead of the single-file executable.

**Comment by thunderstatic** [comment]
@bashonly yeah, the workaround helped.
I was just wondering if there’s anything that could be improved on the tool side, but I get it.
Thanks for the quick response tho!

**Comment by xeptore** [comment]
For me, it didn't require adding `yt-dlp`, nor the terminal application to Developer Tools, just using `yt-dlp_macos.zip` resolved the issue:
```zsh
λ ~ printf '%s\n' \
  "macOS: $(sw_vers -productVersion) ($(sw_vers -buildVersion))" \
  "Architecture: $(uname -m)" \
  "Kernel: $(uname -r)"
macOS: 26.5.2 (25F84)
Architecture: arm64
Kernel: 25.5.0
λ ~ time yt-dlp --version
2026.07.04
yt-dlp --version  0.28s user 0.04s system 98% cpu 0.329 total
``

**Comment by PacoH** [comment]
I added nightly@2026.08.18.122307 to Developer Tools but it still didn't run any faster. I finally had to enable Terminal which was off and now it runs as fast as the standard build.
