### ISSUE TITLE
Why YT extractor is now youtube+AGB?

### ISSUE THREAD

**Issue by bonacker1** [yt-dlp/yt-dlp#10428]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I've updated to nightly@2024.07.10.232707. I see something unusual that I don't understand.

The extractor for all YT videos is now "youtube+AGB." Why and what is AGB? I think AGB is a workaround  that is supposed to get around YT's age restricted videos by using a proxy to a fake account that identifies as older than 13 or whatever. Or something like that. What is it actually and why is it being added to the extractor for ALL YT vids? I'm sure there's a good reason. I'd just like to know what it is.

On another note, I am extremely appreciative of those who so quickly update yt-dlp. The other day,  it looked like YT's formats were suddenly all video only and audio only. Gone was good old "18." While I was still reading about PhantomJS as a fix for missing formats, a new yt-dlp version  fixed the missing format problem. YT videos were also intermittently defaulting to the generic extractor and failing. This too was quickly fixed in an update.

This is just a great bunch of volunteer coders! Thanks for all your work. 

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
The AgeGateBypass extractor plugin overrides the Youtube extractor on every run of yt-dlp. This is how the yt-dlp plugin system works. The bypass mechanism itself is only triggered when necessary.
