### ISSUE TITLE
support for the site mfcamhub.com

### ISSUE THREAD

**Issue by nhnsn2** [yt-dlp/yt-dlp#10449]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Chile

### Example URLs

-Single video: https://mfcamhub.com/videos/107567/watch-luxuryxxo-new-porn-video-chaturbate-tattooedgirl-humiliation-poledance-goth/
-Single video: https://mfcamhub.com/videos/107796/watch-berylfane-hot-porn-video-stripchat-dirty-talk-new-new-brunettes-striptease-white-affordable-cam2cam/

### Provide a description that is worded well enough to be understood

The issue is that yt-dlp is unable to download any videos from the site mfcamhub.com(I've tried with several URLs) , since it runs into an error: "Unable to extract flashvars". The proposed solution is that yt-dlp starts supporting the download of videos from mfcamhub.com

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://mfcamhub.com/videos/107796/watch-berylfane-hot-porn-video-stripchat-dirty-talk-new-new-brunettes-striptease-white-affordable-cam2cam/']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version master@2024.07.12.193440 from yt-dlp/yt-dlp-master-builds [644d84d77] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 2024-06-13-git-0060a368b1-full_build-www.gyan.dev (setts), ffprobe 2024-06-13-git-0060a368b1-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.07.04, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1834 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-master-builds/releases/latest
Latest version: master@2024.07.12.193440 from yt-dlp/yt-dlp-master-builds
yt-dlp is up to date (master@2024.07.12.193440 from yt-dlp/yt-dlp-master-builds)
[generic] Extracting URL: https://mfcamhub.com/videos/107796/watch-berylfane-hot-porn-video-stripchat-dirty-talk-new-new-brunettes-striptease-white-affordable-cam2cam/
[generic] watch-berylfane-hot-porn-video-stripchat-dirty-talk-new-new-brunettes-striptease-white-affordable-cam2cam: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] watch-berylfane-hot-porn-video-stripchat-dirty-talk-new-new-brunettes-striptease-white-affordable-cam2cam: Extracting information
[debug] Looking for embeds
[debug] Identified a KVS Player
ERROR: [generic] Unable to extract flashvars; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 740, in extract
  File "yt_dlp\extractor\generic.py", line 2516, in _real_extract
  File "yt_dlp\extractor\generic.py", line 2645, in _extract_embeds
  File "yt_dlp\extractor\generic.py", line 2290, in _extract_kvs
  File "yt_dlp\extractor\common.py", line 1347, in _search_json
  File "yt_dlp\extractor\common.py", line 1333, in _search_regex
```

**Comment by bashonly** [comment]
Piracy sites are not supported

**Comment by GITangry** [comment]
> ### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE
> * [x]  I understand that I will be **blocked** if I _intentionally_ remove or skip any mandatory* field
> 
> ### Checklist
> * [x]  I'm reporting a new site support request
> * [x]  I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
> * [x]  I've checked that all provided URLs are playable in a browser with the same IP and same login details
> * [x]  I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
> * [x]  I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
> * [x]  I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
> * [x]  I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required
> 
> ### Region
> Chile
> 
> ### Example URLs
> -Single video: https://mfcamhub.com/videos/107567/watch-luxuryxxo-new-porn-video-chaturbate-tattooedgirl-humiliation-poledance-goth/ -Single video: https://mfcamhub.com/videos/107796/watch-berylfane-hot-porn-video-stripchat-dirty-talk-new-new-brunettes-striptease-white-affordable-cam2cam/
> 
> ### Provide a description that is worded well enough to be understood
> The issue is that yt-dlp is unable to download any videos from the site mfcamhub.com(I've tried with several URLs) , since it runs into an error: "Unable to extract flashvars". The proposed solution is that yt-dlp starts supporting the download of videos from mfcamhub.com
> 
> ### Provide verbose output that clearly demonstrates the problem
> * [x]  Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
> * [x]  If using API, add `'verbose': True` to `YoutubeDL` params instead
> * [x]  Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below
> 
> ### Complete Verbose Output
> ```shell
> [debug] Command-line config: ['-vU', 'https://mfcamhub.com/videos/107796/watch-berylfane-hot-porn-video-stripchat-dirty-talk-new-new-brunettes-striptease-white-affordable-cam2cam/']
> [debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
> [debug] yt-dlp version master@2024.07.12.193440 from yt-dlp/yt-dlp-master-builds [644d84d77] (win_exe)
> [debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
> [debug] exe versions: ffmpeg 2024-06-13-git-0060a368b1-full_build-www.gyan.dev (setts), ffprobe 2024-06-13-git-0060a368b1-full_build-www.gyan.dev
> [debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.07.04, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.2, websockets-12.0
> [debug] Proxy map: {}
> [debug] Request Handlers: urllib, requests, websockets, curl_cffi
> [debug] Loaded 1834 extractors
> [debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-master-builds/releases/latest
> Latest version: master@2024.07.12.193440 from yt-dlp/yt-dlp-master-builds
> yt-dlp is up to date (master@2024.07.12.193440 from yt-dlp/yt-dlp-master-builds)
> [generic] Extracting URL: https://mfcamhub.com/videos/107796/watch-berylfane-hot-porn-video-stripchat-dirty-talk-new-new-brunettes-striptease-white-affordable-cam2cam/
> [generic] watch-berylfane-hot-porn-video-stripchat-dirty-talk-new-new-brunettes-striptease-white-affordable-cam2cam: Downloading webpage
> WARNING: [generic] Falling back on generic information extractor
> [generic] watch-berylfane-hot-porn-video-stripchat-dirty-talk-new-new-brunettes-striptease-white-affordable-cam2cam: Extracting information
> [debug] Looking for embeds
> [debug] Identified a KVS Player
> ERROR: [generic] Unable to extract flashvars; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
>   File "yt_dlp\extractor\common.py", line 740, in extract
>   File "yt_dlp\extractor\generic.py", line 2516, in _real_extract
>   File "yt_dlp\extractor\generic.py", line 2645, in _extract_embeds
>   File "yt_dlp\extractor\generic.py", line 2290, in _extract_kvs
>   File "yt_dlp\extractor\common.py", line 1347, in _search_json
>   File "yt_dlp\extractor\common.py", line 1333, in _search_regex
> ```

**Comment by GITangry** [comment]
Emails as follows to privacy@github.com were rejected for no reason and I am therefore reporting the abuse of PRIVACY and GIThub rules here 

I refer to your web page at https://github.com/yt-dlp/yt-dlp/issues/10449 and to the statement on this page “I’ve checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge".  This statement is false.


Your webpage contains a link to “https://mfcamhub.com/videos/107567/watch-luxuryxxo-new-porn-video-chaturbate-tattooedgirl-humiliation-poledance-goth/”, which contains COPYRIGHTED images (both still and moving) and textual data (e.g. biographical), which have been unlawfully copied from live broadcasts and the web page at https://chaturbate.com/luxuryxxo/ and which breach copyright. 

Whilst I accept that your page is not necessarily in breach of copyright itself, it does promote access to illegally published images and I therefore require you to redact the aforesaid link or to delete the entire post.

**Comment by GITangry** [comment]
[bashonly](https://github.com/bashonly) Can you help, please ?

**Comment by bashonly** [comment]
@GITangry the links have been redacted

**Comment by GITangry** [comment]
Thank you SO much !!!  Really appreciate your help! )
