### ISSUE TITLE
mixcloud: support embed extraction

### ISSUE THREAD

**Issue by sdaoden** [yt-dlp/yt-dlp#10444]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

DE

### Provide a description that is worded well enough to be understood

It seems mixcloud is assumed to be supported, thus the issue.

I have two kinds of URLs to use here, one is like that you can see complete output below, the other is

  https://www.mixcloud.com/widget/iframe/?light=1&feed=%2FSonarFestival%2Flaurent-garnier-live-at-s%C3%B3nar-2013-sat-15th-june%2F

P.S.: the checkbox for "I've checked that all provided URLs are playable in a browser with the same IP and same login details *" is a lie (i tried other "equal" ones from Laurent Garnier's side, yesterday)

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
p$ yt-dlp -vU 'https://player-widget.mixcloud.com/?hide_cover=1&mini=1&light=1&feed=%2Flaurentgarnier%2F2012-berlin-lbs-berghain%2F'
[debug] Command-line config: ['-vU', 'https://player-widget.mixcloud.com/?hide_cover=1&mini=1&light=1&feed=%2Flaurentgarnier%2F2012-berlin-lbs-berghain%2F']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.07.09 from yt-dlp/yt-dlp [7ead7332a] (zip)
[debug] Python 3.10.14 (CPython x86_64 64bit) - Linux-6.1.97-ideapad-x86_64-with-glibc2.39 (OpenSSL 3.3.1 4 Jun 2024, glibc 2.39)
[debug] exe versions: ffmpeg 7.0.1 (fdk,setts), ffprobe 7.0.1
[debug] Optional libraries: sqlite3-3.46.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Loaded 1834 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.07.09 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.07.09 from yt-dlp/yt-dlp)
[generic] Extracting URL: https://player-widget.mixcloud.com/?hide_cover=1&mini=1&light=1&feed=%2Flaurentgarnier%2F2012-berlin-lbs-berghain%2F
[generic] ?hide_cover=1&mini=1&light=1&feed=/laurentgarnier/2012-berlin-lbs-berghain/: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] ?hide_cover=1&mini=1&light=1&feed=/laurentgarnier/2012-berlin-lbs-berghain/: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://player-widget.mixcloud.com/?hide_cover=1&mini=1&light=1&feed=%2Flaurentgarnier%2F2012-berlin-lbs-berghain%2F
Traceback (most recent call last):
  File "/usr/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1622, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1757, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/bin/yt-dlp/yt_dlp/extractor/common.py", line 740, in extract
    ie_result = self._real_extract(url)
  File "/usr/bin/yt-dlp/yt_dlp/extractor/generic.py", line 2521, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://player-widget.mixcloud.com/?hide_cover=1&mini=1&light=1&feed=%2Flaurentgarnier%2F2012-berlin-lbs-berghain%2F
```

**Comment by bashonly** [comment]
> the checkbox for "I've checked that all provided URLs are playable in a browser with the same IP and same login details *" is a lie (i tried other "equal" ones from Laurent Garnier's side, yesterday)

what does this mean? why didn't you check these URLs? do they not play in browser?

why are you passing the iframe/widget URLs instead of the actual URLs? do we need to support embed extraction for this site?

**Comment by sdaoden** [comment]
Hello.
No it meant i have the browser in the "secweb" container open, with which i do not visit such things.  (github/lab is weird enough).

So i tried it out and can tell you both URLs work in firefox-bin as compiled by Mozilla themselves just fine.

Regarding the iframe/widget.  I have no idea of yt-dlp and its internal workings.  But if i play that thing in the browser the URL remains the same, it seems script driven that the big picture then becomes a small one and the timeline becomes visible.

Does this help?  Thank you for yt-dlp!

**Comment by sdaoden** [comment]
Hello.

bashonly wrote in
 ***@***.***>:
 |I guess what I should have asked is where are you getting these iframe/w\
 |idget URLs from? 

Laurent Garnier('s managed site) at

  https://www.laurentgarnier.com/lg--subpage--km--dj_set_audio.html

has most soundcloud, but also these.  (In firefox at least, if you
click on one of the pictures, you get a picture line at the bottom
of the window, and can then navigate with cursor in there.)

--steffen
|
|Der Kragenbaer,                The moon bear,
|der holt sich munter           he cheerfully and one by one
|einen nach dem anderen runter  wa.ks himself off
|(By Robert Gernhardt)

**Comment by sdaoden** [comment]
actually i only just now realized that mixcloud offers then an URL that leads to a page without that embedded player, and yt-dlp *can* indeed download *these* things just fine!!
Thanks a bunch!
Ciao, and keep on going!
