### ISSUE TITLE
Can you add support for www.bluey.tv

### ISSUE THREAD

**Issue by kolbdog323** [yt-dlp/yt-dlp#10446]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

USA

### Example URLs

https://www.bluey.tv/watch/bluey-book-reads/mini-bluey-2/

### Provide a description that is worded well enough to be understood

This site is a public site and its free and it has many short videos from the tv show bluey. 

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.bluey.tv/watch/bluey-book-reads/mini-bluey-2/']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.07.11.232833 from yt-dlp/yt-dlp-nightly-builds [cc1a3098c] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 7.0-full_build-www.gyan.dev (setts), ffprobe 7.0-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.07.04, curl_cffi-0.7.0, mutagen-1.47.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1834 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.07.11.232833 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.07.11.232833 from yt-dlp/yt-dlp-nightly-builds)
[generic] Extracting URL: https://www.bluey.tv/watch/bluey-book-reads/mini-bluey-2/
[generic] mini-bluey-2: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] mini-bluey-2: Extracting information
[debug] Looking for embeds
[debug] Identified 2 html5 embeds
[download] Downloading playlist: Bluey Bluey Book Reads | Mini Bluey
[generic] Playlist Bluey Bluey Book Reads | Mini Bluey: Downloading 2 items of 2
[download] Downloading item 1 of 2
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] mini-bluey-2-1: Downloading 1 format(s): 0
[debug] Invoking http downloader on "https://www.bluey.tv/watch/bluey-book-reads/mini-bluey-2/"
[debug] File locking is not supported. Proceeding without locking
[download] Destination: Bluey Bluey Book Reads ｜ Mini Bluey (1) [mini-bluey-2-1].unknown_video
[download] 100% of   50.42KiB in 00:00:00 at 218.63KiB/s
[download] Downloading item 2 of 2
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] mini-bluey-2-2: Downloading 1 format(s): 0
[debug] Invoking http downloader on "https://www.bluey.tv/wp-content/uploads/2023/07/Bluey-S03Ep06-Mini-Bluey_QUOTE_Bluey_Sing-Chores.mp3"
[download] Destination: Bluey Bluey Book Reads ｜ Mini Bluey (2) [mini-bluey-2-2].mp3
[download] 100% of   90.85KiB in 00:00:00 at 159.76KiB/s
[download] Finished downloading playlist: Bluey Bluey Book Reads | Mini Bluey
```

**Comment by bashonly** [comment]
Note for devs:

This video is a youtube embed:

```html
        <section class="wp-block-bbc-video-player fe-video-player" data-props="{&quot;postId&quot;:23673,&quot;url&quot;:&quot;https:\/\/youtu.be\/w10MnR493Fg&quot;,&quot;posterImage&quot;:&quot;https:\/\/www.bluey.tv\/wp-content\/uploads\/2024\/02\/Play-Button.jpg&quot;,&quot;watchDetail&quot;:false,&quot;videoPlayer&quot;:&quot;youtube&quot;,&quot;showTitle&quot;:false,&quot;floatingProp&quot;:false,&quot;floatingPropPosition&quot;:&quot;left&quot;,&quot;proptitle&quot;:&quot;&quot;,&quot;propdescription&quot;:&quot;Description&quot;,&quot;enableTitleCloud&quot;:false,&quot;titleCloudDirection&quot;:&quot;ltr&quot;,&quot;titleCloudSize&quot;:&quot;large&quot;,&quot;titlePosition&quot;:&quot;center&quot;,&quot;noJSVideoWarningText&quot;:&quot;Oh biscuits! You need JavaScript enabled to view this video.&quot;,&quot;reverse&quot;:false,&quot;brightcoveUrl&quot;:&quot;&quot;}" aria-label="Video Player">
```

if they're all youtube embeds like this, should be easy enough to add support for

**Comment by october262** [comment]
click the copy link button in the upper right hand corner of the video
and use it to download the video.
