### ISSUE TITLE
ffmpeg problem in python environment 

### ISSUE THREAD

**Issue by GrandpaEJ** [yt-dlp/yt-dlp#10447]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

use alternative or use "manual path for ffmpeg binary" ☹️

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by seproDev** [comment]
Could you try and explain with a few more words what issue you are having?

**Comment by GrandpaEJ** [comment]
> Could you try and explain with a few more words what issue you are having?

 i don't know how to explain , because i am a begginer 
when yt-dlp required ffmpeg for better experience, but i can't use ffmpeg in my environment ☹️ 

that's why i want to say , you should use a custom path for ffmpeg binary file 🙂

I'm sorry if you've already done this 🎉

**Comment by seproDev** [comment]
You can use `--ffmpeg-location` to specify the location of the FFmpeg executable

**Comment by GrandpaEJ** [comment]
> You can use `--ffmpeg-location` to specify the location of the FFmpeg executable. If not set, yt-dlp will look in your system's PATH.

Thanks 🎉
