### ISSUE TITLE
Error: Extracted extension ('php') is unusual and skipped for safety reasons

### ISSUE THREAD

**Issue by Rishi-0007** [yt-dlp/yt-dlp#10459]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Provide a description that is worded well enough to be understood

I encountered an error while attempting to download a video using yt-dlp with cookies extracted from Firefox. The error message states that the extracted extension ('php') is unusual and will be skipped for safety reasons. I am using the latest version of yt-dlp.

**Command Used:**
```shell
yt-dlp --cookies-from-browser firefox "https://visionias.in/student/pt/video_student/upload/index.php?vid=89852&pid=5996&id=1041824798824419199"
```

**Output:**
```
PS C:\Users\Rishi Nayak> yt-dlp --cookies-from-browser firefox "https://visionias.in/student/pt/video_student/upload/index.php?vid=89852&pid=5996&id=1041824798824419199"
[generic] Extracting URL: https://visionias.in/student/pt/video_student/upload/index.php?vid=89852&pid=5996&id=1041824798824419199
[generic] index: Downloading webpage
Extracting cookies from firefox
Extracted 42 cookies from firefox
WARNING: [generic] Falling back on generic information extractor
WARNING: [generic] URL could be a direct video link, returning it as such.
[info] index: Downloading 1 format(s): 0
ERROR: The extracted extension ('php') is unusual and will be skipped for safety reasons. If you believe this is an error, please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
PS C:\Users\Rishi Nayak>
```

**System Details:**
- yt-dlp version:  nightly@2024.07.13.232701 from yt-dlp/yt-dlp-nightly-builds [Latest version confirmed with `yt-dlp -U`]
- OS: Windows 11

**Steps to Reproduce:**
1. Run the command with the given URL and cookies from Firefox.

**Expected Behavior:**
The video should be downloaded without errors.

**Actual Behavior:**
The process fails with an error regarding the extracted extension ('php') being unusual.

**Additional Information:**
Please let me know if you need any further information or logs. Thank you for your assistance.

---

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.07.13.232701 from yt-dlp/yt-dlp-nightly-builds [150ecc45d] (pip)
[debug] Python 3.12.2 (CPython AMD64 64bit) - Windows-11-10.0.22621-SP0 (OpenSSL 3.0.13 30 Jan 2024)
[debug] exe versions: ffmpeg 7.0.1-full_build-www.gyan.dev (setts), ffprobe 7.0.1-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.02.02, mutagen-1.47.0, requests-2.32.3, sqlite3-3.43.1, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1834 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.07.13.232701 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.07.13.232701 from yt-dlp/yt-dlp-nightly-builds)
```

**Comment by bashonly** [comment]
Regression in the generic extractor due to 5ce582448ececb8d9c30c8c31f58330090ced03a


Patch:

```diff
diff --git a/yt_dlp/extractor/generic.py b/yt_dlp/extractor/generic.py
index 3b8e1e957..04cffaa86 100644
--- a/yt_dlp/extractor/generic.py
+++ b/yt_dlp/extractor/generic.py
@@ -43,6 +43,7 @@
     xpath_text,
     xpath_with_ns,
 )
+from ..utils._utils import _UnsafeExtensionError
 
 
 class GenericIE(InfoExtractor):
@@ -2446,9 +2447,13 @@ def _real_extract(self, url):
         if not is_html(first_bytes):
             self.report_warning(
                 'URL could be a direct video link, returning it as such.')
+            ext = determine_ext(url)
+            if ext not in _UnsafeExtensionError.ALLOWED_EXTENSIONS:
+                ext = 'unknown_video'
             info_dict.update({
                 'direct': True,
                 'url': url,
+                'ext': ext,
             })
             return info_dict
 
```

I will open a PR shortly to fix this

**Comment by shrimpy35** [comment]
i was having the same problem when downloading something from vk.
have you found any fix regarding the matter perhaps?

**Comment by seproDev** [comment]
@shrimpy35 Make sure you have updated to the newest yt-dlp version. If it still doesn't work, please open a new issue with a verbose log.
