### ISSUE TITLE
Failed to resolve 'www.youtube.com' Errno 11004

### ISSUE THREAD

**Issue by yuhler** [yt-dlp/yt-dlp#10452]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Brazil

### Provide a description that is worded well enough to be understood

Since a week ago I can't download any YT videos although I can still watch them from my FF browser. I also tested other download applications like 3dyd64.exe with the same results (e.g. 13:57:59, [warning] #01, omitting stream OPUS 48000Hz Stereo 50kbps 5.91 MB AO: server error (403) from rr4---sn-xhcg5uxa-jo4e.googlevideo.com).

yt-dlp reports:
d:\Downloads\Temp>yt-dlp.exe https://www.youtube.com/watch?v=AwwCSkCEi-Y
[youtube] Extracting URL: https://www.youtube.com/watch?v=AwwCSkCEi-Y
[youtube] AwwCSkCEi-Y: Downloading webpage
WARNING: [youtube] Unable to download webpage: <urllib3.connection.HTTPSConnecti
on object at 0x00000000051543D0>: Failed to resolve 'www.youtube.com' ([Errno 11
004] getaddrinfo failed)

BTW, this is my first report so I hope it's alright. More below.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

d:\Downloads\Temp>yt-dlp -vU https://www.youtube.com/watch?v=AwwCSkCEi-Y
[debug] Command-line config: ['-vU', 'https://www.youtube.com/watch?v=AwwCSkCEi-Y']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8 (No VT), error utf-8 (No VT), screen utf-8 (No VT)
[debug] yt-dlp version stable@2024.07.09 from yt-dlp/yt-dlp [7ead7332a] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-7-6.1.7601-SP1 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.07.04, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1834 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
ERROR: Unable to obtain version info (<urllib3.connection.HTTPSConnection object at 0x0000000004FBEAC0>: Failed to resolve 'api.github.com' ([Errno 11004] getaddrinfo failed)); Please try ag
ain later or visit  https://github.com/yt-dlp/yt-dlp/releases/latest
[youtube] Extracting URL: https://www.youtube.com/watch?v=AwwCSkCEi-Y
[youtube] AwwCSkCEi-Y: Downloading webpage
WARNING: [youtube] Unable to download webpage: <urllib3.connection.HTTPSConnection object at 0x0000000005164640>: Failed to resolve 'www.youtube.com' ([Errno 11004] getaddrinfo failed)
[youtube] AwwCSkCEi-Y: Downloading ios player API JSON
WARNING: [youtube] <urllib3.connection.HTTPSConnection object at 0x00000000051648B0>: Failed to resolve 'www.youtube.com' ([Errno 11004] getaddrinfo failed). Retrying (1/3)...
[youtube] AwwCSkCEi-Y: Downloading ios player API JSON
WARNING: [youtube] <urllib3.connection.HTTPSConnection object at 0x000000000519B5E0>: Failed to resolve 'www.youtube.com' ([Errno 11004] getaddrinfo failed). Retrying (2/3)...
[youtube] AwwCSkCEi-Y: Downloading ios player API JSON
WARNING: [youtube] <urllib3.connection.HTTPSConnection object at 0x000000000518E8B0>: Failed to resolve 'www.youtube.com' ([Errno 11004] getaddrinfo failed). Retrying (3/3)...
[youtube] AwwCSkCEi-Y: Downloading ios player API JSON
WARNING: [youtube] Unable to download API page: <urllib3.connection.HTTPSConnection object at 0x0000000005180460>: Failed to resolve 'www.youtube.com' ([Errno 11004] getaddrinfo failed) (cau
sed by TransportError("<urllib3.connection.HTTPSConnection object at 0x0000000005180460>: Failed to resolve 'www.youtube.com' ([Errno 11004] getaddrinfo failed)"))
[youtube] AwwCSkCEi-Y: Downloading iframe API JS
WARNING: [youtube] Unable to download webpage: <urllib3.connection.HTTPSConnection object at 0x0000000004FBEFA0>: Failed to resolve 'www.youtube.com' ([Errno 11004] getaddrinfo failed)
[youtube] AwwCSkCEi-Y: Downloading web player API JSON
WARNING: [youtube] <urllib3.connection.HTTPSConnection object at 0x0000000005155FA0>: Failed to resolve 'www.youtube.com' ([Errno 11004] getaddrinfo failed). Retrying (1/3)...
[youtube] AwwCSkCEi-Y: Downloading web player API JSON
WARNING: [youtube] <urllib3.connection.HTTPSConnection object at 0x0000000004FBE0A0>: Failed to resolve 'www.youtube.com' ([Errno 11004] getaddrinfo failed). Retrying (2/3)...
[youtube] AwwCSkCEi-Y: Downloading web player API JSON
WARNING: [youtube] <urllib3.connection.HTTPSConnection object at 0x0000000005155A00>: Failed to resolve 'www.youtube.com' ([Errno 11004] getaddrinfo failed). Retrying (3/3)...
[youtube] AwwCSkCEi-Y: Downloading web player API JSON
WARNING: [youtube] Unable to download API page: <urllib3.connection.HTTPSConnection object at 0x00000000051A8190>: Failed to resolve 'www.youtube.com' ([Errno 11004] getaddrinfo failed) (cau
sed by TransportError("<urllib3.connection.HTTPSConnection object at 0x00000000051A8190>: Failed to resolve 'www.youtube.com' ([Errno 11004] getaddrinfo failed)"))
ERROR: [youtube] AwwCSkCEi-Y: Failed to extract any player response; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Con
firm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 740, in extract
  File "yt_dlp\extractor\youtube.py", line 4143, in _real_extract
  File "yt_dlp\extractor\youtube.py", line 4107, in _download_player_responses
  File "yt_dlp\extractor\youtube.py", line 3784, in _extract_player_responses
```

**Comment by bashonly** [comment]
It's a DNS issue with your system/network. Even the update request to Github is failing

**Comment by yuhler** [comment]
> It's a DNS issue with your system/network. Even the update request to Github is failing

That's strange. No changes on my side. I also made a try using a VPN to no avail. I'll try other DNS servers. Thanks.
