### ISSUE TITLE
Downloading a 7z file fails with file extension is uncommon thus unsafe error

### ISSUE THREAD

**Issue by SubZero5** [yt-dlp/yt-dlp#10466]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

In old versions of yt-dlp I was able to get `.7z` files. But this new version threw an error about the extension being not common thus it might be an issue with my security. How come?

PS: an old version of yt-dlp is doing the job with no issues...

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['https://disk.yandex.ru/d/T9XbvjpwEyd1cA', '-Uv']
[debug] Encodings: locale cp1254, fs utf-8, pref cp1254, out cp1254 (No VT), error utf-8, screen cp1254 (No VT)
[debug] yt-dlp version stable@2024.07.09 from yt-dlp/yt-dlp [7ead7332a] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-110925-g45fa85a777-20230529 (setts), ffprobe N-110925-g45fa85a777-20230529
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.07.04, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1834 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
WARNING: [YandexDisk] Unable to download JSON metadata: HTTP Error 422: Unprocessable Entity
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
ERROR: The extracted extension ('7z') is unusual and will be skipped for safety reasons. If you believe this is an error, please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 179, in wrapper
  File "yt_dlp\YoutubeDL.py", line 3474, in process_info
  File "yt_dlp\YoutubeDL.py", line 3366, in existing_video_file
  File "yt_dlp\YoutubeDL.py", line 3365, in <lambda>
  File "yt_dlp\utils\_utils.py", line 2097, in _change_extension
  File "yt_dlp\utils\_utils.py", line 5165, in sanitize_extension
yt_dlp.utils._UnsafeExtensionError: unsafe file extension: '7z'
```

**Comment by bashonly** [comment]
yt-dlp has intentionally dropped support for downloading file extensions that are not video, audio, thumbnail, storyboard, subtitles, or streaming manifest extensions. Read https://github.com/yt-dlp/yt-dlp/security/advisories/GHSA-79w7-vh3h-8g4j for an explanation of this change.

If you really *need* to use yt-dlp to download a non-media file (e.g. by leveraging the YandexDisk extractor or the GoogleDrive extractor), you can do so with a compatibility option: pass `--compat-opt allow-unsafe-ext` with your download command.

***IMPORTANT***: This compat opt makes you vulnerable to the type of attacks outlined in the security advisory linked above. It is **extremely dangerous** and should **ONLY** be used if it's absolutely necessary (i.e. do **NOT** put this option in your configuration file). It would be much safer to just download these types of files in your browser, or with a simpler http download tool like `curl` or `wget` (if possible).
