### ISSUE TITLE
Bandcamp don't prepend artist to title

### ISSUE THREAD

**Issue by mjsir911** [yt-dlp/yt-dlp#10460]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a site-specific feature
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

USA

### Example URLs

https://saoirsedream.bandcamp.com/track/sobadlately-mix-1

### Provide a description that is worded well enough to be understood

Right now bandcamp downloads prefix the `title` metadata field with `<artist> - `. Would be cool if that wasn't the case since that's the standard field to gauge titles for things and the artist is aqcuirable elsewhere.

On other services the title isn't prepended with the artist name.

Related: #1004

A workaround which I actually found in the manual page is:
```
--parse-metadata "title:%(artist)s - %(title)s"
```

but fixing the bandcamp downloader to contain the same info as other downloaders makes more sense?

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
$ yt-dlp -vU --print title --print artist --print track https://saoirsedream.bandcamp.com/track/sobadlately-mix-1
[debug] Command-line config: ['-vU', '--print', 'title', '--print', 'artist', '--print', 'track', 'https://saoirsedream.bandcamp.com/track/sobadlately-mix-1']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.07.09 from yt-dlp/yt-dlp [7ead7332a]
[debug] Lazy loading extractors is disabled
[debug] Python 3.12.3 (CPython x86_64 64bit) - Linux-6.6.32-gentoo-dist-x86_64-11th_Gen_Intel-R-_Core-TM-_i7-1185G7_@_3.00GHz-with-glibc2.39 (OpenSSL 3.0.13 30 Jan 2024, glibc 2.39)
[debug] exe versions: ffmpeg 6.1.1 (setts), ffprobe 6.1.1
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.07.04, mutagen-1.47.0, requests-2.32.3, sqlite3-3.45.3, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1834 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.07.09 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.07.09 from yt-dlp/yt-dlp)
[Bandcamp] Extracting URL: https://saoirsedream.bandcamp.com/track/sobadlately-mix-1
[Bandcamp] sobadlately-mix-1: Downloading webpage
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 4148533023: Downloading 1 format(s): mp3-128
saoirse dream - sobadlately (mix 1)
saoirse dream
sobadlately (mix 1)
```
```

**Comment by bashonly** [comment]
For bandcamp, the `track` field is always extracted with only the track title (no artist prefix).

**Comment by mjsir911** [comment]
@bashonly I can open a new ticket or continue this conversation here, but bandcamp providing the `track` field doesn't help generalize with other services. for example, any soundcloud or youtube link link doesn't populate `artist` or `track`. I don't really know of any other services that might embed the "track" metadata but it looks like there's no procedural way to get only the track name over multiple services.

**Comment by bashonly** [comment]
`track` is a common field used for many sites, including Youtube (music links): https://github.com/yt-dlp/yt-dlp?tab=readme-ov-file#output-template
