### ISSUE TITLE
[Feature Request] access to the site via a proxy, and downloading video without a proxy

### ISSUE THREAD

**Issue by qzmtch** [yt-dlp/yt-dlp#1047]
## Checklist

- [x]  I'm reporting a feature request
- [x]  I've verified that I'm running yt-dlp version **2021.09.02**
- [x]  I've searched the bugtracker for similar feature requests including closed ones

## Description

WRITE DESCRIPTION HERE

hello, I don't know English well yet, so I'll write with a translator

the function that I am requesting may already be available, but I did not find it, and if not, then please add

in general, there is a site that is blocked in my country, and I get access to it via vpn, but when you go to the site with the vpn enabled, and turn on the live broadcast, and then turn off the vpn, the broadcast continues to work, respectively, the servers from which the video is broadcast are not blocked by the provider, in this regard, the thought arose, can you, by some argument, run the program through a proxy so that it receives links to the stream, and then download this stream without a proxy, so that everything will swing at full speed, since proxies are slow?

maybe this is already there, and the proxy works like that, tell me in more detail how `--proxy` works?
and if there is no such function, then maybe add another proxy key?

thanks

**Comment by pukkandan** [comment]
Does `--geo-verification-proxy` not work?

**Comment by qzmtch** [comment]
> Does `--geo-verification-proxy` not work?
I haven't tried it yet, but `--geo-verification-proxy` , but this command kind of gives the site information, not the provider, or am I wrong?

**Comment by shoxie007** [comment]
The proxy works as follows. Here using an example:
`--proxy 156.123.276.52:8080`
where 156.123.276.52 is the IP address and 8080 the port.

Why don't you just upgrade to paid proxies. Service is much better and you get better speeds.

I myself am subscribed to InstantProxies:
`https://instantproxies.com/pricing/`

You get 10 proxies for $10 per month. Speed is slower than my normal bandwidth, but still OK. Still very usable.

**Comment by qzmtch** [comment]
yes, `--geo-verification-proxy` it works as it should, close the question
