### ISSUE TITLE
WARNING: [facebook] unable to extract uploader; ERROR: [facebook] 495007896517569: No video formats found!; 

### ISSUE THREAD

**Issue by joe-oli** [yt-dlp/yt-dlp#10479]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Australia

### Provide a description that is worded well enough to be understood

Self explanatory, but never seen this type of message before.

Try #1
>yt-dlp -F https://www.facebook.com/cakemoe/videos/495007896517569
[facebook] Extracting URL: https://www.facebook.com/cakemoe/videos/495007896517569
[facebook] 495007896517569: Downloading webpage
WARNING: [facebook] unable to extract uploader; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
ERROR: [facebook] 495007896517569: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

Try #2
>yt-dlp -F https://www.facebook.com/watch/?v=495007896517569
[facebook] Extracting URL: https://www.facebook.com/watch/?v=495007896517569
[facebook] 495007896517569: Downloading webpage
ERROR: [facebook] 495007896517569: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
>yt-dlp -vU https://www.facebook.com/cakemoe/videos/495007896517569
[debug] Command-line config: ['-vU', 'https://www.facebook.com/cakemoe/videos/495007896517569']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.07.15.232803 from yt-dlp/yt-dlp-nightly-builds [39e6c4cb4] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22000-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 4.4.1-essentials_build-www.gyan.dev (setts), ffprobe 4.4.1-essentials_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.07.04, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1829 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.07.15.232803 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.07.15.232803 from yt-dlp/yt-dlp-nightly-builds)
[facebook] Extracting URL: https://www.facebook.com/cakemoe/videos/495007896517569
[facebook] 495007896517569: Downloading webpage
WARNING: [facebook] unable to extract uploader; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
ERROR: [facebook] 495007896517569: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1622, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1778, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1837, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2843, in process_video_result
  File "yt_dlp\YoutubeDL.py", line 1119, in raise_no_formats
yt_dlp.utils.ExtractorError: [facebook] 495007896517569: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

**Comment by bashonly** [comment]
Both links give me this in browser:

> This Video Isn't Available Anymore
> The link may be broken or the video may have been removed. You can explore more videos or try logging into facebook.com and then visiting the link again.

Are you sure about this:

> - [x] I've checked that all provided URLs are playable in a browser with the same IP and same login details

**Comment by Rikk** [comment]
I'm having this problem a lot. Not private video. Fails randomly, failures are more frequent than successes.

**Comment by bashonly** [comment]
@Rikk share a verbose log

**Comment by joe-oli** [comment]
> Both links give me this in browser:
> 
> > This Video Isn't Available Anymore
> > The link may be broken or the video may have been removed. You can explore more videos or try logging into facebook.com and then visiting the link again.
> 
> Are you sure about this:
> 
> > * [x]  I've checked that all provided URLs are playable in a browser with the same IP and same login details

Definitely the link is playable in the Browser, I just checked 22/Jul/2024. 
There is no reason you cannot see it, unless the video is geo-location blocked? 

Here is the link again.
https://www.facebook.com/watch/?v=495007896517569

**Comment by bashonly** [comment]
> Definitely the link is playable in the Browser, I just checked 22/Jul/2024.

But is it playable in browser when you're not logged in? In a private/incognito window? You're not passing any cookies to yt-dlp

**Comment by joe-oli** [comment]
> > Definitely the link is playable in the Browser, I just checked 22/Jul/2024.
> 
> But is it playable in browser when you're not logged in? In a private/incognito window? You're not passing any cookies to yt-dlp

OMG! 😮It never occurred to me I had to pass the cookies to yt-dlp, as I never had to do so in FB before. My bad.

```
yt-dlp --cookies-from-browser chrome -F https://www.facebook.com/watch/?v=495007896517569
[facebook] Extracting URL: https://www.facebook.com/watch/?v=495007896517569
[facebook] 495007896517569: Downloading webpage
Extracting cookies from chrome
ERROR: Could not copy Chrome cookie database. See  https://github.com/yt-dlp/yt-dlp/issues/7271  for more info
ERROR: Could not copy Chrome cookie database. See  https://github.com/yt-dlp/yt-dlp/issues/7271  for more info
```

After reading the issue above, I closed all Chrome windows, and voila, the cookies database is no longer locked, and I could download the video! Thanks again.

**Comment by Rikk** [comment]
@bashonly
In my theory, it could be a site bug (or some kind of rate limit), as it happens more often for videos located in some profiles, while in others it doesn't happen, apparently. For the same video, sometimes the problem doesn't manifest at all; while for videos in different profiles, success rate can be very low.

> @Rikk share a verbose log

Failure:
```
[debug] Command-line config: ['--list-formats', '-v', '--', 'https://www.facebook.com/tauan.amorim.1/videos/1809556876049234/']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.07.16 from yt-dlp/yt-dlp [89a161e8c] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19044-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.07.04, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1829 extractors
[facebook] Extracting URL: https://www.facebook.com/tauan.amorim.1/videos/1809556876049234/
[facebook] 1809556876049234: Downloading webpage
ERROR: [facebook] 1809556876049234: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1626, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1782, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1841, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2847, in process_video_result
  File "yt_dlp\YoutubeDL.py", line 1123, in raise_no_formats
yt_dlp.utils.ExtractorError: [facebook] 1809556876049234: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

Success:
```
[debug] Command-line config: ['--list-formats', '-v', '--', 'https://www.facebook.com/tauan.amorim.1/videos/1809556876049234/']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.07.16 from yt-dlp/yt-dlp [89a161e8c] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19044-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.07.04, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1829 extractors
[facebook] Extracting URL: https://www.facebook.com/tauan.amorim.1/videos/1809556876049234/
[facebook] 1809556876049234: Downloading webpage
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[info] Available formats for 1809556876049234:
ID                EXT RESOLUTION ¦   FILESIZE   TBR PROTO ¦ VCODEC        VBR ACODEC     ABR ASR MORE INFO
---------------------------------------------------------------------------------------------------------------------
1826790661010186a m4a audio only ¦ ~231.41KiB   66k https ¦ audio only        mp4a.40.5  66k 44k DASH audio, m4a_dash
sd                mp4 unknown    ¦                  https ¦ unknown           unknown
hd                mp4 unknown    ¦                  https ¦ unknown           unknown
964095082019228v  mp4 360x640    ¦ ~954.27KiB  271k https ¦ avc1.4d001e  271k video only         DASH video, mp4_dash
971446191025227v  mp4 540x960    ¦ ~  1.90MiB  551k https ¦ avc1.64001f  551k video only         DASH video, mp4_dash
1133736587958726v mp4 720x1280   ¦ ~  3.95MiB 1147k https ¦ avc1.64001f 1147k video only         DASH video, mp4_dash
```

**Comment by bashonly** [comment]
@Rikk yep that looks like a legit bug. could you open a new issue please? I think I have a solution for it but it would be good to have proper issue tracking.

**Comment by Rikk** [comment]
@bashonly https://github.com/yt-dlp/yt-dlp/issues/10532

**Comment by life777eternal** [comment]
Greetings, I have noticed the same problem. Even after updating it has the same error, and the video is still available to watch on FB. 

`C:\_______>yt-dlp.exe https://www.facebook.com/tadeodaniel.moracruz/videos/2971407446334915
[facebook] Extracting URL: https://www.facebook.com/tadeodaniel.moracruz/videos/2971407446334915
[facebook] 2971407446334915: Downloading webpage
WARNING: [facebook] unable to extract uploader; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
ERROR: [facebook] 2971407446334915: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

C:\_______>yt-dlp.exe -U
Current version: stable@2024.08.06 from yt-dlp/yt-dlp
Latest version: stable@2024.10.07 from yt-dlp/yt-dlp
Current Build Hash: 468a6f8bf1d156ad173e000a40f696d4fbd69c5aa7360229329b9063a388e7d0
Updating to stable@2024.10.07 from yt-dlp/yt-dlp ...
Updated yt-dlp to stable@2024.10.07 from yt-dlp/yt-dlp

C:\_______>yt-dlp.exe https://www.facebook.com/tadeodaniel.moracruz/videos/2971407446334915
[facebook] Extracting URL: https://www.facebook.com/tadeodaniel.moracruz/videos/2971407446334915
[facebook] 2971407446334915: Downloading webpage
WARNING: [facebook] unable to extract uploader; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
ERROR: [facebook] 2971407446334915: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

C:\_______>yt-dlp.exe "https://www.facebook.com/tadeodaniel.moracruz/videos/2971407446334915"
[facebook] Extracting URL: https://www.facebook.com/tadeodaniel.moracruz/videos/2971407446334915
[facebook] 2971407446334915: Downloading webpage
WARNING: [facebook] unable to extract uploader; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
ERROR: [facebook] 2971407446334915: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
`

Thank you, Shalom.

**Comment by Rikk** [comment]
@life777eternal I think it is because the video is age-restricted, therefore you probably need browser cookies to download it.

**Comment by bashonly** [comment]
@life777eternal can you open a new issue for that please? we should try to detect if the video is age-restricted and raise an appropriate error
