### ISSUE TITLE
[Abema] ダウンロードしようとすると unable to download video data: <urlopen error unknown url type: abematv-license> が発生

### ISSUE THREAD

**Issue by P-Kichi** [yt-dlp/yt-dlp#10489]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Japan

### Provide a description that is worded well enough to be understood

stable@2024.07.16 で Abema (https://abema.tv/) から動画をダウンロードしようとすると、

unable to download video data: \<urlopen error unknown url type: abematv-license\>

というエラーが発生します。
Abema 内のいくつかの動画に対して試してみましたが、結果は同じでした。
また、Linux 版 と Windows 版 の何れも同じエラーが発生します。
尚、少なくとも TVer.jp (https://tver.jp/) 及び YouTube ()https://www.youtube.com/) ではこの現象は発生しません。

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[user@rocky9 ~]$ yt-dlp -vU -f 2400 "https://abema.tv/video/episode/35-53_s1_p910" -o "/storage/video/AbemaTV/test.mp4"
[debug] Command-line config: ['-vU', '-f', '2400', 'https://abema.tv/video/episode/35-53_s1_p910', '-o', '/storage/video/AbemaTV/test.mp4']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.07.16 from yt-dlp/yt-dlp [89a161e8c] (zip)
[debug] Python 3.9.18 (CPython x86_64 64bit) - Linux-5.14.0-427.24.1.el9_4.x86_64-x86_64-with-glibc2.34 (OpenSSL 3.0.7 1 Nov 2022, glibc 2.34)
[debug] exe versions: ffmpeg 5.1.5 (setts), ffprobe 5.1.5
[debug] Optional libraries: Cryptodome-3.18.0, requests-2.25.1, sqlite3-3.34.1, urllib3-1.26.5
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Loaded 1829 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.07.16 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.07.16 from yt-dlp/yt-dlp)
[AbemaTV] Extracting URL: https://abema.tv/video/episode/35-53_s1_p910
[AbemaTV] Authorizing
[AbemaTV] 35-53_s1_p910: Downloading webpage
[AbemaTV] 35-53_s1_p910: Checking playability
[AbemaTV] 35-53_s1_p910: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[info] 35-53_s1_p910: Downloading 1 format(s): 2400
[debug] Invoking hlsnative downloader on "https://vod-abematv.akamaized.net/program/35-53_s1_p910/720/playlist.m3u8?aver=1"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 114
[download] Destination: /storage/video/AbemaTV/test.mp4
[download] /storage/video/AbemaTV/test.mp4.part-Frag1 has already been downloaded
[download]   0.0% of ~  62.03MiB at      0.00B/s ETA Unknown (frag 1/114)ERROR: unable to download video data: <urlopen error unknown url type: abematv-license>
Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/networking/_urllib.py", line 398, in _send
    res = opener.open(urllib_req, timeout=self._calculate_timeout(request))
  File "/usr/lib64/python3.9/urllib/request.py", line 517, in open
    response = self._open(req, data)
  File "/usr/lib64/python3.9/urllib/request.py", line 539, in _open
    return self._call_chain(self.handle_open, 'unknown',
  File "/usr/lib64/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/lib64/python3.9/urllib/request.py", line 1417, in unknown_open
    raise URLError('unknown url type: %s' % type)
urllib.error.URLError: <urlopen error unknown url type: abematv-license>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3483, in process_info
    success, real_download = self.dl(temp_filename, info_dict)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3203, in dl
    return fd.download(name, new_info, subtitle)
  File "/usr/local/bin/yt-dlp/yt_dlp/downloader/common.py", line 466, in download
    ret = self.real_download(filename, info_dict)
  File "/usr/local/bin/yt-dlp/yt_dlp/downloader/hls.py", line 381, in real_download
    return self.download_and_append_fragments(ctx, fragments, info_dict)
  File "/usr/local/bin/yt-dlp/yt_dlp/downloader/fragment.py", line 516, in download_and_append_fragments
    decrypt_fragment(fragment, self._read_fragment(ctx)), fragment['frag_index'], ctx)
  File "/usr/local/bin/yt-dlp/yt_dlp/downloader/fragment.py", line 358, in decrypt_fragment
    or _get_key(traverse_obj(info_dict, ('hls_aes', 'uri')) or decrypt_info['URI']))
  File "/usr/local/bin/yt-dlp/yt_dlp/downloader/fragment.py", line 347, in _get_key
    _key_cache[url] = self.ydl.urlopen(self._prepare_url(info_dict, url)).read()
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 4165, in urlopen
    return self._request_director.send(req)
  File "/usr/local/bin/yt-dlp/yt_dlp/networking/common.py", line 117, in send
    response = handler.send(request)
  File "/usr/local/bin/yt-dlp/yt_dlp/networking/_helper.py", line 208, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/yt-dlp/yt_dlp/networking/common.py", line 340, in send
    return self._send(request)
  File "/usr/local/bin/yt-dlp/yt_dlp/networking/_urllib.py", line 413, in _send
    raise TransportError(cause=e) from e
yt_dlp.networking.exceptions.TransportError: <urlopen error unknown url type: abematv-license>
```

**Comment by hikatch72** [comment]
I am facing the same problem. It seems to occur only in the latest version, 2024.07.16 version. As an emergency workaround, revert to the 2024.07.09 version and you can still use it.
`pip install yt-dlp==2024.07.09`
to downgrade, which resolves this issue.

**Comment by coletdjnz** [comment]
This extractor urllib handler code needs to be ported to the new networking framework. Until then it will keep breaking when unrelated changes are made or from unrelated requests.

**Comment by bashonly** [comment]
I think this will be fixed by #10491, but I need someone in-region / with an account to test it for me.

@P-Kichi @hikatch72 could you test this out?

If you're using the executable/binary/zip, you can upgrade to a pre-release build for testing by running this:

```
yt-dlp --update-to bashonly/yt-dlp@abematv
```

or with pip:

```
python3 -m pip install --force-reinstall "yt-dlp[default] @ https://github.com/bashonly/yt-dlp/archive/fix/abematv-license.tar.gz"
```

**Comment by hikatch72** [comment]
Upon confirmation, the preview version worked properly. 
For a moment I was in a hurry, thinking that DRM had been added to ABEMA 😱.

**Comment by P-Kichi** [comment]
I upgraded to the pre-release version (bashonly/yt-dlp@abematv build 2024.07.17.233943) using the command you provided

 "yt-dlp --update-to bashonly/yt-dlp@abematv"

 and confirmed that the problem was resolved.

Thank you very much for your assistance.
Please consider this matter closed.

**Comment by bashonly** [comment]
This has been fixed in master/nightly @P-Kichi @hikatch72 

If you had updated to the pre-release version / test build, you can run this to get back on the official channel:

executable/binary:
```
yt-dlp --update-to nightly
```

pip:
```
python3 -m pip install -U --pre "yt-dlp[default]"
```

**Comment by P-Kichi** [comment]
I ran the command you instructed me and returned to the official channel.
Thank you.
