### ISSUE TITLE
[instagram story] 'igsh' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by turkeyphant** [yt-dlp/yt-dlp#10498]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

UK

### Provide a description that is worded well enough to be understood

I am trying to download an instagram story from an account.

I am using the command

`yt-dlp https://www.instagram.com/stories/[user]/[id]?utm_source=ig_story_item_share\&igsh=[sh] --cookies cookies.txt`

I am using the URL `https://www.instagram.com/stories/[user]/[id]?utm_source=ig_story_item_share&igsh=[sh]` (redacted as private and no longer live)

I have escaped the ampersand

I get two errors that make no sense:

`ERROR: [instagram:story] [id]: This content is unreachable. Use --cookies, --cookies-from-browser, --username and --password, --netrc-cmd, or --netrc (instagram) to provide account credentials`

It is reachable

`'igsh' is not recognized as an internal or external command,`

It's not a command.

If I instead edit the URL to `https://www.instagram.com/stories/[user]/[id]?igsh=[sh`] it works fine. Suddenly now the cookies file works and the content is reachable.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.instagram.com/stories/[user]/[id]?utm_source=ig_story_item_share\\']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.07.16 from yt-dlp/yt-dlp [89a161e8c] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-105930-ga71a3d1ed2-20220314 (setts), ffprobe 4.1.1
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.07.04, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1829 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.07.16 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.07.16 from yt-dlp/yt-dlp)
[instagram:story] Extracting URL: https://www.instagram.com/stories/[user]/[id]?utm_source=ig_story_item_share\
[instagram:story] [id]: Downloading webpage
[instagram:story] [id]: Downloading JSON metadata
ERROR: [instagram:story] [id]: You need to log in to access this content. Use --cookies, --cookies-from-browser, --username and --password, --netrc-cmd, or --netrc (instagram) to provide account credentials
  File "yt_dlp\extractor\common.py", line 740, in extract
  File "yt_dlp\extractor\instagram.py", line 721, in _real_extract
  File "yt_dlp\extractor\common.py", line 1245, in raise_login_required

'igsh' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by bashonly** [comment]
> `ERROR: [instagram:story] [id]: This content is unreachable. Use --cookies, --cookies-from-browser, --username and --password, --netrc-cmd, or --netrc (instagram) to provide account credentials`
> It is reachable

You can view instagram stories when not being logged in? That's news to me. Please provide evidence of this. This error is self-explanatory.

> `'igsh' is not recognized as an internal or external command,`

Quote the URL. Your shell is splitting the command at the `&` character

**Comment by gamer191** [comment]
I don't understand why you would choose to manually escape the ambersand, when you can just surround the whole URL in quotes (`"URL"`). Regardless, Windows cmd uses ^ as it's escape character, not \

**Comment by turkeyphant** [comment]
> You can view instagram stories without being logged in? That's news to me. Please provide evidence of this. This error is self-explanatory. Pass cookies to yt-dlp.

As per the original post, **I am passing cookies** to yt-dlp. It still doesn't work.

**Comment by turkeyphant** [comment]
> I don't understand why you would choose to manually escape the ambersand, when you can just surround the whole URL in quotes (`"URL"`). Regardless, Windows cmd uses ^ as it's escape character, not \

Because that's what the FAQ linked above told me to do.

**Comment by bashonly** [comment]
> As per the original post, I am passing cookies to yt-dlp. It still doesn't work.

You are not passing cookies in your log. Perhaps you added the `--cookies-from-browser` or `--cookies` arguments ***after** the URL, in which case:

> Quote the URL. Your shell is splitting the command at the `&` character

Please fully read my posts before arguing against them
