### ISSUE TITLE
How to add a number at begin of filename ? Example 001_VIDEONAME 

### ISSUE THREAD

**Issue by n00bsi** [yt-dlp/yt-dlp#10496]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Have a list-file called: list with URLs

https://www.zdf.de/serien/death-in-paradise/death-in-paradise-staffel-1-folge-1-102.html
https://www.zdf.de/serien/death-in-paradise/death-in-paradise-staffel-2-folge-1-102.html
https://www.zdf.de/serien/death-in-paradise/death-in-paradise-staffel-3-folge-1-102.html

```
for i in `cat liste`
do
yt-dlp $i
done

```
got filename: 'Willkommen im Paradies [190627_1_1_dep].mp4'

Wann have:  "001_Willkommen im Paradies [190627_1_1_dep].mp4"

how to do this ?

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by n00bsi** [comment]
```
for i in `cat liste`
do 
yt-dlp --output "%(autonumber)s - %(title)s.%(ext)s" $i 
done

```

**Comment by dirkf** [comment]
Doesn't that give `001_...` for each download? The auto-numbering is per invocation of _yt-dlp_. But maybe this:
```sh
yt-dlp --output "%(autonumber)03d_%(title)s.%(ext)s" $(cat liste)
```

**Comment by bashonly** [comment]
```
yt-dlp --output "%(autonumber)03d_%(title)s.%(ext)s" -a liste
```
