### ISSUE TITLE
What is a better version of `yt-dlp -f "worstvideo+bestaudio"`

### ISSUE THREAD

**Issue by stephane-archer** [yt-dlp/yt-dlp#10502]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

What is a better version of `yt-dlp -f "worstvideo+bestaudio"`
> It is, however, recommended not to use worst and related options. When your format selector is worst, the format which is worst in all respects is selected. Most of the time, what you actually want is the video with the smallest filesize instead. So it is generally better to use -S +size or more rigorously, -S +size,+br,+res,+fps instead of -f worst. See [Sorting Formats](https://github.com/yt-dlp/yt-dlp?tab=readme-ov-file#sorting-formats) for more details.

We can see from the doc that we should use something like `-S +size` but I want this to affect only the `worstvideo` part, not the `bestaudio` part. Is there a way to do that?

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
this is a question, so I don't have any relevant output to show here...
it's not that I want to skip it...
```

**Comment by bashonly** [comment]
Format sorting (`-S`) is how yt-dlp determines what the "best" and the "worst" formats are. When you pass an `-S` argument, it is the criteria for sorting formats from best-to-worst.

**Comment by stephane-archer** [comment]
@bashonly but here I want the smallest video file (the worst in size) and the best audio which is not necessarily the best in size.
`yt-dlp -S size -f "worstvideo+bestaudio"` would work for the `worstvideo` part but not necessary for `bestaudio` but it might be already better than just `yt-dlp -f "worstvideo+bestaudio"`?

**Comment by bashonly** [comment]
When you have specific needs, it helps to give a specific example (at least 1) so those who are trying to help you can test solutions

**Comment by stephane-archer** [comment]
@bashonly Sorry if I wasn't clear.
let's take this popular music video: https://youtu.be/kJQP7kiw5Fk
I want the best audio quality, and the smallest video file (so the file is not so big because the video is not important to me here)
looking at the format, for video I want:
```
394 mp4   256x144     24    │    2.30MiB   69k https │ av01.0.00M.08   69k video only          144p, mp4_dash
```
because of the `2.30MiB` FILESIZE

regarding audio, I want:
```
251 webm  audio only      2 │    4.39MiB  131k https │ audio only          opus       131k 48k medium, webm_dash
```
because of the `131k` ABR

Does this make more sense?

**Comment by bashonly** [comment]
TBH I would just use `-f worstvideo+bestaudio` (and no `-S` arg). The manifest formats will have their approximate/inaccurate/grayed "filesizes" excluded from the sorting anyways. For your example video, this will result in `602+251`: `602` is the video format with the 2nd smallest filesize (only 0.56MB larger than the smallest) and `251` is indeed the best audio format available.
