### ISSUE TITLE
homebrew update to 2024.7.16 broke yt-dlp

### ISSUE THREAD

**Issue by chr1st0ph3rGG** [yt-dlp/yt-dlp#10503]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Updated yt-dlp on my apple silicon mac via homebrew which broke the whole yt-dlp cli leading to the same  python traceback error I posted below. So not even the debug info work at all. Also tried to update to master via yt-dlp command. But I get the same error.
I tried to delete and install it but no luck. 
I tried to reinstall yt-dlp with --head so the whole thing would be installed from source but still, no luck same error. 

Until the update to 2024.7.16 it worked without a problem now it does not work at all (and switching back to older verisons in homebrew is a bit of a pain):/

(dont wonder about the folder of the homebrew setup , homebrew is not installed in its default "/opt" dir but tried it on another mac with the default homebrew setup with the same outcome below...

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp -vU
Traceback (most recent call last):
  File ".homebrew/bin/yt-dlp", line 5, in <module>
    from yt_dlp import main
  File ".homebrew/Cellar/yt-dlp/2024.7.16/libexec/lib/python3.12/site-packages/yt_dlp/__init__.py", line 18, in <module>
    from .cookies import SUPPORTED_BROWSERS, SUPPORTED_KEYRINGS
  File ".homebrew/Cellar/yt-dlp/2024.7.16/libexec/lib/python3.12/site-packages/yt_dlp/cookies.py", line 23, in <module>
    from .aes import (
  File ".homebrew/Cellar/yt-dlp/2024.7.16/libexec/lib/python3.12/site-packages/yt_dlp/aes.py", line 5, in <module>
    from .dependencies import Cryptodome
  File ".homebrew/Cellar/yt-dlp/2024.7.16/libexec/lib/python3.12/site-packages/yt_dlp/dependencies/__init__.py", line 65, in <module>
    import requests
  File ".homebrew/Cellar/yt-dlp/2024.7.16/libexec/lib/python3.12/site-packages/requests/__init__.py", line 164, in <module>
    from .api import delete, get, head, options, patch, post, put, request
  File ".homebrew/Cellar/yt-dlp/2024.7.16/libexec/lib/python3.12/site-packages/requests/api.py", line 11, in <module>
    from . import sessions
  File ".homebrew/Cellar/yt-dlp/2024.7.16/libexec/lib/python3.12/site-packages/requests/sessions.py", line 15, in <module>
    from .adapters import HTTPAdapter
  File ".homebrew/Cellar/yt-dlp/2024.7.16/libexec/lib/python3.12/site-packages/requests/adapters.py", line 81, in <module>
    _preloaded_ssl_context.load_verify_locations(
FileNotFoundError: [Errno 2] No such file or directory
```

**Comment by bashonly** [comment]
It looks like a problem with the `certifi` package. Have you tried running `brew doctor`?

**Comment by chr1st0ph3rGG** [comment]
```
`brew doctor
Your system is ready to brew.`
```

additionally tried to reinstall it, no change

**Comment by bashonly** [comment]
FYI: the yt-dlp homebrew package is not maintained by us. If there is indeed a problem with the yt-dlp brew package, we aren't the ones who can fix it. You would want to report it to [homebrew-core](https://github.com/Homebrew/homebrew-core).

> homebrew is not installed in its default "/opt" dir but tried it on another mac with the default homebrew setup with the same outcome below...

Per the [homebrew docs](https://docs.brew.sh/Installation), installing outside of the default prefixes it not supported.

The only thing I can tell you at this point is that the `requests` library is not able to find the CA certificate bundle provided by `certifi`, probably because it's looking in the wrong path(s) (possibly because of the non-standard brew installation).

**Comment by chr1st0ph3rGG** [comment]
Ah okay, then I will try my luck there, regading the default prefix, like I said, tried it on another mac with the default homebrew setup with the same outcome 🤷.

Thanks
