### ISSUE TITLE
[Site Request] ytmnd.com (image + audio streams ---> merge into a common format?)

### ISSUE THREAD

**Issue by snowbie** [yt-dlp/yt-dlp#1051]
## Checklist

- [x] I'm reporting a new site support request
- [x] I've verified that I'm running yt-dlp version **2021.09.02**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that none of provided URLs violate any copyrights
- [x] The provided URLs do not contain any DRM to the best of my knowledge
- [x] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

GIF + WAV: https://yourethemannowdog.ytmnd.com/
GIF + MP3: https://boilemmashmem.ytmnd.com/
2x GIF + WAV: https://mannotfounddog.ytmnd.com/
2x JPG + MP3: https://momspaghetti.ytmnd.com/
PNG + GIF + MP3: https://uptownmarv.ytmnd.com/
JPG + WAV: https://picard.ytmnd.com/

## Description

If unfamiliar with ytmnd, it's an old content sharing site. Upload one or more images + an audio file, and you get your own dedicated page that plays both at the same time. Gifs & audio loop as long as the site is open. I suppose if you want to make it work as a video, the length should be the longer of the two.  

Checking the network monitor showed me that all of the worthwhile content from the page is loaded from `https://users.content.ytmnd.com/*` through html5.js. The content is quite easy to rip, but I'm hoping yt-dlp would allow for easy site saving.

**Comment by pukkandan** [comment]
yt-dlp/youtube-dl is an audio/video downloader. I could add support for just the audio (and the image as thumbnail), but i doubt that is usefull. It may be better to ask request this for gallery-dl

**Comment by pukkandan** [comment]
Closing since there is no response from OP
