### ISSUE TITLE
[YouTube] where are the 4K VP9 video formats for livestreams?

### ISSUE THREAD

**Issue by Djfe** [yt-dlp/yt-dlp#10513]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Germany

### Provide a description that is worded well enough to be understood

This is a cross-post from https://github.com/ytdl-org/youtube-dl/issues/32868
(not to see who fixes it first, but because both have the issue)

I found a stream on YouTube for which YouTube-DL doesn't extract info on the available video streams in VP9. For this reason 2160p and 1440p aren't available. (H.264 ends at 1080p)
audio is mp4 (aac) for all vp9 streams
https://www.youtube.com/watch?v=RI4GTHC1_jM

![grafik](https://github.com/user-attachments/assets/6b86ae53-c477-46ba-acf6-f61f6c269063)
![grafik](https://github.com/user-attachments/assets/a4ae569b-e3b2-4567-868d-fb143f6d6e9e)
![grafik](https://github.com/user-attachments/assets/14ce45f0-87c9-48f6-b3e5-36a9486eb57e)

I realize the stream will be offline eventually but my report is still useful I feel.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '-F', 'https://www.youtube.com/watch?v=RI4GTHC1_jM']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.07.16 from yt-dlp/yt-dlp [89a161e8c] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 6.1-full_build-www.gyan.dev (setts), ffprobe 6.1-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.07.04, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1829 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.07.16 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.07.16 from yt-dlp/yt-dlp)
[youtube] Extracting URL: https://www.youtube.com/watch?v=RI4GTHC1_jM
[youtube] RI4GTHC1_jM: Downloading webpage
[youtube] RI4GTHC1_jM: Downloading ios player API JSON
[youtube] RI4GTHC1_jM: Downloading m3u8 information
[youtube] RI4GTHC1_jM: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[info] Available formats for RI4GTHC1_jM:
ID  EXT RESOLUTION FPS │   TBR PROTO │ VCODEC        VBR ACODEC     MORE INFO
────────────────────────────────────────────────────────────────────────────────
233 mp4 audio only     │       m3u8  │ audio only        unknown    Default, IOS
234 mp4 audio only     │       m3u8  │ audio only        unknown    Default, IOS
269 mp4 256x144     15 │  290k m3u8  │ avc1.42C00B  290k video only IOS
91  mp4 256x144     15 │  290k m3u8  │ avc1.42c00b       mp4a.40.5  WEB
229 mp4 426x240     30 │  546k m3u8  │ avc1.4D4015  546k video only IOS
92  mp4 426x240     30 │  546k m3u8  │ avc1.4d4015       mp4a.40.5  WEB
230 mp4 640x360     30 │ 1210k m3u8  │ avc1.4D401E 1210k video only IOS
93  mp4 640x360     30 │ 1210k m3u8  │ avc1.4d401e       mp4a.40.2  WEB
231 mp4 854x480     30 │ 1569k m3u8  │ avc1.4D401F 1569k video only IOS
94  mp4 854x480     30 │ 1569k m3u8  │ avc1.4d401f       mp4a.40.2  WEB
232 mp4 1280x720    30 │ 2969k m3u8  │ avc1.4D401F 2969k video only IOS
95  mp4 1280x720    30 │ 2969k m3u8  │ avc1.4d401f       mp4a.40.2  WEB
270 mp4 1920x1080   30 │ 5421k m3u8  │ avc1.640028 5421k video only IOS
96  mp4 1920x1080   30 │ 5421k m3u8  │ avc1.640028       mp4a.40.2  WEB
```

**Comment by bashonly** [comment]
Those formats are available only when passing `--live-from-start`

**Comment by Djfe** [comment]
Thank you so much for the quick help.
That's an option that is useful in general.
Maybe Yt-dlp should actually display a warning if you don't set it for a YouTube livestream then?

Until then this feels like it should be added to the known Issues section, I couldn't find it there:
https://github.com/yt-dlp/yt-dlp/issues/3766

I'll leave this open for a couple of days, so others can respond

**Comment by bashonly** [comment]
AFAIK yt-dlp needs native live DASH support in order for these formats to be available without `--live-from-start`. Progress on that can be tracked in #262

**Comment by bashonly** [comment]
And here is the site feature request for adding these formats without `--live-from-start`:
- #4554

**Comment by bashonly** [comment]
Since circumstances have changed (for the worse), removing this from the FAQ in favor of #11262
