### ISSUE TITLE
MLB.TV HTTP Error 401: Unauthorized

### ISSUE THREAD

**Issue by xthreeeightfour** [yt-dlp/yt-dlp#10510]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Europe

### Provide a description that is worded well enough to be understood

always used to work, credentials are working, ip is not blocked by the site, not working however.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--verbose', '-u', 'PRIVATE', '-p', 'PRIVATE', '-F', 'https://www.mlb.com/tv/g746040/v39312c6e-728f-42ae-a9dd-3b7d069f01a0']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.07.16 from yt-dlp/yt-dlp (linux_exe)
[debug] Python 3.11.9 (CPython x86_64 64bit) - Linux-6.1.0-22-amd64-x86_64-with (OpenSSL 3.1.5 30 Jan 2024)
[debug] exe versions: ffmpeg 5.1.5-0 (setts), ffprobe 5.1.5-0, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.07.04, curl_cffi-0.7.1, mutagen-1.47.0, requests-2.32.3, secretstorage-3.3.3, sqlite3-3.44.2, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1829 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.07.16 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.07.16 from yt-dlp/yt-dlp)
[MLBTV] Downloading JSON metadata
[MLBTV] None: Downloading webpage
[MLBTV] Downloading JSON metadata
[MLBTV] Extracting URL: https://www.mlb.com/tv/g746040/v39312c6e-728f-42ae-a9dd-3b7d069f01a0
[MLBTV] 746040: Downloading JSON metadata
[MLBTV] 746040: Downloading Home-en stream info JSON
WARNING: [MLBTV] Failed to download Home-en stream info, skipping: HTTP Error 401: Unauthorized
[MLBTV] 746040: Downloading Away-en stream info JSON
WARNING: [MLBTV] Failed to download Away-en stream info, skipping: HTTP Error 401: Unauthorized
ERROR: [MLBTV] 746040: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "yt_dlp/YoutubeDL.py", line 1626, in wrapper
  File "yt_dlp/YoutubeDL.py", line 1782, in __extract_info
  File "yt_dlp/YoutubeDL.py", line 1841, in process_ie_result
  File "yt_dlp/YoutubeDL.py", line 2847, in process_video_result
  File "yt_dlp/YoutubeDL.py", line 1123, in raise_no_formats
yt_dlp.utils.ExtractorError: [MLBTV] 746040: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

**Comment by cutilikre03** [comment]
I'm a bit new to github - does a pull request mean it'll be fixed by the next update?

**Comment by bashonly** [comment]
@cutilikre03 it has been fixed in master now. The nightly version releasing in ~2 hours will have the fix
