### ISSUE TITLE
[iq.com] download audio only from iqiyi global

### ISSUE THREAD

**Issue by rrfqi** [yt-dlp/yt-dlp#10511]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

is there any command to download the audio file only? or is it not possible because the audio isn't listed

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--list-formats', 'https://www.iq.com/play/renascence-vietnamese-ver-episode-1-yep5tz3tgo']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.07.16 from yt-dlp/yt-dlp [89a161e8c] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-109138-g3bcec58535-20221119 (setts), ffprobe N-109138-g3bcec58535-20221119, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.07.04, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1829 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.07.16 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.07.16 from yt-dlp/yt-dlp)
[iq.com] Extracting URL: https://www.iq.com/play/renascence-vietnamese-ver-episode-1-yep5tz3tgo
[iq.com] yep5tz3tgo: Downloading webpage
[debug] Loading iq.player_js from cache
[debug] Loading iq.player_js from cache
[iq.com] yep5tz3tgo: Executing signature code (this may take a couple minutes)
[debug] [iq.com] PhantomJS command line: phantomjs "--ssl-protocol=any" C:\Users\User\AppData\Local\Temp\tmpqqapaha2
[iq.com] yep5tz3tgo: Downloading initial video format info
[iq.com] yep5tz3tgo: Downloading format data for 480P
[iq.com] yep5tz3tgo: Downloading format data for 360P
[iq.com] yep5tz3tgo: Downloading format data for 240P
[iq.com] yep5tz3tgo: Downloading format data for 720P
[iq.com] yep5tz3tgo: Downloading format data for 1080P
WARNING: [iq.com] 1080P format is restricted
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[info] Available formats for yep5tz3tgo:
ID  EXT RESOLUTION │ PROTO │ VCODEC  ACODEC  MORE INFO
──────────────────────────────────────────────────────
100 mp4 512x216    │ m3u8  │ unknown unknown 240P
200 mp4 848x360    │ m3u8  │ unknown unknown 360P
300 mp4 896x376    │ m3u8  │ unknown unknown 480P
500 mp4 1280x544   │ m3u8  │ unknown unknown 720P
```

**Comment by seproDev** [comment]
You can add `-x`, but what it will do in this case is download the combined video and audio and then extract the audio from that file.

**Comment by rrfqi** [comment]
> You can add `-x`, but what it will do in this case is download the combined video and audio and then extract the audio from that file.

yeah, but it will takes some time to download the video and audio,  I actually just need the audio file

**Comment by seproDev** [comment]
Nothing can be done then. If the site doesn't offer audio only versions, how is yt-dlp supposed to download them?
