### ISSUE TITLE
Support of capital streaming platform : embed videos of VidMoly.me streaming platform

### ISSUE THREAD

**Issue by trimechee** [yt-dlp/yt-dlp#10519]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

World

### Example URLs

https://vidmoly.me/

https://vidmoly.to/embed-pxdzbdut621e.html

First media player  on : 

https://v5.voiranime.com/anime/viral-hit-vf/

Third media player on : 

https://french-anime.com/animes-vf/1443-kaiju-n8.html

### Provide a description that is worded well enough to be understood

Hello, thank you for the amazing awesome Yt-dlp ! 💯 🥇 

Please i have request : many of embed videos of my favourite anime wesbtes are hosed on Vidmoly platrfrm tat uses HLS protocol so it is difficult or impossible to donwload or send the stream to vlc or potplayer (with 3DYD Youtube Source plugin that uses Yt-dlp) with VidMoly platform  which is one of the few platforms today to add the standard 480p quality ideal when our connection becomes weak, and it will be great please to add support for this platform and their embed videos in may streaming websites , thank you very much !

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
This is the log of potlayer used with plugin  "3DYD Youtube Source" with VidMoly embed video and i put te path of Yt-dlp in 3DYD Youtube Source : 


https://vidmoly.to/embed-pxdzbdut621e.html

https://ys.3dyd.com/

10:09:52, yt-dlp (external): 2024.7.16
10:09:52, libcurl (internal): libcurl/7.68.0 Schannel zlib/1.2.11 brotli/1.0.7 nghttp2/1.40.0
10:09:52, ffmpeg (internal): lavf 58.29.100, lavc 58.54.100, lavu 56.31.100
10:09:52, #01, Analysis, https://vidmoly.to/embed-pxdzbdut621e.html
10:09:52, #01, Opening given  URL...
10:10:26, [warning] yt-dlp: WARNING: [generic] Falling back on generic information extractor
10:10:26, skipped results from 'generic' youtube-dl extractor: analyzing URLs from unsupported sites is disallowed
10:10:26, [error] #01, Analysis, unsupported site URL
10:10:26, #01, Ready
```

**Comment by seproDev** [comment]
Piracy sites will not be supported

**Comment by seproDev** [comment]
Okay, let me try to break this down for you. yt-dlp has a [policy against sites primarily used for piracy](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy).
You even selected
>  [x] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge

which is just not true. The links you provided are pirated videos.

But why do we care?
The short answer is that supporting piracy sites could both get the project shut down and the maintainers into legal trouble. Other similar projects in the past have been shut down for supporting piracy sites. If you are willing to take the risk of fighting (and potentially losing) a year-long legal battle, you are free to fork the project and make your own rules. The current maintainers of yt-dlp have decided that they are not willing to take that risk.

Okay, so what does "sites primarily used for piracy" mean?
There is no clear-cut border here. As you pointed out, any site that hosts user-generated content can be used for piracy. However, with vidmoly, it is being discussed as a safe haven for pirated content in online forums, I am having trouble finding a single non pirated video, and the operators are completely unknown.
These reasons are enough for us to reject the site from being added to yt-dlp.

You might disagree with that decision, but this is non-negotiable.
