### ISSUE TITLE
Separately downloaded mp4 and m4a files from Youtube aren't in synch

### ISSUE THREAD

**Issue by GeorgeL59** [yt-dlp/yt-dlp#10529]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

This problem happened to me the very first time today. I downloaded the latest version to see if it fixes it, it didn't. I also could not figure out which posting category I should post this problem, at the end I figured, that this is the closest one, with one exception: This problem occured on Youtube, I have not tested it on other video sharing websites:

This is the URL of the Youtube video that I have audio synch issue with, with separately downloaded mp4 and m4a files. 

https://www.youtube.com/watch?v=zvdYmJUgvLQ

There is no audio synch issue with the same video if I am watching it online. I played with the audio synch settings in VLC player and figured out that the audio is hastened by -5.000 seconds.

This is weird, it is really weird.

I used video ID 136 and audio ID 140-drc for downloading these files.

I am assuming that the subtitles are embeded in the video, so that's why there is no synch problem with that.

My most intelligent guess for the cause of this problem is, that Youtube decided to incorporate delay in the audio intentionally to piss off folks like me who watches yt videos off line to prevent massive brainwashing by commercials and wasting my precious time.

If the experts/admins find this issue reporting inappropiate for this group, please move it to the right one.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
D:\AMOVIES>yt-dlp.exe -vU -f 136 https://www.youtube.com/watch?v=zvdYmJUgvLQ
[debug] Command-line config: ['-vU', '-f', '136', 'https://www.youtube.com/watch?v=zvdYmJUgvLQ']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8 (No VT), error utf-8 (No VT), screen utf-8 (No VT)
[debug] yt-dlp version stable@2024.07.16 from yt-dlp/yt-dlp [89a161e8c] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-7-6.1.7601-SP1 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.07.04, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1829 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.07.16 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.07.16 from yt-dlp/yt-dlp)
[youtube] Extracting URL: https://www.youtube.com/watch?v=zvdYmJUgvLQ
[youtube] zvdYmJUgvLQ: Downloading webpage
[youtube] zvdYmJUgvLQ: Downloading ios player API JSON
[debug] Loading youtube-nsig.d60b0ef9 from cache
[debug] [youtube] Decrypted nsig 1ZjNDGt6XoOJJpVy => Csf2S6B_IDhrJQ
[debug] Loading youtube-nsig.d60b0ef9 from cache
[debug] [youtube] Decrypted nsig CFS3Dm4KYUNpQH9A => Ettd-ujBH47Rhg
[youtube] zvdYmJUgvLQ: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[info] zvdYmJUgvLQ: Downloading 1 format(s): 136
[debug] Invoking http downloader on "https://rr4---sn-h5bt5guxax3vh-c0qk.googlevideo.com/videoplayback?expire=1721668138&ei=yj2eZqDhKtaOp-oPofyR4Ak&ip=31.46.252.70&id=o-AG1AkxN_50SVHoSIu8F7uqS8nOWXxMnsy6t2XFIeENgX&itag=136&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=hm&mm=31%2C29&mn=sn-h5b
t5guxax3vh-c0qk%2Csn-c0q7lns7&ms=au%2Crdu&mv=m&mvi=4&pl=22&gcr=hu&initcwndbps=1630000&vprv=1&svpuc=1&mime=video%2Fmp4&rqh=1&gir=yes&clen=470840568&dur=7116.400&lmt=1706543273279182&mt=1721646288&fvip=5&keepalive=yes&c=IOS&txp=5432434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2
Cgcr%2Cvprv%2Csvpuc%2Cmime%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRQIgcFgWn58x4TcemaxDQCEq7Wwl5HhOTuCbWMOJwVRJTQUCIQDaRKRCNLJDnSIM0i-GubTS4JW9xUL9PkuqxgwmkV4LFA%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AHlkHjAwRAIgR2nUByOZCsxYLBLh6SzSDALUpR5h6olcrbvvuqoi_A4CIE3dT_F8Bmu
aRHCT8-rjpuRkRGmAxye1qcJDkAe4ua74"
[debug] File locking is not supported. Proceeding without locking
[download] Destination: Love For Rent Episode 17 HD (English Subtitle) [zvdYmJUgvLQ].mp4
[download] 100% of  449.03MiB in 00:00:30 at 14.80MiB/s

D:\AMOVIES>yt-dlp.exe -vU -f 140-drc https://www.youtube.com/watch?v=zvdYmJUgvLQ
[debug] Command-line config: ['-vU', '-f', '140-drc', 'https://www.youtube.com/watch?v=zvdYmJUgvLQ']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8 (No VT), error utf-8 (No VT), screen utf-8 (No VT)
[debug] yt-dlp version stable@2024.07.16 from yt-dlp/yt-dlp [89a161e8c] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-7-6.1.7601-SP1 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.07.04, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1829 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.07.16 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.07.16 from yt-dlp/yt-dlp)
[youtube] Extracting URL: https://www.youtube.com/watch?v=zvdYmJUgvLQ
[youtube] zvdYmJUgvLQ: Downloading webpage
[youtube] zvdYmJUgvLQ: Downloading ios player API JSON
[debug] Loading youtube-nsig.d60b0ef9 from cache
[debug] [youtube] Decrypted nsig lZRiHMdqlRFkPIHp => F2Je8YVcYnw0gA
[debug] Loading youtube-nsig.d60b0ef9 from cache
[debug] [youtube] Decrypted nsig E4rFQ8nKjsLEQFmw => q0kYIKxqlaXybg
[youtube] zvdYmJUgvLQ: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[info] zvdYmJUgvLQ: Downloading 1 format(s): 140-drc
[debug] Invoking http downloader on "https://rr4---sn-h5bt5guxax3vh-c0qk.googlevideo.com/videoplayback?expire=1721668191&ei=_z2eZtrwLbTXi9oPt_a24AI&ip=31.46.252.70&id=o-ADoAAAC_ZO7R9yW8F9BXo-bTjl7sxRkf2jjY7BhwQ5N-&itag=140&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=hm&mm=31%2C29&mn=sn-h5b
t5guxax3vh-c0qk%2Csn-c0q7lns7&ms=au%2Crdu&mv=m&mvi=4&pl=22&gcr=hu&initcwndbps=1630000&vprv=1&svpuc=1&xtags=drc%3D1&mime=audio%2Fmp4&rqh=1&gir=yes&clen=115172930&dur=7116.451&lmt=1706539612265819&mt=1721646288&fvip=5&keepalive=yes&c=IOS&txp=5432434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequ
iressl%2Cxpc%2Cgcr%2Cvprv%2Csvpuc%2Cxtags%2Cmime%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRAIgZFHq02vd_HHN4zdyLMBrxNpRJXlSyhyLx5w_on_V3SYCIDXuAhRWrqfZOUNjn6uoxAlJKUoPWoRDdKODrkuGCY6e&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AHlkHjAwRQIhAPP5n9nlW7sIcK3ta1KHhWgni1U6QiRBgHCnowkEk
VfRAiA3moyW0aKBzyjKmN9wgIPrN0eNMbvAghysOg9g7VwC5A%3D%3D"
[debug] File locking is not supported. Proceeding without locking
[download] Destination: Love For Rent Episode 17 HD (English Subtitle) [zvdYmJUgvLQ].m4a
[download] 100% of  109.84MiB in 00:00:07 at 14.37MiB/s
WARNING: zvdYmJUgvLQ: writing DASH m4a. Only some players support this container. Install ffmpeg to fix this automatically
```

**Comment by GeorgeL59** [comment]
While I was answering these questions and to get the right debug text I downloaded the video audio files at least 4 times, the last download seems to be OK, no synch issue. Because of that I am closing this issue because I don't want anyone spend or waste time on it for now. If it comes up again, I'll get back on this. Thanks.

**Comment by GeorgeL59** [comment]
While I was answering these questions and to get the right debug text I downloaded the video audio files at least 4 times, the last download seems to be OK, no synch issue. Because of that I am closing this issue because I don't want anyone spend or waste time on it for now. If it comes up again, I'll get back on this. Thanks.

**Comment by bashonly** [comment]
why not install ffmpeg and merge the video+audio?

**Comment by bashonly** [comment]
I mean, try installing ffmpeg and see what happens

**Comment by GeorgeL59** [comment]
I installed FFMPEG, the latest version, but it doesn't seem to work on my Windows 7 system, gives me this error message:
"The application was unable to start correctly (0xc0000005)."

But I do have an older version of it from 2017, it seems to work (running the exe gives me the options, and I did put the ffmpeg folder in the enviroment path), but I don't have a clue how can I utilize the ffmpeg to merge video and audio files, the "--help" doesn't seem to have any info on merging audio and video files. Would you please, give me a few hints?

**Comment by bashonly** [comment]
Put `ffmpeg.exe` and `ffprobe.exe` in the same folder as your `yt-dlp.exe`

**Comment by GeorgeL59** [comment]
OK. I did and then what's the next step?

Maybe there is an option now to download a video and audio file and merge them as a final process?

**Comment by bashonly** [comment]
Run yt-dlp without any `-f` argument. By default it will try to select the best video and best audio formats and merge them (if ffmpeg is installed).

If you want to specify formats, then use the `+` operator, e.g. `-f 136+140`.

Or you could use format sorting (`-S`) instead of `-f`, e.g. `-S vcodec:h264,res,acodec:aac` to get mp4 with h264 video and aac audio without having to pass specific format IDs

**Comment by GeorgeL59** [comment]
Wow Dude! This is cool, really cool!!
I figured out that I had to download the Essential version of ffmpeg to make it work on Windows 7 and using the recommended command line
"If you want to specify formats, then use the + operator, e.g. -f 136+140." indeed merged the audio file with the video one at the end.

Since my Dell laptop is a 2008 model, it cannot handle higher res. than 720p and this is the reason I cannot opt for the best resolution when I am using yt-dlp. But I do like the idea of using -s format sorting in order to get mp4 with h264 video and aac audio, but is there a way to set the res. requirement at 720p additionally in this case?

**Comment by bashonly** [comment]
`-S vcodec:h264,res:720,acodec:aac` (uppercase `-S`)

**Comment by GeorgeL59** [comment]
Thank You for this info, it works like a charm.

I already downloaded like 70 mp4 and the matching m4a audio files in a local folder on my hard disk, is there a way to merge them or the only way to get these video with audio files merged by downloading them again from the Net?

**Comment by bashonly** [comment]
It would probably be fastest to either re-download or manually merge with ffmpeg:

```
ffmpeg -i "video.mp4" -i "audio.mp4" -c copy "output.mp4"
```

**Comment by GeorgeL59** [comment]
bashonly: Thanks a lot for all of your helpful answers, you solved all my ffmpeg-yt-dlp related problems!
