### ISSUE TITLE
Can't "--sub-langs LANGS" and "--write-auto-subs" be used together?

### ISSUE THREAD

**Issue by EVANGELION-Air** [yt-dlp/yt-dlp#10526]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Two videos info:

1. [https://www.bilibili.com/video/BV1bE421w78J/](https://www.bilibili.com/video/BV1bE421w78J/)

   ❯ yt-dlp https://www.bilibili.com/video/BV1bE421w78J/ --list-subs
   [BiliBili] Extracting URL: https://www.bilibili.com/video/BV1bE421w78J/
   [BiliBili] 1bE421w78J: Downloading webpage
   Extracting cookies from firefox
   Extracted 2088 cookies from firefox
   [BiliBili] BV1bE421w78J: Extracting videos in anthology
   [BiliBili] 1656334462: Extracting chapters
   [BiliBili] BV1bE421w78J: Extracting subtitle info 1620997229
   [BiliBili] BV1bE421w78J: Downloading JSON metadata
   [BiliBili] BV1bE421w78J: Downloading JSON metadata
   [info] BV1bE421w78J: Downloading subtitles: zh-CN, en-US
   [info] Available subtitles for BV1bE421w78J:
   Language Formats
   danmaku  xml
   zh-CN    srt
   en-US    srt

2. [https://www.youtube.com/watch?v=gTeubeCIwRw](https://www.youtube.com/watch?v=gTeubeCIwRw)

   ❯ yt-dlp https://www.youtube.com/watch?v=gTeubeCIwRw --list-subs
   Extracting cookies from firefox
   Extracted 2088 cookies from firefox
   [youtube] Extracting URL: https://www.youtube.com/watch?v=gTeubeCIwRw
   [youtube] gTeubeCIwRw: Downloading webpage
   [youtube] gTeubeCIwRw: Downloading ios player API JSON
   [youtube] gTeubeCIwRw: Downloading m3u8 information
   [info] Available automatic captions for gTeubeCIwRw:
   Language Name                  Formats
   af       Afrikaans             vtt, ttml, srv3, srv2, srv1, json3
   ak       Akan                  vtt, ttml, srv3, srv2, srv1, json3
   sq       Albanian              vtt, ttml, srv3, srv2, srv1, json3
   am       Amharic               vtt, ttml, srv3, srv2, srv1, json3
   ar       Arabic                vtt, ttml, srv3, srv2, srv1, json3
   hy       Armenian              vtt, ttml, srv3, srv2, srv1, json3
   as       Assamese              vtt, ttml, srv3, srv2, srv1, json3
   ay       Aymara                vtt, ttml, srv3, srv2, srv1, json3
   az       Azerbaijani           vtt, ttml, srv3, srv2, srv1, json3
   bn       Bangla                vtt, ttml, srv3, srv2, srv1, json3
   eu       Basque                vtt, ttml, srv3, srv2, srv1, json3
   be       Belarusian            vtt, ttml, srv3, srv2, srv1, json3
   bho      Bhojpuri              vtt, ttml, srv3, srv2, srv1, json3
   bs       Bosnian               vtt, ttml, srv3, srv2, srv1, json3
   bg       Bulgarian             vtt, ttml, srv3, srv2, srv1, json3
   my       Burmese               vtt, ttml, srv3, srv2, srv1, json3
   ca       Catalan               vtt, ttml, srv3, srv2, srv1, json3
   ceb      Cebuano               vtt, ttml, srv3, srv2, srv1, json3
   zh-Hans  Chinese (Simplified)  vtt, ttml, srv3, srv2, srv1, json3
   zh-Hant  Chinese (Traditional) vtt, ttml, srv3, srv2, srv1, json3
   co       Corsican              vtt, ttml, srv3, srv2, srv1, json3
   hr       Croatian              vtt, ttml, srv3, srv2, srv1, json3
   cs       Czech                 vtt, ttml, srv3, srv2, srv1, json3
   da       Danish                vtt, ttml, srv3, srv2, srv1, json3
   dv       Divehi                vtt, ttml, srv3, srv2, srv1, json3
   nl       Dutch                 vtt, ttml, srv3, srv2, srv1, json3
   en-orig  English (Original)    vtt, ttml, srv3, srv2, srv1, json3
   en       English               vtt, ttml, srv3, srv2, srv1, json3
   eo       Esperanto             vtt, ttml, srv3, srv2, srv1, json3
   et       Estonian              vtt, ttml, srv3, srv2, srv1, json3
   ee       Ewe                   vtt, ttml, srv3, srv2, srv1, json3
   fil      Filipino              vtt, ttml, srv3, srv2, srv1, json3
   fi       Finnish               vtt, ttml, srv3, srv2, srv1, json3
   fr       French                vtt, ttml, srv3, srv2, srv1, json3
   gl       Galician              vtt, ttml, srv3, srv2, srv1, json3
   lg       Ganda                 vtt, ttml, srv3, srv2, srv1, json3
   ka       Georgian              vtt, ttml, srv3, srv2, srv1, json3
   de       German                vtt, ttml, srv3, srv2, srv1, json3
   el       Greek                 vtt, ttml, srv3, srv2, srv1, json3
   gn       Guarani               vtt, ttml, srv3, srv2, srv1, json3
   gu       Gujarati              vtt, ttml, srv3, srv2, srv1, json3
   ht       Haitian Creole        vtt, ttml, srv3, srv2, srv1, json3
   ha       Hausa                 vtt, ttml, srv3, srv2, srv1, json3
   haw      Hawaiian              vtt, ttml, srv3, srv2, srv1, json3
   iw       Hebrew                vtt, ttml, srv3, srv2, srv1, json3
   hi       Hindi                 vtt, ttml, srv3, srv2, srv1, json3
   hmn      Hmong                 vtt, ttml, srv3, srv2, srv1, json3
   hu       Hungarian             vtt, ttml, srv3, srv2, srv1, json3
   is       Icelandic             vtt, ttml, srv3, srv2, srv1, json3
   ig       Igbo                  vtt, ttml, srv3, srv2, srv1, json3
   id       Indonesian            vtt, ttml, srv3, srv2, srv1, json3
   ga       Irish                 vtt, ttml, srv3, srv2, srv1, json3
   it       Italian               vtt, ttml, srv3, srv2, srv1, json3
   ja       Japanese              vtt, ttml, srv3, srv2, srv1, json3
   jv       Javanese              vtt, ttml, srv3, srv2, srv1, json3
   kn       Kannada               vtt, ttml, srv3, srv2, srv1, json3
   kk       Kazakh                vtt, ttml, srv3, srv2, srv1, json3
   km       Khmer                 vtt, ttml, srv3, srv2, srv1, json3
   rw       Kinyarwanda           vtt, ttml, srv3, srv2, srv1, json3
   ko       Korean                vtt, ttml, srv3, srv2, srv1, json3
   kri      Krio                  vtt, ttml, srv3, srv2, srv1, json3
   ku       Kurdish               vtt, ttml, srv3, srv2, srv1, json3
   ky       Kyrgyz                vtt, ttml, srv3, srv2, srv1, json3
   lo       Lao                   vtt, ttml, srv3, srv2, srv1, json3
   la       Latin                 vtt, ttml, srv3, srv2, srv1, json3
   lv       Latvian               vtt, ttml, srv3, srv2, srv1, json3
   ln       Lingala               vtt, ttml, srv3, srv2, srv1, json3
   lt       Lithuanian            vtt, ttml, srv3, srv2, srv1, json3
   lb       Luxembourgish         vtt, ttml, srv3, srv2, srv1, json3
   mk       Macedonian            vtt, ttml, srv3, srv2, srv1, json3
   mg       Malagasy              vtt, ttml, srv3, srv2, srv1, json3
   ms       Malay                 vtt, ttml, srv3, srv2, srv1, json3
   ml       Malayalam             vtt, ttml, srv3, srv2, srv1, json3
   mt       Maltese               vtt, ttml, srv3, srv2, srv1, json3
   mi       Māori                 vtt, ttml, srv3, srv2, srv1, json3
   mr       Marathi               vtt, ttml, srv3, srv2, srv1, json3
   mn       Mongolian             vtt, ttml, srv3, srv2, srv1, json3
   ne       Nepali                vtt, ttml, srv3, srv2, srv1, json3
   nso      Northern Sotho        vtt, ttml, srv3, srv2, srv1, json3
   no       Norwegian             vtt, ttml, srv3, srv2, srv1, json3
   ny       Nyanja                vtt, ttml, srv3, srv2, srv1, json3
   or       Odia                  vtt, ttml, srv3, srv2, srv1, json3
   om       Oromo                 vtt, ttml, srv3, srv2, srv1, json3
   ps       Pashto                vtt, ttml, srv3, srv2, srv1, json3
   fa       Persian               vtt, ttml, srv3, srv2, srv1, json3
   pl       Polish                vtt, ttml, srv3, srv2, srv1, json3
   pt       Portuguese            vtt, ttml, srv3, srv2, srv1, json3
   pa       Punjabi               vtt, ttml, srv3, srv2, srv1, json3
   qu       Quechua               vtt, ttml, srv3, srv2, srv1, json3
   ro       Romanian              vtt, ttml, srv3, srv2, srv1, json3
   ru       Russian               vtt, ttml, srv3, srv2, srv1, json3
   sm       Samoan                vtt, ttml, srv3, srv2, srv1, json3
   sa       Sanskrit              vtt, ttml, srv3, srv2, srv1, json3
   gd       Scottish Gaelic       vtt, ttml, srv3, srv2, srv1, json3
   sr       Serbian               vtt, ttml, srv3, srv2, srv1, json3
   sn       Shona                 vtt, ttml, srv3, srv2, srv1, json3
   sd       Sindhi                vtt, ttml, srv3, srv2, srv1, json3
   si       Sinhala               vtt, ttml, srv3, srv2, srv1, json3
   sk       Slovak                vtt, ttml, srv3, srv2, srv1, json3
   sl       Slovenian             vtt, ttml, srv3, srv2, srv1, json3
   so       Somali                vtt, ttml, srv3, srv2, srv1, json3
   st       Southern Sotho        vtt, ttml, srv3, srv2, srv1, json3
   es       Spanish               vtt, ttml, srv3, srv2, srv1, json3
   su       Sundanese             vtt, ttml, srv3, srv2, srv1, json3
   sw       Swahili               vtt, ttml, srv3, srv2, srv1, json3
   sv       Swedish               vtt, ttml, srv3, srv2, srv1, json3
   tg       Tajik                 vtt, ttml, srv3, srv2, srv1, json3
   ta       Tamil                 vtt, ttml, srv3, srv2, srv1, json3
   tt       Tatar                 vtt, ttml, srv3, srv2, srv1, json3
   te       Telugu                vtt, ttml, srv3, srv2, srv1, json3
   th       Thai                  vtt, ttml, srv3, srv2, srv1, json3
   ti       Tigrinya              vtt, ttml, srv3, srv2, srv1, json3
   ts       Tsonga                vtt, ttml, srv3, srv2, srv1, json3
   tr       Turkish               vtt, ttml, srv3, srv2, srv1, json3
   tk       Turkmen               vtt, ttml, srv3, srv2, srv1, json3
   uk       Ukrainian             vtt, ttml, srv3, srv2, srv1, json3
   ur       Urdu                  vtt, ttml, srv3, srv2, srv1, json3
   ug       Uyghur                vtt, ttml, srv3, srv2, srv1, json3
   uz       Uzbek                 vtt, ttml, srv3, srv2, srv1, json3
   vi       Vietnamese            vtt, ttml, srv3, srv2, srv1, json3
   cy       Welsh                 vtt, ttml, srv3, srv2, srv1, json3
   fy       Western Frisian       vtt, ttml, srv3, srv2, srv1, json3
   xh       Xhosa                 vtt, ttml, srv3, srv2, srv1, json3
   yi       Yiddish               vtt, ttml, srv3, srv2, srv1, json3
   yo       Yoruba                vtt, ttml, srv3, srv2, srv1, json3
   zu       Zulu                  vtt, ttml, srv3, srv2, srv1, json3
   gTeubeCIwRw has no subtitles

I tested three types of yt-dlp.conf：

1. config1
   --sub-langs "zh-CN,ai-zh,en-US"
   --write-auto-subs
   --remux-video mkv
   --embed-subs
   --embed-thumbnail
   --embed-metadata

2. config2
   --sub-langs "zh-CN,ai-zh,en-US"
   --remux-video mkv
   --embed-subs
   --embed-thumbnail
   --embed-metadata

2. config3
   --write-auto-subs
   --remux-video mkv
   --embed-subs
   --embed-thumbnail
   --embed-metadata

If you use the config1, both two video will not be able to download any subtitles.

If you use the config2, the first video will download subtitles, but the second video will not be able to download automatically generated subtitles.

If you use the config3, the first video will not be able to download subtitles, but the second video will download automatically generated subtitles.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
config1:
❯ yt-dlp https://www.bilibili.com/video/BV1bE421w78J/
[BiliBili] Extracting URL: https://www.bilibili.com/video/BV1bE421w78J/
[BiliBili] 1bE421w78J: Downloading webpage
Extracting cookies from firefox
Extracted 2088 cookies from firefox
[BiliBili] BV1bE421w78J: Extracting videos in anthology
[BiliBili] 1656334462: Extracting chapters
[info] BV1bE421w78J: Downloading 1 format(s): 100113+30280
[info] There are no subtitles for the requested languages

❯ yt-dlp https://www.youtube.com/watch?v=gTeubeCIwRw
Extracting cookies from firefox
Extracted 2088 cookies from firefox
[youtube] Extracting URL: https://www.youtube.com/watch?v=gTeubeCIwRw
[youtube] gTeubeCIwRw: Downloading webpage
[youtube] gTeubeCIwRw: Downloading ios player API JSON
[youtube] gTeubeCIwRw: Downloading m3u8 information
[info] gTeubeCIwRw: Downloading 1 format(s): 315+251
[info] There are no subtitles for the requested languages


config2:
❯ yt-dlp https://www.bilibili.com/video/BV1bE421w78J/
[BiliBili] Extracting URL: https://www.bilibili.com/video/BV1bE421w78J/
[BiliBili] 1bE421w78J: Downloading webpage
Extracting cookies from firefox
Extracted 2088 cookies from firefox
[BiliBili] BV1bE421w78J: Extracting videos in anthology
[BiliBili] 1656334462: Extracting chapters
[BiliBili] BV1bE421w78J: Extracting subtitle info 1620997229
[BiliBili] BV1bE421w78J: Downloading JSON metadata
[BiliBili] BV1bE421w78J: Downloading JSON metadata
[info] BV1bE421w78J: Downloading subtitles: zh-CN, en-US
[info] BV1bE421w78J: Downloading 1 format(s): 100113+30280
[info] Writing video subtitles to: D:\Video\Entertainment\英特尔该做出表示了： 芯片内部氧化, 新的微码, &评测者的困难【Gamers Nexus】 [BV1bE421w78J].zh-CN.srt
[info] Writing video subtitles to: D:\Video\Entertainment\英特尔该做出表示了： 芯片内部氧化, 新的微码, &评测者的困难【Gamers Nexus】 [BV1bE421w78J].en-US.srt

❯ yt-dlp https://www.youtube.com/watch?v=gTeubeCIwRw
Extracting cookies from firefox
Extracted 2088 cookies from firefox
[youtube] Extracting URL: https://www.youtube.com/watch?v=gTeubeCIwRw
[youtube] gTeubeCIwRw: Downloading webpage
[youtube] gTeubeCIwRw: Downloading ios player API JSON
[youtube] gTeubeCIwRw: Downloading m3u8 information
[info] gTeubeCIwRw: Downloading 1 format(s): 315+251
[info] There are no subtitles for the requested languages


config3:
❯ yt-dlp https://www.bilibili.com/video/BV1bE421w78J/
[BiliBili] Extracting URL: https://www.bilibili.com/video/BV1bE421w78J/
[BiliBili] 1bE421w78J: Downloading webpage
Extracting cookies from firefox
Extracted 2088 cookies from firefox
[BiliBili] BV1bE421w78J: Extracting videos in anthology
[BiliBili] 1656334462: Extracting chapters
[info] BV1bE421w78J: Downloading 1 format(s): 100113+30280
[info] There are no subtitles for the requested languages

❯ yt-dlp https://www.youtube.com/watch?v=gTeubeCIwRw
Extracting cookies from firefox
Extracted 2088 cookies from firefox
[youtube] Extracting URL: https://www.youtube.com/watch?v=gTeubeCIwRw
[youtube] gTeubeCIwRw: Downloading webpage
[youtube] gTeubeCIwRw: Downloading ios player API JSON
[youtube] gTeubeCIwRw: Downloading m3u8 information
[info] gTeubeCIwRw: Downloading subtitles: en
[info] gTeubeCIwRw: Downloading 1 format(s): 315+251
```

**Comment by grqz** [comment]
Have you tried `--write-subs --write-auto-subs --embed-subs --compat-options no-keep-subs` yet(https://github.com/yt-dlp/yt-dlp/issues/630#issuecomment-893659460)?
Also, you might need **logged in cookies** to download subtitles from bilibili.
Your conf should look like:
```
--write-subs
--write-auto-subs
--embed-subs
--compat-options no-keep-subs
--sub-langs "zh-CN,ai-zh,en.*"
--embed-thumbnail
--embed-metadata
--cookies cookies.txt
```
I changed en-US to en.* because youtube subtitle language codes for English are en and en-orig. That's also why you can't download subtitles for the second video(the yt one) with `--sub-langs "zh-CN,ai-zh,en-US"`(as in config1 and config2)

**Comment by dirkf** [comment]
For a clueless Westerner, `ai-zh` is ?

It appears to be the Chinese localisation of a language that isn't known to G, nor to the `ISO639Utils` class either here or upstream.
