### ISSUE TITLE
[twitter / x.com] "Upload date" metadata shows yesterdays date for 'Spaces' live today. [May be a twitter issue] 

### ISSUE THREAD

**Issue by daltek** [yt-dlp/yt-dlp#10524]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

UK

### Provide a description that is worded well enough to be understood

When Downloading a Twitter Spaces audio that was Live just a few minutes ago the Date in the %(upload_date)s field (and metadata as shown by `mediainfo`) shows Yesterdays date (20240720).  
I know for sure this was live today 20240721. 

I tested with one other Twitter video, and got the same result (but I'm not certain that that was uploaded today).  I tested with a recent Youtube upload and got the correct date.

During download, each "chunk" has a unix time-stamp which was correct (todays date), but maybe the incorrect metadata comes from Twitter.  (sorry to waste your time in that case)

I greatly appreciate your efforts on this extractor, Thank you.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '-fb', '--cookies-from-browser', 'firefox', 'https://x.com/i/spaces/1nAJEpmADwyGL']
[debug] User config "/home/loz/.config/yt-dlp/config": ['--no-mtime', '--restrict-filenames', '-o', '~/Downloads/yt/%(title)s_%(upload_date)s_f%(format_id)s_%(id)s.%(ext)s', '--write-auto-sub', '--write-sub', '--sub-lang', 'en,EN,en-gb,en-GB,EN-GB,en-ca,en-CA,EN-CA,en-ie,en-IE,EN-IE,en-us,en-US,EN-US,eng,ENG,english,English,ENGLISH,subtitles,en*,EN*', '--sub-format', 'best', '--embed-sub', '--add-metadata', '--format=22/18/95/94', '--remux-video=aac>m4a/mov>mp4/webm>mkv']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.07.16 from yt-dlp/yt-dlp [89a161e8c] (zip)
[debug] Python 3.11.9 (CPython x86_64 64bit) - Linux-6.9.9-1-default-x86_64-with-glibc2.39 (OpenSSL 3.1.4 24 Oct 2023, glibc 2.39)
[debug] exe versions: ffmpeg 6.1.1 (setts), ffprobe 6.1.1
[debug] Optional libraries: brotli-1.1.0, certifi-2024.07.04, pycrypto-3.20.0, requests-2.32.3, sqlite3-3.46.0, urllib3-2.1.0
[debug] Proxy map: {}
Extracting cookies from firefox
[debug] Extracting cookies from: "/home/loz/.mozilla/firefox/dnxhsb3t.default-release/cookies.sqlite"
Extracted 977 cookies from firefox
[debug] Request Handlers: urllib, requests
[debug] Loaded 1829 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.07.16 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.07.16 from yt-dlp/yt-dlp)
[twitter:spaces] Extracting URL: https://x.com/i/spaces/1nAJEpmADwyGL
[twitter:spaces] 1nAJEpmADwyGL: Downloading GraphQL JSON
[twitter:spaces] 28_1814646568852856836: Downloading legacy API JSON
[twitter:spaces] 28_1814646568852856836: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[info] 1nAJEpmADwyGL: Downloading 1 format(s): 0
[info] There are no subtitles for the requested languages
[debug] Invoking ffmpeg downloader on "https://prod-fastly-eu-central-1.video.pscp.tv/Transcoding/v1/hls/MSEbNcDdur2Y5t8L-WIlQfxfPZEjcHQUYKbA5bFDLStuLD_3RK34qUPZssWcrgcayfqEwXykNeMp6FQpkZIEWQ/non_transcode/eu-central-1/periscope-replay-direct-prod-eu-central-1-public/audio-space/playlist_16725169884804435372.m3u8?type=replay"
[download] /home/loz/Downloads/yt/ETH_ETF_LIVE_Tuesday..._PulseChain_Price_is_Moving_20240720_f0_1nAJEpmADwyGL.m4a has already been downloaded
[download] 100% of   82.71MiB
[VideoRemuxer] Not remuxing media file "/home/loz/Downloads/yt/ETH_ETF_LIVE_Tuesday..._PulseChain_Price_is_Moving_20240720_f0_1nAJEpmADwyGL.m4a"; could not find a mapping for m4a
[EmbedSubtitle] There aren't any subtitles to embed
[Metadata] Adding metadata to "/home/loz/Downloads/yt/ETH_ETF_LIVE_Tuesday..._PulseChain_Price_is_Moving_20240720_f0_1nAJEpmADwyGL.m4a"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i file:/home/loz/Downloads/yt/ETH_ETF_LIVE_Tuesday..._PulseChain_Price_is_Moving_20240720_f0_1nAJEpmADwyGL.m4a -map 0 -dn -ignore_unknown -vn -acodec copy -write_id3v1 1 -metadata 'title=🍆 ETH ETF LIVE Tuesday… PulseChain Price is Moving 🤑' -metadata date=20240720 -metadata 'description=Twitter Space participated by Randy Hilarski, Crypto Medit₳tor 🤝💙🇬🇷🇳🇱, King Daniel The Great, k9kong 🍆 9inch.io, SuperSecretSpy, Uhlobaron jurAjPE, 🥜🧠Peanut Brain Unification Token 🥜🧠, Execute, 𝔸𝕃𝕄𝕀𝔾ℍ𝕋𝕐 👑, CoinHub, Pepito, Wiz, Oscar Salvatore' -metadata 'synopsis=Twitter Space participated by Randy Hilarski, Crypto Medit₳tor 🤝💙🇬🇷🇳🇱, King Daniel The Great, k9kong 🍆 9inch.io, SuperSecretSpy, Uhlobaron jurAjPE, 🥜🧠Peanut Brain Unification Token 🥜🧠, Execute, 𝔸𝕃𝕄𝕀𝔾ℍ𝕋𝕐 👑, CoinHub, Pepito, Wiz, Oscar Salvatore' -metadata purl=https://x.com/i/spaces/1nAJEpmADwyGL -metadata comment=https://x.com/i/spaces/1nAJEpmADwyGL -metadata 'artist=9inch DEX' -movflags +faststart file:/home/loz/Downloads/yt/ETH_ETF_LIVE_Tuesday..._PulseChain_Price_is_Moving_20240720_f0_1nAJEpmADwyGL.temp.m4a
```

**Comment by bashonly** [comment]
I think you want `release_date` / `release_timestamp`

**Comment by bashonly** [comment]
The space was created yesterday: https://x.com/9inch_io/status/1814648468423528517

It just didn't begin until today. 

`upload_date` is the date when the post was "uploaded", and `release_date` is the date when the stream actually began.

**Comment by bashonly** [comment]
To fix the metadata that is embedded with `--add-metadata` you can pass `--parse-metadata "release_date:%(meta_date)s"`
