### ISSUE TITLE
weird bug with -f ba* "ERROR: [generic] 'audiofile.m4a' is not a valid URL."

### ISSUE THREAD

**Issue by pato-pan** [yt-dlp/yt-dlp#10533]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

There's a weird bug that happens when I use -f ba*, where in addition to choosing my provided url as an input, it also adds a couple of filenames that were previously downloaded. This happens regardless of what folder I use or if I delete the files.

This doesn't happen if I use -f ba instead, which I will use from now on after realizing the documentation tells you that ba* doesn't actually download the best audio. It can't find a format for this video for example.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [x] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp -vU -f ba* "https://www.youtube.com/watch?v=kv_cwzAIOHs"
[debug] Command-line config: ['-vU', '-f', 'backroom labyrinth - Oliver Buckland [iC452qNLXFg].m4a', 'bad and boo night fever - Plexi Music [kg2P2jXAlXA].m4a', 'bass guy VS bald guy - Davie504 [9I9O20G_8eM].m4a', 'https://www.youtube.com/watch?v=kv_cwzAIOHs']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.07.16 from yt-dlp/yt-dlp [89a161e8c]
[debug] Python 3.12.4 (CPython x86_64 64bit) - Linux-6.9.10-zen1-1-zen-x86_64-with-glibc2.39 (OpenSSL 3.3.1 4 Jun 2024, glibc 2.39)
[debug] exe versions: ffmpeg 7.0.1 (setts), ffprobe 7.0.1, rtmpdump 2.4
[debug] Optional libraries: brotli-1.1.0, certifi-2024.07.04, mutagen-1.47.0, pycrypto-3.20.0, requests-2.32.3, sqlite3-3.46.0, urllib3-1.26.19, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1829 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.07.16 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.07.16 from yt-dlp/yt-dlp)
[generic] Extracting URL: bad and boo night fever - Plexi Music [kg2P2jXAlXA].m4a
ERROR: [generic] 'bad and boo night fever - Plexi Music [kg2P2jXAlXA].m4a' is not a valid URL. Set --default-search "ytsearch" (or run  yt-dlp "ytsearch:bad and boo night fever - Plexi Music [kg2P2jXAlXA].m4a" ) to search YouTube
  File "/usr/lib/python3.12/site-packages/yt_dlp/extractor/common.py", line 740, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/yt_dlp/extractor/generic.py", line 2358, in _real_extract
    raise ExtractorError(

[generic] Extracting URL: bass guy VS bald guy - Davie504 [9I9O20G_8eM].m4a
ERROR: [generic] 'bass guy VS bald guy - Davie504 [9I9O20G_8eM].m4a' is not a valid URL. Set --default-search "ytsearch" (or run  yt-dlp "ytsearch:bass guy VS bald guy - Davie504 [9I9O20G_8eM].m4a" ) to search YouTube
  File "/usr/lib/python3.12/site-packages/yt_dlp/extractor/common.py", line 740, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/yt_dlp/extractor/generic.py", line 2358, in _real_extract
    raise ExtractorError(

[youtube] Extracting URL: https://www.youtube.com/watch?v=kv_cwzAIOHs
[youtube] kv_cwzAIOHs: Downloading webpage
[youtube] kv_cwzAIOHs: Downloading ios player API JSON
[debug] [youtube] Extracting signature function js_d60b0ef9_103
[debug] Loading youtube-sigfuncs.js_d60b0ef9_103 from cache
[debug] Loading youtube-nsig.d60b0ef9 from cache
[debug] [youtube] Decrypted nsig IyJWurqKGL5LPm4w => zLd_TusbBdwUmg
[debug] Loading youtube-nsig.d60b0ef9 from cache
[debug] [youtube] Decrypted nsig Cjr63ABqnmtE-eu6 => _4qyM-tcTQRhTA
[debug] [youtube] Extracting signature function js_d60b0ef9_107
[debug] Loading youtube-sigfuncs.js_d60b0ef9_107 from cache
[youtube] kv_cwzAIOHs: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
ERROR: [youtube] kv_cwzAIOHs: Requested format is not available. Use --list-formats for a list of available formats
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 1626, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 1782, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 1841, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 2977, in process_video_result
    raise ExtractorError(
yt_dlp.utils.ExtractorError: [youtube] kv_cwzAIOHs: Requested format is not available. Use --list-formats for a list of available formats
```

**Comment by Grub4K** [comment]
Shell issue. `ba*` is getting expanded by your shell, you have to quote it (`-f "bv*"`)

**Comment by seproDev** [comment]
Also I don't think there is ever a reason to use `ba*`. From the readme:
> `ba*`, `bestaudio*`: Select the best quality format that contains audio. It may also contain video. Equivalent to `best*[acodec!=none]` ([Do not use!](https://github.com/yt-dlp/yt-dlp/issues/979#issuecomment-919629354))

Are you maybe just looking for `-x` to either download the available audio track or extract it from a merged format if no seperate track is available?

**Comment by pato-pan** [comment]
> Also I don't think there is ever a reason to use ba*.

> This doesn't happen if I use -f ba instead, which I will use from now on after realizing the documentation tells you that ba* doesn't actually download the best audio. It can't find a format for this video for example.

**Comment by Cellularhacker** [comment]
I have a same issue in currently.

```shell
[generic] Extracting URL: -
ERROR: [generic] '-' is not a valid URL
[generic] Extracting URL: [%(id)s].%(ext)s
ERROR: [generic] '[%(id)s].%(ext)s' is not a valid URL
```

This is my command I executed. The interesting thing is it had no problem during download shorts and live stream archives.
It seems like making a problem move to start downloading a playlist of the channel(s).
```shell
yt-dlp \
        --break-on-reject \
        --download-archive archive.txt \
        -N ${CONC_FRAG} \
        --buffer-size ${BUFFER_SIZE} \
        --progress \
        --cookies ${COOKIES} \
        -f "(bv*[vcodec~='^((he|a)vc|h26[45])']+ba) / (bv*+ba/b)" \
        ${CHANNEL_URL} \
        --compat-options no-live-chat \
        --playlist-reverse \
        --embed-subs \
        --embed-thumbnail \
        --embed-metadata \
        --continue \
        -t sleep \
        -o ${YTDLP_OUTPUT_ROOT}/${OUTPUT_FORMAT}
```

**Comment by seproDev** [comment]
@Cellularhacker Please open a new issue, with a complete verbose log. This seems like a shell escaping issue.
