### ISSUE TITLE
[Abematv]Problem for abematv-license

### ISSUE THREAD

**Issue by njpengqc** [yt-dlp/yt-dlp#10541]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I've read the previous issue, but it's not enough for me to fix this abematv-license issue

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://abema.tv/video/episode/25-269_s1_p1']
[debug] Encodings: locale cp936, fs utf-8, pref cp936, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.07.16 from yt-dlp/yt-dlp [89a161e8c] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22631-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.07.04, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1829 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.07.16 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.07.16 from yt-dlp/yt-dlp)
[AbemaTV] Extracting URL: https://abema.tv/video/episode/25-269_s1_p1
[AbemaTV] Authorizing
[AbemaTV] 25-269_s1_p1: Downloading webpage
[AbemaTV] 25-269_s1_p1: Checking playability
[AbemaTV] 25-269_s1_p1: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: best/bestvideo+bestaudio
[info] 25-269_s1_p1: Downloading 1 format(s): 5300
[debug] Invoking hlsnative downloader on "https://vod-abematv.akamaized.net/program/25-269_s1_p1/1080/playlist.m3u8?aver=1"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 178
[download] Destination: 第1話 ロシア語でデレるアーリャさん [25-269_s1_p1].mp4
[debug] File locking is not supported. Proceeding without locking
[download] 第1話 ロシア語でデレるアーリャさん [25-269_s1_p1].mp4.part-Frag1 has already been downloaded
[download]   0.0% of ~ 364.10MiB at      0.00B/s ETA Unknown (frag 1/178)ERROR: unable to download video data: <urlopen error unknown url type: abematv-license>
Traceback (most recent call last):
  File "yt_dlp\networking\_urllib.py", line 398, in _send
  File "urllib\request.py", line 525, in open
  File "urllib\request.py", line 547, in _open
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 1425, in unknown_open
urllib.error.URLError: <urlopen error unknown url type: abematv-license>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 3483, in process_info
  File "yt_dlp\YoutubeDL.py", line 3203, in dl
  File "yt_dlp\downloader\common.py", line 466, in download
  File "yt_dlp\downloader\hls.py", line 381, in real_download
  File "yt_dlp\downloader\fragment.py", line 516, in download_and_append_fragments
  File "yt_dlp\downloader\fragment.py", line 358, in decrypt_fragment
  File "yt_dlp\downloader\fragment.py", line 347, in _get_key
  File "yt_dlp\YoutubeDL.py", line 4165, in urlopen
  File "yt_dlp\networking\common.py", line 117, in send
  File "yt_dlp\networking\_helper.py", line 208, in wrapper
  File "yt_dlp\networking\common.py", line 340, in send
  File "yt_dlp\networking\_urllib.py", line 413, in _send
yt_dlp.networking.exceptions.TransportError: <urlopen error unknown url type: abematv-license>
```

**Comment by bashonly** [comment]
`yt-dlp --update-to nightly`

**Comment by njpengqc** [comment]
I have upgraded to the nightly version of yt-dlp, but I encountered an abematv-license error when trying to select high-definition videos


> yt-dlp -f 5300 https://abema.tv/video/episode/25-269_s1_p1
[AbemaTV] Extracting URL: https://abema.tv/video/episode/25-269_s1_p1
[AbemaTV] Authorizing
[AbemaTV] 25-269_s1_p1: Downloading webpage
[AbemaTV] 25-269_s1_p1: Checking playability
[AbemaTV] 25-269_s1_p1: Downloading m3u8 information
[info] 25-269_s1_p1: Downloading 1 format(s): 5300
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 178
[download] Destination: 第1話 ロシア語でデレるアーリャさん [25-269_s1_p1].mp4
[download]   0.3% of ~ 728.21MiB at  374.22KiB/s ETA 18:29:24 (frag 1/178)ERROR: unable to download video data: <urlopen error unknown url type: abematv-license>

**Comment by bashonly** [comment]
can you add `-v` to your command and copy/paste the complete output please

**Comment by njpengqc** [comment]
I have upgraded to the nightly version of yt-dlp, but I encountered an abematv-license error when trying to select high-definition videos

> yt-dlp -f 5300 https://abema.tv/video/episode/25-269_s1_p1
[AbemaTV] Extracting URL: https://abema.tv/video/episode/25-269_s1_p1
[AbemaTV] Authorizing
[AbemaTV] 25-269_s1_p1: Downloading webpage
[AbemaTV] 25-269_s1_p1: Checking playability
[AbemaTV] 25-269_s1_p1: Downloading m3u8 information
[info] 25-269_s1_p1: Downloading 1 format(s): 5300
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 178
[download] Destination: 第1話 ロシア語でデレるアーリャさん [25-269_s1_p1].mp4
[download]   0.3% of ~ 728.21MiB at  374.22KiB/s ETA 18:29:24 (frag 1/178)ERROR: unable to download video data: <urlopen error unknown url type: abematv-license>
