### ISSUE TITLE
Download private videos

### ISSUE THREAD

**Issue by verystupidlysimple** [yt-dlp/yt-dlp#10547]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

i want to download a private video
idc if you have to "ask the owner to grant you permission" or "you just can't"
i need to download this video
i'm so tired of losing stuff like this

BECAUSE IT'S POSSIBLE
https://quiteaplaylist.com/
there are already obscure websites that are able to bypass the "private video' screen
but of course they won't give you the actual video
this website grabs the channel, date, and even creates a wayback machine archive

fym yt-dlp can't download it?
maybe rescript it to work

i tried using the Network method to try and get the playback
i even tried using "Preview Page" on mobile to get past the screen and it still didn't work 

if you want the link it's https://www.youtube.com/watch?v=0DhaBOfYmIY&t=0s
video is called "Deadlands OST - Voxlblade"
the original music comes from the My Hero Academia soundtrack, it sounded very ghastly and howling but thar's also lost

if i can learn how to download private vids then i'll recover the hundreds of videos in my playlist
sorry i'm tweaking out right now

delete this post if it's not relevant but there has to be a way, i just know it.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
Not gonna happen
