### ISSUE TITLE
[youku] Youku server reported error -6004: 客户端无权播放,201

### ISSUE THREAD

**Issue by write3371** [yt-dlp/yt-dlp#10549]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

China

### Provide a description that is worded well enough to be understood

[youku]  客户端无权播放

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://v.youku.com/v_show/id_XNTgzMTg1NDg0NA==.html']
[debug] Encodings: locale cp936, fs utf-8, pref cp936, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.07.16 from yt-dlp/yt-dlp [89a161e8c] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22631-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-116395-g4acb9b7d10-20240723 (setts), ffprobe N-116395-g4acb9b7d10-20240723
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.07.04, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1829 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.07.16 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.07.16 from yt-dlp/yt-dlp)
[youku] Extracting URL: https://v.youku.com/v_show/id_XNTgzMTg1NDg0NA==.html
[youku] XNTgzMTg1NDg0NA: Retrieving cna info
[youku] XNTgzMTg1NDg0NA: Downloading JSON metadata
ERROR: [youku] XNTgzMTg1NDg0NA: Youku server reported error -6004: 客户端无权播放,201; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 740, in extract
  File "yt_dlp\extractor\youku.py", line 171, in _real_extract
```
```

**Comment by bashonly** [comment]
please share **complete verbose output**

add `-vU` to your command, copy all of the output to the clipboard, and paste it into your comment here

**Comment by hugepower** [comment]
Change the `ccode` from `5024` to `5064` to fix the issue with Youku video extraction in the [yt_dlp/extractor/youku.py](https://github.com/yt-dlp/yt-dlp/blob/28d485714fef88937c82635438afba5db81f9089/yt_dlp/extractor/youku.py#L139) file. This issue is often related to the dynamically changing ccode value. 

**Before modification:**

```
yt-dlp https://v.youku.com/v_show/id_XNTgzMTg1NDg0NA\=\=.html
[youku] Extracting URL: https://v.youku.com/v_show/id_XNTgzMTg1NDg0NA==.html
[youku] XNTgzMTg1NDg0NA: Retrieving cna info
[youku] XNTgzMTg1NDg0NA: Downloading JSON metadata
ERROR: [youku] XNTgzMTg1NDg0NA: Youku server reported error -6004: 客户端无权播放,201; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

**After modification:**

```
yt-dlp https://v.youku.com/v_show/id_XNTgzMTg1NDg0NA\=\=.html
[youku] Extracting URL: https://v.youku.com/v_show/id_XNTgzMTg1NDg0NA==.html
[youku] XNTgzMTg1NDg0NA: Retrieving cna info
[youku] XNTgzMTg1NDg0NA: Downloading JSON metadata
[info] XNTgzMTg1NDg0NA: Downloading 1 format(s): 4
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 5
[download] Destination: 改造铅笔更实用，装上笔刷笔帽，能清理桌面的文具 [XNTgzMTg1NDg0NA].mp4
[download] 100% of   32.65MiB in 00:00:01 at 18.76MiB/s
[FixupM3u8] Fixing MPEG-TS in MP4 container of "改造铅笔更实用，装上笔刷笔帽，能清理桌面的文具 [XNTgzMTg1NDg0NA].mp4"
```

**Comment by bashonly** [comment]
> This issue is often related to the dynamically changing ccode value.

Is there any way that we can extract/calculate this value instead of hard-coding it?

**Comment by thinkiny** [comment]
5026 is not working，same as 0526

**Comment by bashonly** [comment]
> 5026 is not working

> Change the ccode from 5024 to **5064**

**Comment by grqz** [comment]
isn't it 0564?
though I can't find the js that contains this value. that's an old API.
