### ISSUE TITLE
Requested format is not available when trying to download Vimeo video

### ISSUE THREAD

**Issue by osuosu** [yt-dlp/yt-dlp#10556]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I'm having a lot of issues trying to download this video:

`https://vimeo.com/989892338/28e7499265`

I've tried this:

`yt-dlp -f mp4 "https://vimeo.com/989892338/28e7499265"`

But it just downloads the mp4 without audio. I've tried this:

`yt-dlp -f "bv*[vcodec^=avc]+ba[acodec^=mp4a]/b" "https://vimeo.com/989892338/28e7499265"`

Which gives me the following errors:

```
[vimeo] Extracting URL: https://vimeo.com/989892338/28e7499265
[vimeo] 989892338: Downloading viewer info
[vimeo] 989892338: Downloading API JSON
[vimeo] 989892338: Downloading API JSON
[vimeo] 989892338: Downloading JSON metadata
[vimeo] 989892338: Downloading akfire_interconnect_quic m3u8 information
[vimeo] 989892338: Downloading fastly_skyfire m3u8 information
[vimeo] 989892338: Downloading akfire_interconnect_quic MPD information
WARNING: [vimeo] 989892338: Failed to parse XML: not well-formed (invalid token): line 1, column 0
[vimeo] 989892338: Downloading fastly_skyfire MPD information
WARNING: [vimeo] 989892338: Failed to parse XML: not well-formed (invalid token): line 1, column 0
ERROR: [vimeo] 989892338: Requested format is not available. Use --list-formats for a list of available formats
``` 

Which is strange as I'm trying to download an mp4 which I did successfully with my first command.

Can anyone help me get the highest quality mp4 video from that URL via a yt-dlp command?

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
use `-S vcodec:h264,res,acodec:aac` and no `-f` arg

**Comment by osuosu** [comment]
> use `-S vcodec:h264,res,acodec:aac` and no `-f` arg

Thanks for this. Would you be able to help me out with the full command please? I'm not sure how to integrate your advice unfortunately...

**Comment by osuosu** [comment]
Amazing, thank you

**Comment by uzairash** [comment]
I am getting this same error for youtube videos as well 

yt_dlp.utils.DownloadError: ERROR: [youtube] l5k1ai_GBDE: Requested format is not available. Use --list-formats for a list of available formats
