### ISSUE TITLE
[YouTube] MP4 format download files do not have audio

### ISSUE THREAD

**Issue by sewflag** [yt-dlp/yt-dlp#10553]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United States

### Provide a description that is worded well enough to be understood

Download YouTube using the -f mp4 format, and the result file will not have any audio.  If -f mp4 option is removed, the result file will have audio.  Also, there is an error message from yt-dlp:  Unable to extract nsig function code (caused by RegexNotFoundError

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '-f', 'mp4', 'https://www.youtube.com/watch?v=6DUKXV38HMg']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.07.16 from yt-dlp/yt-dlp [89a161e8c] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-110062-g9413bdc381-20230322 (setts), ffprobe N-110062-g9413bdc381-20230322
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.07.04, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1829 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.07.16 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.07.16 from yt-dlp/yt-dlp)
[youtube] Extracting URL: https://www.youtube.com/watch?v=6DUKXV38HMg
[youtube] 6DUKXV38HMg: Downloading webpage
[youtube] 6DUKXV38HMg: Downloading ios player API JSON
[youtube] 6DUKXV38HMg: Downloading player 3400486c
WARNING: [youtube] 6DUKXV38HMg: nsig extraction failed: Some formats may be missing
         n = ZIECP5pNJmLxYeasrn ; player = https://www.youtube.com/s/player/3400486c/player_ias.vflset/en_US/base.js
[debug] [youtube] Unable to extract nsig function code (caused by RegexNotFoundError('Unable to extract \x1b[0;94mInitial JS player n function name\x1b[0m; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [youtube] 6DUKXV38HMg: nsig extraction failed: Some formats may be missing
         n = gcGDFSsN_dDJB_0ykf ; player = https://www.youtube.com/s/player/3400486c/player_ias.vflset/en_US/base.js
[youtube] 6DUKXV38HMg: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[info] Testing format 614
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 121
[download] Destination: C:\Users\Jackie\Documents\DailyTravel\tmpx1unsvzx.tmp
[debug] File locking is not supported. Proceeding without locking
[download] 100% of    712.00B in 00:00:00 at 5.23KiB/s
[info] 6DUKXV38HMg: Downloading 1 format(s): 614
[debug] Invoking hlsnative downloader on "https://manifest.googlevideo.com/api/manifest/hls_playlist/expire/1721894208/ei/4LChZur8Jpi7ir4Pz56eoAg/ip/146.85.128.246/id/e8350a5d5dfc1cc8/itag/614/source/youtube/requiressl/yes/ratebypass/yes/pfa/1/wft/1/sgovp/clen%3D57378107%3Bdur%3D661.527%3Bgir%3Dyes%3Bitag%3D248%3Blmt%3D1721869614805943/rqh/1/hls_chunk_host/rr2---sn-q4flrnsk.googlevideo.com/xpc/EgVo2aDSNQ%3D%3D/mh/Nm/mm/31,26/mn/sn-q4flrnsk,sn-a5msen7s/ms/au,onr/mv/m/mvi/2/pl/21/initcwndbps/982500/vprv/1/playlist_type/DVR/dover/13/txp/530F224/mt/1721872391/fvip/2/short_key/1/keepalive/yes/sparams/expire,ei,ip,id,itag,source,requiressl,ratebypass,pfa,wft,sgovp,rqh,xpc,vprv,playlist_type/sig/AJfQdSswRgIhAOq1PP7SFcCD1xaeADKHrru5O2Eea7jtsRJ1wKl1W1zHAiEA1w-Mlc9duwpH6A5YoHRWBMxGfluOYvox_cG4lH-jB4c%3D/lsparams/hls_chunk_host,mh,mm,mn,ms,mv,mvi,pl,initcwndbps/lsig/AGtxev0wRQIgRCvWatUi7DY1LpbNmZlw3uW-ev0fx5poUpQVT9TAs2ACIQCdjfUxVMJ03284M2P_BmGGGCr6EyVlfq_9FfmlM5leeA%3D%3D/playlist/index.m3u8"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 121
[download] Destination: President Biden addresses the nation just days after announcing he won't run for reelection [6DUKXV38HMg].mp4
[download] 100% of   54.82MiB in 00:00:09 at 5.95MiB/s
[debug] ffprobe command line: ffprobe -hide_banner -show_format -show_streams -print_format json "file:President Biden addresses the nation just days after announcing he won't run for reelection [6DUKXV38HMg].mp4"
```

**Comment by distinctjuggle** [comment]
I was running into this issue earlier today but with a different symptom.  Runing `yt-dlp -F url` will show: "nsig extraction failed: Some formats may be missing", as does your post, which I believe is the underling issue.  Some formats which *should* be found, are not.

**Comment by bashonly** [comment]
> WARNING: [youtube] 6DUKXV38HMg: nsig extraction failed: Some formats may be missing

Run `yt-dlp --update-to nightly` to fix this, just like the issue template checklist told you to do

`-f mp4` is generally a bad idea though, unless you want a 360p mp4 from youtube. Pass `-S ext` if you want the highest quality mp4 format(s), or pass `-S vcodec:h264,res,acodec:aac` if you want the highest quality h264+aac mp4 formats

**Comment by distinctjuggle** [comment]
> > WARNING: [youtube] 6DUKXV38HMg: nsig extraction failed: Some formats may be missing
> 
> Run `yt-dlp --update-to nightly` to fix this, just like the issue template checklist told you to do
> 
> `-f mp4` is generally a bad idea though, unless you want a 360p mp4 from youtube. Pass `-S ext` if you want the highest quality mp4 format(s), or pass `-S vcodec:h264,res,acodec:aac` if you want the highest quality h264+aac mp4 formats

Slightly off topic, but isn't opus a better audio quality than aac for any arbitrary video?  It offers higher quality at the same data rate.
