### ISSUE TITLE
QUB/TVA, "Unsupported URL"

### ISSUE THREAD

**Issue by HidingCrab** [yt-dlp/yt-dlp#10555]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Canada

### Provide a description that is worded well enough to be understood

Qub/TVA no longer seems to be supported.
Example URL: https://www.tvaplus.ca/tva/le-baiser-du-barbu/le-baiser-du-barbu-886644190

Using a VPN, making my laptop look like it's coming from Montreal, Canada. The video URL of works within my Windows Firefox web browser.

Qub/TVA worked about one year ago. I had yt-dlp stable@2023.03.04 at that time, and put in the "extractor" folder the tva.py file in [this](https://github.com/ytdl-org/youtube-dl/issues/31240#issuecomment-1249681732) patch.

This issue I'm reporting is different than [this](https://github.com/yt-dlp/yt-dlp/issues/9190) issue, that also reports that Qub/TVA doesn't work, but instead reports that it doesn't work due to failed JSON metadata.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp -vU --write-sub "https://www.tvaplus.ca/tva/le-baiser-du-barbu/le-baiser-du-barbu-886644190"

[debug] Command-line config: ['-vU', '--write-sub', 'https://www.tvaplus.ca/tva/le-baiser-du-barbu/le-baiser-du-barbu-886644190']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.07.25 from yt-dlp/yt-dlp [f0993391e] (pip)
[debug] Python 3.11.9 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 3.0.13 30 Jan 2024)
[debug] exe versions: ffmpeg 6.0-full_build-www.gyan.dev (setts), ffprobe 6.0-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.05.07, mutagen-1.46.0, requests-2.32.3, sqlite3-3.45.1, urllib3-2.1.0, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1829 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.07.25 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.07.25 from yt-dlp/yt-dlp)
[generic] Extracting URL: https://www.tvaplus.ca/tva/le-baiser-du-barbu/le-baiser-du-barbu-886644190
[generic] le-baiser-du-barbu-886644190: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] le-baiser-du-barbu-886644190: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://www.tvaplus.ca/tva/le-baiser-du-barbu/le-baiser-du-barbu-886644190
Traceback (most recent call last):
  File "C:\Users\stepi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\yt_dlp\YoutubeDL.py", line 1626, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\stepi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\yt_dlp\YoutubeDL.py", line 1761, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "C:\Users\stepi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\yt_dlp\extractor\common.py", line 740, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\stepi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\yt_dlp\extractor\generic.py", line 2526, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.tvaplus.ca/tva/le-baiser-du-barbu/le-baiser-du-barbu-886644190
```

**Comment by dirkf** [comment]
... except that the metadata is now in `['pageProps']['staticEntity']` instead of `['initialProps']['pageProps']['fallbackData']`.

The qub.ca pages now redirect to tvaplus.ca.
