### ISSUE TITLE
[Feature Request] Combining `--parse-metadata` and `--flat-playlist`

### ISSUE THREAD

**Issue by ChillingPepper** [yt-dlp/yt-dlp#1055]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running yt-dlp version **2021.09.02**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description

Modifying metadata is currently not possible if playlist videos aren't extracted. Even though metadata may be limited in this case modifying it should be supported.

**Comment by pukkandan** [comment]
The metadata parser is implemented as a postprocessor - and postprocessors only run for each video. So this isn't really possible with the current architecture

**Comment by pukkandan** [comment]
This is already done. Forgot to close the issues
