### ISSUE TITLE
[bbc.co.uk] Cannot download iplayer series / playlist

### ISSUE THREAD

**Issue by superclarkk** [yt-dlp/yt-dlp#10551]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United Kingdom

### Provide a description that is worded well enough to be understood

Using the latest yt-dlp version, 2024.7.16.

I'm attempting to download season 3 of "His Dark Materials" using the following command: 

```
yt-dlp --yes-playlist -S ext,width:720 "https://www.bbc.co.uk/iplayer/episode/p0dgc5jg/his-dark-materials-series-3-1-the-enchanted-sleeper?seriesId=p0dgc2vk"
```

Rather than download all episodes, it downloads the first one, and exits. If I run the command again, it returns, "Dark Materials, Series 3, The Enchanted Sleeper.mp4 has already been downloaded", and exits.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp -vU --yes-playlist -S ext,width:720 "https://www.bbc.co.uk/iplayer/episode/p0dgc5jg/his-dark-materials-series-3-1-the-enchanted-sleeper?seriesId=p0dgc2vk"
[debug] Command-line config: ['-vU', '--yes-playlist', '-S', 'ext,width:720', 'https://www.bbc.co.uk/iplayer/episode/p0dgc5jg/his-dark-materials-series-3-1-the-enchanted-sleeper?seriesId=p0dgc2vk']
[debug] System config "/etc/yt-dlp.conf": ['-o', '/path/to/%(extractor)s/%(playlist_title)s/%(series)s-%(uploader)s-%(upload_date)s-%(title)s.%(ext)s', '--sub-lang', 'en', '--no-mtime']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.07.16 from yt-dlp/yt-dlp [89a161e8c] (pip)
[debug] Python 3.11.4 (CPython x86_64 64bit) - Linux-6.1.0-22-amd64-x86_64-with-glibc2.36 (OpenSSL 3.0.13 30 Jan 2024, glibc 2.36)
[debug] exe versions: ffmpeg 5.1.5-0 (setts), ffprobe 5.1.5-0, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.02.02, mutagen-1.47.0, requests-2.32.3, sqlite3-3.41.2, urllib3-2.2.1, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1829 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.07.16 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.07.16 from yt-dlp/yt-dlp)
[bbc.co.uk] Extracting URL: https://www.bbc.co.uk/iplayer/episode/p0dgc5jg/his-dark-materials-series-3-1-the-enchanted-sleeper?seriesId=p0dgc2vk
[bbc.co.uk] p0dgc5jg: Downloading video page
[bbc.co.uk] p0dgc5jg: Downloading playlist JSON
[bbc.co.uk] p0dgc67d: Downloading media selection JSON
[bbc.co.uk] p0dgc67d: Downloading m3u8 information
[bbc.co.uk] p0dgc67d: Downloading m3u8 information
[bbc.co.uk] p0dgc67d: Downloading m3u8 information
[bbc.co.uk] p0dgc67d: Downloading m3u8 information
[bbc.co.uk] p0dgc67d: Downloading m3u8 information
[bbc.co.uk] p0dgc67d: Downloading m3u8 information
[bbc.co.uk] p0dgc67d: Downloading MPD manifest
[bbc.co.uk] p0dgc67d: Downloading MPD manifest
[bbc.co.uk] p0dgc67d: Downloading MPD manifest
[bbc.co.uk] p0dgc67d: Downloading MPD manifest
[bbc.co.uk] p0dgc67d: Downloading MPD manifest
[bbc.co.uk] p0dgc67d: Downloading MPD manifest
[bbc.co.uk] p0dgc67d: Downloading media selection JSON
[bbc.co.uk] p0dgc67d: Downloading m3u8 information
[bbc.co.uk] p0dgc67d: Downloading m3u8 information
[bbc.co.uk] p0dgc67d: Downloading MPD manifest
[bbc.co.uk] p0dgc67d: Downloading MPD manifest
[bbc.co.uk] p0dgc67d: Downloading m3u8 information
[bbc.co.uk] p0dgc67d: Downloading m3u8 information
[bbc.co.uk] p0dgc67d: Downloading MPD manifest
[bbc.co.uk] p0dgc67d: Downloading MPD manifest
[bbc.co.uk] p0dgc67d: Downloading m3u8 information
[bbc.co.uk] p0dgc67d: Downloading m3u8 information
[bbc.co.uk] p0dgc67d: Downloading MPD manifest
[bbc.co.uk] p0dgc67d: Downloading MPD manifest
[debug] Sort order given by user: ext, width:720
[debug] Formats sorted by: hasvid, ie_pref, vext, aext, width:720(720.0), lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] p0dgc67d: Downloading 1 format(s): mf_cloudfront-1800-1
[debug] Invoking hlsnative downloader on "https://vod-hls-uk.live.cf.md.bbci.co.uk/usp/auth/vod/piff_abr_full_hd/624e99-p0dgc67d/vf_p0dgc67d_24c466cb-51a5-48cf-a390-122581b9c5e7.ism.hlsv2.ism/vf_p0dgc67d_24c466cb-51a5-48cf-a390-122581b9c5e7.ism.hlsv2-audio_eng_1=128000-video=1570000.m3u8"
[download] /path/to/bbc.co.uk/NA/NA-NA-NA-His Dark Materials, Series 3, The Enchanted Sleeper.mp4 has already been downloaded
[download] 100% of  679.24MiB
```

**Comment by dirkf** [comment]
By going to series 2 and checking the link for series 3, you get the actual series/season ID `p0dgc2vk`:
`https://www.bbc.co.uk/iplayer/episode/m000pb15/his-dark-materials-series-2-1-the-city-of-magpies?seriesId=p0dgc2vk`

Then the series page is https://www.bbc.co.uk/programmes/p0dgc2vk and the series/season playlist is https://www.bbc.co.uk/programmes/p0dgc2vk/episodes/player (the link `All available episodes`).

Unfortunately this happens:
```console
$ yt-dlp -vF --playlist-item 1 'https://www.bbc.co.uk/programmes/p0dgc2vk/episodes/player'
[debug] Command-line config: ['-vF', '--playlist-item', '1', 'https://www.bbc.co.uk/programmes/p0dgc2vk/episodes/player']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.07.16 from yt-dlp/yt-dlp [89a161e8c] (zip)
[debug] Python 3.9.19 (CPython i686 32bit) - Linux-4.4.0-210-generic-i686-with-glibc2.23 (OpenSSL 1.1.1w  11 Sep 2023, glibc 2.23)
[debug] exe versions: ffmpeg 4.3, ffprobe 4.3
[debug] Optional libraries: Cryptodome-3.11.0, certifi-2019.11.28, requests-2.25.1, secretstorage-3.2.0, sqlite3-3.37.2, urllib3-1.25.11
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Loaded 1829 extractors
[bbc.co.uk:playlist] Extracting URL: https://www.bbc.co.uk/programmes/p0dgc2vk/episodes/player
[bbc.co.uk:playlist] p0dgc2vk: Downloading webpage
[download] Downloading playlist: BBC One - His Dark Materials, Series 3 - Available now
[bbc.co.uk:playlist] Playlist BBC One - His Dark Materials, Series 3 - Available now: Downloading 1 items
[download] Downloading item 1 of 1
[bbc.co.uk] Extracting URL: http://www.bbc.co.uk/programmes/p0dgc5jg
[bbc.co.uk] p0dgc5jg: Downloading video page
[bbc.co.uk] p0dgc5jg: Downloading playlist JSON
[bbc.co.uk] p0dgc67d: Downloading media selection JSON
[bbc.co.uk] p0dgc67d: Downloading media selection JSON
ERROR: [bbc.co.uk] p0dgc5jg: bbc.co.uk returned error: selectionunavailable
  File "/home/df/./Downloads/yt-dlp-2024-07-16/yt_dlp/extractor/common.py", line 740, in extract
    ie_result = self._real_extract(url)
  File "/home/df/./Downloads/yt-dlp-2024-07-16/yt_dlp/extractor/bbc.py", line 572, in _real_extract
    programme_id, title, description, duration, formats, subtitles = self._download_playlist(group_id)
  File "/home/df/./Downloads/yt-dlp-2024-07-16/yt_dlp/extractor/bbc.py", line 459, in _download_playlist
    version_formats, version_subtitles = self._download_media_selector(programme_id)
  File "/home/df/./Downloads/yt-dlp-2024-07-16/yt_dlp/extractor/bbc.py", line 337, in _download_media_selector
    self._raise_extractor_error(last_exception)
  File "/home/df/./Downloads/yt-dlp-2024-07-16/yt_dlp/extractor/bbc.py", line 314, in _raise_extractor_error
    raise ExtractorError(

[download] Finished downloading playlist: BBC One - His Dark Materials, Series 3 - Available now
$
```
However your yt-dlp seems to have succeeded with the same show, so you could try again using the above `.../episodes/player` URL.

**Comment by bashonly** [comment]
> ```
> ERROR: [bbc.co.uk] p0dgc5jg: bbc.co.uk returned error: selectionunavailable
> ```

looks like #6965

**Comment by dirkf** [comment]
I thought that was [familiar](https://github.com/yt-dlp/yt-dlp/issues/2979#issuecomment-1065198868). Somehow the fix didn't get into the recent extractor update.

**Comment by superclarkk** [comment]
Thanks for the feedback, guys.

The "mistake" I made was to use duckduckgo to search for [iplayer His Dark Materials Season 3](https://duckduckgo.com/?q=iplayer+his+dark+materials+series+3&ia=web), which gives an episode link in series 3 rather than the series link. I couldn't find a way to get the series link from that iplayer page. Incidentally, google gives the series link: [iplayer His Dark Materials Season 3](https://www.google.com/search?q=iplayer+his+dark+materials+series+3).

However, searching for "His Dark Materials" in the iplayer search returns the series link.

As an aside, using the following format string does not give the episode number. Instead, it returns, for example, "NA-NA-NA-NA-His Dark Materials, Series 3, The Enchanted Sleeper.mp4", which makes it difficult to know what order the episodes are in. Am I doing something wrong, or is this a bug? I'm happy to raise a new issue, if needed.

```
-o /path/to/%(extractor)s/%(playlist_title)s/%(series)s-%(uploader)s-%(upload_date)s-%(episode_number)d-%(title)s.%(ext)s
```

I've also tried, `%(episode_number)s` and `%(episode)s` with the same result.

**Comment by superclarkk** [comment]
> As an aside, using the following format string does not give the episode number. Instead, it returns, for example, "NA-NA-NA-NA-His Dark Materials, Series 3, The Enchanted Sleeper.mp4", which makes it difficult to know what order the episodes are in. Am I doing something wrong, or is this a bug? I'm happy to raise a new issue, if needed.
> 
> ```
> -o /path/to/%(extractor)s/%(playlist_title)s/%(series)s-%(uploader)s-%(upload_date)s-%(episode_number)d-%(title)s.%(ext)s
> ```

Can anyone give some guidance on this?

**Comment by superclarkk** [comment]
To summarize, to resolve this issue, if it's technically possible, imho yt-dlp should be able to derive the series ID from the episode link when the `--yes-playlist` option is used.

As I haven't received a response to my question, I'll open another ticket.

**Comment by bashonly** [comment]
> imho yt-dlp should be able to derive the series ID from the episode link when the `--yes-playlist` option is used.

No, that's not the intended use / expected behavior of `--yes-playlist`. `--yes-playlist` is the default behavior, and `--no-playlist` is used to alter the default behavior when a link is passed to yt-dlp where it is ambiguous to whether it is a playlist or single video (e.g. `https://www.youtube.com/watch?v=VIDEO_ID&list=PLAYLIST_ID`).

The link in your OP, while it contains a query param for the series ID, is not the actual series URL, and therefore it would be unexpected for the default behavior to be changed to downloading the entire series. 

> As an aside, using the following format string does not give the episode number. Instead, it returns, for example, "NA-NA-NA-NA-His Dark Materials, Series 3, The Enchanted Sleeper.mp4", which makes it difficult to know what order the episodes are in. Am I doing something wrong, or is this a bug? I'm happy to raise a new issue, if needed.
> 
> ```
> -o /path/to/%(extractor)s/%(playlist_title)s/%(series)s-%(uploader)s-%(upload_date)s-%(episode_number)d-%(title)s.%(ext)s
> ```

You are getting `NA`'s in your output filename because `series`, `uploader`, `upload_date` and `episode_number` are not extracted by this extractor. These are the only fields that are currently extracted:

```py
        return {
            'id': programme_id,
            'title': title,
            'description': description,
            'thumbnail': self._og_search_thumbnail(webpage, default=None),
            'duration': duration,
            'formats': formats,
            'subtitles': subtitles,
        }
```

There is already an open request for episode number metadata to be extracted: #2976

If upload date and uploader information is available in the webpage, your new ticket could instead be a site feature request for that uploader metadata to be extracted

**Comment by superclarkk** [comment]
> No, that's not the intended use / expected behavior of `--yes-playlist`

Thanks for the clarification. So, does that mean this ticket isn't valid? If it is valid, what do you see as the outstanding issue?

I've cobbled together a workaround for episode number using `--parse-metadata`. I'll post it to #2976.
