### ISSUE TITLE
[youtube] Is it possible to retry the "Sign in to confirm you’re not a bot" error?

### ISSUE THREAD

**Issue by oalfonso-o** [yt-dlp/yt-dlp#10560]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Hi,

**CONTEXT**: Around the issue of the recent blacklisting from YouTube with the error message "Sign in to confirm you’re not a bot" -> I have a proxy that works when doing a retry (some IPs are blacklisted but some are not, so after one or two retries it works). My problem is that the default retry looks like doesn't retry this error so for single videos I retry it in python in case of exception.
I would like to download using the --batch-file and --download-archive to run all the downloads in one single command but if the retry doesn't work I will have to go myself over each link, each link is a channel, then for each channel get each video and retry each download one by one

**QUESTION**: Could it be possible to perform a retry by default using builtin yt-dlp retry (--retries) when it fails because of this issue or with any other option that I could be ignoring?

Thank you! (if this is not the right place to ask let me know)

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-x', '--audio-format', 'wav', '--output', 'test.wav', '--proxy', 'myproxy:1234', 'https://www.youtube.com/watch?v=GASP7PA_vi8', '--no-check-certificates', '--retries', '3', '-vU']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.07.25 from yt-dlp/yt-dlp [f0993391e]
[debug] Lazy loading extractors is disabled
[debug] Python 3.11.9 (CPython x86_64 64bit) - Linux-6.5.0-41-generic-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.02.02, mutagen-1.47.0, requests-2.32.3, sqlite3-3.37.2, urllib3-2.2.1, websockets-12.0
[debug] Proxy map: {'all': 'myproxy:1234'}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1829 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.07.25 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.07.25 from yt-dlp/yt-dlp)
[youtube] Extracting URL: https://www.youtube.com/watch?v=GASP7PA_vi8
[youtube] GASP7PA_vi8: Downloading webpage
[youtube] GASP7PA_vi8: Downloading ios player API JSON
ERROR: [youtube] GASP7PA_vi8: Sign in to confirm you’re not a bot. This helps protect our community. Learn more
  File "/home/oalfonso/pipprojects/yt-dlp/yt_dlp/extractor/common.py", line 740, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oalfonso/pipprojects/yt-dlp/yt_dlp/extractor/youtube.py", line 4274, in _real_extract
    self.raise_no_formats(reason, expected=True)
  File "/home/oalfonso/pipprojects/yt-dlp/yt_dlp/extractor/common.py", line 1263, in raise_no_formats
    raise ExtractorError(msg, expected=expected, video_id=video_id)
```

**Comment by bashonly** [comment]
For users who don't have automatic proxy rotation (i.e. ***most*** users), retrying on this error doesn't make any sense. You'll need to use an external script for this

**Comment by oalfonso-o** [comment]
Hi @bashonly, thanks for your answer. I understand from it that there's no such feature and I have to retry it myself right? If this is 100% confirmed then we can close the issue
Thank you again

**Comment by bashonly** [comment]
Correct.

Here's a simple bash example of what you could do:

```bash
for url in "${urls[@]}"; do
    while true; do
        yt-dlp "$url" && break
    done
done
```

**Comment by oalfonso-o** [comment]
Would it make sense to open a PR adding a new parameter to inform about the need of this retry and here https://github.com/yt-dlp/yt-dlp/blob/master/yt_dlp/extractor/common.py#L753  after `except GeoRestrictedError as e:` adding something like this:
```
...
                except ExtractorError as e:
                    if self._is_yt_ip_blacklist_error_and_some_retry_param_is_active(e):
                        continue
                    raise
...
```
reusing the 3 default retries of line 735 `for _ in range(2):`?

**Comment by bashonly** [comment]
No? Like I said, retrying on this error is generally pointless.

**Comment by oalfonso-o** [comment]
I'm offering myself to contribute adding a feature that my team and I need and you show how to do a loop and discard any possibility of myself or my team to contribute because you find our needs pointless, gotcha.

Thank you for your attention and for your help.

**Comment by Grub4K** [comment]
It makes more sense to do this from within a python wrapper. Its trivial to overwrite the extractor code so as to retry a certain function. Rotating IP would have to be done in Python or shell anyways. There is no benefit of blindly retrying, as retrying from the same IP will result in the same error. A decorator like this would make sense:
```py
def retry_after_ip_rotation(func):
    @functools.wraps(func)
    def wrapped(*args, **kwargs):
       for retry in (False, True):
           try:
               return func(*args, **kwargs)
           except ExtractorError:
               if not retry:
                   raise
               rotate_ip()

    return wrapped
```
Above code will retry the same function after rotating the IP. Just decorate any extractor function that requires rotated ip retries.

---
Also keep in mind that yt-dlp is a generic audio and video downloading tool. Highly specific features like this one should therefore not be added, especially if they are trivial to be implemented from outside, and make little sense to the broad public. The solution you proposed was unacceptable, and therefore could not be used.

**Comment by oalfonso-o** [comment]
Hi @Grub4K thank you for your answer. It makes sense to me to not accept my proposal, my idea was not to provide a fully functional solution but to start a conversation where I could get the information that you provided. Everything clear.

My proxy rotates the IP automatically that's why with just a retry it works in my case. I saw the parameter `--extractor-retries` and I was wondering if it could apply here.

But now I'm aware that this library aims to focus on generic features and not include every exception (like mine) which makes totally sense to me as then it has to be maintained.

Again, thank you for your explanation
