### ISSUE TITLE
[Discovery+] Error 404 when trying to download Olympic videos

### ISSUE THREAD

**Issue by LukeT222** [yt-dlp/yt-dlp#10564]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United Kingdom

### Provide a description that is worded well enough to be understood

Whenever I try to download a videos with a URL starting with `https://www.discoveryplus.com/gb/video/olympics/` I've been getting variations of this error: `ERROR: [DiscoveryPlus] olympics/dplus-sport-dplus-sport-sport: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: Not Found>)`

Depending on the URL the `olympics/dplus-sport-dplus-sport-sport:` will sometimes be replaced by either `olympics/eurosport-1-british-eurosport-1-british-sport:` or  `olympics/eurosport-2-british-eurosport-2-british-sport:`

My knowledge of programming and especially python is pretty basic but after a quick look at the extractor code my guess is that the issue is possibly with the regex [on line 937 of dplay.py](https://github.com/yt-dlp/yt-dlp/blob/6b1e430d8e4af56cd4fcb8bdc00fca9b79356464/yt_dlp/extractor/dplay.py#L937) not including the new URL format for these videos which replaces `/sport` with `/olympics`

If I knew how to, I would try to fix it by adding `(?:/olympics)?` to the end of the regex. When trying this using regex101.com, the URL for an Olympic video matched as much as it did for a normal sports video though as I'm sure you can tell, I have no real idea if that would actually fix the problem or if I've misunderstood how it works

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['https://www.discoveryplus.com/gb/video/olympics/dplus-sport-dplus-sport-sport/rugby-sevens-australia-samoa', '--cookies-from-browser', 'chrome', '-vU']
[debug] User config "C:\Users\lukea\AppData\Roaming\yt-dlp\config.txt": ['-S', 'res,fps,hdr,codec,proto,br,ext', '--merge-output-format', 'mp4', '--console-title']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version master@2024.07.24.212312 from yt-dlp/yt-dlp-master-builds [f0993391e] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22631-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 2024-01-04-git-33698ef891-full_build-www.gyan.dev (setts), ffprobe 2024-01-04-git-33698ef891-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.07.04, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {}
Extracting cookies from chrome
[debug] Extracting cookies from: "C:\Users\lukea\AppData\Local\Google\Chrome\User Data\Default\Network\Cookies"
[debug] Found local state file at "C:\Users\lukea\AppData\Local\Google\Chrome\User Data\Local State"
Extracted 1621 cookies from chrome
[debug] cookie version breakdown: {'v10': 1676, 'other': 0, 'unencrypted': 19}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1829 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-master-builds/releases/latest
Latest version: master@2024.07.24.212312 from yt-dlp/yt-dlp-master-builds
yt-dlp is up to date (master@2024.07.24.212312 from yt-dlp/yt-dlp-master-builds)
[DiscoveryPlus] Extracting URL: https://www.discoveryplus.com/gb/video/olympics/dplus-sport-dplus-sport-sport/rugby-sevens-australia-samoa
[debug] Using fake IP 25.148.38.162 (GB) as X-Forwarded-For
[DiscoveryPlus] olympics/dplus-sport-dplus-sport-sport: Downloading JSON metadata
ERROR: [DiscoveryPlus] olympics/dplus-sport-dplus-sport-sport: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: Not Found>)
  File "yt_dlp\extractor\common.py", line 740, in extract
  File "yt_dlp\extractor\dplay.py", line 993, in _real_extract
  File "yt_dlp\extractor\dplay.py", line 79, in _get_disco_api_info
  File "yt_dlp\extractor\common.py", line 1139, in download_content
  File "yt_dlp\extractor\common.py", line 1099, in download_handle
  File "yt_dlp\extractor\common.py", line 960, in _download_webpage_handle
  File "yt_dlp\extractor\common.py", line 909, in _request_webpage

  File "yt_dlp\extractor\common.py", line 896, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 4165, in urlopen
  File "yt_dlp\networking\common.py", line 117, in send
  File "yt_dlp\networking\_helper.py", line 208, in wrapper
  File "yt_dlp\networking\common.py", line 340, in send
  File "yt_dlp\networking\_requests.py", line 365, in _send
yt_dlp.networking.exceptions.HTTPError: HTTP Error 404: Not Found
```

**Comment by bashonly** [comment]
I'm geo-blocked, but this might fix it

```diff
diff --git a/yt_dlp/extractor/dplay.py b/yt_dlp/extractor/dplay.py
index e9f9357ad..d64cff516 100644
--- a/yt_dlp/extractor/dplay.py
+++ b/yt_dlp/extractor/dplay.py
@@ -934,7 +934,7 @@ class TLCIE(DiscoveryPlusBaseIE):
 
 
 class DiscoveryPlusIE(DiscoveryPlusBaseIE):
-    _VALID_URL = r'https?://(?:www\.)?discoveryplus\.com/(?!it/)(?:(?P<country>[a-z]{2})/)?video(?:/sport)?' + DPlayBaseIE._PATH_REGEX
+    _VALID_URL = r'https?://(?:www\.)?discoveryplus\.com/(?!it/)(?:(?P<country>[a-z]{2})/)?video(?:/sport|/olympics)?' + DPlayBaseIE._PATH_REGEX
     _TESTS = [{
         'url': 'https://www.discoveryplus.com/video/property-brothers-forever-home/food-and-family',
         'info_dict': {
```

**Comment by LukeT222** [comment]
I'm sorry but I have no experience with anything like this so I'm kinda lost. How do I try this?

**Comment by bashonly** [comment]
@LukeT222 you can update your yt-dlp to a pre-release build I've made by running this:

```
yt-dlp --update-to bashonly/yt-dlp@dplus
```

After you're done testing with it, if you want to get back on the official release channel, run this:

```
yt-dlp --update-to stable@latest
```

**Comment by LukeT222** [comment]
That's perfect, thank you! I've just tried the pre-release build and it seems to have fixed it. I've just tried it with a handful of videos and they've all downloaded perfectly
