### ISSUE TITLE
Bypass suspicious extension

### ISSUE THREAD

**Issue by Explosion-Scratch** [yt-dlp/yt-dlp#10563]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Downloading files from many sites is a useful feature of this tool, and while it is oriented towards downloading videos, being able to bypass the following message via a flag like `--allow-all-extensions` would come in handy. Note that I'm not requesting full support for downloading non-video files, just a way to bypass this one check. yt-dlp would not need to address issues in downloading non-video files should any arise.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
ERROR: The extracted extension ('pdf') is unusual and will be skipped for safety reasons. If you believe this is an error, please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

This flag would have a warning and not be enabled by default obviously.

Perhaps a flag somewhere to bypass this check basically:
https://github.com/yt-dlp/yt-dlp/blob/89a161e8c62569a662deda1c948664152efcb6b4/yt_dlp/utils/_utils.py#L5049-L5148

**Comment by bashonly** [comment]
https://github.com/yt-dlp/yt-dlp?tab=readme-ov-file#differences-in-default-behavior

> The following compat options restore vulnerable behavior from before security patches:
>
> * `--compat-options allow-unsafe-ext`: Allow files with any extension (including unsafe ones) to be downloaded ([GHSA-79w7-vh3h-8g4j](<https://github.com/yt-dlp/yt-dlp/security/advisories/GHSA-79w7-vh3h-8g4j>))
>
>     > :warning: Only use if a valid file download is rejected because its extension is detected as uncommon

**Comment by Explosion-Scratch** [comment]
Awesome thanks!
