### ISSUE TITLE
How to properly retrieve subtitles programmatically using python?

### ISSUE THREAD

**Issue by animaldomestico** [yt-dlp/yt-dlp#10561]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I managed to get comments from a video using python:
```python
options = {"getcomments": True, "quiet": True}
with YoutubeDL(options) as yt:
                comments = yt.extract_info(url, download=False)["comments"]
                # ...
```
But I tried to see what is available when I use options like `writeautomaticsub = True` and I couldn't see any key that had any sort of JSON with the desired subtitle (being automatic or not).

At moment I'm using [youtube-transcript-api](https://github.com/jdepoix/youtube-transcript-api), and it is very easy to get subttiles there, and even translate them if needed, look:
```python
from youtube_transcript_api import YouTubeTranscriptApi as ytt
first = next(iter(ytt.list_transcripts(video_id)))
subtitles = first.translate("pt").fetch() # translate and returns a list of dict {text, start, duration}
```

Again, could someone please provide me a code snippet as an example to do the same with YoutubeDL? Am I missing something? I would like to use just one library to extract information from Youtube if possible.

In advance, thanks!

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [x] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output
```
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.07.09 from yt-dlp/yt-dlp [7ead7332a] (pip) API
[debug] params: {'writeautomaticsub': True, 'subtitleslangs': ['pt'], 'verbose': True, 'compat_opts': set(), 'http_headers': {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.85 Safari/537.36', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'Accept-Language': 'en-us,en;q=0.5', 'Sec-Fetch-Mode': 'navigate'}}
[debug] Python 3.12.3 (CPython x86_64 64bit) - Linux-6.8.0-38-generic-x86_64-with-glibc2.39 (OpenSSL 3.0.13 30 Jan 2024, glibc 2.39)
[debug] exe versions: ffmpeg 6.1.1 (setts), ffprobe 6.1.1
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.07.04, mutagen-1.47.0, requests-2.32.3, sqlite3-3.45.1, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1834 extractors
[youtube] Extracting URL: https://www.youtube.com/watch?v=ANxZPCJlk6k
[youtube] ANxZPCJlk6k: Downloading webpage
[youtube] ANxZPCJlk6k: Downloading ios player API JSON
[youtube] ANxZPCJlk6k: Downloading player 1f8742dc
WARNING: [youtube] ANxZPCJlk6k: nsig extraction failed: Some formats may be missing
         n = nAGKmSgyGrvaHMG7U ; player = https://www.youtube.com/s/player/1f8742dc/player_ias.vflset/en_US/base.js
[debug] [youtube] Unable to extract nsig function code (caused by RegexNotFoundError('Unable to extract \x1b[0;94mInitial JS player n function name\x1b[0m; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [youtube] ANxZPCJlk6k: nsig extraction failed: Some formats may be missing
         n = MuWQX6YWC6iWxTKHo ; player = https://www.youtube.com/s/player/1f8742dc/player_ias.vflset/en_US/base.js
[youtube] ANxZPCJlk6k: Downloading m3u8 information
[info] ANxZPCJlk6k: Downloading subtitles: pt
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
```

**Comment by bashonly** [comment]
`requested_subtitles` ?

It's always easier to answer these questions if you provide example URLs / output

**Comment by animaldomestico** [comment]
[writewriteautomaticsub.json](https://github.com/user-attachments/files/16381283/writewriteautomaticsub.json)
```python
from yt_dlp import YoutubeDL
import json

# test code
options = {"writewriteautomaticsub": True, "subtitleslangs": ["pt"], "quiet": True}
url_test = "https://www.youtube.com/watch?v=ANxZPCJlk6k&pp=ygUhb3BlcmHDp8OjbyBwcmF0byBlZHNvbiBib2F2ZW50dXJh"
with YoutubeDL(options) as yt:
    info = yt.extract_info(url_test, download=False)
    with open("writewriteautomaticsub.json", "w") as f:
        f.write(json.dumps(info, indent=4, ensure_ascii=False))
```

I could just see some keys named `url` with things like `.../api/timedtext?...` that points to the subs, but nothing likes a structured JSON like I've mentioned with `YouTubeTranscriptApi`.

I've to download and parse them manually?

**Comment by bashonly** [comment]
> I've to download and parse them manually?

Yes, the url is for a webvtt subtitles file.

**Comment by animaldomestico** [comment]
> > I've to download and parse them manually?
> 
> Yes, the url is for a webvtt subtitles file.

Ok, thanks.
