### ISSUE TITLE
[FranceTV] Video is geoblocked when i download from the website

### ISSUE THREAD

**Issue by DFDSDFDDS-POOP** [yt-dlp/yt-dlp#10570]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Cannot Download france.tv due to geoblocking restrictions

**Are there any workarounds?**

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp -vU https://www.france.tv/documentaires/documentaires-art-et-culture/6324842-ceremonie-d-ouverture-premiers-secrets-partie-2.html
[FranceTVSite] Extracting URL: https://www.france.tv/documentaires/documentaires-art-et-culture/6324842-ceremonie-d-ouverture-pr...ecrets-partie-2.html
[FranceTVSite] 6324842-ceremonie-d-ouverture-premiers-secrets-partie-2: Downloading webpage
[FranceTV] Extracting URL: francetv:c41696f3-4e3f-449e-bb7d-60b80067b47b#__youtubedl_smuggle=%7B%22hostname%22%3A+%22www.france.tv%22%7D
[FranceTV] c41696f3-4e3f-449e-bb7d-60b80067b47b: Downloading desktop chrome video JSON
[FranceTV] c41696f3-4e3f-449e-bb7d-60b80067b47b: Downloading mobile safari video JSON
[FranceTV] c41696f3-4e3f-449e-bb7d-60b80067b47b: Downloading MPD manifest
WARNING: [FranceTV] Failed to download MPD manifest: HTTP Error 403: Forbidden
[FranceTV] c41696f3-4e3f-449e-bb7d-60b80067b47b: Downloading m3u8 information
WARNING: [FranceTV] Failed to download m3u8 information: HTTP Error 403: Forbidden
[FranceTV] c41696f3-4e3f-449e-bb7d-60b80067b47b: Checking for geo-restriction
ERROR: [FranceTV] c41696f3-4e3f-449e-bb7d-60b80067b47b: This video is not available from your location due to geo restriction
This video is available in France.
You might want to use a VPN or a proxy server (with --proxy) to workaround.
```

**Comment by DFDSDFDDS-POOP** [comment]
> If you're not in region there's nothing yt-dlp can do about it. Try a VPN

**how? can you send me in a video on how you actually did it?**

**Comment by bashonly** [comment]
This is not a support channel for how to use a VPN, sorry
