### ISSUE TITLE
Youtube: [WinError 10051] A socket operation was attempted to an unreachable network

### ISSUE THREAD

**Issue by Nexen23** [yt-dlp/yt-dlp#10571]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Russia

### Provide a description that is worded well enough to be understood

Downloading from Youtube suddenly stopped working on 25.07.24:
```
> yt-dlp.exe https://www.youtube.com/watch?v=_xXIC96jXBQ
[youtube] Extracting URL: https://www.youtube.com/watch?v=_xXIC96jXBQ
[youtube] _xXIC96jXBQ: Downloading webpage
[youtube] _xXIC96jXBQ: Downloading ios player API JSON
[youtube] _xXIC96jXBQ: Downloading m3u8 information
[info] _xXIC96jXBQ: Downloading 1 format(s): 308+251
[download] Got error: <urllib3.connection.HTTPSConnection object at 0x000001C9DD3C8850>: Failed to establish a new connection: [WinError 10051] A socket operation was attempted to an unreachable network. Retrying (1/10)...
```

Saw similar issues, but solutions from there didn't work:
- updating yt-dlp / switching to master didn't help
- `--cookies-from-browser chrome` didn't help
- `--rm-cache-dir` didn't help

More context:
- downloading Vimeo videos work fine
- all videos from youtube fail to download
- (_may be unrelated but_) day before I tried using proxies for yt-dlp and some badly setuped proxies gave off similar errors (if I remember correctly). But after I stopped these experiments, I used yt-dlp for downloading youtube videos just fine, but it suddenly got broken on the next day

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.youtube.com/watch?v=_xXIC96jXBQ']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version master@2024.07.25.223018 from yt-dlp/yt-dlp-master-builds [28d485714] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.18363-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 3.2.2, ffprobe 3.2.2
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.07.04, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1828 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-master-builds/releases/latest
Latest version: master@2024.07.25.223018 from yt-dlp/yt-dlp-master-builds
yt-dlp is up to date (master@2024.07.25.223018 from yt-dlp/yt-dlp-master-builds)
[youtube] Extracting URL: https://www.youtube.com/watch?v=_xXIC96jXBQ
[youtube] _xXIC96jXBQ: Downloading webpage
[youtube] _xXIC96jXBQ: Downloading ios player API JSON
[debug] Loading youtube-nsig.1f8742dc from cache
[debug] [youtube] Decrypted nsig HVYzlsGTohud3um80 => PDsO9lFwN9nbHg
[debug] Loading youtube-nsig.1f8742dc from cache
[debug] [youtube] Decrypted nsig 7L8X3Lv4PXZVjVAku => GikmIakrSzypug
[youtube] _xXIC96jXBQ: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] _xXIC96jXBQ: Downloading 1 format(s): 308+251
[debug] Invoking http downloader on "https://rr2---sn-gxuo03g-ig3l.googlevideo.com/videoplayback?expire=1722026560&ei=4LWjZu2WLsuLp-oPo5aJyAY&ip=OMITTED_IP&id=o-AKNI9ISaC5aiPXK6hir5bljwrZfja5nWXBCKZjEgZ1eM&itag=308&aitags=133%2C134%2C135%2C136%2C160%2C242%2C243%2C244%2C247%2C278%2C298%2C299%2C302%2C303%2C308%2C394%2C395%2C396%2C397%2C398%2C399%2C400&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=NC&mm=31%2C29&mn=sn-gxuo03g-ig3l%2Csn-5hne6nzk&ms=au%2Crdu&mv=u&mvi=2&pl=26&bui=AXc671JkfvVmJ5xy3K4UWinBP9YRJ3P8WLk9fOhLEX8agjqX9Qn70U39Re2RKCnJ0d6sN-hCSPv_qVnv&spc=NO7bAQyAjWsfgFKNSeQgl1Il1VMRdjlpVTLLrAvspMiWqVG4wXYuhg5Rs9ZA&vprv=1&svpuc=1&mime=video%2Fwebm&ns=ZjslUOnJOo8QGXI5dzh80coQ&rqh=1&gir=yes&clen=40789252&dur=48.866&lmt=1701305384852465&mt=1722003918&fvip=5&keepalive=yes&c=WEB&sefc=1&txp=5532434&n=GikmIakrSzypug&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cxpc%2Cbui%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cns%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRAIgeAg9LVfphhNaLSxmeuUSMc6OW50-1Q-vtLLay2VAq6sCIHX8U6tPRSEK7Dk_OtrTY0yVSX0YvxXCFaw_-CQmgjWt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl&lsig=AGtxev0wRAIgXFLb8Q_YmzYc_9c68V0t9iBGQzZOBSk9THNM3rZFHk8CICfolqTEbHZzKVDAECyBIq52T34eSEGB0KADq1DL2Zv_"
[download] Got error: <urllib3.connection.HTTPSConnection object at 0x000002654AE3D7C0>: Failed to establish a new connection: [WinError 10051] A socket operation was attempted to an unreachable network. Retrying (1/10)...
[download] Got error: <urllib3.connection.HTTPSConnection object at 0x000002654AEA2F40>: Failed to establish a new connection: [WinError 10051] A socket operation was attempted to an unreachable network. Retrying (2/10)...
[download] Got error: <urllib3.connection.HTTPSConnection object at 0x000002654B0FEEE0>: Failed to establish a new connection: [WinError 10051] A socket operation was attempted to an unreachable network. Retrying (3/10)...
[download] Got error: <urllib3.connection.HTTPSConnection object at 0x000002654AE87E50>: Failed to establish a new connection: [WinError 10051] A socket operation was attempted to an unreachable network. Retrying (4/10)...
[download] Got error: <urllib3.connection.HTTPSConnection object at 0x000002654B0FE730>: Failed to establish a new connection: [WinError 10051] A socket operation was attempted to an unreachable network. Retrying (5/10)...
[download] Got error: (<urllib3.connection.HTTPSConnection object at 0x000002654AEA2C70>, 'Connection to rr2---sn-gxuo03g-ig3l.googlevideo.com timed out. (connect timeout=20.0)'). Retrying (6/10)...
[download] Got error: <urllib3.connection.HTTPSConnection object at 0x000002654AE3D070>: Failed to establish a new connection: [WinError 10051] A socket operation was attempted to an unreachable network. Retrying (7/10)...
[download] Got error: <urllib3.connection.HTTPSConnection object at 0x000002654AEB1460>: Failed to establish a new connection: [WinError 10051] A socket operation was attempted to an unreachable network. Retrying (8/10)...
[download] Got error: <urllib3.connection.HTTPSConnection object at 0x000002654AE2E610>: Failed to establish a new connection: [WinError 10051] A socket operation was attempted to an unreachable network. Retrying (9/10)...
```

**Comment by DTrombett** [comment]
_in the **Complete Verbose Output** section you should include the output of `yt-dlp -vU _xXIC96jXBQ`_

**Comment by Nexen23** [comment]
> _in the **Complete Verbose Output** section you should include the output of `yt-dlp -vU _xXIC96jXBQ`_

Gotcha, thanks. Fixed. Is it okay that I omitted the IP?

**Comment by bashonly** [comment]
Looks like either a firewall issue or a lingering issue from your improper proxy configuration.

Are you using a firewall? Anything like pihole or adguard?

Can you elaborate on what you were doing with proxies?

**Comment by Nexen23** [comment]
> Looks like either a firewall issue or a lingering issue from your improper proxy configuration.
> 
> Are you using a firewall? Anything like pihole or adguard?
> 
> Can you elaborate on what you were doing with proxies?

Only default windows firewall which I haven't touch in ages.

I tried proxies to see if I got shadowblocked by youtube because recently yt-dlp downloads videos with ~50kbs speed at best and quite often fails and retries fragments.
For that I used publicly available proxies, so I didn't do manually any setup on PC.

`-4` gave:
```
[download] Got error: <urllib3.connection.HTTPSConnection object at 0x0000023D3F882970>: Failed to resolve 'rr2---sn-gxuo03g-ig3l.googlevideo.com' ([Errno 11001] getaddrinfo failed). Retrying (3/10)...
```

`-6` gave:
```
WARNING: [youtube] <urllib3.connection.HTTPSConnection object at 0x000001EAF9A8B6A0>: Failed to establish a new connection: [WinError 10051] A socket operation was attempted to an unreachable network. Retrying (1/3)...
```
(but retried pretty fast and failed 6 retries within a second)


Am I correct to assume that problem occurs only just for me? If so, I will try out different PC with same IP and different login with clean system to make sure it wasn't my proxy shenanigans somehow affecting yt-dlp

**Comment by bashonly** [comment]
> Am I correct to assume that problem occurs only just for me?

Yes, it looks like it's a problem with your system and/or network

**Comment by Nexen23** [comment]
> > Am I correct to assume that problem occurs only just for me?
> 
> Yes, it looks like it's a problem with your system and/or network

Thanks, I'll check out mentioned options on weekend and return with the results

**Comment by Nexen23** [comment]
Indeed it is a problem on my side. yt-dlp on another PC with the same IP or on clean OS works fine. I yet to find out how this is possible, but yt-dlp is not the issue so I'm closing the issue

**Comment by mbaz** [comment]
@Nexen23 Did you figure out a solution? I'm having the same issue.

**Comment by Nexen23** [comment]
> @Nexen23 Did you figure out a solution? I'm having the same issue.

If I remember correctly, yt-dlp didn't work because proxy was host-wise, so disabling it or enabling OS-wise proxying did the trick

**Comment by mbaz** [comment]
@Nexen23 Thanks for your reply! I don't use a proxy, though, so it must be some other issue...

**Comment by Nexen23** [comment]
> @Nexen23 Thanks for your reply! I don't use a proxy, though, so it must be some other issue...

Yeah, I didn't use either. Proxy mentioned in this thread was just a url set as a yt-dlp cli argument. But That "proxy" was caused by some other program and I for the love of me can't remember what it was. Sorry for not being of much help here, but hope you will find out the cause

**Comment by mbaz** [comment]
For others landing on this page: in my case, the problem turned out to be related to the name resolver (`systemd-resolved` in my case). I'm still not sure what caused the issue, but restarting the service solved it.
