### ISSUE TITLE
How to bypass 'Requested format is not available' with multistreams option

### ISSUE THREAD

**Issue by IceArms** [yt-dlp/yt-dlp#10586]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Is it possible to bypass '**Requested format is not available**' error when using  `--audio-multistreams` and some unavailable formats stop all the process?

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-v', '-f', '(bv/b*)[height<=1080][dynamic_range!*=HDR] + (ba[language=?ru]/ba) + ba[format_id$=-drc] + ba[language=en]', '-o', 'E:\\vods\\yt\\1080\\%(upload_date)s_%(uploader)s_%(title)s_%(id)s.%(ext)s', '-a', '1080p.txt', '--check-formats', '--prefer-insecure', '--legacy-server-connect', '--no-check-certificate', '--geo-bypass', '--no-abort-on-error', '--no-playlist', '--write-auto-subs', '--sub-langs', 'ru,en,-live_chat', '--convert-subs', 'srt', '--live-from-start', '--audio-multistreams', '--no-mtime', '--remux-video', 'mkv', '--embed-thumbnail', '--embed-metadata', '--embed-subs']
[debug] Batch file urls: ['https://www.youtube.com/watch?v=GxziYpZ6eQo']
[debug] Encodings: locale cp1251, fs utf-8, pref cp1251, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.07.25 from yt-dlp/yt-dlp [f0993391e] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.17134-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-116329-g90672974bd-20240718 (setts), ffprobe N-116329-g90672974bd-20240718
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.07.04, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {'http': 'http://127.0.0.1:12899', 'https': 'http://127.0.0.1:12899', 'socks': 'socks://127.0.0.1:12898'}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1829 extractors
[youtube] Extracting URL: https://www.youtube.com/watch?v=GxziYpZ6eQo
[youtube] GxziYpZ6eQo: Downloading webpage
[youtube] GxziYpZ6eQo: Downloading ios player API JSON
[debug] Loading youtube-nsig.1f8742dc from cache
[debug] [youtube] Decrypted nsig FTIq-tRJvYLsHo_y6 => WxH-R8K-WXDEmg
[debug] Loading youtube-nsig.1f8742dc from cache
[debug] [youtube] Decrypted nsig rNnm6NPR3RwTkHqFY => iJ91P6_2wgOrwQ
[youtube] GxziYpZ6eQo: Downloading m3u8 information
[info] GxziYpZ6eQo: Downloading subtitles: ru, en
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[info] Testing format 303
[debug] File locking is not supported. Proceeding without locking
[download] Destination: C:\yt-dlp\tmpdx3cxv8x.tmp
[download] 100% of   10.00KiB in 00:00:00 at 56.27KiB/s
[info] Testing format 251
[download] Destination: C:\yt-dlp\tmpz83wxqoy.tmp
[download] 100% of   10.00KiB in 00:00:00 at 147.93KiB/s
[info] Testing format 251-drc
[download] Destination: C:\yt-dlp\tmpj6kopi9j.tmp
[download] 100% of   10.00KiB in 00:00:00 at 152.42KiB/s
ERROR: [youtube] GxziYpZ6eQo: Requested format is not available. Use --list-formats for a list of available formats
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1626, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1782, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1841, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2977, in process_video_result
yt_dlp.utils.ExtractorError: [youtube] GxziYpZ6eQo: Requested format is not available. Use --list-formats for a list of available formats
```

**Comment by bashonly** [comment]
You'll need to use fallbacks. I think you might want something like this:

```
-f "bv*[height<=1080][dynamic_range!*=HDR] + (ba[language=ru]+[format_id$=-drc]+ba[language=en]/ba[language=?ru]+ba[format_id$=-drc]/ba[language=?ru]) / b" --audio-multistreams
```

Merge best video format (that may also contain audio -- `bv*`) plus:
- best Russian language audio, best DRC audio, and best English language audio
- or fall back to best Russian language audio (if lang is specified) and best DRC audio
- or fall back to best Russian language audio (if lang is specified, or else just best audio)

...or completely fall back to best combined video+audio format (`b`)

**Comment by IceArms** [comment]
Thank you, I'll try this! But I think that's more logical will be implement some simple option to bypass this thing... Should I make a separate request for that?

**Comment by bashonly** [comment]
No. This is the expected and desired behavior for format selection
