### ISSUE TITLE
[tver] tver extractor doesn't work on new paris olympics urls

### ISSUE THREAD

**Issue by daideya** [yt-dlp/yt-dlp#10583]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Provide a description that is worded well enough to be understood

The format for the paris olympic related videos on tver look something like this: https://tver.jp/olympic/paris2024/video/6359247556112

Which is not covered by the link extractor regex:

`_VALID_URL = r'https?://(?:www\.)?tver\.jp/(?:(?P<type>lp|corner|series|episodes?|feature|tokyo2020/video)/)+(?P<id>[a-zA-Z0-9]+)'`

so instead of recognizing it as a tver link, it falls back to the generic extractor, which doesn't work. 

Maybe olympic/paris2024/video needs to be added to the regex?

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://tver.jp/olympic/paris2024/video/6359247556112']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version master@2024.07.25.223018 from yt-dlp/yt-dlp-master-builds [28d485714] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22631-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-115026-gf492095bd3-20240429 (setts), ffprobe N-115026-gf492095bd3-20240429
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.07.04, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1828 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-master-builds/releases/latest
Latest version: master@2024.07.25.223018 from yt-dlp/yt-dlp-master-builds
yt-dlp is up to date (master@2024.07.25.223018 from yt-dlp/yt-dlp-master-builds)
[generic] Extracting URL: https://tver.jp/olympic/paris2024/video/6359247556112
[generic] 6359247556112: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] 6359247556112: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://tver.jp/olympic/paris2024/video/6359247556112
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1626, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1761, in __extract_info
  File "yt_dlp\extractor\common.py", line 740, in extract
  File "yt_dlp\extractor\generic.py", line 2526, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://tver.jp/olympic/paris2024/video/6359247556112
```

**Comment by bashonly** [comment]
Unfortunately, extending the `_VALID_URL` regex pattern alone is not enough to solve this.

**Comment by daideya** [comment]
Damn, that's a shame

**Comment by trollcop** [comment]
Sorry to bring up a closed (?) issue, I saw the /video/ get merged (and works) but I am trying to record an archived live (for example here: https://tver.jp/olympic/paris2024/live/FBLMTEAM11------------SFNL000100--/ (notice how there's /live/ in url instead of /video/ and its falling back to generic handler and isn't working.

**Comment by bashonly** [comment]
@trollcop open a new issue and include complete verbose output please
