### ISSUE TITLE
Selecting languages for audio-multistreams

### ISSUE THREAD

**Issue by IceArms** [yt-dlp/yt-dlp#10581]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [x] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Hello! I'm a little confused about sorting arguments. Is it possible to choose [russian best audio] + [english best audio] with `--audio-multistreams` using `-S` option?
And please give an example for the same queston but for `-f` option.
Thanks in advance!

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
> Is it possible to choose [russian best audio] + [english best audio] with `--audio-multistreams` using `-S` option?

No, `-S` only sorts, it does not select.

> And please give an example for the same queston but for `-f` option.

show the output of `yt-dlp -vF "URL"` where `URL` is the link that you're trying to download the audio streams from

**Comment by IceArms** [comment]
I find out, the best way is to use both: `-S "res:720,fps,codec" -f "bv+ba[language=?ru]+ba[language=?en]/b"`
_(Example for Windows)_
