### ISSUE TITLE
Extension 'vid' is being excluded "for safety reasons"

### ISSUE THREAD

**Issue by 48622** [yt-dlp/yt-dlp#10585]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Releases after 5/27 are blocking downloads of .vid

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://c7.trafficdeposit.com/vidi/0134u9jzv8m8n/yWlTz6UE_AIKiMnr09Bdrw/1722130471/5f3950a938042/66a4bcd44f785.vid']
[debug] User config "/home/zara/.config/yt-dlp/config": ['-o', '~/Videos/%(epoch)s%(title)s.mp4']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.07.25 from yt-dlp/yt-dlp [f0993391e]
[debug] Python 3.12.4 (CPython x86_64 64bit) - Linux-6.9.8-arch1-1-x86_64-with-glibc2.40 (OpenSSL 3.3.1 4 Jun 2024, glibc 2.40)
[debug] exe versions: ffmpeg 7.0.1 (setts), ffprobe 7.0.1
[debug] Optional libraries: Cryptodome-3.20.0, brotlicffi-1.1.0.0, certifi-2024.07.04, requests-2.32.3, secretstorage-3.3.3, sqlite3-3.46.0, urllib3-1.26.19
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Loaded 1829 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.07.25 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.07.25 from yt-dlp/yt-dlp)
[generic] Extracting URL: https://c7.trafficdeposit.com/vidi/0134u9jzv8m8n/yWlTz6UE_AIKiMnr09Bdrw/1722130471/5f3950a938042/66a4bcd44f785.vid
[generic] 66a4bcd44f785: Downloading webpage
[debug] Identified a direct video link
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 66a4bcd44f785: Downloading 1 format(s): fmp4
ERROR: The extracted extension ('vid') is unusual and will be skipped for safety reasons. If you believe this is an error, please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 179, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 3479, in process_info
    dl_filename = existing_video_file(full_filename, temp_filename)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 3371, in existing_video_file
    file = self.existing_file(itertools.chain(*zip(map(converted, filepaths), filepaths)),
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 3370, in <lambda>
    converted = lambda file: replace_extension(file, self.params.get('final_ext') or ext, ext)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/yt_dlp/utils/_utils.py", line 2097, in _change_extension
    return f'{filename}.{_UnsafeExtensionError.sanitize_extension(ext)}'
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/yt_dlp/utils/_utils.py", line 5167, in sanitize_extension
    raise cls(extension)
yt_dlp.utils._UnsafeExtensionError: unsafe file extension: 'vid'
```

**Comment by bashonly** [comment]
https://github.com/yt-dlp/yt-dlp?tab=readme-ov-file#differences-in-default-behavior

> The following compat options restore vulnerable behavior from before security patches:
>
> * `--compat-options allow-unsafe-ext`: Allow files with any extension (including unsafe ones) to be downloaded ([GHSA-79w7-vh3h-8g4j](<https://github.com/yt-dlp/yt-dlp/security/advisories/GHSA-79w7-vh3h-8g4j>))
>
>     > :warning: Only use if a valid file download is rejected because its extension is detected as uncommon
