### ISSUE TITLE
[Broken] Arte.tv

### ISSUE THREAD

**Issue by rtega** [yt-dlp/yt-dlp#1059]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running yt-dlp version **2021.09.02**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] Command-line config: ['-v', 'https://www.arte.tv/fr/videos/086095-001-K/par-dela-les-alpes/']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] yt-dlp version 2021.09.02 
[debug] Python version 3.8.10 (CPython 64bit) - Linux-5.4.0-84-generic-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4, phantomjs 2.1.1, rtmpdump 2.4
[debug] Optional libraries: keyring, mutagen, pycryptodome, sqlite, websockets
[debug] Proxy map: {}
[debug] [generic] Extracting URL: https://www.arte.tv/fr/videos/086095-001-K/par-dela-les-alpes/
[generic] par-dela-les-alpes: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] par-dela-les-alpes: Downloading webpage
[generic] par-dela-les-alpes: Extracting information
ERROR: [generic] Unsupported URL: https://www.arte.tv/fr/videos/086095-001-K/par-dela-les-alpes/
Traceback (most recent call last):
  File "/home/rtega/.local/lib/python3.8/site-packages/yt_dlp/extractor/common.py", line 584, in extract
    ie_result = self._real_extract(url)
  File "/home/rtega/.local/lib/python3.8/site-packages/yt_dlp/extractor/generic.py", line 3713, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.arte.tv/fr/videos/086095-001-K/par-dela-les-alpes/
Traceback (most recent call last):
  File "/home/rtega/.local/lib/python3.8/site-packages/yt_dlp/extractor/common.py", line 584, in extract
    ie_result = self._real_extract(url)
  File "/home/rtega/.local/lib/python3.8/site-packages/yt_dlp/extractor/generic.py", line 3713, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.arte.tv/fr/videos/086095-001-K/par-dela-les-alpes/

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rtega/.local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 1214, in wrapper
    return func(self, *args, **kwargs)
  File "/home/rtega/.local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 1239, in __extract_info
    ie_result = ie.extract(url)
  File "/home/rtega/.local/lib/python3.8/site-packages/yt_dlp/extractor/common.py", line 600, in extract
    raise ExtractorError(
yt_dlp.utils.ExtractorError: [generic] Unsupported URL: https://www.arte.tv/fr/videos/086095-001-K/par-dela-les-alpes/

zsh: exit 1     yt-dlp -v 'https://www.arte.tv/fr/videos/086095-001-K/par-dela-les-alpes/'

```

## Description

Arte seems to use a new API for certain videos. For example the URL provided in the log does not download. More detailed info towards a solution might be found here: https://github.com/ytdl-org/youtube-dl/issues/29870

**Comment by pukkandan** [comment]
https://github.com/ytdl-org/youtube-dl/pull/29653 is incomplete, but looks like a step in the right direction. Perhaps @casper would be willing to continue working on the PR here

**Comment by rtega** [comment]
Thanks for the reply but I guess you meant @casaper. Could you chime in?

**Comment by rtega** [comment]
Thanks for chiming in. It indeed doesn't work. If you could enlighten us on how to start, I'd be willing to see if I can improve on your code.

**Comment by pukkandan** [comment]
Please confirm whether this is fixed. The URL in OP no longer works

**Comment by rtega** [comment]
I have no idea but I have been able to see everything with yt-dlp in the last months. I don't recall anything not working. Either the current code already works or they stopped using api v2.

**Comment by rtega** [comment]
Ok, I'll chime back in when I notice something.

**Comment by andreygursky** [comment]
If you click on the URL for one of the episodes, e.g.
https://www.arte.tv/de/videos/104911-001-A/polar-park-eiskalte-morde-1-6/,
you can see under the video window on the right side the button "Mehr" (eng. "more"). There the URL for the list of episodes differs a bit:
https://www.arte.tv/de/videos/RC-024250/polar-park-eiskalte-morde/RC-024251/polar-park-eiskalte-morde/.
If there are more seasons, the ID would shift +1 further.

**Comment by andreygursky** [comment]
Yes, this works also, e.g.:
```
$ wget https://www.arte.tv/api/rproxy/emac/v4/de/web/collections/RC-024250 -O RC-024250.json
$ jq -r '.value.zones[] | .content.data[] as $d | if $d.type != "collection" then "https://www.arte.tv" + $d.url else "" end' RC-024250.json
https://www.arte.tv/de/videos/104911-001-A/polar-park-eiskalte-morde-1-6/
https://www.arte.tv/de/videos/104911-002-A/polar-park-eiskalte-morde-2-6/
https://www.arte.tv/de/videos/104911-003-A/polar-park-eiskalte-morde-3-6/
https://www.arte.tv/de/videos/104911-004-A/polar-park-eiskalte-morde-4-6/
https://www.arte.tv/de/videos/104911-005-A/polar-park-eiskalte-morde-5-6/
https://www.arte.tv/de/videos/104911-006-A/polar-park-eiskalte-morde-6-6/
https://www.arte.tv/de/videos/114413-001-A/interview-mit-dem-team-von-polar-park-eiskalte-morde/
```

**Comment by ethicnology** [comment]
> Thanks for this hint. I've just found another very interesting API (especially the 'zones' section):
> 
> https://www.arte.tv/api/rproxy/emac/v4/de/web/collections/RC-024250

Using zones, the pattern seems to be the following:
- ignore the first two indexes
- ignore the last four indexes

Between these useless indexes you have seasons, for each, episodes are listed in `zones[i].content.data`

For all the useless indexes, they have in common an empty `.content.data` a risky heuristic/assumption would be to exclude all index that has empty `.content.data`

**Comment by ethicnology** [comment]
Gang, I'm spending a lot of time observing requests, I know `yt-dlp` decided to rely on `api.arte.tv` instead of `www.arte.tv` which seems to be a good choice. 

Actually when you load a content arte.tv perform requests on these two endpoints which contains duplicates data, `www.arte.tv` has some extra information such as authors, directors, years, countries… which are not available on `api.arte.tv`

I'm taking the time to write this message because, right now, I found something a bit scary: `api.arte.tv` is less reliable than `www.arte.tv`

My example rely on a mistake from someone working at ARTE but it shows us **the trustful source of information is   `www.arte.tv` and not `api.arte.tv`** on the documentary about Chinese Mafia: [RC-024605](https://www.arte.tv/fr/videos/RC-024605).

If you fetch `https://api.arte.tv/api/sso/v3/nextEpisode/fr/RC-024605` the payload of the response contains information about the wrong series, `RC-024552` which is a documentary about Northern Ireland while `www.arte.tv` give the information related to the right documentary

**Comment by andreygursky** [comment]
> If you fetch https://api.arte.tv/api/sso/v3/nextEpisode/fr/RC-024605 the payload of the response contains information about the wrong series

When I visit [RC-024605](https://www.arte.tv/fr/videos/RC-024605), arte.tv makes request to ```https://www.arte.tv/api/rproxy/emac/v4/fr/web/collections/RC-024605```, which seems to contain properly metadata. ```api/sso/v3/nextEpisode``` is not used.

**Comment by ethicnology** [comment]
My point is to show that the `api.***` backend seems to be less reliable `www.***` backend, you gave me a `www.` endpoint

The actual arte extractor rely on `api.arte.tv`: https://github.com/yt-dlp/yt-dlp/blob/85b33f5c163f60dbd089a6b9bc2ba1366d3ddf93/yt_dlp/extractor/arte.py#L18C6-L18C6

**Comment by andreygursky** [comment]
> https://api.arte.tv/api/player/v2

It's still ```api/player/v2``` not ```api/sso/v3/nextEpisode```. If the later (abandoned, not more tested / in use?) might sometimes be broken, I'm not sure how this influences the former.

But I've experienced some issues with api.arte.tv. Sometimes JSON from ```https://api.arte.tv/api/player/v2/config/...``` is missing m3u8 URLs. Since it's not easy reproducible (only during high load on arte servers?), I have not reported it yet.

**Comment by wilhelmy** [comment]
It isn't working on https://www.arte.tv/de/videos/RC-024878/samuel/

**Comment by dirkf** [comment]
A verbose log would illustrate **what** is not working and, with luck, **how**. Your interpretation of the result compared to what you expected to happen could also be useful.

**Comment by wilhelmy** [comment]
```
$ yt-dlp -vv 'https://www.arte.tv/de/videos/RC-024878/samuel/'
[debug] Command-line config: ['-vv', 'https://www.arte.tv/de/videos/RC-024878/samuel/']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.08.06 from yt-dlp/yt-dlp [4d9231208] (debian*)
[debug] Python 3.12.6 (CPython x86_64 64bit) - Linux-6.3.0-1-amd64-x86_64-with-glibc2.40 (OpenSSL 3.3.2 3 Sep 2024, glibc 2.40)
[debug] exe versions: ffmpeg 7.0.2-3 (setts), ffprobe 7.0.2-3
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.08.30, mutagen-1.46.0, pyxattr-0.8.1, requests-2.32.3, sqlite3-3.46.0, urllib3-2.0.7, websockets-10.4
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Loaded 1830 extractors
[ArteTVPlaylist] Extracting URL: https://www.arte.tv/de/videos/RC-024878/samuel/
[ArteTVPlaylist] RC-024878: Downloading JSON metadata
[download] Downloading playlist: Samuel
[ArteTVPlaylist] Playlist Samuel: Downloading 0 items
[download] Finished downloading playlist: Samuel
```

Well, it tells me the playlist is empty when there's actually videos in it.
As @ocococococ pointed out, adding 1 to the playlist ID does the trick and the playlist downloads:

```
mw@flare ~/samuel $ yt-dlp -vv 'https://www.arte.tv/de/videos/RC-024879/samuel/'
[debug] Command-line config: ['-vv', 'https://www.arte.tv/de/videos/RC-024879/samuel/']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.08.06 from yt-dlp/yt-dlp [4d9231208] (debian*)
[debug] Python 3.12.6 (CPython x86_64 64bit) - Linux-6.3.0-1-amd64-x86_64-with-glibc2.40 (OpenSSL 3.3.2 3 Sep 2024, glibc 2.40)
[debug] exe versions: ffmpeg 7.0.2-3 (setts), ffprobe 7.0.2-3
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.08.30, mutagen-1.46.0, pyxattr-0.8.1, requests-2.32.3, sqlite3-3.46.0, urllib3-2.0.7, websockets-10.4
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Loaded 1830 extractors
[ArteTVPlaylist] Extracting URL: https://www.arte.tv/de/videos/RC-024879/samuel/
[ArteTVPlaylist] RC-024879: Downloading JSON metadata
[download] Downloading playlist: Samuel
[ArteTVPlaylist] Playlist Samuel: Downloading 21 items of 21
[download] Downloading item 1 of 21
...
```

**Comment by dirkf** [comment]
According to [@ocococococ's subsequently posted fix](https://github.com/yt-dlp/yt-dlp/issues/1059#issuecomment-1784269895), the playlist needs to be fetched with the v4 API rather than v3 or v2 that might be used now.

**Comment by wilhelmy** [comment]
Perhaps this fix can be merged, or submitted as a pull request?
"This commit isn't attached to a branch" didn't inspire confidence that this will be fixed soon, but for now I have a workaround at least. Thanks @ocococococ!
(Note that this issue we're commenting in is marked as closed)

**Comment by bashonly** [comment]
please continue discussion in #2945
