### ISSUE TITLE
Direct Image Link Won't Download from Imgur

### ISSUE THREAD

**Issue by SwimmingLink** [yt-dlp/yt-dlp#10596]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I understand that this was written as an A/V downloader, but I've been additionally using it to download pretty much everything that I download for the "Date modified" timestamp as normal downloads in my browser just set that the same as the "Date created" timestamp. I've had no problem doing this on various sites over the years with direct file links until yesterday when I attempted to download an image from Imgur for the first time and it won't let me because it's not a video or animated image. Is this expected behaviour (possibly some safety/security thing that I don't understand) that's intended to be kept? If not, can this question be converted to a feature request / bug fix to allow direct file links to still be able to download even if they are other file types?

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://i.imgur.com/ZfDGJMT.png']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.07.25.232820 from yt-dlp/yt-dlp-nightly-builds [28d485714] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.26120-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 2024-07-28-git-e7d3ff8dcd-full_build-www.gyan.dev (setts), ffprobe 2024-07-28-git-e7d3ff8dcd-full_build-www.gyan.dev, phantomjs 2.1.1, rtmpdump 2.3
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.07.04, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1828 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.07.25.232820 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.07.25.232820 from yt-dlp/yt-dlp-nightly-builds)
[Imgur] Extracting URL: https://i.imgur.com/ZfDGJMT.png
[Imgur] ZfDGJMT: Downloading JSON metadata
ERROR: [Imgur] ZfDGJMT: ZfDGJMT is not a video or animated image
  File "yt_dlp\extractor\common.py", line 740, in extract
  File "yt_dlp\extractor\imgur.py", line 104, in _real_extract
```

**Comment by bashonly** [comment]
> Is this expected behaviour

Yes. Downloading image-only content is out-of-scope for yt-dlp. The generic extractor may work with images or non-video/audio files, but dedicated extractor support will not be added for images

**Comment by dirkf** [comment]
The Imgur extractor has always been restricted to finding video and animated image data. You might argue that a static image is a special case of an animated image with a single frame, but I believe that other programs exist for image downloading.
