### ISSUE TITLE
New Player 20dfca59 has broken YouTube extractor

### ISSUE THREAD

**Issue by BloodSugar327** [yt-dlp/yt-dlp#10608]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Provide a description that is worded well enough to be understood

A new player (20dfca59) has broken the YouTube extractor

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.07.25 from yt-dlp/yt-dlp [f0993391e] (pip)
[debug] Python 3.12.3 (CPython AMD64 64bit) - Windows-11-10.0.22631-SP0 (OpenSSL 3.0.13 30 Jan 2024)
[debug] exe versions: ffmpeg N-116328-gfa5a605542-20240718 (setts), ffprobe N-116328-gfa5a605542-20240718
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.07.04, mutagen-1.47.0, requests-2.32.3, sqlite3-3.45.1, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1829 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.07.25 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.07.25 from yt-dlp/yt-dlp)
[youtube:tab] Extracting URL: https://music.youtube.com/playlist?list=OLAK5uy_kOExsg4A5Wc7X3_DhtK4GB0YqdeFIIjhs
WARNING: [youtube:tab] YouTube Music is not directly supported. Redirecting to https://www.youtube.com/playlist?list=OLAK5uy_kOExsg4A5Wc7X3_DhtK4GB0YqdeFIIjhs
[youtube:tab] OLAK5uy_kOExsg4A5Wc7X3_DhtK4GB0YqdeFIIjhs: Downloading webpage
[debug] [youtube:tab] Extracted SAPISID cookie
[youtube:tab] OLAK5uy_kOExsg4A5Wc7X3_DhtK4GB0YqdeFIIjhs: Redownloading playlist API JSON with unavailable videos
[download] Downloading playlist: Album - Meteora 20th Anniversary Edition
[youtube:tab] Playlist Album - Meteora 20th Anniversary Edition: Downloading 89 items of 89
[download] Downloading item 1 of 89
[youtube] Extracting URL: https://music.youtube.com/watch?v=d_iv0n9ZpAg
[youtube] d_iv0n9ZpAg: Downloading webpage
[debug] [youtube] Extracted SAPISID cookie
[youtube] d_iv0n9ZpAg: Downloading ios player API JSON
[youtube] d_iv0n9ZpAg: Downloading ios music player API JSON
[youtube] d_iv0n9ZpAg: Downloading web music client config
[youtube] d_iv0n9ZpAg: Downloading player 20dfca59
[youtube] d_iv0n9ZpAg: Downloading web music player API JSON
[debug] [youtube] Extracting signature function js_20dfca59_107
[debug] Loading youtube-sigfuncs.js_20dfca59_107 from cache
WARNING: [youtube] d_iv0n9ZpAg: nsig extraction failed: Some formats may be missing
         n = A1Ou24bVhXz1jIVy ; player = https://www.youtube.com/s/player/20dfca59/player_ias.vflset/en_US/base.js
[debug] [youtube] Unable to extract nsig function code (caused by RegexNotFoundError('Unable to extract \x1b[0;94mInitial JS player n function name\x1b[0m; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [youtube] d_iv0n9ZpAg: nsig extraction failed: Some formats may be missing
         n = -fLCxedkAk4LUTK2 ; player = https://www.youtube.com/s/player/20dfca59/player_ias.vflset/en_US/base.js
[debug] [youtube] Extracting signature function js_20dfca59_103
[debug] Loading youtube-sigfuncs.js_20dfca59_103 from cache
WARNING: [youtube] d_iv0n9ZpAg: nsig extraction failed: Some formats may be missing
         n = lfFDQouqFm1Pmkfk ; player = https://www.youtube.com/s/player/20dfca59/player_ias.vflset/en_US/base.js
WARNING: [youtube] d_iv0n9ZpAg: nsig extraction failed: Some formats may be missing
         n = N6FLr39qpAOmT5Ak ; player = https://www.youtube.com/s/player/20dfca59/player_ias.vflset/en_US/base.js
```

**Comment by OzzyHelix** [comment]
yeah I noticed an issue where mp4's download with no sound I assume this is related

**Comment by BloodSugar327** [comment]
> I'm getting the same error

The referenced branch fixes it. You can wait for it to be merged to the main/nightly or download the YouTube.py and replace the one you have in extractors.

**Comment by kolbdog323** [comment]
I'm not using the pip version I'm using the exe so i have to wait until it's merged.

> > I'm getting the same error
> 
> The referenced branch by bashonly fixes it. You can wait for it to be merged to the main/nightly or download the YouTube.py and replace the one you have in extractors.

**Comment by WA1870** [comment]
Tomorrow I Download Videos Have No Problem.
Now After 12;00AM Get This Error. 


WARNING: [youtube] vhgzkyCmesw: nsig extraction failed: Some formats may be missing
         n = jVeOS8cTQ1N9R_Um ; player = https://www.youtube.com/s/player/20dfca59/player_ias.vflset/en_US/base.js

**Comment by zackees** [comment]
Any word when a new release will be minted with this fix?

**Comment by bashonly** [comment]
@zackees https://github.com/yt-dlp/yt-dlp/releases/tag/2024.08.01
