### ISSUE TITLE
Site conditional parameters in yt-dlp.conf

### ISSUE THREAD

**Issue by twilson90** [yt-dlp/yt-dlp#10609]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

In my yt-dlp.conf I want to automatically sign into youtube with oauth2:
`--username oauth2 --password ''`
But this will then cause links from other video hosting sites to print the error:
`Login using username and password is not currently supported.`
How can I setup my conf file so it only applies these parameters when the url is youtube?

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
Use a netrc file: https://github.com/yt-dlp/yt-dlp?tab=readme-ov-file#authentication-with-netrc

**Comment by twilson90** [comment]
Thanks!
