### ISSUE TITLE
[YouTube] Broken formats and nsig extraction failed errors

### ISSUE THREAD

**Issue by Sanrax** [yt-dlp/yt-dlp#10617]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United States

### Provide a description that is worded well enough to be understood

Downloading any video and requesting mp4 format causes an error, and yt-dlp is throwing warnings about nsig exctraction failing, as well as missing formats.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '-f', 'best[ext=mp4]', 'https://www.youtube.com/watch?v=P-uyKrPlH9Q']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.07.25 from yt-dlp/yt-dlp [f0993391e] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 2024-06-16-git-fcf72966a5-essentials_build-www.gyan.dev (setts), ffprobe 2024-06-16-git-fcf72966a5-essentials_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.07.04, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1829 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.07.25 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.07.25 from yt-dlp/yt-dlp)
[youtube] Extracting URL: https://www.youtube.com/watch?v=P-uyKrPlH9Q
[youtube] P-uyKrPlH9Q: Downloading webpage
[youtube] P-uyKrPlH9Q: Downloading ios player API JSON
[youtube] P-uyKrPlH9Q: Downloading player 20dfca59
WARNING: [youtube] P-uyKrPlH9Q: nsig extraction failed: Some formats may be missing
         n = AwWwGoHtvVoQAQML ; player = https://www.youtube.com/s/player/20dfca59/player_ias.vflset/en_US/base.js
[debug] [youtube] Unable to extract nsig function code (caused by RegexNotFoundError('Unable to extract \x1b[0;94mInitial JS player n function name\x1b[0m; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [youtube] P-uyKrPlH9Q: nsig extraction failed: Some formats may be missing
         n = 2eFi_ZZ_W8OlruDX ; player = https://www.youtube.com/s/player/20dfca59/player_ias.vflset/en_US/base.js
[youtube] P-uyKrPlH9Q: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
ERROR: [youtube] P-uyKrPlH9Q: Requested format is not available. Use --list-formats for a list of available formats
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1626, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1782, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1841, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2977, in process_video_result
yt_dlp.utils.ExtractorError: [youtube] P-uyKrPlH9Q: Requested format is not available. Use --list-formats for a list of available formats
```

**Comment by gamer191** [comment]
Thank you for the bug report

I have confirmed that it does not affect the latest master build of yt-dlp. I recommend running `yt-dlp --update-to master`

**Comment by Sanrax** [comment]
> Thank you for the bug report
> 
> I have confirmed that it does not affect the latest master build of yt-dlp. I recommend running `yt-dlp --update-to master`

Oh. I thought update to master meant the same thing as stable. Gotcha, thanks.

**Comment by bashonly** [comment]
Duplicate of #10608
