### ISSUE TITLE
The recorded file is overwrited when it's "unable to resume"

### ISSUE THREAD

**Issue by sumire608** [yt-dlp/yt-dlp#10622]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

I'm recording tiktok live, but when it's about finished, the part file has be overwrited. 

The 9.26GB file is overwrited by the 8MB file. It should be kept.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
G:\>yt-dlp "https://pull-f5-va01.tiktokcdn.com/activity/stream-2997893220272439373_uhd5.flv?_session_id=084-20240801045727232E95363C7EED3B7051.1722488246238&expire=1723697848&sign=962e33655a64546446cad346c547cdbc&_webnoredir=1&abr_pts=4430899"
[generic] Extracting URL: https://pull-f5-va01.tiktokcdn.com/activity/stream-2997893220272439373_uhd5.flv?_session_id=084-2...ir=1&abr_pts=4430899
[generic] stream-2997893220272439373_uhd5.flv?_session_id=084-20240801045727232E95363C7EED3B7051: Downloading webpage
[info] stream-2997893220272439373_uhd5.flv?_session_id=084-20240801045727232E95363C7EED3B7051: Downloading 1 format(s): x-flv
[download] Destination: stream-2997893220272439373_uhd5 [stream-2997893220272439373_uhd5.flv？_session_id=084-20240801045727232E95363C7EED3B7051].flv
[download]    9.26GiB at  383.32KiB/s (07:02:00)[download] Got error: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:2635). Retrying (1/10)...
[download] Unable to resume
[download] Destination: stream-2997893220272439373_uhd5 [stream-2997893220272439373_uhd5.flv？_session_id=084-20240801045727232E95363C7EED3B7051].flv
[download]    8.00MiB at  795.25KiB/s (07:02:22)[download] Got error: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:2635). Retrying (2/10)...
ERROR: unable to download video data: HTTP Error 404: Not Found
```

**Comment by sumire608** [comment]
I don't know if use "--no-post-overwrites" parameter can avoid this issue, but I think the default should be "--no-post-overwrites", not "-post-overwrites". It's an important 6 hours live, and now it's gone. Sad.

**Comment by bashonly** [comment]
Sorry that you lost your downloaded stream. Unfortunately, there's not much that can be done about this. A dedicated extractor (e.g. if you had used the tiktok live webpage url instead of the direct flv url) would give each download a unique title by adding a timestamp into the title. When you pass a direct flv/etc url, you are using the generic extractor, which can't always detect if what you're giving it is a live stream, and at that point it's up to you to use an output template that will be unique, e.g. `-o "%(title)s %(epoch)s %(id)s.%(ext)s"`

This is the same issue as #6740 though, so closing as duplicate

**Comment by sumire608** [comment]
It seems tiktok live extractor has outdated. Every live shows a message like "XX channel is not living".

**Comment by bashonly** [comment]
Make sure you're on the latest version of yt-dlp; it was partially fixed in a recent release.

If you are still getting a "channel is not live" error every time, then you are likely getting a captcha page from tiktok: 
- #9418

You could try passing cookies to yt-dlp to see if that helps

**Comment by sumire608** [comment]
Neither cookies from browser or cookies from text file works.
Seems outdated.

**Comment by bashonly** [comment]
That's why the above-linked issue is still open

**Comment by sumire608** [comment]
Thank you, I may have to use flv URL & -o with manual parameters temporarily.
