### ISSUE TITLE
Any way to create a logfile.txt that prints errors and warnings?

### ISSUE THREAD

**Issue by cpz3501** [yt-dlp/yt-dlp#10629]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I looked through the options and found no way to do this, I have a rather hard time understanding this kind of stuff, so apologies if I missed the relevant option.

What I'm trying to achieve is something like a logfile.txt that outputs errors from failed URL downloads, especially from youtube and soundcloud, using a config.bat (commandline?) file.

I was imagining something like what gallery-dl does with this code. (Code for reference because I'm struggling to explain this properly)

```
        "logfile": {
              "path": "log.txt",
              "mode": "a",
	      "format": {
                            "info"    : "[{asctime}][{levelname}][{name}]  {message}",
                            "warning" : "[{asctime}][{levelname}][{name}]  {message} [Source URL: {extractor.url}]",
                            "error"   : "[{asctime}][{levelname}][{name}]  {message} [Source URL: {extractor.url}]"
	      },
                   "format-date": "%Y-%m-%d %H_%M_%S"
          }
```

In the case that this is currently not possible without using a complicated workaround, I would like to ask for a feature request.

If this is already possible, perhaps someone can give a few pointers?

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
like this?
```
yt-dlp "URL" 2> log.txt
```

**Comment by grqz** [comment]
> * Each download operation overwrites the previous log and basically deletes it. Is there currently a way to add new log lines instead of overwriting it?  (making it "cumulative")

try `2>>log.txt` instead of `2>log.txt`.

> 2\. Can a timestamp be added to each error and warning? So that large automated downloads can be manually corrected after they are completed (since it's almost guaranteed that something will go wrong when over 1k videos are downloaded).

try [embedding yt-dlp into a python program](https://github.com/yt-dlp/yt-dlp?tab=readme-ov-file#embedding-yt-dlp)? use `open('log.txt', 'a')` to append. `devscripts/cli_to_api.py` can generate API options

**Comment by bashonly** [comment]
Related feature requests: #2668, #1761, #1659

**Comment by pukkandan** [comment]
> 2. Can a timestamp be added to each error and warning?

https://unix.stackexchange.com/questions/26728

**Comment by cpz3501** [comment]
Thanks for the replies.

I've spent a few hours on this but I don't think I can figure this out, I realize phython is simple and you pretty much handed it to me on a silver platter, but my head already hurts from writing a .bat for cmd or whatever it's called, so I'm not sure how to do it.

If the original post implies I know a bit more than the average end user about code, than nope, almost just copied from other people.

Nevertheless, thanks for your work, I really appreciate yt-dlp, especially after the original youtube-dl was dropped.

**Comment by Lichtenshtein** [comment]
For Windows you may get [moreutils-go](https://github.com/gabe565/moreutils-go). This way you will export only warnings and error messages with timestamps to your log file (and debug info with -v):

`yt-dlp -F "URL" 3>&1 1>&2 2>&3 | moreutils ts "[%T]" >"%TEMP%\yt-dlp-log.txt"`

This is not ideal. Right now i'm looking for a way to not suppress anything in stdout, and at the same time to export only errors and warnings WITH timestamps to log file - to show them after download is finished. 

Okay, for now i've tried everything i could find and none of it works: i can see either errors or info in terminal and never both.
