### ISSUE TITLE
Fails to continue to download Rumble Video from Embed Code

### ISSUE THREAD

**Issue by steelliberty** [yt-dlp/yt-dlp#10638]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United States

### Provide a description that is worded well enough to be understood

I have established python running for more than a year downloading from multiple sources including Rumble.  Over the past 24 hours some of the rumble download just fail with no additional info. 

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
(transcriber) root@transcriber:~/transcriber/mypatriotsnetwork.com# yt-dlp -vU --proxy http://154.201.47.22:3128 --get-filename https://rumble.com/embed/v56xz42
[debug] Command-line config: ['-vU', '--proxy', 'http://154.201.47.22:3128', '--get-filename', 'https://rumble.com/embed/v56xz42']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.08.01 from yt-dlp/yt-dlp [ffd7781d6] (pip)
[debug] Python 3.10.11 (CPython x86_64 64bit) - Linux-5.19.0-46-generic-x86_64-with-glibc2.36 (OpenSSL 1.1.1t  7 Feb 2023, glibc 2.36)
[debug] exe versions: ffmpeg 5.1.1 (setts), ffprobe 5.1.1
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.07.04, curl_cffi-0.6.2 (unsupported), mutagen-1.47.0, requests-2.32.3, sqlite3-3.41.2, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {'all': 'http://154.201.47.22:3128'}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1830 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.08.01 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.08.01 from yt-dlp/yt-dlp)
[RumbleEmbed] Extracting URL: https://rumble.com/embed/v56xz42
[RumbleEmbed] v56xz42: Downloading JSON metadata
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] v56xz42: Downloading 1 format(s): mp4-480p
RBN Authentic News (31 July 2024) [v56xz42].mp4
```

**Comment by bashonly** [comment]
You are passing `--get-filename`, which (per the documentation) implies simulation: it will only print the filename and not actually download the file

**Comment by steelliberty** [comment]
That works- but it worked for a year with that there- thank you- sorry for the trouble.
