### ISSUE TITLE
Quality bug or not downloading video

### ISSUE THREAD

**Issue by GuilhermeCouto** [yt-dlp/yt-dlp#10635]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

The last update crashed my app. When I use -f best doesn't downlaod, or download in worst quality.

Any solution?

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
The last update 01/08 crashed my app. When I use "-f best" download in worst quality.

When I use "-f best[height<=1080]" or  "-f best[filesize<=500M]" I got the error below:

ERROR: [youtube] LXb3EKWsInQ: Requested format is not available. Use --list-formats for a list of available formats
                                                                                                    

Any solution?
```

**Comment by bashonly** [comment]
`-f best` is probably not what you want. It will only select the SINGLE "best" combined video+audio format, whereas most formats offered by youtube are separate video and audio tracks (e.g. `-f bestvideo+bestaudio`). The default format selection is `-f "bv*+ba/b"` (see the [README](https://github.com/yt-dlp/yt-dlp#format-selection))

> -f best[height<=1080]

Instead of using that, I would not use any `-f` argument, and instead pass `-S res:1080`

> -f best[filesize<=500M]

Instead of that, try something like `-f "bestvideo[filesize<=500M]+bestaudio[filesize<=500M]/best[filesize<=500M]"`

**Comment by dirkf** [comment]
Isn't this equivalent?
`-f "(bestvideo+bestaudio/best)[filesize<=500M]"`

**Comment by bashonly** [comment]
sure

**Comment by GuilhermeCouto** [comment]
Thank you!!

I updated to NIGHTLY and fixed the bug then
I used `-S res:1080` and it worked like a charm!!!
