### ISSUE TITLE
How to change the sipmle rate using a post processor

### ISSUE THREAD

**Issue by Daoprotoss** [yt-dlp/yt-dlp#10632]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Здравствуйте. Мне нужно скачать аудио дорожку ютуб видео, преобразовать его в формат огг и назначить ему симпле рате в 41100. Я смог сделать все кроме симл рейта, прошу подсказать что делать:
`
-x
--remux-video ogg
--audio-quality 1
--no-keep-video
--postprocessor-args "ffmpeg:-ar 44100"
`

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
Is this your post? https://old.reddit.com/r/youtubedl/comments/1ei8q40/ytdlp_how_to_change_simple_rate/

As explained there, it is not possible with opus formats. That is why all opus formats from youtube are 48kHz. You could select a non-opus format, but it likely would already be 44.1kHZ
