### ISSUE TITLE
How to specify different output names for audio and video files (without including format/codec)?

### ISSUE THREAD

**Issue by Lieutenant-L-T-Smash** [yt-dlp/yt-dlp#10650]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

For simplicity's sake, let's say I'm using `-f ba,bv` to get separate audio and video files. I don't care what the format/codec of either actually is, but I want the audio file to have a `.a` extension and the video file to have `.v`

What should my `-o` parameter look like? I've read the section about replacement values.

I've tried:

`-o '%(id)s.%(hasaud&a|v)s'` -> This has both files ending in .v
`-o '%(id)s.%(hasvid&v|a)s'` -> This has both files ending in .a
`-o '%(id)s.%(vocodec&v|a)s'` -> This has both files ending in .v (Why? The audio file vcodec should have "empty" value per the docs so the second replacement should be applied)
`-o '%(id)s.%(vocodec=none&a|v)s'` -> This has both files ending in .NA (This absolutely defeats me, because I can't make any sense whatsoever of how this could be the output. "a" and "v" should be the only possibilities.)
`-o '%(id)s.%(vcodec=NA&a|v)s'` -> Same as above.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
```
--parse-metadata 'video:%(acodec)s:^(?P<has_audio>(?!none).+)$'
--parse-metadata 'video:%(vcodec)s:^(?P<has_video>(?!none).+)$'
-o '%(id)s.%(has_video&v|)s%(has_audio&a|)s'
```

**Comment by Lieutenant-L-T-Smash** [comment]
Okay, thanks. But I'd really like to understand what I'm doing, and especially what I'm doing **wrong**, so why doesn't `-o '%(id)s.%(vcodec=none&a|v)s'` work? And especially, how does the syntax allow `NA` to be the output?

**Comment by bashonly** [comment]
`vcodec=none` is not valid in an output template. The `=` operator is not supported at all, and it is breaking the parsing.

```
--parse-metadata 'video:acodec:^(?P<has_audio>(?!none).+)$'
--parse-metadata 'video:vcodec:^(?P<has_video>(?!none).+)$'
```

Here you are parsing values for custom fields `has_audio` and `has_video` by using regex to match anything other than `'none'`. An audio-only format will have a `vcodec` value of `'none'` (string) and a video-only format will have an `acodec` value of `'none'` (string)

```
-o '%(id)s.%(has_video&v|)s%(has_audio&a|)s'
```
Then you're putting the new custom fields to use in the output template... if `has_video` then `'v'` else `''` etc

**Comment by Lieutenant-L-T-Smash** [comment]
I see now. The tripmine for me was that I assumed the first part of a replacement can be an expression, but it only takes a plain field name.

I was able to figure out the `--parse-metadata` after some headscratching (although the ?P<> syntax isn't really _specified_ anywhere, it's only given in examples.)

Thank you for the help.
