### ISSUE TITLE
[YouTube] Allow download geoblocked videos using remoteHost

### ISSUE THREAD

**Issue by joaquinito2070** [yt-dlp/yt-dlp#10656]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

I tested, and I need to add remoteHost to download geoblocked videos using --extractor-args "youtube:remote_host:[IPv4|IPv6]".

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
How is this different from `--proxy`?

**Comment by joaquinito2070** [comment]
Adds --extractor-args "youtube:bypass_geoblock=true" to check and connect to all proxies from this list (HTTP, HTTPS, SOCKS4 and SOCKS5): https://raw.githubusercontent.com/0x1337fy/fresh-proxy-list/archive/storage/classic/all.txt
If it succeds, it will stop checking, and if it does not succeds, and still giving error that is not available in your country, it will still checking until it founds one.

**Comment by bashonly** [comment]
Out-of-scope. A job for an external script, in which you can use the `--proxy` option

**Comment by azisalvriyanto** [comment]
I'm sorry, I have just updated my GitHub username, and to see my proxies updated in https://raw.githubusercontent.com/azisalvriyanto/fresh-proxy-list/archive/storage/classic/all.txt
