### ISSUE TITLE
[Discovery+] (Italy) Error 404 when trying to download Olympic videos

### ISSUE THREAD

**Issue by FG-GIS** [yt-dlp/yt-dlp#10654]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Italy

### Provide a description that is worded well enough to be understood

Whenever I try to download an olympic video I get this error:
`[DiscoveryPlusItaly] olympics/dplus-sport-dplus-sport-sport: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: Not Found>)`
I believe is the same issue as #10564, which was resolved some days ago in the nightly build. I'm already using that, for what I can see the same errors as that issue are popping out in my terminal.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--xff', 'never', '--cookies-from-browser', 'brave', 'https://www.discoveryplus.com/it/video/olympics/dplus-sport-dplus-sport-sport/water-polo-greece-italy']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8 
[debug] yt-dlp version nightly@2024.08.01.232808 from yt-dlp/yt-dlp-nightly-builds [919540a96] (pip) 
[debug] Python 3.10.11 (CPython AMD64 64bit) - Windows-10-10.0.26100-SP0 (OpenSSL 1.1.1t  7 Feb 2023) 
[debug] exe versions: none 
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.07.04, mutagen-1.47.0, requests-2.32.3, sqlite3-3.40.1, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {}
Extracting cookies from brave
[debug] Extracting cookies from: "C:\Users\giova\AppData\Local\BraveSoftware\Brave-Browser\User Data\Default\Network\Cookies" 
[debug] Found local state file at "C:\Users\giova\AppData\Local\BraveSoftware\Brave-Browser\User Data\Local State" 
Extracted 1709 cookies from brave 
[debug] cookie version breakdown: {'v10': 1708, 'other': 0, 'unencrypted': 5}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1830 extractors 
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest 
Latest version: nightly@2024.08.01.232808 from yt-dlp/yt-dlp-nightly-builds 
yt-dlp is up to date (nightly@2024.08.01.232808 from yt-dlp/yt-dlp-nightly-builds)
[DiscoveryPlusItaly] Extracting URL: https://www.discoveryplus.com/it/video/olympics/dplus-sport-dplus-sport-sport/water-polo-greece-italy 
[DiscoveryPlusItaly] olympics/dplus-sport-dplus-sport-sport: Downloading JSON metadata 
ERROR: [DiscoveryPlusItaly] olympics/dplus-sport-dplus-sport-sport: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: Not Found>) 
  File "c:\Users\giova\Documents\99_yt_dlp\.venv\lib\site-packages\yt_dlp\extractor\common.py", line 740, in extract 
    ie_result = self._real_extract(url)
  File "c:\Users\giova\Documents\99_yt_dlp\.venv\lib\site-packages\yt_dlp\extractor\dplay.py", line 373, in _real_extract
    return self._get_disco_api_info(url, self._match_id(url), **self._DISCO_API_PARAMS)
  File "c:\Users\giova\Documents\99_yt_dlp\.venv\lib\site-packages\yt_dlp\extractor\dplay.py", line 79, in _get_disco_api_info
    video = self._download_json(
  File "c:\Users\giova\Documents\99_yt_dlp\.venv\lib\site-packages\yt_dlp\extractor\common.py", line 1139, in download_content
    res = getattr(self, download_handle.__name__)(url_or_request, video_id, **kwargs)
  File "c:\Users\giova\Documents\99_yt_dlp\.venv\lib\site-packages\yt_dlp\extractor\common.py", line 1099, in download_handle
    res = self._download_webpage_handle(
  File "c:\Users\giova\Documents\99_yt_dlp\.venv\lib\site-packages\yt_dlp\extractor\common.py", line 960, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data,
  File "c:\Users\giova\Documents\99_yt_dlp\.venv\lib\site-packages\yt_dlp\extractor\common.py", line 909, in _request_webpage
    raise ExtractorError(errmsg, cause=err)

  File "c:\Users\giova\Documents\99_yt_dlp\.venv\lib\site-packages\yt_dlp\extractor\common.py", line 896, in _request_webpage
    return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query, extensions))
  File "c:\Users\giova\Documents\99_yt_dlp\.venv\lib\site-packages\yt_dlp\YoutubeDL.py", line 4165, in urlopen
    return self._request_director.send(req)
  File "c:\Users\giova\Documents\99_yt_dlp\.venv\lib\site-packages\yt_dlp\networking\common.py", line 117, in send
    response = handler.send(request)
  File "c:\Users\giova\Documents\99_yt_dlp\.venv\lib\site-packages\yt_dlp\networking\_helper.py", line 208, in wrapper
    return func(self, *args, **kwargs)
  File "c:\Users\giova\Documents\99_yt_dlp\.venv\lib\site-packages\yt_dlp\networking\common.py", line 340, in send
    return self._send(request)
  File "c:\Users\giova\Documents\99_yt_dlp\.venv\lib\site-packages\yt_dlp\networking\_requests.py", line 365, in _send
    raise HTTPError(res, redirect_loop=max_redirects_exceeded)
yt_dlp.networking.exceptions.HTTPError: HTTP Error 404: Not Found
```

**Comment by bashonly** [comment]
dplus italy was split into its own extractor and it did not receive the olympics URL fix in the last patch.

Try with this:

```
python -m pip install --force-reinstall "yt-dlp[default] @ https://github.com/bashonly/yt-dlp/archive/fix/dplus-it.tar.gz"
```

**Comment by bashonly** [comment]
Note that currently live events and VOD replays of events from within the last ~3 hours will give a 403 error. This happens because there is no non-DRM stream available until there is a proper archive VOD manifest, which is generated approx 4 hours after the livestream ends

**Comment by FG-GIS** [comment]
The patch did work, thank you kindly!
