### ISSUE TITLE
Allow for multiple archive files (--download-archive in CLI and config)

### ISSUE THREAD

**Issue by Squaredude** [yt-dlp/yt-dlp#10661]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

I have tried running --download-archive in both config and command, but only one archive file is updated.

The idea is to keep a global archive of downloaded videos (set in the config file), and then use another archive file in the command line, with priority going first to the command line, then the config file.

For example: the video has not been previously downloaded according to the archive in the command line, then yt-dlp checks for the archive in the config file; if it has been downloaded in the config file, then skip video as normal.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
What is the use case for having a fallback download archive like this? Which archive file is the entry recorded to? Both? I'm having difficulty imagining how this should be implemented since I can't imagine why it would be useful.

**Comment by Squaredude** [comment]
Use case is that I'm downloading several playlists of various topics, and I want to keep a global archive and a per-playlist archive, to avoid downloading the same stuff in different runs.

I would keep the global archive in config, and the per-playlist archive at the command call.

I hope it's clearer than my initial example.

**Comment by bashonly** [comment]
I still don't understand... what is preventing you from just using a global archive file?

**Comment by Squaredude** [comment]
Gotcha, thanks anyway.

I'll see what I can do on my end.

**Comment by bashonly** [comment]
I wasn't being dismissive, I actually didn't understand and I was asking for clarification on what the unique benefit of a fallback download archive would be
