### ISSUE TITLE
How to restrictly set a MAX-SIZE-LIMIT for each download task?

### ISSUE THREAD

**Issue by tienll** [yt-dlp/yt-dlp#10663]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I would like to give a limit before downloading everything, so I'm wondering if that possible to

- predict the total bytes of whole download task before actually download all of the files;    or
- set the limit and download is stopped once the transferred bytes exceed it

Thanks!

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
> set the limit and download is stopped once the transferred bytes exceed it

https://github.com/yt-dlp/yt-dlp#video-selection
```
--max-filesize SIZE             Abort download if filesize is larger than
                                SIZE, e.g. 50k or 44.6M
```

> predict the total bytes of whole download task before actually download all of the files; or

There is no fully automatic way of doing this, but you could print all of the known filesizes with this command:

```
yt-dlp --print "%(filesize,filesize_approx)s" "URL"
```

and then add them together with an external command/script

**Comment by tienll** [comment]
Thanks @bashonly

I tried both of them however they are not working well with twitter url, which is parsed into several m3u8 links.

-  --print filesize gets "NA"
- --max-filesize doesn't stop the download

is there any other workaround for twitter url?

**Comment by tienll** [comment]
Or can I assume that there's no simple or uniform approach at this moment?

**Comment by bashonly** [comment]
> --print filesize gets "NA"

For manifest formats (e.g. m3u8/HLS and mpd/DASH), you'll need to additionally pass `--compat-opt manifest-filesize-approx` in order to include those formats' inaccurate `filesize_approx` values in the extracted info (documented [here](https://github.com/yt-dlp/yt-dlp?tab=readme-ov-file#differences-in-default-behavior)). So that would be:
```
--print "%(filesize,filesize_approx)s" --compat-opt manifest-filesize-approx
```

> --max-filesize doesn't stop the download

IIRC `--max-filesize` doesn't work as expected with manifest formats (HLS/DASH). I am almost positive there is an open issue about this, but I can't find it right now

**Comment by tienll** [comment]
Thanks, it works!

**Comment by dirkf** [comment]
>... there is an open issue about this, but I can't find it right now

ytdl-org/youtube-dl#22133 covers this. Here and upstream, the filesize test is only applied for external (where the downloader supports it) and http downloads.

I guess the fragment downloader(s) should test against the filesize[_approx] in the info JSON, which would have always to be generated.

**Comment by cacfd3a** [comment]
https://github.com/yt-dlp/yt-dlp/issues/14628
https://github.com/yt-dlp/yt-dlp/issues/5353

`--max-filesize` currently does not make much sense, in my opinion. It would be really nice if it there was a way to really just fail (and clean up) as soon as the resulting video is going to be over some size limit.
