### ISSUE TITLE
.m3u8 files - ERROR: [generic] Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: Forbidden>)

### ISSUE THREAD

**Issue by jameel-ansari** [yt-dlp/yt-dlp#10665]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United Kingdom

### Provide a description that is worded well enough to be understood

This exact command worked a few days ago - upon trying today, it throws this error. I am trying to download a ".m3u8" file.

Command:
`yt-dlp --add-headers "Referer:https://player.hotmart.com/" "https://vod-akm.play.hotmart.com/video/9qrpNelAZp/hls/master-t-1709691402001.m3u8?hdnts=st%3D1722804308%7Eexp%3D1722804808%7Ehmac%3D6f9f965ee793748baa2a735d206e152e0d00b4a6ee8c334880e585b2770232ee&app=aa2d356b-e2f0-45e8-9725-e0efc7b5d29c" --cookies "cookies.txt" -o "5.
 Effective Notekeeping.%(ext)s"`

Output:
`[generic] Extracting URL: https://vod-akm.play.hotmart.com/video/9qrpNelAZp/hls/master-t-1709691402001.m3u8?hdnts=st%3D1722...e8-9725-e0efc7b5d29c
[generic] master-t-1709691402001: Downloading webpage
ERROR: [generic] Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: Forbidden>)`

Updated to latest version:
`yt-dlp --version`
`2024.08.01`

I have also tried with a VPN.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--add-headers', 'Referer:https://player.hotmart.com/', 'https://vod-akm.play.hotmart.com/video/9qrpNelAZp/hls/master-t-1709691402001.m3u8?hdnts=st%3D1722804308%7Eexp%3D1722804808%7Ehmac%3D6f9f965ee793748baa2a735d206e152e0d00b4a6ee8c334880e585b2770232ee&app=aa2d356b-e2f0-45e8-9725-e0efc7b5d29c', '--cookies', 'cookies.txt', '-o', '5. Effective Notekeeping.%(ext)s']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.08.01 from yt-dlp/yt-dlp [ffd7781d6] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22631-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-115218-g3fa98f274a-20240514 (setts), ffprobe N-115218-g3fa98f274a-20240514
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.07.04, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1830 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.08.01 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.08.01 from yt-dlp/yt-dlp)
[generic] Extracting URL: https://vod-akm.play.hotmart.com/video/9qrpNelAZp/hls/master-t-1709691402001.m3u8?hdnts=st%3D1722804308%7Eexp%3D1722804808%7Ehmac%3D6f9f965ee793748baa2a735d206e152e0d00b4a6ee8c334880e585b2770232ee&app=aa2d356b-e2f0-45e8-9725-e0efc7b5d29c
[generic] master-t-1709691402001: Downloading webpage
ERROR: [generic] Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: Forbidden>)
  File "yt_dlp\extractor\common.py", line 740, in extract
  File "yt_dlp\extractor\generic.py", line 2384, in _real_extract
  File "yt_dlp\extractor\common.py", line 909, in _request_webpage

  File "yt_dlp\extractor\common.py", line 896, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 4165, in urlopen
  File "yt_dlp\networking\common.py", line 117, in send
  File "yt_dlp\networking\_helper.py", line 208, in wrapper
  File "yt_dlp\networking\common.py", line 340, in send
  File "yt_dlp\networking\_requests.py", line 365, in _send
yt_dlp.networking.exceptions.HTTPError: HTTP Error 403: Forbidden
```

**Comment by bashonly** [comment]
the m3u8 link expired 16 hours ago

**Comment by jameel-ansari** [comment]
> the m3u8 link expired 16 hours ago

Thank you for your reply. I don't quite understand? The link that I grabbed expired or yt-dlp's ability to handle m3u8 links expired?

**Comment by jameel-ansari** [comment]
How could you tell it expired exactly 16 hours ago?

**Comment by grqz** [comment]
From your url:
![image](https://github.com/user-attachments/assets/fd35d168-8cef-4c98-bd27-258dc9da91f6)
There's an exp timestamp in the URL parameters. Goto https://www.epochconverter.com/ to convert that timestamp to human date

**Comment by bashonly** [comment]
The query params (expiration and signature, etc) are dynamically generated by the website. Get a new m3u8 URL from your browser and try with that

**Comment by jameel-ansari** [comment]
Thank you both for your helpful comments. Can confirm it's related to the expiry of the link.

I have 1 more question if you wouldn't mind, please - how would I / is it possible to download the "playlist" .m3u8 link instead of the "master"?

e.g:
`https://vod-akm.play.hotmart.com/video/Nq7BDeWyRA/hls/720/playlist-720-t-1709695279001.m3u8?hdntl=exp=1722951329~acl=/*~data=hdntl~hmac=5c9f49b83fee23df31d54c4bd437a6a32c91d67cbaa6d2391045653a45ac9dd8&app=aa2d356b-e2f0-45e8-9725-e0efc7b5d29c`

Thanks again!

**Comment by jameel-ansari** [comment]
> Pass that url to yt-dlp instead? It will be one of the formats that is extracted from the master m3u8, though. You can see the available formats by passing `-F` to yt-dlp

I tried getting a fresh "playlist" URL but it throws the 403 error no matter what:

`yt-dlp --add-headers "Referer:https://player.hotmart.com/" "https://vod-akm.play.hotmart.com/video/Nq7BDeWyRA/hls/224/playlist-224-t-1709695279001.m3u8?hdntl=exp=1722954195~acl=/*~data=hdntl~hmac=611336c866df8657d1408a6c3d7caa629a0b2ce2f1546734c9be57c99e4c4e75&app=aa2d356b-e2f0-45e8-9725-e0efc7b5d29c" -o "1. Course Overview.%(ext)s"`

`[generic] Extracting URL: https://vod-akm.play.hotmart.com/video/Nq7BDeWyRA/hls/224/playlist-224-t-1709695279001.m3u8?hdntl...e8-9725-e0efc7b5d29c`

`[generic] *~data=hdntl~hmac=611336c866df8657d1408a6c3d7caa629a0b2ce2f1546734c9be57c99e4c4e75&app=aa2d356b-e2f0-45e8-9725-e0efc7b5d29c: Downloading webpage`

`ERROR: [generic] Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: Forbidden>)`

**Comment by bashonly** [comment]
Don't know what's wrong then. For generic m3u8 URLs, it is the responsibility of the user to find how to make them work (i.e. this is not an extractor bug). You'll have to look in your browser's dev tools to see how it is requesting the m3u8 URL; look at the headers, query parameters, etc. You could try a browser extension like "The Stream Detector" for help with this

**Comment by hekmon** [comment]
Not sure if related but I had a similar issue with Crunchyroll (while using top level, human URL of the show and let the extractor do its job). Posting to help others if they search for issues and fint this one as well.

```
[crunchyroll] G8WUN2W3W: Downloading object info JSON (cms)
ERROR: [crunchyroll] XXXXXXX: Unable to download JSON metadata: HTTP Error 403: Forbidden (caused by <HTTPError 403: Forbidden>)
```

I think it was cloudflare blocking because I managed to work around the 403 with an impersonnate flag: `--impersonate Chrome-110:Windows-10`

**Comment by bashonly** [comment]
@hekmon Unrelated AFAIK, and the Crunchyroll extractor is pending removal anyways

**Comment by hekmon** [comment]
I know each endpoint is now DRM protected but please leave him for subtitle download at least :')
