### ISSUE TITLE
[huya] Add support for "moment" videos

### ISSUE THREAD

**Issue by LordLegend** [yt-dlp/yt-dlp#10679]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Germany

### Provide a description that is worded well enough to be understood

yt-dlp is unable to extract video information from Huya.com. When attempting to download a video, the extractor fails with the error message "Can not extract the room info". This occurs with both the stable and master versions of yt-dlp.

- The issue persists even after updating to the latest version (2024.08.06) and trying the master branch.
- The problem occurs with both regular and generic extractor methods.
- The video URL (https://www.huya.com/video/play/1002412640.html) is accessible in a web browser.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-v', 'https://www.huya.com/video/play/1002412640.html']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.08.06 from yt-dlp/yt-dlp [4d9231208]
[debug] Lazy loading extractors is disabled
[debug] Python 3.12.4 (CPython AMD64 64bit) - Windows-11-10.0.22631-SP0 (OpenSSL 3.0.13 30 Jan 2024)
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.07.04, mutagen-1.47.0, requests-2.32.3, sqlite3-3.45.3, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1830 extractors
[huya:live] Extracting URL: https://www.huya.com/video/play/1002412640.html
[huya:live] video: Downloading webpage
ERROR: [huya:live] video: Can not extract the room info
File "C:\Users\james\AppData\Local\Programs\Python\Python312\Lib\site-packages\yt_dlp\extractor\common.py", line 740, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\james\AppData\Local\Programs\Python\Python312\Lib\site-packages\yt_dlp\extractor\huya.py", line 60, in _real_extract
    raise ExtractorError('Can not extract the room info', expected=True)
```

**Comment by hugepower** [comment]
Currently, the [huya.py](https://github.com/yt-dlp/yt-dlp/blob/master/yt_dlp/extractor/huya.py) plugin only supports extracting data for live streaming rooms and does not have an extractor for downloading user-uploaded videos. As I am not yet familiar with `yt-dlp` syntax rules, I am unable to write such an extractor at the moment.

For instance, the video URL [https://www.huya.com/video/play/1002412640.html](https://www.huya.com/video/play/1002412640.html) has a video ID of **1002412640**, which can be used to get video information via the following API endpoint:

```
https://liveapi.huya.com/moment/getMomentContent?videoId=1002412640&uid=&_=1722989457292
```

In this API endpoint, **1722989457292** is a 13-digit timestamp used to ensure the data retrieved is up-to-date. With this information, we can write a dedicated video extractor.

**Comment by grqz** [comment]
so this should be a `site-request`.
url params `uid` and `_`(timestamp) aren't required.
formats are at `.data.moment.videoInfo.definitions` like this
```jsonc
[
  {
    "size": "5854080",
    "width": "1728",
    "height": "1080",
    "definition": "4000",
    "url": "http://al-vod.cdn.huya.com/leaf/1048585/1564376151/75143001/38885780_292ee5e45d941cf6e0915b5d595f09ce_264_1080_6_ai.mp4?bitrate=3218&client=106&definition=yuanhua&pid=1564376151&scene=vod&vid=1002412640&hyvid=1002412640&hyauid=1564376151&hyroomid=0&hyratio=3218&hyscence=vod&appid=66&domainid=25&srckey=NjZfMjVfMTAwMjQxMjY0MA%3D%3D&",
    "m3u8": "http://al-vod.cdn.huya.com/leaf/1048585/1564376151/75143001/38885780_292ee5e45d941cf6e0915b5d595f09ce_264_1080_6_ai.m3u8?bitrate=3218&client=106&definition=yuanhua&pid=1564376151&scene=vod&vid=1002412640&hyvid=1002412640&hyauid=1564376151&hyroomid=0&hyratio=3218&hyscence=vod&appid=66&domainid=25&srckey=NjZfMjVfMTAwMjQxMjY0MA%3D%3D&",
    "defName": "1080P"
  },
  {
    "size": "3066484",
    "width": "1152",
    "height": "720",
    "definition": "1300",
    "url": "http://al-vod.cdn.huya.com/leaf/1048585/1564376151/75143001/38885780_fa9a102d2f0481665828ceb87ecd44a8_264_720_6_ai.mp4?bitrate=1685&client=106&definition=1300&pid=1564376151&scene=vod&vid=1002412640&hyvid=1002412640&hyauid=1564376151&hyroomid=0&hyratio=1685&hyscence=vod&appid=66&domainid=25&srckey=NjZfMjVfMTAwMjQxMjY0MA%3D%3D&",
    "m3u8": "http://al-vod.cdn.huya.com/leaf/1048585/1564376151/75143001/38885780_fa9a102d2f0481665828ceb87ecd44a8_264_720_6_ai.m3u8?bitrate=1685&client=106&definition=1300&pid=1564376151&scene=vod&vid=1002412640&hyvid=1002412640&hyauid=1564376151&hyroomid=0&hyratio=1685&hyscence=vod&appid=66&domainid=25&srckey=NjZfMjVfMTAwMjQxMjY0MA%3D%3D&",
    "defName": "720P"
  },
  {
    "size": "823278",
    "width": "576",
    "height": "360",
    "definition": "350",
    "url": "http://al-vod.cdn.huya.com/leaf/1048585/1564376151/75143001/38885780_1c28ef0f3350c35936bb09f0cd45fc33_264_360_6_ai.mp4?bitrate=452&client=106&definition=350&pid=1564376151&scene=vod&vid=1002412640&hyvid=1002412640&hyauid=1564376151&hyroomid=0&hyratio=452&hyscence=vod&appid=66&domainid=25&srckey=NjZfMjVfMTAwMjQxMjY0MA%3D%3D&",
    "m3u8": "http://al-vod.cdn.huya.com/leaf/1048585/1564376151/75143001/38885780_1c28ef0f3350c35936bb09f0cd45fc33_264_360_6_ai.m3u8?bitrate=452&client=106&definition=350&pid=1564376151&scene=vod&vid=1002412640&hyvid=1002412640&hyauid=1564376151&hyroomid=0&hyratio=452&hyscence=vod&appid=66&domainid=25&srckey=NjZfMjVfMTAwMjQxMjY0MA%3D%3D&",
    "defName": "360P"
  }
]
```
