### ISSUE TITLE
[youtube] Missing metadata in non-web clients

### ISSUE THREAD

**Issue by coletdjnz** [yt-dlp/yt-dlp#1067]
## Checklist

- [ ] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2021.09.02**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] The provided URLs do not contain any DRM to the best of my knowledge
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar bug reports including closed ones
- [X] I've read bugs section in FAQ

## Verbose log

```
N/A

```

## Description

Note: this is **not** an issue when using the defaults.

Need to go through each of the clients and thoroughly check/update the metadata fallbacks. As well as document which ones are currently known to be missing.

Some of the missing metadata when running with `--extractor-args "youtube:player_client=android;player_skip=webpage"`:

- `upload_date`
- `automatic_captions`
- `uploader_id` 
- `uploader_url`
- `categories`

`upload_date` appears to be missing from non-web clients which a bit of a worry. Need to fix this as this mode is useful for avoiding rate limiting (skip webpage) and avoiding erroneous formats (skip web client, #502).

**Comment by pukkandan** [comment]
While it is ofc desirable to have all metadata in all clients, we don't *officially* support using the clients individually, and so I wouldn't consider this a bug

**Comment by coletdjnz** [comment]
`upload_date`, and some of the metadata, is contained within `microformats`, which is not present on other clients.

It appears the only way you can extract the upload date is through the text that is shown on the site ("Nov 11, 2021", "Premiered Feb 17, 2021", etc.) While this is possibly, we would need to take into account how to handle this with other languages (especially with #387).

I am surprised YouTube is still serving the date in a fixed format in `microformats`, when that doesn't appear to be used anywhere? So while this is not an issue right now, it *may* become an issue in the future.

Going to close this as it is not an issue as long as the officially supported clients can get the metadata.
