### ISSUE TITLE
TVer olympic live archive URLs not working

### ISSUE THREAD

**Issue by trollcop** [yt-dlp/yt-dlp#10673]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Japan

### Provide a description that is worded well enough to be understood

yt-dlp tver module does not support olympics 2024 /live/ (archive) version of the links, falling back to generic handler.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://tver.jp/olympic/paris2024/live/FBLMTEAM11------------SFNL000100--/']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.08.04.232814 from yt-dlp/yt-dlp-nightly-builds [e7d73bc45] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19044-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-109332-g45ab5307a6-20221201 (setts), ffprobe N-109332-g45ab5307a6-20221201, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.07.04, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1830 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.08.04.232814 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.08.04.232814 from yt-dlp/yt-dlp-nightly-builds)
[generic] Extracting URL: https://tver.jp/olympic/paris2024/live/FBLMTEAM11------------SFNL000100--/
[generic] FBLMTEAM11------------SFNL000100--: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] FBLMTEAM11------------SFNL000100--: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://tver.jp/olympic/paris2024/live/FBLMTEAM11------------SFNL000100--/
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1626, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1761, in __extract_info
  File "yt_dlp\extractor\common.py", line 740, in extract
  File "yt_dlp\extractor\generic.py", line 2526, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://tver.jp/olympic/paris2024/live/FBLMTEAM11------------SFNL000100--/
```

**Comment by pzhlkj6612** [comment]
> 2024年8月31日をもちましてパリオリンピック特設サイトは終了しました。
> ご愛顧、ありがとうございました。
> 5秒後に[TVerトップ](https://tver.jp/)に切り替わります。

The topic page for Olympic Games has been closed.

**Comment by trollcop** [comment]
🤡
