### ISSUE TITLE
yt-dlp -j URL is not showing youtube video category anymore?

### ISSUE THREAD

**Issue by benoon** [yt-dlp/yt-dlp#10705]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

JSON retrieved with yt-dlp always showed Youtube video category like Entertainment, Sport, Music, etc...
It seems like it is not avaiable in JSON anymore.
Anyone noticed and knows why?

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
Can you give an example with verbose output, please? I can't reproduce the issue:

```
$ yt-dlp --print categories YOelRv7fMxY
['Entertainment']
```

**Comment by benoon** [comment]
"categories": null

Just realized I was testing some mobile user-agents and for some of them categories were null.
It's all fine, sorry for the confusion.
