### ISSUE TITLE
Instagram extractor has hardcoded User-Agent

### ISSUE THREAD

**Issue by emv33** [yt-dlp/yt-dlp#10700]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Antigua and Barbuda

### Provide a description that is worded well enough to be understood

Instagram extractor has hardcoded user-agent:

https://github.com/yt-dlp/yt-dlp/blob/a065086640e888e8d58c615d52ed2f4f4e4c9d18/yt_dlp/extractor/instagram.py#L51

For some videos, Instagram sends different codecs depending on the user-agent. Since the user-agent is hardcoded to Chrome, some videos when downloaded using yt-dlp are only available in vp9 format.

Example video: https://www.instagram.com/reel/C86ZvEaqRmo/

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['https://www.instagram.com/reel/C86ZvEaqRmo/', '-F', '-vU']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.08.06 from yt-dlp/yt-dlp [4d9231208] (pip)
[debug] Python 3.10.12 (CPython x86_64 64bit) - Linux-5.15.146.1-microsoft-standard-WSL2-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.02.02, curl_cffi-0.7.1, mutagen-1.47.0, requests-2.32.2, secretstorage-3.3.1, sqlite3-3.37.2, urllib3-2.2.1, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1830 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.08.06 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.08.06 from yt-dlp/yt-dlp)
[Instagram] Extracting URL: https://www.instagram.com/reel/C86ZvEaqRmo/
[Instagram] C86ZvEaqRmo: Setting up session
WARNING: [Instagram] C86ZvEaqRmo: No csrf token set by Instagram API
[Instagram] C86ZvEaqRmo: Downloading JSON metadata
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[info] Available formats for C86ZvEaqRmo:
ID                      EXT RESOLUTION │   FILESIZE   TBR PROTO │ VCODEC          VBR ACODEC     ABR ASR MORE INFO
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
dash-1041414070747163ad m4a audio only │ ≈541.62KiB   94k https │ audio only          mp4a.40.5  94k 44k DASH audio, m4a_dash
dash-441905538611907vd  mp4 720x1280   │ ≈  3.54MiB  628k https │ vp09.00.31.08  628k video only         DASH video, mp4_dash
dash-1207869753575684v  mp4 720x1280   │ ≈  6.12MiB 1088k https │ vp09.00.31.08 1088k video only         DASH video, mp4_dash
dash-380296784627611v   mp4 720x1280   │ ≈  8.24MiB 1464k https │ vp09.00.31.08 1464k video only         DASH video, mp4_dash
dash-1603700283531109v  mp4 720x1280   │ ≈ 10.99MiB 1953k https │ vp09.00.31.08 1953k video only         DASH video, mp4_dash
dash-786928316879350v   mp4 720x1280   │ ≈ 15.46MiB 2748k https │ vp09.00.31.08 2748k video only         DASH video, mp4_dash
6                       mp4 750x1333   │                  https │ unknown             unknown
dash-1153802215672194v  mp4 1080x1920  │ ≈ 30.44MiB 5410k https │ vp09.00.40.08 5410k video only         DASH video, mp4_dash
```

**Comment by bashonly** [comment]
we can remove the hardcoded user-agent, but it will still be the user's responsibility to pass a different UA header with `--user-agent` to retrieve other codecs
