### ISSUE TITLE
sanitize_info command line option?

### ISSUE THREAD

**Issue by HPP8140** [yt-dlp/yt-dlp#10714]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Is there a `sanitize_info` command line option?

python3 -m yt_dlp --clean-info-json -j URL

Thanks

------------------------
Tip: If you are porting your code from youtube-dl to yt-dlp, one important point to look out for is that we do not guarantee the return value of YoutubeDL.extract_info to be json serializable, or even be a dictionary. It will be dictionary-like, but if you want to ensure it is a serializable dictionary, pass it through YoutubeDL.sanitize_info as shown in the [example below](https://github.com/yt-dlp/yt-dlp#extracting-information)

   # ℹ️ ydl.sanitize_info makes the info json-serializable
    print(json.dumps(ydl.sanitize_info(info)))

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
python3 -m yt_dlp --clean-info-json -j URL
```

**Comment by Grub4K** [comment]
`sanitize_info` will automatically be called to be able to export JSON values if you use `-j`/`-J`. The exported info json is valid json, so it HAD to have been called prior. What am I missing?

**Comment by HPP8140** [comment]
> `sanitize_info` will automatically be called to be able to export JSON values if you use `-j`/`-J`. The exported info json is valid json, so it HAD to have been called prior. What am I missing?

Okay, thank you for clarifying.

**Comment by HPP8140** [comment]
Question answered.
