### ISSUE TITLE
[Nitter] instances are not updated

### ISSUE THREAD

**Issue by 0n-s** [yt-dlp/yt-dlp#10715]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Norway

### Provide a description that is worded well enough to be understood

The list of Nitter instances has not been updated. Consequently, the generic extractor is used for currently working Nitter instances.

Maybe update the list of instances automatically?

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
$ yt-dlp -vU 'https://nitter.lucabased.xyz/miaaowing/status/1810426439792984165#m'
[debug] Command-line config: ['-vU', 'https://nitter.lucabased.xyz/miaaowing/status/1810426439792984165#m']
[debug] System config "/etc/yt-dlp/config": ['--color', 'auto-tty', '--xattrs', '--embed-metadata', '--embed-chapters', '--embed-info-json', '--embed-subs', '--embed-thumbnail', '--sponsorblock-mark', 'all', '--sub-langs', 'all', '-f', 'bv*+?ba/b', '--audio-multistreams', '--video-multistreams']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.08.06 from yt-dlp/yt-dlp [4d9231208] (pip)
[debug] Python 3.12.4 (CPython x86_64 64bit) - Linux-6.10.3-x86_64-with-glibc2.39 (OpenSSL 3.0.14 4 Jun 2024, glibc 2.39)
[debug] exe versions: ffmpeg 6.1.1 (setts), ffprobe 6.1.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.20.0, brotlicffi-1.1.0.0, certifi-2024.02.02, curl_cffi-0.7.1, mutagen-1.47.0, requests-2.32.3, secretstorage-3.3.3, sqlite3-3.46.0, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1830 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.08.06 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.08.06 from yt-dlp/yt-dlp)
[generic] Extracting URL: https://nitter.lucabased.xyz/miaaowing/status/1810426439792984165#m
[generic] 1810426439792984165#m: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] 1810426439792984165#m: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://nitter.lucabased.xyz/miaaowing/status/1810426439792984165#m
Traceback (most recent call last):
  File "/nix/store/b5wz4vi8paggp19ni0395yzrna3as10z-yt-dlp-2024.8.6/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 1626, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/b5wz4vi8paggp19ni0395yzrna3as10z-yt-dlp-2024.8.6/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 1761, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "/nix/store/b5wz4vi8paggp19ni0395yzrna3as10z-yt-dlp-2024.8.6/lib/python3.12/site-packages/yt_dlp/extractor/common.py", line 740, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/b5wz4vi8paggp19ni0395yzrna3as10z-yt-dlp-2024.8.6/lib/python3.12/site-packages/yt_dlp/extractor/generic.py", line 2526, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://nitter.lucabased.xyz/miaaowing/status/1810426439792984165#m
```

**Comment by bashonly** [comment]
Nitter is dying and their instance tracker specifically pleads with users to not use it for scraping. Just use the twitter extractor
