### ISSUE TITLE
Pick proxy from a file containing list of proxies.

### ISSUE THREAD

**Issue by barkoder** [yt-dlp/yt-dlp#10718]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Basically add a `--proxy-file proxylist.txt` option, where `proxylist.txt` contains LF/CRLF/CR separated list of proxies, just like in the `--proxy` format.

yt-dlp picks the first one in that list.

If it fails it picks the second one and so on.

If the proxy list has been exhausted, then throw whatever error.

Also add a `--proxy-random` option.

If `--proxy-random` is specified along with `--proxy-file` then instead of picking proxies sequentially from `proxylist.txt` , yt-dlp picks proxies randomly. However, yt-dlp must ensure not to randomly re-pick a previously picked proxy.

This would help with "Sign in to confirm you’re not a bot" and other errors.

I'm currently having to rotate proxies with a script, reinvoking yt-dlp over and over again. It would be great if yt-dlp was able to do this internally using 1 process.

Thanks!

Also, this issue is not related to #1191

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
I don't think verbose log is required. Let me know if you need it for some reason.
But I'm using nightly version 2024.08.06.232802
```

**Comment by bashonly** [comment]
This is out of scope for yt-dlp. It is a job for an external script/wrapper. The current proxy implementation wouldn't allow swapping of proxies within the same YoutubeDL instance anyways.
