### ISSUE TITLE
Rename `_internal` to `yt-dlp_internal` in yt-dlp_win.zip

### ISSUE THREAD

**Issue by barkoder** [yt-dlp/yt-dlp#10719]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

This isn't a bug. More of a convenience thing.

Could you please rename `_internal` to `yt-dlp_internal` while building `yt-dlp_win.zip` ?

I've reached my path limit and I have other directories beginning with underscore in the directory containing yt-dlp.exe .

I could create a directory symlink and move the `_internal` folder elsewhere, but.... could you please just rename it?

Feel free to tag this as "low-priority" (although the fix seems simple enough?)

Thanks!

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
I don't think verbose log is required. Let me know if you need it for some reason.
But I'm using nightly version 2024.08.06.232802
```

**Comment by bashonly** [comment]
No. The directory structure inside the zip file is decided by PyInstaller, not us

**Comment by bashonly** [comment]
Since changing this in our official builds would risk breaking compatibility for some users who depend on the current directory structure, this won't be changed on our end. But you could create your own PyInstaller `--onedir` build and specify the contents directory name:

https://pyinstaller.org/en/latest/usage.html#cmdoption-contents-directory

> `--contents-directory CONTENTS_DIRECTORY`
> 
>    For onedir builds only, specify the name of the directory in which all supporting files (i.e. everything except the executable itself) will be placed in. Use “.” to re-enable old onedir layout without contents directory.
