### ISSUE TITLE
[Crunchyroll] JSON Metadata - 403 Forbidden

### ISSUE THREAD

**Issue by KazeEnji** [yt-dlp/yt-dlp#10722]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United States

### Provide a description that is worded well enough to be understood

Receiving 403 Forbidden errors trying to download from Crunchyroll. I've attempted two different videos so far, both work in browser from same IP, neither work with yt-dlp, and both produce the same 403 Forbidden error while attempting to download the JSON metadata.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--username', 'PRIVATE', '--password', 'PRIVATE', '--sub-langs', 'en-US', '--remux-video', 'mkv', '--embed-subs', 'https://www.crunchyroll.com/watch/G6P8170J6/whisper-chant-prayer-awaken']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.08.06 from yt-dlp/yt-dlp [4d9231208] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22631-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-116599-g43cde54fc1-20240811 (setts)
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.07.04, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1830 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.08.06 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.08.06 from yt-dlp/yt-dlp)
[debug] Loading crunchyroll.<PRIVATE> from cache
[crunchyroll] Extracting URL: https://www.crunchyroll.com/watch/G6P8170J6/whisper-chant-prayer-awaken
[crunchyroll] Requesting token
[crunchyroll] G6P8170J6: Downloading object info JSON (cms)
ERROR: [crunchyroll] G6P8170J6: Unable to download JSON metadata: HTTP Error 403: Forbidden (caused by <HTTPError 403: Forbidden>)
  File "yt_dlp\extractor\common.py", line 740, in extract
  File "yt_dlp\extractor\crunchyroll.py", line 389, in _real_extract
  File "yt_dlp\extractor\crunchyroll.py", line 149, in _call_api
  File "yt_dlp\extractor\crunchyroll.py", line 140, in _call_base_api
  File "yt_dlp\extractor\common.py", line 1139, in download_content
  File "yt_dlp\extractor\common.py", line 1099, in download_handle
  File "yt_dlp\extractor\common.py", line 960, in _download_webpage_handle
  File "yt_dlp\extractor\common.py", line 909, in _request_webpage

  File "yt_dlp\extractor\common.py", line 896, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 4165, in urlopen
  File "yt_dlp\networking\common.py", line 117, in send
  File "yt_dlp\networking\_helper.py", line 208, in wrapper
  File "yt_dlp\networking\common.py", line 340, in send
  File "yt_dlp\networking\_requests.py", line 365, in _send
yt_dlp.networking.exceptions.HTTPError: HTTP Error 403: Forbidden
```

**Comment by rdamas** [comment]
See #10207, Crunchyroll content is completely protected by DRM now, nothing yt-dlp can do anymore. Your error comes from bot protection if I'm not mistaken, and should be circumvented by specifying a valid user agent.

**Comment by bashonly** [comment]
The solution would be to pass `--impersonate=""`. This extractor will not be worked on any further (and is pending removal) unless there is a non-DRM solution to #10207

**Comment by Tama47** [comment]
> (and is pending removal)

Is it being removed for sure? I would prefer the extractor not being removed, at least not until CR changes things to the point where downloading metadata also no longer works. But if it comes to it, could you notify me before it is being removed?

**Comment by bashonly** [comment]
@Tama47 it will most likely be removed eventually. Seems like a perfect candidate for an extractor plugin

**Comment by Tama47** [comment]
@bashonly 

> Seems like a perfect candidate for an extractor plugin

Can you explain in more detail how to use Crunchyroll.py as an extractor plugin? I would like to use the old extractor to download subtitles, as that still works prior to the removal of the extractor.

**Comment by seproDev** [comment]
@Tama47 See https://github.com/yt-dlp/yt-dlp?tab=readme-ov-file#developing-plugins and specifically [the sample plugin](https://github.com/yt-dlp/yt-dlp-sample-plugins).

You just copy the extractor and change the imports.

**Comment by rdamas** [comment]
Copy the now removed code into a location that yt-dlp scans for plugins. For me (MacOS) ~/Library/Python/3.12/lib/python/site-packages/yt_dlp_plugins/extractor/ works - other locations are mentioned in the documentation. You'll have to change the imports to import from yt_dlp., but that's obvious once you run yt-dlp.

**Comment by Tama47** [comment]
@seproDev @rdamas Thanks for the quick responses!

I believe I put crunchyroll.py extractor in the correct location as it is showing up in the verbose.

```
[debug] Plugin directories: ['/opt/homebrew/Cellar/yt-dlp/2025.1.26/libexec/lib/python3.13/site-packages/yt_dlp_plugins']
```

But I'm getting an error. Not sure if it's because I installed yt-dlp via Homebrew.

Full Path:
```
/opt/homebrew/Cellar/yt-dlp/2025.1.26/libexec/lib/python3.13/site-packages/yt_dlp
/opt/homebrew/Cellar/yt-dlp/2025.1.26/libexec/lib/python3.13/site-packages/yt_dlp_plugins/extractor/crunchyroll.py
```

Changed import from:
```
from .common import InfoExtractor
from ..networking import Request
from ..networking.exceptions import HTTPError
from ..utils import (
```
To
```
from yt_dlp.extractor.common import InfoExtractor
from yt_dlp.networking import Request
from yt_dlp.networking.exceptions import HTTPError
from yt_dlp.utils import (
```

Error:
```
Traceback (most recent call last):
  File "/opt/homebrew/bin/yt-dlp", line 8, in <module>
    sys.exit(main())
             ~~~~^^
  File "/opt/homebrew/Cellar/yt-dlp/2025.1.26/libexec/lib/python3.13/site-packages/yt_dlp/__init__.py", line 1095, in main
    _exit(*variadic(_real_main(argv)))
                    ~~~~~~~~~~^^^^^^
  File "/opt/homebrew/Cellar/yt-dlp/2025.1.26/libexec/lib/python3.13/site-packages/yt_dlp/__init__.py", line 1085, in _real_main
    return ydl.download(all_urls)
           ~~~~~~~~~~~~^^^^^^^^^^
  File "/opt/homebrew/Cellar/yt-dlp/2025.1.26/libexec/lib/python3.13/site-packages/yt_dlp/YoutubeDL.py", line 3618, in download
    self.__download_wrapper(self.extract_info)(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        url, force_generic_extractor=self.params.get('force_generic_extractor', False))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/yt-dlp/2025.1.26/libexec/lib/python3.13/site-packages/yt_dlp/YoutubeDL.py", line 3591, in wrapper
    res = func(*args, **kwargs)
  File "/opt/homebrew/Cellar/yt-dlp/2025.1.26/libexec/lib/python3.13/site-packages/yt_dlp/YoutubeDL.py", line 1612, in extract_info
    if not ie.suitable(url):
           ~~~~~~~~~~~^^^^^
  File "/opt/homebrew/Cellar/yt-dlp/2025.1.26/libexec/lib/python3.13/site-packages/yt_dlp/extractor/common.py", line 611, in suitable
    return cls._match_valid_url(url) is not None
           ~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/opt/homebrew/Cellar/yt-dlp/2025.1.26/libexec/lib/python3.13/site-packages/yt_dlp/extractor/common.py", line 603, in _match_valid_url
    cls._VALID_URL_RE = tuple(map(re.compile, variadic(cls._VALID_URL)))
                        ~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.13/3.13.2/Frameworks/Python.framework/Versions/3.13/lib/python3.13/re/__init__.py", line 289, in compile
    return _compile(pattern, flags)
  File "/opt/homebrew/Cellar/python@3.13/3.13.2/Frameworks/Python.framework/Versions/3.13/lib/python3.13/re/__init__.py", line 349, in _compile
    raise TypeError("first argument must be string or compiled pattern")
TypeError: first argument must be string or compiled pattern
```

**Comment by rdamas** [comment]
IIRC I've seen this error. Obviously yt-dlp complains about not finding the `_VALID_URL` in the extractor. 

Before the extractors were removed, they were imported via
```
from .crunchyroll import (
    CrunchyrollArtistIE,
    CrunchyrollBetaIE,
    CrunchyrollBetaShowIE,
    CrunchyrollMusicIE,
)
```

Now as a standalone module there is the class `CrunchyrollBaseIE` without a `_VALID_URL` attribute - the class is only used as a base class for the real extractor classes. If you rename the class (and uses of the class) to `_CrunchyrollBaseIE` and `CrunchyrollCmsBaseIE`to `_CrunchyrollCmsBaseIE` (I guess a class name without `IE` would work as well) you should be fine.

**Comment by Tama47** [comment]
Thank you, it worked!
