### ISSUE TITLE
Precondition check failed.

### ISSUE THREAD

**Issue by 3eshelon** [yt-dlp/yt-dlp#10725]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Hello. Server ubuntu 22.04 has this error.
Works good locally on mac.
Thank you beforehand

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
stderr: WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying ...
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying ...
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying ...
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] Unable to download API page: HTTP Error 400: Bad Request (caused by <HTTPError 400: 'Bad Request'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [youtube] nsig extraction failed: You may experience throttling for some formats
n = hzquX0IzDogNHTj5G ; player = https://www.youtube.com/s/player/28fd7348/player_ias.vflset/en_US/base.js
eyZsyCuOsuE: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/youtube.py", line 2517, in _decrypt_nsig
    self._player_cache[player_id] = self._extract_n_function(video_id, player_url)
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/youtube.py", line 2543, in _extract_n_function
    funcname = self._extract_n_function_name(jscode)
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/youtube.py", line 2526, in _extract_n_function_name
    nfunc, idx = self._search_regex(
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/common.py", line 1229, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
yt_dlp.utils.RegexNotFoundError: Unable to extract Initial JS player n function name; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
 (caused by RegexNotFoundError('Unable to extract Initial JS player n function name; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [youtube] nsig extraction failed: You may experience throttling for some formats
n = bXevzxOnMuGHhSNVF ; player = https://www.youtube.com/s/player/28fd7348/player_ias.vflset/en_US/base.js
eyZsyCuOsuE: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/youtube.py", line 2517, in _decrypt_nsig
    self._player_cache[player_id] = self._extract_n_function(video_id, player_url)
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/youtube.py", line 2543, in _extract_n_function
    funcname = self._extract_n_function_name(jscode)
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/youtube.py", line 2526, in _extract_n_function_name
    nfunc, idx = self._search_regex(
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/common.py", line 1229, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
yt_dlp.utils.RegexNotFoundError: Unable to extract Initial JS player n function name; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
 (caused by RegexNotFoundError('Unable to extract Initial JS player n function name; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
ERROR: [youtube] eyZsyCuOsuE: Unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

**Comment by seproDev** [comment]
You are on a very, very old version of yt-dlp. Please update to 2024.08.06 or later.

**Comment by 3eshelon** [comment]
Does this version available for ubuntu 22.04

Пн, 12 авг. 2024 г. в 09:38, sepro ***@***.***>:

**Comment by bashonly** [comment]
https://github.com/yt-dlp/yt-dlp/wiki/Installation

**Comment by 3eshelon** [comment]
Use APT

Reading package lists... Done Building dependency tree... Done Reading
state information... Done 24 packages can be upgraded. Run 'apt list
--upgradable' to see them. Reading package lists... Done Building
dependency tree... Done Reading state information... Done yt-dlp is already
the newest version (2022.04.08-1). 0 upgraded, 0 newly installed, 0 to
remove and 24 not upgraded.


Пн, 12 авг. 2024 г. в 09:51, bashonly ***@***.***>:

**Comment by bashonly** [comment]
Don't use apt, though.

`sudo apt remove yt-dlp`

and follow one of the other installation methods

**Comment by seproDev** [comment]
We do not maintain the packages in the Ubuntu repo. They are usually years out of date, which for a software like yt-dlp means pretty much all sites are broken.

**Comment by 3eshelon** [comment]
Thank you.
One more question
I use yt-dlp on my server. Is it possible to use it with VPN?
How does command looks like?

Пн, 12 авг. 2024 г. в 09:58, sepro ***@***.***>:

**Comment by seproDev** [comment]
With a VPN the command will look the same as all traffic (including the yt-dlp one) is routed through the VPN. If you are using a proxy instead you can specify so using the `--proxy` option.
