### ISSUE TITLE
[Broken]LinkedIn Learning - subtitles missing a new line

### ISSUE THREAD

**Issue by sneezydrag0n** [yt-dlp/yt-dlp#1072]
## Checklist

- [x ] I'm reporting a broken site support
- [x ] I've verified that I'm running yt-dlp version **2021.09.02**
- [x ] I've checked that all provided URLs are alive and playable in a browser
- [x ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x ] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
D:\Test>yt-dlp --newline --cookies cookies.txt -i -o "D:\Test\%(playlist_index)3d_%(title)s.mp4" -v --limit-rate 2M --min-sleep-interval 5 --max-sleep-interval 10 --write-sub "https://www.linkedin.com/learning/programming-foundations-fundamentals-3/the-fundamentals-of-programming"
[debug] Command-line config: ['--newline', '--cookies', 'cookies.txt', '-i', '-o', 'D:\\Test\\%(playlist_index)3d_%(title)s.mp4', '-v', '--limit-rate', '2M', '--min-sleep-interval', '5', '--max-sleep-interval', '10', '--write-sub', 'https://www.linkedin.com/learning/programming-foundations-fundamentals-3/the-fundamentals-of-programming']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] yt-dlp version 2021.09.02 (exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.17763-SP0
[debug] exe versions: ffmpeg 2021-09-16-git-8f92a1862a-full_build-www.gyan.dev
[debug] Optional libraries: mutagen, pycryptodome, sqlite, websockets
[debug] Proxy map: {}
[debug] [linkedin:learning] Extracting URL: https://www.linkedin.com/learning/programming-foundations-fundamentals-3/the-fundamentals-of-programming
[linkedin:learning] the-fundamentals-of-programming: Downloading 360p JSON metadata
[linkedin:learning] the-fundamentals-of-programming: Downloading 540p JSON metadata
[linkedin:learning] the-fundamentals-of-programming: Downloading 720p JSON metadata
[linkedin:learning] the-fundamentals-of-programming: Downloading m3u8 information
[debug] Sort order given by extractor: res, source_preference
[debug] Formats sorted by: hasvid, ie_pref, res, source, lang, quality, fps, vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 2230252: Downloading 1 format(s): progressive-720p
[debug] Invoking downloader on "https://dms.licdn.com/playlist/C4E0DAQHDUpArl1xv9Q/learning-original-video-vbr-720/0/1598695182397?e=1632603600&v=beta&t=U2wYVIiEVOx5OW8I0KSQ82IfrZJI828PTrPTozg5Fhs#.mp4"
[download] Sleeping 9.27 seconds ...
[download] Destination: D:\Test\NA_The fundamentals of programming.mp4
[download]   0.0% of 18.15MiB at 64.00KiB/s ETA 04:50
[download]   0.0% of 18.15MiB at 191.99KiB/s ETA 01:36
[download]   0.0% of 18.15MiB at 447.99KiB/s ETA 00:41
[download]   0.1% of 18.15MiB at 959.97KiB/s ETA 00:19
[download]   0.2% of 18.15MiB at 991.92KiB/s ETA 00:18
[download]   0.3% of 18.15MiB at  1.31MiB/s ETA 00:13
[download]   0.7% of 18.15MiB at  1.47MiB/s ETA 00:12
[download]   1.4% of 18.15MiB at  1.89MiB/s ETA 00:09
[download]   2.7% of 18.15MiB at  1.85MiB/s ETA 00:09
[download]   5.5% of 18.15MiB at  1.99MiB/s ETA 00:08
[download]  11.0% of 18.15MiB at  1.99MiB/s ETA 00:08
[download]  22.0% of 18.15MiB at  1.98MiB/s ETA 00:07
[download]  32.8% of 18.15MiB at  1.98MiB/s ETA 00:06
[download]  43.7% of 18.15MiB at  1.99MiB/s ETA 00:05
[download]  54.8% of 18.15MiB at  1.99MiB/s ETA 00:04
[download]  65.9% of 18.15MiB at  1.99MiB/s ETA 00:03
[download]  76.9% of 18.15MiB at  1.99MiB/s ETA 00:02
[download]  87.9% of 18.15MiB at  1.99MiB/s ETA 00:01
[download]  98.8% of 18.15MiB at  1.99MiB/s ETA 00:00
[download] 100.0% of 18.15MiB at  2.00MiB/s ETA 00:00
[download] 100% of 18.15MiB in 00:09

```

## Description

I'm was trying to download subtitles along with videos from the linkedin learning video course.
But only video clips are downloaded. No subtitles.
Subtitles are available and they can be turned _ON_ while watching videos directly on the linkedin learning website (same way like you turn them _ON_ by pressing '**CC**' on youtube).

The link for subtitles can be found if you check html source of that linkedin page ( by pressing CTRL+U) and look for '**data-captions-url**' which is located inside **<video>** tag and it has a link for a subtitle.
So in the source file, it looks like this:
`<video class="share-native-video__node video-js" data-sources="[{&quot;src&quot;:&quot;https://dms.licdn.com/playlist/....." data-poster-url="https://media-exp1.licdn.com....." data-captions-url="https://www.linkedin.com.....`

**Comment by Ashish0804** [comment]
IDK if this a region thing or what but i don't see the captions in the webpage.
The extractor doesn't even use webpages so it would be better to find captions from json.

**Comment by sneezydrag0n** [comment]
I don't know. I think it has nothing to do with region.

For instance, go to this link: https://www.linkedin.com/learning/programming-foundations-fundamentals-3
Press the '**Introduction**' drop-down and select first video '**The Fundamentals of Programmng**'.
When page loads, check the source (CTRL+U)
Line 493 of the source starts with `<video autoplay class="share-native-video__node video-js" data-s.....`
In the same line look for: `data-captions-url="https://www.linkedin.com...`

Here are the screenshots:
https://i.imgur.com/uiip8vk.png
https://i.imgur.com/qsI4OaF.png

^ that `data-captions-url ` holds the link to subtitle file, which when link is pasted in the browser, download a file in ***.vtt** file format.

**Comment by pukkandan** [comment]
I can see the subs in browser. But as Ashish said, we should try to fetch it from the API if possible

**Comment by sneezydrag0n** [comment]
Thanks @Ashish0804 for looking into this issue and for trying to fix it.

I checked it and it does download a subtitile. BUT there is a small 'glitch'.
When file is downloaded, the extension is *.srt (which is also what I like to see), while original file being a *.vtt file (which is the same thing), BUT...

When I tried to play the file with subtitle which was downlaoded with new 'fix', there was ony one messy 'text' over the video and then no subtitle text at all. Here is a screenshot:

https://i.imgur.com/jGLReCE.png

^ After that, I manualy downloaded a subtitle in *.vtt format by checking source code of the website and compared the content of both subtitles. Here on next screenshot you can see the difference (left is the sub downloaded by the fix, on the right is the *.vtt sub downloaded manualy from the browser)

https://i.imgur.com/Zec0mdi.png

In the subtitle downloaded by the fixed linkedin.py, we can see that...(compared to the original *.vtt from the site) there is no space (or 'empty line') after the subtitle text. Or if you will, 'before the new line of subtitle text begins'.

And... since the 'original' (on the right) sub has some 'WEBVTT' text at the begining, and the 'fixed' one doesn't, I would say, that there was some coding involved into 'cleaning' (adjusting) the subtitle file.

I tried to just add an empty line after every line of spoken words, and that 'fixed' it.

So instead having this:

`1`
`00:00:00,070 --> 00:00:04,019`
`- Now more than ever, you hear about the importance`
`2`
`00:00:04,019 --> 00:00:06,040`
`of STEM education and the need`


...it should be:
`1`
`00:00:00,070 --> 00:00:04,019`
`- Now more than ever, you hear about the importance`
<---------------   an empty line here ---------------------->
`2`
`00:00:04,019 --> 00:00:06,040`
`of STEM education and the need`

Could you check and re-fix the fixed extractor file, please?

**Comment by Ashish0804** [comment]
OOOF
I didn't see this bug bcoz it works for me on potplayer.
I'll push a fix later today.
