### ISSUE TITLE
[nicovideo.jp] Extracting the audio from nicovideos in the "aac" or "m4a" file format causes the length to be missing, but NOT "alac"

### ISSUE THREAD

**Issue by Synth-ix** [yt-dlp/yt-dlp#10724]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Japan

### Provide a description that is worded well enough to be understood

# Explaining the problem (& further testing/documentation):
As of 2024/08/11, on Windows 10 Pro 22H2, upon using `"yt-dlp (-x or --extract-audio) (nicovideo.jp link)"` or `"yt-dlp (-x or --extract-audio) --audio-format (best, aac, or m4a) (nicovideo.jp link)"`, the resulting aac / m4a file finishes downloading with no defined audio length. Right-clicking on the file and going to Properties -> Details, the "Length" value is entirely blank. 

### To answer any more possible questions before and/or after looking at the verbose output:
- I do not have a nicovideo.jp account, I use the site as a guest.
- The ffmpeg/ffprode dependency build I'm using is `autobuild-2024-08-10-14-15` from Windows EXE builds by BtbN.
- I've tested downloading aac / m4a files from nicovideos on the latest stable, nightly, and master versions as of 2024/08/11.
(I'm entirely up-to-date on my yt-dlp releases)
- I've tested downloading aac / m4a files from nicovideos with Japanese characters (of which are unsupported in Windows 10 Command Prompt) and with standard English characters, **the length still remained missing.**
(Whatever unicode characters are used in the nicovideo title doesn't matter, it isn't what's causing this problem)
- I've tested downloading aac / m4a files from nicovideos with links that have "sm" in them (SMILEVIDEO videos, "sm" can be used in the link of almost any nicovideo) and nicovideos with links that have "/nm" in them (nicovideos posted with official Nico Nico Video editing software; such as Nico Nico Movie Maker), **the length still remained missing.**
(Whatever nicovideo.jp video link you download doesn't matter [including the example link in the verbose output], it isn't what's causing this problem)
- **I've tested downloading most of the other supported audio files from nicovideos (flac, mp3, opus, vorbis, & wav), _and the length wasn't missing in those audio file formats._**

m4a is the only audio format with this missing length issue, and extracting the audio with yt-dlp with no specified audio format, best audio format, m4a audio format, aac audio format, and alac audio format downloads an .m4a file into my File Explorer.

However, upon using `alac` as an audio format parameter, _**the length wasn't missing in the resulting m4a file** that was downloaded into my File Explorer._
### So, why does `"yt-dlp (-x or --extract-audio) --audio-format alac (nicovideo.jp link)"` NOT have this issue?
i have no idea.
im gonna be so honest with you, i don't know why this works.

## Wait, there's a resource out there that doesn't have this problem to begin with?
Upon testing downloading nicovideos & their audios with other resources, I've found that using the online _nicozon downloader_ ALWAYS provides m4a files with valid length values.
**(Refer to [this video](https://www.youtube.com/watch?v=sztJ8cO4mak) as a brief tutorial on how to use the nicozon downloader through https://www.nicozon.net/)**

### THE TUTORIAL VIDEO ABOVE IS SLIGHTLY OUTDATED, READ BELOW:
The "nicozon downloader" tab now has this look, providing BETA (but still functional) bookmarklets that allow you to download nicovideo components in the same way shown in the video with these options (from top to bottom):
- **"BETA版ブックマークレット"**
_("BETA bookmarklet", downloads video in highest available quality)_
- **"BETA版音声のみブックマークレット"**
_("BETA version audio only bookmarklet", downloads audio in highest available quality)_
- **"BETA版上限720pブックマークレット"**
_("BETA version maximum 720p bookmarklet", downloads video in 720p at the most)_
- **"BETA版上限480pブックマークレット"**
_("BETA version maximum 480p bookmarklet", downloads video in 480p at the most)_
- **"BETA版上限360pブックマークレット"**
_("BETA version maximum 360p bookmarklet", downloads video in 360p at the most)_
![image](https://github.com/user-attachments/assets/020ea134-03cd-4a40-baf0-b5dc8d1b0f76)

Upon bookmarking the download option of your choice using any of the given bookmarklets and pressing "このリンクをクリックした後のページでブックマークレットを実行した後に動画を保存できます", you'll be met with a blank, white page holding the data of the video you ran with the nicozon downloader.
A few seconds after clicking the bookmark on that ext.nicovideo.jp page, you'll be met with a display of an automatic ETA text script for your download. (the example below is for the "BETA版ブックマークレット" ["BETA bookmarklet"] option)
![image](https://github.com/user-attachments/assets/c1465d6c-ed97-4a4a-b827-92ae5aa84c3d)
Once it finishes, the files will finish downloading to wherever your browser is set to put any downloaded files in.

**And for the "BETA版音声のみブックマークレット" ("BETA version audio only bookmarklet") option, it will always provide an m4a file with a valid/working length value.**
### So, why was it worth mentioning nicozon.net at all?
Because maybe you, a developer of yt-dlp hoping to fix this bug, or programmer willing to create their own build bugfixing this problem, could take a look into the coding & function of this website to see how it manages downloading nicovideos because of the fact it doesn't encounter this issue that yt-dlp does.
Perhaps this could be the a resource to look into for solving this problem? I don't know, this is just an idea on looking into how this bug could _potentially_ be fixed.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

extracting audio with no specified format:
```shell

[debug] Command-line config: ['-vU', '-x', 'https://www.nicovideo.jp/watch/nm10550338']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.08.06.232802 from yt-dlp/yt-dlp-nightly-builds [a06508664] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-116557-g1b8d95da3a-20240810 (setts), ffprobe N-116557-g1b8d95da3a-20240810
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.07.04, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1830 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.08.06.232802 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.08.06.232802 from yt-dlp/yt-dlp-nightly-builds)
[niconico] Extracting URL: https://www.nicovideo.jp/watch/nm10550338
[niconico] nm10550338: Downloading webpage
[niconico] nm10550338: Downloading JSON metadata
[niconico] nm10550338: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[info] nm10550338: Downloading 1 format(s): audio-aac-192kbps
[debug] Invoking hlsnative downloader on "https://delivery.domand.nicovideo.jp/hlsbid/65f67dc39d5fe55715fab660/playlists/media/audio-aac-192kbps.m3u8?session=678371f1cb600f9fe20fcfa011073dd38ab3aae89d6a066a0000000066bab3586fe92f41c80f8e42&Expires=1723511640&Signature=PUsdC61ASLMJU8J~-zzdhYm6E~SraHI7DANhN706A1yXrscz6PelQc1W0zcvBeQkKdzcQXJDZt~SQrrmUjzRJaYjfM6N-gM8SAl8X2-bW3qn0a~~Nmozt7wRx5pDszVMqgYxyvMvT6Z8bMq2giZErHVdUkTUfi84XtjkFqKWsSpjY3lO4tkCSbuKp-iBYSx1WM479z5JS9pF00IVG4urkXMe6TkGglw0QX6qQEN-2OZdGZgn1ZSi5Xwk5j5B9scjm~wk6LOVIPstzXTSk4aot3vZ4ffAhGzgkjK~igMQO0sW6OybA1mWCQ~d8qTvl9eIEJD3-XwotI25Av9nSZGimQ__&Key-Pair-Id=K11RB80NFXU134"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 24
[download] Destination: 【マリオペイント】お猿のおもちゃのBGMをリミックスしてみた [nm10550338].m4a
[debug] File locking is not supported. Proceeding without locking
[download] 100% of    3.28MiB in 00:00:03 at 890.36KiB/s
[debug] ffprobe command line: ffprobe -hide_banner -show_format -show_streams -print_format json "file:【マリオペイント 】お猿のおもちゃのBGMをリミックスしてみた [nm10550338].m4a"
[ExtractAudio] Not converting audio 【マリオペイント】お猿のおもちゃのBGMをリミックスしてみた [nm10550338].m4a; the file is already in a common audio format
```

extracting audio with alac:
```
[debug] Command-line config: ['-vU', '-x', '--audio-format', 'alac', 'https://www.nicovideo.jp/watch/nm10550338']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.08.06.232802 from yt-dlp/yt-dlp-nightly-builds [a06508664] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-116557-g1b8d95da3a-20240810 (setts), ffprobe N-116557-g1b8d95da3a-20240810
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.07.04, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1830 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.08.06.232802 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.08.06.232802 from yt-dlp/yt-dlp-nightly-builds)
[niconico] Extracting URL: https://www.nicovideo.jp/watch/nm10550338
[niconico] nm10550338: Downloading webpage
[niconico] nm10550338: Downloading JSON metadata
[niconico] nm10550338: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[info] nm10550338: Downloading 1 format(s): audio-aac-192kbps
[debug] Invoking hlsnative downloader on "https://delivery.domand.nicovideo.jp/hlsbid/65f67dc39d5fe55715fab660/playlists/media/audio-aac-192kbps.m3u8?session=bf04ccb22ed1b5fc1bab8560418f2ca98ab3aae89d6a066a0000000066bac7940ba683f1cb722cb4&Expires=1723516820&Signature=nUG~Yngy6948ER~Be6RTmkpHN55oMm0XF6WYDvSa9NOqNGJYlp7gtwfjMXVkygfegYBG4U8QtFVvOoizgsKgnqBkwUThy-84790olZT8PlApCsgSeNM~61KW5tlqhwepvikIpdhZxkoUn4XhmOBr7QGw4YmSewf49dqTQfZySf4hf2BJyBtuVYYg-XTKE5iOgPClo7akvDj~2De9Hudpm2QXgvroI-qS0VSXnsx5SZ2bsxckj1drkYcW30fLD4VETe60meorqwQY2TDLr1bQN8dEhXJikdVVCWsC6MflFDJeCmne9SJL~xGpGyWqZAZcdWnWdl2ly4mUK93E8MuXxQ__&Key-Pair-Id=K11RB80NFXU134"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 24
[download] Destination: 【マリオペイント】お猿のおもちゃのBGMをリミックスしてみた [nm10550338].m4a
[debug] File locking is not supported. Proceeding without locking
[download] 100% of    3.28MiB in 00:00:02 at 1.50MiB/s
[debug] ffprobe command line: ffprobe -hide_banner -show_format -show_streams -print_format json "file:【マリオペイント 】お猿のおもちゃのBGMをリミックスしてみた [nm10550338].m4a"
[debug] ffmpeg command line: ffprobe -show_streams "file:【マリオペイント】お猿のおもちゃのBGMをリミックスしてみた [nm10550338].m4a"
[ExtractAudio] Destination: 【マリオペイント】お猿のおもちゃのBGMをリミックスしてみた [nm10550338].m4a
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i "file:【マリオペイント】お猿のおもちゃのBGMをリミックス してみた [nm10550338].m4a" -vn -movflags +faststart "file:【マリオペイント】お猿のおもちゃのBGMをリミックスしてみた [nm10550338].temp.m4a"
Deleting original file 【マリオペイント】お猿のおもちゃのBGMをリミックスしてみた [nm10550338].orig.m4a (pass -k to keep)
```
```

**Comment by bashonly** [comment]
from the m4a log:

> ```
> [ExtractAudio] Not converting audio 【マリオペイント】お猿のおもちゃのBGMをリミックスしてみた [nm10550338].m4a; the file is already in a common audio format
> ```

Here, the only thing that `-x` is doing is implicitly selecting the `bestaudio` format. yt-dlp detects that the download is already in an audio-only container (m4a) and does not extract or remux anything. So you end up with the raw product of the m3u8 playlist; the native HLS downloader just concatenates all of the AAC audio stream segments. The resulting container is not playing nice with Windows' metadata parsing.

When you pass `--audio-format alac` (or any format other than `m4a` or `aac`), then yt-dlp will remux or re-encode the download, which effectively fixes the issue.

Possible solutions/workarounds for getting a fixed m4a container:

1. use `-x -f bv+ba/b` to download the video and the audio, merge them, and then extract the audio
2. use `-x --parse-metadata " m4a_dash: %(container)s"` to download only audio and force remuxing after download
3. use ffmpeg as the downloader: `--downloader ffmpeg`
4. manually remux with ffmpeg after downloading, e.g.: `ffmpeg -i "input.m4a" -c copy "output.m4a"`

**Comment by Synth-ix** [comment]
## Those solutions worked just perfectly!
Thank you for the explanation & inputs on fixing the issue, seriously. ♥

**Comment by bashonly** [comment]
Looking at the extractor code though, I'm noticing we manually set the audio format extension to `m4a`. I'm wondering if this should be fixed on the extractor level like this:
```diff
diff --git a/yt_dlp/extractor/niconico.py b/yt_dlp/extractor/niconico.py
index 179e7a9b1..e06740d62 100644
--- a/yt_dlp/extractor/niconico.py
+++ b/yt_dlp/extractor/niconico.py
@@ -420,7 +420,7 @@ def _yield_dms_formats(self, api_data, video_id):
                 'x-request-with': 'https://www.nicovideo.jp',
             })['data']['contentUrl']
         # Getting all audio formats results in duplicate video formats which we filter out later
-        dms_fmts = self._extract_m3u8_formats(dms_m3u8_url, video_id)
+        dms_fmts = self._extract_m3u8_formats(dms_m3u8_url, video_id, 'mp4')
 
         # m3u8 extraction does not provide audio bitrates, so extract from the API data and fix
         for audio_fmt in traverse_obj(dms_fmts, lambda _, v: v['vcodec'] == 'none'):
@@ -432,7 +432,6 @@ def _yield_dms_formats(self, api_data, video_id):
                     'asr': ('samplingRate', {int_or_none}),
                 }), get_all=False),
                 'acodec': 'aac',
-                'ext': 'm4a',
             }
 
         # Sort before removing dupes to keep the format dicts with the lowest tbr
```

**Comment by Synth-ix** [comment]
Definitely shoot me a reply if/when you'd go about releasing a build including this potential patch, I'd be willing to test it out before release if for whatever reason that'd be needed as well.
Glad I was able to bring this to light & you're able to find a possible way to go about troubleshooting this!

**Comment by CXwudi** [comment]
Niconico is known to only have MP4 format (according to [this](https://qa.nicovideo.jp/faq/show/5685) and [this](https://qa.nicovideo.jp/faq/show/21908) Q&A pages from the niconico official site), that's why it was hard-coded to `m4a`.

**Comment by bashonly** [comment]
> Niconico is known to only have MP4 format (according to [this](https://qa.nicovideo.jp/faq/show/5685) and [this](https://qa.nicovideo.jp/faq/show/21908) Q&A pages from the niconico official site), that's why it was hard-coded to `m4a`.

Right, but in those cases that is typically handled by passing `mp4` as the `ext` param to `_extract_m3u8_formats()`, which the above patch does
