### ISSUE TITLE
Loom Missing Audio

### ISSUE THREAD

**Issue by MichaelKuz** [yt-dlp/yt-dlp#10737]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [x] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United States

### Provide a description that is worded well enough to be understood

When I use yt-dlp to download a video from Loom, I get a video file with no audio.

I found this comment indicating that at least one other user wasn't getting audio from the original pull request back in March: https://github.com/yt-dlp/yt-dlp/pull/8686#issuecomment-2022033227

I'm providing the verbose log below as I can't find evidence that bashonly's request for a new issue with log was ever completed. 

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.loom.com/share/5f98127a5b1a4a9790303d0585380570']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.08.12.232840 from yt-dlp/yt-dlp-nightly-builds [49f3741a8] (pip)
[debug] Python 3.9.1 (CPython arm64 64bit) - macOS-13.6.7-arm64-arm-64bit (OpenSSL 3.3.1 4 Jun 2024)
[debug] exe versions: ffmpeg 7.0.1 (setts), ffprobe 7.0.1
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.07.22, mutagen-1.47.0, requests-2.32.3, sqlite3-3.39.5, urllib3-1.26.18, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1830 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.08.12.232840 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.08.12.232840 from yt-dlp/yt-dlp-nightly-builds)
[loom] Extracting URL: https://www.loom.com/share/5f98127a5b1a4a9790303d0585380570
[loom] 5f98127a5b1a4a9790303d0585380570: Downloading GraphQL metadata JSON
[loom] 5f98127a5b1a4a9790303d0585380570: Downloading GraphQL JSON
[loom] 5f98127a5b1a4a9790303d0585380570: Downloading raw-url JSON
[loom] 5f98127a5b1a4a9790303d0585380570: Downloading m3u8 information
[loom] 5f98127a5b1a4a9790303d0585380570: Downloading transcoded-url JSON
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 5f98127a5b1a4a9790303d0585380570: Downloading 1 format(s): hls-raw-1500
[debug] Invoking hlsnative downloader on "https://luna.loom.com/id/5f98127a5b1a4a9790303d0585380570/rev/618f4a97efa59788f9b1cb632e7074284548a81955e7e3c9384416499387396c0/resource/hls/mediaplaylist-video-bitrate1500.m3u8?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9sdW5hLmxvb20uY29tL2lkLzVmOTgxMjdhNWIxYTRhOTc5MDMwM2QwNTg1MzgwNTcwL3Jldi82MThmNGE5N2VmYTU5Nzg4ZjliMWNiNjMyZTcwNzQyODQ1NDhhODE5NTVlN2UzYzkzODQ0MTY0OTkzODczOTZjMC9yZXNvdXJjZS8qIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNzIzNjY5MTc2fX19XX0_&Signature=bVtX-OOHTimdodvm4Bi5uS%7EySxkTp3Grp7zLqfuhEv43f02yGYJfkMWBIImnmV33%7EmhnT0uLcCROO8WGlq2HRPth%7EVi2Q%7E%7EanqpQ8TgmB6I0bxgho0l90pMGJy9otJkR0n-KmUfSuRmx3vtz5qLNU3O-p9GjbHuZPPvMWnWwktq9ytaoHnYxSsUUauBoiBzaQyxaIisBEWEAKu-AVXuW4CQ4cNT4LxB4efwnAus06rR1dNmrRd2uvUH5DImIIP-vON0waUtDRsPucpU-jmLGZSmuOnDPcxfwPppcuqCp8b4w-yM5Agu9ZS0kYjSsSHjWCCr5g3fdEGc9pzeP0ugXNw__&Key-Pair-Id=APKAJQIC5BGSW7XXK7FQ"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 288
[download] Destination: How to start using Photo AI [5f98127a5b1a4a9790303d0585380570].mp4
[download] 100% of  142.71MiB in 00:03:02 at 800.03KiB/s
[debug] ffprobe command line: ffprobe -hide_banner -show_format -show_streams -print_format json 'file:How to start using Photo AI [5f98127a5b1a4a9790303d0585380570].mp4'
[debug] ffmpeg command line: ffprobe -show_streams 'file:How to start using Photo AI [5f98127a5b1a4a9790303d0585380570].mp4'
[FixupM3u8] Fixing MPEG-TS in MP4 container of "How to start using Photo AI [5f98127a5b1a4a9790303d0585380570].mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:How to start using Photo AI [5f98127a5b1a4a9790303d0585380570].mp4' -map 0 -dn -ignore_unknown -c copy -f mp4 -movflags +faststart 'file:How to start using Photo AI [5f98127a5b1a4a9790303d0585380570].temp.mp4'
```

**Comment by kclauhk** [comment]
The transcoded format has audio.
You can download it with `-f http-transcoded`

**Comment by MichaelKuz** [comment]
That worked, thanks very much. 

(I'm not totally sure whether or not to leave this issue open, so I'm going to leave it as-is just in case there's further work to be done)

**Comment by bashonly** [comment]
It can be left open. The m3u8 parsing is broken, and iirc `http-transcoded` is an inferior format compared to the m3u8 formats
