### ISSUE TITLE
Some bilibili festival linked video unable to download (fallback to generic extractor)

### ISSUE THREAD

**Issue by matsumotokenji** [yt-dlp/yt-dlp#10739]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Malaysia

### Provide a description that is worded well enough to be understood

yt-dlp.exe --cookies cookies.txt https://www.bilibili.com/video/BV1tr4y1f7p2/
or
yt-dlp.exe https://www.bilibili.com/video/BV1tr4y1f7p2/

error output as below

[BiliBili] Extracting URL: https://www.bilibili.com/video/BV1tr4y1f7p2/
[BiliBili] 1tr4y1f7p2: Downloading webpage
[generic] Extracting URL: https://www.bilibili.com/festival/bh3-7th?bvid=BV1tr4y1f7p2&
[generic] bh3-7th?bvid=BV1tr4y1f7p2&: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] bh3-7th?bvid=BV1tr4y1f7p2&: Extracting information
ERROR: Unsupported URL: https://www.bilibili.com/festival/bh3-7th?bvid=BV1tr4y1f7p2&

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp.exe https://www.bilibili.com/video/BV1tr4y1f7p2/ -vU
[debug] Command-line config: ['https://www.bilibili.com/video/BV1tr4y1f7p2/', '-vU']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.08.12.232840 from yt-dlp/yt-dlp-nightly-builds [49f3741a8] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22631-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 2023-12-21-git-1e42a48e37-full_build-www.gyan.dev (setts), ffprobe 2023-12-21-git-1e42a48e37-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.07.04, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1830 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.08.12.232840 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.08.12.232840 from yt-dlp/yt-dlp-nightly-builds)
[BiliBili] Extracting URL: https://www.bilibili.com/video/BV1tr4y1f7p2/
[BiliBili] 1tr4y1f7p2: Downloading webpage
[generic] Extracting URL: https://www.bilibili.com/festival/bh3-7th?bvid=BV1tr4y1f7p2&
[generic] bh3-7th?bvid=BV1tr4y1f7p2&: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] bh3-7th?bvid=BV1tr4y1f7p2&: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://www.bilibili.com/festival/bh3-7th?bvid=BV1tr4y1f7p2&
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1626, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1761, in __extract_info
  File "yt_dlp\extractor\common.py", line 740, in extract
  File "yt_dlp\extractor\generic.py", line 2526, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.bilibili.com/festival/bh3-7th?bvid=BV1tr4y1f7p2&
```

**Comment by bashonly** [comment]
the URL regex pattern needs to be relaxed a bit:
```diff
diff --git a/yt_dlp/extractor/bilibili.py b/yt_dlp/extractor/bilibili.py
index a84b7a6f7..809e0c215 100644
--- a/yt_dlp/extractor/bilibili.py
+++ b/yt_dlp/extractor/bilibili.py
@@ -298,7 +298,7 @@ def _get_interactive_entries(self, video_id, cid, metainfo, headers=None):
 
 
 class BiliBiliIE(BilibiliBaseIE):
-    _VALID_URL = r'https?://(?:www\.)?bilibili\.com/(?:video/|festival/\w+\?(?:[^#]*&)?bvid=)[aAbB][vV](?P<id>[^/?#&]+)'
+    _VALID_URL = r'https?://(?:www\.)?bilibili\.com/(?:video/|festival/[^/?#]+\?(?:[^#]*&)?bvid=)[aAbB][vV](?P<id>[^/?#&]+)'
 
     _TESTS = [{
         'url': 'https://www.bilibili.com/video/BV13x41117TL',
```
