### ISSUE TITLE
Question: Does the YouTube videoquality gets better after time, or are there hidden quality-options? 

### ISSUE THREAD

**Issue by sebi-berlin** [yt-dlp/yt-dlp#10732]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Hey, I downloaded this video pretty right after its release:

https://www.youtube.com/watch?v=GNCNR2l-7QI

Today I downloaded it again and the size is nearly the double, although it is both VP9. The downloaded video looks like YouTube Premium, but there is no such option that I can see with the user-interface. 

So my question is: Does the YouTube videoquality gets better after time, or are there hidden quality-options? 

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by sebi-berlin** [comment]
Additional question would be: Is there a command to only download the video, if yt-dlp finds a premium bitrate? Would like to use this, to update my collection.

**Comment by DTrombett** [comment]
yt-dlp already chooses the best quality video and merges it with the best quality audio. This is not possible without ffmpeg so make sure you have it installed.
If you want a video-only file use `-f bv` but note that it will be the same that is used when downloading both audio and video so you won't get any quality upgrade.
Also, if you want to check which format is chosen and its description (like Premium) you can use `-F`. The last format listed is the one that will be chosen for the video stream, while the last one with `audio only` will be the format for the audio (if the video format doesn't already include audio)

**Comment by bashonly** [comment]
> Does the YouTube videoquality gets better after time

Immediately after a video is uploaded, not all of the transcoding may have completed yet. The m3u8 formats in particular take at least a couple hours to be available, and this includes format 616 (the "higher bitrate" 1080p format). If you care about getting the best quality, I would recommend waiting until the video has been available for at least a few hours (or up to 24 hours) before downloading it.

> Is there a command to only download the video, if yt-dlp finds a premium bitrate? 

`616` is the format ID of the "higher bitrate" 1080p format. So you could use `-f 616+ba`. But for videos with resolutions greater than 1080p, format 616 is not available (and you may want the 4K video format instead, etc). So you could use `-f "(bv[height>1080]/616)+ba"` in that case. However, this would result in a "requested format not available" error for videos where the max resolution is less than 1080p, or for 1080p-max videos where youtube doesn't provide format 616.

**Comment by gamer191** [comment]
> Additional question would be: Is there a command to only download the video, if yt-dlp finds a premium bitrate? Would like to use this, to update my collection.

`--no-check-formats` will prevent yt-dlp falling back to the next format if the premium formats aren't yet available
