### ISSUE TITLE
ERROR: [hotstar] 1700042336: Unable to download JSON metadata: HTTP Error 503: Service Unavailable (caused by <HTTPError 503: Service Unavailable>)

### ISSUE THREAD

**Issue by ETapk** [yt-dlp/yt-dlp#10738]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Provide a description that is worded well enough to be understood

Site Url : https://www.hotstar.com/in/shows/tumi-asheypashey-thakle/1260156248/deb-parvatis-love-wins/1700042336/watch

ERROR: [hotstar] 1700042336: Unable to download JSON metadata: HTTP Error 503: Service Unavailable (caused by <HTTPError 503: Service Unavailable>)

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
C:\Users\moder\Downloads\Programs>yt-dlp -vU -F https://www.hotstar.com/in/shows/tumi-asheypashey-thakle/1260156248/deb-parvatis-love-wins/1700042336/watch
[debug] Command-line config: ['-vU', '-F', 'https://www.hotstar.com/in/shows/tumi-asheypashey-thakle/1260156248/deb-parvatis-love-wins/1700042336/watch']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.08.06 from yt-dlp/yt-dlp [4d9231208] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22631-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 2024-02-01-git-94422871fc-essentials_build-www.gyan.dev (setts), ffprobe 2024-02-01-git-94422871fc-essentials_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.07.04, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1830 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.08.06 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.08.06 from yt-dlp/yt-dlp)
[hotstar] Extracting URL: https://www.hotstar.com/in/shows/tumi-asheypashey-thakle/1260156248/deb-parvatis-love-wins/1700042336/watch
[hotstar] 1700042336: Downloading JSON metadata
[hotstar] 1700042336: Downloading webpage
[hotstar] 1700042336: Downloading token
ERROR: [hotstar] 1700042336: Unable to download JSON metadata: HTTP Error 503: Service Unavailable (caused by <HTTPError 503: Service Unavailable>)
  File "yt_dlp\extractor\common.py", line 740, in extract
  File "yt_dlp\extractor\hotstar.py", line 250, in _real_extract
  File "yt_dlp\extractor\hotstar.py", line 65, in _call_api_v2
  File "yt_dlp\extractor\hotstar.py", line 40, in _call_api_impl
  File "yt_dlp\extractor\common.py", line 1139, in download_content
  File "yt_dlp\extractor\common.py", line 1099, in download_handle
  File "yt_dlp\extractor\common.py", line 960, in _download_webpage_handle
  File "yt_dlp\extractor\common.py", line 909, in _request_webpage

  File "yt_dlp\extractor\common.py", line 896, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 4165, in urlopen
  File "yt_dlp\networking\common.py", line 117, in send
  File "yt_dlp\networking\_helper.py", line 208, in wrapper
  File "yt_dlp\networking\common.py", line 340, in send
  File "yt_dlp\networking\_requests.py", line 365, in _send
yt_dlp.networking.exceptions.HTTPError: HTTP Error 503: Service Unavailable


C:\Users\moder\Downloads\Programs>
```

**Comment by bashonly** [comment]
Most likely caused by the same underlying issue as in #10366 (guest token endpoint has been disabled/restricted)

Try passing cookies from a logged-in browser session

**Comment by ETapk** [comment]
Thank you for your response. And your specifying method is working fine.

C:\Users\pc 2\Desktop\video tools>yt-dlp --cookies cookies.txt -vU -F
https://www.hotstar.com/in/shows/khukumoni-home-delivery/1260072493/meet-khukumoni-delivering-food/1000267861/watch
[debug] Command-line config: ['--cookies', 'cookies.txt', '-vU', '-F', '
https://www.hotstar.com/in/shows/khukumoni-home-delivery/1260072493/meet-khukumoni-delivering-food/1000267861/watch
']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error
utf-8, screen utf-8
[debug] yt-dlp version ***@***.*** from yt-dlp/yt-dlp [12b248ce6]
(win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0
(OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-92795-gcdbf8847ea, ffprobe
2024-01-01-git-e1c1dc8347-essentials_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0,
certifi-2024.02.02, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.2,
sqlite3-3.35.5, urllib3-2.2.1, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1820 extractors
[debug] Fetching release info:
https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
[debug] Downloading _update_spec from
https://github.com/yt-dlp/yt-dlp/releases/latest/download/_update_spec
[debug] Downloading SHA2-256SUMS from
https://github.com/yt-dlp/yt-dlp/releases/download/2024.08.06/SHA2-256SUMS
Current version: ***@***.*** from yt-dlp/yt-dlp
Latest version: ***@***.*** from yt-dlp/yt-dlp
Current Build Hash:
e96f6348244306ac999501b1e8e2b096b8a57f098c3b2b9ffe64b2107039e0ae
Updating to ***@***.*** from yt-dlp/yt-dlp ...
[debug] Downloading yt-dlp.exe from
https://github.com/yt-dlp/yt-dlp/releases/download/2024.08.06/yt-dlp.exe
Updated yt-dlp to ***@***.*** from yt-dlp/yt-dlp
[debug] Restarting: yt-dlp --cookies cookies.txt -vU -F
https://www.hotstar.com/in/shows/khukumoni-home-delivery/1260072493/meet-khukumoni-delivering-food/1000267861/watch
[debug] Command-line config: ['--cookies', 'cookies.txt', '-vU', '-F', '
https://www.hotstar.com/in/shows/khukumoni-home-delivery/1260072493/meet-khukumoni-delivering-food/1000267861/watch
']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error
utf-8, screen utf-8
[debug] yt-dlp version ***@***.*** from yt-dlp/yt-dlp [4d9231208]
(win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0
(OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-92795-gcdbf8847ea, ffprobe
2024-01-01-git-e1c1dc8347-essentials_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0,
certifi-2024.07.04, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3,
sqlite3-3.35.5, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1830 extractors
[debug] Fetching release info:
https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: ***@***.*** from yt-dlp/yt-dlp
yt-dlp is up to date ***@***.*** from yt-dlp/yt-dlp)
[hotstar] Extracting URL:
https://www.hotstar.com/in/shows/khukumoni-home-delivery/1260072493/meet-khukumoni-delivering-food/1000267861/watch
[hotstar] 1000267861: Downloading JSON metadata
[hotstar] 1000267861: Downloading webpage
[hotstar] 1000267861: Downloading JSON metadata
[hotstar] 1000267861: Downloading MPD manifest
[hotstar] 1000267861: Downloading m3u8 information
[hotstar] 1000267861: Downloading MPD manifest
[hotstar] 1000267861: Downloading MPD manifest
[hotstar] 1000267861: Downloading m3u8 information
[hotstar] 1000267861: Downloading m3u8 information
[hotstar] 1000267861: Downloading m3u8 information
[hotstar] 1000267861: Downloading m3u8 information
[hotstar] 1000267861: Downloading m3u8 information
[hotstar] 1000267861: Downloading m3u8 information
[hotstar] 1000267861: Downloading MPD manifest
[hotstar] 1000267861: Downloading m3u8 information
[hotstar] 1000267861: Downloading m3u8 information
[hotstar] 1000267861: Downloading m3u8 information
[hotstar] 1000267861: Downloading MPD manifest
[hotstar] 1000267861: Downloading MPD manifest
[hotstar] 1000267861: Downloading MPD manifest
[hotstar] 1000267861: Downloading MPD manifest
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps,
hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext,
aext, hasaud, source, id
[info] Available formats for 1000267861:
ID                                      EXT RESOLUTION FPS HDR CH │
FILESIZE  TBR PROTO │ VCODEC        VBR ACODEC      ABR ASR MORE INFO
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
audio_aac_1635780875016-und-mp4a-1      m4a audio only          2 │ ~
 9.44MiB  50k https │ audio only        mp4a.40.2   50k 48k phone, stereo,
DASH audio, m4a_dash
audio_aac_1635784560451-und-mp4a-1      m4a audio only          2 │ ~
 9.44MiB  50k https │ audio only        mp4a.40.2   50k 48k tv, stereo,
DASH audio, m4a_dash
audio_aac_1635780875016-und-mp4a-2      m4a audio only          2 │ ~
12.46MiB  66k https │ audio only        mp4a.40.2   66k 48k phone, stereo,
DASH audio, m4a_dash
audio_aac_1635784560451-und-mp4a-2      m4a audio only          2 │ ~
12.46MiB  66k https │ audio only        mp4a.40.2   66k 48k tv, stereo,
DASH audio, m4a_dash
audio_aac_1635780875016-und-mp4a-3      m4a audio only          2 │ ~
24.55MiB 130k https │ audio only        mp4a.40.2  130k 48k phone, stereo,
DASH audio, m4a_dash
audio_aac_1635784560451-und-mp4a-3      m4a audio only          2 │ ~
24.55MiB 130k https │ audio only        mp4a.40.2  130k 48k tv, stereo,
DASH audio, m4a_dash
audio_mp4a_129-Unknown-0                mp4 audio only          2 │
        m3u8  │ audio only        aac                 [und] tv, stereo,
Unknown
audio_mp4a_129-Unknown-1                mp4 audio only          2 │
        m3u8  │ audio only        aac                 [und] phone, stereo,
Unknown
audio_mp4a_129-Unknown-2                mp4 audio only          2 │
        m3u8  │ audio only        aac                 [und] tv, stereo,
Unknown
audio_mp4a_129-Unknown-3                mp4 audio only          2 │
        m3u8  │ audio only        aac                 [und] tv, stereo,
Unknown
audio_mp4a_49-Unknown-0                 mp4 audio only          2 │
        m3u8  │ audio only        aac                 [und] tv, stereo,
Unknown
audio_mp4a_49-Unknown-1                 mp4 audio only          2 │
        m3u8  │ audio only        aac                 [und] phone, stereo,
Unknown
audio_mp4a_49-Unknown-2                 mp4 audio only          2 │
        m3u8  │ audio only        aac                 [und] tv, stereo,
Unknown
audio_mp4a_49-Unknown-3                 mp4 audio only          2 │
        m3u8  │ audio only        aac                 [und] tv, stereo,
Unknown
audio_mp4a_65-Unknown-0                 mp4 audio only          2 │
        m3u8  │ audio only        aac                 [und] tv, stereo,
Unknown
audio_mp4a_65-Unknown-1                 mp4 audio only          2 │
        m3u8  │ audio only        aac                 [und] phone, stereo,
Unknown
audio_mp4a_65-Unknown-2                 mp4 audio only          2 │
        m3u8  │ audio only        aac                 [und] tv, stereo,
Unknown
audio_mp4a_65-Unknown-3                 mp4 audio only          2 │
        m3u8  │ audio only        aac                 [und] tv, stereo,
Unknown
177                                     mp4 320x180        sdr  2 │ ~
33.64MiB 177k m3u8  │ avc1.42C00C       mp4a.40.2           phone, stereo
video_h264_fhd_sdr_1635780875016_avc1_1 mp4 320x180     25 sdr    │ ~
17.11MiB  90k dash  │ avc1.42C00C   90k video only          phone, DASH
video, mp4_dash
video_h264_fhd_sdr_1635780875016-avc1-1 mp4 320x180     25 sdr    │ ~
17.11MiB  90k https │ avc1.42C00C   90k video only          phone, DASH
video, mp4_dash
130                                     mp4 320x180     25 sdr    │ ~
24.83MiB 131k m3u8  │ avc1.42C00C  131k video only          phone
131                                     mp4 320x180     25 sdr    │ ~
24.83MiB 131k m3u8  │ avc1.42C00C  131k video only          phone
video_h265_fhd_sdr_1635784560451_hvc1_1 mp4 320x180     25 sdr    │ ~
21.52MiB 114k dash  │ hvc1.1.6.L60 114k video only          phone, DASH
video, mp4_dash
video_h265_fhd_sdr_1635784560451-hvc1-1 mp4 320x180     25 sdr    │ ~
21.52MiB 114k https │ hvc1.1.6.L60 114k video only          phone, DASH
video, mp4_dash
137-0                                   mp4 320x180     25 sdr    │ ~
26.16MiB 138k m3u8  │ hvc1.1.6.L60 138k video only          phone
137-1                                   mp4 320x180     25 sdr    │ ~
26.16MiB 138k m3u8  │ hvc1.1.6.L60 138k video only          phone
233                                     mp4 426x240        sdr  2 │ ~
44.30MiB 234k m3u8  │ avc1.42C015       mp4a.40.2           tv, stereo
video_h264_fhd_sdr_1635780875016_avc1_2 mp4 426x240     25 sdr    │ ~
29.16MiB 154k dash  │ avc1.42C015  154k video only          tv, DASH video,
mp4_dash
video_h264_fhd_sdr_1635780875016-avc1-2 mp4 426x240     25 sdr    │ ~
29.16MiB 154k https │ avc1.42C015  154k video only          phone, DASH
video, mp4_dash
186-0                                   mp4 426x240     25 sdr    │ ~
35.27MiB 186k m3u8  │ avc1.42C015  186k video only          phone
186-1                                   mp4 426x240     25 sdr    │ ~
35.27MiB 186k m3u8  │ avc1.42C015  186k video only          tv
178-0                                   mp4 426x240     25 sdr    │ ~
33.84MiB 179k m3u8  │ hvc1.1.6.L60 179k video only          tv
178-1                                   mp4 426x240     25 sdr    │ ~
33.84MiB 179k m3u8  │ hvc1.1.6.L60 179k video only          tv
video_h265_fhd_sdr_1635784560451_hvc1_2 mp4 426x240     25 sdr    │ ~
35.02MiB 185k dash  │ hvc1.1.6.L60 185k video only          tv, DASH video,
mp4_dash
video_h265_fhd_sdr_1635784560451-hvc1-2 mp4 426x240     25 sdr    │ ~
35.02MiB 185k https │ hvc1.1.6.L60 185k video only          tv, DASH video,
mp4_dash
305                                     mp4 640x360        sdr  2 │ ~
57.95MiB 306k m3u8  │ avc1.4D401E       mp4a.40.2           tv, stereo
video_h264_fhd_sdr_1635780875016-avc1-3 mp4 640x360     25 sdr    │ ~
44.27MiB 234k https │ avc1.4D401E  234k video only          phone, DASH
video, mp4_dash
256-0                                   mp4 640x360     25 sdr    │ ~
48.57MiB 256k m3u8  │ avc1.4D401E  256k video only          phone
256-1                                   mp4 640x360     25 sdr    │ ~
48.57MiB 256k m3u8  │ avc1.4D401E  256k video only          tv
257-0                                   mp4 640x360     25 sdr    │ ~
48.80MiB 257k m3u8  │ hvc1.1.6.L63 257k video only          tv
257-1                                   mp4 640x360     25 sdr    │ ~
48.80MiB 257k m3u8  │ hvc1.1.6.L63 257k video only          tv
video_h265_fhd_sdr_1635784560451-hvc1-3 mp4 640x360     25 sdr    │ ~
54.09MiB 285k https │ hvc1.1.6.L63 285k video only          tv, DASH video,
mp4_dash
616                                     mp4 854x480        sdr  2 │
~116.94MiB 617k m3u8  │ avc1.4D401F       mp4a.40.2           tv, stereo
524-0                                   mp4 854x480     25 sdr    │ ~
99.47MiB 525k m3u8  │ avc1.4D401F  525k video only          phone
524-1                                   mp4 854x480     25 sdr    │ ~
99.47MiB 525k m3u8  │ avc1.4D401F  525k video only          tv
video_h264_fhd_sdr_1635780875016-avc1-4 mp4 854x480     25 sdr    │
~109.11MiB 576k https │ avc1.4D401F  576k video only          phone, DASH
video, mp4_dash
387-0                                   mp4 854x480     25 sdr    │ ~
73.52MiB 388k m3u8  │ hvc1.1.6.L90 388k video only          tv
387-1                                   mp4 854x480     25 sdr    │ ~
73.52MiB 388k m3u8  │ hvc1.1.6.L90 388k video only          tv
video_h265_fhd_sdr_1635784560451-hvc1-4 mp4 854x480     25 sdr    │
~105.94MiB 559k https │ hvc1.1.6.L90 559k video only          tv, DASH
video, mp4_dash

**Comment by BossyBigBoss** [comment]
Anybody finds the solution. 
Ctrl+F5 a few times in the browser sometimes helps to avoid Error 503 and the video plays OK.

**Comment by rohitbd9** [comment]
@ETapk R u bangladeshi?
please give your contact number, email, or anything
i want to.talk to.u
