### ISSUE TITLE
video formats found!

### ISSUE THREAD

**Issue by 1dev-hridoy** [yt-dlp/yt-dlp#10730]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

ERROR: [Instagram] C-aOHKVzpGb: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
127.0.0.1 - - [13/Aug/2024:04:52:50 +0000] "GET /igvideo=https%3A%2F%2Fwww.instagram.com%2Freel%2FC-EYnCqIzFK%2F%3Figsh%3DOWIxcGZsM3J6Y3px HTTP/1.1" 200 85 "-" "axios/1.7.3"
127.0.0.1 - - [13/Aug/2024:04:52:51 +0000] "GET /c83ead3f-06d0-4e56-b467-400471ce8682.mp4 HTTP/1.1" 200 0 "-" "axios/1.7.3"
ERROR: [Instagram] C-aOHKVzpGb: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

**Comment by grqz** [comment]
> * [x]  Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
> * [ ]  If using API, add `'verbose': True` to `YoutubeDL` params instead
> * [x]  Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below
>
