### ISSUE TITLE
[PatreonCampaign] Unable to extract next.js data

### ISSUE THREAD

**Issue by hibes** [yt-dlp/yt-dlp#10733]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

USA

### Provide a description that is worded well enough to be understood

The URL I have been using (was working as of early July) is the campaign API URL (e.g. https://www.patreon.com/api/campaigns/4243769/posts) and even from a logged out private window, you can view these results.

It seems that somewhere along the line support for these types of campaign pages might have been lost.

>  What the problem is

Seems addressed above.

> How it could be fixed

Hopefully there's an obvious additional conditional to solve this. Since all the data is still present within the API response (see data at json selector `.data[0].attributes.content.embed.url` for an example), it seems like this API response should still work. I'm not sure why it's trying to parse next.js data since this is clearly JSON output, possibly an unexpected `content-type` header (I'm seeing `application/vnd.api+json`)

> How your proposed solution would look like

Again, hopefully the code is still there to parse this and just a different conditional to route to existing parsing code will solve it.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--no-call-home', '--add-metadata', '--cookies', '/mnt/huge/share/video-collections/cookie-jar-file', '--download-archive', '/mnt/huge/share/video-collections/.second.thought.ytdlparchive', '--embed-metadata', '--embed-thumbnail', '--sleep-requests', '2', 'https://www.patreon.com/api/campaigns/4243769/posts']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.08.12.232840 from yt-dlp/yt-dlp-nightly-builds [49f3741a8] (pip)
[debug] Python 3.10.12 (CPython x86_64 64bit) - Linux-5.15.0-107-generic-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg N-113348-g0a5813fc68-20240119 (setts), ffprobe N-113348-g0a5813fc68-20240119
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2024.02.02, mutagen-1.47.0, requests-2.32.3, secretstorage-3.3.1, sqlite3-3.37.2, urllib3-2.1.0, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1830 extractors
[debug] Loading archive file '/mnt/huge/share/video-collections/.second.thought.ytdlparchive'
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.08.12.232840 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.08.12.232840 from yt-dlp/yt-dlp-nightly-builds)
[PatreonCampaign] Extracting URL: https://www.patreon.com/api/campaigns/4243769/posts
[PatreonCampaign] api: Downloading webpage
ERROR: [PatreonCampaign] Unable to extract next.js data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/home/h/.local/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 740, in extract
    ie_result = self._real_extract(url)
  File "/home/h/.local/lib/python3.10/site-packages/yt_dlp/extractor/patreon.py", line 497, in _real_extract
    campaign_id = self._search_nextjs_data(
  File "/home/h/.local/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 1760, in _search_nextjs_data
    return self._search_json(
  File "/home/h/.local/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 1347, in _search_json
    json_string = self._search_regex(
  File "/home/h/.local/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 1333, in _search_regex
    raise RegexNotFoundError(f'Unable to extract {_name}')
```

**Comment by bashonly** [comment]
Going by the extractor code, I don't think the `/api/campaigns/` URL format was ever *officially* supported by yt-dlp, and if it worked in the past then it only worked by happenstance (and a recent change to the extractor broke this "accidental" support.)

As an immediate workaround, you could change the URL from `https://www.patreon.com/api/campaigns/4243769/posts` to `https://www.patreon.com/m/4243769/posts` (replace `/api/campaigns/` with `/m/`).

A proper fix to add support for this URL format would look like this:

```diff
diff --git a/yt_dlp/extractor/patreon.py b/yt_dlp/extractor/patreon.py
index 7d6e8439c..6fc3519ce 100644
--- a/yt_dlp/extractor/patreon.py
+++ b/yt_dlp/extractor/patreon.py
@@ -420,7 +420,7 @@ def _get_comments(self, post_id):
 
 class PatreonCampaignIE(PatreonBaseIE):
 
-    _VALID_URL = r'https?://(?:www\.)?patreon\.com/(?!rss)(?:(?:m/(?P<campaign_id>\d+))|(?P<vanity>[-\w]+))'
+    _VALID_URL = r'https?://(?:www\.)?patreon\.com/(?!rss)(?:(?:m|api/campaigns)/(?P<campaign_id>\d+)|(?P<vanity>[-\w]+))'
     _TESTS = [{
         'url': 'https://www.patreon.com/dissonancepod/',
         'info_dict': {
```
(plus an additional test case)

**Comment by hibes** [comment]
@bashonly, thanks for the insanely quick response. I put up a PR #10734 , mind adding your consent to publishing the code as unlicensed?
