### ISSUE TITLE
Is it able to add different criteria separately for video and audio in format sorting (using `--format-sort` or `-S`)

### ISSUE THREAD

**Issue by teadrinker2015** [yt-dlp/yt-dlp#10744]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

The title is clear enough. e.g.

```bash
# a humble proposal
yt-dlp -f "bv+ba" -S "video:+size,audio:size"
# or
yt-dlp -f "bv+ba" -S:v "+size" -S:a "size"
```

# Use Case

Lots of live archives from vtubers, where the audio contents is more informative than the merely symbolic visual contents.

## Why not `-wv`?

quoted from doc:
> Most of the time, what you actually want is the video with the smallest filesize instead. So it is generally better to use -f best -S +size,+br,+res,+fps.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
Bitrate has a direct correlation to filesize, so sorting with `vbr` and `abr` is pretty much what you want. You can also combine worst and best in format selection, e.g. `wv+ba` or `bv+wa`. Are these not sufficient?

**Comment by teadrinker2015** [comment]
@bashonly Pretty much sufficient. Just didn't read the doc thoroughly
