### ISSUE TITLE
[Site Request] Youtube: Add extra fields to the playlist metadata file

### ISSUE THREAD

**Issue by shoxie007** [yt-dlp/yt-dlp#1074]
## Checklist

- [x] I'm reporting a site feature request
- [x] I've verified that I'm running yt-dlp version **2021.09.02**
- [x] I've searched the bugtracker for similar site feature requests including closed ones

## Description

I very much appreciate yt-dlp's ability to write the playlist's own metadata - title, description etc - to a JSON file using command:
`yt-dlp --write-info-json --flat-playlist --playlist-items 1 "https://www.youtube.com/playlist?list=PL8mG-RkN2uTzgyA8zzE8vRB3_ZXQfuFRz"`

But there are some glaring absences in the data fields in the resulting JSON file; data which is clearly shown in the left column when you load a playlist:
- No. of playlist items.  
- No. of views
- Date last updated (Youtube shows a relative date. An exact date would be better in the JSON file.)

For example:
`https://www.youtube.com/playlist?list=PL8mG-RkN2uTzgyA8zzE8vRB3_ZXQfuFRz`
has 5 videos, 2,077 views and was updated 3 days ago. All this info is missing from the JSON file.

I request that this info be added to the playlist's metadata which is written to the JSON file. It should be a small matter to extract this extra info from the webpage.

Thanks

**Comment by coletdjnz** [comment]
> Date last updated (Youtube shows a relative date. An exact date would be better in the JSON file.)


YouTube is probably _only_ providing the relative date. 
While we do have functions to convert this to an estimated date, the accuracy can vary widely. So unless the user knows what they are doing, I am against having this added by default. But we might be able to add a option to enable it, similar to what I was thinking in https://github.com/yt-dlp/yt-dlp/pull/1018.
(on that note, comment extraction does do this by default atm)

> No. of views

should be good to add

> No. of playlist items.

could be useful for giving estimations during page downloads too, similar to comments.

**Comment by pukkandan** [comment]
We don't have any field for "last updated date" anyway. I am against adding a new field just for playlists when we can't even get an accurate date
