### ISSUE TITLE
Documentation bug: *match-filter(s)

### ISSUE THREAD

**Issue by atom-smasher** [yt-dlp/yt-dlp#10751]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Documentation is inconsistent about whether `--match-filters` and `--no-match-filters` is singular or plural.

This command:
`yt-dlp -h | grep -C1 match-filter`

Produces this output:

```
                                    same as --date
    --match-filters FILTER          Generic video filter. Any "OUTPUT TEMPLATE"
                                    field can be compared with a number or a
--
                                    the filter matches if at least one of the
                                    conditions is met. E.g. --match-filter
                                    !is_live --match-filter "like_count>?100 &
                                    description~='(?i)\bcats \& dogs\b'" matches
--
                                    description that contains the phrase "cats &
                                    dogs" (caseless). Use "--match-filter -" to
                                    interactively ask whether to download each
                                    video
    --no-match-filters              Do not use any --match-filter (default)
    --break-match-filters FILTER    Same as "--match-filters" but stops the
                                    download process when a video is rejected
    --no-break-match-filters        Do not use any --break-match-filters
                                    (default)
--
    --break-per-input               Alters --max-downloads, --break-on-existing,
                                    --break-match-filter, and autonumber to
                                    reset per input URL
```

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--ignore-config']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version master@2024.08.13.232712 from yt-dlp/yt-dlp-master-builds [232e6db30] (zip)
[debug] Python 3.10.12 (CPython x86_64 64bit) - Linux-6.5.0-18-generic-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2, phantomjs 2.1.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.11.0, certifi-2020.06.20, mutagen-1.45.1, pyxattr-0.7.2, requests-2.25.1, secretstorage-3.3.1, sqlite3-3.37.2, urllib3-1.26.5
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Extractor Plugins: Youtube_AgeGateBypassIE
[debug] Loaded 1831 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-master-builds/releases/latest
Latest version: master@2024.08.13.232712 from yt-dlp/yt-dlp-master-builds
yt-dlp is up to date (master@2024.08.13.232712 from yt-dlp/yt-dlp-master-builds)
```

**Comment by bashonly** [comment]
`--match-filter` and `--match-filters` are both valid (and both are the exact same option); any long opt can be shortened up until it becomes ambiguous.

For example, `--write-info-json` can be shortened to `--write-info`, but shortening it to `--write` doesn't work because then the argument parser doesn't know if it's `--write-info-json` or `--write-description` or `--write-subs` etc

In spite of this, I agree that consistency in the docs would be nice, and this could be fixed in a cleanup commit
