### ISSUE TITLE
twitter blocked account for downloading videos, any improvement can be done in authentication or downloading?

### ISSUE THREAD

**Issue by ms8x8x** [yt-dlp/yt-dlp#10754]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I use the latest yt-dlp for downloading videos from twitter, with the parameters username and password. This works for months.

Recently, everytime I downloaded, I would receive an email for warning abnormal activities for my account from twitter the next day; and after several mails, my account would be suspended and I was challenged as a robot in login process with CAPTCHA. And then several times of challenges, my account was blocked totally.

Is it related with he authentication process or downloading too fast? 

Hope you guys can check and make it better coz I like this tool very much.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by seproDev** [comment]
Yeah, this is likely related to the repeated authentication in an automated manner.
I would strongly advise against using `--username` and `--password` and instead rely on your browser cookies if necessary, either by exporting them to a file and using that file with `--cookies` or by using `--cookies-from-browser`.

**Comment by bashonly** [comment]
If you are unable to use `--cookies-from-browser` or manually export cookies from browser:

You could use `--username` and `--password` in conjunction with `--cookies cookiefile.txt` ONCE so that the logged-in cookies are written to `cookiefile.txt`. Then going forward you would only need to pass `--cookies cookiefile.txt` (and NOT `--username`/`--password`)

**Comment by ms8x8x** [comment]
thanks a lot! I solved this via internalbrowser in mini A shell to pass the cookies to yt-dlp, it works great!

**Comment by ms8x8x** [comment]
tiwtter now can detect the downloading via cookies way... I was banned serveral times again. are the video links includes the account information? if yes, 3rd party downloading tools can deffinitedly cause banning account...
