### ISSUE TITLE
cat: yt-dlp/2024.8.6/libexec/lib/python3.12/site-packages/yt_dlp/extractor/kakao.py: Operation not permitted

### ISSUE THREAD

**Issue by dnlchen** [yt-dlp/yt-dlp#10750]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

The file yt-dlp/2024.8.6/libexec/lib/python3.12/site-packages/yt_dlp/extractor/kakao.py is broken.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
$ tar xvfz /Users/daniel.c1/Library/Caches/Homebrew/downloads/cc6403e7dde980710f94cea632b22aad7d529b37210f3b0f203931e36cedc48d--yt-dlp--2024.8.6.monterey.bottle.tar.gz
$ cat yt-dlp/2024.8.6/libexec/lib/python3.12/site-packages/yt_dlp/extractor/kakao.py
cat: yt-dlp/2024.8.6/libexec/lib/python3.12/site-packages/yt_dlp/extractor/kakao.py: Operation not permitted
```

**Comment by bashonly** [comment]
Why are you manually untarring a brew bottle? What are you trying to do? How is this a yt-dlp issue?

**Comment by dnlchen** [comment]
I think that the file in the package is broken.

**Comment by bashonly** [comment]
It's a permission error. Not a yt-dlp issue

https://stackoverflow.com/a/70236034
