### ISSUE TITLE
yt-dlp without option -f does lead to not suited video, audio format (e.g.: avc1+ Opus), minor fault for youtube

### ISSUE THREAD

**Issue by Gloster10** [yt-dlp/yt-dlp#10758]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a site-specific feature
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Germany

### Example URLs

https://www.youtube.com/watch?v=Hu0p3GFTdgc&list=PLsltk_UbXJ62Fsg7Zj4NkF1rxt1fJ841d&index=41&pp=iAQB

### Provide a description that is worded well enough to be understood

I would expect, the best (audio+video), but also suited I would get via : 
yt-dlp -o "%(title)s.%(ext)s" --no-playlist -N 8 "https://www.youtube.com/watch?v=Hu0p3GFTdgc&list=PLsltk_UbXJ62Fsg7Zj4NkF1rxt1fJ841d&index=41&pp=iAQB"
But I get : 
Video : 136 mp4   1280x720    25    │  979.76MiB 1116k https │ avc1.64001F   1116k video only          720p, mp4_dash
Audio : 251 webm  audio only      2 │  108.27MiB  123k https │ audio only          opus       123k 48k medium, webm_dash
(After all the used container "mkv" will be correct)

I would expect : 
Video : 136 mp4   1280x720    25    │  979.76MiB 1116k https │ avc1.64001F   1116k video only          720p, mp4_dash
Audio : 140 m4a   audio only      2 │  113.67MiB  129k https │ audio only          mp4a.40.2  129k 44k medium, m4a_dash

Audio + video in a suited format.

It is not a problem to play the not suited formats with vlc, mpv, ...

But I use DLNA via TV, most TVs does not know Opus.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '-o', '%(title)s.%(ext)s', '--no-playlist', '-N', '8', 'https://www.youtube.com/watch?v=Hu0p3GFTdgc&list=PLsltk_UbXJ62Fsg7Zj4NkF1rxt1fJ841d&index=41&pp=iAQB']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.08.06 from yt-dlp/yt-dlp [4d9231208] (zip)
[debug] Python 3.10.12 (CPython x86_64 64bit) - Linux-6.5.0-45-generic-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.02.02, mutagen-1.47.0, requests-2.31.0, secretstorage-3.3.3, sqlite3-3.37.2, urllib3-2.2.0, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, websockets
[debug] Loaded 1830 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.08.06 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.08.06 from yt-dlp/yt-dlp)
[youtube:tab] Extracting URL: https://www.youtube.com/watch?v=Hu0p3GFTdgc&list=PLsltk_UbXJ62Fsg7Zj4NkF1rxt1fJ841d&index=41&pp=iAQB
[youtube:tab] Downloading just the video Hu0p3GFTdgc because of --no-playlist
[youtube] Extracting URL: https://www.youtube.com/watch?v=Hu0p3GFTdgc
[youtube] Hu0p3GFTdgc: Downloading webpage
[youtube] Hu0p3GFTdgc: Downloading ios player API JSON
[youtube] Hu0p3GFTdgc: Downloading web creator player API JSON
[debug] Loading youtube-nsig.53afa3ce from cache
[debug] [youtube] Decrypted nsig i8KKnhSLN69LjepYV => CqzJSHCVDIofNw
[debug] Loading youtube-nsig.53afa3ce from cache
[debug] [youtube] Decrypted nsig TiEghlIqwjRMgivih => IgwECzmfteymDw
[youtube] Hu0p3GFTdgc: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] Hu0p3GFTdgc: Downloading 1 format(s): 136+251
[debug] Invoking http downloader on "https://rr4---sn-uxax4vopj5qx-q0n6.googlevideo.com/videoplayback?expire=1723759089&ei=kSW-ZszcD6XQp-oP3b2K4QQ&ip=93.131.8.41&id=o-APRLBAOYzrhKMGH0c7bhqNG9LvLKXftw-SBBNvuqYm02&itag=136&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=8J&mm=31%2C29&mn=sn-uxax4vopj5qx-q0n6%2Csn-4g5edndy&ms=au%2Crdu&mv=m&mvi=4&pl=18&gcr=de&initcwndbps=1185000&vprv=1&svpuc=1&mime=video%2Fmp4&rqh=1&gir=yes&clen=1027355570&dur=7364.560&lmt=1721580319422596&mt=1723736973&fvip=3&keepalive=yes&c=IOS&txp=6209224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cgcr%2Cvprv%2Csvpuc%2Cmime%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRAIgVG3Lr8nGkMyt5Fgv4v_9mX_DKGIhPyjKnl8ev8MS27oCIFjH7CmsbVJGdSnxI02KukQGc3gy04PdOgDaq-jJfOhc&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AGtxev0wRQIgIY7gJlcfM5HgGCOJXwAqERUARt2jrFe28fbOqaqZfM4CIQDTzyIKrmxDT5ndBDEOL80OLRzWJSi3ucVET9f2M-NoxA%3D%3D"
[download] Destination: New Police Story ｜ 2004 ｜ HD ｜ Action⧸Krimi ｜ mit Jackie Chan ｜.f136.mp4
[download]   1.4% of  979.76MiB at    6.75MiB/s ETA 02:23^C
ERROR: Interrupted by user
```

**Comment by seproDev** [comment]
That is entirely expected. By default, yt-dlp will download the best available formats. Opus is more efficient than AAC, so that has preference over AAC.

If you need AVC/h264 video and AAC audio for compatibility, you can use `-S vcodec:avc,res:acodec:aac` to change the sorting yt-dlp applies to formats.

**Comment by Gloster10** [comment]
I did :
yt-dlp -S vcodec:avc,res:acodec:aac -o "%(title)s.%(ext)s" --no-playlist -N 8 "https://www.youtube.com/watch?v=Hu0p3GFTdgc&list=PLsltk_UbXJ62Fsg7Zj4NkF1rxt1fJ841d&index=41&pp=iAQB"

But got also opus+avc1

**Comment by seproDev** [comment]
Can you share a verbose log please by adding `-v` to that command?

**Comment by seproDev** [comment]
Oops, my bad I typoed. It should be `-S vcodec:avc,res,acodec:aac `

**Comment by Gloster10** [comment]
yt-dlp -v -S vcodec:avc,res:acodec:aac -o "%(title)s.%(ext)s" --no-playlist -N 8 "https://www.youtube.com/watch?v=Hu0p3GFTdgc&list=PLsltk_UbXJ62Fsg7Zj4NkF1rxt1fJ841d&index=41&pp=iAQB"
[debug] Command-line config: ['-v', '-S', 'vcodec:avc,res:acodec:aac', '-o', '%(title)s.%(ext)s', '--no-playlist', '-N', '8', 'https://www.youtube.com/watch?v=Hu0p3GFTdgc&list=PLsltk_UbXJ62Fsg7Zj4NkF1rxt1fJ841d&index=41&pp=iAQB']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.08.06 from yt-dlp/yt-dlp [4d9231208] (zip)
[debug] Python 3.10.12 (CPython x86_64 64bit) - Linux-6.5.0-45-generic-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.02.02, mutagen-1.47.0, requests-2.31.0, secretstorage-3.3.3, sqlite3-3.37.2, urllib3-2.2.0, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, websockets
[debug] Loaded 1830 extractors
[youtube:tab] Extracting URL: https://www.youtube.com/watch?v=Hu0p3GFTdgc&list=PLsltk_UbXJ62Fsg7Zj4NkF1rxt1fJ841d&index=41&pp=iAQB
[youtube:tab] Downloading just the video Hu0p3GFTdgc because of --no-playlist
[youtube] Extracting URL: https://www.youtube.com/watch?v=Hu0p3GFTdgc
[youtube] Hu0p3GFTdgc: Downloading webpage
[youtube] Hu0p3GFTdgc: Downloading ios player API JSON
[youtube] Hu0p3GFTdgc: Downloading web creator player API JSON
[debug] Loading youtube-nsig.410a4f15 from cache
[debug] [youtube] Decrypted nsig 0pORkBTr1W0jBiEAT => C9mhyDDg5xfxrQ
[debug] Loading youtube-nsig.410a4f15 from cache
[debug] [youtube] Decrypted nsig PonZjj7jlqfvzp5dx => MBywTc2zQzzmTA
[youtube] Hu0p3GFTdgc: Downloading m3u8 information
[debug] Sort order given by user: vcodec:avc, res:acodec:aac
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, vcodec:avc(7), res:acodec:aac(acodec:aac), quality, fps, hdr:12(7), source, channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] Hu0p3GFTdgc: Downloading 1 format(s): 136+251
[download] New Police Story ｜ 2004 ｜ HD ｜ Action⧸Krimi ｜ mit Jackie Chan ｜.mkv has already been downloaded

**Comment by seproDev** [comment]
Yeah my bad there should be a `,` after res and not a `:`
So:
```
yt-dlp -S vcodec:avc,res,acodec:aac -o "%(title)s.%(ext)s" --no-playlist -N 8 "https://www.youtube.com/watch?v=Hu0p3GFTdgc&list=PLsltk_UbXJ62Fsg7Zj4NkF1rxt1fJ841d&index=41&pp=iAQB"
```

**Comment by Gloster10** [comment]
@seproDev 
It works, thank you.
