### ISSUE TITLE
Is any possible to get the youtube music and not from youtube

### ISSUE THREAD

**Issue by mdxabu** [yt-dlp/yt-dlp#10752]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [x] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I am developing and music discord bot, but yt-dlp gets music from yt, is there any possible change to get from yt music?

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by noahbroyles** [comment]
I think the content is the same across YouTube and YouTube Music. 

For example, if you visit this link YT Music link `https://music.youtube.com/watch?v=wgqUhK32n1c`, the same exact song/video is on YouTube using the same video ID at `https://youtube.com/watch?v=wgqUhK32n1c`. In this case, the video ID would be `wgqUhK32n1c`.

The only difference is that YouTube Music only shows videos from YouTube that are music, and not the rest of videos from YouTube.

**Comment by bashonly** [comment]
There are some open issues related to this:
- #622
- #6351
- #9913
- #10247
- #10530
- #10695

Closing since the OP does not sufficiently describe the issue or give any examples

**Comment by lomik31** [comment]
> The only difference is that YouTube Music only shows videos from YouTube that are music, and not the rest of videos from YouTube.

I would like to search for tracks only, because very often when searching for music the first result is a clip of that track.
is there any functionality for this in yt-dlp?
