### ISSUE TITLE
After packaging with PyInstaller, can the unlock plugin be used?

### ISSUE THREAD

**Issue by Kukaina** [yt-dlp/yt-dlp#10764]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I packaged my program using PyInstaller and created the yt_dlp folder under the %AppData% directory. It contains the unlock/postprocessor folder. The plugin for releasing Chrome's occupation can be used normally in the environment without packaging, but it is not available after packaging. Is there a problem with the way I install the plugin? 

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by Grub4K** [comment]
Refer to the [Installing Plugins](<https://github.com/yt-dlp/yt-dlp#installing-plugins>) section of the readme. It seems to me you are not using the correct directory. Being able to load plugins is unrelated to bundling.

**Comment by Kukaina** [comment]
> Refer to the [Installing Plugins](https://github.com/yt-dlp/yt-dlp#installing-plugins) section of the readme. It seems to me you are not using the correct directory. Being able to load plugins is unrelated to bundling.

https://y.qq.com/n/ryqq/songDetail/000cLmDa1LcN7L

**Comment by Kukaina** [comment]
> Refer to the [Installing Plugins](https://github.com/yt-dlp/yt-dlp#installing-plugins) section of the readme. It seems to me you are not using the correct directory. Being able to load plugins is unrelated to bundling.
Thank you. I found that I wrongly wrote - as _.
