### ISSUE TITLE
Media offline in Davinci Resolve

### ISSUE THREAD

**Issue by NotShorkAtAll** [yt-dlp/yt-dlp#10767]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Im trying to create some videos and I want to put some memes into my videos. However when I try to upload the video onto Davinci Resolve, some of the frames in the downloaded video will say "Media Offline" I tried to fix it by media linking the folder to my Davinci Resolve but it didn't help. The only solution I found is that I have to use a messaging app, send the downloaded video (from YT-DLP) there and download the video from the messaging app.

Here are the codes I used
yt-dlp.exe -S ext 
yt-dlp -f bestaudio[ext=mp4] LINK (this doesn't download the video at all)

(Reminder that I want an MP4 video)

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
The messaging app is re-encoding the video. The encoding(s) you're downloading from Youtube are not compatible with Davinci Resolve.

> Reminder that I want an MP4 video)

Most likely what you actually want is more specific: h264 video and aac audio in an mp4 container

Try `-S vcodec:h264,res,acodec:aac` without any `-f` argument

```
yt-dlp -S vcodec:h264,res,acodec:aac "URL"
```

**Comment by Endres2** [comment]
Hey, I had a similar issue. I could only download MP4 and some of the videos were very blurry. 

I figured out I had to download a dependency for the encoding to work properly (this is under the installation tab on the main GitHub page for yt-dlp):

https://www.ffmpeg.org/

And the new command that you would run is:

yt-dlp -f "(bestvideo+bestaudio/best)[protocol!*=dash]" --external-downloader ffmpeg

There is a video on how to set it up that I was following if you need more guidance:

https://www.youtube.com/watch?v=NmCVDI4M2Ws
