### ISSUE TITLE
[Broken] Servus TV

### ISSUE THREAD

**Issue by MuenchenSued** [yt-dlp/yt-dlp#1076]
## Checklist
- [x] I'm reporting a broken site support
- [x] I've verified that I'm running yt-dlp version **2021.09.25**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log
```
./yt-dlp --verbose https://www.servustv.com/unterhaltung/v/aa-25fhsqdp51w12
[debug] User config file: /home/user/.config/yt-dlp/config
[debug] User config: ['--restrict-filenames', '--no-mtime', '--compat-options', 'filename']
[debug] Command-line config: ['--verbose', 'https://www.servustv.com/unterhaltung/v/aa-25fhsqdp51w12']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] yt-dlp version 2021.09.25 (zip)
[debug] Compatibility options: filename
[debug] Python version 3.8.10 (CPython 64bit) - Linux-5.4.0-86-generic-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4, rtmpdump 2.4
[debug] Optional libraries: Crypto, keyring, sqlite
[debug] Proxy map: {}
[debug] [generic] Extracting URL: https://www.servustv.com/unterhaltung/v/aa-25fhsqdp51w12
[generic] aa-25fhsqdp51w12: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] aa-25fhsqdp51w12: Downloading webpage
[generic] aa-25fhsqdp51w12: Extracting information
ERROR: [generic] Unsupported URL: https://www.servustv.com/unterhaltung/v/aa-25fhsqdp51w12
Traceback (most recent call last):
  File "./yt-dlp/yt_dlp/extractor/common.py", line 585, in extract
    ie_result = self._real_extract(url)
  File "./yt-dlp/yt_dlp/extractor/generic.py", line 3712, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.servustv.com/unterhaltung/v/aa-25fhsqdp51w12
Traceback (most recent call last):
  File "./yt-dlp/yt_dlp/extractor/common.py", line 585, in extract
    ie_result = self._real_extract(url)
  File "./yt-dlp/yt_dlp/extractor/generic.py", line 3712, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.servustv.com/unterhaltung/v/aa-25fhsqdp51w12

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./yt-dlp/yt_dlp/YoutubeDL.py", line 1227, in wrapper
    return func(self, *args, **kwargs)
  File "./yt-dlp/yt_dlp/YoutubeDL.py", line 1252, in __extract_info
    ie_result = ie.extract(url)
  File "./yt-dlp/yt_dlp/extractor/common.py", line 601, in extract
    raise ExtractorError(
yt_dlp.utils.ExtractorError: [generic] Unsupported URL: https://www.servustv.com/unterhaltung/v/aa-25fhsqdp51w12
```

```
./yt-dlp --verbose https://www.servustv.com/videos/aa-25fhsqdp51w12
[debug] User config file: /home/user/.config/yt-dlp/config
[debug] User config: ['--restrict-filenames', '--no-mtime', '--compat-options', 'filename']
[debug] Command-line config: ['--verbose', 'https://www.servustv.com/videos/aa-25fhsqdp51w12']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] yt-dlp version 2021.09.25 (zip)
[debug] Compatibility options: filename
[debug] Python version 3.8.10 (CPython 64bit) - Linux-5.4.0-86-generic-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4, rtmpdump 2.4
[debug] Optional libraries: Crypto, keyring, sqlite
[debug] Proxy map: {}
[debug] [Servus] Extracting URL: https://www.servustv.com/videos/aa-25fhsqdp51w12
[Servus] AA-25FHSQDP51W12: Downloading token
ERROR: [Servus] aa-25fhsqdp51w12: Unable to download JSON metadata: HTTP Error 401:  (caused by <HTTPError 401: ''>); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
  File "./yt-dlp/yt_dlp/extractor/common.py", line 694, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "./yt-dlp/yt_dlp/YoutubeDL.py", line 3256, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
```

## Description
Servus TV is not working since a couple of months. For a short time it was possible to modify the URL, e.g. from the original URL 
```https://www.servustv.com/unterhaltung/v/aa-25fhsqdp51w12``` to ```https://www.servustv.com/videos/aa-25fhsqdp51w12```
but this is not working any longer. Both URLs are shown in the verbose log above.

**Comment by chrizilla** [comment]
[servus.tv](https://en.wikipedia.org/wiki/ServusTV) is an Austrian TV channel. Among others it broadcasts documentaries such as the science documentary series _"P.M. Wissen"_. This series has its own dedicated website www.pm-wissen.com which is an identically cloned spin-off site from servustv.com. Therefore all videos from this documenary series appear on both sites and are embedded in the same manner I believe.

Example:
```
  https://www.servustv.com/wissen/v/aa-214gz2mcs2112/
https://www.pm-wissen.com/technik/v/aa-214gz2mcs2112/
```

I suspect the extractor could easily handle both sites.

**Comment by LinuxOpa** [comment]
**Servus TV** not working

yt-dlp -v 'https://www.servustv.com/wissen/v/aajlu1mnqxsyw2xvdkng/'
[debug] Command-line config: ['--config-location', '/home/db/.config/youtube-dl/config', '-v', 'https://www.servustv.com/wissen/v/aajlu1mnqxsyw2xvdkng/']
[debug] | Config "/home/db/.config/youtube-dl/config": ['--socket-timeout', '10', '--retries', '9999', '--fragment-retries', '9999', '-f', 'bestvideo[height<=720]+bestaudio/best[height<=720]', '--output', '%(title)s.%(ext)s', '--restrict-filenames', '--ignore-errors', '--continue', '--no-part', '--console-title', '--call-home', '--merge-output-format', 'mp4', '--recode-video', 'mp4', '--yes-playlist', '--buffer-size', '1M', '--http-chunk-size', '1M', '--verbose', '--ffmpeg-location', '/home/db/ffmpeg/ffmpeg', '--postprocessor-args', 'ffmpeg:tune film']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.04.08 [7884ade65]
[debug] Python version 3.8.10 (CPython 64bit) - Linux-5.13.0-39-generic-x86_64-with-glibc2.29
[debug] Checking exe version: /home/db/ffmpeg/ffmpeg -bsfs
[debug] Checking exe version: /home/db/ffmpeg/ffprobe -bsfs
[debug] exe versions: ffmpeg N-105673-g51cd565208 (setts), ffprobe N-105673-g51cd565208
[debug] Optional libraries: brotli, certifi, Cryptodome, secretstorage, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [generic] Extracting URL: https://www.servustv.com/wissen/v/aajlu1mnqxsyw2xvdkng/
[generic] aajlu1mnqxsyw2xvdkng: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] aajlu1mnqxsyw2xvdkng: Downloading webpage
[generic] aajlu1mnqxsyw2xvdkng: Extracting information
[debug] Looking for video embeds
WARNING: [generic] aajlu1mnqxsyw2xvdkng: Failed to parse JSON Expecting ',' delimiter: line 1 column 1238 (char 1237)
ERROR: Unsupported URL: https://www.servustv.com/wissen/v/aajlu1mnqxsyw2xvdkng/
Traceback (most recent call last):
  File "/home/db/.local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 1408, in wrapper
    return func(self, *args, **kwargs)
  File "/home/db/.local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 1478, in __extract_info
    ie_result = ie.extract(url)
  File "/home/db/.local/lib/python3.8/site-packages/yt_dlp/extractor/common.py", line 641, in extract
    ie_result = self._real_extract(url)
  File "/home/db/.local/lib/python3.8/site-packages/yt_dlp/extractor/generic.py", line 4039, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.servustv.com/wissen/v/aajlu1mnqxsyw2xvdkng/

**Comment by uahim** [comment]
in-browser solution until someone fixes the extractor; bookmarklets:
https://gist.github.com/uahim/b0c4b43101440b1f1525ef647025a9f2

**Comment by MuenchenSued** [comment]
> in-browser solution until someone fixes the extractor; bookmarklets: https://gist.github.com/uahim/b0c4b43101440b1f1525ef647025a9f2

The booklet is not working any longer. Is there a way to debug it in Firefox?

**Comment by pukkandan** [comment]
The bookmarklet has nothing to do with yt-dlp. Take the discussion about it elsewhere

**Comment by uahim** [comment]
well yt-dlp extractor still doesn't work, right?

@MuenchenSued let's continue this discussion under here then
https://gist.github.com/uahim/b0c4b43101440b1f1525ef647025a9f2

**Comment by chrizilla** [comment]
> The bookmarklet has nothing to do with yt-dlp.

isn't the bookmarklet code potentially helpful to fix the extractor ?

**Comment by pukkandan** [comment]
I don't mind posting relevant third party tools here, but this issue is not the place to provide support for the tool
