### ISSUE TITLE
--batch-file needed a blank line between each file before it worked

### ISSUE THREAD

**Issue by Catman-232** [yt-dlp/yt-dlp#10776]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I made the list as you would expect to, but it kept giving me the "You must provide at least one URL." error. The URLs were certainly on their own lines, as the documentation says. I added an extra line between each entry in the list and now it works. Not really a big deal but it was bothering me for a good ten minutes trying to figure out why it wasn't just working, and finding no good information amidst lots of people making .bat files instead.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by grqz** [comment]
> but it kept giving me the "You must provide at least one URL." error.

Please try to reproduce it and provide a verbose output. A batch file without an extra line between URLs works for me.

**Comment by Grub4K** [comment]
Alternatively, upload the file that failed here so we can inspect it

**Comment by Catman-232** [comment]
I think it must have been Notepad++ being weird about the links pasting because I can't recreate the error after removing the empty lines, and after making a new txt file entirely it isn't having trouble either. No idea why, just my rotten luck while I was putting together the output template I guess. Sorry to bother you.
