### ISSUE TITLE
How can i automatically download all audio  lanugages without having to specify lauanages

### ISSUE THREAD

**Issue by solomoncyj** [yt-dlp/yt-dlp#10797]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

usually, to get multiple luanges, we must append 
```
-f "bestvideo+ba[language=en]+ba[language=jp]+..."  --audio-multistreams
```
this requires us to know that the video has multiple audio languages beforehand and we need to find out what lanagaes there are. is there a way to skip all that, and have yt-dlp turn the file into a mkv automatically and download all audio languages and embed them?

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
`-f "bv+mergeall[vcodec=none]"`
