### ISSUE TITLE
missing components in windows

### ISSUE THREAD

**Issue by bradwww** [yt-dlp/yt-dlp#10793]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

program seems to be missing some other windows programs that it needs to run - error is:
'list' is not recognized as an internal or external command, operable program or batch file.
'pp' is not recognized as an internal or external command, operable program or batch file.
it seems to expect those programs to exist - where can i find them please?
command i run is:
yt-dlp -vU https://www.youtube.com/watch?v=SmrC6W5IgCU&list=PLJaQinSyQ7Tc2P7sRES6lae3x2tkzSp3n
thanks

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.youtube.com/watch?v=SmrC6W5IgCU']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.08.06 from yt-dlp/yt-dlp [4d9231208] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.07.04, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1830 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.08.06 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.08.06 from yt-dlp/yt-dlp)
[youtube] Extracting URL: https://www.youtube.com/watch?v=SmrC6W5IgCU
[youtube] SmrC6W5IgCU: Downloading webpage
[youtube] SmrC6W5IgCU: Downloading ios player API JSON
[youtube] SmrC6W5IgCU: Downloading web creator player API JSON
[debug] Loading youtube-nsig.53afa3ce from cache
[debug] [youtube] Decrypted nsig 2rdGblEAcM1zz-sJU => FcDuPJSM9Lp5Jg
[youtube] SmrC6W5IgCU: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
WARNING: ffmpeg not found. The downloaded format may not be the best available. Installing ffmpeg is strongly recommended: https://github.com/yt-dlp/yt-dlp#dependencies
[debug] Default format spec: best/bestvideo+bestaudio
[info] SmrC6W5IgCU: Downloading 1 format(s): 18
[debug] Invoking http downloader on "https://rr5---sn-i3co-i3bed.googlevideo.com/videoplayback?expire=1724066582&ei=ttbCZpnLEMn12roPz6WT2AY&ip=59.148.173.120&id=o-AAOCFjR4zTyqbE9ahtSYBIdN84J8CJ_Fg7Ei6XGgy8ru&itag=18&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=zA&mm=31%2C29&mn=sn-i3co-i3bed%2Csn-i3b7knse&ms=au%2Crdu&mv=m&mvi=5&pl=20&initcwndbps=1890000&bui=AQmm2ezTjGMJtE7OngF-Q90GvKOE90WgWcz2o1aPRvt0FBJEbBZ9ZLj7gKi42YxwXqZjzIVsdKDZO3HX&spc=Mv1m9m7OpZu-kW3JgzHOhtBb66rez1zl0IwOR20nnKUafd03HEbIvZM&vprv=1&svpuc=1&mime=video%2Fmp4&ns=YX3zvOSfM3yaTQpm7yNgiKQQ&rqh=1&cnr=14&ratebypass=yes&dur=468.067&lmt=1697442090948633&mt=1724044638&fvip=3&c=WEB_CREATOR&sefc=1&txp=4438434&n=FcDuPJSM9Lp5Jg&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cbui%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cns%2Crqh%2Ccnr%2Cratebypass%2Cdur%2Clmt&sig=AJfQdSswRQIhAJggpsxSNmSlXqbpeARLD_NcQhRD03p44HTcidEvI1YJAiA3ugNR4K3pPJlAin6Z1qoqS_UxnErywBHfkxZmV7H5Pw%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AGtxev0wRAIgdoVkldj56eNipu6dQXQVkjiPaL4DMg0x-cd0s3qtevoCIAHTDnei82_brNzcAJfFrYDs5xA5uEEHq445_A8bSsRc"
[download] How To Be Funny - Easily Visualized [SmrC6W5IgCU].mp4 has already been downloaded
[download] 100% of   11.14MiB
'list' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by bashonly** [comment]
quote the URL

**Comment by bradwww** [comment]
> quote the URL

https://www.youtube.com/watch?v=SmrC6W5IgCU&list=PLJaQinSyQ7Tc2P7sRES6lae3x2tkzSp3n
the url of the playlist right?

**Comment by bashonly** [comment]
yes. if you don't quote the URL, your shell will split the command at each `&`

**Comment by bradwww** [comment]
oh you mean put the URL in quotes??

**Comment by bashonly** [comment]
yeah

**Comment by bradwww** [comment]
thanks for getting me downloading - much appreciated!

any idea if this warning is important?

[youtube:tab] PLJaQinSyQ7Tc2P7sRES6lae3x2tkzSp3n page 1: Downloading API JSON
WARNING: [youtube:tab] Incomplete data received. Retrying (1/3)...
[youtube:tab] PLJaQinSyQ7Tc2P7sRES6lae3x2tkzSp3n page 1: Downloading API JSON
WARNING: [youtube:tab] Incomplete data received. Retrying (2/3)...
[youtube:tab] PLJaQinSyQ7Tc2P7sRES6lae3x2tkzSp3n page 1: Downloading API JSON
WARNING: [youtube:tab] Incomplete data received. Retrying (3/3)...
[youtube:tab] PLJaQinSyQ7Tc2P7sRES6lae3x2tkzSp3n page 1: Downloading API JSON
WARNING: [youtube:tab] Incomplete data received. Giving up after 3 retries
[youtube:tab] Playlist x: Downloading 100 items of 100

thanks

**Comment by bashonly** [comment]
@bradwww that's expected with youtube playlists. nothing to worry about

**Comment by bradwww** [comment]
thanks much. i checked the doc and cannot find an easy way to choose the quality level - the video downloads are too large for my phone - can you refer me to a page that describes the formats available and how to choose one? i searched the doc for DVD, 640x480 and such and came up empty - thanks so much for your help so far!

**Comment by bradwww** [comment]
that is awesome - thanks! so even if it does not find 720 it will
still download whatever is there? thanks!

On Wed, Aug 21, 2024 at 2:49 AM bashonly ***@***.***> wrote:
>
> you can use the -S to sort formats by resolution, e.g. passing -S res:720 will make yt-dlp consider 720p resolution formats as the "best" formats and select them by default
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.Message ID: ***@***.***>



-- 
Brad Waddell, Managing Director, FLEXquarters.com Limited
SMS: +1 702-350-1461 Skype/Telegram/Google/Wechat: bradwww

**Comment by bradwww** [comment]
could not get the command to work - any tips:
yt-dlp -P -S res:720 "C:\Users\bradw\OneDrive\__TV\Mobile\youtube"
"https://youtube.com/playlist?list=PLJaQinSyQ7Tc2P7sRES6lae3x2tkzSp3n&si=nNVctLHOgFBIHX_3"
ERROR: [generic] 'res:720' is not a valid URL. Set --default-search
"ytsearch" (or run  yt-dlp "ytsearch:res:720" ) to search YouTube

thanks

On Wed, Aug 21, 2024 at 6:21 PM Brad ***@***.***> wrote:
>
> that is awesome - thanks! so even if it does not find 720 it will
> still download whatever is there? thanks!
>
> On Wed, Aug 21, 2024 at 2:49 AM bashonly ***@***.***> wrote:
> >
> > you can use the -S to sort formats by resolution, e.g. passing -S res:720 will make yt-dlp consider 720p resolution formats as the "best" formats and select them by default
> >
> > —
> > Reply to this email directly, view it on GitHub, or unsubscribe.
> > You are receiving this because you were mentioned.Message ID: ***@***.***>
>
>
>
> --
> Brad Waddell, Managing Director, FLEXquarters.com Limited
> SMS: +1 702-350-1461 Skype/Telegram/Google/Wechat: bradwww



-- 
Brad Waddell, Managing Director, FLEXquarters.com Limited
SMS: +1 702-350-1461 Skype/Telegram/Google/Wechat: bradwww

**Comment by bradwww** [comment]
ok i put the new options at the end - separate from the other options
and it worked - thanks!

On Wed, Aug 21, 2024 at 6:30 PM Brad ***@***.***> wrote:
>
> could not get the command to work - any tips:
> yt-dlp -P -S res:720 "C:\Users\bradw\OneDrive\__TV\Mobile\youtube"
> "https://youtube.com/playlist?list=PLJaQinSyQ7Tc2P7sRES6lae3x2tkzSp3n&si=nNVctLHOgFBIHX_3"
> ERROR: [generic] 'res:720' is not a valid URL. Set --default-search
> "ytsearch" (or run  yt-dlp "ytsearch:res:720" ) to search YouTube
>
> thanks
>
> On Wed, Aug 21, 2024 at 6:21 PM Brad ***@***.***> wrote:
> >
> > that is awesome - thanks! so even if it does not find 720 it will
> > still download whatever is there? thanks!
> >
> > On Wed, Aug 21, 2024 at 2:49 AM bashonly ***@***.***> wrote:
> > >
> > > you can use the -S to sort formats by resolution, e.g. passing -S res:720 will make yt-dlp consider 720p resolution formats as the "best" formats and select them by default
> > >
> > > —
> > > Reply to this email directly, view it on GitHub, or unsubscribe.
> > > You are receiving this because you were mentioned.Message ID: ***@***.***>
> >
> >
> >
> > --
> > Brad Waddell, Managing Director, FLEXquarters.com Limited
> > SMS: +1 702-350-1461 Skype/Telegram/Google/Wechat: bradwww
>
>
>
> --
> Brad Waddell, Managing Director, FLEXquarters.com Limited
> SMS: +1 702-350-1461 Skype/Telegram/Google/Wechat: bradwww



-- 
Brad Waddell, Managing Director, FLEXquarters.com Limited
SMS: +1 702-350-1461 Skype/Telegram/Google/Wechat: bradwww
