### ISSUE TITLE
I created a new account and used its cookies in the api and it got blocked.

### ISSUE THREAD

**Issue by yourshaxzod** [yt-dlp/yt-dlp#10792]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I created a new account and used its cookies in the api and it got blocked, how can I keep it from being blocked

### Provide verbose output that clearly demonstrates the problem

- [x] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

![image](https://github.com/user-attachments/assets/d94ae5ae-dcc8-41fa-97b9-01f3a70f8eb5)

**Comment by grqz** [comment]
I don't think there's anything we can do to get your account back. And the ban may not be directly related to passing cookies. A normal account ban caused by passing cookies is just temporary and lasts for only several months.

**Comment by yourshaxzod** [comment]
> I don't think there's anything we can do to get your account back. And the ban may not be directly related to passing cookies. A normal account ban caused by passing cookies is just temporary and lasts for only several months.

how can i use yt-dlp without thread blocks

**Comment by grqz** [comment]
Setting cookies or using oauth will get your account banned.

> btw it should be noted that if you're getting the "sign in you bot" error and you start passing cookies or oauth, it's only a matter of time until youtube bans your account too
> don't use your personal account
\- bashonly


Wait until #10648 is merged so that you can use po-Token instead.

**Comment by yourshaxzod** [comment]
> Cookie-fayllarni o'rnatish yoki oauth-dan foydalanish, bir necha marta yuklab olingandan so'ng, hisobingiz bloklanadi.
> 
> Eslatma
> 
> Shuni ta'kidlash kerakki, agar siz "botingizga kiring" xatosiga yo'l qo'ysangiz va siz cookie-fayllarni yoki oauthni o'tkazishni boshlasangiz, YouTube sizning hisobingizni taqiqlaguncha, bu vaqt masalasidir, shaxsiy hisobingizdan foydalanmang - bashonly
> 
> #10648 birlashtirilguncha kuting , shunda siz po-Token o'rniga foydalanishingiz mumkin.

Thank you very much for your help

**Comment by Elite** [comment]
> Wait until #10648 is merged so that you can use po-Token instead.
I tested the `potoken` branch and it seems that got blocked as well after some time for my ip.
