### ISSUE TITLE
bash_completion.d is deprecated

### ISSUE THREAD

**Issue by hseg** [yt-dlp/yt-dlp#108]
- [x] I'm reporting a feature request
- [x] I've verified that I'm running yt-dlp version **2021.02.19**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description

See <https://github.com/scop/bash-completion/blob/master/README.md>, specifically in re the question "I author/maintain package X". The recommended way is to get the path from `bash-completion` by putting
```
PKG_CHECK_VAR(bashcompdir, [bash-completion], [completionsdir], ,
  bashcompdir="${sysconfdir}/bash_completion.d")
AC_SUBST(bashcompdir)
```
in `configure.ac and
```
bashcompdir = @bashcompdir@
dist_bashcomp_DATA = # completion files go here
```
in `Makefile.am`.
In particular, this means `yt-dlp`'s completion will be loaded just-in-time, decreasing the memory footprint.
Similarly, `fish` [wants](https://fishshell.com/docs/current/index.html) its completions placed at `$(pkg-config --variable completionsdir fish)`, so a similar logic as the above works for it.

These default to `/usr/share/bash-completion/completions/` and `/usr/share/fish/vendor_completions.d/`, in case having `pkg-config` look for the locations is not an option.

**Comment by pukkandan** [comment]
I have no idea how these work. Can u make a PR?

**Comment by hseg** [comment]
Can write a PR for the hardcoded versions, am unsure that using pkg-config won't make the build dependent on having the relevant packages installed, checking
