### ISSUE TITLE
since today youtube videos take ~2 minutes to start with mpv+yt-dlp(nightly)

### ISSUE THREAD

**Issue by geextahslex** [yt-dlp/yt-dlp#10802]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Germany

### Provide a description that is worded well enough to be understood

since today youtube video playback with mpv+yt-dlp(nightly) takes about 2 minutes (1:50)
here you can see, that it takes 104 seconds to start

I made also an issue on mpv, you can see it here https://github.com/mpv-player/mpv/issues/14712

```
[   1.286][d][cplayer] Run command: subprocess, flags=64, args=[args="yt-dlp,--no-warnings,-J,--flat-playlist,--sub-format,ass/srt/best,--format,bestvideo+bestaudio/best,--all-subs,--no-playlist,--,https://www.youtube.com/watch?v=xmJUZgQ5HpQ", playback_only="yes", capture_size="67108864", capture_stdout="yes", capture_stderr="yes", detach="no", env="", stdin_data="", passthrough_stdin="no"]
[ 105.265][v][ytdl_hook] Found youtube-dl with path yt-dlp in PATH
[ 105.269][v][ytdl_hook] youtube-dl succeeded!
[ 105.269][d][ytdl_hook] ytdl parsing took 103.984 seconds
```

it would be nice if that could be fixed as it was before. a video used to start playback in about 5-7 seconds
Thank you :)

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.youtube.com/watch?v=TAJHIcAJrcs']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.08.19.232821 from yt-dlp/yt-dlp-nightly-builds [f0bb28504] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 6.1.1-full_build-www.gyan.dev (setts), ffprobe 6.1.1-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.07.04, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1830 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.08.19.232821 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.08.19.232821 from yt-dlp/yt-dlp-nightly-builds)
[youtube] Extracting URL: https://www.youtube.com/watch?v=TAJHIcAJrcs
[youtube] TAJHIcAJrcs: Downloading webpage
[youtube] TAJHIcAJrcs: Downloading ios player API JSON
[youtube] TAJHIcAJrcs: Downloading web creator player API JSON
[debug] Loading youtube-nsig.43bc9526 from cache
[debug] [youtube] Decrypted nsig DV4AFMcavfkUZnQ7ALz => IU6VG8ZqStNkGw
[youtube] TAJHIcAJrcs: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] Testing format 616
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 80
[download] Destination: C:\Users\Deep\tmp138egvw3.tmp
[debug] File locking is not supported. Proceeding without locking
[download] 100% of    712.00B in 00:00:20 at 35.15B/s
[info] TAJHIcAJrcs: Downloading 1 format(s): 616+251
[debug] Invoking hlsnative downloader on "https://manifest.googlevideo.com/api/manifest/hls_playlist/expire/1724182427/ei/O5vEZv_0CZm56dsPqO610Aw/ip/89.14.4.227/id/4c024721c009adcb/itag/616/source/youtube/requiressl/yes/ratebypass/yes/pfa/1/wft/1/sgovp/clen%3D29021214%3Bdur%3D531.130%3Bgir%3Dyes%3Bitag%3D356%3Blmt%3D1724101662079720/rqh/1/hls_chunk_host/rr3---sn-uxax4vopj5qx-cxgs.googlevideo.com/xpc/EgVo2aDSNQ%3D%3D/mh/Uo/mm/31,29/mn/sn-uxax4vopj5qx-cxgs,sn-i5heen7d/ms/au,rdu/mv/m/mvi/3/pl/18/gcr/de/initcwndbps/1122500/vprv/1/playlist_type/DVR/dover/13/txp/5532434/mt/1724160332/fvip/1/short_key/1/keepalive/yes/sparams/expire,ei,ip,id,itag,source,requiressl,ratebypass,pfa,wft,sgovp,rqh,xpc,gcr,vprv,playlist_type/sig/AJfQdSswRQIhAPIXckKzRe0abXQdgEB9qTj2HLvNtFw5HRUCQltfnkkKAiBwa2pTPBdRBcVHaIZq59eg7V8HNlPN6TNbeb9ubUkE7A%3D%3D/lsparams/hls_chunk_host,mh,mm,mn,ms,mv,mvi,pl,initcwndbps/lsig/AGtxev0wRQIgdvB2Wnl5-xNwARtAwAXDHPFlMVXcdTk8D2IrVJ-sks8CIQD5oJWGe2PEgSsgazJsu2JvMgA-EE2ApuA0bVRhn-tlAg%3D%3D/playlist/index.m3u8"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 80
[download] Destination: Dragon Ball Super News Update： Toyotaro is now SOLE Creator？ [TAJHIcAJrcs].f616.mp4
[download] 100% of   27.77MiB in 00:00:09 at 2.94MiB/s
[debug] Invoking http downloader on "https://rr3---sn-uxax4vopj5qx-cxgs.googlevideo.com/videoplayback?expire=1724182427&ei=O5vEZv_0CZm56dsPqO610Aw&ip=89.14.4.227&id=o-APC64VewBJR-9Tu0RnuneodSfCGI3pje77EP75Rh-8-O&itag=251&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=Uo&mm=31%2C29&mn=sn-uxax4vopj5qx-cxgs%2Csn-i5heen7d&ms=au%2Crdu&mv=m&mvi=3&pl=18&gcr=de&initcwndbps=1122500&vprv=1&svpuc=1&mime=audio%2Fwebm&rqh=1&gir=yes&clen=7374149&dur=531.141&lmt=1724100323857391&mt=1724160332&fvip=1&keepalive=yes&c=IOS&txp=5532434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cgcr%2Cvprv%2Csvpuc%2Cmime%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRQIgYf2JFLjsIDcGi9ElFTL-KVlZgQEjf6rSfiO7doTNOxICIQDeZawvkHBGj999wTtFFTSrmTuwz_oSPUQ4mBC7_P-YOA%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AGtxev0wRQIgFB1yYcuBmcMGFuPpbO0DKzDDhT5ADx2jBljsSXch2AwCIQDxO359hUfdc78sZovDQUTu9xZdpwikbW5Zw2RPqJllyA%3D%3D"
[download] Destination: Dragon Ball Super News Update： Toyotaro is now SOLE Creator？ [TAJHIcAJrcs].f251.webm
[download] 100% of    7.03MiB in 00:00:01 at 5.80MiB/s
[Merger] Merging formats into "Dragon Ball Super News Update： Toyotaro is now SOLE Creator？ [TAJHIcAJrcs].webm"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i "file:Dragon Ball Super News Update： Toyotaro is now SOLE Creator？ [TAJHIcAJrcs].f616.mp4" -i "file:Dragon Ball Super News Update： Toyotaro is now SOLE Creator？ [TAJHIcAJrcs].f251.webm" -c copy -map 0:v:0 -map 1:a:0 -movflags +faststart "file:Dragon Ball Super News Update： Toyotaro is now SOLE Creator？ [TAJHIcAJrcs].temp.webm"
Deleting original file Dragon Ball Super News Update： Toyotaro is now SOLE Creator？ [TAJHIcAJrcs].f251.webm (pass -k to keep)
Deleting original file Dragon Ball Super News Update： Toyotaro is now SOLE Creator？ [TAJHIcAJrcs].f616.mp4 (pass -k to keep)
```

**Comment by dirkf** [comment]
I can't repro with stable in Linux (~6s).

Can you show the logs and elapsed times for `yt-dlp -J --flat-playlist --sub-format ass/srt/best --format bestvideo+bestaudio/best --all-subs --no-playlist --verbose -- "https://www.youtube.com/watch?v=xmJUZgQ5HpQ"` with the problem nightly and with the last apparently unproblematic version that you used ?

If the long execution time persists, it would be interesting to see the top running processes at that point. Possibly a deranged (often happens) anti-virus utility is blocking the _yt-dlp_ run, which in your system (`win_exe`) is unzipping executable code each time.

**Comment by geextahslex** [comment]
do you mean this?
[out.txt](https://github.com/user-attachments/files/16677268/out.txt)

**Comment by seproDev** [comment]
What part of the execution takes so long?
Is it startup or the network requests?
If the network requests take long, could you try adding either `-4` or `-6` to your command?

**Comment by geextahslex** [comment]
>What part of the execution takes so long?
Is it startup or the network requests?

I don't know. How do I check this?

**Comment by seproDev** [comment]
You see what line yt-dlp is stuck on for a very long time. Is it not outputting anything for a very long time, or is it stuck on say "Downloading webpage"

**Comment by geextahslex** [comment]
it stucks at `[youtube] TAJHIcAJrcs: Downloading webpage`

**Comment by geextahslex** [comment]
force ipv-4 helped. it seems like I lost ipv-6. thank you.
this is somehow embarrassing ^^'
