### ISSUE TITLE
Offset option for `video_autonumber`

### ISSUE THREAD

**Issue by qtlunya** [yt-dlp/yt-dlp#10806]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

A while back, `video_autonumber` was added to the output template so that auto-numbering would skip a number in case of failed downloads (i.e., video 2 failing wouldn't cause video 3 to be numbered as video 2). However, `--autonumber-start` seems to have no effect on this. It would be nice to have a `--video-autonumber-start` or similar option for this.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
luna@Lunas-MacBook-Air ~
› /opt/homebrew/opt/yt-dlp/bin/yt-dlp -vU --autonumber-start 10 --print '%(video_autonumber)02d' 'https://www.youtube.com/watch?v=aqz-KE-bpKQ'
[debug] Command-line config: ['-vU', '--autonumber-start', '10', '--print', '%(video_autonumber)02d', 'https://www.youtube.com/watch?v=aqz-KE-bpKQ']
[debug] User config "/Users/Luna/.config/yt-dlp/config": ['--downloader', 'aria2c', '-N', '16', '--no-check-certificate', '-S', 'ext:mp4:m4a']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.08.06 from yt-dlp/yt-dlp [4d9231208] (pip)
[debug] Python 3.12.4 (CPython arm64 64bit) - macOS-14.6.1-arm64-arm-64bit (OpenSSL 3.3.1 4 Jun 2024)
[debug] exe versions: ffmpeg 7.0.2 (setts), ffprobe 7.0.2, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.07.04, mutagen-1.47.0, requests-2.32.3, sqlite3-3.46.0, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1830 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.08.06 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.08.06 from yt-dlp/yt-dlp)
[youtube] Extracting URL: https://www.youtube.com/watch?v=aqz-KE-bpKQ
[youtube] aqz-KE-bpKQ: Downloading webpage
[youtube] aqz-KE-bpKQ: Downloading ios player API JSON
[youtube] aqz-KE-bpKQ: Downloading web creator player API JSON
[debug] Loading youtube-nsig.43bc9526 from cache
[debug] [youtube] Decrypted nsig 3vm5fLsBQsAVMpafSsH => BhpfgIM-_3uFQA
[debug] Loading youtube-nsig.43bc9526 from cache
[debug] [youtube] Decrypted nsig rRF3aTYGhaeB0Rjz-3K => S1t6R9JQWA_QKg
[youtube] aqz-KE-bpKQ: Downloading m3u8 information
[debug] Sort order given by user: ext:mp4:m4a
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, vext:mp4(6), aext:m4a(8), quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] aqz-KE-bpKQ: Downloading 1 format(s): 628+258
01

luna@Lunas-MacBook-Air ~
› /opt/homebrew/opt/yt-dlp/bin/yt-dlp -vU --video-autonumber-start 10 --print '%(video_autonumber)02d' 'https://www.youtube.com/watch?v=aqz-KE-bpKQ'
[debug] Command-line config: ['-vU', '--video-autonumber-start', '10', '--print', '%(video_autonumber)02d', 'https://www.youtube.com/watch?v=aqz-KE-bpKQ']
[debug] User config "/Users/Luna/.config/yt-dlp/config": ['--downloader', 'aria2c', '-N', '16', '--no-check-certificate', '-S', 'ext:mp4:m4a']

Usage: yt-dlp [OPTIONS] URL [URL...]

yt-dlp: error: no such option: --video-autonumber-start
```

**Comment by bashonly** [comment]
`--autonumber-start` is a [deprecated option and not recommended](https://github.com/yt-dlp/yt-dlp?tab=readme-ov-file#not-recommended). The README gives this preferred alternative:

```
--autonumber-start NUMBER        Use internal field formatting like %(autonumber+NUMBER)s
```

so for the equivalent of `--video-autonumber-start 10` you would use `%(video_autonumber+10)02d`

**Comment by qtlunya** [comment]
Thanks, I didn't see that.
