### ISSUE TITLE
Add `playlist_webpage_url` field

### ISSUE THREAD

**Issue by zaednasr** [yt-dlp/yt-dlp#10827]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Europe

### Provide a description that is worded well enough to be understood

Sample channel url: [https://www.youtube.com/@KaneB](https://www.youtube.com/@KaneB)

Sample command
`yt-dlp -I 13:13 https://www.youtube.com/@KaneB`

Nothing downloads, even though when you print the item data with -j there is playlist index and playlist name present

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [x] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '-I', '14:14', 'https://www.youtube.com/@KaneB']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.08.21.232751 from yt-dlp/yt-dlp-nightly-builds [6f9e65374] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22631-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 6.0-full_build-www.gyan.dev (setts), ffprobe 6.0-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.07.04, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.2, websockets-13.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1830 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.08.21.232751 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.08.21.232751 from yt-dlp/yt-dlp-nightly-builds)
[youtube:tab] Extracting URL: https://www.youtube.com/@KaneB
[youtube:tab] @KaneB: Downloading webpage
[debug] [youtube:tab] Selected tab: 'videos' (videos), Requested tab: ''
[youtube:tab] Downloading all uploads of the channel. To download only the videos in a specific tab, pass the tab's URL
[youtube:tab] @KaneB/streams: Downloading webpage
[debug] [youtube:tab] Selected tab: 'streams' (live), Requested tab: 'streams'
[youtube:tab] Downloading as multiple playlists, separated by tabs. To download as a single playlist instead, pass https://www.youtube.com/playlist?list=UUGVHC4L6gjS13AMe-JMOjHg
[download] Downloading playlist: Kane B
[youtube:tab] Playlist Kane B: Downloading 0 items of 2
[download] Finished downloading playlist: Kane B
```

**Comment by bashonly** [comment]
did you mean to do `yt-dlp -I 13:13 https://www.youtube.com/@KaneB/videos` ?

**Comment by teddysulaimanGL** [comment]
Hm, I think he's looking for a better way to obtain the "playlist_channel_url" beforehand

**Comment by zaednasr** [comment]
@bashonly  Well none of the indexes work anyway. I tried both 13 and 14. 
This issue doesnt happen if im using a normal playlist url. Only on a channel url.

**Comment by seproDev** [comment]
The comment from bashonly wasn't about the index passed, but the URL passed. You are passing a channel URL, which is a playlist of playlists for which `-I` is not great with.
If you want to download the 13th video (currently [0MgXcih4gCM](https://www.youtube.com/watch?v=0MgXcih4gCM)) you need to pass `https://www.youtube.com/@KaneB/videos` as the URL.

**Comment by teddysulaimanGL** [comment]
As far as I can understand, he wants to process the entire content of that channel, so by specifying the tab, I assume it means it wouldn't process streams?

**Comment by seproDev** [comment]
@teddysulaimanGL I don't get that at all, reading the original message. If the author meant something else, they can explain so themselves.

**Comment by zaednasr** [comment]
@seproDev This is tricky. My usecase of yt-dlp is an android app where the user provides the url.
It can process each item individually and that works fine but also the app can use the playlist url and use indexing to take advantage of playlist metadata to embed it the file.

It wouldnt be good practice to just hard code the case where a youtube video is a channel url and i manually modify the url to add /videos in it.
Because yt-dlp supports 1000 websites, other sites could have a different url structure.

**Comment by bashonly** [comment]
The user should pass the /videos URL ?

**Comment by zaednasr** [comment]
Of course but considering most users are not tech savy, they simply share the channel url from youtube and throw it in the app to handle it

**Comment by teddysulaimanGL** [comment]
> @teddysulaimanGL I don't get that at all, reading the original message. If the author meant something else, they can explain so themselves.

I understand. I know he didn't explicitly mention that, but that's what he wants

**Comment by seproDev** [comment]
I still have trouble fully understanding what you are trying to archive. I am not familiar with how your app interacts with yt-dlp, so help me out here.
Your users pass a channel URL. You now fetch that channel URL with yt-dlp, which returns a playlist consisting of two entries. The first is the Videos tab and the second is the Streams tab. Why should passing `-I 13` download a video?

**Comment by zaednasr** [comment]
- user passes channel url
- app uses -j --flat-playlist to get general data about the items and shows them as results
- user selects which to download
- app uses indexing to download them based on playlist index that is present in the json data from -j

**Comment by teddysulaimanGL** [comment]
Let me help. Since yt-dlp recognizes the channel as tabs, then I guess the index is irrelevant, and therefore returns no results. By specifying the tab, it means we have to choose either streams or videos, right? But he wants to process all the contents as one, so it means to process the entire content of all tabs (Shorts, streams, videos) as one playlist

**Comment by teddysulaimanGL** [comment]
> As far as I can understand, he wants to process the entire content of that channel, so by specifying the tab, I assume it means it wouldn't process streams?

And therefore, it leads to this question again

**Comment by teddysulaimanGL** [comment]
> Hm, I think he's looking for a better way to obtain the "playlist_channel_url" beforehand

And therefore, it leads to this question again

**Comment by zaednasr** [comment]
If i fetch the data using -J instead of -j, i can get the tab structure you are talking about, but still even there yt-dlp doesnt provide the tab url that i can use.

**Comment by seproDev** [comment]
Okay I think I now understand the problem you are running in to.
I agree that a `playlist_url` key would probably make sense, but I don't quite yet get why you fetch the playlist again in the first place. Couldn't you just use the `url` key already extracted?

**Comment by teddysulaimanGL** [comment]
> …why you fetch the playlist again in the first place. Couldn't you just use the `url` key already extracted?

The reason is to extract the items metadata and the index, so that the app user can choose the items to download

**Comment by zaednasr** [comment]
If i use the playlist url instead of url, the app can take advantage of playlist metadata for the downloaded files. This is user configurable and the user can swap to use normal url instead.
So technically this can be avoided but also with the side effect of losing metadata info.

**Comment by seproDev** [comment]
But that info is already present from the first extraction of the playlist, no?
Extracting the playlist twice will imo. only lead to problems with generating more traffic, leading to IP bans, or causing inconsistencies if the playlist changes in between extractions.

**Comment by seproDev** [comment]
Ah or I guess you want to support the use of playlist_ variables in the output template?

**Comment by zaednasr** [comment]
Yes you are correct, output templates can take advantage of the playlist variables.
Also the app when parsing the playlist does a flat playlist query, so just barebones info to show to the user and not full fetch one by one because that would be horribly slow, in big playlists.

Metadata and output template come into play in the download process when a full fetch is done.
Also playlist changing between extractions is highly unlikely, realistically speaking assuming the user will hit download as soon as he gets the results back

**Comment by teddysulaimanGL** [comment]
> But that info is already present from the first extraction of the playlist, no?

Well, it's just that, the app needs to know the metadata and index for the "results card", and if the items URL instead of playlist URL preference is enabled, then the app would need to know the individual URL, as Zaed said

> Extracting the playlist twice will imo. only lead to problems with generating more traffic, leading to IP bans, or causing inconsistencies if the playlist changes in between extractions.

Unfortunately, yes, but maybe it needs to be done anyway

**Comment by teddysulaimanGL** [comment]
> Ah or I guess you want to support the use of playlist_ variables in the output template?

I guess the one that I particularly mentioned

**Comment by bashonly** [comment]
Possibly relevant: As mentioned by sepro above, a YouTube channel URL is a playlist of playlists: a `videos` tab, `streams` tab, and `shorts` tab, with each tab being a nested playlist of videos. It's not possible to specify different playlist indices for each level of nesting via the CLI options as they are currently implemented. There is an open feature request to improve handling of nested playlists, see #5648

**Comment by seproDev** [comment]
The only thing I could come up with that would prevent double extraction and keep the playlist metadata is the following:
- Extract flat playlist
- Have user select video
- Extract video to json by `url` key
- Merge two dicts manually outside (just take all keys starting with `playlist` from the inital dict)
- Load full info json again in to yt-dlp with `--load-info-json`

**Comment by zaednasr** [comment]
@bashonly yes with -J i can access the playlist of playlists but there isnt a playlist_url present in the json. Because if i could access the playlist url, i could manage the results and use the appropriate playlist urls and use their indexes no problem, instead of trying to use a global index.

**Comment by zaednasr** [comment]
> The only thing I could come up with that would prevent double extraction and keep the playlist metadata is the following:
> 
> * Extract flat playlist
> * Have user select video
> * Extract video to json by `url` key
> * Merge two dicts manually outside (just take all keys starting with `playlist` from the inital dict)
> * Load full info json again in to yt-dlp with `--load-info-json`

Good luck trying to do that process with really big playlists.
Its easier to just know that a playlist can provide an index and have -I working and run without overloading the phone.
Playlists could span 4000 items.

**Comment by seproDev** [comment]
> Good luck trying to do that process with really big playlists.

Hmm, I wouldn't expect it to be that bad. You already need to parse the entire flat playlist JSON. Is parsing a single JSON file before each download and adding a couple of keys really too compute intensive? I guess I don't know how high your overhead of calling yt-dlp twice is. I assume you only have access to the CLI and not the python API?

**Comment by seproDev** [comment]
Regarding adding `playlist_url` that seems a bit more complex than just adding a new field. We are investigating.

**Comment by zaednasr** [comment]
as long as there is a field that shows this playlist of playlist is "https://channelurl/video" or "channelurl/shorts" or whatever the url is supposed to be thats all i need. Because with those -I works.

Thank you.
