### ISSUE TITLE
[RumbleChannel] rumble channel URLs broken as of today

### ISSUE THREAD

**Issue by xaeiougit** [yt-dlp/yt-dlp#10833]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Netherlands

### Provide a description that is worded well enough to be understood

As of this morning, "yt-dlp https://rumble.com/c/russellbrand --playlist-items 1-2" fails to download any videos.

As with an earlier issue #8782, yt-dlp instead tries to grab ALL pages - if "/user/" is used instead of "/c/" in the channel URL the result is the same.   

I tried other Rumble channels and the result is also the same.

UPDATE: - if I remove "--playlist-items", still no videos are downloaded, so I think channel download is not working at all.

Maybe a new URL format needs to be used? 

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://rumble.com/c/russellbrand', '--playlist-items', '1-2']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8 (No ANSI), error utf-8 (No ANSI), screen utf-8 (No ANSI)
[debug] yt-dlp version nightly@2024.08.21.232751 from yt-dlp/yt-dlp-nightly-builds [6f9e65374] (zip)
[debug] Python 3.10.12 (CPython x86_64 64bit) - Linux-6.5.0-44-generic-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.11.0, brotli-1.0.9, certifi-2020.06.20, mutagen-1.45.1, pyxattr-0.7.2, requests-2.25.1, secretstorage-3.3.1, sqlite3-3.37.2, urllib3-1.26.5, websockets-9.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Loaded 1830 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.08.21.232751 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.08.21.232751 from yt-dlp/yt-dlp-nightly-builds)
[RumbleChannel] Extracting URL: https://rumble.com/c/russellbrand
[download] Downloading playlist: russellbrand
[RumbleChannel] russellbrand: Downloading page 1
[RumbleChannel] russellbrand: Downloading page 2
[RumbleChannel] russellbrand: Downloading page 3
[RumbleChannel] russellbrand: Downloading page 4
[RumbleChannel] russellbrand: Downloading page 5
[RumbleChannel] russellbrand: Downloading page 6

# Additional pages removed for brevity

[RumbleChannel] russellbrand: Downloading page 78
[RumbleChannel] russellbrand: Downloading page 79
[RumbleChannel] russellbrand: Downloading page 80
[RumbleChannel] Playlist russellbrand: Downloading 0 items
[download] Finished downloading playlist: russellbrand
```

**Comment by NielsMayer** [comment]
I too noticed this issue sprang-up recently: https://x.com/NielsMayer/status/1827119886864453671 :-) 

I was able to work-around this issue for "pro" channels that have an RSS-feed feature.

e.g. for Russell Brand, use https://openrss.org/rumble.com/russellbrand

However, non-pro channels fail because they lack an RSS feed, for example, 

https://openrss.org/rumble.com/TheLastAmericanVagabond (for https://rumble.com/user/TheLastAmericanVagabond )

**Comment by xaeiougit** [comment]
> https://openrss.org/rumble.com/russellbrand

Thanks for that!  Yes, that works great if you're trying to scoop up the recent videos  e.g. in a nightly script, as I am.

But for anyone wanting to download an entire channel, then for the moment they are out of luck.

**Comment by bashonly** [comment]
really simple fix:
```diff
diff --git a/yt_dlp/extractor/rumble.py b/yt_dlp/extractor/rumble.py
index db780a2cf..6f94d8833 100644
--- a/yt_dlp/extractor/rumble.py
+++ b/yt_dlp/extractor/rumble.py
@@ -382,7 +382,7 @@ def entries(self, url, playlist_id):
                 if isinstance(e.cause, HTTPError) and e.cause.status == 404:
                     break
                 raise
-            for video_url in re.findall(r'class="[^>"]*videostream__link[^>]+href="([^"]+\.html)"', webpage):
+            for video_url in re.findall(r'class="[^>"]*videostream__link[^>]+href="([^"]+\.html)', webpage):
                 yield self.url_result('https://rumble.com' + video_url)
 
     def _real_extract(self, url):
```

but a better fix would be to make this more robust by using the `get_elements_html_by_class` and `extract_attributes` utils functions:

```diff
diff --git a/yt_dlp/extractor/rumble.py b/yt_dlp/extractor/rumble.py
index db780a2cf..74c7e4f17 100644
--- a/yt_dlp/extractor/rumble.py
+++ b/yt_dlp/extractor/rumble.py
@@ -8,14 +8,17 @@
     UnsupportedError,
     clean_html,
     determine_ext,
+    extract_attributes,
     format_field,
     get_element_by_class,
+    get_elements_html_by_class,
     int_or_none,
     join_nonempty,
     parse_count,
     parse_iso8601,
     traverse_obj,
     unescapeHTML,
+    urljoin,
 )
 
 
@@ -382,8 +385,10 @@ def entries(self, url, playlist_id):
                 if isinstance(e.cause, HTTPError) and e.cause.status == 404:
                     break
                 raise
-            for video_url in re.findall(r'class="[^>"]*videostream__link[^>]+href="([^"]+\.html)"', webpage):
-                yield self.url_result('https://rumble.com' + video_url)
+            for video_url in traverse_obj(
+                get_elements_html_by_class('videostream__link', webpage), (..., {extract_attributes}, 'href'),
+            ):
+                yield self.url_result(urljoin('https://rumble.com', video_url))
 
     def _real_extract(self, url):
         url, playlist_id = self._match_valid_url(url).groups()
```

**Comment by tony-hn** [comment]
Still no PR for this?

@bashonly - Thanks for the patch. I would be happy to turn it into a PR. The PR checklist asks for the code to be either the work of the PR creator or in the public domain. So I'd need you to put your patch into the public domain to get the PR in.

**Comment by bashonly** [comment]
@tony-hn I am the maintainer who will be reviewing+merging the PR and I will recognize my own patch, you can go ahead

**Comment by tony-hn** [comment]
Thanks, will do. Should have time this weekend.

**Comment by thisisawesome1994** [comment]
So, this was stated as a duplicate? I was talking about livestream tab. This is channel tab. Those are 2 different things. I have been able to download individual videos, so I thought only live streams are broken as of today
