### ISSUE TITLE
Downloading videos from Magoosh GRE/ IELTS premium account

### ISSUE THREAD

**Issue by uncharted-user** [yt-dlp/yt-dlp#10842]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Is it possible to download videos from Magoosh GRE/ IELTS premium account? I can successfully download LinkedIn Learning video playlists by extracting the cookie, which works great, by the way. I wanted to download those videos as I purchased the course, and need to revise some of those now and then. Did anyone try that? For example, I tried the following but getting errors,
```
$ yt-dlp https://gre.magoosh.com/lessons/996-general-introduction
[generic] Extracting URL: https://gre.magoosh.com/lessons/996-general-introduction
[generic] 996-general-introduction: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] 996-general-introduction: Extracting information
ERROR: Unsupported URL: https://gre.magoosh.com/lessons/996-general-introduction

```
### Provide verbose output that clearly demonstrates the problem

- [x] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
```
[debug] Command-line config: ['-vU']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.08.06 from yt-dlp/yt-dlp [4d9231208] (pip)
[debug] Python 3.12.4 (CPython x86_64 64bit) - Linux-6.10.6-200.fc40.x86_64-x86_64-with-glibc2.39 (OpenSSL 3.2.2 4 Jun 2024, glibc 2.39)
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2023.05.07, mutagen-1.47.0, requests-2.32.3, secretstorage-3.3.3, sqlite3-3.45.1, urllib3-1.26.19, websockets-13.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1830 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.08.06 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.08.06 from yt-dlp/yt-dlp)
```
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
what have you tried? why not share a log? are you requesting support to be added? please don't abuse the "question" template

**Comment by uncharted-user** [comment]
> what have you tried? why not share a log? are you requesting support to be added? please don't abuse the "question" template

Sorry, I was trying to know whether it is possible to download from Magoosh or not. I update my questions with what I tried and a log with vU. Unfortunately, I didn't understand the last two check lists. It would have been great to add support for Magoosh video download if currently unavailable. I am very new to this, hence I wanted to know from if anyone did it. I don't have any intention to abuse anything here.

**Comment by bashonly** [comment]
Have you tried [passing cookies to yt-dlp](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp)?

If you would like to make this a site support request, you'll need to add a proper verbose log (add `-vU` to your **download command** where you are passing cookies to yt-dlp). Would you be willing to share your account details? There is almost no chance that anyone will work on this without them. Note that I am not personally asking for your account details, nor am I offering to work on this

**Comment by uncharted-user** [comment]
I tried passing cookies. However, I might end up with a banned account if someone abuse the login information. By the way, thank you for a great CLI downloader. We are grateful.

**Comment by bashonly** [comment]
If you aren't willing to share account details, you could look into using a browser extension such as "The Stream Detector" to help you download the content with yt-dlp

**Comment by uncharted-user** [comment]
> you could look into using a browser extension such as "The Stream Detector" to help you download the content with yt-dlp

Thank you for the alternative solution.
