### ISSUE TITLE
Youtube defaults to 360p no matter parameters specified

### ISSUE THREAD

**Issue by KhaledMahm0vd** [yt-dlp/yt-dlp#10859]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Egypt

### Provide a description that is worded well enough to be understood

Youtube downloads videos in 360p resolution even if i added -S res:720, i have tried both stable yt-dlp version 2024.08.06 & 2024-08-26 nightly and both gives the same result.
I have ffmpeg 7.0 version installed.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-f', 'mp4', '-S', 'res:720', '-vU', '--yes-playlist', 'https://youtu.be/a1iuxFHTJyU']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.08.26.232811 from yt-dlp/yt-dlp-nightly-builds (linux_exe)
[debug] Python 3.11.9 (CPython x86_64 64bit) - Linux-6.9.12-3-MANJARO-x86_64-with (OpenSSL 3.1.6 4 Jun 2024)
[debug] exe versions: ffmpeg 7.0.2 (setts), ffprobe 7.0.2, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.07.04, curl_cffi-0.7.1, mutagen-1.47.0, requests-2.32.3, secretstorage-3.3.3, sqlite3-3.44.2, urllib3-2.2.2, websockets-13.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1831 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
ERROR: Unable to obtain version info (<urllib3.connection.HTTPSConnection object at 0x7caf3975f890>: Failed to resolve 'api.github.com' ([Errno -3] Try again)); Please try again later or visit  https://github.com/yt-dlp/yt-dlp-nightly-builds/releases/latest
[youtube] Extracting URL: https://youtu.be/a1iuxFHTJyU
[youtube] a1iuxFHTJyU: Downloading webpage
[youtube] a1iuxFHTJyU: Downloading ios player API JSON
[youtube] a1iuxFHTJyU: Downloading web creator player API JSON
[debug] Loading youtube-nsig.19828c26 from cache
[debug] [youtube] Decrypted nsig kFbM--pVYCFSGFpuA => xgeyk9GrWjdtIg
[debug] Loading youtube-nsig.19828c26 from cache
[debug] [youtube] Decrypted nsig Q2wWbZ0ZdXt-PvbRM => 1Yfpyi3p9-VT7w
[youtube] a1iuxFHTJyU: Downloading m3u8 information
[debug] Sort order given by user: res:720
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, res:720(720.0), quality, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[info] a1iuxFHTJyU: Downloading 1 format(s): 18
[debug] Invoking http downloader on "https://rr4---sn-xupn5a5uxbt-j5pr.googlevideo.com/videoplayback?expire=1724772771&ei=Q53NZoXBMbGcp-oPmZzbuA4&ip=62.114.229.184&id=o-AP6PoKRDSymOoK8Ous_XLeT7hcfzjS8z48Fc5Dbo323W&itag=18&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=Q6&mm=31%2C29&mn=sn-xupn5a5uxbt-j5pr%2Csn-hgn7rn7y&ms=au%2Crdu&mv=m&mvi=4&pl=24&initcwndbps=247500&bui=AQmm2ezNAOYeeEeMGC1aW_MA2_0QVl9CNCZCL2jjPuxWy9LOlMArMjPjjXfs5FQjYZE8He1aGQC3rK0P&spc=Mv1m9ocwzzSHS5Tz_jCzgu4DZ9AGP4p_uIcFFqkYOIA9byL43MqtruM&vprv=1&svpuc=1&mime=video%2Fmp4&ns=ZOHEuoiwUh1sfHiLOld5aXoQ&rqh=1&gir=yes&clen=139728290&ratebypass=yes&dur=2345.331&lmt=1722066659993232&mt=1724750456&fvip=2&c=WEB_CREATOR&sefc=1&txp=5538434&n=xgeyk9GrWjdtIg&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cbui%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cns%2Crqh%2Cgir%2Cclen%2Cratebypass%2Cdur%2Clmt&sig=AJfQdSswRQIgMs5nVTnKSD77FbeP3GDDAO6VaJZsOUKjnBKazG4umH8CIQDFtQJfQM4aH3HRVMnAUk-4L4XV1kDQra5a5ISrlDnSHQ%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AGtxev0wRAIgT4Ce39I2QHoH2qKDzEVaueUWxbUL0Vw4MwiS4c_p7w0CIBZNufAo9fh-SzrPGwLNajeJnCGfitRO8LoIxVu9E8Sh"
[download] History of a Mediterranean Superpower： Rise & Fall of Venice [a1iuxFHTJyU].mp4 has already been downloaded
[download] 100% of  133.26MiB
```

**Comment by DTrombett** [comment]
You're using `-f mp4` which takes a premerged format. YouTube limits these formats, so you'll get only a low-resolution video. If you really want an mp4 consider using `-S vcodec:h264,res,acodec:aac`. If you're ok with any video/audio formats inside an mp4 container you can try `-S ext`

**Comment by KhaledMahm0vd** [comment]
Thanks for your suggestion, it worked, i have ommitted -f mp4 and the video downloaded in 720p resolution as i specified.
Again, Thank you very much
