### ISSUE TITLE
Add Support for New Video Sites & YouTube MP3 Downloads

### ISSUE THREAD

**Issue by abdullah61830** [yt-dlp/yt-dlp#10866]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

I'd love to see support added for a few popular video streaming sites:

https://hdtoday.tv
https://hdtodayz.to
https://myflixerz.to
https://123moviesfree.net
https://gomovies.sx

Additionally, it would be fantastic to have the option to download YouTube videos directly as MP3 files.

Why This Matters:

Broader Access: Adding these sites means users can download from more sources, which is a big win.
More Versatile: The ability to convert YouTube videos to MP3 is super handy for those who only want the audio.

These features would make the tool even more powerful and user-friendly. Thanks for considering this!

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
Piracy sites won't be supported
