### ISSUE TITLE
[mp4upload] Add mp4upload

### ISSUE THREAD

**Issue by candrapersada** [yt-dlp/yt-dlp#1086]
add for mp4upload.com

**Comment by MinePlayersPE** [comment]
### [Please follow the issue template for site support](https://github.com/yt-dlp/yt-dlp/issues/new?assignees=&labels=Request&template=2_site_support_request.md&title=%5BSite+Request%5D)

Do you have any example URLs that don't require login? Or do you always need an account
Also please make sure the site isn't a pirate haven

**Comment by candrapersada** [comment]
> Do you have any example URLs that don't require login

yes
https://www.mp4upload.com/wssnof547lsr

**Comment by nao20010128nao** [comment]
related: https://github.com/ytdl-org/youtube-dl/pull/19103/files

**Comment by coletdjnz** [comment]
**IGNORING THE ISSUE TEMPLATE WILL RESULT IN ISSUE CLOSED AS INCOMPLETE**

The link you provide contains pirated material -  we do not support sites primary used for piracy. Quick search of this site also brings up that it hosts content for mostly piracy-based sites.

----
Also related from upstream:
https://github.com/ytdl-org/youtube-dl/pull/19103
https://github.com/ytdl-org/youtube-dl/pull/16958
