### ISSUE TITLE
yt-dlp downloads livestream chat when downloading subtitles in youtube

### ISSUE THREAD

**Issue by solomoncyj** [yt-dlp/yt-dlp#10872]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Malaysia

### Provide a description that is worded well enough to be understood

when `--sub-lang all` and `--embed-subs` flages are passed, and the link is / was a youtube livestream/ premier, yt-dlp will attempt to download the live chat as a JSON and will refuse to merge it with the video file. additionaly, if the livestream is ongoing, yt-dlp will refuse to go on and will block the thread.
yt-dlp **should not** download the live stream chat when the sub args are passed

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['https://www.youtube.com/watch?v=r3FCFYF1Qds', '-vU']
[debug] User config "/home/solomoncyj/.yt-dlp/config.txt": ['-o', './%(playlist_title|)s/%(title)s.mkv', '-N', '2000', '-S', 'vcodec:av1', '--embed-metadata', '--sub-lang', 'all', '--embed-subs']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.08.06 from yt-dlp/yt-dlp [4d9231208]
[debug] Lazy loading extractors is disabled
[debug] Python 3.12.5 (CPython x86_64 64bit) - Linux-6.10.6-200.fc40.x86_64-x86_64-with-glibc2.39 (OpenSSL 3.2.2 4 Jun 2024, glibc 2.39)
[debug] exe versions: ffmpeg 6.1.2 (setts), ffprobe 6.1.2
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2023.05.07, mutagen-1.47.0, requests-2.32.3, sqlite3-3.45.1, urllib3-1.26.19, websockets-13.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1830 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.08.06 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.08.06 from yt-dlp/yt-dlp)
[youtube] Extracting URL: https://www.youtube.com/watch?v=r3FCFYF1Qds
[youtube] r3FCFYF1Qds: Downloading webpage
[youtube] r3FCFYF1Qds: Downloading ios player API JSON
[youtube] r3FCFYF1Qds: Downloading web creator player API JSON
[youtube] r3FCFYF1Qds: Downloading m3u8 information
[youtube] r3FCFYF1Qds: Downloading m3u8 information
[info] r3FCFYF1Qds: Downloading subtitles: live_chat
[debug] Sort order given by user: vcodec:av1
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, vcodec:av1(11), quality, res, fps, hdr:12(7), source, channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[debug] Default format spec: best/bestvideo+bestaudio
[info] r3FCFYF1Qds: Downloading 1 format(s): 301
[info] Writing video subtitles to: .//【KARA-REWIND】August Unarchived Karaoke ~! 💄 2024-08-29 17_23.mkv.live_chat.json
[debug] Invoking youtube_live_chat downloader on "https://www.youtube.com/watch?v=r3FCFYF1Qds&bpctr=9999999999&has_verified=1"
[youtube_live_chat] Downloading live chat
WARNING: Live chat download runs until the livestream ends. If you wish to download the video simultaneously, run a separate yt-dlp instance
[youtube_live_chat] Total fragments: unknown (live)
[download] Destination: .//【KARA-REWIND】August Unarchived Karaoke ~! 💄 2024-08-29 17_23.mkv.live_chat.json
```

**Comment by bashonly** [comment]
`--sub-lang all,-live_chat`
