### ISSUE TITLE
where does yt-dlp download videos by default

### ISSUE THREAD

**Issue by Pwnz0rserver2009** [yt-dlp/yt-dlp#10882]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

i'd ask in discussions as this _technically_ isn't a technical issue but discussions are closed so i'm forced to do this

where does yt-dlp download videos by default? i've downloaded a video and i'm not going to just reroute the destination as yt-dlp DID download the video, it' taking my hard drive space

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by seproDev** [comment]
By default, yt-dlp downloads to your current command line location. It should say the location next to where you entered the command. Otherwise, typing `pwd` should tell you your current location in most shells. Though that might differ on some OS's or shells.
With `-P` you can change the location in the future. You can even add it to your config if you don't want to add that every time.

**Comment by Pwnz0rserver2009** [comment]
i figured it out before it was commented on, the conversation being locking just prevented me from actually closing this issue ._.
