### ISSUE TITLE
How to add metadata to already downloaded file

### ISSUE THREAD

**Issue by sbushmanov** [yt-dlp/yt-dlp#10891]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Let's say I happened to download "Blank spaces" audio by Taylor Swift:

```
yt-dlp -i -f 140 "https://www.youtube.com/watch?v=e-ORhEE9VVg"
```
and having a file named `Taylor Swift - Blank Space [e-ORhEE9VVg].m4a`   

What should be my course of action to only add metadata without downloading the whole file with metadata. i.e. without: 
```
yt-dlp --embed-metadata -i -f 140 "https://www.youtube.com/watch?v=e-ORhEE9VVg"
```
(to save the bandwidth)

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
if you haven't moved/renamed the downloaded file, are using the same output template (`-o`), and you aren't using `--force-overwrite`, then running the same command again with `--embed-metadata` will only embed the metadata and not re-download the video

**Comment by sbushmanov** [comment]
@bashonly 
Thank you very much for the suggestion.

Ended up:
```
find . -type f | grep -Po '\[\K[^]]{4,}' | xargs -I@ yt-dlp --embed-metadata -i -f 140 "https://www.youtube.com/watch?v=@"
```
