### ISSUE TITLE
Standardized way to detect if a link simply has no media to download

### ISSUE THREAD

**Issue by WilliamVenner** [yt-dlp/yt-dlp#10900]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Forgive me if this is a duplicate; it is difficult to search for this feature specifically.

It would be great if yt-dlp could return a standardized output that states "the link is fine, there's just not any media to download from it."

For example, X/Twitter links don't necessarily contain any media, and can be text-only posts. However, there is seemingly no reliable/standardized way to detect whether this is the case for a particular link.

I noticed `--ignore-no-formats-error` but this doesn't really satisfy this feature request.

`--ignore-no-formats-error --dump-json` _does_ satisfy this feature request but still throws an error for "unsupported URLs."

`--ignore-no-formats-error --dump-json --no-simulate` doesn't satisfy this feature request because there's no media to download, which throws an error (despite `--ignore-no-formats-error`) - separate bug?

Unfortunately, the downloaders/extractors don't have a standardized error message for saying "there's no media here."

Furthermore, some downloaders/extractors will give a "unsupported URL" error. If this feature request is implemented, it should also apply to these errors, as that also really implies "there's no media here."

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp -Uv https://x.com/X/status/1830287114669273200
[debug] Command-line config: ['-Uv', 'https://x.com/X/status/1830287114669273200']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.08.06 from yt-dlp/yt-dlp [4d9231208] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22631-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 2024-08-28-git-b730defd52-full_build-www.gyan.dev (setts), ffprobe 2024-08-28-git-b730defd52-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.07.04, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1830 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.08.06 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.08.06 from yt-dlp/yt-dlp)
[twitter] Extracting URL: https://x.com/X/status/1830287114669273200
[twitter] 1830287114669273200: Downloading guest token
[twitter] 1830287114669273200: Downloading GraphQL JSON
ERROR: [twitter] 1830287114669273200: No video could be found in this tweet
  File "yt_dlp\extractor\common.py", line 740, in extract
  File "yt_dlp\extractor\twitter.py", line 1598, in _real_extract
  File "yt_dlp\extractor\common.py", line 1263, in raise_no_formats

yt-dlp -Uv https://instagram.com/direct/inbox
[debug] Command-line config: ['-Uv', 'https://instagram.com/direct/inbox']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.08.06 from yt-dlp/yt-dlp [4d9231208] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22631-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 2024-08-28-git-b730defd52-full_build-www.gyan.dev (setts), ffprobe 2024-08-28-git-b730defd52-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.07.04, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1830 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.08.06 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.08.06 from yt-dlp/yt-dlp)
[generic] Extracting URL: https://instagram.com/direct/inbox
[generic] inbox: Downloading webpage
[redirect] Following redirect to https://www.instagram.com/accounts/login/?next=https%3A%2F%2Fwww.instagram.com%2Fdirect%2Finbox%2F%3F__coig_login%3D1
[generic] Extracting URL: https://www.instagram.com/accounts/login/?next=https%3A%2F%2Fwww.instagram.com%2Fdirect%2Finbox%2F%3F__coig_login%3D1
[generic] ?next=https://www.instagram: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] ?next=https://www.instagram: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://www.instagram.com/accounts/login/?next=https%3A%2F%2Fwww.instagram.com%2Fdirect%2Finbox%2F%3F__coig_login%3D1
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1626, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1761, in __extract_info
  File "yt_dlp\extractor\common.py", line 740, in extract
  File "yt_dlp\extractor\generic.py", line 2526, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.instagram.com/accounts/login/?next=https%3A%2F%2Fwww.instagram.com%2Fdirect%2Finbox%2F%3F__coig_login%3D1
```

**Comment by bashonly** [comment]
The focus of yt-dlp is to be a media downloader, not an all purpose web/metadata scraper. If video/audio cannot be downloaded from a link, the expected behavior is and should be to raise an error. Some extractors (such as the Twitter extractor) are written so that metadata can still be extracted even when media is not present in the link (if you pass `--ignore-no-formats`), but this is merely a **bonus**. It is not something that can be reasonably expected out of every link/site/extractor.

> `--ignore-no-formats-error --dump-json --no-simulate` doesn't satisfy this feature request because there's no media to download, which throws an error (despite `--ignore-no-formats-error`) - separate bug?

No. `--no-simulate` implies you want to download media, rather than simulating downloading media (e.g. for metadata extraction or debugging purposes). If you pass `--no-simulate` and media cannot be downloaded, the correct behavior for yt-dlp is to raise an error.

> Furthermore, some downloaders/extractors will give a "unsupported URL" error. If this feature request is implemented, it should also apply to these errors, as that also really implies "there's no media here."

If a URL is unsupported, it doesn't imply that "there's no media here." It means that yt-dlp isn't currently equipped to determine if there is or is not media present in the link. The error is appropriate as-is
