### ISSUE TITLE
[Question] YouTube Music 256kbps

### ISSUE THREAD

**Issue by axeldelafosse** [yt-dlp/yt-dlp#1091]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

Hey! Thanks for the hard work. I have a question related to YouTube Music. Saw this in the readme:

> 255kbps audio is extracted from youtube music if premium cookies are given

I have a YouTube Music + Premium account and I'm using the YT cookies to download songs (uploaded by YouTube), for example: `yt-dlp -f bestaudio --extract-audio --embed-thumbnail --cookies youtube.com_cookies.txt --add-metadata -o "%(artist)s - %(title)s.%(ext)s" https://music.youtube.com/watch\?v\=MDSGU8l9LTw -k`

I'm checking with `ffmpeg` the bitrate but I never get 256 kbps. It's between 150 and 180.

Am I doing something wrong? Or is this related to the overall audio quality from YouTube Music, i.e. they don't always use 256 kpbs?

Thank you :)

**Comment by pukkandan** [comment]
Only VEVO music has 256kbps format

**Comment by axeldelafosse** [comment]
Thank you for the quick answer. Yeah looks like some songs uploaded by Vevo can go up to 200 kbps. I found some at 150 but not at 256. So yeah depends on the songs and on the uploader.

It was too good to be true! Good to know that YouTube Music audio quality is not that good after all.

**Comment by axeldelafosse** [comment]
Maybe worth mentioning this in the readme? I can send a PR if you think it's a good idea. Otherwise you can close this. Have a good weekend!

**Comment by pukkandan** [comment]
I thought it was obvious that it can be extracted only when youtube provides it

```md
     * `255kbps` audio is extracted (if available) from youtube music when premium cookies are given
```

would this be better?

**Comment by axeldelafosse** [comment]
Yes it's better.

No worries -- it's not your fault, I was thinking that all songs uploaded automatically by YouTube (for YouTube Music) would be high quality. The YouTube Music "high quality" setting is misleading.

The weird thing is, from my testing, you extract the same quality even when you don't use premium cookies. I was able to get a 200 kbps version without using cookies. I'm starting to think that YouTube Music and/or Premium is just the same audio quality as bare YouTube.

**Comment by pukkandan** [comment]
Atleast when this feature was implemented, some songs specifically had a 256k audio available only with premium. I don't know if something is broken now and I dont have premium to test with. Could you test with https://music.youtube.com/watch?v=8ay_BkRuv-o. The higher quality audio will have an id 141

**Comment by axeldelafosse** [comment]
137 kb/s

```
Input #0, ogg, from 'Jim Yosef - Firefly.opus':
  Duration: 00:04:16.64, start: 0.000000, bitrate: 137 kb/s
  Stream #0:0(eng): Audio: opus, 48000 Hz, stereo, fltp
    Metadata:
      encoder         : Lavf58.76.100
      title           : Firefly
      date            : 20150714
      purl            : https://www.youtube.com/watch?v=XclachpHxis
      synopsis        : Provided to YouTube by AEI Media Ltd
                      :
                      : Firefly · Jim Yosef
                      :
                      : Firefly
                      :
                      : ℗ 2015 NCS Ltd.
                      :
                      : Released on: 2015-06-28
                      :
                      : Auto-generated by YouTube.
      comment         : https://www.youtube.com/watch?v=XclachpHxis
      artist          : Jim Yosef
      album           : Firefly
```

**Comment by pukkandan** [comment]
can u show the output of `-F`?

@coletdjnz do you still have a premium account to check if this is broken?

**Comment by axeldelafosse** [comment]
Hmm, interesting. Looks like `-f bestaudio` uses id 251 instead of 141. So YouTube Music does have high quality audio! Good news.
```
[info] Available formats for XclachpHxis:
ID  EXT  RESOLUTION FPS |  FILESIZE    TBR PROTO | VCODEC          VBR ACODEC     ABR  ASR    MORE INFO
--- ---- ---------- --- - ---------- ----- ----- - ------------- ----- --------- ---- ------- -----------------
139 m4a  audio only     |  1.49MiB     48k https |                     mp4a.40.5  48k 22050Hz low, m4a_dash
249 webm audio only     |  1.49MiB     48k https |                     opus       48k 48000Hz low, webm_dash
250 webm audio only     |  1.97MiB     64k https |                     opus       64k 48000Hz low, webm_dash
140 m4a  audio only     |  3.96MiB    129k https |                     mp4a.40.2 129k 44100Hz medium, m4a_dash
251 webm audio only     |  3.92MiB    128k https |                     opus      128k 48000Hz medium, webm_dash
141 m4a  audio only     |  7.88MiB    257k https |                     mp4a.40.2 257k 44100Hz high, m4a_dash
17  3gp  176x144    6   |  1.25MiB     40k https | mp4v.20.3       40k mp4a.40.2   0k 22050Hz 144p
394 mp4  144x144    25  |  578.69KiB   18k https | av01.0.00M.08   18k                        144p, mp4_dash
160 mp4  144x144    25  |  265.63KiB    8k https | avc1.4d400b      8k                        144p, mp4_dash
278 webm 144x144    25  |  569.01KiB   18k https | vp9             18k                        144p, webm_dash
395 mp4  240x240    25  |  832.62KiB   26k https | av01.0.00M.08   26k                        240p, mp4_dash
133 mp4  240x240    25  |  348.18KiB   11k https | avc1.4d400c     11k                        240p, mp4_dash
242 webm 240x240    25  |  900.29KiB   28k https | vp9             28k                        240p, webm_dash
396 mp4  360x360    25  |  1.02MiB     33k https | av01.0.00M.08   33k                        360p, mp4_dash
134 mp4  360x360    25  |  498.17KiB   15k https | avc1.4d4015     15k                        360p, mp4_dash
18  mp4  360x360    25  |  5.06MiB    165k https | avc1.42001E    165k mp4a.40.2   0k 44100Hz 360p
243 webm 360x360    25  |  1.12MiB     36k https | vp9             36k                        360p, webm_dash
397 mp4  480x480    25  |  1.43MiB     46k https | av01.0.01M.08   46k                        480p, mp4_dash
135 mp4  480x480    25  |  687.59KiB   21k https | avc1.4d401e     21k                        480p, mp4_dash
244 webm 480x480    25  |  1.82MiB     59k https | vp9             59k                        480p, webm_dash
398 mp4  720x720    25  |  1.82MiB     59k https | av01.0.04M.08   59k                        720p, mp4_dash
136 mp4  720x720    25  |  976.23KiB   31k https | avc1.4d401f     31k                        720p, mp4_dash
22  mp4  720x720    25  |             160k https | avc1.64001F    160k mp4a.40.2   0k 44100Hz 720p
247 webm 720x720    25  |  5.46MiB    178k https | vp9            178k                        720p, webm_dash
399 mp4  1080x1080  25  |  9.83MiB    321k https | av01.0.08M.08  321k                        1080p, mp4_dash
137 mp4  1080x1080  25  |  2.15MiB     70k https | avc1.640020     70k                        1080p, mp4_dash
248 webm 1080x1080  25  |  16.66MiB   544k https | vp9            544k                        1080p, webm_dash
```

**Comment by pukkandan** [comment]
> Hmm, interesting. Looks like -f bestaudio uses id 251 instead of 141

The sorting looks correct (it is worst to best). Show the verbose log of your download run

**Comment by axeldelafosse** [comment]
Oh! Now it's working, I get the `.m4a` file instead of the `.opus`!

**Comment by pukkandan** [comment]
I assume all your queries have been answered

**Comment by axeldelafosse** [comment]
Yes, I tried with a fresh install in Docker and it's working too so I wasn't able to reproduce the issue. Thank you @pukkandan!
