### ISSUE TITLE
Wistia.com -- No video formats found! --- password protected

### ISSUE THREAD

**Issue by scirocco-github** [yt-dlp/yt-dlp#10914]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

USA

### Provide a description that is worded well enough to be understood

Video is playable in browser from https://jimmyc.wistia.com/medias/dpt6962jwb using password xlk676

yt-dlp fails with "No video formats found!" when using --video-password

(yt-dlp installed via pip)

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
DonkeeMac:~ aaron$ yt-dlp -v --video-password xlk676 https://jimmyc.wistia.com/medias/dpt6962jwb
[debug] Command-line config: ['-v', '--video-password', 'PRIVATE', 'https://jimmyc.wistia.com/medias/dpt6962jwb']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.05.27 from yt-dlp/yt-dlp [12b248ce6] (pip)
[debug] Python 3.11.8 (CPython x86_64 64bit) - macOS-10.15.7-x86_64-i386-64bit (OpenSSL 3.3.1 4 Jun 2024)
[debug] exe versions: ffmpeg N-104236-g21979cf98e-tessus (setts), rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2022.12.07, mutagen-1.47.0, requests-2.31.0, sqlite3-3.45.1, urllib3-2.1.0, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1820 extractors
[Wistia] Extracting URL: https://jimmyc.wistia.com/medias/dpt6962jwb
[Wistia] dpt6962jwb: Downloading JSON metadata
[Wistia] Checking media extension
ERROR: [Wistia] dpt6962jwb: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1606, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1762, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1821, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 2825, in process_video_result
    self.raise_no_formats(info_dict)
  File "/usr/local/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1104, in raise_no_formats
    raise ExtractorError(msg, video_id=info['id'], ie=info['extractor'],
yt_dlp.utils.ExtractorError: [Wistia] dpt6962jwb: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

**Comment by bashonly** [comment]
```diff
diff --git a/yt_dlp/extractor/wistia.py b/yt_dlp/extractor/wistia.py
index fb2a8648f..df7ecb3cd 100644
--- a/yt_dlp/extractor/wistia.py
+++ b/yt_dlp/extractor/wistia.py
@@ -8,6 +8,7 @@
 from ..utils import (
     ExtractorError,
     determine_ext,
+    filter_dict,
     float_or_none,
     int_or_none,
     parse_qs,
@@ -25,16 +26,25 @@ class WistiaBaseIE(InfoExtractor):
 
     def _download_embed_config(self, config_type, config_id, referer):
         base_url = self._EMBED_BASE_URL + f'{config_type}/{config_id}'
+        video_password = self.get_param('videopassword')
         embed_config = self._download_json(
             base_url + '.json', config_id, headers={
                 'Referer': referer if referer.startswith('http') else base_url,  # Some videos require this.
-            })
+            }, query=filter_dict({'password': video_password}))
 
         error = traverse_obj(embed_config, 'error')
         if error:
             raise ExtractorError(
                 f'Error while getting the playlist: {error}', expected=True)
 
+        if traverse_obj(embed_config, (
+                'media', ('embed_options', 'embedOptions'), 'plugin',
+                'passwordProtectedVideo', 'on', any)) == 'true':
+            if video_password:
+                raise ExtractorError('Invalid video password', expected=True)
+            raise ExtractorError(
+                'This content is password-protected. Use the --video-password option', expected=True)
+
         return embed_config
 
     def _get_real_ext(self, url):
```

**Comment by scirocco-github** [comment]
output from an attempt from the patreon page in which the wistia is embedded 


DonkeeMac:~ aaron$ yt-dlp -v --cookies-from-browser chrome --video-password xlk676 https://www.patreon.com/posts/psychology-of-w-37745632
[debug] Command-line config: ['-v', '--cookies-from-browser', 'chrome', '--video-password', 'PRIVATE', 'https://www.patreon.com/posts/psychology-of-w-37745632']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.05.27 from yt-dlp/yt-dlp [12b248ce6] (pip)
[debug] Python 3.11.8 (CPython x86_64 64bit) - macOS-10.15.7-x86_64-i386-64bit (OpenSSL 3.3.1 4 Jun 2024)
[debug] exe versions: ffmpeg N-104236-g21979cf98e-tessus (setts), rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2022.12.07, mutagen-1.47.0, requests-2.31.0, sqlite3-3.45.1, urllib3-2.1.0, websockets-12.0
[debug] Proxy map: {}
Extracting cookies from chrome
[debug] Extracting cookies from: "/Users/aaron/Library/Application Support/Google/Chrome/Default/Cookies"
[debug] using find-generic-password to obtain password from OSX keychain
Extracted 3411 cookies from chrome
[debug] cookie version breakdown: {'v10': 3325, 'other': 0, 'unencrypted': 112}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1820 extractors
[Patreon] Extracting URL: https://www.patreon.com/posts/psychology-of-w-37745632
[Patreon] 37745632: Downloading API JSON
[Patreon] 37745632: Checking embed URL
[Wistia] Extracting URL: https://jimmyc.wistia.com/medias/dpt6962jwb
[Wistia] dpt6962jwb: Downloading JSON metadata
[Wistia] Checking media extension
ERROR: [Wistia] dpt6962jwb: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1606, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1762, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1821, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 2825, in process_video_result
    self.raise_no_formats(info_dict)
  File "/usr/local/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1104, in raise_no_formats
    raise ExtractorError(msg, video_id=info['id'], ie=info['extractor'],
yt_dlp.utils.ExtractorError: [Wistia] dpt6962jwb: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

**Comment by scirocco-github** [comment]
> ```diff
> diff --git a/yt_dlp/extractor/wistia.py b/yt_dlp/extractor/wistia.py
> index fb2a8648f..df7ecb3cd 100644
> --- a/yt_dlp/extractor/wistia.py
> +++ b/yt_dlp/extractor/wistia.py


Wait there's a patch already?

--- OUTSTANDING --- 

thanks for all you (and you-all) do!
