### ISSUE TITLE
10play - Website code changed breaks support

### ISSUE THREAD

**Issue by wastedhate** [yt-dlp/yt-dlp#10926]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Australia

### Provide a description that is worded well enough to be understood

Appears to be a site code change which has effected yt-dlp's ability to download from the site. Tested links that work yesterday which now no longer works.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp.exe -F https://10play.com.au/neighbours/episodes/season-42/episode-9107/tpv240902nzqyp -u PRIVATE -p PRIVATE -vU
[debug] Command-line config: ['-F', 'https://10play.com.au/neighbours/episodes/season-42/episode-9107/tpv240902nzqyp', '-u', 'PRIVATE', '-p', 'PRIVATE', '-vU']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.09.02.232855 from yt-dlp/yt-dlp-nightly-builds [e8e6a982a] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22631-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-116754-ga754ee0844-20240821 (setts), ffprobe N-116754-ga754ee0844-20240821
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.08.30, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.2, websockets-13.0.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1832 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.09.02.232855 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.09.02.232855 from yt-dlp/yt-dlp-nightly-builds)
[TenPlay] Extracting URL: https://10play.com.au/neighbours/episodes/season-42/episode-9107/tpv240902nzqyp
[TenPlay] tpv240902nzqyp: Downloading JSON metadata
[TenPlay] tpv240902nzqyp: Getting bearer token
[TenPlay] tpv240902nzqyp: Downloading video JSON
[TenPlay] tpv240902nzqyp: Downloading webpage
ERROR: Invalid URL 'https://': No host supplied
Traceback (most recent call last):
  File "yt_dlp\networking\_requests.py", line 328, in _send
  File "requests\sessions.py", line 575, in request
  File "requests\sessions.py", line 484, in prepare_request
  File "requests\models.py", line 367, in prepare
  File "requests\models.py", line 444, in prepare_url
requests.exceptions.InvalidURL: Invalid URL 'https://': No host supplied

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1626, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1761, in __extract_info
  File "yt_dlp\extractor\common.py", line 740, in extract
  File "yt_dlp\extractor\tenplay.py", line 96, in _real_extract
  File "yt_dlp\extractor\common.py", line 896, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 4165, in urlopen
  File "yt_dlp\networking\common.py", line 117, in send
  File "yt_dlp\networking\_helper.py", line 208, in wrapper
  File "yt_dlp\networking\common.py", line 340, in send
  File "yt_dlp\networking\_requests.py", line 360, in _send
yt_dlp.networking.exceptions.RequestError: Invalid URL 'https://': No host supplied
```

**Comment by ringofyre** [comment]
Can confirm - 
yt-dlp -v -u [username] -p [password] https://10play.com.au/have-you-been-paying-attention/episodes/2024/episode-18/tpv240909vreuf
[debug] Command-line config: ['-v', '-u', 'PRIVATE', '-p', 'PRIVATE', 'https://10play.com.au/have-you-been-paying-attention/episodes/2024/episode-18/tpv240909vreuf']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.08.06 from yt-dlp/yt-dlp [4d9231208] (zip)
[debug] Python 3.12.6 (CPython x86_64 64bit) - Linux-6.10.6-x64v3-xanmod1-x86_64-with-glibc2.40 (OpenSSL 3.3.2 3 Sep 2024, glibc 2.40)
[debug] exe versions: ffmpeg 4.4.5 (fdk,setts), ffprobe 4.4.5, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.06.02, mutagen-1.46.0, requests-2.32.3, secretstorage-3.3.3, sqlite3-3.46.0, urllib3-2.0.7, websockets-10.4
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Loaded 1830 extractors
[TenPlay] Extracting URL: https://10play.com.au/have-you-been-paying-attention/episodes/2024/episode-18/tpv240909vreuf
[TenPlay] tpv240909vreuf: Downloading JSON metadata
[TenPlay] tpv240909vreuf: Getting bearer token
[TenPlay] tpv240909vreuf: Downloading video JSON
[TenPlay] tpv240909vreuf: Downloading webpage
ERROR: Invalid URL 'https://': No host supplied
Traceback (most recent call last):
  File "/usr/bin/yt-dlp/yt_dlp/networking/_requests.py", line 328, in _send
    requests_res = session.request(
                   ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 575, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/usr/lib/python3/dist-packages/requests/models.py", line 367, in prepare
    self.prepare_url(url, params)
  File "/usr/lib/python3/dist-packages/requests/models.py", line 444, in prepare_url
    raise InvalidURL(f"Invalid URL {url!r}: No host supplied")
requests.exceptions.InvalidURL: Invalid URL 'https://': No host supplied

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1626, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1761, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "/usr/bin/yt-dlp/yt_dlp/extractor/common.py", line 740, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/yt-dlp/yt_dlp/extractor/tenplay.py", line 96, in _real_extract
    m3u8_url = self._request_webpage(HEADRequest(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/yt-dlp/yt_dlp/extractor/common.py", line 896, in _request_webpage
    return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query, extensions))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 4165, in urlopen
    return self._request_director.send(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/yt-dlp/yt_dlp/networking/common.py", line 117, in send
    response = handler.send(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/yt-dlp/yt_dlp/networking/_helper.py", line 208, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/yt-dlp/yt_dlp/networking/common.py", line 340, in send
    return self._send(request)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/yt-dlp/yt_dlp/networking/_requests.py", line 360, in _send
    raise RequestError(cause=e) from e
yt_dlp.networking.exceptions.RequestError: Invalid URL 'https://': No host supplied

**Comment by gamer191** [comment]
Is the website still working? It seems broken for me, suggesting that this change might get reverted soon

**Comment by ringofyre** [comment]
Tenplay still plays video in browser (chromium) but you need an account and ublock off to access.
