### ISSUE TITLE
Add name to subtitle file so can only be one call to yt-dlp

### ISSUE THREAD

**Issue by nadermx** [yt-dlp/yt-dlp#10923]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

I currently have been trying unsucesffuly to make this work.  I found this issue, which seems to be related, but it's 4 years old, https://github.com/ytdl-org/youtube-dl/issues/25344 and then I found this issue https://github.com/yt-dlp/yt-dlp/issues/7496#issuecomment-1666801979 with this solution `yt-dlp --skip-download --write-subs --exec before_dl:"sed -i -e '/^[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9] --> [0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9]$/d' -e '/^[[:digit:]]\{1,3\}$/d' -e 's/<[^>]*>//g' %(requested_subtitles.:.filepath)#q" "URL"'`
but despite putting both of them together in hopes for a solution, it still ends up with a file name `-.en.vtt` with my command

```
yt-dlp --verbose -c --no-part \
    -f "<FORMAT>/bestvideo[ext=mp4]/bestvideo/best" \
    --write-subs --sub-lang "<SUBTITLE_LANGUAGE>" --sub-format "vtt" \
    --no-geo-bypass --no-cache-dir --hls-prefer-native \
    --exec "before_dl:\"echo 'Subtitles saved at %(requested_subtitles.:.filepath)#q'\"" \
    -o "-" "<VIDEO_URL>"
```

Making it so to get subtitles it requires a completely different call instead of being able to do both the video to output and read the subtitle file `before_dl`

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
This is out-of-scope

The quoting in the `--exec` arg appears to be incorrect

**Comment by nadermx** [comment]
Could you provide the correct quoting? You mean " vs '?

**Comment by bashonly** [comment]
also why are you using `-o -`

**Comment by nadermx** [comment]
Because ideally I'd like to have it output the video, and output the subtitles, either to another pipe, or to a temporary file

**Comment by bashonly** [comment]
the subtitles cannot be piped, they will always be written to a file

**Comment by nadermx** [comment]
Okay, but what I'm trying to have is where they will be, when in the same call piping a video.  And if it's possible to direct where the subtitles will be written to, ie, so they could be written into a temporary file

**Comment by bashonly** [comment]
you can additionally use a subtitle output template, e.g.
```
 -o "subtitle:%(id)s.%(ext)s" -o -
```

**Comment by nadermx** [comment]
Since I have to make an extra call regardless, I was able to get the specific sub title file url via 

```
yt-dlp --skip-download --write-subs --sub-lang en --print "requested_subtitles.en.url" VIDEO_URL
```
