### ISSUE TITLE
yt-dlp & SponsorBlock troubles

### ISSUE THREAD

**Issue by Baltazar500** [yt-dlp/yt-dlp#10932]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

1. Is it possible to increase the number of request attempts and timeout duration to the SponsorBlock server if a 503 error occurs indicating that the resource is unavailable?

2. How can I skip downloading a video if the SponsorBlock server is unavailable? I don't need an "uncut" video.

3. Are there any SponsorBlock server mirrors that work with yt-dlp?

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
> 1. Is it possible to increase the number of request attempts and timeout duration to the SponsorBlock server if a 503 error occurs indicating that the resource is unavailable?

No

> 2. How can I skip downloading a video if the SponsorBlock server is unavailable? I don't need an "uncut" video.

Not currently possible; there is an open feature request: #9953

You can always download the video now and then run the same command later when sponsorblock data is available to remove the sponsor segments (the video won't be re-downloaded as long as you don't move/rename it). yt-dlp always downloads the full video anyways before it slices and dices it

> 3. Are there any SponsorBlock server mirrors that work with yt-dlp?

Any sponsorbock API mirrors should work with yt-dlp, you would use them with:

```
--sponsorblock-api URL          SponsorBlock API location, defaults to
                                https://sponsor.ajay.app
```

As far as what the mirrors are, I have no idea, and that question is really out-of-scope for this issue tracker. The [sponsorblock website](https://sponsor.ajay.app/) lists a discord server and a matrix room, you could try looking/asking around in there
