### ISSUE TITLE
Has anyone gotten itvX to work?

### ISSUE THREAD

**Issue by PacoH** [yt-dlp/yt-dlp#10937]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

yt-dlp --version
2024.08.06

>I'm reporting that yt-dlp is broken on a supported site

Acc. to [yt-dlp/supportedsites.md at master · yt-dlp/yt-dlp](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md):
ITV

>I've verified that I have updated yt-dlp to nightly or master

yt-dlp --version
2024.09.05.184733

>I've checked that all provided URLs are playable in a browser with the same IP and same login details

[Orphan Black: Echoes - Series 1 - Episode 1 - ITVX](https://www.itv.com/watch/orphan-black:-echoes/10a4782/10a4782a0001)
`https://www.itv.com/watch/orphan-black:-echoes/10a4782/10a4782a0001`

Playing in next tab as I type.

Logged into my account. Using a VPN connected to a London IP address. Plays fine in Chrome.

>I've checked that all URLs and arguments with special characters are properly quoted or escaped

Tried with and without escaping:

`"https://www.itv.com/watch/orphan-black:-echoes/10a4782/10a4782a0001"`

`https://www.itv.com/watch/orphan-black\:-echoes/10a4782/10a4782a0001`

>I've searched known issues and the bugtracker for similar issues including closed ones. DO NOT post duplicates

>I've read the guidelines for opening an issue

>Please include the full output of yt-dlp when run with -vU
>`yt-dlp -vU <your command line>`

```
yt-dlp -vU -F "https://www.itv.com/watch/orphan-black:-echoes/10a4782/10a4782a0001"
[debug] Command-line config: ['-vU', '-F', 'https://www.itv.com/watch/orphan-black:-echoes/10a4782/10a4782a0001']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version master@2024.09.05.184733 from yt-dlp/yt-dlp-master-builds [0fba08485] (zip)
[debug] Python 3.12.4 (CPython x86_64 64bit) - macOS-13.6.5-x86_64-i386-64bit (OpenSSL 3.3.1 4 Jun 2024)
[debug] exe versions: ffmpeg 7.0.1 (setts), ffprobe 7.0.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.07.04, mutagen-1.47.0, requests-2.32.3, sqlite3-3.46.0, urllib3-2.2.2, websockets-13.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1832 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-master-builds/releases/latest
Latest version: master@2024.09.05.184733 from yt-dlp/yt-dlp-master-builds
yt-dlp is up to date (master@2024.09.05.184733 from yt-dlp/yt-dlp-master-builds)
[generic] Extracting URL: https://www.itv.com/watch/orphan-black:-echoes/10a4782/10a4782a0001
[generic] 10a4782a0001: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] 10a4782a0001: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://www.itv.com/watch/orphan-black:-echoes/10a4782/10a4782a0001
```

>Enter the country/region that the site is accessible from

UK

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by october262** [comment]
videos are DRM protected, Brave browser wants to install the Google widevine add-on

**Comment by dirkf** [comment]
There was originally a viewable mobile format that the extractor could use, but it isn't served any longer. STV (ITV Scotland) has its own site that is more accommodating.

**Comment by PacoH** [comment]
@october262
>videos are DRM protected

Huh? I mentioned that I can play the videos in Chrome, no problem. Without ads. Even if they were DRMed, they could still be downloaded.

**Comment by DTrombett** [comment]
No, DRM protected videos cannot be downloaded

**Comment by PacoH** [comment]
> STV (ITV Scotland) has its own site that is more accommodating.

I am able to download content from STV but they don't have the same content as ITV. Orphan Black is not available.

**Comment by Vangelis66** [comment]
> No, DRM protected videos **cannot be downloaded**

Being pedantic :smile: , **DRM-protected** videos **can still be downloaded** to disk (provided you know how :stuck_out_tongue_winking_eye: ), but in their "**encrypted**" form ONLY (no good for off-line viewing); it is the decryption part (**DRM circumvention**) that is **illegal** in most jurisdictions and the one part that `yt-dlp` will NEVER engage itself in, because it would then risk **DMCA** takedown requests by **Google** (owner of the prevailing DRM module, **Widevine**) and all content providers that choose to guard their offerings (from piracy, supposedly) by putting it behind DRM (the net effect being that the average user of those services, not inclined in the slightest to pirate media), is being extremely limited in the choice of browser/OS/device/way etc. to "enjoy" this media content :angry: ...

**Comment by PacoH** [comment]
> Being pedantic 😄 , **DRM-protected** videos **can still be downloaded** to disk (provided you know how 😜 ), but in their "**encrypted**" form ONLY (no good for off-line viewing); 

Not pedantic at all. Exactly as I thought. You can download DRMed content with Prime app but can only play them within the app.

**Comment by bashonly** [comment]
#5570
