### ISSUE TITLE
[Youtube] "Downloading 0 items" when downloading from shorts tab

### ISSUE THREAD

**Issue by nightcrawlereto** [yt-dlp/yt-dlp#10936]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

France

### Provide a description that is worded well enough to be understood

When I try to download every shorts videos from a channel using the shorts tab url, yt-dlp fails at least 40% of the time and returns "Downloading 0 items" meaning zero shorts video was downloaded. The remaining 60% of the time, it works perfectly. But it's still annoying.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp -P .\tmp\ -vU "https://www.youtube.com/@PitchAddict.shorts/shorts"
[debug] Command-line config: ['-P', '.\\tmp\\', '-vU', 'https://www.youtube.com/@PitchAddict.shorts/shorts']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.09.05.232840 from yt-dlp/yt-dlp-nightly-builds [0fba08485] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 7.0.1-essentials_build-www.gyan.dev (setts), ffprobe 7.0.1-essentials_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.08.30, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.2, websockets-13.0.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1832 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.09.05.232840 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.09.05.232840 from yt-dlp/yt-dlp-nightly-builds)
[youtube:tab] Extracting URL: https://www.youtube.com/@PitchAddict.shorts/shorts
[youtube:tab] @PitchAddict.shorts/shorts: Downloading webpage
[debug] [youtube:tab] Selected tab: 'shorts' (shorts), Requested tab: 'shorts'
[download] Downloading playlist: Pitch Addict - Shorts - Shorts
[youtube:tab] UCol37a-Gd1wVz6qbCJtF5mQ page 1: Downloading API JSON
[youtube:tab] UCol37a-Gd1wVz6qbCJtF5mQ page 2: Downloading API JSON
[youtube:tab] UCol37a-Gd1wVz6qbCJtF5mQ page 3: Downloading API JSON
[youtube:tab] UCol37a-Gd1wVz6qbCJtF5mQ page 4: Downloading API JSON
[youtube:tab] UCol37a-Gd1wVz6qbCJtF5mQ page 5: Downloading API JSON
[youtube:tab] UCol37a-Gd1wVz6qbCJtF5mQ page 6: Downloading API JSON
[youtube:tab] UCol37a-Gd1wVz6qbCJtF5mQ page 7: Downloading API JSON
[youtube:tab] UCol37a-Gd1wVz6qbCJtF5mQ page 8: Downloading API JSON
[youtube:tab] UCol37a-Gd1wVz6qbCJtF5mQ page 9: Downloading API JSON
[youtube:tab] UCol37a-Gd1wVz6qbCJtF5mQ page 10: Downloading API JSON
[youtube:tab] UCol37a-Gd1wVz6qbCJtF5mQ page 11: Downloading API JSON
[youtube:tab] UCol37a-Gd1wVz6qbCJtF5mQ page 12: Downloading API JSON
[youtube:tab] UCol37a-Gd1wVz6qbCJtF5mQ page 13: Downloading API JSON
[youtube:tab] UCol37a-Gd1wVz6qbCJtF5mQ page 14: Downloading API JSON
[youtube:tab] UCol37a-Gd1wVz6qbCJtF5mQ page 15: Downloading API JSON
[youtube:tab] UCol37a-Gd1wVz6qbCJtF5mQ page 16: Downloading API JSON
[youtube:tab] UCol37a-Gd1wVz6qbCJtF5mQ page 17: Downloading API JSON
[youtube:tab] UCol37a-Gd1wVz6qbCJtF5mQ page 18: Downloading API JSON
[youtube:tab] UCol37a-Gd1wVz6qbCJtF5mQ page 19: Downloading API JSON
[youtube:tab] Playlist Pitch Addict - Shorts - Shorts: Downloading 0 items
[download] Finished downloading playlist: Pitch Addict - Shorts - Shorts
```

**Comment by seproDev** [comment]
This has to do with the rollout of the new `shortsLockupViewModel` node. 
[Here](https://github.com/user-attachments/files/16910029/api.json) an api dump if someone wants to try and implement this.

**Comment by anikialt** [comment]
same problem, when its will be fixed?

**Comment by ariaamaia** [comment]
I'm having the same exact issue. Oh, well.

**Comment by usz-or** [comment]
Same problem
`yt-dlp --type shorts --exclude-regular-videos https://www.youtube.com/@ChannelName` doesn't work

**Comment by Vihershunde** [comment]
Same problem, tried master build, does not work

**Comment by anikialt** [comment]
> EDIT: I have merged #10938 in my local environment and now it works perfectly. If someone needs an explanation of how to do this, just reply I can help.

how i can  do it on windows ?

**Comment by usz-or** [comment]
When is this integrated into a new .exe release?

**Comment by bashonly** [comment]
@usz-or now if you run `yt-dlp --update-to nightly`

**Comment by usz-or** [comment]
> @usz-or now if you run `yt-dlp --update-to nightly`

Thanks do you know how to only get YouTube shorts from a channel?
Like `yt-dlp.exe https://www.youtube.com/@ChannelName/videos --match-filter "original_url!=/shorts/ & url!=/shorts/"`

**Comment by bashonly** [comment]
`yt-dlp "https://www.youtube.com/@channel/shorts"`

**Comment by Vihershunde** [comment]
> > EDIT: I have merged #10938 in my local environment and now it works perfectly. If someone needs an explanation of how to do this, just reply I can help.
> 
> how i can do it on windows ? dont download any videos from playlist

Update to nightly and run yt-dlp url/@channel/shorts

**Comment by gpmikhail** [comment]
> @usz-or now if you run `yt-dlp --update-to nightly`

works like a charm, thanks

**Comment by v0ry** [comment]
yt-dlp -f "bv+ba/b" <URL> 
and shorten the short url like https://youtube.com/shorts/saBSFNETjqE?si=7qpJYZU76DezNdhB
becomes yt-dlp -f "bv+ba/b" https://youtube.com/watch\?v\=saBSFNETjqE
