### ISSUE TITLE
Latest yt-dlp Nightly releases: Error creating child process. Access is denied.

### ISSUE THREAD

**Issue by Blue-Ike** [yt-dlp/yt-dlp#10949]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Hi I have been having trouble with using the nightly build ever since the 2024.08.26.232811 release. Whenever I enter a command in command-line I get this secondary popup window that appears and then disappears after a few seconds right after I enter a command in the cmd window of where I'm running yt-dlp and inputting these commands. On top of the popup command prompt window I can see the yt-dlp logo on the very top left corner of the window. And in the command-line a message saying "error creating child process." pops up on the first line and on the second line at the bottom it says "access is denied." And then the window quickly disappears. Afterwards I have to wait about a minute until I can attempt to enter a new command but no matter what command I enter this popup continues to show up and disappear without any of my commands working.

I do not have this issue with the latest Stable build (2024.08.06) of yt-dlp or the nightly build 2024.08.21.232751 or prior versions of the nightly. I am now currently only using the 2024.08.21 release of the nightly build which works for me. Is there some sort of administrator permission method I am missing? I did not have this issue before so I can't see how it could be that. Something changed or maybe was taken off the newest nightly release that perhaps the previous one had? I'm not sure. Please help.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['--verbose']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.08.21.232751 from yt-dlp/yt-dlp-nightly-builds [6f9e65374] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-116875-g3d0d0f68d5-20240905 (setts), ffprobe N-116875-g3d0d0f68d5-20240905
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.07.04, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.2, websockets-13.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1830 extractors
```

**Comment by seproDev** [comment]
At least from our side, there was no change regarding the build system in yt-dlp. The nightly builds also work fine on my Windows machine. To try and narrow this down further could you test a confirm a couple things for me?
Run
```
yt-dlp --update-to master@2024.08.26.205651
```
This does build still work?

Run
```
yt-dlp --update-to master@2024.08.26.211743
```
This does build still work?

**Comment by Blue-Ike** [comment]
Oh hey! I tried the first command you told me "yt-dlp --update-to master@2024.08.26.205.651 = And no change
I tried the second command you told me "yt-dlp --update-to master@2024.08.26.211743 = Seems to be working

After I updated yt-dlp to the second master you listed I entered yt-dlp -F [Url Address]
And the popup window did not come up this time and the command worked and listed the format details for the url I used.
What does this mean?

**Comment by seproDev** [comment]
That is really odd. There is practically no difference between `master@2024.08.26.211743` and `nightly@2024.08.26.232811`.
And you are saying `master@2024.08.26.211743` is working?
Can you send a verbose log after updating to that version, please?
```
yt-dlp -v
```

Also, if that version works, does updating to the latest master build work? `yt-dlp --update-to master` (if yes, please also share a verbose log after updating)

**Comment by Blue-Ike** [comment]
Yes, the master@2024.08.26.211743 is working. Here is the verbose log for it.

[debug] Command-line config: ['-v']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version master@2024.08.26.211743 from yt-dlp/yt-dlp-master-builds [41be32e78] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-116875-g3d0d0f68d5-20240905 (setts), ffprobe N-116875-g3d0d0f68d5-20240905
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.07.04, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.2, websockets-13.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1831 extractors

Will try updating now.

**Comment by Blue-Ike** [comment]
Okay I updated to master and the secondary command prompt window with the yt-dlp logo on the top left corner pops up but this time it seems to run the commands output in that window and then disappears making it unusable. After I updated to master I entered "yt-dlp -F [Url address]" and the pop up window came up but I can see the format details showing up but then once it's done the window closes and disappears. Then I tried it with the "yt-dlp -v" command and same thing happened. The verbose log appeared on the "yt-dlp command prompt popup window" and then once it was done quickly closed the popup window. :(

**Comment by seproDev** [comment]
I'm super confused...
Do you have some aggressive anti malware software running?

**Comment by Blue-Ike** [comment]
I use AVG Antivirus but I have it disabled. I also have McAfee Live but not sure if that is running or not or if it has a firewall on.

**Comment by seproDev** [comment]
A firewall would only interfere with the downloading, not the execution.
Could you try disabling everything (McAfee, AVG) and test if that is maybe interfering with yt-dlp?
The way yt-dlp provides a single executable file is sometimes detected as malicious due to the way it unpacks itself.

If that also doesn't help, could you try just installing yt-dlp from scratch. Follow these instructions.
- Create a new folder on your Desktop
- Download the latest yt-dlp master from here https://github.com/yt-dlp/yt-dlp-master-builds/releases/latest/download/yt-dlp.exe
- Place the exe inside your newly created folder
- Open that folder and in the address bar at the top enter `cmd`. Do not "Run as administrator" or anything like that. You should almost never run anything as administrator.
- In the newly opened window, type `yt-dlp -v` and report back if it worked.

**Comment by Blue-Ike** [comment]
seproDev said:"Could you try disabling everything (McAfee, AVG) and test if that is maybe interfering with yt-dlp?
The way yt-dlp provides a single executable file is sometimes detected as malicious due to the way it unpacks itself."

Oh my god man I think that's what it was! I opened up AVG Antivirus which is the anti-virus app my pc is running. In the window it showed "Web & Email" tab I was unprotected. And for "Computer" tab I was "protected". So I clicked on the "Computer" tab and it took me to the next screen which showed "File Shield" enabled. So I disabled it. I then updated to master from the master@2024.08.26.211743 update to "yt-dlp --update-to master" updated yt-dlp to master@2024.09.07.150630 sucessfully. Then I entered the command "yt-dlp -F [Url address] and this time NO Popup window and the format details showed and everything seems to be working fine now.

Conclusion the issue was my AVG Antivirus app. The "File Shield" setting being on is what was causing this issue it seems. Here is a screenshot of my Antivirus software and where I had to disable it for the nightly master to work.
![AVG screenshot](https://github.com/user-attachments/assets/bd56630f-6325-4803-b018-761318d44f4c)

**Comment by seproDev** [comment]
I, personally, think the default Windows defender is good enough for 99% of cases. Just don't download random exe files from sketchy websites, and you should mostly be good.
Other than that, I can't really help you with AVG. But good to know that we finally figured out what the issue was. Strange how they only had a problem with some of the versions.

**Comment by Blue-Ike** [comment]
Windows defender is fine. It's not a firewall issue as you said. 
I am looking into AVG and have found a "Blocked and Allowed Apps" setting where I can possibly manually add yt-dlp to the "Allowed list" to prevent AVG from blocking yt-dlp executable in the future for newly updates. And looking at the list yt-dlp is not on either the allowed or blocked lists as of now. So it's time for me to configure this for myself lol

Thank you for helping me this far. I really really really appreciate it as I had this problem for about two weeks now ever since the august 26 nightly release. 

Again Thank You very much sir.

**Comment by seproDev** [comment]
Glad I could help. I'll close this issue now.
