### ISSUE TITLE
ORF_ON: Split Chapter no longer working

### ISSUE THREAD

**Issue by annomatik** [yt-dlp/yt-dlp#10946]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Austria

### Provide a description that is worded well enough to be understood

Hi! A while ago, I could split orf_on videos with --split-chapters, if they had chapters in them. Apparently, ORF changed something, this now no longer seems to work for me.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-o', 'chapter:%(section_number)s %(section_title)s.%(ext)s', '--split-chapters', '-vU', 'https://on.orf.at/video/14240656']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.08.06 from yt-dlp/yt-dlp [4d9231208] (pip)
[debug] Python 3.9.2 (CPython armv7l 32bit) - Linux-5.15.36-v7l+-armv7l-with-glibc2.31 (OpenSSL 1.1.1n  15 Mar 2022, glibc 2.31)
[debug] exe versions: ffmpeg 4.3.4-0, ffprobe 4.3.4-0, phantomjs broken
[debug] Optional libraries: Cryptodome-3.9.7, brotli-1.0.9, certifi-2020.06.20, mutagen-1.45.1, requests-2.32.3, secretstorage-3.3.1, sqlite3-3.34.1, urllib3-2.1.0, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1830 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.08.06 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.08.06 from yt-dlp/yt-dlp)
[orf:on] Extracting URL: https://on.orf.at/video/14240656
[orf:on] 14240656: Downloading JSON metadata
[orf:on] 14240656: Downloading m3u8 information
[orf:on] 14240656: Downloading m3u8 information
[orf:on] 14240656: Downloading MPD manifest
[orf:on] 14240656: Downloading MPD manifest
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 14240656: Downloading 1 format(s): dash-p0va0br3002543-1+dash-p0aa0br192000-1
[debug] Invoking dashsegments downloader on "https://vod-ww.mdn.ors.at/cms-worldwide_episodes_nas/_definst_/nas/cms-worldwide_episodes/online/14240656_0008_hr.smil/manifest.mpd"
[dashsegments] Total fragments: 158
[download] Destination: Bewusst Gesund - Das Magazin vom 31.08.2024 [14240656].fdash-p0va0br3002543-1.mp4
[download] 100% of  560.35MiB in 00:01:18 at 7.15MiB/s
[debug] Invoking dashsegments downloader on "https://vod-ww.mdn.ors.at/cms-worldwide_episodes_nas/_definst_/nas/cms-worldwide_episodes/online/14240656_0008_hr.smil/manifest.mpd"
[dashsegments] Total fragments: 158
[download] Destination: Bewusst Gesund - Das Magazin vom 31.08.2024 [14240656].fdash-p0aa0br192000-1.m4a
[download] 100% of   36.38MiB in 00:00:12 at 2.89MiB/s
[Merger] Merging formats into "Bewusst Gesund - Das Magazin vom 31.08.2024 [14240656].mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:Bewusst Gesund - Das Magazin vom 31.08.2024 [14240656].fdash-p0va0br3002543-1.mp4' -i 'file:Bewusst Gesund - Das Magazin vom 31.08.2024 [14240656].fdash-p0aa0br192000-1.m4a' -c copy -map 0:v:0 -map 1:a:0 -movflags +faststart 'file:Bewusst Gesund - Das Magazin vom 31.08.2024 [14240656].temp.mp4'
Deleting original file Bewusst Gesund - Das Magazin vom 31.08.2024 [14240656].fdash-p0aa0br192000-1.m4a (pass -k to keep)
Deleting original file Bewusst Gesund - Das Magazin vom 31.08.2024 [14240656].fdash-p0va0br3002543-1.mp4 (pass -k to keep)
[SplitChapters] Chapter information is unavailable
```

**Comment by seproDev** [comment]
I'm actually surprised `--split-chapters` used to work since the extractor doesn't extract any chapter info.
Either way, I think you rather want to use `--concat-playlist never --extractor-args "orfon:prefer_segments_playlist"`
That way you are just downloading the individual segments instead of splitting them after the fact.

**Comment by annomatik** [comment]
yes, for a couple of releases that worked. A guy here on github recommended that approach, as for me the playlist approach was no longer working :-)

Thanks, works great!
