### ISSUE TITLE
Infinite downloaod progress from this site

### ISSUE THREAD

**Issue by RafaelLinux** [yt-dlp/yt-dlp#10948]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Spain / Russia

### Example URLs

https://ok.ru/video/7034934664735  (works)
https://ok.ru/video/7368152255008 (total size changes constantly)

### Provide a description that is worded well enough to be understood

Yt-dl displays the total size of some videos on that website in a strange way, increasing or decreasing the total size of the video. It is very strange.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
> yt-dlp -vU https://ok.ru/video/5140778912363
[debug] Command-line config: ['-vU', 'https://ok.ru/video/5140778912363']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.08.06 from yt-dlp/yt-dlp [4d9231208]
[debug] Python 3.11.9 (CPython x86_64 64bit) - Linux-6.10.7-1-default-x86_64-with-glibc2.40 (OpenSSL 3.1.4 24 Oct 2023, glibc 2.40)
[debug] exe versions: ffmpeg 7.0.2 (fdk,setts), ffprobe 7.0.2
[debug] Optional libraries: brotli-1.1.0, certifi-2024.07.04, mutagen-1.47.0, requests-2.32.3, sqlite3-3.46.0, urllib3-2.1.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Loaded 1830 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.08.06 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.08.06 from yt-dlp/yt-dlp)
[Odnoklassniki] Extracting URL: https://ok.ru/video/5140778912363
[Odnoklassniki] 5140778912363: Downloading desktop webpage
[Odnoklassniki] 5140778912363: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 5140778912363: Downloading 1 format(s): hls-4411
[debug] Invoking hlsnative downloader on "https://vd296.mycdn.me/expires/1725807174976/srcIp/79.117.167.93/pr/10/srcAg/CHROME/ms/185.226.53.5/type/5/sig/JLZCAfRF1_c/ct/8/urls/45.136.20.65/clientType/0/zs/65/id/2984480279147/video/"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 574
[download] Destination: Scoop 2006 1080p Castellano [5140778912363].mp4
[download]  12.4% of ~   3.07GiB at  217.32KiB/s ETA 02:39:44 (frag 71/574)^C
ERROR: Interrupted by user

----------> Pressed Ctrl-C cause it seems to be forever downloading <-------------------
```

**Comment by seproDev** [comment]
For this site, yt-dlp does not know the size of the video before downloading it. So instead, the size is estimated based on what you have already downloaded. The more you download, the more accurate that estimate will be. This does mean that in the beginning the estimated filesize does jump quite a lot.

**Comment by RafaelLinux** [comment]
However it doesn't happen with all videos from that site, seems to happen only with videos greater than 2GB.

**Comment by bashonly** [comment]
The longer the video the greater the variance can be
