### ISSUE TITLE
'Unable to extract yt initial data' in Seal

### ISSUE THREAD

**Issue by lalalasupa0** [yt-dlp/yt-dlp#10953]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Everywhere I guess

### Provide a description that is worded well enough to be understood

I'm not sure if I should've open this with `Core bug report`

I got this after solving `Sign in to confirm you’re not a bot. This helps protect our community...` (https://github.com/yt-dlp/yt-dlp/issues/10128)
I get it with stable too

Seal doesn't give me more info to put in `Complete Verbose Output`

`Confirm you are on the latest version using  yt-dlp -U`
I am

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
App version: 1.13.0 (11302)
Device information: Android 12 (API 31)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2024.09.07.232731

URL: https://youtube.com/clip/UgkxWLQCB_R9_YTJ8IarN9qsoUuSh-wQ1fjy?si=w2mfVhQPhQmQeQ3H
ERROR: [youtube:clip] UgkxWLQCB_R9_YTJ8IarN9qsoUuSh-wQ1fjy: Unable to extract yt initial data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

**Comment by bashonly** [comment]
provide verbose output

**Comment by lalalasupa0** [comment]
> provide verbose output

> Seal doesn't give me more info to put in Complete Verbose Output

I dunno what to do abt that

**Comment by seproDev** [comment]
Without a verbose log it is almost impossible to help as we just don't know what is happening. A random guess would be that this is network related, but could be any number of things.

With the command template you can also get a verbose log using seal. Alternatively if you want help here you must switch to using yt-dlp directly.
