### ISSUE TITLE
Bypass geolocation restriction on www.france.tv

### ISSUE THREAD

**Issue by pavel167** [yt-dlp/yt-dlp#10958]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a site-specific feature
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

France

### Example URLs

https://www.france.tv/films/6404240-le-cercle-des-poetes-disparus.html

### Provide a description that is worded well enough to be understood

Hello,
On the www.arte.tv you embedded nice feature allowing to bypass geolocation restriction.
Can you do the same on www.france.tv.
Thanks.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
(ytdlp_env1) pavel@MISSURI:~/ytdlp_env1$ yt-dlp -vU https://www.france.tv/films/6404240-le-cercle-des-poetes-disparus.html
[debug] Command-line config: ['-vU', 'https://www.france.tv/films/6404240-le-cercle-des-poetes-disparus.html']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.08.06 from yt-dlp/yt-dlp [4d9231208] (pip)
[debug] Python 3.12.3 (CPython x86_64 64bit) - Linux-6.8.0-41-generic-x86_64-with-glibc2.39 (OpenSSL 3.0.13 30 Jan 2024, glibc 2.39)
[debug] exe versions: ffmpeg 6.1.1 (setts), ffprobe 6.1.1
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.08.30, mutagen-1.47.0, requests-2.32.3, sqlite3-3.45.1, urllib3-2.2.2, websockets-13.0.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1830 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.08.06 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.08.06 from yt-dlp/yt-dlp)
[FranceTVSite] Extracting URL: https://www.france.tv/films/6404240-le-cercle-des-poetes-disparus.html
[FranceTVSite] 6404240-le-cercle-des-poetes-disparus: Downloading webpage
[FranceTV] Extracting URL: francetv:21163cca-6903-469d-ba11-333ac74dc97c#__youtubedl_smuggle=%7B%22hostname%22%3A+%22www.france.tv%22%7D
[FranceTV] 21163cca-6903-469d-ba11-333ac74dc97c: Downloading desktop chrome video JSON
[FranceTV] 21163cca-6903-469d-ba11-333ac74dc97c: Downloading mobile safari video JSON
[FranceTV] 21163cca-6903-469d-ba11-333ac74dc97c: Downloading signed dash manifest URL
[FranceTV] 21163cca-6903-469d-ba11-333ac74dc97c: Downloading MPD manifest
WARNING: [FranceTV] Failed to download MPD manifest: HTTP Error 403: Forbidden
[FranceTV] 21163cca-6903-469d-ba11-333ac74dc97c: Downloading signed hls manifest URL
[FranceTV] 21163cca-6903-469d-ba11-333ac74dc97c: Downloading m3u8 information
WARNING: [FranceTV] Failed to download m3u8 information: HTTP Error 403: Forbidden
[FranceTV] 21163cca-6903-469d-ba11-333ac74dc97c: Checking for geo-restriction
ERROR: [FranceTV] 21163cca-6903-469d-ba11-333ac74dc97c: This video is not available from your location due to geo restriction
This video is available in France.
You might want to use a VPN or a proxy server (with --proxy) to workaround.
Traceback (most recent call last):
  File "/home/pavel/ytdlp_env1/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 1626, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pavel/ytdlp_env1/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 1761, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "/home/pavel/ytdlp_env1/lib/python3.12/site-packages/yt_dlp/extractor/common.py", line 740, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pavel/ytdlp_env1/lib/python3.12/site-packages/yt_dlp/extractor/francetv.py", line 247, in _real_extract
    return self._extract_video(video_id, hostname=hostname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pavel/ytdlp_env1/lib/python3.12/site-packages/yt_dlp/extractor/francetv.py", line 201, in _extract_video
    self.raise_geo_restricted(countries=self._GEO_COUNTRIES, metadata_available=True)
  File "/home/pavel/ytdlp_env1/lib/python3.12/site-packages/yt_dlp/extractor/common.py", line 1254, in raise_geo_restricted
    raise GeoRestrictedError(msg, countries=countries)
yt_dlp.utils.GeoRestrictedError: [FranceTV] 21163cca-6903-469d-ba11-333ac74dc97c: This video is not available from your location due to geo restriction

(ytdlp_env1) pavel@MISSURI:~/ytdlp_env1$
```

**Comment by seproDev** [comment]
This is something very site specific. What works for one site, doesn't necessarily work for another.
Unless you know of a way to bypass the geo restriction for france.tv, there is nothing to do here.

**Comment by pavel167** [comment]
The only way I know is using VPN.
But since 3 weeks the french server from my paid VPN is "blacklisted", i.e. many links are unavailable for seeing/downloading.

**Comment by seproDev** [comment]
Then you will need to look into a better VPN provider.
I'll close this issue, since this isn't something that can be changed in yt-dlp.

**Comment by pavel167** [comment]
Ok, thanks.
