### ISSUE TITLE
What am I doing wrong?

### ISSUE THREAD

**Issue by ApplicationError** [yt-dlp/yt-dlp#10966]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I looked through the known issues -- couldn't find this one, so I am assuming it's a user error (me). 

bash-3.2$ yt-dlp -vU https://www.youtube.com/watch?v=QjNSisBnf6U
[debug] Command-line config: ['-vU', 'https://www.youtube.com/watch?v=QjNSisBnf6U']
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/local/bin/yt-dlp/__main__.py", line 19, in <module>
  File "/usr/local/bin/yt-dlp/yt_dlp/__init__.py", line 869, in main
  File "/usr/local/bin/yt-dlp/yt_dlp/__init__.py", line 830, in _real_main
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 667, in __init__
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3743, in _setup_opener
  File "/usr/local/bin/yt-dlp/yt_dlp/utils.py", line 1027, in make_HTTPS_handler
AttributeError: module 'certifi' has no attribute 'where'

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.youtube.com/watch?v=QjNSisBnf6U']
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/local/bin/yt-dlp/__main__.py", line 19, in <module>
  File "/usr/local/bin/yt-dlp/yt_dlp/__init__.py", line 869, in main
  File "/usr/local/bin/yt-dlp/yt_dlp/__init__.py", line 830, in _real_main
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 667, in __init__
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3743, in _setup_opener
  File "/usr/local/bin/yt-dlp/yt_dlp/utils.py", line 1027, in make_HTTPS_handler
AttributeError: module 'certifi' has no attribute 'where'
```

**Comment by Superkaizhen07** [comment]
update code to request new format from youtube cus youtube have change format for now bro
my issue now is cannot fetch link from channel url

**Comment by dirkf** [comment]
The quoted log doesn't match the logged command options, so it's not clear what version you're running or where, but in older versions the backtrace shown might be avoided using the `no-certifi` compat option (see manual).

The horse's mouth says that [your `certifi` installation is problematic](https://github.com/certifi/python-certifi/issues/107).

**Comment by bashonly** [comment]
Also it looks like you are running a very old version of yt-dlp. See the [installation wiki page](https://github.com/yt-dlp/yt-dlp/wiki/Installation) for alternative installation methods

**Comment by ApplicationError** [comment]
Thanks for all the help!

I've been uninstalling things, installing things, but just can't get it to work. Any help would really be appreciated.

bash-3.2$ yt-dlp --version
2024.08.06
bash-3.2$ youtube-dl -f 137 https://www.youtube.com/watch?v=QjNSisBnf6U
[youtube] QjNSisBnf6U: Downloading webpage
WARNING: unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
ERROR: unable to download video data: HTTP Error 403: Forbidden
bash-3.2$

**Comment by seproDev** [comment]
youtube-dl and yt-dlp are two different pieces of software.
youtube-dl has not had a release since 2021. This is the issue tracker for yt-dlp which is a fork of youtube-dl and is still receiving regular updates.
> bash-3.2$ youtube-dl -f 137 https://www.youtube.com/watch?v=QjNSisBnf6U

So you probably want to run `yt-dlp` here instead

**Comment by ApplicationError** [comment]
> youtube-dl and yt-dlp are two different pieces of software. youtube-dl has not had a release since 2021. This is the issue tracker for yt-dlp which is a fork of youtube-dl and is still receiving regular updates.
> 
> > bash-3.2$ youtube-dl -f 137 https://www.youtube.com/watch?v=QjNSisBnf6U
> 
> So you probably want to run `yt-dlp` here instead

Wow, I am an idiot. Thank you SO much!

**Comment by geerlingguy** [comment]
Note: I had a similar error, from an old pip install...

The fix was:

```
pip install trash-cli
trash-put $SITE_PACKAGES_FOLDER/certifi*
pip install --upgrade certifi
```

Just posting in case I run into the same issue again :)
