### ISSUE TITLE
Add a specified network card and ip to access youtube to counter youtube's bot detection mechanism

### ISSUE THREAD

**Issue by chatop2020** [yt-dlp/yt-dlp#10964]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Add a specified network card and ip to access youtube to counter youtube's bot detection mechanism

Like this 

yt-dlp --interface eth0 -F https://www.youtube.com/watch?v=cr161aUOCWc
yt-dlp --ipaddress 10.1.1.1 -F https://www.youtube.com/watch?v=cr161aUOCWc
yt-dlp --ipaddress 2608:a8a0:3:4a7::a -F https://www.youtube.com/watch?v=cr161aUOCWc

like this ,Visit https://www.youtube.com/watch?v=cr161auocwc through eth0 or 10.1.1.1 or 2608:a8a0:3:4a7::a

When the server has multiple IPs, especially when IPv6/64, it can effectively fight the robot detection mechanism of YouTube

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by seproDev** [comment]
You mean `--source-address`? https://github.com/yt-dlp/yt-dlp#network-options
