### ISSUE TITLE
Tiktok and some other videos not working in some apps / Creating archive for downloaded videos

### ISSUE THREAD

**Issue by BenderBRod** [yt-dlp/yt-dlp#10965]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Since discussions are disabled and i cant use Discord:

1.
When i download tiktoks especially, they just dont want to work in apps like telegram, session, not even in the browser.
I found out the codec might not be supported, but HEVC/h265 is supported everywhere and the highest quality is always in HEVC.
In telegram i cant even upload the videos, in session only sound is playing but offline they work fine in every player.
What the hell am i doing wrong?

2.
When i started archiving, i did not know i have to create an archive of the video id's to only download new files since i was used to gallery-dl's option -A 1
Is there a way to get all the id's of my downloaded videos without downloading them again?
I played around a bit but nothing seems to work here either.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
> When i download tiktoks especially, they just dont want to work in apps like telegram, session, not even in the browser.

Almost certainly due to the h265 video codec

> Is there a way to get all the id's of my downloaded videos without downloading them again?

There is no way to do this with yt-dlp unless you used `--write-info-json` with all your downloads. If not, but your output template (`-o`) included `id`, then you could use an external script to parse all of the downloaded filenames and write a mock archive file

**Comment by BenderBRod** [comment]
> Almost certainly due to the h265 video codec
But i can play other h265 files everywhere just fine
Can i provide any kind of log to give you more information?

> There is no way to do this with yt-dlp unless you used `--write-info-json` with all your downloads. If not, but your output template (`-o`) included `id`, then you could use an external script to parse all of the downloaded filenames and write a mock archive file

Sadly i did not. Only upload date and filename.
I thought simulating the download but actually saving the id's could work but that didnt.
Is it hard to implement the -A 1 option from gallery-dl? Why not just break on existing? It is so great!

**Comment by bashonly** [comment]
> But i can play other h265 files everywhere just fine

The platform that's embedding the media needs to support h265 too, not just your system/browser. Do a web search for "telegram embedding h265" or "discord embedding h265" etc and you'll see this is not a yt-dlp issue. You either need to download a compatible format (e.g. h264 video) or re-encode the download

> I thought simulating the download but actually saving the id's could work but that didnt.

You can kinda make this work, e.g. something like

```
yt-dlp --flat-playlist --simulate --print-to-file "%(extractor_key)s %(id)s" "mock_archive.txt" "URL"
```

but then you'll have to reprocess `mock_archive.txt` with your own script (or manually) to convert the `extractor_key` on each line to all lowercase
