### ISSUE TITLE
[YouTube] 403 error sometimes while downloading videos

### ISSUE THREAD

**Issue by joaquinito2070** [yt-dlp/yt-dlp#10961]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Worldwide

### Provide a description that is worded well enough to be understood

403 error while downloading some formats sometimes.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
H:\616>yt-dlp -f 616+251 -N 8 --extractor-args "youtube:player_client=all" --impersonate safari ytsearch:"Minnie Bow-Too
ns Camp Minnie Compilation"
[youtube:search] Extracting URL: ytsearch:Minnie Bow-Toons Camp Minnie Compilation
[download] Downloading playlist: Minnie Bow-Toons Camp Minnie Compilation
[youtube:search] query "Minnie Bow-Toons Camp Minnie Compilation": Downloading web client config
[youtube:search] query "Minnie Bow-Toons Camp Minnie Compilation" page 1: Downloading API JSON
[youtube:search] Playlist Minnie Bow-Toons Camp Minnie Compilation: Downloading 1 items of 1
[download] Downloading item 1 of 1
[youtube] Extracting URL: https://www.youtube.com/watch?v=SUcbIC1EsJU
[youtube] SUcbIC1EsJU: Downloading webpage
[youtube] SUcbIC1EsJU: Downloading ios player API JSON
[youtube] SUcbIC1EsJU: Downloading ios music player API JSON
[youtube] SUcbIC1EsJU: Downloading ios creator player API JSON
[youtube] SUcbIC1EsJU: Downloading web embedded client config
[youtube] SUcbIC1EsJU: Downloading player 5f8f5b0f
[youtube] SUcbIC1EsJU: Downloading web embedded player API JSON
[youtube] SUcbIC1EsJU: Downloading web safari player API JSON
[youtube] SUcbIC1EsJU: Downloading web music client config
[youtube] SUcbIC1EsJU: Downloading web music player API JSON
[youtube] SUcbIC1EsJU: Downloading web creator player API JSON
[youtube] SUcbIC1EsJU: Downloading tv player API JSON
[youtube] SUcbIC1EsJU: Downloading tv embedded player API JSON
[youtube] SUcbIC1EsJU: Downloading mweb player API JSON
[youtube] SUcbIC1EsJU: Downloading android player API JSON
[youtube] SUcbIC1EsJU: Downloading android music player API JSON
[youtube] SUcbIC1EsJU: Downloading android creator player API JSON
[youtube] SUcbIC1EsJU: Downloading android vr player API JSON
[youtube] SUcbIC1EsJU: Downloading android testsuite player API JSON
[youtube] SUcbIC1EsJU: Downloading android producer player API JSON
[youtube] SUcbIC1EsJU: Downloading mediaconnect player API JSON
WARNING: [youtube] SUcbIC1EsJU: android client formats are broken and may yield HTTP Error 403. They will be deprioritized
[youtube] SUcbIC1EsJU: Downloading m3u8 information
[youtube] SUcbIC1EsJU: Downloading m3u8 information
[youtube] SUcbIC1EsJU: Downloading m3u8 information
[youtube] SUcbIC1EsJU: Downloading m3u8 information
[youtube] SUcbIC1EsJU: Downloading m3u8 information
[youtube] SUcbIC1EsJU: Downloading m3u8 information
[info] SUcbIC1EsJU: Downloading 1 format(s): 616+251
[download] Minnie's Bow-Toons： Camp Minnie! 🎀🏕 ｜ NEW 30 Minute Compilation ｜ @disneyjr [SUcbIC1EsJU].f616.mp4 has already been downloaded
[download] 100% of    1.05GiB
ERROR: unable to download video data: HTTP Error 403: Forbidden
[download] Finished downloading playlist: Minnie Bow-Toons Camp Minnie Compilation
```

**Comment by bashonly** [comment]
Not a verbose log. Don't use `player_client=all`. Some clients return broken formats due to po_token requirement
