### ISSUE TITLE
Sony LIV not working 

### ISSUE THREAD

**Issue by Sahil-7746** [yt-dlp/yt-dlp#10960]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

India

### Provide a description that is worded well enough to be understood

https://www.sonyliv.com/shows/the-kapil-sharma-show-1700000083/season/1

WARNING: skipping cookie file entry due to invalid length 6: '.tapad.com\tTRUE\t/\tTRUE\t13374140878160636\tTapAd_3WAY_SYNCS\n'
ERROR: [generic] Unable to download webpage: [Errno 104] Connection reset by peer (caused by TransportError('[Errno 104] Connection reset by peer'))

Uploading Screenrecorder-2024-09-08-23-07-13-701.mp4…

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
https://www.sonyliv.com/shows/the-kapil-sharma-show-1700000083/season/1

WARNING: skipping cookie file entry due to invalid length 6: '.tapad.com\tTRUE\t/\tTRUE\t13374140878160636\tTapAd_3WAY_SYNCS\n'
ERROR: [generic] Unable to download webpage: [Errno 104] Connection reset by peer (caused by TransportError('[Errno 104] Connection reset by peer'))
```

**Comment by bashonly** [comment]
That's not a verbose log. Please share complete verbose output as instructed in the issue template

It looks like there is a problem with your cookiefile, and your network

**Comment by bashonly** [comment]
show verbose output though!

**Comment by Sahil-7746** [comment]
How

**Comment by bashonly** [comment]
> ### Provide verbose output that clearly demonstrates the problem
> - Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
> - **If** using API, add `'verbose': True` to `YoutubeDL` params instead
> - Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by Sahil-7746** [comment]
Uploading Screenrecorder-2024-09-11-15-14-23-328.mp4…

**Comment by Sahil-7746** [comment]
https://github.com/user-attachments/assets/ef61640a-3889-4711-aeb8-54f26cf6ec2c

**Comment by zaednasr** [comment]
@bashonly all the app is essentially doing there is a json dump to fetch data
