### ISSUE TITLE
[Question] Add brackets and similar characters to folder name.

### ISSUE THREAD

**Issue by fosam** [yt-dlp/yt-dlp#1097]
## Checklist

- [X] I'm asking a question
- [X] I've looked through the README and FAQ for similar questions
- [X] I've searched the bugtracker for similar questions including closed ones

## Question

How can i make yt-dlp create a folder with brackets and similar characters?

Let's take this example:

```
# Download all playlists of YouTube channel/user keeping each playlist in separate directory:

yt-dlp -o '%(uploader)s/%(playlist)s/%(playlist_index)s - %(title)s.%(ext)s' https://www.youtube.com/user/TheLinuxFoundation/playlists
```

I want the playlist folder to look like something like this: (name of playlist) or [name of playlist] etc..

How can i achieve this?

**Comment by pukkandan** [comment]
If you want brackets, just use brackets!

`[%(playlist)s]`

**Comment by fosam** [comment]
I see, i was doing it wrong `%[(playlist)]s`
Thanks!
