### ISSUE TITLE
[Kick.com] New site rollout causing issue

### ISSUE THREAD

**Issue by phere-x** [yt-dlp/yt-dlp#10975]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

USA

### Provide a description that is worded well enough to be understood

Prior to this it worked perfectly fine. But recently they rolled out their new site with mostly UI changes. 

First thing I noticed was how their VOD urls are laballed now
Before: `https://kick.com/video/{LONG_VOD_ID}`
Now: `https://kick.com/{Channel}/videos/{LONG_VOD_ID}`

Using the new URLs returns `ERROR: [kick:live] {Channel}: The channel is not currently live`

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
$ yt-dlp https://kick.com/xqc/videos/8dd97a8d-e17f-48fb-8bc3-565f88dbc9ea -vU
[debug] Command-line config: ['https://kick.com/xqc/videos/8dd97a8d-e17f-48fb-8bc3-565f88dbc9ea', '-vU']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.08.06 from yt-dlp/yt-dlp [4d9231208] (pip)
[debug] Python 3.8.10 (CPython x86_64 64bit) - Linux-5.15.107-1-pve-x86_64-with-glibc2.29 (OpenSSL 1.1.1f  31 Mar 2020, glibc 2.31)
[debug] exe versions: ffmpeg 4.2.7, ffprobe 4.2.7
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2020.12.05, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.31.1, urllib3-2.2.1, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1830 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.08.06 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.08.06 from yt-dlp/yt-dlp)
[kick:live] Setting up session
[debug] [kick:live] kick.com did not set XSRF-TOKEN cookie
[kick:live] Extracting URL: https://kick.com/xqc/videos/8dd97a8d-e17f-48fb-8bc3-565f88dbc9ea
[kick:live] xqc: Downloading API JSON
ERROR: [kick:live] xqc: The channel is not currently live
  File "/home/sv/.local/lib/python3.8/site-packages/yt_dlp/extractor/common.py", line 740, in extract
    ie_result = self._real_extract(url)
  File "/home/sv/.local/lib/python3.8/site-packages/yt_dlp/extractor/kick.py", line 76, in _real_extract
    raise UserNotLive(video_id=channel)
```

**Comment by bashonly** [comment]
```diff
diff --git a/yt_dlp/extractor/kick.py b/yt_dlp/extractor/kick.py
index 1c1b2a177..691f6d53e 100644
--- a/yt_dlp/extractor/kick.py
+++ b/yt_dlp/extractor/kick.py
@@ -67,7 +67,7 @@ class KickIE(KickBaseIE):
 
     @classmethod
     def suitable(cls, url):
-        return False if KickClipIE.suitable(url) else super().suitable(url)
+        return False if (KickVODIE.suitable(url) or KickClipIE.suitable(url)) else super().suitable(url)
 
     def _real_extract(self, url):
         channel = self._match_id(url)
@@ -98,9 +98,9 @@ def _real_extract(self, url):
 
 class KickVODIE(KickBaseIE):
     IE_NAME = 'kick:vod'
-    _VALID_URL = r'https?://(?:www\.)?kick\.com/video/(?P<id>[\da-f]{8}-(?:[\da-f]{4}-){3}[\da-f]{12})'
+    _VALID_URL = r'https?://(?:www\.)?kick\.com/[\w-]+/videos/(?P<id>[\da-f]{8}-(?:[\da-f]{4}-){3}[\da-f]{12})'
     _TESTS = [{
-        'url': 'https://kick.com/video/e74614f4-5270-4319-90ad-32179f19a45c',
+        'url': 'https://kick.com/xqc/videos/e74614f4-5270-4319-90ad-32179f19a45c',
         'md5': '3870f94153e40e7121a6e46c068b70cb',
         'info_dict': {
             'id': 'e74614f4-5270-4319-90ad-32179f19a45c',
```

**Comment by ESDAone** [comment]
How do I apply this patch (If that's even possible)? Sorry, complete newb here. I'm just trying to download some Kick VODs

**Comment by grqz** [comment]
```sh
git clone https://github.com/yt-dlp/yt-dlp.git
cd yt-dlp
git apply
# copy the patch here, ending with EOF(can be ctrl+Z(win) or ctrl+D(unix-based))
python3 -m yt_dlp <your args>
# in some cases, it's py or python
```
