### ISSUE TITLE
[Broken] Vbox7 issues 

### ISSUE THREAD

**Issue by chiphu** [yt-dlp/yt-dlp#1098]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running yt-dlp version **2021.09.25**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[Vbox7] f9840099c3: Downloading JSON metadata
[Vbox7] f9840099c3: Downloading webpage
WARNING: [Vbox7] unable to extract JSON-LD ; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
WARNING: [Vbox7] unable to extract thumbnail URL; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
[info] f9840099c3: Downloading 1 format(s): 0
[download] Destination: Where there's a wheel there's a way - Japanese unicycle specialist shows off her skills [f9840099c3].mpd
[download] 100% of 58.76KiB in 00:02

```

## Description

What it downloaded from the following link was a useless tiny piece of file: 
https://www.vbox7.com/play:f9840099c3

I also tried some other links from Vbox7 and got the same issue. Please fix! Thank you so very much!

**Comment by u-spec-png** [comment]
Upstream pr https://github.com/ytdl-org/youtube-dl/pull/29680

**Comment by pukkandan** [comment]
Looks like they are using a workaround. The ideal solution would be to improve the mpd parser to handle the format

**Comment by iFUCKINGHATEcomputers** [comment]
This needs to be urgently fixed - on February 22nd Vbox7 will be privating nearly all their videos. Archivists and regular users need an easy way to back up videos/channels, whether individually or en masse.

https://www.reddit.com/r/Archiveteam/comments/19d6ou7/video_platform_vbox7_is_about_to_restrict_access/
