### ISSUE TITLE
SBS Australia On Demand Error: No Formats Are Available

### ISSUE THREAD

**Issue by cf100clunk** [yt-dlp/yt-dlp#10983]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Australia

### Provide a description that is worded well enough to be understood

After successfully extracting several video files from SBS Australia there was suddenly an error message that said "No formats are available". I get that error always now from SBS Australia.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [x] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--verbose', 'https://www.sbs.com.au/ondemand/tv-series/darkness-those-who-kill/season-4/darkness-those-who-kill-s4-ep8/2365873219814']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.09.08.232909 from yt-dlp/yt-dlp-nightly-builds [d1c4d88b2] (zip)
[debug] Python 3.11.2 (CPython x86_64 64bit) - Linux-6.5.0-5mx-ahs-amd64-x86_64-with-glibc2.36 (OpenSSL 3.0.14 4 Jun 2024, glibc 2.36)
[debug] exe versions: ffmpeg 6.0.1 (fdk,setts), ffprobe 6.0.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.11.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.46.0, requests-2.28.1, sqlite3-3.40.1, urllib3-1.26.12, websockets-10.4
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Loaded 1832 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.09.08.232909 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.09.08.232909 from yt-dlp/yt-dlp-nightly-builds)
[debug] Using fake IP 1.129.16.38 (AU) as X-Forwarded-For
[SBS] Extracting URL: https://www.sbs.com.au/ondemand/tv-series/darkness-those-who-kill/season-4/darkness-those-who-kill-s4-ep8/2365873219814
[SBS] 2365873219814: Downloading SMIL file
[SBS] 2365873219814: Checking geo-restriction
ERROR: [SBS] 2365873219814: No formats are available; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/bin/yt-dlp/yt_dlp/extractor/common.py", line 740, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/bin/yt-dlp/yt_dlp/extractor/sbs.py", line 111, in _real_extract
    self.raise_no_formats('No formats are available', video_id=video_id)
  File "/bin/yt-dlp/yt_dlp/extractor/common.py", line 1263, in raise_no_formats
    raise ExtractorError(msg, expected=expected, video_id=video_id)
```

**Comment by gamer191** [comment]
The example URL gives me a 404 error (in Australia). Does it work for you?

**Comment by bashonly** [comment]
> This content expired on 9/11/24 2:00 PM.

```xml
<smil xmlns="http://www.w3.org/2005/SMIL21/Language">
	<head>
	</head>
	<body>
	<seq>
		<ref src="http://link.theplatform.com/s/errorFiles/Unavailable.flv" title="Expired" abstract="This content expired on 9/11/24 2:00 PM.">
			<param name="isException" value="true"/>
			<param name="exception" value="Expired"/>
			<param name="responseCode" value="403"/>
			<param name="correlationId" value="1c1cf619-2b4b-4158-9421-c971f4094fc6"/>
		</ref>
	</seq>
	</body>
</smil>
```
