### ISSUE TITLE
Best video format does not download best video (in terms of a bitrate and a file size)

### ISSUE THREAD

**Issue by slrslr** [yt-dlp/yt-dlp#10985]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

ytd -F --simulate https://www.youtube.com/watch?v=-E7roCsC6Rc
returns:
```
ID      EXT   RESOLUTION FPS CH │   FILESIZE   TBR PROTO │ VCODEC          VBR ACODEC      ABR ASR MORE INFO
398     mp4   1280x720    30    │  280.71MiB  566k https │ av01.0.05M.08  566k video only          720p, mp4_dash
232     mp4   1280x720    30    │ ~  1.12GiB 2313k m3u8  │ avc1.4D401F   2313k video only
136     mp4   1280x720    30    │  266.09MiB  537k https │ avc1.4D401F    537k video only          720p, mp4_dash
609     mp4   1280x720    30    │ ~862.86MiB 1741k m3u8  │ vp09.00.31.08 1741k video only
247     webm  1280x720    30    │  282.11MiB  569k https │ vp09.00.31.08  569k video only          720p, webm_dash
```

yt-dlp -vU --simulate --write-subs --sub-langs all --merge-output-format=mp4 --format="bv*[height<=720]+ba/b" https://www.youtube.com/watch?v=-E7roCsC6Rc
returns:
`Downloading 1 format(s): 247+251`

yet the video format 247 has much lower bit rate and file size than other formats. This is confusing and I am unable to figure out how to make it download really best video quality. Same issue is with the audio.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
$ yt-dlp -vU --write-subs --sub-langs all --merge-output-format=mp4 --format="bv*[height<=720]+ba/b" https://www.youtube.com/watch?v=-E7roCsC6Rc
[debug] Command-line config: ['-vU', '--write-subs', '--sub-langs', 'all', '--merge-output-format=mp4', '--format=bv*[height<=720]+ba/b', 'https://www.youtube.com/watch?v=-E7roCsC6Rc']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.09.08.232909 from yt-dlp/yt-dlp-nightly-builds [d1c4d88b2] (zip)
[debug] Python 3.9.2 (CPython x86_64 64bit) - Linux-5.10.0-32-amd64-x86_64-with-glibc2.31 (OpenSSL 1.1.1w  11 Sep 2023, glibc 2.31)
[debug] exe versions: ffmpeg 4.3.7-0, ffprobe 4.3.7-0
[debug] Optional libraries: Cryptodome-3.9.7, brotli-1.1.0, certifi-2020.06.20, mutagen-1.45.1, pyxattr-0.7.2, requests-2.32.3, secretstorage-3.3.1, sqlite3-3.34.1, urllib3-2.2.2, websockets-13.0.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1832 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.09.08.232909 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.09.08.232909 from yt-dlp/yt-dlp-nightly-builds)
[youtube] Extracting URL: https://www.youtube.com/watch?v=-E7roCsC6Rc
[youtube] -E7roCsC6Rc: Downloading webpage
[youtube] -E7roCsC6Rc: Downloading ios player API JSON
[youtube] -E7roCsC6Rc: Downloading web creator player API JSON
[debug] Loading youtube-nsig.e38bb6de from cache
[debug] [youtube] Decrypted nsig RNmTEuw7R_FwmFIX => We9UnqCnv_jTuQ
[youtube] -E7roCsC6Rc: Downloading m3u8 information
[info] -E7roCsC6Rc: Downloading subtitles: ar, en, hi, id, pt-BR, es, th
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[info] -E7roCsC6Rc: Downloading 1 format(s): 247+251
```

**Comment by bashonly** [comment]
Please review the [sorting formats section of the README](https://github.com/yt-dlp/yt-dlp?tab=readme-ov-file#sorting-formats)

**Comment by slrslr** [comment]
I am unable to figure out right parameters of the -S switch. Spent around 20 minutes on that.
Please let me know how to adjust my above mentioned command to use HD (720px) resolution (res) and out of that, best quality - possibly sorted by the size (size) and bitrate (tbr?).
It seems to me like a problem that should be fixed, because i am not getting best quality using command in my leading post of this issue.

**Comment by bashonly** [comment]
This is not a bug. This is the intended and expected behavior.

Firstly, it should be noted that 609 and 247 are exactly the same quality; youtube's m3u8 formats' bitrates/filesizes are inaccurate/exaggerated. 609 is just the HLS variant of 247 in an mp4 container. They will look identical if you download both and compare side-by-side.

Also, maybe more importantly: higher bitrate does not necessarily mean higher quality. The only thing bitrate actually tells you is how big the file will be for a given duration. Higher efficiency codecs can yield better quality at lower bitrates, e.g. lower bitrate vp9 can look better than higher bitrate avc/h264.

I suggested that you read the sorting formats section of the README because it explains how formats are sorted by default: video codec has higher priority than bitrate, and the vp9 codec has the highest priority among all video codecs. You would use the `-S` option to tweak this sorting to your liking.

> HD (720px) resolution (res) and out of that, best quality - possibly sorted by the size (size) and bitrate (tbr?)

`-S res:720,br`

**Comment by slrslr** [comment]
Out of 720p formats, the leading command not downloaded highest quality format per my observation.
I have downloaded several percent of each format file and compared seemingly same video frame of each file. Significantly best quality was format 398 (av01.0.05M.08 mp4_dash). Maybe yt-dlp failed to provide best quality format because it is non standard (less supported) AV1 codec as you have said this:

> sorted by default: video codec has higher priority than bitrate, and the vp9 codec has the highest priority among all video codecs.

Yours linked format sorting page seemingly prioritize AV01 codec:

> vcodec: Video Codec (av01 > vp9.2 > vp9 > h265 > h264 > vp8 > h263 > theora > other)

but it was not true in my case and the parameter best* or bv did not provide best quality video.

I assume that if I want to prefer best video codec (and possibly also really best quality) and maximum HD resolution, i can do:
--format="bv*[height<=720]+ba/b" -S vcodec
or just:
-S vcodec,res:720

?

**Comment by bashonly** [comment]
> `-S vcodec,res:720`

yep, that'll work

**Comment by slrslr** [comment]
Thanks, do you have any comment on this part?

> what is weird is that "-S vcodec" and "-S codec" wants to combine mp4_dash AV1 video with webm_dash Opus audio

One would rather expect mp4_dash+m4a_dash which is available under format 140

```
youtube-dl -F vcodec,res:720 --simulate https://www.youtube.com/watch?v=-E7roCsC6Rc # list formats
youtube-dl -S vcodec,res:720 --simulate https://www.youtube.com/watch?v=-E7roCsC6Rc # simulate download
```

any universal tweak (not applicable just to this video/site) of that -S parameter which would ensure more compatible audio is selected for the best video (in this case AV1) format?

**Comment by bashonly** [comment]
`-S vcodec,res:720,acodec:aac`
