### ISSUE TITLE
zsh completions are not installed

### ISSUE THREAD

**Issue by hseg** [yt-dlp/yt-dlp#110]
## Checklist
- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running yt-dlp version **2021.02.24**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Description

`python setup.py build` skips the zsh completion file because it expects to find `_yt-dlp` but finds `yt-dlp.zsh` instead.
One possibility is to abandon installing completions via `setup.py` and have them installed via `make` instead, in which case it'd probably be a good idea to have the `yt-dlp` target either call `setup.py` or build the self-executing zip based on a flag.
Another possibilty (which I haven't researched in depth yet) is to try prodding `setup.py` into accepting `yt-dlp.zsh` and renaming it.
In any case, it might be a good idea to have `setup.py` be as declarative as possible, following PEP-517/518.

**Comment by pukkandan** [comment]
Related: https://github.com/yt-dlp/yt-dlp/pull/109 https://github.com/yt-dlp/yt-dlp/issues/108

**Comment by hseg** [comment]
If we go with the "`setup.py` is for the python artifacts, `Makefile` is for packaging" route, it seems the only part of `setup.py` that needs a non-declarative build is the lazy extractors and plugin features. Possibly there is an alternative way of building them?

**Comment by pukkandan** [comment]
>  and plugin features

please explain what u mean

> it seems the only part of setup.py that needs a non-declarative build is the lazy extractors

Lazy extractors are buildable by either the makefile or setup.py. I don't see the harm in keeping it so. That being said, lazy extraction is buggy atm and is not officially supported. I believe the same is true for youtube-dl

**Comment by hseg** [comment]
I mean that aside from the dynamic generation of `data_files`, the only non-declarative parts of `setup.py` are the `build_lazy_extractors` class and the call to `find_packages`
