### ISSUE TITLE
Is there any way to avoid specific googlevideo cache servers?

### ISSUE THREAD

**Issue by Yoksven** [yt-dlp/yt-dlp#11007]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Currently Russia has a lot of problems with Youtube. I'm well aware that it's not yt-dlp's fault and it's an issue outside of anyone's control. People have found working workarounds in the past, however, recently there was a new wave of blocking attempts and it has lead to access to random googlevideo cache servers to be blocked. It's different for different people, but for me it's rr1---sn-4axm-n8vs.googlevideo.com and rr2---sn-4axm-n8vs.googlevideo.com, and if yt-dlp accesses these specific servers when trying to download a video - it gets completely timed out. Also, in my experience if yt-dlp started trying to download from a specific server, then it will continue to try access it if I restart over and over. After some hours it might try another one, but it's very random. 

The important part is - in browser, people have found that there are some uBlock filter settings that allow to avoid getting connections to specific servers:

! Blocking all connections to googlevideo
||googlevideo.com/videoplayback^
! Allowing connections with the right ip to avoid 403 error
@@||googlevideo.com/videoplayback*ip=your_ip"*^

! Blocking failing servers one by one
||rr1---sn-4axm-n8vs.googlevideo.com^$important
||rr2---sn-4axm-n8vs.googlevideo.com^$important

And in browser it somehow forces Youtube to never even touch these faulty servers. In network reports they aren't reported to be blocked by uBlock, they are just not even there. Consistently. I don't know how that works, but it does.

But I haven't found any sort of system wide workaround that would work for yt-dlp. I've tried blocking them with the hosts file, but, as you can see in the output, that just gave me WinError 10061 (machine rejecting the connection). Maybe firewall, but I've never messed with it (to my shame), so I wouldn't know what to do (maybe someone can help me with that?). VPN or proxy theoretically could work, if the only blocked cache servers are those inside of Russia. I don't have a system wide VPN, so I can't really check. I'm feeling more and more pressure to get one, but for now I'm looking for other solutions, if there are any.

So, is there any way to either avoid specific cache servers or to force specific servers to be used or to use random server every time, instead of trying the same one over and over? If anyone has any ideas - all are welcomed.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[GUI] executing command line: "C:\Program Files\ytdlp-interface\yt-dlp.exe" -S "res:720,vext:webm,aext:opus,vcodec:vp9,acodec:aac" --embed-chapters --no-mtime -r 1.0M --verbose  -P "C:\Users\User\Desktop\vods n stuff" -o "%(title)s [%(upload_date>%Y.%m.%d)s].%(ext)s" "https://www.youtube.com/watch?v=ga9Qk38FaHM"

[debug] User config "C:\Users\User\AppData\Roaming\yt-dlp\config": ['-o', 'c:/users/user/desktop/vods n stuff/%(title)s.%(ext)s', '-r', '999K', '-f', '136+140']
[debug] Encodings: locale cp1251, fs utf-8, pref UTF-8, out cp1251 (No VT), error cp1251 (No VT), screen cp1251 (No VT)
[debug] yt-dlp version nightly@2024.09.13.232912 from yt-dlp/yt-dlp-nightly-builds [36f9e602a] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-7-6.1.7601-SP1 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-115007-g1f8e5b6d95-20240425 (setts), ffprobe N-115007-g1f8e5b6d95-20240425
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.08.30, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.3, websockets-13.0.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1834 extractors
[youtube] Extracting URL: https://www.youtube.com/watch?v=ga9Qk38FaHM
[youtube] ga9Qk38FaHM: Downloading webpage
[youtube] ga9Qk38FaHM: Downloading ios player API JSON
[youtube] ga9Qk38FaHM: Downloading web creator player API JSON
[debug] Loading youtube-nsig.e38bb6de from cache
[debug] [youtube] Decrypted nsig u20CRPLcZYpkLCvU => c2peUazasoY-5g
[youtube] ga9Qk38FaHM: Downloading m3u8 information
[debug] Sort order given by user: res:720, vext:webm, aext:opus, vcodec:vp9, acodec:aac
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, res:720(720.0), vext:webm(4), aext:opus(4), vcodec:vp9(9), acodec:aac(10), quality, fps, hdr:12(7), source, channels, lang, proto, size, br, asr, hasaud, id
[info] ga9Qk38FaHM: Downloading 1 format(s): 136+140
[debug] Invoking http downloader on "https://rr2---sn-4axm-n8vs.googlevideo.com/videoplayback?expire=1726377493&ei=tRnmZqCMLNnFv_IPspHTiQQ&ip=109.237.239.77&id=o-APibKHTtVctgWbxuuciQ6dBE-pwQrzjviIYwCk4m2wtZ&itag=136&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=81&mm=31%2C29&mn=sn-4axm-n8vs%2Csn-n8v7znsy&ms=au%2Crdu&mv=m&mvi=2&pl=20&vprv=1&svpuc=1&mime=video%2Fmp4&rqh=1&gir=yes&clen=49436174&dur=1044.000&lmt=1726117670999610&mt=1726355582&fvip=11&keepalive=yes&c=IOS&txp=5532434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cvprv%2Csvpuc%2Cmime%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRAIgRToLvxaXNGUD7KoajGcXTX7SQGUfLDbruPBCWKRK1CECIBOlTteGyIwFe6PZA936zKAykPvkh6HDzQuPHibBYERG&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl&lsig=ABPmVW0wRQIhAMJQTi3EqnX2Dqf2x1nCZnpU-JcP8jFlOcaSJ65fcgBfAiBtf4qVy00bRBXW4ruHFFh_h-K97Kxw_65k3DpuQuosgQ%3D%3D"
[download] Got error: <urllib3.connection.HTTPSConnection object at 0x00000000052437F0>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение. Retrying (1/10)...
[download] Got error: <urllib3.connection.HTTPSConnection object at 0x00000000052C5E80>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение. Retrying (2/10)...
[download] Got error: <urllib3.connection.HTTPSConnection object at 0x00000000052D68E0>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение. Retrying (3/10)...
[download] Got error: <urllib3.connection.HTTPSConnection object at 0x00000000052C5C40>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение. Retrying (4/10)...
[download] Got error: <urllib3.connection.HTTPSConnection object at 0x00000000050366A0>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение. Retrying (5/10)...
[download] Got error: <urllib3.connection.HTTPSConnection object at 0x00000000052D60A0>: Failed to establish a new connection: [WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение. Retrying (6/10)...

[GUI] yt-dlp.exe process was ended gracefully via Ctrl+C signal
```

**Comment by october262** [comment]
have you tried using a VPN with yt-dlp ??
connect to a server in the united states ??

**Comment by Yoksven** [comment]
If you read carefully, I've mentioned that I don't have a system wide VPN. I've been coasting on GoodbyeDPI and VPNs provided by Russia freedom movements, but those can't be used outside of a browser and often can't be configured at all. To quote myself from earlier - I'm feeling more and more pressure to get a VPN, but for now I'm looking into other ways to solve this, since this is the only thing I would need a VPN for and the problem only occurs sometimes, randomly, due to the random nature of the chosen servers.

**Comment by october262** [comment]
> If you read carefully, I've mentioned that I don't have a system wide VPN. I've been coasting on GoodbyeDPI and VPNs provided by Russia freedom movements, but those can't be used outside of a browser and some can't be configured at all. To quote myself from earlier - I'm feeling more and more pressure to get a VPN, but for now I'm looking into other ways to solve this, since this is the only thing I would need a VPN for and the problem only occurs sometimes, randomly, due to the random nature of the chosen servers.

a Socks5 proxy  ?? - https://meduza.io/en/feature/2024/08/08/youtube-has-suddenly-stopped-working-in-russia-meduza-s-readers-describe-how-they-re-handling-the-loss-of-the-world-s-most-popular-video-streaming-service

**Comment by Yoksven** [comment]
I don't understand your question.

**Comment by october262** [comment]
> I don't understand your question.

two users in that link i posted use a Socks5 proxy for youtube  
and the other uses a proy service and Tor on their desktop.

**Comment by Yoksven** [comment]
Yes. And? Tor is not a solution for yt-dlp, and free proxies don't work well on my ISP. God knows why.

**Comment by bashonly** [comment]
are these workarounds still of any use:
- https://github.com/yt-dlp/yt-dlp/issues/10443#issuecomment-2248940967

**Comment by Yoksven** [comment]
GoodbyeDPI still works, it just needs different parameters after recent blocking attempts. But the google cache server issue exists even when GDPI works and does it's job. Nobody really knows why random cache servers are inaccessible. One theory is that since Google has left Russia, cache servers get not maintenance, so they are just straight up failing in a regular way, and it has nothing to do with blocking attempts. But nobody knows for sure.

I might be out of the woods, at least for now. It seems like cache servers are rotating and these two bad ones have rotated out. They might come back, but for now things are okay.

**Comment by bashonly** [comment]
To the answer the original question, no
