### ISSUE TITLE
Cannot download Instagram video

### ISSUE THREAD

**Issue by shiisa** [yt-dlp/yt-dlp#11002]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

It happened since 2024.9.13. 
Using the latest version yt-dlp.
Error message is as followed:

WARNING: [Instagram] unable to extract shared data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [Instagram] Main webpage is locked behind the login page. Retrying with embed webpage (some metadata might be missing).
[Instagram] CsTwy4FBA5n: Downloading embed webpage
^C^CWARNING: [Instagram] unable to extract additional data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['--cookies-from-browser', 'chrome', 'https://www.instagram.com/reel/CsTwy4FBA5n', '--force-overwrites', '-o', 'output/1070/video.mp4', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481] (pip)
[debug] Python 3.11.4 (CPython arm64 64bit) - macOS-14.2.1-arm64-arm-64bit (OpenSSL 3.0.12 24 Oct 2023)
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.19.0, brotli-None, certifi-2023.07.22, mutagen-1.47.0, sqlite3-2.6.0, websockets-11.0.3
[Cookies] Extracting cookies from chrome
[debug] Extracting cookies from: "/Users/freedom/Library/Application Support/Google/Chrome/Default/Cookies"
[debug] using find-generic-password to obtain password from OSX keychain
[Cookies] Extracted 1182 cookies from chrome
[debug] cookie version breakdown: {'v10': 1202, 'other': 0, 'unencrypted': 16}
[debug] Proxy map: {'http': 'http://127.0.0.1:7890', 'https': 'http://127.0.0.1:7890'}
[debug] Loaded 1855 extractors
[Instagram] Extracting URL: https://www.instagram.com/reel/CsTwy4FBA5n
[Instagram] CsTwy4FBA5n: Downloading video info
WARNING: [Instagram] Video info extraction failed: HTTP Error 401: Unauthorized
[Instagram] CsTwy4FBA5n: Setting up session
[Instagram] CsTwy4FBA5n: Downloading JSON metadata
WARNING: [Instagram] CsTwy4FBA5n: General metadata extraction failed (some metadata might be missing).
[Instagram] CsTwy4FBA5n: Downloading webpage
WARNING: [Instagram] unable to extract shared data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [Instagram] Main webpage is locked behind the login page. Retrying with embed webpage (some metadata might be missing).
[Instagram] CsTwy4FBA5n: Downloading embed webpage
WARNING: [Instagram] unable to extract additional data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
ERROR: [Instagram] CsTwy4FBA5n: Requested content is not available, rate-limit reached or login required. Use --cookies, --cookies-from-browser, --username and --password, --netrc-cmd, or --netrc (instagram) to provide account credentials
  File "/Users/freedom/miniconda3/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 710, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/freedom/miniconda3/lib/python3.11/site-packages/yt_dlp/extractor/instagram.py", line 456, in _real_extract
    self.raise_login_required('Requested content is not available, rate-limit reached or login required')
  File "/Users/freedom/miniconda3/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 1170, in raise_login_required
    raise ExtractorError(msg, expected=True)
```

**Comment by bashonly** [comment]
don't pass `--cookies-from-browser`; it looks like your account has been flagged for suspicious activity

**Comment by shiisa** [comment]
Correct, I use --cookies instead, it is ok now. Thank you for supporting:-)

**Comment by shiisa** [comment]
Correct, I use --cookies instead, it is ok now. Thank you for supporting:-)

**Comment by modesty88** [comment]
ERROR: [Ixigua] 740663771958712786: Failed to get SSR_HYDRATED_DATA;
