### ISSUE TITLE
Parse format list to json file or at least json into json string.

### ISSUE THREAD

**Issue by kal-asther** [yt-dlp/yt-dlp#11015]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I would like to gather just the id's and formats, and specifically if they're audio_only and video_only.

I'm making a gui for it through a website for personal use, since my old-timer relatives need something with a relative(pun intended) ease-of-use. This way I can just parse the Json into javascript objects and display them there via their formats, just one of mp4, webm(av1 if possible), mp3, and aac for audio. And one of each video resolution for both webm and mp4.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by seproDev** [comment]
You can either get a python dict using the api or use `-j` to get a json string of the extracted info.

**Comment by kal-asther** [comment]
> You can either get a python dict using the api or use `-j` to get a json string of the extracted info.

Sorry, forgot to update this. I read a thread about (not exactly) the same thing, and it led me to a command that would output a custom json string.

Which led me to use the output command -O to acquire the results in json and then picked the fields that are most important to me.

Which then led me to this command
yt-dlp -O "%(.{id,title,formats})#j" <url>

Hope it helps anybody looking for the same thing.
