### ISSUE TITLE
Is there any way to download multiple URLs concurrently

### ISSUE THREAD

**Issue by johnathanchiu** [yt-dlp/yt-dlp#11022]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Is there a flag or operation to do concurrent downloads for files with yt-dlp? For instance, can I run concurrent downloads if I have a function like this and can pass in a list of urls? There seems to be a bit of latency when downloading these pieces.

```
def get_m3u8(url, filename, protocol):
    command = [
        "yt-dlp",
        "--verbose",
        "--format",
        protocol,
        "--extractor-arg",
        "youtube:player_client=default,mediaconnect",
        "--skip-download",
        "--exec",
        f'video:curl -Lo "{filename}" %(url)q',
        url,
    ]
    _ = subprocess.run(command, text=True, capture_output=True)

    with open(filename, "r") as f:
        m3u8_content = "".join(f.readlines())

    return m3u8_content
```

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
No

**Comment by barsnick** [comment]
> There seems to be a bit of latency when downloading these pieces.

Which pieces do you mean? The m3u8 files?

Some friendly remarks:
- Since you're using python, you may as well use yt-dlp's python API.
- In your script, you could launch concurrent async threads.
- With `with open()`, you can just use one call of `f.read()` instead of looping over `f.readline()`
- Even better, if it does not NEED to be curl, you can use Python's [`urllib.request.urlopen`](http://docs.python.org/dev/library/urllib.request.html#urllib.request.urlopen) to download the file content into a variable.
- I'm not sure what you want to do with the m3u8's content afterwards though...

**Comment by johnathanchiu** [comment]
Can you explain the last point of the `urllib.request.urlopen`? What do you mean by this?

**Comment by johnathanchiu** [comment]
Yes, thanks for the reminder. I might end up using this in other languages as well so writing it to call the executable is also good in this case. 

I'll take a stab at using the direct python version too though. Do you think you can put me in the right direction with a python script example of what I'm trying to accomplish above?

**Comment by bashonly** [comment]
there is a feature request for this: #1918

**Comment by johnathanchiu** [comment]
This is the python function I am using now:

```
from yt_dlp import YoutubeDL

def get_m3u8(url, protocol):
    ydl_opts = {
        'format': protocol,
        'skip_download': True,
        'force_generic_extractor': True,
        'extractor_args': {
            'youtube': {
                'player_client': ['default', 'mediaconnect']
            }
        },
        'verbose': False,
        'quiet': True,
    }

    with YoutubeDL(ydl_opts) as ydl:
        result = ydl.extract_info(url, download=False)
    
    return result.get('url', '')
```

Are there any ways to speed this up? Ideally some flags that would not grab all information?

**Comment by bashonly** [comment]
why `force_generic_extractor`? I don't think it does what you think it does

> Are there any ways to speed this up? Ideally some flags that would not grab all information?

you could remove the `extractor_args`, or use ONLY `ios` or `web_creator` as the `player_client`, but this will result in fewer formats available

**Comment by johnathanchiu** [comment]
I set to this and this seems to be the fastest:

```
def get_m3u8(url, protocol):
    ydl_opts = {
        'format': protocol,
        'skip_download': True,
        'extractor_args': {
            'youtube': {
                'player_client': ['mediaconnect']
            }
        },
        'verbose': False,
        'quiet': True,
    }

    with YoutubeDL(ydl_opts) as ydl:
        result = ydl.extract_info(url, download=False)
    
    return result.get('url', '')
```

Does this sound about right?

**Comment by bashonly** [comment]
looks good
