### ISSUE TITLE
Files Downloaded from Youtube do not play!!!

### ISSUE THREAD

**Issue by jd1008** [yt-dlp/yt-dlp#11029]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

USA

### Provide a description that is worded well enough to be understood

My version of yt-dlp is current:
yt-dlp -U
Latest version: stable@2024.08.06 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.08.06 from yt-dlp/yt-dlp)

----------------------------------

Downloaded a video, which mplayer cannot play

$ /bin/yt-dlp -vU  -f 616 --output Agam-NAMASKARATHA_MANTRA-NXxLJF52Rhc.mp4  https://www.youtube.com/watch?v=NXxLJF52Rhc
[debug] Command-line config: ['-vU', '-f', '616', '--output', 'Agam-NAMASKARATHA_MANTRA-NXxLJF52Rhc.mp4', 'https://www.youtube.com/watch?v=NXxLJF52Rhc']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.08.06 from yt-dlp/yt-dlp [4d9231208] (zip)
[debug] Python 3.10.8 (CPython x86_64 64bit) - Linux-6.0.12-100.fc35.x86_64-x86_64-with-glibc2.34 (OpenSSL 1.1.1q  FIPS 5 Jul 2022, glibc 2.34)
[debug] exe versions: ffmpeg 4.4.3 (setts), ffprobe N-51556-ge278500
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2020.12.05, mutagen-1.45.1, requests-2.27.1, sqlite3-3.36.0, urllib3-1.26.12, websockets-10.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Loaded 1830 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.08.06 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.08.06 from yt-dlp/yt-dlp)
[youtube] Extracting URL: https://www.youtube.com/watch?v=NXxLJF52Rhc
[youtube] NXxLJF52Rhc: Downloading webpage
[youtube] NXxLJF52Rhc: Downloading ios player API JSON
[youtube] NXxLJF52Rhc: Downloading web creator player API JSON
[debug] Loading youtube-nsig.7fe34188 from cache
[debug] [youtube] Decrypted nsig mVD0MEhsXGWQDaww => qySK-LUObGGU2g
[debug] Loading youtube-nsig.7fe34188 from cache
[debug] [youtube] Decrypted nsig sL5DK_Piqlf5yG1D => xDYd9cK8IaSmxQ
[youtube] NXxLJF52Rhc: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[info] NXxLJF52Rhc: Downloading 1 format(s): 616
[debug] Invoking hlsnative downloader on "https://manifest.googlevideo.com/api/manifest/hls_playlist/expire/1726629101/ei/jfDpZoWOIrSK2_gP6oG-2Ag/ip/2607:fb91:1136:8a32:fc91:fbde:0:13f/id/357c4b245e764617/itag/616/source/youtube/requiressl/yes/ratebypass/yes/pfa/1/wft/1/sgovp/clen%3D85807246%3Bdur%3D359.080%3Bgir%3Dyes%3Bitag%3D356%3Blmt%3D1723839256532314/rqh/1/hls_chunk_host/rr2---sn-qxo7rn7k.googlevideo.com/xpc/EgVo2aDSNQ%3D%3D/mh/JE/mm/31,26/mn/sn-qxo7rn7k,sn-p5qs7nsk/ms/au,onr/mv/m/mvi/2/pl/40/initcwndbps/2323750/vprv/1/playlist_type/DVR/dover/13/txp/4532434/mt/1726607106/fvip/2/short_key/1/keepalive/yes/sparams/expire,ei,ip,id,itag,source,requiressl,ratebypass,pfa,wft,sgovp,rqh,xpc,vprv,playlist_type/sig/AJfQdSswRgIhAIZnkxCUjeHrQDwfigTrVolZySCNiO-GHuQYHmX3-UstAiEAnxUOftnRExnZwCzDhElpNMqitk0kLWpdos34_GNkzcU%3D/lsparams/hls_chunk_host,mh,mm,mn,ms,mv,mvi,pl,initcwndbps/lsig/ABPmVW0wRgIhANF5zgN3MFTIA4-Tam_Y9BXByLPgnFXVU2sRs9UYC5w9AiEAy0VG-cUDInZRMLa374dhyY30hW1dLmrg7tbsCteKk4Q%3D/playlist/index.m3u8"
[download] Agam-NAMASKARATHA_MANTRA-NXxLJF52Rhc.mp4 has already been downloaded
[download] 100% of   81.84MiB
{22437-jd@localhost}$ rmrf Agam-NAMASKARATHA_MANTRA-NXxLJF52Rhc.mp4                                                                              
{22438-jd@localhost}$ /bin/yt-dlp -vU  -f 616 --output Agam-NAMASKARATHA_MANTRA-NXxLJF52Rhc.mp4  https://www.youtube.com/watch?v=NXxLJF52Rhc
[debug] Command-line config: ['-vU', '-f', '616', '--output', 'Agam-NAMASKARATHA_MANTRA-NXxLJF52Rhc.mp4', 'https://www.youtube.com/watch?v=NXxLJF52Rhc']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.08.06 from yt-dlp/yt-dlp [4d9231208] (zip)
[debug] Python 3.10.8 (CPython x86_64 64bit) - Linux-6.0.12-100.fc35.x86_64-x86_64-with-glibc2.34 (OpenSSL 1.1.1q  FIPS 5 Jul 2022, glibc 2.34)
[debug] exe versions: ffmpeg 4.4.3 (setts), ffprobe N-51556-ge278500
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2020.12.05, mutagen-1.45.1, requests-2.27.1, sqlite3-3.36.0, urllib3-1.26.12, websockets-10.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Loaded 1830 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.08.06 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.08.06 from yt-dlp/yt-dlp)
[youtube] Extracting URL: https://www.youtube.com/watch?v=NXxLJF52Rhc
[youtube] NXxLJF52Rhc: Downloading webpage
[youtube] NXxLJF52Rhc: Downloading ios player API JSON
[youtube] NXxLJF52Rhc: Downloading web creator player API JSON
[debug] Loading youtube-nsig.7fe34188 from cache
[debug] [youtube] Decrypted nsig 3NOHUZRECS0p41Rs => mQzES1M7wx73gw
[youtube] NXxLJF52Rhc: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[info] NXxLJF52Rhc: Downloading 1 format(s): 616
[debug] Invoking hlsnative downloader on "https://manifest.googlevideo.com/api/manifest/hls_playlist/expire/1726629138/ei/svDpZt-wEL7Plu8P37makQs/ip/2607:fb91:1136:8a32:fc91:fbde:0:13f/id/357c4b245e764617/itag/616/source/youtube/requiressl/yes/ratebypass/yes/pfa/1/wft/1/sgovp/clen%3D85807246%3Bdur%3D359.080%3Bgir%3Dyes%3Bitag%3D356%3Blmt%3D1723839256532314/rqh/1/hls_chunk_host/rr2---sn-qxoedn7k.googlevideo.com/xpc/EgVo2aDSNQ%3D%3D/mh/JE/mm/31,26/mn/sn-qxoedn7k,sn-p5qs7nsk/ms/au,onr/mv/m/mvi/2/pl/40/initcwndbps/2323750/vprv/1/playlist_type/DVR/dover/13/txp/4532434/mt/1726607106/fvip/2/short_key/1/keepalive/yes/sparams/expire,ei,ip,id,itag,source,requiressl,ratebypass,pfa,wft,sgovp,rqh,xpc,vprv,playlist_type/sig/AJfQdSswRQIhAPAIP408eGH4h6D6OWDLbkcyEfH_qDPdxBGPRNcvYqIRAiASrnyNTnulYbys-SpCniDSqEsKPhgL6xoMVJMcISlB0w%3D%3D/lsparams/hls_chunk_host,mh,mm,mn,ms,mv,mvi,pl,initcwndbps/lsig/ABPmVW0wRAIgeNjhIOQHs7FKJamHPTHHeTtFrnwppYU0WGxQDSCbi4UCIHCexYo2PbXsjhODc3mkWhXyojoXW20rw7WeXRI9TYS4/playlist/index.m3u8"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 70
[download] Destination: Agam-NAMASKARATHA_MANTRA-NXxLJF52Rhc.mp4
[download] 100% of   81.84MiB in 00:00:50 at 1.61MiB/s
[debug] ffprobe command line: ffprobe -hide_banner -show_format -show_streams -print_format json file:Agam-NAMASKARATHA_MANTRA-NXxLJF52Rhc.mp4
ERROR: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1626, in wrapper
    return func(self, *args, **kwargs)
  File "/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1782, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1841, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3015, in process_video_result
    self.process_info(new_info)
  File "/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 179, in wrapper
    return func(self, *args, **kwargs)
  File "/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3561, in process_info
    replace_info_dict(self.post_process(dl_filename, info_dict, files_to_move))
  File "/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3743, in post_process
    info = self.run_all_pps('post_process', info, additional_pps=info.get('__postprocessors'))
  File "/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3725, in run_all_pps
    info = self.run_pp(pp, info)
  File "/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3703, in run_pp
    files_to_delete, infodict = pp.run(infodict)
  File "/bin/yt-dlp/yt_dlp/postprocessor/common.py", line 23, in run
    ret = func(self, info, *args, **kwargs)
  File "/bin/yt-dlp/yt_dlp/postprocessor/common.py", line 128, in wrapper
    return func(self, info)
  File "/bin/yt-dlp/yt_dlp/postprocessor/ffmpeg.py", line 902, in run
    if all(self._needs_fixup(info)):
  File "/bin/yt-dlp/yt_dlp/postprocessor/ffmpeg.py", line 893, in _needs_fixup
    metadata = self.get_metadata_object(info['filepath'])
  File "/bin/yt-dlp/yt_dlp/postprocessor/ffmpeg.py", line 297, in get_metadata_object
    return json.loads(stdout)
  File "/usr/lib64/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

$ mplayer Agam-NAMASKARATHA_MANTRA-NXxLJF52Rhc.mp4
MPlayer 1.5-11 (C) 2000-2022 MPlayer Team
do_connect: could not connect to socket
connect: No such file or directory
Failed to open LIRC support. You will not be able to use your remote control.

Playing Agam-NAMASKARATHA_MANTRA-NXxLJF52Rhc.mp4.
libavformat version 58.76.100 (external)
libavformat file format detected.
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7f22f7c48300]Protocol name not provided, cannot determine if input is local or a network protocol, buffers and access patterns cannot be configured optimally without knowing the protocol
[lavf] stream 0: video (vp9), -vid 0
VIDEO:  [vp09]  1920x816  24bpp  25.000 fps  1910.2 kbps (233.2 kbyte/s)
Failed to open VDPAU backend libvdpau_crocus.so: cannot open shared object file: No such file or directory
[vdpau] Error when calling vdp_device_create_x11: 1
[VO_XV] Could not grab port 153.
==========================================================================
Cannot find codec matching selected -vo and video format 0x39307076.
==========================================================================
No stream found.

Exiting... (End of file)

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.08.06 from yt-dlp/yt-dlp [4d9231208] (zip)
[debug] Python 3.10.8 (CPython x86_64 64bit) - Linux-6.0.12-100.fc35.x86_64-x86_64-with-glibc2.34 (OpenSSL 1.1.1q  FIPS 5 Jul 2022, glibc 2.34)
[debug] exe versions: ffmpeg 4.4.3 (setts), ffprobe N-51556-ge278500
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2020.12.05, mutagen-1.45.1, requests-2.27.1, sqlite3-3.36.0, urllib3-1.26.12, websockets-10.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Loaded 1830 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
```

**Comment by bashonly** [comment]
Have you tried other media players? mpv, vlc? your ffmpeg/ffmpeg versions look to be quite old, have you tried upgrading ffmpeg? upgrading mplayer?

I don't quite understand what's going on in the multiple logs you posted. None of them are the original download
