### ISSUE TITLE
pls. add support in --cookies-from-browser for Waterfox browser

### ISSUE THREAD

**Issue by Yevgeny1** [yt-dlp/yt-dlp#11021]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

pls. add support for option --cookies-from-browser for Waterfox browser,  it's clone of Firefox.
Currently yt-dlp support Firefox + chrome (and chrome clones), it works, but not support Waterfox.
Waterfox  simply user another path to user profile  (same path , but *Waterfox*  instead of *\Mozilla\Firefox\*), same format of profile.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by dirkf** [comment]
Probably the same applies for PaleMoon, and SeaMonkey too. Isn't this what the `PROFILE` element of the value passed as `--cookies-from-browser ...` is for?

**Comment by Yevgeny1** [comment]
option "--cookies-from-browser"   is for using auth cookies from browser  in download sessions from sites, require auth.

**Comment by dirkf** [comment]
Please review #2903 and also, say, the resolution of #2983.

**Comment by bashonly** [comment]
can you try using `--cookies-from-browser` like this:
```
yt-dlp -v --cookies-from-browser "firefox:/path/to/waterfox/profile" "URL"
```
replacing the placeholder path with your actual waterfox profile directory path

please provide a verbose log if it doesn't work

**Comment by Yevgeny1** [comment]
"can you try using --cookies-from-browser like this:
yt-dlp -v --cookies-from-browser "firefox:/path/to/waterfox/profile" "URL"
replacing the placeholder path with your actual waterfox profile directory path"

 it works,
thanks.
