### ISSUE TITLE
Instagram Video Download issue

### ISSUE THREAD

**Issue by aravindnadumane** [yt-dlp/yt-dlp#11033]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

$ yt-dlp https://www.instagram.com/p/C-gPpGcSW4g/
[Instagram] Extracting URL: https://www.instagram.com/p/C-gPpGcSW4g/
[Instagram] C-gPpGcSW4g: Setting up session
WARNING: [Instagram] C-gPpGcSW4g: No csrf token set by Instagram API
[Instagram] C-gPpGcSW4g: Downloading JSON metadata

WARNING: [Instagram] unable to extract username; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
ERROR: [Instagram] C-gPpGcSW4g: Unable to extract video url; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
$ yt-dlp -vU https://www.instagram.com/p/C-gPpGcSW4g/
[debug] Command-line config: ['-vU', 'https://www.instagram.com/p/C-gPpGcSW4g/']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out cp1252 (No VT), error cp1252 (No VT), screen cp1252 (No VT)
[debug] yt-dlp version stable@2024.08.06 from yt-dlp/yt-dlp [4d9231208] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22631-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 2024-02-04-git-7375a6ca7b-full_build-www.gyan.dev (setts), ffprobe 2024-02-04-git-7375a6ca7b-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.07.04, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1830 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.08.06 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.08.06 from yt-dlp/yt-dlp)
[Instagram] Extracting URL: https://www.instagram.com/p/C-gPpGcSW4g/
[Instagram] C-gPpGcSW4g: Setting up session
WARNING: [Instagram] C-gPpGcSW4g: No csrf token set by Instagram API
[Instagram] C-gPpGcSW4g: Downloading JSON metadata
WARNING: [Instagram] unable to extract username; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
ERROR: [Instagram] C-gPpGcSW4g: Unable to extract video url; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 740, in extract
  File "yt_dlp\extractor\instagram.py", line 490, in _real_extract
  File "yt_dlp\extractor\common.py", line 1479, in _og_search_video_url
  File "yt_dlp\extractor\common.py", line 1369, in _html_search_regex
  File "yt_dlp\extractor\common.py", line 1333, in _search_regex
```

**Comment by bashonly** [comment]
Are you using a VPN, proxy or data center IP? Are you able to view the instagram post in your browser on the same machine, from the same IP address, without being logged in (private browsing)?

**Comment by bashonly** [comment]
I can't get the video to load in a browser without logging in

Anyways this is a dupe of #5967
