### ISSUE TITLE
[TikTok] 31KB non-video files are being downloaded

### ISSUE THREAD

**Issue by KellvinSB** [yt-dlp/yt-dlp#11034]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Brazil

### Provide a description that is worded well enough to be understood

Yesterday, everything was working fine, but today no TikTok video can be downloaded (YouTube downloads work normally).  
I use downloads via CLI and Python, but neither of them work anymore.

### Command + ffmpeg output:
```bash
yt-dlp -vU --format "bestvideo+bestaudio/best" --output "%(uploader)s - %(title)s.%(ext)s" --download-archive downloaded_videos.txt https://www.tiktok.com/@feelsfinder/video/7402367418137349406

ffmeg:
[mov,mp4,m4a,3gp,3g2,mj2 @ 000002e7041c2cc0] moov atom not found
[in#0 @ 000002e7041c28c0] Error opening input: Invalid data found when processing input
Error opening input file C:\clr\Nova pasta\tik\feelsfinder - #moon #aestheticvideos #background .mp4.
Error opening input files: Invalid data found when processing input

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--format', 'bestvideo+bestaudio/best', '--output', '%(uploader)s - %(title)s.%(ext)s', '--download-archive', 'downloaded_videos.txt', 'https://www.tiktok.com/@feelsfinder/video/7402367418137349406']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.08.06 from yt-dlp/yt-dlp [4d9231208] (pip)
[debug] Python 3.10.2 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1m  14 Dec 2021)
[debug] exe versions: ffmpeg 2024-09-05-git-3d0d0f68d5-full_build-www.gyan.dev (setts), ffprobe 2024-09-05-git-3d0d0f68d5-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.08.30, mutagen-1.47.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.2, websockets-13.0.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1830 extractors
[debug] Loading archive file 'downloaded_videos.txt'
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.08.06 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.08.06 from yt-dlp/yt-dlp)
[TikTok] Extracting URL: https://www.tiktok.com/@feelsfinder/video/7402367418137349406
[TikTok] 7402367418137349406: Downloading webpage
[debug] [TikTok] Found universal data for rehydration
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[info] 7402367418137349406: Downloading 1 format(s): bytevc1_1080p_231851-2
[debug] Invoking http downloader on "https://www.tiktok.com/aweme/v1/play/?faid=1988&file_id=15846d2d5ffe48369fee01287fb3c5a8&is_play_url=1&item_id=7402367418137349406&line=0&ply_type=2&signaturev3=dmlkZW9faWQ7ZmlsZV9pZDtpdGVtX2lkLjMyNWE5Mzc2N2E1NmQ2YTBmZmZjZDVmZGRhMzk3ZjNh&tk=tt_chain_token&video_id=v15044gf0000cqt7qdnog65rtbindi30"
[debug] File locking is not supported. Proceeding without locking
[download] Destination: feelsfinder - #moon #aestheticvideos #background .mp4
[download] 100% of   30.39KiB in 00:00:00 at 84.19KiB/s
[debug] Adding to archive: tiktok 7402367418137349406
```

**Comment by bashonly** [comment]
I can't reproduce the issue. The actual video downloads fine for me.

Are you able to watch the video in browser without being logged in?

Can you try opening your download in a text editor? Is it an html file by any chance?

**Comment by bashonly** [comment]
Looks like a login page perhaps

I ask again:

> Are you able to watch the video in browser without being logged in?

**Comment by bashonly** [comment]
can someone who is affected by this issue add `--print "%(formats)#j"` to their command and share the output

**Comment by bashonly** [comment]
Seems like it's the formats with `https://www.tiktok.com/aweme/v1/play/` URLs that are the problem

I'm not getting any format URLs like that on my end. Possibly A/B testing or a regional thing

Also notable, and I *am* experiencing this, is that non-watermarked formats seem to be completely missing from the webpage-extracted formats

**Comment by bashonly** [comment]
possible workaround for now:
```
-f "b[url!^='https://www.tiktok.com/']"
```
or if using a unix-like shell, then swap the single/double quoting:
```
-f 'b[url!^="https://www.tiktok.com/"]'
```

**Comment by KellvinSB** [comment]
bashonly I thought the issue was with yt-dl, but it looks like it’s my IP. You said it works for you, so I tried downloading using a VPN and it worked. I have two internet connections and two PCs, and on both, the download stalls at 30MB. When I open the video in text format, it shows an HTML. The videos play normally on TikTok, even in incognito mode. Can you help me? (I’m from Brazil). Here’s a video I recorded: https://www.youtube.com/watch?v=8WkLWqxp6Vc

**Comment by bashonly** [comment]
@KellvinSB please try the `--format` argument above that I just posted as a workaround

**Comment by KellvinSB** [comment]
My God, thank you, the command below works.
`yt-dlp --ignore-errors --format "best[format_id$=-0]" --output "%(uploader)s - %(title)s.%(ext)s" --download-archive downloaded_videos.txt https://www.tiktok.com/@username`

Just to note, foreign connections worked, but Brazilian ones weren't downloading with the script below:
`yt-dlp --ignore-errors --format "bestvideo+bestaudio/best" --output "%(uploader)s - %(title)s.%(ext)s" --download-archive downloaded_videos.txt https://www.tiktok.com/@username`

**Comment by bashonly** [comment]
Note that the format ID suffix numbering is completely arbitrary. Currently, the `-2` suffix correlates to the broken formats and `-0` correlates to working formats, but this could change at any time. Filtering by `url` instead would be less prone to breakage

**Comment by KellvinSB** [comment]
Yeah, -2 doesn’t work, but -0 and -1 do. I tried switching to other formats before, but all the ones I picked were -2, haha.

**Comment by YakivGluck** [comment]
> possible workaround for now:
> 
> ```
> -f "b[url!^='https://www.tiktok.com/']"
> ```
> 
> or if using a unix-like shell, then swap the single/double quoting:
> 
> ```
> -f 'b[url!^="https://www.tiktok.com/"]'
> ```

ty, that actually helped

**Comment by BreadJS** [comment]
Now we wait for a fix so we can use it like normal. I'm using seal (on android) which uses ytd

**Comment by DTrombett** [comment]
> possible workaround for now:
> 
> ```
> -f "b[url!^='https://www.tiktok.com/']"
> ```
> 
> or if using a unix-like shell, then swap the single/double quoting:
> 
> ```
> -f 'b[url!^="https://www.tiktok.com/"]'
> ```

Mmh, can't we implement this filter automatically in the extractor or something else needs to be done?
