### ISSUE TITLE
Can conditions be added to output template?

### ISSUE THREAD

**Issue by netherlink117** [yt-dlp/yt-dlp#11031]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Can we add conditions (like `if` and `else`) to the output template so it can place files into a "live" path if video is/was live and "non live" if video isn't/wasn't? So i can use same config file for both live and non live videos while keep organized the videos.

I already tried with `%('live' id is_live or was_live else 'non live')s `and it didn't work (it puts `NA` to the output), later tried `%(is_live or was_live&live)s`  even tried `%({'live' if was_live or is_live else 'non live'})s`.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
assuming the extractor is not setting `is_live` to `False`, this should work:
```
%(is_live,was_live&live|non live)s
```

**Comment by netherlink117** [comment]
Hi @bashonly , Thanks for you comment, I tested your example, for me it puts "live" on the output even if video was not live, is this a bug or somethings with the extractor? also noticed it changes the "/" for a similar character.

```
[debug] Command-line config: ['-vU', '--simulate', '--no-warnings', '--ignore-errors', '--no-playlist', '--windows-filenames', '--add-metadata', '--live-from-start', '--wait-for-video', '1', '--user-agent', 'Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36', '--print', 'filename', '--output', '/home/user/Downloads/%(extractor)s/%(uploader)s%(is_live,was_live&/live|/nonlive)s/%(width)sx%(height)s/%(upload_date)s %(id)s.%(ext)s', 'https://www.youtube.com/watch?v=BaW_jenozKc']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.09.17.232940 from yt-dlp/yt-dlp-nightly-builds [4a9bc8c36] (pip)
[debug] Python 3.10.12 (CPython x86_64 64bit) - Linux-6.9.3-76060903-generic-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.11.0, brotli-1.0.9, certifi-2020.06.20, mutagen-1.45.1, pyxattr-0.7.2, requests-2.32.3, secretstorage-3.3.1, sqlite3-3.37.2, urllib3-2.2.2, websockets-13.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1835 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.09.17.232940 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.09.17.232940 from yt-dlp/yt-dlp-nightly-builds)
[youtube] Extracting URL: https://www.youtube.com/watch?v=BaW_jenozKc
[youtube] BaW_jenozKc: Downloading webpage
[youtube] BaW_jenozKc: Downloading ios player API JSON
[youtube] BaW_jenozKc: Downloading web creator player API JSON
[youtube] BaW_jenozKc: Downloading player a9d81eca
[debug] Saving youtube-nsig.a9d81eca to cache
[debug] [youtube] Decrypted nsig eOM_ITSj0myO2EO2Z => ejsMz1e_dBiBrA
[debug] Loading youtube-nsig.a9d81eca from cache
[debug] [youtube] Decrypted nsig aUMT3oqhzOOwRudf1 => Cuuzl_ItPx6jqA
[youtube] BaW_jenozKc: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] BaW_jenozKc: Downloading 1 format(s): 137+140
/home/user/Downloads/youtube/Philipp Hagemeister⧸live/1920x1080/20121002 BaW_jenozKc.mp4
```

**Comment by bashonly** [comment]
welp my original suggestion won't work because `is_live` and `was_live` are `False` instead of `None`, so merely checking the presence of the values will always succeed

> also noticed it changes the "/" for a similar character.

this is expected. metadata field values are sanitized. you won't be able to do what you want to do this way

I actually don't think this is possible without using an external script, and at that point it would be much simpler to just use the Python API

**Comment by netherlink117** [comment]
Do you know if there is a way to use `--config-location` with the API?

I'm starting to work on a python script with the API. already tried this:
```python
with yt_dlp.YoutubeDL({'config_locations':['/home/user/Downloads/yt-dlp.conf'], 'verbose': True}) as ydl:
  ydl.download('https://www.youtube.com/watch?v=BaW_jenozKc')
```
And it seems like is not a option for the API (as I can see on the output of the command, there isn't any template from the `yt-dlp.conf` file):
```
[debug] params: {'config_locations': ['/home/user/Downloads/yt-dlp.conf'], 'verbose': True, 'compat_opts': set(), 'http_headers': {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.15 Safari/537.36', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'Accept-Language': 'en-us,en;q=0.5', 'Sec-Fetch-Mode': 'navigate'}}
```
Also tried changing `config_locations` for `config_location` but I'm not sure.

**Comment by grqx** [comment]
config parsing should be done in `yt_dlp.utils._utils.Config.load_configs` before the youtubedl instance is initialised.
you can use `devscripts/cli_to_api.py`, though

**Comment by Grub4K** [comment]
You should try avoid importing from `yt_dlp.utils._utils` of possible. Use `yt_dlp.utils.Config` instead, and then manually pass it the config files. Merge the resulting dict however you like.

**Comment by bashonly** [comment]
Backing this conversation up a bit: the Python API doesn't make use of config files. The params you pass to `YoutubeDL` ***are*** your config. So, as grqx said, you could use `devscripts/cli_to_api.py` to manually convert your config file to a params dict; or, as Grub4K said, you could use `yt-dlp.utils.Config` for a more programmatic approach to doing the same thing

**Comment by Grub4K** [comment]
Also related: #8511

This will simplify how to construct output templates from within the API. When it ever finishes
