### ISSUE TITLE
Suggestion: Change when SLEEP is called to help avoid "you're a bot" with playlists

### ISSUE THREAD

**Issue by MrSmite** [yt-dlp/yt-dlp#11047]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

This isn't specifically for YouTube but I haven't used yt-dlp on another site to know if this is an issue elsewhere.

Currently when you use --download-interval and --max-download-interval, the sleep is first triggered after yt-dlp performs URL extraction. The problem is, the act of determining the format can cause the "sign in to confirm you're not a bot" error and if you're downloading a playlist, it will continue on to the next item instead of sleeping. This usually results in the remaining playlist generating bot protection errors.

Adding a SLEEP before yt-dlp starts the URL extraction might help salvage some of the playlist. Even if a download does randomly trigger bot protection, pausing between actual playlist items instead of after URL extraction might give enough time for the server to calm down.

Example:

**Current behavior:**

> [youtube] Extracting URL
> [youtube] Downloading webpage
> [youtube] Downloading ios player API JSON
> [youtube] Downloading m3u8 information
> [info] Downloading 1 format(s): 134+140
> [download] sleeping for 45 seconds...
> [download] destination c:\media\not-a-bot.f134.mp4
> [download] progress...
> [download] sleeping for 75 seconds...
> [download] destination c:\media\not-a-bot.f140.m4a
> [merger] merging formats ...
> [youtube] Extracting URL
> [youtube] Downloading webpage
> [youtube] Downloading ios player API JSON
> **[error] sign in to confirm you're not a bot**
> [youtube] Extracting URL
> [youtube] Downloading webpage
> [youtube] Downloading ios player API JSON
> **[error] sign in to confirm you're not a bot**

**Suggested behavior:**

> [youtube] Extracting URL
> [youtube] Downloading webpage
> [youtube] Downloading ios player API JSON
> [youtube] Downloading m3u8 information
> [info] Downloading 1 format(s): 134+140
> [download] sleeping for 45 seconds...
> [download] destination c:\media\not-a-bot.f134.mp4
> [download] progress...
> [download] sleeping for 75 seconds...
> [download] destination c:\media\not-a-bot.f140.m4a
> [merger] merging formats ...
> [youtube] Extracting URL
> [youtube] Downloading webpage
> [youtube] Downloading ios player API JSON
> **[error] sign in to confirm you're not a bot**
> 
> **INSERT_SLEEP_HERE before attempting to start the next item**
> 
> [youtube] Extracting URL
> [youtube] Downloading webpage
> [youtube] Downloading ios player API JSON
> [youtube] Downloading m3u8 information
> [info] Downloading 1 format(s): 134+140
> [download] sleeping for 45 seconds...
> [download] destination c:\media\not-a-bot-2.f134.mp4
> [download] progress...
> [download] sleeping for 75 seconds...
> [download] destination c:\media\not-a-bot-2.f140.m4a
> [merger] merging formats ...

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
`--sleep-requests` ?

**Comment by MrSmite** [comment]
Thank you. I interpreted "sleep between data extraction" to mean sleep between each chunk request in a DASH file.

**Comment by bashonly** [comment]
> Is it possible to modify this parameter so it also uses --max-sleep-interval?

No

> Being randomized might provide more obfuscation against the bot protection.

Perhaps, but there are so many other ways for them to analyze your traffic

**Comment by MrSmite** [comment]
> Perhaps, but there are so many other ways for them to analyze your traffic

Indeed. Even with the random sleep between audio/video streams, I still get "you're a bot" messages frequently.
