### ISSUE TITLE
The download speed for YouTube video links can be quite slow

### ISSUE THREAD

**Issue by kaixuangh** [yt-dlp/yt-dlp#11052]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

yt-dlp -g  "https://www.youtube.com/watch?v=KbahC-QCKU8"   get video download url :https://rr4---sn-ajogu5-55.googlevideo.com/videoplayback?expire=1726936076&ei=rJ_uZoH4EMyU1d8PmLKfwQs&ip=152.67.219.91&id=o-APZ7h6_rlhdF3HFEzzkLfv8CSzB-Bf7TGFRJ5rvFC1gq&itag=135&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=2t&mm=31%2C29&mn=sn-ajogu5-55%2Csn-ogueln66&ms=au%2Crdu&mv=m&mvi=4&pl=24&initcwndbps=351250&siu=1&vprv=1&svpuc=1&mime=video%2Fmp4&rqh=1&gir=yes&clen=190292913&dur=2448.581&lmt=1726434645326403&mt=1726914060&fvip=1&keepalive=yes&c=IOS&txp=4532434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Csiu%2Cvprv%2Csvpuc%2Cmime%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRQIhALnvIDf8YS2BqjtyLRtHLT0LxNPELavJmhIgtV9bZjQhAiAHEBJA-c2eajmCIxyUplHLGIgVNiobiO7JeiwcRB0qTg%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=ABPmVW0wRQIgVD5XnF62Q7v3C0QpKSqlYzvTiyCx42uJiEvXLH2WHEcCIQD5QR-6P1ZWqrlJ9DEh0RNuemQxZa2folt8tVY9dyi3Gg%3D%3D

then:
download with requests download slowly

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by kaixuangh** [comment]
30kb/s

**Comment by seproDev** [comment]
Is the download fast when downloading through yt-dlp? Are you chunking your downloads to 10 MB?

**Comment by kaixuangh** [comment]
> Is the download fast when downloading through yt-dlp? Are you chunking your downloads to 10 MB?

es, the download speed is fast when using yt-dlp directly, but I want to separate the crawling and downloading processes to avoid IP blocking issues by Google. However, after obtaining the download link through yt-dlp and downloading it separately, the speed becomes very slow, and I am not using chunked downloading. Is it possible to get a download link without speed limitations?

**Comment by kaixuangh** [comment]
> Is the download fast when downloading through yt-dlp? Are you chunking your downloads to 10 MB?

Yes, the download speed is fast when using yt-dlp directly, but I want to separate the crawling and downloading processes to avoid IP blocking issues by Google. However, after obtaining the download link through yt-dlp and downloading it separately, the speed becomes very slow, and I am not using chunked downloading. Is it possible to get a download link without speed limitations?

**Comment by kaixuangh** [comment]
> Is the download fast when downloading through yt-dlp? Are you chunking your downloads to 10 MB?

this is my download code:
 download_video_url = download_info.get('download_video_url')
        download_audio_url = download_info.get('download_audio_url')
        ydl_opts_video = {
            'outtmpl': os.path.join(youtube_path, f'{video_name}'),
            'external_downloader_args': '-j 10',
            'skip_unavailable_fragments': False,
            'retries': 10,
            'file_access_retries': 3,
            'fragment_retries': 10
        }
        ydl_opts_audio = {
            'outtmpl': os.path.join(youtube_path, f'{audio_name}'),
            'external_downloader_args': '-j 10',
            'skip_unavailable_fragments': False,
            'retries': 10,
            'file_access_retries': 3,
            'fragment_retries': 10
        }
        start_msec = time.time()
        with yt_dlp.YoutubeDL(ydl_opts_video) as ydl_video, \
                    yt_dlp.YoutubeDL(ydl_opts_audio) as ydl_audio:
                ydl_video.download([download_video_url])
                ydl_audio.download([download_audio_url])

download_video_url is:
https://www.youtube.com/watch?v=KbahC-QCKU8" get video download url :https://rr4---sn-ajogu5-55.googlevideo.com/videoplayback?expire=1726936076&ei=rJ_uZoH4EMyU1d8PmLKfwQs&ip=152.67.219.91&id=o-APZ7h6_rlhdF3HFEzzkLfv8CSzB-Bf7TGFRJ5rvFC1gq&itag=135&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=2t&mm=31%2C29&mn=sn-ajogu5-55%2Csn-ogueln66&ms=au%2Crdu&mv=m&mvi=4&pl=24&initcwndbps=351250&siu=1&vprv=1&svpuc=1&mime=video%2Fmp4&rqh=1&gir=yes&clen=190292913&dur=2448.581&lmt=1726434645326403&mt=1726914060&fvip=1&keepalive=yes&c=IOS&txp=4532434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Csiu%2Cvprv%2Csvpuc%2Cmime%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRQIhALnvIDf8YS2BqjtyLRtHLT0LxNPELavJmhIgtV9bZjQhAiAHEBJA-c2eajmCIxyUplHLGIgVNiobiO7JeiwcRB0qTg%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=ABPmVW0wRQIgVD5XnF62Q7v3C0QpKSqlYzvTiyCx42uJiEvXLH2WHEcCIQD5QR-6P1ZWqrlJ9DEh0RNuemQxZa2folt8tVY9dyi3Gg%3D%3D

**Comment by seproDev** [comment]
You need to download the videos in chunks of 10MB max. Otherwise, you will get throttled. Afaik. there is no way around this.

**Comment by kaixuangh** [comment]
> Is the download fast when downloading through yt-dlp? Are you chunking your downloads to 10 MB?

his is my download code:
download_video_url = download_info.get('download_video_url')
download_audio_url = download_info.get('download_audio_url')
ydl_opts_video = {
'outtmpl': os.path.join(youtube_path, f'{video_name}'),
'external_downloader_args': '-j 10',
'skip_unavailable_fragments': False,
'retries': 10,
'file_access_retries': 3,
'fragment_retries': 10
}
ydl_opts_audio = {
'outtmpl': os.path.join(youtube_path, f'{audio_name}'),
'external_downloader_args': '-j 10',
'skip_unavailable_fragments': False,
'retries': 10,
'file_access_retries': 3,
'fragment_retries': 10
}
start_msec = time.time()
with yt_dlp.YoutubeDL(ydl_opts_video) as ydl_video,
yt_dlp.YoutubeDL(ydl_opts_audio) as ydl_audio:
ydl_video.download([download_video_url])
ydl_audio.download([download_audio_url])

download_video_url is:
https://rr4---sn-ajogu5-55.googlevideo.com/videoplayback?expire=1726936076&ei=rJ_uZoH4EMyU1d8PmLKfwQs&ip=152.67.219.91&id=o-APZ7h6_rlhdF3HFEzzkLfv8CSzB-Bf7TGFRJ5rvFC1gq&itag=135&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=2t&mm=31%2C29&mn=sn-ajogu5-55%2Csn-ogueln66&ms=au%2Crdu&mv=m&mvi=4&pl=24&initcwndbps=351250&siu=1&vprv=1&svpuc=1&mime=video%2Fmp4&rqh=1&gir=yes&clen=190292913&dur=2448.581&lmt=1726434645326403&mt=1726914060&fvip=1&keepalive=yes&c=IOS&txp=4532434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Csiu%2Cvprv%2Csvpuc%2Cmime%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRQIhALnvIDf8YS2BqjtyLRtHLT0LxNPELavJmhIgtV9bZjQhAiAHEBJA-c2eajmCIxyUplHLGIgVNiobiO7JeiwcRB0qTg%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=ABPmVW0wRQIgVD5XnF62Q7v3C0QpKSqlYzvTiyCx42uJiEvXLH2WHEcCIQD5QR-6P1ZWqrlJ9DEh0RNuemQxZa2folt8tVY9dyi3Gg%3D%3D

**Comment by kaixuangh** [comment]
> https://rr4---sn-ajogu5-55.googlevideo.com/videoplayback?expire=1726936076&ei=rJ_uZoH4EMyU1d8PmLKfwQs&ip=152.67.219.91&id=o-APZ7h6_rlhdF3HFEzzkLfv8CSzB-Bf7TGFRJ5rvFC1gq&itag=135&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=2t&mm=31%2C29&mn=sn-ajogu5-55%2Csn-ogueln66&ms=au%2Crdu&mv=m&mvi=4&pl=24&initcwndbps=351250&siu=1&vprv=1&svpuc=1&mime=video%2Fmp4&rqh=1&gir=yes&clen=190292913&dur=2448.581&lmt=1726434645326403&mt=1726914060&fvip=1&keepalive=yes&c=IOS&txp=4532434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Csiu%2Cvprv%2Csvpuc%2Cmime%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRQIhALnvIDf8YS2BqjtyLRtHLT0LxNPELavJmhIgtV9bZjQhAiAHEBJA-c2eajmCIxyUplHLGIgVNiobiO7JeiwcRB0qTg%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=ABPmVW0wRQIgVD5XnF62Q7v3C0QpKSqlYzvTiyCx42uJiEvXLH2WHEcCIQD5QR-6P1ZWqrlJ9DEh0RNuemQxZa2folt8tVY9dyi3Gg%3D%3D



> You need to download the videos in chunks of 10MB max. Otherwise, you will get throttled. Afaik. there is no way around this.



> You need to download the videos in chunks of 10MB max. Otherwise, you will get throttled. Afaik. there is no way around this.

I want to download this url:
https://rr4---sn-ajogu5-55.googlevideo.com/videoplayback?expire=1726936076&ei=rJ_uZoH4EMyU1d8PmLKfwQs&ip=152.67.219.91&id=o-APZ7h6_rlhdF3HFEzzkLfv8CSzB-Bf7TGFRJ5rvFC1gq&itag=135&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=2t&mm=31%2C29&mn=sn-ajogu5-55%2Csn-ogueln66&ms=au%2Crdu&mv=m&mvi=4&pl=24&initcwndbps=351250&siu=1&vprv=1&svpuc=1&mime=video%2Fmp4&rqh=1&gir=yes&clen=190292913&dur=2448.581&lmt=1726434645326403&mt=1726914060&fvip=1&keepalive=yes&c=IOS&txp=4532434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Csiu%2Cvprv%2Csvpuc%2Cmime%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRQIhALnvIDf8YS2BqjtyLRtHLT0LxNPELavJmhIgtV9bZjQhAiAHEBJA-c2eajmCIxyUplHLGIgVNiobiO7JeiwcRB0qTg%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=ABPmVW0wRQIgVD5XnF62Q7v3C0QpKSqlYzvTiyCx42uJiEvXLH2WHEcCIQD5QR-6P1ZWqrlJ9DEh0RNuemQxZa2folt8tVY9dyi3Gg%3D%3D

can give me the example code?

**Comment by bashonly** [comment]
what are you trying to do? why are you downloading in 3 separate steps?

**Comment by dirkf** [comment]
1. Is there more that you should explain about your "separation" between crawling and downloading?

2. What happens if you generate the info-json without downloading and then `with yt_dlp.YoutubeDL(audio_video_opts) as ydl: ydl.download_with_info_file(info_json_file)`?

**Comment by observeroftime02** [comment]
> I want to separate the crawling and downloading processes to avoid IP blocking issues by Google

Are you by chance generating the download link on a different machine with a different IP? AFAIK those download links will only give you the proper speeds when used by the IP they were generated on. Say you use one machine to generate the download links, then a separate machine to do the actual download. Your download link would be throttled. You can actually see the IP the link was generated on inside of the download URL itself.

Just a hunch based on your quote there, if you do both on the same machine / IP then it should give you proper speed. AFAIK these download links also expire after a time, and the 30 kb/s speed looks like basic throttling. If that's not what you're doing then disregard my comment.
