### ISSUE TITLE
Clarifications of PO Token process

### ISSUE THREAD

**Issue by mokhosh** [yt-dlp/yt-dlp#11053]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I'm trying to follow the logged out steps in https://github.com/yt-dlp/yt-dlp/wiki/Extractors and I have a few questions.

1. I open an incognito browser and paste the url, and follow the steps 1 and 2
2. When I press play as instructed in step 3, I get the PO Token, but the player in the browser is saying "Sign in to confirm you’re not a bot"
3. Is the PO Token useful even though I'm getting this error? Or should I skip and only copy if the player starts playing?
4. In step 5 you say "export cookies", but I didn't find an official way of exporting cookies.
5. I downloaded two extensions called cookie editor. One of them only shows the PREF cookie, and the other shows some __Secure cookies. None of them show the VISITOR_INFO1_LIVE cookie even though I can see it in the network tab. What am I missing here?

Thanks

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by coletdjnz** [comment]
If you are getting `Sign in to confirm you’re not a bot` in the browser then your IP is already blocked and PO Token will not help. 

The main purpose of passing PO Token is to help _prevent_ getting blocked (if on non-DC IP) and allow formats from web clients to work.

For extracting cookies see https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp

**Comment by mokhosh** [comment]
Thanks this is very helpful. 

One more question. If I get the po token from a client that's not blocked, will it help a server that might already be blocked? Or do I need to change the server ip as well?

**Comment by Elite** [comment]
@mokhosh No, PO Token is bound to that IP, so you cannot use some other IP to generate POToken and use on your setup.

**Comment by mokhosh** [comment]
Ah, ok.
@Elite So, is there a way to generate a PO Token on a vps where you can't open a browser?

**Comment by grqz** [comment]
yes, with tools like LuanRT/BgUtils, iv-org/youtube-trusted-session-generator and YunzheZJU/youtube-po-token-generator
but it is very likely to be broken on a vps even with potoken

**Comment by Mswpresents** [comment]
Anybody Can make its permanent Solution

**Comment by mokhosh** [comment]
> but it is very likely to be broken on a vps even with potoken passed

@grqz Why is that?

How are all the "youtube downloader" websites working currently?

**Comment by mokhosh** [comment]
Update, here's what I tried:

1. used https://github.com/iv-org/youtube-trusted-session-generator the docker version and got two values
2. put them in `/etc/yt-dlp.conf` like so:
```
--extractor-args "youtube:player..."
```
3. tried using yt-dlp and got "Sign in to confirm you’re not a bot. This helps protect our community. Learn more" again.

Any ideas?

**Comment by bashonly** [comment]
> Why is that?

because:

> If you are getting `Sign in to confirm you’re not a bot` in the browser then your IP is already blocked and PO Token will not help.

---

> How are all the "youtube downloader" websites working currently?

ask them

**Comment by mokhosh** [comment]
> because:
> 
> > If you are getting `Sign in to confirm you’re not a bot` in the browser then your IP is already blocked and PO Token will not help.

No but let's say I get a new VPS. Then I should be able to have a clean setup right?
(But it didn't work as per my previous comment)



> ask them

lol, thank I will. I just thought some of them might pass by.

**Comment by Elite** [comment]
>but it is very likely to be broken on a vps even with potoken passed

Why will that be the case if the VPS IP is not flagged?

**Comment by seproDev** [comment]
Since youtube has started broadly blocking access from datatcenter ips. Even if no one ever accessed youtube from that IP it could still be blocked.

**Comment by fireattack** [comment]
I think we should clarify in https://github.com/yt-dlp/yt-dlp/wiki/Extractors#youtube when PO token was needed to be manually set to begin with.

The article reads like you always need to do this step (".. a parameter that YouTube requires to be sent with video ..."), but in reality it looks to me (correct me if I'm wrong) if you just use your residential IP, you either don't need this token at all, or yt-dlp handles it for you already. Because most of people never do anything about it and it works fine.

**Comment by coletdjnz** [comment]
> I think we should clarify in https://github.com/yt-dlp/yt-dlp/wiki/Extractors#youtube when PO token was needed to be manually set to begin with.
> 
> The article reads like you always need this token (".. a parameter that YouTube requires to be sent with video ..."), but in reality it looks to me (correct me if I'm wrong) if you just use your residential IP, you either don't need this token at all, or yt-dlp handles it for you already. Because most of people never do anything about it and it works fine.

The wiki states:

> Proof of Origin (PO) token is a parameter that YouTube requires to be sent with video playback requests from some clients. Without it, requests for the affected clients' format URLs may return HTTP Error 403, or result in your account or IP address being blocked.

This other words:
1. PO Token is required for *some* (Innertube) clients (player-client)
2. If it is not provided for those clients that require it, the download may/will fail with a 403
3. In general, if it is not provided, because it is a way of telling youtube you are a request from a genuine client, it *may* result in your IP or account being blocked. (not confirmed, but suggested due to what the token is)

The docs don't say what clients currently require the token (WEB and ANDROID), nor do they say that the default clients we have currently don't require a token. Hence why for general downloads it works fine for your average user. Perhaps we could add something to clarify that?

YouTube's  use of PO Token enforcement is still in early stages hence the lack of clarity as we don't know too much either. 

ps. suggestions better to be made as issues on the [yt-dlp-wiki](https://github.com/yt-dlp/yt-dlp-wiki) repo :)

**Comment by blisst** [comment]
@mokhosh 
If you ever figure out how the current YouTube downloader websites are working, please let me know!

**Comment by mokhosh** [comment]
> @mokhosh If you ever figure out how the current YouTube downloader websites are working, please let me know!

@blisst I managed to fix my issue by doing OAuth login. Remember not to use your main account, and not list your main account as recovery email of the accounts you're using.

**Comment by blisst** [comment]
OAuth is no longer supported though

**Comment by blisst** [comment]
> > @mokhosh If you ever figure out how the current YouTube downloader websites are working, please let me know!
> 
> @blisst I managed to fix my issue by doing OAuth login. Remember not to use your main account, and not list your main account as recovery email of the accounts you're using.

OAuth is no longer supported though

**Comment by LovesTha** [comment]
> If you are getting `Sign in to confirm you’re not a bot` in the browser then your IP is already blocked and PO Token will not help.
> 
> The main purpose of passing PO Token is to help _prevent_ getting blocked (if on non-DC IP) and allow formats from web clients to work.
> 
> For extracting cookies see https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp

A pity that yt-dlp only suggests using a PO Token after you are blocked and as the way to solve the block.....

**Comment by bashonly** [comment]
> A pity that yt-dlp only suggests using a PO Token after you are blocked and as the way to solve the block.....

No? Nowhere do we suggest that using a PO token can bypass a block if you've already been blocked. The comment you're quoting says the exact opposite, and does the wiki, and so do maintainers' comments in the related issues.
