### ISSUE TITLE
Too many 'time out' errors from YT

### ISSUE THREAD

**Issue by Napoleon-BlownApart** [yt-dlp/yt-dlp#11060]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

When downloading from YT, using format 95 most of the time, I get numerous 'time out. Retrying (1/10)' errors.
Though I always get file in the end, these errors really slow down the process.  Is this a settings issue, platform issue, or something not right in yt-dlp?

Below is the output showing the time-out errors.
```
[download]   8.5% of ~  35.92MiB at  143.55KiB/s ETA 03:56 (frag 17/189)[download] Got error: timed out. Retrying (1/10)...
[download]  25.4% of ~  33.45MiB at  172.37KiB/s ETA 03:53 (frag 49/189)[download] Got error: timed out. Retrying (1/10)...
[download]  38.6% of ~  33.56MiB at  129.32KiB/s ETA 02:57 (frag 74/189)[download] Got error: timed out. Retrying (1/10)...
[download]  90.5% of ~  35.26MiB at  118.80KiB/s ETA 00:31 (frag 172/189)[download] Got error: timed out. Retrying (1/10)...
[download]  98.5% of ~  35.18MiB at  107.08KiB/s ETA 00:07 (frag 187/189)[download] Got error: timed out. Retrying (1/10)...
```

Any tips are welcome, thanks!

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by seproDev** [comment]
Please provide a verbose log. Timeout errors would generally indicate network issues on your end.

**Comment by Napoleon-BlownApart** [comment]
Understand, my internet connectivity isn't that bad.  This happens particularly with YT.

**Comment by dirkf** [comment]
>... Timeout errors would generally indicate network issues on your end.
...

Or perhaps somewhere between "your end" and the YT CDN, say because [a govt is digging around in the traffic](https://github.com/yt-dlp/yt-dlp/issues/10443).
