### ISSUE TITLE
Youtube says: Video unavailable. This video contains content from SME, who has blocked it in your country on copyright grounds.

### ISSUE THREAD

**Issue by Cryosim** [yt-dlp/yt-dlp#11067]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Hi, Why youtube says me is SME copyright, if i try watching from VPS+VPN-Xray-Vless in Germany? This video allowed in Germany.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
C:\Users\mcmas>python -myt_dlp -vUF https://www.youtube.com/watch?v=y21nU0J5AqY
[debug] Command-line config: ['-vUF', 'https://www.youtube.com/watch?v=y21nU0J5AqY']
[debug] Encodings: locale cp1251, fs utf-8, pref cp1251, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.09.17.232940 from yt-dlp/yt-dlp-nightly-builds [4a9bc8c36] (pip)
[debug] Python 3.12.1 (CPython AMD64 64bit) - Windows-11-10.0.22631-SP0 (OpenSSL 3.0.11 19 Sep 2023)
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.07.04, mutagen-1.47.0, requests-2.32.3, sqlite3-3.43.1, urllib3-2.2.2, websockets-13.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1835 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.09.17.232940 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.09.17.232940 from yt-dlp/yt-dlp-nightly-builds)
[youtube] Extracting URL: https://www.youtube.com/watch?v=y21nU0J5AqY
[youtube] y21nU0J5AqY: Downloading webpage
[youtube] y21nU0J5AqY: Downloading ios player API JSON
[youtube] y21nU0J5AqY: Downloading web creator player API JSON
ERROR: [youtube] y21nU0J5AqY: Video unavailable. This video contains content from SME, who has blocked it in your country on copyright grounds
  File "C:\Users\mcmas\AppData\Local\Programs\Python\Python312\Lib\site-packages\yt_dlp\extractor\common.py", line 741, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mcmas\AppData\Local\Programs\Python\Python312\Lib\site-packages\yt_dlp\extractor\youtube.py", line 4467, in _real_extract
    self.raise_no_formats(reason, expected=True)
  File "C:\Users\mcmas\AppData\Local\Programs\Python\Python312\Lib\site-packages\yt_dlp\extractor\common.py", line 1275, in raise_no_formats
    raise ExtractorError(msg, expected=expected, video_id=video_id)
```

**Comment by seproDev** [comment]
Are you sure you are accessing the video from an IP address that Google categorizes as from Germany?
Accessing the video from Germany it plays fine and yt-dlp can download it. Accessing it from Russia I get the same error message as yt-dlp on the website:
![image](https://github.com/user-attachments/assets/5f8dd966-7b65-4d45-bd8c-5409eb95b7a3)

**Comment by Cryosim** [comment]
@seproDev Yes, VPN changed my IP to Germany. I also try Wireguard VPN, same SME copyryght.

**Comment by Cryosim** [comment]
@seproDev VPN server on VPS, VPN client on Windows PC as tunnel.

**Comment by Cryosim** [comment]
@seproDev In the browser not playing. show SME copyright.
`curl ifconfig.me` says VPN IP address.

**Comment by seproDev** [comment]
If you cannot play the file in the browser then yt-dlp also can't download it.
What country does YouTube say you are in?
For Germany, it should say "DE", while for Russia, it should say "RU".
![image](https://github.com/user-attachments/assets/a114004c-f069-43fb-bc1f-5db2154a8119)
If this says RU then either your VPS isn't in Germany or Google is misidentifying the IP.

Either way, there is nothing that can be done from the yt-dlp side. yt-dlp can only download what you can also play back in a browser.

**Comment by october262** [comment]
> ```shell
> https://www.youtube.com/watch?v=y21nU0J5AqY
> ```

can you change your VPN to a USA IP address ??
video plays fine here in USA
