### ISSUE TITLE
[instagram] unable to extract "username"

### ISSUE THREAD

**Issue by AhmadAlwaeily** [yt-dlp/yt-dlp#11062]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Hi ever one , when I need download video this error show to me 
Unable to extract video url; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

### Provide verbose output that clearly demonstrates the problem

- [x] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [x] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [x] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by grqz** [comment]
the site is likely to be broken. please post a verbose log





> ### Provide verbose output that clearly demonstrates the problem
> * [ ]  Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
> * [ ]  If using API, add `'verbose': True` to `YoutubeDL` params instead
> * [ ]  Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below
> 
> ### Complete Verbose Output
> _No response_

**Comment by pzhlkj6612** [comment]
Which site?

<br>

> ### Complete Verbose Output
> _No response_

There is still no log posted.

**Comment by AhmadAlwaeily** [comment]
I used android studio to development project for download videos by used yt-dlp when run the project this error that already show it to you ,why?

**Comment by seproDev** [comment]
Without a verbose log we can not help you.

**Comment by AhmadAlwaeily** [comment]
Hi ever one , when I need download video this error show to me
Unable to extract video url; please report this issue on https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using yt-dlp -U

**Comment by AhmadAlwaeily** [comment]
https://www.instagram.com/reel/C85ELOyo5aw/?igsh=cjFwODI5aGE2cjFp

**Comment by AhmadAlwaeily** [comment]
Any details more,I don't understand more than that!

**Comment by seproDev** [comment]
You have still not provided a verbose log...
Though given that the link, you shared is Instagram, you are likely running against the issue of Instagram blocking anonymous access. You could try passing cookies, but that comes at the risk of getting your account locked/banned.

**Comment by AhmadAlwaeily** [comment]
I new in github , help me in this error :- ERROR: 3465801984906655874: An
extractor error has occurred. (caused by KeyError('config')); please report
this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the
appropriate issue template. Confirm you are on the latest version using
yt-dlp -U

**Comment by grqz** [comment]
post your **verbose** log. for example, if you are using `yt-dlp "url"`, run `yt-dlp -vU "url"` and put the **full** log here

**Comment by AhmadAlwaeily** [comment]
Ok I will try

**Comment by AhmadAlwaeily** [comment]
yt-dlp -vU "
https://www.instagram.com/reel/C85ELOyo5aw/?igsh=cjFwODI5aGE2cjFp"
[debug] Command-line config: ['-vU', '
https://www.instagram.com/reel/C85ELOyo5aw/?igsh=cjFwODI5aGE2cjFp']
[debug] Encodings: locale utf-8, fs utf-8, pref utf-8, out utf-8, error
utf-8, screen utf-8
[debug] yt-dlp version ***@***.*** from yt-dlp/yt-dlp [4d9231208]
(pip)
[debug] Python 3.11.10 (CPython aarch64 64bit) -
Linux-4.14.186-g7c18952d3c68-aarch64-with-libc (OpenSSL 3.3.2 3 Sep 2024,
libc)
[debug] exe versions: ffmpeg 6.1.2 (setts), ffprobe 6.1.2
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0,
certifi-2024.08.30, mutagen-1.47.0, requests-2.32.3, sqlite3-3.46.1,
urllib3-2.2.3, websockets-13.0.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1830 extractors
[debug] Fetching release info:
https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: ***@***.*** from yt-dlp/yt-dlp
yt-dlp is up to date ***@***.*** from yt-dlp/yt-dlp)
[Instagram] Extracting URL:
https://www.instagram.com/reel/C85ELOyo5aw/?igsh=cjFwODI5aGE2cjFp
[Instagram] C85ELOyo5aw: Setting up session
[Instagram] C85ELOyo5aw: Downloading JSON metadata
WARNING: [Instagram] unable to extract username; please report this issue
on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the
appropriate issue template. Confirm you are on the latest version using
yt-dlp -U
ERROR: [Instagram] C85ELOyo5aw: Unable to extract video url; please report
this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the
appropriate issue template. Confirm you are on the latest version using
yt-dlp -U
  File
"/data/data/com.termux/files/usr/lib/python3.11/site-packages/yt_dlp/extractor/common.py",
line 740, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File
"/data/data/com.termux/files/usr/lib/python3.11/site-packages/yt_dlp/extractor/instagram.py",
line 490, in _real_extract
    video_url = self._og_search_video_url(webpage, secure=False)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File
"/data/data/com.termux/files/usr/lib/python3.11/site-packages/yt_dlp/extractor/common.py",
line 1479, in _og_search_video_url
    return self._html_search_regex(regexes, html, name, **kargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File
"/data/data/com.termux/files/usr/lib/python3.11/site-packages/yt_dlp/extractor/common.py",
line 1369, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags,
group)

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File
"/data/data/com.termux/files/usr/lib/python3.11/site-packages/yt_dlp/extractor/common.py",
line 1333, in _search_regex
    raise RegexNotFoundError(f'Unable to extract {_name}')

**Comment by grqx** [comment]
can you watch the video in the browser _without_ logging in? If you can't, try `yt-dlp -vU --cookies-from-browser <BROWSER> “https://www.instagram.com/reel/C85ELOyo5aw/?igsh=cjFwODI5aGE2cjFp”`(replace `<BROWSER>` with your browser's name, it can be one of `brave`, `chrome`, `chromium`, `edge`, `firefox`, `opera`, `safari`, `vivaldi`, `whale`)

**Comment by bashonly** [comment]
Duplicate of #5967

**Comment by AhmadAlwaeily** [comment]
Sorry, I will go , thank you for answer,thank you for all , bye , and I'm
sorry again.
