### ISSUE TITLE
[Question] ~/yt-dlp.conf instead of ~/.yt-dlp.conf ?

### ISSUE THREAD

**Issue by JensKorte** [yt-dlp/yt-dlp#1106]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

In the README and checked in real there is
> ~/yt-dlp.conf

as a default, without a dot in the beginning. Did you mean it, or was is by accident?

youtube-dl and the other programs so far use ~/.programname.conf

**Comment by pukkandan** [comment]
youtube-dl uses `~/youtube-dl.conf` without a dot at the start
https://github.com/ytdl-org/youtube-dl/blob/a8035827177d6b59aca03bd717acb6a9bdd75ada/youtube_dl/options.py#L80-L83

**Comment by JensKorte** [comment]
You are right. I don't know why I thought of ~/.youtube-dl.conf.

**Comment by liMilCo** [comment]
i used:
 C:\Users\<user name>\youtube-dl.conf
and 
  %APPDATA%\youtube-dl\config.txt
it didn't work but 
  C:\Users\<user name>\yt-dlp.conf
worked.
