### ISSUE TITLE
Bug when download chapter when ffmpeg path enabled

### ISSUE THREAD

**Issue by yasirarism** [yt-dlp/yt-dlp#11073]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

I'm download chapter using yt-dlp, when i'm using it without ffmpeg path it will working. But if i add ffmpeg path, it will thrown error. I think it missing some parameter in yt-dlp code.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
Input:
from yt_dlp import YoutubeDL
from yt_dlp.utils import download_range_func

youtube_id = "https://youtu.be/C5-nZ8WM0NU"
ctx = {
    'download_ranges': download_range_func([], [[0.0, 81.0]]),
    'logtostderr': True,
    'verbose': True,
    'cookiefile': "cookies.txt",
    "ffmpeg_location": "/usr/bin/my-ffmpeg",
}

with YoutubeDL(ctx) as ydl:
    ydl.download(youtube_id)


Output:
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8 (No ANSI), error utf-8 (No ANSI), screen utf-8 (No ANSI)
[debug] yt-dlp version stable@2024.08.06 from yt-dlp/yt-dlp [4d9231208] (pip) API
[debug] params: {'download_ranges': yt_dlp.utils.download_range_func([], [[0.0, 81.0]]), 'logtostderr': True, 'verbose': True, 'cookiefile': 'cookies.txt', 'compat_opts': set(), 'http_headers': {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.43 Safari/537.36', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'Accept-Language': 'en-us,en;q=0.5', 'Sec-Fetch-Mode': 'navigate'}}
[debug] Python 3.10.6 (CPython aarch64 64bit) - Linux-6.5.0-1026-oracle-aarch64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffprobe 4.4.2, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2024.08.30, curl_cffi-0.7.1, mutagen-1.46.0, requests-2.32.3, sqlite3-3.37.2, urllib3-1.26.20, websockets-13.0.1, xattr-0.10.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1830 extractors
[youtube] Extracting URL: https://youtu.be/C5-nZ8WM0NU
[youtube] C5-nZ8WM0NU: Downloading webpage
[debug] [youtube] Extracted SAPISID cookie
[youtube] C5-nZ8WM0NU: Downloading ios player API JSON
[youtube] C5-nZ8WM0NU: Downloading web creator player API JSON
[debug] Loading youtube-nsig.c41f1db5 from cache
[debug] [youtube] Decrypted nsig jJT2m_kEaxEGnOAdG => fgBqRlzvhg0l6w
[debug] Loading youtube-nsig.c41f1db5 from cache
[debug] [youtube] Decrypted nsig ABXmgw4CLbUQZ-W6Y => vtVCuL4oFfYTsg
[youtube] C5-nZ8WM0NU: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
WARNING: ffmpeg not found. The downloaded format may not be the best available. Installing ffmpeg is strongly recommended: https://github.com/yt-dlp/yt-dlp#dependencies
[debug] Default format spec: best/bestvideo+bestaudio
[info] C5-nZ8WM0NU: Downloading 1 format(s): 18
[info] C5-nZ8WM0NU: Downloading 1 time ranges: 0.0-81.0
ERROR: You have requested downloading the video partially, but ffmpeg is not installed. Aborting
```

**Comment by rdamas** [comment]
Is this: `"ffmpeg_location": "/usr/bin/my-ffmpeg,` a typo? Or does the entry have a closing "?

My guess: there's a typo somewhere in your real script.

**Comment by yasirarism** [comment]
> Is this: `"ffmpeg_location": "/usr/bin/my-ffmpeg,` a typo? Or does the entry have a closing "?
> 
> My guess: there's a typo somewhere in your real script.

That's just typo and i have edit it in my sample code, and i have closed quotation still got that error. I have renamed ffmpeg package to another package to prevent some server detect this package.

**Comment by bashonly** [comment]
```py
from yt_dlp.postprocessor import FFmpegPostProcessor
FFmpegPostProcessor._ffmpeg_location.set('/usr/bin/my-ffmpeg')
```

see also
- https://github.com/yt-dlp/yt-dlp/issues/6439#issuecomment-1455130033
- https://github.com/yt-dlp/yt-dlp/issues/2191#issuecomment-1972630504

**Comment by Mohammad9760** [comment]
```
from yt_dlp.postprocessor import FFmpegPostProcessor
FFmpegPostProcessor._ffmpeg_location.set('/usr/bin/my-ffmpeg')
```
doesn't seem to do anything. still produces the error:
```
ERROR: Postprocessing: ffprobe and ffmpeg not found. Please install or provide the path using --ffmpeg-location
An error occurred while downloading https...: ERROR: Postprocessing: ffprobe and ffmpeg not found. Please install or provide the path using --ffmpeg-location
```
