### ISSUE TITLE
add --remove-hashtags option

### ISSUE THREAD

**Issue by Markus-N** [yt-dlp/yt-dlp#11077]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

People often add hashtags to their video titles, e.g. on YouTube shorts (but not only there).  
I'm usually using this pattern for the output filename:  
`--output "%(upload_date)s %(title)s %(resolution)s %(id)s.%(ext)s"`  
I'd like to have an option to remove these redundant words completely from the title. But not in the same way as **--restrict-filenames** which would only remove the hash character but keep the word after it. My idea is to remove everything from the hash character to the next whitespace.  
I'm aware that this would create a problem when the title consists of hashtags only. And so far, I have no idea what to do in this case. Maybe that could be discussed here.

I'm unsure how the output of a verbose  / debug run of the program helps in this case, so I omitted it.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
`--replace-in-metadata title "#" ""`

**Comment by Markus-N** [comment]
Not sure if this is what I need ... I don't want only the # to disappear, but #everything #that #starts #with #a #hash

**Comment by Markus-N** [comment]
Oh, that's cool. I just did not get that from that chapter.
