### ISSUE TITLE
Having yt-dlp create a symlink for a certain file extension in another folder

### ISSUE THREAD

**Issue by Aces-and-Jacks** [yt-dlp/yt-dlp#11080]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

At the moment this isn't a feature request, just a question. Maybe there's a different wording so asking in case. If this isn't possible I'll open a feature request. 

So basically I was wondering if there's any way to symlink downloaded files of a certain extension automatically to another location using yt-dlp? I currently have everything downloaded to their own folder, however it'd be easier to only view videos and not the other file types if they were symlinked to another location. I don't want to make a duplicate copy. 

I did a command-find for anything mentioning symlink in README and nothing showed. I've searched in issues and saw nothing in a title refering to symlinking files. I've updated yt-dlp to latest version. If I somehow missed anything referring to this, like maybe a different word used, I apologise about that. 

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
use `--exec` to with your shell's command for symlinking

**Comment by Aces-and-Jacks** [comment]
well I mean something I can put in a config so I wouldn't have to worry about manually doing it. Is that a thing yt-dlp can do? If I do it manually through terminal I'd having to do it for each video on top of downloading. If I download in bulk that'd be troublesome

**Comment by bashonly** [comment]
you can put the `--exec` arg in your config

**Comment by Aces-and-Jacks** [comment]
I can...? So your saying I can use `--exec` in my config file to symlink?

**Comment by bashonly** [comment]
yep

**Comment by Aces-and-Jacks** [comment]
Would you be able to provide an example of what the command may look like to symlink an extension upon download to another folder location? If you don't mind me asking.

**Comment by Aces-and-Jacks** [comment]
I'm not good with figuring that out. I can find it in README but figuring out the command for it, I can't do too well

**Comment by bashonly** [comment]
`--exec` just lets you run a shell command in the postprocessing stage. You haven't given enough info for me to suggest anything. What is the command you would use to create a symlink on your system?

**Comment by Aces-and-Jacks** [comment]
Sorry. Currently I have my config set to when it downloads a video it goes in a folder to `/Users/****/Library/Application Support/Stacher/Downloads/%(uploader)s%(upload_date)s_%(title)s.%(ext)s`
Along with anything else that may be downloaded. 

I want only the `.mp4` extension files to be symlinked to `/Users/***/Downloads/sym-folder` for example

**Comment by Aces-and-Jacks** [comment]
oh and my system is macOS. I'll look for the symlink command

**Comment by bashonly** [comment]
```
--exec 'cd "/Users/USERNAME/Downloads/sym-folder" && ln -s --'
```

**Comment by Aces-and-Jacks** [comment]
Thank you! I apreciate your help. 

Also what does the `&& ln -s --` part do?

**Comment by Aces-and-Jacks** [comment]
oh nvm

**Comment by Aces-and-Jacks** [comment]
I have one more question. If I wanted to do it for a different file type what would I need to change in the command?

**Comment by bashonly** [comment]
> ```bash
> --exec 'cd "/Users/USERNAME/Downloads/sym-folder" && ln -s --'
> ```

in the example I gave above, yt-dlp is adding the video filepath to the end of the command:

```
--exec [WHEN:]CMD               Execute a command, optionally prefixed with
                                when to execute it, separated by a ":".
                                Supported values of "WHEN" are the same as
                                that of --use-postprocessor (default:
                                after_move). Same syntax as the output
                                template can be used to pass any field as
                                arguments to the command. If no fields are
                                passed, %(filepath,_filename|)q is appended
                                to the end of the command. This option can
                                be used multiple times
```

so it's two commands that are being executed,

first, change directory to the target symlink folder:
```bash
cd "/Users/USERNAME/Downloads/sym-folder"
```
then, create the symlink in that directory:
```bash
ln -s -- %(filepath,_filename|)q
```

IMPORTANT: you should only ever use `%()q` in `--exec` arguments, and never `%()s`

> For example if I wanted to put the .decription in the folder instead of the .mp4?

The reason why I explained all that above is because there is not really a built-in way to use the .description filepath in the `--exec` line, and you'd need to do some shell string manipulation to achieve what you want (or write an external script)

**Comment by Aces-and-Jacks** [comment]
Alright. Thank you for explaining further. So currently as you say there's no built in way for any other file. The targeted extension `.mp4` works since it's applied to the end of the original command. So If I was just downloading the `.mp3` file that'd be shown instead, since that's the original target

**Comment by bashonly** [comment]
> So If I was just downloading the .mp3 file that'd be shown instead, since that's the original target

right

> So currently as you say there's no built in way for any other file

there are fields for some other files, e.g. `infojson_filename`, `thumbnails.:.filepath`, `requested_subtitles.en.filepath`, etc, just not for description

**Comment by Aces-and-Jacks** [comment]
> there are fields for some other files, e.g. infojson_filename, thumbnails.:.filepath, requested_subtitles.en.filepath, etc, just not for description

Wait, so what if I wanted to symlink `infojson_filename`? your saying that's possible? 

> I have one more question. If I wanted to do it for a different file type what would I need to change in the command? For example if I wanted to put the .decription in the folder instead of the .mp4?

Because over here I was just using `.description` as an example. But from what you're saying it sounds like I can symlink other formats?

**Comment by Aces-and-Jacks** [comment]
> separated by a ":".
                                Supported values of "WHEN" are the same as
                                that of --use-postprocessor (default:
                                after_move).

Is that refering to this part? No idea how it'd be typed

**Comment by Aces-and-Jacks** [comment]
Well never mind I suppose. I got my main question answered so that's good enough. Thank you again for your help
