### ISSUE TITLE
ERROR: [youtube] fVs0suPHAX8: Sign in to confirm your age. This video may be inappropriate for some users. 

### ISSUE THREAD

**Issue by leij0318** [yt-dlp/yt-dlp#11086]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Hongkong

### Provide a description that is worded well enough to be understood

But I get this error when downloading youtube videos
ERROR: [youtube] fVs0suPHAX8: Sign in to confirm your age. This video may be inappropriate for some users.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
。。
```

**Comment by GuyMicciche** [comment]
for me, disable VPN

**Comment by emperor06** [comment]
So yt-dlp does not support downloading videos that are age restricted anymore? (without logging in I mean)

**Comment by bashonly** [comment]
> So yt-dlp does not support downloading videos that are age restricted anymore? (without logging in I mean)

Only if the video is embeddable

**Comment by seproDev** [comment]
As an alternative, you can use this plugin: https://github.com/pukkandan/yt-dlp-YTAgeGateBypass

**Comment by leij0318** [comment]
> 然后按照说明进行操作并通过提供 cookie 进行登录。 详细日志也不是可选的。

I'm already logged into my youtube account using cookies.
```
WARNING: skipping cookie file entry due to invalid length 6: '.youtube.com\tTRUE\t/\tTRUE\t13374043424464235\tGPS\n'
WARNING: skipping cookie file entry due to invalid length 6: '.accounts.google.com\tTRUE\t/\tTRUE\t13376634449000000\tOTZ\n'
WARNING: skipping cookie file entry due to invalid length 6: '.youtube.com\tTRUE\t/\tTRUE\t13437114443000000\tPREF\n'
WARNING: skipping cookie file entry due to invalid length 6: '.accounts.google.com\tTRUE\t/\tTRUE\t13437114476933915\tACCOUNT_CHOOSER\n'
WARNING: skipping cookie file entry due to invalid lengt'.google.com\tTRUE\t/\tFALSE\t13437114476686382\tAPISID\n'
WARNING: skipping cookie file entry due to invalid length 6: '.google.com\tTRUE\t/\tFALSE\t13437114476686321\tHSID\n'
WARNING: skipping cookie file entry due to invalid length 6: '.accounts.google.com\tTRUE\t/\tTRUE\t13437114477140383\tLSID\n'
WARNING: skipping cookie file entry due to invalid length 6: '.google.com\tTRUE\t/\tTRUE\t13389853649685927\tNID\n'
WARNING: skipping cookie file entry due to invalid length 6: '.myaccount.google.com\tTRUE\t/\tTRUE\t13437114478256098\tOSID\n'
WARNING: skipping cookie file entry due to invalid length 6: '.gds.google.com\tTRUE\t/\tTRUE\t13376634481000000\tOTZ\n'
WARNING: skipping cookie file entry due to invalid length 6: '.google.com\tTRUE\t/\tTRUE\t13437114476686411\tSAPISID\n'
WARNING: skipping cookie file entry due to invalid length 6: '.google.com\tTRUE\t/\tFALSE\t13437114476686061\tSID\n'
WARNING: skipping cookie file entry due to invalid length 6: '.google.com\tTRUE\t/\tFALSE\t13405578481376938\tSIDCC\n'
WARNING: skipping cookie file entry due to invalid length 6: '.accounts.google.com\tTRUE\t/\tTRUE\t13437114476686569\tSMSV\n'
WARNING: skipping cookie file entry due to invalid length 6: '.google.com\tTRUE\t/\tTRUE\t13437114476686350\tSSID\n'
WARNING: skipping cookie file entry due to invalid length 6: '.accounts.google.com\tTRUE\t/\tTRUE\t13437114477140504\t__Host-1PLSID\n'
WARNING: skipping cookie file entry due to invalid length 6: '.accounts.google.com\tTRUE\t/\tTRUE\t13437114477140559\t__Host-3PLSID\n'
WARNING: skipping cookie file entry due to invalid length 6: '.accounts.google.com\tTRUE\t/\tTRUE\t13437114476686534\t__Host-GAPS\n'
WARNING: skipping cookie file entry due to invalid length 6: '.google.com\tTRUE\t/\tTRUE\t13437114476686440\t__Secure-1PAPISID\n'
WARNING: skipping cookie file entry due to invalid length 6: '.google.com\tTRUE\t/\tTRUE\t13437114476686103\t__Secure-1PSID\n'
WARNING: skipping cookie file entry due to invalid length 6: '.google.com\tTRUE\t/\tTRUE\t13405578481377016\t__Secure-1PSIDCC\n'
WARNING: skipping cookie file entry due to invalid length 6: '.google.com\tTRUE\t/\tTRUE\t13437114476686472\t__Secure-3PAPISID\n'
WARNING: skipping cookie file entry due to invalid length 6: '.google.com\tTRUE\t/\tTRUE\t13437114476686187\t__Secure-3PSID\n'
WARNING: skipping cookie file entry due to invalid length 6: '.google.com\tTRUE\t/\tTRUE\t13405578481377052\t__Secure-3PSIDCC\n'
WARNING: skipping cookie file entry due to invalid length 6: '.myaccount.google.com\tTRUE\t/\tTRUE\t13437114478256266\t__Secure-OSID\n'
ERROR: [youtube] 1bUAqRozxUM: Sign in to confirm you’re not a bot. This helps protect our community. Learn more
```
