### ISSUE TITLE
Request for streamtape.com

### ISSUE THREAD

**Issue by gaurang1123** [yt-dlp/yt-dlp#11097]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Example URLs

https://streamtape.com/v/oAyl8rV67auW39

### Provide a description that is worded well enough to be understood

it gives chinks of images

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
/content/yt-dlp
[debug] Command-line config: ['-v', '--downloader', 'aria2c', '-o', '/content/test.mp4', 'https://streamtape.com/v/oAyl8rV67auW39']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.08.06 from yt-dlp/yt-dlp [4d9231208] (source)
[debug] Lazy loading extractors is disabled
[debug] Git HEAD: fb8b7f226
[debug] Python 3.10.12 (CPython x86_64 64bit) - Linux-6.1.85+-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.08.30, mutagen-1.47.0, requests-2.32.3, secretstorage-3.3.1, sqlite3-3.37.2, urllib3-2.2.3, websockets-13.1
[debug] Proxy map: {'colab_language_server': '/usr/colab/bin/language_service'}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1835 extractors
[generic] Extracting URL: https://streamtape.com/v/oAyl8rV67auW39
[generic] oAyl8rV67auW39: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] oAyl8rV67auW39: Extracting information
[debug] Looking for embeds
[redirect] Following redirect to https://streamtape.com/v/+e+
[generic] Extracting URL: https://streamtape.com/v/+e+
[generic] +e+: Downloading webpage
ERROR: [generic] Unable to download webpage: HTTP Error 404: Not Found (caused by <HTTPError 404: Not Found>)
  File "/content/yt-dlp/yt_dlp/extractor/common.py", line 741, in extract
    ie_result = self._real_extract(url)
  File "/content/yt-dlp/yt_dlp/extractor/generic.py", line 2384, in _real_extract
    full_response = self._request_webpage(url, video_id, headers=filter_dict({
  File "/content/yt-dlp/yt_dlp/extractor/common.py", line 910, in _request_webpage
    raise ExtractorError(errmsg, cause=err)

  File "/content/yt-dlp/yt_dlp/extractor/common.py", line 897, in _request_webpage
    return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query, extensions))
  File "/content/yt-dlp/yt_dlp/YoutubeDL.py", line 4165, in urlopen
    return self._request_director.send(req)
  File "/content/yt-dlp/yt_dlp/networking/common.py", line 117, in send
    response = handler.send(request)
  File "/content/yt-dlp/yt_dlp/networking/_helper.py", line 208, in wrapper
    return func(self, *args, **kwargs)
  File "/content/yt-dlp/yt_dlp/networking/common.py", line 340, in send
    return self._send(request)
  File "/content/yt-dlp/yt_dlp/networking/_requests.py", line 365, in _send
    raise HTTPError(res, redirect_loop=max_redirects_exceeded)
yt_dlp.networking.exceptions.HTTPError: HTTP Error 404: Not Found
```

**Comment by garret1317** [comment]
You already asked this in the discord, the answer has not changed
piracy sites (or sites primarily used for piracy) will not be supported by yt-dlp

**Comment by davidebeatrici** [comment]
@garret1317 The website itself doesn't appear to promote piracy, in fact I'm pretty sure it is used because (according to the homepage) they allow videos up to 15 GB per file.

Realistically, copyrighted content could be anywhere and I personally don't think it's a good idea to avoid implementing a scraper for a random website just because it is relied on by some streaming hubs.

Also, there is a [working Java snippet](https://github.com/ChristopherProject/Streamtape-Video-Downloader) by @ChristopherProject, meaning that it's just a matter of translating existing code into Python.

**Comment by seproDev** [comment]
@davidebeatrici We will not add sites primarily used for piracy. This has been the policy for years. You can read more about the reasoning and what counts as "primarily used for piracy" here: https://github.com/yt-dlp/yt-dlp/wiki/FAQ#why-is-there-a-rule-against-websites-primarily-used-for-piracy
