### ISSUE TITLE
How to limit the length of the "title field" when exporting files?

### ISSUE THREAD

**Issue by wutongskype** [yt-dlp/yt-dlp#11096]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

When I use yt-dlp to download some videos from youtube on Windows 11, the file name is too long and the video cannot be played because the title field is too long. I guess the length of the "title field" of the downloaded video may exceed the limit of the Windows system. I used the "--windows-filenames" and "--trim-filenames 250" commands to limit the length. The former is used to avoid some unconventional characters, and the latter limits the length. However, the length limited by --trim-filenames seems to include the path. As a result, some of my output parameters are not displayed completely.

My output template:
set PRname=anyone
-o "%~dp0\%PRname%\[%%(playlist,channel)s][%%(playlist_id,channel_id)s]\[%%(uploader)s][%%(uploader_id)s]\[%%(upload_date)s][%%(id)s][%%(resolution)s][%%(format_id)s][%%(vcodec)s][%%(acodec)s][ %%(title)s].%%(ext)s"

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
`%(title).100B` or `%(title).50B` etc

**Comment by wutongskype** [comment]
> `%(title).100B` or `%(title).50B` etc

This problem makes me afraid to put the title field in front of the output file name, because I am afraid that a too long title will occupy the output of other parameters.

**Comment by bashonly** [comment]
what do you mean? with my suggestion you are truncating only the `title` field so that you don't need to use `--trim-filenames`, and then `title` can be placed anywhere in the output template

**Comment by wutongskype** [comment]
> what do you mean? with my suggestion you are truncating only the `title` field so that you don't need to use `--trim-filenames`, and then `title` can be placed anywhere in the output template

Thanks, it works fine.
