### ISSUE TITLE
'Unable to extract yt initial data' when using --cookies cookies.txt

### ISSUE THREAD

**Issue by pato-pan** [yt-dlp/yt-dlp#11094]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United States

### Provide a description that is worded well enough to be understood

similar issue report to #10953 but I use yt-dlp from the terminal. I had started having this issue recently where I think my cookies work for a moment, and after a few days they stop working with the error 

> WARNING: [youtube:tab] unable to extract yt initial data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

I thought the file got corrupted, but this happened again and it doesn't seem like any of my cookie files are working. Getting the cookies again always seems to fix the issue

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--yes-playlist', '--geo-bypass', '--embed-metadata', '--embed-thumbnail', '--embed-chapters', '-x', '-c', '-f', 'ba', '--audio-format', 'best', '--audio-quality', '0', '--cookies', 'cookies.txt', 'https://www.youtube.com/playlist?list=PLrUgkzDqaGJsbdWGhiE_CJSMVHsHre1cJ', '-o', '/home/user/music/test/%(title)s - %(uploader)s [%(id)s].%(ext)s']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.08.06 from yt-dlp/yt-dlp [4d9231208]
[debug] Python 3.12.6 (CPython x86_64 64bit) - Linux-6.10.10-zen1-1-zen-x86_64-with-glibc2.40 (OpenSSL 3.3.2 3 Sep 2024, glibc 2.40)
[debug] exe versions: ffmpeg 7.0.2 (setts), ffprobe 7.0.2, rtmpdump 2.4
[debug] Optional libraries: brotli-1.1.0, certifi-2024.08.30, mutagen-1.47.0, pycrypto-3.20.0, requests-2.32.3, sqlite3-3.46.1, urllib3-1.26.20
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Loaded 1830 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.08.06 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.08.06 from yt-dlp/yt-dlp)
[youtube:tab] Extracting URL: https://www.youtube.com/playlist?list=PLrUgkzDqaGJsbdWGhiE_CJSMVHsHre1cJ
[youtube:tab] PLrUgkzDqaGJsbdWGhiE_CJSMVHsHre1cJ: Downloading webpage
WARNING: [youtube:tab] unable to extract yt initial data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [youtube:tab] Incomplete yt initial data received. Retrying (1/3)...
[youtube:tab] PLrUgkzDqaGJsbdWGhiE_CJSMVHsHre1cJ: Downloading webpage
WARNING: [youtube:tab] unable to extract yt initial data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [youtube:tab] Incomplete yt initial data received. Retrying (2/3)...
[youtube:tab] PLrUgkzDqaGJsbdWGhiE_CJSMVHsHre1cJ: Downloading webpage
WARNING: [youtube:tab] unable to extract yt initial data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [youtube:tab] Incomplete yt initial data received. Retrying (3/3)...
[youtube:tab] PLrUgkzDqaGJsbdWGhiE_CJSMVHsHre1cJ: Downloading webpage
WARNING: [youtube:tab] unable to extract yt initial data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [youtube:tab] Incomplete yt initial data received; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U. Giving up after 3 retries
[debug] [youtube:tab] Extracted SAPISID cookie
[debug] [youtube:tab] Copying __Secure-3PAPISID cookie to SAPISID cookie
ERROR: [youtube:tab] PLrUgkzDqaGJsbdWGhiE_CJSMVHsHre1cJ: Playlists that require authentication may not extract correctly without a successful webpage download. If you are not downloading private content, or your cookies are only for the first account and channel, pass "--extractor-args youtubetab:skip=authcheck" to skip this check
  File "/usr/lib/python3.12/site-packages/yt_dlp/extractor/common.py", line 740, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/yt_dlp/extractor/youtube.py", line 4817, in wrapper
    info_dict = func(self, url, smuggled_data)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/yt_dlp/extractor/youtube.py", line 6751, in _real_extract
    data, ytcfg = self._extract_data(url, display_id)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/yt_dlp/extractor/youtube.py", line 5539, in _extract_data
    self._report_playlist_authcheck(ytcfg, fatal=fatal)
  File "/usr/lib/python3.12/site-packages/yt_dlp/extractor/youtube.py", line 5517, in _report_playlist_authcheck
    raise ExtractorError(
```

**Comment by bashonly** [comment]
seems like you're experiencing #8227

youtube rapidly rotates your cookies, so if you continue to use the session in your browser that you exported the cookies from, they will be rotated and your exported cookies will be invalidated

see [workarounds here](https://github.com/yt-dlp/yt-dlp/issues/8227#issuecomment-1867184804)

**Comment by pato-pan** [comment]
> seems like you're experiencing #8227
> 
> youtube rapidly rotates your cookies, so if you continue to use the session in your browser that you exported the cookies from, they will be rotated and your exported cookies will be invalidated
> 
> see [workarounds here](https://github.com/yt-dlp/yt-dlp/issues/8227#issuecomment-1867184804)

I agree that's likely the case. I will close this issue and reopen if there's an update.
