### ISSUE TITLE
Why does yt-dlp start bwrap?

### ISSUE THREAD

**Issue by super22n** [yt-dlp/yt-dlp#11109]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Whenever I download a video, and after it's downloaded, as I understand it, yt-dlp is using **ffmpeg** to rearrange the file. 
While it's still processing, I run: 

`ps aux | grep -i [f]fmpeg`

and I see in the output that it's running **bwrap** with some arguments, for example: 

`bwrap --ro-bind /usr /usr --ro-bind /etc/ld.so.cache /etc/ld.so.cache --symlink`

My question is: is this normal, and if so, how does yt-dlp use bwrap?

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by Grub4K** [comment]
We don't use bubblewrap in our code or distributions explicitly. Probably you installed ffmpeg or some other programs through flatpak, but hard to tell without you giving more information.

If you need more info you need to provide a verbose log, as well as how you installed all used dependencies.

**Comment by super22n** [comment]
I installed **ffmpeg** with apt. And **yt-dlp** I installed with pip3.  Here's a log from **yt-dlp** while downloading:

`>yt-dlp --verbose https://www.somesite/watch/somevideo

[debug] Command-line config: ['--verbose', 'https://www.somesite/watch/somevideo']
Deprecated Feature: Support for Python version 3.7 has been deprecated. See  https://github.com/yt-dlp/yt-dlp/issues/7803  for details.
                    You may stop receiving updates on this version at any time! Please update to Python 3.8 or above
[debug] yt-dlp version stable@2023.11.16 from yt-dlp/yt-dlp (pip)
[debug] Python 3.7 (CPython x86_64 64bit) - Linux-.... (OpenSSL 1., glibc ...)
[debug] exe versions: ffmpeg, ffprobe, 
[debug] Optional libraries: Cryptodome-., brotli-1., certifi-2021., mutagen-, requests-, secretstorage-,
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Loaded 1901 extractors
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] Testing format 625
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 221
[download] Destination: /tmp/tmp1u4aq23x.tmp
[download] 100% of    712.00B in 00:00:00 at 22.58KiB/s
[info] 123456abcdef: Downloading 1 format(s): 625+140
[debug] Invoking hlsnative downloader on "https://long.website.name/dir/path/index.m3u8"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:my video file [123456abcdef].abc.mp4' -i 'file:my video file [123456abcdef].fvv.m4a' -c copy -map 0:v:0 -map 1:a:0 -movflags +faststart 'file:my video file [123456abcdef].temp.mp4'`

**Comment by bashonly** [comment]
python 3.7 is no longer supported and you are using a severely outdated version of yt-dlp. Closing as invalid, don't strip info from your log if you want help
