### ISSUE TITLE
Youtube Channel profile picture download feature request. (--profile-picture)

### ISSUE THREAD

**Issue by angentanewbe** [yt-dlp/yt-dlp#1111]
- [x] I'm reporting a feature request
- [x] I've verified that I'm running yt-dlp version **2021.09.25**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description

Hi
I am requesting a feature to download the profile pictures of Youtube channels. Although I know a way to download by just changing some values out of the profile link maybe you can program it in the yt-dlp for automation.

first open up a youtube channel for eg https://www.youtube.com/channel/UCNeOeCvRK0pDv3kKZj6xUFQ

now right click on profile picture and view it (In Firefox browser)

now you get a link in the opened tab https://yt3.ggpht.com/ytc/AAUvwniM79AKFrUQMLOgCRRRhESud3DikoGd3tbuAwQi=s88-c-k-c0x00ffffff-no-rj

by changing the value s88 to s1024 we get the full view of the profile picture

here is the edited link https://yt3.ggpht.com/ytc/AAUvwniM79AKFrUQMLOgCRRRhESud3DikoGd3tbuAwQi=s1024-c-k-c0x00ffffff-no-rj

you can automate the process and add the feature to yt-dlp. Use --profile-picture as the argument to be used for the extraction of image through yt-dlp.

Important : I noticed that the yt-dlp write the profile picture if provided with channel link and --write-thumbnail command it download the profile picture along with thumbnails of a channel. you can somehow separate it for the profile picture only with --profile-picture argument. I used youtube-dl before and it does not download the profile picture with --write-thumbnail argument. This issue was originally raised by me on the youtube-dl github more info about the issue at the end.

Also some other suggestions for argument instead of --profile-picture
--user-picture
--picture
--profile-photo
--pp
--photo

Note : This feature request is copy of issue of youtube-dl  issue #28449.
link : https://github.com/ytdl-org/youtube-dl/issues/28449

**Comment by coletdjnz** [comment]
>  I noticed that the yt-dlp write the profile picture if provided with channel link and --write-thumbnail command it download the profile picture along with thumbnails of a channel

In the latest release you can download the profile picture of a channel only by using `--write-thumbnail --playlist-items 0`

I'll let @pukkandan look into the suggestions, I'm not so sure myself.

----
Some related upstream PRs for the sake of linking them: https://github.com/ytdl-org/youtube-dl/pull/28860, https://github.com/ytdl-org/youtube-dl/pull/28872

**Comment by angentanewbe** [comment]
> 
> 
> > I noticed that the yt-dlp write the profile picture if provided with channel link and --write-thumbnail command it download the profile picture along with thumbnails of a channel
> 
> In the latest release you can download the profile picture of a channel only by using `--write-thumbnail --playlist-items 0`
> 
> I'll let @pukkandan look into the suggestions, I'm not so sure myself.
> 
> Some related upstream PRs for the sake of linking them: [ytdl-org/youtube-dl#28860](https://github.com/ytdl-org/youtube-dl/pull/28860), [ytdl-org/youtube-dl#28872](https://github.com/ytdl-org/youtube-dl/pull/28872)

I know and I have mentioned this in my post. I am requesting to make the argument --profile-picture do the task of downloading the profile picture. It will help people configure to download profile picture without using --write-thumbnail argument. This will help people avoid downloading the thumbnails of videos as per their requirements.

**Comment by pukkandan** [comment]
As coletdjnz already mentioned, you can do this with `--write-thumbnail --playlist-items 0`. I don't understand what is the point of adding yet another switch to do the same thing

**Comment by angentanewbe** [comment]
> 
> 
> As coletdjnz already mentioned, you can do this with `--write-thumbnail --playlist-items 0`. I don't understand what is the point of adding yet another switch to do the same thing

because I dont want to download the thumbnails of videos just the profile picture along with the videos.

**Comment by yebamed** [comment]
> 
> 
> As coletdjnz already mentioned, you can do this with `--write-thumbnail --playlist-items 0`. I don't understand what is the point of adding yet another switch to do the same thing

Hi pukkandan, in my case it's for having more flexibility in where to download the profile picture along with the thumbnails. When using

`--write-thumbnail -o "thumbnail:R:\Youtube\%(channel)s\thumbnails\%(title)s.%(ext)s"`

to download an entire channel it correctly downloads all thumbnails of every video in the folder "thumbnails", but also downloads the profile picture in the parent folder with the channel's name

By having `--profile-picture` I would do something like this 

`--profile-picture -o "profile_picture:R:\Youtube\%(channel)s\profile picture\%(channel)s.%(ext)s"`

along with downloading the thumbnails the standard way

**Comment by pukkandan** [comment]
there is a separate key `pl_thumbnail` for setting the playlist thumbnail's `-o`

**Comment by pukkandan** [comment]
> because I dont want to download the thumbnails of videos just the profile picture along with the videos.

I can think of a different way to allow this, which should also solve #760

**Comment by pukkandan** [comment]
> because I dont want to download the thumbnails of videos just the profile picture along with the videos.

With https://github.com/yt-dlp/yt-dlp/commit/80c03fa98fdd54410bd36684ef453f6976a9c0bf, you can now pass an empty output template to not download that type of file. So if you just want the playlist thumbnail but not the video thumbnail, you can do `--write-thumbnail -o "thumbnail:"`
