### ISSUE TITLE
Feature request : Add a normalize option to normalize the audio through the ffmpeg-normalize python tool

### ISSUE THREAD

**Issue by sebma** [yt-dlp/yt-dlp#11118]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Hi, there is a python CLI tool called `ffmpeg-normalize` which can be easily installed through a `sudo pip3 install ffmpeg-normalize` than copies the video streams by default but normalizes the audio : https://github.com/slhck/ffmpeg-normalize

Here are example usage of this tool : https://github.com/slhck/ffmpeg-normalize/wiki/examples

Can you please implement a `--normalize-audio` (or `--normalize`) option that passes the downloaded file to `ffmpeg-normalize` for example like this : `ffmpeg-normalize $downloadedVideo` ?

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
you could just add `--exec "ffmpeg-normalize %(filepath)q -o %(filepath)q` to your command

**Comment by bashonly** [comment]
closing as out-of-scope; there's already a simple way to achieve this
