### ISSUE TITLE
[Patreon] Locked videos not downloading above 720p quality

### ISSUE THREAD

**Issue by 3my** [yt-dlp/yt-dlp#11125]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

USA

### Provide a description that is worded well enough to be understood

Public embedded videos download at proper 1080p ([example here](https://www.patreon.com/posts/mini-moni-da-110311558)), but videos locked behind a tier (even a free one [such as this](https://www.patreon.com/posts/meq8-max-for-for-111459779)) do not download above 720p, I'm using the latest nightly on Windows 10, ffmpeg installed.
I have tried using other programs such as Video DownloadHelper and they download them just fine at their normal 1080p quality

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--cookies-from-browser', 'firefox', 'https://www.patreon.com/posts/meq8-max-for-for-111459779']
[debug] Encodings: locale cp932, fs utf-8, pref cp932, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.09.27 from yt-dlp/yt-dlp [c6387abc1] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 2024-09-26-git-f43916e217-essentials_build-www.gyan.dev (setts), ffprobe 2024-09-26-git-f43916e217-essentials_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.08.30, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.3, websockets-13.1
[debug] Proxy map: {}
Extracting cookies from firefox
[debug] Extracting cookies from: "C:\Users\User\AppData\Roaming\Mozilla\Firefox\Profiles\ve8tsts6.default-release\cookies.sqlite"
Extracted 1371 cookies from firefox
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1838 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.09.27 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.09.27 from yt-dlp/yt-dlp)
[Patreon] Extracting URL: https://www.patreon.com/posts/meq8-max-for-for-111459779
[Patreon] 111459779: Downloading API JSON
[Patreon] 111459779: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 111459779: Downloading 1 format(s): 1877
[debug] Invoking hlsnative downloader on "https://manifest-gcp-us-east4-vop1.cfcdn.mux.com/Rd7wS29MmpwUdvSklrWy48Af5s02Rg7JDgy54UYRm2fzKd02pxXxs8e2SokxGpsKGKCCB9ECkJpCn5nxqBFXUQsEX9Vc00lmbwk/rendition.m3u8?cdn=fastly&expires=1727701200&rid=FQQ1DVFKgSdKJJqPMX5OVAvM02v2fOoVYyRucWXFRUTw&skid=default&signature=NjZmYWEwZDBfYzI2N2UxYjY5NjcwZGZjYTQ2OTU1NGY0ODdiYjBjZGExYjE0ZGUzMzNjNWVhNjU0ZmZkMjRmYzdmZWI5N2RlMw=="
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 56
[download] Destination: MEQ8 - Max for Live Modulator for EQ8 [111459779].mp4
[debug] File locking is not supported. Proceeding without locking
[download] 100% of   18.40MiB in 00:00:05 at 3.51MiB/s
[debug] ffprobe command line: ffprobe -hide_banner -show_format -show_streams -print_format json "file:MEQ8 - Max for Live Modulator for EQ8 [111459779].mp4"
[debug] ffmpeg command line: ffprobe -show_streams "file:MEQ8 - Max for Live Modulator for EQ8 [111459779].mp4"
[FixupM3u8] Fixing MPEG-TS in MP4 container of "MEQ8 - Max for Live Modulator for EQ8 [111459779].mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i "file:MEQ8 - Max for Live Modulator for EQ8 [111459779].mp4" -map 0 -dn -ignore_unknown -c copy -f mp4 -bsf:a aac_adtstoasc -movflags +faststart "file:MEQ8 - Max for Live Modulator for EQ8 [111459779].temp.mp4"
```

**Comment by bashonly** [comment]
If you're willing to share your account credentials (privately), I could take a look into this.

You can contact me via:
discord: `bashonly`
or
email: `bashonly [ a t ] proton mail ( d o t ) com`
