### ISSUE TITLE
New Sites

### ISSUE THREAD

**Issue by al12345-dot** [yt-dlp/yt-dlp#11126]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [x] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [x] I'm requesting a feature unrelated to a specific site
- [x] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [ ] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [ ] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [x] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

add new sites, MediaDownloader supports many more sites

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by seproDev** [comment]
MediaDownlaoder uses yt-dlp (among optionally others) as their backend. If you have a request for a specific site, you can open it. Blanket statements like "support more sites" are not helpful.

**Comment by al12345-dot** [comment]
ok
