### ISSUE TITLE
[Site Request] wetv.vip

### ISSUE THREAD

**Issue by Sparh4wk** [yt-dlp/yt-dlp#1115]
- [x] I'm reporting a new site support request
- [x] I've verified that I'm running yt-dlp version **2021.09.25**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that none of provided URLs violate any copyrights
- [x] The provided URLs do not contain any DRM to the best of my knowledge
- [x] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

- Single video: https://wetv.vip/play/air11ooo2rdsdi3-Cute-Programmer/v0040pr89t9-EP1-Cute-Programmer
- Single video: https://wetv.vip/play/bi3mcnv6qg0os9k-Manner-of-Death/b0035046n4p-EP1-Manner-of-Death
- Playlist: https://wetv.vip/play/air11ooo2rdsdi3-Cute-Programmer

## Description

Website with a lot of dramas and "anime" shows and movies. As mgtv they have a lot of original content.

**Comment by zackmark29** [comment]
There's already a PR for that last year
https://github.com/ytdl-org/youtube-dl/pull/26809

Ah you also the one who requested
https://github.com/ytdl-org/youtube-dl/issues/22040

**Comment by Sparh4wk** [comment]
> @Tithen-Firion wrote a PR for that, last year. https://github.com/Tithen-Firion [ytdl-org/youtube-dl#26809](https://github.com/ytdl-org/youtube-dl/pull/26809)
> 
> Ah you also the one who requested [ytdl-org/youtube-dl#22040](https://github.com/ytdl-org/youtube-dl/issues/22040)

oh sry, I totally forgot about it.. its been a year :( and for some reason search didnt find me anything here.

**Comment by pukkandan** [comment]
It is a bit too complex for me to easily port it over myself. Perhaps @Tithen-Firion would be willing to port it themselves?

**Comment by zackmark29** [comment]
> > @Tithen-Firion wrote a PR for that, last year. https://github.com/Tithen-Firion [ytdl-org/youtube-dl#26809](https://github.com/ytdl-org/youtube-dl/pull/26809)
> > Ah you also the one who requested [ytdl-org/youtube-dl#22040](https://github.com/ytdl-org/youtube-dl/issues/22040)
> 
> oh sry, I totally forgot about it.. its been a year :( and for some reason search didnt find me anything here.
> 
> edit: oh its on old repo.. sry I didnt check it.. but seems like that PR is probably dead anyway

The ckey algo still works (which I've been using also) that's just the very important.
Maybe the api are already outdated and just needed a little modification.

**Comment by nao20010128nao** [comment]
Tithen-Firion seems to be inactive, so ytdl-org/youtube-dl#26809 should be ported by another user

**Comment by zackmark29** [comment]
> Tithen-Firion seems to be inactive, so [ytdl-org/youtube-dl#26809](https://github.com/ytdl-org/youtube-dl/pull/26809) should be ported by another user

![image](https://user-images.githubusercontent.com/62680932/135242470-71233288-2bc4-4c3a-9d23-bbb67ef6a369.png)

**Comment by Tithen-Firion** [comment]
Not familiar with this project, not interested with porting. BTW, porting? I thought this was a youtube-dl fork. Are extractors not compatible with each other?

As for the wetv - like I said in the original PR, most of the `CKey` code is just AES-CBC encryption so you can simplify it greatly.

But there's one issue. Downloading with youtube-dl was painfully slow. That's because no matter which downloader I used (native or ffmpeg) it was downloading one chunk at a time. And I think wetv is throttling the download speed. So I gave up on that. Instead I grabbed the `.m3u8` playlist from wetv website and downloaded with some M3U8 downloader (don't remember which one but it let you download multiple chunks at once).

So unless this fork is modified to download multiple chunks at once it will be a pretty bad experience.

**Comment by nyuszika7h** [comment]
> So unless this fork is modified to download multiple chunks at once it will be a pretty bad experience.

I think it already does that, via `-N` or `--downloader aria2c`.

**Comment by pukkandan** [comment]
>  porting? I thought this was a youtube-dl fork. Are extractors not compatible with each other?

ok, porting may not be the right word. The extractors are mostly compatible. But more importantly, it is helpful for the original author to copy the PR and address reviews. If not, I can only make any changes based on how much I understand without any feedback on what the intend of some of the code may be

> As for the wetv - like I said in the original PR, most of the CKey code is just AES-CBC encryption so you can simplify it greatly.

This is one example of the same. I havent yet looked at how complex the CKey code is, but I (or whoever "ports" it) will need to go through and thoroughly understand the entire thing to decide which parts can be replaced by the existing CBC decryptor

> So unless this fork is modified to download multiple chunks at once it will be a pretty bad experience.

Yes, we have the ability to download fragments in parallel

> Not familiar with this project, not interested with porting. 

That's fine. Just pinged you in case you were interested. Thanks for replying anyway

**Comment by Sparh4wk** [comment]
so it seems there is no hope for this site to be supported? :(
