### ISSUE TITLE
What in the hell happened?!

### ISSUE THREAD

**Issue by HeerWither** [yt-dlp/yt-dlp#11169]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United Kingdom

### Provide a description that is worded well enough to be understood

Downloading:
Title: THE AMAZING DIGITAL CIRCUS - Ep 3: The Mystery Of Mildenhall Manor
URL: https://www.youtube.com/watch?v=bKjfw77cxeQ
Type: video
Command: 
 -N "3" --trim-filenames "184" --no-mtime --sponsorblock-remove "music_offtopic" --extractor-args "youtube:player_client=default,mediaconnect" --sponsorblock-mark "all" --embed-chapters -f "bv+ba/b" --embed-subs --sub-format "srt/best" --convert-subtitles "srt" --sub-langs "en.*,.*-orig" -P "/storage/emulated/0/Android/data/com.deniscerri.ytdl/files/downloads/1" -o "%(uploader).30B - %(title).170B.%(ext)s" --replace-in-metadata "title" ".+" "THE AMAZING DIGITAL CIRCUS - Ep 3: The Mystery Of Mildenhall Manor" --parse-metadata "%(title)s:%(meta_title)s" --replace-in-metadata "uploader" ".+" "GLITCH" --parse-metadata "%(uploader)s:%(artist)s" --parse-metadata "%(uploader,channel,creator,artist|null)s:^(?P<uploader>.*?)(?:(?= - Topic)|$)" "https://www.youtube.com/watch?v=bKjfw77cxeQ" 

WARNING: [youtube] Skipping unsupported client mediaconnect
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (1/3)...
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (2/3)...
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (3/3)...
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] Unable to download API page: HTTP Error 400: Bad Request (caused by <HTTPError 400: 'Bad Request'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [youtube] bKjfw77cxeQ: nsig extraction failed: You may experience throttling for some formats
         n = cn5zjT_q29ob0y1QAK ; player = https://www.youtube.com/s/player/96d06116/player_ias.vflset/en_US/base.js
WARNING: [youtube] bKjfw77cxeQ: nsig extraction failed: You may experience throttling for some formats
         n = ZXhLA3PIDaJzlYCBBI ; player = https://www.youtube.com/s/player/96d06116/player_ias.vflset/en_US/base.js
WARNING: Unable to communicate with SponsorBlock API: <urlopen error [Errno 7] No address associated with hostname>. Retrying (1/3)...
WARNING: Unable to communicate with SponsorBlock API: <urlopen error [Errno 7] No address associated with hostname>. Retrying (2/3)...
WARNING: Unable to communicate with SponsorBlock API: <urlopen error [Errno 7] No address associated with hostname>. Retrying (3/3)...
ERROR: Preprocessing: Unable to communicate with SponsorBlock API: <urlopen error [Errno 7] No address associated with hostname>
WARNING: The download speed shown is only of one thread. This is a known issue
ERROR: 
[download] Got error: HTTP Error 403: Forbidden. Giving up after 10 retries
ERROR: fragment 1 not found, unable to continue
WARNING: The download speed shown is only of one thread. This is a known issue
ERROR: 
[download] Got error: HTTP Error 403: Forbidden. Giving up after 10 retries
ERROR: fragment 1 not found, unable to continue
ERROR: Preprocessing: Unable to communicate with SponsorBlock API: <urlopen error [Errno 7] No address associated with hostname>

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
Downloading:
Title: THE AMAZING DIGITAL CIRCUS - Ep 3: The Mystery Of Mildenhall Manor
URL: https://www.youtube.com/watch?v=bKjfw77cxeQ
Type: video
Command: 
 -N "3" --trim-filenames "184" --no-mtime --sponsorblock-remove "music_offtopic" --extractor-args "youtube:player_client=default,mediaconnect" --sponsorblock-mark "all" --embed-chapters -f "bv+ba/b" --embed-subs --sub-format "srt/best" --convert-subtitles "srt" --sub-langs "en.*,.*-orig" -P "/storage/emulated/0/Android/data/com.deniscerri.ytdl/files/downloads/1" -o "%(uploader).30B - %(title).170B.%(ext)s" --replace-in-metadata "title" ".+" "THE AMAZING DIGITAL CIRCUS - Ep 3: The Mystery Of Mildenhall Manor" --parse-metadata "%(title)s:%(meta_title)s" --replace-in-metadata "uploader" ".+" "GLITCH" --parse-metadata "%(uploader)s:%(artist)s" --parse-metadata "%(uploader,channel,creator,artist|null)s:^(?P<uploader>.*?)(?:(?= - Topic)|$)" "https://www.youtube.com/watch?v=bKjfw77cxeQ" 

WARNING: [youtube] Skipping unsupported client mediaconnect
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (1/3)...
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (2/3)...
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (3/3)...
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] Unable to download API page: HTTP Error 400: Bad Request (caused by <HTTPError 400: 'Bad Request'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [youtube] bKjfw77cxeQ: nsig extraction failed: You may experience throttling for some formats
         n = cn5zjT_q29ob0y1QAK ; player = https://www.youtube.com/s/player/96d06116/player_ias.vflset/en_US/base.js
WARNING: [youtube] bKjfw77cxeQ: nsig extraction failed: You may experience throttling for some formats
         n = ZXhLA3PIDaJzlYCBBI ; player = https://www.youtube.com/s/player/96d06116/player_ias.vflset/en_US/base.js
WARNING: Unable to communicate with SponsorBlock API: <urlopen error [Errno 7] No address associated with hostname>. Retrying (1/3)...
WARNING: Unable to communicate with SponsorBlock API: <urlopen error [Errno 7] No address associated with hostname>. Retrying (2/3)...
WARNING: Unable to communicate with SponsorBlock API: <urlopen error [Errno 7] No address associated with hostname>. Retrying (3/3)...
ERROR: Preprocessing: Unable to communicate with SponsorBlock API: <urlopen error [Errno 7] No address associated with hostname>
WARNING: The download speed shown is only of one thread. This is a known issue
ERROR: 
[download] Got error: HTTP Error 403: Forbidden. Giving up after 10 retries
ERROR: fragment 1 not found, unable to continue
WARNING: The download speed shown is only of one thread. This is a known issue
ERROR: 
[download] Got error: HTTP Error 403: Forbidden. Giving up after 10 retries
ERROR: fragment 1 not found, unable to continue
ERROR: Preprocessing: Unable to communicate with SponsorBlock API: <urlopen error [Errno 7] No address associated with hostname>
```

**Comment by Grub4K** [comment]
You are using an outdated version of `yt-dlp`; update! Also seems as if you are offline, or have some internet trouble.

Also this is not a verbose log, you have to support `--verbose` and paste the WHOLE output.
