### ISSUE TITLE
Different types of 'item' (mostly cosmetical)

### ISSUE THREAD

**Issue by HalvorRaknes** [yt-dlp/yt-dlp#11161]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

On YouTube there are different classes of videos on each channel: Videos, Live and Shorts. When downloading a time interval of videos `yt-dlp` goes through every video classed as 'Video', then all classed as 'Live' and finally all 'Shorts'.

When `yt-dlp` is finished with the 'Video' playlist and is ready to move on to 'Live' playlist it informs of this with this message:

`[download] Downloading item 2 of 3`

 and then it goes on to download the shorts with this message:

`[download] Downloading item 1 of 6`

This is a little bit confusing since both the three classes of default playlists and each video within each class are labeled 'item' and the informing message about process progression is identical.

There is contextual surrounding lines of information that makes the distinction clear enough, but perhaps the phrasing of the two different progression messages could be disambiguated also?

It would be neater.

(I didn't repeat this with the -vU flag added when I noticed this, my apology, but I believe it wouldn't add anything substantial to this issue)

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[download] 2019-11-13 upload date is not in range 2022-11-01 to 2022-11-10
[download] Downloading item 135 of 135
[youtube] Extracting URL: https://www.youtube.com/watch?v=-UlC8OSoDgk
[youtube] -UlC8OSoDgk: Downloading webpage
[youtube] -UlC8OSoDgk: Downloading ios player API JSON
[youtube] -UlC8OSoDgk: Downloading web creator player API JSON
[youtube] -UlC8OSoDgk: Downloading m3u8 information
[download] 2019-10-14 upload date is not in range 2022-11-01 to 2022-11-10
[download] Finished downloading playlist: The Grayzone - Live
[download] Downloading item 3 of 3
[download] Downloading playlist: The Grayzone - Shorts
[youtube:tab] Playlist The Grayzone - Shorts: Downloading 6 items of 6
[download] Downloading item 1 of 6
```

**Comment by bashonly** [comment]
Playlists can be nested inside playlists which can be nested inside playlists, and so forth. Core code doesn't know in advance which items in a playlist will be playlists and which will be videos until it finishes extracting them. "Item" is actually an improvement over what the output was previously: bc5c2f8a2c84633940956a27bf2125804f73882e

**Comment by HalvorRaknes** [comment]
I understand.
