### ISSUE TITLE
[YouTube] Format `251` is sometimes unavailable due to `web_creator` request failing intermittently

### ISSUE THREAD

**Issue by mwoehlke** [yt-dlp/yt-dlp#11165]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

USA

### Provide a description that is worded well enough to be understood

I'm not sure if this is an *actual* bug, or YouTube being YouTube, but I'm having a lot of issues with yt-dlp not downloading the requested format, i.e. downloading a `.m4a` despite `--prefer-free-formats` being specified, and despite Opus being available.

This typically manifests while downloading playlists; some will result in a `.webm`, while some will result in a `.m4a`. I have a wrapper that I can invoke on `*.m4a` to redownload those videos, which will often obtain `.webm`s for *some*, but not all of the videos that didn't download as `.webm` the first time. It often takes three attempts to get everything to download as `.webm`.

(Strictly speaking, I haven't tested this in a browser, but I doubt that would be informative, since yt-dlp *is* able to download the right thing, it just takes several tries. Besides, I don't know how to know or control what format a browser uses, anyway.)

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--embed-chapters', '--prefer-free-formats', '-f', 'bestaudio', '-o', "01 - The Church's One Foundation [tWv15vdMmqc].%(ext)s", '--', 'tWv15vdMmqc']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version master@2024.10.01.001408 from yt-dlp/yt-dlp-master-builds [e59c82a74] (zip)
[debug] Python 3.10.11 (CPython x86_64 64bit) - Linux-6.2.15-100.fc36.x86_64-x86_64-with-glibc2.35 (OpenSSL 3.0.8 7 Feb 2023, glibc 2.35)
[debug] exe versions: ffmpeg 5.0.3 (setts), ffprobe 5.0.3
[debug] Optional libraries: requests-2.27.1, sqlite3-3.36.0, urllib3-1.26.12
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Loaded 1838 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-master-builds/releases/latest
Latest version: master@2024.10.01.001408 from yt-dlp/yt-dlp-master-builds
yt-dlp is up to date (master@2024.10.01.001408 from yt-dlp/yt-dlp-master-builds)
[youtube] Extracting URL: tWv15vdMmqc
[youtube] tWv15vdMmqc: Downloading webpage
[youtube] tWv15vdMmqc: Downloading ios player API JSON
[youtube] tWv15vdMmqc: Downloading web creator player API JSON
[youtube] tWv15vdMmqc: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[info] tWv15vdMmqc: Downloading 1 format(s): 140
[debug] Invoking http downloader on "https://rr2---sn-ab5l6nr6.googlevideo.com/videoplayback?expire=1728097209&ei=WVcAZ9jMBaa1kucPv8euoA4&ip=2603%3A7081%3A3f04%3Aefce%3A3f4e%3A2ab2%3A8bd3%3A7222&id=o-ACN7GaO8wAc-Nh4RH30bazDaGmruIWqmbXZhm0SlnuQz&itag=140&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=M-&mm=31%2C29&mn=sn-ab5l6nr6%2Csn-ab5sznzl&ms=au%2Crdu&mv=m&mvi=2&pl=36&gcr=us&initcwndbps=1166250&vprv=1&svpuc=1&mime=audio%2Fmp4&rqh=1&gir=yes&clen=5482344&dur=338.546&lmt=1603303299786991&mt=1728075414&fvip=2&keepalive=yes&fexp=51300761&c=IOS&txp=2311222&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cgcr%2Cvprv%2Csvpuc%2Cmime%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRQIgXzJ5xwG7tFOqfndkzu3w-vE2yXtiRFpIlD70Out8hGoCIQCf8v4nn9mI1neEAP2qj3pBtPxUSTmM79tLKDig4Puz8A%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=ACJ0pHgwRQIgGRUi7-LhIavU74m-Oll_cD2Rl3YPdOza3cJkQ5skAtwCIQDPsK__g9xZPjkTY2EM0wW4B04U2o24sB50kHmqBltGmw%3D%3D"
[download] 01 - The Church's One Foundation [tWv15vdMmqc].m4a has already been downloaded
[download] 100% of    5.22MiB
[Metadata] There isn't any metadata to add
```

**Comment by bashonly** [comment]
I can't reproduce the issue. Using the same command-line config, format 251 is selected for me.

Can you try to reproduce the issue with these options and share the log?
```
--ignore-config -vF --no-simulate --prefer-free-formats -f ba
```

**Comment by mwoehlke** [comment]
Yeah, it doesn't seem consistent, and I wouldn't count on any specific video being able to reliably reproduce. It seems very likely to happen when downloading several (or especially a few dozen) videos in batch, though.

I wasn't sure if it was format selection being wonky, or on YouTube's side. It sounds like you're pretty sure it's the latter, in which case I'll understand if there's not much yt-dlp can do about it... Still worth reporting IMHO, but mostly I was hoping for help ruling out an issue on yt-dlp's end.

**Comment by bashonly** [comment]
see https://github.com/yt-dlp/yt-dlp/issues/11154#issuecomment-2398092084
