### ISSUE TITLE
How to embed synopsis and description in meta comment?

### ISSUE THREAD

**Issue by zohozer** [yt-dlp/yt-dlp#11168]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Hi all.

I do need to embed both the URL of the downloaded video and his description into the file Comment description field and I tried a few versions of the following command but unfortunately I can't make the yt-dlp to embed both field. It is always embedding one or the other field.

`--parse-metadata 'synopsis:%(webpage_url)s + description:(?s)(?P<meta_comment>.+)' --add-metadata`
`--parse-metadata 'synopsis:%(webpage_url)s description:(?s)(?P<meta_comment>.+)' --add-metadata`
`--parse-metadata 'synopsis:%(webpage_url)s' + 'description:(?s)(?P<meta_comment>.+)' --add-metadata`

What is the correct syntax to embed both the synopsis and description into the same Comment field?

Best regards.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
```
--parse-metadata "%(webpage_url)s %(description)s:%(meta_comment)s" --embed-metadata
```

**Comment by zohozer** [comment]
> ```
> --parse-metadata "%(webpage_url)s %(description)s:(?s)(?P<meta_comment>.+)" --embed-metadata
> ```

Thank you. It is working. It is possible to also insert an empty line between `webpage_url` and `meta_comment`?

Like:

```
webpage_url

meta_comment
```

**Comment by bashonly** [comment]
you'd have to put an actual newline in the quoted argument, e.g.:

```
--parse-metadata "%(webpage_url)s

%(description)s:(?s)(?P<meta_comment>.+)" --embed-metadata
```
not sure if that will work in your shell. if not, you can add it to your config file (or [create one if you don't have one already](https://github.com/yt-dlp/yt-dlp#configuration))
