### ISSUE TITLE
ERROR: [tubitv] ...: This video is DRM protected

### ISSUE THREAD

**Issue by antdude** [yt-dlp/yt-dlp#11170]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

USA

### Provide a description that is worded well enough to be understood

No longer can download videos from Tubi's web site.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
$ ~/bin/yt-dlpMasterBuild -v -U  --embed-subs --sub-langs en https://tubitv.com/movies/679215/the-three-stooges-meet-hercules

[debug] Command-line config: ['-v', '-U', '--embed-subs', '--sub-langs', 'en', 'https://tubitv.com/movies/679215/the-three-stooges-meet-hercules']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version master@2024.10.01.001408 from yt-dlp/yt-dlp-master-builds [e59c82a74] (zip)
[debug] Python 3.11.2 (CPython x86_64 64bit) - Linux-6.1.0-26-amd64-x86_64-with-glibc2.36 (OpenSSL 3.0.14 4 Jun 2024, glibc 2.36)
[debug] exe versions: ffmpeg 5.1.6-0 (setts), ffprobe 5.1.6-0
[debug] Optional libraries: brotli-1.0.9, certifi-2022.09.24, pyxattr-0.8.1, requests-2.28.1, sqlite3-3.40.1, urllib3-1.26.12
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Loaded 1838 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-master-builds/releases/latest
Latest version: master@2024.10.01.001408 from yt-dlp/yt-dlp-master-builds
yt-dlp is up to date (master@2024.10.01.001408 from yt-dlp/yt-dlp-master-builds)
[tubitv] Extracting URL: https://tubitv.com/movies/679215/the-three-stooges-meet-hercules
[tubitv] 679215: Downloading webpage
ERROR: [tubitv] 679215: This video is DRM protected
  File "/home/ant/bin/yt-dlpMasterBuild/yt_dlp/extractor/common.py", line 741, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ant/bin/yt-dlpMasterBuild/yt_dlp/extractor/tubitv.py", line 119, in _real_extract
    self.report_drm(video_id)
  File "/home/ant/bin/yt-dlpMasterBuild/yt_dlp/extractor/common.py", line 1231, in report_drm
    self.raise_no_formats('This video is DRM protected', expected=True, video_id=video_id)
  File "/home/ant/bin/yt-dlpMasterBuild/yt_dlp/extractor/common.py", line 1275, in raise_no_formats
    raise ExtractorError(msg, expected=expected, video_id=video_id)
```

**Comment by seproDev** [comment]
Can you play the video in your browser with DRM disabled?
If not, there is nothing that can be done. yt-dlp cannot download DRM protected content.

**Comment by antdude** [comment]
Nope in my updated SeaMonkey v2.53.19 web browser: "Content requires DRM
Sorry, this video requires DRM. You can troubleshoot DRM issues using this [link](https://tubitv.com/help-center/Setup-and-Troubleshooting/articles/4410077357467)." :(

I wonder when Tubi added DRM to its videos. IIRC, it was fine last month.

**Comment by dirkf** [comment]
Test videos are failing, but differently (401). This could be the site's way of saying "expired".

The problem video page says "content unavailable" for me, above the title, but that might be geo-blocking.

https://tubitv.com/tv-shows/200141623/s01-e01-episode-1 is a non-DRM link, working here but not upstream (401).

**Comment by october262** [comment]
this title (Ben-Hur) still works with yt-dlp - https://tubitv.com/movies/100028628/ben-hur

**Comment by dirkf** [comment]
Yet:
```console
$ ~/Downloads/yt-dlp -vF 'https://tubitv.com/movies/100028628/ben-hur' --geo-bypass-country=US
[debug] Command-line config: ['-vF', 'https://tubitv.com/movies/100028628/ben-hur', '--geo-bypass-country=US']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.09.27 from yt-dlp/yt-dlp [c6387abc1] (zip)
[debug] Python 3.11.2 (CPython i686 32bit) - Linux-6.1.0-25-686-pae-i686-with-glibc2.36 (OpenSSL 3.0.14 4 Jun 2024, glibc 2.36)
[debug] exe versions: ffmpeg 5.1.6-0 (setts), ffprobe 5.1.6-0
[debug] Optional libraries: certifi-2022.09.24, requests-2.28.1, sqlite3-3.40.1, urllib3-1.26.12
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Loaded 1838 extractors
[debug] Using fake IP 6.203.210.112 (US) as X-Forwarded-For
[tubitv] Extracting URL: https://tubitv.com/movies/100028628/ben-hur
[tubitv] 100028628: Downloading webpage
ERROR: [tubitv] 100028628: This content is currently unavailable
  File "/home/df/Downloads/yt-dlp/yt_dlp/extractor/common.py", line 741, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/df/Downloads/yt-dlp/yt_dlp/extractor/tubitv.py", line 121, in _real_extract
    raise ExtractorError('This content is currently unavailable', expected=True)

$
```
(same w/o `--geo-bypass-country`; same w/back-ported upstream code)

But the Shameless episode linked above is OK, except that the title extracted from JSON doesn't contain the name of the series, so it's just `S01:E01 - Episode 1`: a better title is in the ld+json block.

Also, the `Saddle Club` series used in the playlist extractor tests is not available: the playlist extractor should check for `'policy_match': False` and the tests should use (eg) Bob Ross seasons instead.

**Comment by bashonly** [comment]
I don't think xff is effective with tubi; from a genuine US IP I can extract that URL

**Comment by dirkf** [comment]
It seems that `'policy_match': False` indicates geo-restriction among other unavailability reasons.

Indeed XFF doesn't appear to have any effect with the current site.

From the UK the Bob Ross and Shameless shows (expiry in 2026) are available.

Not entirely on topic for this particular issue but perhaps of interest, I only get 373 episodes of the former. The site offers seasons/series 2-31 and each should have 13 episodes, making 390 altogether, but the `seasons` JSON served to me is missing 17 episodes:
* S22 lacks E7-9,11
* S23 lacks E1,4,6,8
* S29 lacks E6-13
* S31 lacks E13. 

This is actually reflected in the website, which seems to be using the same logic as the `tubitv:series` extractor (get the episode IDs from the `seasons` JSON, fetch the episode details for each).

Something similar must explain why the extractor test only wants 389 episodes.

However going to each season page in turn and extracting the episode items (`'type' == 'v'`) does yield the 390 expected shows.
##`tubitv:series` extractor test 0 results

<details><summary>yt-dlp master</summary>

```console
$ python3 test/test_download.py TestDownload.test_TubiTvShow
[debug] Loaded 1855 extractors
[tubitv:series] Extracting URL: https://tubitv.com/series/3936/the-joy-of-painting-with-bob-ross?start=true
[download] Downloading playlist: the-joy-of-painting-with-bob-ross
[tubitv:series] the-joy-of-painting-with-bob-ross: Downloading webpage
[tubitv:series] Playlist the-joy-of-painting-with-bob-ross: Downloading 373 items of 373
[debug] The information of all playlist entries will be held in memory
[download] Downloading item 1 of 373
[download] Downloading item 2 of 373
[download] Downloading item 3 of 373
...
[download] Downloading item 371 of 373
[download] Downloading item 372 of 373
[download] Downloading item 373 of 373
[download] Finished downloading playlist: the-joy-of-painting-with-bob-ross
F
======================================================================
FAIL: test_TubiTvShow (__main__.TestDownload):
----------------------------------------------------------------------
...
AssertionError: False is not true : Expected at least 389 in playlist https://tubitv.com/series/3936/the-joy-of-painting-with-bob-ross?start=true, but got only 373

----------------------------------------------------------------------
Ran 1 test in 3.787s

FAILED (failures=1)
$
```

</details>
... whereas ...
<details><summary><code>Upstream WIP</summary>

```console
$ python test/test_download.py TestDownload.test_TubiTvShow
[download] Downloading playlist: the-joy-of-painting-with-bob-ross
[tubitv:series] the-joy-of-painting-with-bob-ross: Downloading webpage
[tubitv:series] the-joy-of-painting-with-bob-ross-season-3: Downloading webpage
...
[tubitv:series] the-joy-of-painting-with-bob-ross-season-30: Downloading webpage
[tubitv:series] the-joy-of-painting-with-bob-ross-season-31: Downloading webpage
[tubitv:series] playlist the-joy-of-painting-with-bob-ross: Downloading 390 videos
[download] Downloading video 1 of 390
[download] Downloading video 2 of 390
[download] Downloading video 3 of 390
...
[download] Downloading video 380 of 390
[download] Downloading video 381 of 390
[download] Downloading video 382 of 390
[download] Downloading video 383 of 390
[download] Downloading video 384 of 390
[download] Downloading video 385 of 390
[download] Downloading video 386 of 390
[download] Downloading video 387 of 390
[download] Downloading video 388 of 390
[download] Downloading video 389 of 390
[download] Downloading video 390 of 390
[download] Finished downloading playlist: the-joy-of-painting-with-bob-ross
.
----------------------------------------------------------------------
Ran 1 test in 60.902s

OK
$
```

</details>
