### ISSUE TITLE
i don't understand how to install

### ISSUE THREAD

**Issue by Triramama** [yt-dlp/yt-dlp#11179]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

why is it so hard cant it work like normal progarms? i installed exe and this what it gave me
Usage: yt-dlp.exe [OPTIONS] URL [URL...]

yt-dlp.exe: error: Do not double-click the executable, instead call it from a command line.
Please read the README for further information on how to use yt-dlp: https://github.com/yt-dlp/yt-dlp#readme

man add ui to this things or something

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by grqz** [comment]
If you are entirely unfamiliar with command line, consider using one of the third party GUIs

__**GUIs**__ (Unofficial)
> * https://github.com/mhogomchungu/media-downloader
> * https://github.com/jely2002/youtube-dl-gui
> * https://github.com/oleksis/youtube-dl-gui
> * https://github.com/axcore/tartube
> * https://github.com/onionware-github/OnionMedia
> * https://github.com/sylviiu/ezytdl
> * Most other GUIs also technically support it as long as you manually replace their youtube-dl executable with the yt-dlp executable
>     * You can find a list of more youtube-dl GUIs here: https://reddit.com/r/youtubedl/wiki/info-guis

**Comment by TheSystemGuy1337** [comment]
YT-DLP is trivial to use. You are just using it wrong.

To download a video, run yt-dlp and insert the video URL after the program name.

Example: `yt-dlp https://www.youtube.com/watch?v=LfXBhs_0YiA`

Or you could just use a 3rd party GUI.
