### ISSUE TITLE
Optionally specify a temporary download location

### ISSUE THREAD

**Issue by dark-penguin** [yt-dlp/yt-dlp#11172]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Hi! Thanks for the awesome project. :heart: 

My current workflow:
- I download video+audio tracks into a temporary directory in tmpfs
- Then the two tracks are merged (which requires twice the space in tmpfs!)
- Then I move the video to the directory I want to store it in

There are multiple reasons to do this: to speed up the merging, especially considering possible fragmentation on the temporary files, and to avoid unnecessary SSD wear.

However, I don't always have twice the space in tmpfs. So, I would like to be able to specify the "temporary" directory to store incomplete files in, and only write the merge output into the "output" directory. I can see more use cases, e.g. using faster storage for the temporary files.

Example:
```
yt-dlp <url> --temp-dir /tmp/ -P ./
```
Behaviour:
- Two tracks are downloaded into `/tmp/`
  - By default, same as "output" directory (set with `-P` or current)
  - In case we're "continuing", they are also expected to be found in /tmp/`
  - In case we're only downloading one track, it should still be downloaded to the temporary directory until it's complete, then moved into the output directory
- During the "merge" phase, output is written into the "output" directory (set with `-P`), then temporary files are deleted from `/tmp/`

Is this maybe already possible? I went through `--help` and did some searches, but couldn't find a way to do it.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by grqz** [comment]
try `-P temp:/tmp/ -P home:./`

**Comment by dark-penguin** [comment]
Oh!! That works! Thank you! :heart:

**Comment by dark-penguin** [comment]
Actually, no, it doesn't. I haven't noticed that before, but after downloading the video and audio tracks, those two tracks get merged *in the `temp:` directory*, then copied to the `home:` directory. Why? Wouldn't it make more sense to output the merged file directly to `home:`?

**Comment by dark-penguin** [comment]
Oh... Seems like this happened because there was one more step: "adding metadata". Seems like there is no way to do all that in one step, e.g. by "piping" multiple operations together, and avoid copying the files over and over multiple times?

**Comment by Grub4K** [comment]
Each postprocessor step is independent of another and therefor cannot be orchestrated in a way you want. Ideally multiple postprocessors could be run simultaneously if they all use ffmpeg, or if they would pipe together, but the logic involving this is very complicated and probably can never be achieved in a complicated setting like this.

If you need to run multiple postprocessors you probably have to do so manually, either through a script or using a bit of wrapper python.

**Comment by dark-penguin** [comment]
All I'm doing is getting video, audio, subtitles and chapters into one file. So, I guess "multiple postprocessors" means that instead of combining them all in one go, tracks are combined one-by-one (I'm not sure if subtitles also require a separate step since there there were none in this particular video).

I'm just guessing, but those are probably just ffmpeg options - multiple tracks and probably some other option for chapters. I understand that flexibility creates complexity, so optimizing multiple postprocessors might really be near-impossible. But in this specific case (adding chapters at the same step as combining tracks), do you think it would still be too troublesome? (In terms of benefits, I would think that simply getting video+audio+subtitles+chapters is a pretty common scenario, so it's not some esoteric use case that will almost never be used.)

**Comment by Grub4K** [comment]
They were never designed that way in the first place. While certainly *possible*, I don't think it will be done in the near future

**Comment by bashonly** [comment]
Closing in favor of #126

**Comment by bashonly** [comment]
please continue discussion in #126 and/or #1879
