### ISSUE TITLE
veeps output corrupt file

### ISSUE THREAD

**Issue by tcafranz** [yt-dlp/yt-dlp#11171]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United States

### Provide a description that is worded well enough to be understood

I managed to download a replay of a live stream concert that I purchased and got a 4gb mp4 file that is almost 2 hours long and according to MediaInfo, SHOULD be exactly what I was trying to get. However, when I play the file, it's a fuzzy picture for 5 seconds.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--cookies', 'cookies.txt', 'https://div7xyk10qxp3.cloudfront.net/out/v1/84b8d198d9d347daa60649d1fc9d83d5/446b996fcbc349de91c9170241d37c76/622d7e85521544d5b8659b42e102a779/widevine_clip.m3u8']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.09.27 from yt-dlp/yt-dlp [c6387abc1] (pip)
[debug] Python 3.10.11 (CPython AMD64 64bit) - Windows-10-10.0.26120-SP0 (OpenSSL 1.1.1t  7 Feb 2023)
[debug] exe versions: ffmpeg 7.0 (setts)
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.07.04, mutagen-1.47.0, requests-2.32.3, sqlite3-3.40.1, urllib3-2.2.2, websockets-13.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1838 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.09.27 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.09.27 from yt-dlp/yt-dlp)
[generic] Extracting URL: https://div7xyk10qxp3.cloudfront.net/out/v1/84b8d198d9d347daa60649d1fc9d83d5/446b996fcbc349de91c9170241d37c76/622d7e85521544d5b8659b42e102a779/widevine_clip.m3u8
[generic] widevine_clip: Downloading webpage
[debug] Identified a direct video link
[generic] widevine_clip: Downloading m3u8 information
[generic] widevine_clip: Checking m3u8 live status
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] widevine_clip: Downloading 1 format(s): 6371+audio_0-und
[download] widevine_clip [widevine_clip].mp4 has already been downloaded
```

**Comment by grqz** [comment]
is it DRM'ed? [How to check if a media is DRM protected](https://github.com/yt-dlp/yt-dlp/issues/4062#issuecomment-1153474056)

**Comment by tcafranz** [comment]
> is it DRM'ed? [How to check if a media is DRM protected](https://github.com/yt-dlp/yt-dlp/issues/4062#issuecomment-1153474056)

Yea I tried on Brave with Widevine disabled and it wouldn't play, so guess that means it's DRM protected and I'm SOL... not even a way to get like just the audio? Aside of actually recording it while it's playing?

Thanks ahead of time.

**Comment by bashonly** [comment]
no
