### ISSUE TITLE
Need of requirements.txt file.

### ISSUE THREAD

**Issue by vignesh1507** [yt-dlp/yt-dlp#11183]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

The project doesn't have a requirements.txt file, it would be nice if it would be included in the repository.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by grqz** [comment]
there's already a `pyproject.toml`. if you want to install the dependencies, try running `devscripts/install_deps.py` or `pip install .`

**Comment by seproDev** [comment]
If you do need a requirements.txt file you can run `python devscripts/install_deps.py --print > requirements.txt`
We removed it as part of b8a433aaca86b15cb9f1a451b0f69371d2fc22a9 and wont be adding it back.
