### ISSUE TITLE
Please add support for xcancel.com

### ISSUE THREAD

**Issue by Fritz66** [yt-dlp/yt-dlp#11186]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

It doesn't work with xcancel.com, a Twitter replacement site.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
$ yt-dlp https://xcancel.com/WallStreetApes/status/1840856232346952165 -vU 
[debug] Command-line config: ['https://xcancel.com/WallStreetApes/status/1840856232346952165', '-vU']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.09.27 from yt-dlp/yt-dlp [c6387abc1] (zip)
[debug] Python 3.10.12 (CPython x86_64 64bit) - Linux-5.15.0-91-generic-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.11.0, brotli-1.0.9, certifi-2020.06.20, mutagen-1.45.1, pyxattr-0.7.2, requests-2.25.1, secretstorage-3.3.1, sqlite3-3.37.2, urllib3-1.26.5, websockets-9.1
[debug] Proxy map: {'all': 'socks5://127.0.0.1:9050'}
[debug] Request Handlers: urllib
[debug] Loaded 1838 extractors
[debug] Loading archive file '/media/user/SSD-storage/user/media-downloaded'
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.09.27 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.09.27 from yt-dlp/yt-dlp)
[generic] Extracting URL: https://xcancel.com/WallStreetApes/status/1840856232346952165
[generic] 1840856232346952165: Downloading webpage
ERROR: [generic] Unable to download webpage: HTTP Error 503: Service Temporarily Unavailable (caused by <HTTPError 503: Service Temporarily Unavailable>)
  File "/usr/bin/yt-dlp/yt_dlp/extractor/common.py", line 741, in extract
    ie_result = self._real_extract(url)
  File "/usr/bin/yt-dlp/yt_dlp/extractor/generic.py", line 2384, in _real_extract
    full_response = self._request_webpage(url, video_id, headers=filter_dict({
  File "/usr/bin/yt-dlp/yt_dlp/extractor/common.py", line 910, in _request_webpage
    raise ExtractorError(errmsg, cause=err)

  File "/usr/bin/yt-dlp/yt_dlp/networking/_urllib.py", line 398, in _send
    res = opener.open(urllib_req, timeout=self._calculate_timeout(request))
  File "/usr/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/usr/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 503: Service Temporarily Unavailable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/bin/yt-dlp/yt_dlp/extractor/common.py", line 897, in _request_webpage
    return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query, extensions))
  File "/usr/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 4165, in urlopen
    return self._request_director.send(req)
  File "/usr/bin/yt-dlp/yt_dlp/networking/common.py", line 117, in send
    response = handler.send(request)
  File "/usr/bin/yt-dlp/yt_dlp/networking/_helper.py", line 208, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/bin/yt-dlp/yt_dlp/networking/common.py", line 340, in send
    return self._send(request)
  File "/usr/bin/yt-dlp/yt_dlp/networking/_urllib.py", line 403, in _send
    raise HTTPError(UrllibResponseAdapter(e.fp), redirect_loop='redirect error' in str(e)) from e
yt_dlp.networking.exceptions.HTTPError: HTTP Error 503: Service Temporarily Unavailable
```

**Comment by dirkf** [comment]
This site is a Nitter instance protected by an anti-bot challenge.

The challenge is a number displayed using server-generated CSS, to be submitted via an HTML form. It would be necessary to OCR the digits, which might be possible by analysing the CSS as long as the digit patterns are as plain as they are now.

**Comment by bashonly** [comment]
nitter is on its last legs and the remaining instances have asked not to be scraped. I'd rather respect their wishes than reverse-engineer their anti-bot challenge

**Comment by Fritz66** [comment]
Would it be easier to do it for nitter.privacydev.net ?

**Comment by bashonly** [comment]
just use the twitter extractor

**Comment by Fritz66** [comment]
> twitter extractor

I checked the user manual, but I still don't know how to download a video.
Can you provide me with an example syntax?

**Comment by jonsummers** [comment]
If xcancel has a video that has been deleted from Twitter/X, you can obtain the m3u8 url by loading the xcancel page and view source. Search for ".u3m8", edit to extract url "https%3A%2F%2Fvideo.twimg.com%2Fext_tw_video...[STUFF].u3m8"
then convert %3A to ':' and every %2F to '/'.
Then use yt-dlp with the m3u8 url.
