### ISSUE TITLE
How can i exact the url of a mix from youtube

### ISSUE THREAD

**Issue by minhduc1212** [yt-dlp/yt-dlp#11181]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I want to get all the url of the mix in youtube but i don't know and also don't find in readme

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
what is the mix?

**Comment by gamer191** [comment]
I think they want the video and audio URLs, in which case they should use `--print urls`

**Comment by minhduc1212** [comment]
> what is the mix?
like this
https://www.youtube.com/watch?v=u6wOyMUs74I&list=RDu6wOyMUs74I&start_radio=1&rv=u6wOyMUs74I&t=2

**Comment by minhduc1212** [comment]
> I think they want the video and audio URLs, in which case they should use `--print urls`

I wish it will easy like you said but i can not get exactly url from the mix in yt like this: https://www.youtube.com/watch?v=u6wOyMUs74I&list=RDu6wOyMUs74I&start_radio=1&rv=u6wOyMUs74I&t=2

**Comment by grqz** [comment]
![image](https://github.com/user-attachments/assets/bed88d5b-5bfa-4052-ac87-8c709cf56b2d)
`yt-dlp -O webpage_url "https://www.youtube.com/watch?v=u6wOyMUs74I&list=RDu6wOyMUs74I&start_radio=1&t=2s"`

**Comment by gamer191** [comment]
Playlists must be put in quotes, otherwise yt-dlp will likely only download the first video
