### ISSUE TITLE
Unable to download 1080p Bilibili videos while logged in (passing cookies)

### ISSUE THREAD

**Issue by mmmpipi** [yt-dlp/yt-dlp#11199]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

China

### Provide a description that is worded well enough to be understood

Unable to download 1080p video while logged in,
It can be replicated on both Windows and Linux
It was okay in September.
Perhaps Bilibili has added additional login credentials,
Other projects such as bili sync and bilidown can still work
It could also be a security restriction
You can try using other accounts to replicate it
Or it could be that Bilibili changed the video link location

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['https://www.bilibili.com/video/BV1ZxsCe3EQW', '-vU', '--cookies-from-browser', 'firefox']
[debug] Home config "yt-dlp.conf": ['--output', '/mnt/win10/D/bilibili_video/mp4/%(title)s-%(uploader)s.%(ext)s', '--console-title', '--progress-template', 'download-title:%(info.id)s-%(progress.eta)s', '--merge-output-format', 'mp4', '--cookies', 'cookies.txt', '--embed-thumbnail', '--embed-metadata', '--convert-subs', 'srt']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.10.07 from yt-dlp/yt-dlp [1a176d874]
[debug] Python 3.12.6 (CPython x86_64 64bit) - Linux-6.11.2-zen1-1-zen-x86_64-with-glibc2.40 (OpenSSL 3.3.2 3 Sep 2024, glibc 2.40)
[debug] exe versions: ffmpeg 7.0.2 (setts), ffprobe 7.0.2, rtmpdump 2.4
[debug] Optional libraries: brotli-1.1.0, certifi-2024.08.30, mutagen-1.47.0, requests-2.32.3, secretstorage-3.3.3, sqlite3-3.46.1, urllib3-1.26.20, websockets-12.0
[debug] Proxy map: {}
Extracting cookies from firefox
[debug] Extracting cookies from: "/home/mmmpipi/.mozilla/firefox/gjo2ffbh.default-release/cookies.sqlite"
Extracted 1103 cookies from firefox
[debug] Request Handlers: urllib, requests
[debug] Loaded 1838 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.10.07 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.10.07 from yt-dlp/yt-dlp)
[BiliBili] Extracting URL: https://www.bilibili.com/video/BV1ZxsCe3EQW
[BiliBili] 1ZxsCe3EQW: Downloading webpage
[BiliBili] BV1ZxsCe3EQW: Extracting videos in anthology
[BiliBili] Format(s) 1080P 高清, 720P 高清 are missing; you have to login or become a premium member to download them. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies
[BiliBili] 113181129182344: Extracting chapters
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] BV1ZxsCe3EQW: Downloading 1 format(s): 100110+30280
[info] Downloading video thumbnail 0 ...
[info] Writing video thumbnail 0 to: /mnt/win10/D/bilibili_video/mp4/虎落平阳被犬欺!妈妈抱抱-宫百万_.jpg
[SubtitlesConvertor] There aren't any subtitles to convert
[debug] Invoking http downloader on "https://cn-sxty-cu-03-06.bilivideo.com/upgcxcode/65/88/25961368865/25961368865-1-100110.m4s?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0MvXg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M=&uipk=5&nbs=1&deadline=1728454405&gen=playurlv2&os=bcache&oi=0&trid=000009d7124754074acaa1e4aa6fedc5a713u&mid=0&platform=pc&og=cos&upsig=7eb84b623a7c07148cfa3d8b7905d8db&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,mid,platform,og&cdnid=71406&bvc=vod&nettype=0&orderid=0,3&buvid=456D2247-1ABB-B04C-3D91-C43DC8B3885B13730infoc&build=0&f=u_0_0&agrr=0&bw=27413&logo=80000000"
[download] Destination: /mnt/win10/D/bilibili_video/mp4/虎落平阳被犬欺!妈妈抱抱-宫百万_.f100110.mp4
[download] 100% of  615.74KiB in 00:00:00 at 2.47MiB/s
[debug] Invoking http downloader on "https://cn-sxty-cu-03-06.bilivideo.com/upgcxcode/65/88/25961368865/25961368865-1-30280.m4s?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0MvXg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M=&uipk=5&nbs=1&deadline=1728454405&gen=playurlv2&os=bcache&oi=0&trid=000009d7124754074acaa1e4aa6fedc5a713u&mid=0&platform=pc&og=hw&upsig=c127d257311cfa72792b59892015de77&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,mid,platform,og&cdnid=71406&bvc=vod&nettype=0&orderid=0,3&buvid=456D2247-1ABB-B04C-3D91-C43DC8B3885B13730infoc&build=0&f=u_0_0&agrr=0&bw=5517&logo=80000000"
[download] Destination: /mnt/win10/D/bilibili_video/mp4/虎落平阳被犬欺!妈妈抱抱-宫百万_.f30280.m4a
[download] 100% of  123.93KiB in 00:00:00 at 1.47MiB/s
[Merger] Merging formats into "/mnt/win10/D/bilibili_video/mp4/虎落平阳被犬欺!妈妈抱抱-宫百万_.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:/mnt/win10/D/bilibili_video/mp4/虎落平阳被犬欺!妈妈抱抱-宫百万_.f100110.mp4' -i 'file:/mnt/win10/D/bilibili_video/mp4/虎落平阳被犬欺!妈妈抱抱-宫百万_.f30280.m4a' -c copy -map 0:v:0 -map 1:a:0 -movflags +faststart 'file:/mnt/win10/D/bilibili_video/mp4/虎落平阳被犬欺!妈妈抱抱-宫百万_.temp.mp4'
Deleting original file /mnt/win10/D/bilibili_video/mp4/虎落平阳被犬欺!妈妈抱抱-宫百万_.f30280.m4a (pass -k to keep)
Deleting original file /mnt/win10/D/bilibili_video/mp4/虎落平阳被犬欺!妈妈抱抱-宫百万_.f100110.mp4 (pass -k to keep)
[Metadata] Adding metadata to "/mnt/win10/D/bilibili_video/mp4/虎落平阳被犬欺!妈妈抱抱-宫百万_.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:/mnt/win10/D/bilibili_video/mp4/虎落平阳被犬欺!妈妈抱抱-宫百万_.mp4' -map 0 -dn -ignore_unknown -c copy -write_id3v1 1 -metadata 'title=虎落平阳被犬欺!妈妈抱抱' -metadata date=20240922 -metadata 'description=虎落平阳被犬欺!妈妈抱抱' -metadata 'synopsis=虎落平阳被犬欺!妈妈抱抱' -metadata purl=https://www.bilibili.com/video/BV1ZxsCe3EQW -metadata comment=https://www.bilibili.com/video/BV1ZxsCe3EQW -metadata 'artist=宫百万_' -movflags +faststart 'file:/mnt/win10/D/bilibili_video/mp4/虎落平阳被犬欺!妈妈抱抱-宫百万_.temp.mp4'
[EmbedThumbnail] mutagen: Adding thumbnail to "/mnt/win10/D/bilibili_video/mp4/虎落平阳被犬欺!妈妈抱抱-宫百万_.mp4"
```

**Comment by grqz** [comment]
are you sure you're logged in in firefox? I can't reproduce
```log
C:\Users\Admin\Downloads\yt-dlp>yt-dlp -vU "https://www.bilibili.com/video/BV1ZxsCe3EQW" --cookies-from-browser firefox
[debug] Command-line config: ['-vU', 'https://www.bilibili.com/video/BV1ZxsCe3EQW', '--cookies-from-browser', 'firefox']
[debug] Encodings: locale cp936, fs utf-8, pref cp936, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.10.07.232845 from yt-dlp/yt-dlp-nightly-builds [079a7bc33] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-116607-gdeee00e2eb-20240812 (setts), ffprobe N-116607-gdeee00e2eb-20240812
[debug] Optional libraries: Cryptodome-3.21.0, brotli-1.1.0, certifi-2024.08.30, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.3, websockets-13.1
[debug] Proxy map: {}
Extracting cookies from firefox
[debug] Extracting cookies from: "C:\Users\Admin\AppData\Roaming\Mozilla\Firefox\Profiles\1kl3t5nv.default-release\cookies.sqlite"
Extracted 855 cookies from firefox
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Extractor Plugins: GetPOT (YoutubeIE), InvidiousIE, InvidiousPlaylistIE
[debug] Plugin directories: ['C:\\Users\\Admin\\Downloads\\yt-dlp\\yt-dlp-plugins\\bgutil-ytdlp-pot-provider.zip\\yt_dlp_plugins', 'C:\\Users\\Admin\\Downloads\\yt-dlp\\yt-dlp-plugins\\yt-dlp-get-pot.zip\\yt_dlp_plugins', 'C:\\Users\\Admin\\Downloads\\yt-dlp\\yt-dlp-plugins\\yt-dlp-invidious.zip\\yt_dlp_plugins']
[debug] Loaded 1838 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.10.07.232845 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.10.07.232845 from yt-dlp/yt-dlp-nightly-builds)
[BiliBili] Extracting URL: https://www.bilibili.com/video/BV1ZxsCe3EQW
[BiliBili] 1ZxsCe3EQW: Downloading webpage
[BiliBili] BV1ZxsCe3EQW: Extracting videos in anthology
[BiliBili] 113181129182344: Extracting chapters
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] BV1ZxsCe3EQW: Downloading 1 format(s): 100113+30280
[debug] Invoking http downloader on "https://upos-sz-mirroraliov.bilivideo.com/upgcxcode/65/88/25961368865/25961368865-1-100113.m4s?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0MvXg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M=&uipk=5&nbs=1&deadline=1728454872&gen=playurlv2&os=aliovbv&oi=2112787580&trid=41a081fb46cf4e74aef704d932e70802u&mid=492260394&platform=pc&og=hw&upsig=5e450bec258845b5d179930bb8f2d20a&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,mid,platform,og&bvc=vod&nettype=0&orderid=0,2&buvid=A5BFADF9-152C-0F88-F1FC-5045ABF2ACA218771infoc&build=0&f=u_0_0&agrr=0&bw=79538&logo=80000000"
[debug] File locking is not supported. Proceeding without locking
[download] Destination: 虎落平阳被犬欺!妈妈抱抱 [BV1ZxsCe3EQW].f100113.mp4
[download] 100% of    1.74MiB in 00:00:01 at 1.56MiB/s
[debug] Invoking http downloader on "https://upos-sz-mirroraliov.bilivideo.com/upgcxcode/65/88/25961368865/25961368865-1-30280.m4s?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0MvXg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M=&uipk=5&nbs=1&deadline=1728454872&gen=playurlv2&os=aliovbv&oi=2112787580&trid=41a081fb46cf4e74aef704d932e70802u&mid=492260394&platform=pc&og=hw&upsig=0c90c11c3f8bdf8fdef39b3d18ebfaed&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,mid,platform,og&bvc=vod&nettype=0&orderid=0,2&buvid=A5BFADF9-152C-0F88-F1FC-5045ABF2ACA218771infoc&build=0&f=u_0_0&agrr=0&bw=5517&logo=80000000"
[download] Destination: 虎落平阳被犬欺!妈妈抱抱 [BV1ZxsCe3EQW].f30280.m4a
[download] 100% of  123.93KiB in 00:00:00 at 754.32KiB/s
[Merger] Merging formats into "虎落平阳被犬欺!妈妈抱抱 [BV1ZxsCe3EQW].mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i "file:虎落平阳被犬欺!妈妈抱抱 [BV1ZxsCe3EQW].f100113.mp4" -i "file:虎落平阳被犬欺!妈妈抱抱 [BV1ZxsCe3EQW].f30280.m4a" -c copy -map 0:v:0 -map 1:a:0 -movflags +faststart "file:虎落平阳被犬欺!妈妈抱抱 [BV1ZxsCe3EQW].temp.mp4"
Deleting original file 虎落平阳被犬欺!妈妈抱抱 [BV1ZxsCe3EQW].f100113.mp4 (pass -k to keep)
Deleting original file 虎落平阳被犬欺!妈妈抱抱 [BV1ZxsCe3EQW].f30280.m4a (pass -k to keep)
```

**Comment by mmmpipi** [comment]
> are you sure you're logged in in firefox? I can't reproduce你确定你在Firefox中登录了吗？我不能生育
> 
> ```
> C:\Users\Admin\Downloads\yt-dlp>yt-dlp -vU "https://www.bilibili.com/video/BV1ZxsCe3EQW" --cookies-from-browser firefox
> [debug] Command-line config: ['-vU', 'https://www.bilibili.com/video/BV1ZxsCe3EQW', '--cookies-from-browser', 'firefox']
> [debug] Encodings: locale cp936, fs utf-8, pref cp936, out utf-8, error utf-8, screen utf-8
> [debug] yt-dlp version nightly@2024.10.07.232845 from yt-dlp/yt-dlp-nightly-builds [079a7bc33] (win_exe)
> [debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
> [debug] exe versions: ffmpeg N-116607-gdeee00e2eb-20240812 (setts), ffprobe N-116607-gdeee00e2eb-20240812
> [debug] Optional libraries: Cryptodome-3.21.0, brotli-1.1.0, certifi-2024.08.30, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.3, websockets-13.1
> [debug] Proxy map: {}
> Extracting cookies from firefox
> [debug] Extracting cookies from: "C:\Users\Admin\AppData\Roaming\Mozilla\Firefox\Profiles\1kl3t5nv.default-release\cookies.sqlite"
> Extracted 855 cookies from firefox
> [debug] Request Handlers: urllib, requests, websockets, curl_cffi
> [debug] Extractor Plugins: GetPOT (YoutubeIE), InvidiousIE, InvidiousPlaylistIE
> [debug] Plugin directories: ['C:\\Users\\Admin\\Downloads\\yt-dlp\\yt-dlp-plugins\\bgutil-ytdlp-pot-provider.zip\\yt_dlp_plugins', 'C:\\Users\\Admin\\Downloads\\yt-dlp\\yt-dlp-plugins\\yt-dlp-get-pot.zip\\yt_dlp_plugins', 'C:\\Users\\Admin\\Downloads\\yt-dlp\\yt-dlp-plugins\\yt-dlp-invidious.zip\\yt_dlp_plugins']
> [debug] Loaded 1838 extractors
> [debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
> Latest version: nightly@2024.10.07.232845 from yt-dlp/yt-dlp-nightly-builds
> yt-dlp is up to date (nightly@2024.10.07.232845 from yt-dlp/yt-dlp-nightly-builds)
> [BiliBili] Extracting URL: https://www.bilibili.com/video/BV1ZxsCe3EQW
> [BiliBili] 1ZxsCe3EQW: Downloading webpage
> [BiliBili] BV1ZxsCe3EQW: Extracting videos in anthology
> [BiliBili] 113181129182344: Extracting chapters
> [debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
> [debug] Default format spec: bestvideo*+bestaudio/best
> [info] BV1ZxsCe3EQW: Downloading 1 format(s): 100113+30280
> [debug] Invoking http downloader on "https://upos-sz-mirroraliov.bilivideo.com/upgcxcode/65/88/25961368865/25961368865-1-100113.m4s?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0MvXg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M=&uipk=5&nbs=1&deadline=1728454872&gen=playurlv2&os=aliovbv&oi=2112787580&trid=41a081fb46cf4e74aef704d932e70802u&mid=492260394&platform=pc&og=hw&upsig=5e450bec258845b5d179930bb8f2d20a&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,mid,platform,og&bvc=vod&nettype=0&orderid=0,2&buvid=A5BFADF9-152C-0F88-F1FC-5045ABF2ACA218771infoc&build=0&f=u_0_0&agrr=0&bw=79538&logo=80000000"
> [debug] File locking is not supported. Proceeding without locking
> [download] Destination: 虎落平阳被犬欺!妈妈抱抱 [BV1ZxsCe3EQW].f100113.mp4
> [download] 100% of    1.74MiB in 00:00:01 at 1.56MiB/s
> [debug] Invoking http downloader on "https://upos-sz-mirroraliov.bilivideo.com/upgcxcode/65/88/25961368865/25961368865-1-30280.m4s?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0MvXg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M=&uipk=5&nbs=1&deadline=1728454872&gen=playurlv2&os=aliovbv&oi=2112787580&trid=41a081fb46cf4e74aef704d932e70802u&mid=492260394&platform=pc&og=hw&upsig=0c90c11c3f8bdf8fdef39b3d18ebfaed&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,mid,platform,og&bvc=vod&nettype=0&orderid=0,2&buvid=A5BFADF9-152C-0F88-F1FC-5045ABF2ACA218771infoc&build=0&f=u_0_0&agrr=0&bw=5517&logo=80000000"
> [download] Destination: 虎落平阳被犬欺!妈妈抱抱 [BV1ZxsCe3EQW].f30280.m4a
> [download] 100% of  123.93KiB in 00:00:00 at 754.32KiB/s
> [Merger] Merging formats into "虎落平阳被犬欺!妈妈抱抱 [BV1ZxsCe3EQW].mp4"
> [debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i "file:虎落平阳被犬欺!妈妈抱抱 [BV1ZxsCe3EQW].f100113.mp4" -i "file:虎落平阳被犬欺!妈妈抱抱 [BV1ZxsCe3EQW].f30280.m4a" -c copy -map 0:v:0 -map 1:a:0 -movflags +faststart "file:虎落平阳被犬欺!妈妈抱抱 [BV1ZxsCe3EQW].temp.mp4"
> Deleting original file 虎落平阳被犬欺!妈妈抱抱 [BV1ZxsCe3EQW].f100113.mp4 (pass -k to keep)
> Deleting original file 虎落平阳被犬欺!妈妈抱抱 [BV1ZxsCe3EQW].f30280.m4a (pass -k to keep)
> ```

im sure login in firefox,and try on my windows.it don't work on windows too.

**Comment by mmmpipi** [comment]
i see other programe has ac_time_value to login bilibili,and it isn't in cookies,it in local data. It may be related to this

**Comment by kclauhk** [comment]
ac_time_value is not needed
The following are available (in Windows) without 'ac_time_value'
<pre>
100026 mp4 1080x1920   30 │ ≈  2.31MiB  838k https │ av01.0.00M.10  838k video only
30080  mp4 1080x1920   30 │ ≈  6.11MiB 2214k https │ avc1.640032   2214k video only
100113 mp4 1080x1920   30 │ ≈  1.76MiB  639k https │ hev1.1.6.L150  639k video only
</pre>

try logout and login again in firefox

**Comment by mmmpipi** [comment]
> ac_time_value is not needed The following are available (in Windows) without 'ac_time_value'
> 
> 100026 mp4 1080x1920   30 │ ≈  2.31MiB  838k https │ av01.0.00M.10  838k video only
> 30080  mp4 1080x1920   30 │ ≈  6.11MiB 2214k https │ avc1.640032   2214k video only
> 100113 mp4 1080x1920   30 │ ≈  1.76MiB  639k https │ hev1.1.6.L150  639k video only
> 
> try logout and login again in firefox

No effect, still not working

**Comment by mmmpipi** [comment]
[debug] Command-line config: ['--cookies-from-browser', 'firefox', 'https://www.bilibili.com/video/BV1ZxsCe3EQW', '--cookies', 'cookies.txt', '-F', '-vU']
[debug] Home config "yt-dlp.conf": ['--output', '/mnt/win10/D/bilibili_video/mp4/%(title)s-%(uploader)s.%(ext)s', '--console-title', '--progress-template', 'download-title:%(info.id)s-%(progress.eta)s', '--merge-output-format', 'mp4', '--cookies', 'cookies.txt', '--embed-thumbnail', '--embed-metadata', '--convert-subs', 'srt']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.10.07 from yt-dlp/yt-dlp [1a176d874]
[debug] Python 3.12.6 (CPython x86_64 64bit) - Linux-6.11.2-zen1-1-zen-x86_64-with-glibc2.40 (OpenSSL 3.3.2 3 Sep 2024, glibc 2.40)
[debug] exe versions: ffmpeg 7.0.2 (setts), ffprobe 7.0.2, rtmpdump 2.4
[debug] Optional libraries: brotli-1.1.0, certifi-2024.08.30, mutagen-1.47.0, requests-2.32.3, secretstorage-3.3.3, sqlite3-3.46.1, urllib3-1.26.20, websockets-12.0
[debug] Proxy map: {}
Extracting cookies from firefox
[debug] Extracting cookies from: "/home/mmmpipi/.mozilla/firefox/gjo2ffbh.default-release/cookies.sqlite"
Extracted 1112 cookies from firefox
[debug] Request Handlers: urllib, requests
[debug] Loaded 1838 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.10.07 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.10.07 from yt-dlp/yt-dlp)
[BiliBili] Extracting URL: https://www.bilibili.com/video/BV1ZxsCe3EQW
[BiliBili] 1ZxsCe3EQW: Downloading webpage
[BiliBili] BV1ZxsCe3EQW: Extracting videos in anthology
[BiliBili] Format(s) 1080P 高清, 720P 高清 are missing; you have to login or become a premium member to download them. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies
[BiliBili] 113181129182344: Extracting chapters
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[info] Available formats for BV1ZxsCe3EQW:
ID     EXT RESOLUTION FPS │   FILESIZE  TBR PROTO │ VCODEC         VBR ACODEC     ABR
─────────────────────────────────────────────────────────────────────────────────────
30216  m4a audio only     │ ≈123.03KiB  43k https │ audio only         mp4a.40.5  43k
30232  m4a audio only     │ ≈123.03KiB  43k https │ audio only         mp4a.40.5  43k
30280  m4a audio only     │ ≈123.03KiB  43k https │ audio only         mp4a.40.5  43k
100022 mp4 360x640     30 │ ≈541.12KiB 191k https │ av01.0.00M.10 191k video only
30016  mp4 360x640     30 │ ≈  1.01MiB 366k https │ avc1.64001E   366k video only
100109 mp4 360x640     30 │ ≈438.91KiB 155k https │ hev1.1.6.L120 155k video only
100023 mp4 480x852     30 │ ≈745.30KiB 263k https │ av01.0.00M.10 263k video only
30032  mp4 480x852     30 │ ≈  1.53MiB 552k https │ avc1.64001F   552k video only
100110 mp4 480x852     30 │ ≈621.87KiB 220k https │ hev1.1.6.L120 220k video only

**Comment by mmmpipi** [comment]
with reboot and relogin, it works!
