### ISSUE TITLE
[Question] Possible wrong metadata info in TikTok videos.

### ISSUE THREAD

**Issue by 54m4d** [yt-dlp/yt-dlp#1119]
## Checklist

- [X] I'm asking a question
- [X] I've looked through the README and FAQ for similar questions
- [X] I've searched the bugtracker for similar questions including closed ones

## Question

When checking the metadata on a downloaded tiktok video there's a metadata field that i think is wrong:

<pre>
Format                      : MPEG-4
Format profile              : Base Media
Codec ID                    : isom (isom/iso2/mp41)
File size                   : 899 KiB
Duration                    : 56 s 392 ms
Overall bit rate            : 131 kb/s
<b>Movie name </b>                 : original sound
Performer                   : Lachief
Description                 : Do this If you have a Computer or Laptop  #pctips #pctricks #computertricks #computertips #gamingpc #laptophack #pchacks
Recorded date               : 20210915
Writing application         : Lavf59.5.100
Comment                     : https://www.tiktok.com/@.lachief/video/7008059634590207233
LongDescription             : Do this If you have a Computer or Laptop  #pctips #pctricks #computertricks #computertips #gamingpc #laptophack #pchacks
</pre>

Shouldn't `Movie name` be called `track` or `sound/sound name`?

I checked the video on the site and i could verify that it is the song/sound that was used in the video and not a movie name.

**Comment by pukkandan** [comment]
The field names shown are by media info. They are not the actual internal field names and we have no control over it

**Comment by fosam** [comment]
Is it even possible to show the actual field names with a tool or something?

**Comment by pukkandan** [comment]
You can see them with ffprobe. But again, the fields must use certain standard names for it to be recognized by video players, media info etc. So thise are the names that yt-dlp uses. If you want to add custom fields, you have to use `--parse-metadata`. See https://github.com/yt-dlp/yt-dlp#modifying-metadata

**Comment by fosam** [comment]
I tried `--parse-metadata "song:%(meta_Movie name)s"` and `--parse-metadata "Movie name:%(meta_song)s"` but coudn't see a difference

**Comment by pukkandan** [comment]
https://kdenlive.org/en/project/adding-meta-data-to-mp4-video/

**Comment by fosam** [comment]
Hmm, in my testing it works with `MKV` and easy, unlike `MP4`

**Comment by pukkandan** [comment]
mkv supports any arbitrary metadata fields. mp4 doesn't

Please close the issue if you have no further questions
