### ISSUE TITLE
[Instagram Reel] How to remove Destination: Video by frederikkewaerens and get title file name

### ISSUE THREAD

**Issue by seaklin83546** [yt-dlp/yt-dlp#11209]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

[Instagram Reel] How to remove Destination: Video by frederikkewaerens and get title file name: Honey and thyme baked apricots served on burrata with toasted bread🍯🍑 The perfect side dish!.

Please help me 🙏

yt-dlp -vU --cookies "instagram.txt" -f "bv*[vcodec^=avc]+ba[ext=m4a]/b[ext=mp4]/b" https://www.instagram.com/reel/C97eB5PIlZ_/
[debug] Command-line config: ['-vU', '--cookies', 'instagram.txt', '-f', 'bv*[vcodec^=avc]+ba[ext=m4a]/b[ext=mp4]/b', 'https://www.instagram.com/reel/C97eB5PIlZ_/']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.10.07.232845 from yt-dlp/yt-dlp-nightly-builds [079a7bc33] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22631-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 2024-10-02-git-358fdf3083-full_build-www.gyan.dev (setts), ffprobe 2024-10-02-git-358fdf3083-full_build-www.gyan.dev, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.21.0, brotli-1.1.0, certifi-2024.08.30, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.3, websockets-13.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1838 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.10.07.232845 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.10.07.232845 from yt-dlp/yt-dlp-nightly-builds)
[Instagram] Extracting URL: https://www.instagram.com/reel/C97eB5PIlZ_/
[Instagram] C97eB5PIlZ_: Downloading video info
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[info] C97eB5PIlZ_: Downloading 1 format(s): 1144191919975363v
[debug] Invoking http downloader on "https://instagram.fpnh11-1.fna.fbcdn.net/o1/v/t16/f1/m86/A943A53FA5B94BCB6DABFE1AB64885AA_video_dashinit.mp4?efg=eyJ2ZW5jb2RlX3RhZyI6Inhwdl9wcm9ncmVzc2l2ZS5JTlNUQUdSQU0uQ0xJUFMuQzMuNzIwLmRhc2hfYmFzZWxpbmVfMV92MSJ9&_nc_ht=instagram.fpnh11-1.fna.fbcdn.net&_nc_cat=103&vs=80672a6c54a1e331&_nc_vs=HBksFQIYUmlnX3hwdl9yZWVsc19wZXJtYW5lbnRfc3JfcHJvZC9BOTQzQTUzRkE1Qjk0QkNCNkRBQkZFMUFCNjQ4ODVBQV92aWRlb19kYXNoaW5pdC5tcDQVAALIAQAVAhg6cGFzc3Rocm91Z2hfZXZlcnN0b3JlL0dGNGItaG9ZXzhPbDk2TUJBTnV1N3Q0ZDgtQkVicV9FQUFBRhUCAsgBACgAGAAbAogHdXNlX29pbAExEnByb2dyZXNzaXZlX3JlY2lwZQExFQAAJqj30Ljh0YIEFQIoAkMzLBdAI3dLxqfvnhgSZGFzaF9iYXNlbGluZV8xX3YxEQB1_gcA&ccb=9-4&oh=00_AYCs00AZYNuf2-mZbRXtaOs_SY8maZkMw4AfTkZlZchCsg&oe=67094BD7&_nc_sid=1d576d"
[debug] File locking is not supported. Proceeding without locking
[download] Destination: Video by frederikkewaerens [C97eB5PIlZ_].mp4
[download] 100% of    2.87MiB in 00:00:01 at 2.01MiB/s

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by grqz** [comment]
```
-o "%(description)s [%(id)s].%(ext)s" --parse-metadata "description:(?P<description>.+)\n"
```
