### ISSUE TITLE
[Facebook Reel] How to remove ( Destination: 19M views · 132K reactions ｜) 

### ISSUE THREAD

**Issue by seaklin83546** [yt-dlp/yt-dlp#11208]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

How to remove => Destination: 19M views · 132K reactions because i need only title. Please help me.

yt-dlp -vU -f "bv*[vcodec^=avc]+ba[ext=m4a]/b[ext=mp4]/b" https://www.facebook.com/reel/1518618646198141
[debug] Command-line config: ['-vU', '-f', 'bv*[vcodec^=avc]+ba[ext=m4a]/b[ext=mp4]/b', 'https://www.facebook.com/reel/1518618646198141']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.09.08.232909 from yt-dlp/yt-dlp-nightly-builds [d1c4d88b2] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22631-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 2024-10-02-git-358fdf3083-full_build-www.gyan.dev (setts), ffprobe 2024-10-02-git-358fdf3083-full_build-www.gyan.dev, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.08.30, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.2, websockets-13.0.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1832 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
[debug] Downloading _update_spec from https://github.com/yt-dlp/yt-dlp-nightly-builds/releases/latest/download/_update_spec
[debug] Downloading SHA2-256SUMS from https://github.com/yt-dlp/yt-dlp-nightly-builds/releases/download/2024.10.07.232845/SHA2-256SUMS
Current version: nightly@2024.09.08.232909 from yt-dlp/yt-dlp-nightly-builds
Latest version: nightly@2024.10.07.232845 from yt-dlp/yt-dlp-nightly-builds
Current Build Hash: df29cd6032ada0273458c8f38734788e85e4c2219bff88ac145dd3a4d8bae8fe
Updating to nightly@2024.10.07.232845 from yt-dlp/yt-dlp-nightly-builds ...
[debug] Downloading yt-dlp.exe from https://github.com/yt-dlp/yt-dlp-nightly-builds/releases/download/2024.10.07.232845/yt-dlp.exe
Updated yt-dlp to nightly@2024.10.07.232845 from yt-dlp/yt-dlp-nightly-builds
[debug] Restarting: C:\bin\yt-dlp.exe -vU -f "bv*[vcodec^=avc]+ba[ext=m4a]/b[ext=mp4]/b" https://www.facebook.com/reel/1518618646198141
[debug] Command-line config: ['-vU', '-f', 'bv*[vcodec^=avc]+ba[ext=m4a]/b[ext=mp4]/b', 'https://www.facebook.com/reel/1518618646198141']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.10.07.232845 from yt-dlp/yt-dlp-nightly-builds [079a7bc33] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22631-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 2024-10-02-git-358fdf3083-full_build-www.gyan.dev (setts), ffprobe 2024-10-02-git-358fdf3083-full_build-www.gyan.dev, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.21.0, brotli-1.1.0, certifi-2024.08.30, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.3, websockets-13.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1838 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.10.07.232845 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.10.07.232845 from yt-dlp/yt-dlp-nightly-builds)
[facebook:reel] Extracting URL: https://www.facebook.com/reel/1518618646198141
[facebook] Extracting URL: https://m.facebook.com/watch/?v=1518618646198141&_rdr
[facebook] 1518618646198141: Downloading webpage
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[info] 1518618646198141: Downloading 1 format(s): hd
[debug] Invoking http downloader on "https://video.fpnh11-1.fna.fbcdn.net/o1/v/t2/f2/m69/AQO_P7F6HrBW8XIydv4B72SkcLOeLw-JmZsT-qEdrBdTRKUmKNmCc3DEwYXH7lx2vCuVaqqO2zeJ2B1Squ-vYQOx.mp4?efg=eyJ2ZW5jb2RlX3RhZyI6Im9lcF9oZCJ9&_nc_ht=video.fpnh11-1.fna.fbcdn.net&_nc_cat=1&strext=1&vs=4785fd265ea11a3a&_nc_vs=HBksFQIYOnBhc3N0aHJvdWdoX2V2ZXJzdG9yZS9HREpBWEJzSlNTbjhUNHdGQUNWand5XzJpUXRxYm1kakFBQUYVAALIAQAVAhg6cGFzc3Rocm91Z2hfZXZlcnN0b3JlL0dKbzFYUnZYYVlCNTJsNEJBSU5ZeE9KOE5wVk1ickZxQUFBRhUCAsgBAEsHiBJwcm9ncmVzc2l2ZV9yZWNpcGUBMQ1zdWJzYW1wbGVfZnBzABB2bWFmX2VuYWJsZV9uc3ViACBtZWFzdXJlX29yaWdpbmFsX3Jlc29sdXRpb25fc3NpbQAoY29tcHV0ZV9zc2ltX29ubHlfYXRfb3JpZ2luYWxfcmVzb2x1dGlvbgAddXNlX2xhbmN6b3NfZm9yX3ZxbV91cHNjYWxpbmcAEWRpc2FibGVfcG9zdF9wdnFzABUAJQAcjBdAAAAAAAAAABERAAAAJqinysGR6uUBFQIoAkMzGAt2dHNfcHJldmlldxwXQEL3bItDlYEYGWRhc2hfaDI2NC1iYXNpYy1nZW4yXzcyMHASABgYdmlkZW9zLnZ0cy5jYWxsYmFjay5wcm9kOBJWSURFT19WSUVXX1JFUVVFU1QbCogVb2VtX3RhcmdldF9lbmNvZGVfdGFnBm9lcF9oZBNvZW1fcmVxdWVzdF90aW1lX21zATAMb2VtX2NmZ19ydWxlB3VubXV0ZWQTb2VtX3JvaV9yZWFjaF9jb3VudAQ2NDkwEW9lbV9pc19leHBlcmltZW50AAxvZW1fdmlkZW9faWQQMTUxODYxODY0NjE5ODE0MRJvZW1fdmlkZW9fYXNzZXRfaWQQMzMzODk0MDczNjIzNzk0OBVvZW1fdmlkZW9fcmVzb3VyY2VfaWQPNTA1Mzk5NzQyMTIyNDUyHG9lbV9zb3VyY2VfdmlkZW9fZW5jb2RpbmdfaWQPNTA0Njk4MTI5MDIyMjg5DnZ0c19yZXF1ZXN0X2lkACUCHAAlxAEbB4gBcwQ3MDk1AmNkCjIwMjQtMDktMDgDcmNiBDY0MDADYXBwFEZhY2Vib29rIGZvciBBbmRyb2lkAmN0DkZCX1NIT1JUU19QT1NUE29yaWdpbmFsX2R1cmF0aW9uX3MJMzcuODk5OTg5AnRzFXByb2dyZXNzaXZlX2VuY29kaW5ncwA&ccb=9-4&oh=00_AYBCpYLQNbAmM2766NTg8iZ0wEclkVb0cOk_3d0alBPUCA&oe=670933C4&_nc_sid=1d576d&_nc_rid=224417555057687&_nc_store_type=1"
[debug] File locking is not supported. Proceeding without locking
[download] Destination: 19M views · 132K reactions ｜ En mis tiempos las escondiamos 🤣🤣🤣 @seguidores #reelsviralシ #paratiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii #fypシ #seguidores #destacar #virals #Todos ｜ Elpopos ｜ Susy Díaz · Vive La Vida (2021 Version) [1518618646198141].mp4
[download] 100% of    7.07MiB in 00:00:00 at 9.56MiB/s

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
```
--parse-metadata "title:.+reactions \| (?P<title>.+)"
```

**Comment by seaklin83546** [comment]
> --parse-metadata "title:.+reactions \| (?P<title>.+)"

Worked. Thank you very much admin 🙏
