### ISSUE TITLE
[weverse] Failed to parse JSON (API end point might have changed)

### ISSUE THREAD

**Issue by RichardReallyHard** [yt-dlp/yt-dlp#11213]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [x] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

all

### Provide a description that is worded well enough to be understood

starting from 20241010, the following error occurs for every live video (watchable on browser)

> ERROR: [Weverse] 3-181507553: 3-181507553: Failed to parse JSON (caused by JSONDecodeError("Expecting value in '': line 1 column 1 (char 0)"));

links to the video (non-membership, actually all video fails):

> https://weverse.io/fromis9/live/3-181507553

the JSON format or API end point might have changed ?

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [x] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--', 'https://weverse.io/fromis9/live/3-181507553']
[debug] Encodings: locale cp950, fs utf-8, pref cp950, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.10.07.232845 from yt-dlp/yt-dlp-nightly-builds [079a7bc33] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 2022-02-10-git-b6bb6b9f22-essentials_build-www.gyan.dev (setts), ffprobe 2022-02-10-git-b6bb6b9f22-essentials_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.21.0, brotli-1.1.0, certifi-2024.08.30, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.3, websockets-13.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1838 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.10.07.232845 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.10.07.232845 from yt-dlp/yt-dlp-nightly-builds)
[Weverse] Extracting URL: https://weverse.io/fromis9/live/3-181507553
[Weverse] 3-181507553: Downloading API JSON
[Weverse] 3-181507553: Downloading VOD API key
ERROR: [Weverse] 3-181507553: 3-181507553: Failed to parse JSON (caused by JSONDecodeError("Expecting value in '': line 1 column 1 (char 0)")); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 741, in extract
  File "yt_dlp\extractor\weverse.py", line 304, in _real_extract
  File "yt_dlp\extractor\weverse.py", line 91, in _call_api
  File "yt_dlp\extractor\common.py", line 1151, in download_content
  File "yt_dlp\extractor\common.py", line 1118, in download_handle
  File "yt_dlp\extractor\common.py", line 1106, in parse
  File "yt_dlp\extractor\common.py", line 1093, in _parse_json
  File "yt_dlp\extractor\common.py", line 1076, in __print_error

  File "yt_dlp\utils\_utils.py", line 552, in decode
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\extractor\common.py", line 1090, in _parse_json
  File "json\__init__.py", line 370, in loads
  File "yt_dlp\utils\_utils.py", line 560, in decode
json.decoder.JSONDecodeError: Expecting value in '': line 1 column 1 (char 0)
```

**Comment by hooned** [comment]
hi is there a fix to this issue ? i've been having it as well 🥹 thank you so much!

**Comment by grqz** [comment]
@hooned 
```sh
yt-dlp --update-to nightly
```

**Comment by hooned** [comment]
thank you thank you soo much !! 🥹

**Comment by entreprenr** [comment]
Yay thanks, I had the same issue and after updating to nightly it works now!
