### ISSUE TITLE
How can I update yt-dlp to version 2024.10.07 without pip or brew?

### ISSUE THREAD

**Issue by JacobDreiling** [yt-dlp/yt-dlp#11217]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I used to update yt-dlp using pip, but a few years back, it became a mess keeping track of python versions. Here's the result when I try using pip (I've tried many similar commands and changing paths, and it always shows this older version):
```
quasarbooster@Jacobs-MacBook-Air-2 ~ % python3 -m pip install yt-dlp  
Requirement already satisfied: yt-dlp in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (2023.11.16)
```
I switched to using brew, but it's no longer supported on macOS 12, and my computer can't update to a newer OS version. How can I keep up with yt-dlp without brew or pip? Or what do I need to do differently?

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [x] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
quasarbooster@Jacobs-MacBook-Air-2 ~ % yt-dlp -vU
[debug] Command-line config: ['-vU']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.08.06 from yt-dlp/yt-dlp [4d9231208] (pip)
[debug] Python 3.12.4 (CPython x86_64 64bit) - macOS-12.7.6-x86_64-i386-64bit (OpenSSL 3.3.2 3 Sep 2024)
[debug] exe versions: ffmpeg 7.0.1 (setts), ffprobe 7.0.1
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.07.04, mutagen-1.47.0, requests-2.32.3, sqlite3-3.46.1, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1830 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
[debug] Downloading _update_spec from https://github.com/yt-dlp/yt-dlp/releases/latest/download/_update_spec
Current version: stable@2024.08.06 from yt-dlp/yt-dlp
Latest version: stable@2024.10.07 from yt-dlp/yt-dlp
ERROR: You installed yt-dlp with pip or using the wheel from PyPi; Use that to update
```

**Comment by bashonly** [comment]
`python3 -m pip install -U yt-dlp `

**Comment by JacobDreiling** [comment]
I get the same response from pip. I also tried uninstall and reinstall.

**Comment by gamer191** [comment]
1. uninstall the pip version of yt-dlp, and any other installed version
2. run the following commands:
```
curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp_macos_legacy -o ~/.local/bin/yt-dlp
chmod a+rx ~/.local/bin/yt-dlp
```
Then whenever you want to update just run `yt-dlp -U`

Let me know if the above commands work, since I don't have a MacBook to test them on. If you get permission denied, just add sudo to the start of the failed command

**Comment by JacobDreiling** [comment]
That local bin location didn't exist on my mac, so I tried curl to
```
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12
```
That seemed to successfully instal yt-dlp. However when I try to check the version, zsh cannot find the command. It looks like the version of python running on my terminal is 3.7.

Should I try installing yt-dlp in a virtual env instead?

**Comment by gamer191** [comment]
`yt-dlp_macos_legacy` is a compiled executable, not a python package. I have no idea how you can get rid of it now without creating further problems (since you probably overwrote the yt-dlp python package). Perhaps `python312 -m pip uninstall yt-dlp` will work

Please run the curl command as is, and let me know whether it works. Folders beginning in . are supposed to be hidden, and if they don't exist curl can probably create them anyway (but if not, run `mkdir ~/.local/bin --parents`). Also, correcting my previous message, please don't run either command with sudo

**Comment by JacobDreiling** [comment]
Pip uninstall didn't work. I just manually deleted the executable, and I'll have to see if I messed anything up too badly. Running your above command didn't work (no such file or directory), but after creating the directory with mkdir, it did work.

I also ran chmod as suggested. Trying `yt-dlp --version` still gives `zsh: command not found`

**Comment by bashonly** [comment]
> ```
> quasarbooster@Jacobs-MacBook-Air-2 ~ % python3 -m pip install yt-dlp  
> ```

you are missing the `-U` (`--upgrade`) in this :point_up: command, so that's why you were getting this :point_down::

> ```
> Requirement already satisfied: yt-dlp in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (2023.11.16)
> ```

which is why I suggested adding the `-U` to the command :point_down:

> `python3 -m pip install -U yt-dlp`

---

> That local bin location didn't exist on my mac, so I tried curl to
> ```
> /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/yt-dlp
> ```

do not do this :point_up:

if you want to install the pyinstaller-bundled executable for macOS, follow [:point_right:**these steps**:point_left:](https://github.com/yt-dlp/yt-dlp/issues/10356#issuecomment-2210374201)

**Comment by JacobDreiling** [comment]
I really appreciate both of your help so far. Weirdly, after installing the executable last night as gamer191 suggested, zsh didn't recognize yt-dlp. However, after just trying it, it does work now. I don't remember changing anything since last night. One concern: is it supposed to stall for 10-20 seconds before running?

> you'll need to uninstall 3.7 and ensure that 3.12 is in your PATH if you want to use pip-installed yt-dlp

Can confirm I have 3.12 in my PATH. If I did want to uninstall 3.7, would it mess up any important systems that use it? What's the recommended way to uninstall it? (I have projects in pycharm that use it in a venv - would those still work?)

**Comment by bashonly** [comment]
> is it supposed to stall for 10-20 seconds before running?

This is just how it is for some macOS systems with the pyinstaller onefile executable. It's Apple security scanning slowing everything down. This is why it is preferable for most macOS to install with brew or pip/pipx

**Comment by bashonly** [comment]
> If I did want to uninstall 3.7, would it mess up any important systems that use it? What's the recommended way to uninstall it? (I have projects in pycharm that use it in a venv - would those still work?)

I don't know. I would just give 3.12 precedence in your PATH then (currently 3.7 has precedence)

**Comment by JacobDreiling** [comment]
> I don't know. I would just give 3.12 precedence in your PATH then (currently 3.7 has precedence)

That seemed to work. I was able to use pip to get the most recent version of yt-dlp and it's not stalling anymore. I removed the executable, then added my updated PYTHONPATH to bash_profile:
```
sudo nano ~/.bash_profile
PYTHONPATH="/Library/Frameworks/Python.framework/Versions/3.12/bin/python3"
export PYTHONPATH
source ~/.bash_profile
```
Is this an okay way of changing which version of python is used?

**Comment by bashonly** [comment]
> Is this an okay way of changing which version of python is used?

I don't know enough about your system / other Python usage to say definitively. You'll have to try it and see. But it makes sense as far as yt-dlp usage goes

**Comment by JacobDreiling** [comment]
Thanks again you both! I'm glad to have found a fix for using pip.
