### ISSUE TITLE
Does yt_dlp.YoutubeDL make any requests to the external network?

### ISSUE THREAD

**Issue by vmstarchenko** [yt-dlp/yt-dlp#11214]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Hello. I have a general question about how the yt_dlp.YoutubeDL function works. I have the following code:

```python
ydl_opts = {
    ...
}

with yt_dlp.YoutubeDL(ydl_opts) as ydl:
    # real work
```

I want to understand if any requests are made or if connections to the service are opened before the "real work" line. For example, if I have 100 proxies that I want to use one after the other, is it safe to call yt_dlp.YoutubeDL 100 times in the context manager at the program startup and then use them somehow? Or will this be opening 100 connections to the service at the same time and will look like suspicious traffic.

```python
with ExitStack() as stack:
    ydlps = {i: stack.enter_context(yt_dlp.YoutubeDL({**ydl_opts, 'proxy': proxies[i])) for i in range(100)}
    # round robin select ydlp from available
```

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
initializing `YoutubeDL` alone does not make any network requests
