### ISSUE TITLE
Intermittent Issue: "WARNING - Cannot Update utime of File", Followed by Failure to Move File from Temp Folder to Final Path

### ISSUE THREAD

**Issue by MattBlackOnly** [yt-dlp/yt-dlp#11223]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

The issue is that the file downloads successfully and appears to be complete and in the correct format, but it intermittently fails when attempting to update the file's utime. 

As a result, the file is not moved to the final path and remains in the temp folder. Interestingly, for the same video, this sometimes works without any issues. 

When it doesn't work, running the exact same code again immediately, it will move the file from the temp folder to its final location, without downloading.
  
  
  
**Note:** these are the file left in the `/temp` folder -> 
> /temp/My Video Download!.mp4 
> /temp/My Video Download!.png  

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8 (No ANSI), error utf-8 (No ANSI), screen utf-8 (No ANSI)
[debug] yt-dlp version stable@2024.10.07 from yt-dlp/yt-dlp [1a176d874] (pip) API
[debug] params: {'ignore_no_formats_error': True, 'noplaylist': True, 'outtmpl': 'My Video Download!.%(ext)s', 'ffmpeg_location': '/usr/bin/ffmpeg', 'writethumbnail': True, 'quiet': False, 'extract_flat': True, 'format': 'bestvideo+bestaudio/best', 'updatetime': False, 'extractor_args': {'youtubetab': {'skip': ['authcheck']}}, 'paths': {'home': '/data', 'temp': '/temp'}, 'no_overwrites': True, 'verbose': True, 'merge_output_format': 'mp4', 'cookiefile': '/cookies.txt', 'postprocessors': [{'key': 'SponsorBlock', 'categories': ['sponsor']}, {'key': 'ModifyChapters', 'remove_sponsor_segments': ['sponsor']}, {'key': 'FFmpegThumbnailsConvertor', 'format': 'png', 'when': 'before_dl'}, {'key': 'FFmpegMetadata'}, {'key': 'EmbedThumbnail'}], 'compat_opts': set(), 'http_headers': {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.81 Safari/537.36', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'Accept-Language': 'en-us,en;q=0.5', 'Sec-Fetch-Mode': 'navigate'}}
[debug] Python 3.12.7 (CPython x86_64 64bit) - Linux-6.1.0-26-amd64-x86_64-with (OpenSSL 3.3.2 3 Sep 2024)
[debug] exe versions: ffmpeg 6.1.1 (setts), ffprobe 6.1.1
[debug] Optional libraries: Cryptodome-3.21.0, brotli-1.1.0, certifi-2024.08.30, mutagen-1.47.0, requests-2.32.3, sqlite3-3.45.3, urllib3-2.2.3, websockets-13.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1838 extractors
[youtube] Extracting URL: https://www.youtube.com/watch?v=example
[youtube] example Downloading webpage
[debug] [youtube] Extracted SAPISID cookie
[debug] [youtube] Copying __Secure-3PAPISID cookie to SAPISID cookie
[youtube] example Downloading ios player API JSON
[youtube] example Downloading mweb player API JSON
[debug] Loading youtube-nsig.2f238d39 from cache
[debug] [youtube] Decrypted nsig 
[debug] Loading youtube-nsig.2f238d39 from cache
[debug] [youtube] Decrypted nsig 
[youtube] example Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[info] example Downloading 1 format(s): 625+140
[info] Downloading video thumbnail 42 ...
[info] Writing video thumbnail 42 to: /temp/My Video Download!.webp
[ThumbnailsConvertor] Converting thumbnail "/temp/My Video Download!.webp" to png
[debug] ffmpeg command line: /usr/bin/ffmpeg -y -loglevel repeat+info -f image2 -pattern_type none -i 'file:/temp/My Video Download!.webp' -update 1 -movflags +faststart 'file:/temp/My Video Download!.png'
Deleting original file /temp/My Video Download!.webp (pass -k to keep)
[hlsnative] Downloading m3u8 manifest
[debug] Invoking hlsnative downloader on 
[download] Destination: /temp/My Video Download!.f140.m4a

[Merger] Merging formats into "/temp/My Video Download!.mp4"
[debug] ffmpeg command line: /usr/bin/ffmpeg -y -loglevel repeat+info -i 'file:/temp/My Video Download!.f625.mp4' -i 'file:/temp/My Video Download!.f140.m4a' -c copy -map 0:v:0 -map 1:a:0 -movflags +faststart 'file:/temp/My Video Download!.temp.mp4'
Deleting original file /temp/My Video Download!.f140.m4a (pass -k to keep)
Deleting original file /temp/My Video Download!.f625.mp4 (pass -k to keep)
[SponsorBlock] Fetching SponsorBlock segments
[debug] SponsorBlock query: https://sponsor.ajay.app/api/skipSegments
[SponsorBlock] Found 2 segments in the SponsorBlock database
[debug] ffprobe command line: /usr/bin/ffprobe -hide_banner -show_format -show_streams -print_format json 'file:/temp/My Video Download!.mp4'
[ModifyChapters] Removing chapters from /temp/My Video Download!.mp4
[debug] Concat spec = 0.0-254.000000, 342.000000-934.000000, 953.849000-inf
[debug] Writing concat spec to /temp/My Video Download!.temp.mp4.concat
[debug] ffmpeg command line: /usr/bin/ffmpeg -y -loglevel repeat+info -hide_banner -nostdin -f concat -safe 0 -i 'file:/temp/My Video Download!.temp.mp4.concat' -map 0 -dn -ignore_unknown -c copy -c:s mov_text -movflags +faststart 'file:/temp/My Video Download!.temp.mp4'
Deleting original file /temp/My Video Download!.uncut.mp4 (pass -k to keep)
[Metadata] Adding metadata to "/temp/My Video Download!.mp4"
[debug] ffmpeg command line: /usr/bin/ffmpeg -y -loglevel repeat+info -i 'file:/temp/My Video Download!.mp4' -i 'file:/temp/My Video Download!.meta' -map 0 -dn -ignore_unknown -c copy -map_metadata 1 -write_id3v1 1 -metadata 'title=My Video Download!' -metadata date=20240922 -metadata 'description=example' -metadata 'purl=https://www.youtube.com/watch?v=example' -metadata 'comment=https://www.youtube.com/watch?example' -metadata artist=example -metadata:s:1 language=eng -movflags +faststart 'file:/temp/My Video Download!.temp.mp4'

WARNING: Cannot update utime of file
ERROR - Error downloading: My Video Download! - [Errno 2] No such file or directory: '/temp/My Video Download!.temp.mp4' -> '/temp/My Video Download!.mp4'
```

Similar to #7542

**Comment by MattBlackOnly** [comment]
**Python Code:**

    import yt_dlp
    
    url = "https://www.youtube.com/watch?v=2Gg6Seob5Mg"
    
    ydl_opts = {
        "ignore_no_formats_error": True,
        "noplaylist": True,
        "extract_flat": True,
        "extractor_args": {"youtubetab": {"skip": ["authcheck"]}},
        "writethumbnail": True,
        "format": "bestvideo+bestaudio/best",
        "outtmpl": "%(title)s.%(ext)s",
        "updatetime": False,
        "paths": {"home": "/data", "temp": "/temp"},
        "verbose": True,
        "no_overwrites": True,
        "merge_output_format": "mp4",
        "ffmpeg_location": "D:\\",
    }
    
    ydl_opts["postprocessors"] = [
        {"key": "SponsorBlock", "categories": ["sponsor"]},
        {"key": "ModifyChapters", "remove_sponsor_segments": ["sponsor"]},
        {"key": "FFmpegThumbnailsConvertor", "format": "png", "when": "before_dl"},
        {"key": "FFmpegMetadata"},
        {"key": "EmbedThumbnail"},
    ]
    
    
    ydl = yt_dlp.YoutubeDL(ydl_opts)
    ydl.download([url])
    ydl.close()

**Comment by bashonly** [comment]
are you running this in WSL?

**Comment by MattBlackOnly** [comment]
> are you running this in WSL?

No, its running in a Docker container

**Comment by dirkf** [comment]
[Historical issue](https://github.com/ytdl-org/youtube-dl/issues/12292) was with Termux.

In this one, is it possible that the failure to set `utime` causes the temporary file (that the next step would have moved) to be removed?

**Comment by MattBlackOnly** [comment]
> [Historical issue](https://github.com/ytdl-org/youtube-dl/issues/12292) was with Termux.
> 
> In this one, is it possible that the failure to set `utime` causes the temporary file (that the next step would have moved) to be removed?

I'm not entirely sure, but it seems likely. What’s puzzling is that it works most of the time but occasionally fails. 

I suspect the problem happens during the embed metadata stage with ffmpeg, where it fails to set utime. Then somehow this causes a "file doesn't exist" error, preventing the file from being moved: -> 
https://github.com/yt-dlp/yt-dlp/blob/f4338714241b11d9d43768ae71a25f5e952f677d/yt_dlp/postprocessor/ffmpeg.py#L369-L371

---

`try_utime` is the only place that has the warning message:

https://github.com/yt-dlp/yt-dlp/blob/f4338714241b11d9d43768ae71a25f5e952f677d/yt_dlp/postprocessor/common.py#L152-L156

**Comment by bashonly** [comment]
`try_utime` is not specifically related to `--embed-metadata`, it is called on all downloads by default unless `--no-mtime` is passed

**Comment by MattBlackOnly** [comment]
> `try_utime` is not specifically related to `--embed-metadata`, it is called on all downloads by default unless `--no-mtime` is passed

I was using `updatetime: False` to use the downloaded timestamp as the `mtime`, is that incorrect?

I also just tried adding `no_mtime: True` but I'm still seeing the same issue.

**Comment by bashonly** [comment]
>  was using `updatetime: False` to use the downloaded timestamp as the `mtime`, is that incorrect?

That's correct, I had missed that. What's happening is all of the postprocessors call `try_utime` to try to preserve the original mtime (e.g. in case `updatetime` was `True`)

Could you try removing the postprocessors one-by-one to see when the problem no longer manifests?

**Comment by bashonly** [comment]
Can you also show the output of `echo $USER ; ls -ld /temp /data` from inside the container

**Comment by bashonly** [comment]
> ```
>     "ffmpeg_location": "D:\\",
> ```

BTW, :point_up: this is why I asked if you were running this on WSL, and because this issue seemed vaguely reminiscient of #8088

**Comment by MattBlackOnly** [comment]
> > ```
> >     "ffmpeg_location": "D:\\",
> > ```
> 
> BTW, ☝️ this is why I asked if you were running this on WSL, and because this issue seemed vaguely reminiscient of #8088

Apologies I was doing some testing on a windows machine, but the issue was on linux

**Comment by MattBlackOnly** [comment]
Also just changed the order to embed the metadata first and then embed thumbnail and this was the result, with the video successfully moved but without thumbnail, again this is intermittent.


WARNING: Cannot update utime of file
WARNING: Skipping embedding the thumbnail because the file is missing.
WARNING: File "/temp/My Video Download!.png" cannot be found

**Comment by MattBlackOnly** [comment]
Dockerfile:

```
FROM python:3.12-alpine

# Install dependencies, including su-exec
RUN apk update && apk add --no-cache ffmpeg su-exec

# Create appuser and appgroup
RUN addgroup -g 1000 appgroup && adduser -D -u 1000 -G appgroup appuser

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV PYTHONPATH=/app/tubetube

# Set the working directory
WORKDIR /app

# Install Python dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the application code
COPY . .

# Ensure proper ownership of /config, /data and /temp directories
RUN mkdir -p /config /data /temp && \
    chown -R appuser:appgroup /config /data /temp && \
    chmod -R 775 /temp

# Copy start script and make it executable
COPY start.sh /app/start.sh
RUN chmod +x /app/start.sh

# Expose the application port
EXPOSE 6543

# Use the start script as the entrypoint
ENTRYPOINT ["/app/start.sh"]
```

---
start.sh:
```
#!/bin/sh

# Default values for PUID and PGID
PUID=${PUID:-1000}
PGID=${PGID:-1000}

echo "Using PUID=${PUID} and PGID=${PGID}"

# Modify the appuser and appgroup to match PUID and PGID
if [ "$(id -u appuser)" != "$PUID" ] || [ "$(id -g appuser)" != "$PGID" ]; then
    echo "Updating UID and GID for appuser to match PUID:PGID..."
    deluser appuser
    addgroup -g "$PGID" appgroup
    adduser -D -u "$PUID" -G appgroup appuser
fi

# Ensure ownership of /config, /data and /temp are correct
chown -R appuser:appgroup /config /data /temp

# Start the application as appuser
exec su-exec appuser:appgroup gunicorn tubetube.tubetube:app -c gunicorn_setup.py
```

**Comment by MattBlackOnly** [comment]
> Can you also show the output of `echo $USER ; ls -ld /temp /data` from inside the container

```
/ # echo $USER ; ls -ld /temp /data

drwxr-xr-x    1 appuser  appgroup      4096 Oct 12 13:01 /data
drwxrwxr-x    1 appuser  appgroup      4096 Oct 12 13:02 /temp

```

**Comment by MattBlackOnly** [comment]
I appreciate the assistance on this

**Comment by bashonly** [comment]
> Is there a way to trim the metadata (mainly description) before embedding to test this theory?

```
--parse-metadata ":(?P<meta_description>)"
--parse-metadata ":(?P<meta_synopsis>)"
```

**Comment by MattBlackOnly** [comment]
> > Is there a way to trim the metadata (mainly description) before embedding to test this theory?
> 
> ```
> --parse-metadata ":(?P<meta_description>)" --parse-metadata ":(?P<meta_synopsis>)"
> ```

How does that look in Python code?

**Comment by MattBlackOnly** [comment]
Is this a similar issue? #11020

**Comment by bashonly** [comment]
> How does that look in Python code?

Use [`devscripts/cli_to_api.py`](https://github.com/yt-dlp/yt-dlp/blob/master/devscripts/cli_to_api.py) for this kind of thing

This:
```
--parse-metadata ":(?P<meta_description>)" --parse-metadata ":(?P<meta_synopsis>)"
```
would be equivalent to this:
```py
from yt_dlp.postprocessor.metadataparser import MetadataParserPP

ydl_opts = {
    'key': 'MetadataParser',
    'when': 'pre_process',
    'postprocessors': [{
        'actions': [
            (MetadataParserPP.interpretter, '', '(?P<meta_description>)'),
            (MetadataParserPP.interpretter,'', '(?P<meta_synopsis>)'),
        ],
    }],
}
```

**Comment by bashonly** [comment]
> Is this a similar issue? https://github.com/yt-dlp/yt-dlp/issues/11020

They both involve embedding metadata, but I don't think the cause is the same

**Comment by MattBlackOnly** [comment]
I'm not seeing this issue as much, so maybe something has been changed in the recent update. Either way, I've also added a custom post processor to trim the metadata. So hopefully the issue is resolved.

Thanks @bashonly
