### ISSUE TITLE
[vk] Wrong file timestamp

### ISSUE THREAD

**Issue by tkzv** [yt-dlp/yt-dlp#11224]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Provide a description that is worded well enough to be understood

Some formats are saved from VK.com with a wrong date.
For example, https://vk.com/video-214113807_456239495 has the date 2023-12-05. 
` yt-dlp https://vk.com/video-214113807_456239495 -f dash_webm-2+dash_webm-3` saves file with the date 2014-01-01
` yt-dlp https://vk.com/video-214113807_456239495` saves file with the current date.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://vk.com/video-214113807_456239495', '-f', 'dash_webm-2+dash_webm-3']
[debug] User config "/home/tkzv/yt-dlp.conf": ['--alias', 'tg', '--write-info-json -o "%(channel)s[%(id)s].%(ext)s"', '--alias', 'yt', '--proxy socks5h://127.0.0.1:9050']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.10.11.232837 from yt-dlp/yt-dlp-nightly-builds [f43387142] (pip)
[debug] Python 3.12.3 (CPython x86_64 64bit) - Linux-5.15.32-gentoo-r1-x86_64-AMD_FX-tm-8300_Eight-Core_Processor-with-glibc2.39 (OpenSSL 3.0.13 30 Jan 2024, glibc 2.39)
[debug] exe versions: ffmpeg 6.1.1 (fdk,setts), ffprobe 6.1.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-3021.03.16, mutagen-1.47.0, requests-2.32.3, sqlite3-3.45.3, urllib3-2.2.1, websockets-13.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1838 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.10.11.232837 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.10.11.232837 from yt-dlp/yt-dlp-nightly-builds)
[vk] Extracting URL: https://vk.com/video-214113807_456239495
[vk] -214113807_456239495: Downloading JSON metadata
[vk] -214113807_456239495: Downloading MPD manifest
[vk] -214113807_456239495: Downloading MPD manifest
[vk] -214113807_456239495: Downloading m3u8 information
[debug] Sort order given by extractor: res, source
[debug] Formats sorted by: hasvid, ie_pref, res, source, lang, quality, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, id
[info] -214113807_456239495: Downloading 1 format(s): dash_webm-2+dash_webm-3
[debug] Invoking http downloader on "https://vkvd365.okcdn.ru/?expires=1728967231840&srcIp=95.220.116.194&pr=40&srcAg=CHROME&ms=185.226.53.200&type=1&sig=Bx3uHVyqfkU&ct=21&urls=185.226.52.209&clientType=13&appId=512000384397&id=5813258947249"
[download] Destination: Трейлер ГТА 6 [-214113807_456239495].fdash_webm-2.webm
[download] 100% of    3.43MiB in 00:00:00 at 10.67MiB/s
[debug] Invoking http downloader on "https://vkvd365.okcdn.ru/?expires=1728967231840&srcIp=95.220.116.194&pr=40&srcAg=CHROME&ms=185.226.53.200&type=4&sig=zXokvDSXyXw&ct=22&urls=185.226.52.209&clientType=13&appId=512000384397&id=5813258947249"
[download] Destination: Трейлер ГТА 6 [-214113807_456239495].fdash_webm-3.webm
[download] 100% of  381.93KiB in 00:00:00 at 8.23MiB/s
[Merger] Merging formats into "Трейлер ГТА 6 [-214113807_456239495].webm"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:Трейлер ГТА 6 [-214113807_456239495].fdash_webm-2.webm' -i 'file:Трейлер ГТА 6 [-214113807_456239495].fdash_webm-3.webm' -c copy -map 0:v:0 -map 1:a:0 -movflags +faststart 'file:Трейлер ГТА 6 [-214113807_456239495].temp.webm'
Deleting original file Трейлер ГТА 6 [-214113807_456239495].fdash_webm-3.webm (pass -k to keep)
Deleting original file Трейлер ГТА 6 [-214113807_456239495].fdash_webm-2.webm (pass -k to keep)



[debug] Command-line config: ['-vU', 'https://vk.com/video-214113807_456239495']
[debug] User config "/home/tkzv/yt-dlp.conf": ['--alias', 'tg', '--write-info-json -o "%(channel)s[%(id)s].%(ext)s"', '--alias', 'yt', '--proxy socks5h://127.0.0.1:9050']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.10.11.232837 from yt-dlp/yt-dlp-nightly-builds [f43387142] (pip)
[debug] Python 3.12.3 (CPython x86_64 64bit) - Linux-5.15.32-gentoo-r1-x86_64-AMD_FX-tm-8300_Eight-Core_Processor-with-glibc2.39 (OpenSSL 3.0.13 30 Jan 2024, glibc 2.39)
[debug] exe versions: ffmpeg 6.1.1 (fdk,setts), ffprobe 6.1.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-3021.03.16, mutagen-1.47.0, requests-2.32.3, sqlite3-3.45.3, urllib3-2.2.1, websockets-13.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1838 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.10.11.232837 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.10.11.232837 from yt-dlp/yt-dlp-nightly-builds)
[vk] Extracting URL: https://vk.com/video-214113807_456239495
[vk] -214113807_456239495: Downloading JSON metadata
[vk] -214113807_456239495: Downloading MPD manifest
[vk] -214113807_456239495: Downloading MPD manifest
[vk] -214113807_456239495: Downloading m3u8 information
[debug] Sort order given by extractor: res, source
[debug] Formats sorted by: hasvid, ie_pref, res, source, lang, quality, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] -214113807_456239495: Downloading 1 format(s): url360
[debug] Invoking http downloader on "https://vkvd365.okcdn.ru/?srcIp=95.220.116.194&pr=40&expires=1729167218639&srcAg=CHROME&fromCache=1&ms=185.226.53.200&type=1&sig=ml7t_11Ghe4&ct=0&urls=45.136.22.154&clientType=13&appId=512000384397&id=5813258947249"
[download] Destination: Трейлер ГТА 6 [-214113807_456239495].mp4
[download] 100% of    6.22MiB in 00:00:00 at 10.75MiB/s
```

**Comment by bashonly** [comment]
The `upload_date` is correct:
```
$ yt-dlp --print upload_date 'https://vk.com/video-214113807_456239495'
20231204
```

You must be referring to the file's modified time set after download. This is based on the server's modified time. There is a [feature request to expand `--mtime` to use values such as `upload_date`](https://github.com/yt-dlp/yt-dlp/issues/903) and a [plugin](https://github.com/bradenhilton/yt-dlp-FixupMtime) that can do the same

**Comment by tkzv** [comment]
> The `upload_date` is correct:
> 
> ```
> $ yt-dlp --print upload_date 'https://vk.com/video-214113807_456239495'
> 20231204
> ```
> 
> You must be referring to the file's modified time set after download. This is based on the server's modified time. There is a [feature request to expand `--mtime` to use values such as `upload_date`](https://github.com/yt-dlp/yt-dlp/issues/903) and a [plugin](https://github.com/bradenhilton/yt-dlp-FixupMtime) that can do the same

Where does it get the mtime for WebM format? From the headers of media file URLs formats.3.url and formats.16.url ? Do you mean that the server reports the date for all WebM URLs as 2014-01-01 01:00:00 UTC? What is the field name to display this time with `--print`?

Thanks for the links.

**Comment by bashonly** [comment]
> Where does it get the mtime for WebM format?

From the oldest `last-modified` header value

> Do you mean that the server reports the date for all WebM URLs as 2014-01-01 01:00:00 UTC?

yes

> What is the field name to display this time with `--print`?

There isn't one
