### ISSUE TITLE
SSL: CERTIFICATE_VERIFY_FAILED ISSUE

### ISSUE THREAD

**Issue by kushiemoon-dev** [yt-dlp/yt-dlp#11229]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

France

### Provide a description that is worded well enough to be understood

Hello we normally was using Twitch for streaming DJ in clubs in vrchat. But it appear than actually a lot of people encounter issue to load stream twitch in general. I check the logs and found this line, Do someone have maybe a idea of how to fix that ? 
I have check the certificate of windows but dont find any related to vrchat,google or twitch.
Thanks by advance for the respond
Have nice day ! 
Im not the owner of most of the world and dont know them so i can't really give the -vU.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
2024.10.12 16:44:07 Error      -  [Video Playback] ERROR: [twitch:stream] doktorfroid: Failed to download m3u8 information: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131) (caused by CertificateVerifyError('[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

**Comment by bashonly** [comment]
I assume VRChat uses whichever `yt-dlp` is found in your `PATH`? How did you install yt-dlp? Executable, pip, etc? You probably needto either use the [Windows executable](https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp.exe) or else install `certifi` with pip

If that doesn't solve your problem, then you need to reproduce the issue using **yt-dlp alone** (**not** VRChat) and share **complete verbose output**

**Comment by thedarkcave215** [comment]
I'm having the same issue, but with YouTube instead. I also can't check for updates with ```yt-dlp -U```, because it throws the same issue: ```Unable to obtain version info ([SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1020));```

**Comment by bashonly** [comment]
@thedarkcave215 can you show the full output of `yt-dlp -v`

**Comment by thedarkcave215** [comment]
> @thedarkcave215 can you show the full output of `yt-dlp -v`

```[debug] Command-line config: ['-v']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.08.06 from yt-dlp/yt-dlp [4d9231208] (zip)
[debug] Python 3.13.0 (CPython arm64 64bit) - macOS-15.0.1-arm64-arm-64bit-Mach-O (OpenSSL 3.0.15 3 Sep 2024)
[debug] exe versions: ffmpeg 7.1 (setts), ffprobe 7.1, rtmpdump 2.4
[debug] Optional libraries: sqlite3-3.45.3
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Loaded 1830 extractors
```

**Comment by bashonly** [comment]
@thedarkcave215 same solution as above, but replace "Windows" with "macOS". You either need to install `certifi` with pip (since the `yt-dlp` unix zip release uses your system's Python libraries), or use the [macOS executable](https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp_macos)

Alternatively you could [install with homebrew](https://github.com/yt-dlp/yt-dlp/wiki/Installation#homebrew), which would probably make for a much better experience

**Comment by thedarkcave215** [comment]
Alright, I'll try that. What's weird is that it worked fine a few days ago.
