### ISSUE TITLE
Interpolate environment variables in --user-agent

### ISSUE THREAD

**Issue by ghost** [yt-dlp/yt-dlp#11238]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

I would like to specify my user-agent in a separate location, so that multiple programs can share it. My preferred way to do it would be to just embed an environment variable into the config file `--user-agent "${USER_AGENT}"` but this does not, currently, interpolate the variable; it sends to the server the literal string `${USER_AGENT}`.

This is similar to #4938, although the fix there also passes through expanduser which is not desirable here.

Or if there's some other way to get the contents of a file or an environment variable into the user agent, that would work too.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'http://example.com']
[debug] User config "/home/user/.config/yt-dlp/config": ['-o', '%(channel,uploader)s [%(webpage_url_domain)s %(channel_id,uploader_id)s]/%(title)s [%(extractor)s %(id)s].%(ext)s', '--download-archive', '/home/jrunyon/.config/yt-dlp/download-archive.txt', '--write-info-json', '--compat-options', 'no-keep-subs', '--write-subs', '--embed-subs', '--no-write-auto-subs', '--sub-langs', 'en,en.*,en-orig', '--sub-format', 'srt/ass/best', '--embed-chapters', '--xattrs', '--sponsorblock-mark', 'sponsor,selfpromo,preview', '--user-agent', '${USER_AGENT}']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8 (No ANSI), error utf-8 (No ANSI), screen utf-8 (No ANSI)
[debug] yt-dlp version local@2024.10.13 [d710a6ca7]
[debug] Compatibility options: no-keep-subs
[debug] Python 3.12.6 (CPython x86_64 64bit) - Linux-6.6.38-nope (OpenSSL 3.3.2 3 Sep 2024, glibc 2.39)
[debug] exe versions: ffmpeg 6.1.1 (setts), ffprobe 6.1.1
[debug] Optional libraries: certifi-3024.7.22, mutagen-1.47.0, pycrypto-3.20.0, requests-2.32.3, secretstorage-3.3.3, sqlite3-3.46.1, urllib3-2.2.3
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Loaded 1838 extractors
[debug] Loading archive file '/home/user/.config/yt-dlp/download-archive.txt'
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.10.07 from yt-dlp/yt-dlp
yt-dlp is up to date (local@2024.10.13)
[generic] Extracting URL: http://example.com
[generic] example: Downloading webpage
[redirect] Following redirect to http://example.com/
[generic] Extracting URL: http://example.com/
[generic] example: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] example: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: http://example.com/
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 1626, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/yt_dlp/YoutubeDL.py", line 1761, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/yt_dlp/extractor/common.py", line 741, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/yt_dlp/extractor/generic.py", line 2533, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: http://example.com/
```

**Comment by bashonly** [comment]
you'll have to use an external script or shell alias/function
