### ISSUE TITLE
Include playlist information in --flat-playlist json output

### ISSUE THREAD

**Issue by Earnestly** [yt-dlp/yt-dlp#11234]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

```
[debug] Command-line config: ['-vU']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8 (No ANSI), error utf-8 (No ANSI), screen utf-8 (No ANSI)
[debug] yt-dlp version stable@2024.10.07 from yt-dlp/yt-dlp [1a176d874]
[debug] Python 3.12.6 (CPython x86_64 64bit) - Linux-6.10.10-arch1-1-x86_64-with-glibc2.40 (OpenSSL 3.3.2 3 Sep 2024, glibc 2.40)
[debug] exe versions: ffmpeg 7.0.2 (setts), ffprobe 7.0.2
[debug] Optional libraries: Cryptodome-3.20.0, brotlicffi-1.1.0.0, certifi-2024.08.30, mutagen-1.47.0, requests-2.32.3, sqlite3-3.46.1, urllib3-1.26.20, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Loaded 1838 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.10.07 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.10.07 from yt-dlp/yt-dlp)
```

Currently yt-dlp only includes `playlist_` entries in `-J`, `--dump-single-json` output when `--flat-playlist` is *not* used.

I would like yt-dlp to include the `playlist_` keys [[1]](https://github.com/yt-dlp/yt-dlp/blob/master/yt_dlp/YoutubeDL.py#L1942) when `--flat-playlist` is used (when relevant) so that hopefully mpv might be able to incorporate that information into its metadata. Then I can extract this information for my logging; currently I have to call yt-dlp again to aquire the information when it should be possible once.

This would also mean that when `--flat-playlist` is used the title of the playlist will be behind `playlist_title` rather than `title`.

**Comment by bashonly** [comment]
Not sure I understand... the playlist's metadata (id, title, etc) is in the root of the JSON. Why can this not be used?

**Comment by Earnestly** [comment]
My understanding is that the issue is with the key `title` for an individual playlist entry conflicting with the key `title` when used for the playlist itself.  When new metadata reflects a new entry loading the `title` of the playlist is overwritten with the `title` of the entry.

This theory may be incorrect though as I found it difficult to observe propety changes indicating it.

If the keys were named with their `playlist_` prefixes it would [allow mpv](https://github.com/mpv-player/mpv/blob/master/player/lua/ytdl_hook.lua#L61-L70) to retain these values and so make them available to `mp.get_property[_native]`. (It may also somewhat better conforms to the documentation/README which suggests the title to be `playlist_title`).

**Comment by bashonly** [comment]
It's not overwritten though? e.g.:

```json
{
    "title": "this is the playlist title",
    "entries": [{
        "title": "this is the 1st entry's title"
    }]
}

**Comment by Earnestly** [comment]
With `--flat-playlist` those entries are obviated:

```
~ yt-dlp -J -I 1:1 --flat-playlist -- 'https://www.youtube.com/@3Blue1Brown/videos' | jq -rf ~jq/ls.jq | grep -F .playlist_
.playlist_count = null

~ yt-dlp -J -I 1:1 -- 'https://www.youtube.com/@3Blue1Brown/videos' | jq -rf ~jq/ls.jq | grep -F .playlist_
.playlist_count = null
.entries[0].playlist_count = null
.entries[0].playlist_id = "UCYO_jab_esuFRV4b17AJtAw"
.entries[0].playlist_title = "3Blue1Brown - Videos"
.entries[0].playlist_uploader = "3Blue1Brown"
.entries[0].playlist_uploader_id = "@3blue1brown"
.entries[0].playlist_channel = "3Blue1Brown"
.entries[0].playlist_channel_id = "UCYO_jab_esuFRV4b17AJtAw"
.entries[0].playlist_index = 1
.entries[0].playlist_autonumber = 1
```

I'm not 100% sure what the issue is that ytdl_hook.lua is having, but at least with `--flat-playlist` this information is apparently missing.

**Comment by bashonly** [comment]
per my example they are not prefixed with `playlist_`

**Comment by Earnestly** [comment]
I believe that is exactly the issue, that they are not prefixed.

**Comment by bashonly** [comment]
...because they are in a diffferent path in the JSON

**Comment by Earnestly** [comment]
Yes exactly, so code would have to specifically regard the differences.

If the playlist title were keyed on `playlist_title` then code can simply use that instead of trying to determine if the `title` is the title or the playlist title based on location.

The documentation for yt-dlp also tells us that the playlist title is called `playlist_title`, regardless of the path, which is apparently what mpv followed when writing ytdl_hook. Therefore they don't really believe this is an mpv issue.

Do you have any suggestions perhaps?

**Comment by bashonly** [comment]
> `--flat-playlist` tells yt-dlp to not resolve and process the playlist's entries further. "Processing" the entries is where the `playlist_`-prefixed convenience fields are added

Expanding on this: the `playlist_`-prefixed convenience fields are added so that the user has access to the playlist metadata at the `video` stage (vs. the `playlist` stage). The `video` stage is never reached when `--flat-playlist` is passed; yt-dlp only ever processes the playlist(s), never its video entries. So there's no point to this

**Comment by bashonly** [comment]
> The documentation for yt-dlp also tells us that the playlist title is called `playlist_title`

The [**OUTPUT TEMPLATE** section of the readme](https://github.com/yt-dlp/yt-dlp?tab=readme-ov-file#output-template) tells you that there is a `playlist_title` field available. This is the only place where the field is documented. It is intended to be used in output templates (`-o`).

**Comment by bashonly** [comment]
> Do you have any suggestions perhaps?

Only if you can provide more information on what you're actually trying to accomplish; links to relevant code, feature proposals, mpv issues, etc. I am still failing to see why the current JSON output is insufficient

**Comment by Earnestly** [comment]
There aren't any mpv issues as yet since it was only irc discussion.

My goal is to ultimately access the playlist title from mpv's metadata property which itself is populated by the ytdl_hook.

The reason for this goal is that I'm attempting to capture a bit more metadata about the video/media when saving state on exit; this includes the path, titles, artists, etc. which is stored in a database that can be queried later (i.e. dmenus).

This is especially important for playlists (mostly youtube playlists) as I want to store the playlist title along with the title of the saved video (and perhaps position). Currently it is difficult to reconstruct this relationship using the current `watch_later` infrastructure, see https://github.com/mpv-player/mpv/pull/13476 (although this approach is worse than the script below, so I'm not inclined on them accepting this PR).

I've written a bit of a quick script as a bit of a prototype which you can read in full here:

<details>
<summary> <code>watchlater.lua</code></summary>

```lua

local utils = require "mp.utils"

local data = {
    timestamp = 0,
    live = false,
    path = "",
    playlist_path = "",
    playlist_title = "",
    playlist_position = 1,
    playlist_count = 1,
    author = "",
    title = ""
}

local function bool(str)
    if str == "true" then
        return true
    else
        return false
    end
end

-- XXX Unnecessary if switching to json.
local function tabs_to_spaces(str)
    if str == nil then
        return
    else
        return string.gsub(str, "\t", "    ")
    end
end

local function url_encode_filename(path)
    -- XXX Not happy with this cargo-cult. If using json, despite it requiring
    --     UTF-8, I will probably drop this.
    path = path:gsub(" ", "+")
    path = path:gsub("([^%w /_%%%-%.~])", function(m) return string.format("%%%02x", string.byte(m)) end)

    if string.find(path, "/") ~= 1 then
        -- Ensure paths are absolute where possible.
        path = utils.getcwd() .. "/" .. path
    end

    return "file://" .. path
end

local function super_quit_watch_later_helper(metadata)
    data.title = tabs_to_spaces(mp.get_property("media-title"))

    -- If no title was found mpv probably fell back to a filename, try to
    -- extract the basename as the title. (It may not be the best place to do
    -- this.)
    if data.title and utils.file_info(data.title) then
        _, data.title = utils.split_path(data.title)
    end

    data.author = tabs_to_spaces(metadata.artist)

    if data.author == nil then
        data.author = tabs_to_spaces(metadata.uploader)
    end

    data.path = mp.get_property("path")

    if data.path and utils.file_info(data.path) then
        data.path = url_encode_filename(data.path)
    end

    -- XXX Local playlists could consist of a bunch of paths given to mpv. This
    --     sort of playlist should/could(?) not really be supported.
    data.playlist_path = mp.get_property("playlist-path")

    if data.playlist_path then
        data.playlist_position = mp.get_property("playlist-pos-1")
        data.playlist_count = mp.get_property("playlist-count")

        -- XXX Might be better to compare playlist-path/path to stream-path or
        --     even check if ytdl_hook was used for this as some urls can point
        --     simply to a video file which would not use ytdl.
        if data.playlist_path:match("^https://") then
            mp.osd_message("Attempting to determine the playlist title (yt-dlp#11234)", 10)

            -- XXX Does not appear to be accessible from mpv.
            --     https://github.com/yt-dlp/yt-dlp/issues/11234
            local r = mp.command_native({
                name = "subprocess",
                args = {"yt-dlp", "-JI", "1:1", "--flat-playlist", "--", data.playlist_path},
                capture_stdout = true
            })

            if r.status == 0 then
                local stdout = utils.parse_json(r.stdout)
                data.playlist_title = tabs_to_spaces(stdout.title)
            end
        end

        if utils.file_info(data.playlist_path) then
            data.playlist_path = url_encode_filename(data.playlist_path)
        end
    end

    data.live = bool(metadata.ytdl_is_live)

    -- XXX A bit annoying this.
    if data.live and data.path:match("^https://www.twitch.tv") then
        data.title = tabs_to_spaces(metadata.ytdl_description)
    end

    local file = mp.command_native({"expand-path", "~~state/super-watch-later"})

    local fh, err = io.open(file, 'a')

    if fh == nil then
        msg.error(string.format("watchlater: error: %s: %s\n", file, err))
        return
    end

    -- XXX local socket = require "socket"
    --     socket.gettime()?
    data.timestamp = os.time()

    -- XXX Experiment
    -- local result = mp.get_property_native("user-data/mpv/ytdl/json-subprocess-result")
    -- local json = result.stdout
    -- fh:write(json)

    fh:write(string.format(
        "%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\n",
        data.timestamp,
        data.path,
        data.playlist_path,
        data.playlist_position,
        data.playlist_count,
        data.live,
        data.author,
        data.playlist_title,
        data.title))

    -- fh:write(utils.format_json(data))

    fh:close()

    mp.command("quit-watch-later")
end

local function super_quit_watch_later()
    mp.observe_property("metadata", "native", function(_, metadata)
        if metadata then
            super_quit_watch_later_helper(metadata)
        else
            mp.osd_message("Waiting for metadata to become available", 10)
        end
    end)
end

mp.register_script_message("super-quit-watch-later", super_quit_watch_later)
```

</details>

As you can perhaps see the playlist title is not available which is resulting in me having to call `yt-dlp` again in order to obtain it, which is a tad slow. When asking mpv about this they were concerned about `playlist_title` being missing, so I am here following up on the leads.

If you have any suggestions I'm all for it, I can provide whatever detail you think I may have left out.

**Comment by bashonly** [comment]
what about using `-I0` instead of `--flat-playlist -I1:1` ?

**Comment by Earnestly** [comment]
That seems like a nice improvement; updated. I didn't realise that was possible.

**Comment by bashonly** [comment]
In mpv's `ytdl_hook` you can access the playlist title as `json["title"]` anywhere in this code path:

https://github.com/mpv-player/mpv/blob/228f38606ba03b2871567de75c1df4ff6bb61d09/player/lua/ytdl_hook.lua#L1073-L1194

**Comment by Earnestly** [comment]
> In mpv's `ytdl_hook` you can access the playlist title as `json["title"]` anywhere in this code path:
> 
> https://github.com/mpv-player/mpv/blob/228f38606ba03b2871567de75c1df4ff6bb61d09/player/lua/ytdl_hook.lua#L1073-L1194

This seems promising. I've copied the hook over and made some local changes. While I can print the result of `json["title"]`, I am having a bit of difficulty adding to the metadata as it is not yet available in that particular code path. Trying to add this as `json["playlist_title"] = json["title"]` hoping the other code paths pick up the json but no such luck. I may make an mpv issue and cross-reference it soon.
`

**Comment by bashonly** [comment]
> Trying to add this as json["playlist_title"] = json["title"] hoping the other code paths pick up the json but no such luck. I may make an mpv issue and cross-reference it soon.

I think you'd have to iterate through `json.entries` and add `playlist_title` to each entry

**Comment by Earnestly** [comment]
> I think you'd have to iterate through `json.entries` and add `playlist_title` to each entry

Yes, I tried this approach but didn't have much luck. I did however get something working, which I can explain.

It appears that when a playlist url is given to ytdl_hook it will iterate through the entries and build an M3U playlist in memory.

Now that a playlist is available mpv will open each stream and so trigger the `run_ytdl_hook` once again.

In this instance of `run_ytdl_hook` the `if json["direct"] then` branch fails, as does the `elseif` and then runs the `else` branch with `add_single_video(json)`. However the json is local to `run_ytdl_hook` and so is lost.

What I have done is to create a local object/string to the entire script that is then updated in the code path you mentioned. This is what it does:

``` diff
--- a/ytdl_hook.lua      2024-10-14 22:28:23.158995797 +0100
+++ b/ytdl_hook.lua      2024-10-14 22:36:43.038116649 +0100
@@ -27,6 +27,7 @@
 
 local chapter_list = {}
 local playlist_cookies = {}
+local playlist_title = ""
 
 local function Set (t)
     local set = {}
@@ -1065,6 +1066,10 @@
 
     json["proxy"] = json["proxy"] or proxy
 
+    if playlist_title then
+        json["playlist_title"] = playlist_title
+    end
+
     -- what did we get?
     if json["direct"] then
         -- direct URL, nothing to do
@@ -1079,6 +1084,8 @@
             return
         end
 
+        playlist_title = json["title"]
+
         local self_redirecting_url =
             json.entries[1]["_type"] ~= "url_transparent" and
             json.entries[1]["webpage_url"] and
```

I don't know if this is a particularly good idea.

**Comment by bashonly** [comment]
if that's the approach you want to take then I think it would make more sense to add the `playlist_title` in the `else` path directly below, since `direct` results will never be part of a playlist
```lua
    else -- probably a video
        if playlist_title then
            json["playlist_title"] = playlist_title
        end
        add_single_video(json)
```

**Comment by Earnestly** [comment]
Fair comment. I'm not sure it's what mpv will accept but opened as a PR to see can be done.

**Comment by bashonly** [comment]
Something else worth noting is that not every playlist has a `title` (e.g. sites other than Youtube); the key won't even exist

**Comment by Earnestly** [comment]
Yes, I doubt this PR would be accepted as-is because it also doesn't account for all the other potential `ytdl_` keys that would otherwise be available.
It seems like any approach to this comes across as a bit of a bodge because it is essentially having to resupply all the metadata yt-dlp should, perhaps, have provided.

**Comment by bashonly** [comment]
> It seems like any approach to this comes across as a bit of a bodge because it is essentially having to resupply all the metadata yt-dlp should, perhaps, have provided.

I've already explained why yt-dlp should **not** provide these `playlist_`-prefixed *convenience* fields for `--flat-playlist` results. Please re-read my earlier comments if this is still not clear. The metadata IS made available by yt-dlp, and IS available to mpv, it's just not in the JSON path where you want it to be. Closing this since the discussion is now going in circles

**Comment by Earnestly** [comment]
Yes, I understood the reasoning although I don't quite agree with it.

**Comment by bashonly** [comment]
Just following up on this after having another think about it:

Maybe I'm making an incorrect assumption about how mpv handles yt-dlp playlists, but first it extracts the playlist URL with `--flat-playlist`, and then when an entry is reached during playback, that entry's `webpage_url` is then (fully) extracted, correct? This would mean that the original `--flat-playlist` entry information is forgotten about anyways. So I don't think setting `playlist_title` in a flat playlist result would even be helpful (if I'm right about how the ytdl_hook works)

**Comment by Earnestly** [comment]
Yes, you might make a good point about the information being lost such that even `yt-dlp` could not help me here.

I think the approach of associating urls with playlist entries might be sufficient but I still wonder if there is a way to better delineate between playlist entries and non-playlist entries in an environment where there might be playlists-within-playlists including single videos sprinked amongst them. (There may not be a way.)

**Comment by bashonly** [comment]
Looks like you got it sorted out. Nice work

Closing as completed by https://github.com/mpv-player/mpv/commit/9f6cca624f8e58dc8716975372ff1c8a4ac98d0e

**Comment by Earnestly** [comment]
Thank you for your comments as well.
