### ISSUE TITLE
Add Spleeter functionality to extract and remove background music from videos

### ISSUE THREAD

**Issue by Iliannnn** [yt-dlp/yt-dlp#11239]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

It would be awesome if yt-dlp had the ability to process downloaded videos and remove or isolate background music. This feature could integrate Spleeter. It can separate vocals and music into different stems, and it would be super helpful for anyone wanting to extract vocals from videos or remove the background music altogether.

The main use-case would be downloading videos and then applying Spleeter to remove or isolate the background music. This feature could be particularly useful for creators and editors working with downloaded content, giving them more flexibility with the audio tracks.

Integrating this functionality directly into yt-dlp would save users from the need for a separate post-processing step. It would make the workflow more seamless and efficient.

```
yt-dlp https://example.com/video-url --spleeter 2stems
```

This command would download the video, process the audio using Spleeter, and then separate it into two stems: vocals and background music. The user could choose whether to keep both, or only the isolated vocals, for instance.

* This functionality could be optional and controlled by a flag (e.g., `--spleeter 2stems` for vocals + music, `--spleeter 4stems` for more detailed separation).
* There could also be an option to remove the background music and leave only the vocal track.
* Users would need to have Spleeter installed, but yt-dlp could check for the dependency and notify users if it's missing.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
This can be done like so:

```
--exec "spleeter separate -p spleeter:2stems -o spleeter_output"
```

Or you can create a `--spleeter` alias by adding this to your config file:

```
--alias spleeter '--exec "spleeter separate -p spleeter:2stems -o spleeter_output"'
```

**Comment by bashonly** [comment]
IMO any more integrated functionality than my above example is out-of-scope for yt-dlp. But it would make for a good postprocessor plugin
