### ISSUE TITLE
[Site Request] tagesschau.de

### ISSUE THREAD

**Issue by AxelSchwarz** [yt-dlp/yt-dlp#1124]
## Checklist

- [ x] I'm reporting a new site support request
- [ x] I've verified that I'm running yt-dlp version **2021.09.25**
- [ x] I've checked that all provided URLs are alive and playable in a browser
- [ x] I've checked that none of provided URLs violate any copyrights
- [ x] The provided URLs do not contain any DRM to the best of my knowledge
- [ x] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

- Single video: https://www.tagesschau.de/multimedia/video/video-924833.html
- Single video: https://www.tagesschau.de/multimedia/sendung/ts-45041.html
- Playlist: https://www.tagesschau.de/100sekunden/index.html

## Description

German news from ARD (public service broadcaster)

**Comment by poschi3** [comment]
There is [already an extractor](https://github.com/yt-dlp/yt-dlp/commits/master/yt_dlp/extractor/tagesschau.py). Unfortunately it's broken at the moment.
