### ISSUE TITLE
Unique undownloadable YouTube video ([WinError 31] A device attached to the system is not functioning)

### ISSUE THREAD

**Issue by DevanWolf** [yt-dlp/yt-dlp#11243]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United States

### Provide a description that is worded well enough to be understood

I am trying to download [Casio LK-78CD: Casio LK-280CDTV Option Discs Showcase](https://youtu.be/WB4FglhHLA0) by Gabriel Miceli so that I can listen to it offline, but this video is so unique that makes it undownloadable on Windows due to a storage access bug. Same problem using the other format codes. The other videos download fine.
I had to instead use NewPipe on an Android device to download it.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp -vU https://youtu.be/WB4FglhHLA0 -f140
[debug] Command-line config: ['-vU', 'https://youtu.be/WB4FglhHLA0', '-f140']
[debug] Failed to enable VT mode: SetConsoleMode failed
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8 (No VT), error utf-8 (No VT), screen utf-8 (No VT)
[debug] yt-dlp version stable@2024.10.07 from yt-dlp/yt-dlp [1a176d874] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22631-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 5.1.2-essentials_build-www.gyan.dev (setts), ffprobe 5.1.2-essentials_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.21.0, brotli-1.1.0, certifi-2024.08.30, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.3, websockets-13.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1838 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.10.07 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.10.07 from yt-dlp/yt-dlp)
[youtube] Extracting URL: https://youtu.be/WB4FglhHLA0
[youtube] WB4FglhHLA0: Downloading webpage
[youtube] WB4FglhHLA0: Downloading ios player API JSON
[youtube] WB4FglhHLA0: Downloading mweb player API JSON
[debug] [youtube] Extracting signature function js_2f238d39_109
[debug] Loading youtube-sigfuncs.js_2f238d39_109 from cache
[debug] Loading youtube-nsig.2f238d39 from cache
[debug] [youtube] Decrypted nsig -CpcY-NsCMvLUmT => hDke-SOiV2F0uQ
[debug] Loading youtube-nsig.2f238d39 from cache
[debug] [youtube] Decrypted nsig JJR1fvlqLlltkbs => qWUc7Ht8OjgCdg
[youtube] WB4FglhHLA0: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[info] WB4FglhHLA0: Downloading 1 format(s): 140
[debug] Invoking http downloader on "https://rr4---sn-5pgnugx5h-hn2z.googlevideo.com/videoplayback?expire=1728889291&ei=a20MZ7HQJZKxzN0PsZHjqQ4&ip=173.245.130.58&id=o-AO7C2uT1TZD-BCsrm5AOEakH-Wdh35ZYRtYDyhI9yGms&itag=140&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&met=1728867691%2C&mh=Ko&mm=31%2C29&mn=sn-5pgnugx5h-hn2z%2Csn-vgqsrnek&ms=au%2Crdu&mv=m&mvi=4&pl=20&rms=au%2Cau&initcwndbps=1210000&vprv=1&svpuc=1&mime=audio%2Fmp4&rqh=1&gir=yes&clen=376631873&dur=23271.989&lmt=1703826692554584&mt=1728867414&fvip=2&keepalive=yes&fexp=51300760&c=IOS&txp=6218224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cvprv%2Csvpuc%2Cmime%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRQIhAOuf8JzxMcY3FM4RHoF7aS5xL4pOaDgYpB9GESJ6jI6GAiADUaExde1gd8-FSsTgU0w1LewmHOwCwGv4CPbJ5U13hw%3D%3D&lsparams=met%2Cmh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Crms%2Cinitcwndbps&lsig=ACJ0pHgwRAIgGPbmvHi-oguJo8pUfkjREPLKLPEChs0ssax2jIwX8sACICo5-XR8qf_kadAHEwHGOZh-MjEClzE9frJlJcrFfpCj"
[debug] File locking is not supported. Proceeding without locking
ERROR: unable to open for writing: [WinError 31] A device attached to the system is not functioning
Traceback (most recent call last):
  File "yt_dlp\downloader\http.py", line 269, in download
  File "yt_dlp\downloader\common.py", line 293, in report_destination
  File "yt_dlp\downloader\common.py", line 115, in to_screen
  File "yt_dlp\YoutubeDL.py", line 943, in to_screen
  File "yt_dlp\YoutubeDL.py", line 924, in _write_string
  File "yt_dlp\utils\_utils.py", line 1442, in write_string
PermissionError: [WinError 31] A device attached to the system is not functioning

ERROR: Unable to download video: [WinError 31] A device attached to the system is not functioning
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 3483, in process_info
  File "yt_dlp\YoutubeDL.py", line 3203, in dl
  File "yt_dlp\downloader\common.py", line 467, in download
  File "yt_dlp\downloader\common.py", line 308, in _finish_multiline_status
  File "yt_dlp\minicurses.py", line 134, in wrapper
  File "yt_dlp\minicurses.py", line 174, in end
  File "yt_dlp\minicurses.py", line 102, in write
  File "yt_dlp\utils\_utils.py", line 1442, in write_string
PermissionError: [WinError 31] A device attached to the system is not functioning

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1626, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1782, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1841, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 3015, in process_video_result
  File "yt_dlp\YoutubeDL.py", line 179, in wrapper
  File "yt_dlp\YoutubeDL.py", line 3495, in process_info
yt_dlp.utils.UnavailableVideoError: Unable to download video: [WinError 31] A device attached to the system is not functioning

Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
PermissionError: [WinError 31] A device attached to the system is not functioning
```

**Comment by Elite** [comment]
Looks like a file permission error, see - https://stackoverflow.com/questions/77449624/python-permissionerror-winerror-31-a-device-attached-to-the-system-is-not-fun

**Comment by dirkf** [comment]
Or perhaps the default filename, according to `--windows-filenames`, is `Casio LK-78CD： Casio LK-280CDTV Option Discs Showcase [WB4FglhHLA0].mkv` which might look like a strangely named and indeed "not functioning" device `Casio LK-78CD`.

What happens on the same system with `--restrict-filenames`, which proposes `Casio_LK-78CD_-_Casio_LK-280CDTV_Option_Discs_Showcase-[WB4FglhHLA0].mkv`?

**Comment by Grub4K** [comment]
The device thats mentioned here is stderr, which is why the error happens in `write_string`. Thats probably also related to why VT cannot be enabled.

I'm at a loss as to why thats the case though. How are you invoking yt-dlp? Are you using Windows Terminal, conhost, ...? Is there anything special about your setup?

**Comment by gamer191** [comment]
Have you currently got this checkbox enabled? https://stackoverflow.com/a/44574463

**Comment by dirkf** [comment]
The weirdness is that the failing line seems to be flushing the buffer to which the proposed filename, **encoded with the option to `ignore` errors**, has just been written. **If** this specific video is failing, some characteristic of that filename must be responsible.

**Comment by Grub4K** [comment]
Encoding with the option to ignore errors does not make a difference if the encoding does not match up with the expected one due to the encoding fallback. There it encodes the bytes just fine but then writes the bytes with a non matching encoding which can cause a mismatch. In this case it will fallback to utf8 and then write a multi byte sequence. If the device does not support non ascii characters, or does not support multi byte sequences, or does not like wide characters, ... then this can fail regardless of the encoding option being set to ignore

**Comment by dirkf** [comment]
Exactly, the weirdness is that the extensive attempts in the function to select a valid encoding are failing; also that the Python IO library doesn't reveal this until `.flush()`.

Last resort?
```diff
-    buffer.write(s.encode(enc, 'ignore') if enc else s)
-    out.flush()
+    for _ in range(2):
+        try:
+            buffer.write(s.encode(enc, 'ignore') if enc else s)
+            out.flush()
+        except OSError:
+            # only if not enc?
+            enc = 'ascii'
+            continue
```

**Comment by DevanWolf** [comment]
[I have spotted another undownloadable video!](https://youtu.be/qOs8ababcto)

**Comment by Grub4K** [comment]
I cannot reproduce at all, I think it has to be something with your setup. Please answer the previous questions

> How are you invoking yt-dlp? Are you using Windows Terminal, conhost, ...? Is there anything special about your setup?
