### ISSUE TITLE
Add oqee.tv

### ISSUE THREAD

**Issue by nara20** [yt-dlp/yt-dlp#11285]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a site-specific feature
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

France

### Example URLs

https://oqee.tv/replay/3132112/play

### Provide a description that is worded well enough to be understood

yt-dlp.exe https://oqee.tv/replay/3132112/play
[generic] Extracting URL: https://oqee.tv/replay/3132112/play
[generic] play: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] play: Extracting information
ERROR: Unsupported URL: https://oqee.tv/replay/3132112/play

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp.exe -vU
[debug] Command-line config: ['-vU']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.10.07 from yt-dlp/yt-dlp [1a176d874] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22631-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.21.0, brotli-1.1.0, certifi-2024.08.30, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.3, websockets-13.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1838 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.10.07 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.10.07 from yt-dlp/yt-dlp)
```

**Comment by bashonly** [comment]
More information is needed.

No video loads in my browser. Do you need to be logged in to watch videos? If so, is there free content or is everything paywalled? If not, am I geo-blocked?

Do videos play in your browser when [DRM is disabled](https://github.com/yt-dlp/yt-dlp/issues/4062#issuecomment-1153474056)?

You need to share the complete verbose output of your attempt to download the example URL you are requesting support for; not just the output of `yt-dlp -vU` alone (which is meaningless). And if the site requires you to log in to watch videos, then you need to show of log where you have [passed cookies to yt-dlp](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp)

**Comment by pukkandan** [comment]
Closed due to inactivity

**Comment by krodelabestiole** [comment]
It is indeed geoblocked and behind a paywall since it a TV and TV replay service provided by an ISP (named _Free_, but not free in any way).
I think it's also all DRMed.

I will have a look at the command line return later on.
