### ISSUE TITLE
How to parse the artists metadata array as a single string separated by comma?

### ISSUE THREAD

**Issue by zaednasr** [yt-dlp/yt-dlp#11287]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

In some youtube music songs, there is no artist tag but artists tag. Json dump considers this an array of strings, but is there a way to parse the metadata to make it human readable separated by commas?

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp --print "%(artists)s" "https://music.youtube.com/watch?v=GCpo61azoYE&si=Nr9NbTqU5Z0isqoY"
['Mayumi Fujita', '田中怜子', 'ATLUS']
```

**Comment by bashonly** [comment]
`%(artists)l`

**Comment by bashonly** [comment]
see [**7. More Conversions**](https://github.com/yt-dlp/yt-dlp?tab=readme-ov-file#output-template)
