### ISSUE TITLE
Requested format is not available. Use --list-formats for a list of available formats

### ISSUE THREAD

**Issue by khsinat** [yt-dlp/yt-dlp#11295]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

I am using this code to download playlists
```shell
 yt-dlp -o "%(playlist)s/%(playlist_index)s - %(title)s.%(ext)s" "URL" -f 'bv*[height=720]+ba'
``` 
it works sometimes but for some videos it doesn't and shows this
```
ERROR: [youtube] 9twcmtQj4DU: Requested format is not available. Use --list-formats for a list of available formats
``` 
so i add this   ```-S vcodec:h264,res,acodec:aac``` 
so it becomes 
```
 yt-dlp -o "%(playlist)s/%(playlist_index)s - %(title)s.%(ext)s" -S vcodec:h264,res,acodec:aac "URL" 'bv*[height=720]+ba'
```
but this doesn't work and downloads any video quality
i want something like this which allows me to download a playlist with quality of my choice (example: 720p) 

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
Extracting URL: 
[youtube] OJX1umVCsJc: Downloading webpage
[youtube] OJX1umVCsJc: Downloading ios player API JSON
[youtube] OJX1umVCsJc: Downloading mweb player API JSON
[youtube] OJX1umVCsJc: Downloading m3u8 information
ERROR: [youtube] OJX1umVCsJc: Requested format is not available. Use --list-formats for a list of available formats
```

**Comment by seproDev** [comment]
Drop the `-f` and only use `-S vcodec:h264,res:720,acodec:aac`.
The problem is that for the video 9twcmtQj4DU, no video stream with a height of exactly 720 pixels exists. `-f` is strict with what format should be used, while `-S` just sorts the formats so it prefers the highest resolution, that is 720p or below.

**Comment by khsinat** [comment]
Thank you this works

**Comment by HYJ-creator** [comment]
the command i use is "
command = [
        "yt-dlp",
        "--cookies", "cookies.txt",
        "--quiet",
        "--no-warnings",
        "--force-keyframes-at-cuts",
        "-x",
        "--audio-format", "wav",
        "-f", "bestaudio",
        "-o", str(output_path),
        "--download-sections", f"*{start_time}-{end_time}",
        f"https://www.youtube.com/watch?v={video_id}"
    ]"
when i run "python .\Download.py", i miss thie error
{'ytid': '-0Gj8-vB1q4', 'start_s': 30, 'end_s': 40, 'audioset_positive_labels': '/m/0140xf,/m/02cjck,/m/04rlf', 'aspect_list': "['low quality', 'sustained strings melody', 'soft female vocal', 'mellow piano melody', 'sad', 'soulful', 'ballad']", 'caption': 'The low quality recording features a ballad song that contains sustained strings, mellow piano melody and soft female vocal singing over it. It sounds sad and soulful, like something you would hear at Sunday services.', 'author_id': 4, 'is_balanced_subset': False, 'is_audioset_eval': True}
[1] 下载: -0Gj8-vB1q4 -> musiccaps_data\-0Gj8-vB1q4.wav
ERROR: [youtube] -0Gj8-vB1q4: Requested format is not available. Use --list-formats for a list of available formats
