### ISSUE TITLE
 Video not available, status code 10204;

### ISSUE THREAD

**Issue by cherry899** [yt-dlp/yt-dlp#11308]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I already updated the latest version but it still have error about version:

(tiktok) lichengzhang@local:~/zsh$ yt-dlp https://www.tiktok.com/@nhotnews/video/7406254501511925010
[TikTok] Extracting URL: https://www.tiktok.com/@nhotnews/video/7406254501511925010
[TikTok] 7406254501511925010: Downloading webpage
ERROR: [TikTok] 7406254501511925010: Video not available, status code 10204; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
(tiktok) lichengzhang@local:~/zsh$ yt-dlp -U
Latest version: nightly@2024.10.20.232914 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.10.20.232914 from yt-dlp/yt-dlp-nightly-builds)

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by cherry899** [comment]
sorry, It's ok now

**Comment by RoninReilly** [comment]
> sorry, It's ok now

How u fixed it?
