### ISSUE TITLE
[tiktok] Failed to fetch video or user detail

### ISSUE THREAD

**Issue by RichardReallyHard** [yt-dlp/yt-dlp#11303]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

all

### Provide a description that is worded well enough to be understood

failed to fetch video detail nor user detail. video is downloadable using other online downloader.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--', 'https://vt.tiktok.com/ZSjekG1vo/']
[debug] Encodings: locale cp950, fs utf-8, pref cp950, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.10.20.232914 from yt-dlp/yt-dlp-nightly-builds [87408ccfd] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 2022-02-10-git-b6bb6b9f22-essentials_build-www.gyan.dev (setts), ffprobe 2022-02-10-git-b6bb6b9f22-essentials_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.21.0, brotli-1.1.0, certifi-2024.08.30, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.3, websockets-13.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1839 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.10.20.232914 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.10.20.232914 from yt-dlp/yt-dlp-nightly-builds)
[vm.tiktok] Extracting URL: https://vt.tiktok.com/ZSjekG1vo/
[vm.tiktok] ZSjekG1vo: Downloading webpage
[TikTok] Extracting URL: https://www.tiktok.com/@tribedaloca/video/7428151463727074561?_t=8qj15m0aC52&_r=1
[TikTok] 7428151463727074561: Downloading webpage
ERROR: [TikTok] 7428151463727074561: Unable to extract webpage video data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 741, in extract
  File "yt_dlp\extractor\tiktok.py", line 889, in _real_extract
  File "yt_dlp\extractor\tiktok.py", line 250, in _extract_web_data_and_status
```

**Comment by RichardReallyHard** [comment]
for the user detail part, verbose output are as follows (either cmd produce same output):
```
yt-dlp -vU -- https://www.tiktok.com/@tribedaloca
yt-dlp -vU -- tiktokuser:tribedaloca
```

```
[debug] Command-line config: ['-vU', '--', 'https://www.tiktok.com/@tribedaloca']
[debug] Encodings: locale cp950, fs utf-8, pref cp950, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.10.20.232914 from yt-dlp/yt-dlp-nightly-builds [87408ccfd] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 2022-02-10-git-b6bb6b9f22-essentials_build-www.gyan.dev (setts), ffprobe 2022-02-10-git-b6bb6b9f22-essentials_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.21.0, brotli-1.1.0, certifi-2024.08.30, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.3, websockets-13.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1839 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.10.20.232914 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.10.20.232914 from yt-dlp/yt-dlp-nightly-builds)
[tiktok:user] Extracting URL: https://www.tiktok.com/@tribedaloca
[tiktok:user] tribedaloca: Downloading user webpage
[tiktok:user] tribedaloca: Downloading live webpage
[tiktok:user] tribedaloca: Downloading user embed page
[tiktok:user] 7428151463727074561: Downloading webpage
[tiktok:user] 7427425250670873857: Downloading webpage
[tiktok:user] 7427410315949739281: Downloading webpage
[tiktok:user] 7427023909028957457: Downloading webpage
[tiktok:user] 7426977207337192705: Downloading webpage
[tiktok:user] 7426736413774761223: Downloading webpage
[tiktok:user] 7426666808167468295: Downloading webpage
[tiktok:user] 7426295695428029714: Downloading webpage
[tiktok:user] 7425940870668537106: Downloading webpage
[tiktok:user] 7424425430364507400: Downloading webpage
ERROR: [tiktok:user] tribedaloca: Unable to extract secondary user ID. If you are able to get the channel_id from a video posted by this user, try using "tiktokuser:channel_id" as the input URL (replacing `channel_id` with its actual value)
  File "yt_dlp\extractor\common.py", line 741, in extract
  File "yt_dlp\extractor\tiktok.py", line 1033, in _real_extract
```

**Comment by bashonly** [comment]
I can't reproduce the issue; everything is working on my end. Have you been downloading heavily from TT recently? It's possible you've been rate-limited or are receiving a captcha challenge page

**Comment by bashonly** [comment]
What happens when you open one of these pages in browser in a private/incognito tab? Do you get any sort of challenge page?

**Comment by bashonly** [comment]
> actually tiktok discontinued service in my area long time ago (kind of geoblock),
> tiktok video/user page is not available in browser.

If the content is unavailable in your browser, then it's expected that yt-dlp will fail as well.

You could try passing `--xff US` (this seems to be effective for livestreams at least), or extracting via API by passing the [`app_info` extractor-arg](https://github.com/yt-dlp/yt-dlp/issues/8678#issuecomment-2316086400) (but the extractor-arg would have no effect for the user extractor, only the video extractor).

If you have no success with those workarounds, you'll need to use a VPN

**Comment by RichardReallyHard** [comment]
> > actually tiktok discontinued service in my area long time ago (kind of geoblock),
> > tiktok video/user page is not available in browser.
> 
> If the content is unavailable in your browser, then it's expected that yt-dlp will fail as well.
> 
> You could try passing `--xff US` (this seems to be somewhat effective for livestreams at least), or extracting via API by passing the [`app_info` extractor-arg](https://github.com/yt-dlp/yt-dlp/issues/8678#issuecomment-2316086400) (but the extractor-arg may only be effective with the video extractor, not the user extractor).
> 
> If you have no success with those workarounds, you'll need to use a VPN

adding --xff US has no effect , but adding extractor-arg gives a slightly different output,
I guess the API JSON is also geoblocked regardless of xff ?

```
[debug] Command-line config: ['-v', '--xff', 'US', '--extractor-arg', 'tiktok:app_info=735572885697939226', '--', 'https://vt.tiktok.com/ZSjekG1vo/']
[debug] Encodings: locale cp950, fs utf-8, pref cp950, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.10.20.232914 from yt-dlp/yt-dlp-nightly-builds [87408ccfd] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 2022-02-10-git-b6bb6b9f22-essentials_build-www.gyan.dev (setts), ffprobe 2022-02-10-git-b6bb6b9f22-essentials_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.21.0, brotli-1.1.0, certifi-2024.08.30, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.3, websockets-13.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1839 extractors
[debug] Using fake IP 6.218.17.13 (US) as X-Forwarded-For
[vm.tiktok] Extracting URL: https://vt.tiktok.com/ZSjekG1vo/
[vm.tiktok] ZSjekG1vo: Downloading webpage
[debug] Using fake IP 6.159.148.62 (US) as X-Forwarded-For
[TikTok] Extracting URL: https://www.tiktok.com/@tribedaloca/video/7428151463727074561?_t=8qj15m0aC52&_r=1
[debug] [TikTok] {'app_name': 'musical_ly', 'app_version': '35.1.3', 'manifest_app_version': '2023501030', 'aid': '0', 'iid': '735572885697939226'}
[TikTok] 7428151463727074561: Downloading API JSON
WARNING: [TikTok] 7428151463727074561: Failed to parse JSON (caused by JSONDecodeError("Expecting value in '': line 1 column 1 (char 0)")); trying with webpage
[TikTok] 7428151463727074561: Downloading webpage
ERROR: [TikTok] 7428151463727074561: Unable to extract webpage video data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 741, in extract
  File "yt_dlp\extractor\tiktok.py", line 889, in _real_extract
  File "yt_dlp\extractor\tiktok.py", line 250, in _extract_web_data_and_status
```

**Comment by bashonly** [comment]
> I guess the API JSON is also geoblocked regardless of xff

Looks like it. I think VPN or proxy is your only solution

**Comment by bashonly** [comment]
Actually, the `iid` you used in the `app_info` arg has been banned / no longer works. Maybe try a different one

**Comment by Muhammad-Shakeel123** [comment]
Download video through url downloaded but the issue is when enter tiktok url then not download why? using yt-dlp
