### ISSUE TITLE
How to download video (including its audio) with mp4 format

### ISSUE THREAD

**Issue by yanhuiyi** [yt-dlp/yt-dlp#11302]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

As titled, I always get a .webm file, while I want to download a 720p video with mp4 output. Below is the code I use

```
from yt_dlp import YoutubeDL
import os

URLS = ['https://youtu.be/AJWTUvXA0Wc']

cur_dir = os.getcwd()

ydl_opts = {
    "outtmpl": os.path.join(cur_dir, f"{id}.mp4"),
    "format": "bestvideo[height<=720][ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best",
    "write-thumbnail": True,
}

with YoutubeDL() as ydl:
    ydl.download(URLS)
```

### Provide verbose output that clearly demonstrates the problem

- [x] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [x] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```
[youtube] Extracting URL: https://youtu.be/AJWTUvXA0Wc
[youtube] AJWTUvXA0Wc: Downloading webpage
[youtube] AJWTUvXA0Wc: Downloading ios player API JSON
[youtube] AJWTUvXA0Wc: Downloading mweb player API JSON
[youtube] AJWTUvXA0Wc: Downloading m3u8 information
[info] AJWTUvXA0Wc: Downloading 1 format(s): 248+251
[download] Destination: Immersive Desert World -- From Idea to 3D Scene in Three Minutes ｜ NVIDIA Research [AJWTUvXA0Wc].f248.webm
[download] 100% of    5.15MiB in 00:00:01 at 4.03MiB/s
[download] Destination: Immersive Desert World -- From Idea to 3D Scene in Three Minutes ｜ NVIDIA Research [AJWTUvXA0Wc].f251.webm
[download] 100% of  924.54KiB in 00:00:00 at 1.86MiB/s
[Merger] Merging formats into "Immersive Desert World -- From Idea to 3D Scene in Three Minutes ｜ NVIDIA Research [AJWTUvXA0Wc].webm"
Deleting original file Immersive Desert World -- From Idea to 3D Scene in Three Minutes ｜ NVIDIA Research [AJWTUvXA0Wc].f251.webm (pass -k to keep)
Deleting original file Immersive Desert World -- From Idea to 3D Scene in Three Minutes ｜ NVIDIA Research [AJWTUvXA0Wc].f248.webm (pass -k to keep)
```

**Comment by seproDev** [comment]
Three things:
- You are not using the `ydl_opts `
- `-f bestvideo[height<=720][ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best` is probably not what you want. mp4 is only the container which can contain different video codecs such as h264, vp9 or, av1. You likely want h264/avc, but with your current format selection, there is no guarantee you get that. Instead, you should use format sorting i.e. `-S vcodec:avc,res:720,acodec:aac`
- `write-thumbnail` is not a valid option. The correct option name would be `writethumbnail`. Don't try to guess the appropriate option name, but use `devscripts(cli_to_api.py`

**Comment by yanhuiyi** [comment]
Thank you so much @seproDev. 
I'm sorry for the first thing you pointed above, I missed that when typing example code. The following opts works for me.
`
"format_sort": ["vcodec:avc", "res:720", "acodec:aac"],
'writethumbnail':'writethumbnail',
`
Closed this question.
