### ISSUE TITLE
Scrap youtube over websocket

### ISSUE THREAD

**Issue by Hydralerne** [yt-dlp/yt-dlp#11301]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

hello team, to make workaround for downloading and get video links, inested of using --proxy to serve youtube i want to make request on user device and parse or progress it using ytdlp, to paybass ip block

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by seproDev** [comment]
Do you mean trying to run yt-dlp in a user's web browser? Not possible due to CORS.
If you mean something else, you would need to explain a bit more.

**Comment by Hydralerne** [comment]
actually no, i mean it will be nodejs client side script or any other websocket that works with mobile apps, it will do the scrap request for the ytdlp insted of using proxy and it's valid approach, i tried to make proxy that redirect request to user soket but it will be much easier if they made a way that we can customize requests or add the request data from socket through

**Comment by Hydralerne** [comment]
ytdlp on server  -> socket connection between user and server -> scrap youtube locally and send the response back via websocket,

**Comment by Grub4K** [comment]
This is off-scope for an enhancement request. You will have to implement a custom `RequestHandler` that will forward requests to the user in Python. Then add it with a high precedence to the `RequestDirector`. See the other request handlers for inspiration.
