### ISSUE TITLE
Facebook photo Download!

### ISSUE THREAD

**Issue by Ohtim1** [yt-dlp/yt-dlp#11313]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

[generic] Extracting URL: https://www.facebook.com/475872082272030
[generic] 475872082272030: Downloading webpage
[redirect] Following redirect to https://web.facebook.com/permalink.php?story_fbid=475872082272030&id=100095477259005
[facebook] Extracting URL: https://web.facebook.com/permalink.php?story_fbid=475872082272030&id=100095477259005
[facebook] 475872082272030: Downloading webpage
[facebook] 475872082272030: Downloading webpage
ERROR: [facebook] 475872082272030: Cannot parse data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[generic] Extracting URL: https://www.facebook.com/475872082272030
[generic] 475872082272030: Downloading webpage
[redirect] Following redirect to https://web.facebook.com/permalink.php?story_fbid=475872082272030&id=100095477259005
[facebook] Extracting URL: https://web.facebook.com/permalink.php?story_fbid=475872082272030&id=100095477259005
[facebook] 475872082272030: Downloading webpage
[facebook] 475872082272030: Downloading webpage
ERROR: [facebook] 475872082272030: Cannot parse data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

**Comment by seproDev** [comment]
Photos are out of scope for yt-dlp

**Comment by Ohtim1** [comment]
> Photos are out of scope for yt-dlp

any solution?

**Comment by seproDev** [comment]
yt-dlp is for downloading videos. You will need to use another program for downloading photos. Either, just right click and save if it is a single image. Otherwise, maybe look in to [gallery-dl](https://github.com/mikf/gallery-dl)

**Comment by Ohtim1** [comment]
> yt-dlp is for downloading videos. You will need to use another program for downloading photos. Either, just right click and save if it is a single image. Otherwise, maybe look in to [gallery-dl](https://github.com/mikf/gallery-dl)

No want to download whole profile photo not just one!

**Comment by Ohtim1** [comment]
and my script is working fine for other photo 
@echo off
setlocal enabledelayedexpansion

set /p customDir="Enter output directory (leave blank for 'Downloads'): "
if "%customDir%"=="" set "customDir=Downloads"

REM Ensure output directory exists
if not exist "%customDir%" mkdir "%customDir%"

REM Initialize counter
set "counter=1"

REM Read URLs from file
for /f "tokens=*" %%i in (urls.txt) do (
    set "url=%%i"
    
    REM Extract filename and handle query parameters
    for /f "delims=? tokens=1" %%b in ("%%~nxi") do (
        set "filename=%%~nxb"
    )

    REM Check if filename has an extension, else default to .jpg
    if "!filename:~-4!"==".jpg" (
        set "unique_filename=!filename!"
    ) else (
        set "unique_filename=!filename!_!counter!.jpg"
    )

    REM Download using ffmpeg
    echo Downloading !url! to %customDir%\!unique_filename!
    start /B ffmpeg -i "!url!" -q:v 1 "%customDir%\!unique_filename!"

    REM Increment the counter
    set /a counter+=1
)

echo All downloads initiated. Waiting for completion...

:wait_for_completion
REM Check if any ffmpeg processes are still running
tasklist /FI "IMAGENAME eq ffmpeg.exe" 2>NUL | find /I "ffmpeg.exe" >NUL
if %ERRORLEVEL% == 0 (
    timeout /T 1 /NOBREAK >NUL
    goto :wait_for_completion
)

echo Download completed.
pause

**Comment by seproDev** [comment]
Again, yt-dlp is only for downloading videos/audio. This is out of scope for the project. I cannot help you further.
