### ISSUE TITLE
BBC iPlayer

### ISSUE THREAD

**Issue by methodphoto** [yt-dlp/yt-dlp#11312]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

UK

### Provide a description that is worded well enough to be understood

Getting 'ERROR: unable to download video data: [Errno 1] Operation not permitted: ' issues when trying to download programmes.
Not sure if the URL format has changed "https://www.bbc.co.uk/iplayer/episode/m00248k9"

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-vU', '-f', 'mp4', 'https://www.bbc.co.uk/iplayer/episode/m00248k9']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Git HEAD: 35ebf4a047
[debug] Python version 3.10.15 (CPython) - macOS-15.1-arm64-arm-64bit
[debug] exe versions: ffmpeg 7.1, ffprobe 7.1
[debug] Proxy map: {}
It looks like you installed youtube-dl with a package manager, pip, setup.py or a tarball. Please use that to update.
[bbc.co.uk] m00248k9: Downloading video page
[bbc.co.uk] m00248k9: Downloading playlist JSON
[bbc.co.uk] m0024gcy: Downloading media selection JSON
[bbc.co.uk] m0024gcy: Downloading MPD manifest
[bbc.co.uk] m0024gcy: Downloading MPD manifest
[bbc.co.uk] m0024gcy: Downloading MPD manifest
[bbc.co.uk] m0024gcy: Downloading MPD manifest
[bbc.co.uk] m0024gcy: Downloading MPD manifest
[bbc.co.uk] m0024gcy: Downloading MPD manifest
[bbc.co.uk] m0024gcy: Downloading m3u8 information
[bbc.co.uk] m0024gcy: Downloading m3u8 information
[bbc.co.uk] m0024gcy: Downloading m3u8 information
[bbc.co.uk] m0024gcy: Downloading m3u8 information
[bbc.co.uk] m0024gcy: Downloading m3u8 information
[bbc.co.uk] m0024gcy: Downloading m3u8 information
[debug] Invoking downloader on 'https://vod-hls-uk.live.cf.md.bbci.co.uk/usp/auth/vod/piff_abr_full_hd/2c9acb-m0024gcy/vf_m0024gcy_18dad669-3d35-456d-9a3f-0db4bc681e05.ism.hlsv2.ism/vf_m0024gcy_18dad669-3d35-456d-9a3f-0db4bc681e05.ism.hlsv2-audio_eng_1=128000-video=5070000.m3u8'
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 690
[download] Destination: BBC Proms, 2024, Florence + The Machine at the Proms-m0024gcy.mp4
ERROR: unable to download video data: [Errno 1] Operation not permitted: 'BBC Proms, 2024, Florence + The Machine at the Proms-m0024gcy.mp4.ytdl'
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 1976, in process_info
    success = dl(filename, info_dict)
  File "/opt/homebrew/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 1915, in dl
    return fd.download(name, info)
  File "/opt/homebrew/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/downloader/common.py", line 366, in download
    return self.real_download(filename, info_dict)
  File "/opt/homebrew/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/downloader/hls.py", line 112, in real_download
    self._prepare_and_start_frag_download(ctx)
  File "/opt/homebrew/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/downloader/fragment.py", line 69, in _prepare_and_start_frag_download
    self._prepare_frag_download(ctx)
  File "/opt/homebrew/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/downloader/fragment.py", line 182, in _prepare_frag_download
    self._write_ytdl_file(ctx)
  File "/opt/homebrew/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/downloader/fragment.py", line 87, in _write_ytdl_file
    frag_index_stream, _ = sanitize_open(self.ytdl_filename(ctx['filename']), 'w')
  File "/opt/homebrew/Cellar/youtube-dl/2021.12.17/libexec/lib/python3.10/site-packages/youtube_dl/utils.py", line 2055, in sanitize_open
    stream = open(encodeFilename(filename), open_mode)
PermissionError: [Errno 1] Operation not permitted: 'BBC Proms, 2024, Florence + The Machine at the Proms-m0024gcy.mp4.ytdl'
```

**Comment by dirkf** [comment]
You are running _youtube-dl_, not _yt-dlp_, so this is the [wrong place](https://github.com/ytdl-org/youtube-dl/issues/30839). If this were an issue about the BBC extractor itself, asking here would fail because the extractor modules aren't synced.

But this problem is something to do with macOS, which doesn't want to write any HLS fragment to the designated place in the file system.

Consider whether the directory to which the files are being written is writable for your user session, or whether _python3_ or [**_Terminal_**](https://github.com/yt-dlp/yt-dlp/issues/7392#issuecomment-1657496651) may need to be given [Full Disk Access](https://www.alfredapp.com/help/troubleshooting/indexing/terminal-full-disk-access/) to write there.
