### ISSUE TITLE
Cannot Install

### ISSUE THREAD

**Issue by imronin97** [yt-dlp/yt-dlp#11320]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Cannot install. There's an error: "Do not double-click the executable, instead call it from a command line." There's no command line to install the program

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
It's not an installer; the exe you downloaded is the entire program. You need to run it from a command line terminal, such as cmd or powershell

Open the folder where you downloaded `yt-dlp.exe` in Windows file explorer. Click the address bar in Windows explorer, type `cmd` and press enter. You will get a command line where you can run `yt-dlp "URL"` (replace `URL` with the actual url you want ot download).

You probably want to install ffmpeg if you have not already. Download [this zip file](https://github.com/yt-dlp/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-win64-gpl.zip) and extract it. There will be a `bin` folder that is extracted; you want to copy the 3 `exe` files from the `bin` folder into the same folder where you have `yt-dlp.exe`
