### ISSUE TITLE
Pass oauth token from web UI to YoutubeDL class in python script

### ISSUE THREAD

**Issue by yanhuiyi** [yt-dlp/yt-dlp#11339]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I use YoutubeDL in python script as a backend service for a frontend web UI. The requirement is users input Youtube video URL and click a 'download' button, then the request goes to backend service which invoking YoutubeDL to download the video.

As the Youtube requires auth to anti-bot, so I want to require users in my frontend web UI to provide XXX-YYY-ZZZ code that requires by "[youtube] oauth: To give yt-dlp access to your account, go to https://www.google.com/device and enter code XXX-YYY-ZZZ". 

My question if yt-dlp provide functions/API to invoke above auth so that I can use it in my frontend to trigger the oauth process, then I pass the code that users entered to my backend to allow YoutubeDL to download videos.

The params that works for yt-dlp command converted to below opts.

```
 ydl_opts = {
        "username": "oauth",
        "password": "",
    }
```

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
[add a logger](https://github.com/yt-dlp/yt-dlp?tab=readme-ov-file#adding-logger-and-progress-hook), wait for the oauth message, parse it for the code

**Comment by yanhuiyi** [comment]
Thanks, @bashonly. When I passed MyLogger to the opts, my program hanged and has to ctrl + C to terminate the program. Looks I have to re-implement such all authentication functions https://github.com/yt-dlp/yt-dlp/blob/2024.10.22/yt_dlp/extractor/youtube.py#L579 here in my code.

**Comment by yanhuiyi** [comment]
I somehow import those extractor class and able to invoke login manually.

```
    with YoutubeDL(ydl_opts) as ydl:
        ie = YoutubeIE(ydl)
        ie._perform_login(username='oauth', password='')
        info = ydl.extract_info(url, download=False)
```
then it prints user code on the stdout with `[youtube] oauth: To give yt-dlp access to your account, go to  https://www.google.com/device  and enter code xxx-xxx-xxx`. Looks I just needs rewrite these auth code to my web UI for users. Then question is,

If I need to execute above perform_login every time I call ydl download.
