### ISSUE TITLE
[twitter] Error(s) while querying API: Could not authenticate you

### ISSUE THREAD

**Issue by ByCzech** [yt-dlp/yt-dlp#11338]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Czech republic

### Provide a description that is worded well enough to be understood

Trying download video from X (Twitter) as usual. Checked with cookies from Vivaldi and from Chrome (--cookies-from-browser), but not worked now.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
$ yt-dlp -vU --cookies-from-browser chrome https://x.com/Beaver_63/status/1849381239284797838
[debug] Command-line config: ['-vU', '--cookies-from-browser', 'chrome', 'https://x.com/Beaver_63/status/1849381239284797838']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.10.22 from yt-dlp/yt-dlp [67adeb7ba] (zip)
[debug] Python 3.11.2 (CPython x86_64 64bit) - Linux-6.1.0-26-amd64-x86_64-with-glibc2.36 (OpenSSL 3.0.14 4 Jun 2024, glibc 2.36)
[debug] exe versions: ffmpeg 6.1.2 (fdk,setts), ffprobe 6.1.2, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.11.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.46.0, pyxattr-0.8.1, requests-2.28.1, secretstorage-3.3.3, sqlite3-3.40.1, urllib3-1.26.12, websockets-10.4
[debug] Proxy map: {}
Extracting cookies from chrome
[debug] Extracting cookies from: "/home/jarda/.config/google-chrome/Profile 1/Cookies"
[Cookies] Loading cookie      0/  3065[debug] detected desktop environment: KDE5
[debug] Chosen keyring: KWALLET5
[debug] using kwallet-query to obtain password from KWALLET5
[debug] NetworkWallet = "kdewallet"
[debug] password found
[Cookies] Loading cookie      1/  3065WARNING: failed to decrypt cookie (AES-CBC) because UTF-8 decoding failed. Possibly the key is wrong?
Extracted 1883 cookies from chrome (1174 could not be decrypted)
[debug] cookie version breakdown: {'v10': 0, 'v11': 3065, 'other': 0, 'unencrypted': 0}
[debug] Request Handlers: urllib
[debug] Loaded 1839 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.10.22 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.10.22 from yt-dlp/yt-dlp)
[twitter] Extracting URL: https://x.com/Beaver_63/status/1849381239284797838
[twitter] 1849381239284797838: Downloading GraphQL JSON
ERROR: [twitter] 1849381239284797838: Error(s) while querying API: Could not authenticate you; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/usr/bin/yt-dlp/yt_dlp/extractor/common.py", line 741, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/yt-dlp/yt_dlp/extractor/twitter.py", line 1430, in _real_extract
    status = self._extract_status(twid)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/yt-dlp/yt_dlp/extractor/twitter.py", line 1408, in _extract_status
    status = self._graphql_to_legacy(self._call_graphql_api(self._GRAPHQL_ENDPOINT, twid), twid)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/yt-dlp/yt_dlp/extractor/twitter.py", line 339, in _call_graphql_api
    return traverse_obj(self._call_api(endpoint, media_id, query=query, graphql=True), 'data')
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/yt-dlp/yt_dlp/extractor/twitter.py", line 329, in _call_api
    raise ExtractorError(f'Error(s) while querying API: {errors or "Unknown error"}')
```

**Comment by bashonly** [comment]
`--cookies-from-browser` is currently broken for chromium-based browsers. Use firefox instead of chrome/vivaldi/brave/chromium/etc, or else [export your cookies to a text file](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp) and use `--cookies`.

This is the same issue that's being discussed towards the end of #6564, but I agree with [mbway's comment](https://github.com/yt-dlp/yt-dlp/issues/6564#issuecomment-2387109475) that it is not the same issue as the OP of that thread; it is just the same symptom, and it deserves its own issue.

**Comment by bashonly** [comment]
I can't reproduce the error with a successful `--cookies-from-browser` run, so I'm pretty sure that's the issue here.

If I had to guess what's happening, it's that you have twitter.com and x.com cookies in your browser's cookie storage, and `--cookies-from-browser chrome` is failing to decrypt the recent (new version) x.com cookies, and succeeding at loading the old/invalidated twitter.cookies. This is causing the yt-dlp extractor's twitter=>x cookie workaround code path to be hit:

https://github.com/yt-dlp/yt-dlp/blob/ec9b25043f399de6a591d8370d32bf0e66c117f2/yt_dlp/extractor/twitter.py#L153-L159

so the extractor proceeds with the assumption that you are logged-in, but twitter rejects the auth token.

We should probably remove this workaround now

**Comment by bashonly** [comment]
OP, can you confirm that it works with firefox or by manually exporting x.com cookies?

**Comment by ByCzech** [comment]
> OP, can you confirm that it works with firefox or by manually exporting x.com cookies?

Export cookies to .txt file by extension works.
