### ISSUE TITLE
[facebook] ERROR: No video formats found / public reels broken

### ISSUE THREAD

**Issue by someziggyman** [yt-dlp/yt-dlp#11337]
### EDIT: This has been fixed, [update yt-dlp to nightly!](https://github.com/yt-dlp/yt-dlp/issues/11337#issuecomment-2435977983)

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

anywhere

### Provide a description that is worded well enough to be understood

Links for testing (all are publicly available):
https://www.facebook.com/heuteshow/videos/was-ist-deutsch/1095152267837555/?rdid=92hHFvgogKs9X10j

https://www.facebook.com/share/v/si7djamaPBu5nDXS/

https://www.facebook.com/reel/1753449678524605
https://www.facebook.com/reel/8279240698806214
https://www.facebook.com/reel/337477362448918
https://www.facebook.com/reel/1166780407785381

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
./yt-dlp -F "https://www.facebook.com/heuteshow/videos/was-ist-deutsch/1095152267837555/?rdid=92hHFvgogKs9X10j"
[facebook] Extracting URL: https://www.facebook.com/heuteshow/videos/was-ist-deutsch/1095152267837555/?rdid=92hHFvgogKs9X10j
[facebook] 1095152267837555: Downloading webpage
ERROR: [facebook] 1095152267837555: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
sy@SYs-MacBook-Air myDLP % ./yt-dlp -vU -F "https://www.facebook.com/heuteshow/videos/was-ist-deutsch/1095152267837555/?rdid=92hHFvgogKs9X10j"
[debug] Command-line config: ['-vU', '-F', 'https://www.facebook.com/heuteshow/videos/was-ist-deutsch/1095152267837555/?rdid=92hHFvgogKs9X10j']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.10.22 from yt-dlp/yt-dlp [67adeb7ba] (zip)
[debug] Python 3.12.2 (CPython arm64 64bit) - macOS-14.6.1-arm64-arm-64bit (OpenSSL 3.0.13 30 Jan 2024)
[debug] exe versions: phantomjs 2.1.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.07.04, curl_cffi-0.7.1, mutagen-1.47.0, requests-2.32.3, sqlite3-3.45.1, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, curl_cffi
[debug] Extractor Plugins: SamplePluginIE
[debug] Post-Processor Plugins: SamplePluginPP
[debug] Loaded 1959 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.10.22 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.10.22 from yt-dlp/yt-dlp)
[facebook] Extracting URL: https://www.facebook.com/heuteshow/videos/was-ist-deutsch/1095152267837555/?rdid=92hHFvgogKs9X10j
[facebook] 1095152267837555: Downloading webpage
ERROR: [facebook] 1095152267837555: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "./yt-dlp/yt_dlp/YoutubeDL.py", line 1629, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "./yt-dlp/yt_dlp/YoutubeDL.py", line 1785, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "./yt-dlp/yt_dlp/YoutubeDL.py", line 1844, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "./yt-dlp/yt_dlp/YoutubeDL.py", line 2850, in process_video_result
    self.raise_no_formats(info_dict)
  File "./yt-dlp/yt_dlp/YoutubeDL.py", line 1126, in raise_no_formats
    raise ExtractorError(msg, video_id=info['id'], ie=info['extractor'],
yt_dlp.utils.ExtractorError: [facebook] 1095152267837555: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

**Comment by checkdev7** [comment]
Hi, Any Update on this issue?

**Comment by charliezxy** [comment]
Same issue here. I can confirm that the issue reported is real. Any update? 
I tried latest versions on both linux and Windows and it's not working as reported on this thread.

**Comment by bashonly** [comment]
The issue just started within the last day or so. If there is any update you will see so in this issue

**Comment by charliezxy** [comment]
Sure, sounds good

**Comment by bashonly** [comment]
This has been fixed in master. If are using a release binary, you can run `yt-dlp --update-to master`

If you used pip to install: https://github.com/yt-dlp/yt-dlp/wiki/Installation#pip-master

---

There will be a new nightly release at midnight UTC tonight. Then `yt-dlp --update-to nightly` or https://github.com/yt-dlp/yt-dlp/wiki/Installation#pip-nightly will work

**Comment by nikalasmd** [comment]
@bashonly 
I have upgraded
pip install --force-reinstall "yt-dlp[default] @ https://github.com/yt-dlp/yt-dlp/archive/master.tar.gz"

Now I have another error.

yt-dlp -vU https://www.facebook.com/reel/510163451947976/?mibextid=ZZyLBr
[debug] Command-line config: ['-vU', 'https://www.facebook.com/reel/510163451947976/?mibextid=ZZyLBr']
[debug] Encodings: locale cp1251, fs utf-8, pref cp1251, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.10.22 from yt-dlp/yt-dlp [67adeb7ba]
[debug] Lazy loading extractors is disabled
[debug] Python 3.11.1 (CPython AMD64 64bit) - Windows-10-10.0.22000-SP0 (OpenSSL 1.1.1q  5 Jul 2022)
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.21.0, brotli-1.1.0, certifi-2024.08.30, mutagen-1.47.0, requests-2.32.3, sqlite3-3.39.4, urllib3-2.2.3, websockets-13.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1839 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.10.22 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.10.22 from yt-dlp/yt-dlp)
[facebook:reel] Extracting URL: https://www.facebook.com/reel/510163451947976/?mibextid=ZZyLBr
[facebook] Extracting URL: https://m.facebook.com/watch/?v=510163451947976&_rdr
[facebook] 510163451947976: Downloading webpage
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
WARNING: ffmpeg not found. The downloaded format may not be the best available. Installing ffmpeg is strongly recommended: https://github.com/yt-dlp/yt-dlp#dependencies
[debug] Default format spec: best/bestvideo+bestaudio
[info] 510163451947976: Downloading 1 format(s): hd
[debug] Invoking http downloader on "https://video.fkiv9-2.fna.fbcdn.net/o1/v/t2/f2/m69/AQNYdDxSQzqFQrG9OiSY704yAlH39-Udv9aJEMmdERl2dTPBtoZLI3-T_anQmO5VZchP_aL7V0PM-DuXFjyIikTz.mp4?efg=eyJ4cHZfYXNzZXRfaWQiOjE1NDg1MjY1NTI0MjE1OTgsInZlbmNvZGVfdGFnIjoieHB2X3Byb2dyZXNzaXZlLkZBQ0VCT09LLi5DMy43MjAuZGFzaF9oMjY0LWJhc2ljLWdlbjJfNzIwcCJ9&_nc_ht=video.fkiv9-2.fna.fbcdn.net&_nc_cat=101&strext=1&vs=d34572c0505f2789&_nc_vs=HBksFQIYOnBhc3N0aHJvdWdoX2V2ZXJzdG9yZS9HR1dfZXh1T29wOS1fWDBFQUVZSHI5NEUyZUk0Ym1kakFBQUYVAALIAQAVAhg6cGFzc3Rocm91Z2hfZXZlcnN0b3JlL0dEVFBmQnQySHhncEdUWURBRzhJMy12YVJmNTRickZxQUFBRhUCAsgBACgAGAAbAogHdXNlX29pbAExEnByb2dyZXNzaXZlX3JlY2lwZQExFQAAJrzTqPGNmMAFFQIoAkMzLBdAVOuFHrhR7BgZZGFzaF9oMjY0LWJhc2ljLWdlbjJfNzIwcBEAdQIA&ccb=9-4&oh=00_AYCdhXgNmpeG55zMhMTGg7bwVkEa1vksX-ufs1EXokml1w&oe=671C4E18&_nc_sid=1d576d"
[download] Unable to open file: [Errno 22] Invalid argument: '92 reactions · 53 shares ｜ De vânzare apartamente în sect. Centru, strada Ismail📍!🔹 Amplasare ultracentrală!🔹 Complex exclusiv, tip CLUB HOUSE!🔹 Apartamente disponibile cu 1, 2 sau 3 camere, cu suprafețe între 47 și 85 m² – perfecte pentru locuit sau investiție. Nu rata această oportunitate unică! Contactați-ne acum pentru mai multe detalii! 📲 079911701 www.vasigur.md ｜ Vasigur Grup [510163451947976].mp4.part'. Retrying (1/3)...
[download] Unable to open file: [Errno 22] Invalid argument: '92 reactions · 53 shares ｜ De vânzare apartamente în sect. Centru, strada Ismail📍!🔹 Amplasare ultracentrală!🔹 Complex exclusiv, tip CLUB HOUSE!🔹 Apartamente disponibile cu 1, 2 sau 3 camere, cu suprafețe între 47 și 85 m² – perfecte pentru locuit sau investiție. Nu rata această oportunitate unică! Contactați-ne acum pentru mai multe detalii! 📲 079911701 www.vasigur.md ｜ Vasigur Grup [510163451947976].mp4.part'. Retrying (2/3)...
[download] Unable to open file: [Errno 22] Invalid argument: '92 reactions · 53 shares ｜ De vânzare apartamente în sect. Centru, strada Ismail📍!🔹 Amplasare ultracentrală!🔹 Complex exclusiv, tip CLUB HOUSE!🔹 Apartamente disponibile cu 1, 2 sau 3 camere, cu suprafețe între 47 și 85 m² – perfecte pentru locuit sau investiție. Nu rata această oportunitate unică! Contactați-ne acum pentru mai multe detalii! 📲 079911701 www.vasigur.md ｜ Vasigur Grup [510163451947976].mp4.part'. Retrying (3/3)...
ERROR: unable to open for writing: [Errno 22] Invalid argument: '92 reactions · 53 shares ｜ De vânzare apartamente în sect. Centru, strada Ismail📍!🔹 Amplasare ultracentrală!🔹 Complex exclusiv, tip CLUB HOUSE!🔹 Apartamente disponibile cu 1, 2 sau 3 camere, cu suprafețe între 47 și 85 m² – perfecte pentru locuit sau investiție. Nu rata această oportunitate unică! Contactați-ne acum pentru mai multe detalii! 📲 079911701 www.vasigur.md ｜ Vasigur Grup [510163451947976].mp4.part'
Traceback (most recent call last):
  File "C:\Users\Nicu\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\utils\_utils.py", line 590, in sanitize_open
    raise LockingUnsupportedError
yt_dlp.utils.LockingUnsupportedError: File locking is not supported

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Nicu\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\downloader\http.py", line 265, in download
    ctx.stream, ctx.tmpfilename = self.sanitize_open(
                                  ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nicu\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\downloader\common.py", line 243, in wrapper
    for retry in RetryManager(self.params.get('file_access_retries', 3), error_callback, fd=self):
  File "C:\Users\Nicu\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\utils\_utils.py", line 5258, in __iter__
    self.error_callback(self.error, self.attempt, self.retries)
  File "C:\Users\Nicu\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\downloader\common.py", line 236, in error_callback
    return RetryManager.report_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nicu\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\utils\_utils.py", line 5266, in report_retry
    raise e
  File "C:\Users\Nicu\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\downloader\common.py", line 245, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nicu\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\downloader\common.py", line 256, in sanitize_open
    f, filename = sanitize_open(filename, open_mode)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nicu\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\utils\_utils.py", line 593, in sanitize_open
    stream = open(filename, open_mode)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 22] Invalid argument: '92 reactions · 53 shares ｜ De vânzare apartamente în sect. Centru, strada Ismail📍!🔹 Amplasare ultracentrală!🔹 Complex exclusiv, tip CLUB HOUSE!🔹 Apartamente disponibile cu 1, 2 sau 3 camere, cu suprafețe între 47 și 85 m² – perfecte pentru locuit sau investiție. Nu rata această oportunitate unică! Contactați-ne acum pentru mai multe detalii! 📲 079911701 www.vasigur.md ｜ Vasigur Grup [510163451947976].mp4.part'


 yt-dlp -vU https://www.facebook.com/reel/510163451947976/?mibextid=ZZyLBr
[debug] Command-line config: ['-vU', 'https://www.facebook.com/reel/510163451947976/?mibextid=ZZyLBr']
[debug] Encodings: locale cp1251, fs utf-8, pref cp1251, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.10.22 from yt-dlp/yt-dlp [67adeb7ba]
[debug] Lazy loading extractors is disabled
[debug] Python 3.11.1 (CPython AMD64 64bit) - Windows-10-10.0.22000-SP0 (OpenSSL 1.1.1q  5 Jul 2022)
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.21.0, brotli-1.1.0, certifi-2024.08.30, mutagen-1.47.0, requests-2.32.3, sqlite3-3.39.4, urllib3-2.2.3, websockets-13.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1839 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.10.22 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.10.22 from yt-dlp/yt-dlp)
[facebook:reel] Extracting URL: https://www.facebook.com/reel/510163451947976/?mibextid=ZZyLBr
[facebook] Extracting URL: https://m.facebook.com/watch/?v=510163451947976&_rdr
[facebook] 510163451947976: Downloading webpage
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
WARNING: ffmpeg not found. The downloaded format may not be the best available. Installing ffmpeg is strongly recommended: https://github.com/yt-dlp/yt-dlp#dependencies
[debug] Default format spec: best/bestvideo+bestaudio
[info] 510163451947976: Downloading 1 format(s): hd
[debug] Invoking http downloader on "https://video.fkiv9-2.fna.fbcdn.net/o1/v/t2/f2/m69/AQNYdDxSQzqFQrG9OiSY704yAlH39-Udv9aJEMmdERl2dTPBtoZLI3-T_anQmO5VZchP_aL7V0PM-DuXFjyIikTz.mp4?efg=eyJ4cHZfYXNzZXRfaWQiOjE1NDg1MjY1NTI0MjE1OTgsInZlbmNvZGVfdGFnIjoieHB2X3Byb2dyZXNzaXZlLkZBQ0VCT09LLi5DMy43MjAuZGFzaF9oMjY0LWJhc2ljLWdlbjJfNzIwcCJ9&_nc_ht=video.fkiv9-2.fna.fbcdn.net&_nc_cat=101&strext=1&vs=d34572c0505f2789&_nc_vs=HBksFQIYOnBhc3N0aHJvdWdoX2V2ZXJzdG9yZS9HR1dfZXh1T29wOS1fWDBFQUVZSHI5NEUyZUk0Ym1kakFBQUYVAALIAQAVAhg6cGFzc3Rocm91Z2hfZXZlcnN0b3JlL0dEVFBmQnQySHhncEdUWURBRzhJMy12YVJmNTRickZxQUFBRhUCAsgBACgAGAAbAogHdXNlX29pbAExEnByb2dyZXNzaXZlX3JlY2lwZQExFQAAJrzTqPGNmMAFFQIoAkMzLBdAVOuFHrhR7BgZZGFzaF9oMjY0LWJhc2ljLWdlbjJfNzIwcBEAdQIA&ccb=9-4&oh=00_AYCdhXgNmpeG55zMhMTGg7bwVkEa1vksX-ufs1EXokml1w&oe=671C4E18&_nc_sid=1d576d"
[download] Unable to open file: [Errno 22] Invalid argument: '92 reactions · 53 shares ｜ De vânzare apartamente în sect. Centru, strada Ismail📍!🔹 Amplasare ultracentrală!🔹 Complex exclusiv, tip CLUB HOUSE!🔹 Apartamente disponibile cu 1, 2 sau 3 camere, cu suprafețe între 47 și 85 m² – perfecte pentru locuit sau investiție. Nu rata această oportunitate unică! Contactați-ne acum pentru mai multe detalii! 📲 079911701 www.vasigur.md ｜ Vasigur Grup [510163451947976].mp4.part'. Retrying (1/3)...
[download] Unable to open file: [Errno 22] Invalid argument: '92 reactions · 53 shares ｜ De vânzare apartamente în sect. Centru, strada Ismail📍!🔹 Amplasare ultracentrală!🔹 Complex exclusiv, tip CLUB HOUSE!🔹 Apartamente disponibile cu 1, 2 sau 3 camere, cu suprafețe între 47 și 85 m² – perfecte pentru locuit sau investiție. Nu rata această oportunitate unică! Contactați-ne acum pentru mai multe detalii! 📲 079911701 www.vasigur.md ｜ Vasigur Grup [510163451947976].mp4.part'. Retrying (2/3)...
[download] Unable to open file: [Errno 22] Invalid argument: '92 reactions · 53 shares ｜ De vânzare apartamente în sect. Centru, strada Ismail📍!🔹 Amplasare ultracentrală!🔹 Complex exclusiv, tip CLUB HOUSE!🔹 Apartamente disponibile cu 1, 2 sau 3 camere, cu suprafețe între 47 și 85 m² – perfecte pentru locuit sau investiție. Nu rata această oportunitate unică! Contactați-ne acum pentru mai multe detalii! 📲 079911701 www.vasigur.md ｜ Vasigur Grup [510163451947976].mp4.part'. Retrying (3/3)...
ERROR: unable to open for writing: [Errno 22] Invalid argument: '92 reactions · 53 shares ｜ De vânzare apartamente în sect. Centru, strada Ismail📍!🔹 Amplasare ultracentrală!🔹 Complex exclusiv, tip CLUB HOUSE!🔹 Apartamente disponibile cu 1, 2 sau 3 camere, cu suprafețe între 47 și 85 m² – perfecte pentru locuit sau investiție. Nu rata această oportunitate unică! Contactați-ne acum pentru mai multe detalii! 📲 079911701 www.vasigur.md ｜ Vasigur Grup [510163451947976].mp4.part'
Traceback (most recent call last):
  File "C:\Users\Nicu\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\utils\_utils.py", line 590, in sanitize_open
    raise LockingUnsupportedError
yt_dlp.utils.LockingUnsupportedError: File locking is not supported

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Nicu\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\downloader\http.py", line 265, in download
    ctx.stream, ctx.tmpfilename = self.sanitize_open(
                                  ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nicu\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\downloader\common.py", line 243, in wrapper
    for retry in RetryManager(self.params.get('file_access_retries', 3), error_callback, fd=self):
  File "C:\Users\Nicu\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\utils\_utils.py", line 5258, in __iter__
    self.error_callback(self.error, self.attempt, self.retries)
  File "C:\Users\Nicu\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\downloader\common.py", line 236, in error_callback
    return RetryManager.report_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nicu\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\utils\_utils.py", line 5266, in report_retry
    raise e
  File "C:\Users\Nicu\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\downloader\common.py", line 245, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nicu\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\downloader\common.py", line 256, in sanitize_open
    f, filename = sanitize_open(filename, open_mode)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nicu\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\utils\_utils.py", line 593, in sanitize_open
    stream = open(filename, open_mode)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 22] Invalid argument: '92 reactions · 53 shares ｜ De vânzare apartamente în sect. Centru, strada Ismail📍!🔹 Amplasare ultracentrală!🔹 Complex exclusiv, tip CLUB HOUSE!🔹 Apartamente disponibile cu 1, 2 sau 3 camere, cu suprafețe între 47 și 85 m² – perfecte pentru locuit sau investiție. Nu rata această oportunitate unică! Contactați-ne acum pentru mai multe detalii! 📲 079911701 www.vasigur.md ｜ Vasigur Grup [510163451947976].mp4.part'

**Comment by bashonly** [comment]
@nikalasmd that's happening because the output filename is too long. Add `-o "%(title).100B [%(id)s].%(ext)s"` to your command to mitigate this

**Comment by mvan231** [comment]
Any information that can be provided by users to help?

**Comment by bashonly** [comment]
> Any information that can be provided by users to help?

[update to nightly](https://github.com/yt-dlp/yt-dlp/issues/11337#issuecomment-2435977983)

**Comment by Stevencuong19** [comment]
list of errors when downloading videos here: ERROR: [facebook] 837686098441609: Video format not found!; please report this issue on https://github.com/yt-dlp/yt-dlp/issues?q= ,
fill in the appropriate issue form. Confirm you are using the latest version using yt-dlp -U
pip install yt-dlp -U did not help me get rid of the error

**Comment by bashonly** [comment]
# FOLLOW THE LINK THAT TELLS YOU HOW TO UPDATE TO NIGHTLY
