### ISSUE TITLE
www2.putlocker.digital not working

### ISSUE THREAD

**Issue by MercedesMcdaniel** [yt-dlp/yt-dlp#11365]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Canada

### Example URLs

https://www2.putlocker.digital/movie/classified-2024/l7m49b2y/2vqCRvSH-watch-online-free.html

### Provide a description that is worded well enough to be understood

ERROR: [generic] Unable to download webpage: Failed to perform

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
debug] Command-line config: ['https://www2.putlocker.digital/movie/classified-2024/l7m49b2y/2vqCRvSH-watch-online-free.html', '-vU']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.10.22 from yt-dlp/yt-dlp (linux_exe)
[debug] Python 3.11.10 (CPython x86_64 64bit) - Linux-5.15.0-124-generic-x86_64-with (OpenSSL 3.1.7 3 Sep 2024)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.21.0, brotli-1.1.0, certifi-2024.08.30, curl_cffi-0.7.1, mutagen-1.47.0, requests-2.32.3, secretstorage-3.3.3, sqlite3-3.44.2, urllib3-2.2.3, websockets-13.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1839 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.10.22 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.10.22 from yt-dlp/yt-dlp)
[generic] Extracting URL: https://www2.putlocker.digital/movie/classified-2024/l7m49b2y/2vqCRvSH-watch-online-free.html
[generic] 2vqCRvSH-watch-online-free: Downloading webpage
ERROR: [generic] Unable to download webpage: Failed to perform, curl: (35) Recv failure: Connection reset by peer. See https://curl.se/libcurl/c/libcurl-errors.html first for more details. (caused by SSLError('Failed to perform, curl: (35) Recv failure: Connection reset by peer. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp/extractor/common.py", line 741, in extract
  File "yt_dlp/extractor/generic.py", line 2391, in _real_extract
  File "yt_dlp/extractor/common.py", line 910, in _request_webpage

  File "yt_dlp/networking/_curlcffi.py", line 217, in _send
  File "curl_cffi/requests/session.py", line 968, in request
curl_cffi.requests.errors.RequestsError: Failed to perform, curl: (35) Recv failure: Connection reset by peer. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "yt_dlp/extractor/common.py", line 897, in _request_webpage
  File "yt_dlp/YoutubeDL.py", line 4165, in urlopen
  File "yt_dlp/networking/common.py", line 117, in send
  File "yt_dlp/networking/_curlcffi.py", line 156, in send
  File "yt_dlp/networking/_helper.py", line 208, in wrapper
  File "yt_dlp/networking/common.py", line 340, in send
  File "yt_dlp/networking/_curlcffi.py", line 235, in _send
yt_dlp.networking.exceptions.SSLError: Failed to perform, curl: (35) Recv failure: Connection reset by peer. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.
```

**Comment by bashonly** [comment]
Sites primarily used for piracy won't be supported

https://github.com/yt-dlp/yt-dlp/wiki/FAQ#why-is-there-a-rule-against-websites-primarily-used-for-piracy
