### ISSUE TITLE
Downloading in mp4 I got some video with Audio in Opus?

### ISSUE THREAD

**Issue by tormyvancool** [yt-dlp/yt-dlp#11362]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

By following a very valid suggestion, I downloaded some video with this command line arguments

yt-dlp.exe --merge-output-format mp4 <URL>

but in a couple of case, by playing the MP4 with VLC I got the message that the audio is in OPUS.
And some app I have, is not reading OPUS (that's strange because also VLC returns an error).

May I ask how to prevent this please? 

I know YT is using OPUS? but I would like to get rid of these non-sense errors from the reading apps.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
The `--merge-output-format` option is not going to have any effect on what codecs are selected, it only decides the output container if multiple video / audio formats need to be merged.

You probably want to use the format sorting option, `-S`, to prefer certain codecs

A commonly used format sorting arg is `-S vcodec:h264,res,acodec:aac`

It will prefer h264 video formats and aac audio formats, and if formats are available with those codecs, you will end up with an mp4 final product that should be compatible with almost any modern media player.
