### ISSUE TITLE
How to grab youtube utf-8 title fast from channel ?

### ISSUE THREAD

**Issue by Bharat0112** [yt-dlp/yt-dlp#11360]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

This gets list of youtube video titles from channel perfectly in utf-8, but it takes time, as it loads page one by one :
`yt-dlp -s --print-to-file "%(title)s" FileName.txt "https://www.youtube.com/@ChannelName/videos"`

This grabs titles list fast with utf-8 , but doesn't get stored in a text file, only Latin characters are stored.
`yt-dlp -i --print "%(title)s" --skip-download "https://www.youtube.com/@ChannelName/videos" > FileName.txt`

How do I make it both ->  UTF-8  titles + get list of titles fast ?

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
```
yt-dlp --flat-playlist --print-to-file "%(title)s" FileName.txt "https://www.youtube.com/@ChannelName/videos"
```

**Comment by Bharat0112** [comment]
Awesome. Thank you very much.
