### ISSUE TITLE
I want to watch YT channels from the start - help? 😔

### ISSUE THREAD

**Issue by ldexterldesign** [yt-dlp/yt-dlp#11378]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

👋 all,

Hope y'all OK!

I want to watch some YT channels from the start (i.e. chronologically). Some channels started 10 years ago so it's not practical to use the UI for this. It's also not practical to download 10 years worth of content when I could grab a small batch (e.g. 10 videos, 1GB, 2014-5) and repeat.

After a few hours researching and experimenting I tried various combinations of `--playlist-start/end` and `--playlist-reverse` (seems to be a lot of people complaining combining these flags is problematic 🤷) and then resorting back to `--date-before/after` - neither successful for my use case 😢

I suppose [this] issue is the closest I've got with research - technically a command with `--date-before/after` will work but, to be frank, there's zero chance I'm gonna wait for the command to call the YT API hundreds of times before the new batch of videos I want downloads 🥱

Examples/suggestions/tips appreciated..?

Yours hopefully

[this]: https://github.com/yt-dlp/yt-dlp/issues/11084

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by ldexterldesign** [comment]
👋 https://github.com/ytdl-org/youtube-dl/issues/32962 - crossposted 🙏

**Comment by gamer191** [comment]
Do you actually want to download the videos or do you just want the links? `--playlist-reverse --flat-playlist --print-to-file webpage_url videourls.txt` will write a list of video urls to the file videourls.txt

Note that it's not perfect because it will write shorts and livestreams (including past livestreams) at the top of the file. If that's an issue let me know and I'll come up with a different command

**Comment by ldexterldesign** [comment]
Thanks for reply

Videos please

Aside, thanks for links tip - will experiment with that to avoid the API calls until something better emerges 🤞

Hope to hear back

Cheers

**Comment by bashonly** [comment]
`--playlist-reverse` is currently the only way afaik. Use `--break-on-reject --datebefore DATE` if you want to stop at a certain point in time.

**Comment by ldexterldesign** [comment]
👋 @bashonly,

Thanks for reply

I'm afraid your proposed solution doesn't work:
```
yt-dlp http://youtube.com/@cherdleys --break-on-reject --datebefore 20160101 --playlist-reverse
[youtube:tab] Extracting URL: http://youtube.com/@cherdleys
[youtube:tab] @cherdleys: Downloading webpage
[youtube:tab] Downloading all uploads of the channel. To download only the videos in a specific tab, pass the tab's URL
[youtube:tab] @cherdleys/shorts: Downloading webpage
[youtube:tab] Downloading as multiple playlists, separated by tabs. To download as a single playlist instead, pass https://www.youtube.com/playlist?list=UUPHeAtHSXnymNh8b_Kkj2rw
[download] Downloading playlist: Cherdleys
[youtube:tab] Playlist Cherdleys: Downloading 2 items of 2
[download] Downloading item 1 of 2
[download] Downloading playlist: Cherdleys - Shorts
[youtube:tab] UCPHeAtHSXnymNh8b_Kkj2rw page 1: Downloading API JSON
[youtube:tab] UCPHeAtHSXnymNh8b_Kkj2rw page 2: Downloading API JSON
[youtube:tab] UCPHeAtHSXnymNh8b_Kkj2rw page 3: Downloading API JSON
[youtube:tab] UCPHeAtHSXnymNh8b_Kkj2rw page 4: Downloading API JSON
[youtube:tab] UCPHeAtHSXnymNh8b_Kkj2rw page 5: Downloading API JSON
[youtube:tab] UCPHeAtHSXnymNh8b_Kkj2rw page 6: Downloading API JSON
[youtube:tab] UCPHeAtHSXnymNh8b_Kkj2rw page 7: Downloading API JSON
[youtube:tab] Playlist Cherdleys - Shorts: Downloading 381 items of 381
[download] Downloading item 1 of 381
[youtube] Extracting URL: https://www.youtube.com/shorts/UOI8tjaXsOo
[youtube] UOI8tjaXsOo: Downloading webpage
[youtube] UOI8tjaXsOo: Downloading ios player API JSON
[youtube] UOI8tjaXsOo: Downloading mweb player API JSON
[youtube] UOI8tjaXsOo: Downloading m3u8 information
[download] 2022-02-05 upload date is not in range 0001-01-01 to 2016-01-01
[info] Encountered a video that did not match filter, stopping due to --break-match-filter
Aborting remaining downloads
yt-dlp http://youtube.com/@cherdleys --datebefore 20160101 --playlist-reverse --break-on-reject
[youtube:tab] Extracting URL: http://youtube.com/@cherdleys
[youtube:tab] @cherdleys: Downloading webpage
[youtube:tab] Downloading all uploads of the channel. To download only the videos in a specific tab, pass the tab's URL
[youtube:tab] @cherdleys/shorts: Downloading webpage
[youtube:tab] Downloading as multiple playlists, separated by tabs. To download as a single playlist instead, pass https://www.youtube.com/playlist?list=UUPHeAtHSXnymNh8b_Kkj2rw
[download] Downloading playlist: Cherdleys
[youtube:tab] Playlist Cherdleys: Downloading 2 items of 2
[download] Downloading item 1 of 2
[download] Downloading playlist: Cherdleys - Shorts
[youtube:tab] UCPHeAtHSXnymNh8b_Kkj2rw page 1: Downloading API JSON
[youtube:tab] UCPHeAtHSXnymNh8b_Kkj2rw page 2: Downloading API JSON
[youtube:tab] UCPHeAtHSXnymNh8b_Kkj2rw page 3: Downloading API JSON
[youtube:tab] UCPHeAtHSXnymNh8b_Kkj2rw page 4: Downloading API JSON
[youtube:tab] UCPHeAtHSXnymNh8b_Kkj2rw page 5: Downloading API JSON
[youtube:tab] UCPHeAtHSXnymNh8b_Kkj2rw page 6: Downloading API JSON
[youtube:tab] UCPHeAtHSXnymNh8b_Kkj2rw page 7: Downloading API JSON
[youtube:tab] Playlist Cherdleys - Shorts: Downloading 381 items of 381
[download] Downloading item 1 of 381
[youtube] Extracting URL: https://www.youtube.com/shorts/UOI8tjaXsOo
[youtube] UOI8tjaXsOo: Downloading webpage
[youtube] UOI8tjaXsOo: Downloading ios player API JSON
[youtube] UOI8tjaXsOo: Downloading mweb player API JSON
[youtube] UOI8tjaXsOo: Downloading m3u8 information
[download] 2022-02-05 upload date is not in range 0001-01-01 to 2016-01-01
[info] Encountered a video that did not match filter, stopping due to --break-match-filter
Aborting remaining downloads
yt-dlp http://youtube.com/@cherdleys --playlist-reverse --break-on-reject --datebefore 20160101
[youtube:tab] Extracting URL: http://youtube.com/@cherdleys
[youtube:tab] @cherdleys: Downloading webpage
[youtube:tab] Downloading all uploads of the channel. To download only the videos in a specific tab, pass the tab's URL
[youtube:tab] @cherdleys/shorts: Downloading webpage
[youtube:tab] Downloading as multiple playlists, separated by tabs. To download as a single playlist instead, pass https://www.youtube.com/playlist?list=UUPHeAtHSXnymNh8b_Kkj2rw
[download] Downloading playlist: Cherdleys
[youtube:tab] Playlist Cherdleys: Downloading 2 items of 2
[download] Downloading item 1 of 2
[download] Downloading playlist: Cherdleys - Shorts
[youtube:tab] UCPHeAtHSXnymNh8b_Kkj2rw page 1: Downloading API JSON
[youtube:tab] UCPHeAtHSXnymNh8b_Kkj2rw page 2: Downloading API JSON
[youtube:tab] UCPHeAtHSXnymNh8b_Kkj2rw page 3: Downloading API JSON
[youtube:tab] UCPHeAtHSXnymNh8b_Kkj2rw page 4: Downloading API JSON
[youtube:tab] UCPHeAtHSXnymNh8b_Kkj2rw page 5: Downloading API JSON
[youtube:tab] UCPHeAtHSXnymNh8b_Kkj2rw page 6: Downloading API JSON
[youtube:tab] UCPHeAtHSXnymNh8b_Kkj2rw page 7: Downloading API JSON
[youtube:tab] Playlist Cherdleys - Shorts: Downloading 381 items of 381
[download] Downloading item 1 of 381
[youtube] Extracting URL: https://www.youtube.com/shorts/UOI8tjaXsOo
[youtube] UOI8tjaXsOo: Downloading webpage
[youtube] UOI8tjaXsOo: Downloading ios player API JSON
[youtube] UOI8tjaXsOo: Downloading mweb player API JSON
[youtube] UOI8tjaXsOo: Downloading m3u8 information
[download] 2022-02-05 upload date is not in range 0001-01-01 to 2016-01-01
[info] Encountered a video that did not match filter, stopping due to --break-match-filter
Aborting remaining downloads
```

In case someone *does* have a solution, I will appreciate it if you'd leave the issue open - at least a little longer - for visibility

If you insist on closing the issue then it is possible to create some type of feature request from this - between the two repos I did see issues going back over a decade requesting a solution for this type of problem 🤯

Yours hopefully

**Comment by bashonly** [comment]
pass `https://youtube.com/@cherdleys/videos` and `http://youtube.com/@cherdleys/shorts` isntead of `http://youtube.com/@cherdleys`

**Comment by ldexterldesign** [comment]
👋 @bashonly,

Ahh, that seems to do the trick 😊

Glad I created this issue

Hope it helps someone else too!

Kind thanks

**Comment by ldexterldesign** [comment]
FYR the two scripts I have for solving this use case

```sh
// creates include.txt & captures all channel video ids
yt-dlp --flat-playlist --get-id http://youtube.com/@[channel]/videos > include.txt --playlist-reverse
```

```sh
// downloads first/next 10 videos & captures downloaded video ids to exclude.txt (ie so they aren't downloaded again)
yt-dlp --download-archive exclude.txt --max-downloads 10 -a include.txt --merge-output-format mp4/mkv --output "%(upload_date)s - %(title)s.%(ext)s"  -S "height:1080" http://youtube.com/@[channel]/videos
```

<img width="1840" height="1191" alt="Image" src="https://github.com/user-attachments/assets/e9ed1c19-71d7-426f-9750-b4a886ceb1e1" />

Hope this helps!
