### ISSUE TITLE
Remove Hashtag # from filename?

### ISSUE THREAD

**Issue by seaklin83546** [yt-dlp/yt-dlp#11373]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Remove Hashtag # from filename?

Ex. Краш Тесту #Hobot Ukraine пройден Успешно 🤩👍🏻.mp4
To. Краш Тесту Ukraine пройден Успешно 🤩👍🏻.mp4

Thank you Admin.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
to remove a hashtag that's in the middle of the title, you could use:
```
--replace-in-metadata title " #\w+ " " "
```

but if you want to remove *any* hashtags that may be at the beginning, middle or end of the title, use this:
```
--replace-in-metadata title " #\w+ " " " --replace-in-metadata title "^#\w+ " "" --replace-in-metadata title " #\w+$" ""
```

**Comment by seaklin83546** [comment]
> to remove a hashtag that's in the middle of the title, you could use:
> 
> ```
> --replace-in-metadata title " #\w+ " " "
> ```
> 
> but if you want to remove _any_ hashtags that may be at the beginning, middle or end of the title, use this:
> 
> ```
> --replace-in-metadata title " #\w+ " " " --replace-in-metadata title "^#\w+ " "" --replace-in-metadata title " #\w+$" ""
> ```

Worked, Thank you very much Admin.

**Comment by seaklin83546** [comment]
> to remove a hashtag that's in the middle of the title, you could use:
> 
> ```
> --replace-in-metadata title " #\w+ " " "
> ```
> 
> but if you want to remove _any_ hashtags that may be at the beginning, middle or end of the title, use this:
> 
> ```
> --replace-in-metadata title " #\w+ " " " --replace-in-metadata title "^#\w+ " "" --replace-in-metadata title " #\w+$" ""
> ```

But it support unicode?
https://www.tiktok.com/@souenn2/video/7427433721831181575

Replying to @ស្រី ខ្មៅ #ឈុតសាប៊ូកក់សក់er #កក់2ដងឃេីញផល .mp4

**Comment by seaklin83546** [comment]
> want to remove _any_ hashtags that may be at the beginning

But i want to remove any hashtags. Can you help please.

**Comment by bashonly** [comment]
```
--replace-in-metadata title " #[^\s]+ " " " --replace-in-metadata title "^#[^\s]+ " "" --replace-in-metadata title " #[^\s]+$" ""
```

**Comment by seaklin83546** [comment]
> ```
> --replace-in-metadata title " #[^\s]+ " " " --replace-in-metadata title "^#[^\s]+ " "" --replace-in-metadata title " #[^\s]+$" ""
> ```

this code not work for Unicode Admin.

Result: ไวรัลชั่วข้ามคืน สแน็ก มิสแกรนด์เลย 2023 #นับจากนี้ทุกพื้นที่มีแต่แกรนด์

**Comment by bashonly** [comment]
try this:
```
--replace-in-metadata title " #.+? " " " --replace-in-metadata title "^#.+? " "" --replace-in-metadata title " #.+$" ""
```
