### ISSUE TITLE
Unable to download API page

### ISSUE THREAD

**Issue by mahyarw** [yt-dlp/yt-dlp#11381]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

iran

### Provide a description that is worded well enough to be understood

im using v2ray tun and case of the Internet censorship in Iran, cant access youtube without a vpn 
this is the i get 

C:\Users\persain dell>yt-dlp https://www.youtube.com/watch?v=TMzs6GvsZXU
[youtube] Extracting URL: https://www.youtube.com/watch?v=TMzs6GvsZXU
[youtube] TMzs6GvsZXU: Downloading webpage
WARNING: [youtube] Unable to download webpage: HTTPSConnectionPool(host='www.youtube.com', port=443): Read timed out. (read timeout=20.0)
[youtube] TMzs6GvsZXU: Downloading ios player API JSON
WARNING: [youtube] <urllib3.connection.HTTPSConnection object at 0x0000024A6F8377F0>: Failed to resolve 'www.youtube.com' ([Errno 11001] getaddrinfo failed). Retrying (1/3)...
[youtube] TMzs6GvsZXU: Downloading ios player API JSON
WARNING: [youtube] <urllib3.connection.HTTPSConnection object at 0x0000024A6F837F40>: Failed to resolve 'www.youtube.com' ([Errno 11001] getaddrinfo failed). Retrying (2/3)...
[youtube] TMzs6GvsZXU: Downloading ios player API JSON
WARNING: [youtube] <urllib3.connection.HTTPSConnection object at 0x0000024A6F82C2B0>: Failed to resolve 'www.youtube.com' ([Errno 11001] getaddrinfo failed). Retrying (3/3)...
[youtube] TMzs6GvsZXU: Downloading ios player API JSON
WARNING: [youtube] Unable to download API page: HTTPSConnectionPool(host='www.youtube.com', port=443): Read timed out. (read timeout=20.0) (caused by TransportError("HTTPSConnectionPool(host='www.youtube.com', port=443): Read timed out. (read timeout=20.0)"))
[youtube] TMzs6GvsZXU: Downloading iframe API JS
WARNING: [youtube] Unable to download webpage: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
[youtube] TMzs6GvsZXU: Downloading mweb player API JSON
WARNING: [youtube] ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)). Retrying (1/3)...
[youtube] TMzs6GvsZXU: Downloading mweb player API JSON
WARNING: [youtube] ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)). Retrying (2/3)...
[youtube] TMzs6GvsZXU: Downloading mweb player API JSON
WARNING: [youtube] HTTPSConnectionPool(host='www.youtube.com', port=443): Read timed out. (read timeout=20.0). Retrying (3/3)...
[youtube] TMzs6GvsZXU: Downloading mweb player API JSON
WARNING: [youtube] Unable to download API page: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)) (caused by TransportError("('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))"))
ERROR: [youtube] TMzs6GvsZXU: Failed to extract any player response; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
C:\Users\persain dell>yt-dlp -vU https://www.youtube.com/watch?v=TMzs6GvsZXU
[debug] Command-line config: ['-vU', 'https://www.youtube.com/watch?v=TMzs6GvsZXU']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.10.22 from yt-dlp/yt-dlp [67adeb7ba] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-116435-g719e46f54c-20240726 (setts), ffprobe N-116435-g719e46f54c-20240726
[debug] Optional libraries: Cryptodome-3.21.0, brotli-1.1.0, certifi-2024.08.30, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.3, websockets-13.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1839 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
ERROR: Unable to obtain version info (<urllib3.connection.HTTPSConnection object at 0x00000259B9E092B0>: Failed to resolve 'api.github.com' ([Errno 11001] getaddrinfo failed)); Please try again later or visit  https://github.com/yt-dlp/yt-dlp/releases/latest
[youtube] Extracting URL: https://www.youtube.com/watch?v=TMzs6GvsZXU
[youtube] TMzs6GvsZXU: Downloading webpage
WARNING: [youtube] Unable to download webpage: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
[youtube] TMzs6GvsZXU: Downloading ios player API JSON
WARNING: [youtube] HTTPSConnectionPool(host='www.youtube.com', port=443): Read timed out. (read timeout=20.0). Retrying (1/3)...
[youtube] TMzs6GvsZXU: Downloading ios player API JSON
WARNING: [youtube] <urllib3.connection.HTTPSConnection object at 0x00000259B9E092B0>: Failed to resolve 'www.youtube.com' ([Errno 11001] getaddrinfo failed). Retrying (2/3)...
[youtube] TMzs6GvsZXU: Downloading ios player API JSON
WARNING: [youtube] <urllib3.connection.HTTPSConnection object at 0x00000259BA012160>: Failed to resolve 'www.youtube.com' ([Errno 11001] getaddrinfo failed). Retrying (3/3)...
[youtube] TMzs6GvsZXU: Downloading ios player API JSON
WARNING: [youtube] Unable to download API page: <urllib3.connection.HTTPSConnection object at 0x00000259B9FBFE80>: Failed to resolve 'www.youtube.com' ([Errno 11001] getaddrinfo failed) (caused by TransportError("<urllib3.connection.HTTPSConnection object at 0x00000259B9FBFE80>: Failed to resolve 'www.youtube.com' ([Errno 11001] getaddrinfo failed)"))
[youtube] TMzs6GvsZXU: Downloading iframe API JS
WARNING: [youtube] Unable to download webpage: <urllib3.connection.HTTPSConnection object at 0x00000259BA004460>: Failed to resolve 'www.youtube.com' ([Errno 11001] getaddrinfo failed)
[youtube] TMzs6GvsZXU: Downloading mweb player API JSON
WARNING: [youtube] <urllib3.connection.HTTPSConnection object at 0x00000259B9FE86D0>: Failed to resolve 'www.youtube.com' ([Errno 11001] getaddrinfo failed). Retrying (1/3)...
[youtube] TMzs6GvsZXU: Downloading mweb player API JSON
WARNING: [youtube] <urllib3.connection.HTTPSConnection object at 0x00000259BA023FD0>: Failed to resolve 'www.youtube.com' ([Errno 11001] getaddrinfo failed). Retrying (2/3)...
[youtube] TMzs6GvsZXU: Downloading mweb player API JSON
WARNING: [youtube] <urllib3.connection.HTTPSConnection object at 0x00000259B9FBFC70>: Failed to resolve 'www.youtube.com' ([Errno 11001] getaddrinfo failed). Retrying (3/3)...
[youtube] TMzs6GvsZXU: Downloading mweb player API JSON
WARNING: [youtube] Unable to download API page: HTTPSConnectionPool(host='www.youtube.com', port=443): Read timed out. (read timeout=20.0) (caused by TransportError("HTTPSConnectionPool(host='www.youtube.com', port=443): Read timed out. (read timeout=20.0)"))
ERROR: [youtube] TMzs6GvsZXU: Failed to extract any player response; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 741, in extract
  File "yt_dlp\extractor\youtube.py", line 4568, in _real_extract
  File "yt_dlp\extractor\youtube.py", line 4532, in _download_player_responses
  File "yt_dlp\extractor\youtube.py", line 4191, in _extract_player_responses
```

**Comment by seproDev** [comment]
This is an issue with your internet connection. Not even the Github server to check for updates can be reached.
