### ISSUE TITLE
Youtube downloading generates corrupted file

### ISSUE THREAD

**Issue by Leocraft1** [yt-dlp/yt-dlp#11382]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Italy (Europe)

### Provide a description that is worded well enough to be understood

Downloading every video (from today) results in a corrupted video file with no video but audio is available. Also the progress bar with the percentage doesn't get cleared and results in kilometers of percentage printed on the console.
![IMG_1640](https://github.com/user-attachments/assets/c402b5f9-79ae-4610-a39e-f7123d74a3d8)
![IMG_1641](https://github.com/user-attachments/assets/65a8f996-714c-45f1-93c7-15e2f5280bdf)
![IMG_1642](https://github.com/user-attachments/assets/50f44c89-cc53-4721-a3ed-6d9d7760f239)

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
I added that as a screenshot as I'm on phone right now and I can't copy from the console
```

**Comment by seproDev** [comment]
You are using an outdated yt-dlp version. Update!
Also at least from your logs the video looks fine. Is it really corrupted, or are you just using a media player that doesn't support the downloaded codec? Please provide a verbose yt-dlp log in **text** form and the ffprobe log for the video.

**Comment by Leocraft1** [comment]
I installed it with apt install yt-dlp, when I do an apt update it just says i'm up to date (i'm using sudo)

**Comment by Leocraft1** [comment]
Regarding the codec, every player I tried does read only the audio or crashes (tried with vlc too)

**Comment by seproDev** [comment]
> I installed it with apt install yt-dlp

We do not maintain the versions of yt-dlp provided in distribution package managers. Some distributions are known to ship old to very old software versions. If you want support here you will need to install a current yt-dlp version. You even checked in the issue template that you installed the latest nightly/master, which you did not. You can read more here: https://github.com/yt-dlp/yt-dlp/wiki/FAQ#the-yt-dlp-in-my-package-manager-is-outdatedbroken

In short you will need to uninstall the yt-dlp version you installed through apt and either grab one of the release binaries or install yt-dlp with pip/pipx. For some distros there also exist PPAs or unstable repos that might contain a more recent versions if you wish to stick to apt.

> every player I tried does read only the audio or crashes (tried with vlc too)

Please provide a ffprobe output like I asked you to. Downloading the same video and the exact same formats as you did, the video plays back fine for me.

**Comment by Leocraft1** [comment]
Fixed! Just removed from apt and installed the version from snap (with sudo snap install yt-dlp) which is version 2024.08.06 and now everything works, no thousand of lines in the console and visible video! Thanks

**Comment by seproDev** [comment]
Just so you are aware, 2024.08.06 is still outdated. Sites often change how they work, and yt-dlp constantly needs to adjust. Thus, it is very important to stay on the latest version.
We also don't maintain the snap version, but they do seem to support installing the last release through their edge branch with
```
sudo snap install yt-dlp --edge
```
