### ISSUE TITLE
[Artstation Learning] Add support for Artstation Learning

### ISSUE THREAD

**Issue by nocoel** [yt-dlp/yt-dlp#1140]
## Checklist

- [x] I'm reporting a new site support request
- [x] I've verified that I'm running yt-dlp version **2021.09.25**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that none of provided URLs violate any copyrights
- [x] The provided URLs do not contain any DRM to the best of my knowledge
- [x] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

- https://www.artstation.com/learning/courses/dqQ/character-design-masterclass-with-serge-birault/chapters/Rxn3/introduction

- https://www.artstation.com/learning/courses/PJo/intro-to-substance-designer-for-vfx/chapters/Wnar/course-intro

## Description

Artstation Learning has alot of free tutorials for art, 3d modeling, art for game development and design in general
its Free, it requires an account but you can create an Artstation account and use everything for free till 2022

hopping really hard for it to be implemented before the end of the year

**Comment by coletdjnz** [comment]
Both videos in the example URLs appear to be DRM protected. We do not support downloading DRM content.
