### ISSUE TITLE
't' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by Foxiseminger** [yt-dlp/yt-dlp#11403]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

its running a command called 't' but i dont have 't'.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [x] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
C:\Users\foxis>yt-dlp https://www.youtube.com/watch?v=GNDfLEKUhag&t=24s
[youtube] Extracting URL: https://www.youtube.com/watch?v=GNDfLEKUhag
[youtube] GNDfLEKUhag: Downloading webpage
[youtube] GNDfLEKUhag: Downloading ios player API JSON
[youtube] GNDfLEKUhag: Downloading mweb player API JSON
[youtube] GNDfLEKUhag: Downloading m3u8 information
[info] GNDfLEKUhag: Downloading 1 format(s): 308+251
[download] Destination: Hard Machine (LEVEL SHOWCASE) [GNDfLEKUhag].f308.webm
[download] 100% of   98.67MiB in 00:00:10 at 9.04MiB/s
[download] Destination: Hard Machine (LEVEL SHOWCASE) [GNDfLEKUhag].f251.webm
[download] 100% of    1.77MiB in 00:00:00 at 9.70MiB/s
[Merger] Merging formats into "Hard Machine (LEVEL SHOWCASE) [GNDfLEKUhag].webm"
Deleting original file Hard Machine (LEVEL SHOWCASE) [GNDfLEKUhag].f308.webm (pass -k to keep)
Deleting original file Hard Machine (LEVEL SHOWCASE) [GNDfLEKUhag].f251.webm (pass -k to keep)
't' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by Grub4K** [comment]
This is a shell problem. `&` has special meaning in cmd. You want to quote the url, like this:
```console
yt-dlp "https://www.youtube.com/watch?v=GNDfLEKUhag&t=24s"
```

**Comment by Foxiseminger** [comment]
ok fixed it
