### ISSUE TITLE
after the video has been downloaded, where is it stored?

### ISSUE THREAD

**Issue by Foxiseminger** [yt-dlp/yt-dlp#11406]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

it downloaded the video but where is the output?

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by Grub4K** [comment]
Its in the folder your shell was at when downloading the video. If you open another terminal window, it should be at the same point

**Comment by FoxyWorld1** [comment]
it's not in there also I ran yt-dlp from C:\Program Files\yt-dlp\yt-dlp.exe

**Comment by Bugg4** [comment]
Are you getting a `ERROR: unable to open for writing: [Errno 13] Permission denied` ?
You probably shouldn't download a video into a system folder in the first place.

try running it from the Desktop, or Documents, or any other folder in user space.

**Comment by Foxiseminger** [comment]
no not getting that error, but i fixed it anyways.

**Comment by Foxiseminger** [comment]
hey why did you dislike my comment @Bugg4

**Comment by Bugg4** [comment]
@Foxiseminger you closed the issue without saying how you fixed it.
Even if the solution was simple/trivial, imo it's good practice to at least say how it was solved.

**Comment by FoxyWorld1** [comment]
the cmd was open in C:\Users\foxis and the video was in that directory @Bugg4

**Comment by FoxyWorld1** [comment]
> @Foxiseminger you closed the issue without saying how you fixed it.
> Even if the solution was simple/trivial, imo it's good practice to at least say how it was solved.

sorry whoops
