### ISSUE TITLE
Importing configuration files, file decoding errors

### ISSUE THREAD

**Issue by leij0318** [yt-dlp/yt-dlp#11416]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I installed yt-dlp today to download youtube videos. After I got familiar with the command, I started using yt-dlp to download videos. Except for enabling aria2 and using cookies, there were errors (cookies were imported using files, and aria2 was cancelled because I used a proxy, so all the problems were solved).
But when I wrote the config file and put it in the `$USERPROFILE/.yt-dlp` folder, and used the command to download the video, it reported an error that I didn't expect!

```yt-dlp.exe: error: Unable to parse "C:\Users\22202\.yt-dlp\config": 'gbk' codec can't decode byte 0x80 in position 33: illegal multibyte sequence```

So I used the command `iconv -f utf-8 -t gbk config.txt -o config1.txt` to convert it to gbk encoding, but it still went wrong.
I used other editors to convert the encoding and enabled an experimental parameter of yt-dlp `--encoding`, but the error still occurred; I have no idea!

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp.exe: error: Unable to parse "C:\Users\22202\.yt-dlp\config": 'gbk' codec can't decode byte 0x80 in position 33: illegal multibyte sequence
```

**Comment by Grub4K** [comment]
Please show the complete verbose output when running `yt-dlp --ignore-config`. Is there anything special about your filesystem or system in general?

**Comment by leij0318** [comment]
> 请在运行时显示完整的详细输出 `yt-dlp --ignore-config`。您的文件系统或一般系统有什么特别之处吗？

I have found the reason. It was because I used Chinese characters in the comments of the configuration file. I changed the comments to English and there was no problem.
The main problem now is that I cannot enable the aria2 function to speed up downloading (the reason why I use the system proxy) and each time I download a video, I need to use the browser extension to export the cookie file for downloading.
The yt-dlp tool is very powerful, but lacks a GUI interface to adapt it！

**Comment by bashonly** [comment]
> The main problem now is that I cannot enable the aria2 function to speed up downloading (the reason why I use the system proxy) 

Why is this a problem? Seems unrelated to your original issue. What is going wrong? Please share complete verbose output

> each time I download a video, I need to use the browser extension to export the cookie file for downloading.

If you're talking about youtube cookies, see this section of the wiki on how to achieve long-lasting YT cookies: https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies

**Comment by leij0318** [comment]
> 为什么这是一个问题？似乎与您原来的问题无关。出了什么问题？请分享完整的详细输出
I have looked up the relevant issue and found that it is a problem of enabling aria2 when yt-dlp uses the system proxy, but I saw that the relevant developer did not answer the question, and the same is true in the aria2 official github (also did not answer the question)，so I cancelled the aria2 parameter .
`--downloader aria2c --downloader-args aria2c:"-c -j 3 -x 8 -k 1M`
As for the debugging information, it is in the aria2-related issue. You can search for the keyword aria2 to see that the error is the same. I have understood the use of YouTube cookies, thanks for your help.

Okay, I gonna close this issue.
