### ISSUE TITLE
add directory sort in youtube

### ISSUE THREAD

**Issue by alphaleadership** [yt-dlp/yt-dlp#11417]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a site-specific feature
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

n/a

### Example URLs

https://www.youtube.com/@SamEckholm

### Provide a description that is worded well enough to be understood

y suggest when you dowload a youtube channel to create 2 dir video and short 

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
n/a
```

**Comment by bashonly** [comment]
you can do this by passing these options
```
--parse-metadata "playlist_title:.+ - (?P<folder_name>Videos|Shorts|Live)$" -o "./%(folder_name|)s/%(title)s [%(id)s].%(ext)s"
```

**Comment by alphaleadership** [comment]
ok and y suppose y can extract channel to create channel folder

**Comment by alphaleadership** [comment]
thanks

**Comment by alphaleadership** [comment]
ytdlp -vU  https://www.youtube.com/channel/UCAOUTJyHMjLgLcu71xMEyAQ --parse-metadata "playlist_title:.+ - (?P<folder_name>Videos|Shorts|Live)$" -o "./%(channel|)s/%(folder_name|)s/%(title)s [%(id)s].%(ext)s" whatis the error with this command

**Comment by alphaleadership** [comment]
is in cmd file

**Comment by alphaleadership** [comment]
is patch
