### ISSUE TITLE
Tiktok videos downloading with wrong Extension

### ISSUE THREAD

**Issue by harshbhardwaj77** [yt-dlp/yt-dlp#11419]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Provide a description that is worded well enough to be understood

I am ttrying to download videos from Tiktok. **But instead of .mp4 file , they get downloaded as mp4'** . I have to rename all the videos. Is there a fix for this ?

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp  -f  bv*+ba/b' -vU  -o   /Tiktok/X/%(uploader)s-%(title)s-%(upload_date)s-%(autonumber)s.%(ext)s' https://www.tiktok.com/@livvy/video/7430934186623569198?is_from_webapp=1&sender_device=pc&web_id=7408823273708766728 is_from_webapp=1&sender_device=pc&web_id=7408823273708766728
[debug] Command-line config: ['-f', "bv*+ba/b'", '-vU', '-o', "/Tiktok/X/%(uploader)s-%(title)s-%(upload_date)s-%(autonumber)s.%(ext)s'", 'https://www.tiktok.com/@livvy/video/7430934186623569198?is_from_webapp=1']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.10.22 from yt-dlp/yt-dlp [67adeb7ba] (pip)
[debug] Python 3.11.5 (CPython AMD64 64bit) - Windows-10-10.0.22621-SP0 (OpenSSL 3.0.9 30 May 2023)
[debug] exe versions: ffmpeg N-117622-g8d940a07d1-20241021 (setts), ffprobe N-117622-g8d940a07d1-20241021
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.08.30, mutagen-1.47.0, requests-2.32.3, sqlite3-3.42.0, urllib3-2.2.2, websockets-13.0.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1839 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.10.22 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.10.22 from yt-dlp/yt-dlp)
[TikTok] Extracting URL: https://www.tiktok.com/@livvy/video/7430934186623569198?is_from_webapp=1
[TikTok] 7430934186623569198: Downloading webpage
[debug] [TikTok] Found universal data for rehydration
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[info] 7430934186623569198: Downloading 1 format(s): bytevc1_1080p_2492365-1
[debug] Invoking http downloader on "https://v19-webapp-prime.tiktok.com/video/tos/maliva/tos-maliva-ve-0068c799-us/oEcJJ4fK8NUIi0LM4MRAOzAQifAeAtFfWxfgBG/?a=1988&bti=ODszNWYuMDE6&ch=0&cr=3&dr=0&lr=all&cd=0%7C0%7C0%7C&cv=1&br=4866&bt=2433&cs=2&ds=4&ft=-Csk_mugPD12NBe9KE-Ux-eFaY6e3wv25AcAp&mime_type=video_mp4&qs=15&rc=ZjlkMzozNzY7aTU8NjRmPEBpM201ams5cjh5djMzZzczNEBhNmE1LWIxXmMxNGJfL2IwYSMtM2djMmRraWNgLS1kMS9zcw%3D%3D&btag=e00088000&expire=1730407626&l=202410311446585919DD340843B90D47E1&ply_type=2&policy=2&signature=26550321449fa278b408253f97158422&tk=tt_chain_token"
[debug] File locking is not supported. Proceeding without locking
[download] Destination: \Tiktok\X\livvy-this leo is utopia #foryou #gymnastics #lsu -20241028-00001.mp4'
[download] 100% of    2.34MiB in 00:00:13 at 176.40KiB/s
'sender_device' is not recognized as an internal or external command,
operable program or batch file.
'web_id' is not recognized as an internal or external command,
operable program or batch file.
'sender_device' is not recognized as an internal or external command,
operable program or batch file.
'web_id' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by bashonly** [comment]
it's a quoting issue in your command. there is a stray `'` at the end of your `-o` argument

**Comment by harshbhardwaj77** [comment]
> it's a quoting issue in your command. there is a stray `'` at the end of your `-o` argument
Damn. Thank you. Maybe i should remove this question LOL.  I have another question though.   yt-dlp doesnt download tiktoks with photos. Is there a way to download them too

**Comment by bashonly** [comment]
Downloading photo slideshows has determined to be out-of-scope for yt-dlp, see: #6217, #6168

If Tiktok actually serves the slideshow as a video file, that would be a different story. But no one requesting support for TT slideshows has made that claim (or provided necessary evidence)
