### ISSUE TITLE
The extracted extension ('vid') is unusual and will be skipped for safety reasons.

### ISSUE THREAD

**Issue by McBain789** [yt-dlp/yt-dlp#11412]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

When I want to download a video from an URL that provides a *.vid file format, I get the following error:

The extracted extension ('vid') is unusual and will be skipped for safety reasons.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['https://c11.trafficdeposit.com/vidi/h72qaj082qzr8m2o066szn9u0sfc0wzo4i4y0y1mz61l1x58erzd6t9c9v0gzn7r1lap2yzg6k7f9f7/1ehQqS0M_wztBqZoqUzHLQ/1730290329/5f38c5670bd25/67114d5cec201.vid', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.10.22 from yt-dlp/yt-dlp [67adeb7ba] (pip)
[debug] Python 3.13.0 (CPython arm64 64bit) - macOS-15.1-arm64-arm-64bit-Mach-O (OpenSSL 3.4.0 22 Oct 2024)
[debug] exe versions: ffmpeg 7.1 (setts), ffprobe 7.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.21.0, brotli-1.1.0, certifi-2024.08.30, mutagen-1.47.0, requests-2.32.3, sqlite3-3.47.0, urllib3-2.2.3, websockets-13.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1839 extractors
[generic] Extracting URL: https://c11.trafficdeposit.com/vidi/h72qaj082qzr8m2o066szn9u0sfc0wzo4i4y0y1mz61l1x58erzd6t9c9v0gzn7r1lap2yzg6k7f9f7/1ehQqS0M_wztBqZoqUzHLQ/1730290329/5f38c5670bd25/67114d5cec201.vid
[generic] 67114d5cec201: Downloading webpage
[debug] Identified a direct video link
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 67114d5cec201: Downloading 1 format(s): fmp4
ERROR: The extracted extension ('vid') is unusual and will be skipped for safety reasons. If you believe this is an error, please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/yt-dlp/2024.10.22/libexec/lib/python3.13/site-packages/yt_dlp/YoutubeDL.py", line 178, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/homebrew/Cellar/yt-dlp/2024.10.22/libexec/lib/python3.13/site-packages/yt_dlp/YoutubeDL.py", line 3478, in process_info
    dl_filename = existing_video_file(full_filename, temp_filename)
  File "/opt/homebrew/Cellar/yt-dlp/2024.10.22/libexec/lib/python3.13/site-packages/yt_dlp/YoutubeDL.py", line 3370, in existing_video_file
    file = self.existing_file(itertools.chain(*zip(map(converted, filepaths), filepaths)),
                              ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/yt-dlp/2024.10.22/libexec/lib/python3.13/site-packages/yt_dlp/YoutubeDL.py", line 3369, in <lambda>
    converted = lambda file: replace_extension(file, self.params.get('final_ext') or ext, ext)
                             ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/yt-dlp/2024.10.22/libexec/lib/python3.13/site-packages/yt_dlp/utils/_utils.py", line 2144, in _change_extension
    return f'{filename}.{_UnsafeExtensionError.sanitize_extension(ext)}'
                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/opt/homebrew/Cellar/yt-dlp/2024.10.22/libexec/lib/python3.13/site-packages/yt_dlp/utils/_utils.py", line 5219, in sanitize_extension
    raise cls(extension)
yt_dlp.utils._UnsafeExtensionError: unsafe file extension: 'vid'
```

**Comment by bashonly** [comment]
https://github.com/yt-dlp/yt-dlp?tab=readme-ov-file#differences-in-default-behavior

> The following compat options restore vulnerable behavior from before security patches:
>
> * `--compat-options allow-unsafe-ext`: Allow files with any extension (including unsafe ones) to be downloaded ([GHSA-79w7-vh3h-8g4j](<https://github.com/yt-dlp/yt-dlp/security/advisories/GHSA-79w7-vh3h-8g4j>))
>
>     > :warning: Only use if a valid file download is rejected because its extension is detected as uncommon


#10585
