### ISSUE TITLE
rutube shorts error

### ISSUE THREAD

**Issue by tellts** [yt-dlp/yt-dlp#11415]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Russia

### Provide a description that is worded well enough to be understood

Microsoft Windows [Version 10.0.19045.5011]
(c) Корпорация Майкрософт (Microsoft Corporation). Все права защищены.

C:\Users\admin>yt-dlp -vU yt-dlp  -f "bv*[height<=360]+ba/b[height<=360] / wv*+ba/w" -S res,ext:mp4:m4a --recode mp4 --write-thumbnail --convert-thumbnails jpg -a F:\yt-dlp\sel.txt -o "e:\ioni\%(uploader)s\%(title)s-%(id)s.%(ext)s" --ffmpeg-location="F:\yt-dlp\ffmpeg.exe"
[debug] Command-line config: ['-vU', 'yt-dlp', '-f', 'bv*[height<=360]+ba/b[height<=360] / wv*+ba/w', '-S', 'res,ext:mp4:m4a', '--recode', 'mp4', '--write-thumbnail', '--convert-thumbnails', 'jpg', '-a', 'F:\\yt-dlp\\sel.txt', '-o', 'e:\\ioni\\%(uploader)s\\%(title)s-%(id)s.%(ext)s', '--ffmpeg-location=F:\\yt-dlp\\ffmpeg.exe']

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Batch file urls: ['https://rutube.ru/channel/25902603/shorts/']
[debug] Encodings: locale cp1251, fs utf-8, pref cp1251, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.10.07 from yt-dlp/yt-dlp [1a176d874] (pip)
[debug] Python 3.11.2 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1s  1 Nov 2022)
[debug] exe versions: ffmpeg N-89061-g6d00905f81-sherpya (needs_adtstoasc), ffprobe n5.0-3-ga394d35a43-20220129
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.0.9, certifi-2021.10.08, mutagen-1.47.0, requests-2.32.3, sqlite3-3.39.4, urllib3-2.2.1, websockets-13.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1838 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
[debug] Downloading _update_spec from https://github.com/yt-dlp/yt-dlp/releases/latest/download/_update_spec
Current version: stable@2024.10.07 from yt-dlp/yt-dlp
Latest version: stable@2024.10.22 from yt-dlp/yt-dlp
ERROR: You installed yt-dlp with pip or using the wheel from PyPi; Use that to update
[generic] Extracting URL: https://rutube.ru/channel/25902603/shorts/
[generic] shorts: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] shorts: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://rutube.ru/channel/25902603/shorts/
Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\yt_dlp\YoutubeDL.py", line 1626, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\yt_dlp\YoutubeDL.py", line 1761, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\yt_dlp\extractor\common.py", line 741, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\yt_dlp\extractor\generic.py", line 2526, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://rutube.ru/channel/25902603/shorts/

[CommonMistakes] Extracting URL: yt-dlp
ERROR: [CommonMistakes] You've asked yt-dlp to download the URL "yt-dlp". That doesn't make any sense. Simply remove the parameter in your command or configuration.
  File "C:\Python311\Lib\site-packages\yt_dlp\extractor\common.py", line 741, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\yt_dlp\extractor\commonmistakes.py", line 25, in _real_extract
    raise ExtractorError(msg, expected=True)


C:\Users\admin>
```

**Comment by dirkf** [comment]
From the error message
>You've asked yt-dlp to download the URL "yt-dlp". That doesn't make any sense. Simply remove the parameter in your command or configuration.

The URL ending in `/shorts/` is not supported, but the shorts results should be included in the `/videos/` results; you can't distinguish them by the URL formats.

To get separate shorts/non-shorts lists (they seem to be called `rshorts` and`rtb`, s/t like this:
```diff
--- old/yt-dlp/yt_dlp/extractor/rutube.py
+++ new/yt-dlp/yt_dlp/extractor/rutube.py
@@ -357,6 +357,33 @@
@@ -349,7 +349,7 @@
 
 class RutubeChannelIE(RutubePlaylistBaseIE):
     IE_NAME = 'rutube:channel'
-    IE_DESC = 'Rutube channel'
+    IE_DESC = 'Rutube channel videos'
     _VALID_URL = r'https?://rutube\.ru/channel/(?P<id>\d+)/videos'
     _TESTS = [{
         'url': 'https://rutube.ru/channel/639184/videos/',
@@ -357,6 +357,33 @@
             'id': '639184',
         },
         'playlist_mincount': 133,
-    }]
-
-    _PAGE_TEMPLATE = 'http://rutube.ru/api/video/person/%s/?page=%s&format=json'
+    }, {
+        'url': 'https://rutube.ru/channel/25902603/shorts/',
+        'info_dict': {
+            'id': '25902603',
+        },
+        'playlist_count': 129,
+    }]
+
+    _PAGE_TEMPLATE = 'http://rutube.ru/api/video/person/%s/?origin_type=rtb&page=%s&format=json'
+
+
+class RutubeChannelShortsIE(RutubePlaylistBaseIE):
+    IE_NAME = 'rutube:channel:shorts'
+    IE_DESC = 'Rutube channel shorts'
+    _VALID_URL = r'https?://rutube\.ru/channel/(?P<id>\d+)/shorts'
+    _TESTS = [{
+        'url': 'https://rutube.ru/channel/639184/shorts/',
+        'info_dict': {
+            'id': '639184',
+        },
+        'playlist_count': 0,
+    }, {
+        'url': 'https://rutube.ru/channel/25902603/shorts/',
+        'info_dict': {
+            'id': '25902603',
+        },
+        'playlist_count': 276,
+    }]
+
+    _PAGE_TEMPLATE = 'http://rutube.ru/api/video/person/%s/?origin_type=rshorts&page=%s&format=json'
```

**Comment by tellts** [comment]
Microsoft Windows [Version 10.0.19045.5011]
(c) Корпорация Майкрософт (Microsoft Corporation). Все права защищены.

C:\Users\admin>cd G:\gig\yt-dlp

C:\Users\admin>g:

G:\gig\yt-dlp>yt-dlp.exe  -P "g:\gig\yt-dlp\1kachaem" -a sel.txt
[generic] Extracting URL: https://rutube.ru/channel/47052171/
[generic] 47052171: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] 47052171: Extracting information
ERROR: Unsupported URL: https://rutube.ru/channel/47052171/

G:\gig\yt-dlp>
