### ISSUE TITLE
[netrc] empty string parsing for Python <=3.10

### ISSUE THREAD

**Issue by idMysteries** [yt-dlp/yt-dlp#11413]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

I'm sorry that I'm not submitting the issue correctly. But this will be enough to resolve the issue.

In the past, I wrote that oauth authorization is required every time https://github.com/yt-dlp/yt-dlp/pull/11001#issuecomment-2428913707. Now I realized that it was because of netrc.

As you can see below, when netrc is enabled, the token is not read from the cache, but is replaced with "" (the token in the cache is replaced with quotes)

As far as I understand, this is incorrect behavior, since the use of .netrc is essentially only needed to not apply authorization to all sites, but only to the selected one (youtube in my case)

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
WITH NETRC:
[debug] [youtube:subscriptions] Using netrc for youtube authentication
[debug] Saving youtube.oauth_refresh_token_default to cache

WITHOUT:
[debug] Loading youtube.oauth_refresh_token_default from cache
```

**Comment by bashonly** [comment]
please share complete verbose logs

**Comment by idMysteries** [comment]
```
[debug] Command-line config: ['-v', ':ytsubs', '--match-filters', '!is_live & duration < 200', '--no-wait-for-video', '--username', 'PRIVATE', '--password', 'PRIVATE']
[debug] Portable config "C:\Program Files\mpv\yt-dlp.conf": ['-f', 'bv*[height<=1200]+ba/b[height<=1200] / wv*+ba/w', '--no-check-certificates', '--yes-playlist', '--embed-metadata', '--parse-metadata', 'title:%(meta_title)s', '--mark-watched', '--buffer-size', '1M', '--write-sub', '--sub-lang', 'ru', '--ignore-errors', '--fragment-retries', '30', '--concurrent-fragments', '3', '--wait-for-video', '15', '--compat-options', 'no-youtube-unavailable-videos', '--downloader-args', 'ffmpeg:-loglevel warning -stats', '--download-archive', 'F:\\mpv\\archive.txt', '--sponsorblock-mark', 'all', '-P', 'F:/Videos', '-o', '%(uploader|)s/%(playlist|)s/%(upload_date>%Y-%m-%d - |)s%(title).150s%(id& [{}]|)s.%(ext)s']
[debug] Encodings: locale cp1251, fs utf-8, pref cp1251, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.10.29.232854 from yt-dlp/yt-dlp-nightly-builds [5bc5fb283] (win_exe)
[debug] Compatibility options: no-youtube-unavailable-videos
[debug] Python 3.10.11 (CPython AMD64 64bit) - Windows-10-10.0.22631-SP0 (OpenSSL 1.1.1t  7 Feb 2023)
[debug] exe versions: ffmpeg N-117673-gbb57b7801 (setts), ffprobe N-115976-g0b67c83b2e-20240623
[debug] Optional libraries: Cryptodome-3.21.0, brotli-1.1.0, certifi-2024.08.30, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.40.1, urllib3-2.2.3, websockets-13.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1837 extractors
[debug] Loading archive file 'F:\\mpv\\archive.txt'
[debug] Loading youtube.oauth_refresh_token_default from cache
[youtube:subscriptions] oauth: Refreshing access token
[debug] [youtube:subscriptions] oauth: Logged in using profile "default"
[youtube:subscriptions] Extracting URL: :ytsubs
[debug] [youtube:tab] oauth: Using cached access token for profile "default"
[youtube:tab] Extracting URL: https://www.youtube.com/feed/subscriptions
[youtube:tab] subscriptions: Downloading webpage
[download] Downloading playlist: subscriptions
[youtube:tab] subscriptions page 1: Downloading API JSON
[youtube:tab] subscriptions page 2: Downloading API JSON
[youtube:tab] subscriptions page 3: Downloading API JSON
[youtube:tab] subscriptions page 4: Downloading API JSON
```

**Comment by bashonly** [comment]
and what does the `machine youtube` line in your netrc file look like? can you copy/paste here in a code block (only that line)?

**Comment by idMysteries** [comment]
with netrc:
```
[debug] Command-line config: ['-v', ':ytsubs', '--match-filters', '!is_live & duration < 200', '--no-wait-for-video', '--netrc']
[debug] Portable config "C:\Program Files\mpv\yt-dlp.conf": ['-f', 'bv*[height<=1200]+ba/b[height<=1200] / wv*+ba/w', '--no-check-certificates', '--yes-playlist', '--embed-metadata', '--parse-metadata', 'title:%(meta_title)s', '--mark-watched', '--buffer-size', '1M', '--write-sub', '--sub-lang', 'ru', '--ignore-errors', '--fragment-retries', '30', '--concurrent-fragments', '3', '--wait-for-video', '15', '--compat-options', 'no-youtube-unavailable-videos', '--downloader-args', 'ffmpeg:-loglevel warning -stats', '--download-archive', 'F:\\mpv\\archive.txt', '--sponsorblock-mark', 'all', '-P', 'F:/Videos', '-o', '%(uploader|)s/%(playlist|)s/%(upload_date>%Y-%m-%d - |)s%(title).150s%(id& [{}]|)s.%(ext)s']
[debug] Encodings: locale cp1251, fs utf-8, pref cp1251, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.10.29.232854 from yt-dlp/yt-dlp-nightly-builds [5bc5fb283] (win_exe)
[debug] Compatibility options: no-youtube-unavailable-videos
[debug] Python 3.10.11 (CPython AMD64 64bit) - Windows-10-10.0.22631-SP0 (OpenSSL 1.1.1t  7 Feb 2023)
[debug] exe versions: ffmpeg N-117673-gbb57b7801 (setts), ffprobe N-115976-g0b67c83b2e-20240623
[debug] Optional libraries: Cryptodome-3.21.0, brotli-1.1.0, certifi-2024.08.30, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.40.1, urllib3-2.2.3, websockets-13.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1837 extractors
[debug] Loading archive file 'F:\\mpv\\archive.txt'
[debug] [youtube:subscriptions] Using netrc for youtube authentication
[debug] Saving youtube.oauth_refresh_token_default to cache
[youtube:subscriptions] oauth: Refreshing access token
WARNING: [youtube:subscriptions] oauth: Failed to refresh access token: Refresh token is invalid, revoked, or expired (invalid_grant)
[youtube:subscriptions] oauth: Initializing authorization flow
[youtube:subscriptions] oauth: To give yt-dlp access to your account, go to 
```

**Comment by idMysteries** [comment]
```
machine youtube login oauth password ""
```

**Comment by idMysteries** [comment]
the token in the cache is replaced with quotes
```
{"yt-dlp_version": "2024.10.29.232854", "data": "\"\""}
```

**Comment by bashonly** [comment]
cc @coletdjnz

**Comment by bashonly** [comment]
I can't repro the issue on Python 3.12

Looks like there was a change in Python's `netrc` stdlib module in 3.11: https://github.com/python/cpython/commit/15409c720be0503131713e3d3abc1acd0da07378
```
      The entry in the netrc file no longer needs to contain all tokens.  The missing
      tokens' value default to an empty string.  All the tokens and their values now
      can contain arbitrary characters, like whitespace and non-ASCII characters.
      If the login name is anonymous, it won't trigger the security check.
```
so it's impossible to pass an empty string password via netrc file in Python versions 3.10 and older (the yt-dlp `win_exe` builds are 3.8/3.10)

**Comment by idMysteries** [comment]
Oh... Fixed, lol
```
machine youtube login oauth password ''
```

**Comment by bashonly** [comment]
> ```
> machine youtube login oauth password ''
> ```

This only works due to some user-error-correcting code we have in the youtube extractor. It is a temporary workaround, not a proper solution. It may stop working at any time

**Comment by bashonly** [comment]
The documentation's suggestion of `machine youtube login oauth password ""` will work after #11414 is merged and makes its way into the release you use. At that time it is strongly recommended you change the line in your netrc back to that

**Comment by leij0318** [comment]
@bashonly 

Why is it that every time I use oauth to download youtube videos, it prompts that the previous oauth is not working? Is there a good solution for this?
