### ISSUE TITLE
[Archive.org] Index out of range

### ISSUE THREAD

**Issue by NanaMizukiAnother7** [yt-dlp/yt-dlp#11411]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

U.S.A.

### Provide a description that is worded well enough to be understood

After Archive.org is down for more than a week, when you attempt to download a video, it throws a "list index out of range" error and therefore cannot be downloaded.

EDIT: It was caused by JSPlayer failing to load.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-o', 'd:\\Google Drive & YouTube Video Downloads and more\\%(title)s.%(ext)s', 'https://archive.org/details/dvd-transfer-27', '-v']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version master@2024.10.29.233233 from yt-dlp/yt-dlp-master-builds [5bc5fb283] (win_exe)
[debug] Python 3.10.11 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1t  7 Feb 2023)
[debug] exe versions: ffmpeg 6.1-full_build-www.gyan.dev (setts), ffprobe 6.1-full_build-www.gyan.dev, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.21.0, brotli-1.1.0, certifi-2024.08.30, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.40.1, urllib3-2.2.3, websockets-13.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1837 extractors
[archive.org] Extracting URL: https://archive.org/details/dvd-transfer-27
[archive.org] dvd-transfer-27: Downloading webpage
ERROR: list index out of range
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1625, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1760, in __extract_info
  File "yt_dlp\extractor\common.py", line 742, in extract
  File "yt_dlp\extractor\archiveorg.py", line 229, in _real_extract
  File "yt_dlp\extractor\archiveorg.py", line 212, in _playlist_data
IndexError: list index out of range
```

**Comment by bashonly** [comment]
> EDIT: It was caused by JSPlayer failing to load.

The media doesn't load in browser either?

**Comment by NanaMizukiAnother7** [comment]
> > EDIT: It was caused by JSPlayer failing to load.
> 
> The media doesn't load in browser either?

Yes. It does not load for me.

**Comment by bashonly** [comment]
If it won't load in browser, then it's expected that yt-dlp can't load it either. Ideally our error handling would be better here, but I don't see a reliably way to distinguish between a site-side problem and an extractor bug
