### ISSUE TITLE
Support for fjernleje.filmstriben.dk

### ISSUE THREAD

**Issue by Laurentius-mp3** [yt-dlp/yt-dlp#11428]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Denmark

### Example URLs

https://fjernleje.filmstriben.dk/film/9000006575/en-frokost-pa-bjerget
https://fjernleje.filmstriben.dk/film/9000006092/delicieux

### Provide a description that is worded well enough to be understood

I'm unable to download a video file that i am watching on a streaming platform that let's user rent movies.
When i use yt-dlp, terminal states that the url is unsupported. I've looked for a .m3u8 url witout luck, i tried using cookies and all sorts 

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] yt-dlp -vU "https://fjernleje.filmstriben.dk/film/9000006575/en-frokost-pa-bjerget"
[debug] Command-line config: ['-vU', 'https://fjernleje.filmstriben.dk/film/9000006575/en-frokost-pa-bjerget']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.10.22 from yt-dlp/yt-dlp [67adeb7ba] (pip)
[debug] Python 3.13.0 (CPython arm64 64bit) - macOS-14.4-arm64-arm-64bit-Mach-O (OpenSSL 3.4.0 22 Oct 2024)
[debug] exe versions: ffmpeg 7.1 (setts), ffprobe 7.1
[debug] Optional libraries: Cryptodome-3.21.0, brotli-1.1.0, certifi-2024.08.30, mutagen-1.47.0, requests-2.32.3, sqlite3-3.47.0, urllib3-2.2.3, websockets-13.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1839 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.10.22 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.10.22 from yt-dlp/yt-dlp)
[generic] Extracting URL: https://fjernleje.filmstriben.dk/film/9000006575/en-frokost-pa-bjerget
[generic] en-frokost-pa-bjerget: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] en-frokost-pa-bjerget: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://fjernleje.filmstriben.dk/film/9000006575/en-frokost-pa-bjerget
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/yt-dlp/2024.10.22/libexec/lib/python3.13/site-packages/yt_dlp/YoutubeDL.py", line 1625, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/homebrew/Cellar/yt-dlp/2024.10.22/libexec/lib/python3.13/site-packages/yt_dlp/YoutubeDL.py", line 1760, in __extract_info
    ie_result = ie.extract(url)
  File "/opt/homebrew/Cellar/yt-dlp/2024.10.22/libexec/lib/python3.13/site-packages/yt_dlp/extractor/common.py", line 741, in extract
    ie_result = self._real_extract(url)
  File "/opt/homebrew/Cellar/yt-dlp/2024.10.22/libexec/lib/python3.13/site-packages/yt_dlp/extractor/generic.py", line 2533, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://fjernleje.filmstriben.dk/film/9000006575/en-frokost-pa-bjerget
```

**Comment by dirkf** [comment]
You need to be using the page that appears when you `Se nu` the movie. If it's the same URL, or perhaps anyway, you'd need to pass cookies from your logged-in browser session for _yt-dlp_ to have a chance of finding any media links. Even so, the site may be providing them through JS, and in that case a developer with a site account would have to analyse the site's JS and page traffic to create an extractor.

**Comment by bashonly** [comment]
OP can you also [test if the video plays in your browser with disabled](https://github.com/yt-dlp/yt-dlp/issues/4062#issuecomment-1153474056) please

**Comment by pukkandan** [comment]
Closed due to inactivity
