### ISSUE TITLE
Extract links on youtube about page

### ISSUE THREAD

**Issue by salmansarwar5102** [yt-dlp/yt-dlp#11423]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a site-specific feature
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

pakistan

### Example URLs

https://www.youtube.com/@morganjingram/about

![image](https://github.com/user-attachments/assets/0bc52f68-f665-4612-91e1-5695c37c81c4)

### Provide a description that is worded well enough to be understood

I am using this command : yt-dlp --write-info-json --ignore-no-formats "https://www.youtube.com/@morganjingram/about"

it gives out json of every data displayed on the about page but the links of socials or website are not included.

is it possible to include links in the json.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
{"id": "@morganjingram", "channel": "Morgan J Ingram", "channel_id": "UCnhg__lkPcrdr2zqLu5kwUQ", "title": "Morgan J Ingram", "channel_follower_count": 1380, "description": "Making videos on B2B sales, influencer marketing and LinkedIn to help you generate pipeline. \n\nDocumenting my journey as a bootstrap founder.\n", "tags": [], "thumbnails": [{"url": "https://yt3.googleusercontent.com/ajD3pS7bMu37YxqTvMprVx_aiQuqTDPNA80KU_WG7I6IeSJEaCs3hot6cyjfnuVe1ywZ8NQBYA=w1060-fcrop64=1,00005a57ffffa5a8-k-c0xffffffff-no-nd-rj", "height": 175, "width": 1060, "preference": -10, "id": "0", "resolution": "1060x175"}, {"url": "https://yt3.googleusercontent.com/ajD3pS7bMu37YxqTvMprVx_aiQuqTDPNA80KU_WG7I6IeSJEaCs3hot6cyjfnuVe1ywZ8NQBYA=w1138-fcrop64=1,00005a57ffffa5a8-k-c0xffffffff-no-nd-rj", "height": 188, "width": 1138, "preference": -10, "id": "1", "resolution": "1138x188"}, {"url": "https://yt3.googleusercontent.com/ajD3pS7bMu37YxqTvMprVx_aiQuqTDPNA80KU_WG7I6IeSJEaCs3hot6cyjfnuVe1ywZ8NQBYA=w1707-fcrop64=1,00005a57ffffa5a8-k-c0xffffffff-no-nd-rj", "height": 283, "width": 1707, "preference": -10, "id": "2", "resolution": "1707x283"}, {"url": "https://yt3.googleusercontent.com/ajD3pS7bMu37YxqTvMprVx_aiQuqTDPNA80KU_WG7I6IeSJEaCs3hot6cyjfnuVe1ywZ8NQBYA=w2120-fcrop64=1,00005a57ffffa5a8-k-c0xffffffff-no-nd-rj", "height": 351, "width": 2120, "preference": -10, "id": "3", "resolution": "2120x351"}, {"url": "https://yt3.googleusercontent.com/ajD3pS7bMu37YxqTvMprVx_aiQuqTDPNA80KU_WG7I6IeSJEaCs3hot6cyjfnuVe1ywZ8NQBYA=w2276-fcrop64=1,00005a57ffffa5a8-k-c0xffffffff-no-nd-rj", "height": 377, "width": 2276, "preference": -10, "id": "4", "resolution": "2276x377"}, {"url": "https://yt3.googleusercontent.com/ajD3pS7bMu37YxqTvMprVx_aiQuqTDPNA80KU_WG7I6IeSJEaCs3hot6cyjfnuVe1ywZ8NQBYA=w2560-fcrop64=1,00005a57ffffa5a8-k-c0xffffffff-no-nd-rj", "height": 424, "width": 2560, "preference": -10, "id": "5", "resolution": "2560x424"}, {"url": "https://yt3.googleusercontent.com/ajD3pS7bMu37YxqTvMprVx_aiQuqTDPNA80KU_WG7I6IeSJEaCs3hot6cyjfnuVe1ywZ8NQBYA=s0", "id": "banner_uncropped", "preference": -5}, {"url": "https://yt3.googleusercontent.com/lOd8J3ugPV72fvDGR1y1vKFEdHsWd4A8UvVVSQEx3sQDDpF6iVq3h6G3fFT71X50w6zBF3frK_U=s900-c-k-c0x00ffffff-no-rj", "height": 900, "width": 900, "id": "7", "resolution": "900x900"}, {"url": "https://yt3.googleusercontent.com/lOd8J3ugPV72fvDGR1y1vKFEdHsWd4A8UvVVSQEx3sQDDpF6iVq3h6G3fFT71X50w6zBF3frK_U=s0", "id": "avatar_uncropped", "preference": 1}], "uploader_id": "@morganjingram", "uploader_url": "https://www.youtube.com/@morganjingram", "playlist_count": 0, "uploader": "Morgan J Ingram", "channel_url": "https://www.youtube.com/channel/UCnhg__lkPcrdr2zqLu5kwUQ", "_type": "playlist", "webpage_url": "https://www.youtube.com/@morganjingram/about", "webpage_url_basename": "about", "webpage_url_domain": "youtube.com", "extractor": "youtube:tab", "extractor_key": "YoutubeTab", "epoch": 1730445247, "_version": {"version": "2024.10.22", "release_git_head": "67adeb7bab00662ba55d473e405b301abb42fe61", "repository": "yt-dlp/yt-dlp"}}
```

**Comment by bashonly** [comment]
This is out-of-scope IMO. There is no appropriate field to extract this data to. yt-dlp is not a linktree scraper

**Comment by salmansarwar5102** [comment]
YT-DLP does scrape metadata in JSON format, which can be considered somewhat out of scope since the "About" section is not directly related to audio or video downloads. However, if the implementation of a feature to extract links from this section isn't overly complicated, it would be beneficial to include it. This enhancement could improve the utility of the tool for users who want a more comprehensive view of the content associated with the media they are downloading.

**Comment by bashonly** [comment]
Using an LLM to argue in favor of your request is only gonna make me close this faster

**Comment by salmansarwar5102** [comment]
I always write my own content and ask GPT to make it read well since i am not a native speaker. sit down and relax!

**Comment by seproDev** [comment]
Why should I care what some AI wrote, when you can't even be bothered to write it yourself?
I'd much rather read your thoughts and ideas, even if in broken English, than some generic AI response.

Regarding your request, I don't see a yt-dlp info dict field in to which this data fits. yt-dlp is an audio/video downloader. Not a YouTube-specific site scraper. If you require this info, either grab it yourself from the API, write a yt-dlp plugin that returns this data in a custom info-dict field, or use another project that specializes in scraping all available info from YouTube.

**Comment by bashonly** [comment]
here's a plugin
```py
from yt_dlp.extractor.youtube import YoutubeTabIE
from yt_dlp.utils.traversal import traverse_obj


class YoutubeTab_AboutTabIE(YoutubeTabIE, plugin_name='AboutTab'):
    LINKS_FIELD_NAME = 'external_links'

    def _extract_metadata_from_tabs(self, item_id, data):
        info = super()._extract_metadata_from_tabs(item_id, data)
        about_channel_view_model = traverse_obj(data, (
            'onResponseReceivedEndpoints', ..., 'showEngagementPanelEndpoint',
            'engagementPanel', 'engagementPanelSectionListRenderer', 'content',
            'sectionListRenderer', 'contents', ..., 'itemSectionRenderer', 'contents',
            ..., 'aboutChannelRenderer', 'metadata', 'aboutChannelViewModel', {dict}, any))
        links = traverse_obj(about_channel_view_model, (
            'links', ..., 'channelExternalLinkViewModel', {
                'title': ('title', 'content', {str}),
                'url': ('link', 'content', {str}),
            }))
        if links:
            info[self.LINKS_FIELD_NAME] = links

        return info


__all__ = []
```
