### ISSUE TITLE
Add `Cache-Control`

### ISSUE THREAD

**Issue by Anuskuss** [yt-dlp/yt-dlp#11429]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Provide a description that is worded well enough to be understood

There's a supported site (I'd rather not tell) that doesn't let me download unless I add the `Cache-Control` header. The value doesn't seem to matter but I'd suggest `no-cache`. So my question is if there's any harm in adding that header unconditionally? I tested a few sites and none of them broke. Do you have a test suite with a bunch of links you can test this with?

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '***']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.10.22 from yt-dlp/yt-dlp [67adeb7ba]
[debug] Python 3.12.7 (CPython x86_64 64bit) - Linux-6.11.6-2-cachyos-x86_64-with-glibc2.40 (OpenSSL 3.4.0 22 Oct 2024, glibc 2.40)
[debug] exe versions: ffmpeg 7.0.2 (fdk,setts), ffprobe 7.0.2, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.20.0, brotlicffi-1.1.0.0, certifi-2024.08.30, requests-2.32.3, sqlite3-3.46.1, urllib3-1.26.20, websockets-12.0, xattr-0.10.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Loaded 1839 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.10.22 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.10.22 from yt-dlp/yt-dlp)
[***] Extracting URL: ***
[***] ***: Downloading webpage
ERROR: [***] ***: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: Forbidden>)
```

**Comment by bashonly** [comment]
> There's a supported site (I'd rather not tell) ...
> So my question is if there's any harm in adding that header unconditionally? 

We're not going to add this to the standard headers passed with every request to every site if it's only needed for 1 site. We can add it to the request headers for that 1 site. Closing as invalid. Can reopen if an unredacted log is shared

**Comment by Anuskuss** [comment]
I guess "if it ain't hurting" isn't a good reason to add something but I think you missed the grand point: Is `Cache-Control`, specifically `no-cache`, beneficial? Will the user benefit from servers respecting the setting, i.e. serving the latest copy of the media the user is trying to download? This was more of an attempt at discussion rather than a `site-bug` (and I probably shouldn't have filed it as such) and I was just explaining where it's coming from.
