### ISSUE TITLE
How to avoid merged file being written to temp dir before being copied to destination?

### ISSUE THREAD

**Issue by er013** [yt-dlp/yt-dlp#11435]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Using yt-dlp with -P "temp:/dev/shm" (while cwd is /mnt/). Youtube has reduced its ready-made formats, so mostly its video+audio nowadays. Yt-dlp correctly writes its initial audio and video formats to temp dir. But. It then proceeds to create resulting merged file also in there. Before moving it to destination. 

Am I missing something? How is final, merged file, considered temp file? Why is it not written directly to final destination?

Is there some way to specify it with yt-dlp, so it would behave that way (only temporary files to temp, merged file directly to destination) ?

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
"Merger" is just one of several postprocessors that yt-dlp calls upon, each independent of one another and without the knowledge if another postprocessor (e.g. the PP triggered by `--embed-thumbnail`) will be used after. All products of postprocessing are written to the temp dir. When the postprocessing stage is complete, then the final product is moved to the final destination dir

see https://github.com/yt-dlp/yt-dlp/issues/11172#issuecomment-2424150788, the discussion that follows, and the linked issues
