### ISSUE TITLE
Download encrypt live mpd and decrypt and restream with ffmpeg[Question]

### ISSUE THREAD

**Issue by duongpro2004** [yt-dlp/yt-dlp#1143]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

I have encrypt mdp link, i use this command to download and decrypt and restream it with ffmpeg
`yt-dlp  --allow-unplayable-formats https://sgn-vnpt-001-livecdn-vthn2-vnd.vieon.vn/f33d43d6ac3b3c47426eb630e930aec2/1633166506523/wz/livetv_origin_drm/kplus_phaimanh_22_08_2021.smil/manifest.mpd    -f bestvideo+bestaudio   -o -  | ffmpeg   -decryption_key 4f76d3ce1c8ce826ffa952220c8f499c -re -i - -vcodec copy -f mpegts udp://127.0.0.1:1234 `

But
- Yt-dlp don't auto refresh mpd link for download new segments , it just download to 100% and stop
- When i play decrypt video, it's only video, no audio, and yt-dlp show warning
_

 _**WARNING: You have requested merging of multiple formats while also allowing unplayable formats to be downloaded. The formats won't be merged to prevent data corruption.**_
 
 _**WARNING: You have requested downloading multiple formats to stdout using a downloader other than ffmpeg. The formats will be streamed one after the other**_

_

Is there any command to run it without the above problems?
Thanks!
Sorry for my English.

**Comment by pukkandan** [comment]
You seem to have missed the other warning
```
WARNING: You have asked for unplayable formats to be listed/downloaded. This is a developer option intended for debugging. If you experience any issues while using this option, DO NOT open a bug report
```
