### ISSUE TITLE
Workaround yt-dlp with cookies / Questions

### ISSUE THREAD

**Issue by BBugato** [yt-dlp/yt-dlp#11447]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Hello!

I have been using yt-dlp (formerly youtube-dl) for years. For months there has been the well-known problem with cookies. I have around 50 - 100,000 downloads a day. I always did it so that I had around 50 - 100 cookies (with different users logged in). But now YouTube blocks the account even after (100 requests) a NEW cookie. Is there a way to change that?

I use the latest version of yt-dlp. The accounts from the cookies are of course also blocked. The same thing even happens to cookies from premium accounts.

Is there anyone who also has a lot of downloads and can tell me a solution.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp -vU https://www.youtube.com/watch?v=tbItn2ec67A
[debug] Command-line config: ['-vU', 'https://www.youtube.com/watch?v=tbItn2ec67A']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.10.22 from yt-dlp/yt-dlp [67adeb7ba] (pip)
[debug] Python 3.9.2 (CPython x86_64 64bit) - Linux-5.10.0-33-amd64-x86_64-with-glibc2.31 (OpenSSL 1.1.1w  11 Sep 2023, glibc 2.31)
[debug] exe versions: ffmpeg 4.3.8-0, ffprobe 4.3.8-0, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.9.7, brotli-1.0.9, certifi-2020.06.20, mutagen-1.45.1, pyxattr-0.7.2, requests-2.25.1, sqlite3-3.34.1, urllib3-1.26.5, websockets-8.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Loaded 1839 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
[debug] Downloading _update_spec from https://github.com/yt-dlp/yt-dlp/releases/latest/download/_update_spec
Current version: stable@2024.10.22 from yt-dlp/yt-dlp
Latest version: stable@2024.11.04 from yt-dlp/yt-dlp
ERROR: You installed yt-dlp with pip or using the wheel from PyPi; Use that to update
[youtube] Extracting URL: https://www.youtube.com/watch?v=tbItn2ec67A
[youtube] tbItn2ec67A: Downloading webpage
[youtube] tbItn2ec67A: Downloading ios player API JSON
[youtube] tbItn2ec67A: Downloading mweb player API JSON
ERROR: [youtube] tbItn2ec67A: Sign in to confirm you’re not a bot. This helps protect our community. Learn more
  File "/home/debian/.local/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 741, in extract
    ie_result = self._real_extract(url)
  File "/home/debian/.local/lib/python3.9/site-packages/yt_dlp/extractor/youtube.py", line 4671, in _real_extract
    self.raise_no_formats(reason, expected=True)
  File "/home/debian/.local/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 1275, in raise_no_formats
    raise ExtractorError(msg, expected=expected, video_id=video_id)
```

**Comment by bashonly** [comment]
You have 3 options:

1. use `--cookies-from-browser` and don't browse youtube while you're running yt-dlp (browsing will invalidate the cookies that yt-dlp is using)

2. see [the wiki section on tips on exporting long-lasting youtube cookies](https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies)

3. [login in with oauth instead](https://github.com/yt-dlp/yt-dlp/wiki/Extractors#logging-in-with-oauth)

**Comment by BBugato** [comment]
Okay - I tried now with oath but seems not working - only first time - and at Every download I have to to same again.

debian@....:~$ yt-dlp --username=oauth --password="q2w9hujni6m" https://www.youtube.com/watch?v=qFe0S3F389w
[youtube] oauth: Refreshing access token
WARNING: [youtube] oauth: Failed to refresh access token: Refresh token is invalid, revoked, or expired (invalid_grant)
[youtube] oauth: Initializing authorization flow
[youtube] oauth: To give yt-dlp access to your account, go to  https://www.google.com/device  and enter code  DGZ-XXV-NRJ
[youtube] Extracting URL: https://www.youtube.com/watch?v=qFe0S3F389w
[youtube] qFe0S3F389w: Downloading webpage
[youtube] qFe0S3F389w: Downloading ios player API JSON
[youtube] qFe0S3F389w: Downloading mweb player API JSON
[youtube] qFe0S3F389w: Downloading m3u8 information
[info] qFe0S3F389w: Downloading 1 format(s): 616+251
[download] Microsoft's Former CEO Says Disagreement With Gates on Smartphones Drove Them Apart [qFe0S3F389w].webm has already been downloaded
debian@...:~$ yt-dlp --username=oauth --password="q2w9hujni6m" https://www.youtube.com/watch?v=qFe0S3F389w
[youtube] oauth: Refreshing access token
WARNING: [youtube] oauth: Failed to refresh access token: Refresh token is invalid, revoked, or expired (invalid_grant)
[youtube] oauth: Initializing authorization flow
[youtube] oauth: To give yt-dlp access to your account, go to  https://www.google.com/device  and enter code  HYP-YQK-FDWJ

What I'm doing wrong?

**Comment by bashonly** [comment]
update yt-dlp. it was a bug in version 2024.10.22

**Comment by bashonly** [comment]
closing as this isn't a software issue, it's a usage issue
