### ISSUE TITLE
I can't install it using "pkg install" (Termux).

### ISSUE THREAD

**Issue by VladiStep** [yt-dlp/yt-dlp#11453]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

[The Wiki page](https://github.com/yt-dlp/yt-dlp/wiki/Installation#android) states that it's possible to install "yt-dlp" to Termux using this command:
`pkg install -U "yt-dlp[default]"`.
But it says that there is no such package:
![Screenshot_2024-11-05-02-27-34-427_com termux](https://github.com/user-attachments/assets/12b80497-8d66-4721-83bd-d4d1dbd06697)

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by seproDev** [comment]
No, the wiki says something else:
```
pip install -U "yt-dlp[default]
```

**Comment by VladiStep** [comment]
Oh, sorry then.
But it was a little bit difficult to notice (but probably it's just me):
![Screenshot_2024-11-05-02-41-07-259_com android chrome](https://github.com/user-attachments/assets/f6c16098-2d93-43d1-8b4f-e4e200b907fe)

I think it won't hurt adding some note like "hence `pip`" or IDK
