### ISSUE TITLE
yt-dlp windows 7 fork (nicolaasjan) - how to run?

### ISSUE THREAD

**Issue by honx4amiga** [yt-dlp/yt-dlp#11450]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

i ask this here because i can't find a place on https://github.com/nicolaasjan/yt-dlp to post this issue so maybe someone here might be able to answer...

this question is not regarding official yt-dlp which UNFORTUNATELY doesn't work on good old windows 7 anymore, it's about the yt-dlp fork which is supposed to still run on windows 7. but on my windows 7 the fork does NOT run. :( if i try running the fork, there is a error message popup regarding a missing .dll:

"
yt-dlp.exe - Systemfehler

Das Programm kann nicht gestartet werden, da api-ms-win-core-path-l1-1-0.dll auf dem Computer fehlt. Installieren Sie das Programm erneut, um das Problem zu beheben. 
"

and yt-dlp fork itsself says in cmd window:
"
[PYI-6508:ERROR] Failed to load Python DLL 'C:\Users\GAMEWO~1\AppData\Local\Temp
\_MEI54442\python310.dll'.
LoadLibrary: Das angegebene Modul wurde nicht gefunden.
"

i tried both yt-dlp.exe and yt-dlp_x86 from nicolaasjan fork.

i had to check the checkbox regarding updated in order to be able to to submit this question which of course is not true, of course NO update took place since latest official yt-dlp doesn't work anymore on windows 7, thus no "update" is offered, if trying to update official yt-dlp.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
You're using https://github.com/nicolaasjan/yt-dlp/releases/download/2024.11.04.073739/yt-dlp_win7.exe ? And NOT https://github.com/nicolaasjan/yt-dlp/releases/download/2024.11.04.073739/yt-dlp.exe ?

Sorry, but when the changelog said yt-dlp no longer supports Windows 7, it really does mean that no support will be provided on this tracker for Windows 7.
