### ISSUE TITLE
automatic files sort ? ()

### ISSUE THREAD

**Issue by pawfmrpimt** [yt-dlp/yt-dlp#11457]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

automatically create folders according to website eg. [your directories]/[website's name] / [tags and or artist]/[videos and or images] when using -P to tell where the downloaded files should be. I was looking for similar experience to gallery-dl but some websites are not supported on gallery-dl but are on yt-dlp.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
> [your directories]/[website's name] / [tags and or artist]/[videos and or images]

You can't use output templates with `-P`; this option just specifies the base directory for downloads

But you can use them with `-o`, e.g.:

```
-P ~/Downloads
-o "%(extractor)s/%(artist,uploader,channel)s/%(title)s [%(id)s].%(ext)s"
```

**Comment by dupespra** [comment]
I think this output path is closer to how gallery-dl does it:

```
-o "yt-dlp/%(extractor)s/%(uploader_id)s/%(title)s [%(id)s].%(ext)s"
```

Using `uploader_id` works better with non-youtube sites.
