### ISSUE TITLE
[NBC]/[adobepass] ERROR: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by jsmith1299** [yt-dlp/yt-dlp#11469]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United States

### Provide a description that is worded well enough to be understood

Unable to pull Law and Order SVU or any NBC shows. Getting ERROR: 'NoneType' object is not iterable. I also tried cookies-from-browser but the application still returns to use ap-mso credentials.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['https://www.nbc.com/law-and-order-special-victims-unit/video/economics-of-shame/9000392650', '--ap-mso', 'Verizon', '--ap-username', 'PRIVATE', '--ap-password', 'PRIVATE', '-vU']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.11.04 from yt-dlp/yt-dlp [197d0b03b] (win_exe)
[debug] Python 3.10.11 (CPython AMD64 64bit) - Windows-10-10.0.22631-SP0 (OpenSSL 1.1.1t  7 Feb 2023)
[debug] exe versions: ffmpeg N-93302-g147ef1d947, ffprobe N-93302-g147ef1d947
[debug] Optional libraries: Cryptodome-3.21.0, brotli-1.1.0, certifi-2024.08.30, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.40.1, urllib3-2.2.3, websockets-13.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1838 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.11.04 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.11.04 from yt-dlp/yt-dlp)
[NBC] Extracting URL: https://www.nbc.com/law-and-order-special-victims-unit/video/economics-of-shame/9000392650
[NBC] 9000392650: Downloading JSON metadata
[NBC] 9000392650: Downloading JSON metadata
ERROR: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1625, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1760, in __extract_info
  File "yt_dlp\extractor\common.py", line 742, in extract
  File "yt_dlp\extractor\nbc.py", line 212, in _real_extract
  File "yt_dlp\extractor\adobepass.py", line 1449, in _extract_mvpd_auth
  File "yt_dlp\extractor\adobepass.py", line 1365, in _download_webpage_handle
TypeError: 'NoneType' object is not iterable
```

**Comment by bashonly** [comment]
Regression introduced in dcfeea4dd5e5686821350baa6c7767a011944867

This should be the fix:
```diff
diff --git a/yt_dlp/extractor/adobepass.py b/yt_dlp/extractor/adobepass.py
index 7cc15ec7b..f1b877927 100644
--- a/yt_dlp/extractor/adobepass.py
+++ b/yt_dlp/extractor/adobepass.py
@@ -1362,7 +1362,7 @@ class AdobePassIE(InfoExtractor):  # XXX: Conventionally, base classes should en
 
     def _download_webpage_handle(self, *args, **kwargs):
         headers = self.geo_verification_headers()
-        headers.update(kwargs.get('headers', {}))
+        headers.update(kwargs.get('headers') or {})
         kwargs['headers'] = headers
         return super()._download_webpage_handle(
             *args, **kwargs)
```

**Comment by bashonly** [comment]
@jsmith1299 `yt-dlp --update-to master`

**Comment by jsmith1299** [comment]
@bashonly thank you so much. It works!
