### ISSUE TITLE
Can't find __main__ module in C:\Program Files (x86)\ClipGrab\python\python.exe (python 3.8.9)

### ISSUE THREAD

**Issue by mywebext** [yt-dlp/yt-dlp#11467]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

No videos display that can be downloaded. This is a fresh download from https://clipgrab.org/download-clipgrab/ on windows 11 with program run with elevated administrative privileges. 

In the check list it states to download the latest python so im guessing the installation package is cached from the download site as AVG seems to be part of the package. I am here as a consumer and not a developer.

Video URL: https://www.youtube.com/watch?v=bDcnc7f7ki0
Program Response:
![image](https://github.com/user-attachments/assets/81e526b4-69fb-4c5f-92ec-2f4e6d0eaa35)

I tried to work around the issue to automatically download via links from clipboard and save to Video namespace of C drive and I get no errors but a download status bar indicates activity, but nothings ever downloaded. The following screen offers a hint as to what might be going on. 
![image](https://github.com/user-attachments/assets/7afb01fa-e9d2-4fac-add1-2c1c5e665ac8)

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
I am not sure how to do this
```

**Comment by bashonly** [comment]
We do not provide support for 3rd party GUIs on this tracker, sorry. If ClipGrab is bundling or installing Python itself, then it's likely that ClipGrab needs to upgrade its Python from 3.8 to 3.9
