### ISSUE TITLE
How to overwrite an existing downloaded video?

### ISSUE THREAD

**Issue by tormyvancool** [yt-dlp/yt-dlp#11468]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

how can I overwrite an existing videofile?

Here the command line I use
`yt-dlp  -S vcodec:h264,res,acodec:aac <URL> -P "J:\" -o TEST.mp4`
With this line,  yt-dlp returns `[download] J:\TEST.mp4 has already been downloaded`

Indeed `TEST.mp4` exists but I want to overwrite it.

In the past there was the switch to avoid overwriting. I believe it doesn't overwrite anyonger by default (?) so how can I force overwriting?

Thanks in advance

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by grqx** [comment]
pass `--force-overwrite`
