### ISSUE TITLE
[Youtube] HTTP Error 400 Bad Request using Oauth, but cookies work

### ISSUE THREAD

**Issue by Dulaithol** [yt-dlp/yt-dlp#11462]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

USA

### Provide a description that is worded well enough to be understood

When using oauth for authentication Youtube is returning a 400 bad request. Using the same command as either anonymous or with browser cookies (for the same account) works without any error. I am subscribed to YouTube Music (family plan) and YouTube Premium. I would like to use my account for the higher quality steams.

I've tried multiple different videos from both Youtube and Youtube music. I don't have any other issues using web browsers and/or mobile devices. 

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--username=PRIVATE', '--password=', '--list-formats', 'https://music.youtube.com/watch?v=dQw4w9WgXcQ']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.11.04 from yt-dlp/yt-dlp [197d0b03b] (pip)
[debug] Python 3.11.2 (CPython x86_64 64bit) - Linux-6.1.0-25-amd64-x86_64-with-glibc2.36 (OpenSSL 3.0.14 4 Jun 2024, glibc 2.36)
[debug] exe versions: ffmpeg 5.1.6-0 (setts), ffprobe 5.1.6-0
[debug] Optional libraries: secretstorage-3.3.3, sqlite3-3.40.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Loaded 1838 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.11.04 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.11.04 from yt-dlp/yt-dlp)
[debug] Loading youtube.oauth_refresh_token_default from cache
[youtube] oauth: Refreshing access token
[debug] [youtube] oauth: Logged in using profile "default"
[youtube] Extracting URL: https://music.youtube.com/watch?v=dQw4w9WgXcQ
[youtube] dQw4w9WgXcQ: Downloading webpage
[youtube] dQw4w9WgXcQ: Downloading ios player API JSON
[youtube] dQw4w9WgXcQ: Downloading mweb player API JSON
[youtube] dQw4w9WgXcQ: Downloading ios music player API JSON
WARNING: [youtube] YouTube said: ERROR - Request contains an invalid argument.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (1/3)...
[youtube] dQw4w9WgXcQ: Downloading ios music player API JSON
HTTP Error 400: Bad Request
WARNING: [youtube] YouTube said: ERROR - Request contains an invalid argument.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (2/3)...
[youtube] dQw4w9WgXcQ: Downloading ios music player API JSON
WARNING: [youtube] YouTube said: ERROR - Request contains an invalid argument.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (3/3)...
[youtube] dQw4w9WgXcQ: Downloading ios music player API JSON
WARNING: [youtube] YouTube said: ERROR - Request contains an invalid argument.
WARNING: [youtube] Unable to download API page: HTTP Error 400: Bad Request (caused by <HTTPError 400: Bad Request>)
[debug] [youtube] Extracting signature function js_4e23410d_111
[debug] Loading youtube-sigfuncs.js_4e23410d_111 from cache
[debug] Loading youtube-nsig.4e23410d from cache
[debug] [youtube] Decrypted nsig FWB71e2YaILzV4Jk6 => c9DtuMX86FuFLg
[debug] Loading youtube-nsig.4e23410d from cache
[debug] [youtube] Decrypted nsig ntd9OrqYeHwbeFAZW => I7n4wL1bNcbp_A
[debug] [youtube] Extracting signature function js_4e23410d_107
[debug] Loading youtube-sigfuncs.js_4e23410d_107 from cache
[youtube] dQw4w9WgXcQ: Downloading m3u8 information
WARNING: [youtube] Incomplete data received in embedded initial data; re-fetching using API.
[youtube] dQw4w9WgXcQ: Downloading initial data API JSON
WARNING: [youtube] YouTube said: ERROR - Request contains an invalid argument.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (1/3)...
[youtube] dQw4w9WgXcQ: Downloading initial data API JSON
WARNING: [youtube] YouTube said: ERROR - Request contains an invalid argument.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (2/3)...
[youtube] dQw4w9WgXcQ: Downloading initial data API JSON
WARNING: [youtube] YouTube said: ERROR - Request contains an invalid argument.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (3/3)...
[youtube] dQw4w9WgXcQ: Downloading initial data API JSON
WARNING: [youtube] YouTube said: ERROR - Request contains an invalid argument.
ERROR: [youtube] dQw4w9WgXcQ: Unable to download API page: HTTP Error 400: Bad Request (caused by <HTTPError 400: Bad Request>)
  File "/home/jake/yt-dlp/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 742, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jake/yt-dlp/lib/python3.11/site-packages/yt_dlp/extractor/youtube.py", line 4902, in _real_extract
    initial_data = self._extract_response(
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jake/yt-dlp/lib/python3.11/site-packages/yt_dlp/extractor/youtube.py", line 1270, in _extract_response
    next(main_retries)
  File "/home/jake/yt-dlp/lib/python3.11/site-packages/yt_dlp/utils/_utils.py", line 5271, in __iter__
    self.error_callback(self.error, self.attempt, self.retries)
  File "/home/jake/yt-dlp/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 3896, in _error_or_warning
    RetryManager.report_retry(
  File "/home/jake/yt-dlp/lib/python3.11/site-packages/yt_dlp/utils/_utils.py", line 5279, in report_retry
    raise e
  File "/home/jake/yt-dlp/lib/python3.11/site-packages/yt_dlp/extractor/youtube.py", line 1243, in _extract_response
    response = self._call_api(
               ^^^^^^^^^^^^^^^
  File "/home/jake/yt-dlp/lib/python3.11/site-packages/yt_dlp/extractor/youtube.py", line 861, in _call_api
    return self._download_json(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/jake/yt-dlp/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 1153, in download_content
    res = getattr(self, download_handle.__name__)(url_or_request, video_id, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jake/yt-dlp/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 1113, in download_handle
    res = self._download_webpage_handle(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jake/yt-dlp/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 963, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jake/yt-dlp/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 912, in _request_webpage
    raise ExtractorError(errmsg, cause=err)

  File "/home/jake/yt-dlp/lib/python3.11/site-packages/yt_dlp/networking/_urllib.py", line 398, in _send
    res = opener.open(urllib_req, timeout=self._calculate_timeout(request))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 525, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 634, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 563, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: Bad Request

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jake/yt-dlp/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 898, in _request_webpage
    return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query, extensions))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jake/yt-dlp/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 4162, in urlopen
    return self._request_director.send(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jake/yt-dlp/lib/python3.11/site-packages/yt_dlp/networking/common.py", line 117, in send
    response = handler.send(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/jake/yt-dlp/lib/python3.11/site-packages/yt_dlp/networking/_helper.py", line 208, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jake/yt-dlp/lib/python3.11/site-packages/yt_dlp/networking/common.py", line 340, in send
    return self._send(request)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/jake/yt-dlp/lib/python3.11/site-packages/yt_dlp/networking/_urllib.py", line 403, in _send
    raise HTTPError(UrllibResponseAdapter(e.fp), redirect_loop='redirect error' in str(e)) from e
yt_dlp.networking.exceptions.HTTPError: HTTP Error 400: Bad Request
```

**Comment by bashonly** [comment]
There are some clients that OAuth is not compatible with, and apparently `ios_music` is one of them.

Try passing `--extractor-args "youtube:player_client=web_music"`, and if that fails, then try `--extractor-args "youtube:player_client=android_music"`. Note: ONLY pass these arguments when downloading **music** URLs

**Comment by coletdjnz** [comment]
This looks like a possible A/B test/rollout of OAuth being disabled for /next endpoint on WEB - for both embedded next response and the API request (initial data)

**Comment by Prototaxis** [comment]
`/next`, `/browse`, and a couple other endpoints are affected.

**Comment by Dulaithol** [comment]
Unfortunately trying just a music URL with both android_music and web_music still resulted in the same 400 error. I have a feeling A/B test theory is the most likely.

**Comment by Dulaithol** [comment]
As a work around for now I'm able to use a brand account. Seems the 400 possible A/B test is per account.

**Comment by MarvinSchenkel** [comment]
I tried the brand account trick, but for me it unfortunately does not work. Even a 1min old brand account is running into 400's

**Comment by 111100001** [comment]
> I tried the brand account trick, but for me it unfortunately does not work. Even a 1min old brand account is running into 400's

yes that is true, same thing for me.

**Comment by Javierchik** [comment]
On Friday I was able to use oauth via .netrc file and it worked flawlessly, today I switched the google account I was using, then the prompt asked for device registration, it was success and then it fails showing the error above... I switched back to the google account I used initially and it still works... so is it a thing of registering new accounts ???

**Comment by bashonly** [comment]
It's an A/B test. The breaking change has been rolled out for some accounts, but not others yet. Eventually it will be broken for all.

**Comment by Javierchik** [comment]
> It's an A/B test. The breaking change has been rolled out for some accounts, but not others yet. Eventually it will be broken for all.

Thanks for reply, can you let us know  if it's a YT A/B test or yt-dlp thing or something else A/B testing?

**Comment by lucacordioli** [comment]
I have 5 google accounts at my disposal and all of them give me the problem

**Comment by bashonly** [comment]
> can you let us know if it's a YT A/B test or yt-dlp thing or something else A/B testing?

It's a YT A/B test. Out of our control.

> I have 5 google accounts at my disposal and all of them give me the problem

Then the change has been rolled out for all of them.

The eventual outcome is that OAuth support will be removed from yt-dlp. This issue will be kept open until then.

**Comment by Javierchik** [comment]
@bashonly I really appreciate your input here: Correct me if I'm wrong, OAuth support was added because of YT asking for `Sign in to confirm you are not a bot......` then is there any other way to sign in without expose credentials? I would like to move forward with the initial issue that brought me to use OAuth :)

**Comment by bashonly** [comment]
Pass cookies instead

**Comment by Javierchik** [comment]
> Pass cookies instead

Just one more: If YT/Google account password is changed, then cookie gets expired?

**Comment by MarvinSchenkel** [comment]
@bashonly We use `yt-dlp` with OAuth here at Music Assistant to provide a nice log-in experience to our users via OAuth. Are you basically saying Google will disallow the usage of OAuth for YT Music altogether? Is there any chance this A/B test will be rolled back? 

If we have to revert back to using cookies, then it is what it is.

**Comment by bashonly** [comment]
> Are you basically saying Google will disallow the usage of OAuth for YT Music altogether?

OAuth was only ever intended by YT to work with TV clients (e.g. `--extractor-arg "youtube:player_client=tv"` in yt-dlp terms). It was a happy accident that it even worked at all with other clients (e.g. `web`, `mweb`, `ios`). The change being rolled out to accounts now restricts OAuth to only work with TV clients as originally intended.

Without getting into too much technical detail / to make a long story short: OAuth will still exist, and while it may still be useful for some other applications, it will be effectively useless as far as yt-dlp is concerned. OAuth support is expected to be removed from yt-dlp once the A/B testing period is over and the change has been fully rolled out to all accounts.

> Is there any chance this A/B test will be rolled back?

Anything is possible. But, realistically: no.

**Comment by bashonly** [comment]
> But the #1 comment on https://github.com/yt-dlp/yt-dlp/issues/10128 screams "DO NOT PASS YOUR COOKIES"

Using OAuth with YT carries all the same risk that using cookies does. If you care about the account not being blocked/banned, the same sentiment applies to OAuth. Nevertheless, the comment has been hidden as it is outdated and may be misleading.

> It would be nice to get  consistent advice here - e.g., in a section about the "Sign in to confirm you’re not a bot" problem in the FAQ. 

The regularly updated [pinned issues thread](https://github.com/yt-dlp/yt-dlp/issues/3766) details all of the ongoing youtube issues and their known workarounds (if any).

**Comment by bashonly** [comment]
See also:
- #11640
