### ISSUE TITLE
How do you add a newline to --print-to-file  output.txt

### ISSUE THREAD

**Issue by kartik1986x** [yt-dlp/yt-dlp#11461]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

yt-dlp --skip-download --print "%(title)s %(description)s %(original_url)s" https://www.youtube.com/watch?v=B4udoZqkY5Y output.txt

I want to get all printed in separate lines.
How can i get title,description,original_url all printed  in separate lines ?
command for newline like \n or \r\n.
(for --print and --print-to-file) for windows.
please anybody can give some example for this.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by seproDev** [comment]
You enter the newline literally. So not `\n` but just a linebreak.

**Comment by kartik1986x** [comment]
Thanks bashonly it is working.
