### ISSUE TITLE
mcloud.vvid30c.site

### ISSUE THREAD

**Issue by SubZero5** [yt-dlp/yt-dlp#11474]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Example URLs

`https://mcloud.vvid30c.site/watch/?v11#VDRIY3NuUHE4bzRzb3pLVTdqa2plSlZGNTdpVlp3dXRnWW00SklEWFZuc3FwZnh3QTVyZWZmeE92bzlHVGNmaUU0SFU`

### Provide a description that is worded well enough to be understood

Please support mcloud.vvid30c.site

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
C:\Users\AsusTV\Downloads>yt-dlp.exe "https://mcloud.vvid30c.site/watch/?v11#VDRIY3NuUHE4bzRzb3pLVTdqa2plSlZGNTdpVlp3dXRnWW00SklEWFZuc3FwZnh3QTVyZWZmeE92bzlHVGNmaUU0SFU" -vU
[debug] Command-line config: ['https://mcloud.vvid30c.site/watch/?v11#VDRIY3NuUHE4bzRzb3pLVTdqa2plSlZGNTdpVlp3dXRnWW00SklEWFZuc3FwZnh3QTVyZWZmeE92bzlHVGNmaUU0SFU', '-vU']
[debug] Encodings: locale cp1254, fs utf-8, pref cp1254, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version master@2024.11.06.215904 from yt-dlp/yt-dlp-master-builds [be3579aaf] (win_exe)
[debug] Python 3.10.11 (CPython AMD64 64bit) - Windows-10-10.0.22631-SP0 (OpenSSL 1.1.1t  7 Feb 2023)
[debug] exe versions: ffmpeg N-117685-g1864025458-20241101 (setts), ffprobe N-117685-g1864025458-20241101
[debug] Optional libraries: Cryptodome-3.21.0, brotli-1.1.0, certifi-2024.08.30, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.40.1, urllib3-2.2.3, websockets-13.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1839 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-master-builds/releases/latest
Latest version: master@2024.11.06.215904 from yt-dlp/yt-dlp-master-builds
yt-dlp is up to date (master@2024.11.06.215904 from yt-dlp/yt-dlp-master-builds)
[generic] Extracting URL: https://mcloud.vvid30c.site/watch/?v11#VDRIY3NuUHE4bzRzb3pLVTdqa2plSlZGNTdpVlp3dXRnWW00SklEWFZuc3FwZnh3QTVyZWZmeE92bzlHVGNmaUU0SFU
[generic] ?v11#VDRIY3NuUHE4bzRzb3pLVTdqa2plSlZGNTdpVlp3dXRnWW00SklEWFZuc3FwZnh3QTVyZWZmeE92bzlHVGNmaUU0SFU: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] ?v11#VDRIY3NuUHE4bzRzb3pLVTdqa2plSlZGNTdpVlp3dXRnWW00SklEWFZuc3FwZnh3QTVyZWZmeE92bzlHVGNmaUU0SFU: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://mcloud.vvid30c.site/watch/?v11#VDRIY3NuUHE4bzRzb3pLVTdqa2plSlZGNTdpVlp3dXRnWW00SklEWFZuc3FwZnh3QTVyZWZmeE92bzlHVGNmaUU0SFU
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1625, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1760, in __extract_info
  File "yt_dlp\extractor\common.py", line 742, in extract
  File "yt_dlp\extractor\generic.py", line 2553, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://mcloud.vvid30c.site/watch/?v11#VDRIY3NuUHE4bzRzb3pLVTdqa2plSlZGNTdpVlp3dXRnWW00SklEWFZuc3FwZnh3QTVyZWZmeE92bzlHVGNmaUU0SFU
```

**Comment by seproDev** [comment]
Sites primarily used for piracy won't be supported

https://github.com/yt-dlp/yt-dlp/wiki/FAQ#why-is-there-a-rule-against-websites-primarily-used-for-piracy
