### ISSUE TITLE
[vk:uservideos] Endless loop during playlist extraction

### ISSUE THREAD

**Issue by WlaBo75** [yt-dlp/yt-dlp#11471]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Worldide

### Provide a description that is worded well enough to be understood

Some channels is not possible to download, but some works fine. It is just ednless download of JSON metadata.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp -vU --ignore-config https://vk.com/video/@gorkyfilmstudio/all
[debug] Command-line config: ['-vU', '--ignore-config', 'https://vk.com/video/@gorkyfilmstudio/all']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.11.04.232933 from yt-dlp/yt-dlp-nightly-builds [282e19db8] (pip)
[debug] Python 3.11.2 (CPython x86_64 64bit) - Linux-6.1.0-26-amd64-x86_64-with-glibc2.36 (OpenSSL 3.0.14 4 Jun 2024, glibc 2.36)
[debug] exe versions: ffmpeg 6.1.2 (fdk,setts), ffprobe 6.1.2, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.21.0, brotlicffi-1.1.0.0, certifi-2024.08.30, curl_cffi-0.7.1, mutagen-1.47.0, requests-2.32.3, secretstorage-3.3.3, sqlite3-3.40.1, urllib3-2.2.3, websockets-13.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1838 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.11.04.232933 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.11.04.232933 from yt-dlp/yt-dlp-nightly-builds)
[vk:uservideos] Extracting URL: https://vk.com/video/@gorkyfilmstudio/all
[vk:uservideos] @gorkyfilmstudio: Downloading webpage
[download] Downloading playlist: -121487680_all
[vk:uservideos] -121487680: Downloading JSON metadata
[vk:uservideos] -121487680: Downloading JSON metadata
[vk:uservideos] -121487680: Downloading JSON metadata
[vk:uservideos] -121487680: Downloading JSON metadata
[vk:uservideos] -121487680: Downloading JSON metadata
[vk:uservideos] -121487680: Downloading JSON metadata
[vk:uservideos] -121487680: Downloading JSON metadata
[vk:uservideos] -121487680: Downloading JSON metadata
[vk:uservideos] -121487680: Downloading JSON metadata
[vk:uservideos] -121487680: Downloading JSON metadata
[vk:uservideos] -121487680: Downloading JSON metadata
[vk:uservideos] -121487680: Downloading JSON metadata
[vk:uservideos] -121487680: Downloading JSON metadata
[vk:uservideos] -121487680: Downloading JSON metadata
[vk:uservideos] -121487680: Downloading JSON metadata
[vk:uservideos] -121487680: Downloading JSON metadata
[vk:uservideos] -121487680: Downloading JSON metadata
[vk:uservideos] -121487680: Downloading JSON metadata
[vk:uservideos] -121487680: Downloading JSON metadata
[vk:uservideos] -121487680: Downloading JSON metadata
^C
ERROR: Interrupted by user
```

**Comment by seproDev** [comment]
Is it actually an infinite loop, or is the channel just really large? You might want to use `--lazy-playlist`

**Comment by WlaBo75** [comment]
> Is it actually an infinite loop, or is the channel just really large? You might want to use `--lazy-playlist`

I'm preferring to use  --playlist-reverse but with --lazy-playlist it works. As a workaround is fine for me.

**Comment by WlaBo75** [comment]
Update: also with the --lazy-playlist it's still running endless in loop after reaching the end of the playlist, so the workaroung did'nt resolved the issue.

**Comment by bashonly** [comment]
The user account in the OP's log apparently has 2 videos that aren't available, but are still included in the total video count, breaking our pagination logic.

```diff
diff --git a/yt_dlp/extractor/vk.py b/yt_dlp/extractor/vk.py
index 6ccc701a2..7ef30898a 100644
--- a/yt_dlp/extractor/vk.py
+++ b/yt_dlp/extractor/vk.py
@@ -561,7 +561,11 @@ def _entries(self, page_id, section):
                 'oid': page_id,
                 'section': section,
             })[0][section]
-            count += video_list_json['count']
+            new_count = video_list_json['count']
+            if not new_count:
+                self.to_screen(f'{page_id}: Skipping {total - count} unavailable videos')
+                break
+            count += new_count
             video_list = video_list_json['list']
 
     def _real_extract(self, url):
```

**Comment by WlaBo75** [comment]
> The user account in the OP's log apparently has 2 videos that aren't available, but are still included in the total video count, breaking our pagination logic.
> 
> ```diff
> diff --git a/yt_dlp/extractor/vk.py b/yt_dlp/extractor/vk.py
> index 6ccc701a2..7ef30898a 100644
> --- a/yt_dlp/extractor/vk.py
> +++ b/yt_dlp/extractor/vk.py
> @@ -561,7 +561,11 @@ def _entries(self, page_id, section):
>                  'oid': page_id,
>                  'section': section,
>              })[0][section]
> -            count += video_list_json['count']
> +            new_count = video_list_json['count']
> +            if not new_count:
> +                self.to_screen(f'{page_id}: Skipping {total - count} unavailable videos')
> +                break
> +            count += new_count
>              video_list = video_list_json['list']
>  
>      def _real_extract(self, url):
> ```

Many thanks for the patch. Hopefully it will be included in the next releases of yt-dlp.

**Comment by WlaBo75** [comment]
Update: I've tested with multiple channels that had this issue and with this pach it's resolved. I will close the issue.

**Comment by WlaBo75** [comment]
After update it's still not working. There was lots of changes in this section in file vk.py so I can't apply this patch anymore.
yt-dlp is up to date (nightly@2024.11.10.232816 from yt-dlp/yt-dlp-nightly-builds)

**Comment by WlaBo75** [comment]
Update: uninstalled/installed again current nightly@2024.11.10.232816 build and was able to apply patch. Works fine.

**Comment by krasnh** [comment]
Since some time, the url of the link in the browser has been changing from vk.com/video on vkvideo. And `https://vk.com/video/@gorkyfilmstudio/all` - it works, but `https://vkvideo.ru/@gorkyfilmstudio/all` - it doesn't work.

**Comment by WlaBo75** [comment]
> Since some time, the url of the link in the browser has been changing from vk.com/video on vkvideo. And `https://vk.com/video/@gorkyfilmstudio/all` - works with yt-dlp, but `https://vkvideo.ru/@gorkyfilmstudio/all` - it doesn't work.
> 
> I hope I'm not the only one who noticed this?

The link https://vk.com/video/@gorkyfilmstudio/all works fine with patch and don't work without patch. It's running in loop endless trying to get the playlist.
The link https://vkvideo.ru/@gorkyfilmstudio/all redirects in my browser just to https://vk.com/video.

**Comment by krasnh** [comment]
>The link `https://vkvideo.ru/@gorkyfilmstudio/al`l redirects in my browser just to `https://vk.com/video`.

Yes, it's like that again now. I don't know what it was.

**Comment by krasnh** [comment]
>The link `https://vkvideo.ru/@gorkyfilmstudio/all` redirects in my browser just to `https://vk.com/video`.

@WlaBo75,  and today? It looks like some work is being done there, that the address is changing back and forth.

**Comment by WlaBo75** [comment]
> > The link `https://vkvideo.ru/@gorkyfilmstudio/all` redirects in my browser just to `https://vk.com/video`.
> 
> @WlaBo75, and today? It looks like some work is being done there, that the address is changing back and forth.

Today it opens without redirection but can't load properly. Seems to be temporarly overloaded right now. vk.com doesn't work currenty too. Got message Too many Requests

**Comment by krasnh** [comment]
> vkvideo.ru

Well, the situation did not go unnoticed,  "[VK] add domain vkvideo.ru" (#11646).
