### ISSUE TITLE
[Request]Steam community workshop [video] [wallpaper engine etc.]

### ISSUE THREAD

**Issue by pawfmrpimt** [yt-dlp/yt-dlp#11475]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

japan

### Example URLs

https://steamcommunity.com/sharedfiles/filedetails/?id=[number]
https://steamcommunity.com/profiles/[steam id]/myworkshopfiles/

### Provide a description that is worded well enough to be understood

Request websites to be able to download from links https://steamcommunity.com/sharedfiles/filedetails/?id=[number] and from profile's workshop items https://steamcommunity.com/profiles/[steam id]/myworkshopfiles/

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
none
```

**Comment by grqx** [comment]
> [https://steamcommunity.com/sharedfiles/filedetails/?id=[number]](https://steamcommunity.com/sharedfiles/filedetails/?id=%5Bnumber%5D)

https://github.com/yt-dlp/yt-dlp/blob/be3579aaf0c3b71a0a3195e1955415d5e4d6b3d8/yt_dlp/extractor/steam.py#L20

this one should be supported


> ### Complete Verbose Output
> ```shell
> none
> ```

also, please show your verbose output

**Comment by bashonly** [comment]
closing since there's not even actual urls given
