### ISSUE TITLE
Download multiple subtitles of same language

### ISSUE THREAD

**Issue by serena13** [yt-dlp/yt-dlp#1148]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Verbose log

```
C:\Downloads>yt-dlp -v "https://vod-akc-na-central-1.media.dsso
tt.com/ps01/disney/33efc89b-fc39-47b8-8151-105a00f9969e/r/composite_es-419_FORCED_3a39e823-5f42-4685
-b6b8-8cdbdddb5568_a3334ef7-8927-4091-9493-ad533469fed6.m3u8" --skip-download --sub-langs all --writ
e-subs
[debug] Command-line config: ['-v', 'https://vod-akc-na-central-1.media.dssott.com/ps01/disney/33efc
89b-fc39-47b8-8151-105a00f9969e/r/composite_es-419_FORCED_3a39e823-5f42-4685-b6b8-8cdbdddb5568_a3334
ef7-8927-4091-9493-ad533469fed6.m3u8', '--skip-download', '--sub-langs', 'all', '--write-subs']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] yt-dlp version 2021.09.25 (exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-2012ServerR2-6.3.9600-SP0
[debug] exe versions: none
[debug] Optional libraries: Crypto, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [generic] Extracting URL: https://vod-akc-na-central-1.media.dssott.com/ps01/disney/33efc89b
-fc39-47b8-8151-105a00f9969e/r/composite_es-419_FORCED_3a39e823-5f42-4685-b6b8-8cdbdddb5568_a3334ef7
-8927-4091-9493-ad533469fed6.m3u8
[generic] composite_es-419_FORCED_3a39e823-5f42-4685-b6b8-8cdbdddb5568_a3334ef7-8927-4091-9493-ad533
469fed6: Requesting header
[generic] composite_es-419_FORCED_3a39e823-5f42-4685-b6b8-8cdbdddb5568_a3334ef7-8927-4091-9493-ad533
469fed6: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, vcodec:vp9.2(10), acodec, files
ize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: best/bestvideo+bestaudio
[info] composite_es-419_FORCED_3a39e823-5f42-4685-b6b8-8cdbdddb5568_a3334ef7-8927-4091-9493-ad533469
fed6: Downloading 1 format(s): 0


C:\Downloads\>yt-dlp -v "https://vod-akc-na-central-1.media.dsso
tt.com/ps01/disney/33efc89b-fc39-47b8-8151-105a00f9969e/r/composite_es-419_NORMAL_c79657c0-bec6-444f
-9dfc-dc51d5c5c46a_6abedef0-7a4f-42cd-b9ad-9ac71fe7888f.m3u8" --skip-download --sub-format best --wr
ite-subs
[debug] Command-line config: ['-v', 'https://vod-akc-na-central-1.media.dssott.com/ps01/disney/33efc
89b-fc39-47b8-8151-105a00f9969e/r/composite_es-419_NORMAL_c79657c0-bec6-444f-9dfc-dc51d5c5c46a_6abed
ef0-7a4f-42cd-b9ad-9ac71fe7888f.m3u8', '--skip-download', '--sub-format', 'best', '--write-subs']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] yt-dlp version 2021.09.25 (exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-2012ServerR2-6.3.9600-SP0
[debug] exe versions: none
[debug] Optional libraries: Crypto, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [generic] Extracting URL: https://vod-akc-na-central-1.media.dssott.com/ps01/disney/33efc89b
-fc39-47b8-8151-105a00f9969e/r/composite_es-419_NORMAL_c79657c0-bec6-444f-9dfc-dc51d5c5c46a_6abedef0
-7a4f-42cd-b9ad-9ac71fe7888f.m3u8
[generic] composite_es-419_NORMAL_c79657c0-bec6-444f-9dfc-dc51d5c5c46a_6abedef0-7a4f-42cd-b9ad-9ac71
fe7888f: Requesting header
[generic] composite_es-419_NORMAL_c79657c0-bec6-444f-9dfc-dc51d5c5c46a_6abedef0-7a4f-42cd-b9ad-9ac71
fe7888f: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, vcodec:vp9.2(10), acodec, files
ize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: best/bestvideo+bestaudio
[info] composite_es-419_NORMAL_c79657c0-bec6-444f-9dfc-dc51d5c5c46a_6abedef0-7a4f-42cd-b9ad-9ac71fe7
888f: Downloading 1 format(s): 0
```

## Description

I am trying to download two subtitles, and I have not been able to download them successfully, I do not know if it is possible to download them with Yt-Dlp

My commands are as follows:

First Subtitle (Spanish "NORMAL Complete")

yt-dlp "https://vod-akc-na-central-1.media.dssott.com/ps01/disney/33efc89b-fc39-47b8-8151-105a00f9969e/r/composite_es-419_NORMAL_c79657c0-bec6-444f-9dfc-dc51d5c5c46a_6abedef0-7a4f-42cd-b9ad-9ac71fe7888f.m3u8" --skip-download --sub-langs all --write-subs

yt-dlp "https://vod-akc-na-central-1.media.dssott.com/ps01/disney/33efc89b-fc39-47b8-8151-105a00f9969e/r/composite_es-419_NORMAL_c79657c0-bec6-444f-9dfc-dc51d5c5c46a_6abedef0-7a4f-42cd-b9ad-9ac71fe7888f.m3u8" --skip-download --sub-format best --write-subs

Second Subtitle (Spanish "FORCED")

yt-dlp "https://vod-akc-na-central-1.media.dssott.com/ps01/disney/33efc89b-fc39-47b8-8151-105a00f9969e/r/composite_es-419_FORCED_3a39e823-5f42-4685-b6b8-8cdbdddb5568_a3334ef7-8927-4091-9493-ad533469fed6.m3u8" --skip-download --sub-langs all --write-subs

yt-dlp "https://vod-akc-na-central-1.media.dssott.com/ps01/disney/33efc89b-fc39-47b8-8151-105a00f9969e/r/composite_es-419_FORCED_3a39e823-5f42-4685-b6b8-8cdbdddb5568_a3334ef7-8927-4091-9493-ad533469fed6.m3u8" --skip-download --sub-format best --write-subs

**Comment by fstirlitz** [comment]
Those are direct links to subtitle segment lists, which yt-dlp does not recognise correctly. Basically this is the issue I anticipated in <https://github.com/yt-dlp/yt-dlp/pull/247#issuecomment-826028909>.

If you point yt-dlp to the m3u8 manifest describing all the video and audio formats, yt-dlp should be able to recognise the subtitles present within.

**Comment by pukkandan** [comment]
Use the master m3u8

**Comment by serena13** [comment]
Yes, it is what I tried, use the "master", but only download one of the two subtitles since they have the same language code (es-419), One is full subtitle (NAME="Español (Latinoamericano)") and the other is forced subtitle (NAME="es-419--forced--")

This is the "master"

https://vod-akc-na-central-1.media.dssott.com/ps01/disney/33efc89b-fc39-47b8-8151-105a00f9969e/ctr-all-8eeb158b-ac95-4193-b71f-57176b37c3fe-a4ce99af-b2e0-474f-b07e-fc30331a0c8a.m3u8?r=720&v=1&sxl=ja&hash=6320c97932dec099707adb9a32ce98d6b3d7db35

**Comment by pukkandan** [comment]
> but only download one of the two subtitles since they have the same language code (es-419), One is full subtitle (NAME="Español (Latinoamericano)") and the other is forced subtitle (NAME="es-419--forced--"

This is a known issue. I don't remember whether there is an issue open for this though

I am working on improving subtitle selection code (which will to fix this). But it wont be complete for a while

**Comment by serena13** [comment]
> I am working on improving subtitle selection code (which will fix this). But it wont be complete for a while

Thanks, I will wait

**Comment by pukkandan** [comment]
It seems there has never been a proper issue reported for it. So I am keeping this open to track this

**Comment by fstirlitz** [comment]
I think #946 already covers this.

Meanwhile, this ticket was originally opened about direct links to subtitle segment lists.

**Comment by pukkandan** [comment]
oh, I did not see that. Thanks!

In that case, I am closing this since it's not really possible to support direct subtitle manifests

**Comment by fstirlitz** [comment]
It is possible, but requires content-type sniffing: at the very least performing a HEAD request at the segments.
