### ISSUE TITLE
Peloton Overlay - cadence and resistance 

### ISSUE THREAD

**Issue by Hot-P0tato** [yt-dlp/yt-dlp#11496]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Guys just wondering if there is a way to get the overlay extracted along with the video, so this overlay only appears on the APP but it does not appear on a web url, I have found someone has utilised an API which adds the overlay details to a web url video:

https://zv3zrmct.github.io/peloton_schwinn_metrics/

The fix above is achieved by clicking on a javascript bookmark whilst you have the window open and video playing and it GETS and displays the correct.
 
However is it possible to write / include these to the downloaded mp4 ?

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
Closed due to lack of verbose log
