### ISSUE TITLE
[info] xxxxxxxxxxx: Downloading 1 format(s): 774 is logged but no download actually occurs

### ISSUE THREAD

**Issue by raintonr** [yt-dlp/yt-dlp#11505]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

France

### Provide a description that is worded well enough to be understood

yt-dlp was working for me recently (7 Oct 2024) but tried to download my discovery playlist today and while there are no errors, and output stated something was being downloaded, nothing actually was downloaded.

If I use `--verbose --print-traffic --abort-on-error --keep-video` it's the same story. Nothing is downloaded.

For each track in the playlist given the lines shown in the log below repeat. The URLs that are printed are real and work in my browser. I have verified cookies are all correct.

What is odd, is that for other HTTP request I can see headers, etc. listed with `--print-traffic` on, but directly after the `Downloading 1 format(s): 774` log there is nothing. yt-dlp just moves on to the next track in the playlist without further explanation of why and without printing any traffic information.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--config-location', 'ytmDiscovery.config']
[debug] | Config "ytmDiscovery.config": ['--verbose', '--restrict-filenames', '--no-overwrites', '--keep-video', '--format', 'bestaudio', '--extract-audio', '--audio-format', 'mp3', '--audio-quality', '0', '--embed-metadata', '--add-metadata', '--cookies', './ytm.cookies', '--get-url', 'https://www.youtube.com/playlist?list=Redacted', '--output', '/mnt/music/YTM Discovery/%(artist,uploader)s/%(album)s/%(track,title)s']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version master@2024.11.11.174914 from yt-dlp/yt-dlp-master-builds (linux_exe)
[debug] Python 3.11.10 (CPython x86_64 64bit) - Linux-6.8.8-300.fc40.x86_64-x86_64-with (OpenSSL 3.1.7 3 Sep 2024)
[debug] exe versions: ffmpeg 6.1.1 (setts), ffprobe 6.1.1
[debug] Optional libraries: Cryptodome-3.21.0, brotli-1.1.0, certifi-2024.08.30, curl_cffi-0.7.1, mutagen-1.47.0, requests-2.32.3, secretstorage-3.3.3, sqlite3-3.44.2, urllib3-2.2.3, websockets-13.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1838 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-master-builds/releases/latest
Latest version: master@2024.11.11.174914 from yt-dlp/yt-dlp-master-builds
yt-dlp is up to date (master@2024.11.11.174914 from yt-dlp/yt-dlp-master-builds)
[youtube:tab] Extracting URL: https://www.youtube.com/playlist?list=Redacted
[youtube:tab] Redacted: Downloading webpage
[debug] [youtube:tab] Extracted SAPISID cookie
[youtube:tab] Redacted: Redownloading playlist API JSON with unavailable videos
[download] Downloading playlist: Discover Mix
[youtube:tab] Playlist Discover Mix: Downloading 50 items of 50
[download] Downloading item 1 of 50
[youtube] Extracting URL: https://www.youtube.com/watch?v=DhQfOVLDuvA
[youtube] DhQfOVLDuvA: Downloading webpage
[debug] [youtube] Extracted SAPISID cookie
[youtube] DhQfOVLDuvA: Downloading ios player API JSON
[youtube] DhQfOVLDuvA: Downloading mweb player API JSON
[debug] [youtube] Extracting signature function js_6f0e2ed6_110
[debug] Loading youtube-sigfuncs.js_6f0e2ed6_110 from cache
[debug] Loading youtube-nsig.6f0e2ed6 from cache
[debug] [youtube] Decrypted nsig m5bxsjxYmD14KVi70 => 35LCPi0SeH8E8w
[debug] [youtube] Extracting signature function js_6f0e2ed6_106
[debug] Loading youtube-sigfuncs.js_6f0e2ed6_106 from cache
[debug] Loading youtube-nsig.6f0e2ed6 from cache
[debug] [youtube] Decrypted nsig cSckv_c19fAPgem3q => exCh4K36k1eYNg
[youtube] DhQfOVLDuvA: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec, channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[info] DhQfOVLDuvA: Downloading 1 format(s): 774
https://ActualWorkingURL/
[download] Downloading item 2 of 50
...
```

**Comment by seproDev** [comment]
You have `--get-url` in your config which implies `--simulate` (i.e. no actual downloading happens)

**Comment by raintonr** [comment]
Adding `--no-simulate` works. Thank you @seproDev
