### ISSUE TITLE
Need help with oauth template

### ISSUE THREAD

**Issue by sebi-berlin** [yt-dlp/yt-dlp#11519]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Hi, I wanted to add a burner account to automatically use with YouTube. 

For this I provided the following information in the yt-dlp.conf

machine youtube login oauth password "MyIndividualPassword"

Unfortunately this doesn't work, please see my output: 

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp https://www.youtube.com/watch?v=mtDx2kPfdxw
[generic] Extracting URL: machine
ERROR: [generic] 'machine' is not a valid URL. Set --default-search "ytsearch" (or run  yt-dlp "ytsearch:machine" ) to search YouTube
[generic] Extracting URL: youtube
ERROR: [generic] 'youtube' is not a valid URL. Set --default-search "ytsearch" (or run  yt-dlp "ytsearch:youtube" ) to search YouTube
[generic] Extracting URL: login
ERROR: [generic] 'login' is not a valid URL. Set --default-search "ytsearch" (or run  yt-dlp "ytsearch:login" ) to search YouTube
[generic] Extracting URL: oauth
ERROR: [generic] 'oauth' is not a valid URL. Set --default-search "ytsearch" (or run  yt-dlp "ytsearch:oauth" ) to search YouTube
[generic] Extracting URL: password
ERROR: [generic] 'password' is not a valid URL. Set --default-search "ytsearch" (or run  yt-dlp "ytsearch:password" ) to search YouTube
[youtube] Extracting URL: MyIndividualPassword
```

**Comment by bashonly** [comment]
It looks like you are trying to pass the line that should go in your `.netrc` file in the command line.

Also, don't use oauth: #11462
