### ISSUE TITLE
how to get playlist titles and ids only?

### ISSUE THREAD

**Issue by Albretch** [yt-dlp/yt-dlp#11511]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

while using the latest version:
$ date; ./yt-dlp --version
Mon 11 Nov 2024 05:16:56 PM CST
2024.11.04
 I can't just download the playlist titles and ids from a yt uploader. If you try:
 ./yt-dlp -i -o "%(playlist_id)s|%(playlist_title)s|%(playlist_index)s" --skip-download --no-warnings "@LibraryoftheUntold" 
 yt-dlp apparently works as if it were downloading the actual videos in the playlists.
 

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by seproDev** [comment]
Do you want the title and IDs of all playlists of a channel? Use:
```
yt-dlp --print "%(id)s|%(title)s|%(playlist_index)s" --flat-playlist "https://www.youtube.com/@LibraryoftheUntold/playlists"
```

**Comment by Albretch** [comment]
that did it! the settings are a bit confusing.

**Comment by Albretch** [comment]
last related question: How do you include the number of videos in that playlist?

**Comment by Albretch** [comment]
I asked because neither of these worked:

"%(id)s|%(title)s|%(playlist_count)s|%(playlist_index)s"
"%(id)s|%(title)s|%(count)s|%(playlist_index)s"

 "%(playlist_count)s" would repeatedly give you the number of playlists in the uploader's account (not the number of videos in that playlist) and "%(count)s" would result in no output at all.

**Comment by bashonly** [comment]
> How do you include the number of videos in that playlist?

You can't if you are using `--flat-playlist`. "Flat" means only the outer playlist is processed, any videos or nested playlists within are not processed.
