### ISSUE TITLE
 yt-dlp HTTP Error 400 when downloading YouTube video

### ISSUE THREAD

**Issue by MrDaRkFoRcE** [yt-dlp/yt-dlp#11539]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [x] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

I'm encountering an issue when trying to download a YouTube video using yt-dlp. The error I receive is an HTTP 400 (Bad Request) after attempting to extract video data. The message indicates that YouTube returns "Request contains an invalid argument."

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
Here is the complete verbose output I get when running the command:

root@dark:~# yt-dlp --username=oauth --password="" https://www.youtube.com/watch?v=3Fr-o01awPE
[youtube] oauth: Refreshing access token
[youtube] Extracting URL: https://www.youtube.com/watch?v=3Fr-o01awPE
[youtube] 3Fr-o01awPE: Downloading webpage
[youtube] 3Fr-o01awPE: Downloading ios player API JSON
[youtube] 3Fr-o01awPE: Downloading mweb player API JSON
[youtube] 3Fr-o01awPE: Downloading m3u8 information
WARNING: [youtube] Incomplete data received in embedded initial data; re-fetching using API.
[youtube] 3Fr-o01awPE: Downloading initial data API JSON
WARNING: [youtube] YouTube said: ERROR - Request contains an invalid argument.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (1/3)...
[youtube] 3Fr-o01awPE: Downloading initial data API JSON
WARNING: [youtube] YouTube said: ERROR - Request contains an invalid argument.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (2/3)...
[youtube] 3Fr-o01awPE: Downloading initial data API JSON
WARNING: [youtube] YouTube said: ERROR - Request contains an invalid argument.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (3/3)...
[youtube] 3Fr-o01awPE: Downloading initial data API JSON
WARNING: [youtube] YouTube said: ERROR - Request contains an invalid argument.
ERROR: [youtube] 3Fr-o01awPE: Unable to download API page: HTTP Error 400: Bad Request (caused by <HTTPError 400: Bad Request>)
```

**Comment by bashonly** [comment]
Duplicate of #11462

Stop using OAuth
