### ISSUE TITLE
Can't download videos to my preferred folder using the "-P" command, getting Error 

### ISSUE THREAD

**Issue by TylerDurden90** [yt-dlp/yt-dlp#11544]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I'm completely new to yt-dlp as well as using the Command Prompt. I want to download a video to a specific folder on my Windows computer. The yt-dlp.exe is saved on C: and I want to download the video to "D:\Alex\Videos". I put ffmpeg.exe, ffprobe.exe and yt-dlp.exe in one folder and added that folder to my PATH environment, so that I'm able to use yt-dlp in the command prompt from any location. 

Now, when I type the command "yt-dlp -P "D:\Alex\Videos" -S "res:720" https://www.youtube.com/watch?v=njX2bu-_Vw4" and hit enter, it doesn't work, I get "ERROR: unable to open for writing: [Errno 2] No such file or directory: 'D:\\Alex\\Videos\\2020 LG OLED l  The Black 4K HDR 60fps [njX2bu-_Vw4].f698.mp4.part' ". 

What I find strange is, when I type a comma after "D:\Alex\Videos", the video is downloaded. The command then looks like this: 
yt-dlp -P "D:\Alex\Videos", -S "res:720" https://www.youtube.com/watch?v=njX2bu-_Vw4

But now, the video is not saved in "D:\Alex\Videos". At "D:\Alex", a new folder named "Videos," (with the comma) is created, where the video is saved.

Does somebody know, why this happens and why I can't save the video to "D:\Alex\Videos"

Thanks a lot in advance!

### Provide verbose output that clearly demonstrates the problem

- [x] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [x] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

[debug] Command-line config: ['-vU', '-P', 'D:\\Alex\\Videos', '-S', 'res:720', 'https://www.youtube.com/watch?v=njX2bu-_Vw4']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.11.04 from yt-dlp/yt-dlp [197d0b03b] (win_exe)
[debug] Python 3.10.11 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1t  7 Feb 2023)
[debug] exe versions: ffmpeg 2024-11-11-git-96d45c3b21-full_build-www.gyan.dev (setts), ffprobe 2024-11-11-git-96d45c3b21-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.21.0, brotli-1.1.0, certifi-2024.08.30, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.40.1, urllib3-2.2.3, websockets-13.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1838 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.11.04 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.11.04 from yt-dlp/yt-dlp)
[youtube] Extracting URL: https://www.youtube.com/watch?v=njX2bu-_Vw4
[youtube] njX2bu-_Vw4: Downloading webpage
[youtube] njX2bu-_Vw4: Downloading ios player API JSON
[youtube] njX2bu-_Vw4: Downloading mweb player API JSON
[debug] Loading youtube-nsig.0ccfa671 from cache
[debug] [youtube] Decrypted nsig l4959jVW0AwVJAn => YJ97gPMz8oMUOg
[debug] Loading youtube-nsig.0ccfa671 from cache
[debug] [youtube] Decrypted nsig J9yU0d8Upi-MHHI => 1J07nTzKgtDJMg
[youtube] njX2bu-_Vw4: Downloading m3u8 information
[debug] Sort order given by user: res:720
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, res:720(720.0), quality, fps, hdr:12(7), source, vcodec, channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] njX2bu-_Vw4: Downloading 1 format(s): 698+258
[debug] Invoking http downloader on "https://rr5---sn-4g5lzned.googlevideo.com/videoplayback?expire=1731642631&ei=p3A2Z_K_CaGBi9oPx42PwQI&ip=192.145.125.36&id=o-AIzZCSpAxdCJUX2OApOz7WFmtQWcDhJQ6bsSaCqgFKds&itag=698&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&met=1731621031%2C&mh=zf&mm=31%2C26&mn=sn-4g5lzned%2Csn-f5f7knee&ms=au%2Conr&mv=m&mvi=5&pl=25&rms=au%2Cau&initcwndbps=816250&spc=qtApAZPrlzqYVBz6gK4a_O2ACZV4Nv-vTv9m3hoehVcVcZA&vprv=1&c=IOS&svpuc=1&mime=video%2Fmp4&rqh=1&gir=yes&clen=41846957&dur=126.543&lmt=1728201579157156&mt=1731620725&fvip=5&keepalive=yes&fexp=51299154%2C51312688%2C51326932&txp=550C434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cspc%2Cvprv%2Cc%2Csvpuc%2Cmime%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRAIgBzV9OuxNgW0GkEIucGMijhmS77r0PcGq-QqGwGMtiYICICPzeNfJsTun7rb0JNcH8vZx_GT1jk0xKiSdxJbvIWNh&lsparams=met%2Cmh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Crms%2Cinitcwndbps&lsig=AGluJ3MwRQIhAO5Li3a2S5C3NCcTJKSPfNDogT-Hvkf-ESJTwR7KK33zAiBT_UWImrv9pvggN_omJZPkYinyrpSIQVBLhf2opnQz_A%3D%3D"
ERROR: unable to open for writing: [Errno 2] No such file or directory: 'D:\\Alex\\Videos\\2020 LG OLED l  The Black 4K HDR 60fps [njX2bu-_Vw4].f698.mp4.part'
Traceback (most recent call last):
  File "yt_dlp\utils\_utils.py", line 607, in sanitize_open
yt_dlp.utils.LockingUnsupportedError: File locking is not supported

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\downloader\http.py", line 265, in download
  File "yt_dlp\downloader\common.py", line 250, in wrapper
  File "yt_dlp\downloader\common.py", line 236, in error_callback
  File "yt_dlp\utils\_utils.py", line 5279, in report_retry
  File "yt_dlp\downloader\common.py", line 245, in wrapper
  File "yt_dlp\downloader\common.py", line 256, in sanitize_open
  File "yt_dlp\utils\_utils.py", line 610, in sanitize_open
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\Alex\\Videos\\2020 LG OLED l  The Black 4K HDR 60fps [njX2bu-_Vw4].f698.mp4.part'

[debug] Invoking http downloader on "https://rr1---sn-4g5edn6r.googlevideo.com/videoplayback?expire=1731642631&ei=p3A2Z_XSEYeBi9oPvYPMiQM&ip=192.145.125.36&id=o-ALqwmlEZpZYJsd8u-Hzapk_LIpq8KG1AYgVO9whSNs6P&itag=258&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&met=1731621031%2C&mh=zf&mm=31%2C29&mn=sn-4g5edn6r%2Csn-4g5lzned&ms=au%2Crdu&mv=m&mvi=1&pl=25&rms=au%2Cau&initcwndbps=816250&bui=AQn3pFTU3P6L_Vtd4aClcSr0tcjQX9-i0fZdS360bETHRiAgOai4qFuRhAxZbetwGIAUPpzeHR2chNza&spc=qtApAdCzdln82aS-NYUC18YmIiVGaDn2sT-57_4hN3p0BzLw1mQTzhe4Klbx&vprv=1&c=MWEB&svpuc=1&mime=audio%2Fmp4&ns=f3lywEC5uDgOxOH9_rq0-zIQ&rqh=1&gir=yes&clen=6138019&dur=126.592&lmt=1728200688570845&mt=1731620725&fvip=5&keepalive=yes&fexp=51299154%2C51312688%2C51326932%2C51331020&sefc=1&txp=5502434&n=1J07nTzKgtDJMg&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cbui%2Cspc%2Cvprv%2Cc%2Csvpuc%2Cmime%2Cns%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRQIhAPv_PL7B_zqIUUPLcexkP9tawvIMHpbniuQQynFCJaxlAiBZ6lWlaZvDQMD0cSvR9SgzcTftMO8IsO1b5U24kmzz4g%3D%3D&lsparams=met%2Cmh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Crms%2Cinitcwndbps&lsig=AGluJ3MwRgIhAJ4NX_h10wpv-BoNfq8g083C96j3uFfX8qC5ylSYtqfhAiEAp3D__o_gbvV3j3tBY6KWXfwPrXIJ6dYl1h0cNcB5Iyg%3D"
ERROR: unable to open for writing: [Errno 2] No such file or directory: 'D:\\Alex\\Videos\\2020 LG OLED l  The Black 4K HDR 60fps [njX2bu-_Vw4].f258.m4a.part'
Traceback (most recent call last):
  File "yt_dlp\utils\_utils.py", line 607, in sanitize_open
yt_dlp.utils.LockingUnsupportedError: File locking is not supported

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\downloader\http.py", line 265, in download
  File "yt_dlp\downloader\common.py", line 250, in wrapper
  File "yt_dlp\downloader\common.py", line 236, in error_callback
  File "yt_dlp\utils\_utils.py", line 5279, in report_retry
  File "yt_dlp\downloader\common.py", line 245, in wrapper
  File "yt_dlp\downloader\common.py", line 256, in sanitize_open
  File "yt_dlp\utils\_utils.py", line 610, in sanitize_open
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\Alex\\Videos\\2020 LG OLED l  The Black 4K HDR 60fps [njX2bu-_Vw4].f258.m4a.part'

**Comment by bashonly** [comment]
provide complete verbose output please

**Comment by TylerDurden90** [comment]
Complete Verbose Output

[debug] Command-line config: ['-vU', '-P', 'D:\Alex\Videos', '-S', 'res:720', 'https://www.youtube.com/watch?v=njX2bu-_Vw4']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.11.04 from yt-dlp/yt-dlp [https://github.com/yt-dlp/yt-dlp/commit/197d0b03b6a3c8fe4fa5ace630eeffec629bf72c] (win_exe)
[debug] Python 3.10.11 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1t 7 Feb 2023)
[debug] exe versions: ffmpeg 2024-11-11-git-96d45c3b21-full_build-www.gyan.dev (setts), ffprobe 2024-11-11-git-96d45c3b21-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.21.0, brotli-1.1.0, certifi-2024.08.30, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.40.1, urllib3-2.2.3, websockets-13.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1838 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.11.04 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.11.04 from yt-dlp/yt-dlp)
[youtube] Extracting URL: https://www.youtube.com/watch?v=njX2bu-_Vw4
[youtube] njX2bu-_Vw4: Downloading webpage
[youtube] njX2bu-_Vw4: Downloading ios player API JSON
[youtube] njX2bu-_Vw4: Downloading mweb player API JSON
[debug] Loading youtube-nsig.0ccfa671 from cache
[debug] [youtube] Decrypted nsig l4959jVW0AwVJAn => YJ97gPMz8oMUOg
[debug] Loading youtube-nsig.0ccfa671 from cache
[debug] [youtube] Decrypted nsig J9yU0d8Upi-MHHI => 1J07nTzKgtDJMg
[youtube] njX2bu-_Vw4: Downloading m3u8 information
[debug] Sort order given by user: res:720
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, res:720(720.0), quality, fps, hdr:12(7), source, vcodec, channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] njX2bu-_Vw4: Downloading 1 format(s): 698+258
[debug] Invoking http downloader on "https://rr5---sn-4g5lzned.googlevideo.com/videoplayback?expire=1731642631&ei=p3A2Z_K_CaGBi9oPx42PwQI&ip=192.145.125.36&id=o-AIzZCSpAxdCJUX2OApOz7WFmtQWcDhJQ6bsSaCqgFKds&itag=698&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&met=1731621031%2C&mh=zf&mm=31%2C26&mn=sn-4g5lzned%2Csn-f5f7knee&ms=au%2Conr&mv=m&mvi=5&pl=25&rms=au%2Cau&initcwndbps=816250&spc=qtApAZPrlzqYVBz6gK4a_O2ACZV4Nv-vTv9m3hoehVcVcZA&vprv=1&c=IOS&svpuc=1&mime=video%2Fmp4&rqh=1&gir=yes&clen=41846957&dur=126.543&lmt=1728201579157156&mt=1731620725&fvip=5&keepalive=yes&fexp=51299154%2C51312688%2C51326932&txp=550C434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cspc%2Cvprv%2Cc%2Csvpuc%2Cmime%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRAIgBzV9OuxNgW0GkEIucGMijhmS77r0PcGq-QqGwGMtiYICICPzeNfJsTun7rb0JNcH8vZx_GT1jk0xKiSdxJbvIWNh&lsparams=met%2Cmh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Crms%2Cinitcwndbps&lsig=AGluJ3MwRQIhAO5Li3a2S5C3NCcTJKSPfNDogT-Hvkf-ESJTwR7KK33zAiBT_UWImrv9pvggN_omJZPkYinyrpSIQVBLhf2opnQz_A%3D%3D"
ERROR: unable to open for writing: [Errno 2] No such file or directory: 'D:\Alex\Videos\2020 LG OLED l The Black 4K HDR 60fps [njX2bu-_Vw4].f698.mp4.part'
Traceback (most recent call last):
File "yt_dlp\utils_utils.py", line 607, in sanitize_open
yt_dlp.utils.LockingUnsupportedError: File locking is not supported

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "yt_dlp\downloader\http.py", line 265, in download
File "yt_dlp\downloader\common.py", line 250, in wrapper
File "yt_dlp\downloader\common.py", line 236, in error_callback
File "yt_dlp\utils_utils.py", line 5279, in report_retry
File "yt_dlp\downloader\common.py", line 245, in wrapper
File "yt_dlp\downloader\common.py", line 256, in sanitize_open
File "yt_dlp\utils_utils.py", line 610, in sanitize_open
FileNotFoundError: [Errno 2] No such file or directory: 'D:\Alex\Videos\2020 LG OLED l The Black 4K HDR 60fps [njX2bu-_Vw4].f698.mp4.part'

[debug] Invoking http downloader on "https://rr1---sn-4g5edn6r.googlevideo.com/videoplayback?expire=1731642631&ei=p3A2Z_XSEYeBi9oPvYPMiQM&ip=192.145.125.36&id=o-ALqwmlEZpZYJsd8u-Hzapk_LIpq8KG1AYgVO9whSNs6P&itag=258&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&met=1731621031%2C&mh=zf&mm=31%2C29&mn=sn-4g5edn6r%2Csn-4g5lzned&ms=au%2Crdu&mv=m&mvi=1&pl=25&rms=au%2Cau&initcwndbps=816250&bui=AQn3pFTU3P6L_Vtd4aClcSr0tcjQX9-i0fZdS360bETHRiAgOai4qFuRhAxZbetwGIAUPpzeHR2chNza&spc=qtApAdCzdln82aS-NYUC18YmIiVGaDn2sT-57_4hN3p0BzLw1mQTzhe4Klbx&vprv=1&c=MWEB&svpuc=1&mime=audio%2Fmp4&ns=f3lywEC5uDgOxOH9_rq0-zIQ&rqh=1&gir=yes&clen=6138019&dur=126.592&lmt=1728200688570845&mt=1731620725&fvip=5&keepalive=yes&fexp=51299154%2C51312688%2C51326932%2C51331020&sefc=1&txp=5502434&n=1J07nTzKgtDJMg&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cbui%2Cspc%2Cvprv%2Cc%2Csvpuc%2Cmime%2Cns%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRQIhAPv_PL7B_zqIUUPLcexkP9tawvIMHpbniuQQynFCJaxlAiBZ6lWlaZvDQMD0cSvR9SgzcTftMO8IsO1b5U24kmzz4g%3D%3D&lsparams=met%2Cmh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Crms%2Cinitcwndbps&lsig=AGluJ3MwRgIhAJ4NX_h10wpv-BoNfq8g083C96j3uFfX8qC5ylSYtqfhAiEAp3D__o_gbvV3j3tBY6KWXfwPrXIJ6dYl1h0cNcB5Iyg%3D"
ERROR: unable to open for writing: [Errno 2] No such file or directory: 'D:\Alex\Videos\2020 LG OLED l The Black 4K HDR 60fps [njX2bu-_Vw4].f258.m4a.part'
Traceback (most recent call last):
File "yt_dlp\utils_utils.py", line 607, in sanitize_open
yt_dlp.utils.LockingUnsupportedError: File locking is not supported

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "yt_dlp\downloader\http.py", line 265, in download
File "yt_dlp\downloader\common.py", line 250, in wrapper
File "yt_dlp\downloader\common.py", line 236, in error_callback
File "yt_dlp\utils_utils.py", line 5279, in report_retry
File "yt_dlp\downloader\common.py", line 245, in wrapper
File "yt_dlp\downloader\common.py", line 256, in sanitize_open
File "yt_dlp\utils_utils.py", line 610, in sanitize_open
FileNotFoundError: [Errno 2] No such file or directory: 'D:\Alex\Videos\2020 LG OLED l The Black 4K HDR 60fps [njX2bu-_Vw4].f258.m4a.part'

**Comment by bashonly** [comment]
Does yt-dlp have permission to write to `D:\Alex\Videos`? Windows has some kind of "protected folders" setting, are you sure that isn't enabled for that directory?

**Comment by TylerDurden90** [comment]
No, I'm not sure. How can I find out if that setting is enabled for that directory?

**Comment by bashonly** [comment]
Not sure, I don't use Windows. It's called "Controlled folder access" though. Search around

**Comment by dirkf** [comment]
From https://learn.microsoft.com/en-us/defender-endpoint/controlled-folders:
>The Windows systems folders that are protected by default are:
>
>...
>*   c:\Users\<username>\Videos
>...

In the same page: "Controlled folder access can be configured by using the Windows Security App ..."

Anyone would think that this feature was required because of some fundamental flaw in Windows security.

**Comment by TylerDurden90** [comment]
That was exactly the reason why it didn't work. Thanks a lot for the quick help!
