### ISSUE TITLE
One link only to download the latest yt-dlp

### ISSUE THREAD

**Issue by hbtalha** [yt-dlp/yt-dlp#1154]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running yt-dlp version **2021.09.25**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description

In youtube-dl you have one link only that will always download the latest version, I used to use to that to automatically download the latest version from a GUI program. Now I am switching to yt-dlp it would be great if I could do the same with yt-dlp.

**Comment by pukkandan** [comment]
https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp.exe

**Comment by hbtalha** [comment]
Thank you!
