### ISSUE TITLE
[Soop] Live Download Error

### ISSUE THREAD

**Issue by hui1601** [yt-dlp/yt-dlp#11549]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

South Korea

### Provide a description that is worded well enough to be understood

Background Context: The three major telecommunications companies in South Korea (Korea Telecom, SK Telecom, LG U+), which effectively maintain a monopoly, charge network usage fees to CPs (Content Providers). This violates network neutrality, and Soop is forcibly installing P2P clients to reduce Korea's network usage fees, which are 20-30 times higher than other regions worldwide.

Recently, Soop has modified their Live API to include the client's current quality (cq: client quality) value when requesting aid, in order to block user scripts (https://github.com/hui1601/AfreecaBypassInstallAgent) that bypass mandatory P2P installation.

https://github.com/yt-dlp/yt-dlp/blob/f2a4983df7a64c4e93b56f79dbd16a781bd90206/yt_dlp/extractor/afreecatv.py#L336-L344
Therefore, `'cq': 'sd'` needs to be added here.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-v', 'https://play.sooplive.co.kr/jingburger1/278711366']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.11.04 from yt-dlp/yt-dlp [197d0b03b] (source)
[debug] Git HEAD: f2a4983df
[debug] Python 3.12.4 (CPython x86_64 64bit) - Linux-6.11.0-9-generic-x86_64-with-glibc2.40 (OpenSSL 3.0.14 4 Jun 2024, glibc 2.40)
[debug] exe versions: ffmpeg 7.0.2 (setts), ffprobe 7.0.2
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.0.9, certifi-2024.06.02, mutagen-1.47.0, requests-2.32.2, secretstorage-3.3.1, sqlite3-3.45.3, urllib3-2.2.2, websockets-13.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1838 extractors
[generic] Extracting URL: https://play.sooplive.co.kr/jingburger1/278711366
[generic] 278711366: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] 278711366: Extracting information
[debug] Looking for embeds
WARNING: Falling back to normal extractor since lazy extractor CNNArticleIE does not have attribute real_class; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
ERROR: maximum recursion depth exceeded
Traceback (most recent call last):
  File "/data/projects/yt-dlp/yt_dlp/YoutubeDL.py", line 1625, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/projects/yt-dlp/yt_dlp/YoutubeDL.py", line 1760, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "/data/projects/yt-dlp/yt_dlp/extractor/common.py", line 742, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/projects/yt-dlp/yt_dlp/extractor/generic.py", line 2548, in _real_extract
    embeds = list(self._extract_embeds(original_url, webpage, urlh=full_response, info_dict=info_dict))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/projects/yt-dlp/yt_dlp/extractor/generic.py", line 2573, in _extract_embeds
    gen = ie.extract_from_webpage(self._downloader, url, webpage)
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/projects/yt-dlp/yt_dlp/extractor/lazy_extractors.py", line 26, in __getattr__
    return getattr(cls.real_class, name)
                   ^^^^^^^^^^^^^^
  File "/data/projects/yt-dlp/yt_dlp/extractor/lazy_extractors.py", line 26, in __getattr__
    return getattr(cls.real_class, name)
                   ^^^^^^^^^^^^^^
  File "/data/projects/yt-dlp/yt_dlp/extractor/lazy_extractors.py", line 26, in __getattr__
    return getattr(cls.real_class, name)
                   ^^^^^^^^^^^^^^
  [Previous line repeated 982 more times]
  File "/data/projects/yt-dlp/yt_dlp/utils/_utils.py", line 5053, in __get__
    return self.func(cls)
           ^^^^^^^^^^^^^^
  File "/data/projects/yt-dlp/yt_dlp/extractor/lazy_extractors.py", line 33, in real_class
    cls._real_class = getattr(importlib.import_module(cls._module), cls.__name__)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hibot/anaconda3/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1384, in _gcd_import
RecursionError: maximum recursion depth exceeded
```

**Comment by seproDev** [comment]
It looks like you are running from source with lazy extractors, but have not rebuilt your `lazy_extractors.py` file after pulling changes.
When running from source, I would recommend not building lazy extractors. `rm yt_dlp/extractor/lazy_extractors.py`

**Comment by hui1601** [comment]
```
LivePlayer.js file has been updated!

Hash comparison
Previous: fb40d636d03fbf3f3f4b0ca45d2a01577d20a560
Current: 3e0a89c1741520b61705da852e427ff562114690
```
Soop has just rolled back the changes.
I will close this issue.
