### ISSUE TITLE
Can't extract cookies from brave anymore on Linux / ERROR: Item does not exist!

### ISSUE THREAD

**Issue by TheWranger** [yt-dlp/yt-dlp#11570]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

After updating to Brave 1.73.89 on Linux, using `cookies-from-browser brave` returns `ERROR: Item does not exist!`. Using Linux Mint 21.3 Cinnamon. Brave 1.71.123 doesn't have the issue.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--cookies-from-browser', 'brave', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version master@2024.11.17.193527 from yt-dlp/yt-dlp-master-builds (linux_exe)
[debug] Python 3.11.10 (CPython x86_64 64bit) - Linux-6.8.0-48-generic-x86_64-with (OpenSSL 3.1.7 3 Sep 2024)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2
[debug] Optional libraries: Cryptodome-3.21.0, brotli-1.1.0, certifi-2024.08.30, curl_cffi-0.7.1, mutagen-1.47.0, requests-2.32.3, secretstorage-3.3.3, sqlite3-3.44.2, urllib3-2.2.3, websockets-13.1
[debug] Proxy map: {}
Extracting cookies from brave
[debug] Extracting cookies from: "/home/anon/.config/BraveSoftware/Brave-Browser/Default/Cookies"
[Cookies] Loading cookie      0/   149[debug] detected desktop environment: CINNAMON
[debug] Chosen keyring: GNOMEKEYRING
ERROR: Item does not exist!
Traceback (most recent call last):
  File "secretstorage/util.py", line 48, in send_and_get_reply
jeepney.wrappers.DBusErrorResponse: [org.freedesktop.DBus.Error.UnknownMethod] ('Object does not exist at path “/org/freedesktop/secrets/collection/login/6”',)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "yt_dlp/cookies.py", line 99, in load_cookies
  File "yt_dlp/cookies.py", line 122, in extract_cookies_from_browser
  File "yt_dlp/cookies.py", line 328, in _extract_chrome_cookies
  File "yt_dlp/cookies.py", line 363, in _process_chrome_cookie
  File "yt_dlp/cookies.py", line 464, in decrypt
  File "functools.py", line 1001, in __get__
  File "yt_dlp/cookies.py", line 433, in _v11_key
  File "yt_dlp/cookies.py", line 972, in _get_linux_keyring_password
  File "yt_dlp/cookies.py", line 952, in _get_gnome_keyring_password
  File "secretstorage/collection.py", line 87, in get_all_items
  File "secretstorage/item.py", line 32, in __init__
  File "secretstorage/util.py", line 67, in get_property
  File "secretstorage/util.py", line 52, in send_and_get_reply
secretstorage.exceptions.ItemNotFoundException: Item does not exist!
```

**Comment by bashonly** [comment]
Did this start happening recently?

**Comment by bashonly** [comment]
Possibly related: https://github.com/mitya57/secretstorage/issues/42

**Comment by bashonly** [comment]
More information might help, e.g. your linux distro and version, your desktop environment, your keyring daemon (`gnome-keyring`?)

**Comment by grawity** [comment]
> Object does not exist at path 

It might likely be a bug in gnome-keyring-daemon's "secret-service" code. I've seen it several times in the past (unrelated to yt-dlp). Usually goes away at the next boot/login, i.e. when gnome-keyring-daemon starts fresh and re-reads the keyring file.
