### ISSUE TITLE
min max sleep interval does not apply to thumbnail and subtitles, resulting HTTP 429 error

### ISSUE THREAD

**Issue by Lumerica** [yt-dlp/yt-dlp#11580]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

By using --min-sleep-interval and --max-sleep-interval I expected that it applies for even subtitles or anything it downloads. However that is not the case. If you wrote a generic command to download any available subtitle the command will just run through all requested subtitles and download any subtitles without break.

This results in HTTP 429 errors and risking IP ban.

e.g. adding this command alone that I use got me few times ip ban:
--write-thumbnail --min-sleep-interval 20 --max-sleep-interval 50 --write-subs --write-auto-subs --sub-format "best" --sub-langs "ja-ko,en.*,ko-orig,ja-orig,ko-ja,en,ko,ja"

So I would like to suggest to have an option to apply the interval for downloading/writing subtitle and alternatively also a separate option to apply it when downloading thumbnail.
Having this option, people can just use a single command load a list of URL from text files and download just the thumbnails while having the interval applied to avoid risking IP ban.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
```
--sleep-requests SECONDS        Number of seconds to sleep between requests
                                during data extraction
--sleep-subtitles SECONDS       Number of seconds to sleep before each
                                subtitle download
```
