### ISSUE TITLE
stripchat extractor not working: "No active stream found"

### ISSUE THREAD

**Issue by mosmos-fict** [yt-dlp/yt-dlp#11587]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Israel

### Provide a description that is worded well enough to be understood

When trying to download a stream from stripchat.com yt-dlp gives back "No active stream" even though a stream is live at the same time. If I paste the m3u8 of the same stream then yt-dlp works and downloads the stream.

sidenote:
I tried to set my yt-dlp to nightly but can't because I downloaded it from homebrew. and using yt-dlp --update-to nightly gives back:
"ERROR: You installed yt-dlp from a manual build or with a package manager; Use that to update"
and no documentation on how to exactly do that.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://stripchat.com/MagicLilu']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.11.18 from yt-dlp/yt-dlp [7ea278792]
[debug] Python 3.13.0 (CPython arm64 64bit) - macOS-14.6.1-arm64-arm-64bit-Mach-O (OpenSSL 3.4.0 22 Oct 2024)
[debug] exe versions: ffmpeg 7.1 (setts), ffprobe 7.1
[debug] Optional libraries: Cryptodome-3.21.0, brotli-1.1.0, certifi-2024.08.30, mutagen-1.47.0, requests-2.32.3, sqlite3-3.47.0, urllib3-2.2.3, websockets-13.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1837 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.11.18 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.11.18 from yt-dlp/yt-dlp)
[Stripchat] Extracting URL: https://stripchat.com/MagicLilu
[Stripchat] MagicLilu: Downloading webpage
ERROR: [Stripchat] MagicLilu: No active streams found
  File "/opt/homebrew/Cellar/yt-dlp/HEAD-f919729/libexec/lib/python3.13/site-packages/yt_dlp/extractor/common.py", line 742, in extract
    ie_result = self._real_extract(url)
  File "/opt/homebrew/Cellar/yt-dlp/HEAD-f919729/libexec/lib/python3.13/site-packages/yt_dlp/extractor/stripchat.py", line 56, in _real_extract
    self.raise_no_formats('No active streams found', expected=True)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/yt-dlp/HEAD-f919729/libexec/lib/python3.13/site-packages/yt_dlp/extractor/common.py", line 1276, in raise_no_formats
    raise ExtractorError(msg, expected=expected, video_id=video_id)
```

**Comment by mikeymatrix70** [comment]
Looks like they're using .live as a host now
https://edge-hls.doppiocdn.com/hls/164812713/master/164812713_auto.m3u8 doesn't work but https://edge-hls.doppiocdn.live/hls/164812713/master/164812713_auto.m3u8 does so Stripchat extractor needs .live as a fallback I think. Also is there a way to also use xHamsterLive as it uses the exact same manifests but  doesn't work because of domain name.

**Comment by dickylawre** [comment]
its showing on telegram bot
ERROR: [Stripchat] valeriadiax: No active streams found
