### ISSUE TITLE
[Feature Request] Option to specify arbitrary browser_dir to extract cookies from

### ISSUE THREAD

**Issue by exikyut** [yt-dlp/yt-dlp#1159]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running yt-dlp version **2021.09.25**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description

`--cookies-from-browser` makes it possible to extract browser cookies from a particular browser, and (presumably) works great if you're using the standard directories like `~/.config/chromium` etc. I learned about the `--user-data-dir` option long before I discovered the browser's profile selector GUI, and I've been using it for years as an easy-to-reason-about way to keep sessions completely isolated. The current cookie extract implementation has no way to point `yt-dlp` at alternate data directories.

One approach to fix this could be to look for a `:` after the profile name, so you could do things like `--cookies_from_browser chrome::/path/to/user_data_dir` to look for the `"" -> Default` profile in that path.

A simpler approach, which *would* add an extra commandline option, would be to introduce `--browser-dir`.

In all fairness I'm not sure how non-Chromium browsers handle this. It looks like Firefox lets you hand arbitrary paths to `--profile`, while Safari doesn't seem to have any options for this at all. In any case, any directory with the right cookie files in it is technically acceptable.

In any case, I'm happy just leaving this here; I was just trying to download a playlist I'd set to *Private* and thought it would be interesting to see how the cookie extractor worked. No issues just changing it to *Unlisted* instead.

(Cheeky bonus bugreport: `chrome` is mapped to `~/.config/chromium`, but I'm using the official Chrome Dev (so I retain access to Sync, Translate etc - yep, I'm mad), so `yt-dlp` can't even see my profile directory anyway - there are no mappings/options for directories like `~/.config/google-chrome` or `~/.config/google-chrome-unstable`. Fixing the above would allow me to manually point `yt-dlp` directly at the correct directory.)

**Comment by pukkandan** [comment]
You can already do this. From README:
```
--cookies-from-browser BROWSER[:PROFILE]
                                 Load cookies from a user profile of the
                                 given web browser. Currently supported
                                 browsers are: brave, chrome, chromium,
                                 edge, firefox, opera, safari, vivaldi. You
                                 can specify the user profile name or
                                 directory using "BROWSER:PROFILE_NAME" or
                                 "BROWSER:PROFILE_PATH". If no profile is
                                 given, the most recently accessed one is
                                 used
```

> You can specify the user profile name **or directory** using "BROWSER:PROFILE_NAME" or **"BROWSER:PROFILE_PATH"**

**Comment by exikyut** [comment]
### \*<i>Facepalm</i>\*

I actually took a look at the code before posting, but didn't come across any logic that would indicate this functionality was present.

Thanks so much.

**Comment by pukkandan** [comment]
Here's the relevant logic

https://github.com/yt-dlp/yt-dlp/blob/ff1dec819a38addb73c9d52bd47fbac01b10e5d1/yt_dlp/cookies.py#L739-L745

**Comment by exikyut** [comment]
D'oh. `is_path`. Yep, I'm really bad at reading Python ;)

Thanks again. Really cool project.
