### ISSUE TITLE
What option should I use in api so that skip fragment does not occur?

### ISSUE THREAD

**Issue by Abdolahi34** [yt-dlp/yt-dlp#11593]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

hello
I will download using the source of the project.
But while downloading, when the internet is weak, I encounter skip fragment.
What should I do to avoid skip fragment?
What option should I add when using yt_dlp.YoutubeDL class?

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by seproDev** [comment]
The same options you would use for the CLI. Namely `--fragment-retries `, `--retry-sleep`, `--abort-on-unavailable-fragments`, etc.
You can use [`devscripts/cli_to_api.py`](https://github.com/yt-dlp/yt-dlp/blob/master/devscripts/cli_to_api.py) to convert from CLI to API.

**Comment by bashonly** [comment]
```py
ydl_opts = {'skip_unavailable_fragments': False}
```
