### ISSUE TITLE
Youtube is not working not downloading not with the site

### ISSUE THREAD

**Issue by Ngbcoder** [yt-dlp/yt-dlp#11590]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Youtube playlist not downloading i pinged google and youtube it it worked

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
olan@npi-rpi4:~/vids $ ./yt-dlp -f bv*+ba https://youtube.com/playlist?list=PLaURolsKD_VHYsYQ_7E73V5Wdg8361JPL -v
[debug] Command-line config: ['-f', 'bv*+ba', 'https://youtube.com/playlist?list=PLaURolsKD_VHYsYQ_7E73V5Wdg8361JPL', '-v']
[debug] Encodings: locale utf-8, fs utf-8, pref utf-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.11.18 from yt-dlp/yt-dlp [7ea278792] (zip)
[debug] Python 3.11.2 (CPython aarch64 64bit) - Linux-6.6.51+rpt-rpi-v8-aarch64-with-glibc2.36 (OpenSSL 3.0.15 3 Sep 2024, glibc 2.36)
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.11.0, certifi-2022.09.24, requests-2.28.1, sqlite3-3.40.1, urllib3-1.26.12
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Loaded 1837 extractors
[youtube:tab] Extracting URL: https://youtube.com/playlist?list=PLaURolsKD_VHYsYQ_7E73V5Wdg8361JPL
[youtube:tab] PLaURolsKD_VHYsYQ_7E73V5Wdg8361JPL: Downloading webpage
WARNING: [youtube:tab] _ssl.c:975: The handshake operation timed out. Retrying (1/3)...
[youtube:tab] PLaURolsKD_VHYsYQ_7E73V5Wdg8361JPL: Downloading webpage
WARNING: [youtube:tab] _ssl.c:975: The handshake operation timed out. Retrying (2/3)...
[youtube:tab] PLaURolsKD_VHYsYQ_7E73V5Wdg8361JPL: Downloading webpage
WARNING: [youtube:tab] _ssl.c:975: The handshake operation timed out. Retrying (3/3)...
[youtube:tab] PLaURolsKD_VHYsYQ_7E73V5Wdg8361JPL: Downloading webpage
```

**Comment by coletdjnz** [comment]
issue with your connection
