### ISSUE TITLE
Yt-dlp with proxy not works on YouTube

### ISSUE THREAD

**Issue by Kuchizu** [yt-dlp/yt-dlp#11592]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Ukraine, Netherlands

### Example URLs

https://www.youtube.com/watch?v=UT94rXV_Vp4

### Provide a description that is worded well enough to be understood

Download with proxy not works after pip update. Checked with many proxies, it worked yesterday but not today.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
(venv) root@korneluk92:~/YTLoaders# yt-dlp https://www.youtube.com/watch?v=UT94rXV_Vp4 --proxy='user88048:vm953z@194.93.3.148:7103' -v
[debug] Command-line config: ['https://www.youtube.com/watch?v=UT94rXV_Vp4', '--proxy=user88048:vm953z@194.93.3.148:7103', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.11.04 from yt-dlp/yt-dlp [197d0b03b] (pip)
[debug] Python 3.10.12 (CPython x86_64 64bit) - Linux-5.15.0-118-generic-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2, rtmpdump 2.4
[debug] Optional libraries: certifi-2024.08.30, mutagen-1.47.0, requests-2.32.3, sqlite3-3.37.2, urllib3-2.2.3
[debug] Proxy map: {'all': 'user88048:vm953z@194.93.3.148:7103'}
[debug] Request Handlers: urllib, requests
[debug] Loaded 1838 extractors
[youtube] Extracting URL: https://www.youtube.com/watch?v=UT94rXV_Vp4
[youtube] UT94rXV_Vp4: Downloading webpage
WARNING: [youtube] Unable to download webpage: HTTPSConnectionPool(host='www.youtube.com', port=443): Read timed out. (read timeout=20.0)
[youtube] UT94rXV_Vp4: Downloading ios player API JSON
WARNING: [youtube] HTTPSConnectionPool(host='www.youtube.com', port=443): Read timed out. (read timeout=20.0). Retrying (1/3)...
[youtube] UT94rXV_Vp4: Downloading ios player API JSON
```

**Comment by coletdjnz** [comment]
issue with your proxy most likely. 

check that your proxy is http, otherwise add the correct protocol to the proxy url (e.g. `socks5h://user88...` for socks5h)

**Comment by grqx** [comment]
http works fine for me though
<details><summary>logs</summary>


```log
[debug] Command-line config: ['https://www.youtube.com/watch?v=UT94rXV_Vp4', '--proxy=user88048:vm953z@194.93.3.148:7103', '-v', '--simulate']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.10.07 from yt-dlp/yt-dlp [1a176d874]
[debug] Lazy loading extractors is disabled
[debug] Python 3.13.0 (CPython x86_64 64bit) - Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2
[debug] Optional libraries: Cryptodome-3.21.0, brotli-1.1.0, certifi-2024.08.30, curl_cffi-0.7.1, mutagen-1.47.0, requests-2.32.3, secretstorage-3.3.3, sqlite3-3.37.2, urllib3-2.2.3, websockets-13.1
[debug] Proxy map: {'all': 'user88048:vm953z@194.93.3.148:7103'}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1843 extractors
[youtube] Extracting URL: https://www.youtube.com/watch?v=UT94rXV_Vp4
[youtube] UT94rXV_Vp4: Downloading webpage
[youtube] UT94rXV_Vp4: Downloading ios player API JSON
[youtube] UT94rXV_Vp4: Downloading mweb player API JSON
[debug] [youtube] Extracting signature function js_a8476471_104
[youtube] UT94rXV_Vp4: Downloading player a8476471
[debug] Saving youtube-sigfuncs.js_a8476471_104 to cache
[debug] Saving youtube-nsig.a8476471 to cache
[debug] [youtube] Decrypted nsig IIyfYjLUxqc3SCK => tvIXYVco3lxAkA
[debug] Loading youtube-nsig.a8476471 from cache
[debug] [youtube] Decrypted nsig QwFevGAwA1sq2IA => fT3GVqGczWUQDQ
[debug] [youtube] Extracting signature function js_a8476471_108
[debug] Saving youtube-sigfuncs.js_a8476471_108 to cache
[youtube] UT94rXV_Vp4: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] UT94rXV_Vp4: Downloading 1 format(s): 244+251
```

</details>
