### ISSUE TITLE
why does my windows goes to sleep while yt-dlp is downloading?

### ISSUE THREAD

**Issue by emilyexa** [yt-dlp/yt-dlp#11598]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I started yt-dlp on my windows 11 insider (dev) with -a argument to a txt file full of links and after a while when I came back pc was turned off because it went to sleep.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
PS C:\Users\mohse> yt-dlp -vU
[debug] Command-line config: ['-vU']
[debug] User config "C:\Users\mohse\AppData\Roaming\yt-dlp\config.txt": ['-o', 'E:\\\\YouTube\\\\%(playlist_title)s\\\\%(playlist_index)s %(title)s.%(ext)s', '-f', 'bv+ba[ext=m4a]/b', '-S', 'res:1080,fps', '-S', 'proto', '-S', '+codec:h264', '-N', '12', '--retries', 'infinite', '--fragment-retries', 'infinite', '--embed-thumbnail', '--embed-metadata', '--embed-info-json', '--embed-subs', '--sub-langs', 'en', '--default-search', 'ytsearch', '--external-downloader', 'aria2c', '--external-downloader-args', 'aria2c:-c -s 24 -j 24 -x 12 -k 1M -m 0', '--download-archive', 'E:\\\\YouTube\\\\download_archive.txt', '--merge-output-format', 'mkv', '--compat-options', 'embed-thumbnail-atomicparsley', '--xff', 'us']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version master@2024.11.18.053655 from yt-dlp/yt-dlp-master-builds [7ea278792] (win_exe)
[debug] Compatibility options: embed-thumbnail-atomicparsley
[debug] Python 3.10.11 (CPython AMD64 64bit) - Windows-10-10.0.26120-SP0 (OpenSSL 1.1.1t  7 Feb 2023)
[debug] exe versions: ffmpeg 7.1-essentials_build-www.gyan.dev (setts), ffprobe 7.1-essentials_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.21.0, brotli-1.1.0, certifi-2024.08.30, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.40.1, urllib3-2.2.3, websockets-13.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Extractor Plugins: GetPOT (YoutubeIE)
[debug] Plugin directories: ['C:\\Users\\mohse\\AppData\\Roaming\\yt-dlp\\plugins\\yt-dlp-get-pot.zip\\yt_dlp_plugins']
[debug] Loaded 1837 extractors
[debug] Loading archive file 'E:\\\\YouTube\\\\download_archive.txt'
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-master-builds/releases/latest
Latest version: master@2024.11.18.053655 from yt-dlp/yt-dlp-master-builds
yt-dlp is up to date (master@2024.11.18.053655 from yt-dlp/yt-dlp-master-builds)
```

**Comment by absidue** [comment]
Because you have set your computer to sleep after a while of inactivity, if you don't want your computer to do that, you should turn it off in the Windows settings.

**Comment by coletdjnz** [comment]
There is also this plugin to make yt-dlp not go to sleep https://github.com/Grub4K/yt-dont-lock-p

related https://github.com/yt-dlp/yt-dlp/issues/8935
