### ISSUE TITLE
how to disable `--format-sort` if use `--audio-quality`

### ISSUE THREAD

**Issue by candrapersada** [yt-dlp/yt-dlp#11599]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

how to automatically disable `--format-sort` if you want to download music using `-x --audio-format mp3 --audio-quality 5`?

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by seproDev** [comment]
I am not sure what you man by disabling `--format-sort`. Format sorting always happens.
If you pass `-x --audio-format mp3 --audio-quality 5` you are telling yt-dlp to convert the downloaded file to mp3 after the fact. yt-dlp still needs to download a audio track (either aac or opus for youtube) to convert in to mp3.

**Comment by candrapersada** [comment]
but what i mean is downloading with beat quality music without changing `--format-sort`
`--format-sort +res,+fps:20,+vbr,+abr,+size`

**Comment by seproDev** [comment]
If you want the best quality you should not convert to mp3. Conversion to mp3 is always lossy. The audio quality will always be worse than if you had downloaded the opus/aac track and didn't convert.

The defualt format sort value used by yt-dlp is `--format-sort lang,quality,res,fps,hdr:12,vcodec,channels,acodec,size,br,asr,proto,ext,hasaud,source,id`

**Comment by candrapersada** [comment]
how to automatically The default format sort value without changing `--format-sort` if using `--audio-quality` like `--no-format-sort-force`?

**Comment by seproDev** [comment]
Just don't pass `--format-sort`?
I'm having a really hard time understanding what you mean. Can you maybe explain in a bit more detail what you are trying to achieve?

**Comment by candrapersada** [comment]
> I'm guessing they have a config file with the format sort argument and want to ignore it when downloading audio?

yes

**Comment by bashonly** [comment]
You either need to pass a different `-S` arg to override what's in your config or pass `--ignore-config`. There's nothing else that can be done
