### ISSUE TITLE
Proxy mode for specific domains.

### ISSUE THREAD

**Issue by shell1986** [yt-dlp/yt-dlp#11604]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

It often happens that it is convenient to use a proxy only for specific sites. For example, if YouTube is blocked in your office, you need a proxy, but it is not needed for all other sites.
For example, my proxy can give a low speed, 10 times slower than my Internet. It is more logical to use a proxy on those sites where it is needed, and use a direct connection for all the others.

That is why I suggest making a list of domains for the proxy "*.youtube.com,facebook.com,pornhub.com" 😊
Thank you!

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by grqz** [comment]
related: #1191

**Comment by coletdjnz** [comment]
I would say this is the same as #1191, which we could implement as proxy per extractor. Anything more fine grained gets tricky.

Technically right now you can add an excludes list of domains with NO_PROXY env var.

Closing in favour of #1191
