### ISSUE TITLE
Is it possible to provide binaries compiled with Py2exe or provide documentation? [Question]

### ISSUE THREAD

**Issue by ahm750** [yt-dlp/yt-dlp#1160]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

Hi, binaries with Pyinstaller and --onefile command take a long time to launch when the binary is called via command line. Is it possible to provide binaries that have been built with Py2exe instead? If not, is there any documentation that you can provide on how to compile with py2exe?

**Comment by pukkandan** [comment]
With https://github.com/yt-dlp/yt-dlp/commit/5d535b4a559ff114866368bfb3cde38b54f9462b, you can now run `setup.py py2exe` to make a build.

But there will be no official releases with it for the foreseeable future, and I do not guarantee these builds will be fully functional
