### ISSUE TITLE
Steam community workshop [video] (with verbose this time sry for the last one)

### ISSUE THREAD

**Issue by pawfmrpimt** [yt-dlp/yt-dlp#11606]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a site-specific feature
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

japan

### Example URLs

https://steamcommunity.com/sharedfiles/filedetails/?id=3367449320

### Provide a description that is worded well enough to be understood

Export cookies of steam using cookie editor as netscape save as .txt use it to login cuz it said login with passwords not available.
what my command looked like: yt-dlp --cookies '/cookies.txt' -o "/%(extractor)s/%(artist,uploader,channel)s [%(id)s].%(ext)s" -vU 'https://steamcommunity.com/sharedfiles/filedetails/?id=3367449320'

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.11.04 from yt-dlp/yt-dlp [197d0b03b] (pip)
[debug] Python 3.12.4 (CPython arm64 64bit) - macOS-15.0.1-arm64-arm-64bit (OpenSSL 3.0.14 4 Jun 2024)
[debug] exe versions: ffmpeg 7.1 (setts), ffprobe 7.1
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.0.9, certifi-2024.08.30, mutagen-1.47.0, requests-2.32.3, sqlite3-3.45.3, urllib3-2.2.3, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Loaded 1838 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
[debug] Downloading _update_spec from https://github.com/yt-dlp/yt-dlp/releases/latest/download/_update_spec
Current version: stable@2024.11.04 from yt-dlp/yt-dlp
Latest version: stable@2024.11.18 from yt-dlp/yt-dlp
ERROR: You installed yt-dlp with pip or using the wheel from PyPi; Use that to update
[Steam] Extracting URL: https://steamcommunity.com/sharedfiles/filedetails/?id=3367449320
[Steam] 3367449320: Downloading webpage
ERROR: [Steam] Could not find any videos; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "#######/miniconda3/lib/python3.12/site-packages/yt_dlp/extractor/common.py", line 742, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "########/miniconda3/lib/python3.12/site-packages/yt_dlp/extractor/steam.py", line 122, in _real_extract
    raise ExtractorError('Could not find any videos')
```

**Comment by seproDev** [comment]
Thanks for providing a verbose log.
The URL in your log does not contain a video, only an animated gif. As such, it is out of scope to be downloaded by yt-dlp.

If you just want to save this image, you can right-click and select "Save image as...".

**Comment by seproDev** [comment]
Actually, my bad. Animated gifs are considered in scope.

**Comment by pawfmrpimt** [comment]
okay what about this one:https://steamcommunity.com/sharedfiles/filedetails/?id=3370229204 This one contain video I'm sure because i put the link through steam workshop downloader and the file size is about 62.9MB Theres a thing called steamcmd but i haven't tried yet

**Comment by pawfmrpimt** [comment]
okay I just using it now but the problem I have is that it doesn't have file name formatting and can't download multiple workshop items or games from the lists in txt files(someone solved it but doesn't tell how) which is the function yt-dlp have for the supported websites. you need game id and workshop id to download it also you must own the game.

**Comment by seproDev** [comment]
Ah, you want to download the actual steam workshop files, and not the preview embedded on the website.
SteamCMD is an official tool by Valve, we would need to reimplement the steam auth logic to be able to download files. I would also assume that most files are not videos, but mods/game files. Not sure how it works for Wallpaper Engine, if the files are just videos or if they are stored in some form of archive.

**Comment by bashonly** [comment]
If you want the actual workshop files instead of the animated gif preview, then this is indeed out-of-scope. yt-dlp is a video/audio downloader. It is not intended as an all-purpose downloader of data files or metadata.
