### ISSUE TITLE
filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

### ISSUE THREAD

**Issue by Upitoraon** [yt-dlp/yt-dlp#11603]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

`import yt_dlp
import os

# प्रोफाइल का उपयोगकर्ता नाम
profile_username = "naturefusiongallery"

# आउटपुट फोल्डर
output_folder = "/sdcard/FB-upload"

# अगर आउटपुट फोल्डर मौजूद नहीं है, तो इसे बनाएं
if not os.path.exists(output_folder):
    os.makedirs(output_folder)

# Session ID को कस्टम रूप से सेट करें
session_id = "57121688826%3AVtVpeffgEFGIox%3A18%3AAYdd9768Z4wJA5s7z31BwvHY4gESbO-9wIUSIUMUVg"

# yt-dlp के लिए ऑप्शंस
ydl_opts = {
    'format': 'bestvideo+bestaudio/best',  # उच्च गुणवत्ता में वीडियो डाउनलोड करें
    'merge_output_format': 'mp4',           # केवल MP4 फॉर्मेट में वीडियो सेव करें
    'outtmpl': os.path.join(output_folder, '%(title)s.%(ext)s'),  # वीडियो का नाम प्रोफाइल के कैप्शन पर आधारित
    'postprocessors': [{
        'key': 'FFmpegVideoConvertor',
        'preferedformat': 'mp4'           # आउटपुट फॉर्मेट MP4 रखें
    }],
    'cookiefile': None,  # Ensure that cookiefile is not used if using direct session ID
    'cookies': {
        'sessionid': session_id  # Directly using the session ID as a cookie
    }
}

# yt-dlp डाउनलोड प्रोसेस
try:
    # yt-dlp इंस्टाग्राम प्रोफाइल से वीडियो डाउनलोड करें
    with yt_dlp.YoutubeDL(ydl_opts) as ydl:
        ydl.download([f"https://www.instagram.com/{profile_username}"])
        print(f"Downloaded all videos from: {profile_username}")

except Exception as e:
    print(f"Failed to download videos: {e}")'

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
WARNING: The program functionality for this site has been marked as broken, and will probably not work.
[instagram:user] Extracting URL: https://www.instagram.com/naturefusiongallery
[instagram:user] naturefusiongallery: Downloading webpage
ERROR: [instagram:user] naturefusiongallery: Unable to extract data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Failed to download videos: ERROR: [instagram:user] naturefusiongallery: Unable to extract data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

**Comment by seproDev** [comment]
You will have to formulate some sort of question, so we can help you. What kind of response are you expecting by just posting code snippets and an incomplete log that tells you that Instagram user extraction is currently broken?
