### ISSUE TITLE
With this command line lower resolution?  -S vcodec:h264,res,acodec:aac

### ISSUE THREAD

**Issue by tormyvancool** [yt-dlp/yt-dlp#11601]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Why by giving this command line I don't get the full resolution .mp4 downloaded?

I tried with 4k video and it downloads 1920x1080 one

`yt-dlp -S vcodec:h264,res,acodec:aac <URL>` ?

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by seproDev** [comment]
Youtube does not provide 4k h264 video formats

**Comment by tormyvancool** [comment]
> Youtube does not provide 4k h264 video formats

what should I do to get the original resolution? and MP4?

**Comment by seproDev** [comment]
> Because when I try to download 1920x1080 video, they come down 640 x 320 which is not what I want.

You will need to show what you are doing with a verbose log.

Either way, if you just want a mp4 file, you can use `yt-dlp --merge-output-format mp4 "URL"`
Note that this will not download h264 video or aac audio, so the mp4 file might not be compatible with legacy software.

If you want a mp4 file with h264/avc video and a resolution higher than 1080p, you will need to transcode the video which is lossy and requires a lot of compute. I would recommend just downloading the highest quality video with `yt-dlp "URL"` in that case and using ffmpeg/x264 to transcode yourself.

**Comment by tormyvancool** [comment]
> > Because when I try to download 1920x1080 video, they come down 640 x 320 which is not what I want.
> 
> You will need to show what you are doing with a verbose log.
> 
> Either way, if you just want a mp4 file, you can use `yt-dlp --merge-output-format mp4 "URL"` Note that this will not download h264 video or aac audio, so the mp4 file might not be compatible with legacy software.
> 
> If you want a mp4 file with h264/avc video and a resolution higher than 1080p, you will need to transcode the video which is lossy and requires a lot of compute. I would recommend just downloading the highest quality video with `yt-dlp "URL"` in that case and using ffmpeg/x264 to transcode yourself.

That line 
`--merge-output-format mp4`

does the job.

Thank you a lot.
