### ISSUE TITLE
Video quality 4K is not available for YouTube live stream

### ISSUE THREAD

**Issue by freerss2** [yt-dlp/yt-dlp#11614]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a site-specific feature
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Israel

### Example URLs

https://www.youtube.com/watch?v=SnCEL_FnR-s

### Provide a description that is worded well enough to be understood

I'm trying to get a list of available formats from URL mentioned in example. 
While browser allows to select a 4K stream, the best selection that I get from command-line is:
mp4 1920x1080   60fps ...

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--list-formats', '-s', '--skip-download', 'https://www.youtube.com/watch?v=SnCEL_FnR-s']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.11.18 from yt-dlp/yt-dlp [7ea278792] (win_exe)
[debug] Python 3.10.11 (CPython AMD64 64bit) - Windows-10-10.0.22631-SP0 (OpenSSL 1.1.1t  7 Feb 2023)
[debug] exe versions: ffmpeg git-2019-10-18-feaec3b
[debug] Optional libraries: Cryptodome-3.21.0, brotli-1.1.0, certifi-2024.08.30, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.40.1, urllib3-2.2.3, websockets-13.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1837 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.11.18 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.11.18 from yt-dlp/yt-dlp)
[youtube] Extracting URL: https://www.youtube.com/watch?v=SnCEL_FnR-s
[youtube] SnCEL_FnR-s: Downloading webpage
[youtube] SnCEL_FnR-s: Downloading ios player API JSON
[youtube] SnCEL_FnR-s: Downloading mweb player API JSON
[youtube] SnCEL_FnR-s: Downloading m3u8 information
[youtube] SnCEL_FnR-s: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec, channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[info] Available formats for SnCEL_FnR-s:
ID  EXT RESOLUTION FPS │   TBR PROTO │ VCODEC        VBR ACODEC     MORE INFO
────────────────────────────────────────────────────────────────────────────────
233 mp4 audio only     │       m3u8  │ audio only        unknown    Default, IOS
234 mp4 audio only     │       m3u8  │ audio only        unknown    Default, IOS
269 mp4 256x144     15 │  290k m3u8  │ avc1.42C00B  290k video only IOS
91  mp4 256x144     15 │  290k m3u8  │ avc1.42c00b       mp4a.40.5  MWEB
229 mp4 426x240     30 │  546k m3u8  │ avc1.4D4015  546k video only IOS
92  mp4 426x240     30 │  546k m3u8  │ avc1.4d4015       mp4a.40.5  MWEB
230 mp4 640x360     30 │ 1210k m3u8  │ avc1.4D401E 1210k video only IOS
93  mp4 640x360     30 │ 1210k m3u8  │ avc1.4d401e       mp4a.40.2  MWEB
231 mp4 854x480     30 │ 1569k m3u8  │ avc1.4D401F 1569k video only IOS
94  mp4 854x480     30 │ 1569k m3u8  │ avc1.4d401f       mp4a.40.2  MWEB
311 mp4 1280x720    60 │ 4370k m3u8  │ avc1.4D4020 4370k video only IOS
300 mp4 1280x720    60 │ 4370k m3u8  │ avc1.4d4020       mp4a.40.2  MWEB
312 mp4 1920x1080   60 │ 7172k m3u8  │ avc1.64002A 7172k video only IOS
301 mp4 1920x1080   60 │ 7172k m3u8  │ avc1.64002a       mp4a.40.2  MWEB
[debug] Default format spec: best/bestvideo+bestaudio
[info] SnCEL_FnR-s: Downloading 1 format(s): 301
```

**Comment by bashonly** [comment]
https://github.com/yt-dlp/yt-dlp/issues/11262#issuecomment-2415919973

**Comment by seproDev** [comment]
Also keep in mind that you need to use `--live-from-start` as the m3u8 livestreams are only available up to 1080p.

**Comment by freerss2** [comment]
Thanks, after changing the client app and adding "--live-from-start" it worked like a charm.
Maybe this case should be referred in documentation for beginners (like me).
