### ISSUE TITLE
[VK] add domain vkvideo.ru

### ISSUE THREAD

**Issue by qzmtch** [yt-dlp/yt-dlp#11646]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a site-specific feature
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Example URLs

https://vkvideo.ru/video-127553155_456242961
https://live.vkvideo.ru/panterka

### Provide a description that is worded well enough to be understood

vk.com for me today, (for some people earlier) VK began to redirect to this domain vkvideo.ru when clicking on vk.com/video . And there are now links to videos with a different domain
also instead of live.vkplay.ru now live.vkvideo.ru
with the old video domain also available https://vk.com/video-127553155_456242961

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://vkvideo.ru/video-127553155_456242961']
[debug] Encodings: locale cp1251, fs utf-8, pref cp1251, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version master@2024.11.24.222048 from yt-dlp/yt-dlp-master-builds [4b5eec0aa] (win_exe)
[debug] Python 3.10.11 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1t  7 Feb 2023)
[debug] exe versions: ffmpeg N-116122-gd241edc2b4-20240703 (setts), ffprobe N-116122-gd241edc2b4-20240703, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.21.0, brotli-1.1.0, certifi-2024.08.30, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.40.1, urllib3-2.2.3, websockets-14.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1837 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-master-builds/releases/latest
Latest version: master@2024.11.24.222048 from yt-dlp/yt-dlp-master-builds
yt-dlp is up to date (master@2024.11.24.222048 from yt-dlp/yt-dlp-master-builds)
[generic] Extracting URL: https://vkvideo.ru/video-127553155_456242961
[generic] video-127553155_456242961: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] video-127553155_456242961: Extracting information
[debug] Looking for embeds
[debug] Identified a Open Graph video info
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec, channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] video_ext: Downloading 1 format(s): 0
ERROR: The extracted extension ('php') is unusual and will be skipped for safety reasons. If you believe this is an error, please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 177, in wrapper
  File "yt_dlp\YoutubeDL.py", line 3475, in process_info
  File "yt_dlp\YoutubeDL.py", line 3367, in existing_video_file
  File "yt_dlp\YoutubeDL.py", line 3366, in <lambda>
  File "yt_dlp\utils\_utils.py", line 2130, in _change_extension
  File "yt_dlp\utils\_utils.py", line 5212, in sanitize_extension
yt_dlp.utils._UnsafeExtensionError: unsafe file extension: 'php'
```

**Comment by sashk555** [comment]
the same problem. It would be great if you fix it.

**Example URLs**
[https://vkvideo.ru/@nsasvoemesto](url)
**Complete Verbose Output**

> d:\VK_NaSvoemMeste>rem d:\VK_NaSvoemMeste\yt-dlp.exe -J -vU --flat-playlist --no-cache-dir --ignore-config --user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36" --no-check-certificate --yes-playlist https://vkvideo.ru/@nsasvoemesto
> 
> d:\VK_NaSvoemMeste>d:\VK_NaSvoemMeste\yt-dlp.exe -vU https://vkvideo.ru/@nsasvoemesto
> [debug] Command-line config: ['-vU', 'https://vkvideo.ru/@nsasvoemesto']
> [debug] Encodings: locale cp1251, fs utf-8, pref cp1251, out utf-8, error utf-8, screen utf-8
> [debug] yt-dlp version stable@2024.11.18 from yt-dlp/yt-dlp [7ea278792] (win_exe)
> [debug] Python 3.10.11 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1t  7 Feb 2023)
> [debug] exe versions: ffmpeg 6.1.1-full_build-www.gyan.dev (setts), ffprobe 6.1.1-full_build-www.gyan.dev
> [debug] Optional libraries: Cryptodome-3.21.0, brotli-1.1.0, certifi-2024.08.30, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.40.1, urllib3-2.2.3, websockets-13.1
> [debug] Proxy map: {}
> [debug] Request Handlers: urllib, requests, websockets, curl_cffi
> [debug] Loaded 1837 extractors
> [debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
> Latest version: stable@2024.11.18 from yt-dlp/yt-dlp
> yt-dlp is up to date (stable@2024.11.18 from yt-dlp/yt-dlp)
> [generic] Extracting URL: https://vkvideo.ru/@nsasvoemesto
> [generic] @nsasvoemesto: Downloading webpage
> WARNING: [generic] Falling back on generic information extractor
> [generic] @nsasvoemesto: Extracting information
> [debug] Looking for embeds
> [redirect] Following redirect to https://vkvideo.ru/badbrowser.php
> [generic] Extracting URL: https://vkvideo.ru/badbrowser.php
> [generic] badbrowser: Downloading webpage
> WARNING: [generic] Falling back on generic information extractor
> [generic] badbrowser: Extracting information
> [debug] Looking for embeds
> ERROR: Unsupported URL: https://vkvideo.ru/badbrowser.php
> Traceback (most recent call last):
>   File "yt_dlp\YoutubeDL.py", line 1624, in wrapper
>   File "yt_dlp\YoutubeDL.py", line 1759, in __extract_info
>   File "yt_dlp\extractor\common.py", line 742, in extract
>   File "yt_dlp\extractor\generic.py", line 2553, in _real_extract
> yt_dlp.utils.UnsupportedError: Unsupported URL: https://vkvideo.ru/badbrowser.php

**Comment by nvrskRU** [comment]
I confirm the problem.
the code change and new domain addition has happened today.

one more URL example that also should be added/fixed:

https://vkvideo.ru/playlist/-218471730_-2/video-218471730_456239774

**Comment by zaeboba** [comment]
and live.vkvideo.ru

**Comment by zaeboba** [comment]
in the night assembly added, BUT with arguments does not want to download, says that cookies are not valid (I updated them), but if without any arguments insert a link, then will be downloaded 🤷‍♂️

**Comment by qzmtch** [comment]
> in the night assembly added, BUT with arguments does not want to download, says that cookies are not valid (I updated them), but if without any arguments insert a link, then will be downloaded 🤷‍♂️

nobody changed anything

**Comment by qzmtch** [comment]
> Backup original files before edit!
> 
> Temporarily you can find **vk.py** in **yt-dlp** folder. Change `vk.com` into `vkvideo.ru` and `vk\.com` into `vkvideo\.ru` You may need to edit file **lazy_extractors.py**

why replace if vk.com also works and will remain for videos in posts and vk groups?

**Comment by AutomationD** [comment]
> > Backup original files before edit!
> > Temporarily you can find **vk.py** in **yt-dlp** folder. Change `vk.com` into `vkvideo.ru` and `vk\.com` into `vkvideo\.ru` You may need to edit file **lazy_extractors.py**
> 
> why replace if vk.com also works and will remain for videos in posts and vk groups?

Yeah, it should be an addition for sure.
(but vkvideo format playlists don't seem to work)

**Comment by krasnh** [comment]
> "[VK] add domain vkvideo.ru"   qzmtch opened this issue Nov 26, 2024 

And the news was officially announced only today, December 4th. :)
[Платформа «VK Видео» запустила обновлённую веб-версию на отдельном домене vkvideo.ru](https://habr.com/ru/news/863666/)

**Comment by qzmtch** [comment]
> > "[VK] add domain vkvideo.ru"   qzmtch opened this issue Nov 26, 2024
> 
> And the news was officially announced only today, December 4th. :) [Платформа «VK Видео» запустила обновлённую веб-версию на отдельном домене vkvideo.ru](https://habr.com/ru/news/863666/)
seriously?
https://vk.com/vkvideo?w=wall-220754053_83366
https://vk.company/ru/press/releases/11917/

**Comment by qzmtch** [comment]
We need to add links to playlists
https://vkvideo.ru/playlist/-51890028_-2/video-51890028_456241268

**Comment by qzmtch** [comment]
https://vkvideo.ru/video-51890028_456241268
it works

**Comment by ivanioannovich** [comment]
how change endpoint in def _download_payload if url contain 'vkvideo'?

**Comment by bashonly** [comment]
@qzmtch @ivanioannovich could you each open new issues please? include examples and complete verbose output

**Comment by Astlaan** [comment]
As of now, I get this error:

```
> yt-dlp https://vkvideo.ru/video-20507050_456241553
[vk] Extracting URL: https://vkvideo.ru/video-20507050_456241553
[vk] -20507050_456241553: Downloading JSON metadata
ERROR: [vk] Unable to download JSON metadata: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1010) (caused by CertificateVerifyError('[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1010)')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

**Comment by krasnh** [comment]
>As of now, I get this error

I have the same mistake. However, if I log in to my vk account and then try to download it again, there is no error. 

Moreover, I have the string `--cookies-from-browser` in my config, but it looks like cookies become obsolete if you don't visit your account for a long time.

```sh
yt-dlp 'https://vkvideo.ru/video-20507050_456241553'
[vk] Extracting URL: https://vkvideo.ru/video-20507050_456241553
[vk] -20507050_456241553: Downloading JSON metadata
Extracting cookies from firefox
Extracted 2036 cookies from firefox
[vk] -20507050_456241553: Downloading MPD manifest
[vk] -20507050_456241553: Downloading MPD manifest
[vk] -20507050_456241553: Downloading m3u8 information
[SponsorBlock] SponsorBlock is not supported for VK
[info] -20507050_456241553: Downloading 1 format(s): url720
[download] Destination: Реактивное движение ⧸ 1978 ⧸ ЦентрНаучФильм [-20507050_456241553].mp4
[download]   1.4% of  287.87MiB at    2.06MiB/s ETA 02:17^C
```

**Comment by krasnh** [comment]
>I have the same mistake.

No, the errors don't match.

```sh
yt-dlp 'https://vkvideo.ru/video-20507050_456241553'
[vk] Extracting URL: https://vkvideo.ru/video-20507050_456241553
[vk] -20507050_456241553: Downloading JSON metadata
Extracting cookies from firefox
Extracted 2036 cookies from firefox
ERROR: [vk] This video is only available for registered users. Use --cookies, --cookies-from-browser, --username and --password, --netrc-cmd, or --netrc (vk) to provide account credentials. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies
```

**Comment by Astlaan** [comment]
Apparently I eventually made it work, by using `--no-check-certificate`..

However, I noticed that the following doesn't work
```
yt-dlp https://vkvideo.ru/CHANNEL/playlists
```

instead, I had to pass 

```
yt-dlp https://vkvideo.ru/CHANNEL
```

**Comment by bashonly** [comment]
open a new issue if you want any devs to actually look into whatever problem you're having
