### ISSUE TITLE
[YouTube] Is there a working player_client with cookie and don't use signatureCipher in response?

### ISSUE THREAD

**Issue by InfinityLoop1308** [yt-dlp/yt-dlp#11657]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Hi, PipePipe dev here.
Followed by #10128 , we use cookie with ios client to avoid the block, but it doesn't work now as #11640, so we are looking for a alternative. Problem is, mweb return signatureCipher instead of URL, which can't be parsed based on current code, so we have to look for an alternative client.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by qinfendezhou** [comment]
I attempted to parse signatureCipher by calling the base.js file from the YouTube website and successfully implemented resource playback. This method worked as recently as August of this year, but starting from November 21, the parsed resource links return a 403 error. I have yet to find a solution to this issue.
![Uploading 79827c56dc17a7a7bbb1138ae1c30900.png…]()

**Comment by coletdjnz** [comment]
YouTube is very quickly fixing their auth problem and stopping the likes of WEB cookies being used on other clients. Even if there are alternatives they are being patched pretty quickly and probably wont last very long.

I recommend looking at how to deal with WEB nsig as a starting point. Though you will need to consider what to do with PO Token once that becomes mandatory. I believe upstream NewPipe will be running into similar issues (if they don't already have workarounds).

(I recommend reaching out on our discord/matrix)

**Comment by InfinityLoop1308** [comment]
Yeah you are right, I think I will have to deal with ciphers in the end.

By the way, NewPipe is not our upstream - we haven't track them since day 1. They don't use accounts so I don't think the change will affect them.

**Comment by Elite** [comment]
@InfinityLoop1308 Can you pls. confirm that `WEB` formats using signature decipher like this https://github.com/iv-org/inv_sig_helper still works?

**Comment by InfinityLoop1308** [comment]
@Elite We decided to switch to alternative methods, so it is not needed. But thanks for your info.

**Comment by Elite** [comment]
@InfinityLoop1308 Can you share what worked for you?

**Comment by InfinityLoop1308** [comment]
@Elite Bundle yt-dlp into our app😄

**Comment by Elite** [comment]
@coletdjnz Can you pls confirm that using the `inv_sig_helper` with `WEB` client url's provide downloadable links?
