### ISSUE TITLE
[YouTube] Unable to download live chat from membership stream

### ISSUE THREAD

**Issue by kombomo** [yt-dlp/yt-dlp#11653]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [x] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Provide a description that is worded well enough to be understood

For upcoming public YouTube streams, I can can start downloading the live chat as soon as the stream URL is up and chat is enabled:
`yt-dlp.exe --no-download --ignore-no-formats-error --cookies-from-browser firefox::yt-dlp --write-subs
 --sub-langs live_chat https://www.youtube.com/watch?v=XXXXX`

When I run the same command for an upcoming members-only stream it seems to download data at first, but as soon as the fragment counter ticks up to 2, at around 1MiB transfered, it fails with "ERROR: The downloaded file is empty"

If I run the same command after the stream has started (or after it has ended), it works flawlessly.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [x] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp.exe -vU --no-download --ignore-no-formats-error --cookies-from-browser firefox::yt-dlp --write-subs --sub-langs live_chat https://www.youtube.com/watch?v=XXXXXXXX
[debug] Command-line config: ['-vU', '--no-download', '--ignore-no-formats-error', '--cookies-from-browser', 'firefox::yt-dlp', '--write-subs', '--sub-langs', 'live_chat', 'https://www.youtube.com/watch?v=XXXXXXXX']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.11.18 from yt-dlp/yt-dlp [7ea278792] (win_exe)
[debug] Python 3.10.11 (CPython AMD64 64bit) - Windows-10-10.0.22631-SP0 (OpenSSL 1.1.1t  7 Feb 2023)
[debug] exe versions: ffmpeg N-110125-g0684e58886-20230329 (setts), ffprobe N-110125-g0684e58886-20230329, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.21.0, brotli-1.1.0, certifi-2024.08.30, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.40.1, urllib3-2.2.3, websockets-13.1
[debug] Proxy map: {}
Extracting cookies from firefox
[debug] Extracting cookies from: "C:\Users\sillybilly\AppData\Roaming\Mozilla\Firefox\Profiles\rz17doal.default-release\cookies.sqlite"
[debug] Only loading cookies from firefox container "yt-dlp", ID 17
Extracted 19 cookies from firefox
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1837 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.11.18 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.11.18 from yt-dlp/yt-dlp)
[youtube] Extracting URL: https://www.youtube.com/watch?v=XXXXXXXX
[youtube] XXXXXXXX: Downloading webpage
[debug] [youtube] Extracted SAPISID cookie
[youtube] XXXXXXXX: Downloading ios player API JSON
WARNING: [youtube] YouTube said: ERROR - Request contains an invalid argument.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (1/3)...
[youtube] XXXXXXXX: Downloading ios player API JSON
WARNING: [youtube] YouTube said: ERROR - Request contains an invalid argument.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (2/3)...
[youtube] XXXXXXXX: Downloading ios player API JSON
WARNING: [youtube] YouTube said: ERROR - Request contains an invalid argument.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (3/3)...
[youtube] XXXXXXXX: Downloading ios player API JSON
WARNING: [youtube] YouTube said: ERROR - Request contains an invalid argument.
WARNING: [youtube] Unable to download API page: HTTP Error 400: Bad Request (caused by <HTTPError 400: Bad Request>)
[youtube] XXXXXXXX: Downloading mweb player API JSON
WARNING: [youtube] This live event will begin in 5 hours.
[info] XXXXXXXX: Downloading subtitles: live_chat
WARNING: No video formats found!
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec, channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
WARNING: Requested format is not available
[info] Writing video subtitles to: YYYYYYYYYYYY [XXXXXXXX].live_chat.json
[debug] Invoking youtube_live_chat downloader on "https://www.youtube.com/watch?v=XXXXXXXX&bpctr=9999999999&has_verified=1"
[youtube_live_chat] Downloading live chat
[youtube_live_chat] Total fragments: unknown (live)
[download] Destination: YYYYYYYYYYYY [XXXXXXXX].live_chat.json
[debug] File locking is not supported. Proceeding without locking
[download]    1.08MiB at  790.24KiB/s (00:00:02) (frag 2)ERROR: The downloaded file is empty
  File "yt_dlp\__main__.py", line 17, in <module>
  File "yt_dlp\__init__.py", line 1093, in main
  File "yt_dlp\__init__.py", line 1083, in _real_main
  File "yt_dlp\YoutubeDL.py", line 3604, in download
  File "yt_dlp\YoutubeDL.py", line 3577, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1613, in extract_info
  File "yt_dlp\YoutubeDL.py", line 1624, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1780, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1839, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 3010, in process_video_result
  File "yt_dlp\YoutubeDL.py", line 177, in wrapper
  File "yt_dlp\YoutubeDL.py", line 3266, in process_info
  File "yt_dlp\YoutubeDL.py", line 4350, in _write_subtitles
  File "yt_dlp\YoutubeDL.py", line 3198, in dl
  File "yt_dlp\downloader\common.py", line 464, in download
  File "yt_dlp\downloader\youtube_live_chat.py", line 192, in real_download
  File "yt_dlp\downloader\fragment.py", line 300, in _finish_frag_download
  File "yt_dlp\YoutubeDL.py", line 1090, in report_error
  File "yt_dlp\YoutubeDL.py", line 1018, in trouble
```

**Comment by kombomo** [comment]
Sorry, it now turns out it doesn't work after the stream has started either - same behavior, same stacktrace. I'm sure it worked until recently but it's hard to tell for certain since I have no way of setting up members-only streams for testing myself...

**Comment by bashonly** [comment]
seems like this has been going on for a while: #11454

**Comment by kombomo** [comment]
> seems like this has been going on for a while: #11454

I saw that one, but wasn't sure if it was relevant - I have no problems downloading live chat replay from members-only VODs, only live streams (double-checked just now). I'd prefer to be able to start recording messages in advance, since messages from before the stream started aren't included in the live chat replay.

**Comment by kombomo** [comment]
This seems to have been a problem with my YouTube session/cookies - after a while I stopped being able to access members-only content completely, and when I checked on the Firefox container I use for yt-dlp I was completely logged out. After logging in again I have been able to record live chat, including pre-chat, in multiple members-only streams without problems.
