### ISSUE TITLE
[Youtube] Provide link to Album Artwork

### ISSUE THREAD

**Issue by Batwam** [yt-dlp/yt-dlp#11660]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a site-specific feature
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Example URLs

https://music.youtube.com/playlist?list=OLAK5uy_mre2DKP3bVu0mUf-LI9FFWNw3xTttYCZA

### Provide a description that is worded well enough to be understood

I am looking to get the url of the artwork for a given playlist. When I download the playlist informations using `yt-dlp --flat-playlist --print-json https://music.youtube.com/playlist?list=OLAK5uy_mre2DKP3bVu0mUf-LI9FFWNw3xTttYCZA | jq .thumbnails` , I only appear to get thumbnail urls from i.ytimg.com like [this](https://i.ytimg.com/vi/QSCJtrFxASw/hqdefault.jpg) 480x360 with some very large borders top/bottom and left/right.

However, if I inspect the content of the webpage, I can get a much higher resolution picture (544x544) which is stored under lh3.googleusercontent.com:
`curl -s "https://music.youtube.com/playlist?list=OLAK5uy_mre2DKP3bVu0mUf-LI9FFWNw3xTttYCZA" | sed 's/</\n</g' | grep og:image`

Is there a way to get this googleusercontent.com url information from yt-dlp?

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
<meta property="og:image" content="https://lh3.googleusercontent.com/iMUT2Fzl_u6YdoPLL--GLhKRa-GrAagIcT_sO3DHQ6FFMuA8Z1v1LOOOvQhBkkAkLk3rkLen8tVtH14T=w544-h544-s-l90-rj">
<meta property="og:image:width" content="544">
<meta property="og:image:height" content="544">
```

**Comment by bashonly** [comment]
there is a 640x640 thumbnail available at the playlist level

```
yt-dlp -I0 --print "playlist:%(thumbnails)j" "https://music.youtube.com/playlist?list=OLAK5uy_mre2DKP3bVu0mUf-LI9FFWNw3xTttYCZA" | jq
```

```json
[
  {
    "url": "https://i9.ytimg.com/s_p/OLAK5uy_mre2DKP3bVu0mUf-LI9FFWNw3xTttYCZA/mqdefault.jpg?sqp=CMzznLoGir7X7AMICNG_lLoGEAE=&rs=AOn4CLA5VO2eL_jALoPs3DILTCoifNT6ng&v=1732583377",
    "height": 180,
    "width": 180,
    "id": "0",
    "resolution": "180x180"
  },
  {
    "url": "https://i9.ytimg.com/s_p/OLAK5uy_mre2DKP3bVu0mUf-LI9FFWNw3xTttYCZA/sddefault.jpg?sqp=CMzznLoGir7X7AMICNG_lLoGEAE=&rs=AOn4CLBIfTT2Amsq2bVhW8awodf7w6l-lw&v=1732583377",
    "height": 640,
    "width": 640,
    "id": "1",
    "resolution": "640x640"
  },
  {
    "url": "https://i9.ytimg.com/s_p/OLAK5uy_mre2DKP3bVu0mUf-LI9FFWNw3xTttYCZA/maxresdefault.jpg",
    "height": 1200,
    "width": 1200,
    "id": "2",
    "resolution": "1200x1200"
  }
]
```

**Comment by Batwam** [comment]
This looks exercise like what I need, thanks!

So this isn't included in the default output when running `yt-dlp --flat-playlist --print-json` right? Is there any option to be added to the above command to exclude the extra sizes? I can definitely run the extra command but if I can bundle everything together that would be neater (I'm extracting other info with jq like artist, year,...)

**Comment by Batwam** [comment]
@bashonly would you have a list of metadata we can extract with this method? I see that `id` and `url` work, however, I'm looking for the album/playlist year, duration and artist picture, all of which are available in the page's source html code.

**Comment by bashonly** [comment]
@Batwam Most of that is not possible; see #622

**Comment by Batwam** [comment]
This is very relevant indeed. Didn't realise that the info is only in music.youtube.com and not www.youtube.com. This makes more sense then.

I guess I'll keep scraping the data manually using curl then.
