### ISSUE TITLE
Recode the video to h264 from VP09

### ISSUE THREAD

**Issue by charliezxy** [yt-dlp/yt-dlp#11668]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Hello,

When using --list-formats for fb video, all formats are shown in vp09

![image](https://github.com/user-attachments/assets/b6092407-ab27-4fdb-8bde-f79f403e255f)

In this case, is it still possible to --recode the video in h264 in mp4 container directly from yt-dlp download? Is there any way, we can get h264 directly from yt-dlp in such cases where it shows only vp09 and thus bypassing the need to encode it again to h264 by ffmpeg (which is an intensive task, especially if the video is 30 minute plus).

or the only option is to encode into h264 with ffmpeg after downloading, but that is a very time intensive task. I get speed of 8x when encoding with this command:

$ffmpegpath -i $downloadlocation \
-c:v libx264 -preset superfast -profile:v high -level 4.1 -b:v 3550k -movflags +faststart $outpathpath

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
Please always share full verbose output AS TEXT, not incomplete SCREENSHOTS

I don't even have a URL to copy/paste so I can reproduce the issue, test solutions/workarounds, etc

What you can do is pass a Firefox `--user-agent` string to yt-dlp to get h264 formats. You'll have to find that yourself; you didn't make things easy for me so I will not make them easy for you

**Comment by charliezxy** [comment]
I understand. Below are the verbose and 2 examples to try. 
In example 1, all formats and resolutions are available in av1 
In example 2, all formats and resolutions are available in vp09 

And yes, I passed user agent too

I was thinking if there is any way to find and download h264 formats without needing to convert with ffmpeg later. I gave you 2 examples of facebook reels and reels are short. But if the video is 30 minute plus long, then ffmpeg can take a lot of time. That's why I was thinking if there is any way to get the h264 stream directly.

Below are the examples:

Example 1 : AVAILABLE FORMAT - AV01 FORMAT ONLY - TEST LINK - https://www.facebook.com/reel/901359768637125

root@myproject:~# /home/cloudproject/htdocs/website/yt-dlp --list-formats --add-header "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36" --verbose "https://www.facebook.com/reel/901359768637125"
[debug] Command-line config: ['--list-formats', '--add-header', 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36', '--verbose', 'https://www.facebook.com/reel/901359768637125']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version master@2024.10.28.110905 from yt-dlp/yt-dlp-master-builds [f101e5d34] (zip)
[debug] Python 3.12.3 (CPython x86_64 64bit) - Linux-6.8.0-49-generic-x86_64-with-glibc2.39 (OpenSSL 3.0.13 30 Jan 2024, glibc 2.39)
[debug] exe versions: none
[debug] Optional libraries: certifi-2023.11.17, requests-2.31.0, sqlite3-3.45.1, urllib3-2.0.7
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Loaded 1837 extractors
[facebook:reel] Extracting URL: https://www.facebook.com/reel/901359768637125
[facebook] Extracting URL: https://m.facebook.com/watch/?v=901359768637125&_rdr
[facebook] 901359768637125: Downloading webpage
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[info] Available formats for 901359768637125:
ID                EXT RESOLUTION │   FILESIZE   TBR PROTO │ VCODEC          VBR ACODEC     ABR ASR MORE INFO
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
548015101550069a  m4a audio only │ ~454.66KiB   80k https │ audio only          mp4a.40.5  80k 48k DASH audio, m4a_dash
sd                mp4 unknown    │                  https │ unknown             unknown
hd                mp4 unknown    │                  https │ unknown             unknown
435770889388103v  mp4 720x1280   │ ~  1.89MiB  342k https │ av01.0.05M.08  342k video only         DASH video, mp4_dash
886549083632511v  mp4 720x1280   │ ~  4.69MiB  849k https │ av01.0.05M.08  849k video only         DASH video, mp4_dash
8833681036699331v mp4 720x1280   │ ~  6.41MiB 1161k https │ av01.0.05M.08 1161k video only         DASH video, mp4_dash
1110743124187626v mp4 720x1280   │ ~  8.19MiB 1483k https │ av01.0.05M.08 1483k video only         DASH video, mp4_dash
1122592449486384v mp4 720x1280   │ ~ 10.49MiB 1899k https │ av01.0.05M.08 1899k video only         DASH video, mp4_dash
994167125852088v  mp4 720x1280   │ ~ 14.18MiB 2566k https │ av01.0.05M.08 2566k video only         DASH video, mp4_dash
1957100738130676v mp4 1080x1920  │ ~ 18.68MiB 3382k https │ av01.0.08M.08 3382k video only         DASH video, mp4_dash
573977305042089v  mp4 2160x3840  │ ~ 24.48MiB 4433k https │ av01.0.12M.08 4433k video only         DASH video, mp4_dash


==================
==================
=================


Example 2 : AVAILABLE FORMAT - VP09 FORMAT ONLY -  TEST LINK - https://www.facebook.com/reel/559260123368837

root@myproject:~# /home/cloudproject/htdocs/website/yt-dlp --list-formats --add-header "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36" --verbose "https://www.facebook.com/reel/559260123368837"
[debug] Command-line config: ['--list-formats', '--add-header', 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36', '--verbose', 'https://www.facebook.com/reel/559260123368837']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version master@2024.10.28.110905 from yt-dlp/yt-dlp-master-builds [f101e5d34] (zip)
[debug] Python 3.12.3 (CPython x86_64 64bit) - Linux-6.8.0-49-generic-x86_64-with-glibc2.39 (OpenSSL 3.0.13 30 Jan 2024, glibc 2.39)
[debug] exe versions: none
[debug] Optional libraries: certifi-2023.11.17, requests-2.31.0, sqlite3-3.45.1, urllib3-2.0.7
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Loaded 1837 extractors
[facebook:reel] Extracting URL: https://www.facebook.com/reel/559260123368837
[facebook] Extracting URL: https://m.facebook.com/watch/?v=559260123368837&_rdr
[facebook] 559260123368837: Downloading webpage
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[info] Available formats for 559260123368837:
ID                EXT RESOLUTION │   FILESIZE   TBR PROTO │ VCODEC          VBR ACODEC     ABR ASR MORE INFO
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
887923809754579a  m4a audio only │ ~ 60.78KiB   50k https │ audio only          mp4a.40.5  50k 44k DASH audio, m4a_dash
sd                mp4 unknown    │                  https │ unknown             unknown
hd                mp4 unknown    │                  https │ unknown             unknown
454258474361572v  mp4 720x1280   │ ~183.91KiB  151k https │ vp09.00.31.08  151k video only         DASH video, mp4_dash
559532510363677v  mp4 720x1280   │ ~324.39KiB  267k https │ vp09.00.31.08  267k video only         DASH video, mp4_dash
473175651895336v  mp4 720x1280   │ ~466.38KiB  383k https │ vp09.00.31.08  383k video only         DASH video, mp4_dash
1519050408876672v mp4 720x1280   │ ~659.77KiB  542k https │ vp09.00.31.08  542k video only         DASH video, mp4_dash
581762877873902v  mp4 720x1280   │ ~883.34KiB  726k https │ vp09.00.31.08  726k video only         DASH video, mp4_dash
603164665463049v  mp4 720x1280   │ ~  1.12MiB  945k https │ vp09.00.31.08  945k video only         DASH video, mp4_dash
1865315847208992v mp4 1080x1920  │ ~  1.68MiB 1413k https │ vp09.00.40.08 1413k video only         DASH video, mp4_dash
1501315310579375v mp4 1080x1920  │ ~  2.29MiB 1929k https │ vp09.00.40.08 1929k video only         DASH video, mp4_dash

**Comment by bashonly** [comment]
That's not a Firefox user-agent, but I just tried it with one (`Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:128.0) Gecko/20100101 Firefox/128.0`), and it made no diffference for the 1st link and only yielded av01 instead of vp9 for the 2nd link. I guess the user-agent workaround no longer works

**Comment by bashonly** [comment]
There's really not a good built-in way to re-encode to h264 if the format downloaded is already in an mp4 container, because the `--recode-video` option was foolishly designed to take a container argument instead of a codec argument. You'll need to use an `--exec` ffmpeg line (use `%(filepath)q`)

**Comment by charliezxy** [comment]
So you mean that if the video is not available in h264, then there is no other way to download it and then encode it with ffmpeg either using exec or proc commands and then serve it. Right?

**Comment by dirkf** [comment]
Isn't it possible to use _ffmpeg_ as downloader and specify a conversion to be applied at the same time? Or to specify a conversion arg to the Merger PP?

... even without implementing the _ffmpeg_ combining issue(/PR?) that I somehow can't find now.

**Comment by charliezxy** [comment]
Yes, I understand that @bashonly Good day

@dirkf, why would you want to download with ffmpeg? Is it resource efficient or faster?

**Comment by dirkf** [comment]
It could be if you're going to transcode anyway. Or, doesn't `--recode-video mp4` force what you want (when the site offers no h.264)?

**Comment by bashonly** [comment]
> Isn't it possible to use ffmpeg as downloader and specify a conversion to be applied at the same time? 

Since the formats are separate video and audio, not sure if it's possible to pass downloader args for one format but not the other

> Or, doesn't `--recode-video mp4` force what you want (when the site offers no h.264)?

`--recode mp4` is a no-op if the downloaded format is already in an mp4 container (which facebook's vp9/av01 formats are)

**Comment by dirkf** [comment]
So let's pass the conversion args as _ffmpeg_ output args to the MergerPP (wow, that's some funky syntax):
```console
$ yt-dlp -v --postprocessor-args 'Merger+ffmpeg_o1:-vcodec h264' 'https://www.facebook.com/reel/559260123368837'
[debug] Command-line config: ['-v', '--postprocessor-args', 'Merger+ffmpeg_o1:-vcodec h264', 'https://www.facebook.com/reel/559260123368837']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.11.18 from yt-dlp/yt-dlp [7ea278792] (zip)
[debug] Python 3.11.2 (CPython i686 32bit) - Linux-6.1.0-27-686-pae-i686-with-glibc2.36 (OpenSSL 3.0.15 3 Sep 2024, glibc 2.36)
[debug] exe versions: ffmpeg 5.1.6-0 (setts), ffprobe 5.1.6-0
[debug] Optional libraries: Cryptodome-3.11.0, certifi-2022.09.24, requests-2.28.1, sqlite3-3.40.1, urllib3-1.26.12
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Loaded 1837 extractors
[facebook:reel] Extracting URL: https://www.facebook.com/reel/559260123368837
[facebook] Extracting URL: https://m.facebook.com/watch/?v=559260123368837&_rdr
[facebook] 559260123368837: Downloading webpage
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec, channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 559260123368837: Downloading 1 format(s): 1501315310579375v+887923809754579a
[debug] Invoking http downloader on "https://video.flhr10-1.fna.fbcdn.net/v/t39.25447-2/467999492_1073310144263073_1837701230774859749_n.mp4?_nc_cat=109&ccb=1-7&_nc_sid=9a5d50&efg=eyJ2ZW5jb2RlX3RhZyI6ImRhc2hfcjJldmV2cDktcjFnZW4ydnA5LWhmcl9xOTAiLCJ2aWRlb19pZCI6NTU5MjYwMTIzMzY4ODM3fQ==&_nc_e2o=559260123368837&_nc_ohc=_2_MTziGlEoQ7kNvgHWg1Yl&_nc_zt=28&_nc_ht=video.flhr10-1.fna&_nc_gid=A05nEIOGDrHn2eJP2WEY2E8&oh=00_AYBEzTu_1mZFMLKHHFvC5mujG2ftYA3slgzPVFrR7HFgjA&oe=674FF109"
[download] Destination: 2.2M views · 23K reactions ｜ Crunchy High Protein Chips 😋🔥 ｜ Keto Snackz [559260123368837].f1501315310579375v.mp4
[download] 100% of    2.29MiB in 00:00:02 at 1.12MiB/s
[debug] Invoking http downloader on "https://video.flhr10-2.fna.fbcdn.net/v/t58.16807-2/459938024_1241632397055336_6708966974524931067_n.mp4?_nc_cat=111&ccb=1-7&_nc_sid=9a5d50&efg=eyJ2ZW5jb2RlX3RhZyI6ImRhc2hfYXVkaW9fYWFjcF80OF9mcmFnXzJfYXVkaW8iLCJ2aWRlb19pZCI6NTU5MjYwMTIzMzY4ODM3fQ==&_nc_e2o=559260123368837&_nc_ohc=_xN51yTIvaMQ7kNvgF3luTG&_nc_zt=28&_nc_ht=video.flhr10-2.fna&_nc_gid=A05nEIOGDrHn2eJP2WEY2E8&oh=00_AYCYEMgoQozrEkX8cMrIaGbltQpBNElIBCCIQhzIoDmnog&oe=675004CA"
[download] Destination: 2.2M views · 23K reactions ｜ Crunchy High Protein Chips 😋🔥 ｜ Keto Snackz [559260123368837].f887923809754579a.m4a
[download] 100% of   61.59KiB in 00:00:00 at 352.19KiB/s
[Merger] Merging formats into "2.2M views · 23K reactions ｜ Crunchy High Protein Chips 😋🔥 ｜ Keto Snackz [559260123368837].mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:2.2M views · 23K reactions ｜ Crunchy High Protein Chips 😋🔥 ｜ Keto Snackz [559260123368837].f1501315310579375v.mp4' -i 'file:2.2M views · 23K reactions ｜ Crunchy High Protein Chips 😋🔥 ｜ Keto Snackz [559260123368837].f887923809754579a.m4a' -c copy -map 0:v:0 -map 1:a:0 -movflags +faststart -vcodec h264 'file:2.2M views · 23K reactions ｜ Crunchy High Protein Chips 😋🔥 ｜ Keto Snackz [559260123368837].temp.mp4'
Deleting original file 2.2M views · 23K reactions ｜ Crunchy High Protein Chips 😋🔥 ｜ Keto Snackz [559260123368837].f1501315310579375v.mp4 (pass -k to keep)
Deleting original file 2.2M views · 23K reactions ｜ Crunchy High Protein Chips 😋🔥 ｜ Keto Snackz [559260123368837].f887923809754579a.m4a (pass -k to keep)
$ ffprobe -hide_banner -show_format -print_format csv 2.2M\ views\ ·\ 23K\ reactions\ ｜\ Crunchy\ High\ Protein\ Chips\ 😋🔥\ ｜\ Keto\ Snackz\ \[559260123368837\].mp4 
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '2.2M views · 23K reactions ｜ Crunchy High Protein Chips 😋🔥 ｜ Keto Snackz [559260123368837].mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf59.27.100
  Duration: 00:00:10.08, start: 0.000000, bitrate: 3556 kb/s
  Stream #0:0[0x1](und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709, progressive), 1080x1920, 3538 kb/s, 60 fps, 60 tbr, 15360 tbn (default)
    Metadata:
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
      encoder         : Lavc59.37.100 libx264
  Stream #0:1[0x2](und): Audio: aac (HE-AAC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 48 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
      vendor_id       : [0][0][0][0]
format,2.2M views · 23K reactions ｜ Crunchy High Protein Chips 😋🔥 ｜ Keto Snackz [559260123368837].mp4,2,0,"mov,mp4,m4a,3gp,3g2,mj2",QuickTime / MOV,0.000000,10.078000,4480600,3556737,100,isom,512,isomiso2avc1mp41,Lavf59.27.100
```
Bingo! Previous logs reveal the secret knowledge that Merger specifies `-c copy ...`; as the user-specified output arguments are inserted before the output filename, `-vcodec h264` overrides the default `copy` codec.

This seems a bit lucky and likely to be broken in future, so maybe a more formal solution should be considered.

With `--recode-video ...`, the option value specifies a certain required container type, with whatever required media conversion, and there isn't a way to be more specific.

For cases like this the option syntax might be extended to specify, optionally, a required codec, compatible with the specified container by `ext`, say a semicolon-separated string of `type:codec` where `type can be one of `a`, `v`, `s` and `codec` is a name as defined in `ffmpeg -encoders` for that `type`. In this case `--recode-video mp4;v:h264` would be wanted.

A wild-card `ext`, meaning "the expected container ext" might also be supported, say `@` (character that is generally not significant to a shell and also not used in codec names, or `*` or `any`) when specifying a codec: then `--recode-video @;v:h264`.

**Comment by bashonly** [comment]
Discussion about or proposals for improving the `--recode` option should be continued in #7607

**Comment by dirkf** [comment]
> ... not sure if it's possible to pass downloader args for one format but not the other

Actually, it doesn't matter when the arg is just `-vcodec h264`. As in the Merger PP, it overrides an existing default `-c ...` option, but since the `-v` semantics is forwarded into the _ffmpeg_ download options (it isn't for PP) you get a message about the override:
```
$ yt-dlp -v --external-downloader ffmpeg --external-downloader-args 'ffmpeg:-vcodec h264' 'https://www.facebook.com/reel/559260123368837'
...
[debug] Invoking ffmpeg downloader on ...
...
Multiple -c, -codec, -acodec, -vcodec, -scodec or -dcodec options specified for stream 0, only the last option '-c:v h264' will be used.
...
$ gh\ Protein\ Chips\ 😋🔥\ ｜\ Keto\ Snackz\ \[559260123368837\].mp4 
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '2.4M views · 26K reactions ｜ Crunchy High Protein Chips 😋🔥 ｜ Keto Snackz [559260123368837].mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf59.27.100
  Duration: 00:00:10.08, start: 0.000000, bitrate: 3556 kb/s
  Stream #0:0[0x1](und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709, progressive), 1080x1920, 3538 kb/s, 60 fps, 60 tbr, 15360 tbn (default)
    Metadata:
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
      encoder         : Lavc59.37.100 libx264
  Stream #0:1[0x2](und): Audio: aac (HE-AAC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 48 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
      vendor_id       : [0][0][0][0]
format,2.4M views · 26K reactions ｜ Crunchy High Protein Chips 😋🔥 ｜ Keto Snackz [559260123368837].mp4,2,0,"mov,mp4,m4a,3gp,3g2,mj2",QuickTime / MOV,0.000000,10.078000,4480600,3556737,100,isom,512,isomiso2avc1mp41,Lavf59.27.100
$
```
As 3k more people have reacted to the page and ~197k more either tried this download or viewed the page, the title of the video now begins `2.4M ...`.
