### ISSUE TITLE
Error: Sign in to confirm your age, but --cookies don't work

### ISSUE THREAD

**Issue by madixi** [yt-dlp/yt-dlp#11672]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Russia

### Provide a description that is worded well enough to be understood

I try to download video. I've signed in and exported cookies from browser.
But I get error message "Sign in to confirm your age. This video may be inappropriate for some users."

Every time, when I try to open this video in browser I see:

> This video may be inappropriate for some users.
> I understand and wish to proceed

Only if I click on the button I can see video

Restricted mode is disabled.
![Screenshot from 2024-11-28 23-28-53](https://github.com/user-attachments/assets/659448bc-a73f-4ef7-94db-65484bb7711c)
![Screenshot from 2024-11-28 23-28-36](https://github.com/user-attachments/assets/1d3884fe-9e74-4d17-812d-4c63b65a2fbb)

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
$ yt-dlp -vU --cookies cookies.txt https://www.youtube.com/watch?v=c452gV8u8fw
[debug] Command-line config: ['-vU', '--cookies', 'cookies.txt', 'https://www.youtube.com/watch?v=c452gV8u8fw']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.11.27.232921 from yt-dlp/yt-dlp-nightly-builds [00dcde728] (pip)
[debug] Python 3.10.12 (CPython x86_64 64bit) - Linux-5.15.0-126-generic-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2
[debug] Optional libraries: Cryptodome-3.21.0, brotli-1.1.0, certifi-2020.06.20, mutagen-1.45.1, requests-2.32.3, secretstorage-3.3.1, sqlite3-3.37.2, urllib3-2.2.2, websockets-13.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1837 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.11.27.232921 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.11.27.232921 from yt-dlp/yt-dlp-nightly-builds)
[youtube] Extracting URL: https://www.youtube.com/watch?v=c452gV8u8fw
[youtube] c452gV8u8fw: Downloading webpage
[youtube] c452gV8u8fw: Downloading ios player API JSON
[youtube] c452gV8u8fw: Downloading mweb player API JSON
ERROR: [youtube] c452gV8u8fw: Sign in to confirm your age. This video may be inappropriate for some users. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies
  File "/home/dimon/.local/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 742, in extract
    ie_result = self._real_extract(url)
  File "/home/dimon/.local/lib/python3.10/site-packages/yt_dlp/extractor/youtube.py", line 4465, in _real_extract
    self.raise_no_formats(reason, expected=True)
  File "/home/dimon/.local/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 1276, in raise_no_formats
    raise ExtractorError(msg, expected=expected, video_id=video_id)
```

**Comment by bashonly** [comment]
Did you follow [this guide](https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies)? (the link is in the error message)

yt-dlp isn't finding valid logged-in yt cookies in your cookies.txt

**Comment by madixi** [comment]
> Did you follow [this guide](https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies)? (the link is in the error message)
> 
> yt-dlp isn't finding valid logged-in yt cookies in your cookies.txt

I did it by this instruction https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp
![Screenshot](https://github.com/user-attachments/assets/5bde0730-8feb-425b-aa5e-e4697143b7ba)

**Comment by bashonly** [comment]
Ok, but you also need to follow the Youtube-specific guide that I linked, or else your exported cookies will be invalidated by Youtube

**Comment by madixi** [comment]
> Ok, but you also need to follow the Youtube-specific guide that I linked, or else your exported cookies will be invalidated by Youtube

OK, I did it again by this instruction https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies

1. I installed new Google Chrome
2. I cleared the cookies, history and any data that may have been stored.
4. I opened new private tab, opened youtube in the tab and logged in.
6. I confirmed two-factor authentication on my phone. Maybe it's important.
7. I opened a new private tab and closed youtube tab.
8. I called in terminal:
   yt-dlp -vU --cookies-from-browser chrome --cookies cookies.txt https://www.youtube.com/watch?v=c452gV8u8fw
I see:
`$ yt-dlp -vU --cookies-from-browser chrome --cookies cookies.txt https://www.youtube.com/watch?v=c452gV8u8fw
[debug] Command-line config: ['-vU', '--cookies-from-browser', 'chrome', '--cookies', 'cookies.txt', 'https://www.youtube.com/watch?v=c452gV8u8fw']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.11.27.232921 from yt-dlp/yt-dlp-nightly-builds [00dcde728] (pip)
[debug] Python 3.10.12 (CPython x86_64 64bit) - Linux-5.15.0-126-generic-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2
[debug] Optional libraries: Cryptodome-3.21.0, brotli-1.1.0, certifi-2020.06.20, mutagen-1.45.1, requests-2.32.3, secretstorage-3.3.1, sqlite3-3.37.2, urllib3-2.2.2, websockets-13.1
[debug] Proxy map: {}
Extracting cookies from chrome
[debug] Extracting cookies from: "/home/dimon/.config/google-chrome/Default/Cookies"
[Cookies] Loading cookie      0/     2[debug] detected desktop environment: GNOME
[debug] Chosen keyring: GNOMEKEYRING
Extracted 2 cookies from chrome
[debug] cookie version breakdown: {'v10': 0, 'v11': 2, 'other': 0, 'unencrypted': 0}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1837 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.11.27.232921 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.11.27.232921 from yt-dlp/yt-dlp-nightly-builds)
[youtube] Extracting URL: https://www.youtube.com/watch?v=c452gV8u8fw
[youtube] c452gV8u8fw: Downloading webpage
[youtube] c452gV8u8fw: Downloading ios player API JSON
[youtube] c452gV8u8fw: Downloading mweb player API JSON
ERROR: [youtube] c452gV8u8fw: Sign in to confirm your age. This video may be inappropriate for some users. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies
  File "/home/dimon/.local/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 742, in extract
    ie_result = self._real_extract(url)
  File "/home/dimon/.local/lib/python3.10/site-packages/yt_dlp/extractor/youtube.py", line 4465, in _real_extract
    self.raise_no_formats(reason, expected=True)
  File "/home/dimon/.local/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 1276, in raise_no_formats
    raise ExtractorError(msg, expected=expected, video_id=video_id)
`

I guess that method doesn't work anymore.

**Comment by seproDev** [comment]
@finch71 I don't think it can. Video from this issue:
![Screenshot_20241205_134955_NewPipe](https://github.com/user-attachments/assets/d579fbdd-f32a-40ef-99e0-a43ae7a6bb42)

If you have any video that newpipe can access, but yt-dlp can't please provide it.
