### ISSUE TITLE
Can this be a Method to scrape community posts that could be added to ytdlp

### ISSUE THREAD

**Issue by heyeanne34** [yt-dlp/yt-dlp#11676]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

so i ran this by installing pip install post-archiver https://github.com/sadadYes/post-archiver and !playwright install-deps my code is: 

import subprocess

# Command to scrape YouTube community posts using post-archiver with verbose output
command = (
    f"post-archiver -c -v -o {output_dir} https://www.youtube.com/@aljazeeraenglish/community"
)

# Execute the command and show all activities
process = subprocess.Popen(command, shell=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)

# Stream the output in real-time
for line in iter(process.stdout.readline, b''):
    print(line.decode().strip())

# Wait for the process to complete
process.wait()

# Check for errors
if process.returncode != 0:
    error_output = process.stderr.read().decode()
    print("Error:", error_output)

The result is it gets the posts then the comments:
Found post: 2 days ago
Member only: False
URL: https://www.youtube.com/post/UgkxC1RFiNTq3RgUNCy4dL220qlZP-4UHWvm
Likes: 639
Comments: 204

in the file generated by the code:
[posts_aljazeeraenglish_temp_20241129_014159.json](https://github.com/user-attachments/files/17953531/posts_aljazeeraenglish_temp_20241129_014159.json)

so the code has 200 posts/comments limited and is kinda slow and not like ytdlp that can get everything
if ytdlp function can be added to the here itll work very well and get a ytdlp exe update for the community post added function

Hopefully this can help
pls add community posts feature

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by heyeanne34** [comment]
i ran this by installing pip install post-archiver https://github.com/sadadYes/post-archiver and !playwright install-deps my code is: 
the one in the description made parts of the code as a header so i just took a screenshot 

![Comunity post code i used Screenshot 2024-11-29 100621](https://github.com/user-attachments/assets/25c0748b-562f-4101-bb6b-eaf4360e9015)

**Comment by heyeanne34** [comment]
inside the json output by the code is: 
![code json output Screenshot 2024-11-29 101127](https://github.com/user-attachments/assets/770971d6-f851-4841-96f9-23502a290758)

ytdlp can probably get more metadata
pls

**Comment by coletdjnz** [comment]
out of scope, this is better off as a plugin.

Someone did build one, not tested myself https://github.com/biggestsonicfan/yt-dlp-community-plugin
