### ISSUE TITLE
Crunchyroll with username and password gives ERROR: [crunchyroll] G14U422Q4: Unable to download JSON metadata: HTTP Error 403: Forbidden (caused by <HTTPError 403: Forbidden>)

### ISSUE THREAD

**Issue by ubershmekel** [yt-dlp/yt-dlp#11675]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

usa

### Provide a description that is worded well enough to be understood

When trying to download a video from crunchyroll with a username and password, I get this error: `Unable to download JSON metadata: HTTP Error 403: Forbidden`

```
C:\Users\ubers>yt-dlp -u "myemail@gmail.com" -p mypassword "https://www.crunchyroll.com/watch/G14U422Q4/bakugos-start-
line"
[crunchyroll] Extracting URL: https://www.crunchyroll.com/watch/G14U422Q4/bakugos-start-line
[crunchyroll] Requesting token
[crunchyroll] G14U422Q4: Downloading object info JSON (cms)
ERROR: [crunchyroll] G14U422Q4: Unable to download JSON metadata: HTTP Error 403: Forbidden (caused by <HTTPError 403: Forbidden>)
```

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '-u', 'PRIVATE', '-p', 'PRIVATE', 'https://www.crunchyroll.com/watch/G14U422Q4/bakugos-start-line']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version master@2024.11.27.014746 from yt-dlp/yt-dlp-master-builds [00dcde728] (win_exe)
[debug] Python 3.10.11 (CPython AMD64 64bit) - Windows-10-10.0.22631-SP0 (OpenSSL 1.1.1t  7 Feb 2023)
[debug] exe versions: ffmpeg N-111626-g0ba719f726-20230726 (setts), ffprobe N-111626-g0ba719f726-20230726
[debug] Optional libraries: Cryptodome-3.21.0, brotli-1.1.0, certifi-2024.08.30, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.40.1, urllib3-2.2.3, websockets-14.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1837 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-master-builds/releases/latest
Latest version: master@2024.11.27.014746 from yt-dlp/yt-dlp-master-builds
yt-dlp is up to date (master@2024.11.27.014746 from yt-dlp/yt-dlp-master-builds)
[debug] Loading crunchyroll.ubershmekel@gmail.com from cache
[crunchyroll] Extracting URL: https://www.crunchyroll.com/watch/G14U422Q4/bakugos-start-line
[crunchyroll] Requesting token
[crunchyroll] G14U422Q4: Downloading object info JSON (cms)
ERROR: [crunchyroll] G14U422Q4: Unable to download JSON metadata: HTTP Error 403: Forbidden (caused by <HTTPError 403: Forbidden>)
  File "yt_dlp\extractor\common.py", line 742, in extract
  File "yt_dlp\extractor\crunchyroll.py", line 389, in _real_extract
  File "yt_dlp\extractor\crunchyroll.py", line 149, in _call_api
  File "yt_dlp\extractor\crunchyroll.py", line 140, in _call_base_api
  File "yt_dlp\extractor\common.py", line 1152, in download_content
  File "yt_dlp\extractor\common.py", line 1112, in download_handle
  File "yt_dlp\extractor\common.py", line 962, in _download_webpage_handle
  File "yt_dlp\extractor\common.py", line 911, in _request_webpage

  File "yt_dlp\extractor\common.py", line 898, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 4162, in urlopen
  File "yt_dlp\networking\common.py", line 117, in send
  File "yt_dlp\networking\_helper.py", line 208, in wrapper
  File "yt_dlp\networking\common.py", line 340, in send
  File "yt_dlp\networking\_requests.py", line 365, in _send
yt_dlp.networking.exceptions.HTTPError: HTTP Error 403: Forbidden
```

**Comment by bashonly** [comment]
support for this site is broken (see #10207) and the extractor is pending removal
