### ISSUE TITLE
Why am I getting an error stating can't play in mobile browser when running Firefox on Mac?

### ISSUE THREAD

**Issue by Napoleon-BlownApart** [yt-dlp/yt-dlp#11689]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Why am i getting the message `This content can't be played on your mobile browser. Get the YouTube app to start watching.` when I am using the latest Firefox and YT-DLP?  I have supplied `--user-agent "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:133.0) Gecko/20100101 Firefox/133.0"` and `--compat-options youtube-dl --cookies ~/tmp/cookies.txt --age-limit 18`.

Is there something I haven't done correctly?

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
why are you passing the user-agent? please share **complete verbose output**

**Comment by Napoleon-BlownApart** [comment]
Thanks for  having a look.
I am using `user-agent` because I thought that was the cause of the error message.
Note I logged into YT, exported the cookie to the file mentioned, and then logged out.  The video is rated `MA15+`, which is why I logged in.
The verbose output is below:

```
yt-dlp -f 136+140 -v --user-agent "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:133.0) Gecko/20100101 Firefox/133.0"  --compat-options youtube-dl --cookies ~/tmp/cookies.txt --age-limit 18 "https://www.youtube.com/watch?v=xxxxxxxxxxx"
[debug] Command-line config: ['-f', '136+140', '-v', '--user-agent', 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:133.0) Gecko/20100101 Firefox/133.0', '--compat-options', 'youtube-dl', '--cookies', '/Users/nap/tmp/cookies.txt', '--age-limit', '18', 'https://www.youtube.com/watch?v=xxxxxxxxxxx']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.11.18 from yt-dlp/yt-dlp [7ea278792] (source)
[debug] Lazy loading extractors is disabled
[debug] Compatibility options: embed-thumbnail-atomicparsley, seperate-video-versions, no-live-chat, no-playlist-metafiles, embed-metadata, prefer-legacy-http-handler, no-keep-subs, abort-on-error, no-clean-infojson, no-youtube-prefer-utc-upload-date, format-spec, no-external-downloader-progress, no-youtube-unavailable-videos, no-direct-merge, no-attach-info-json, list-formats, no-youtube-channel-redirect, filename, no-certifi, playlist-index, format-sort, filename-sanitization
[debug] Git HEAD: f91972953
[debug] Python 3.12.6 (CPython x86_64 64bit) - macOS-14.2.1-x86_64-i386-64bit (OpenSSL 3.3.2 3 Sep 2024)
[debug] exe versions: ffmpeg 7.0.2 (setts), ffprobe 7.0.2, phantomjs 2.1.1, rtmpdump 2.4
[debug] Optional libraries: sqlite3-3.46.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Loaded 1837 extractors
[youtube] Extracting URL: https://www.youtube.com/watch?v=xxxxxxxxxxx
[youtube] xxxxxxxxxxx: Downloading webpage
[debug] [youtube] Extracted SAPISID cookie
[debug] [youtube] Copying __Secure-3PAPISID cookie to SAPISID cookie
[youtube] xxxxxxxxxxx: Downloading ios player API JSON
[youtube] xxxxxxxxxxx: This video is age-restricted and YouTube is requiring account age-verification; some formats may be missing
[youtube] xxxxxxxxxxx: Downloading web creator player API JSON
[youtube] xxxxxxxxxxx: Downloading mweb player API JSON
ERROR: [youtube] xxxxxxxxxxx: Sign in to confirm your age. The video you have requested has been rated MA15+ and may contain content intended for mature audiences. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies
  File "~/yt-dlp/yt_dlp/extractor/common.py", line 742, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "~/yt-dlp/yt_dlp/extractor/youtube.py", line 4465, in _real_extract
    self.raise_no_formats(reason, expected=True)
  File "~/yt-dlp/yt_dlp/extractor/common.py", line 1276, in raise_no_formats
    raise ExtractorError(msg, expected=expected, video_id=video_id)
```

**Comment by bashonly** [comment]
Is your account age-verified? Are you in a region where YT requires account age-verification to watch age-restricted content?

Are you following the [wiki guide](https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies) when exporting YT cookies?

If you try again / share another log, please do not pass the `--user-agent` option

**Comment by Napoleon-BlownApart** [comment]
Thanks, you highlighted several things I wasn't aware of.
