### ISSUE TITLE
use --match-filter to exclude youtube premium format

### ISSUE THREAD

**Issue by error-reporting** [yt-dlp/yt-dlp#11694]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

how to use --match-filter to exclude youtube premium format and what param to use

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['--config-locations', '/data/user/0/com.deniscerri.ytdl/cache/config-TERMINAL[1733060084345].txt', '-P', '/storage/emulated/0/Android/data/com.deniscerri.ytdl/files/downloads/TERMINAL/7', '--no-cache-dir', '--ffmpeg-location', '/data/app/com.deniscerri.ytdl-7TgEaUl1aXwUu9d8Hc2kXw==/lib/arm64/libffmpeg.so']
[debug] | Config "/data/user/0/com.deniscerri.ytdl/cache/config-TERMINAL[1733060084345].txt": ['--match-filters', 'format_note', '!=? premium', '--add-header', 'UA:Mozilla/5.0 (X11; Linux x86_64; rv:131.0) Gecko/20100101 Firefox/131.0,gzip(gfe)', 'https://youtube.com/watch?v=Btc3p3h3cEI', '--skip-download', '-v']
[debug] Encodings: locale utf-8, fs utf-8, pref utf-8, out utf-8 (No ANSI), error utf-8 (No ANSI), screen utf-8 (No ANSI)
[debug] yt-dlp version nightly@2024.11.27.232921 from yt-dlp/yt-dlp-nightly-builds [00dcde728] (zip)
[debug] Python 3.11.10 (CPython aarch64 64bit) - Linux-4.4.248-hadesKernel-v2.0-greatlte-aarch64-with-libc (OpenSSL 3.3.2 3 Sep 2024, libc)
[debug] exe versions: ffmpeg 7.0.1 (setts), ffprobe 7.0.1
[debug] Optional libraries: Cryptodome-3.20.0, mutagen-1.47.0, sqlite3-3.46.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Loaded 1837 extractors
ERROR: [generic] '!=? premium' is not a valid URL. Set --default-search "ytsearch" (or run  yt-dlp "ytsearch:!=? premium" ) to search YouTube
  File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/extractor/common.py", line 742, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/user/0/com.deniscerri.ytdl/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/extractor/generic.py", line 2361, in _real_extract
    raise ExtractorError(
[debug] [youtube] Extracting signature function js_b46bb280_111
[debug] [youtube] Decrypted nsig -tPA_qnn-ByKMhsGkDA => 7xJcwIzuJbTizg
[debug] [youtube] Decrypted nsig ItAtHbyYm-Rkjgro8sC => nDWocm14haM0ng
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec, channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
```

**Comment by bashonly** [comment]
1. It looks like there's a quoting issue; the filter arg is being split

2. You'd also want to capitalize `Premium`

3. `--match-filter` will exclude the **entire video** if it has a premium format, I think you probably want to use `-f` instead to select a non-premium format:

```
-f "bv[format_note!*=Premium]+ba"
```

**Comment by error-reporting** [comment]
how to quote that --match-filters

**Comment by bashonly** [comment]
P.S. `--add-header "UA:..."` is just adding a bogus header for no reason afaict

**Comment by bashonly** [comment]
> how to quote that --match-filters
```
--match-filters "format_note!*=Premium"
```

**Comment by error-reporting** [comment]
> P.S. `--add-header "UA:..."` is just adding a bogus header for no reason afaict

that's to match what the user agent the browser use to access youtube and the browser that is used to take cookies from

**Comment by bashonly** [comment]
`UA` is not the header name, though. `User-Agent` is the header name. And it's not helpful with the youtube extractor
