### ISSUE TITLE
low res video downloaded if FFmpeg are not installed ?

### ISSUE THREAD

**Issue by tormyvancool** [yt-dlp/yt-dlp#11695]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

What I got on the internet is confusing, as answer to my question.
I saw that yt-dlp, to download High-Res files with the switch `--merge-output-format mp4` needs FFmpeg installed.
It informs yo with a very quick warning during the download process

My question ins: is there a way to get High-Res video in mp4 format without the FFmepg? Or am I obliged to install them (as I already did on my laptop where I discovered this requirement)?

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by rdamas** [comment]
If the source is youtube, then yes: you need to install ffmpeg for any download with decent resolution.

**Comment by tormyvancool** [comment]
> If the source is youtube, then yes: you need to install ffmpeg for any download with decent resolution.

Does it mean that's platform dependent than?

**Comment by bashonly** [comment]
An ffmpeg binary is platform-dependent, yes

**Comment by tormyvancool** [comment]
> An ffmpeg binary is platform-dependent, yes

Thank you so much.
