### ISSUE TITLE
Command doesn't work as expected after reinstalling yt-dlp, wrong video codec

### ISSUE THREAD

**Issue by xeno567** [yt-dlp/yt-dlp#11693]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Hi, after setting up a new Mac, I installed yt-dlp and ffmpeg using homebrew, just like I had it on my old machine. 

Everything seemed to work as expected, but when I tried syncing a downloaded video via iTunes, I got an error and realized that the video codec of downloaded videos was av01, not H264 like it used to. 

I've been using the following command for a while, excluding vp09 already: 

`yt-dlp -f 'bv[height<=1080][vcodec!~='vp09'][ext=mp4]+ba[ext=m4a]/mp4'`

After excluding av01 / specifying H264, I only got a video with 360p resolution. 
When looking through the available formats (-F), I realized that there are no options for H264 at all. Yet, just a month ago, I could still download videos in 1080p and H264 just fine using that exact command.

Did I perhaps forget to connect yt-dlp and ffmpeg in some way? Maybe it was converted automatically along the way before and now I just didn't set it up properly.

Please tell me if I need to set up another thing or modify my command so it works in the way I intended. I don't usually code and am therefore very bad at syntax, so a perfect command would be greatly appreciated ;)

Thanks!

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
use `-S vcodec:h264,res,acodec:aac`

> When looking through the available formats (-F), I realized that there are no options for H264 at all.

Please SHOW **COMPLETE VERBOSE OUTPUT** like the issue template asked you to do

Show the output of your command with `-vUF` added to it

**Comment by xeno567** [comment]
Your provided command technically worked the way I wanted, but now the file size of the video is doubled. Isn't there any way to modify my existing command just slightly? I don't really understand why -S is used suddenly.

After doing some research I found out that YouTube is focusing on av01 and is slowly dropping support on H264, so that would explain why it's not listed anymore as an available format for most videos. After searching around I found some videos that still had H264 available, so downloading those still worked as intended using my command. 
It's a very weird coincidence though that this change happens to affect me just at the time I reinstalled yt-dlp, so I am very confused, and thinking I did something wrong while installing was the obvious guess.

Another point of confusion for me is that H264 is also called avc1, which is very similar to AV1/av01, whatever way you write it... 

As you can see I'm left very clueless but I hope I could clarify what the problem is. 
So I guess my real question is: **How do I convert any 1080p video to H264 while downloading (if necessary), preferably outputting the same specs/file size as "native" H264?**

**Comment by bashonly** [comment]
> It's a very weird coincidence though that this change happens to affect me just at the time I reinstalled yt-dlp, so I am very confused, and thinking I did something wrong while installing was the obvious guess.

Youtube is changing things practically every week, especially lately. These things are out of our control. 

> How do I convert any 1080p video to H264 while downloading (if necessary), preferably outputting the same specs/file size as "native" H264?

You can't. AV1 is a more efficient codec than H264/AVC, so it results in smaller filesizes.

**Comment by xeno567** [comment]
Well, I didn't want the files to get bigger than they need to be of course, so smaller file sizes shouldn't be an issue. 
But generally converting while/after downloading is not possible with only one command? 
I could convert it afterwards using ffmpeg I guess but thats a bit bothersome...

**Comment by bashonly** [comment]
I don't understand what you want anymore. I thought you wanted to download H264; I provided a solution. Then you said the filesizes were too large. Now you want AV1 for a smaller filesize? Just download AV1 then.

**Comment by xeno567** [comment]
I wanted to understand why -S is suddenly the command of choice and how it differs from -f, but well, as long as it works ;)

> How do I convert any 1080p video to H264 while downloading (if necessary), preferably outputting the same specs/file size as "native" H264?

Also, I was so baffled about the doubling in file size that I forgot all standards, therefore my question didn't make sense. After checking again, around 50MB for a music video (in H264) is not unusual at all... sorry about that, I got what I asked for after all. 
So I guess this is solved now, thank you!

I don't think my confusion would help anyone so I would be glad if you could just delete this issue XD
