### ISSUE TITLE
I meet a problem about Downloading videos in Bilibili

### ISSUE THREAD

**Issue by BubbleSothoth** [yt-dlp/yt-dlp#11697]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

China(Chinese Mainland)

### Provide a description that is worded well enough to be understood

I meet this problem when I use it to download some videos coming from Bilibili. Everything is okey when I used it yesterday , but now it can not work. Althouth I update to the nightly version that be released on 11.18.2024, but the problem still keeps. I used VPN and made a test to download videos of YouTube and the procedure run normally, which means that this problem is only happened in Bilibili.

I read source codes simply, and find some clues. The procedure shows that the ERROR be raised at line 664, which means  variable "play_info" is empty. "play_info" is decided by function "traverse_obj" which is in charge of traversing a data struct called "play_info_obj". And I find "play_info_obj" is decided by " _search_json", a member function of BilibiliBaseIE's father class called "InfoExtractor". In this line, procedure find some data base "window.__playinfo__\s" in the webpage. Obviously, there are some unexpected things happening, such as no "window.__playinfo__\s" in the webpage. Maybe Bilibili official update their website? In fact, the issues #11665 discussed this situation that "window.__playinfo__" has been removed from the page source. Although some method was used but the problem still exists. I find that some come codes was inserted to raise a ExtractorError, but the core of the problem has not be solved. The extractor still can not work and users use.

Yt-dlp is my most favourite downloader in my daily life, and I will be glad if my description is useful for you. 

PS:  In fact, my mother tongue is Chinese and my English ability is not my advantage. Thus there are some mistake of grammar might be found in this description. I am so sorry if my English ability cause inconvenience to you.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-o', 'C:\\Users\\27746\\AppData\\Local\\Temp\\Easy-yt-dlp\\out', '--cookies', 'F:\\cookies\\cookies.txt', 'https://www.bilibili.com/video/BV1xq4y1f7GK', '-vU']
[debug] Encodings: locale cp936, fs utf-8, pref cp936, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.11.18 from yt-dlp/yt-dlp [7ea278792] (win_exe)
[debug] Python 3.10.11 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1t  7 Feb 2023)
[debug] exe versions: ffmpeg 7.0.1-essentials_build-www.gyan.dev (setts), ffprobe 7.0.1-essentials_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.21.0, brotli-1.1.0, certifi-2024.08.30, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.40.1, urllib3-2.2.3, websockets-13.1
[debug] Proxy map: {'http': 'http://127.0.0.1:7890', 'https': 'http://127.0.0.1:7890', 'ftp': 'http://127.0.0.1:7890'}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1837 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.11.18 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.11.18 from yt-dlp/yt-dlp)
[BiliBili] Extracting URL: https://www.bilibili.com/video/BV1xq4y1f7GK
[BiliBili] 1xq4y1f7GK: Downloading webpage
WARNING: [BiliBili] unable to extract play info; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
ERROR: [BiliBili] 1xq4y1f7GK: Failed to extract play info; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 742, in extract
  File "yt_dlp\extractor\bilibili.py", line 664, in _real_extract
```

**Comment by bashonly** [comment]
Yes, this is the same issue as #11665

It will be fixed by pull request #11667, which is still being reviewed

Once #11665 is closed, you can run `yt-dlp --update-to master` to get the fix

Closing this as duplicate
