### ISSUE TITLE
video

### ISSUE THREAD

**Issue by Waqasaziz248** [yt-dlp/yt-dlp#11699]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Pakistan 

### Provide a description that is worded well enough to be understood

Some videos from Instagram when i try to download shows(Unable to get URL) or something like that. I have also report that commond to you
![Screenshot_20241202-041240](https://github.com/user-attachments/assets/97099e94-8817-4ebc-a2ab-b4ae5140de1e)

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
Command: 
 -N "3" --trim-filenames "182" --no-mtime --embed-chapters -f "bv+ba/b" --embed-subs --sub-format "srt/best" --convert-subtitles "srt" --sub-langs "en.*,.*-orig" -P "/storage/emulated/0/Android/data/com.deniscerri.ytdl/files/downloads/190" -o "%(uploader).30B - %(title).170B.%(ext)s" --print-to-file "video:%()#j" "/storage/emulated/0/Android/data/com.deniscerri.ytdl/files/downloads/infojsons/72368f48aafc6f8ca191e831a88b8b87.info.json" --parse-metadata "%(uploader,channel,creator|null)l:^(?P<uploader>.*?)(?:(?= - Topic)|$)" "https://www.instagram.com/p/DCwLZ4auDiO/?igsh=MXU4MTVpZGd2MWdoNw=="
```

**Comment by bashonly** [comment]
It's not a video. It's just an image
