### ISSUE TITLE
CAN'T DOWNLOAD INSTAGRAM VIDEOS NOW!!

### ISSUE THREAD

**Issue by BracedScarf** [yt-dlp/yt-dlp#11692]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Pakistan 

### Provide a description that is worded well enough to be understood

At first i can download the videos of Instagram. But recently it doesn't work now. I did everything i could. I even join discord and follow steps and insert my login credentials in the cookies. But doesn't work now. Please fix this

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
Downloading:
Title: 
URL: https://www.instagram.com/share/reel/_bW-p2y7r
Type: video
Command: 
 -N "3" --cookies "/data/user/0/com.deniscerri.ytdl/cache/cookies.txt" --trim-filenames "184" --no-mtime --sponsorblock-remove "music_offtopic" --write-info-json --no-clean-info-json -o "infojson:/storage/emulated/0/Android/data/com.deniscerri.ytdl/files/downloads/infojsons/38c2a10e93617916841c422d8ab4fcc0" -o "%(uploader).30B - %(title).170B.%(ext)s" --sponsorblock-mark "all" --embed-chapters -f "bv+ba/b" --embed-subs --sub-format "srt/best" --convert-subtitles "srt" --sub-langs "en.*,.*-orig" -P "/storage/emulated/0/Android/data/com.deniscerri.ytdl/files/downloads/8" --parse-metadata "%(uploader,channel,creator|null)l:^(?P<uploader>.*?)(?:(?= - Topic)|$)" "https://www.instagram.com/share/reel/_bW-p2y7r" 

WARNING: [Instagram] Video info extraction failed: HTTP Error 400: Bad Request
WARNING: [Instagram] _bW-p2y7r: Instagram API is not granting access
WARNING: [Instagram] unable to extract username; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
ERROR: [Instagram] _bW-p2y7r: Unable to extract video url; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

**Comment by bashonly** [comment]
Duplicate of #11630
