### ISSUE TITLE
transfer speed is shown incorrectly on slower then internet storage

### ISSUE THREAD

**Issue by nanderer** [yt-dlp/yt-dlp#11704]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

hi,

i have some bad setup, i am writing to an usb2 hard disk with is mounted using wifi using sshfs, normally that is fine and all but when i have a couple of transfer jobs running at the same time the it drops so deep that it is slower then the internet speed, but it is not shown correctly (compere download speed and time left). Also i would appreciate if the FixupM3u8 step could be improved maybe with using /tmp/ instead of the destination to speed thins up a little...

thanks in advance for looking into it 

### relevant  Output

not relevant to show the whole stuff but manually braking lines at the right tme to get comparable values is key in this case...:
```shell
[download]  21.2% of ~ 380.38MiB at    1.31MiB/s ETA 12:01 (frag 33/152)        
[download]  35.6% of ~ 361.28MiB at    1.35MiB/s ETA 03:03 (frag 54/152)        
[download] 100% of  320.70MiB in 00:06:18 at 868.70KiB/s  
```
here you can see what happens when a ytdlp transer is done while the blocking transfer is is just getting finished, note that MiB/s dosnt represent the actual transfer speed, while it is waiting for the storage, also maybe a good idea to write fragments and part files to /tmp and not to the destinaton if it is network storage

PS: yes i omitted the verbose log steps for a good reason: it is not reproducible, i was happy to be able to capture the behavior at all, also it is hardly relevant given my hopefully adequate description

**Comment by bashonly** [comment]
> also maybe a good idea to write fragments and part files to /tmp

`-P "temp:/tmp"`
