### ISSUE TITLE
[Feature Request] Make --download-archive more human readable

### ISSUE THREAD

**Issue by Burve** [yt-dlp/yt-dlp#1172]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running yt-dlp version **2021.09.25**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description

While using `--download-archive` helps keep track of what is downloaded and what is not, but in a case, that something need t be redownloaded it is not really human readable. As example

```
funimation 1311430
funimation 1321632
funimation 1321613
funimation 1321629
funimation 1321628
funimation 1321627
funimation 1321631
funimation 1333848
funimation 1339679
funimation 1340989
funimation 1340974
funimation 1341030
```
I do understand, that I can add file ID to the file name and try to find a proper ID that way, but having an option to pass extra parameter with OUTPUT TEMPLATE to add after ID would allow for a more user-readable archive.

**Comment by Ashish0804** [comment]
It's not supposed to be human readable.
Use `yt-dlp <url> --print id` to get the `id` if it's not obvious from the url

Or use `yt-dlp <url> --no-download-archive`

**Comment by Burve** [comment]
I am more talking about something like
`funimation 1311430 episode_name_or_some_other_custom_text_here`
so main logic stays, but if you need to edit it by hand, it is doable.

As for getting ID separately and then matching them to get the line I need to remove (in my case if something is updated in a video and I need to redownload it, first I need to find it in the list and remove it to redownload) and will do that with a custom script.
Here I just thinking about more human convenience if only few records needs to be edited, having some extra human-readable info would be nice.

**Comment by pukkandan** [comment]
Download archive is for yt-dlp to read it back. It is not meant to be human readable
