### ISSUE TITLE
Somewhat more elaborate means to detect compatible Python version(s)

### ISSUE THREAD

**Issue by apfeltee** [yt-dlp/yt-dlp#11727]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

The script file `yt-dlp.sh` makes pretty basic assumptions about the current Python installation.  
However on some platforms, such as Cygwin, this will fail because cygwin caches executables differently, and also tends to be somewhat behind most platforms including, but not limited to, Linux.

Since this is an extremely minor change, intended to make yt-dlp usable rightaway by `ln -sfv`ing to `$PATH`, i'm posing this as a request.  
I think that other non-Linux platforms might benefit from this as well.  
I've written it in such a way that it is trivial to extend to check for further versions

Here is the modified version of `yt-dlp.sh`:

```
#!/bin/bash

pyexe=python

## yt-dlp requires >=3.9
checkthesepythons=(
  python3.9
  python3.10
)

for item in "${checkthesepythons[@]}"; do
  if which "$item" >/dev/null; then
    pyexe="$item"
    break
  fi
done

if [[ "$pyexe" == "python" ]]; then
  pyver="$("$pyexe" --version | cut -d' ' -f2-)"
  if [[ "$pyver" =~ *3.* ]]; then
    echo "*** could not find python3.{9,*} - this may not work!"
  fi
fi

exec "$pyexe" -Werror -Xdev "$(dirname "$(realpath "$0")")/yt_dlp/__main__.py" "$@"
```

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
This would add a bash dependency, though. It's more portable if we keep it POSIX sh

**Comment by bashonly** [comment]
It's a script intended only for developers anyways. They should be able to get their Python versions sorted. Some maintainers even want to remove this script entirely

**Comment by dirkf** [comment]
Anyone who should be running the script should be capable of setting `PYTHON` so as to find the desired Python executable, if `python3` is not on the `PATH`.

The Windows version `yt-dlp.cmd` expects the Python command to be `py` but could be made equivalent, s-t like:
```cmd
@echo off
if [%PYTHON%]==[] set PYTHON=python3
%PYTHON% -bb -Werror -Xdev "%~dp0yt_dlp\__main__.py" %*
```
