### ISSUE TITLE
Using the extract_info method to extract specific m3u8 links can download in the background for a long time

### ISSUE THREAD

**Issue by Guovin** [yt-dlp/yt-dlp#11729]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Even though I used asynchronous timeout processing and skipped the download parameters, the background download thread continued to download after the timeout period was reached and did not stop until I shut down the terminal. My guess is that there is a part of this special m3u8 request (for example: http://zsntlqj.xicp.net:8896/bysid/83.m3u8) will be unlimited downloads, lead to can't return information. Is there any good solution?
This my code:
```python
def get_info_yt_dlp(url, timeout=config.sort_timeout):
    """
    Get the url info by yt_dlp
    """
    ydl_opts = {
        "socket_timeout": timeout,
        "skip_download": True,
        "no_warnings": True,
        "format": "best",
        "verbose": True,
    }
    with yt_dlp.YoutubeDL(ydl_opts) as ydl:
        return ydl.sanitize_info(ydl.extract_info(url, download=False))


async def get_speed_yt_dlp(url, timeout=config.sort_timeout):
    """
    Get the speed of the url by yt_dlp
    """
    try:
        start_time = time()
        info = await asyncio.wait_for(
            asyncio.to_thread(get_info_yt_dlp, url, timeout), timeout=timeout
        )
        fps = int(round((time() - start_time) * 1000)) if len(info) else float("inf")
        resolution = (
            f"{info['width']}x{info['height']}"
            if "width" in info and "height" in info
            else None
        )
        return fps, resolution
    except:
        return float("inf"), None

speed = await get_speed_yt_dlp("http://zsntlqj.xicp.net:8896/bysid/83.m3u8", timeout=10)
```

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Encodings: locale cp936, fs utf-8, pref cp936, out utf-8, error utf-8, screen utf-8 
[debug] yt-dlp version stable@2024.12.03 from yt-dlp/yt-dlp [2b67ac300] (pip) API 
[debug] params: {'socket_timeout': 10, 'skip_download': True, 'no_warnings': True, 'format': 'best', 'verbose': True, 'compat_opts': set(), 'http_headers': {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'Accept-Language': 'en-us,en;q=0.5', 'Sec-Fetch-Mode': 'navigate'}} 
[debug] Python 3.13.0 (CPython AMD64 64bit) - Windows-11-10.0.22631-SP0 (OpenSSL 3.0.15 3 Sep 2024)
[debug] exe versions: ffmpeg N-110767-g944243477b-20230525 (setts), ffprobe N-110767-g944243477b-20230525
[debug] Optional libraries: certifi-2024.08.30, requests-2.32.3, sqlite3-3.45.3, urllib3-2.2.3
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Loaded 1837 extractors
[generic] Extracting URL: http://zsntlqj.xicp.net:8896/bysid/83.m3u8
[generic] 83: Downloading webpage
[debug] Identified a direct video link
[generic] 83: Downloading m3u8 information
```

**Comment by Guovin** [comment]
> Illegitimate URL. Won't support

Why is it defined as illegal? According to my understanding, if this kind of url does not meet the yt_dlp processing requirements, is there a way to skip? Or provide a parameter to extract information timeout?

**Comment by seproDev** [comment]
You want to argue that `zsntlqj.xicp.net` is an official service? To what service does it belong?
We will not provide support for pirated/illegal content.
