### ISSUE TITLE
Can Youtube-dlc and Youtube-dlp both work on same server?[Question]

### ISSUE THREAD

**Issue by adapana** [yt-dlp/yt-dlp#1173]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

I am currently using Youtube-dlc on Ubuntu server, now I want to use youtube-dlp on same server. Will I face any issue using both?  Or Do I have to make any changes in server or code?

**Comment by Ashish0804** [comment]
yes.
