### ISSUE TITLE
How to stop the extract_info execution before returning the result?

### ISSUE THREAD

**Issue by Guovin** [yt-dlp/yt-dlp#11739]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Using the extract_info method on a url, is there a way to set the execution timeout? I tried, but after reaching the timeout, extract_info still seems to be running, how do I stop it? This is my current code:
```python
def get_info_yt_dlp(url, timeout=config.sort_timeout):
    """
    Get the url info by yt_dlp
    """
    ydl_opts = {
        "socket_timeout": timeout,
        "skip_download": True,
        "quiet": True,
        "no_warnings": True,
        "format": "best"
    }
    with yt_dlp.YoutubeDL(ydl_opts) as ydl:
        return ydl.sanitize_info(ydl.extract_info(url, download=False))


async def get_speed_yt_dlp(url, timeout=config.sort_timeout):
    """
    Get the speed of the url by yt_dlp
    """
    try:
        start_time = time()
        info = await asyncio.wait_for(
            asyncio.to_thread(get_info_yt_dlp, url, timeout), timeout=timeout
        )
        speed = int(round((time() - start_time) * 1000)) if len(info) else float("inf")
        return speed
    except:
        return float("inf")
```

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
You would use `socket_timeout` (as you are doing). If using it doesn't seem to be working, then there's likely something else going on instead of the host being unresponsive. You would have to provide a verbose log of the issue, and make sure any and all URLs in the log are legitimate or you will be blocked from the repository for spam.

**Comment by Guovin** [comment]
I found that downloading the m3u8 url containing playlist caused a timeout, I will close this issue, thank you.
