### ISSUE TITLE
Cannot download members video

### ISSUE THREAD

**Issue by assassinliujie** [yt-dlp/yt-dlp#11737]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Extracted 636 cookies from firefox
[youtube] Extracting URL: https://www.youtube.com/watch?v=twFQyfwizfc
[youtube] twFQyfwizfc: Downloading webpage
[youtube] twFQyfwizfc: Downloading ios player API JSON
[youtube] twFQyfwizfc: Downloading ios player API JSON
WARNING: [youtube] YouTube said: ERROR - Request contains an invalid argument.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (1/3)...
[youtube] twFQyfwizfc: Downloading ios player API JSON
WARNING: [youtube] YouTube said: ERROR - Request contains an invalid argument.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (2/3)...
WARNING: [youtube] YouTube said: ERROR - Request contains an invalid argument.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (3/3)...
[youtube] twFQyfwizfc: Downloading ios player API JSON
[youtube] twFQyfwizfc: Downloading mweb player API JSON
WARNING: [youtube] YouTube said: ERROR - Request contains an invalid argument.
WARNING: [youtube] Unable to download API page: HTTP Error 400: Bad Request (caused by <HTTPError 400: Bad Request>)
Extracting cookies from firefox
[Cookies] Loading cookie      0/   650Extracted 636 cookies from firefox
[youtube] Extracting URL: https://www.youtube.com/watch?v=twFQyfwizfc
[youtube] twFQyfwizfc: Downloading webpage
[youtube] twFQyfwizfc: Downloading ios player API JSON
WARNING: [youtube] YouTube said: ERROR - Request contains an invalid argument.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (1/3)...
[youtube] twFQyfwizfc: Downloading ios player API JSON
[youtube] twFQyfwizfc: Downloading ios player API JSON
WARNING: [youtube] YouTube said: ERROR - Request contains an invalid argument.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (2/3)...
WARNING: [youtube] YouTube said: ERROR - Request contains an invalid argument.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (3/3)...
[youtube] twFQyfwizfc: Downloading ios player API JSON
WARNING: [youtube] YouTube said: ERROR - Request contains an invalid argument.
WARNING: [youtube] Unable to download API page: HTTP Error 400: Bad Request (caused by <HTTPError 400: Bad Request>)
[youtube] twFQyfwizfc: Downloading mweb player API JSON
[info] twFQyfwizfc: Downloading 1 format(s): 299+251
[download] Destination: videos\twFQyfwizfc\twFQyfwizfc.mp4.f299.mp4
[download]   0.4% of    5.29GiB at   44.85MiB/s ETA 02:00Error processing video https://www.youtube.com/watch?v=twFQyfwizfc: ERROR: unable to download video data: H
TTP Error 403: Forbidden
ERROR: unable to download video data: HTTP Error 403: Forbidden
only this specific video cannot be download.
In fact, it will attempt to start downloading a small portion of the content first, and then a 403 error occurs. I tried changing devices, but the error still happens.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
C:\Users\assas>yt-dlp -vU --proxy http://127.0.0.1:7897 --cookies-from-browser firefox https://www.youtube.com/watch?v=twFQyfwizfc
[debug] Command-line config: ['-vU', '--proxy', 'http://127.0.0.1:7897', '--cookies-from-browser', 'firefox', 'https://www.youtube.com/watch?v=twFQyfwizfc']
[debug] Encodings: locale cp936, fs utf-8, pref cp936, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.11.27.232921 from yt-dlp/yt-dlp-nightly-builds [00dcde728] (pip)
[debug] Python 3.12.7 (CPython AMD64 64bit) - Windows-11-10.0.22631-SP0 (OpenSSL 3.0.15 3 Sep 2024)
[debug] exe versions: ffmpeg 2024-11-28-git-bc991ca048-full_build-www.gyan.dev (setts), ffprobe 2024-11-28-git-bc991ca048-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.21.0, brotli-1.1.0, certifi-2024.08.30, mutagen-1.47.0, requests-2.32.3, sqlite3-3.45.3, urllib3-2.2.3, websockets-14.1
[debug] Proxy map: {'all': 'http://127.0.0.1:7897'}
Extracting cookies from firefox
[debug] Extracting cookies from: "C:\Users\assas\AppData\Roaming\Mozilla\Firefox\Profiles\q117xsxa.default-release\cookies.sqlite"
Extracted 677 cookies from firefox
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1837 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
[debug] Downloading _update_spec from https://github.com/yt-dlp/yt-dlp-nightly-builds/releases/latest/download/_update_spec
Current version: nightly@2024.11.27.232921 from yt-dlp/yt-dlp-nightly-builds
Latest version: nightly@2024.12.04.232942 from yt-dlp/yt-dlp-nightly-builds
ERROR: You installed yt-dlp with pip or using the wheel from PyPi; Use that to update
[youtube] Extracting URL: https://www.youtube.com/watch?v=twFQyfwizfc
[youtube] twFQyfwizfc: Downloading webpage
[debug] [youtube] Extracted SAPISID cookie
[youtube] twFQyfwizfc: Downloading ios player API JSON
WARNING: [youtube] YouTube said: ERROR - Request contains an invalid argument.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (1/3)...
[youtube] twFQyfwizfc: Downloading ios player API JSON
WARNING: [youtube] YouTube said: ERROR - Request contains an invalid argument.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (2/3)...
[youtube] twFQyfwizfc: Downloading ios player API JSON
WARNING: [youtube] YouTube said: ERROR - Request contains an invalid argument.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (3/3)...
[youtube] twFQyfwizfc: Downloading ios player API JSON
WARNING: [youtube] YouTube said: ERROR - Request contains an invalid argument.
WARNING: [youtube] Unable to download API page: HTTP Error 400: Bad Request (caused by <HTTPError 400: Bad Request>)
[youtube] twFQyfwizfc: Downloading mweb player API JSON
[debug] Loading youtube-nsig.62ccfae7 from cache
[debug] [youtube] Decrypted nsig -8QF0pigaumRBnMwag6 => w1KhZ4kqGMssAA
[debug] Loading youtube-nsig.62ccfae7 from cache
[debug] [youtube] Decrypted nsig Rzavlo4ZCXK5UbX7_D8 => LiO7lUNS49m4_A
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec, channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] twFQyfwizfc: Downloading 1 format(s): 299+251
[debug] Invoking http downloader on "https://rr4---sn-npoe7nsl.googlevideo.com/videoplayback?expire=1733377276&ei=nOhQZ7jMDsuNg8UPrtaxsQ4&ip=2400%3A8901%3A%3Af03c%3A95ff%3Afe8f%3Af63b&id=o-AIWmJKd2uuy8S6jQxtyLzWkYQA9hLe2CyGgR8rDq7iEg&itag=299&aitags=134%2C136%2C160%2C243%2C298%2C299&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&met=1733355676%2C&mh=V5&mm=31%2C26&mn=sn-npoe7nsl%2Csn-oguesn6k&ms=au%2Conr&mv=m&mvi=4&pl=32&rms=au%2Cau&initcwndbps=515000&siu=1&bui=AQn3pFRA_dVv9x7akfloaWP0eyloi4qIK2wwQQJ1-bnJXBiAGM9yLTPER5oR-rgbAyTDkBI9lA&spc=qtApASOj8HbzhcFkS2eo7ZDk9spHbVKeArQzLaJvbbVlvRSVvVQAKvoiPcNPAgePYs0uiThJHFWrs8Q&vprv=1&svpuc=1&mime=video%2Fmp4&ns=Q5LYftX1WDf6ZsKDiqYQs9kQ&rqh=1&gir=yes&clen=5681555711&dur=14147.000&lmt=1733332230490682&mt=1733355185&fvip=2&keepalive=yes&fexp=51326932%2C51331020%2C51335594&c=MWEB&sefc=1&txp=7209224&n=LiO7lUNS49m4_A&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cxpc%2Csiu%2Cbui%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cns%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRQIhANvceKzcgycIQuDZv_dV20MwZcFAIBN5lEWCR7ib7Mf2AiAe0S_tBAICwRWo7RbfuJFkXFpv179oEC6UE2miGktsLA%3D%3D&lsparams=met%2Cmh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Crms%2Cinitcwndbps&lsig=AGluJ3MwRAIgAbEO_uuRmfaRdk2jjl4kHJ27AuN3uskAoPxtKpIio-UCICCp2FtgcTXVkOx6awLoppJieie10JRHozjoSeIdcTZu"
[download] Resuming download at byte 20137170
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "C:\Users\assas\AppData\Local\Programs\Python\Python312\Lib\site-packages\yt_dlp\YoutubeDL.py", line 3461, in process_info
    partial_success, real_download = self.dl(fname, new_info)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\assas\AppData\Local\Programs\Python\Python312\Lib\site-packages\yt_dlp\YoutubeDL.py", line 3199, in dl
    return fd.download(name, new_info, subtitle)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\assas\AppData\Local\Programs\Python\Python312\Lib\site-packages\yt_dlp\downloader\common.py", line 464, in download
    ret = self.real_download(filename, info_dict)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\assas\AppData\Local\Programs\Python\Python312\Lib\site-packages\yt_dlp\downloader\http.py", line 367, in real_download
    establish_connection()
  File "C:\Users\assas\AppData\Local\Programs\Python\Python312\Lib\site-packages\yt_dlp\downloader\http.py", line 118, in establish_connection
    ctx.data = self.ydl.urlopen(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\assas\AppData\Local\Programs\Python\Python312\Lib\site-packages\yt_dlp\YoutubeDL.py", line 4162, in urlopen
    return self._request_director.send(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\assas\AppData\Local\Programs\Python\Python312\Lib\site-packages\yt_dlp\networking\common.py", line 117, in send
    response = handler.send(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\assas\AppData\Local\Programs\Python\Python312\Lib\site-packages\yt_dlp\networking\_helper.py", line 208, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\assas\AppData\Local\Programs\Python\Python312\Lib\site-packages\yt_dlp\networking\common.py", line 340, in send
    return self._send(request)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\assas\AppData\Local\Programs\Python\Python312\Lib\site-packages\yt_dlp\networking\_requests.py", line 365, in _send
    raise HTTPError(res, redirect_loop=max_redirects_exceeded)
yt_dlp.networking.exceptions.HTTPError: HTTP Error 403: Forbidden
```

**Comment by bashonly** [comment]
update to the latest nightly
