### ISSUE TITLE
Vimeo/Patreon link returns 403 even with cookies fetched.

### ISSUE THREAD

**Issue by TrulyStucker** [yt-dlp/yt-dlp#11732]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Serbia

### Provide a description that is worded well enough to be understood

I'm trying to download the vimeo video from Patreon and nothing that I tried of worked. Inevitable I'm getting a 403 access denied error. --cookies-from-browser chrome won't work due to "Could not copy Chrome cookie database. See  https://github.com/yt-dlp/yt-dlp/issues/7271", tried every possible solution. In the end I managed to extract cookies to a .txt file and put a path to that file as advised here: https://github.com/yt-dlp/yt-dlp/issues/10927. Still no luck. Maybe I'm doing something wrong, I dunno.

403 error is being returned both when browser is closed / when it's open.

First time raising an issue here, I think I went through the checklist and didn't break any rules. Sorry if I did something wrong.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--cookies', 'D:\\ffmpeg\\bin\\cookies.txt', '--referer', 'https://www.patreon.com/posts/wintersun-sons-110460144', 'https://vod-adaptive-ak.vimeocdn.com/exp=1733335309~acl=%2F17615183-bd54-4774-ae2f-5e2f01278e32%2F%2A~hmac=4f594011d2648f87d31d9548cc106303bf4ade3009747170124534498c36ca81/17615183-bd54-4774-ae2f-5e2f01278e32/v2/playlist/av/primary/prot/cXNyPTE/playlist.m3u8']
[debug] Encodings: locale cp1251, fs utf-8, pref cp1251, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version master@2024.12.03.202240 from yt-dlp/yt-dlp-master-builds [2b67ac300] (win_exe)
[debug] Python 3.10.11 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1t  7 Feb 2023)
[debug] exe versions: ffmpeg 2023-12-11-git-1439784ff0-full_build-www.gyan.dev (setts), ffprobe 2023-12-11-git-1439784ff0-full_build-www.gyan.dev, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.21.0, brotli-1.1.0, certifi-2024.08.30, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.40.1, urllib3-2.2.3, websockets-14.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1837 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-master-builds/releases/latest
Latest version: master@2024.12.03.202240 from yt-dlp/yt-dlp-master-builds
yt-dlp is up to date (master@2024.12.03.202240 from yt-dlp/yt-dlp-master-builds)
[generic] Extracting URL: https://vod-adaptive-ak.vimeocdn.com/exp=1733335309~acl=%2F17615183-bd54-4774-ae2f-5e2f01278e32%2F%2A~hmac=4f594011d2648f87d31d9548cc106303bf4ade3009747170124534498c36ca81/17615183-bd54-4774-ae2f-5e2f01278e32/v2/playlist/av/primary/prot/cXNyPTE/playlist.m3u8
[generic] playlist: Downloading webpage
ERROR: [generic] Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: Forbidden>)
  File "yt_dlp\extractor\common.py", line 742, in extract
  File "yt_dlp\extractor\generic.py", line 2393, in _real_extract
  File "yt_dlp\extractor\common.py", line 911, in _request_webpage

  File "yt_dlp\extractor\common.py", line 898, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 4162, in urlopen
  File "yt_dlp\networking\common.py", line 117, in send
  File "yt_dlp\networking\_helper.py", line 208, in wrapper
  File "yt_dlp\networking\common.py", line 340, in send
  File "yt_dlp\networking\_requests.py", line 365, in _send
yt_dlp.networking.exceptions.HTTPError: HTTP Error 403: Forbidden
```

**Comment by bashonly** [comment]
pass the patreon webpage URL or the vimeo webpage URL, not the m3u8 URL
