### ISSUE TITLE
How to install nightly

### ISSUE THREAD

**Issue by BBugato** [yt-dlp/yt-dlp#11741]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I install yt-dlp all the time with sudo python3.9 -m pip install --upgrade git+https://github.com/yt-dlp/yt-dlp.git@release

Can somebody tell me how I can install the nightly version with this code pip install .?!

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by seproDev** [comment]
https://github.com/yt-dlp/yt-dlp?tab=readme-ov-file#update
```
# To install nightly with pip:
python3 -m pip install -U --pre "yt-dlp[default]"
```

**Comment by BBugato** [comment]
Hi! I had version 03.12.2024 - now I have version after the command from you 2023.11.16 

How come?
