### ISSUE TITLE
[Site Request] PornZog.com

### ISSUE THREAD

**Issue by FraFraFra-LongD** [yt-dlp/yt-dlp#1174]
## Checklist

- [x] I'm reporting a site feature request
- [x] I've verified that I'm running yt-dlp version **2021.09.25**
- [x] I've searched the bugtracker for similar site feature requests including closed ones

## Description

I'm unable to download videos from pornzog.com, i can still download every video with badassdowloader but I'd like to standardize my program to download from that site too, without doing it manually.

**Comment by Ashish0804** [comment]
Incorrect issue format therefore closing this. Open a new issue with proper format.
