### ISSUE TITLE
Doesn't take notice of the command line

### ISSUE THREAD

**Issue by CliveWi** [yt-dlp/yt-dlp#11745]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Why am I going to Chrome when I was told to use Edge?

PS C:\YouTube-DL> .\yt-dlp_x86.exe --cookies-from-browser Edge https://www.youtube.com/watch?v=dwaxWoJPUC0
Extracting cookies from edge
ERROR: Could not copy Chrome cookie database. See  https://github.com/yt-dlp/yt-dlp/issues/7271  for more info
ERROR: Could not copy Chrome cookie database. See  https://github.com/yt-dlp/yt-dlp/issues/7271  for more info
PS C:\YouTube-DL>

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
PS C:\YouTube-DL> .\yt-dlp_x86.exe -U
Latest version: nightly@2024.12.04.232942 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.12.04.232942 from yt-dlp/yt-dlp-nightly-builds)
PS C:\YouTube-DL> .\yt-dlp_x86.exe --cookies-from-browser Edge https://www.youtube.com/watch?v=dwaxWoJPUC0
Extracting cookies from edge
ERROR: Could not copy Chrome cookie database. See  https://github.com/yt-dlp/yt-dlp/issues/7271  for more info
ERROR: Could not copy Chrome cookie database. See  https://github.com/yt-dlp/yt-dlp/issues/7271  for more info
PS C:\YouTube-DL> .\yt-dlp_x86.exe -vU --cookies-from-browser Edge https://www.youtube.com/watch?v=dwaxWoJPUC0
[debug] Command-line config: ['-vU', '--cookies-from-browser', 'Edge', 'https://www.youtube.com/watch?v=dwaxWoJPUC0']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.12.04.232942 from yt-dlp/yt-dlp-nightly-builds [fca3eb5f8] (win_x86_exe)
[debug] Python 3.10.11 (CPython AMD64 32bit) - Windows-10-10.0.22631-SP0 (OpenSSL 1.1.1t  7 Feb 2023)
[debug] exe versions: ffmpeg 2024-07-28-git-e7d3ff8dcd-full_build-www.gyan.dev (setts), ffprobe 2024-07-28-git-e7d3ff8dcd-full_build-www.gyan.dev, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.21.0, brotli-1.1.0, certifi-2024.08.30, mutagen-1.47.0, requests-2.32.3, sqlite3-3.40.1, urllib3-2.2.3, websockets-14.1
[debug] Proxy map: {}
Extracting cookies from edge
[debug] Extracting cookies from: "C:\Users\Clive\AppData\Local\Microsoft\Edge\User Data\Default\Network\Cookies"
ERROR: Could not copy Chrome cookie database. See  https://github.com/yt-dlp/yt-dlp/issues/7271  for more info
Traceback (most recent call last):
  File "yt_dlp\cookies.py", line 310, in _extract_chrome_cookies
  File "yt_dlp\cookies.py", line 1102, in _open_database_copy
  File "shutil.py", line 417, in copy
  File "shutil.py", line 254, in copyfile
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\Clive\\AppData\\Local\\Microsoft\\Edge\\User Data\\Default\\Network\\Cookies'

ERROR: Could not copy Chrome cookie database. See  https://github.com/yt-dlp/yt-dlp/issues/7271  for more info
Traceback (most recent call last):
  File "yt_dlp\cookies.py", line 310, in _extract_chrome_cookies
  File "yt_dlp\cookies.py", line 1102, in _open_database_copy
  File "shutil.py", line 417, in copy
  File "shutil.py", line 254, in copyfile
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\Clive\\AppData\\Local\\Microsoft\\Edge\\User Data\\Default\\Network\\Cookies'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\cookies.py", line 99, in load_cookies
  File "yt_dlp\cookies.py", line 122, in extract_cookies_from_browser
  File "yt_dlp\cookies.py", line 351, in _extract_chrome_cookies
yt_dlp.utils.DownloadError: Could not copy Chrome cookie database. See  https://github.com/yt-dlp/yt-dlp/issues/7271  for more info
```

**Comment by grqx** [comment]
Did you read what the error message said? See https://github.com/yt-dlp/yt-dlp/issues/7271#issuecomment-1584404779.

**Comment by bashonly** [comment]
> Why am I going to Chrome when I was told to use Edge?

Edge is a chromium-based browser; it shares its cookies code with Chrome. The issue you are experiencing is #7271, see the comment linked above for workarounds. 

Even if you work around that, though, you'll probably run into #10927

Either use Firefox with `--cookies-from-browser` or else [export your cookies to a cookiefile and use it with `--cookies`](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp)
