### ISSUE TITLE
Allow .mp4 to use .vtt file while embedding.

### ISSUE THREAD

**Issue by 1YuvrajS** [yt-dlp/yt-dlp#11740]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

This .mp4 files use a .txt file for subtitle, they do not use .vtt files. The .vtt files offer dynamic text styling and more detailed text within each embedded file.

For example:
1. In .txt, shows two English in subtitle list. Which I don't know which one is Auto Generated.

2. In .vtt, it will show two different one is English and another Is English - Auto Generated.

Because we need .vtt over .txt for .mp4 videos.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
Nil
```

**Comment by bashonly** [comment]
mp4 doesn't support webvtt

**Comment by 1YuvrajS** [comment]
> ~~mp4 doesn't support webvtt~~
> 
> Correction: ***ffmpeg*** doesn't support embedding webvtt in mp4, therefore IMO this request is unfortunately not feasible.

And Thumbnail cover can be fully embedded in .mp4 and .mkv video files???

**Comment by mrfragger** [comment]
> ~mp4 doesn't support webvtt~
> 
> Correction: _**ffmpeg**_ doesn't support embedding webvtt in mp4, therefore IMO this request is unfortunately not feasible.

it does for mp4 just use -c:s mov_text
ffmpeg -i input.mp4 codec=-c:v libx264 -crf 28 -c:a aac -b:a 128k -c:s mov_text output.mp4

for mkv just use -c:s -c:s webvtt
ffmpeg -i input.mkv codec=-c:v libx265 -crf 28 -c:a libopus -b:a 32k -c:s webvtt output.mkv

**Comment by seproDev** [comment]
No, FFmpeg does not support muxing WebVTT in to a MP4 container. Using `-c:s mov_text` embeds the subtitles as `tx3g` (Timed Text stream) and not `wvtt` (WebVTT data). This process is lossy.

yt-dlp already uses `-c:s mov_text` when requesting to download a WebVTT file and requesting to embed that file in to a MP4.

**Comment by mrfragger** [comment]
thanks for that info.  I was not aware it strips away formatting as I purely used vtt to avoid using index # as srt does...to keep it a smaller size.
