### ISSUE TITLE
[FEATURES REQUEST] Can we use Thumbnail for Cover

### ISSUE THREAD

**Issue by 1YuvrajS** [yt-dlp/yt-dlp#11758]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Thumbnail Cover in Video can be great feature for user who want to find large collection of Music Videos like me in device, Using thumbnail can be used As Cover in Video file formats in mkv.

When user download any music video from YouTube and also has Thumbnail, user can easily to find Thumbnail Cover on the Video file.

User can decide it whether include it or exclude it.

Without use of Thumbnail can be hard to find Music Videos what user was looking for?

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
Nil
```

**Comment by Zezombye** [comment]
`--embed-thumbnail`

**Comment by 1YuvrajS** [comment]
> -embed-thumbnail

How do I use this code? Can you provide a step by step.

**Comment by bashonly** [comment]
```
yt-dlp --embed-thumbnail "URL"
```
replace `URL` with the actual url
