### ISSUE TITLE
For france.tv

### ISSUE THREAD

**Issue by lutzig** [yt-dlp/yt-dlp#11765]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

France

### Example URLs

https://www.france.tv/documentaires/documentaires-histoire/notre-dame-de-paris/

### Provide a description that is worded well enough to be understood

When I try to download from france.tv (even if I use my connecting) I receive the following message :
ERROR: Unsupported URL: https://www.france.tv/documentaires/documentaires-histoire/notre-dame-de-paris/

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp  -vU https://www.france.tv/documentaires/documentaires-histoire/notre-dame-de-paris/
[debug] Command-line config: ['-vU', 'https://www.france.tv/documentaires/documentaires-histoire/notre-dame-de-paris/']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.04.09 from yt-dlp/yt-dlp [ff0779267] (debian*)
[debug] Python 3.12.3 (CPython x86_64 64bit) - Linux-6.8.0-49-generic-x86_64-with-glibc2.39 (OpenSSL 3.0.13 30 Jan 2024, glibc 2.39)
[debug] exe versions: ffmpeg 6.1.1 (setts), ffprobe 6.1.1
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2023.11.17, mutagen-1.46.0, requests-2.31.0, secretstorage-3.3.3, sqlite3-3.45.1, urllib3-2.0.7, websockets-10.4
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Loaded 1810 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
[debug] Downloading _update_spec from https://github.com/yt-dlp/yt-dlp/releases/latest/download/_update_spec
Current version: stable@2024.04.09 from yt-dlp/yt-dlp
Latest version: stable@2024.12.06 from yt-dlp/yt-dlp
ERROR: As yt-dlp has been installed via apt, you should use that to update.  If you're on a stable release, also check backports.
[generic] Extracting URL: https://www.france.tv/documentaires/documentaires-histoire/notre-dame-de-paris/
[generic] notre-dame-de-paris: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] notre-dame-de-paris: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://www.france.tv/documentaires/documentaires-histoire/notre-dame-de-paris/
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/yt_dlp/YoutubeDL.py", line 1606, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/yt_dlp/YoutubeDL.py", line 1741, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/common.py", line 734, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/generic.py", line 2514, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.france.tv/documentaires/documentaires-histoire/notre-dame-de-paris/
```

**Comment by Trit34** [comment]
Try these, instead:

https://www.france.tv/documentaires/documentaires-histoire/6685124-notre-dame-resurrection.html
https://www.france.tv/documentaires/documentaire-histoire/1123601-notre-dame-de-paris-l-epreuve-des-siecles.html

**Comment by lutzig** [comment]
~$ yt-dlp https://www.france.tv/documentaires/documentaires-histoire/6685124-notre-dame-resurrection.html
[FranceTVSite] Extracting URL: https://www.france.tv/documentaires/documentaires-histoire/6685124-notre-dame-resurrection.html
[FranceTVSite] 6685124-notre-dame-resurrection: Downloading webpage
[FranceTV] Extracting URL: francetv:48a746aa-f0f1-4a40-a4c1-e754e68d38ad#__youtubedl_smuggle=%7B%22hostname%22%3A+%22www.france.tv%22%7D
[FranceTV] 48a746aa-f0f1-4a40-a4c1-e754e68d38ad: Downloading desktop chrome video JSON
[FranceTV] 48a746aa-f0f1-4a40-a4c1-e754e68d38ad: Downloading mobile safari video JSON
[FranceTV] 48a746aa-f0f1-4a40-a4c1-e754e68d38ad: Downloading MPD manifest
WARNING: [FranceTV] Failed to download MPD manifest: HTTP Error 403: Forbidden
[FranceTV] 48a746aa-f0f1-4a40-a4c1-e754e68d38ad: Downloading m3u8 information
WARNING: [FranceTV] Failed to download m3u8 information: HTTP Error 403: Forbidden
[FranceTV] 48a746aa-f0f1-4a40-a4c1-e754e68d38ad: Checking for geo-restriction
WARNING: Only images are available for download. use --list-formats to see them
ERROR: [FranceTV] 48a746aa-f0f1-4a40-a4c1-e754e68d38ad: Requested format is not available. Use --list-formats for a list of available formats

$ yt-dlp https://www.france.tv/documentaires/documentaire-histoire/1123601-notre-dame-de-paris-l-epreuve-des-siecles.html
[FranceTVSite] Extracting URL: https://www.france.tv/documentaires/documentaire-histoire/1123601-notre-dame-de-paris-l-epreuve-des-siecles.html
[FranceTVSite] 1123601-notre-dame-de-paris-l-epreuve-des-siecles: Downloading webpage
[FranceTV] Extracting URL: francetv:a4569cb2-d986-45cd-961e-e6d7980bee8b#__youtubedl_smuggle=%7B%22hostname%22%3A+%22www.france.tv%22%7D
[FranceTV] a4569cb2-d986-45cd-961e-e6d7980bee8b: Downloading desktop chrome video JSON
[FranceTV] a4569cb2-d986-45cd-961e-e6d7980bee8b: Downloading mobile safari video JSON
[FranceTV] a4569cb2-d986-45cd-961e-e6d7980bee8b: Downloading MPD manifest
WARNING: [FranceTV] Failed to download MPD manifest: HTTP Error 403: Forbidden
[FranceTV] a4569cb2-d986-45cd-961e-e6d7980bee8b: Downloading m3u8 information
WARNING: [FranceTV] Failed to download m3u8 information: HTTP Error 403: Forbidden
[FranceTV] a4569cb2-d986-45cd-961e-e6d7980bee8b: Checking for geo-restriction
WARNING: Only images are available for download. use --list-formats to see them
ERROR: [FranceTV] a4569cb2-d986-45cd-961e-e6d7980bee8b: Requested format is not available. Use --list-formats for a list of available formats

**Comment by Trit34** [comment]
```
$ yt-dlp -F https://www.france.tv/documentaires/documentaires-histoire/6685124-notre-dame-resurrection.html
[FranceTVSite] Extracting URL: https://www.france.tv/documentaires/documentaires-histoire/6685124-notre-dame-resurrection.html
[FranceTVSite] 6685124-notre-dame-resurrection: Downloading webpage
[FranceTV] Extracting URL: francetv:48a746aa-f0f1-4a40-a4c1-e754e68d38ad#__youtubedl_smuggle=%7B%22hostname%22%3A+%22www.france.tv%22%7D
[FranceTV] 48a746aa-f0f1-4a40-a4c1-e754e68d38ad: Downloading desktop chrome video JSON
[FranceTV] 48a746aa-f0f1-4a40-a4c1-e754e68d38ad: Downloading mobile safari video JSON
[FranceTV] 48a746aa-f0f1-4a40-a4c1-e754e68d38ad: Downloading signed dash manifest URL
[FranceTV] 48a746aa-f0f1-4a40-a4c1-e754e68d38ad: Downloading MPD manifest
[FranceTV] 48a746aa-f0f1-4a40-a4c1-e754e68d38ad: Downloading signed hls manifest URL
[FranceTV] 48a746aa-f0f1-4a40-a4c1-e754e68d38ad: Downloading m3u8 information
[info] Available formats for 48a746aa-f0f1-4a40-a4c1-e754e68d38ad:
ID                               EXT   RESOLUTION FPS │   FILESIZE   TBR PROTO │ VCODEC        VBR ACODEC     ABR ASR MORE INFO
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
spritesheets                     mhtml unknown        │                  mhtml │ images                               storyboard
dash-audio_fre=96000             m4a   audio only     │ ~ 78.71MiB   96k dash  │ audio only        mp4a.40.2  96k 48k [fr] DASH audio, m4a_dash
hls-audio-aacl-96-Audio_Français mp4   audio only     │ ~ 78.71MiB   96k m3u8  │ audio only        mp4a       96k     [fr] Audio Français
dash-video=400000                mp4   384x216     25 │ ~327.97MiB  400k dash  │ avc1.42C01E  400k video only         DASH video, mp4_dash
hls-522                          mp4   384x216     25 │ ~428.00MiB  522k m3u8  │ avc1.42C01E  522k video only
dash-video=950000                mp4   640x360     25 │ ~778.93MiB  950k dash  │ avc1.4D401F  950k video only         DASH video, mp4_dash
hls-1105                         mp4   640x360     25 │ ~906.01MiB 1105k m3u8  │ avc1.4D401F 1105k video only
dash-video=1400000               mp4   960x540     25 │ ~  1.12GiB 1400k dash  │ avc1.4D401F 1400k video only         DASH video, mp4_dash
hls-1582                         mp4   960x540     25 │ ~  1.27GiB 1582k m3u8  │ avc1.4D401F 1582k video only
dash-video=2000000               mp4   1280x720    25 │ ~  1.60GiB 2000k dash  │ avc1.64001F 2000k video only         DASH video, mp4_dash
hls-2218                         mp4   1280x720    25 │ ~  1.78GiB 2218k m3u8  │ avc1.64001F 2218k video only
dash-video=5000000               mp4   1920x1080   25 │ ~  4.00GiB 5000k dash  │ avc1.640029 5000k video only         DASH video, mp4_dash
hls-5398                         mp4   1920x1080   25 │ ~  4.32GiB 5398k m3u8  │ avc1.640029 5398k video only

```
Could it be that it is geo-restricted?

**Comment by lutzig** [comment]
As French in France, I don't think so...

I've tried with -F, too and this is what appears :+1: 

$ yt-dlp -F https://www.france.tv/documentaires/documentaires-histoire/6685124-notre-dame-resurrection.html
[FranceTVSite] Extracting URL: https://www.france.tv/documentaires/documentaires-histoire/6685124-notre-dame-resurrection.html
[FranceTVSite] 6685124-notre-dame-resurrection: Downloading webpage
[FranceTV] Extracting URL: francetv:48a746aa-f0f1-4a40-a4c1-e754e68d38ad#__youtubedl_smuggle=%7B%22hostname%22%3A+%22www.france.tv%22%7D
[FranceTV] 48a746aa-f0f1-4a40-a4c1-e754e68d38ad: Downloading desktop chrome video JSON
[FranceTV] 48a746aa-f0f1-4a40-a4c1-e754e68d38ad: Downloading mobile safari video JSON
[FranceTV] 48a746aa-f0f1-4a40-a4c1-e754e68d38ad: Downloading MPD manifest
WARNING: [FranceTV] Failed to download MPD manifest: HTTP Error 403: Forbidden
[FranceTV] 48a746aa-f0f1-4a40-a4c1-e754e68d38ad: Downloading m3u8 information
WARNING: [FranceTV] Failed to download m3u8 information: HTTP Error 403: Forbidden
[FranceTV] 48a746aa-f0f1-4a40-a4c1-e754e68d38ad: Checking for geo-restriction
WARNING: Only images are available for download. use --list-formats to see them
[info] Available formats for 48a746aa-f0f1-4a40-a4c1-e754e68d38ad:
ID           EXT   RESOLUTION │ PROTO │ VCODEC MORE INFO
─────────────────────────────────────────────────────────
spritesheets mhtml unknown    │ mhtml │ images storyboard

**Comment by bashonly** [comment]
The first URL, for a single video, is working. The URL that's not working is for a collection of videos. Are you requesting that collections be supported (and yt-dlp would download everything in the collection when you pass the URL to it)?

**Comment by lutzig** [comment]
It is working now !
Thank you !

Have a nice evening !
