### ISSUE TITLE
How do I pass login information to aria2c if I use the external download command aria2c to download YouTube?

### ISSUE THREAD

**Issue by DOSforever** [yt-dlp/yt-dlp#11760]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

如果使用外部下载命令 aria2c 下载 YouTube 该如何把登录信息传递给 aria2c？

如果不额外指定 --external-downloader-args 选项的变元，yt-dlp 自动给 aria2c 生成的选项无法进行下载。提示
>  -> [SocketCore.cc:1019] errorCode=1 SSL/TLS handshake failure: Error: 操作成功完成。

---

The options that yt-dlp automatically generates for aria2c cannot be downloaded without additionally specifying the arguments for the --external-downloader-args option. Tip.
>  -> [SocketCore.cc:1019] errorCode=1 SSL/TLS handshake failure: Error: operation completed successfully.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
I don't understand the question. Can you share complete verbose output? How can I reproduce the issue? Please elaborate

**Comment by DOSforever** [comment]
Downloading YouTube with yt-dlp requires a login, I thought that if yt-dlp calls aria2c then aria2c also needs to be logged in to YouTube, what I don't know is how aria2c logs in to Youtube. Maybe I'm wrong, I couldn't download before maybe it was a proxy server problem, but now I can download again. I'll take another look and I'll add any questions.

**Comment by seproDev** [comment]
yt-dlp passes all necessary information like cookies on to aria2c. You don't need to also pass cookies separately to aria2c.
Since you mentioned using a proxy, yes, this does seem to be a network issue. But you need to share a complete verbose log; otherwise we cannot help you.
