### ISSUE TITLE
Imgur album doesn't download

### ISSUE THREAD

**Issue by joskezelensky** [yt-dlp/yt-dlp#11762]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Belgium

### Provide a description that is worded well enough to be understood

doesn't error and loads correctly but doesn't download

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://imgur.com/a/special-screenshots-NklBBYG']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.12.06 from yt-dlp/yt-dlp [4bd265539] (pip)
[debug] Python 3.13.0 (CPython x86_64 64bit) - Linux-5.4.241-20682-ga1a694ca87ae-x86_64-AMD_3015Ce_with_Radeon_Graphics-with-glibc2.35 (OpenSSL 3.4.0 22 Oct 2024, glibc 2.35)
[debug] exe versions: ffmpeg b08d796 (fdk,setts), ffprobe b08d796, rtmpdump 2.4
[debug] Optional libraries: sqlite3-3.47.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Loaded 1837 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.12.06 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.12.06 from yt-dlp/yt-dlp)
[imgur:album] Extracting URL: https://imgur.com/a/special-screenshots-NklBBYG
[imgur:album] NklBBYG: Downloading JSON metadata
[download] Downloading playlist: Special Screenshots
[imgur:album] Playlist Special Screenshots: Downloading 0 items
[download] Finished downloading playlist: Special Screenshots
```

**Comment by seproDev** [comment]
The album contains no videos. yt-dlp is for downloading video/audio, not arbitrary media. Closing as out of scope.

**Comment by joskezelensky** [comment]
> The album contains no videos. yt-dlp is for downloading video/audio, not arbitrary media. Closing as out of scope.

oh i did not now that
thought that it was also for images

**Comment by seproDev** [comment]
You can maybe take a look at https://github.com/mikf/gallery-dl which might fit your needs.
