### ISSUE TITLE
"[youtube] jNOEntzvJ48: Requested format is not available. Use --list-formats for a list of available formats"

### ISSUE THREAD

**Issue by freywald** [yt-dlp/yt-dlp#11769]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Germany

### Provide a description that is worded well enough to be understood

[info] Available formats for jNOEntzvJ48:
ID  EXT   RESOLUTION FPS CH │  FILESIZE  TBR PROTO │ VCODEC       VBR ACODEC     ASR MORE INFO
──────────────────────────────────────────────────────────────────────────────────────────────────────────
sb2 mhtml 48x27        0    │                mhtml │ images                          storyboard
sb1 mhtml 60x45        0    │                mhtml │ images                          storyboard
sb0 mhtml 120x90       0    │                mhtml │ images                          storyboard
160 mp4   192x144     25    │   5.59MiB  27k https │ avc1.4D400B  27k video only     144p, IOS, mp4_dash
134 mp4   480x360     25    │  11.76MiB  56k https │ avc1.4D4015  56k video only     360p, IOS, mp4_dash
18  mp4   480x360     25  2 │  32.15MiB 154k https │ avc1.42001E      mp4a.40.2  44k 360p, IOS
243 webm  480x360     25    │  19.73MiB  95k https │ vp9          95k video only     360p, MWEB, webm_dash
135 mp4   640x480     25    │  23.58MiB 113k https │ avc1.4D401E 113k video only     480p, IOS, mp4_dash

I only need the audio, but this video is special. Only the video source exists, I guess --extract-audio needs to be more intelligent; or does a special command line switch to handle this case already exist? 

This case can be handled by: 
- automatically download the video
- save it on disk
- extract the audio
- only keep the audio

I'm surprised --extract-audio does not handle this case, I think it should.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] $ yt-dlp -f bestaudio --extract-audio -vU -- https://www.youtube.com/watch?v=jNOEntzvJ48
[debug] Command-line config: ['-f', 'bestaudio', '--extract-audio', '-vU', '--', 'https://www.youtube.com/watch?v=jNOEntzvJ48']
[debug] User config "/home/ju/.config/yt-dlp/config": ['--write-description', '--write-info-json', '--add-metadata', '--embed-subs', '--ignore-errors', '--no-overwrites', '-o', '%(channel)s/%(title).150B/%(fulltitle).200Bs. – %(id)s.%(ext)s', '--concurrent-fragments', '1', '--compat-options', 'multistreams', '--compat-options', 'no-youtube-channel-redirect', '--compat-options', 'no-clean-infojson', '--cookies=/home/ju/.config/yt-dlp/cookies.txt', '--extractor-args', 'youtubetab:skip=webpage,authcheck', '--lazy', '--download-archive', '/home/ju/.config/yt-dlp/download-index.txt']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.12.06.161513 from yt-dlp/yt-dlp-nightly-builds [6fef82402] (zip)
[debug] Compatibility options: multistreams, no-youtube-channel-redirect, no-clean-infojson
[debug] Python 3.12.7 (CPython x86_64 64bit) - Linux-6.11.0-8-generic-x86_64-with-glibc2.40 (OpenSSL 3.3.1 4 Jun 2024, glibc 2.40)
[debug] exe versions: ffmpeg 7.1 (setts), ffprobe 7.1
[debug] Optional libraries: brotli-1.1.0, certifi-2024.08.30, mutagen-1.47.0, requests-2.32.3, secretstorage-3.3.3, sqlite3-3.46.1, urllib3-2.0.7
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Loaded 1837 extractors
[debug] Loading archive file '/home/ju/.config/yt-dlp/download-index.txt'
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.12.06.161513 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.12.06.161513 from yt-dlp/yt-dlp-nightly-builds)
[youtube] Extracting URL: https://www.youtube.com/watch?v=jNOEntzvJ48
[youtube] jNOEntzvJ48: Downloading webpage
[youtube] jNOEntzvJ48: Downloading ios player API JSON
[youtube] jNOEntzvJ48: Downloading mweb player API JSON
[debug] Loading youtube-nsig.62ccfae7 from cache
[debug] [youtube] Decrypted nsig ODz4UyiaJcSiW_t3M3B => d0-It-eyAeR13A
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec, channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
ERROR: [youtube] jNOEntzvJ48: Requested format is not available. Use --list-formats for a list of available formats
Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1624, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1780, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1839, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 2973, in process_video_result
    raise ExtractorError(
yt_dlp.utils.ExtractorError: [youtube] jNOEntzvJ48: Requested format is not available. Use --list-formats for a list of available formats
```

**Comment by seproDev** [comment]
`--extract-audio` is exactly the command you need. Just don't pass a `-f` option.
