### ISSUE TITLE
Speed up recode-video

### ISSUE THREAD

**Issue by Jamu2800** [yt-dlp/yt-dlp#11776]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I am trying to download a very good sound quality file with the following command.
```PowerShell
> .\yt-dlp.exe --recode-video flac  --ffmpeg-location .\ffmpeg-master-latest-win64-gpl\bin https://youtu.be/XXX
```
Similarly, to download a very good video, use the following command
```PowerShell
> .\yt-dlp.exe --recode-video mp4 --ffmpeg-location .\ffmpeg-master-latest-win64-gpl\bin https://youtu.be/XXX
```

My problem is high CPU usage and the encoding never ends.
It's not that it never ends, it takes a long time.
![image](https://github.com/user-attachments/assets/5d1f7d30-30bd-43fc-9337-9bd2082ba465)

I learned about this option from the following issue, but when I try to use it, I get an error.
https://github.com/yt-dlp/yt-dlp/issues/11200
```PowerShell
> .\yt-dlp.exe --recode-video flac  --ffmpeg-location .\ffmpeg-master-latest-win64-gpl\bin --postprocessor-args  '-c:v h264_nvenc' https://youtu.be/XXX
WARNING: Post-Processor arguments given without specifying name. The arguments will be given to all post-processors
[youtube] Extracting URL: https://youtu.be/XXX
[youtube] J8PUUv4LFkQ: Downloading webpage
[youtube] J8PUUv4LFkQ: Downloading ios player API JSON
[youtube] J8PUUv4LFkQ: Downloading mweb player API JSON
[youtube] J8PUUv4LFkQ: Downloading m3u8 information
[info] J8PUUv4LFkQ: Downloading 1 format(s): 399+251
[download] Destination: XXX.mp4
[download] 100% of  117.80MiB in 00:00:04 at 28.50MiB/s
[download] Destination: XXX.webm
[download] 100% of    3.37MiB in 00:00:00 at 29.29MiB/s
[Merger] Merging formats into "XXX.webm"
ERROR: Postprocessing: Conversion failed!
```

I understand that it is probably my environment, but I don't know how to solve the problem. I would like to know.

### My PC
- OS: Windows 11 (64-bit)
- yt-dlp version: 2024.12.06
- CPU: Intel core i9 13900kf
- GPU: NVIDIA RTX 3080

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
> .\yt-dlp.exe -vU
[debug] Command-line config: ['-vU']
[debug] Encodings: locale cp932, fs utf-8, pref cp932, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.12.03 from yt-dlp/yt-dlp [2b67ac300] (win_exe)
[debug] Python 3.10.11 (CPython AMD64 64bit) - Windows-10-10.0.26100-SP0 (OpenSSL 1.1.1t  7 Feb 2023)
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.21.0, brotli-1.1.0, certifi-2024.08.30, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.40.1, urllib3-2.2.3, websockets-14.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1837 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
[debug] Downloading _update_spec from https://github.com/yt-dlp/yt-dlp/releases/latest/download/_update_spec
[debug] Downloading SHA2-256SUMS from https://github.com/yt-dlp/yt-dlp/releases/download/2024.12.06/SHA2-256SUMS
Current version: stable@2024.12.03 from yt-dlp/yt-dlp
Latest version: stable@2024.12.06 from yt-dlp/yt-dlp
Current Build Hash: 219eaf463f31be34af73926c6bddc38f799ff28a73965f12a0a794846e7221c4
Updating to stable@2024.12.06 from yt-dlp/yt-dlp ...
[debug] Downloading yt-dlp.exe from https://github.com/yt-dlp/yt-dlp/releases/download/2024.12.06/yt-dlp.exe
Updated yt-dlp to stable@2024.12.06 from yt-dlp/yt-dlp
```

**Comment by seproDev** [comment]
When re-encoding the entire file needs to be decoded first (pretty fast) and then needs to be encoded again (very slow).
You only ever want to do this if you must. Why are you exactly re-encoding the downloaded formats?
Converting to flac in this case only increases the filesize. Converting lossy to lossless can't increase the audio quality.
If you are converting to mp4, do you maybe want to download a mp4 video with h264 video and aac audio? In that case consider using `-S vcodec:h264,res,acodec:aac` instead.

**Comment by Jamu2800** [comment]
Thanks.
I was able to download the video successfully with the command you gave me.

I also improved on that command and downloaded the music with the following command.
```PowerShell
> .\yt-dlp.exe -x -S acodec:aac --audio-format aac --ffmpeg-location .\ffmpeg-master-latest-win64-gpl\bin https://youtu.be/XXX
[youtube] Extracting URL: https://youtu.be/XXX
[youtube] J8PUUv4LFkQ: Downloading webpage
[youtube] J8PUUv4LFkQ: Downloading ios player API JSON
[youtube] J8PUUv4LFkQ: Downloading mweb player API JSON
[youtube] J8PUUv4LFkQ: Downloading m3u8 information
[info] J8PUUv4LFkQ: Downloading 1 format(s): 140
[download] Destination: XXX.m4a
[download] 100% of    3.68MiB in 00:00:00 at 12.32MiB/s
[FixupM4a] Correcting container of "XXX.m4a"
[ExtractAudio] Not converting audio XXX.m4a; file is already in target format aac
```

However, the output file is XXX.m4a.
Do I need to use the “-o” option to make it XXX.aac?
Or does this fail to format the aac properly?

**Comment by seproDev** [comment]
I would generally recommend keeping m4a files instead of using raw aac bitstreams. You can, for example, embed metadata like the title and thumbnail in m4a files.
I don't think it is currently possible to directly save aac files with yt-dlp.

**Comment by Jamu2800** [comment]
I did not understand AAC very well.
I did some research on m4a and understood that it is the aac extension.
So I think I was able to solve my problem.
Thank you for your patience to the end!
