### ISSUE TITLE
Automating youtube cookie export

### ISSUE THREAD

**Issue by twilson90** [yt-dlp/yt-dlp#11773]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

In the last few weeks since OAuth2 stopped working, I've been having to manually export a cookie file from my browser (on a separate chrome profile that I only use for this purpose) every week or so using the 'Get Cookies.txt Locally' Chrome addon.
The cookies expire quite quickly and I'd like to implement an automated solution that will export a new cookie every day.
The cookie is used with a headless server.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
Are you following this guide https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies ?

**Comment by twilson90** [comment]
> Are you following this guide https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies ?

Yes, although I haven't tried using a PO Token.

**Comment by helpimnotdrowning** [comment]
You could stick something lile this into a cronjob:
`yt-dlp --cookies-from-browser <your browser> --cookies <output filepath>`

I use this to help `ytarchive` do live membership streams since it can't get cookies on its own and I haven't had any issues.

It will always give back an error code since there's no URL, so watch out for that.

**Comment by twilson90** [comment]
> I'm starting to think the easiest solution is to just create a new dummy Google/YouTube account and call yt-dlp with --username and --password. Who cares if it somehow gets hacked. And is it really that much unsafer than using cookies? If someone can find your username/password in your code or command line history, they can probably also find your current cookie file and use it.

After weeks of struggling with this you're the first to mention username and password authorization. Will give this a go, thanks!

**Comment by bashonly** [comment]
The youtube extractor doesn't support login via username and password

**Comment by devkulemannege** [comment]
I've made a system to do exactly this. Maybe [check it out](https://github.com/devkulemannege/yt-dlp-Cookie-Sync) and give it a try.
