### ISSUE TITLE
 NSFW tweet requires authentication

### ISSUE THREAD

**Issue by jnxyatmjx** [yt-dlp/yt-dlp#11770]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

US

### Provide a description that is worded well enough to be understood

download with cookies paramter but error

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['--cookies', './twitter', 'https://x.com/allvideodld/status/1864320115921310120?t=fcgxGtr__B6GuQ9PhtHXOw&s=09', '-o', '%(id)s.10B.%(ext)s', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.12.06 from yt-dlp/yt-dlp [4bd265539] (pip)
[debug] Python 3.9.2 (CPython x86_64 64bit) - Linux-5.10.0-33-amd64-x86_64-with-glibc2.31 (OpenSSL 1.1.1w  11 Sep 2023, glibc 2.31)
[debug] exe versions: ffmpeg 6.1-static (setts), ffprobe 6.1-static
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2023.11.17, mutagen-1.47.0, requests-2.32.3, sqlite3-3.34.1, urllib3-2.1.0, websockets-12.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Loaded 1837 extractors
[twitter] Extracting URL: https://x.com/allvideodld/status/1864320115921310120?t=fcgxGtr__B6GuQ9PhtHXOw&s=09
[twitter] 1864320115921310120: Downloading guest token
[twitter] 1864320115921310120: Downloading GraphQL JSON
ERROR: [twitter] 1864320115921310120: NSFW tweet requires authentication. Use --cookies, --cookies-from-browser, --username and --password, --netrc-cmd, or --netrc (twitter) to provide account credentials. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies
  File "/et/teleg/py/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 742, in extract
    ie_result = self._real_extract(url)
  File "/et/teleg/py/lib/python3.9/site-packages/yt_dlp/extractor/twitter.py", line 1422, in _real_extract
    status = self._extract_status(twid)
  File "/et/teleg/py/lib/python3.9/site-packages/yt_dlp/extractor/twitter.py", line 1400, in _extract_status
    status = self._graphql_to_legacy(self._call_graphql_api(self._GRAPHQL_ENDPOINT, twid), twid)
  File "/et/teleg/py/lib/python3.9/site-packages/yt_dlp/extractor/twitter.py", line 1277, in _graphql_to_legacy
    self.raise_login_required('NSFW tweet requires authentication')
  File "/et/teleg/py/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 1258, in raise_login_required
    raise ExtractorError(msg, expected=True)
```

**Comment by bashonly** [comment]
I can't reproduce the issue. Looks like the cookiefile may not have the relevant cookies.

Can you show the output of this command?

```bash
cat ./twitter | cut -f1-6 -d$'\t'
```

(It should print the contents of your cookiefile minus the cookies' values)

**Comment by jnxyatmjx** [comment]
> I can't reproduce the issue. Looks like the cookiefile may not have the relevant cookies.
> 
> Can you show the output of this command?
> 
> ```shell
> cat ./twitter | cut -f1-6 -d$'\t'
> ```
> 
> (It should print the contents of your cookiefile minus the cookies' values)

I think cookie file is correct.   Because the URL https://x.com/CMGS1988/status/1865746232305750222 can download.

**Comment by bashonly** [comment]
> I think cookie file is correct. Because the URL https://x.com/CMGS1988/status/1865746232305750222 can download.

That's not an NSFW tweet. You don't need authentication to download it. If you don't provide the info I am asking for then I can't help you

**Comment by jnxyatmjx** [comment]
> It should print the contents of your cookiefile minus the cookies' values)

.twitter.com    TRUE    /       TRUE    1748894454      auth_token
.twitter.com    TRUE    /       FALSE   1748894454      ct0
.twitter.com    TRUE    /       FALSE   1748680345      guest_id
.twitter.com    TRUE    /       TRUE    1799949137      guest_id_ads
.twitter.com    TRUE    /       TRUE    1799949137      guest_id_marketing
.twitter.com    TRUE    /       TRUE    1748894454      kdt
.twitter.com    TRUE    /       TRUE    1799949137      personalization_id
.twitter.com    TRUE    /       TRUE    1799949137      twid
twitter.com     FALSE   /       FALSE   0       lang

**Comment by bashonly** [comment]
you are exporting cookies from twitter.com instead of x.com

**Comment by jnxyatmjx** [comment]
> you are exporting cookies from twitter.com instead of x.com

This mean I need export cookies from x.com, right?

**Comment by bashonly** [comment]
yes

**Comment by jnxyatmjx** [comment]
I remeber export from x.com and what operation will yt-dlp do to change the cookies?

**Comment by bashonly** [comment]
Just pass the exported x.com cookiefile to yt-dlp like you were doing with the twitter cookies originally

**Comment by jnxyatmjx** [comment]
> Just pass the exported x.com cookiefile to yt-dlp like you were doing with the twitter cookies originally

OK, thank you very much.
