### ISSUE TITLE
[youtube] Cannot get index py in: {} (caused by KeyError('py'))

### ISSUE THREAD

**Issue by torfinli** [yt-dlp/yt-dlp#11798]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

China

### Provide a description that is worded well enough to be understood

Sometime I download video with a cookie file, I get this error. But I can successfully get mp4 format without cookie file.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp --no-progress --no-mtime --cookies cookies.txt -o video.mp4 --write-info-json --skip-download https://www.youtube.com/watch?v=tziNYGCaR5Q --list-formats -vU
[debug] Command-line config: ['--no-progress', '--no-mtime', '--cookies', '/app/tmp/import/runtime/cookies.txt', '-o', './tmp/import/118718fc-4853-4f2f-b55a-3e819e6210e9/1/YT_tziNYGCaR5Q/source/video-raw.video', '--write-info-json', '--skip-download', 'https://www.youtube.com/watch?v=tziNYGCaR5Q', '--list-formats', '-vU']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.12.06 from yt-dlp/yt-dlp [4bd265539] (pip)
[debug] Python 3.10.12 (CPython x86_64 64bit) - Linux-6.8.0-1015-gcp-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg 7.0.1 (fdk,setts), ffprobe 7.0.1
[debug] Optional libraries: Cryptodome-3.21.0, brotli-1.1.0, certifi-2024.08.30, mutagen-1.47.0, requests-2.32.3, sqlite3-3.37.2, urllib3-2.2.3, websockets-13.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1837 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.12.06 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.12.06 from yt-dlp/yt-dlp)
[youtube] Extracting URL: https://www.youtube.com/watch?v=tziNYGCaR5Q
[youtube] tziNYGCaR5Q: Downloading webpage
[debug] [youtube] Extracted SAPISID cookie
[youtube] tziNYGCaR5Q: Downloading web creator player API JSON
[youtube] tziNYGCaR5Q: Downloading mweb player API JSON
[debug] [youtube] Extracting signature function js_2f1832d2_112
[youtube] tziNYGCaR5Q: Downloading player 2f1832d2
WARNING: [youtube] tziNYGCaR5Q: Signature extraction failed: Some formats may be missing
[debug] [youtube] Cannot get index py in: {} (caused by KeyError('py')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[debug] [youtube] Extracting signature function js_2f1832d2_108
WARNING: Only images are available for download. use --list-formats to see them
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec, channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[info] Available formats for tziNYGCaR5Q:
ID  EXT   RESOLUTION FPS │ PROTO │ VCODEC MORE INFO
────────────────────────────────────────────────────
sb2 mhtml 25x45        1 │ mhtml │ images storyboard
sb3 mhtml 48x27        2 │ mhtml │ images storyboard
sb1 mhtml 50x90        1 │ mhtml │ images storyboard
sb0 mhtml 101x180      1 │ mhtml │ images storyboard
```

**Comment by Boya-Na** [comment]
url: https://youtube.com/shorts/haImbK2TShY, have same problem

**Comment by torfinli** [comment]
I would like to provide some additional information. I have another account that rarely experiences this type of error with its cookies, but I have used another new YouTube account where this error occurs frequently
