### ISSUE TITLE
Get all media [videos+images] from Instagram carousel? 

### ISSUE THREAD

**Issue by mostafa-norouzi** [yt-dlp/yt-dlp#11792]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Hi,

I can see that yt-dlp can get videos from an Instagram carousel: 
yt-dlp -x -R 3 -r 500K https://instagram.com/p/1111111

But is there anyway to get all slide media (even images)?
I saw in somewhere that --cookie switch can do something about it but it wasn't obvious. 

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[Instagram] Extracting URL: https://instagram.com/p/1111111
[Instagram] C4GhVSIqClB: Setting up session
[Instagram] C4GhVSIqClB: Downloading JSON metadata
[download] Downloading playlist: Post by birdsonearth
[Instagram] Playlist Post by birdsonearth: Downloading 2 items of 2
[download] Downloading item 1 of 2
[info] C4GhR8sqVB3: Downloading 1 format(s): 0
[download] Destination: Video 1 [C4GhR8sqVB3].mp4
[download] 100% of  684.84KiB in 00:00:01 at 488.57KiB/s
[ExtractAudio] Destination: Video 1 [C4GhR8sqVB3].m4a
Deleting original file Video 1 [C4GhR8sqVB3].mp4 (pass -k to keep)
[download] Downloading item 2 of 2
[info] C4GhTZRKQL_: Downloading 1 format(s): 0
[download] Destination: Video 2 [C4GhTZRKQL_].mp4
[download] 100% of    1.05MiB in 00:00:02 at 492.68KiB/s
[ExtractAudio] Destination: Video 2 [C4GhTZRKQL_].m4a
Deleting original file Video 2 [C4GhTZRKQL_].mp4 (pass -k to keep)
[download] Finished downloading playlist: Post by birdsonearth
```

**Comment by bashonly** [comment]
yt-dlp is not an image downloader. You want to use something like [gallery-dl](https://github.com/mikf/gallery-dl) for that
