### ISSUE TITLE
Any way to download only 360° videos from youtube?

### ISSUE THREAD

**Issue by JamesR98** [yt-dlp/yt-dlp#11790]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I'm looking to download only 360° videos (not to be confused with 360p videos) from youtube, mainly via a channel page or a general search. You can see an example of a 360° here:

https://www.youtube.com/watch?v=PeIiXiEdz-M

Looking in the info.json downloaded I'm not seeing any specific flag that shows it's a 360 video.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
try `--extractor-arg "youtube:player_client=android_vr"`

maybe related #9903

**Comment by JamesR98** [comment]
> try `--extractor-arg "youtube:player_client=android_vr"`
> 
> maybe related #9903

Maybe I am misunderstanding your answer but I don't think this answers my question. I attempted to use that argument to see if in the json any value related to it being a 360° video was there and I did not see any. I'm looking for a way to filter only 360° videos from a search or channel page, something to use in --match-filter.

**Comment by bashonly** [comment]
Not possible AFAIK
