### ISSUE TITLE
[Site Request] Bilibili Playlist

### ISSUE THREAD

**Issue by pxssy** [yt-dlp/yt-dlp#118]
## Checklist

- [X] I'm reporting a site feature request
- [X] I've verified that I'm running yt-dlp version **2021.02.24**
- [X] I've searched the bugtracker for similar site feature requests including closed ones

## Description

I see you've implemented channel downloads, something not even annie can do. However i'd like to request for a playlist download like annie. for example this link https://www.bilibili.com/video/BV1bK411W797 has multiple videos, suffixed with https://www.bilibili.com/video/BV1bK411W797?p=1

Possible for a switch to download all of them at once?

**Comment by pukkandan** [comment]
> something not even annie can do

annie?

**Comment by animelover1984** [comment]
I should be able to start working on this next weekend if no one else wants to.

> > something not even annie can do
> 
> annie?
another video downloader, https://github.com/iawia002/annie

**Comment by pukkandan** [comment]
I am not very familiar with bilibili. Can you explain to me how this multiple videos thing works?
Does `https://www.bilibili.com/video/BV1bK411W797` point to both the video and the playlist? Is there any separate URL for one or the other?

> Possible for a switch to download all of them at once?

Adding a switch for this seems inelegant since no other extractor would make use of it. Any other ideas how to implement this? Maybe `--no-playlist` and `--yes-playlist` can be used?

> I should be able to start working on this next weekend if no one else wants to.

That would be awesome

**Comment by pxssy** [comment]
> I should be able to start working on this next weekend if no one else wants to.
> 
> > > something not even annie can do
> > 
> > 
> > annie?
> 
> another video downloader, https://github.com/iawia002/annie
> 
> Also: are you archiving from bilibili? If you don't mind, pm me on discord: Otoman#6721

I'm not quite archiving, just that some channels have content that i really like and downloading 1 by 1 is quite tedious. Are you running a project to archive bilibili?



> I am not very familiar with bilibili. Can you explain to me how this multiple videos thing works?
> Does `https://www.bilibili.com/video/BV1bK411W797` point to both the video and the playlist? Is there any separate URL for one or the other?
> 
> > Possible for a switch to download all of them at once?
> 
> Adding a switch for this seems inelegant since no other extractor would make use of it. Any other ideas how to implement this? Maybe `--no-playlist` and `--yes-playlist` can be used?
> 
> > I should be able to start working on this next weekend if no one else wants to.
> 
> That would be awesome

The site doesn't seem to distinguish which videos are part of a playlist or not, at least not from the url. The base link https://www.bilibili.com/video/BV1bK411W797 points to the video and the playlist linked to it, there isn't a direct link to the playlist, except that adding ?p=1 ?p=2 ?p=3 etc to the end will link to the 1st, 2nd, 3rd videos of the playlist

**Comment by candrapersada** [comment]
but not working in https://www.bilibili.tv/id/video/2042374711?bstar_from=bstar-web.ugc-video-detail.playlist.all
