### ISSUE TITLE
The `uploader_id` template does not print asian characters or letters with diacritical marks on the yt site.

### ISSUE THREAD

**Issue by iXDXD** [yt-dlp/yt-dlp#11816]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Provide a description that is worded well enough to be understood

The template `uploader_id` doesn't print asian characters or letters with diacritical marks on the yt site. While the template `uploader` does.

_Example Channel URL:_
1. https://www.youtube.com/@으아-v1k
2. https://www.youtube.com/c/CONTROLMÁS-SUILERALTAMIRANO

_Example Command:_
`yt-dlp -o "./%(uploader)s %(uploader_id)s/Videos/%(upload_date)s %(uploader_id)s %(title)s [%(id)s].%(ext)s" "Example_Channel_URL"`

_Output:_ 
Name of the created folders
1. `ㅇㅇ#`
2. `Suiler Altamirano - Control + NA`

Using the `--print` argument.

_Command:_
`yt-dlp -vU --print uploader,uploader_id "https://www.youtube.com/shorts/18NGQq7p3LY"`

_Ouput:_
```
ㅇㅇ
NA
```

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--print', 'uploader,uploader_id', 'https://www.youtube.com/shorts/18NGQq7p3LY']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.12.13 from yt-dlp/yt-dlp [542166962] (win_exe)
[debug] Python 3.10.11 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1t  7 Feb 2023)
[debug] exe versions: ffmpeg 2024-07-07-git-0619138639-full_build-www.gyan.dev (setts), ffprobe 2024-07-07-git-0619138639-full_build-www.gyan.dev, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.21.0, brotli-1.1.0, certifi-2024.08.30, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.40.1, urllib3-2.2.3, websockets-14.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Extractor Plugins: 
[debug] Post-Processor Plugins: 
[debug] Plugin directories: []
[debug] Loaded 1839 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.12.13 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.12.13 from yt-dlp/yt-dlp)
[youtube] Extracting URL: https://www.youtube.com/shorts/18NGQq7p3LY
[youtube] 18NGQq7p3LY: Downloading webpage
[youtube] 18NGQq7p3LY: Downloading ios player API JSON
[youtube] 18NGQq7p3LY: Downloading mweb player API JSON
[debug] Loading youtube-nsig.f8f53e1a from cache
[debug] [youtube] Decrypted nsig uq0JCV23R3b7atLWxO4 => 9vigDFaIWXoXwA
[debug] Loading youtube-nsig.f8f53e1a from cache
[debug] [youtube] Decrypted nsig -T_DSjpoOPpyTJKSn0b => N9TXRFGASCEhbA
[youtube] 18NGQq7p3LY: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec, channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 18NGQq7p3LY: Downloading 1 format(s): 315+251
ㅇㅇ
NA
```

**Comment by bashonly** [comment]
This looks like two distinct, though semi-related, issues

1. The extractor fails to return an `uploader_id` for the first channel's videos because the non-ASCII characters are being percent-encoded, both by yt-dlp and by Youtube. We would need to `urllib.parse.unquote` the values before regex searching for the `@`-handle:

```diff
diff --git a/yt_dlp/extractor/youtube.py b/yt_dlp/extractor/youtube.py
index fd9c7107c..6822aef8c 100644
--- a/yt_dlp/extractor/youtube.py
+++ b/yt_dlp/extractor/youtube.py
@@ -518,11 +518,12 @@ def ucid_or_none(self, ucid):
         return self._search_regex(rf'^({self._YT_CHANNEL_UCID_RE})$', ucid, 'UC-id', default=None)
 
     def handle_or_none(self, handle):
-        return self._search_regex(rf'^({self._YT_HANDLE_RE})$', handle, '@-handle', default=None)
+        return self._search_regex(rf'^({self._YT_HANDLE_RE})$', urllib.parse.unquote(handle),
+                                  '@-handle', default=None)
 
     def handle_from_url(self, url):
         return self._search_regex(rf'^(?:https?://(?:www\.)?youtube\.com)?/({self._YT_HANDLE_RE})',
-                                  url, 'channel handle', default=None)
+                                  urllib.parse.unquote(url), 'channel handle', default=None)
 
     def ucid_from_url(self, url):
         return self._search_regex(rf'^(?:https?://(?:www\.)?youtube\.com)?/({self._YT_CHANNEL_UCID_RE})',
```

2. The second channel does have the same percent-encoding thing going on, but more importantly, it does not have any `@`-handle. When I print the values we pass to `handle_or_none()` and `handle_from_url()`, this is the output:

```
http://www.youtube.com/c/CONTROLM%C3%81S-SUILERALTAMIRANO
/c/CONTROLM%C3%81S-SUILERALTAMIRANO
```

And since the channel has no `@`-handle, the uploader also does not have a display name in the comments:
![example](https://github.com/user-attachments/assets/0b7bfa3b-4fc2-4ff0-a20c-26ce7f4c1bad)

@coletdjnz Any ideas about this?

**Comment by coletdjnz** [comment]
> This looks like two distinct, though semi-related, issues
> 
> 1. The extractor fails to return an `uploader_id` for the first channel's videos because the non-ASCII characters are being percent-encoded, both by yt-dlp and by Youtube. We would need to `urllib.parse.unquote` the values before regex searching for the `@`-handle:
> 
> ```diff
> diff --git a/yt_dlp/extractor/youtube.py b/yt_dlp/extractor/youtube.py
> index fd9c7107c..46b0eafda 100644
> --- a/yt_dlp/extractor/youtube.py
> +++ b/yt_dlp/extractor/youtube.py
> @@ -518,11 +518,12 @@ def ucid_or_none(self, ucid):
>          return self._search_regex(rf'^({self._YT_CHANNEL_UCID_RE})$', ucid, 'UC-id', default=None)
>  
>      def handle_or_none(self, handle):
> -        return self._search_regex(rf'^({self._YT_HANDLE_RE})$', handle, '@-handle', default=None)
> +        return self._search_regex(rf'^({self._YT_HANDLE_RE})$', urllib.parse.unquote(handle or ''),
> +                                  '@-handle', default=None)
>  
>      def handle_from_url(self, url):
>          return self._search_regex(rf'^(?:https?://(?:www\.)?youtube\.com)?/({self._YT_HANDLE_RE})',
> -                                  url, 'channel handle', default=None)
> +                                  urllib.parse.unquote(url or ''), 'channel handle', default=None)
>  
>      def ucid_from_url(self, url):
>          return self._search_regex(rf'^(?:https?://(?:www\.)?youtube\.com)?/({self._YT_CHANNEL_UCID_RE})',
> ```
> 
> 2. The second channel does have the same percent-encoding thing going on, but more importantly, it does not have any `@`-handle. When I print the values we pass to `handle_or_none()` and `handle_from_url()`, this is the output:
> 
> ```
> http://www.youtube.com/c/CONTROLM%C3%81S-SUILERALTAMIRANO
> /c/CONTROLM%C3%81S-SUILERALTAMIRANO
> ```
> 
> And since the channel has no `@`-handle, the uploader also does not have a display name in the comments:
> ![example](https://github.com/user-attachments/assets/0b7bfa3b-4fc2-4ff0-a20c-26ce7f4c1bad)
> 
> @coletdjnz Any ideas about this?

If there is no handle, then there is no uploader_id/uploader extracted. This is **intentional** so the behaviour for 2 is expected.

**Comment by iXDXD** [comment]
In the second case I think it's fine to print `/c/CONTROLMMAS-SUILERALTAMIRANO` as it would imply that there is no identifier. But changing the `/` character to `⧸` for file and folder names. I don't know if it's possible to do that but it's just a comment.

So is there a solution for both? Should I wait for the next update?

**Comment by bashonly** [comment]
There is a solution for 1, but the lack of `uploader_id` for the 2nd case is intentional, so there will be no fix for that

**Comment by iXDXD** [comment]
I understand. The first case solution is the one I need the most at the moment so it's Ok. So I have to wait for the next update for the first case solution?

**Comment by bashonly** [comment]
@iXDXD After #11818 is merged, you'll be able to run `yt-dlp --update-to master`to get the fix. Or else wait until the next stable release

**Comment by iXDXD** [comment]
Great. Many thanks!!
