### ISSUE TITLE
[Question] Native HLS downlaoder destroys downloaded files in case of netowkr error?

### ISSUE THREAD

**Issue by DerBunteBall** [yt-dlp/yt-dlp#1181]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

Hello all,

is it the normal and wanted behaviour that the HLS native downlaoder destroys downloads by overwriting in a case of network errors?

```
[download] Destination: [GER] NEW WORLD RELEASE 08_00 Uhr - Ultra Grind auf Arbeitsamt angelehnt 2021-09-28 08_54 [100095501_100095501_1632811897].flv
[download] 771.15GiB at  1.21MiB/s (--:--:--)[download] Got server HTTP error: [Errno 104] Connection reset by peer. Retrying (attempt 1 of 10) ...
[download] Unable to resume
[download] Destination: [GER] NEW WORLD RELEASE 08_00 Uhr - Ultra Grind auf Arbeitsamt angelehnt 2021-09-28 08_54 [100095501_100095501_1632811897].flv
[download] 100% of 715.32KiB in --:--:--
```

If the network dies - also if this happens at server side - the downloaded file gets overwritten instead of creating a new one like _2 or .2 or so. Sometimes this will lead to the little crap file but eventually something more. The old (first) file should be useable.

Is this wanted?

Fun fact: the time info explodes at 100:00:00h.

Best Regards

**Comment by pukkandan** [comment]
No, it should normally resume. Show the full verbose log so that I can try to reproduce

**Comment by DerBunteBall** [comment]
That's sadly not possible. It was a livestream downlaod. So I can rerun the command by using -v.

I think it's happening when something on network get's wrong. I think the stream stopped a second or so and the HLS server in fact started a new .m3u8 file/context. Had similiar behaviour in such a situation. This happend this night. Just saw as I reattached the tmux session.

Best Regards

**Comment by pukkandan** [comment]
Don't download livestreams with the native downloader. If it is for a supported site, yt-dlp should have automatically detected this and used ffmpeg. If it is a generic URL, you need to pass `--downloader ffmpeg`

**Comment by DerBunteBall** [comment]
It's Trovo this site is supported but uses HLS-Native as default. Will edit my livestream config to force ffmpeg.

Best Regards

**Comment by pukkandan** [comment]
Trovo is not an HLS download and doesn't seem like it can be resumed. The only solution here is to set `--retries 0` so that yt-dlp doesn't try to redownload and overwrite the existing file

**Comment by DerBunteBall** [comment]
As far as I can see trovo.live uses HLS technology for livestreams and VODs.

Capturing a livestream with forcing ffmpeg also works.

The Trovo Extractor uses HLS native by default always. Unimportant whether it's a livestream or a VOD.

Best Regards

**Comment by DerBunteBall** [comment]
Ok. So it seems like the VODs are HLS and the livestream is a changing .flv file or something like that.

Capturing with using `--downloader ffmpeg` also works for a livestream.

A VOD gives this (I'm actually using aria2c for all static videos):

```
yt-dlp "https://trovo.live/video/ltv-100903204_100903204_3701925925008943921?ltab=videos"
[TrovoVod] ltv-100903204_100903204_3701925925008943921: Downloading JSON metadata
[info] ltv-100903204_100903204_3701925925008943921: Downloading 1 format(s): source
[hlsnative] Downloading m3u8 manifest
[hlsnative] Fragment downloads will be delegated to aria2c
[hlsnative] Total fragments: 765
[download] Destination: /tmp/./TrovoVod/GiroudGG/Csgo_20211006_NA.mp4
```

So the question now is what's better for livestreams ffmpeg or yt-dlp's native downloader.

Best Regards

**Comment by pukkandan** [comment]
> So the question now is what's better for livestreams ffmpeg or yt-dlp's native downloader.

Both seem to be effectively the same. Neither is able to resume the download in case of an error. The native (with --retries 0) terminates the download on even the smallest network error. I dont know whether ffmpeg has some recovery mechanism in this case. Both also gives me the same speed

**Comment by DerBunteBall** [comment]
It's just important to don't lose the files if it breaks. So --retries 0 will do I think.

Thanks for the fast help.

Best Regards
