### ISSUE TITLE
Add argument to open folder after successful download

### ISSUE THREAD

**Issue by rnxm** [yt-dlp/yt-dlp#11826]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

A really nice feature would be to automatically open the folder specified in `-P` after download, if you specify it in an additional argument, such as `--open-folder` (`-F` and `-O` are already taken sadly), maybe make it so file explorer already selects it for you? Maybe I could open a pull request for this, but I'm way too scared to do it haha

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU']                                                                                    [debug] User config "C:\Users\Pearoo\AppData\Roaming\yt-dlp\config": ['--no-mtime', '--windows-filenames', '--force-overwrites', '-S', 'res:1080,fps:60,codec:h264:m4a', '-P', '%USERPROFILE%/Downloads']                                       [debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8                           [debug] yt-dlp version stable@2024.12.13 from yt-dlp/yt-dlp [542166962] (win_exe)                                       [debug] Python 3.10.11 (CPython AMD64 64bit) - Windows-10-10.0.22631-SP0 (OpenSSL 1.1.1t  7 Feb 2023)                   [debug] exe versions: ffmpeg 7.1-essentials_build-www.gyan.dev (setts), ffprobe 7.1-essentials_build-www.gyan.dev       [debug] Optional libraries: Cryptodome-3.21.0, brotli-1.1.0, certifi-2024.08.30, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.40.1, urllib3-2.2.3, websockets-14.1                                                              [debug] Proxy map: {}                                                                                                   [debug] Request Handlers: urllib, requests, websockets, curl_cffi                                                       [debug] Loaded 1837 extractors                                                                                          [debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest                               Latest version: stable@2024.12.13 from yt-dlp/yt-dlp                                                                    yt-dlp is up to date (stable@2024.12.13 from yt-dlp/yt-dlp)
```

**Comment by bashonly** [comment]
It would be impossible to make this cross-platform. Out-of-scope, IMO.

And it should already be (mostly) possible with `--exec`, e.g.
```
--exec "explorer.exe /e,C:\Videos"
```
you may need to do some additional quoting/escaping if the path has spaces in it

&nbsp;

Once upon a time this worked, too:
```
--exec "explorer.exe /e,{}\.."
```
but I think our exec security fix broke that
