### ISSUE TITLE
Copyright video owner tiktok

### ISSUE THREAD

**Issue by NoneToRoot** [yt-dlp/yt-dlp#11830]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a site-specific feature
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Saudi arabia

### Example URLs

https://vt.tiktok.com/ZS6eKtX94/

### Provide a description that is worded well enough to be understood

I remeber the version of yt-dlp before maybe 3/4 updates the toolbwas able to download tiktok videos and removing all the creator copyright
Which is not still remain available now.
Is it normal all there is an error ?

thank you

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
No output
```

**Comment by bashonly** [comment]
> removing all the creator copyright

What does this mean? Do you mean the video watermark? yt-dlp still downloads the videos without watermarks. Please show complete verbose output demonstrating the issue

**Comment by Idrss1** [comment]
> > removing all the creator copyright
> 
> 
> 
> What does this mean? Do you mean the video watermark? yt-dlp still downloads the videos without watermarks. Please show complete verbose output demonstrating the issue

Take these 2 photos taken from a video that was downloaded using yt-dlp

As you can see the tiktok watermarks has not been removed from the video, before some updates in the past the tool was removing this which is not the case actually

Hopping that is more clear

![image](https://github.com/user-attachments/assets/cb142e9c-ea48-43a5-bb78-4a598c3321d8)


![image](https://github.com/user-attachments/assets/cccf8851-9642-450e-8f76-b33569e41b6e)

**Comment by bashonly** [comment]
Closing as incomplete. Since you are refusing to share complete verbose output, there is no way for anyone to help you with this
