### ISSUE TITLE
Error postprocessing stream copy YOUTUBE

### ISSUE THREAD

**Issue by terremoth** [yt-dlp/yt-dlp#11833]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Brazil

### Provide a description that is worded well enough to be understood

Using the nightly version (2024.12.15.232913) show this error: ERROR: Postprocessing:   Stream #1:0 -> #0:1 (copy)

I think when it goes to be merged?

Please see the output

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
\> yt-dlp.exe -vU https://www.youtube.com/watch?v=HqKu4aGF3d4

[debug] Command-line config: ['-vU', 'https://www.youtube.com/watch?v=HqKu4aGF3d4']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.12.15.232913 from yt-dlp/yt-dlp-nightly-builds [d298693b1] (win_exe)
[debug] Python 3.10.11 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1t  7 Feb 2023)
[debug] exe versions: ffmpeg N-91510-gd134b8d85f, ffprobe N-91510-gd134b8d85f
[debug] Optional libraries: Cryptodome-3.21.0, brotli-1.1.0, certifi-2024.12.14, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.40.1, urllib3-2.2.3, websockets-14.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1837 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.12.15.232913 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.12.15.232913 from yt-dlp/yt-dlp-nightly-builds)
[youtube] Extracting URL: https://www.youtube.com/watch?v=HqKu4aGF3d4
[youtube] HqKu4aGF3d4: Downloading webpage
[youtube] HqKu4aGF3d4: Downloading ios player API JSON
[youtube] HqKu4aGF3d4: Downloading mweb player API JSON
[debug] Loading youtube-nsig.2f1832d2 from cache
[debug] [youtube] Decrypted nsig -mQvyTItm0dkN7rcoGMn0 => WkEE6h7PSyozQQ
[debug] Loading youtube-nsig.2f1832d2 from cache
[debug] [youtube] Decrypted nsig zib6ExGEuxHbpnXYOeg3x => GHz4XTcgibRbVA
[youtube] HqKu4aGF3d4: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec, channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] HqKu4aGF3d4: Downloading 1 format(s): 396+251
[debug] Invoking http downloader on "https://rr2---sn-oxvgxqx-4aoe.googlevideo.com/videoplayback?expire=1734395892&ei=lHNgZ826G9KWobIP3qeZsA8&ip=2804%3A1530%3A106%3A22ca%3Acdf5%3A38b6%3A58d5%3A2d77&id=o-ADo4ya_Nr5DcPZ_TUeBgjxDBV9HGsKMZnNKg4puo8cgv&itag=396&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&met=1734374292%2C&mh=DI&mm=31%2C29&mn=sn-oxvgxqx-4aoe%2Csn-bg0ezne7&ms=au%2Crdu&mv=m&mvi=2&pl=40&rms=au%2Cau&pcm2=yes&initcwndbps=2431250&bui=AfMhrI8-_fCNAHqlW5XcRLvCYT-9LU3zgnTKAqg93dVs2Tb1RTdCXI2VgTNjjrzGIyZIZRIiRUKkVhqZ&spc=x-caUHKREsm1Ol05Rh7HavpR9g8Oc181_QpiCrn63wnTxVNqLg&vprv=1&svpuc=1&mime=video%2Fmp4&rqh=1&gir=yes&clen=107665992&dur=6536.162&lmt=1706420040127155&mt=1734373788&fvip=4&keepalive=yes&fexp=51326932%2C51335594%2C51347747&c=IOS&txp=543G434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cpcm2%2Cbui%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRQIhAJ6mE3mZPa8ssAPpuBd8txhJcYFB8SkYeQRjMNOrTkjRAiA_iGeRQJJBXxWJOI3tVeuOzkk6sx6YjjiuD9tB4PlxNA%3D%3D&lsparams=met%2Cmh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Crms%2Cinitcwndbps&lsig=AGluJ3MwRQIgOASmMQpaNHezWeJkDe7ecklQH1oRsP5TjPRq9kLLrCsCIQCNVZldh6Hu8lekO_0_e-cPoJ1BRCh8j0lEjSFAO6cDpQ%3D%3D"
[debug] File locking is not supported. Proceeding without locking
[download] Destination: Operação Prato, entrevista Uyrangê Hollanda [HqKu4aGF3d4].f396.mp4
[download] 100% of  102.68MiB in 00:00:02 at 35.49MiB/s
[debug] Invoking http downloader on "https://rr2---sn-oxvgxqx-4aoe.googlevideo.com/videoplayback?expire=1734395892&ei=lHNgZ826G9KWobIP3qeZsA8&ip=2804%3A1530%3A106%3A22ca%3Acdf5%3A38b6%3A58d5%3A2d77&id=o-ADo4ya_Nr5DcPZ_TUeBgjxDBV9HGsKMZnNKg4puo8cgv&itag=251&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&met=1734374292%2C&mh=DI&mm=31%2C29&mn=sn-oxvgxqx-4aoe%2Csn-bg0ezne7&ms=au%2Crdu&mv=m&mvi=2&pl=40&rms=au%2Cau&pcm2=yes&initcwndbps=2431250&bui=AfMhrI8-_fCNAHqlW5XcRLvCYT-9LU3zgnTKAqg93dVs2Tb1RTdCXI2VgTNjjrzGIyZIZRIiRUKkVhqZ&spc=x-caUHKREsm1Ol05Rh7HavpR9g8Oc181_QpiCrn63wnTxVNqLg&vprv=1&svpuc=1&mime=audio%2Fwebm&rqh=1&gir=yes&clen=110385905&dur=6536.221&lmt=1706419948751974&mt=1734373788&fvip=4&keepalive=yes&fexp=51326932%2C51335594%2C51347747&c=IOS&txp=5432434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cpcm2%2Cbui%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRQIgVzzRyAxeeUpIBbQUCFDccCr1B9i6dEOWSmEDJYbToTUCIQD731qIsFs4-vnXrEVNUuRtv346S7tMSgOzuGUIgIA83g%3D%3D&lsparams=met%2Cmh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Crms%2Cinitcwndbps&lsig=AGluJ3MwRQIgOASmMQpaNHezWeJkDe7ecklQH1oRsP5TjPRq9kLLrCsCIQCNVZldh6Hu8lekO_0_e-cPoJ1BRCh8j0lEjSFAO6cDpQ%3D%3D"
[download] Destination: Operação Prato, entrevista Uyrangê Hollanda [HqKu4aGF3d4].f251.webm
[download] 100% of  105.27MiB in 00:00:02 at 41.57MiB/s
[Merger] Merging formats into "Operação Prato, entrevista Uyrangê Hollanda [HqKu4aGF3d4].webm"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i "file:Operação Prato, entrevista Uyrangê Hollanda [HqKu4aGF3d4].f396.mp4" -i "file:Operação Prato, entrevista Uyrangê Hollanda [HqKu4aGF3d4].f251.webm" -c copy -map 0:v:0 -map 1:a:0 -movflags +faststart "file:Operação Prato, entrevista Uyrangê Hollanda [HqKu4aGF3d4].temp.webm"
[debug] ffmpeg version N-91510-gd134b8d85f Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 7.3.1 (GCC) 20180722
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-bzlib --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth
  libavutil      56. 18.102 / 56. 18.102
  libavcodec     58. 21.106 / 58. 21.106
  libavformat    58. 17.101 / 58. 17.101
  libavdevice    58.  4.101 / 58.  4.101
  libavfilter     7. 26.100 /  7. 26.100
  libswscale      5.  2.100 /  5.  2.100
  libswresample   3.  2.100 /  3.  2.100
  libpostproc    55.  2.100 / 55.  2.100
[mov,mp4,m4a,3gp,3g2,mj2 @ 000001c0be05ae00] Unknown AV1 Codec Configuration Box version 129
[libaom-av1 @ 000001c0be06d700] 1.0.0-183-gee1205ada
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'file:Operação Prato, entrevista Uyrangê Hollanda [HqKu4aGF3d4].f396.mp4':
  Metadata:
    major_brand     : dash
    minor_version   : 0
    compatible_brands: iso6av01mp41
    creation_time   : 2024-01-28T05:03:12.000000Z
  Duration: 01:48:56.16, start: 0.000000, bitrate: 131 kb/s
    Stream #0:0(und): Video: av1 (Main) (av01 / 0x31307661), yuv420p(tv, bt709), 640x360, 0 kb/s, 29.97 fps, 29.97 tbr, 30k tbn, 30k tbc (default)
    Metadata:
      creation_time   : 2024-01-28T05:03:12.000000Z
      handler_name    : ISO Media file produced by Google Inc.
Input #1, matroska,webm, from 'file:Operação Prato, entrevista Uyrangê Hollanda [HqKu4aGF3d4].f251.webm':
  Metadata:
    encoder         : google/video-file
  Duration: 01:48:56.22, start: -0.007000, bitrate: 135 kb/s
    Stream #1:0(eng): Audio: opus, 48000 Hz, stereo, fltp (default)
[webm @ 000001c0be09a640] Only VP8 or VP9 video and Vorbis or Opus audio and WebVTT subtitles are supported for WebM.
Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #1:0 -> #0:1 (copy)


ERROR: Postprocessing:   Stream #1:0 -> #0:1 (copy)
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 3557, in process_info
  File "yt_dlp\YoutubeDL.py", line 3741, in post_process
  File "yt_dlp\YoutubeDL.py", line 3723, in run_all_pps
  File "yt_dlp\YoutubeDL.py", line 3701, in run_pp
  File "yt_dlp\postprocessor\common.py", line 22, in run
  File "yt_dlp\postprocessor\common.py", line 127, in wrapper
  File "yt_dlp\postprocessor\ffmpeg.py", line 839, in run
  File "yt_dlp\postprocessor\ffmpeg.py", line 329, in run_ffmpeg_multiple_files
  File "yt_dlp\postprocessor\ffmpeg.py", line 367, in real_run_ffmpeg
yt_dlp.postprocessor.ffmpeg.FFmpegPostProcessorError:   Stream #1:0 -> #0:1 (copy)
```

**Comment by rdamas** [comment]
You shoud update your ffmpeg version. (Your version is from mid 2018, if I'm not mistaken.)

**Comment by bashonly** [comment]
yeah upgrade ffmpeg or else select formats that ancient ffmpeg won't complain about, e.g. use `-S vcodec:h264,res,acodec:aac`

**Comment by terremoth** [comment]
humm, ok, let me test here right now. I will use the latest right now from: https://github.com/BtbN/FFmpeg-Builds/releases (using the not-shared libs one binaries):

`yt-dlp.exe -vU https://www.youtube.com/watch?v=HqKu4aGF3d4
[debug] Command-line config: ['-vU', 'https://www.youtube.com/watch?v=HqKu4aGF3d4']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.12.15.232913 from yt-dlp/yt-dlp-nightly-builds [d298693b1] (win_exe)
[debug] Python 3.10.11 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1t  7 Feb 2023)
[debug] exe versions: ffmpeg N-118081-g7b0bd6c4a7-20241217 (setts), ffprobe N-118081-g7b0bd6c4a7-20241217
[debug] Optional libraries: Cryptodome-3.21.0, brotli-1.1.0, certifi-2024.12.14, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.40.1, urllib3-2.2.3, websockets-14.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1837 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.12.15.232913 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.12.15.232913 from yt-dlp/yt-dlp-nightly-builds)
[youtube] Extracting URL: https://www.youtube.com/watch?v=HqKu4aGF3d4
[youtube] HqKu4aGF3d4: Downloading webpage
[youtube] HqKu4aGF3d4: Downloading ios player API JSON
[youtube] HqKu4aGF3d4: Downloading mweb player API JSON
[debug] Loading youtube-nsig.03dbdfab from cache
[debug] [youtube] Decrypted nsig Si_QAJ-zmiqd9eJZJ => v8Kqcijg94A7mA
[debug] Loading youtube-nsig.03dbdfab from cache
[debug] [youtube] Decrypted nsig 6VF8ZiylaywBkhSTH => ocal1x-oFAdawA
[youtube] HqKu4aGF3d4: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec, channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] HqKu4aGF3d4: Downloading 1 format(s): 396+251
[debug] Invoking http downloader on "https://rr2---sn-oxvgxqx-4aoe.googlevideo.com/videoplayback?expire=1734538260&ei=tJ9iZ5ynCN2tobIPosGqwAs&ip=2804%3A1530%3A106%3A22ca%3A8c29%3Ae08e%3Ae7d1%3Af0b&id=o-AGIr6vWTtU1viN1MSS7TsfEtha_A0ppGx0ZtK2h7elEW&itag=396&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&met=1734516660%2C&mh=DI&mm=31%2C29&mn=sn-oxvgxqx-4aoe%2Csn-bg0eznsr&ms=au%2Crdu&mv=m&mvi=2&pcm2cms=yes&pl=40&rms=au%2Cau&initcwndbps=2507500&bui=AfMhrI_Xd1ihqID_5taSO1X2YQSCYsoUt59zTwd9Hng-zqgZTLY3HLvSflcs2YMJ_I_8bPSkvaWv6qfr&spc=x-caUOQ9Q3LcTnwEO60fPUtnx4vNob_5IVWWwwJIEz0BI1sh7q_e&vprv=1&svpuc=1&mime=video%2Fmp4&rqh=1&gir=yes&clen=107665992&dur=6536.162&lmt=1706420040127155&mt=1734516320&fvip=1&keepalive=yes&fexp=51326932%2C51335594%2C51371294&c=IOS&txp=543G434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cbui%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRgIhAO3-3WRf_NOoTpUo_hpf5oho5OAShYFSpgmFDdXGk9FqAiEA9HJ0kGLSeX8u8GxBpjUhdn_XwJNrgjBbjksfdgv_Hww%3D&lsparams=met%2Cmh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Crms%2Cinitcwndbps&lsig=AGluJ3MwRQIhAOJ8zaIrWfjvOQAFQzqePuakM6e5ce6pIc7n5LLuhwNVAiB9abPQLH70GLi6xbbAjZYGEg7_8jrtn8AQunZxcqB9Lw%3D%3D"
[debug] File locking is not supported. Proceeding without locking
[download] Destination: Operação Prato, entrevista Uyrangê Hollanda [HqKu4aGF3d4].f396.mp4
[download] 100% of  102.68MiB in 00:00:02 at 48.17MiB/s
[debug] Invoking http downloader on "https://rr2---sn-oxvgxqx-4aoe.googlevideo.com/videoplayback?expire=1734538260&ei=tJ9iZ5ynCN2tobIPosGqwAs&ip=2804%3A1530%3A106%3A22ca%3A8c29%3Ae08e%3Ae7d1%3Af0b&id=o-AGIr6vWTtU1viN1MSS7TsfEtha_A0ppGx0ZtK2h7elEW&itag=251&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&met=1734516660%2C&mh=DI&mm=31%2C29&mn=sn-oxvgxqx-4aoe%2Csn-bg0eznsr&ms=au%2Crdu&mv=m&mvi=2&pcm2cms=yes&pl=40&rms=au%2Cau&initcwndbps=2507500&bui=AfMhrI_Xd1ihqID_5taSO1X2YQSCYsoUt59zTwd9Hng-zqgZTLY3HLvSflcs2YMJ_I_8bPSkvaWv6qfr&spc=x-caUOQ9Q3LcTnwEO60fPUtnx4vNob_5IVWWwwJIEz0BI1sh7q_e&vprv=1&svpuc=1&mime=audio%2Fwebm&rqh=1&gir=yes&clen=110385905&dur=6536.221&lmt=1706419948751974&mt=1734516320&fvip=1&keepalive=yes&fexp=51326932%2C51335594%2C51371294&c=IOS&txp=5432434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cbui%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRQIhANVJ4UMnq46KjptQ8huEeU-DjdVENna7Db3NMnEW3xIqAiAYdUHJd3mDs6VA3YjEdnBNF9TLDC-nj0WhtgFlOgKRwA%3D%3D&lsparams=met%2Cmh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Crms%2Cinitcwndbps&lsig=AGluJ3MwRQIhAOJ8zaIrWfjvOQAFQzqePuakM6e5ce6pIc7n5LLuhwNVAiB9abPQLH70GLi6xbbAjZYGEg7_8jrtn8AQunZxcqB9Lw%3D%3D"
[download] Destination: Operação Prato, entrevista Uyrangê Hollanda [HqKu4aGF3d4].f251.webm
[download] 100% of  105.27MiB in 00:00:01 at 57.44MiB/s
[Merger] Merging formats into "Operação Prato, entrevista Uyrangê Hollanda [HqKu4aGF3d4].webm"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i "file:Operação Prato, entrevista Uyrangê Hollanda [HqKu4aGF3d4].f396.mp4" -i "file:Operação Prato, entrevista Uyrangê Hollanda [HqKu4aGF3d4].f251.webm" -c copy -map 0:v:0 -map 1:a:0 -movflags +faststart "file:Operação Prato, entrevista Uyrangê Hollanda [HqKu4aGF3d4].temp.webm"
Deleting original file Operação Prato, entrevista Uyrangê Hollanda [HqKu4aGF3d4].f251.webm (pass -k to keep)
Deleting original file Operação Prato, entrevista Uyrangê Hollanda [HqKu4aGF3d4].f396.mp4 (pass -k to keep)`

worked, but for some reason it didn't generate the thumb like others.

I also tried without the -vU option:

`yt-dlp.exe https://www.youtube.com/watch?v=HqKu4aGF3d4
[youtube] Extracting URL: https://www.youtube.com/watch?v=HqKu4aGF3d4
[youtube] HqKu4aGF3d4: Downloading webpage
[youtube] HqKu4aGF3d4: Downloading ios player API JSON
[youtube] HqKu4aGF3d4: Downloading mweb player API JSON
[youtube] HqKu4aGF3d4: Downloading m3u8 information
[info] HqKu4aGF3d4: Downloading 1 format(s): 396+251
[download] Destination: Operação Prato, entrevista Uyrangê Hollanda [HqKu4aGF3d4].f396.mp4
[download] 100% of  102.68MiB in 00:00:01 at 64.46MiB/s
[download] Destination: Operação Prato, entrevista Uyrangê Hollanda [HqKu4aGF3d4].f251.webm
[download] 100% of  105.27MiB in 00:00:01 at 65.30MiB/s
[Merger] Merging formats into "Operação Prato, entrevista Uyrangê Hollanda [HqKu4aGF3d4].webm"
Deleting original file Operação Prato, entrevista Uyrangê Hollanda [HqKu4aGF3d4].f251.webm (pass -k to keep)
Deleting original file Operação Prato, entrevista Uyrangê Hollanda [HqKu4aGF3d4].f396.mp4 (pass -k to keep)`


![image](https://github.com/user-attachments/assets/80fa2f76-c99b-49c1-a6a5-9457a7835a71)

Now seems to have another problem, maybe

**Comment by bashonly** [comment]
That's a Windows problem. Use `--embed-thumbnail` if you want to embed a proper thumbnail, instead of relying on Windows to auto-generate a thumb from the video track.

**Comment by terremoth** [comment]
Ok, but before, I never needed to use that option. Will I need to always use it from now on?

**Comment by bashonly** [comment]
> Ok, but before, I never needed to use that option. Will I need to always use it from now on?

AV1 video is sorted as "best" by default now. This is a relatively recent change, and likely what is causing the confusion for you. You could select the best VP9 video format instead, as this was the result of the previous format sorting behavior. Otherwise if you want to stick with the AV1 video, yes you will probably need to keep using `--embed-thumb`

**Comment by terremoth** [comment]
@bashonly ah ok, but the --embed-thumb behavior is like download the youtube thumb right? Not actually make Windows generate the thumb like always?
