### ISSUE TITLE
I don't know how to update yt-dlp with packages apt correctly.

### ISSUE THREAD

**Issue by khaquachtrong74** [yt-dlp/yt-dlp#11832]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I have a problem when download audio from youtube, 5 day ago I can downloads it but now it don't, I try to update it with packages apt but it doesn't work, I still get version 2024.04.08 instead off 2024.12.13-1

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by khaquachtrong74** [comment]
and this is the first time I use this, so it has any problem, please teach me, thanks.

**Comment by khaquachtrong74** [comment]
OK, I just found that I can use pip to update it in README.

**Comment by bashonly** [comment]
Don't install with apt. `sudo apt remove yt-dlp`

https://github.com/yt-dlp/yt-dlp/wiki/Installation

I'd recommend installing with pip in a virtual environment. Or you could use `pipx`, which may simplify that process

**Comment by MalcolmReed-ent** [comment]
If your running Debian SID the latest version is available
```
[will@debian` ~]$ yt-dlp --version
2024.12.13
```

If your running Debian Bookworm or Trixie, you can install it via pythonvenv, install this
`sudo apt-get install python3-venv` 
Or something like python3.11-venv whatever your version have, if you dont know what you have, run 
`apt search pythonvenv`

and to make the environment
`python3 -m venv $HOME/.venv && source $HOME/.venv/bin/activate`

then run this to install yt-dlp
`pip install yt-dlp`

**Comment by aarrbba123** [comment]
> If your running Debian SID the latest version is available
> ```
> [will@debian` ~]$ yt-dlp --version
> 2024.12.13
> ```
> 
> If your running Debian Bookworm or Trixie, you can install it via pythonvenv, install this
> `sudo apt-get install python3-venv` 
> Or something like python3.11-venv whatever your version have, if you dont know what you have, run 
> `apt search pythonvenv`
> 
> and to make the environment
> `python3 -m venv $HOME/.venv && source $HOME/.venv/bin/activate`
> 
> then run this to install yt-dlp
> `pip install yt-dlp`
>  

To add to that, if you're using the latest stable version (as of writing this, bookworm) you can also use the official backports.

First remove the original yt-dlp
`apt remove yt-dlp`

Then, add a backport repository to your `/etc/apt/sources.list`
(in my case, `http://deb.debian.org/debian/`)
Like this:
`deb http://deb.debian.org/debian/ bookworm-backports main`

After that, update apt and (re)install yt-dlp using this:
`apt install yt-dlp/bookworm-backports`

**Comment by khaquachtrong74** [comment]
Thanks guys for help me fix yt-dlp and now it work correctly like I want
