### ISSUE TITLE
There are websites that can't be downloaded.

### ISSUE THREAD

**Issue by Tomp-Akoe** [yt-dlp/yt-dlp#11844]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Hello, Xinpianchang: It seems that the website of the new film sto can't be downloaded.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [x] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
please share complete verbose output

**Comment by Tomp-Akoe** [comment]
> 请分享完整的详细输出

ok

C:\Users\n1289>yt-dlp -f -best "https://www.xinpianchang.com/a12294310?from=IndexPick&part=%E7%BC%96%E8%BE%91%E7%B2%BE%E
9%80%89&index=4"
[Xinpianchang] Extracting URL: https://www.xinpianchang.com/a12294310?from=IndexPick&part=%E7%BC%96%E8%BE%91%E7%B2%BE%E9%80%89&index=4
[Xinpianchang] a12294310: Downloading webpage
ERROR: [Xinpianchang] a12294310: Unable to download webpage: HTTP Error 406: Not Acceptable (caused by <HTTPError 406: Not Acceptable>)
