### ISSUE TITLE
[Youtube] Provide thumbnail in flat playlist

### ISSUE THREAD

**Issue by alervd** [yt-dlp/yt-dlp#1184]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running yt-dlp version **2021.09.25**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description

I'm using the following command to query video/playlist information:
python -m yt_dlp -J --flat-playlist URL

The returned JSON contains thumbnails section for the playlist itself. 

I would like JSON to also contain thumbnail information for the each playlist's video in the entries section.

**Comment by pukkandan** [comment]
If you don't use --flat-playlist, yt-dlp does get the thumbnail info.

When using that option, I think it is possible to accurately extract only a low resolution thumbnail. We can also generate all possible thumbnail URLs, but many of them may not be actually available. To resolve them, you need to remove --flat-playlist and add `--check-formats`.

But if you think this is a feature you want despite these caveats, I can add it

**Comment by alervd** [comment]
--flat-playlist works much faster, so we need it in our project. 
I think that low resolution thumbnails are OK to this use case. We need to show them in create download dialog.
High resolution thumbnails will be downloaded for the videos selected by the user. These videos will be parsed separately without --flat-playlist command.
