### ISSUE TITLE
--audio-format mp3 not working in soundcloud?

### ISSUE THREAD

**Issue by mostafa-norouzi** [yt-dlp/yt-dlp#11850]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Hi,

I ran below command format :
```
yt-dlp --audio-format mp3  https://soundcloud.com/emantium/wondering -v
```

But for some URLs like sample, I get only the opus format whereas I think FFMPEG can convert it to mp3. So is it a bug? 

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['--audio-format', 'mp3', 'https://soundcloud.com/emantium/wondering', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.12.13 from yt-dlp/yt-dlp [542166962] (zip)
[debug] Python 3.9.21 (CPython x86_64 64bit) - Linux-5.14.0-503.15.1.el9_5.x86_64-x86_64-with-glibc2.34 (OpenSSL 3.2.2 4 Jun 2024, glibc 2.34)
[debug] exe versions: ffmpeg N-71064-gd5e603ddc0-static (setts), ffprobe N-71064-gd5e603ddc0-static
[debug] Optional libraries: mutagen-1.47.0, requests-2.25.1, sqlite3-3.34.1, urllib3-1.26.5
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Loaded 1837 extractors
[debug] Loading soundcloud.client_id from cache
[soundcloud] Extracting URL: https://soundcloud.com/emantium/wondering
[soundcloud] emantium/wondering: Downloading info JSON
[soundcloud] 561119283: Downloading original download format info JSON
WARNING: [soundcloud] Original download format is only available for registered users. Use --cookies, --cookies-from-browser, --username and --password, --netrc-cmd, or --netrc (soundcloud) to provide account credentials. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies
[soundcloud] 561119283: Downloading hls_mp3 format info JSON
[soundcloud] 561119283: Downloading http_mp3 format info JSON
[soundcloud] 561119283: Downloading hls_opus format info JSON
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec, channels, acodec,size, br, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 561119283: Downloading 1 format(s): hls_opus_0_0
[debug] Invoking hlsnative downloader on "https://cf-hls-opus-media.sndcdn.com/playlist/Btbv77yxw45q.64.opus/playlist.m3u8?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiKjovL2NmLWhscy1vcHVzLW1lZGlhLnNuZGNkbi5jb20vcGxheWxpc3QvQnRidjc3eXh3NDVxLjY0Lm9wdXMvcGxheWxpc3QubTN1OCoiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE3MzQ1Mzg2ODV9fX1dfQ__&Signature=H7k5eFCtHAD8oA~b2h-cu6OJe~QC1yU27lpNbvMfrG7kHRIdN~6zDgO7Y70SjiRijl2bv6j~6IcVBv5TKw5-XKD78xwKW-TQe3QPHfXzo07jNQJBcHHfaLDkbWSlZPa4TOEMxe0GjJdRf1mGu-pnL6i1cMNabXjoL1KB0BrYW-SNC3BxQh6i-Lneniu7CSLB2Ui~c9T5V14XowQXJbZ7rHXM76n5q9dGyAYq08q3mL1I2t7jjwJNu-HqZXlEfwtngJKqxKW08zWQV7MqIc~qDDDtH1~~1WuWkoD9D-BVpBZQKkKLfMpBSrWlk3kvuXqpZdRXa1XwVDZ4UlcUse6zFg__&Key-Pair-Id=APKAI6TU7MMXM5DG6EPQ"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 26
[download] Destination: Wondering [561119283].opus
[download] 100% of    1.76MiB in 00:00:01 at 904.30KiB/s
```

**Comment by bashonly** [comment]
As per the README, `--audio-format` only works in conjunction with `--extract-audio`/`-x`. It tells yt-dlp what format to convert the audio to. If you only want to download the mp3 format, use `-S ext:mp3`
