### ISSUE TITLE
How can I get the original link of a TikTok video?

### ISSUE THREAD

**Issue by zed-syn** [yt-dlp/yt-dlp#11854]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

https://v19-webapp-prime.tiktok.com/video/tos/alisg/tos-alisg-pve-0037/o4At3S2kRNARBE6RxSPAZJO5liY96iQI6VPuz/?a=1988&bti=ODszNWYuMDE6&ch=0&cr=3&dr=0&lr=all&cd=0%7C0%7C0%7C&cv=1&br=1288&bt=644&cs=2&ds=3&eid=12800&ft=-Csk_mDUPD12Nf4jzE-UxDGvbY6e3wv25IcAp&mime_type=video_mp4&qs=14&rc=NDlnPGVkOzs8NTQ6MzU1O0BpM2tveG05cmh5dzMzODgzNEAvYF8tNGFiXzExYjFhXzFjYSM2L2kzMmQ0Y2VgLS1kLzFzcw%3D%3D&btag=e00098000&expire=1734791767&l=20241219143304BC49A97DC46A2FE6501B&ply_type=2&policy=2&signature=ff9a057a08b724a2d87393bf495d42fc&tk=tt_chain_token  
  
My link when running the yt_dlp command is not the original TikTok video link and cannot be accessed from other sources or browsers. However, the example link below can be accessed from anywhere. How can I extract the original link similar to the one below?
  
https://v16m-default.akamaized.net/6553a1128d9d294263a698dbc05ceebc/6764807b/video/tos/alisg/tos-alisg-pve-0037c001/oUqOZQDQIDCEcwjRfIAAEHlFWkzEIfxfw6DjgL/?a=0&bti=OUBzOTg7QGo6OjZAL3AjLTAzYCMxNDNg&ch=0&cr=0&dr=0&er=0&lr=all&net=0&cd=0%7C0%7C0%7C0&cv=1&br=1516&bt=758&cs=0&ds=6&ft=XE5bCqT0m7jPD12b~vnJ3wUX73yKMeF~O5&mime_type=video_mp4&qs=0&rc=OWU1OGlkNGU0NTdmZGY8ZEBpanJmd2s5cmtsdjMzODczNEA1XmMyY2M2XjYxYzY1YTE2YSNzZDZkMmQ0Y21gLS1kMS1zcw%3D%3D&vvpl=1&l=20241219141710F40777399E55D5158305&btag=e000a0000

`yt-dlp --format "bestvideo+bestaudio/best" --merge-output-format "mp4" --cookies "cookies.txt" --user-agent "Mozilla/5.0 (iPhone; CPU iPhone OS 16_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.6 Mobile/15E148 Safari/604.1" "https://www.tiktok.com/@camerachiensi/video/7450071291446562055"`

### Provide verbose output that clearly demonstrates the problem

- [x] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [x] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
The first example URL comes from webpage extraction, and it requires the cookies that are set during yt-dlp's extraction requests in order for you access it.

The second example URL comes from the mobile API, which yt-dlp can use for extraction if you pass a mobile install ID with the `app_info` extractor-arg: https://github.com/yt-dlp/yt-dlp#tiktok
