### ISSUE TITLE
Is it possible to pass a wildcard for audio or video formats?

### ISSUE THREAD

**Issue by guy-teube** [yt-dlp/yt-dlp#11855]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Hi there,

I use yt-dlp to download videos from french TV broadcaster France Télévisions.
But for the same quality of video, there are multiple values.
Example for 720p, for this TV show: https://www.france.tv/france-2/ca-commence-aujourd-hui/5513172-le-plus-beau-noel-de-leur-vie.html
If you look the three last videos with -F option, you will see each one has its own 720p video value:
- hls-22-15
- hls-22-11
- hls-22-08
(the fourth one has 22-15 too).

I don't know why there is this difference, maybe it's to piss off yt-dlp users... :D

For another TV show on the same channel, it will be another values, again (hls-22-72, hls-22-92 and so on).

I ue Ubuntu, and make an alias to run yt-dlp with 720p option ("alias y=yt-dlp -f quality1/quality2/... $1" with $1 as the url). But because there are so many values, sometimes the downloads doesn't start because my alias doesn't have the good value for the required video.

So here my question: is there a way to put a wildcard? I would like to pass "-f hls-22*" (I never see a value starting with something else, but it could be 100 different values, I don't want to put 100 values in my alias if possible).

Thank you for your help.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
$ ytdlp -vU
[debug] Command-line config: ['-vU']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version master@2024.12.15.202031 from yt-dlp/yt-dlp-master-builds [d298693b1] (zip)
[debug] Python 3.10.12 (CPython x86_64 64bit) - Linux-6.8.0-49-generic-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.11.0, brotli-1.0.9, certifi-2020.06.20, mutagen-1.45.1, pyxattr-0.7.2, requests-2.25.1, secretstorage-3.3.1, sqlite3-3.37.2, urllib3-1.26.5, websockets-9.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Loaded 1837 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-master-builds/releases/latest
Latest version: master@2024.12.15.202031 from yt-dlp/yt-dlp-master-builds
yt-dlp is up to date (master@2024.12.15.202031 from yt-dlp/yt-dlp-master-builds)
```

**Comment by bashonly** [comment]
You could just use `-S res:720`. This is the best solution to this problem, IMO.

To answer the original question though: yes, you can use the format filter operators `^=` (starts with), `*=` (contains) or `~=` (regex), e.g.:

```
-f "bv[format_id^='hls-22-']+ba"
```

https://github.com/yt-dlp/yt-dlp?tab=readme-ov-file#filtering-formats

**Comment by guy-teube** [comment]
Thanks @bashonly this is exactly what I needed! :)
