### ISSUE TITLE
What is the fastest way to resolve a stream url for YT Music?

### ISSUE THREAD

**Issue by MarvinSchenkel** [yt-dlp/yt-dlp#11861]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Hello people 👋  , Music Assistant dev here.

We use your amazing product over at Music Assistant to integrate playback for YT Music. Now, Google has been making our life harder and harder to properly support YT Music by first dropping OAuth support. We implementing cookie authentication as a workaround, but now Google has also broken the `ios` client in combination with providing cookies.

We were previously using the following config that resulted in stream urls being resolved super fast (< 2 sec):
```python
ydl_opts = {
      "cookiefile": StringIO(self._netscape_cookie),
      # This enforces a player client and skips unnecessary scraping to increase speed
      "extractor_args": {
          "youtube": {"skip": ["translated_subs", "dash"], "player_client": ["ios"]}
      },
  }
```

Now, since this is broken, we are using the default player client:
```python
ydl_opts = {
    "cookiefile": StringIO(self._netscape_cookie),
    # This enforces a player client and skips unnecessary scraping to increase speed
    "extractor_args": {
        "youtube": {
            "skip": ["translated_subs", "dash"],
            "player_client": ["web_music"],
            "player_skip": ["webpage"],
        }
    },
}
```

Unfortunately, this can sometimes take around 10 secs to resolve a stream url. As you can imagine, this does not provide a nice user experience when a user clicks a song in the front end. The reason we use authentication is twofold:

1. We want to grab the HQ `141` streams to ensure the highest quality playback
2. We want to verify that a user has YT Premium. As far as I know, only subscribed users can obtain a `141` stream.

**Question:** Is there any way to speed up resolving YT Music stream urls after the new restrictions that have been put on us?

Again, thanks a lot for the amazing work here and I hope we can find a way to keep the music alive 💪 .

Cheers,
Marvin

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
There isn't any faster way than what you are currently using AFAIK.

**Comment by MarvinSchenkel** [comment]
Thanks for your response! Too bad, I guess it's a restriction the users will have to live with.
