### ISSUE TITLE
adding cookies when running script as part of cron job

### ISSUE THREAD

**Issue by modernNeo** [yt-dlp/yt-dlp#11866]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

some of the playlists I download from occasionally have videos with some strong language which gets me this error `Sign in to confirm your age. This video may be inappropriate for some users.`.

looking into the documentation, seems I have to pass the cookies from a logged in session of YT to be able to get around that. However, I notice that in part 3 of https://github.com/yt-dlp/yt-dlp/wiki/FAQ#im-getting-http-error-403-and-the-site-has-an-open-issue-on-the-tracker-thats-labeled-cloudflare-related-what-can-i-do, it says
>  Note that the cookies need to be exported from a fresh browser session (see step 1) **within the past 30 minutes.**

I have my script run on a schedule when I am asleep on my server. does this mean in my setup, there isn't a way for me to be able to get those explicit videos with that kinda workflow?

### Provide verbose output that clearly demonstrates the problem

- [x] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [x] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [x] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
The FAQ answer you've linked is unrelated to your problem. See instead https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies

**Comment by modernNeo** [comment]
that worked, thanks 👍🏿
