### ISSUE TITLE
Youtube VR player client "android_vr" does not work with cookies to bypass age gate

### ISSUE THREAD

**Issue by ronaldeustace** [yt-dlp/yt-dlp#11867]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Provide a description that is worded well enough to be understood
NOTE: I believe this issue is separate from issues 9633 and 9903. 

I am using player_client setting of "android_vr" to download a youtube 8k VR video.  The android_vr player client is required to download the 8K versions of VR videos (format 571).  However, the android_vr download does not work when used in conjunction with a cookies file to bypass the age gate of restricted videos.  The cookies file was from an account/IP that is verified to be able to view the video in the browser, and the same cookies file works fine when downloading the same video with the default player_client (but of course the default client can only download the low-res version).

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--cookies', 'cookies.txt', '--extractor-args', 'youtube:player_client=android_vr', 'https://www.youtube.com/watch?v=txNn-QZDz6Q']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version master@2024.12.15.202031 from yt-dlp/yt-dlp-master-builds [d298693b1] (zip)
[debug] Python 3.9.16 (CPython x86_64 64bit) - CYGWIN_NT-10.0-26100-3.5.0-1.x86_64-x86_64-64bit-WindowsPE (OpenSSL 1.1.1w  11 Sep 2023)
[debug] exe versions: ffmpeg 2024-08-11-git-43cde54fc1-full_build-www.gyan.dev (setts), ffprobe 2024-08-11-git-43cde54fc1-full_build-www.gyan.dev, phantomjs 1.9.2
[debug] Optional libraries: Crypto-broken 2.6.1, brotli-1.1.0, certifi-2021.10.08, mutagen-1.45.1, requests-2.31.0, sqlite3-3.34.0, urllib3-1.26.7
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Loaded 1837 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-master-builds/releases/latest
Latest version: master@2024.12.15.202031 from yt-dlp/yt-dlp-master-builds
yt-dlp is up to date (master@2024.12.15.202031 from yt-dlp/yt-dlp-master-builds)
[youtube] Extracting URL: https://www.youtube.com/watch?v=txNn-QZDz6Q
[youtube] txNn-QZDz6Q: Downloading webpage
[debug] [youtube] Extracted SAPISID cookie
[youtube] txNn-QZDz6Q: Downloading android vr player API JSON
WARNING: [youtube] YouTube said: ERROR - Request contains an invalid argument.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (1/3)...
[youtube] txNn-QZDz6Q: Downloading android vr player API JSON
WARNING: [youtube] YouTube said: ERROR - Request contains an invalid argument.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (2/3)...
[youtube] txNn-QZDz6Q: Downloading android vr player API JSON
WARNING: [youtube] YouTube said: ERROR - Request contains an invalid argument.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (3/3)...
[youtube] txNn-QZDz6Q: Downloading android vr player API JSON
WARNING: [youtube] YouTube said: ERROR - Request contains an invalid argument.
WARNING: [youtube] Unable to download API page: HTTP Error 400: Bad Request (caused by <HTTPError 400: Bad Request>)
WARNING: Only images are available for download. use --list-formats to see them
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec, channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
ERROR: [youtube] txNn-QZDz6Q: Requested format is not available. Use --list-formats for a list of available formats
Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1624, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1780, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1839, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 2973, in process_video_result
    raise ExtractorError(
yt_dlp.utils.ExtractorError: [youtube] txNn-QZDz6Q: Requested format is not available. Use --list-formats for a list of available formats
```

**Comment by bashonly** [comment]
This is expected. As [the documentation for the `player_client` extractor-arg states](https://github.com/yt-dlp/yt-dlp#youtube), cookies will not work with all clients. They only work with `web`, the `web_*` variants and `mweb`.

**Comment by ronaldeustace** [comment]
Is there an alternate way to bypass the age gate on 8k vr video downloads?  Or should this be considered a feature request rather than a bug?

**Comment by ronaldeustace** [comment]
Furthermore, the code for android_vr seems to indicate that it supports cookies:

    'android_vr': {
        'INNERTUBE_CONTEXT': {
            'client': {
                'clientName': 'ANDROID_VR',
                'clientVersion': '1.60.19',
                'deviceMake': 'Oculus',
                'deviceModel': 'Quest 3',
                'androidSdkVersion': 32,
                'userAgent': 'com.google.android.apps.youtube.vr.oculus/1.60.19 (Linux; U; Android 12L; eureka-user Build/SQ3A.220605.009.A1) gzip',
                'osName': 'Android',
                'osVersion': '12L',
            },
        },
        'INNERTUBE_CONTEXT_CLIENT_NAME': 28,
        'REQUIRE_JS_PLAYER': False,
        'SUPPORTS_COOKIES': True,
    },

Would this therefore still be a bug?

**Comment by bashonly** [comment]
the `SUPPORTS_COOKIES` field and comment are outdated and need to be updated

feature request isn't appropriate since it will likely never be possible again

**Comment by bashonly** [comment]
did you try it without cookies?

**Comment by ronaldeustace** [comment]
I did try without cookies.  Unfortunately it hits the age gate and says "Sign in to confirm your age".  Here is the debug:

[debug] Command-line config: ['-vU', '--extractor-args', 'youtube:player_client=android_vr', 'https://www.youtube.com/watch?v=txNn-QZDz6Q']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version master@2024.12.15.202031 from yt-dlp/yt-dlp-master-builds [d298693b1] (zip)
[debug] Python 3.9.16 (CPython x86_64 64bit) - CYGWIN_NT-10.0-26100-3.5.0-1.x86_64-x86_64-64bit-WindowsPE (OpenSSL 1.1.1w  11 Sep 2023)
[debug] exe versions: ffmpeg 2024-08-11-git-43cde54fc1-full_build-www.gyan.dev (setts), ffprobe 2024-08-11-git-43cde54fc1-full_build-www.gyan.dev, phantomjs 1.9.2
[debug] Optional libraries: Crypto-broken 2.6.1, brotli-1.1.0, certifi-2021.10.08, mutagen-1.45.1, requests-2.31.0, sqlite3-3.34.0, urllib3-1.26.7
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Loaded 1837 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-master-builds/releases/latest
Latest version: master@2024.12.15.202031 from yt-dlp/yt-dlp-master-builds
yt-dlp is up to date (master@2024.12.15.202031 from yt-dlp/yt-dlp-master-builds)
[youtube] Extracting URL: https://www.youtube.com/watch?v=txNn-QZDz6Q
[youtube] txNn-QZDz6Q: Downloading webpage
[youtube] txNn-QZDz6Q: Downloading android vr player API JSON
[youtube] txNn-QZDz6Q: This video is age-restricted; some formats may be missing without authentication. Use --cookies, --cookies-from-browser, --username and --password, --netrc-cmd, or --netrc (youtube) to provide account credentials. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies
[youtube] txNn-QZDz6Q: Downloading web embedded client config
[youtube] txNn-QZDz6Q: Downloading player 03dbdfab
[youtube] txNn-QZDz6Q: Downloading web embedded player API JSON
ERROR: [youtube] txNn-QZDz6Q: Sign in to confirm your age. This video may be inappropriate for some users. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 742, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/youtube.py", line 4533, in _real_extract
    self.raise_no_formats(reason, expected=True)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 1276, in raise_no_formats
    raise ExtractorError(msg, expected=expected, video_id=video_id)

**Comment by bashonly** [comment]
Keeping this open to track the outdated client code/comment
