### ISSUE TITLE
cookiesfrombrowser chrome custom path not work ?

### ISSUE THREAD

**Issue by irfanykywz** [yt-dlp/yt-dlp#11873]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

i have a chrome profile with custom userdatadir, when i try to download restricted content require login its not working 

i has set the chrome path like this 

`        ydl_opts = {
            'noplaylist': True,
            'quiet': True,
            'temp_dir': TEMP_PATH,
            'noconfirm': True,
            'cookiesfrombrowser': ('chrome', CHROME_PATH, None, None),
            'ffmpeg_location': FFMPEG_FILE,
            'extractor_args': {
                'generic': {
                    'impersonate': 'chrome'  # Change this to the desired browser
                }
            },
        }`

how to correctly set cookiesfrom browser use custom path userdatadir ?

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
> ### Provide verbose output that clearly demonstrates the problem

> - [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
> - [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by irfanykywz** [comment]
i try again and its work thanks
