### ISSUE TITLE
YouTube video download failing with HTTP 403 error

### ISSUE THREAD

**Issue by darui3018823** [yt-dlp/yt-dlp#11877]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Japan

### Region:
Japan

### Problem Description
When trying to download any YouTube video using yt-dlp, the process fails with an HTTP 403 error. This issue occurs across all YouTube videos and is not limited to specific URLs.

### Steps to Reproduce
1. Use the following command:
   ```
   yt-dlp -f bestvideo+bestaudio --merge-output-format mp4 --embed-thumbnail --add-metadata --output "E:/yt-dlp/%(title)s.%(ext)s" https://www.youtube.com/watch?v=dummy
   ```
2. Observe the following error message:
   ```
   ERROR: unable to download video data: HTTP Error 403: Forbidden
   ```

### Troubleshooting Attempted
1. Verified that the issue persists with the latest version of yt-dlp (version: stable@2024.12.13).
2. Used `--cookies` to provide browser cookies.
3. Tried `--force-ipv4` to ensure no IPv6 issues.
4. Checked multiple video URLs in a browser, and they all play without any issues.

### Environment
- **Region**: Japan
- **OS**: Windows 11 64-bit
- **yt-dlp Version**: stable@2024.12.13
- **ffmpeg Version**: 7.0.2-full_build-www.gyan.dev

### Notes
- This issue occurs for all YouTube videos accessed through yt-dlp, regardless of the specific video or URL.
- The problem seems to occur with videos hosted on YouTube's servers (e.g., rr2---sn-3pm7dn7d.googlevideo.com).
- Similar issues have been reported, but most reports are from non-Japan regions.

Please investigate if this issue is region-specific or related to a recent change in YouTube's infrastructure.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
PS C:\Users\user> yt-dlp -vU -f bestvideo+bestaudio --merge-output-format mp4 --embed-thumbnail --add-metadata --output "E:/yt-dlp/%(title)s.%(ext)s" https://www.youtube.com/watch?v=uXszKmEVNhg
[debug] Command-line config: ['-vU', '-f', 'bestvideo+bestaudio', '--merge-output-format', 'mp4', '--embed-thumbnail', '--add-metadata', '--output', 'E:/yt-dlp/%(title)s.%(ext)s', 'https://www.youtube.com/watch?v=uXszKmEVNhg']
[debug] Encodings: locale cp932, fs utf-8, pref cp932, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.12.13 from yt-dlp/yt-dlp [542166962] (win_exe)
[debug] Python 3.10.11 (CPython AMD64 64bit) - Windows-10-10.0.22631-SP0 (OpenSSL 1.1.1t  7 Feb 2023)
[debug] exe versions: ffmpeg 7.0.2-full_build-www.gyan.dev (setts), ffprobe 7.0.2-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.21.0, brotli-1.1.0, certifi-2024.08.30, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.40.1, urllib3-2.2.3, websockets-14.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1837 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.12.13 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.12.13 from yt-dlp/yt-dlp)
[youtube] Extracting URL: https://www.youtube.com/watch?v=uXszKmEVNhg
[youtube] uXszKmEVNhg: Downloading webpage
[youtube] uXszKmEVNhg: Downloading ios player API JSON
[youtube] uXszKmEVNhg: Downloading mweb player API JSON
[debug] [youtube] Extracting signature function js_03dbdfab_107
[debug] Loading youtube-sigfuncs.js_03dbdfab_107 from cache
[debug] Loading youtube-nsig.03dbdfab from cache
[debug] [youtube] Decrypted nsig 9vVVUHHyC5iPjKeOe => wCdKYKTZhOpcog
[debug] Loading youtube-nsig.03dbdfab from cache
[debug] [youtube] Decrypted nsig stOWvxpKAsM9Kfb4b => jwYhirB0HGzdVg
[debug] [youtube] Extracting signature function js_03dbdfab_103
[debug] Loading youtube-sigfuncs.js_03dbdfab_103 from cache
[youtube] uXszKmEVNhg: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec, channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[info] uXszKmEVNhg: Downloading 1 format(s): 399+251
[info] Downloading video thumbnail 42 ...
[info] Writing video thumbnail 42 to: E:\yt-dlp\劇場版：大妖怪＂○ね＂-THE FINAL-【Apex⧸エーペックス】.webp
[debug] Invoking http downloader on "https://rr3---sn-3pm7dnel.googlevideo.com/videoplayback?expire=1734912054&ei=1lNoZ-mHOYzIs8IP0MnU2Ag&ip=2400%3A2652%3A8420%3Afb00%3Abc41%3A9c5c%3A3a84%3A6215&id=o-AK0_31g5Yxg--P1LEj2odXBlVgw7Ft9qJ1TXSQ42ENSr&itag=399&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&met=1734890454%2C&mh=07&mm=31%2C29&mn=sn-3pm7dnel%2Csn-3pm76nes&ms=au%2Crdu&mv=m&mvi=3&pl=36&rms=au%2Cau&initcwndbps=3062500&bui=AfMhrI9IlTUjey5SG--0d-B95joKAVmBuZ8YcbgfzUoIucInPZh4inUoRGTqsnAQrgc9WCyqX_EkDQVl&spc=x-caUFS-S1z9kqN8u9uDz_9JCujZ7fyHsMd6ZYRd8HvBrl2AhIgr&vprv=1&svpuc=1&mime=video%2Fmp4&rqh=1&gir=yes&clen=425412913&dur=886.483&lmt=1733853056098658&mt=1734889991&fvip=1&keepalive=yes&fexp=51326932%2C51335594%2C51371294&c=IOS&txp=5537434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cbui%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRgIhANcOqM6_WcfndMccfH_QmbSRTZxj7ne9fjOVtdb83DL_AiEAqRJblTPdA3HavVzUYsNqYFf5SW6S9p0u2XA00tdi4dc%3D&lsparams=met%2Cmh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Crms%2Cinitcwndbps&lsig=AGluJ3MwRgIhAOtGpjamAKLdkgcv-S7RRehd5YvjFA6ofITnjqWwYAmzAiEAniNcBfyeO-lKoNv7Ae6cHiYAcxGjvjrm-o8TO28UhQk%3D"
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 3461, in process_info
  File "yt_dlp\YoutubeDL.py", line 3199, in dl
  File "yt_dlp\downloader\common.py", line 464, in download
  File "yt_dlp\downloader\http.py", line 367, in real_download
  File "yt_dlp\downloader\http.py", line 118, in establish_connection
  File "yt_dlp\YoutubeDL.py", line 4162, in urlopen
  File "yt_dlp\networking\common.py", line 117, in send
  File "yt_dlp\networking\_helper.py", line 208, in wrapper
  File "yt_dlp\networking\common.py", line 340, in send
  File "yt_dlp\networking\_requests.py", line 365, in _send
yt_dlp.networking.exceptions.HTTPError: HTTP Error 403: Forbidden
```

**Comment by bashonly** [comment]
Indeed the same issue as #11868, closing as duplicate

In your case, passing `-4` with your yt-dlp command may serve as a (temporary?) workaround
