### ISSUE TITLE
yt-dlp downloads broken video stream from YouTube 

### ISSUE THREAD

**Issue by TCH68k** [yt-dlp/yt-dlp#11882]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Hungary

### Provide a description that is worded well enough to be understood

Audio stream comes down all OK, but video stream is broken. If i try to play it (either the merged stream, or the separate videostream, kept by `-k`), i get this: [http://oscomp.hu/depot/yt-dlp-broken-video-stream.log](http://oscomp.hu/depot/yt-dlp-broken-video-stream.log)

This may be related to issue #11868.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.youtube.com/watch?v=3sYXVgvF6I4']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.12.13 from yt-dlp/yt-dlp [542166962] (zip)
[debug] Python 3.9.2 (CPython x86_64 64bit) - Linux-6.1.0-0.deb11.13-amd64-x86_64-with-glibc2.31 (OpenSSL 1.1.1w  11 Sep 2023, glibc 2.31)
[debug] exe versions: ffmpeg 5.1.6 (setts), ffprobe 5.1.6, rtmpdump 2.4
[debug] Optional libraries: certifi-2020.06.20, requests-2.25.1, sqlite3-3.34.1, urllib3-1.26.5
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Loaded 1837 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.12.13 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.12.13 from yt-dlp/yt-dlp)
[youtube] Extracting URL: https://www.youtube.com/watch?v=3sYXVgvF6I4
[youtube] 3sYXVgvF6I4: Downloading webpage
[youtube] 3sYXVgvF6I4: Downloading ios player API JSON
[youtube] 3sYXVgvF6I4: Downloading mweb player API JSON
[debug] [youtube] Extracting signature function js_03dbdfab_107
[debug] Loading youtube-sigfuncs.js_03dbdfab_107 from cache
[debug] Loading youtube-nsig.03dbdfab from cache
[debug] [youtube] Decrypted nsig jGEPDCuW6mDt4OD-k => ROrQqXvrfjewKQ
[youtube] 3sYXVgvF6I4: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec, channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 3sYXVgvF6I4: Downloading 1 format(s): 398+251
[debug] Invoking http downloader on "https://rr5---sn-qpbpu8-c0qs.googlevideo.com/videoplayback?expire=1734948301&ei=beFoZ76GBL7Wi9oPiqHN-AI&ip=188.143.5.74&id=o-AAmFnggaGahBm2lBaQ_Bw1s1zyaFc8B-2FrGu9gtunNf&itag=398&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&met=1734926701%2C&mh=PB&mm=31%2C29&mn=sn-qpbpu8-c0qs%2Csn-c0q7lnz7&ms=au%2Crdu&mv=m&mvi=5&pl=24&rms=au%2Cau&initcwndbps=3520000&bui=AfMhrI96t_Hy9oDt5GzQ0Suv3BKypRvGtr4WbAZMN46FD16jtyQZ1naeEccAsgz3_Xn0DjGlkA6r5GKX&spc=x-caUF1KH0ZsS2WUbkydge0Z_CYA0o0EZzX_GTRNeaLxyoS21cGm&vprv=1&svpuc=1&mime=video%2Fmp4&rqh=1&gir=yes&clen=62240146&dur=883.320&lmt=1726026028048961&mt=1734926222&fvip=5&keepalive=yes&fexp=51326932%2C51335594%2C51371294&c=IOS&txp=5537434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cbui%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRAIgLUpO5A_ta8d8XVhWcCgpIIMm0MdR4IRYZLd0EGQinL0CIHhUyzRC6XZn0_hfoei5RMgi85bi5e2-y0vGL-Qfo_w6&lsparams=met%2Cmh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Crms%2Cinitcwndbps&lsig=AGluJ3MwRQIhAJwKyIFSmfCVZJnrO7tbk1BvY1Bb3HiMDaUJQ1IYqwVwAiA8O5KDM0BXdLp5ZY4rz3LtZgAbpg97gahXHi4SYzz_VQ%3D%3D"
[download] Destination: Tolvajkergetők II. 12.： Egy csibész és egy szent [3sYXVgvF6I4].f398.mp4
[download] 100% of   59.36MiB in 00:00:05 at 10.34MiB/s
[debug] Invoking http downloader on "https://rr5---sn-qpbpu8-c0qs.googlevideo.com/videoplayback?expire=1734948301&ei=beFoZ76GBL7Wi9oPiqHN-AI&ip=188.143.5.74&id=o-AAmFnggaGahBm2lBaQ_Bw1s1zyaFc8B-2FrGu9gtunNf&itag=251&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&met=1734926701%2C&mh=PB&mm=31%2C29&mn=sn-qpbpu8-c0qs%2Csn-c0q7lnz7&ms=au%2Crdu&mv=m&mvi=5&pl=24&rms=au%2Cau&initcwndbps=3520000&bui=AfMhrI96t_Hy9oDt5GzQ0Suv3BKypRvGtr4WbAZMN46FD16jtyQZ1naeEccAsgz3_Xn0DjGlkA6r5GKX&spc=x-caUF1KH0ZsS2WUbkydge0Z_CYA0o0EZzX_GTRNeaLxyoS21cGm&vprv=1&svpuc=1&mime=audio%2Fwebm&rqh=1&gir=yes&clen=13911622&dur=883.341&lmt=1726021812686150&mt=1734926222&fvip=5&keepalive=yes&fexp=51326932%2C51335594%2C51371294&c=IOS&txp=5532434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cbui%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&sig=AJfQdSswRAIgYadPDHjlU-OOtchcCgmhbkyI1HTq48oEovZUVy4YwJ8CIFmQwqXEPOxjv9ZaiyaeEkVCTScakmF07IdT4EAhN_2t&lsparams=met%2Cmh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Crms%2Cinitcwndbps&lsig=AGluJ3MwRQIhAJwKyIFSmfCVZJnrO7tbk1BvY1Bb3HiMDaUJQ1IYqwVwAiA8O5KDM0BXdLp5ZY4rz3LtZgAbpg97gahXHi4SYzz_VQ%3D%3D"
[download] Destination: Tolvajkergetők II. 12.： Egy csibész és egy szent [3sYXVgvF6I4].f251.webm
[download] 100% of   13.27MiB in 00:00:01 at 10.34MiB/s
[Merger] Merging formats into "Tolvajkergetők II. 12.： Egy csibész és egy szent [3sYXVgvF6I4].webm"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:Tolvajkergetők II. 12.： Egy csibész és egy szent [3sYXVgvF6I4].f398.mp4' -i 'file:Tolvajkergetők II. 12.： Egy csibész és egy szent [3sYXVgvF6I4].f251.webm' -c copy -map 0:v:0 -map 1:a:0 -movflags +faststart 'file:Tolvajkergetők II. 12.： Egy csibész és egy szent [3sYXVgvF6I4].temp.webm'
Deleting original file Tolvajkergetők II. 12.： Egy csibész és egy szent [3sYXVgvF6I4].f398.mp4 (pass -k to keep)
Deleting original file Tolvajkergetők II. 12.： Egy csibész és egy szent [3sYXVgvF6I4].f251.webm (pass -k to keep)
```

**Comment by coletdjnz** [comment]
Plays fine for me in mpv, same formats and all. I don't see those errors.
 Your log suggests it downloaded fine, so probably either an issue with playback on your system or youtube somehow served you a corrupted file (unlikely)..?

Won't be https://github.com/yt-dlp/yt-dlp/issues/11868 as you wouldn't be able to download it

**Comment by TCH68k** [comment]
I don't know, but if i pass `--extractor-arg "youtube:player_client=ios" -f "bv[protocol=m3u8_native]+ba[protocol=m3u8_native]"` along with the URL - as suggested in #11868 - then i get a working video.

**Comment by coletdjnz** [comment]
> I don't know, but if i pass `--extractor-arg "youtube:player_client=ios" -f "bv[protocol=m3u8_native]+ba[protocol=m3u8_native]"` along with the URL - as suggested in #11868 - then i get a working video.

That would effectively select a different format. Perhaps your system cannot play av1?

**Comment by TCH68k** [comment]
> Perhaps your system cannot play av1?

Indeed it cannot. I simply forgot. My program filters av1, so i did not have to pay attention for that, but now, that everything gives 403 in it, i switched back to download with yt-dlp and i did not consider that it can download av1 as default.
Thanks for pointing out.

The issue is invalid, sorry about that.
