### ISSUE TITLE
Peloton IDNA label too long

### ISSUE THREAD

**Issue by mccalls77** [yt-dlp/yt-dlp#11881]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Unites States/New York

### Provide a description that is worded well enough to be understood

First time trying Peloton videos. I've tried from Windows, Linux, and MacOS and get this idna label too long message that I cant find too much info about.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://members.onepeloton.com/classes/player/491a1d94f7394c31bf15447f84943cf8', '--username', 'PRIVATE', '--password', 'PRIVATE']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.12.13 from yt-dlp/yt-dlp [542166962] (win_exe)
[debug] Python 3.10.11 (CPython AMD64 64bit) - Windows-10-10.0.22631-SP0 (OpenSSL 1.1.1t  7 Feb 2023)
[debug] exe versions: ffmpeg N-118108-g0a6388d1da-20241222 (setts), ffprobe N-118108-g0a6388d1da-20241222
[debug] Optional libraries: Cryptodome-3.21.0, brotli-1.1.0, certifi-2024.08.30, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.40.1, urllib3-2.2.3, websockets-14.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1837 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.12.13 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.12.13 from yt-dlp/yt-dlp)
[peloton] Extracting URL: https://members.onepeloton.com/classes/player/491a1d94f7394c31bf15447f84943cf8
[peloton] 491a1d94f7394c31bf15447f84943cf8: Starting session
[peloton] 491a1d94f7394c31bf15447f84943cf8: Logging in
[peloton] 491a1d94f7394c31bf15447f84943cf8: Starting session
[peloton] 491a1d94f7394c31bf15447f84943cf8: Downloading JSON metadata
[peloton] 491a1d94f7394c31bf15447f84943cf8: Downloading token
[peloton] 491a1d94f7394c31bf15447f84943cf8: Downloading m3u8 information
ERROR: encoding with 'idna' codec failed (UnicodeError: label too long)
Traceback (most recent call last):
  File "encodings\idna.py", line 165, in encode
UnicodeError: label too long

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1624, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1780, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1839, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2866, in process_video_result
  File "yt_dlp\YoutubeDL.py", line 2576, in _calc_headers
  File "yt_dlp\cookies.py", line 1383, in get_cookies_for_url
  File "yt_dlp\utils\networking.py", line 159, in normalize_url
UnicodeError: encoding with 'idna' codec failed (UnicodeError: label too long)
```

**Comment by bashonly** [comment]
could you add these options to your command and share the output, please?

```
-vUF --print urls
```

**Comment by mccalls77** [comment]
Running the same command today works for me, it looks like Python updated. So I appear to be good to go now. For what it's worth, here is the output you requestes anyway. Thanks for taking a look.

[debug] Command-line config: ['-vUF', '-print', 'urls', 'https://members.onepeloton.com/classes/player/ad4b2c6428c54bdbb2bd6b78576d9bf3', '--username', 'PRIVATE', '--password', 'PRIVATE']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.12.13 from yt-dlp/yt-dlp [542166962] (darwin_exe)
[debug] Python 3.12.8 (CPython arm64 64bit) - macOS-15.2-arm64-arm-64bit (OpenSSL 3.0.15 3 Sep 2024)
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.21.0, brotli-1.1.0, certifi-2024.08.30, curl_cffi-0.7.1, mutagen-1.47.0, requests-2.32.3, sqlite3-3.45.3, urllib3-2.2.3, websockets-14.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1837 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.12.13 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.12.13 from yt-dlp/yt-dlp)
[generic] Extracting URL: urls
ERROR: [generic] 'urls' is not a valid URL. Set --default-search "ytsearch" (or run  yt-dlp "ytsearch:urls" ) to search YouTube
  File "yt_dlp/extractor/common.py", line 742, in extract
  File "yt_dlp/extractor/generic.py", line 2361, in _real_extract

[peloton] Extracting URL: https://members.onepeloton.com/classes/player/ad4b2c6428c54bdbb2bd6b78576d9bf3
[peloton] ad4b2c6428c54bdbb2bd6b78576d9bf3: Starting session
[peloton] ad4b2c6428c54bdbb2bd6b78576d9bf3: Logging in
[peloton] ad4b2c6428c54bdbb2bd6b78576d9bf3: Starting session
[peloton] ad4b2c6428c54bdbb2bd6b78576d9bf3: Downloading JSON metadata
[peloton] ad4b2c6428c54bdbb2bd6b78576d9bf3: Downloading token
[peloton] ad4b2c6428c54bdbb2bd6b78576d9bf3: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec, channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[info] Available formats for ad4b2c6428c54bdbb2bd6b78576d9bf3:
ID                                     EXT RESOLUTION FPS │   FILESIZE   TBR PROTO │ VCODEC        VBR ACODEC     MORE INFO
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Audio_Selector_Group_1-More_Instructor mp4 audio only     │                  m3u8  │ audio only        unknown    [eng] More Instructor
Audio_Selector_Group_1-More_Music      mp4 audio only     │                  m3u8  │ audio only        unknown    [eng] More Music
Audio_Selector_Group_1-Original_Mix    mp4 audio only     │                  m3u8  │ audio only        unknown    [eng] Original Mix
408                                    mp4 512x288     30 │ ~ 97.47MiB  409k m3u8  │ avc1.4d4015  409k video only
448                                    mp4 640x360     30 │ ~106.95MiB  448k m3u8  │ avc1.4d401e  448k video only
646                                    mp4 960x540     30 │ ~154.30MiB  647k m3u8  │ avc1.4d401f  647k video only
1163                                   mp4 1280x720    30 │ ~277.63MiB 1164k m3u8  │ avc1.4d401f 1164k video only
4681                                   mp4 1920x1080   30 │ ~  1.09GiB 4682k m3u8  │ avc1.4d4028 4682k video only

**Comment by bashonly** [comment]
`--print urls` not `-print urls`, but if you aren't experiencing the error anymore it doesn't really matter

**Comment by joachim97** [comment]
yt-dlp.exe --cookies www.cda.pl_cookies.txt https://www.cda.pl/video/22733152a1/vfilm?wersja=1080p -vUF --print urls
[debug] Command-line config: ['--cookies', 'www.cda.pl_cookies.txt', 'https://www.cda.pl/video/22733152a1/vfilm?wersja=1080p', '-vUF', '--print', 'urls']
[debug] Encodings: locale cp1250, fs utf-8, pref cp1250, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2025.02.19 from yt-dlp/yt-dlp [4985a4041] (win_exe)
[debug] Python 3.10.11 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1t  7 Feb 2023)
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.21.0, brotli-1.1.0, certifi-2025.01.31, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.40.1, urllib3-2.3.0, websockets-15.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1841 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2025.02.19 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2025.02.19 from yt-dlp/yt-dlp)
[CDA] Extracting URL: https://www.cda.pl/video/22733152a1/vfilm?wersja=1080p
[CDA] 22733152a1: Downloading webpage
[CDA] 22733152a1: Fetching 360p url
[CDA] 22733152a1: Fetching 480p url
[CDA] 22733152a1: Fetching 720p url
[CDA] 22733152a1: Fetching 1080p url
ERROR: encoding with 'idna' codec failed (UnicodeError: label empty or too long)
Traceback (most recent call last):
  File "encodings\idna.py", line 163, in encode
UnicodeError: label empty or too long

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1637, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1793, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1852, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2879, in process_video_result
  File "yt_dlp\YoutubeDL.py", line 2589, in _calc_headers
  File "yt_dlp\cookies.py", line 1383, in get_cookies_for_url
  File "yt_dlp\utils\networking.py", line 159, in normalize_url
UnicodeError: encoding with 'idna' codec failed (UnicodeError: label empty or too long)
