### ISSUE TITLE
[Question] clearer documentation for using this as a python module

### ISSUE THREAD

**Issue by ghost** [yt-dlp/yt-dlp#1188]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

Youtube-DL had support for using it as a python module, and it had examples in the README.md, why doesn't this project have?

**Comment by pjalsGit** [comment]
for some reason it ALWAYS thinks the URL/Search Term is 'h'

**Comment by sahaynitin** [comment]
> ## Checklist
> * [x]  I'm asking a question
> * [x]  I've looked through the README and FAQ for similar questions
> * [x]  I've searched the bugtracker for similar questions including closed ones
> 
> ## Question
> Youtube-DL had support for using it as a python module, and it had examples in the README.md, why doesn't this project have?
