### ISSUE TITLE
Download from Dropout.tv not working using --username and --password, --cookies

### ISSUE THREAD

**Issue by Edit-the-Kid** [yt-dlp/yt-dlp#11888]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United States

### Provide a description that is worded well enough to be understood

Windows
New to this, but as far as I can tell, I haven't done anything wrong.
Have an active Dropout account. Username and password are 100% correct. Username is an email address with @ sign in it and password also has special characters. Both were in quotes.
I've also tried --cookies with a getcookies.txt file, nada. Tried other Dropout videos too.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--username', 'PRIVATE', '--password', 'PRIVATE', 'https://www.dropout.tv/dimension-20-burrow-s-end-the-complete-experience/videos/the-red-warren']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.12.13 from yt-dlp/yt-dlp [542166962] (win_exe)
[debug] Python 3.10.11 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1t  7 Feb 2023)
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.21.0, brotli-1.1.0, certifi-2024.08.30, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.40.1, urllib3-2.2.3, websockets-14.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1837 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.12.13 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.12.13 from yt-dlp/yt-dlp)
[Dropout] Extracting URL: https://www.dropout.tv/dimension-20-burrow-s-end-the-complete-experience/videos/the-red-warren
[Dropout] the-red-warren: Getting authenticity token
[Dropout] the-red-warren: Logging in
[Dropout] the-red-warren: Downloading webpage
[vhx:embed] Downloading login token
[vhx:embed] Logging in
ERROR: [vhx:embed] 2920064: Unable to log in; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 739, in extract
  File "yt_dlp\extractor\common.py", line 645, in initialize
  File "yt_dlp\extractor\vimeo.py", line 76, in _perform_login
```

**Comment by bashonly** [comment]
try using a [netrc file](https://github.com/yt-dlp/yt-dlp?tab=readme-ov-file#authentication-with-netrc)

**Comment by Edit-the-Kid** [comment]
Yoooo!
Took me an hour to figure out what a netrc file is, but that worked. Guess it couldn't read the username/password straight up.

**Comment by bashonly** [comment]
The problem is that `--username`/`--password` passes your credentials to all extractors, including vhx/vimeo, which was causing the error (since your credentials are only good for dropout). With the netrc file, you can specify which extractor the credentials belong to

**Comment by bashonly** [comment]
There's another open issue that is tracking this, but I can't find it right now

**Comment by Edit-the-Kid** [comment]
Oh, that makes sense. Will use netrc in the future and pray Dropout doesn't change stuff on their end or whatever. Thanks for your help!

**Comment by rdhar** [comment]
For anyone else landing here for Windows, create a ".netrc" file consisting of your login:

```txt
machine dropout login EMAIL password REDACTED
```

Assuming you have both your "yt-dlp.exe" and ".netrc" files in your Downloads folder, run: 

```powershell
C:\Users\Name\Downloads> .\yt-dlp --netrc --netrc-location ".\.netrc" "https://watch.dropout.tv/series/videos/id"
```
