### ISSUE TITLE
Question for best use of the -sleep option for YouTube

### ISSUE THREAD

**Issue by sebi-berlin** [yt-dlp/yt-dlp#11897]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Hello, the -sleep options seem to be exactly what I am looking for. I want to have yt-dlp to "sleep" after each segment download as long as the fragment playback would be, so that YouTube thinks I am watching a video, rather than downloading nonstop. 

Could anyone help me with the best option for this? As I guess segments duration might differ from format to format, I think it would be the best for me, to use the longest pause between each segment so that I just run my downloads during the night. 

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by sebi-berlin** [comment]
So I tried all options now, but still all segments are getting downloaded as fast as possible. This doesn't make too much sense, as this ain't normal watchers behaviour and could still get detected. :-( My IPv6 is already banned since a week and I don't want to get my IPv4 get banned too. My ISP doesn't let me change my IP.

**Comment by pukkandan** [comment]
`--sleep` only waits between videos, not between fragments. Is this what you want?

```
-r, --limit-rate RATE           Maximum download rate in bytes per second,
                                e.g. 50K or 4.2M
```

**Comment by sebi-berlin** [comment]
> `--sleep` only waits between videos, not between fragments. Is this what you want?
> 
> ```
> -r, --limit-rate RATE           Maximum download rate in bytes per second,
>                                 e.g. 50K or 4.2M
> ```

Oh yeah, thank you so much. Totally overlooked that one. 
So I am currently using
```
yt-dlp -4 -r 3M --sleep-requests 3 --sleep-interval 60 --max-sleep-interval 120
```
Hope with this one I will be safe...

**Comment by DesertBanana** [comment]
> > `--sleep` only waits between videos, not between fragments. Is this what you want?
> > ```
> > -r, --limit-rate RATE           Maximum download rate in bytes per second,
> >                                 e.g. 50K or 4.2M
> > ```
> 
> Oh yeah, thank you so much. Totally overlooked that one. So I am currently using
> 
> ```
> yt-dlp -4 -r 3M --sleep-requests 3 --sleep-interval 60 --max-sleep-interval 120
> ```
> 
> Hope with this one I will be safe...

Did this strategy work? Or did you try something else?
