### ISSUE TITLE
Signatures on Android, iOS and MWEB direct stream links?

### ISSUE THREAD

**Issue by TCH68k** [yt-dlp/yt-dlp#11891]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Are there any kind of signatures - like the `nsig` on the web_creator - on the other players' direct stream links? I see `sig` and `lsig`; are they needed to be deciphered too? I see no trace of this in `extractor/youtube.py`, just the `nsig`.

Thanks in advance.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by coletdjnz** [comment]
these are usually present on videoplayback urls regardless of client, but only on js clients you need to process them

**Comment by TCH68k** [comment]
Which ones are the JS clients? The web_* ones?

**Comment by bashonly** [comment]
Look in the source code. The JS clients are any client that doesn't have `'REQUIRE_JS_PLAYER': False`

https://github.com/yt-dlp/yt-dlp/blob/3905f64920ed078d9eeb5640884f5854e01d744d/yt_dlp/extractor/youtube.py#L76-L289

**Comment by TCH68k** [comment]
I see. And i also see, that both iOS and Android have the `REQUIRE_PO_TOKEN` property set to true now... :(

[In this commit](https://github.com/yt-dlp/yt-dlp/commit/9f42e68a74f3f00b0253fe70763abd57cac4237b) i read, that there are "formats" which are not protected by po tokens; are those "formats" are the streams themselves? So, basically i can simply find the non po token-protected ones and filter the rest?

BTW, if these formats are po token protected now, then why yt-dlp still work for me on any video? Or maybe it was just sheer luck?

Any chance for a future solution against the po tokens? Maybe an external library, or program?

**Comment by bashonly** [comment]
> are those "formats" are the streams themselves?

yes

> BTW, if these formats are po token protected now, then why yt-dlp still work for me on any video? Or maybe it was just sheer luck?

By default, yt-dlp only extracts formats that do not require a PO token

> Any chance for a future solution against the po tokens? Maybe an external library, or program?

https://github.com/yt-dlp/yt-dlp/wiki/Extractors#po-token-guide

**Comment by TCH68k** [comment]
> https://github.com/yt-dlp/yt-dlp/wiki/Extractors#po-token-guide

If i install those two plugins for yt-dlp, then yt-dlp will be able to generate po tokens for external applications? Or just for itself?

**Comment by turbe** [comment]
I would like to ask if it is necessary to set a cookie when downloading after getting the download link, and how the cookie is generated

**Comment by TCH68k** [comment]
If i generate a po token and visitor data with an external generator, then how can i make those direct stream links accessable with them? I've read that for the po token, the argument `pot` is needed. But i still get 403, if i append `&pot=<token here>` to the end of the stream link.

What i am doing wrong?

**Comment by turbe** [comment]
That's what I was going to ask.

when i after _decrypt_signature() and _decrypt_nsig() to get links, and accessing the link on Google Chrome still gets 403. So, what else do I need to do if I want to access the link properly on chrome browser?

**Comment by bashonly** [comment]
Are you two actually using yt-dlp? Or just asking for help in your own reverse engineering? If the latter, this is abuse of the "Question" issue template. This is not a general forum for reverse engineering. It is a bug tracker for yt-dlp

**Comment by TCH68k** [comment]
As a matter of fact, i do use yt-dlp. And [i've explicitly asked](#issuecomment-2561175926) if yt-dlp is able to generate po tokens for external applications. Using yt-dlp from other applications seems to be a valid use case of yt-dlp for me.

**Comment by bashonly** [comment]
yt-dlp doesn't generate PO tokens

**Comment by TCH68k** [comment]
[With these two plugins installed.](https://github.com/yt-dlp/yt-dlp/wiki/Extractors#po-token-guide) This two yt-dlp plugins are for po token generation. Question is, if they are able to generate po tokens only for internal usage of yt-dlp, or yt-dlp can print these tokens out?

**Comment by bashonly** [comment]
Those plugins are not yt-dlp
