### ISSUE TITLE
--write-info-json writes a strange URL

### ISSUE THREAD

**Issue by axcore** [yt-dlp/yt-dlp#119]
## Checklist

- [ ] I'm reporting a broken site support issue
- [ x] I've verified that I'm running yt-dlp version **2021.02.24**
- [x ] I've checked that all provided URLs are alive and playable in a browser
- [x ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ x] I've searched the bugtracker for similar bug reports including closed ones
- [ x] I've read bugs section in FAQ

## Verbose log

```
/home/ra/.local/bin/yt-dlp --write-info-json -v https://www.youtube.com/watch?v=tPEE9ZwTmy0
[debug] Command-line config: ['--write-info-json', '-v', 'https://www.youtube.com/watch?v=tPEE9ZwTmy0']
[debug] Loading archive file None
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] yt-dlp version 2021.02.24 
[debug] Python version 3.8.5 (CPython 64bit) - Linux-5.4.0-65-generic-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4
[debug] Proxy map: {}
[youtube] tPEE9ZwTmy0: Downloading webpage
[debug] Sort order given by user: 
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] Downloading format(s) 244+251
[info] Writing video metadata as JSON to: Shortest Video on Youtube [tPEE9ZwTmy0].info.json
[download] Shortest Video on Youtube [tPEE9ZwTmy0].webm has already been downloaded

```

## Description

`--write-info-json` creates a metadata file ending `.info.json`. 

The metadata file includes the URL of the video downloaded, in the `webpage_url` field. Compare the field created by youtube-dl:

`"webpage_url": "https://www.youtube.com/watch?v=tPEE9ZwTmy0"`

...with the field created by yt-dlp:

`"webpage_url": "https://www.youtube.com/watch?v=tPEE9ZwTmy0&has_verified=1&bpctr=9999999999"`

Presumably this is not deliberate but an oversight. Both URLs work in a web browser, but the longer URL does not match the one reported by yt-dlp in other contexts.

A longer URL is not generated for every video. I'm not sure why. For example, every video in [this playlist](https://www.youtube.com/watch?v=tPEE9ZwTmy0&list=PLHJH2BlYG-EEBtw2y1njWpDukJSTs8Qqx) generates a long URL, but the famous [Me at the zoo video](https://www.youtube.com/watch?v=jNQXAC9IVRw) does not.

**Comment by pukkandan** [comment]
> https://www.youtube.com/watch?v=tPEE9ZwTmy0&has_verified=1&bpctr=9999999999

This is the actual URL that yt-dlp uses for getting video data `&has_verified=1&bpctr=9999999999` are required to work around certain youtube issues. How it got into the infojson, I have no idea and will investigate
