### ISSUE TITLE
No video formats found with youtube:player_client=all and live-from-start in livestreams

### ISSUE THREAD

**Issue by ThePhoenix576** [yt-dlp/yt-dlp#11907]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Indonesia

### Provide a description that is worded well enough to be understood

Hi, so since the latest stable [2024.12.23](https://github.com/yt-dlp/yt-dlp/releases/tag/2024.12.23) and even on the master [2024.12.23.232653](https://github.com/yt-dlp/yt-dlp-master-builds/releases/tag/2024.12.23.232653) . YT-DLP has been failing for me to extract the max resolution of a current live stream (ongoing). I usually use this to automatically create a VOD grabber so that it can automatically download the processed VODs after the live is over.

Here is the command that i usually use to extract the resolution.
`yt-dlp --extractor-args 'youtube:player_client=all' --live-from-start --print width 'https://www.youtube.com/@Valkyrae/live'`

I used all player client to make sure that I don't need to touch it anymore and it can always get the largest available resolution since default limits it to 1080p, I used live from start so it will show the resolutions higher than 1080p in the livestream.

But now it just results in NA. After further investigation, it seems like it can't find any video formats even though I have set the YouTube player client to all. The interesting thing is that it will work when i just use youtube:player_client=android_vr instead of all. 

Doesn't the "all" option should also include "android_vr"? It seems to be included but it doesn't seem to use the formats available from the android_vr client.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--extractor-args', 'youtube:player_client=all', '--live-from-start', '--print', 'width', 'https://www.youtube.com/@Valkyrae/live']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version master@2024.12.23.232653 from yt-dlp/yt-dlp-master-builds [65cf46cdd] (darwin_exe)
[debug] Python 3.13.1 (CPython arm64 64bit) - macOS-14.7.2-arm64-arm-64bit-Mach-O (OpenSSL 3.0.15 3 Sep 2024)
[debug] exe versions: ffmpeg 7.0.2 (setts), ffprobe 7.0.2, phantomjs 2.1.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.21.0, brotli-1.1.0, certifi-2024.12.14, curl_cffi-0.7.1, mutagen-1.47.0, requests-2.32.3, sqlite3-3.45.3, urllib3-2.3.0, websockets-14.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1837 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-master-builds/releases/latest
Latest version: master@2024.12.23.232653 from yt-dlp/yt-dlp-master-builds
yt-dlp is up to date (master@2024.12.23.232653 from yt-dlp/yt-dlp-master-builds)
[youtube:tab] Extracting URL: https://www.youtube.com/@Valkyrae/live
[youtube:tab] @Valkyrae/live: Downloading webpage
[youtube] Extracting URL: https://www.youtube.com/watch?v=gko77bw1CT4
[youtube] gko77bw1CT4: Downloading webpage
[youtube] gko77bw1CT4: Downloading ios player API JSON
[youtube] gko77bw1CT4: Downloading ios music player API JSON
[youtube] gko77bw1CT4: Downloading ios creator player API JSON
[youtube] gko77bw1CT4: Downloading web embedded client config
[youtube] gko77bw1CT4: Downloading player 03dbdfab
[youtube] gko77bw1CT4: Downloading web embedded player API JSON
[youtube] gko77bw1CT4: Downloading web safari player API JSON
[youtube] gko77bw1CT4: Downloading web music client config
[youtube] gko77bw1CT4: Downloading web music player API JSON
[youtube] gko77bw1CT4: Downloading web creator player API JSON
[youtube] gko77bw1CT4: Downloading tv player API JSON
[youtube] gko77bw1CT4: Downloading tv embedded player API JSON
[youtube] gko77bw1CT4: Downloading mweb player API JSON
[youtube] gko77bw1CT4: Downloading android player API JSON
[youtube] gko77bw1CT4: Downloading android music player API JSON
[youtube] gko77bw1CT4: Downloading android creator player API JSON
[youtube] gko77bw1CT4: Downloading android vr player API JSON
[youtube] gko77bw1CT4: Downloading MPD manifest
WARNING: [youtube] gko77bw1CT4: web client dash formats require a PO Token which was not provided. They will be skipped as they may yield HTTP Error 403. You can manually pass a PO Token for this client with --extractor-args "youtube:po_token=web+XXX. For more information, refer to  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#po-token-guide . To enable these broken formats anyway, pass --extractor-args "youtube:formats=missing_pot"
[youtube] gko77bw1CT4: Downloading MPD manifest
[youtube] gko77bw1CT4: Downloading MPD manifest
[youtube] gko77bw1CT4: Downloading MPD manifest
[youtube] gko77bw1CT4: Downloading MPD manifest
[youtube] gko77bw1CT4: Downloading MPD manifest
[youtube] gko77bw1CT4: Downloading MPD manifest
ERROR: [youtube] gko77bw1CT4: This video is not available
  File "yt_dlp/extractor/common.py", line 742, in extract
  File "yt_dlp/extractor/youtube.py", line 4541, in _real_extract
  File "yt_dlp/extractor/common.py", line 1276, in raise_no_formats
```

**Comment by coletdjnz** [comment]
Don't use player-client=all except for testing/debugging purposes. It is not supported for general use. 

Anyways, I can reproduce if I don't pass a PO Token for the WEB client. This causes the WEB client formats to be skipped. You need to pass a PO Token for WEB client, or skip WEB client extraction with `--extractor-args "youtube:player-client=all,-web`.

https://github.com/yt-dlp/yt-dlp/wiki/Extractors#po-token-guide

There seems to be some bug where other clients' DASH formats are not being returned when the WEB DASH ones are automatically skipped due to no PO Token.

**Comment by ThePhoenix576** [comment]
> There seems to be some bug where other clients' DASH formats are not being returned when the WEB DASH ones are automatically skipped due to no PO Token, in this particular case.

Ah I see. So that means the "all" option should've worked just fine even without the PO Token for this particular case but because of the bug it just skips DASH formats.
