### ISSUE TITLE
Download from a list of url and multiple downloads

### ISSUE THREAD

**Issue by soullessj** [yt-dlp/yt-dlp#11909]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Hi, came across this program recently, still figuring it out but so far working well,
Just wanted to ask if it was possible to download from a list or url and also to do more than one at a time,
Had it working by manually doing 1 in different windows, but want to know if its possible to import/run the program and download from a saved list or url and run them all at the same time,

thx

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by seproDev** [comment]
With `-a` you can pass a text file containing a list of links https://github.com/yt-dlp/yt-dlp?tab=readme-ov-file#filesystem-options

A single yt-dlp instance can't run multiple downloads in parallel. I would also not recommend this. If downloading from Youtube you should instead add some of the sleep options to slow downloading/extraction down since otherwise your IP might get blocked.

**Comment by StefanLobbenmeier** [comment]
> also to do more than one at a time
> manually doing 1 in different windows

You might be looking for gnu parallel: https://www.gnu.org/software/parallel/, which allows you to easily run shell commands in parallel
