### ISSUE TITLE
Support invidious (youtube proxy) as a workaround to signing in

### ISSUE THREAD

**Issue by gptlang** [yt-dlp/yt-dlp#11903]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Due to #10128, you need to either sign in (cookies from browser) or have an unblocked IP. 

This is true even if you pass in an invidious link where it defaults to extracting information from YouTube and fails.

I propose that we instead use the invidious API where possible to extract the data instead when given an invidious instance link.

API: https://docs.invidious.io/api/

Notes: [Invidious companion](https://github.com/iv-org/invidious-companion/) is currently in the works which should make this even easier in the future.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '-f', 'm4a', '--embed-metadata', '-o', '%(id)s.%(ext)s', '--', 'kGATkUHSVCQ']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.12.23 from yt-dlp/yt-dlp [65cf46cdd]
[debug] Lazy loading extractors is disabled
[debug] Python 3.13.1 (CPython x86_64 64bit) - Linux-6.11.11-300.fc41.x86_64-x86_64-with-glibc2.40 (OpenSSL 3.2.2 4 Jun 2024, glibc 2.40)
[debug] exe versions: ffmpeg 7.0.2 (setts), ffprobe 7.0.2
[debug] Optional libraries: Crypto-broken 2.6.1, brotli-1.1.0, certifi-2023.05.07, requests-2.32.3, sqlite3-3.46.1, urllib3-1.26.20
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Loaded 1837 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.12.23 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.12.23 from yt-dlp/yt-dlp)
[youtube] Extracting URL: kGATkUHSVCQ
[youtube] kGATkUHSVCQ: Downloading webpage
[youtube] kGATkUHSVCQ: Downloading ios player API JSON
[youtube] kGATkUHSVCQ: Downloading mweb player API JSON
ERROR: [youtube] kGATkUHSVCQ: Sign in to confirm you’re not a bot. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies. Also see  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies  for tips on effectively exporting YouTube cookies
  File "/home/acheong/.local/lib/python3.13/site-packages/yt_dlp/extractor/common.py", line 742, in extract
    ie_result = self._real_extract(url)
  File "/home/acheong/.local/lib/python3.13/site-packages/yt_dlp/extractor/youtube.py", line 4541, in _real_extract
    self.raise_no_formats(reason, expected=True)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/acheong/.local/lib/python3.13/site-packages/yt_dlp/extractor/common.py", line 1276, in raise_no_formats
    raise ExtractorError(msg, expected=expected, video_id=video_id)
```

**Comment by absidue** [comment]
@gptlang Please do not abuse Invidious instances for downloading, they are already getting IP blocked a lot faster than you downloading with yt-dlp. All this selfish act will do is result in the Invidious instance going down and being unusable for everyone. Please just learn to change your IP address yourself.

**Comment by Grub4K** [comment]
Agreed. Closing as off scope.

**Comment by gptlang** [comment]
@absidue I host my own invidious instance. I don't think it'd be wrong to download from my own instance. Using the API would mean that you won't be able to use most public instances for downloading since they disable it explicitly to prevent abuse.

**Comment by bashonly** [comment]
@gptlang Support will not be added. You are free to write a [plugin](https://github.com/yt-dlp/yt-dlp/wiki/Plugin-Development) that you can use to download from your own instance.
