### ISSUE TITLE
Add cookie extraction support for Floorp

### ISSUE THREAD

**Issue by 2husecondary** [yt-dlp/yt-dlp#11905]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Floorp, which is a derivative of Firefox, happens to have cookie extraction unsupported. I believe support for it could be added since it's basically the same as Firefox.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--cookies-from-browser', 'floorp', 'https://www.youtube.com/watch?v=-LhZ5R_ROns']

Usage: yt-dlp.exe [OPTIONS] URL [URL...]

yt-dlp.exe: error: unsupported browser specified for cookies: "floorp". Supported browsers are: brave, chrome, chromium, edge, firefox, opera, safari, vivaldi, whale
```

**Comment by dirkf** [comment]
Have you tried the documented option suffixes (`:PROFILE[::CONTAINER]`) that tell the cookie-from-browser code how your browser's cookie store differs from FF?

**Comment by pukkandan** [comment]
See pinned issue https://github.com/yt-dlp/yt-dlp/issues/2903
