### ISSUE TITLE
How to request to python api

### ISSUE THREAD

**Issue by fc1104** [yt-dlp/yt-dlp#11919]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [x] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

china

### Provide a description that is worded well enough to be understood

[debug] Not all the video resource data have been obtained.
[debug]I have written an example of downloading youtube video through python code to stream back. There is no problem when I pass the apifox test locally, and I can get the final video data. However, when the front end calls, it only scans more than 3000 bytes of data. Why, how should the front end call?
My current testing process: the backend uses the fastapi framework, starts the project, accesses the project address, and calls it through fetch in the console. The code is as follows:
[debug]
[debug]python：
    @classmethod
    async def download_youtube_video_by_yt_dlp(cls, schema):
        """
        yt-dlp 下载原始视频格式
        """
        # 获取当前脚本文件的绝对路径
        current_dir = os.path.dirname(os.path.abspath(__file__))

        # 绝对路径，假设 cookies.txt 位于项目根目录
        cookies_path = os.path.join(current_dir, 'cookies.txt')
        ydl_opts = {
            'format': 'bestvideo',
            'outtmpl': '%(title)s.%(ext)s',
            'cachedir': False,  # 避免缓存文件占用过多磁盘空间，可根据需求调整
            'nopart': True,  # 禁用分段下载（如果不需要的话，根据实际情况调整）
            'nooverwrites': True,  # 不覆盖已有文件，可按需修改
            'quiet': True,  # 减少不必要的输出信息
            'user_agent': "Apifox/1.0.0 (https://apifox.com)",
            # 'user_agent': "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36",
            'referer': 'https://www.youtube.com',
            'no_check_certificate': True,
            'Connection': 'keep-alive'
        }

        def generate():
            with yt_dlp.YoutubeDL(ydl_opts) as ydl:
                with yt_dlp.YoutubeDL(ydl_opts) as ydl:
                    try:
                        info_dict = ydl.extract_info(schema.url, download=False)
                        print(info_dict)
                        url = info_dict['url']
                        print(f"使用的流 URL: {url}")
                        # 使用requests获取视频流并返回
                        with ydl.urlopen(url) as stream:
                            while True:
                                data = stream.read(4 * 1024 * 1024)  # 每次读取4MB数据，可调整大小
                                print(f"读取了 {len(data)} 字节数据")
                                if not data:
                                    print("数据流读取完毕。")
                                    break
                                yield data
                    except yt_dlp.DownloadError as e:
                        print(f"下载出现错误: {e}")
                    except Exception as e:
                        print(f"其他错误: {e}")
        print('流数据读取完成。。。。')
        return StreamingResponse(generate(), media_type='video/mp4', headers={
            'Transfer-Encoding': 'chunked',
            'Content-Disposition': 'attachment; filename="video.mp4"'
        })

js：
try {
    const response = await fetch("apiurl", {
        method: 'POST',
        headers: {
            'Content-Type': 'application/json',
            'X-Signature': 'xvxvxv332'
        },
        body: JSON.stringify({
            url: "https://youtube.com/shorts/68kf4Xd63rc?si=aRexNBocRnLX6E4A"
        })
    });
    if (!response.ok) {
                    throw new Error('网络请求失败');
                }
                const chunks = [];
                const reader = response.body.getReader();
                let { done, value } = await reader.read();
                while (!done) {
                    chunks.push(value);
                    ({ done, value } = await reader.read());
                }
                const downloadLink = document.createElement('a');
                const blob = new Blob(chunks, { type: 'video/mp4' });
                const url = URL.createObjectURL(blob);
                downloadLink.href = url;
                downloadLink.download = 'video.mp4';
                document.body.appendChild(downloadLink);
                downloadLink.click();
                
            } catch (error) {
                console.error('下载出错:', error);
}

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Not all the video resource data have been obtained.
I have written an example of downloading youtube video through python code to stream back. There is no problem when I pass the apifox test locally, and I can get the final video data. However, when the front end calls, it only scans more than 3000 bytes of data. Why, how should the front end call?
My current testing process: the backend uses the fastapi framework, starts the project, accesses the project address, and calls it through fetch in the console. The code is as follows:

python：
    @classmethod
    async def download_youtube_video_by_yt_dlp(cls, schema):
        """
        yt-dlp 下载原始视频格式
        """
        # 获取当前脚本文件的绝对路径
        current_dir = os.path.dirname(os.path.abspath(__file__))

        # 绝对路径，假设 cookies.txt 位于项目根目录
        cookies_path = os.path.join(current_dir, 'cookies.txt')
        ydl_opts = {
            'format': 'bestvideo',
            'outtmpl': '%(title)s.%(ext)s',
            'cachedir': False,  # 避免缓存文件占用过多磁盘空间，可根据需求调整
            'nopart': True,  # 禁用分段下载（如果不需要的话，根据实际情况调整）
            'nooverwrites': True,  # 不覆盖已有文件，可按需修改
            'quiet': True,  # 减少不必要的输出信息
            'user_agent': "Apifox/1.0.0 (https://apifox.com)",
            # 'user_agent': "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36",
            'referer': 'https://www.youtube.com',
            'no_check_certificate': True,
            'Connection': 'keep-alive'
        }

        def generate():
            with yt_dlp.YoutubeDL(ydl_opts) as ydl:
                with yt_dlp.YoutubeDL(ydl_opts) as ydl:
                    try:
                        info_dict = ydl.extract_info(schema.url, download=False)
                        print(info_dict)
                        url = info_dict['url']
                        print(f"使用的流 URL: {url}")
                        # 使用requests获取视频流并返回
                        with ydl.urlopen(url) as stream:
                            while True:
                                data = stream.read(4 * 1024 * 1024)  # 每次读取4MB数据，可调整大小
                                print(f"读取了 {len(data)} 字节数据")
                                if not data:
                                    print("数据流读取完毕。")
                                    break
                                yield data
                    except yt_dlp.DownloadError as e:
                        print(f"下载出现错误: {e}")
                    except Exception as e:
                        print(f"其他错误: {e}")
        print('流数据读取完成。。。。')
        return StreamingResponse(generate(), media_type='video/mp4', headers={
            'Transfer-Encoding': 'chunked',
            'Content-Disposition': 'attachment; filename="video.mp4"'
        })

js：
try {
    const response = await fetch("apiurl", {
        method: 'POST',
        headers: {
            'Content-Type': 'application/json',
            'X-Signature': 'xvxvxv332'
        },
        body: JSON.stringify({
            url: "https://youtube.com/shorts/68kf4Xd63rc?si=aRexNBocRnLX6E4A"
        })
    });
    if (!response.ok) {
                    throw new Error('网络请求失败');
                }
                const chunks = [];
                const reader = response.body.getReader();
                let { done, value } = await reader.read();
                while (!done) {
                    chunks.push(value);
                    ({ done, value } = await reader.read());
                }
                const downloadLink = document.createElement('a');
                const blob = new Blob(chunks, { type: 'video/mp4' });
                const url = URL.createObjectURL(blob);
                downloadLink.href = url;
                downloadLink.download = 'video.mp4';
                document.body.appendChild(downloadLink);
                downloadLink.click();
                
            } catch (error) {
                console.error('下载出错:', error);
}
```

**Comment by pukkandan** [comment]
We can't debug your code for you. If you have any issue with the yt-dlp output, provide verbose log

**Comment by fc1104** [comment]
> We can't debug your code for you. If you have any issue with the yt-dlp output, provide verbose log

There is no detailed log. I want to ask if there is any similar scenario problem before. I can only get more than 3000 bytes of data each time through front-end code call.

**Comment by bashonly** [comment]
> There is no detailed log.

Find a way to produce one. Add `'verbose': True` to your `ydl_opts`, etc

This issue will be closed if you can't provide a log
