### ISSUE TITLE
ERROR: [youtube:tab] @wine-lcr: Unable to recognize tab page; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= 

### ISSUE THREAD

**Issue by TKIENJ16** [yt-dlp/yt-dlp#11913]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United States of America Pacific North West

### Provide a description that is worded well enough to be understood

I'm reporting an error as requested. This is my first time doing something like this, but I believe the output should provide enough information for a developer to identify the issue. I'm using an alternative email that doesn't forward messages, so my response time might be about a day.

The video URL is provided below; it leads to a channel's video tab. I used the "Open-With" to launch yt-dlp from Firefox to direct the output to the desired location. openwith is abandonware and not maintained. It is written in Python. The results were the same when I ran it directly in the terminal.

I'm on Windows 11 Pro (version 23H2), installed on January 1, 2023. I haven't tested this on Gentoo, Arch, or Ubuntu, but I believe my Gentoo installation, along with all the other distributions, is multi-lib. I suspect the issue is specific to Windows, while it might work correctly on Linux. I apologize if my explanation is unclear; I have a spinal injury, which limits my computing time. I must go. It is the end of getting the video off YouTube. It is coming.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
C:\Users\Eunha\bin>yt-dlp -vU  "https://www.youtube.com/@wine-lcr/videos"
[debug] Command-line config: ['-vU', 'https://www.youtube.com/@wine-lcr/videos']
[debug] User config "C:\Users\Eunha\AppData\Roaming\yt-dlp\config.txt": ['--extractor-args=youtube:skip=translated_subs', '--external-downloader=aria2c', '--external-downloader-args', 'aria2c:--min-split-size=1M --file-allocation=none --optimize-concurrent-downloads=true --max-connection-per-server=8 --max-concurrent-downloads=2 --split=8', '--throttled-rate=100k', '--compat-options=no-keep-subs', '--compat-options=embed-metadata', '--compat-options=no-clean-infojson', '--http-chunk-size=1M', '--user-agent=Mozilla/5.0 (iPad; CPU OS 16_7_10 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.6 Mobile/15E148 Safari/604.1,gzip(gfe)', '--no-mark-watched', '--geo-bypass', '--continue', '--no-call-home', '--no-mtime', '--progress', '--color', 'always', '--yes-playlist', '--format-sort', 'hdr,res', '--write-sub', '--write-auto-sub', '--sub-format', 'best', '--sub-lang=en.*', '--embed-subs', '--parse-metadata=description:(?s)(?P<meta_comment>.+)', '--embed-metadata', '--embed-chapters', '--embed-thumbnail', '--merge-output-format=mp4', '-o', 'H:\\ITZY\\%(uploader)s.%(upload_date)s.%(title)s-%(id)s.%(format_id)s.%(ext)s']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.12.23.232812 from yt-dlp/yt-dlp-nightly-builds [65cf46cdd] (win_exe)
[debug] Compatibility options: embed-metadata, no-keep-subs, no-clean-infojson
[debug] Python 3.10.11 (CPython AMD64 64bit) - Windows-10-10.0.22631-SP0 (OpenSSL 1.1.1t  7 Feb 2023)
[debug] exe versions: ffmpeg N-117900-gbcbf3a5630-20241125 (setts), ffprobe N-117900-gbcbf3a5630-20241125
[debug] Optional libraries: Cryptodome-3.21.0, brotli-1.1.0, certifi-2024.12.14, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.40.1, urllib3-2.3.0, websockets-14.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1837 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.12.23.232812 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.12.23.232812 from yt-dlp/yt-dlp-nightly-builds)
[youtube:tab] Extracting URL: https://www.youtube.com/@wine-lcr/videos
[youtube:tab] @wine-lcr/videos: Downloading webpage
WARNING: [youtube:tab] unable to extract yt initial data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [youtube:tab] Incomplete yt initial data received. Retrying (1/3)...
[youtube:tab] @wine-lcr/videos: Downloading webpage
WARNING: [youtube:tab] unable to extract yt initial data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [youtube:tab] Incomplete yt initial data received. Retrying (2/3)...
[youtube:tab] @wine-lcr/videos: Downloading webpage
WARNING: [youtube:tab] unable to extract yt initial data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [youtube:tab] Incomplete yt initial data received. Retrying (3/3)...
[youtube:tab] @wine-lcr/videos: Downloading webpage
WARNING: [youtube:tab] unable to extract yt initial data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [youtube:tab] Incomplete yt initial data received; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U. Giving up after 3retries
[youtube:tab] @wine-lcr/videos: Downloading API parameters API JSON
[youtube:tab] @wine-lcr/videos: Downloading API JSON
ERROR: [youtube:tab] @wine-lcr: Unable to recognize tab page; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 742, in extract
  File "yt_dlp\extractor\youtube.py", line 5001, in wrapper
  File "yt_dlp\extractor\youtube.py", line 7082, in _real_extract
```

**Comment by bashonly** [comment]
try removing the `--user-agent` option from your config
