### ISSUE TITLE
Can't Figure Out How to Pass Cookies to Youtube-dl

### ISSUE THREAD

**Issue by bq2enqou23** [yt-dlp/yt-dlp#11914]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I can't figure out how to pass cookies to youtube-dl. The commands I've tried:

yt-dlp --cookies F:\Youtube F\ffmpeg-master-latest-win64-gpl\archive\cookies.txt --audio-quality 0 --no-abort-on-error --download-archive downloaded2.txt -o "%(playlist)s/%(playlist_index)s - %(title)s.%(ext)s - %(channel)s.%(upload_date)s" "https://www.youtube.com/watch?v=8JLc7-DrtBQ"

I get _ERROR: [generic] 'F\\ffmpeg-master-latest-win64-gpl\\archive\\cookies.txt' is not a valid URL._ and _ERROR: 'F:\\Youtube' does not look like a Netscape format cookies file_.

yt-dlp --cookies F:/Youtube F/ffmpeg-master-latest-win64-gpl/archive/cookies.txt --audio-quality 0 --no-abort-on-error --download-archive downloaded2.txt -o "%(playlist)s/%(playlist_index)s - %(title)s.%(ext)s - %(channel)s.%(upload_date)s" "https://www.youtube.com/watch?v=8JLc7-DrtBQ"
 
same errors as previous

yt-dlp --cookies cookies.txt --audio-quality 0 --no-abort-on-error --download-archive downloaded2.txt -o "%(playlist)s/%(playlist_index)s - %(title)s.%(ext)s - %(channel)s.%(upload_date)s" "https://www.youtube.com/watch?v=8JLc7-DrtBQ"

I get _WARNING: [youtube] YouTube said: ERROR - Request contains an invalid argument._ and _ERROR: [youtube] 8JLc7-DrtBQ: Requested format is not available. Use --list-formats for a list of available formats_.

yt-dlp --cookies cookies --audio-quality 0 --no-abort-on-error --download-archive downloaded2.txt -o "%(playlist)s/%(playlist_index)s - %(title)s.%(ext)s - %(channel)s.%(upload_date)s" "https://www.youtube.com/watch?v=8JLc7-DrtBQ"

I get _ERROR: [youtube] 8JLc7-DrtBQ: Sign in to confirm you’re not a bot. This helps protect our community. Learn more_.

My issue is that I am seemingly ip banned as every time I try to use youtube-dl I get the "sign in to confirm you're not a bot error."
I read that passing in cookies is the only way to solve this, but cannot get the command line to work. For extra context, the cookies file is in the folder path F:\Youtube F\ffmpeg-master-latest-win64-gpl\archive and is a text file named "cookies"

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by dirkf** [comment]
If `F:\Youtube F\ffmpeg-master-latest-win64-gpl\archive\cookies.txt` is actually your exported cookie file, you need to "quote it"; otherwise replace that string by the correct pathname, [quoted if it contains spaces](https://ss64.com/nt/syntax-esc.html). Or use the `--cookies-from-browser ...` option instead

**Comment by bq2enqou23** [comment]
> If `F:\Youtube F\ffmpeg-master-latest-win64-gpl\archive\cookies.txt` is actually your exported cookie file, you need to "quote it"; otherwise replace that string by the correct pathname, [quoted if it contains spaces](https://ss64.com/nt/syntax-esc.html). Or use the `--cookies-from-browser ...` option instead

I renamed the file path to remove spaces and then tried the commands

yt-dlp --cookies "F:\Youtube-F\ffmpeg-master-latest-win64-gpl\archive\cookies.txt" "https://www.youtube.com/watch?v=8JLc7-DrtBQ"

and

yt-dlp --cookies-from-browser firefox "https://www.youtube.com/watch?v=8JLc7-DrtBQ"

but both commands give me 

WARNING: [youtube] YouTube said: ERROR - Request contains an invalid argument.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (1/3)...
WARNING: [youtube] Unable to download API page: HTTP Error 400: Bad Request (caused by <HTTPError 400: Bad Request>)
WARNING: [youtube] 8JLc7-DrtBQ: nsig extraction failed: Some formats may be missing
         n = S9JjgMWe3H5drOa98 ; player = https://www.youtube.com/s/player/03dbdfab/player_ias.vflset/en_US/base.js
WARNING: Only images are available for download. use --list-formats to see them
ERROR: [youtube] 8JLc7-DrtBQ: Requested format is not available. Use --list-formats for a list of available formats

**Comment by StefanLobbenmeier** [comment]
I can download that video without cookies: `yt-dlp  "https://www.youtube.com/watch?v=8JLc7-DrtBQ"` - I suspect you are actually running into another issue (possibly the rate limiting one, but that should say http 403 and not http 400) 


But to get support here you need the verbose log as indicated in the issue template, so please try this:

`yt-dlp -vU --cookies-from-browser firefox "https://www.youtube.com/watch?v=8JLc7-DrtBQ"`

**Comment by bashonly** [comment]
> I get WARNING: [youtube] YouTube said: ERROR - Request contains an invalid argument. and ERROR: [youtube] 8JLc7-DrtBQ: Requested format is not available. Use --list-formats for a list of available formats.

The cookies are working in this attempt; but your yt-dlp is out-of-date
