### ISSUE TITLE
User Configuration ${XDG_CONFIG_HOME}/yt-dlp.conf UNSUPPORTED

### ISSUE THREAD

**Issue by SingleRottenChips** [yt-dlp/yt-dlp#11920]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

XDG_CONFIG_HOME has been defined in ~/.bashrc:
```  shell
echo ${XDG_CONFIG_HOME}
/home/lochips/videos/config

ls -l ${XDG_CONFIG_HOME}/yt-dlp.conf
-rw-r----- 1 lochips lochips 2092 Dec 27 17:59 /home/lochips/videos/config/yt-dlp.conf
```
But config file is unrecognized:
```shell
yt-dlp --verbose
[debug] Command-line config: ['--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
...
```
A symbolic link to the "recommend" path solved the problem:
```shell
ln -s /home/lochips/videos/config/yt-dlp.conf ~/.config/yt-dlp/config

yt-dlp --verbose
[debug] Command-line config: ['--verbose']
[debug] User config "/home/lochips/.config/yt-dlp/config": ['-f', 'bv[protocol!*=dash]+ba/b', '-o', '%(upload_date>%Y-%m-%d)s_%(title)s [%(webpage_url_basename)s].%(ext)s', '--hls-prefer-ffmpeg', '-q', '--download-archive', 'config/archive.txt', '--netrc', '--netrc-location', 'config/.netrc', '--print', 'playlist:filename', '--no-simulate']
...
```

Is it a system or disk thing? Or is it time to update the document?

------

Sorry, just found out ~/.config is not the "recommended" path but what ${XDG_CONFIG_HOME} defaults to.

Tried to copy it to the recommended location, but it was still unidentified though:
```shell
cp /home/lochips/videos/config/yt-dlp.conf /home/lochips/videos/config/yt-dlp/config

dl -v
[debug] Command-line config: ['-v']
```

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp -vU
[debug] Command-line config: ['-vU']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version master@2024.12.26.011937 from yt-dlp/yt-dlp-master-builds [0b6b7742c] (zip)
[debug] Python 3.11.11 (CPython x86_64 64bit) - Linux-6.6.62-gentoo-whatbox-x86_64-AMD_EPYC_7702P_64-Core_Processor-with-glibc2.40 (OpenSSL 3.3.2 3 Sep 2024, glibc 2.40)
[debug] exe versions: ffmpeg 6.1.2 (setts), ffprobe 6.1.2
[debug] Optional libraries: certifi-3024.7.22, pycrypto-3.21.0, requests-2.32.3, sqlite3-3.46.1, urllib3-2.2.3
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Loaded 1837 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-master-builds/releases/latest
Latest version: master@2024.12.26.011937 from yt-dlp/yt-dlp-master-builds
yt-dlp is up to date (master@2024.12.26.011937 from yt-dlp/yt-dlp-master-builds)
```

**Comment by bashonly** [comment]
I can't reproduce the issue

```shell
$ printf -- '--verbose\n' > /home/user/Downloads/dlp/yt-dlp.conf
$ XDG_CONFIG_HOME=/home/user/Downloads/dlp yt-dlp
[debug] Command-line config: []
[debug] User config "/home/user/Downloads/dlp/yt-dlp.conf": ['--verbose']
```

**Comment by bashonly** [comment]
Did you figure out what the problem was?

**Comment by SingleRottenChips** [comment]
> Did you figure out what the problem was?

No when I closed the issue. 
But I just realized it was probably because I set XDG_CONFIG_HOME in ~/.bashrc without _exporting_ it.
And it turns out to be the reason lol.
