### ISSUE TITLE
Confusion about the "section" option in Documentation/Readme of yt-dlp. It's not clear if there is or there is no ability to cut/download a specific part of the video

### ISSUE THREAD

**Issue by ByteBolt556** [yt-dlp/yt-dlp#11938]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Hello! 

I've been reading the documentation of yt-dlp for about an hour now, tried many different variations, looked through the Readme, open and closed tickets in this repository, even googled it but I can't seem to find what I'm looking for. Maybe I am terrible with searching for my solution and hopefully I can get some help from the developers and not get scolded by them xD. 

I was wondering if there is an option to cut/download a specific part of the video with yt-dlp. Let's just say for example I want to download a section from 00:00 to 00:08 from this video https://youtu.be/dQw4w9WgXcQ without me needing to download the full video and edit it manually in my program for editing. How would I do that? 

According to this ticket: https://github.com/yt-dlp/yt-dlp/issues/1803 it seems impossible to implement that function or am I getting something wrong? If I am right - can you guys make it clearer (for slow people like me) in the documentation that this option isn't a thing? Thank you and please forgive me for my ignorance!

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.12.23 from yt-dlp/yt-dlp [65cf46cdd] (win_exe)
[debug] Python 3.10.11 (CPython AMD64 64bit) - Windows-10-10.0.26100-SP0 (OpenSSL 1.1.1t  7 Feb 2023)
[debug] exe versions: ffmpeg 7.1-full_build-www.gyan.dev (setts), ffprobe 7.1-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.21.0, brotli-1.1.0, certifi-2024.12.14, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.40.1, urllib3-2.3.0, websockets-14.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1837 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.12.23 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.12.23 from yt-dlp/yt-dlp)
```

**Comment by Grub4K** [comment]
You are probably looking for `--download-sections`. Look up the info on it in the readme.

**Comment by october262** [comment]
try yt-dlp --download-sections *00:00-00:08 --force-keyframes-at-cuts "https://youtu.be/dQw4w9WgXcQ"

**Comment by ByteBolt556** [comment]
> try yt-dlp --download-sections *00:00-00:08 --force-keyframes-at-cuts "https://youtu.be/dQw4w9WgXcQ"

This seems to have worked. Thanks a bunch!
