### ISSUE TITLE
[SOOP] Playback glitch due to mismatched resolutions

### ISSUE THREAD

**Issue by s0ren99** [yt-dlp/yt-dlp#11932]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Singapore

### Provide a description that is worded well enough to be understood

yt-dlp concatenates m3u8 videos for SOOP video URLs, which usually works.

However, I just found that videos of different resolutions are also concatenated; as a result, the output video starts to stutter at the first intersection, progressing frame by frame.

Clicking or seeking forward does make the video play, but the audio is out of sync.

The glitch occurs on mpv, iina, and VLC. I've found two video URLs with this situation.

Could we add another requirement/condition, namely having the same resolution, for video files to be concatenable?

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-F', '--no-download-archive', '--simulate', '--print', 'filename', '-vU', 'https://vod.sooplive.co.kr/player/146436779']
[debug] User config "/home/lochips/.config/yt-dlp/config": ['-f', 'bv[protocol!*=dash]+ba/b', '-o', '千伊珠_천이주_ks940714_%(upload_date>%Y-%m-%d)s_%(title)s [%(webpage_url_basename)s].mp4', '--downloader', 'm3u8:ffmpeg', '--downloader-args', 'ffmpeg:-v error', '--download-archive', 'config/archive.txt', '--progress', '--progress-template', '%(info.id)s-%(progress.eta)s', '--netrc', '--netrc-location', 'config/.netrc', '--print', 'after_move:filename', '--print', 'playlist:filename', '--no-simulate']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version master@2024.12.26.011937 from yt-dlp/yt-dlp-master-builds [0b6b7742c] (zip)
[debug] Python 3.11.11 (CPython x86_64 64bit) - Linux-6.6.62-gentoo-whatbox-x86_64-AMD_EPYC_7702P_64-Core_Processor-with-glibc2.40 (OpenSSL 3.3.2 3 Sep 2024, glibc 2.40)
[debug] exe versions: ffmpeg 6.1.2 (setts), ffprobe 6.1.2
[debug] Optional libraries: certifi-3024.7.22, pycrypto-3.21.0, requests-2.32.3, sqlite3-3.46.1, urllib3-2.2.3
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Loaded 1837 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-master-builds/releases/latest
Latest version: master@2024.12.26.011937 from yt-dlp/yt-dlp-master-builds
yt-dlp is up to date (master@2024.12.26.011937 from yt-dlp/yt-dlp-master-builds)
[debug] [soop] Using netrc for afreecatv authentication
[soop] Logging in
[soop] Extracting URL: https://vod.sooplive.co.kr/player/146436779
[soop] 146436779: Downloading API JSON
[soop] 146436779: Downloading part 1 m3u8 information
[soop] 146436779: Downloading part 2 m3u8 information
[soop] 146436779: Downloading part 3 m3u8 information
[soop] 146436779: Downloading part 4 m3u8 information
[soop] 146436779: Downloading part 5 m3u8 information
[download] Downloading multi_video: [이노레이블] 별수호 주옥ㄴㅏ개쩐ㄷㅏ
[soop] Playlist [이노레이블] 별수호 주옥ㄴㅏ개쩐ㄷㅏ: Downloading 5 items of 5
[debug] The information of all playlist entries will be held in memory
[download] Downloading item 1 of 5
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec, channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[info] Available formats for 20241228_4C57269A_279936926_1:
ID           EXT RESOLUTION │   FILESIZE   TBR PROTO │ VCODEC      ACODEC
────────────────────────────────────────────────────────────────────────────
hls-hd       mp4 960x540    │ ~ 28.61MiB 1000k m3u8  │ avc1.640020 mp4a.40.2
hls-hd4k     mp4 1280x720   │ ~114.44MiB 4000k m3u8  │ avc1.640020 mp4a.40.2
hls-original mp4 1920x1080  │ ~228.88MiB 8000k m3u8  │ avc1.64002A mp4a.40.2
[info] 20241228_4C57269A_279936926_1: Downloading 1 format(s): hls-original
千伊珠_천이주_ks940714_2024-12-28_[이노레이블] 별수호 주옥ㄴㅏ개쩐ㄷㅏ (part 1) [146436779].mp4
[download] Downloading item 2 of 5
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec, channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[info] Available formats for 20241228_2AA5D83E_279936926_2:
ID           EXT RESOLUTION │  FILESIZE   TBR PROTO │ VCODEC      ACODEC
───────────────────────────────────────────────────────────────────────────
hls-hd       mp4 960x540    │ ~11.09MiB 1000k m3u8  │ avc1.64001F mp4a.40.2
hls-original mp4 1280x720   │ ~44.35MiB 4000k m3u8  │ avc1.64001F mp4a.40.2
[info] 20241228_2AA5D83E_279936926_2: Downloading 1 format(s): hls-original
千伊珠_천이주_ks940714_2024-12-28_[이노레이블] 별수호 주옥ㄴㅏ개쩐ㄷㅏ (part 2) [146436779].mp4
[download] Downloading item 3 of 5
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec, channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[info] Available formats for 146436779_1735325282_3:
ID           EXT RESOLUTION │  FILESIZE   TBR PROTO │ VCODEC      ACODEC
───────────────────────────────────────────────────────────────────────────
hls-hd       mp4 960x540    │ ~22.17MiB 1000k m3u8  │ avc1.64001F mp4a.40.2
hls-original mp4 1280x720   │ ~88.69MiB 4000k m3u8  │ avc1.64001F mp4a.40.2
[info] 146436779_1735325282_3: Downloading 1 format(s): hls-original
千伊珠_천이주_ks940714_2024-12-28_[이노레이블] 별수호 주옥ㄴㅏ개쩐ㄷㅏ (part 3) [146436779].mp4
[download] Downloading item 4 of 5
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec, channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[info] Available formats for 146436779_1735325282_4:
ID           EXT RESOLUTION │   FILESIZE   TBR PROTO │ VCODEC      ACODEC
────────────────────────────────────────────────────────────────────────────
hls-hd       mp4 960x540    │ ~ 72.96MiB 1000k m3u8  │ avc1.64001F mp4a.40.2
hls-original mp4 1280x720   │ ~291.82MiB 4000k m3u8  │ avc1.64001F mp4a.40.2
[info] 146436779_1735325282_4: Downloading 1 format(s): hls-original
千伊珠_천이주_ks940714_2024-12-28_[이노레이블] 별수호 주옥ㄴㅏ개쩐ㄷㅏ (part 4) [146436779].mp4
[download] Downloading item 5 of 5
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec, channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[info] Available formats for 146436779_1735323854_5:
ID           EXT RESOLUTION │   FILESIZE   TBR PROTO │ VCODEC      ACODEC
────────────────────────────────────────────────────────────────────────────
hls-hd       mp4 960x540    │ ~149.61MiB 1000k m3u8  │ avc1.64001F mp4a.40.2
hls-original mp4 1280x720   │ ~598.43MiB 4000k m3u8  │ avc1.64001F mp4a.40.2
[info] 146436779_1735323854_5: Downloading 1 format(s): hls-original
千伊珠_천이주_ks940714_2024-12-28_[이노레이블] 별수호 주옥ㄴㅏ개쩐ㄷㅏ (part 5) [146436779].mp4
千伊珠_천이주_ks940714_2024-12-28_[이노레이블] 별수호 주옥ㄴㅏ개쩐ㄷㅏ [146436779].mp4
[download] Finished downloading playlist: [이노레이블] 별수호 주옥ㄴㅏ개쩐ㄷㅏ
```

**Comment by bashonly** [comment]
This is a general problem with `multi_video` playlists. I don't think there is a real solution aside from not using `multi_video` playlists for this site (and all sites?)

As a workaround you can pass `--concat never`

**Comment by SingleRottenChips** [comment]
> This is a general problem with `multi_video` playlists. I don't think there is a real solution aside from not using `multi_video` playlists for this site (and all sites?)
> 
> As a workaround you can pass `--concat never`

I fully understand they are `multi_video` playlists in effect; but I still think these m3u8 videos together represent one video, ideally and practically, as they are in one VOD URL (https://vod.sooplive.co.kr/player/), and presented as _chapters_ of one video in the web player.

I know I can choose not to concatenate the video parts, which is how I've fixed it; but that's _only if_ I find they have different resolutions while they mostly don't.  ~~This means I need to check the video or list formats every time before downloading and make adjustments accordingly, which is time-consuming.~~

Maybe I'll add [height=1080] in -f, see if there is any error in the output, and make adjustments with a script.
