### ISSUE TITLE
ERROR: unable to download video data: HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by Persona78** [yt-dlp/yt-dlp#11936]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

pORTUGAL

### Provide a description that is worded well enough to be understood

[youtube:tab] Extracting URL: https://www.youtube.com/watch?v=1k8craCGpgs&list=PLUueilRKpIbIrG1_epVxnVBsL4lkmlBWL
[youtube:tab] Downloading playlist PLUueilRKpIbIrG1_epVxnVBsL4lkmlBWL - add --no-playlist to download just the video 1k8craCGpgs
[youtube:tab] PLUueilRKpIbIrG1_epVxnVBsL4lkmlBWL: Downloading webpage
[youtube:tab] Extracting URL: https://www.youtube.com/playlist?list=PLUueilRKpIbIrG1_epVxnVBsL4lkmlBWL
[youtube:tab] PLUueilRKpIbIrG1_epVxnVBsL4lkmlBWL: Downloading webpage
[youtube:tab] PLUueilRKpIbIrG1_epVxnVBsL4lkmlBWL: Redownloading playlist API JSON with unavailable videos
[download] Downloading playlist: Greatest Hits
[youtube:tab] PLUueilRKpIbIrG1_epVxnVBsL4lkmlBWL page 1: Downloading API JSON
[youtube:tab] Playlist Greatest Hits: Downloading 21 items of 21
[download] Downloading item 1 of 21
[youtube] Extracting URL: https://www.youtube.com/watch?v=1k8craCGpgs
[youtube] 1k8craCGpgs: Downloading webpage
[youtube] 1k8craCGpgs: Downloading ios player API JSON
[youtube] 1k8craCGpgs: Downloading mweb player API JSON
[youtube] 1k8craCGpgs: Downloading m3u8 information
[info] 1k8craCGpgs: Downloading 1 format(s): 251
ERROR: unable to download video data: HTTP Error 403: Forbidden

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['--no-flat-playlist', '--recode-video', 'mp3', '--extract-audio', '--audio-quality', '0', '--progress', '-P', 'Greatests', '--no-keep-video', '--ffmpeg-location', 'bin\\ffmpeg.exe', 'https://www.youtube.com/watch?v=1k8craCGpgs&list=PLUueilRKpIbIrG1_epVxnVBsL4lkmlBWL', '-vU']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.12.23 from yt-dlp/yt-dlp [65cf46cdd] (win_exe)
[debug] Python 3.10.11 (CPython AMD64 64bit) - Windows-10-10.0.26100-SP0 (OpenSSL 1.1.1t  7 Feb 2023)
[debug] exe versions: ffmpeg 7.1-full_build-www.gyan.dev (setts)
[debug] Optional libraries: Cryptodome-3.21.0, brotli-1.1.0, certifi-2024.12.14, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.40.1, urllib3-2.3.0, websockets-14.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1837 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.12.23 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.12.23 from yt-dlp/yt-dlp)
[youtube:tab] Extracting URL: https://www.youtube.com/watch?v=1k8craCGpgs&list=PLUueilRKpIbIrG1_epVxnVBsL4lkmlBWL
[youtube:tab] Downloading playlist PLUueilRKpIbIrG1_epVxnVBsL4lkmlBWL - add --no-playlist to download just the video 1k8craCGpgs
[youtube:tab] PLUueilRKpIbIrG1_epVxnVBsL4lkmlBWL: Downloading webpage
[youtube:tab] Extracting URL: https://www.youtube.com/playlist?list=PLUueilRKpIbIrG1_epVxnVBsL4lkmlBWL
[youtube:tab] PLUueilRKpIbIrG1_epVxnVBsL4lkmlBWL: Downloading webpage
[youtube:tab] PLUueilRKpIbIrG1_epVxnVBsL4lkmlBWL: Redownloading playlist API JSON with unavailable videos
[download] Downloading playlist: Greatest Hits
[youtube:tab] PLUueilRKpIbIrG1_epVxnVBsL4lkmlBWL page 1: Downloading API JSON
[youtube:tab] Playlist Greatest Hits: Downloading 21 items of 21
[download] Downloading item 1 of 21
[youtube] Extracting URL: https://www.youtube.com/watch?v=1k8craCGpgs
[youtube] 1k8craCGpgs: Downloading webpage
[youtube] 1k8craCGpgs: Downloading ios player API JSON
[youtube] 1k8craCGpgs: Downloading mweb player API JSON
[debug] [youtube] 1k8craCGpgs: ios client https formats require a PO Token which was not provided. They will be skipped as they may yield HTTP Error 403. You can manually pass a PO Token for this client with --extractor-args "youtube:po_token=ios+XXX. For more information, refer to  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#po-token-guide . To enable these broken formats anyway, pass --extractor-args "youtube:formats=missing_pot"
[debug] [youtube] Extracting signature function js_03dbdfab_103
[debug] Loading youtube-sigfuncs.js_03dbdfab_103 from cache
[debug] Loading youtube-nsig.03dbdfab from cache
[debug] [youtube] Decrypted nsig xcFjgtQEcUThDeOAu => aD1dpXj_KhAXXQ
[debug] Loading youtube-nsig.03dbdfab from cache
[debug] [youtube] Decrypted nsig 1BNE-vzslYXwWEdm8 => Af5aeNh4_DWmsQ
[debug] [youtube] Extracting signature function js_03dbdfab_107
[debug] Loading youtube-sigfuncs.js_03dbdfab_107 from cache
[youtube] 1k8craCGpgs: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec, channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[info] 1k8craCGpgs: Downloading 1 format(s): 251
[debug] Invoking http downloader on "https://rr2---sn-apn7en7s.googlevideo.com/videoplayback?expire=1735422821&ei=BR9wZ8uUJtL_xN8PrYDooQc&ip=2001%3A818%3Ae348%3A5700%3Aedb1%3A824c%3Aea5%3A4766&id=o-ACT93_x6_h-kCq94ZSp-cGP69qflHD4EhVTvbIXc8GWW&itag=251&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&met=1735401221%2C&mh=Hb&mm=31%2C29&mn=sn-apn7en7s%2Csn-apn7en7e&ms=au%2Crdu&mv=m&mvi=2&pl=42&rms=au%2Cau&gcr=pt&initcwndbps=3205000&bui=AfMhrI9nMXPjWRFcRuJVhIXPnQ0nSkpTR0q5HP3BiCju2z5zFSuJ8HnAJqCo3hrnYwDPElJekx_djQ2o&vprv=1&svpuc=1&mime=audio%2Fwebm&ns=DGLDagkRqm4fZ2U_LBNQpbwQ&rqh=1&gir=yes&clen=4080051&dur=250.241&lmt=1715026746312448&mt=1735400726&fvip=1&keepalive=yes&fexp=51326932%2C51331020%2C51335594%2C51371294&c=MWEB&sefc=1&txp=4502434&n=Af5aeNh4_DWmsQ&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cgcr%2Cbui%2Cvprv%2Csvpuc%2Cmime%2Cns%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=met%2Cmh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Crms%2Cinitcwndbps&lsig=AGluJ3MwRQIgIwTLxhXn3cBWkMlKNtfMvbGZDpFOw6FOPxoKU5fuF9oCIQCtQ85AYg-RCwU6m4Zh88cLaPrqyPi6W6v-WnLIlIlxNQ%3D%3D&sig=AJfQdSswRgIhAOV02As8oxH56O10UMeUwUg8WWWBGh2pfI3ZiwKgutMoAiEA62HB06Y07TslVdnItLVjyyYxgECyEN5BhaDwZA2O4Dg%3D"
ERROR: unable to download video data: HTTP Error 403: Forbidden
```

**Comment by anurag12-webster** [comment]
does anyone have come to solution for this??

**Comment by coletdjnz** [comment]
https://github.com/yt-dlp/yt-dlp/issues/11868
