### ISSUE TITLE
Suddenly video error when video is downloaded and imported in Reaper

### ISSUE THREAD

**Issue by tormyvancool** [yt-dlp/yt-dlp#11942]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I launch yt-dlp

`yt-dlp.exe  --update-to master --merge-output-format mp4 https://www.youtube.com/watch?v=OmwC8ZSjS3I -P "k:\My Valentine" --force-overwrite`

The video is downloaded. 

But when I import it in Reaper, I get  a green screen instead of the video. This error means that the file is corrupted. On VLC iit works.

Never happened before. It started form the day before yesterday so far.
Reaper version 7.28 (I never had this issue before with the same Reaper's version)

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--update-to', 'master', '--merge-output-format', 'mp4', 'https://www.youtube.com/watch?v=OmwC8ZSjS3I', '-P', 'k:\\My Valentine', '--force-overwrite']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out cp1252 (No VT), error utf-8, screen cp1252 (No VT)
[debug] yt-dlp version master@2024.12.26.011937 from yt-dlp/yt-dlp-master-builds [0b6b7742c] (win_exe)
[debug] Python 3.10.11 (CPython AMD64 64bit) - Windows-10-10.0.26100-SP0 (OpenSSL 1.1.1t  7 Feb 2023)
[debug] exe versions: ffmpeg 6.1.1-essentials_build-www.gyan.dev (setts), ffprobe 6.1.1-essentials_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.21.0, brotli-1.1.0, certifi-2024.12.14, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.40.1, urllib3-2.3.0, websockets-14.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1837 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-master-builds/releases/latest
[debug] [youtube] OmwC8ZSjS3I: ios client https formats require a PO Token which was not provided. They will be skipped as they may yield HTTP Error 403. You can manually pass a PO Token for this client with --extractor-args "youtube:po_token=ios+XXX". For more information, refer to  https://github.com/yt-dlp/yt-dlp/wiki/Extractors#po-token-guide . To enable these broken formats anyway, pass --extractor-args "youtube:formats=missing_pot"
[debug] [youtube] Extracting signature function js_03dbdfab_107
[debug] Loading youtube-sigfuncs.js_03dbdfab_107 from cache
[debug] Loading youtube-nsig.03dbdfab from cache
[debug] [youtube] Decrypted nsig WfX56B9ha05TlGxC2 => CAOiDVyMt1O5rw
[debug] [youtube] Extracting signature function js_03dbdfab_103
[debug] Loading youtube-sigfuncs.js_03dbdfab_103 from cache
[debug] Loading youtube-nsig.03dbdfab from cache
[debug] [youtube] Decrypted nsig tcokZHMJRvuMtxbTO => w_ZP33ksDU4ldg
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec, channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[debug] Invoking http downloader on "https://rr5---sn-uxaxoxu-cg0r.googlevideo.com/videoplayback?expire=1735493373&ei=nTJxZ7rLC9OahcIPi4XakQc&ip=84.197.137.130&id=o-AAk-vLiOhG71-LAaCGJpujZ76bGq1fwgcGEI_8h_URav&itag=399&aitags=134%2C136%2C137%2C160%2C243%2C394%2C395%2C396%2C397%2C398%2C399%2C597%2C598&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&met=1735471773%2C&mh=_p&mm=31%2C29&mn=sn-uxaxoxu-cg0r%2Csn-5hne6nzy&ms=au%2Crdu&mv=m&mvi=5&pl=13&rms=au%2Cau&initcwndbps=3227500&bui=AfMhrI_UPOVjtKV4IFL48-4ArRiZgs0LqCFwEPxffk8IwPcn8VeF-uVdpSq_pFerYzt8sZVjYC8knnJ8&vprv=1&svpuc=1&mime=video%2Fmp4&ns=Fe03izcvvMhSCTekO0wQzmMQ&rqh=1&gir=yes&clen=36376737&dur=211.360&lmt=1584286851618122&mt=1735471514&fvip=1&keepalive=yes&fexp=51326932%2C51331020%2C51335594%2C51371294&c=MWEB&sefc=1&txp=5431432&n=w_ZP33ksDU4ldg&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cxpc%2Cbui%2Cvprv%2Csvpuc%2Cmime%2Cns%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=met%2Cmh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Crms%2Cinitcwndbps&lsig=AGluJ3MwRQIhALsIyaj6LVml3RUMsS-HOnBlMKMNQk4YPM-ZBNVoK9R-AiAb43NTy9sagbqxhYQPeMDgTCv1MovhQL8kFlXL4B2DAA%3D%3D&sig=AJfQdSswRQIgLc-4o3HsfFNQ_3QDeGfYesqMIHlzQ-EWQRUZFvSFg54CIQDVxzJDsIvHy_vLGYA8maai0MRHcPM-HtrLAO25ajbViw%3D%3D"
[debug] File locking is not supported. Proceeding without locking
[debug] Invoking http downloader on "https://rr5---sn-uxaxoxu-cg0r.googlevideo.com/videoplayback?expire=1735493373&ei=nTJxZ7rLC9OahcIPi4XakQc&ip=84.197.137.130&id=o-AAk-vLiOhG71-LAaCGJpujZ76bGq1fwgcGEI_8h_URav&itag=251&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&met=1735471773%2C&mh=_p&mm=31%2C29&mn=sn-uxaxoxu-cg0r%2Csn-5hne6nzy&ms=au%2Crdu&mv=m&mvi=5&pl=13&rms=au%2Cau&initcwndbps=3227500&bui=AfMhrI_UPOVjtKV4IFL48-4ArRiZgs0LqCFwEPxffk8IwPcn8VeF-uVdpSq_pFerYzt8sZVjYC8knnJ8&vprv=1&svpuc=1&mime=audio%2Fwebm&ns=Fe03izcvvMhSCTekO0wQzmMQ&rqh=1&gir=yes&clen=4058723&dur=211.381&lmt=1583940968957300&mt=1735471514&fvip=1&keepalive=yes&fexp=51326932%2C51331020%2C51335594%2C51371294&c=MWEB&sefc=1&txp=5431432&n=w_ZP33ksDU4ldg&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cbui%2Cvprv%2Csvpuc%2Cmime%2Cns%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=met%2Cmh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Crms%2Cinitcwndbps&lsig=AGluJ3MwRQIhALsIyaj6LVml3RUMsS-HOnBlMKMNQk4YPM-ZBNVoK9R-AiAb43NTy9sagbqxhYQPeMDgTCv1MovhQL8kFlXL4B2DAA%3D%3D&sig=AJfQdSswRgIhAMpcfPynE_-gU7_d7kUL95eqEi5DYig4sBXxqkXoF8LqAiEAzEMY0ypB--ijGoUq9iRMEUVx1dTZb4m6D3VPZJ3rCFk%3D"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i "file:k:\My Valentine\Mic Check #1 - Superlux WH5. Посвящается всем влюблённым [OmwC8ZSjS3I].f399.mp4" -i "file:k:\My Valentine\Mic Check #1 - Superlux WH5. Посвящается всем влюблённым [OmwC8ZSjS3I].f251.webm" -c copy -map 0:v:0 -map 1:a:0 -movflags +faststart "file:k:\My Valentine\Mic Check #1 - Superlux WH5. Посвящается всем влюблённым [OmwC8ZSjS3I].temp.mp4"
```

**Comment by bashonly** [comment]
that is only stderr, please share a log with both stdout and stderr

**Comment by tormyvancool** [comment]
> that is only stderr, please share a log with both stdout and stderr

I have used this command line following the instructions 

`yt-dlp.exe -vU --update-to master --merge-output-format mp4 https://www.youtube.com/watch?v=OmwC8ZSjS3I -P "k:\My Valentine" --force-overwrite >> k:\verbose.txt`

**Comment by bashonly** [comment]
reaper most likely doesn't support the av01 codec of the video format that is downloaded by default

for max compatibility with editing software, try adding this to your command: `-S vcodec:h264,res,acodec:aac`

**Comment by tormyvancool** [comment]
> reaper most likely doesn't support the av01 codec of the video format that is downloaded by default
> 
> for max compatibility with editing software, try adding this to your command: `-S vcodec:h264,res,acodec:aac`

Very wrong because it has worked till a week ago. I even made a tutorial with it and I will never implement again that " `-S vcodec:h264,res,acodec:aac`" because it doesn't download original resolution.

**Comment by bashonly** [comment]
>  I will never implement again that " -S vcodec:h264,res,acodec:aac" because it doesn't download original resolution.

Then try downloading vp9 instead?

> Very wrong because it has worked till a week ago. 

Prioritizing av01 by default was a fairly [recent change](https://github.com/yt-dlp/yt-dlp/commit/3945677a75e94a1fecc085432d791e1c21220cd3), and also note that YT occasionally changes what encodings are available

If you find what I'm saying to be dubious, please provide more information or more of an explanation than just saying I'm "very wrong"

**Comment by tormyvancool** [comment]
> > I will never implement again that " -S vcodec:h264,res,acodec:aac" because it doesn't download original resolution.
> 
> Then try downloading vp9 instead?
> 

how? I need full resolution each time and HQ audio of course.

**Comment by bashonly** [comment]
`--compat-opt prefer-vp9-sort`

**Comment by tormyvancool** [comment]
> `--compat-opt prefer-vp9-sort`

in the place of? Because I tried in place of `--merge-output-format mp4` but returns error without the "mp4"
then `--compat-opt prefer-vp9-sort mp4` something wrong with the syntaxis I think

**Comment by tormyvancool** [comment]
Found the way: 
` --update-to master --merge-output-format mp4 --compat-opt prefer-vp9-sort https://www.youtube.com/watch?v=OmwC8ZSjS3I -P "k:\My Valentine" --force-overwrite`

So it works!
