### ISSUE TITLE
Add support for cookie extraction from other versions of browsers (e.g. Firefox ESR, Edge Extended Stable, Chrome Canary, etc)

### ISSUE THREAD

**Issue by azzydoesgit** [yt-dlp/yt-dlp#11948]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Currently, yt-dlp only supports cookie extraction from the stable releases of Firefox, Opera, Safari, Chrome, etc etc.
I use firefox-esr on Pop!_OS 22.04, so [cookies.py](https://github.com/yt-dlp/yt-dlp/blob/master/yt_dlp/cookies.py#L207) looks for those cookies in the following directories:
```
'~/.mozilla/firefox',
'~/snap/firefox/common/.mozilla/firefox',
'~/.var/app/org.mozilla.firefox/.mozilla/firefox',
```
And in my case, since my firefox path is `~/.mozilla/firefox-esr/[profiles]`, it doesn't find any cookies. Copy-pasting my profile to `~/.mozilla/firefox/` fixes this issue, but it'd be nice if yt-dlp supported this without the workaround.

I'm unsure how other OS's and browsers handle their different versions, but if, say, Chrome Canary's AppData is found in `%LOCALAPPDATA%\Google\Chrome Canary\User Data`, then this path should be added to the list of directories to search for cookies in.

Just about every major browser has multiple versions (even Brave has a [beta](https://brave.com/download-beta/) and [nightly](https://brave.com/download-nightly/) version), so there's a bit of work involved here.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp --ignore-config -vU --cookies-from-browser firefox https://www.youtube.com/watch?v=69Ukg2BqIk0
[debug] Command-line config: ['--ignore-config', '-vU', '--cookies-from-browser', 'firefox', 'https://www.youtube.com/watch?v=69Ukg2BqIk0']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.12.23 from yt-dlp/yt-dlp [65cf46cdd] (pip)
[debug] Python 3.10.12 (CPython x86_64 64bit) - Linux-6.9.3-76060903-generic-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2
[debug] Optional libraries: Cryptodome-3.17, brotli-1.1.0, certifi-2023.11.17, mutagen-1.47.0, requests-2.32.3, secretstorage-3.3.1, sqlite3-3.37.2, urllib3-2.1.0, websockets-13.1
[debug] Proxy map: {}
Extracting cookies from firefox
ERROR: could not find firefox cookies database in '/home/azzy/.mozilla/firefox', '/home/azzy/snap/firefox/common/.mozilla/firefox', '/home/azzy/.var/app/org.mozilla.firefox/.mozilla/firefox'
Traceback (most recent call last):
  File "/home/azzy/.local/lib/python3.10/site-packages/yt_dlp/cookies.py", line 99, in load_cookies
    extract_cookies_from_browser(browser_name, profile, YDLLogger(ydl), keyring=keyring, container=container))
  File "/home/azzy/.local/lib/python3.10/site-packages/yt_dlp/cookies.py", line 118, in extract_cookies_from_browser
    return _extract_firefox_cookies(profile, container, logger)
  File "/home/azzy/.local/lib/python3.10/site-packages/yt_dlp/cookies.py", line 144, in _extract_firefox_cookies
    raise FileNotFoundError(f'could not find firefox cookies database in {search_root}')
FileNotFoundError: could not find firefox cookies database in '/home/azzy/.mozilla/firefox', '/home/azzy/snap/firefox/common/.mozilla/firefox', '/home/azzy/.var/app/org.mozilla.firefox/.mozilla/firefox'
```
```

**Comment by azzydoesgit** [comment]
I was going to make a pull request myself to add Firefox ESR, Dev, Beta, and Nightly support, but then I realized I'd have to also add those paths for Windows and MacOS, and that I should also probably do the same for Chrome, Edge, Brave, and all the other browsers cookies.py supports... which hey I might still do but perhaps somebody already has these paths somewhere.

**Comment by rdamas** [comment]
#2903 doesn't help?
