### ISSUE TITLE
manifest_url no longer found in JSON output from YT

### ISSUE THREAD

**Issue by fe80Grau** [yt-dlp/yt-dlp#11952]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I have **updated yt-dlp to nightly or master** ([update instructions](https://github.com/yt-dlp/yt-dlp#update-channels))
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I have a script that previously used the -j parameter to get the complete JSON. It then searched for the manifest_url within the formats list. My Python script would then redirect to this manifest_url, and up until a few months ago, it worked well, allowing me to play YouTube videos in high quality on Emby using .strm files. However, this is no longer working. It doesn't find manifest_url within the formats list, and I also can't see it when manually inspecting the JSON.

I apologize for not being precise about the time and exact version when this stopped working; I haven't had time until now to notice this issue.

Here is the snippet of code where I use yt-dlp to get the JSON, and where I used to be able to obtain the manifest_url:
``` 
command = [
    'yt-dlp', 
    '-j',
    '--no-warnings',
    f'https://www.youtube.com/watch?v={youtube_id}'
]
Youtube().set_cookies(command)
Youtube().set_proxy(command)
full_info_json_str = w.worker(command).output()
m3u8_url = None
try:
    full_info_json = json.loads(full_info_json_str)
    
    for fmt in full_info_json["formats"]:
        if "manifest_url" in fmt.keys():
            m3u8_url = fmt["manifest_url"]
            break
```

The test command to obtain the JSON and manually check it would be:

```
yt-dlp -vU -j --no-warnings --cookies-from-browser firefox -f best https://www.youtube.com/watch?v=nVD7M---Jhw > test.json
```

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '-j', '--no-warnings', '--cookies-from-browser', 'firefox', '-f', 'best', 'https://www.youtube.com/watch?v=nVD7M---Jhw']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out cp1252 (No VT), error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.12.23 from yt-dlp/yt-dlp [65cf46cdd] (pip)
[debug] Python 3.12.3 (CPython AMD64 64bit) - Windows-11-10.0.22631-SP0 (OpenSSL 3.0.13 30 Jan 2024)
[debug] exe versions: ffmpeg N-116875-g3d0d0f68d5-20240905 (setts), ffprobe N-116875-g3d0d0f68d5-20240905
[debug] Optional libraries: Cryptodome-3.12.0, brotli-1.1.0, certifi-2023.11.17, curl_cffi-0.7.1, mutagen-1.47.0, requests-2.32.3, sqlite3-3.45.1, urllib3-2.1.0, websockets-13.1
[debug] Proxy map: {}
Extracting cookies from firefox
[debug] Extracting cookies from: "xxxxxx\cookies.sqlite"
Extracted 73 cookies from firefox
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1837 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.12.23 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.12.23 from yt-dlp/yt-dlp)
[youtube] Extracting URL: https://www.youtube.com/watch?v=nVD7M---Jhw
[youtube] nVD7M---Jhw: Downloading webpage
[debug] [youtube] Extracted SAPISID cookie
[youtube] nVD7M---Jhw: Downloading web creator player API JSON
[youtube] nVD7M---Jhw: Downloading mweb player API JSON
[debug] Loading youtube-nsig.03dbdfab from cache
[debug] [youtube] Decrypted nsig t8dSh99qCbEPxu6ET => 9bZLLELdEjs-tw
[debug] Loading youtube-nsig.03dbdfab from cache
[debug] [youtube] Decrypted nsig W2Snl_5g6JabYFYCY => WgOWOD_4QFiDHw
[debug] Loading youtube-nsig.03dbdfab from cache
[debug] [youtube] Decrypted nsig QCJRAKbcs0V8nbDeE => FhIVj0OYnVN9qw
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec, channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[info] nVD7M---Jhw: Downloading 1 format(s): 18
```

**Comment by fe80Grau** [comment]
The issue has been fixed in the Discord discussion. The solution is to add `--extractor-args "youtube:player-client=default,web_safari"` to the command

**Comment by bashonly** [comment]
To further explain: the `ios` client is no longer usable with cookies, and it is the client that gets all of the m3u8 formats for non-live videos by default. So the workaround is to use the `web_safari` client when passing cookies
