### ISSUE TITLE
Youtube - title includes datetime

### ISSUE THREAD

**Issue by lekoOwO** [yt-dlp/yt-dlp#120]
## Checklist

- [v] I'm reporting a broken site support issue
- [v] I've verified that I'm running yt-dlp version **2021.02.24**
- [v] I've checked that all provided URLs are alive and playable in a browser
- [v] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [v] I've searched the bugtracker for similar bug reports including closed ones
- [v] I've read bugs section in FAQ

## Description

Run the following command
```
 yt-dlp --print-json --skip-download "ANY_YOUTUBE_URL"
```
gets a `YYYY-MM-DD HH:mm` datetime in the title field (result in `"${TITLE} ${DATETIME}"`)

for example:

```
yt-dlp --print-json --referer "https://www.youtube.com/feed/subscriptions" "https://www.youtube.com/watch?v=w8sedls02ks" -v
[debug] Command-line config: ['--print-json', '--referer', 'https://www.youtube.com/feed/subscriptions', 'https://www.youtube.com/watch?v=w8sedls02ks', '-v']
[debug] Loading archive file None
[debug] Encodings: locale cp950, fs utf-8, out utf-8, pref cp950
[debug] yt-dlp version 2021.02.24
[debug] Python version 3.8.2 (CPython 64bit) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg 4.3.1-2020-11-19-essentials_build-www.gyan.dev, ffprobe 4.3.1-2020-11-19-essentials_build-www.gyan.dev
[debug] Proxy map: {}
{"id": "w8sedls02ks", "title": "\u3010 90\u4e07\u4eba\u6b4c\u67a0 \u3011\uff19\uff10\u4e07\u4eba\u898b\u5c4a\u3051\u305f\u3044\u306b\u3047\uff5e\uff5e\uff5e\uff5e\uff01\uff01\uff01\u3010\u30db\u30ed\u30e9\u30a4\u30d6/\u3055\u304f\u3089\u307f\u3053\u3011 2021-02-28 18:36", ...
```
You see a `2021-02-28 18:36` after the original title

**Comment by pukkandan** [comment]
This is how live video titles are in `youtube-dl` as well.
I am not sure what is the reason for this, and I can't change it until I know what the original intention was, so as not to break anything

**Comment by lekoOwO** [comment]
> This is how live video titles are in `youtube-dl` as well.
> I am not sure what is the reason for this, and I can't change it until I know what the original intention was, so as not to break anything

Oh I see... I have 2020-11 ver. `youtube-dl` (Which has no datetime in the title)
after upgraded, the datetime showed up :(
