### ISSUE TITLE
[ytsearch] Not detecting playlists

### ISSUE THREAD

**Issue by pukkandan** [yt-dlp/yt-dlp#1213]
An other question:
- has yt-dlp a feature to use ytsearch: to search for youtube playlists only?
- is it possible to list the content (video list) of a given youtube playlist id?

I always did patch the currently outdated youtube-dl myself and now Im looking if yt-dlp maybe already supports this.

_Originally posted by @Crypto90 in https://github.com/yt-dlp/yt-dlp/issues/1211#issuecomment-939356201_

**Comment by pukkandan** [comment]
@Crypto90 Please keep #1211 on topic


> has yt-dlp a feature to use ytsearch: to search for youtube playlists only?

Not with ytsearch. But you can go to youtube, search, apply filters and pass the whole URL to yt-dlp. The filters that were applied in website will carry over. Make sure to use `--playlist-end` so that the search doesn't go on indefenitely

> is it possible to list the content (video list) of a given youtube playlist id?

`yt-dlp --flat-playlist --get-url "PLAYLIST URL"`

**Comment by Crypto90** [comment]
yea I know this but it would be great to get it fully functional with console only handling, which is possible with a few lines of code changes.

**Comment by pukkandan** [comment]
You want just playlists, someone else will want some other filter. It is impractical to make a new extractor for each and every use case where there is already a general way to accomplish it. 

You only need to manually apply the filter once. You can later use the same URL with just the search term changed. Eg: `https://www.youtube.com/results?sp=EgIQAw%253D%253D&search_query=python`. The `sp=EgIQAw%253D%253D` is the filter. You can just change the search query `python` for future searches with the same filter

**Comment by pukkandan** [comment]
I initially though this broke because of some youtube change. But now that I had a look, it seems playlists inside search results never used to work. A proper solution to this would need us to merge the `YoutubeSearchIE` code with `YoutubeTabIE` and so will take time to implement. In the meantime, if you can make a PR with your "hacky" solution, we can merge it

cc @coletdjnz

**Comment by Crypto90** [comment]
I have created a pull request:

https://github.com/yt-dlp/yt-dlp/pull/1214

**Comment by Crypto90** [comment]
@coletdjnz passing the url with those "sp=EgIQAw%253D%253D" filters do already work.
So searching is not an issue.

The only issue I run into were the missing search results of type playlist. It only results "videos" but no playlists with a longer playlist_id.

My pull request adds this check, to differ between a video result and a playlist result and changes the result response in the playlist case to get the correct resulting playlist_id instead of a wrong "video_id".
