### ISSUE TITLE
[Question] Segments downloading slowly with --allow-unplayable-formats

### ISSUE THREAD

**Issue by ischmidt20** [yt-dlp/yt-dlp#1218]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README
- [x] I've read the opening an issue section in CONTRIBUTING.md
- [x] I've searched the bugtracker for similar questions including closed ones
- [x] I have given an appropriate title to the issue

## Question

Hi,

I am using yt-dlp to download encrypted video files from [beIN Connect](https://connect.beinsports.com/us) (tv login required), by setting `--allow-unplayable-formats`. I've noticed that when setting this option, the segments download really slowly, especially compared to other platforms, and also compared with just writing a basic Python script to download these segments manually. By the latter I mean just building a list of the segments and manually looping over them and downloading with `requests.get`.

Unfortunately, I cannot directly compare the behavior on this specific platform by toggling the `--allow-unplayable-formats` option, because if I don't set it, there is nothing to download.

I know any odd behavior here should not be filed as a bug, which is why I'm just asking a question. So my question is: **Is there anything intrinsic to the `--allow-unplayable-formats` option that would lead to slower segment downloads?** If so, how to fix?

Thanks!

**Comment by pukkandan** [comment]
> Is there anything intrinsic to the --allow-unplayable-formats option that would lead to slower segment downloads? 

No

But, when using that option, you must have recied a warning
```
WARNING: You have asked for unplayable formats to be listed/downloaded. This is a developer option intended for debugging.
         If you experience any issues while using this option, DO NOT open a bug report
```
