### ISSUE TITLE
"The system cannot find the file specified" when using -N

### ISSUE THREAD

**Issue by candrapersada** [yt-dlp/yt-dlp#1222]
## Checklist

- [x] I'm asking a question
- [ ] I've looked through the README
- [ ] I've read the opening an issue section in CONTRIBUTING.md
- [ ] I've searched the bugtracker for similar questions including closed ones
- [ ] I have given an appropriate title to the issue

## Question

WRITE QUESTION HERE
how to automatically resume download when download fails with error message
`ERROR: unable to download video data: <urlopen error [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>` and
`ERROR: unable to download video data: [WinError 2] The system cannot find the file specified: '.part-Frag162.part'`
with `-N` or `--concurrent-fragments`

**Comment by pukkandan** [comment]
Just re-run your command

**Comment by candrapersada** [comment]
> Just re-run your command


I asked for the feature to automatically resume downloading without re-entering the command
