### ISSUE TITLE
[Site Request] youmaker.com (already implemented for youtube-dl)

### ISSUE THREAD

**Issue by flashdagger** [yt-dlp/yt-dlp#1223]
## Checklist

- [x] I'm reporting a new site support request
- [x] I've verified that I'm running yt-dlp version **2021.10.10**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that none of provided URLs violate any copyrights
- [x] The provided URLs do not contain any DRM to the best of my knowledge
- [x] I've searched the bugtracker for similar site support requests including closed ones
- [x] I've read the opening an issue section in CONTRIBUTING.md
- [x] I have given an appropriate title to the issue

## Example URLs

- Single video: http://www.youmaker.com/video/71b5d2c5-31b6-43b8-8475-1dcb5e10dfb0
- Channel: http://www.youmaker.com/channel/f06b2e8d-219e-4069-9003-df343ac5fcf3
- Playlist: https://www.youmaker.com/channel/f8d585f8-2ff7-4c3c-b1ea-a78d77640d54/playlists/f99a120c-7a5e-47b2-9235-3817d1c12662

## Description

Since I already have an implementation with a pending [pull request](https://github.com/ytdl-org/youtube-dl/pull/30048) for youtube-dl I also wanted contribute to yt-dlp.
Because I haven't looked deeply into your codebase here are some questions:
-  are there any differences in the API for extractors? (specifically playlist_result(), _extract_m3u8_formats(), OnDemandPagedList)
- does code formatting with [black](https://pypi.org/project/black/) meet your coding style conventions?
- if not, can it be a achieved with tools?

**Comment by pukkandan** [comment]
> are there any differences in the API for extractors? (specifically playlist_result(), _extract_m3u8_formats(), OnDemandPagedList)

Mostly no. There are some slight improvements, but they can be easily addressed in a code review

> does code formatting with black meet your coding style conventions?

No. Our conventions are the same as youtube-dl's. See https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions

**Comment by flashdagger** [comment]
The extractor is now implemented as a plugin.
