### ISSUE TITLE
which command should I use for downloading multi-audio and multi-sub ?

### ISSUE THREAD

**Issue by MinhajBoss** [yt-dlp/yt-dlp#1240]
you know there are some sites that have multi audio and subtitle support for a single video. is there any way to download all the audio and subtitles for the video?

I am talking about the Curiositystream site.

**Comment by nochlab1** [comment]
I know for subtitles you use --all-subs and then either --embed-subs to embed them or (and) --write-subs to keep the subtitle files

**Comment by nochlab1** [comment]
For audio i think you use --audio-multistreams -f mergeall or -f (VideoQuilty+mergeall)

**Comment by pukkandan** [comment]
> or -f videoquality+mergeall to choose the video quality

should be `-f videoquality+mergeall[vcodec=none]`. Otherwise, all videos will be downloaded
