### ISSUE TITLE
I need to install and use yt-dlp

### ISSUE THREAD

**Issue by Max-Enrik** [yt-dlp/yt-dlp#1252]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README
- [x] I've read the opening an issue section in CONTRIBUTING.md
- [x] I've searched the bugtracker for similar questions including closed ones
- [x] I have given an appropriate title to the issue

## Question

PC - Windows 10 - 21H1

I currently use `youtube-dl` but I need to try `yt-dlp` but I can't do it by myself and even I read `Installation` section, but still need a help to install `yt-dlp` and use it.

Any help highly appreciated.
_English isn't my native language._

**Comment by hbtalha** [comment]
if you have used youtube-dl.exe and you know how it works, then yt-dlp is not different, you use it the same way you use youtube-dl

**Comment by nicolaasjan** [comment]
> but `yt-dlp` doesn't work at all.

Post the output of:

`yt-dlp.exe -vU` 

On my Linux system it looks like this:

```
yt-dlp -vU
[debug] Command-line config: ['-vU']
[debug] User config file: /home/nico/.config/yt-dlp/config
[debug] User config: ['-o', '~/Desktop/test-dlp/%(title)s.%(ext)s', '-f', 'bestvideo[height<=1080][ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best', '--no-mtime', '--add-metadata', '--convert-thumbnails', 'jpg', '--embed-thumbnail', '--force-ipv4', '--sponsorblock-remove', 'all', '--downloader', 'aria2c', '--downloader-args', 'aria2c:-x 10 -s 10 -j 10 -k 1M --log-level=info --file-allocation=none']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] yt-dlp version 2021.10.10 (zip)
[debug] Lazy loading extractors enabled
[debug] Python version 3.6.9 (CPython 64bit) - Linux-5.4.0-87-generic-x86_64-with-LinuxMint-19.3-tricia
[debug] exe versions: ffmpeg N-104315-g148ada5577-Nico-20211011-With-VP9-Timestamp-Fix, ffprobe N-104315-g148ada5577-Nico-20211011-With-VP9-Timestamp-Fix
[debug] Optional libraries: Cryptodome, keyring, mutagen, sqlite, websockets
[debug] ANSI escape support: stdout = True, stderr = True
[debug] Proxy map: {}
yt-dlp is up to date (2021.10.10)

```

**Comment by nicolaasjan** [comment]
**Tip**:
You can use yt-dlp in the command prompt from any location.
Just add the folder where the .exe is in, to your PATH.

For example, when it is in `C:\Program files\mpv`, do this: 

Open the command prompt as administrator: 
Click Start, type `cmd`. When the cmd.exe icon appears, right click and select "Run as administrator".

To add/update system environment variables paste this in and hit enter: 

`setx /m PATH "%PATH%;C:\Program files\mpv"`

Or if you like the GUI way:  
https://www.computerhope.com/issues/ch000549.htm

When you've done that, you can just type `yt-dlp [OPTIONS] [URL]` in CMD (no need to type `yt-dlp.exe`).

**Comment by pukkandan** [comment]
> Now I need to be able to watch video by using mpv player and using yt-dlp.

See mpv's documentation. They have an option to use yt-dlp instead of youtube-dl

**Comment by pukkandan** [comment]
Closed due to inactivity

**Comment by srroger956** [comment]
I make a folder and put the yt-dlp.exe on it, open cmd inside the folder and I type yt-dlp.exe but it didn’t work. Terminal  suggested me type .\yt-dlp.exe and it works
