### ISSUE TITLE
[Question] Converting your downloads to other formats

### ISSUE THREAD

**Issue by hbtalha** [yt-dlp/yt-dlp#1255]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README
- [x] I've read the opening an issue section in CONTRIBUTING.md
- [x] I've searched the bugtracker for similar questions including closed ones
- [x] I have given an appropriate title to the issue

## Question

I am downloading videos with the default format option (bestvideo+bestaudio) and I want have my downloaded video in one of these formats: mkv, mp4, ogg, webm, flv.

There's the option `--recode-video FORMAT` that works just fine but the problem is that it is too CPU intensive. 

Another option is to use `--merge-output-format FORMAT` but this doesn't seem to work with all the formats (not sure if I should open an issue for that), the only format it always that worked when used in my tests where mkv and mp4, ogg and flv didn't work for any video in my tests, webm worked on some videos.

So I am wondering if there are other options I could use?

**Comment by Ashish0804** [comment]
`this doesn't seem to work with all the formats`
This is because it's only triggered when merge is required. So if a site serves a mp4 with both video and audio, there's no need to merge.

Other than that most sites provide video in mp4, if an extractor is providing video in m3u8 or another meme language then it's proly a bug

**Comment by hbtalha** [comment]
> So if a site serves a mp4 with both video and audio, there's no need to merge.

With `bestvideo+bestaudio` I believe all videos must be merged, but the option `--merge-output-format ` doesn't work with all the formats mentioned in doc

**Comment by pukkandan** [comment]
ffmpeg will throw error for --merge-output-format if the formats are not actually mergeable in the given extension. You have to reencode with --recode otherwise
