### ISSUE TITLE
Using yt-dlp in 32 bit  XP machine 

### ISSUE THREAD

**Issue by bonacker1** [yt-dlp/yt-dlp#1274]
I downloaded yt-dlp.exe and yt-dlp_x86.exe, but I get an error message from Windows that the exe is not a valid Win 32 application.

I am still using XP. (There are reasons why.) I have a 32 bit machine. Is the problem related to XP? If so, are there any Windows executables available anywhere  for XP other than the two in the Github yt-dlp releases page? Is there any workaround?

Is there any way to use the last version of yt-dlc from a year ago that does work for me to update it to include the fixes in yt-dlp?

TIA

**Comment by pbcairo** [comment]
@bonacker1 Thankfully someone ported it to Windows XP - https://github.com/nicolaasjan/yt-dlp/releases/download/2023.04.06.082550/yt-dlp_x86_Windows-XP.zip

https://github.com/nicolaasjan/yt-dlp/releases (use `yt-dlp_x86_Windows-XP.zip`)

I think it's kinda slower than the official version though
