### ISSUE TITLE
[Bug] Unable to use cookies in multibyte environments

### ISSUE THREAD

**Issue by suica2k4** [yt-dlp/yt-dlp#1276]
## Checklist

- [x] I'm reporting a bug unrelated to a specific site
- [x] I've verified that I'm running yt-dlp version **2021.10.10**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] The provided URLs do not contain any DRM to the best of my knowledge
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read the opening an issue section in CONTRIBUTING.md
- [x] I have given an appropriate title to the issue

## Verbose log

```
G:\tools\yt-dlp>yt-dlp.exe -v "https://www.youtube.com/watch?v=bhv4JMBHkJs" --cookies-from-browser chrome --extractor-args youtube:player_client=android -f bestvideo+bestaudio  --ffmpeg-location "G:\tools\Encode\ffmpeg-4.3.1-2020-10-01-full_build\bin\ffmpeg.exe"
[debug] Command-line config: ['-v', 'https://www.youtube.com/watch?v=bhv4JMBHkJs', '--cookies-from-browser', 'chrome', '--extractor-args', 'youtube:player_client=android', '-f', 'bestvideo+bestaudio', '--ffmpeg-location', 'G:\\tools\\Encode\\ffmpeg-4.3.1-2020-10-01-full_build\\bin\\ffmpeg.exe']
[Cookies] Extracting cookies from chrome
[debug] Extracting cookies from: "C:\Users\[user name]\AppData\Local\Google\Chrome\User Data\Default\Cookies"
Traceback (most recent call last):
  File "yt_dlp\__main__.py", line 19, in <module>
  File "yt_dlp\__init__.py", line 779, in main
  File "yt_dlp\__init__.py", line 740, in _real_main
  File "yt_dlp\YoutubeDL.py", line 602, in __init__
  File "yt_dlp\YoutubeDL.py", line 3332, in _setup_opener
  File "yt_dlp\cookies.py", line 78, in load_cookies
  File "yt_dlp\cookies.py", line 96, in extract_cookies_from_browser
  File "yt_dlp\cookies.py", line 237, in _extract_chrome_cookies
  File "yt_dlp\cookies.py", line 315, in get_cookie_decryptor
  File "yt_dlp\cookies.py", line 385, in __init__
  File "yt_dlp\cookies.py", line 624, in _get_windows_v10_key
  File "json\__init__.py", line 293, in load
UnicodeDecodeError: 'cp932' codec can't decode byte 0x86 in position 4164: illegal multibyte sequence
[21652] Failed to execute script '__main__' due to unhandled exception!
```

## Description

An error occurs when the option "--cookies-from-browser" is specified in a multibyte environment (e.g. Japanese).

In Windows 10, the default character encoding is "utf8", but if you load a file using "open" without specifying the character encoding, it will be processed as "cp932".

In a single-byte environment with only alphabetic characters, there is no problem because both "utf8" and "cp932" are the same character code, but in a multi-byte environment, there will be garbled characters and an error will occur.

This can be avoided by modifying line 623 of cookies.py as follows, so please reflect it in the source code.

[Before modification]
`with open(path, 'r') as f:`

[After correction]
`with open(path, 'r', encoding="utf8") as f:`

Thanks to the development team.

**Comment by pukkandan** [comment]
@mbway Can u confirm this won't break anything else?

**Comment by mbway** [comment]
the different browsers store their cookies differently. Only chromium based browsers on windows store this value in a json file. firefox uses sqlite to store cookies for example.
There are places where I just assumed UTF-8 like with the cookie names/values so it's possible there are other encoding issues but hopefully UTF-8 is used everywhere for the cookie names/values
