### ISSUE TITLE
[Feature Request] Remove default value for extractor_retries

### ISSUE THREAD

**Issue by makeworld-the-better-one** [yt-dlp/yt-dlp#1290]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running yt-dlp version **2021.10.10**
- [x] I've searched the bugtracker for similar feature requests including closed ones
- [x] I've read the opening an issue section in CONTRIBUTING.md
- [x] I have given an appropriate title to the issue

## Description

Currently, `--extractor-retries` has a default value of 3. I think having a default value is pointless, as when used in the code, a default value needs to be specified anyway. Here are the places `extractor_retries` is referenced in the code as of now:

```
➤ rg extractor_retries
yt_dlp/YoutubeDL.py
457:    extractor_retries: Number of times to retry for known errors

yt_dlp/options.py
1487:        dest='extractor_retries', metavar='RETRIES', default=3,

yt_dlp/__init__.py
210:    if opts.extractor_retries is not None:
211:        opts.extractor_retries = parse_retries(opts.extractor_retries, 'extractor ')
631:        'extractor_retries': opts.extractor_retries,

yt_dlp/extractor/cbc.py
255:        retries = self.get_param('extractor_retries', 15)

yt_dlp/extractor/soundcloud.py
675:        retries = self.get_param('extractor_retries', 3)

yt_dlp/extractor/tiktok.py
422:        max_retries = self.get_param('extractor_retries', 3)

yt_dlp/extractor/youtube.py
799:        retries = self.get_param('extractor_retries', 3)
4217:        retries = self.get_param('extractor_retries', 3)

```

As you can see, there is always a default. But in the case of `cbc.py`, the default is higher than 3, and so the whole thing becomes pointless. If a user doesn't specify `--extractor-retries`, it will get set to 3. If they do specify it, then the code default of `15` is unused. Either way `15` is unused.

To be honest, I will probably be removing that code from cbc.py in a future PR for unrelated reasons, but when testing, I realized the issue with having a default value.

**Comment by pukkandan** [comment]
Was there any specific reason why the CBC one is 15? It is better to have consistent behavior across the various extractors

**Comment by pukkandan** [comment]
From all the extractors that currently use retries, this does not appear to be a necessary change. This can be re-opened if it becomes usefull in future.

Having to do `self.get_param('extractor_retries', 3)` in each extractor is indeed bad code. But https://github.com/yt-dlp/yt-dlp/pull/1649 should fix that
