### ISSUE TITLE
[Site Feature] gronkh.tv

### ISSUE THREAD

**Issue by rGunti** [yt-dlp/yt-dlp#1293]
## Checklist

- [x] I'm reporting a site feature request
- [x] I've verified that I'm running yt-dlp version **2021.10.10**
- [x] I've searched the bugtracker for similar site feature requests including closed ones
- [x] I've read the opening an issue section in CONTRIBUTING.md
- [x] I have given an appropriate title to the issue

## Description

gronkh.tv is a new streaming platform by German YouTuber and Twitch streamer Erik "Gronkh" Range. He provides recordings of his streams and let's plays in the future. It would be cool if `yt-dlp` could support that site.

**Comment by pukkandan** [comment]
You used the wrong template. It's fine though as long as you can **Provide example URLs*
