### ISSUE TITLE
[Broken] Odysee: Only lists the last 1000 videos

### ISSUE THREAD

**Issue by christoph-heinrich** [yt-dlp/yt-dlp#1296]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running yt-dlp version **2021.10.10**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones
- [x] I've read the opening an issue section in CONTRIBUTING.md
- [x] I have given an appropriate title to the issue

## Verbose log

```
[debug] Command-line config: ['--ignore-config', '-v', '-F', 'https://odysee.com/@21:7']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] yt-dlp version 2021.10.10 (zip)
[debug] Python version 3.9.7 (CPython 64bit) - Linux-5.14.12-arch1-1-x86_64-with-glibc2.33
[debug] exe versions: ffmpeg 4.4, ffprobe 4.4, rtmpdump 2.4
[debug] Optional libraries: Crypto, mutagen, sqlite, websockets
[debug] ANSI escape support: stdout = False, stderr = False
[debug] Proxy map: {}
[debug] [lbry:channel] Extracting URL: https://odysee.com/@21:7
[lbry:channel] @21#7: Downloading channel JSON metadata
[download] Downloading playlist: 21 Studios
[lbry:channel] 7f1137707c918dab287ac91c9dbb28748696a36b: Downloading page 1 JSON metadata
[lbry:channel] 7f1137707c918dab287ac91c9dbb28748696a36b: Downloading page 2 JSON metadata
[lbry:channel] 7f1137707c918dab287ac91c9dbb28748696a36b: Downloading page 3 JSON metadata
[lbry:channel] 7f1137707c918dab287ac91c9dbb28748696a36b: Downloading page 4 JSON metadata
[lbry:channel] 7f1137707c918dab287ac91c9dbb28748696a36b: Downloading page 5 JSON metadata
[lbry:channel] 7f1137707c918dab287ac91c9dbb28748696a36b: Downloading page 6 JSON metadata
[lbry:channel] 7f1137707c918dab287ac91c9dbb28748696a36b: Downloading page 7 JSON metadata
[lbry:channel] 7f1137707c918dab287ac91c9dbb28748696a36b: Downloading page 8 JSON metadata
[lbry:channel] 7f1137707c918dab287ac91c9dbb28748696a36b: Downloading page 9 JSON metadata
[lbry:channel] 7f1137707c918dab287ac91c9dbb28748696a36b: Downloading page 10 JSON metadata
[lbry:channel] 7f1137707c918dab287ac91c9dbb28748696a36b: Downloading page 11 JSON metadata
[lbry:channel] 7f1137707c918dab287ac91c9dbb28748696a36b: Downloading page 12 JSON metadata
[lbry:channel] 7f1137707c918dab287ac91c9dbb28748696a36b: Downloading page 13 JSON metadata
[lbry:channel] 7f1137707c918dab287ac91c9dbb28748696a36b: Downloading page 14 JSON metadata
[lbry:channel] 7f1137707c918dab287ac91c9dbb28748696a36b: Downloading page 15 JSON metadata
[lbry:channel] 7f1137707c918dab287ac91c9dbb28748696a36b: Downloading page 16 JSON metadata
[lbry:channel] 7f1137707c918dab287ac91c9dbb28748696a36b: Downloading page 17 JSON metadata
[lbry:channel] 7f1137707c918dab287ac91c9dbb28748696a36b: Downloading page 18 JSON metadata
[lbry:channel] 7f1137707c918dab287ac91c9dbb28748696a36b: Downloading page 19 JSON metadata
[lbry:channel] 7f1137707c918dab287ac91c9dbb28748696a36b: Downloading page 20 JSON metadata
[lbry:channel] 7f1137707c918dab287ac91c9dbb28748696a36b: Downloading page 21 JSON metadata
[lbry:channel] playlist 21 Studios: Downloading 1000 videos
[download] Downloading video 1 of 1000
[debug] [lbry] Extracting URL: https://odysee.com/top-21-tiktok-men-keeping-women-in-2:e9bac2aed179bcabb25c8d8e34b8c328724e41e1
[lbry] top-21-tiktok-men-keeping-women-in-2#e9bac2aed179bcabb25c8d8e34b8c328724e41e1: Downloading stream JSON metadata
[lbry] e9bac2aed179bcabb25c8d8e34b8c328724e41e1: Downloading streaming url JSON metadata
[lbry] top-21-tiktok-men-keeping-women-in-2#e9bac2aed179bcabb25c8d8e34b8c328724e41e1: Downloading streaming redirect url info
[info] Available formats for e9bac2aed179bcabb25c8d8e34b8c328724e41e1:
ID EXT RESOLUTION |  FILESIZE  PROTO | VCODEC  ACODEC
-- --- ---------- - ---------- ----- - ------- -------
0  mp4 1920x1080  |  216.55MiB https | unknown unknown
[download] Downloading video 2 of 1000
[debug] [lbry] Extracting URL: https://odysee.com/donovan-sharpe-admits-he's-super-dumb:03bcbf1b0d53850da48de14b8d8f3904958a7fb9
[lbry] donovan-sharpe-admits-he's-super-dumb#03bcbf1b0d53850da48de14b8d8f3904958a7fb9: Downloading stream JSON metadata
[lbry] 03bcbf1b0d53850da48de14b8d8f3904958a7fb9: Downloading streaming url JSON metadata
[lbry] donovan-sharpe-admits-he's-super-dumb#03bcbf1b0d53850da48de14b8d8f3904958a7fb9: Downloading streaming redirect url info
[info] Available formats for 03bcbf1b0d53850da48de14b8d8f3904958a7fb9:
ID EXT RESOLUTION |  FILESIZE PROTO | VCODEC  ACODEC
-- --- ---------- - --------- ----- - ------- -------
0  mp4 1920x1080  |  22.01MiB https | unknown unknown
.
.
.
[download] Downloading video 999 of 1000
[debug] [lbry] Extracting URL: https://odysee.com/what-exists-because-of-you-zan-perrion:87e04d7c2cc95cf1f33377d9736a77cfc2a53b8f
[lbry] what-exists-because-of-you-zan-perrion#87e04d7c2cc95cf1f33377d9736a77cfc2a53b8f: Downloading stream JSON metadata
[lbry] 87e04d7c2cc95cf1f33377d9736a77cfc2a53b8f: Downloading streaming url JSON metadata
[lbry] what-exists-because-of-you-zan-perrion#87e04d7c2cc95cf1f33377d9736a77cfc2a53b8f: Downloading streaming redirect url info
[info] Available formats for 87e04d7c2cc95cf1f33377d9736a77cfc2a53b8f:
ID EXT RESOLUTION |  FILESIZE PROTO | VCODEC  ACODEC
-- --- ---------- - --------- ----- - ------- -------
0  mp4 1920x1080  |  74.73MiB https | unknown unknown
[download] Downloading video 1000 of 1000
[debug] [lbry] Extracting URL: https://odysee.com/the-3-masculine-style-archetypes-tanner:675a9490d2c78fd61d7d7f0e10d4d9ab46fc93b9
[lbry] the-3-masculine-style-archetypes-tanner#675a9490d2c78fd61d7d7f0e10d4d9ab46fc93b9: Downloading stream JSON metadata
[lbry] 675a9490d2c78fd61d7d7f0e10d4d9ab46fc93b9: Downloading streaming url JSON metadata
[lbry] the-3-masculine-style-archetypes-tanner#675a9490d2c78fd61d7d7f0e10d4d9ab46fc93b9: Downloading streaming redirect url info
[info] Available formats for 675a9490d2c78fd61d7d7f0e10d4d9ab46fc93b9:
ID EXT RESOLUTION |  FILESIZE PROTO | VCODEC  ACODEC
-- --- ---------- - --------- ----- - ------- -------
0  mp4 1280x720   |  17.30MiB https | unknown unknown
[download] Finished downloading playlist: 21 Studios

```

## Description

In June I opened an [issue in the youtube-dl repo](https://github.com/ytdl-org/youtube-dl/issues/29311) and the problem still exists. Since development has stopped over there, I'm linking it here.
Btw I didn't explicitly point this out in the other issue, but it doesn't just list the last 1000 videos when running it with -F, but also when trying to download the whole channel (probably uses the same code anyway, just wanted to make sure).

**Comment by Ashish0804** [comment]
Even the site only shows 1000 videos
![Screenshot from 2021-10-16 09_07_25](https://user-images.githubusercontent.com/39122144/137572285-f0dca243-eb59-4699-8161-60d29c3b5b46.png)
![Screenshot from 2021-10-16 09_07_16](https://user-images.githubusercontent.com/39122144/137572286-0e74edc0-6026-4d8e-bf16-5177b9d262e8.png)
![Screenshot from 2021-10-16 09_10_31](https://user-images.githubusercontent.com/39122144/137572359-4fa22608-c889-435e-90bc-22d5a96b7e9f.png)

The api gives literally an empty list for page 21 so it's working as expected. 
![Screenshot from 2021-10-16 09_08_13](https://user-images.githubusercontent.com/39122144/137572337-c33cb98c-1fcb-4748-b77b-a80586744162.png)

**Comment by christoph-heinrich** [comment]
Oh, I didn't realize that. Thanks for looking into this so quickly.

**Comment by HakkaTjakka** [comment]
I've made a script for bash:
`
#!/bin/bash

get_page() {
	curl  --location --request POST \
		'https://api.lbry.tv/api/v1/proxy' \
		--header 'Content-Type: application/json' \
		--data-raw '{
		"method": "claim_search",
			"params": {
				"channel": "@English_Subtitles:b",
				"order_by": "creation_timestamp",
				"page": '$1',
				"release_time": "<'$2'",
				"page_size": 50
			}
		}' > test.json

# 			"release_time": "<1725400800",
}

proces_json() {
	if [ -f "hoppa.txt" ]; then
		rm hoppa.txt 
	fi
	start=true
	while IFS= read -r line1 && IFS= read -r line2 <&3 && IFS= read -r line3 <&4; do
	  	counter=$((counter+1))
	  	counter_tot=$((counter_tot+1))
	  	date=$(date -d @$line1 +"%F %T")
		if [ $start == true ]; then 
			start=false
			date_start=$(date -d @$line1 +"%F_%T")
		fi
		timestamp_end=$line1
	  	printf "%4d timestamp: $line1 - date: %s - title: %s - ulr: %s\n" "$counter_tot" "$date" "$line2" "$line3" >> $4
	  	printf "%4d timestamp: $line1 - date: %s - title: %s - ulr: %s\n" "$counter_tot" "$date" "$line2" "$line3"
	done < $1 3< $2 4< $3
}

proces_json2() {
	start=true
	while IFS= read -r line1 && IFS= read -r line2 <&3; do
	  	counter=$((counter+1))
	  	counter_tot=$((counter_tot+1))
	  	date=$(date -d @$line1 +"%F %T")
		if [ $start == true ]; then 
			start=false
			date_start=$(date -d @$line1 +"%F_%T")
		fi
		timestamp_end=$line1
	  	printf "%4d timestamp: $line1	- date: %s  - url/title: %s \n" "$counter_tot" "$date" "$line2" >> $3
	  	printf "%4d timestamp: $line1	- date: %s  - url/title: %s \n" "$counter_tot" "$date" "$line2"
	done < $1 3< $2
}

GET_1000_MAX() {
	if [ ! -d "output" ]; then
		mkdir output
	fi
	counter=0
	date_start=""
	date_end=""
	
	if [ -f "hoppa.tot" ]; then
		rm hoppa.tot 
	fi
	
	PAGE=1
	now=$1
	while : ; do
		get_page $PAGE $now

		jq -r '  .result.items.[].meta.creation_timestamp ' test.json > creation_timestamp.txt
		jq -r '  .result.items.[].canonical_url ' test.json > canonical_url.txt
		jq -r '  .result.items.[].value.title ' test.json > title.txt
		jq -r '  .result.items.[].value.tags | @sh ' test.json > tags.txt
		jq -r '  .result.items.[].value.video.duration ' test.json > duration.txt
		jq -r '  .result.items.[].value.thumbnail.url ' test.json > thumbnail.txt

		cat creation_timestamp.txt >> creation_timestamp.tot
		cat canonical_url.txt >> canonical_url.tot
		cat title.txt >> title.tot
		cat tags.txt >> tags.tot
		cat duration.txt >> duration.tot
		cat thumbnail.txt >> thumbnail.tot

#		date -d@12345 -u +%H:%M:%S

#		jq -r '  .result.items.[].short_url ' test.json > hoppa2.txt
	
		proces_json creation_timestamp.txt canonical_url.txt title.txt hoppa.txt
	
		filename="English_Subtitles_"$date_start".json"
		cp "test.json" "output/$filename"
	
		cat hoppa.txt >> hoppa.tot
		PAGES=$(jq -r '.result| "\(.page) \(.total_pages)"' test.json)
		IFS=' ' read PAGE TOTAL_PAGES	<<< $(echo $PAGES)
		echo "Page $PAGE of $TOTAL_PAGES"
	  if [ $PAGE == $TOTAL_PAGES ]; then
	  	break
	  else
	 # 	echo -n "Sleeping 5"
	 # 	sleep 1
	 # 	echo -ne "\rSleeping 4"
	 # 	sleep 1
	 # 	echo -ne "\rSleeping 3"
	 # 	sleep 1
	 # 	echo -ne "\rSleeping 2"
	 # 	sleep 1
	  	echo -ne "\rSleeping 1"
	  	sleep 1
		  echo -ne "\r          \r"
	  fi
		PAGE=$((PAGE+1))
	done
	
	sort --key=3 -r hoppa.tot >> hoppa.srt
	
	date_end=$(date -d @$timestamp_end +"%F_%T")
	filename="English_Subtitles_"$date_end".srt"
	cp "hoppa.srt" "output/$filename"
}

timestamp_end=0
counter_tot=0
counter=0

rm creation_timestamp.tot
rm canonical_url.tot
rm title.tot
rm tags.tot
rm duration.tot
rm thumbnail.tot

GET_1000_MAX $(date +%s)
while [ $counter == 1000 ];
do
	GET_1000_MAX $timestamp_end
done

#now=$(date +%s)
#now=1731514873
#now=1727389683

rm url.tot
rm total_title.tot
rm title_url.tot

counter_tot=0
counter=0

proces_json2 creation_timestamp.tot canonical_url.tot url.tot

counter_tot=0
counter=0

proces_json2 creation_timestamp.tot title.tot total_title.tot

counter_tot=0
counter=0

proces_json creation_timestamp.tot title.tot canonical_url.tot title_url.tot

sort --key=3 -r url.tot > url.srt
sort --key=3 -r total_title.tot > total_title.srt
sort --key=3 -r title_url.tot > total_title_url.srt

sort --key=10 url.tot > url2.srt
sort --key=10 total_title.tot > total_title2.srt
sort --key=10 title_url.tot > total_title_url2.srt



`
