### ISSUE TITLE
[YouTube] No exception raised if retries are exhausted by incomplete data errors.

### ISSUE THREAD

**Issue by colethedj** [yt-dlp/yt-dlp#130]
## Checklist

- [ ] I'm reporting a broken site support issue
- [X] I've verified that I'm running yt-dlp version **2021.03.01**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar bug reports including closed ones
- [X] I've read bugs section in FAQ

## Verbose log

```
yt-dlp --verbose --flat-playlist "https://www.youtube.com/SBTjornalismo/videos?sort=da" --extractor-retries 3
[debug] Command-line config: ['--verbose', '--flat-playlist', 'https://www.youtube.com/SBTjornalismo/videos?sort=da', '--extractor-retries', '3']
[debug] Loading archive file None
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] yt-dlp version 2021.03.01 
[debug] Python version 3.9.1 (CPython 64bit) - Linux-5.10.15-1-MANJARO-x86_64-with-glibc2.33
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1, rtmpdump 2.4
[debug] Proxy map: {}
[youtube:tab] SBTjornalismo: 
[download] Downloading playlist: SBT Jornalismo - Videos
[youtube:tab] Downloading page 1
WARNING: [youtube:tab] Incomplete data recieved. Retrying ...
[youtube:tab] Downloading page 1 (retry #1)
WARNING: [youtube:tab] Incomplete data recieved. Retrying ...
[youtube:tab] Downloading page 1 (retry #2)
WARNING: [youtube:tab] Incomplete data recieved. Retrying ...
[youtube:tab] Downloading page 1 (retry #3)
[youtube:tab] playlist SBT Jornalismo - Videos: Downloading 10 videos
[download] Downloading video 1 of 10
[download] Downloading video 2 of 10
[download] Downloading video 3 of 10
[download] Downloading video 4 of 10
[download] Downloading video 5 of 10
[download] Downloading video 6 of 10
[download] Downloading video 7 of 10
[download] Downloading video 8 of 10
[download] Downloading video 9 of 10
[download] Downloading video 10 of 10
[download] Finished downloading playlist: SBT Jornalismo - Videos
```

## Description

Reported on discord but writing here to help keep track.

This channel, sorted by oldest is erroneous as of typing however has uncovered a small issue:

In this case the initial page was downloaded (with 10 videos, not the issue here) and the subsequent pages using the continuation were providing incomplete data. Once the retries were used up no error is raised. This means the extractor returns what videos it had extracted,   incorrectly treating the partial download as successful.

**Comment by pukkandan** [comment]
If I throw an error in that case, then no videos will be downloaded. Not sure if it is possible to download the available videos, but then also throw error

**Comment by pukkandan** [comment]
The error will be thrown now, but the videos will still be downloaded unless `--abort-on-error` is given. The exact implementation is a bit non-standard, but I couldn't find any other way to do it

**Comment by colethedj** [comment]
I was just looking at consistency with the extractor - when it e.g. exhaust retries on 404's it'll raise the ExtractorError and stop, so was thinking similar thing should happen for the incomplete data "extractor error".
