### ISSUE TITLE
[Bug] "duration_string" match-filter skips all videos

### ISSUE THREAD

**Issue by mhogomchungu** [yt-dlp/yt-dlp#1309]
## Checklist

- [x ] I'm reporting a bug unrelated to a specific site
- [x ] I've verified that I'm running yt-dlp version **2021.10.10**
- [x ] I've checked that all provided URLs are alive and playable in a browser
- [x ] The provided URLs do not contain any DRM to the best of my knowledge
- [x ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x ] I've searched the bugtracker for similar bug reports including closed ones
- [ x] I've read the opening an issue section in CONTRIBUTING.md
- [x ] I have given an appropriate title to the issue

## Verbose log

Below command does not produce any hits
```
yt-dlp "--dump-json" "--match-filter" "duration_string<=00:05:00" "https://www.youtube.com/playlist?list=PLB0j2hqgnW6UEIjZ6gFpgQXBdE0tayAlk"
WARNING: [youtube:tab] YouTube said: INFO - 2 unavailable videos are hidden
WARNING: [youtube:tab] YouTube said: INFO - Unavailable videos will be hidden during playback
ERROR: [youtube] _5QTUFE_raY: Video unavailable. This video is no longer available because the YouTube account associated with this video has been terminated.
ERROR: [youtube] duw9KIGve0k: Video unavailable. This video is no longer available due to a copyright claim by Bangladesh Television.
```
## Description

1. "--match-filter" "duration_string<=00:05:00" does not seem to be working.
2. "--match-filter" "duration<=300" works as expected.
3. Above two lines should work the same way

**Comment by pukkandan** [comment]
There are some fields that are not available in `--match-filter`, but only in `--output`/`--print`. `duration_string` is one of them. I'll add this to the documentation.

That said, even if it were available in filter, it is a string which means it is compared lexically against other durations and so is not the same as comparing using duration

**Comment by pukkandan** [comment]
Not possible. duration_**string** can only do string comparison.

I can probably make it possible to do `duration<=00:05:00` though

**Comment by dirkf** [comment]
In 18f96d1, the regex group `intval` was removed but this later line still (now) references the non-existent group
```diff
-        comparison_value = m['quotedstrval'] or m['strval'] or m['intval']
+        comparison_value = m['quotedstrval'] or m['strval']
```
