### ISSUE TITLE
Iwara parser format sort picks the wrong "best" format. 

### ISSUE THREAD

**Issue by pxssy** [yt-dlp/yt-dlp#1315]
## Checklist

- [ ] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2021.10.10**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] The provided URLs do not contain any DRM to the best of my knowledge
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar bug reports including closed ones
- [X] I've read the opening an issue section in CONTRIBUTING.md
- [X] I have given an appropriate title to the issue

## Verbose log

```
yt-dlp -F https://www.iwara.tv/videos/lw7reuk6li8kyxa6
[Iwara] lw7reuk6li8kyxa6: Downloading webpage
[Iwara] lw7reuk6li8kyxa6: Downloading JSON metadata
[info] Available formats for lw7reuk6li8kyxa6:
ID     EXT RESOLUTION | PROTO | VCODEC  ACODEC
------ --- ---------- - ----- - ------- -------
Source mp4 unknown    | https | unknown unknown
360p   mp4 640x360    | https | unknown unknown
540p   mp4 960x540    | https | unknown unknown

```

## Description

format sort by resolution or size always picks the 540p instead of the "source", but "source" is better and should be prioritized over 540p. i think the issue is just that it can't sort numbers and alphabets and still deduce the best format. This site needs an exception, to pick source over 540p.

**Comment by pukkandan** [comment]
Closed due to inactivity
