### ISSUE TITLE
[Feature Request] Sponsorblock API should time-out if unreachable

### ISSUE THREAD

**Issue by gergles** [yt-dlp/yt-dlp#1320]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running yt-dlp version **2021.10.10**
- [x] I've searched the bugtracker for similar feature requests including closed ones
- [x] I've read the opening an issue section in CONTRIBUTING.md
- [x] I have given an appropriate title to the issue

## Description

Right now, the primary SponsorBlock API server is down – the connect() call succeeds but then the remote end never responds.

I have sponsorblock enabled in my config file, so yt-dlp is trying to contact the sponsorblock server, receiving no response, and then hanging forever.

I'd propose that a timeout be added to the sponsorblock API call to continue without sponsorblock data in the event that the server is down or providing invalid responses (after printing an error message?)

The least user-friendly part of this is that I had no way to determine this was related to Sponsorblock without running yt-dlp in debug mode, as no sponsorblock status message is printed:

```
% yt-dlp -x "https://www.youtube.com/watch?v=r2Kh_XMIDPU"
[youtube] r2Kh_XMIDPU: Downloading webpage
[youtube] r2Kh_XMIDPU: Downloading android player API JSON
{it hangs here}^C
ERROR: Interrupted by user
```

However, if you add --debug to the arguments, you can see that this is actually hanging at the Sponsorblock query:
```
% yt-dlp --verbose -x "https://www.youtube.com/watch?v=r2Kh_XMIDPU"                             
[debug] Command-line config: ['--verbose', '-x', 'https://www.youtube.com/watch?v=r2Kh_XMIDPU']
[debug] User config file: /home/me/.config/yt-dlp/config
[debug] User config: ['--sponsorblock-remove', 'sponsor', '--sponsorblock-mark', 'all', '--no-mtime']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] yt-dlp version 2021.10.10
[debug] Python version 3.8.10 (CPython 64bit) - Linux-5.4.0-88-generic-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4, rtmpdump 2.4
[debug] Optional libraries: Cryptodome, keyring, mutagen, sqlite, websockets
[debug] ANSI escape support: stdout = True, stderr = True
[debug] Proxy map: {}
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=r2Kh_XMIDPU
[youtube] r2Kh_XMIDPU: Downloading webpage
[youtube] r2Kh_XMIDPU: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, source, codec:vp9.2, lang
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, source, vcodec:vp9.2(10), acodec, lang, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, id
[debug] SponsorBlock query: https://sponsor.ajay.app/api/skipSegments/a3dc?service=YouTube&categories=%5B%22sponsor%22%2C+%22interaction%22%2C+%22preview%22%2C+%22selfpromo%22%2C+%22outro%22%2C+%22intro%22%2C+%22music_offtopic%22%5D
{it hangs here}
```

**Comment by pukkandan** [comment]
It times out after the period given by `--socket-timeout`. By default, it is 10 minutes. I have no idea why. But this is inherited behavior from youtube-dl and so I am wary of changing it without understanding why it was set to be so large in the first place. I recommend manually passing a smaller value for it

> The least user-friendly part of this is that I had no way to determine this was related to Sponsorblock without running yt-dlp in debug mode, as no sponsorblock status message is printed:

I'll add a message

**Comment by shakeyourbunny** [comment]
Currently, I'm getting HTTP 502 on retrieving sponsorblock data.
