### ISSUE TITLE
[Question] A short description of your question

### ISSUE THREAD

**Issue by PredatorHackerzZ** [yt-dlp/yt-dlp#1321]
## Checklist

- [ ] I'm asking a question
- [ ] I've looked through the README
- [ ] I've read the opening an issue section in CONTRIBUTING.md
- [ ] I've searched the bugtracker for similar questions including closed ones
- [ ] I have given an appropriate title to the issue

## Question

WRITE QUESTION HERE

Can You please make it deployable on heroku..... Please....... That we can us it on telegram. ... 

Thank You😊

**Comment by pukkandan** [comment]
No. Feel free to do so yourself
