### ISSUE TITLE
[Question] I have some questions with yt-dlp for Manjaro

### ISSUE THREAD

**Issue by candrapersada** [yt-dlp/yt-dlp#1325]
## Checklist

- [x] I'm asking a question
- [ ] I've looked through the README
- [ ] I've read the opening an issue section in CONTRIBUTING.md
- [ ] I've searched the bugtracker for similar questions including closed ones
- [ ] I have given an appropriate title to the issue

## Question

WRITE QUESTION HERE
I have some questions with yt-dlp for Manjaro. I get this error when I try to download a video:
`ERROR: Unable to download webpage: <urlopen error [Errno -2] Name or service not known> (caused by URLError(gaierror(-2, 'Name or service not known'),))
`

**Comment by coletdjnz** [comment]
DNS or networking issue on your side.
