### ISSUE TITLE
[Feature Request] Special symbols for filenames

### ISSUE THREAD

**Issue by mlatushko** [yt-dlp/yt-dlp#1330]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running yt-dlp version **2021.10.10**
- [x] I've searched the bugtracker for similar feature requests including closed ones
- [x] I've read the opening an issue section in CONTRIBUTING.md
- [x] I have given an appropriate title to the issue

## Description

To replace these symbols for filenames:

```
¦ǀǁ❙|︱︳—— ｜
/ ╱⧸̷ ⁄ —— ／
?؟¿❓ —— ‽
: —— ：
\╲⧹ —— ＼
«» ‹› ⟪⟫ ≪ ≫❛❜ ❝❞ —— “”
✖ × —— x
＆ —— &
❗¡ —— !
```

Also may be used:
．，·

( Now it works like: original STRING: STRING ——  STRING - STRING )

**Comment by pukkandan** [comment]
what!?

**Comment by pukkandan** [comment]
Please provide a list of which characters you think should be replaced, and with what. We can implement it when not `--restricted-filenames`

**Comment by mlatushko** [comment]
Hello. I can’t check if the characters are matching for systems except Win7.

```
¦ǀǁ❙|︱︳—— ｜
/ ╱⧸̷ ⁄ —— ／
?؟¿❓ —— ‽
: —— ：
\╲⧹ —— ＼
«» ⟪⟫ ≪≫ ❝❞ —— “”
❛❜ —— ‘’
(quotation marks; which are better?) " —— ‚ „ ̔̕ ̏ ̎ ̍ ̒̓ `´
✖ —— ×(x)
＆⅋ —— &
💲 —— $
❗¡ —— !
< —— ‹
> —— ›
* —— ＊
⁏ —— ;
➕ +
ё|е¨ —— ё
й —— й
ｉ —— i
(delete symbols)[​  ‏‎]
∽ —— ~(～)
… —— ...
(emphasis)[̀◌́][′׳᾿ˈꞌ] —— [`´](which is better?)
(other symbols may be replaced|filled by the marks)··•◘♥♦♣♠
[⠀　 ] —— [ ]
⁽⁾ —— ()
①②③④⑤⑥⑦⑧⑨⓪𝟭𝟮𝟯𝟰𝟱𝟲𝟳𝟴𝟵𝟬𝟏𝟐𝟑𝟒𝟓𝟔𝟕𝟖𝟗𝟎❶❷❸❹❺❻❼❽❾⓿➀➁➂➃➄➅➆➇➈Ѳ ¹²³⁴⁵⁶⁷⁸⁹⁰ 1ƻ ߁234567890 ₁₂₃₄₅₆₇₈₉₀  
—— １２３４５６７８９０


monospace (Fullwidth)
'!%&()*+,-./:;?[\]_`{|}~#$^=
—— ＇！％＆（）＊＋，－．／：；？［＼］＿｀｛｜｝～＃＄＾＝

(a-z monospace) 𝚊𝚋𝚌𝚍𝚎𝚏𝚐𝚑𝚒𝚓𝚔𝚕𝚖𝚗𝚘𝚙𝚚𝚛𝚜𝚝𝚞𝚟𝚠𝚡𝚢𝚣 𝙰𝙱𝙲𝙳𝙴𝙵𝙶𝙷𝙸𝙹𝙺𝙻𝙼𝙽𝙾𝙿𝚀𝚁𝚂𝚃𝚄𝚅𝚆𝚇𝚈𝚉

```

(some are not printable here, so they are here https://cloud.mail.ru/public/EAa2/kP5s3kabd)

**Comment by pukkandan** [comment]
I think there is some misunderstanding here.
* Are you asking to transform characters like `|` etc (that can't be present in filenames) to similar unicode symbols?
* Or, are you asking to convert unicode characters to their "equivalent" ASCII counterparts when using `--restricted-filenames`?
or something else?

I understood your request as (1), but then the mappings given don't make any sense

**Comment by mlatushko** [comment]
Both options look similar. Yes, you need to replace the characters with those that are uniquely supported in the system. Yes, transform or convert|replace to readable on Windows 7+ equivalents.
Options `--no-restrict-filenames --windows-filenames` do not replace those characters, and this one `--restricted-filenames` is missing.

**Comment by pukkandan** [comment]
Request (1) can be done (Thanks @sheerluck)

```diff
diff --git a/yt_dlp/utils.py b/yt_dlp/utils.py
index d405ed3e3..2c1fd6b97 100644
--- a/yt_dlp/utils.py
+++ b/yt_dlp/utils.py
@@ -647,6 +647,8 @@ def replace_insane(char):
             return ACCENT_CHARS[char]
         elif not restricted and char == '\n':
             return '\0 '
+        elif is_id is NO_DEFAULT and not restricted and char in '"*:<>?|/\\':
+            return {'/': '\u29F8', '\\': '\u29f9'}.get(char, chr(ord(char) + 65248))
         elif char == '?' or ord(char) < 32 or ord(char) == 127:
             return ''
         elif char == '"':
```

For (2), your list is very subjective and I don't want to maintain such a list. However, Unicode already has the concept of "equivalent" characters; and you can tell yt-dlp to replace them using NFKC normalization (We could consider using this as default when `--restrict-filenames` is given)

From https://github.com/yt-dlp/yt-dlp#output-template:

> 7. **Unicode normalization**: The format type `U` can be used for NFC [unicode normalization](https://docs.python.org/3/library/unicodedata.html#unicodedata.normalize). The alternate form flag (`#`) changes the normalization to NFD and the conversion flag `+` can be used for NFKC/NFKD compatibility equivalence normalization. Eg: `%(title)+.100U` is NFKC


If you want more characters to be replaced, use `--replace-in-metadata`

PS: I don't think these options existed when this request was originally made

**Comment by pukkandan** [comment]
For reference, here's [your sample text](https://github.com/yt-dlp/yt-dlp/issues/1330#issuecomment-1039639105) after normalization:
```
¦ǀǁ❙|—_—— |
/ ╱⧸̷ ⁄ —— /
?؟¿❓ —— ‽
: —— :
\╲⧹ —— \
«» ⟪⟫ ≪≫ ❝❞ —— “”
❛❜ —— ‘’
(quotation marks; which are better?) " —— ‚ „ ̔̕ ̏ ̎ ̍ ̒̓ ` ́
✖ —— ×(x)
&⅋ —— &
💲 —— $
❗¡ —— !
< —— ‹
> —— ›
* —— *
⁏ —— ;
➕ +
ё|е ̈ —— ё
й —— й
i —— i
(delete symbols)[​  ‏‎]
∽ —— ~(~)
... —— ...
(emphasis)[̀◌́][′׳ ̓ˈꞌ] —— [` ́](which is better?)
(other symbols may be replaced|filled by the marks)··♥♦♣♠
[⠀  ] —— [ ]
() —— ()
123456789012345678901234567890❶❷❸❹❺❻❼❽❾⓿➀➁➂➃➄➅➆➇➈Ѳ 1234567890 1ƻ ߁234567890 1234567890
—— 1234567890


monospace (Fullwidth)
'!%&()*+,-./:;?[\]_`{|}~#$^=
—— '!%&()*+,-./:;?[\]_`{|}~#$^=

(a-z monospace) abcdefghijklmnopqrstuvwxyz ABCDEFGHIJKLMNOPQRSTUVWXYZ
```

So these characters were replaced:

```
 ¨²³´¹̆·и᾿ … ⁰⁴⁵⁶⁷⁸⁹⁽⁾₀₁₂₃₄₅₆₇₈₉①②③④⑤⑥⑦⑧⑨⓪　︱︳！＃＄％＆＇（）＊＋，－．／０１２３４５６７８９：；＝？［＼］＾＿｀ｉ｛｜｝～𝙰𝙱𝙲𝙳𝙴𝙵𝙶𝙷𝙸𝙹𝙺𝙻𝙼𝙽𝙾𝙿𝚀𝚁𝚂𝚃𝚄𝚅𝚆𝚇𝚈𝚉𝚊𝚋𝚌𝚍𝚎𝚏𝚐𝚑𝚒𝚓𝚔𝚕�
𝚗𝚘𝚙𝚚𝚛𝚜𝚝𝚞𝚟𝚠𝚡𝚢𝚣𝟎𝟏𝟐𝟑𝟒𝟓𝟔𝟕𝟖𝟗𝟬𝟭𝟮𝟯𝟰𝟱𝟲𝟳𝟴𝟵�
```

by:

```
  ̈23 ́1̆·и ̓ ... 0456789()01234567891234567890 —_!#$%&'()*+,-./0123456789:;=?[\]^_`i{|}~ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz01234567890123456789
```

while these (+ASCII) are left as-is:

```
¡¦«·»¿×ƻǀǁˈ̷̀́̆̈̍̎̏̒̓̔̕еиѲ׳؟߁​‎‏—‘’‚“”„′‹›‽⁄⁏⅋∽≪≫⓿╱╲◌♠♣♥♦✖❓❗❙❛❜❝❞❶❷❸❹❺❻❼❽❾➀➁➂➃➄➅➆➇➈➕⟪⟫⠀⧸⧹ꞌ💲
```

**Comment by mlatushko** [comment]
Would like more. 
```
︱︳｜
／
：
＼
[̔̕] [̕ U+0315] [̔ U+0314]
[´]
[᾿]
＆
ё|(е¨)
й
ｉ
～
…
[　 ]
⁽⁾
```

```
—_|
/
:
\
[̔̕] (swapped U+0315 U+0314 → U+0314 U+0315)
[́]
[ ̓]
&
ё|(е ̈) (= ё = ё)
й
i
~
...
[  ]
()
```

`| / : \` - These characters are not accepted in Windows 7

**Comment by pukkandan** [comment]
Did you not read my above comment?

> your list is very subjective and I don't want to maintain such a list.
