### ISSUE TITLE
MacOS: SSL Error

### ISSUE THREAD

**Issue by VVfearless** [yt-dlp/yt-dlp#1338]
##Question
yt-dlp not worked on macOS. Did I miss something to download or install?

##Description
I typed:
yt-dlp https://www.youtube.com/watch?v=A7mSohcW3pw

and the Errors are as follows:
ERROR: [youtube] A7mSohcW3pw: Unable to download API page: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)> (caused by URLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),))

I also tried to add the double quote：
yt-dlp “https://www.youtube.com/watch?v=A7mSohcW3pw”
and the error is the same.

## Checklist

- [ ] I'm asking a question
- [ ] I've looked through the README
- [ ] I've read the opening an issue section in CONTRIBUTING.md
- [ ] I've searched the bugtracker for similar questions including closed ones
- [ ] I have given an appropriate title to the issue

## Question
yt-dlp not worked on macOS. Did I miss something to download or install?

**Comment by coletdjnz** [comment]
Issue with your system/python install. Can either run with `--no-check-certificate` or look at fixing it. 

https://stackoverflow.com/questions/42098126/mac-osx-python-ssl-sslerror-ssl-certificate-verify-failed-certificate-verify
