### ISSUE TITLE
[Question] Wingfox.com and their videocourses

### ISSUE THREAD

**Issue by Deretsiger** [yt-dlp/yt-dlp#1347]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README
- [x] I've read the opening an issue section in CONTRIBUTING.md
- [x] I've searched the bugtracker for similar questions including closed ones
- [x] I have given an appropriate title to the issue

## Question

Trying to download some videos from here https://www.wingfox.com/p/8457 i'm able to get the trailer since it has an .m3u8 file, but the next 2 files "Introduction" and "Observation" (which are available with a free account) have a .pdx file 
https://hls.videocc.net/9215d65496/8/9215d65496f634ce61945164eeba7328_1.pdx 
brief search says it's chinese videohosting alternative to .m3u8
https://polyvofficial.wordpress.com/2017/01/07/concise-tutorial-encrypting-and-transcoding-settings-for-source-files/

Is there a way to download those videos or am i out of options?

**Comment by pukkandan** [comment]
We don't currently have any support for this format
