### ISSUE TITLE
[Site Request] gloria.tv

### ISSUE THREAD

**Issue by smnthermes** [yt-dlp/yt-dlp#135]
## Checklist

- [x] I'm reporting a new site support request
- [x] I've verified that I'm running yt-dlp version **2021.03.03.2**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that none of provided URLs violate any copyrights
- [x] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

- Single video: https://gloria.tv/post/3TLtwh4xvPJACPxsfouFNkGAi
- Playlist: https://gloria.tv/post/e4uqjnXkpkcg4ojRHyf68V1Y3
- Channel: https://gloria.tv/condeloppeux

## Description

Individual videos work with the generic extractor, but not playlists or channels.

**Comment by pukkandan** [comment]
A large portion of videos on this website are copyright infringement. I don't want to get in any legal trouble and so this site will not be supported

See:
https://transparencyreport.google.com/copyright/domains/gloria.tv
https://github.com/ytdl-org/youtube-dl/issues/10885#issuecomment-252471046

**Comment by smnthermes** [comment]
That report doesn't show anything about the host's policy concerning copyright claims. Terms of service: https://gloria.tv/termsofservice/

**Comment by shirt-dev** [comment]
Our stance is not changing on this at this time.
