### ISSUE TITLE
[Question] How can I forcefully use video title and channel name as metadata instead of YouTube's "song" metadata

### ISSUE THREAD

**Issue by gwenz1111010** [yt-dlp/yt-dlp#1350]
## Checklist

- [X] I'm asking a question
- [X] I've looked through the README
- [X] I've read the opening an issue section in CONTRIBUTING.md
- [X] I've searched the bugtracker for similar questions including closed ones
- [X] I have given an appropriate title to the issue

## Question

I'm using `-x --add-metadata`. If a video on YouTube doesn't have "song" metadata (information that appears below the description), the title of the video and the channel name will be used as track title and artist respectively. However, when the video DOES have this information, it'll be used instead.

This usually isn't a problem, but this information can sometimes be incorrect. For example, when it's a cover of a song instead of the original song, YouTube or the creator may put the information about the original in these fields instead of the content of the actual video, and the artist will be the one who performed the original instead of the cover (which is the one that's being downloaded).

So what I want is the option to override this behavior and ALWAYS use the video title and channel name. Is this possible? I searched the man page but couldn't find anything.

Thanks

**Comment by pukkandan** [comment]
`--parse-metadata "title:%(track)s"` replaces `track` with `title`. You can create similar commands for each field you need to modify. See https://github.com/yt-dlp/yt-dlp#modifying-metadata
