### ISSUE TITLE
[Broken] Website Name: A short description of the issue

### ISSUE THREAD

**Issue by stgzach** [yt-dlp/yt-dlp#1356]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running yt-dlp version **2021.10.10**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones
- [x] I've read the opening an issue section in CONTRIBUTING.md
- [x] I have given an appropriate title to the issue

## Verbose log

```
[debug] Command-line config: ['-v']
[debug] Encodings: locale cp1252, fs utf-8, out cp1252, pref cp1252
[debug] yt-dlp version 2021.10.10
[debug] Python version 3.10.0 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] exe versions: ffmpeg 4.4-full_build-www.gyan.dev, ffprobe 4.4-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] ANSI escape support: stdout = False, stderr = True
[debug] Proxy map: {}

```

## Description

The full TikTok account download does not work anymore since the yt-dlp update.

**Comment by nyuszika7h** [comment]
> [x] I have given an appropriate title to the issue

Don't just blindly tick checkboxes.
