### ISSUE TITLE
[Site Request] streamff.com - simple video sharing website

### ISSUE THREAD

**Issue by soystemd** [yt-dlp/yt-dlp#1359]
## Checklist

- [x] I'm reporting a new site support request
- [x] I've verified that I'm running yt-dlp version **2021.10.10**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that none of provided URLs violate any copyrights
- [x] The provided URLs do not contain any DRM to the best of my knowledge
- [x] I've searched the bugtracker for similar site support requests including closed ones
- [x] I've read the opening an issue section in CONTRIBUTING.md
- [x] I have given an appropriate title to the issue

## Example URLs

- Single video: https://streamff.com/v/55cc94

## Description

streamff.com is for uploading and sharing single videos, much like streamwo.com or streamja.com, which are supported by youtube-dl and yt-dlp.

**Comment by coletdjnz** [comment]
for devs:
A GET request is sent to `https://streamff.com/api/videos/<video ID>` which responds with a JSON dict containing the video link and some other basic metadata.

Should be a very simple extractor to implement.

**Comment by cntrl-s** [comment]
@coletdjnz can you assign this issue to me

**Comment by pukkandan** [comment]
@cntrl-s You don't need to ask for permission to start working on issues :D

**Comment by cntrl-s** [comment]
@pukkandan i am asking so that someone else doesn't pick the same issue

**Comment by Ashish0804** [comment]
@cntrl-s are you still working on this?

**Comment by cntrl-s** [comment]
@Ashish0804  yes

**Comment by cntrl-s** [comment]
@pukkandan i have created a PR https://github.com/yt-dlp/yt-dlp/pull/1736
