### ISSUE TITLE
[Feature Request] add zspotify as spotify downloader!

### ISSUE THREAD

**Issue by erickyun** [yt-dlp/yt-dlp#1368]
## Checklist

-  [x] I'm reporting a feature request
- [x] I've verified that I'm running yt-dlp version **2021.10.10**
- [x] I've searched the bugtracker for similar feature requests including closed ones
- [x] I've read the opening an issue section in CONTRIBUTING.md
- [x] I have given an appropriate title to the issue

## Description

Hi,

I did found this [Spotify Downloader](https://github.com/Footsiefat/zspotify) can this be added to yt-dlp for spotify downloader?

**Comment by pukkandan** [comment]
> But for spotify ytdlp does use youtube or other sites to get songs right?

No. We dont support spotify songs because of DRM

**Comment by erickyun** [comment]
> > But for spotify ytdlp does use youtube or other sites to get songs right?
> 
> No. We dont support spotify songs because of DRM

ok I understand thank you for your answer.

**Comment by Leseratte10** [comment]
Spotify songs have DRM? In the linked application (the Spotify downloader) I see absolutely no code regarding DRM removal, or any Widevine or FairPlay code / circumvention. It all just seems to be obfuscated, like it is for YouTube. 

If stuff like this is considered DRM, then YouTube's n-sig algorithm (#1437) should be considered a DRM as well, right? What's the difference? Or am I missing something?
If a plain, simple Python script like the one linked in this issue can download Spotify songs, there can't really be DRM - or am I misunderstanding how DRM works or what yt-dlp's rules regarding DRM are?

**Comment by pukkandan** [comment]
Spotify songs do have proper DRM - atleast the publicly accessible formats do. I did not look at the source code of the linked app, so I have no idea what they are doing

**Comment by Footsiefat** [comment]
@pukkandan author of zspotify here. Only the webclient has drm(widevine), the desktop client on the other hand has no drm so it can be emulated to pull songs from spotify.
