### ISSUE TITLE
Mediaset Playlist Extractor

### ISSUE THREAD

**Issue by stefanodvx** [yt-dlp/yt-dlp#1372]
### Checklist

- [X] I'm reporting a site feature request
- [X] I've verified that I'm running yt-dlp version **2021.10.10**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Italy

### Description

Is it possible to add playlist extractor for Mediaset? Here's an example URL: https://www.mediasetplay.mediaset.it/fiction/fireforce_SE000000001556

**Comment by pukkandan** [comment]
@nixxo may be interested
