### ISSUE TITLE
[youku] Download 1080p with VIP account

### ISSUE THREAD

**Issue by snowywish** [yt-dlp/yt-dlp#1376]
### Checklist

- [X] I'm reporting a site feature request
- [X] I've verified that I'm running yt-dlp version **2021.10.10**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

china

### Description

Hi,
I can't download youku videos in 1080p? pls someone help out

**Comment by elyse0** [comment]
@snowywish I'm updating the Youku extractor, this is my branch https://github.com/elyse0/yt-dlp/tree/youku

If you still have a vip account, I could look into adding 1080p formats n-n  This is my email: elyse0@proton.me

**Comment by karma-sun** [comment]
> Update:
> 
> The OP didn't answer, if someone else is interested in continuing with this, here is my branch https://github.com/elyse0/yt-dlp/tree/youku . The main challenge for using the web api (and getting at least 720p formats) is generating Ckeys, but for that we'll need access to the dom of the page.

have test your branch,but it get 720p only,not 1080p?

**Comment by elyse0** [comment]
1080p is vip only and I didn't have an account to test. Probably it's related to the ckey, right now it's using a "guest" code.
