### ISSUE TITLE
Postprocessing error when embeding metadata after already embedding thumbnail

### ISSUE THREAD

**Issue by Rexadev** [yt-dlp/yt-dlp#1378]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2021.10.10**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

**Also See - https://www.reddit.com/r/youtubedl/comments/qbae5l/comment/hhe0hg1/**

### Verbose log

```
[opus @ 0000014cc384c180] Unsupported codec id in stream 1
Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument
Error initializing output stream 0:1 --
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)


ERROR: Postprocessing:   Stream #0:1 -> #0:1 (copy)
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 3236, in process_info
  File "yt_dlp\YoutubeDL.py", line 3406, in post_process
  File "yt_dlp\YoutubeDL.py", line 3388, in run_all_pps
  File "yt_dlp\YoutubeDL.py", line 3367, in run_pp
  File "yt_dlp\postprocessor\common.py", line 25, in run
  File "yt_dlp\postprocessor\common.py", line 126, in wrapper
  File "yt_dlp\postprocessor\ffmpeg.py", line 692, in run
  File "yt_dlp\postprocessor\ffmpeg.py", line 313, in run_ffmpeg_multiple_files
  File "yt_dlp\postprocessor\ffmpeg.py", line 351, in real_run_ffmpeg
yt_dlp.postprocessor.ffmpeg.FFmpegPostProcessorError:   Stream #0:1 -> #0:1 (copy)
```

**Comment by Rexadev** [comment]
@pukkandan I think it is fixed

**Comment by pukkandan** [comment]
Well, we didn't change anything. Though, if you are no longer affected, feel free to close the issue

**Comment by Rexadev** [comment]
No problem still exists

**Comment by bashonly** [comment]
Closing in favor of #11487
