### ISSUE TITLE
YouTube Music Premium-only videos won't download

### ISSUE THREAD

**Issue by gergles** [yt-dlp/yt-dlp#1383]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2021.10.10**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United States

### Description

YouTube Music has some videos that are available to Music Premium members only. Example: https://www.youtube.com/watch?v=NSYzJsrt2NI

yt-dlp cannot download these videos and instead passes on the "This video is only available to Music Premium members" message from YouTube, even if you supply cookies from a user who's logged in with premium.

### Verbose log

```shell
[debug] Command-line config: ['-Uv', '-x', '--cookies', 'ytc.txt', 'https://youtube.com/watch?v=NSYzJsrt2NI']
[debug] User config file: /home/ME/.config/yt-dlp/config
[debug] User config: ['--sponsorblock-remove', 'sponsor', '--sponsorblock-mark', 'all', '--no-check-certificate', '--no-mtime']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] yt-dlp version 2021.10.10
[debug] Python version 3.8.10 (CPython 64bit) - Linux-5.4.0-89-generic-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4, rtmpdump 2.4
[debug] Optional libraries: Cryptodome, keyring, mutagen, sqlite, websockets
[debug] ANSI escape support: stdout = True, stderr = True
[debug] Proxy map: {}
yt-dlp is up to date (2021.10.10)
[debug] [youtube] Extracting URL: https://youtube.com/watch?v=NSYzJsrt2NI
[youtube] NSYzJsrt2NI: Downloading webpage
[debug] [youtube] Extracted SAPISID cookie
[youtube] NSYzJsrt2NI: Downloading android player API JSON
ERROR: [youtube] NSYzJsrt2NI: This video is only available to Music Premium members
Traceback (most recent call last):
  File "/home/ME/.local/lib/python3.8/site-packages/yt_dlp/extractor/common.py", line 589, in extract
    ie_result = self._real_extract(url)
  File "/home/ME/.local/lib/python3.8/site-packages/yt_dlp/extractor/youtube.py", line 2853, in _real_extract
    self.raise_no_formats(reason, expected=True)
  File "/home/ME/.local/lib/python3.8/site-packages/yt_dlp/extractor/common.py", line 1085, in raise_no_formats
    raise ExtractorError(msg, expected=expected, video_id=video_id)
yt_dlp.utils.ExtractorError: This video is only available to Music Premium members
Traceback (most recent call last):
  File "/home/ME/.local/lib/python3.8/site-packages/yt_dlp/extractor/common.py", line 589, in extract
    ie_result = self._real_extract(url)
  File "/home/ME/.local/lib/python3.8/site-packages/yt_dlp/extractor/youtube.py", line 2853, in _real_extract
    self.raise_no_formats(reason, expected=True)
  File "/home/ME/.local/lib/python3.8/site-packages/yt_dlp/extractor/common.py", line 1085, in raise_no_formats
    raise ExtractorError(msg, expected=expected, video_id=video_id)
yt_dlp.utils.ExtractorError: This video is only available to Music Premium members

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ME/.local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 1263, in wrapper
    return func(self, *args, **kwargs)
  File "/home/ME/.local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 1288, in __extract_info
    ie_result = ie.extract(url)
  File "/home/ME/.local/lib/python3.8/site-packages/yt_dlp/extractor/common.py", line 605, in extract
    raise ExtractorError(
yt_dlp.utils.ExtractorError: [youtube] NSYzJsrt2NI: This video is only available to Music Premium members
```

**Comment by lapc506** [comment]
Hello @pukkandan and @gergles , I'd like to suggest re-opening this issue.

I'm coming from issues #7271 and #10927:
Testing with this video:

- I had to export the cookies from my MS Edge to a separate file.
- Made sure that the cookies were being detected using -vU
- I have my yt-dlp.exe binary located in `C:\Program Files\ffmpeg\bin\` mapped to PATH.
- Tried using **music**.youtube.com as suggested by @coletdjnz 
- I can play the video on my Chrome and MS Edge browser using my YouTube Premium subscription
- Using a binary version even higher than the one described on the issue statement:
  - `stable@2025.07.21 from yt-dlp/yt-dlp [9951fdd0d] (win_exe)`

Testing with this command:
`yt-dlp --cookies "C:\Program Files\ffmpeg\bin\edge_cookies.txt" -F https://music.youtube.com/watch?v=G4spBKeErkE -vU`

**Output:**
```
[debug] Command-line config: ['--cookies', 'C:\\Program Files\\ffmpeg\\bin\\edge_cookies.txt', '-F', 'https://music.youtube.com/watch?v=G4spBKeErkE', '-vU']
[debug] Portable config "C:\Program Files\ffmpeg\bin\yt-dlp.conf": []
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8 
[debug] yt-dlp version stable@2025.07.21 from yt-dlp/yt-dlp [9951fdd0d] (win_exe) 
[debug] Python 3.10.11 (CPython AMD64 64bit) - Windows-10-10.0.26120-SP0 (OpenSSL 1.1.1t  7 Feb 2023) 
[debug] exe versions: ffmpeg 2024-01-07-git-90bef6390f-full_build-www.gyan.dev (setts), ffprobe 2024-01-07-git-90bef6390f-full_build-www.gyan.dev 
[debug] Optional libraries: Cryptodome-3.23.0, brotli-1.1.0, certifi-2025.07.14, curl_cffi-0.10.0, mutagen-1.47.0, requests-2.32.4, sqlite3-3.40.1, urllib3-2.5.0, websockets-15.0.1 
[debug] Proxy map: {} 
[debug] Request Handlers: urllib, requests, websockets, curl_cffi 
[debug] Plugin directories: none 
[debug] Loaded 1857 extractors 
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest 
Latest version: stable@2025.07.21 from yt-dlp/yt-dlp 
yt-dlp is up to date (stable@2025.07.21 from yt-dlp/yt-dlp) 
[debug] [youtube] [pot] PO Token Providers: none 
[debug] [youtube] [pot] PO Token Cache Providers: memory 
[debug] [youtube] [pot] PO Token Cache Spec Providers: webpo 
[youtube] Extracting URL: https://music.youtube.com/watch?v=G4spBKeErkE 
[youtube] G4spBKeErkE: Downloading webpage 
[youtube] G4spBKeErkE: Downloading tv client config 
[debug] Loading youtube-sts.0b00c3eb-main from cache 
[youtube] G4spBKeErkE: Downloading tv player API JSON 
[debug] [youtube] G4spBKeErkE: tv player response playability status: UNPLAYABLE 
[youtube] G4spBKeErkE: Downloading ios player API JSON 
[debug] [youtube] G4spBKeErkE: ios player response playability status: UNPLAYABLE 
[debug] [youtube] G4spBKeErkE: web player response playability status: UNPLAYABLE 
ERROR: [youtube] G4spBKeErkE: This video is only available to Music Premium members 
  File "yt_dlp\extractor\common.py", line 761, in extract 
  File "yt_dlp\extractor\youtube\_video.py", line 3930, in _real_extract 
  File "yt_dlp\extractor\common.py", line 1273, in raise_no_formats 
```

**Comment by coletdjnz** [comment]
> Hello @pukkandan and @gergles , I'd like to suggest re-opening this issue.
> 
> I'm coming from issues #7271 and #10927:
> Testing with this video:
> 
> - I had to export the cookies from my MS Edge to a separate file.
> - Made sure that the cookies were being detected using -vU
> - I have my yt-dlp.exe binary located in `C:\Program Files\ffmpeg\bin\` mapped to PATH.
> - Tried using **music**.youtube.com as suggested by @coletdjnz 
> - I can play the video on my Chrome and MS Edge browser using my YouTube Premium subscription
> - Using a binary version even higher than the one described on the issue statement:
>   - `stable@2025.07.21 from yt-dlp/yt-dlp [9951fdd0d] (win_exe)`
> 
> Testing with this command:
> `yt-dlp --cookies "C:\Program Files\ffmpeg\bin\edge_cookies.txt" -F https://music.youtube.com/watch?v=G4spBKeErkE -vU`
> 
> **Output:**
> ```
> [debug] Command-line config: ['--cookies', 'C:\\Program Files\\ffmpeg\\bin\\edge_cookies.txt', '-F', 'https://music.youtube.com/watch?v=G4spBKeErkE', '-vU']
> [debug] Portable config "C:\Program Files\ffmpeg\bin\yt-dlp.conf": []
> [debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8 
> [debug] yt-dlp version stable@2025.07.21 from yt-dlp/yt-dlp [9951fdd0d] (win_exe) 
> [debug] Python 3.10.11 (CPython AMD64 64bit) - Windows-10-10.0.26120-SP0 (OpenSSL 1.1.1t  7 Feb 2023) 
> [debug] exe versions: ffmpeg 2024-01-07-git-90bef6390f-full_build-www.gyan.dev (setts), ffprobe 2024-01-07-git-90bef6390f-full_build-www.gyan.dev 
> [debug] Optional libraries: Cryptodome-3.23.0, brotli-1.1.0, certifi-2025.07.14, curl_cffi-0.10.0, mutagen-1.47.0, requests-2.32.4, sqlite3-3.40.1, urllib3-2.5.0, websockets-15.0.1 
> [debug] Proxy map: {} 
> [debug] Request Handlers: urllib, requests, websockets, curl_cffi 
> [debug] Plugin directories: none 
> [debug] Loaded 1857 extractors 
> [debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest 
> Latest version: stable@2025.07.21 from yt-dlp/yt-dlp 
> yt-dlp is up to date (stable@2025.07.21 from yt-dlp/yt-dlp) 
> [debug] [youtube] [pot] PO Token Providers: none 
> [debug] [youtube] [pot] PO Token Cache Providers: memory 
> [debug] [youtube] [pot] PO Token Cache Spec Providers: webpo 
> [youtube] Extracting URL: https://music.youtube.com/watch?v=G4spBKeErkE 
> [youtube] G4spBKeErkE: Downloading webpage 
> [youtube] G4spBKeErkE: Downloading tv client config 
> [debug] Loading youtube-sts.0b00c3eb-main from cache 
> [youtube] G4spBKeErkE: Downloading tv player API JSON 
> [debug] [youtube] G4spBKeErkE: tv player response playability status: UNPLAYABLE 
> [youtube] G4spBKeErkE: Downloading ios player API JSON 
> [debug] [youtube] G4spBKeErkE: ios player response playability status: UNPLAYABLE 
> [debug] [youtube] G4spBKeErkE: web player response playability status: UNPLAYABLE 
> ERROR: [youtube] G4spBKeErkE: This video is only available to Music Premium members 
>   File "yt_dlp\extractor\common.py", line 761, in extract 
>   File "yt_dlp\extractor\youtube\_video.py", line 3930, in _real_extract 
>   File "yt_dlp\extractor\common.py", line 1273, in raise_no_formats 
> ```

Your cookies are bad. If they were valid it should log a line along the lines of "Detected YouTube account cookies"

Try exporting them again, following the guide here: https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies

**Comment by karanking207** [comment]
is there a code to download members only video of Any channel? 
@coletdjnz

**Comment by bashonly** [comment]
@karanking207 No. Do not reply to an issue with an unrelated comment and do not ping a maintainer apropos of nothing. You will be blocked if you do it again.
