### ISSUE TITLE
[SponsorBlock] New Category - poi_highlight

### ISSUE THREAD

**Issue by ObsessedHacker** [yt-dlp/yt-dlp#1392]
### Checklist

- [X] I'm reporting a feature request
- [X] I've verified that I'm running yt-dlp version **2021.10.22**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

https://github.com/ajayyy/SponsorBlock/wiki/Types#category

Video with the new category:
https://www.youtube.com/watch?v=zF2KF-SVIXc

Can yt-dlp add support for SponsorBlock poi_highlight?

**Comment by pukkandan** [comment]
This has already been implemented. I forgot to close the issue
