### ISSUE TITLE
Reduce RAM usage when crawling large playlist

### ISSUE THREAD

**Issue by barkoder** [yt-dlp/yt-dlp#1399]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2021.10.22**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Description

`yt-dlp.exe` and `yt-dlp_min.exe` version `2021.10.22`

If I only download the thumbnails from a 834 video playlist using

    yt-dlp_min.exe -wv --no-cache-dir --geo-bypass -o "%(uploader)s-%(upload_date)s-%(title)s-%(id)s.%(ext)s" --restrict-filenames --write-thumbnail 'https://www.youtube.com/playlist?list=PLnQX-jgAF5pTkwtUuVpqS5tuWmJ-6ZM-Z' --skip-download

then by the end of it, `tasklist` shows `yt-dlp_min.exe` using `1,056,568 K` of RAM

I also tried just getting the videoid using

    yt-dlp.exe -w --no-cache-dir --geo-bypass --get-id 'https://www.youtube.com/playlist?list=PLnQX-jgAF5pTkwtUuVpqS5tuWmJ-6ZM-Z' >> 3Blue1Brown_Curated_Math_Videos_Explainer_Playlist_VIDEOIDS.txt

and by the end of that, `tasklist` shows `yt-dlp.exe` using `1,123,872 K` of RAM.  
~67MB higher than `yt-dlp_min.exe`.

I think that's way too much RAM usage.  
And it would have kept rising too, had there been more videos in the playlist.

### Verbose log

```shell
I'm not posting the entire really long verbose log because I don't think it's required here.

[debug] Command-line config: ['-wv', '--no-cache-dir', '--geo-bypass', '-o', '%(uploader)s-%(upload_date)s-%(title)s-%(id)s.%(ext)s', '--restrict-filenames', '--write-thumbnail', 'https://www.youtube.com/playlist?list=PLnQX-jgAF5pTkwtUuVpqS5tuWmJ-6ZM-Z', '--skip-download']
[debug] Encodings: locale cp1252, fs utf-8, out cp1252 (No ANSI), err cp1252 (No ANSI), pref cp1252[debug] yt-dlp version 2021.10.22 (py2exe)
```

**Comment by pukkandan** [comment]
@barkoder Regarding #2084,

The thing with workarounds (as opposed to fixes) is that you should expect them to break. Since https://github.com/yt-dlp/yt-dlp/commit/093a17107ea5e375ba606ed1c31d1c259f93e0df#diff-d3ba8be45cae8dd7889a71c3360c9e4ac1160de8a5f3443b6e4a656395267f9bR2364-R2365, any changes made by pre-processors is accounted in the format selection (may not be usefull for CLI, but is usefull so for API). So if you set the formats to ` `, it ofc breaks.

It can currently be worked around with `--parse-metadata ":(P<formats>)" --parse-metadata ":(?P<automatic_captions>)" --ignore-no-formats`. But again, this is a workaround and not a fix. I can't promise that this will keep working in the future

Any further discussion abot this should happen here - not as new issues

**Comment by barkoder** [comment]
> It can currently be worked around with `--parse-metadata ":(P<formats>)" --parse-metadata ":(?P<automatic_captions>)" --ignore-no-formats`. But again, this is a workaround and not a fix. I can't promise that this will keep working in the future

I was getting a warning `WARNING: Could not interpret '' as '(P<formats>)'`

I think there should be a a `?` before `P<formats>)"` as there is one before `<automatic_captions>)` ?

That seems to fix it.

But then the warnings change to `WARNING: Requested format is not available`

Yes I know "It's a workaround. Not a Fix."

But it works. So Thank you @pukkandan .

> Any further discussion abot this should happen here - not as new issues

Sorry. Will do.

**Comment by barkoder** [comment]
[Would this help?](https://github.com/bloomberg/memray)

[Related HN discussion](https://news.ycombinator.com/item?id=31102089).

[Twitter thread with an overview of it.](https://nitter.net/1st1/status/1516859294896906241)

**Comment by pukkandan** [comment]
When used through CLI, yt-dlp will now try to be smart about whether to keep the playlist entries in memory. Situations when this is needed are:
1. `--dump-single-json`
2. `--write-info-json --no-clean-info-json`
3. `--concat-playlist always`
4. `--print`/`--print-to-file` with `playlist:`

As long as none of these options are in effect, the memory usage will not increase with the playlist size

When used though API, the user has to pass `'extract_flat': 'discard'` to make use of this improvement
