### ISSUE TITLE
[Question] How to rename yt-dlp to a preferred name?

### ISSUE THREAD

**Issue by fosam** [yt-dlp/yt-dlp#140]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

I want to switch from `youtube-dlc` to `yt-dlp` but i have many scripts that i have to modify to make them work with `yt-dlp`

It would be less work if i have to make a slight modification such as using `youtube-dlp` instead of `yt-dlp`

How can i modify this fork to make it work using `youtube-dlp` instead of `yt-dlp` ?

**Comment by pukkandan** [comment]
if you are using the release binary, just rename the file (even to youtube-dlc if you want). Everything will keep working.
If you are using PIP, there is no easy way

**Comment by fosam** [comment]
Yes, this is correct, i was doing exactly this when i was alternating between `youtube-dl` and `youtube-dlc` i have just forgot

I must have been thinking of some other modification when i asked this question. 🤪

I always use release binary (recommended method)

I will therefore close this question.
