### ISSUE TITLE
ORF TvThek strongly geoblocked

### ISSUE THREAD

**Issue by avagraha** [yt-dlp/yt-dlp#1411]
### Checklist

- [X] I'm reporting a site feature request
- [X] I've verified that I'm running yt-dlp version **2021.10.22**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Austria

### Example URLs

https://tvthek.orf.at/profile/Archiv/7648449/Neues-beim-Wiener-Sommernachtskonzert/13919349/Neues-beim-Wiener-Sommernachtskonzert/13995118

### Description

Hi, I'd like to watch/download this kind of video 
https://tvthek.orf.at/profile/Archiv/7648449/Neues-beim-Wiener-Sommernachtskonzert/13919349/Neues-beim-Wiener-Sommernachtskonzert/13995118

but I can download the warning video only ("Dieses Video darf
aus....werden")!

I tried:

1) --geo-bypass-country AT : failed

2) austrian IP Nummer 84.113.84.83 : failed

3) -v --proxy 109.70.100.8:443  : failed

4) webproxy.at : failed

5) TOR : unable to install due to my OS
6 curl failed
7 xidel failed

thanks for suggestions, what to do?

I just discovered you today. It seems a very good project, congratulations.
PS: Where could I read a complete list of all supported websites? thanks.
Finally the log.

C:\Users\ciao>yt -v --geo-bypass-country AT https://tvthek.orf.at/profile/
Archiv/7648449/Neues-beim-Wiener-Sommernachtskonzert/13919349/Neues-beim-Wi
ener-Sommernachtskonzert/13995118
[debug] Command-line config: ['-v', '--geo-bypass-country', 'AT', 'https://
tvthek.orf.at/profile/Archiv/7648449/Neues-beim-Wiener-Sommernachtskonzert/
13919349/Neues-beim-Wiener-Sommernachtskonzert/13995118']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8 (No ANSI), err utf-8
(No ANSI), pref cp1252[debug] yt-dlp version 2021.10.22 (win_exe)
[debug] Python version 3.7.9 (CPython 32bit) - Windows-Vista-6.0.6002-SP2
[debug] exe versions: ffmpeg N-94698-g83e0b71-Reino, ffprobe N-94698-g83e0b
71-Reino, rtmpdump 2.4
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] Using fake IP 77.119.0.175 (AT) as X-Forwarded-For
[debug] [orf:tvthek] Extracting URL: https://tvthek.orf.at/profile/Archiv/7
648449/Neues-beim-Wiener-Sommernachtskonzert/13919349/Neues-beim-Wiener-Som
mernachtskonzert/13995118
[orf:tvthek] 13995118: Downloading webpage
[orf:tvthek] 13995118: Downloading m3u8 information
ERROR: [orf:tvthek] 13995118: This video is not available from your locatio
n due to geo restriction
Traceback (most recent call last):
  File "yt_dlp\extractor\common.py", line 593, in extract
  File "yt_dlp\extractor\orf.py", line 96, in _real_extract
  File "yt_dlp\extractor\common.py", line 1081, in raise_geo_restricted
yt_dlp.utils.GeoRestrictedError: This video is not available from your loca
tion due to geo restriction
Traceback (most recent call last):
  File "yt_dlp\extractor\common.py", line 593, in extract
  File "yt_dlp\extractor\orf.py", line 96, in _real_extract
  File "yt_dlp\extractor\common.py", line 1081, in raise_geo_restricted
yt_dlp.utils.GeoRestrictedError: This video is not available from your loca
tion due to geo restriction

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1280, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1305, in __extract_info
  File "yt_dlp\extractor\common.py", line 610, in extract
yt_dlp.utils.ExtractorError: [orf:tvthek] 13995118: This video is not avail
able from your location due to geo restriction
C:\Users\ciao>

**Comment by anunasica** [comment]
what could be a working IP for these ORF videos?
