### ISSUE TITLE
Short-form vs long-form segment download status output

### ISSUE THREAD

**Issue by boulderob** [yt-dlp/yt-dlp#1417]
### Checklist

- [X] I'm asking a question and not reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

Sometimes when I download videos,`yt-dlp` / `youtube-dl` "suppresses" the download output so that it constantly updates the output percentage vs outputting and scrolling each downloaded segment to shell stdout.  Other times it does the opposite scrolling each downloaded serialized segment to screen.  I prefer the first output style as it doesn't clutter up my shell output for "eyeballing" successive runs of the command.

To my knowledge, I "think" that the "surpressed" output style seems to happen when I download mp4 containers that contain *both* the audio and video file and the "long-winded verbose segemented" output occurs when i have to specify specific video and audio files that need to be muxed after the fact or mpd/dash streams but that's just a guess.

Since hls / m3u8 and dash / mpd are both segmented streams I can't see one or the other as making a difference to the output though.  

- Is there some reason why the output changes to short-form supressed and or long-form scrolled segment output depending on the way I evoke the command, specify the `format_id` or choose container or separate audio and video files or segment types?  
- Is there a way to change the behavior with a command line option?  (`-q` disables all output and I don't want that)

Thanks if you have the time.

Here's an example of a video that is short-form supressed

```bash
yt-dlp -Uv -f "best[ext=mp4][width<=480]" --write-sub https://www.ardmediathek.de/video/donna-leon/donna-leon-schoener-schein/das-erste/Y3JpZDovL2Rhc2Vyc3RlLmRlL2Rvbm5hIGxlb24vMGNkMjFiMDktZjE2MS00ZDg3LWI4OTEtNGMzYTkxOTk4ZDQw/
[debug] Command-line config: ['-Uv', '-f', 'best[ext=mp4][width<=480]', '--write-sub', 'https://www.ardmediathek.de/video/donna-leon/donna-leon-schoener-schein/das-erste/Y3JpZDovL2Rhc2Vyc3RlLmRlL2Rvbm5hIGxlb24vMGNkMjFiMDktZjE2MS00ZDg3LWI4OTEtNGMzYTkxOTk4ZDQw/']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2021.10.22 (source)
[debug] Lazy loading extractors is disabled
[debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
[debug] Git HEAD: fccf50211
[debug] Python version 3.9.6 (CPython 64bit) - macOS-11.2.3-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.4, ffprobe 4.4, rtmpdump 2.4
[debug] Optional libraries: sqlite
[debug] Proxy map: {}
yt-dlp is up to date (2021.10.22)
[debug] Using fake IP 53.9.0.181 (DE) as X-Forwarded-For
[debug] [ARD:mediathek] Extracting URL: https://www.ardmediathek.de/video/donna-leon/donna-leon-schoener-schein/das-erste/Y3JpZDovL2Rhc2Vyc3RlLmRlL2Rvbm5hIGxlb24vMGNkMjFiMDktZjE2MS00ZDg3LWI4OTEtNGMzYTkxOTk4ZDQw/
[ARD:mediathek] Y3JpZDovL2Rhc2Vyc3RlLmRlL2Rvbm5hIGxlb24vMGNkMjFiMDktZjE2MS00ZDg3LWI4OTEtNGMzYTkxOTk4ZDQw: Downloading webpage
[ARD:mediathek] 90451812: Downloading media JSON
[ARD:mediathek] 90451812: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Downloading subtitles: de
[info] 90451812: Downloading 1 format(s): hls-508
[info] Writing video subtitles to: Donna Leon - Schöner Schein [90451812].de.ttml
[debug] Invoking downloader on "https://www.ardmediathek.de/subtitle/520157"
[download] Destination: Donna Leon - Schöner Schein [90451812].de.ttml
[download] 100% of 122.64KiB in 00:00
[debug] Invoking downloader on "https://dasersteuni-vh.akamaihd.net/i/int/2021/06/17/0cd21b09-f161-4d87-b891-4c3a91998d40/,640-1_921535,480-1_921535,960-1_921535,1280-1_921535,1920-1_921535,.mp4.csmil/index_1_av.m3u8?null=0"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 1329
[download] Destination: Donna Leon - Schöner Schein [90451812].mp4
[download]   3.4% of ~412.46MiB at  3.13MiB/s ETA 05:15
```

Here's an example of one that is long-form explicit downloaded segment by segment output to shell.  I've edited out all the segment download update lines that normally would follow to keep the output down but it should be obvious what I'm trying to convey.

```bash
yt-dlp -f "bestvideo[ext=mp4][width<=960]+bestaudio[format_id$=Audio_Description]" --write-sub  https://www.france.tv/france-2/candice-renoir/candice-renoir-saison-9/2767859-la-beaute-ne-se-voit-qu-avec-les-yeux-de-l-ame.html
```

**Comment by boulderob** [comment]
It is true that I do *not* have `pycryptodomex` installed.   This means that all my downloads go through `ffmpeg`.  The fact that I see long form segment output some times and not others means that it probably doesn't have anything to with `pycryptodomex`.  My guess is that the short vs long output behavior depends on the stream itself.   

Perhaps some stream segments are encrypted and others aren't and that is what generates the longform output?  Is there a way to check / know this easily from the command output?

**Comment by pukkandan** [comment]
> This means that all my downloads go through ffmpeg

No, only encrypted streams go through ffmpeg

**Comment by boulderob** [comment]
> > This means that all my downloads go through ffmpeg
> 
> No, only encrypted streams go through ffmpeg

Ok.  To clarify the long form output appears to only be generated on *encrypted* segments that just so happen to run through ffmpeg.   

When the segments are *not* encrypted does `yt-dlp` use a native / custom segment downloader or another third-party tool other than `ffmpeg`? 

I think the confusion on my end is that I've only ever manually downloaded manifests with `ffmpeg` and assumed it was the defacto standard for such things.

**Comment by pukkandan** [comment]
we have native downloader for HLS videos. it supports even aes encrypted streams, but u need cryptodome for that. 

PS: live videos arent supported by the native downloader

**Comment by boulderob** [comment]
Ok thanks.  Since you pulled in a third party package is there any reason why you chose that route vs using ffmpeg anyway as it is the default?  

Prior to switching to `yt-dlp` I periodically dipped into the old code base of `youtube-dl`.  There's a lot of moving pieces behind the scenes in either code base outside of the basic IEs and I'd like to understand them at a deeper level.  

I'm just trying to get an idea of what benefits come from rolling your own native downloader in this case vs using something that already existed?

**Comment by pukkandan** [comment]
> I'm just trying to get an idea of what benefits come from rolling your own native downloader in this case vs using something that already existed?

1. youtube-dl has always tried to be as dependency-free as possible
1. native downloader is generally faster than ffmpeg
1. We get much more control over the downloads. For example, we automatically remove known ad-segments from hls.
1. --keep-fragments, --fragment-retries, --abort-on-unavailable-fragments etc are not supported by ffmpeg
1. Socks proxies don't work with ffmpeg (even http proxies didn't used to work some years ago)
1. For yt-dlp, the mulithreading support either with aria2c or with -N are also facilitated by the native downloader

**Comment by boulderob** [comment]
Super.  Thanks for the concise input.  Very helpful.
