### ISSUE TITLE
Site support for 3speak.tv

### ISSUE THREAD

**Issue by trizen** [yt-dlp/yt-dlp#1421]
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2021.10.22**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Worldwide

### Example URLs

- Single video: https://3speak.tv/watch?v=dannyshine/wjgoxyfy

### Description

The download URL for the above video, would be:

https://threespeakvideo.b-cdn.net/wjgoxyfy/NuraIACMfAhnlaNrAFPYgkQFITiXtJgOHgUdjVnuhHgeuyjWlGXhOVzbkridrlHA.mp4

The video download URL is easily extractable from the HTML page, as the website supports downloading of videos.

![2021-10-25-191123_1920x1080_scrot](https://user-images.githubusercontent.com/614513/138731976-7f3212e3-d4ec-4888-961d-95b42685cea7.jpg)

### Verbose log

```shell
% yt-dlp -Uv https://3speak.tv/watch\?v\=dannyshine/wjgoxyfy
[debug] Command-line config: ['-Uv', 'https://3speak.tv/watch?v=dannyshine/wjgoxyfy']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2021.10.22
[debug] Lazy loading extractors is disabled
[debug] Python version 3.9.7 (CPython 64bit) - Linux-5.14.14-hardened1-1-hardened-x86_64-with-glibc2.33
[debug] exe versions: ffmpeg 4.4, ffprobe 4.4, rtmpdump 2.4
[debug] Optional libraries: Crypto, mutagen, sqlite, websockets
[debug] Proxy map: {}
yt-dlp is up to date (2021.10.22)
[debug] [generic] Extracting URL: https://3speak.tv/watch?v=dannyshine/wjgoxyfy
[generic] wjgoxyfy: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] wjgoxyfy: Downloading webpage
[generic] wjgoxyfy: Extracting information
[debug] [generic] Extracting URL: https://3speak.tv/embed?v=dannyshine/wjgoxyfy
[generic] wjgoxyfy: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] wjgoxyfy: Downloading webpage
[generic] wjgoxyfy: Extracting information
[generic] wjgoxyfy: Downloading m3u8 information
WARNING: [generic] Failed to download m3u8 information: HTTP Error 404: Not Found
ERROR: [generic] wjgoxyfy: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1311, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1349, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1399, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/usr/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 2273, in process_video_result
    self.raise_no_formats(info_dict)
  File "/usr/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 913, in raise_no_formats
    raise ExtractorError(msg, video_id=info['id'], ie=info['extractor'],
yt_dlp.utils.ExtractorError: [generic] wjgoxyfy: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
```

**Comment by kyleb1111** [comment]
3speak still doesn't work, has this been implemented yet?

**Comment by bashonly** [comment]
@kyleb1111 yes, but that was nearly 3 years ago, and the extractor's code has not been touched since then, so it may be broken. Please open a new issue with a verbose log if it's not working for you
