### ISSUE TITLE
[Crunchyroll] Log In support

### ISSUE THREAD

**Issue by federicorosso1993** [yt-dlp/yt-dlp#1424]
### Checklist

- [X] I'm reporting a site feature request
- [X] I've verified that I'm running yt-dlp version **2021.10.22**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Example URLs

https://beta.crunchyroll.com/it/watch/G8WUN2ND8/La-citt-delle-bestie-magiche-coperta-di-neve
https://beta.crunchyroll.com/watch/GJWU2J7Z8/Clash-Class-A-vs-Class-B

### Description

Like I said the in site support issue 
https://github.com/yt-dlp/yt-dlp/issues/915

It is possible to not only support the website but also the login for crunchyroll.
Access to beta crunchyroll should be default in US for free and paid account (so you should be able to test this with a free account).
Like I said in the support site issue we already got two example on how to implement the log in support
https://github.com/hyugogirubato/Kamyroll-Python
the old basic script (really easy to understand)
https://github.com/hyugogirubato/Kamyroll-Python/blob/ffba19ec6f8c81dae4e5f35e368748fe2fca6494/kamyroll.py
and my own C# implementation (based on that old kamyroll python version, easier to understand at least for me)
https://github.com/federicorosso1993/Kamyroll-CSharp

I think the old crunchyroll log in support was already half broken (it required a cookies.txt file and the user agent), my own script and kamyroll-python do not require anything like that (my own implementation and the old version of kamyroll used this kind of code

`var cookie = cookieContainer.GetCookies(uri).Cast().FirstOrDefault(x => x.Name == "etp_rt");` 
in C# and a code like this 
```
r = requests.get(endpoint)
etp_rt = r.cookies.get("etp_rt") 
```
in python

So it should be possible to avoid the request of a cookie file from the user. I know that the new kamyroll implemetation in python don't even need that since it use the mobile api to log in.
The old implementation use the desktop app api.
My own implementation got also a comment with the web API implementation to log in (I made it as a comment because the desktop app api it's already working as an alternative).
You can use this page
https://www.crunchyroll.com/welcome/login 
and this page
https://www.crunchyroll.com/originals/it/index.html

to find the basic auth code (in a get with this url https://api.crunchyroll.com/start_session.0.json?sess_id=1&device_type=com.crunchyroll.static&device_id=whatvalueshouldbeforweb&access_token=giKq5eY27ny3cqz )
It's always the same value and it will work to start the log in.

Not sure how to implement it in a large python app like yt-dlp (I'm not really skilled with python) but the code it's already done and it's working in another app (made just to fix youtube-dl and now yt-dlp).

**Comment by tejing1** [comment]
FYI, if you're ok with using cookies rather than a proper login, #2506 implements that. Any login system that gets you an `etp_rt` cookie should integrate with that without hassle as well. Other mechanisms would probably need to alter the way `auth_response` is generated.

**Comment by tejing1** [comment]
Is including static 'access tokens' like kamyroll does a legal issue yt-dlp wants to avoid? If it isn't, I'd be happy to whip up a login mechanism for the beta extractor based on what the current version of kamyroll is doing. It's a pretty small addition to what I do in #2506. Basically just generate `auth_response` differently, supplying a hardcoded basic token copied from kamyroll in the `Authorization` header and putting `grant_type=password&username=<username>&password=<password>&scope=offline_access` in the post data.

**Comment by pukkandan** [comment]
Is the "access_token" obtainable publically? ie, can it be deduced from the webpage or the requests that we get in the browser. If so, it is fine to hardcode it. If it is instead some sort of leaked key, that could have legal implications and is not something I want to deal with

**Comment by federicorosso1993** [comment]
> Is the "access_token" obtainable publically? ie, can it be deduced from the webpage or the requests that we get in the browser. If so, it is fine to hardcode it. If it is instead some sort of leaked key, that could have legal implications and is not something I want to deal with

Yes. You can get it from here
https://www.crunchyroll.com/welcome/login

The access token is always the same
https://api.crunchyroll.com/get_upsell_data.0.json?sess_id=1&device_id=whatvalueshouldbeforweb&device_type=com.crunchyroll.static&access_token=giKq5eY27ny3cqz&referer=https:%2F%2Fwww.crunchyroll.com%2Fit%2Fwelcome%2Flogin

**Comment by pukkandan** [comment]
Then u can hardcode it. We do the same for other sites including youtube

**Comment by tejing1** [comment]
The key used by the current kamyroll implementation (`aHJobzlxM2F3dnNrMjJ1LXRzNWE6cHROOURteXRBU2Z6QjZvbXVsSzh6cUxzYTczVE1TY1k=`) is datamined from the mobile app or its traffic, rather than the web site, afaik. The mobile app is freely available, but presumably has a EULA of some kind, unlike a web site. Still ok?

**Comment by federicorosso1993** [comment]
> Not sure how to implement it in a large python app like yt-dlp (I'm not really skilled with python) but the code it's already done and it's working in another app (made just to fix youtube-dl and now yt-dlp).

I quote myself
"Not sure how to implement it in a large python app like yt-dlp (I'm not really skilled with python) but the code it's already done and it's working in another app (made just to fix youtube-dl and now yt-dlp)."
My own implementation is in a C# app
https://github.com/federicorosso1993/Kamyroll-CSharp

**Comment by tejing1** [comment]
Hmm, ok. After some inspection, and your comments, I'm starting to see how the web login works, so I think I could implement that directly, without any hardcoded tokens. I'll work on it soon.

**Comment by tejing1** [comment]
I also find it amusing that `whatvalueshouldbeforweb` is literally the device id... somebody used a template and never changed it I guess :-P

**Comment by tejing1** [comment]
I gave it a shot, but the problem I'm running into is that I get a 403 Forbidden response from cloudflare, that wants me to prove I'm human with a captcha, when I try to download the login page (https://www.crunchyroll.com/welcome/login). Afaict this happens even when I'm sending the exact same http request as the browser does (for example, using the 'copy as curl' option from my browser's inspector), so I'm a bit stumped as to how to get around it.

**Comment by tejing1** [comment]
On the plus side, the rest of the process works fine, so I went ahead and made a PR with the data from the login page hardcoded.

**Comment by federicorosso1993** [comment]
> I gave it a shot, but the problem I'm running into is that I get a 403 Forbidden response from cloudflare, that wants me to prove I'm human with a captcha, when I try to download the login page (https://www.crunchyroll.com/welcome/login). Afaict this happens even when I'm sending the exact same http request as the browser does (for example, using the 'copy as curl' option from my browser's inspector), so I'm a bit stumped as to how to get around it.

I tried it again and you're right (it was working when I opened this ticket a while ago).
Right now I'm still using the access_token from the desktop app as default and that still work, but I understand that you cannot use any access_token.
Not sure how will you solve this problem but I'm glad you can.
Worst case scenario a solution could be to ask the user to input that

**Comment by tejing1** [comment]
> I tried to read your fix and if I understand it right you are still able to get the session_id with self._download_json on that url (not sure how that is different from a regular get)...

I think the difference is mostly that it's on api.crunchyroll.com rather than crunchyroll.com. The api.crunchyroll.com domain isn't cloudflare-happy. Unsurprisingly, given that it's intended to be accessed by non-browser software like the desktop and mobile apps, and the various streaming box apps as well.

The only thing I'm having trouble with is the login page itself, so I just hardcoded the data that would normally be in it, which hasn't changed, at least since you opened the issue, so I think we're good.

**Comment by tejing1** [comment]
Ah, I realized I misunderstood you. `self._download_json` is a wrapper around urllib, and becomes a `GET` in this case because I used `query=`. `data=` would produce a `POST` instead.

My process starts with a session id from a `GET` to `get_upsell_data.0.json`, then logs in with a `POST` to `login.1.json`, which sets the `etp_rt` cookie needed for the beta extractor's call to `auth/v1/token` on the beta api (and presumably also the non-beta mechanism works on the same cookie).

**Comment by federicorosso1993** [comment]
Yes I can confirm that the same cookie is used on the non-beta website.
Thank you for your explaination. I actually misunderstood you too since I tried a GET on postman-like website of  https://api.crunchyroll.com/get_upsell_data.0.json?sess_id=1&device_id=whatvalueshouldbeforweb&device_type=com.crunchyroll.static&access_token=giKq5eY27ny3cqz&referer=https:%2F%2Fwww.crunchyroll.com%2Fit%2Fwelcome%2Flogin and it gave me the cloudflare error so I was under the impression that it did not work anymore even with hardcoded access_token, device_type, device_id, sess_id. 
So I'm glad it's working on python (maybe if I'll try again in an actual application it will work too).

**Comment by tejing1** [comment]
> Yes I can confirm that the same cookie is used on the non-beta website.

Good. That raises my confidence that this code will work for non-beta users.

> I tried a GET on postman-like website of [...] and it gave me the cloudflare error so I was under the impression that it did not work anymore [...]. So I'm glad it's working on python (maybe if I'll try again in an actual application it will work too).

Just running `curl` on that url (with no special flags) works fine for me with no cloudflare issues, so it can't be too sensitive, since that command would send an honest user-agent string identifying as `curl`. Maybe it's more sensitive in some regions of the world than others?

**Comment by federicorosso1993** [comment]
I didn't even tried curl.. No you are right it's working and since I'm in italy I don't think it's more sensitive in some regions.
My mistake was to trust a website to make an API call, but I was outside just a while ago.

**Comment by tejing1** [comment]
Ah, ok. Good. I was worried my code might not work in some places.

**Comment by tejing1** [comment]
Cloudflare probably just thinks that specific IP is suspicious
