### ISSUE TITLE
Support to specify extractor

### ISSUE THREAD

**Issue by djfdat** [yt-dlp/yt-dlp#1468]
### Checklist

- [X] I'm reporting a feature request
- [X] I've verified that I'm running yt-dlp version **2021.10.22**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

I'm running into a case where I'm attempting to download video from a platform (Teachable) that is hosted on a custom platform. Unfortunately, this causes it to fallback to the generic extractor.

Instead of trying to add support for all these potential domains for that platform, I was hoping we could get an option to specify the extractor to use instead.

**Comment by anamyk** [comment]
how did your get your cookies correctly?
