### ISSUE TITLE
[Broken] YouTube: Removed channels redirect to homepage when cookies are provided

### ISSUE THREAD

**Issue by Zirro** [yt-dlp/yt-dlp#147]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running yt-dlp version **2021.03.03.2**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
$ yt -s --cookies ~/cookies.txt -vvv 'https://www.youtube.com/user/ForensicFilesChannel'
[debug] Command-line config: ['-s', '--cookies', 'cookies.txt', '-vvv', 'https://www.youtube.com/user/ForensicFilesChannel']
[debug] Loading archive file None
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] yt-dlp version 2021.03.03.2
[debug] Python version 3.9.2 (CPython 64bit) - macOS-10.15.7-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.3.2, ffprobe 4.3.2, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
WARNING: A channel/user page was given. All the channel's videos will be downloaded. To download only the videos in the home page, add a "/featured" to the URL
[youtube:tab] ForensicFilesChannel: Downloading webpage
[download] Downloading playlist: ForensicFilesChannel
[youtube:tab] ForensicFilesChannel page 1: Downloading API JSON
[youtube:tab] ForensicFilesChannel page 2: Downloading API JSON
[youtube:tab] ForensicFilesChannel page 3: Downloading API JSON
[youtube:tab] ForensicFilesChannel page 4: Downloading API JSON
[youtube:tab] ForensicFilesChannel page 5: Downloading API JSON
[youtube:tab] ForensicFilesChannel page 6: Downloading API JSON
[youtube:tab] ForensicFilesChannel page 7: Downloading API JSON
[youtube:tab] ForensicFilesChannel page 8: Downloading API JSON
[youtube:tab] ForensicFilesChannel page 9: Downloading API JSON
[youtube:tab] ForensicFilesChannel page 10: Downloading API JSON
[youtube:tab] ForensicFilesChannel page 11: Downloading API JSON
[youtube:tab] ForensicFilesChannel page 12: Downloading API JSON
[youtube:tab] ForensicFilesChannel page 13: Downloading API JSON
[youtube:tab] playlist ForensicFilesChannel: Downloading 333 videos
[download] Downloading video 1 of 333
...
```

## Description

https://www.youtube.com/user/ForensicFilesChannel

There used to be a channel located at this URL which has since been hidden or deleted. Without `--cookies`, it responds with a 404 page and behaves as expected.

When `--cookies` are provided, the URL will redirect to another page instead. Depending on whether the associated Google account has set up a YouTube channel or not, it appears that the redirect ends up either on the user's own channel or the YouTube homepage with a prompt asking if you want to create a YouTube channel. In the latter case, yt-dlp starts downloading videos from the YouTube homepage instead. This is obviously not what the user intended.

When a URL for what turns out to be a deleted channel is provided, it would probably be better not to follow redirects to these locations and instead show an error message.

**Comment by pukkandan** [comment]
The issue is that youtube does not give any indication that the channel doesn't exist before redirecting. afaik there is no way to differentiate this from an actually valid redirect

**Comment by Zirro** [comment]
If a link to a specific channel is given, I would assume that the only useful redirect in this situation from a yt-dlp user's perspective would be to the same channel under a new name.

It seems like yt-dlp could choose to ignore any other unwanted redirect based on where it leads, such as when the destination is the YouTube homepage. I don't think it'd break any legitimate use case if a URL like  'https://www.youtube.com/user/ForensicFilesChannel' was prevented from redirecting to the YouTube homepage.

**Comment by pukkandan** [comment]
https://www.youtube.com/user/ForensicFilesChannel redirects me to https://www.youtube.com/channel/UCKcqXmCcyqnhgpA5P0oHH_Q
https://www.youtube.com/AsapSCIENCE redirects to https://www.youtube.com/channel/UCC552Sd-3nyi_tk2BudLUzA

The issue is how to distinguish these two cases

**Comment by Zirro** [comment]
It looks like there's a 303 redirect to https://www.youtube.com/profile in the former case when the target is your own channel. Could we simply cancel the redirections if 'https://www.youtube.com/profile' is part of the chain (in addition to when the target is non-channel locations such as the YouTube homepage)?

**Comment by pukkandan** [comment]
There are many invalid youtube URLs that redirect back to the home page. (Eg: https://www.youtube.com/playlist?list=notaplaylist) It is impossible to fix for all such cases. Not to mention that youtube changes these redirect behaviors on a whim.

**Comment by Zirro** [comment]
Interesting - that link does not actually perform a redirect to the home page. It includes the video listing from the home page while remaining on the playlist URL. We could probably detect this special case by looking at the markup, but assuming that this only happens for URLs that don't follow the pattern of [_PLAYLIST_ID_RE](https://github.com/yt-dlp/yt-dlp/blob/master/yt_dlp/extractor/youtube.py#L71) this should be very rare.

We could at least try to solve it for playlists which have been valid/existed at one point. Based on the examples so far, I believe the following rule would help:

If the provided `URL` matches that of a valid playlist/channel/user page and responds with HTTP code...
- 200
  - Download the playlist.

- 303
  - Follow the chain of redirects. If the chain leads to a path matching `/` or `/profile`, throw an error. This not the playlist you're looking for.

- 404
  - Throw an error. There is no playlist here.

Can you think of a situation where this would cause problems, or other special cases to consider?

**Comment by pukkandan** [comment]
The redirect itself is handled by libraries. Modifying it to do conditional redirects is very difficult

I had discussed the matter with @colethedj  and we could not find any other reliable way to fix this.

I honestly don't want to spend too much effort on what is essentially a youtube bug - especially one that is only an issue in these edge cases.

In general, if the URL doesn't work as expected in browser, don't expect it to work in yt-dlp.

**Comment by Zirro** [comment]
I see. I regularly archive a set of around 8300 channels and playlists so I can't always be there to actively watch the process and see if it starts downloading unrelated videos because a page has disappeared.

But I can certainly also understand your desire to not add further complexity/maintenance burden to the already complex YouTube extractor, so I'm fine with writing my own script to detect when unrelated videos start being downloaded. You can close the issue if you want. Thanks for the discussion!

**Comment by pukkandan** [comment]
I do understand your issue. I will keep this open in case someone else wants to try their hand at fixing this. 

In the meantime, I recommend you use either channel URLs or direct URLs instead of User ones. 
* https://www.youtube.com/ForensicFilesChannel does not cause this issue.
* Invalid channel URLs like https://www.youtube.com/channel/UCKcqXmCcyqnhgpA5P0oHH_s also give correct message.
The issue is only when using /user/ URLs

**Comment by Zirro** [comment]
Ah, I had no idea that made a difference. Do all `/user/` URLs have that equivalent at the root path? If so, I'm tempted to suggest that yt-dlp does that rewrite automatically. Either way, thanks for the tip. That's very helpful :-)

**Comment by pukkandan** [comment]
> Do all `/user/` URLs have that equivalent at the root path

No. See https://support.google.com/youtube/answer/6180214

**Comment by colethedj** [comment]
Think YouTube has fixed this issue - I now get a 404 page when logged in when I go to https://www.youtube.com/user/ForensicFilesChannel.

```
[debug] Command-line config: ['--flat-playlist', '--verbose', '--cookies', '~/Desktop/cookies.Youtube.txt', 'https://www.youtube.com/user/ForensicFilesChannel']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] yt-dlp version 2021.03.24.1 (source)
[debug] Plugin Extractors: ['SamplePlugin']
[debug] Git HEAD: 5a9aae9e5
[debug] Python version 3.9.2 (CPython 64bit) - Linux-5.10.23-1-MANJARO-x86_64-with-glibc2.33
[debug] exe versions: ffmpeg 4.3.2, ffprobe 4.3.2, rtmpdump 2.4
[debug] Proxy map: {}
[youtube:tab] ForensicFilesChannel: Downloading webpage
WARNING: A channel/user page was given. All the channel's videos will be downloaded. To download only the videos in the home page, add a "/featured" to the URL
ERROR: Unable to download webpage: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
  File "/home/colethedj/Development/yt-dlp/yt_dlp/extractor/common.py", line 666, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/home/colethedj/Development/yt-dlp/yt_dlp/YoutubeDL.py", line 2822, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/usr/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
```

Though invalid playlist urls still redirect to a broken home https://www.youtube.com/playlist?list=notaplaylist.
