### ISSUE TITLE
Support binary name comparison as alternative to --compat-options

### ISSUE THREAD

**Issue by Leseratte10** [yt-dlp/yt-dlp#1478]
### Checklist

- [X] I'm reporting a feature request
- [X] I've verified that I'm running yt-dlp version **2021.10.22**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

I was wondering if it was possible / simple to implement to make yt-dlp automatically apply compat-options when called with a different binary name. 

When I take the yt-dlp binary and call it like `./yt-dlp --help`, the help output states "yt-dlp". 
When I create a symlink like this: `ln -s yt-dlp youtube-dl`, I can then also run `./youtube-dl --help` instead, which will still run the yt-dlp binary but the help now displays "youtube-dl" instead of "yt-dlp". 

This means that yt-dlp is already capable of figuring out which name it is running under. 

What I am now suggesting is, when the yt-dlp tool notices it's called with the "youtube-dl" name, then it should automatically behave as if `--compat-options youtube-dl` was passed (unless of course the user adds his own compat-options to override this. Same of course for "youtube-dlc". 

This would make it so that you could use yt-dlp as a "drop in" for youtube-dl and all previously written scripts or stuff (which expect youtube-dl behaviour) would continue working, all that you needed to do was to create a symlink from "youtube-dl" to "yt-dlp". 

I've seen various forks of other popular projects (unrelated to youtube-dl) do this, putting instructions like these in the README file: If you want yt-dlp to behave like youtube-dl, all you need to do is rename the binary (or create a symlink). 

This allows people to easily make yt-dlp behave like youtube-dl by just calling "youtube-dl", even if they only have yt-dlp installed, without the need to update any scripts to call yt-dlp instead and add the compat-options parameter.

**Comment by pukkandan** [comment]
> What I am now suggesting is, when the yt-dlp tool notices it's called with the "youtube-dl" name, then it should automatically behave as if --compat-options youtube-dl was passed (unless of course the user adds his own compat-options to override this. Same of course for "youtube-dlc".

No, this will not be implemented. Each compat option comes with its own caveats and issues. They will only be used if the user **explicitly** requests them

**Comment by Leseratte10** [comment]
Well, if I execute "youtube-dl" instead of "yt-dlp" then I do explicitly request the tool to behave like youtube-dl, don't I?

**Comment by pukkandan** [comment]
1. Making a program behave differently based on the executable name is dumb and counter-intuitive (unless the program is specifically designed for that, ofc)
2. If you wanted to keep youtube-dl's behavior exactly, you'd just use youtube-dl, wouldn't you? The compat options exist as a way to revert specific changes that can break compatibility with existing scripts/wrappers and to ease any transition. It is not a blanket solution to make yt-dlp a "drop in replacement" for youtube-dl. And as such, I have no intention of making any of these options enabled by default under any circumstance
3. There are already people who use yt-dlp renamed/symlinked to youtube-dl. A change like this could potentially break all their setups
