### ISSUE TITLE
Compat-options format-sort not working properly [youtube.com]

### ISSUE THREAD

**Issue by eatkd** [yt-dlp/yt-dlp#1479]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2021.10.22**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

The --compact-options format-sort does not give the same sorting list as that of youtube-dl

My youtube-dl config is
-f bestvideo+bestaudio/best
-o C:/Users/eatkd/Desktop/dl_video_downloads/%(title)s.%(ext)s
--no-mtime
--merge-output-format mkv

My yt-dlp config is 
--compat-options format-sort
-f bestvideo+bestaudio/best
-o C:/Users/eatkd/Desktop/dlp_video_downloads/%(title)s.%(ext)s
--no-mtime
--merge-output-format mkv

C:\Users\eatkd>youtube-dl.exe https://www.youtube.com/watch?v=S8kG2TQyIwE
[youtube] S8kG2TQyIwE: Downloading webpage
[youtube] S8kG2TQyIwE: Downloading MPD manifest
[dashsegments] Total fragments: 361
[download] Destination: C:\Users\eatkd\Desktop\dl_video_downloads\comma ai Scopie Sunday.f244.webm
[download]   8.0% of ~42.52MiB at 82.00KiB/s ETA 19:49

C:\Users\eatkd>yt-dlp https://www.youtube.com/watch?v=S8kG2TQyIwE
[youtube] S8kG2TQyIwE: Downloading webpage
[youtube] S8kG2TQyIwE: Downloading android player API JSON
[youtube] S8kG2TQyIwE: Downloading MPD manifest
[youtube] S8kG2TQyIwE: Downloading MPD manifest
[info] S8kG2TQyIwE: Downloading 1 format(s): 135+251
[download] Destination: C:\Users\eatkd\Desktop\dlp_video_downloads\comma ai Scopie Sunday.f135.mp4
[download]  08.0% of 73.91MiB at 838.51KiB/s ETA 01:18

### Verbose log

```shell
C:\Users\eatkd>yt-dlp -v https://www.youtube.com/watch?v=S8kG2TQyIwE
[debug] Command-line config: ['-v', 'https://www.youtube.com/watch?v=S8kG2TQyIwE']
[debug] User config file: C:\Users\eatkd\AppData\Roaming\yt-dlp\config.txt
[debug] User config: ['-f', 'bestvideo+bestaudio/best', '-o', 'C:/Users/eatkd/Desktop/dlp_video_downloads/%(title)s.%(ext)s', '--no-mtime', '--merge-output-format', 'mkv', '--compat-options', 'format-sort']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252[debug] yt-dlp version 2021.10.22 (win_exe)
[debug] Compatibility options: format-sort
[debug] Python version 3.7.9 (CPython 32bit) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg 4.4-full_build-www.gyan.dev, ffprobe 4.4-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=S8kG2TQyIwE
[youtube] S8kG2TQyIwE: Downloading webpage
```

**Comment by pukkandan** [comment]
Has been fixed. If you can't wait for next release, use `-S quality,tbr` as a temporary workaround
