### ISSUE TITLE
[Broken] Viki Pass Plus

### ISSUE THREAD

**Issue by cavalia88** [yt-dlp/yt-dlp#148]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running yt-dlp version **2021.03.03.2**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
H:\IDM>yt-dlp -v https://www.viki.com/videos/1178775v --username xxxx and --password xxxx
[debug] Command-line config: ['-v', 'https://www.viki.com/videos/1178775v', '--username', 'PRIVATE', 'and', '--password', 'PRIVATE']
[debug] Loading archive file None
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] yt-dlp version 2021.03.03.2 (exe)
[debug] Python version 3.8.7 (CPython 64bit) - Windows-10-10.0.18362-SP0
[debug] exe versions: none
[debug] Proxy map: {}
[viki] Logging in
[viki] 1178775v: Downloading video JSON
[viki] 1178775v: Downloading video streams JSON
ERROR: No video formats found; please report this issue on https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1024, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1045, in __extract_info
  File "yt_dlp\extractor\common.py", line 546, in extract
  File "yt_dlp\extractor\viki.py", line 378, in _real_extract
  File "yt_dlp\extractor\common.py", line 1655, in _sort_formats
yt_dlp.utils.ExtractorError: No video formats found; please report this issue on https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.

ERROR: 'and' is not a valid URL. Set --default-search "ytsearch" (or run  yt-dlp "ytsearch:and" ) to search YouTube
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1024, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1045, in __extract_info
  File "yt_dlp\extractor\common.py", line 546, in extract
  File "yt_dlp\extractor\generic.py", line 2383, in _real_extract
yt_dlp.utils.ExtractorError: 'and' is not a valid URL. Set --default-search "ytsearch" (or run  yt-dlp "ytsearch:and" ) to search YouTube

```

## Description

WRITE DESCRIPTION HERE

Unable to download video from Viki website that requires "Viki Pass Plus" access. I have Viki Pass Plus access and have provided the necessary username and password, but the downloads don't work. Able to view the videos on web-browser with no issues.

I managed to download the mpd file, but not sure what to do with it. Tried passing the URL for the mpd into youtube-dl, but no luck either.

I can PM you the Viki Pass Plus credentials if required.

Normal videos from Viki for "Standard" users work fine.

**Comment by pukkandan** [comment]
Probably the formats are DRM protected

What is the output of
```
    yt-dlp --allow-unplayable-formats -v -F https://www.viki.com/videos/1178775v --username xxxx --password xxxx 
```

**Comment by cavalia88** [comment]
`yt-dlp --allow-unplayable-formats -v -F https://www.viki.com/videos/1178775v --username xxxx --password xxxx
[debug] Command-line config: ['--allow-unplayable-formats', '-v', '-F', 'https://www.viki.com/videos/1178775v', '--username', 'PRIVATE', '--password', 'PRIVATE']
WARNING: --fixup is ignored since --allow-unplayable-formats was given
[debug] Loading archive file None
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] yt-dlp version 2021.03.03.2 (exe)
[debug] Python version 3.8.7 (CPython 64bit) - Windows-10-10.0.18362-SP0
[debug] exe versions: none
[debug] Proxy map: {}
[viki] Logging in
[viki] 1178775v: Downloading video JSON
[viki] 1178775v: Downloading video streams JSON
ERROR: No video formats found; please report this issue on https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1024, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1045, in __extract_info
  File "yt_dlp\extractor\common.py", line 546, in extract
  File "yt_dlp\extractor\viki.py", line 378, in _real_extract
  File "yt_dlp\extractor\common.py", line 1655, in _sort_formats
yt_dlp.utils.ExtractorError: No video formats found; please report this issue on https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.`

Yes, the streams are DRM protected based on the MPD I managed to download. Finding the Key:Kid is possible, the issue is not being able to download the DRM protected streams.

Upon closer inspection of the MPD, managed to find the two media links, one for audio and other for video. Not sure if they are useful:

`<SegmentTemplate timescale="1000" media="https://kalhlspd-a.akamaihd.net/edashncl/p/2282631/sp/228263100/serveFlavor/entryId/1_8kmhtg0h/sequence/1_dm60lcv2/pv/4/ev/10/flavorParamIds/1545651,1545661,1545701,1545671,1545681,1545721/captions/English,Portuguese,Spanish/forceproxy/true/name/a.mp4/fragment-$Number$-$RepresentationID$.m4s" initialization="https://kalhlspd-a.akamaihd.net/edashncl/p/2282631/sp/228263100/serveFlavor/entryId/1_8kmhtg0h/sequence/1_dm60lcv2/pv/4/ev/10/flavorParamIds/1545651,1545661,1545701,1545671,1545681,1545721/captions/English,Portuguese,Spanish/forceproxy/true/name/a.mp4/init-c1-$RepresentationID$.mp4" duration="4000" startNumber="1">`

`media="https://kalhlspd-a.akamaihd.net/edashncl/p/2282631/sp/228263100/serveFlavor/entryId/1_8kmhtg0h/sequence/1_dm60lcv2/pv/4/ev/10/flavorParamIds/1545651,1545661,1545701,1545671,1545681,1545721/captions/English,Portuguese,Spanish/forceproxy/true/name/a.mp4/fragment-$Number$-i1-$RepresentationID$.m4s" initialization="https://kalhlspd-a.akamaihd.net/edashncl/p/2282631/sp/228263100/serveFlavor/entryId/1_8kmhtg0h/sequence/1_dm60lcv2/pv/4/ev/10/flavorParamIds/1545651,1545661,1545701,1545671,1545681,1545721/captions/English,Portuguese,Spanish/forceproxy/true/name/a.mp4/init-c2-$RepresentationID$.mp4" duration="4000" startNumber="1">`

**Comment by pukkandan** [comment]
We do not support downloading DRM protected content
