### ISSUE TITLE
Timestamps of mp4 and subtitle files used to be the same as the download time but are now different

### ISSUE THREAD

**Issue by boulderob** [yt-dlp/yt-dlp#1481]
### Checklist

- [X] I'm asking a question and not reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

I don't want to open this as a bug because I'm not sure it is.  I'm just looking for guidance here.

I've downloaded tons of video + subtitle combinations using `youtube-dl` for a few years now and more recently been doing the same with a switch to `yt-dlp`.  Whenver I would download a video + subtitles in the past using `--write-subs`, both would get recorded to my local filesystem as new files with the current time as the timestamp listed as the *last write to my local filesystem*.  This appeared to be the case whether the files were segmented or not (at least on the video side of things).

The huge benefit of this is that when I batch download vids + subtitles, when I later sort a folder by timestamp, the downloaded files are in a very easy to follow and organized sequence that is consistent over time as new batches come in.  By that I mean that:

- the files are always in the order that they were download
- each subtitle file is always *right next to it's parent video file*

This makes both *using* and *managing* the files very easy because pairs of files are always together and you have an easy way to chronologically see your downloads as they occured over time.  You can't beat this style.

However, since either the switch to `yt-dlp` or simply the switch to newer segmented subtitle files or some other unexplained reason, the downloaded subtitle files and sometimes even the video container files themselves take on the date / timestamp that they were uploaded to the provider server and not the timestamp when they are recorded to my system.   This throws the ordering and pairing of the files off on the local filesystem.

I'm mostly seeing this in terms of **francetv** video links (francetv extractor) because this is what I download the most.

For instance, if francetv uploaded a video and subtitle file to it's servers two weeks or a year ago, and I download it today, while downloading is in process, the initial video, audio and subtitle `.part` files  are always *initially* stamped with the current time.  But after segment download is completed, some final "file processing" occurs that resets the subtitle file timestamp to an older date then the original and current download time in my own filesystem. 

This often leaves the mp4 container at the current timestamp but reset's the subtitle file to what I presume is it's original provider upload timestamp.

Example:  You can see that I downloaded all of these files today (around midnight straddling Oct 29th and 30th).  The listing is in chronological order.  The `mp4` files have retain the local download time timestampbut the `vtt` subtitle files get reset back anywhere from a few hours to a few days earlier which throws them out of sync with their parent `mp4` files.  

```
total 4229104
drwxr-xr-x  15 mbpme  staff        510 Oct 30 00:50 ./
-rw-r--r--   1 mbpme  staff  720183494 Oct 30 00:11 C dans l'air - Macron _ Biden  - après la trahison, la confrontation !-89725f6e-3da4-4a35-830a-5a5063d69d56.mp4
-rw-r--r--   1 mbpme  staff  281383092 Oct 30 00:06 Plus belle la vie-472fb7e3-03ac-4f6b-aa8d-3b400b0e628a.mp4
-rw-r--r--   1 mbpme  staff  598473322 Oct 30 00:02 Germinal-af8c03fb-a354-4829-b493-2916324ea7c9.mp4
-rw-r--r--   1 mbpme  staff  564823570 Oct 29 23:56 Germinal-dbc8e2d8-003c-4381-ae5d-5fb4b6f89706.mp4
-rw-r--r--   1 mbpme  staff      21381 Oct 29 20:59 Plus belle la vie-472fb7e3-03ac-4f6b-aa8d-3b400b0e628a.fr.vtt
-rw-r--r--   1 mbpme  staff      74615 Oct 29 19:43 C dans l'air - Macron _ Biden  - après la trahison, la confrontation !-89725f6e-3da4-4a35-830a-5a5063d69d56.fr.vtt
-rw-r--r--   1 mbpme  staff      41668 Oct 27 23:20 Germinal-af8c03fb-a354-4829-b493-2916324ea7c9.fr.vtt
-rw-r--r--   1 mbpme  staff      36856 Oct 27 22:33 Germinal-dbc8e2d8-003c-4381-ae5d-5fb4b6f89706.fr.vtt
```

Why does this happen?  Is there a way to override this behavior?  As I said it was never like this in the past and the behavior only changed in the last few months.

Here's the command I use for one of the example files above.

```
yt-dlp -f best[ext=mp4][width<=960][format_id^=hls]/bestvideo[ext=mp4][width<=960][format_id^=hls]+bestaudio[ext=mp4] -Uv -o %(title)s-%(id)s.%(ext)s --write-subs https://www.france.tv/france-2/germinal/germinal-saison-1/2830613-episode-1.html
```

Thanks

**Comment by pukkandan** [comment]
`--no-mtime` is the option you are looking for

> Whenver I would download a video + subtitles in the past using --write-subs, both would get recorded to my local filesystem as new files with the current time as the timestamp listed as the last write to my local filesystem. This appeared to be the case whether the files were segmented or not (at least on the video side of things).

To verify this claim, you are going to have to show the verbose logs of running both youtube-dl and yt-dlp with the same options

**Comment by boulderob** [comment]
Thanks for that tip!  Hopefully that takes care of it.

I have 4T / 4 years worth of files to prove it as I use them extensively / daily so that when things stop working and the files become hard to work with it's obvious and not an oversight.  But I totally understand where you're coming from too.  

The thing is that since the `youtube-dl` francetv IE is broken, there is no way to run a side by side comparison.   But even if I could, I'm not sure it would matter because this behavior seemed to creep in around the time the francetv IE broke and there was a move to the `mpd` formats and segmented subtitle files.   So my guess it has something to do with the combined francetv backend / frontend IE changes that took place a few months ago as that is when the change in behavior started happening.

That said, per my other "ard Tatort" tests that I've posted in the other issue, I can see that the "ard" IE *does* process the subtitle files correctly maintaining the timestamps.   So if you run the following two commands, you will get different subtitle timestamp results for the different IEs.  We're not comparing old fork and new fork francetv IEs to one another but why does current fork "ard" IE maintain the timestamps and "francetv" IE doesn't?   Where or what in the code determines the final timestamp of the subtitle?   (I guess I need to search for `--no-mtime` in the codebase)

ard first:

```
 yt-dlp -Uv -f hls-162 --write-subs https://www.ardmediathek.de/video/tatort/absturz/mdr-fernsehen/Y3JpZDovL21kci5kZS9iZWl0cmFnL2Ntcy84OTIxZTdmYy01YmJjLTRkZmYtYTE5Yy1kYTlkNmUxMzMxMGY/
[debug] Command-line config: ['-Uv', '-f', 'hls-162', '--write-subs', 'https://www.ardmediathek.de/video/tatort/absturz/mdr-fernsehen/Y3JpZDovL21kci5kZS9iZWl0cmFnL2Ntcy84OTIxZTdmYy01YmJjLTRkZmYtYTE5Yy1kYTlkNmUxMzMxMGY/']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2021.10.22 (source)
[debug] Lazy loading extractors is disabled
[debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
[debug] Git HEAD: fccf50211
[debug] Python version 3.9.7 (CPython 64bit) - macOS-11.2.3-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.4.1, ffprobe 4.4.1, rtmpdump 2.4
[debug] Optional libraries: sqlite
[debug] Proxy map: {}
yt-dlp is up to date (2021.10.22)
[debug] Using fake IP 53.33.25.72 (DE) as X-Forwarded-For
[debug] [ARD:mediathek] Extracting URL: https://www.ardmediathek.de/video/tatort/absturz/mdr-fernsehen/Y3JpZDovL21kci5kZS9iZWl0cmFnL2Ntcy84OTIxZTdmYy01YmJjLTRkZmYtYTE5Yy1kYTlkNmUxMzMxMGY/
[ARD:mediathek] Y3JpZDovL21kci5kZS9iZWl0cmFnL2Ntcy84OTIxZTdmYy01YmJjLTRkZmYtYTE5Yy1kYTlkNmUxMzMxMGY: Downloading webpage
[ARD:mediathek] 94131462: Downloading media JSON
[ARD:mediathek] 94131462: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Downloading subtitles: de
[info] 94131462: Downloading 1 format(s): hls-162
[info] Writing video subtitles to: Absturz [94131462].de.ttml
[debug] Invoking downloader on "https://www.ardmediathek.de/subtitle/554906"
[download] Destination: Absturz [94131462].de.ttml
[download] 100% of 133.30KiB in 00:00
[debug] Invoking downloader on "https://mdronline-vh.akamaihd.net/i/mp4dyn2/8/FCMS-8921e7fc-5bbc-4dff-a19c-da9d6e13310f-,41dd60577440,730aae549c28,d1ceaa57a495,be7c2950aac6,70dc5e5f2727,1af20647950e,_89.mp4.csmil/index_2_av.m3u8?set-akamai-hls-revision=5"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 532
[download] Destination: Absturz [94131462].mp4
[download] 100% of 142.18MiB in 01:59
[debug] ffmpeg command line: ffprobe -show_streams 'file:Absturz [94131462].mp4'
[FixupM3u8] Fixing malformed AAC bitstream of "Absturz [94131462].mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:Absturz [94131462].mp4' -c copy -map 0 -dn -f mp4 -bsf:a aac_adtstoasc 'file:Absturz [94131462].temp.mp4'

 $ ▶ ll -t
drwxr-xr-x  18 mbpme  staff        612 Oct 30 02:44 ./
-rw-r--r--   1 mbpme  staff  127453739 Oct 30 02:44 Absturz [94131462].mp4
-rw-r--r--   1 mbpme  staff     136503 Oct 30 02:42 Absturz [94131462].de.ttml

```

francetv

```
yt-dlp -Uv -f best[ext=mp4][width<=960][format_id^=hls]/bestvideo[ext=mp4][width<=960][format_id^=hls]+bestaudio[ext=mp4] -Uv -o %(title)s-%(id)s.%(ext)s --write-subs https://www.france.tv/france-2/germinal/germinal-saison-1/2830613-episode-1.html

[debug] Command-line config: ['-q', '--progress', '-f', 'best[ext=mp4][width<=960][format_id^=hls]/bestvideo[ext=mp4][width<=960][format_id^=hls]+bestaudio[ext=mp4]', '-Uv', '-o', '%(title)s-%(id)s.%(ext)s', '--write-subs', 'https://www.france.tv/france-2/germinal/germinal-saison-1/2830613-episode-1.html']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8 (No ANSI), err utf-8 (No ANSI), pref UTF-8
[debug] yt-dlp version 2021.10.22 (source)
[debug] Lazy loading extractors is disabled
[debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
[debug] Git HEAD: fccf50211
[debug] Python version 3.9.7 (CPython 64bit) - macOS-11.2.3-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.4.1, ffprobe 4.4.1, rtmpdump 2.4
[debug] Optional libraries: sqlite
[debug] Proxy map: {}
yt-dlp is up to date (2021.10.22)
[debug] [FranceTVSite] Extracting URL: https://www.france.tv/france-2/germinal/germinal-saison-1/2830613-episode-1.html
[FranceTVSite] 2830613-episode-1: Downloading webpage
[debug] [FranceTV] Extracting URL: francetv:dbc8e2d8-003c-4381-ae5d-5fb4b6f89706
[FranceTV] dbc8e2d8-003c-4381-ae5d-5fb4b6f89706: Downloading desktop video JSON
[FranceTV] dbc8e2d8-003c-4381-ae5d-5fb4b6f89706: Downloading mobile video JSON
[FranceTV] dbc8e2d8-003c-4381-ae5d-5fb4b6f89706: Downloading signed dash manifest URL
[FranceTV] dbc8e2d8-003c-4381-ae5d-5fb4b6f89706: Downloading MPD manifest
[FranceTV] dbc8e2d8-003c-4381-ae5d-5fb4b6f89706: Downloading signed hls manifest URL
[FranceTV] dbc8e2d8-003c-4381-ae5d-5fb4b6f89706: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id

[debug] Downloading subtitles: fr
[info] dbc8e2d8-003c-4381-ae5d-5fb4b6f89706: Downloading 1 format(s): hls-1582+hls-audio-aacl-96-Audio_Français
[info] Writing video subtitles to: Germinal-dbc8e2d8-003c-4381-ae5d-5fb4b6f89706.fr.vtt
[debug] Invoking downloader on "https://cloudreplay.ftven.fr/693c6333b9716/1050200180_france-domtom_TA.ism/ZXhwPTE2MzU1NjU5OTZ+YWNsPSUyZjY5M2M2MzMzYjk3MTYlMmYxMDUwMjAwMTgwX2ZyYW5jZS1kb210b21fVEEuaXNtKn5obWFjPTI3ZWQ2ZWVmMDk3NjkyMjQzMmNlNDRmNWQ5ZmUyODEzMTYzYjc2ZDAwZTMyZDc5ODg2MzI5MzJkOGJlNjg0Mjk=/1050200180_france-domtom_TA-textstream_fre=1000.m3u8"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 301
[download] Destination: Germinal-dbc8e2d8-003c-4381-ae5d-5fb4b6f89706.fr.vtt

[download] 100% of 35.99KiB in 00:45                                                       

[debug] Invoking downloader on "https://cloudreplay.ftven.fr/693c6333b9716/1050200180_france-domtom_TA.ism/ZXhwPTE2MzU1NjU5OTZ+YWNsPSUyZjY5M2M2MzMzYjk3MTYlMmYxMDUwMjAwMTgwX2ZyYW5jZS1kb210b21fVEEuaXNtKn5obWFjPTI3ZWQ2ZWVmMDk3NjkyMjQzMmNlNDRmNWQ5ZmUyODEzMTYzYjc2ZDAwZTMyZDc5ODg2MzI5MzJkOGJlNjg0Mjk=/1050200180_france-domtom_TA-video=1400000.m3u8"
[hlsnative] Downloading m3u8 manifest
WARNING: The stream has AES-128 encryption and pycryptodomex is not available; extraction will be delegated to ffmpeg
[download] Destination: Germinal-dbc8e2d8-003c-4381-ae5d-5fb4b6f89706.fhls-1582.mp4
[debug] ffmpeg command line: ffmpeg -y -loglevel quiet -headers 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3657.1 Safari/537.36
Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Encoding: gzip, deflate
Accept-Language: en-us,en;q=0.5
' -i https://cloudreplay.ftven.fr/693c6333b9716/1050200180_france-domtom_TA.ism/ZXhwPTE2MzU1NjU5OTZ+YWNsPSUyZjY5M2M2MzMzYjk3MTYlMmYxMDUwMjAwMTgwX2ZyYW5jZS1kb210b21fVEEuaXNtKn5obWFjPTI3ZWQ2ZWVmMDk3NjkyMjQzMmNlNDRmNWQ5ZmUyODEzMTYzYjc2ZDAwZTMyZDc5ODg2MzI5MzJkOGJlNjg0Mjk=/1050200180_france-domtom_TA-video=1400000.m3u8 -c copy -f mp4 file:Germinal-dbc8e2d8-003c-4381-ae5d-5fb4b6f89706.fhls-1582.mp4.part
[ffmpeg] Downloaded 526983929 bytes

[download] 100% of 502.57MiB in 02:43[debug] Invoking downloader on "https://cloudreplay.ftven.fr/693c6333b9716/1050200180_france-domtom_TA.ism/ZXhwPTE2MzU1NjU5OTZ+YWNsPSUyZjY5M2M2MzMzYjk3MTYlMmYxMDUwMjAwMTgwX2ZyYW5jZS1kb210b21fVEEuaXNtKn5obWFjPTI3ZWQ2ZWVmMDk3NjkyMjQzMmNlNDRmNWQ5ZmUyODEzMTYzYjc2ZDAwZTMyZDc5ODg2MzI5MzJkOGJlNjg0Mjk=/1050200180_france-domtom_TA-audio_fre=96000.m3u8"

[hlsnative] Downloading m3u8 manifest
WARNING: The stream has AES-128 encryption and pycryptodomex is not available; extraction will be delegated to ffmpeg
[download] Destination: Germinal-dbc8e2d8-003c-4381-ae5d-5fb4b6f89706.fhls-audio-aacl-96-Audio_Français.mp4
[debug] ffmpeg command line: ffmpeg -y -loglevel quiet -headers 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3657.1 Safari/537.36
Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Encoding: gzip, deflate
Accept-Language: en-us,en;q=0.5
' -i https://cloudreplay.ftven.fr/693c6333b9716/1050200180_france-domtom_TA.ism/ZXhwPTE2MzU1NjU5OTZ+YWNsPSUyZjY5M2M2MzMzYjk3MTYlMmYxMDUwMjAwMTgwX2ZyYW5jZS1kb210b21fVEEuaXNtKn5obWFjPTI3ZWQ2ZWVmMDk3NjkyMjQzMmNlNDRmNWQ5ZmUyODEzMTYzYjc2ZDAwZTMyZDc5ODg2MzI5MzJkOGJlNjg0Mjk=/1050200180_france-domtom_TA-audio_fre=96000.m3u8 -c copy -f mp4 'file:Germinal-dbc8e2d8-003c-4381-ae5d-5fb4b6f89706.fhls-audio-aacl-96-Audio_Français.mp4.part'
[ffmpeg] Downloaded 37013119 bytes

[download] 100% of 35.30MiB in 01:37[debug] ffmpeg command line: ffprobe -show_streams 'file:Germinal-dbc8e2d8-003c-4381-ae5d-5fb4b6f89706.fhls-audio-aacl-96-Audio_Français.mp4'

[Merger] Merging formats into "Germinal-dbc8e2d8-003c-4381-ae5d-5fb4b6f89706.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i file:Germinal-dbc8e2d8-003c-4381-ae5d-5fb4b6f89706.fhls-1582.mp4 -i 'file:Germinal-dbc8e2d8-003c-4381-ae5d-5fb4b6f89706.fhls-audio-aacl-96-Audio_Français.mp4' -c copy -map 0:v:0 -map 1:a:0 -bsf:a:0 aac_adtstoasc file:Germinal-dbc8e2d8-003c-4381-ae5d-5fb4b6f89706.temp.mp4
Deleting original file Germinal-dbc8e2d8-003c-4381-ae5d-5fb4b6f89706.fhls-audio-aacl-96-Audio_Français.mp4 (pass -k to keep)
Deleting original file Germinal-dbc8e2d8-003c-4381-ae5d-5fb4b6f89706.fhls-1582.mp4 (pass -k to keep)
```

Thanks

**Comment by pukkandan** [comment]
Without `--no-mtime`, the timestamp is set to whatever the server says is the "last modified time" of the file. So it is possible that it is a server side change like you said.

Anyway, check with --no-mtime and close the issue if it serves your needs

> Where or what in the code determines the final timestamp of the subtitle? (I guess I need to search for --no-mtime in the codebase)

It is in http.py and fragment.py. Search for `'updatetime'` to quickly find it

**Comment by boulderob** [comment]
Ok. give me a few days to try it and post back.  Thanks for the followup.

**Comment by boulderob** [comment]
Didn't realize I could close these issues myself.  I will do just that.  I just tried `--no-time` and it did the trick.  Thanks for the tip.
