### ISSUE TITLE
how to use BiliBiliSearch in cli

### ISSUE THREAD

**Issue by wanghaisheng** [yt-dlp/yt-dlp#1493]
### Checklist

- [X] I'm asking a question and not reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

```  
$ yt-dlp "BiliBiliSearch:雷电将军" --config-location config.txt 
[generic] BiliBiliSearch:雷电将军: Requesting header
WARNING: [generic] Could not send HEAD request to BiliBiliSearch:雷电将军: <urlopen error unknown url type: bilibilisearch>
[generic] BiliBiliSearch:雷电将军: Downloading webpage
ERROR: [generic] Unable to download webpage: <urlopen error unknown url type: bilibilisearch> (caused by URLError('unknown url type: bilibilisearch'))
(base) 
```

**Comment by pukkandan** [comment]
See supported sites
> BiliBiliSearch: Bilibili video search; "bilisearch:" prefix
