### ISSUE TITLE
www.amazon.co.uk

### ISSUE THREAD

**Issue by Chaz6** [yt-dlp/yt-dlp#1509]
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2021.10.22**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Europe

### Example URLs

- Single video: https://www.amazon.co.uk/dp/B098XNCHLD/

### Description

www.amazon.co.uk is an ecommerce website which contains product videos.

### Verbose log

```shell
[debug] Command-line config: ['-v', 'https://www.amazon.co.uk/dp/B098XNCHLD/']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8[debug] yt-dlp version 2021.10.22
[debug] Python version 3.10.0 (CPython 64bit) - Linux-5.13.9-1.el7.elrepo.x86_64-x86_64-with-glibc2.17
[debug] exe versions: ffmpeg N-58594-g715f63232f-static, ffprobe N-58594-g715f63232f-static
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [generic] Extracting URL: https://www.amazon.co.uk/dp/B098XNCHLD/
[generic] B098XNCHLD: Requesting header
WARNING: [generic] Could not send HEAD request to https://www.amazon.co.uk/dp/B098XNCHLD/: HTTP Error 405: Method Not Allowed
[generic] B098XNCHLD: Downloading webpage
WARNING: [generic] Falling back on generic information extractor.
[generic] B098XNCHLD: Extracting information
ERROR: [generic] Unsupported URL: https://www.amazon.co.uk/dp/B098XNCHLD/
Traceback (most recent call last):
  File "/home/chaz/.local/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 593, in extract
    ie_result = self._real_extract(url)
  File "/home/chaz/.local/lib/python3.10/site-packages/yt_dlp/extractor/generic.py", line 3706, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.amazon.co.uk/dp/B098XNCHLD/
Traceback (most recent call last):
  File "/home/chaz/.local/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 593, in extract
    ie_result = self._real_extract(url)
  File "/home/chaz/.local/lib/python3.10/site-packages/yt_dlp/extractor/generic.py", line 3706, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.amazon.co.uk/dp/B098XNCHLD/

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/chaz/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1280, in wrapper
    return func(self, *args, **kwargs)
  File "/home/chaz/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1305, in __extract_info
    ie_result = ie.extract(url)
  File "/home/chaz/.local/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 609, in extract
    raise ExtractorError(
yt_dlp.utils.ExtractorError: [generic] Unsupported URL: https://www.amazon.co.uk/dp/B098XNCHLD/
```

**Comment by RingoTheDog** [comment]
I was able to download this by pointing yt-dlp directly to the video.

You need to click on the video on the product page, and then "copy the link address" from the video page:

https://www.amazon.co.uk/vdp/13b9a9d5c920484fbfa55feedeff44e1?ref=dp_vse_ibvc0

**Comment by pukkandan** [comment]
To devs:
All the info can be found in the webpage by searching for `obj = jQuery.parseJSON('.+')`

**Comment by nao20010128nao** [comment]
Example in JP store: https://www.amazon.co.jp/dp/B084MF7YZ9/
should have same structure as UK

**Comment by Ashish0804** [comment]
since the structure is same on uk, jp and in
I'll assume it's same on all regions.
