### ISSUE TITLE
Playlist pages persistance

### ISSUE THREAD

**Issue by boggeroff** [yt-dlp/yt-dlp#1514]
### Checklist

- [X] I'm reporting a site feature request
- [X] I've verified that I'm running yt-dlp version **2021.10.22**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

USA

### Example URLs

BBC News
https://www.youtube.com/channel/UC16niRr50-MSBwiO3YDb3RA

### Description

If someone wanted to download videos 1-299 in reverse order (meaning the oldest ones), then all pages would need to be downloaded. And then you might want to repeat this in another session for videos 300-599. The problem is, the page downloading part can even take hours when overall video count is in the 10s of thousands, and you have to repeat it each time. This is a big issue for me. --sleep-interval* options don't play here, and using --sleep-requests to make sure these don't taunt the servers too much is something I'd like to avoid.

So a solution would sound like going throught these steps once,
[youtube:tab] UC16niRr50-MSBwiO3YDb3RA page 1: Downloading API JSON
[youtube:tab] UC16niRr50-MSBwiO3YDb3RA page 2: Downloading API JSON
[youtube:tab] UC16niRr50-MSBwiO3YDb3RA page 3: Downloading API JSON
...
and caching them in the program's cache dir, and then for subsequent invocations making use of this cache. This could be turned on with a flag for the youtubetab extractor. Cache would be only extended for one channel/playlist if there are no corresponding items in the cache based on their ids, otherwise it would be used.
*cache-dir* options are already part of CLI, resetting cache would be easy. But handling these together with youtube-sigfuncs might not be desirable, I don't know.  Lookup could be based on the video_id string: "UC16niRr50-MSBwiO3YDb3RA page 3". Although, this is already stored in memory of course, starting from there would be advisable; this I haven't exactly found so far. This is the point where the page downloads occur: https://github.com/yt-dlp/yt-dlp/blob/c588b602d34f005dc018ae004281226741414192/yt_dlp/extractor/youtube.py#L3783

**Comment by pukkandan** [comment]
I don't see the point. Use `--write-info-json --flat-playlist --no-clean-infojson` to save all the entries in the first run. Then you can `--load-info-json` and do whatever you want with it without re-requesting the pages

**Comment by boggeroff** [comment]
@pukkandan Hm, funny. I've been writing info.jsons since before I can remember, but --load-info-json option has so far eluded me, in the sense how it could be useful. Sounds like a solution and thanks for that! Even though, I suspect it will require an amount of scripting, but that I'm fine with. And why would you say --no-clean-infojson is required?
I'll do some experiments and report back in a day.

**Comment by pukkandan** [comment]
The playlist entries aren't recorded without `--no-clean-infojson`, only the metadata is

**Comment by boggeroff** [comment]
With the following instruction,
```
yt-dlp --write-info-json --flat-playlist --no-clean-infojson -o "%(id)s.%(ext)s" "https://www.youtube.com/channel/UCxTmNldpjtu69y2dQlWlDCQ"
```
I get a <channel id>.info.json file with all the 1359 entries. An entry's fields are only partly valid, like so:

> {'_type': 'url',
              'description': None,
              'duration': 104.0,
              'id': 'EGGR-wIftSQ',
              'ie_key': 'Youtube',
              'title': 'Please subscribe to my new YouTube channel!',
              'uploader': None,
              'url': 'https://www.youtube.com/watch?v=EGGR-wIftSQ',
              'view_count': 1257}

When executing
`ydl --load-info-json "UCxTmNldpjtu69y2dQlWlDCQ.info.json" --playlist-items 1359 -o "%(title)s.%(ext)s" "https://www.youtube.com/channel/UCxTmNldpjtu69y2dQlWlDCQ"`
, this error follows:

> WARNING: "url" field is missing or empty - skipping format, there is an error in extractor
> Traceback (most recent call last):
>   File ".../git/yt-dlp/yt_dlp/__main__.py", line 19, in <module>
>     yt_dlp.main()
>   File ".../git/yt-dlp/yt_dlp/__init__.py", line 791, in main
>     _real_main(argv)
>   File ".../git/yt-dlp/yt_dlp/__init__.py", line 779, in _real_main
>     retcode = ydl.download_with_info_file(expand_path(opts.load_info_filename))
>   File ".../git/yt-dlp/yt_dlp/YoutubeDL.py", line 2946, in download_with_info_file
>     self.process_ie_result(info, download=True)
>   File ".../git/yt-dlp/yt_dlp/YoutubeDL.py", line 1368, in process_ie_result
>     ie_result = self.process_video_result(ie_result, download=download)
>   File ".../git/yt-dlp/yt_dlp/YoutubeDL.py", line 2371, in process_video_result
>     raise ExtractorError('Requested format is not available', expected=True,
> yt_dlp.utils.ExtractorError: [youtube:tab] UCxTmNldpjtu69y2dQlWlDCQ: Requested format is not available

Manual processing of these entries is still a possiblility, but how to make --load-info-json work with a playlist download as you alluded to?

**Comment by pukkandan** [comment]
You have found a bug that is preventing playlists from loading correctly. Will fix it asap.

Note that you need to use `--no-clean-infojson` when loading the infojson too (after the bug is fixed). Also u don't need to pass the URL

**Comment by pukkandan** [comment]
Has been fixed

**Comment by boggeroff** [comment]
Sweet, a bug :), and a nice one at that. Works this way now swimmingly, good job!
