### ISSUE TITLE
Inaccurate speeds reported for fragmented downloads

### ISSUE THREAD

**Issue by klartext** [yt-dlp/yt-dlp#1517]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2021.10.22**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

See subject line: the qrong download speed is reported.

### Verbose log

```shell
myhome:~$ yt-dlp -Uv  "https://www.youtube.com/watch?v=YOH1AoVjGPc" 
[debug] Command-line config: ['-o', '%(title)s__%(uploader)s__%(upload_date)s_%(id)s.%(ext)s', '--no-playlist', '--restrict-filenames', '-Uv', 'https://www.youtube.com/watch?v=YOH1AoVjGPc']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8[debug] yt-dlp version 2021.10.22
[debug] Lazy loading extractors is disabled
[debug] Python version 3.9.7 (CPython 64bit) - Linux-5.14.15-arch1-1-x86_64-with-glibc2.33
[debug] exe versions: ffmpeg 4.4, ffprobe 4.4, rtmpdump 2.4
[debug] Optional libraries: Cryptodome, keyring, mutagen, sqlite, websockets
[debug] Proxy map: {}
yt-dlp is up to date (2021.10.22)
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=YOH1AoVjGPc
[youtube] YOH1AoVjGPc: Downloading webpage
[youtube] YOH1AoVjGPc: Downloading android player API JSON
[youtube] Downloading just video YOH1AoVjGPc because of --no-playlist
[youtube] YOH1AoVjGPc: Downloading MPD manifest
[youtube] YOH1AoVjGPc: Downloading MPD manifest
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] YOH1AoVjGPc: Downloading 1 format(s): 248+251
[debug] Invoking downloader on "https://manifest.googlevideo.com/api/manifest/dash/expire/1635833509/ei/RYKAYZOLNsKR1gLHtI6IAQ/ip/89.12.132.51/id/60e1f502856318f7/source/youtube/requiressl/yes/playback_host/r7---sn-uxax4vopj5qx-cxge.googlevideo.com/mh/Sh/mm/31%2C29/mn/sn-uxax4vopj5qx-cxge%2Csn-h0jeened/ms/au%2Crdu/mv/m/mvi/7/pl/18/tx/24008108/txs/23997970%2C24008108/hfr/all/as/fmp4_audio_clear%2Cwebm_audio_clear%2Cwebm2_audio_clear%2Cfmp4_sd_hd_clear%2Cwebm2_sd_hd_clear/initcwndbps/1258750/vprv/1/mt/1635811738/fvip/5/keepalive/yes/fexp/24001373%2C24007246/itag/0/sparams/expire%2Cei%2Cip%2Cid%2Csource%2Crequiressl%2Ctx%2Ctxs%2Chfr%2Cas%2Cvprv%2Citag/sig/AOq0QJ8wRAIgfjy73Aelw-mhfIgJP_ZdCH7cUElRQANTV3HnZFYvyQkCICyzrUys45oNOUw8a17wjMXddhIpD8P_b3oGmdo4LErj/lsparams/playback_host%2Cmh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps/lsig/AG3C_xAwRAIgE2afku7qPTbcEE-AwHmTcflgXkkwhDD-vhM99fP1xL8CIC8vb70N78VQ8clzfmGjeDcea-YjtFXyC90OXhdKA9IH"
[dashsegments] Total fragments: 853
[download] Destination: Eric_Random_-_A_Boy_Alone_FULL_ALBUM__Yan_Skene__20200917_YOH1AoVjGPc.f248.webm
[download]  17.8% of ~43.11MiB at  5.43MiB/s ETA 01:17^C
ERROR: Interrupted by user
[...]
```

**Comment by pukkandan** [comment]
Does the speed stay like that, or keep fluctuating? It is normal for the instananeous speeds to be inaccurate. The average should be correct though. If not, can u show output with `--newline`

**Comment by Jules-A** [comment]
One thing I've noticed (at least on Windows with -N 4) is that the download speed changes (flickers) so fast that you can't ever see accurate values (even if all you want to see if the value of 1 download thread).

**Comment by pukkandan** [comment]
@Jules-A That is unrelated, and as the warning says, "patches are welcome". I have no clue how to fix the progress in -N

**Comment by Jules-A** [comment]
> 
> 
> @Jules-A That is unrelated, and as the warning says, "patches are welcome". I have no clue how to fix the progress in -N

Hmm.. I don't know... The download speed resets every time a new fragments starts so it shows the peak speed instead of taking in to account the download speed from the previous fragments and smoothly transitioning into it. Even without -N, with a fast download speed or on small files with many fragments (such as audio) it would still occur.

**Comment by klartext** [comment]
![speedtest-1](https://user-images.githubusercontent.com/3165583/139959019-24e436db-a864-49f1-8426-8f18fd16280a.png)
![speedtest-2](https://user-images.githubusercontent.com/3165583/139959027-9821dae7-60b6-4350-8db8-270b5a943d1c.png)
![speedtest-3](https://user-images.githubusercontent.com/3165583/139959028-c7a7b4ec-f55d-443d-bf32-405478315878.png)
[Speed_3.txt](https://github.com/yt-dlp/yt-dlp/files/7464272/Speed_3.txt)
[Speed_2.txt](https://github.com/yt-dlp/yt-dlp/files/7464273/Speed_2.txt)
[Speed_1.txt](https://github.com/yt-dlp/yt-dlp/files/7464274/Speed_1.txt)

I did some measurements...

**Comment by klartext** [comment]
Today it was fast ;-)

**Comment by klartext** [comment]
Looks as if it is the downloaded size per fragment,  not the speed (aka downloaded size per download time).

**Comment by klartext** [comment]
Histogram of the download speed as reported by yt-dlp:
![speedtest-hist-yt-dlp-output](https://user-images.githubusercontent.com/3165583/139962103-ab120a87-4a44-4be6-b30a-f3e95193b932.png)

**Comment by klartext** [comment]
Summaries in B/s:
```
> summary(s1)
       V1         
 Min.   : 114647  
 1st Qu.:1132462  
 Median :2401239  
 Mean   :2724520  
 3rd Qu.:4299162  
 Max.   :7193231  
> summary(s2)
       V1         
 Min.   : 386202  
 1st Qu.:1239941  
 Median :2642412  
 Mean   :2843995  
 3rd Qu.:4369940  
 Max.   :7696548  
> summary(s3)
       V1          
 Min.   :  186102  
 1st Qu.: 1226834  
 Median : 2589983  
 Mean   : 2779479  
 3rd Qu.: 4225761  
 Max.   :11418993  
>
```

**Comment by klartext** [comment]
OK, one last plot...
![timeline-cutout-speedtest-1](https://user-images.githubusercontent.com/3165583/139963548-21ebb0a8-8135-4ce6-9f6a-a9be8f1b9b03.png)

**Comment by klartext** [comment]
Why has this been closed?
The data shows the output of what yt-dlp THINKS that the download speed is.
The gnome-data AFAIK shows that the download speed is lower than what yt-dlp reports.
At least the display stays at the highest value peak for longer, before the value goes down again.
As far as I can see, there is no reason to close the ticket.

**Comment by pukkandan** [comment]
This should be fixed in https://github.com/yt-dlp/yt-dlp/commit/bd93fd5d45e104561bad919d4775feba869d0145
