### ISSUE TITLE
Extract release_date year into file name

### ISSUE THREAD

**Issue by ACR-Jeff** [yt-dlp/yt-dlp#1522]
### Checklist

- [X] I'm asking a question and not reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

I am downloading movies from Pluto TV. 
The url is example: https://pluto.tv/en/on-demand/movies/buried-2011-1-1 
My code is: yt-dlp --verbos --output "/mnt/Edit Video HD/Movies/%(title)s (%(release_date)s).%(ext)s" "$(xclip -o)"

What I am trying to do is extract/get the year the video was released in my file name as follows above. I have tried everything that I personally can think of how it should be done. Maybe Pluto TV doesn't provide that anywhere other than in the url? Is there any way to extract that into the file name? Thank you.

What other options I have tried:
yt-dlp --verbos --output "/mnt/Edit Video HD/Movies/%(title)s (%(release_date>%Y)s).%(ext)s" "$(xclip -o)"
yt-dlp --verbos --output "/mnt/Edit Video HD/Movies/%(title)s (%(upload_date>%Y)s).%(ext)s" "$(xclip -o)"
yt-dlp --verbos --output "/mnt/Edit Video HD/Movies/%(title)s (%(release_timestamp)s).%(ext)s" "$(xclip -o)"

The output of the file name comes out as: Buried (NA).mp4

**Comment by Ashish0804** [comment]
the extractor doesn't provide it.
There are the available keys
```
        info = {
            'id': video_id,
            'formats': formats,
            'subtitles': subtitles,
            'title': video_json.get('name'),
            'description': video_json.get('description'),
            'duration': float_or_none(video_json.get('duration'), scale=1000),
        }
        if series_name:
            info.update({
                'series': series_name,
                'episode': video_json.get('name'),
                'season_number': int_or_none(video_json.get('season')),
                'episode_number': int_or_none(video_json.get('number')),
            })
```

**Comment by ACR-Jeff** [comment]
> the extractor doesn't provide it. These are the available keys
> 
> ```
>         info = {
>             'id': video_id,
>             'formats': formats,
>             'subtitles': subtitles,
>             'title': video_json.get('name'),
>             'description': video_json.get('description'),
>             'duration': float_or_none(video_json.get('duration'), scale=1000),
>         }
>         if series_name:
>             info.update({
>                 'series': series_name,
>                 'episode': video_json.get('name'),
>                 'season_number': int_or_none(video_json.get('season')),
>                 'episode_number': int_or_none(video_json.get('number')),
>             })
> ```

Thank you for such a quick response, Well then darn, I will just have to create another script that extracts the Year from the url and renames the file accordingly. Thank you again.

**Comment by ACR-Jeff** [comment]
I have created a script for Pluto-TV On Demand Videos, Hope it helps someone else. Not all videos have the Year in the url to extract to the output. So that being said you will still have to manually change some videos to add the year. Also "xclip" installation is required to get this script working the way it is.

`#!/bin/sh

String="$(xclip -o)"
Year=$(echo "$String" | grep -o -E '[0-9]+' | head -1 | sed -e 's/^0\+//')
Path=/YourSavePathHere/

yt-dlp --verbos --output "$Path%(title)s ($Year).%(ext)s" "$String"`
