### ISSUE TITLE
Spankbang - Error 403

### ISSUE THREAD

**Issue by NSFWOrangeCat** [yt-dlp/yt-dlp#1524]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2021.10.22**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Russia

### Description

Error 403 on every video link from Spankbang. 
Examples:
https://spankbang.com/5tuld/video/ass+lava
https://spankbang.com/66m5f/video/swallowed+chanell+heart
https://spankbang.com/672w3/video/bimbo

### Verbose log

```shell
[debug] Command-line config: ['-Uv', 'https://spankbang.com/672w3/video/bimbo']
[debug] Encodings: locale cp1251, fs utf-8, out utf-8 (No ANSI), err utf-8 (No A
NSI), pref cp1251[debug] yt-dlp version 2021.10.22 (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg git-2020-01-10-3d894db, ffprobe git-2020-01-10-3d89
4db
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
yt-dlp is up to date (2021.10.22)
[debug] [SpankBang] Extracting URL: https://spankbang.com/672w3/video/bimbo
[SpankBang] 672w3: Downloading webpage
ERROR: [SpankBang] 672w3: Unable to download webpage: HTTP Error 403: Forbidden
(caused by <HTTPError 403: 'Forbidden'>); please report this issue on  https://g
ithub.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-d
lp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its
 complete output.
  File "yt_dlp\extractor\common.py", line 702, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 3252, in urlopen
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 649, in http_error_default
```

**Comment by TheGrimKeeper** [comment]
FYI, downloads are working again (for me, for now).  This problem was happening a lot a few months ago, and it always seemed to be on SB's side.  Sometimes adding --referer="https://spankbang.com" helped, but not always, and it didn't this time.
