### ISSUE TITLE
How to select language english as default ?

### ISSUE THREAD

**Issue by post-master** [yt-dlp/yt-dlp#1526]
### Checklist

- [X] I'm asking a question and not reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

How to select language English as default?

which argument should I include in the command line for default English audio?

site: curiositystream

**Comment by pukkandan** [comment]
Read https://github.com/yt-dlp/yt-dlp#format-selection

Atleast give more info. Show us the output of `yt-dlp -vUF "YOUR_URL"`

**Comment by mnn** [comment]
For some reason I was always getting Spanish audio when downloading from curiositystream with no format selected (I think this should be improved). I managed to make it download the `en` stream with this: `-f 'bv+ba[language=en]'` (notice it's `language`, not `lang` which is printed by `-F`).
