### ISSUE TITLE
Add Canal Alpha

### ISSUE THREAD

**Issue by vekin03** [yt-dlp/yt-dlp#1528]
### Checklist

- [x] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2021.10.22**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Switzerland

### News
- Full episode (complete daily news): https://www.canalalpha.ch/play/le-journal/episode/24520/jeudi-28-octobre-2021
- Single video: https://www.canalalpha.ch/play/le-journal/topic/24512/la-poste-fait-de-neuchatel-un-pole-cryptographique

### TV Shows
The TV channel has several shows available on their website. For example:
- "**[EUREKA](https://www.canalalpha.ch/play/eureka)**": https://www.canalalpha.ch/play/eureka/episode/24484/ces-innovations-qui-veulent-rendre-lagriculture-plus-durable
- "**[Avec le temps...](https://www.canalalpha.ch/play/avec-le-temps)**": https://www.canalalpha.ch/play/avec-le-temps/episode/23516/redonner-de-leclat-grace-au-polissage

### Description

This is a regional TV channel in Switzerland. Their website is completely free and no membership is required.

Thanks in advance :-)

### Verbose log

```shell
[debug] Command-line config: ['-Uv']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252[debug] yt-dlp version 2021.10.22 (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] exe versions: ffmpeg 4.4-full_build-www.gyan.dev, ffprobe 4.4-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
yt-dlp is up to date (2021.10.22)
```

**Comment by Ashish0804** [comment]
Can u diff b/w these two?
```
Full episode (complete daily news): https://www.canalalpha.ch/play/le-journal/episode/24520/jeudi-28-octobre-2021
Single video: https://www.canalalpha.ch/play/le-journal/topic/24512/la-poste-fait-de-neuchatel-un-pole-cryptographique
```
When u say Full episode u just want that 18 min video, right?
And with Single video u want that 2min 15 sec video?

**Comment by vekin03** [comment]
Exactly, the video as it is presented on their respective pages ;-)

In fact, the "single video" is a extract of a particular topic from the "full episode". In other words, each topic have its own dedicaced page and video.

**Comment by Ashish0804** [comment]
@vekin03 can u provide some urls with subtitles?

**Comment by vekin03** [comment]
@Ashish0804 Unfortunately, I couldn't find any videos with subtitles. I think they don't have any, sorry!
