### ISSUE TITLE
Almost 2 hours delay when recording a dash live stream.

### ISSUE THREAD

**Issue by lfer94** [yt-dlp/yt-dlp#153]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running yt-dlp version **2021.03.03.2**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
yt-dlp -v --allow-unplayable-formats "https://edge-mix01-cen.cvattv.com.ar/live/c3eds/Fox_Sports_Premiun_HD/SA_Live_dash_enc/Fox_Sports_Premiun_HD.mpd" --no-part -o FSP1080p.mp4
[debug] Command-line config: ['-v', '--allow-unplayable-formats', 'https://edge-mix01-cen.cvattv.com.ar/live/c3eds/Fox_Sports_Premiun_HD/SA_Live_dash_enc/Fox_Sports_Premiun_HD.mpd', '--no-part', '-o', 'FSP1080p.mp4']
WARNING: --fixup is ignored since --allow-unplayable-formats was given
[debug] Loading archive file None
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] yt-dlp version 2021.03.03.2 (exe)
[debug] Python version 3.8.7 (CPython 64bit) - Windows-8.1-6.3.9600-SP0
[debug] exe versions: ffmpeg N-100746-gd8a585d4d5, ffprobe N-100746-gd8a585d4d5
[debug] Proxy map: {}
[generic] Fox_Sports_Premiun_HD: Requesting header
WARNING: Falling back on generic information extractor.
[generic] Fox_Sports_Premiun_HD: Downloading webpage
[generic] Fox_Sports_Premiun_HD: Extracting information
[debug] Sort order given by user:
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] Downloading format(s) video=4999936.track_id=10000+audio_20001=145200.track_id=20001
WARNING: You have requested merging of multiple formats while also allowing unplayable formats to be downloaded. The formats won't be merged to prevent data corruption.
[debug] Invoking downloader on 'https://edge-mix01-cen.cvattv.com.ar/live/c3eds/Fox_Sports_Premiun_HD/SA_Live_dash_enc/Fox_Sports_Premiun_HD.mpd'
[dashsegments] Total fragments: 3597
[download] Destination: FSP1080p.fvideo=4999936.track_id=10000.mp4
[download]   0.0% of ~1.95GiB at 435.58KiB/s ETA 07:24:01
ERROR: Interrupted by user

```

## Description

Hello. I've been trying for a while to record a dash live stream using an mpd link, but the downloaded file has a delay of almost 2 hours compared to the TV broadcast (real-time). For example: while the TV is broadcasting [this](https://i.ibb.co/jf47SCF/fsp.png), the downloaded file shows [this](https://i.ibb.co/PzW6dQ9/fspdelay.png) (that was broadcasted 2 hours before on TV).

I've used the `--skip-unavailable-fragments` and `--playlist-end 3597` options thinking it would work, but was unsuccessful.

[This](https://futbollibre.net/embed/?r=Ly90ZWxldmlzaW9ubGlicmUubmV0L2VtYmVkL2RybXBsYXllcl8yLmh0bWw/Z2V0PUx5OWphSEp2YldWallYTjBMbU4yWVhSMGRpNWpiMjB1WVhJdmJHbDJaUzlqTTJWa2N5OUdiM2hmVTNCdmNuUnpYMUJ5WlcxcGRXNWZTRVF2VTBGZlRHbDJaVjlrWVhOb1gyVnVZeTlHYjNoZlUzQnZjblJ6WDFCeVpXMXBkVzVmU0VRdWJYQms=&p=QaJbIEJJ) is the website where I got the mpd link. You probably need a VPN from Argentina to be able to surf it.

...

PS: There are some mpd links with wich I be able to record the real-time broadcast, but they only download a few fragments. For example:

```
yt-dlp -v --allow-unplayable-formats "https://arlocalliveclarovideo.akamaized.net/Content/DASH_DASH_Fk/Live/channel(Fox_Sport_Premium_HD)/manifest.mpd" --no-part -o FSP1080p2.mp4
[debug] Command-line config: ['-v', '--allow-unplayable-formats', 'https://arlocalliveclarovideo.akamaized.net/Content/DASH_DASH_Fk/Live/channel(Fox_Sport_Premium_HD)/manifest.mpd', '--no-part', '-o', 'FSP1080p2.mp4']
WARNING: --fixup is ignored since --allow-unplayable-formats was given
[debug] Loading archive file None
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] yt-dlp version 2021.03.03.2 (exe)
[debug] Python version 3.8.7 (CPython 64bit) - Windows-8.1-6.3.9600-SP0
[debug] exe versions: ffmpeg N-100746-gd8a585d4d5, ffprobe N-100746-gd8a585d4d5
[debug] Proxy map: {}
[generic] manifest: Requesting header
WARNING: Falling back on generic information extractor.
[generic] manifest: Downloading webpage
[generic] manifest: Extracting information
[debug] Sort order given by user:
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] Downloading format(s) 1605722223289item-06item+1605722223289item-07item
WARNING: You have requested merging of multiple formats while also allowing unplayable formats to be downloaded. The formats won't be merged to prevent data corruption.
[debug] Invoking downloader on 'https://arlocalliveclarovideo.akamaized.net/Content/DASH_DASH_Fk/Live/channel(Fox_Sport_Premium_HD)/manifest.mpd'
[dashsegments] Total fragments: 4
[download] Destination: FSP1080p2.f1605722223289item-06item.mp4
[download] 100% of 5.46MiB in 00:11
[debug] Invoking downloader on 'https://arlocalliveclarovideo.akamaized.net/Content/DASH_DASH_Fk/Live/channel(Fox_Sport_Premium_HD)/manifest.mpd'
[dashsegments] Total fragments: 4
[download] Destination: FSP1080p2.mp4.f1605722223289item-07item
[download] 100% of 291.10KiB in 00:14

```

Any solution?

**Comment by pukkandan** [comment]
yt-dlp is downloading whatever the server is sending. If the mpd contains fragments from 2 hours prior, that is what will be downloaded. Nothing can be done from my end

**Comment by lfer94** [comment]
Ok. But in the 2nd case, is there anything that can be done to make the download continuous?

**Comment by pukkandan** [comment]
If the fragments are in fact present in the manifest and the issue is of yt-dlp's parsing, then I can reopen the issue. Attach the manifest so that I can test

**Comment by lfer94** [comment]
Manifest
`https://arlocalliveclarovideo.akamaized.net/Content/DASH_DASH_Fk/Live/channel(Fox_Sport_Premium_HD)/manifest.mpd`

Key
`f18ec7355e0ded70e7db597403dd21cb`

Website
`https://futbollibre.net/embed/?r=Ly9jZG4udHNudC54eXovZW1iZWQva2wuaHRtbD9pZD04ODgxNjA=&p=QaJbIEJJ`

**Comment by pukkandan** [comment]
Do not post key!

I cannot access the link. Attach the actual manifest itself, not the link

**Comment by lfer94** [comment]
Ok, sorry. I'm just an amateur at this, so I assume you mean the manifest.mpd file https://mega.nz/file/uv5UEaqK#PPE-izTodDP0vqYwMgzkJ1vjUnLLjsJ-pqe_jJ8Rr7c

**Comment by pukkandan** [comment]
I understand the issue now. yt-dlp can only download the fragments that are available at the time of parsing and doesn't wait for new fragments to become available. You can try using `--external-downloader ffmpeg`.

If it doesn't work, you can open a new issue with a example URL that is NOT ENCRYPTED

**Comment by lfer94** [comment]
I tried with the encrypted url and a not encrypted url, but sadly it didn't work. I will open a new issue later. Thanks for your time.
