### ISSUE TITLE
Check for new subtitles, don't overwrite when downloaded 

### ISSUE THREAD

**Issue by Wilann** [yt-dlp/yt-dlp#1530]
### Checklist

- [X] I'm asking a question and not reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

I have a question about checking for new subtitles - apologies is this is already stated in the README, but I couldn't find it. 

I would like to download a video as soon as possible, whether or not subtitles have been added yet. When subtitles are added, I would like to downloading them as well, but have the same output name. The output name has `%(upload_date)s`, which I would like to be the same for the video and subtitles, even if they aren't uploaded on the same date. Is there any way to accomplish this? 

Caveat: Once the video/subtitles are downloaded, I don't want them to be changed (even it they're updated from the uploader) 

Here's the my current `config.txt`: 
```
-i ...
-f 'bestvideo+bestaudio'
--merge-output-format mp4
--output "%(upload_date)s - %(uploader)s - %(title)s"

--add-metadata
--embed-thumbnail

--write-sub
--sub-lang en,en-us,en_us,en-US,en_US
--convert-subs vtt
```

Thank you for your time.

**Comment by pukkandan** [comment]
> The output name has %(upload_date)s, which I would like to be the same for the video and subtitles, even if they aren't uploaded on the same date. Is there any way to accomplish this?

This is already the case. `upload_date` always points to the video's upload date, not the subtitle's

> Caveat: Once the video/subtitles are downloaded, I don't want them to be changed (even it they're updated from the uploader)

`--no-overwrite`

**Comment by csadam** [comment]
Please note, that the already downloaded video file will still be changed despite of `--no-overwrite` when `--embed-*` is used.

**Comment by Wilann** [comment]
What's the difference between `--no-overwrite` and `--download-archive`? Does `--no-overwrite` apply to all files, and `--download-archive` to only videos?

**Comment by pukkandan** [comment]
They are totally different things

```
    -w, --no-overwrites              Do not overwrite any files
    --force-overwrites               Overwrite all video and metadata files.
                                     This option includes --no-continue
    --no-force-overwrites            Do not overwrite the video, but overwrite
                                     related files (default)
```
```
    --download-archive FILE          Download only videos not listed in the
                                     archive file. Record the IDs of all
                                     downloaded videos in it
```
Download archive doesn't process the same videos again AT ALL. Doesn't matter if the file still exists or not. the `overwrite` options only looks at whether files with the same name already exists

**Comment by Wilann** [comment]
@csadam Will this be changed anytime soon? If not, is there an alternative I can look into (like a python script to embed images into videos with the same name)?

**Comment by Wilann** [comment]
It seems that when using this config metadata is still being added when its been added before:
```
--merge-output mp4

--add-metadata
--write-thumbnail

--write-sub
--sub-lang en,en-us,en_us,en-US,en_US
--convert-subs vtt

--no-overwrite
```

**Comment by pukkandan** [comment]
Yes, see #1467

**Comment by Wilann** [comment]
So I would have to use `--download-archive` + `--embed-thumbnail` in a single script, then use another script to search for subs? Something like this I think? :
```
--skip-download
--write-sub
--sub-lang en,en-us,en_us,en-US,en_US
--convert-subs vtt
```

**Comment by pukkandan** [comment]
until I figure out a solution for #1467, yes.

If you are dealing with large channels, you will get better performance if you write the channel infojson first and load it back for subsequent runs. But this is something that would take a bit of scripting to achieve

**Comment by Wilann** [comment]
I see. Thank you for letting me know. Will keep track of that issue and hoping it'll be fixed.

**Comment by Wilann** [comment]
@pukkandan An issue I found with using 2 separate script for this case is that: 
- The script using `--download-archive` records the video title 
- Then running the script for downloading subtitles with `--skip-download` will download the subs, but if the uploader changes the video title, the video & subs downloaded will have different titles 

Just something I thought you should be aware of. Hopefully it helps you out a bit.

**Comment by pukkandan** [comment]
>  but if the uploader changes the video title, the video & subs downloaded will have different titles

There is nothing we can do about that

**Comment by Wilann** [comment]
@pukkandan As a follow up, is it possible to use something like `--download-archive` with `--skip-download` and `--write-sub` so that subs are only downloaded once? I tried it and it doesn't seem to work.

**Comment by pukkandan** [comment]
`--force-write-archive`

**Comment by Wilann** [comment]
It seems that this is writing the video ID even if subs weren't downloaded (aka as long as it checks the url). I want to only archive the video IDs where subs have been downloaded.

**Comment by pukkandan** [comment]
>  I want to only archive the video IDs where subs have been downloaded. For the videos where subs haven't been downloaded, I want to be able to check again when running the script again.

That's not possible
