### ISSUE TITLE
Best way to share config files across multiple folders? 

### ISSUE THREAD

**Issue by Wilann** [yt-dlp/yt-dlp#1531]
### Checklist

- [X] I'm asking a question and not reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

I have a question about sharing config files across some, but not all, folders - apologies is this is already stated in the README, but I couldn't find it. 

I currently have a python file I run to use `yt-dlp` on some folders, where their respective config files are in those folders. I end up having many config files with some shared commands and some different commands. 

For example, all my config files have:
```
-f 'bestvideo+bestaudio'
--merge-output-format mp4

--add-metadata
--embed-thumbnail
```
And only some of them have: 
```
--write-sub
--sub-lang en,en-us,en_us,en-US,en_US
--convert-subs vtt
```
They of course all have different:
```
-i ...
```

Because of this, I end up writing the first set of configs in all my files. To make this cleaner, is there a way to "combine" config files for runs? Or is there a better way to accomplish this? 

Thank you for your time.

**Comment by pukkandan** [comment]
The different tiers of config files as mentioned in https://github.com/yt-dlp/yt-dlp#configuration can be stacked together. So you could put all your common configs in a user/portable config file and keep the different options in home config (the one in diff folders).

The order of precedence is the same as the order given in readme. So for example, if you have `-f bv+ba` in user config and `-f 22` in home config, only the `-f22` will be taken.

**Comment by Wilann** [comment]
I can understand the precedence. So the lower the number, the higher the precedence. 

I forgot to mention that I'm running yt-dlp from my python script which is on an external hard drive. Does this make a difference? 

I don't understand the user/home/portable config. 
For user config, what's `%XDG_CONFIG_HOME%/yt-dlp/config`? On MacOS is it `~/.config/yt-dlp/config`? Can I change it to `~/.config/yt-dlp/config.txt`
In home config, what's `-P "home:<path>"`? 
And in portable config, what's "`yt-dlp.conf` in the same directory as the bundled binary" ?

**Comment by Wilann** [comment]
Another question, is it okay to do the following? :
```
yt-dlp -i url --config-location config.txt
```

**Comment by pukkandan** [comment]
> For user config, what's %XDG_CONFIG_HOME%/yt-dlp/config? On MacOS is it ~/.config/yt-dlp/config?

Depends on your setup. Unless you have `XDG_CONFIG_HOME` defined to some other path, yes, its `~/.config/yt-dlp/config`

> Can I change it to ~/.config/yt-dlp/config.txt

No. The standard locations for config files in UNIX are `%XDG_CONFIG_HOME%/yt-dlp/config` and `%XDG_CONFIG_HOME%/yt-dlp.conf`

> In home config, what's -P "home:<path>"?

If u give a path with `-P` (`--paths`) option, that location will be used as the location for home config file

> And in portable config, what's "yt-dlp.conf in the same directory as the bundled binary" ?

exactly what it says. If your binary file is in `downloads`, the file  `downloads/yt-dlp.conf` is searched. If ur binary is in something like `usr/local/bin`, its probably not very useful to you. But this is used by those who keep their binaries in "portable" locations

> Another question, is it okay to do the following? :
> yt-dlp -i url --config-location config.txt

Yes. Note that if u dont specify path, `config.txt` is searched for in the current directory

> I forgot to mention that I'm running yt-dlp from my python script which is on an external hard drive. Does this make a difference?

If you are using `subprocess` or the like to operate yt-dlp CLI, then no. If u r using the API, none of this is relevent and u have to load the config files yourself

**Comment by Wilann** [comment]
@pukkandan Thank you very much for the explanation. Will re-open if I have any other issues.

**Comment by Wilann** [comment]
@pukkandan I'm running MacOS and have my user config file in `~/.config/yt-dlp/config` and am running my command as:
```
yt-dlp -i url --config-location config.txt ~/.config/yt-dlp/config
```

`config.txt`:
```
--merge-output mp4
```

`config`:
```
--add-metadata
--embed-thumbnail
```

It doesn't seem that the user config file is working. Could you let me know what I'm doing wrong?

**Comment by pukkandan** [comment]
Show verbose log

**Comment by Wilann** [comment]
```
$ yt-dlp -i https://www.youtube.com/watch?v=a33jcY-j8Ek --config-location config_video.txt ~/.config/yt-dlp/config --verbose
[debug] Command-line config: ['-i', 'https://www.youtube.com/watch?v=a33jcY-j8Ek', '--config-location', 'config_video.txt', '/Users/wilsonchan/.config/yt-dlp/config', '--verbose']
[debug] Custom config file: config_video.txt
[debug] Custom config: ['--merge-output', 'mp4']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, err UTF-8, pref UTF-8[debug] yt-dlp version 2021.10.22
[debug] Python version 3.7.4 (CPython 64bit) - Darwin-21.1.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome, keyring, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=a33jcY-j8Ek
[youtube] a33jcY-j8Ek: Downloading webpage
[youtube] a33jcY-j8Ek: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] a33jcY-j8Ek: Downloading 1 format(s): 248+251
[debug] Invoking downloader on "https://r3---sn-qpnugpc0uxa-tu1l.googlevideo.com/videoplayback?expire=1636074416&ei=UC-EYcKFDpmztQf9tYLIDg&ip=216.58.16.109&id=o-ABMkKI4QoF5vqcZ26MRa1m5tyIAjoDKx-YAaJcNKQXjW&itag=248&source=youtube&requiressl=yes&mh=MZ&mm=31%2C29&mn=sn-qpnugpc0uxa-tu1l%2Csn-tt1e7n7l&ms=au%2Crdu&mv=m&mvi=3&pl=20&initcwndbps=1222500&vprv=1&mime=video%2Fwebm&gir=yes&clen=96322384&dur=492.925&lmt=1636042075502749&mt=1636052449&fvip=3&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=5535434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRAIge4df-qz6d4pIQaQ_HuCRPiD-kHUVOj2tBK907BOdBA0CID4fFcwL7aO83DCblQ6if8GWCPs5RDP3ps9517VmY7tV&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAJvCl7bFdP1-gDQ68D5qBJP7Nz0C3xjCt7BymxpY_MdDAiEA43wM-IrAZrgrwoU57Qm5RB_yN573ob6ozsAjSGHTdBU%3D"
[download] Destination: 【緊急報告】２週連続で優勝しました！！ [a33jcY-j8Ek].f248.webm
[download] 100% of 91.86MiB in 01:03                  
[debug] Invoking downloader on "https://r3---sn-qpnugpc0uxa-tu1l.googlevideo.com/videoplayback?expire=1636074416&ei=UC-EYcKFDpmztQf9tYLIDg&ip=216.58.16.109&id=o-ABMkKI4QoF5vqcZ26MRa1m5tyIAjoDKx-YAaJcNKQXjW&itag=251&source=youtube&requiressl=yes&mh=MZ&mm=31%2C29&mn=sn-qpnugpc0uxa-tu1l%2Csn-tt1e7n7l&ms=au%2Crdu&mv=m&mvi=3&pl=20&initcwndbps=1222500&vprv=1&mime=audio%2Fwebm&gir=yes&clen=7502675&dur=492.961&lmt=1636029003148507&mt=1636052449&fvip=3&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=5532434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIhAN23MBboMLuwrKI2j3gM9a9-rLkbGbR_bA9br2AaADvgAiAxcHSZ0GWojJ43UBhPMODt9PoHwr7y-yikvcUZdIiS9g%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAJvCl7bFdP1-gDQ68D5qBJP7Nz0C3xjCt7BymxpY_MdDAiEA43wM-IrAZrgrwoU57Qm5RB_yN573ob6ozsAjSGHTdBU%3D"
[download] Destination: 【緊急報告】２週連続で優勝しました！！ [a33jcY-j8Ek].f251.webm
[download] 100% of 7.16MiB in 00:08                   
[Merger] Merging formats into "【緊急報告】２週連続で優勝しました！！ [a33jcY-j8Ek].mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:【緊急報告】２週連続で優勝しました！！ [a33jcY-j8Ek].f248.webm' -i 'file:【緊急報告】２週連続で優勝しました！！ [a33jcY-j8Ek].f251.webm' -c copy -map 0:v:0 -map 1:a:0 'file:【緊急報告】２週連続で優勝しました！！ [a33jcY-j8Ek].temp.mp4'
Deleting original file 【緊急報告】２週連続で優勝しました！！ [a33jcY-j8Ek].f248.webm (pass -k to keep)
Deleting original file 【緊急報告】２週連続で優勝しました！！ [a33jcY-j8Ek].f251.webm (pass -k to keep)
[debug] [generic] Extracting URL: /Users/wilsonchan/.config/yt-dlp/config
ERROR: [generic] '/Users/wilsonchan/.config/yt-dlp/config' is not a valid URL. Set --default-search "ytsearch" (or run  yt-dlp "ytsearch:/Users/wilsonchan/.config/yt-dlp/config" ) to search YouTube
Traceback (most recent call last):
  File "/Users/wilsonchan/opt/anaconda3/lib/python3.7/site-packages/yt_dlp/extractor/common.py", line 593, in extract
    ie_result = self._real_extract(url)
  File "/Users/wilsonchan/opt/anaconda3/lib/python3.7/site-packages/yt_dlp/extractor/generic.py", line 2493, in _real_extract
    % (url, url), expected=True)
yt_dlp.utils.ExtractorError: '/Users/wilsonchan/.config/yt-dlp/config' is not a valid URL. Set --default-search "ytsearch" (or run  yt-dlp "ytsearch:/Users/wilsonchan/.config/yt-dlp/config" ) to search YouTube
Traceback (most recent call last):
  File "/Users/wilsonchan/opt/anaconda3/lib/python3.7/site-packages/yt_dlp/extractor/common.py", line 593, in extract
    ie_result = self._real_extract(url)
  File "/Users/wilsonchan/opt/anaconda3/lib/python3.7/site-packages/yt_dlp/extractor/generic.py", line 2493, in _real_extract
    % (url, url), expected=True)
yt_dlp.utils.ExtractorError: '/Users/wilsonchan/.config/yt-dlp/config' is not a valid URL. Set --default-search "ytsearch" (or run  yt-dlp "ytsearch:/Users/wilsonchan/.config/yt-dlp/config" ) to search YouTube

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/wilsonchan/opt/anaconda3/lib/python3.7/site-packages/yt_dlp/YoutubeDL.py", line 1280, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/wilsonchan/opt/anaconda3/lib/python3.7/site-packages/yt_dlp/YoutubeDL.py", line 1305, in __extract_info
    ie_result = ie.extract(url)
  File "/Users/wilsonchan/opt/anaconda3/lib/python3.7/site-packages/yt_dlp/extractor/common.py", line 610, in extract
    e.msg, video_id=video_id, ie=self.IE_NAME, tb=e.traceback, expected=e.expected, cause=e.cause)
yt_dlp.utils.ExtractorError: [generic] '/Users/wilsonchan/.config/yt-dlp/config' is not a valid URL. Set --default-search "ytsearch" (or run  yt-dlp "ytsearch:/Users/wilsonchan/.config/yt-dlp/config" ) to search YouTube
```

**Comment by pukkandan** [comment]
can u check if `XDG_CONFIG_HOME` is set to some other path on your system? run `echo $XDG_CONFIG_HOME`


btw, why r u passing `~/.config/yt-dlp/config` as an argument?

**Comment by Wilann** [comment]
It returns nothing: 
```
$ echo $XDG_CONFIG_HOME

```

I thought that was how you use the user config. Or is it automatic?

**Comment by pukkandan** [comment]
> I thought that was how you use the user config. Or is it automatic?Cant reproduce your issue.

**Comment by pukkandan** [comment]
> I thought that was how you use the user config. Or is it automatic?

Yes, its automatic

Cant reproduce the issue. Can you make sure it in in fact in the right location? You can check by `head ~/.config/yt-dlp/config`

**Comment by Wilann** [comment]
Ah apologies this was my fault. I used the finder to check the file, and although the path was correct, it was a txt file (shown by the "file type" column) but the finder didn't show the .txt extension. 

Issue fixed. Thank you for all your help.

**Comment by wanghaisheng** [comment]
@Wilann  can you share your config file

**Comment by Wilann** [comment]
@wanghaisheng My config file is literally `config`:
```
--add-metadata
```

**Comment by wanghaisheng** [comment]
this is mine,what I do not figure out is how to search a tag using "#keyword" in youtube to catch all the channel or video metadata @Wilann  
```
ytsearch:"#dog"
-o "./%(extractor_key)s/[%(channel_id)s] %(uploader)s/[%(upload_date)s] %(title)s [%(id)s].%(ext)s"
-ciw
--console-title
--extractor-args "youtube:player_client=android,web;comment_sort=top;max_comments=1000"
--yes-playlist
--remux-video flv>mp4
--merge-output-format mp4
--no-embed-sub
--no-clean-infojson
--write-thumbnail
--sub-lang all
--proxy socks://127.0.0.1:1080
--convert-subtitles srt
--write-description
--write-info-json
--convert-thumbnails png
--no-write-comments
--embed-metadata
--parse-metadata "title:(?s)(?P<meta_title>.+)"
--parse-metadata "uploader:(?s)(?P<meta_artist>.+)"
--parse-metadata " : (?P<meta_synopsis>.*)"
--parse-metadata " : (?P<meta_album>.*)"
--abort-on-unavailable-fragment
--no-write-playlist-metafiles
```

**Comment by pukkandan** [comment]
Update on this: since 06e57990f7b12328a68471309ae460f320006354 (v2022.01.21), you can use multiple `--config-location` and even nest them
