### ISSUE TITLE
Getting 401 while trying to download videos from SlidesLive

### ISSUE THREAD

**Issue by huhlik-cz** [yt-dlp/yt-dlp#1532]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2021.10.22**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Czech Republic

### Description

Hi, I'm not able to download any videos from SlidesLive as it gives me HTTP Error 401: Unauthorized. The video is playable directly from the browser, no login is required. I tried multiple different videos with the same output. Here's what I tried:

https://slideslive.com/38897546
https://slideslive.com/38900146
https://slideslive.com/38946802
https://slideslive.com/38922304

### Verbose log

```shell
yt-dlp -Uv https://slideslive.com/38900146
[debug] Command-line config: ['-Uv', 'https://slideslive.com/38900146']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8[debug] yt-dlp version 2021.10.22
[debug] Python version 3.9.7 (CPython 64bit) - macOS-11.6-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.4.1, ffprobe 4.4.1
[debug] Optional libraries: sqlite
[debug] Proxy map: {}
yt-dlp is up to date (2021.10.22)
[debug] [SlidesLive] Extracting URL: https://slideslive.com/38900146
[SlidesLive] 38900146: Downloading JSON metadata
ERROR: [SlidesLive] 38900146: Unable to download JSON metadata: HTTP Error 401: Unauthorized (caused by <HTTPError 401: 'Unauthorized'>); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
  File "/usr/local/Cellar/yt-dlp/2021.10.22/libexec/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 702, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/Cellar/yt-dlp/2021.10.22/libexec/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 3252, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
```

**Comment by stepp1** [comment]
This seems to be caused by the addition of the query parameter`player_token`.

A valid parameter can be extracted from <div> containing the embedded player.

**Comment by credo99** [comment]
I have the same issue and indeed, there is a authenticity_token in the player frame sourcecode (I don't know if this is the same culprit as above mentioned):

<html>
<body>


<meta name="csrf-param" content="authenticity_token" />
--
  | <meta name="csrf-token" content="p-CmDKIkwtBeOYHIXWP1jidCzy3k2NdiVJXlbe9pNrILukH7K6uvlRzLwmCLLNIsvYbRNpnGupjbBhfNd-5Bag" />


</body>
</html>

**Comment by HobbyistDev** [comment]
From this link (https://slideslive.com/38897546/special-metaprednaska-petra-ludwiga-hodnoty-pro-lepsi-spolecnost), we can get `video_id` from `https://ben.slideslive.com/player/ `.
Here's the output from `https://ben.slideslive.com/player/38897546?player_token=eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTU3MjQ1MzUsImV4cCI6MTY1NTczMTczNSwiaXAiOiIxMjUuMTYyLjI0Ni4xMDciLCJ1IjpudWxsLCJwIjozODg5NzU0NiwibSI6OTM3MywibV9uX2EiOmZhbHNlfQ.jKCpnTonVTaGEzM6240hcf4ro4DwgwCy9EUuBkIOEgA`:
```
#EXTM3U
#EXT-SL-VERSION:1
#EXT-SL-PRESENTATION-ID:38897546
#EXT-SL-PRESENTATION-TITLE:SPECIÁL: Meta-přednáška Petra Ludwiga - Hodnoty pro lepší společnost
#EXT-SL-PRESENTATION-UPDATED-AT:2021-04-18T22:58:35Z
#EXT-SL-PLAYER-TYPE:video_slideshow
#EXT-SL-PRESENTATION-THUMBNAIL:https://cdn.slideslive.com/data/presentations/38897546/slideslive_petr-ludwig_special-metaprednaska-petra-ludwiga-hodnoty-pro-lepsi-spolecnost.jpg?1618786713
#EXT-SL-PLAYLIST-TYPE:vod
#EXT-SL-PRESENTATION-MEDIA-SET-ID:9373
#EXT-SL-VOD-VIDEO-SERVICE-NAME:youtube
#EXT-SL-VOD-VIDEO-ID:jmg02wCJD5M
#EXT-SL-VOD-VIDEO-KEN-ENABLED:
#EXT-SL-VOD-SLIDES-XML-URL:https://slides.slideslive.com/38897546/38897546.xml?1642065757
#EXT-SL-VOD-SLIDES-JSON-URL:https://slides.slideslive.com/38897546/slides.json?1642065757
```
From there we can check the video provider in `#EXT-SL-VOD-VIDEO-SERVICE-NAME` and if the result is `youtube`, we can pass this id in Youtube Extractor. 

We can get the video from webpage too but i think it's not too reliable. The link is in `iframe` tag and we can get the link from `src`

PS: i don't check other link so correct me if i'm wrong

**Comment by robhawkins** [comment]
I'm getting this error too,

> ERROR: [SlidesLive] xxxxxxxx: Unable to download JSON metadata: HTTP Error 401: Unauthorized (caused by <HTTPError 401: 'Unauthorized'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

Is there a way to "bring your own" json? I tried the `--load-info-json` option but that appears to be for something else.

**Comment by ferreirafabio** [comment]
One year later, this problem still exists. In my opinion, it's bold to keep listing SlidesLive as supported here: https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md ;-)
