### ISSUE TITLE
Crunchyroll appears broken.

### ISSUE THREAD

**Issue by klop422** [yt-dlp/yt-dlp#1533]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2021.10.22**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United Kingdom (among others)

### Description

Crunchyroll (both beta and old) both seem to have stopped working due to a certificate verification error. This has happened with every link I've tried.

### Verbose log

```shell
yt-dlp -Uv https://www.crunchyroll.com/en-gb/takt-opdestiny/episode-1-conduct-creed-819675
[debug] Command-line config: ['-Uv', 'https://www.crunchyroll.com/en-gb/takt-opdestiny/episode-1-conduct-creed-819675']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252[debug] yt-dlp version 2021.10.22 (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] exe versions: ffmpeg 2021-10-28-git-e84c83ef98-full_build-www.gyan.dev, ffprobe 2021-10-28-git-e84c83ef98-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
yt-dlp is up to date (2021.10.22)
[debug] [crunchyroll] Extracting URL: https://www.crunchyroll.com/en-gb/takt-opdestiny/episode-1-conduct-creed-819675
[crunchyroll] 819675: Downloading webpage
ERROR: [crunchyroll] 819675: Unable to download webpage: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)> (caused by URLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))
  File "yt_dlp\extractor\common.py", line 702, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 3252, in urlopen
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 563, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 755, in http_error_302
  File "urllib\request.py", line 525, in open
  File "urllib\request.py", line 542, in _open
  File "urllib\request.py", line 502, in _call_chain
  File "yt_dlp\utils.py", line 2874, in https_open
  File "urllib\request.py", line 1357, in do_open
```

**Comment by pukkandan** [comment]
`CERTIFICATE_VERIFY_FAILED` is generally an issue with your system. Try with `--no-check-certificate`

**Comment by klop422** [comment]
My apologies, I tried it and it seemed to work.
