### ISSUE TITLE
Option for aborting due to low disk space

### ISSUE THREAD

**Issue by Zirro** [yt-dlp/yt-dlp#1535]
### Checklist

- [X] I'm reporting a feature request
- [X] I've verified that I'm running yt-dlp version **2021.10.22**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

While downloading large playlists I occasionally run out of disk space. This is undesirable since it brings all processes writing to that particular disk to a halt. It would be useful if yt-dlp had a "`--abort-on-low-disk-space [SIZE]`" option which would check before downloading each video that the free space of the target disk remains above the estimated video size + the size provided by this option. The option could have a fairly safe default value like 15GiB, making the argument optional.

Worth keeping in mind for the implementation is that it should check the disk at the path being written to, which is not necessarily the disk that yt-dlp is running from.

**Comment by Zirro** [comment]
I'd like to work on this when I have some time available (assuming that the concept itself is okay).

**Comment by pukkandan** [comment]
Wouldn't it be easier to just write a wrapper that kills yt-dlp when disk space is low? Such a tool can be used with other programs as well. I don't think it makes sense to implement this as a native option
