### ISSUE TITLE
example of --paths

### ISSUE THREAD

**Issue by AplhaSlayer1964** [yt-dlp/yt-dlp#1536]
### Checklist

- [X] I'm asking a question and not reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

So first my problem is that the file path that my video is saved in is to long for ffmpeg to merge the output to mp4 (windows). So I thought maybe I could use --path as it seems that it downloads and does everything in home or a temp location then moves it to the desired location. if that is correct would you be able to show an example of using it? For me it just seems to download everything to the current working directory and does not move anything. Also for reference I'm using it within a python script, here is the function:
```python
def download_yt_dlp(path, link):
    import yt_dlp
    ydl_opts = {
        "paths": {"%(ext)s" : "{}/%(title)s.%(ext)s".format(path)},
        "noplaylist" : True, 
        "merge_output_format" : "mp4",
        "quiet" : False,
        "verbose": True
    }
    with yt_dlp.YoutubeDL(ydl_opts) as ydl:
        ydl.download([link])
```
I can't just use --output because the input path might be to long for ffmpeg.

**Comment by pukkandan** [comment]
```pt
        "paths": {"temp" : "path/to/temp/folder", "home": "path/to/final/folder"},
```
The paths should be literal, not output templates. Also, I am curious what made u think `%(ext)s` is a valid key?

**Comment by AplhaSlayer1964** [comment]
I was just throwing stuff at it and that was the last thing I tried. Did temp and home first but still wasn't getting the result I wanted. Can you only use output formatting using the cli version?

**Comment by pukkandan** [comment]
output formatting cannot be used in --paths, only in --output

**Comment by pukkandan** [comment]
> Did temp and home first but still wasn't getting the result I wanted

Show verbose log and minimum viable code I can use to reproduce the issue. Otherwise cant help

**Comment by AplhaSlayer1964** [comment]
Well the main problem is with ffmpegs file lengths limitation not yt-dlp.
I'm testing what you gave me right now.

**Comment by AplhaSlayer1964** [comment]
Yes this works! Is there a way to get it to delete the temp folder after? If not that's fine

**Comment by pukkandan** [comment]
From CLI, I guess u can do 
`--exec 'del path/to/temp/folder'`

but since u r using API, probably best to just delete the folder with python code

**Comment by AplhaSlayer1964** [comment]
ok I will do that. Thank you for the quick responses!
