### ISSUE TITLE
Mac - Compile new binary from master before new release version

### ISSUE THREAD

**Issue by pinochico** [yt-dlp/yt-dlp#1539]
### Checklist

- [X] I'm asking a question and not reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

This is guide for other users who are apple dummy like me and don't understand this information from readme:

`DO NOT post unrelated comments here. This has nothing to do with this thread. The instructions for running from master branch are in the README. And if you are not able to follow it, wait for the new release`

If you don't want wait for new binary (maybe new master have new merged PR, but still not created new release)
you can create your custom:

A) Clone this GitHub repo with all branches

`I use app Fork and clone to localhost`

B) Install new version Python 3 and setup as global

https://www.freecodecamp.org/news/python-version-on-mac-update/

> 1) I use Homebrew == install Homebrew on Mac

> 2) I use  pyenv to Manage Your Python Versions == install pyenv

> 3) I use pyenv to install Python > 2.7 == Install python 3.10

> 4) I setup the last version of Python as global == setup Python as global

> 5) I install PyInstaller by Homebrew - https://formulae.brew.sh/formula/pyinstaller

So on my iMac I have now Mac OS Big Sur, homebrew, pyenv, python3, pyinstaller, make (default), zip (default).

Now open clone this project by Fork, open project folder by terminal (you see the same folder as this - https://github.com/yt-dlp/yt-dlp)

Now you have to continue as the same from readme - https://github.com/yt-dlp/yt-dlp#compile for Unix:

> 6) In terminal you write - /usr/bin/python3 devscripts/update-version.py

The version of your localhost project is update to new version by actually date

> 7) In terminal you write - make yt-dlp

The binary (execute Unix file) now will be create in actually folder

> 8) Rename your app yt-dlp in folder usr/local/bin/yt-dlp to usr/local/bin/_yt-dlp

> 9) Copy the new binary app from your fork folder to usr/local/bin/yt-dlp

> 10) Test version by terminal: yt-dlp --version

If you see new version > as from there - https://github.com/yt-dlp/yt-dlp/tags, you are finished

**Comment by pinochico** [comment]
Thanks for this PR for me:

https://github.com/yt-dlp/yt-dlp/issues/1075
https://github.com/yt-dlp/yt-dlp/pull/1221

**Comment by pukkandan** [comment]
So what is the question?

**Comment by pukkandan** [comment]
And why open 2 issues? #1538

**Comment by pinochico** [comment]
Ohhhh, you are very quickly and close task before I finish :)

> So what is the question?

Questions was before in closed discussion, a lot of testing, install and now this is quide for apple dummy as me, how create binary for apple.

> And why open 2 issues? #1538

Sorry, but maybe my iMac, but I don't want create two issues, only one :)
you can delete this other

**Comment by pukkandan** [comment]
From https://github.com/yt-dlp/yt-dlp#with-pip

> You can also install the master branch with:
```
python3 -m pip3 install -U https://github.com/yt-dlp/yt-dlp/archive/master.zip
```
