### ISSUE TITLE
Can someone compile a new release ?

### ISSUE THREAD

**Issue by Palawa** [yt-dlp/yt-dlp#1543]
### Checklist

- [X] I'm asking a question and not reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

Hello!

Is it possible that some of the admins can compile a new release ? 

Regards

Tom

**Comment by pukkandan** [comment]
No. Release will come out when it does. Nobody is going to make special releases for you. Read installation and compilation instructions if you want to do it yourself

Another thing you can do is to fork the project and push master to release in your fork. This will cause the GHA to automatically create a release
