### ISSUE TITLE
Streaming site vier.be moved to goplay.be.

### ISSUE THREAD

**Issue by tsafen** [yt-dlp/yt-dlp#1546]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2021.10.22**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Belgium (have not checked for the rest of Europe)

### Description

The streaming site for the Belgian tv channels Vier and Vijf has been moved from vier.be (and vijf.be, tv.be) to goplay.be. The new site is not supported.

This has [previously been discussed ](https://github.com/ytdl-org/youtube-dl/issues/27993) in the youtube-dl git page.

I'm able to extract the episode when looking for the m3u8 url, the following command runs fine (in contrast with the command included in the log):

yt-dlp -Uv https://stream2-vod.cdn1.sbs.prd.telenet-ops.be/non-geo/BAKE_OFF_VLAANDEREN/S5/volledigeafleveringen/1014745044154552701074761770676694101474/BAKE_OFF_VLAANDEREN_5_1_F0288762/BAKE_OFF_VLAANDEREN_5_1_F0288762.m3u8 -u PRIVATE -p PRIVATE

### Verbose log

```shell
[debug] Command-line config: ['-Uv', 'https://www.goplay.be/video/bake-off-vlaanderen/bake-off-vlaanderen-s5/bake-off-vlaanderen-s5-aflevering-1#autoplay', '-u', 'PRIVATE', '-p', 'PRIVATE']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, err UTF-8, pref UTF-8[debug] yt-dlp version 2021.10.22 (zip)
[debug] Python version 3.6.9 (CPython 64bit) - Linux-4.15.0-156-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.8, ffprobe 3.4.8
[debug] Optional libraries: mutagen, sqlite
[debug] Proxy map: {}
yt-dlp is up to date (2021.10.22)
[debug] [generic] Extracting URL: https://www.goplay.be/video/bake-off-vlaanderen/bake-off-vlaanderen-s5/bake-off-vlaanderen-s5-aflevering-1#autoplay
[generic] bake-off-vlaanderen-s5-aflevering-1#autoplay: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] bake-off-vlaanderen-s5-aflevering-1#autoplay: Downloading webpage
[generic] bake-off-vlaanderen-s5-aflevering-1#autoplay: Extracting information
ERROR: [generic] Unsupported URL: https://www.goplay.be/video/bake-off-vlaanderen/bake-off-vlaanderen-s5/bake-off-vlaanderen-s5-aflevering-1#autoplay
Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 593, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/generic.py", line 3706, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.goplay.be/video/bake-off-vlaanderen/bake-off-vlaanderen-s5/bake-off-vlaanderen-s5-aflevering-1#autoplay
Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 593, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/generic.py", line 3706, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.goplay.be/video/bake-off-vlaanderen/bake-off-vlaanderen-s5/bake-off-vlaanderen-s5-aflevering-1#autoplay

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1280, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1305, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 610, in extract
    e.msg, video_id=video_id, ie=self.IE_NAME, tb=e.traceback, expected=e.expected, cause=e.cause)
yt_dlp.utils.ExtractorError: [generic] Unsupported URL: https://www.goplay.be/video/bake-off-vlaanderen/bake-off-vlaanderen-s5/bake-off-vlaanderen-s5-aflevering-1#autoplay
```

**Comment by pukkandan** [comment]
There is an upstream PR https://github.com/ytdl-org/youtube-dl/pull/27815 by @CNugteren, but it contains GPL code by @michaelarnauts which we cannot merge

**Comment by michaelarnauts** [comment]
> There is an upstream PR [ytdl-org/youtube-dl#27815](https://github.com/ytdl-org/youtube-dl/pull/27815) by @CNugteren, but it contains GPL code by @michaelarnauts which we cannot merge
> 
> PS: Seems only the login code has GPL. So it should be simpler to implement a cookies-based authentication

I'll gladly re-license that piece of code if that can help.

**Comment by emversch** [comment]
any updates on this issue?

**Comment by pateik** [comment]
a few notes:
1) I can provide an account if needed
2) The PR upstream still works, but do check out my comments in that ticket

Is there anything specific still blocking this issue?

**Comment by jeroenj** [comment]
I've prepared the code change (backported from https://github.com/ytdl-org/youtube-dl/pull/27815 and https://github.com/jeroenj/youtube-dl/pull/1) in https://github.com/jeroenj/yt-dlp/pull/1.

I haven't created the PR in this repository yet as I'm not sure what the implications of the GPL-3 license in the authentication code is: https://github.com/ytdl-org/youtube-dl/pull/27815#issuecomment-1083314039.

Would there be anybody that can help with that? Can that code be (easily) relicensed? Should it be an external dependency? 🤷‍♂️

**Comment by pukkandan** [comment]
> Can that code be (easily) relicensed?

It is sufficient for **all contributors** to state that they are willing to re-licence it as `Unlicence`

michaelarnauts has already stated above that he's willing to do so. But I do not know if there are any other contributors to the code

**Comment by basrieter** [comment]
The code originates from me. And I don't mind either. The source has has a link to my original code, that is fine with me.

**Comment by jeroenj** [comment]
Cool, thanks for the confirmation.

I did some more cleanups, fixed the tests, and opened a PR with all those changes: https://github.com/yt-dlp/yt-dlp/pull/3412.
