### ISSUE TITLE
Random "youtube -tag" folder is being created

### ISSUE THREAD

**Issue by Maki711** [yt-dlp/yt-dlp#1550]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2021.10.22**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

When I take a playlist and use `-o "F:/Videos/youtube-dl/%(uploader)s/%(uploader)s/Other/%(title)s.%(ext)s"` it will put everything into `F:\Videos\youtube-dl\NapoleonWils0n\NapoleonWils0n\Other` and the playlist files (description, info.json, jpg) in the same `Other` folder together with all files.
BUT
If I use `-o "F:/Videos/youtube-dl/%(extractor)s/%(uploader)s/Other/%(title)s.%(ext)s"`  it will put the playlist files (description, info.json, jpg) in `F:\Videos\youtube-dl\youtube -tab\NapoleonWils0n\Other`

It looks like it has something to do with `extractor` part and individual files destination:

```
-o "thumbnail:F:/Videos/youtube-dl/%(extractor)s/%(uploader)s/Other/%(title)s/%(title)s.%(ext)s"
-o "description:F:/Videos/youtube-dl/%(extractor)s/%(uploader)s/Other/%(title)s/%(title)s.%(ext)s"
-o "infojson:F:/Videos/youtube-dl/%(extractor)s/%(uploader)s/Other/%(title)s/%(title)s.%(ext)s"
```

It is creating `youtube -tab` for no real reason and puts playlist files into it, clearly visible in log:
```
[info] Writing playlist metadata as JSON to: F:\Videos\youtube-dl\youtube -tab\NapoleonWils0n\Other\Uploads from NapoleonWils0n.info.json
[info] Writing playlist description to: F:\Videos\youtube-dl\youtube -tab\NapoleonWils0n\Other\Uploads from NapoleonWils0n.description
[info] Downloading playlist thumbnail ...
[info] Writing playlist thumbnail to: F:\Videos\youtube-dl\youtube -tab\NapoleonWils0n\Other\Uploads from NapoleonWils0n.jpg
```

Used command in PowerShell:
`Start-Process -FilePath F:\Videos\youtube-dl\yt-dlp.exe -ArgumentList ('--config-location "F:/Videos/youtube-dl/youtube-config_NapoleonWils0n.txt" https://www.youtube.com/playlist?list=UUriRR_CzOny-akXyk1R-oDQ') -NoNewWindow -Wait`

Used config:
```
-f "(bestvideo[vcodec^=av01][height>=1080][fps>30]/bestvideo[vcodec=vp9.2][height>=1080][fps>30]/bestvideo[vcodec=vp9][height>=1080][fps>30]/bestvideo[vcodec^=av01][height>=1080]/bestvideo[vcodec=vp9.2][height>=1080]/bestvideo[vcodec=vp9][height>=1080]/bestvideo[height>=1080]/bestvideo[vcodec^=av01][height>=720][fps>30]/bestvideo[vcodec=vp9.2][height>=720][fps>30]/bestvideo[vcodec=vp9][height>=720][fps>30]/bestvideo[vcodec^=av01][height>=720]/bestvideo[vcodec=vp9.2][height>=720]/bestvideo[vcodec=vp9][height>=720]/bestvideo[height>=720]/bestvideo)+(bestaudio[acodec=opus]/bestaudio)/best" 
--merge-output-format mkv 

--ffmpeg-location "C:\Program Files\ffmpeg\bin" 

--write-auto-sub 
--sub-lang "en,de,sr,hr" 
--convert-subs srt 

--add-metadata 
--write-description
--write-thumbnail
--embed-thumbnail 
--write-info-json  

--sleep-interval 5
--max-sleep-interval 30

--retries 30

--fragment-retries 30
--abort-on-unavailable-fragment

--external-downloader aria2c.exe
--external-downloader-args "-j 8 -x 8 -s 8 -k 2M --file-allocation=none"

-o "F:/Videos/youtube-dl/%(extractor)s/%(uploader)s/Other/%(title)s.%(ext)s" 
-o "thumbnail:F:/Videos/youtube-dl/%(extractor)s/%(uploader)s/Other/%(title)s/%(title)s.%(ext)s"
-o "description:F:/Videos/youtube-dl/%(extractor)s/%(uploader)s/Other/%(title)s/%(title)s.%(ext)s"
-o "subtitle:F:/Videos/youtube-dl/%(extractor)s/%(uploader)s/Other/%(title)s/%(title)s.%(ext)s"
-o "infojson:F:/Videos/youtube-dl/%(extractor)s/%(uploader)s/Other/%(title)s/%(title)s.%(ext)s"
--download-archive "F:/Videos/youtube-dl/downloaded_NapoleonWils0n.txt" 
-i
-v
```

### Verbose log

```shell
PS C:\Users\MJ711> Start-Process -FilePath F:\Videos\youtube-dl\yt-dlp.exe -ArgumentList ('--config-location "F:/Videos/youtube-dl/youtube-config_NapoleonWils0n.txt" https://www.youtube.com/playlist?list=UUriRR_CzOny-akXyk1R-oDQ') -NoNewWindow -Wait
[debug] Command-line config: ['--config-location', 'F:/Videos/youtube-dl/youtube-config_NapoleonWils0n.txt', 'https://www.youtube.com/playlist?list=UUriRR_CzOny-akXyk1R-oDQ']
[debug] Custom config file: F:/Videos/youtube-dl/youtube-config_NapoleonWils0n.txt
[debug] Custom config: ['-f', '(bestvideo[vcodec^=av01][height>=1080][fps>30]/bestvideo[vcodec=vp9.2][height>=1080][fps>30]/bestvideo[vcodec=vp9][height>=1080][fps>30]/bestvideo[vcodec^=av01][height>=1080]/bestvideo[vcodec=vp9.2][height>=1080]/bestvideo[vcodec=vp9][height>=1080]/bestvideo[height>=1080]/bestvideo[vcodec^=av01][height>=720][fps>30]/bestvideo[vcodec=vp9.2][height>=720][fps>30]/bestvideo[vcodec=vp9][height>=720][fps>30]/bestvideo[vcodec^=av01][height>=720]/bestvideo[vcodec=vp9.2][height>=720]/bestvideo[vcodec=vp9][height>=720]/bestvideo[height>=720]/bestvideo)+(bestaudio[acodec=opus]/bestaudio)/best', '--merge-output-format', 'mkv', '--ffmpeg-location', 'C:\\Program Files\\ffmpeg\\bin', '--write-auto-sub', '--sub-lang', 'en,de,sr,hr', '--convert-subs', 'srt', '--add-metadata', '--write-description', '--write-thumbnail', '--embed-thumbnail', '--write-info-json', '--sleep-interval', '5', '--max-sleep-interval', '30', '--retries', '30', '--fragment-retries', '30', '--abort-on-unavailable-fragment', '--external-downloader', 'aria2c.exe', '--external-downloader-args', '-j 8 -x 8 -s 8 -k 2M --file-allocation=none', '-o', 'F:/Videos/youtube-dl/%(extractor)s/%(uploader)s/Other/%(title)s.%(ext)s', '-o', 'thumbnail:F:/Videos/youtube-dl/%(extractor)s/%(uploader)s/Other/%(title)s/%(title)s.%(ext)s', '-o', 'description:F:/Videos/youtube-dl/%(extractor)s/%(uploader)s/Other/%(title)s/%(title)s.%(ext)s', '-o', 'subtitle:F:/Videos/youtube-dl/%(extractor)s/%(uploader)s/Other/%(title)s/%(title)s.%(ext)s', '-o', 'infojson:F:/Videos/youtube-dl/%(extractor)s/%(uploader)s/Other/%(title)s/%(title)s.%(ext)s', '--download-archive', 'F:/Videos/youtube-dl/downloaded_NapoleonWils0n.txt', '-i', '-v']
Das System kann den angegebenen Pfad nicht finden.
WARNING: --downloader-args given without specifying name. The arguments will be given to all external downloaders
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252[debug] yt-dlp version 2021.10.22 (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg 4.3.1-2020-11-19-full_build-www.gyan.dev, ffprobe 4.3.1-2020-11-19-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] Loading archive file 'F:/Videos/youtube-dl/downloaded_NapoleonWils0n.txt'
[debug] [youtube:tab] Extracting URL: https://www.youtube.com/playlist?list=UUriRR_CzOny-akXyk1R-oDQ
[youtube:tab] UUriRR_CzOny-akXyk1R-oDQ: Downloading webpage
[youtube:tab] UUriRR_CzOny-akXyk1R-oDQ: Downloading API JSON with unavailable videos
[download] Downloading playlist: Uploads from NapoleonWils0n
[youtube:tab] UUriRR_CzOny-akXyk1R-oDQ page 1: Downloading API JSON
[youtube:tab] UUriRR_CzOny-akXyk1R-oDQ page 2: Downloading API JSON
[info] Writing playlist metadata as JSON to: F:\Videos\youtube-dl\youtube -tab\NapoleonWils0n\Other\Uploads from NapoleonWils0n.info.json
[info] Writing playlist description to: F:\Videos\youtube-dl\youtube -tab\NapoleonWils0n\Other\Uploads from NapoleonWils0n.description
[info] Downloading playlist thumbnail ...
[info] Writing playlist thumbnail to: F:\Videos\youtube-dl\youtube -tab\NapoleonWils0n\Other\Uploads from NapoleonWils0n.jpg
[youtube:tab] playlist Uploads from NapoleonWils0n: Downloading 260 videos
[download] Downloading video 1 of 260
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=s8-VegsP4VA
[youtube] s8-VegsP4VA: Downloading webpage
[youtube] s8-VegsP4VA: Downloading android player API JSON
[youtube] s8-VegsP4VA: Downloading MPD manifest
[youtube] s8-VegsP4VA: Downloading MPD manifest
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, id
[debug] Downloading subtitles: en, de, sr, hr
[info] s8-VegsP4VA: Downloading 1 format(s): 248+251
[info] Writing video description to: F:\Videos\youtube-dl\youtube\NapoleonWils0n\Other\Mac Monterey qemu virtual machine with kholia osx-kvm\Mac Monterey qemu virtual machine with kholia osx-kvm.description
[info] Writing video subtitles to: F:\Videos\youtube-dl\youtube\NapoleonWils0n\Other\Mac Monterey qemu virtual machine with kholia osx-kvm.en.vtt
```

**Comment by pukkandan** [comment]
The playlist extractor's name is `youtube:tab`. So the `extractor` key resolves to that and since `:` cant be in filename, turns into `youtube -tab`

**Comment by Maki711** [comment]
> 
> 
> The playlist extractor's name is `youtube:tab`. So the `extractor` key resolves to that and since `:` cant be in filename, turns into `youtube -tab`

Ok but why is it marked as invalid when this is clearly a bug and undesired behaviour?
Where in the filename is `:`  ?
What is actually the problem here? How can people bypass this?
This: `thumbnail:` ?

If this is the problem then this whole part should be removed from the documentation:

> Additionally, you can set different output templates for the various metadata files separately from the general output template by specifying the type of file followed by the template separated by a colon :. The different file types supported are subtitle, thumbnail, description, annotation (deprecated), infojson, link, pl_thumbnail, pl_description, pl_infojson, chapter. For example, -o '%(title)s.%(ext)s' -o 'thumbnail:%(title)s\%(title)s.%(ext)s' will put the thumbnails in a folder with the same name as the video. If any of the templates (except default) is empty, that type of file will not be written. Eg: --write-thumbnail -o "thumbnail:" will write thumbnails only for playlists and not for video.

**Comment by MinePlayersPE** [comment]
> Where in the filename is `:`?

> since `:` ***cant*** be in filename,

---

> Why is it defaulting to `youtube -tab` and not just `youtube`? (edited bc the wording is confusing)
Desired behaviour is to have the extractor name and not random -tab added to it.

> The playlist ***extractor's name is youtube:tab.*** So the extractor key resolves to that

**Comment by Maki711** [comment]
> > The playlist _**extractor's name is youtube:tab.**_ So the extractor key resolves to that

Can we please somehow make it resolve to `youtube` and not `youtube -tab` ?

This was not the case with the `youtube-dl`. There the `%(extractor)s` was properly resolved to `youtube` and nothing else.

**Comment by pukkandan** [comment]
For the VIDEOS, the extractor key resolves to `youtube`. For the PLAYLIST, the key resolves to `youtube:tab`. youtube-dl doesnt download playlist metadata, so you just never noticed it. If that is what you want, use `--no-playlist-metafiles`

**Comment by Maki711** [comment]
> 
> 
> For the VIDEOS, the extractor key resolves to `youtube`. For the PLAYLIST, the key resolves to `youtube:tab`. youtube-dl doesnt download playlist metadata, so you just never noticed it. If that is what you want, use `--no-playlist-metafiles`

I see now. This `--no-playlist-metafiles` is a possible work around.
But if somebody would want to have playlist-metafiles for some reason, can we please still get it to place the files in properly named directories?
I understand now that `:` is creating problems because of `youtube:tab` for the playlists but is it really not possible to somehow/somewhere replace the `youtube -tab` with `youtube` ?

**Comment by pukkandan** [comment]
> But if somebody would want to have playlist-metafiles for some reason, can we please still get it to place the files in properly named directories?

It IS the properly named directory according to your template. If you want the folder to be always named `youtube` and not the actual extractor name, use `youtube` in your output template, not `%(extractor)s`

You can also give a different template for the playlist files than for the video files if that is what you want

**Comment by Maki711** [comment]
> It IS the properly named directory according to your template. If you want the folder to be always named `youtube` and not the actual extractor name, use `youtube` in your output template, not `%(extractor)s`
> 
> You can also give a different template for the playlist files than for the video files if that is what you want

I will settle down with `--no-playlist-metafiles` and later work on separate template for playlist files.
BUT in my honest opinion, having `youtube:tab` resolve to `youtube -tab` for a directory is really impropriate.
`youtube -tab` is impropriate name and no user would ever expect or even want that as a directory name, does not matter if the extractor itself is named `youtube:tab`.
**Default behaviour should always be to have the same name a video extractor, at least for the directory destination for end user.** How that is managed inside of the code is not important for end user. Now it just breaks the directory structure and adds unnecessary step by creating a different template only for playlists files. 
But that is just my opinion.

Thanks for the help.
