### ISSUE TITLE
[Youtube] Storyboards

### ISSUE THREAD

**Issue by fboumol** [yt-dlp/yt-dlp#1553]
### Checklist

- [X] I'm reporting a feature request
- [X] I've verified that I'm running yt-dlp version **2021.10.22**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

I am wondering whether it might be possible (from a technical point of view) to add the feature of generating a collage of thumbnails (like in this [movie thumbnailer software](http://moviethumbnail.sourceforge.net/)) from an online video (e.g., for the youtube service) without downloading the full video.

This would be a great way to save bandwidth; this kind of collages (some people have called them video contact sheets) help a lot as a preview feature before deciding to download the full video.

**Comment by pukkandan** [comment]
Are you asking to download storyboards (the thumbnails youtube shows on the timeline), or to literally fetch thumbnails from the video?

If the former, it is a valid feature request since youtube provides this information

For the latter, it may be possible with ffmpeg, but is out of scope for this project

**Comment by fboumol** [comment]
Both options seem interesting to me. I guess the first option seems easier to implement, i.e., adding an option to yt-dlp to generate a storyboard from the "youtube thumbnails shown in the timeline".

As I said before this can be used as a fast way to preview whether it is worth to download the video.

**Comment by pukkandan** [comment]
Related https://github.com/ytdl-org/youtube-dl/pull/14951

**Comment by fboumol** [comment]
By the way, is there any way to get the timestamp (minutes, seconds, ...) of each one of the thumbnails given in the timeline (of a youtube video)? I have looked at the json info that yt-dlp gives and this information is missing. This information would be nice to keep it (in case youtube provides it).

**Comment by pukkandan** [comment]
>  I have looked at the json info that yt-dlp gives and this information is missing. 

What do u mean? story boards isnt even implemented yet 😕

**Comment by fboumol** [comment]
Let me be more precise. If we run (in a terminal)
````
url="https://www.youtube.com/watch?v=n1wePk9ZGs0"
yt-dlp -j --skip-download "${url}" | jq . '[.thumbnails]'
````
we get the list of all (url) thumbnails of this particular video. In particular, one of the thumbnails in the list is 
 > https://i.ytimg.com/vi_webp/n1wePk9ZGs0/sd3.webp

but I do not see any info in the json saying to which minute and second (of the video) corresponds [such thumbnail](https://i.ytimg.com/vi_webp/n1wePk9ZGs0/sd3.webp). I find this information really useful to be written down in the final storyboard (which I already know it is not yet implemented).

**Comment by MarcAbonce** [comment]
> Related [ytdl-org/youtube-dl#14951](https://github.com/ytdl-org/youtube-dl/pull/14951)

By the way, I don't know how much does this fork deviate from the upstream youtube-dl code, but feel free to cherry-pick my PR over there if it works in here.

**Comment by pukkandan** [comment]
@MarcAbonce Thanks, but the youtube code in particular has diverged quite a bit. Also, we have a framework to list storyboards as a format, so I am planning to implement this differently than your PR
