### ISSUE TITLE
Niconico is not accepting username and passwords when listing formats but cookies work

### ISSUE THREAD

**Issue by cg0** [yt-dlp/yt-dlp#1559]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2021.10.22**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United Kingdom

### Description

I am trying to list formats for a Niconico video but even when providing the details for my premium account it's only listing low resolutions however if I ask yt-dlp to grab cookies from Firefox it gives me the full results.

Niconico requires a premium account for high resolutions during peak times

# Examples
## With username and password
```
yt-dlp --username XXX@gmail.com --password XXX -F https://nicovideo.jp/watch/sm37361351
[niconico] Logging in
[niconico] sm37361351: Downloading webpage
[niconico] sm37361351: Downloading video info page
[info] Available formats for sm37361351:
ID                       EXT RESOLUTION | PROTO | VCODEC ACODEC  ABR MORE INFO
------------------------ --- ---------- - ----- - ------ ------ ---- ---------------
h264_360p_low-aac_64kbps mp4 640x360    | dmc   | h264   aac     64k DMC Low-Quality
h264_360p-aac_64kbps     mp4 640x360    | dmc   | h264   aac     64k DMC 360p
```

## With cookies from Firefox
```
yt-dlp -F https://nicovideo.jp/watch/sm37361351 --cookies-from-browser firefox
[Cookies] Extracting cookies from firefox
[Cookies] Extracted 2948 cookies from firefox
[niconico] sm37361351: Downloading webpage
[niconico] sm37361351: Downloading video info page
[info] Available formats for sm37361351:
ID                        EXT RESOLUTION | PROTO | VCODEC ACODEC  ABR MORE INFO
------------------------- --- ---------- - ----- - ------ ------ ---- ---------------
h264_360p_low-aac_64kbps  mp4 640x360    | dmc   | h264   aac     64k DMC Low-Quality
h264_360p_low-aac_192kbps mp4 640x360    | dmc   | h264   aac    192k DMC Low-Quality
h264_360p-aac_64kbps      mp4 640x360    | dmc   | h264   aac     64k DMC 360p
h264_360p-aac_192kbps     mp4 640x360    | dmc   | h264   aac    192k DMC 360p
h264_480p-aac_64kbps      mp4 854x480    | dmc   | h264   aac     64k DMC 480p
h264_480p-aac_192kbps     mp4 854x480    | dmc   | h264   aac    192k DMC 480p
h264_720p-aac_64kbps      mp4 1280x720   | dmc   | h264   aac     64k DMC 720p
h264_720p-aac_192kbps     mp4 1280x720   | dmc   | h264   aac    192k DMC 720p
h264_1080p-aac_64kbps     mp4 1920x1080  | dmc   | h264   aac     64k DMC 1080p
h264_1080p-aac_192kbps    mp4 1920x1080  | dmc   | h264   aac    192k DMC 1080p
```

### Verbose log

```shell
[debug] Command-line config: ['-Uv', '--username', 'PRIVATE', '--password', 'PRIVATE', '-F', 'https://nicovideo.jp/watch/sm37361351']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8[debug] yt-dlp version 2021.10.22
[debug] Python version 3.9.7 (CPython 64bit) - Linux-5.14.15-zen1-1-zen-x86_64-with-glibc2.33
[debug] exe versions: ffmpeg 4.4, ffprobe 4.4, rtmpdump 2.4
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
yt-dlp is up to date (2021.10.22)
[niconico] Logging in
[debug] [niconico] Extracting URL: https://nicovideo.jp/watch/sm37361351
[niconico] sm37361351: Downloading webpage
[niconico] sm37361351: Downloading video info page
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[info] Available formats for sm37361351:
ID                       EXT RESOLUTION | PROTO | VCODEC ACODEC  ABR MORE INFO
------------------------ --- ---------- - ----- - ------ ------ ---- ---------------
h264_360p_low-aac_64kbps mp4 640x360    | dmc   | h264   aac     64k DMC Low-Quality
h264_360p-aac_64kbps     mp4 640x360    | dmc   | h264   aac     64k DMC 360p
```

**Comment by cg0** [comment]
Apologises for the time waste raising this ticket, read through the niconico code and tried to request the login endpoint myself to find this text in the response body "ログイン失敗が続いたため、アカウントがロックされました" letting me know my account was disabled due to login failures, going through the process to unlock my account worked and I'm getting expected output from dlp again.

**Comment by pukkandan** [comment]
@cg0 silently ignoring a message like that from the API is not good. Since u went through the code anyway, can you make a PR to actually display the warning from the API?
