### ISSUE TITLE
[youtube] incomplete download of ended live video (with no error indicated)

### ISSUE THREAD

**Issue by ohhai** [yt-dlp/yt-dlp#1564]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2021.10.22**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Ukraine

### Description

This specific video has length ~10 hours, but downloaded has exactly 4 hours.
Reproduces also for smallest video format, so it's not file size issue.

This specific live stream seems to had interrupt in the middle, but Youtube website shows and plays it with full length.

I did search similar issues here by "incomplete", nothing related found.

### Verbose log

```shell
$  yt-dlp -Uv -f 278+139 https://www.youtube.com/watch?v=Zbbs782FHyo 
[debug] Command-line config: ['-Uv', '-f', '278+139', 'https://www.youtube.com/watch?v=Zbbs782FHyo']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8[debug] yt-dlp version 2021.10.22 (zip)
[debug] Python version 3.10.0 (CPython 64bit) - Linux-5.14.15-300.fc35.x86_64+debug-x86_64-with-glibc2.34
[debug] exe versions: ffmpeg 4.4.1, ffprobe 4.4.1
[debug] Optional libraries: sqlite
[debug] Proxy map: {}
yt-dlp is up to date (2021.10.22)
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=Zbbs782FHyo
[youtube] Zbbs782FHyo: Downloading webpage
[youtube] Zbbs782FHyo: Downloading android player API JSON
[youtube] Zbbs782FHyo: Downloading m3u8 information
[youtube] Zbbs782FHyo: Downloading MPD manifest
[youtube] Zbbs782FHyo: Downloading m3u8 information
[youtube] Zbbs782FHyo: Downloading MPD manifest
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, id
[info] Zbbs782FHyo: Downloading 1 format(s): 278+139
WARNING: Requested formats are incompatible for merge and will be merged into mkv
[debug] Invoking downloader on "https://manifest.googlevideo.com/api/manifest/dash/expire/1636160880/ei/EIGFYd_yDJSFvdIPmceNiAI/ip/176.36.162.42/id/Zbbs782FHyo.1/source/yt_live_broadcast/requiressl/yes/as/fmp4_audio_clear%2Cwebm_audio_clear%2Cwebm2_audio_clear%2Cfmp4_sd_hd_clear%2Cwebm2_sd_hd_clear/force_finished/1/vprv/1/itag_bl/376%2C377%2C384%2C385%2C409%2C410%2C411%2C412%2C557%2C558%2C612%2C613%2C617%2C619%2C623%2C628%2C655%2C656%2C660%2C662%2C666%2C671/keepalive/yes/fexp/24001373%2C24007246/itag/0/playlist_type/DVR/sparams/expire%2Cei%2Cip%2Cid%2Csource%2Crequiressl%2Cas%2Cforce_finished%2Cvprv%2Citag%2Cplaylist_type/sig/AOq0QJ8wRQIgE004sEmYQsi5K2yh0DuytZWAuNutoUk_u4d9arqBYiICIQC-TGFYurLW_sS63zdZBtvNnWvwEJe7UDAWecxmdG3e0g%3D%3D"
[dashsegments] Total fragments: 2880
[download] Destination: Психосоматична медицина - наука та практика (5 листопада 2021 року) [Zbbs782FHyo].f278.webm
[download] 100% of 113.02MiB in 05:18                  
[debug] Invoking downloader on "https://manifest.googlevideo.com/api/manifest/dash/expire/1636160880/ei/EIGFYd_yDJSFvdIPmceNiAI/ip/176.36.162.42/id/Zbbs782FHyo.1/source/yt_live_broadcast/requiressl/yes/as/fmp4_audio_clear%2Cwebm_audio_clear%2Cwebm2_audio_clear%2Cfmp4_sd_hd_clear%2Cwebm2_sd_hd_clear/force_finished/1/vprv/1/itag_bl/376%2C377%2C384%2C385%2C409%2C410%2C411%2C412%2C557%2C558%2C612%2C613%2C617%2C619%2C623%2C628%2C655%2C656%2C660%2C662%2C666%2C671/keepalive/yes/fexp/24001373%2C24007246/itag/0/playlist_type/DVR/sparams/expire%2Cei%2Cip%2Cid%2Csource%2Crequiressl%2Cas%2Cforce_finished%2Cvprv%2Citag%2Cplaylist_type/sig/AOq0QJ8wRQIgE004sEmYQsi5K2yh0DuytZWAuNutoUk_u4d9arqBYiICIQC-TGFYurLW_sS63zdZBtvNnWvwEJe7UDAWecxmdG3e0g%3D%3D"
[dashsegments] Total fragments: 2880
[download] Destination: Психосоматична медицина - наука та практика (5 листопада 2021 року) [Zbbs782FHyo].f139.m4a
[download] 100% of 90.08MiB in 05:58                  
[Merger] Merging formats into "Психосоматична медицина - наука та практика (5 листопада 2021 року) [Zbbs782FHyo].mkv"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:Психосоматична медицина - наука та практика (5 листопада 2021 року) [Zbbs782FHyo].f278.webm' -i 'file:Психосоматична медицина - наука та практика (5 листопада 2021 року) [Zbbs782FHyo].f139.m4a' -c copy -map 0:v:0 -map 1:a:0 'file:Психосоматична медицина - наука та практика (5 листопада 2021 року) [Zbbs782FHyo].temp.mkv'
Deleting original file Психосоматична медицина - наука та практика (5 листопада 2021 року) [Zbbs782FHyo].f139.m4a (pass -k to keep)
Deleting original file Психосоматична медицина - наука та практика (5 листопада 2021 року) [Zbbs782FHyo].f278.webm (pass -k to keep)

$ du -b *
202019519       Психосоматична медицина - наука та практика (5 листопада 2021 року) [Zbbs782FHyo].mkv

$ ffmpeg -i * 2>&1 | grep Duration:
  Duration: 04:00:00.00, start: 0.000000, bitrate: 112 kb/s

$ mediainfo * | grep ^Duration
Duration                                 : 4 h 0 min
Duration                                 : 4 h 0 min
Duration                                 : 3 h 59 min
```

**Comment by pukkandan** [comment]
This is a known issue. You can only download the full video after youtube has finished processing the video (which can take a few hours to couple of days)

**Comment by ohhai** [comment]
Interesting, thank you.
Youtube site is able to provide full video immediately, as far as I see.
So it still not possible to download this full length (which Youtube site offers right now) for some reason?

**Comment by mexus** [comment]
As far as I can tell the video in question has become fully available via yt-dlp :+1:

**Comment by ohhai** [comment]
Yes, but I still have a question how to download full length which is provided (so, it should be possible) by Youtube instantly after live ends.

Besides that it may be worth to add some indication for incomplete downloads since it could lead to data loss (someone thinks that full length is downloaded, but it's not).

**Comment by pukkandan** [comment]
Yes, this is an issue that needs to be fixed. Hence why I keep the issue open

**Comment by dfgyuri** [comment]
I tried using the workaround thats used for ytdl (https://github.com/ytdl-org/youtube-dl/issues/26330) but yt-dlp doesnt seem to read the edited json correctly and still only reads the original 7200 segments (youtube-dl fetches all the segments provided just fine). Is there some change to the way yt-dlp reads the json file?

**Comment by alternistom** [comment]
this is still a thing :(

**Comment by d1nuc0m** [comment]
@pukkandan as this problem is being reported repeatedly, what about adding it to known issues?

**Comment by fireattack** [comment]
I'm surprised this hasn't been fixed since there are workarounds provided in the previous discussions (I meant the one by manuallying adding fragments into JSON). 

Does the `-f 137+140` method mentioned in #3700 always work? I vaguely remembered that I can't get more than 2 hours in some previous attempts without any formats.

**Comment by lazypete365** [comment]
In the meantime, would it be possible to include `isPostLiveDvr` (or something like that) as a valid filter for `--match-filter`? Filtering out problematic videos until they are fully processed would help work around this issue in archival scripts.
