### ISSUE TITLE
Can not download the full plalylist in curiositystream

### ISSUE THREAD

**Issue by post-master** [yt-dlp/yt-dlp#1568]
### Checklist

- [X] I'm reporting a feature request
- [X] I've verified that I'm running yt-dlp version **2021.10.22**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

if I want to download a series I can not download the all episodes. it downloads only the video that I have put into the command line.

here is the log: https://ghostbin.com/jMyOD

**Comment by pukkandan** [comment]
Ofcourse it only downloads the video that you pass the "video" URL the command line

If you want to download a series, pass the URL of the series. It should looks something like `https://curiositystream.com/series/2`

**Comment by post-master** [comment]
Then how can I select the series that I want to download ?
