### ISSUE TITLE
YouTube live streams have incorrect titles

### ISSUE THREAD

**Issue by eniraa** [yt-dlp/yt-dlp#1573]
### Checklist

- [ ] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2021.10.22**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Description

YouTube live stream titles are not extracted as they appear on the website. For instance, when trying to extract the title of https://www.youtube.com/watch?v=5qap5aO4i9A, the result ends up as `lofi hip hop radio - beats to relax/study to 2021-11-06 14:55` rather than `lofi hip hop radio - beats to relax/study to`.

On the command line, it looks like this:

```
[youtube] 5qap5aO4i9A: Downloading webpage
[youtube] 5qap5aO4i9A: Downloading android player API JSON
[youtube] 5qap5aO4i9A: Downloading m3u8 information
[youtube] 5qap5aO4i9A: Downloading m3u8 information
[info] 5qap5aO4i9A: Downloading 1 format(s): 96-hls
[download] Destination: lofi hip hop radio - beats to relax_study to 2021-11-06 14_55 [5qap5aO4i9A].mp4
```

While I don't know how this *should* be fixed, since I haven't taken a look at the code, a temporary fix would be to just remove the date & time from the end of the title.

### Verbose log

```shell
[debug] Command-line config: ['-Uv', 'https://www.youtube.com/watch?v=5qap5aO4i9A']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8[debug] yt-dlp version 2021.10.22
[debug] Python version 3.8.8 (CPython 64bit) - macOS-10.14.6-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.4, ffprobe 4.4, rtmpdump 2.4
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
yt-dlp is up to date (2021.10.22)
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=5qap5aO4i9A
[youtube] 5qap5aO4i9A: Downloading webpage
[youtube] 5qap5aO4i9A: Downloading android player API JSON
[youtube] 5qap5aO4i9A: Downloading m3u8 information
[youtube] 5qap5aO4i9A: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, id
[debug] Default format spec: best/bestvideo+bestaudio
[info] 5qap5aO4i9A: Downloading 1 format(s): 96-hls
[debug] Invoking downloader on "https://manifest.googlevideo.com/api/manifest/hls_playlist/expire/1636246011/ei/m82GYZNmw8WHBvv-l-AH/ip/96.242.228.121/id/5qap5aO4i9A.1/itag/96/source/yt_live_broadcast/requiressl/yes/ratebypass/yes/live/1/sgoap/gir%3Dyes%3Bitag%3D140/sgovp/gir%3Dyes%3Bitag%3D137/hls_chunk_host/rr2---sn-8xgp1vo-ab5s.googlevideo.com/playlist_duration/30/manifest_duration/30/vprv/1/playlist_type/DVR/initcwndbps/8580/mh/30/mm/44/mn/sn-8xgp1vo-ab5s/ms/lva/mv/m/mvi/2/pl/18/dover/11/keepalive/yes/fexp/24001373,24007246/mt/1636224032/sparams/expire,ei,ip,id,itag,source,requiressl,ratebypass,live,sgoap,sgovp,playlist_duration,manifest_duration,vprv,playlist_type/sig/AOq0QJ8wRQIgYFZ2JZVsHpJ1o926V6eyypB2R6_OcH7Yy5XKMREELesCIQDPpAFM2O126WUMlJsMm_4TdBAy1Jh9fo-StgFvIgt2IA%3D%3D/lsparams/hls_chunk_host,initcwndbps,mh,mm,mn,ms,mv,mvi,pl/lsig/AG3C_xAwRgIhAJp54zISv54L-tmNZuDPRMf5m5kz6oRCiRfMWe__pUgQAiEAnzjK5nOmTUGD1TXltqO5TosGDY_58nuagA1G0GPN2Co%3D/playlist/index.m3u8"
[download] Destination: lofi hip hop radio - beats to relax_study to 2021-11-06 14_46 [5qap5aO4i9A].mp4

(the rest is not necessary, as the title has been extracted already)
```

**Comment by pukkandan** [comment]
This is an intentional design decision by youtube-dl devs. https://github.com/ytdl-org/youtube-dl/issues/29293

I disagree with it too, but I'll need to think about changing it since it is technically a backward-incompatible change

**Comment by eniraa** [comment]
I wonder if streams on other sites exhibit the same inaccurate title behavior…

**Comment by pukkandan** [comment]
Not sure if all do, but a lot of them do. You can search the code for `_live_title`

**Comment by pukkandan** [comment]
For compatibility reason, `title` has to keep the timestamp. But now you can use `fulltitle` to get the title without timestamp
