### ISSUE TITLE
Documentation for adding request headers on embedded yt-dlp

### ISSUE THREAD

**Issue by douglas-legulas** [yt-dlp/yt-dlp#1583]
### Checklist

- [X] I'm reporting a feature request
- [X] I've verified that I'm running yt-dlp version **2021.10.22**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

Current documentation: https://github.com/yt-dlp/yt-dlp#embedding-yt-dlp

The CLI lets us add custom headers with the `--add-header` option. There's no documentation for doing this on an embedded python script.

I got this from someone on your Discord channel. This is how I'm adding custom headers before calling the download function. It ain't pretty, but it works. Maybe there's a better way to do this? I suggest we document it anyway.
```py
yt_dlp.utils.std_headers['Cookie'] = 'name=value'
```

**Comment by pukkandan** [comment]
That is in fact the "correct" way. I will add it to the documentation
