### ISSUE TITLE
With API can I get format_id before downloading ?

### ISSUE THREAD

**Issue by nastia-diaphan** [yt-dlp/yt-dlp#1587]
### Checklist

- [X] I'm asking a question and not reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

The question is in the title:

With API, can I get `format_id` (used with out template) before downloading (with `'pre_process'` or alike) ?

Thank you.

**Comment by pukkandan** [comment]
You can do it with a `before_dl` postprocessor. But it may be easier to just pass `download=False` to `extract_info`. See the relevant docstrings for more details

**Comment by nastia-diaphan** [comment]
Thank you @pukkandan, I will explore the two ways.

**Comment by nastia-diaphan** [comment]
Almost done, but I need you again @pukkandan. Thank you

I can get `format_id` with `before_dl` but it seems then too late to set (change) it.

With `extract_info`, I do what I want, but I don't know how to resume download. Can I pass modified info dict to `ydl.download` or must I redo the whole thing (and reload web page) with modified ydl_opts ?

**Comment by pukkandan** [comment]
please explain what exactly you want to do. You asked how to **get** the format_id, so I gave you methods for that. If you want to modify it, you can just modify in the pre_processor and return it. But idk why you would want to do that.

I suspect that you are trying to do something else and are trying to oversimplify the question. Read https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-there-enough-context-in-your-bug-report

**Comment by pukkandan** [comment]
If you are trying to adjust the selected format, see https://github.com/yt-dlp/yt-dlp/issues/1464#issuecomment-954705039

**Comment by pukkandan** [comment]
wait, u r the same guy that asked that question 😕

**Comment by nastia-diaphan** [comment]
:+1: yes it's me

**Comment by nastia-diaphan** [comment]
And yes I oversimplify my request.

I want to have a better control over the formats, and need only audio itag for output file (not the two formats), for compatibility with many already downloaded files. Last but not least, I want to avoid overwriting metadata of already downloaded files.

and many thanks.

**Comment by pukkandan** [comment]
> I want to have a better control over the formats

You can do it with a preprocessor like I explained in the other question. You just need to move the format you want to the end of the list and it will be selected with the default format selector

> need only audio itag for output file (not the two formats), for compatibility with many already downloaded files.

Since u are already writing a pre-processor, you can just take the audio-itag and put it in a new field that can be used in outtmpl. Or you can also just use `%(requested_formats.1.format_id)s` in the output template

> Last but not least, I want to avoid overwriting metadata of already downloaded files.

Use `--download-archive`

**Comment by nastia-diaphan** [comment]
Thank you @pukkandan. You are very speedy.

It is already late here. I will try more tomorrow. but I have time tonight to try`--download-archive`...

**Comment by nastia-diaphan** [comment]
Adding `{'download_archive': True,} to the options, do not the trick. I need help here again. But it is late.... 
Good night or may be good morning.

**Comment by pukkandan** [comment]
that is not how you use archive. read the documentation

**Comment by nastia-diaphan** [comment]
If I have understood, `--download-archive` is not what I need. It store video id in a text file and ydl do not try to download it anymore. It's not my goal because if a better version become available, I want it.

It is why I store the format in the filename. I will download a new version only if it is better that the one on disk. and updating metadata is useless.

Working on pre_processor stage seems effectively be the better way:
- to choose the best format.
- to format the output filename
- to cancel operation if filename already exist.

At the pre_process stage, can I have access to the wonderful table generated by `--list-formats` to display it and/or to save it on disk to verify that my selection is ok ?

**Comment by pukkandan** [comment]
The table is the `formats` in the infodict. If you want to print it in the tabular form, use `self._downloader.list_formats(info_dict)`

**Comment by nastia-diaphan** [comment]
Thank you speedy @pukkandan
