### ISSUE TITLE
[Feature request] Fully download live DASH manifests

### ISSUE THREAD

**Issue by lfer94** [yt-dlp/yt-dlp#159]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running yt-dlp version **2021.03.07**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE

```

## Description

Hello again. I did what you said me in the [issue](https://github.com/yt-dlp/yt-dlp/issues/153) I posted previously, but it didn't worked.

Edited by @pukkandan - Dont post DRM protected content as examples!

And finally tried once again, but with a random Facebook livestream (still live right now). Only 11 fragments have been downloaded.

```
yt-dlp -v --external-downloader ffmpeg --allow-unplayable-formats "https://video.fcor2-1.fna.fbcdn.net/hvideo-ftw-frc/_nc_cat-111/v/rd_iGoW3sG0Bxrk--RU8w/_nc_ohc-BCbNGdpg7GIAX_M89fB/live-dash/dash-abr5/3284853154951411.mpd?_nc_rl=AfBaHoYnb1AS6pinD1U&ms=m_CNP&oh=9b43fc0892e519366ea88ecfcd842c3d&oe=60488B2F" -o FBLIVEfmpeg.mp4
[debug] Command-line config: ['-v', '--external-downloader', 'ffmpeg', '--allow-unplayable-formats', 'https://video.fcor2-1.fna.fbcdn.net/hvideo-ftw-frc/_nc_cat-111/v/rd_iGoW3sG0Bxrk--RU8w/_nc_ohc-BCbNGdpg7GIAX_M89fB/live-dash/dash-abr5/3284853154951411.mpd?_nc_rl=AfBaHoYnb1AS6pinD1U&ms=m_CNP&oh=9b43fc0892e519366ea88ecfcd842c3d&oe=60488B2F', '-o', 'FBLIVEfmpeg.mp4']
[debug] Loading archive file None
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] yt-dlp version 2021.03.07 (exe)
[debug] Python version 3.8.7 (CPython 64bit) - Windows-8.1-6.3.9600-SP0
[debug] exe versions: ffmpeg N-100746-gd8a585d4d5, ffprobe N-100746-gd8a585d4d5
[debug] Proxy map: {}
[generic] 3284853154951411: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 3284853154951411: Downloading webpage
[generic] 3284853154951411: Extracting information
[debug] Sort order given by user:
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] Downloading format(s) dash-lp-pst-v+dash-lp-md-a
WARNING: You have requested merging of multiple formats while also allowing unplayable formats to be downloaded. The formats won't be merged to prevent data corruption.
[debug] Invoking downloader on 'https://video.fcor2-1.fna.fbcdn.net/hvideo-ftw-frc/_nc_cat-111/v/rd_iGoW3sG0Bxrk--RU8w/_nc_ohc-BCbNGdpg7GIAX_M89fB/live-dash/dash-abr5/3284853154951411.mpd?_nc_rl=AfBaHoYnb1AS6pinD1U&ms=m_CNP&oh=9b43fc0892e519366ea88ecfcd842c3d&oe=60488B2F'
[dashsegments] Total fragments: 11
[download] Destination: FBLIVEfmpeg.fdash-lp-pst-v.mp4
[download] 100% of 14.33MiB in 00:28
[debug] Invoking downloader on 'https://video.fcor2-1.fna.fbcdn.net/hvideo-ftw-frc/_nc_cat-111/v/rd_iGoW3sG0Bxrk--RU8w/_nc_ohc-BCbNGdpg7GIAX_M89fB/live-dash/dash-abr5/3284853154951411.mpd?_nc_rl=AfBaHoYnb1AS6pinD1U&ms=m_CNP&oh=9b43fc0892e519366ea88ecfcd842c3d&oe=60488B2F'
[dashsegments] Total fragments: 11
[download] Destination: FBLIVEfmpeg.mp4.fdash-lp-md-a
[download] 100% of 322.30KiB in 00:03
```

I also used every available external downloaders, but always got the same result.

Whatever, here is the mpd file of the facebook live stream. I hope this help to solve it,
[3284853154951411.zip](https://github.com/yt-dlp/yt-dlp/files/6107489/3284853154951411.zip)

**Comment by 2ShedsJackson** [comment]
Have you tried using Streamlink?

**Comment by lfer94** [comment]
> Have you tried using Streamlink?

Yes. Streamlink works with Facebook and Instagram live streams, but I'm interested in be able to download DRM protected streams. Only for personal purposes.

**Comment by robd003** [comment]
@2ShedsJackson Could you share how you linked https://github.com/streamlink/streamlink to yt-dlp?

Does streamlink let you replay a stream from the beginning?

**Comment by 2ShedsJackson** [comment]
> @2ShedsJackson Could you share how you linked [streamlink](https://github.com/streamlink/streamlink) to yt-dlp?
> 
> Does streamlink let you replay a stream from the beginning?

Linked? I merely mentioned it. Streamlink often can capture live streams that youtube-dl etc. can't. Streamlink doesn't replay streams from the beginning.

The point of this issue is that live streams often update their manifests in real time. The last I saw, for some live streams yt-dlp will download a manifest, download the media segments in the manifest, then finish. Streamlink, in contrast, will refresh the manifest over and over and download new segments as they appear.

**Comment by pukkandan** [comment]
https://github.com/yt-dlp/yt-dlp/commit/b67f7757a08d5dd4491db1160c1338cd243e4679 allows DASH manifests to be downloaded with ffmpeg. This allows live dash to be downloaded as well. I consider this an experimental feature though since there are a few potential issues that this could cause. In any case, make sure to test it out and let me know

**Comment by nao20010128nao** [comment]
note for Ubuntu users: Ubuntu 20.04 and later have at least FFmpeg 4.2.

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.2 LTS
Release:        20.04
Codename:       focal

$ apt info ffmpeg
Package: ffmpeg
Version: 7:4.2.4-1ubuntu0.1
Priority: optional
Section: universe/video
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Debian Multimedia Maintainers <debian-multimedia@lists.debian.org>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 2,058 kB
Depends: libavcodec58 (= 7:4.2.4-1ubuntu0.1), libavdevice58 (= 7:4.2.4-1ubuntu0.1), libavfilter7 (= 7:4.2.4-1ubuntu0.1), libavformat58 (= 7:4.2.4-1ubuntu0.1), libavresample4 (= 7:4.2.4-1ubuntu0.1), libavutil56 (= 7:4.2.4-1ubuntu0.1), libc6 (>= 2.29), libpostproc55 (= 7:4.2.4-1ubuntu0.1), libsdl2-2.0-0 (>= 2.0.10), libswresample3 (= 7:4.2.4-1ubuntu0.1), libswscale5 (= 7:4.2.4-1ubuntu0.1)
Suggests: ffmpeg-doc
Breaks: libav-tools (<< 6:12~~), qt-faststart (<< 7:2.7.1-3~), winff (<< 1.5.5-5~)
Replaces: libav-tools (<< 6:12~~), qt-faststart (<< 7:2.7.1-3~)
Homepage: https://ffmpeg.org/
Task: ubuntustudio-video, ubuntustudio-audio, ubuntukylin-desktop, ubuntu-mate-desktop, ubuntu-budgie-desktop
Download-Size: 1,453 kB
APT-Manual-Installed: yes
APT-Sources: http://jp.archive.ubuntu.com/ubuntu focal-updates/universe amd64 Packages
Description: Tools for transcoding, streaming and playing of multimedia files
 FFmpeg is the leading multimedia framework, able to decode, encode, transcode,
 mux, demux, stream, filter and play pretty much anything that humans and
 machines have created. It supports the most obscure ancient formats up to the
 cutting edge.
 .
 This package contains:
  * ffmpeg: a command line tool to convert multimedia files between formats
  * ffplay: a simple media player based on SDL and the FFmpeg libraries
  * ffprobe: a simple multimedia stream analyzer
  * qt-faststart: a utility to rearrange Quicktime files

N: There is 1 additional record. Please use the '-a' switch to see it
```

**Comment by lfer94** [comment]
> 
> 
> [6251555](https://github.com/yt-dlp/yt-dlp/commit/6251555f1c670c66aa781bf9f29e9b5b33d90be1) allows DASH manifests to be downloaded with ffmpeg. This allows live dash to be downloaded as well. I consider this an experimental feature though since there are a few potential issues that this could cause. In any case, make sure to test it out and let me know
> 
> PS: Your ffmpeg must be built with dash support enabled. For youtube dash manifests, it must also be a newer version (4.2, I think)

Sorry for the late reply.

I just tested it and it works, but only if I add `-f bestvideo` because otherwise ffmpeg crashes, although that's probably because my laptop is a piece of sh*t 😅.

Another thing I noticed is that some frames are lost at the beginning of the video, but that is an ffmpeg bug (own experience).

Thank you.

**Comment by danepedersen** [comment]
> > [6251555](https://github.com/yt-dlp/yt-dlp/commit/6251555f1c670c66aa781bf9f29e9b5b33d90be1) allows DASH manifests to be downloaded with ffmpeg. This allows live dash to be downloaded as well. I consider this an experimental feature though since there are a few potential issues that this could cause. In any case, make sure to test it out and let me know
> > PS: Your ffmpeg must be built with dash support enabled. For youtube dash manifests, it must also be a newer version (4.2, I think)
> 
> Sorry for the late reply.
> 
> I just tested it and it works, but only if I add `-f bestvideo` because otherwise ffmpeg crashes, although that's probably because my laptop is a piece of sh*t 😅.
> 
> Another thing I noticed is that some frames are lost at the beginning of the video, but that is an ffmpeg bug (own experience).
> 
> Thank you.

I have a similar bug where when I record a live MPD with FFmpeg I get large swathes of "[mp4 @ 000002622b466e40] Non-monotonous DTS in output stream 0:1; previous: 27732616, current: 27730388; changing to 27732617. This may result in incorrect timestamps in the output file" and the resulting video has lots of freezes (for both audio and video) in it.

Perhaps I should report that as a bug on the FFmpeg issues section if someone hasn't already?
