### ISSUE TITLE
Can I use this library to download unknown type of live sports stream?

### ISSUE THREAD

**Issue by zydjohnHotmail** [yt-dlp/yt-dlp#1590]
### Checklist

- [X] I'm asking a question and not reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

Hello:
I can login to watch some live sports games from one small video web site. But there is no customer service, I don’t know how to set up a customer account.
However, I found that the web site uses JWPlayer to play live videos, and from the web site JavaScript, I found the HLS source seems to be available for all browser without login. It is working for Google Chrome, Microsoft Edge, and Firfox without login.
The following is one of such URL, which I can watch live sport game:
https://bingsport.com/1proxy.php?id=g_1
Other examples like: 
https://bingsport.com/1proxy.php?id=g_2
https://bingsport.com/1proxy.php?id=g_3
......
https://bingsport.com/1proxy.php?id=g_20

Depend on what time you try, in the European nights, there are always some live sports games.
I tried to use Youtube-DL.exe to download it, but I got error message:
[generic] 1proxy: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 1proxy: Downloading webpage
[generic] 1proxy: Extracting information
ERROR: Unsupported URL: https://bingsport.com/1proxy.php?id=g_1
I want to know what type of live stream this URL is using, and how I can download it?
For example, if I want to download this type of live stream and save as an MP4 file in my local disk using this library, what I should do?
Thanks,

**Comment by flashdagger** [comment]
You will need to have installed ffmpeg. Then open the [developer view](https://help.divvyhq.com/hc/en-us/articles/360044771812-How-do-I-use-Inspect-on-Chrome-and-Firefox-) in your browser and look for `playlist.m3u8` url in the _network_ traffic section. With that url you can invoke yt-dlp:
` yt-dlp https://m3u8.1proxy.xyz/media/g_23/playlist.m3u8 --downloader ffmpeg --referer "https://bingsport.com/"`
Don't get confused about the warnings:
`[https @ 0x558beddc1780] Cannot reuse HTTP connection for different host:`

**Comment by zydjohnHotmail** [comment]
Hello:
Thank you very much for your help.  Your command seems working now.  I don't know much about yt-dlp, how I can give the different name for local file (MP4 format).
By the way, I would like to have API of yt-dlp, so I can call API from .NET (C#) in windows.  I want to be able to get events like download completed.
Any suggestions?
Thanks,

**Comment by pukkandan** [comment]
> how I can give the different name for local file (MP4 format).

`--output`. Read the docs

> By the way, I would like to have API of yt-dlp, so I can call API from .NET (C#) in windows. I want to be able to get events like download completed.

the API can only directly be accessed from python. For other languages, you will need to parse the CLI or write some kind of a bridge
