### ISSUE TITLE
Doc is wrong that you cannot install yt-dlp on Termux

### ISSUE THREAD

**Issue by rofrol** [yt-dlp/yt-dlp#1599]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2021.10.22**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

After installing Termux from F-Droid and running `pkg update`, you can install yt-dlp with no problem.

It also works with Termux from Google Play, but you have to update sources manually for `pkg update`.

### Verbose log

```shell
Doc bug
```

**Comment by pukkandan** [comment]
I only meant that **IF** you have trouble installing, u can install with --no-deps. I'll reword the docs to clarify

**Comment by pukkandan** [comment]
actually, I'll just remove the mention of termux altogether
