### ISSUE TITLE
ProsiebenMAXX - Different URLs of different episodes download the same video

### ISSUE THREAD

**Issue by hurda** [yt-dlp/yt-dlp#1600]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2021.10.22**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Austria/Germany

### Description

Trying to download the three episodes of "Astra - Lost in Space"[0] from prosiebemaxx.at/prosiebenmaxx.de results in the wrong video, and it's the same video for all three (`6583934`), which is just around 2 minutes long instead of the episodes' 23 minutes.
Downloading other videos released around the same time, i.e. the Fairy-Tail-URL[1], results in the correct video being downloaded.

While you need to have a free account to play the video in the browser, downloading the videos from this site using yt-dlp worked fine until these three URLs appeared.

Which adds another aspect of this bug, because when using an account, the same Astra-URLs play the proper video in the browser.

EDIT:
I just noticed that the Astra-videos are using DRM in the browser, so I assume it's just some quirk of the website's CMS and the video cannot be downloaded with yt-dlp either way.

[0] 
AT:
https://www.prosiebenmaxx.at/anime/astra-lost-in-space/video/11-planet-camp-ganze-folge
https://www.prosiebenmaxx.at/anime/astra-lost-in-space/video/12-wilderness-ganze-folge
https://www.prosiebenmaxx.at/anime/astra-lost-in-space/video/13-meteor-ganze-folge
DE:
https://www.prosiebenmaxx.de/anime/astra-lost-in-space/video/11-planet-camp-ganze-folge
https://www.prosiebenmaxx.de/anime/astra-lost-in-space/video/12-wilderness-ganze-folge
https://www.prosiebenmaxx.de/anime/astra-lost-in-space/video/13-meteor-ganze-folge

[1]
AT:
https://www.prosiebenmaxx.at/anime/fairy-tail/video/616-folge-242-tartaros-saga-leben-lassen-oder-toeten-ganze-folge
DE:
https://www.prosiebenmaxx.de/anime/fairy-tail/video/616-folge-242-tartaros-saga-leben-lassen-oder-toeten-ganze-folge

### Verbose log

```shell
[debug] Command-line config: ['-fdash-f8-v1-x3+dash-f3-a1-x3', '--no-mtime', '--abort-on-unavailable-fragment', '-o', 'astra_-_lost_in_space_e01.mp4', 'https://www.prosiebenmaxx.at/anime/astra-lost-in-space/video/11-planet-camp-ganze-folge', '-vv']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8 (No ANSI), err utf-8 (No ANSI), pref cp1252[debug] yt-dlp version 2021.10.22 (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg 4.3.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [prosiebensat1] Extracting URL: https://www.prosiebenmaxx.at/anime/astra-lost-in-space/video/11-planet-camp-ganze-folge
[prosiebensat1] anime/astra-lost-in-space/video/11-planet-camp-ganze-folge: Downloading webpage
[prosiebensat1] 6583934: Downloading videos JSON
[prosiebensat1] 6583934: Downloading protocols JSON
[prosiebensat1] 6583934: Downloading urls JSON
[prosiebensat1] 6583934: Downloading MPD manifest
[prosiebensat1] 6583934: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[info] 6583934: Downloading 1 format(s): dash-f8-v1-x3+dash-f3-a1-x3
[debug] Invoking downloader on "http://vas-v4.p7s1video.net/4.0/playlist.mpd?x=01&y=E_1AAZGY-TSfGUegwpzWpZOAqd1hgXtCayftvgVUSyXCblVP2nz4S9RwDk3-3v5nQSk8LoqFkjUN93BNItZvpu4DVCD8Tl-c7bky926thswUnWZhelK5j1-hyoRMOPSzP-7O1xIAUHaX_sd2HQ8UbUvtcV4KCdgEK0lVqHnYGswHEKPSVaDHdSG6sW8TDyrvqAmkY70SkJ7aqiwE8LOhuhrA6B6XuISvugQXMUY7xIRFjeGO6gYXn3B6vf8aO8pZFaNorzRceAM4LabGrSfWRdsoc3SuydrTrN_3aw5kE3ZJ2cMwlUJlr-nJ3yJiJ5vPdNFlB9t_skBV0PGZaERW6u6urIy6vA-f3HGam4UEqgQ"
[dashsegments] Total fragments: 23
[download] Destination: astra_-_lost_in_space_e01.fdash-f8-v1-x3.mp4
[download] 100% of 39.59MiB in 00:11
[debug] Invoking downloader on "http://vas-v4.p7s1video.net/4.0/playlist.mpd?x=01&y=E_1AAZGY-TSfGUegwpzWpZOAqd1hgXtCayftvgVUSyXCblVP2nz4S9RwDk3-3v5nQSk8LoqFkjUN93BNItZvpu4DVCD8Tl-c7bky926thswUnWZhelK5j1-hyoRMOPSzP-7O1xIAUHaX_sd2HQ8UbUvtcV4KCdgEK0lVqHnYGswHEKPSVaDHdSG6sW8TDyrvqAmkY70SkJ7aqiwE8LOhuhrA6B6XuISvugQXMUY7xIRFjeGO6gYXn3B6vf8aO8pZFaNorzRceAM4LabGrSfWRdsoc3SuydrTrN_3aw5kE3ZJ2cMwlUJlr-nJ3yJiJ5vPdNFlB9t_skBV0PGZaERW6u6urIy6vA-f3HGam4UEqgQ"
[dashsegments] Total fragments: 23
[download] Destination: astra_-_lost_in_space_e01.fdash-f3-a1-x3.m4a
[download] 100% of 2.06MiB in 00:02
[Merger] Merging formats into "astra_-_lost_in_space_e01.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:astra_-_lost_in_space_e01.fdash-f8-v1-x3.mp4" -i "file:astra_-_lost_in_space_e01.fdash-f3-a1-x3.m4a" -c copy -map "0:v:0" -map "1:a:0" "file:astra_-_lost_in_space_e01.temp.mp4"
Deleting original file astra_-_lost_in_space_e01.fdash-f3-a1-x3.m4a (pass -k to keep)
Deleting original file astra_-_lost_in_space_e01.fdash-f8-v1-x3.mp4 (pass -k to keep)
```

**Comment by pukkandan** [comment]
Check if the episode downloads when passing cookies

**Comment by pukkandan** [comment]
Closed due to inactivity
