### ISSUE TITLE
yt-dlp for sinusbot

### ISSUE THREAD

**Issue by rikkuzzz** [yt-dlp/yt-dlp#1602]
### Checklist

- [X] I'm asking a question and not reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

Hi, i'm using sinusbot on a server of teamspeak on a VPS with linux with a version of youtube-dl 2021-04-01. From 2 months the download of this version is very slowly. I'm reading on forum of sinusbot that someone it's using yt-dlp and it is solve this problem. Someone can explain how we can change youtube-dl with yt-dlp?

**Comment by pukkandan** [comment]
How would we know? Ask the sinusbot devs
