### ISSUE TITLE
[FranceTV] -10 seconds audio delay on some FranceTV videos with mpv

### ISSUE THREAD

**Issue by Totorrr** [yt-dlp/yt-dlp#1603]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2021.10.22**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

France

### Description

I don't know if this is an mpv or a yt-dlp issue. I already filled a bug report with mpv about it. I also fill one here. 

Please check the original bug report here: 
https://github.com/mpv-player/mpv/issues/9429 

The issue appears on some france.tv videos: 
- I run `mpv 'https://www.france.tv/france-5/vu/2916059-emission-du-lundi-8-novembre-2021.html'`
- The video appears, but the sound is exactly 10 seconds in advance compared to the images.
- Also, when the playback actually starts, the OSD indicates that we are at 00:00:10

However: 

- when I use `yt-dlp 'https://www.france.tv/france-5/vu/2916059-emission-du-lundi-8-novembre-2021.html'`, everything work as expected. 

I think the issue appeared after the latests changes on the francetv extractor. It was working properly a few weeks/months ago. 

Here is how yt-dlp is called from mpv: 
```
[ytdl_hook] Running: yt-dlp --no-warnings -J --flat-playlist --sub-format ass/srt/best --format bestvideo+bestaudio/best --all-subs --no-playlist -- https://www.france.tv/france-5/vu/2916059-emission-du-lundi-8-novembre-2021.html
```

I wonder if there is something wrong with the result of this command that mpv uses to playback. 

I use mpv and yt-dlp latest versions. 

### Verbose log

```shell
Please see verbose mpv log provided in https://github.com/mpv-player/mpv/issues/9429
```

**Comment by pukkandan** [comment]
It is unlikely to be yt-dlp's issue. It is most likely either problem with the data provided by the website, or something with mpv's processing. Try downloading the video and see if you can reproduce the issue

**Comment by pukkandan** [comment]
I see you have said that you cant reproduce from local file in the issue on mpv

> When downloading the video file with yt-dlp, and then playing the resulting local file with mpv, everything works smoothly.

In that case, it is defenitely not a yt-dlp issue

**Comment by pukkandan** [comment]
> Please see verbose mpv log provided in https://github.com/mpv-player/mpv/issues/9429

btw, you have to provide yt-dlp's log for issues. Not mpv's

**Comment by Totorrr** [comment]
Ok @pukkandan, thanks for the feedback!

(I know about the log from yt-dlp, but that's some kind of a grey area where I'm not sure which software is concerned)
