### ISSUE TITLE
In pre_processor, how to cancel any download 

### ISSUE THREAD

**Issue by nastia-diaphan** [yt-dlp/yt-dlp#1604]
### Checklist

- [X] I'm asking a question and not reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

#1587

if it is a general python question, sorry. I'm a noob.

I am lost in `pre_processor.` When the conditions are met, how to cancel the whole process. A little as if {'simulate':True} was present in options (ydl_opts).

Thank you

**Comment by pukkandan** [comment]
u can raise a `PostProcessingError` to cancel the download. But the "correct" way is to use `match_filter` and not PP to selectively download only some videos

**Comment by nastia-diaphan** [comment]
I don't know if I must switch to `match_filter` but I try the pre_processor that is almost done

I am too noob to raise this error:

name 'PostProcessingError' is not defined

```
        self.to_screen('before error')
        raise PostProcessingError("Video file already exist")
        self.to_screen('after error')

```
```
[pre_process] before error
Traceback (most recent call last):
...
    info_dict, _ = self.pre_process(info_dict)
  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/YoutubeDL.py", line 3037, in pre_process
    info = self.run_pp(pp, info)
  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/YoutubeDL.py", line 2990, in run_pp
    files_to_delete, infodict = pp.run(infodict)
  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/postprocessor/common.py", line 22, in run
    ret = func(self, info, *args, **kwargs)
  File "/home/lg/python3/yt-dlp/dn.py", line 310, in run
    raise PostProcessingError("Video file already exist")
NameError: name 'PostProcessingError' is not defined

```

**Comment by pukkandan** [comment]
import it from `yt_dlp.utils`

**Comment by nastia-diaphan** [comment]
Thank you @pukkandan
