### ISSUE TITLE
How I can set a time-out for downloading live stream with the repo?

### ISSUE THREAD

**Issue by zydjohnHotmail** [yt-dlp/yt-dlp#1606]
### Checklist

- [X] I'm asking a question and not reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

Hello:
I can use the repo to download live sports game video from M3U8 link, like this:
C:\Vidoes\Download\> yt-dlp https://xxx.xyz/playlist.m3u8 --downloader ffmpeg -o soccer_game1.mp4
But how I can add some kind of time-out?
For example, usually, one soccer game last less than 2 hours, if I begin to download a soccer live game from an M3U8 link and save to local hard drive.  But most of the time, even after the soccer game finishes, the M3U8 link will still last quite a few hours (some times, it last nearly 9 hours), before the M3U8 link stops.
I want to know if I can add a time-out for 2 hours for one M3U8 link, then after 2 hours, yt-dlp will stop download the live stream, but most importantly, how to keep the downloaded part as a playable MP4 format video?
I have tried to Ctrl-C to stop the downloading, but I got useless file in local hard disk, can’t be played by any media player.
Please advise!
Thanks,

**Comment by zydjohnHotmail** [comment]
I got it already!

**Comment by pukkandan** [comment]
mind sharing your solution so that other people looking for this can benefit?
