### ISSUE TITLE
Is there a way to download password-protected videos from Vimeo?

### ISSUE THREAD

**Issue by ahm750** [yt-dlp/yt-dlp#1610]
### Checklist

- [X] I'm reporting a site feature request
- [X] I've verified that I'm running yt-dlp version **2021.11.10.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

US

### Example URLs

https://vimeo.com/427510332

### Description

Hi,

How can I download Vimeo videos that are password protected? I've used cookies but it's not working.

**Comment by Ashish0804** [comment]
`--video-password`
