### ISSUE TITLE
[YouTube] Infinite loop when downloading channels

### ISSUE THREAD

**Issue by adrgru** [yt-dlp/yt-dlp#1612]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2021.11.10.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Description

When trying to download whole YouTube channels, yt-dlp goes into an infinite loop if it has to load more than one page. It was working yesterday, so there might have been some change on their end. I've got the same problem in Termux on Android, so it can't just be a Windows issue.

This happens for example with [jacksfilms](https://www.youtube.com/user/jacksfilms/videos) (1398 videos), [Danny Gonzalez](https://www.youtube.com/user/ActualDannyGonzalez/videos) (244), and [Daniel Thrasher](https://www.youtube.com/channel/UCnZx--LpG2spgmlxOcC-DRA/videos) (167). The cut-off seems to be at 50, since [Michael Reeves](https://www.youtube.com/c/MichaelReeves/videos) with 47 videos works, while [Primink](https://www.youtube.com/channel/UCAG3zESsD73rnHu0x3DDZHg/videos) with 50 doesn't.

I didn't find anything similar here. I did find [this issue](https://github.com/ytdl-org/youtube-dl/issues/28702) about youtube-dl from April, but it seems to concern playlists and lists an example that doesn't pose problems on my end.

### Verbose log

```shell
yt-dlp -Uv https://www.youtube.com/user/jacksfilms/videos
[debug] Command-line config: ['-Uv', 'https://www.youtube.com/user/jacksfilms/videos']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2021.11.10.1
[debug] Python version 3.9.6 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] exe versions: ffmpeg 2021-08-18-git-dbe40478e2-full_build-www.gyan.dev (setts), ffprobe 2021-08-18-git-dbe40478e2-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
yt-dlp is up to date (2021.11.10.1)
[debug] [youtube:tab] Extracting URL: https://www.youtube.com/user/jacksfilms/videos
[youtube:tab] jacksfilms: Downloading webpage
[debug] [youtube:tab] Final URL: https://www.youtube.com/user/jacksfilms/videos
[download] Downloading playlist: jacksfilms - Videos
[youtube:tab] UCPcFg7aBbaVzXoIKSNqwaww page 1: Downloading API JSON
[youtube:tab] UCPcFg7aBbaVzXoIKSNqwaww page 2: Downloading API JSON
[youtube:tab] UCPcFg7aBbaVzXoIKSNqwaww page 3: Downloading API JSON
[youtube:tab] UCPcFg7aBbaVzXoIKSNqwaww page 4: Downloading API JSON
[youtube:tab] UCPcFg7aBbaVzXoIKSNqwaww page 5: Downloading API JSON
[youtube:tab] UCPcFg7aBbaVzXoIKSNqwaww page 6: Downloading API JSON
[youtube:tab] UCPcFg7aBbaVzXoIKSNqwaww page 7: Downloading API JSON
[youtube:tab] UCPcFg7aBbaVzXoIKSNqwaww page 8: Downloading API JSON
[youtube:tab] UCPcFg7aBbaVzXoIKSNqwaww page 9: Downloading API JSON
[youtube:tab] UCPcFg7aBbaVzXoIKSNqwaww page 10: Downloading API JSON
[youtube:tab] UCPcFg7aBbaVzXoIKSNqwaww page 11: Downloading API JSON
[youtube:tab] UCPcFg7aBbaVzXoIKSNqwaww page 12: Downloading API JSON
[youtube:tab] UCPcFg7aBbaVzXoIKSNqwaww page 13: Downloading API JSON
[youtube:tab] UCPcFg7aBbaVzXoIKSNqwaww page 14: Downloading API JSON
...
[youtube:tab] UCPcFg7aBbaVzXoIKSNqwaww page 380: Downloading API JSON
[youtube:tab] UCPcFg7aBbaVzXoIKSNqwaww page 381: Downloading API JSON
[youtube:tab] UCPcFg7aBbaVzXoIKSNqwaww page 382: Downloading API JSON
[youtube:tab] UCPcFg7aBbaVzXoIKSNqwaww page 383: Downloading API JSON
[youtube:tab] UCPcFg7aBbaVzXoIKSNqwaww page 384: Downloading API JSON

ERROR: Interrupted by user
```

**Comment by coletdjnz** [comment]
Someone bet you to it: https://github.com/yt-dlp/yt-dlp/issues/1611

Issue with YouTube as far as we are aware rn.
