### ISSUE TITLE
MVP, lean, quick, etc cli to reduce "complexity footprint" 

### ISSUE THREAD

**Issue by christianlc-xyz** [yt-dlp/yt-dlp#1617]
### Checklist

- [X] I'm reporting a feature request
- [X] I've verified that I'm running yt-dlp version **2021.11.10.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

Hey guys, first and most importantly, your tool works, so thank you for that. Second, as far as CLI's go, its about as feature rich as openssl, awscli, ffmpeg, etc - you get the idea. Those tools address a complex problem set, where the granularity they provide is easier to justify; here though, i would imagine that the 5 9's of use cases could best be described as: download video at given $uri, at the best quality available.. and done.  

Wireguard's `wg` tool comes with the purposefully limited `wg-quick`, that thus far has allowed me to never use `wg` or think about setting up interfaces and routes. A *quick* tool here would benefit the end user, whom i am guessing most are not cli proficient, as well as save you guys from having to deal with all of the stupid, stupid, moronic, lazy, hyper aggressive, overly dramatic and selfish requests that inevitably come when releasing a tool to the end consumer. 

Anyways, I could be completely wrong, but speaking as someone with a couple decades of experience, I was shocked by the number of flags available; I realize that you don't own that, from a legacy perspective, but its yours now :)

cheers

**Comment by nyuszika7h** [comment]
> i would imagine that the 5 9's of use cases could best be described as: download video at given $uri, at the best quality available.. and done.

Indeed. For those use cases you need nothing more than:
```
yt-dlp "https://example.com"
```
Maybe `--cookies-from-browser chrome`, `--cookies cookies.txt`, `-u username -p password`. That's about it. The default is already to get the best available quality in the majority of cases (though sometimes it can't be objectively determined, e.g. when there are different codecs.)

**Comment by pukkandan** [comment]
So, what exactly are you requesting?

**Comment by Ashish0804** [comment]
>  selfish requests that inevitably come when releasing a tool to the end consumer.

r/SelfAwarewolves 😄
