### ISSUE TITLE
With API, is it realy possible to select format to download at pre_processor stage ?

### ISSUE THREAD

**Issue by nastia-diaphan** [yt-dlp/yt-dlp#1619]
### Checklist

- [x] I'm asking a question and not reporting a bug/feature request
- [x] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [x] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [x] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

It is impossible with some selection as` bv+wa` or `wv+ba`in ytd_opts to avoid hybrid container mkv or the need to re-encoding .

@pukkandan at #1464 suggest to me to use post_processor at pre_process stage and write for me some piece of code to begin with.

If I have understood, this piece of code has two parts.
- a elegant algorithm to select format
- a trick to force yt-dlp to take this format.

The first part is probably working, I don't know because I use my own, but I can't get the second part to work.

First and without the trick, I thought that this will be very easy, because I can modify ytd_opts at pre_process stage. for example, I define the folder where to download the video, and add that path in info_dict with the key `folder`. It is magic, the key `%(folder)s` in output template is then the path. But this doesn't work for the key `format_id` that I also use in the output template. The template keep the value defined by the option `wv+ba`. If I put the key `{'format': '%(format_id)s'}` to define format in ytd_opts, it throw a `SyntaxError: Invalid format specification: Unexpected "("`

Then, back to the trick of @pukkandan :
He add the selected format to the end of `info['formats']` because last is the best. I can't get it to work.

Here is some piece of code where I replace `info['formats']`with only to value: one audio format and one video (each is the last of course). Here with video_id LeuPYxs6PYs, I try to get the best audio (id='251') and then the worst webm video (id='278')

```
ydl_opts = {
    'simulate': True,
    'quiet': False,
    'outtmpl': '/%(folder)s/%(upload_date)s.%(id)s.%(format_id)s.%(ext)s',
    'format': 'bv*+wa',
}

class pre_processPP(PostProcessor):
    def run(self, info):
        myAudio = next(f for f in info['formats'] if f['format_id'] == '251')
        myVideo = next(f for f in info['formats'] if f['format_id'] == '278')
        self.to_screen('all formats:')
        self._downloader.list_formats(info)
        info['formats'] = [myAudio,myVideo]
        info['folder'] = 'myPath' # this does work in template
        info['format_id'] = '278+251' # this does NOT work in template
        self.to_screen('only selected formats:')
        self._downloader.list_formats(info)

        return [], info

def main():        
    with yt_dlp.YoutubeDL(ydl_opts) as ydl:
        ydl.add_post_processor(pre_processPP(), 'pre_process')
        ydl.download(['https://www.youtube.com/watch?v=LeuPYxs6PYs'])
```
and the result
```
~$ test.py LeuPYxs6PYs
python.3.8.10
yt_dlp 2021.10.22
video_id: LeuPYxs6PYs
[youtube] LeuPYxs6PYs: Downloading webpage
[youtube] LeuPYxs6PYs: Downloading android player API JSON
[pre_process] all formats:
[info] Available formats for LeuPYxs6PYs:
ID  EXT  RESOLUTION FPS |  FILESIZE   TBR PROTO | VCODEC          VBR ACODEC     ABR  ASR    MORE INFO
--- ---- ---------- --- - --------- ----- ----- - ------------- ----- --------- ---- ------- -----------------
139 m4a  audio only     |  1.83MiB    48k https |                     mp4a.40.5  48k 22050Hz low, m4a_dash
249 webm audio only     |  1.89MiB    50k https |                     opus       50k 48000Hz low, webm_dash
250 webm audio only     |  2.52MiB    67k https |                     opus       67k 48000Hz low, webm_dash
140 m4a  audio only     |  4.85MiB   129k https |                     mp4a.40.2 129k 44100Hz medium, m4a_dash
251 webm audio only     |  5.01MiB   133k https |                     opus      133k 48000Hz medium, webm_dash
17  3gp  176x144    6   |  2.95MiB    78k https | mp4v.20.3       78k mp4a.40.2   0k 22050Hz 144p
394 mp4  256x144    25  |  2.35MiB    62k https | av01.0.00M.08   62k                        144p, mp4_dash
160 mp4  256x144    25  |  2.01MiB    53k https | avc1.4d400c     53k                        144p, mp4_dash
278 webm 256x144    25  |  3.11MiB    82k https | vp9             82k                        144p, webm_dash
395 mp4  426x240    25  |  3.95MiB   105k https | av01.0.00M.08  105k                        240p, mp4_dash
133 mp4  426x240    25  |  3.12MiB    83k https | avc1.4d4015     83k                        240p, mp4_dash
242 webm 426x240    25  |  4.55MiB   121k https | vp9            121k                        240p, webm_dash
396 mp4  640x360    25  |  7.64MiB   204k https | av01.0.01M.08  204k                        360p, mp4_dash
134 mp4  640x360    25  |  5.65MiB   150k https | avc1.4d401e    150k                        360p, mp4_dash
18  mp4  640x360    25  |  18.88MiB  504k https | avc1.42001E    504k mp4a.40.2   0k 44100Hz 360p
243 webm 640x360    25  |  7.61MiB   203k https | vp9            203k                        360p, webm_dash
397 mp4  854x480    25  |  13.71MiB  366k https | av01.0.04M.08  366k                        480p, mp4_dash
135 mp4  854x480    25  |  8.55MiB   228k https | avc1.4d401e    228k                        480p, mp4_dash
244 webm 854x480    25  |  11.51MiB  307k https | vp9            307k                        480p, webm_dash
398 mp4  1280x720   25  |  27.58MiB  736k https | av01.0.05M.08  736k                        720p, mp4_dash
136 mp4  1280x720   25  |  15.68MiB  418k https | avc1.4d401f    418k                        720p, mp4_dash
22  mp4  1280x720   25  |            547k https | avc1.64001F    547k mp4a.40.2   0k 44100Hz 720p
247 webm 1280x720   25  |  20.16MiB  538k https | vp9            538k                        720p, webm_dash
399 mp4  1920x1080  25  |  49.85MiB 1331k https | av01.0.08M.08 1331k                        1080p, mp4_dash
137 mp4  1920x1080  25  |  39.11MiB 1044k https | avc1.640028   1044k                        1080p, mp4_dash
248 webm 1920x1080  25  |  45.86MiB 1224k https | vp9           1224k                        1080p, webm_dash
[pre_process] only selected formats:
[info] Available formats for LeuPYxs6PYs:
ID  EXT  RESOLUTION FPS |  FILESIZE   TBR PROTO | VCODEC   VBR ACODEC  ABR  ASR    MORE INFO
--- ---- ---------- --- - --------- ----- ----- - ------ ----- ------ ---- ------- -----------------
251 webm audio only     |  5.01MiB   133k https |              opus   133k 48000Hz medium, webm_dash
278 webm 256x144    25  |  3.11MiB    82k https | vp9      82k                     144p, webm_dash
[info] LeuPYxs6PYs: Downloading 1 format(s): 248+139
```
As we can see yt-dlp still download 248+139, what it has selected with option `wv+ba` (not bad in this case), but not what I expected.

**Comment by pukkandan** [comment]
Before I answer this, did you first try the code I gave you in https://github.com/yt-dlp/yt-dlp/issues/1464#issuecomment-954705039?

**Comment by nastia-diaphan** [comment]
no, I will...

**Comment by nastia-diaphan** [comment]
ok, you are right, your selection is downloaded...

I must work a little more

Thank you and sorry @pukkandan 

I come back....

**Comment by pukkandan** [comment]
Try changing `info['formats'] = [myAudio,myVideo]` to `info['formats'][:] = [myAudio,myVideo]`

Also, I will soon push a new and simpler way to achieve this. Probably wont be usefull to you since you have already implemented this, but hopefully helps the next guy

**Comment by nastia-diaphan** [comment]
Thank you @pukkandan, you was right, is it possible and your code is beautiful.
```
        info['formats'][:] = [myAudio,myVideo]
```
work like a charm. I would like to understand.
and the outtmpl is updated :+1: 

You are the King

**Comment by pukkandan** [comment]
the formats have to be replaced in-place. This is the python syntax to do so. Google it for better explaination
