### ISSUE TITLE
What are the plans for cbs vs paramount plus extractors - found a 'page limit' in the API of 50

### ISSUE THREAD

**Issue by mshiels** [yt-dlp/yt-dlp#1620]
### Checklist

- [X] I'm asking a question and not reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

So in switching some of my shows from CBS to paramount plus URLs I found that no matter what it was only giving 50 shows - and somewhat random it seemed.  Ends up the API request submitted says 100000 to download but internally they must max(50) limit it.  The API does return the total count, so I was just about to code up a change to loop over things 50 at a time etc. 

But then I realized there was some discussion I saw about getting rid of paramount plus extractor and going back to robustify(?) the CBS one instead.   So my question is more on direction here.  I am sure I can do up the paramount change, but don't really want to waste the time if it will be just tossed away soon, right?

**Comment by pukkandan** [comment]
Not sure. This discussion should be continued in #1466
