### ISSUE TITLE
[Discovery+] Using US XFR for other countries

### ISSUE THREAD

**Issue by rafaelalbino88** [yt-dlp/yt-dlp#1623]
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2021.11.10.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Brazil

### Example URLs

- Single video: https://www.discoveryplus.com/br/video/90-dias-para-casar-antes-dos-90-dias-tlc-br/triangulo-amoroso

### Description

Support Request for Discoveryplus Brazil

### Verbose log

```shell
[debug] Command-line config: ['--cookies', 'cookies.txt', '--verbose', 'https://www.discoveryplus.com/br/video/90-dias-para-casar-antes-dos-90-dias-tlc-br/triangulo-amoroso']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2021.11.10.1 (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] exe versions: none
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [DiscoveryPlus] Extracting URL: https://www.discoveryplus.com/br/video/90-dias-para-casar-antes-dos-90-dias-tlc-br/triangulo-amoroso
[debug] Using fake IP 6.252.32.205 (US) as X-Forwarded-For
[DiscoveryPlus] 90-dias-para-casar-antes-dos-90-dias-tlc-br/triangulo-amoroso: Downloading JSON metadata
ERROR: [DiscoveryPlus] 90-dias-para-casar-antes-dos-90-dias-tlc-br/triangulo-amoroso: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output. (caused by <HTTPError 404: 'Not Found'>); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
  File "yt_dlp\extractor\common.py", line 713, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 3295, in urlopen
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 649, in http_error_default
```

**Comment by pukkandan** [comment]
Try adding `--no-geo-bypass`. It **may** help to work around the issue

**Comment by rafaelalbino88** [comment]
Worked! Thanks!

**Comment by pukkandan** [comment]
Don't close the issue. That was just a workaround. yt-dlp should be able to figure out on its own that a US XFR shouldnt be used here

**Comment by gergles** [comment]
It's also using a US XFR inside the US unnecessarily, which causes Discovery+ to return a 404 even if the content exists. Here's a run without --no-geo-bypass:
```
% ./yt-dlp --verbose --cookies-from-browser brave "https://www.discoveryplus.com/video/battle-for-the-bird-us/battle-for-the-bird"
[debug] Command-line config: ['--verbose', '--cookies-from-browser', 'brave', 'https://www.discoveryplus.com/video/battle-for-the-bird-us/battle-for-the-bird']
[Cookies] Extracting cookies from brave
[debug] Extracting cookies from: "/Users/me/Library/Application Support/BraveSoftware/Brave-Browser/Default/Cookies"
[debug] using find-generic-password to obtain password
[Cookies] Extracted 268 cookies from brave
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2021.11.10.1 (zip)
[debug] Python version 3.8.2 (CPython 64bit) - macOS-11.6-arm64-arm-64bit
[debug] exe versions: none
[debug] Optional libraries: Crypto, sqlite
[debug] Proxy map: {}
[debug] [DiscoveryPlus] Extracting URL: https://www.discoveryplus.com/video/battle-for-the-bird-us/battle-for-the-bird
[debug] Using fake IP 6.194.37.198 (US) as X-Forwarded-For
[DiscoveryPlus] battle-for-the-bird-us/battle-for-the-bird: Downloading JSON metadata
ERROR: [DiscoveryPlus] battle-for-the-bird-us/battle-for-the-bird: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output. (caused by <HTTPError 404: 'Not Found'>); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
  File "./yt-dlp/yt_dlp/extractor/common.py", line 713, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "./yt-dlp/yt_dlp/YoutubeDL.py", line 3295, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
```

And here is (a successful one) with it:
```
% ./yt-dlp --no-geo-bypass --verbose --cookies-from-browser brave "https://www.discoveryplus.com/video/battle-for-the-bird-us/battle-for-the-bird"
[debug] Command-line config: ['--no-geo-bypass', '--verbose', '--cookies-from-browser', 'brave', 'https://www.discoveryplus.com/video/battle-for-the-bird-us/battle-for-the-bird']
[Cookies] Extracting cookies from brave
[debug] Extracting cookies from: "/Users/me/Library/Application Support/BraveSoftware/Brave-Browser/Default/Cookies"
[debug] using find-generic-password to obtain password
[Cookies] Extracted 268 cookies from brave
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2021.11.10.1 (zip)
[debug] Python version 3.8.2 (CPython 64bit) - macOS-11.6-arm64-arm-64bit
[debug] exe versions: none
[debug] Optional libraries: Crypto, sqlite
[debug] Proxy map: {}
[debug] [DiscoveryPlus] Extracting URL: https://www.discoveryplus.com/video/battle-for-the-bird-us/battle-for-the-bird
[DiscoveryPlus] battle-for-the-bird-us/battle-for-the-bird: Downloading JSON metadata
[DiscoveryPlus] 3840016: Downloading JSON metadata
[DiscoveryPlus] battle-for-the-bird-us/battle-for-the-bird: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: best/bestvideo+bestaudio
[info] 3840016: Downloading 1 format(s): hls-5273
[debug] Invoking downloader on "https://content-ause1-ur-discovery1.uplynk.com
[snipped]
```

**Comment by sandrosg2018** [comment]
> It's also using a US XFR inside the US unnecessarily, which causes Discovery+ to return a 404 even if the content exists. Here's a run without --no-geo-bypass:
> 
> ```
> % ./yt-dlp --verbose --cookies-from-browser brave "https://www.discoveryplus.com/video/battle-for-the-bird-us/battle-for-the-bird"
> [debug] Command-line config: ['--verbose', '--cookies-from-browser', 'brave', 'https://www.discoveryplus.com/video/battle-for-the-bird-us/battle-for-the-bird']
> [Cookies] Extracting cookies from brave
> [debug] Extracting cookies from: "/Users/me/Library/Application Support/BraveSoftware/Brave-Browser/Default/Cookies"
> [debug] using find-generic-password to obtain password
> [Cookies] Extracted 268 cookies from brave
> [debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
> [debug] yt-dlp version 2021.11.10.1 (zip)
> [debug] Python version 3.8.2 (CPython 64bit) - macOS-11.6-arm64-arm-64bit
> [debug] exe versions: none
> [debug] Optional libraries: Crypto, sqlite
> [debug] Proxy map: {}
> [debug] [DiscoveryPlus] Extracting URL: https://www.discoveryplus.com/video/battle-for-the-bird-us/battle-for-the-bird
> [debug] Using fake IP 6.194.37.198 (US) as X-Forwarded-For
> [DiscoveryPlus] battle-for-the-bird-us/battle-for-the-bird: Downloading JSON metadata
> ERROR: [DiscoveryPlus] battle-for-the-bird-us/battle-for-the-bird: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output. (caused by <HTTPError 404: 'Not Found'>); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
>   File "./yt-dlp/yt_dlp/extractor/common.py", line 713, in _request_webpage
>     return self._downloader.urlopen(url_or_request)
>   File "./yt-dlp/yt_dlp/YoutubeDL.py", line 3295, in urlopen
>     return self._opener.open(req, timeout=self._socket_timeout)
>   File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 531, in open
>     response = meth(req, response)
>   File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 640, in http_response
>     response = self.parent.error(
>   File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 569, in error
>     return self._call_chain(*args)
>   File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 502, in _call_chain
>     result = func(*args)
>   File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 649, in http_error_default
>     raise HTTPError(req.full_url, code, msg, hdrs, fp)
> ```
> 
> And here is (a successful one) with it:
> 
> ```
> % ./yt-dlp --no-geo-bypass --verbose --cookies-from-browser brave "https://www.discoveryplus.com/video/battle-for-the-bird-us/battle-for-the-bird"
> [debug] Command-line config: ['--no-geo-bypass', '--verbose', '--cookies-from-browser', 'brave', 'https://www.discoveryplus.com/video/battle-for-the-bird-us/battle-for-the-bird']
> [Cookies] Extracting cookies from brave
> [debug] Extracting cookies from: "/Users/me/Library/Application Support/BraveSoftware/Brave-Browser/Default/Cookies"
> [debug] using find-generic-password to obtain password
> [Cookies] Extracted 268 cookies from brave
> [debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
> [debug] yt-dlp version 2021.11.10.1 (zip)
> [debug] Python version 3.8.2 (CPython 64bit) - macOS-11.6-arm64-arm-64bit
> [debug] exe versions: none
> [debug] Optional libraries: Crypto, sqlite
> [debug] Proxy map: {}
> [debug] [DiscoveryPlus] Extracting URL: https://www.discoveryplus.com/video/battle-for-the-bird-us/battle-for-the-bird
> [DiscoveryPlus] battle-for-the-bird-us/battle-for-the-bird: Downloading JSON metadata
> [DiscoveryPlus] 3840016: Downloading JSON metadata
> [DiscoveryPlus] battle-for-the-bird-us/battle-for-the-bird: Downloading m3u8 information
> [debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
> [debug] Default format spec: best/bestvideo+bestaudio
> [info] 3840016: Downloading 1 format(s): hls-5273
> [debug] Invoking downloader on "https://content-ause1-ur-discovery1.uplynk.com
> [snipped]
> ```
Friend, what is the command to download from Paramount +?

**Comment by sandrosg2018** [comment]
> It's also using a US XFR inside the US unnecessarily, which causes Discovery+ to return a 404 even if the content exists. Here's a run without --no-geo-bypass:
> 
> ```
> % ./yt-dlp --verbose --cookies-from-browser brave "https://www.discoveryplus.com/video/battle-for-the-bird-us/battle-for-the-bird"
> [debug] Command-line config: ['--verbose', '--cookies-from-browser', 'brave', 'https://www.discoveryplus.com/video/battle-for-the-bird-us/battle-for-the-bird']
> [Cookies] Extracting cookies from brave
> [debug] Extracting cookies from: "/Users/me/Library/Application Support/BraveSoftware/Brave-Browser/Default/Cookies"
> [debug] using find-generic-password to obtain password
> [Cookies] Extracted 268 cookies from brave
> [debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
> [debug] yt-dlp version 2021.11.10.1 (zip)
> [debug] Python version 3.8.2 (CPython 64bit) - macOS-11.6-arm64-arm-64bit
> [debug] exe versions: none
> [debug] Optional libraries: Crypto, sqlite
> [debug] Proxy map: {}
> [debug] [DiscoveryPlus] Extracting URL: https://www.discoveryplus.com/video/battle-for-the-bird-us/battle-for-the-bird
> [debug] Using fake IP 6.194.37.198 (US) as X-Forwarded-For
> [DiscoveryPlus] battle-for-the-bird-us/battle-for-the-bird: Downloading JSON metadata
> ERROR: [DiscoveryPlus] battle-for-the-bird-us/battle-for-the-bird: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output. (caused by <HTTPError 404: 'Not Found'>); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
>   File "./yt-dlp/yt_dlp/extractor/common.py", line 713, in _request_webpage
>     return self._downloader.urlopen(url_or_request)
>   File "./yt-dlp/yt_dlp/YoutubeDL.py", line 3295, in urlopen
>     return self._opener.open(req, timeout=self._socket_timeout)
>   File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 531, in open
>     response = meth(req, response)
>   File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 640, in http_response
>     response = self.parent.error(
>   File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 569, in error
>     return self._call_chain(*args)
>   File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 502, in _call_chain
>     result = func(*args)
>   File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 649, in http_error_default
>     raise HTTPError(req.full_url, code, msg, hdrs, fp)
> ```
> 
> And here is (a successful one) with it:
> 
> ```
> % ./yt-dlp --no-geo-bypass --verbose --cookies-from-browser brave "https://www.discoveryplus.com/video/battle-for-the-bird-us/battle-for-the-bird"
> [debug] Command-line config: ['--no-geo-bypass', '--verbose', '--cookies-from-browser', 'brave', 'https://www.discoveryplus.com/video/battle-for-the-bird-us/battle-for-the-bird']
> [Cookies] Extracting cookies from brave
> [debug] Extracting cookies from: "/Users/me/Library/Application Support/BraveSoftware/Brave-Browser/Default/Cookies"
> [debug] using find-generic-password to obtain password
> [Cookies] Extracted 268 cookies from brave
> [debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
> [debug] yt-dlp version 2021.11.10.1 (zip)
> [debug] Python version 3.8.2 (CPython 64bit) - macOS-11.6-arm64-arm-64bit
> [debug] exe versions: none
> [debug] Optional libraries: Crypto, sqlite
> [debug] Proxy map: {}
> [debug] [DiscoveryPlus] Extracting URL: https://www.discoveryplus.com/video/battle-for-the-bird-us/battle-for-the-bird
> [DiscoveryPlus] battle-for-the-bird-us/battle-for-the-bird: Downloading JSON metadata
> [DiscoveryPlus] 3840016: Downloading JSON metadata
> [DiscoveryPlus] battle-for-the-bird-us/battle-for-the-bird: Downloading m3u8 information
> [debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
> [debug] Default format spec: best/bestvideo+bestaudio
> [info] 3840016: Downloading 1 format(s): hls-5273
> [debug] Invoking downloader on "https://content-ause1-ur-discovery1.uplynk.com
> [snipped]
> ```

![Shot 0002](https://user-images.githubusercontent.com/95977674/145693140-5ddcc04d-f838-448c-8ff2-46c3327aa3ec.jpg)

**Comment by pukkandan** [comment]
@sandrosg2018 Dont post unrelated comments

**Comment by sandrosg2018** [comment]
> Dont post unrelated comments

Hi, I would like to know what is the correct command to download Paramount Plus?

**Comment by Naranjis** [comment]
Hi, I'm trying to download from Spain a show that's only available in discovery plus Spain (https://www.discoveryplus.com/es/video/wild-frank/temporada-1-brasil-episodio-1) and I can't download it... any solutions? Thank u so much!

**Comment by bashonly** [comment]
Could anyone outside the US give this PR a try?

- #10471

I've created pre-release builds for testing purposes:

```
yt-dlp --update-to bashonly/yt-dlp@dplay
```

If it works, please comment and include your country (BR, ES, GB, etc)

If it doesn't work, please comment and include a verbose log (add `-v` to your command)
