### ISSUE TITLE
Building macOS version of YT-DLP failed - suggestion

### ISSUE THREAD

**Issue by section83** [yt-dlp/yt-dlp#1624]
### Checklist

- [X] I'm asking a question and not reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

The failure to build the macOS version of the 10/11/21 release might be due to PyInstaller v4.6 which was released on 29/10/21.

Version 4.6 changed the way PyInstaller handles ad-hoc code signing. This was done because of a problem for PyInstaller in macOS 10.13.

Can you specify PyInstaller 4.5.1 for the macOS build of YT-DLP ? At least that did work for the 22/10/21 release.

**Comment by pukkandan** [comment]
Yes, this has already been identified here. https://github.com/yt-dlp/yt-dlp/pull/1221#issuecomment-964984731

I just haven't had the time to test and push a patch yet

**Comment by section83** [comment]
Thanks. Sorry I didn't find your #1221 discussion before asking.
