### ISSUE TITLE
SYFY - Unsupported URL

### ISSUE THREAD

**Issue by jsmith1299** [yt-dlp/yt-dlp#1634]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2021.11.10.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

USA

### Description

Unable to download from Syfy

### Verbose log

```shell
yt-dlp.exe -v https://www.syfy.com/chucky/season-1/episode-105/little-little-lies-extended
[debug] Command-line config: ['-v', 'https://www.syfy.com/chucky/season-1/episode-105/little-little-lies-extended']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2021.11.10.1 (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19042-SP0
[debug] exe versions: ffmpeg N-93302-g147ef1d947, ffprobe N-93302-g147ef1d947
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [generic] Extracting URL: https://www.syfy.com/chucky/season-1/episode-105/little-little-lies-extended
[generic] little-little-lies-extended: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] little-little-lies-extended: Downloading webpage
[generic] little-little-lies-extended: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://www.syfy.com/chucky/season-1/episode-105/little-little-lies-extended
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1311, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1336, in __extract_info
  File "yt_dlp\extractor\common.py", line 595, in extract
  File "yt_dlp\extractor\generic.py", line 3766, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.syfy.com/chucky/season-1/episode-105/little-little-lies-extended
```

**Comment by useless2764** [comment]
Fun fact, you can go to NBCs main website and get stuff without issue from any nbc owned network

see: https://www.nbc.com/networks/syfy

**Comment by jsmith1299** [comment]
Thanks for the information. Using NBC works.

**Comment by jsmith1299** [comment]
Workaround is using NBC link instead.
