### ISSUE TITLE
 malformed AAC bitstream detected

### ISSUE THREAD

**Issue by Ivoyko** [yt-dlp/yt-dlp#1638]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2021.11.10.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

I am in Ubuntu 20.04. I have last ffmpeg and last yt-dlp version but i still get this error with twitch videos downloads.
Did i miss something?

### Verbose log

```shell
[download] 100% of 67.03MiB WARNING: v1149810294: malformed AAC bitstream detected
```

**Comment by pukkandan** [comment]
That is not the ENTIRE VERBOSE LOG

and that is not an error. The warning is normal

**Comment by Ivoyko** [comment]
if audio isnt fine should be a error but ok, pal.

**Comment by pukkandan** [comment]
> if audio isnt fine should be a error but ok, pal

read the rest of the output. ffmpeg will be used to auto-fix this

**Comment by pukkandan** [comment]
> if wasnt a error, why audio its malformed?

When downloading from m3u8 streams, the fragmented audio stream has ADTS framing which must be removed from the final file. Until it is removed, the audio bitream is "malformed". yt-dlp will automatically invoke ffmpeg to fixup this.

If you have any issues with this process, you must provide the full verbose log. When all you have given us is the warning, there is nothing more to be said or done
