### ISSUE TITLE
ism/manifest file not downloaded or merged propery

### ISSUE THREAD

**Issue by Baku86** [yt-dlp/yt-dlp#164]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running yt-dlp version **2021.03.07**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE

```

## Description

Hello,
I would like to download encrypted ism/manifest (Microsoft IIS Smooth Streaming Media ) audio and video. I'm 100% sure, that I can decrypt them, so it's not an issue.

Yt-dlp allows that with --allow-unplayable-formats but somehow downloaded files don't have proper encryption signaling. 

> An encrypted ismv/mp4 file has its sample description 'wrapped' in an encv box (child of the stsd box). 

Without this files cannot be decrypted, because decryptor assumes they are decrypted already.

Furthermore YT-dlp is not merging downloaded parts (ism are in fact fragmented mp4 files) correctly, but this can be fixed by external tool. I'm not 100% sure if it is done properly however, but at least fixed file plays in vlc (still encrypted) with proper runtime. More info:

> Most legacy tools (encoder and packagers) that produce ISMV and ISMA files generate fragmented MP4 files that lack a tfdt timestamp box. While these files appear to be normal fragmented MP4 files, the lack of tfdt renders those media files unsuitable for playback.

Any help would be much appreciated.

**Comment by pukkandan** [comment]
`--allow-unplayable-formats` is not intended as tool to help break DRM protection. If the issue exists in a non-DRM video, give example URL and I will look into it
