### ISSUE TITLE
[Feature Request] `--embed-info-json` option which does not require `--write-info-json` (or removes the file afterwards)

### ISSUE THREAD

**Issue by markhenrick** [yt-dlp/yt-dlp#1644]
### Checklist

- [X] I'm reporting a feature request
- [X] I've verified that I'm running yt-dlp version **2021.11.10.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

As far as I can tell, from reading the documentation and doing some experiments, there is no way to embed an infojson without also writing it to a separate file, which will not be deleted afterwards (short of using a custom `exec` to rm it). It would be nice to have an `--embed-info-json` consistent with `--embed-subs`, which would remove the `.json` file after it has been successfully embedded (and the user has not also specified `--write-info-json`)

**Comment by pukkandan** [comment]
Makes sense. The json embedding was ported from animelover's fork and honestly I havent put much thought into it. I will also add an option to disable the json embedding while keeping both --write-infojson and --add-metadata
