### ISSUE TITLE
yt-dlp doesn't correctly download an m3u8 audio stream

### ISSUE THREAD

**Issue by VXsz** [yt-dlp/yt-dlp#1647]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2021.11.10.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

Okay so for most m3u8 streams yt-dlp works, but sometimes it produces audio files that are incomplete with missing segments 

Here's one of those `https://mbc-aws-ksa.mncdn.com/out/v1/28092eb012f34e2e88ac24cbd6416b77/a82af339e99a490684e63554466650b9/9951caf943ff4de6b0ee4ae605278201/manifest.m3u8`

the video downloads correctly, but the audio downloads with missing segments (1 full minute), even tho I tried with m3u8-cli and it seems to be grabbing everything correctly & _the audio size is actually smaller_ I have no idea why but it could be not parsing the response correctly

### Verbose log

```shell
[debug] Command-line config: ['-Uv', '--allow-unplayable-formats', '--no-warnings', '--no-check-certificate', '-f', 'all[vcodec=none]', '--fixup', 'never', 'https://mbc-aws-ksa.mncdn.com/out/v1/28092eb012f34e2e88ac24cbd6416b77/a82af339e99a490684e63554466650b9/9951caf943ff4de6b0ee4ae605278201/manifest.m3u8', '-o', 'test.%(language)s.m4a', '--audio-multistreams', '--external-downloader=aria2c']
[debug] Encodings: locale cp1256, fs utf-8, out utf-8, err utf-8, pref cp1256
[debug] yt-dlp version 2021.11.10.1
[debug] Python version 3.9.6 (CPython 64bit) - Windows-10-10.0.19042-SP0
[debug] exe versions: ffmpeg n4.4-ffmpeg-windows-build-helpers (setts,fdk), ffprobe n4.4-ffmpeg-windows-build-helpers
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
yt-dlp is up to date (2021.11.10.1)
[debug] [generic] Extracting URL: https://mbc-aws-ksa.mncdn.com/out/v1/28092eb012f34e2e88ac24cbd6416b77/a82af339e99a490684e63554466650b9/9951caf943ff4de6b0ee4ae605278201/manifest.m3u8
[generic] manifest: Requesting header
[debug] Identified a direct video link
[generic] manifest: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[info] manifest: Downloading 1 format(s): audio_0-ar_eg
[debug] Invoking downloader on "https://mbc-aws-ksa.mncdn.com/out/v1/28092eb012f34e2e88ac24cbd6416b77/a82af339e99a490684e63554466650b9/9951caf943ff4de6b0ee4ae605278201/7882902478e54487bd8eb0a107550cbd/9057fef85f034bebb858c1a1ce6be9b5/manifest_11_0.m3u8"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Fragment downloads will be delegated to aria2c
[hlsnative] Total fragments: 462
[download] Destination: test.ar.m4a
[debug] aria2c command line: aria2c -c "--console-log-level=warn" "--summary-interval=0" "--download-result=hide" "--file-allocation=none" -x16 -j16 -s16 "--allow-overwrite=true" "--allow-piece-length-change=true" --header "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.29 Safari/537.36" --header "Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7" --header "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8" --header "Accept-Encoding: gzip, deflate" --header "Accept-Language: en-us,en;q=0.5" "--check-certificate=false" "--remote-time=true" "--auto-file-renaming=false" "--file-allocation=none" "--uri-selector=inorder" -i test.ar.m4a.part.frag.urls
[aria2c] Downloaded 22162846 bytes#6852ba 16KiB/46KiB(34%)][#5726eb 0B/46KiB(0%)][#d7e129 0B/0B][#c5edcb 0B/0B](+11)
[download] 100% of 21.14MiB in 00:03
```

**Comment by Ashish0804** [comment]
>--allow-unplayable-formats

don't open issues for drm stuff

**Comment by VXsz** [comment]
> > --allow-unplayable-formats
> 
> don't open issues for drm stuff

it does not contain DRM at all, the argument is just in-case the server sends weird formats, you can download the video and see it's not protected nor the audio, I hope this gets reopened

**Comment by Ashish0804** [comment]
it works just fine for me without and issues afaict
```
Audio
ID                                       : 1
Format                                   : AAC LC
Format/Info                              : Advanced Audio Codec Low Complexity
Codec ID                                 : mp4a-40-2
Duration                                 : 46 min 14 s
Bit rate mode                            : Constant
Bit rate                                 : 61.3 kb/s
Channel(s)                               : 2 channels
Channel layout                           : L R
Sampling rate                            : 48.0 kHz
Frame rate                               : 46.875 FPS (1024 SPF)
Compression mode                         : Lossy
Stream size                              : 20.3 MiB (98%)
Default                                  : Yes
Alternate group                          : 1
```

I see that u have fixup never aswell
try with just this and see if it works
`yt-dlp -x --downloader aria2c <url>`

**Comment by VXsz** [comment]
Okay so after a bit of trying looks like `--allow-unplayable-formats` is the main issue, with it yt-dlp doesn't attempt to fix the malformed audio track (even through it gives a warning)

is there a way to also force fixing malformed tracks while using the `--allow-unplayable-formats` arguments?

Thank you for the feedback
