### ISSUE TITLE
How Can I Download A Full Series of CuriosityStream?

### ISSUE THREAD

**Issue by post-master** [yt-dlp/yt-dlp#1648]
### Checklist

- [X] I'm asking a question and not reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

I have opened an issue before but not answered my issue with the proper solution, that is here: https://github.com/yt-dlp/yt-dlp/issues/1568

How Can I Download A Full Series of CuriosityStream?

I can see the series list here " https://curiositystream.com/series" But how can I select a series for download? I have tried with the series name but not worked. @pukkandan answered me that I should use the link like "https://curiositystream.com/series/2" but how I know the number of a series that I want to download?

Can you please explain with a proper solution please? 

I can share my credentials if you want for checking and testing

**Comment by pukkandan** [comment]
The stupid site won't let me navigate the website properly without an account. But anyway, I have managed to find the series URL as https://curiositystream.com/series/694.

But curiosity series downloads seems to be broken in general. I will need to fix that

**Comment by pukkandan** [comment]
I have pushed a patch for the series downloads https://github.com/yt-dlp/yt-dlp/commit/92775d8a40728fe045af000755f1c3eeffb2089d

**Comment by post-master** [comment]
> The stupid site won't let me navigate the website properly without an account. But anyway, I have managed to find the series URL as https://curiositystream.com/series/694.
> 
> But curiosity series downloads seems to be broken in general. I will need to fix that

Sir credentials won't be a problem. I can share my account if you want. I just need that support for downloading series. because it's really tough to download one by one from a big series. @pukkandan

**Comment by post-master** [comment]
> The stupid site won't let me navigate the website properly without an account. But anyway, I have managed to find the series URL as https://curiositystream.com/series/694.
> 
> But curiosity series downloads seems to be broken in general. I will need to fix that

I have found your way of getting the link for downloading a series. but now i am facing with another issue. getting this error right now. here is the screenshot: https://prnt.sc/1zgb8pi

**note: i have redownloaded full repo for update code and tried**  @pukkandan

**Comment by pukkandan** [comment]
Account details won't really help in this case. Once we have the series URL, it can be downloaded with yt-dlp. I assumed the series URL would be easy to find on the website. Hence why I assumed your original issue to be a user error. Sorry about that. (It didn't help that you opened it with wring template - but that's neither here nor there)

But from my experience without logging in and the fact that you opened the issue again, it does seem like the website makes it really hard to find the series URL for some reason. This is quite frankly the website's problem and not something we can fix.

However, I understand that blaming the website and closing the issue doesnt help anyone. So I have added the field `series_id` to the metadata extracted from single videos. So now, even if the website doesn't give you the right URL, you can find it using yt-dlp itself.

Eg:

```
➤ yt-dlp https://curiositystream.com/video/5423 --print series_id --no-warn
694

➤ yt-dlp https://curiositystream.com/series/694
[curiositystream:series] 694: Downloading JSON metadata
[download] Downloading playlist: Crash Course: Biology
[curiositystream:series] playlist Crash Course: Biology: Collected 40 videos; downloading 40 of them
[download] Downloading video 1 of 40
[curiositystream] 5423: Downloading JSON metadata
[curiositystream] 5423: Downloading m3u8 information
WARNING: [curiositystream] Ignoring subtitle tracks found in the HLS manifest; if any subtitle tracks are missing, please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
[curiositystream] 5423: Downloading JSON metadata
[curiositystream] 5423: Downloading MPD manifest
WARNING: [curiositystream] Ignoring subtitle tracks found in the DASH manifest; if any subtitle tracks are missing, please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
[info] 5423: Downloading 1 format(s): hls-3789+dash-094606be-4074-4990-8024-5cdc2396c0d0
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 30
[download] Destination: That's Why Carbon Is A Tramp - Crash Course Biology #1 [5423].fhls-3789.mp4
[download]  53.5% of ~40.29MiB at  2.67MiB/s ETA 00:07 (frag 16/30)
ERROR: Interrupted by user
```

>  getting this error right now. here is the screenshot: prnt.sc/1zgb8pi

I didn't see your edit until after closing the issue, but now this has been fixed as well

**Comment by pukkandan** [comment]
Also, it appears that we already had this discussion before in https://github.com/yt-dlp/yt-dlp/issues/277 and it was decided there to let `/video` urls be single videos and to only allow `/series` URLs for the series

That's what you get when neither of us bothered to search existing issues first

**Comment by post-master** [comment]
Thanks A lot for your great effort and project. now I can download the series all at once. Thanks for your time sir
