### ISSUE TITLE
Multithreading and faster download time

### ISSUE THREAD

**Issue by Collin8000** [yt-dlp/yt-dlp#165]
I want to know if you can put in multithreading and/or parallell downloading

**Comment by pukkandan** [comment]
We have considered adding native multithreaded downloading. But this is not a trivial task and even if we were to implement it, it probably won't happen anytime soon.

You can use `aria2c` to get multithreaded downloads in most cases

**Comment by Collin8000** [comment]
Thank you i will try that :)

**Comment by NathanDai5287** [comment]
Is `aria2c` able to download YouTube videos?

**Comment by BOplaid** [comment]
> Is `aria2c` able to download YouTube videos?

yep
