### ISSUE TITLE
postprocessor_hooks option doesn't work

### ISSUE THREAD

**Issue by JVT038** [yt-dlp/yt-dlp#1650]
### Checklist

- [X] I'm asking a question and not reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

Hi,
I'm using yt-dlp in my python project, and I'm trying to use the `postprocessor_hooks` option.
My options:
```python
    ytdl_options = {
        'format': format,
        'postprocessors': postprocessors,
        'ffmpeg_location': ffmpeg,
        'postprocessor_hooks': [yt.postprocessor_hook],
        'progress_hooks': [yt.download_hook],
        'outtmpl': filepath,
        'noplaylist': True,
        # 'updatetime': True, 
    }
```
So the `progress_hooks` works fine, and the function `yt.download_hook` does what it's supposed to do, however the `yt.postprocessor_hook` isn't being executed.
I tried putting `print('test')` in `yt.postprocessor_hook`, and I'm not seeing `test` in my console output.
I want to use `postprocessor_hooks`, because I'm trying to get the final extension after the FFmpeg conversion and I want to know when the conversion is finished, so I tried to achieve that through this hook, but it doesn't work for some reason.

Can anyone help me figure this out? 
With kind regards,

**Comment by pukkandan** [comment]
You are right. This is broken. As a workaround, you can do `ydl.add_postprocessor_hook(yt.postprocessor_hook)` after initializing the YoutubeDL instance

**Comment by JVT038** [comment]
Alright, got it. Thanks for your reply.
