### ISSUE TITLE
Format selecting with slash and plus not working as expect

### ISSUE THREAD

**Issue by xin344** [yt-dlp/yt-dlp#1660]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2021.11.10.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Taiwan

### Description

I want to download and merge the format: video 137 or 136 and the audio 140
When the format  136 is the only available with 137 unavailable it works properly, but if the 137 format is available, yt-dlp will only download the 137 format as a mp4 file, not download the 140 audio. And it will not be merged to mkv format.

The log is here with username and proxy port hidden.
The key of log: [info] YOmJaWABopQ: Downloading 1 format(s): 137
URL: https://www.youtube.com/watch?v=YOmJaWABopQ

Conf file content: 
--no-mtime
--proxy http://localhost
-o "~/Downloads/YTB/%(upload_date)s.%(title)s - %(display_id)s.%(ext)s"
-f 137/136+140
--merge-output-format mkv

### Verbose log

```shell
[debug] Command-line config: ['https://www.youtube.com/watch?v=YOmJaWABopQ', '-Uv']
[debug] Home config file: yt-dlp.conf
[debug] Home config: ['--no-mtime', '--proxy', 'http://localhost', '-o', '~/Downloads/YTB/%(upload_date)s.%(title)s - %(display_id)s.%(ext)s', '-f', '137/136+140', '--merge-output-format', 'mkv']
[debug] User config file: C:\Users\one\yt-dlp.conf
[debug] User config: ['--no-mtime', '--proxy', 'http://localhost', '-o', '~/Downloads/YTB/%(upload_date)s.%(title)s - %(display_id)s.%(ext)s', '-f', '137/136+140', '--merge-output-format', 'mkv']
[debug] Encodings: locale cp936, fs utf-8, out utf-8, err utf-8, pref cp936
[debug] yt-dlp version 2021.11.10.1 (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] exe versions: ffmpeg 4.4.1-full_build-www.gyan.dev (setts), ffprobe 4.4.1-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {'http': 'http://localhost', 'https': 'http://localhost'}
yt-dlp is up to date (2021.11.10.1)
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=YOmJaWABopQ
[youtube] YOmJaWABopQ: Downloading webpage
[youtube] YOmJaWABopQ: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[info] YOmJaWABopQ: Downloading 1 format(s): 137
[debug] Invoking downloader on "https://r5---sn-a5msen7l.googlevideo.com/videoplayback?expire=1636906308&ei=5OCQYfS3Hb6KsfIPy7a1oA4&ip=103.102.4.106&id=o-AAsK6PRXq5E8fyZx54SgwhjCE3yELMiuAiAH_dUBgOhZ&itag=137&source=youtube&requiressl=yes&mh=DB&mm=31%2C26&mn=sn-a5msen7l%2Csn-o097znz7&ms=au%2Conr&mv=m&mvi=5&pl=24&initcwndbps=2216250&vprv=1&mime=video%2Fmp4&gir=yes&clen=85349904&dur=739.071&lmt=1636800166242250&mt=1636884289&fvip=5&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=5432434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRgIhALdtiy3AAlIKUdEjDyhQA5LoNbycIHtuKhYIvGTyKO3KAiEAz2-WxKRsuiMF6v6SL86l3igHnwq-2XvNenXHj9bUBhs%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgfVKx2RpwfFgFnATqG8m7BNuK13ePQtHojyFN2a-kJvACIQCsubFG05zJVAq2t7iluWJQZ7gInnLdUwr6VstmyPBu7g%3D%3D"

ERROR: Interrupted by user
```

**Comment by pukkandan** [comment]
`+` has precedence. Use `-f (137/136)+140`
