### ISSUE TITLE
RedTube DL don't work any more

### ISSUE THREAD

**Issue by demonluo** [yt-dlp/yt-dlp#1663]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2021.11.10.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Description

only downloaded a small file (893 btyes) which is obviously not the real video file...
sample url:
https://www.redtube.com/39016781

### Verbose log

```shell
Download Log for url: https://www.redtube.com/39016781

Waiting
[RedTube] 39016781: Downloading webpage
[RedTube] 39016781: Downloading m3u8 information
[info] 39016781: Downloading 1 format(s): 1
[download] Destination: C:\Users\Sony\xxx\Youtube-Dl\Cute Asian is fucked & creampied!-39016781.mp4
[download] 893.00B at 436.07KiB/s (00:02)
[download] 100% of 893.00B in 00:02
Download Worker Finished.
```

**Comment by Mennaruuk** [comment]
I can reproduce:
```
yt-dlp -Uv https://www.redtube.com/39016781
[debug] Command-line config: ['-Uv', 'https://www.redtube.com/39016781']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2021.11.10.1 (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] exe versions: none
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
yt-dlp is up to date (2021.11.10.1)
[debug] [RedTube] Extracting URL: https://www.redtube.com/39016781
[RedTube] 39016781: Downloading webpage
[RedTube] 39016781: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: best/bestvideo+bestaudio
[info] 39016781: Downloading 1 format(s): 1
[debug] Invoking downloader on "https://www.redtube.com/media/mp4?s=eyJ2a2V5IjozOTAxNjc4MSwicyI6Ijk3NjkwYzc5Y2Q3MTE0NjIzZGFhYWRjYWU4NzNjYzViNWIwODViZWY2NzMwMmVlNzFmNGYxNWVkZWU1N2U2MGQiLCJndCI6MTYzNjkwNTI3M30"
[download] Destination: Cute Asian is fucked & creampied! [39016781].mp4
[download] 100% of 1001.00B in 00:00
```

**Comment by parasiteoflife** [comment]
Same here, worst thing is yt-dlp marks the video as completed and adds it to the archive file.

**Comment by tredondo** [comment]
[Not fixed](https://github.com/yt-dlp/yt-dlp/commit/93864403ea7c982be9a78af38835ac0747ed12d1#r62128460) by today's revision.
