### ISSUE TITLE
v.qq.com

### ISSUE THREAD

**Issue by demonluo** [yt-dlp/yt-dlp#1666]
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2021.11.10.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Example URLs

- Single video: https://v.qq.com/x/cover/mzc002007g7aqqt/t0960an30x7.html
- Single video: https://v.qq.com/x/page/g0369qp6w4k.html

### Description

this site is very popular in china so it should be supported just like youku...

### Verbose log

```shell
Download Log for url: https://v.qq.com/x/cover/mzc002007g7aqqt/t0960an30x7.html

Waiting
[generic] t0960an30x7: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] t0960an30x7: Downloading webpage
[generic] t0960an30x7: Extracting information
ERROR: Unsupported URL: https://v.qq.com/x/cover/mzc002007g7aqqt/t0960an30x7.html
Download Worker Finished.
```

**Comment by coletdjnz** [comment]
Related upstream issue: https://github.com/ytdl-org/youtube-dl/issues/6831
