### ISSUE TITLE
Sohu DL don't work any more

### ISSUE THREAD

**Issue by demonluo** [yt-dlp/yt-dlp#1667]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2021.11.10.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Description

yt-dlp always give the meesage "ERROR: Unsupported URL" but sohu is listed as one of the supported sites...

### Verbose log

```shell
Download Log for url: https://tv.sohu.com/v/dXMvMzI4OTQ3MDQxLzIwMjI4NDczMC5zaHRtbA==.html

Waiting
[generic] dXMvMzI4OTQ3MDQxLzIwMjI4NDczMC5zaHRtbA==: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] dXMvMzI4OTQ3MDQxLzIwMjI4NDczMC5zaHRtbA==: Downloading webpage
[generic] dXMvMzI4OTQ3MDQxLzIwMjI4NDczMC5zaHRtbA==: Extracting information
ERROR: Unsupported URL: https://tv.sohu.com/v/dXMvMzI4OTQ3MDQxLzIwMjI4NDczMC5zaHRtbA==.html
Download Worker Finished.
```

**Comment by pukkandan** [comment]
The existing sohu extractor looks for a totally different URL pattern which seems to no longer exist. Probably the whole extractor needs to be re-written

**Comment by rom1504** [comment]
I found https://github.com/soimort/you-get works for sohu
that might be helpful

**Comment by bashonly** [comment]
relevant discussion in duplicate issue:
https://github.com/yt-dlp/yt-dlp/issues/7463#issuecomment-1639079013
https://github.com/yt-dlp/yt-dlp/issues/7463#issuecomment-1613858639
