### ISSUE TITLE
Ability to exclude certain fragments (outside of Sponsorblock) from file download

### ISSUE THREAD

**Issue by JVT038** [yt-dlp/yt-dlp#1669]
### Checklist

- [X] I'm reporting a feature request
- [X] I've verified that I'm running yt-dlp version **2021.11.10.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

Hi,
So I have a situation where I need to exclude certain timestamps / fragments from the file download.
I was thinking of something like this:
An post-processor argument called `--exclude-from-file ARGS`, where the `ARGS` are like this:
`minute:second-minute:second`, and the supplied time stamp would be skipped, just like `--sponsorblock-remove CAT` excludes fragments from the file download.

And if multiple fragments / timestamps need to be excluded, the fragments could be separated by a semicolon.

**Comment by pukkandan** [comment]
From https://github.com/yt-dlp/yt-dlp#post-processing-options
```
--remove-chapters REGEX          Remove chapters whose title matches the
                                 given regular expression. Time ranges
                                 prefixed by a "*" can also be used in place
                                 of chapters to remove the specified range.
                                 Eg: --remove-chapters "*10:15-15:00"
                                 --remove-chapters "intro". This option can
                                 be used multiple times
```

**Comment by JVT038** [comment]
Wow, thanks!
How do I use this in my own Python program though? I'm assuming it's a part of the `postprocessors` key in the `ytdl_options`, but how do I append this in the `postprocessors` option?

**Comment by pukkandan** [comment]
```py
        YoutubeDL({'postprocessors': [{
            'key': 'ModifyChapters',
            'remove_ranges': [(start1, stop1), (start2, stop2)]
        }]
```
Here are the other arguments that ModifyChapters take: https://github.com/yt-dlp/yt-dlp/blob/d0e6121adf4f82b266c82d7e632f7fe79f05096c/yt_dlp/postprocessor/modify_chapters.py#L22-L24

**Comment by JVT038** [comment]
Thank you once again!
One last question; are these ranges in seconds (like: `(120, 150)`) or in the same way as `--remove-chapters`? (Like `2:00-2:30`)

**Comment by JVT038** [comment]
Never mind for my last questions, I figured it out.

For anyone else who wants to know how to do this:
I used 2 different keys, like this:

```
    'postprocessors': [
        {
        'key': 'FFmpegExtractAudio', 
        // other stuff
        }, 
        {
        'key': 'ModifyChapters',
        // other stuff
        }
    ], 
The `remove_ranges` has to contain integers. They also need to be in the same index of the `ModifyChapters` key.
Like this:
```
        {
        'key': 'ModifyChapters',
        'remove_ranges': [
            (197, 209), 
            (242, 272), 
            (260, 272)
            ]
        }
```
My complete options dictionary:
```
{
    'format': 'bestaudio/best', 
    'postprocessors': [
        {
        'key': 'FFmpegExtractAudio', 
        'preferredcodec': 'mp3',
        'preferredquality': '192'
        }, 
        {
        'key': 'ModifyChapters',
        'remove_ranges': [
            (197, 209), 
            (242, 272), 
            (260, 272)
            ]
        }
    ], 
    'ffmpeg_location': 'bin', 
    'progress_hooks': [progress_function],
    'outtmpl': 'downloads\\%(title)s.%(ext)s', 
    'noplaylist': True
}
```

**Comment by pukkandan** [comment]
I should have been more clear about that. `remove_ranges` should be in seconds. The `min:sec` syntax is allowed in CLI only for convenience. If you want to make use of that in your script, you can use the `yt_dlp.utils.parse_duration`
