### ISSUE TITLE
A&E/History Network Sites HTTP Question

### ISSUE THREAD

**Issue by Mr-Jake** [yt-dlp/yt-dlp#1671]
### Checklist

- [X] I'm asking a question and not reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

When downloading from the A&E/History network sites there was always an option to download the HLS TS stream or the HTTP MP4 file. You could get the full list using -F. About a month ago I was still able to extract and download the HTTP mp4. It had the domain:
```
http://aepdaks3.aetndigital.com/AETN-History_VMS/<filename>.mp4?__gda__=<key>
```
However, when I did -F today, only the HLS streams were listed.

Did A&E/History remove the HTTP mp4 files or is there an issue with the extractor?

**Comment by pukkandan** [comment]
The least you can do is provide an example URL. How do you expect anyone to answer this question without any info? Also, if you think this is a bug, you should be opening a `extractor-bug` instead
