### ISSUE TITLE
How do I use hardware transcoding with the post processors?

### ISSUE THREAD

**Issue by JVT038** [yt-dlp/yt-dlp#1672]
### Checklist

- [X] I'm asking a question and not reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

Basically as the question says.
Can I tell FFmpeg in the post processing arguments to use hardware transcoding?
I've searched on this repo, but didn't really find any instructions / methods to do this.
I'd like to use my GPU, and it would be able to use VAAPI / NVENC / QSV, etc for transcoding videos.

If this isn't possible, could this be implemented? I know FFmpeg supports hardware transcoding, so I'm guessing it's possible, but I don't know how hard it is for the devs to implement this.

**Comment by pukkandan** [comment]
You can pass any argument you want to ffmpeg using `--ppa`. But what the relevant args are for hardware transcoding, I do not know. You will have to look at ffmpeg documentation for it

**Comment by JVT038** [comment]
For anyone reading this and wondering how hardware transcoding could work, I figured it out.
In the CLI: `yt-dlp [url] --no-playlist --format=best --recode-video=[desired format, such as 'm4a']--postprocessor-args "VideoConvertor: -c:v h264_nvenc" --verbose`

In this case I'm using h264_nvenc, but you can replace that with any hardware transcoder you want, as long as it's compatible with ffmpeg.
