### ISSUE TITLE
[FunimationShow] Missing episodes

### ISSUE THREAD

**Issue by pukkandan** [yt-dlp/yt-dlp#1674]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2021.11.10.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

AU (Not available in US)

### Description

Currently `FunimationShowIE` uses the endpoint `prod-api-funimationnow.dadcdigital.com/api/funimation/episodes` which is not returning all the episodes for this series. 

The website on the other hand uses these endpoints to get the list of seasons first and then the episodes per season
```
https://d33et77evd9bgg.cloudfront.net/data/v2/shows/sailor-moon-crystal.json
https://d33et77evd9bgg.cloudfront.net/data/v2/seasons/SMC-S1-1.json
```

In fact, I could not find any call to `api/funimation/episodes` at all in the browser. @Mevious, how did you find this endpoint? Do you have any idea if this can be fixed without needing to rewrite the extractor with the cloudfrond endpoints?

PS: You don't need account to list the series even though you cant download the actual episodes. Also, you can use tunnelbear for a free VPN with AU server

### Verbose log

```shell
[debug] Command-line config: ['-v', '--write-pages', '--flat-playlist', '--cookies-from-browser', 'vivaldi', 'https://www.funimation.com/en/shows/sailor-moon-crystal']
[Cookies] Extracting cookies from vivaldi
[debug] Extracting cookies from: REDACTED
[Cookies] Extracted 1383 cookies from vivaldi
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2021.11.10.1 (source)
[debug] Lazy loading extractors is disabled
[debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
[debug] Git HEAD: 013b50b79
[debug] Python version 3.10.0 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] exe versions: ffmpeg N-103892-g71f2a9a2e5-20210927 (fdk,setts), ffprobe N-103892-g71f2a9a2e5-20210927, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [funimation:show] Extracting URL: https://www.funimation.com/en/shows/sailor-moon-crystal
[funimation:show] sailor-moon-crystal: Downloading JSON metadata
[funimation:show] Saving request to sailor-moon-crystal_https_-_title-api.prd.funimationsvc.com_v2_shows_sailor-moon-crystalregion=AU_deviceType=web_locale=en.dump
[funimation:show] sailor-moon-crystal: Downloading JSON metadata
[funimation:show] Saving request to sailor-moon-crystal_https_-_prod-api-funimationnow.dadcdigital.com_api_funimation_episodes_limit=99999_title_id=1572978.dump
[download] Downloading playlist: Sailor Moon Crystal
[funimation:show] playlist Sailor Moon Crystal: Collected 15 videos; downloading 15 of them
[download] Downloading video 1 of 15
[download] Downloading video 2 of 15
[download] Downloading video 3 of 15
[download] Downloading video 4 of 15
[download] Downloading video 5 of 15
[download] Downloading video 6 of 15
[download] Downloading video 7 of 15
[download] Downloading video 8 of 15
[download] Downloading video 9 of 15
[download] Downloading video 10 of 15
[download] Downloading video 11 of 15
[download] Downloading video 12 of 15
[download] Downloading video 13 of 15
[download] Downloading video 14 of 15
[download] Downloading video 15 of 15
[download] Finished downloading playlist: Sailor Moon Crystal
```

**Comment by Mevious** [comment]
> In fact, I could not find any call to `api/funimation/episodes` at all in the browser. @Mevious, how did you find this endpoint? Do you have any idea if this can be fixed without needing to rewrite the extractor with the cloudfrond endpoints?

It's been a little while, but I think I simply looked through the network tab on chrome dev tools searching for any API calls that looked important. I'm having trouble finding any references to `https://title-api.prd.funimationsvc.com` at the moment. It's possible a lot has changed on the back end since June. But I did find a new endpoint when visiting [an episode page for hack sign](https://www.funimation.com/v/hacksign/role-play/).
https://playlist-service.prd.funimationsvc.com/v1/playlist/show/HSN
`HSN` appears to be a new slug different from the other API calls or URLs I've seen in the past. For "Sailor Moon Crystal" it looks like it uses `SMC` and includes multiple seasons.
https://playlist-service.prd.funimationsvc.com/v1/playlist/show/SMC
I'm not sure where to find out what the slug should be for a given show.

**Comment by Jules-A** [comment]
I'm unable to reproduce this, the normal api is returning the correct amount of episodes now: https://prod-api-funimationnow.dadcdigital.com/api/funimation/episodes/?limit=99999&title_id=1572978

It's possible it was just a mistake by Funimation and nothing needs to be changed.
