### ISSUE TITLE
TikTok Videos Missing

### ISSUE THREAD

**Issue by Theoneflop** [yt-dlp/yt-dlp#1676]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2021.11.10.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

All around the world

### Description

When providing the URL of a TikToker's Profile, YT-DLP does not download all the videos of the user. Here we take the example of a tiktoker whose profile is "cashbaker" who has videos since 2017(and yes I checked if his 2017 videos still exist, they do). When executing the command to download his profile, YT-DLP downloads from 2021 till Dec 2019 (YT-DLP detects 97 pages and 2020 videos.)

Missing: Videos from 6 Dec 2019 --> 2017

### Verbose log
[lista.txt](https://github.com/yt-dlp/yt-dlp/files/7546506/lista.txt)

### Notes
I'm using yt-dlp on Android.
EDIT: Same issue happens on Fedora Linux and to everybody else according to the reddit post.
This issue has a [reddit post on r/youtube-dl](https://www.reddit.com/r/youtubedl/comments/qup0dc/ytdlp_not_downloading_all_users_tiktok_videos/?utm_medium=android_app&utm_source=share) too

**Comment by Theoneflop** [comment]
**UPDATE**
On fedora linux, way more videos and pages were detected.
`[starshine@fedora ~]$ yt-dlp https://vm.tiktok.com/ZSehsYYpo/ --datebefore 20191206
[generic] ZSehsYYpo: Requesting header
[redirect] Following redirect to https://www.tiktok.com/@cashbaker?_d=secCgwIARCbDRjEFSADKAESPgo8IunCpbjphSUZl3GMehxWtlJLZ5hd8XJQyOnLMuUbVYDErTtEZjGQeg2nB5IFq9gFFPc%2BilFS8WzLzOlPGgA%3D&language=en&sec_uid=MS4wLjABAAAArg_559ejF51bHxP1pmrtxxw9NKdXBhoiTU_33DBotjZHDl8E0TQ7-OGD6rVHnAs9&sec_user_id=MS4wLjABAAAAOkLgiKnZIBqD1c5ZIUaRfpOfVgv2Rps_-JgoEV197JSpXx_bt3-aUbAmir-jFo0q&share_app_id=1233&share_author_id=6558879147065475077&share_link_id=bf6450db-598e-4c94-bbd8-4f3570929108&timestamp=1636983383&u_code=dlegb2cfck6b3g&user_id=7026701991499318278&utm_campaign=client_share&utm_medium=android&utm_source=copy&source=h5_m&_r=1
[tiktok:user] cashbaker: Downloading webpage
[download] Downloading playlist: cashbaker
[tiktok:user] cashbaker: Downloading user video list page 1
[tiktok:user] cashbaker: Downloading user video list page 2
[tiktok:user] cashbaker: Downloading user video list page 3
[tiktok:user] cashbaker: Downloading user video list page 4
[tiktok:user] cashbaker: Downloading user video list page 5
[tiktok:user] cashbaker: Downloading user video list page 6
[tiktok:user] cashbaker: Downloading user video list page 7
[tiktok:user] cashbaker: Downloading user video list page 8
[tiktok:user] cashbaker: Downloading user video list page 9
[tiktok:user] cashbaker: Downloading user video list page 10
[tiktok:user] cashbaker: Downloading user video list page 11
[tiktok:user] cashbaker: Downloading user video list page 12
[tiktok:user] cashbaker: Downloading user video list page 13
[tiktok:user] cashbaker: Downloading user video list page 14
[tiktok:user] cashbaker: Downloading user video list page 15
[tiktok:user] cashbaker: Downloading user video list page 16
[tiktok:user] cashbaker: Downloading user video list page 17
[tiktok:user] cashbaker: Downloading user video list page 18
[tiktok:user] cashbaker: Downloading user video list page 19
[tiktok:user] cashbaker: Downloading user video list page 20
[tiktok:user] cashbaker: Downloading user video list page 21
[tiktok:user] cashbaker: Downloading user video list page 22
[tiktok:user] cashbaker: Downloading user video list page 23
[tiktok:user] cashbaker: Downloading user video list page 24
[tiktok:user] cashbaker: Downloading user video list page 25
[tiktok:user] cashbaker: Downloading user video list page 26
[tiktok:user] cashbaker: Downloading user video list page 27
[tiktok:user] cashbaker: Downloading user video list page 28
[tiktok:user] cashbaker: Downloading user video list page 29
[tiktok:user] cashbaker: Downloading user video list page 30
[tiktok:user] cashbaker: Downloading user video list page 31
[tiktok:user] cashbaker: Downloading user video list page 32
[tiktok:user] cashbaker: Downloading user video list page 33
[tiktok:user] cashbaker: Downloading user video list page 34
[tiktok:user] cashbaker: Downloading user video list page 35
[tiktok:user] cashbaker: Downloading user video list page 36
[tiktok:user] cashbaker: Downloading user video list page 37
[tiktok:user] cashbaker: Downloading user video list page 38
[tiktok:user] cashbaker: Downloading user video list page 39
[tiktok:user] cashbaker: Downloading user video list page 40
[tiktok:user] cashbaker: Downloading user video list page 41
[tiktok:user] cashbaker: Downloading user video list page 42
[tiktok:user] cashbaker: Downloading user video list page 43
[tiktok:user] cashbaker: Downloading user video list page 44
[tiktok:user] cashbaker: Downloading user video list page 45
[tiktok:user] cashbaker: Downloading user video list page 46
[tiktok:user] cashbaker: Downloading user video list page 47
[tiktok:user] cashbaker: Downloading user video list page 48
[tiktok:user] cashbaker: Downloading user video list page 49
[tiktok:user] cashbaker: Downloading user video list page 50
[tiktok:user] cashbaker: Downloading user video list page 51
[tiktok:user] cashbaker: Downloading user video list page 52
[tiktok:user] cashbaker: Downloading user video list page 53
[tiktok:user] cashbaker: Downloading user video list page 54
[tiktok:user] cashbaker: Downloading user video list page 55
[tiktok:user] cashbaker: Downloading user video list page 56
[tiktok:user] cashbaker: Downloading user video list page 57
[tiktok:user] cashbaker: Downloading user video list page 58
[tiktok:user] cashbaker: Downloading user video list page 59
[tiktok:user] cashbaker: Downloading user video list page 60
[tiktok:user] cashbaker: Downloading user video list page 61
[tiktok:user] cashbaker: Downloading user video list page 62
[tiktok:user] cashbaker: Downloading user video list page 63
[tiktok:user] cashbaker: Downloading user video list page 64
[tiktok:user] cashbaker: Downloading user video list page 65
[tiktok:user] cashbaker: Downloading user video list page 66
[tiktok:user] cashbaker: Downloading user video list page 67
[tiktok:user] cashbaker: Downloading user video list page 68
[tiktok:user] cashbaker: Downloading user video list page 69
[tiktok:user] cashbaker: Downloading user video list page 70
[tiktok:user] cashbaker: Downloading user video list page 71
[tiktok:user] cashbaker: Downloading user video list page 72
[tiktok:user] cashbaker: Downloading user video list page 73
[tiktok:user] cashbaker: Downloading user video list page 74
[tiktok:user] cashbaker: Downloading user video list page 75
[tiktok:user] cashbaker: Downloading user video list page 76
[tiktok:user] cashbaker: Downloading user video list page 77
[tiktok:user] cashbaker: Downloading user video list page 78
[tiktok:user] cashbaker: Downloading user video list page 79
[tiktok:user] cashbaker: Downloading user video list page 80
[tiktok:user] cashbaker: Downloading user video list page 81
[tiktok:user] cashbaker: Downloading user video list page 82
[tiktok:user] cashbaker: Downloading user video list page 83
[tiktok:user] cashbaker: Downloading user video list page 84
[tiktok:user] cashbaker: Downloading user video list page 85
[tiktok:user] cashbaker: Downloading user video list page 86
[tiktok:user] cashbaker: Downloading user video list page 87
[tiktok:user] cashbaker: Downloading user video list page 88
[tiktok:user] cashbaker: Downloading user video list page 89
[tiktok:user] cashbaker: Downloading user video list page 90
[tiktok:user] cashbaker: Downloading user video list page 91
[tiktok:user] cashbaker: Downloading user video list page 92
[tiktok:user] cashbaker: Downloading user video list page 93
[tiktok:user] cashbaker: Downloading user video list page 94
[tiktok:user] cashbaker: Downloading user video list page 95
[tiktok:user] cashbaker: Downloading user video list page 96
[tiktok:user] cashbaker: Downloading user video list page 97
[tiktok:user] cashbaker: Downloading user video list page 98
[tiktok:user] cashbaker: Downloading user video list page 99
[tiktok:user] cashbaker: Downloading user video list page 100
[tiktok:user] cashbaker: Downloading user video list page 101
[tiktok:user] cashbaker: Downloading user video list page 102
[tiktok:user] cashbaker: Downloading user video list page 103
[tiktok:user] cashbaker: Downloading user video list page 104
[tiktok:user] cashbaker: Downloading user video list page 105
[tiktok:user] cashbaker: Downloading user video list page 106
[tiktok:user] cashbaker: Downloading user video list page 107
[tiktok:user] cashbaker: Downloading user video list page 108
[tiktok:user] cashbaker: Downloading user video list page 109
[tiktok:user] cashbaker: Downloading user video list page 110
[tiktok:user] cashbaker: Downloading user video list page 111
[tiktok:user] cashbaker: Downloading user video list page 112
[tiktok:user] cashbaker: Downloading user video list page 113
[tiktok:user] cashbaker: Downloading user video list page 114
[tiktok:user] cashbaker: Downloading user video list page 115
[tiktok:user] cashbaker: Downloading user video list page 116
[tiktok:user] cashbaker: Downloading user video list page 117
[tiktok:user] cashbaker: Downloading user video list page 118
[tiktok:user] cashbaker: Downloading user video list page 119
[tiktok:user] playlist cashbaker: Downloading 2491 videos
[download] Downloading video 1 of 2491
`

**Comment by Theoneflop** [comment]
UPDATE 2:
When downloading a video, the stated 'modified date' of the file is different from the actual date the video was created, for e.g.: A video was created in 2019 while yt-dlp stated it was modified in 2020.

**Comment by Ashish0804** [comment]
If it's a spammy account, they this could be bcoz of the fact that more videos were uploaded in recent days.
If yes, then core issue is TT not providing videos older than DEC 2019 with the endpoint dlp is using.
If the ones u extracted more are infact older videos then it's proly some bug on TTs side.

Can you try with some other accounts which have videos going back to 2018 and with diff OSs/machines at the same time?

**Comment by Theoneflop** [comment]
> If it's a spammy account, they this could be bcoz of the fact that more videos were uploaded in recent days. If yes, then core issue is TT not providing videos older than DEC 2019 with the endpoint dlp is using. If the ones u extracted more are infact older videos then it's proly some bug on TTs side.
> 
> Can you try with some other accounts which have videos going back to 2018 and with diff OSs/machines at the same time?

I will do both. Right now, I'm trying to download the 2019 -> 2017 missing videos that wouldn't download. If it does not work, I will try with another tiktokers account. But as of what I see, it seems like at-least one or more bugs from yt-dlp's end.

**Comment by Theoneflop** [comment]
YT-DLP states wrong creation/modified date.
