### ISSUE TITLE
Youtube throttle at about 80 KiB/s now also with yt-dlp

### ISSUE THREAD

**Issue by jk-85** [yt-dlp/yt-dlp#1680]
### Checklist

- [x] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2021.11.10.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

Some weeks I was glad finding an alternative to the throttled youtube-dl, but now yt-dlp has the same problem with slow youtube-downloads. I have python 2.7 on my linux machine, don't know if that problem is related, I think not.

### Verbose log

```shell
yt-dlp https://www.youtube.com/channel/UCHO1FDpBJ83VLCAep1mtTHQ/videos --write-description
```

**Comment by nyuszika7h** [comment]
There's no way you're using yt-dlp with Python 2.7, it requires 3.6 (unless you're just using the compiled binary). Also, post a **full log** with the `-v` option, NOT just the command.

**Comment by pukkandan** [comment]
PROVIDE VERBOSE LOG

**Comment by jk-85** [comment]
Sorry, in the meantime I switched to youtube-dl, changed the youtube.py and the downloader works fast. I installed Python 3.6 and I got the same slow download-speeds. But I switch to youtube-dl now.

**Comment by jk-85** [comment]
Just tried the windows version. Seems I did something wrong and this issue can be closed, because the windows-version has fast download speeds. Maybe I did something wrong earlier.

**Comment by bithub2** [comment]
I have the same problem with the Windows version, it's not my internet and it might only be certain videos, because YouTube video "dQw4w9WgXcQ" still only takes 2 seconds to download, but most other videos at around the same size take about a minute (at least), please help!!!

**Comment by pukkandan** [comment]
# PROVIDE VERBOSE LOG
