### ISSUE TITLE
Where should i find my files?

### ISSUE THREAD

**Issue by icfhg** [yt-dlp/yt-dlp#1684]
### Checklist

- [x] I'm asking a question and not reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

i just download a twitcast livestream and never set any config file
Checked the 

> %APPDATA%/yt-dlp/config (recommended on Windows)
> %APPDATA%/yt-dlp/config.txt
> ~/yt-dlp.conf
> ~/yt-dlp.conf.txt

_all of the above is not exist_
and ALL the README, i can't see any way to check my download destination
my yt-dlp install by python pip install

**Comment by pukkandan** [comment]
The downloads go to your current working directory by default

![image](https://user-images.githubusercontent.com/6623388/141879040-f9de7c60-b395-463f-b443-1e22efb48649.png)

**Comment by icfhg** [comment]
> The downloads go to your current working directory by default
> 
> ![image](https://user-images.githubusercontent.com/6623388/141879040-f9de7c60-b395-463f-b443-1e22efb48649.png)

Checked, there's the first location i find

**Comment by pukkandan** [comment]
Show the full verbose log in that case

**Comment by icfhg** [comment]
> PS H:\YouTubeArchive\VtbRecord> yt-dlp https://twitcasting.tv/8ra195/movie/709828505
> [TwitCasting] 709828505: Downloading webpage
> [TwitCasting] 709828505: Downloading live info
> [TwitCasting] 709828505: Downloading m3u8 information
> [info] 709828505: Downloading 1 format(s): ws-main
> [download] Destination: OFFLINE                                                                 雑談のみ                                                                    おはよー！10ふんだけ✨ [709828505].mp4
> [mov,mp4,m4a,3gp,3g2,mj2 @ 000002786453c1c0] Found duplicated MOOV Atom. Skipped it
> [mov,mp4,m4a,3gp,3g2,mj2 @ 000002786453c1c0] decoding for stream 0 failed
> Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'pipe:':
>   Metadata:
>     minor_version   : 0
>     major_brand     : iso6
>     compatible_brands: iso6
>   Duration: 00:09:18.26, start: 0.000000, bitrate: N/A
>   Stream #0:0[0x1](und): Video: h264 (Constrained Baseline) (avc1 / 0x31637661), yuv420p(progressive), 640x360, 0 kb/s, 0.0018 fps, 1k tbr, 1k tbn (default)
>     Metadata:
>       handler_name    : VideoHandler
>       vendor_id       : [0][0][0][0]
>   Stream #0:1[0x2](und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 0 kb/s (default)
>     Metadata:
>       handler_name    : SoundHandler
>       vendor_id       : [0][0][0][0]
> Output #0, mp4, to 'file:OFFLINE                                                                 雑談のみ
>                                                      おはよー！10ふんだけ✨ [709828505].mp4.part':
>   Metadata:
>     minor_version   : 0
>     major_brand     : iso6
>     compatible_brands: iso6
>     encoder         : Lavf59.8.100
>   Stream #0:0(und): Video: h264 (Constrained Baseline) (avc1 / 0x31637661), yuv420p(progressive), 640x360, q=2-31, 0 kb/s, 0.0018 fps, 1k tbr, 16k tbn (default)
>     Metadata:
>       handler_name    : VideoHandler
>       vendor_id       : [0][0][0][0]
>   Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 0 kb/s (default)
>     Metadata:
>       handler_name    : SoundHandler
>       vendor_id       : [0][0][0][0]
> Stream mapping:
>   Stream #0:0 -> #0:0 (copy)
>   Stream #0:1 -> #0:1 (copy)
> frame= 3619 fps=4.7 q=-1.0 Lsize=   42789kB time=00:22:07.79 bitrate= 264.0kbits/s speed=1.73x
> video:29640kB audio:12907kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.567500%
is that because of a unarchived stream?

**Comment by pukkandan** [comment]
Did you let the download run to completion? If so, lines are missing from your log. Besides, this is not the verbose log. Add a `-Uv` to your command

**Comment by icfhg** [comment]
i do think the download ended since the next line is repeating the powershell+folder location

> PS H:\YouTubeArchive\VtbRecord> yt-dlp -Uv
> [debug] Command-line config: ['-Uv']
> [debug] Encodings: locale cp950, fs utf-8, out utf-8, err utf-8, pref cp950
> [debug] yt-dlp version 2021.11.10.1
> [debug] Python version 3.10.0 (CPython 64bit) - Windows-10-10.0.22000-SP0
> [debug] exe versions: ffmpeg 2021-11-03-git-08a501946f-full_build-www.gyan.dev (setts), ffprobe 2021-11-03-git-08a501946f-full_build-www.gyan.dev
> [debug] Optional libraries: Cryptodome, keyring, mutagen, sqlite, websockets
> [debug] Proxy map: {}
> yt-dlp is up to date (2021.11.10.1)

is that the verbose log needed?

**Comment by Mennaruuk** [comment]
This is because the video in question is not published.

```
yt-dlp https://twitcasting.tv/8ra195/movie/709828505 -Uv
[debug] Command-line config: ['https://twitcasting.tv/8ra195/movie/709828505', '-Uv']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2021.11.10.1 (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] exe versions: none
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
yt-dlp is up to date (2021.11.10.1)
[debug] [TwitCasting] Extracting URL: https://twitcasting.tv/8ra195/movie/709828505
[TwitCasting] 709828505: Downloading webpage
[TwitCasting] 709828505: Downloading live info
ERROR: [TwitCasting] 709828505: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1311, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1349, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1399, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2273, in process_video_result
  File "yt_dlp\YoutubeDL.py", line 912, in raise_no_formats
yt_dlp.utils.ExtractorError: [TwitCasting] 709828505: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
```

Below is an example of a video that is published:
```
yt-dlp https://twitcasting.tv/shunsing02/movie/709765066 -Uv
[debug] Command-line config: ['https://twitcasting.tv/shunsing02/movie/709765066', '-Uv']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2021.11.10.1 (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] exe versions: none
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
yt-dlp is up to date (2021.11.10.1)
[debug] [TwitCasting] Extracting URL: https://twitcasting.tv/shunsing02/movie/709765066
[TwitCasting] 709765066: Downloading webpage
[TwitCasting] 709765066: Downloading live info
[TwitCasting] 709765066: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: best/bestvideo+bestaudio
[info] 709765066: Downloading 1 format(s): hls
[debug] Invoking downloader on "https://dl01.twitcasting.tv/tc.vod/v/709765066.0.2-1637033123-1637061923-3ea3d779-27ec04b1bd927fe6/fmp4/index.m3u8"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 21
[download] Destination: ちょっとお時間ください！！ _ オノシュンヤ [709765066].mp4
[download]  22.0% of ~9.72MiB at 46.70KiB/s ETA 02:11 (frag 4/21)
```
