### ISSUE TITLE
[nebula] Unable to extract API key

### ISSUE THREAD

**Issue by octylFractal** [yt-dlp/yt-dlp#1690]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2021.11.10.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United States

### Description

I get an error stating "Unable to extract API key" when trying to download from Nebula. I have credentials, the video works fine.

### Verbose log

```shell
[debug] Command-line config: ['-Uv', '--netrc', 'https://nebula.app/videos/the-closer-look-dune-why-loyal-adaptations-dont-work']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2021.11.10.1
[debug] Python version 3.9.7 (CPython 64bit) - Linux-5.15.2-zen1-1-zen-x86_64-with-glibc2.33
[debug] exe versions: ffmpeg 4.4.1 (setts), ffprobe 4.4.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
yt-dlp is up to date (2021.11.10.1)
[Nebula] Logging in
[Nebula] Authenticating to Nebula with supplied credentials
[debug] [Nebula] Extracting URL: https://nebula.app/videos/the-closer-look-dune-why-loyal-adaptations-dont-work
[Nebula] the-closer-look-dune-why-loyal-adaptations-dont-work: Downloading webpage
[Nebula] the-closer-look-dune-why-loyal-adaptations-dont-work: Retrieving Zype API key
ERROR: [Nebula] the-closer-look-dune-why-loyal-adaptations-dont-work: Unable to extract API key; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/octy/.local/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 595, in extract
    ie_result = self._real_extract(url)
  File "/home/octy/.local/lib/python3.9/site-packages/yt_dlp/extractor/nebula.py", line 206, in _real_extract
    api_key = self._retrieve_zype_api_key(url, display_id)
  File "/home/octy/.local/lib/python3.9/site-packages/yt_dlp/extractor/nebula.py", line 137, in _retrieve_zype_api_key
    api_key = self._search_regex(
  File "/home/octy/.local/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 1166, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
yt_dlp.utils.RegexNotFoundError: Unable to extract API key; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/octy/.local/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 595, in extract
    ie_result = self._real_extract(url)
  File "/home/octy/.local/lib/python3.9/site-packages/yt_dlp/extractor/nebula.py", line 206, in _real_extract
    api_key = self._retrieve_zype_api_key(url, display_id)
  File "/home/octy/.local/lib/python3.9/site-packages/yt_dlp/extractor/nebula.py", line 137, in _retrieve_zype_api_key
    api_key = self._search_regex(
  File "/home/octy/.local/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 1166, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
yt_dlp.utils.RegexNotFoundError: Unable to extract API key; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/octy/.local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1311, in wrapper
    return func(self, *args, **kwargs)
  File "/home/octy/.local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1336, in __extract_info
    ie_result = ie.extract(url)
  File "/home/octy/.local/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 621, in extract
    raise type(e)(e.msg, **kwargs)
yt_dlp.utils.RegexNotFoundError: [Nebula] the-closer-look-dune-why-loyal-adaptations-dont-work: Unable to extract API key; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
```

**Comment by pukkandan** [comment]
@hheimbuerger

**Comment by hheimbuerger** [comment]
@octylFractal (CC @pukkandan) Thanks for your report, I've seen it and will get back to you by tomorrow!

**Comment by hheimbuerger** [comment]
@octylFractal I had a chance to take a look at this now. I can reproduce the issue. It seems to affect all Nebula videos, the whole extractor.

It appears that Nebula has changed their general architecture. The frontend is no longer exposing the Zype API key, because it is no longer making direct calls to the Zype API. There's no easy fix, because the Nebula extractor currently released is heavily relying on the Zype API and needs the API key.

That's the bad news. Here's the good news:

A few weeks ago, I implemented channel support for Nebula. After some internal refactoring, I ended up having [rewritten pretty much the entire extractor](https://gfycat.com/popularcircularbittern). Although that wasn't a specific goal, that rewrite also dropped usage of the Zype API — it just ended up being easier that way.

Unfortunately, some other important life project came up and I never got around to polishing this and creating the pull request. I'll do that now.

In the meantime, if you're so inclined, you could try this branch: https://github.com/hheimbuerger/yt-dlp/tree/add-nebula-collection-support (based on `yt-dlp:master` as of five minutes ago)

**Comment by octylFractal** [comment]
I can confirm that the branch works, thank you for your hard work!

**Comment by hheimbuerger** [comment]
@octylFractal That makes me happy, thanks for testing!

I opened the pull request now: https://github.com/yt-dlp/yt-dlp/pull/1694

**Comment by grahamotte** [comment]
I'm also getting this issue - just wanted to say thanks @hheimbuerger for maintaining this, much appreciated!
