### ISSUE TITLE
Soundcloud downloading 6 times JSON metadata for each tracks

### ISSUE THREAD

**Issue by dianatura** [yt-dlp/yt-dlp#1691]
### Checklist

- [x] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2021.11.10.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

USA

### Description

For each tracks, it does download the metadata 6 times, which slow down significantly while using "--sleep-requests"

Seems that is does many unnecessary requests, which quickly trigger their limit rate.

### Verbose log

```shell
[debug] Command-line config: ['-o', '%(title)s.%(ext)s', '--add-header', 'OAuth', '--sleep-requests', '2', 'https://soundcloud.com/hippiesabotage/sets/floating-palace', '-Uv']
'path'
CMD.EXE was started with the above path as the current directory.
UNC paths are not supported.  Defaulting to Windows directory.
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2021.11.10.1
[debug] Python version 3.9.6 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] exe versions: ffmpeg 2021-09-08-git-5e7e2e5031-full_build-www.gyan.dev (setts), ffprobe 2021-09-08-git-5e7e2e5031-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
yt-dlp is up to date (2021.11.10.1)
[debug] [soundcloud:set] Extracting URL: https://soundcloud.com/hippiesabotage/sets/floating-palace
[soundcloud:set] hippiesabotage/sets/floating-palace: Downloading JSON metadata
[download] Downloading playlist: FLOATING PALACE
[soundcloud:set] playlist FLOATING PALACE: Collected 14 videos; downloading 14 of them
[download] Downloading video 1 of 14
[debug] [soundcloud] Extracting URL: https://soundcloud.com/hippiesabotage/01-crypticcaptions-4424-ref-15oct2021
[soundcloud] Sleeping 2.0 seconds ...
[soundcloud] hippiesabotage/01-crypticcaptions-4424-ref-15oct2021: Downloading info JSON
[soundcloud] Sleeping 2.0 seconds ...
[soundcloud] 1156240180: Downloading JSON metadata
[soundcloud] Sleeping 2.0 seconds ...
[soundcloud] 1156240180: Downloading JSON metadata
[soundcloud] Sleeping 2.0 seconds ...
[soundcloud] 1156240180: Downloading JSON metadata
[soundcloud] Sleeping 2.0 seconds ...
[soundcloud] 1156240180: Downloading JSON metadata
[soundcloud] Sleeping 2.0 seconds ...
[soundcloud] 1156240180: Downloading JSON metadata
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 1156240180: Downloading 1 format(s): http_aac_256
```

**Comment by Ashish0804** [comment]
> For each tracks, it does download the metadata 6 time

That's just the default message.

If you are getting rate limited, then try increasing the time between requests. 

```py
def _download_json_handle(
            self, url_or_request, video_id, note='Downloading JSON metadata',
            errnote='Unable to download JSON metadata', transform_source=None,
            fatal=True, encoding=None, data=None, headers={}, query={},
            expected_status=None)
```

Also how is this a broken site issue? From your logs it seems like it's downloading just fine.

**Comment by dianatura** [comment]
> If you are getting rate limited, then try increasing the time between requests.

Was implying that I use a rate limit because of that

> That's just the default message.

So the default message is supposed to show up 6 times per tracks and actually way 6 times x amount of seconds ?
I don't get this with other websites

**Comment by Ashish0804** [comment]
Not every site works the same way. 
Make a PR if u think you can drop some requests.

**Comment by dianatura** [comment]
>Not every site works the same way.

Well, check other users logs in other issues and you will see that they do not have this issue.

I am reporting a bug here, if your answer is DIY, then I don't see where this is constructive behavior

**Comment by Ashish0804** [comment]
I tested this and i see your issue now.
But i can't reproduce this. Did u strip out information from the `Command-line config:` line?

Here's what i get
```shell
C:\Users\Ashish\Desktop> yt-dlp -v https://soundcloud.com/hippiesabotage/sets/floating-palace
[debug] Command-line config: ['-v', 'https://soundcloud.com/hippiesabotage/sets/floating-palace']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2021.11.10.1
[debug] Python version 3.8.8 (CPython 64bit) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg 3.0.1 (needs_adtstoasc), ffprobe 3.0.1
[debug] Optional libraries: Cryptodome, keyring, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [soundcloud:set] Extracting URL: https://soundcloud.com/hippiesabotage/sets/floating-palace
[soundcloud:set] hippiesabotage/sets/floating-palace: Downloading JSON metadata
[download] Downloading playlist: FLOATING PALACE
[soundcloud:set] playlist FLOATING PALACE: Collected 14 videos; downloading 14 of them
[download] Downloading video 1 of 14
[debug] [soundcloud] Extracting URL: https://soundcloud.com/hippiesabotage/01-crypticcaptions-4424-ref-15oct2021
[soundcloud] hippiesabotage/01-crypticcaptions-4424-ref-15oct2021: Downloading info JSON
[soundcloud] 1156240180: Downloading JSON metadata
[soundcloud] 1156240180: Downloading JSON metadata
[soundcloud] 1156240180: Downloading JSON metadata
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 1156240180: Downloading 1 format(s): http_mp3_128
[debug] Invoking downloader on "https://cf-media.sndcdn.com/lVqAHpBvh7SB.128.mp3?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiKjovL2NmLW1lZGlhLnNuZGNkbi5jb20vbFZxQUhwQnZoN1NCLjEyOC5tcDMqIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNjM3MDYzMTk0fX19XX0_&Signature=ET2OPdGpLURsWTZhD6WfoJbX5dJOSJP7ImYNO~5L0i7ZQjJQN3EXJK4Z0FZHWWACz-TTvKqAA717-LQVOUtQVLbcQOCa6aDTcEyTGHEfPYUzQmWkHfFAsAcmZOpYkHDF9rbbNEALsFyrhB1n2ALZjuufrMPzDgkcnu0DgogPb~fT2bYLdBfhIdhO5eXzwoPplpoviGAIXjJvZLdynCp0UEDzOuFheMrcyaH15ptvtNCiu2cqXT7ZFFuDFpxJFcCJZkz6uK9rIc7D6DrMcB1gJSDFrqPd7s-8lNHzP6ZaVLDvas74tM9OzaEYK7onHzvMx2MutvLYEjpRpfCBirTFXw__&Key-Pair-Id=APKAI6TU7MMXM5DG6EPQ"
[download] 1. CRYPTIC CAPTIONS [1156240180].mp3 has already been downloaded
[download] 100% of 4.50MiB[download] Downloading video 2 of 14
[debug] [soundcloud] Extracting URL: https://soundcloud.com/hippiesabotage/02-safeharbor-4424-ref-15oct2021
[soundcloud] hippiesabotage/02-safeharbor-4424-ref-15oct2021: Downloading info JSON

ERROR: Interrupted by user
```
Notice how `[soundcloud] 1156240180: Downloading JSON metadata` is only thrice for me

**Comment by pukkandan** [comment]
The json is downloaded once for the video metadata and once for each format. Since you passed oauth, u have more formats available than most. Hence why you get the message more times. Other than chaging the message to be more clear, there is nothing to be done

**Comment by dianatura** [comment]
> The json is downloaded once for the video metadata and once for each format. Since you passed oauth, u have more formats available than most. Hence why you get the message more times. Other than chaging the message to be more clear, there is nothing to be done

Thank you for the clarification, makes more sense

Is it possible to reduce that if best or specific format is specified ?

> But i can't reproduce this. Did u strip out information from the Command-line config: line?

I did not. But I think the previous message would explain why there is a difference between your result and mine.

**Comment by pukkandan** [comment]
likely not. We need to get the data of all formats to find which is the best one in the first place. Perhaps an extractor arg can be added to limit the formats extracted, but (unlike sites like funimation where we know the language/version ahead of time), we know very little about the format before actually downloading the JSONs. So not sure how useful that will be

**Comment by dianatura** [comment]
One thing I noticed in the different audio format is that the original soundtrack (uploaded by the author) sits on top of the format list.

Would that mean that it would be possible to grab the first one if looking for best quality ?

![image](https://user-images.githubusercontent.com/94433728/142410622-cf54a662-dc25-468a-ad7a-2f080ccba1e2.png)

**Comment by pukkandan** [comment]
It should be at the bottom (best). If you can share account details, I can check

**Comment by dianatura** [comment]
Sorry, but that is not something I am willing to do. Perhaps do you have an other solution so I can help you ?

**Comment by pukkandan** [comment]
You can do `--write-pages` and give me all the `.dump` files generated. But I am not sure if there is any sensitive account-related info in these files. Also consider opening a proper issue for this so that some developer who already has an account would be able to have a look

**Comment by dianatura** [comment]
Sorry for the late reply.
Do you have suggestions for the title and content for making a new issue ?
In the meanwhile I will have a look into .dump file see if there are sensitive information in it

Kudos for maintaining the project by the way

**Comment by pukkandan** [comment]
Something like `[SoundCloud] Wrong format order` should do. Title is honestly not very important. Just make sure you provide the verbose log and attach the dump files (preferably from the same run as the logs)
