### ISSUE TITLE
Image download

### ISSUE THREAD

**Issue by aviv926** [yt-dlp/yt-dlp#1693]
### Checklist

- [X] I've verified that I'm running yt-dlp version **2021.11.10.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I'm reporting a site feature request
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United state

### Example URLs

https://www.facebook.com/instagram/posts/4569061909846284

### Description

I know this is not the main goal of the project but I wanted to suggest adding a feature to allow downloading of **photos** from a post on Facebook and not just the videos from the post

Thanks!

**Comment by pukkandan** [comment]
We only support video/audio and their metadata. You may want to have a look at the gallery-dl project

**Comment by aviv926** [comment]
@pukkandan Thanks for your quick response

I found gallery-dl but it does not support Facebook
Do you have another idea for a similar project?
