### ISSUE TITLE
How to add track number (soundcloud)

### ISSUE THREAD

**Issue by yant0** [yt-dlp/yt-dlp#1695]
### Checklist

- [X] I'm asking a question and not reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

i use
yt-dlp -x URL -o 'ARTIST/YT-DLP/%(playlist_autonumber)02d - %(title)s.%(ext)s' --embed-thumbnail --embed-metadata

it doesnt get the track number

~~unrelated but i had to change `ARTIST` & `YT-DLP` manually since `%(artist)s` & `%(album)s` spew `<unknown>`. do you know how to fix the above?`~~

**Comment by october262** [comment]
try this - https://superuser.com/questions/1313121/how-to-add-track-numbers-to-the-filename-with-youtube-dl

**Comment by yant0** [comment]
> '(playlist_autonumber)02d - %(title)s.%(ext)s'

exactly the same point
i was asking this since my player sort song by track number not filenames. Alternatively, how to put song's track number with filenames would be helpful

**Comment by october262** [comment]
> > '(playlist_autonumber)02d - %(title)s.%(ext)s'
> 
> exactly the same thing i was asking this since my player sort song by track number (metadata) not filenames. Alternatively, how to put song's track number with filenames would be helpful

try yt-dlp --auto-number url  - https://askubuntu.com/questions/694848/how-to-download-a-youtube-playlist-with-numbered-prefix-via-youtube-dl

**Comment by yant0** [comment]
im not asking for a prefix, im asking for track number metadata

**Comment by yant0** [comment]
found it [(reddit)](https://www.reddit.com/r/youtubedl/comments/l8bie6/how_to_fill_track_number_metadata_on_an_mp3_with/glcos4l/)

new
```
yt-dlp -o '%(playlist_uploader)s/%(playlist_title)s/%(playlist_autonumber)02d - %(title)s.%(ext)s' --embed-thumbnail --parse-metadata 'playlist_index:%(track_number)s' --add-metadata --embed-metadata
```

closed
