### ISSUE TITLE
Instagram : Unable to download webpage: HTTP Error 500:

### ISSUE THREAD

**Issue by RingoTheDog** [yt-dlp/yt-dlp#1702]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2021.11.10.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Canada

### Description

This is probably going to fall into the "can't reproduce" category, but here we go....

Even with a --cookies file I am recieiving errors when trying to download files from instagram  
Unfortunately, this is not consistant...sometimes it works...sometime it does not.

Initally I was seening:
ERROR: [Instagram] CV86ozbAkOa: You need to log in to access this content. Use --cookies, --username and --password, or --netrc to provide account credentials
Even with the --cookies file

...then I saw HTTP Error 500  (see verbose log below)

Due to the random responses I am seeing this may be very hard to troubleshoot.
Please let me know if there are any more details I can provide.

Thanks in advance
Ringo

### Verbose log

```shell
yt-dlp.py -v "https://www.instagram.com/p/CV86ozbAkOa/" --cookies instagram.com_cookies.txt
[debug] Command-line config: ['-v', 'https://www.instagram.com/p/CV86ozbAkOa/', '--cookies', 'instagram.com_cookies.txt']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2021.11.10.1 (zip)
[debug] Python version 3.6.6 (CPython 64bit) - Windows-10-10.0.14393-SP0
[debug] exe versions: ffmpeg 4.3.2-2021-02-02-full_build-www.gyan.dev, ffprobe 4.3.2-2021-02-02-full_build-www.gyan.dev, rtmpdump 2.4
[debug] Optional libraries: sqlite
[debug] Proxy map: {}
[debug] [Instagram] Extracting URL: https://www.instagram.com/p/CV86ozbAkOa/
[Instagram] CV86ozbAkOa: Downloading webpage
ERROR: [Instagram] CV86ozbAkOa: Unable to download webpage: HTTP Error 500: Internal Server Error (caused by <HTTPError 500: 'Internal Server Error'>); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output. (caused by <HTTPError 500: 'Internal Server Error'>); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
  File "C:\Transmogrifier\yt-dlp.py\yt_dlp\extractor\common.py", line 713, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "C:\Transmogrifier\yt-dlp.py\yt_dlp\YoutubeDL.py", line 3295, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "C:\Program Files\Python36\lib\urllib\request.py", line 532, in open
    response = meth(req, response)
  File "C:\Program Files\Python36\lib\urllib\request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Program Files\Python36\lib\urllib\request.py", line 570, in error
    return self._call_chain(*args)
  File "C:\Program Files\Python36\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "C:\Program Files\Python36\lib\urllib\request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
```

**Comment by RingoTheDog** [comment]
So just for giggles, I opened that instagram video in chrome and re-exported my cookies file.
Now I am recieving a different error:



`yt-dlp.py -v "https://www.instagram.com/p/CV86ozbAkOa/" --cookies instagram.com_cookies.txt
[debug] Command-line config: ['-v', 'https://www.instagram.com/p/CV86ozbAkOa/', '--cookies', 'instagram.com_cookies.txt']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2021.11.10.1 (zip)
[debug] Python version 3.6.6 (CPython 64bit) - Windows-10-10.0.14393-SP0
[debug] exe versions: ffmpeg 4.3.2-2021-02-02-full_build-www.gyan.dev, ffprobe 4.3.2-2021-02-02-full_build-www.gyan.dev, rtmpdump 2.4
[debug] Optional libraries: sqlite
[debug] Proxy map: {}
[debug] [Instagram] Extracting URL: https://www.instagram.com/p/CV86ozbAkOa/
[Instagram] CV86ozbAkOa: Downloading webpage
WARNING: [Instagram] unable to extract og:video:height; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
WARNING: [Instagram] unable to extract og:video:width; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] CV86ozbAkOa: Downloading 1 format(s): dash-18200416771141004vd+dash-17907417959276898ad
WARNING: Requested formats are incompatible for merge and will be merged into mkv
[debug] Invoking downloader on "https://instagram.fybz2-2.fna.fbcdn.net/v/t66.30100-16/169749299_4988114994549318_598765012444608674_n.webm?_nc_ht=instagram.fybz2-2.fna.fbcdn.net&_nc_cat=106&_nc_ohc=_kj95wZ9AIwAX_TL7jz&edm=AABBvjUBAAAA&ccb=7-4&oh=7e8ce730c4220200af569f4fea16106b&oe=6197A337&_nc_sid=83d603"
ERROR: unable to open for writing: [Errno 13] Permission denied: 'Video by lululemon [CV86ozbAkOa].fdash-18200416771141004vd.webm.part'
Traceback (most recent call last):
  File "C:\Transmogrifier\yt-dlp.py\yt_dlp\downloader\http.py", line 267, in download
    ctx.tmpfilename, ctx.open_mode)
  File "C:\Transmogrifier\yt-dlp.py\yt_dlp\utils.py", line 2094, in sanitize_open
    stream = open(encodeFilename(filename), open_mode)
PermissionError: [Errno 13] Permission denied: 'Video by lululemon [CV86ozbAkOa].fdash-18200416771141004vd.webm.part'


[debug] Invoking downloader on "https://instagram.fymy1-1.fna.fbcdn.net/v/t50.16885-16/254352613_885967122086183_3257552944131858502_n.mp4?_nc_ht=instagram.fymy1-1.fna.fbcdn.net&_nc_cat=111&_nc_ohc=0b1JzBmCyAYAX99ssl7&edm=AABBvjUBAAAA&ccb=7-4&oh=12703a1071977af94b2d0351ce4cb2ed&oe=6197AA3A&_nc_sid=83d603"
ERROR: unable to open for writing: [Errno 13] Permission denied: 'Video by lululemon [CV86ozbAkOa].fdash-17907417959276898ad.m4a.part'
Traceback (most recent call last):
  File "C:\Transmogrifier\yt-dlp.py\yt_dlp\downloader\http.py", line 267, in download
    ctx.tmpfilename, ctx.open_mode)
  File "C:\Transmogrifier\yt-dlp.py\yt_dlp\utils.py", line 2094, in sanitize_open
    stream = open(encodeFilename(filename), open_mode)
PermissionError: [Errno 13] Permission denied: 'Video by lululemon [CV86ozbAkOa].fdash-17907417959276898ad.m4a.part'
`

**Comment by october262** [comment]
this link - https://www.instagram.com/p/CV86ozbAkOa/ worked ok for me.
didn't need to use cookies either. from what i can find, the  HTTP Error 500 
seems to be a server error.

**Comment by pukkandan** [comment]
It works when not giving cookies. I can reproduce the first error when cookies are given. The second error is unrelated and is because some program in your system is locking the file

**Comment by pukkandan** [comment]
Re-exporting the cookies fixes the issue. So I am not sure there is anything that can be done about this

**Comment by RingoTheDog** [comment]
understood ...thank you for your time
