### ISSUE TITLE
ALAC codec support and more audio features

### ISSUE THREAD

**Issue by CZeil** [yt-dlp/yt-dlp#1707]
### Checklist

- [X] I'm reporting a feature request
- [X] I've verified that I'm running yt-dlp version **2021.11.10.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

It is possible that they could implement the alac codec for audio extraction, also audio sampling rate options 44KHz - 44.1KHz - 96KHz - 192KHz for ALAC and FLAC codec.

**Comment by pukkandan** [comment]
what? Explain exactly what u r asking for

**Comment by CZeil** [comment]
> what? Explain exactly what u r asking for

Only if you could implement some parameters that ffmpeg has in yt-dlp for example these are some of them with which I did conversion of a mp3 song:
  -aq 0 -acodec alac -ac 5 -ar 192000 -sample_fmt s32p -vcodec copy.
I don't know if I made myself clear

**Comment by lvqcl** [comment]
honestly, that's beyond stupid.

**Comment by CZeil** [comment]
> honestly, that's beyond stupid.

What do you think is stupid?

**Comment by pukkandan** [comment]
I can add `alac` as an allowed format to `-x --audio-format`. But any other args you need to pass, you have to do with `--ppa`

**Comment by CZeil** [comment]
> I can add `alac` as an allowed format to `-x --audio-format`. But any other args you need to pass, you have to do with `--ppa`

Basically you are telling me that you can add it but that I have to change the sample rate with --ppa...?

**Comment by CZeil** [comment]
> Yes, I can add `alac`. But it isnt reasonable to add new options for each ffmpeg option

I understand, well if you add the codec it will benefit me a lot, thanks for the support pukkandan
