### ISSUE TITLE
Ignore "&feature=share" in URL

### ISSUE THREAD

**Issue by Rexadev** [yt-dlp/yt-dlp#1710]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2021.11.10.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

Ignore "&feature=share" in at the end of URL

### Verbose log

```shell
https://music.youtube.com/watch?v=VideoID_**&feature=share**_

[youtube] VideoID: Downloading webpage
[youtube] VideoID: Downloading android player API JSON
[youtube] VideoID: Downloading android music player API JSON
[youtube] VideoID: Downloading web_music config
[youtube] VideoID: Downloading player 
[youtube] VideoID: Downloading web music player API JSON
[info] VideoID: Downloading 1 format(s): 251
[info] Downloading video thumbnail ...
[info] Writing video thumbnail to: Downloads\Music\Stan.webp
[SubtitlesConvertor] There aren't any subtitles to convert
[download] Destination: VideoTitle.webm
[download] 100% of 5.77MiB in 00:01
[ExtractAudio] Destination: VideoTitle.opus
Deleting original file Downloads\Music\Stan.webm (pass -k to keep)
[EmbedSubtitle] Subtitles can only be embedded in mp4, webm or mkv files
[Metadata] Adding metadata to "VideoTitle.opus"
[ThumbnailsConvertor] Converting thumbnail "VideoTitle.webp" to png
[EmbedThumbnail] mutagen: Adding thumbnail to "VideoTitle.opus"
Deleting original file VideoTitle.png (pass -k to keep)
Deleting original file VideoTitle.webp (pass -k to keep)
[XAttrMetadata] Writing metadata to file's xattrs
ERROR: Postprocessing: Invalid argument
_**'feature' is not recognized as an internal or external command,
operable program or batch file.**_
```

**Comment by Ashish0804** [comment]
>I've checked that all URLs and arguments with special characters are properly quoted or escaped

Have you tho? Can you paste log with url in quotes?

Something like
yt-dlp "url" or yt-dlp 'url'

**Comment by nyuszika7h** [comment]
It should be double quotes (`""`) since you're using the Windows command prompt.

In PowerShell and on macOS/Linux, single quotes (`''`) would work too.

**Comment by Rexadev** [comment]
> It should be double quotes (`""`) since you're using the Windows command prompt.
> 
> In PowerShell and on macOS/Linux, single quotes (`''`) would work too.

Please Explain

**Comment by pukkandan** [comment]
Instead of blindly ticking the checkboxes, read the provided link

> - [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)

**Comment by Rexadev** [comment]
> Instead of blindly ticking the checkboxes, read the provided link
> 
> > * [x]  I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)

The URL in not in quotes I used markdown for bold and italics

**Comment by MinePlayersPE** [comment]
> The URL in not in quotes I used markdown for bold and italics

@Rexadev ...yes, we're saying that the URL *needs* to be in quotes to be properly escaped

**Comment by Rexadev** [comment]
> > The URL in not in quotes I used markdown for bold and italics
> 
> @Rexadev ...yes, we're saying that the URL _needs_ to be in quotes to be properly escaped

Ok Thanks you 
This (https://github.com/yt-dlp/yt-dlp#usage-and-options) should be updated
or
"&feature=share" should be cleaned at input

**Comment by nyuszika7h** [comment]
> "&feature=share" should be cleaned at input

That's not possible. When you run the command in question, it is split by the Windows Command Prompt into two separate commands: `yt-dlp https://music.youtube.com/watch?v=VideoID` and `feature=share`. It is impossible for yt-dlp to know there was a `&` or anything after it. By quoting it as `yt-dlp "https://music.youtube.com/watch?v=VideoID&feature=share"`, you will tell the command prompt to pass the whole URL unmodified to yt-dlpp.
