### ISSUE TITLE
All 4/Channel 4 Site Support

### ISSUE THREAD

**Issue by nmills3** [yt-dlp/yt-dlp#1719]
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2021.11.10.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

United Kingdom

### Example URLs

- Single video: https://www.channel4.com/programmes/gurren-lagann/on-demand/69960-001

### Description

It would be nice for this to work as this site includes a lot of free TV content in the UK

### Verbose log

```shell
[debug] Command-line config: ['https://www.channel4.com/programmes/gurren-lagann/on-demand/69960-001', '--verbose']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2021.11.10.1 (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] exe versions: ffmpeg 4.1.3, ffprobe 4.1.3
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [generic] Extracting URL: https://www.channel4.com/programmes/gurren-lagann/on-demand/69960-001
[generic] 69960-001: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] 69960-001: Downloading webpage
[generic] 69960-001: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://www.channel4.com/programmes/gurren-lagann/on-demand/69960-001
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1311, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1336, in __extract_info
  File "yt_dlp\extractor\common.py", line 595, in extract
  File "yt_dlp\extractor\generic.py", line 3766, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.channel4.com/programmes/gurren-lagann/on-demand/69960-001
```

**Comment by u-spec-png** [comment]
DRM:
![2021-11-19_16-06-999](https://user-images.githubusercontent.com/54671367/142645035-d359df71-f5ff-4a45-af0c-68258f61aa04.png)

**Comment by pukkandan** [comment]
@u-spec-png Do you know if all content on the site has DRM?

**Comment by nmills3** [comment]
Sorry about that. How do you check if a site has DRM or not?

**Comment by nyuszika7h** [comment]
If you use Firefox, it will show an icon in the address bar when playing DRM-protected content. For Chrome, you can install [EME Logger](https://greasyfork.org/en/scripts/373903-eme-logger) and see if it prints a bunch of EME/Widevine-related stuff to the console.

**Comment by pukkandan** [comment]
No need to be sorry. The checkbox is there because a lot of people were requesting sites that they knew full well has DRM/piracy. I don't expect most normal users to be able to actually determine whether sites have DRM. So honest mistakes are fine

That said, if the site has no non-DRM content, it obv cant be supported
