### ISSUE TITLE
Download only a segment of a video?

### ISSUE THREAD

**Issue by paul1149** [yt-dlp/yt-dlp#1724]
### Checklist

- [X] I'm asking a question and not reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

Is it possible to specify the start and end points for a video download? I know this is possible using ffmpeg directly, but it's quite detailed and laborious. I would like to do this during the download operation, not as a post-process edit.

Thanks.

**Comment by pukkandan** [comment]
https://github.com/yt-dlp/yt-dlp/issues/686#issuecomment-904191812

**Comment by paul1149** [comment]
Thanks, pukkandan, I missed that in my search. Works great!
