### ISSUE TITLE
Separate output template for thumbnail appears broken

### ISSUE THREAD

**Issue by Sarioah** [yt-dlp/yt-dlp#1726]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2021.11.10.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

I've been trying to name my thumbnails separately to my videos, as per the output template examples, but it seems like the option is ignored. 

Using 
`'-o' 'thumbnail:%(uploader)s %(upload_date)s %(title)s (%(id)s) thumb.%(ext)s'` and 
`'-o' '%(uploader)s %(upload_date)s %(title)s (%(id)s).%(ext)s'`
results in 
`/home/sari/test/Raiz Space 20211119 Kerbal Space Program with RO - Solar System Tourism 43 (mdTsmMXAUk8).webp`
When it should be
`/home/sari/test/Raiz Space 20211119 Kerbal Space Program with RO - Solar System Tourism 43 (mdTsmMXAUk8) thumb.webp`

### Verbose log

```shell
sari@plexbox:~/test$ yt-dlp --config-location ./config -v https://www.youtube.com/watch?v=mdTsmMXAUk8
[debug] Command-line config: ['--config-location', './config', '-v', 'https://www.youtube.com/watch?v=mdTsmMXAUk8']
[debug] Custom config file: ./config
[debug] Custom config: ['-ciR', '10', '-f', 'best', '--write-thumbnail', '--download-archive', './archive.txt', '--downloader', 'native', '-P', '~/test/', '-o', 'thumbnail:%(uploader)s %(upload_date)s %(title)s (%(id)s) thumb.%(ext)s', '-o', '%(uploader)s %(upload_date)s %(title)s (%(id)s).%(ext)s']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2021.11.10.1
[debug] Python version 3.8.10 (CPython 64bit) - Linux-5.4.0-90-generic-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4
[debug] Optional libraries: Cryptodome, keyring, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] Loading archive file './archive.txt'
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=mdTsmMXAUk8
[youtube] mdTsmMXAUk8: Downloading webpage
[youtube] mdTsmMXAUk8: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[info] mdTsmMXAUk8: Downloading 1 format(s): 22
[info] Downloading video thumbnail 41 ...
[info] Writing video thumbnail 41 to: /home/sari/test/Raiz Space 20211119 Kerbal Space Program with RO - Solar System Tourism 43 (mdTsmMXAUk8).webp
[debug] Invoking downloader on "https://r3---sn-ntq7yney.googlevideo.com/videoplayback?expire=1637406550&ei=9oKYYcqYIOmRssUP4sqP0AY&ip=203.169.22.204&id=o-ALrHPvAmWo7vyaa1xnkLyl5i8BAusIeiAuo3PAoQ616v&itag=22&source=youtube&requiressl=yes&mh=XO&mm=31%2C29&mn=sn-ntq7yney%2Csn-ntqe6n76&ms=au%2Crdu&mv=m&mvi=3&pl=23&initcwndbps=380000&vprv=1&mime=video%2Fmp4&cnr=14&ratebypass=yes&dur=936.019&lmt=1637381445557419&mt=1637384211&fvip=3&fexp=24001373%2C24007246&c=ANDROID&txp=6311224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Ccnr%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRQIgG2LDJ1N490l0uByRMj1khN3loqFlglU2CV7fkCqii0gCIQDbJ6IHCfL41IAuNlSM90o4n8DUX0gF88TUzVM7nuJVkQ%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhANaAiC7R7OWkyK42y16n2IhYCUh_KYHDK0WgfZ5T5jsmAiEA45QgRdjTeYe3dVckZoXV9BK2cij8HnESMELp8xCH1ek%3D"
[download] Destination: /home/sari/test/Raiz Space 20211119 Kerbal Space Program with RO - Solar System Tourism 43 (mdTsmMXAUk8).mp4
[download]   3.1% of 99.85MiB at  1.57MiB/s ETA 01:01^C
ERROR: Interrupted by user
```

**Comment by pukkandan** [comment]
Let the process finish

**Comment by Sarioah** [comment]
That's.....a bit counterintuitive / annoying but thanks 👍

**Comment by pukkandan** [comment]
The codebase inherited from youtube-dl has some limitations that forces the thumbnail to initially have the same name as the video. Due to recent changes to the code, I think this limitation may not exist now. I will have a look if the renaming at the end can be avoided - but no promises
