### ISSUE TITLE
[StreamCZ] Unsupported URL error

### ISSUE THREAD

**Issue by herkul-s** [yt-dlp/yt-dlp#1731]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2021.11.10.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Czech Republic

### Description

I'm trying to pass a URL from stream.cz, but I'm receiving an Unsupported URL error. 

### Verbose log

```shell
yt-dlp -F "https://www.stream.cz/peklonataliri/ecka-pro-deti-189752" --verbose
[debug] Command-line config: ['-F', 'https://www.stream.cz/peklonataliri/ecka-pro-deti-189752', '--verbose']
[debug] Encodings: locale cp1250, fs utf-8, out utf-8, err utf-8, pref cp1250
[debug] yt-dlp version 2021.11.10.1 (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19042-SP0
[debug] exe versions: ffprobe 3.4.1
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [generic] Extracting URL: https://www.stream.cz/peklonataliri/ecka-pro-deti-189752
[generic] ecka-pro-deti-189752: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] ecka-pro-deti-189752: Downloading webpage
[generic] ecka-pro-deti-189752: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://www.stream.cz/peklonataliri/ecka-pro-deti-189752
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1311, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1336, in __extract_info
  File "yt_dlp\extractor\common.py", line 595, in extract
  File "yt_dlp\extractor\generic.py", line 3766, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.stream.cz/peklonataliri/ecka-pro-deti-189752
```

**Comment by dirkf** [comment]
See https://github.com/ytdl-org/youtube-dl/issues/30160#issuecomment-953363936.

**Comment by arkamar** [comment]
#1616 should fix this.
