### ISSUE TITLE
I want to use a domain name or an extractor name in the output template.

### ISSUE THREAD

**Issue by sheepwng** [yt-dlp/yt-dlp#1732]
### Checklist

- [X] I'm reporting a feature request
- [X] I've verified that I'm running yt-dlp version **2021.11.10.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

I want to use a domain name or an extractor name in the output template.

My template
`--output "my folder\%%(channel)s\%%(playlist_title)s\%%(upload_date)s-%%(title)s.%%(ext)s"`

I want to keep them in separate folders.
`--output "my folder\%%(extractor)s\%%(channel)s\%%(playlist_title)s\%%(upload_date)s-%%(title)s.%%(ext)s"`
D:\my folder\youtube\.......
D:\my folder\bilibili\......
D:\my folder\niconico\......

`--output "my folder\%%(domain)s\%%(channel)s\%%(playlist_title)s\%%(upload_date)s-%%(title)s.%%(ext)s"`
D:\my folder\youtube.com\.......
D:\my folder\bilibili.com\......
D:\my folder\nicovideo.jp\......

**Comment by Zirro** [comment]
Using `%(extractor)s` works for me. The double `%%` characters may be the real cause of your issues. Try removing one of them for each field.

**Comment by sheepwng** [comment]
I'm sorry. I didn't realize that the feature existed.
I used `%%(extractor)s` and it worked fine.
