### ISSUE TITLE
yt-dlp: command not found

### ISSUE THREAD

**Issue by PeaceMaker2001** [yt-dlp/yt-dlp#1733]
### Checklist

- [X] I'm asking a question and not reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

```
~$ python3 -m pip install -U yt-dlp
Collecting yt-dlp
  Downloading yt_dlp-2021.11.10.1-py2.py3-none-any.whl (2.4 MB)
     |████████████████████████████████| 2.4 MB 1.0 MB/s 
Collecting mutagen
  Downloading mutagen-1.45.1-py3-none-any.whl (218 kB)
     |████████████████████████████████| 218 kB 4.3 MB/s 
Collecting pycryptodomex
  Downloading pycryptodomex-3.11.0-cp35-abi3-manylinux2010_x86_64.whl (1.9 MB)
     |████████████████████████████████| 1.9 MB 932 kB/s 
Collecting websockets
  Downloading websockets-10.1-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (110 kB)
     |████████████████████████████████| 110 kB 8.9 MB/s 
Installing collected packages: mutagen, pycryptodomex, websockets, yt-dlp
  WARNING: The scripts mid3cp, mid3iconv, mid3v2, moggsplit, mutagen-inspect and mutagen-pony are installed in '/home/dakota/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script yt-dlp is installed in '/home/dakota/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed mutagen-1.45.1 pycryptodomex-3.11.0 websockets-10.1 yt-dlp-2021.11.10.1
~$ man yt-dlp
No manual entry for yt-dlp
~$ yt-dlp -h
yt-dlp: command not found
~$ yt-dlp
yt-dlp: command not found
```
Salutations. I've tried installing yt-dlp as a PyPI package, and it appears that the program is not functional, probably because the directory it's installed to is not on PATH (Whatever that means?). Can this be fixed by adding the directory to PATH and if so, how?
I'm not very knowledgeable about the terminal and how everything works in it...

**Comment by Ashish0804** [comment]
>WARNING: The script yt-dlp is installed in '/home/dakota/.local/bin' which is not on PATH.

Google `How to add a folder to path in <your distro name>`

**Comment by PeaceMaker2001** [comment]
Yep, XD I'm such a newb. I've edited my .bashrc file and added the directory where yt-dlp resides. Works like a charm!
https://linuxize.com/post/how-to-add-directory-to-path-in-linux/



> > WARNING: The script yt-dlp is installed in '/home/dakota/.local/bin' which is not on PATH.
> 
> Google `How to add a folder to path in <your distro name>`

Appreciate your response and your time.

**Comment by lee321987** [comment]
Just wanted to say that I saw the same error (right after installing yt-dlp), but after exiting and restarting WSL it worked.

**Comment by Andybasicasd** [comment]
replace "yt-dlp -h" to "/home/dakota/.local/bin/yt-dlp -h"
