### ISSUE TITLE
Discovery Plus - Unable to Choose Language

### ISSUE THREAD

**Issue by jack-sparrow1** [yt-dlp/yt-dlp#1739]
### Checklist

- [X] I'm asking a question and not reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

Is there a way to download video from DSCV+ India and include different language tracks.

This is the response from the master.m3u8 file, but I'm unable to download it in English. It keeps downloading it in the default language.
```
#EXTM3U
#EXT-X-INDEPENDENT-SEGMENTS

#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="stereo_128000",NAME="Hindi",LANGUAGE="hi",AUTOSELECT=YES,DEFAULT=YES,URI="audio-hi-a57a7b6e-e20c-4d74-9ff4-b12a5a5c08ca/video-128000bps.m3u8"
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="stereo_128000",NAME="English",LANGUAGE="en",AUTOSELECT=YES,URI="audio-en-989bf02e-15aa-4916-abd2-273c60b91bb1/video-128000bps.m3u8"

#EXT-X-MEDIA:TYPE=SUBTITLES,GROUP-ID="subtitle_group",NAME="English",LANGUAGE="en",AUTOSELECT=YES,CHARACTERISTICS="public.accessibility.describes-music-and-sound",URI="caption-en/captions.m3u8"
```

**Comment by pukkandan** [comment]
Show output of `yt-dlp -vUF URL`

**Comment by jack-sparrow1** [comment]
```
[debug] Command-line config: ['-vUF', 'https://dplusindia-google-v3.prod-vod.h264.io/b8e8/c019/60bc/0051575d-baf7-4c4b-bac5-b3b224e93295/ts-raw/x-goog-token=Expires=1637498669']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2021.11.10.1 (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] exe versions: ffmpeg N-104591-g8c150d3d97-20211119 (setts), ffprobe N-104591-g8c150d3d97-20211119
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
yt-dlp is up to date (2021.11.10.1)
[debug] [generic] Extracting URL: https://dplusindia-google-v3.prod-vod.h264.io/b8e8/c019/60bc/0051575d-baf7-4c4b-bac5-b3b224e93295/ts-raw/x-goog-token=Expires=1637498669
[generic] x-goog-token=Expires=1637498669: Requesting header
WARNING: [generic] Could not send HEAD request to https://dplusindia-google-v3.prod-vod.h264.io/b8e8/c019/60bc/0051575d-baf7-4c4b-bac5-b3b224e93295/ts-raw/x-goog-token=Expires=1637498669: HTTP Error 403: Forbidden
[generic] x-goog-token=Expires=1637498669: Downloading webpage
ERROR: [generic] Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output. (caused by <HTTPError 403: 'Forbidden'>); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
  File "yt_dlp\extractor\common.py", line 713, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 3295, in urlopen
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 649, in http_error_default

'KeyName' is not recognized as an internal or external command,
operable program or batch file.
'Signature' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by pukkandan** [comment]
See the `[en]`/`[hi]` in `MORE INFO`. That is the language yt-dlp has detected. So you can do `-f bv+ba[language=en]` to select the best english version, for example

**Comment by jack-sparrow1** [comment]
Hey I tried this. but it did not work. Is there something wrong the code that I used

`yt-dlp --cookies discovery_cookies.txt https://www.discoveryplus.in/videos/tech-billionaires-in/elon-musk?type=EPISODE&seasonId=1 -f bv+ba[language=en]`

**Comment by Ashish0804** [comment]
Provide logs.

**Comment by jack-sparrow1** [comment]
Not exactly sure how to generate logs. Need a little help on that part. 

`--verbose` ?

**Comment by pukkandan** [comment]
> [debug] Command-line config: ['--verbose', '--cookies', 'discovery_cookies.txt', 'https://www.discoveryplus.in/videos/tech-billionaires-in/elon-musk?type=EPISODE']

You haven't passed any -f argument

**Comment by jack-sparrow1** [comment]
> > [debug] Command-line config: ['--verbose', '--cookies', 'discovery_cookies.txt', 'https://www.discoveryplus.in/videos/tech-billionaires-in/elon-musk?type=EPISODE']
> 
> You haven't passed any -f argument. Make sure your command is quoted properly


I used this command to download the video
`yt-dlp --cookies discovery_cookies.txt https://www.discoveryplus.in/videos/tech-billionaires-in/elon-musk?type=EPISODE&seasonId=1 -f bv+ba[language=en]`

Am I doing something wrong here?

**Comment by MinePlayersPE** [comment]
> `yt-dlp --cookies discovery_cookies.txt https://www.discoveryplus.in/videos/tech-billionaires-in/elon-musk?type=EPISODE&seasonId=1 -f bv+ba[language=en]`

> `'seasonId' is not recognized as an internal or external command,
operable program or batch file.`

@jack-sparrow1 put the url in double quotes to properly escape them

**Comment by Ashish0804** [comment]
>[download] Elon Musk [55978].mp4 has already been downloaded

delete this file first.
run `yt-dlp <your shit> -F url` first
then 
`yt-dlp <your shit> url`

If it doesn't work then paste output of both of them.
Not every url on DSCV+IN has languages or hls

**Comment by jack-sparrow1** [comment]
> > `yt-dlp --cookies discovery_cookies.txt https://www.discoveryplus.in/videos/tech-billionaires-in/elon-musk?type=EPISODE&seasonId=1 -f bv+ba[language=en]`
> 
> > `'seasonId' is not recognized as an internal or external command, operable program or batch file.`
> 
> @jack-sparrow1 put the url in double quotes to properly escape them

This solved the issue. Thanks all for the help.
