### ISSUE TITLE
yt-dlp has virus?

### ISSUE THREAD

**Issue by vikralthakur** [yt-dlp/yt-dlp#174]
Is yt-dlp version 2021.03.15 safe? At first, chrome blocked the download, so I checked the file on VT,

![yt-dlp_screen](https://user-images.githubusercontent.com/79197429/111272126-2fac5800-8658-11eb-8b45-42d2b31304c0.png)

**Comment by pukkandan** [comment]
See the pinned issue https://github.com/yt-dlp/yt-dlp/issues/25
