### ISSUE TITLE
Bilibili international extractor doesn't work after recent website update (bilibili.tv / Bstation)

### ISSUE THREAD

**Issue by beam2546** [yt-dlp/yt-dlp#1744]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2021.11.10.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Thailand but likely to be accessible for most SEA countries

### Description

It was working until recent update 3 days ago where they introducing quality setting, volume control and pick subtitle language

### Verbose log

```shell
beam@Beams-MacBook-Air ~ % yt-dlp -Uv "https://www.bilibili.tv/th/play/35111/350277"
[debug] Command-line config: ['-Uv', 'https://www.bilibili.tv/th/play/35111/350277']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2021.11.10.1
[debug] Git HEAD: 819eea566
[debug] Python version 3.10.0 (CPython 64bit) - macOS-12.0.1-arm64-arm-64bit
[debug] exe versions: ffmpeg 4.4.1 (setts), ffprobe 4.4.1
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
yt-dlp is up to date (2021.11.10.1)
[debug] [BiliIntl] Extracting URL: https://www.bilibili.tv/th/play/35111/350277
[BiliIntl] 350277: Downloading JSON metadata
ERROR: [BiliIntl] 350277: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output. (caused by <HTTPError 404: 'Not Found'>); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
  File "/opt/homebrew/Cellar/yt-dlp/2021.11.10.1/libexec/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 713, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/opt/homebrew/Cellar/yt-dlp/2021.11.10.1/libexec/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3295, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/opt/homebrew/Cellar/python@3.10/3.10.0_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/opt/homebrew/Cellar/python@3.10/3.10.0_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/opt/homebrew/Cellar/python@3.10/3.10.0_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/opt/homebrew/Cellar/python@3.10/3.10.0_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/opt/homebrew/Cellar/python@3.10/3.10.0_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
```

**Comment by kyliezero** [comment]
I also experienced it, I hope someone can fix it

**Comment by minhngoc25a** [comment]
@pukkandan You can test the new site interface with this link: https://www.bilibili.tv/en/play/37549

That is a link to a series, **Bilibili New Year's Eve Gala**, which is not geo-blocked anywhere. The new site interface broke yt-dlp by adding the ability to switch subtitles plus many changes in the video player. The episode list is no longer a horizontal list but a vertical list, located to the right of the video player. The new interface also gained the ability to search for other series.

I hope that much information is helpful!
