### ISSUE TITLE
this program is complete shit

### ISSUE THREAD

**Issue by fuckyoutubedl** [yt-dlp/yt-dlp#1745]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2021.11.10.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

SHUT THE SITE DOWN AND SLIT YORU WRIST YOU FUCKING CUCKS @pukkandan @shirt-dev @Ashish0804 STUPID FAGGOTS I WILL RAPE YOUR SISTERS AND MOTHERS AT WILL MOTHERFUCKERS. HOW CAN IT BE SO DAMN HARD TO MAKE A PROGRAM THAT ACTUALLY WORKS? I SPENT HOURS LOOKING AT THE DOCUMENTATION LEARNING HOW THIS PIECE OF SHIT WORKS AND IT DOESNT WANT TO COOPERATE. I RECOMMEND LIGHTING YOURSELF ON FIRE, YOU SELFHATING UGLY SHITSKIN SUBHUMAN FAGGOTS.

![man-on-fire](https://user-images.githubusercontent.com/94801146/142774002-4e0b8ddc-d12a-4eab-9dec-04a6332084a6.gif)
 

### Verbose log

```shell
-v
-v
-v
-v
-v
-vvvvv
```

**Comment by Ashish0804** [comment]
![image](https://user-images.githubusercontent.com/39122144/142774697-f6bb823e-91ce-4de5-881d-0aa29551085f.png)
commandlets keep seething 😎
