### ISSUE TITLE
[Help] fixing mtimes on already local files

### ISSUE THREAD

**Issue by EdWoow** [yt-dlp/yt-dlp#1747]
### Checklist

- [X] I'm asking a question and not reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

Is it possible to make yt-dlp change the mtime on already downloaded files? Assumed, I have downloaded a playlist with --no-mtime and would like to fix the times of the files to what they would have been if I had used --mtime (default) in the first hand. 

I've tried: --postprocessor-args FixupTimestamp but that did not what I have been hoping for and
--use-postprocessor FixupTimestamp:when="after_move"
just produces an error. Any chance to fix mtimes otherwise, as I may not fully understand the man page?

**Comment by pukkandan** [comment]
`FixupTimestamp` has nothing to do with mtime

I don't think it is possible. The mtime is calculated from `Last-Modified` header during download

**Comment by EdWoow** [comment]
Thanks very much for your explanation
