### ISSUE TITLE
How to check integrity of downloaded video at post processor stage ?

### ISSUE THREAD

**Issue by nastia-diaphan** [yt-dlp/yt-dlp#1750]
### Checklist

- [X] I'm asking a question and not reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

All my downloaded files are automated with API. Very rarely I have found video that freeze some seconds and after re-download it is obvious that some fragments were skipped.

when using CLI sometimes but rarely (and then I have no log) we can see errors on downloading stage.
```
...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 102 (attempt 9 of 10)...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 102 (attempt 10 of 10)...
[download] Skipping fragment 102...
....
```
If it is not the first fragment, the process continue to the end. I believe.

I can certainly take action at post processor stage to retry if that stage is informed of downloading problem. 

But may be, I'm taking the wrong way....

**Comment by nyuszika7h** [comment]
This may work:
```
ffmpeg -v error -xerror -i out.mp4 -f null -
```

**Comment by nastia-diaphan** [comment]
Interesting, thank you @nyuszika7h 

Unfortunately, I have for now no video that is for sure missing some fragment. I will read online and if this command is not too resource intensive, I will launch it on all my videos.

**Comment by nastia-diaphan** [comment]
if no error, ffmpeg is completely silent. 
Here is the find command to check all my already downloaded videos (must be run with mp4 too) and I can see the progress.

```
find /youtube/ -name \*.webm -printf '%p\n' -exec ffmpeg -v error -xerror -i {} -f null - 2>ffmpeg-error.log \;
```
Thank you @nyuszika7h.

Will I find some missing fragments ?

**Comment by pukkandan** [comment]
You can also use `--abort-on-unavailable-fragment` to ensure the download doesn't proceed if there are missing fragments in the first place

**Comment by nastia-diaphan** [comment]
thank you @pukkandan, but I prefer partial then nothing. I just want to known if it need a retry.

Access to `[download]` console information from `post process` would be great. Can I find a solution by looking at `progress_hooks` ?

**Comment by pukkandan** [comment]
If you are using API, You can have access to the console message in `logger`. Another trick is to replace `FragmentFD.report_skip_fragment` with your custom hook. Something like this:

```py
from yt_dlp.downloader.fragment import FragmentFD

def skip_fragment_hook(self, frag_index, err=None):
    # do stuff
    ...

FragmentFD.report_skip_fragment = skip_fragment_hook
```

**Comment by nastia-diaphan** [comment]
Thank you @pukkandan, this look like very useful.

**Comment by nastia-diaphan** [comment]
Checking at post processor stage the presence of a file with .ytdl extension is enough to schedule a retry.
But this file seem to exist only if download is broken. I have only 3 on my disk and all are broken at fragment 0 which is fatal even with `--abort-on-unavailable-fragment: False`

My strategy:

1. keeping all fragments
2. if a fragment is skipping, create a file with ext. .part.ytdl (maybe with list of missing fragments).
3. at post processor stage check the presence of this file.
4. if exist: schedule retry and delete this file and if not, delete all fragments.

Questions:
- I don't know how to use `--keep-fragments` with API  lol
- I don't know where to put `FragmentFD.report_skip_fragment = skip_fragment_hook`

**Comment by pukkandan** [comment]
> all are broken at fragment 0 which is fatal even with --abort-on-unavailable-fragment: False

Media will be unplayable without the first fragment. Hence why it is considered fatal.

> if a fragment is skipping, create a file with ext. .part.ytdl (maybe with list of missing fragments).

Use some other extension (or even better, just use a variable in ur program). `.ytdl` files are used for resuming downloads. Manually writing such files may case unexpected behavior

> I don't know how to use --keep-fragments with API lol

`keep_fragments`

> I don't know where to put FragmentFD.report_skip_fragment = skip_fragment_hook

anywhere before running `YoutubeDL(...).download`

**Comment by nastia-diaphan** [comment]
I have though about `keep_fragments` but it didn't work. No fragments are kept.
Now I thing that dash format is not so frequent within my selection of formats.

___________

```
from yt_dlp.downloader.fragment import FragmentFD

def skip_fragment_hook(self, frag_index, err=None):
    # do stuff
    ...

FragmentFD.report_skip_fragment = skip_fragment_hook
```
If I understand, with this hook mechanism, I can hack almost all yt-dlp :+1:

**Comment by pukkandan** [comment]
> Now I thing that dash format is not so frequent within my selection of formats.

> Moreover I misunderstand what is dash. I'm sure that I already sew number of fragments before downloading, and today, nothing.

Unless you show your code and verbose log, how would I know?

**Comment by nastia-diaphan** [comment]
OK option was working... `[dashsegments] Total fragments: 10` and fragments are kept.

But for that, I must choose a format with dash protocol. As we can see below, `m4a_dash` does not mean that this format is send with dash protocol, and is using fragments.
```
ID       EXT  RESOLUTION FPS │  FILESIZE    TBR PROTO │ VCODEC        VBR ACODEC     ABR  ASR    MORE INFO
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
139-dash m4a  audio only     │  420.10KiB  50k  dash  │                   mp4a.40.5  50k 22050Hz DASH audio, m4a_dash
140-dash m4a  audio only     │  1.09MiB   130k  dash  │                   mp4a.40.2 130k 44100Hz DASH audio, m4a_dash
251-dash webm audio only     │  1.03MiB   136k  dash  │                   opus      136k 48000Hz DASH audio, webm_dash
139      m4a  audio only     │  420.10KiB  48k  https │                   mp4a.40.5  48k 22050Hz low, m4a_dash
140      m4a  audio only     │  1.09MiB   129k  https │                   mp4a.40.2 129k 44100Hz medium, m4a_dash
251      webm audio only     │  1.03MiB   122k  https │                   opus      122k 48000Hz medium, webm_dash

```
As we can see too, the very same file (some differences but file size is the same) is sent in dash and in https protocol. My actual selection is https. But which one is the best for our job ? and why ?

**Comment by pukkandan** [comment]
Youtube is known to provide incorrect bitrate information for DASH. The two sets of formats are actually the exact same (except for delivery method). I would recommend downloading without dash whenever possible
