### ISSUE TITLE
[itv.py] broken: "ERROR: 'dict_items' object is not reversible"

### ISSUE THREAD

**Issue by Vangelis66** [yt-dlp/yt-dlp#1758]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2021.11.10.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

England/United Kingdom

### Description

Using latest `yt-dlp_x86.exe` built on CPython 3.7.9 (32-bit);
using a **whitelisted** UK VPN, as my real location is overseas... 😉 
Trying to fetch last Sunday's "An Audience with... Adele", 

https://www.itv.com/hub/an-audience-with/L0055a0007

which is up already on the ITV Hub...

Sadly, current `yt-dlp` chokes with:

`ERROR: 'dict_items' object is not reversible` 😭 

The **itvIE** was inherited in a broken state from upstream, but was fixed (?) in release **2021.09.25** (see PRs #913 and #1001); v**2021.09.25** is itself broken, producing the same error as the latest one: 

```
yt-dlp --version =>
2021.09.25

yt-dlp -F "https://www.itv.com/hub/an-audience-with/L0055a0007" => 
[ITV] L0055a0007: Downloading webpage
ERROR: 'dict_items' object is not reversible
```
Below is the "History" of file `itv.py`: 

https://github.com/yt-dlp/yt-dlp/commits/master/yt_dlp/extractor/itv.py

I have a local build compiled from source cc33cc4, which dates from Sept 14th, i.e. **after** PR #913 but **prior to** PR #1001; that one build **works**: 

```
yt-dlp --version =>
2021.09.02+44-git-20210914-gcc33cc4

yt-dlp -F "https://www.itv.com/hub/an-audience-with/L0055a0007" =>
[ITV] L0055a0007: Downloading webpage
[ITV] L0055a0007: Downloading JSON metadata
[ITV] L0055a0007: Downloading m3u8 information
[info] Available formats for L0055a0007:
ID       EXT RESOLUTION FPS |   TBR PROTO  | VCODEC        VBR ACODEC     ABR
-------- --- ---------- --- - ----- ------ - ----------- ----- --------- ----
hls-68   mp4 audio only     |   68k m3u8_n |                   mp4a.40.2  64k
hls-102  mp4 audio only     |  102k m3u8_n |                   mp4a.40.2  96k
hls-285  mp4 512x288    25  |  285k m3u8_n | avc1.4D401F  203k mp4a.40.2  64k
hls-636  mp4 512x288    25  |  636k m3u8_n | avc1.4D401F  503k mp4a.40.2  96k
hls-848  mp4 512x288    25  |  848k m3u8_n | avc1.4D401F  703k mp4a.40.2  96k
hls-1272 mp4 896x504    25  | 1272k m3u8_n | avc1.4D401F 1103k mp4a.40.2  96k
hls-1908 mp4 896x504    25  | 1908k m3u8_n | avc1.4D401F 1703k mp4a.40.2  96k
```
What also works is if I compile **upstream** (`youtube-dl`) with **locally merged** upstream PR [#28955](https://github.com/ytdl-org/youtube-dl/pull/28955):

```
youtube-dl --version => 
2021.06.06+18-git-20210701-ga803582+PR#28955v2

youtube-dl -F "https://www.itv.com/hub/an-audience-with/L0055a0007" => 
[ITV] L0055a0007: Downloading webpage
[ITV] L0055a0007: Downloading JSON metadata
[ITV] L0055a0007: Downloading m3u8 information
[ITV] L0055a0007: Downloading JSON metadata
[info] Available formats for L0055a0007:
format code  extension  resolution note
hls-68       mp4        audio only   68k , mp4a.40.2@ 64k
hls-102      mp4        audio only  102k , mp4a.40.2@ 96k
hls-285      mp4        512x288     285k , avc1.4D401F@ 203k, 25.0fps, mp4a.40.2@ 64k
hls-636      mp4        512x288     636k , avc1.4D401F@ 503k, 25.0fps, mp4a.40.2@ 96k
hls-848      mp4        512x288     848k , avc1.4D401F@ 703k, 25.0fps, mp4a.40.2@ 96k
hls-1272     mp4        896x504    1272k , avc1.4D401F@1103k, 25.0fps, mp4a.40.2@ 96k
hls-1908     mp4        896x504    1908k , avc1.4D401F@1703k, 25.0fps, mp4a.40.2@ 96k (best)
```
Thus, my money is on PR #1001 as being somehow the cause for my predicament... 
@coletdjnz , any thoughts?

Many thanks in advance!

### Verbose log

```shell
[debug] Command-line config: ['--ffmpeg-location', '..', '--downloader-args', 'ffmpeg:-v 8 -stats', '-F', 'https://www.itv.com/hub/an-audience-with/L0055a0007', '-Uv']
[debug] Encodings: locale cp1253, fs utf-8, out utf-8 (No ANSI), err utf-8 (No ANSI), pref cp1253
[debug] yt-dlp version 2021.11.10.1 (win_exe)
[debug] Python version 3.7.9 (CPython 32bit) - Windows-Vista-6.0.6003-SP2
[debug] exe versions: ffmpeg 4.4.1 (setts), ffprobe 4.4.1
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
yt-dlp is up to date (2021.11.10.1)
[debug] Using fake IP 25.49.40.96 (GB) as X-Forwarded-For
[debug] [ITV] Extracting URL: https://www.itv.com/hub/an-audience-with/L0055a0007
[ITV] L0055a0007: Downloading webpage
ERROR: 'dict_items' object is not reversible
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1311, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1336, in __extract_info
  File "yt_dlp\extractor\common.py", line 595, in extract
  File "yt_dlp\extractor\itv.py", line 149, in _real_extract
TypeError: 'dict_items' object is not reversible
```

**Comment by pukkandan** [comment]
I get a 403 for that URL and I don't have access to a GB VPN atm
If you can, try and check whether this patch fixes your issue
```diff
diff --git a/yt_dlp/extractor/itv.py b/yt_dlp/extractor/itv.py
index 6e6a3673c..10aedc496 100644
--- a/yt_dlp/extractor/itv.py
+++ b/yt_dlp/extractor/itv.py
@@ -146,7 +146,7 @@ class ITVIE(InfoExtractor):
         # See: https://github.com/yt-dlp/yt-dlp/issues/986
         platform_tag_video, featureset_video = next(
             ((platform_tag, featureset)
-             for platform_tag, featuresets in reversed(variants.items()) for featureset in featuresets
+             for platform_tag, featuresets in reversed(list(variants.items())) for featureset in featuresets
              if try_get(featureset, lambda x: x[:2]) == ['hls', 'aes']),
             (None, None))
         if not platform_tag_video or not featureset_video:
```

**Comment by pukkandan** [comment]
This is why the bug remained undetected so far:
https://docs.python.org/3/library/stdtypes.html#dict-views
![image](https://user-images.githubusercontent.com/6623388/142963191-e6dbdce1-5336-4cc7-8456-6a61f68eef23.png)

**Comment by Vangelis66** [comment]
> This is why the bug remained undetected so far:
> https://docs.python.org/3/library/stdtypes.html#dict-views
>```
>reversed(dictview)
>
>    Return a reverse iterator over the keys, values or items of the dictionary. The view will be iterated in reverse order of the insertion.
>
>    Changed in version 3.8: Dictionary views are now reversible.
>```

Thank you very much for **identifying the root cause of/addressing** my issue so swiftly! 🥇 
Out of pure curiosity 😜 , I dug out `yt-dlp_x86.exe` download counts, as reported by GitHub itself, for versions affected, and it looks like below:

- `2021.09.25`   =  3762
- `2021.10.09`   =   414
- `2021.10.10`   =  5028
- `2021.10.22`   =  8906
- `2021.11.10`   =   153
- `2021.11.10.1` = 11970

(a total of 30,233 downloads - of course, actual _user numbers_ can be much lower, as the **same** user updates from older to newer releases); from a statistical point of view, it shows that the **itvIE** is a niche one among users of the `yt-dlp_x86.exe` binary (and among those still on py**3.6**/**3.7** on various other environments); had it been otherwise, I'd have expected the bug to surface much sooner...

And, pardon me for asking 😉 , don't you have some **automated checks in place** to check for and identify such types of "syntax" bugs between the **various Python versions** (3.6-3.9?) `yt-dlp` currently supports? 
This time it was **itvIE**, in the same context it could possibly be some other IE in the future, could it not? 😄 

Hugely indebted, keep up your unwavering efforts!
