### ISSUE TITLE
Could yt-dlp be used for mpv streaming?

### ISSUE THREAD

**Issue by erickyun** [yt-dlp/yt-dlp#176]
Can I use yt-dlp for mpv?

And also could yt-dlp use not ffmpeg but **Aria2c as the external downloader** when mpv is used for streaming?

I want this cuz aria2c downloads faster CR videos than ffmpeg.

Would something like this work for yt-dlp?
`ytdl-raw-options=cookies="/storage/emulated/0/download/cookies.txt",external-downloader=aria2,external-downloader-args:aria2c="-x 16 -s 16 -k 1M"`

**Comment by pukkandan** [comment]
`mpv` uses `youtube-dl`/`yt-dlp` only for getting the URL and actually downloads using `ffmpeg`. So external-downloader will be ignored. Also, see #142

**Comment by erickyun** [comment]
> `mpv` uses `youtube-dl`/`yt-dlp` only for getting the URL and actually downloads using `ffmpeg`. So `external-downloader` will be ignored.
> 
> Also, see #142 and [its workaround](https://github.com/yt-dlp/yt-dlp/issues/142#issuecomment-791782721)

I understand Thank you for your explanation.
