### ISSUE TITLE
--download-archive file format extending

### ISSUE THREAD

**Issue by QuAzI** [yt-dlp/yt-dlp#1762]
### Checklist

- [X] I'm reporting a feature request
- [X] I've verified that I'm running yt-dlp version **2021.11.10.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

Is there any way to save additional information in additional columns?
- episode url
- file name in -o format (a.k.a. `%(title)s [%(id)s].%(ext)s` by default)
- sha1 file checksum

**Comment by pukkandan** [comment]
As explained in https://github.com/yt-dlp/yt-dlp/issues/1172, download-archive's one and only purpose is to facilitate the "already recorded in archive" detection. It's formatting will not be expanded.

You can write whatever data you want to a separate file using `--exec`. Eg: `--exec "echo %(extractor)s %(id)s %(filepath)s>videos.txt`

**Comment by QuAzI** [comment]
Sometimes it is difficult to understand by Id if file already downloaded or not. E.g. same series from other source. Or source reupload series with new ID.
But thanks for `--exec`

**Comment by QuAzI** [comment]
`--exec` fired even for files which already downloaded before. It fired for files which not downloaded in current session. So it will be fired for old files each time when new episodes added to season page (my source doesn't have per episode link).

**Comment by pukkandan** [comment]
Use archive to prevent re-downloading of videos, use --exec if you want a human-readable database. There is nothing preventing you from using both at the same time
