### ISSUE TITLE
--batch-file file format extending

### ISSUE THREAD

**Issue by QuAzI** [yt-dlp/yt-dlp#1763]
### Checklist

- [X] I'm reporting a feature request
- [X] I've verified that I'm running yt-dlp version **2021.11.10.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

It will be nice to have something like
```
some.site/url ./destination_path
some.site/season1 "./01 season"
some.site/season2 "./02 season"
some.site/ova "./03 ova"
```
to save all series to special destination right from batch

**Comment by pukkandan** [comment]
There is nothing special about the  output template as opposed to other options. So  basically, what you want it to be able to specify different options for diferent URLs. In that case, why not just make it a batch file?
```
yt-dlp some.site/url -o "./destination_path"
yt-dlp some.site/season1 -o "./01 season"
...
```

**Comment by QuAzI** [comment]
Too much items will be in each string. Too much scripting required each time. Also in my case `batch-file` can be CSV separated by tabs or spaces

**Comment by pukkandan** [comment]
I don't understand. How is that any harder than putting the filenames in the `-a` file?

> Also in my case batch-file can be CSV separated by tabs or spaces

Sounds like it is better off to write your own wrapper. I am not going to add support for CSV or other new formats

**Comment by QuAzI** [comment]
CSV with tabs in simple cases is just file which looks like
```
column1    column2
url             destination
```
but `\t` used instead of spaces. So `\s+` to split fields still fine. You don't need to write full CSV support

**Comment by QuAzI** [comment]
I've tested this behavior to check just links for this format. Spaces and tabs around line trimmed fine. But if line contains multiple columns it crashes because trying to match full line like URL
