### ISSUE TITLE
CP24 (should be added to 9c9media extractor)

### ISSUE THREAD

**Issue by RingoTheDog** [yt-dlp/yt-dlp#1768]
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2021.11.10.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Canada

### Example URLs

- Single video: https://www.cp24.com/news/video-shows-atm-being-ripped-out-of-business-by-pickup-truck-driver-in-mississauga-1.5676877
- Single video: https://www.cp24.com/video?binId=1.1127680

### Description

[CP24](https://en.wikipedia.org/wiki/CP24) is a Canadian English-language specialty news channel owned by Bell Media.

I believe CP24.COM should be added to 9c9media extractor as it is part of BellMedia.

### Verbose log

```shell
>yt-dlp.py -v "https://www.cp24.com/news/video-shows-atm-being-ripped-out-of-business-by-pickup-truck-driver-in-mississauga-1.5676877"
[debug] Command-line config: ['-v', 'https://www.cp24.com/news/video-shows-atm-being-ripped-out-of-business-by-pickup-truck-driver-in-mississauga-1.5676877']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2021.11.10.1 (zip)
[debug] Python version 3.6.6 (CPython 64bit) - Windows-10-10.0.14393-SP0
[debug] exe versions: ffmpeg 4.3.2-2021-02-02-full_build-www.gyan.dev, ffprobe 4.3.2-2021-02-02-full_build-www.gyan.dev, rtmpdump 2.4
[debug] Optional libraries: sqlite
[debug] Proxy map: {}
[debug] [generic] Extracting URL: https://www.cp24.com/news/video-shows-atm-being-ripped-out-of-business-by-pickup-truck-driver-in-mississauga-1.5676877
[generic] video-shows-atm-being-ripped-out-of-business-by-pickup-truck-driver-in-mississauga-1: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] video-shows-atm-being-ripped-out-of-business-by-pickup-truck-driver-in-mississauga-1: Downloading webpage
[generic] video-shows-atm-being-ripped-out-of-business-by-pickup-truck-driver-in-mississauga-1: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://www.cp24.com/news/video-shows-atm-being-ripped-out-of-business-by-pickup-truck-driver-in-mississauga-1.5676877
Traceback (most recent call last):
  File "C:\Transmogrifier\yt-dlp.py\yt_dlp\YoutubeDL.py", line 1311, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Transmogrifier\yt-dlp.py\yt_dlp\YoutubeDL.py", line 1336, in __extract_info
    ie_result = ie.extract(url)
  File "C:\Transmogrifier\yt-dlp.py\yt_dlp\extractor\common.py", line 595, in extract
    ie_result = self._real_extract(url)
  File "C:\Transmogrifier\yt-dlp.py\yt_dlp\extractor\generic.py", line 3766, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.cp24.com/news/video-shows-atm-being-ripped-out-of-business-by-pickup-truck-driver-in-mississauga-1.5676877
```

**Comment by Ashish0804** [comment]
Can be used using `'9c9media:cp24_web:2328005'` as url for `https://www.cp24.com/news/video-shows-atm-being-ripped-out-of-business-by-pickup-truck-driver-in-mississauga-1.5676877`

**Comment by Ashish0804** [comment]
@RingoTheDog provide all possible URLs for `https://www.cp24.com/*` else i'll just hardcode `https://www.cp24.com/news/` if it's the only one.
Also i doubt the live url would be downloadable

**Comment by RingoTheDog** [comment]
Yes cp24.com/news is the only sub dir with video that I could find.  (most of the videos URLs are /video?binId=)
There is /lifestyle, /world and a few others, but only articles I believe...no video content that I could find.

Thank you sir!

**Comment by Ashish0804** [comment]
/video ones are handled by another extractor (generic afaik) already
