### ISSUE TITLE
[Broken] AMCNetworks

### ISSUE THREAD

**Issue by 2ShedsJackson** [yt-dlp/yt-dlp#177]
- [x] I'm reporting a broken site support
- [x] I've verified that I'm running yt-dlp version **2021.03.15**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] User config file: C:\lib\yt-dlp.conf
[debug] User config: ['--ap-mso', 'PRIVATE', '--ap-username', 'PRIVATE', '--ap-password', 'PRIVATE']
[debug] Home config file: yt-dlp.conf
[debug] Home config: ['--ap-mso', 'PRIVATE', '--ap-username', 'PRIVATE', '--ap-password', 'PRIVATE']
[debug] Command-line config: ['--verbose', 'https://www.amc.com/shows/talking-dead/episodes/season-10-episode-24-on-the-walking-dead-1019--54270']
[debug] Loading archive file None
[debug] Encodings: locale cp1252, fs utf-8, out cp1252, pref cp1252
[debug] yt-dlp version 2021.03.15 (exe)
[debug] Python version 3.8.7 (CPython 64bit) - Windows-10-10.0.18362-SP0
[debug] exe versions: ffmpeg 4.3.1-2020-10-01-full_build-www.gyan.dev, ffprobe 4.3.1-2020-10-01-full_build-www.gyan.dev, phantomjs 2.1.1
[debug] Proxy map: {}
[AMCNetworks] shows/talking-dead/episodes/season-10-episode-24-on-the-walking-dead-1019--54270: Downloading JSON metadata
[AMCNetworks] shows/talking-dead/episodes/season-10-episode-24-on-the-walking-dead-1019--54270: Downloading JSON metadata
[AMCNetworks] MdqNc4oS_P6P: Downloading Provider Redirect Page
[AMCNetworks] MdqNc4oS_P6P: Downloading Provider Login Page
[AMCNetworks] MdqNc4oS_P6P: Logging in
[AMCNetworks] MdqNc4oS_P6P: Confirming Login
[AMCNetworks] MdqNc4oS_P6P: Retrieving Session
[AMCNetworks] MdqNc4oS_P6P: Retrieving Authorization Token
[AMCNetworks] MdqNc4oS_P6P: Retrieving Media Token
[AMCNetworks] MdqNc4oS_P6P: Downloading SMIL data
[AMCNetworks] MdqNc4oS_P6P: Downloading m3u8 information
ERROR: No video formats found; please report this issue on https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1024, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1045, in __extract_info
  File "yt_dlp\extractor\common.py", line 554, in extract
  File "yt_dlp\extractor\amcnetworks.py", line 92, in _real_extract
  File "yt_dlp\extractor\common.py", line 1663, in _sort_formats
yt_dlp.utils.ExtractorError: No video formats found; please report this issue on https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.


```

## Description

Some videos from amc.com download fine but others don't, such as this one:
https://www.amc.com/shows/talking-dead/episodes/season-10-episode-24-on-the-walking-dead-1019--54270

For this video, the m3u8 file downloaded by yt-dlp uses Fairplay protection. However, if I inspect the webpage in a browser, the m3u8 file doesn't use Fairplay.  The URLs for the two m3u8 files are of the form

https://amc-dai-amd-theplatform.akamaized.net/sp/AMC_Networks_-_AMC/567/91/hls_fp/1615316725297/1871051843874_1615313060919_1871069251586_mp4_video_1920x1080_0_primary_audio_und_6-master.m3u8?hdnea=...
and
https://amc-dai-amd-theplatform.akamaized.net/sp/AMC_Networks_-_AMC/567/91/hls_e/1615316713798/1871051843874_1615313060919_1871069251586_mp4_video_1920x1080_0_primary_audio_und_6-master.m3u8?hdnea=...

**Comment by october262** [comment]
did you try signing in with your TV provider and then try using the cookies command ??

**Comment by 2ShedsJackson** [comment]
> did you try signing in with your TV provider and then try using the cookies command ??

Doing that results in a different error:

Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1024, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1045, in __extract_info
  File "yt_dlp\extractor\common.py", line 554, in extract
  File "yt_dlp\extractor\amcnetworks.py", line 87, in _real_extract
  File "yt_dlp\extractor\adobepass.py", line 1544, in _extract_mvpd_auth
  File "yt_dlp\extractor\adobepass.py", line 1370, in post_form
  File "yt_dlp\extractor\common.py", line 1050, in _html_search_regex
  File "yt_dlp\extractor\common.py", line 1041, in _search_regex
yt_dlp.utils.RegexNotFoundError: Unable to extract post url; please report this issue on https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.

**Comment by 2ShedsJackson** [comment]
In the _real_extract in the amcnetworks.py extractor, data comes from the JSON info from the URL
https://content-delivery-gw.svc.ds.amcn.com/api/v2/content/amcn/amc/url/shows/talking-dead/episodes/season-10-episode-24-on-the-walking-dead-1019--54270

The function uses the value of videoPid to create a URL that leads to Fairplay protection-
https://link.theplatform.com/s/M_UwQC/media/z_KGAHuv2JhE? ...

If one uses the value of releasePid instead to create the URL
https://link.theplatform.com/s/M_UwQC/vD5punENmVLh? ...
then the resulting video doesn't have Fairplay and yt-dlp has no trouble with the download. Note the removal of "media/" from the URL.

I haven't yet tested this change for other videos on the site.

**Comment by pukkandan** [comment]
@2ShedsJackson Since you already have a solution, a PR would be appreciated and would save me so much time

**Comment by 2ShedsJackson** [comment]
> @2ShedsJackson Since you already have a solution, a PR would be appreciated and would save me so much time

Will do. I first looked at the code literally only a couple of days ago and I'm checking some other stuff. It's annoying that the different extractors don't follow a common template but that's inherited from youtube-dl.

But here's a question- should a thumbnail image match the video resolution or should the highest resolution be downloaded or all the resolutions?  The extractor currently downloads a 1920x1080 image for the video in this issue although a 2560x1440 version is also available.

**Comment by pukkandan** [comment]
> should a thumbnail image match the video resolution or should the highest resolution be downloaded or all the resolutions

If there are multiple thumbnails available, ideally all the thumbnails should be extracted to the `thumbnails` key. Then yt-dlp will automatically select the best one to download. Currently, there is no option for the user to choose another thumbnail than the default, but it is a planned feature

> It's annoying that the different extractors don't follow a common template but that's inherited from youtube-dl.

Due to how the different extractors work very differently, there is no way for them to be too much similar. But the overall structure is actually the same. See the documentation of `InfoExtractor` class in `extractor/common.py`

**Comment by 2ShedsJackson** [comment]
> Due to how the different extractors work very differently, there is no way for them to be too much similar. But the overall structure is actually the same. See the documentation of `InfoExtractor` class in `extractor/common.py`

Some extractors don't return thumbnails or series titles. I found another one that doesn't return season and episode info. Beyond that, I'm being picky about the lack of consistency in variable names, error reporting, etc.
