### ISSUE TITLE
Youtube slow downloads, throttling

### ISSUE THREAD

**Issue by codl** [yt-dlp/yt-dlp#1771]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2021.11.10.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

France

### Description

Downloading from Youtube is really slow. It spends a couple minutes on `Downloading webpage`, and a couple more on `Downloading android player API JSON`. Once it's downloading the video, [the shape of the traffic is odd, with bursts every 20 seconds](https://user-images.githubusercontent.com/315139/143079282-480650fe-de4b-42e1-9647-1436a7cbb76d.png). I can try to provide a packet capture, if it helps. This has happened every time I've tried to download a video in the last week or so (4-5 times).

### Verbose log

```shell
$ time yt-dlp -v --no-config "https://www.youtube.com/watch?v=1Bw2dTY3SsQ&t=2s"                                                                                                         
[debug] Command-line config: ['-v', '--no-config', 'https://www.youtube.com/watch?v=1Bw2dTY3SsQ&t=2s']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2021.11.10.1
[debug] Lazy loading extractors is disabled
[debug] Python version 3.9.7 (CPython 64bit) - Linux-5.15.2-arch1-1-x86_64-with-glibc2.33
[debug] exe versions: ffmpeg 4.4.1 (setts), ffprobe 4.4.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=1Bw2dTY3SsQ&t=2s
[youtube] 1Bw2dTY3SsQ: Downloading webpage
[youtube] 1Bw2dTY3SsQ: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 1Bw2dTY3SsQ: Downloading 1 format(s): 313+251
[debug] Invoking downloader on "https://r3---sn-cv0tb0xn-gone.googlevideo.com/videoplayback?expire=1637710941&ei=_SedYYnPMOeD6dsPi92Z0Ak&ip=31.38.14.210&id=o-ADmxrPSGSx5JJEZzsd5Dz2r7dIMCLJdEh7fdxcAap6Gl&itag=313&source=youtube&requiressl=yes&mh=Q9&mm=31%2C29&mn=sn-cv0tb0xn-gone%2Csn-25glene7&ms=au%2Crdu&mv=m&mvi=3&pcm2cms=yes&pl=17&initcwndbps=1081250&vprv=1&mime=video%2Fwebm&gir=yes&clen=365025878&dur=167.667&lmt=1637424350307622&mt=1637689013&fvip=6&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=4532434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRgIhALQQ6Ip5VxDsBAjgORvdhwUbRm55L-YAyVM_2hUxmC7JAiEA3xvWTPvVJwGGgOjTbO4-u1AwxnlpLAPytrjPiDr3KtM%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgZYZvN-w6mYNFojX0FGxyjgTV8z152N1GD5rYRU1nMm4CIAW0pycajW0Roj7u53iVhi-65lxkRqQG8LdySUjb-AhH"
[download] Destination: 100 gecs - mememe {OFFICIAL MUSIC VIDEO} [1Bw2dTY3SsQ].f313.webm
[download] 100% of 348.12MiB in 12:55                 
[debug] Invoking downloader on "https://r3---sn-cv0tb0xn-gone.googlevideo.com/videoplayback?expire=1637710941&ei=_SedYYnPMOeD6dsPi92Z0Ak&ip=31.38.14.210&id=o-ADmxrPSGSx5JJEZzsd5Dz2r7dIMCLJdEh7fdxcAap6Gl&itag=251&source=youtube&requiressl=yes&mh=Q9&mm=31%2C29&mn=sn-cv0tb0xn-gone%2Csn-25glene7&ms=au%2Crdu&mv=m&mvi=3&pcm2cms=yes&pl=17&initcwndbps=1081250&vprv=1&mime=audio%2Fwebm&gir=yes&clen=2813229&dur=167.681&lmt=1637393562096437&mt=1637689013&fvip=6&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=4532434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIgL8WdWpU32GqU8Lx2A0-jud0JpPWaExjQUzgGmPIEHY8CIQDvMm4bZoEpl-tKsZUaZQC4IRl1lFpVqrKxJHYE4UjWcQ%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgZYZvN-w6mYNFojX0FGxyjgTV8z152N1GD5rYRU1nMm4CIAW0pycajW0Roj7u53iVhi-65lxkRqQG8LdySUjb-AhH"
[download] Destination: 100 gecs - mememe {OFFICIAL MUSIC VIDEO} [1Bw2dTY3SsQ].f251.webm
[download] 100% of 2.68MiB in 00:20                 
[Merger] Merging formats into "100 gecs - mememe {OFFICIAL MUSIC VIDEO} [1Bw2dTY3SsQ].webm"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:100 gecs - mememe {OFFICIAL MUSIC VIDEO} [1Bw2dTY3SsQ].f313.webm' -i 'file:100 gecs - mememe {OFFICIAL MUSIC VIDEO} [1Bw2dTY3SsQ].f251.webm' -c copy -map 0:v:0 -map 1:a:0 'file:100 gecs - mememe {OFFICIAL MUSIC VIDEO} [1Bw2dTY3SsQ].temp.webm'
Deleting original file 100 gecs - mememe {OFFICIAL MUSIC VIDEO} [1Bw2dTY3SsQ].f313.webm (pass -k to keep)
Deleting original file 100 gecs - mememe {OFFICIAL MUSIC VIDEO} [1Bw2dTY3SsQ].f251.webm (pass -k to keep)

________________________________________________________
Executed in   16.02 mins    fish           external
   usr time    1.78 secs  272.00 micros    1.78 secs
   sys time    1.35 secs   37.00 micros    1.35 secs


$
```

**Comment by ketoeater** [comment]
Can confirm downloads are throttled in USA.

**Comment by coletdjnz** [comment]
Hmm. I may have experienced something similar not too long ago as well, but it wasn't that bad and never found out what caused it.

Has your IP been 429nd by YouTube prior to this happening by any chance? Do other sites work fine with yt-dlp?

Not sure if this is a server side issue or if YouTube is imposing some sort of throttling on making new connections.

**Comment by coletdjnz** [comment]
Note: for anyone reading this, make sure you check https://github.com/yt-dlp/yt-dlp/issues/985#issuecomment-944839974 to ensure you are not seeing something else. 

This issue is likely related to the connection requests (not the actual file/page download) being unusually slow.

**Comment by codl** [comment]
> This issue is likely related to the connection requests (not the actual file/page download) being unusually slow.

Ha, this helped me figure it out. My network recently got non-functional IPv6, meaning I have a globally-routable IPv6 address but I can't reach the internet with it. Looks like for every single request, yt-dlp tries IPv6 first and waits for a timeout before trying IPv4. If I manually remove the address, I get normal speeds again.

I'm working on getting that IPv6 functional, but until then, would be nice if yt-dlp could use happy eyeballs.

**Comment by coletdjnz** [comment]
Ah! That makes sense, given the default socket timeout. You can force yt-dlp to use IPv4 with `--force-ipv4`
