### ISSUE TITLE
[pinterest] Failed extract some videos

### ISSUE THREAD

**Issue by k3ns1n** [yt-dlp/yt-dlp#1772]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2021.11.10.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Description

Failed extract for https://pin.it/1IDcxxi link

### Verbose log

```shell
yt-dlp -v 'https://pin.it/1IDcxxi'
[debug] Command-line config: ['-v', 'https://pin.it/1IDcxxi']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2021.11.10.1
[debug] Python version 3.9.8 (CPython 64bit) - macOS-10.15.7-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.4.1 (setts), ffprobe 4.4.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [generic] Extracting URL: https://pin.it/1IDcxxi
[generic] 1IDcxxi: Requesting header
[redirect] Following redirect to https://www.pinterest.com/pin/1084663891475263837/sent/?invite_code=54ee875476024653944c129295a21dc1&sender=658651651661399279&sfo=1
[debug] [Pinterest] Extracting URL: https://www.pinterest.com/pin/1084663891475263837/sent/?invite_code=54ee875476024653944c129295a21dc1&sender=658651651661399279&sfo=1
[Pinterest] 1084663891475263837: Download Pin JSON metadata
ERROR: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "./lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1311, in wrapper
    return func(self, *args, **kwargs)
  File "./lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1336, in __extract_info
    ie_result = ie.extract(url)
  File "./lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 595, in extract
    ie_result = self._real_extract(url)
  File "./lib/python3.9/site-packages/yt_dlp/extractor/pinterest.py", line 140, in _real_extract
    return self._extract_video(data)
  File "./lib/python3.9/site-packages/yt_dlp/extractor/pinterest.py", line 38, in _extract_video
    for format_id, format_dict in data['videos']['video_list'].items():
TypeError: 'NoneType' object is not subscriptable
```

**Comment by someziggyman** [comment]
Another link that fails for some reason, same error message:
https://www.pinterest.fr/pin/616430267754192999/

Other pins seem to be working fine... strange
https://www.pinterest.com/pin/56013589110815406/
https://www.pinterest.com/pin/673499319268887982/?d=t&mt=login

**Comment by rajatvermaiam** [comment]
anybody got this?

**Comment by AlizerUncaged** [comment]
I get this error too, it seems to fail on private pins...? Not quite sure...

It **fails** on these post, these posts are from my feed:
https://www.pinterest.ph/pin/910079037172057454/
https://www.pinterest.ph/pin/783626403916675810/
https://www.pinterest.ph/pin/678917712588379220/

These posts are from search query and it **works**:
https://www.pinterest.ph/pin/592012313522225255/
https://www.pinterest.ph/pin/318770479883329551/

**Comment by rekayno** [comment]
How about fixing it? Come on, it's been a year.
