### ISSUE TITLE
[ITV] Fix "No downloads available"

### ISSUE THREAD

**Issue by staubichsauger** [yt-dlp/yt-dlp#1775]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2021.11.10.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United Kingdom

### Description

Downloading videos from ITV has stopped working today. After some debugging I found out, that I just needed to flip the array in the [itv extractor](https://github.com/yt-dlp/yt-dlp/blob/ff51ed588fa75256b98ead67bdef7edda08b66f0/yt_dlp/extractor/itv.py#L150) to be `['aes', 'hls']`. Not sure whether this is happening for others.

### Verbose log

```shell
[debug] Command-line config: ['--no-geo-bypass', '-Uv', 'https://www.itv.com/hub/im-a-celebrity-get-me-out-of-here/1a7103a0274']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2021.11.10.1 (zip)
[debug] Python version 3.9.7 (CPython 64bit) - Linux-5.14.8-arch1-1-x86_64-with-glibc2.33
[debug] exe versions: ffmpeg 4.4 (setts), ffprobe 4.4, rtmpdump 2.4
[debug] Optional libraries: Cryptodome, mutagen, sqlite
[debug] Proxy map: {}
yt-dlp is up to date (2021.11.10.1)
[debug] [ITV] Extracting URL: https://www.itv.com/hub/im-a-celebrity-get-me-out-of-here/1a7103a0274
[ITV] 1a7103a0274: Downloading webpage
ERROR: [ITV] 1a7103a0274: 1a7103a0274: No downloads available
Traceback (most recent call last):
  File "/home/tim/Videos/./yt-dlp/yt_dlp/extractor/common.py", line 595, in extract
    ie_result = self._real_extract(url)
  File "/home/tim/Videos/./yt-dlp/yt_dlp/extractor/itv.py", line 153, in _real_extract
    raise ExtractorError('No downloads available', expected=True, video_id=video_id)
yt_dlp.utils.ExtractorError: 1a7103a0274: No downloads available
Traceback (most recent call last):
  File "/home/tim/Videos/./yt-dlp/yt_dlp/extractor/common.py", line 595, in extract
    ie_result = self._real_extract(url)
  File "/home/tim/Videos/./yt-dlp/yt_dlp/extractor/itv.py", line 153, in _real_extract
    raise ExtractorError('No downloads available', expected=True, video_id=video_id)
yt_dlp.utils.ExtractorError: 1a7103a0274: No downloads available

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tim/Videos/./yt-dlp/yt_dlp/YoutubeDL.py", line 1311, in wrapper
    return func(self, *args, **kwargs)
  File "/home/tim/Videos/./yt-dlp/yt_dlp/YoutubeDL.py", line 1336, in __extract_info
    ie_result = ie.extract(url)
  File "/home/tim/Videos/./yt-dlp/yt_dlp/extractor/common.py", line 621, in extract
    raise type(e)(e.msg, **kwargs)
yt_dlp.utils.ExtractorError: [ITV] 1a7103a0274: 1a7103a0274: No downloads available
```

**Comment by Vangelis66** [comment]
> Not sure whether this is **happening for others.**

To my considerable distress 😠 , I've experienced **the exact same thing** after having compiled locally latest master snapshot, ff51ed5, which includes the fix, bc8ab44, for #1758 that I submitted only yesterday, and @pukkandan was kind enough to address very quickly...
```
yt-dlp -F "https://www.itv.com/hub/family-guy/2a4259a0372" -v => 

[debug] Command-line config: ['--ffmpeg-location', '..', '--downloader-args', 'ffmpeg:-v 8 -stats', '-F', 'https://www.itv.com/hub/family-guy/2a4259a0372', '-v']
[debug] Encodings: locale cp1253, fs utf-8, out utf-8 (No ANSI), err utf-8 (No ANSI), pref cp1253
[debug] yt-dlp version 2021.11.10.1+60-git-20211123-gff51ed5 (win_exe)
[debug] Python version 3.7.12 (CPython 32bit) - Windows-Vista-6.0.6003-SP2
[debug] exe versions: ffmpeg 4.4.1 (setts), ffprobe 4.4.1
[debug] Optional libraries: Crypto, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] Using fake IP 25.237.193.155 (GB) as X-Forwarded-For
[debug] [ITV] Extracting URL: https://www.itv.com/hub/family-guy/2a4259a0372
[ITV] 2a4259a0372: Downloading webpage
ERROR: [ITV] 2a4259a0372: 2a4259a0372: No downloads available
Traceback (most recent call last):
  File "yt_dlp\extractor\common.py", line 597, in extract
  File "yt_dlp\extractor\itv.py", line 153, in _real_extract
yt_dlp.utils.ExtractorError: 2a4259a0372: No downloads available
Traceback (most recent call last):
  File "yt_dlp\extractor\common.py", line 597, in extract
  File "yt_dlp\extractor\itv.py", line 153, in _real_extract
yt_dlp.utils.ExtractorError: 2a4259a0372: No downloads available

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1318, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1343, in __extract_info
  File "yt_dlp\extractor\common.py", line 623, in extract
yt_dlp.utils.ExtractorError: [ITV] 2a4259a0372: 2a4259a0372: No downloads available
```
To me, it's evident the ITV Hub "people" are monitoring these "apps" and just want to break our moral/nerves 😠 ...
> I found out, that I just needed to flip the array in the itv extractor to be **['aes', 'hls']**

Well spotted! 👍 🎉 

![itv](https://user-images.githubusercontent.com/9669492/143163376-683e8b9c-11fb-4209-a14a-3762bc1c97b3.JPG)

Does your "fix" (i.e. PR) also restore **subtitles**, or were they not affected by their shenanigans?

**Comment by staubichsauger** [comment]
> Does your "fix" (i.e. PR) also restore **subtitles**, or were they not affected by their shenanigans?

It seems like subtitles as well as news videos were not affected, as I was able to successfully download one of each just now.

**Comment by Vangelis66** [comment]
> It seems like subtitles as well as news videos **were not affected**

Glad to hear 😅 ; thanks for your reply, **huge** thanks for your PR 👍 ; respect for the app devs! 🥇

**Comment by Vangelis66** [comment]
I compiled just a while ago **latest master** snapshot (eb56d13), which includes PR #1776, the fix for this very issue...

Upon `-F`-ing an **ITV Hub** URL, 

`yt-dlp --no-geo-bypass -F "https://www.itv.com/hub/an-audience-with/L0055a0007" -v`, 
I noticed **exorbitant** filesizes reported for the various available quality variants: 
```
[debug] Command-line config: ['--ffmpeg-location', '..', '--downloader-args', 'ffmpeg:-v 8 -stats', '--no-geo-bypass', '-F', 'https://www.itv.com/hub/an-audience-with/L0055a0007', '-v']
[debug] Encodings: locale cp1253, fs utf-8, out utf-8 (No ANSI), err utf-8 (No ANSI), pref cp1253
[debug] yt-dlp version 2021.11.10.1+67-git-20211124-geb56d13 (win_exe)
[debug] Python version 3.7.12 (CPython 32bit) - Windows-Vista-6.0.6003-SP2
[debug] exe versions: ffmpeg 4.4.1 (setts), ffprobe 4.4.1
[debug] Optional libraries: Crypto, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [ITV] Extracting URL: https://www.itv.com/hub/an-audience-with/L0055a0007
[ITV] L0055a0007: Downloading webpage
[ITV] L0055a0007: Downloading JSON metadata
[ITV] L0055a0007: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7),vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext,aext, hasaud, source, id
[info] Available formats for L0055a0007:
ID       EXT RESOLUTION FPS |    FILESIZE   TBR PROTO  | VCODEC        VBR ACODEC    ABR
----------------------------------------------------------------------------------------
hls-68   mp4                | ~1009.54MiB   68k m3u8_n | audio only        mp4a.40.2 64k
hls-102  mp4                | ~   1.48GiB  102k m3u8_n | audio only        mp4a.40.2 96k
hls-285  mp4 512x288     25 | ~   4.13GiB  285k m3u8_n | avc1.4D401F  203k mp4a.40.2 64k
hls-636  mp4 512x288     25 | ~   9.22GiB  636k m3u8_n | avc1.4D401F  503k mp4a.40.2 96k
hls-848  mp4 512x288     25 | ~  12.29GiB  848k m3u8_n | avc1.4D401F  703k mp4a.40.2 96k
hls-1272 mp4 896x504     25 | ~  18.44GiB 1272k m3u8_n | avc1.4D401F 1103k mp4a.40.2 96k
hls-1908 mp4 896x504     25 | ~  27.66GiB 1908k m3u8_n | avc1.4D401F 1703k mp4a.40.2 96k
```
![fs](https://user-images.githubusercontent.com/9669492/143374180-800193dc-5cb9-4a03-b674-83e682175325.JPG)

FTR, the **real** filesize of the **best** variant (**hls-1908**) is ca. 930MiB: 

`[download] 100% of 930.13MiB in 13:50`

; @pukkandan, is this a known limitation/bug or should I file a **new issue** about it?

Thanks in advance for any insight... 😃

**Comment by pukkandan** [comment]
I believe those filesizes are approximated from the `tbr` and `duration`. So either of these must be wrong. I can't check this myself because of geo-restriction as I mentioned in the other issue. Better to open a new issue so that someone else may take a look

btw, please don't @ me for every single comment

**Comment by Vangelis66** [comment]
> btw, please don't @ me for every single comment

Please accept my apologies... 

> I can't check this myself because of geo-restriction as I mentioned in the other issue. 

Is there a **non-public** way I could contact you with details on how to mitigate/circumvent said geo-restriction? Just want to help, simple as that...

**Comment by pukkandan** [comment]
you can DM me on discord (https://discord.gg/H5MNcFW63r) or on reddit (/u/pukkandan), or even just email me (pukkandan.ytdlp@gmail.com)
