### ISSUE TITLE
[youtube] Incorrect metadata in SDR vp9 formats in some HDR videos

### ISSUE THREAD

**Issue by saikat0511** [yt-dlp/yt-dlp#1779]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2021.11.10.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Description

Some HDR youtube videos have incorrect metadata when downloaded in SDR vp9 format, causing issues in VLC (washed out colors). This is a known VLC bug caused by HDR to SDR tonemapping issues but it isnt supposed to happen with SDR video files.

Its caused by two metadata entries which are **not** supposed to be present in a SDR video and causing VLC to freak out. The entries are "Maximum Content Light Level : 1100" and "Maximum Frame-Average Light Level : 180".

It can be fixed by removing the above mentioned metadata entries using `MKVToolNix` (maybe its possible using ffmpeg but I don't know of any way). The command I used was `mkvpropedit -e track:1 -d max-frame-light -d max-content-light <file>`

I also noticed this issue is present in some youtube videos while not in others. For example the video [COSTA RICA IN 4K 60fps HDR (ULTRA HD)](https://www.youtube.com/watch?v=LXb3EKWsInQ) when downloaded in vp9 SDR format has the incorrect HDR metadata but [The World in HDR in 4K (ULTRA HD)](https://www.youtube.com/watch?v=tO01J-M3g0U) doesn't. Both are HDR videos. Also I couldn't find this issue in mp4 videos (atleast the ones I tested)

Is this a youtube issue or a yt-dlp? Since the videos are encoded on server-side and yt-dlp just downloads and merges I guess the problem is on youtube's side. I would have never even noticed this issue if vlc didn't have tonemapping issues.

### Verbose log

```shell
[debug] Command-line config: ['-Uv', '-f303+251', 'https://www.youtube.com/watch?v=LXb3EKWsInQ']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2021.11.10.1
[debug] Lazy loading extractors is disabled
[debug] Python version 3.9.7 (CPython 64bit) - Linux-5.15.3-lqx2-1-lqx-x86_64-with-glibc2.33
[debug] exe versions: ffmpeg 4.4.1 (setts), ffprobe 4.4.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
yt-dlp is up to date (2021.11.10.1)
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=LXb3EKWsInQ
[youtube] LXb3EKWsInQ: Downloading webpage
[youtube] LXb3EKWsInQ: Downloading android player API JSON
[debug] Loading youtube-nsig.10df06bb from cache
[debug] [youtube] Decrypted nsig g9IXL35Rr8MbgenP => lsLx25wmq7mRdQ
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr,vbr, abr, asr, vext, aext, hasaud, id
[info] LXb3EKWsInQ: Downloading 1 format(s): 303+251
[debug] Invoking downloader on "https://r3---sn-5aap5ojx-jj0s.googlevideo.com/videoplayback?expire=1637774245&ei=RR-eYenJLY-I1AbdpZa4CQ&ip=45.64.239.116&id=o-AA9Ua5mOAqWxLHUoD3gs-_VJNrRn64Ljw8qvcoPJK1WI&itag=303&source=youtube&requiressl=yes&mh=NH&mm=31%2C29&mn=sn-5aap5ojx-jj0s%2Csn-h557snzr&ms=au%2Crdu&mv=m&mvi=3&pcm2cms=yes&pl=24&initcwndbps=1165000&vprv=1&mime=video%2Fwebm&gir=yes&clen=134710778&dur=313.780&lmt=1628193060632942&mt=1637752145&fvip=3&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=1532434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRgIhAMtvMNWyY8qNftzg7TgPtYaeaynxH26jI-yJhImh5Iv1AiEA_NaBq-DPgQFtjzQvoDJ-ecM9hGVcFfvNDydK2DDaD_o%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgDXiiGvxv8c68kuY6TehM8pSYG76DLa_vQvx25lRGQb8CIBxxF5mcZUczQxUiqfFj4FOaXUfm09UkdVXK8bzFtXRh"
[download] Destination: COSTA RICA IN 4K 60fps HDR (ULTRA HD) [LXb3EKWsInQ].f303.webm
[download] 100% of 128.47MiB in 00:50
[debug] Invoking downloader on "https://r3---sn-5aap5ojx-jj0s.googlevideo.com/videoplayback?expire=1637774245&ei=RR-eYenJLY-I1AbdpZa4CQ&ip=45.64.239.116&id=o-AA9Ua5mOAqWxLHUoD3gs-_VJNrRn64Ljw8qvcoPJK1WI&itag=251&source=youtube&requiressl=yes&mh=NH&mm=31%2C29&mn=sn-5aap5ojx-jj0s%2Csn-h557snzr&ms=au%2Crdu&mv=m&mvi=3&pcm2cms=yes&pl=24&initcwndbps=1165000&vprv=1&mime=audio%2Fwebm&gir=yes&clen=5199784&dur=313.801&lmt=1625670330797558&mt=1637752145&fvip=3&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=5511222&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRgIhAKP47Ez_LMMOAErRUeHDorWakbGrk4NjrocppJRtZC-CAiEAn5t7jzL46ZsFWPPMv5MBK9p58rYnzHrzlvjxXCONjAo%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgDXiiGvxv8c68kuY6TehM8pSYG76DLa_vQvx25lRGQb8CIBxxF5mcZUczQxUiqfFj4FOaXUfm09UkdVXK8bzFtXRh"
[download] Destination: COSTA RICA IN 4K 60fps HDR (ULTRA HD) [LXb3EKWsInQ].f251.webm
[download] 100% of 4.96MiB in 00:01
[Merger] Merging formats into "COSTA RICA IN 4K 60fps HDR (ULTRA HD) [LXb3EKWsInQ].webm"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:COSTA RICA IN 4K 60fps HDR (ULTRA HD) [LXb3EKWsInQ].f303.webm' -i 'file:COSTA RICA IN 4K 60fps HDR (ULTRA HD) [LXb3EKWsInQ].f251.webm' -c copy -map 0:v:0 -map 1:a:0 'file:COSTA RICA IN 4K 60fps HDR (ULTRA HD) [LXb3EKWsInQ].temp.webm'
Deleting original file COSTA RICA IN 4K 60fps HDR (ULTRA HD) [LXb3EKWsInQ].f251.webm (pass -k to keep)
Deleting original file COSTA RICA IN 4K 60fps HDR (ULTRA HD) [LXb3EKWsInQ].f303.webm (pass -k to keep)
```

**Comment by pukkandan** [comment]
We simply download the video as-is given by youtube. You can make sure ffmpeg is not messing anything up during merge by using just `-f 303`. It is either issue with youtube or with VLC

**Comment by error-reporting** [comment]
the problem also won't show up either if your phone has proper HDR display support
