### ISSUE TITLE
Documentation needs updating to reflect subtitle changes from cffab0e which differs from yt-dl

### ISSUE THREAD

**Issue by Jules-A** [yt-dlp/yt-dlp#178]
## Checklist

- [ ] I'm reporting a broken site support issue
- [ ] I've verified that I'm running yt-dlp version **2021.03.15**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
I'm still downloading, can do this if needed later.

```

## Description

Previously subtitles would get deleted after muxing, if this is intended I don't think I saw anything in documentation about it unless I'm blind.

Using these parameters:
```https://www.crunchyroll.com/kabaneri-of-the-iron-fortress/episode-5-inescapable-darkness-790004 -o "D:\Programs\YoutubeDL\crunchyroll.com\%(series)s - S%(season_number)sE%(episode_number)s - %(episode)s - %(epoch)s.%(ext)s" --write-sub --embed-subs --sub-lang enUS --cookies "D:\Programs\YoutubeDL\cookies-crunchyroll-com.txt" --user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:86.0) Gecko/20100101 Firefox/86.0" --download-archive archive.txt --remux-video mkv -N 1```

**Comment by pukkandan** [comment]
Having `--write-sub` implies that you want to keep the subtitles after embedding. Just using `--embed-subs` will embed subs and then delete them

**Comment by Jules-A** [comment]
Is that different behavior to youtube-dl? Also it used to delete them before, what commit was it changed in (if you remember, if not dw)? So I just need to remove --write-sub now if I just want to embed them?

**Comment by pukkandan** [comment]
Yes, this is different behavior. However, this is consistent with embed-thumbnail. Let me find the commit. 1 sec

**Comment by pukkandan** [comment]
See https://github.com/yt-dlp/yt-dlp/commit/cffab0eefcb7207949dd100523d6be89ddd55ee5 and https://github.com/yt-dlp/yt-dlp/issues/57#issuecomment-775227745

> What about if it fails to embed for whatever reason?

It shouldn't delete if postprocessing fails. I didnt test though

**Comment by Jules-A** [comment]
I see thanks, you can close this if you want (I won't because I feel it needs some more info in documentation since it's different to yt-dl).

**Comment by pukkandan** [comment]
This is how `--embed-thumbnail` works and nowhere does it say in `youtube-dl`/`yt-dlp` documentation that the subtitles will be deleted when `--write-subs --embed-subs` is used. So this imo is a bug in `youtube-dl` and a change in this behaviour does not warrant any additional documentation.

However, if you make a PR to improve the documentation, I would be willing to consider it
