### ISSUE TITLE
Bring back Python v2.6+ support

### ISSUE THREAD

**Issue by YoshiKill** [yt-dlp/yt-dlp#1781]
### Checklist

- [X] I'm reporting a feature request
- [X] I've verified that I'm running yt-dlp version **2021.11.10.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

Hello! I know that my feature request is weird but any way. 
Original youtube-dl is required python v2.6+ and at this time it work on old CPU without SSE2 instruction (like Pentium 3, AthlonXP) in Windows xp OS.  
Can in future version of yt-dlp add support of older Python version like v2.6 to bring support of Old school PC and Windows XP? 
It will be great because youtube-dlp wil be very helpful way to watch YT in old OS and PC.

**Comment by Ashish0804** [comment]
Consider getting a (better) job to afford new computers instead of worrying about watching YouTube on microwaves.

**Comment by nicolaasjan** [comment]
No chance that the support will be implemented again...

Found a build for XP on a Russian forum however (use at your own risk!!!):
https://rsload.net/soft/manager/35393-yt-dlp.html
(run Google Translate if you can't read Russian)
Search for "Message # 9": 

> If anyone needs it, here are the yt-dlp builds for Windows XP:
> https://disk.yandex.ru/d/oygszhQilB1ZLg
> https://drive.google.com/drive/folders/1oxCJWNYjUQhuwRNm9Fyery_DV2utdfVp?usp=sharing

I've tried it in a XP virtual machine snapshot and it worked.

**Comment by pukkandan** [comment]
Will not be done. I have made my stance on this already clear here: https://github.com/yt-dlp/yt-dlp/issues/267#issuecomment-921943990
