### ISSUE TITLE
404 Error on Xvideos, but Site is Available

### ISSUE THREAD

**Issue by TheGrimKeeper** [yt-dlp/yt-dlp#1788]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2021.11.10.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United States

### Description

yt-dlp is returning a 404 error for all xvideos.com URLs, even though the site is alive and all videos are playable through a browser. The generic downloader works if you feed it the m3u8.

### Verbose log

```shell
[debug] Command-line config: ['-v', 'https://www.xvideos.com/video1106625/ericka_-_anal_amateur_honeymoon']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2021.11.10.1 (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19042-SP0
[debug] exe versions: ffmpeg n4.4-78-g031c0cb0b4-20210714 (setts), ffprobe n4.4-78-g031c0cb0b4-20210714
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [XVideos] Extracting URL: https://www.xvideos.com/video1106625/ericka_-_anal_amateur_honeymoon
[XVideos] 1106625: Downloading webpage
ERROR: [XVideos] 1106625: Unable to download webpage: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output. (caused by <HTTPError 404: 'Not Found'>); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
  File "yt_dlp\extractor\common.py", line 713, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 3295, in urlopen
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 649, in http_error_default
```

**Comment by abyssotrophon** [comment]
God I need this.

**Comment by TheGrimKeeper** [comment]
It looks like xnxx.com is still working, which is interesting because these two sites serve the same content.  Not sure why one is working and one is not, however.

**Comment by volpol** [comment]
The problem is that https://www.xvideos.com/video<video_id>/ URL which xvideos.py uses to download the page is not always valid. The website uses the form https://www.xvideos.com/video<video_id>/<title> and that works fine, but any random string instead of <title> works. At least for now.
