### ISSUE TITLE
Streamhub.to

### ISSUE THREAD

**Issue by DankMemz69** [yt-dlp/yt-dlp#1789]
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2021.11.10.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Example URLs

- Single video: https://streamhub.to/e/apackcdva638
- Single video: https://streamhub.to/e/x16sxaxihovi

### Description

streamhub.to is a video and file host. 

### Verbose log

```shell
[debug] Command-line config: ['-v', 'https://streamhub.to/e/apackcdva638']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, err UTF-8, pref UTF-8
[debug] yt-dlp version 2021.11.10.1
[debug] Python version 3.7.12 (CPython 64bit) - Linux-5.4.104+-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.8, ffprobe 3.4.8
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [generic] Extracting URL: https://streamhub.to/e/apackcdva638
[generic] apackcdva638: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] apackcdva638: Downloading webpage
[generic] apackcdva638: Extracting information
[debug] Looking for video embeds
[debug] Identified a HTML5 media
[download] Downloading playlist: video
[generic] playlist video: Collected 1 videos; downloading 1 of them
[download] Downloading video 1 of 1
ERROR: [generic] apackcdva638: No video formats found!; please report this issue on
```

**Comment by pukkandan** [comment]
> this site mostly hosts pirated content.

[Look like it](https://www.google.com/search?q=site%3Astreamhub.to)

@ashleyconnor You may wish to distribute it as a [plugin](https://github.com/yt-dlp/yt-dlp#plugins)
