### ISSUE TITLE
[youtube] throttling on formats with `ratebypass=yes` on WEB client

### ISSUE THREAD

**Issue by coletdjnz** [yt-dlp/yt-dlp#1796]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2021.11.10.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Description

Reposting from discord so it doesn't get lost.

When using the WEB client, formats such as 18,22 are throttled. I can confirm this is the same n-sig throttling issue as https://github.com/ytdl-org/youtube-dl/issues/29326.

This appears to be caused by the n-sig not being transformed for this format, likely as the format url has `ratebypass=yes`:
https://github.com/yt-dlp/yt-dlp/blob/eb56d132d21752fa50e0dd2c3bfa3d983ad48655/yt_dlp/extractor/youtube.py#L2517-L2525

Removing that check, it transforms the n-sig successfully and such downloads at full speed.

However, I'm not sure if this would have any impact on other client playback urls.

Originally found as part of https://github.com/yt-dlp/yt-dlp/issues/1793
Somewhat related: https://github.com/yt-dlp/yt-dlp/issues/985

### Verbose log

```shell
$ yt-dlp https://www.youtube.com/watch\?v\=DZgkF5A6e14 --extractor-args youtube:player_client=web -f 18 --force-over -v --proxy socks5://127.0.0.1:1080 --newline 
[debug] Command-line config: ['https://www.youtube.com/watch?v=DZgkF5A6e14', '--extractor-args', 'youtube:player_client=web', '-f', '18', '--force-over', '-v', '--proxy', 'socks5://127.0.0.1:1080', '--newline']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2021.11.10.1
[debug] Lazy loading extractors is disabled
[debug] Python version 3.9.7 (CPython 64bit) - Linux-5.14.10-1-MANJARO-x86_64-with-glibc2.33
[debug] exe versions: ffmpeg 4.4 (setts), ffprobe 4.4, phantomjs 2.1.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome, keyring, mutagen, sqlite, websockets
[debug] Proxy map: {'http': 'socks5://127.0.0.1:1080', 'https': 'socks5://127.0.0.1:1080'}
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=DZgkF5A6e14
[youtube] DZgkF5A6e14: Downloading webpage
[debug] Loading youtube-nsig.10df06bb from cache
[debug] [youtube] Decrypted nsig PNnUtaGfFJ_lonDw => DXRMLrMjhYhp4A
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[info] DZgkF5A6e14: Downloading 1 format(s): 18
[debug] Invoking downloader on "https://r1---sn-ntqe6n7r.googlevideo.com/videoplayback?expire=1637881258&ei=SsGfYfmiE-eo3LUP_4iz4Ag&ip=116.90.74.245&id=o-AFllJ0wstAmXlVCrFL8pL9xUDkMPTnWJAvRvfzPVGVw3&itag=18&source=youtube&requiressl=yes&mh=mi&mm=31%2C29&mn=sn-ntqe6n7r%2Csn-ntq7yner&ms=au%2Crdu&mv=m&mvi=1&pl=24&initcwndbps=573750&vprv=1&mime=video%2Fmp4&ns=NUknjPY_W2c64kT3pM_7qr8G&gir=yes&clen=25990271&ratebypass=yes&dur=560.970&lmt=1637822599459102&mt=1637859189&fvip=1&fexp=24001373%2C24007246&c=WEB&txp=5430434&n=oKBjgrG3smtpW6_0&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRQIhAIEEDpig8Pm8vM_lEkNDmmxJp2_e9TUCpgXoryPxBGpfAiAqqqHlolzwbGZV-zd4wmOKGLolgQkpM1CP_NLl2PYfJA%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgfd3EOFKto7nV7Y831RBZPR18Hz7zH9P2nbH8xsvhZVACICcm-CZCbtMtqgmhF0CBZU2aSZTX26WHv2gYLwm5neNU"
[download] Destination: Tidigare centerpartisten - Annie Lööfs dröm om den breda mitten finns inte [DZgkF5A6e14].mp4
[download]   0.0% of 24.79MiB at  5.40KiB/s ETA 01:18:18
[download]   0.0% of 24.79MiB at 16.19KiB/s ETA 26:07
[download]   0.0% of 24.79MiB at 37.74KiB/s ETA 11:12
[download]   0.1% of 24.79MiB at 80.81KiB/s ETA 05:13
[download]   0.1% of 24.79MiB at 61.82KiB/s ETA 06:50
[download]   0.2% of 24.79MiB at 56.83KiB/s ETA 07:25
[download]   0.5% of 24.79MiB at 49.25KiB/s ETA 08:33
[download]   0.6% of 24.79MiB at 53.48KiB/s ETA 07:51
[download]   0.9% of 24.79MiB at 50.51KiB/s ETA 08:17
[download]   1.1% of 24.79MiB at 50.16KiB/s ETA 08:20
[download]   1.3% of 24.79MiB at 50.30KiB/s ETA 08:18
[download]   1.5% of 24.79MiB at 50.93KiB/s ETA 08:11
[download]   1.7% of 24.79MiB at 51.93KiB/s ETA 08:00
[download]   1.9% of 24.79MiB at 51.43KiB/s ETA 08:04
```

**Comment by xioren** [comment]
might be related to https://github.com/yt-dlp/yt-dlp/issues/1793

**Comment by pukkandan** [comment]
I believe the check can be safely removed. I had originally noticed that URL with `ratebypass` are NOT getting throttled and so assumed that the transform function is not needed for it. But now it does not seem to be the case anymore

**Comment by dirkf** [comment]
Yes, a nicety that I completely (and apparently correctly) overlooked in https://github.com/ytdl-org/youtube-dl/pull/30184.
