### ISSUE TITLE
download error from tiktok

### ISSUE THREAD

**Issue by jerrylvq** [yt-dlp/yt-dlp#1798]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2021.11.10.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

yt-dlp -o '/tmp/Movies/%(uploader)s/%(title)s-%(view_count)s.%(ext)s' --proxy 127.0.0.1:1087 https://www.tiktok.com/@boxbox2805

### Verbose log

```shell
[tiktok:user] boxbox2805: Downloading webpage
ERROR: [tiktok:user] boxbox2805: Unable to extract user ID; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
```

**Comment by MinePlayersPE** [comment]
1. That's not a verbose log
2. Run the command with `--write-pages` and upload the resulting .dump files here

**Comment by pukkandan** [comment]
Closed due to inactivity
