### ISSUE TITLE
Replacing youtube-dl in third-party applications

### ISSUE THREAD

**Issue by bamper45** [yt-dlp/yt-dlp#1801]
### Checklist

- [X] I'm asking a question and not reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

Is it possible to make it work instead of youtube-dl in third party applications like radio ++ (this is an applet on cinnamon).
  She wants youtube-dl but can't download

**Comment by nyuszika7h** [comment]
Most apps should just work fine if you just rename the binary to `youtube-dl`. Some may need you to set `--compat-options youtube-dl` in the config if they depend on youtube-dl behavior that's different in yt-dlp.

**Comment by bamper45** [comment]
> Большинство приложений должно работать нормально, если вы просто переименуете двоичный файл в `youtube-dl`. Некоторым может потребоваться установить `--compat-options youtube-dl`в конфигурации, если они зависят от поведения youtube-dl, которое отличается от yt-dlp.

How to do it, how to rename
Or how to change the configuration

**Comment by nyuszika7h** [comment]
You don't know how to rename a file on a computer? Seriously?

For the configuration: https://github.com/yt-dlp/yt-dlp#configuration

**Comment by pukkandan** [comment]
If possible, you should just ask the app's devs to support yt-dlp (and other forks). But assuming that is not possible, create a symlink for youtube-dl to yt-dlp
```sh
sudo ln -s /usr/local/bin/yt-dlp /usr/local/bin/youtube-dl
```

**Comment by bamper45** [comment]
@pukkandan I have asked.
Can't find the config file

**Comment by pukkandan** [comment]
The simply create the file

**Comment by bamper45** [comment]
@pukkandan I do not know where to create

**Comment by pukkandan** [comment]
Probably `~/.config/yt-dlp/config`. Read https://github.com/yt-dlp/yt-dlp#configuration

**Comment by bamper45** [comment]
> If possible, you should just ask the app's devs to support yt-dlp (and other forks). But assuming that is not possible, create a symlink for youtube-dl to yt-dlp
> 
> ```shell
> sudo ln -s /usr/local/bin/yt-dlp /usr/local/bin/youtube-dl
> ```

Okay, that seems to work, but how do I get back if I want to?

**Comment by pukkandan** [comment]
get what back?

**Comment by bamper45** [comment]
> получить что обратно?

For example, if this does not work, and I want to return the opening of files in youtube-dl

**Comment by pukkandan** [comment]
delete `/usr/local/bin/youtube-dl` and install youtube-dl again

**Comment by bamper45** [comment]
@pukkandan I tried but writes like this

"noob @ debian: ~ $ sudo ln -s / usr / local / bin / yt-dlp / usr / local / bin / youtube-dl
[sudo] password for noob:
ln: could not create symlink '/ usr / local / bin / youtube-dl': File exists
noob @ debian: ~ $"

**Comment by nao20010128nao** [comment]
We're not computer teacher. Read error message carefully.

**Comment by bamper45** [comment]
@nao20010128nao Did I ask you? Pass by, if you don't know, noob!
