### ISSUE TITLE
[Youtube] Extract exact timestamps

### ISSUE THREAD

**Issue by HalvorRaknes** [yt-dlp/yt-dlp#1803]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2021.11.10.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

When downloading YouTube videos the timestamps given to the downloaded files are inaccurate. I suppose this can be improved by copying the method used by Youtube DataViewer (https://citizenevidence.amnestyusa.org/).

Can this be impletemented?

### Verbose log

```shell
-
```

**Comment by pukkandan** [comment]
They are probably using [Youtube Data API](https://developers.google.com/youtube/v3/getting-started) which gives the uploaded timestamp. But we can only use the innertube API which only gives the uploaded date

**Comment by HalvorRaknes** [comment]
OK. Why is it they can use that and we aren't allowed?

Also, would it be possible to extract timestampts from other video sites such as BitChute and Odysee? That would save me a bit of extraneous work doing 'touch -t' on the downloaded videoes.

**Comment by coletdjnz** [comment]
> youtube-dl will not use any kind of APIs involving sharing personal keys due to obvious reasons.
> _Originally posted by @dstftw in https://github.com/ytdl-org/youtube-dl/issues/376#issuecomment-583290045_

If you require accurate timestamps, use the official data API yourself with your own personal API key. As @pukkandan mentioned, it is not possible to get the accurate timestamp from the Innertube API or the website (unless someone manages to find a way). 

> Also, would it be possible to extract timestampts from other video sites such as BitChute and Odysee? That would save me a bit of extraneous work doing 'touch -t' on the downloaded videoes.

open a site feature request issue for each of these sites

**Comment by pukkandan** [comment]
> That would save me a bit of extraneous work doing 'touch -t' on the downloaded videoes.

Note that the mtime of the videos are NOT the `timestamp` as extracted by yt-dlp. If you want the mtime, there is no choice but to get it from the downloaded file or by probing the download URL

**Comment by pukkandan** [comment]
Closing since it is impossible afaik. If it ever becomes possible to implement (without using the Data API ofc), it can be re-opened
