### ISSUE TITLE
With yt-dlp assigning a key to a command in mpv input.conf doesn't work?

### ISSUE THREAD

**Issue by erickyun** [yt-dlp/yt-dlp#181]
I'm trying to run this command from the input.conf in mpv to save videos. The problem is
with youtube-dl it works fine but with yt-dlp it isn't working?

`
CTRL+c run "cmd.exe" "/d" "/c" "chdir /d C:/Users/aydin/Desktop && yt-dlp ${path} -f '(bv*+ba/b)[format_id!*=hardsub]' --cookies C:/Users/aydin/Desktop/yt-dl/cookies.txt --all-subs --write-sub --remux mkv --embed-subs --force-ipv4 --http-chunk-size 10M --external-downloader aria2c --external-downloader-args -x 16 -s 16 -k 10M --max-tries=1000000000 --log-level=error --log=log.txt"
`

**Comment by pukkandan** [comment]
What Is input.conf?

**Comment by erickyun** [comment]
> What Is input.conf?

Sorry forgot to write it for mpv I mean

**Comment by pukkandan** [comment]
I don't know what is the syntax for mpv config file. The issue is probably that you need to escape some characters or quote arguments. If you were directly running this, the correct syntax would be:

```cmd
cmd.exe /c "chdir /d "C:/Users/aydin/Desktop" && yt-dlp ${path} -f "(bv*+ba/b)[format_id!*=hardsub]" --cookies "C:/Users/aydin/Desktop/yt-dl/cookies.txt" --all-subs --write-sub --remux mkv --embed-subs --force-ipv4 --http-chunk-size 10M --external-downloader aria2c --external-downloader-args "-x 16 -s 16 -k 10M --max-tries=1000000000 --log-level=error --log=log.txt""
```

**Comment by erickyun** [comment]
> I don't know what is the syntax for mpv config file. The issue is probably that you need to escape some characters or quote arguments. If you were directly running this, the correct syntax would be:
> 
> ```batchfile
> cmd.exe /c "chdir /d "C:/Users/aydin/Desktop" && yt-dlp ${path} -f "(bv*+ba/b)[format_id!*=hardsub]" --cookies "C:/Users/aydin/Desktop/yt-dl/cookies.txt" --all-subs --write-sub --remux mkv --embed-subs --force-ipv4 --http-chunk-size 10M --external-downloader aria2c --external-downloader-args "-x 16 -s 16 -k 10M --max-tries=1000000000 --log-level=error --log=log.txt""
> ```

Yes thank you very much that solved it.👍🙂
