### ISSUE TITLE
[TwitCasting] Add password prompt for password locked VODs

### ISSUE THREAD

**Issue by etui-null** [yt-dlp/yt-dlp#1810]
### Checklist

- [X] I'm reporting a site feature request
- [X] I've verified that I'm running yt-dlp version **2021.11.10.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

USA

### Example URLs

https://twitcasting.tv/rurufuhizuki/movie/710660381

### Description

VODs on TwitCasting may be locked with a password. This can be bypassed by getting the m3u8 URL manually and passing in user agent and header values to either ffmpeg or yt-dlp manually after entering the password in your browser; however, you miss out on all of the extra information the extractor can parse.

And fix for this would be to detect when a password is required and prompt the user for entry. After some searching online it seems someone has added this functionality to a different fork of youtube-dl. If the code is of any interest or help, here is the commit.
https://git.furworks.de/opensourcemirror/youtube-dl/commit/88b547492f5d9440072b0037494402f46aabc810

**Comment by pukkandan** [comment]
This is already implemented. Use `--video-password` and show us the verbose log if it fails

**Comment by etui-null** [comment]
@pukkandan that worked flawlessly, thank you. I was unaware of that command line option.
