### ISSUE TITLE
The 2nd example of embedding yt-dlp is not working with Python 3.10

### ISSUE THREAD

**Issue by BigFatBass** [yt-dlp/yt-dlp#1812]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2021.11.10.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

I want to use my own format selection for the yt-dlp in my Python script. I delighted when I discovered such a possibility in the more complete example at [Embedding yt-dlp](https://github.com/yt-dlp/yt-dlp#embedding-yt-dlp). But I surprised that it is not working.

Here are the steps to reproduce it:
1. Install Python 3.10.
2. Install the yt-dlp in Python 3.10.
3. Copy-paste the code lines from the example to a python script (e.g. example.py).
4. Run the script with Python 3.10

I got the **Python exception inside build_format_selector() of the yt_dlp/YoutubeDL.py**.
The issue is reproducible in Windows 11 and Ubuntu 20.04.

The **format_selector() of the example** causes the issue. I think the **build_format_selector()** has a bug. But I'm not sure.

In any rate, I think the declared feature should work.

### Verbose log

```shell
Traceback (most recent call last):
  File "D:\Py\example.py", line 87, in <module>
    with yt_dlp.YoutubeDL(ydl_opts) as ydl:
  File "C:\Users\enygma\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 616, in __init__
    else self.build_format_selector(self.params['format']))
  File "C:\Users\enygma\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 2066, in build_format_selector
    stream = io.BytesIO(format_spec.encode('utf-8'))
AttributeError: 'function' object has no attribute 'encode'
```

**Comment by nyuszika7h** [comment]
Can you provide the code you're using? I suspect you passed something other than a string to the `format` parameter.

**Comment by pukkandan** [comment]
What yt-dlp version are you using? If you are using the release version, refer the docs of the same: https://github.com/yt-dlp/yt-dlp/tree/release#embedding-yt-dlp

The feature to use a function as `format` is not in the release yet

**Comment by BigFatBass** [comment]
> What yt-dlp version are you using? If you are using the release version, refer the docs of the same: https://github.com/yt-dlp/yt-dlp/tree/release#embedding-yt-dlp
> 
> The feature to use a function as `format` is not in the release yet
> 
> If not, show verbose log (add `'verbose': True` to the options)

I use yt-dlp version 2021.11.10.1. The verbose log is not printed due to the exception occurs earlier.

I thinked that the docs at https://github.com/yt-dlp/yt-dlp#embedding-yt-dlp refers to the release version.

Well, could you tell please when you plan to add this feature to a release?

**Comment by pukkandan** [comment]
The docs in master branch is for the master branch. Which means the feature will be available in next version
