### ISSUE TITLE
How to output / print specific metadata

### ISSUE THREAD

**Issue by dianatura** [yt-dlp/yt-dlp#1815]
### Checklist

- [X] I'm asking a question and not reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

I am wondering how I can print or output (to a file) specific metadata like upload date in the same order as the playlist (respecting if `--playlist-reverse` is used or not).

I did try to use `--write-info-json` but I could not find the upload date of each videos in the json files. I don't mind making a script to extract upload dates from individual json files, but it would be easier if that can be printed in the console directly.

Perhaps would it be possible to run a command that would output this metadata without downloading the videos ? Essentially I would like to have a way to bulk extract upload dates from a channel or playlist in a convenient way to be used elsewhere.

Sorry if this is a duplicate, thanks !

**Comment by pukkandan** [comment]
`--print`

> I did try to use --write-info-json but I could not find the upload date of each videos in the json files

Depending on the website, the upload date may not be available

**Comment by dianatura** [comment]
Oh, thanks !

Is there is a way to output `--print` to a file like `output.txt` ?

**Comment by pukkandan** [comment]
Not directly. You can always redirect stdout to a file instead
