### ISSUE TITLE
[feature request] improve '--referer' functionality (cURL/wGet)

### ISSUE THREAD

**Issue by eladkarako** [yt-dlp/yt-dlp#1816]
### Checklist

- [X] I'm reporting a feature request
- [X] I've verified that I'm running yt-dlp version **2021.11.10.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

curl --referer ";auto" follows current location, through redirects.
aria "--referer=*" will simply take the download URL and put it in the REFER header, no need to explicitly specify it.

may yt-dlp provide such simple functionality ("*" simply replaced with the current URL) to help mitigate REFER header lost when the download redirects few times..?

**Comment by pukkandan** [comment]
I don't understand your request. Can you explain with examples?

**Comment by eladkarako** [comment]
it is hard to explain.
HTTP referer header (it is a referrer without one 'r'): https://en.wikipedia.org/wiki/HTTP_referer
it helps a server to "see" where you last came from before accessing the resource.
without it many servers identifying a request to download as "hotlinking".

a workaround in many download managers is an additional switch to easily specify the referer header, "auto" or "*" are shorthand for using the current URL as the referer. curl actually goes beyond and if the response is 'redirect', it collects the last URL, which is what a browser would do.

yt-dlp has this switch but I thing it does not have a way to shorthand the URL or properly follow redirections while preserving the last URL (instead of what has entered initially).

**Comment by pukkandan** [comment]
ok, but where is it useful? Provide an example

**Comment by Zirro** [comment]
Based on OP's comments in #1817 - "product stability wise, integrating this into the product can really attract users, as the "next gen." file downloader" - I think they are under the impression that yt-dlp aims to be a general file downloader similar to aria2 or wget.

Rather, yt-dlp focuses on known video hosting sites and implementing the features required to download their content. A known use case where a site actually requires this redirect-referer behaviour to download videos would make it more relevant to implement.
