### ISSUE TITLE
[feature request] QUIC (http/3) and Brotli

### ISSUE THREAD

**Issue by eladkarako** [yt-dlp/yt-dlp#1817]
### Checklist

- [X] I'm reporting a feature request
- [X] I've verified that I'm running yt-dlp version **2021.11.10.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

it seems that CURL has builds with [QUIC](https://en.wikipedia.org/wiki/QUIC) support,  
which could smooth out quirks and boost downloads stability (for YouTube and dozens more websites).

https://everything.curl.dev/http/http3
https://daniel.haxx.se/blog/2019/08/05/first-http-3-with-curl/

for now, it can be employed into yt-dlp with external downloader arguments such as 
`--http3-direct` or `--alt-svc altcache`

wget has some early builds: https://github.com/MoofMonkey/quic-wget

aria2c not so much: https://github.com/rust-lang/rustup/pull/2212

as for python (for the native downloader)  
https://github.com/aiortc/aioquic  
wraps around the newest openssl dev and provide a very convenient handling. it is pretty stable too.

<hr/>

you may opt-in to use QUIC and brotli by default, and it will make connections and downloads (especially when downloading a huge video)

product stability wise, integrating this into the product can really attract users, as the "next gen." file downloader. and I know I've mentioned it before, but multi-part downloading from YouTube with QUIC is extremely stable and provide proper 'range' in the response.

it is extremely safe and falls back to normal http/2 if it isn't possible. it is all high-level..

**Comment by Seirdy** [comment]
This isn't something yt-dlp needs to implement. This is something that Python or external downloaders like aria2, wget, or axel should implement.

yt-dlp supports using cURL as an external downloader, and cURL can be built with support for HTTP/3 using Quiche or ngtcp2.

Since this isn't a yt-dlp issue, perhaps this issue should be closed.

**Comment by eladkarako** [comment]
update:  
curl/wget/aria2c won't release builds yet, so the only 'downloader' 
that is capable of using quic is a python w/ https://github.com/aiortc/aioquic  

there are several positive aspects of data served over QUIC (w/ Brotli),  
especially with 'google videos' servers (youtube).
it is discussed in various youtube-dl and NewPipe reddit threads.

this is a feature request (not a bug).
feel free to re-open in the future.

**Comment by eladkarako** [comment]
a wiki that tracks known implementations of QUIC.  
https://github.com/quicwg/base-drafts/wiki/Implementations  

(several native python, or c bindings to python are available).

**Comment by eladkarako** [comment]
https://www.rfc-editor.org/rfc/rfc9114.html

**Comment by pukkandan** [comment]
What?
