### ISSUE TITLE
Self-updater resets permissions

### ISSUE THREAD

**Issue by cyberbrix** [yt-dlp/yt-dlp#182]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running yt-dlp version **2021.03.15**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
Running yt-dlp -U resets the permissions on the binary.  have to run chmod a+x afterwards to ensure all users can use it.

```

## Description

WRITE DESCRIPTION HERE

**Comment by pukkandan** [comment]
Which version did you update from? Which OS?

This should have been fixed in https://github.com/yt-dlp/yt-dlp/commit/c4a508ab31f725545bb1faba10e21bc2a6416421
See https://github.com/yt-dlp/yt-dlp/issues/133

**Comment by cyberbrix** [comment]
Ubuntu 18 LTS. I don't recall which version I was on previously. I'll see how it behaves next update

**Comment by pukkandan** [comment]
I'm closing this for now then. Can reopen if you encounter the error in future updates
