### ISSUE TITLE
Portable Yt-dlp Unable to Detect .CONF Config File

### ISSUE THREAD

**Issue by hairycactus** [yt-dlp/yt-dlp#1820]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2021.11.10.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

Using Yt-dlp in portable mode on a non-system drive, Yt-dlp seems unable to detect the config file that is placed in the same folder (beside the EXE file).

To rule out this being caused by the presence of hyphen & underscore in the filename, `yt-dlp_min.exe` has been renamed to `ytp.exe` & the folder structure is as follows:-

    G:\zTemp\ytp.exe  
    G:\zTemp\ytp.conf  

The [`ytp.conf` file](https://github.com/yt-dlp/yt-dlp#configuration) (extension = conf) contains the below content:-

    # Shorten Video Filenames:
    -o "%(title).200s.%(ext)s"

    # Disable Filesystem Caching  
    --no-cache-dir  

### Observed Behaviour:
The line [`[debug] Portable config file: G:\zTemp\ytp.conf`](https://github.com/yt-dlp/yt-dlp/issues/1280#issuecomment-952313270) (ref: #1280) is missing from the verbose log. There are no lines mentioning `[debug] Portable config` in the log.

Yt-dlp fails to download from the sample video URL, & throws a `FileNotFoundError: [Errno 2] No such file or directory` error -- which is typical for Twitter URLs where the post contains an "excessive" number of characters (ref: #1280).

### Expected Behaviour:
Yt-dlp should have successfully downloaded the video with an automatically shortened filename -- as instructed by the option[ `-o "%(title).200s.%(ext)s"`](https://github.com/yt-dlp/yt-dlp/issues/1136#issuecomment-932077195) stated in the config file.

Instead, one has to manually specify a short filename using the `-o` option in the download command, & repeat this for every affected video URL, eg. `ytp -v https://twitter.com/UNDP/status/1453210331308691459  -o "OutputVideo.mp4"`.

**Tested:** Yt-dlp v2021.11.10.1 x64 & earlier versions  
**OS:** Win 10 x64

### Verbose log

```shell
G:\zTemp>ytp -v https://twitter.com/UNDP/status/1453210331308691459  

    [debug] Command-line config: ['-v', 'https://twitter.com/UNDP/status/1453210331308691459']  
    [debug] Encodings: locale cp65001, fs utf-8, out utf-8, err utf-8, pref cp65001  
    [debug] yt-dlp version 2021.11.10.1 (py2exe)  
    [debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.18363  
    [debug] exe versions: ffmpeg 4.4.1-essentials_build-www.gyan.dev (setts), ffprobe 4.4.1-essentials_build-www.gyan.dev  
    [debug] Optional libraries: mutagen, sqlite, websockets  
    [debug] Proxy map: {}  

    [debug] [twitter] Extracting URL: https://twitter.com/UNDP/status/1453210331308691459  
    [twitter] 1453210331308691459: Downloading guest token  
    [twitter] 1453210331308691459: Downloading JSON metadata  
    [twitter] 1453210331308691459: Downloading m3u8 information  

    [debug] Sort order given by extractor: res, br, size, proto  
    [debug] Formats sorted by: hasvid, ie_pref, res, tbr, vbr, abr, filesize, fs_approx, proto, lang, quality, fps, hdr:12(7), vcodec:vp9.2(10), acodec, asr, vext, aext, hasaud, source, id  
    [debug] Default format spec: bestvideo*+bestaudio/best  

    [info] 1453210331308691459: Downloading 1 format(s): http-2176  
    [debug] Invoking downloader on "https://video.twimg.com/amplify_video/1453031541362212868/vid/1280x720/vc42DdFjro3TqCaN.mp4?tag=14"  

    ERROR: unable to open for writing: [Errno 2] No such file or directory: "UN Development - We can’t ignore #ClimateChange any longer. Unless we end the excuses, we’ll be another species facing extinction.   Join us and @FrankieTheDino, and let's take #ClimateAction before it’s too late -  #DontChooseExtinction #COP26 [1453210331308691459].mp4.part"
    Traceback (most recent call last):  
      File "yt_dlp\downloader\http.pyc", line 266, in download  
      File "yt_dlp\utils.pyc", line 2094, in sanitize_open  

    FileNotFoundError: [Errno 2] No such file or directory: "UN Development - We can’t ignore #ClimateChange any longer. Unless we end the excuses, we’ll be another species facing extinction.   Join us and @FrankieTheDino, and let's take #ClimateAction before it’s too late -  #DontChooseExtinction #COP26 [1453210331308691459].mp4.part"
```

**Comment by pukkandan** [comment]
From docs:

> Portable Configuration: `yt-dlp.conf` in the same directory as the bundled binary.

The config file's name should always be `yt-dlp.conf` - even if you renamed the exe

**Comment by hairycactus** [comment]
> The config file's name should always be `yt-dlp.conf` - even if you renamed the exe

Ah ...  so that's it ! I'd thought that Yt-dlp is like other portable programs, where the config/INI file has to be the same name as the main executable. Perhaps it would be helpful to state the name requirement clearly in the `ReadMe`.

Using `yt-dlp.conf` as the filename, I confirm that Yt-dlp now detects the config file, & the Twitter video downloads successfully with a shortened 200-char filename.

### Verbose Log (beginning):
    G:\zTemp>yt -v https://twitter.com/UNDP/status/1453210331308691459
    [debug] Command-line config: ['-v', 'https://twitter.com/UNDP/status/1453210331308691459']
    [debug] Portable config file: G:\zTemp\yt-dlp.conf
    [debug] Portable config: ['-o', '%(title).200s.%(ext)s', '--no-cache-dir']
    [debug] Home config file: yt-dlp.conf
    [debug] Home config: ['-o', '%(title).200s.%(ext)s', '--no-cache-dir']
    [...]

Thanks !
