### ISSUE TITLE
Configuring both FFmpeg and Aconv in yt-dlp.conf

### ISSUE THREAD

**Issue by shortthirdman** [yt-dlp/yt-dlp#1824]
### Checklist

- [X] I'm asking a question and not reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

Hi community/dev team,

How to configure both `ffmpeg` and `aconv` in the option `--ffmpeg-location` in the configuration file - `yt-dlp.conf`. Would like to use the power of the both the tools.

I have tried setting using semicolon (;) in the string separated like - `ffmpeg_path;aconv_path` but failed.

Any suggestion and/or workarounds would be appreciated?

**Comment by pukkandan** [comment]
avconv support is deprecated for yt-dlp

**Comment by shortthirdman** [comment]
Okay @pukkandan .
