### ISSUE TITLE
downloas speed

### ISSUE THREAD

**Issue by happuji** [yt-dlp/yt-dlp#1828]
### Checklist

- [X] I'm asking a question and not reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

( so i was using youtube dl which give me only 50-60 kb speed
and now I'm using dlp  * which give me only 160-190 kb speed
but why this only I want more speed . my wifi is enough for more speed . i  am frustrated. 
i just watched some tutorial online to install them . i don't know cmd fully and I am not linux user . me a only noob of window who has only 2 week experience of using it . )

**Comment by eladkarako** [comment]
have you tried aria2c w/ yt-dlp? it got me ~twice the speed (800kbit/s to 1.7mbit/s)
<details> <summary>...</summary>
then I also copied all my google auth cookies key/value from my browser, specified refer(r)er as the same url, and used the same user agent of my chrome (navigator.userAgent). got ~5mbit/s (still not nearly close to browser's ~30mbit/s). I've tried to mock xhr header, sec-ch-ua headers w/o success, and even x-client-data and message ClientVariations header decoded..  

couldn't it get faster.  

browser fetch it as ajax shrinked w/ brotli and gQUIC and it also pre verify "non-robot" viewing w/ background captcha tech (w/o challenge),
it sums up to a client side cookie that carries along the first chunk of data to the "gvs 1.0" server, 
on optimal cases it gets no load balancing. the request has a "score". it's a heuristic sh!t. so annoying. and it is re eval. every few minutes, so the server can dynamically adjust the download rate. 
...
still better than vanilla ytdl. I just let it finish a list in the background... :|
maybe headless browser integration in the future? ¯\_(ツ)_/¯

honestly, for best results, I suggest to simply cam-recording the screen ;] 
</detail>
