### ISSUE TITLE
[TIKTOK:USER] Download only the highest rated videos of a user and dump the rest.

### ISSUE THREAD

**Issue by Theoneflop** [yt-dlp/yt-dlp#1833]
### Checklist

- [X] I'm reporting a site feature request
- [X] I've verified that I'm running yt-dlp version **2021.11.10.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Everywhere

### Example URLs

https://tiktok.com/@cashbaker

### Description

Give us the ability to tell yt-dlp to only download a user's top videos. We could give it like a 'minimum likes' of 200.0k for a video to be downloaded.

**Comment by pukkandan** [comment]
Search for `--match-filter` in the docs
