### ISSUE TITLE
needs to clarify that 'geo-bypass-country' does not support country subdivision

### ISSUE THREAD

**Issue by eladkarako** [yt-dlp/yt-dlp#1834]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2021.11.10.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

<blockquote><pre>
--geo-bypass-country CODE    Force bypass geographic restriction with
                             explicitly provided two-letter ISO 3166-2
                             country code
</pre></blockquote>

`US` works.  `US-CA` doesn't,

not sure if it is a bug, since it should have been supported,  
or that it never been supported and so just needs a documentation fix.  
..just fyi I guess.

https://en.wikipedia.org/wiki/ISO_3166-2#Current_codes
https://en.wikipedia.org/wiki/ISO_3166-2:US
https://en.wikipedia.org/wiki/ISO_3166-1

### Verbose log

```shell
ERROR: not enough values to unpack (expected 2, got 1)
Traceback (most recent call last):
  File "Dpython-3.10.0\lib\site-packages\yt_dlp\YoutubeDL.py", line 1311, in wrapper
    return func(self, *args, **kwargs)
  File "Dpython-3.10.0\lib\site-packages\yt_dlp\YoutubeDL.py", line 1336, in __extract_info
    ie_result = ie.extract(url)
  File "Dpython-3.10.0\lib\site-packages\yt_dlp\extractor\common.py", line 593, in extract
    self.initialize()
  File "Dpython-3.10.0\lib\site-packages\yt_dlp\extractor\common.py", line 496, in initialize
    self._initialize_geo_bypass({
  File "Dpython-3.10.0\lib\site-packages\yt_dlp\extractor\common.py", line 584, in _initialize_geo_bypass
    self._x_forwarded_for_ip = GeoUtils.random_ipv4(country)
  File "Dpython-3.10.0\lib\site-packages\yt_dlp\utils.py", line 5888, in random_ipv4
    addr, preflen = block.split('/')
ValueError: not enough values to unpack (expected 2, got 1)
```

**Comment by pukkandan** [comment]
The lines you quoted does say "**two-letter** ISO 3166-2 country code"

**Comment by pukkandan** [comment]
I've added a more appropriate error message in a5e3187e48d42d41c10c301483cf23c34ec93cac
