### ISSUE TITLE
how to set pagination limit or count when download youtube tag videos

### ISSUE THREAD

**Issue by wanghaisheng** [yt-dlp/yt-dlp#1835]
### Checklist

- [X] I'm asking a question and not reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

yt-dlp  --config-location config.txt https://www.youtube.com/hashtag/keyword

it seems only grab first 10 pages
look up doc,found nothing about this

**Comment by pukkandan** [comment]
Use `--playlist-end`

**Comment by wanghaisheng** [comment]
--playlist-end NUMBER            Playlist video to end at (default is last)
@pukkandan  does this mean there are only 10 for my keyword in https://www.youtube.com/hashtag

**Comment by pukkandan** [comment]
Only 10 pages? yes. If you go to the URL and scroll down, you can see that youtube only provides 10 pages

**Comment by wanghaisheng** [comment]
for example  https://www.youtube.com/hashtag/%E9%A4%8A%E7%94%9F
```
[youtube:tab] 養生: Downloading webpage
[download] Downloading playlist: #養生
[youtube:tab] 養生 page 1: Downloading API JSON
[youtube:tab] 養生 page 2: Downloading API JSON
[youtube:tab] 養生 page 3: Downloading API JSON
[youtube:tab] 養生 page 4: Downloading API JSON
[youtube:tab] 養生 page 5: Downloading API JSON
[youtube:tab] 養生 page 6: Downloading API JSON
[youtube:tab] 養生 page 7: Downloading API JSON
[youtube:tab] 養生 page 8: Downloading API JSON
[youtube:tab] 養生 page 9: Downloading API JSON
[youtube:tab] 養生 page 10: Downloading API JSON
WARNING: [youtube:tab] Incomplete data received. Retrying ...
[youtube:tab] playlist #養生: Downloading 560 videos
···

actually  there are 
11K videos • 1K channels

@pukkandan

**Comment by pukkandan** [comment]
>  If you go to the URL and scroll down, you can see that youtube only provides 10 pages

**Comment by pukkandan** [comment]
Whether it is intentional, or something broken on youtube's side, I don't know

![image](https://user-images.githubusercontent.com/6623388/143926027-026f9c10-114d-49d0-8954-a042b04e601f.png)

**Comment by wanghaisheng** [comment]
can you show me a screenshot?for me  there is none 10 pages

yes  .I can manually scroll down over 10 times

**Comment by wanghaisheng** [comment]
actually if I fix this,https://github.com/ytdl-org/youtube-dl/issues/30288
I dont need this tag api anymore,just scrape each channel id is straight foward

**Comment by pukkandan** [comment]
Wait for next release. see https://github.com/yt-dlp/yt-dlp/issues/1213

**Comment by wanghaisheng** [comment]
@pukkandan  you are so effective awesome  
FYI
if I use https://www.youtube.com/results?search_query=keyword  instead of https://www.youtube.com/hashtag/keyword 
it seems i can get all channel count and videos.
with the same config file, channel downloaded increase from 250+ to 500+ now
