### ISSUE TITLE
Fail with an error if items can't be merged instead of warning

### ISSUE THREAD

**Issue by csuhta** [yt-dlp/yt-dlp#1840]
### Checklist

- [X] I'm reporting a feature request
- [X] I've verified that I'm running yt-dlp version **2021.11.10.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

Currently, if you are using a file format flags, this warning appears _after_ you have already downloaded something:

> WARNING: You have requested merging of multiple formats but ffmpeg is not installed. The formats won't be merged.

Leaving you with a pile of files downloaded that you'd have to fix yourself.

Instead, this warning should be a hard error before anything gets downloaded. ffmpeg can't be found, you requested a file merge, and the command won't do what you want. 

> ERROR: You have requested merging of multiple formats but ffmpeg is not installed. Please install ffmpeg and re-run your command.

**Comment by pukkandan** [comment]
> Leaving you with a pile of files downloaded that you'd have to fix yourself.

You don't need to fix it yourself. Just install ffmpeg and re-run the command

**Comment by hiiamboris** [comment]
I get `WARNING: You have requested merging of multiple formats but ffmpeg is not installed. The formats won't be merged.` with `ffmpeg` available on %PATH%. How do I trick `yt-dlp` to trust me and call the command? Version `2021.12.27`

**Comment by hiiamboris** [comment]
OK I just put it into `ffmpeg` dir instead. Would be nice if it looked for `.bat` and `.cmd` files in `%PATH%` though. It must be the issue.

**Comment by pukkandan** [comment]
Whether an error or warning is given now obeys `--abort-on-error`

**Comment by BETLOG** [comment]
I had the same problem. It seems that by installing via :
`$ sudo snap install yt-dlp`
ffmpeg is not recognised

```
$ which ffmpeg
/usr/bin/ffmpeg
```

```
$ sudo apt install ffmpeg
...
ffmpeg is already the newest version (7:4.2.4-1ubuntu0.1).
0 to upgrade, 0 to newly install, 0 to remove and 5 not to upgrade.
```

and yet:
`WARNING: You have requested merging of multiple formats but ffmpeg is not installed. The formats won't be merged.
`

but after:
```
sudo apt install yt-dlp
sudo snap remove yt-dlp
```

yt-dlp calling ffmpeg works now.
