### ISSUE TITLE
How do you add a newline to --print output

### ISSUE THREAD

**Issue by Thespikedballofdoom** [yt-dlp/yt-dlp#1841]
### Checklist

- [X] I'm asking a question and not reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

I don't understand what you mean by "flag #"

/n outputs blablab/nlablabla

**Comment by pukkandan** [comment]
> I don't understand what you mean by "flag #"

I dont understand what you mean by "flag #" either

---

You can pass multiple print statements that will be printed in separate lines. Eg: `-O title -O id`

If your console allows you to use newline characters, you can do that as well. If not, you can put it in the config file. Config files are parsed in a POSIX compliant manner irrespective of your OS. Eg:
```sh
--print '%(title)s
%(id)s'
```
