### ISSUE TITLE
Embed yt-dlp and use postprocessor_args in ytdl_options

### ISSUE THREAD

**Issue by JVT038** [yt-dlp/yt-dlp#1843]
### Checklist

- [X] I'm asking a question and not reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

So I'm trying to use `postprocessor_args` in my python app, however I can't get it to work.
According to the docs: 
```
    postprocessor_args: A dictionary of postprocessor/executable keys (in lower case)
                       and a list of additional command-line arguments for the
                       postprocessor/executable. The dict can also have "PP+EXE" keys
                       which are used when the given exe is used by the given PP.
                       Use 'default' as the name for arguments to passed to all PP
                       For compatibility with youtube-dl, a single list of args
                       can also be used
```
So I tried this:
``` 
                postprocessor_args.append({
                    'default',
                    ["-c:v h264_nvenc"]
                })
```
This one gives me the error `TypeError: unhashable type: 'list'`, as list apparently can't be inserted into dictionaries.
So I tried this:
```
                postprocessor_args.append({
                    'default',
                    "-c:v h264_nvenc"
                })
```
which gives me another error: `ERROR: Postprocessing: error running ffmpeg`
In the CLI, this worked: `yt-dlp https://www.youtube.com/watch?v=u3VFzuUiTGw --no-playlist --format=best --recode-video=m4a --postprocessor-args "VideoConvertor: -c:v h264_nvenc" --verbose`
so I don't really understand why my attempts to embed it into my python app have failed.
Could someone explain to me the correct syntax of using this ytdlp option?
Thanks in advance

**Comment by pukkandan** [comment]
> This one gives me the error TypeError: unhashable type: 'list', as list apparently can't be inserted into dictionaries.

That is not how you create dicts in python. Those are sets, not dicts

The correct syntax is:
```
postprocessor_args = {'VideoConvertor': ['-c:v', 'h264_nvenc']}
```
