### ISSUE TITLE
TrovoChannelVodIE is broken because of worng inheritance

### ISSUE THREAD

**Issue by DerBunteBall** [yt-dlp/yt-dlp#1849]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2021.12.01**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Worldwide

### Description

Doing e.g. this:

```yt-dlp --ignore-config --downloader aria2c --ffmpeg-location ./.yt-dlp/ffmpeg/ffmpeg-n4.4.1-3-g88ffbf6e01-linux64-lgpl-4.4/bin/ --verbose trovovod:The_real_Rocco```

The first version worked. The inheritance is wrong. While _call_api is defined in TrovoBaseIE the TrovoChannelVodIE is a child of TrovoChannelBaseIE which itself is a child of InfoExtractor. So _call_api which is defined in TrovoBaseIE and not in InfoExtractor will not be present here. So line 241 and 262 are not possible in that way. The TrovoBaseIE and TrovoChannelBaseIE would be need to be combined. My git and Python skills are to bad to create a Pull REquest.

Best Regards

### Verbose log

```shell
[debug] Command-line config: ['--ignore-config', '--downloader', 'aria2c', '--ffmpeg-location', './.yt-dlp/ffmpeg/ffmpeg-n4.4.1-3-g88ffbf6e01-linux64-lgpl-4.4/bin/', '--verbose', 'trovovod:The_real_Rocco']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2021.12.01 [91f071af6] (zip)
[debug] Python version 3.8.10 (CPython 64bit) - Linux-5.4.0-89-generic-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg n4.4.1-3-g88ffbf6e01-20211111 (setts), ffprobe n4.4.1-3-g88ffbf6e01-20211111
[debug] Optional libraries: keyring, sqlite
[debug] Proxy map: {}
[debug] [TrovoChannelVod] Extracting URL: trovovod:The_real_Rocco
ERROR: 'TrovoChannelVodIE' object has no attribute '_call_api'
Traceback (most recent call last):
  File "/home/lukas/.local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1329, in wrapper
    return func(self, *args, **kwargs)
  File "/home/lukas/.local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1398, in __extract_info
    ie_result = ie.extract(url)
  File "/home/lukas/.local/bin/yt-dlp/yt_dlp/extractor/common.py", line 597, in extract
    ie_result = self._real_extract(url)
  File "/home/lukas/.local/bin/yt-dlp/yt_dlp/extractor/trovo.py", line 219, in _real_extract
    uid = str(self._call_api(id, query={
AttributeError: 'TrovoChannelVodIE' object has no attribute '_call_api'
```

**Comment by Ashish0804** [comment]
@nyuszika7h Can you take a look?
