### ISSUE TITLE
https://superriki.yt/

### ISSUE THREAD

**Issue by yashoswalyo** [yt-dlp/yt-dlp#1854]
### Checklist

- [X] I've verified that I'm running yt-dlp version **2021.12.01**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I'm reporting a new site support request
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Global

### Example URLs

- Single video: https://superriki.yt/comedy/161-ak-mantk-ntikam-love-logic-revenge/source-23-series-8.html
- Single video: https://superriki.yt/comedy/161-ak-mantk-ntikam-love-logic-revenge/source-23-series-6.html#iframePlayerPagination

### Description

This site provides turkish dramas with english subtitles

### Verbose log

```shell
[debug] Command-line config: ['-Uv', 'https://superriki.yt/comedy/161-ak-mantk-ntikam-love-logic-revenge/source-23-series-8.html']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2021.12.01 [91f071af6]
[debug] Python version 3.9.7 (CPython 64bit) - Linux-5.13.0-22-generic-x86_64-with-glibc2.34
[debug] exe versions: ffmpeg 4.4 (setts), ffprobe 4.4, rtmpdump 2.4
[debug] Optional libraries: Cryptodome, keyring, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2021.12.01, Current version: 2021.12.01
yt-dlp is up to date (2021.12.01)
[debug] [generic] Extracting URL: https://superriki.yt/comedy/161-ak-mantk-ntikam-love-logic-revenge/source-23-series-8.html
[generic] source-23-series-8: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] source-23-series-8: Downloading webpage
[generic] source-23-series-8: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://superriki.yt/comedy/161-ak-mantk-ntikam-love-logic-revenge/source-23-series-8.html
Traceback (most recent call last):
  File "/home/yashoswal/.local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1329, in wrapper
    return func(self, *args, **kwargs)
  File "/home/yashoswal/.local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1398, in __extract_info
    ie_result = ie.extract(url)
  File "/home/yashoswal/.local/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 597, in extract
    ie_result = self._real_extract(url)
  File "/home/yashoswal/.local/lib/python3.9/site-packages/yt_dlp/extractor/generic.py", line 3813, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://superriki.yt/comedy/161-ak-mantk-ntikam-love-logic-revenge/source-23-series-8.html
```

**Comment by pukkandan** [comment]
From first impressions, it looks like a piracy site?

**Comment by yashoswalyo** [comment]
But only this site provides drama with english subs

**Comment by pukkandan** [comment]
Do they have the rights to distribute those drama?

**Comment by yashoswalyo** [comment]
I dont think they have rights but its also available on yt without subs, so downloading from here wouldnt be piracy

**Comment by nyuszika7h** [comment]
It's piracy because they're rehosting the videos with burned in subtitles. If it was a YouTube embed with a custom player to show subtitles like Amara then it would be more legitimate (though rightsholders still love to call fansubs piracy even when it's not distributed with an illegal copy of the video, which I personally disagree with).

**Comment by yashoswalyo** [comment]
ok
