### ISSUE TITLE
[Enhancement] Concatenating videos in a playlist

### ISSUE THREAD

**Issue by Barmem** [yt-dlp/yt-dlp#1855]
### Checklist

- [X] I'm reporting a feature request
- [X] I've verified that I'm running yt-dlp version **2021.12.01**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

- An option to stitch all downloaded videos in one video
- An option to embed each video title as chapters

**Comment by pukkandan** [comment]
Related: https://github.com/ytdl-org/youtube-dl/pull/28153 https://github.com/yt-dlp/yt-dlp/issues/382
