### ISSUE TITLE
`--console-title` doesn't work properly

### ISSUE THREAD

**Issue by SarsNeunSieben** [yt-dlp/yt-dlp#1859]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2021.12.01**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

The `--console-title` flag tries to print illegal characters on MacOS. I've tried it with `--console-title --progress-template "download-title:%(info.id)s-%(progress.eta)s"` and it works flawlessly, but with all other prefixes, so 
- `--console-title --progress-template "download:%(info.id)s-%(progress.eta)s"`
- `--console-title --progress-template "postprocess:%(info.id)s-%(progress.eta)s"`
- `--console-title --progress-template "postprocess-title:%(info.id)s-%(progress.eta)s"`
 
it tries to print some illegal characters and raises the bell like on an error. It also doesn't matter from which side I try to download, even with the generic extractor it is the same behavior. 
So I guess it has something to do with the prefixes of the console title.

### Verbose log

```shell
yt-dlp -Uv --ignore-config --console-title "https://youtu.be/RDfjXj5EGqI"                       
[debug] Command-line config: ['-Uv', '--ignore-config', '--console-title', 'https://youtu.be/RDfjXj5EGqI']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2021.12.01 [91f071af6]
[debug] Python version 3.9.9 (CPython 64bit) - macOS-12.0.1-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.4.1 (setts), ffprobe 4.4.1, rtmpdump 2.4
[debug] Optional libraries: sqlite
[debug] Proxy map: {}
Latest version: 2021.12.01, Current version: 2021.12.01
yt-dlp is up to date (2021.12.01)
[debug] [youtube] Extracting URL: https://youtu.be/RDfjXj5EGqI
[youtube] RDfjXj5EGqI: Downloading webpage
[youtube] RDfjXj5EGqI: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] RDfjXj5EGqI: Downloading 1 format(s): 248+251
[debug] Invoking downloader on "https://r5---sn-h0jelnez.googlevideo.com/videoplayback?expire=1638398717&ei=naanYYWuN4j01wL4l5uYCg&ip=2003%3Aec%3Ac707%3Aab00%3Ad1c9%3A8edd%3Aa8de%3A7c9d&id=o-ANVgfUPSkl_2Rg7hhKZNORTf1pmsrawy_M2-hOSstF0t&itag=248&source=youtube&requiressl=yes&mh=aJ&mm=31%2C26&mn=sn-h0jelnez%2Csn-4g5edndl&ms=au%2Conr&mv=m&mvi=5&pl=34&initcwndbps=1431250&vprv=1&mime=video%2Fwebm&gir=yes&clen=9551527345&dur=28827.465&lmt=1637025436655671&mt=1638376865&fvip=5&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=5535434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRAIgWbITf9zK4OfCQ69DSv5Jur36Aq2qep6xhgMAqBXyYuECIH3M1Y1R1DmMARIWYoNa14gTrcl4ZKPNSUrrK4r_wBd1&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIge9nZJkGGTjNHHTyV7NGjFzYTFQDN8yd0Au7v6PO4hNMCIQCu38M0v9sjEWiRk4QnoFEc1dgj9KjTNDUQcsPeD5lAIw%3D%3D"
[download] Destination: ✰ 8 HOURS ✰ Best Fireplace HD 1080p video ✰ Relaxing fireplace sound ✰ Fireplace Burning ✰ Full HD [RDfjXj5EGqI].f248.webm
[download]   0.0% of 8.90GiB at  6.29MiB/s ETA 24:070;94m  0.0% of 8.90GiB at  6.29MiB/s ETA 24:07^C
ERROR: Interrupted by user
```

**Comment by pukkandan** [comment]
oops! When adding color to progress bar, I accidentally added it to console title as well. Will fix asap
