### ISSUE TITLE
filter youtube title other than english

### ISSUE THREAD

**Issue by wanghaisheng** [yt-dlp/yt-dlp#1861]
### Checklist

- [X] I'm asking a question and not reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

there are a bunch of indian or spanish youtube title video around there,I only want english ones
how can I achieve

**Comment by pukkandan** [comment]
Use `--match-filter`. But yt-dlp has no sense of what language the title is in. You will have to come up with an appropriate filter yourself
