### ISSUE TITLE
Using `ytsearch` feature is slow

### ISSUE THREAD

**Issue by dasl-** [yt-dlp/yt-dlp#1865]
### Checklist

- [X] I'm asking a question and not reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

I'm trying to use yt-dlp as a CLI youtube search tool that does not require a youtube API key. As shown in the below example, searching for 10 videos matching the query "foo" took 16.5 seconds:

```
% time yt-dlp "ytsearch10:foo" --print id 2>/dev/null
gykGUEiBSVY
eT_FJHM-Qhs
eBG7P-K-r1Y
jsDgrKdczAE
WXqrfQU8Ejk
F1WSkKqKKl0
3f5HDjjzwqo
SBjQ9tuuTJQ
aIo6n3ljtdY
4PkcfQtibmU
yt-dlp "ytsearch10:foo" --print id 2> /dev/null  5.94s user 0.41s system 38% cpu 16.523 total
```

Execution time appears to increase linearly with the number of videos being searched for (via changing `N` in the `ytsearchN` string).

Is there a faster way to retrieve video_ids for a given search query? I don't need detailed metadata per each search result, just the video_id would suffice.

yt-dlp version: 2021.12.01

**Comment by pukkandan** [comment]
Since you only want the ID, use --flat-playlist. If you want all metadata, there is no faster way

**Comment by dasl-** [comment]
awesome, thank you!
