### ISSUE TITLE
Suggestions - add system timestamp to debugging logs

### ISSUE THREAD

**Issue by section83** [yt-dlp/yt-dlp#1866]
### Checklist

- [X] I'm reporting a feature request
- [X] I've verified that I'm running yt-dlp version **2021.12.01**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

Is it possible to add timestamps to each line in the log output of YT-DLP ? Timestamps would come from the time on the system running YT-DLP.  They would help diagnose problems such as intermittent connections etc.

I can see one issue: having to get the current system time before writing each line could slow down YT-DLP processing. If that would be an issue, would it be possible to add timestamps to particular lines ? e.g. calls to FFmpeg and other utilities, starting and stopping downloads, warnings and errors.

Thanks.

**Comment by pukkandan** [comment]
But why? I dont think it makes sense to be added into yt-dlp itself. For CLI, this is easily achievable. 
https://github.com/section83/MacYTDL/issues/46 should be addressed by the code that consumes the log imo.

```sh
> ./yt-dlp test:youtube | ts
Dec 03 04:58:13 [TestURL] Test URL: https://www.youtube.com/watch?v=BaW_jenozKc&t=1s&end=9
Dec 03 04:58:13 [youtube] BaW_jenozKc: Downloading webpage
Dec 03 04:58:15 [youtube] BaW_jenozKc: Downloading android player API JSON
Dec 03 04:58:17 [info] BaW_jenozKc: Downloading 1 format(s): 248+251
Dec 03 04:58:17 [download] youtube-dl test video ''_ä↭𝕐 [BaW_jenozKc].webm has already been downloaded
```

OR

```sh
> ./yt-dlp test:youtube | while IFS= read -r line; do printf '%s %s\n' "$(date)" "$line"; done
Fri Dec  3 04:53:51 IST 2021 [TestURL] Test URL: https://www.youtube.com/watch?v=BaW_jenozKc&t=1s&end=9
Fri Dec  3 04:53:51 IST 2021 [youtube] BaW_jenozKc: Downloading webpage
Fri Dec  3 04:53:53 IST 2021 [youtube] BaW_jenozKc: Downloading android player API JSON
Fri Dec  3 04:54:03 IST 2021 [info] BaW_jenozKc: Downloading 1 format(s): 248+251
Fri Dec  3 04:54:06 IST 2021 [download] Destination: youtube-dl test video ''_ä↭𝕐 [BaW_jenozKc].f248.webm
[download] 100% of 965.31KiB in 00:03
Fri Dec  3 04:54:09 IST 2021 [download] Destination: youtube-dl test video ''_ä↭𝕐 [BaW_jenozKc].f251.webm
[download] 100% of 138.96KiB in 00:02
Fri Dec  3 04:54:10 IST 2021 [Merger] Merging formats into "youtube-dl test video ''_ä↭𝕐 [BaW_jenozKc].webm"
Fri Dec  3 04:54:12 IST 2021 Deleting original file youtube-dl test video ''_ä↭𝕐 [BaW_jenozKc].f248.webm (pass -k to keep)
Fri Dec  3 04:54:12 IST 2021 Deleting original file youtube-dl test video ''_ä↭𝕐 [BaW_jenozKc].f251.webm (pass -k to keep)
```

**Comment by section83** [comment]
My lack of CLI knowledge shows.

>section83/MacYTDL#46 should be addressed by the code that consumes the log imo.

Yes. "ts" is not available in Apple's implementation of zsh or sh.  So, I'll have to use "read" or something similar.

Thanks.
