### ISSUE TITLE
CBS DRM on random episodes even weeks later?

### ISSUE THREAD

**Issue by RedPenguin2** [yt-dlp/yt-dlp#1868]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2021.12.01**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

USA

### Description

I know that for a while CBS had a thing where episodes of The Late Show with Stephen Colbert, could be DRMed for about a week then work fine.

Yet I am noticing this episode from 11-17-21, still claims to have DRM even though episodes before and after it all download 1-2-3.

https://www.cbs.com/shows/the-late-show-with-stephen-colbert/video/h0WsEzT_t_kfbNns5qb_Ztmm5USV3ecr/the-late-show-11-17-21-adam-driver-america-ferrera-/

### Verbose log

```shell
yt-dlp -Uv "https://www.cbs.com/shows/the-late-show-with-stephen-colbert/video/h0WsEzT_t_kfbNns5qb_Ztmm5USV3ecr/the-late-show-11-17-21-adam-driver-america-ferrera-/"
[debug] Command-line config: ['-Uv', 'https://www.cbs.com/shows/the-late-show-with-stephen-colbert/video/h0WsEzT_t_kfbNns5qb_Ztmm5USV3ecr/the-late-show-11-17-21-adam-driver-america-ferrera-/']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2021.12.01 [91f071a] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19042-SP0
[debug] exe versions: ffmpeg N-101416-g3065532a0e-ffmpeg-windows-build-helpers (setts), ffprobe N-101416-g3065532a0e-ffmpeg-windows-build-helpers, phantomjs 2.1.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2021.12.01, Current version: 2021.12.01
yt-dlp is up to date (2021.12.01)
[debug] [CBS] Extracting URL: https://www.cbs.com/shows/the-late-show-with-stephen-colbert/video/h0WsEzT_t_kfbNns5qb_Ztmm5USV3ecr/the-late-show-11-17-21-adam-driver-america-ferrera-/
[CBS] h0WsEzT_t_kfbNns5qb_Ztmm5USV3ecr: Downloading XML
ERROR: [CBS] h0WsEzT_t_kfbNns5qb_Ztmm5USV3ecr: h0WsEzT_t_kfbNns5qb_Ztmm5USV3ecr: This video is DRM protected
Traceback (most recent call last):
  File "yt_dlp\extractor\common.py", line 597, in extract
  File "yt_dlp\extractor\cbs.py", line 72, in _real_extract
  File "yt_dlp\extractor\cbs.py", line 158, in _extract_video_info
  File "yt_dlp\extractor\common.py", line 1061, in report_drm
  File "yt_dlp\extractor\common.py", line 1105, in raise_no_formats
yt_dlp.utils.ExtractorError: h0WsEzT_t_kfbNns5qb_Ztmm5USV3ecr: This video is DRM protected
Traceback (most recent call last):
  File "yt_dlp\extractor\common.py", line 597, in extract
  File "yt_dlp\extractor\cbs.py", line 72, in _real_extract
  File "yt_dlp\extractor\cbs.py", line 158, in _extract_video_info
  File "yt_dlp\extractor\common.py", line 1061, in report_drm
  File "yt_dlp\extractor\common.py", line 1105, in raise_no_formats
yt_dlp.utils.ExtractorError: h0WsEzT_t_kfbNns5qb_Ztmm5USV3ecr: This video is DRM protected

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1329, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1398, in __extract_info
  File "yt_dlp\extractor\common.py", line 623, in extract
yt_dlp.utils.ExtractorError: [CBS] h0WsEzT_t_kfbNns5qb_Ztmm5USV3ecr: h0WsEzT_t_kfbNns5qb_Ztmm5USV3ecr: This video is DRM protected
```

**Comment by TheGrimKeeper** [comment]
Not necessarily the case here (since I haven't looked at this one specifically), but I have seen before where CBS "forgets" to remove the DRM from a random episode.  So this isn't a new or unprecedented problem.

**Comment by pukkandan** [comment]
It is unlikely for a non-DRM video to show DRM error. But I cant confirm 100% without account

**Comment by RedPenguin2** [comment]
> Not necessarily the case here (since I haven't looked at this one specifically), but I have seen before where CBS "forgets" to remove the DRM from a random episode. So this isn't a new or unprecedented problem.

I think that probably is the case, because every other episode is working.

I just thought after about 7 days, you can download any episode, but it seems have PlayReady DRM, right before they moved it to Paramount+-only access, I was able to watch it. I don't know why Playready as most websites seem to use Widevine.

**Comment by pukkandan** [comment]
If you want me to check for sure what is happening, you can send account details to me (discord/reddit/email). But as I mentioned above, this is unlikely to be an error.
