### ISSUE TITLE
Downloaded videos are not supported on WhatsApp

### ISSUE THREAD

**Issue by leo9595** [yt-dlp/yt-dlp#1873]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2021.12.01**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

I have successfully downloaded a youtube video using the following command:

`yt-dlp -ciw  --output '/root/yt/%(title)s.%(ext)s' --format 'bestvideo+bestaudio[ext=m4a]/bestvideo+bestaudio/best' --merge-output-format mp4 https://youtube.com/xxxxxxxxxxxxxx`

The video downloads successfully, but doesn't play in all apps, **it's not even possible to share the video on WhatsApp**. It returns "File is not supported", even though it is in MP4. Even in App Google Photos, videos are not played and in App Files of Google, it is able to be played.

I believe this is because ffmpeg is not being used to convert correctly, since the **--prefer-ffmpeg** command is no longer supported. How to fix this?

### Verbose log

```shell
No yt-dlp returns no error. The file just doesn't play in all video player apps. I did the test with youtube-dl, it was reproduced successfully.

The command used was:

yt-dlp -ciw  --output '/root/yt/%(title)s.%(ext)s' --format 'bestvideo+bestaudio[ext=m4a]/bestvideo+bestaudio/best' --merge-output-format mp4 https://youtube.com/xxxxxxxxxxxxxx

On youtube-dl I used it the same way:

youtube-dl -ciw  --output '/root/yt/%(title)s.%(ext)s' --format 'bestvideo+bestaudio[ext=m4a]/bestvideo+bestaudio/best' --merge-output-format mp4 https://youtube.com/xxxxxxxxxxxxxx
```

**Comment by october262** [comment]
> 



> ### Checklist
> * [x]  I'm reporting a bug unrelated to a specific site
> * [x]  I've verified that I'm running yt-dlp version **2021.12.01**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
> * [x]  I've checked that all provided URLs are alive and playable in a browser
> * [x]  I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
> * [x]  I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
> * [x]  I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
> 
> ### Description
> I have successfully downloaded a youtube video using the following command:
> 
> `yt-dlp -ciw --output '/root/yt/%(title)s.%(ext)s' --format 'bestvideo+bestaudio[ext=m4a]/bestvideo+bestaudio/best' --merge-output-format mp4 https://youtube.com/xxxxxxxxxxxxxx`
> 
> The video downloads successfully, but doesn't play in all apps, **it's not even possible to share the video on WhatsApp**. It returns "File is not supported", even though it is in MP4. Even in App Google Photos, videos are not played and in App Files of Google, it is able to be played.
> 
> I believe this is because ffmpeg is not being used to convert correctly, since the **--prefer-ffmpeg** command is no longer supported. How to fix this?
> 
> ### Verbose log
> ```shell
> No yt-dlp returns no error. The file just doesn't play in all video player apps. I did the test with youtube-dl, it was reproduced successfully.
> 
> The command used was:
> 
> yt-dlp -ciw  --output '/root/yt/%(title)s.%(ext)s' --format 'bestvideo+bestaudio[ext=m4a]/bestvideo+bestaudio/best' --merge-output-format mp4 https://youtube.com/xxxxxxxxxxxxxx
> 
> On youtube-dl I used it the same way:
> 
> youtube-dl -ciw  --output '/root/yt/%(title)s.%(ext)s' --format 'bestvideo+bestaudio[ext=m4a]/bestvideo+bestaudio/best' --merge-output-format mp4 https://youtube.com/xxxxxxxxxxxxxx
> ```

how long is the youtube video ?? make sure that the video does not exceed the limit of one and a half minutes

**Comment by Ashish0804** [comment]
`-f best` ig

**Comment by leo9595** [comment]
> `-f best` ig

works, but the video comes in the lowest quality.

**Comment by leo9595** [comment]
> > 
> 
> > ### Checklist
> > 
> > * [x]   I'm reporting a bug unrelated to a specific site
> > * [x]   I've verified that I'm running yt-dlp version **2021.12.01**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
> > * [x]   I've checked that all provided URLs are alive and playable in a browser
> > * [x]   I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
> > * [x]   I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
> > * [x]   I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
> > 
> > ### Description
> > I have successfully downloaded a youtube video using the following command:
> > `yt-dlp -ciw --output '/root/yt/%(title)s.%(ext)s' --format 'bestvideo+bestaudio[ext=m4a]/bestvideo+bestaudio/best' --merge-output-format mp4 https://youtube.com/xxxxxxxxxxxxxx`
> > The video downloads successfully, but doesn't play in all apps, **it's not even possible to share the video on WhatsApp**. It returns "File is not supported", even though it is in MP4. Even in App Google Photos, videos are not played and in App Files of Google, it is able to be played.
> > I believe this is because ffmpeg is not being used to convert correctly, since the **--prefer-ffmpeg** command is no longer supported. How to fix this?
> > ### Verbose log
> > ```shell
> > No yt-dlp returns no error. The file just doesn't play in all video player apps. I did the test with youtube-dl, it was reproduced successfully.
> > 
> > The command used was:
> > 
> > yt-dlp -ciw  --output '/root/yt/%(title)s.%(ext)s' --format 'bestvideo+bestaudio[ext=m4a]/bestvideo+bestaudio/best' --merge-output-format mp4 https://youtube.com/xxxxxxxxxxxxxx
> > 
> > On youtube-dl I used it the same way:
> > 
> > youtube-dl -ciw  --output '/root/yt/%(title)s.%(ext)s' --format 'bestvideo+bestaudio[ext=m4a]/bestvideo+bestaudio/best' --merge-output-format mp4 https://youtube.com/xxxxxxxxxxxxxx
> > ```
> 
> how long is the youtube video ?? make sure that the video does not exceed the limit of one and a half minutes

The video is less than 50 seconds. I changed the format code to this one below. "It worked", but in larger videos, the audio is ahead. Do you know what to do?

`-f 'bv*[ext=mp4]+ba[ext=m4a]' --merge-output-format mp4 --embed-metadata`

**Comment by october262** [comment]
> > > 
> > 
> > 
> > > ### Checklist
> > > 
> > > * [x]    I'm reporting a bug unrelated to a specific site
> > > * [x]    I've verified that I'm running yt-dlp version **2021.12.01**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
> > > * [x]    I've checked that all provided URLs are alive and playable in a browser
> > > * [x]    I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
> > > * [x]    I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
> > > * [x]    I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
> > > 
> > > ### Description
> > > I have successfully downloaded a youtube video using the following command:
> > > `yt-dlp -ciw --output '/root/yt/%(title)s.%(ext)s' --format 'bestvideo+bestaudio[ext=m4a]/bestvideo+bestaudio/best' --merge-output-format mp4 https://youtube.com/xxxxxxxxxxxxxx`
> > > The video downloads successfully, but doesn't play in all apps, **it's not even possible to share the video on WhatsApp**. It returns "File is not supported", even though it is in MP4. Even in App Google Photos, videos are not played and in App Files of Google, it is able to be played.
> > > I believe this is because ffmpeg is not being used to convert correctly, since the **--prefer-ffmpeg** command is no longer supported. How to fix this?
> > > ### Verbose log
> > > ```shell
> > > No yt-dlp returns no error. The file just doesn't play in all video player apps. I did the test with youtube-dl, it was reproduced successfully.
> > > 
> > > The command used was:
> > > 
> > > yt-dlp -ciw  --output '/root/yt/%(title)s.%(ext)s' --format 'bestvideo+bestaudio[ext=m4a]/bestvideo+bestaudio/best' --merge-output-format mp4 https://youtube.com/xxxxxxxxxxxxxx
> > > 
> > > On youtube-dl I used it the same way:
> > > 
> > > youtube-dl -ciw  --output '/root/yt/%(title)s.%(ext)s' --format 'bestvideo+bestaudio[ext=m4a]/bestvideo+bestaudio/best' --merge-output-format mp4 https://youtube.com/xxxxxxxxxxxxxx
> > > ```
> > 
> > 
> > how long is the youtube video ?? make sure that the video does not exceed the limit of one and a half minutes
> 
> The video is less than 50 seconds. I changed the format code to this one below. "It worked", but in larger videos, the audio is ahead. Do you know what to do?
> 
> `-f 'bv*[ext=mp4]+ba[ext=m4a]' --merge-output-format mp4 --embed-metadata`

try again with ffmpeg and use --prefer-ffmpeg in your yt-dlp command.

**Comment by leo9595** [comment]
> --prefer-ffmpeg

It has no effect

**Comment by october262** [comment]
> > --prefer-ffmpeg
> 
> It has no effect

do you have ffmpeg installed ??

**Comment by leo9595** [comment]
> > > --prefer-ffmpeg
> > 
> > 
> > It has no effect
> 
> do you have ffmpeg installed ??

Yes!

```
ffmpeg version 4.2.4-1ubuntu0.1 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.3.0-10ubuntu2)
  configuration: --prefix=/usr --extra-version=1ubuntu0.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-nvenc --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
```

**Comment by Ashish0804** [comment]
> works, but the video comes in the lowest quality.

NO
yt has upto 720p in best...that's better than what u got with ytdl (480p)

**Comment by Ashish0804** [comment]
This not a ytdlp issue anyways
It's an external issue (ur video player)

Use -F to see that available formats and their codec and then use -f to select them
If u want a diff container then use --remux-video 

> the --prefer-ffmpeg command is no longer supported

That's bcoz it's enabled by default

**Comment by weskerty** [comment]
WhatsApp Requires H264 and ACC
If you have another codec, playback will fail. If it's AV1 and ACC, only the audio will be heard and the video will be black (at least on devices that don't support AV1).
Your solution is to use custom flags that prioritize H264 and ACC.
Like this: `-f "bestvideo[vcodec*=h264]+bestaudio[acodec*=aac]/bestvideo[vcodec*=h264]+bestaudio[acodec*=mp4a]/bestvideo[vcodec*=h264]+bestaudio/bestvideo+bestaudio/best"`

Read more settings in the documentation ytdlp
