### ISSUE TITLE
Integrating yt-dlp with a media library (player / downloader)

### ISSUE THREAD

**Issue by SuRGeoNix** [yt-dlp/yt-dlp#1874]
### Checklist

- [X] I'm asking a question and not reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

Hi Guys and thanks for your work!

I'm developing a media library [Flyleaf](https://github.com/SuRGeoNix/Flyleaf). I have already integrated yt-dlp with a [plugin](https://github.com/SuRGeoNix/Flyleaf/blob/master/FlyleafLib.Plugins.YoutubeDL/YoutubeDL.cs).

Currently, I'm using --write-info-json and -o options to export .json file and read all the available formats which then I expose to the users. My questions are the following:

1) Is this the ideal -performance wise- way to extract url formats? (eg. I have notice -j/-J might be better?). Minimal bandwidth/requests required (any options to disable default requests that in my case are not required?)

2) --write-info-json option doesn't respect playlists? I have noticed however if I give a -o filename with an extension it will create two files and one of them will contain the 1st video in playlist json output

3) Json url vs manifest_url attributes.  I'm currently using URLs (url attribute from json) from each format and open two different ffmpeg demuxers if required (eg different url for audio and different for video) which makes the audio/video sync more unstable and sometimes urls are not working properly.  I would prefer to have a master m3u8 with all the available audio/video/subtitle streams  parsed to ffmpeg directly. Is this possible or it's based on the extractor?

**Comment by pukkandan** [comment]
> Is this the ideal -performance wise- way to extract url formats? (eg. I have notice -j/-J might be better?). Minimal bandwidth/requests required (any options to disable default requests that my case don't required?)

`--write-info-json` writes the data to disk, `-j` writes to stdout. That is the only difference performance wise (assuming you are using `-s`)

> --write-info-json option doesn't respect playlists? I have noticed however if I give a -o filename with an extension it will create two files and one of them will contain the 1st video in playlist json output

It does. Show your verbose logs. You are probably passing some wrong options

> Json url vs manifest_url attributes. I'm currently using URLs (url attribute from json) from each format and open two different ffmpeg demuxers if required (eg different url for audio and different for video) which makes the audio/video sync more unstable and sometimes urls are not working properly. I would prefer to have a master m3u8 with all the available audio/video/subtitle streams parsed to ffmpeg directly. Is this possible or it's based on the extractor?

It depends on the extractor. You can take a look at the downloader code (yt_dlp/downloader/external.py/FfmpegFD) to see how we process the URLs. Instead of passing to ffmpeg, I suggest passing it back to yt-dlp with `--load-info-json path/to/file.info.json -f yourformat`. You can force ffmpeg using `--downloader ffmpeg` or stream to stdout if needed using `-o -`

**Comment by SuRGeoNix** [comment]
Thanks for you quick response @pukkandan

Can you tell me what is wrong with the following command and it overwrites the json file when using a playlist?

```
yt-dlp.exe --no-check-certificate --skip-download --youtube-skip-dash-manifest --write-info-json -o c:\root\t01 "https://www.youtube.com/watch?v=XzLGcLw3cHc&list=RDQM_xhIudLKsjM&start_radio=1"

[youtube:tab] Downloading playlist RDQM_xhIudLKsjM; add --no-playlist to just download video XzLGcLw3cHc
[youtube:tab] RDQM_xhIudLKsjM: Downloading webpage
[download] Downloading playlist: Mix - Deep house
[youtube:tab] RDQM_xhIudLKsjM page 1: Downloading API JSON
[youtube:tab] RDQM_xhIudLKsjM page 2: Downloading API JSON
[youtube:tab] RDQM_xhIudLKsjM page 3: Downloading API JSON
[youtube:tab] First video XzLGcLw3cHc found again; Assuming end of Mix
[info] Writing playlist metadata as JSON to: c:\root\t01.info.json
[youtube:tab] playlist Mix - Deep house: Downloading 79 videos
[download] Downloading video 1 of 79
[youtube] XzLGcLw3cHc: Downloading webpage
[youtube] XzLGcLw3cHc: Downloading android player API JSON
[info] XzLGcLw3cHc: Downloading 1 format(s): 22
[info] Writing video metadata as JSON to: c:\root\t01.info.json
[download] Downloading video 2 of 79
[youtube] pUjE9H8QlA4: Downloading webpage
[youtube] pUjE9H8QlA4: Downloading android player API JSON
[info] pUjE9H8QlA4: Downloading 1 format(s): 22
[info] Writing video metadata as JSON to: c:\root\t01.info.json
[download] Downloading video 3 of 79
```

I will check the code you suggest for the downloader even if I cannot use yt-dlp generally as I'm using ffmpeg api to have full control.

**Comment by pukkandan** [comment]
> `-o c:\root\t01`

You are asking all infojsons to be written to the same path. use `-P C:\root\to1` instead to just set the folder
