### ISSUE TITLE
How to early return when retry to download

### ISSUE THREAD

**Issue by drgpu** [yt-dlp/yt-dlp#1875]
### Checklist

- [X] I'm asking a question and not reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

I'm using a bad proxy pool and it often fails at sometime. When I use yt-dlp in my python code to extract information of a youtube video, it retries different methods to analyze the link even I limit the `extractor_retries` to 1. Could you tell me how to return the method when it tries the first method and got a timeout or 403 error?

**Comment by pukkandan** [comment]
I am assuming u r asking about youtube. You can use extractor-args https://github.com/yt-dlp/yt-dlp#youtube to limit which of the fallbacks are attempted. But other than that, there is no way to do it.

yt-dlp is not a proxy tester after all. I suggest you test the proxy with a random request and then run yt-dlp

**Comment by drgpu** [comment]
@pukkandan Could you tell me how to use this option?

I tried `options['extractor_args'] = "youtube:player-client=web" ` or `option[extractor_args'] = {"youtube": "player-client=web"}`, but it doesn't work. The program still tries android client. I use it in my python program rather than yt-dlp command line. Thank you very much.

**Comment by pukkandan** [comment]
```
option["extractor_args"] = {"youtube": {"player-client": ["web"]}}
```
