### ISSUE TITLE
Is the date value for the output based on the IP and if so is it possible to base it on the system date instead? 

### ISSUE THREAD

**Issue by smthjhn** [yt-dlp/yt-dlp#1881]
### Checklist

- [X] I'm asking a question and not reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

My system timezone is set to UTC and when I checked a newly uploaded video on youtube it matches the date on my system but when I downloaded it with `yt-dlp` the date is different. Is it possible to make the date value match my system date?

**Comment by pukkandan** [comment]
The timestamp returned should always be UTC irrespective of IP or system timezone

**Comment by smthjhn** [comment]
That's weird. Is it possible that the upload_date of a video might be different if the video is a scheduled upload? I have screenshot proof that the video I am talking about was uploaded on 20211128 it even says so on YouTube. But when I downloaded it again it still says that the upload_date is 20211127.

**Comment by smthjhn** [comment]
I also want to ask if it is normal that a normal video upload doesn't have an epoch timestamp string in the info.json? Because a livestream has a timestamp string in its info.json despite it being equivalent to "NA" on the output template.

**Comment by pukkandan** [comment]
> That's weird. Is it possible that the upload_date of a video might be different if the video is a scheduled upload? I have screenshot proof that the video I am talking about was uploaded on 20211128 it even says so on YouTube. But when I downloaded it again it still says that the upload_date is 20211127.

Give link

> I also want to ask if it is normal that a normal video upload doesn't have an epoch timestamp string in the info.json? Because a livestream has a timestamp string in its info.json despite it being equivalent to "NA" on the output template.

Yes. The exact timestamp is only known for livestreams (and only before they end, I believe)

**Comment by smthjhn** [comment]
Here's the link `https://www.youtube.com/watch?v=rcOAHTlBUKM`

**Comment by smthjhn** [comment]
I tried using the youtube api and grabbed the metadata of the link I posted. According to the response the "publishedAt" value is "2021-11-28T04:00:12Z". That's the only timestamp available there.

**Comment by coletdjnz** [comment]
We could enforce timezone to UTC for YouTube by default for consistency and certainty. Pretty much the same as how we currently enforce English.

 But, I'm also not certain on what YouTube defaults to. @pukkandan mentioned theirs defaulted to a US timezone.

**Comment by pukkandan** [comment]
if we can set it, UTC is best imo. The docs imply it should be UTC
```
    timestamp:      UNIX timestamp of the moment the video was uploaded
    upload_date:    Video upload date (YYYYMMDD).
                    If not explicitly set, calculated from timestamp.
```

**Comment by coletdjnz** [comment]
So, I think I found what the actual issue you were seeing is. But it goes deeper,  the timezones of dates and times extracted and processed throughout the YouTube extractor are/can be all over the place :sweat_smile: 

For webpage and the API, any sort of date text is returned in the client's timezone (UTC by default). ***However*, the upload and published dates in the `playerResponse` are fixed to a timezone (`UTC-??`, prob PT) regardless of client preference. This is the date we (and youtube-dl) use for the video upload date, hence the discrepancy you noticed.**

Ideally, as described by pukkandan, everything should be in UTC. So we could do the following to try achieve this:
- enforce UTC for API/webpage calls - though this is YouTube's default, it is needed to override any tz pref from cookies
- prefer `dateText` for video upload date (which is localized to client timezone) over the playerResponse upload date - will need to wait till #2069 . This will also add upload date extraction for non-web clients.
- fix (or add an option to set tz) `datetime_from_str` using computer's timezone for relative time calculations (yes, this has made me notice that we are calculating the relative time based on your computers timezone, from relative time text based in UTC, and then converting the result into a UNIX timestamp that is supposed to be in UTC :laughing:). This affects the estimated dates processed from relative time text for comments, video upload dates extracted from feeds, and playlist modified times (being added in #2069).
