### ISSUE TITLE
[youtube] Don't download all API json pages when using the arguments "--dateafter --break-on-reject"

### ISSUE THREAD

**Issue by jonno85uk** [yt-dlp/yt-dlp#1883]
### Checklist

- [X] I'm reporting a site feature request
- [X] I've verified that I'm running yt-dlp version **2021.12.01**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Example URLs

https://www.youtube.com/c/BritishMovietone/
https://www.youtube.com/user/PewDiePie

### Description

For certain youtube channels it is possible that all of the API json pages are downloaded even if not required.

As an example:

`yt-dlp --dateafter now-1day --break-on-reject https://www.youtube.com/c/BritishMovietone/`

This command downloads thousands of pages before exiting despite no videos matching the --dateafter argument (as of writing).

The desired behaviour would be that the program exited on realisation that the first page resulted in no matching videos.
This is on the assumption that the pages are in chronological order but with debugging the youtube downloader, the assumption appears to be valid.

**Comment by jonno85uk** [comment]
After reading the comments on #1018 let me explain a use-case:

- A users list of youtube subscriptions exists in a csv file (retrieved via takeout.google.com).
- The csv file is parsed and all videos in each channel that is less than a day old are downloaded.
- These videos then get served via a personal media-server.

**Comment by coletdjnz** [comment]
Fixed again by https://github.com/yt-dlp/yt-dlp/commit/a30a6ed3e49a0e037af6d5e26ecef3f3eba67d33

Need to use the extractor arg `youtubetab:approximate_date`

e.g. `yt-dlp --dateafter now-2week --break-on-reject https://www.youtube.com/c/BritishMovietone/ --extractor-args youtubetab:approximate_date`
