### ISSUE TITLE
Sign release binaries with GPG

### ISSUE THREAD

**Issue by 7thFox** [yt-dlp/yt-dlp#1886]
### Checklist

- [X] I'm reporting a feature request
- [X] I've verified that I'm running yt-dlp version **2021.12.01**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

I'm looking to pull the latest binary release as part of a Docker deployment. It would be great if I could verify my download isn't someone else spoofing the file by comparing a GPG signature.

**Comment by pukkandan** [comment]
We should be able to use this https://github.com/marketplace/actions/import-gpg. If someone can make a PR, that would be appreciated

**Comment by fstirlitz** [comment]
Is it trustworthy? There is a danger that an external action may exfiltrate the keys. Honestly, I would rather set up signing manually just to be safe.

**Comment by fstirlitz** [comment]
I started some exploratory work on this.  The actual signing is not too hard to do, but there are a couple of obstacles.  The biggest one is that the Windows binaries are built on Windows, which I am not sure even has a GPG binary installed, and even if it did, it would still necessitate writing build steps separately from the other systems.  Though on the other hand, by the same token the users will not necessarily have a way to verify the signature either.

A smaller obstacle is that I am kind of confused where I should place the signing step.  The build steps sometimes overwrite the artifacts to later upload them under different names, which means I cannot add just one ‘sign and upload’ step at the end.  (Not to mention, there are many ‘ends’ where it would need to be added.)

A bigger problem is how to figure out key rotation and distribution. Also, incorporating signature verification into the updater will necessitate adding a dependency; at the very least on the `gpg` binary itself, though it would be better to use the GPGME bindings.

**Comment by pukkandan** [comment]
youtube-dl had a `rsa_verify` function in the updater. Will need to look into the details of how it worked

The [GHA windows VM](https://github.com/actions/virtual-environments/blob/main/images/win/Windows2022-Readme.md) does not have gpg installed and installing it ourself may be difficult depending on what limitations the VM has set up for security. The action I mentioned above is using [openpgpjs](https://openpgpjs.org)

In my opinion, there is no need for us to re-invent the wheel here. We can fork/freeze the dependencies to address any concerns of trust.

**Comment by SkyKwas** [comment]
Hi, I was also wondering if a public signing key could be provided. I'm currently running Linux Mint 21 and used the APT package manager to install yt-dlp. I then went to add the stable PPA so that I could get the latest version, but no signing key was provided on launchpad.

If creating and implementing the signing key(s) for the binaries, package managers, etc. is too much work, is it possible to make the key(s) for just package managers?

If I'm missing something please let me know! Thanks.

**Comment by bashonly** [comment]
Closed by 12647e03d417feaa9ea6a458bea5ebd747494a53
