### ISSUE TITLE
String length limit

### ISSUE THREAD

**Issue by Fabian42** [yt-dlp/yt-dlp#1888]
### Checklist

- [X] I'm reporting a feature request
- [X] I've verified that I'm running yt-dlp version **2021.12.01**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

I would like to be able to limit the length of a string parameter in the file name template.

Proposed syntax example: `-o "%(uploader)s_-_%(title)20s_%(id)s.%(ext)s"`

What currently happens if I use `--trim-filenames` is that the ID gets cut off completely if the title is too long. In the worst case, if I'm downloading a playlist of videos with titles like "Super long series title, episode 42: XYZ", I would get completely identical filenames and all downloads after the first one would get skipped.

Looking at the `%(playlist_index)04d` syntax, I realise that my suggestion is inconsistent in defining an upper bound instead of a lower bound, but from my own perspective, I would consider this usecase more common than padding (and then the question would be whether it would happen with spaces, underscores, zeroes or something else). But maybe I'm wrong in that. If both are wanted, some other syntax would have to be used.

I personally am in the process of writing a complicated wrapper script around `yt-dlp` anyway, so I would probably just work around this unwanted trimming behaviour by removing `_%(id)s` from my file name template and inserting the ID back into the filename afterwards via script (together with stripping out all `%`, `+`, `=`, `@`, `~` and extra `.`).

**Comment by chio0hai** [comment]
I believe this feature is already supported.

Python slicing can be used according to: https://github.com/yt-dlp/yt-dlp#output-template

For your example, the output template syntax would be: `-o "%(uploader)s_-_%(title.0:20)s_%(id)s.%(ext)s"`

**Comment by nao20010128nao** [comment]
Simpler solution: `%(title).20s`

**Comment by pukkandan** [comment]
From docs:
> The special sequences may be formatted according to [Python string formatting operations](https://docs.python.org/3/library/stdtypes.html#printf-style-string-formatting)

Go through the given link

**Comment by Fabian42** [comment]
Ah, I did not expect that to also work on strings. Thanks!
