### ISSUE TITLE
Is there still a way to view "regions allowed" ?

### ISSUE THREAD

**Issue by BlohoJo** [yt-dlp/yt-dlp#1889]
### Checklist

- [X] I'm asking a question and not reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

You used to be able to view the html page source on a YouTube video and see the "regionsallowed" countries. Currently, the HTML source still shows "regionsallowed" but it's now blank.

Here's a video for testing that I know is region locked to the UK:

[https://www.youtube.com/watch?v=Fh7UgrHMjbQ](https://www.youtube.com/watch?v=Fh7UgrHMjbQ)

If you view the page source and searched for "regionsallowed" it now shows as:

`<meta itemprop="regionsAllowed" content="">`

Is there any way to now know what regions videos are geo-locked to? Or has that been lost for good?

**Comment by pukkandan** [comment]
Youtube now shows the regionsAllowed only when you are in an allowed region already
