### ISSUE TITLE
[Question] How to use retry unavailable fragments for aria2c?

### ISSUE THREAD

**Issue by erickyun** [yt-dlp/yt-dlp#189]
I did see that `[aria2c] Support retry/abort unavailable fragments` is added.

So my question is how do I use retry unavailable fragments for aria2c?

Would something like this work:
```
yt-dlp 'URL' --fragment-retries infinite --external-downloader aria2c
```
Or do I need to add a command to
**--external-downloader-args aria2c:** ?

**Comment by pukkandan** [comment]
> yt-dlp 'URL' --fragment-retries infinite --external-downloader aria2c

This works although I don't recommend using `infinite` retries

**Comment by erickyun** [comment]
> > yt-dlp 'URL' --fragment-retries infinite --external-downloader aria2c
> 
> This works although I don't recommend using `infinite` retries

Thank you
And
Could you explain why?
Would not better if all segments would be downloaded?

**Comment by pukkandan** [comment]
Yes, but some videos may have actually missing fragments. With infinite retries, the download will never finish in that case.

**Comment by erickyun** [comment]
> Yes, but some videos may have actually missing fragments. With infinite retries, the download will never finish in that case.

I understand 🤔 thanks again 🙂

**Comment by erickyun** [comment]
> Yes, but some videos may have actually missing fragments. With infinite retries, the download will never finish in that case.

Does aria2c retry downloading fragments at the end of the download or when a error occurs?

**Comment by pukkandan** [comment]
@erickyun aria2c doesnt itself have the option to retry the fragments afaik. So yt-dlp checks if aria returns an error, and then retries the download. So yes, the retry will only happen at the end of download

**Comment by erickyun** [comment]
@pukkandan ok I understand so yt-dlp makes aria2c download again all segments only a error occured thank you again. 🙂

**Comment by pukkandan** [comment]
> download again all segments

The already downloaded segments are automatically skipped

**Comment by erickyun** [comment]
> > download again all segments
> 
> The already downloaded segments are automatically skipped

@pukkandan sorry my bad English I did mean only every segment with a error

**Comment by pukkandan** [comment]
just clarifying in case you misunderstood :D

**Comment by erickyun** [comment]
> just clarifying in case you misunderstood :D

🙂👍thanks
