### ISSUE TITLE
Chapters for Vimeo

### ISSUE THREAD

**Issue by t0ben** [yt-dlp/yt-dlp#1892]
### Checklist

- [X] I'm reporting a site feature request
- [X] I've verified that I'm running yt-dlp version **2021.12.01**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

World

### Example URLs

yt-dlp -f "bestvideo[height<=480]+bestaudio/best[height<=480]" --add-metadata --merge-output-format mkv --referer https://traumasuperconference.com --all-subs --embed-subs --embed-chapters --embed-thumbnail  https://player.vimeo.com/video/641685338

### Description

Is there any way to get the chapters from Vimeo ?  
Ripping with the sample in URL (above) doesnot generate a file with Chapters (tested in VLC)

![Vimeo_Chapter_Sample](https://user-images.githubusercontent.com/139028/144748319-de1bd7c8-5555-43e1-be83-bc377efa272b.png)

**Comment by pukkandan** [comment]
Since I cannot view the video in browser, can u confirm that the first chapter starts 9seconds in? How is the time before that marked? Also, does the last chapter go till the end of the video? or is there a black section like in the start?

**Comment by t0ben** [comment]
Embed Page : https://traumasuperconference.com/session/levels-compassion-gabor-mate/

**Comment by pukkandan** [comment]
Yeah, it doesnt work rn, I'm adding it.

> Embed Page : traumasuperconference.com/session/levels-compassion-gabor-mate 

You should've started with that :D. Makes it easier for me to see what exactly the embed player is doing

Video files need chapters to go from the start to end of the video. So I'll have to insert a chapter `<Untitled>` at the start from 0-9s

**Comment by t0ben** [comment]
First Chapter starts at 9s - before that nothing is marked, last chapter goes until end. No Black sections I can see.

**Comment by t0ben** [comment]
Thank you !
