### ISSUE TITLE
8K video support for `bilibili.com`

### ISSUE THREAD

**Issue by c2xusnpq6** [yt-dlp/yt-dlp#1898]
### Checklist

- [X] I'm reporting a site feature request
- [X] I've verified that I'm running yt-dlp version **2021.12.01**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Example URLs

https://www.bilibili.com/video/BV1KS4y197BN
https://www.bilibili.com/video/BV1Zr4y1Q75j

### Description

refer to: 
- https://github.com/yt-dlp/yt-dlp/issues/1878
- https://github.com/ytdl-org/youtube-dl/issues/30315

**Comment by pukkandan** [comment]
It appears anything above 1080p needs an account. Pass cookie and show verbose log of the format list  (-F)

**Comment by c2xusnpq6** [comment]
> It appears anything above 1080p needs an account. Pass cookie and show verbose log of the format list (-F)

No. You don't.

Pick up a 360p or 480p and you'll have this. There are all the details inside the request.

![image](https://user-images.githubusercontent.com/75058881/144863366-64724eef-110e-45e0-9f14-8929243ad08e.png)

![image](https://user-images.githubusercontent.com/75058881/144863975-7038d364-57f4-4d3b-8501-46393ea88f1d.png)

![image](https://user-images.githubusercontent.com/75058881/144863012-ab3eb3aa-a474-4f17-9327-bcef123ac355.png)

That's from InPrivate Mode.☝🏼😁

**Comment by c2xusnpq6** [comment]
![image](https://user-images.githubusercontent.com/75058881/144880571-32456cf6-1d2f-459f-97ea-01ba96d8b6fe.png)

**Comment by c2xusnpq6** [comment]
https://github.com/iawia002/annie/commit/950db57f997720c42f70fac4d54db0eae49eaf1f

**Comment by c2xusnpq6** [comment]
@soimort https://github.com/soimort/you-get 👀

**Comment by pukkandan** [comment]
@c2xusnpq6 why are you commenting random stuff with no context?

**Comment by c2xusnpq6** [comment]
> @c2xusnpq6 why are you commenting random stuff with no context?

I cannot submit an issue to his repository, and I can only tag him here... So...
