### ISSUE TITLE
--embed-thumbnail option in python implementation?

### ISSUE THREAD

**Issue by zsQ8ymRSY8B4owpdCvTRdkz8rQUK** [yt-dlp/yt-dlp#1901]
### Checklist

- [X] I'm asking a question and not reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

I'm in the process of transitioning my script to using the python implementation of yt-dlp. The only options I can't seem to find in the documentation are the equivalent sof --embed-thumbnail and --embed-metadata

Are there equivalent options in the python version?

**Comment by pukkandan** [comment]
They are postprocessors. See the various classes defined in yt_dlp/postprocessors. The embedding example in readme shows how to add a PP to the options with embed-metadata as the example

**Comment by zsQ8ymRSY8B4owpdCvTRdkz8rQUK** [comment]
I got metadata to work, but I feel I'm missing another key or value to get the thumbnails PP to work. Here's my yt-opts:

`ydl_opts = {
  'download_archive': 'data/archive.txt',
  'paths': { 'home': '/downloads/test', 'temp': '/data' },
  'outtmpl': '%(uploader)s - %(title)s.%(ext)s',
  'merge_output_format': 'mkv',
  'noplaylist': 'true',
  'writesubtitles': 'true',
  'subtitleslangs': 'en',
  'merge_output_format': 'mkv',
  'postprocessors': [{
    # Embed metadata in video using ffmpeg.
    'key': 'FFmpegMetadata',
    'add_metadata': True, }, {
    # Embed thumbnail in file
    'key': 'EmbedThumbnail',
    'already_have_thumbnail': False,
  }],
}`

**Comment by zsQ8ymRSY8B4owpdCvTRdkz8rQUK** [comment]
Solved. For anybody interested:

`ydl_opts = {
  'download_archive': 'data/archive.txt',
  'paths': { 'home': '/downloads/test', 'temp': '/data' },
  'outtmpl': '%(uploader)s - %(title)s.%(ext)s',
  'merge_output_format': 'mkv',
  'noplaylist': 'true',
  'writesubtitles': 'true',
  'subtitleslangs': 'en',
  'merge_output_format': 'mkv',
  'writethumbnail': 'true', # Required to embed thumbnail
  'postprocessors': [{
    # Embed metadata in video using ffmpeg.
    'key': 'FFmpegMetadata',
    'add_metadata': True, }, {
    # Embed thumbnail in file
    'key': 'EmbedThumbnail',
    'already_have_thumbnail': False,
  }],
}`
