### ISSUE TITLE
Find playlists with the specified video

### ISSUE THREAD

**Issue by aleksejrs** [yt-dlp/yt-dlp#1902]
### Checklist

- [X] I'm reporting a site feature request
- [X] I've verified that I'm running yt-dlp version **2021.12.01**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) It comes from the relevant archive file, but has the wrong version string.
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Russia

### Example URLs

https://www.youtube.com/watch?v=BqVoYfFrCMs
https://www.youtube.com/results?search_query=%22Cats+Thug+Life+Compilation%22&sp=EgIQAw%253D%253D

### Description

It is often possible, at least at YouTube, to find playlists with a particular video manually.

For example, the video https://www.youtube.com/watch?v=BqVoYfFrCMs is titled "Cats Thug Life Compilation". To find the playlists it is in, enter "Cats Thug Life Compilation" in the search field, and [filter to show only the playlists](https://www.youtube.com/results?search_query=%22Cats+Thug+Life+Compilation%22&sp=EgIQAw%253D%253D). The playlist https://www.youtube.com/playlist?list=PLnEWEBmsuPQCwUpQhd05Dvry9Y9CH3a_l is the only playlist of the uploader and is the top result.

Some titles are not so easy to search (if they are searchable at all).

Could yt-dlp help searching? This is useful because you can download a playlist into a separate directory.

**Comment by pukkandan** [comment]
How do you expect yt-dlp to be able to do that!? It is a tool to download (and extract data of) videos from the URL you enter, not a search engine. If you have some specific idea on how it could help, you are going to have to explain it better. Because right now, I have no idea how your question is related to yt-dlp at all

You can pass the search URL (with filters) to yt-dlp to fetch info about the playlists, but idk if that is any help to you

**Comment by aleksejrs** [comment]
1. Get the title and the uploader for https://www.youtube.com/watch?v=BqVoYfFrCMs
2. Get playlists with the video like with https://www.youtube.com/results?search_query=%22Cats+Thug+Life+Compilation%22&sp=EgIQAw%253D%253D or by downloading the list data from the uploader's page.
3. List the playlists with the video.

> not a search engine.

It already can list videos without downloading them.

**Comment by pukkandan** [comment]
Sure, you can do all the individual parts of this with yt-dlp. But you'll need to write some kind of script to bring it together

Get channel URL

```
➤ yt-dlp -O channel_url BqVoYfFrCMs
https://www.youtube.com/channel/UCVaQwUU0NLkBeO6m7_j2U2Q
```

Get playlists with the video - note that this may take a long time for large channels. Use `--playlist-end` to limit the search scope if needed

```
➤ yt-dlp --print playlist_id= --print playlist_index= --match-filter "id~=PL.+|BqVoYfFrCMs" "https://www.youtube.com/channel/UCVaQwUU0NLkBeO6m7_j2U2Q/playlists"
playlist_id = PLnEWEBmsuPQCwUpQhd05Dvry9Y9CH3a_l
playlist_index = 4
```

You can also do similar with the search URL, but that would be even slower

---

See the readme for what these options are doing and for the other options that may help you
