### ISSUE TITLE
Site Request: mrdeepfakes.com

### ISSUE THREAD

**Issue by masternoob420** [yt-dlp/yt-dlp#1903]
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2021.12.01**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Example URLs

- Single video: https://mrdeepfakes.com/video/16341/not-brooke-monk-proves-she-is-another-anal-slut-from-tiktok
- Single video: https://mrdeepfakes.com/video/14961/not-bella-poarch-on-vacation-with-stepbro
- Playlist: The site does not support playlists as far as I'm aware.

### Description

I tried to download videos from here but it doesn't work, I've also tried using [The Stream Detector](https://github.com/rowrawer/stream-detector). But that doesn't work either, the site seems to be using KVS v6.

The site does require an account for 1080p(+?)

### Verbose log

```shell
[debug] Command-line config: ['https://mrdeepfakes.com/video/16341/not-brooke-monk-proves-she-is-another-anal-slut-from-tiktok', '-Uv']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2021.12.01 [91f071a] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.22000-SP0
[debug] exe versions: ffmpeg 4.3, ffprobe 4.3
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2021.12.01, Current version: 2021.12.01
yt-dlp is up to date (2021.12.01)
[debug] [generic] Extracting URL: https://mrdeepfakes.com/video/16341/not-brooke-monk-proves-she-is-another-anal-slut-from-tiktok
[generic] not-brooke-monk-proves-she-is-another-anal-slut-from-tiktok: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] not-brooke-monk-proves-she-is-another-anal-slut-from-tiktok: Downloading webpage
[generic] not-brooke-monk-proves-she-is-another-anal-slut-from-tiktok: Extracting information
[debug] Looking for video embeds
[debug] Identified a KWS Player
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 16341: Downloading 1 format(s): 720p
[debug] Invoking downloader on "https://mrdeepfakes.com/get_file/8/29443f383b1d78234963501b8cd48057abb889774d/16000/16341/16341_720p.mp4/?br=1995"
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 2933, in process_info
  File "yt_dlp\YoutubeDL.py", line 2654, in dl
  File "yt_dlp\downloader\common.py", line 421, in download
  File "yt_dlp\downloader\http.py", line 372, in real_download
  File "yt_dlp\downloader\http.py", line 120, in establish_connection
  File "yt_dlp\downloader\http.py", line 114, in establish_connection
  File "yt_dlp\YoutubeDL.py", line 3385, in urlopen
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 563, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 755, in http_error_302
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

**Comment by nyuszika7h** [comment]
Pretty sure this is illegal in many countries.

**Comment by pukkandan** [comment]
There are currently no deep-fake sites in youtube-dl/yt-dlp. Since there is no precedent for this, I am making the decision not to support deep fake porn
