### ISSUE TITLE
[Feature Request] Private field with date/time of download (and other timings, potentially)

### ISSUE THREAD

**Issue by Zirro** [yt-dlp/yt-dlp#191]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running yt-dlp version **2021.03.21**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description

With the recognition of private/meta-meta fields in https://github.com/yt-dlp/yt-dlp/commit/75d43ca08004e711fb37694f7208af35615118d5, I'd like to suggest the addition of a field containing the datetime the file was written (basically the infojson's `mtime`, but more likely to be preserved).

If you don't mind writing to the file several times, it might also be useful to log the time for when each processing stage began and finished - the downloads, merging, embedding metadata, embedding thumbnail, xattrs and whether any error/abort occurred. These could be useful for me in determining the impact of changes to my configuration over time, as well as finding files that I want to reprocess later.

**Comment by pukkandan** [comment]
"Private fields" does not mean fields with fields with personal info. They refer to data that is normally used for internal use such as `_filename`. I knew someone would confuse this, but I dont really know how to document it better
```
    --clean-infojson                 Remove some private fields such as
                                     filenames from the infojson. Note that it
                                     could still contain some personal
                                     information
```

> I'd like to suggest the addition of a field containing the datetime the file was written (basically the infojson's mtime, but more likely to be preserved

This can be added, but the rest is not feasible since the file is written before any download process starts

**Comment by Zirro** [comment]
> "Private fields" does not mean fields with fields with personal info.

I'm aware of this, but given the introduction of CLI flags to keep the data I don't think there's a need to distinguish between the two meanings in this case.

> This can be added, but the rest is not feasible since the file is written before any download process starts

The file could be modified several times after the initial creation to insert new data in the JSON structure, if this feature is desirable.
