### ISSUE TITLE
DateRange Object

### ISSUE THREAD

**Issue by zsQ8ymRSY8B4owpdCvTRdkz8rQUK** [yt-dlp/yt-dlp#1912]
### Checklist

- [X] I'm asking a question and not reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

I'm trying to get the daterange option working in yt_dlp, but I get the following error:
`[download] 2021-12-02 upload date is not in range {'start': '2021-11-07', 'end': '2021-12-07'}`

daterange led me to the DateRange object, which looks for two key pairs, 'start' and 'end'. I've tried many variations of feeding it date formats but nothing works. What am I doing wrong here?

```
history = 30 #days how far back to download
history_end = date.today().isoformat()
history_start = ( date.today() - timedelta(days=history) ).isoformat()

ydl_opts = {
  'daterange': { 'start': history_start, 'end': history_end },
```

**Comment by nyuszika7h** [comment]
Try this:
```py
from yt_dlp.utils import DateRange

ydl_opts = {
    'daterange': DateRange(history_start, history_end)
}
```
