### ISSUE TITLE
IQYI 

### ISSUE THREAD

**Issue by BlackLuster13** [yt-dlp/yt-dlp#1919]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2021.12.01**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Philippines

### Description

I cant download on IQYI

### Verbose log

```shell
D:\ytdl>yt-dlp.exe -v https://www.iq.com/play/demon-slayer-kimetsu-no-yaiba-entertainment-district-arc-episode-1-1q4exf58np0?lang=en_us
[debug] Command-line config: ['-v', 'https://www.iq.com/play/demon-slayer-kimetsu-no-yaiba-entertainment-district-arc-episode-1-1q4exf58np0?lang=en_us']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2021.12.01 [91f071a] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19042-SP0
[debug] exe versions: ffmpeg 2021-10-28-git-e84c83ef98-essentials_build-www.gyan.dev (setts), ffprobe 2021-10-28-git-e84c83ef98-essentials_build-www.gyan.dev
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [generic] Extracting URL: https://www.iq.com/play/demon-slayer-kimetsu-no-yaiba-entertainment-district-arc-episode-1-1q4exf58np0?lang=en_us
[generic] demon-slayer-kimetsu-no-yaiba-entertainment-district-arc-episode-1-1q4exf58np0?lang=en_us: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] demon-slayer-kimetsu-no-yaiba-entertainment-district-arc-episode-1-1q4exf58np0?lang=en_us: Downloading webpage
```

**Comment by Ashish0804** [comment]
wrong domain and there's already an open issue for it.

**Comment by pukkandan** [comment]
Duplicate of https://github.com/yt-dlp/yt-dlp/issues/704
