### ISSUE TITLE
Live streams from raiplayradio.it

### ISSUE THREAD

**Issue by 4ricci** [yt-dlp/yt-dlp#1920]
### Checklist

- [X] I'm reporting a site feature request
- [X] I've verified that I'm running yt-dlp version **2021.12.01**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Italy

### Example URLs

https://www.raiplayradio.it/radio1 (https://radiounoita-live.akamaized.net/hls/live/2032820/radiounoita/radiounoita/playlist.m3u8)
https://www.raiplayradio.it/radio2 (https://radiodue-live.akamaized.net/hls/live/2032592/radiodue/radiodue/playlist.m3u8)

### Description

Playlists and individual audios from raiplayradio.it are already supported, as well as live streams from raiplay.it, but not live streams from the former.

I briefly tried to change the url regexes of various extractors defined in `rai.py` to see if the existing code was enough, but this didn't work.

**Comment by pukkandan** [comment]
@frafra and @nixxo may be interested

**Comment by 4ricci** [comment]
This could be fixed together with #1951.
