### ISSUE TITLE
Downloads from oneplus.ch - For example, "Bauer, ledig, sucht"

### ISSUE THREAD

**Issue by m1w31l** [yt-dlp/yt-dlp#1922]
### Checklist

- [X] I'm reporting a site feature request
- [X] I've verified that I'm running yt-dlp version **2021.12.01**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Switzerland

### Example URLs

https://www.oneplus.ch/play/1008188
https://www.oneplus.ch/play/1010969
https://www.oneplus.ch/play/1013461

### Description

Is it possible that you include the download of oneplus.ch?
Thank you in advance.

**Comment by nyuszika7h** [comment]
All of the videos you linked have DRM.

**Comment by m1w31l** [comment]
Oh, that's right. They just recently switched the site over and apparently everything is DRM since then. Sorry for the request.
