### ISSUE TITLE
[Broken] BIQLE (biqle.ru)

### ISSUE THREAD

**Issue by mmshasan** [yt-dlp/yt-dlp#193]
## Checklist

- [x ] I'm reporting a broken site support
- [x ] I've verified that I'm running yt-dlp version **2021.03.21**
- [x ] I've checked that all provided URLs are alive and playable in a browser
- [x ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x ] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] Command-line config: ['-F', '--verbose', 'https://biqle.ru/watch/-XXXXXXXXX_XXXXXXXXX']
[debug] Loading archive file None
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] yt-dlp version 2021.03.21 (exe)
[debug] Python version 3.8.8 (CPython 64bit) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg 2021-03-07-git-a7f841718f-full_build-www.gyan.dev, ffprobe 2021-03-07-git-a7f841718f-full_build-www.gyan.dev
[debug] Proxy map: {}
[BIQLE] -XXXXXXXXX_XXXXXXXXX: Downloading webpage
[BIQLE] -XXXXXXXXX_XXXXXXXXX: Downloading webpage
[BIQLE] -XXXXXXXXX_XXXXXXXXX: Downloading JSON metadata
ERROR: not enough values to unpack (expected 2, got 1)
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1025, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1046, in __extract_info
  File "yt_dlp\extractor\common.py", line 558, in extract
  File "yt_dlp\extractor\biqle.py", line 75, in _real_extract
ValueError: not enough values to unpack (expected 2, got 1)

```

## Description

I frequently download videos from biqle.ru, and it's stopped working before the last release

**Comment by 2ShedsJackson** [comment]
Changing line 75 of extractor/biqle.py to `ext, height = f_id.split('_') if '_' in f_id else (f_id, '')` fixes the ValueError problem. However, downloading results in different errors, depending on the video, including `HTTP Error 400: Bad Request`. Intermediate links that yt-dlp can't download are accessible via curl. Something strange is going on outside the extractor.

Here's a short non-pornographic video on the site: https://biqle.ru/watch/-2000421746_85421746
Other content that appears on the webpage, however, is NSFW.

**Comment by october262** [comment]
for this link -  https://biqle.ru/watch/-2000421746_85421746 yt-dlp & youtube-dl chokes if
you try to use the index.m3u8 via the developer tools, i used the firefox addon called the stream detector to download the video.

**Comment by nonjenec** [comment]
how is the progress of this issue now? currently using JD2.

here's my attempt
```
C:\Users\brave>yt-dlp --verbose https://biqle.org/watch/220757514_456239939
[debug] User config file: C:\Users\#####\AppData\Roaming\yt-dlp\config
[debug] User config: ['--download-archive', '-w', '-4', '-n', '--no-mtime', '--print-traffic', '-f', 'bv*[height<=480]+ba/b[height<=480]']
[debug] Command-line config: ['--verbose', 'https://biqle.org/watch/220757514_456239939']

[debug] Encodings: locale cp65001, fs utf-8, out utf-8, pref cp65001
[debug] yt-dlp version 2021.09.02 (exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19042-SP0
[debug] exe versions: ffmpeg 4.2.3, ffprobe 4.2.3
[debug] Optional libraries: mutagen, pycryptodome, sqlite, websockets
[debug] Proxy map: {}
[debug] [BIQLE] Extracting URL: https://biqle.org/watch/220757514_456239939
[BIQLE] 220757514_456239939: Downloading webpage
send: b'GET /watch/220757514_456239939 HTTP/1.1\r\nHost: biqle.org\r\nUser-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.113 Safari/537.36\r\nAccept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7\r\nAccept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8\r\nAccept-Encoding: gzip, deflate\r\nAccept-Language: en-us,en;q=0.5\r\nConnection: close\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
header: Server: nginx
header: Date: Wed, 15 Sep 2021 02:11:26 GMT
header: Content-Type: text/html; charset=utf-8
header: Content-Length: 10289
header: Connection: close
header: Set-Cookie: ext_on=1; expires=Wed, 15-Sep-2021 02:12:26 GMT; Max-Age=60
header: X-Frame-Options: DENY
header: Vary: Accept-Encoding
header: Content-Encoding: gzip
ERROR: [BIQLE] 220757514_456239939: Unable to extract embed url; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "yt_dlp\extractor\common.py", line 584, in extract
  File "yt_dlp\extractor\biqle.py", line 45, in _real_extract
  File "yt_dlp\extractor\common.py", line 1147, in _search_regex
yt_dlp.utils.RegexNotFoundError: Unable to extract embed url; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "yt_dlp\extractor\common.py", line 584, in extract
  File "yt_dlp\extractor\biqle.py", line 45, in _real_extract
  File "yt_dlp\extractor\common.py", line 1147, in _search_regex
yt_dlp.utils.RegexNotFoundError: Unable to extract embed url; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1214, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1239, in __extract_info
  File "yt_dlp\extractor\common.py", line 600, in extract
yt_dlp.utils.ExtractorError: [BIQLE] 220757514_456239939: Unable to extract embed url; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
```

this also happens in youtube-dl too

**Comment by nonjenec** [comment]
how is the progress of this issue now? currently using JD2.

here's my attempt

C:\Users\#####>yt-dlp --verbose https://biqle.org/watch/220757514_456239939
[debug] User config file: C:\Users\#####\AppData\Roaming\yt-dlp\config
[debug] User config: ['--download-archive', '-w', '-4', '-n', '--no-mtime', '--print-traffic', '-f', 'bv*[height<=480]+ba/b[height<=480]']
[debug] Command-line config: ['--verbose', 'https://biqle.org/watch/220757514_456239939']

[debug] Encodings: locale cp65001, fs utf-8, out utf-8, pref cp65001
[debug] yt-dlp version 2021.09.02 (exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19042-SP0
[debug] exe versions: ffmpeg 4.2.3, ffprobe 4.2.3
[debug] Optional libraries: mutagen, pycryptodome, sqlite, websockets
[debug] Proxy map: {}
[debug] [BIQLE] Extracting URL: https://biqle.org/watch/220757514_456239939
[BIQLE] 220757514_456239939: Downloading webpage
send: b'GET /watch/220757514_456239939 HTTP/1.1\r\nHost: biqle.org\r\nUser-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.113 Safari/537.36\r\nAccept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7\r\nAccept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8\r\nAccept-Encoding: gzip, deflate\r\nAccept-Language: en-us,en;q=0.5\r\nConnection: close\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
header: Server: nginx
header: Date: Wed, 15 Sep 2021 02:11:26 GMT
header: Content-Type: text/html; charset=utf-8
header: Content-Length: 10289
header: Connection: close
header: Set-Cookie: ext_on=1; expires=Wed, 15-Sep-2021 02:12:26 GMT; Max-Age=60
header: X-Frame-Options: DENY
header: Vary: Accept-Encoding
header: Content-Encoding: gzip
ERROR: [BIQLE] 220757514_456239939: Unable to extract embed url; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "yt_dlp\extractor\common.py", line 584, in extract
  File "yt_dlp\extractor\biqle.py", line 45, in _real_extract
  File "yt_dlp\extractor\common.py", line 1147, in _search_regex
yt_dlp.utils.RegexNotFoundError: Unable to extract embed url; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "yt_dlp\extractor\common.py", line 584, in extract
  File "yt_dlp\extractor\biqle.py", line 45, in _real_extract
  File "yt_dlp\extractor\common.py", line 1147, in _search_regex
yt_dlp.utils.RegexNotFoundError: Unable to extract embed url; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1214, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1239, in __extract_info
  File "yt_dlp\extractor\common.py", line 600, in extract
yt_dlp.utils.ExtractorError: [BIQLE] 220757514_456239939: Unable to extract embed url; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.

this also happens in youtube-dl too

**Comment by nonjenec** [comment]
how is the progress of this issue now? currently using JD2.

here's my attempt

```
C:\Users\#####>yt-dlp --verbose https://biqle.org/watch/220757514_456239939
[debug] User config file: C:\Users\#####\AppData\Roaming\yt-dlp\config
[debug] User config: ['--download-archive', '-w', '-4', '-n', '--no-mtime', '--print-traffic', '-f', 'bv*[height<=480]+ba/b[height<=480]']
[debug] Command-line config: ['--verbose', 'https://biqle.org/watch/220757514_456239939']

[debug] Encodings: locale cp65001, fs utf-8, out utf-8, pref cp65001
[debug] yt-dlp version 2021.09.02 (exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19042-SP0
[debug] exe versions: ffmpeg 4.2.3, ffprobe 4.2.3
[debug] Optional libraries: mutagen, pycryptodome, sqlite, websockets
[debug] Proxy map: {}
[debug] [BIQLE] Extracting URL: https://biqle.org/watch/220757514_456239939
[BIQLE] 220757514_456239939: Downloading webpage
send: b'GET /watch/220757514_456239939 HTTP/1.1\r\nHost: biqle.org\r\nUser-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.113 Safari/537.36\r\nAccept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7\r\nAccept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8\r\nAccept-Encoding: gzip, deflate\r\nAccept-Language: en-us,en;q=0.5\r\nConnection: close\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
header: Server: nginx
header: Date: Wed, 15 Sep 2021 02:11:26 GMT
header: Content-Type: text/html; charset=utf-8
header: Content-Length: 10289
header: Connection: close
header: Set-Cookie: ext_on=1; expires=Wed, 15-Sep-2021 02:12:26 GMT; Max-Age=60
header: X-Frame-Options: DENY
header: Vary: Accept-Encoding
header: Content-Encoding: gzip
ERROR: [BIQLE] 220757514_456239939: Unable to extract embed url; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "yt_dlp\extractor\common.py", line 584, in extract
  File "yt_dlp\extractor\biqle.py", line 45, in _real_extract
  File "yt_dlp\extractor\common.py", line 1147, in _search_regex
yt_dlp.utils.RegexNotFoundError: Unable to extract embed url; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "yt_dlp\extractor\common.py", line 584, in extract
  File "yt_dlp\extractor\biqle.py", line 45, in _real_extract
  File "yt_dlp\extractor\common.py", line 1147, in _search_regex
yt_dlp.utils.RegexNotFoundError: Unable to extract embed url; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1214, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1239, in __extract_info
  File "yt_dlp\extractor\common.py", line 600, in extract
yt_dlp.utils.ExtractorError: [BIQLE] 220757514_456239939: Unable to extract embed url; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
```

this also happens in youtube-dl too
