### ISSUE TITLE
NPR Music Tiny Desk Sporadically Broken

### ISSUE THREAD

**Issue by cliss** [yt-dlp/yt-dlp#1934]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2021.12.01**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United States

### Description

I've found an instance of a [NPR Tiny Desk Concert](https://www.npr.org/series/tiny-desk-concerts/) that does not work.

Most concerts — such as [this one](https://www.npr.org/2021/10/15/1045251626/camila-cabello-tiny-desk-home-concert) — work no sweat.

Oddly, [this one](https://www.npr.org/2021/10/26/1048372074/ed-sheeran-tiny-desk-home-concert) does not. It plays just fine in Safari.

### Verbose log

```shell
[debug] Command-line config: ['-Uv', 'https://www.npr.org/2021/10/26/1048372074/ed-sheeran-tiny-desk-home-concert']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8 (No ANSI), err utf-8, pref UTF-8
[debug] yt-dlp version 2021.12.01 [91f071af6]
[debug] Python version 3.10.0 (CPython 64bit) - macOS-12.0.1-arm64-arm-64bit
[debug] exe versions: ffmpeg 4.4.1 (setts), ffprobe 4.4.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [Npr] Extracting URL: https://www.npr.org/2021/10/26/1048372074/ed-sheeran-tiny-desk-home-concert
WARNING: [Npr] Failed to download m3u8 information: HTTP Error 404: Not Found
ERROR: [Npr] 1048372074: Unable to download SMIL file: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output. (caused by <HTTPError 404: 'Not Found'>); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
  File "/opt/homebrew/Cellar/yt-dlp/2021.12.1/libexec/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 715, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/opt/homebrew/Cellar/yt-dlp/2021.12.1/libexec/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3385, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/opt/homebrew/Cellar/python@3.10/3.10.0_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/opt/homebrew/Cellar/python@3.10/3.10.0_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/opt/homebrew/Cellar/python@3.10/3.10.0_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/opt/homebrew/Cellar/python@3.10/3.10.0_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/opt/homebrew/Cellar/python@3.10/3.10.0_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
```

**Comment by nixxo** [comment]
i checked and it fails because the website returns a cookie consent webpage instead of the page the extractor expects...

**Comment by r5d** [comment]
Looks like most (or perhaps all) SMIL links returned by api.npr.org
   are 404s.

   Currently, the `_extract_smil_formats` call in `NprIE` does not
   pass `fatal=False`. Consequently, the call fails and makes the 
   download fail.

   If `fatal=False` is passed to `_extract_smil_formats`, the download
   works:

```bash
$ python -m yt_dlp https://www.npr.org/2021/10/26/1048372074/ed-sheeran-tiny-desk-home-concert
[Npr] 1048372074: Downloading JSON metadata
[Npr] 1048379421: Downloading m3u8 information
WARNING: [Npr] Failed to download m3u8 information: HTTP Error 404: Not Found
[Npr] 1048379421: Downloading SMIL file
WARNING: [Npr] Unable to download SMIL file: HTTP Error 404: Not Found
[Npr] hlsUrl: Downloading m3u8 information
[download] Downloading playlist: Ed Sheeran: Tiny Desk (Home) Concert
[Npr] playlist Ed Sheeran: Tiny Desk (Home) Concert: Collected 1 videos; downloading 1 of them
[download] Downloading video 1 of 1
[info] 1048379421: Downloading 1 format(s): hls-3740
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 338
[download] Destination: Ed Sheeran - Tiny Desk (Home) Concert [1048379421].mp4
[download] 100% of 618.08MiB in 10:16
[FixupM3u8] Fixing MPEG-TS in MP4 container of "Ed Sheeran - Tiny Desk (Home) Concert [1048379421].mp4"
[download] Finished downloading playlist: Ed Sheeran: Tiny Desk (Home) Concert
```

   Here's the patch:

```diff
diff --git a/yt_dlp/extractor/common.py b/yt_dlp/extractor/common.py
index e15763953..6cd2551bf 100644
--- a/yt_dlp/extractor/common.py
+++ b/yt_dlp/extractor/common.py
@@ -2332,7 +2332,7 @@ class InfoExtractor(object):
 
         if smil is False:
             assert not fatal
-            return []
+            return [], {}
 
         namespace = self._parse_smil_namespace(smil)
 
diff --git a/yt_dlp/extractor/npr.py b/yt_dlp/extractor/npr.py
index 9d1122f0c..49f062d7a 100644
--- a/yt_dlp/extractor/npr.py
+++ b/yt_dlp/extractor/npr.py
@@ -91,7 +91,8 @@ class NprIE(InfoExtractor):
                     elif format_id == 'smil':
                         smil_formats = self._extract_smil_formats(
                             format_url, media_id, transform_source=lambda s: s.replace(
-                                'rtmp://flash.npr.org/ondemand/', 'https://ondemand.npr.org/'))
+                                'rtmp://flash.npr.org/ondemand/', 'https://ondemand.npr.org/'),
+                            fatal=False)
                         self._check_formats(smil_formats, media_id)
                         formats.extend(smil_formats)
                     else:
```

   Does this look good? Should I go ahead and open a PR?

**Comment by pukkandan** [comment]
> Should I go ahead and open a PR?

please do

**Comment by r5d** [comment]
> > Should I go ahead and open a PR?
> 
> please do

Done.

**Comment by cliss** [comment]
Just tested this on the new release. Works perfectly. Thank you, @r5d!

**Comment by cliss** [comment]
Seems this has cropped up again, unfortunately. Currently seeing a failure with [this video](https://www.npr.org/2022/03/15/1084896560/bonobo-tiny-desk-home-concert).

<details><summary>Log Here</summary>

```
[debug] Command-line config: ['-Uv', 'https://www.npr.org/2022/03/15/1084896560/bonobo-tiny-desk-home-concert']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8 (No ANSI), err utf-8, pref UTF-8
[debug] yt-dlp version 2022.04.08 [7884ade65]
[debug] Python version 3.10.2 (CPython 64bit) - macOS-12.3.1-arm64-arm-64bit
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 5.0.1 (setts), ffprobe 5.0.1, rtmpdump 2.4
[debug] Optional libraries: brotli, certifi, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [Npr] Extracting URL: https://www.npr.org/2022/03/15/1084896560/bonobo-tiny-desk-home-concert
ERROR: [Npr] 1086468851: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/yt-dlp/2022.4.8/libexec/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1408, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/homebrew/Cellar/yt-dlp/2022.4.8/libexec/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1834, in __process_iterable_entry
    return self.process_ie_result(
  File "/opt/homebrew/Cellar/yt-dlp/2022.4.8/libexec/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1548, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/opt/homebrew/Cellar/yt-dlp/2022.4.8/libexec/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 2487, in process_video_result
    self.raise_no_formats(info_dict)
  File "/opt/homebrew/Cellar/yt-dlp/2022.4.8/libexec/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 981, in raise_no_formats
    raise ExtractorError(msg, video_id=info['id'], ie=info['extractor'],
yt_dlp.utils.ExtractorError: [Npr] 1086468851: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

</details>

**Comment by r5d** [comment]
For the Bonobo link, the `format` and `stream` fields, under the
`multimedia` object returned by the API, are empty:

<details>
<summary>curl dump</summary>
<pre>
curl -s "http://api.npr.org/query?id=1084896560&fields=audio,multimedia,title&format=json&apiKey=MDAzMzQ2MjAyMDEyMzk4MTU1MDg3ZmM3MQ010" | python -m json.tool
{
    "version": "0.94",
    "list": {
        "title": {
            "$text": "Stories from NPR"
        },
        "teaser": {
            "$text": "Assorted stories from NPR"
        },
        "miniTeaser": {
            "$text": "Custom NPR News Feed API.  Visit https://www.npr.org/templates/apidoc/index.php for more information."
        },
        "link": [
            {
                "type": "api",
                "$text": "http://api.npr.org/query?id=1084896560&apiKey=MDAzMzQ2MjAyMDEyMzk4MTU1MDg3ZmM3MQ010"
            },
            {
                "type": "html",
                "$text": "https://www.npr.org/2022/03/15/1084896560/bonobo-tiny-desk-home-concert?ft=nprml&f=1084896560"
            }
        ],
        "story": [
            {
                "id": "1084896560",
                "link": [
                    {
                        "type": "html",
                        "$text": "https://www.npr.org/2022/03/15/1084896560/bonobo-tiny-desk-home-concert?ft=nprml&f=1084896560"
                    },
                    {
                        "type": "api",
                        "$text": "http://api.npr.org/query?id=1084896560&apiKey=MDAzMzQ2MjAyMDEyMzk4MTU1MDg3ZmM3MQ010"
                    }
                ],
                "title": {
                    "$text": "Bonobo: Tiny Desk (Home) Concert"
                },
                "multimedia": [
                    {
                        "id": "1086468851",
                        "title": {},
                        "duration": {
                            "$text": "1061"
                        },
                        "format": {},
                        "dataUrl": {},
                        "rightsHolder": {},
                        "caption": {},
                        "credit": {
                            "$text": "Courtesy of the artist"
                        },
                        "width": {
                            "$text": "624"
                        },
                        "height": {
                            "$text": "351"
                        },
                        "altImageUrl": {
                            "$text": "https://media.npr.org/assets/img/2022/03/14/20220310_tdhc-bonobo_thumbnail_wide-d5df4d272116d5fef9b89fb46d56bf71820ee300.jpg"
                        },
                        "permissions": {
                            "download": {
                                "allow": "false"
                            },
                            "stream": {
                                "allow": "true"
                            },
                            "embed": {
                                "allow": "true"
                            }
                        },
                        "stream": {
                            "active": "false"
                        }
                    }
                ]
            }
        ]
    }
}
</pre>
</details>

The NPR extractor depends on the link in the `format` and `stream`
fields for downloading the video. Consequently, the download fails.

Forunately, the NPR web page contains a JSON-LD with the "stream" link
in the JSON-LD VideoObject's "embedUrl" field.

I've opened PR #3455 that updates the NPR Extractor to use the "embedUrl"
as a stream url if the `format` and `stream` fields returned by the
API is empty.

The Bonobo link downloads successfully with the patch in PR #3455:

```bash
$ python -m yt_dlp https://www.npr.org/2022/03/15/1084896560/bonobo-tiny-desk-home-concert
[Npr] 1084896560: Downloading JSON metadata
[Npr] 1084896560: Downloading webpage
[Npr] hlsUrl: Downloading m3u8 information
[download] Downloading playlist: Bonobo: Tiny Desk (Home) Concert
[Npr] playlist Bonobo: Tiny Desk (Home) Concert: Collected 1 videos; downloading 1 of them
[download] Downloading video 1 of 1
[info] 1086468851: Downloading 1 format(s): hls-3620
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 266
[download] Destination: Bonobo - Tiny Desk (Home) Concert [1086468851].mp4
[download] 100% of 470.85MiB in 08:38
[FixupM3u8] Fixing MPEG-TS in MP4 container of "Bonobo - Tiny Desk (Home) Concert [1086468851].mp4"
[download] Finished downloading playlist: Bonobo: Tiny Desk (Home) Concert
```

**Comment by r5d** [comment]
@cliss, you could use the NPR Music youtube feed to download tiny
concerts -- https://www.youtube.com/feeds/videos.xml?channel_id=UC4eYXhJI4-7wSWc8UNRwD4A

i've (written and) been using [fern][fern] to download tiny desk
concerts. fern parses youtube feeds and uses yt-dlp to download the
videos.

Something like this:

```json
   {
      "id": "tiny-desk",
      "source": "https://www.youtube.com/feeds/videos.xml?channel_id=UC4eYXhJI4-7wSWc8UNRwD4A",
      "schema": "youtube",
      "title-contains": "tiny desk",
      "last": 10
   }
```

in the fern config will make fern download just tiny desk videos from
the NPR Music feed.

See https://pkg.go.dev/ricketyspace.net/fern if you want to try fern.

[fern]: https://pkg.go.dev/ricketyspace.net/fern

**Comment by cliss** [comment]
@r5d Thanks for the fix! Excited to try it.

Thanks for the tip wrt `fern`; I’ll keep that in mind. Generally speaking I prefer to download Tiny Desks piecemeal, rather than en masse, but I’m happy to have another tool to keep in mind. :)

**Comment by r5d** [comment]
@cliss, You may test the fix with:

```bash
git clone --branch npr-1934-jsonld-fallback https://github.com/r5d/yt-dlp.git
cd yt-dlp
python3 -m yt_dlp https://www.npr.org/2022/03/15/1084896560/bonobo-tiny-desk-home-concert
```

**Comment by cliss** [comment]
Confirmed, @r5d: worked no sweat. 😗👌🏻
