### ISSUE TITLE
aria2c doesn't unpack gzip encoded files during downloading

### ISSUE THREAD

**Issue by vevv** [yt-dlp/yt-dlp#1936]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2021.12.01**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

Issue: output file is gzip when downloading with aria2c

Reproduction steps:
* run `yt-dlp https://tubitv.com/movies/528795 --external-downloader aria2c`
* run file/mediainfo on the output file, it should show gzip; creates a valid MP4 after `gzip -d` is run on it.
(checking individual fragments during downloading shows they are expectedly also gzip)

Suggested fix:
* add `--http-accept-gzip=true` flag to the aria2c command line, if Accept-Encoding header has gzip in it; adding it manually to the command copied from the log results in files being correctly unpacked

### Verbose log

```shell
[debug] Command-line config: ['-Uv', 'https://tubitv.com/movies/528795', '--proxy', '[REDACTED]', '--external-downloader', 'aria2c', '--write-sub']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2021.12.01 [91f071af6]
[debug] Python version 3.9.2 (CPython 64bit) - Linux-4.19.0-16-amd64-x86_64-with-glibc2.31
[debug] exe versions: ffmpeg 4.4 (fdk,setts), ffprobe 4.4, phantomjs 2.1.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {'http': '[REDACTED]', 'https': '[REDACTED]'}
Latest version: 2021.12.01, Current version: 2021.12.01
yt-dlp is up to date (2021.12.01)
[debug] Using fake IP [REDACTED] (US) as X-Forwarded-For
[debug] [TubiTv] Extracting URL: https://tubitv.com/movies/528795
[TubiTv] 528795: Downloading JSON metadata
[TubiTv] 528795: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Downloading subtitles: English
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 528795: Downloading 1 format(s): 2674
[info] Writing video subtitles to: Last Train to Berlin [528795].English.srt
[debug] Invoking downloader on "http://s.adrise.tv/e8b6b416-f795-4d0f-9eac-b8e3c8ebfd2f.srt"
[download] Destination: Last Train to Berlin [528795].English.srt
[debug] aria2c command line: aria2c -c --console-log-level=warn --summary-interval=0 --download-result=hide --file-allocation=none -x16 -j16 -s16 --min-split-size 1M --header 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3767.0 Safari/537.36' --header 'Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7' --header 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8' --header 'Accept-Encoding: gzip, deflate' --header 'Accept-Language: en-us,en;q=0.5' --header 'X-Forwarded-For: 6.90.60.174' --all-proxy [REDACTED] --check-certificate=true --remote-time=true --out './Last Train to Berlin [528795].English.srt.part' --auto-file-renaming=false -- http://s.adrise.tv/e8b6b416-f795-4d0f-9eac-b8e3c8ebfd2f.srt
[aria2c] Downloaded 49290 bytes
[download] 100% of 48.13KiB in 00:01
[debug] Invoking downloader on "https://manifest.production-public.tubi.io/29a48477-0a09-4282-8ef8-12f50b242583/vjruqgnb/stream.m3u8?token=[REDACTED]&manifest=true"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Fragment downloads will be delegated to aria2c
[hlsnative] Total fragments: 1521
[download] Destination: Last Train to Berlin [528795].mp4
[debug] aria2c command line: aria2c -c --console-log-level=warn --summary-interval=0 --download-result=hide --file-allocation=none -x16 -j16 -s16 --allow-overwrite=true --allow-piece-length-change=true --header 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3767.0 Safari/537.36' --header 'Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7' --header 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8' --header 'Accept-Encoding: gzip, deflate' --header 'Accept-Language: en-us,en;q=0.5' --header 'X-Forwarded-For: 6.90.60.174' --all-proxy [REDACTED] --check-certificate=true --remote-time=true --auto-file-renaming=false --file-allocation=none --uri-selector=inorder -i 'Last Train to Berlin [528795].mp4.part.frag.urls'
[aria2c] Downloaded 1668683888 bytes)][#72017d 0B/1.2MiB(0%)][#e838ef 0B/690KiB(0%)][#20ab87 0B/1.2MiB(0%)][#51e575 0B/1.2MiB(0%)](+11)
[download] 100% of 1.55GiB in 03:12
[debug] ffprobe command line: ffprobe -hide_banner -show_format -show_streams -print_format json 'file:Last Train to Berlin [528795].mp4'
```

**Comment by pukkandan** [comment]
Temporary workaround: Add the flag to `--downloader-args`

Is it safe to always add `--http-accept-gzip=true` irrespective of the accept-encoding? 🤔

**Comment by vevv** [comment]
I think it should be fine, but not sure, there's all kinds of weirdly behaving servers out there. Thanks for letting me know about `--downloader-args`, didn't know about it and ended up just temporarily adding the flag to `yt_dlp/downloader/external.py` manually.

**Comment by nyuszika7h** [comment]
From the man page:
> **NOTE:**
> Some server responds with Content-Encoding: gzip for files which itself is gzipped file. aria2 inflates them anyway because of the response header.

**Comment by slycordinator** [comment]
When I add the --http-accept-gzip=true to the external downloader arguments, I still end up with a subtitle file downloaded that is actually gzip data.

$ yt-dlp --write-sub --sub-lang en --external-downloader "aria2c" --external-downloader-args "--http-accept-gzip=true -c -j 5 -x 5 -s 5 -k 1M" "$YOUTUBE_URL"

$ file video_name.en.vtt
video_name.en.vtt: gzip compressed data, max compression, original size modulo 2^32 4189

And when I remove that argument, I get the same result.
