### ISSUE TITLE
[facebook] Does not extract `uploader`

### ISSUE THREAD

**Issue by stdedos** [yt-dlp/yt-dlp#1943]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2021.12.01**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Description

WARNING: [facebook] unable to extract OpenGraph title; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.

### Verbose log

```shell
$ youtube-dl-mp4 --no-download-archive --verbose https://www.facebook.com/watch/?v=371287803854594
[debug] Command-line config: ['--sponsorblock-mark', 'all', '--download-archive', '~/.yt-archive.txt', '--compat-options', 'filename', '--no-clean-infojson', '-S', 'ext', '--no-download-archive', '--verbose', 'https://www.facebook.com/watch/?v=371287803854594']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2021.12.01 [91f071af6]
[debug] Lazy loading extractors is disabled
[debug] Compatibility options: filename
[debug] Python version 3.8.5 (CPython 64bit) - Linux-4.4.0-18362-Microsoft-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.2-static, ffprobe 4.0.2-static
[debug] Optional libraries: Cryptodome, keyring, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [facebook] Extracting URL: https://www.facebook.com/watch/?v=371287803854594
[facebook] 371287803854594: Downloading webpage
[debug] Sort order given by user: ext
[debug] Sort order given by extractor: res, quality
[debug] Formats sorted by: hasvid, ie_pref, vext, aext, res, quality, lang, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, hasaud, source, id
WARNING: [facebook] unable to extract OpenGraph title; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
[SponsorBlock] SponsorBlock is not supported for Facebook
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 371287803854594: Downloading 1 format(s): hd
[debug] Invoking downloader on "https://scontent-hel3-1.xx.fbcdn.net/v/t66.36240-6/45693187_2775132492784847_4037222365591080173_n.mp4?_nc_cat=110&ccb=1-5&_nc_sid=985c63&efg=eyJybHIiOjE1MDAsInJsYSI6MTAyNCwidmVuY29kZV90YWciOiJvZXBfaGQifQ%3D%3D&_nc_ohc=0WS1L8n33kQAX_g_GKk&rl=1500&vabr=255&_nc_ht=scontent-hel3-1.xx&oh=1565c1e4f0a6d2068058c221f6a5ffb8&oe=61B7EF36"
[download] Facebook video #371287803854594-371287803854594.mp4 has already been downloaded
[download] 100% of 449.75KiB[Metadata] There isn't any metadata to add
```

**Comment by pukkandan** [comment]
The warning is wrong 🤦. It is actually failing to extract the uploader, not the title

**Comment by pukkandan** [comment]
Related https://github.com/yt-dlp/yt-dlp/issues/795 https://github.com/yt-dlp/yt-dlp/issues/453

**Comment by stdedos** [comment]
Apologies for the issue-spam. I can track one of the linked ones, if you think "my issue" is part of either one (or as a whole)

(It's not really an issue I myself "bother with"; I just thought you (i.e. yt-dlp) really meant that "WARNING: [facebook] unable to extract OpenGraph title; please report this issue")

**Comment by pukkandan** [comment]
This is a valid issue and is separate from the other reported issues (though related to them)

**Comment by barsnick** [comment]
The uploader seems to now be in the embedded JSON (twice), in such a construct:
```
"owner":{"__typename":"Page","name":"This is the uploader's official display name","__isVideoOwner":"Page","has_professional_features_for_watch":true ...
```
That can be grabbed by a regex (very crude and hacky), or by extracting the JSON and parsing it. Perhaps other modern meta-info is also embedded there.

P.S.: This is the regex. Works for me. Don't do this, JSON and HTML should never be parsed with regexes.
```
self._search_regex(r'"owner":{[^}]*"name":"([^"]+)"', webpage, 'uploader', default=None)
```
