### ISSUE TITLE
Site support request: Panopto

### ISSUE THREAD

**Issue by jxu** [yt-dlp/yt-dlp#1946]
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2021.12.01**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

US

### Example URLs

- Single video: https://ucc.cloud.panopto.eu/Panopto/Pages/Viewer.aspx?id=0e8484a4-4ceb-4d98-a63f-ac0200b455cb
- Playlist: https://ucc.cloud.panopto.eu/Panopto/Podcast/Podcast.ashx?courseid=361ccc29-dd09-422b-9a42-d666473ecdef&type=mp4

I have not tested these

### Description

(repost of upstream https://github.com/ytdl-org/youtube-dl/issues/22688) 

Institutional videos probably require cookies. Videos can be downloaded just from RSS playlist but may give lower quality, so needs to have index.m3u8 extractor

**Comment by pukkandan** [comment]
Related: https://github.com/ytdl-org/youtube-dl/pull/13449

**Comment by jxu** [comment]
For some reason cookies-from-browser firefox didn't load the right cookies, but a manually downloaded cookies.txt from firefox browser extension worked. I'm not sure how cookies extraction works but private videos require csrfToken and/or .ASPXAUTH cookies.

**Comment by coletdjnz** [comment]
> For some reason cookies-from-browser firefox didn't load the right cookies, but a manually downloaded cookies.txt from firefox browser extension worked. I'm not sure how cookies extraction works but private videos require csrfToken and/or .ASPXAUTH cookies.

Yeah, I noticed this too. 

The  .ASPXAUTH cookie seems to have an expires/max-age of `Session`. I think this means the cookie are deleted when the browser closes, i.e. it is not stored in the cookie database (and hence cookies from browser not grabbing them)? https://developer.mozilla.org/en-US/docs/Tools/Storage_Inspector/Cookies

**Comment by jxu** [comment]
I know next to nothing about cookies, but if that's the case then yt-dlp's cookie grabbing may need to be more thorough

**Comment by jxu** [comment]
Also as a bonus feature, are there ways to extract captions? I believe the videos downloaded from RSS (if available) have captions embedded. Not sure about the mp4 TS chunks.

**Comment by coletdjnz** [comment]
> Also as a bonus feature, are there ways to extract captions? I believe the videos downloaded from RSS (if available) have captions embedded. Not sure about the mp4 TS chunks.

Yeah I missed supporting captions in the original PR in some cases. #3009 fixes that, which I'm about to merge. Then you'll be able to use `--embed-subs` to embed them into the file.

Chapters are also supported, if that is of interest.

**Comment by coletdjnz** [comment]
> I know next to nothing about cookies, but if that's the case then yt-dlp's cookie grabbing may need to be more thorough

Even if we were able to extract session cookies, I think there would still be some issues if what I said above is true:
- the cookies will not exist when the browser is closed
- the cookies will only exist when you have logged in on your current browser session

cc @mbway

**Comment by jxu** [comment]
> Even if we were able to extract session cookies, I think there would still be some issues if what I said above is true:
> 
>     * the cookies will not exist when the browser is closed
> 
>     * the cookies will only exist when you have logged in on your current browser session
> 
> 
> cc @mbway

Well I assume people have the video open to get the link. The program could add a message saying "if importing from browser current session cookies, have browser session open". But that probably belongs in a separate issue about cookies.

**Comment by pukkandan** [comment]
Firefox doesn't write session cookies to disk, and I assume neither does chrome. So it is impossible for `--cookies-from-browser` to extract them

**Comment by jxu** [comment]
Ok. I looked at Chrome's handling a long time ago and a lot of internal details were stored in little SQLite databases that were readable.

**Comment by mbway** [comment]
I also think that session cookies are never written to disk by firefox. I did some investigation here: https://github.com/yt-dlp/yt-dlp/issues/550#issuecomment-885536983 and https://github.com/yt-dlp/yt-dlp/issues/550#issuecomment-885898751

**Comment by jxu** [comment]
Also how does yt-dlp determine the approximate video size? When I downloaded a video yesterday it estimated correctly 1 GB, but a different video today says ~280 GB which is way off the mark.

**Comment by jxu** [comment]
It appears fragment 1 is very large compared to all the other fragments. I converted it to TS and opened in VLC and it looks like it's the entire video put into 1 fragment so I'm not sure what the others are. index.m3u8 shows all approximately 2MB fragments like
```
#EXTINF:9.000000,
#EXT-X-BYTERANGE:2022384@2097728
fragmented.mp4
```

**Comment by mathew2214** [comment]
not working, please re-open.

**Comment by bashonly** [comment]
@mathew2214 please open a new "broken site support" issue with proper log

**Comment by pCoder3000** [comment]
still broken

**Comment by seproDev** [comment]
@pCoder3000 please open a new "broken site support" issue with proper log
