### ISSUE TITLE
[Site Request] Update Invidious section of the YT extractor to use new link element on videos.

### ISSUE THREAD

**Issue by syeopite** [yt-dlp/yt-dlp#195]
## Checklist

- [x] I'm reporting a site feature request
- [x] I've verified that I'm running yt-dlp version **2021.03.21**
- [x] I've searched the bugtracker for similar site feature requests including closed ones

## Description

Currently yt-dlp (and upstream) uses a list of invidious instances to handle all Invidious requests. This is time consuming to maintain and often requires manual updates like in #92. It really isn't ideal.

Last month ago Invidious [added a link element](https://github.com/iv-org/invidious/pull/1730) that refers to the youtube version in its video pages. Would it be possible to update the Invidious section of the youtube extractor to use this instead of the instance list?

**Comment by pukkandan** [comment]
For the time being, I am not removing the hard-coded list. The link element will act as a fallback for any new instances. To see the new extraction method in action, use `--force-generic`
