### ISSUE TITLE
Bug form asks to run 'yt-dlp -Uv' but it fails: yt-dlp: error: no such option: -U

### ISSUE THREAD

**Issue by yurivict** [yt-dlp/yt-dlp#1957]
### Checklist

- [X] I'm asking a question and not reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

It looks like the command needs to be updated?

**Comment by pukkandan** [comment]
No, the command is correct
