### ISSUE TITLE
[Feature request] Set metadata based on multiple fields

### ISSUE THREAD

**Issue by pukkandan** [yt-dlp/yt-dlp#196]
I'd like to be able to format the video title added as metadata. The title is just title but, for TV shows, I'd like to add series, episode_number, and season_number.

_Originally posted by @2ShedsJackson in https://github.com/yt-dlp/yt-dlp/issues/126#issuecomment-803409551_

**Comment by pukkandan** [comment]
@2ShedsJackson Now this can be done like:
```
--parse-metadata "%(series)s S%(season_number).2d E%(episode_number).3d %(title):%(title)"
```

**Comment by 2ShedsJackson** [comment]
> @2ShedsJackson Now this can be done like:
> 
> ```
> --parse-metadata "%(series)s S%(season_number).2d E%(episode_number).3d %(title):%(title)"
> ```

Shouldn't the syntax be similar to the file name output template? Why the extra periods?
`%(series)s S%(season_number)2d E%(episode_number)3d %(title):%(title)`
although the usual usage found on the net is
`%(series)s S%(season_number)02dE%(episode_number)02d %(title):%(title)`

The usage under Post-Processing Options help is lengthy and poorly worded. The help usage should be like the one for `-o`: It should briefly say what the option does then have a section in the readme to explain how the option works, with examples. regex usage should explicitly mention **Python** regex syntax. `(?P<artist>.+?)` doesn't make sense in most regex usage that doesn't have anything to do with Python, like with sed or grep. I can help rewrite the readme later.

Can the syntax be expanded to allow conditional output templates? For example, if `%(series)s%(season_number)s%(episode_number)s == 'NANANA'` then use the template `%(title)`

Btw, being able to specify the embedded title metadata comes in handy when directly downloading an m3u8 file. The resulting title is usually "master" or something cryptic based on the filename.

**Comment by pukkandan** [comment]
> Shouldn't the syntax be similar to the file name output template? Why the extra periods?
> `%(series)s S%(season_number)2d E%(episode_number)3d %(title):%(title)`
> although the usual usage found on the net is
> `%(series)s S%(season_number)02dE%(episode_number)02d %(title):%(title)`

Both are valid

> The usage under Post-Processing Options help is lengthy and poorly worded. The help usage should be like the one for `-o`: It should briefly say what the option does then have a section in the readme to explain how the option works, with examples.

A PR with improvements to the readme would be appreciated

> Can the syntax be expanded to allow conditional output templates? For example, if %(series)s%(season_number)s%(episode_number)s == 'NANANA' then use the template %(title)

Not directly. This is possible using some clever regex though. I had plans for adding conditional output templates, but I'm not sure how to implement it without making `-o` much more complex than it already is

**Comment by 2ShedsJackson** [comment]
> Not directly. This is possible using some clever regex though. I had plans for adding conditional output templates, but I'm not sure how to implement it without making `-o` much more complex than it already is

How about something like
condition:filetype:format
where filetype:format gets used only if the condition is True? Multiple uses of `-o` would add more conditions; a negated condition would provide the else case of a previous condition. Make the first use of `-o` without a condition become the default format and/or have a special condition that uses the string `default`.

Btw, since filetype:format is the current syntax, how do you insert a literal `:` in the format string?

**Comment by pukkandan** [comment]
> Btw, since filetype:format is the current syntax, how do you insert a literal : in the format string?

Only the valid keys are matched as the prefix. For example, `-o c:\video.ext` would work exactly as in youtube-dl

**Comment by 2ShedsJackson** [comment]
> Only the valid keys are matched as the prefix. For example, `-o c:\video.ext` would work exactly as in youtube-dl

So how would I specify a format to name a video `thumbnail: the end of the manicure`

**Comment by pukkandan** [comment]
`-o " thumbnail: the end of the manicure"` or `-o ".\thumbnail: the end of the manicure` both work
