### ISSUE TITLE
Format selection in MPV 

### ISSUE THREAD

**Issue by aeseok** [yt-dlp/yt-dlp#1960]
### Checklist

- [X] I'm asking a question and not reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

I'm looking for a way to specify stream quality in the MPV conf file like how youtube-dl used "--ytdl-format="bestvideo[height=1440]+bestaudio"/"bestvideo+bestaudio"" for format selection

**Comment by pukkandan** [comment]
You can do the same for yt-dlp. And, this question should be asked to mpv devs, not here
