### ISSUE TITLE
I am unable to download from Paramount Plus with yt-dlp.

### ISSUE THREAD

**Issue by sandrosg2018** [yt-dlp/yt-dlp#1963]
### Checklist

- [X] I'm asking a question and not reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

I wanted to know what command to download Paramount Plus?

**Comment by pukkandan** [comment]
yt-dlp URL

**Comment by sandrosg2018** [comment]
> yt-dlp URL

![Shot 0001](https://user-images.githubusercontent.com/95977674/145689797-22472e38-7bc6-4b6c-ad4c-c7dba7c398b0.jpg)

**Comment by sandrosg2018** [comment]
> yt-dlp URL

![Shot 0002](https://user-images.githubusercontent.com/95977674/145690008-f360aaf6-7a2d-4c5a-828b-764530d008d1.jpg)

**Comment by pukkandan** [comment]
Pass your cookies for authentication https://github.com/yt-dlp/yt-dlp#authentication-options
