### ISSUE TITLE
Rutube: Please add support for downloading all videos of a channel

### ISSUE THREAD

**Issue by mara004** [yt-dlp/yt-dlp#1966]
### Checklist

- [X] I'm reporting a site feature request
- [X] I've verified that I'm running yt-dlp version **2021.12.01**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Region

Worldwide (based in Russia)

### Example URLs

https://rutube.ru/channel/639184/videos/

### Description

I'd like to request support for downloading a whole channel on Rutube. This feature also exists for YouTube, so it would be nice if it could be implemented for Rutube, too. Copying all URLs manually is quite tedious for larger channels.
It would be best if downloading a channel could be done concurrently with multiple threads for improved performance.

**Comment by dirkf** [comment]
Rutube's `.../channel/{id}/` URLs replace the `.../person/{id}/video/` URLs, which redirect to them. Therefore `RutubePersonIE` cab be removed, or the extractors can be unified. The hint is in the identical `_PAGE_TEMPLATE`s.
