### ISSUE TITLE
audio stream download still throttled to about 130kB/s.

### ISSUE THREAD

**Issue by schmorp** [yt-dlp/yt-dlp#1967]
### Checklist

- [X] I'm reporting a feature request
- [X] I've verified that I'm running yt-dlp version **2021.12.01**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

I am downloading youtube videos mainly in formats 303 (webm) and 251 (opus).

Until the recent throttling workaround by decrypting the n-sig, both of these streams downloaded at about a constant rate 130kB/s.

With the current version, the video stream downloads fast (well, at least much faster, it still seems to be throttled at around 1MB/s sometimes), but the audio stream is still being throttled at the same 130kB/s as before, often making the audio stream download to be actually slower than the video stream download, despite it being much smaller.

Since the speed seems to be the same as with throttling, could it be that the audio stream also needs some signature decryption and yt-dlp does not yet do that, or is this a new/different throttling problem?

An example video id where this happens would be DhEcS_VNTzI, although it seems to happen with every video.

**Comment by pukkandan** [comment]
Show verbose log. If you are downloading a DASH format, then the slowdown is expected. Only way around it is to use `-N` or `--downloader aria2c`

**Comment by schmorp** [comment]
I tried hard to choose the correct template - what would the correct template have been, and how could I have decided better? How can I be expected to know that this is an "extractor bug" and not a missing feature? I think you set the bar for reporting too high.

yt-dlp does not list format 251 as dash format (but has 251-dash as dash format). -N12 does not make any difference, verbose log:

[debug] Command-line config: ['--sleep-requests', '0.5', '--sleep-subtitles', '1', '--no-write-playlist-metafiles', '--write-subs', '--write-auto-subs', '--throttled-rate', '50K', '--abort-on-unavailable-fragment', '--fragment-retries', '25', '--throttled-rate', '50K', '--socket-timeout', '10', '--sleep-interval', '1', '--add-metadata', '--cookies', '/home/user/.youtube-dl-cookies', '--force-ipv4', '--buffer-size', '1M', '--http-chunk-size', '16M', '--convert-subtitles', 'srt', '--embed-subs', '--sub-lang', 'en,de', '--embed-subs', '--merge-output-format', 'mkv', '--no-cache-dir', '-f', 'bestvideo[vcodec=vp9][height=1440]+bestaudio[acodec=opus]/bestvideo[vcodec=m4a][height=1440]+bestaudio[acodec=opus]/bestvideo[vcodec=vp9][height=1080]+bestaudio[acodec=opus]/bestvideo[vcodec=m4a][height=1080]+bestaudio[acodec=opus]/bestvideo[vcodec=vp9][height=720]+bestaudio[acodec=opus]/bestvideo[vcodec=m4a][height=720]+bestaudio[acodec=opus]/bestvideo[height<=?1080]+bestaudio/best[height<=?1080]/bestvideo+bestaudio/best', '-o', '%(uploader)s-%(title)s-%(upload_date)s-%(id)s.%(ext)s', '-i', '-c', '--download-archive', '/home/user/.ytd-archive', '--sponsorblock-mark', 'all', '--reject-title', 'atisfactory', '--add-metadata', '--write-info-json', '-v', 'yn1tBGKCIcg']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8 (No ANSI), err utf-8 (No ANSI), pref UTF-8
[debug] yt-dlp version 2021.12.01 [91f071af6] (zip)
[debug] Python version 3.9.2 (CPython 64bit) - Linux-5.10.0-9-amd64-x86_64-with-glibc2.31
[debug] exe versions: ffmpeg 4.4 (fdk,setts), ffprobe 4.4, phantomjs 2.1.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Loading archive file '/home/user/.ytd-archive'
[debug] [youtube] Extracting URL: yn1tBGKCIcg
[youtube] yn1tBGKCIcg: Downloading webpage
[youtube] Sleeping 0.5 seconds ...
[youtube] yn1tBGKCIcg: Downloading android player API JSON
[youtube] Sleeping 0.5 seconds ...
[youtube] yn1tBGKCIcg: Downloading player dc05ba20
[debug] [youtube] Decrypted nsig Tr34ml-wy_-FGE => nPylSxbcVkQOIQ
[youtube] Sleeping 0.5 seconds ...
[youtube] yn1tBGKCIcg: Downloading MPD manifest
[youtube] Sleeping 0.5 seconds ...
[youtube] yn1tBGKCIcg: Downloading MPD manifest
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[debug] Downloading subtitles: en, de
[SponsorBlock] Fetching SponsorBlock segments
[debug] SponsorBlock query: https://sponsor.ajay.app/api/skipSegments/01c1?service=YouTube&categories=%5B%22sponsor%22%2C+%22intro%22%2C+%22interaction%22%2C+%22music_offtopic%22%2C+%22preview%22%2C+%22outro%22%2C+%22selfpromo%22%5D
[SponsorBlock] No segments were found in the SponsorBlock database
[info] yn1tBGKCIcg: Downloading 1 format(s): 303+251
[info] Writing video subtitles to: Sinatar-Eye of the Beholder II - Legend of Darkmoor (DOS) - Finale!-20211211-yn1tBGKCIcg.en.vtt
[debug] Invoking downloader on "https://www.youtube.com/api/timedtext?v=yn1tBGKCIcg&asr_langs=de%2Cen%2Ces%2Cfr%2Cid%2Cit%2Cja%2Cko%2Cnl%2Cpt%2Cru%2Ctr%2Cvi&caps=asr&exp=xftt%2Cxctw&xoaf=5&hl=en&ip=0.0.0.0&ipbits=0&expire=1639351071&sparams=ip%2Cipbits%2Cexpire%2Cv%2Casr_langs%2Ccaps%2Cexp%2Cxoaf&signature=60157298AC02FB0EFE8F19186F28B3326E678834.B85895912D233641886F570715CAEAD7C12237CE&key=yt8&kind=asr&lang=en&tlang=en&fmt=vtt"
[download] Sleeping 1 seconds ...
[download] Unable to resume
[download] Destination: Sinatar-Eye of the Beholder II - Legend of Darkmoor (DOS) - Finale!-20211211-yn1tBGKCIcg.en.vtt
[download] 100% of 886.10KiB in 00:00
[info] Writing video subtitles to: Sinatar-Eye of the Beholder II - Legend of Darkmoor (DOS) - Finale!-20211211-yn1tBGKCIcg.de.vtt
[debug] Invoking downloader on "https://www.youtube.com/api/timedtext?v=yn1tBGKCIcg&asr_langs=de%2Cen%2Ces%2Cfr%2Cid%2Cit%2Cja%2Cko%2Cnl%2Cpt%2Cru%2Ctr%2Cvi&caps=asr&exp=xftt%2Cxctw&xoaf=5&hl=en&ip=0.0.0.0&ipbits=0&expire=1639351071&sparams=ip%2Cipbits%2Cexpire%2Cv%2Casr_langs%2Ccaps%2Cexp%2Cxoaf&signature=60157298AC02FB0EFE8F19186F28B3326E678834.B85895912D233641886F570715CAEAD7C12237CE&key=yt8&kind=asr&lang=en&tlang=de&fmt=vtt"
[download] Sleeping 1 seconds ...
[download] Unable to resume
[download] Destination: Sinatar-Eye of the Beholder II - Legend of Darkmoor (DOS) - Finale!-20211211-yn1tBGKCIcg.de.vtt
[download] 100% of 835.03KiB in 00:00
[info] Writing video metadata as JSON to: Sinatar-Eye of the Beholder II - Legend of Darkmoor (DOS) - Finale!-20211211-yn1tBGKCIcg.info.json
[SubtitlesConvertor] Converting subtitles
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:Sinatar-Eye of the Beholder II - Legend of Darkmoor (DOS) - Finale!-20211211-yn1tBGKCIcg.en.vtt' -f srt 'file:Sinatar-Eye of the Beholder II - Legend of Darkmoor (DOS) - Finale!-20211211-yn1tBGKCIcg.en.srt'
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:Sinatar-Eye of the Beholder II - Legend of Darkmoor (DOS) - Finale!-20211211-yn1tBGKCIcg.de.vtt' -f srt 'file:Sinatar-Eye of the Beholder II - Legend of Darkmoor (DOS) - Finale!-20211211-yn1tBGKCIcg.de.srt'
Deleting original file Sinatar-Eye of the Beholder II - Legend of Darkmoor (DOS) - Finale!-20211211-yn1tBGKCIcg.de.vtt (pass -k to keep)
Deleting original file Sinatar-Eye of the Beholder II - Legend of Darkmoor (DOS) - Finale!-20211211-yn1tBGKCIcg.en.vtt (pass -k to keep)
[debug] Invoking downloader on "https://manifest.googlevideo.com/api/manifest/dash/expire/1639347471/ei/ryC2YcndD6SCmQbS_Z2QBw/ip/37.49.68.13/id/ca7d6d04628221c8/source/youtube/requiressl/yes/playback_host/r2---sn-h0jeenle.googlevideo.com/mh/EB/mm/31%2C29/mn/sn-h0jeenle%2Csn-h0jelnes/ms/au%2Crdu/mv/m/mvi/2/pl/22/hfr/all/as/fmp4_audio_clear%2Cwebm_audio_clear%2Cwebm2_audio_clear%2Cfmp4_sd_hd_clear%2Cwebm2_sd_hd_clear/initcwndbps/1836250/vprv/1/mt/1639325574/fvip/2/keepalive/yes/fexp/24001373%2C24007246/itag/0/sparams/expire%2Cei%2Cip%2Cid%2Csource%2Crequiressl%2Chfr%2Cas%2Cvprv%2Citag/sig/AOq0QJ8wRgIhALuHNqHkT38ucKGa41V-uhGf1J5c3qCA8rwf2bkOLjODAiEA_kP1P-P7SJf_qk-SZBoVv75V8EWgCaWqhNUVVSrlFgI%3D/lsparams/playback_host%2Cmh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps/lsig/AG3C_xAwRQIgNq8fEUSgJSQr_BCArvArlKZGmOhIIW01goy1nfvWmJ8CIQCc5tjOb9qKFP51_o6xhDPFthmDOBQI5b7cgoDAkdYnpQ%3D%3D"
[download] Sinatar-Eye of the Beholder II - Legend of Darkmoor (DOS) - Finale!-20211211-yn1tBGKCIcg.f303.webm has already been downloaded
[download] 100% of 3.29GiB[debug] Invoking downloader on "https://rr2---sn-h0jelnes.googlevideo.com/videoplayback?expire=1639347472&ei=sCC2YbLyFsuc8gOxw7uQAg&ip=37.49.68.13&id=o-ALjQIr4IFjHqGFhFnqZwNznlUGA3LPRM4D5VTCgEvKg2&itag=251&source=youtube&requiressl=yes&mh=EB&mm=31%2C26&mn=sn-h0jelnes%2Csn-4g5ednsk&ms=au%2Conr&mv=m&mvi=2&pl=22&initcwndbps=1811250&vprv=1&mime=audio%2Fwebm&gir=yes&clen=369598118&otfp=1&dur=23063.021&lmt=1639220713592175&mt=1639325574&fvip=2&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=6211224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cotfp%2Cdur%2Clmt&sig=AOq0QJ8wRQIgIBVc42CiIhtWSK20KMoAuG7RTtY7vEb6BOpf6YAuKjsCIQC5pyQZGMw-COUE1xuKFHRS1taFTbF8x38UAIJ5xXQ8ZA%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAI69bWQs6OxTQeazbozu5NDsZXzZzI1Tr6ZlOvN0SjRZAiEAlfXXVBAfXhL5ZTlMuP5rq1FIJ7AVZllrAjqkUQkoDLo%3D"
[download] Sleeping 1 seconds ...
[download] Resuming download at byte 3145728
[download] Destination: Sinatar-Eye of the Beholder II - Legend of Darkmoor (DOS) - Finale!-20211211-yn1tBGKCIcg.f251.webm
[download]   2.7% of 352.48MiB at 137.90KiB/s ETA 42:25

**Comment by pukkandan** [comment]
> and how could I have decided better? How can I be expected to know that this is an "extractor bug" and not a missing feature?

You are reporting that youtube downloads (which is something that is expected to work) isnt working properly. I'd assume most people would consider this either a bug or an extractor-bug. I don't understand why you though it is an enhancement.

Anyway, no matter. The main difference in the template between the two is that you are not expected to provide verbose logs for enhancements. But for debugging bugs, they are essential. The template exist to avoid that step in between that I have to ask for the log. Now that you have provided the log, the template isn't too important

---

Try removing `--http-chunk-size 12M` and let me know whether it solves the issue. Youtube is known to throttle some downloads with chunksize > 10M.

```
➤ yt-dlp yn1tBGKCIcg -f251
[youtube] yn1tBGKCIcg: Downloading webpage
[youtube] yn1tBGKCIcg: Downloading android player API JSON
[youtube] yn1tBGKCIcg: Downloading player dc05ba20
[youtube] yn1tBGKCIcg: Downloading MPD manifest
[youtube] yn1tBGKCIcg: Downloading MPD manifest
[info] yn1tBGKCIcg: Downloading 1 format(s): 251
[download] Destination: Eye of the Beholder II - Legend of Darkmoor (DOS) - Finale! [yn1tBGKCIcg].webm
[download]   1.1% of 352.48MiB at  2.69MiB/s ETA 02:09
ERROR: Interrupted by user

➤ yt-dlp yn1tBGKCIcg -f251 --http-chunk-size 12M
[youtube] yn1tBGKCIcg: Downloading webpage
[youtube] yn1tBGKCIcg: Downloading android player API JSON
[youtube] yn1tBGKCIcg: Downloading MPD manifest
[youtube] yn1tBGKCIcg: Downloading MPD manifest
[info] yn1tBGKCIcg: Downloading 1 format(s): 251
[download] Resuming download at byte 4193280
[download] Destination: Eye of the Beholder II - Legend of Darkmoor (DOS) - Finale! [yn1tBGKCIcg].webm
[download]   1.6% of 352.48MiB at 117.66KiB/s ETA 50:18
ERROR: Interrupted by user
```

**Comment by dimitarvp** [comment]
Apologies if this is only adding noise -- just wanted to add my voice here to report the same.

I use aria2c with 16 concurrent connections and all my videos download at no less than 15 MB/s, but audio streams are always at 2-3 MB/s so it seems that maybe YouTube introduces hard cap on download on those, say 5x - 8x less than the maximum speed for videos.

What I am saying is, this might not be unfixable because I've been observing it for several weeks now and it's universal. Haven't noticed a single exception to this (seeming) rule.

**Comment by PacoH** [comment]
I am having the same slow-down problem with audio and video with `yt-dlp 2021.12.1`. `aria2c` and `axel` actually further slowed down the download. Throttling I guess. I didn't know about `-N, --concurrent-fragments N` or `--http-chunk-size`. I tried different combinations on a slow Youtube video––https://www.youtube.com/watch?v=E_ZXUvNPm5I.

Results using `-f "bestvideo[ext=webm]+bestaudio[ext=webm]/bestvideo+bestaudio/best"` `webm` output:

    Raw
    00h03m09s
    --concurrent-fragments 20 --http-chunk-size 20M
    00h04m59s
    --http-chunk-size 10M
    00h03m09s
    --concurrent-fragments 20 --http-chunk-size 10M
    00h00m48s
    --concurrent-fragments 10
    00h00m48s
    --concurrent-fragments 20
    00h00m48s

 So now I use `--concurrent-fragments 20`. It's amazing to see the fragment count whizz on by. This also works on non-Youtube sites.

 Thanks for the suggestions.

**Comment by pukkandan** [comment]
You do not need to change `--http-chunk-size`. However, **if** you change it, make sure it is under 10M

**Comment by PacoH** [comment]
yt-dlp man page:

    --http-chunk-size SIZE           Size of a chunk for chunk-based HTTP
                                                   downloading (e.g. 10485760 or 10M) (default
                                                   is disabled). May be useful for bypassing
                                                   bandwidth throttling imposed by a webserver
                                                   (experimental)

Where'd you get the 'under 10M' rule? I don't see it documented.

For above-mentioned Youtube video:

| Option                 | Time      |
|------------------------|-----------|
| none                   | 00h03m09s |
| \-\-http-chunk-size      |           |
| 1M                     | 00h03m52s |
| 5M                     | 00h03m12s |
| 10M                    | 00h07m25s |
| \-\-concurrent-fragments |           |
| 10                     | 00h00m48s |
| 20                     | 00h00m48s |
| 40                     | 00h00m48s |

Given that even a 1M chunk-size makes no difference, it would be better to avoid `--http-chunk-size` altogether. Using `--concurrent-fragments` over a broad range of values (10-40) reduces time from over 3 minutes to under one minute no matter which value is chosen. That's quite a speedup. So far this works consistently only for Youtube videos. Ones from other sources vary.

**Comment by pukkandan** [comment]
> Where'd you get the 'under 10M' rule? I don't see it documented.

> Youtube is known to throttle some downloads with chunksize > 10M.

**Comment by PacoH** [comment]
Hmmm… Where is that documented?

**Comment by pukkandan** [comment]
Ask youtube. It is just something we have observed about youtube. Why would it be documented in our docs!?

**Comment by ClosedPort22** [comment]
You could try using `--extractor-args youtube:player_client=web`. This works for me. I read somewhere that Android and iOS clients weren't affected by the `nsig` throttling, and since by default yt-dlp uses both `web` and `android`, I'm guessing that YouTube is starting to throttle Android clients as well. With the above parameters, I'm seeing two `[youtube] Decrypted nsig` lines instead of one in the log.
