### ISSUE TITLE
miomio.info japanese variety show website

### ISSUE THREAD

**Issue by THEWOKE** [yt-dlp/yt-dlp#1971]
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2021.12.01**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Australia

### Example URLs

Playlist: https://play.ninetyvieoprogood.xyz/player/6178055add75dfb79eb189f3/playlist.m3u8

### Description

Can there please be support for this website? 

Whenever I try to download the m3u8 playlist from this website, I get WARNING: [generic] Falling back on generic information extractor meaning that yt-dlp does not support it

### Verbose log

```shell
[debug] Command-line config: ['-F', '-v', 'https://play.ninetyvieoprogood.xyz/player/6178055add75dfb79eb189f3/playlist.m3u8']
[debug] Encodings: locale cp932, fs utf-8, out utf-8, err utf-8, pref cp932
[debug] yt-dlp version 2021.12.01 [91f071a] (win_dir)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] exe versions: ffmpeg git-2020-08-14-a762fd2, ffprobe git-2020-08-14-a762fd2
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [generic] Extracting URL: https://play.ninetyvieoprogood.xyz/player/6178055add75dfb79eb189f3/playlist.m3u8
[generic] playlist: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] playlist: Downloading webpage
[debug] Identified a M3U playlist
[generic] playlist: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[info] Available formats for playlist:
ID EXT RESOLUTION │ PROTO  │ VCODEC  ACODEC
─────────────────────────────────────────────
0  mp4 unknown    │ m3u8_n │ unknown unknown
```

**Comment by Ashish0804** [comment]
provide url of the video itself, not the manifest

**Comment by nao20010128nao** [comment]
yt-dlp should fallback to ok.ru when you have provided url of the video page (as Ashish says). Also, it's piracy website.

```
$ ytdl -s https://miomio.info/[redacted].html
[generic] [redacted]: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] [redacted]: Downloading webpage
[generic] [redacted]: Extracting information
[Odnoklassniki] [redacted]: Downloading desktop webpage
[Odnoklassniki] [redacted]: Downloading m3u8 information
[info] [redacted]: Downloading 1 format(s): mpd-5
```
