### ISSUE TITLE
[Viki] Changing audio language metadata and removing tags

### ISSUE THREAD

**Issue by Sparh4wk** [yt-dlp/yt-dlp#1973]
### Checklist

- [X] I'm asking a question and not reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

Hi,

is there a way to change metadata for audio track and removing tags?

Im using command like this for dl from viki. 

yt-dlp "xxx" --merge-output-format mkv --sub-lang en --sub-lang cs --sub-format srt --write-sub --embed-subs --username "xxx" --password "xxx"

But its always like this:

![image](https://user-images.githubusercontent.com/7014826/145707261-ba995f64-1787-4e93-a40d-812ba9d6104b.png)

and I would like to change audio to ko/zh depending of show and removing all those tags and global tags.

**Comment by pukkandan** [comment]
Show verbose output. You say you are not using `--embed-metadata` in which case there should be no metadata attached by yt-dlp to the file

**Comment by Sparh4wk** [comment]
`yt-dlp "https://www.viki.com/videos/1188518v-school-2021-special-episode-1" --merge-output-format mkv --sub-lang en --sub-lang cs --sub-format srt --write-sub --embed-subs --verbose
[debug] Command-line config: ['https://www.viki.com/videos/1188518v-school-2021-special-episode-1', '--merge-output-format', 'mkv', '--sub-lang', 'en', '--sub-lang', 'cs', '--sub-format', 'srt', '--write-sub', '--embed-subs', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8[debug] yt-dlp version 2021.10.22 (zip)
[debug] Python version 3.9.9 (CPython 64bit) - Linux-5.10.84-1-lts-x86_64-with-glibc2.33
[debug] exe versions: ffmpeg 4.4.1, ffprobe 4.4.1
[debug] Optional libraries: Crypto, keyring, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [viki] Extracting URL: https://www.viki.com/videos/1188518v-school-2021-special-episode-1
[viki] 1188518v: Downloading video JSON
[viki] 1188518v: Downloading video streams JSON
[viki] 1188518v: Downloading initial MPD manifest
[viki] 1188518v: Downloading MPD manifest
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Downloading subtitles: en
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 1188518v: Downloading 1 format(s): 0+9
[info] Writing video subtitles to: Special [1188518v].en.srt
[debug] Invoking downloader on "https://api.viki.io/v4/videos/1188518v/auth_subtitles/en.srt?app=100005a&stream_id=107703126"
[download] Destination: Special [1188518v].en.srt
[download] 100% of 85.85KiB in 00:00
[debug] Invoking downloader on "https://m-content6-viki.s.llnwi.net/1188518v/dash/1188518v_dash_high_1080p_eb02c8_2112011204_track1_dashinit.mp4"
[download] Destination: Special [1188518v].f0.mp4
[download] 100% of 1.32GiB in 00:26
[debug] Invoking downloader on "https://m-content6-viki.s.llnwi.net/1188518v/dash/1188518v_dash_high_720p_a2d755_2112011004_track2_dashinit.mp4"
[download] Destination: Special [1188518v].f9.m4a
[download] 100% of 81.45MiB in 00:01
[Merger] Merging formats into "Special [1188518v].mkv"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:Special [1188518v].f0.mp4' -i 'file:Special [1188518v].f9.m4a' -c copy -map 0:v:0 -map 1:a:0 'file:Special [1188518v].temp.mkv'
Deleting original file Special [1188518v].f9.m4a (pass -k to keep)
Deleting original file Special [1188518v].f0.mp4 (pass -k to keep)
[debug] ffprobe command line: ffprobe -hide_banner -show_format -show_streams -print_format json 'file:Special [1188518v].mkv'
[EmbedSubtitle] Embedding subtitles in "Special [1188518v].mkv"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:Special [1188518v].mkv' -i 'file:Special [1188518v].en.srt' -c copy -map 0 -dn -map -0:s -map -0:d -map 1:0 -metadata:s:s:0 language=eng 'file:Special [1188518v].temp.mkv'`

**Comment by pukkandan** [comment]
You can see the only the subtitle language `-metadata:s:s:0 language=eng` is set by yt-dlp. Idk what the other "tags" shown in the OP are. You can use `--ppa` or `--exec` to set custom metadata. It can also be done with `--embed-metadata`, but since you don't want any of the standard metadata, that is not worth it

Eg (untested):

```
--ppa "EmbedSubtitle:-metadata:s:a:0 language=ko"
```
