### ISSUE TITLE
Why is yt-dlp so slow?

### ISSUE THREAD

**Issue by u-spec-png** [yt-dlp/yt-dlp#1978]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2021.12.01**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

I usually wait 10-20s between requests.

https://user-images.githubusercontent.com/54671367/145724249-e0cdff2a-4f2c-4ddb-b2cb-b0d7d0b7e881.mp4

### Verbose log

```shell
$ yt-dlp -v https://youtu.be/0e3GPea1Tyg                               
[debug] Command-line config: ['-v', 'https://youtu.be/0e3GPea1Tyg']
[debug] User config file: /home/pogaca/.config/yt-dlp/config
[debug] User config: ['-f', 'mkv', '-f', 'bestvideo[height<=1080]+bestaudio/best/standard', '-o', '~/Downloads/%(title).200s - %(id)s.%(ext)s']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2021.12.01 [91f071af6]
[debug] Lazy loading extractors is disabled
[debug] Python version 3.9.9 (CPython 64bit) - Linux-5.15.7-arch1-1-x86_64-with-glibc2.33
[debug] exe versions: ffmpeg 4.4.1 (setts), ffprobe 4.4.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [youtube] Extracting URL: https://youtu.be/0e3GPea1Tyg
[youtube] 0e3GPea1Tyg: Downloading webpage
[youtube] 0e3GPea1Tyg: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[info] 0e3GPea1Tyg: Downloading 1 format(s): 248+251
[download] /home/pogaca/Downloads/$456,000 Squid Game In Real Life! - 0e3GPea1Tyg.webm has already been downloaded
```

**Comment by pukkandan** [comment]
No idea. Is it just for youtube? Possibly network issue. But even so, the socket should timeout if a request takes more than 20secs. See if `--print-traffic` gives any clue


https://user-images.githubusercontent.com/6623388/145724835-12384af3-c6c0-468c-ba63-50f1fad746f9.mp4

**Comment by u-spec-png** [comment]
It was a network. Seems like disabling IPV6 fixed a problem (idk why).
