### ISSUE TITLE
Crashes on launch

### ISSUE THREAD

**Issue by Hergeirs** [yt-dlp/yt-dlp#1991]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2021.12.01**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

Running on archlinux.
installed version yt-dlp-2021.12.01-2 through AUR.

Running yt-dlp throws an exception.
```
$ yt-dlp --version
Traceback (most recent call last):
  File "/usr/bin/yt-dlp", line 33, in <module>
    sys.exit(load_entry_point('yt-dlp==2021.11.10.1', 'console_scripts', 'yt-dlp')())
  File "/usr/bin/yt-dlp", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib/python3.9/importlib/metadata.py", line 524, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.9/importlib/metadata.py", line 187, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: yt-dlp
```

I really don't know what else to include in the bug report.
I'll give all info I can provide.

### Verbose log

```shell
$ yt-dlp -Uv --version                                                            
Traceback (most recent call last):
  File "/usr/bin/yt-dlp", line 33, in <module>
    sys.exit(load_entry_point('yt-dlp==2021.11.10.1', 'console_scripts', 'yt-dlp')())
  File "/usr/bin/yt-dlp", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib/python3.9/importlib/metadata.py", line 524, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.9/importlib/metadata.py", line 187, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: yt-dlp
```

**Comment by Ashish0804** [comment]
AUR is not official
Use methods listed here https://github.com/yt-dlp/yt-dlp#installation

**Comment by pukkandan** [comment]
looks like an issue with the package. Since AUR package isnt made by us, nothing we can do. Report it to the people who packaged it

**Comment by pukkandan** [comment]
Actually, it seems like an issue with the versioning. https://github.com/yt-dlp/yt-dlp/commit/a804f6d89c233fa90ee64e84778b151909baa554 should fix this for the next release

**Comment by Hergeirs** [comment]
Nice. Thank you for the quick turnaround +1:

**Comment by PotionsYT** [comment]
How did you fix this. Because its not fixing for me
The program just crashes

**Comment by Hergeirs** [comment]
I just updated yt-dlp. 
I'm using ```paru``` as my AUR helper on archlinux, so it was as simple as running ```paru -Syu yt-dlp``` on my system.
