### ISSUE TITLE
Know which postprocessor has finished through postprocessor hook 

### ISSUE THREAD

**Issue by JVT038** [yt-dlp/yt-dlp#1993]
### Checklist

- [X] I'm asking a question and not reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

Hi,
I want to keep track which post processor has finished processing.
I've seen the `[ModifyChapters]` and `[ExtractAudio]` prefixes in the command line, when using the CLI of yt-dlp, but I'm trying to embed yt-dlp in my own python program and I want to know when a post processor has finished.
When printing the `postprocessor` key ([here](https://github.com/yt-dlp/yt-dlp/blob/master/yt_dlp/YoutubeDL.py#L380)), it only prints 'MoveFiles', so that doesn't really help.
Is there a way for me to keep track of the post processors when embedding yt-dlp?

**Comment by pukkandan** [comment]
`MoveFiles` is a PP that always runs. Maybe you are not using any other PPs. Show your code

**Comment by JVT038** [comment]
```
{
    'format': 'ba', 
    'postprocessors': [
        {
        'key': 'FFmpegExtractAudio', 
        'preferredcodec': 'mp3', 
        'preferredquality': '192'
        },
        {
            'key': 'ModifyChapters', 
            'remove_ranges': [
                (197, 209), (242, 272), (260, 272)
            ]
        }
    ], 
    'postprocessor_args': {}, 
    'ffmpeg_location': '/usr/bin', 
    'progress_hooks': [<function YouTube.download_hook at 0x0000012E92C8BDC0>], 
    'postprocessor_hooks': [<function YouTube.postprocessor_hook at 0x0000012E92C8BE50>], 
    'logger': <Logger default (DEBUG)>, 
    'outtmpl': 'downloads\\%(title)s.%(ext)s', 
    'noplaylist': True, 
    'verbose': True
}
```

**Comment by pukkandan** [comment]
Can confirm it is a bug
