### ISSUE TITLE
Video file last modified date is equal to the date of video upload in windows

### ISSUE THREAD

**Issue by antsareflying** [yt-dlp/yt-dlp#1997]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2021.12.01**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

This occurs for all video files that I've downloaded. According to properties, the file created date is correct but file last modified date is the upload date of the video, so file created date is more recent than file last modified date. Below is the ls output. All the other files, such as subs, pics and description files are all correct in their date.

### Verbose log

```shell
PS C:\Users\seong\archive\public\videos\3Blue1Brown - Videos\20211023-A few of the best math explainers from this summer> ls


    Directory: C:\Users\seong\archive\public\videos\3Blue1Brown - Videos\20211023-A few of the best math explainers
    from this summer


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----        14/12/2021  08:40 PM           3952 20211023-A few of the best math explainers from this
                                                  summer-F3Qixy-r_rQ.description
-a----        14/12/2021  08:40 PM         790125 20211023-A few of the best math explainers from this
                                                  summer-F3Qixy-r_rQ.info.json
-a----        24/10/2021  08:12 AM       86997704 20211023-A few of the best math explainers from this
                                                  summer-F3Qixy-r_rQ.mkv
-a----        14/12/2021  08:40 PM          44600 20211023-A few of the best math explainers from this
                                                  summer-F3Qixy-r_rQ.webp
```

**Comment by pukkandan** [comment]
This is the expected behavior. Use `--no-mtime`
