### ISSUE TITLE
[Broken] Age verification issues - can't download video.

### ISSUE THREAD

**Issue by fosam** [yt-dlp/yt-dlp#200]
## Checklist

- [x] I'm reporting a broken site support
- [X] I've verified that I'm running yt-dlp version **2021.03.24.1**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar issues including closed ones

## Verbose log

<pre>
yt-dlp --verbose https://www.youtube.com/watch?v=rR8s72aouNE
[debug] Command-line config: ['--verbose', 'https://www.youtube.com/watch?v=rR8s72aouNE']
[debug] Loading archive file None
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] yt-dlp version 2021.03.24.1 (exe)
[debug] Python version 3.8.8 (CPython 64bit) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg 2021-03-24-git-a77beea6c8-full_build, ffprobe 2021-03-24-git-a77beea6c8-full_build
[debug] Proxy map: {}
[youtube] rR8s72aouNE: Downloading webpage
[youtube] rR8s72aouNE: Refetching age-gated info webpage
<b>ERROR: Sign in to confirm your age
This video may be inappropriate for some users.</b>
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1026, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1047, in __extract_info
  File "yt_dlp\extractor\common.py", line 558, in extract
  File "yt_dlp\extractor\youtube.py", line 1991, in _real_extract
yt_dlp.utils.ExtractorError: Sign in to confirm your age
This video may be inappropriate for some users.
</pre>

## Description

Hello @pukkandan and thanks for this fork!

I tried to download a video and i got some age verification errors as you can see in the Verbose log above.
<br />

When i tried to use `--cookies` then i got the error below:

<pre>
yt-dlp --cookies C:/Users/account/Desktop/cookies.txt --verbose https://www.youtube.com/watch?v=rR8s72aouNE
[debug] Command-line config: ['--cookies', 'C:/Users/account/Desktop/cookies.txt', '--verbose', 'https://www.youtube.com/watch?v=rR8s72aouNE']
[debug] Loading archive file None
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] yt-dlp version 2021.03.24.1 (exe)
[debug] Python version 3.8.8 (CPython 64bit) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg 2021-03-24-git-a77beea6c8-full_build, ffprobe 2021-03-24-git-a77beea6c8-full_build
[debug] Proxy map: {}
[youtube] rR8s72aouNE: Downloading webpage
<b>ERROR: Verify your age
Complete a brief check to show you're old enough to watch this video. Learn more</b>
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1026, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1047, in __extract_info
  File "yt_dlp\extractor\common.py", line 558, in extract
  File "yt_dlp\extractor\youtube.py", line 1991, in _real_extract
yt_dlp.utils.ExtractorError: Verify your age
Complete a brief check to show you're old enough to watch this video. Learn more
</pre>

I'm signed in to my account and i verified that the cookies are not expired. and of course my date of birth is over 18 years.

I tried youtube-dl as well, but it's the same issue there too.

What is wrong? please help..

Thank you very much.

**Comment by pukkandan** [comment]
I can't reproduce.

* Can you play the video in browser? If so, do you get that popup first? What is the URL shown in browser after it has started playing?
* Also, add a `--write-pages` to the command and give me the `.dump` file(s) that are generated.

**Comment by fosam** [comment]
- No, i can't play it in the browser, it still asking for the age verification there too:

![Capture 28_03_2021_19_55_29](https://user-images.githubusercontent.com/52612348/112764179-a9a0f180-9007-11eb-9f6d-2013f8a857d7.png)

- I got the dump files, how can i proceed with these?

**Comment by pukkandan** [comment]
If you cant play it in browser, I can't do anything. You'll need to verify in browser and export the cookies

**Comment by october262** [comment]
> * No, i can't play it in the browser, it still asking for the age verification there too:
> 
> ![Capture 28_03_2021_19_55_29](https://user-images.githubusercontent.com/52612348/112764179-a9a0f180-9007-11eb-9f6d-2013f8a857d7.png)
> 
> * I got the dump files, how can i proceed with these?

try clearing your browser cookies for youtube.
close down / restart you browser and sign back in to youtube
and then retry downloading the video with your cookies file.

**Comment by fosam** [comment]
@october262 unfortunately did not work, there is an age-restriction in the EU region 😠

I just tried now with a vpn and i was able to play the video in the browser, but when i tried to download the video it failed due to the error in the first verbose log, then i exported the `--cookies` and tried again (while still on vpn) and i'm able to download, but almost not worth it as the download speed is extremely slow. (maybe the vpn, but i'm not sure).

My main goal was to use `dlp` to work-around the age-gated webpage to be able to download, but this did not work, and when i provided the cookies i got pushed even deeper down the hole by asking me to verify, now it is impossible to download some age-gated videos without vpn+`--cookies`

Maybe i'll create an issue @.**youtube-dl** too and see if somebody can figure something out.
