### ISSUE TITLE
PlutoTV Unsupported URL

### ISSUE THREAD

**Issue by rgabbo** [yt-dlp/yt-dlp#2007]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2021.12.01**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Italy

### Description

If I try to download this video https://pluto.tv/it/on-demand/movies/love-always-santa-it-2015-1-1 I get "Unsupported URL". Video is not DRM protected.

### Verbose log

```shell
[debug] Command-line config: ['-Uv', 'https://pluto.tv/it/on-demand/movies/love-always-santa-it-2015-1-1']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2021.12.01 [91f071a] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.18363-SP0
[debug] exe versions: ffmpeg 4.4.1-essentials_build-www.gyan.dev (setts), ffprobe 4.4.1-essentials_build-www.gyan.dev
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2021.12.01, Current version: 2021.12.01
yt-dlp is up to date (2021.12.01)
[debug] [generic] Extracting URL: https://pluto.tv/it/on-demand/movies/love-always-santa-it-2015-1-1
[generic] love-always-santa-it-2015-1-1: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] love-always-santa-it-2015-1-1: Downloading webpage
[generic] love-always-santa-it-2015-1-1: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://pluto.tv/it/on-demand/movies/love-always-santa-it-2015-1-1
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1329, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1398, in __extract_info
  File "yt_dlp\extractor\common.py", line 597, in extract
  File "yt_dlp\extractor\generic.py", line 3813, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://pluto.tv/it/on-demand/movies/love-always-santa-it-2015-1-1
```

**Comment by pukkandan** [comment]
Workaround: try pluto.tv/en/on-demand/movies/love-always-santa-it-2015-1-1

**Comment by edudiego** [comment]
I have the very same issue.

- [ ] I'm running version 2021.12.17

This is the URL: https://pluto.tv/en/on-demand/series/my-strange-addiction-br/season/3/episode/dating-my-car-baby-powder-addict-2011-3-3-ptv2
