### ISSUE TITLE
[DiscoveryPlus]Add support for Discovery+ India

### ISSUE THREAD

**Issue by Ashish0804** [yt-dlp/yt-dlp#201]
## Checklist

- [x] I'm reporting a new site support request
- [x] I've verified that I'm running yt-dlp version **2021.03.24.1**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that none of provided URLs violate any copyrights
- [x] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

- Single video: https://www.discoveryplus.in/videos/how-do-they-do-it/fugu-and-more?seasonId=8&type=EPISODE
- Single video: https://www.discoveryplus.in/videos/how-do-they-do-it/fugu-and-more?seasonId=8&type=EPISODE
- Playlist: https://www.discoveryplus.in/show/how-do-they-do-it

## Description

https://www.discoveryplus.in/ is the streaming site for Discovery channel content in India. It has a mix of both free (not needing an account) and paid videos (needing a sub).

I can confirm atleast the free videos don't have any drm.

**Comment by pukkandan** [comment]
Cant access. Are you sure the example given is free? 
![image](https://user-images.githubusercontent.com/6623388/113120689-793b9c00-922f-11eb-8b4f-f830e8e81924.png)

**Comment by Ashish0804** [comment]
Works for me mate. I am using a delhi IP, if that matters somehow.
![image](https://user-images.githubusercontent.com/39122144/113122349-2a8f0180-9231-11eb-8dc0-76c049cfe480.png)
