### ISSUE TITLE
Downloading Videos from ITV Hub - "HTTP Error 404: Not Found"

### ISSUE THREAD

**Issue by skong24** [yt-dlp/yt-dlp#2011]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2021.12.01**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

Hi!

I have used TV Downloader in the past few years to download the videos from ITV. This is the first time I have encountered this error. Could someone please take a look at it?

My yt-dlp is most up-to-date.

Video link: https://www.itv.com/hub/snooker-champion-of-champions/2a2734a0097

Please see the error message below:
![image](https://user-images.githubusercontent.com/44278040/146295787-e08dd785-6007-4b12-9f1b-d143bef52c2b.png)

Thanks a ton!

### Verbose log

```shell
[ITV] 2a2734a0097: Downloading webpage
ERROR: [ITV] 2a2734a0097: Unable to download webpage: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
```

**Comment by pukkandan** [comment]
Provide the complete verbose output of yt-dlp that clearly demonstrates the problem.
Add the `-Uv` flag to your command line you run yt-dlp with (`yt-dlp -Uv <your command line>`), copy the **WHOLE** output and insert it below.
