### ISSUE TITLE
[403 Forbidden] When downloading an Instagram reel

### ISSUE THREAD

**Issue by ARyOtaRe** [yt-dlp/yt-dlp#2013]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2021.12.01**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

France

### Description

![image](https://user-images.githubusercontent.com/72984363/146345442-fa4dd005-5257-4f98-87de-f92c9ea6f042.png)
 the actual link: <https://www.instagram.com/gumblol/reel/CXMMIICIkyY/?utm_medium=copy_link>

### Verbose log

```shell
[debug] Command-line config: ['-Uv', 'https://www.instagram.com/gumblol/reel/CXMMIICIkyY/?utm_medium=copy_link']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2021.12.01 [91f071af6]
[debug] Python version 3.10.1 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] exe versions: ffmpeg 4.4-full_build-www.gyan.dev (setts), ffprobe 4.4-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2021.12.01, Current version: 2021.12.01
yt-dlp is up to date (2021.12.01)
[debug] [generic] Extracting URL: https://www.instagram.com/gumblol/reel/CXMMIICIkyY/?utm_medium=copy_link
[generic] ?utm_medium=copy_link: Requesting header
[redirect] Following redirect to https://www.instagram.com/accounts/login/
[debug] [generic] Extracting URL: https://www.instagram.com/accounts/login/
[generic] login: Requesting header
WARNING: [generic] Could not send HEAD request to https://www.instagram.com/accounts/login/: HTTP Error 405: Method Not Allowed
[generic] login: Downloading webpage
WARNING: [generic] Falling back on generic information extractor.
[generic] login: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://www.instagram.com/accounts/login/
Traceback (most recent call last):
  File "C:\Users\ARyOtaRe\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 1329, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\ARyOtaRe\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 1398, in __extract_info
    ie_result = ie.extract(url)
  File "C:\Users\ARyOtaRe\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\extractor\common.py", line 597, in extract
    ie_result = self._real_extract(url)
  File "C:\Users\ARyOtaRe\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\extractor\generic.py", line 3813, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.instagram.com/accounts/login/
```

**Comment by humble-barnacle001** [comment]
Simply shows that the person has a private account and you might need to login or use browser cookies to actually access that

**Comment by MinePlayersPE** [comment]
Duplicate of https://github.com/yt-dlp/yt-dlp/issues/1925 (fixed with https://github.com/yt-dlp/yt-dlp/commit/8b688881ba45ee7a34d45ad33b295adb871f8f5c, and workaroundable with https://www.instagram.com/reel/CXMMIICIkyY/)

**Comment by ARyOtaRe** [comment]
Didn't see the duplicate 🤔 but thank you!

**Comment by ARyOtaRe** [comment]
I'll close the issue thank you 😄
