### ISSUE TITLE
comment_count usage

### ISSUE THREAD

**Issue by wanghaisheng** [yt-dlp/yt-dlp#2015]
### Checklist

- [X] I'm asking a question and not reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

--write-comments -o "comment_count:10000"

yt-dlp  --config-location config.txt https://www.youtube.com/watch?v=pCUjYAX2JCs

anyway it only extract 1000

**Comment by nao20010128nao** [comment]
You mean `--extractor-args youtube:max_comments=1000` ?

**Comment by wanghaisheng** [comment]
```
-o "./%(extractor_key)s/%(channel_id)s/%(id)s.%(ext)s"
-ciw
--playlist-end 10000
--console-title
--extractor-args "youtube:player_client=android,web;comment_sort=top;max_comments=1000"
--yes-playlist
--remux-video flv>mp4
--merge-output-format mp4
--clean-infojson
--write-thumbnail
--convert-thumbnails png
--proxy socks://127.0.0.1:1080
--embed-subs
--embed-thumbnail 
--write-auto-subs    
--sub-langs "en"
--write-description
--write-info-json
--convert-thumbnails png
--write-comments -o "comment_count:10000"
```
