### ISSUE TITLE
Zee5 link ending with /episodes gives UnsupportedError

### ISSUE THREAD

**Issue by NightFury135269** [yt-dlp/yt-dlp#2016]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2021.12.01**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

India

### Description

When passed a zee5 series link ending with /episodes rises UnsupportedError error as the regex to validate the link in zee5 extractor don't handle it. 
When on zee5 required series page the link is for example "https://www.zee5.com/tvshows/details/chala-hawa-yeu-dya-ladies-zindabaad/0-6-2943" but when we click More button to get all episodes available, '/episodes' is add to link at end changing it to "https://www.zee5.com/tvshows/details/chala-hawa-yeu-dya-ladies-zindabaad/0-6-2943/episodes".

To Fix update _VALID_URL in Zee5SeriesIE with r"(?x)(?:zee5:series:|https?://(?:www\.)?zee5\.com/(?:[^#?]+/)?(?:tvshows|kids|zee5originals)(?:/[^#/?]+){2}/)(?P<id>[^#/?]+)/?(?:episodes)/?(?:$|[?#])".
Here I just added /?(?:episodes) to handle it.

Its not a big issue but I myself was trying to download series and keep on getting error made me thinking that yt-dlp don't support it but on looking at extractor I realized it was '/episodes' causing problem and worked as expected with '/episodes' removed.

### Verbose log

```shell
PS C:\Users\username> yt-dlp -Uv https://www.zee5.com/tvshows/details/chala-hawa-yeu-dya-ladies-zindabaad/0-6-2943/episodes

[debug] Command-line config: ['-Uv', 'https://www.zee5.com/tvshows/details/chala-hawa-yeu-dya-ladies-zindabaad/0-6-2943/episodes']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2021.12.01 [91f071a] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.22000-SP0
[debug] exe versions: ffmpeg 4.4-full_build-www.gyan.dev (setts), ffprobe 4.4-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2021.12.01, Current version: 2021.12.01
yt-dlp is up to date (2021.12.01)
[debug] [generic] Extracting URL: https://www.zee5.com/tvshows/details/chala-hawa-yeu-dya-ladies-zindabaad/0-6-2943/episodes
[generic] episodes: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] episodes: Downloading webpage
[generic] episodes: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://www.zee5.com/tvshows/details/chala-hawa-yeu-dya-ladies-zindabaad/0-6-2943/episodes
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1329, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1398, in __extract_info
  File "yt_dlp\extractor\common.py", line 597, in extract
  File "yt_dlp\extractor\generic.py", line 3813, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.zee5.com/tvshows/details/chala-hawa-yeu-dya-ladies-zindabaad/0-6-2943/episodes
```

**Comment by Ashish0804** [comment]
Not an issue.
The episodes page is technically seasons page which would imply downloading a particular season is supported (which isn't)

**Comment by NightFury135269** [comment]
But from what I have observed the ids for different seasons of same series are different so why is it not supported
