### ISSUE TITLE
Debian/Ubuntu deb package

### ISSUE THREAD

**Issue by sebastian-arnhold** [yt-dlp/yt-dlp#2018]
### Checklist

- [X] I'm reporting a feature request
- [X] I've verified that I'm running yt-dlp version **2021.12.01**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

Dear developers,

it seems that youtube-dl has died, as have all other similar projects. Therefore, yt-dlp can be seen as it's true successor.

Would it be possible to create a .deb package and include it in the Debian repository?

The release schedule for Ubuntu's next big release (22.04 LTS) states that "Debian import freeze" will happen on February 24th. If yt-dlp can be added to the Debian repository before then, it will make it into Ubuntu's next release which will be supported for two years and have widespread usage.

It would also make the installation procedure a lot easier, and more trustworthy for beginners.

There's also a project called youtubedl-gui made by "JaGoLi" (https://github.com/JaGoLi/ytdl-gui), which is currently included in Debian/Ubuntu. Maybe these guys want to work together with you to adapt their GUI to your project (since the two are very similar)? Then we'd all have a functioning GUI for yt-dlp ready to install with one click.

Thanks in advance! :)
Sebastian

**Comment by pukkandan** [comment]
Ask debian package maintainers

**Comment by pukkandan** [comment]
> There's also a project called youtubedl-gui made by "JaGoLi" (JaGoLi/ytdl-gui), which is currently included in Debian/Ubuntu. Maybe these guys want to work together with you to adapt their GUI to your project (since the two are very similar)? Then we'd all have a functioning GUI for yt-dlp ready to install with one click.

Again, ask the developer of the GUI to add support for yt-dlp if you want. There is nothing for me to do about it

**Comment by sebastian-arnhold** [comment]
My feature request was if the development team of yt-dlp would like to maintain the Debian/Ubuntu package. This would greatly improve availability and ease of use in the Linux world, therefore helping to spread the software. Maybe this is in your interest.

Same goes for cooperation with the GUI project. This would have to be closely coordinated between the two git projects, but would also vastly increase the usability and therefore help getting more users to use the software.

If this is not possible, it's alright with me. I just wanted to feature request this since I believe these two things could be helpful. Thanks! :)

**Comment by pukkandan** [comment]
> My feature request was if the development team of yt-dlp would like to maintain the Debian/Ubuntu package themselves. This would greatly improve availability and ease of use in the Linux world, therefore helping to spread the software. Maybe this is in your interest.

We will not be maintaining or supporting distro packages. Use PIP if you want an "official" solution

> Same goes for cooperation with the GUI project. This would have to be closely coordinated between the two github projects, but would also vastly increase the usability and therefore help getting more users to use the softwares of both teams.

That is not how the relationship b/w backend and frontends works. yt-dlp has many third party GUIs and there is no plan to make a first-party solution. It is on the developer of the above-mentioned project to support yt-dlp. If the devs want some feature or changes for better integration with their project, they are free to make a request for it
