### ISSUE TITLE
How to provide `format_id` in Embedding Yt-DLP ? 

### ISSUE THREAD

**Issue by MrBotDeveloper** [yt-dlp/yt-dlp#2024]
### Checklist

- [X] I'm asking a question and not reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

Hello, I have to provide `format_id` in format . But I can't get how to do so. I have tried to do so but I got error. Please help me.

Code which I tried ....
```python
from yt_dlp import YoutubeDL

def down_hook(d):
    if d['status'] == 'finished':
        print('Successfully completed download.')

ytdl_opts = {
    'format': {
        'format_id': 701,
        'ext': 'mp4'
    }, 
    'progress_hooks': [down_hook],
    'outtmpl': './Downloads/video77.mp4',
    'ignoreerrors': True,
    'restrictfilenames': False,
    'quiet': True
}

url = "https://youtu.be/hVvEISFw9w0"

def download():
    with YoutubeDL(ytdl_opts) as ytdlp:
        ytdlp.download([url])

download()
```

But using above code I am getting the below 👇 error :
```text
File "/app/code.py", line 22, in download
    with YoutubeDL(ytdl_opts) as ytdlp:
    File "/app/.railway/python/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 627, in __init__
        else self.build_format_selector(self.params['format']))
    File "/app/.railway/python/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 2139, in build_format_selector
        stream = io.BytesIO(format_spec.encode('utf-8'))
AttributeError: 'dict' object has no attribute 'encode'
```

**Comment by pukkandan** [comment]
I don't understand what you are trying to accomplish. What would be the equivalent CLI command?

**Comment by MrBotDeveloper** [comment]
As it provides a good option of getting download hooks....

**Comment by MrBotDeveloper** [comment]
@pukkandan sorry sir, for the last mistake now I have completed my code please guide me....

**Comment by pukkandan** [comment]
> As it provides a good option of getting progress_hooks....

I am not asking why you are using API...

I just don't understand what you are trying to do with the `format` key here. You are going to have to explain it more than "I have to provide format_id in format".

Maybe you are looking for `'format': '22'`?

**Comment by MrBotDeveloper** [comment]
Ok, thanks a lot sir, it worked 😊.

I had tried that as I have seen such type way [here](https://github.com/yt-dlp/yt-dlp#embedding-yt-dlp) in `def format_selector(ctx)` so, i thinked to do so.....

**Comment by MrBotDeveloper** [comment]
> > As it provides a good option of getting progress_hooks....
> 
> I am NOT asking why you are using API...
> 
> I just don't understand what you are trying to do with the `format` key here. You are going to have to explain it more than "I have to provide format_id in format".
> 
> Maybe you are looking for `'format': '22'`?

Using directly `format_id` is generating a video without audio. How can I fix it?
