### ISSUE TITLE
private videos

### ISSUE THREAD

**Issue by kurt580228** [yt-dlp/yt-dlp#2027]
### Checklist

- [X] I'm asking a question and not reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

Dear all,
 
I'm using yt-dlp 2021.12.01.
On downloading playlists on Youtube I get a lot of
'Private video. Sign in if you've been granted access to this video'- remarks. Is this right?
As I think, if you put videos on Youtube, they shouldn't be private.
 
Kind regards
 
Kurt (that's my christian name (or surname)

**Comment by pukkandan** [comment]
> As I think, if you put videos on Youtube, they shouldn't be private.

You can put private videos on youtube. Try opening them in browser and see if it is actually private. If not, provide link and verbose log.
