### ISSUE TITLE
Does videos downloaded from Rumble work for you?

### ISSUE THREAD

**Issue by peter099** [yt-dlp/yt-dlp#2028]
### Checklist

- [X] I'm asking a question and not reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

I am able to download videos from Rumble but when i try to play it they won't play. Anyone else having this problem?

**Comment by pukkandan** [comment]
> [x] I'm asking a question and not reporting a bug/feature request

**Comment by peter099** [comment]
I am asking a question, not reporting broken site.

**Comment by pukkandan** [comment]
You want us to go find a video, test if it downloads and report back to you when you are not even willing to fill out the appropriate templates? This is not a forum, but the project's issue tracker

**Comment by peter099** [comment]
You don't need to look for a specific video, it happens with any video i download from rumble, and i am asking if anyone else is experience the same or the problem is on my side. Also, with youtube-dl i don't have this issue.
