### ISSUE TITLE
Broken link?

### ISSUE THREAD

**Issue by DarrenPIngram** [yt-dlp/yt-dlp#2030]
### Checklist

- [X] I'm asking a question and not reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

Should the 'sponsor this project' link (presumably a way to give a modest personal donation) go to a list of people who are making great software together?

Slightly confused and I had my 'virtual chequebook' out too.

**Comment by pukkandan** [comment]
It does go to https://github.com/yt-dlp/yt-dlp/blob/master/Collaborators.md#collaborators which lists the maintainers of the repo with each of their donation links.

For obvious reasons, it is not practical to provide links for all the 100+ contributors (that isn't even including all youtube-dl contributors). If there is some specific contributor you wish to donate to, I suggest you look at their profile for a link, or try reaching out to them

**Comment by DarrenPIngram** [comment]
Ah, not so familiar and (wrongly) assumed there may be a project pot, I guess it created temporary confusion.  Will go and drop a little something in. 


—- 
Via iPad. Hopefully with not too many typos.
