### ISSUE TITLE
MPD: how to download only fragments, without concat into one output file

### ISSUE THREAD

**Issue by wilsonssss** [yt-dlp/yt-dlp#2034]
### Checklist

- [X] I'm asking a question and not reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

i wonder there are features blow or not?

- wanner download only fragments, no concat video or audio
- save original mpd file

**Comment by nyuszika7h** [comment]
Note that a saved MPD with relative BaseURLs may be useless unless you either

* saved the MPD URL
* rewrote all relative BaseURLs in the MPD to be absolute

**Comment by pukkandan** [comment]
> download only fragments, no concat video or audio

`--keep-fragments` will download and append the fragments, but also keep them on disk. You can delete the final file at the end

> save original mpd file

`--write-pages` will save all webpages downloaded including manifests

Other than that, these are not possible
