### ISSUE TITLE
[YoutubeDL] Display verbose video titles in formats list output

### ISSUE THREAD

**Issue by parmjitv** [yt-dlp/yt-dlp#2035]
### Checklist

- [X] I'm reporting a feature request
- [X] I've verified that I'm running yt-dlp version **2021.12.01**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

$ yt-dlp --no-color -Uv -F https://www.youtube.com/watch?v=9_dgIfz876A
[debug] Command-line config: ['--no-color', '-Uv', '-F', 'https://www.youtube.com/watch?v=9_dgIfz876A']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, err UTF-8, pref UTF-8
[debug] yt-dlp version 2021.12.01 [91f071af6] (zip)
[debug] Python version 3.7.3 (CPython 64bit) - Linux-4.19.0-9-amd64-x86_64-with-debian-10.4
[debug] exe versions: ffmpeg 4.1.4-1, ffprobe 4.1.4-1, phantomjs ., rtmpdump 2.4
[debug] Optional libraries: Crypto, keyring, sqlite
[debug] Proxy map: {}
Latest version: 2021.12.01, Current version: 2021.12.01
yt-dlp is up to date (2021.12.01)
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=9_dgIfz876A
[youtube] 9_dgIfz876A: Downloading webpage
[youtube] 9_dgIfz876A: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
**[info] Available formats for 9_dgIfz876A:**
...

It would be very useful for troubleshooting/inspection purposes to also see all video titles in the formats list output - option switch (-F) in YoutubeDL.

i.e.
[info] Available formats for Nine Inch Nails - Right Where It Belongs 720p HD (Fixed camera angle, from BYIT) [9_dgIfz876A]:

Cheers,

Parmjit V.

**Comment by Ashish0804** [comment]
`--print title`

**Comment by parmjitv** [comment]
@Ashish0804 Ah, thank you! Good to know for future reference.

**Comment by pukkandan** [comment]
Unlike youtube-dl, the `--print` and the various `--list` options can be combined in yt-dlp

**Comment by parmjitv** [comment]
@Ashish0804 @pukkandan Very nice! I was one of the contributors to the previous youtube-dl project a while back, and I am happy to see this project is active now with new features and collaborators.  Looking forward to making contributions again.  Cheers!
