### ISSUE TITLE
Add option to prevent/restrict redirection

### ISSUE THREAD

**Issue by gentlecolts** [yt-dlp/yt-dlp#2044]
### Checklist

- [X] I'm reporting a feature request
- [X] I've verified that I'm running yt-dlp version **2021.12.01**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

Many sites embed media in sometimes awkward ways, for example: A twitter post may link to a site which embeds a youtube stream.  Youtube-dl/yt-dlp will recurse through links in an attempt to find the media a user requests, however this can at times be undesireable, especially when used with automated downloaders.

My use case:  I run a chat bot that fetches media that users post (and am looking to migrate from youtube-dl to yt-dlp).  If a user, for example, posts a twitter or reddit link with video content.  Occasionally, some of these links actually embed lengthy youtube streams, which causes the bot to hang up for long periods of time.  It would be nice if there were some way to specify, both through command line and through the python interface, to specify a maximum number of redirect attempts to prevent this issue.

**Comment by pukkandan** [comment]
example?

**Comment by gentlecolts** [comment]
Here is an exmaple: https://twitter.com/TheRealStanLee/status/1470750431643058181?s=20

I have not tested this particular link in yt-dlp yet, however in youtube-dl, it will redirect  to the linked page, the [Generic] handler will find a youtube embed, which then gets downloaded, when instead i would have preferred this page skipped entirely, since there's no actual video content embedded in the tweet

**Comment by pukkandan** [comment]
There is a fundamental assumption in youtube-dl's design that the page you are passing has some video content that you are trying to download. So in order to catch as many cases as possible, the generic extractor tries all sort of tricks to find a video in the webpage. It is not possible to disable these without breaking a lot of pages.

There has been a feature request to allow user to specify the IEs that should be used for extraction. . Once that is implemented, you should be able to completely disable Generic extractor (example syntax: `--ie-names all,-Generic`). But as I said above, this will break a lot of pages. I am assuming you are okay with that

**Comment by gentlecolts** [comment]
Being able to restrict which extractors are use would address this use case as well, that's good to hear.  I assume this will be supported via the python interface as well, and not just as a command line flag?

**Comment by pukkandan** [comment]
yes, ofc. Anything that u can do via CLI can be done with the API - even if one may sometimes be easier than the other

Actually, if you are using API, you can already monkeypatch yt_dlp to do this

```py
from yt_dlp import YoutubeDL, extractor

assert extractor._ALL_CLASSES[-1].__name__ == 'GenericIE'
extractor._ALL_CLASSES.pop()

with YoutubeDL() as ydl:
    ydl.extract_info('https://twitter.com/TheRealStanLee/status/1470750431643058181?s=20')
```

**Comment by pukkandan** [comment]
Now you can do `--ies default,-generic`
