### ISSUE TITLE
Default downloader instead of aria2c is used when downloading mhtml videos 

### ISSUE THREAD

**Issue by mhogomchungu** [yt-dlp/yt-dlp#2047]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2021.12.01**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

I have setup yt-dlp to use aria2c as a downloader but it uses the default downloader instead when downloading media with extension "mhtml" on youtube.

### Verbose log

```shell
"yt-dlp" "--downloader" "aria2c"  "--newline" "-f" "sb0" "https://www.youtube.com/watch?v=zZB2CdvlzKE"
[youtube] zZB2CdvlzKE: Downloading webpage
[youtube] zZB2CdvlzKE: Downloading android player API JSON
[info] zZB2CdvlzKE: Downloading 1 format(s): sb0
[mhtml] Total fragments: 3
[download] Destination: THROWBACK - Brock Lesnar serves up breakfast 🍳 _ #shorts [zZB2CdvlzKE].mhtml
[download]   1.6% of ~61.86KiB at  964.18B/s ETA 01:04
[download]   4.8% of ~61.86KiB at  2.82KiB/s ETA 00:20
[download]  11.3% of ~61.86KiB at  6.42KiB/s ETA 00:08
[download]  24.2% of ~61.86KiB at 13.75KiB/s ETA 00:03
[download]  33.3% of ~61.86KiB at 18.86KiB/s ETA 00:02
[download]  33.3% of ~61.86KiB at 18.84KiB/s ETA 00:02 (frag 1/3)
[download]  32.3% of ~66.97KiB at  531.33B/s ETA 00:06 (frag 1/3)
[download]  35.3% of ~66.97KiB at  1.56KiB/s ETA 00:05 (frag 1/3)
[download]  41.2% of ~66.97KiB at  3.63KiB/s ETA 00:04 (frag 1/3)
[download]  53.2% of ~66.97KiB at  7.77KiB/s ETA 00:02 (frag 1/3)
[download]  66.7% of ~66.97KiB at 11.89KiB/s ETA 00:01 (frag 1/3)
[download]  66.7% of ~66.97KiB at 11.88KiB/s ETA 00:01 (frag 2/3)
[download]  92.4% of ~49.42KiB at  587.59B/s ETA 00:00 (frag 2/3)
[download]  96.4% of ~49.42KiB at  1.72KiB/s ETA 00:00 (frag 2/3)
[download] 100% of ~49.42KiB at  2.73KiB/s ETA 00:00 (frag 2/3)
[download] 100% of ~49.42KiB at  2.73KiB/s ETA 00:00 (frag 3/3)
[download] 100% of 52.00KiB in 00:04
[ink@localhost ~]$ 


When downloading other formats, aria2c is used as expected.

"yt-dlp" "--downloader" "aria2c"  "--newline" "-f" "worstaudio" "https://www.youtube.com/watch?v=zZB2CdvlzKE" >
[youtube] zZB2CdvlzKE: Downloading webpage
[youtube] zZB2CdvlzKE: Downloading android player API JSON
[info] zZB2CdvlzKE: Downloading 1 format(s): 139
[download] Destination: THROWBACK - Brock Lesnar serves up breakfast 🍳 _ #shorts [zZB2CdvlzKE].m4a
[#d50b35 208KiB/327KiB(63%) CN:1 DL:173KiB]
[#d50b35 224KiB/327KiB(68%) CN:1 DL:101KiB ETA:1s]
[#d50b35 224KiB/327KiB(68%) CN:1 DL:70KiB ETA:1s]
[#d50b35 224KiB/327KiB(68%) CN:1 DL:53KiB ETA:1s]
[#d50b35 224KiB/327KiB(68%) CN:1 DL:43KiB ETA:2s]
[#d50b35 224KiB/327KiB(68%) CN:1 DL:36KiB ETA:2s]
[#d50b35 224KiB/327KiB(68%) CN:1 DL:31KiB ETA:3s]

[aria2c] Downloaded 335622 bytes
[download] 100% of 327.76KiB in 00:07
[FixupM4a] Correcting container of "THROWBACK - Brock Lesnar serves up breakfast 🍳 _ #shorts [zZB2CdvlzKE].m4a"
```

**Comment by pukkandan** [comment]
That is normal. External downloader support is not implemented for `mhtml`. And even if implemented, it will probably only decrease download speeds - the fragments are too few and too small for aria2c to do its magic. I can convert this to a feature request if you want, but as I said above, it won't actually help and so it's unlikely any devs will want to work on it

There are also some other formats that are not supported by aria2c. Eg: live videos, arbitrary byte-range downloads (not for YT). Those will also fall back to the native/ffmpeg

**Comment by mhogomchungu** [comment]
Ok, i did not know it was intentional.
