### ISSUE TITLE
[odysee] Livestream support

### ISSUE THREAD

**Issue by trueauracoral** [yt-dlp/yt-dlp#2054]
### Checklist

- [X] I'm reporting a site feature request
- [X] I've verified that I'm running yt-dlp version **2021.12.01**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

USA

### Example URLs

https://odysee.com/@stjohnshermancenter:1/live:a16. If you need more links go to the wild west tab on odysee and you can find all kinds of livestreams.

I would put a peertube link here but I can't find a active livestream.

### Description

So on both twitch and youtube (proprietary platforms) you can watch livestreams with yt-dlp + mpv. However on more respecting of the user platforms like odysee or peertube. yt-dlp + mpv to view there livestreams don't want to work. Is it possible that livestream support for these platforms could get added?

**Comment by troler36** [comment]
this is a well written issue. I hope it gets fixed soon

**Comment by pukkandan** [comment]
Odyssey and peertube are totally different services and should be tracked in separate issues. I'll rename this to just odessey. Open a new one for peertube.

> I would put a peertube link here but I can't find a active livestream.

If you can't tell us where we can find links to livestreams, how can devs add support for it?

**Comment by trueauracoral** [comment]
> Odyssey and peertube are totally different services and should be tracked in separate issues. I'll rename this to just odessey. Open a new one for peertube.
> 
> > I would put a peertube link here but I can't find a active livestream.
> 
> If you can't tell us where we can find links to livestreams, how can devs add support for it?

I made a new issue <https://github.com/yt-dlp/yt-dlp/issues/2055>

**Comment by Ashish0804** [comment]
I'll try to add this today (will have to read a couple of live extractors)
