### ISSUE TITLE
[peertube] Livestream Support

### ISSUE THREAD

**Issue by trueauracoral** [yt-dlp/yt-dlp#2055]
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2021.12.01**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

USA

### Example URLs

https://yoba.tv/w/aMGyZjoNx8R3XnRvSnCC9G
Finding livestreams on peertube is difficult. But it's doable. This one goes on forever so I think it's useful for testing and stuff.

### Description

Peertube is a open source, multi instance, decentralized epic platform for sharing videos. I would love to be able to watch livestreams through yt-dlp + mpv like it is possible with youtube/twitch.

### Verbose log

```shell
yt-dlp https://yoba.tv/w/aMGyZjoNx8R3XnRvSnCC9G
[generic] aMGyZjoNx8R3XnRvSnCC9G: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] aMGyZjoNx8R3XnRvSnCC9G: Downloading webpage
[generic] aMGyZjoNx8R3XnRvSnCC9G: Extracting information
[download] Downloading playlist: BAKED & LOULZ | 24/7 Cam YOBA House Live | TTS & Media
[generic] playlist BAKED & LOULZ | 24/7 Cam YOBA House Live | TTS & Media: Collected 1 videos; downloading 1 of them
[download] Downloading video 1 of 1
[PeerTube] aMGyZjoNx8R3XnRvSnCC9G: Downloading video JSON
ERROR: [PeerTube] aMGyZjoNx8R3XnRvSnCC9G: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
[download] Finished downloading playlist: BAKED & LOULZ | 24/7 Cam YOBA House Live | TTS & Media
```

**Comment by ndren** [comment]
The JSON API (https://yoba.tv/api/v1/videos/aMGyZjoNx8R3XnRvSnCC9G) returns the following m3u8: https://yoba.tv/static/streaming-playlists/hls/4f43b80e-f320-45e2-a490-b0b7d99856f8/master.m3u8. Playing that directly works as intended.

**Comment by libreom** [comment]
> The JSON API (https://yoba.tv/api/v1/videos/aMGyZjoNx8R3XnRvSnCC9G) returns the following m3u8: https://yoba.tv/static/streaming-playlists/hls/4f43b80e-f320-45e2-a490-b0b7d99856f8/master.m3u8. Playing that directly works as intended.

any updates?
If this works,why not go with it.

**Comment by ndren** [comment]
I'm not familiar with the codebase, please try it out if you would like.

**Comment by trueauracoral** [comment]
I have some knowledge in python. I think probably next week (I currently have exams in all my classes) I can try my best to follow the documentation and implement this. Hopefully the API mentioned in the previous comment the url structure still is relevant and can be used today. 
https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#adding-support-for-a-new-site

**Comment by RutD0g** [comment]
Any progress on this? I don't have the coding skills myself.

My workaround is to use Video DownloadHelper browser extension to sniff out the .m3u8, copy it and use yt-dlp on that link.

Is there any better or simpler way to find the .m3u8?

Example:

https://peertube.anon-kenkai.com/w/eUT7Fu9su2XumApsUNuQnC

![image](https://github.com/yt-dlp/yt-dlp/assets/66397082/edc639c3-7f5b-4a09-b202-e9cbdaaf80ad)

![image](https://github.com/yt-dlp/yt-dlp/assets/66397082/0512f096-4289-478f-ae64-5851d2cc4667)

https://poast.tv/static/streaming-playlists/hls/70a8fabe-b3d9-49da-8f1a-2a96c8da8b66/0.m3u8

Abridged output:
```

C:\> yt-dlp --list-formats  https://poast.tv/static/streaming-playlists/hls/70a8fabe-b3d9-49da-8f1a-2a96c8da8b66/0.m3u8
[debug] Identified a direct video link
[generic] 0: Downloading m3u8 information
[generic] 0: Checking m3u8 live status
[info] Available formats for 0:

ID EXT RESOLUTION │ PROTO │ VCODEC  ACODEC
───────────────────────────────────────────
0  mp4 unknown    │ m3u8  │ unknown unknown
```

**Comment by trueauracoral** [comment]
No, I forgot about this I now have finals actually last post I had midterms. I can probably try next week but actually this time. It appears the api is still functioning to return the m3u8

https://peertube.anon-kenkai.com/api/v1/videos/eUT7Fu9su2XumApsUNuQnC
![image](https://github.com/yt-dlp/yt-dlp/assets/87541524/0c09dbf8-35af-4b5a-b630-9812c9c4d8e3)

Yeah if a code is made to do this all in yt-dlp it would be much easier. I have never written a yt-dlp extension so it would be more difficult I will just need to read the documentation finally.

**Comment by RutD0g** [comment]
Long overdue thanks for getting this implemented. I use it regularly.

Is there any way to show support other than my thanks? 

If you happen to be at 2024.fossy.org in Portland this weekend I'll buy you a drink!

**Comment by trueauracoral** [comment]
I am glad that you find use from this. That is enough for me. I don't drink alcohol, I just drink water. Thank you for the consideration. I hope you have a nice day
