### ISSUE TITLE
Control Video Quality in Peertube?

### ISSUE THREAD

**Issue by MintMain21** [yt-dlp/yt-dlp#2057]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2021.12.01**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

In my MPV.config file, I have --ytdl-format="bestvideo[height<=360][vcodec!=vp9]+bestaudio/best" listed as an option. This insures that videos I play from YouTube won't overwork my slightly under-powered computer. Experimenting with Peertube links after upgrading from YT-DL to YT-DLP, I've found that this command is not respected and playback will be of a HD video that my computer cannot handle. Perhaps there is a different command I'm overlooking to ensure decent playback, but I feel like since most videos on Peertube (tilvids.com specifically) have an option to view videos in 360p that it should respect my preference as if it were a YouTube link. 

### Verbose log

```shell
$ yt-dlp -Uv
[debug] Command-line config: ['-Uv']
[debug] Portable config file: /home/michael/bin/yt-dlp.conf
[debug] Portable config: ['--embed-thumbnail', '-o', '~/YT-DLP/%(title)s.%(ext)s']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2021.12.01 [91f071af6] (zip)
[debug] Python version 3.8.10 (CPython 64bit) - Linux-5.4.0-91-generic-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4, rtmpdump 2.4
[debug] Optional libraries: Crypto, keyring, mutagen, sqlite
[debug] Proxy map: {}
Latest version: 2021.12.01, Current version: 2021.12.01
yt-dlp is up to date (2021.12.01)
```

**Comment by pukkandan** [comment]
> In my MPV.config file, I have --ytdl-format="bestvideo[height<=360][vcodec!=vp9]+bestaudio/best" listed as an option

This is not the mpv issue tracker!

Run the equivalent command directly in `yt-dlp` and show the full verbose log

**Comment by MintMain21** [comment]
Welp, after doing some research, I found that if I replaced "bestvideo[height<=360][vcodec!=vp9]+bestaudio/best" with "res:360" I got my intended results, in YouTube and Peertube. So, I guess the command I was looking for was here all along. Sorry.

**Comment by bheeshmpita** [comment]
> Welp, after doing some research, I found that if I replaced "bestvideo[height<=360][vcodec!=vp9]+bestaudio/best" with "res:360" I got my intended results, in YouTube and Peertube. So, I guess the command I was looking for was here all along. Sorry.

i am facing the same issue. i want the youtube (&other)  videos to stream videos which are not of vp9 codec and <=480p. so what changes should i make and where?

**Comment by MintMain21** [comment]
Just do what I did.

**Comment by bheeshmpita** [comment]
> Just do what I did.

just to be clear, i wanted to know where should i make changes- in mpv.conf?
and can you confirm should i be adding `yt-dlp "res:480"` for streaming video in 480p and in h264 codec
