### ISSUE TITLE
Viki no video formats found

### ISSUE THREAD

**Issue by shivsah** [yt-dlp/yt-dlp#206]
## Checklist

- [X] I'm reporting a broken site support
- [X] I've verified that I'm running yt-dlp version **2021.03.24.1**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] Command-line config: ['-F', '--username', 'PRIVATE', '--password', 'PRIVATE', '--add-header', 'x-viki-app-ver:6.0.0', '--add-header', 'x-viki-as-id: 100005a', '--add-header', 'x-client-user-agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.183 Safari/537.36', '--sub-lang', 'en', '--sub-format', 'vtt', '--write-sub', '--allow-unplayable-formats', 'https://www.viki.com/videos/1161860v-the-best-hit-episode-1', '--verbose']
[debug] Loading archive file None
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] yt-dlp version 2021.03.24.1
[debug] Python version 3.7.3 (CPython 64bit) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg 4.2, ffprobe 4.2
[debug] Proxy map: {}
[viki] Logging in
[viki] 1161860v: Downloading video JSON
[viki] 1161860v: Downloading video streams JSON
ERROR: No video formats found; please report this issue on https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "c:\users\shivam\appdata\local\programs\python\python37\lib\site-packages\yt_dlp\YoutubeDL.py", line 1026, in wrapper
    return func(self, *args, **kwargs)
  File "c:\users\shivam\appdata\local\programs\python\python37\lib\site-packages\yt_dlp\YoutubeDL.py", line 1047, in __extract_info
    ie_result = ie.extract(url)
  File "c:\users\shivam\appdata\local\programs\python\python37\lib\site-packages\yt_dlp\extractor\common.py", line 558, in extract
    ie_result = self._real_extract(url)
  File "c:\users\shivam\appdata\local\programs\python\python37\lib\site-packages\yt_dlp\extractor\viki.py", line 378, in _real_extract
    self._sort_formats(formats)
  File "c:\users\shivam\appdata\local\programs\python\python37\lib\site-packages\yt_dlp\extractor\common.py", line 1667, in _sort_formats
    raise ExtractorError('No video formats found')
yt_dlp.utils.ExtractorError: No video formats found; please report this issue on https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.

```

## Description

It just seems to be happening in limited shows so far.

Show i tried :- [https://www.viki.com/tv/35431c](https://www.viki.com/tv/35431c)

**Comment by pukkandan** [comment]
Are you able to see this in browser? I get this: 
![image](https://user-images.githubusercontent.com/6623388/113259796-29baa600-92eb-11eb-8d5c-5502f42f19ab.png)

**Comment by shivsah** [comment]
for me the page loads

**Comment by shivsah** [comment]
![image](https://user-images.githubusercontent.com/17703895/113259958-58d11780-92eb-11eb-9b9b-78be9b6ce232.png)
This is what i get.

**Comment by pukkandan** [comment]
this loads. Try playing the first episode

**Comment by shivsah** [comment]
![image](https://user-images.githubusercontent.com/17703895/113260175-95047800-92eb-11eb-9b2b-78f72db4700d.png)

**Comment by pukkandan** [comment]
> this loads. Try playing the first episode
This was issue from my side.

The video is DRM protected, so I will not be fixing it. If you can give an example URL without DRM where this happens, I can look into it

PS: I dont have a viki account, so you'll need to either give free video URLs, or DM me the account details

**Comment by shivsah** [comment]
Are all the streams DRM protected ..?

**Comment by shivsah** [comment]
![image](https://user-images.githubusercontent.com/17703895/113261429-18729900-92ed-11eb-8ce9-26d5b5c9fc6a.png)
It works even without an account

**Comment by pukkandan** [comment]
> It works even without an account

Yes

> Are all the streams DRM protected ..?

All that I could find. I'm not closing this issue so that someone else could also have a look

**Comment by parnexcodes** [comment]
Working fine for me .
`General
Complete name                            : D:\webdl\Downloads\viki1.mp4
Format                                   : MPEG-4
Format profile                           : Base Media
Codec ID                                 : isom (isom/iso2/avc1/mp41)
File size                                : 219 MiB
Duration                                 : 39 min 10 s
Overall bit rate                         : 782 kb/s
Writing application                      : Lavf58.32.104

Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L3
Format settings                          : CABAC / 4 Ref Frames
Format settings, CABAC                   : Yes
Format settings, Reference frames        : 4 frames
Codec ID                                 : avc1
Codec ID/Info                            : Advanced Video Coding
Duration                                 : 39 min 10 s
Bit rate                                 : 585 kb/s
Width                                    : 852 pixels
Height                                   : 480 pixels
Display aspect ratio                     : 16:9
Original display aspect ratio            : 16:9
Frame rate mode                          : Constant
Frame rate                               : 24.000 FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.060
Stream size                              : 164 MiB (75%)
Writing library                          : x264 core 148
Encoding settings                        : cabac=1 / ref=3 / deblock=1:0:0 / analyse=0x3:0x113 / me=umh / subme=10 / psy=1 / psy_rd=1.00:0.00 / mixed_ref=1 / me_range=24 / chroma_me=1 / trellis=2 / 8x8dct=1 / cqm=0 / deadzone=21,11 / fast_pskip=1 / chroma_qp_offset=-2 / threads=12 / lookahead_threads=1 / sliced_threads=0 / nr=0 / decimate=1 / interlaced=0 / bluray_compat=0 / constrained_intra=0 / bframes=3 / b_pyramid=2 / b_adapt=2 / b_bias=0 / direct=1 / weightb=1 / open_gop=0 / weightp=2 / keyint=120 / keyint_min=61 / scenecut=0 / intra_refresh=0 / rc_lookahead=60 / rc=2pass / mbtree=1 / bitrate=585 / ratetol=1.0 / qcomp=0.60 / qpmin=0 / qpmax=69 / qpstep=4 / cplxblur=20.0 / qblur=0.5 / vbv_maxrate=1170 / vbv_bufsize=1755 / nal_hrd=none / filler=0 / ip_ratio=1.40 / aq=1:1.00
Codec configuration box                  : avcC

Audio
ID                                       : 2
Format                                   : AAC LC
Format/Info                              : Advanced Audio Codec Low Complexity
Codec ID                                 : mp4a-40-2
Duration                                 : 39 min 10 s
Bit rate mode                            : Constant
Bit rate                                 : 192 kb/s
Channel(s)                               : 2 channels
Channel layout                           : L R
Sampling rate                            : 48.0 kHz
Frame rate                               : 46.875 FPS (1024 SPF)
Compression mode                         : Lossy
Stream size                              : 53.8 MiB (25%)
Default                                  : Yes
Alternate group                          : 1

`

**Comment by pukkandan** [comment]
@parnexcodes what is the command u used to download?

**Comment by parnexcodes** [comment]
Edited my comment , check.

**Comment by pukkandan** [comment]
DO NOT post methods to break DRM. You will be blocked
