### ISSUE TITLE
`--embed-thumbnail` should not override default container preference

### ISSUE THREAD

**Issue by database64128** [yt-dlp/yt-dlp#2061]
### Checklist

- [X] I'm reporting a feature request
- [X] I've verified that I'm running yt-dlp version **2021.12.01**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

The commit 4e3b637d5be70b92ee511743405f3c907fed20f6 introduced an unexpected and surprising behavior, where the use of `--embed-thumbnail` option overrides the default container preference. This change essentially added a nasty workaround that looks terrible and out of place in code, breaks hierarchy, and is difficult to maintain. I also fail to see why it's necessary. The user can always use `--merge-output-format mkv` after seeing the warning message.

**Comment by database64128** [comment]
ref #500

**Comment by nyuszika7h** [comment]
I don't see the issue here. As far as I can tell from the code, it only forces MKV if `--merge-output-format` is not explicitly specified. Users generally expect yt-dlp to work out of the box rather than being bombarded with "use this option" and "use that option". (One notable exception is things like `--check-formats` which may cause significant slowdown if enabled by default.)

**Comment by pukkandan** [comment]
Why do you consider this "unexpected behavior"? When user does not specify a format to merge, don't you think yt-dlp should select the best format suitable according to the other options given?

**Comment by database64128** [comment]
> Why do you consider this "unexpected behavior"?

For example, when you specify `-f 248+251`, it's natural to assume `webm` would be the container of the merged file, since both `248` and `251` are in the `webm` container. This is no longer the case after this change.

Also, when you download the audio from a video with subtitles using `-f 140`, the final container is always `m4a` and `--embed-subs` does not change the container. This is the correct and expected behavior. After this change, `--embed-thumbnail` no longer behaves the same as `--embed-subs`.

> When user does not specify a format to merge, don't you think yt-dlp should select the best format suitable according to the other options given?

That's what container preference is for. This change unnecessarily complicates the logic for container selection, and makes the code look messy.

**Comment by pukkandan** [comment]
> For example, when you specify -f 248+251, it's natural to assume webm would be the container of the merged file, since both 248 and 251 are in the webm container. This is no longer the case after this change.

No, if you want it to be strictly in webm, use `--merge webm`. It is more "natural" to assume thumbnail wil be embedded when you use `--embed-thumbnails`

> Also, when you download the audio from a video with subtitles using -f 140, the final container is always m4a and --embed-subs does not change the container. This is the correct and expected behavior. After this change, --embed-thumbnail no longer behaves the same as --embed-subs.

Sounds like it should be a feature request to do this for subs. There have been similar request for `--embed-chapters` #822

---

I understand where you are coming from, but I disagree that this is an "an unexpected and surprising behavior" and think the current behavior is the better default
