### ISSUE TITLE
Use of datetime.strptime can crash runtime in an embedded environment

### ISSUE THREAD

**Issue by fbacher** [yt-dlp/yt-dlp#2064]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2021.12.01**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

The problem is a known Python embedded problem, but there are no resources to fix it at this time. The problem ONLY shows up when embedded python is used, so most users are not affected by this problem. However, a workaround is easy to implement and I think worth doing.

Kodi python plugins run in an embedded runtime. A long time Python bug (https://bugs.python.org/issue27400) results in the runtime crashing if datetime.strptime is initialized multiple times. 
Therefore, if Kodi launches an application which uses datetime.strptime (such as one that uses yt-dlp) more than once, then Kodi crashes. 

It would help if yt-dlp would switch from using datetime.datetime.strptime to time.strptime, as documented in issue27400. Of course this does not guarantee that used libs won't hit this problem. There is a hack solution for that, but I don't think that should be in yt-dlp, but rather the using application. The hack can have some undesirable side-effects.

An alternative solution is for whatever Kodi plugin provides the yt-dlp support to modify that copy of yt-dlp to make and maintain these changes in it's copy.

### Verbose log

```shell
No log since this is a workaround for a known embedded python problem
```

**Comment by Ashish0804** [comment]
> An alternative solution is for whatever Kodi plugin provides the yt-dlp support to modify that copy of yt-dlp to make and maintain these changes in it's copy.

dlp doesn't maintain any official kodi plugins. Ask the devs of that plugin to do so.
As of changing all the instances of datetime, it's a gigantic task and will cause more issues than it will fix.

**Comment by pukkandan** [comment]
As I understand, the issue is not with `strptime` in particular, but in `datetime` module as a whole. And it is not practical for us to completely ditch that module.

So what exactly are you asking us to do about it?
