### ISSUE TITLE
Add interactive "prompt for format" option

### ISSUE THREAD

**Issue by smithfred** [yt-dlp/yt-dlp#2065]
### Checklist

- [X] I'm reporting a feature request
- [X] I've verified that I'm running yt-dlp version **2021.12.01**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

A lot of the time I find myself running yt-dlp twice in succession:

```bash
yt-dlp <url> -F
# Manually check format options
yt-dlp <url> -f <format-spec>
```

Though yt-dlp has various automatic format selection options, there are frequently cases where manually inspecting format information is needed to avoid a poor-quality downloaded video.

For example, I usually prefer VP9 video over AVC, but sometimes the former has been far too-heavily compressed (anything significantly below about 2/3 of the size of the latter) and as a result the quality is noticeably worse.

So to handle cases like this, I usually manually check for some sites.

An option like `--prompt-for-format` would be great in this case, that did something similar to:

```bash
yt-dlp <url> -F && read -rp 'Format? ' && yt-dlp <url> -f "$REPLY"
```

**Comment by Ashish0804** [comment]
I don't think this is in scope of dlp.
This should be handled by external scripts.

**Comment by smithfred** [comment]
Is there a reason it would be specifically out of scope?

**Comment by smithfred** [comment]
Additionally, implementing the feature properly as an external wrapper script would require codifying all of yt-dlp's flags in the wrapper script, to be able to pick out the video URL and correctly pass all of the remaining flags through to yt-dlp on the second pass. For example: `yt-dlp-prompt --no-mtime <url> --exec foo` would need to know `--no-mtime` is a boolean flag, `--exec` takes a value, etc., to parse the flags/vals and robustly find the param. that isn't a value for a flag, i.e. the URL.
