### ISSUE TITLE
Unknown Problem Pls help

### ISSUE THREAD

**Issue by Bananaxp** [yt-dlp/yt-dlp#2067]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2021.12.01**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

Since youtubes latest update a few days ago, youtube links dont play anymore and i cant seem to figure out exatcly why. pls help

### Verbose log

```shell
20.12 23:24:08 [Bot] [debug] Encodings: locale UTF-8, fs utf-8, out utf-8 (No ANSI), err utf-8 (No ANSI), pref UTF-8
20.12 23:24:08 [Bot] [debug] yt-dlp version 2021.12.01 [91f071af6]
20.12 23:24:08 [Bot] [debug] Python version 3.9.7 (CPython 64bit) - Linux-4.4.232-1.el7.elrepo.x86_64-x86_64-with-glibc2.27
20.12 23:24:08 [Bot] [debug] exe versions: ffmpeg 3.4.8, ffprobe 3.4.8
20.12 23:24:08 [Bot] [debug] Optional libraries: Cryptodome, keyring, mutagen, sqlite, websockets
20.12 23:24:08 [Bot] [debug] Proxy map: {}
20.12 23:24:08 [Bot] Starting the download of the url
20.12 23:24:09 [Bot] [debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=60hq1KtQPfA
20.12 23:24:09 [Bot] [youtube] 60hq1KtQPfA: Downloading webpage
20.12 23:24:10 [Bot] [youtube] 60hq1KtQPfA: Downloading android player API JSON
20.12 23:24:10 [Bot] [debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
20.12 23:24:10 [Bot] [debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
20.12 23:24:10 [Bot] [debug] Default format spec: bestvideo*+bestaudio/best
20.12 23:24:10 [Bot] Url is found
20.12 23:24:10 [Bot] PRINTING THE *INFO
20.12 23:24:10 [Bot] ,id,title,formats,thumbnails,thumbnail,description,upload_date,uploader,uploader_id,uploader_url,channel_id,channel_url,duration,view_count,average_rating,age_limit,webpage_url,categories,tags,playable_in_embed,is_live,was_live,live_status,release_timestamp,chapters,like_count,channel,availability,__post_extractor,original_url,webpage_url_basename,extractor,extractor_key,playlist,playlist_index,display_id,duration_string,requested_subtitles,__has_drm,requested_formats,format,format_id,ext,protocol,language,format_note,filesize_approx,tbr,width,height,resolution,fps,dynamic_range,vcodec,vbr,stretched_ratio,acodec,abr,asr,epoch
20.12 23:24:10 [Bot] https://www.youtube.com/watch?v=60hq1KtQPfA < -- This is the webpageurl
20.12 23:24:10 [Bot] https://i.ytimg.com/sb/60hq1KtQPfA/storyboard3_L0/default.jpg?sqp=-oaymwENSDfyq4qpAwVwAcABBqLzl_8DBgi2meCNBg==&sigh=rs$AOn4CLB64m9NLiN3FyfPb4Vb40YavDGEhA < -- This is the url
20.12 23:24:10 [Bot] [https @ 0x55f920acf560] Unable to parse 'VISITOR_INFO1_LIVE=; Domain=.youtube.com; Expires=Tue, 26-Mar-2019 22:24:10 GMT; Path=/; Secure; HttpOnly; SameSite=none'
20.12 23:24:10 [Bot] https://www.youtube.com/watch?v=60hq1KtQPfA: Invalid data found when processing input
```

**Comment by MinePlayersPE** [comment]
> 20.12 23:24:10 [Bot] https://i.ytimg.com/sb/60hq1KtQPfA/storyboard3_L0/default.jpg?sqp=-oaymwENSDfyq4qpAwVwAcABBqLzl_8DBgi2meCNBg==&sigh=rs$AOn4CLB64m9NLiN3FyfPb4Vb40YavDGEhA < -- This is the url
20.12 23:24:10 [Bot] [https @ 0x55f920acf560] Unable to parse 'VISITOR_INFO1_LIVE=; Domain=.youtube.com; Expires=Tue, 26-Mar-2019 22:24:10 GMT; Path=/; Secure; HttpOnly; SameSite=none'

How exactly are you getting the format URL and passing it to your ffmpeg bot? Because it seems like you're passing the first `formats` entry (which afaik is the worst format) instead of using `requested_formats` (but that doesn't really explain the ffmpeg error either)
