### ISSUE TITLE
[How to] MPV + yt-dlp + SponsorBlock

### ISSUE THREAD

**Issue by ObsessedHacker** [yt-dlp/yt-dlp#2068]
### Checklist

- [X] I'm asking a question and not reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

I'm using MPV with yt-dlp and I want to use [SponsorBlock](https://github.com/yt-dlp/yt-dlp#sponsorblock-options), because yt-dlp has support for `poi_highlight` which no other script of SponsorBlock has.
I did read it, but I did not understand which command to put in `mpv.conf`, I tried to put `sponsorblock-mark all`, but it doesn't work.
I want it to mark and skip all.

**Comment by pukkandan** [comment]
You can't. mpv does not use yt-dlp's sponsorblock functionality. It only uses our extractor to get the video URL. If mpv devs want to support this feature and there is some change we can make to help, feel free to contact us

**Comment by samyak039** [comment]
hey, correct me if I'm wrong, the chapters are being transferred to mpv also, so cannot you just transfer sponsorblock timing as chapter to mpv ??

**Comment by pukkandan** [comment]
That will mark the chapters, but not skip them

**Comment by lamyergeier** [comment]
@pukkandan  Can you confirm if I add the following to my mpv.conf neither the chapters are marked nor skipped:

```bash
cat mpv.conf

ytdl-raw-options=ignore-config=,sub-lang='en',write-sub=,write-auto-sub=,sponsorblock-mark=default,sponsorblock-remove=default
```

**Comment by jvschiavo** [comment]
> That will mark the chapters, but not skip them

Hi, I'd like to have the sponsorblock chapters marked (not skipped) for mpv to see. Is there a way to achieve that right now?
