### ISSUE TITLE
[Site Request] RAI 1080p 

### ISSUE THREAD

**Issue by albino1** [yt-dlp/yt-dlp#207]
## Checklist

- [X] I'm reporting a site feature request
- [X] I've verified that I'm running yt-dlp version **2021.03.24.1**
- [X] I've searched the bugtracker for similar site feature requests including closed ones

## Description

This is really more of a feature request to merge an already existing really great and useful pull request by @nixxo over on the original youtube-dl repository:

https://github.com/ytdl-org/youtube-dl/pull/27990

This allows for direct MP4 files from the Italian site RAI, as well as the ability to get the 1080p version as well.

Here's the current output of `--list-formats` with yt-dlp 2021.03.24 using the current `rai.py`:

```
yt-dlp-2021.03.24.exe --list-formats https://www.raiplay.it/video/2021/03/Leonardo-S1E1-b5703b02-82ee-475a-85b6-c9e4a8adf642.html
[RaiPlay] b5703b02-82ee-475a-85b6-c9e4a8adf642: Downloading video JSON
[RaiPlay] b5703b02-82ee-475a-85b6-c9e4a8adf642: Downloading XML metadata for platform mon
[RaiPlay] b5703b02-82ee-475a-85b6-c9e4a8adf642: Downloading m3u8 information
[RaiPlay] b5703b02-82ee-475a-85b6-c9e4a8adf642: Downloading XML metadata for platform flash
[RaiPlay] b5703b02-82ee-475a-85b6-c9e4a8adf642: Downloading XML metadata for platform native
[info] Available formats for b5703b02-82ee-475a-85b6-c9e4a8adf642:
ID                       EXT RESOLUTION |   TBR PROTO  | VCODEC    VBR ACODEC   ABR NOTE
------------------------ --- ---------- - ----- ------ - ------- ----- ------- ---- ------------------
hls-aac-Audiodescrizione mp4 audio only |       m3u8_n |               unknown      [Audiodescrizione]
hls-aac-Italiano         mp4 audio only |       m3u8_n |               unknown      [Italiano]
hls-1200                 mp4 736x414    | 1288k m3u8_n | unknown 1288k unknown   0k
hls-1800                 mp4 1024x576   | 1758k m3u8_n | unknown 1758k unknown   0k
hls-2400                 mp4 1280x720   | 2344k m3u8_n | unknown 2344k unknown   0k

```

And here is the `--list-formats` with that updated `rai.py` fix:

```
python -m youtube_dl --list-formats https://www.raiplay.it/video/2021/03/Leonardo-S1E1-b5703b02-82ee-475a-85b6-c9e4a8adf642.html
[RaiPlay] b5703b02-82ee-475a-85b6-c9e4a8adf642: Downloading video JSON
[RaiPlay] b5703b02-82ee-475a-85b6-c9e4a8adf642: Downloading XML metadata for platform mon
[RaiPlay] b5703b02-82ee-475a-85b6-c9e4a8adf642: Downloading m3u8 information
[RaiPlay] b5703b02-82ee-475a-85b6-c9e4a8adf642: Downloading XML metadata for platform flash
[RaiPlay] b5703b02-82ee-475a-85b6-c9e4a8adf642: Downloading XML metadata for platform native
[info] Available formats for b5703b02-82ee-475a-85b6-c9e4a8adf642:
format code               extension  resolution note
hls-aac-Audiodescrizione  mp4        audio only [Audiodescrizione]
hls-aac-Italiano          mp4        audio only [Italiano]
hls-1200                  mp4        736x414    1288k
https-1200                mp4        736x414    1288k
hls-1800                  mp4        1024x576   1758k
https-1800                mp4        1024x576   1758k
hls-2400                  mp4        1280x720   2344k
https-2400                mp4        1280x720   2344k
https-3600                mp4        1440x810   3600k
https-5000                mp4        1920x1080  5000k  (best)
```

As you can see with the fix you get several better options, including access to `https-5000` which gives you the full 1080p version.

If taking the pull request from youtube-dl isn't kosher, then maybe @nixxo would be willing to do a new PR over here on yt-dlp.

Thanks so much!

**Comment by pukkandan** [comment]
Pinging @nixxo

**Comment by nixxo** [comment]
yes, I have it already in my local repo because I was trying to improve it. I'll make a PR so you can give a look as well.

**Comment by albino1** [comment]
@nixxo thanks for looking into this!

I tried the `rai.py` from your pull request (https://github.com/yt-dlp/yt-dlp/pull/208) and was able to get 1080p for most things, but interestingly not others even within the same season.  Using Season 1 of Tutto può succedere for example:

https://www.raiplay.it/programmi/tuttopuosuccedere/episodi/stagione-1

Episode 2, 3, 4, etc all give me the `https-5000` 1080p listing, but Episode 1 only gives me `https-3200` as the max which is 1440x810.  It's possible the 1080p just doesn't exist for that episode, but it seems weird to have the pilot episode be the one with the lowest resolution.  Any thoughts?

**Comment by nixxo** [comment]
yeah, unfortunately querying the mediaserver in this way is not very reliable.

I'm starting to think that the best solution is to go back to my initial setup and manually create an array with a bunch of url and sending HEAD request to check which one gives not a 404 error.

**Comment by albino1** [comment]
I'm not sure if I'm jumping the gun by testing the changes you made only a couple of hours ago, but it already works significantly better.  There's still a couple I found that don't list all of the available formats, but the ones I did find were able to successfully download the `https-5000` version with no 404 errors.   I haven't found anything that shows `https-10000` to test those yet with, but the other formats work fine.

If you want some example URLs where `--list-formats` doesn't show them all, let me know as I wrote some down.  Great work either way!

**Comment by nixxo** [comment]
thank you for testing.

yes, report any anomaly that you find, it, will help imprive the extractor.

**Comment by albino1** [comment]
Great!  I grabbed your latest update to do some testing on the previous files I had identified.

Using the same show as before as the example, Tutto può succedere, Season 1 and Season 2 show all of the available formats so far as I can tell, but there are a couple of random episodes in Season 3 which don't.

Here's S03E02 which shows all of the formats:

```
yt_dlp --list-formats "https://www.raiplay.it/video/2018/06/Tutto-puo-succedere-S3E2-a3a2e324-8643-4192-b80b-a9263bea2463.html"
[RaiPlay] a3a2e324-8643-4192-b80b-a9263bea2463: Downloading video JSON
[RaiPlay] a3a2e324-8643-4192-b80b-a9263bea2463: Downloading XML metadata for platform mon
[RaiPlay] a3a2e324-8643-4192-b80b-a9263bea2463: Downloading m3u8 information
[RaiPlay] a3a2e324-8643-4192-b80b-a9263bea2463: Downloading XML metadata for platform flash
[RaiPlay] a3a2e324-8643-4192-b80b-a9263bea2463: Downloading XML metadata for platform native
[info] Available formats for a3a2e324-8643-4192-b80b-a9263bea2463:
ID         EXT RESOLUTION |   TBR PROTO  | VCODEC       VBR ACODEC     ABR
---------- --- ---------- - ----- ------ - ---------- ----- --------- ----
https-250  mp4 352x198    |  250k https  | unknown     250k unknown     0k
https-400  mp4 512x288    |  400k https  | unknown     400k unknown     0k
https-700  mp4 512x288    |  700k https  | unknown     700k unknown     0k
hls-1265   mp4 736x414    | 1265k m3u8_n | avc1.77.30 1265k mp4a.40.2   0k
https-1200 mp4 736x414    | 1265k https  | avc1.77.30 1265k mp4a.40.2   0k
hls-1893   mp4 1024x576   | 1893k m3u8_n | avc1.77.30 1893k mp4a.40.2   0k
https-1800 mp4 1024x576   | 1893k https  | avc1.77.30 1893k mp4a.40.2   0k
hls-2528   mp4 1280x720   | 2528k m3u8_n | avc1.77.30 2528k mp4a.40.2   0k
https-2400 mp4 1280x720   | 2528k https  | avc1.77.30 2528k mp4a.40.2   0k
https-3200 mp4 1440x810   | 3200k https  | unknown    3200k unknown     0k
https-5000 mp4 1920x1080  | 5000k https  | unknown    5000k unknown     0k
```

And then here's S03E01:

```
yt_dlp --list-formats "https://www.raiplay.it/video/2018/06/Tutto-puo-succedere-S3E1-ea643f2f-3ccc-4970-bab4-4294f66d6257.html"
[RaiPlay] ea643f2f-3ccc-4970-bab4-4294f66d6257: Downloading video JSON
[RaiPlay] ea643f2f-3ccc-4970-bab4-4294f66d6257: Downloading XML metadata for platform mon
[RaiPlay] ea643f2f-3ccc-4970-bab4-4294f66d6257: Downloading m3u8 information
[RaiPlay] ea643f2f-3ccc-4970-bab4-4294f66d6257: Downloading XML metadata for platform flash
[RaiPlay] ea643f2f-3ccc-4970-bab4-4294f66d6257: Downloading XML metadata for platform native
[info] Available formats for ea643f2f-3ccc-4970-bab4-4294f66d6257:
ID         EXT RESOLUTION |   TBR PROTO  | VCODEC       VBR ACODEC     ABR
---------- --- ---------- - ----- ------ - ---------- ----- --------- ----
hls-1892   mp4 1024x576   | 1892k m3u8_n | avc1.77.30 1892k mp4a.40.2   0k
https-1800 mp4 1024x576   | 1892k https  | avc1.77.30 1892k mp4a.40.2   0k
```

Similarly, S03E04, E05 and E14 also only show `https-1800`:

https://www.raiplay.it/video/2018/06/Tutto-puo-succedere-S3E4-46618af8-95df-4297-aa66-e2ec745ee9d4.html
https://www.raiplay.it/video/2018/06/Tutto-puo-succedere-S3E5-822d4be2-8c8b-4e6a-8d66-b056f9e6b535.html
https://www.raiplay.it/video/2018/06/Tutto-puo-succedere-S3E14-33aef879-34fa-4338-8d06-01b6665a36aa.html

However, the other 12 episodes show all of the formats including the 1080p `https-5000` one, so I don't know why those episodes don't work.

As a side note, Season 2 of La strada di casa now has 1080p `https-5000` with your extractor, but I noticed that Season 1 only has a pretty bad 720x404 `https-1800` format:

https://www.raiplay.it/video/2017/11/La-strada-di-casa--S1E1-d3652f8b-a7f8-453e-8f45-9654ff1411ad.html

I don't think it's the extractor's fault because that's the results I get in every version of the extractor, I only mention it in case it's related somehow.

**Comment by nixxo** [comment]
![x2scrap](https://user-images.githubusercontent.com/426049/114312329-9d7e5f00-9af2-11eb-9122-53d011cc3682.jpg)
![x2scrap2](https://user-images.githubusercontent.com/426049/114312332-9eaf8c00-9af2-11eb-9573-131909697b64.jpg)

**Comment by albino1** [comment]
Ah, I didn't even think to check that.  Weird screw up by RAI, but the good news is that your extractor is working as intended.

**Comment by pukkandan** [comment]
Closed by #208

**Comment by albino1** [comment]
Sorry to bump this, but I'm not sure it's working as well as one of the previous `rai.py` extractors that @nixxo did.

Using the current version of yt-dlp on a brand new show which just appeared on RAI recently if I use yt-dlp here's what I get:

```
yt-dlp.exe --version
2021.04.11

yt-dlp.exe --list-formats https://www.raiplay.it/video/2021/04/Nudes-S1E1-Vittorio-1-10e88844-3790-425b-905d-93e0d1aecb25.html

[RaiPlay] 10e88844-3790-425b-905d-93e0d1aecb25: Downloading video JSON
[RaiPlay] 10e88844-3790-425b-905d-93e0d1aecb25: Downloading XML metadata for platform mon
[RaiPlay] 10e88844-3790-425b-905d-93e0d1aecb25: Downloading m3u8 information
[RaiPlay] 10e88844-3790-425b-905d-93e0d1aecb25: Downloading XML metadata for platform flash
[RaiPlay] 10e88844-3790-425b-905d-93e0d1aecb25: Downloading XML metadata for platform native
[info] Available formats for 10e88844-3790-425b-905d-93e0d1aecb25:
ID                       EXT RESOLUTION |   TBR PROTO  | VCODEC    VBR ACODEC   ABR NOTE
------------------------ --- ---------- - ----- ------ - ------- ----- ------- ---- ------------------
hls-aac-Audiodescrizione mp4 audio only |       m3u8_n |               unknown      [Audiodescrizione]
hls-aac-Italiano         mp4 audio only |       m3u8_n |               unknown      [Italiano]
hls-1200                 mp4 736x414    | 1288k m3u8_n | unknown 1288k unknown   0k
hls-1800                 mp4 1024x576   | 1758k m3u8_n | unknown 1758k unknown   0k
hls-2400                 mp4 1280x720   | 2344k m3u8_n | unknown 2344k unknown   0k
```

And now here's what I get with one of the older `rai.py` extractors I was testing, which I think might have been the original PR on the youtube-dl repository:

```
youtube-dl.exe --list-formats https://www.raiplay.it/video/2021/04/Nudes-S1E1-Vittorio-1-10e88844-3790-425b-905d-93e0d1aecb25.html

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '--list-formats', 'https://www.raiplay.it/video/2021/04/Nudes-S1E1-Vittorio-1-10e88844-3790-425b-905d-93e0d1aecb25.html']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2019.07.16
[debug] Python version 3.9.0 (CPython) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg N-92926-g2d580d727c
[debug] Proxy map: {}
[RaiPlay] 10e88844-3790-425b-905d-93e0d1aecb25: Downloading video JSON
[RaiPlay] 10e88844-3790-425b-905d-93e0d1aecb25: Downloading XML metadata for platform mon
[RaiPlay] 10e88844-3790-425b-905d-93e0d1aecb25: Downloading m3u8 information
[RaiPlay] 10e88844-3790-425b-905d-93e0d1aecb25: Downloading XML metadata for platform flash
[RaiPlay] 10e88844-3790-425b-905d-93e0d1aecb25: Downloading XML metadata for platform native
[info] Available formats for 10e88844-3790-425b-905d-93e0d1aecb25:
format code               extension  resolution note
hls-aac-Audiodescrizione  mp4        audio only [Audiodescrizione]
hls-aac-Italiano          mp4        audio only [Italiano]
hls-1200                  mp4        736x414    1288k
https-1200                mp4        736x414    1288k
hls-1800                  mp4        1024x576   1758k
https-1800                mp4        1024x576   1758k
hls-2400                  mp4        1280x720   2344k
https-2400                mp4        1280x720   2344k
https-3600                mp4        1440x810   3600k
https-5000                mp4        1920x1080  5000k  (best)
```

Here's the `rai.py` that shows the `https-5000 ` option:

https://gist.github.com/albino1/2908dac3604f5cbadfe63b456d49170e

Let me know if you want me to test anything else.

**Comment by pukkandan** [comment]
@albino1 I havent made a release yet after merging this. Try with the git master

**Comment by albino1** [comment]
Ah, I saw it was merged and didn't think to check which branch.  I'll wait until it officially releases and then test it.  Sorry about that!

**Comment by pukkandan** [comment]
@albino1 Just letting you know that this is now in the latest release

**Comment by albino1** [comment]
Works great, thanks!
