### ISSUE TITLE
[Youtube] live_chat extraction gives up after a single failed try without retrying

### ISSUE THREAD

**Issue by auroraanon38** [yt-dlp/yt-dlp#2071]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2021.12.01**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Worldwide/USA

### Description

When running the following command on the source: `python3 $HOME/yt-dlp/yt_dlp/__main__.py --prefer-free-formats --embed-thumbnail --add-metadata --write-comments --all-subs --embed-subs -i https://www.youtube.com/watch?v=ySJslFpo91U`, the `live_chat` extraction gives up on first error and doesn't retry the connection.

It is the only extractor element which doesn't seem to retry after a failure. I think it should also retry much like all the other parts.

The logs have been truncated to show only the parts pertaining to live chat, as nothing gets printed out about it besides the failure of the connection and the inclusion being skipped at embed-time.

Presence of the merged downloaded video or absence of it makes no difference on the result. The same failure happens in all cases for me.

### Verbose log

```shell
[info] Writing video subtitles to: [WEST OF LOATHING] M'HOWDY [ySJslFpo91U].live_chat.json
[debug] Invoking downloader on "https://www.youtube.com/watch?v=ySJslFpo91U"
[youtube_live_chat] Downloading live chat
[youtube_live_chat] Total fragments: unknown (live)
[download] Destination: [WEST OF LOATHING] M'HOWDY [ySJslFpo91U].live_chat.json
[download] 13.76MiB at 409.24KiB/s (00:58) (frag 61)WARNING: Unable to download video subtitles for 'live_chat': Remote end closed connection without response
[info] Downloading video thumbnail 45 ...
[info] Writing video thumbnail 45 to: [WEST OF LOATHING] M'HOWDY [ySJslFpo91U].webp
[info] Writing video metadata as JSON to: [WEST OF LOATHING] M'HOWDY [ySJslFpo91U].info.json
WARNING: webm doesn't support embedding a thumbnail, mkv will be used
[download] [WEST OF LOATHING] M'HOWDY [ySJslFpo91U].mkv has already been downloaded
WARNING: Skipping embedding live_chat subtitle because the file is missing
[debug] ffprobe command line: ffprobe -hide_banner -show_format -show_streams -print_format json 'file:[WEST OF LOATHING] M'"'"'HOWDY [ySJslFpo91U].mkv'
[Metadata] Adding metadata to "[WEST OF LOATHING] M'HOWDY [ySJslFpo91U].mkv"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:[WEST OF LOATHING] M'"'"'HOWDY [ySJslFpo91U].mkv' -map 0 -dn -c copy -metadata 'title=[WEST OF LOATHING] M'"'"'HOWDY' -metadata date=20210903 -metadata 'description=[Twitter]
```

**Comment by pukkandan** [comment]
> The logs have been truncated to show only the parts pertaining to live chat, as nothing gets printed out about it besides the failure of the connection and the inclusion being skipped at embed-time.

Post the ENTIRE **verbose** log like the template ask you

**Comment by coletdjnz** [comment]
I believe https://github.com/yt-dlp/yt-dlp/pull/3065 will fix this
