### ISSUE TITLE
yt-dld with --split-chapters does not support filename patterns in -o option

### ISSUE THREAD

**Issue by RaviV1** [yt-dlp/yt-dlp#2078]
### Checklist

- [X] I'm reporting a feature request
- [X] I've verified that I'm running yt-dlp version **2021.12.01**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

I would like when I download large files which is a combination of the various chapters - to include the resolution and duration for the chapters
 This gives the filenames correctly !! 
--restrict-filenames -f "bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best" -o "%(uploader)s/%(playlist_title)s--%(playlist_id)s/%(playlist_index)03d--%(title)s--%(upload_date)s--%(resolution)s--%(duration)06ds--%(id)s.%(ext)s" 

But I would like the same pattern for
--restrict-filenames -f "bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best" -o "%(uploader)s/%(playlist_title)s--%(playlist_id)s/%(playlist_index)03d--%(title)s--%(upload_date)s--%(resolution)s--%(duration)06ds--%(id)s.%(ext)s"  --split-chapters

**Comment by pukkandan** [comment]
The split chapters use a separate output template. Use something like `-o "chapter:%(title)s - %(section_title)s.%(ext)s"`. See docs for more fields that are available for the `chapter:` prefix
