### ISSUE TITLE
Termux can't lock archive files

### ISSUE THREAD

**Issue by ComedyTomedy** [yt-dlp/yt-dlp#2080]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2021.12.01**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

When run on Termux with --download-archive, yt-dlp fails and exits with error when archive file exists. Otherwise it seems to create but not write the archive.

Android 11, Termux 0.117.

### Verbose log

```shell
$ touch example
$ yt-dlp -Uv --download-archive example https://youtube.com/
[debug] Command-line config: ['-Uv', '--download-archive', 'example', 'https://youtube.com/']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2021.12.01 [91f071af6]
[debug] Python version 3.10.0 (CPython 64bit) - Linux-4.14.190-perf-g6879b1d702f2-dirty-aarch64-with-libc
[debug] exe versions: ffmpeg 4.4.1 (setts), ffprobe 4.4.1
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] Loading archive file 'example'
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/yt-dlp", line 8, in <module>
    sys.exit(main())
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/yt_dlp/__init__.py", line 823, in main
    _real_main(argv)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/yt_dlp/__init__.py", line 784, in _real_main
    with YoutubeDL(ydl_opts) as ydl:
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 670, in __init__
    preload_download_archive(self.params.get('download_archive'))
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 660, in preload_download_archive
    with locked_file(fn, 'r', encoding='utf-8') as archive_file:
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/yt_dlp/utils.py", line 3594, in __enter__
    _lock_file(self.f, exclusive)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/yt_dlp/utils.py", line 3571, in _lock_file
    fcntl.flock(f, fcntl.LOCK_EX if exclusive else fcntl.LOCK_SH)
OSError: [Errno 38] Function not implemented
```

**Comment by Zirro** [comment]
A bit of searching revealed another user with the same issue: https://old.reddit.com/r/youtubedl/comments/ohz2op/downloadarchive_not_working_with_termux/

It would seem that Android 11 includes security updates that limit which actions an app can perform on certain paths by default. There's a post with a work-around in the reddit thread above, and more information/suggestions on the Termux wiki: https://wiki.termux.com/wiki/FAQ#How_can_I_access_device_storage_with_Termux

**Comment by pukkandan** [comment]
Does the download work fine? If so, seems "scoped storage" is allowing us to write files, but not lock them. We could try to make the locking non-fatal. But I don't have an android 11 device to test. So a PR will be needed

Tangentially related: https://github.com/yt-dlp/yt-dlp/pull/1066

**Comment by ComedyTomedy** [comment]
@Zirro fantastic, well found :) didn't occur to me to search outside of here.

@pukkandan Yes, the download works, and i suspect that's exactly what's happening, it feels right. 

As a test, is there a function I can call in the Python repl to attempt to lock a file and see if it fails? Maybe something in fcntl? I'm not a Python hacker, but can do that much.
