### ISSUE TITLE
string slicing in the output not working correctly

### ISSUE THREAD

**Issue by koryphaee** [yt-dlp/yt-dlp#2081]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2021.12.01**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

When using string slicing like this `-o '%(id.0:2)s/video.mp4'` dashes are incorrectly converted to underscores.
For example: `yt-dlp --get-filename https://www.youtube.com/watch?v=--2aGD6Rpss -o '%(id.1)c/%(id)s'` returns `_/--2aGD6Rpss` instead of `-/--2aGD6Rpss`.

This behaviour is also not very consistent, lets assume the ID `---abc`:

- `%(id)c` returns `-` which is correct
- `%(id.0)c` returns `_` which is not correct
- `%(id.0)s` returns `_` which is not correct
- `%(id.0:2)s` returns `_-` which is partly correct

I have tried both `--no-restrict-filenames` and `--no-windows-filenames` to no avail.

### Verbose log

```shell
yt-dlp --get-filename --no-restrict-filenames --no-windows-filenames https://www.youtube.com/watch?v=--2aGD6Rpss -o '%(id.1)c/%(id)s' -Uv
[debug] Command-line config: ['--get-filename', '--no-restrict-filenames', '--no-windows-filenames', 'https://www.youtube.com/watch?v=--2aGD6Rpss', '-o', '%(id.1)c/%(id)s', '-Uv']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2021.12.01 [91f071af6] (zip)
[debug] Python version 3.8.10 (CPython 64bit) - Linux-5.10.16.3-microsoft-standard-WSL2-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4
[debug] Optional libraries: keyring, sqlite
[debug] Proxy map: {}
Latest version: 2021.12.01, Current version: 2021.12.01
yt-dlp is up to date (2021.12.01)
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=--2aGD6Rpss
[youtube] --2aGD6Rpss: Downloading webpage
[youtube] --2aGD6Rpss: Downloading android player API JSON
[youtube] --2aGD6Rpss: Downloading player 8da38e9a
[debug] Saving youtube-nsig.8da38e9a to cache
[debug] [youtube] Decrypted nsig onrb5ItPJqFFYowt => 5WQSN9ZH84rr7Q
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] --2aGD6Rpss: Downloading 1 format(s): 303+251
_/--2aGD6Rpss
```

**Comment by pukkandan** [comment]
uh, another side effect of youtube-dl trying to be over-smart when sanitizing filenames. Let me see how to fix it

**Comment by pukkandan** [comment]
Fixed in https://github.com/yt-dlp/yt-dlp/commit/e0fd95737d1a3c4a2bfb470c5408a396c8545ca5

**Comment by koryphaee** [comment]
Thank you so much for quick fix
