### ISSUE TITLE
Subtitles and Thumbnails are downloaded multiple times when output template has format_id specified

### ISSUE THREAD

**Issue by barkoder** [yt-dlp/yt-dlp#2082]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2021.12.01**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

`yt-dlp -wv -o "%(uploader)s-%(upload_date)s-%(title)s-%(id)s.f%(format_id)s.%(ext)s" --restrict-filenames --write-thumbnail https://www.youtube.com/watch?v=0UyXSJhbFHA --write-sub en --convert-subs srt -f 18,22,140,251`

Unless I'm mistaken(please correct me if I am), I don't know of any youtube/vimeo/dailymotion/twitch or any streaming video website's webpage, where subtitles and thumbnails change depending on the format selected.

The same thumbnails and subtitles are being re-downloaded for each `-f` format_id .

Subtitles and thumbnails should only be downloaded once regardless of how many `-f` I query.

Thank you.

### Verbose log

```shell
$ yt-dlp -wv -o "%(uploader)s-%(upload_date)s-%(title)s-%(id)s.f%(format_id)s.%(ext)s" --restrict-filenames --write-thumbnail https://www.youtube.com/watch?v=0UyXSJhbFHA --write-sub en --convert-subs srt -f 18,22,140,251
[debug] yt-dlp version 2021.12.01 [91f071a] (py2exe)
[debug] Optional libraries: mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=0UyXSJhbFHA
[youtube] 0UyXSJhbFHA: Downloading webpage
[youtube] 0UyXSJhbFHA: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[debug] Downloading subtitles: en-US
[info] 0UyXSJhbFHA: Downloading 4 format(s): 18, 22, 140, 251
[info] Writing video subtitles to: vlogbrothers-20211207-Reading_Hank_s_Decade-Old_Tweets-0UyXSJhbFHA.f18.en-US.vtt
[debug] Invoking downloader on "https://www.youtube.com/api/timedtext?v=0UyXSJhbFHA<REDACTEDREDACTEDREDACTEDREDACTEDREDACTEDREDACTEDREDACTED>&lang=en-US&fmt=vtt"
[download] Destination: vlogbrothers-20211207-Reading_Hank_s_Decade-Old_Tweets-0UyXSJhbFHA.f18.en-US.vtt
[download] 100% of 5.74KiB in 00:01
[info] Downloading video thumbnail 41 ...
[info] Writing video thumbnail 41 to: vlogbrothers-20211207-Reading_Hank_s_Decade-Old_Tweets-0UyXSJhbFHA.f18.webp
[SubtitlesConvertor] Converting subtitles
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:vlogbrothers-20211207-Reading_Hank_s_Decade-Old_Tweets-0UyXSJhbFHA.f18.en-US.vtt" -f srt "file:vlogbrothers-20211207-Reading_Hank_s_Decade-Old_Tweets-0UyXSJhbFHA.f18.en-US.srt"
Deleting original file vlogbrothers-20211207-Reading_Hank_s_Decade-Old_Tweets-0UyXSJhbFHA.f18.en-US.vtt (pass -k to keep)
[debug] Invoking downloader on "https://LONG_GOOGLEVIDEO_URL_THAT_I_HAVE_REDACTED"
[download] Destination: vlogbrothers-20211207-Reading_Hank_s_Decade-Old_Tweets-0UyXSJhbFHA.f18.mp4
.
.
.
AND SO ON...BASICALLY RE-DOWNLOADS THUMBNAILS AND SUBTITLES ONCE FOR EACH -f I SPECIFY.
```

**Comment by pukkandan** [comment]
That is expected behavior. Otherwise what would the `format_id` in the subtitle's filename be? You can set a separate output template for the subs/thumbnails

**Comment by barkoder** [comment]
Can't `format_id` and other non-subtitle specific,non-thumbnail-specifc output template fields be ignored while writing subtitles and thumbnails?

Since it's the same thumbnails and subtitles being re-downloaded over and over?

Basically while writing subtitles it should just be `vlogbrothers-20211207-Reading_Hank_s_Decade-Old_Tweets-0UyXSJhbFHA.vtt`

**Comment by pukkandan** [comment]
> You can set a separate output template for the subs/thumbnails
