### ISSUE TITLE
Output template to append filesize in GiB,MiB or KiB as shown in -F

### ISSUE THREAD

**Issue by barkoder** [yt-dlp/yt-dlp#2085]
### Checklist

- [X] I'm reporting a feature request
- [X] I've verified that I'm running yt-dlp version **2021.12.01**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

Basically a `%(pretty_filesize)s` output template field.

I know that `%(filesize)s` and `%(approx_filesize)s` exists.  
But I want the value that shows up in `-F` to show up in my filenames. I know that size is less precise but it's way more human-readable.

I'd like
`yt-dlp --get-filename --restrict-filenames -f 135 BaW_jenozKc -o "%(uploader)s-%(upload_date)s-%(title)s-%(id)s-%(pretty_filesize)s.%(ext)s"` 
to print
`Philipp_Hagemeister-20121002-youtube-dl_test_video_a-BaW_jenozKc-849.41KiB.mp4`

Or if I want `-f 22 BaW_jenozKc` then `%(pretty_filesize)s` should print its corresponding approx. filesize of `~1.82MiB` as shown in `-F` making the output file `Philipp_Hagemeister-20121002-youtube-dl_test_video_a-BaW_jenozKc-~1.82MiB.mp4`

Thanks.

**Comment by pukkandan** [comment]
With https://github.com/yt-dlp/yt-dlp/commit/e0fd95737d1a3c4a2bfb470c5408a396c8545ca5, you can do `%(filesize).2DiB`

**Comment by barkoder** [comment]
`%(filesize).2DiB` appears to give some sort of approximate size? Instead of the actual size as shown in `-F`?

Am I mistaken?

    $ yt-dlp -F FJSI7QTAt_o | grep 3840x2160
    313 webm  3840x2160   25 |    3.98GiB 8320k https | vp9         8320k video only              2160p, webm_dash

`f313` is `3.98GiB`. And the actual file size when downloaded is also `3.98GiB` as shown in `-F`.

However, when I do

    $ yt-dlp --print filename -f 313 FJSI7QTAt_o -o "%(filesize).2DiB"
    4.28GiB

`4.28GiB` is way off the actual size of `3.98GiB`.

It's not just `f313`. It's all formats.  
The disparity is wider when the video filesize is larger so I've used `f313` to illustrate.
But the `%(filesize).2DiB` for none of the formats match the correct size value as shown in `-F`.

Also for `-f 22`

    yt-dlp --print filename -f 22 FJSI7QTAt_o -o "%(filesize).2DiB"
    NoneiB

Instead of `~189.70MiB`.

**Comment by pukkandan** [comment]
The `D` prefix uses 1000 based suffix. This is why the filesize was appearing different from what you expected. In https://github.com/yt-dlp/yt-dlp/commit/abbeeebc4c20bc5c690d96c83e91e89effd04b81, I have now added `#D` to use 1024 instead.

For -f22, the `filesize` is not known, only the `filesize_approx` is. If you want to use either, you can use `filesize,filesize_approx` as the key

**Comment by barkoder** [comment]
Hey @pukkandan Thanks for the help but could you make it so that the decimals are not truncated? 

    yt-dlp --print filename -f 313 FJSI7QTAt_o -o "%(filesize)#DB"
    3GiB

which is almost ~1GB away from the actual size of 3.98GiB

I'd very much like the output to be 3.98GiB as shown in `-F`.

Thanks!

**Comment by pukkandan** [comment]
It accepts the same format as float. So just do `%(filesize)#.2DB`
