### ISSUE TITLE
Get all ids/titles/duration from playlists almost instantly possible?

### ISSUE THREAD

**Issue by barkoder** [yt-dlp/yt-dlp#2086]
### Checklist

- [X] I'm reporting a site feature request
- [X] I've verified that I'm running yt-dlp version **2021.12.01**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Example URLs

https://www.youtube.com/playlist?list=PLnQX-jgAF5pTkwtUuVpqS5tuWmJ-6ZM-Z

### Description

Is there a way for `yt-dlp` to have ids/titles/durations show up instantly?

[youtubedr(written in Go)](https://github.com/kkdai/youtube) is able to do it instantly(under ~1 second) upto a 100 videos in a playlist with `youtubedr list https://www.youtube.com/playlist?list=PLnQX-jgAF5pTkwtUuVpqS5tuWmJ-6ZM-Z`
Unfortunately it CAN only do a 100 and then it stops completely, even if the playlist has more videos :)

I know yt-dlp has `--get-id --get-title --get-duration`? But it is painfully slow compared to [`youtubedr list youtube_playlist_URL`](https://github.com/kkdai/youtube) Since yt-dlp appears to be doing it one URL at a time.

Is there a way to have it be instant?

If a yt-dlp user is only querying **--get-id**,**--get-title**,**--get-duration** et al(basically variables that are already available right on the playlist page), it would also partially help with #1399.

Only partially though, since If the user also requests `-F`, obviously that will require crawling the actual youtube "/watch" page and won't help with #1399.

But if it can be achieved in yt-dlp, it would be great and would save so much time.

Thanks.

**Comment by coletdjnz** [comment]
YouTube only serves 100 videos/page for playlists, so it has to download all the pages to get all the videos.

`--flat-playlist` is probably what you are looking for, this will speed things up in your situation.

**Comment by barkoder** [comment]
Thank you so very much @coletdjnz .
