### ISSUE TITLE
YT: --live-from-start hangs indefinitely after stream goes private

### ISSUE THREAD

**Issue by P-reducible** [yt-dlp/yt-dlp#2089]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2021.12.01**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Description

The show I was downloading was made private by the author at the end of the public stream.  (He does this every time).  Sadly, I didn't enable the --verbose flag, but here is what I got (see below). After the final "fragment not found" message, the program hung indefinitely until I interrupted it.  The stream went on for about 2-3 hours.

### Verbose log

```shell
[download] fragment not found; Skipping fragment 3951 ...
[download] Got server HTTP error: HTTP Error 403: Forbidden. Retrying fragment 3951 (attempt 1 of 10) ...
[download] Got server HTTP error: HTTP Error 403: Forbidden. Retrying fragment 3951 (attempt 2 of 10) ...
[download] Got server HTTP error: HTTP Error 403: Forbidden. Retrying fragment 3951 (attempt 3 of 10) ...
[download] Got server HTTP error: HTTP Error 403: Forbidden. Retrying fragment 3951 (attempt 4 of 10) ...
[download] Got server HTTP error: HTTP Error 403: Forbidden. Retrying fragment 3951 (attempt 5 of 10) ...
[download] Got server HTTP error: HTTP Error 403: Forbidden. Retrying fragment 3951 (attempt 6 of 10) ...
[download] Got server HTTP error: HTTP Error 403: Forbidden. Retrying fragment 3951 (attempt 7 of 10) ...
[download] Got server HTTP error: HTTP Error 403: Forbidden. Retrying fragment 3951 (attempt 8 of 10) ...
[download] Got server HTTP error: HTTP Error 403: Forbidden. Retrying fragment 3951 (attempt 9 of 10) ...
[download] Got server HTTP error: HTTP Error 403: Forbidden. Retrying fragment 3951 (attempt 10 of 10) ...
[download] fragment not found; Skipping fragment 3951 ...
[download] Got server HTTP error: HTTP Error 403: Forbidden. Retrying fragment 3952 (attempt 1 of 10) ...
[download] Got server HTTP error: HTTP Error 403: Forbidden. Retrying fragment 3952 (attempt 2 of 10) ...
[download] Got server HTTP error: HTTP Error 403: Forbidden. Retrying fragment 3952 (attempt 3 of 10) ...
[download] Got server HTTP error: HTTP Error 403: Forbidden. Retrying fragment 3952 (attempt 4 of 10) ...
[download] Got server HTTP error: HTTP Error 403: Forbidden. Retrying fragment 3952 (attempt 5 of 10) ...
[download] Got server HTTP error: HTTP Error 403: Forbidden. Retrying fragment 3952 (attempt 6 of 10) ...
[download] Got server HTTP error: HTTP Error 403: Forbidden. Retrying fragment 3952 (attempt 7 of 10) ...
[download] Got server HTTP error: HTTP Error 403: Forbidden. Retrying fragment 3952 (attempt 8 of 10) ...
[download] Got server HTTP error: HTTP Error 403: Forbidden. Retrying fragment 3952 (attempt 9 of 10) ...
[download] Got server HTTP error: HTTP Error 403: Forbidden. Retrying fragment 3952 (attempt 1 of 10) ...
[download] Got server HTTP error: HTTP Error 403: Forbidden. Retrying fragment 3952 (attempt 10 of 10) ...
[download] Got server HTTP error: HTTP Error 403: Forbidden. Retrying fragment 3952 (attempt 2 of 10) ...
[download] fragment not found; Skipping fragment 3952 ...
[download] Got server HTTP error: HTTP Error 403: Forbidden. Retrying fragment 3952 (attempt 3 of 10) ...
[download] Got server HTTP error: HTTP Error 403: Forbidden. Retrying fragment 3952 (attempt 4 of 10) ...
[download] Got server HTTP error: HTTP Error 403: Forbidden. Retrying fragment 3952 (attempt 5 of 10) ...
[download] Got server HTTP error: HTTP Error 403: Forbidden. Retrying fragment 3952 (attempt 6 of 10) ...
[download] Got server HTTP error: HTTP Error 403: Forbidden. Retrying fragment 3952 (attempt 7 of 10) ...
[download] Got server HTTP error: HTTP Error 403: Forbidden. Retrying fragment 3952 (attempt 8 of 10) ...
[download] Got server HTTP error: HTTP Error 403: Forbidden. Retrying fragment 3952 (attempt 9 of 10) ...
[download] Got server HTTP error: HTTP Error 403: Forbidden. Retrying fragment 3952 (attempt 10 of 10) ...
[download] fragment not found; Skipping fragment 3952 ...
```

**Comment by pukkandan** [comment]
@nao20010128nao any idea?

**Comment by nao20010128nao** [comment]
@pukkandan If extractor is able to detect failed fragments, it should try re-extraction (and stop iteration if needed)
If not, shorten re-extraction spans to 30 minutes or less (or make it configurable via `--extractor-args`)

**Comment by glubsy** [comment]
I deal with this issue (example [here](https://github.com/glubsy/livestream_saver/blob/0f1a2dfb907f1f3e35e0212aff75707b34cc682d/livestream_saver/download.py#L269-L291)) by checking this value in the JSON response for the videoId: `responseContext->serviceTrackingParams->params->key->is_viewed_live->value`. If it is not "True" after I start getting 403 errors, I consider the live stream as being over and stop trying to get fragments.

**Comment by Flat** [comment]
This issue also causes streams to be unplayable until you re-encode them as the post processing doesn't work to strip duplicate moov atoms.
