### ISSUE TITLE
Safety hazard, need help

### ISSUE THREAD

**Issue by jiemo9527** [yt-dlp/yt-dlp#2090]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2021.12.01**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

I tried to call yt-dlp to execute the download command through the php page, but it was blocked by the security protection software. In the same situation, calling youtube-dl will not be intercepted. The error message is as follows

### Verbose log

```shell
Warning: system(): open_basedir restriction in effect. File(/opt/rasp_php72/logs/alarm/alarm.log.2021-12-23) is not within the allowed path(s): (/www/wwwroot/fdm/:/tmp/:/www/php_session/fdm.a/) in /www/wwwroot/fdm/download.php on line 249

Warning: system(/opt/rasp_php72/logs/alarm/alarm.log.2021-12-23): failed to open stream: Operation not permitted in /www/wwwroot/fdm/download.php on line 249

Warning: [OpenRASP] 20002 Fail to open php_stream of /opt/rasp_php72/logs/alarm/alarm.log.2021-12-23! in /www/wwwroot/fdm/download.php on line 249
```

**Comment by jiemo9527** [comment]
The code on line 249 is 'system($cmd);'
The execution command is ： 'yt-dlp '+url+' --external-downloader aria2c --external-downloader-args "-x 16 -k 1M" -o file/'+name

**Comment by jiemo9527** [comment]
After turning off the security protection, still not resolved

**Comment by pukkandan** [comment]
This isn't really related to yt-dlp and you are better off asking this in some PHP dev community forums. I will keep this issue open for a few days in case someone can help you, but I doubt you'll get any answers here

**Comment by jiemo9527** [comment]
I solved it, yt-dlp does not have high permissions, so the full path is required for invocation. Modify the instruction to'python3 /usr/bin/yt-dlp...' and it will work
