### ISSUE TITLE
Thumbnail Embed does not work

### ISSUE THREAD

**Issue by crumhirnd** [yt-dlp/yt-dlp#2091]
### Checklist

- [ ] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2021.12.01**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

Command: yt-dlp 'https://www.youtube.com/watch?v=v-Se1DGeDC0' --recode-video mp4 -o "/Volumes/Media/ASMR/%(uploader)s/%(title)s %(id)s.%(ext)s" --add-metadata --embed-thumbnail -Uv

Thumbnail:
![image](https://user-images.githubusercontent.com/83274039/147261658-f0c404ce-1f93-4bc7-9c01-5cf0f05a3208.png)

Result:
![image](https://user-images.githubusercontent.com/83274039/147261402-04556288-ef24-4562-9fa9-1ae43e022b80.png)

### Verbose log

```shell
[debug] Command-line config: ['https://www.youtube.com/watch?v=v-Se1DGeDC0', '--recode-video', 'mp4', '-o', '/Volumes/Media/ASMR/%(uploader)s/%(title)s %(id)s.%(ext)s', '--add-metadata', '--embed-thumbnail', '-Uv']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2021.12.01 [91f071af6]
[debug] Python version 3.9.9 (CPython 64bit) - macOS-12.0.1-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.4.1 (setts), ffprobe 4.4.1, rtmpdump 2.4
[debug] Optional libraries: sqlite
[debug] Proxy map: {}
Latest version: 2021.12.01, Current version: 2021.12.01
yt-dlp is up to date (2021.12.01)
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=v-Se1DGeDC0
[youtube] v-Se1DGeDC0: Downloading webpage
[youtube] v-Se1DGeDC0: Downloading android player API JSON
[debug] Loading youtube-nsig.8da38e9a from cache
[debug] [youtube] Decrypted nsig N9scJXAsPfiGm_x1 => pARKUlxBVSEIKw
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] v-Se1DGeDC0: Downloading 1 format(s): 303+251
[info] Downloading video thumbnail 41 ...
[info] Writing video thumbnail 41 to: /Volumes/Media/ASMR/ASMR Glow/ASMR Super SENSITIVE Mouth Sounds (W_ NEW MICS) v-Se1DGeDC0.webp
WARNING: webm doesn't support embedding a thumbnail, mkv will be used
[debug] Invoking downloader on "https://rr1---sn-v2u0n-hxar.googlevideo.com/videoplayback?expire=1640292607&ei=n4zEYZvFE9CPwgOan79A&ip=175.39.188.101&id=o-ACx3n9o4Odur1rKaEneekJ25xGw9hzms6lQYGrS1W0aw&itag=303&source=youtube&requiressl=yes&mh=9D&mm=31%2C29&mn=sn-v2u0n-hxar%2Csn-v2u0n-ntqk&ms=au%2Crdu&mv=m&mvi=1&pl=21&initcwndbps=1535000&vprv=1&mime=video%2Fwebm&gir=yes&clen=246459097&dur=1344.876&lmt=1639101020244185&mt=1640270720&fvip=1&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=5516222&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIhAMr_hUJ78eZM5pUvx53LcWwUctQ-BFOTh2S9xOyYcvH7AiBztAH2qhmQBksRkbS5pTk65XBP1bi9W0nEZxeX2kyRzg%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgC1rXvvMn58PYsUPj5g_dWOUoMacWhOKWnNqKbTiCE40CIQCI82Jf8-dzapecP52YURqTlQXlSgR2Urt-fkdJxtdwgw%3D%3D"
[download] Destination: /Volumes/Media/ASMR/ASMR Glow/ASMR Super SENSITIVE Mouth Sounds (W_ NEW MICS) v-Se1DGeDC0.f303.webm
[download] 100% of 235.04MiB in 00:56                                     
[debug] Invoking downloader on "https://rr1---sn-v2u0n-hxar.googlevideo.com/videoplayback?expire=1640292607&ei=n4zEYZvFE9CPwgOan79A&ip=175.39.188.101&id=o-ACx3n9o4Odur1rKaEneekJ25xGw9hzms6lQYGrS1W0aw&itag=251&source=youtube&requiressl=yes&mh=9D&mm=31%2C29&mn=sn-v2u0n-hxar%2Csn-v2u0n-ntqk&ms=au%2Crdu&mv=m&mvi=1&pl=21&initcwndbps=1535000&vprv=1&mime=audio%2Fwebm&gir=yes&clen=23324609&dur=1344.921&lmt=1639101019017897&mt=1640270720&fvip=1&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=5511222&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRgIhAKlE3258EuVainlFiUo6ZG8NuBtFRBLlENdDbQBmwATvAiEA50o-YEoQlvBNxoUDudTidK_Apf8jpWtjfuLjC4TAm-4%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgC1rXvvMn58PYsUPj5g_dWOUoMacWhOKWnNqKbTiCE40CIQCI82Jf8-dzapecP52YURqTlQXlSgR2Urt-fkdJxtdwgw%3D%3D"
[download] Destination: /Volumes/Media/ASMR/ASMR Glow/ASMR Super SENSITIVE Mouth Sounds (W_ NEW MICS) v-Se1DGeDC0.f251.webm
[download] 100% of 22.24MiB in 00:07                                     
[Merger] Merging formats into "/Volumes/Media/ASMR/ASMR Glow/ASMR Super SENSITIVE Mouth Sounds (W_ NEW MICS) v-Se1DGeDC0.mkv"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:/Volumes/Media/ASMR/ASMR Glow/ASMR Super SENSITIVE Mouth Sounds (W_ NEW MICS) v-Se1DGeDC0.f303.webm' -i 'file:/Volumes/Media/ASMR/ASMR Glow/ASMR Super SENSITIVE Mouth Sounds (W_ NEW MICS) v-Se1DGeDC0.f251.webm' -c copy -map 0:v:0 -map 1:a:0 'file:/Volumes/Media/ASMR/ASMR Glow/ASMR Super SENSITIVE Mouth Sounds (W_ NEW MICS) v-Se1DGeDC0.temp.mkv'
Deleting original file /Volumes/Media/ASMR/ASMR Glow/ASMR Super SENSITIVE Mouth Sounds (W_ NEW MICS) v-Se1DGeDC0.f303.webm (pass -k to keep)
Deleting original file /Volumes/Media/ASMR/ASMR Glow/ASMR Super SENSITIVE Mouth Sounds (W_ NEW MICS) v-Se1DGeDC0.f251.webm (pass -k to keep)
[VideoConvertor] Converting video from mkv to mp4; Destination: /Volumes/Media/ASMR/ASMR Glow/ASMR Super SENSITIVE Mouth Sounds (W_ NEW MICS) v-Se1DGeDC0.mp4
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:/Volumes/Media/ASMR/ASMR Glow/ASMR Super SENSITIVE Mouth Sounds (W_ NEW MICS) v-Se1DGeDC0.mkv' 'file:/Volumes/Media/ASMR/ASMR Glow/ASMR Super SENSITIVE Mouth Sounds (W_ NEW MICS) v-Se1DGeDC0.mp4'
Deleting original file /Volumes/Media/ASMR/ASMR Glow/ASMR Super SENSITIVE Mouth Sounds (W_ NEW MICS) v-Se1DGeDC0.mkv (pass -k to keep)
[Metadata] Adding metadata to "/Volumes/Media/ASMR/ASMR Glow/ASMR Super SENSITIVE Mouth Sounds (W_ NEW MICS) v-Se1DGeDC0.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:/Volumes/Media/ASMR/ASMR Glow/ASMR Super SENSITIVE Mouth Sounds (W_ NEW MICS) v-Se1DGeDC0.mp4' -map 0 -dn -c copy -metadata 'title=ASMR Super SENSITIVE Mouth Sounds (W/ NEW MICS)' -metadata date=20211206 -metadata 'description=This ASMR video includes sensitive and intense mouth sounds with my new super sensitive mics!   Click the bell to have notifications, like & subscribe, it would make my DAY!

Twitter: https://twitter.com/asmrglow_
Instagram: https://www.instagram.com/asmrglow/
Merch: https://teespring.com/stores/glow-asmr Get yours!
My other channel: https://www.youtube.com/channel/UC5df6R3eauFbM9fSf-6St7A/videos
ALL MY OTHER LINKS (Social Media, Music Platforms, Merch): https://linktr.ee/asmrglow

#ASMR' -metadata 'synopsis=This ASMR video includes sensitive and intense mouth sounds with my new super sensitive mics!   Click the bell to have notifications, like & subscribe, it would make my DAY!

Twitter: https://twitter.com/asmrglow_
Instagram: https://www.instagram.com/asmrglow/
Merch: https://teespring.com/stores/glow-asmr Get yours!
My other channel: https://www.youtube.com/channel/UC5df6R3eauFbM9fSf-6St7A/videos
ALL MY OTHER LINKS (Social Media, Music Platforms, Merch): https://linktr.ee/asmrglow

#ASMR' -metadata 'purl=https://www.youtube.com/watch?v=v-Se1DGeDC0' -metadata 'comment=https://www.youtube.com/watch?v=v-Se1DGeDC0' -metadata 'artist=ASMR Glow' 'file:/Volumes/Media/ASMR/ASMR Glow/ASMR Super SENSITIVE Mouth Sounds (W_ NEW MICS) v-Se1DGeDC0.temp.mp4'
[ThumbnailsConvertor] Converting thumbnail "/Volumes/Media/ASMR/ASMR Glow/ASMR Super SENSITIVE Mouth Sounds (W_ NEW MICS) v-Se1DGeDC0.webp" to png
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -f image2 -pattern_type none -i 'file:/Volumes/Media/ASMR/ASMR Glow/ASMR Super SENSITIVE Mouth Sounds (W_ NEW MICS) v-Se1DGeDC0.webp' 'file:/Volumes/Media/ASMR/ASMR Glow/ASMR Super SENSITIVE Mouth Sounds (W_ NEW MICS) v-Se1DGeDC0.png'
[debug] ffprobe command line: ffprobe -hide_banner -show_format -show_streams -print_format json 'file:/Volumes/Media/ASMR/ASMR Glow/ASMR Super SENSITIVE Mouth Sounds (W_ NEW MICS) v-Se1DGeDC0.mp4'
[EmbedThumbnail] ffmpeg: Adding thumbnail to "/Volumes/Media/ASMR/ASMR Glow/ASMR Super SENSITIVE Mouth Sounds (W_ NEW MICS) v-Se1DGeDC0.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:/Volumes/Media/ASMR/ASMR Glow/ASMR Super SENSITIVE Mouth Sounds (W_ NEW MICS) v-Se1DGeDC0.mp4' -i 'file:/Volumes/Media/ASMR/ASMR Glow/ASMR Super SENSITIVE Mouth Sounds (W_ NEW MICS) v-Se1DGeDC0.png' -c copy -map 0 -dn -map 1 -disposition:2 attached_pic 'file:/Volumes/Media/ASMR/ASMR Glow/ASMR Super SENSITIVE Mouth Sounds (W_ NEW MICS) v-Se1DGeDC0.temp.mp4'
Deleting original file /Volumes/Media/ASMR/ASMR Glow/ASMR Super SENSITIVE Mouth Sounds (W_ NEW MICS) v-Se1DGeDC0.webp (pass -k to keep)
Deleting original file /Volumes/Media/ASMR/ASMR Glow/ASMR Super SENSITIVE Mouth Sounds (W_ NEW MICS) v-Se1DGeDC0.png (pass -k to keep)
```

**Comment by pukkandan** [comment]
The thumbnail in file explorer is generated by windows or the associated program. Whether it respects the embedded thumbnail is up to it. From the logs, it appears the thumbnail is in fact embedded. If not, show the output of ffprobe on the file

**Comment by crumhirnd** [comment]
FFprobe output:

ffprobe '/Volumes/Media/ASMR/ASMR Glow/ASMR Testing My New EAR MIC! Ear oil massage, mouth sounds.... EV1823p3imM.mp4'
ffprobe version 4.4.1 Copyright (c) 2007-2021 the FFmpeg developers
  built with Apple clang version 13.0.0 (clang-1300.0.29.3)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/4.4.1_3 --enable-shared --enable-pthreads --enable-version3 --cc=clang --host-cflags= --host-ldflags= --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libbluray --enable-libdav1d --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librist --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libspeex --enable-libsoxr --enable-libzmq --enable-libzimg --disable-libjack --disable-indev=jack --enable-avresample --enable-videotoolbox
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7fb7fe816a00] stream 0, timescale not set
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/Volumes/Media/ASMR/ASMR Glow/ASMR Testing My New EAR MIC! Ear oil massage, mouth sounds.... EV1823p3imM.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    title           : ASMR Testing My New EAR MIC! Ear oil massage, mouth sounds....
    artist          : ASMR Glow
    date            : 20211007
    encoder         : Lavf58.76.100
    comment         : https://www.youtube.com/watch?v=EV1823p3imM
    description     : Thanks to 3DIO for sending this mic!!!!!
                    : This ASMR video includes ear oil massage, mouth sounds, ear brushing, ear tapping, ear touching, closeup whispers, squishy virus lmao, feathers...Click the bell to have notifications, like & subscribe, it would make my DAY!
                    : 
                    : Twitter: https://twitter.com/asmrglow_
                    : Merch: https://teespring.com/stores/glow-asmr Get yours!
                    : My other channel: https://www.youtube.com/channel/UC5df6R3eauFbM9fSf-6St7A/videos
                    : Instagram: https://www.instagram.com/asmrglow/
                    : ALL MY OTHER LINKS (Social Media, Music Platforms, Merch): https://linktr.ee/asmrglow
                    : 
                    : Timestamps (Thank YOU CAKE BOW)
                    : 
                    : 0:00 intro (close whispering, tapping on ears)
                    : 3:01 ear touching/massage, close whispering
                    : 3:44 ear brushing
                    : 6:55 mouth sounds, ear cupping
                    : 10:10 scratching on mic
                    : 11:26 ear cupping
                    : 12:45 ear tapping
                    : 14:00 feather on ears
                    : 16:33 virus toy
                    : 18:49 wet cottons
                    : 22:11 oil massage
                    : 
                    : #ASMR
    synopsis        : Thanks to 3DIO for sending this mic!!!!!
                    : This ASMR video includes ear oil massage, mouth sounds, ear brushing, ear tapping, ear touching, closeup whispers, squishy virus lmao, feathers...Click the bell to have notifications, like & subscribe, it would make my DAY!
                    : 
                    : Twitter: https://twitter.com/asmrglow_
                    : Merch: https://teespring.com/stores/glow-asmr Get yours!
                    : My other channel: https://www.youtube.com/channel/UC5df6R3eauFbM9fSf-6St7A/videos
                    : Instagram: https://www.instagram.com/asmrglow/
                    : ALL MY OTHER LINKS (Social Media, Music Platforms, Merch): https://linktr.ee/asmrglow
                    : 
                    : Timestamps (Thank YOU CAKE BOW)
                    : 
                    : 0:00 intro (close whispering, tapping on ears)
                    : 3:01 ear touching/massage, close whispering
                    : 3:44 ear brushing
                    : 6:55 mouth sounds, ear cupping
                    : 10:10 scratching on mic
                    : 11:26 ear cupping
                    : 12:45 ear tapping
                    : 14:00 feather on ears
                    : 16:33 virus toy
                    : 18:49 wet cottons
                    : 22:11 oil massage
                    : 
                    : #ASMR
  Duration: 00:27:48.19, start: 0.000000, bitrate: 1846 kb/s
  Chapters:
    Chapter #0:0: start 0.000000, end 181.000000
      Metadata:
        title           : intro (close whispering, tapping on ears)
    Chapter #0:1: start 181.000000, end 224.000000
      Metadata:
        title           : ear touching/massage, close whispering
    Chapter #0:2: start 224.000000, end 415.000000
      Metadata:
        title           : ear brushing
    Chapter #0:3: start 415.000000, end 610.000000
      Metadata:
        title           : mouth sounds, ear cupping
    Chapter #0:4: start 610.000000, end 686.000000
      Metadata:
        title           : scratching on mic
    Chapter #0:5: start 686.000000, end 765.000000
      Metadata:
        title           : ear cupping
    Chapter #0:6: start 765.000000, end 840.000000
      Metadata:
        title           : ear tapping
    Chapter #0:7: start 840.000000, end 993.000000
      Metadata:
        title           : feather on ears
    Chapter #0:8: start 993.000000, end 1129.000000
      Metadata:
        title           : virus toy
    Chapter #0:9: start 1129.000000, end 1331.000000
      Metadata:
        title           : wet cottons
    Chapter #0:10: start 1331.000000, end 1668.000000
      Metadata:
        title           : oil massage
  Stream #0:0(eng): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709), 1920x1080 [SAR 1:1 DAR 16:9], 1695 kb/s, 59.94 fps, 59.94 tbr, 19001 tbn, 119.88 tbc (default)
    Metadata:
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
  Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 128 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
      vendor_id       : [0][0][0][0]
  Stream #0:2(und): Video: png (mp4v / 0x7634706D), rgb24(pc), 1280x720, 198653 kb/s, 25 fps, 25 tbr, 12800 tbn, 12800 tbc
    Metadata:
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
  Stream #0:3(eng): Data: bin_data (text / 0x74786574), 0 kb/s
    Metadata:
      handler_name    : SubtitleHandler
  Stream #0:4: Video: png, rgba(pc), 1280x720, 90k tbr, 90k tbn, 90k tbc (attached pic)
Unsupported codec with id 100359 for input stream 3

When I use mp3tag the thumbnails are properly embedded, see other examples:
![image](https://user-images.githubusercontent.com/83274039/147304357-fd01c1f0-8253-4f7e-9964-af16c9c08177.png)
![image](https://user-images.githubusercontent.com/83274039/147304370-7f3dd26f-6377-4e58-8451-dcee8aa9b505.png)

Output of FFprobe for the first one:
ffprobe '/Volumes/Media/ASMR/ASMR Glow/ASMR I Found The BEST NEW TRIGGERS hCu7IZ14SRw.mp4'
ffprobe version 4.4.1 Copyright (c) 2007-2021 the FFmpeg developers
  built with Apple clang version 13.0.0 (clang-1300.0.29.3)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/4.4.1_3 --enable-shared --enable-pthreads --enable-version3 --cc=clang --host-cflags= --host-ldflags= --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libbluray --enable-libdav1d --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librist --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libspeex --enable-libsoxr --enable-libzmq --enable-libzimg --disable-libjack --disable-indev=jack --enable-avresample --enable-videotoolbox
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7fe5cf017a00] stream 0, timescale not set
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/Volumes/Media/ASMR/ASMR Glow/ASMR I Found The BEST NEW TRIGGERS hCu7IZ14SRw.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    title           : ASMR I Found The BEST NEW TRIGGERS???
    artist          : ASMR Glow
    date            : 20210928
    encoder         : Lavf58.76.100
    comment         : Thank you Helix for sponsoring this ASMR video! Visit https://helixsleep.com/glow to get up to $200 off your Helix mattress, plus two free pillows.
                    : 
                    : This video includes a bunch of new triggers and some old ones! 
                    : Click the bell to have notifications, like & subscribe, it would make my DAY!
                    : 
                    : Twitter: https://twitter.com/asmrglow_
                    : Merch: https://teespring.com/stores/glow-asmr Get yours!
                    : My bloopers/gaming/song covers channel: https://www.youtube.com/channel/UC5df6R3eauFbM9fSf-6St7A/videos
                    : Instagram: https://www.instagram.com/asmrglow/
                    : ALL MY OTHER LINKS (Social Media, Music Platforms, Merch): https://linktr.ee/asmrglow
                    : 
                    : Earrings from https://www.etsy.com/shop/YueAndLotus
                    : 
                    : Time stamps: 
                    : 
                    : 00:00 Sponsor
                    : 02:21 Intro Whispering/mic scratching
                    : 03:24 Woven Sponge 
                    : 07:32 Computer Mouse (clicking/scroll wheel)
                    : 09:40 Squishy virus toy
                    : 15:25 Popsicle sticks
                    : 18:31 Packaging material (crunching)
                    : 20:46 Golden claws 
                    : 23:50 Police megaphone
                    : 
                    : 
                    : #ASMR
    description     : Thank you Helix for sponsoring this ASMR video! Visit https://helixsleep.com/glow to get up to $200 off your Helix mattress, plus two free pillows.
                    : 
                    : This video includes a bunch of new triggers and some old ones! 
                    : Click the bell to have notifications, like & subscribe, it would make my DAY!
                    : 
                    : Twitter: https://twitter.com/asmrglow_
                    : Merch: https://teespring.com/stores/glow-asmr Get yours!
                    : My bloopers/gaming/song covers channel: https://www.youtube.com/channel/UC5df6R3eauFbM9fSf-6St7A/videos
                    : Instagram: https://www.instagram.com/asmrglow/
                    : ALL MY OTHER LINKS (Social Media, Music Platforms, Merch): https://linktr.ee/asmrglow
                    : 
                    : Earrings from https://www.etsy.com/shop/YueAndLotus
                    : 
                    : Time stamps: 
                    : 
                    : 00:00 Sponsor
                    : 02:21 Intro Whispering/mic scratching
                    : 03:24 Woven Sponge 
                    : 07:32 Computer Mouse (clicking/scroll wheel)
                    : 09:40 Squishy virus toy
                    : 15:25 Popsicle sticks
                    : 18:31 Packaging material (crunching)
                    : 20:46 Golden claws 
                    : 23:50 Police megaphone
                    : 
                    : 
                    : #ASMR
  Duration: 00:27:53.33, start: 0.000000, bitrate: 2337 kb/s
  Chapters:
    Chapter #0:0: start 0.000000, end 141.000000
      Metadata:
        title           : Sponsor
    Chapter #0:1: start 141.000000, end 204.000000
      Metadata:
        title           : Intro Whispering/mic scratching
    Chapter #0:2: start 204.000000, end 452.000000
      Metadata:
        title           : Woven Sponge
    Chapter #0:3: start 452.000000, end 580.000000
      Metadata:
        title           : Computer Mouse (clicking/scroll wheel)
    Chapter #0:4: start 580.000000, end 925.000000
      Metadata:
        title           : Squishy virus toy
    Chapter #0:5: start 925.000000, end 1111.000000
      Metadata:
        title           : Popsicle sticks
    Chapter #0:6: start 1111.000000, end 1246.000000
      Metadata:
        title           : Packaging material (crunching)
    Chapter #0:7: start 1246.000000, end 1430.000000
      Metadata:
        title           : Golden claws
    Chapter #0:8: start 1430.000000, end 1673.000000
      Metadata:
        title           : Police megaphone
  Stream #0:0(eng): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709), 1920x1080 [SAR 1:1 DAR 16:9], 2195 kb/s, 59.94 fps, 59.94 tbr, 19001 tbn, 119.88 tbc (default)
    Metadata:
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
  Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 128 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
      vendor_id       : [0][0][0][0]
  Stream #0:2(eng): Data: bin_data (text / 0x74786574), 0 kb/s
    Metadata:
      handler_name    : SubtitleHandler
  Stream #0:3: Video: mjpeg (Baseline), yuvj420p(pc, bt470bg/unknown/unknown), 1280x720, 90k tbr, 90k tbn, 90k tbc (attached pic)
Unsupported codec with id 100359 for input stream 2

**Comment by ehoogeveen-medweb** [comment]
Windows' built-in support for thumbnails seems fragile. Using the tool [Icaros](https://shark007.net/tools.html) I got the thumbnails to work just fine (it uses the embedded image as expected), but by default they didn't show up.

**Comment by pukkandan** [comment]
Yeah, windows' thumbnail support is trash. But either way, if it can read the thumbnail attached by mp3tag properly (haven't tested myself yet), then there is probably something we can do to make it work as well

**Comment by crumhirnd** [comment]
I think it may have worked on the original yt-dl. I will need to test this again. By the way I am using a Mac.

**Comment by pukkandan** [comment]
oh! I totally missed that. Install `mutagen` and try again

**Comment by crumhirnd** [comment]
If I used homebrew wouldn't it automatically install all the dependencies?

**Comment by pukkandan** [comment]
I dont know. But either way, you don't currently have mutagen

**Comment by pukkandan** [comment]
Can re-open if you can provide logs after installing mutagen

**Comment by crumhirnd** [comment]
I installed mutagen but it still thinks it is not installed
![image](https://user-images.githubusercontent.com/83274039/147833037-f78f43c4-51c0-4755-bd06-e028b3d2bbc4.png)
![image](https://user-images.githubusercontent.com/83274039/147833066-d7eae666-5a39-4e84-8ffa-e6b871fdb96d.png)

**Comment by pukkandan** [comment]
not that mutagen, this one https://pypi.org/project/mutagen/

**Comment by TheYellowArchitect** [comment]
Why is this closed?
There are 3 commands related to embedding thumbnails:
[]--write-thumbnail
[]--embed-thumbnail
[]--add-metadata (I doubt it works as it says)

I have ffprobe, but I cannot embed any thumbnail using the above commands or their combination. If this is a bug, why is it closed?

**Comment by crumhirnd** [comment]
> not that mutagen, this one https://pypi.org/project/mutagen/

[lachlan@Lachlans-MBP ~ % yt-dlp -f '271+bestaudio' --recode-video mp4 'https://www.youtube.com/watch?v=DxF1rl3Bpms' --embed-thumbnail
[youtube] DxF1rl3Bpms: Downloading webpage
[youtube] DxF1rl3Bpms: Downloading android player API JSON
[info] DxF1rl3Bpms: Downloading 1 format(s): 271+251
[info] Downloading video thumbnail 41 ...
[info] Writing video thumbnail 41 to: Christmas Time Is Here _ Vince Guaraldi _ A Charles Cornell Christmas [DxF1rl3Bpms].webp
WARNING: webm doesn't support embedding a thumbnail, mkv will be used
[download] Christmas Time Is Here _ Vince Guaraldi _ A Charles Cornell Christmas [DxF1rl3Bpms].mp4 has already been downloaded
[VideoConvertor] Not converting media file 'Christmas Time Is Here _ Vince Guaraldi _ A Charles Cornell Christmas [DxF1rl3Bpms].mp4'; already is in target format mp4
[ThumbnailsConvertor] Converting thumbnail "Christmas Time Is Here _ Vince Guaraldi _ A Charles Cornell Christmas [DxF1rl3Bpms].webp" to png
[EmbedThumbnail] mutagen was not found. Falling back to AtomicParsley
[EmbedThumbnail] atomicparsley: Adding thumbnail to "Christmas Time Is Here _ Vince Guaraldi _ A Charles Cornell Christmas [DxF1rl3Bpms].mp4"
Deleting original file Christmas Time Is Here _ Vince Guaraldi _ A Charles Cornell Christmas [DxF1rl3Bpms].png (pass -k to keep)
Deleting original file Christmas Time Is Here _ Vince Guaraldi _ A Charles Cornell Christmas [DxF1rl3Bpms].webp (pass -k to keep)
lachlan@Lachlans-MBP ~ % brew uninstall mutagen
Error: No such keg: /usr/local/Cellar/mutagen
lachlan@Lachlans-MBP ~ % pip install mutagen
Requirement already satisfied: mutagen in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (1.45.1)

Hmm, still doesn’t work.
