### ISSUE TITLE
Option flag to use clipboard contents as input URL 

### ISSUE THREAD

**Issue by Xiode** [yt-dlp/yt-dlp#2098]
### Checklist

- [X] I'm reporting a feature request
- [X] I've verified that I'm running yt-dlp version **2021.12.01**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

I'd like a flag that grabs the contents of the clipboard and uses it as the input url.

Merry Christmas, devs!

**Comment by pukkandan** [comment]
out of scope
