### ISSUE TITLE
Unable to Download Vlive+ Videos

### ISSUE THREAD

**Issue by renDegade** [yt-dlp/yt-dlp#2101]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2021.12.01**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Bulgaria

### Description

Im getting an Error Unknown URL Type: Null everytime i try to download this video https://www.vlive.tv/video/11998

### Verbose log

```shell
D:\yt dlp>yt-dlp -vU --username MYUSERNAME --password MYPASSWORD https://www.vlive.tv/video/11998
[debug] Command-line config: ['-vU', '--username', 'PRIVATE', '--password', 'PRIVATE', 'https://www.vlive.tv/video/11998']
[debug] Encodings: locale cp1251, fs utf-8, out utf-8, err utf-8, pref cp1251
[debug] yt-dlp version 2021.12.01 [91f071a] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] exe versions: none
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2021.12.01, Current version: 2021.12.01
yt-dlp is up to date (2021.12.01)
[vlive] Downloading login cookies
[vlive] Logging in
[vlive] Checking login status
[debug] [vlive] Extracting URL: https://www.vlive.tv/video/11998
[vlive] 11998: Downloading officialVideoPost JSON metadata
[vlive] 11998: Downloading inkey JSON metadata
[vlive] 11998: Downloading JSON metadata
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
ERROR: unknown url type: 'null'
Traceback (most recent call last):
File "yt_dlp\YoutubeDL.py", line 1329, in wrapper
File "yt_dlp\YoutubeDL.py", line 1412, in __extract_info
File "yt_dlp\YoutubeDL.py", line 1462, in process_ie_result
File "yt_dlp\YoutubeDL.py", line 2414, in process_video_result
File "yt_dlp\YoutubeDL.py", line 2175, in _calc_headers
File "yt_dlp\YoutubeDL.py", line 2187, in _calc_cookies
File "yt_dlp\utils.py", line 2224, in sanitized_Request
File "urllib\request.py", line 328, in init
File "urllib\request.py", line 354, in full_url
File "urllib\request.py", line 383, in _parse
ValueError: unknown url type: 'null'
```

**Comment by Ashish0804** [comment]
I get `You can use this after buying Beautiful TWICE SANA #2.` on the webpage.
Do you have any free video where this error occurs?

**Comment by renDegade** [comment]
nop free videos work perfectly fine i just downloaded one from Vlive, i payed for that Sana one, and how can i share the account so u can log in , in the vlive cuze i see account needed can share account, i can give the account
