### ISSUE TITLE
Termux [cookies from browser]

### ISSUE THREAD

**Issue by CZeil** [yt-dlp/yt-dlp#2102]
### Checklist

- [X] I'm asking a question and not reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

Is it possible to use the --cookies-from-browser option from termux in android?

**Comment by pukkandan** [comment]
No. Apps running inside termux normally do not have access to other apps' data.

Perhaps it can be done if the phone is rooted? I am not sure. @mbway any idea?

**Comment by mbway** [comment]
I use yt-dlp with termux but this never crossed my mind. I think you're right that without rooting it's not possible (i checked with `find . -iname '*cookie*'` and found nothing.

I assume that the mobile versions of the desktop browsers share a lot of code, whether that extends to cookie management I have no idea. I don't have a rooted phone so I can't look into this myself but I am happy to help where I can if anyone is interested in adding support for android

**Comment by CZeil** [comment]
> No. Apps running inside termux normally do not have access to other apps' data.
> 
> Perhaps it can be done if the phone is rooted? I am not sure. @mbway any idea?

No. I dont rooted my phone
