### ISSUE TITLE
How to output to log file and console? 

### ISSUE THREAD

**Issue by Wilann** [yt-dlp/yt-dlp#2106]
### Checklist

- [X] I'm asking a question and not reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

Hi, 

How can I direct the output of yt-dlp to a log (or text) file, while also keeping the output to the console? 

I can re-direct the output to a text file via `>log.txt 2>&1`, but it disappears from the console.

**Comment by pukkandan** [comment]
Windows doesn't provide this functionality. In UNIX, you can use `tee`

**Comment by wamasi** [comment]
If you're ok with PowerShell, you can try something like this:
`powershell.exe "YT-DLP CMD HERE" | Tee-Object -Append "OUTPUTFILEPATHHERE.txt"`

**Comment by Wilann** [comment]
Will try it out @pukkandan - thank you for the guidance 

Thanks for the recommendation @wamasi - I'm using Ubuntu Terminal, do you have an alternative command for Terminal?

**Comment by wamasi** [comment]
You can just use pukkandan's suggestion with 'tee' in ubuntu terminal

example:
yt-dlpcmdhere |& tee -a '/path/to/file.log'

source: https://askubuntu.com/a/731237

**Comment by Wilann** [comment]
When running my command in python and subprocess, I'm getting this error:
`FileNotFoundError: [Errno 2] No such file or directory: 'yt-dlp -i "..." -o "%(playlist_title)s/%(upload_date)s - %(title)s" --download-archive "archive.txt" --match-filter "!is_live & title~=vs &
duration > 600 " --add-metadata --merge-output mp4 --embed-thumbnail |& tee -a test.log'`

Not sure if this is outside the scope of yt-dlp. Hope you can point me in the right direction.

**Comment by pukkandan** [comment]
You are using subprocess wrong. It takes a list of [exe] + [args], not the whole command string. I suggest looking at docs/tutorials or asking in a python community

**Comment by Wilann** [comment]
Will do. Thanks @pukkandan  and @wamasi for directing me towards tee. 

If anyone else comes across this, using something like `yt-dlp -i ... | tee -a log_file.txt` worked for me
