### ISSUE TITLE
How to add `timestmp` to output file name?

### ISSUE THREAD

**Issue by Wilann** [yt-dlp/yt-dlp#2107]
### Checklist

- [X] I'm asking a question and not reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

Hi, 

I'm currently using this command to download a video:
`yt-dlp https://www.youtube.com/watch?v=MUf-wrbUNEg&list=PLW--L_tD2yC-85UL9PXnrDrreS2iCX-Zs&index=6 --output "%(timestamp)s - %(title)s" --merge-output mp4`

I'm expecting some sort of upload time at the beginning of the file name, but I'm getting: `HSBC BWF World Tour Finals 2021 _ Lakshya Sen (IND) vs Kento Momota (JPN) _ Group A [MUf-wrbUNEg].webm`

How do I get the video's uploaded time?

**Comment by pukkandan** [comment]
YouTube doesn't provide upload time, only date. But you will not have gotten that filename with the given command. Show full verbose log if you need further help
