### ISSUE TITLE
--geo-verification-proxy does not work for me

### ISSUE THREAD

**Issue by qzmtch** [yt-dlp/yt-dlp#2108]
### Checklist

- [X] I'm asking a question and not reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

hi, recently, the proxy option stopped working for me displaying an error like this in the console (only tested on chaturbate)

`ERROR: [Chaturbate] shycinderella: Unable to download webpage: <urlopen error timed out> (caused by URLError(timeout('timed out'))) (caused by URLError(timeout('timed out')))`

I tested only on this site, because I did not know what else there are sites blocked where only the entrance is blocked, and the video works even without a proxy, it used to work, but for a couple of weeks or more, it stopped working and an error appeared

I don’t know where the problem is, on the site, or on me, or on yt-dlp, so this is a question, and not other tags, please check who doesn’t work either, with this site, and others, and help find the problem if I have it then I will look further 

tnx

**Comment by pukkandan** [comment]
Check if you can open the webpage through the same proxy on browser. If not, open a bug report. There is nothing anyone can do with the info you have provided

**Comment by qzmtch** [comment]
yes it was my problem, the proxy address was not responding
