### ISSUE TITLE
[CBC Gem] Broken regex

### ISSUE THREAD

**Issue by makeworld-the-better-one** [yt-dlp/yt-dlp#2110]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2021.12.25**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Canada

### Description

No CBC Gem videos can be downloaded to an error with the regex added in #1913 by @DavidSkrundz 

Not sure what's causing this. The regex is bad but not sure why exactly.

### Verbose log

```shell
[debug] Command-line config: ['https://gem.cbc.ca/media/schitts-creek/s06e01', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2021.12.25 [87e049962]
[debug] Python version 3.10.1 (CPython 64bit) - Linux-5.15.10-arch1-1-x86_64-with-glibc2.33
[debug] exe versions: ffmpeg 4.4.1 (setts), ffprobe 4.4.1, phantomjs 2.1.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] Using fake IP 99.230.215.143 (CA) as X-Forwarded-For
[debug] Loading cbcgem.claims_token from cache
[debug] [gem.cbc.ca] Extracting URL: https://gem.cbc.ca/media/schitts-creek/s06e01
[gem.cbc.ca] schitts-creek/s06e01: Downloading JSON metadata
[gem.cbc.ca] schitts-creek/s06e01: Downloading JSON metadata
[gem.cbc.ca] schitts-creek/s06e01: Downloading m3u8 information
[gem.cbc.ca] schitts-creek/s06e01: Downloading secret XML
ERROR: invalid group reference 11 at position 1
Traceback (most recent call last):
  File "/home/makeworld/.local/pipx/venvs/yt-dlp/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1352, in wrapper
    return func(self, *args, **kwargs)
  File "/home/makeworld/.local/pipx/venvs/yt-dlp/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1421, in __extract_info
    ie_result = ie.extract(url)
  File "/home/makeworld/.local/pipx/venvs/yt-dlp/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 599, in extract
    ie_result = self._real_extract(url)
  File "/home/makeworld/.local/pipx/venvs/yt-dlp/lib/python3.10/site-packages/yt_dlp/extractor/cbc.py", line 371, in _real_extract
    formats.extend(self._find_secret_formats(formats, video_id))
  File "/home/makeworld/.local/pipx/venvs/yt-dlp/lib/python3.10/site-packages/yt_dlp/extractor/cbc.py", line 343, in _find_secret_formats
    'url': re.sub(r'(QualityLevels\()\d+(\))', fr'\1{bitrate}\2', base_url),
  File "/usr/lib/python3.10/re.py", line 209, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "/usr/lib/python3.10/re.py", line 326, in _subx
    template = _compile_repl(template, pattern)
  File "/usr/lib/python3.10/re.py", line 317, in _compile_repl
    return sre_parse.parse_template(repl, pattern)
  File "/usr/lib/python3.10/sre_parse.py", line 1036, in parse_template
    addgroup(int(this[1:]), len(this) - 1)
  File "/usr/lib/python3.10/sre_parse.py", line 980, in addgroup
    raise s.error("invalid group reference %d" % index, pos)
re.error: invalid group reference 11 at position 1
```

**Comment by makeworld-the-better-one** [comment]
Maybe this is the issue:

In #2020 the regex was updated:

```diff
-                    'url': re.sub(r'(QualityLevels\()\d+(\))', fr'\<1>{bitrate}\2', base_url),
+                    'url': re.sub(r'(QualityLevels\()\d+(\))', fr'\g<1>{bitrate}\2', base_url),
````

@pukkandan closed the PR in favour of b69fd25, which updates it a different way:

```diff
-                    'url': re.sub(r'(QualityLevels\()\d+(\))', fr'\<1>{bitrate}\2', base_url),
+                    'url': re.sub(r'(QualityLevels\()\d+(\))', fr'\1{bitrate}\2', base_url),
```

**Comment by makeworld-the-better-one** [comment]
Ok I tested myself and can confirm this was the issue. If #2020 was implemented this issue would be fixed.

**Comment by pukkandan** [comment]
oh! because the bitrate is a number 🤦

**Comment by makeworld-the-better-one** [comment]
Yeah that makes sense. Not sure if the `g` is needed but the angle brackets are at least. Probably would be good to leave the `g` in just in case.

**Comment by pukkandan** [comment]
yes. `g` is needed. Backref can be either `\1` or `\g<1>`. But since bitrate is a number, `\1{bitrate}` got interpretted as a group
