### ISSUE TITLE
your ffmpeg.exe for yt-dlp is not compatible

### ISSUE THREAD

**Issue by anunasica** [yt-dlp/yt-dlp#2115]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

Hi, I tried your ffmpeg with amelioraments and fixes to be used only for yt-dlp from here: 
https://github.com/yt-dlp/FFmpeg-Builds/releases/download/autobuild-2021-12-24-12-47/ffmpeg-n4.4.1-3-gcfec0bae44-win32-gpl-4.4.zip
It crashes at start. Perhaps the exe does not find a dll. Vista32 SP2. The one and only still working for me is this exe bigger in size from 2019:
https://up2sha.re/file?f=uj8D2we67Lr08ma70K&token=Q%2BkMSP7hUxkV3XKttnoXGfw7j8Sqv%2FPn
What to do? At the moment I am unable to switch to Win10 or 11. thanks. 

### Verbose log

```shell
Error:
https://postimg.cc/CnGdR1TD
"Unable to find the access point .... into the...DLL."
```

**Comment by pukkandan** [comment]
I don't really know. The ffmpeg builds are provided for convenience and not as an official part of yt-dlp (i.e., don't expect the same level of support). I'm not sure about whether they support vista or how to build for it. Maybe @Vangelis66 knows more

PS: In future, open issues in the correct repository

**Comment by nicolaasjan** [comment]
Static FFmpeg x86 builds can be downloaded from :
https://www.notion.so/venomissimo/34dc4ddf501a4b98b46ea9fb4f3470af

Of course these builds don't have the fix for yt-dlp.
But I guess that won't be a problem when you avoid vp9 codec.
