### ISSUE TITLE
How to get the whole list of video-ids from the specific channel id

### ISSUE THREAD

**Issue by xinkez** [yt-dlp/yt-dlp#2117]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

Hi, 
I want to get the whole list of video-ids from the specific channel id. But I don't find the proper solution. Thank you in advance.

### Verbose log

```shell
None
```

**Comment by Ashish0804** [comment]
`yt-dlp --flat-playlist --print id <channel url>`

eg:
```shell
C:\Users\Ashish> yt-dlp --flat-playlist --print id 'https://www.youtube.com/c/GeekyRanjitRidesVlogs'
WARNING: [youtube:tab] A channel/user page was given. All the channel's videos will be downloaded. To download only the videos in the home page, add a "/featured" to the URL
aMSEeaTnfGA
5ZrpKKrF3BI
Fbjf9q5sKKg
R_F6ymkOMKE
BdxA4gVuzf4
7W3IKj50KAw
VlPSbIuHscE
WZeCL0pjwpI
NDEjbOLyJa8
ebUSUnYJDU8
juPgQgo2gVs
L2WFlpC0-MU
1VPsI84_YdY
yuW0VbpRzOE
AZGwNW12fwA
0Sb3fO3CyAw
1_mw2mygXBc
-RlDhaImtxE
9qmHA3yBAMo
PfoKOphfjBU
```

**Comment by xinkez** [comment]
It works. Thank you.

**Comment by a92nj2efnfsa** [comment]
How can I get this to append youtube in front? like:
youtube PfoKOphfjBU

I am trying to pre-populate an archive file for a youtube channel so that I can only download the latest video uploaded to a channel.

**Comment by coletdjnz** [comment]
`--print "%(extractor)s %(id)s"`

**Comment by a92nj2efnfsa** [comment]
This seems to be the only thing that works for me:
yt-dlp --skip-download --print "youtube %(id)s" channel >> file.txt

**Comment by a92nj2efnfsa** [comment]
Never mind, I see what you're saying. I think the best option is to use:
yt-dlp --skip-download --force-write-archive --download-archive test.txt ytchannel

This way "force write archive" will always create a file in the appropriate format needed for future builds.
