### ISSUE TITLE
[question/idea] split the modules from the core

### ISSUE THREAD

**Issue by pirate486743186** [yt-dlp/yt-dlp#2121]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

What if yt-dlp was split in a core, that changes relatively slowly, and modules that change relatively fast?

Presumably, it will make things easier to manage. When you have a difficult problem, a strategy is cutting it down into smaller pieces.

It would be easier for linux distributions to have the core included. Presumably, it would stay compatible with latest modules for quite a  long time with some official API. The core, could have normal release cycles, something preferred by distros. Presumably, it would be possible to remove the distros modules and install your own.  You could install a core system wide, and modules locally for each user... Maybe the modules could come directly from upstream or pip.

It would be easier for people to maintain their own forks of the core.

It would be easier for users to maintain their own modules, instaid of having to fork the whole thing. Or even people could have github forks of certain modules.

Presumably, you could install individual modules and from different sources.
 
Presumably, it gives an extra layer of legal protection from lawyers.

And when someone creates a bundle of modules for pirate sites, that's not the projects fault.

**Comment by pukkandan** [comment]
You can already write plugins. There was a PR to allow plugins to be installed via PIP, but the author lost interest and abandoned it.

So what you are asking is to remove all the extractors (websites) from the project?

**Comment by pirate486743186** [comment]
it's about managing complexity.

There's an API in the core, that doesn't change very fast. The plugins can change at any time to be up to date. If you write a plugin outside of the project, you know it will not brake, until the new release of the core. Even then, you know what changes are coming.

Not remove the extractors from the project, i'm not saying to just delete them.  If it's two subprojects, or two sister projects doesn't really matter. If you feel paranoid, you could go the two (or more) projects root. On what ground, a lawyer would demand the shutdown of the core project?

I'm saying, to have a relatively stable slow changing core, with normal version numbers, instaid of just have the whole thing change at any time. It will be easier to manage downstream. Not everybody uses arch linux. This introduces a minimum of stability, in the constraint of having to chase a moving target.

**Comment by gippeumgwa** [comment]
@pirate486743186 
![image](https://user-images.githubusercontent.com/90806492/147463734-f9fe81f8-8730-4c05-8132-e5f11395116d.png)

**Comment by pukkandan** [comment]
Have you ever written an extractor? The core API has maintained backward compatibility for years.

I am not going to maintain two separate packages

**Comment by pirate486743186** [comment]
..... It could be maintained by someone else.

and it will probably solve/reduce #25
(the maintainer will be able to sign it, etc...)

It's very nice that it hasn't change for years, downstream is supposed to know this how? There's no way in taking advantage of that right now. They need a cue of when it changes, that's a new version number.

**Comment by pukkandan** [comment]
> It could be maintained by someone else.

I don't understand what you are asking at all... You want to split this program into core and extractors, and then not have me maintain the extractors part? That effectively means just remove all extractors from this project and let others deal with it. But then you also say:

> Not remove the extractors from the project, i'm not saying to just delete them. If it's two subprojects, or two sister projects doesn't really matter.

**Comment by pirate486743186** [comment]
that's semantics. They are still dependent on each other to do anything.

You micromanage everything? You don't delegate anything?
You'll end up burning out like the youtube-dl guy if you don't.
A lot of open source maintainers do this mistake, over doing it and burning out.

You can split it into two projects, keep control of both for oversight, but actually delegate some stuff to collaborators. (in theory, extractors could be further subdivided between collaborators) And i recommend dictatorship, most people just mess things up in trying to do clever organizations. Linus Torvalds stopped writing code years ago, he just verifies what others did, or just accepts stuff from people he learned to trust.
 
yt-dlp is a relatively large project and needs some subdivision.

**Comment by chrizilla** [comment]
@pukkandan : sry for asking despite my poor coding knowledge, but doesn't @pirate486743186 make some good points here?

**Comment by pukkandan** [comment]
I dont fully understand what they mean by "splitting the project" and this was never really answered.

> I don't understand what you are asking at all... You want to split this program into core and extractors, and then not have me maintain the extractors part? That effectively means just remove all extractors from this project and let others deal with it. But then you also say:

> > Not remove the extractors from the project, i'm not saying to just delete them. If it's two subprojects, or two sister projects doesn't really matter.

If you think they are making a good point, please do elaborate on this

**Comment by chrizilla** [comment]
thanks for your reply, pukkandan. I don't want to misinterpret the comments above, so I hope @pirate486743186 will clarify, but I think the idea was a split like Firefox and Firefox plugins ? I just thought the [last comment](#issuecomment-1003310296) raised a couple of seemingly interesting points (although again, I'm in no position to judge how valid they are).

**Comment by pukkandan** [comment]
> but I think the idea was a split like Firefox and Firefox plugins

yt-dlp already has a plugin architecture. See my above comment

I see I never addressed the last comment since he never answered my question

> You'll end up burning out like the youtube-dl guy if you don't.
> A lot of open source maintainers do this mistake, over doing it and burning out.

Perhaps. The solution is for more people to help. I'm not necessarily talking about PRs. There is something for anyone to do. The most important thing you can do is to follow proper guidelines when open issues! Help in triaging (validating/testing) issues, answering questions etc are also very much appreciated. If you are able to, you can also help by making/review PRs and making sure to follow code guidelines when you do. A lot of my time is spend triaging issues and "fixing" non-conforming code

> So what you are asking is  (supported sites) from the project?

If my interpretation of OPs suggestion as "remove all the extractors and let others deal with it" is correct, it will in fact reduce my load. But I hope the cost of doing that is obvious... If the interpretation is for me to instead maintain both halfs of the project, I don't see what splitting accomplishes

> You can split it into two projects, keep control of both for oversight, but actually delegate some stuff to collaborators. 

Collaborators already have commit and triaging rights to the repo. Again, I don't see how splitting the project helps anyone here

**Comment by chrizilla** [comment]
> > but I think the idea was a split like Firefox and Firefox plugins
> yt-dlp already has a plugin architecture.

sure, I didn't want to compare Firefox plugins to yt-dlp plugins on the coding architecture level but from a purely organizational viewpoint. But maybe I am wrong and there aren't any major differences there either.

> Perhaps. The solution is for more people to help.

Once  I am more familiar with yt-dlp and am good enough in Python, I'll gladly help.

> If my interpretation of OPs suggestion as "remove all the extractors and let others deal with it" is correct, it will in fact reduce my load. But I hope the cost of doing that is obvious... If the interpretation is for me to instead maintain both halfs of the project, I don't see what splitting accomplishes
> 
> > You can split it into two projects, keep control of both for oversight, but actually delegate some stuff to collaborators.
> 
> Collaborators already have commit and triaging rights to the repo. Again, I don't see how splitting the project helps anyone here

Thanks for this insight. That makes sense. Maybe @pirate486743186 can clarify.
