### ISSUE TITLE
[RFE] Add support for ruv.is

### ISSUE THREAD

**Issue by africola** [yt-dlp/yt-dlp#2122]
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2021.12.25**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Worldwide; parts accessible from Iceland only

### Example URLs

https://www.ruv.is/sjonvarp/spila/jolin-koma/32539/9ma3lh
https://www.ruv.is/sjonvarp/spila/kastljos/30772/95erup
https://www.ruv.is/utvarp/spila/jolatonleikar-valdimars-gudmundssonar/32480/9lo3g1
https://www.ruv.is/utvarp/spila/gerpla/21137/69ig0h

### Description

Please add support for downloading video/audio from the media library of RÚV, Iceland´s state broadcaster. Thank you!

### Verbose log

```shell
[debug] Command-line config: ['-Uv', '-F', 'https://www.ruv.is/sjonvarp/spila/jolin-koma/32539/9ma3lh']
[debug] Encodings: locale cp1252, fs utf-8, out cp1252 (No ANSI), err cp1252 (No ANSI), pref cp1252
[debug] yt-dlp version 2021.12.25 [87e0499] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit)
[debug] exe versions: ffmpeg 4.2.3
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2021.12.25, Current version: 2021.12.25
yt-dlp is up to date (2021.12.25)
[debug] [generic] Extracting URL: https://www.ruv.is/sjonvarp/spila/jolin-koma/32539/9ma3lh
[generic] 9ma3lh: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] 9ma3lh: Downloading webpage
[generic] 9ma3lh: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://www.ruv.is/sjonvarp/spila/jolin-koma/32539/9ma3lh
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1352, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1421, in __extract_info
  File "yt_dlp\extractor\common.py", line 599, in extract
  File "yt_dlp\extractor\generic.py", line 3817, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.ruv.is/sjonvarp/spila/jolin-koma/32539/9ma3lh
```

**Comment by Ashish0804** [comment]
to devs
here's the req to get the stuff
```
curl 'https://www.ruv.is/gql/?operationName=getSerie&variables=%7B%22episodeID%22%3A%5B%229ma3lh%22%5D%2C%22programID%22%3A32539%7D&extensions=%7B%22persistedQuery%22%3A%7B%22version%22%3A1%2C%22sha256Hash%22%3A%22fd7fcb985afe3f26ea4cf46419772e9b33a7e34c903a6cfc95eb0caf81450690%22%7D%7D' \
  -H 'accept: */*' \
  -H 'Referer: https://www.ruv.is/sjonvarp/spila/jolin-koma/32539/9ma3lh' \
  -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36' \
  -H 'content-type: application/json' \
  --compressed
```

**Comment by africola** [comment]
Excellent, thank you _very_ much to everyone involved in handling this!
