### ISSUE TITLE
Facebook Live: Support Permalinks

### ISSUE THREAD

**Issue by rgabbo** [yt-dlp/yt-dlp#2126]
### Checklist

- [X] I'm reporting a site feature request
- [X] I've verified that I'm running yt-dlp version **2021.12.25**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Example URLs

https://www.facebook.com/BasicHacker/live

### Description

As stated [here](https://www.facebook.com/business/help/629164494303277?id=1123223941353904),  is possible to point to current live streaming from a specific Facebook page in the form `facebook.com/nameofthepage/live`
However, if you use this URL with yt-dlp you get an error. It would be great to support this for scripting purposes.

### Verbose log

```shell
[debug] Command-line config: ['-Uv', 'https://www.facebook.com/BasicHacker/live']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2021.12.25 [87e0499] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.18363-SP0
[debug] exe versions: ffmpeg 4.4.1-essentials_build-www.gyan.dev (setts), ffprobe 4.4.1-essentials_build-www.gyan.dev
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2021.12.25, Current version: 2021.12.25
yt-dlp is up to date (2021.12.25)
[debug] [generic] Extracting URL: https://www.facebook.com/BasicHacker/live
[generic] live: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] live: Downloading webpage
[generic] live: Extracting information
[debug] Looking for video embeds
[redirect] Following redirect to https://www.facebook.com/BasicHacker/live?_fb_noscript=1
[debug] [generic] Extracting URL: https://www.facebook.com/BasicHacker/live?_fb_noscript=1
[generic] live?_fb_noscript=1: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] live?_fb_noscript=1: Downloading webpage
[generic] live?_fb_noscript=1: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://www.facebook.com/BasicHacker/live?_fb_noscript=1
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1352, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1421, in __extract_info
  File "yt_dlp\extractor\common.py", line 599, in extract
  File "yt_dlp\extractor\generic.py", line 3817, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.facebook.com/BasicHacker/live?_fb_noscript=1
```

**Comment by pukkandan** [comment]
Same underlying issue as https://github.com/yt-dlp/yt-dlp/issues/2187
