### ISSUE TITLE
Newgrounds download reports invalid SSL certificate

### ISSUE THREAD

**Issue by Nan123721** [yt-dlp/yt-dlp#2130]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2021.12.25**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Everywhere

### Description

This has happened for every video I have tried, i'm not sure what else there is to say here. Running a fully up to date install of Windows 10. I am not a developer, so I don't know what would cause this, perhaps a library? It may also be Newgrounds itself acting up.

### Verbose log

```shell
Latest version: 2021.12.25, Current version: 2021.12.25
yt-dlp is up to date (2021.12.25)
[Newgrounds] 827175: Downloading webpage
[Newgrounds] 827175: Downloading JSON metadata
[Newgrounds] 827175: Checking 1080p video format URL
[Newgrounds] 827175: 1080p video format URL is invalid, skipping: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)>
[Newgrounds] 827175: Checking 720p video format URL
[Newgrounds] 827175: 720p video format URL is invalid, skipping: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)>
[Newgrounds] 827175: Checking 360p video format URL
[Newgrounds] 827175: 360p video format URL is invalid, skipping: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)>
```

**Comment by pukkandan** [comment]
Try with --no-check-certificate

**Comment by Nan123721** [comment]
Works as expected with that arg

**Comment by pukkandan** [comment]
You did not provide VERBOSE log! Are you using a Mac?

**Comment by pukkandan** [comment]
In any case, the issue is that you don't have the relevent certificates. This is a known issue on macOS, but similar issue can happen in other OSes too. See https://stackoverflow.com/a/42334357/12907559

**Comment by Nan123721** [comment]
No I am not, I used -Uv and then > log.txt. Appears to have cut stuff off though. Heres a copy pasted log:
https://pastebin.com/AGbZERMt
