### ISSUE TITLE
Cannot download private facebook videos

### ISSUE THREAD

**Issue by charlie-collard** [yt-dlp/yt-dlp#2140]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2021.12.27**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [x] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

UK

### Verbose log

```shell
[debug] Command-line config: ['-Uv', '--username', 'PRIVATE', '--password', 'PRIVATE', 'https://www.facebook.com/100006437392630/videos/254658231859010']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2021.12.27 [6223f67a8] (source)
[debug] Lazy loading extractors is disabled
[debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
[debug] Git HEAD: 45d86abeb
[debug] Python version 3.9.6 (CPython 64bit) - macOS-10.16-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.4.1 (setts), ffprobe 4.4.1
[debug] Optional libraries: sqlite, websockets
[debug] Proxy map: {}
[facebook] Downloading login page
[facebook] Logging in
[debug] [facebook] Extracting URL: https://www.facebook.com/100006437392630/videos/254658231859010
[facebook] 254658231859010: Downloading webpage
ERROR: [facebook] 254658231859010: This video is only available for registered users. Use --cookies, --username and --password, or --netrc to provide account credentials
  File "/Users/charlie/yt-dlp/yt_dlp/extractor/common.py", line 599, in extract
    ie_result = self._real_extract(url)
  File "/Users/charlie/yt-dlp/yt_dlp/extractor/facebook.py", line 721, in _real_extract
    return self._extract_from_url(real_url, video_id)
  File "/Users/charlie/yt-dlp/yt_dlp/extractor/facebook.py", line 601, in _extract_from_url
    self.raise_login_required()
  File "/Users/charlie/yt-dlp/yt_dlp/extractor/common.py", line 1089, in raise_login_required
    raise ExtractorError(msg, expected=True)
```

### Description

All videos which require a login on Facebook are failing to download for me on the latest version.

I've run a git bisect to try and find the source of the issue, as I know this works fine in older versions of yt-dlp. The first commit where downloads no longer work is d76d15a6699dc41eea26a96d054a1b7bcb12c69b.

Here is an example successful output of running the same command on e978789f0f0bfe1963f4a295f6094dafa7524933, which is the parent of d76d15a6699dc41eea26a96d054a1b7bcb12c69b:

```
[debug] Command-line config: ['-v', '--username', 'PRIVATE', '--password', 'PRIVATE', 'https://www.facebook.com/100006437392630/videos/254658231859010']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2021.12.01 [91f071af6] (source)
[debug] Lazy loading extractors is disabled
[debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
[debug] Git HEAD: e978789f0
[debug] Python version 3.9.6 (CPython 64bit) - macOS-10.16-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.4.1 (setts), ffprobe 4.4.1
[debug] Optional libraries: sqlite, websockets
[debug] Proxy map: {}
[facebook] Downloading login page
[facebook] Logging in
[debug] [facebook] Extracting URL: https://www.facebook.com/100006437392630/videos/254658231859010
[facebook] 254658231859010: Downloading webpage
[debug] Sort order given by extractor: res, quality
[debug] Formats sorted by: hasvid, ie_pref, res, quality, lang, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
WARNING: [facebook] unable to extract OpenGraph title; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 254658231859010: Downloading 1 format(s): hd
[debug] Invoking downloader on "PRIVATE"
[download] Destination: Facebook video #254658231859010 [254658231859010].mp4
[download] 100% of 1.79MiB in 00:03                                      
```

I have tried multiple private videos and found the same problem for all of them.

**Comment by pukkandan** [comment]
Can you confirm if `--user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.47 Safari/537.36"` works around the issue

**Comment by bspammer** [comment]
Yep it worked, it hung for much longer on the `Logging in` prompt if that's useful.

```
[debug] Command-line config: ['-v', '--user-agent', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.47 Safari/537.36', '--username', 'PRIVATE', '--password', 'PRIVATE', 'https://www.facebook.com/100006437392630/videos/254658231859010']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2021.12.27 [6223f67a8] (source)
[debug] Lazy loading extractors is disabled
[debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
[debug] Git HEAD: 26f2aa3db
[debug] Python version 3.9.6 (CPython 64bit) - macOS-10.16-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.4.1 (setts), ffprobe 4.4.1
[debug] Optional libraries: sqlite, websockets
[debug] Proxy map: {}
[facebook] Downloading login page
[facebook] Logging in
[debug] [facebook] Extracting URL: https://www.facebook.com/100006437392630/videos/254658231859010
[facebook] 254658231859010: Downloading webpage
[debug] Sort order given by extractor: res, quality
[debug] Formats sorted by: hasvid, ie_pref, res, quality, lang, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
WARNING: [facebook] unable to extract OpenGraph title; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 254658231859010: Downloading 1 format(s): hd
[debug] Invoking downloader on "PRIVATE"
[download] 100% of 1.79MiB in 00:04
```

**Comment by pukkandan** [comment]
So this is same underlying issue as #2187. Closing as duplicate in favor of tracking the issue there

**Comment by Brumbpo-Tungus** [comment]
> Yep it worked, it hung for much longer on the `Logging in` prompt if that's useful.
> 
> ```
> [debug] Command-line config: ['-v', '--user-agent', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.47 Safari/537.36', '--username', 'PRIVATE', '--password', 'PRIVATE', 'https://www.facebook.com/100006437392630/videos/254658231859010']
> [debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
> [debug] yt-dlp version 2021.12.27 [6223f67a8] (source)
> [debug] Lazy loading extractors is disabled
> [debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
> [debug] Git HEAD: 26f2aa3db
> [debug] Python version 3.9.6 (CPython 64bit) - macOS-10.16-x86_64-i386-64bit
> [debug] exe versions: ffmpeg 4.4.1 (setts), ffprobe 4.4.1
> [debug] Optional libraries: sqlite, websockets
> [debug] Proxy map: {}
> [facebook] Downloading login page
> [facebook] Logging in
> [debug] [facebook] Extracting URL: https://www.facebook.com/100006437392630/videos/254658231859010
> [facebook] 254658231859010: Downloading webpage
> [debug] Sort order given by extractor: res, quality
> [debug] Formats sorted by: hasvid, ie_pref, res, quality, lang, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
> WARNING: [facebook] unable to extract OpenGraph title; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
> [debug] Default format spec: bestvideo*+bestaudio/best
> [info] 254658231859010: Downloading 1 format(s): hd
> [debug] Invoking downloader on "PRIVATE"
> [download] 100% of 1.79MiB in 00:04
> ```

Hey, is this still working? I tried the --user-agent string and I still get the original error you opened the ticket for.

**Comment by rahul23oza** [comment]
Why I cannot download Facebook videos from yt-dlp command ?? Although I can download YT videos.
