### ISSUE TITLE
Unable to extract metadata: ffprobe not found

### ISSUE THREAD

**Issue by PatrykMis** [yt-dlp/yt-dlp#2141]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2021.12.27**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

> WARNING: Unable to extract metadata: ffprobe not found. Please install or provide the path using --ffmpeg-location

ffmpeg and ffprobe are on path and even in the same directory, but this warning still exists.

This issue may, but not nessesaryly be tight with vk.com site.

### Verbose log

```shell
[debug] Command-line config: ['--concurrent-fragments', '8', '-Uv', 'https://vk.com/video-201956532_456240735']
[debug] Encodings: locale cp1250, fs utf-8, out utf-8, err utf-8, pref cp1250
[debug] yt-dlp version 2021.12.27 [6223f67] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] exe versions: ffmpeg N-104676-g5593f5cf24-ffmpeg-windows-build-helpers (fdk)
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {'socks': 'socks://10.64.0.1:1080'}
Latest version: 2021.12.27, Current version: 2021.12.27
yt-dlp is up to date (2021.12.27)
[debug] [vk] Extracting URL: https://vk.com/video-201956532_456240735
[vk] -201956532_456240735: Downloading JSON metadata
[vk] -201956532_456240735: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] -201956532_456240735: Downloading 1 format(s): hls-3203
[debug] Invoking downloader on "https://vk6-7.vkuser.net/expires/1640913901778/srcIp/5.253.206.220/pr/43/srcAg/CHROME/ms/95.142.206.166/type/3/sig/ic3Q7leUvzE/ct/8/urls/45.136.22.171%3B185.226.52.155/clientType/13/zs/43/id/2543581727232/video/"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 393
[download] Destination: Zaczyna się dziać dobrze  --) [-201956532_456240735].mp4
WARNING: The download speed shown is only of one thread. This is a known issue and patches are welcome
[download] 100% of 1.47GiB in 00:49
WARNING: Unable to extract metadata: ffprobe not found. Please install or provide the path using --ffmpeg-location
[FixupM3u8] Fixing MPEG-TS in MP4 container of "Zaczyna się dziać dobrze  --) [-201956532_456240735].mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:Zaczyna się dziać dobrze  --) [-201956532_456240735].mp4" -c copy -map 0 -dn -f mp4 "-bsf:a" aac_adtstoasc -movflags "+faststart" "file:Zaczyna się dziać dobrze  --) [-201956532_456240735].temp.mp4"
```

**Comment by pukkandan** [comment]
> [debug] exe versions: ffmpeg N-104676-g5593f5cf24-ffmpeg-windows-build-helpers (fdk)

yt-dlp is only seeing `ffmpeg` in PATH, not `ffprobe`. Show me the output of `where ffprobe` run rom the same working dir

**Comment by PatrykMis** [comment]
```
ffprobe version N-104676-g5593f5cf24-ffmpeg-windows-build-helpers Copyright (c) 2007-2021 the FFmpeg developers
  built with gcc 10.2.0 (GCC)
  configuration: --pkg-config=pkg-config --pkg-config-flags=--static --extra-version=ffmpeg-windows-build-helpers --enable-version3 --disable-debug --disable-w32threads --arch=x86_64 --target-os=mingw32 --cross-prefix=/home/patryk/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/bin/x86_64-w64-mingw32- --enable-libcaca --enable-gray --enable-libtesseract --enable-fontconfig --enable-gmp --enable-gnutls --enable-libass --enable-libbluray --enable-libbs2b --enable-libflite --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopus --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libvorbis --enable-libwebp --enable-libzimg --enable-libzvbi --enable-libmysofa --enable-libopenjpeg --enable-libopenh264 --enable-liblensfun --enable-libvmaf --enable-libsrt --enable-libxml2 --enable-opengl --enable-libdav1d --enable-cuda-llvm --enable-libsvthevc --enable-libsvtav1 --enable-libaom --enable-libvpx --enable-nvenc --enable-nvdec --extra-libs=-lharfbuzz --extra-libs=-lm --extra-libs=-lpthread --extra-cflags=-DLIBTWOLAME_STATIC --extra-cflags=-DMODPLUG_STATIC --extra-cflags=-DCACA_STATIC --enable-amf --enable-libmfx --enable-gpl --enable-frei0r --enable-librubberband --enable-libvidstab --enable-libx264 --enable-libx265 --enable-avisynth --enable-libaribb24 --enable-libxvid --enable-libdavs2 --enable-libxavs2 --enable-libxavs --extra-cflags='-mtune=generic' --extra-cflags=-O3 --enable-shared --disable-static --prefix=/home/patryk/ffmpeg-windows-build-helpers/sandbox/win64/ffmpeg_git_with_fdk_aac_shared --enable-nonfree --enable-libfdk-aac --enable-decklink
  libavutil      57.  9.101 / 57.  9.101
  libavcodec     59. 13.101 / 59. 13.101
  libavformat    59.  9.102 / 59.  9.102
  libavdevice    59.  0.101 / 59.  0.101
  libavfilter     8. 17.100 /  8. 17.100
  libswscale      6.  1.100 /  6.  1.100
  libswresample   4.  0.100 /  4.  0.100
  libpostproc    56.  0.100 / 56.  0.100
Simple multimedia streams analyzer
usage: ffprobe [OPTIONS] [INPUT_FILE]

You have to specify one input file.
Use -h to get full help or, even better, run 'man ffprobe'.
```

**Comment by pukkandan** [comment]
> Show me the output of `where ffprobe` run from the same working dir

Showing ffprobe output doesn't tell me anything. Actually, since you are saying it's in the same directory, it's even better to give output of `dir` from that folder

Also, try using `--ffmpeg-location` just in case

**Comment by CagesThrottleUs** [comment]
This works for me, I tried it on my system.

### Verbose log
[debug] Command-line config: ['--concurrent-fragments', '8', '-Uv', 'https://vk.com/video-201956532_456240735']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2021.12.31 [1c8970b] (win_exe)
[debug] ** This build is unofficial daily builds, provided for ease of use.
[debug] ** Please do not ask for any support.
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] exe versions: ffmpeg n4.4.1-3-g7450be2f0b-20211220 (setts), ffprobe n4.4.1-3-g7450be2f0b-20211220
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.01.01.114514, Current version: 2021.12.31
Current Build Hash 35d17a3d35bacdd3edb6a2c803d7a173442fd5370a93192ac59619dcfdabd8bf
Updating to version 2022.01.01.114514 ...
ERROR: Unable to fetch updates; Visit  https://github.com/yt-dlp/yt-dlp/releases/latest
[debug] [vk] Extracting URL: https://vk.com/video-201956532_456240735
[vk] -201956532_456240735: Downloading JSON metadata
[vk] -201956532_456240735: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] -201956532_456240735: Downloading 1 format(s): hls-3203
[debug] Invoking downloader on "https://vk6-7.vkuser.net/expires/1641274919343/srcIp/185.252.221.149/pr/43/srcAg/CHROME/ms/95.142.206.166/type/3/sig/p9cTHNiN8VY/ct/8/urls/45.136.22.171%3B45.136.21.140/clientType/13/zs/43/id/2543581727232/video/"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 393
[download] Destination: Zaczyna się dziać dobrze  --) [-201956532_456240735].mp4
WARNING: The download speed shown is only of one thread. This is a known issue and patches are welcome
[download]  18.0% of ~1.51GiB at 61.07KiB/s ETA 02:35 (frag 71/393)[download] Got server HTTP error: <urlopen error _ssl.c:1114: The handshake operation timed out>. Retrying (attempt 1 of 10) ...
[download] 100% of 1.47GiB in 02:59
[debug] ffprobe command line: ffprobe -hide_banner -show_format -show_streams -print_format json "file:Zaczyna się dziać dobrze  --) [-201956532_456240735].mp4"
[FixupM3u8] Fixing MPEG-TS in MP4 container of "Zaczyna się dziać dobrze  --) [-201956532_456240735].mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:Zaczyna się dziać dobrze  --) [-201956532_456240735].mp4" -c copy -map 0 -dn -f mp4 "-bsf:a" aac_adtstoasc -movflags "+faststart" "file:Zaczyna się dziać dobrze  --) [-201956532_456240735].temp.mp4"

### What needs to be done
This looks like that you do not have the proper ffprobe from the latest auto-build present [here](https://github.com/yt-dlp/FFmpeg-Builds/releases) (prefer to use the latest). You should download the proper version from here and perform the following operations.

Go to your terminal/command prompt and type `where ffprobe` and execute and whatever is the output please share here.

### My guess
This is something you **should** ignore at first, this is meant for devs. I think OP is using the ffmpeg the windows version in their Linux machine. This is a guess from `--cross-prefix` and `--prefix`, which on my system returns `--prefix=/ffbuild/prefix` and `--cross-prefix=x86_64-w64-mingw32-` as i have Windows 10.

**Comment by pukkandan** [comment]
His original verbose log shows windows

> [debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19043-SP0

**Comment by CagesThrottleUs** [comment]
Then it's issue of ffprobe being not installed.

**Comment by PatrykMis** [comment]
Problem solved. ffprobe was installed but it is my own build which yt-dlp doesn't recognize for whatever reason (stricte yt-dlp problem, no problem with any different software)…
With https://github.com/yt-dlp/FFmpeg-Builds/releases/ it works.
