### ISSUE TITLE
Python yt-dlp module spamming console in quiet mode

### ISSUE THREAD

**Issue by Bowarc** [yt-dlp/yt-dlp#2143]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2021.12.27**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

Hey, im using yt-dlp's python module and my console if filled with logs that i diddn't asked for as i am in quiet mode.
i already have my custom logger for the logs i want.
My console output after one `yt_dlp.YoutubeDL` call:
```
[download]   0.1% of 12.84MiB at  3.41MiB/s ETA 00:03[02:30:43] [app:42] [Thread:(MainThread)] [WARNING]: Downloader event not handled: Type: prcentUpdate, Msg: 0.0
[02:30:43] [app:42] [Thread:(MainThread)] [WARNING]: Downloader event not handled: Type: prcentUpdate, Msg: 0.0
[02:30:43] [app:42] [Thread:(MainThread)] [WARNING]: Downloader event not handled: Type: prcentUpdate, Msg: 0.1
[download]   0.1% of 12.84MiB at  1.33MiB/s ETA 00:09[02:30:43] [app:42] [Thread:(MainThread)] [WARNING]: Downloader event not handled: Type: prcentUpdate, Msg: 0.1
[download]   0.2% of 12.84MiB at  1.97MiB/s ETA 00:06[02:30:43] [app:42] [Thread:(MainThread)] [WARNING]: Downloader event not handled: Type: prcentUpdate, Msg: 0.2
[download]   0.5% of 12.84MiB at  2.52MiB/s ETA 00:05[02:30:43] [app:42] [Thread:(MainThread)] [WARNING]: Downloader event not handled: Type: prcentUpdate, Msg: 0.5
[download]   1.0% of 12.84MiB at  3.72MiB/s ETA 00:03[02:30:43] [app:42] [Thread:(MainThread)] [WARNING]: Downloader event not handled: Type: prcentUpdate, Msg: 1.0
[download]   1.9% of 12.84MiB at  5.43MiB/s ETA 00:02[02:30:43] [app:42] [Thread:(MainThread)] [WARNING]: Downloader event not handled: Type: prcentUpdate, Msg: 1.9
[download]   3.9% of 12.84MiB at  7.35MiB/s ETA 00:01[02:30:43] [app:42] [Thread:(MainThread)] [WARNING]: Downloader event not handled: Type: prcentUpdate, Msg: 3.9
[download]   7.8% of 12.84MiB at  8.91MiB/s ETA 00:01[02:30:43] [app:42] [Thread:(MainThread)] [WARNING]: Downloader event not handled: Type: prcentUpdate, Msg: 7.8
[download]  15.6% of 12.84MiB at  9.99MiB/s ETA 00:01[02:30:43] [app:42] [Thread:(MainThread)] [WARNING]: Downloader event not handled: Type: prcentUpdate, Msg: 15.6
[download]  31.1% of 12.84MiB at 10.57MiB/s ETA 00:00[02:30:43] [app:42] [Thread:(MainThread)] [WARNING]: Downloader event not handled: Type: prcentUpdate, Msg: 31.1
[download]  62.3% of 12.84MiB at 10.89MiB/s ETA 00:00[02:30:44] [app:42] [Thread:(MainThread)] [WARNING]: Downloader event not handled: Type: prcentUpdate, Msg: 62.3
[download]  93.4% of 12.84MiB at 11.02MiB/s ETA 00:00[02:30:44] [app:42] [Thread:(MainThread)] [WARNING]: Downloader event not handled: Type: prcentUpdate, Msg: 93.4
[02:30:44] [app:42] [Thread:(MainThread)] [WARNING]: Downloader event not handled: Type: prcentUpdate, Msg: 100
```
note that warnings logs, for example: `[02:30:44] [app:42] [Thread:(MainThread)] [WARNING]: Downloader event not handled: Type: prcentUpdate, Msg: 100` are my logger's prints
but everything else are yt-dlp's (still in quiet mode btw)

My options:
``` 
options = {
    "format": dlArgs.format.name,
    "progress_hooks": [self.customYtdlHook],
    "noplaylist": dlArgs.noPlaylist,
    "outtmpl": f"{dlArgs.path}/%(title)s-%(id)s.%(ext)s",
    "quiet": True,
}
```
It's mainly custom class calls, but you got the point.

Please make a silent mode or fix the quiet mode koz it's curently verry anoying.
Or maybe that's something that i diddn't understood ?

Overall a rly good python module

### Verbose log

```shell
Well, im using the python module not the command line aruments, so i don't have any logs to put here ..
```

**Comment by pukkandan** [comment]
Add `'noprogress': True` to your options

**Comment by Bowarc** [comment]
> Add `'noprogress': True` to your options
> 
> Note: If you use an external downloader, it's output may still be printed to console

It's working, thank you.
Is there a documentation for the python module ? i can't seem to find any, and that could prevent dumb questions like this.

**Comment by pukkandan** [comment]
There is some basic instructions here: https://github.com/yt-dlp/yt-dlp#embedding-yt-dlp

For more details, look at the docstrings - especially of YoutubeDL https://github.com/yt-dlp/yt-dlp/blob/master/yt_dlp/YoutubeDL.py#L165

**Comment by Bowarc** [comment]
Thanks
