### ISSUE TITLE
PRX podcast support

### ISSUE THREAD

**Issue by dredmorbius** [yt-dlp/yt-dlp#2144]
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2021.12.27**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

United States

### Example URLs

- Single audio:  https://beta.prx.org/stories/239600
- Podcast channel:  https://beta.prx.org/series/37658

### Description

PRX are a major producer of podcasts, serving over 70 million downloads per month according to https://www.prx.org/company/about/

The site is not presently supported by yt-dlp.

### Verbose log

```shell
[debug] Command-line config: ['-Uv', 'https://exchange.prx.org/pieces/239600-tpp-17-55-final-edition']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8 (No ANSI), err utf-8 (No ANSI), pref UTF-8
[debug] yt-dlp version 2021.12.01 [91f071af6]
[debug] Python version 3.10.1 (CPython 64bit) - Linux-4.4.194-perf-g4294a15-dirty-aarch64-with-libc
[debug] exe versions: ffmpeg 4.4.1 (setts), ffprobe 4.4.1
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2021.12.27, Current version: 2021.12.01
ERROR: It looks like you installed yt-dlp with a package manager, pip, setup.py or a tarball; Use that to update
[debug] [generic] Extracting URL: https://exchange.prx.org/pieces/239600-tpp-17-55-final-edition
[generic] 239600-tpp-17-55-final-edition: Requesting header
[redirect] Following redirect to https://beta.prx.org/stories/239600
[debug] [generic] Extracting URL: https://beta.prx.org/stories/239600
[generic] 239600: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] 239600: Downloading webpage
[generic] 239600: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://beta.prx.org/stories/239600
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1329, in wrapper
    return func(self, *args, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1398, in __extract_info
    ie_result = ie.extract(url)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 597, in extract
    ie_result = self._real_extract(url)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/yt_dlp/extractor/generic.py", line 3813, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://beta.prx.org/stories/239600
```

**Comment by coletdjnz** [comment]
Related upstream request: https://github.com/ytdl-org/youtube-dl/issues/15948
This site appears to be in beta, but has been for years. 

Everything seems to requested through the JSON API (`cms.prx.org/api/v1`) which is nice.

There is also the PRX exchange site which seems older as an alternative to access media.
E.g. https://exchange.prx.org/group/truthpoliticsandpower?m=false, https://exchange.prx.org/playlists/354104
 I don't think we'll add support for this - if anything - we can just redirect things to the "beta" PRX extractors.
