### ISSUE TITLE
Offer Beta and Stable releases?

### ISSUE THREAD

**Issue by MintMain21** [yt-dlp/yt-dlp#2145]
### Checklist

- [X] I'm reporting a feature request
- [X] I've verified that I'm running yt-dlp version **2021.12.27**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

I started using YT-DLP with the December 1st release. After updating to the December 27th release, I encountered numerous bugs that drove me back to the December 1st release. I realize it's important to report bugs in the most up-to-date releases, but I also realize that it's difficult to do so with so many users asking basic questions that aren't bugs in themselves, or may otherwise be resolved simply without updating the software.

I propose then splitting YT-DLP into two seperate repositories on Github. One that is "Bleeding Edge" (a Beta Release) and one where the features aren't quite up to date but everything is overall stable (a Stable Release).

**Comment by pukkandan** [comment]
If you find regressions, report them and I will fix them asap. I take regressions very seriously. But I will not be maintaining two separate versions of the project
