### ISSUE TITLE
Mediaset Infinity broken

### ISSUE THREAD

**Issue by Mishosan** [yt-dlp/yt-dlp#2149]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2021.12.27**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Italy

### Description

I cannot download from videos from Mediaset Inifinity anymore.

The video I tried to download:

yt-dlp --verbose https://www.mediasetplay.mediaset.it/movie/selvaggi/selvaggi_F006474501000101

^^It's watchable in the browser.

### Verbose log

```shell
[debug] Command-line config: ['--verbose', 'https://www.mediasetplay.mediaset.it/movie/selvaggi/selvaggi_F006474501000101']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2021.12.27 [6223f67a8]
[debug] Python version 3.8.10 (CPython 64bit) - Linux-5.15.11-xanmod1-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.4.1 (setts), ffprobe 4.4.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome, secretstorage, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [Mediaset] Extracting URL: https://www.mediasetplay.mediaset.it/movie/selvaggi/selvaggi_F006474501000101
[Mediaset] F006474501000101: Downloading JSON metadata
[Mediaset] F006474501000101: Downloading MPEG4 SMIL data
ERROR: [Mediaset] F006474501000101: None of the available releases match the specified AssetType, ProtectionScheme, and/or Format preferences
  File "/home/<USER>/.local/lib/python3.8/site-packages/yt_dlp/extractor/common.py", line 599, in extract
    ie_result = self._real_extract(url)
  File "/home/<USER>/.local/lib/python3.8/site-packages/yt_dlp/extractor/mediaset.py", line 188, in _real_extract
    raise first_e
  File "/home/<USER>/.local/lib/python3.8/site-packages/yt_dlp/extractor/mediaset.py", line 175, in _real_extract
    tp_formats, tp_subtitles = self._extract_theplatform_smil(
  File "/home/<USER>/.local/lib/python3.8/site-packages/yt_dlp/extractor/theplatform.py", line 48, in _extract_theplatform_smil
    raise ExtractorError(
```

**Comment by pukkandan** [comment]
@nixxo

**Comment by dirkf** [comment]
https://github.com/ytdl-org/youtube-dl/issues/30411

**Comment by pukkandan** [comment]
Yes, this error appears for DRM content. But it can also appear if the asset types we are requesting is incomplete. So further investigation is needed
