### ISSUE TITLE
How to burn mp4s downloaded with latest yt-dlp to Blue-Ray BD-R?

### ISSUE THREAD

**Issue by freddy3333** [yt-dlp/yt-dlp#2155]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

I'm using this command with the latest yt-dlp (2021.12.27) to download yt videos in 1080 (converted to .mp4) for burning to blu-ray BD-R discs:
`yt-dlp -a videos.txt -f "bestvideo[height<=?1080]+bestaudio/best" --merge-output-format mp4`

The videos download, convert to .mp4 and are playable via the latest VLC player, but my blu-ray burning program (TMPGEnc Authoring Works) produces a "Cannot open the file" error when I attempt to add any of the .mp4s from yt-dlp. However, if I download the same videos with Video Download Capture, they burn and playback perfectly. Is there a command I'm missing?

p.s. This may be a clue: The yt-dlp .mp4s are smaller than the same .mp4 downloaded/converted by Video Download Capture (1,403Kb vs 2,093Kb, respectively).

**Comment by pukkandan** [comment]
Your burning program probably can't process the codecs you are downloading. Check all available formats in `-F`. `avc1+m4a` is generally a safe bet since most programs will atleast have support for it

**Comment by freddy3333** [comment]
pukkandan: Thank you for the quick response. I added the two commands you indicated:
`yt-dlp -a videos2.txt -F avc1+m4a "bestvideo[height<=?1080]+bestaudio/best" --merge-output-format mp4`

But that produced an error:
```
ERROR: [generic] 'avc1+m4a' is not a valid URL. Set --default-search "ytsearch" (or run  yt-dlp "ytsearch:avc1+m4a" ) to search YouTube
ERROR: [generic] 'bestvideo[height<=?1080]+bestaudio/best' is not a valid URL. Set --default-search "ytsearch" (or run  yt-dlp "ytsearch:bestvideo[height<=?1080]+bestaudio/best" ) to search YouTube
```

**Comment by freddy3333** [comment]
I apologize if I'm missing something simple/obvious, but I think I'm just downloading .webm, which yt-dlp is converting to .mp4. Here is the yt-dlp output I get using my original command:
```
[youtube] n8OcGw_2SVI: Downloading webpage
[youtube] n8OcGw_2SVI: Downloading android player API JSON
[info] n8OcGw_2SVI: Downloading 1 format(s): 247+251
[download] Destination: Bye Bye Love (25 Jan 1969) - The Beatles [n8OcGw_2SVI].f247.webm
[download] 100% of 491.91KiB in 00:00
[download] Destination: Bye Bye Love (25 Jan 1969) - The Beatles [n8OcGw_2SVI].f251.webm
[download] 100% of 880.84KiB in 00:00
[Merger] Merging formats into "Bye Bye Love (25 Jan 1969) - The Beatles [n8OcGw_2SVI].mp4"
Deleting original file Bye Bye Love (25 Jan 1969) - The Beatles [n8OcGw_2SVI].f247.webm (pass -k to keep)
Deleting original file Bye Bye Love (25 Jan 1969) - The Beatles [n8OcGw_2SVI].f251.webm (pass -k to keep)
```

**Comment by pukkandan** [comment]
That was not a command. That was what to look for in the format list (`-F`). A command for always selecting such formats would look something like:

    yt-dlp -S "res:1080,codec:avc1:m4a" URL

**Comment by freddy3333** [comment]
pukkandan: Brilliant!

Thank you!
