### ISSUE TITLE
ORF Live failed, but...

### ISSUE THREAD

**Issue by anunasica** [yt-dlp/yt-dlp#2157]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2021.12.27**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

Hi, youtube-dl is able to download this live (you can try it right now, the live is still active!)
https://tvthek.orf.at/live/-/14151305?fbclid=IwAR1xP6Kit5XZM14MrIzIN3NxfoiRqiqBbxSG12Jcf-gnEk8ukUcWmxBiOHM
while your app was not :( 
thanks for fix for the next time.

### Verbose log

```shell
DLP:
https://postimg.cc/r0syrhcc

vs.

YT-DL:
https://postimg.cc/4KJxJfSY
```

**Comment by Ashish0804** [comment]
Shit title, clearly related to a specific site, no verbose log.

**Comment by anunasica** [comment]
thanks for you help.

**Comment by pukkandan** [comment]
Can be re-opened if you can provide the complete verbose logs
