### ISSUE TITLE
"Thailand" Hotstar

### ISSUE THREAD

**Issue by daliali2088** [yt-dlp/yt-dlp#2160]
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2021.12.27**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Thailand

### Example URLs

https://www.hotstar.com/th/tv/snowdrop/1260075599/episode-5/1260075826

### Description

Requesting support for "Thailand" Hotstar, I used the same command as India and was told "ERROR: Unsupported URL"

### Verbose log

```shell
C:\Users\Administrator\Desktop\mp4jiemi>yt-dlp -k --allow-unplayable-formats --cookies-from-browser edge "https://www.hotstar.com/th/tv/snowdrop/1260075599/episode-5/1260075826"
WARNING: You have asked for UNPLAYABLE formats to be listed/downloaded. This is a developer option intended for debugging.
         If you experience any issues while using this option, DO NOT open a bug report
[Cookies] Extracting cookies from edge
[Cookies] Extracted 2090 cookies from edge
[generic] 1260075826: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] 1260075826: Downloading webpage
[generic] 1260075826: Extracting information
ERROR: Unsupported URL: https://www.hotstar.com/th/tv/snowdrop/1260075599/episode-5/1260075826
```

**Comment by Ashish0804** [comment]
You are using auf

**Comment by daliali2088** [comment]
> You are using auf

What is 'auf'? Is there any way to download it?

**Comment by nao20010128nao** [comment]
`--allow-unplayable-formats`

**Comment by daliali2088** [comment]
> `--allow-unplayable-formats`

But I deleted '--allow-unplayable-formats' and was told it was not supported

```
C:\Users\Administrator\Desktop\mp4jiemi>yt-dlp -vU -k --cookies-from-browser edge "https://www.hotstar.com/th/tv/snowdrop/1260075599/episode-5/1260075826"
[debug] Command-line config: ['-vU', '-k', '--cookies-from-browser', 'edge', 'https://www.hotstar.com/th/tv/snowdrop/1260075599/episode-5/1260075826']
.
.
.
[debug] [generic] Extracting URL: https://www.hotstar.com/th/tv/snowdrop/1260075599/episode-5/1260075826
[generic] 1260075826: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] 1260075826: Downloading webpage
[generic] 1260075826: Extracting information
[debug] Looking for video embeds
**ERROR: Unsupported URL: https://www.hotstar.com/th/tv/snowdrop/1260075599/episode-5/1260075826**
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1353, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1423, in __extract_info
  File "yt_dlp\extractor\common.py", line 599, in extract
  File "yt_dlp\extractor\generic.py", line 3829, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.hotstar.com/th/tv/snowdrop/1260075599/episode-5/1260075826
```

**Comment by nyuszika7h** [comment]
It does seem like Hotstar Thailand support might be missing, but that particular show is part of Disney+ Hotstar so it probably has DRM anyway.

**Comment by daliali2088** [comment]
> It does seem like Hotstar Thailand support might be missing, but that particular show is part of Disney+ Hotstar so it probably has DRM anyway.

Ok, I see what you mean, thanks for the answer

**Comment by Ashish0804** [comment]
I thought of generalizing hs earlier this year but Wikipedia said they were going to expand aggressively in 2021. Now that the year has ended, I'll think about doing it in first quarter of 2022.

That being said, this issue helps no one.
A proper issue would be movie, episode and series urls atleast for each country and all urls must be free.
