### ISSUE TITLE
yt-dlp: error: Invalid time range to wait

### ISSUE THREAD

**Issue by sebi-berlin** [yt-dlp/yt-dlp#2176]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2021.12.27**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

I am using the new --wait-for-video flag as I want to start a recording, which might get flagged private after the premiere. In my case, the premiere is in 30 hours. Could that already be the problem? Is there a maximum time to wait? 

Unfortunately the verbose log, doesn't give much info: 

### Verbose log

```shell
yt-dlp -Uv --wait-for-video https://www.youtube.com/watch?v=9kWrYzt4lF4
[debug] Command-line config: ['-Uv', '--wait-for-video', 'https://www.youtube.com/watch?v=9kWrYzt4lF4']
Usage: yt-dlp [OPTIONS] URL [URL...]

yt-dlp: error: Invalid time range to wait
```

**Comment by pukkandan** [comment]
```
    --wait-for-video MIN[-MAX]       Wait for scheduled streams to become
                                     available. Pass the minimum number of
                                     seconds (or range) to wait between retries
```

**Comment by sebi-berlin** [comment]
Oops, I see, thank you! :-)
