### ISSUE TITLE
The -O / --print version in the yt-dlp API

### ISSUE THREAD

**Issue by JVT038** [yt-dlp/yt-dlp#2179]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [x] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

Hi,
I want to 'preview' the output filename after entering a template.
For example, if I have an `outtmpl` key with the value `%(track,title)s.%(ext)s`, I'd like to know how the filename is actually going to be, before starting the download process.
I tried to set `simulate` to `True`, but it doesn't work.
Is there a way to do the `-O` / `--print` in python code?

**Comment by pukkandan** [comment]
If you want to print it to console, use the config `forceprint`.

To get it in a variable, run `ydl.evaluate_outtmpl(outtmpl, info_dict)`. You can get the info_dict from `ydl.extract_info(url, download=False)`

If you are asking specifically only about the filename, it is in `info_dict['filepath']`

**Comment by JVT038** [comment]
Thanks, it worked!
