### ISSUE TITLE
TikTok: Failed to parse JSON

### ISSUE THREAD

**Issue by jericjan** [yt-dlp/yt-dlp#2183]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2021.12.27**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [x] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Description

yt-dlp used to be able to take unwatermarked high quality videos from TikTok. Now it doesn't. Is it because of a change in TikTok's API? If I run the command without the `-Uv` flag, it only gives me this as the list of formats:
`0  mp4 576x1024   │ https │ unknown unknown`

The last time it was working for me was on December 15th.

### Verbose log

```shell
>yt-dlp -F -Uv --verbose https://www.tiktok.com/@d_t_quinn/video/7041188621675810049
[debug] Command-line config: ['-F', '-Uv', '--verbose', 'https://www.tiktok.com/@d_t_quinn/video/7041188621675810049']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2021.12.27 [6223f67] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg git-2020-05-28-c0f01ea, ffprobe git-2020-05-28-c0f01ea
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2021.12.27, Current version: 2021.12.27
yt-dlp is up to date (2021.12.27)
[debug] [TikTok] Extracting URL: https://www.tiktok.com/@d_t_quinn/video/7041188621675810049
[TikTok] 7041188621675810049: Downloading video details
WARNING: [TikTok] 7041188621675810049: Failed to parse JSON  (caused by JSONDecodeError('Expecting value: line 1 column 1 (char 0)')); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.; Retrying with webpage
[TikTok] 7041188621675810049: Downloading webpage
[TikTok] 7041188621675810049: Downloading video webpage
ERROR: [TikTok] 7041188621675810049: Unable to extract json_string; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
  File "yt_dlp\extractor\common.py", line 599, in extract
  File "yt_dlp\extractor\tiktok.py", line 368, in _real_extract
  File "yt_dlp\extractor\common.py", line 1173, in _search_regex
```

**Comment by MinePlayersPE** [comment]
> - [x] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates

Duplicate of https://github.com/yt-dlp/yt-dlp/issues/2133 and sort of duplicate of https://github.com/yt-dlp/yt-dlp/issues/2135

**Comment by jericjan** [comment]
My bad. I'll close this.
