### ISSUE TITLE
[TikTok] Add subtitles support

### ISSUE THREAD

**Issue by LeaPhant** [yt-dlp/yt-dlp#2184]
### Checklist

- [X] I'm reporting a site feature request
- [X] I've verified that I'm running yt-dlp version **2021.12.27**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Germany

### Example URLs

https://www.tiktok.com/@hankgreen1/video/7047596209028074758

### Description

TikTok has built-in captioning support which is used widely since you can automatically generate captions when posting. They only show up in the mobile apps (not the web version) and the creator can choose the vertical position at which they appear.

![image](https://user-images.githubusercontent.com/14080165/147816265-cc13ef8d-4a98-422b-bd5e-477eadae2ed2.png)

Supporting these in yt-dlp would be great for accessibility.

### Verbose log

```shell
[debug] Command-line config: ['-Uv', '--list-subs', 'https://www.tiktok.com/@hankgreen1/video/7047596209028074758']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2021.12.27 [6223f67a8]
[debug] Lazy loading extractors is disabled
[debug] Python version 3.9.6 (CPython 64bit) - Linux-5.13.12-arch1-1-x86_64-with-glibc2.33
[debug] exe versions: ffmpeg 4.4 (setts), ffprobe 4.4, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2021.12.27, Current version: 2021.12.27
yt-dlp is up to date (2021.12.27)
[debug] [TikTok] Extracting URL: https://www.tiktok.com/@hankgreen1/video/7047596209028074758
[TikTok] 7047596209028074758: Downloading video details
[debug] Sort order given by extractor: quality, codec, size, br
[debug] Formats sorted by: hasvid, ie_pref, quality, vcodec, acodec, filesize, fs_approx, tbr, vbr, abr, lang, res, fps, hdr:12(7), asr, proto, vext, aext, hasaud, source, id
7047596209028074758 has no subtitles
```

**Comment by hcbille** [comment]
I just went back to this to find that this has broken again. Just an FYI.
