### ISSUE TITLE
TikTok - Get full size profile photo

### ISSUE THREAD

**Issue by UweLau** [yt-dlp/yt-dlp#2186]
### Checklist

- [X] I'm reporting a feature request
- [X] I've verified that I'm running yt-dlp version **2021.12.27**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

I want to request a feature to get the full size profile picture of the TikTok user account I am downloading from.
In the web app it now shows only the 100x100 version, it used to show the 720x720 version on the web. It seems it is also possible to get 1080x1080. For further reference see https://www.instafollowers.co/tiktok-profile-picture-size

**Comment by pukkandan** [comment]
@MinePlayersPE Do you know whether this is possible?

**Comment by UweLau** [comment]
@MinePlayersPE @pukkandan 
I did some digging of my own and it seems this would be an easy thing to implement. In the source of the website there are JSON tables where the interesting is the "UserModule". Right under "users" there are several pointers to the different profile pictures URLs, there is a "avatarLarger" which has the 1080x1080 version and also a "avatarMedium" with the 720x720 version and a "avatarThumb" with the 100x100.

The URL is UTF16+URL encoded like this "https:\u002F\u002Fp16-sign-va.tiktokcdn.com\u002Ftos-maliva-avt-0068\u002F384b1f1....8dd~c5_1080x1080.jpeg?x-expires=1641823200&x-signature=cLAQ5...jX38%3D" which translates to "https://p16-sign-va.tiktokcdn.com/tos-maliva-avt-0068/384b1f1....8dd~c5_1080x1080.jpeg?x-expires=1641823200&x-signature=cLAQ5...jX38="

Would be nice if you could include that one somehow in the source so it would download the profile picture whenever there is a change (maybe introduce some parameter --avatar)
