### ISSUE TITLE
Download videos from facebook with shortened links (fb.watch/123) not working

### ISSUE THREAD

**Issue by go-ive** [yt-dlp/yt-dlp#2187]
### Checklist

- [X] I'm reporting a site feature request
- [X] I've verified that I'm running yt-dlp version **2021.12.27**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Austria

### Example URLs

https://fb.watch/a6Hq7Wq__5

### Description

This kind of URL redirects to a supported facebook videos URL: https://www.facebook.com/165608444009109/videos/637638560246579/?extid=NS-UNK-UNK-UNK-AN_GK0T-GK1C&ref=sharing

The fb.watch part gets created when a video is shared via some other app. It's a simple redirect that is missing here.

### Verbose log

```shell
$ yt-dlp -vU https://fb.watch/a6Hq7Wq__5
[debug] Command-line config: ['-vU', 'https://fb.watch/a6Hq7Wq__5']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2021.12.27 [6223f67a8]
[debug] Python version 3.8.10 (CPython 64bit) - Linux-5.4.72-microsoft-standard-WSL2-x86_64-with-glibc2.29
[debug] exe versions: none
[debug] Optional libraries: Cryptodome, secretstorage, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2021.12.27, Current version: 2021.12.27
yt-dlp is up to date (2021.12.27)
[debug] [generic] Extracting URL: https://fb.watch/a6Hq7Wq__5
[generic] a6Hq7Wq__5: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] a6Hq7Wq__5: Downloading webpage
[generic] a6Hq7Wq__5: Extracting information
[debug] Looking for video embeds
[redirect] Following redirect to https://fb.watch/a6Hq7Wq__5?_fb_noscript=1
[debug] [generic] Extracting URL: https://fb.watch/a6Hq7Wq__5?_fb_noscript=1
[generic] a6Hq7Wq__5?_fb_noscript=1: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] a6Hq7Wq__5?_fb_noscript=1: Downloading webpage
[generic] a6Hq7Wq__5?_fb_noscript=1: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://fb.watch/a6Hq7Wq__5?_fb_noscript=1
Traceback (most recent call last):
  File "/home/ive/.local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 1353, in wrapper
    return func(self, *args, **kwargs)
  File "/home/ive/.local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 1423, in __extract_info
    ie_result = ie.extract(url)
  File "/home/ive/.local/lib/python3.8/site-packages/yt_dlp/extractor/common.py", line 599, in extract
    ie_result = self._real_extract(url)
  File "/home/ive/.local/lib/python3.8/site-packages/yt_dlp/extractor/generic.py", line 3829, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://fb.watch/a6Hq7Wq__5?_fb_noscript=1
```

**Comment by pukkandan** [comment]
Most likely, same underlying cause as https://github.com/yt-dlp/yt-dlp/issues/2140.

The issue can be temporarily worked around using `--user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.47 Safari/537.36"`

This is a regression introduced in #2023. It appears facebook redirects the URL differently for newer UAs than for the older ones.

cc @fstirlitz

**Comment by fstirlitz** [comment]
Adding a `Sec-Fetch-Mode: navigate` header makes the redirect go through.

<https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Sec-Fetch-Mode> explains it was added in Chrome 76.

Not sure about the best course of action now.

**Comment by pukkandan** [comment]
Since the older user-agents were not causing us any immediate issues, I think it's best to revert the change for the time being

**Comment by OmarShawky1** [comment]
> Most likely, same underlying cause as #2140.
> 
> The issue can be temporarily worked around using `--user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.47 Safari/537.36"`
> 
> This is a regression introduced in #2023. It appears facebook redirects the URL differently for newer UAs than for the older ones.
> 
> cc @fstirlitz

This is the only one working currently

**Comment by anunasica** [comment]
idem
https://fb.watch/gcmxkm0Qeb/

:(
