### ISSUE TITLE
Unable to get subtitles in the same way as the video 

### ISSUE THREAD

**Issue by shirishag75** [yt-dlp/yt-dlp#2189]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2021.12.27**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

I tried downloading subtitles as I do in youtube-dl but somehow there are some changes, for e.g. I do understand that in youtube-dl it is --write-auto-sub while here it is --write-auto-subs but other than that can't make out why it doesn't work :(

I have tried a couple of other videos with the same exact result :(

### Verbose log

```shell
$ yt-dlp -Uv
[debug] Command-line config: ['-Uv']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2021.12.27 [6223f67a8] (zip)
[debug] Python version 3.9.9 (CPython 64bit) - Linux-5.15.0-2-amd64-x86_64-with-glibc2.33
[debug] exe versions: ffmpeg 4.4.1-2 (setts), ffprobe 4.4.1-2, phantomjs 2.1.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome, secretstorage, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2021.12.27, Current version: 2021.12.27
yt-dlp is up to date (2021.12.27)

```

```
$ yt-dlp -c -f 22 -- -F4yTU3LSlI --write-auto-subs
[youtube] -F4yTU3LSlI: Downloading webpage
[youtube] -F4yTU3LSlI: Downloading android player API JSON
[info] -F4yTU3LSlI: Downloading 1 format(s): 22
[download] Build A Medieval Shop _ Medieval Trader Simulator Gameplay _ First look [-F4yTU3LSlI].mp4 has already been downloaded
[download] 100% of 555.51MiB
ERROR: [generic] '--write-auto-subs' is not a valid URL. Set --default-search "ytsearch" (or run  yt-dlp "ytsearch:--write-auto-subs" ) to search YouTube

```
```

**Comment by pukkandan** [comment]
You can't put options after `--`
