### ISSUE TITLE
"Requested format is not available" for video that should be excluded by --match-filter, causing non-zero exit status

### ISSUE THREAD

**Issue by yump** [yt-dlp/yt-dlp#2190]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2021.12.27**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

I think this might be a regression.

I use yt-dlp to youtube channels in audio-only format.  The script containing the yt-dlp command is written to fail early and loudly, because if the anything deviates from what I expected, the result could be very difficult to sort out.

Because it is apparently not possible to get audio-only for live-streaming videos, I skip them with `--match-filter '!is_live'`, and they get picked up on the next run of the script. The filter was added to the script a while back to stop it from erroring out when a youtube channel is currently streaming. I'm fairly certain this fix worked at the time.

But today I ran the script against a channel that was streaming, and it failed with the "Requested format is not available" error, instead of what I expected, which was for the video to be skipped with no error.

The provided log is from a command to download the "lo-fi beats" continuous livestream, which reproduces the problem at the time I am writing this, and hopefully will remain available into the future. 

```
> yt-dlp -j 'https://www.youtube.com/watch?v=5qap5aO4i9A' | jq | grep is_live
  "is_live": true,
  "live_status": "is_live",
```

### Verbose log

```shell
> yt-dlp -Uv -f 'worstaudio[acodec=opus][tbr>=40]/bestaudio' --match-filter '!is_live' 'https://www.youtube.com/watch?v=5qap5aO4i9A'
[debug] Command-line config: ['-Uv', '-f', 'worstaudio[acodec=opus][tbr>=40]/bestaudio', '--match-filter', '!is_live', 'https://www.youtube.com/watch?v=5qap5aO4i9A']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2021.12.27 [6223f67a8] (zip)
[debug] Python version 3.10.1 (CPython 64bit) - Linux-5.15.11-200.fc35.x86_64-x86_64-with-glibc2.34
[debug] exe versions: ffmpeg 4.4.1 (setts), ffprobe 4.4.1
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2021.12.27, Current version: 2021.12.27
yt-dlp is up to date (2021.12.27)
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=5qap5aO4i9A
[youtube] 5qap5aO4i9A: Downloading webpage
[youtube] 5qap5aO4i9A: Downloading android player API JSON
[youtube] 5qap5aO4i9A: Downloading m3u8 information
[youtube] 5qap5aO4i9A: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
ERROR: [youtube] 5qap5aO4i9A: Requested format is not available
Traceback (most recent call last):
  File "/home/rhaley/localbin/yt-dlp/yt_dlp/YoutubeDL.py", line 1353, in wrapper
    return func(self, *args, **kwargs)
  File "/home/rhaley/localbin/yt-dlp/yt_dlp/YoutubeDL.py", line 1437, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/home/rhaley/localbin/yt-dlp/yt_dlp/YoutubeDL.py", line 1489, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/home/rhaley/localbin/yt-dlp/yt_dlp/YoutubeDL.py", line 2535, in process_video_result
    raise ExtractorError('Requested format is not available', expected=True,
yt_dlp.utils.ExtractorError: [youtube] 5qap5aO4i9A: Requested format is not available
```

**Comment by pukkandan** [comment]
why do you say this is a regression? As far as I can see, this behavior is consistent with both older yt-dlp versions as well as with youtube-dl.

It would be difficult to make this work in general since the filter can use format-specific variables. Since you don't care about them, you should be able to make it work using `--ignore-no-formats`

**Comment by yump** [comment]
I had thought `--match-filter '!is_live'` fixed the problem when I first added it to my script, but it's possible that the problem video completed its conversion from live stream to archived stream on Youtube's end while I was buried in documentation and trying to fix the script.

In any case, `--ignore-no-formats-error` does allow skipping livestreams without error, and importantly it *does* seem to fail with error if the stream is not skipped by the filter, although that is not immediately apparent from the man page.  I added that to my script, although it does sound a little bit scary because I'm not sure that the !is_live filter covers all conditions that might cause a no-formats error to arise and be ignored.

Thank you.

**Comment by pukkandan** [comment]
--ignore-no-formats-error tries to ignore any error related to no formats - so that filter, simulate, print etc can run on them. But once the actual download is reached, yt-dlp has no option but to raise the error. (The error message may change though). So it is perfectly safe to use as long as you are actually downloading and not just simulating
