### ISSUE TITLE
vk.com extractor:  User profile video's and or playlists are not able to download, yet a single video still does.

### ISSUE THREAD

**Issue by jzneter** [yt-dlp/yt-dlp#2196]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2021.12.27**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Europe, Russia, Most of asia.

### Description

Due to a update to VK.com.

it seems no longer to be possible to download videos directly from a channel,
for example https://vk.com/video/@mobidevices. (channel is accessable without a vk account)

yet if you select a url such as https://vk.com/video-17892518_456239840 (first video on that channel as of 1-1-2022)
the select video will download, but only that selected video.

i am using the windows build and this issue only happens on VK.com

### Verbose log

```shell
[debug] Command-line config: ['-Uv', '--cookies-from-browser', 'edge', '-o', 'E:\\Principle maindrive\\home\\Joey/0_Video/%(title)s %(channel)s (%(id)s) [%(channel_id)s].%(ext)s', '--add-metadata', '--geo-bypass', '--downloader', 'aria2c', '--downloader-args=aria2c:-x16 -k1M -s16', '--merge-output-format=mkv', '--postprocessor-args=ffmpeg:-threads 2', '--throttled-rate', '100k', 'https://vk.com/video/@mobidevices']
[Cookies] Extracting cookies from edge
[debug] Extracting cookies from: "C:\Users\jzneter\AppData\Local\Microsoft\Edge\User Data\Default\Cookies"
[Cookies] Extracted 719 cookies from edge
[debug] cookie version breakdown: {'v10': 719, 'other': 0, 'unencrypted': 0}
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2021.12.27 [6223f67] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] exe versions: ffmpeg n4.4-154-g79c114e1b2-20210924 (setts), ffprobe n4.4-154-g79c114e1b2-20210924
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2021.12.27, Current version: 2021.12.27
yt-dlp is up to date (2021.12.27)
[debug] [generic] Extracting URL: https://vk.com/video/@mobidevices
[generic] @mobidevices: Requesting header
WARNING: [generic] Could not send HEAD request to https://vk.com/video/@mobidevices: HTTP Error 418:
[generic] @mobidevices: Downloading webpage
WARNING: [generic] Falling back on generic information extractor.
[generic] @mobidevices: Extracting information
[debug] Looking for video embeds
[redirect] Following redirect to https://vk.com/badbrowser.php
[debug] [generic] Extracting URL: https://vk.com/badbrowser.php
[generic] badbrowser: Requesting header
WARNING: [generic] Could not send HEAD request to https://vk.com/badbrowser.php: HTTP Error 418:
[generic] badbrowser: Downloading webpage
WARNING: [generic] Falling back on generic information extractor.
[generic] badbrowser: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://vk.com/badbrowser.php
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1353, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1423, in __extract_info
  File "yt_dlp\extractor\common.py", line 599, in extract
  File "yt_dlp\extractor\generic.py", line 3829, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://vk.com/badbrowser.php
```

**Comment by pukkandan** [comment]
Are you sure this used to work? As far as I can see, this would never have worked...

**Comment by jzneter** [comment]
> Are you sure this used to work? As far as I can see, this would never have worked...

Yes, i used to download entire channels a few months ago, and when it stopped working i didnt had the time to report this. This weekend i had the time, so thats why you only see it now

**Comment by Ashish0804** [comment]
Can be done since there's an API
```bash
curl 'https://vk.com/al_video.php?act=load_videos_silent' \
  -H 'authority: vk.com' \
  -H 'user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36' \
  -H 'x-requested-with: XMLHttpRequest' \
  -H 'content-type: application/x-www-form-urlencoded' \
  -H 'accept: */*' \
  -H 'sec-gpc: 1' \
  -H 'origin: https://vk.com' \
  -H 'sec-fetch-site: same-origin' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-dest: empty' \
  -H 'referer: https://vk.com/video/@mobidevices' \
  -H 'accept-language: en-US,en;q=0.9' \
  -H 'cookie: remixlang=3; remixlgck=45217a05110d236ee1; remixstid=1911976896_c336zy2NPGs54dRkmgVRSl8ihNryDrF1hDL5gnE6jdc; remixflash=0.0.0; remixscreen_width=1536; remixscreen_height=864; remixscreen_dpr=1.25; remixscreen_depth=24; remixdt=9000; remixrefkey=42835fee5ec1d229fa; remixscreen_orient=1; remixgp=a3e0487769e8e984dd012122aa7da332; remixQUIC=1; remixscreen_winzoom=2.90; remixsts=%7B%22data%22%3A%5B%5B1641069820%2C%22browser_features%22%2C%22current_scheme%3A2/is_auto_schemes_supported%3A1/is_schemes_supported%3A1%22%5D%5D%2C%22uniqueId%22%3A934022566%7D' \
  --data-raw 'al=1&need_albums=0&offset=0&oid=-17892518&rowlen=3&section=all&snippet_video=0' \
  --compressed
```
The result is beyond retarded tho....
I'll try to add this is tomorrow

**Comment by Ashish0804** [comment]
@jzneter can u provide an url with around 150 videos?
Or can you manually confirm how many videos does the url u provided has?

**Comment by jzneter** [comment]
> @jzneter can u provide an url with around 150 videos? Or can you manually confirm how many videos does the url u provided has?

The url provided has quite a lot of videos but i will try to find one that fits your description.

**Comment by jzneter** [comment]
Found this one that has around 516 videos in total. https://vk.com/video/@englishpolls

**Comment by Ashish0804** [comment]
The api is kinda retarded tbh.
even when u explicitly ask it to return say `100` videos, it returns like 90
then the code thinks that since we asked for 100 but it returned 100, so that proly means there are no more videos to return and it stops thus resulting in some missed videos.

I'll see if i can solve this someway

**Comment by pukkandan** [comment]
@Ashish0804 If it doesnt return a reliable number of vids, dont use PagedList and just use a generator instead
