### ISSUE TITLE
Download Simplified Comments

### ISSUE THREAD

**Issue by TheYellowArchitect** [yt-dlp/yt-dlp#2202]
### Checklist

- [X] I'm reporting a feature request
- [X] I've verified that I'm running yt-dlp version **2021.12.27**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

--write-comments is my most-used option, but it is machine data not meant for humans.

I would like to request --write-simplified-comments
It would parse the --write-comments .json file, to make a new simple .json file, and delete the --write-comments .json

JSON Format
- - - - - - - - - - - -
Description

======
comment1
comment2
comment3
- - - - - - - - - - - -

^And so on. Optimally, there would be nested comments displayed, with an inline/tab below the parent comment.
But honestly, just having the comments by themselves as displayed above, works great (no likes, no username)

Description and comments are often what you read after you see a great video, and both are part of any great video platform. This would allow yt-dlp to fully replace youtube for users like me

**Comment by pukkandan** [comment]
Everyone will want it to be in a different format and have different amounts of data. You should use either a plugin PP, `jq` or a third party script to convert it into whatever format you need

Here's an example script that writes nested comments in a separate json: https://gist.github.com/pukkandan/ee737fec64822f2552caf3ca4cbf5db7

**Comment by TheYellowArchitect** [comment]
> Everyone will want it to be in a different format and have different amounts of data. 
I disagree. What I asked in reality is --write-minimal-comments, yet you tell me of timestamp data or likedata or username data mattering. This functionality doesn't even exist, how can you claim that everyone will somehow care about an optional addition?

I will use your script for my current usage, but please re-open my issue, I would love to see this as default yt-dlp behaviour without doing this hack.

**Comment by mhogomchungu** [comment]
> > Everyone will want it to be in a different format and have different amounts of data.
> 
> I disagree. What I asked in reality is --write-minimal-comments, yet you tell me of data for timestamps or likes or usernames mattering? This functionality doesn't even exist, how can you claim that everyone will somehow care about an optional addition?
> 
> I will use your script for my current usage, but please re-open my issue, I would love to see this as default yt-dlp behaviour without doing this hack.

Everybody has a different idea of what "minimal" is and the best solution is for yt-dlp to return everything and let user decide what to use and what to ignore.

For example, timestamps and usernames are useless to you but they are not to me and my "minimal" entries as they appear in the GUI and saved comments file created by the application looks like below.

![Screenshot_20220121_090144](https://user-images.githubusercontent.com/3496115/150474975-a11ff2b5-8f94-4bc4-8768-7031d65f8f72.png)

![Screenshot_20220121_090817](https://user-images.githubusercontent.com/3496115/150475478-06c29ddd-a7c9-4e1a-8cfe-1f865cdaebd3.png)
