### ISSUE TITLE
Convert Thumbnails option does not exist

### ISSUE THREAD

**Issue by TheYellowArchitect** [yt-dlp/yt-dlp#2203]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2021.12.27**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

On the new features of README, there is this

> Other new options: Many new options have been added such as --print, --wait-for-video, --sleep-requests, --convert-thumbnails, --write-link, --force-download-archive, --force-overwrites, --break-on-reject etc

--convert-thumbnails, results into verbose log below

Am I using --convert-thumbnails wrong? If yes, close this issue.
If not, what does it do?

Slightly off-topic, with which commands can I attach a thumbnail onto a video download?

### Verbose log

```shell
>USAGE: yt-dlp.exe [OPTIONS] URL [URL...]
yt-dlp.exe: error: invalid thumbnail format specified
```

**Comment by pukkandan** [comment]
> Am I using --convert-thumbnails wrong? If yes, close this issue.

How would I know if you don't tell us what command you are using?

From the error message, it appears to me you are not passing the format to convert to.

From readme:
```
    --convert-thumbnails FORMAT      Convert the thumbnails to another format
                                     (currently supported: jpg|png)
```

**Comment by pukkandan** [comment]
> Slightly off-topic, with which commands can I attach a thumbnail onto a video download?

--embed-thumbnail

**Comment by TheYellowArchitect** [comment]
It seems to work. Thank you. I am certain I had written the above yet it didn't work, maybe it was because it downloaded in .webm instead of .mp4 idk

Anyway, for any1 stumbling into this, here is the full command to download a video with its thumbnail:

--embed-thumbnail --format mp4 [YoutubeURL]
