### ISSUE TITLE
Musicdex

### ISSUE THREAD

**Issue by unknownsoldier08** [yt-dlp/yt-dlp#2204]
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2021.12.27**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Example URLs

- Single Video: https://www.musicdex.org/track/306/dual-existence
- Playlist: https://www.musicdex.org/playlist/2/to-aru-kagaku-no-railgun / https://www.musicdex.org/playlist/9/test
- Albums: https://www.musicdex.org/album/56/tenmon-and-eiichiro-yanagi-minori/ef-a-tale-of-memories-original-soundtrack-2-fortissimo
- Artists: https://www.musicdex.org/artist/11/fripside

### Description

[MusicDex](https://www.musicdex.org/) is a website full of anime OPs and EDs albums and tracks.

https://www.musicdex.org/

### Verbose log

```shell
[debug] Command-line config: ['-v', 'https://www.musicdex.org/track/306/dual-existence']
[debug] Portable config file: C:\yt-dlp\yt-dlp.conf
[debug] Portable config: []
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2021.12.27 [6223f67] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] exe versions: ffmpeg 2021-12-30-git-12f21849e5-essentials_build-www.gyan.dev (setts), ffprobe 4.2.1
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [generic] Extracting URL: https://www.musicdex.org/track/306/dual-existence
[generic] dual-existence: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] dual-existence: Downloading webpage
[generic] dual-existence: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://www.musicdex.org/track/306/dual-existence
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1353, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1423, in __extract_info
  File "yt_dlp\extractor\common.py", line 599, in extract
  File "yt_dlp\extractor\generic.py", line 3829, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.musicdex.org/track/306/dual-existence
```

**Comment by Ashish0804** [comment]
@unknownsoldier08 provide example url for playlist with more than 50 songs

**Comment by unknownsoldier08** [comment]
> @unknownsoldier08 provide example url for playlist with more than 50 songs

Here is a playlist with more than 50 songs

https://www.musicdex.org/playlist/9/test
