### ISSUE TITLE
Override download folder for specific channels in archive file

### ISSUE THREAD

**Issue by jeandestouches** [yt-dlp/yt-dlp#2206]
### Checklist

- [X] I'm reporting a feature request
- [X] I've verified that I'm running yt-dlp version **2021.12.27**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

Hello,
Would it be possible to implement a way to use a specific download folder (--download-archive option) when it reads the channels.txt file ?

My file looks like that :
channels.txt
````
# channel1
https://www.youtube.com/channel/blablabla

# channel2
https://www.youtube.com/channel/blablabla

etc....
````
By default, it downloads the videos to the folder set in ~/.config/yt-dlp/config
Maybe by appending the desired folder next to the url in channels.txt ?

````
# channel1
https://www.youtube.com/channel/blablabla DIR=/path/to/folder
````

I looked in the man to see if there was an existing way to deal with that but nothing relevant. If I'm mistaken, please let me know.

Thanks.

**Comment by pukkandan** [comment]
Make an sh/bat file?
```sh
yt-dlp URL1 -P folder1
yt-dlp URL2 -P folder2
```

**Comment by pukkandan** [comment]
Can re-open if you can explain why this is not sufficient
