### ISSUE TITLE
europeantour.com support

### ISSUE THREAD

**Issue by bann0** [yt-dlp/yt-dlp#2208]
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2021.12.27**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Example URLs

- Single video: https://www.europeantour.com/dpworld-tour/news/video/the-best-shots-of-the-2021-seasons/

### Description

Generic extractor fails to fetch the hls urls.

### Verbose log

```shell
[debug] Command-line config: ['--no-config', '-v', 'https://www.europeantour.com/dpworld-tour/news/video/the-best-shots-of-the-2021-seasons/']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, err UTF-8, pref UTF-8
[debug] yt-dlp version 2021.12.27 [6223f67a8]
[debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
[debug] Python version 3.7.3 (CPython 64bit) - Linux-4.19.0-18-amd64-x86_64-with-debian-10.11
[debug] exe versions: ffmpeg 4.1.8-0, ffprobe 4.1.8-0, phantomjs ., rtmpdump 2.4
[debug] Optional libraries: Crypto, secretstorage, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [generic] Extracting URL: https://www.europeantour.com/dpworld-tour/news/video/the-best-shots-of-the-2021-seasons/
[generic] the-best-shots-of-the-2021-seasons: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] the-best-shots-of-the-2021-seasons: Downloading webpage
[generic] the-best-shots-of-the-2021-seasons: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://www.europeantour.com/dpworld-tour/news/video/the-best-shots-of-the-2021-seasons/
Traceback (most recent call last):
  File "/opt/yt-dlp/yt_dlp/YoutubeDL.py", line 1355, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/yt-dlp/yt_dlp/YoutubeDL.py", line 1425, in __extract_info
    ie_result = ie.extract(url)
  File "/opt/yt-dlp/yt_dlp/extractor/common.py", line 599, in extract
    ie_result = self._real_extract(url)
  File "/opt/yt-dlp/yt_dlp/extractor/generic.py", line 3829, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.europeantour.com/dpworld-tour/news/video/the-best-shots-of-the-2021-seasons/
```

**Comment by Ashish0804** [comment]
For devs:
This is a typical brightcove based extractor.
