### ISSUE TITLE
[openrec] support movie URLs

### ISSUE THREAD

**Issue by rivke41levp656** [yt-dlp/yt-dlp#2218]
### Checklist

- [X] I'm reporting a site feature request
- [X] I've verified that I'm running yt-dlp version **2021.12.27**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Example URLs

https://www.openrec.tv/movie/nqz5xl5km8v

### Description

It seems URLs of this form are not supported yet: openrec.tv/movie/random_string

### Verbose log

```shell
[debug] Command-line config: ['--ignore-config', 'https://www.openrec.tv/movie/nqz5xl5km8v', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2021.12.27 [6223f67a8]
[debug] Python version 3.10.1 (CPython 64bit) - Linux-5.15.12-arch1-1-x86_64-with-glibc2.33
[debug] exe versions: ffmpeg 4.4.1 (setts), ffprobe 4.4.1
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [generic] Extracting URL: https://www.openrec.tv/movie/nqz5xl5km8v
[generic] nqz5xl5km8v: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] nqz5xl5km8v: Downloading webpage
[generic] nqz5xl5km8v: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://www.openrec.tv/movie/nqz5xl5km8v
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1353, in wrapper
    return func(self, *args, **kwargs)
  File "/home/user/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1423, in __extract_info
    ie_result = ie.extract(url)
  File "/home/user/.local/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 599, in extract
    ie_result = self._real_extract(url)
  File "/home/user/.local/lib/python3.10/site-packages/yt_dlp/extractor/generic.py", line 3829, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.openrec.tv/movie/nqz5xl5km8v
```

**Comment by pukkandan** [comment]
To devs: Everything's in `window.pageStore`. Code can be generalized with other extractors in `openrec.py`

**Comment by Lesmiscore** [comment]
https://github.com/ytdl-patched/ytdl-patched/blob/ytdlp/yt_dlp/extractor/openrec.py#L127
The weird thing is that they each has slightly different structure which is hard to simplify extraction (except extracting `pageStore`)
