### ISSUE TITLE
Is there a way I can use this project in a backend server to provide a direct download link

### ISSUE THREAD

**Issue by humble-barnacle001** [yt-dlp/yt-dlp#2219]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

Can know of a way that I can use the project in a javascript or python backend to get a direct download link of the media to be sent to the frontend?

**Comment by pukkandan** [comment]
If it is an unfragmented download, you can get the URL with `--print urls`. Although, depending on the service, this URL may be bound to additional headers (`--print http_headers`), the geolocation or sometimes even the IP address.

For fragmented downloads, there is no one "direct URL". All the fragment URLs as well as the manifest_url are still in the info dict, but the front end will have to somehow support downloading it

**Comment by pukkandan** [comment]
No, and there wont be. There are third party telegram bots

**Comment by humble-barnacle001** [comment]
Thanks @pukkandan for the quick response. I want to know one more thing. Suppose I do a pip install of the package. Then I wish to call the project's main inside my own python code. What should I import and which function to call?

**Comment by pukkandan** [comment]
https://github.com/yt-dlp/yt-dlp#embedding-yt-dlp

**Comment by humble-barnacle001** [comment]
Thanks. I am closing this then.
