### ISSUE TITLE
feature request, to remove and replace the "space" from video's title

### ISSUE THREAD

**Issue by icesof** [yt-dlp/yt-dlp#2221]
### Checklist

- [X] I'm reporting a feature request
- [X] I've verified that I'm running yt-dlp version **2021.12.27**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

Dear developer,

My interested Youtube video is using the title of UTF-8 code, like a Chinese character. And, some space inside the title is used by the author of the video. I try with file system option "--restrict-filenames" or "--windows-filenames". Unfortunately, it can't truncate the space from the tile with necessary information keep. 

If you could consider, providing the option to remove some special characters, like space and "*" further? in addition, will it be possible to a customized character as a replacer, like underscore? The benefit of replacement will keep the tile meaningful as it was.

**Comment by pukkandan** [comment]
--replace-in-metadata title " " ""

**Comment by icesof** [comment]
> ```
> --replace-in-metadata title " " "_"
> ```

try with one output, 
the combined characters of ": "  replaced to " -_" ?

**Comment by poslat-pismo** [comment]
> ```
> --replace-in-metadata title " " "_"
> ```

But this way also replaces metatadata title inside file itself, not just filename(...

**Comment by bashonly** [comment]
```
--parse-metadata "title:%(filename_title)s"
--replace-in-metadata filename_title " " "_"
-o "%(filename_title)s [%(id)s].%(ext)s"
```

**Comment by poslat-pismo** [comment]
Thank you!
