### ISSUE TITLE
[livestream extractor] Unable to download JSON metadata (HTTP Error 404)

### ISSUE THREAD

**Issue by lukas1414** [yt-dlp/yt-dlp#2225]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2021.12.27**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Description

Downloading of https://livestream.com/accounts/[user-number] gives me an HTTP Error 404. I'd like to download several videos from the account. Individual videos are working.

### Verbose log

```shell
yt-dlp -U --verbose  https://livestream.com/accounts/8712572
[debug] Command-line config: ['-U', '-o', 'C:/Users/XYZ/Downloads/test_DL/output/%(upload_date>%y%m%d)s_%(title)s.%(ext)s', '--verbose', 'https://livestream.com/accounts/8712572']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2021.12.27 [6223f67] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] exe versions: ffmpeg 2021-08-10-git-c245963a21-full_build-www.gyan.dev (setts), ffprobe 2021-08-10-git-c245963a21-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2021.12.27, Current version: 2021.12.27
yt-dlp is up to date (2021.12.27)
[debug] [livestream] Extracting URL: https://livestream.com/accounts/8712572
[livestream] Downloading JSON metadata
ERROR: [livestream] Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output. (caused by <HTTPError 404: 'Not Found'>); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
  File "yt_dlp\extractor\common.py", line 717, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 3458, in urlopen
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 563, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 755, in http_error_302
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 649, in http_error_default


C:\Users\Puresive Films>
```

**Comment by pukkandan** [comment]
To devs:
Events are supported. The API to get the events of an account is 
https://api.new.livestream.com/accounts/8712572/events

**Comment by theperfectpunk** [comment]
Hi @coletdjnz open a [PR](https://github.com/yt-dlp/yt-dlp/pull/6324) to resolve this
