### ISSUE TITLE
Convert thumbnails to webp

### ISSUE THREAD

**Issue by Oondanomala** [yt-dlp/yt-dlp#2226]
### Checklist

- [X] I'm reporting a feature request
- [X] I've verified that I'm running yt-dlp version **2021.12.27**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [x] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

Webp is lossless and smaller than png, so it would be great to have the ability to convert thumnails to webp. (currently it is only possible to convert to jpg and png)

**Comment by nicolaasjan** [comment]
I doubt that (at least) YouTube's webp's are really lossless.
Here is an enlargement of the webp from [this video](https://www.youtube.com/watch?v=8OTuc_2JGEE).
You can clearly see compression artifacts, so it's not lossless.

(YouTube converts to webp from what the uploader provides?)

Still better than the converted jpg though, even when using `--ppa "ThumbnailsConvertor:-q:v 1"` to get the least compression.
