### ISSUE TITLE
[Site Request] http://saitosan.net/

### ISSUE THREAD

**Issue by Ronam22** [yt-dlp/yt-dlp#224]
## Checklist

- [x] I'm reporting a new site support request
- [x] I've verified that I'm running yt-dlp version **2021.04.03**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that none of provided URLs violate any copyrights
- [x] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

- http://saitosan.net/broadcast.html

## Description

Japanese live website.

**Comment by pukkandan** [comment]
The video is transferred over websocket and would therefore be very hard to implement

**Comment by llacb47** [comment]
The video isn't, only the initial session negotiation is to get the video metadata and URL, so we could probably request the `socket.io` endpoints through HTTPS.
