### ISSUE TITLE
Tiktok Failed to parse JSON

### ISSUE THREAD

**Issue by darktrend** [yt-dlp/yt-dlp#2246]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2021.12.27**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

USA

### Description

Tiktok not working, yt-dlp version I am using is a freshly compiled version from the latest master. I saw the other issue [](https://github.com/yt-dlp/yt-dlp/issues/2243) saying the fix was included in the latest master but I am still getting this issue. 

### Verbose log

```shell
c:\>yt-dlp --verbose https://www.tiktok.com/@therock
[debug] Command-line config: ['--verbose', 'https://www.tiktok.com/@therock']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2021.12.27 [6223f67a8] (win_exe)
[debug] Lazy loading extractors is disabled
[debug] Python version 3.10.0 (CPython 64bit) - Windows-10-10.0.19042-SP0
[debug] exe versions: ffmpeg 4.2.3
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [tiktok:user] Extracting URL: https://www.tiktok.com/@therock
[tiktok:user] therock: Downloading webpage
[download] Downloading playlist: therock
[tiktok:user] therock: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value: line 1 column 1 (char 0). Retrying...
[tiktok:user] therock: Downloading user video list page 1 (attempt 1)
WARNING: [tiktok:user] Expecting value: line 1 column 1 (char 0). Retrying...
[tiktok:user] therock: Downloading user video list page 1 (attempt 2)
WARNING: [tiktok:user] Expecting value: line 1 column 1 (char 0). Retrying...
[tiktok:user] therock: Downloading user video list page 1 (attempt 3)
ERROR: therock: Failed to parse JSON  (caused by JSONDecodeError('Expecting value: line 1 column 1 (char 0)')); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "yt_dlp\extractor\common.py", line 990, in _parse_json
  File "json\__init__.py", line 346, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "yt_dlp\extractor\common.py", line 990, in _parse_json
  File "json\__init__.py", line 346, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1365, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1652, in <lambda>
  File "yt_dlp\utils.py", line 2729, in __getitem__
  File "yt_dlp\extractor\tiktok.py", line 500, in _entries_api
  File "yt_dlp\extractor\tiktok.py", line 75, in _call_api
  File "yt_dlp\extractor\common.py", line 979, in _download_json
  File "yt_dlp\extractor\common.py", line 965, in _download_json_handle
  File "yt_dlp\extractor\common.py", line 994, in _parse_json
yt_dlp.utils.ExtractorError: therock: Failed to parse JSON  (caused by JSONDecodeError('Expecting value: line 1 column 1 (char 0)')); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.

[tiktok:user] playlist therock: Downloading 0 videos
[download] Finished downloading playlist: therock
```

**Comment by darktrend** [comment]
Nevermind the command I was using was invoking an old version of yt-dlp, I tried it again using the path of the newest compiled version of yt-dlp and it works fine

**Comment by Bay40k** [comment]
@darktrend Thanks for this, was having same issue and just force reinstalled from master branch

**Comment by Shados** [comment]
Weird. I'm seeing this error while running a build compiled from master.

**Comment by MinePlayersPE** [comment]
@Shados Show log with `--print-traffic` on

**Comment by Janitsu** [comment]
Having a JSON parsing failure as well, here are my --verbose and --print-traffic logs in a gist:
[LOGS](https://gist.github.com/Janitsu/e93568d5f8e4a8da4a3ff0a94d9a9890)

I've added a few comments (yt-dlp -U and yt-dlp download command used) in the comments as well.

**Comment by MinePlayersPE** [comment]
@Janitsu You are running from release, not master

**Comment by Janitsu** [comment]
@MinePlayersPE thanks! After running a version compiled from the master, I am getting the first warning, but the download proceeds normally otherwise. I am completely happy getting the warning as long as the download completes, but if anyone is interested in the issue still seemingly persisting 🤷‍♀️.

`WARNING: [TikTok] 7025054794444229894: Failed to parse JSON  (caused by JSONDecodeError('Expecting value: line 1 column 1 (char 0)')); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.; Retrying with webpage`
