### ISSUE TITLE
Can't download accessable video from vod_tvp_pl - why ?

### ISSUE THREAD

**Issue by elvisef** [yt-dlp/yt-dlp#2252]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

Why I can not download a video ? 
I've entered user and password credentials. 
The account is a 14day trial account with full access to the "Strefa ABO" category, and the video I am trying to download is in this category (some VOD's are payable individually without any subscription).

There are also free videos, that I can download even without using credentials - i.e. publicly playable.

Verbose log:
> [debug] Command-line config: ['-u', 'PRIVATE', '-p', 'PRIVATE', '-f', 'bv*[height=720]+ba', 'https://vod.tvp.pl/website/ikaria-xb1,49587089', '-Uv']
> [debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
> [debug] yt-dlp version 2021.12.27 [6223f67a8]
> [debug] Python version 3.9.2 (CPython 64bit) - Linux-5.10.0-10-amd64-x86_64-with-glibc2.31
> [debug] exe versions: ffmpeg 4.3.3-0, ffprobe 4.3.3-0, rtmpdump 2.4
> [debug] Optional libraries: Cryptodome, secretstorage, mutagen, sqlite, websockets
> [debug] Proxy map: {}
> Latest version: 2021.12.27, Current version: 2021.12.27
> yt-dlp is up to date (2021.12.27)
> [debug] [tvp:series] Extracting URL: https://vod.tvp.pl/website/ikaria-xb1,49587089
> [download] Downloading playlist: 49587089
> [tvp:series] ikaria-xb1: Downloading page 1
> [tvp:series] ikaria-xb1: Downloading page 2
> [tvp:series] playlist 49587089: Downloading 1 videos
> [download] Downloading video 1 of 1
> [debug] [tvp:embed] Extracting URL: tvp:49613528
> [tvp:embed] 49613528: Downloading webpage
> ERROR: [tvp:embed] 49613528: Obiekt wymaga płatności; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
>   File "/usr/local/lib/python3.9/dist-packages/yt_dlp/extractor/common.py", line 599, in extract
>     ie_result = self._real_extract(url)
>   File "/usr/local/lib/python3.9/dist-packages/yt_dlp/extractor/tvp.py", line 373, in _real_extract
>     raise ExtractorError(error[0]['desc'])
> 
> [download] Finished downloading playlist: 49587089

![2022-01-07_15-17](https://user-images.githubusercontent.com/25976749/148556788-fe51a2c4-115e-46ab-ab47-2271091103a2.png)
![2022-01-07_15-16](https://user-images.githubusercontent.com/25976749/148556792-fa59601c-b10c-45c2-a1ac-2e56ae955d7e.png)

**Comment by Ashish0804** [comment]
Most proly bcoz there is no code to perform the login.
Try with cookies and if it doesn't work either then open an issue and share the account details with the developer who is willing to work on this.

**Comment by elvisef** [comment]
> 

Can You advise me how to use cookies to log in ?
I mean, maybe You have a link with some examples with how to do this ?
I can only see parametres to pass into YTdlp, but no examples of how to use it, step by step.

**Comment by pukkandan** [comment]
Login to the website on chrome and then run `yt-dlp --cookies-from-browser chrome "URL"`

**Comment by elvisef** [comment]
> Login to the website on chrome and then run `yt-dlp --cookies-from-browser chrome "URL"`
Thanks !

Tried it, but..

Command used: 
`yt-dlp --cookies-from-browser chromium "https://vod.tvp.pl/website/ikaria-xb1,49587089" --verbose`

Console response:
![2022-01-20_08-46](https://user-images.githubusercontent.com/25976749/150295459-b9c6a2c5-67b2-4957-bfc8-940510533307.png)

What that could mean, these errors ?
I am using Debian 11.x stable.
![2022-01-20_08-49](https://user-images.githubusercontent.com/25976749/150295663-65dea318-9eac-46a3-88da-56056dd44c08.png)

**Comment by pukkandan** [comment]
Try with new release

**Comment by elvisef** [comment]
Thanks ! 

I've just updated to the newest version using GIT and generally it works, it downloads a file. I will check the file after it's downloaded. But.. a little 404 error is visible here:
![image](https://user-images.githubusercontent.com/25976749/153506532-cac8cc1d-cf41-4973-aee5-2f8039108083.png)
