### ISSUE TITLE
Video in retweeted tweet is no longer retrieved: 'not enough values to unpack'

### ISSUE THREAD

**Issue by RalphCorderoy** [yt-dlp/yt-dlp#2254]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2021.12.27**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Description

I often download a tweet's video where the tweet has been quote-retweeted by giving the URL of the retweet. That didn't work today: `ValueError: not enough values to unpack (expected 2, got 0)`

### Verbose log

```shell
$ ./yt-dlp -Uv -F https://twitter.com/SteveBakerHW/status/1479403699978096641
[debug] Command-line config: ['-Uv', '-F', 'https://twitter.com/SteveBakerHW/status/1479403699978096641']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, err UTF-8, pref UTF-8
[debug] yt-dlp version 2021.12.27 [6223f67a8] (zip)
[debug] Python version 3.6.3 (CPython 64bit) - Linux-4.13.0-17-generic-x86_64-with-Ubuntu-17.10-artful
[debug] exe versions: ffmpeg 3.3.4-2, ffprobe 3.3.4-2, rtmpdump 2.4
[debug] Optional libraries: sqlite
[debug] Proxy map: {}
Latest version: 2021.12.27, Current version: 2021.12.27
yt-dlp is up to date (2021.12.27)
[debug] [twitter] Extracting URL: https://twitter.com/SteveBakerHW/status/1479403699978096641
[twitter] 1479403699978096641: Downloading guest token
[twitter] 1479403699978096641: Downloading JSON metadata
ERROR: not enough values to unpack (expected 2, got 0)
Traceback (most recent call last):
  File "./yt-dlp/yt_dlp/YoutubeDL.py", line 1353, in wrapper
    return func(self, *args, **kwargs)
  File "./yt-dlp/yt_dlp/YoutubeDL.py", line 1423, in __extract_info
    ie_result = ie.extract(url)
  File "./yt-dlp/yt_dlp/extractor/common.py", line 599, in extract
    ie_result = self._real_extract(url)
  File "./yt-dlp/yt_dlp/extractor/twitter.py", line 556, in _real_extract
    formats, subtitles = self._extract_formats_from_vmap_url(vmap_url, content_id or twid)
ValueError: not enough values to unpack (expected 2, got 0)

$ 
```
```

**Comment by pukkandan** [comment]
Are you sure this used to work?

**Comment by RalphCorderoy** [comment]
Hi @pukkandan, that's a fair question and when I normally ask it, it's because the code suggests it could never have worked. :-)

Here's a tweet of a tweet with a video which did work, taken from my shell's history, and **still does**! https://twitter.com/andrew_lilico/status/1460199960847294466

This suggests that although the visual appearance of both tweet hierarchies look similar to me, the viewer, they're different in data structure when accessed by the code in which case it's obviously not a regression, but still confusing for the user.

**Comment by pukkandan** [comment]
Turns out, that used to work just due to dumb luck. Now I've fixed it to work with quoted status properly
