### ISSUE TITLE
Getting Entity too large errors (HTTP 413)

### ISSUE THREAD

**Issue by timothejus** [yt-dlp/yt-dlp#2256]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

Am i doing something wrong, am i missing something?

I am using cookies, because it is a yt-music thing. (and higher quality :) )

pls let me know whats happening, i'd like to get this working.

### Verbose log

```shell
C:\workspaces\Album-downloader>yt-dlp.exe -x --audio-format flac -k --format bestaudio --cookies cookies.txt -o "C:\Users\ME\Music\downloads-temp/TEST\%(title)s.%(ext)s" -i OLAK5uy_mCouTzQYIZXIt-U-OGxTGVLfIrDrYi8Zo --verbose
[debug] Command-line config: ['-x', '--audio-format', 'flac', '-k', '--format', 'bestaudio', '--cookies', 'cookies.txt', '-o', 'C:\\Users\\ME\\Music\\downloads-temp/TEST\\%(title)s.%(ext)s', '-i', 'OLAK5uy_mCouTzQYIZXIt-U-OGxTGVLfIrDrYi8Zo', '--verbose']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2021.12.27 [6223f67] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] exe versions: ffmpeg 4.3.2-2021-02-27-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [youtube:playlist] Extracting URL: OLAK5uy_mCouTzQYIZXIt-U-OGxTGVLfIrDrYi8Zo
[debug] [youtube:tab] Extracting URL: https://www.youtube.com/playlist?list=OLAK5uy_mCouTzQYIZXIt-U-OGxTGVLfIrDrYi8Zo
[youtube:tab] OLAK5uy_mCouTzQYIZXIt-U-OGxTGVLfIrDrYi8Zo: Downloading webpage
WARNING: [youtube:tab] HTTP Error 413: Request Entity Too Large. Retrying ...
[youtube:tab] OLAK5uy_mCouTzQYIZXIt-U-OGxTGVLfIrDrYi8Zo: Downloading webpage (retry #1)
WARNING: [youtube:tab] HTTP Error 413: Request Entity Too Large. Retrying ...
[youtube:tab] OLAK5uy_mCouTzQYIZXIt-U-OGxTGVLfIrDrYi8Zo: Downloading webpage (retry #2)
WARNING: [youtube:tab] HTTP Error 413: Request Entity Too Large. Retrying ...
[youtube:tab] OLAK5uy_mCouTzQYIZXIt-U-OGxTGVLfIrDrYi8Zo: Downloading webpage (retry #3)
WARNING: [youtube:tab] Unable to download webpage: HTTP Error 413: Request Entity Too Large (caused by <HTTPError 413: 'Request Entity Too Large'>); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with
 the --verbose flag and include its complete output.
[debug] [youtube:tab] Extracted SAPISID cookie
ERROR: [youtube:tab] OLAK5uy_mCouTzQYIZXIt-U-OGxTGVLfIrDrYi8Zo: Playlists that require authentication may not extract correctly without a successful webpage download. If you are not downloading private content, or your cookies are only for the first account and channel, pass "--extractor-args youtubetab:skip=au
thcheck" to skip this check
  File "yt_dlp\extractor\common.py", line 599, in extract
  File "yt_dlp\extractor\youtube.py", line 4397, in _real_extract
  File "yt_dlp\extractor\youtube.py", line 4463, in __real_extract
  File "yt_dlp\extractor\youtube.py", line 3847, in _extract_data
```

**Comment by coletdjnz** [comment]
Hmm we haven't seen this before with the webpage, and cannot reproduce :confused: 

Does this happen when not using cookies? If not, try generating your cookies again and see if that helps (or use `--cookies-from-browser`)

**Comment by timothejus** [comment]
Thanks for your response, i was on a bit a wild goose chase but i think i got it working. still testing it though.

I tried your solution but i wouldnt extract the cookies from firefox. (its set quite strict) but even after lowering my security settings it wouldnt budge. 

i then though i would extract my cookies again but instead of extracting them only from music.youtube.com i extracted all the cookies. this seemd to have done something as downloading now works. not tested all my "premium" links yet but i expecct it to be fixed. 

Thanks again for the respnonse! if you have no further questions or don't require more information on the fix you can close this one.

**Comment by pukkandan** [comment]
oh, you should always pass all `.youtube.com` cookies for proper authentication. Also, if you want to get the the higher quality music, pass the music.youtube.com URL to yt-dlp, not just the id. With just the playlist id, yt-dlp doesn't know to search for the higher quality format

**Comment by timothejus** [comment]
Ah great, thanks for the tip! Will try that out.

**Comment by timothejus** [comment]
> oh, you should always pass all `.youtube.com` cookies for proper authentication. Also, if you want to get the the higher quality music, pass the music.youtube.com URL to yt-dlp, not just the id. With just the playlist id, yt-dlp doesn't know to search for the higher quality format

It appears that there is no difference between giving the whole URL with music subdomain. it will change it to a youtube url anyway. the quality is still m4a. This is fine as youtube doesn't offer any lossless compression anyway.

**Comment by dirkf** [comment]
m4a can contain lossless (eg ALAC) audio, but as you say [not at YT](https://support.google.com/youtubemusic/thread/134468321/is-there-any-plans-for-ytm-to-add-lossless-flac-bitrates?hl=en).
