### ISSUE TITLE
malware?: yt-dlp_macos V2021.12.27 contains ASP webshell script threat according to Bkav Pro (Virustotal)

### ISSUE THREAD

**Issue by Davelortenco** [yt-dlp/yt-dlp#2257]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2021.12.27**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

As of today (2022-01--08)   "yt-dlp_macos"  V2021.12.27 macos standalone executable contains ASP webshell security script according to Bkav Pro (Virustotal).

False positive ?

### Verbose log

```shell
no yt-dl output to mention here, file checked by third party.
```

**Comment by pukkandan** [comment]
https://github.com/yt-dlp/yt-dlp/issues/25
