### ISSUE TITLE
documentation error regarding format sorting?

### ISSUE THREAD

**Issue by chrizilla** [yt-dlp/yt-dlp#2259]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

I believe there is an error in the documentation.
https://github.com/yt-dlp/yt-dlp#sorting-formats says:
> « `ie_pref`: The format preference as given by the extractor
[…]
The fields `hasvid` and `ie_pref` are always given highest priority in sorting, irrespective of the user-defined order. This behaviour can be changed by using `--format-sort-force`. Apart from these, the default order used is: `lang,quality,res,fps,hdr:12,codec:vp9.2,size,br,asr,proto,ext,hasaud,source,id`. The extractors may override this default order, but they cannot override the user-provided order. »

So at first, the doc says `ie_pref` (i.e. the extractor's format preference) always has the highest priority, irrespective of the user-defined order. In other words, the **extractor preference overrides the user preference**.

So far so good, but then the doc goes on saying the **extractor cannot override the user preference** (last sentence in quote).

I may be mistaken, but I believe these two statements are contradictory and can't both be true at the same time.

**Comment by pukkandan** [comment]
Obviously, extractor sets all the fields. What the docs say is, "Extractor cannot override the user-provided **order**"

Which means, if user gives `-S res`, and extractor gives `['quality', 'tbr']`, the final order is `ie_pref,hasvid,res,quality,tbr`

**Comment by chrizilla** [comment]
> What the docs say is, "Extractor cannot override the user-provided **order**"

Yes, but earlier the doc sys: _"`ie_pref` [the extractor preferences] are always given highest priority in sorting, irrespective of the user-defined order."_ To me this is contradictory:

> « The fields […] **`ie_pref` are always given highest priority in sorting, irrespective of the user-defined order**. […] The extractors […] **cannot override the user-provided order**. »

**Comment by pukkandan** [comment]
> but earlier the doc says: "ie_pref [the extractor preferences] are always given highest priority in sorting, irrespective of the user-defined order."

Yes, but the extractor is not overriding the user-given sorting order. It sets the `ie_pref` of the format, just like it sets the `qualty`, `height`, `lang` etc of the format. What else would you expect to set this if not the extractor!? 😕

**Comment by chrizilla** [comment]
Ok, apparently I am misunderstanding the README - probably because I don't quite understand how exactly `ie_pref` works (what values it can have). What does "ie" stand for btw? **i**nternal **e**xtractor?

To me, at first the README says the **extractor** _"ie_pref are **always given highest priority** in sorting, irrespective of the user-defined order"_ but then the README says, on the contrary, the **user-prefs have a higher priority than the extractor-prefs** (_"the extractors may override this default order, but they cannot override the user-provided order"_).

That's the apparent contradiction I wanted to point out. (I think your point of view is how yt-dlp works and my point of view is just a textual analysis ... maybe that's why we are talking at cross purposes).

I thought the readme may need some clarification, but maybe I am the only user who doesn't understand this part of the README easily.

What I don't quite get in this context: If the extractor prefs are _"always given highest priority in sorting, irrespective of the user-defined order"_, then what effect does it have to define a user-defined order (without using `--format-sort-force`) ?

**Comment by pukkandan** [comment]
> What does "ie" stand for btw? internal extractor?

ie = "information extractor", generally just called "extractor" in the readme, is the website-specific code that extracts the video formats and metadata of the URL u input

> I don't quite understand how exactly ie_pref works (what values it can have)

`ie_pref` (internally, called `preference`) is just a number (-1 by default), similar to `quality`. But unlike quality, which just says "this format is overall better/worse than the other formats", `preference` is set only when an extractor decides a format must never be considered "best", irrespective of the `-S` used (hence why it is given higher priority than user-provided options). For example, in deezer, some formats of a video can be a preview while other formats are the full track. In that case, the preview tracks are given a lower `preference`. If you give `-S filesize`, you don't want the preview to be downloaded... This is not used by most extractors. We try to use `quality`, `lang` etc where reasonable so that user don't have to generally do `--format-sort-force`

> To me, at first the README says the extractor "ie_pref are always given highest priority in sorting, irrespective of the user-defined order". But then the README says, on the contrary, the user-prefs have a higher priority than the extractor-prefs ("the extractors may override this default order, but they cannot override the user-provided order").

It is not a contradiction though. The extraction mustnot<sup>[1]</sup> override the order of the fields that user gives. But it does decide what values to give each field of each format. It sets the ie_pref of each format the same way it sets the codec, bitrate, quality etc. The only difference is that ie_pref is a high priority field, while the others are not

[1] docs say "cannot", but technically they can. When merging code, I just make sure that they don't


Hopefully I have cleared your confusion

**Comment by chrizilla** [comment]
@pukkandan : many thanks for helping me here. Ok, I guess the doc is right. Blame it on my poor understanding of how yt-dlp works. Sorry, i will close this issue.

Can you please enable me to edit the title of my issue (into _"format sorting documentation"_) ?

**Comment by chrizilla** [comment]
Is there any place where I could find some information about the fields used in [format sorting](https://github.com/yt-dlp/yt-dlp#sorting-formats) to avoid bothering you ?
(I'd like to find out for example what other values than "-1" `ie_pref` can have. And what `source` means and what values it can have.)

**Comment by chrizilla** [comment]
One last observation, if I may. I found something curious:

First, I ran `yt-dlp https://youtu.be/vmkh_4cLyUI -v -F --no-config`

output:
```
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id

```
Then, I passed along the default sort order as defined by [README](https://github.com/yt-dlp/yt-dlp#sorting-formats):

> the default order used is: `lang,quality,res,fps,hdr:12,codec:vp9.2,size,br,asr,proto,ext,hasaud,source,id`

Theoretically, I thought this should not change anything in the final sort order, as I am only passing along the default sort order (i.e. the sort order yt-dlp uses every time, even in the first run printed above).

So I ran `yt-dlp https://youtu.be/vmkh_4cLyUI -v -F --no-config --format-sort lang,quality,res,fps,hdr:12,codec:vp9.2,size,br,asr,proto,ext,hasaud,source,id`

To my surprise this DOES change the final sort order, as seen in the output:
```
[debug] Sort order given by user: lang, quality, res, fps, hdr:12, codec:vp9.2, size, br, asr, proto, ext, hasaud, source, id
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
```

First the sortorder was "**hasvid, ie_pref, quality**, etc." — now it is "**hasvid, ie_pref, lang**, etc.".

How can this be explained ?

**Comment by pukkandan** [comment]
> Is there any place where I could find some information about the fields used in format sorting to avoid bothering you ?
(I'd like to find out for example what other values than "-1" ie_pref can have. And what source means and what values it can have.)

Other than looking at extractor source code, no

> Theoretically, I thought this should not change anything in the final sort order, as I am only passing along the default sort order (i.e. the sort order yt-dlp uses every time, even in the first run printed above).

That is because the YouTube extractor overrides the default sort order (which you overrode when passing it as user order)

> [debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto

**Comment by chrizilla** [comment]
ok, thanks again for your kind help. All clear now!

> @pukkandan [said](https://github.com/yt-dlp/yt-dlp/issues/2259#issuecomment-1008237084):
> Other than looking at extractor source code, no

I looked into the [code](https://github.com/yt-dlp/yt-dlp/blob/master/yt_dlp/extractor/youtube.py), but only found this:

```
# Source is given priority since formats that throttle are given lower source_preference
# When throttling issue is fully fixed, remove this
'source_preference': -10 if throttled else -1,

```
The readme says: _"`source:` Preference of the source as given by the extractor"_

What does that mean?
What is the "source" in the context of youtube videos for example?
I mean all the video formats are from the same source (uploader), no?

**Comment by pukkandan** [comment]
Some formats are from the Android API and some from the Web API. The formats from Web API may be throttled (it's actually fixed now, though the checking code isn't removed). So we check if the format will be throttled and then reduce `source_preference` if it is.

The field is similarly used in niconico and tiktok

**Comment by chrizilla** [comment]
I see. Many thanks.
