### ISSUE TITLE
[TikTok] Friends-only 404

### ISSUE THREAD

**Issue by rsamay** [yt-dlp/yt-dlp#2265]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2021.12.27**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

US

### Description

I'm getting 404 errors when trying to download friends-only videos when logged in (using --cookies-from-browser) as a user that has access to those videos.

This problem is happening in practice, but I've set up a test account to isolate it.  My test account has two videos:

* https://www.tiktok.com/@yvettebedoin/video/7050873817777851653 -- "followers-only" (which means publiic.)  I can download it successfully whether logged in or not.
* https://www.tiktok.com/@yvettebedoin/video/7050874021692329222 -- "friends-only" (which means it's only visible to people that @yvettebedoin follows).  This fails (as expected) when not logged in.  When logged in, though, it seems to download the metadata but it gets the wrong URL for the video itself and 404s.  I pass --write-info-json and it writes the JSON file but not the video.  Attached: [Friends Video [7050874021692329222].info.json.txt](https://github.com/yt-dlp/yt-dlp/files/7833652/Friends.Video.7050874021692329222.info.json.txt)

I can provide access to an account that is friends with this account, or you can follow @yvettebedoin and I'll follow you back to give you access to the video in question.

Thank you!  I've tried to take a look myself, but I don't understand how I'm supposed to generate the correct video URL from the JSON that seems to be available.  I also don't have the MITM shenanigans set up to record SSL traffic from my phone.

### Verbose log

```shell
$ yt-dlp.sh --cookies-from-browser firefox:ik38447o.Alternate https://www.tiktok.com/@yvettebedoin/video/7050874021692329222 -Uv --write-info-json
[debug] Command-line config: ['--cookies-from-browser', 'firefox:ik38447o.Alternate', 'https://www.tiktok.com/@yvettebedoin/video/7050874021692329222', '-Uv', '--write-info-json']
[Cookies] Extracting cookies from firefox
[debug] Extracting cookies from: "/home/xxx/.mozilla/firefox/ik38447o.Alternate/cookies.sqlite"
[Cookies] Extracted 2167 cookies from firefox
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2021.12.27 [6223f67a8] (source)
[debug] Lazy loading extractors is disabled
[debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
[debug] Git HEAD: bfa0e270c
[debug] Python version 3.8.10 (CPython 64bit) - Linux-5.11.0-43-generic-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4, rtmpdump 2.4
[debug] Optional libraries: Cryptodome, secretstorage, sqlite
[debug] Proxy map: {}
Latest version: 2021.12.27, Current version: 2021.12.27
yt-dlp is up to date (2021.12.27)
[debug] [TikTok] Extracting URL: https://www.tiktok.com/@yvettebedoin/video/7050874021692329222
[TikTok] 7050874021692329222: Downloading video details
WARNING: [TikTok] 7050874021692329222: Failed to parse JSON  (caused by JSONDecodeError('Expecting value: line 1 column 1 (char 0)')); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.; Retrying with feed workaround
[TikTok] 7050874021692329222: Downloading video feed
[debug] Sort order given by extractor: quality, codec, size, br
[debug] Formats sorted by: hasvid, ie_pref, quality, vcodec, acodec, filesize, fs_approx, tbr, vbr, abr, lang, res, fps, hdr:12(7), asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 7050874021692329222: Downloading 1 format(s): h264_720p_0
[info] Writing video metadata as JSON to: Friends Video [7050874021692329222].info.json
[debug] Invoking downloader on "https://api.tiktokv.com/aweme/v1/play/?video_id=v09025g40000c7crp03c77ucc4brcipg&line=0&is_play_url=1&source=PackSourceEnum_FEED&sign=ce922305db97088607d885977d20abe2"
ERROR: unable to download video data: HTTP Error 404: Not Found
Traceback (most recent call last):
  File "/home/xxx/bin/yt-dlp-unstable/yt-dlp/yt_dlp/YoutubeDL.py", line 3046, in process_info
    success, real_download = self.dl(temp_filename, info_dict)
  File "/home/xxx/bin/yt-dlp-unstable/yt-dlp/yt_dlp/YoutubeDL.py", line 2759, in dl
    return fd.download(name, new_info, subtitle)
  File "/home/xxx/bin/yt-dlp-unstable/yt-dlp/yt_dlp/downloader/common.py", line 440, in download
    ret = self.real_download(filename, info_dict)
  File "/home/xxx/bin/yt-dlp-unstable/yt-dlp/yt_dlp/downloader/http.py", line 371, in real_download
    establish_connection()
  File "/home/xxx/bin/yt-dlp-unstable/yt-dlp/yt_dlp/downloader/http.py", line 119, in establish_connection
    raise err
  File "/home/xxx/bin/yt-dlp-unstable/yt-dlp/yt_dlp/downloader/http.py", line 113, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "/home/xxx/bin/yt-dlp-unstable/yt-dlp/yt_dlp/YoutubeDL.py", line 3516, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```

**Comment by rsamay** [comment]
I should add that this wasn't broken four days ago (January 3, 2022).  I've also noticed some changes to their HTML/CSS on the web app, so they might have pushed a new version recently.

**Comment by pukkandan** [comment]
This is supposed to have been fixed in https://github.com/yt-dlp/yt-dlp/pull/2171
But I see you already have that commit
> [debug] Git HEAD: bfa0e270c

@MinePlayersPE
