### ISSUE TITLE
[Feature Request] yt-dlp not catching video streams

### ISSUE THREAD

**Issue by dannykym** [yt-dlp/yt-dlp#227]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running yt-dlp version **2021.04.03**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description

Hello, I came across with an mpd file and processed it with latest version of yt-dlp, but it seems like it is only catching audio stream (not video).

Please review the logs & a file below and update when you get a chance :)

Have a wonderful day!

>yt-dlp.exe --cookie cookies.txt --external-downloader aria2c "https://<path to chunklist>/chunklist5000.mpd" --verbose
[debug] Command-line config: ['--cookie', 'cookies.txt', '--external-downloader', 'aria2c', 'https:// <path to chunklist> /chunklist5000.mpd', '--verbose']
[debug] Loading archive file None
[debug] Encodings: locale cp949, fs utf-8, out utf-8, pref cp949
[debug] yt-dlp version 2021.04.03 (exe)
[debug] Python version 3.8.8 (CPython 64bit) - Windows-10-10.0.18362-SP0
[debug] exe versions: none
[debug] Proxy map: {}
[generic] chunklist5000: Requesting header
WARNING: Falling back on generic information extractor.
[generic] chunklist5000: Downloading webpage
[generic] chunklist5000: Extracting information
[debug] Sort order given by user:
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: best/bestvideo+bestaudio
[info] Downloading format(s) 5000_audio
[debug] Invoking downloader on 'https://<path to chunklist>/chunklist5000.mpd'
[dashsegments] Total fragments: 1242
[dashsegments] Fragment downloads will be delegated to aria2c
[download] Destination: chunklist5000 [chunklist5000].m4a
[debug] aria2c command line: aria2c -c  <aria2c is working fine to download files. Redacted this part due to personal information listed in cookies>
[aria2c] Downloaded 60734025 bytes#ff82ec 0B/47KiB(0%)][#da1d17 0B/47KiB(0%)][#1b4213 0B/0B][#680adc 0B/47KiB(0%)](+11
[download] 100% of 57.92MiB in 00:31
WARNING: chunklist5000: writing DASH m4a. Only some players support this container. Install ffmpeg to fix this automatically.

[chunk5000.zip](https://github.com/yt-dlp/yt-dlp/files/6279066/chunk5000.zip)

**Comment by pukkandan** [comment]
```
$ yt-dlp -F file:///<REDACTED>/chunk5000.mpd
[generic] chunk5000: Requesting header
WARNING: Falling back on generic information extractor.
[generic] chunk5000: Downloading webpage
[generic] chunk5000: Extracting information
[info] Available formats for chunk5000:
ID         EXT RESOLUTION |   TBR PROTO | VCODEC        VBR ACODEC     ABR  ASR    NOTE
---------- --- ---------- - ----- ----- - ----------- ----- --------- ---- ------- -----------------------------
250_audio  m4a audio only |   64k dash  |                   mp4a.40.2  64k 48000Hz DASH audio, m4a_dash, 48000Hz
500_audio  m4a audio only |  128k dash  |                   mp4a.40.2 128k 48000Hz DASH audio, m4a_dash, 48000Hz
5000_audio m4a audio only |  192k dash  |                   mp4a.40.2 192k 48000Hz DASH audio, m4a_dash, 48000Hz
150_video  mp4 480x270    |  100k dash  | avc1.4D4015  100k                        DASH video, mp4_dash
250_video  mp4 480x270    |  200k dash  | avc1.4D4015  200k                        DASH video, mp4_dash
500_video  mp4 640x360    |  500k dash  | avc1.4D401E  500k                        DASH video, mp4_dash
1000_video mp4 854x480    | 1000k dash  | avc1.4D401E 1000k                        DASH video, mp4_dash
2000_video mp4 1280x720   | 2000k dash  | avc1.4D401F 2000k                        DASH video, mp4_dash
5000_video mp4 1920x1080  | 5000k dash  | avc1.4D4028 5000k                        DASH video, mp4_dash
```

In the mpd you gave, I can see both audio and video. Unless you give the actual URL where you got this from, I cant help try actually downloading

> [debug] Default format spec: best/bestvideo+bestaudio

This indicates to me that you are trying to download a live mpd (which is not fully supported). But the mpd you gave

**Comment by dannykym** [comment]
The actual original mpd file had <ContentProtection> parts which I redacted from original.
Below is the original file with that parts.
[chunk5000.zip](https://github.com/yt-dlp/yt-dlp/files/6280252/chunk5000.zip)

And I also tried -F file:/// to see if works on original mpd, and it seems like it is disabled on public release version.
`urlopen error file:// scheme is explicitly disabled in yt-dlp for security reasons`

**Comment by pukkandan** [comment]
The video streams are not listed because they have DRM. You can force them to be listed using `--allow-unplayable-formats`, but obviously, the downloaded file will be unplayable

```cmd
$ yt-dlp file:///E:/AKJ/TRASH/Downloads/chunk5000.mpd -F --allow-unplayable-formats
[generic] chunk5000: Requesting header
WARNING: Falling back on generic information extractor.
[generic] chunk5000: Downloading webpage
[generic] chunk5000: Extracting information
[info] Available formats for chunk5000:
ID         EXT RESOLUTION |   TBR PROTO | VCODEC        VBR ACODEC     ABR  ASR    NOTE
---------- --- ---------- - ----- ----- - ----------- ----- --------- ---- ------- -----------------------------
250_audio  m4a audio only |   64k dash  |                   mp4a.40.2  64k 48000Hz DASH audio, m4a_dash, 48000Hz
500_audio  m4a audio only |  128k dash  |                   mp4a.40.2 128k 48000Hz DASH audio, m4a_dash, 48000Hz
5000_audio m4a audio only |  192k dash  |                   mp4a.40.2 192k 48000Hz DASH audio, m4a_dash, 48000Hz
150_video  mp4 480x270    |  100k dash  | avc1.4D4015  100k                        DASH video, mp4_dash
250_video  mp4 480x270    |  200k dash  | avc1.4D4015  200k                        DASH video, mp4_dash
500_video  mp4 640x360    |  500k dash  | avc1.4D401E  500k                        DASH video, mp4_dash
1000_video mp4 854x480    | 1000k dash  | avc1.4D401E 1000k                        DASH video, mp4_dash
2000_video mp4 1280x720   | 2000k dash  | avc1.4D401F 2000k                        DASH video, mp4_dash
5000_video mp4 1920x1080  | 5000k dash  | avc1.4D4028 5000k                        DASH video, mp4_dash

$ yt-dlp file:///E:/AKJ/TRASH/Downloads/chunk5000.mpd -F
[generic] chunk5000: Requesting header
WARNING: Falling back on generic information extractor.
[generic] chunk5000: Downloading webpage
[generic] chunk5000: Extracting information
[info] Available formats for chunk5000:
ID         EXT RESOLUTION |   TBR PROTO | ACODEC     ABR  ASR    NOTE
---------- --- ---------- - ----- ----- - --------- ---- ------- -----------------------------
250_audio  m4a audio only |   64k dash  | mp4a.40.2  64k 48000Hz DASH audio, m4a_dash, 48000Hz
500_audio  m4a audio only |  128k dash  | mp4a.40.2 128k 48000Hz DASH audio, m4a_dash, 48000Hz
5000_audio m4a audio only |  192k dash  | mp4a.40.2 192k 48000Hz DASH audio, m4a_dash, 48000Hz
```

> it seems like it is disabled on public release version.

Yes, it is enabling it causes security issues when yt-dlp is run from a server
