### ISSUE TITLE
Yt-dlp from pip3 fails to start: "Illegal instruction" on Raspbian 10 (Raspberry Pi Zero, Arm v 6)

### ISSUE THREAD

**Issue by pymanx** [yt-dlp/yt-dlp#2274]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2021.12.27**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

I'm trying to install yt-dlp via pip3 on Raspbian 10 (buster). 
My device is Raspberry Pi Zero Rev 1.3. Processor: Arm v 6.

After installation an attempt to launch the software always gives me this error: Illegal instruction

It seems that some binaries in dependent packages are not compiled to work properly with my system or hardware. Please help.

### Verbose log

```shell
pi@raspberrypi:~ $ cat /etc/os-release | grep VERSION=
VERSION="10 (buster)"

pi@raspberrypi:~ $ cat /proc/device-tree/model
Raspberry Pi Zero Rev 1.3

pi@raspberrypi:~ $ python3 -V
Python 3.7.3

pi@raspberrypi:~ $ python3 -m pip install yt-dlp
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting yt-dlp
  Downloading https://files.pythonhosted.org/packages/27/7e/5bf52a334a0638639b57b7699e6a3adaaaa8e7bd6f7ad33e62a9e2be7bb7/yt_dlp-2021.12.27-py2.py3-none-any.whl (2.4MB)
    100% |████████████████████████████████| 2.4MB 22kB/s
Collecting mutagen (from yt-dlp)
  Downloading https://files.pythonhosted.org/packages/16/b3/f7aa8edf2ff4495116f95fd442b2a346aa55d1d46313143c8814886dbcdb/mutagen-1.45.1-py3-none-any.whl (218kB)
    100% |████████████████████████████████| 225kB 190kB/s
Collecting pycryptodomex (from yt-dlp)
  Downloading https://www.piwheels.org/simple/pycryptodomex/pycryptodomex-3.12.0-cp35-abi3-linux_armv6l.whl (1.8MB)
    100% |████████████████████████████████| 1.8MB 29kB/s
Collecting websockets (from yt-dlp)
  Downloading https://www.piwheels.org/simple/websockets/websockets-10.1-cp37-cp37m-linux_armv6l.whl (109kB)
    100% |████████████████████████████████| 112kB 288kB/s
Installing collected packages: mutagen, pycryptodomex, websockets, yt-dlp
  The scripts mid3cp, mid3iconv, mid3v2, moggsplit, mutagen-inspect and mutagen-pony are installed in '/home/pi/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  The script yt-dlp is installed in '/home/pi/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed mutagen-1.45.1 pycryptodomex-3.12.0 websockets-10.1 yt-dlp-2021.12.27

pi@raspberrypi:~ $ yt-dlp -Uv
Illegal instruction

pi@raspberrypi:~ $ python3
Python 3.7.3 (default, Dec 20 2019, 18:57:59)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import yt_dlp
Illegal instruction
```

**Comment by pukkandan** [comment]
yt-dlp itself is pure python and so shouldn't have any issues. Try uninstalling the dependencies one by one to see which one is causing this.

> Installing collected packages: mutagen, pycryptodomex, websockets, yt-dlp

My suspicion is that it is `pycryptodomex` which has compiled C code

**Comment by nurupo** [comment]
You could try installing the deps from the package repository, e.g.

```bash
apt-get install python3-pycryptodome python3-mutagen python3-websocket
```

and see if that works. You would obviously need to uninstall the ones you have installed via pip.

**Comment by pukkandan** [comment]
This seems to be the issue. https://github.com/Legrandin/pycryptodome/issues/585

Try uninstalling pycryptodomex

    pip3 uninstall pycryptodomex

**Comment by pukkandan** [comment]
Closed due to inactivity
