### ISSUE TITLE
conflict between -P and -o parameters ?

### ISSUE THREAD

**Issue by chrizilla** [yt-dlp/yt-dlp#2278]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2021.12.27**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

Until now, I have been working in Windows with yt-dlp.exe in my download directory and it worked without any problems
Yt-dlp downloads my videos into the same directory as yt-dlp.exe.
My -o output templates have also been working fine.

Now however, I have to specify a download location different from the yt-dlp.exe location, but my `--path` and `-o` parameters don't seem to like each other:

**command:** `yt-dlp gr51aVj-mLg -v --ignore-config --paths "c:\Users\User\Downloads\yt" -o "%(playlist|)s\file.%(ext)s"`

**results:**
    ❌ "**WARNING: --paths is ignored since an absolute path is given in output template**" although no absolute path is used
    ❌ `C:\` is used instead of the requested download dir

**log:**
```
yt-dlp gr51aVj-mLg -v --ignore-config --paths "c:\Users\User\Downloads\yt" -o "%(playlist|)s\file.%(ext)s"
[debug] Command-line config: ['gr51aVj-mLg', '-v', '--ignore-config', '--paths', 'c:\\Users\\User\\Downloads\\yt', '-o', '%(playlist|)s\\file.%(ext)s']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2021.12.27 [6223f67] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] exe versions: ffmpeg N-105208-gb24f0c82b3-20220108 (setts), ffprobe N-105208-gb24f0c82b3-20220108
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [youtube] Extracting URL: gr51aVj-mLg
[youtube] gr51aVj-mLg: Downloading webpage
[youtube] gr51aVj-mLg: Downloading android player API JSON
[youtube] gr51aVj-mLg: Downloading MPD manifest
[youtube] gr51aVj-mLg: Downloading MPD manifest
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] gr51aVj-mLg: Downloading 1 format(s): 244+140
WARNING: --paths is ignored since an absolute path is given in output template
WARNING: Requested formats are incompatible for merge and will be merged into mkv
[download] c:\file.mkv has already been downloaded
```

If I remove the "|" character in my output template, the warning disappears:

**command:** `yt-dlp gr51aVj-mLg -v --ignore-config --paths "c:\Users\User\Downloads\yt" -o "%(playlist)s\file.%(ext)s"`

**results:**
    ✅ the specified download dir is respected

**log:**
```
yt-dlp gr51aVj-mLg -v --ignore-config --paths "c:\Users\User\Downloads\yt" -o "%(playlist)s\file.%(ext)s"
[debug] Command-line config: ['gr51aVj-mLg', '-v', '--ignore-config', '--paths', 'c:\\Users\\User\\Downloads\\yt', '-o', '%(playlist)s\\file.%(ext)s']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2021.12.27 [6223f67] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] exe versions: ffmpeg N-105208-gb24f0c82b3-20220108 (setts), ffprobe N-105208-gb24f0c82b3-20220108
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [youtube] Extracting URL: gr51aVj-mLg
[youtube] gr51aVj-mLg: Downloading webpage
[youtube] gr51aVj-mLg: Downloading android player API JSON
[youtube] gr51aVj-mLg: Downloading MPD manifest
[youtube] gr51aVj-mLg: Downloading MPD manifest
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] gr51aVj-mLg: Downloading 1 format(s): 244+140
WARNING: Requested formats are incompatible for merge and will be merged into mkv
[download] c:\Users\User\Downloads\yt\NA\file.mkv has already been downloaded
```

There seems to be a problem, because the "|" is allowed and used in the [README examples](https://github.com/yt-dlp/yt-dlp#output-template-examples) and aside from that, the (more complex) output formats I am using have always been working well when I have not used the `--path` parameter.

**Comment by pukkandan** [comment]
There is a tricky situation going on here. When `playlist` is not present, your output template `-o "%(playlist|)s\file.%(ext)s"` becomes `\file.mkv`. Because of the `\`, it gets interpreted as an absolute path. I am not sure how to "fix" this, or if it even can be fixed unambiguously

You can workaround by passing `.\%(playlist|)s\file.%(ext)s` or  `%(playlist|.)s\file.%(ext)s` to clarify to yt-dlp that it is in fact a relative path

**Comment by chrizilla** [comment]
Thanks for your quick reply. 

> Because of the `\`, it gets interpreted as an absolute path.

Ok. Sorry, I did not know that. This is the first I see it interpreted it that way. I am only used to absolute paths including drive letters.

> You can workaround by passing `.\%(playlist|)s\file.%(ext)s` or `%(playlist|.)s\file.%(ext)s`

stupid me, I didn't think about that. That seems to solve the issue, judging from a quick test.

**Comment by chrizilla** [comment]
Thanks for your quick reply. 

> Because of the `\`, it gets interpreted as an absolute path.

Ok. Sorry, I did not know that. This is the first I see it interpreted it that way. I am only used to absolute paths including drive letters.

> You can workaround by passing `.\%(playlist|)s\file.%(ext)s` or `%(playlist|.)s\file.%(ext)s`

stupid me, I didn't think about that. That seems to solve the issue, judging from a quick test.

**Comment by pukkandan** [comment]
> This is the first I see it interpreted it that way. I am only used to absolute paths including drive letters.

On UNIX, `/` points to the root
and on windows, it points to the root of the current drive

> That seems to solve the issue, judging from a quick test.

Since that fixes your issue, I am closing this. I honestly don't know whether to treat it as a bug or not. But either way, it's not clear how to resolve this unambiguously. If more people have this issue, we can  see if anything can be done. Right now, I dont think it is worth trying to fix it

**Comment by chrizilla** [comment]
ok, thanks for the feedback
