### ISSUE TITLE
Use `-bitexact` flag with ffmpeg to provide deterministic output by default

### ISSUE THREAD

**Issue by cameel** [yt-dlp/yt-dlp#2284]
### Checklist

- [X] I'm reporting a feature request
- [X] I've verified that I'm running yt-dlp version **2021.12.27**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

#### Summary
I think that yt-dlp should by default pass `-bitexact` flag to ffmpeg to always provide deterministic output. Or at least it should have an easily discoverable flag to enable this behavior.

#### Context
The file created by yt-dlp is slightly different each time it is downloaded when certain options/formats are used. Anything that requires postprocessing with ffmpeg results in non-deterministic output.

I ran into this while trying to compare the files produced by yt-dlp and youtube-dl. This makes it hard to ensure that the file is not damaged and that they actually download the same thing.

In the end I found a solution: I can force `ffmpeg` to produce deterministic output with `-bitexact` option so adding `--postprocessor-args "ffmpeg:-bitexact"` to the yt-dlp command fixes the problem. I wish it was easier to discover though. Initially I did not realize what was causing such differences in the output because I assumed that yt-dlp tries to always give you the same exact data (I'm sure many other users do too). I suspected a bug in the `--add-metadata` option but conditions to reproduce it were not consistent. I spent a lot of time trying to debug this and create a sensible bug report only to discard it when I found out what was happening.

I think that there should be an explicit option to enable deterministic behavior. Preferably enabled by default. I suspect that there are valid reasons why ffmpeg does not default to this (probably performance) but I think in case of yt-dlp/youtube-dl it would be a good default. One of its most important uses cases is archiving of publicly available videos after all, and for this reproducible results matter more than tiny performance gains. There could always be an option to disable this in case this does have measurable performance impact.

#### Reproducing the non-deterministic behavior
You can observe this behavior even by just downloading the test video:

```bash
yt-dlp "https://www.youtube.com/watch?v=BaW_jenozKc" --output "test1.webm"
yt-dlp "https://www.youtube.com/watch?v=BaW_jenozKc" --output "test2.webm"
diff <(hexdump test1.webm) <(hexdump test2.webm) --unified=0 --color
```
In this case it grabs `--format 248+251`, which requires muxing the streams into a single file so no extra options are needed to trigger it. In other cases adding `--add-metadata` is usually enough.

Here's the diff I see:
```diff
@@ -15,2 +15,2 @@
-0000110 0000 0000 0000 d74e 0181 c573 b588 135b
-0000120 4b7d 4cb2 9cfc 0081 b522 839c 6e65 8667
+0000110 0000 0000 0000 d74e 0181 c573 7888 a7d5
+0000120 db68 65a8 9cdb 0081 b522 839c 6e65 8667
@@ -21 +21 @@
-0000170 7302 88c5 8395 45fe 8501 034b 819c 2200
+0000170 7302 88c5 7572 ee02 3afc 2a5f 819c 2200
@@ -30,2 +30,2 @@
-0000200 0001 0000 0000 3300 c063 638b 88c5 5bb5
-0000210 7d13 b24b fc4c c867 45a2 88a3 5544 4152
+0000200 0001 0000 0000 3300 c063 638b 88c5 d578
+0000210 68a7 a8db db65 c867 45a2 88a3 5544 4152
@@ -34,2 +34,2 @@
-0000240 0000 0000 6333 8bc0 c563 9588 fe83 0145
-0000250 4b85 6703 a2c8 a345 4488 5255 5441 4f49
+0000240 0000 0000 6333 8bc0 c563 7288 0275 fcee
+0000250 5f3a 672a a2c8 a345 4488 5255 5441 4f49
```
The diff is of course slightly different every time.

The differences in this case are only at the very beginning, probably in some padding in headers or metadata. This is not always the case. E.g. with `--extract-audio` there are more of them and they are spread all over the file. In any case, `ffprobe` shows that there are no actual differences in metadata or any other properties of the video, which you can check by running:
``` bash
diff --unified=0 --color \
    <(ffprobe test1.webm -show_entries format:streams:packets:frames:programs:chapters 2>&1) \
    <(ffprobe test2.webm -show_entries format:streams:packets:frames:programs:chapters 2>&1)
```

With `-bitexact` both files are actually byte-for-byte identical:
```bash
yt-dlp "https://www.youtube.com/watch?v=BaW_jenozKc" --output "test1.webm" --postprocessor-args "ffmpeg:-bitexact"
yt-dlp "https://www.youtube.com/watch?v=BaW_jenozKc" --output "test2.webm" --postprocessor-args "ffmpeg:-bitexact"
diff <(hexdump test1.webm) <(hexdump test2.webm) --unified=0 --color
```
The diff is empty.

**Comment by pukkandan** [comment]
The only thing -bitexact does is that it does not write ffmpeg's version specific tags to the file

From https://ffmpeg.org/ffmpeg-all.html

```
‘bitexact’
Only write platform-, build- and time-independent data. (except (I)DCT). This ensures that file and data checksums are reproducible and match between platforms. Its primary use is for regression testing.
```

I don't see any reason why yt-dlp should use it by default. You can always add the `--ppa` if you want it

**Comment by pukkandan** [comment]
> One of its most important uses cases is archiving of publicly available videos after all, and for this reproducible results matter more than tiny performance gains

Can you explain how exact reproducibility is important?

> I ran into this while trying to compare the files produced by yt-dlp and youtube-dl. This makes it hard to ensure that the file is not damaged and that they actually download the same thing.

This is not a good test of whether the file is undamaged. Any systematic errors in either ffmpeg or yt-dlp will cause the checksum to remain same across runs. The only use I can see from your post is comparing b/w youtube-dl and yt-dlp. But imo that is too niche a use-case to justify changing the defaults, or adding new options - especially considering it can already be done with `--ppa`
