### ISSUE TITLE
TikTok "Failed to parse JSON"

### ISSUE THREAD

**Issue by beringov** [yt-dlp/yt-dlp#2286]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2021.12.27**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Russia

### Description

Seemed Tiktok parsing has been broken from yesterday. Same happens for previous version 2021.12.25

### Verbose log

```shell
Z:\Programs\cli_programs>yt-dlp --verbose https://www.tiktok.com/@nkozyavina/video/7035717794452753666
[debug] Command-line config: ['--verbose', 'https://www.tiktok.com/@nkozyavina/video/7035717794452753666']
[debug] Encodings: locale cp1251, fs utf-8, out cp1251 (No ANSI), err utf-8, pref cp1251
[debug] yt-dlp version 2021.12.27 [6223f67] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19042-SP0
[debug] exe versions: ffmpeg 2021-12-09-git-b9f4c1231f-full_build-www.gyan.dev (setts), ffprobe 2021-12-09-git-b9f4c1231f-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [TikTok] Extracting URL: https://www.tiktok.com/@nkozyavina/video/7035717794452753666
WARNING: [TikTok] 7035717794452753666: Failed to parse JSON  (caused by JSONDecodeError('Expecting value: line 1 column 1 (char 0)')); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you
are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.; Retrying with webpage
ERROR: [TikTok] 7035717794452753666: Unable to extract json_string; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
  File "yt_dlp\extractor\common.py", line 599, in extract
  File "yt_dlp\extractor\tiktok.py", line 368, in _real_extract
  File "yt_dlp\extractor\common.py", line 1173, in _search_regex
```

**Comment by pukkandan** [comment]
Duplicate of #2282, #2282, #2250, #2250, #2246, #2246, #2243, #2183, #2183, #2165, #2159, #2159, #2150, #2150, #2135, #2133

Is it so hard to search before opening an issue!!
