### ISSUE TITLE
[TwitCastingLive] An extractor error has occurred. (caused by KeyError('llfmp4'))

### ISSUE THREAD

**Issue by nurupo** [yt-dlp/yt-dlp#2289]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2021.12.27**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Description

Since about a week ago I'm unable to watch live streams of one particular streamer. It worked before but no longer works. Other several streamers that I have tried at random off the front page seem to work just fine.

Streamlink is having the same issue https://github.com/streamlink/streamlink/issues/4281

Looks the JSON response for this streamer's live stream is missing `llfmp4` (what yt-dlp uses) and `fmp4` (what streamlink uses) keys.

### Verbose log

```shell
$ yt-dlp -Uv -o test.ts https://twitcasting.tv/054109
[debug] Command-line config: ['-Uv', '-o', 'test.ts', 'https://twitcasting.tv/054109']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2021.12.27 [6223f67a8]
[debug] Python version 3.9.2 (CPython 64bit) - Linux-5.10.0-8-amd64-x86_64-with-glibc2.31
[debug] exe versions: ffmpeg 4.3.2-0, ffprobe 4.3.2-0, rtmpdump 2.4
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2021.12.27, Current version: 2021.12.27
yt-dlp is up to date (2021.12.27)
[debug] [TwitCastingLive] Extracting URL: https://twitcasting.tv/054109
[TwitCastingLive] Downloading live video of user 054109. Pass "https://twitcasting.tv/054109/show" to download the history
[TwitCastingLive] 054109: Downloading webpage
[debug] [TwitCasting] Extracting URL: https://twitcasting.tv/054109/movie/716611113
[TwitCasting] 716611113: Downloading webpage
[TwitCasting] 716611113: Downloading live info
ERROR: 716611113: An extractor error has occurred. (caused by KeyError('llfmp4')); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File ".pyenv/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 599, in extract
    ie_result = self._real_extract(url)
  File ".pyenv/lib/python3.9/site-packages/yt_dlp/extractor/twitcasting.py", line 104, in _real_extract
    for mode, ws_url in stream_server_data['llfmp4']['streams'].items():
KeyError: 'llfmp4'
Traceback (most recent call last):
  File ".pyenv/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 599, in extract
    ie_result = self._real_extract(url)
  File ".pyenv/lib/python3.9/site-packages/yt_dlp/extractor/twitcasting.py", line 104, in _real_extract
    for mode, ws_url in stream_server_data['llfmp4']['streams'].items():
KeyError: 'llfmp4'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".pyenv/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1353, in wrapper
    return func(self, *args, **kwargs)
  File ".pyenv/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1423, in __extract_info
    ie_result = ie.extract(url)
  File ".pyenv/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 629, in extract
    raise ExtractorError('An extractor error has occurred.', cause=e, video_id=self.get_temp_id(url))
yt_dlp.utils.ExtractorError: 716611113: An extractor error has occurred. (caused by KeyError('llfmp4')); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
```

**Comment by Lesmiscore** [comment]
![image](https://user-images.githubusercontent.com/10355528/148770657-e909a6d1-22b9-42bf-b51a-2a5f0d52801b.png)

lol :smile: 

it seems they patched the endpoint we have used for websockets

**Comment by nurupo** [comment]
Looks like this stream requires you to be logged in.

I didn't occur to me to check in Incognito before.

https://twitcasting.tv/streamserver.php?target=054109&mode=client contains `llfmp4` when I'm logged in

```
{"movie":{"id":716611113,"live":true},"hls":{"host":"twitcasting.tv","proto":"https","source":true},"fmp4":{"host":"202-218-143-75.twitcasting.tv","proto":"wss","source":true,"mobilesource":false},"llfmp4":{"streams":{"main":"wss://202-218-143-75.twitcasting.tv/tc.edge/v1/streams/716611113.336.96/fmp4","base":"wss://202-218-143-75.twitcasting.tv/tc.edge/v1/streams/716611113.240.64/fmp4"}}}
```

but doesn't when I'm not:

```
{"movie":{"id":716611113,"live":true},"hls":{"host":"twitcasting.tv","proto":"https","source":true}}
```

and there is this obvious message in Incognito:

![must-be-logged-in](https://user-images.githubusercontent.com/1855294/148772681-a0c6f3e6-c826-4cea-92ec-9b87cd4bafe8.png)

**Comment by nurupo** [comment]
>it seems they patched the endpoint we have used for websockets

Your URL request looks wrong to me. You have used the wrong target. The requests I'm seeing are using streamer username, but you have set it to a movie id instead. `716610548` is a movie id: https://twitcasting.tv/usss_info/movie/716610548, and it's not even published "This video is not published". (It doesn't work even for published movie ids, I have just tried).

**Comment by Lesmiscore** [comment]
@nurupo yeah my fault. the response will not change without login even with correct parameter values though.

**Comment by nurupo** [comment]
Yep. I see you opened a PR fixing the crash. Should I open a separate issue requesting the login functionality to be added for TwitCastingLive or renaming this issue is fine?

**Comment by Lesmiscore** [comment]
I guess you can use cookies. (use `--cookies-from-browser BROWSER` or `--cookies FILE`)
If it won't work, you have to open new issues.

**Comment by Lesmiscore** [comment]
@nurupo Can you please give me any example which explicitly requires logging in, if you have one? <sub><sup>why I forgot taking page dumps</sup></sub>

**Comment by nurupo** [comment]
Don't have one. Tune in for the stream tomorrow. They are usually from around 22:30 to 02:30 JST.

**Comment by Lesmiscore** [comment]
Okay, then let's wait for that. Thanks

**Comment by nurupo** [comment]
Works with cookies.
