### ISSUE TITLE
Separate working directory for downloading+muxing

### ISSUE THREAD

**Issue by fren-archivist** [yt-dlp/yt-dlp#2296]
### Checklist

- [X] I'm reporting a feature request
- [X] I've verified that I'm running yt-dlp version **2021.12.27**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

In the course of muxing a video after it is downloaded, the data may be read and rewritten to several times. This can happen for several reasons, such as combining audio and video or embedding metadata/thumbnail. If one is downloading a playlist, the next download will not begin until the entire muxing process is finished. This means that, even though a regular hard drive is the most natural place to _store_ the final file, it is a bad option for where to download it. The low speed will bottleneck your playlist download. In extreme cases where the network speed is high and the drive speed is low, this muxing may take longer than the actual download!

A more natural place to download to in a tiered storage system would be an SSD. Even better would be a ramdisk to get maximum speed and not worry about SSD endurance, assuming you have enough ram spare. But these methods basically require a separate background process that will periodically push the files over to the HDD when they're done. It's doable but moderately inconvenient. Alternatively you can have yt-dlp just download the audio and video files and write a separate muxing script yourself, but again, this is inconvenient. It also may be possible to use a faster drive to cache the write to the HDD, achieving the same purpose, but setting this up is not trivial and I don't know if it's even possible for a ramdisk.

I'm proposing that a separate "working directory" option be added for downloads that will require one or more calls to ffmpeg after they finish. The audio+video download and all subsequent writes should happen in this directory, and only the final write would go to the target location.

**Comment by pukkandan** [comment]
`--paths temp:`

See the docs of `--paths`
