### ISSUE TITLE
Tiktok Failed to parse JSON

### ISSUE THREAD

**Issue by darktrend** [yt-dlp/yt-dlp#2298]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2021.12.27**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

USA

### Description

yt-dlp stopped working. Using a freshly compiled version of YT-dlp. 

### Verbose log

```shell
yt-dlp -v https://www.tiktok.com/@therock
[debug] Command-line config: ['-v', 'https://www.tiktok.com/@therock']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2021.12.27 [6223f67a8] (win_exe)
[debug] Lazy loading extractors is disabled
[debug] Python version 3.10.0 (CPython 64bit) - Windows-10-10.0.19042-SP0
[debug] exe versions: ffmpeg 4.2.3
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [tiktok:user] Extracting URL: https://www.tiktok.com/@therock
[tiktok:user] therock: Downloading webpage
[tiktok:user] therock: Downloading user video list page 1
WARNING: [tiktok:user] Expecting value: line 1 column 1 (char 0). Retrying...
[tiktok:user] therock: Downloading user video list page 1 (attempt 1)
WARNING: [tiktok:user] Expecting value: line 1 column 1 (char 0). Retrying...
[tiktok:user] therock: Downloading user video list page 1 (attempt 2)
WARNING: [tiktok:user] Expecting value: line 1 column 1 (char 0). Retrying...
[tiktok:user] therock: Downloading user video list page 1 (attempt 3)
ERROR: [tiktok:user] therock: therock: Failed to parse JSON  (caused by JSONDecodeError('Expecting value: line 1 column 1 (char 0)')); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output. (caused by JSONDecodeError('Expecting value: line 1 column 1 (char 0)')); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.  File "yt_dlp\extractor\common.py", line 610, in extract
  File "yt_dlp\extractor\tiktok.py", line 537, in _real_extract
  File "yt_dlp\utils.py", line 6667, in traverse_obj
  File "yt_dlp\utils.py", line 6653, in _traverse_obj
  File "yt_dlp\utils.py", line 4266, in __getitem__
  File "yt_dlp\extractor\tiktok.py", line 506, in _video_entries_api
  File "yt_dlp\extractor\tiktok.py", line 79, in _call_api
  File "yt_dlp\extractor\common.py", line 990, in _download_json
  File "yt_dlp\extractor\common.py", line 976, in _download_json_handle
  File "yt_dlp\extractor\common.py", line 1005, in _parse_json
```

**Comment by Lesmiscore** [comment]
https://github.com/yt-dlp/yt-dlp/issues?q=is%3Aissue+tiktok

**Comment by darktrend** [comment]
it's working for me again, sorry for contributing to the tiktok is down spam, I'll be more patient with my reports in the future.

**Comment by AplhaSlayer1964** [comment]
@darktrend is it still working for you? I looked through all the other posts and saw no solutions.
