### ISSUE TITLE
[YouTube] Reject tab download on expired cookies or redirected tab

### ISSUE THREAD

**Issue by krichbanana** [yt-dlp/yt-dlp#2306]
### Checklist

- [X] I'm reporting a site feature request
- [X] I've verified that I'm running yt-dlp version **2021.12.27**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Example URLs

https://www.youtube.com/channel/UCO_aKKYxn4tvrqPjcTzZ6EQ/membership (not normally accessible without cookies)
https://www.youtube.com/channel/UCO_aKKYxn4tvrqPjcTzZ6EQ/community (accessible without cookies but lacks members posts)

### Description

I wish to be able to obtain a list of all members-only videos for a channel. For this I have found two ways:

- Scrape the membership tab directly. Recently, YouTube has listed members-only videos and posts directly on the membership tab. Pretty convenient.
- Scrape the community page twice, once without cookies, and removing the common videos between both scrapes. This is much slower.

In both cases, I use `--flat-playlist` to quickly get the list of videos, without having to check each video individually.

My issue stemming this request is that when the cookies expire/no longer work after a few weeks, rather than throwing an error (which I can automatically handle), the page redirects to the Home tab. This means unrelated, public videos appear in the scrape results. For the second bullet, a lack of member videos may not be completely indicative of expired cookies.

Existing possibilities I have considered:
- Scraping each video for availability matching "subscriber_only". This works, but is very slow, increases chances of ratelimiting, and can be unreliable as the availability of the video could change.
- Trying to match the playlist title. Knowing that the playlist_title field ends in " - Membership", I tried `--match-filter 'playlist_title~=Membership'`, but the filter doesn't seem to have any effect on flat playlists.
- Using custom, curated membership playlists. These playlists will not be updated in real time, and they won't include upcoming streams.
- Attempting to download a live chat replay on a known members-only video. This can detect bad cookies but as a check it is excessively cumbersome to automate. Not to mention, this can't be done within a single call to yt-dlp.
- I looked at the options for the youtubetab extractor and didn't see anything that stood out.

Solutions:
I believe a combination of checking for the correct session cookies and checking whether the "Membership" tab is accessible may be sufficient to determine if membership content is available. If the tab isn't available, then either cookies are expired, you are not logged in, or your membership is no longer valid. A misspelled cookie file should also not be ignored. Any of these conditions should cause yt-dlp to abort with error. Unfortunately my unimaginative mind cannot think of a good way to extend the commandline options; perhaps '--check-access' may make sense, with behavior based on the current URL or option value? I'm aware that there is also premium-only content; the option could most likely be reused for that as well.

Additionally (or alternatively), I believe it to be broadly useful for an option to abort yt-dlp when a tab is found to have redirected, including the various video live views (since some views like "Upcoming live streams" are likely to be unavailable, and would probably redirect to Uploads). Something like checking the selected tab or video view against known URL patterns would probably be sufficient. This would prevent the accidental download or scrape of videos that aren't on that tab. This would also allow yt-dlp to exit quickly before loading any additional continuation pages, saving time and reducing network requests. I suppose an option like '--no-tab-redirect' or '--no-page-redirect' (with respective negative variants) would work, but again, naming is not my strong suit. It might also make sense to abort by default and not have an option, but compatibility issues are very likely.

### Verbose log

```shell
# With valid cookies (extracts from Membership tab)
[debug] Command-line config: ['-Uv', '--cookies', 'cookies/UCO_aKKYxn4tvrqPjcTzZ6EQ.cookies', '--skip-download', '-s', '--flat-playlist', 'https://www.youtube.com/channel/UCO_aKKYxn4tvrqPjcTzZ6EQ/membership']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2021.12.27 [6223f67a8]
[debug] Python version 3.10.1 (CPython 64bit) - Linux-5.15.10-arch1-1-x86_64-with-glibc2.33
[debug] exe versions: ffmpeg 4.4.1 (setts), ffprobe 4.4.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2021.12.27, Current version: 2021.12.27
yt-dlp is up to date (2021.12.27)
[debug] [youtube:tab] Extracting URL: https://www.youtube.com/channel/UCO_aKKYxn4tvrqPjcTzZ6EQ/membership
[youtube:tab] UCO_aKKYxn4tvrqPjcTzZ6EQ: Downloading webpage
[debug] [youtube:tab] Final URL: https://www.youtube.com/channel/UCO_aKKYxn4tvrqPjcTzZ6EQ/membership
[download] Downloading playlist: Ceres Fauna Ch. hololive-EN - Membership
[debug] [youtube:tab] Extracted SAPISID cookie
[youtube:tab] UCO_aKKYxn4tvrqPjcTzZ6EQ page 1: Downloading API JSON
[youtube:tab] playlist Ceres Fauna Ch. hololive-EN - Membership: Downloading 14 videos
[download] Downloading video 1 of 14
[download] Downloading video 2 of 14
[download] Downloading video 3 of 14
[download] Downloading video 4 of 14
[download] Downloading video 5 of 14
[download] Downloading video 6 of 14
[download] Downloading video 7 of 14
[download] Downloading video 8 of 14
[download] Downloading video 9 of 14
[download] Downloading video 10 of 14
[download] Downloading video 11 of 14
[download] Downloading video 12 of 14
[download] Downloading video 13 of 14
[download] Downloading video 14 of 14
[download] Finished downloading playlist: Ceres Fauna Ch. hololive-EN - Membership

# Without valid cookies (redirects to Home)
[debug] Command-line config: ['-Uv', '--cookies', '/tmp/misspeeled.txt', '--skip-download', '-s', '--flat-playlist', 'https://www.youtube.com/channel/UCO_aKKYxn4tvrqPjcTzZ6EQ/membership']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2021.12.27 [6223f67a8]
[debug] Python version 3.10.1 (CPython 64bit) - Linux-5.15.10-arch1-1-x86_64-with-glibc2.33
[debug] exe versions: ffmpeg 4.4.1 (setts), ffprobe 4.4.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2021.12.27, Current version: 2021.12.27
yt-dlp is up to date (2021.12.27)
[debug] [youtube:tab] Extracting URL: https://www.youtube.com/channel/UCO_aKKYxn4tvrqPjcTzZ6EQ/membership
[youtube:tab] UCO_aKKYxn4tvrqPjcTzZ6EQ: Downloading webpage
[debug] [youtube:tab] Final URL: https://www.youtube.com/channel/UCO_aKKYxn4tvrqPjcTzZ6EQ/membership
[download] Downloading playlist: Ceres Fauna Ch. hololive-EN - Home
[youtube:tab] playlist Ceres Fauna Ch. hololive-EN - Home: Downloading 5 videos
[download] Downloading video 1 of 5
[download] Downloading video 2 of 5
[download] Downloading video 3 of 5
[download] Downloading video 4 of 5
[download] Downloading video 5 of 5
[download] Finished downloading playlist: Ceres Fauna Ch. hololive-EN - Home

# Alternate method, when with cookies (public and membership posts)
[debug] Command-line config: ['-Uv', '--cookies', 'cookies/UCO_aKKYxn4tvrqPjcTzZ6EQ.cookies', '--skip-download', '-s', '--flat-playlist', 'https://www.youtube.com/channel/UCO_aKKYxn4tvrqPjcTzZ6EQ/community']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2021.12.27 [6223f67a8]
[debug] Python version 3.10.1 (CPython 64bit) - Linux-5.15.10-arch1-1-x86_64-with-glibc2.33
[debug] exe versions: ffmpeg 4.4.1 (setts), ffprobe 4.4.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2021.12.27, Current version: 2021.12.27
yt-dlp is up to date (2021.12.27)
[debug] [youtube:tab] Extracting URL: https://www.youtube.com/channel/UCO_aKKYxn4tvrqPjcTzZ6EQ/community
[youtube:tab] UCO_aKKYxn4tvrqPjcTzZ6EQ: Downloading webpage
[debug] [youtube:tab] Final URL: https://www.youtube.com/channel/UCO_aKKYxn4tvrqPjcTzZ6EQ/community
[download] Downloading playlist: Ceres Fauna Ch. hololive-EN - Community
[debug] [youtube:tab] Extracted SAPISID cookie
[youtube:tab] UCO_aKKYxn4tvrqPjcTzZ6EQ page 1: Downloading API JSON
[youtube:tab] UCO_aKKYxn4tvrqPjcTzZ6EQ page 2: Downloading API JSON
[youtube:tab] playlist Ceres Fauna Ch. hololive-EN - Community: Downloading 14 videos
[download] Downloading video 1 of 14
[download] Downloading video 2 of 14
[download] Downloading video 3 of 14
[download] Downloading video 4 of 14
[download] Downloading video 5 of 14
[download] Downloading video 6 of 14
[download] Downloading video 7 of 14
[download] Downloading video 8 of 14
[download] Downloading video 9 of 14
[download] Downloading video 10 of 14
[download] Downloading video 11 of 14
[download] Downloading video 12 of 14
[download] Downloading video 13 of 14
[download] Downloading video 14 of 14
[download] Finished downloading playlist: Ceres Fauna Ch. hololive-EN - Community

# Alternative method, without valid cookies (public videos/posts only)
[debug] Command-line config: ['-Uv', '--cookies', '/tmp/misspeeled.txt', '--skip-download', '-s', '--flat-playlist', 'https://www.youtube.com/channel/UCO_aKKYxn4tvrqPjcTzZ6EQ/community']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2021.12.27 [6223f67a8]
[debug] Python version 3.10.1 (CPython 64bit) - Linux-5.15.10-arch1-1-x86_64-with-glibc2.33
[debug] exe versions: ffmpeg 4.4.1 (setts), ffprobe 4.4.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2021.12.27, Current version: 2021.12.27
yt-dlp is up to date (2021.12.27)
[debug] [youtube:tab] Extracting URL: https://www.youtube.com/channel/UCO_aKKYxn4tvrqPjcTzZ6EQ/community
[youtube:tab] UCO_aKKYxn4tvrqPjcTzZ6EQ: Downloading webpage
[debug] [youtube:tab] Final URL: https://www.youtube.com/channel/UCO_aKKYxn4tvrqPjcTzZ6EQ/community
[download] Downloading playlist: Ceres Fauna Ch. hololive-EN - Community
[youtube:tab] UCO_aKKYxn4tvrqPjcTzZ6EQ page 1: Downloading API JSON
[youtube:tab] UCO_aKKYxn4tvrqPjcTzZ6EQ page 2: Downloading API JSON
[youtube:tab] playlist Ceres Fauna Ch. hololive-EN - Community: Downloading 2 videos
[download] Downloading video 1 of 2
[download] Downloading video 2 of 2
[download] Finished downloading playlist: Ceres Fauna Ch. hololive-EN - Community
```

**Comment by coletdjnz** [comment]
I agree we should have better handling for this. There does seem to be some checking for tab redirects in the code, (used for /live and redirecting to /videos), including raising a warning if we are being redirected. But the latter does not appear to be working in this case? 

If we fix that we could potentially add an option to not redirect, or better, not redirect by default. Since, I agree with you, these tab redirects by YouTube just end up causing yt-dlp to extract unwanted data most of the time.


---

> Scraping each video for availability matching "subscriber_only". This works, but is very slow, increases chances of ratelimiting, and can be unreliable as the availability of the video could change.

We _did_ add functionality for getting the members-only availability from the playlist page, though I'm not sure if this works with tabs. Might look into this too.

**Comment by pukkandan** [comment]
> We did add functionality for getting the members-only availability from the playlist page, though I'm not sure if this works with tabs. Might look into this too.

Even if the data is available, the filter isn't run when --flat-playlist
