### ISSUE TITLE
Unavailable videos not included in playlist count

### ISSUE THREAD

**Issue by JMan-Zx** [yt-dlp/yt-dlp#231]
Youtube playlist x with A B C D E, where B is unavailable, A and C downloaded in archive file.

Expected behavior (youtube-dl if it fixed 100 videos only issue): download resumes from D. D has %(playlist_index) = 4, E has %(playlist_index) = 5, 
yt-dlp behavior: download resumes from D, D has %(playlist_index) = 3, sharing the same index with downloaded C. E has %(playlist_index) = 4.

Can this be updated so that new downloads won't be confused with existing ones if some more videos are made unavailable in the playlist?

**Comment by pukkandan** [comment]
The behavior should be same in both. Show log of both youtube-dl and yt-dlp for same URL
