### ISSUE TITLE
improve readability of console log

### ISSUE THREAD

**Issue by chrizilla** [yt-dlp/yt-dlp#2312]
### Checklist
- [X] I'm reporting a feature request
- [X] I've verified that I'm running yt-dlp version **2021.12.27**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

# proposal
The console log could have alternating colors to improve readability:
```
line 1: white
line 2: gray
line 3: white
line 4: gray
line 5: white
line 6: gray
etc.
```
# rationale
I find it a bit difficult to read, when the screen is full of text:
![img1](https://i.imgur.com/VKtSapj.png)
Alternating colors would improve readability IMO:
![img2](https://i.imgur.com/izREEGS.png)

**Comment by Zirro** [comment]
Showing alternating colors for each line sounds like it would be more within the domain of the terminal emulator itself - by applying a theme for example - rather than the textual interface of the application running within it.

The common way to use color to increase CLI readability looks to be by coloring parts of the text itself, depending on the type of output it represents. The output from aria2 is a good example of this, and yt-dlp could probably make good use of it too (as long as an option to turn it off is also provided for those who'd prefer that).

**Comment by chrizilla** [comment]
> The output from aria2 is a good example of this, and yt-dlp could probably make good use of it too

thanks for your input. Can you provide an example screenshot from aria2 ?

> Showing alternating colors for each line sounds like it would be more within the domain of the terminal emulator itself

you mean it's impossible for yt-dlp ?

**Comment by pukkandan** [comment]
> yt-dlp could probably make good use of it too (as long as an option to turn it off is also provided for those who'd prefer that).

We already do - though, not in too many places. The only prominently colored sections are progress, -F, errors and warnings. If you have more specific suggestions for coloring some other another section, I'm all ears (or even better, u can make PR. You just need to wrap the relevant text in `ydl._format_screen()`)

> > Showing alternating colors for each line sounds like it would be more within the domain of the terminal emulator itself

> you mean it's impossible for yt-dlp ?

Technically, it is possible. But it's out of scope and wont be done

**Comment by chrizilla** [comment]
Why out of scope?
Don't you think it would improve the readability? (I added screenshots to the OP)

**Comment by pukkandan** [comment]
> Why out of scope?

Because this:

> Showing alternating colors for each line sounds like it would be more within the domain of the terminal emulator itself - by applying a theme for example - rather than the textual interface of the application running within it.

In UNIX, you can do something like https://stackoverflow.com/questions/1831527. On windows, it's probably a bit harder

---

> Don't you think it would improve the readability? (I added screenshots to the OP)

Out of scope != Not usefull. It just means it's not in the scope of yt-dlp to implement

**Comment by chrizilla** [comment]
Ok, I see what you mean now.

But as you point out, you already use colors for some output (apparently not ouf of scope). I don't yet get why my proposal is any different from what you are already doing (highlighting some stuff).

Users could still turn this behaviour on/off in the options or override that with a theme as shown in your stackoverflow link, right?

So in case you agree that it's useful, is there any offsetting conflict/downside/problem that led to your decision ?
