### ISSUE TITLE
res:480 stopped working!

### ISSUE THREAD

**Issue by whitetop** [yt-dlp/yt-dlp#2313]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

Is anyone else having problems downloading with res:480/720 ect? it used to work find but now its stopped working.

yt-dlp -v -s "res:480" -f "https://www.youtube.com/watch?v=sZX4MmdXPRA" -o AEW.DARK.11th.Jan.2022.mp4

this one works fine but no matter what i do it just downloads 1080p
yt-dlp --get-filename -o '%(title)s.%(ext)s' my704d_l-a8
yt-dlp -f "480[ext=mp4]+bestaudio[ext=m4a]/480[ext=mp4]/480" https://youtu.be/my704d_l-a8
timeout 50

I use bat files yes.

### Verbose log

```shell
C:\Users\name\Desktop\youtubedownloader>yt-dlp -v -s "res:480" -f "https://w
ww.youtube.com/watch?v=sZX4MmdXPRA" -o AEW.DARK.11th.Jan.2022.mp4
[debug] Command-line config: ['-v', '-s', 'res:480', '-f', 'https://www.youtube.
com/watch?v=sZX4MmdXPRA', '-o', 'AEW.DARK.11th.Jan.2022.mp4']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8 (No ANSI), err utf-8 (No A
NSI), pref cp1252
[debug] yt-dlp version 2021.12.27 [6223f67] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-2008ServerR2-6.1.7601-SP
1
[debug] exe versions: ffmpeg N-69723-gc7ad1f5 (needs_adtstoasc), rtmpdump 2.4
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [generic] Extracting URL: res:480
ERROR: [generic] 'res:480' is not a valid URL. Set --default-search "ytsearch" (
or run  yt-dlp "ytsearch:res:480" ) to search YouTube
  File "yt_dlp\extractor\common.py", line 599, in extract
  File "yt_dlp\extractor\generic.py", line 2558, in _real_extract


C:\Users\name\Desktop\youtubedownloader>timeout 600

Waiting for 599 seconds, press a key to continue ...
```

**Comment by whitetop** [comment]
> it should be capital `-S`, not `-s`. For the second one, syntax is totally wrong

I've kept this code with lower s and it worked fine so i don't think that is the problem.

**Comment by pukkandan** [comment]
Why don't you try it anyway? If it doesn't work, show verbose log

Or, to the contrary, if the lowercase worked in an older version, provide logs of that

**Comment by whitetop** [comment]
Changed and still the same and how on earth can i show a log on when it was working? asking that is a bit stupid.

C:\Users\name\Desktop\youtubedownloader>yt-dlp -v -S "res:480" -f "https://w
ww.youtube.com/watch?v=sZX4MmdXPRA" -o AEW.DARK.11th.Jan.2022.mp4
[debug] Command-line config: ['-v', '-S', 'res:480', '-f', 'https://www.youtube.
com/watch?v=sZX4MmdXPRA', '-o', 'AEW.DARK.11th.Jan.2022.mp4']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8 (No ANSI), err utf-8 (No A
NSI), pref cp1252
[debug] yt-dlp version 2021.12.27 [6223f67] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-2008ServerR2-6.1.7601-SP
1
[debug] exe versions: ffmpeg N-69723-gc7ad1f5 (needs_adtstoasc), rtmpdump 2.4
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Usage: yt-dlp [OPTIONS] URL [URL...]

yt-dlp: error: You must provide at least one URL.
Type yt-dlp --help to see a list of all options.

C:\Users\name\Desktop\youtubedownloader>timeout 600

Waiting for 597 seconds, press a key to continue ...

**Comment by whitetop** [comment]
> > yt-dlp -v -S "res:480" -f "www.youtube.com/watch?v=sZX4MmdXPRA" -o AEW.DARK.11th.Jan.2022.mp4
> 
> You are passing the URL as argument to `-f`. Remove `-f` if you don't want to set it...
> 
> ```
> yt-dlp -v -S "res:480" "www.youtube.com/watch?v=sZX4MmdXPRA"
> ```

Cheers, its strange it used to work then it stopped, even with -f. Thanks as its working now.
