### ISSUE TITLE
Site Request: PokerGO.com

### ISSUE THREAD

**Issue by tristanfleming** [yt-dlp/yt-dlp#2316]
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2021.12.27**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

United States

### Example URLs

single video: https://www.pokergo.com/videos/f1b9c644-75ee-46ac-bb4e-14a74ebcf74a

### Description

I am able to download the mp4 of the stream using the Chrome extension Video Downloader PLUS (https://chrome.google.com/webstore/detail/video-downloader-plus/njgehaondchbmjmajphnhlojfnbfokng?hl=en)

Also using Video DownloadHelper extension for Chrome/Edge, I am able to grab a .m3u8 link. I can then use yt-dlp to grab that, but at an extremely slow speed compared to web-based extensions.
https://videos-fms.jwpsrv.com/0_61dfc74f_0xdc8245585f4ef442608fd1e09d838f5f9172a632/content/conversions/B9cQSE7A/videos/bs9enx5M-32738461.mp4.m3u8

I have account details for when someone is ready for those.

### Verbose log

```shell
[debug] Command-line config: ['-Uv', '--ignore-config', 'https://www.pokergo.com/videos/f1b9c644-75ee-46ac-bb4e-14a74ebcf74a']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2021.12.27 [6223f67] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] exe versions: ffmpeg git-2020-04-20-cacdac8, ffprobe git-2020-04-20-cacdac8
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2021.12.27, Current version: 2021.12.27
yt-dlp is up to date (2021.12.27)
[debug] [generic] Extracting URL: https://www.pokergo.com/videos/f1b9c644-75ee-46ac-bb4e-14a74ebcf74a
[generic] f1b9c644-75ee-46ac-bb4e-14a74ebcf74a: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] f1b9c644-75ee-46ac-bb4e-14a74ebcf74a: Downloading webpage
[generic] f1b9c644-75ee-46ac-bb4e-14a74ebcf74a: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://www.pokergo.com/videos/f1b9c644-75ee-46ac-bb4e-14a74ebcf74a
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1353, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1423, in __extract_info
  File "yt_dlp\extractor\common.py", line 599, in extract
  File "yt_dlp\extractor\generic.py", line 3829, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.pokergo.com/videos/f1b9c644-75ee-46ac-bb4e-14a74ebcf74a
```

**Comment by Ashish0804** [comment]
Site is completely paywalled.
I can't guarantee if I will be able to support this but feel free to email me the details if u want me to look.
`Ashish08@protonmail.com`

**Comment by tristanfleming** [comment]
> `Ashish08@protonmail.com`

Thanks for taking a look. I have emailed you the credentials.
