### ISSUE TITLE
video codec preference to "unknown"

### ISSUE THREAD

**Issue by 362227** [yt-dlp/yt-dlp#2321]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

preference to 1 and 5 .  thanks

![QQ截图20220113154057](https://user-images.githubusercontent.com/91358231/149286773-9ba677df-b0d1-4572-89d1-3e2183507608.jpg)
![QQ截图20220113154123](https://user-images.githubusercontent.com/91358231/149286781-ea561b27-78ff-47e6-bc68-0d86ae7d65ea.jpg)

I tried
`yt-dlp  --format "(bestvideo[vcodec^=unknown]/bestvideo)" "https://www.instagram.com/p/CYn-s6FKNcg --add-header "cookie: *****"` 
but failed

**Comment by pukkandan** [comment]
what!?

**Comment by pukkandan** [comment]
`unknown` here means the absence of a known value. From what little you have show, I think `-f b` would work for you. If not, you will need to provide proper verbose log for any more help

Run this and copy-paste the **entire** console output **as text**

    yt-dlp -UvF "YOUR URL"

**Comment by 362227** [comment]
> -f b

It works. thanks
