### ISSUE TITLE
Options

### ISSUE THREAD

**Issue by nddwss** [yt-dlp/yt-dlp#2322]
### Checklist

- [X] I'm reporting a feature request
- [X] I've verified that I'm running yt-dlp version **2021.12.27**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

Can it be added to exit on completion or error? Or is there any option to achieve this

**Comment by pukkandan** [comment]
elaborate

What are you doing? what currently happens? what do you want to happen?

**Comment by gamer191** [comment]
> Can it be added to exit on completion or error? Or is there any option to achieve this

That already exists. If you want it to exit on errors, do --abort-on-error. Otherwise, do --ignore-errors

**Comment by nddwss** [comment]
When the program completes the task or makes an error, it is necessary to press any key to exit the operation. . I want to write a shell script to run 10 tasks in a loop, determine whether it is successful, record the log, and then process it. . . How can I cancel this step of pressing any key?

**Comment by pukkandan** [comment]
> When the program completes the task or makes an error, it is necessary to press any key to exit the operation. . 

No, it is not. You are probably not using yt-dlp directly, but some script that is asking this
