### ISSUE TITLE
Reddit Embeds + -S "res:360" command = audio/video de-sync in MPV. 

### ISSUE THREAD

**Issue by MintMain21** [yt-dlp/yt-dlp#2336]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2021.12.27**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United States

### Description

I prefer to keep videos around 360p when streaming through MPV, and I use MPV for as much online videos as I can, including Reddit Embeds. The problem is though, when I have this setting hardwired into mpv.config, reddit embeds will have desynced video/audio. See, for example, https://www.reddit.com/r/marvelstudios/comments/s3c1q6/this_is_one_of_my_favorite_quotes_from_the_mcu/. 

PS: I'm on Linux Mint 20.3, and I'm using the MPV Flatpak. 

### Verbose log

```shell
[debug] Command-line config: ['-Uv']
[debug] Portable config file: /home/michael/bin/yt-dlp.conf
[debug] Portable config: ['--embed-thumbnail', '--embed-metadata', '-o', '~/YT-DLP/%(title).200s.%(ext)s', '-S', 'res:360']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2021.12.27 [6223f67a8] (zip)
[debug] Python version 3.8.10 (CPython 64bit) - Linux-5.4.0-94-generic-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4, rtmpdump 2.4
[debug] Optional libraries: Crypto, secretstorage, mutagen, sqlite
[debug] Proxy map: {}
Latest version: 2021.12.27, Current version: 2021.12.27
yt-dlp is up to date (2021.12.27)
```

**Comment by pukkandan** [comment]
I can't reproduce by downloading the video and playing it. Ask mpv devs, not here
