### ISSUE TITLE
[ndr]: Unable to extract json url

### ISSUE THREAD

**Issue by leoarnold** [yt-dlp/yt-dlp#2337]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2021.12.27**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Germany

### Description

I try to download this video from NDR since it was not published in ARDmediathek yet. Download does not work though.

### Verbose log

```shell
$  yt-dlp -Uv 'https://daserste.ndr.de/panorama/archiv/2022/Das-Ende-des-Schnitzels,schnitzel236.html'
[debug] Command-line config: ['-Uv', 'https://daserste.ndr.de/panorama/archiv/2022/Das-Ende-des-Schnitzels,schnitzel236.html']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2021.12.27 [6223f67a8] (zip)
[debug] Python version 3.8.10 (CPython 64bit) - Linux-5.11.0-46-generic-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4
[debug] Optional libraries: Crypto, secretstorage, sqlite
[debug] Proxy map: {}
Latest version: 2021.12.27, Current version: 2021.12.27
yt-dlp is up to date (2021.12.27)
[debug] [ndr] Extracting URL: https://daserste.ndr.de/panorama/archiv/2022/Das-Ende-des-Schnitzels,schnitzel236.html
[ndr] Das-Ende-des-Schnitzels: Downloading webpage
WARNING: [ndr] unable to extract json url; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
ERROR: [ndr] schnitzel236: Unable to extract json url; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
  File "/home/leoarnold/bin/yt-dlp/yt_dlp/extractor/common.py", line 599, in extract
    ie_result = self._real_extract(url)
  File "/home/leoarnold/bin/yt-dlp/yt_dlp/extractor/ndr.py", line 22, in _real_extract
    return self._extract_embed(webpage, display_id, id)
  File "/home/leoarnold/bin/yt-dlp/yt_dlp/extractor/ndr.py", line 118, in _extract_embed
    json_url = base_url + self._search_regex(r'apiUrl\s?=\s?\'([^\']+)\'', webpage, 'json url').replace(
  File "/home/leoarnold/bin/yt-dlp/yt_dlp/extractor/common.py", line 1173, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
```

**Comment by dirkf** [comment]
Working in https://github.com/ytdl-org/youtube-dl/pull/30531, with target in JS `var sophoraID = ...`.

**Comment by JensKorte** [comment]
yt-dlp doesn't work for me on other pages of ndr.de any more. Yesterday it worked. I am not sure, if these issues are the same:

yt-dlp -f b https://www.ndr.de/nachrichten/hamburg/Unterwegs-mit-einem-Hamburger-Hilfskonvoi-zur-ukrainischen-Grenze,hilfskonvoi106.html
[ndr] Unterwegs-mit-einem-Hamburger-Hilfskonvoi-zur-ukrainischen-Grenze: Downloading webpage
[ndr] hilfskonvoi106: Downloading JSON metadata
[ndr] hilfskonvoi106: Downloading m3u8 information
ERROR: [ndr] hilfskonvoi106: Failed to download m3u8 information: HTTP Error 502: Bad Gateway (caused by <HTTPError 502: 'Bad Gateway'>); please report this issue on  https://github.com/yt-dlp/yt-dlp , filling out the "Broken site" issue template properly. Confirm you are on the latest version using -U (caused by <HTT
PError 502: 'Bad Gateway'>); please report this issue on  https://github.com/yt-dlp/yt-dlp , filling out the "Broken site" issue template properly. Confirm you are on the latest version using -U

yt-dlp -U
Latest version: 2022.02.04, Current version: 2022.02.04
yt-dlp is up to date (2022.02.04)

**Comment by dirkf** [comment]
Also gettable in yt-dl git master: it skips a 400 error from one potential, probably obsolete, target, and the 502 from the m3u8 target, which may also be obsolete.

`-g` gives me https://mediandr-a.akamaihd.net/progressive/2022/0303/TV-20220303-2030-1100.hd.mp4, in case Jens wants to watch what looks like a news item while it's fresh.

**Comment by JensKorte** [comment]
> Also gettable in yt-dl git master (PR now merged): it skips a 400 error from one potential, probably obsolete, target, and the 502 from the m3u8 target, which may also be obsolete.
> 
> `-g` gives me https://mediandr-a.akamaihd.net/progressive/2022/0303/TV-20220303-2030-1100.hd.mp4, in case Jens wants to watch what looks like a news item while it's fresh.

:D Thanks. yt-dlp works for me again.
