### ISSUE TITLE
Unable to download API page: IncompleteRead

### ISSUE THREAD

**Issue by coreyoilar** [yt-dlp/yt-dlp#2344]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2021.12.27**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

USA

### Description

CLI says to report the problem so here's a small copy & paste from the window:

[youtube] CXO_uawnjyI: Downloading webpage
[youtube] CXO_uawnjyI: Downloading android player API JSON
[info] CXO_uawnjyI: Downloading 1 format(s): 303+251
[info] Video subtitle live_chat.json is already present
[info] Video thumbnail is already present
WARNING: webm doesn't support embedding a thumbnail, mkv will be used
[download] Resuming download at byte 2028535639
[download] Destination: Z:\# INCOMING #\YOUTUBE-DL\Perry Stone\Perry Stone - Videos\20191029-0445 - Perry Stone _ End Time Warfare Concealed in the Parables _ Omega Center International.f303.webm
[download] 100% of 2.74GiB in 01:28
[download] Destination: Z:\# INCOMING #\YOUTUBE-DL\Perry Stone\Perry Stone - Videos\20191029-0445 - Perry Stone _ End Time Warfare Concealed in the Parables _ Omega Center International.f251.webm
[download] 100% of 93.95MiB in 00:08
[Merger] Merging formats into "Z:\# INCOMING #\YOUTUBE-DL\Perry Stone\Perry Stone - Videos\20191029-0445 - Perry Stone _ End Time Warfare Concealed in the Parables _ Omega Center International.mkv"
Deleting original file Z:\# INCOMING #\YOUTUBE-DL\Perry Stone\Perry Stone - Videos\20191029-0445 - Perry Stone _ End Time Warfare Concealed in the Parables _ Omega Center International.f303.webm (pass -k to keep)
Deleting original file Z:\# INCOMING #\YOUTUBE-DL\Perry Stone\Perry Stone - Videos\20191029-0445 - Perry Stone _ End Time Warfare Concealed in the Parables _ Omega Center International.f251.webm (pass -k to keep)
[VideoRemuxer] Not remuxing media file 'Z:\\# INCOMING #\\YOUTUBE-DL\\Perry Stone\\Perry Stone - Videos\\20191029-0445 - Perry Stone _ End Time Warfare Concealed in the Parables _ Omega Center International.mkv'; already is in target format mkv
WARNING: JSON subtitles cannot be embedded
[Metadata] Adding metadata to "Z:\# INCOMING #\YOUTUBE-DL\Perry Stone\Perry Stone - Videos\20191029-0445 - Perry Stone _ End Time Warfare Concealed in the Parables _ Omega Center International.mkv"
[ThumbnailsConvertor] Converting thumbnail "Z:\# INCOMING #\YOUTUBE-DL\Perry Stone\Perry Stone - Videos\20191029-0445 - Perry Stone _ End Time Warfare Concealed in the Parables _ Omega Center International.webp" to png
[EmbedThumbnail] ffmpeg: Adding thumbnail to "Z:\# INCOMING #\YOUTUBE-DL\Perry Stone\Perry Stone - Videos\20191029-0445 - Perry Stone _ End Time Warfare Concealed in the Parables _ Omega Center International.mkv"
Deleting original file Z:\# INCOMING #\YOUTUBE-DL\Perry Stone\Perry Stone - Videos\20191029-0445 - Perry Stone _ End Time Warfare Concealed in the Parables _ Omega Center International.webp (pass -k to keep)
Deleting original file Z:\# INCOMING #\YOUTUBE-DL\Perry Stone\Perry Stone - Videos\20191029-0445 - Perry Stone _ End Time Warfare Concealed in the Parables _ Omega Center International.png (pass -k to keep)
[XAttrMetadata] Writing metadata to file's xattrs
[download] Downloading video 446 of 1438
[youtube] JwumjCY5sV0: Downloading webpage
WARNING: [youtube] Unable to download webpage: IncompleteRead(98040 bytes read)
[youtube] JwumjCY5sV0: Downloading android player API JSON
WARNING: [youtube] IncompleteRead(5 bytes read). Retrying ...
[youtube] JwumjCY5sV0: Downloading android player API JSON (retry #1)
WARNING: [youtube] IncompleteRead(16 bytes read). Retrying ...
[youtube] JwumjCY5sV0: Downloading android player API JSON (retry #2)
WARNING: [youtube] IncompleteRead(16 bytes read). Retrying ...
[youtube] JwumjCY5sV0: Downloading android player API JSON (retry #3)
[youtube] JwumjCY5sV0: Downloading iframe API JS
WARNING: [youtube] Unable to download webpage: IncompleteRead(565 bytes read)
[youtube] JwumjCY5sV0: Downloading web player API JSON
WARNING: [youtube] IncompleteRead(15441 bytes read). Retrying ...
[youtube] JwumjCY5sV0: Downloading web player API JSON (retry #1)
WARNING: [youtube] Unable to download API page: IncompleteRead(21 bytes read) (caused by IncompleteRead(21 bytes read)); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
WARNING: [youtube] nsig extraction failed: You may experience throttling for some formats
n = cFlfSUQcWbCoEXIR ; player = None
Cannot decrypt nsig without player_url; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
WARNING: [youtube] nsig extraction failed: You may experience throttling for some formats
n = vi-Y-h4zy4N8Bwe6 ; player = None
Cannot decrypt nsig without player_url; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
[youtube] JwumjCY5sV0: Downloading initial data API JSON
WARNING: [youtube] IncompleteRead(64591 bytes read). Retrying ...
[youtube] JwumjCY5sV0: Downloading initial data API JSON (retry #1)
WARNING: [youtube] IncompleteRead(48215 bytes read). Retrying ...
[youtube] JwumjCY5sV0: Downloading initial data API JSON (retry #2)
WARNING: [youtube] IncompleteRead(64575 bytes read). Retrying ...
[youtube] JwumjCY5sV0: Downloading initial data API JSON (retry #3)
WARNING: [youtube] Unable to download API page: IncompleteRead(64583 bytes read) (caused by IncompleteRead(64583 bytes read)); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
ERROR: local variable 'contents' referenced before assignment
[download] Downloading video 447 of 1438
[youtube] 4i3kMsvR9hY: Downloading webpage
WARNING: [youtube] Unable to download webpage: IncompleteRead(129177 bytes read)
[youtube] 4i3kMsvR9hY: Downloading android player API JSON
WARNING: [youtube] IncompleteRead(19 bytes read). Retrying ...
[youtube] 4i3kMsvR9hY: Downloading android player API JSON (retry #1)
WARNING: [youtube] IncompleteRead(1 bytes read). Retrying ...
[youtube] 4i3kMsvR9hY: Downloading android player API JSON (retry #2)
WARNING: [youtube] IncompleteRead(5 bytes read). Retrying ...
[youtube] 4i3kMsvR9hY: Downloading android player API JSON (retry #3)
[youtube] 4i3kMsvR9hY: Downloading iframe API JS
[youtube] 4i3kMsvR9hY: Downloading web player API JSON
WARNING: [youtube] IncompleteRead(97351 bytes read). Retrying ...
[youtube] 4i3kMsvR9hY: Downloading web player API JSON (retry #1)
WARNING: [youtube] IncompleteRead(97360 bytes read). Retrying ...
[youtube] 4i3kMsvR9hY: Downloading web player API JSON (retry #2)

### Verbose log

```shell
yt-dlp --verbose
[debug] Command-line config: ['--verbose']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2021.12.27 [6223f67] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] exe versions: ffmpeg 4.4-essentials_build-www.gyan.dev (setts), ffprobe 4.4-essentials_build-www.gyan.dev
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Usage: yt-dlp [OPTIONS] URL [URL...]
```

**Comment by coletdjnz** [comment]
Likely a network issue server side or an issue with your proxy (if you are using one, I can't tell as you didn't post a verbose log)
