### ISSUE TITLE
add support for newsy.com

### ISSUE THREAD

**Issue by 2011** [yt-dlp/yt-dlp#2346]
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2021.12.27**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Example URLs

https://www.newsy.com/stories/nft-trend-leads-to-fraudulent-art-auctions/

### Description

A section of the source (which contains the video link):

`<div id="main-video-player" class="video-container" data-video-player="{&quot;id&quot;:&quot;609d65125b086c24fb529312&quot;,&quot;stream&quot;:&quot;https:\/\/content.uplynk.com\/89b28a35bdfc4da48c2682511cea449b.m3u8?rays=fghed&quot;,&quot;headline&quot;:&quot;NFT Art Auctions Have A Piracy Problem&quot;,&quot;url&quot;:&quot;https:\/\/www.newsy.com\/stories\/nft-trend-leads-to-fraudulent-art-auctions\/&quot;,&quot;image&quot;:&quot;https:\/\/cdn.newsy.com\/images\/videos\/x\/1620927824_xyrrP4.jpg&quot;,&quot;image_alt&quot;:&quot;A drawing of a thief in the middle of an NFT auction&quot;,&quot;old_id&quot;:114618,&quot;autostart&quot;:true,&quot;file&quot;:&quot;https:\/\/cdn.newsy.com\/videos\/609d65125b086c24fb529312.mov&quot;,&quot;caption&quot;:&quot;https:\/\/cdn.newsy.com\/captions\/609d65125b086c24fb529312.xml&quot;,&quot;duration&quot;:339630,&quot;ip_address&quot;:&quot;23.82.193.109&quot;,&quot;device_ua&quot;:&quot;Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/92.0.4515.159 Safari\/537.36&quot;,&quot;noad&quot;:false,&quot;sharing&quot;:true}"></div>`

An upgraded generic extractor (that can remove the quoting backslashes) might work if it searches for uplynk.

### Verbose log

```shell
$ yt-dlp-2021.12.27 -v 'https://www.newsy.com/stories/nft-trend-leads-to-fraudulent-art-auctions/'
[debug] Command-line config: ['-v', 'https://www.newsy.com/stories/nft-trend-leads-to-fraudulent-art-auctions/']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2021.12.27 [6223f67a8] (zip)
[debug] Python version 3.9.9 (CPython 64bit) - Linux-5.15.11-with-glibc2.33
[debug] exe versions: ffmpeg 4.4.1 (setts), ffprobe 4.4.1
[debug] Optional libraries: Crypto
[debug] Proxy map: {}
[debug] [generic] Extracting URL: https://www.newsy.com/stories/nft-trend-leads-to-fraudulent-art-auctions/
[generic] nft-trend-leads-to-fraudulent-art-auctions: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] nft-trend-leads-to-fraudulent-art-auctions: Downloading webpage
[generic] nft-trend-leads-to-fraudulent-art-auctions: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://www.newsy.com/stories/nft-trend-leads-to-fraudulent-art-auctions/
Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp-2021.12.27/yt_dlp/YoutubeDL.py", line 1353, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/yt-dlp-2021.12.27/yt_dlp/YoutubeDL.py", line 1423, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/yt-dlp-2021.12.27/yt_dlp/extractor/common.py", line 599, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/yt-dlp-2021.12.27/yt_dlp/extractor/generic.py", line 3829, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.newsy.com/stories/nft-trend-leads-to-fraudulent-art-auctions/

[download works fine using .m3u8 link in the source]

$ yt-dlp-2021.12.27 -v 'https://content.uplynk.com/89b28a35bdfc4da48c2682511cea449b.m3u8'
[debug] Command-line config: ['-v', 'https://content.uplynk.com/89b28a35bdfc4da48c2682511cea449b.m3u8']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2021.12.27 [6223f67a8] (zip)
[debug] Python version 3.9.9 (CPython 64bit) - Linux-5.15.11-glibc2.33
[debug] exe versions: ffmpeg 4.4.1 (setts), ffprobe 4.4.1
[debug] Optional libraries: Crypto
[debug] Proxy map: {}
[debug] [uplynk] Extracting URL: https://content.uplynk.com/89b28a35bdfc4da48c2682511cea449b.m3u8
[uplynk] 89b28a35bdfc4da48c2682511cea449b: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[uplynk] 89b28a35bdfc4da48c2682511cea449b: Downloading JSON metadata
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 89b28a35bdfc4da48c2682511cea449b: Downloading 1 format(s): 5912
[debug] Invoking downloader on "http://content-ausw2-up-1.uplynk.com/89b28a35bdfc4da48c2682511cea449b/h.m3u8"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 83
[download] Destination: NFT Art Auctions Are Facing A Piracy Problem [89b28a35bdfc4da48c2682511cea449b].mp4
[download] 100% of 239.36MiB in 03:40
[debug] ffprobe command line: ffprobe -hide_banner -show_format -show_streams -print_format json 'file:NFT Art Auctions Are Facing A Piracy Problem [89b28a35bdfc4da48c2682511cea449b].mp4'
[FixupM3u8] Fixing MPEG-TS in MP4 container of "NFT Art Auctions Are Facing A Piracy Problem [89b28a35bdfc4da48c2682511cea449b].mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:NFT Art Auctions Are Facing A Piracy Problem [89b28a35bdfc4da48c2682511cea449b].mp4' -c copy -map 0 -dn -f mp4 -bsf:a aac_adtstoasc -movflags +faststart 'file:NFT Art Auctions Are Facing A Piracy Problem [89b28a35bdfc4da48c2682511cea449b].temp.mp4'
```

**Comment by Ashish0804** [comment]
> An upgraded generic extractor (that can remove the quoting backslashes) might work if it searches for uplynk.

I prefer adding a new extractor for it. If that's okay with @pukkandan then I can start working on this.

**Comment by pukkandan** [comment]
sure, go ahead
