### ISSUE TITLE
[YouTube] [ChannelTab] extract subscriber count and channel views

### ISSUE THREAD

**Issue by bbilly1** [yt-dlp/yt-dlp#2350]
### Checklist

- [X] I'm reporting a site feature request
- [X] I've verified that I'm running yt-dlp version **2021.12.27**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Example URLs

https://www.youtube.com/channel/UCR1IuLEqb6UEA_zQ81kwXfg

### Description

I have implemented a scraper with BeautifulSoup to extract some additional metadata from YouTube Channel for a [project](https://github.com/bbilly1/tubearchivist/blob/7028621bc576936c1b9808336b481a00252ab997/tubearchivist/home/src/index.py#L88) of mine. I was wondering if there would be interest to integrate that into yt-dlp? Both of these fields are extractable from the page without an API call.

- Channel Subscribers: This information is available in the ytInitialData script in header -> c4TabbedHeaderRenderer -> subscriberCountText
  - The number is unfortunately truncated and as a string, e.g. "2.03M subscribers"
  - As far as I have observed the unit can be *M* for *millions*, *K* for *thousands* and none for below 1000.
  - That is language specific, but as far as I know yt-dlp defaults to english already?
- Channel Views: This information is in ytInitialData at itemSectionRenderer -> contents -> viewCountText.
  - This is as a string and will need some logic to extract the numbers.

Additionally, for extracting banners there is already an issue open: #2237.

This would be a great addition to have upstream directly in yt-dlp.

### Verbose log

```shell
Does not apply...
```

**Comment by coletdjnz** [comment]
For subscriber count we maybe could add a field such as`followers` or `playlist_followers`? This can probably be extracted in other places the subscriber count shows up too. Language is not an issue, we enforce English now for YouTube regardless due to reasons like this. 

For the channel view count, I'm not sure where you were looking. I think you might've gotten mixed up with individual video view counts? The channel view count is only provided in the response for the about tab.

**Comment by bbilly1** [comment]
> This can probably be extracted in other places the subscriber count shows up too.

I did some testing, the *subscriberCountText* field is also available on the Video page (https://www.youtube.com/watch?v=\<video-id\>) but at a different location in the json: videoSecondaryInfoRenderer -> owner -> videoOwnerRenderer

But it is for example not available in the playlist page (https://www.youtube.com/playlist?list=\<playlist-id\>).

> For the channel view count, I'm not sure where you were looking. I think you might've gotten mixed up with individual video view counts? The channel view count is only provided in the response for the about tab.

Yes, you are right about this one, I've meant to specify, that field is only available at the about page (https://www.youtube.com/c/\<channel-name\>/about). None the less, still useful, but I guess less easy to access if you need to request a specific page /about to get that...
