### ISSUE TITLE
[Peertube] Unsupported URL?

### ISSUE THREAD

**Issue by HalvorRaknes** [yt-dlp/yt-dlp#2351]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2021.12.27**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Norway

### Description

Is it the top-level-domain being .se that's confusing yt-dlp? I searched the bugtracker and clearly got the impressions that Peertube is a supported site.

### Verbose log

```shell
$ yt-dlp -uv https://peertube.se/videos/w/0d0a4c14-8880-44f4-8649-c1c3064d5915
Type account password and press [Return]: 
[generic] 0d0a4c14-8880-44f4-8649-c1c3064d5915: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] 0d0a4c14-8880-44f4-8649-c1c3064d5915: Downloading webpage
[generic] 0d0a4c14-8880-44f4-8649-c1c3064d5915: Extracting information
ERROR: Unsupported URL: https://peertube.se/videos/w/0d0a4c14-8880-44f4-8649-c1c3064d5915
```

**Comment by flashdagger** [comment]
It works with this URL: https://peertube.se/w/2BoVvKYJx5gAuFzdC83Kpk

**Comment by HalvorRaknes** [comment]
There is a /video/ part of the URL in my posting that isn't there in yours. Also the rest of the URL seems to have a different structure. I copied my URL from right-clicking on the video on the page https://nordiskradio.se/?avsnitt=rn-direkt-216 and then selecting "Copy the video URL". Actually, if I click the "Peertube" link in the menu bar of the embedded video I get a 404 error.

Where did you find that first URL which is in fact the video that I was trying to download and which indeed worked fine also for me?

**Comment by flashdagger** [comment]
> Where did you find that first URL which is in fact the video that I was trying to download and which indeed worked fine also for me?

Just put the UUID into the [Peertube search bar](https://peertube.se/search?search=0d0a4c14-8880-44f4-8649-c1c3064d5915).

**Comment by pukkandan** [comment]
the URL in OP doesn't open in browser
