### ISSUE TITLE
[Facebook] Cannot parse data, public video

### ISSUE THREAD

**Issue by RoboDoc** [yt-dlp/yt-dlp#2352]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2021.12.27**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Norway

### Description

yt-dlp quits, reporting "cannot parse data", from public video. The video is verified as viewable for users that are not logged in to Facebook (tested in Firefox, incognito mode).

URL to public video: "https://www.facebook.com/1182153476/videos/10227176116527060/".

### Verbose log

```shell
$ sudo yt-dlp -Uv
[debug] Command-line config: ['-Uv']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2021.12.27 [6223f67a8] (zip)
[debug] Python version 3.10.0rc1 (CPython 64bit) - FreeBSD-14.0-CURRENT-amd64-64bit-ELF
[debug] exe versions: ffmpeg 4.4.1 (setts), ffprobe 4.4.1, rtmpdump 2.4
[debug] Optional libraries: none
[debug] Proxy map: {}
Latest version: 2021.12.27, Current version: 2021.12.27
yt-dlp is up to date (2021.12.27)

$ yt-dlp -v "https://www.facebook.com/1182153476/videos/10227176116527060/"
[debug] Command-line config: ['-v', 'https://www.facebook.com/1182153476/videos/10227176116527060/']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2021.12.27 [6223f67a8] (zip)
[debug] Python version 3.10.0rc1 (CPython 64bit) - FreeBSD-14.0-CURRENT-amd64-64bit-ELF
[debug] exe versions: ffmpeg 4.4.1 (setts), ffprobe 4.4.1, rtmpdump 2.4
[debug] Optional libraries: none
[debug] Proxy map: {}
[debug] [facebook] Extracting URL: https://www.facebook.com/1182153476/videos/10227176116527060/
[facebook] 10227176116527060: Downloading webpage
[facebook] 10227176116527060: Downloading webpage
ERROR: [facebook] 10227176116527060: Cannot parse data; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 599, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/facebook.py", line 721, in _real_extract
    return self._extract_from_url(real_url, video_id)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/facebook.py", line 667, in _extract_from_url
    raise ExtractorError('Cannot parse data')
```

**Comment by pukkandan** [comment]
Already fixed in code
