### ISSUE TITLE
add support for crowdbunker.com

### ISSUE THREAD

**Issue by cayenne17** [yt-dlp/yt-dlp#2356]
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2021.12.27**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Example URLs

- Single video: https://crowdbunker.com/v/4wETRr7C

### Description

« CrowdBunker protects our freedom of expression. It is a platform that is exclusively funded by your donations. Any individual contribution, no matter how small, allows us to expand our capabilities to better protect the freedom of all of us. »

Doesn't require an account to watch videos.

I created a small bash script to download videos from crowdbunker.com that requires curl and ffmpeg
If you want it, don't hesitate to ask me, I don't know where I can make it available. You can use it as a starting point.

### Verbose log

```shell
> yt-dlp.exe -Uv https://crowdbunker.com/v/4wETRr7C
[debug] Command-line config: ['-Uv', 'https://crowdbunker.com/v/4wETRr7C']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2021.12.27 [6223f67] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] exe versions: none
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2021.12.27, Current version: 2021.12.27
yt-dlp is up to date (2021.12.27)
[debug] [generic] Extracting URL: https://crowdbunker.com/v/4wETRr7C
[generic] 4wETRr7C: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] 4wETRr7C: Downloading webpage
[generic] 4wETRr7C: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://crowdbunker.com/v/4wETRr7C
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1353, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1423, in __extract_info
  File "yt_dlp\extractor\common.py", line 599, in extract
  File "yt_dlp\extractor\generic.py", line 3829, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://crowdbunker.com/v/4wETRr7C
```

**Comment by Ashish0804** [comment]
Extractor is really simple to add (I'll make PR soon)
@cayenne17 the api result has these fields 
```
canDelete: false
censored: false
censoredAt: null
```
Do u have an example of a video where this is true or maybe a hunch as to what a censored video is supposed to mean?
(like it can be accessed only with account or it's not visible but api request will still work or something else???)

**Comment by cayenne17** [comment]
> Extractor is really simple to add (I'll make PR soon) @cayenne17 the api result has these fields
> 
> ```
> canDelete: false
> censored: false
> censoredAt: null
> ```
> 
> Do u have an example of a video where this is true or maybe a hunch as to what a censored video is supposed to mean? (like it can be accessed only with account or it's not visible but api request will still work or something else???)


Hello,
In fact on Crowdbunker platform, you connect your account of your Youtube channel.
Crowdbunker will upload all the Youtube videos to their servers. When you watch the video on Crowdbunker, if it is not censored on Youtube, then it will watch the video on Youtube. Otherwise, if it is censored from Youtube, then it will watch it from Crowdbunker servers.

Here is an example where it says "CENSORSHIP DETECTED" : https://crowdbunker.com/v/0z4Kms8pi8I

**Comment by cayenne17** [comment]
I just found another example "CENSORSHIP DETECTED" :   https://crowdbunker.com/v/8l3mTjK3Po4

**Comment by Ashish0804** [comment]
@cayenne17 Can u provide a video with subtitles?

**Comment by cayenne17** [comment]
> subtitles

I found an example where there are subtitles in 3 languages : https://crowdbunker.com/v/85kVlAWA4YM

On the other hand there is an error on this video when it passes by Crowdbunker: 
"Impossible de lire la vidéo.
Un problème est survenu lors du chargement de la vidéo.
Error code: hls:networkError_manifestParsingError"

**Comment by cayenne17** [comment]
> @cayenne17 Can u provide a video with subtitles?

Other examples of censored video with FR subtitles : https://crowdbunker.com/v/wvQlKvLi464

**Comment by cayenne17** [comment]
> @cayenne17 Can u provide a video with subtitles?

@Ashish0804  Other examples of censored video with FR subtitles : https://crowdbunker.com/v/wvQlKvLi464

**Comment by cayenne17** [comment]
Hello,
I just tried to download a Crowdbunker video with the latest version and it doesn't work

```
> yt-dlp.exe -Uv https://crowdbunker.com/v/4wETRr7C
[debug] Command-line config: ['-Uv', 'https://crowdbunker.com/v/4wETRr7C']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.01.21 [f20d607] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] exe versions: none
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.01.21, Current version: 2022.01.21
yt-dlp is up to date (2022.01.21)
[debug] [CrowdBunker] Extracting URL: https://crowdbunker.com/v/4wETRr7C
[CrowdBunker] 4wETRr7C: Downloading JSON metadata
[CrowdBunker] 4wETRr7C: Downloading MPD manifest
[CrowdBunker] 4wETRr7C: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: best/bestvideo+bestaudio
[info] 4wETRr7C: Downloading 1 format(s): 9
[debug] Invoking downloader on "https://d.video-cdn.divulg.org/cb-medias4/videos/01FS9MANFHCX6GH05FVD8VAT59/</Representation>"
[hlsnative] Downloading m3u8 manifest
ERROR: unable to download video data: HTTP Error 404: Not Found
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 3054, in process_info
  File "yt_dlp\YoutubeDL.py", line 2769, in dl
  File "yt_dlp\downloader\common.py", line 440, in download
  File "yt_dlp\downloader\hls.py", line 68, in real_download
  File "yt_dlp\YoutubeDL.py", line 3526, in urlopen
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found
```
