### ISSUE TITLE
Redirect yt-dlp output to VLC or MPV

### ISSUE THREAD

**Issue by 99bobster99** [yt-dlp/yt-dlp#236]
I tried running this command, from within a cmd prompt (using the latest yt-dlp x64 v2021.04.03 and aria2c x64 v1.35.0);

`ytdlp --external-downloader aria2c --external-downloader-args "-j 8 -x 8 -s 8" "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4" -o - | mpv -`

The above command creates a file named ` - `.

If I run this command, from within a cmd prompt;

`yt-dlp "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4" -o - | mpv -`

The above command runs as expected, and opens MPV player and redirects the video output to the MPV console.

I'm assuming that the redirecting of a multiple connection download is is not possible. But even when `-j 1 -x 1` is selected as the arguments, the video is not redirected to MPV, and a file named ` - ` is created.

I find the same results when using the latest youtube-dl with aria2c.

Could the ability to redirect yt-dlp's output to a pipe, when using aria2c, be added?

**Comment by pukkandan** [comment]
I dont think `aria2c` supports downloading file to console. In that case, it is not possible

**Comment by pukkandan** [comment]
Confirmed to be not possible: https://github.com/aria2/aria2/issues/190
