### ISSUE TITLE
[DiscoveryPlus] 404 error when downloading JSON metadata

### ISSUE THREAD

**Issue by gergles** [yt-dlp/yt-dlp#2361]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2021.12.27**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

USA

### Description

Trying to download video from Discovery+ fails with a fake 404 generated by the server when retrieving the JSON. Below this is the log with valid cookies.

(--no-geo-bypass is required to avoid another a different case where D+ sends a fake 404 if the request is made from within the USA, see #1623.)

The ID number for this video is 4274095, but I couldn't figure out a way to try bypassing the part of the extractor that converted URL into ID to just try downloading the file.

Here is the log with no cookies, which shows the JSON file does exist:
```
[debug] Command-line config: ['-Uv', '--no-geo-bypass', 'https://www.discoveryplus.com/video/90-day-the-single-life/the-ship-has-sailed']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2021.12.27 [6223f67] (mac_exe)
[debug] Python version 3.8.9 (CPython 64bit) - macOS-11.6.2-arm64-arm-64bit
[debug] exe versions: none
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2021.12.27, Current version: 2021.12.27
yt-dlp is up to date (2021.12.27)
[debug] [DiscoveryPlus] Extracting URL: https://www.discoveryplus.com/video/90-day-the-single-life/the-ship-has-sailed
[DiscoveryPlus] 90-day-the-single-life/the-ship-has-sailed: Downloading JSON metadata
ERROR: [DiscoveryPlus] 90-day-the-single-life/the-ship-has-sailed: This video is only available for registered users. You may want to use --cookies.
  File "yt_dlp/extractor/common.py", line 599, in extract
  File "yt_dlp/extractor/dplay.py", line 396, in _real_extract
  File "yt_dlp/extractor/dplay.py", line 92, in _get_disco_api_info
  File "yt_dlp/extractor/dplay.py", line 50, in _process_errors
```

### Verbose log

```
[debug] Command-line config: ['-Uv', '--cookies-from-browser', 'brave', '--no-geo-bypass', 'https://www.discoveryplus.com/video/90-day-the-single-life/the-ship-has-sailed']
[Cookies] Extracting cookies from brave
[debug] Extracting cookies from: "/Users/X/Library/Application Support/BraveSoftware/Brave-Browser/Default/Cookies"
[debug] using find-generic-password to obtain password from OSX keychain
[Cookies] Extracted 389 cookies from brave
[debug] cookie version breakdown: {'v10': 385, 'other': 0, 'unencrypted': 4}
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2021.12.27 [6223f67] (mac_exe)
[debug] Python version 3.8.9 (CPython 64bit) - macOS-11.6.2-arm64-arm-64bit
[debug] exe versions: none
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2021.12.27, Current version: 2021.12.27
yt-dlp is up to date (2021.12.27)
[debug] [DiscoveryPlus] Extracting URL: https://www.discoveryplus.com/video/90-day-the-single-life/the-ship-has-sailed
[DiscoveryPlus] 90-day-the-single-life/the-ship-has-sailed: Downloading JSON metadata
ERROR: [DiscoveryPlus] 90-day-the-single-life/the-ship-has-sailed: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output. (caused by <HTTPError 404: 'Not Found'>); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
  File "yt_dlp/extractor/common.py", line 717, in _request_webpage
  File "yt_dlp/YoutubeDL.py", line 3458, in urlopen
  File "urllib/request.py", line 531, in open
  File "urllib/request.py", line 640, in http_response
  File "urllib/request.py", line 569, in error
  File "urllib/request.py", line 502, in _call_chain
  File "urllib/request.py", line 649, in http_error_default
```

**Comment by Naesstrom** [comment]
Looks to be the same problem that I'm having from the swedish Discoveryplus
```
C:\misc apps>yt-dlp --verbose --cookies I:\Downloads\discoveryplus.com_cookies.txt https://www.discoveryplus.com/se/video/90-day-fiance-the-other-way/all-in-the-name-of-love
[debug] Command-line config: ['--verbose', '--cookies', 'I:\\Downloads\\discoveryplus.com_cookies.txt', 'https://www.discoveryplus.com/se/video/90-day-fiance-the-other-way/all-in-the-name-of-love']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2021.12.27 [6223f67] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] exe versions: ffmpeg git-2019-12-06-b66a800, ffprobe git-2019-12-06-b66a800
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [DiscoveryPlus] Extracting URL: https://www.discoveryplus.com/se/video/90-day-fiance-the-other-way/all-in-the-name-of-love
[debug] Using fake IP 6.19.186.172 (US) as X-Forwarded-For
[DiscoveryPlus] 90-day-fiance-the-other-way/all-in-the-name-of-love: Downloading JSON metadata
ERROR: [DiscoveryPlus] 90-day-fiance-the-other-way/all-in-the-name-of-love: This video is only available for registered users. You may want to use --cookies.
  File "yt_dlp\extractor\common.py", line 599, in extract
  File "yt_dlp\extractor\dplay.py", line 396, in _real_extract
  File "yt_dlp\extractor\dplay.py", line 92, in _get_disco_api_info
  File "yt_dlp\extractor\dplay.py", line 50, in _process_errors
```

**Comment by pazau** [comment]
Having the same issue in Denmark from the danish Discovery+.

**Comment by LordFransie** [comment]
I am getting the same issue.

**Comment by DrMxrcy** [comment]
Still Having this Issue. Any Clue?

**Comment by Martin9833** [comment]
Having the same problem with Norwegian Discoveryplus
(This video is only available for registered users. You may want to use --cookies.
and extracted cookies from my browser)

**Comment by JonasR** [comment]
After applying the fix from #4905 the cookiesfile appears to work, but now I get the issue reported here on Germany Discovery+

**Comment by gamer191** [comment]
For those in (presumably) Norway: https://github.com/yt-dlp/yt-dlp/issues/2138#issuecomment-1546623404. Note the comment under the patch.

For those in the UK, see above, but replace `no` with `uk` in the 2nd last line

For those in other countries, see Norway above, but change the 2nd last line to your country's code (https://en.wikipedia.org/wiki/ISO_3166-1). If it works, let us know!

If it doesn't work, perhaps try replacing "eu", in the 4th last line, with your continent's code (I dunno if there's a standard for that, so you might need to guess it). Let us know if this works!

If none of the above work, use your browser's dev tools to find proper replacements for both the second and fourth last lines (and, once again, please let us know once you find them)

**Comment by gamer191** [comment]
PS for those in the US, I guess just ignore the `_DISCO_API_PARAMS` changes altogether?

**Comment by dirkf** [comment]
The dplay module includes a lot of extractor classes, of which some may now be obsolete as Discovery has consolidated into DiscoveryPlus. 
* direct subclasses of `DPlayBaseIE`: UK (aka GB) URLs all redirect to discovery.com/gb; if that's true for DE too, `DiscoveryNetworksDeIE` is obsolete; the same may apply for the original dk|es|fi|it|jp|no|se `DPlayBaseIE` extractor
* as a result, new subclasses of `DiscoveryPlusBaseIE` are needed to cover those countries, or the `DiscoveryPlusIE` extractor logic needs to be reworked
* a lot of US-based topic channels need to be verified, but require a subscription.

Problems for anyone trying to overhaul the dplay module:
1. similar to South Park, DiscoveryPlus aggressively redirects user-facing URLs to what it thinks appropriate to the user's region: so discoveryplus.de -> discoveryplus.com/gb for a user in the UK
2. some sub-sites may have only subscription material
3. maybe everything will change again with the HBO/Warner Discovery merger and the new combined Max streaming service (even if initially ["Discovery Plus will remain a separate service"](https://www.businessinsider.com/guides/streaming/max-streaming-service?r=US&IR=T)).

Currently from the UK (see 1 above), these parameters look (see 2 above) like they would work with a `DiscoveryPlusGBIE` similar to the one for IT:
```py
    _PRODUCT = 'dplus_gb'
    _DISCO_API_PARAMS = {
        'disco_host': 'eu1-prod-direct.discoveryplus.com',
        'realm': 'dplay',
        'country': 'gb',
    }
```
`DiscoveryPlusIndiaIE` passes its test from UK with the current parameters. `DiscoveryPlusItalyIE` passes this test case (based on an existing `only_matching` test):
```py
        'url': 'https://www.discoveryplus.com/it/video/super-benny/trailer',
        'info_dict': {
            'id': '2440530',
            'ext': 'mp4',
            'title': 'Trailer',
            'description': 'In arrivo a giugno - Scopri la sigla di Super Benny!',
            'timestamp': 1653030000,
            'upload_date': '20220520',
        },
```

**Comment by JonasR** [comment]
If it helps the discussion, in Germany I tried with [this](https://www.discoveryplus.com/de/video/sport/eurosport-1-germany-eurosport-1-germany-sport/weltcup-jakarta-4663856) video and see the following headers
```
x-disco-client: WEB:UNKNOWN:dplus_us:27.42.0
x-disco-params: realm=dplay,siteLookupKey=dplus_de,bid=dplus,hn=www.discoveryplus.com,hth=de
```
The host appears to be `eu1-prod-direct.go.discovery.com`

I tried the patch from above, changed the country to `de` and also tried changing the product to `dplus_us` (as well as `dplus_de`) in both `DiscoveryPlusBaseIE._update_disco_api_headers` as well as `GoDiscoveryIE` but nothing has worked so far.

**Comment by dirkf** [comment]
The URL https://www.discoveryplus.com/de/video/sport/eurosport-1-germany-eurosport-1-germany-sport/weltcup-jakarta-4663856 is unlike the currently supported DiscoveryPlus URLs in that it has `/video/sport/...` rather than `/video/...`. A test indicates that the slug to be used for looking up the video is just `eurosport-1-germany-eurosport-1-germany-sport/weltcup-jakarta-4663856`, as prepending `sport/` returns error `not.found - no resource for path`. Possibly `sport` and any other special video category words should be added to other URL patterns for DiscoveryPlus extractors.

This extractor code finds the resource and wants your subscription:
```py
class DiscoveryPlusDeIE(DiscoveryPlusBaseIE):
    _VALID_URL = r'https?://(?:www\.)?discoveryplus\.com/de/video(?:/sport)?' + DPlayBaseIE._PATH_REGEX

    _PRODUCT = 'dplus_de'
    _DISCO_API_PARAMS = {
        'disco_host': 'eu1-prod-direct.discoveryplus.com',
        'realm': 'dplay',
        'country': 'de',
    }
```
`de` has to be excluded, like `it`, from the 2-letter codes accepted in `DiscoveryPlusIE._VALID_URL`, and this change also has to be made in the base extractor (I used client version 27.42 but [27.38 also works](https://github.com/yt-dlp/yt-dlp/issues/2138#issuecomment-1546623404)):
```diff 
 
 class DiscoveryPlusBaseIE(DPlayBaseIE):
+    _DISCO_CLIENT_VER = '27.42.0'
+
     def _update_disco_api_headers(self, headers, disco_base, display_id, realm):
-        headers['x-disco-client'] = f'WEB:UNKNOWN:{self._PRODUCT}:25.2.6'
+        # https://github.com/yt-dlp/yt-dlp/issues/2138#issuecomment-1546623404
+        headers.update({
+            'x-disco-params': f'realm={realm}',
+            'x-disco-client': f'WEB:UNKNOWN:{self._PRODUCT}:{self._DISCO_CLIENT_VER}',
+            'Authorization': self._get_auth(disco_base, display_id, realm),
+        })
 
     def _download_video_playback_info(self, disco_base, video_id, headers):
         return self._download_json(
```

**Comment by bashonly** [comment]
Could anyone with an account give this PR a try?

- #10471

I've created pre-release builds for testing purposes:

```
yt-dlp --update-to bashonly/yt-dlp@dplay
```

If it works, please comment and include your country (US, GB or DE)

If it doesn't work, please comment and include a verbose log (add `-v` to your command)
