### ISSUE TITLE
Tele5 (not a duplicate of issue 2303)

### ISSUE THREAD

**Issue by github-bugsubmit** [yt-dlp/yt-dlp#2364]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2021.12.27**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Germany

### Description

Tele 5 video download fails (worked until day before yesterday).

Site unterwent complete rebuild a week and half ago, breaking until-then method of download, but video download still **generally** worked, you only needed to go to the detail page for a movie/series rather than the overview page. Also, you could no longer download several episodes of a series in one go.

**Now:** Does not work at all any longer, no matter what.

### Verbose log

```shell
[debug] Command-line config: ['--verbose', 'https://tele5.de/mediathek/fargo/die-schmutzige-strae/']
[debug] User config file: C:\Users\...\AppData\Roaming\yt-dlp\config.txt
[debug] User config: ['--compat-options', 'all', '--yes-playlist', '--fragment-retries', '100', '--no-check-certificate', '--buffer-size', '512M', '-c', '-N', '48', '--prefer-insecure', '--write-sub', '--sub-lang', 'en_US,ko_KR,en_GB,en,ko', '--embed-subs']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8 (No ANSI), err cp1252 (No ANSI), pref cp1252
[debug] yt-dlp version 2021.12.27 [6223f67] (win_exe)
[debug] Compatibility options: list-formats, no-keep-subs, seperate-video-versions, no-live-chat, no-clean-infojson, format-sort, no-youtube-channel-redirect, playlist-index, embed-metadata, no-playlist-metafiles, multistreams, format-spec, no-attach-info-json, filename, no-direct-merge, abort-on-error, embed-thumbnail-atomicparsley, no-youtube-unavailable-videos
[debug] Python version 3.8.10 (CPython 64bit) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg 2021-08-04-git-3b298640e1-full_build-www.gyan.dev (setts), ffprobe 2021-08-04-git-3b298640e1-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] Using fake IP 53.101.238.32 (DE) as X-Forwarded-For
[debug] [Tele5] Extracting URL: https://tele5.de/mediathek/fargo/die-schmutzige-strae/
ERROR: [Tele5] die-schmutzige-strae: Unable to extract jwplatform id; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
  File "yt_dlp\extractor\common.py", line 599, in extract
  File "yt_dlp\extractor\tele5.py", line 102, in _real_extract
  File "yt_dlp\extractor\tele5.py", line 91, in extract_id
  File "yt_dlp\extractor\common.py", line 1182, in _html_search_regex
  File "yt_dlp\extractor\common.py", line 1173, in _search_regex
```

**Comment by pukkandan** [comment]
Looks like #2303 to me. You didnt explain why you think it is not

**Comment by dirkf** [comment]
With my [yt-dl patch](https://github.com/yt-dlp/yt-dlp/issues/2303#issuecomment-1013682049), this page gives the `Missing deviceId in context` error, so that may be the difference.

**Comment by pukkandan** [comment]
Can someone who has access to this video on browser confirm whether or not it is DRM? From what we discussed in the other issues, that error happens in case of DRM

**Comment by nyuszika7h** [comment]
Yeah, the linked video is using Widevine DRM.

![Screenshot](https://user-images.githubusercontent.com/482367/149758517-766ca873-ca67-4454-b6d0-65104d137b92.png)
