### ISSUE TITLE
Code checker flagged line in error

### ISSUE THREAD

**Issue by fbacher** [yt-dlp/yt-dlp#2368]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2021.12.27**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

Static code checker for Kodi flagged a line as an ERROR:

extractor/common.py line 3472:

  def _int(self, v, name, fatal=False, **kwargs):
        res = int_or_none(v, **kwargs)
        if 'get_attr' in kwargs:
            **print(getattr(v, kwargs['get_attr']))**
        if res is None:
            msg = 'Failed to extract %s: Could not parse value %r' % (name, v)
   
Bold line should be: **print((getattr(v, kwargs['get_attr'])))**
The extra parenthesis is apparently meant to ensure that whatever is returned by gettattr is contained in a tuple for *argv. I could submit a PR, but just in case I'm misunderstanding the issue I'd like another opinion first.

### Verbose log

```shell
(code checker output):
ERROR: ./script.module.youtube.dl/resources/code/lib/yt_dlp/extractor/common.py
--- ./script.module.youtube.dl/resources/code/lib/yt_dlp/extractor/common.py	(original)
+++ ./script.module.youtube.dl/resources/code/lib/yt_dlp/extractor/common.py	(refactored)
@@ -3469,7 +3469,7 @@
     def _int(self, v, name, fatal=False, **kwargs):
         res = int_or_none(v, **kwargs)
         if 'get_attr' in kwargs:
-            print(getattr(v, kwargs['get_attr']))
+            print((getattr(v, kwargs['get_attr'])))
         if res is None:
             msg = 'Failed to extract %s: Could not parse value %r' % (name, v)
             if fatal:
ERROR: ParseError: bad input: type=1, value='exec', context=('', (7, 6))
```

**Comment by nyuszika7h** [comment]
I don't understand. `(x)` is not a tuple. To make a single-element tuple, you must do `(x,)`.

**Comment by pukkandan** [comment]
There is no error here. But, that print statement should never have existed either. The code has been like that since b14f3a4c1da00cbee8775904c24c4d0547018ae0 and no one ever noticed, lol! I didnt even know `_int` and `_float` functions existed 😐
