### ISSUE TITLE
Support for southpark.lat

### ISSUE THREAD

**Issue by Mora2403** [yt-dlp/yt-dlp#2369]
### Checklist

- [X] I'm reporting a feature request
- [X] I've verified that I'm running yt-dlp version **2021.12.27**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

Asking for support on https://www.southpark.lat/
Episode 1 for test: https://www.southpark.lat/episodios/940f8z/south-park-cartman-consigue-una-sonda-anal-temporada-1-ep-1

Site is geo restricted

**Comment by Ashish0804** [comment]
This is not a feature request.
We have request category specific templates for a reason
