### ISSUE TITLE
“yt-dlp_macos” can’t be opened because Apple cannot check it for malicious software.

### ISSUE THREAD

**Issue by ridoy** [yt-dlp/yt-dlp#2374]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2021.12.27**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

macOS Monterey 12.1

To reproduce:
After installing the mac standalone, from terminal do:
`sudo chmod a+rx`
`./yt-dlp_macos {youtube url}`

I saw https://github.com/yt-dlp/yt-dlp/issues/25 but it didn't seem related.

Can't verify that I'm using 2021.12.27 (won't run), but the executable I'm using was downloaded today from the link in the readme.

### Verbose log

```shell
“yt-dlp_macos” can’t be opened because Apple cannot check it for malicious software.
```

**Comment by ridoy** [comment]
This was silly, I had to allow it from Security & Privacy preferences. Just updated to Monterey today. Works now. Closing.

**Comment by Strong-Foundation** [comment]
![Image](https://github.com/user-attachments/assets/e3030f2e-a3aa-44a8-b63f-08718b47e805)
