### ISSUE TITLE
[ok.ru] Downloaded video is broken

### ISSUE THREAD

**Issue by dizimax** [yt-dlp/yt-dlp#2376]
### Checklist

- [x] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2021.12.27**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

I have a HLS stream system and i used yt-dlp for import ok.ru videos. The video is downloaded and saved no problems so far. However, after downloading the video and converting it to HLS i saw that the parts were corrupt. Then i noticed the same problem when I play it with the media player. 
Problem photo;
![Screenshot_4](https://user-images.githubusercontent.com/80402580/149910156-dce5656e-bdff-4775-a947-4ddcb930b9a1.png)

There was no such problem a few days ago. There is no problem in the video on ok.ru.
Same problem have on youtube-dl.

### Verbose log

```shell
[debug] Command-line config: ['-Uv', 'https://ok.ru/video/3567708670511']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2021.12.27 [6223f67] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.14393-SP0
[debug] exe versions: none
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2021.12.27, Current version: 2021.12.27
yt-dlp is up to date (2021.12.27)
[debug] [Odnoklassniki] Extracting URL: https://ok.ru/video/3567708670511
[Odnoklassniki] 3567708670511: Downloading desktop webpage
[Odnoklassniki] 3567708670511: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: best/bestvideo+bestaudio
[info] 3567708670511: Downloading 1 format(s): mpd-5
[debug] Invoking downloader on "https://vd161.mycdn.me/?expires=1642585058087&srcIp=78.47.225.91&pr=10&srcAg=CHROME&ms=45.136.21.8&type=5&sig=FZ0bJoBGij8&ct=4&urls=185.226.53.29&clientType=0&id=2223686617647"
[download] TheBlacklist908.tr [3567708670511].mp4 has already been downloaded
[download] 100% of 1.57GiB
```

**Comment by pukkandan** [comment]
Is it a one time thing, or is it reproducible? 

> [download] TheBlacklist908.tr [3567708670511].mp4 has already been downloaded

Provide verbose log of the actual run that downloaded the video

Also, seems it's geo-blocked? What country are u access it from? (This is why u should use the correct template!)
