### ISSUE TITLE
[Question] MPD Live Stream Only Downloads Segments Available And Then Quits

### ISSUE THREAD

**Issue by Dazzler1985** [yt-dlp/yt-dlp#238]
When i want to record a dash live stream it only downloads what available at the time and then quits .
How do i get it when a new segment is available it downloads . And sometimes there is dvr function in the mpd and downloads like 2 hours in the past first how can you skip that and purely record the new segments during livestream ?

**Comment by pukkandan** [comment]
Not currently possible. There is already a feature request for this: https://github.com/yt-dlp/yt-dlp/issues/159
