### ISSUE TITLE
README.md: how to read the `Not recommended` table?

### ISSUE THREAD

**Issue by schittli** [yt-dlp/yt-dlp#2381]
### Question

Hello
**Thank you very much for sharing your great work!**

#### I have a small question: 
[README.md](https://github.com/yt-dlp/yt-dlp#readme) has the section **_Not recommended_**:

> Not recommended
> While these options still work, their use is not recommended since there are other alternatives to achieve the same

And just below, there is this table, unfortunately, it has no column headings:

```
--exec-before-download CMD       --exec "before_dl:CMD"
--no-exec-before-download        --no-exec
--all-formats                    -f all
--all-subs                       --sub-langs all --write-subs
--print-json                     -j --no-simulate
…                                …
```

#### How should we understand this table?

Are the non-recommended options in the left column 
and the new notation in the right column?

Or should these functions no longer be used at all?

Many thanks for any light in this puzzle 😃 

Thanks a lot, kind regards,
Thomas

**Comment by pukkandan** [comment]
> Are the non-recommended options in the left column
> and the new notation in the right column?

Yes.

The `#deprecated options` description says:

    These are all the deprecated options and the current alternative to achieve the same effect
