### ISSUE TITLE
yt-dlp reports "Malformed storyboard" when attempting to download a YT URL

### ISSUE THREAD

**Issue by BozRetro** [yt-dlp/yt-dlp#2382]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2021.12.27**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

I attempted to download the URL https://www.youtube.com/watch?v=A_fMN9kFm14. yt-dlp responded with the following:

[youtube] A_fMN9kFm14: Downloading webpage
[youtube] A_fMN9kFm14: Downloading android player API JSON
WARNING: [youtube] Malformed storyboard 0: 72#54#100#10#10#0#storyboard_high; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
ERROR: unknown url type: '/sb/A_fMN9kFm14/storyboard_low.jpg&sigh='

### Verbose log

```shell
[debug] Command-line config: ['https://www.youtube.com/watch?v=A_fMN9kFm14', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2021.12.27 [6223f67a8] (zip)
[debug] Python version 3.8.10 (CPython 64bit) - Linux-5.4.72-microsoft-standard-WSL2-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4, rtmpdump 2.4
[debug] Optional libraries: secretstorage, sqlite
[debug] Proxy map: {}
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=A_fMN9kFm14
[youtube] A_fMN9kFm14: Downloading webpage
[youtube] A_fMN9kFm14: Downloading android player API JSON
WARNING: [youtube] Malformed storyboard 0: 72#54#100#10#10#0#storyboard_high; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
ERROR: unknown url type: '/sb/A_fMN9kFm14/storyboard_low.jpg&sigh='
Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1353, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1437, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1489, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 2446, in process_video_result
    format['http_headers'] = self._calc_headers(full_format_info)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 2203, in _calc_headers
    cookies = self._calc_cookies(info_dict)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 2215, in _calc_cookies
    pr = sanitized_Request(info_dict['url'])
  File "/usr/local/bin/yt-dlp/yt_dlp/utils.py", line 687, in sanitized_Request
    return compat_urllib_request.Request(url, *args, **kwargs)
  File "/usr/lib/python3.8/urllib/request.py", line 328, in __init__
    self.full_url = url
  File "/usr/lib/python3.8/urllib/request.py", line 354, in full_url
    self._parse()
  File "/usr/lib/python3.8/urllib/request.py", line 383, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: '/sb/A_fMN9kFm14/storyboard_low.jpg&sigh='
```

**Comment by coletdjnz** [comment]
Looks like a bug YouTube's side - the storyboard appears to be broken on YouTube as well. However, this should not be fatal in yt-dlp.

---
technical observations for devs:
In this case the `base_url` extracted appears to be a relative url. There is no `sigh=` param. 

On YouTube, it adds `www.youtube.com` which gives  `https://www.youtube.com/sb/A_fMN9kFm14/storyboard_low.jpg`. This doesn't work and returns a channel page (HTML) :laughing:
