### ISSUE TITLE
support for wetv.vip

### ISSUE THREAD

**Issue by takedowndmca** [yt-dlp/yt-dlp#2383]
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2021.12.27**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Indonesia

### Example URLs

https://wetv.vip/play/2c0wm22ushpeqaa-Tersanjung-The-Series/y0041z7uzmr-EP01A-Tersanjung-The-Series

### Description

please add support site wetv.vip

### Verbose log

```shell
[debug] Command-line config: ['-Uv', 'https://wetv.vip/play/2c0wm22ushpeqaa-Tersanjung-The-Series/y0041z7uzmr-EP01A-Tersanjung-The-Series']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2021.12.27 [6223f67a8]
[debug] Python version 3.8.12 (CPython 64bit) - Linux-5.11.0-1026-gcp-x86_64-with-glibc2.27
[debug] exe versions: ffmpeg 3.4.8, ffprobe 3.4.8
[debug] Optional libraries: Cryptodome, secretstorage, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2021.12.27, Current version: 2021.12.27
yt-dlp is up to date (2021.12.27)
[debug] [generic] Extracting URL: https://wetv.vip/play/2c0wm22ushpeqaa-Tersanjung-The-Series/y0041z7uzmr-EP01A-Tersanjung-The-Series
[generic] y0041z7uzmr-EP01A-Tersanjung-The-Series: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] y0041z7uzmr-EP01A-Tersanjung-The-Series: Downloading webpage
[generic] y0041z7uzmr-EP01A-Tersanjung-The-Series: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://wetv.vip/play/2c0wm22ushpeqaa-Tersanjung-The-Series/y0041z7uzmr-EP01A-Tersanjung-The-Series
Traceback (most recent call last):
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 1353, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 1423, in __extract_info
    ie_result = ie.extract(url)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/yt_dlp/extractor/common.py", line 599, in extract
    ie_result = self._real_extract(url)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/yt_dlp/extractor/generic.py", line 3829, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://wetv.vip/play/2c0wm22ushpeqaa-Tersanjung-The-Series/y0041z7uzmr-EP01A-Tersanjung-The-Series
```

**Comment by Sipherdrakon** [comment]
I was looking at the link provided and it seems to be fairplay drm-protected content. I'm not saying there isn't a non-drm version of it that I'm just not seeing. But what I looked at showed fairplay-drm. :-(

**Comment by shane-tw** [comment]
duplicate https://github.com/yt-dlp/yt-dlp/issues/1115
I'd also like this
