### ISSUE TITLE
ITV Hub's 'duration' isn't correctly parsed

### ISSUE THREAD

**Issue by dirkf** [yt-dlp/yt-dlp#2388]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2021.12.27**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

UK

### Description

Example: Vera S04E01 is shown as having approximate file size 44GiB for a 120 minute 2Mbit/s stream, which should be ~ 1.8GiB.

Breaking the extractor with pdb:
```
(Pdb) p video_data.keys()
dict_keys(['Duration', 'Timecodes', 'Base', 'MediaFiles', 'Subtitles', 'Token'])
(Pdb) p video_data['Duration']
'01:29:34:000'
(Pdb) p parse_duration(video_data['Duration'])
192840.0
(Pdb) p parse_duration(video_data['Duration'].replace(':0','.0'))
5374.0
```
Here 5374 is the correct duration, 2 "ITV hours", allowing another 30 minutes for ads.

The problem is that ITV doesn't know about decimal points, which is perhaps fair enough since a lot of the world is confused about them, and `parse_duration()` in `utils.py` does expect one between the seconds and milliseconds.

Either in the extractor or in `utils.py`, the value (`duration_string`) to be parsed should be conditioned as `re.sub(r':(\d{3,})$', r'.\1', duration_string)`.

Disambiguating strings that might have either days or 1-2 digit milliseconds, eg '01:29:34:00' which might be 1 day, 29 hours, ... , or 1 hour, 29 minutes, ..., would need additional, probably unjustified, parsing.

### Verbose log

```shell
$ python3.9 -m yt_dlp -Uv -o '%(duration)s' --get-filename 'https://www.itv.com/hub/vera/1a7314a0015/'
[debug] Command-line config: ['-Uv', '-o', '%(duration)s', '--get-filename', 'https://www.itv.com/hub/vera/1a7314a0015/']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2021.12.27 [6223f67a8] (source)
[debug] Lazy loading extractors is disabled
[debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
[debug] Git HEAD: f5c2c2c9b
[debug] Python version 3.9.7 (CPython 32bit) - Linux-4.4.0-210-generic-i686-with-glibc2.23
[debug] exe versions: avconv 4.3, avprobe 4.3, ffmpeg 4.3, ffprobe 4.3
[debug] Optional libraries: sqlite
[debug] Proxy map: {}
Latest version: 2021.12.27, Current version: 2021.12.27
yt-dlp is up to date (2021.12.27)
[debug] Using fake IP 25.111.7.23 (GB) as X-Forwarded-For
[debug] [ITV] Extracting URL: https://www.itv.com/hub/vera/1a7314a0015/
[ITV] 1a7314a0015: Downloading webpage
[ITV] 1a7314a0015: Downloading JSON metadata
[ITV] 1a7314a0015: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 1a7314a0015: Downloading 1 format(s): hls-1908
192840.0
$
```

**Comment by Vangelis66** [comment]
... First reported by me ca. **two months ago**, albeit in an "out-of-place" comment: 

https://github.com/yt-dlp/yt-dlp/issues/1775#issuecomment-978795367 😜 

Thanks to the (proper) issue reporter (**dirkf**) and to the maintainer (**pukkandan**) for finally addressing that (minor) handicap... ❤️
