### ISSUE TITLE
Install yt-dlp dependencies on Windows

### ISSUE THREAD

**Issue by superbonaci** [yt-dlp/yt-dlp#2389]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

I'm downloading `yt-dlp.exe	Windows (Win7 SP1+) standalone x64 binary (recommended for Windows)`, however does it include all the dependencies under section `DEPENDENCIES`? Or it's better to use native Windows python and use `python3 -m pip install -U yt-dlp`? I already have the Windows builds of `mplayer`, `ffmpeg` and `ffprobe` and in my PATH, but I'm talking about the other dependencies (mutagen, pycryptodomex, websockets, secretstorage, AtomicParsley, rtmpdump, phantomjs, sponskrub)

**Comment by pukkandan** [comment]
> mutagen, pycryptodomex, websockets

There are included in the binary

>  secretstorage, AtomicParsley, rtmpdump, phantomjs, sponskrub

ffmpeg, ffprobe is probably all you need. If you ever need the rest, yt-dlp will tell you

**Comment by superbonaci** [comment]
> ffmpeg, ffprobe is probably all you need. If you ever need the rest, yt-dlp will tell you

That's great. I think that's not mentiones in the documentation.

**Comment by pukkandan** [comment]
> While all the other dependencies are optional, `ffmpeg` and `ffprobe` are highly recommended
