### ISSUE TITLE
How to get IDs of all search results from a particular channel?

### ISSUE THREAD

**Issue by Mennaruuk** [yt-dlp/yt-dlp#2390]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

I'm trying to get a list of all YouTube URLs/IDs of videos whose titles match an exact string from a particular channel.

So, for example, say PewDiePie has the LWIAY series. He has plenty of videos where in the title it says LWIAY. I would love to know how I can get a list of all PewDiePie videos where in the title it says LWIAY.

I'm also wondering if it's possible to add custom dates, so I can filter only videos between say January 1, 2018 to January 1, 2019.

Hope I didn't make it too hard to understand. Please let me know if you need any elaboration, and thank you so very much!!!

**Comment by pukkandan** [comment]
Use --match-filter, --match-title, --date and --print as needed. What is the difficulty you ae experiencing?

**Comment by Mennaruuk** [comment]
Nothing really shows up. PewDiePie has thousands of videos, so let's do Vsauce instead. He has a video where the title contains the word _disgust_. I tried to make yt-dlp get the ID of all videos by Vsauce containing in the title the word _disgust_, but I got nothing :(

Here's the command I ran:

`yt-dlp --match-filter "title = disgust"  --print id https://www.youtube.com/channel/UC6nSFpj9HTCZ5t-N3Rm3-HA`

Also, is the URL always required? I thought making a --match-filter specifying the channel name or ID would make the URL superfluous, but unfortunately yt-dlp gave me an error.

Thank you.

**Comment by pukkandan** [comment]
> Also, is the URL always required?

YES

> --match-filter "title = disgust"

You are checking for title = disgust, not contains! Either use --match-title or `*=`

```
➤ yt-dlp --match-filter "title *= disgust" --print id= "https://www.youtube.com/c/vsauce1/videos" --flat-playlist
id = 4ZJWv6t-PfY
id = dacojrlGM7Q
```

**Comment by Mennaruuk** [comment]
Thank you pukkandan. I hope you have a lovely night. Your help is invaluable.
