### ISSUE TITLE
[Youtube] Failed to download member-only video

### ISSUE THREAD

**Issue by kewpiemayo** [yt-dlp/yt-dlp#2392]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

Hello,

I have joined the channel membership program and I try to download member-only video using command
`yt-dlp --cookies cookies.txt --simulate https://www.youtube.com/watch\?v\=video_id`

And it was failed and showing message "Join this channel to get access to members-only content like this video, and other exclusive perks."

Is there any other command that I should try?

### Verbose log

```shell
[debug] Command-line config: ['--cookies', 'cookies.txt', '--simulate', 'https://www.youtube.com/watch?v=video_id', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2021.12.27 [6223f67a8] (zip)
[debug] Python version 3.8.2 (CPython 64bit) - macOS-11.5.2-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=video_id
[youtube] video_id: Downloading webpage
[debug] [youtube] Extracted SAPISID cookie
[youtube] video_id: Downloading android player API JSON
ERROR: [youtube] video_id: Join this channel to get access to members-only content like this video, and other exclusive perks.
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 599, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/youtube.py", line 2921, in _real_extract
    self.raise_no_formats(reason, expected=True)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 1107, in raise_no_formats
    raise ExtractorError(msg, expected=expected, video_id=video_id)
```

**Comment by coletdjnz** [comment]
I feel like this may be an issue with your cookies.

Can you try using `--cookies-from-browser` (e.g. `--cookies-from-browser chrome`) while logged into the account that has access to the videos in such browser?

**Comment by LazyNerdYT** [comment]
im still having the same issue, i think its a bug with with the program

**Comment by WebMechanic** [comment]
did as @coletdjnz suggested and worked for me with "stable@2023.10.13" on Win with Firefox `--cookies-from-browser firefox`

**Comment by saurav2015** [comment]
https://www.youtube.com/watch?v=84mjaW5zr90 anyone please help me to get access of this video?
