### ISSUE TITLE
download speed has been really slow since past few days

### ISSUE THREAD

**Issue by usernamebutexists** [yt-dlp/yt-dlp#2395]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

I'm using the latest windows release version, earlier youtube videos download speed was very good, i was getting speed of round 4-5 MB/s but since past few days i'm getting around 100-200 kbps sometimes in 300's kbps sometimes below 100kbps. I am getting faster speed in youtube-dl, which is weird cuz earlier i was getting lesser speed in youtube-dl and much faster in yt-dlp. I dont know what's the issue if anyone know about this, please let me know how to fix it

**Comment by pukkandan** [comment]
Provide verbose log

**Comment by usernamebutexists** [comment]
> Provide verbose log

C:\Users\abc\Downloads\youtube-dl\yt-dlp>yt-dlp.exe -Uv https://youtu.be/kJHzKdIZ9vQ
[debug] Command-line config: ['-Uv', 'https://youtu.be/kJHzKdIZ9vQ']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2021.12.27 [6223f67] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] exe versions: ffmpeg 2022-01-17-git-dcc9454ab9-full_build-www.gyan.dev (setts), ffprobe 2022-01-17-git-dcc9454ab9-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2021.12.27, Current version: 2021.12.27
yt-dlp is up to date (2021.12.27)
[debug] [youtube] Extracting URL: https://youtu.be/kJHzKdIZ9vQ
[youtube] kJHzKdIZ9vQ: Downloading webpage
[youtube] kJHzKdIZ9vQ: Downloading android player API JSON
[youtube] kJHzKdIZ9vQ: Downloading MPD manifest
[youtube] kJHzKdIZ9vQ: Downloading MPD manifest
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] kJHzKdIZ9vQ: Downloading 1 format(s): 248+251
[debug] Invoking downloader on "https://manifest.googlevideo.com/api/manifest/dash/expire/1642619161/ei/uQzoYZHGDqvF4-EPj_OcwAM/ip/45.127.139.165/id/9091f329d219f6f4/source/youtube/requiressl/yes/playback_host/rr3---sn-bxvoxupo-qxae.googlevideo.com/mh/Eo/mm/31%2C29/mn/sn-bxvoxupo-qxae%2Csn-qxaeenls/ms/au%2Crdu/mv/m/mvi/3/pl/24/tx/24027691/txs/24027691%2C24027692%2C24027693%2C24027694%2C24067852/hfr/all/as/fmp4_audio_clear%2Cwebm_audio_clear%2Cwebm2_audio_clear%2Cfmp4_sd_hd_clear%2Cwebm2_sd_hd_clear/initcwndbps/868750/vprv/1/mt/1642597257/fvip/3/keepalive/yes/fexp/24001373%2C24007246/itag/0/sparams/expire%2Cei%2Cip%2Cid%2Csource%2Crequiressl%2Ctx%2Ctxs%2Chfr%2Cas%2Cvprv%2Citag/sig/AOq0QJ8wRAIgbuwydcV-E0eKasGpj3fKpldmam8fpppqoN7cw85_nnQCIECIEMvDJiy2jMhY7vmv9HnhZ74U_0xB-FLj3TAKi1b9/lsparams/playback_host%2Cmh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps/lsig/AG3C_xAwRAIgCvs8GrIVKAtVSklcsCgnNWLtXWt4hpcwTZ0Rqogq5_0CIBbDgbdN2PZiX6xUk0MamymEEU22gDh4Y0lg_XKrIkZ-"
[dashsegments] Total fragments: 854
[download] Destination: CA Final Classes in English May 22 [kJHzKdIZ9vQ].f248.webm
[download] 100% of 321.22MiB in 02:36
[debug] Invoking downloader on "https://rr3---sn-bxvoxupo-qxae.googlevideo.com/videoplayback?expire=1642619161&ei=uQzoYZKZNZCYvwS864uIAg&ip=45.127.139.165&id=o-AIN4L0x7uHdAvXPu8J4Df1NClFkh0Q_Nbb8-r1M6_oIS&itag=251&source=youtube&requiressl=yes&mh=Eo&mm=31%2C29&mn=sn-bxvoxupo-qxae%2Csn-qxaelnes&ms=au%2Crdu&mv=m&mvi=3&pl=24&initcwndbps=868750&vprv=1&mime=audio%2Fwebm&gir=yes&clen=48921169&otfp=1&dur=4265.041&lmt=1642569563967818&mt=1642597257&fvip=3&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=7211222&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cotfp%2Cdur%2Clmt&sig=AOq0QJ8wRgIhAL3GpWjOgs-KAOcpHAIKugft7k5fSadcaj0kARl3qIX8AiEApA50DqkTdVfk2iM94iJPjFrggiCzUSTRi9KThtvNc6o%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAIon99v04XH5xhsAQg85tnl4XeWnpu3kvA3gsA6uBG45AiEA7FSR6oOOoWpTRhlm0rKqyTATsX0qjrcZvyIAoc53bys%3D"
[download] Destination: CA Final Classes in English May 22 [kJHzKdIZ9vQ].f251.webm
[download] 100% of 46.65MiB in 00:06
[Merger] Merging formats into "CA Final Classes in English May 22 [kJHzKdIZ9vQ].webm"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:CA Final Classes in English May 22 [kJHzKdIZ9vQ].f248.webm" -i "file:CA Final Classes in English May 22 [kJHzKdIZ9vQ].f251.webm" -c copy -map "0:v:0" -map "1:a:0" -movflags "+faststart" "file:CA Final Classes in English May 22 [kJHzKdIZ9vQ].temp.webm"
Deleting original file CA Final Classes in English May 22 [kJHzKdIZ9vQ].f251.webm (pass -k to keep)
Deleting original file CA Final Classes in English May 22 [kJHzKdIZ9vQ].f248.webm (pass -k to keep)




I guess its because its newly uploaded video. As this time when i tried to download the same video which took 18 minutes earlier now took only around 3 minutes. I tried downloading popular videos & its downoading faster. But still youtube dl downloads faster(only the video part though, audio part is still slowly downloaded by youtube-dl). But through that ssyoutube website method it downloaded much faster doesnt matter if its new or unpopular video.

**Comment by pukkandan** [comment]
> [dashsegments] Total fragments: 854

DASH formats download slower than normal downloads. Select a different format, use `-N` or aria2c to get faster speeds. 

> But still youtube dl downloads faster(only the video part though, audio part is still slowly downloaded by youtube-dl).

You are probably downloading a different format with youtube-dl

**Comment by usernamebutexists** [comment]
thank you very much
