### ISSUE TITLE
ADD --mark-watched after x% of video has played

### ISSUE THREAD

**Issue by allanlaal** [yt-dlp/yt-dlp#2398]
### Checklist

- [X] I'm reporting a feature request
- [X] I've verified that I'm running yt-dlp version **2021.12.27**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

currently mark-watched jumps the gun a bit and marks the video watched even if I only played a few seconds of it

this can be solved by adding i.e. ´--mark-watched-after ´, which could accept either a percentage of total video or a human readable time value

**Comment by pukkandan** [comment]
That makes no sense. You don't "watch" videos with yt-dlp!!

--mark-watched runs after the video data is extracted, and this cannot be changes

**Comment by allanlaal** [comment]
I'm using mpv, which uses any youtube-dl variant :)

is it possible to do nothing but mark the video played? this way I can write an mpv extension that does that.
