### ISSUE TITLE
[Feature request] Startup time optimisation

### ISSUE THREAD

**Issue by RJVB** [yt-dlp/yt-dlp#2405]
### Checklist

- [X] I'm reporting a feature request
- [X] I've verified that I'm running yt-dlp version **2021.12.27**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

I would like to see a possibility to cache `yt-dlp`'s extracted code, or an option to install it as a local python script. Or maybe just a succinct explanation how to unpack (unzip) the script and write a launcher/wrapper.

Rationale: unpacking the packed executable takes time, up to 3 seconds on my not-so-young-anymore beater notebook. That may not seem a big deal when you're executing the script "by hand", but the times add up if it's being called repeatedly by a GUI app like `QMPlay2` that makes for a nice YouTube browser.

**Comment by pukkandan** [comment]
https://github.com/yt-dlp/yt-dlp#with-pip

Or you could just download the source code and run `yt-dlp.sh`

**Comment by RJVB** [comment]
On Thursday January 20 2022 05:46:30 pukkandan wrote:
>https://github.com/yt-dlp/yt-dlp#with-pip

This might be an option but won't be trivial to get right when installing into user-writable locations on systems that have multiple python versions installed.

But consider this: applications leveraging yt-dlp now only need to download the executable and launch it from the location where they put it (e.g. an app-specific directory). Periodically they can call it first with `-U` to get the latest version. If written with a middleware like Qt those apps don't depend on 3rd party software for this, other than python itself, not even on pip.

Python apparently has the support built in for unpacking the packed executable; it would be my hunch that no additional components are necessary to let it unpack the files to disk. Maybe there's even a command line option like the one AppImage binaries accept to let them be unpacked to disk.

My idea for the applications in question would be that they could use the extraction option after the initial install and each upgrade and use a self-provided wrapper to launch the extracted code. Or - how complicated would it be to do a `pip install --user` like install from with yt-dlp, installing to the user location of the python instance being used, and putting the loader script in the same directory from where yt-dlp was launched?

**Comment by pukkandan** [comment]
So this?
![image](https://user-images.githubusercontent.com/6623388/150366251-dc1eec89-adc7-4f21-a718-1a0629e92604.png)

https://github.com/yt-dlp/yt-dlp#alternatives

**Comment by pukkandan** [comment]
> Maybe a direct, explicit question: is there a command line argument that one can pass to `yt-dlp` so that the `yt_dlp` directory gets unpacked next to the `yt-dlp` binary?

No
