### ISSUE TITLE
set output to stdout still check if file exist ...

### ISSUE THREAD

**Issue by tsukasagenesis** [yt-dlp/yt-dlp#2406]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2021.12.27**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

The bug is simple, is you set -o - for output to stdout (as written on doc https://github.com/yt-dlp/yt-dlp#output-template), if there is a file -.mp4 you get this error
[download] -.mp4 has already been downloaded

since output is stdout, all check if file exist should be disabled.

### Verbose log

```shell
[download] -.mp4 has already been downloaded
```

**Comment by pukkandan** [comment]
The verbose log field is not for show!

**Comment by pukkandan** [comment]
```
➤ type -.mkv
x

➤ yt-dlp test:youtube -o - --merge mkv >nul
[TestURL] Test URL: https://www.youtube.com/watch?v=BaW_jenozKc&t=1s&end=9
[youtube] BaW_jenozKc: Downloading webpage
[youtube] BaW_jenozKc: Downloading android player API JSON
[info] BaW_jenozKc: Downloading 1 format(s): 22
[download] Destination: -
[download] 100% of 1.74MiB in 00:00
```
