### ISSUE TITLE
add --direct-merger or -P merger:dir

### ISSUE THREAD

**Issue by bann0** [yt-dlp/yt-dlp#2410]
### Checklist

- [X] I'm reporting a feature request
- [X] I've verified that I'm running yt-dlp version **2021.12.27**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

I usually use -P temp: ramdrivepath along with -f bv+ba.
In this case "Merger" first writes to the temp path and then moves to the destination directory (-o or -P home:).
If the temporary folder and the destination folder are on different devices, an unnecessary double write occurs.
I would like a "Merger" option to write directly to the destination directory to speed things up, half ram usage or avoid ssd worn.
I use shell script to work around.

**Comment by pukkandan** [comment]
Not possible. The point of `temp:` path is that the file is moved out of it only after ALL postprocessing is complete. And merger is not necessarily the last PP step
