### ISSUE TITLE
Free Unlocked Videos on Discovery.com does not download in Youtube DLP anymore

### ISSUE THREAD

**Issue by magnum32** [yt-dlp/yt-dlp#2413]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2021.12.27**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United States

### Description

ever since Discovery.com whitched to their new go format app thingy on their website, the unlocked videos no longer download in Youtube DL/Youtube DLP. Here is an example: https://go.discovery.com/video/chopped-volume-3-food-network-atve-us/lighten-up

### Verbose log

```shell
yt-dlp --newline -i --hls-prefer-native --write-description --write-info-json --write-annotations --cookies E:/Tartube2/cookies.txt --write-thumbnail -f bestvideo[height<=?720]+bestaudio/best[height<=?720] --output E:/Tartube2/%(title)s.%(ext)s https://go.discovery.com/video/chopped-volume-3-food-network-atve-us/lighten-up
[generic] lighten-up: Requesting header
[generic] lighten-up: Downloading webpage
[generic] lighten-up: Extracting information
WARNING: [generic] Falling back on generic information extractor.
ERROR: Unsupported URL: https://go.discovery.com/video/chopped-volume-3-food-network-atve-us/lighten-up
```

**Comment by pukkandan** [comment]
Closing in favor of #2438
