### ISSUE TITLE
[Site request] Paravi

### ISSUE THREAD

**Issue by BLSTR13** [yt-dlp/yt-dlp#2427]
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.01.21**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Japan

### Example URLs

https://www.paravi.jp/watch/20313
https://www.paravi.jp/title/20314

### Description

Idk if paravi is drm i think it is but im not sure so I hope you can do something about this 

### Verbose log

```shell
[debug] Command-line config: ['-vU', 'https://www.paravi.jp/watch/20313']
[debug] User config "C:\Users\Cherri Estudillo\AppData\Roaming\yt-dlp\config.txt": ['-o', 'D:/ytdl/%(title)s.%(ext)s', '--no-mtime']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.01.21 [f20d607] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] exe versions: ffmpeg 2021-10-28-git-e84c83ef98-essentials_build-www.gyan.dev (setts), ffprobe 2021-10-28-git-e84c83ef98-essentials_build-www.gyan.dev
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.01.21, Current version: 2022.01.21
yt-dlp is up to date (2022.01.21)
[debug] [generic] Extracting URL: https://www.paravi.jp/watch/20313
[generic] 20313: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] 20313: Downloading webpage
[generic] 20313: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://www.paravi.jp/watch/20313
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1367, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1437, in __extract_info
  File "yt_dlp\extractor\common.py", line 612, in extract
  File "yt_dlp\extractor\generic.py", line 3966, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.paravi.jp/watch/20313
```

**Comment by BLSTR13** [comment]
@pukkandan where can I contact you?

**Comment by BLSTR13** [comment]
cuthbertjehogonzales13@gmail.com
firelord13

my account has no subscription plan but there some free to watch on paravi

**Comment by MinePlayersPE** [comment]
@BLSTR13 you'll need to delete the edit revisions to remove your login details properly
<img width="632" alt="image" src="https://user-images.githubusercontent.com/20515340/150655361-a4a51d31-3c96-4f39-b9f8-4f45eb907625.png">

**Comment by BLSTR13** [comment]
oh thanks, done

**Comment by garret1317** [comment]
paravi is no more

**Comment by bashonly** [comment]
can confirm https://en.wikipedia.org/wiki/Paravi

> On February 17, 2023, U-Next announced its merger with Premium Platform Japan, which operates the subscription video streaming service Paravi with 0.85 million subscribers and is owned by [TBS Television](https://en.wikipedia.org/wiki/TBS_Television_(Japan)) and [TV Tokyo](https://en.wikipedia.org/wiki/TV_Tokyo). The merger will take effect on March 31, **with U-Next being the surviving company.**

> Paravi was scheduled to transfer its service to U-Next by July and its content can be viewed on U-Next's monthly plan thereafter

> **On June 30, the integration of Paravi into U-Next was completed.**
