### ISSUE TITLE
URplay.se

### ISSUE THREAD

**Issue by Tygry1** [yt-dlp/yt-dlp#2428]
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.01.21**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Sweden

### Example URLs

https://urplay.se/program/214542-historien-om-kalla-kriget-skrack-styr-varlden

Urplay.se 

### Description

I am using the latest version and when in trying to download a video from this page i get "unable to extract urplayer data".

https://urplay.se/program/214542-historien-om-kalla-kriget-skrack-styr-varlden

It was suposed to be fixed on this update. Still not working.

### Verbose log

```shell
475-DEBUG-Worker_1-ERROR: Unable to extract urplayer data; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output. 
475-DEBUG-Worker_1-Child process exited with non-zero code: 1
```

**Comment by pukkandan** [comment]
You are using youtube-dl, not yt-dlp
