### ISSUE TITLE
When vp9 bit rate is about 30% higher than AV1

### ISSUE THREAD

**Issue by shimiaoyerin** [yt-dlp/yt-dlp#2432]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

I often get a situation where VP09 is greater than AV01, I have been struggling with their selection weight, whether it is bitrate first or AV01 first?  

### Verbose log

```shell
C:\Users\yerin>yt-dlp https://m.youtube.com/watch?v=E1Z3qgUg_pY -F
[youtube] E1Z3qgUg_pY: Downloading webpage
[youtube] E1Z3qgUg_pY: Downloading android player API JSON
[info] Available formats for E1Z3qgUg_pY:
ID  EXT   RESOLUTION FPS │   FILESIZE    TBR PROTO │ VCODEC           VBR ACODEC      ABR     ASR MORE INFO
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
sb2 mhtml 48x27          │                   mhtml │ images                                       storyboard
sb1 mhtml 80x45          │                   mhtml │ images                                       storyboard
sb0 mhtml 160x90         │                   mhtml │ images                                       storyboard
139 m4a                  │    1.24MiB    48k https │ audio only           mp4a.40.5   48k 22050Hz low, m4a_dash
249 webm                 │    1.01MiB    39k https │ audio only           opus        39k 48000Hz low, webm_dash
250 webm                 │    1.26MiB    49k https │ audio only           opus        49k 48000Hz low, webm_dash
140 m4a                  │    3.28MiB   129k https │ audio only           mp4a.40.2  129k 44100Hz medium, m4a_dash
251 webm                 │    2.26MiB    89k https │ audio only           opus        89k 48000Hz medium, webm_dash
17  3gp   176x144      8 │    1.91MiB    75k https │ mp4v.20.3        75k mp4a.40.2    0k 22050Hz 144p
394 mp4   256x144     30 │    1.76MiB    69k https │ av01.0.00M.08    69k video only              144p, mp4_dash
160 mp4   256x144     30 │    2.59MiB   102k https │ avc1.4d400c     102k video only              144p, mp4_dash
278 webm  256x144     30 │    2.34MiB    92k https │ vp9              92k video only              144p, webm_dash
395 mp4   426x240     30 │    3.68MiB   145k https │ av01.0.00M.08   145k video only              240p, mp4_dash
133 mp4   426x240     30 │    5.70MiB   225k https │ avc1.4d4015     225k video only              240p, mp4_dash
242 webm  426x240     30 │    4.87MiB   192k https │ vp9             192k video only              240p, webm_dash
396 mp4   640x360     30 │    7.84MiB   309k https │ av01.0.01M.08   309k video only              360p, mp4_dash
134 mp4   640x360     30 │   14.28MiB   564k https │ avc1.4d401e     564k video only              360p, mp4_dash
18  mp4   640x360     30 │   18.50MiB   730k https │ avc1.42001E     730k mp4a.40.2    0k 44100Hz 360p
243 webm  640x360     30 │   10.50MiB   414k https │ vp9             414k video only              360p, webm_dash
397 mp4   854x480     30 │   14.78MiB   583k https │ av01.0.04M.08   583k video only              480p, mp4_dash
135 mp4   854x480     30 │   25.24MiB   997k https │ avc1.4d401f     997k video only              480p, mp4_dash
244 webm  854x480     30 │   18.00MiB   711k https │ vp9             711k video only              480p, webm_dash
398 mp4   1280x720    30 │   30.31MiB  1197k https │ av01.0.05M.08  1197k video only              720p, mp4_dash
136 mp4   1280x720    30 │   42.83MiB  1692k https │ avc1.4d401f    1692k video only              720p, mp4_dash
22  mp4   1280x720    30 │ ~ 47.14MiB  1821k https │ avc1.64001F    1821k mp4a.40.2    0k 44100Hz 720p
247 webm  1280x720    30 │   35.78MiB  1413k https │ vp9            1413k video only              720p, webm_dash
399 mp4   1920x1080   30 │   54.92MiB  2170k https │ av01.0.08M.08  2170k video only              1080p, mp4_dash
137 mp4   1920x1080   30 │   99.51MiB  3931k https │ avc1.640028    3931k video only              1080p, mp4_dash
248 webm  1920x1080   30 │   62.51MiB  2469k https │ vp9            2469k video only              1080p, webm_dash
400 mp4   2560x1440   30 │  172.58MiB  6818k https │ av01.0.12M.08  6818k video only              1440p, mp4_dash
271 webm  2560x1440   30 │  206.61MiB  8163k https │ vp9            8163k video only              1440p, webm_dash
401 mp4   3840x2160   30 │  348.31MiB 13762k https │ av01.0.12M.08 13762k video only              2160p, mp4_dash
313 webm  3840x2160   30 │  420.26MiB 16604k https │ vp9           16604k video only              2160p, webm_dash
```

**Comment by pukkandan** [comment]
From https://github.com/yt-dlp/yt-dlp#sorting-formats

> the default order used is: `lang,quality,res,fps,hdr:12,codec:vp9.2,size,br,asr,proto,ext,hasaud,source,id`. The extractors may override this default order, but they cannot override the user-provided order.

> Note that the default has `codec:vp9.2`; i.e. `av1` is not preferred. Similarly, the default for hdr is `hdr:12`; i.e. dolby vision is not preferred. These choices are made since DV and AV1 formats are not yet fully compatible with most devices. This may be changed in the future as more devices become capable of smoothly playing back these formats.

**Comment by shimiaoyerin** [comment]
> From https://github.com/yt-dlp/yt-dlp#sorting-formats
> 
> > the default order used is: `lang,quality,res,fps,hdr:12,codec:vp9.2,size,br,asr,proto,ext,hasaud,source,id`. The extractors may override this default order, but they cannot override the user-provided order.
> 
> > Note that the default has `codec:vp9.2`; i.e. `av1` is not preferred. Similarly, the default for hdr is `hdr:12`; i.e. dolby vision is not preferred. These choices are made since DV and AV1 formats are not yet fully compatible with most devices. This may be changed in the future as more devices become capable of smoothly playing back these formats.

I understand his usage, because I like to collect videos, so I want to collect them in the way of maximum quality, so I want to know if the quality of VP09 is better than AV01 when the bit rate is greater than AV01.  Would a 30% bit rate difference be better than av01?

**Comment by chrizilla** [comment]
related: #458

**Comment by defder-su** [comment]
> I want to collect them in the way of maximum quality

Maybe it sounds like a joke, but in the future maximum quality is achievable by downloading both videos. Because of there will be applications which can use information from both.

**Comment by shimiaoyerin** [comment]
> > I want to collect them in the way of maximum quality
> 
> Maybe it sounds like a joke, but in the future maximum quality is achievable by downloading both videos. Because of there will be applications which can use information from both.

The downloaded video is coded, but at least it's the highest quality that can be collected on the Internet

**Comment by chrizilla** [comment]
> @defder-su : _"in the future maximum quality is achievable by downloading both videos. Because of there will be applications which can use information from both."_

Sounds interesting. Is this your personal prediction or do you have a link for us to read ?

**Comment by aliafshany** [comment]
did you get any answers?

**Comment by pukkandan** [comment]
answers to what? the original question? see #458

**Comment by aliafshany** [comment]
yea i meant that.
thank you

**Comment by shimiaoyerin** [comment]
> 你得到任何答案了吗？



> did you get any answers?

(The following content is from google translation) In fact, the problem does not end here, https://www.youtube.com/watch?v=AfREnMb3vvg, in this case, vp9 has exceeded 100% of the bit rate stream, after my frame comparison , in some scenarios, av1 wins, in some scenarios vp9 wins, and in general similar bit rate streams, the same result, and [https://github.com/yt-dlp/yt-dlp/issues /458](url) just compares with anime, it does not conform to our daily videos, so it is difficult to give an answer
