### ISSUE TITLE
instagram reels download bug

### ISSUE THREAD

**Issue by tucomel** [yt-dlp/yt-dlp#2435]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.01.21**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

instagram error while trying download reels 

### Verbose log

```shell
C:\Users\Arthur>yt-dlp "https://www.instagram.com/p/CYXiOV3INwI/" --cookies "C:\Users\Arthur\Downloads\instagram.com_cookies.txt" -vU
[debug] Command-line config: ['https://www.instagram.com/p/CYXiOV3INwI/', '--cookies', 'C:\\Users\\Arthur\\Downloads\\instagram.com_cookies.txt', '-vU']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.01.21 [f20d607] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.22000-SP0
[debug] exe versions: ffmpeg git-2020-03-15-c467328, ffprobe git-2020-03-15-c467328
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.01.21, Current version: 2022.01.21
yt-dlp is up to date (2022.01.21)
[debug] [Instagram] Extracting URL: https://www.instagram.com/p/CYXiOV3INwI/
[Instagram] CYXiOV3INwI: Downloading webpage
WARNING: [Instagram] unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
ERROR: [Instagram] CYXiOV3INwI: Unable to extract video url; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
  File "yt_dlp\extractor\common.py", line 612, in extract
  File "yt_dlp\extractor\instagram.py", line 347, in _real_extract
  File "yt_dlp\extractor\common.py", line 1300, in _og_search_video_url
  File "yt_dlp\extractor\common.py", line 1195, in _html_search_regex
  File "yt_dlp\extractor\common.py", line 1186, in _search_regex


C:\Users\Arthur>
```

**Comment by o-alquimista** [comment]
When did you try it?

A couple of hours ago I noticed Instagram made some drastic changes to their JSON structure, which caused our extractors to fail, but it was later changed back to a working state. Give it another try!

**Comment by MinePlayersPE** [comment]
Instagram's still using the "reel items" structure for me when logged in
Since there is already a template for a extractor on InstagramStoryIE, I'm assigning myself to this

**Comment by Sharkyyy3** [comment]
The same thing happens with me. Asks me to log in and if I send cookies or password out:
`C:\Users>yt-dlp "https://www.instagram.com/p/CY37IcKls26" --cookies "C:\Users\insta.txt" -vU
[debug] Command-line config: ['https://www.instagram.com/p/CY37IcKls26', '--cookies', 'C:\Users\insta.txt', '-vU']
[debug] Encodings: locale cp1251, fs utf-8, out utf-8, err utf-8, pref cp1251
[debug] yt-dlp version 2022.01.21 [f20d607b0]
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19042-SP0
[debug] exe versions: ffmpeg n4.4-80-gbf87bdd3f6-20210902 (setts), ffprobe n4.4-80-gbf87bdd3f6-20210902
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.01.21, Current version: 2022.01.21
yt-dlp is up to date (2022.01.21)
[debug] [Instagram] Extracting URL: https://www.instagram.com/p/CY37IcKls26
[Instagram] CY37IcKls26: Downloading webpage
WARNING: [Instagram] unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
ERROR: [Instagram] CY37IcKls26: Unable to extract video url; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
  File "c:\users\appdata\local\programs\python\python38\lib\site-packages\yt_dlp\extractor\common.py", line 612, in extract
    ie_result = self._real_extract(url)
  File "c:\users\appdata\local\programs\python\python38\lib\site-packages\yt_dlp\extractor\instagram.py", line 347, in _real_extract
    video_url = self._og_search_video_url(webpage, secure=False)
  File "c:\users\appdata\local\programs\python\python38\lib\site-packages\yt_dlp\extractor\common.py", line 1300, in _og_search_video_url
    return self._html_search_regex(regexes, html, name, **kargs)
  File "c:\users\appdata\local\programs\python\python38\lib\site-packages\yt_dlp\extractor\common.py", line 1195, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "c:\users\appdata\local\programs\python\python38\lib\site-packages\yt_dlp\extractor\common.py", line 1186, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)`

**Comment by Sharkyyy3** [comment]
The same thing happens with me. Asks me to log in and if I send cookies or password out:

```
C:\Users>yt-dlp "https://www.instagram.com/p/CY37IcKls26" --cookies "C:\Users\insta.txt" -vU
[debug] Command-line config: ['https://www.instagram.com/p/CY37IcKls26', '--cookies', 'C:\Users\insta.txt', '-vU']
[debug] Encodings: locale cp1251, fs utf-8, out utf-8, err utf-8, pref cp1251
[debug] yt-dlp version 2022.01.21 [f20d607b0]
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19042-SP0
[debug] exe versions: ffmpeg n4.4-80-gbf87bdd3f6-20210902 (setts), ffprobe n4.4-80-gbf87bdd3f6-20210902
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.01.21, Current version: 2022.01.21
yt-dlp is up to date (2022.01.21)
[debug] [Instagram] Extracting URL: https://www.instagram.com/p/CY37IcKls26
[Instagram] CY37IcKls26: Downloading webpage
WARNING: [Instagram] unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
ERROR: [Instagram] CY37IcKls26: Unable to extract video url; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
  File "c:\users\appdata\local\programs\python\python38\lib\site-packages\yt_dlp\extractor\common.py", line 612, in extract
    ie_result = self._real_extract(url)
  File "c:\users\appdata\local\programs\python\python38\lib\site-packages\yt_dlp\extractor\instagram.py", line 347, in _real_extract
    video_url = self._og_search_video_url(webpage, secure=False)
  File "c:\users\appdata\local\programs\python\python38\lib\site-packages\yt_dlp\extractor\common.py", line 1300, in _og_search_video_url
    return self._html_search_regex(regexes, html, name, **kargs)
  File "c:\users\appdata\local\programs\python\python38\lib\site-packages\yt_dlp\extractor\common.py", line 1195, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "c:\users\appdata\local\programs\python\python38\lib\site-packages\yt_dlp\extractor\common.py", line 1186, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
```

**Comment by wxolp** [comment]
https://github.com/yt-dlp/yt-dlp/issues/2547

**Comment by pritam20ps05** [comment]
it still happens see #3077
