### ISSUE TITLE
List known regressions in update changelogs

### ISSUE THREAD

**Issue by gamer191** [yt-dlp/yt-dlp#2436]
### Checklist

- [X] I'm reporting a feature request
- [X] I've verified that I'm running yt-dlp version **2022.01.21**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

I would appreciate if the update changelogs listed known regressions in the update. A good place to start would be every commit listed as re-opening an issue, such as https://github.com/yt-dlp/yt-dlp/commit/66f7c6a3e0f8e5e1f57c27981d851e10882faa64. It would also be appreciated if regressions from previous updates that remained unpatched were listed. If this feature request would take a lot of effort, then don't worry about it.

Kind regards,
Gamer191

PS: alternatively, listing regressions in the README.md file would also work

**Comment by gamer191** [comment]
Alternatively, listing known regressions in the README.md file would also work

**Comment by pukkandan** [comment]
Known regressions are a rare thing, especially ones that are known at the time of release. But I will keep that in mind to mention any in changelog. It definitely won't be added to readme
