### ISSUE TITLE
Discovery GO changed video URLs

### ISSUE THREAD

**Issue by dare2** [yt-dlp/yt-dlp#2438]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.01.21**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

USA

### Description

Discovery Channel changed the URL/site of their videos. Last week I downloaded an episode of Battlebots successfully. The URL was:

https://go.discovery.com/tv-shows/battlebots/full-episodes/i-like-big-bots

This week, the URL for the same episode is this:

https://go.discovery.com/video/battlebots-discovery-atve-us/i-like-big-bots

Using that URL doesn't even trigger the Discovery extractor and falls back to the generic extractor, as seen in the verbose log.

Hopefully this is a quick fix in getting the Discovery extractor to trigger on the new URL format.

### Verbose log

```shell
>yt-dlp -f best[height=720] --cookies cookdisc.txt https://go.discovery.com/video/battlebots-discovery-atve-us/i-like-big-bots --verbose
[debug] Command-line config: ['-f', 'best[height=720]', '--cookies', 'cookdisc.txt', 'https://go.discovery.com/video/battlebots-discovery-atve-us/i-like-big-bots', '--verbose']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.01.21 [f20d607] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.17763-SP0
[debug] exe versions: ffmpeg N-81707-g11777eb (needs_adtstoasc), ffprobe N-81707-g11777eb, rtmpdump 2.4
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [generic] Extracting URL: https://go.discovery.com/video/battlebots-discovery-atve-us/i-like-big-bots
[generic] i-like-big-bots: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] i-like-big-bots: Downloading webpage
[generic] i-like-big-bots: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://go.discovery.com/video/battlebots-discovery-atve-us/i-like-big-bots
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1367, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1437, in __extract_info
  File "yt_dlp\extractor\common.py", line 612, in extract
  File "yt_dlp\extractor\generic.py", line 3966, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://go.discovery.com/video/battlebots-discovery-atve-us/i-like-big-bots
```

**Comment by cookieguru** [comment]
discovery.com is going to need to be updated to use the [dplay](https://github.com/yt-dlp/yt-dlp/tree/master/yt_dlp/extractor/dplay.py) extractor
