### ISSUE TITLE
This Old House Insider

### ISSUE THREAD

**Issue by scarng63** [yt-dlp/yt-dlp#2443]
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.01.21**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

USA

### Example URLs

https://www.thisoldhouse.com/the-concord-country-cape-episodes

### Description

Unable to download any "Insider" videos from This Old House.  I login to insider account select the video to play, then download cookies and initiate yt-dlp.exe extraction. 

### Verbose log

```shell
[debug] Command-line config: ['-Uv', '--cookies-from-browser', 'chrome', 'https://www.thisoldhouse.com/the-concord-country-cape/22891237/s43-e15-crafty-finishes']
[Cookies] Extracting cookies from chrome
[debug] Extracting cookies from: "C:\Users\Jules\AppData\Local\Google\Chrome\User Data\Default\Network\Cookies"
[Cookies] Extracted 276 cookies from chrome
[debug] cookie version breakdown: {'v10': 276, 'other': 0, 'unencrypted': 0}
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.01.21 [f20d607b0] (win_exe)
[debug] Python version 3.7.2 (CPython 64bit) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg 2021-09-01-git-c500dc7cca-full_build-www.gyan.dev (setts), ffprobe 2021-09-01-git-c500dc7cca-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.01.21, Current version: 2022.01.21
yt-dlp is up to date (2022.01.21)
[debug] [ThisOldHouse] Extracting URL: https://www.thisoldhouse.com/the-concord-country-cape/22891237/s43-e15-crafty-finishes
[ThisOldHouse] s43-e15-crafty-finishes: Downloading webpage
[debug] [Zype] Extracting URL: https://player.zype.com/embed/61e764ef3000810001efd33b.html?api_key=hsOk_yMSPYNrT22e9pu8hihLXjaZf0JW5jsOWv4ZqyHJFvkJn6rtToHl09tbbsbe
[Zype] 61e764ef3000810001efd33b: Downloading JSON metadata
ERROR: [Zype] 61e764ef3000810001efd33b: This video requires a purchase entitlement in order to watch.
  File "yt_dlp\extractor\common.py", line 612, in extract
  File "yt_dlp\extractor\zype.py", line 52, in _real_extract
```

**Comment by Ashish0804** [comment]
Hmmm
Feel free to email me the login details.

**Comment by Ashish0804** [comment]
I have received the login creds and it's what i thought.
Site updated the url on their site but not on their zype backend.
I'll see what I can do
