### ISSUE TITLE
why when downloading the worst quality video it becomes 3gp not video+audio dash

### ISSUE THREAD

**Issue by candrapersada** [yt-dlp/yt-dlp#2451]
### Checklist

- [x] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.01.21**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [ ] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [ ] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

why `yt-dlp -f "wv*+wa"` not working properly, for example, when I download a video with the worst quality, it downloads in 3gp format, not video+audio?

### Verbose log

```shell
[debug] Home config "yt-dlp.conf": ['-i', '--hls-prefer-native', '--remux-video'
, 'mp4', '-f', 'wv*+wa/w', '-N', '10', '--fragment-retries', 'infinite', '--outp
ut', '%(playlist)s/%(title)s.%(ext)s', '-vU']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8 (No ANSI), err utf-8 (No A
NSI), pref cp1252
[debug] yt-dlp version 2022.01.21 [f20d607] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg n4.4.1-3-gb9e6f19095-20211123 (setts), ffprobe 4.4-
full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.01.21, Current version: 2022.01.21
yt-dlp is up to date (2022.01.21)
```

**Comment by pukkandan** [comment]
You thin 3gp is not worse quality than the other formats?

**Comment by candrapersada** [comment]
not what I mean is the merge video+audio feature with use `yt-dlp -f "wv*+wa"` but what I download is only 3gp, not video+audio?

**Comment by pukkandan** [comment]
Remove the `*` if you want to guarantee separate video and audio downloads

**Comment by candrapersada** [comment]
how to use `[height<=129]` for audio 129k

**Comment by pukkandan** [comment]
`-f ba[abr<=129k]`
