### ISSUE TITLE
Unable to play downloaded video using QuickTime Player on macOS. Video generated uses Google vp9 encoding method, not generic encode (H.264/265)

### ISSUE THREAD

**Issue by hkix** [yt-dlp/yt-dlp#2453]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

When I tried to play the video downloaded using yt-dlp, an error message occured: 

<img width="467" alt="Screenshot 2022-01-23 at 22 27 56" src="https://user-images.githubusercontent.com/83116884/150683311-2b9c7d8c-168f-48dd-8deb-93fc8a3c5867.png">

I also cannot play the downloaded file on iOS devices. 
However, I can play the video using other player, such as IINA on macOS. I found that the video encoding is vp9 (Google vp9), not a generic format such as H.264/265

<img width="470" alt="IINA_video_info" src="https://user-images.githubusercontent.com/83116884/150683046-64b2d9aa-e349-4b38-9f08-3283732777e3.png">

For comparison, this is a youtube video downloaded using another web-based download tool, which uses H.264 encode, and it can be properly played using QuickTime Player or iOS device. 

<img width="496" alt="IINA_h264" src="https://user-images.githubusercontent.com/83116884/150683440-bfc1e9b3-30ac-4d5b-8574-837bfd6be81d.png">

I am using the following lines in configuration file for encoding: 
`--merge-output-format mp4`
`--recode-video mp4`

What encoding configuration is needed to properly encode the downloaded video, so that it can play on any device without specialized player?

**Comment by pukkandan** [comment]
Idk what your player supports, or why it can't play vp9. Even web browsers can play vp9!. Assuming only h264 is supported, you'd do this: `-S codec:h264:m4a`
