### ISSUE TITLE
[Question] --downloader aria2c is not working for Crunchyroll?

### ISSUE THREAD

**Issue by erickyun** [yt-dlp/yt-dlp#246]
it uses ffmpeg to download?

Verbose:
https://pastebin.com/raw/nRi1MCsF

**Comment by pukkandan** [comment]
There was a bug with downloader selection for m3u8 in the latest version. That may be the culprit. Can you try either with git master or the previous release?

**Comment by erickyun** [comment]
> There was a bug with downloader selection for m3u8 in the latest version. That may be the culprit. Can you try either with git master or the previous release?

Yes git master and yt-dlp 2021.4.3 works thank you for your response.
