### ISSUE TITLE
Support --write-html flag

### ISSUE THREAD

**Issue by defder-su** [yt-dlp/yt-dlp#2460]
### Checklist

- [X] I'm reporting a feature request
- [X] I've verified that I'm running yt-dlp version **2022.01.21**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

I would like to save html page related to video. It may contain info which yt-dlp doesn't parse. For example, [Coub](https://coub.com) items contains tags and also link to source video.

Yt-dlp downloads specified web page for video. Just write it as html, if --write-html specified.

**Comment by pukkandan** [comment]
If you just want the initial webpage, just use curl. If you want all pages that yt-dlp downloads use `--write-pages`

**Comment by defder-su** [comment]
I use yt-dlp for downloading channels with option `--output "%(uploader)s/%(uploader)s - %(upload_date)s - %(title)s/%(uploader)s - %(upload_date)s - %(title)s [%(id)s].%(ext)s"` (seeing [the script](https://github.com/defder-su/SaveMedia/blob/master/scripts/Channels/save)). So, I can't obtain html in corresponded place easily (moreover, any complex solution may be broken by some yt-dlp update).

**Comment by pukkandan** [comment]
These metadata are extracted from the downloaded pages and are hence not known not at the time of downloading the page. So this is impossible

**Comment by defder-su** [comment]
There are way I see to use --write-url-link and then parse all *.url files, wgetting corresponded *.html.

**Comment by chrizilla** [comment]
> If you just want the initial webpage, use curl/wget etc.

can this be handled/called by yt-dlp via a parameter ?
It would be nice if yt-dlp could be set to download the initial webpage automatically for every video and place it into the `-o description:` directory.

**Comment by defder-su** [comment]
There is a workaround in [write_html script](https://github.com/defder-su/SaveMedia/blob/master/scripts/write_html). Requires  --write-url-link option (seeing example [save script](https://github.com/defder-su/SaveMedia/blob/master/scripts/Unique/save)).
