### ISSUE TITLE
--print playlist problem

### ISSUE THREAD

**Issue by chrizilla** [yt-dlp/yt-dlp#2465]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.01.21**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

## scenario 1 (ok)

with yt-dlp.conf:
```
--print "playlist              %(playlist)s"
--print "playlist_id:          %(playlist_id)s"
--print "playlist_title:       %(playlist_title)s"
```
and this command `yt-dlp https://www.youtube.com/watch?v=MegG5jFNRmQ&list=PLTlJK3kwZIbQM5WM-J3wAc20xcQuuwinm`

I get this ouput:
```
playlist              NA
playlist_id:          NA
playlist_title:       NA
"list" is not recognized as an internal or external command
```
... which is fine. However in the following scenario:

## scenario 2
When I add ":" after "playlist"
```
--print "playlist:             %(playlist)s"
--print "playlist_id:          %(playlist_id)s"
--print "playlist_title:       %(playlist_title)s"
```
and for the same command as above, the first line in the output disappears:
```
playlist_id:          NA
playlist_title:       NA
"list" is not recognized as an internal or external command
```

## errors/bugs ?

1. Why does the line disappear? Is this an error/bug ?
2. Why do I get the error `"list" is not recognized as an internal or external command` ?
3. Shouldn't these 3 fields have some values?
    (`playlist_title`="Motherboard’s Space Show", `playlist_id`="PLTlJK3kwZIbQM5WM-J3wAc20xcQuuwinm")

Has 1+2 been fixed in the [printing bug fix](https://github.com/yt-dlp/yt-dlp/issues/2464#issuecomment-1019575639) ?

With **v2021.12.27** I get these results:
❌ `"list ist not recognized"` error: is also thrown
✔️  line does not disappear, even with `colon` --print "playlist:"
❌ the 3 fields are also empty

**Comment by pukkandan** [comment]
`playlist:` is a valid prefix (WHEN) for `--print`. So it is interpreted as such

```

-O, --print [WHEN:]TEMPLATE      Field name or output template to print to
                                 screen, optionally prefixed with when to
                                 print it, separated by a ":". Supported
                                 values of "WHEN" are the same as that of
                                 --use-postprocessor, and "video" (default).
                                 Implies --quiet and --simulate (unless
                                 --no-simulate is used). This option can be
                                 used multiple times
--use-postprocessor NAME[:ARGS]  ...
                                 The "when" argument determines when the
                                 postprocessor is invoked. It can be one of
                                 "pre_process" (after extraction),
                                 "before_dl" (before video download),
                                 "post_process" (after video download;
                                 default), "after_move" (after moving file
                                 to their final locations), "after_video"
                                 (after downloading and processing all
                                 formats of a video), or "playlist" (end of
                                 playlist). ...
```

If you do not want it to be interpretted as a prefix, explicityly give the `video:` prefix

```
--print "video:playlist: %(playlist)s"
```

> "list ist not recognized" error: is also thrown

This is printed by cmd because you did not quote the command properly

> - [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)

> the 3 fields are also empty

Also caused due to wrong quoting

**Comment by chrizilla** [comment]
Thanks for the explanation. And I am very sorry for the missing quotes.

**Comment by Zirro** [comment]
> playlist: is a valid prefix (WHEN) for --print. So it is interpreted as such

The occurrence of this could probably be substantially reduced if no whitespace was allowed around the ":"-delimiter for a prefix to be recognised.
