### ISSUE TITLE
[BRMediathek] redirect fails

### ISSUE THREAD

**Issue by chrizilla** [yt-dlp/yt-dlp#2466]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.01.21**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required **(no account required)**

### Region

Germany

### Description

both
https://www.br.de/mediathek/video/av:61b0db581aed360007558c12
https://www.br.de/mediathek//video/av:61b0db581aed360007558c12

redirect to

https://www.br.de/mediathek/video/meryns-sprechzimmer-gesundheitstalk-corona-positiv-trotz-impfung-av:61b0db581aed360007558c12

yt-dlp recognizes the latter URL, but not the former (see log below).

### Verbose log

```shell
[debug] Command-line config: ['https://www.br.de/mediathek//video/av:61b0db581aed360007558c12', '-v', '--ignore-config', '-F']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.01.21 [f20d607] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] exe versions: ffmpeg N-105208-gb24f0c82b3-20220108 (setts), ffprobe N-105208-gb24f0c82b3-20220108
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [generic] Extracting URL: https://www.br.de/mediathek//video/av:61b0db581aed360007558c12
[generic] av:61b0db581aed360007558c12: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] av:61b0db581aed360007558c12: Downloading webpage
[generic] av:61b0db581aed360007558c12: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://www.br.de/mediathek//video/av:61b0db581aed360007558c12
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1367, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1437, in __extract_info
  File "yt_dlp\extractor\common.py", line 612, in extract
  File "yt_dlp\extractor\generic.py", line 3966, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.br.de/mediathek//video/av:61b0db581aed360007558c12
```

**Comment by pukkandan** [comment]
This will probably fix this, but I cant test due to geo-blocking
```diff
diff --git a/yt_dlp/extractor/br.py b/yt_dlp/extractor/br.py
index 7169eceb6..bd618119c 100644
--- a/yt_dlp/extractor/br.py
+++ b/yt_dlp/extractor/br.py
@@ -175,7 +175,7 @@ class BRIE(InfoExtractor):

 class BRMediathekIE(InfoExtractor):
     IE_DESC = 'Bayerischer Rundfunk Mediathek'
-    _VALID_URL = r'https?://(?:www\.)?br\.de/mediathek/video/[^/?&#]*?-(?P<id>av:[0-9a-f]{24})'
+    _VALID_URL = r'https?://(?:www\.)?br\.de/mediathek/video/(?:[^/?&#]+?-)?(?P<id>av:[0-9a-f]{24})'

     _TESTS = [{
         'url': 'https://www.br.de/mediathek/video/gesundheit-die-sendung-vom-28112017-av:5a1e6a6e8fce6d001871cc8e',
diff --git a/yt_dlp/extractor/youtube.py b/yt_dlp/extractor/youtube.py
index 98f02331c..c29afe98e 100644
```

**Comment by pukkandan** [comment]
Are you able to test this? if so, I can commit

**Comment by chrizilla** [comment]
thank you for the fix.
I am also geo-blocked and currently only have access to a Windows machine.
I use Tor to get around geo-blocks, but I think I need a yt-dlp.exe file for that.
I asked elsewhere how to do that and was [told](https://github.com/Lazza/RecuperaBit/issues/105#issuecomment-1030006194) _"building an executable from python is not always an easy task and most of the time it's a waste of time"_ .

Your code looks good to me.
It doesn't account for the double-slash `//` before `video` though, which I have sometimes seen in [br.de](http://www.br.de) URLs in the wild (or is this handled elsewhere in the code?).

I don't know if that's of any help, but if you commit, I can test the next released .exe ?

**Comment by pukkandan** [comment]
You don't need to build the exe. Assuming you have python installed, you can just download the source and run `yt-dlp.cmd`

**Comment by chrizilla** [comment]
ok, I'll see what I can do.

**Comment by chrizilla** [comment]
sry, I was unable to look into that earlier.
I tried but I seem to be unable to get around the geo-block.

`--geo-bypass-country DE` doesn't work for me
`--proxy socks5://127.0.0.1:9150` with concurrently running Tor browser did work for me in the past, but for reasons unknown to me, this currently also fails

So I'm afraid, I'm in the same situation as yourself, seeing that I live outside DE.

What are your tricks to get around geo-blocks such as this ?

**Comment by calestyo** [comment]
I wouldn't be affected by geoblocking, but it doesn't work for me.... which I don't understand as the RE looks good.

It still falls simply back to the generic extractor:
```
$ yt-dlp https://www.br.de/mediathek/video/av:5f05c7f21d8f38001b2bd431 -F
[generic] av:5f05c7f21d8f38001b2bd431: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] av:5f05c7f21d8f38001b2bd431: Downloading webpage
[generic] av:5f05c7f21d8f38001b2bd431: Extracting information
ERROR: Unsupported URL: https://www.br.de/mediathek/video/av:5f05c7f21d8f38001b2bd431
```

**Comment by calestyo** [comment]
@pukkandan any idea why it doesn't match?

**Comment by pukkandan** [comment]
You likely did not apply the patch correctly https://regex101.com/r/sDiZlp/1

**Comment by calestyo** [comment]
Nah it wasn't that... must have been something with the pyc stuff... when I just edited the py files from the Debian package, it didn't work - but when I rebuilt the latter it worked.

Anyway... your patch works, please merge.

**Comment by pukkandan** [comment]
Editing yt-dlp's source files from packages (either PIP or other PMs) often don't work since it contains some code that is auto-generated at build time (lazy_extractors.py). If you are modifying source code, you must have lazy extractors disabled

**Comment by calestyo** [comment]
Ah I see.

Any... I've been able to confirm that it works.
