### ISSUE TITLE
How to get 1080p iq.com

### ISSUE THREAD

**Issue by cx410** [yt-dlp/yt-dlp#2467]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

Hello

How to get 1080p resolution on iq.com? I've used VIP account cookies, but still only getting 720p.

`WARNING: [iq.com] 1080P format is restricted`

https://ibb.co/VCysC8y

**Comment by MinePlayersPE** [comment]
Will be fixed in https://github.com/yt-dlp/yt-dlp/pull/2444
