### ISSUE TITLE
Should we report if --geo-bypass doesn't help ?

### ISSUE THREAD

**Issue by chrizilla** [yt-dlp/yt-dlp#2468]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

Should we report if a site is geo-blocked and `--geo-bypass` `--geo-bypass-country` doesn't help ?

**Comment by pukkandan** [comment]
No. It only works for some sites and if it doesn't, there is nothing we can do to make it

**Comment by chrizilla** [comment]
I thought as much. As always, thanks pukkandan.

> If it doesn't work for a site where it is enabled by **default**, feel free to report so that the default can be removed

will do
