### ISSUE TITLE
make a --really-best-format option

### ISSUE THREAD

**Issue by philcerf** [yt-dlp/yt-dlp#2469]
### Checklist

- [X] I'm reporting a feature request
- [X] I've verified that I'm running yt-dlp version **2022.01.21**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

The format sorting is documented to have the default:
```
lang,quality,res,fps,hdr:12,codec:vp9.2,size,br,asr,proto,ext,hasaud,source,id
```
mentioning that `hdr:12` and `odec:vp9.2` is set because better ones aren't supported by many devices yet.

That seems rather unfortunate, because people expect that per default they get the "best", while in fact they may not in some cases.

Of course one could just override that with:
```
--format-sort 'lang,quality,res,fps,hdr,codec,size,br,asr,proto,ext,hasaud,source,id'
```
which has however the drawback, that it also overrides any extractor specific sort order (which is usually there for a good reason).

So it would be nice to either have something like a `--really-best-format` option or alternatively, really use the best per default (and perhaps provide a compatibility option that allow people to select formats for older devices.

Cheers.

**Comment by chrizilla** [comment]
related: #2260

**Comment by Ashish0804** [comment]
or better way is to make `best` really the best by using av1 and add a `--i-use-dlp-on-a-toaster-even-in-2020s` option.

**Comment by philcerf** [comment]
@pukkandan But doesn't this again mean that one needs to manually override (and worse, have knowledge about why some extractors override the default and whether this should be actually kept)?

What @Ashish0804 proposes would have my other choice... I guess it's probably just bad, that the default is not really the best.

**Comment by pukkandan** [comment]
https://github.com/yt-dlp/yt-dlp/issues/458#issuecomment-913082217

The HDR restriction makes sense to use permanently. While DV is technically better than the other formats, it is terrible if your display does not support it. So I want users to specifically ask for it if they want to prioritize it

**Comment by Jules-A** [comment]
@philcerf  Even if most people can play AV1, Youtube (practically the only site that's serving it) aim for AV1 to have the same quality as the VP9 encode with the advantage only being the file size savings from using a lower bitrate which is more useful for streaming than downloading with YT-DLP.

**Comment by nyuszika7h** [comment]
> [#458 (comment)](https://github.com/yt-dlp/yt-dlp/issues/458#issuecomment-913082217)
> 
> The HDR restriction makes sense to use permanently. While DV is technically better than the other formats, it is terrible if your display does not support it. So I want users to specifically ask for it if they want to prioritize it

Yeah, DV is a proprietary format. But dual-layer HDR10+DV streams (DV profile 8) should probably be prioritized over HDR10-only.

**Comment by chrizilla** [comment]
> with the advantage only being the file size savings from using a lower bitrate which is more useful for streaming than downloading with YT-DLP.

???

Same quality for half (or considerable reduction of) the file size is useful for both streaming and downloading. One could argue that filesize is even more important for downloading given that you have to store the downloaded video on a limited storage space.

**Comment by chrizilla** [comment]
> @Ashish0804 commented on Jan 24, 2022:
> _or better way is to make `best` really the best by using av1_

@pukkandan : as 15 months have passed, I thought it may be time to reconsider ?
