### ISSUE TITLE
AbemaTV 

### ISSUE THREAD

**Issue by BLSTR13** [yt-dlp/yt-dlp#2472]
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.01.21**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Region

Japan

### Example URLs

https://abema.tv/video/episode/273-123_s1_p1
https://abema.tv/video/title/273-123

### Description

I can download it on streamlink but I want to have a support on yt-dlp so it can be easily downloaded and easy conversion to mkv

### Verbose log

```shell
[debug] Command-line config: ['-vU', 'https://abema.tv/video/episode/273-123_s1_p1']
[debug] User config "C:\Users\Cherri Estudillo\AppData\Roaming\yt-dlp\config.txt": ['-o', 'D:/ytdl/%(title)s.%(ext)s', '--no-mtime']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.01.21 [f20d607] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] exe versions: ffmpeg 2021-10-28-git-e84c83ef98-essentials_build-www.gyan.dev (setts), ffprobe 2021-10-28-git-e84c83ef98-essentials_build-www.gyan.dev
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.01.21, Current version: 2022.01.21
yt-dlp is up to date (2022.01.21)
[debug] [generic] Extracting URL: https://abema.tv/video/episode/273-123_s1_p1
[generic] 273-123_s1_p1: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] 273-123_s1_p1: Downloading webpage
[generic] 273-123_s1_p1: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://abema.tv/video/episode/273-123_s1_p1
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1367, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1437, in __extract_info
  File "yt_dlp\extractor\common.py", line 612, in extract
  File "yt_dlp\extractor\generic.py", line 3966, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://abema.tv/video/episode/273-123_s1_p1
```

**Comment by BLSTR13** [comment]
@Lesmiscore dont have a knowledge in coding and stuff, can you please explain this to me? cant really understand the pull request too

**Comment by Lesmiscore** [comment]
@BLSTR13 It literally adds support for AbemaTV. Although it can't be merged without dependent PRs.

**Comment by BLSTR13** [comment]
> @BLSTR13 It literally adds support for AbemaTV. Although it can't be merged without dependent PRs.

So it can still extract from AbemaTV or no? If so, how?

**Comment by Lesmiscore** [comment]
@BLSTR13 You need to do something complex to actually use that.
Instead you can try how it works using https://github.com/ytdl-patched/ytdl-patched where AbemaTV support is already implemented.

**Comment by BLSTR13** [comment]
> @BLSTR13 You need to do something complex to actually use that.
> Instead you can check how it works using https://github.com/ytdl-patched/ytdl-patched where AbemaTV support is already implemented.

Thanks!
