### ISSUE TITLE
Question: how can I use --restrict-filenames on some given filename

### ISSUE THREAD

**Issue by philcerf** [yt-dlp/yt-dlp#2474]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

What I'd like to do is using `--restrict-filenames` in the future and also rename all my existing downloads accordingly.

I have the `info.json` so it's easy to get the real title... is it somehow possible to directly call `filename_sanitizer` (which I guess is the function that does the conversion)?

Thanks :-)

**Comment by pukkandan** [comment]
Are you asking about the API, or the CLI?

**Comment by philcerf** [comment]
I could live with both... I tried to directly import utils.py in Python an call the function from there, but apparently my Python skills aren't good enough ^^

Ideally something like:
`printf '%s' "$title" | magic` which prints out the transformed filename.

**Comment by pukkandan** [comment]
You have the infojson, right? So you can do:

    yt-dlp --print filename --restrict-filenames --load-info "path/to/your.info.json"

Note that the printed file's extension may be wrong depending on what options you were using while actually downloading it
