### ISSUE TITLE
Videos on CCTV.com only download partially

### ISSUE THREAD

**Issue by ualaa1** [yt-dlp/yt-dlp#2479]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.01.21**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Description

Example video: https://tv.cctv.com/2022/01/24/VIDEumOgCNSu1sJ0tH5OVNGK220124.shtml
It is 25 minutes long but yt-dlp only downloads first five minutes. Video downloading seems to work correct on youtube-dl

### Verbose log

```shell
yt-dlp -vU "https://tv.cctv.com/2022/01/24/VIDEumOgCNSu1sJ0tH5OVNGK220124.shtml"
[debug] Command-line config: ['-vU', 'https://tv.cctv.com/2022/01/24/VIDEumOgCNSu1sJ0tH5OVNGK220124.shtml']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.01.21 [f20d607b0]
[debug] Python version 3.9.0 (CPython 64bit) - macOS-12.0.1-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.01.21, Current version: 2022.01.21
yt-dlp is up to date (2022.01.21)
[debug] [CCTV] Extracting URL: https://tv.cctv.com/2022/01/24/VIDEumOgCNSu1sJ0tH5OVNGK220124.shtml
[CCTV] VIDEumOgCNSu1sJ0tH5OVNGK220124: Downloading webpage
[CCTV] f21b0f09a2cd4a13b3c773e74b34be9c: Downloading JSON metadata
[CCTV] f21b0f09a2cd4a13b3c773e74b34be9c: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] f21b0f09a2cd4a13b3c773e74b34be9c: Downloading 1 format(s): http
[debug] Invoking downloader on "http://hot.v.cntv.cn/flash/mp4video63/TMS/2022/01/24/f21b0f09a2cd4a13b3c773e74b34be9c_h264418000nero_aac32-1.mp4"
[download] Destination: 《回家吃饭》 20220124 晒晒我家年夜饭（五） 给新年餐桌添点异域风味 [f21b0f09a2cd4a13b3c773e74b34be9c].mp4
[download] 100% of 16.24MiB in 00:01
```

**Comment by pukkandan** [comment]
As a workaround, select a diff format than `http`
