### ISSUE TITLE
`epoch` should be renamed to its meaning

### ISSUE THREAD

**Issue by schittli** [yt-dlp/yt-dlp#2484]
### Checklist

- [X] I'm reporting a feature request
- [X] I've verified that I'm running yt-dlp version **2022.01.21**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

Hello

I have a small suggestion that should improve the understandability of yt-dlp:
`epoch`, the output template field name, states in its name that _"it is of the type 'Unix epoch'"_.

This, unfortunately, leads to tedious questions and misunderstandings, because field names should not say what type they are from, but what content, what value they represent. Unfortunately, the help description is also vague, too:
> epoch (numeric): Unix epoch when creating the file

I thought that `epoch` represents the time at which the YouTube Video / Audio file was produced. 
This is probably wrong: I *suspect* that the field records the time at which yt-dlp downloads the file.

### Proposal: Rename the field `epoch` to `download_timestamp`

Because of the help text _"epoch (numeric): Unix epoch when creating the file"_ one could also choose `creation_timestamp`, but then it is unclear which time is meant: the time when the video was produced? Or the time when the file was downloaded?

Therefore I think that `download_timestamp` would be the clearest and most useful name instead of `epoch`.

Thanks a lot, kind regards,
Thomas

**Comment by chrizilla** [comment]
:+1 for `download_timestamp`

other suggestions for better understanding:

1. > `playlist` (string): Name or id of the playlist that contains the video
   
    could be clarified as follows (whatever applies):
   * "`playlist` (string): equals either `playlist_id` or `playlist_title`" or
   * "`playlist` (string): equals `playlist_title` and, if void, falls back to `playlist_id`"
    ... because these fields are already defined. I think this would help avoid [misunderstandings](https://github.com/yt-dlp/yt-dlp/issues/2464#issuecomment-1019582889).
   

2. > `--concat-playlist POLICY` ... `multi_video` (default; only when the videos form a single show)`
   
   maybe rename `multi_video` to `single_show` ?
I'm not sure `multi_video` is very conclusive in a context (concatting) that **always** deals with multiple videos.

**Comment by pukkandan** [comment]
Field names will not be renamed. I can consider clarifying the help text

**Comment by chrizilla** [comment]
> 2\. maybe rename `multi_video` to `single_show` ?
>         I'm not sure `multi_video` is very conclusive in a context (concatting) that **always** deals with multiple videos.

> pukkandan: Field names will not be renamed.

I only suggested it because this one is only a few days old and thus not yet widely adopted.

**Comment by pukkandan** [comment]
`multi_video` is not a new thing. Only concating it is. https://github.com/yt-dlp/yt-dlp/blob/fa8fd951184017b9ba164dfa5e6d95d44ff6edd4/yt_dlp/extractor/common.py#L400-L403

**Comment by pukkandan** [comment]
Yes, I understand. I am just clarifying why the option is called "multi_video"

**Comment by chrizilla** [comment]
I know and thank you for that. Very helpful, as always.

**Comment by chrizilla** [comment]
For `playlist` I would have explained that it equals either `playlist_title` or `playlist_id` and how this decision is made.

**Comment by pukkandan** [comment]
😕 It does say! 

> Either the id or the name

**Comment by chrizilla** [comment]
> 😕 It does say!
> 
> > Either the id or the name

You decide of course.
In my opinion, "either `playlist_title` or `playlist_id`" would be more precise.
Why paraphrase if precisely defined variables exist already.
It's incomprehensible for me, but do what you deem best.

**Comment by pukkandan** [comment]
See the linked commit
