### ISSUE TITLE
Helptext for `epoch' is ambiguous

### ISSUE THREAD

**Issue by schittli** [yt-dlp/yt-dlp#2485]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.01.21**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

Hello

In [readme.md](https://github.com/yt-dlp/yt-dlp#readme) the field `epoch` is explained as:

> epoch (numeric): Unix epoch when creating the file

Unfortunately, this description is ambiguous, because it is unclear from which file the creation date is meant. 
For example, I thought that it is the creation timestamp of the Youtube video, e.g. if the author cuts the video, and then the Video is re-published and replaces the previous version.

### Therefore I propose a slightly more specific help text like:

**_epoch (numeric, Unix epoch): time at which yt-dlp downloads a file._**

Thanks a lot, kind regards and all the best!
Thomas

### Verbose log

```shell
NA
```

**Comment by Ashish0804** [comment]
Issues are not for you to play around. 
It is because of stupid trolls like these that open source maintainers feel burnt out and the project eventually dies.
