### ISSUE TITLE
support for eurosport.com

### ISSUE THREAD

**Issue by chrizilla** [yt-dlp/yt-dlp#2487]
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.01.21**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

worldwide

### Example URLs

https://www.eurosport.com/tennis/australian-open/2022/nick-kyrgios-hits-kid-in-crowd-with-wild-shot-turns-his-tears-to-smiles-with-gift-at-australian-open_vid1614604/video.shtml

### Description

[Eurosport](https://en.wikipedia.org/wiki/Eurosport) is a pan-European television sports network and a subsidiary of Discovery.

### Verbose log

```shell
[debug] Command-line config: ['https://www.eurosport.com/tennis/australian-open/2022/nick-kyrgios-hits-kid-in-crowd-with-wild-shot-turns-his-tears-to-smiles-with-gift-at-australian-open_vid1614604/video.shtml', '--ignore-config', '-v']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.01.21 [f20d607] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] exe versions: ffmpeg N-105208-gb24f0c82b3-20220108 (setts), ffprobe N-105208-gb24f0c82b3-20220108
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [generic] Extracting URL: https://www.eurosport.com/tennis/australian-open/2022/nick-kyrgios-hits-kid-in-crowd-with-wild-shot-turns-his-tears-to-smiles-with-gift-at-australian-open_vid1614604/video.shtml
[generic] video: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] video: Downloading webpage
[generic] video: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://www.eurosport.com/tennis/australian-open/2022/nick-kyrgios-hits-kid-in-crowd-with-wild-shot-turns-his-tears-to-smiles-with-gift-at-australian-open_vid1614604/video.shtml
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1367, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1437, in __extract_info
  File "yt_dlp\extractor\common.py", line 612, in extract
  File "yt_dlp\extractor\generic.py", line 3966, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.eurosport.com/tennis/australian-open/2022/nick-kyrgios-hits-kid-in-crowd-with-wild-shot-turns-his-tears-to-smiles-with-gift-at-australian-open_vid1614604/video.shtml
```

**Comment by HobbyistDev** [comment]
I found url that not geo-blocked:
https://www.eurosport.com/tennis/roland-garros/2022/highlights-rafael-nadal-brushes-aside-caper-ruud-to-win-record-extending-14th-french-open-title_vid1694147/video.shtml
https://www.eurosport.com/tennis/roland-garros/2022/watch-the-top-five-shots-from-men-s-final-as-rafael-nadal-beats-casper-ruud-to-seal-14th-french-open_vid1694283/video.shtml

**Comment by alternistom** [comment]
This would be a game changer, currently I have to download the audio and video separately then join hem together afterwards.
