### ISSUE TITLE
'Latin-1' codec can't encode

### ISSUE THREAD

**Issue by nnovrealty52** [yt-dlp/yt-dlp#2489]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

yt-dlp -f 299 https://www.youtube.com/watch?v=n61ULEU7CO0&t=14221s
[2] 42381
root@vm327935:~/video# [youtube] n61ULEU7CO0: Downloading webpage
[youtube] n61ULEU7CO0: Downloading android player API JSON
[info] n61ULEU7CO0: Downloading 1 format(s): 299
ERROR: 'latin-1' codec can't encode character '\u2728' in position 26: ordinal not in range(256)

Ubuntu 20.04 - error
Kali linux 2021.2 - ok

why does Ubuntu start up with an error? 

Ubuntu 20.04 - error
Kali linux 2021.2 - ok

why does Ubuntu start up with an error? 
Python versions are identical in both ubuntu and kali linux

**Comment by pukkandan** [comment]
READ the issue form you are filling out!

> - [x] I'm asking a question and not reporting a bug/feature request
>
> ...
> If your question contains "isn't working" or "can you add", this is most likely the wrong template

Open a bug report with relevant verbose logs

PS: Quote your URL too
