### ISSUE TITLE
[Feature Request] Improved Youtube Search Extractor Support

### ISSUE THREAD

**Issue by horahoradev** [yt-dlp/yt-dlp#249]
## Checklist
- [X] I'm reporting a feature request
- [X] I've verified that I'm running yt-dlp version **2021.04.11**
- [X] I've searched the bugtracker for similar feature requests including closed ones

## Description
I'm requesting improved search extractor support for youtube. The current API in use allows up to 30-31 pages of results, which isn't sufficient for my purposes. Ideally, the search extractor would be modified to allow an arbitrary number of results to be returned.
I'm willing to pay if someone can add this.

**Comment by october262** [comment]
would something like this work ?? - https://www.reddit.com/r/learnpython/comments/3q1wfl/how_to_search_for_videos_in_youtubedl/

**Comment by coletdjnz** [comment]
I don't think there is any known method of returning more results from YouTube searches. There *could* possibly be some way through modifying the tokens, however, even if someone does find that it would likely not be implemented as it would be prone to breaking.

**Comment by pukkandan** [comment]
This may be possible after all https://github.com/ytdl-org/youtube-dl/issues/30795#issuecomment-1084552639

**Comment by horahoradev** [comment]
Ok this is epic

**Comment by coletdjnz** [comment]
Closing as not really feasible and the workaround solution would be extremely hacky and probably unstable. It would be better off as a plugin.
