### ISSUE TITLE
Problem with sound on france.tv

### ISSUE THREAD

**Issue by illydone** [yt-dlp/yt-dlp#2490]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.01.21**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

France

### Description

When downloading on france.tv without argument the video is complete but the sound stops after about a few minutes.
I tried with -x and in this case the resulting m4a file size is only 5MB although the original sound file was 65MB.
I tried with 2 links and the result is the same.
For example: https://www.france.tv/france-2/alex-hugo/alex-hugo-saison-6/1950415-un-reve-impossible.html

### Verbose log

```shell
There's no apparent problem but after downloading and merging the sound file is incomplete.
```

**Comment by pukkandan** [comment]
Possibly https://github.com/yt-dlp/yt-dlp/issues/2528
