### ISSUE TITLE
"Unable to extract next.js data" when trying to download TED talk

### ISSUE THREAD

**Issue by nortti0** [yt-dlp/yt-dlp#2491]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.01.21**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Finland

### Description

When trying to download TED talks (e.g. https://www.ted.com/talks/thomas_thwaites_how_i_built_a_toaster_from_scratch but the same issue manifested also with arbitrary ones I tried from the front page), I get the error that yt-dlp is unable to extract the `next.js` data. I presume this is due to the format of `next.js` having changed.

I found a #2343 which appeared relevant, but that was marked fixed. The new TED extractor that fixed that issue was merged 6 days ago (#2359), and so I presume would be in 2022.01.21 which I am using.

### Verbose log

```shell
[debug] Command-line config: ['-vU', 'https://www.ted.com/talks/thomas_thwaites_how_i_built_a_toaster_from_scratch']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.01.21 [f20d607b0] (zip)
[debug] Python version 3.8.10 (CPython 64bit) - Linux-5.4.0-96-generic-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4, rtmpdump 2.4
[debug] Optional libraries: Cryptodome, secretstorage, sqlite
[debug] Proxy map: {}
Latest version: 2022.01.21, Current version: 2022.01.21
yt-dlp is up to date (2022.01.21)
[debug] [TedTalk] Extracting URL: https://www.ted.com/talks/thomas_thwaites_how_i_built_a_toaster_from_scratch
[TedTalk] thomas_thwaites_how_i_built_a_toaster_from_scratch: Downloading webpage
ERROR: [TedTalk] thomas_thwaites_how_i_built_a_toaster_from_scratch: Unable to extract next.js data; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
  File "/home/nortti/bin/yt-dlp/yt_dlp/extractor/common.py", line 612, in extract
    ie_result = self._real_extract(url)
  File "/home/nortti/bin/yt-dlp/yt_dlp/extractor/ted.py", line 48, in _real_extract
    talk_info = self._search_nextjs_data(webpage, display_id)['props']['pageProps']['videoData']
  File "/home/nortti/bin/yt-dlp/yt_dlp/extractor/common.py", line 1550, in _search_nextjs_data
    self._search_regex(
  File "/home/nortti/bin/yt-dlp/yt_dlp/extractor/common.py", line 1186, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
```

**Comment by trassshhub** [comment]
Sigh, it seems that TED has decided to revert only their talks page back to the old one. You can use  yt-dlp 2021.12.01
to download talks for now.
Playlist and series use the new format but the extractor fails at the individual video extraction step.

**Comment by trassshhub** [comment]
TED has switched back to the new version and the new extractor is working again.

**Comment by wxolp** [comment]
https://github.com/ytdl-org/youtube-dl/issues/30561

**Comment by pukkandan** [comment]
Closing since it's working now. Can re-open (and add fallback in code) if it happens again
