### ISSUE TITLE
smallest suggestion :-): Small addition to the help text for --dump-json

### ISSUE THREAD

**Issue by schittli** [yt-dlp/yt-dlp#2492]
### Checklist

- [X] I'm reporting a feature request
- [X] I've verified that I'm running yt-dlp version **2022.01.21**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

Good evening

I stumbled across this help text for `--dump-json`:

> Quiet, but print JSON information for each
> video. Simulate unless --no-simulate is
> used. See "OUTPUT TEMPLATE" for a
> description of available keys

I expected to get one JSON information for each Video and the result is collected in a JSON Array - but that's wrong.

Therefore I propose to slightly change the help text to describe the result more precise, for example:

_Quiet, **but per video, one line with its JSON 
information is printed to StdOut.**
Simulate unless --no-simulate is used. 
See "OUTPUT TEMPLATE" for a
description of available keys_

Thanks a lot for your great work!
Kind regards,
Thomas

**Comment by pukkandan** [comment]
```
    -j, --dump-json                  Quiet, but print JSON information for each
                                     video. Simulate unless --no-simulate is
                                     used. See "OUTPUT TEMPLATE" for a
                                     description of available keys
    -J, --dump-single-json           Quiet, but print JSON information for each
                                     url or infojson passed. Simulate unless
                                     --no-simulate is used. If the URL refers to
                                     a playlist, the whole playlist information
                                     is dumped in a single line
```

It explicitly states **for each video**
