### ISSUE TITLE
Unable to download videos from Douyu

### ISSUE THREAD

**Issue by Zythrickal** [yt-dlp/yt-dlp#2494]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.01.21**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Australia

### Description

Looking to download some League of Legends videos on Douyu but it appears to be broken.

### Verbose log

```shell
D:\>yt-dlp -vU "https://v.douyu.com/show/aRbBv32gjXoW6PYV"
[debug] Command-line config: ['-vU', 'https://v.douyu.com/show/aRbBv32gjXoW6PYV']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.01.21 [f20d607] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] exe versions: ffmpeg 4.4-full_build-www.gyan.dev (setts), ffprobe 4.4-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.01.21, Current version: 2022.01.21
yt-dlp is up to date (2022.01.21)
[debug] [DouyuShow] Extracting URL: https://v.douyu.com/show/aRbBv32gjXoW6PYV
[DouyuShow] aRbBv32gjXoW6PYV: Downloading webpage
ERROR: [DouyuShow] aRbBv32gjXoW6PYV: Unable to extract room info; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
  File "yt_dlp\extractor\common.py", line 612, in extract
  File "yt_dlp\extractor\douyutv.py", line 153, in _real_extract
  File "yt_dlp\extractor\common.py", line 1186, in _search_regex


D:\>
```

**Comment by Ashish0804** [comment]
Site changed completely.
Even fixing the regex won't fix error that come after that.
The api returns `视频已删除` 

Extractor needs a complete rewrite.
