### ISSUE TITLE
How do I download by id with a specific extractor?

### ISSUE THREAD

**Issue by tezlm** [yt-dlp/yt-dlp#2496]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

If I have a soundcloud track id, how would I get yt-dlp to download it? I only have the id and know that it's from soundcloud.

**Comment by MinePlayersPE** [comment]
try `https://api-v2.soundcloud.com/tracks/TRACK_ID`

**Comment by tezlm** [comment]
cool, it works
