### ISSUE TITLE
[TwitCasting] Title contains a lot of space

### ISSUE THREAD

**Issue by HitomaruKonpaku** [yt-dlp/yt-dlp#2497]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.01.21**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

When download TwitCasting live with `%(title)s` in output, title has a lot of space which could lead to error due to file length > 255

Can reproduce by any live

---

**Expected:**

```
[NA][NA] しょけんさんください！！ 最強にかわいい配信！ 2022-01-26 14_37 (718518443).mp4
```

**Actual:**

```
[NA][NA] しょけんさんください！！                                                                    最強にかわいい配信！ 2022-01-26 14_37 (718518443).mp4
```

---

I put the image since markdown eat all the space

![image](https://user-images.githubusercontent.com/9608105/151123002-7ed0dbae-2d66-4e39-b3ee-17e6ee2a350b.png)

### Verbose log

```shell
[debug] Command-line config: ['-vU', 'https://twitcasting.tv/kagu__2525']
[debug] Portable config "E:\YouTube\yt-dlp.conf": ['--console-title', '--no-playlist', '--hls-use-mpegts', '--no-continue', '--no-part', '--cookies', './cookies.txt', '--output', './download/[%(uploader)s][%(upload_date)s] %(title)s (%(id)s).%(ext)s', '--write-info-json', '--write-thumbnail']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.01.21 [f20d607] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.22000-SP0
[debug] exe versions: ffmpeg 2021-07-11-git-79ebdbb9b9-full_build-www.gyan.dev (setts), ffprobe 2021-07-11-git-79ebdbb9b9-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.01.21, Current version: 2022.01.21
yt-dlp is up to date (2022.01.21)
[debug] [TwitCastingLive] Extracting URL: https://twitcasting.tv/kagu__2525
[TwitCastingLive] Downloading live video of user kagu__2525. Pass "https://twitcasting.tv/kagu__2525/show" to download the history
[TwitCastingLive] kagu__2525: Downloading webpage
[debug] [TwitCasting] Extracting URL: https://twitcasting.tv/kagu__2525/movie/718518443
[TwitCasting] 718518443: Downloading webpage
[TwitCasting] 718518443: Downloading live info
[TwitCasting] 718518443: Downloading m3u8 information
[TwitCasting] 718518443: Downloading source quality m3u8
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: best/bestvideo+bestaudio
[info] 718518443: Downloading 1 format(s): ws-main
[info] Downloading video thumbnail 0 ...
[info] Writing video thumbnail 0 to: download\[NA][NA] しょけんさんください！！                                                                    最強にかわいい配信！ 2022-01-26 14_37 (718518443).jpg
[info] Writing video metadata as JSON to: download\[NA][NA] しょけんさんください！！                                                                    最強にかわいい配信！ 2022-01-26 14_37 (718518443).info.json
[debug] Invoking downloader on "wss://202-239-41-12.twitcasting.tv/tc.edge/v1/streams/718518443.672.96/fmp4"
[download] Destination: download\[NA][NA] しょけんさんください！！                                                                    最強にかわいい配信！ 2022-01-26 14_37 (718518443).mp4
[debug] ffmpeg command line: ffmpeg -y -loglevel verbose -i - -c copy -f mp4 "file:download\[NA][NA] しょけんさんください！！
                         最強にかわいい配信！ 2022-01-26 14_37 (718518443).mp4"
```

**Comment by Ashish0804** [comment]
TBF, that's how it is in the webpage.
never worked on the site before but changing this
```py
        title = (clean_html(get_element_by_id('movietitle', webpage))
                 or self._html_search_meta(['og:title', 'twitter:title'], webpage, fatal=True))
```
to
```py
        title = self._html_search_meta(['og:title', 'twitter:title'], webpage, fatal=True) or clean_html(get_element_by_id('movietitle', webpage))
```
Should fix this.

**Comment by Lesmiscore** [comment]
I guess it's caused by "bug" in `clean_html` rather than Extractor itself. On HTML, when you paste the "actual title" as a text (e.g. in `<p>`), only one space remains for consecutive ones, hence "expected title" shows up on the browsers.

**Comment by nyuszika7h** [comment]
@Ashish0804 You should remove `fatal=True`, otherwise it will never fall back to `movietitle` if the `<meta>` extraction fails.

**Comment by Ashish0804** [comment]
@Lesmiscore so adding `html = re.sub(r'\s{2,}', ' ', html)` to `clean_html` is the correct way to solve this issue?

**Comment by Lesmiscore** [comment]
@Ashish0804 `html = re.sub(r'\s+', ' ', html)`

**Comment by dirkf** [comment]
Eg, adapt the existing logic that changes newline to space and then adds a newline for each `<br>` and `</p><p>` (same for yt-dl):
```
     # Newline vs <br />
-    html = html.replace('\n', ' ')
-    html = re.sub(r'(?u)\s*<\s*br\s*/?\s*>\s*', '\n', html)
-    html = re.sub(r'(?u)<\s*/\s*p\s*>\s*<\s*p[^>]*>', '\n', html)
+    html = re.sub(r'\s+', ' ', html)
+    html = re.sub(r'(?u)\s?<\s?br\s?/?\s?>\s*', '\n', html)
+    html = re.sub(r'(?u)<\s?/\s?p\s?>\s?<\s?p[^>]*>', '\n', html)
     # Strip html tags
```
Merging the last two patterns might be a performance improvement but I guess not worthwhile even if so for the length of text normally passed to `clean_html()`.

I wonder how many other patterns ought to have `(?u)` and don't.

**Comment by pukkandan** [comment]
`(?u)` is a no-op in python3
