### ISSUE TITLE
[viki] bad request, unable to download

### ISSUE THREAD

**Issue by svtoshi** [yt-dlp/yt-dlp#2499]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.01.21**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Poland

### Description

Downloading from Viki has stopped working. I've tried many different dramas but to no avail.

### Verbose log

```shell
[debug] Command-line config: ['-vU', 'https://www.viki.com/tv/32240c-the-legend-of-the-blue-sea', '--playlist-items', '1', '--username', 'PRIVATE', '--password', 'PRIVATE']
[debug] Encodings: locale cp1250, fs utf-8, out utf-8, err utf-8, pref cp1250
[debug] yt-dlp version 2022.01.21 [f20d607] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] exe versions: ffmpeg 4.4.1-essentials_build-www.gyan.dev (setts), ffprobe 4.4.1-essentials_build-www.gyan.dev
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.01.21, Current version: 2022.01.21
yt-dlp is up to date (2022.01.21)
[viki:channel] Logging in
[debug] [viki:channel] Extracting URL: https://www.viki.com/tv/32240c-the-legend-of-the-blue-sea
[viki:channel] 32240c: Downloading channel JSON
[download] Downloading playlist: The Legend of the Blue Sea
[viki:channel] 32240c: Downloading Episodes JSON page 1
[viki:channel] playlist The Legend of the Blue Sea: Downloading 1 videos
[download] Downloading video 1 of 1
[viki] Logging in
[debug] [viki] Extracting URL: https://www.viki.com/videos/1115637v
[viki] 1115637v: Downloading video JSON
[viki] 1115637v: Downloading video streams JSON
ERROR: [viki] 1115637v: viki said: Bad request
  File "yt_dlp\extractor\common.py", line 612, in extract
  File "yt_dlp\extractor\viki.py", line 255, in _real_extract
  File "yt_dlp\extractor\viki.py", line 78, in _call_api
  File "yt_dlp\extractor\viki.py", line 86, in _raise_error

[download] Finished downloading playlist: The Legend of the Blue Sea
```

**Comment by pukkandan** [comment]
Could you check if the video is Kokowa https://github.com/yt-dlp/yt-dlp/issues/1379#issuecomment-950114372

**Comment by svtoshi** [comment]
It's not, just standard VikiPass

**Comment by LITUATUI** [comment]
Free TV shows are also not working, so you don't need an account to test.

```
yt-dlp -F https://www.viki.com/videos/1101211v-reply-1988-episode-1
[viki] 1101211v: Downloading video JSON
[viki] 1101211v: Downloading video streams JSON
ERROR: [viki] 1101211v: viki said: Bad request
```

**Comment by snowywish** [comment]
I'm facing same issues

**Comment by digiotaku** [comment]
Here too:  
https://www.viki.com/tv/37490c-invisible-life
ERROR: [viki] 1175823v: viki said: Bad request

**Comment by zackmark29** [comment]
```
{'vcode': 6400, 'error': 'Bad request', 'details': 'invalid drm type'
```
Unfortunately, it's already patched. They already removed the drm type/tag for non-drm content.
I don't think so if there will be another method for non-drm.

**Comment by pukkandan** [comment]
@zackmark29 Can you confirm whether both given URLs are DRMed in browser?

**Comment by bbibbimiau** [comment]
I'm facing the same problem :( . I think that there must be another method because I use a website to watch dramas and it offers the option  to download them giving you the non-drm hls link. It's sad that this doesn't work anymore because I prefer to download them in batch using yt-dlp.

The website is here if someone wants to check https://www.reddit.com/r/koreanvariety/comments/723mtd/i_created_this_website_that_streams_korean_shows/

**Comment by BLSTR13** [comment]
same problem here, also bad request

**Comment by pukkandan** [comment]
@bbibbimiau Don't promote piracy sites here!
