### ISSUE TITLE
Permission denied error after update using yt-dlp -U // Update command removes execute permissions

### ISSUE THREAD

**Issue by Sono-Gomorrha** [yt-dlp/yt-dlp#250]
## Checklist

- [ ] I'm reporting a broken site support issue
- [X] I've verified that I'm running yt-dlp version **2021.04.11**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar bug reports including closed ones
- [X] I've read bugs section in FAQ

## Verbose log

```
I omitted this, as it will only give me the latest output of yt-dlp, which is however, not being able to be accessed (see description below)

```

## Description

Today I looked at the folder my downloads go into and saw no new files. I checked the logs on the machine I'm running yt-dlp at (a LXC container based on Ubuntu) and found Permission Denied errors for yt-dlp. 

```
root@youtube-dl:/mnt/youtube-dl/yt-archive# /usr/local/bin/yt-dlp
-bash: /usr/local/bin/yt-dlp: Permission denied
```

I run a cronjob daily to update yt-dlp to the latest version, but I have the same issue after doing a manual update. This is the cronjb:

> 7 6 * * * /usr/local/bin/yt-dlp -U

I verified the permissions and indeed excecute permissions were missing:

> root@youtube-dl:/mnt/youtube-dl/yt-archive# ll /usr/local/bin
> total 3676
> drwxr-xr-x  2 root root    4096 Mar  4 06:07 ./
> drwxr-xr-x 10 root root    4096 Apr 25  2020 ../
> -rwxr-xr-x  1 root root 1838308 Apr 18 06:05 youtube-dl*
> -rw-r--r--  1 root root 1913571 Mar  4 06:07 yt-dlp
> root@youtube-dl:/mnt/youtube-dl/yt-archive# chmod a+rx /usr/local/bin/yt-dlp
> root@youtube-dl:/mnt/youtube-dl/yt-archive# ll /usr/local/bin
> total 3676
> drwxr-xr-x  2 root root    4096 Mar  4 06:07 ./
> drwxr-xr-x 10 root root    4096 Apr 25  2020 ../
> -rwxr-xr-x  1 root root 1838308 Apr 18 06:05 youtube-dl*
> -rwxr-xr-x  1 root root 1913571 Mar  4 06:07 yt-dlp*

I then tried a manual update and had the same issue again:

> root@youtube-dl:/mnt/youtube-dl/yt-archive# /usr/local/bin/yt-dlp -U
> Current Build Hash 374040b051456da197f296e774b1604d9fec8eef4910f90b90a92d83a0022e52
> Updating to version 2021.04.11 ...
> Updated yt-dlp. Restart yt-dlp to use the new version.
> root@youtube-dl:/mnt/youtube-dl/yt-archive# ll /usr/local/bin
> total 3712
> drwxr-xr-x  2 root root    4096 Apr 18 12:15 ./
> drwxr-xr-x 10 root root    4096 Apr 25  2020 ../
> -rwxr-xr-x  1 root root 1838308 Apr 18 06:05 youtube-dl*
> -rw-r--r--  1 root root 1953369 Apr 18 12:15 yt-dlp

Like stated above, the machine is a LXC container, files are being downloaded to a network share, so nothing special there.

**Comment by pukkandan** [comment]
This was a known issue (https://github.com/yt-dlp/yt-dlp/issues/133) in an older version of yt-dlp. Do you know which version you updated from?

**Comment by Sono-Gomorrha** [comment]
Unfortunately no I don't know my old version. But I had the container dormant for some time, so I'm pretty confident it might be the same as in the one mentioned. I will close this issue and reopen it if necessary.
