### ISSUE TITLE
format counting error

### ISSUE THREAD

**Issue by chrizilla** [yt-dlp/yt-dlp#2504]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.01.21**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

## Description

There seems to be a minor bug in the format count:

```
actual result:   [info] dJdaI3pCowU: Downloading 1 format(s): 248+251
expected result: [info] dJdaI3pCowU: Downloading 2 format(s): 248+251

```
## Verbose log

```shell
[debug] Command-line config: ['SaeLMWqgYKM', '-v', '--ignore-config']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.01.21 [f20d607] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] exe versions: ffmpeg N-105208-gb24f0c82b3-20220108 (setts), ffprobe N-105208-gb24f0c82b3-20220108
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [youtube] Extracting URL: SaeLMWqgYKM
[youtube] SaeLMWqgYKM: Downloading webpage
[youtube] SaeLMWqgYKM: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] SaeLMWqgYKM: Downloading 1 format(s): 248+251
[debug] Invoking downloader on "https://rr4---sn-h0jeln7e.googlevideo.com/videoplayback?expire=1643267977&ei=KfPxYeiNH4PN1gLD5YcY&ip=91.119.221.247&id=o-AB7kXbuh2EsqNC3uPGxsofDV8gODpHY5iblVw8RVODek&itag=248&source=youtube&requiressl=yes&mh=rm&mm=31%2C29&mn=sn-h0jeln7e%2Csn-h0jeened&ms=au%2Crdu&mv=m&mvi=4&pl=18&initcwndbps=1738750&vprv=1&mime=video%2Fwebm&gir=yes&clen=164466009&dur=583.600&lmt=1643186171102058&mt=1643245293&fvip=4&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=5535434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRgIhAOUeYR7zvlzmSDuKtUNwX_PVC6EMOikoyCzABDKFstxTAiEAoj4NDLux48p3i7qK28QVrN7sFxM4ZNJE4lrWtdkh9Ns%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgP5KU3XoM5SJhdKpuBACirPGduKYjaBm4KIOYnzxbIlACIQD205f5e1C5pnu0njI8Z1vYTZHBe5CafsQBlaEqGqjA6g%3D%3D"
[download] Destination: Denis Shapovalov Press Conference (QF) _ Australian Open 2022 [SaeLMWqgYKM].f248.webm
[download]   0.2% of 156.85MiB at 238.04KiB/s ETA 11:13
```

**Comment by Lesmiscore** [comment]
It's normal. That's a "merged format" which will download into 1 file. If you specify `-f bv,ba` for example, it counts as 2 since it'll be no merged formats.

**Comment by chrizilla** [comment]
`-F` says _"Available formats for SaeLMWqgYKM:"_
I assume each subsequent line counts as 1 format.
If 248+251 is selected, then 2 formats are downloaded and merged into 1 file.

> That's a "merged format" which will download into 1 file. If you specify -f bv,ba for example, it counts as 2 since it'll be no merged formats.

The former results in 1 file, the latter in 2 files.
To me this sounds like counting files rather than formats.

**Comment by pukkandan** [comment]
Lesmi is right
