### ISSUE TITLE
Documented "--print" string default is incorrect

### ISSUE THREAD

**Issue by mbish** [yt-dlp/yt-dlp#2511]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.01.21**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

The default formatting string listed in the REAME and man pages is incorrect instead the title appears to be filtered (`S`) by default. I'm on arch linux.

```
 $ yt-dlp --no-download --print "%(title)s [%(id)s].%(ext)s" https://www.youtube.com/watch\?v\=MaobMHescwg                                                                         
Heidegger: Being and Time [MaobMHescwg].webm
```
The video title after actually downloading the video is
```
Heidegger - Being and Time [MaobMHescwg].webm
```
I think the default should be shown as `%(title)S [%(id)s].%(ext)s"` in the documentation.

### Verbose log

```shell
[debug] Command-line config: ['-v', '--no-download', '--print', '%(title)s [%(id)s].%(ext)s', 'https://www.youtube.com/watch?v=MaobMHescwg']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.01.21 [f20d607b0]
[debug] Python version 3.10.1 (CPython 64bit) - Linux-5.16.1-arch1-1-x86_64-with-glibc2.33
[debug] exe versions: ffmpeg 4.4.1 (setts), ffprobe 4.4.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=MaobMHescwg
[youtube] MaobMHescwg: Downloading webpage
[youtube] MaobMHescwg: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] MaobMHescwg: Downloading 1 format(s): 248+251
Heidegger: Being and Time [MaobMHescwg].webm
```

**Comment by pukkandan** [comment]
Filenames are always sanitized. Otherwise the files can't be created! This is the case not just for the default outtmpl, but to any custom one given by the user. `-o %(something)s --print filename` and `--print %(something)s` will give different results. 

The `S` exists just so that you can use the same sanitization function in `--print`. Even the description of `S` says sanitize **as filename** implying filenames are always sanitized with this.
