### ISSUE TITLE
apt doesn't keep track of latest version

### ISSUE THREAD

**Issue by HalvorRaknes** [yt-dlp/yt-dlp#2514]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

Yesterday I came online and the first thing I did was to run `sudo apt upgrade yt-dlp`. At the time I had a version 2021-12-27 or something similar. Apt then told me I had the latest version and didn't need to upgrade,

I run Linux Mint 20.3 and as it happened the gui Update Manager ran at the same time, and it told me I could upgrade to version 2022.01.21, which I did using the Upgrade Manager.

I have never before experienced the Upgrade Manager telling me about an available upgrade for yt-dlp. Perhaps this is a new interaction. In any case I appreciate it since that's the most dead-sure way of catching new upgrades and being up-to-date.

**Comment by pukkandan** [comment]
You should ask the people who make apt packages. They are not maintained by me (and I am not going to maintain for the hundreds of PMs)

**Comment by HalvorRaknes** [comment]
PMs?

**Comment by pukkandan** [comment]
Package managers

**Comment by pukkandan** [comment]
To be fair to them, yt-dlp tends to break a lot due to external factors. So it needs frequent updates and is not really suitable for any manually maintained PMs - especially ones that don't go by rolling release models. Even so, a lot of devs do good job maintaining the packages (brew, AUR etc).

But at the end, I strongly recommend just installing through PIP or the provided release. The release binary has a self-update mechanism. So you are guarenteed to always be at the latest as long as you put a `-U` in the config. Similarly, the pip release is made automatically as part of the workflow and so is always guaranteed to be up to date

**Comment by pukkandan** [comment]
No idea

**Comment by HalvorRaknes** [comment]
OK, but you referred to using PIP as the best way to go about staying updated. Could you give the simple command line to do the update check and upgrade with PIP? I know I have had some issue trying it in the past.

**Comment by pukkandan** [comment]
https://github.com/yt-dlp/yt-dlp#with-pip

**Comment by HalvorRaknes** [comment]
But seeing as I already have yt-dlp installed. Wouldn't running PIP now mess up stuff?

**Comment by pukkandan** [comment]
You'll end up with both versions installed... or, you can just uninstall the other version

**Comment by HalvorRaknes** [comment]
If I have two versions installed at the same time, which one is called when I run yt-dlp from the command line? Surely not both? How does one distinguish between them?

**Comment by pukkandan** [comment]
depends on how your PATH is set up

These questions really have nothing to do with yt-dlp and is better asked in some linux forums

**Comment by HalvorRaknes** [comment]
OK. Thank you for being patient!
