### ISSUE TITLE
Pytrhon2 support

### ISSUE THREAD

**Issue by wellinton-capixaba** [yt-dlp/yt-dlp#2516]
### Checklist

- [X] I'm reporting a feature request
- [X] I've verified that I'm running yt-dlp version **2022.01.21**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

I tried to run yt-dlp, and received: "/usr/bin/env: python3: No such file or directory"

Why it does not support Python 2 as youtube-dl? This is a massive setback for me, I am not sure the sacrifice necessary to have Python 3 running on my system (massive hard disk space used, plus the time to compile and install it every time I reinstall the OS) is enough to justify the gains of using it instead of youtube-dl + download websites.

**Comment by pukkandan** [comment]
Python2 support was dropped months back and will not be added back
