### ISSUE TITLE
[zoom] add support to downloading screen recording

### ISSUE THREAD

**Issue by Mipsters** [yt-dlp/yt-dlp#2523]
### Checklist

- [X] I'm reporting a site feature request
- [X] I've verified that I'm running yt-dlp version **2022.01.21**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

worldwide

### Example URLs

I have access to multiple zoom recordings that are relevant to this feature, I am willing to share credentials although I plan to implement this feature by myself

### Description

the current zoom extractor always download the camera recording, if a zoom meeting contains a screen share it will not be downloaded
I want to add support to download only the screen share, or both
I managed to implement this feature in youtube-dl already, but since then I learned of yt-dlp and prefer to implement this here
I'm opening this issue as described in [Adding new feature or making overarching changes](https://github.com/Mipsters/yt-dlp/blob/master/CONTRIBUTING.md#adding-new-feature-or-making-overarching-changes)

the way I see it, this feature includes:
* some way of choosing what to download between these three options (these are zoom's code terms)
  * `view` (the camera recording only, default value and current behavior)
  * `share` (the screen share video only)
  * `both` (this is a term I made up, its debatable)
    * the two videos will downloaded as a playlist, with the `view` as the first and `share` as the second
* if share is selected (whether in `both` or `share`) but the meeting does not contain a share video, it will log a non fatal warning, revert to the default option and continue

### Verbose log

```shell
[debug] Command-line config: ['-vU']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.01.21 [f20d607b0]
[debug] Python version 3.10.1 (CPython 64bit) - Windows-10-10.0.22000-SP0
[debug] exe versions: ffmpeg 4.4.1-full_build-www.gyan.dev (setts), ffprobe 4.4.1-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.01.21, Current version: 2022.01.21
yt-dlp is up to date (2022.01.21)
```

**Comment by pukkandan** [comment]
You can simply return them as different formats of the same video. Users can select what to download using `-f`

**Comment by Mipsters** [comment]
> You can simply return them as different formats of the same video. Users can select what to download using `-f`

I may not understand the formats correctly, but isn't it suppose to be for different versions of the same video?
in this case, the audio stream is the same for both of them, but there are two different video streams
in what way do you suggest this will this be represented in the -f parameter?

**Comment by pukkandan** [comment]
See https://github.com/yt-dlp/yt-dlp/issues/389

**Comment by p2635** [comment]
Sorry I'm late to the party, is this feature available for use? How do I save both the screen recording and camera recording?

**Comment by Mipsters** [comment]
> Sorry I'm late to the party, is this feature available for use? How do I save both the screen recording and camera recording?

Unless it was removed, then yes it's available
Zoom now require some proof of work for logging in, so if the recording require a password you'll need to manually enter the password in the browser and copy the session cookie and add it to the header in yt-dlp

To list all available formats use `-F`, then it should be listed there

My bad that the issue wasn't closed 😅
After so long I feel like I should check that it still works before closing it
I'll see when I have the time
