### ISSUE TITLE
Globoplay not working

### ISSUE THREAD

**Issue by pootz10** [yt-dlp/yt-dlp#2524]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.01.21**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Brazil

### Description

Hello, I use a .bat file to usually download videos, some months ago I tried to download a globoplay link and the return was DRM protected, I think that kind of content wasn't allowed or possible to be downloaded, then I didn't complain about it or thought "it's not working I should report it". Now the error is completely differently and the message encourage me to report it

> No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update.

> D:\Users\Pootz\Desktop\youtube>yt-dlp --version
> 2022.01.21

Today I was trying to download this video [https://globoplay.globo.com/v/10248083/](https://globoplay.globo.com/v/10248083/) which plays fine even on my firefox 96.0.3 private window (I meant not logged in, on an account) even so I have cookies.txt accounts for every download I use to do.

Differently from those cases:
[https://github.com/yt-dlp/yt-dlp/issues/991](https://github.com/yt-dlp/yt-dlp/issues/991)
[https://github.com/yt-dlp/yt-dlp/issues/1132](https://github.com/yt-dlp/yt-dlp/issues/1132)
I've searched and seen now, that were reported here.

I was able to download it on [downloadHelper extension](https://www.downloadhelper.net/) but it was on a poor quality. The good ones I wasn't able to get it.

Not even the formats ( -F ) shows any available download quality, but the video plays fine.

[Here is another link where the globoplay video is embed](https://ge.globo.com/futebol/copa-do-mundo/eliminatorias-america-do-sul/jogo/27-01-2022/equador-brasil.ghtml)

Thanks in advance.

### Verbose log

```shell
D:\Users\Pootz\Desktop\youtube>yt-dlp --console-title -f best -vU https://globoplay.globo.com/v/10248083/
[debug] Command-line config: ['--console-title', '-f', 'best', '-vU', 'https://globoplay.globo.com/v/10248083/']
[debug] User config "D:\Users\Pootz\AppData\Roaming\yt-dlp\config.txt": ['-f', 'bestvideo[height<=480][ext=mp4]+bestaudio[ext=m4a]/best[height<=480]', '-o', 'D:/Users/Pootz/Desktop/_%(title)s.%(ext)s', '--ffmpeg-location', 'D:/Program Files/Combined Community Codec Pack 64bit/ffmpeg-20200617-0b3bd00-win64-static/bin', '--cookies', 'cookies.txt']
WARNING: "-f best" selects the best pre-merged format which is often not the best option.
         To let yt-dlp download and merge the best available formats, simply do not pass any format selection.
         If you know what you are doing and want only the best pre-merged format, use "-f b" instead to suppress this warning
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.01.21 [f20d607] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.17763-SP0
[debug] exe versions: ffmpeg n4.3.2-160-gfbb9368226, ffprobe n4.3.2-160-gfbb9368226
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.01.21, Current version: 2022.01.21
yt-dlp is up to date (2022.01.21)
[debug] [Globo] Extracting URL: https://globoplay.globo.com/v/10248083/
[Globo] 10248083: Downloading JSON metadata
[Globo] 10248083: Downloading security hash for 10248083
[Globo] 10248083: Downloading m3u8 information
WARNING: [Globo] Failed to download m3u8 information: HTTP Error 403: Forbidden
ERROR: [Globo] 10248083: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1367, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1451, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1503, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2413, in process_video_result
  File "yt_dlp\YoutubeDL.py", line 954, in raise_no_formats
yt_dlp.utils.ExtractorError: [Globo] 10248083: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
```

**Comment by glaucoheitor** [comment]
Hey @pukkandan, I don't think this is related to geo-blocking as I'm having the same issue with a video that does't have that kind of block. In my case I'm using cookies from browser as it's a video that require the user to be logged in.

Example: https://globoplay.globo.com/v/10250970/programa/?s=0s

**Comment by pukkandan** [comment]
The label is to indicate to potential devs that the content is geo-blocked; not that the issue is due to geo-blocking (if so, issue would have been closed). If you can provide free example URL that is not geo-blocked, the label can be removed

**Comment by Bricio** [comment]
If you use saved cookie from browser it works.

![image](https://user-images.githubusercontent.com/216170/151910112-68f22c3c-f7c7-4ab7-9e37-cb30764eaaf8.png)

> D:\ytdlp>yt-dlp.exe -v --cookies cookies.txt  "https://globoplay.globo.com/v/10248083/"
[debug] Command-line config: ['-v', '--cookies', 'cookies.txt', 'https://globoplay.globo.com/v/10248083/']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8 (No ANSI), err utf-8 (No ANSI), pref cp1252
[debug] yt-dlp version 2022.01.21 [f20d607] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [Globo] Extracting URL: https://globoplay.globo.com/v/10248083/
[Globo] 10248083: Downloading JSON metadata
[Globo] 10248083: Downloading security hash for 10248083
[Globo] 10248083: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: best/bestvideo+bestaudio
[info] 10248083: Downloading 1 format(s): hls-2735
[debug] Invoking downloader on "https://vod-as-03-30.video.globo.com/r90_720/v0/c8/82/df/10248083_df4d8fd36481c57f24735d8760755383392237ac/10248083-U369wJY-manifest.ism/10248083-U369wJY-manifest-audio_por=128004-video_por=2452000.m3u8?hls_client_manifest_version=4"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 89
[download] Destination: Melhores momentos - Equador 1 x 1 Brasil pelas Eliminatórias da Copa do Mundo 2022 [10248083].mp4
[download] 100% of 169.49MiB in 00:14
WARNING: 10248083: Possible MPEG-TS in MP4 container or malformed AAC timestamps. Install ffmpeg to fix this automatically

**Comment by pootz10** [comment]
I am using cookies.txt .
Please confirm to me, the cookies.txt goes inside yt-dlp.exe folder ?
I set my default commands on config.txt inside Roaming folder

Unless [the cookies firefox extension](https://github.com/lennonhill/cookies-txt) isn't taking the cookies right.

I enter the same command you enter and the result was the same, and I generated a fresh cookies.txt right now to avoid mistakes.

adding -F or -f best fails here too.

The cookies.txt generated file from globoplay has 44 lines counting from the first line `# Netscape HTTP Cookie File`

**Comment by Bricio** [comment]
That is what i did when it worked.

1. Add [FF extension](https://addons.mozilla.org/en-US/firefox/addon/cookies-txt/). I didn't have it. 
2. Allow FF extension to run on private window. 
3. Open new private window.
4. Open video link.
5. Pause the video.
6. Export "Current Site" cookies.
7. Save cookies.txt in the same folder as executable.
8. run command `yt-dlp.exe -v --cookies cookies.txt  "https://globoplay.globo.com/v/10248083/"`

but.... right now i did the same thing and didn't work.

Before start working I was trying other commands to download files returned on dev tools.

> yt-dlp.exe -v "https://v.glbimg.com/v0/c8/82/df/10248083_df4d8fd36481c57f24735d8760755383392237ac/10248083-360p_300k_h264-5a811a60-61fd-013a-fc0a-0242ac110005.mp4"
> yt-dlp.exe -v "https://vod-as-03-30.video.globo.com/r90_720/v0/c8/82/df/10248083_df4d8fd36481c57f24735d8760755383392237ac/10248083-U369wJY-manifest.ism/10248083-U369wJY-manifest-audio_por=128004-video_por=301000.m3u8?hls_client_manifest_version=4"
> yt-dlp.exe -v --cookies cookies.txt "https://vod-as-03-30.video.globo.com/r90_720/v0/c8/82/df/10248083_df4d8fd36481c57f24735d8760755383392237ac/10248083-U369wJY-manifest.ism/10248083-U369wJY-manifest-audio_por=128004-video_por=301000.m3u8?hls_client_manifest_version=4"
> yt-dlp.exe -v --cookies cookies.txt --force-generic-extractor  "https://vod-as-03-30.video.globo.com/r90_720/v0/c8/82/df/10248083_df4d8fd36481c57f24735d8760755383392237ac/10248083-U369wJY-manifest.ism/10248083-U369wJY-manifest-audio_por=128004-video_por=301000.m3u8?hls_client_manifest_version=4"

then suddenly, this commands started working. And I thought: dam i should have tried this at first.  

> yt-dlp.exe -v --cookies cookies.txt --force-generic-extractor  "https://vod-as-03-30.video.globo.com/r90_720/v0/c8/82/df/10248083_df4d8fd36481c57f24735d8760755383392237ac/10248083-U369wJY-manifest.ism/10248083.m3u8?h=0411643687495730550659316436859021843271116mJtQk4QY7m5sZaAUMxV99Q&k=html5&a=A&u=BR~"
> yt-dlp.exe -v --cookies cookies.txt --force-generic-extractor  "https://vod-as-03-30.video.globo.com/r90_720/v0/c8/82/df/10248083_df4d8fd36481c57f24735d8760755383392237ac/10248083-U369wJY-manifest.ism/10248083.m3u8?h=0411643687495730550659316436859021843271116mJtQk4QY7m5sZaAUMxV99Q\u0026k=html5\u0026a=A\u0026u=BR~"
> yt-dlp.exe -v --cookies cookies.txt  "https://globoplay.globo.com/v/10248083/"

I will try to investigate a little further to find out what was the turning point.

**Comment by pootz10** [comment]
As I thought, it's strange the issue be only here because I always used a .bat file  ( so the commands it's certainly not wrong) and cookies on config.txt

Maybe the same reason I could get it from downloadHelper extension I said on my main post, is the reason it worked for you.
The extension isn't able to download anymore too.

**Comment by Bricio** [comment]
I find out. 
Globo now uses cookies to grant access to manifest and video and changed the json format too.
It only worked before because i called --force-gerenic-extractor with correct cookies before calling the page with globo extractor.

I was able to fix it in my on local copy of yt-dlp, but i don't know if the code is correct for every case, or it can be done in better way.
Or how to test it.

![image](https://user-images.githubusercontent.com/216170/152020508-173784df-a391-441e-aa38-6d4ed3d51c69.png)

Can someone help me with this?

**Comment by pootz10** [comment]
If you want test the fix for new links
[https://globoplay.globo.com/v/10262289/](https://globoplay.globo.com/v/10262289/)
[https://globoplay.globo.com/v/10262174](https://globoplay.globo.com/v/10262174)
also not working.

**Comment by Bricio** [comment]
Fixing code already merged with main code, wait for next release or you can download right now using python version.

![image](https://user-images.githubusercontent.com/216170/152152441-ef8ec380-b40e-4a36-8a1f-8cc058ad879a.png)

**Comment by pootz10** [comment]
Thank you, I'll wait the next release.
