### ISSUE TITLE
Modifying `std_headers` in embedded YoutubeDL

### ISSUE THREAD

**Issue by pukkandan** [yt-dlp/yt-dlp#2526]
Well it is one way, but when handling multiple requests at once using multiple `YoutubeDL` instances in an multithreaded embedded environment makes the global setting not the best way to go forward. 

When using `YoutubeDL.extract_info` one can provide an `extra_info` dictionary which is used to handle the download request. One of the parameters that can be provided with that is `http_headers`. I use it explicitly to provide a `Referer` header to the video download. Sadly this additional dict is only important when it comes to downloading the actual video file, not for getting the redirections chain. 

Something to initialize the `YoutubeDL` class that would allow one to configure the headers used further on would be nice as global `std_headers` isn't always possible to use.

_Originally posted by @arandomliz in https://github.com/yt-dlp/yt-dlp/issues/2396#issuecomment-1024602677_

**Comment by pukkandan** [comment]
Let's not hijack #2396 and instead continue discussion about `std_headers` here.

I agree that the current method is bad design.

`extra_info` cannot be used for this purpose. It is a dict that is injected into the `info_dict` and is mostly for internal use. It has nothing to do with extractor code. The better way would be to allow headers to be passed in `params`

**Comment by arandomliz** [comment]
Good idea moving this into it's own issue. Thank you. 

Yes. I also think now that using `extra_info` isn't a good way. It's undocumented, internal use only, ...

Correct me if I'm wrong, but what I could see was that injecting the headers into the request when `YoutubeDL.urlopen` is called works really well as it is always called on a web request by the extractors. At this point one also has access to parameters provided to the used `YoutubeDL` instance. 

At least in my experiments overwriting this method and having `http_headers` as an input parameter at init, it worked well. Headers that will not be changed are the ones that download the final video / that are provided by the extractors, which is think is the right way of doing things as it would mean an internal order of for header priority of `extractor headers > get_params("http_headers") > std_headers`

**Comment by pukkandan** [comment]
> At least in my experiments overwriting this method and having http_headers as an input parameter at init, it worked well. Headers that will not be changed are the ones that download the final video / that are provided by the extractors

I dont understand exactly which part you mean. Can you provide a diff

**Comment by pukkandan** [comment]
This is what I am thinking to do

```diff
diff --git a/yt_dlp/utils.py b/yt_dlp/utils.py
index 2b33e1ec9..8a82def2f 100644
--- a/yt_dlp/utils.py
+++ b/yt_dlp/utils.py
@@ -1374,7 +1374,10 @@ class YoutubeDLHandler(compat_urllib_request.HTTPHandler):
         if url != url_escaped:
             req = update_Request(req, url=url_escaped)

-        for h, v in std_headers.items():
+        headers = std_headers.copy()
+        headers.update(self._params.get('http_headers', {}))
+
+        for h, v in headers.items():
             # Capitalize is needed because of Python bug 2275: http://bugs.python.org/issue2275
             # The dict keys are capitalized because of this bug by urllib
             if h.capitalize() not in req.headers:
```

**Comment by arandomliz** [comment]
I'm not sure whether `std_headers` need to be copied here tbh, as these headers will be added to the request further down the line. Otherwise you've the right idea (also see https://github.com/arandomliz/yt-dlp/commit/261dac83a4bdbbdfb3143973d23f77969ba71784)

```diff
index 24843c775..54713980f 100644
--- a/yt_dlp/YoutubeDL.py
+++ b/yt_dlp/YoutubeDL.py
@@ -3552,6 +3552,14 @@ class YoutubeDL(object):
         """ Start an HTTP download """
         if isinstance(req, compat_basestring):
             req = sanitized_Request(req)
+
+        headers = self.params.get("http_headers")
+        if isinstance(headers, dict):
+            for h, v in headers.items():
+                # see YoutubeDLHandler.http_request
+                if h.capitalize() not in req.headers:
+                    req.add_header(h, v)
+
         return self._opener.open(req, timeout=self._socket_timeout)
 
     def print_debug_header(self):
```

**Comment by arandomliz** [comment]
Wait sorry. You're overwritting `http_request` in `YoutubeDLHandler`. Does this class has access to the parameters provided to the `YoutubeDL` class? What I meant was overwritting the `urlopen` instance method in `YoutubeDL`

**Comment by pukkandan** [comment]
Untested: https://github.com/pukkandan/yt-dlp-dev/tree/features/std_headers

There is a known issue with the case sensitivity of headers which will need to be addressed

**Comment by arandomliz** [comment]
Excuse the stupid question, but how could I test it? Wouldn't I need to build it first or can I just install it with pip using the git URL?

**Comment by pukkandan** [comment]
You can just pip install. Or assuming u want to edit the code, better to pull with git

**Comment by pukkandan** [comment]
> But doesn't .capitalize already fix the issue of case sensitivity?

We need to take care of this every time wo dicts are merged. If the `std_headers` and `http_headers` have same key, but with diff case, the wrong header may be applied

**Comment by coletdjnz** [comment]
> > But doesn't .capitalize already fix the issue of case sensitivity?
> 
> We need to take care of this every time two dicts are merged. If the `std_headers` and `http_headers` have same key, but with diff case, the wrong header may be applied

Technically, this might not be worry since I believe the insertion order is preserved. We could use OrderedDict to be sure.

Alternatively, we could make a merge/update headers function. Or we could store headers in something like:
```python
from email.message import Message
class YDLHTTPHeaderStore(Message):
    def __init__(self, data=None):
        super().__init__()
        if data is not None:
            self.add_headers(data)

    def add_headers(self, data):
        for k, v in data.items():
            self.add_header(k, v)
            
    def replace_headers(self, data):
        for k, v in data.items():
            self.replace_header(k, v)

    def copy(self):
        return HTTPHeaderStore(self)
 ```
Note `Message` is already being used as the header store for HTTPResponse.headers.
But that might be a bit overkill for request headers.

**Comment by arandomliz** [comment]
Hmh. How does `addheader` of request work? Couldn't we just transform both dicts to lowercase, merge them and insert with that? This assumes `req.addheader` will fix the casing.

**Comment by pukkandan** [comment]
> Couldn't we just transform both dicts to lowercase, merge them and insert with that?

Yes, that would work, and is what I am planning to do for now.

coletdjnz is working an an overhaul of the network code. So his approach may be useful for long term
