### ISSUE TITLE
[Question] Is there a way to download all subtitles except a certain format?

### ISSUE THREAD

**Issue by louie-github** [yt-dlp/yt-dlp#253]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

I just tried out yt-dlp coming from the original youtube-dl. and I was surprised that adding `--all-subs` also downloaded live chat JSON. I've read through a bit of the relevant documentation and I feel like I now sort of understand this behavior.

That being said, how would I go downloading all subtitles (using `--all-subs` for example) but exempting a certain format (such as `live_chat`) from being downloaded? In general, I just want to be able to add `--all-subs` to download all subtitles from a video without having to check and specify each available format, but exempt `live_chat` from being downloaded as I usually don't need it.

Thank you so much for your time and I wish you all the best!

**Comment by pukkandan** [comment]
Currently not possible. The `live_chat` being considered as a subtitle is an annoying behavior imho, but this is how it was in youtube-dlc, and it is not possible to revert this without causing compatibility issues. (I know for a fact that quite a few people use scripts that download live_chat).

I'll see if it is possible to add an option to exclude a certain language. A syntax like `--sub-langs all,-live_chat` shouldn't be too hard to implement

**Comment by october262** [comment]
> Currently not possible. The `live_chat` being considered as a subtitle is an annoying behavior imho, but this is how it was in youtube-dlc, and it is not possible to revert this without causing compatibility issues. (I know for a fact that quite a few people use scripts that download live_chat).
> 
> I'll see if it is possible to add an option to exclude a certain language. A syntax like `--sub-langs all,-live_chat` shouldn't be too hard to implement

would it be possible to use the firefox addon called the stream detector
to download all the subs and just delete the ones that are not needed ??

**Comment by pukkandan** [comment]
From next release, `--sub-langs all,-live_chat` will work

**Comment by louie-github** [comment]
Well, that was an amazingly fast response. Thank you so much for your work, and I wish you all the best once again!
