### ISSUE TITLE
SponsorBlock segments are downloaded before verifying that the video will also be downloaded

### ISSUE THREAD

**Issue by db48x** [yt-dlp/yt-dlp#2536]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.01.21**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

yt-dlp downloads the SponsorBlock segment list for the video before it checks conditions such as --dateafter. This can result in thousands of api calls to SponsorBlock even when yt-dlp doesn’t end up downloading any videos. It slows yt-dlp down quite a bit and amplifies the traffic to SponsorBlock significantly.

### Verbose log

```shell
~/video/raw ~/video/raw
https://www.youtube.com/user/szyzyg/videos
[debug] Command-line config: ['--no-check-certificate', '--ignore-errors', '--console-title', '--write-description', '--write-annotations', '--write-info-json', '--no-write-playlist-metafiles', '--embed-metadata', '--sponsorblock-mark', 'all', '-o', '%(uploader)s/%(title)s - %(resolution)s [%(extractor)s;%(id)s;%(format_id)s].%(ext)s', '--no-mtime', '--download-archive', '.youtube-dl', '--playlist-reverse', '--match-filter', '!is_live', '--match-title', '', 'https://www.youtube.com/user/szyzyg/videos', '--dateafter', 'today-2years', '-vU']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8 (No ANSI), err utf-8 (No ANSI), pref UTF-8
[debug] yt-dlp version 2022.01.21 [f20d607b0] (zip)
[debug] Python version 3.9.9 (CPython 64bit) - Linux-5.15.11-100.fc34.x86_64-x86_64-with-glibc2.33
[debug] exe versions: ffmpeg N-82301-g1bbb18f, ffprobe N-82301-g1bbb18f
[debug] Optional libraries: Cryptodome, secretstorage, sqlite
[debug] Proxy map: {}
[debug] Loading archive file '.youtube-dl'
[22;0tLatest version: 2022.01.21, Current version: 2022.01.21
yt-dlp is up to date (2022.01.21)
[debug] [youtube:tab] Extracting URL: https://www.youtube.com/user/szyzyg/videos
[youtube:tab] szyzyg: Downloading webpage
[debug] [youtube:tab] Final URL: https://www.youtube.com/user/szyzyg/videos
[download] Downloading playlist: Scott Manley - Videos
[youtube:tab] UCxzC4EngIsMrPmbm6Nxvb-A page 1: Downloading API JSON
[youtube:tab] UCxzC4EngIsMrPmbm6Nxvb-A page 2: Downloading API JSON
…
[youtube:tab] UCxzC4EngIsMrPmbm6Nxvb-A page 81: Downloading API JSON
[youtube:tab] UCxzC4EngIsMrPmbm6Nxvb-A page 82: Downloading API JSON
[youtube:tab] playlist Scott Manley - Videos: Downloading 2478 videos
[download] Downloading video 1 of 2478
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=5gMCnvAnSKY
[youtube] 5gMCnvAnSKY: Downloading webpage
[youtube] 5gMCnvAnSKY: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
]0;yt-dlp SponsorBlock started[SponsorBlock] Fetching SponsorBlock segments
[debug] SponsorBlock query: https://sponsor.ajay.app/api/skipSegments/2a18?service=YouTube&categories=%5B%22poi_highlight%22%2C+%22outro%22%2C+%22intro%22%2C+%22filler%22%2C+%22sponsor%22%2C+%22interaction%22%2C+%22preview%22%2C+%22selfpromo%22%2C+%22music_offtopic%22%5D
[SponsorBlock] No segments were found in the SponsorBlock database
]0;yt-dlp SponsorBlock finished[debug] Default format spec: bestvideo*+bestaudio/best
[info] 5gMCnvAnSKY: Downloading 1 format(s): 243+251
[download] 2009-07-11 upload date is not in range 2020-01-29 - 9999-12-31
[download] Downloading video 2 of 2478
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=ANY6hDOfJVM
[youtube] ANY6hDOfJVM: Downloading webpage
[youtube] ANY6hDOfJVM: Downloading android player API JSON
[youtube] ANY6hDOfJVM: Downloading MPD manifest
[youtube] ANY6hDOfJVM: Downloading MPD manifest
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
]0;yt-dlp SponsorBlock started[SponsorBlock] Fetching SponsorBlock segments
[debug] SponsorBlock query: https://sponsor.ajay.app/api/skipSegments/386c?service=YouTube&categories=%5B%22poi_highlight%22%2C+%22outro%22%2C+%22intro%22%2C+%22filler%22%2C+%22sponsor%22%2C+%22interaction%22%2C+%22preview%22%2C+%22selfpromo%22%2C+%22music_offtopic%22%5D
[SponsorBlock] No segments were found in the SponsorBlock database
]0;yt-dlp SponsorBlock finished[debug] Default format spec: bestvideo*+bestaudio/best
[info] ANY6hDOfJVM: Downloading 1 format(s): 243+140
[download] 2009-08-02 upload date is not in range 2020-01-29 - 9999-12-31
[download] Downloading video 3 of 2478
…
```

**Comment by db48x** [comment]
Putting SponsorBlock in the “post_process” phase instead of “pre_process” fixes the problem for me, though I am not entirely sure how to test it effectively.

**Comment by pukkandan** [comment]
There are reasons why it is a pre-processor. It should not be moved to post. I will need to look into how to perform match-filter before it

**Comment by db48x** [comment]
The processing phases are not very well documented (POSTPROCESS_WHEN), but maybe add a new phase in between “before_dl” and “post_process”? Call it “after_match_filter” and run it just after the video passes all the filters, but before the video itself is downloaded.

**Comment by db48x** [comment]
Incidentally, I started add comments to POSTPROCESS_WHEN:

```python
# It is not very clear what order these steps happen in. This is my best guess.
POSTPROCESS_WHEN = {
    'pre_process',  # This appears to be prior to any significant work has been done
    'before_dl',    # This is immediately before retrieving video metadata
    'post_process', # This is apparently just after downloading video and audio,
                    # and if necessary combining them into a single file
    'after_video',  # It gets a bit confusing here.
    'after_move',   # I would say that this one is just after the downloaded
                    # files have been moved to their final location, just going
                    # by the name.
    'playlist'      # Your guess is as good as mine.
}
```

**Comment by pukkandan** [comment]
From README
```
    --use-postprocessor NAME[:ARGS]  ...
                                     The "when" argument determines when the
                                     postprocessor is invoked. It can be one of
                                     "pre_process" (after extraction),
                                     "before_dl" (before video download),
                                     "post_process" (after video download;
                                     default), "after_move" (after moving file
                                     to their final locations), "after_video"
                                     (after downloading and processing all
                                     formats of a video), or "playlist" (end of
                                     playlist). ...
```

>  run it just after the video passes all the filters, but before the video itself is downloaded.

That is just `before_dl`. Moving the sponsorblock to that stage is a reasonable compromise, but it will cause the same API request to be made multiple times when doing `-f f1,f2`. The real issue here is that match_filter is performed per format, while we want sponsorblock to be performed per video.

**Comment by db48x** [comment]
I missed that particular bit of documentation. It does help for a few of them, but it doesn’t explain very much. It especially doesn’t distinguish between “pre_process” and “before_dl”.


> That is just `before_dl`. Moving the sponsorblock to that stage is a reasonable compromise, but it will cause the same API request to be made multiple times when doing `-f f1,f2`. The real issue here is that match_filter is performed per format, while we want sponsorblock to be performed per video.

Moving SponsorBlock to “before_dl” was the first thing I tried, and it didn’t work, because it happens before `match_filter` is called.

FWIW, I am happy to have SponsorBlock called once per format, since that is at least a better outcome than calling it thousands of times for videos that aren’t even going to be downloaded.

**Comment by db48x** [comment]
It occurs to me to wonder if moving “before_dl” to just after `match_filter` would cause any other problems. There are two other processors that use that stage (`FFmpegSubtitlesConvertor` and `FFmpegThumbnailsConvertor`), and it seems logical for them to be skipped if the video itself is going to be skipped.

**Comment by YanisKyr** [comment]
Came over to ask how to avoid Fetching SponsorBlock segments when date check or other filters are negative?

I'll follow this thread so.

**Comment by db48x** [comment]
Thank you! :D
