### ISSUE TITLE
niconico new channel need support

### ISSUE THREAD

**Issue by lokilin** [yt-dlp/yt-dlp#2537]
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.01.21**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Example URLs

https://nicochannel.jp/mimimoto-ayaka/video/smRS96YpmDJr24YpWFZziG4L

https://hls-auth.cloud.stream.co.jp/mediaplaylist/smRS96YpmDJr24YpWFZziG4L/transcoded/jok04eygx1oyriw0_6k84wrqze2ng03ex_MSHouneiZZk8fHMtR5zpum_1_20220124-22-01-03_0_1080p.m3u8?session_id=9d547c74-f626-46d6-866d-df2b5c5d997f(session_id will change everytime)

### Description

niconico has released new channel servers and it can't download by yt-dlp now!
The sample video is free to watch but can't download.
I have tried default url and then yt-dlp show HTTP Error 404, Looks like couldn't find m3u8 file. 
And I use m3u8 direct link, then it show "ERROR: Incorrect AES key length (9 bytes)(Forbidden)" is can't access the site to get the key from uri in the m3u8 link.
Use cookies also didn't work.

Then I try Stream Recorder that it can capture video correctly.
So I think it need token to access the key but yt-dlp can't get it now.
Need help! Thank everyone!

### Verbose log

```shell
.\yt-dlp.exe -vU https://nicochannel.jp/mimimoto-ayaka/video/smRS96YpmDJr24YpWFZziG4L
[debug] Command-line config: ['-vU', 'https://nicochannel.jp/mimimoto-ayaka/video/smRS96YpmDJr24YpWFZziG4L']
[debug] Encodings: locale cp950, fs utf-8, out utf-8, err utf-8, pref cp950
[debug] yt-dlp version 2022.01.21 [f20d607] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.22000-SP0
[debug] exe versions: ffmpeg 4.4-full_build-www.gyan.dev (setts), ffprobe 4.4-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.01.21, Current version: 2022.01.21
yt-dlp is up to date (2022.01.21)
[debug] [generic] Extracting URL: https://nicochannel.jp/mimimoto-ayaka/video/smRS96YpmDJr24YpWFZziG4L
[generic] smRS96YpmDJr24YpWFZziG4L: Requesting header
WARNING: [generic] Could not send HEAD request to https://nicochannel.jp/mimimoto-ayaka/video/smRS96YpmDJr24YpWFZziG4L: HTTP Error 404: Not Found
[generic] smRS96YpmDJr24YpWFZziG4L: Downloading webpage
ERROR: [generic] Unable to download webpage: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output. (caused by <HTTPError 404: 'Not Found'>); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
  File "yt_dlp\extractor\common.py", line 730, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 3526, in urlopen
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 649, in http_error_default




.\yt-dlp.exe -vU https://hls-auth.cloud.stream.co.jp/mediaplaylist/smRS96YpmDJr24YpWFZziG4L/transcoded/jok04eygx1oyriw0_6k84wrqze2ng03ex_MSHouneiZZk8fHMtR5zpum_1_20220124-22-01-03_0_1080p.m3u8?session_id=45576c4f-1b32-4769-b645-100e7d05f8df
[debug] Command-line config: ['-vU', 'https://hls-auth.cloud.stream.co.jp/mediaplaylist/smRS96YpmDJr24YpWFZziG4L/transcoded/jok04eygx1oyriw0_6k84wrqze2ng03ex_MSHouneiZZk8fHMtR5zpum_1_20220124-22-01-03_0_1080p.m3u8?session_id=45576c4f-1b32-4769-b645-100e7d05f8df']
[debug] Encodings: locale cp950, fs utf-8, out utf-8, err utf-8, pref cp950
[debug] yt-dlp version 2022.01.21 [f20d607] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.22000-SP0
[debug] exe versions: ffmpeg 4.4-full_build-www.gyan.dev (setts), ffprobe 4.4-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.01.21, Current version: 2022.01.21
yt-dlp is up to date (2022.01.21)
[debug] [generic] Extracting URL: https://hls-auth.cloud.stream.co.jp/mediaplaylist/smRS96YpmDJr24YpWFZziG4L/transcoded/jok04eygx1oyriw0_6k84wrqze2ng03ex_MSHouneiZZk8fHMtR5zpum_1_20220124-22-01-03_0_1080p.m3u8?session_id=45576c4f-1b32-4769-b645-100e7d05f8df
[generic] jok04eygx1oyriw0_6k84wrqze2ng03ex_MSHouneiZZk8fHMtR5zpum_1_20220124-22-01-03_0_1080p: Requesting header
[debug] Identified a direct video link
[generic] jok04eygx1oyriw0_6k84wrqze2ng03ex_MSHouneiZZk8fHMtR5zpum_1_20220124-22-01-03_0_1080p: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] jok04eygx1oyriw0_6k84wrqze2ng03ex_MSHouneiZZk8fHMtR5zpum_1_20220124-22-01-03_0_1080p: Downloading 1 format(s): 0
[debug] Invoking downloader on "https://hls-auth.cloud.stream.co.jp/mediaplaylist/smRS96YpmDJr24YpWFZziG4L/transcoded/jok04eygx1oyriw0_6k84wrqze2ng03ex_MSHouneiZZk8fHMtR5zpum_1_20220124-22-01-03_0_1080p.m3u8?session_id=45576c4f-1b32-4769-b645-100e7d05f8df"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 367
[download] Destination: jok04eygx1oyriw0_6k84wrqze2ng03ex_MSHouneiZZk8fHMtR5zpum_1_20220124-22-01-03_0_1080p [jok04eygx1oyriw0_6k84wrqze2ng03ex_MSHouneiZZk8fHMtR5zpum_1_20220124-22-01-03_0_1080p].mp4
[download] jok04eygx1oyriw0_6k84wrqze2ng03ex_MSHouneiZZk8fHMtR5zpum_1_20220124-22-01-03_0_1080p [jok04eygx1oyriw0_6k84wrqze2ng03ex_MSHouneiZZk8fHMtR5zpum_1_20220124-22-01-03_0_1080p].mp4.part-Frag1 has already been downloaded
[download]   0.3% of ~2.81GiB at Unknown speed ETA Unknown (frag 1/367)ERROR: Incorrect AES key length (9 bytes)
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1367, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1451, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1503, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2589, in process_video_result
  File "yt_dlp\YoutubeDL.py", line 3054, in process_info
  File "yt_dlp\YoutubeDL.py", line 2769, in dl
  File "yt_dlp\downloader\common.py", line 440, in download
  File "yt_dlp\downloader\hls.py", line 358, in real_download
  File "yt_dlp\downloader\fragment.py", line 516, in download_and_append_fragments
  File "yt_dlp\downloader\fragment.py", line 369, in decrypt_fragment
  File "yt_dlp\aes.py", line 12, in aes_cbc_decrypt_bytes
  File "Cryptodome\Cipher\AES.py", line 232, in new
  File "Cryptodome\Cipher\__init__.py", line 79, in _create_cipher
  File "Cryptodome\Cipher\_mode_cbc.py", line 274, in _create_cbc_cipher
  File "Cryptodome\Cipher\AES.py", line 93, in _create_base_cipher
ValueError: Incorrect AES key length (9 bytes)
```

**Comment by Lesmiscore** [comment]
related: https://github.com/streamlink/streamlink/issues/4366

**Comment by pzhlkj6612** [comment]
Hi! I'd like to share what I found with you.

Since the MPEG-TS streams on niconico channel Plus are encrypted (AES-128 CBC), we need to find the key and the "initialization vector (iv)" to decrypt them (I only tested VoD, though):

1. Launch "Developer Tools" (F12) and switch to the "Network" tab.
2. Navigate to the video page (for example, "https://nicochannel.jp/mimimoto-ayaka/video/smRS96YpmDJr24YpWFZziG4L" from the OP).
3. Search "```/mediaplaylist```" and you can get the m3u8 playlist.
4. Search "```hls-auth.cloud.stream.co.jp/key```" and you can see the key in the response payload.

Because "https://nicochannel.jp/NfcOndemandPlayer.js" contains "```createInitializationVector```", I guess the player *is inspired by* [hls.js](https://github.com/video-dev/hls.js); after reading the [source code of "fragment.ts"](https://github.com/video-dev/hls.js/blob/98d4ab329827bfb2104a882cd13a4df8e983cbe8/src/loader/fragment.ts#L215-L228), we can know that the "iv" is calculated from the HLS segment number (1, 2, ...).

Then, we are able to download, decrypt and merge the streams.

<br>

We can also get the key by "curl":

```console
$ curl --silent \
>   'https://hls-auth.cloud.stream.co.jp/key?session_id=...&media_view_id=...' \
>   -H 'User-Agent: ...' \
>   -H 'Sec-Fetch-Dest: empty' \
>   -H 'Sec-Fetch-Mode: cors' \
>   -H 'Sec-Fetch-Site: cross-site' \
>     | xxd -ps
bd78ebf19bdbd0ea238730eb04618f37

```

OP said:

> ```console
> ValueError: Incorrect AES key length (9 bytes)
> ```

I guess the 9-byte "key" is "```Forbidden```":

```console
$ curl --silent \
>   'https://hls-auth.cloud.stream.co.jp/key?session_id=...&media_view_id=...' \
>     | xxd
00000000: 466f 7262 6964 6465 6e                   Forbidden
```

<br>

I'm personally using [Last-Order/Minyami](https://github.com/Last-Order/Minyami). It helps me to download the video without manually decrypting and merging streams.

**Comment by lokilin** [comment]
WOW [Last-Order/Minyami](https://github.com/Last-Order/Minyami)
Thank you told me that tool! easy to download and don't need find key by myself!
