### ISSUE TITLE
[Tiktok] - Open Pull Request, Problems with current "avatarLarger" implementation

### ISSUE THREAD

**Issue by UweLau** [yt-dlp/yt-dlp#2546]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

[Tiktok] - Open Pull Request, Problems with current "avatarLarger" implementation

Hi there,
I have several questions and remarks regarding the current TikTok extractor:
- First of all I am puzzled as to why the pull request #2449 is not already merged into the main branch? I tested the fix over at @MinePlayersPE branch and - at least for me - it fixes the problem mentioned at #2476 

- The next topic is regarding the commit b31874334d5d68121a4a3f0d28dc1b39e5fca93b 
The commit does what it should do: Extract the 1080x1080 thumbnail. Alas there are some problems with it:
- It seems the thumbnail is saved using the userid as number in the resulting output file so when the profile pictures changes the existing file is overwritten on my storage. It should check if the file is the same and if not then add a number to it. Or any other means to not just overwrite the old picture. I'm not sure if --no-overwrites would remedy that or if it only would mean it would keep the first downloaded profile picture forever. To make matters worth I noticed it DELETES the file when the user deletes its profile picture. I am not sure why this can even happen. Needless to say, this is not what it should do in my opinion 
- There is also a problem with generating a thumbnail in the first place. It fails when the user either has no video or have set its user to private. It seems it is because the URL for the file is taken from the video property. So when there is no video - there is no profile picture. There should be a solution for these cases to get the picture elsewhere (as mentioned in my #2186 issue)

Just for reference, I am using YT-DLP in its most basic form
yt-dlp https://www.tiktok.com/@user --write-thumbnail

Any help is appreciated

**Comment by pukkandan** [comment]
1. PRs take time to finalize and merge
2. "Comparing" the file is out of scope. You can use different output template so the files don't overwrite
3. If a user has no video, don't expect yt-dlp to do anything with it. It is a **video** downloader after all! I don't understand what you mean by "set its user to private". Best if you open a issue with example and verbose log

**Comment by UweLau** [comment]
1. OK
2. Can you give me a example how I can achieve my goal? 
3. Even if it's only a video downloader we could at least try to find a solution for that. Maybe @MinePlayersPE has an idea. "set its user to private" just means the account is private and I have no access to the videos, basically the same as is public but has no videos = same output: no profile picture.

**Comment by pukkandan** [comment]
> Can you give me a example how I can achieve my goal?

Your goal of comparing the files? I just said it is out of scope

**Comment by pukkandan** [comment]
You can add `%(epoch)s` to ensure each time the file is downloaded with a different name
