### ISSUE TITLE
[Broken] Go extractor doesn't match some URLs

### ISSUE THREAD

**Issue by tv21** [yt-dlp/yt-dlp#255]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running yt-dlp version **2021.04.11**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] Command-line config: ['-v', 'https://www.freeform.com/shows/cruel-summer/episode-guide/season-01/01-happy-birthday-jeanette-turner']
[debug] Loading archive file None
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] yt-dlp version 2021.04.11 (zip)
[debug] Python version 3.7.3 (CPython 32bit) - Linux-4.19.0-16-686-pae-i686-with-debian-10.9
[debug] exe versions: avconv 4.1.6-1, avprobe 4.1.6-1, ffmpeg 4.3-static, ffprobe 4.3-static, rtmpdump 2.4
[debug] Proxy map: {}
[generic] 01-happy-birthday-jeanette-turner: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 01-happy-birthday-jeanette-turner: Downloading webpage
[generic] 01-happy-birthday-jeanette-turner: Extracting information
ERROR: Unsupported URL: https://www.freeform.com/shows/cruel-summer/episode-guide/season-01/01-happy-birthday-jeanette-turner
Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1037, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1058, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 558, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/generic.py", line 3555, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.freeform.com/shows/cruel-summer/episode-guide/season-01/01-happy-birthday-jeanette-turner
```

## Description

WRITE DESCRIPTION HERE

Freeform (go.py) extractor doesn't seem to work here or in youtube-dl.  They have a patch to the go.py extractor that is only 11 hours old as I write this (https://github.com/ytdl-org/youtube-dl/commit/ac19c3ac8035fbf9369fd4bd336c9045d4eeafa3) but it still doesn't address this issue.  The link given in the verbose log is to the first show of the series which does not require credentials for access.

**Comment by pukkandan** [comment]
Don't forget the title when opening issues

**Comment by tv21** [comment]
My apologies, I thought I had entered a title but I guess not.  Anyway thank you very much for the fix!  I assume you'll be releasing an update to yt-dlp sometime in the not too distant future.

Thank you again for your quick attention to this!

**Comment by pukkandan** [comment]
>  I assume you'll be releasing an update to yt-dlp sometime in the not too distant future.

Yes. An update has been a bit overdue already. Expect it today/tomorrow
