### ISSUE TITLE
[generic] extractor for erome.com ouputs duplicate entries

### ISSUE THREAD

**Issue by brpy** [yt-dlp/yt-dlp#256]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running yt-dlp version **2021.04.11**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
yt-dlp -v -g https://www.erome.com/a/DkWy1XRA
[debug] Command-line config: ['-v', '-g', 'https://www.erome.com/a/DkWy1XRA']
[debug] Loading archive file None
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] yt-dlp version 2021.04.11 (zip)
[debug] Python version 3.9.2 (CPython 64bit) - Linux-5.11.14-200.fc33.x86_64-x86_64-with-glibc2.32
[debug] exe versions: ffmpeg 4.3.2, ffprobe 4.3.2
[debug] Proxy map: {}
WARNING: Falling back on generic information extractor.
https://s10.erome.com/366/DkWy1XRA/Jxot0Unb_480p.mp4
https://s10.erome.com/366/DkWy1XRA/Jxot0Unb_480p.mp4
```

## Description

The [link](https://www.erome.com/a/DkWy1XRA) provided has only one video, but the same video is downloaded twice. 

If it has multiple number of videos, each video is downloaded twice.

May be check for duplicates before returning the links? Thanks.

**Comment by frans77frans** [comment]
I ended up just writing a python script to purge the duplicate URLs before passing them on to yt-dlp. For anyone in the same boat, Erome does not allow you to just visit the CDN link directly, it requires you to use the base "album" link as the referer. It then works.

**Comment by harryqt** [comment]
As of today the latest version still has the same issue.. :(

**Comment by grimenycricket** [comment]
Made a .bat script for erome that auto skips the next file erome tries to serve (the duplicate). Ensure that the .exe is in the same folder that you save this .bat script into. once clicked it will just ask you for the url. No more duplicates.

@echo off
set /p "url=Paste Erome Playlist URL: "
yt-dlp.exe --playlist-items 1::2 --no-overwrites -o "%%(title).100s.%%(ext)s" %url%
pause
