### ISSUE TITLE
Destination file for --write-subs

### ISSUE THREAD

**Issue by xxcodianxx** [yt-dlp/yt-dlp#2560]
### Checklist

- [X] I'm reporting a feature request
- [X] I've verified that I'm running yt-dlp version **2022.01.21**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

Currently, when using the `--write-subs` option, the resulting file bears the same filename of the video, specified with the `-o` option.

It would be convenient to be able to specify, separately from the `-o` flag, the destination file(s) of the downloaded subtitles.

Example:
`--write-subs mysubs -o myvideo.mp4`

Resulting Files:
`mysubs.en.vtt`
`mysubs.fr.vtt`
`myvideo.mp4`

To maintain compatibility, if no filename is supplied for the subtitle destination, it should use the value of `-o` as before.

**Comment by pukkandan** [comment]
https://github.com/yt-dlp/yt-dlp#output-template

> Additionally, you can set different output templates for the various metadata files separately from the general output template by specifying the type of file followed by the template separated by a colon `:`
