### ISSUE TITLE
Hotstar Payment required

### ISSUE THREAD

**Issue by Ayush-4265** [yt-dlp/yt-dlp#2563]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.01.21**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

India

### Description

Cant download any hotstar files. ERROR 402. Payment Required

### Verbose log

```shell
[debug] Command-line config: ['-vU', 'https://www.hotstar.com/in/tv/the-book-of-boba-fett/1260076689/chapter-1/1260076691']
[debug] User config "C:\Users\asus\AppData\Roaming\yt-dlp\config.txt": ['--downloader', 'aria2c', '--downloader-args', 'aria2c:-c -j 8 -x 8 -s 8 -k 10M']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.01.21 [f20d607] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.22533-SP0
[debug] exe versions: ffmpeg n5.0-3-ga394d35a43-20220131 (setts), ffprobe n5.0-3-ga394d35a43-20220131
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.01.21, Current version: 2022.01.21
yt-dlp is up to date (2022.01.21)
[debug] [hotstar] Extracting URL: https://www.hotstar.com/in/tv/the-book-of-boba-fett/1260076689/chapter-1/1260076691
[hotstar] 1260076691: Downloading JSON metadata
[hotstar] 1260076691: Downloading webpage
[hotstar] 1260076691: Downloading token
[hotstar] 1260076691: Downloading JSON metadata
ERROR: [hotstar] 1260076691: Unable to download JSON metadata: HTTP Error 402: Payment Required (caused by <HTTPError 402: 'Payment Required'>); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output. (caused by <HTTPError 402: 'Payment Required'>); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
  File "yt_dlp\extractor\common.py", line 730, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 3526, in urlopen
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 649, in http_error_default
```

**Comment by pukkandan** [comment]
Pass cookies with access to the content

**Comment by Ashish0804** [comment]
DRM and paid.

**Comment by Abhijit47** [comment]
My account is paid but same problem :(

**Comment by ArgX11** [comment]
adding --cookies-from-browser BrowserName solves the problem. I have a paid account, tried this method and it worked.
