### ISSUE TITLE
"Unable to extract OpenGraph title" when trying to download from fc2

### ISSUE THREAD

**Issue by maxiy01** [yt-dlp/yt-dlp#2566]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.01.21**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Russia

### Description

I get "Unable to extract OpenGraph title" error whenever I try to download video from fc2

### Verbose log

```shell
D:\youtube-dl>yt-dlp.exe -vU --cookies=cookies.txt -f "bestvideo[fps>=59][height=720][ext=mp4]+bestaudio[ext=m4a]/bestvideo[fps>=59][height<=1080][ext=mp4]+bestaudio[ext=m4a]/best[height<=720]/best[height<=1080]" --no-playlist -a ytdlp-links.txt
[debug] Command-line config: ['-vU', '--cookies=cookies.txt', '-f', 'bestvideo[fps>=59][height=720][ext=mp4]+bestaudio[ext=m4a]/bestvideo[fps>=59][height<=1080][ext=mp4]+bestaudio[ext=m4a]/best[height<=720]/best[height<=1080]', '--no-playlist', '-a', 'ytdlp-links.txt']
[debug] Batch file urls: ['https://video.fc2.com/content/201110052Z4kmmNX']
[debug] Encodings: locale cp1251, fs utf-8, out utf-8, err utf-8, pref cp1251
[debug] yt-dlp version 2022.01.21 [f20d607] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19042-SP0
[debug] exe versions: ffmpeg 4.2.3, ffprobe 2021-05-26-git-7a879cce37-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.01.21, Current version: 2022.01.21
yt-dlp is up to date (2022.01.21)
[debug] [fc2] Extracting URL: https://video.fc2.com/content/201110052Z4kmmNX
[fc2] 201110052Z4kmmNX: Downloading webpage
ERROR: [fc2] 201110052Z4kmmNX: Unable to extract OpenGraph title; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
  File "yt_dlp\extractor\common.py", line 612, in extract
  File "yt_dlp\extractor\fc2.py", line 88, in _real_extract
  File "yt_dlp\extractor\common.py", line 1294, in _og_search_title
  File "yt_dlp\extractor\common.py", line 1282, in _og_search_property
  File "yt_dlp\extractor\common.py", line 1186, in _search_regex
```

**Comment by pukkandan** [comment]
cc @Lesmiscore since u were working on fc2 live

**Comment by Lesmiscore** [comment]
@pukkandan These two has diff structure, not like YT.
Anyway I see something has to be fixed
