### ISSUE TITLE
An error is reported when os.system runs on windows.

### ISSUE THREAD

**Issue by shoucandanghehe** [yt-dlp/yt-dlp#257]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

I have an error when running yt-dlp using os.system.
Only Windows systems will report errors
When I run the same command in cmd, it does not produce an error
The command is as follows:
`yt-dlp --format "bestvideo[ext=mp4]+bestaudio[ext=m4a]/bestvideo+bestaudio/best" --merge-output-format mp4 -o'%(title)s.%(ext )s' -N 16 'YouTubeVideoLink'`

**Comment by pukkandan** [comment]
What is the code you are running, what is the output?

> I have an error when running yt-dlp using os.system

"an error" really doesn't help!!

**Comment by shoucandanghehe** [comment]
I have instructions for running code
The error is
[youtube] 【url】: Downloading webpage
ERROR: requested format not available

**Comment by shoucandanghehe** [comment]
No problem when running the same program on Ubuntu

**Comment by shoucandanghehe** [comment]
This is the program I used for testing
```
import os
url = 'x8VYWazR5mE'
os.system(f"yt-dlp --format 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/bestvideo+bestaudio/best' --merge-output-format mp4 -o '%(title)s.%(ext)s' -N 16 https://www.youtube.com/watch?v={url}")
```

**Comment by pukkandan** [comment]
windows doesn't allow single quotes. Use double quotes

**Comment by shoucandanghehe** [comment]
It is running
Thank you
I have no problem using single quotes in Powershell, but I don’t know that they cannot be used in cmd
lol
