### ISSUE TITLE
Unsupported URL Hotstar

### ISSUE THREAD

**Issue by azizramdan** [yt-dlp/yt-dlp#2571]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.01.21**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Indonesia

### Description

I try to download from hotstar Indonesia, but always get Unsupported URL error. Does it not support the Indonesian region?

### Verbose log

```shell
yt-dlp.exe -vU --cookies cookies-hotstar.txt "https://www.hotstar.com/id/tv/snowdrop/1260075599/episode-1/1260075603"
[debug] Command-line config: ['-vU', '--cookies', 'cookies-hotstar.txt', 'https://www.hotstar.com/id/tv/snowdrop/1260075599/episode-1/1260075603']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.01.21 [f20d607] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] exe versions: none
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.01.21, Current version: 2022.01.21
yt-dlp is up to date (2022.01.21)
[debug] [generic] Extracting URL: https://www.hotstar.com/id/tv/snowdrop/1260075599/episode-1/1260075603
[generic] 1260075603: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] 1260075603: Downloading webpage
[generic] 1260075603: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://www.hotstar.com/id/tv/snowdrop/1260075599/episode-1/1260075603
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1367, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1437, in __extract_info
  File "yt_dlp\extractor\common.py", line 612, in extract
  File "yt_dlp\extractor\generic.py", line 3966, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.hotstar.com/id/tv/snowdrop/1260075599/episode-1/1260075603
```

**Comment by MinePlayersPE** [comment]
Example URL is DRM protected

**Comment by azizramdan** [comment]
> Example URL is DRM protected

Ah I see

**Comment by Ashish0804** [comment]
Also dlp doesn't have the generalized hotstar code yet. It exists on my fork on the `better` branch and will be ported here sooner or later...u can give it a try if u want (won't help with DRM video ofc) but don't expect support.

**Comment by Rajveer0916** [comment]
Ashish plzzz add hotstar code

**Comment by azizramdan** [comment]
> Also dlp doesn't have the generalized hotstar code yet. It exists on my fork on the `better` branch and will be ported here sooner or later...u can give it a try if u want (won't help with DRM video ofc) but don't expect support.

How to find non DRM videos?

**Comment by Ashish0804** [comment]
Usually on hs, all free videos are non DRM. 
All Disney videos are drm'd and for rest dlp will tell u it's encrypted if DRM.

**Comment by coolzaa** [comment]
> Also dlp doesn't have the generalized hotstar code yet. It exists on my fork on the `better` branch and will be ported here sooner or later...u can give it a try if u want (won't help with DRM video ofc) but don't expect support.

Will there be an update code for hotstar download with drm soon? I just want to download the video. Now I'm stuck with Unsupported URL problem.
