### ISSUE TITLE
MacOS standalone executable script

### ISSUE THREAD

**Issue by someziggyman** [yt-dlp/yt-dlp#2574]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

I'm switching Macs from time to time and wanted to have a portable standalone executable like you create in Releases section. 
I was wondering, if there's some script or command, I could use to build from source and have a "signed" standalone universal binary?

Based on my amateurish research I've tried downloading ytdl source code, installed pyinstaller via brew and ran this script  **pyinstaller ./__main__.py  --codesign-identity “CreatedCodeSignature”  --onefile --name portableYTDL**

A couple problems with it:
- it's not universal2 (I assume, this is because I'm using pyinstaller from brew and this way it only matches Mac's architecture)
- my self built binary works only locally for some reason
- other Macs with "clean" OS versions would complain about python3 not being signed properly.. That's one of the reasons why I decided I need to try and build from source in order to code-sign everything "deeper", when binary is built. 
- is a bit smaller in size - 10.4 Mb, yours is 13.2Mb 
- not as reliable as release version due to some random SSL certificate error messages...

Some of these might just be specific to my set up or my assumptions are wrong, but I'll be glad, if someone could give a hint on where to start, what I'm doing wrong and how to build "release like" binary from source?

**Comment by pukkandan** [comment]
`yt-dlp_macos` is built like this
https://github.com/yt-dlp/yt-dlp/blob/d6bc443bdeb8d0246cef1c4b8b9206a18413dbca/.github/workflows/build.yml#L176

I have no clue for the rest of your questions. Best to ask in some python/pyinstaller community
