### ISSUE TITLE
Add support for QQ.com

### ISSUE THREAD

**Issue by ahm750** [yt-dlp/yt-dlp#2577]
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.01.21**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Example URLs

QQ single video: https://v.qq.com/x/page/o3208rrtzzp.html
Youku single video: https://v.youku.com/v_show/id_XMzYyNDAzODYxNg==.html?spm=a2h0c.8166622.PhoneSokuUgc_2.dtitle

### Description

Hi, would it be possible to add support for these two websites?

### Verbose log

```shell
[debug] Command-line config: ['-J', '-vU', 'https://v.qq.com/x/page/o3208rrtzzp.html']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, err UTF-8, pref UTF-8
[debug] yt-dlp version 2022.01.21 [f20d607b0]
[debug] Python version 3.7.5 (CPython 64bit) - Linux-4.15.0-135-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: none
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.01.21, Current version: 2022.01.21
yt-dlp is up to date (2022.01.21)
[debug] [generic] Extracting URL: https://v.qq.com/x/page/o3208rrtzzp.html
[generic] o3208rrtzzp: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] o3208rrtzzp: Downloading webpage
[generic] o3208rrtzzp: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://v.qq.com/x/page/o3208rrtzzp.html
Traceback (most recent call last):
  File "/home/bd7/.local/lib/python3.7/site-packages/yt_dlp/YoutubeDL.py", line 1367, in wrapper
    return func(self, *args, **kwargs)
  File "/home/bd7/.local/lib/python3.7/site-packages/yt_dlp/YoutubeDL.py", line 1437, in __extract_info
    ie_result = ie.extract(url)
  File "/home/bd7/.local/lib/python3.7/site-packages/yt_dlp/extractor/common.py", line 612, in extract
    ie_result = self._real_extract(url)
  File "/home/bd7/.local/lib/python3.7/site-packages/yt_dlp/extractor/generic.py", line 3966, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://v.qq.com/x/page/o3208rrtzzp.html

null
```

**Comment by pukkandan** [comment]
youku is supported, but broken. Open a new issue

**Comment by HobbyistDev** [comment]
related / duplicate #1666
