### ISSUE TITLE
iFunny support

### ISSUE THREAD

**Issue by jericjan** [yt-dlp/yt-dlp#2578]
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.01.21**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Philippines

### Example URLs

Single video: https://ifunny.co/video/that-yoinky-sploinky-DMf3w6YA8

### Description

There's no support for iFunny. Seems simple enough. You can already right-click then "Copy video address" in the browser but I'd like to have this automated with yt-dlp. It currently downloads this `unknown_video` file that seems to just be the site downloaded as an html file.

### Verbose log

```shell
[debug] Command-line config: ['-vU', 'https://ifunny.co/video/that-yoinky-sploinky-DMf3w6YA8']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, err UTF-8, pref UTF-8
[debug] yt-dlp version 2022.01.21 [f20d607b0] (zip)
[debug] Python version 3.7.12 (CPython 64bit) - Linux-5.4.144+-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.8, ffprobe 3.4.8
[debug] Optional libraries: sqlite
[debug] Proxy map: {}
Latest version: 2022.01.21, Current version: 2022.01.21
yt-dlp is up to date (2022.01.21)
[debug] [generic] Extracting URL: https://ifunny.co/video/that-yoinky-sploinky-DMf3w6YA8
[generic] that-yoinky-sploinky-DMf3w6YA8: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] that-yoinky-sploinky-DMf3w6YA8: Downloading webpage
[generic] that-yoinky-sploinky-DMf3w6YA8: Extracting information
[debug] Looking for video embeds
[debug] Identified a JSON LD
[debug] Default format spec: bestvideo*+bestaudio/best
[info] that-yoinky-sploinky-DMf3w6YA8: Downloading 1 format(s): 0
[debug] Invoking downloader on "https://ifunny.co/video/DMf3w6YA8"
[download] Destination: That yoinky sploinky - ) [that-yoinky-sploinky-DMf3w6YA8].unknown_video
[download] 100% of 157.31KiB in 00:00
```

**Comment by ahm750** [comment]
Came here to submit a support request for this site. Glad that you brought it up.
