### ISSUE TITLE
[BITCHUTE] Refresh on low download rates

### ISSUE THREAD

**Issue by HalvorRaknes** [yt-dlp/yt-dlp#2583]
### Checklist

- [X] I'm reporting a site feature request
- [X] I've verified that I'm running yt-dlp version **2022.01.21**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Norway

### Example URLs

https://www.bitchute.com/video/UfEkp_TFvY0/

### Description

BitChute will sometimes (quite often actually) pick a very low transfer rate, typically <100kB/s).  Usually, or at least quite often, this can be drastically improved by simply restarting the download which may then proceed at 2-4MB/s.

For this reason it would be a great improvement for BitChute jobs if a threshold limit could be set where, if download speed falls below, the particular download would be restarted after some suitable time duration. Perhaps 30 seconds or one minute would be appropriate picks so as not to disrupt or vex the site unduly since these diminished speeds are probably (?) assigned to alleviate bandwidth strain on the BitChute server.

### Verbose log

```shell
-
```

**Comment by pukkandan** [comment]
https://github.com/yt-dlp/yt-dlp#download-options
```
--throttled-rate RATE            Minimum download rate in bytes per second
                                 below which throttling is assumed and the
                                 video data is re-extracted (e.g. 100K)
```

**Comment by HalvorRaknes** [comment]
Thank you! I'll try it out!
