### ISSUE TITLE
Livestream Tiktok Support?

### ISSUE THREAD

**Issue by UnixCro** [yt-dlp/yt-dlp#2585]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

I wanted to ask if it might be possible to program yt-dlp in such a way that it is also able to display the video address of a Tiktok live stream or, best of all, to download it.  Currently there are only Instagram Livestream Downloader on Github.

Thank you

**Comment by pukkandan** [comment]
> [x] I'm asking a question and not reporting a bug/feature request

Do not spam

**Comment by UnixCro** [comment]
I don't spam  Once I asked a question and once I reported a problem.  Nobody listens to me and just closes.  What shoud that?

**Comment by pukkandan** [comment]
The issue templates exist for a reason. If you don't follow it, the issues will be treated as invalid

**Comment by pukkandan** [comment]
If you are asking to support tiktok live stream, properly fill out the [site feature request](https://github.com/yt-dlp/yt-dlp/issues/new?labels=triage%2Csite-enhancement&template=3_site_feature_request.yml)

**Comment by UnixCro** [comment]
I'll deal with my requests later.  Please reopen.

**Comment by gamer191** [comment]
> I'll deal with my requests later.


![Any day now!](https://media.tenor.com/NEwl9afO460AAAAM/whatever-any-time-now.gif)
