### ISSUE TITLE
[twitter] `%(title)s` contains another `%(uploader)s`, even template already has a `%(uploader)s`

### ISSUE THREAD

**Issue by NewUserHa** [yt-dlp/yt-dlp#2587]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.01.21**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Description

If the template is like `%(uploader)s-%(title)s.%(ext)s`, then there will be two `%(uploader)s` in the file name.

Also, the `title` actually is using the `description` as content, which may have a very long length.
What about shrinking it, or changing it to other Infos maybe like the number '1468039525062803458' in the url?

### Verbose log

```shell
[debug] Command-line config: ['-vU', '-o', '%(uploader)s-%(title)s.%(ext)s', 'https://mobile.twitter.com/ystk_yrk/status/1468039525062803458']
[debug] Encodings: locale cp936, fs utf-8, out utf-8, err utf-8, pref cp936
[debug] yt-dlp version 2022.01.21 [f20d607b0]
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.17134-SP0
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.01.21, Current version: 2022.01.21
yt-dlp is up to date (2022.01.21)
[debug] [twitter] Extracting URL: https://mobile.twitter.com/ystk_yrk/status/1468039525062803458
[twitter] 1468039525062803458: Downloading guest token
[twitter] 1468039525062803458: Downloading JSON metadata
[twitter] 1468039525062803458: Downloading m3u8 information
[debug] Sort order given by extractor: res, br, size, proto
[debug] Formats sorted by: hasvid, ie_pref, res, tbr, vbr, abr, filesize, fs_approx, proto, lang, quality, fps, hdr:12(7), vcodec:vp9.2(10), acodec, asr, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 1468039525062803458: Downloading 1 format(s): http-2176
[debug] Invoking downloader on "https://video.twimg.com/ext_tw_video/1468039498902560770/pu/vid/720x1280/3K53-yHgQ5SQVmKC.mp4?tag=12"
[download] Destination: 吉高由里子-吉高由里子 - さぁ！ 8話も放送され 9話も撮りきり ラストスパート！待ってました10話！ おっ⁉︎撮休か⁉︎ 何するか⁉︎ 寝溜めするか⁉︎ 夜ふかしするか⁉︎ おぅん⁉︎どうするんだい⁉︎  あー😩遊ぶよね 元気に朝から遊ぶよね 上手くもないから 走り回ってボール探すよね ねぇ🥺ラスト頑張るから🥺許して🥺.mp4
[download] 100% of 503.87KiB in 00:02
```

**Comment by pukkandan** [comment]
That IS the title of the webpage. If you think there is some other data that is more appropriate as title, let us know
![image](https://user-images.githubusercontent.com/6623388/152051824-ef9c742e-ef8f-49ee-a718-63ca280a183b.png)

**Comment by NewUserHa** [comment]
`ERROR: unable to open for writing: [Errno 22] Invalid argument: ` if the description has any invalid string for a path, which is very common cases on twitter.
consider reopening this issue?

**Comment by pukkandan** [comment]
See #1136

**Comment by NewUserHa** [comment]
ok.
