### ISSUE TITLE
[youtube] nsig extraction failed

### ISSUE THREAD

**Issue by tacohitbox** [yt-dlp/yt-dlp#2588]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.01.21**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United States

### Description

Download still succeeds, just throttled again.

### Verbose log

```shell
$ yt-dlp -vU --no-download https://www.youtube.com/watch?v=VzqN4Cn8r3U
[debug] Command-line config: ['-vU', '--no-download', 'https://www.youtube.com/watch?v=VzqN4Cn8r3U']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.01.21 [f20d607b0] (zip)
[debug] Python version 3.10.1 (CPython 64bit) - Linux-5.14.21-2-MANJARO-x86_64-with-glibc2.33
[debug] exe versions: ffmpeg 4.4.1 (setts), ffprobe 4.4.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome, secretstorage, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.01.21, Current version: 2022.01.21
yt-dlp is up to date (2022.01.21)
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=VzqN4Cn8r3U
[youtube] VzqN4Cn8r3U: Downloading webpage
[youtube] VzqN4Cn8r3U: Downloading android player API JSON
[youtube] VzqN4Cn8r3U: Downloading player e06dea74
WARNING: [youtube] nsig extraction failed: You may experience throttling for some formats
n = 2rWZ998KTlsmBLexbl ; player = https://www.youtube.com/s/player/e06dea74/player_ias.vflset/en_US/base.js
VzqN4Cn8r3U: Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/youtube.py", line 2412, in _decrypt_nsig
    self._player_cache[player_id] = self._extract_n_function(video_id, player_url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/youtube.py", line 2433, in _extract_n_function
    funcname = self._extract_n_function_name(jscode)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/youtube.py", line 2421, in _extract_n_function_name
    return self._search_regex(
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 1186, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
yt_dlp.utils.RegexNotFoundError: Unable to extract Initial JS player n function name; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
 (caused by RegexNotFoundError('Unable to extract \x1b[0;94mInitial JS player n function name\x1b[0m; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.')); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] VzqN4Cn8r3U: Downloading 1 format(s): 315+251
```

**Comment by pukkandan** [comment]
> - [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates

---

![image](https://user-images.githubusercontent.com/6623388/152050913-6f75443c-f620-4a59-b58b-501d8bafc8a5.png)

**Comment by tacohitbox** [comment]
> > * [x]  I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
> 
> ![image](https://user-images.githubusercontent.com/6623388/152050913-6f75443c-f620-4a59-b58b-501d8bafc8a5.png)

apologies, forgot to check closed issues

**Comment by filterfish** [comment]
> > * [x]  I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
> 
> ![image](https://user-images.githubusercontent.com/6623388/152050913-6f75443c-f620-4a59-b58b-501d8bafc8a5.png)

Surely it would be *much* easier just to paste the uri of the duplicate. At least anyone else who finds themself here can just click through to the correct ticket.

**Comment by pukkandan** [comment]
How many duplicates do you think I should copy pasted the URL of the "original" for? Even my patience has its limits. What I should really do is not even reply to duplicates and treat these issues as spam

How do you even "find yourself here" but not be able to find the original when the issue is clearly tagged as a duplicate!?

**Comment by fstirlitz** [comment]
> What I should really do is not even reply to duplicates and treat these issues as spam

Just like dstftw?

> How do you even "find yourself here" but not be able to find the original when the issue is clearly tagged as a duplicate!?

How do you expect to the original ticket to be findable six months from now, after a hundred or so other tickets about extraction failure?

It can be hard to know what to search for sometimes, even when tickets have titles better than ‘plz halp it no work’. If you were to reconsider #620, it might be possible to incorporate automatic search for duplicates in bug report mode by tossing a request at <https://api.github.com/search/issues?q=repo:yt-dlp/yt-dlp>.

(I believe the relevant ticket here is #2569.)

**Comment by pukkandan** [comment]
> How do you expect the original ticket to be findable six months from now, after a hundred or so other tickets about extraction failure?

> It can be hard to know what to search for sometimes, even when tickets have titles better than ‘plz halp it no work’

You can see from the other issues that I do generally link the original issue for duplicates. But when there is so many issues opened with pretty much the same title, just hours apart - as I said, even my patience has its limit. The community members are always free to help those people by linking the original issue. There is no need to put all the burden on me

> If you were to reconsider https://github.com/yt-dlp/yt-dlp/issues/620, it might be possible to incorporate automatic search for duplicates in bug report mode by tossing a request at [api.github.com/search/issues?q=repo:yt-dlp/yt-dlp](https://api.github.com/search/issues?q=repo:yt-dlp/yt-dlp).

Since you never replied to it, I was under the impression you were satisfied with issue forms. I can re-open the issue. But I'm still not sure this is feasible to implement

**Comment by tacohitbox** [comment]
> But when there is so many issues opened with pretty much the same title, just hours apart - as I said, even my patience has its limit. 

I'm really sorry again for this. It was my fault for not checking that well. I really appreciate the work you do for this community.

**Comment by filterfish** [comment]
> You can see from the other issues that I do generally link the original issue for duplicates. But when there is so many issues opened with pretty much the same title, just hours apart - as I said, even my patience has its limit. The community members are always free to help those people by linking the original issue. There is no need to put all the burden on me

Maybe that's the answer. Get community members to help with the problem, you simply close them as spam and hope others pick up the burden of dealing with spam. Or maybe get others to triage issues so you don't have to deal with them. I'm not sure if you're heard of phabricator (sadly on longer maintained) but it had the notion of triage built in and it's really useful. Anyway just some random thoughts.

**Comment by aasdfasdfg** [comment]
Sorry for posting on an old issue, and for reporting something on an old version of yt-dlp, but I ran into a similar error just now and I am in a rush - so I can't do the full due diligence before filing a new issue right now. So I am leaving this comment with enough info to either revisit it later myself, or at the very least leave enough breadcrumbs for someone else in case I don't get around to that myself.

```
yt-dlp rMIEPkaadq0
[youtube] rMIEPkaadq0: Downloading webpage
[youtube] rMIEPkaadq0: Downloading android player API JSON
[youtube] rMIEPkaadq0: Downloading player 87b9576a
WARNING: [youtube] nsig extraction failed: You may experience throttling for some formats
n = sSFow21YhNN4l1Fxsx ; player = https://www.youtube.com/s/player/87b9576a/player_ias.vflset/en_US/base.js
rMIEPkaadq0: Traceback (most recent call last):
  File "/usr/local/Cellar/yt-dlp/2021.12.27/libexec/lib/python3.10/site-packages/yt_dlp/extractor/youtube.py", line 2095, in _decrypt_nsig
    self._player_cache[player_id] = self._extract_n_function(video_id, player_url)
  File "/usr/local/Cellar/yt-dlp/2021.12.27/libexec/lib/python3.10/site-packages/yt_dlp/extractor/youtube.py", line 2116, in _extract_n_function
    funcname = self._extract_n_function_name(jscode)
  File "/usr/local/Cellar/yt-dlp/2021.12.27/libexec/lib/python3.10/site-packages/yt_dlp/extractor/youtube.py", line 2104, in _extract_n_function_name
    return self._search_regex(
  File "/usr/local/Cellar/yt-dlp/2021.12.27/libexec/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 1173, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
yt_dlp.utils.RegexNotFoundError: Unable to extract Initial JS player n function name; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
 (caused by RegexNotFoundError('Unable to extract \x1b[0;94mInitial JS player n function name\x1b[0m; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.')); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
[info] rMIEPkaadq0: Downloading 1 format(s): 303+251
```

**Comment by pukkandan** [comment]
@aasdfasdfg The issue is already fixed. You just need to update

**Comment by eremitein** [comment]
hi, here is again same issue in latest version which I checked today

```
yt-dlp -U
Latest version: 2022.08.19, Current version: 2022.08.08
Current Build Hash 0d92f197c26b4f9db96d6124a69062bc630f04f616231be666b03b465dd5a7e2
Updating to version 2022.08.19 ...
Updated yt-dlp to version 2022.08.19
```

issue message
```
yt-dlp -f 244+251 --no-mtime --windows-filenames -a /tmp/3
[youtube] agxpCg9m_Y4: Downloading webpage
[youtube] agxpCg9m_Y4: Downloading android player API JSON
WARNING: [youtube] agxpCg9m_Y4: nsig extraction failed: You may experience throttling for some formats
         Install PhantomJS to workaround the issue
         n = e8vN8el9IGq1y7NthHe2 ; player = https://www.youtube.com/s/player/dc0c6770/player_ias.vflset/en_US/base.js
[info] agxpCg9m_Y4: Downloading 1 format(s): 244+251
```
