### ISSUE TITLE
[Zoom} Chat support

### ISSUE THREAD

**Issue by upintheairsheep** [yt-dlp/yt-dlp#2591]
### Checklist

- [X] I'm reporting a site feature request
- [X] I've verified that I'm running yt-dlp version **2022.01.21**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

All

### Example URLs

none

### Description

ADD SUPPORT for writing the Zoom chatlog on a zoom recording.

### Verbose log

```shell
none
```

**Comment by chrizilla** [comment]
Is this even possible for yt-dlp (even if the issue were not "imcomplete") ?

**Comment by upintheairsheep** [comment]
To download the chat logs from the zoom recording
