### ISSUE TITLE
Metadata-only archives

### ISSUE THREAD

**Issue by upintheairsheep** [yt-dlp/yt-dlp#2596]
### Checklist

- [X] I'm reporting a feature request
- [X] I've verified that I'm running yt-dlp version **2022.01.21**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

can you do youtube channel archiving without archiving the video files, only metadata including comments? Comments are extremely useful and valuable info. Live chat and replies are included.

Archival requests (comments, replies, and live chat ONLY):
https://www.youtube.com/user/GilvaSunner (deleting channel in Friday this week, large)
https://www.youtube.com/channel/UC7thyISASts8_nlQMZmE1VQ (medium, channel getting striked)

**Comment by pukkandan** [comment]
Go through the readme

> without archiving the video files

`--skip-download`

> only metadata including comments? 

`--write-info-json --write-comments`

> Live chat and replies are included.

`--write-subs --sub-lang live_chat`
