### ISSUE TITLE
[twitch:stream] Support "--wait-for-video" option.

### ISSUE THREAD

**Issue by dude22072** [yt-dlp/yt-dlp#2597]
### Checklist

- [X] I'm reporting a feature request
- [X] I've verified that I'm running yt-dlp version **2022.01.21**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

Title is fairly self explanatory. With the "twitch:stream" extractor if the user is offline it errors out and exits yt-dlp:
```
[twitch:stream] USERNAME: Downloading stream GraphQL
ERROR: [twitch:stream] USERNAME: USERNAME is offline
```
when using the "--wait-for-video" option instead of erroring out and exiting the extractor should respect it and retry after the given amount of time.

**Comment by pukkandan** [comment]
Example URL

**Comment by pukkandan** [comment]
Are you asking about using a user URL? If so, it is not possible. `--wait-for-video` can only wait for **scheduled** videos. If there is no schedule, you might as well just run yt-dlp in a loop

**Comment by dude22072** [comment]
Is running in a loop not what it does for YouTube videos? Just because a stream is scheduled to start at a specific time does not mean it actually will.  
  
As far as I understand it works this way:  
When trying to use yt-dlp on a scheduled YouTube stream it will error out saying "This live event will begin in X hours." and exit yt-dlp. When using --wait-for-video yt-dlp will instead sit and wait until the stream is scheduled to start, and then loop on the given URL until it actually does start and the download can begin.  
When using yt-dlp on a Twitch user URL it will error out saying "X is offline" and exit, so far we are the same as YouTube in this aspect. So the request here is to make the second half the same as well, sit and loop on the given URL until a stream is live. Just in this case it is a user URL (which will provide the current stream once live) instead of looping on a specific video ID.  
If there has to be some sort of "wait until this specific time" aspect to the option, Twitch does have a built-in schedule feature which lets you set reminders same as YouTube that could be used as the start time, it's just that Twitch does not assign IDs to the scheduled streams ahead of time like YouTube.

**Comment by pukkandan** [comment]
> Twitch does have a built-in schedule feature which lets you set reminders same as YouTube that could be used as the start time, it's just that Twitch does not assign IDs to the scheduled streams a

Give examples, or how to find such sheduled streams on the site

**Comment by Zirro** [comment]
> Are you asking about using a user URL? If so, it is not possible. --wait-for-video can only wait for scheduled videos. If there is no schedule, you might as well just run yt-dlp in a loop
 
Would you consider adding a way to check once every minute or so, instead? I think most people would expect it to work that way. Livestreams rarely start right on time - some start early, some start late - and some don't follow a schedule at all.

To set it apart from merely running yt-dlp in a loop, the check could use smaller requests than normal downloads (potentially by looking for the existence of a `_live`-thumbnail in case that is an indicator of a stream that has started, for example) and slow down in case it receives 429 errors. I'm sure it would also help a lot of users to have a simple way to do this without needing to figure out how loops work on their particular platform or shell.

**Comment by dude22072** [comment]
> > Twitch does have a built-in schedule feature which lets you set reminders same as YouTube that could be used as the start time, it's just that Twitch does not assign IDs to the scheduled streams a
> 
> Give examples, or how to find such sheduled streams on the site

Go to a users channel and click the "schedule" tab where it has Home/About/Schedule/Videos/Chat
If you need a direct link to someone who uses it then https://www.twitch.tv/midnababy/schedule

**Comment by pukkandan** [comment]
> Go to a users channel and click the "schedule" tab where it has Home/About/Schedule/Videos/Chat
> If you need a direct link to someone who uses it then [twitch.tv/midnababy/schedule](https://www.twitch.tv/midnababy/schedule)

That is not scheduled videos in the same sense as youtube

> Would you consider adding a way to check once every minute or so, instead? I think most people would expect it to work that way. Livestreams rarely start right on time - some start early, some start late - and some don't follow a schedule at all.

**Comment by pukkandan** [comment]
> Go to a users channel and click the "schedule" tab where it has Home/About/Schedule/Videos/Chat
> If you need a direct link to someone who uses it then [twitch.tv/midnababy/schedule](https://www.twitch.tv/midnababy/schedule)

That is not scheduled streams in the same sense as for youtube

> Would you consider adding a way to check once every minute or so, instead? I think most people would expect it to work that way. Livestreams rarely start right on time - some start early, some start late - and some don't follow a schedule at all.

The intended use of `--wait-for-video` is to wait for a **video** that has `live_status=is_upcoming` (ie, scheduled videos). In this case, there is no video on the webpage at all. So what you are asking is to wait for the URL to contain a video; ie, run in a loop till exit code = 0. These are totally different things

**Comment by lorenzolamasse** [comment]
This one would be nice, especially when most music streams get partly silent after diffusion due to copyrighting matters, so if we were able to grab them on the go by planning the dl (using the global channel link) we would be sure to get the full stream and not the modified one... Don't know how technical it would be though ;-)
