### ISSUE TITLE
[Site Request] Add support for Reality app

### ISSUE THREAD

**Issue by yk6** [yt-dlp/yt-dlp#2601]
### Checklist

- [X] I'm reporting a feature request
- [X] I've verified that I'm running yt-dlp version **2022.01.21**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

Is it possible to add support for reality app streams?
Sample url: https://reality.app/viewer/27256284?adj_t=1tl7pjp_yu20f4x

**Comment by pukkandan** [comment]
This should have been a site request!

The page gives 404. Provide working example and verbose log

**Comment by yk6** [comment]
The link below is a close one that I found, but I am not very sure how can it be accessed via web browser.
https://till0196.com/post6576
The stream is only available as livestream and there is no archive.

**Comment by pukkandan** [comment]
If you can't access it in browser, we can't support it
