### ISSUE TITLE
UK: Channel4/All4 Unable to download video.

### ISSUE THREAD

**Issue by Davetheraveuk** [yt-dlp/yt-dlp#2605]
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.01.21**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

United Kingdom

### Example URLs

https://www.channel4.com/programmes/no-angels/on-demand/33369-001

### Description

OS: **Arch Linux**
yt-dlg version: **2022.01.21-1**

I would like to be able to download a TV series called "No Angels" from the Channel 4/All4 website (Yes I do hold a TV Licence).
S01E01 Is in the link above.

Please let me know if you require any more information.
Have a nice day.
David.

### Verbose log

```shell
[dave@ArcoLinuxB Desktop]$ yt-dlp -vU "https://www.channel4.com/programmes/no-angels/on-demand/33369-001"
[debug] Command-line config: ['-vU', 'https://www.channel4.com/programmes/no-angels/on-demand/33369-001']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.01.21 [f20d607b0]
[debug] Python version 3.10.2 (CPython 64bit) - Linux-5.15.18-1-lts-x86_64-with-glibc2.33
[debug] exe versions: ffmpeg 4.4.1 (setts), ffprobe 4.4.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.01.21, Current version: 2022.01.21
yt-dlp is up to date (2022.01.21)
[debug] [generic] Extracting URL: https://www.channel4.com/programmes/no-angels/on-demand/33369-001
[generic] 33369-001: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] 33369-001: Downloading webpage
[generic] 33369-001: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://www.channel4.com/programmes/no-angels/on-demand/33369-001
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1367, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1437, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 612, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.10/site-packages/yt_dlp/extractor/generic.py", line 3966, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.channel4.com/programmes/no-angels/on-demand/33369-001

[dave@ArcoLinuxB Desktop]$
```

**Comment by nyuszika7h** [comment]
This website uses Widevine DRM, it cannot be supported.

**Comment by Davetheraveuk** [comment]
Okay, thank you.
