### ISSUE TITLE
add a flag to upload to the Internet Archive

### ISSUE THREAD

**Issue by upintheairsheep** [yt-dlp/yt-dlp#2608]
### Checklist

- [X] I'm reporting a feature request
- [X] I've verified that I'm running yt-dlp version **2022.01.21**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

add a flag --upload-to-ia or --upload that uploads to the internet archive like tubeup dows. Add another flag, --delete-after-upload that deletes the files after it uploads it to the internet archive qualified.

**Comment by pukkandan** [comment]
Out of scope
