### ISSUE TITLE
Loom support

### ISSUE THREAD

**Issue by upintheairsheep** [yt-dlp/yt-dlp#2609]
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.01.21**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

All

### Example URLs

see description

## Checklist

- [x] I'm reporting a new site support request
- [x] I've verified that I'm running youtube-dl version **2020.12.14**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that none of provided URLs violate any copyrights
- [x] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

- Single video: https://www.loom.com/share/0dadc9eb8d07475eab099dd55032e742 (DEAD LINK)
- Video with lots of metadata and its up: https://www.loom.com/share/24351eb8b317420289b158e4b7e96ff2
- More links: http://web.archive.org/web/*/https://www.loom.com/share/*

## Description

A screen recording software

### Verbose log

```shell
none
```

**Comment by upintheairsheep** [comment]
the video contains useful metadata

**Comment by miller1212** [comment]
Dm let me solve your issues

**Comment by pukkandan** [comment]
The link gives 404 in browser

And you didn't fill out verbose log

**Comment by upintheairsheep** [comment]
https://www.loom.com/share/24351eb8b317420289b158e4b7e96ff2

**Comment by upintheairsheep** [comment]
> The link gives 404 in browser
> 
> And you didn't fill out verbose log

https://www.loom.com/share/24351eb8b317420289b158e4b7e96ff2
