### ISSUE TITLE
llatest yt-dlp_min detected as Gen:Variant.Tedy.69821 before download completes

### ISSUE THREAD

**Issue by adanvdo** [yt-dlp/yt-dlp#2612]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

I am running into a strange issue with yt-dlp_min.exe being detected as a Trojan Tedy.69821 before I even confirm the download.  It's quite confusing to me. 

In both chrome and firefox when I attempt to download the latest yt-dlp_min.exe release, as soon as I click on the link Bitdefender detects an infection and starts analyzing the file.

I was not aware that this was how the browsers work, but they actually begin a partial download to either my default downloads directory (chrome) or AppData\Local\Temp (firefox) before I confirm that I want to save the file.

I have not had any problems with the Windows zip or the standard exe file, I have not been able to find anything related to that particular "infection"

When I run an analysis on VirusTotal, it is reported clean by all agents including BitDefender.  Even more confusion.

I am not demanding anything be done about this, but I wanted to inform you about the issue.

![2022-02-02_18-55-10](https://user-images.githubusercontent.com/26498008/152257808-bc00c407-cd32-4966-ad00-65395a74173b.jpg)
![2022-02-02_18-47-56](https://user-images.githubusercontent.com/26498008/152257817-7fa36933-c0ba-44a8-9318-8f15895e79bc.jpg)

**Comment by pukkandan** [comment]
#25

**Comment by pukkandan** [comment]
> I am not demanding anything be done about this, but I wanted to inform you about the issue.

Thanks for letting us know, but there really is nothing to be done about it

**Comment by adanvdo** [comment]
fyi @pukkandan the issue no longer exists with the latest release
