### ISSUE TITLE
the site https://music.163.com is broken (netease:album)

### ISSUE THREAD

**Issue by AustinMemeLord** [yt-dlp/yt-dlp#2613]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.01.21**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Description

I am trying to download an album from this website: https://music.163.com/#/album?id=71813265

yt-dlp gives me "netease:album" 

The errors I am getting are:

"An extractor error has occurred" (most common one)

If I keep spamming "yt-dlp -F https://music.163.com/#/album?id=71813265" or "yt-dlp https://music.163.com/#/album?id=71813265" it will eventually "start" (nothings downloads) It stays frozen for a long time on "Checking song URL" before spitting out these: "urlopen error timed out" or "No video formats found!" 

![Captaure1](https://user-images.githubusercontent.com/33107045/152263889-a05d7336-2553-4513-8e93-a529e52e59f9.PNG)

![Captaure2](https://user-images.githubusercontent.com/33107045/152264252-268b7ee8-92c0-4d18-a83f-040ec82646bb.PNG)

### Verbose log

```shell
[debug] Command-line config: ['-vU', 'https://music.163.com/#/album?id=71813265']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.01.21 [f20d607] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] exe versions: ffmpeg 4.4-full_build-www.gyan.dev (setts), ffprobe 4.4-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.01.21, Current version: 2022.01.21
yt-dlp is up to date (2022.01.21)
[debug] [netease:album] Extracting URL: https://music.163.com/#/album?id=71813265
[netease:album] 71813265: Downloading album data
ERROR: 71813265: An extractor error has occurred. (caused by KeyError('album')); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "yt_dlp\extractor\common.py", line 612, in extract
  File "yt_dlp\extractor\neteasemusic.py", line 205, in _real_extract
KeyError: 'album'
Traceback (most recent call last):
  File "yt_dlp\extractor\common.py", line 612, in extract
  File "yt_dlp\extractor\neteasemusic.py", line 205, in _real_extract
KeyError: 'album'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1367, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1437, in __extract_info
  File "yt_dlp\extractor\common.py", line 642, in extract
yt_dlp.utils.ExtractorError: 71813265: An extractor error has occurred. (caused by KeyError('album')); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
```

**Comment by pukkandan** [comment]
The URL doesn't open for me in browser. Possibly geo-blocked?

**Comment by AustinMemeLord** [comment]
> The URL doesn't open for me in browser. Possibly geo-blocked?

URL opens for me, the songs are blanked out. I think it's geo-blocked also because when I go to click on a song it gives "Due to copyright protection, it is temporarily unavailable in your region."

![rer](https://user-images.githubusercontent.com/33107045/152267763-6462fdea-46cc-409f-8bb2-221db469ba7a.PNG)

Should yt-dlp be able to bypass this? (I am assuming that because there's support for "netease" on the supported list file, which matches the website title that is displayed in the tab thing.) I tried using a VPN on the website to no avail.

**Comment by pukkandan** [comment]
> Should yt-dlp be able to bypass this?

No
> - [x] I've checked that all provided URLs are alive and playable in a browser

---

> I tried using a VPN on the website to no avail.

Are you saying you can't access the video in browser through VPN? If so, nothing we can do. The extractor is broken only if you can access the video in browser but yt-dlp can't download it

**Comment by AustinMemeLord** [comment]
> Are you saying you can't access the video in browser through VPN? If so, nothing we can do. The extractor is broken only if you can access the video in browser but yt-dlp can't download it

It's not videos, they are song links as for as I can tell.

I can access the website without a VPN, I tried using a VPN to change my location to see if it will let me view the songs and it didn't work.

Sorry for the confusion.
