### ISSUE TITLE
Instagram: Requested format is not available

### ISSUE THREAD

**Issue by wxolp** [yt-dlp/yt-dlp#2614]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.01.21**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United States

### Description

If I install like this:

~~~
pip install https://github.com/yt-dlp/yt-dlp/archive/master.zip
~~~

### Verbose log

I get this result:

~~~
[debug] Command-line config: ['--verbose', '--username', 'PRIVATE', '--password', 'PRIVATE', 'https://www.instagram.com/p/CZVEugIPkVn/']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.01.21 [f20d607b0]
[debug] Lazy loading extractors is disabled
[debug] Python version 3.9.9 (CPython 64bit) - Windows-10-10.0.18363-SP0
[debug] exe versions: ffmpeg 2021-06-30-git-de8e6e67e7-essentials_build-www.gyan.dev (setts)
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[Instagram] Downloading login webpage
[Instagram] Logging in
[debug] [Instagram] Extracting URL: https://www.instagram.com/p/CZVEugIPkVn/
[Instagram] CZVEugIPkVn: Downloading webpage
WARNING: "url" field is missing or empty - skipping format, there is an error in extractor
[debug] Default format spec: bestvideo*+bestaudio/best
ERROR: [Instagram] CZVEugIPkVn: Requested format is not available
Traceback (most recent call last):
  File "C:\python\lib\site-packages\yt_dlp\YoutubeDL.py", line 1381, in wrapper
    return func(self, *args, **kwargs)
  File "C:\python\lib\site-packages\yt_dlp\YoutubeDL.py", line 1465, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "C:\python\lib\site-packages\yt_dlp\YoutubeDL.py", line 1517, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "C:\python\lib\site-packages\yt_dlp\YoutubeDL.py", line 2592, in process_video_result
    raise ExtractorError('Requested format is not available', expected=True,
yt_dlp.utils.ExtractorError: [Instagram] CZVEugIPkVn: Requested format is not available
~~~

**Comment by MinePlayersPE** [comment]
There is no video attached to the post?
