### ISSUE TITLE
Not interested in live stream

### ISSUE THREAD

**Issue by Lucabenj** [yt-dlp/yt-dlp#2622]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

How can I download a youtube playlist but not download the current live video streams?

**Comment by pukkandan** [comment]
`--match-filter !is_live`

**Comment by Lucabenj** [comment]
> `--match-filter !is_live`

Thank you very much!
