### ISSUE TITLE
2022.02.03 doesn't work

### ISSUE THREAD

**Issue by Catishere** [yt-dlp/yt-dlp#2626]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.02.03**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

The latest build 2022.02.03 broke my app.
As you can see in the verbose log yt-dlp.exe ( 2022.02.03 ) fails with Error: None, but
yt-dlp.exe ([2022.01.21](https://github.com/yt-dlp/yt-dlp/releases/tag/2022.01.21)) works fine.

### Verbose log

```shell
PS C:\Folders> ./yt-dlp.exe --verbose -x --extract-audio --audio-format wav "ytsearch: Adele - Hello" --ppa "ffmpeg: -bitexact -ac 1 -ab 352k -ar 22050"
[debug] Command-line config: ['--verbose', '-x', '--extract-audio', '--audio-format', 'wav', 'ytsearch: Adele - Hello', '--ppa', 'ffmpeg: -bitexact -ac 1 -ab 352k -ar 22050']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.02.03 [28469ed] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] exe versions: ffmpeg 4.0.2, ffprobe 4.0.2
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [youtube:search] Extracting URL: ytsearch: Adele - Hello
[download] Downloading playlist:  Adele - Hello
ERROR: None
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1381, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1685, in <lambda>
  File "yt_dlp\utils.py", line 2731, in __getitem__
  File "yt_dlp\extractor\youtube.py", line 4295, in _search_results
  File "yt_dlp\extractor\youtube.py", line 758, in _extract_response
  File "yt_dlp\extractor\youtube.py", line 415, in _extract_context
  File "yt_dlp\extractor\youtube.py", line 390, in _get_default_ytcfg
KeyError: None

[youtube:search] playlist  Adele - Hello: Downloading 0 videos
[download] Finished downloading playlist:  Adele - Hello
```

**Comment by coletdjnz** [comment]
fixed in https://github.com/yt-dlp/yt-dlp/commit/af5c1c553e0147fad5f386f42058186e1952ee4e
