### ISSUE TITLE
Piping audio source

### ISSUE THREAD

**Issue by Pringlers** [yt-dlp/yt-dlp#2627]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

What is the best way to download audio only from YouTube and other sources and pipe it?

1. You cannot mix `-x` option with `-o -`, means you cannot download *audio only* and pipe it.
2. Downloading audio manually from the URL returned by command used with `-g` flag is throttled by YouTube's n parameter challenge

So what is the supposed way to do?

**Comment by pukkandan** [comment]
`-f ba`
