### ISSUE TITLE
Instagram Stories: able or unable? 

### ISSUE THREAD

**Issue by anunasica** [yt-dlp/yt-dlp#2632]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

Hi, are you sure that your app is able to download Insta stories?
Insta stories for me means https://www.instagram.com/stories/alessandra__masi/2765355312017058776/
or, if there are more than one story, https://www.instagram.com/stories/alessandra__masi/
For download them I had to use web services. But I read that your app officially supports stories (even inthe changelog), therefore I dont understand. thanks.

**Comment by pukkandan** [comment]
Search for existing issues, or open a broken site issue if your issue is not already reported
