### ISSUE TITLE
SyntaxError: future feature annotations is not defined

### ISSUE THREAD

**Issue by LittleTerry** [yt-dlp/yt-dlp#2633]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.02.03**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

I'm trying to download this video：

yt-dlp --embed-chapters --embed-metadata --embed-thumbnail https://www.youtube.com/watch?v=GBvQvi79Fw4

but it said：

SyntaxError: future feature annotations is not defined

### Verbose log

```shell
(autopy) C:\Users\Terry\PycharmProjects\exercise\YT_download>yt-dlp --embed-chapters --embed-metadata --embed-thumbnail https://www.youtube.com/watch?v=GBvQvi79Fw4
Traceback (most recent call last):
  File "C:\ProgramData\Miniconda3\envs\autopy\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\ProgramData\Miniconda3\envs\autopy\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Miniconda3\envs\autopy\Scripts\yt-dlp.exe\__main__.py", line 4, in <module>
  File "C:\ProgramData\Miniconda3\envs\autopy\lib\site-packages\yt_dlp\__init__.py", line 16, in <module>
    from .options import (
  File "C:\ProgramData\Miniconda3\envs\autopy\lib\site-packages\yt_dlp\options.py", line 27, in <module>
    from .downloader.external import list_external_downloaders
  File "C:\ProgramData\Miniconda3\envs\autopy\lib\site-packages\yt_dlp\downloader\__init__.py", line 40, in <module>
    from .websocket import WebSocketFragmentFD
  File "C:\ProgramData\Miniconda3\envs\autopy\lib\site-packages\yt_dlp\downloader\websocket.py", line 7, in <module>
    import websockets
  File "C:\ProgramData\Miniconda3\envs\autopy\lib\site-packages\websockets\__init__.py", line 1
    from __future__ import annotations
    ^
SyntaxError: future feature annotations is not defined
```

**Comment by pukkandan** [comment]
The issue seems to be in the websockets (optional) library. What is your python version? and what version of websockets do you have?

**Comment by LittleTerry** [comment]
> The issue seems to be in the websockets (optional) library. What is your python version? and what version of websockets do you have?

My python version was 3.6.13. Websockets's version is 10.1.
I just upgrade the python version to 3.7.4, but it still gave me the same error.

**Comment by pukkandan** [comment]
what does `pythom3 -VV` show?

**Comment by LittleTerry** [comment]
> what does `python3 -VV` show?

![image](https://user-images.githubusercontent.com/19617725/152474198-84fd37d9-fce2-4aab-97a2-e5b749c07b2e.png)

**Comment by LittleTerry** [comment]
> what does `python3 -VV` show?

![image](https://user-images.githubusercontent.com/19617725/152474303-7365ac31-1a89-4c9c-9096-fcc694eecf6f.png)

**Comment by pukkandan** [comment]
Websockets 10.1 only supports py3.7 and above. https://pypi.org/project/websockets/. Try either uninstalling or downgrading the module
