### ISSUE TITLE
Nicovideo subtitles and danmaku/comments

### ISSUE THREAD

**Issue by KoleckOLP** [yt-dlp/yt-dlp#2636]
### Checklist

- [X] I'm reporting a site feature request
- [X] I've verified that I'm running yt-dlp version **2022.02.04**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Global, Japan

### Example URLs

https://www.nicovideo.jp/watch/sm17003341

### Description

I would like to be able to download subtitles and danmaku/comments text that appear on screen.

There used to be this fork of the original YoutubeDL that used to be able to do this but now it's probably outdated and does not have a public build https://github.com/animelover1984/youtube-dl

Could this be inplemented to yt-dlp

### Verbose log

```shell
[debug] Command-line config: ['-vU', 'https://www.nicovideo.jp/watch/sm17003341', '--write-sub', '--all-subs']
[debug] Encodings: locale cp1250, fs utf-8, out utf-8, err utf-8, pref cp1250
[debug] yt-dlp version 2022.02.04 [c1653e9ef]
[debug] Python version 3.10.0 (CPython 64bit) - Windows-10-10.0.19041-SP0
[debug] exe versions: none
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.02.04, Current version: 2022.02.04
yt-dlp is up to date (2022.02.04)
[debug] [niconico] Extracting URL: https://www.nicovideo.jp/watch/sm17003341
[niconico] sm17003341: Downloading webpage
[niconico] sm17003341: Downloading video info page
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: best/bestvideo+bestaudio
[info] sm17003341: Downloading 1 format(s): h264_360p-aac_64kbps
[debug] Invoking downloader on "niconico_dmc:sm17003341/archive_h264_360p/archive_aac_64kbps"
[download] みんなコロブチカないじゃない！ [sm17003341].mp4 has already been downloaded
[download] 100% of 11.86MiB
```

**Comment by Lesmiscore** [comment]
> [animelover1984/youtube-dl](https://github.com/animelover1984/youtube-dl)

This fork is actually copying code from [GPL-licensed library called danmaku2ass](https://github.com/m13253/danmaku2ass), which cannot be copied into yt-dlp.
We could use it as an external dependency though. (but we can't install it via pip,as it lacks setup.py :thinking:)

P.S. lol

**Comment by pukkandan** [comment]
Can't we download danmaku (as json?), but not convert it? Any convertion can be left for the user to do with third party tools (using --exec or plugin PPs)
