### ISSUE TITLE
microsoft.com embedded videos

### ISSUE THREAD

**Issue by nicolaasjan** [yt-dlp/yt-dlp#2638]
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.02.04**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

The Netherlands

### Example URLs

https://www.microsoft.com/en-us/videoplayer/embed/RWL07e

### Description

mp4 can be downloaded by passing:
  
`yt-dlp "https://wus-streaming-video-rt-microsoft-com.akamaized.net/064e1812-e02f-4fea-aff8-af73e11b3661/b6d9ea70-00f6-4786-be08-4fc9d1bf.ism/manifest(format=mpd-time-csf)"  `

But this results in a weird file name:
`manifest(format=mpd-time-csf).mp4`

### Verbose log

```shell
yt-dlp -v https://www.microsoft.com/en-us/videoplayer/embed/RWL07e
[debug] Command-line config: ['-v', 'https://www.microsoft.com/en-us/videoplayer/embed/RWL07e']
[debug] User config "/home/nico/.config/yt-dlp/config": ['-o', '/dev/shm/test-dlp/%(title)s.%(ext)s', '-f', 'bestvideo[height<=1080][ext=mp4][vcodec!*=av01]+bestaudio[ext=m4a]/best[ext=mp4]/best', '--no-mtime', '--add-metadata', '--convert-thumbnails', 'jpg', '--embed-thumbnail', '--ppa', 'ThumbnailsConvertor:-q:v 1', '--ppa', 'ffmpeg:-metadata synopsis=""', '--force-ipv4', '--sponsorblock-remove', 'all', '--console-title', '--downloader', 'aria2c', '--downloader-args', 'aria2c:-x 10 -s 10 -j 10 -k 1M --log-level=info --file-allocation=none']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.02.04 [c1653e9ef] (zip)
[debug] Python version 3.8.10 (CPython 64bit) - Linux-5.4.0-97-generic-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg N-105256-g6c4074e423-Nico-20220110-with-non-monotonous-DTS-Fix (fdk,setts), ffprobe N-105256-g6c4074e423-Nico-20220110-with-non-monotonous-DTS-Fix, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome, secretstorage, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [generic] Extracting URL: https://www.microsoft.com/en-us/videoplayer/embed/RWL07e
[generic] RWL07e: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] RWL07e: Downloading webpage
[generic] RWL07e: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://www.microsoft.com/en-us/videoplayer/embed/RWL07e
Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1381, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1451, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 612, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/generic.py", line 3986, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.microsoft.com/en-us/videoplayer/embed/RWL07e
```

**Comment by coletdjnz** [comment]
Video metadata and streams are fetched from this api call: `https://prod-video-cms-rt-microsoft-com.akamaized.net/vhs/api/videos/<video id>`

Not quite sure where the domain comes from but it's probably fine to hard-code.
