### ISSUE TITLE
[tvthek.orf.at]  Unable to extract playlist

### ISSUE THREAD

**Issue by someziggyman** [yt-dlp/yt-dlp#2649]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.02.04**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

anywhere

### Description

Test Link:
 https://tvthek.orf.at/topic/Politik/13869653/ZIB-2/14103221/Schallenberg-zu-Rettungsbemuehungen/14985822

Test link provided does not seem to be GEO restricted.
This one seems to work though:
https://tvthek.orf.at/profile/Wien-heute/70018/Wien-heute/14123078/Diskussion-um-Teststrategie/15094569

### Verbose log

```shell
./yt-dlp -v -F https://tvthek.orf.at/topic/Politik/13869653/ZIB-2/14103221/Schallenberg-zu-Rettungsbemuehungen/14985822
[debug] Command-line config: ['-v', '-F', 'https://tvthek.orf.at/topic/Politik/13869653/ZIB-2/14103221/Schallenberg-zu-Rettungsbemuehungen/14985822']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.02.03 [28469edd7] (zip)
[debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
[debug] Python version 3.9.10 (CPython 64bit) - macOS-11.6.3-arm64-arm-64bit
[debug] exe versions: none
[debug] Optional libraries: sqlite
[debug] Proxy map: {}
[debug] [orf:tvthek] Extracting URL: https://tvthek.orf.at/topic/Politik/13869653/ZIB-2/14103221/Schallenberg-zu-Rettungsbemuehungen/14985822
[orf:tvthek] 14103221: Downloading webpage
ERROR: [orf:tvthek] 14103221: Unable to extract playlist; please report this issue on  https://github.com/yt-dlp/yt-dlp , filling out the "Broken site" issue template properly. Confirm you are on the latest version using -U; please report this issue on  https://github.com/yt-dlp/yt-dlp , filling out the "Broken site" issue template properly. Confirm you are on the latest version using -U
  File "/Users/zig/Downloads/DrB/yt-dlp/./yt-dlp/yt_dlp/extractor/common.py", line 612, in extract
    ie_result = self._real_extract(url)
  File "/Users/zig/Downloads/DrB/yt-dlp/./yt-dlp/yt_dlp/extractor/orf.py", line 186, in _real_extract
    self._search_regex(
  File "/Users/zig/Downloads/DrB/yt-dlp/./yt-dlp/yt_dlp/extractor/common.py", line 1186, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
```

**Comment by dirkf** [comment]
With or without `--geo-bypass-country AT`, https://tvthek.orf.at/topic/Politik/13869653/ZIB-2/14103221/Schallenberg-zu-Rettungsbemuehungen/14985822 redirects to the site's home page from the UK.

What happens if you run the test with `--print-traffic`? Does it now show redirecting to https://tvthek.orf.at/?

Whereas (eg) https://tvthek.orf.at/topic/Politik/13869653/ZIB-2/14122887/Erschuetterte-Buendnisse-in-Italien/15093961 finds a playlist with 9 items where the main video on the page is the first item and 2-9 are videos from a related clip carousel, another case where `--no-playlist` ought to be the default. See https://github.com/ytdl-org/youtube-dl/issues/30564.

**Comment by someziggyman** [comment]
Oh, wow. Strange. It does the same on my end as well (even with AT vpn enabled) Did not redirect to main page yesterday.

Here are other test links (no redirect):
https://tvthek.orf.at/history/Oesterreichs-Zeitzeugen/13425177
https://tvthek.orf.at/topic/News/13869393

LOG:
yt-dlp -v -F https://tvthek.orf.at/history/Oesterreichs-Zeitzeugen/13425177
[debug] Command-line config: ['-v', '-F', 'https://tvthek.orf.at/history/Oesterreichs-Zeitzeugen/13425177']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.02.03 [28469edd7] (zip)
[debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
[debug] Python version 3.9.10 (CPython 64bit) - macOS-11.6.3-arm64-arm-64bit
[debug] exe versions: none
[debug] Optional libraries: sqlite
[debug] Proxy map: {}
[debug] [orf:tvthek] Extracting URL: https://tvthek.orf.at/history/Oesterreichs-Zeitzeugen/13425177
[orf:tvthek] 13425177: Downloading webpage
ERROR: [orf:tvthek] 13425177: Unable to extract playlist; please report this issue on  https://github.com/yt-dlp/yt-dlp , filling out the "Broken site" issue template properly. Confirm you are on the latest version using -U; please report this issue on  https://github.com/yt-dlp/yt-dlp , filling out the "Broken site" issue template properly. Confirm you are on the latest version using -U
  File "/Users/zig/Downloads/DrB/yt-dlp/./yt-dlp/yt_dlp/extractor/common.py", line 612, in extract
    ie_result = self._real_extract(url)
  File "/Users/zig/Downloads/DrB/yt-dlp/./yt-dlp/yt_dlp/extractor/orf.py", line 186, in _real_extract
    self._search_regex(
  File "/Users/zig/Downloads/DrB/yt-dlp/./yt-dlp/yt_dlp/extractor/common.py", line 1186, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)

**Comment by dirkf** [comment]
This would be fixed with a test patch to the yt-dl extractor that I made for the linked issue (not the posted patch), but the yt-dlp extractor is a bit fancier and the patch doesn't apply directly.

Basically, if no JSON is found as the value of the `data-jsb` attribute of a `<div>` whose classname contains `VideoPlaylist`, the programme links have to be extracted from `<a href=...>` elements.

I guess some unification is needed to fix both issues at once.

**Comment by ds2k5** [comment]
Hi,
using: Version 2023.11.16

URL: https://tvthek.orf.at/livestream/Neue-Geschichten-vom-Pumuckl-Koboldsgesetz/14270760

./yt-dlp https://tvthek.orf.at/livestream/Neue-Geschichten-vom-Pumuckl-Koboldsgesetz/14270760

ERROR: [orf:tvthek] 14270760: Unable to extract playlist; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

**Comment by seproDev** [comment]
The tvthek is no longer available.
