### ISSUE TITLE
Media downloader ; Unable to download JSON metadata: HTTP Error 404: Not Found 

### ISSUE THREAD

**Issue by Amudon** [yt-dlp/yt-dlp#2650]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

Hello, I am using media downloader because the youtube dl refuse to work on my computer as well as Python.
The media downloader as well as Stacher worked fine before but now do the error : Unable to download JSON metadata: HTTP Error 404: Not Found  ''

I don't know what to do. Please consider English is not my main language

### Verbose log

```shell
[FranceTVSite] 3042541-tout-va-bien-integral: Downloading webpage
[FranceTV] 99c34ca5-c22a-419c-8dca-9daef50dc368: Downloading video JSON
ERROR: [FranceTV] 99c34ca5-c22a-419c-8dca-9daef50dc368: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
```

**Comment by pukkandan** [comment]
You can ask the media downloader dev @mhogomchungu how to obtain the verbose log. Then open a "broken site" report with the verbose log and filling out form appropriately. We can't hlp you with the information you have given

**Comment by mhogomchungu** [comment]
@Amudon 

Try to download again using "basic downloader" tab in "Media Downloader" and then post all the text that were produced.
