### ISSUE TITLE
Cannot download aged restricted

### ISSUE THREAD

**Issue by nrafaelos** [yt-dlp/yt-dlp#2651]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.02.04**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

Cannot download - aged restricted 
https://www.youtube.com/watch?v=wlPNnVEINMM

### Verbose log

```shell
22:03:38, youtube-dl (external): 2022.2.4
22:03:38, libcurl (internal): libcurl/7.68.0 Schannel zlib/1.2.11 brotli/1.0.7 nghttp2/1.40.0
22:03:38, ffmpeg (internal): lavf 58.29.100, lavc 58.54.100, lavu 56.31.100
22:03:38, #01, Analysis, https://www.youtube.com/watch?v=wlPNnVEINMM
22:03:38, #01, Opening given Youtube URL...
22:03:45, [warning] youtube-dl: ERROR: [youtube] wlPNnVEINMM: Sign in to confirm your age. This video may be inappropriate for some users.
22:03:45, [warning] #01, youtube-dl: [youtube] wlPNnVEINMM: Sign in to confirm your age. This video may be inappropriate for some users.
22:03:45, [warning] youtube-dl finished with error code 1
22:03:46, [warning] #01, This video may be inappropriate for some users.
```

**Comment by pukkandan** [comment]
Only some age-restricted videos can be downloaded without an account. Pass logged in (but not necessarily age-verified) cookies

**Comment by aleksejrs** [comment]
Cookies don't help.

**Comment by october262** [comment]
> Cookies don't help.

video downloaded ok for me using the cookies file & signed in to youtube

**Comment by pukkandan** [comment]
> Cookies don't help.

Provide verbose log

**Comment by aleksejrs** [comment]
It works with cookies from a Firefox profile, but not with cookies.txt exported using Export Cookies. I am using containers, but I think I did so most of the time.

```
$ yt-dlp --ignore-config --verbose --cookies cookies.txt https://www.youtube.com/watch?v=wlPNnVEINMM
[debug] Command-line config: ['--ignore-config', '--verbose', '--cookies', 'cookies.txt', 'https://www.youtube.com/watch?v=wlPNnVEINMM']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.02.04 [c1653e9ef] (zip)
[debug] Python version 3.9.2 (CPython 64bit) - Linux-5.10.0-10-amd64-x86_64-with-glibc2.33
[debug] exe versions: ffmpeg 4.3.3-0, ffprobe 4.3.3-0, rtmpdump 2.4
[debug] Optional libraries: Cryptodome, secretstorage, mutagen, sqlite
[debug] Proxy map: {}
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=wlPNnVEINMM
[youtube] wlPNnVEINMM: Downloading webpage
[youtube] wlPNnVEINMM: Downloading android player API JSON
[youtube] wlPNnVEINMM: Downloading android agegate player API JSON
[youtube] wlPNnVEINMM: Downloading web agegate player API JSON
ERROR: [youtube] wlPNnVEINMM: Sign in to confirm your age. This video may be inappropriate for some users.
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 612, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/youtube.py", line 3246, in _real_extract
    self.raise_no_formats(reason, expected=True)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 1120, in raise_no_formats
    raise ExtractorError(msg, expected=expected, video_id=video_id)
```

**Comment by pukkandan** [comment]
Since it works with `--cookies-from-browser`, you are probably not exporting all the relevant cookies.
