### ISSUE TITLE
Pornhub Premium

### ISSUE THREAD

**Issue by Lucif3rHun1** [yt-dlp/yt-dlp#2653]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.02.04**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United States

### Description

Yt-dlp does not download pornhubpremium videos even after adding credentials.

### Verbose log

```shell
Lucif3rHun1 ERROR: [PornHub] ph616ef5f858aa9: Unable to extract title; please report this issue on  https://github.com/yt-dlp/yt-dlp , filling out the "Broken site" issue template properly. Confirm you are on the latest version using -U; please report this issue on  https://github.com/yt-dlp/yt-dlp , filling out the "Broken site" issue template properly. Confirm you are on the latest version using -U
```

**Comment by Lucif3rHun1** [comment]
[debug] Command-line config: ['-vU', '--netrc-location', 'C:\\Users\\lucigendu\\Desktop\\.netrc', 'https://www.pornhubpremium.com/view_video.php?viewkey=ph61941060ccdaf']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.02.04 [c1653e9] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.22000-SP0
[debug] exe versions: ffmpeg 2022-02-03-git-e1a14479a8-full_build-www.gyan.dev (setts), ffprobe 2022-02-03-git-e1a14479a8-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.02.04, Current version: 2022.02.04
yt-dlp is up to date (2022.02.04)
[debug] [PornHub] Extracting URL: https://www.pornhubpremium.com/view_video.php?viewkey=ph61941060ccdaf
[PornHub] ph61941060ccdaf: Downloading pc webpage
ERROR: [PornHub] ph61941060ccdaf: Unable to extract title; please report this issue on  https://github.com/yt-dlp/yt-dlp , filling out the "Broken site" issue template properly. Confirm you are on the latest version using -U; please report this issue on  https://github.com/yt-dlp/yt-dlp , filling out the "Broken site" issue template properly. Confirm you are on the latest version using -U
  File "yt_dlp\extractor\common.py", line 612, in extract
  File "yt_dlp\extractor\pornhub.py", line 300, in _real_extract
  File "yt_dlp\extractor\common.py", line 1195, in _html_search_regex
  File "yt_dlp\extractor\common.py", line 1186, in _search_regex

**Comment by Lucif3rHun1** [comment]
So should i just paste my account here?

**Comment by pukkandan** [comment]
No! When someone decides to work on this, they will ask for account details (if they dont have one). The labels are so devs can easily identify that you are willing to share account if asked

**Comment by Lucif3rHun1** [comment]
ok

**Comment by Bricio** [comment]
Ow....

You didn't use `--netrc` parameter.
That way yt-dlp don't read .netrc file
