### ISSUE TITLE
Performing the last file merges manually on an improperly ended livestream.

### ISSUE THREAD

**Issue by Ninmi** [yt-dlp/yt-dlp#2658]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

Quite often livestreams have hiccups or they just don't end properly, leaving `*.mp4.part`, `*.mp4.part-Frag[number].part` and `*.mp4.ytdl` files around. Is there a way to initiate the final merge on these files manually?

Edit:  
I found this https://github.com/yt-dlp/yt-dlp/pull/888#issuecomment-1001505184, but it does not deal with the last fragments.

**Comment by pukkandan** [comment]
The `part-frag` files that are left behind are incomplete and therefore useless. The `.ytdl` file contains data needed for resuming and can be ignored. You just need to merge the 2 `.part` files with ffmpeg.

**Comment by Ninmi** [comment]
The part-frag *does* play back normally and is position right after `.part` file, so deleting it would essentially remove a portion of the original stream, even if only a tiny bit. Is there no way to concatenate the `part-frag` files in?

**Comment by DirkDort** [comment]
Ninmi,

I experienced this only once, and the part-frag-files really were of very limited use.

You can use TSSplitter for example (a freeware that is no longer developed, but a working version can be found on an established site called "Videohelp" - probably known to most here. Most other file joiner/splitter software will probably work as well). Just join the video and audio files separately, and mux them with FFMPEG or any other suitable program.

The resulting video played fine in my case, but the audio was cut off at some point, On closer inspection of the original (frag) files, they just were incomplete. I guess there must have been a major glitch during the stream, which lead to these "part-frag" files.

Well, I'm neither a professional for FFMPEG nor for YT-DLP nor for video processing in general, just experienced and sometimes solved some problems over the years. I totally trust pukkandan's expertise. You will probably only gain a few seconds of additional, usable video/audio (if at all) by joining the files. But then again, it's not really time-consuming or difficult, so maybe worth a try. 

Hope this is helpful.

**Comment by pukkandan** [comment]
You can concatenate the files `cat part-frag-file >> part-file` which is basically what yt-dlp does once the fragment is complete

**Comment by krichbanana** [comment]
You should be able to kludge it in python as well using yt_dlp.

```python3
from yt_dlp.postprocessor import FFmpegConcatPP, FFmpegMergerPP

def concat(in_files, out_file):
    # [name.fNNN.mp4.part, name.fNNN.mp4.part-FragMMMM.part, ...] -> name.fNNN.mp4
    fileconcatpp = FFmpegConcatPP(None)
    fileconcatpp.concat_files(in_files, out_file)

def merge(in_files, out_file):
    # [name.fNNN.mp4, name.fMMM.mp4] -> name.mp4
    filemergerpp = FFmpegMergerPP()
    filemergerpp.run_ffmpeg_multiple_files(
        in_files,
        out_file,
        [
            "-hide_banner",
            "-loglevel", "repeat+info",
            "-y",
            "-c", "copy",
            "-movflags", "+faststart",
        ],
    )

```

**Comment by Ninmi** [comment]
Thank you all for the answers!

> You can concatenate the files `cat part-frag-file >> part-file` which is basically what yt-dlp does once the fragment is complete

I can't believe you can just `cat` them together. Looks like it worked.

I might as well try the python script if this ends up happening too often, to automate things.

**Comment by DirkDort** [comment]
Well, I used the --live-from-start option, because I was a little late to the show, and it ended with 2 video and 2 audio files, all of them with .mp4 extension, though 2 of them rather were .m4a. The fragmented second audio file at least was incomplete, for what reason ever.

It was a short streaming, 6 minutes or so, with New Year's wishes on YouTube by an artist I follow, nothing vital, but I just merged the files anyway.

The stream was immediately deleted afterwards, not just set to private.

Something like this only happened once to me till now.

That's all I can say. Hope this is of use for the further development of YT-DLP.

**Comment by conkerts** [comment]
I'll just join, I have the same issue half of the time.
Sometimes it decides to properly merge, sometimes not, i haven't really found any logic/pattern behind it.
Quite annoying actually.
I am using it at least with the -k option so it keeps all the parts, so i don't have to download everything again.

**Comment by user334** [comment]
I just have to manually finish the download process of a live stream with yt-dlp so the *part* files were not merged properly. All I left with were a bunch of this files: 
```
video.mp4.part-Frag1
video.mp4.part-Frag2
....
video.mp4.part-Frag6494
video.mp4.part-Frag6495
```
I've done this things to fix it: 
`ls | sort -V > videos.txt` - make a list of part fragments with the numbers growing sequentially
The file format should be like one `string file 'filename'` on a new line so I've added this prefix and suffix to each line with an [external program](https://www.gtrigonakis.com/textworkflow) (that was easier for me atm). 
`ffmpeg -f concat -i videos.txt -c copy output9.mp4` - to actually concatenate videos into a single file
`rm *Frag*` - to remove leftovers
