### ISSUE TITLE
[youtube:tab] Redirects to home when given an invalid playlist id

### ISSUE THREAD

**Issue by coletdjnz** [yt-dlp/yt-dlp#2660]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.02.04**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

mostly everywhere

### Description

Given an invalid playlist id, e.g. `https://youtube.com/playlist?list=badid`, YouTube redirects to the home page. Currently the tab extractor follows this redirect, making it look like it is downloading the playlist. 

(On contrary, if the playlist id is a valid playlist id, but the playlist does not exist, YouTube does not redirect and gives us the error)

I think it might be worth seeing it we can prevent the former from happening if possible to prevent user confusion in the case they accidentally add or remove a character from the id.

### Verbose log

```shell
$ yt-dlp -v "https://youtube.com/playlist?list=badid"                             
[debug] Command-line config: ['-v', 'https://youtube.com/playlist?list=badid']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.02.04 [c1653e9ef]
[debug] Lazy loading extractors is disabled
[debug] Python version 3.10.1 (CPython 64bit) - Linux-5.15.12-1-MANJARO-x86_64-with-glibc2.33
[debug] exe versions: ffmpeg 4.4.1 (setts), ffprobe 4.4.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome, secretstorage, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [youtube:tab] Extracting URL: https://youtube.com/playlist?list=badid
[youtube:tab] badid: Downloading webpage
[debug] [youtube:tab] Final URL: https://www.youtube.com/playlist?list=badid
[download] Downloading playlist: badid
[youtube:tab] badid page 1: Downloading API JSON
[youtube:tab] badid page 2: Downloading API JSON
[youtube:tab] badid page 3: Downloading API JSON
[youtube:tab] badid page 4: Downloading API JSON
[youtube:tab] badid page 5: Downloading API JSON
^C
```

**Comment by pukkandan** [comment]
Didn't we already fix this once? 🤔

**Comment by coletdjnz** [comment]
> Didn't we already fix this once? thinking

I think we observed this a while back, but don't think we ever fixed it? (unless it was something you did)

**Comment by dirkf** [comment]
In the current yt-dlp master, ll.5024-6 of `extractor/youtube.py` check for the playlist being in the URL, but apparently this isn't an actual HTTP redirect, just YT serving the home page by default with no notice. The page title ("Home - YouTube") is set from JS, so it's not directly available. Video pages with an invalid ID already fail with "Video unavailable".

Maybe look for the playlist_id in the `content` of the `<meta property="og:url" ...>` element, if present?

Like this patch for yt-dl, which I guess would translate straightforwardly to the location in the yt-dlp extractor above:
```
--- a/youtube_dl/extractor/youtube.py
+++ b/youtube_dl/extractor/youtube.py
@@ -3021,6 +3021,10 @@ class YoutubeTabIE(YoutubeBaseInfoExtractor):
                 return self.url_result(video_id, ie=YoutubeIE.ie_key(), video_id=video_id)
             self.to_screen('Downloading playlist %s - add --no-playlist to just download video %s' % (playlist_id, video_id))
         webpage = self._download_webpage(url, item_id)
+        if playlist_id:
+            og_url = self._og_search_property('url', webpage, default='')
+            if not og_url or playlist_id not in og_url:
+               self.report_warning('''This YouTube page doesn't match the requested playlist "%s"''' % (playlist_id, ))
         data = self._extract_yt_initial_data(item_id, webpage)
         tabs = try_get(
             data, lambda x: x['contents']['twoColumnBrowseResultsRenderer']['tabs'], list)
```
And this result:
```
$ python -m youtube_dl -F  "https://youtube.com/playlist?list=badid"
[youtube:tab] badid: Downloading webpage
WARNING: [youtube:tab] This YouTube page doesn't match the requested playlist "badid"
[download] Downloading playlist: badid
[youtube:tab] Downloading page 1
[youtube:tab] Downloading page 2
...
```
Or the download could be aborted?

**Comment by Zirro** [comment]
> Didn't we already fix this once? 🤔

We discussed it here a while ago, though you did not see any viable solutions at the time: https://github.com/yt-dlp/yt-dlp/issues/147#issuecomment-792226423

**Comment by Fabian42** [comment]
Is there anything I can do to work around this for now, without writing my own `wget`-based parser? I tried things like `--get-id`, but of course they apply per video, no matter where it comes from. I tried `--reverse-playlist`, hoping it would fail in some way because the recommendation stream is infinite, but it just starts around 200. Can I somehow get a playlist ID from yt-dlp maybe?

**Comment by Fabian42** [comment]
This also works with the "UU…" playlists for all uploads.  
The "liked videos" playlists works.  
Music mixes don't matter, since that kind of URL doesn't work for them anyway and you don't get redirected to the homepage if you try.  
I can't think of any other edge cases right now.

Bash script example:
```bash
id=1304600592
if [[ $(yt-dlp -o "%(playlist_uploader_id)s" --get-filename --playlist-end 1 "youtube.com/playlist?list=$id") != "NA" ]]; then
 yt-dlp "youtube.com/playlist?list=$id"
else
 echo "some failure output"
fi
```

(Have fun finding out where that number comes from. ;) It was my first test case when I started going down this rabbit hole.)

If you're extra paranoid (or know something about the channel ID syntax than I don't), you can use `--output-na-placeholder` and compare to anything else instead.

My first attempt at a `wget` parsed failed because of the consent popup BTW. I didn't research this further, but it would likely be very annoying to get around that.

**Comment by Fabian42** [comment]
Confirmed fixed.
