### ISSUE TITLE
Failed install yt-dlp on iOS with a-Shell

### ISSUE THREAD

**Issue by cgand** [yt-dlp/yt-dlp#2662]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.02.04**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

Failed to install yt-dlp on iPad via a-Shell (while I’ve succesfully installed youtube-dl)
A-Shell is a Terminal for iOS https://github.com/holzschu/a-shell
Installation failed when setup.py stuck preparing  #metadata.

Thanks for support.

P.S. no problem installing yt-dlp on macOS via terminal

### Verbose log

```shell
$ pip install --upgrade pip
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pip in /private/var/mobile/Containers/Data/Application/23ED609F-10D3-4C5B-A8C2-601B462B0639/Library/lib/python3.9/site-
packages (21.3.1)
Collecting pip
  Downloading pip-22.0.3-py3-none-any.whl (2.1 MB)
     |████████████████████████████████| 2.1 MB 7.1 MB/s            
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 21.3.1
    Uninstalling pip-21.3.1:
      Successfully uninstalled pip-21.3.1
Successfully installed pip-22.0.3
$ pip install --upgrade youtube-dl
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: youtube-dl in /private/var/mobile/Containers/Data/Application/23ED609F-10D3-4C5B-A8C2-601B462B0639/Library/lib/python3.
9/site-packages (2021.12.17)
$ python3 -m pip install -U yt-dlp
Defaulting to user installation because normal site-packages is not writeable
Collecting yt-dlp
  Using cached yt_dlp-2022.2.4-py2.py3-none-any.whl (2.5 MB)
Collecting mutagen
  Using cached mutagen-1.45.1-py3-none-any.whl (218 kB)
Collecting pycryptodomex
  Using cached pycryptodomex-3.14.1.tar.gz (3.4 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [0 lines of output]
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed
× Encountered error while generating package metadata.
╰─> See above for output.
note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
$ 
```

**Comment by cgand** [comment]
Solved by a-Shell developer:

> yt-dlp requires pycryptodomex, which has some C components, so it cannot be installed on iOS since there are no C compilers. 
> 
> The recommanded solution is to disable dependencies: "pip install yt-dlp --no-deps". 
>

**Comment by coletdjnz** [comment]
related: https://github.com/holzschu/a-shell/issues/331

since this is not a yt-dlp issue, I will close this

**Comment by pukkandan** [comment]
How to install without deps is also given in the readme

**Comment by cgand** [comment]
Yes, I also tried with no dependencies and it didn't work. It worked after I've to updated pip.
Happy that yt-dlp work on iOS.
Sorry. Thanks.
