### ISSUE TITLE
https://fmovies.to/

### ISSUE THREAD

**Issue by Lignite4** [yt-dlp/yt-dlp#2667]
### Checklist

- [X] I'm reporting a site feature request
- [X] I've verified that I'm running yt-dlp version **2022.02.04**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

everywhere

### Example URLs

https://fmovies.to/series/the-book-of-boba-fett-17zjq/1-2

https://fmovies.to/movie/the-ice-age-adventures-of-buck-wild-zk5w3/1-full

### Description

I would like to be able to download the movies and tv shows from here.

### Verbose log

```shell
[debug] Command-line config: ['-vU', 'https://fmovies.to/series/the-book-of-boba-fett-17zjq/1-2']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.02.04 [c1653e9] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] exe versions: none
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.02.04, Current version: 2022.02.04
yt-dlp is up to date (2022.02.04)
[debug] [generic] Extracting URL: https://fmovies.to/series/the-book-of-boba-fett-17zjq/1-2
[generic] 1-2: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] 1-2: Downloading webpage
[generic] 1-2: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://fmovies.to/series/the-book-of-boba-fett-17zjq/1-2
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1381, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1451, in __extract_info
  File "yt_dlp\extractor\common.py", line 612, in extract
  File "yt_dlp\extractor\generic.py", line 3986, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://fmovies.to/series/the-book-of-boba-fett-17zjq/1-2
```

**Comment by Lesmiscore** [comment]
![image](https://user-images.githubusercontent.com/10355528/152744971-bdf10208-498f-4f39-b12a-4c6a53ce2da0.png)

**Comment by Lignite4** [comment]
How come this was closed?

**Comment by pukkandan** [comment]
We will not support piracy sites

**Comment by Lignite4** [comment]
There are already a lot of sites which break ToS by allowing people to download. Including multiple streaming sites.
