### ISSUE TITLE
[Discussion] Drop support for Python 2 and jython?

### ISSUE THREAD

**Issue by fstirlitz** [yt-dlp/yt-dlp#267]
As was [noticed already](https://github.com/yt-dlp/yt-dlp/pull/247#issuecomment-821643791), the test suite experiences intermittent failures when testing under Jython, because `pip` fails to install `nose`. Using the `-vv` option reveals this:

> Could not fetch URL https://pypi.python.org/simple/nose/: 403 Client Error: [[[!!! BREAKING CHANGE !!!]]] Support for clients that do not support Server Name Indication is temporarily disabled and will be permanently deprecated soon. See https://status.python.org/incidents/hzmjhqsdjqgb and https://github.com/pypa/pypi-support/issues/978 [[[!!! END BREAKING CHANGE !!!]]] for url: https://pypi.python.org/simple/nose/ - skipping

This means this breakage is intentional, and the test suite is soon going to break completely.

Jython hasn’t had a release for more than a year, and the <https://github.com/jython/jython/> repository has not had any commits for 9 months. SNI support in Jython’s TLS implementation was [first requested in 2015](https://bugs.jython.org/issue2446), and apparently hasn’t been ever worked on. Let’s face it, Jython is obsolete. And so is Python 2.6, which doesn’t support SNI either, and yet this project still nominally claims to maintain compatibility with it (although it’s not actually included in the test suite, so it might have been broken already).

This might be as good an occasion as any to drop support for Python 2 completely. Doing so would enable us to take advantage of innovations brought by Python 3, like:
- more granular function signatures (I already had to put a [pretty nasty hack](https://github.com/yt-dlp/yt-dlp/pull/247/commits/4f1ad1b6cf4f14f56d1be5450936f824951bab2a#diff-b7f6633815316063666fc3ecebb970e68fdcb5ee01beba03d04c01830e55e8a6R3325-R3330) in a pull request for the sake of Python 2 support)
- `pathlib` (to replace fragile pathname manipulation code)
- dataclasses (as a replacement for passing fixed-key dicts around)
- type annotations (a type checker could be added to catch bugs in extractors earlier)
- native asynchronous programming (might be useful for parallel downloads)
- `__init_subclass__` (to simplify the giant list of imports in `extractors.py` and plugin loading)
- `html.parser` (to replace all the shoddy regex scraping)

Alternatively, the test suite failures could be worked around by manually downloading the packages. (Like upstream [already did](https://github.com/ytdl-org/youtube-dl/commit/999329cf6b29878d054c6ccdd24573489a2886d5).) But that would be just delaying the inevitable. Let’s put those zombies in the grave.

**Comment by pukkandan** [comment]
I personally think we should maintain support for the older versions as long as `youtube-dl` does the same. But I'll keep this issue open coz I want to hear others' opinions on this.

**Comment by Ashish0804** [comment]
I agree with OP, there's no point in maintaining py2 support, the language itself isn't supported anymore. As of being more welcoming to new users, imo anyone who knows how to install python 2, can already install python 3. All tutorials online tell you to install python3. As of youtube-dl, imo this project has changed a lot from youtube-dl, i don't see why maintain py2 support just bcoz ytdl does so.

I might have missed something so if anyone is using py2, please lemme know how you are using yt-dlp.

**Comment by colethedj** [comment]
I also agree with OP and @Ashish0804 that there shouldn't be a requirement to keep python 2 support, as well as some of the improvements it could bring mentioned. `websockets` support comes to mind too.

Though, imo if we were to make any large improvements/overhauls to the codebase as a whole using python 3 features I feel like it would be better implemented upstream? It seems like a big task for the current size of this project in comparison (yt-dlp vs youtube-dl). But that's also dependent on if upstream would be willing to move anyways...

**Comment by pukkandan** [comment]
To clarify - right now, I am not open to moving the existing codebase to remove all python 2 compatibility; but only for not caring about it in future code.

The reason for it is that if we were to clean up the existing code, it would become impossibly difficult for me to frequently merge with upstream code. In general, as long as no functionality is sacrificed, our code must maintain similarity to the upstream code

**Comment by fstirlitz** [comment]
To be clear, I’m not advocating for rewriting everything from scratch either. All the potential improvements can be performed incrementally, while maintaining compatibility with upstream extractors. But things like the `compat` module could be significantly trimmed down, for example, and we could start introducing our own extractor helper methods that take advantage of Python 3 features.

**Comment by pukkandan** [comment]
btw, @colethedj We don't need to deprecate python 2 for `websockets` support. All that is required is that the import failure be handled gracefully. This is a requirement for all non-standard libraries. Have a look at the `concurrent.futures`, `pycryptodome` and `mutagen` imports in various places in the code

**Comment by fstirlitz** [comment]
Python 2 support is already kind of broken and undertested.

When I tried testing #247 under Python 2 on <https://devstreaming-cdn.apple.com/videos/streaming/examples/bipbop_16x9/bipbop_16x9_variant.m3u8>, I noticed that the HLS downloader contains a reference to `FileNotFoundError`, which didn’t exist before Python 3.3. And it wasn’t due to any code I wrote; it was added in 4cf1e5d2f9.

**Comment by pukkandan** [comment]
I had made announcement regarding this discussion in both [discord](https://discord.gg/H5MNcFW63r) and [youtube-dl sub-reddit](https://www.reddit.com/r/youtubedl/comments/myvpay) (A lot of yt-dlp users are there) and have not received any real arguments to keep py2 compatibility. So we will move forward with the decision to drop support. 

So,
1. In the next release, I will announce that py2 support has been deprecated, a warning will be issued whenever py2 is used and documentation will be updated
2. After a couple more releases, obsolete tests will be removed and developers will be allowed to make breaking changes
3. All compatibility wrappers (like `compat_str`) will be kept as-is unless it is actually detrimental
4. Any new features (like using `html.parser`) should only compliment and never replace the existing functions. This will ensure we can keep merging extractors from upstream with relative ease
5. At least for the time-being, I am opposed to making changes that would require massive rewrites (like using dataclasses)

If anyone feels differently about any of these, do let me know

---

Also, while we are at it, we need to decide which py3 versions we should support. While `youtube-dl` supports py3.2+, versions 3.5 and below are actually at end-of-life already and 3.6 will EOL by the end of the year. So my first instinct is to think of supporting 3.6+ only and to keep dropping support for versions in future as soon as they reach eol

But a significant roadblock for this is that we have no real standalone executable for UNIX. The release package `yt-dlp` is actually a source zip with a python shebang. I assume those running from `pip` or the source are generally tech-savy enough to update their python if necessary, but those using the releases often may not be. So if we are doing this, it would be useful to provide standalone executable for UNIX similar to the windows release

**Comment by Ashish0804** [comment]
> Also, while we are at it, we need to decide which py3 versions we should support. While `youtube-dl` supports py3.2+, versions 3.5 and below are actually at end-of-life already and 3.6 will EOL by the end of the year. So my first instinct is to think of supporting 3.6+ only and to keep dropping support for versions in future as soon as they reach eol

As i mentioned before, a big reason to drop py2 support is that it's not supported.
So while we are at it, it's better to drop support for 3.6 and below just so we don't have a similar issue 1 year from now.
As of what minimum py3 version to support, i recommend to support atleast the version currently on google colab.
As of 4th May 2021 it's `Python 3.7.10`

**Comment by fstirlitz** [comment]
CPython ≤ 3.6 may be EOL soon, but other implementations not necessarily so. PyPy is still maintained, and only claims to target the 3.6 version of the language (though it implements some later features as well). Stackless targets 3.7. The still-in-development 3.x branch of IronPython apparently targets 3.4, but this may change. GraalPython targets 3.8.

As for distributions: Debian buster (current stable) provides 3.7, Ubuntu bionic (old LTS) provides 3.6, focal (current LTS) provides 3.8, CentOS 7 provides 3.6, openSUSE Leap 15.2 provides 3.6.

I think 3.6 is at a certain sweet spot in that it has enough of the modern Python features to be comfortable to use, but still widely supported even in (current) LTS distro releases and not too demanding of implementations to practically lock the project to a single one.

> I assume those running from `pip` or the source are generally tech-savy enough to update their python if necessary, but those using the releases often may not be. So if we are doing this, it would be useful to provide standalone executable for UNIX similar to the windows release

Non-technical users most likely have Python installed through their package manager, and those provide a relatively recent version of Python 3 already, even the LTS releases, as I mentioned above. If the user is capable of upgrading anything at all, they can upgrade Python just as easily.

There isn’t an established toolchain to generate stand-alone Python executables on Unix anyway. Nobody expects this. I wouldn’t bother either.

**Comment by Mathnerd314** [comment]
Regarding pypy, stackless, etc., there don't seem to be any advantages to running yt-dlp under a different implementation, because it's network-bound. So I think only the standard CPython implementation needs to be considered.

One question is what version of Python the README should recommend to use. I would say to recommend whatever version the most yt-dlp developers are using. I guess it would be 3.8 or 3.9.

**Comment by pukkandan** [comment]
We'll only be testing for (and therefore officially supporting) PyPy and CPython

**Comment by stefnotch** [comment]
Is there an upstream (youtube-dl) discussion regarding dropping support for Python 2? If not, would it be worthwhile to start one?

**Comment by pukkandan** [comment]
https://github.com/ytdl-org/youtube-dl/issues/5697

There is also
https://github.com/ytdl-org/youtube-dl/issues/9751
https://github.com/ytdl-org/youtube-dl/pull/14515

**Comment by pirate486743186** [comment]
This was discussed before youtube-dl development stopped. Now yt-dlp is not just a fork, it has become the new youtube-dl.

ubuntu 16.04 and debian 9 (stretch) are on python 3.5
debian 9 EOL is 2022 and ubuntu 16.04 2024
I personally don't use those, but i think i saw some people complaining in a youtube-dl issue about yt-dlp and requiring a too new python version.

officially asking on the youtube-dl issues is probably the best way to see if they are still users that actually need older python versions. Asking existing yt-dlp users will just give a biased answer.

**Comment by pukkandan** [comment]
> Now yt-dlp is not just a fork, it has become the new youtube-dl.

Just because youtube-dl devs have gone missing, you cannot expect me to start doing things the way youtube-dl has done them. Whether you want to see yt-dlp as just a fork with some nifty new features or as the "new youtube-dl" is up to you.

The fact is that we have already removed support for python 3.5 (which is past EOL btw) and support for it is not going to be added back. If anyone wants to, they are always free to fork yt-dlp and keep just the work on just the compatibility code. But I am unwilling to bear that overhead

**Comment by nyuszika7h** [comment]
> ubuntu 16.04 and debian 9 (stretch) are on python 3.5
> debian 9 EOL is 2022 and ubuntu 16.04 2024

You are right about Debian 9 LTS support ending in 9 months, I missed that. However, Ubuntu 16.04 already became EOL 5 months ago according to https://endoflife.date/ubuntu.

**Comment by pirate486743186** [comment]
The ESR is free for individual personal use, i don't remember the exact conditions. You just need to register yourself (free). I'm not aware of a possible extension for debian 9.

I personally don't use old stuff like this. Some might have good reasons to.
For example there's blackberry 10 with python 3.2 that will finally die this january.

I'm saying to go ask them in youtube-dl issues to see how much of a demand there is.
Contrary to normal applications, you are forced to use the latest yt-dlp.

Of course... there's an entirely different possibility. Setting up an LTS release.
You could take the last youtube-dl and make it the first LTS release.
That would mean no new features in the core, backport extractors, and drop python support above 3.6 . When it dies, freeze a new version from the bleeding edge release. 
It might actually be easier this way rather then try and squease multiple python version in the same executable. I always thought of that been a bit insane.

**Comment by Ashish0804** [comment]
It's been almost 3 months since we dropped py2 support.
No point in discussing who should we ask if they want py2 support or not now.

**Comment by pirate486743186** [comment]
@nyuszika7h
lol, speak of the devil, they just upgraded 14.04 and 16.04 to 10 years
https://ubuntu.com/advantage
