### ISSUE TITLE
I need help selecting quality

### ISSUE THREAD

**Issue by modernCRTuser** [yt-dlp/yt-dlp#2671]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

Hello

Sorry for asking here, I don't speak English well and don't know where else to ask
I search here for an answer and see there is no easy way to select best quality
I found that best quality now is AV1 codec (I can play it) but I want to select it above everything else then H264 and then the rest
What should cmd command look like in that case?

Also is it possible to download best available (no matter resolution) and convert it to background to 720p 2pass q20 vbr mode somehow automatically and delete original big resolution file via cmd/ytdlp commands?

**Comment by modernCRTuser** [comment]
Thanks for your reply!

So H264 is 1st in order by default and we make AV1 in front of it by that command? H264 will still have priority over VP9?

I usually work with other GUI based software to convert videos after they are downloaded and never did it via console commands unfortunately. I just wanted to automate this process. To download best version possible and then automatically convert it to something like 720p 2pass profile with slow preset. Because YT does such an awful job at converting stuff even 1080p somehow looks subpar 720p if not 480p. So I thought converting best available 4k option can give me good quality achieved from 4k downscale and small size too but it is annoying to manually set up the whole process after files are downloaded plus they are not deleted automatically to free up space

**Comment by pukkandan** [comment]
> So H264 is 1st in order by default and we make AV1 in front of it by that command? H264 will still have priority over VP9?

No. Re-reading your question, I see I misunderstood what you wanted to do. `-S vcodec` will set the order to `av01 > vp9 > h265 > h264 > ...`. It is currently not possible to set it as av1 > h264 > vp9 using -S (can be done with `-f`). However, we can use the fact that av1 and h264 are served in mp4 to set `-S ext:mp4,vcodec`

> and then automatically convert it to something like 720p 2pass profile with slow preset.

You will have to figure out the ffmpeg command for that. You can try asking in some ffmpeg community

Though honestly, youtube probably does better encoding that whatever you do. So it is better imo to just download the 720p from youtube directly
