### ISSUE TITLE
Use it as Module

### ISSUE THREAD

**Issue by gaetan1903** [yt-dlp/yt-dlp#2673]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

How to use it as module ?

like 
```python
import yt_dlp

yt_dlp.download(url)
```

**Comment by pukkandan** [comment]
https://github.com/yt-dlp/yt-dlp#embedding-yt-dlp

**Comment by gaetan1903** [comment]
Thank you, it's similar youtube-dl
