### ISSUE TITLE
Hotstar Broken Site

### ISSUE THREAD

**Issue by Abhijit47** [yt-dlp/yt-dlp#2674]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.02.04**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Description

[hotstar] 1770002746: Unable to download JSON metadata: HTTP Error 402: Payment Required (caused by <HTTPError 402: 'Payment Required'>); please report this issue on  https://github.com/yt-dlp/yt-dlp , filling out the "Broken site" issue template properly.

### Verbose log

```shell
[debug] Command-line config: ['-vU', 'https://www.hotstar.com/in/movies/royal-bengal-rahashya/1770002746']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.02.04 [c1653e9ef] (source)
[debug] Lazy loading extractors is disabled
[debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
[debug] Python version 3.9.0 (CPython 64bit) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg git-2020-05-04-5767a2e, ffprobe git-2020-05-04-5767a2e
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.02.04, Current version: 2022.02.04
yt-dlp is up to date (2022.02.04)
[debug] [hotstar] Extracting URL: https://www.hotstar.com/in/movies/royal-bengal-rahashya/1770002746
[hotstar] 1770002746: Downloading JSON metadata
[hotstar] 1770002746: Downloading webpage
[hotstar] 1770002746: Downloading token
[hotstar] 1770002746: Downloading JSON metadata
ERROR: [hotstar] 1770002746: Unable to download JSON metadata: HTTP Error 402: Payment Required (caused by <HTTPError 402: 'Payment Required'>); please report this issue on  https://github.com/yt-dlp/yt-dlp , filling out the "Broken site" issue template properly. Confirm you are on the latest version using -U (caused by <HTTPError 402: 'Payment Required'>); please report this issue on  https://github.com/yt-dlp/yt-dlp , filling out the "Broken site" issue template properly. Confirm you are on the latest version using -U
  File "D:\Python tools\yt-dlp-master\yt_dlp\extractor\common.py", line 730, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "D:\Python tools\yt-dlp-master\yt_dlp\YoutubeDL.py", line 3558, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "C:\Program Files\Python39\lib\urllib\request.py", line 523, in open
    response = meth(req, response)
  File "C:\Program Files\Python39\lib\urllib\request.py", line 632, in http_response
    response = self.parent.error(
  File "C:\Program Files\Python39\lib\urllib\request.py", line 561, in error
    return self._call_chain(*args)
  File "C:\Program Files\Python39\lib\urllib\request.py", line 494, in _call_chain
    result = func(*args)
  File "C:\Program Files\Python39\lib\urllib\request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
```

**Comment by pukkandan** [comment]
Pass cookies of an account that has access to the content. If that doesn't work, show its verbose log

**Comment by Abhijit47** [comment]
> Pass cookies of an account that has access to the content. If that doesn't work, show its verbose log

can you please help how can i use cookies

**Comment by Abhijit47** [comment]
> log in to your browser, and then pass `--cookies-from-browser chrome`, replacing `chrome`with your browser of choice

D:\Python tools\yt-dlp-master>yt-dlp -F --cookies-from-browser chrome https://www.hotstar.com/in/movies/eternals/1260077949 -vU
[debug] Command-line config: ['-F', '--cookies-from-browser', 'chrome', 'https://www.hotstar.com/in/movies/eternals/1260077949', '-vU']
[Cookies] Extracting cookies from chrome
[debug] Extracting cookies from: "C:\Users\ABHIJIT KARMAKAR\AppData\Local\Google\Chrome\User Data\Default\Network\Cookies"
[Cookies] Extracted 1415 cookies from chrome
[debug] cookie version breakdown: {'v10': 1415, 'other': 0, 'unencrypted': 0}
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.02.04 [c1653e9ef] (source)
[debug] Lazy loading extractors is disabled
[debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
[debug] Python version 3.9.0 (CPython 64bit) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg git-2020-05-04-5767a2e, ffprobe git-2020-05-04-5767a2e
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.02.04, Current version: 2022.02.04
yt-dlp is up to date (2022.02.04)
[debug] [hotstar] Extracting URL: https://www.hotstar.com/in/movies/eternals/1260077949
[hotstar] 1260077949: Downloading JSON metadata
[hotstar] 1260077949: Downloading webpage
[hotstar] 1260077949: Downloading JSON metadata
[hotstar] 1260077949: Downloading MPD manifest
[hotstar] 1260077949: Downloading MPD manifest
[hotstar] 1260077949: Downloading MPD manifest
[hotstar] 1260077949: Downloading m3u8 information
[hotstar] 1260077949: Downloading MPD manifest
[hotstar] 1260077949: Downloading m3u8 information
[hotstar] 1260077949: Downloading m3u8 information
[hotstar] 1260077949: Downloading MPD manifest
[hotstar] 1260077949: Downloading m3u8 information
[hotstar] 1260077949: Downloading MPD manifest
[hotstar] 1260077949: Downloading m3u8 information
[hotstar] 1260077949: Downloading MPD manifest
[hotstar] 1260077949: Downloading m3u8 information
[hotstar] 1260077949: Downloading m3u8 information
[hotstar] 1260077949: Downloading m3u8 information
[hotstar] 1260077949: Downloading MPD manifest
[hotstar] 1260077949: Downloading m3u8 information
[hotstar] 1260077949: Downloading MPD manifest
[hotstar] 1260077949: Downloading m3u8 information
[hotstar] 1260077949: Downloading m3u8 information
[hotstar] 1260077949: Downloading MPD manifest
[hotstar] 1260077949: Downloading MPD manifest
[hotstar] 1260077949: Downloading MPD manifest
[hotstar] 1260077949: Downloading m3u8 information
[hotstar] 1260077949: Downloading MPD manifest
[hotstar] 1260077949: Downloading MPD manifest
[hotstar] 1260077949: Downloading MPD manifest
[hotstar] 1260077949: Downloading m3u8 information
[hotstar] 1260077949: Downloading MPD manifest
[hotstar] 1260077949: Downloading MPD manifest
[hotstar] 1260077949: Downloading MPD manifest
[hotstar] 1260077949: Downloading MPD manifest
[hotstar] 1260077949: Downloading m3u8 information
[hotstar] 1260077949: Downloading MPD manifest
[hotstar] 1260077949: Downloading MPD manifest
[hotstar] 1260077949: Downloading MPD manifest
[hotstar] 1260077949: Downloading MPD manifest
[hotstar] 1260077949: Downloading m3u8 information
[hotstar] 1260077949: Downloading MPD manifest
[hotstar] 1260077949: Downloading m3u8 information
[hotstar] 1260077949: Downloading MPD manifest
[hotstar] 1260077949: Downloading MPD manifest
[hotstar] 1260077949: Downloading m3u8 information
[hotstar] 1260077949: Downloading MPD manifest
[hotstar] 1260077949: Downloading MPD manifest
[hotstar] 1260077949: Downloading MPD manifest
[hotstar] 1260077949: Downloading m3u8 information
[hotstar] 1260077949: Downloading MPD manifest
[hotstar] 1260077949: Downloading m3u8 information
[hotstar] 1260077949: Downloading MPD manifest
[hotstar] 1260077949: Downloading m3u8 information
[hotstar] 1260077949: Downloading MPD manifest
[hotstar] 1260077949: Downloading m3u8 information
[hotstar] 1260077949: Downloading MPD manifest
[hotstar] 1260077949: Downloading MPD manifest
[hotstar] 1260077949: Downloading m3u8 information
[hotstar] 1260077949: Downloading MPD manifest
[hotstar] 1260077949: Downloading m3u8 information
[hotstar] 1260077949: Downloading m3u8 information
[hotstar] 1260077949: Downloading MPD manifest
[hotstar] 1260077949: Downloading MPD manifest
[hotstar] 1260077949: Downloading MPD manifest
[hotstar] 1260077949: Downloading MPD manifest
[hotstar] 1260077949: Downloading MPD manifest
[hotstar] 1260077949: Downloading MPD manifest
[hotstar] 1260077949: Downloading m3u8 information
[hotstar] 1260077949: Downloading m3u8 information
[hotstar] 1260077949: Downloading MPD manifest
[hotstar] 1260077949: Downloading MPD manifest
[hotstar] 1260077949: Downloading MPD manifest
[hotstar] 1260077949: Downloading MPD manifest
[hotstar] 1260077949: Downloading MPD manifest
[hotstar] 1260077949: Downloading MPD manifest
[hotstar] 1260077949: Downloading MPD manifest
[hotstar] 1260077949: Downloading MPD manifest
[hotstar] 1260077949: Downloading MPD manifest
[hotstar] 1260077949: Downloading MPD manifest
[hotstar] 1260077949: Downloading m3u8 information
[hotstar] 1260077949: Downloading m3u8 information
[hotstar] 1260077949: Downloading MPD manifest
[hotstar] 1260077949: Downloading MPD manifest
[hotstar] 1260077949: Downloading MPD manifest
[hotstar] 1260077949: Downloading m3u8 information
[hotstar] 1260077949: Downloading MPD manifest
[hotstar] 1260077949: Downloading MPD manifest
[hotstar] 1260077949: Downloading MPD manifest
[hotstar] 1260077949: Downloading MPD manifest
[hotstar] 1260077949: Downloading MPD manifest
[hotstar] 1260077949: Downloading MPD manifest
[hotstar] 1260077949: Downloading MPD manifest
[hotstar] 1260077949: Downloading MPD manifest
[hotstar] 1260077949: Downloading MPD manifest
[hotstar] 1260077949: Downloading m3u8 information
[hotstar] 1260077949: Downloading MPD manifest
[hotstar] 1260077949: Downloading MPD manifest
[hotstar] 1260077949: Downloading m3u8 information
[hotstar] 1260077949: Downloading MPD manifest
[hotstar] 1260077949: Downloading m3u8 information
[hotstar] 1260077949: Downloading MPD manifest
[hotstar] 1260077949: Downloading MPD manifest
[hotstar] 1260077949: Downloading m3u8 information
[hotstar] 1260077949: Downloading m3u8 information
[hotstar] 1260077949: Downloading m3u8 information
[hotstar] 1260077949: Downloading m3u8 information
[hotstar] 1260077949: Downloading MPD manifest
[hotstar] 1260077949: Downloading m3u8 information
[hotstar] 1260077949: Downloading m3u8 information
[hotstar] 1260077949: Downloading MPD manifest
[hotstar] 1260077949: Downloading m3u8 information
[hotstar] 1260077949: Downloading MPD manifest
[hotstar] 1260077949: Downloading m3u8 information
[hotstar] 1260077949: Downloading m3u8 information
[hotstar] 1260077949: Downloading MPD manifest
[hotstar] 1260077949: Downloading MPD manifest
[hotstar] 1260077949: Downloading MPD manifest
[hotstar] 1260077949: Downloading MPD manifest
[hotstar] 1260077949: Downloading m3u8 information
[hotstar] 1260077949: Downloading m3u8 information
[hotstar] 1260077949: Downloading MPD manifest
[hotstar] 1260077949: Downloading m3u8 information
[hotstar] 1260077949: Downloading MPD manifest
[hotstar] 1260077949: Downloading MPD manifest
[hotstar] 1260077949: Downloading m3u8 information
[hotstar] 1260077949: Downloading MPD manifest
[hotstar] 1260077949: Downloading MPD manifest
[hotstar] 1260077949: Downloading MPD manifest
[hotstar] 1260077949: Downloading m3u8 information
[hotstar] 1260077949: Downloading MPD manifest
[hotstar] 1260077949: Downloading MPD manifest
[hotstar] 1260077949: Downloading MPD manifest
[hotstar] 1260077949: Downloading m3u8 information
[hotstar] 1260077949: Downloading MPD manifest
[hotstar] 1260077949: Downloading MPD manifest
[hotstar] 1260077949: Downloading MPD manifest
[hotstar] 1260077949: Downloading m3u8 information
[hotstar] 1260077949: Downloading MPD manifest
[hotstar] 1260077949: Downloading MPD manifest
[hotstar] 1260077949: Downloading MPD manifest
[hotstar] 1260077949: Downloading m3u8 information
[hotstar] 1260077949: Downloading m3u8 information
[hotstar] 1260077949: Downloading MPD manifest
[hotstar] 1260077949: Downloading MPD manifest
[hotstar] 1260077949: Downloading m3u8 information
[hotstar] 1260077949: Downloading MPD manifest
[hotstar] 1260077949: Downloading MPD manifest
[hotstar] 1260077949: Downloading MPD manifest
[hotstar] 1260077949: Downloading m3u8 information
[hotstar] 1260077949: Downloading MPD manifest
[hotstar] 1260077949: Downloading MPD manifest
[hotstar] 1260077949: Downloading MPD manifest
[hotstar] 1260077949: Downloading MPD manifest
[hotstar] 1260077949: Downloading m3u8 information
[hotstar] 1260077949: Downloading m3u8 information
[hotstar] 1260077949: Downloading m3u8 information
[hotstar] 1260077949: Downloading MPD manifest
[hotstar] 1260077949: Downloading m3u8 information
[hotstar] 1260077949: Downloading m3u8 information
[hotstar] 1260077949: Downloading MPD manifest
[hotstar] 1260077949: Downloading MPD manifest
[hotstar] 1260077949: Downloading MPD manifest
[hotstar] 1260077949: Downloading MPD manifest
[hotstar] 1260077949: Downloading MPD manifest
[hotstar] 1260077949: Downloading m3u8 information
[hotstar] 1260077949: Downloading MPD manifest
[hotstar] 1260077949: Downloading MPD manifest
[hotstar] 1260077949: Downloading m3u8 information
[hotstar] 1260077949: Downloading MPD manifest
[hotstar] 1260077949: Downloading MPD manifest
[hotstar] 1260077949: Downloading MPD manifest
[hotstar] 1260077949: Downloading m3u8 information
[hotstar] 1260077949: Downloading m3u8 information
[hotstar] 1260077949: Downloading m3u8 information
[hotstar] 1260077949: Downloading m3u8 information
[hotstar] 1260077949: Downloading MPD manifest
[hotstar] 1260077949: Downloading m3u8 information
[hotstar] 1260077949: Downloading MPD manifest
[hotstar] 1260077949: Downloading MPD manifest
[hotstar] 1260077949: Downloading m3u8 information
[hotstar] 1260077949: Downloading MPD manifest
[hotstar] 1260077949: Downloading MPD manifest
[hotstar] 1260077949: Downloading m3u8 information
[hotstar] 1260077949: Downloading MPD manifest
[hotstar] 1260077949: Downloading MPD manifest
[hotstar] 1260077949: Downloading MPD manifest
[hotstar] 1260077949: Downloading MPD manifest
[hotstar] 1260077949: Downloading m3u8 information
[hotstar] 1260077949: Downloading m3u8 information
[hotstar] 1260077949: Downloading m3u8 information
[hotstar] 1260077949: Downloading MPD manifest
[hotstar] 1260077949: Downloading MPD manifest
[hotstar] 1260077949: Downloading MPD manifest
[hotstar] 1260077949: Downloading m3u8 information
[hotstar] 1260077949: Downloading MPD manifest
[hotstar] 1260077949: Downloading MPD manifest
[hotstar] 1260077949: Downloading MPD manifest
[hotstar] 1260077949: Downloading MPD manifest
[hotstar] 1260077949: Downloading MPD manifest
[hotstar] 1260077949: Downloading m3u8 information
[hotstar] 1260077949: Downloading MPD manifest
[hotstar] 1260077949: Downloading m3u8 information
[hotstar] 1260077949: Downloading MPD manifest
[hotstar] 1260077949: Downloading MPD manifest
[hotstar] 1260077949: Downloading m3u8 information
[hotstar] 1260077949: Downloading MPD manifest
[hotstar] 1260077949: Downloading m3u8 information
[hotstar] 1260077949: Downloading MPD manifest
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
ERROR: [hotstar] 1260077949: This video is DRM protected
Traceback (most recent call last):
  File "D:\Python tools\yt-dlp-master\yt_dlp\YoutubeDL.py", line 1381, in wrapper
    return func(self, *args, **kwargs)
  File "D:\Python tools\yt-dlp-master\yt_dlp\YoutubeDL.py", line 1465, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "D:\Python tools\yt-dlp-master\yt_dlp\YoutubeDL.py", line 1517, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "D:\Python tools\yt-dlp-master\yt_dlp\YoutubeDL.py", line 2431, in process_video_result
    self.raise_no_formats(info_dict)
  File "D:\Python tools\yt-dlp-master\yt_dlp\YoutubeDL.py", line 961, in raise_no_formats
    raise ExtractorError(msg, video_id=info['id'], ie=info['extractor'],
yt_dlp.utils.ExtractorError: [hotstar] 1260077949: This video is DRM protected

is there any chance to fix this error

**Comment by pukkandan** [comment]
DRM protected videos will not be supported
