### ISSUE TITLE
sleep-interval should be triggered for each video in a list, rather than triggered by a download operation

### ISSUE THREAD

**Issue by rolypolyman** [yt-dlp/yt-dlp#2676]
### Checklist

- [X] I'm reporting a feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.02.04**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

**yt-dlp** can easily be used to scrape video comments for an entire channel, with `--skip-download --write-comments [channelURL]` .  This works great.  I don't want the videos, just the comments so I can search them.

The problem is the sleep commands aren't useful for this purpose because --sleep-interval is only triggered by download of a video.

**using no sleep option** will result in a YouTube ban.  If a channel has 1000 videos, with 1000 comments on each one, yt-dlp will plow through it all very quickly with numerous page requests for each video, and there will be an IP block after getting through maybe the first 50-100 videos.

**--sleep-interval** is ignored because it only activates "before each download".  No download of the video content occurs when scraping only comments.

**--sleep-requests** works, but this makes the sleep interval highly variable depending on how many comments are in a video.

I would ask that --sleep-interval be keyed on each iteration through the list of videos, rather than requiring a full video download to trigger it.  So what I would like is something like this, so such downloads can be done safely and responsibly:

`yt-dlp --sleep-interval 600 --skip-download --write-comments https://www.youtube.com/c/DrainAddict/`

This is really the way that sleep-interval should be working in the first place.  Process the first video in the list, wait, then iterate to the next video in the loop.  This should not be keyed entirely on specific types of operations like a full video download.    This would also do away with the need for a separate --sleep-subtitles parameter because it would be handled already by --sleep-interval's corrected behavior.

Thanks!

**Comment by phaolo2** [comment]
Sleep before any download (even single) doesn't make sense, it should be "sleep after download" in case of a playlist 🤷‍♂️
