### ISSUE TITLE
[Feature Request] Add retries to sponskrub

### ISSUE THREAD

**Issue by PabloOQ** [yt-dlp/yt-dlp#268]
## Checklist

- [ X ] I'm reporting a feature request
- [ X ] I've verified that I'm running yt-dlp version **2021.04.22**
- [ X ] I've searched the bugtracker for similar feature requests including closed ones

## Description

First of all, I do not know if this should be considered a "Feature Request" or a "Bug", also I do not know either if this should be submitted here or in the Sponskrub repo, so I apologize if this doesn't belong here.

Sometimes Sponskrub fails (see at the end) when using this command `.\yt-dlp.exe --sponskrub-location .\sponskrub\ --sponskrub-cut -i -x --audio-format mp3 --embed-thumbnail -o 'downloaded_files/test_mp3_updated3/%(title)s.%(ext)s' 'https://www.youtube.com/watch?v=NHKHln_R5HQ&list=PL8mG-RkN2uTynZBZG5c3l-KLBv2pj5tZp' --verbose` .  Also, when it fails it stops processing that video so in this specific case that means the thumbnail does not get embedded, this results in an mp3 file without the Sponskrub cuts and another file wich is the thumbnail (webp, jpg,...) this is how I spotted this error.

Clearly it fails to reach the server, the problem is that the program does not try again, this results in the video being downloaded without being processed by sponskrub and unless I manually check the console and then ctrl+f searching for "got 500" I can't really tell which videos are unprocessed.

My request is to add an option to fix this, here are some solutions I think might work:

- Extractors and downloads already have a retry parameter via yt-dl, as Sponskrub relies on a server it could be beneficial to have this option when using Sponskrub 

- An option wich checks if a video has already been processed by Sponskrub, this could work by either using a file to store this information or by checking the length of the video and comparing it with what should be after Sponskrub

- An option which stores in a file the videos that failed to be processed

## Error 

This error happens at random when trying to replicate it, sometimes it didn't occur and sometimes 4 files didn't got processed by Sponskrub

```
[download] Downloading video 16 of 27
[youtube] Tk6JMSrqiQo: Downloading webpage
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[info] Tk6JMSrqiQo: Downloading format(s) 251
[youtube] Tk6JMSrqiQo: Downloading thumbnail  ...
[youtube] Tk6JMSrqiQo: Writing thumbnail to: downloaded_files\test_mp3_updated3\The CHEAPEST Heatsink on the Market.jpg
[debug] Invoking downloader on 'https://r4---sn-h5qzen76.googlevideo.com/videoplayback?expire=1619209569&ei=AdmCYPHwJYriWdLRvcAH&ip=80.39.196.242&id=o-AJpXaEApLcqAT5l1LqMkq6inlFWXZzBqaGgkz1A-yuVb&itag=251&source=youtube&requiressl=yes&mh=jz&mm=31%2C29&mn=sn-h5qzen76%2Csn-h5q7knes&ms=au%2Crdu&mv=m&mvi=4&pl=17&initcwndbps=1342500&vprv=1&mime=audio%2Fwebm&ns=6FmLqBD13j-7MQt2GKSmWbEF&gir=yes&clen=9767663&dur=664.801&lmt=1540769513077313&mt=1619187894&fvip=4&keepalive=yes&fexp=24001373%2C24007246&c=WEB&txp=5511222&n=tybOXf88iWIspDleZF&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRgIhAOezqBuXidjcQwbYupez-o9rF5kf32lLhu8TU-F9yv_iAiEAqw7hcitp_QTkJblbEUkL3Sfa2EpXn2JkYCPwOEEdQdg%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhAL0gNwWosB7VR4LYVoMJISJvMdm8Dd3CVUQDhzFKAfrYAiBs_IPWd1ftjps2dTNt19CrZp3r9a_cZQDXpPBbhI-smQ%3D%3D'
[download] Destination: downloaded_files\test_mp3_updated3\The CHEAPEST Heatsink on the Market.webm
[download] 100% of 9.32MiB in 00:04
[debug] ffmpeg command line: ffprobe -show_streams "file:downloaded_files\test_mp3_updated3\The CHEAPEST Heatsink on the Market.webm"
[ExtractAudio] Destination: downloaded_files\test_mp3_updated3\The CHEAPEST Heatsink on the Market.mp3
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:downloaded_files\test_mp3_updated3\The CHEAPEST Heatsink on the Market.webm" -vn -acodec libmp3lame "-q:a" 5 "file:downloaded_files\test_mp3_updated3\The CHEAPEST Heatsink on the Market.mp3"
Deleting original file downloaded_files\test_mp3_updated3\The CHEAPEST Heatsink on the Market.webm (pass -k to keep)
[SponSkrub] Trying to remove sponsor sections
WARNING: Cutting out sponsor segments will cause the subtitles to go out of sync.
[debug] sponskrub command line: ".\sponskrub\sponskrub" -- Tk6JMSrqiQo "downloaded_files\test_mp3_updated3\The CHEAPEST Heatsink on the Market.mp3" "downloaded_files\test_mp3_updated3\The CHEAPEST Heatsink on the Market.spons.mp3"
Downloading video sponsor data
Got 500 the server must be broken, try again later
ERROR: Postprocessing: sponskrub failed with error code 6
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 2551, in process_info
  File "yt_dlp\YoutubeDL.py", line 2688, in post_process
  File "yt_dlp\YoutubeDL.py", line 2638, in run_pp
  File "yt_dlp\postprocessor\sponskrub.py", line 94, in run
yt_dlp.utils.PostProcessingError: sponskrub failed with error code 6

```

**Comment by pukkandan** [comment]
if there were errors in any downloads (or postprocessing), `yt-dlp` returns a non-zero exit code. You can rerun the command in that case. Unless you explicitly tell yt-dlp otherwise, the file won't be downloaded again, but only the postprocessing will be run. You can also use `--abort-on-error` if you want

**Comment by PabloOQ** [comment]
Thank you, I didn't know yt-dlp continues post-processing too if it fails. I could solve it with what you said but I still have some questions about that solution, as the only way I could find to solve the problems I found was using regex with the output of `yt-dlp`. Maybe I'm missing something but the exit code is either 0 or 1, there's no way to tell if it failed because of sponskrub or if it was something else, so for example if there is a hidden video it gets stuck as the exit code is always 1.

**Comment by PabloOQ** [comment]
Closing this as it was solved and I'm the only one requesting this feature
