### ISSUE TITLE
Is there a list of progress attributes ?

### ISSUE THREAD

**Issue by section83** [yt-dlp/yt-dlp#2684]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

The YT-DLP readme explains that for the "--progress-template" option, progress attributes are accessible under "progress" key and gives this example:  --progress-template "download-title:%(info.id)s-%(progress.eta)s"

I assume that "eta" is one of the progress attributes.  I found this in "options.py"

>TODO: Document the fields inside "progress"

Does that mean there is no list of all the progress attributes available ?  Yet ?

Thanks.

**Comment by pukkandan** [comment]
These are the "public" progress attributes (except `info_dict`). https://github.com/yt-dlp/yt-dlp/blob/a3125791c7a5cdf2c8c025b99788bf686edd1a8a/yt_dlp/YoutubeDL.py#L364-L383

They are just not documented in the README yet

There are actually more fields, but they are not part of the public API and may change in the future. But they can still be usefull. Set `--progress-template %(progress)j` to see all the fields

**Comment by section83** [comment]
Great, thanks.

**Comment by VorpalBlade** [comment]
Why is this closed? The issue seems to still be around (progress attributes are not documented in README or man page)

**Comment by Grub4K** [comment]
Because they probably shouldn't be documented in the README. Doing so will only duplicate the documentation. like said above, they are in the source as well as available through `--progress-template %(progress)j`

**Comment by Lukanex** [comment]
Hi, I am have not figured out how to use the --progress-template %(progress)j on the dashboard.
There seem to be no attributes like the ones in the YoutubeDL.py linked above.

How can I use them, please?

**Comment by bashonly** [comment]
Shell issue. Quote the argument:  `--progress-template "%(progress)j"`

**Comment by aeakos** [comment]
$ yt-dlp --progress-template "%(progress)j"

Usage: yt-dlp [OPTIONS] URL [URL...]

yt-dlp: error: You must provide at least one URL.
Type yt-dlp --help to see a list of all options.

**Comment by Grub4K** [comment]
Pass any valid video url alongside the `--progress-template`

**Comment by aeakos** [comment]
Thanks, a lot of output, no comprehensive list of fields, I'll try fishing them out of the melee, but better than nothing.

_Update:_
In case they help someone else, these are the fields I extracted from the output:

- _default_template
- _downloaded_bytes_str
- _elapsed_str
- _eta_str
- _percent
- _percent_str
- _speed_str
- _total_bytes_estimate_str
- _total_bytes_str
- ctx_id
- downloaded_bytes
- elapsed
- eta
- filename
- speed
- status
- tmpfilename
- total_bytes

**Comment by bashonly** [comment]
The "public" fields are basically the same as what was listed above: https://github.com/yt-dlp/yt-dlp/issues/2684#issuecomment-1032424355

The availability of the "private" fields (prefixed with underscore) may change at any time

**Comment by snowe2010** [comment]
> Because they probably shouldn't be documented in the README. Doing so will only duplicate the documentation. like said above, they are in the source as well as available through --progress-template %(progress)j

If they are available through `--progress-template %(progress)j` then that should be in the readme and man pages. As it is I had to dig into GH issues in order to find this information.

**Comment by BOplaid** [comment]
> > Because they probably shouldn't be documented in the README. Doing so will only duplicate the documentation. like said above, they are in the source as well as available through --progress-template %(progress)j
> 
> If they are available through `--progress-template %(progress)j` then that should be in the readme and man pages. As it is I had to dig into GH issues in order to find this information.

agreed
