### ISSUE TITLE
[Feature request] Include ffmpeg in binaries

### ISSUE THREAD

**Issue by gamer191** [yt-dlp/yt-dlp#2687]
### Checklist

- [X] I'm reporting a feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.02.04**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

This feature request goes against "[Is anyone going to need the feature?](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-anyone-going-to-need-the-feature)", but I feel like a large number of non-technical users would benefit from ffmpeg being included in the pre-compiled binaries. Is there a reason it isn't (genuine question)?

**Comment by pukkandan** [comment]
No, look for a docker image
