### ISSUE TITLE
diverse questions

### ISSUE THREAD

**Issue by khk58** [yt-dlp/yt-dlp#2692]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

Hi to all, I’m @khk58,

On downloading youtube-playlists, I get lots of the following messages:

1) Private video. Sign in if you've been granted access to this video

2) Video unavailable. The uploader has not made this video available in your country

3) Video unavailable. This video contains content from 'xxx', who has blocked it in your country on copyright grounds, 
         where 'xxx' is one of the following

          A+E Networks
          AdRevEnt_managed
          ARD
          Constantin Film
          DEFA-Stiftung
          E! Entertainment Television
          LDS
          Muyap
          rbb media GmbH
          RTL 2 Fernsehen GmbH & Co. KG
          Satel Film GmbH
          Seven.One
          SME
          Studio Hamburg
          Studio71_1_1
          Studio71_2_4
          Warner Bros. Entertainment
          WMG
          ZDFE
          ZDFE.drama
          
What can I do?

Kind regards,

Kurt

**Comment by nyuszika7h** [comment]
> 1. Private video. Sign in if you've been granted access to this video
If you can play the video in your browser while logged in, use the `--cookies` or `--cookies-from-browser` option.

> 2. Video unavailable. The uploader has not made this video available in your country
> 3. Video unavailable. This video contains content from 'xxx', who has blocked it in your country on copyright grounds,
>    where 'xxx' is one of the following
>    ```
>       A+E Networks
>       AdRevEnt_managed
>       ARD
>       Constantin Film
>       DEFA-Stiftung
>       E! Entertainment Television
>       LDS
>       Muyap
>       rbb media GmbH
>       RTL 2 Fernsehen GmbH & Co. KG
>       Satel Film GmbH
>       Seven.One
>       SME
>       Studio Hamburg
>       Studio71_1_1
>       Studio71_2_4
>       Warner Bros. Entertainment
>       WMG
>       ZDFE
>       ZDFE.drama
>    ```
If you get the same error in your browser, there's nothing yt-dlp can do about it. You can try using a proxy or VPN. Though this sounds a lot like you're trying to download pirated content, which we will not help with.
