### ISSUE TITLE
Request to introduce intermediary algorithms to make large playlist jobs more efficient and much faster

### ISSUE THREAD

**Issue by HalvorRaknes** [yt-dlp/yt-dlp#2693]
### Checklist

- [X] I'm reporting a feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.02.04**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

When specifying download of videos for e.g. a specific date within a large playlist yt-dlp incrementally trudges through the list from the first item to the last, for each file checking to see whether the file date satisfies the date specified (or dates when the `--datebefore` and `--dateafter` are specified). This can take a lot of time. For instance, I just downloaded 14 files dated July 15, 2021 from the 5,442 videos total Rumble channel 'Steve Bannon's War Room'. Downloading itself only took a few minutes but the full yt-dlp process lasted almost 5 hours.

This was for a channel which is only a little over one year old. It would be easy to find examples of channels where this process would have taken a lot longer.

For the channel I chose, yt-dlp started off by first downloading the playlist which was listed out over 220 pages. At this point some additional steps and calculations could be inserted to shorten the total process. For instance, going to page 110 and checking the date of the first video there to see whether the sought after date would be before or after. Then going to the next mid point and so on. In a handful of steps we would have the desired videos pinpointed without the need for wading through a myriad of unwanted files.

Currently the YouTube channel with the most videos has more than 1.7 million videos. Consider it for benchmarking purposes…

**Comment by pukkandan** [comment]
Playlists need no be always ordered by date. So this can't be done by default. But since you know it is ordered in this case, you can use `--break-on-reject`. If you have an archive file, `--break-on-existing` can make it even faster

**Comment by HalvorRaknes** [comment]
I don't understand how those would work. 

 ```
      --break-on-existing
              Stop  the  download  process when encountering a file that is in
              the archive

       --break-on-reject
              Stop the download process when encountering a file that has been
              filtered out

```
Could you give an example and/or elaborate on the explanations?

**Comment by pukkandan** [comment]
For your specific purpose, `--break-on-reject` is only useful with `--date-after`

`--break-on-existing` needs `--download-archive`

**Comment by pukkandan** [comment]
>  For instance, going to page 110 and checking the date of the first video there to see whether the sought after date would be before or after. Then going to the next mid point and so on. In a handful of steps we would have the desired videos pinpointed without the need for wading through a myriad of unwanted files.

As I said above, playlists are generally not sorted by date. So this won't work. In your specific case, the playlist just happened to be sorted

**Comment by HalvorRaknes** [comment]
> 



> As I said above, playlists are generally not sorted by date. So this won't work. In your specific case, the playlist just happened to be sorted

It seems odd to me that you state that since practically all the playlists that I download are sorted by date. In particular, when the channel itself is treated as a "playlist" this seems universally the case.

**Comment by pukkandan** [comment]
Not necessarily sorted by date
* https://www.youtube.com/c/veritasium/videos?sort=da
* https://www.twitch.tv/collections/wlDCoH0zEBZZbQ
* https://www.dailymotion.com/playlist/xv4bw
* https://www.youtube.com/watch?v=TQxeutcYP6I&list=PLAB27A3C12C31E663

Always sorted by date:
* https://www.youtube.com/c/veritasium/videos

The fact that the URLs you download are sorted by date is clearly not a generalizable fact and is specific to just the kind of URLs you pass to yt-dlp. If youtube decides to change the default channel sorting to say, "most popular", even that won't be sorted in the future

**Comment by HalvorRaknes** [comment]
OK. But I will venture to propose that when dealing with really large (as in HUGE) playlists, where the problem fix that I request would be extremely beneficial, these are almost always sorted by date. Even when one can choose to have them sorted by popularity or "most relevant" people will generally go by 'sort by date' in these cases. There could even be a warning inserted here saying e.g. "THIS IS A VERY LARGE PLAYLIST. YOU HAVE OPTED TO DOWNLOAD VIDEOS SORTED BY [POPULARITY/MOST RELEVANT]. THIS WILL TAKE MUCH LONGER TIME THAN IF YOU CHOOSE TO DOWNLOAD THE PLAYLIST SORTED BY DATE."

**Comment by pukkandan** [comment]
what? yt-dlp have no way of knowing how it is sorted. I'm telling you that youtube channels is sorted because of my experience with youtube. That experience is not easily translatable into code

**Comment by HalvorRaknes** [comment]
OK, but still, that warning message could be issued for all very large playlists by simply tweaking "YOU HAVE OPTED" to "IF YOU HAVE OPTED".

**Comment by pukkandan** [comment]
I have no idea how what you are asking for can be implemented. Feel free to try your hand at a PR

**Comment by HalvorRaknes** [comment]
> I have no idea how what you are asking for can be implemented. Feel free to try your hand at a PR

I have no competency in programming.

**Comment by pukkandan** [comment]
By "you", I don't necessarily mean you. I meant anyone who wants to try implementing this can have a try

**Comment by pukkandan** [comment]
> I have no idea how what you are asking for can be implemented. Feel free to try your hand at a PR

I thought I just didn't understand your request exactly. But now re-reading your OP, this is entirely impossible!

> For instance, going to page 110 and checking the date of the first video there to see whether the sought after date would be before or after. Then going to the next mid point and so on. In a handful of steps we would have the desired videos pinpointed without the need for wading through a myriad of unwanted files.

The pages of youtube playlist/channel can only be downloaded in sequence. It may technically be possible to implement this for a few sites that allow downloading pages out of order (though still difficult), but that obv doesn't help you.

I'm closing this unless someone wants to re-request this feature for another site where this is actually possible. No point in keeping a feature request that benefits nobody
