### ISSUE TITLE
No audio, how do I fix, start over or another way?

### ISSUE THREAD

**Issue by shellig** [yt-dlp/yt-dlp#2700]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

I did not notice in the differences that format coding changed. I downloaded about 30 videos with command line format:
W:\Media\Videos\YouTube>yt-dlp -vu -4 -w -f "135/136/22/mp4" -o "W:\Media\Videos\YouTubeCourses\%%(upload_date)s %%(uploader_id)s %%(title)s.%%(ext)s" https://www.youtube.com/watch?v=v2oNWja7M2E
I am lost trying to figure out the best way to fix this.  Delete and redownload modifying command or download audio and somehow combine?

**Comment by dirkf** [comment]
YT formats 135 and 136 are video-only: don't ask for those without separate audio (eg, with 140, `(135/136)+140/22/mp4). Hence you don't audio that you would get with 22 or `mp4`. 

Generally, ask for what kind of format you want, if somehow the default selection is not satisfactory, rather than actually specifying format IDs, unless you just listed the formats beforehand.

**Comment by pukkandan** [comment]
> Delete and redownload modifying command or download audio and somehow combine?

Deleting and re-downloading is the easiest way.

But you could also rename the already downloaded file to it's intermediate counterpart `<filename>.f<format_id>.<ext>` and then run the download. That way, yt-dlp will pick up the format as already downloaded and will download just the audio and merge them. If you have no idea what I am talking about, just delete and re-download

**Comment by shellig** [comment]
Thank you so much.  I had just used the old command structure without reading all the instructions for the new version.  Really appreciate the help!  Can close this if you need my input for that 😊
