### ISSUE TITLE
subtitle option "--all-subs --embed-subs --write-sub --write-auto-sub" causing HTTP 429 too many requests on YouTube.

### ISSUE THREAD

**Issue by Originalimoc** [yt-dlp/yt-dlp#2706]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.02.04**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

Maybe on other rate-limited sites too.
Set a delay or retry.

### Verbose log

```shell
ERROR: Unable to download video subtitles for 'mg-zh-Hant': HTTP Error 429: Too Many Requests
```

**Comment by coletdjnz** [comment]
use `--sleep-subtitles`

duplicate: https://github.com/yt-dlp/yt-dlp/issues/2212

**Comment by Originalimoc** [comment]
Just found this option😅
