### ISSUE TITLE
Download audio file from Instagram videos

### ISSUE THREAD

**Issue by chromer030** [yt-dlp/yt-dlp#2712]
### Checklist

- [X] I'm reporting a feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.02.04**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

As there is this feature for Youtube and we can select it with `-f` switch, please implement this feature for Instagram videos too, it's so useful when we want to download long videos and IGTVs and Lives in MP3, there is some websites that provides this feature , and the download link is from Instagram also, this means that there is the audio file on Instagram server by default and we need just an extractor.
Thanks.

**Comment by chromer030** [comment]
```
user@user ~/Desktop % yt-dlp -UvF https://www.instagram.com/tv/CZuVHNTJecf/
[debug] Command-line config: ['-UvF', 'https://www.instagram.com/tv/CZuVHNTJecf/']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.02.04 [c1653e9ef]
[debug] Python version 3.10.2 (CPython 64bit) - Linux-5.16.8-arch1-1-x86_64-with-glibc2.33
[debug] exe versions: ffmpeg 4.4.1 (setts), ffprobe 4.4.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.02.04, Current version: 2022.02.04
yt-dlp is up to date (2022.02.04)
[debug] [Instagram] Extracting URL: https://www.instagram.com/tv/CZuVHNTJecf/
[Instagram] CZuVHNTJecf: Downloading webpage
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[info] Available formats for CZuVHNTJecf:
ID EXT RESOLUTION │ PROTO │ VCODEC  ACODEC
────────────────────────────────────────────
0  mp4 1080x1920  │ https │ unknown unknown
```

**Comment by chromer030** [comment]
[This Site](https://instavideosave.net/audio/) downloads Instagram videos to mp3, maybe helps.

**Comment by pukkandan** [comment]
I don't see any audio-only streams on instagram. That site is converting the format themselves. You can use `-x` with yt-dlp to do the same
