### ISSUE TITLE
Possible to modify Youtube URL for proxy?

### ISSUE THREAD

**Issue by ikmolbo** [yt-dlp/yt-dlp#2713]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

Hi,

I need to route requests to Youtube via my reverse proxy. Using the --proxy flag isn't appropriate as my server accepts only GET requests, not CONNECT. 

Instead, I need to modify each request to Youtube so that, instead of (for example) https://www.youtube.com/watch?v=9hGc1k3UcxQ, Youtube-dl sends the request to https://www.mysite.com/youtube.com/watch?v=9hGc1k3UcxQ, where I can proxy the request to Youtube.

Is this possible with a pre-processor hook, for example?

Grateful for any advice.

**Comment by pukkandan** [comment]
No. You will have to set up your proxy server to accept CONNECT

If your server can mirror all youtube API calls, it *may* be possible to do by modifying the `extractor/youtube.py` source code
