### ISSUE TITLE
[minor] by default download jpg thumbnails instead of webp

### ISSUE THREAD

**Issue by pirate486743186** [yt-dlp/yt-dlp#2717]
### Checklist

- [X] I'm reporting a feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.02.04**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

by default webp thumbnails are downloaded first. It should be jpg instead. webp is still too new and a lot of programs can't handle them. This default would be changed back in the future, if webp is more wildly used.

**Comment by pukkandan** [comment]
> lot of programs can't handle them

Even your browser can handle them!

webp is generally better quality than jpeg and will continue to be given higher priority

**Comment by cunlem** [comment]
> webp is generally better quality than jpeg and will continue to be given higher priority

Fair enough. Can we get an option to choose image format? Right now to get a JPEG  `--write-all-thumbnails` is required which is a bit of a hassle.
