### ISSUE TITLE
[Broken] watchnebula is now nebula.app

### ISSUE THREAD

**Issue by mmshasan** [yt-dlp/yt-dlp#272]
## Checklist

- [x ] I'm reporting a broken site support
- [x ] I've verified that I'm running yt-dlp version **2021.04.22**
- [x ] I've checked that all provided URLs are alive and playable in a browser
- [x ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x ] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] Command-line config: ['-F', '--verbose', '--cookies', 'nebula.app_cookies.txt', '--username', 'PRIVATE', '--password', 'PRIVATE', '**_Video Url was Here_**']
[debug] Loading archive file None
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] yt-dlp version 2021.04.22 (exe)
[debug] Python version 3.8.9 (CPython 64bit) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg 2021-03-07-git-a7f841718f-full_build-www.gyan.dev, ffprobe 2021-03-07-git-a7f841718f-full_build-www.gyan.dev
[debug] Proxy map: {}
[generic] **_video page name was here_**: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] **_video page name was here_**: Downloading webpage
[generic] **_video page name was here_**: Extracting information
ERROR: Unsupported URL: **_Video Url was here_**
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1059, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1080, in __extract_info
  File "yt_dlp\extractor\common.py", line 558, in extract
  File "yt_dlp\extractor\generic.py", line 3555, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: **_Video Url was here_**

```

## Description

Please note, replacing nebula.app with watchnebula.com still works. Minor tweak should fix the problem.

**Comment by pukkandan** [comment]
It's probably an easy fix, but I can't test without account details. You can PM via discord/reddit/email

**Comment by Lamieur** [comment]
Changing the regex is enough (api.watchnebula.com didn't move so far). For basic level of completness, I also changed the urls in tests, but nothing else.

```
--- nebula.py.ytdlp	2021-04-26 13:02:07.117877540 +0200
+++ nebula.py	2021-04-26 13:37:58.293753911 +0200
@@ -15,10 +15,10 @@
 
 class NebulaIE(InfoExtractor):
 
-    _VALID_URL = r'https?://(?:www\.)?watchnebula\.com/videos/(?P<id>[-\w]+)'
+    _VALID_URL = r'https?://(?:www\.)?(?:watchnebula\.com|nebula\.app)/videos/(?P<id>[-\w]+)'
     _TESTS = [
         {
-            'url': 'https://watchnebula.com/videos/that-time-disney-remade-beauty-and-the-beast',
+            'url': 'https://nebula.app/videos/that-time-disney-remade-beauty-and-the-beast',
             'md5': 'fe79c4df8b3aa2fea98a93d027465c7e',
             'info_dict': {
                 'id': '5c271b40b13fd613090034fd',
@@ -36,7 +36,7 @@
             'skip': 'All Nebula content requires authentication',
         },
         {
-            'url': 'https://watchnebula.com/videos/the-logistics-of-d-day-landing-craft-how-the-allies-got-ashore',
+            'url': 'https://nebula.app/videos/the-logistics-of-d-day-landing-craft-how-the-allies-got-ashore',
             'md5': '6d4edd14ce65720fa63aba5c583fb328',
             'info_dict': {
                 'id': '5e7e78171aaf320001fbd6be',
@@ -54,7 +54,7 @@
             'skip': 'All Nebula content requires authentication',
         },
         {
-            'url': 'https://watchnebula.com/videos/money-episode-1-the-draw',
+            'url': 'https://nebula.app/videos/money-episode-1-the-draw',
             'md5': '8c7d272910eea320f6f8e6d3084eecf5',
             'info_dict': {
                 'id': '5e779ebdd157bc0001d1c75a',
```

**Comment by pukkandan** [comment]
Thanks @Lamieur 

> api.watchnebula.com didn't move so far

That was indeed my concern. Could you make a PR?

> For basic level of completness, I also changed the urls in tests, but nothing else.

Leave some of the tests in old URL and some in new, so that both patterns are tested

**Comment by Lamieur** [comment]
@hheimbuerger will probably make a PR, I can't be bothered with learning cryptic git commands to patch a single line :)

Old urls are just 301 redirects now:
```
wget https://watchnebula.com/videos/polymatter-water-chinas-reckoning-part-3
(...)
Connecting to watchnebula.com (watchnebula.com)|2606:4700:3036::ac43:9ff6|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://nebula.app/videos/polymatter-water-chinas-reckoning-part-3 [following]
(...)
```

So it makes sense to leave them in the valid url pattern for people's bookmarks and whatnot. I simply didn't think it's a necessary thing to test for. But you're right, if backwards compatibility is offered, it probably should be tested. I just didn't think about it, sorry. I'm sure a more thought-out PR will come, for now I just wanted to show affected users that it still works after a one-line fix.

**Comment by pukkandan** [comment]
> I can't be bothered with learning cryptic git commands to patch a single line

Np, I'll patch it myself

**Comment by hheimbuerger** [comment]
> > @hheimbuerger will probably make a PR, I can't be bothered with learning cryptic git commands to patch a single line :)

👍 

> Np, I'll patch it myself

👍 I won't take action then unless you tell me otherwise.

I'm also happy to provide support for this extractor, feel free to @-mention me in the future. (I'll also see if there's a way to set up keyword notifications for new issues in GitHub.)

**Comment by pukkandan** [comment]
> I'm also happy to provide support for this extractor, feel free to @-mention me in the future.

I'll keep that in mind 😄
