### ISSUE TITLE
twitcasting and account login

### ISSUE THREAD

**Issue by MrTyton** [yt-dlp/yt-dlp#2720]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.02.04**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

USA

### Description

I cannot download a video that requires has a user login requirement on the archive, even though I'm passing in the correct user/password. It works for other videos in the channel, but not the one that requires an account to view.

### Verbose log

```shell
.\yt-dlp.exe https://twitcasting.tv/cordelia_yurica/movie/720415482 --ffmpeg-location "C:\Users\Joshua\Downloads\ffmpeg-4.3.1-full_build\bin" -o "%(uploader)s/%(title)s.%(ext)s" --write-thumbnail --username $USERNAME--password $PASSWORD --verbose -U
[debug] Command-line config: ['https://twitcasting.tv/cordelia_yurica/movie/720415482', '--ffmpeg-location', 'C:\\Users\\Joshua\\Downloads\\ffmpeg-4.3.1-full_build\\bin', '-o', '%(uploader)s/%(title)s.%(ext)s', '--write-thumbnail', '--username', 'PRIVATE', '--password', 'PRIVATE', '--verbose', '-U']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.02.04 [c1653e9] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19042-SP0
[debug] exe versions: ffmpeg 4.3.1-full_build-www.gyan.dev, ffprobe 4.3.1-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.02.04, Current version: 2022.02.04
yt-dlp is up to date (2022.02.04)
[debug] [TwitCasting] Extracting URL: https://twitcasting.tv/cordelia_yurica/movie/720415482
[TwitCasting] 720415482: Downloading webpage
[TwitCasting] 720415482: Downloading live info
ERROR: [TwitCasting] 720415482: Failed to get m3u8 playlist; please report this issue on  https://github.com/yt-dlp/yt-dlp , filling out the "Broken site" issue template properly. Confirm you are on the latest version using -U; please report this issue on  https://github.com/yt-dlp/yt-dlp , filling out the "Broken site" issue template properly. Confirm you are on the latest version using -U
  File "yt_dlp\extractor\common.py", line 612, in extract
  File "yt_dlp\extractor\twitcasting.py", line 144, in _real_extract
```

**Comment by MrTyton** [comment]
That did work, by using ` --cookies-from-browser chrome`. It's still odd that the user/pass didn't work, though. I'm ok closing this as my need is met, even though the main issue might be an issue, up to you. Thanks for the help!

**Comment by pukkandan** [comment]
user+pass support needs to be added for each site and is not implemented for twitcasting
