### ISSUE TITLE
[Bug] `--print-to-file` cannot create folders

### ISSUE THREAD

**Issue by pukkandan** [yt-dlp/yt-dlp#2721]
Additionally, it seems that `--print-to-file` cannot create folders. It creates the file if it doesn't yet exist, but if the path to the file does not yet exist, it is not created, the whole process simply fails with `[Errno 2] No such file or directory`.

_Originally posted by @Blacklands in https://github.com/yt-dlp/yt-dlp/issues/2372#issuecomment-1035060120_

**Comment by Blacklands** [comment]
(I should probably have created a separate issue for this, sorry.)
In https://github.com/yt-dlp/yt-dlp/blob/a3125791c7a5cdf2c8c025b99788bf686edd1a8a/yt_dlp/YoutubeDL.py#L2724, there is an `io.open()`, in append mode, which does not create the path if it does not yet exist I believe.
