### ISSUE TITLE
How do --geo-bypass and --geo-bypass-country affect each other ?

### ISSUE THREAD

**Issue by chrizilla** [yt-dlp/yt-dlp#2722]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

How do `--geo-bypass` and `--geo-bypass-country` affect each other ?
What is the relationship between the 2 parameters ?

Should only 1 of the 2 parameters be used at a time ?
Does `--geo-bypass` somehow negatively infere with `--geo-bypass-country` ?
Or can both be safely used at the same time ?

I guess `--geo-bypass` does find out the required country IP by itself ?
So given that `--geo-bypass` is enabled by default, when is `--geo-bypass-country` needed/useful ?

**Comment by pukkandan** [comment]
`--geo-bypass` by itself only works when the extractor has defined the country to spoof. User can override this (or enable it for unsupported extractors) by using `--geo-bypass-country`

**Comment by chrizilla** [comment]
> `--geo-bypass` by itself only works when the extractor has defined the country to spoof.

thank you. ok, then if I understand correctly, using the `--geo-bypass` parameter does not ever accomplish anything, because it is enabled by default and does nothing if the extractor has not defined the country. I assume it only exists for the sake of completeness, so as to have a counterpart for `--no-geo-bypass`. Correct?

So there is no harm if I always use `--geo-bypass` (because it is enabled by default anyway) and in case I want to specify a country manually, I can additionally use `--geo-bypass-country`, correct?

**Comment by pukkandan** [comment]
yes to both

**Comment by chrizilla** [comment]
ok, thank you
