### ISSUE TITLE
ffmpeg PATH imposible to set on Windows

### ISSUE THREAD

**Issue by zohozer** [yt-dlp/yt-dlp#2726]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.02.04**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

I am using the latest YT-DLP on a Windows10 machine and I need to use-it with ffmpeg.

I created a configuration file that it is readed by YT-DLP but I can't set the FFMPEG path to FFMPEG.

I do tryed all sorts of ligatures without any luck:
`--ffmpeg-location C:\\Programs\\Video\\ffmpeg\\bin`

The error that I get from YT-DLP:
`ERROR: Postprocessing: ffmpeg not found. Please install or provide the path using --ffmpeg-location`

### Verbose log

```shell
ERROR: Postprocessing: ffmpeg not found. Please install or provide the path using --ffmpeg-location
```

**Comment by gamer191** [comment]
`--ffmpeg-location "C:\Programs\Video\ffmpeg\bin"`

**Comment by zohozer** [comment]
Thank you. Fixed this isuue. I was unarchived the binaries in other directory by mistake and didn't realized that the `bin` directory is empty.
