### ISSUE TITLE
[instagram] Raise appropriate error for private content

### ISSUE THREAD

**Issue by Ra10Bit** [yt-dlp/yt-dlp#2736]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.02.04**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Russia

### Description

The link is given:
https://www.instagram.com/p/CZOkixaJmD0P53zRckxVVsiVrmOn5kf7wwFSNY0/

Link Features:
1. Requires authorization
2. Requires a subscription to a group\channel to access the video

Problem:
The December versions of YT-DLP requested cookies from this link (although it couldn't even download them), and the latest versions show various errors.

How to repeat:

First you need to download the app:

https://drive.google.com/file/d/108H8AxzSf3q9upPHPfVpbwB9DssemH3K/view?usp=sharing

1. The folder with the executable file must contain Python and YT-DLP libraries: 
"pylibs\\yt_dlp\\__init__.py"

2. Run the executable file (it is written in Delphi using Python4Delphi)

3. Click "10. YTDL GetInfo" and wait for the "ALL DONE" message in the console
The file "out.mp4" should be saved to the folder with the executable file

4. You should observe the appearance of the error
ScreenShot: 
https://yadi.sk/d/tqo-EDgB95i7tg

### Verbose log

```shell
...
2022-02-10 18:01:53.313  TYoutubeDl yt-dlp stack: DEBUG: [Instagram] CZOkixaJmD0P53zRckxVVsiVrmOn5kf7wwFSNY0: Downloading webpage
2022-02-10 18:01:54.697  TYoutubeDl yt-dlp stack: WARNING: [Instagram] unable to extract username; please report this issue on  https://github.com/yt-dlp/yt-dlp , filling out the "Broken site" issue template properly. Confirm you are on the latest version using -U
2022-02-10 18:01:54.710  TYoutubeDl yt-dlp stack: ERR: Err: [instagram] czokixajmd0p53zrckxvvsivrmon5kf7wwfsny0: unable to extract video url; please report this issue on  https://github.com/yt-dlp/yt-dlp , filling out the "broken site" issue template properly. confirm you are on the latest version using -u
2022-02-10 18:01:54.716  TYoutubeDl yt-dlp stack: ; please report this issue on  https://github.com/yt-dlp/yt-dlp , filling out the "broken site" issue template properly. confirm you are on the latest version using -u...
...
OR
...

LOG DEBUG: [debug] [Instagram] Extracting URL: https://www.instagram.com/p/CZOkixaJmD0P53zRckxVVsiVrmOn5kf7wwFSNY0/
LOG INFO: [Instagram] CZOkixaJmD0P53zRckxVVsiVrmOn5kf7wwFSNY0: Downloading webpage
LOG WARNING: [Instagram] Main webpage is locked behind the login page. Retrying with embed webpage (Note that some metadata might be missing)
LOG INFO: [Instagram] CZOkixaJmD0P53zRckxVVsiVrmOn5kf7wwFSNY0: Downloading embed webpage
LOG ERROR: ERROR: [Instagram] CZOkixaJmD0P53zRckxVVsiVrmOn5kf7wwFSNY0: Unable to download webpage: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on  https://github.com/yt-dlp/yt-dlp , filling out the "Broken si
te" issue template properly. Confirm you are on the latest version using -U (caused by <HTTPError 404: 'Not Found'>); please report this issue on  https://github.com/yt-dlp/yt-dlp , filling out the "Broken site" issue template properly. Confirm you are on t
he latest version using -U
LOG ERROR:   File "C:\Users\USER-PC\Desktop\Test To Merge Push\pylibs\yt_dlp\extractor\common.py", line 730, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "C:\Users\USER-PC\Desktop\Test To Merge Push\pylibs\yt_dlp\YoutubeDL.py", line 3558, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 641, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 503, in _call_chain
  File "urllib\request.py", line 649, in http_error_default
...
```

**Comment by pukkandan** [comment]
I am not going to download and debug your app. Run the equivalent yt-dlp command in terminal and provide the ENTIRE verbose output

Also, the account you liked is private. So make sure to pass cookies with access to the content

**Comment by Ra10Bit** [comment]
> I am not going to download and debug your app. Run the equivalent yt-dlp command in terminal and provide the ENTIRE verbose output
> 
> Also, the account you liked is private. So make sure to pass cookies with access to the content

`
[debug] Command-line config: ['-v', '-F', 'https://www.instagram.com/p/CZOkixaJmD0P53zRckxVVsiVrmOn5kf7wwFSNY0/']
[debug] Encodings: locale cp1251, fs utf-8, out utf-8, err utf-8, pref cp1251
[debug] yt-dlp version 2022.01.21 [f20d607] (win_dir)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19042-SP0
[debug] exe versions: none
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [Instagram] Extracting URL: https://www.instagram.com/p/CZOkixaJmD0P53zRckxVVsiVrmOn5kf7wwFSNY0/
[Instagram] CZOkixaJmD0P53zRckxVVsiVrmOn5kf7wwFSNY0: Downloading webpage
WARNING: [Instagram] Main webpage is locked behind the login page. Retrying with embed webpage (Note that some metadata might be missing)
[Instagram] CZOkixaJmD0P53zRckxVVsiVrmOn5kf7wwFSNY0: Downloading embed webpage
ERROR: [Instagram] CZOkixaJmD0P53zRckxVVsiVrmOn5kf7wwFSNY0: Unable to download webpage: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output. (caused by <HTTPError 404: 'Not Found'>); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
  File "yt_dlp\extractor\common.py", line 730, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 3526, in urlopen
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 649, in http_error_default


C:\Users\Vayrus-PC\Desktop\yt-dlp~\yt-dlp dlls>pause
`

**Comment by Bricio** [comment]
To complain about recent version error message. 
First you should update your yt-dlp version. It is outdated.

Last version return another error.

**Comment by pukkandan** [comment]
@MinePlayersPE Would it be possible to detect this and raise appropriate error?

**Comment by Ra10Bit** [comment]
> To complain about recent version error message. First you should update your yt-dlp version. It is outdated.
> 
> Last version return another error.

I have already fixed it, the same error is in the latest version. And it is necessary as before: "Use --cookies, --username and --password or --do not provide account credentials"

**Comment by Ra10Bit** [comment]
There are links that some people, with frequent access to Instagram, can start asking for authorization, 
but the new mechanism "embed webpage" bypasses this restriction without specifying cookies, for example:
https://www.instagram.com/p/BOCm2YSgu23

You can check by creating multiple HEAD requests to the same link.

When there was no such mechanism yet, I watched the redirection to the authorization page and bypassed it 
by simply changing part of the url to another from the list:
"/p/" to "/tv/" or "/reel/" etc + "/?__1" for direct access to GraphQL JSON (YT-DLP use GENERIC extractor)

But, this mechanism does not work with the link above.

**Comment by rockmetal58342** [comment]
Same exact thing is happening to me. Those types of longer links for some reason are showing up as "404 not found"s for me as well

**Comment by rockmetal58342** [comment]
It is not a story, it is a longer post link like the one posted in this issue. (https://www.instagram.com/p/CWytPziL9CLFnariT8WXrKcn8_Mtx1wYWC_vVI0/)

**Comment by bifa2** [comment]
I'm getting 404 for private stories too:

```
[debug] Command-line config: ['-vU']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.03.08.1 [c0c2c57] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] exe versions: ffmpeg git-2020-06-28-4cfcfb3, ffprobe git-2020-06-28-4cfcfb3
[debug] Optional libraries: brotli, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.03.08.1, Current version: 2022.03.08.1
yt-dlp is up to date (2022.03.08.1)
```

Running either:
`.\yt-dlp.exe "https://www.instagram.com/stories/username/" "--cookies-from-browser chrome"`
`.\yt-dlp.exe "https://www.instagram.com/stories/username/3897489234892374/" "--cookies-from-browser chrome"`

... both result in a 404.

If I visit the URL directly in a browser, the page is rendered but asks if I want to view the story as my own account (I have a few different accounts).
