### ISSUE TITLE
Cannot write video metadata to JSON file

### ISSUE THREAD

**Issue by zenom141** [yt-dlp/yt-dlp#2737]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

When i try to get url links , this error comes. How to avoid this? Or this can't be handled ? BTW i dont wamt to download video, i need only video urls.

**Comment by zenom141** [comment]
Hello, i get the error logs. It is saying file name too long error. How to skip this error?

:~$ youtube-dl --write-info-json -v --skip-download https://www.youtube.com/watch?v=id
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--write-info-json', '-v', '--skip-download', 'https://www.youtube.com/watch?v=id']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.8.10 (CPython)
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] id Downloading webpage
[debug] Default format spec: best/bestvideo+bestaudio
[info] Writing video description metadata as JSON to: तेरा मुझसे है पहले का नाता कोई - teraa mujhase hai pahale kaa naataa koii 6_15PM-id.info.json
ERROR: Cannot write metadata to JSON file तेरा मुझसे है पहले का नाता कोई - teraa mujhase hai pahale kaa naataa koii 6_15PM-id.info.json
Traceback (most recent call last):
  File "/.local/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 1900, in process_info
    write_json_file(self.filter_requested_info(info_dict), infofn)
  File "/.local/lib/python3.8/site-packages/youtube_dl/utils.py", line 1829, in write_json_file
    tf = tempfile.NamedTemporaryFile(**compat_kwargs(args))
  File "/usr/lib/python3.8/tempfile.py", line 679, in NamedTemporaryFile
    (fd, name) = _mkstemp_inner(dir, prefix, suffix, flags, output_type)
  File "/usr/lib/python3.8/tempfile.py", line 389, in _mkstemp_inner
    fd = _os.open(file, flags, 0o600)
OSError: [Errno 36] File name too long: 'तेरा मुझसे है पहले का नाता कोई - teraa mujhase hai pahale kaa naataa koii 6_15PM-id.info.json.3rtfd9i2.tmp'

**Comment by pukkandan** [comment]
Use `-o` to set a smaller filename
