### ISSUE TITLE
[extractor/Nowtv] Add new extractor 

### ISSUE THREAD

**Issue by Heros99** [yt-dlp/yt-dlp#2744]
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.02.04**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [x] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Italia

### Example URLs

https://www.nowtv.it/watch/home/asset/and-just-like-that/skyserie_f8fe979772e8437d8a61ab83b6d293e9/seasons/1/episodes/8/R_126182_HD

### Description

[extractor/Nowtv] Add new extractor 

### Verbose log

```shell
[debug] Command-line config: ['-vU', '--cookies-from-browser', 'firefox', 'https://www.nowtv.it/watch/home/asset/and-just-like-that/skyserie_f8fe979772e8437d8a61ab83b6d293e9/seasons/1/episodes/8/R_126182_HD']
[Cookies] Extracting cookies from firefox
[debug] Extracting cookies from: "C:\Users\House\AppData\Roaming\Mozilla\Firefox\Profiles\5jzz5ux9.default-release\cookies.sqlite"
[Cookies] Extracted 2889 cookies from firefox
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.02.04 [c1653e9] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] exe versions: ffmpeg n4.4.1-12-gb4da29fee1-20211231 (setts), ffprobe n4.4.1-12-gb4da29fee1-20211231
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.02.04, Current version: 2022.02.04
yt-dlp is up to date (2022.02.04)
[debug] [generic] Extracting URL: https://www.nowtv.it/watch/home/asset/and-just-like-that/skyserie_f8fe979772e8437d8a61ab83b6d293e9/seasons/1/episodes/8/R_126182_HD
[generic] R_126182_HD: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] R_126182_HD: Downloading webpage
[generic] R_126182_HD: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://www.nowtv.it/watch/home/asset/and-just-like-that/skyserie_f8fe979772e8437d8a61ab83b6d293e9/seasons/1/episodes/8/R_126182_HD
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1381, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1451, in __extract_info
  File "yt_dlp\extractor\common.py", line 612, in extract
  File "yt_dlp\extractor\generic.py", line 3986, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.nowtv.it/watch/home/asset/and-just-like-that/skyserie_f8fe979772e8437d8a61ab83b6d293e9/seasons/1/episodes/8/R_126182_HD
```

**Comment by Heros99** [comment]
@pukkandan 
Sarabertovello@Gmail.com
filippo2!

**Comment by Heros99** [comment]
sent account for work @pukkandan

**Comment by pukkandan** [comment]
What? I am not working on this issue rn. The only thing I can do is forward it to any devs who want to work on it. But you could just have given them details when asked...

From https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed

> So any developer interested in solving your issue may ask you for account details

**Comment by Heros99** [comment]
> Che cosa? Non sto lavorando su questo problema rn. L'unica cosa che posso fare è inoltrarlo a tutti gli sviluppatori che vogliono lavorare. Ma avresti potuto fornire loro i dettagli quando richiesto...
> 
> Da [https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-se-necessario](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed)
> 
> > Quindi si è interessato a risolvere il tuo problema potrebbe chiederti i dettagli dell'account

I would be very happy if the developers could insert the new extractor.
for sharing the account there is no problem.

**Comment by nixxo** [comment]
It's a streaming service and certainly uses DRM. Cannot download content with yt-dlp

**Comment by coletdjnz** [comment]
If the whole site is DRM'd it should be added to KnownDRMIE then

**Comment by Heros99** [comment]
> If the whole site is DRM'd it should be added to KnownDRMIE then

I agree with you
