### ISSUE TITLE
Discovery 

### ISSUE THREAD

**Issue by scarng63** [yt-dlp/yt-dlp#2745]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.02.04**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

USA

### Description

I can play Gold Rush: 'Rebirth of  Monster Red' live, but I'm not able to download as it state unsupported url.

### Verbose log

```shell
[debug] Command-line config: ['-Uv', '--cookies', 'discovery.com_cookies.txt', 'https://go.discovery.com/video/gold-rush-discovery/rebirth-of-monster-red']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.02.04 [c1653e9] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19042-SP0
[debug] exe versions: ffmpeg 2021-09-01-git-c500dc7cca-full_build-www.gyan.dev (setts), ffprobe 2021-09-01-git-c500dc7cca-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.02.04, Current version: 2022.02.04
yt-dlp is up to date (2022.02.04)
[debug] [GoDiscovery] Extracting URL: https://go.discovery.com/video/gold-rush-discovery/rebirth-of-monster-red
[debug] Using fake IP 6.77.124.101 (US) as X-Forwarded-For
[GoDiscovery] gold-rush-discovery/rebirth-of-monster-red: Downloading JSON metadata
ERROR: [GoDiscovery] gold-rush-discovery/rebirth-of-monster-red: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on  https://github.com/yt-dlp/yt-dlp , filling out the "Broken site" issue template properly. Confirm you are on the latest version using -U (caused by <HTTPError 404: 'Not Found'>); please report this issue on  https://github.com/yt-dlp/yt-dlp , filling out the "Broken site" issue template properly. Confirm you are on the latest version using -U
  File "yt_dlp\extractor\common.py", line 730, in _request_webpage
    if isinstance(err, compat_urllib_error.HTTPError):
  File "yt_dlp\YoutubeDL.py", line 3558, in urlopen
    write_debug('Plugins: %s' % [
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 649, in http_error_default
```

**Comment by pukkandan** [comment]
Try with --no-geo-bypass
