### ISSUE TITLE
Unable to download certain YouTube videos

### ISSUE THREAD

**Issue by KPackratt2k** [yt-dlp/yt-dlp#2751]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.02.04**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

Hello. I'm attempting to download a certain video on YouTube, but it fails at  71.5% with a 404 Not Found error. I've tried redownloading the video a second time and it still occurs.

This is the video in question:
https://www.youtube.com/watch?v=tqydVNaLR1w

### Verbose log

```shell
C:\Users\Kaz\Downloads\youtube-dl>yt-dlp.exe -vU https://www.youtube.com/watch?v
=tqydVNaLR1w
[debug] Command-line config: ['-vU', 'https://www.youtube.com/watch?v=tqydVNaLR1
w']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8 (No ANSI), err utf-8 (No A
NSI), pref cp1252
[debug] yt-dlp version 2022.02.04 [c1653e9] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.02.04, Current version: 2022.02.04
yt-dlp is up to date (2022.02.04)
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=tqydVNaLR1w
[youtube] tqydVNaLR1w: Downloading webpage
[youtube] tqydVNaLR1w: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:
vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source
, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr
, vext, aext, hasaud, id
[debug] Default format spec: best/bestvideo+bestaudio
[info] tqydVNaLR1w: Downloading 1 format(s): 22
[debug] Invoking downloader on "https://rr1---sn-nx57ynls.googlevideo.com/videop
layback?expire=1644720004&ei=JBsIYt61KeWPsfIPkrW78A0&ip=2601%3A602%3A8a80%3A6a80
%3A9c07%3A74f7%3A8ded%3Ac1ff&id=o-APA9R7TUS1hE7uIfQN9137BCxW2w3TyzkvaxBzzP7hVq&i
tag=22&source=youtube&requiressl=yes&mh=pi&mm=31%2C29&mn=sn-nx57ynls%2Csn-nx5s7n
7d&ms=au%2Crdu&mv=m&mvi=1&pl=36&initcwndbps=2120000&vprv=1&mime=video%2Fmp4&cnr=
14&ratebypass=yes&dur=1415.302&lmt=1644641563722703&mt=1644698203&fvip=1&fexp=24
001373%2C24007246&c=ANDROID&txp=3310222&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Cs
ource%2Crequiressl%2Cvprv%2Cmime%2Ccnr%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRAIg
LQi8eMeXR3CYMJ_i99LNWlZBMJBvqHdqQMmkkuwlh8YCIEmjvMT00TsdnoqbCVqxFnEIb1YhgpC1ADQl
f6JbJS0S&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwR
QIhANPajIQDusFN7XKWEmLOx2zdRo1kn_Mp0dmV2k4MOgbuAiBk8QF1uMhyzfqIc-QK-825YCAyZ4vSE
lCY9Cqpaq2ZFA%3D%3D"
[download] Destination: Making a '90s Style Website With Microsoft FrontPage 98!
 [tqydVNaLR1w].mp4
[download]  71.5% of 189.70MiB at  7.20MiB/s ETA 00:07[download] Got server HTTP
 error: Downloaded 142242359 bytes, expected 198918648 bytes. Retrying (attempt
1 of 10) ...
ERROR: unable to download video data: HTTP Error 404: Not Found
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 3086, in process_info
  File "yt_dlp\YoutubeDL.py", line 2801, in dl
  File "yt_dlp\downloader\common.py", line 440, in download
  File "yt_dlp\downloader\http.py", line 371, in real_download
  File "yt_dlp\downloader\http.py", line 119, in establish_connection
  File "yt_dlp\downloader\http.py", line 113, in establish_connection
  File "yt_dlp\YoutubeDL.py", line 3558, in urlopen
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 563, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 755, in http_error_302
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found
```

**Comment by pukkandan** [comment]
The format doesn't play in browser either. So this is a youtube side issue and nothing can be done about it. You will need to select another format

**Comment by NanaMizukiAnother7** [comment]
I think that it is now working after eight hours:

`[debug] Command-line config: ['-Uv', '-f', '22', 'https://www.youtube.com/watch?v=tqydVNaLR1w']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8 (No ANSI), err utf-8 (No ANSI), pref cp1252
[debug] yt-dlp version 2022.02.04 [c1653e9] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-105446-g2e82c61055-20220202 (setts), ffprobe N-105038-g30322ebe3c-sherpya
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.02.04, Current version: 2022.02.04
yt-dlp is up to date (2022.02.04)
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=tqydVNaLR1w
[youtube] tqydVNaLR1w: Downloading webpage
[youtube] tqydVNaLR1w: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[info] tqydVNaLR1w: Downloading 1 format(s): 22
[debug] Invoking downloader on "https://rr1---sn-5fo-0u2e.googlevideo.com/videoplayback?expire=1644749848&ei=uI8IYpXlEJKR8QOvqJKgCw&ip=184.22.41.77&id=o-AITIUGRGJVsGj2lriuL8JYZUTL7wW9-9tWwzeyDhNXcm&itag=22&source=youtube&requiressl=yes&mh=pi&mm=31%2C29&mn=sn-5fo-0u2e%2Csn-5fo-c33z&ms=au%2Crdu&mv=m&mvi=1&pcm2cms=yes&pl=22&initcwndbps=1873750&vprv=1&mime=video%2Fmp4&cnr=14&ratebypass=yes&dur=1415.302&lmt=1644700975755480&mt=1644727484&fvip=1&fexp=24001373%2C24007246&c=ANDROID&txp=4432434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Ccnr%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRQIgH5fu_cGNGFZ5OzHx2R4TAcQ5B649GeI2DRhaWgC_4EkCIQDb6y5pI_ICicS52lSL860FM3d1KMuWXgGZpyEH2o-L5g%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgBFOb3OVcSSfRKWUoQVlwvOAwWtCGpvvA_oD4ZWdiaPQCIQDgI38Gj5JeV2_Y2q6OCHrwrFVFMjxvDeDTA94lp9muUA%3D%3D"
[download] Destination: Making a ’90s Style Website With Microsoft FrontPage 98! [tqydVNaLR1w].mp4
[download] 100% of 66.61MiB in 00:20`
