### ISSUE TITLE
What can --download-archive be used for?

### ISSUE THREAD

**Issue by HalvorRaknes** [yt-dlp/yt-dlp#2754]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

In [this](https://github.com/yt-dlp/yt-dlp/issues/2693#issuecomment-1036658116) reply Pukkandan directs me to use the `--download-archive` option. But I don't understand what this archive file is and how this would work in the particular case discussed in that thread.

I hope I can receive some education here!

**Comment by pukkandan** [comment]
> - [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)

**Comment by pukkandan** [comment]
```
--download-archive FILE          Download only videos not listed in the
                                 archive file. Record the IDs of all
                                 downloaded videos in it
```

In the context of that discussion, also see 
```
--break-on-existing              Stop the download process when encountering
                                 a file that is in the archive
```

**Comment by pukkandan** [comment]
When you run `yt-dlp --download-archive archive.txt URL` for the first time, it will download all the videos in URL and record those video IDs in `archive.txt`. On subsequent runs of the same command, any videos that are in the archive file will be skipped. That way, you can update just the new videos without parsing each of the old videos

PS: Like `--break-for-reject`, this may not be suitable for your specific use case. You are probably better off using yt-dlp to just get the video ids and writing your own script to bisect by date

**Comment by HalvorRaknes** [comment]
> When you run `yt-dlp --download-archive archive.txt URL` for the first time, it will download all the videos in URL and record those video IDs in `archive.txt`. On subsequent runs of the same command, any videos that are in the archive file will be skipped. That way, you can update just the new videos without parsing each of the old videos

Downloading all videos certainly isn't what I want. Not even the first time.

I don't really see that these two break-on options are useful to me.

**Comment by FT129** [comment]
If you download all your stuff to the same folder and you're not sure if you've already downloaded a particular file, running yt-dlp with the ` --download-archive` option every time will make sure it doesn't download the same file again. It's also good when you're downloading a bunch of files at the same time and your download stops or your network drops for some reason, and some of the files have already been downloaded but you're not sure which. You can run them again without worrying about accidentally downloading them again. I use this option along with a script that scraps full seasons of tv shows (free and legal) and downloads them. Occasionally the download breaks because of expired cookies or network issues and this really comes in handy because I can simply re-run them again without manually checking which downloads are complete and which are pending.

**Comment by dirkf** [comment]
One thing that might be useful is a way to pre-populate the download-archive index. Correctly, the archive doesn't get updated by `--skip-download` or `--simulate`.

I believe that all you can do now is to use the "intended to be used by the end-user" `--test` option and then delete all the resulting media files.

**Comment by pukkandan** [comment]
There is a `--force-write-archive` option that writes the archive even in `--simulate`

**Comment by pukkandan** [comment]
The option was adapted from https://github.com/ytdl-org/youtube-dl/pull/16455

**Comment by AntonSamokat** [comment]
Also `--download-archive` option can be used for re-downloading (updating) comments for already downloaded videos in archive:
```
yt-dlp --skip-download --write-comments --write-info-json -- $(sed -z "s/\n/ /g" videos_ids_archive.txt | sed "s/youtube //g")
```

Related question about how to populate `videos_ids_archive.txt` file for channel or playlist (channels are treated by `yt-dlp` in the same way as playlists): [How to get the whole list of video-ids from the specific channel id](https://github.com/yt-dlp/yt-dlp/issues/2117)
