### ISSUE TITLE
Can't overwrite the "created generic title" with a default (or an alternative) value

### ISSUE THREAD

**Issue by AlttiRi** [yt-dlp/yt-dlp#2760]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.02.04**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

If the `title` name pattern key is missed, the program created a generic title. 

I can't overwrite it with a "Default" value, or with an "Alternative" value.

---

I want to use an empty string if there is no title, but it — `%(title|)s` — does not work.
I just see 
```
WARNING: Extractor failed to obtain "title". Creating a generic title instead
```
And the program uses that created generic title, ignoring my rule.

---

Since I use such alias in my `.bashrc`:
```bash
alias yt='yt-dlp --write-thumbnail --write-description -o "[%(webpage_url_domain)s] %(uploader)s—%(upload_date>%Y.%m.%d)s—%(id)s—%(title|)s.%(ext)s" '
```
The generic title just duplicates `webpage_url_domain` and `id` values.

The result:
- [tiktok.com] marymeeri—2021.09.08—7005467079704956165—TikTok video #7005467079704956165.mp4

The expected result:
- [tiktok.com] marymeeri—2021.09.08—7005467079704956165—.mp4

### Verbose log

```shell
[debug] Command-line config: ['--write-thumbnail', '--write-description', '-o', '[%(webpage_url_domain)s] %(uploader)s—%(upload_date>%Y.%m.%d)s—%(id)s—%(title|)s.%(ext)s', 'https://www.tiktok.com/@marymeeri/video/7005467079704956165', '-vU']
[debug] Encodings: locale cp65001, fs utf-8, out utf-8 (No ANSI), err utf-8 (No ANSI), pref cp65001
[debug] yt-dlp version 2022.02.04 [c1653e9ef]
[debug] Lazy loading extractors is disabled
[debug] Python version 3.9.9 (CPython 64bit) - Windows-10
[debug] exe versions: ffmpeg 4.4-full_build-www.gyan.dev (setts), ffprobe 4.4-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.02.04, Current version: 2022.02.04
yt-dlp is up to date (2022.02.04)
[debug] [TikTok] Extracting URL: https://www.tiktok.com/@marymeeri/video/7005467079704956165
...
WARNING: Extractor failed to obtain "title". Creating a generic title instead
...
[info] Writing video description to: [tiktok.com] marymeeri—2021.09.08—7005467079704956165—TikTok video #7005467079704956165.description
```

**Comment by pukkandan** [comment]
Use `fulltitle`

> - `fulltitle` (string): Video title ignoring live timestamp and generic title
