### ISSUE TITLE
Extracting channel info with --print fails with Cyrillic characters and gives unexpected results (windows)

### ISSUE THREAD

**Issue by MrSmite** [yt-dlp/yt-dlp#2767]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.02.04**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

While trying to extract a channel name to use in a script variable, I noticed the result is an empty string if the channel name uses Cyrillic alphabet. NOTE that Windows batch doesn't allow piping directly to a variable so the FOR loop is necessary.

Using Windows batch, parameters tried are:

%(creator)s
%(channel)s 
%(channel_id)s
%(uploader)s
%(uploader_id)s

NOTE: For the purpose of the bug report, I included all parameters together. My script only uses one parameter.

```
SET /p theURL= ^> Enter a URL: 
SET theChannel=

FOR /F "tokens=*" %%A IN ('!theDownloader! --proxy !proxyInf! --print "%%(creator)s - %%(channel)s - %%(channel_id)s - %%(uploader)s - %%(uploader_id)s" --playlist-end 1 "!theURL!"') DO (
    ECHO uploader is "%%A"
    SET theChannel=%%A
)
```

**Example 1:**

https://www.youtube.com/watch?v=d6yVXYz9P6c

The above URL will produce the following output:

> uploader is "NA - - UC-39fLDJPwSDuR7rlHGoXUg -   - AleksZamorin"

Note that the channel name is actually **МанхэттенФотошкола** and the display name is **Друзья Фотошкола** but neither of those are obtained. Also note that the channel and uploader results are blank. If you search for the channel ID in the Youtube search bar and filter on "channel", it returns:

https://www.youtube.com/c/МанхэттенФотошкола

The expected output would be:

> uploader is "NA - МанхэттенФотошкола - UC-39fLDJPwSDuR7rlHGoXUg - Друзья Фотошкола - AleksZamorin"

**Example 2:**

https://www.youtube.com/watch?v=bv_6f_utMek

This channel is in english but still seems to give unexpected results:

> uploader is "NA - David Manning - UC_sSJZnJdsnjuAKdr95D9HQ - David Manning - UC_sSJZnJdsnjuAKdr95D9HQ"

The channel name is actually **DavidManningvlog** as seen in the URL when you search for the channel ID in the Youtube search bar and filter on "channel":  https://www.youtube.com/c/DavidManningvlog/videos

### Verbose log

```shell
[debug] Command-line config: ['-v', '--print', '%(creator)s - %(channel)s - %(channel_id)s - %(uploader)s - %(
uploader_id)s', '--playlist-end', '1', 'https://www.youtube.com/watch?v=d6yVXYz9P6c']
[debug] Encodings: locale cp1252, fs utf-8, out cp1252 (No ANSI), err utf-8 (No ANSI), pref cp1252
[debug] yt-dlp version 2022.02.04 [c1653e9] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=d6yVXYz9P6c
[youtube] d6yVXYz9P6c: Downloading webpage
[youtube] d6yVXYz9P6c: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, la
ng, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] d6yVXYz9P6c: Downloading 1 format(s): 248+251
uploader is "NA -   - UC-39fLDJPwSDuR7rlHGoXUg -   - AleksZamorin"
```

**Comment by pukkandan** [comment]
```
❯ yt-dlp -O "%(creator)s - %(channel)s - %(channel_id)s - %(uploader)s - %(uploader_id)s" d6yVXYz9P6c
NA - Друзья Фотошкола - UC-39fLDJPwSDuR7rlHGoXUg - Друзья Фотошкола - AleksZamorin
```

Your console probably doesn't support unicode characters and therefore blanked them out. I can't test on a windows 7 system right now, but try running `chpcp 65001` before yt-dlp

> The channel name is actually DavidManningvlog as seen in the URL when you search for the channel ID in the Youtube search bar and filter on "channel": [youtube.com/c/DavidManningvlog/videos](https://www.youtube.com/c/DavidManningvlog/videos)

`channel` is the "name" of the channel, not it's URL slug
![image](https://user-images.githubusercontent.com/6623388/153811994-144f1b98-3f1a-4e55-8aba-c5214b44ad13.png)

**Comment by MrSmite** [comment]
> Your console probably doesn't support unicode characters and therefore blanked them out

Thanks for the reply. My console does actually support unicode. In fact, I often get the correct result printed to the console but when I try to pipe it to a file using >, it's blank.

For example:

SET theURL=https://www.youtube.com/c/МанхэттенФотошкола/videos

!theDownloader! --proxy !proxyInf! --print "%%(channel)s" --playlist-end 1 "!theURL!"
!theDownloader! --proxy !proxyInf! --print "%%(channel)s" --playlist-end 1 "!theURL!" > test.txt

The console shows: Друзья Фотошкола
The text file is empty

**Comment by pukkandan** [comment]
did u try this!?

>  but try running chpcp 65001 before yt-dlp

**Comment by MrSmite** [comment]
> did u try this?
> 
> > but try running chpcp 65001 before yt-dlp

Yes, it filled in the missing parameters:

> NA - Друзья Фотошкола - UC-39fLDJPwSDuR7rlHGoXUg - Друзья Фотошкола - AleksZamorin

But this brings up two additional questions:

1. How do I know which codepage to use if I'm accepting any random URL from Youtube
2. Why doesn't the output properly get printed to the text file?

NOTE: I tried to use --print-to-file but it failed on a playlist URL because "multiple files but only one ouput" or something.

**Comment by pukkandan** [comment]
> How do I know which codepage to use if I'm accepting any random URL from Youtube
> Why doesn't the output properly get printed to the text file?

Windows 7 console does not have proper unicode support. The closest you can get it is 65001. Even in windows 10/11, full utf8 support is marked as beta

> NOTE: I tried to use --print-to-file but it failed on a playlist URL because "multiple files but only one ouput" or something.

verbose log?

> --download-archive "!downloadDir!%(channel)s!videoList!.txt"

Download archive must be a single file, not an output template

**Comment by MrSmite** [comment]
> > NOTE: I tried to use --print-to-file but it failed on a playlist URL because "multiple files but only one ouput" or something.
> 
> verbose log?

Sorry, my mistake. It was an error in my command structure, I forgot to add --playlist-end 1 in my previous test.

--print to file actually works well except it downloads the first video before hitting my PAUSE directive. I only want to dump the channel name to a file, not actually start downloading yet.

> yt-dlp.exe -v --playlist-end 1 --print-to-file "%%(channel)s" test.txt "!theURL!"

I get a file with the channel name and also the first MP4 on the channel's "videos" tab.

**Comment by pukkandan** [comment]
Add `--simulate`. Unlike `--print`, `--print-to-file` does not automatically imply it

**Comment by MrSmite** [comment]
Finally, this works

SET /p theURL= ^> Enter a URL:

> chcp 65001
> yt-dlp.exe --simulate --playlist-end 1 --print-to-file "%(channel)s" test.txt !theURL!
> SET /p theChannel= < test.txt
> ECHO !theChannel!
> ECHO !theChannel! > !theChannel!.txt

I can echo the channel name to the screen and to a file with the same name. Without the _**chcp 65001**_ I can sometimes echo to the screen but the filename is all garbage.

Thank you for your help. I'm marking this resolved.

**Comment by fstirlitz** [comment]
It would be good to know how this issue would be affected by 79ecd190da3c6803b749941ea156108832f1f59e and/or 680da2aeb058a0453dee6a8690451aec0857a7e8. I have no Windows set-up to test this.

Are you able to create a custom build with those two patches applied?

**Comment by pukkandan** [comment]
Windows 10+ is unaffected. I'll test on win7 before merging, but I can't test for a few days atleast
