### ISSUE TITLE
Have "Cannot download embed-only video without embedding URL" error for site embedding Vimeo with referrer and cookies already provided

### ISSUE THREAD

**Issue by ohhai** [yt-dlp/yt-dlp#2780]
### Checklist

- [X] I'm reporting a feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.02.04**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

Posting this partially as feature request and partially as a hint for those who will step on same problem, since Google did not help me with it.

In short: check for multiple nested iframes on embedding page if you have this error with `--referer` and `--cookies` already provided:
"_Cannot download embed-only video without embedding URL. Please call yt-dlp with the URL of the page that embeds this video_".

I had it like this: page on address1 embeds iframe from address2 which in turn embeds Vimeo player.
So I still had that "_Cannot download_" error with `--referer=address1` and cookies already specified.
Setting `--referer=address2` made everything working.

Tried to check if there is quick automated solution for my case: `curl address1 | grep address2` finds it successfully, but `curl address2 | grep -i vimeo` does not.
Seems like Vimeo player is constructed by some javascript (?) after address2 is loaded.
I'm not a web developer, not sure if it could be solved in automated way like yt-dlp will check for nested iframes with no additional data provided by user.

**Comment by pukkandan** [comment]
This is not a forum!, but the projects issue tracker. You can try the youtube-dl subreddit.

I don't see any feature request in your post. If a certain site is not working, open a proper broken site/site request

**Comment by ohhai** [comment]
That's an issue and I don't seek for solution, I provide it. Without it video can't be downloaded at all.
As for feature request, I thought it's clear enough, but ok, I'll rephrase. Problem would disappear if referer to address2 could be automatically detected with --referer=address1. That's why I wrote about my check if it's possible just to find nested iframe src in address1.

**Comment by pukkandan** [comment]
> If a certain site is not working, open a proper broken site/site request

**Comment by baptx** [comment]
@ohhai Thanks for mentioning the `--referer` parameter, it worked for Vimeo. I thought it was not needed because my web browser Firefox sent it automatically when opening the video URL directly with a right click and selecting "open frame in new tab".
