### ISSUE TITLE
--embed-subs option for python

### ISSUE THREAD

**Issue by unknownsoldier08** [yt-dlp/yt-dlp#2782]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

Hello,
I am embedding yt-dlp into a python script, but am unsure if there is an option available for --embed-subs under ydl_opts?

I looked through the YoutubeDL.py, but didn't seem to find anything related to embedding subs.

**Comment by pukkandan** [comment]
See https://github.com/yt-dlp/yt-dlp/issues/2462, https://github.com/yt-dlp/yt-dlp/issues/1901
