### ISSUE TITLE
Deleted or disabled videos cause channel name extraction to fail if --playlist-end 1 is used

### ISSUE THREAD

**Issue by MrSmite** [yt-dlp/yt-dlp#2785]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.02.04**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

While trying to obtain the channel name, if the first video encountered by yt-dlp has been removed, the operation will fail.

In my script I have the following:

```
yt-dlp.exe --proxy !_proxyInf! --simulate --playlist-end 1 --print-to-file "%%(channel)s" %_rootDir%\yt-dlp.tmp !theURL! > nul
```

The problem I'm encountering is that yt-dlp will fail to extract channel information if the first video it encounters has been removed by Youtube or blocked by the uploader:

> This video has been removed for violating YouTube's Community Guidelines

or

> This video has been blocked in your country

After these lines print to the console, the yt-dlp.tmp file I create is empty.

If I run this modified script which repeatedly increments the value for --playlist-end and keeps trying, it will eventually succeed when it encounters a valid video. This just takes a very long time because of 429 "too many connections" errors.

```
SET /A playlistEnd=1

:get_channel_info

yt-dlp.exe --proxy !_proxyInf! --simulate --playlist-end !playlistEnd! --print-to-file "%%(channel)s" %_rootDir%\yt-dlp.tmp !theURL! > nul
SET /p uploaderName= < %_rootDir%\yt-dlp.tmp

REM Clear the temp file because --print-to-file above appends. Powershell works best here because ECHO/ can cause problems if a file named ECHO exists
powershell -Command "Set-Content %_rootDir%\yt-dlp.tmp $null"

REM Check if above failed
IF "[!uploaderName!]"=="[]" (
    SET /A playlistEnd+=1
    ECHO/
    ECHO Unable to find user info, retrying with playlist end value: !playlistEnd!
    GOTO get_channel_info
)
```

### Verbose log

```shell
Sorry, I don't remember what URL I was using that had the removed video. I posted the two warnings that were printed to the console if that helps.

I know one URL that this happens with is:

https://www.youtube.com/c/BobRossIncVideos/playlists?view=50&sort=dd&shelf_id=3

This one will randomly fail with the "video blocked in your country" message depending on the proxy used.
```

**Comment by pukkandan** [comment]
You can try `--ignore-no-formats`. With it, yt-dlp tries to extract as much info as possible even if the video is inaccessible. But I can't guarentee the specific info you are looking for is available.

For your use, it may be better to use the `playlist:` prefix for --print and set `--playlist-items 0`

**Comment by MrSmite** [comment]
> You can try `--ignore-no-formats`. With it, yt-dlp tries to extract as much info as possible even if the video is inaccessible. But I can't guarentee the specific info you are looking for is available.
> 
> For your use, it may be better to use the `playlist:` prefix for --print and set `--playlist-items 0`

Thanks for the advice. I won't be able to test it for a few days so if you think this isn't a bug but rather a limitation of Youtube's interaction with yt-dlp, this issue can be closed.

**Comment by pukkandan** [comment]
Closing. But if u have further issues when trying to do this, feel free to continue here
