### ISSUE TITLE
Embedding metadata and info json into videos that are already downloaded

### ISSUE THREAD

**Issue by blekmus** [yt-dlp/yt-dlp#2791]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

If I already have a video downloaded using yt-dlp from an earlier date. Specifically a youtube video. Is it possible to embed metadata and the info json file into it? Like using an existing file and it's url without downloading the whole file again. So the output would be as if I downloaded the video as so in the first place;

```
yt-dlp --embed-metadata --embed-info-json <url>
```

If it's not possible using the cli. Is it possible using through the python interface?

**Comment by pukkandan** [comment]
Just re-run the same command. As long as `--download-archive` or `--force-overwrite` is not used, it should just run Postprocessing without re-downloading

**Comment by blekmus** [comment]
Ah, alright. Seems pretty easy thanks! 

Also, if I were to do this programmatically using python.  Would it be a combination of [extract_info](https://github.com/yt-dlp/yt-dlp/blob/9a5b0125752179f6447ca29deb89ee452fd78b85/yt_dlp/YoutubeDL.py#L1330) to extract data and [post_process](https://github.com/yt-dlp/yt-dlp/blob/9a5b0125752179f6447ca29deb89ee452fd78b85/yt_dlp/YoutubeDL.py#L3344) to embed it into the existing file?

**Comment by pukkandan** [comment]
You can do that. Or, you can just do `ydl.download`. This is what the CLI calls, so will behave the same
