### ISSUE TITLE
allow URL caching for faster resuming download

### ISSUE THREAD

**Issue by J-ZhengLi** [yt-dlp/yt-dlp#2798]
### Checklist

- [X] I'm reporting a feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.02.04**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

**Summary:**

There are some occasions where I need to download large videos from YouTube with public wifi, but unable to finish all the downloads before my laptop's battery dies. Currently `yt-dlp` requires an URL as parameter to run, but I was hoping there is sub-command like `resume` to get whatever the last URL input and continue from that, so that I don't have to try searching for the same video link or playlist link that I wanted to download previously. 

I don't know if there's any work around in this version, if this is already an existing feature, do let me know.

**Version:**
```
[debug] Command-line config: ['-vU', 'demo.com']
[debug] Encodings: locale cp936, fs utf-8, out utf-8, err utf-8, pref cp936
[debug] yt-dlp version 2022.02.04 [c1653e9ef]
[debug] Python version 3.9.6 (CPython 64bit) - Windows-10-10.0.22000-SP0
[debug] exe versions: ffmpeg 4.4-essentials_build-www.gyan.dev (setts), ffprobe 4.4-essentials_build-www.gyan.dev
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.02.04, Current version: 2022.02.04
yt-dlp is up to date (2022.02.04)
```

**Comment by pukkandan** [comment]
Use --write-imfo and --load-info

**Comment by J-ZhengLi** [comment]
> Use --write-info and --load-info

Oh nice, thanks, that did the trick~

But I wish this is could be a default option, maybe similar to how [spotDL did it](https://github.com/spotDL/spotify-downloader#to-resume-a-failedincomplete-download-run). Which seems could be a nice feature in the future.
