### ISSUE TITLE
new questions

### ISSUE THREAD

**Issue by khk58** [yt-dlp/yt-dlp#2804]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

Hi to all, I’m @khk58,
On downloading youtube-playlists, I get lots of the following messages:

    Private video. Sign in if you've been granted access to this video
    How can I get a contact to the people, who uploaded tis video, to get access?

    Video unavailable. This video contains content from 'xxx', who has blocked it in your country on copyright grounds,
    where 'xxx' is one of the following

       ZDF
       ZDFE
       ZDFE.drama

I think 'ZDF*' is no pirated content.

What can I do?

Kind regards,

Kurt

**Comment by Bricio** [comment]
Can you open unavailable videos in your browser?

If you can't, yt-dlp cant help you.

If you can, try using `--cookies-from-browser` parameter so yt-dlp will use same cookies to access videos.
