### ISSUE TITLE
(support oldstable) support for python3.2?

### ISSUE THREAD

**Issue by mrkapqa** [yt-dlp/yt-dlp#2806]
### Checklist

- [X] I'm reporting a feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.02.04**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

Hello ,

is there a version which is backwards-compatible with python3.2?

using debian 7 on linux64bit, thanks.

**Comment by coletdjnz** [comment]
No. We only support python 3.6+.
Last release that might have supported 3.2 is https://github.com/yt-dlp/yt-dlp/releases/tag/2021.06.01. 

You should look into upgrading your python version, distro, or use youtube-dl which is currently still maintaining compatibility with obsolete python versions.

**Comment by dirkf** [comment]
>... upgrading your python version...

Maybe you could try this: https://github.com/squeaky-pl/portable-pypy?

**Comment by pukkandan** [comment]
This has been answered multiple times before. We will not support versions below 3.6 anymore. See https://github.com/yt-dlp/yt-dlp/issues/1781
