### ISSUE TITLE
Incorporate "Simple YouTube Age Restriction Bypass"

### ISSUE THREAD

**Issue by AdKiller** [yt-dlp/yt-dlp#2808]
### Checklist

- [X] I'm reporting a feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.02.04**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

This addon can view age restricted videos even without logging in to Youtube. Would be great if you could incorporate it with yt-dlp.

https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass

**Comment by Lesmiscore** [comment]
https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass/blob/main/src/components/unlocker.js

>         // Strategy 1: Retrieve the video info by using a age-gate bypass for the innertube API
>         // Source: https://github.com/yt-dlp/yt-dlp/issues/574#issuecomment-887171136

**Comment by MinePlayersPE** [comment]
Judging from https://github.com/yt-dlp/yt-dlp/issues/2770#issuecomment-1039151314, this won't be implemented on the core program

**Comment by october262** [comment]
while this works for viewing age restricted videos,
you will still need to be signed in & use a cookies file to download the video.

**Comment by pukkandan** [comment]
It uses multiple tricks to view the restricted video. We already implement most of them. The only one we don't implement is passing the request through a proxy with a logged in account. I will neither maintain such a proxy nor use any third party proxy for this. So this won't be implemented

**Comment by pukkandan** [comment]
Here's a plugin to do this: https://gist.github.com/pukkandan/fcf5ca1785c80f64e471f0ee14f990fb

Related: #3182

**Comment by AdKiller** [comment]
Thanks a lot for the plugin!

I read "Plugins are loaded from <root-dir>/ytdlp_plugins/<type>/__init__.py"

What type is this?

**Comment by pukkandan** [comment]
It's an extractor

**Comment by bjkeli** [comment]
> 这是一个提取器插件：https://gist.github.com/pukkandan/fcf5ca1785c80f64e471f0ee14f990fb
> 
> 相关：#3182

how to use it ?

**Comment by bjkeli** [comment]
> It's an extractor

how to use it ?
