### ISSUE TITLE
how to download tiktok videos in h264 or MPEG-4 format?

### ISSUE THREAD

**Issue by heyhowRyou** [yt-dlp/yt-dlp#2809]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

Youtube-DLP downloads tiktok videos in HEVC format, is there any way to download the videos in h264 or MPEG-4?

**Comment by dirkf** [comment]
An example would help.

For instance the extractor's first test page gives a video with formats having `vcodec` h265 (HEVC) and also h264. Then `-f (bv*+ba/b)[vcodec!=?h265]` should solve your problem.

**Comment by heyhowRyou** [comment]
> -f (bv*+ba/b)[vcodec!=?h265]

it worked. thank so much.

**Comment by pukkandan** [comment]
Or simpler, `-S vcodec:h264`

**Comment by Arsh1219** [comment]
> Or simpler, `-S vcodec:h264`

Thank you, just made my day.
