### ISSUE TITLE
404 Not Found - Selfmade Error

### ISSUE THREAD

**Issue by Dean-Corso** [yt-dlp/yt-dlp#2810]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.02.04**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

Hi,

so I'am not sure whether it's a bug or not but I found a specific problem in yt-dlp sending default request paramters.In some +/- cases I got that 404 not found response error from yt-dlp when trying to check some URLs and other tools or manually sending requests was working.I thought already that the problem must be the used yt-dlp sending paramters in the header.I wanted to know what parameter yt-dlp does send but there is no command anymore to let output the entire debug log with all info what means I don't get any infos about request / response from yt-dlp itself to see (just add this please).Now I was using a HTTP toolkit to get those infos logged when using yt-dlp and now I found also the problem for that 404 error.

YT does send this: accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Problem: accept: text/html

Some sites seems to reject this "text/html" paramter when you send it which then results into 404 error.

Solution: Just remove the specific "text/html" paramter.

So as user I can bypass this problem successfully by setting it manually...
`--add-header "Accept:*/*"`
...to overwrite the default used paramter.

Just wanted to post that info also for all others who having the same trouble.

### Verbose log

```shell
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.02.04 [c1653e9] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] exe versions: ffmpeg 4.0.1, ffprobe 4.0.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] [generic] Extracting URL: https://......
[generic] 1644813658jgjvp: Requesting header
WARNING: [generic] Could not send HEAD request to https://......: HTTP Error 404: Not Found
[generic] 1644813658jgjvp: Downloading webpage
ERROR: [generic] Unable to download webpage: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on  https://github.com/yt-dlp/yt-dlp , filling out the "Broken site" issue template properly. Confirm you are on the latest version using -U (caused by <HTTPError 404: 'Not Found'>); please report this issue on  https://github.com/yt-dlp/yt-dlp , filling out the "Broken site" issue template properly. Confirm you are on the latest version using -U
  File "yt_dlp\extractor\common.py", line 730, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 3558, in urlopen
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 649, in http_error_default
```

**Comment by pukkandan** [comment]
> I wanted to know what parameter yt-dlp does send but there is no command anymore to let output the entire debug log with all info what means I don't get any infos about request / response from yt-dlp itself to see (just add this please).

`--print-traffic`

> Some sites seems to reject this "text/html" paramter when you send it which then results into 404 error.

And some **supported** sites may reject the request without it. This cannot be changed in general.

While you redacted the specific site from the logs, I can see that it is not a supported site. So you will have to pass the headers manually. Or, you can create a site request for it
