### ISSUE TITLE
(ubuntu18.04) python3.6 too low^?

### ISSUE THREAD

**Issue by mrkapqa** [yt-dlp/yt-dlp#2815]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.02.04**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

hello,

i use program svp4linux on ubuntu 18.04 which apparently relies on yt-dlp

getting this error here

`You are using an unsupported version of Python. Only Python versions 3.6 and above are supported by yt-dlp`
` Tube: initializing youtube_dl...
15:34:48.404 [W]: SyntaxError('invalid syntax', ('/home/rich/SVP 4/extensions/tube/youtube_dl/__init__.py', 4, 109, \f'You are using an unsupported version of Python. Only Python versions 3.6 and above are supported by yt-dlp'  # noqa: F541\n\))
Segmentation fault (core dumped)
`

however, on Ubuntu 18.04 LTS python3 --version is 3.6.9.

please suggest a soluiton, thanks.

### Verbose log

```shell
15:34:48.100 [I]: Memory:  16017  MB total,  13315 MB free
15:34:48.100 [I]: System: finding network settings...
15:34:48.116 [I]: Screens: updating information, 2 screen(s) found
15:34:48.116 [I]: Screens: screen 0 (DisplayPort-1) - 1920x1200 @60.000 Hz, x1.0 [94 DPI]
15:34:48.116 [I]: Screens: screen 1 (DisplayPort-2) - 1280x1024 @60.000 Hz, x1.0 [86 DPI]
15:34:48.116 [I]: Screens: primary screen is 0
15:34:48.137 [I]: Main: preparing video profiles...
15:34:48.165 [I]: Main: preparing performance graphs...
15:34:48.195 [I]: Main: preparing mpv...
15:34:48.208 [I]: Main: preparing remote control...
15:34:48.208 [I]: RemoteControl: started
15:34:48.209 [I]: Main: preparing main menu...
15:34:48.227 [I]: Main: loading extensions...
15:34:48.232 [I]: Extensions: found svpcast 1.1.0.174 ...
15:34:48.232 [I]: Settings: loading cast.cfg OK
15:34:48.237 [I]: Streaming: Web UI listening on http://127.0.0.1:9900
15:34:48.243 [I]: Extensions: found svpcode 1.0.0.174 ...
15:34:48.244 [I]: Settings: loading code.cfg OK
15:34:48.256 [I]: Extensions: found svplight 2.0.0.168 ...
15:34:48.256 [I]: Settings: loading leds.cfg OK
15:34:48.271 [I]: Extensions: found svptube 2.1.0.173 ...
15:34:48.272 [I]: Settings: loading tube.cfg OK
15:34:48.379 [I]: Tube: initializing youtube_dl...
15:34:48.404 [W]: SyntaxError('invalid syntax', ('/home/rich/SVP 4/extensions/tube/youtube_dl/__init__.py', 4, 109, \f'You are using an unsupported version of Python. Only Python versions 3.6 and above are supported by yt-dlp'  # noqa: F541\n\))
Segmentation fault (core dumped)
```

**Comment by mrkapqa** [comment]
apparently this version of yt-dlp is being installed by program

https://github.com/yt-dlp/yt-dlp/releases/tag/2021.09.25

**Comment by pukkandan** [comment]
Ask the devs of whatever program is calling yt-dlp. It is trying to run yt-dlp using the wrong python version. Nothing we can do

**Comment by pukkandan** [comment]
That is, unless you can reproduce the issue by directly calling yt-dlp from the console. In that case, the issue can be re-opened
