### ISSUE TITLE
funimation -  No video formats found!

### ISSUE THREAD

**Issue by keawepoo** [yt-dlp/yt-dlp#2817]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.02.04**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

USA

### Description

Sorry if this is a duplicate post... Ive seen others but they are kinda old, and still open so I didnt know if I should have posted there or make a new one/not on the same OS.... maybe related? https://github.com/yt-dlp/yt-dlp/issues/2723

`yt-dlp --newline -f "bv+ba/b" -u ******@gmail.com -p ********* --extractor-args "funimation:version=uncut,language=english" "http://www.funimation.com/v/arifureta-from-commonplace-to-worlds-strongest/irregular-56006e1c-7417-11ec-a973-0242ac110003"`

Thanks.

### Verbose log

```shell
yt-dlp -vU --newline -f "bv+ba/b" -u ********@gmail.com -p ******** --extractor-args "funimation:version=uncut,language=english" "http://www.funimation.com/v/arifureta-from-commonplace-to-worlds-strongest/irregular-56006e1c-7417-11ec-a973-0242ac110003"
[debug] Command-line config: ['-vU', '--newline', '-f', 'bv+ba/b', '-u', 'PRIVATE', '-p', 'PRIVATE', '--extractor-args', 'funimation:version=uncut,language=english', 'http://www.funimation.com/v/arifureta-from-commonplace-to-worlds-strongest/irregular-56006e1c-7417-11ec-a973-0242ac110003']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.02.04 [c1653e9] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] exe versions: none
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.02.04, Current version: 2022.02.04
yt-dlp is up to date (2022.02.04)
[funimation:page] Checking geo-location
[funimation:page] Logging in
[debug] [funimation:page] Extracting URL: http://www.funimation.com/v/arifureta-from-commonplace-to-worlds-strongest/irregular-56006e1c-7417-11ec-a973-0242ac110003
[funimation:page] arifureta-from-commonplace-to-worlds-strongest_irregular-56006e1c-7417-11ec-a973-0242ac110003: Downloading JSON metadata
[debug] [Funimation] Extracting URL: https://www.funimation.com/player/4106081
[Funimation] 4106081: Downloading player webpage for 4106081
ERROR: [Funimation] 4056788: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp , filling out the "Broken site" issue template properly. Confirm you are on the latest version using -U
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1381, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1465, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1517, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2431, in process_video_result
  File "yt_dlp\YoutubeDL.py", line 961, in raise_no_formats
yt_dlp.utils.ExtractorError: [Funimation] 4056788: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp , filling out the "Broken site" issue template properly. Confirm you are on the latest version using -U
```

**Comment by keawepoo** [comment]
`yt-dlp -vU --newline -f "bv+ba/b" -u  ********** -p  ********** --extractor-args "funimation:version=uncut,language=english" "https://www.funimation.com/player/4106081/"
[debug] Command-line config: ['-vU', '--newline', '-f', 'bv+ba/b', '-u', 'PRIVATE', '-p', 'PRIVATE', '--extractor-args', 'funimation:version=uncut,language=english', 'https://www.funimation.com/player/4106081/']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.02.04 [c1653e9] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] exe versions: none
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.02.04, Current version: 2022.02.04
yt-dlp is up to date (2022.02.04)
[Funimation] Logging in
[debug] [Funimation] Extracting URL: https://www.funimation.com/player/4106081/
[Funimation] 4106081: Downloading player webpage for 4106081
ERROR: [Funimation] 4056788: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp , filling out the "Broken site" issue template properly. Confirm you are on the latest version using -U
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1381, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1465, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1517, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2431, in process_video_result
  File "yt_dlp\YoutubeDL.py", line 961, in raise_no_formats
yt_dlp.utils.ExtractorError: [Funimation] 4056788: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp , filling out the "Broken site" issue template properly. Confirm you are on the latest version using -U`

**Comment by CZeil** [comment]
Series that are categorized as mature content (TV-MA) need to extract cookies in order to work. Otherwise you will get this error

**Comment by keawepoo** [comment]
> 

how do I extract it?

**Comment by CZeil** [comment]
You need a browser extension (depending on which one you use, it can be firefox or chrome).

**Comment by CZeil** [comment]
> You need a browser extension (depending on which one you use, it can be firefox or chrome).

For example I use this extension for firefox 
(https://addons.mozilla.org/es/firefox/addon/export-cookies-txt/)

Then, you install the extension and after that you access funimation and log in to your user.
After you are already on the home page with your user, click on the extension and it asks you from which domain you want to extract the cookies and you have to see funimation.com, but it has to be funimation.com because if you click on www.funimation.com it will not work.

**Comment by keawepoo** [comment]
```shell
yt-dlp -vU --newline -f "bv+ba/b" -u  ******* -p  ******** --windows-filenames --cookies "cookies-funimation-com.txt" --extractor-args "funimation:version=uncut,language=english" "https://www.funimation.com/player/4106081/"
[debug] Command-line config: ['-vU', '--newline', '-f', 'bv+ba/b', '-u', 'PRIVATE', '-p', 'PRIVATE', '--windows-filenames', '--cookies', 'cookies-funimation-com.txt', '--extractor-args', 'funimation:version=uncut,language=english', 'https://www.funimation.com/player/4106081/']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.02.04 [c1653e9] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] exe versions: none
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.02.04, Current version: 2022.02.04
yt-dlp is up to date (2022.02.04)
[Funimation] Logging in
[debug] [Funimation] Extracting URL: https://www.funimation.com/player/4106081/
[Funimation] 4106081: Downloading player webpage for 4106081
ERROR: [Funimation] 4056788: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp , filling out the "Broken site" issue template properly. Confirm you are on the latest version using -U
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1381, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1465, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1517, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2431, in process_video_result
  File "yt_dlp\YoutubeDL.py", line 961, in raise_no_formats
yt_dlp.utils.ExtractorError: [Funimation] 4056788: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp , filling out the "Broken site" issue template properly. Confirm you are on the latest version using -U
```

**Comment by CZeil** [comment]
> ```shell
> yt-dlp -vU --newline -f "bv+ba/b" -u  ******* -p  ******** --windows-filenames --cookies "cookies-funimation-com.txt" --extractor-args "funimation:version=uncut,language=english" "https://www.funimation.com/player/4106081/"
> [debug] Command-line config: ['-vU', '--newline', '-f', 'bv+ba/b', '-u', 'PRIVATE', '-p', 'PRIVATE', '--windows-filenames', '--cookies', 'cookies-funimation-com.txt', '--extractor-args', 'funimation:version=uncut,language=english', 'https://www.funimation.com/player/4106081/']
> [debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
> [debug] yt-dlp version 2022.02.04 [c1653e9] (win_exe)
> [debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
> [debug] exe versions: none
> [debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
> [debug] Proxy map: {}
> Latest version: 2022.02.04, Current version: 2022.02.04
> yt-dlp is up to date (2022.02.04)
> [Funimation] Logging in
> [debug] [Funimation] Extracting URL: https://www.funimation.com/player/4106081/
> [Funimation] 4106081: Downloading player webpage for 4106081
> ERROR: [Funimation] 4056788: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp , filling out the "Broken site" issue template properly. Confirm you are on the latest version using -U
> Traceback (most recent call last):
>   File "yt_dlp\YoutubeDL.py", line 1381, in wrapper
>   File "yt_dlp\YoutubeDL.py", line 1465, in __extract_info
>   File "yt_dlp\YoutubeDL.py", line 1517, in process_ie_result
>   File "yt_dlp\YoutubeDL.py", line 2431, in process_video_result
>   File "yt_dlp\YoutubeDL.py", line 961, in raise_no_formats
> yt_dlp.utils.ExtractorError: [Funimation] 4056788: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp , filling out the "Broken site" issue template properly. Confirm you are on the latest version using -U
> ```

Try to split the extractor args in two

Example: 
--extractor-args funimation:version=uncut,simulcast --extractor-args funimation:language=japanese 

Another thing is that this chapter has only simulcast version, so yt-dlp does not find the specified format.

**Comment by keawepoo** [comment]
worked :) Thank you.
