### ISSUE TITLE
[Broken] Crackle

### ISSUE THREAD

**Issue by BeeMuffins** [yt-dlp/yt-dlp#282]
## Checklist

- [X] I'm reporting a broken site support
- [X] I've verified that I'm running yt-dlp version **2021.04.22**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
yt-dlp -v -F "https://www.crackle.com/watch/7320"
[debug] Command-line config: ['-v', '-F', 'https://www.crackle.com/watch/7320']
[debug] Loading archive file None
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] yt-dlp version 2021.04.22
[debug] Python version 3.9.4 (CPython 64bit) - macOS-11.3-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.4, ffprobe 4.4
[debug] Proxy map: {}
[Crackle] 7320: Downloading media JSON as US
[Crackle] 7320: Downloading media JSON as AU
[Crackle] 7320: Downloading media JSON as CA
[Crackle] 7320: Downloading media JSON as AS
[Crackle] 7320: Downloading media JSON as FM
[Crackle] 7320: Downloading media JSON as GU
[Crackle] 7320: Downloading media JSON as MP
[Crackle] 7320: Downloading media JSON as PR
[Crackle] 7320: Downloading media JSON as PW
[Crackle] 7320: Downloading media JSON as MH
[Crackle] 7320: Downloading media JSON as VI
ERROR: exceptions must derive from BaseException
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1059, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1080, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 558, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/extractor/crackle.py", line 200, in _real_extract
    raise last_e
TypeError: exceptions must derive from BaseException

```

## Description

Receive the above error when attempting to download from Crackle.  While I didn't see any issues here, there seems to be some similar issues on youtube-dl, but they have been open for a long period of time with no updates.  Reference https://github.com/ytdl-org/youtube-dl/issues/25791 and https://github.com/ytdl-org/youtube-dl/issues/20622

If this is a DRM thing is site support removed here or is it based on upstream?

Tried with --allow-unplayable-formats which provides the same results.  The crackle extractor code also references a -usedrm flag, but that prompts for an account password.

**Comment by pukkandan** [comment]
The error seems to happen when your country is not in the list `'US', 'AU', 'CA', 'AS', 'FM', 'GU', 'MP', 'PR', 'PW', 'MH', 'VI'`

Try giving your country code with `--geo-bypass-country`

Also, let me know which country you are in, so that I can add it to the list/try fixing the issue some other way

**Comment by BeeMuffins** [comment]
Thanks for looking into.  I'm coming from a country in that list and used ```--geo-bypass-country``` with the country code and get the same error.  Tried with a VPN as well for a country outside that list also using ```--geo-bypass-county GB``` for example and it provides the same error as well.

**Comment by pukkandan** [comment]
The URL you gave seems to be a that of a show. Playlists are not currently supported for crackle
When I try to download the single episodes instead, I can see that it is DRM protected
