### ISSUE TITLE
yt-dlp in combination with ffmpeg returns wrong PID

### ISSUE THREAD

**Issue by sc44** [yt-dlp/yt-dlp#2822]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

Hi there,

we have a problem with the returned PID's from ffmpeg in combination with yt-dlp.
We need a valid PID from ffmpeg to terminate the process via timer later.

Test the following little Python program and then you will see the problem:

```
#!/usr/bin/env python3

import subprocess
import time

link = "https://fashiontv-fashiontv-4-de.samsung.wurl.com/manifest/playlist.m3u8"

cmd_string = 'ffmpeg -i $(yt-dlp -g "' + link + '") -c:v copy -c:a copy "out.ts" 2> /dev/null'
#cmd_string = 'ffmpeg -i $(youtube-dl -g "' + link + '") -c:v copy -c:a copy "out.ts" 2> /dev/null'

for z in range(3):
    try:
        last_pid = int(subprocess.check_output(["pidof", "-s", "ffmpeg"]))
    except:
        last_pid = 0

    subprocess.Popen(cmd_string, shell=True)
    print("\n0.00 - 000 - {:d}".format(last_pid))

    start = time.time()
    new_pid = 0
    for x in range(700):
        try:
            new_pid = int(subprocess.check_output(["pidof", "-s", "ffmpeg"]))
        except:
            pass
        if not new_pid == last_pid:
            print("{:.2f} - {:3d} - {:d}".format(time.time()-start, x, new_pid))
            last_pid = new_pid

    print("{:.2f} - {:3d} - {:d}".format(time.time()-start, x, new_pid))
    print(subprocess.check_output(["pidof", "ffmpeg"]))

subprocess.Popen('killall ffmpeg', shell=True)

```

You can see that after about 0.5 seconds it returns an wrong PID, then it switched back to the old one and after some time the correct PID is returned. This is not how we can reliably determine a valid PID. If you try the same with youtube-dl everything is fine. What is it?

Thanks for your effort

**Comment by pukkandan** [comment]
This sounds like more of a python question than a yt-dlp question. Best to ask in some python forums

**Comment by sc44** [comment]
This is not a python/unix problem because the same with **youtube-dl** works fine.

**Comment by Lesmiscore** [comment]
`yt-dlp -g` exits after outputting playlist URL, that's it.

**Comment by fstirlitz** [comment]
This is some extremely poor code. `pidof` and `killall` are tools for sysadmins, not programmers.

**Comment by fstirlitz** [comment]
The problem is that you have poor code. It’s just as ill-advised to do the same in production:

https://github.com/sc44/Stream-Recorder/blob/34dab4113c14860da33272d535a2985e4c9f4b87/srecorder.py#L927-L933

https://github.com/sc44/Stream-Recorder/blob/34dab4113c14860da33272d535a2985e4c9f4b87/srecorder.py#L1003

`subprocess.Popen` has a `pid` attribute. Use that one and **never touch any other PID**.
