### ISSUE TITLE
English subtitles file will overwrite auto-generated english subtitles file

### ISSUE THREAD

**Issue by ontamomo** [yt-dlp/yt-dlp#2854]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.02.04**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

Trying to download both the auto-generated english subtitles and english subtitles if available at the same time causes the english subtitle to overwrite the auto-generated english subtitle file. This does not happen if you download the british english subtitles along with auto-generated english subtitles probably because the title name of the file is different "en-GB" for british english versus the "en" for both english and auto-generated english.
So if you run something like:
--write-auto-subs
--write-subs
--sub-langs en
--sub-langs en-GB

You will not get the auto-generated subtitles and english subtitles in two separate files, you end up with english subtitles in one file alone.

### Verbose log

```shell
--write-auto-subs
--write-subs
--sub-langs en
--sub-langs en-GB
```

**Comment by pukkandan** [comment]
Same issue as https://github.com/yt-dlp/yt-dlp/issues/946, https://github.com/yt-dlp/yt-dlp/issues/2262
