### ISSUE TITLE
Support for fptplay.vn

### ISSUE THREAD

**Issue by ualaa1** [yt-dlp/yt-dlp#2857]
### Checklist

- [X] I'm reporting a site feature request
- [X] I've verified that I'm running yt-dlp version **2022.02.04**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Vietnam

### Example URLs

https://fptplay.vn/xem-video/dai-chien-nguoi-khong-lo-phan-cuoi-attack-on-titan-final-season-61cea96078507bc5102527fc

### Description

Videos are only accessible in Vietnam. Yt-dlp download URL is https://vod02-cdn.fptplay.net/ovod/_definst_/smil:mp4/encoded/20220117/anime_paytv_aniplus_aotss4_2022_ep01/d729a85e8520db6b441a6980742a4898.smil/playlist.m3u8?token=eyJoYXNoX3ZhbHVlIjogIjk5MjA2MjExMDQwYmM4MzAwNDBkNjg5YTk2MjFjMjY1IiwgInZpZGVvX2lkIjogIjYxY2VhOTYwNzg1MDdiYzUxMDI1MjdmYyIsICJzZXJ2ZXJfdGltZSI6IDE2NDU1NTY2MzAsICJ2YWxpZF9taW51dGVzIjogNzIwfQ (no proxies needed if outside VIetnam)

### Verbose log

```shell
yt-dlp -v "https://fptplay.vn/xem-video/dai-chien-nguoi-khong-lo-phan-cuoi-attack-on-titan-final-season-61cea96078507bc5102527fc"
[debug] Command-line config: ['-v', 'https://fptplay.vn/xem-video/dai-chien-nguoi-khong-lo-phan-cuoi-attack-on-titan-final-season-61cea96078507bc5102527fc']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.02.04 [c1653e9ef]
[debug] Python version 3.9.0 (CPython 64bit) - macOS-12.0.1-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [generic] Extracting URL: https://fptplay.vn/xem-video/dai-chien-nguoi-khong-lo-phan-cuoi-attack-on-titan-final-season-61cea96078507bc5102527fc
[generic] dai-chien-nguoi-khong-lo-phan-cuoi-attack-on-titan-final-season-61cea96078507bc5102527fc: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] dai-chien-nguoi-khong-lo-phan-cuoi-attack-on-titan-final-season-61cea96078507bc5102527fc: Downloading webpage
[generic] dai-chien-nguoi-khong-lo-phan-cuoi-attack-on-titan-final-season-61cea96078507bc5102527fc: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://fptplay.vn/xem-video/dai-chien-nguoi-khong-lo-phan-cuoi-attack-on-titan-final-season-61cea96078507bc5102527fc
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1381, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1451, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 612, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/extractor/generic.py", line 3986, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://fptplay.vn/xem-video/dai-chien-nguoi-khong-lo-phan-cuoi-attack-on-titan-final-season-61cea96078507bc5102527fc
```

**Comment by mrvson** [comment]
addon not work pls update

**Comment by bashonly** [comment]
@mrvson open a new "broken site support" issue please
