### ISSUE TITLE
[CBC] not download CLOSED-CAPTIONS subtitles

### ISSUE THREAD

**Issue by mtrakal** [yt-dlp/yt-dlp#2859]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.02.04**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Canada

### Description

It has captions on website (English subtitles), but YT DLP don't see them and don't download them.
There is no URI attribute in m3u8 file, captions are marked as CLOSED-CAPTIONS

```
#EXT-X-MEDIA:TYPE=CLOSED-CAPTIONS,GROUP-ID="CC",LANGUAGE="en",NAME="English",DEFAULT=YES,AUTOSELECT=YES,INSTREAM-ID="CC1"
#EXT-X-STREAM-INF:BANDWIDTH=2767793,RESOLUTION=1280x720,CODECS="avc1.4d401f,mp4a.40.2",AUDIO="audio",CLOSED-CAPTIONS="CC"
```

Maybe it could be related to some another extractor: https://github.com/yt-dlp/yt-dlp/pull/1980/commits/f3fa3e1404cade685373e1c84df7edc1415b06d5 ?

### Verbose log

```shell
[debug] Command-line config: ['-vU', 'https://gem.cbc.ca/media/absolutely-canadian/s10', '--list-subs']
[debug] Encodings: locale cp1250, fs utf-8, out utf-8, err utf-8, pref cp1250
[debug] yt-dlp version 2022.02.04 [c1653e9ef] (win_exe)
[debug] Python version 3.10.1 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] exe versions: ffmpeg N-104959-gfa2e460f63-20211221 (setts), ffprobe N-104959-gfa2e460f63-20211221
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.02.04, Current version: 2022.02.04
yt-dlp is up to date (2022.02.04)
[debug] [gem.cbc.ca:playlist] Extracting URL: https://gem.cbc.ca/media/absolutely-canadian/s10
[gem.cbc.ca:playlist] absolutely-canadian/s10: Downloading JSON metadata
[download] Downloading playlist: Season 10
[gem.cbc.ca:playlist] playlist Season 10: Collected 1 videos; downloading 1 of them
[download] Downloading video 1 of 1
[debug] Using fake IP 99.255.78.80 (CA) as X-Forwarded-For
[debug] [gem.cbc.ca] Extracting URL: https://gem.cbc.ca/media/absolutely-canadian/s10e01
[gem.cbc.ca] absolutely-canadian/s10e01: Downloading JSON metadata
[gem.cbc.ca] absolutely-canadian/s10e01: Downloading JSON metadata
[gem.cbc.ca] absolutely-canadian/s10e01: Downloading m3u8 information
[gem.cbc.ca] absolutely-canadian/s10e01: Downloading secret XML
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
absolutely-canadian/s10e01 has no subtitles
[download] Finished downloading playlist: Season 10
```

**Comment by nyuszika7h** [comment]
FFmpeg is able to detect these captions but not extract or embed them AFAIK. You can use CCExtractor for this instead. Might be worth adding it as an optional dependency for yt-dlp, it's pretty easy to detect the CC magic from the first ~60 kB of the file (`b'1GA94'`, at least for H.264), or call ffprobe and grep for "Closed Captions".

**Comment by pukkandan** [comment]
If the subs are inside the video, I don't see what yt-dlp can/should do here

**Comment by nyuszika7h** [comment]
They're embedded in the H.264 NAL (which is a pretty standard thing to do for CEA-608) but not burned in to the video stream, CCExtractor can extract them.

**Comment by pukkandan** [comment]
I got that. But should yt-dlp be able to extract them? It can't currently extract any subtitles embedded into videos - even if ffmpeg can handle it. Are you asking for a new `--extract-subtitles` option like `-x`? I honestly don't think such an option is warranted.

**Comment by nyuszika7h** [comment]
I mean you could argue it's easy enough to just run CCExtractor manually, but I do think having support for automating it (even if as a separate option) would be nice. Then the user only needs to at most install it when yt-dlp warns that it's needed for this file, rather than Google themselves how to extract it (and the first first intuition might be to use ffmpeg, which won't work). Especially since sometimes this is the only subtitle format available, and subtitles are important for accessibility too.

**Comment by mtrakal** [comment]
> Note the "Closed Captions" marking in stream 0:0. The subtitles are probably there, but your player may not support them (VLC, for example, works fine.) You may be able to extract the subtitles from the file using ffmpeg if you want them in a different format

You are right, subtitles are really in video stream file (not burned into video), but MPC-BE can't load them. VLC really works fine, can show/hide them.

Sorry for report this like issue, I was confused, that subtitles are on website and in m3u8 file, but `--list-subs` didn't see them.

It would be nice, when `--list-subs` could show that there is existing subtitles, but are closed-captions and show Hint in terminal, that you can use external tool to extract them from video stream after download finished, instead of show No subtitles.

**Comment by nyuszika7h** [comment]
One thing I forgot to mention in my previous comment: the difference with `--extract-audio` here is that while *some* players can deal with CEA-608 subtitles, barely any can, so it makes sense to provide an option to extract it IMO. Not everyone uses VLC.

**Comment by Zirro** [comment]
> FFmpeg is able to detect these captions but not extract or otherwise properly handle them AFAIK.

FFmpeg has 'experimental' support for reading these according to this post, which also contains an example command: https://old.reddit.com/r/ffmpeg/comments/recfke/extracting_eia608_closed_captions_so_i_can_make/hogp1fe/ (with EIA-608 apparently being an alternative name for CEA-608)

**Comment by makeworld-the-better-one** [comment]
> I got that. But should yt-dlp be able to extract them? It can't currently extract any subtitles embedded into videos - even if ffmpeg can handle it. Are you asking for a new `--extract-subtitles` option like `-x`? I honestly don't think such an option is warranted.
@pukkandan 

If what @nyuszika7h says is true, that "barely any [video players] can" extract these subtitles, then being able to extract them is probably a useful thing for yt-dlp to do. I can see how it might be out of scope, but it would definitely be useful for cases like this.

**Comment by pukkandan** [comment]
Being useful does not mean it is in scope of the program. yt-dlp doesn't even "know" that there are subs in the video till after it is downloaded. So even if this is implemented, it will just have to blindly call ffmpeg on the downloaded file. You can just do that using `--exec` instead. So I don't think this is a compelling enough reason to add an entire postprocessor
