### ISSUE TITLE
[Site Request] dougbillings.us

### ISSUE THREAD

**Issue by HalvorRaknes** [yt-dlp/yt-dlp#286]
## Checklist

- [x] I'm reporting a new site support request
- [x] I've verified that I'm running yt-dlp version **2021.04.22**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that none of provided URLs violate any copyrights
- [x] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

- Single video: https://www.youtube.com/watch?v=BaW_jenozKc
- Single video: https://youtu.be/BaW_jenozKc
- Playlist: https://www.youtube.com/playlist?list=PL4lCao7KL_QFVb7Iudeipvc2BCavECqzc

## Description

WRITE DESCRIPTION HERE

**Comment by HalvorRaknes** [comment]
I'm taking a chance about the "bugtracker" as I cannot find any link to it, but here's a sample video that yt-dlp currently won't download: https://dougbillings.us/wp-content/uploads/2021/04/TheRightSide20210429Compressed.mp4

**Comment by pukkandan** [comment]
> https://dougbillings.us/wp-content/uploads/2021/04/TheRightSide20210429Compressed.mp4

This URL doesnt open and just redirects me to the home page

**Comment by pukkandan** [comment]
When I tried with a random video on the website, it does download:

```
$ yt-dlp "https://dougbillings.us/video/dougs-latest-interview-with-sidney-powell"
[generic] dougs-latest-interview-with-sidney-powell: Requesting header
[redirect] Following redirect to https://dougbillings.us/video/dougs-latest-interview-with-sidney-powell/
[generic] dougs-latest-interview-with-sidney-powell: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] dougs-latest-interview-with-sidney-powell: Downloading webpage
[generic] dougs-latest-interview-with-sidney-powell: Extracting information
[download] Downloading playlist: Doug's latest interview with Sidney Powell
[generic] playlist Doug's latest interview with Sidney Powell: Collected 1 videos; downloading 1 of them
[download] Downloading video 1 of 1
[info] dougs-latest-interview-with-sidney-powell: Downloading format(s) 0
[download] Destination: Doug's latest interview with Sidney Powell [dougs-latest-interview-with-sidney-powell].mp4
[download]   0.3% of 342.38MiB at 947.76KiB/s ETA 06:08
ERROR: Interrupted by user
```
