### ISSUE TITLE
Free Download Manager support

### ISSUE THREAD

**Issue by CrypticCus** [yt-dlp/yt-dlp#2863]
### Checklist

- [X] I'm reporting a feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.02.04**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

fdm recetly added support for addons. can you add support for fdm structure so we can use this in fdm?

**Comment by pukkandan** [comment]
https://www.freedownloadmanager.org this? It does not appear to be a CLI program. If it is, I can't find any docs. Provide more details

**Comment by Lesmiscore** [comment]
To confirm you what are you mentioning about, but is this what you mean right?

https://github.com/FreeDownloadManagerTeam/fdm-addons-docs

**Comment by CrypticCus** [comment]
yes thats what i am talking about

**Comment by pukkandan** [comment]
Someone needs to make a **FDM plugin** to support yt-dlp. There is nothing to be done in yt-dlp to achieve this and so this issue doesnt belong here

**Comment by CrypticCus** [comment]
anyone wants to help to create an addon for us? we don't get any support from fdm end. creator team added addon support for us but we can't add this addon to there. they don't create addons.

**Comment by meowcateatrat** [comment]
Done. https://github.com/meowcateatrat/elephant.
