### ISSUE TITLE
Tiktok mobile (vm.tiktok) links don't work

### ISSUE THREAD

**Issue by AephK** [yt-dlp/yt-dlp#2864]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.02.04**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United Kingdom

### Description

When passing a mobile Tiktok link (in the example below https://vm.tiktok.com/ZMLhV4Lcv/, yt-dlp fails to download the video.

Running a curl against this URL shows that Tiktok is just redirecting from vm.tiktok.com to the relevant tiktok.com page:

```
curl https://vm.tiktok.com/ZMLhV4Lcv/
<a href="https://www.tiktok.com/@jasper.roberts/video/7066492416550980910?_t=8Q72LwQX7Dh&amp;_r=1">Moved Permanently</a>.
```

Would it be possible for yt-dlp to account for this and use the redirected link instead of the one passed to it?

I am not familiar enough with how yt-dlp works to know if this is possible.

Many thanks,
AephK

### Verbose log

```shell
.\yt-dlp.exe -vU https://vm.tiktok.com/ZMLhV4Lcv/ --ffmpeg-location .\ffmpeg\bin
[debug] Command-line config: ['-vU', 'https://vm.tiktok.com/ZMLhV4Lcv/', '--ffmpeg-location', '.\\ffmpeg\\bin']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.02.04 [c1653e9] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.22000-SP0
[debug] exe versions: ffmpeg 2022-01-19-git-dd17c86aa1-full_build-www.gyan.dev (setts), ffprobe 2022-01-19-git-dd17c86aa1-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.02.04, Current version: 2022.02.04
yt-dlp is up to date (2022.02.04)
[debug] [generic] Extracting URL: https://vm.tiktok.com/ZMLhV4Lcv/
[generic] ZMLhV4Lcv: Requesting header
WARNING: [generic] Could not send HEAD request to https://vm.tiktok.com/ZMLhV4Lcv/ ): The read operation timed out
[generic] ZMLhV4Lcv: Downloading webpage
ERROR: [generic] Unable to download webpage: The read operation timed out (caused by timeout('The read operation timed out')); please report this issue on  https://github.com/yt-dlp/yt-dlp , filling out the "Broken site" issue template properly. Confirm you are on the latest version using -U (caused by timeout('The read operation timed out')); please report this issue on  https://github.com/yt-dlp/yt-dlp , filling out the "Broken site" issue template properly. Confirm you are on the latest version using -U
  File "yt_dlp\extractor\common.py", line 730, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 3558, in urlopen
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 563, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 755, in http_error_302
  File "urllib\request.py", line 525, in open
  File "urllib\request.py", line 542, in _open
  File "urllib\request.py", line 502, in _call_chain
  File "yt_dlp\utils.py", line 1501, in https_open
  File "urllib\request.py", line 1358, in do_open
  File "http\client.py", line 1344, in getresponse
  File "http\client.py", line 307, in begin
  File "http\client.py", line 268, in _read_status
  File "socket.py", line 669, in readinto
  File "ssl.py", line 1241, in recv_into
  File "ssl.py", line 1099, in read
```

**Comment by MinePlayersPE** [comment]
Duplicate of https://github.com/yt-dlp/yt-dlp/issues/2396

**Comment by okandorman6-max** [comment]
https://vm.tiktok.com/ZS9dHGEcApLyX-2WCP1/ Bu gönderi TikTok Lite aracılığıyla paylaşıldı. Daha fazla gönderinin keyfini çıkarmak için TikTok Lite'ı indirin:  https://www.tiktok.com/tiktoklite
