### ISSUE TITLE
Next question on yt-dlp

### ISSUE THREAD

**Issue by khk58** [yt-dlp/yt-dlp#2865]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

Dear all,

First I beg pardon for my poor english.

On downloading the following playlist

'yt-dlp --cookies-from-browser firefox --playlist-start 1750 --download-archive ..\archive.txt  -i --geo-bypass -o "%%(title)s.%%(ext)s"  https://www.youtube.com/playlist?list=UU6ySWla_95opV6RuXOX3HMQ'

I get the following messages

[download] Downloading video 4 of 1623
[youtube] RDdj4EsRhG0: Downloading webpage
[youtube] RDdj4EsRhG0: Downloading android player API JSON
[youtube] RDdj4EsRhG0: Downloading MPD manifest
[youtube] RDdj4EsRhG0: Downloading MPD manifest
[info] RDdj4EsRhG0: Downloading 1 format(s): 302+251
[dashsegments] Total fragments: 162
[download] Destination: 🌲🎉 12 - Smart Home.f302.webm
[download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 1 of 10) ...
[download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 2 of 10) ...
[download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 3 of 10) ...
[download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 4 of 10) ...
[download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 5 of 10) ...
[download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 6 of 10) ...
[download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 7 of 10) ...
[download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 8 of 10) ...
[download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 9 of 10) ...
[download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 10 of 10) ...
ERROR: giving up after 10 retries
ERROR: unable to download video data: [Errno 2] No such file or directory: '🌲🎉 12 - Smart Home.f302.webm.part-Frag1'

[download] Downloading video 11 of 1623
[youtube] nym7AgETvog: Downloading webpage
[youtube] nym7AgETvog: Downloading android player API JSON
[youtube] nym7AgETvog: Downloading MPD manifest
[youtube] nym7AgETvog: Downloading MPD manifest
[info] nym7AgETvog: Downloading 1 format(s): 302+251
[dashsegments] Total fragments: 26
[download] Destination: 🌲🎉 05 - Nicht-Sport Bluetooth In-Ear-Kopfhörer.f302.webm
[download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 1 of 10) ...
[download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 2 of 10) ...
[download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 3 of 10) ...
[download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 4 of 10) ...
[download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 5 of 10) ...
[download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 6 of 10) ...
[download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 7 of 10) ...
[download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 8 of 10) ...
[download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 9 of 10) ...
[download] Got server HTTP error: HTTP Error 503: Service Unavailable. Retrying (attempt 10 of 10) ...
ERROR: giving up after 10 retries
ERROR: unable to download video data: [Errno 2] No such file or directory: '🌲🎉 05 - Nicht-Sport Bluetooth In-Ear-Kopfhörer.f302.webm.part-Frag1'

But if I look in the browser the above mentioned URL's, I can completely see them.

The other files (1-3, 5-10, 12-....) can be downloaded without any errors.

What shall I do?

Kind regards from Austria

Kurt

**Comment by pukkandan** [comment]
Try with `--check-formats`

**Comment by khk58** [comment]
Thanks, this works
