### ISSUE TITLE
[Wistia] Some wistia hosted fail with Downloading 0 videos error

### ISSUE THREAD

**Issue by someziggyman** [yt-dlp/yt-dlp#2866]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.02.04**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

anywhere

### Description

Test link with Wistia hosted contnent is redirected to generic extractor for some reason:
https://robinsharma.wistia.com/medias/bvcxteevyj

This one works though:
https://fast.wistia.net/embed/playlists/aodt9etokc

### Verbose log

```shell
/yt-dlp -F -v "https://robinsharma.wistia.com/medias/bvcxteevyj"
[debug] Command-line config: ['-F', '-v', 'https://robinsharma.wistia.com/medias/bvcxteevyj']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.02.03 [28469edd7] (zip)
[debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
[debug] Python version 3.9.10 (CPython 64bit) - macOS-11.6.4-arm64-arm-64bit
[debug] exe versions: none
[debug] Optional libraries: sqlite
[debug] Proxy map: {}
[debug] [generic] Extracting URL: https://robinsharma.wistia.com/medias/bvcxteevyj
[generic] bvcxteevyj: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] bvcxteevyj: Downloading webpage
[generic] bvcxteevyj: Extracting information
[debug] Looking for video embeds
[download] Downloading playlist: The Greatness Guide
[generic] playlist The Greatness Guide: Downloading 0 videos
[download] Finished downloading playlist: The Greatness Guide
```

**Comment by dirkf** [comment]
The extractor only knows about fast.wistia.com (or.net) and it expects `embed/` before `medias/xxxx`. This patch finds the media at https://robinsharma.wistia.com/medias/bvcxteevyj:
```py
--- old/yt_dlp/extractor/wistia.py
+++ new/yt_dlp/extractor/wistia.py
@@ -14,7 +14,7 @@ from ..utils import (
 
 class WistiaBaseIE(InfoExtractor):
     _VALID_ID_REGEX = r'(?P<id>[a-z0-9]{10})'
-    _VALID_URL_BASE = r'https?://(?:fast\.)?wistia\.(?:net|com)/embed/'
+    _VALID_URL_BASE = r'https?://(?:\w+\.)?wistia\.(?:net|com)/(?:embed/)?'
     _EMBED_BASE_URL = 'http://fast.wistia.com/embed/'
 
     def _download_embed_config(self, config_type, config_id, referer):
 ```

**Comment by aliafshany** [comment]
i have this issue at the current latest version

**Comment by pukkandan** [comment]
> consider whether `_EMBED_BASE_URL` should use https

Doesn't really matter. If https is supported, it should auto-upgrade
