### ISSUE TITLE
ParamountPlus: No video Formats Found!

### ISSUE THREAD

**Issue by supercool117** [yt-dlp/yt-dlp#2868]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.02.04**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United States

### Description

Getting a "No video formats found!" error trying to download tmnt from ParamountPlus. I've tried with and without credentials, but it doesn't appear to make a difference.

### Verbose log

```shell
yt-dlp https://www.paramountplus.com/shows/rise-of-the-teenage-mutant-ninja-turtles/video/DQDAfHqw8CSi8cO2_RAEwiOFClp0UpON/rise-of-the-teenage-mutant-ninja-turtles-flushed-but-never-forgotten-lair-games/ -u XXX -p XXX -vU
[debug] Command-line config: ['https://www.paramountplus.com/shows/rise-of-the-teenage-mutant-ninja-turtles/video/DQDAfHqw8CSi8cO2_RAEwiOFClp0UpON/rise-of-the-teenage-mutant-ninja-turtles-flushed-but-never-forgotten-lair-games/', '-u', 'PRIVATE', '-p', 'PRIVATE', '-vU']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.02.04 [c1653e9] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] exe versions: none
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.02.04, Current version: 2022.02.04
yt-dlp is up to date (2022.02.04)
[debug] [ParamountPlus] Extracting URL: https://www.paramountplus.com/shows/rise-of-the-teenage-mutant-ninja-turtles/video/DQDAfHqw8CSi8cO2_RAEwiOFClp0UpON/rise-of-the-teenage-mutant-ninja-turtles-flushed-but-never-forgotten-lair-games/
[ParamountPlus] DQDAfHqw8CSi8cO2_RAEwiOFClp0UpON: Downloading JSON metadata
[ParamountPlus] DQDAfHqw8CSi8cO2_RAEwiOFClp0UpON: Downloading JSON metadata
[ParamountPlus] DQDAfHqw8CSi8cO2_RAEwiOFClp0UpON: Downloading DASH_CENC_PRECON SMIL data
[ParamountPlus] DQDAfHqw8CSi8cO2_RAEwiOFClp0UpON: Downloading m3u8 information
WARNING: [ParamountPlus] Failed to download m3u8 information: <urlopen error timed out>
ERROR: [ParamountPlus] DQDAfHqw8CSi8cO2_RAEwiOFClp0UpON: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp , filling out the "Broken site" issue template properly. Confirm you are on the latest version using -U
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1381, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1465, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1517, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2431, in process_video_result
  File "yt_dlp\YoutubeDL.py", line 961, in raise_no_formats
yt_dlp.utils.ExtractorError: [ParamountPlus] DQDAfHqw8CSi8cO2_RAEwiOFClp0UpON: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp , filling out the "Broken site" issue template properly. Confirm you are on the latest version using -U
```

**Comment by october262** [comment]
try this video again - https://www.paramountplus.com/shows/rise-of-the-teenage-mutant-ninja-turtles/video/DQDAfHqw8CSi8cO2_RAEwiOFClp0UpON/rise-of-the-teenage-mutant-ninja-turtles-flushed-but-never-forgotten-lair-games/ 
it worked for me.

**Comment by supercool117** [comment]
thanks for checking, I had to turn my VPN off, works for me now too.
