### ISSUE TITLE
[Site Request] ukcolumn.org

### ISSUE THREAD

**Issue by HalvorRaknes** [yt-dlp/yt-dlp#287]
## Checklist

- [x] I'm reporting a new site support request
- [x] I've verified that I'm running yt-dlp version **2021.04.22**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that none of provided URLs violate any copyrights
- [x] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs
https://www.ukcolumn.org/index.php/ukcolumn-news/uk-column-news-28th-april-2021

## Description

The Firefox extension "Flash and Video Download" doesn't recognize any content on this page at all. "Video DownloadHelper" recognizes 5 format variations (240p - 1080p).

**Comment by pukkandan** [comment]
Does all video URLs look like: `https://www.ukcolumn.org(/index.php)?/ukcolumn-news/...`?

**Comment by pukkandan** [comment]
nvm, I also found these: https://www.ukcolumn.org/video/insight-eu-military-unification
