### ISSUE TITLE
Can't download from Facebook

### ISSUE THREAD

**Issue by midaspt** [yt-dlp/yt-dlp#2874]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.02.04**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Europe

### Description

Just can't download <https://www.facebook.com/UNILADTech/videos/463029358636004/>...

See output below.

### Verbose log

```shell
E:\_PROGS\CLI\yt-dl-ffmpeg>yt-dlp_min.exe https://www.facebook.com/watch/?v=463029358636004
[facebook] 463029358636004: Downloading webpage
[facebook] 463029358636004: Downloading webpage
ERROR: [facebook] 463029358636004: Cannot parse data; please report this issue on  https://github.com/yt-dlp/yt-dlp , filling out the "Broken site" issue template properly. Confirm you are on the latest version using -U; please report this issue on  https://github.com/yt-dlp/yt-dlp , filling out the "Broken site" issue template properly. Confirm you are on the latest version using -U
```

**Comment by dinbtechit** [comment]
Have the same issue any update on this? Perhaps the video is geo blocked?

**Comment by dinbtechit** [comment]
I had the same issue.  I was able to get around that by passing in a `--cookies yourfbcookie.txt` .  Basically, export the facebook cookie from your browser. I used a chrome addon for that.


```
 yt-dlp --cookies yourfbcookie.txt  https://www.facebook.com/UNILADTech/videos/463029358636004
```

**Comment by 4mohamedaliii** [comment]
Is there any other way to download it without using cookies and give my username and password?
Could yt-dlp find a hacky way to pass that?
