### ISSUE TITLE
Verbose log with -vU or -v ?

### ISSUE THREAD

**Issue by HalvorRaknes** [yt-dlp/yt-dlp#2877]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

Why are we instructed to submit the verbose log using the `-vU` rather than the `-v` option? The reason I ask is that the former will not show much of the download log that gives much information  about the problems encountered.

**Comment by CZeil** [comment]
in case you have not downloaded the latest version of yt-dlp the -Uv command updates it, but if you have already downloaded the latest version just use the -v option, at least that's how I see it.

**Comment by pukkandan** [comment]
-v is fine if u know what u r doing. -U helps avoid the common mistake of being out of date
