### ISSUE TITLE
How do I specify max resolution)

### ISSUE THREAD

**Issue by HalvorRaknes** [yt-dlp/yt-dlp#2878]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

MY laptop is 9 years old, and often when i attempt to play 1080p videos they become lagged with the video becoming more and more out of sync.

Is there some way I can specify that the best quality video is downloaded but not beyond 720p?

Since I often download many videos from a playlist it is important that no video is skipped because it doesn't offer any specific format.

**Comment by CZeil** [comment]
You could do this by filtering by specifying the following

```-f bv[height<=720]+ba/b[height<=720]```

**Comment by CZeil** [comment]
enclose it in single quotation marks
```
yt-dlp -f 'bv[height<=720]+ba/b[height<=720]'
```

**Comment by ElusiveZatchmo** [comment]
This isn't working for me. I'm putting 
`yt-dlp -f 'bv[height<=1080p]+ba' `
and my videos are downloading in 4K and I'm not sure why :/

**Comment by HalvorRaknes** [comment]
How do I modify  `'bv[height<=480]+ba/b[height<=480]' ` to make it download lowest available resolution if no video satisfies the specifications?

**Comment by pukkandan** [comment]
Replace it with `-S res:480`

**Comment by atomGit** [comment]
> `-f bv[height<=720]+ba/b[height<=720]`

why is an audio format specified if one only wants to limit video resolution? for a video containing an audio track, isn't `-f bv[height<=X]` enough? or `-f bv[height<=X]+ba`?

i also don't understand `ba/b` - why is /b (best) needed?

**Comment by bashonly** [comment]
> why is an audio format specified if one only wants to limit video resolution? 

if you remove the filters, it is `bestvideo+bestaudio/best`, which means: try to select `bestvideo` and `bestaudio` that are separate streams/files and need to be merged (`+`), and if those are not available, then select the `best` video and audio pre-merged in one stream/file

> i also don't understand ba/b - why is /b (best) needed?

`-f bv` will select a video-only format, and if one isn't available, it will raise a "requested format not available" error

`-f bv/b` will fallback to pre-merged video and audio if video-only formats are not available

**Comment by atomGit** [comment]
> if you remove the filters, it is bestvideo+bestaudio/best, which means: try to select bestvideo and bestaudio ...

right, but i was asking why ba (not bv) was specified if one only wants to limit video resolution - for example, if i want 720 resolution video, why would i bother specifying anything having to do with audio (`ba/b[height<=720]')?

**Comment by bashonly** [comment]
`-f bv[height<=720]+ba/b[height<=720]`
the height filter is being applied to `bv` (bestvideo)
if you don't add `+ba`  you'll end up with no audio at all

**Comment by atomGit** [comment]
of course! i suspected i was missing something stupid simple!

thanks
