### ISSUE TITLE
downloading just first few fragments

### ISSUE THREAD

**Issue by fenopa** [yt-dlp/yt-dlp#2879]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

Hi, is it possible to let's say to download only first fragment of a mpd url, or just first few, or just last fragment?
Or make a list of all fragment urls without downloading, just like how it sends such a list to aria2c for example?

**Comment by Lesmiscore** [comment]
If you need only the first fragment of MPD/HLS, you can use `--test`. There's no option for 2 or more for now.

**Comment by pukkandan** [comment]
> Or make a list of all fragment urls without downloading, just like how it sends such a list to aria2c for example?

You can extract that info from `-j`/`--print`. Otherwise, like Lesmiscore said, there is no way to download specific fragments

**Comment by fenopa** [comment]
Thanks for the responses @pukkandan @Lesmiscore --test is very useful indeed, I didn't know that. And -j also satisfies my need of a list of fragment urls. Thanks again.
