### ISSUE TITLE
Add support for filmmodu.org

### ISSUE THREAD

**Issue by rentanadviser** [yt-dlp/yt-dlp#288]
## Checklist

- [x] I'm reporting a new site support request
- [x] I've verified that I'm running yt-dlp version **2021.04.22**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that none of provided URLs violate any copyrights
- [x] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

- https://www.filmmodu.org/avengers-endgame-hd-turkce-dublaj-izle
- https://www.filmmodu.org/avengers-endgame-hd-altyazili-izle

## Description

- Sample page URL https://www.filmmodu.org/traffic-turkce-dublaj-izle
- Extract movie_id form page source e.g. var videoId = '1585'
- Extract videoType form page source e.g. var videoType = 'tr'
- Create m3u8 url like https://www.filmmodu.org/get-source?movie_id=videoId&type=videoType
- final URL should like https://www.filmmodu.org/get-source?movie_id=1585&type=tr

**Comment by pukkandan** [comment]
Cant access the site. Which country is it available in?

**Comment by rentanadviser** [comment]
www is required I think. Please try with www like https://www.filmmodu.org I can access it from TURKIYE

**Comment by pukkandan** [comment]
Related: https://github.com/ytdl-org/youtube-dl/issues/28924
