### ISSUE TITLE
Add Filmarkivet.se as a Supported Site

### ISSUE THREAD

**Issue by NanaMizukiAnother7** [yt-dlp/yt-dlp#2885]
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.02.04**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

United States

### Example URLs

https://www.filmarkivet.se/movies/paris-d-moll/

### Description

Please add Filmarkivet.se as a supported site. I already watched the YouTube video "The Secret Logos Of SF Studios (1919 - 1999)" by CCGFilms, which has some SF Studios logos. I need to capture its logos.

### Verbose log

```shell
[debug] Command-line config: ['-v', 'https://www.filmarkivet.se/movies/paris-d-moll/']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8 (No ANSI), err utf-8 (No ANSI), pref cp1252
[debug] yt-dlp version 2022.02.04 [c1653e9] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-105662-ge534d98af3-20220217 (setts), ffprobe N-105038-g30322ebe3c-sherpya
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [generic] Extracting URL: https://www.filmarkivet.se/movies/paris-d-moll/
[generic] paris-d-moll: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] paris-d-moll: Downloading webpage
WARNING: [generic] URL could be a direct video link, returning it as such.
[debug] Default format spec: bestvideo*+bestaudio/best
[info] paris-d-moll: Downloading 1 format(s): 0
[debug] Invoking downloader on "https://www.filmarkivet.se/movies/paris-d-moll/"
[download] Destination: paris-d-moll [paris-d-moll].unknown_video
[download] 100% of 373.64KiB in 00:01
```

**Comment by Ashish0804** [comment]
Wow didn't know something like this existed...
tack så mycket

**Comment by dirkf** [comment]
The extractor from the PR linked above should be a drop-in here.

The patch (extension had to be added for GH) attached might be applied with `git am`.

[0001-Filmarkivet-Add-extractor-for-Filmarkivet.se.patch.txt](https://github.com/yt-dlp/yt-dlp/files/8146774/0001-Filmarkivet-Add-extractor-for-Filmarkivet.se.patch.txt)

**Comment by NanaMizukiAnother7** [comment]
I compiled this extractor by myself and I got this error!:
```
C:\Users\User>C:\yt-dlp-master\yt-dlp.cmd -o "D:\Filmarkivet.se Videos\%(title)s.mp4" https://www.filmarkivet.se/movies/paris-d-moll/ -v
[debug] Command-line config: ['-o', 'D:\\Filmarkivet.se Videos\\%(title)s.mp4', 'https://www.filmarkivet.se/movies/paris-d-moll/', '-v']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8 (No ANSI), err utf-8 (No ANSI), pref cp1252
[debug] yt-dlp version 2022.04.08 [7884ade65] (source)
[debug] Lazy loading extractors is disabled
[debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
[debug] Python version 3.8.10 (CPython 64bit) - Windows-7-6.1.7601-SP1
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: ffmpeg -bsfs
[debug] exe versions: ffmpeg 2022-04-07-git-607ecc27ed-full_build-www.gyan.dev (setts), ffprobe N-106528-g4fbf3c828b-sherpya
[debug] Optional libraries: sqlite3-2.6.0
[debug] Proxy map: {}
[debug] [Filmarkivet.se] Extracting URL: https://www.filmarkivet.se/movies/paris-d-moll/
[Filmarkivet.se] paris-d-moll: Downloading webpage
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
ERROR: 'NoneType' object has no attribute 'startswith'
Traceback (most recent call last):
  File "C:\yt-dlp-master\yt_dlp\YoutubeDL.py", line 1400, in wrapper
    return func(self, *args, **kwargs)
  File "C:\yt-dlp-master\yt_dlp\YoutubeDL.py", line 1484, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "C:\yt-dlp-master\yt_dlp\YoutubeDL.py", line 1540, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "C:\yt-dlp-master\yt_dlp\YoutubeDL.py", line 2423, in process_video_result
    self._sanitize_thumbnails(info_dict)
  File "C:\yt-dlp-master\yt_dlp\YoutubeDL.py", line 2327, in _sanitize_thumbnails
    t['url'] = sanitize_url(t['url'])
  File "C:\yt-dlp-master\yt_dlp\utils.py", line 717, in sanitize_url
    if url.startswith('//'):
AttributeError: 'NoneType' object has no attribute 'startswith'
```

**Comment by dirkf** [comment]
Plainly something is setting a thumbnail with a `{'url': None}`. The extractor doesn't extract thumbnails explicitly, so it must be the extraction from ld+json or from JWPlayer data. 

yt-dl applies the same test as yt-dlp's `_sanitize_thumbnails()` method, but it doesn't fail there.

This code in the `extract_video_object()` function in yt-dlp's `_json_ld()` method is suspect:
```py
                'thumbnails': [{'url': url_or_none(url)}
                               for url in variadic(traverse_obj(e, 'thumbnailUrl', 'thumbnailURL'))],
```
Instead:
```py
                'thumbnails': [{'url': u} for u in 
                               (url_or_none(url) for url in variadic(traverse_obj(e, 'thumbnailUrl', 'thumbnailURL')))
                               if u is not None],
```
The equivalent (less ambitious) line in yt-dl:
```py
                'thumbnail': url_or_none(e.get('thumbnailUrl') or e.get('thumbnailURL')),
```

**Comment by NanaMizukiAnother7** [comment]
Remove the "patch available" label because it is now supported.
