### ISSUE TITLE
angelstudios.com not finding complete audio

### ISSUE THREAD

**Issue by marcelosomers** [yt-dlp/yt-dlp#2888]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.02.04**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United States

### Description

I'm trying to grab [The Chosen s01e05](https://watch.angelstudios.com/thechosen/watch/episodes/season-1-episode-5-the-wedding-gift). Most of the other episodes are working fine on their site, however this particular link isn't able to get the audio. I end up with an audio file about 90 seconds long, while the video is 56min.

There are many formats available with the `-F` flag, so I am specifically trying to get the `aud-English` format.

Everything works fine in the browser, which tells me the audio is there somewhere, yt-dlp is just not grabbing it properly.

One thing I noticed: the URL it downloads references `The_Chosen_105_CTA_Preroll_v2` - and this episode does start with a 90 second preroll, which is the audio I am able to download. I'm wondering if there's another audio source hidden somewhere that needs to be merged in, but I'm reaching the limits of my knowledge with using the Chrome web inspector to view the sources coming in. I'm able to see individual `.ts` files that are a few seconds long that when individually saved are segments of the complete audio, but I haven't found a way to get them all.

The log does mention a missing fragment, but I don't think a single fragment would account for 55min of missing audio.

Any ideas?

Thanks!

### Verbose log

```shell
~yt-dlp -f aud-English -vU https://watch.angelstudios.com/thechosen/watch/episodes/season-1-episode-5-the-wedding-gift
[debug] Command-line config: ['-f', 'aud-English', '-vU', 'https://watch.angelstudios.com/thechosen/watch/episodes/season-1-episode-5-the-wedding-gift']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.02.04 [c1653e9ef] (zip)
[debug] Python version 3.9.9 (CPython 64bit) - macOS-12.1-arm64-arm-64bit
[debug] exe versions: ffmpeg 4.4.1 (setts), ffprobe 4.4.1
[debug] Optional libraries: sqlite
[debug] Proxy map: {}
Latest version: 2022.02.04, Current version: 2022.02.04
yt-dlp is up to date (2022.02.04)
[debug] [generic] Extracting URL: https://watch.angelstudios.com/thechosen/watch/episodes/season-1-episode-5-the-wedding-gift
[generic] season-1-episode-5-the-wedding-gift: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] season-1-episode-5-the-wedding-gift: Downloading webpage
[generic] season-1-episode-5-the-wedding-gift: Extracting information
[debug] Looking for video embeds
[debug] Identified a JSON LD
[generic] season-1-episode-5-the-wedding-gift: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[info] season-1-episode-5-the-wedding-gift: Downloading 1 format(s): aud-English
[debug] Invoking downloader on "https://video.thechosen.tv/temp/The_Chosen_105_CTA_Preroll_v2/AUDIO-001-English.m3u8"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 430
[download] Destination: The Wedding Gift [season-1-episode-5-the-wedding-gift].mp4
[download] Got server HTTP error: HTTP Error 403: Forbidden. Retrying fragment 430 (attempt 1 of 10) ...
[download] Got server HTTP error: HTTP Error 403: Forbidden. Retrying fragment 430 (attempt 2 of 10) ...
[download] Got server HTTP error: HTTP Error 403: Forbidden. Retrying fragment 430 (attempt 3 of 10) ...
[download] Got server HTTP error: HTTP Error 403: Forbidden. Retrying fragment 430 (attempt 4 of 10) ...
[download] Got server HTTP error: HTTP Error 403: Forbidden. Retrying fragment 430 (attempt 5 of 10) ...
[download] Got server HTTP error: HTTP Error 403: Forbidden. Retrying fragment 430 (attempt 6 of 10) ...
[download] Got server HTTP error: HTTP Error 403: Forbidden. Retrying fragment 430 (attempt 7 of 10) ...
[download] Got server HTTP error: HTTP Error 403: Forbidden. Retrying fragment 430 (attempt 8 of 10) ...
[download] Got server HTTP error: HTTP Error 403: Forbidden. Retrying fragment 430 (attempt 9 of 10) ...
[download] Got server HTTP error: HTTP Error 403: Forbidden. Retrying fragment 430 (attempt 10 of 10) ...
[download] fragment not found; Skipping fragment 430 ...
[download] 100% of 84.59MiB in 03:02
[debug] ffprobe command line: ffprobe -hide_banner -show_format -show_streams -print_format json 'file:The Wedding Gift [season-1-episode-5-the-wedding-gift].mp4'
[FixupM3u8] Fixing MPEG-TS in MP4 container of "The Wedding Gift [season-1-episode-5-the-wedding-gift].mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:The Wedding Gift [season-1-episode-5-the-wedding-gift].mp4' -map 0 -dn -ignore_unknown -c copy -f mp4 -bsf:a aac_adtstoasc -movflags +faststart 'file:The Wedding Gift [season-1-episode-5-the-wedding-gift].temp.mp4'
```

**Comment by pukkandan** [comment]
It is not a supported site. See https://github.com/yt-dlp/yt-dlp/issues/1243

**Comment by roger6106** [comment]
@marcelosomers: Use the URL from [this comment](https://github.com/yt-dlp/yt-dlp/issues/1243#issuecomment-997135454): `https://video.thechosen.tv/The_Chosen_S01E05_muxed-20211201_0eoyMljD.m3u8`

It appears that when they added the preroll, somehow downloading with yt-dlp got broken. That URL is the one without the preroll.

**Comment by BenMcLean** [comment]
> It appears that when they added the preroll, somehow downloading with yt-dlp got broken. That URL is the one without the preroll.

How do I find those URLs for all the season 2 episodes?

**Comment by BenMcLean** [comment]
> @marcelosomers: Use the URL from [this comment](https://github.com/yt-dlp/yt-dlp/issues/1243#issuecomment-997135454): `https://video.thechosen.tv/The_Chosen_S01E05_muxed-20211201_0eoyMljD.m3u8`
> 
> It appears that when they added the preroll, somehow downloading with yt-dlp got broken. That URL is the one without the preroll.

That doesn't seem to fix the issues for season 2.
