### ISSUE TITLE
Playlist name

### ISSUE THREAD

**Issue by s4028600** [yt-dlp/yt-dlp#2892]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

I don't know English so use google translate

Playlist URL
https://www.youtube.com/playlist?list=OLAK5uy_kCsDTcETud3ME2EwOT54_zdlSXdd0v8F4

Output parameters
ydl_opts = {'outtmpl': "%(playlist_title)s/%(title)s %(uploader)s.%(resolution)s.%(ext)s"}

The name of the playlist title displayed by the browser
アンデッドアリス

The name of the folder after download
Undead Alice

**Comment by Jules-A** [comment]
The playlist is displayed in English as Undead Alice in all places of the browser EXCEPT the tab name :/

**Comment by coletdjnz** [comment]
There is no way to get localized title at the moment. The YouTube extractor is enforcing English localization due to extraction issues.

See https://github.com/yt-dlp/yt-dlp/issues/387
