### ISSUE TITLE
[question] --format-sort quality meaning

### ISSUE THREAD

**Issue by pxssy** [yt-dlp/yt-dlp#2894]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

What does quality in `--format-sort quality` mean? 

default option is `--format-sort lang,quality,res,fps,hdr:12,codec:vp9.2,size,br,asr,proto,ext,hasaud,source,id`

res, fps and size are rather concrete and quantitative properties, but since you put quality in pirority, i'd like to know why, and if i should put it in front as well. 

Currently i have quality behind res, fps and size, since these are things i can ensure are exactly what i want.

**Comment by pukkandan** [comment]
It means slightly different things different sites. It is basically a numeric representation of some quality parameter that the website gives.

For youtube, the formats have an associated string like hd720,low etc and quality is the numeric representation of this. So sorting by quality or by resolution is effectively the same for youtube video. Quality is however more important for audio, which is grouped into high, medium, low.

For other sites, it may be the case that only quality is available and not resolution. In this case, it becomes more important. If generally recommend leaving quality as the first option unless you are using limiters (like res:1080)
