### ISSUE TITLE
NYTimesArticleIE unable to extract an embedded video

### ISSUE THREAD

**Issue by fstirlitz** [yt-dlp/yt-dlp#2899]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.02.04**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Description

Sample URL: <https://www.nytimes.com/2022/02/25/world/europe/zelensky-speech-video.html>

The stream endpoints can be found within a quasi-JSON object stuffed into `window.__preloadedData` relatively late in the page HTML. First extract objects within `"initialState"` with `"__typename": "Video"`, then follow the IDs in `"renditions"`. Alternatively, follow the `"url"` to get an URL `NYTimesIE` can process.

### Verbose log

```shell
[debug] Command-line config: ['-vF', 'https://www.nytimes.com/2022/02/25/world/europe/zelensky-speech-video.html']
⋮
-- SNIP --
⋮
[debug] [NYTimesArticle] Extracting URL: https://www.nytimes.com/2022/02/25/world/europe/zelensky-speech-video.html
[NYTimesArticle] zelensky-speech-video: Downloading webpage
ERROR: [NYTimesArticle] zelensky-speech-video: Unable to extract podcast data; please report this issue on  https://github.com/yt-dlp/yt-dlp , filling out the "Broken site" issue template properly. Confirm you are on the latest version using -U; please report this issue on  https://github.com/yt-dlp/yt-dlp , filling out the "Broken site" issue template properly. Confirm you are on the latest version using -U
  File "[REDACTED]/yt-dlp/yt_dlp/extractor/common.py", line 616, in extract
    ie_result = self._real_extract(url)
  File "[REDACTED]/yt-dlp/yt_dlp/extractor/nytimes.py", line 223, in _real_extract
    podcast_data = self._search_regex(
  File "[REDACTED]/yt-dlp/yt_dlp/extractor/common.py", line 1190, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
```

**Comment by dirkf** [comment]
Related, if not the same: https://github.com/ytdl-org/youtube-dl/issues/29447.

**Comment by pukkandan** [comment]
The page has a json/ld with a video object. However, the video URL is in the `id` field, which is not to spec afaik. Related: https://github.com/yt-dlp/yt-dlp/issues/2831
