### ISSUE TITLE
[Site Request]CBS.py add support for Paramountplus movies

### ISSUE THREAD

**Issue by BeeMuffins** [yt-dlp/yt-dlp#290]
## Checklist

- [X] I'm reporting a site feature request
- [X] I've verified that I'm running yt-dlp version **2021.04.22**
- [X] I've searched the bugtracker for similar site feature requests including closed ones

## Description

Paramountplus.com also has movies in addition to TV Shows, the structure of the website is slightly different and the current _VALID_URL regex needs to be updated to account for it.

**Example Movie URL:** https://www.paramountplus.com/movies/million-dollar-american-princesses-meghan-and-harry/C0LpgNwXYeB8txxycdWdR9TjxpJOsdCq/
**Example TV Episode URL:** https://www.paramountplus.com/shows/scorpion/video/669A52D8-99BA-1CC1-4922-D33CBF4CA3C0/scorpion-a-cyclone/

I'm new to regex, but I was able to update the regex to the below which was able to match.

``` _VALID_URL = r'(?:cbs:|https?://(?:www\.)?(?:(?:cbs|paramountplus)\.com/shows/[^/]+/video|paramountplus\.com/movies/[^/]+|colbertlateshow\.com/(?:video|podcasts))/)(?P<id>[\w-]+)'```

Here is a link to regex101 where I was testing the above URLs and the ones from the CBS.py tests
https://regex101.com/r/WWXPGS/1

**Comment by pukkandan** [comment]
I don't have an account to test this on. Have you tested that changing only `_VALID_URL` is sufficient for the downloads to work?

You can try with this:

```
    _VALID_URL = r'''(?x)
        (?:
            cbs:|
            https?://(?:www\.)?
            (?:
                (?:cbs|paramountplus)\.com/(?:shows/[^/]+/video|movies)|
                colbertlateshow\.com/(?:video|podcasts))/
        )(?P<id>[\w-]+)'''
```

**Comment by BeeMuffins** [comment]
Yes, only `_VALID_URL` needed to be updated in my testing for yt-dlp as I ran all test cases in the CBS.py file and a few of the non-DRM movie links to make sure they could all be downloaded.

I used your updated code, but I think it needs to be updated to have ```/[^/]+)``` after movies.  Updated regex tests I did is here https://regex101.com/r/pYpf4Z/1

```
    _VALID_URL = r'''(?x)
        (?:
            cbs:|
            https?://(?:www\.)?(?:
                (?:cbs|paramountplus)\.com/(?:shows/[^/]+/video|movies/[^/]+)/|
                colbertlateshow\.com/(?:video|podcasts)/)
        )(?P<id>[\w-]+)'''
```

May make sense to add an additional test case to the extractor as well for this new URL format:
```
{
        'url': 'https://www.paramountplus.com/movies/million-dollar-american-princesses-meghan-and-harry/C0LpgNwXYeB8txxycdWdR9TjxpJOsdCq/',
        'only_matching': True,
    }
```

**Comment by pukkandan** [comment]
> I used your updated code, but I think it needs to be updated to have /[^/]+) after movies

right, my bad

> May make sense to add an additional test case to the extractor as well for this new URL format:

Will do
