### ISSUE TITLE
Loading Cookies from Opera GX using --cookies-from-browser

### ISSUE THREAD

**Issue by TheBluuDot** [yt-dlp/yt-dlp#2903]
### Checklist

- [X] I'm reporting a feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.02.04**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

The command `--cookies-from-browser` works fine on regular Opera but it does not support Opera GX. Opera GX support only requires a few additions in `cookies.py` to look in `Opera Software\Opera GX Stable` similar to how regular Opera is dealt with. This will allow Opera GX users like me to be able to avoid having to extract cookies manually every time.

**Comment by pukkandan** [comment]
Assuming opera and GX store cookies similarly, You can do `--cookies-from-browser "opera:path/to/gx/profile"`. This allows us to not have to support the different variants of each browser explicitly. Let me know if this works

**Comment by TheBluuDot** [comment]
Oh nice it works. Thanks a lot.

**Comment by ACR-Jeff** [comment]
> Assuming opera and GX store cookies similarly, You can do `--cookies-from-browser "opera:path/to/gx/profile"`. This allows us to not have to support the different variants of each browser explicitly. Let me know if this works

I know this is old but just wanted to say your instructions helped solve my issue with Librewolf with a bit of adjustment
`--cookies-from-browser "Firefox:path/to/.librewolf`
Maybe it will help others out.

**Comment by PrivacyFriendlyMuffins** [comment]
> > Assuming opera and GX store cookies similarly, You can do `--cookies-from-browser "opera:path/to/gx/profile"`. This allows us to not have to support the different variants of each browser explicitly. Let me know if this works
> 
> I know this is old but just wanted to say your instructions helped solve my issue with Librewolf with a bit of adjustment `--cookies-from-browser "Firefox:path/to/.librewolf` Maybe it will help others out.

I believe I'm doing this wrong but I'm not sure how.

I typed into terminal `yt-dlp --cookies-from-browser "Firefox:/home/{username}/.librewolf/"` and it just gave me the standard error message.

&nbsp;

---

- Linux Mint 22.1 Cinnamon

**Comment by gamer191** [comment]
@PrivacyFriendlyMuffins instructions to find Librewolf’s directory can be found at https://github.com/yt-dlp/yt-dlp/issues/12120#issuecomment-2600772236

**Comment by PrivacyFriendlyMuffins** [comment]
Thank you very much!
