### ISSUE TITLE
[Broken] RMCDecouverte - Unsupported URL: https://rmcdecouverte.bfmtv.com

### ISSUE THREAD

**Issue by MantaRayDeeJay** [yt-dlp/yt-dlp#291]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running yt-dlp version **2021.04.22**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] Command-line config: ['-v', '--list-formats', '--batch-file', 'D:\\Informatique\\_Projets\\_Training\\BACH\\Youtube Download\\yt_solo_video.txt']
[debug] Batch file urls: ['https://rmcdecouverte.bfmtv.com/vestiges-de-guerre_22240/les-bunkers-secrets-domaha-beach_25303/']
[debug] Loading archive file None
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] yt-dlp version 2021.04.22 (exe)
[debug] Python version 3.8.9 (CPython 64bit) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg 4.1, ffprobe 4.1
[debug] Proxy map: {}
[generic] les-bunkers-secrets-domaha-beach_25303: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] les-bunkers-secrets-domaha-beach_25303: Downloading webpage
[generic] les-bunkers-secrets-domaha-beach_25303: Extracting information
ERROR: Unsupported URL: https://rmcdecouverte.bfmtv.com/vestiges-de-guerre_22240/les-bunkers-secrets-domaha-beach_25303/
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1059, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1080, in __extract_info
  File "yt_dlp\extractor\common.py", line 558, in extract
  File "yt_dlp\extractor\generic.py", line 3555, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://rmcdecouverte.bfmtv.com/vestiges-de-guerre_22240/les-bunkers-secrets-domaha-beach_25303/
```

## Description

"RMCDecouverte" is well supported in the url list, so I don't understand the error message :
Unsupported URL: https://rmcdecouverte.bfmtv.com

**Comment by MantaRayDeeJay** [comment]
I would like to re-open the ticket, the issue seems not be solved :

yt-dlp
2021.05.11

yt-dlp.exe -v --list-formats --batch-file "D:\Informatique\_Projets\_Training\BACH\Youtube Download\yt_solo_video.txt"

[debug] Command-line config: ['-v', '--list-formats', '--batch-file', 'D:\\Informatique\\_Projets\\_Training\\BACH\\Youtube Download\\yt_solo_video.txt']
[debug] Batch file urls: ['https://rmcdecouverte.bfmtv.com/avions-furtifs-la-technologie-de-lextreme_10598/']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] yt-dlp version 2021.05.11 (exe)
[debug] Python version 3.8.9 (CPython 64bit) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg 4.1, ffprobe 4.1
[debug] Proxy map: {}
[generic] avions-furtifs-la-technologie-de-lextreme_10598: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] avions-furtifs-la-technologie-de-lextreme_10598: Downloading webpage
[generic] avions-furtifs-la-technologie-de-lextreme_10598: Extracting information
ERROR: Unsupported URL: https://rmcdecouverte.bfmtv.com/avions-furtifs-la-technologie-de-lextreme_10598/
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1117, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1138, in __extract_info
  File "yt_dlp\extractor\common.py", line 557, in extract
  File "yt_dlp\extractor\generic.py", line 3560, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://rmcdecouverte.bfmtv.com/avions-furtifs-la-technologie-de-lextreme_10598/

**Comment by MantaRayDeeJay** [comment]
I can't check it because videos are only available for few days only on the server.
Below the 2 links (1st was in the issue and second is the new link I have used to test with the last version which include the bug fixed)
https://rmcdecouverte.bfmtv.com/vestiges-de-guerre_22240/les-bunkers-secrets-domaha-beach_25303/
https://rmcdecouverte.bfmtv.com/avions-furtifs-la-technologie-de-lextreme_10598/

**Comment by MantaRayDeeJay** [comment]
No, I can't do it.
But this is the 2 current case I have ever seen :
- 1st is place is one category
- 2nd can't be classified and is placed in "root"

Can't you update the reg pattern to take in charge any level like this ?
https://rmcdecouverte.bfmtv.com/string_1/optional_string_2/../optional_string_n/

**Comment by pukkandan** [comment]
> No, I can't do it.

?

```
$ yt-dlp https://rmcdecouverte.bfmtv.com/anything/avions-furtifs-la-technologie-de-lextreme_10598
[RMCDecouverte] avions-furtifs-la-technologie-de-lextreme_10598: Downloading webpage
[brightcove:new] 6250253057001: Downloading JSON metadata
[brightcove:new] 6250253057001: Downloading m3u8 information
[brightcove:new] 6250253057001: Downloading m3u8 information
[info] 6250253057001: Downloading format(s) hls-1993-1+hls-audio-2-en__Main_-1
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 315
[download] Destination: AVIONS FURTIFS  - LA TECHNOLOGIE DE [6250253057001].fhls-1993-1.mp4
[download]   6.0% of ~606.31MiB at  1.43MiB/s ETA 13:34
ERROR: Interrupted by user
```
