### ISSUE TITLE
Support for Telegram channels (t.me)

### ISSUE THREAD

**Issue by mikikleist** [yt-dlp/yt-dlp#2910]
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.02.04**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

World

### Example URLs

- Single video: https://t.me/europa_press/613

### Description

Most content in Telegram channels, including videos that aren't too big, can be accessed directly via browser from URLs. So it would be interesting to be able to download them with `yt-dlp`.

It was suggested to use the "context" view, i.e. the URL in this form: https://t.me/s/europa_press/613. However, the `generic` extractor downloads a playlist of several videos, and not the specific video. Moreover, with this method, `yt-dlp` does not retrieve the metadata (there are on Telegram most of the time, including the date of creation of the video).

### Verbose log

```shell
[debug] Command-line config: ['-vU', 'https://t.me/europa_press/613']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.02.04 [c1653e9] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19042-SP0
[debug] exe versions: ffmpeg 2021-09-08-git-5e7e2e5031-full_build-www.gyan.dev (setts), ffprobe 2021-09-08-git-5e7e2e5031-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.02.04, Current version: 2022.02.04
yt-dlp is up to date (2022.02.04)
[debug] [generic] Extracting URL: https://t.me/europa_press/613
[generic] 613: Requesting header
WARNING: [generic] Could not send HEAD request to https://t.me/europa_press/613: HTTP Error 501: Not Implemented
[generic] 613: Downloading webpage
WARNING: [generic] Falling back on generic information extractor.
[generic] 613: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://t.me/europa_press/613
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1381, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1451, in __extract_info
  File "yt_dlp\extractor\common.py", line 612, in extract
  File "yt_dlp\extractor\generic.py", line 3986, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://t.me/europa_press/613
```

**Comment by fosam** [comment]
@hatienl0i261299 Does this work for groups and private groups using cookies?

**Comment by baptx** [comment]
@fosam @hatienl0i261299 Telegram web version does not use cookies but local storage. It also uses a service worker to play the video.
I remember Telegram web version K still had a download button for videos a few days ago but now it is gone. It could have been useful to see how the download button works to try to restore the function manually.
If someone has a solution to download videos for private groups / channels, it would be nice to share.
