### ISSUE TITLE
[patreon] Raise appropriate error when cookies are needed

### ISSUE THREAD

**Issue by NewUserHa** [yt-dlp/yt-dlp#2914]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.02.04**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Description

when yt-dlp a twitter post, but redirected to a link in the post content, and it also found out a issue.

btw I think:
* yt-dlp should NOT follow the link in the post body.
* yt-dlp may should download queued items before next posts page within [PatreonUser] extractor.
* the tip may update from `Confirm you are on the latest version using -U` to `pip install -U` or remove the `-U`
* when without `-v`, the redirection is silent, and the users may still think it's a bug from twitter extractor

### Verbose log

```shell
[debug] Command-line config: ['-v', 'https://twitter.com/vashperado/status/1497602028209520640']
[debug] Encodings: locale cp936, fs utf-8, out utf-8, err utf-8, pref cp936
[debug] yt-dlp version 2022.02.04 [c1653e9ef]
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.17134-SP0
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [twitter] Extracting URL: https://twitter.com/vashperado/status/1497602028209520640
[twitter] 1497602028209520640: Downloading guest token
[twitter] 1497602028209520640: Downloading JSON metadata
[debug] [PatreonUser] Extracting URL: http://patreon.com/vashperado
[PatreonUser] vashperado: Downloading webpage
[download] Downloading playlist: vashperado
[PatreonUser] vashperado: Downloading posts page 1
[PatreonUser] vashperado: Downloading posts page 2
[PatreonUser] vashperado: Downloading posts page 3
[PatreonUser] vashperado: Downloading posts page 4
[PatreonUser] vashperado: Downloading posts page 5
[PatreonUser] vashperado: Downloading posts page 6
[PatreonUser] vashperado: Downloading posts page 7
[PatreonUser] vashperado: Downloading posts page 8
[PatreonUser] vashperado: Downloading posts page 9
[PatreonUser] vashperado: Downloading posts page 10
[PatreonUser] vashperado: Downloading posts page 11
[PatreonUser] vashperado: Downloading posts page 12
[PatreonUser] vashperado: Downloading posts page 13
[PatreonUser] vashperado: Downloading posts page 14
[PatreonUser] vashperado: Downloading posts page 15
[PatreonUser] vashperado: Downloading posts page 16
[PatreonUser] vashperado: Downloading posts page 17
[PatreonUser] vashperado: Downloading posts page 18
[PatreonUser] vashperado: Downloading posts page 19
[PatreonUser] vashperado: Downloading posts page 20
[PatreonUser] vashperado: Downloading posts page 21
[PatreonUser] vashperado: Downloading posts page 22
[PatreonUser] vashperado: Downloading posts page 23
[PatreonUser] vashperado: Downloading posts page 24
[PatreonUser] playlist vashperado: Downloading 480 videos
[download] Downloading video 1 of 480
[debug] [Patreon] Extracting URL: https://www.patreon.com/posts/twi-lek-babes-63123658
[Patreon] 63123658: Downloading JSON metadata
ERROR: 63123658: An extractor error has occurred. (caused by KeyError('post_file')); please report this issue on  https://github.com/yt-dlp/yt-dlp , filling out the "Broken site" issue template properly. Confirm you are on the latest version using -U
Traceback (most recent call last):
  File "c:\program files\python38\lib\site-packages\yt_dlp\extractor\common.py", line 612, in extract
    ie_result = self._real_extract(url)
  File "c:\program files\python38\lib\site-packages\yt_dlp\extractor\patreon.py", line 181, in _real_extract
    post_file = attributes['post_file']
KeyError: 'post_file'
Traceback (most recent call last):
  File "c:\program files\python38\lib\site-packages\yt_dlp\extractor\common.py", line 612, in extract
    ie_result = self._real_extract(url)
  File "c:\program files\python38\lib\site-packages\yt_dlp\extractor\patreon.py", line 181, in _real_extract
    post_file = attributes['post_file']
KeyError: 'post_file'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\program files\python38\lib\site-packages\yt_dlp\YoutubeDL.py", line 1381, in wrapper
    return func(self, *args, **kwargs)
  File "c:\program files\python38\lib\site-packages\yt_dlp\YoutubeDL.py", line 1451, in __extract_info
    ie_result = ie.extract(url)
  File "c:\program files\python38\lib\site-packages\yt_dlp\extractor\common.py", line 642, in extract
    raise ExtractorError('An extractor error has occurred.', cause=e, video_id=self.get_temp_id(url))
yt_dlp.utils.ExtractorError: 63123658: An extractor error has occurred. (caused by KeyError('post_file')); please report this issue on  https://github.com/yt-dlp/yt-dlp , filling out the "Broken site" issue template properly. Confirm you are on the latest version using -U

[download] Downloading video 2 of 480
[debug] [Patreon] Extracting URL: https://www.patreon.com/posts/brig-and-dva-63084773
[Patreon] 63084773: Downloading JSON metadata
ERROR: 63084773: An extractor error has occurred. (caused by KeyError('post_file')); please report this issue on  https://github.com/yt-dlp/yt-dlp , filling out the "Broken site" issue template properly. Confirm you are on the latest version using -U
Traceback (most recent call last):
  File "c:\program files\python38\lib\site-packages\yt_dlp\extractor\common.py", line 612, in extract
    ie_result = self._real_extract(url)
  File "c:\program files\python38\lib\site-packages\yt_dlp\extractor\patreon.py", line 181, in _real_extract
    post_file = attributes['post_file']
KeyError: 'post_file'
Traceback (most recent call last):
  File "c:\program files\python38\lib\site-packages\yt_dlp\extractor\common.py", line 612, in extract
    ie_result = self._real_extract(url)
  File "c:\program files\python38\lib\site-packages\yt_dlp\extractor\patreon.py", line 181, in _real_extract
    post_file = attributes['post_file']
KeyError: 'post_file'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\program files\python38\lib\site-packages\yt_dlp\YoutubeDL.py", line 1381, in wrapper
    return func(self, *args, **kwargs)
  File "c:\program files\python38\lib\site-packages\yt_dlp\YoutubeDL.py", line 1451, in __extract_info
    ie_result = ie.extract(url)
  File "c:\program files\python38\lib\site-packages\yt_dlp\extractor\common.py", line 642, in extract
    raise ExtractorError('An extractor error has occurred.', cause=e, video_id=self.get_temp_id(url))
yt_dlp.utils.ExtractorError: 63084773: An extractor error has occurred. (caused by KeyError('post_file')); please report this issue on  https://github.com/yt-dlp/yt-dlp , filling out the "Broken site" issue template properly. Confirm you are on the latest version using -U

ERROR: Interrupted by user
```

**Comment by pukkandan** [comment]
Not quite on topic, but I'll answer these anyway

> yt-dlp should NOT follow the link in the post body.

yt-dlp tries it's hardest to find some video in the URL you pass. Since the tweet has no embedded video, it looks for URLs. This is necessary to catch say, youtube embeds in tweets.

> yt-dlp may should download queued items before next posts page within [PatreonUser] extractor.

You can open a feature request. This is something I have considered, but is a bit tricky to implement

> the tip may update from Confirm you are on the latest version using -U to pip install -U or remove the -U

The tip is correct. Running `yt-dlp -U` will tell you whether you are on the latest version and how to update if not

> when without -v, the redirection is silent, and the users may still think it's a bug from twitter extractor

wdym?

```
❯ yt-dlp https://twitter.com/vashperado/status/1497602028209520640
[twitter] 1497602028209520640: Downloading guest token
[twitter] 1497602028209520640: Downloading JSON metadata
[PatreonUser] vashperado: Downloading webpage
[download] Downloading playlist: vashperado
[PatreonUser] vashperado: Downloading posts page 1
...
```

**Comment by pukkandan** [comment]
As for the actual issue, pass cookies if you have access to the patron post

**Comment by NewUserHa** [comment]
> yt-dlp tries it's hardest to find some video in the URL you pass. Since the tweet has no embedded video, it looks for URLs. This is necessary to catch say, youtube embeds in tweets.

if the embeded link is a single page, then the user probably wants that page. But if it is a home page, then because it will download a bunch of things so probably not.

> You can open a feature request. This is something I have considered, but is a bit tricky to implement

not sure if it's necessary because users will get all things after all, so maybe it's not an issue for real users.

>The tip is correct. Running yt-dlp -U will tell you whether you are on the latest version and how to update if not

maybe complete it as `Confirm you are on the latest version using yt-dlp -U`?

> wdym

never mind

> As for the actual issue, pass cookies if you have access to the patron post. If you don't have access, yt-dlp can't download it

I don't have that cookies.
maybe throw `probably need cookies` error instead of `KeyError('post_file')`?

**Comment by pukkandan** [comment]
> maybe throw probably need cookies error instead of KeyError('post_file')? don't know if it is because of cookies.

I don't know either and only someone with access to the content can check

**Comment by NewUserHa** [comment]
> if the embeded link is a single page, then the user probably wants that page. But if it is a home page, then because it will download a bunch of things so probably not.

maybe a new issue or even a PR that checks if the embedded url has a `path` part?

**Comment by pukkandan** [comment]
As far as yt-dlp is concerned, http://patreon.com/vashperado is a playlist. Like I said above, yt-dlp tries its best to find videos in the link you give. It does not make sense to not extract the page when it is possible to do so. If there is no video (that you are interested in) in a link, just dont run yt-dlp on it

**Comment by NewUserHa** [comment]
ok. that seems to make sense
