### ISSUE TITLE
Extract audio and keep the video file, but nothing else

### ISSUE THREAD

**Issue by mkhoshbin1** [yt-dlp/yt-dlp#2916]
### Checklist

- [X] I'm reporting a feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.02.04**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

I'd like to download a video (A.mkv) and extract its audio as a separate file (A.opus).

The -x option extracts the audio and gives me a clean audio file, but the final video (A.mkv) is deleted.

So I have to use the -k option to keep the intermediate video. This gives me the final audio and audio+video versions (A.mkv and A.opus), but also gives me all of the intermediate files which include a number of audio and video files that have been used to create the previous files. Also, the cover art and subtitles are preserved.

Would it be possible to have a parameter for downloading the video and extracting the audio from it and keeping ONLY these two?

**Comment by pukkandan** [comment]
You could do `-x -k --exec "del %(requested_formats.:.filepath)#q"`

(On UNIX, change `del` to `rm`)

> Also, the cover art and subtitles are preserved.

That is because of other options in your config, not `-k`

**Comment by mkhoshbin1** [comment]
@pukkandan 
Thanks!
I looked again and you are right! Unfortunately, I couldn't get the exec command to work and will be using a separate command to convert using ffmpeg.
