### ISSUE TITLE
Metadata for offline streams cannot be acquired

### ISSUE THREAD

**Issue by Metritutus** [yt-dlp/yt-dlp#2919]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.02.04**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

If `yt-dlp` is pointed at an offline stream, it seems unable to acquire the metadata of the video.

Example: `yt-dlp https://www.youtube.com/watch?v=45OF5RZxFqY --write-info-json`

I've also tried it with `--dump-json`, and also other arguments such as `--write-description`, none of which had any apparent effect.

The only error it presents is: `ERROR: [youtube] 45OF5RZxFqY: This live event will begin in a few moments.`

The message is the same whether the event is scheduled (like the above link, despite being in the past) or simply 'Live stream offline'.

I presume this information is supposed to be accessible even if the video stream is not, as there are fields in the documentation such as `live_status`, implying that you can acquire metadata on livestreams even if they are not currently live.

### Verbose log

```shell
[debug] Command-line config: ['https://www.youtube.com/watch?v=45OF5RZxFqY', '--write-info-json', '-vU']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8 (No ANSI), err utf-8 (No ANSI), pref cp1252
[debug] yt-dlp version 2022.02.04 [c1653e9] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-8.1-6.3.9600-SP0
[debug] exe versions: ffmpeg 5.0-full_build-www.gyan.dev (setts), ffprobe 5.0-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.02.04, Current version: 2022.02.04
yt-dlp is up to date (2022.02.04)
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=45OF5RZxFqY
[youtube] 45OF5RZxFqY: Downloading webpage
[youtube] 45OF5RZxFqY: Downloading android player API JSON
ERROR: [youtube] 45OF5RZxFqY: This live event will begin in a few moments.
  File "yt_dlp\extractor\common.py", line 612, in extract
  File "yt_dlp\extractor\youtube.py", line 3246, in _real_extract
  File "yt_dlp\extractor\common.py", line 1120, in raise_no_formats
```

**Comment by coletdjnz** [comment]
`--ignore-no-formats-error`

**Comment by Metritutus** [comment]
> `--ignore-no-formats-error`

That works!  I hadn't realised that no formats was the real error.  Cheers!
