### ISSUE TITLE
[youtube] Age-Gate for video - Invidious-implemented bypass required?

### ISSUE THREAD

**Issue by tr13dm03** [yt-dlp/yt-dlp#2923]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.02.04**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

yt-dlp fails to extract the video at https://www.youtube.com/watch?v=dIZ-e4WwJ5w while [Invidious manages it](https://invidious.snopyta.org/watch?v=dIZ-e4WwJ5w).

Is whatever bypass Invidious uses applicable to the yt-dlp code-base?

### Verbose log

```shell
[debug] Command-line config: ['-vU', '-i', '--rm-cache-dir', 'https://www.youtube.com/watch?v=dIZ-e4WwJ5w']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.02.04 [c1653e9ef] (source)
[debug] Lazy loading extractors is disabled
[debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
[debug] Git HEAD: 7c219ea60
[debug] Python version 3.9.2 (CPython 64bit) - Linux-5.10
[debug] exe versions: ffmpeg 4.3.3-0, ffprobe 4.3.3-0
[debug] Optional libraries: Cryptodome, sqlite
[debug] Proxy map: {}
Removing cache dir /home/user/.cache/yt-dlp ..
Latest version: 2022.02.04, Current version: 2022.02.04
yt-dlp is up to date (2022.02.04)
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=dIZ-e4WwJ5w
[youtube] dIZ-e4WwJ5w: Downloading webpage
[youtube] dIZ-e4WwJ5w: Downloading android player API JSON
[youtube] dIZ-e4WwJ5w: Downloading android agegate player API JSON
[youtube] dIZ-e4WwJ5w: Downloading web agegate player API JSON
ERROR: [youtube] dIZ-e4WwJ5w: Sign in to confirm your age. This video may be inappropriate for some users.
  File "/home/user/yt-dlp/yt_dlp/extractor/common.py", line 616, in extract
    ie_result = self._real_extract(url)
  File "/home/user/yt-dlp/yt_dlp/extractor/youtube.py", line 3248, in _real_extract
    self.raise_no_formats(reason, expected=True)
  File "/home/user/yt-dlp/yt_dlp/extractor/common.py", line 1124, in raise_no_formats
    raise ExtractorError(msg, expected=expected, video_id=video_id)
```

**Comment by deepesh-agarwal** [comment]
@pukkandan So reverting back the commit should solve the issue?

**Comment by pukkandan** [comment]
That commit was made because some other videos like `HtVdAasjOgU` was failing without it. But now it is working again 🤷. So reverting it should fix the issue
