### ISSUE TITLE
[Instagram]

### ISSUE THREAD

**Issue by ruizlenato** [yt-dlp/yt-dlp#2927]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

Is it possible to download one more video from an Instagram post?

When I put the link yt-dlp always downloads the first video.

**Comment by pukkandan** [comment]
> - [X] I'm asking a question and **not** reporting a bug/feature request

You have not given any data for us to go on. Do not abuse the "Question" template to post incomplete issues/feature requests. Open a new issue, properly filling out the "broken site" issue form
