### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by Sipherdrakon** [yt-dlp/yt-dlp#293]
## Checklist

- [X] I'm reporting a feature request
- [X] I've verified that I'm running yt-dlp version **2021.04.22**
- [X] I've searched the bugtracker for similar feature requests including closed ones

## Description

I was curious if there was a way to add Sling-TV to the list of APOs. There are a few sites that allow login to view content with Sling and didn't see an option within the ap-list-mso.

**Comment by pukkandan** [comment]
This is not a feature request. Open a site-support request with the necessary details
