### ISSUE TITLE
live.nicovideo.jp does not work

### ISSUE THREAD

**Issue by EnderShadow** [yt-dlp/yt-dlp#2931]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.02.04**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United States

### Description

Supposedly the program works on nicovideo.jp, but apparently not on live.nicovideo.jp. While the livestream is a member's only thing, the first few minutes are viewable without an account. I do have an account if that's needed for testing though. I want to be able to download the live stream, so I'm open to workarounds as well.

### Verbose log

```shell
[debug] Command-line config: ['-vU', 'https://live.nicovideo.jp/watch/lv335845784']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.02.04 [c1653e9ef]
[debug] Python version 3.10.2 (CPython 64bit) - Linux-5.16.8-zen1-1-zen-x86_64-with-glibc2.33
[debug] exe versions: ffmpeg 4.4.1 (setts), ffprobe 4.4.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome, secretstorage, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.02.04, Current version: 2022.02.04
yt-dlp is up to date (2022.02.04)
[debug] [generic] Extracting URL: https://live.nicovideo.jp/watch/lv335845784
[generic] lv335845784: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] lv335845784: Downloading webpage
[generic] lv335845784: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://live.nicovideo.jp/watch/lv335845784
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1381, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1451, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 612, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.10/site-packages/yt_dlp/extractor/generic.py", line 3986, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://live.nicovideo.jp/watch/lv335845784
```

**Comment by pukkandan** [comment]
Related: #367

**Comment by EnderShadow** [comment]
#367 was completed and it seems to work now
