### ISSUE TITLE
--print 

### ISSUE THREAD

**Issue by tjsnowfun** [yt-dlp/yt-dlp#2932]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

cmd：yt_dlp.exe  url  --print %(formats)j

How can I shorten and simplify the "formats" content to exclude the content I don't want?

formats:[
    { a:1, 
      b:2, 
      c:3, 
     d:4
   } ,
   { a:1, 
      b:2, 
      c:3, 
     d:4
   } 
]

to

formats:[
    { a:1, 
      b:2
    } ,
   {  a:1, 
      b:2
   } 
]

**Comment by pukkandan** [comment]
There is no way to do that without using external tools

**Comment by tjsnowfun** [comment]
1
