### ISSUE TITLE
new site request sproutvideo

### ISSUE THREAD

**Issue by suprapoke** [yt-dlp/yt-dlp#2933]
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.02.04**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Example URLs

https://videos.sproutvideo.com/embed/069edcb31e1be0c08f/767e75aa22ae215d

### Description

linked over from paid patreon page

### Verbose log

```shell
e@android:/media/e/6TBnew1/dwhelper$ yt-dlp https://maxxed3.vids.io/videos/069edcb31e1be0c08f/p-59-special-new-shein-dress-haul-1-mp4 --referer https://www.patreon.com/posts/51431435 --cookies cookies.txt --verbose
[debug] Command-line config: ['https://maxxed3.vids.io/videos/069edcb31e1be0c08f/p-59-special-new-shein-dress-haul-1-mp4', '--referer', 'https://www.patreon.com/posts/51431435', '--cookies', 'cookies.txt', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.02.04 [c1653e9ef]
[debug] Lazy loading extractors is disabled
[debug] Python version 3.8.10 (CPython 64bit) - Linux-5.9.16-050916-generic-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4, rtmpdump 2.4
[debug] Optional libraries: Cryptodome, secretstorage, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [generic] Extracting URL: https://maxxed3.vids.io/videos/069edcb31e1be0c08f/p-59-special-new-shein-dress-haul-1-mp4
[generic] p-59-special-new-shein-dress-haul-1-mp4: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] p-59-special-new-shein-dress-haul-1-mp4: Downloading webpage
[generic] p-59-special-new-shein-dress-haul-1-mp4: Extracting information
[debug] Looking for video embeds
[debug] Identified a twitter:player iframe
[debug] [generic] Extracting URL: https://videos.sproutvideo.com/embed/069edcb31e1be0c08f/767e75aa22ae215d
[generic] 767e75aa22ae215d: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] 767e75aa22ae215d: Downloading webpage
[generic] 767e75aa22ae215d: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://videos.sproutvideo.com/embed/069edcb31e1be0c08f/767e75aa22ae215d
Traceback (most recent call last):
  File "/home/e/.local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 1381, in wrapper
    return func(self, *args, **kwargs)
  File "/home/e/.local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 1451, in __extract_info
    ie_result = ie.extract(url)
  File "/home/e/.local/lib/python3.8/site-packages/yt_dlp/extractor/common.py", line 616, in extract
    ie_result = self._real_extract(url)
  File "/home/e/.local/lib/python3.8/site-packages/yt_dlp/extractor/generic.py", line 3978, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://videos.sproutvideo.com/embed/069edcb31e1be0c08f/767e75aa22ae215d
```

**Comment by sideloading** [comment]
I used the following PR a while ago and it worked. Potentially implemented for yt-dlp? 

https://github.com/ytdl-org/youtube-dl/pull/27685

**Comment by sideloading** [comment]
@suprapoke 

1. `git clone --single-branch --branch sproutvideo https://github.com/TheZ3ro/youtube-dl-1.git`
2. navigate into the cloned folder
3. run `python -m youtube_dl https://videos.sproutvideo.com/embed/XYZ/XYZ`

**Comment by sideloading** [comment]
hi @suprapoke, yeah, same error I was getting too. I think the PR has some issues, but the testing run works so I'm not sure. 

You could try Jdownloader for the timebeing, but seems you are using android currently?

**Comment by suprapoke** [comment]
@sideloading hi, what is the "testing run"?  if there is a test version that works, I will give it a try, thx

**Comment by sideloading** [comment]
@suprapoke it's test-run code, not a 'working' version or whatever. Check the PR I referenced in my very first reply if you want to learn more about it.

**Comment by J0s3f** [comment]
The code works at least for links which don't need a password or special referer, so adding it would be great. It's not 100%, but it can download a lot of videos!

**Comment by ro0mquy** [comment]
I cloned @J0s3f's branch and used it as described by @sideloading. At first I struggled with 403 errors when downlaoding the stream's .key file. But then `pip install pycryptodomex` solved that problem. I had to set a `--referer` header. (Homebrew installation on macOS.)

**Comment by cimenta** [comment]
> I tried to adapt the youtube-dl pull request to yt-dlp. Here is the result: [master...J0s3f:yt-dlp:sproutvideo-yt-dlp](https://github.com/yt-dlp/yt-dlp/compare/master...J0s3f:yt-dlp:sproutvideo-yt-dlp)
> 

Can I use your code on Windows?

**Comment by david-littlefield** [comment]
I got it to work. 

### commands:
git clone --single-branch --branch sproutvideo https://github.com/TheZ3ro/youtube-dl-1.git
pip install pycryptodome
cd youtube-dl-1
python -m youtube_dl --referer "[referer-url]" --add-header "User Agent: [user-agent]" "[sprout-url]"

### instructions:
**[referer-url]**
this is the regular url of the website where your video is embedded

_example:_
_https://www.patreon.com/posts/38381291_

**[user-agent]**
this is a description of the type of computer accessing the website

1. open "developer tools" in chrome ( command + option + I )
2. click "network" tab
3. clear network log ( command + k )
4. play video
5. click video-related resource from list of resources ( mine was ts file )
6. scroll down to "request headers" section
7. copy and paste "user-agent" value into [user-agent] part of command

_example:_
_Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36_

**[sprout-url]**
this is the actual url of the embedded sprout video

1. copy and paste "referer" value into [sprout-url] part of command

_example:_
_https://videos.sproutvideo.com/embed/d39ed4ab1415e7s23b/661f827f6gdfb9e7?playerColor=2f3437&playerTheme=dark&type=hd_

<img width="1026" alt="Screenshot 2023-12-19 at 11 27 51 PM" src="https://github.com/yt-dlp/yt-dlp/assets/30560737/a9c632bf-4ff9-44cc-ba6e-a978b180386d">

**Comment by muhamed-didovic** [comment]
@david-littlefield thanks, it still works :)

**Comment by ehdjs1203** [comment]
What am I doing wrong?

I have installed the lasted version of yt-dlp and still getting an error

I did 
yt-dlp --referer "referer-url" --user-agent "user-agent"  https://videos.sproutvideo.com/embed/.../OOO

[generic] Extracting URL: https://videos.sproutvideo.com/embed/.../OOO
[generic] OOO: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] ...: Extracting information
ERROR: Unsupported URL: https://videos.sproutvideo.com/embed/.../OOO
