### ISSUE TITLE
new site support request - aha.video

### ISSUE THREAD

**Issue by chennaimov** [yt-dlp/yt-dlp#2934]
### Checklist

- [X] I'm reporting a site feature request
- [X] I've verified that I'm running yt-dlp version **2022.02.04**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

India

### Example URLs

https://www.aha.video/player/movie/lucky-man

### Description

This is one of my favourite website. It would be great if you can add it in your supported site list.

### Verbose log

```shell
yt-dlp.exe --cookies /aha.video_cookies.txt https://www.aha.video/player
/movie/lucky-man -v
[debug] Command-line config: ['--cookies', '/aha.video_cookies.txt', 'https://ww
w.aha.video/player/movie/lucky-man', '-v']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8 (No ANSI), err utf-8 (No A
NSI), pref cp1252
[debug] yt-dlp version 2022.02.04 [c1653e9] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg 4.4.1-essentials_build-www.gyan.dev (setts), ffprob
e 4.4.1-essentials_build-www.gyan.dev
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [generic] Extracting URL: https://www.aha.video/player/movie/lucky-man
[generic] lucky-man: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] lucky-man: Downloading webpage
[generic] lucky-man: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://www.aha.video/player/movie/lucky-man
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1381, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1451, in __extract_info
  File "yt_dlp\extractor\common.py", line 612, in extract
  File "yt_dlp\extractor\generic.py", line 3986, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.aha.video/player/mov
ie/lucky-man

Traceback (most recent call last):
  File "yt_dlp\__main__.py", line 19, in <module>
  File "yt_dlp\__init__.py", line 857, in main
  File "yt_dlp\__init__.py", line 850, in _real_main
  File "yt_dlp\YoutubeDL.py", line 838, in __exit__
  File "yt_dlp\utils.py", line 1541, in save
PermissionError: [Errno 13] Permission denied: '/aha.video_cookies.txt'
[2808] Failed to execute script '__main__' due to unhandled exception!
```

**Comment by chennaimov** [comment]
@pukkandan Do let me know if you need an account. I can help.

**Comment by m4tu4g** [comment]
aha.video provides only DRMed content, which yt-dlp wont support

**Comment by pukkandan** [comment]
@m4tu4g Are you saying that the formats that plays by default is DRM protected? Or have you checked on a DRM disabled browser (you can disable it in firefox)?

**Comment by m4tu4g** [comment]
> @m4tu4g Are you saying that the formats that plays by default is DRM protected? Or have you checked on a DRM disabled browser (you can disable it in firefox)?

Incase if we disable DRM browser module, site responds that DRM is not supported by browser and won't play any content.

**Comment by pukkandan** [comment]
thanks for the info

**Comment by kamaravichow** [comment]
is there any possibility to add this ?
