### ISSUE TITLE
Suppress messages

### ISSUE THREAD

**Issue by khk58** [yt-dlp/yt-dlp#2948]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

Is it possible to suppress the following message 
'Video unavailable. This video is no longer available because the YouTube account associated with this video has been terminated.'
when downloading playlists?

**Comment by pukkandan** [comment]
No. error messages (unlike warnings) cannot be suppressed. You can redirect the entire stderr if you want
