### ISSUE TITLE
Negative playlist indices offset from a playlist's end

### ISSUE THREAD

**Issue by Alzarath** [yt-dlp/yt-dlp#2951]
### Checklist

- [X] I'm reporting a feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.02.04**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

# Use Case

I hoped to use the playlist options to download an entire channel offset from the 10th video uploaded to the most recent. Current behavior for downloading a channel is to download all of the videos from the most recent to the oldest. I could get around this by using `--playlist-reverse`. But to start from the 10th video, I would have to calculate where that is at the end of the playlist from the latest video, which would generally be `# of videos - starting index` and set that to `--playlist-end`.

# Suggestion

It would be intuitive and convenient if we could instead use a negative value to fetch the value offset from the end of a playlist. e.g. `--playlist-end=-10` would give me the 10th video from the end of the playlist.

**Comment by pukkandan** [comment]
Already working on it: https://github.com/yt-dlp/yt-dlp/pull/2853
