### ISSUE TITLE
Quick way to get the underlying download dependency url / manifest

### ISSUE THREAD

**Issue by boulderob** [yt-dlp/yt-dlp#2953]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

I've been running into a situation where segmented subtitle download is inconsistent / regularly broken.  I'm seeing it on the site I include below but I've seen it with others at times as well.  

The subtitles always work in the live site player but when yt-dlp tries to download them the downloads sometime randomly "choke" and never complete (presumably because yt-dlp subtitle processing hit a segment it can't process (see error message))

Is there a way for me to easily make yt-dlp "spit out" what the subtitle target manifest + stream url and or in the case of pure file simple url that it is trying to download so that I can "play with it" directly?  If I can work with the streams directly and more easily I might be able to figure out what's going on or just manually assemble the broken files if and when it happens.

Hunting down the manifest stream urls in the browser devtools every time I switch back and forth between videos that work and those that don't isn't productive especially if there's a quicker way to immediately get the info from the yt-dlp cli.  

I want to say I've seen this type of functionality before for the video streams, which I'd also be interested in, but I can't find it anymore. 

A perfect example follows.  The subtitle worked perfectly one time (downloaded file to completion) but when I deleted the subtitle file to do another test to paste here the same download fails???  

The inconsistencies are frustrating. 

```bash
yt-dlp--write-sub --skip-download https://www.rts.ch/play/tv/scenes-de-menages/video/60?urn=urn:rts:video:12887975
[SRGSSR] 12887975: Downloading JSON metadata
[SRGSSR] 12887975: Downloading m3u8 information
[info] 12887975: Downloading 1 format(s): HLS-H264-HD-6130+HLS-H264-HD-audio0-Français
[info] Writing video subtitles to: 60 [12887975].fr.vtt
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 241
[download] Destination: 60 [12887975].fr.vtt
[download] 60 [12887975].fr.vtt.part-Frag24 has already been downloaded
[download]  10.0% of ~31.86KiB at 34.57KiB/s ETA Unknown (frag 24/241)ERROR: Unable to download video subtitles for 'fr': 'utf-8' codec can't decode bytes in position 1-2: invalid continuation byte
```

A more complete dump is included in the verbose log i sent you.

Also the download of subtitle segmented files can be painfully slow compared to segmented video for some reason.   A subtitle file download that is only 44K (that's a K!) akes literally a minute (and sometimes more)?

Thanks 

### Verbose log

```shell
yt-dlp -vU --write-sub --skip-download https://www.rts.ch/play/tv/scenes-de-menages/video/60?urn=urn:r>
[debug] Command-line config: ['-vU', '--write-sub', '--skip-download', 'https://www.rts.ch/play/tv/scenes-de-menages/video/60?urn=urn:rts:video:12887975']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.01.21 [f20d607b0] (source)
[debug] Lazy loading extractors is disabled
[debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
[debug] Git HEAD: 2974f3d5a
[debug] Python version 3.9.7 (CPython 64bit) - macOS-11.2.3-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.4.1 (setts), ffprobe 4.4.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome, sqlite
[debug] Proxy map: {}
Latest version: 2022.02.04, Current version: 2022.01.21
ERROR: You cannot update when running from source code; Use git to pull the latest changes
[debug] [SRGSSRPlay] Extracting URL: https://www.rts.ch/play/tv/scenes-de-menages/video/60?urn=urn:rts:video:12887975
[debug] [SRGSSR] Extracting URL: srgssr:rts:video:12887975
[SRGSSR] 12887975: Downloading JSON metadata
[SRGSSR] 12887975: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Downloading subtitles: fr
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 12887975: Downloading 1 format(s): HLS-H264-HD-6130+HLS-H264-HD-audio0-Français
[info] Writing video subtitles to: 60 [12887975].fr.vtt
[debug] Invoking downloader on "https://rts-vod-amd.akamaized.net/ch/12887975/ca224022-ee55-3548-92bd-c75de44ddb55/index-f6.m3u8?aka_me_session_id=AAAAAAAAAAAmtiNiAAAAAApULMIDOoowtYL3veg1v7U4G+s6u9LtZ49QjLBSJ+2c75E3GEOs6QVBRAew3YpV8z4IAT6SU8mr&aka_media_format_type=hls"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 241
[download] Destination: 60 [12887975].fr.vtt
[download]  73.0% of ~54.79KiB at  3.36KiB/s ETA 00:05 (frag 176/241)ERROR: Unable to download video subtitles for 'fr': 'utf-8' codec can't decode byte 0x93 in position 2: invalid start byte
Traceback (most recent call last):
  File "/Users/mbpme/bin/ytd2/yt_dlp/YoutubeDL.py", line 3822, in _write_subtitles
    self.dl(sub_filename, sub_copy, subtitle=True)
  File "/Users/mbpme/bin/ytd2/yt_dlp/YoutubeDL.py", line 2798, in dl
    return fd.download(name, new_info, subtitle)
  File "/Users/mbpme/bin/ytd2/yt_dlp/downloader/common.py", line 440, in download
    ret = self.real_download(filename, info_dict)
  File "/Users/mbpme/bin/ytd2/yt_dlp/downloader/hls.py", line 355, in real_download
    self.download_and_append_fragments(
  File "/Users/mbpme/bin/ytd2/yt_dlp/downloader/fragment.py", line 516, in download_and_append_fragments
    result = append_fragment(decrypt_fragment(fragment, frag_content), frag_index, ctx)
  File "/Users/mbpme/bin/ytd2/yt_dlp/downloader/fragment.py", line 487, in append_fragment
    self._append_fragment(ctx, pack_func(frag_content, frag_index))
  File "/Users/mbpme/bin/ytd2/yt_dlp/downloader/hls.py", line 270, in pack_fragment
    for block in webvtt.parse_fragment(frag_content):
  File "/Users/mbpme/bin/ytd2/yt_dlp/webvtt.py", line 362, in parse_fragment
    parser = _MatchParser(frag_content.decode('utf-8'))
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x93 in position 2: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mbpme/bin/ytd2/yt_dlp/YoutubeDL.py", line 1374, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/mbpme/bin/ytd2/yt_dlp/YoutubeDL.py", line 1458, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/Users/mbpme/bin/ytd2/yt_dlp/YoutubeDL.py", line 1510, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/Users/mbpme/bin/ytd2/yt_dlp/YoutubeDL.py", line 2604, in process_video_result
    self.process_info(new_info)
  File "/Users/mbpme/bin/ytd2/yt_dlp/YoutubeDL.py", line 2849, in process_info
    sub_files = self._write_subtitles(info_dict, temp_filename)
  File "/Users/mbpme/bin/ytd2/yt_dlp/YoutubeDL.py", line 3827, in _write_subtitles
    raise DownloadError(f'Unable to download video subtitles for {sub_lang!r}: {err}', err)
yt_dlp.utils.DownloadError: Unable to download video subtitles for 'fr': 'utf-8' codec can't decode byte 0x93 in position 2: invalid start byte
```

**Comment by boulderob** [comment]
I just ran the same command but without the `vU` and it worked!

```bash
ytd12 --write-sub --skip-download https://www.rts.ch/play/tv/scenes-de-menages/video/60?urn=urn:rts:video:12887975
[SRGSSR] 12887975: Downloading JSON metadata
[SRGSSR] 12887975: Downloading m3u8 information
[info] 12887975: Downloading 1 format(s): HLS-H264-HD-6130+HLS-H264-HD-audio0-Français
[info] Writing video subtitles to: 60 [12887975].fr.vtt
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 241
[download] Destination: 60 [12887975].fr.vtt
[download] 100% of 38.09KiB in 00:32
```

huh?  

It took 32 secs to download 38K?

Speedtest says i'm at 30Mbps?

**Comment by pukkandan** [comment]
If you can attach the fragment where this is failing, we can check what is going on

As for your actual question, all the info is present inside the info-dict which you can see by using either `-j` or `--write-info-json`. Once you figure out where exactly the data you want is, you can also use `--print` to print just that URL.

Eg: `--print %(subtitles.fr.0.manifest_url)s` (my guess based on your logs; untested)

**Comment by pukkandan** [comment]
> It took 32 secs to download 38K?

fragmented downloads are slow when single threaded. Try using `-N 8`

**Comment by boulderob** [comment]
@pukkandan see what i just wrote.  The subtitles just downloaded fine.  Sometimes they work and sometimes they don't.

I'll look into your other suggestions.  

I though there was an even a simpler command than grokking the json (at least for vid streams).

But if the videos are segmented as well, why do they download much faster then the subtitles?

**Comment by boulderob** [comment]
Is there any way to get around the throttling?   By altering the way yt-dlp is downloading with cli options or wrapping it with a wrapper script that does similar?  

Like I said the video downloads much faster generally.   Oddly enough I really want the subtitles more than the video!  It's for learning languages!  But I have more problems with the subtitles on all of my streams.

**Comment by pukkandan** [comment]
>  The subtitles just downloaded fine. Sometimes they work and sometimes they don't.

You can give us the left over fragment file if/when it fails again

> I though there was an even a simpler command than grokking the json (at least for vid streams).

> Is there any way to get around the throttling? By altering the way yt-dlp is downloading with cli options or wrapping it with a wrapper script that does similar?

Read my comments again

**Comment by boulderob** [comment]
Thanks for info @pukkandan.  Been busy here and haven't had time to get back to you on this.
