### ISSUE TITLE
Issue with Youtube auto subtitle

### ISSUE THREAD

**Issue by saood06** [yt-dlp/yt-dlp#2956]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.02.04**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Description

The auto subtitles from youtube no longer work properly. Looking at the generated vtt and then converted ass subtitles the script is fully pulled, but it places the full script within the first few seconds (<5) in the subtitle files. This used to not happen, and does not seem to be caused by a change in yt-dlp since the behaviour changed without a change in yt-dlp. I have also tested and it does not seem to be a one off issue with this video, it seems to happen on all videos (only on auto generated subtitles not traditional subtitles).

### Verbose log

```shell
[debug] Command-line config: ['-vU', '-i', '--convert-subs', 'ass', '--merge-output-format', 'mkv', '--embed-chapters', '--video-multistreams', '--audio-multistreams', '--embed-subs', '--write-auto-subs', '--write-subs', '--compat-options', 'no-keep-subs', '--sponsorblock-mark', 'all', '--no-check-certificate', 'https://www.youtube.com/watch?v=k00UASRvAiw']
[debug] Encodings: locale cp1252, fs utf-8, out cp1252 (No ANSI), err cp1252 (No ANSI), pref cp1252
[debug] yt-dlp version 2022.02.04 [c1653e9] (win_exe)
[debug] Compatibility options: no-keep-subs
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg 4.2.3, ffprobe 4.4-essentials_build-www.gyan.dev
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.02.04, Current version: 2022.02.04
yt-dlp is up to date (2022.02.04)
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=k00UASRvAiw
[youtube] k00UASRvAiw: Downloading webpage
[youtube] k00UASRvAiw: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[debug] Downloading subtitles: en
[SponsorBlock] Fetching SponsorBlock segments
[debug] SponsorBlock query: https://sponsor.ajay.app/api/skipSegments/3e51?service=YouTube&categories=%5B%22selfpromo%22%2C+%22outro%22%2C+%22poi_highlight%22%2C+%22preview%22%2C+%22music_offtopic%22%2C+%22interaction%22%2C+%22intro%22%2C+%22filler%22%2C+%22sponsor%22%5D
[SponsorBlock] Found 2 segments in the SponsorBlock database
[debug] Default format spec: bestvideo+bestaudio/best
[info] k00UASRvAiw: Downloading 1 format(s): 313+251
[info] Writing video subtitles to: Scammer Can't Get His Chicken to be Quiet!  [k00UASRvAiw].en.vtt
[debug] Invoking downloader on "https://www.youtube.com/api/timedtext?v=k00UASRvAiw&asr_langs=de%2Cen%2Ces%2Cfr%2Cid%2Cit%2Cja%2Cko%2Cnl%2Cpt%2Cru%2Ctr%2Cvi&caps=asr&exp=xctw&xoaf=5&hl=en&ip=0.0.0.0&ipbits=0&expire=1646462330&sparams=ip%2Cipbits%2Cexpire%2Cv%2Casr_langs%2Ccaps%2Cexp%2Cxoaf&signature=E9A08B8EBA1E7F1CA73B27A6D96EAFE2A724757B.5E2ADB3AE55B7E07ED61FA3828997EB9A9D80518&key=yt8&kind=asr&lang=en&tlang=en&fmt=vtt"
[download] Destination: Scammer Can't Get His Chicken to be Quiet!  [k00UASRvAiw].en.vtt
[download] 100% of 46.97KiB in 00:00
[SubtitlesConvertor] Converting subtitles
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:Scammer Can't Get His Chicken to be Quiet!  [k00UASRvAiw].en.vtt" -f ass -movflags "+faststart" "file:Scammer Can't Get His Chicken to be Quiet!  [k00UASRvAiw].en.ass"
Deleting original file Scammer Can't Get His Chicken to be Quiet!  [k00UASRvAiw].en.vtt (pass -k to keep)
[debug] Invoking downloader on "https://rr3---sn-vgqsrnes.googlevideo.com/videoplayback?expire=1646458730&ei=CqMiYsSkKaSV2_gPs7i90AU&ip=73.36.52.228&id=o-AH8f9WXFlRGpbvM5KVPi98M6AmDcGwVp3WZyOOzgftx3&itag=313&source=youtube&requiressl=yes&mh=tR&mm=31%2C26&mn=sn-vgqsrnes%2Csn-p5qddn7k&ms=au%2Conr&mv=m&mvi=3&pl=16&initcwndbps=1961250&vprv=1&mime=video%2Fwebm&gir=yes&clen=897945521&dur=808.307&lmt=1646411175489886&mt=1646436778&fvip=3&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=3310224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRgIhAI4MES-8KwIhMtx9GPNAw-qp2seSV4ri_EIf57bf-Ys-AiEA1EnU37K_sTaU3jomYn6Wf82uYQcF9OBeC02E1es2irI%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhAIi7qW4D7RM5lBezrIP6CTmT_QNSIexXJQPdM8XiHExEAiB8lyBz1OKk0O8I7PN9zDPZhqH6KYS77_1AHz4SGrkMLw%3D%3D"
[download] Destination: Scammer Can't Get His Chicken to be Quiet!  [k00UASRvAiw].f313.webm
[download] 100% of 856.35MiB in 00:29
[debug] Invoking downloader on "https://rr3---sn-vgqsrnes.googlevideo.com/videoplayback?expire=1646458730&ei=CqMiYsSkKaSV2_gPs7i90AU&ip=73.36.52.228&id=o-AH8f9WXFlRGpbvM5KVPi98M6AmDcGwVp3WZyOOzgftx3&itag=251&source=youtube&requiressl=yes&mh=tR&mm=31%2C26&mn=sn-vgqsrnes%2Csn-p5qddn7k&ms=au%2Conr&mv=m&mvi=3&pl=16&initcwndbps=1961250&vprv=1&mime=audio%2Fwebm&gir=yes&clen=12034419&dur=808.341&lmt=1646410894049576&mt=1646436778&fvip=3&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=3310224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIgCcisW2KTThR3vV5MOZwosSiw4v7Hp890qNYEJrlisOACIQDh1ZQgnVbEd_T72UJUYKOIutvVD1T71R-NL0qT50iHJA%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhAIi7qW4D7RM5lBezrIP6CTmT_QNSIexXJQPdM8XiHExEAiB8lyBz1OKk0O8I7PN9zDPZhqH6KYS77_1AHz4SGrkMLw%3D%3D"
[download] Destination: Scammer Can't Get His Chicken to be Quiet!  [k00UASRvAiw].f251.webm
[download] 100% of 11.48MiB in 00:00
[Merger] Merging formats into "Scammer Can't Get His Chicken to be Quiet!  [k00UASRvAiw].mkv"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:Scammer Can't Get His Chicken to be Quiet!  [k00UASRvAiw].f313.webm" -i "file:Scammer Can't Get His Chicken to be Quiet!  [k00UASRvAiw].f251.webm" -c copy -map "0:v:0" -map "1:a:0" -movflags "+faststart" "file:Scammer Can't Get His Chicken to be Quiet!  [k00UASRvAiw].temp.mkv"
Deleting original file Scammer Can't Get His Chicken to be Quiet!  [k00UASRvAiw].f251.webm (pass -k to keep)
Deleting original file Scammer Can't Get His Chicken to be Quiet!  [k00UASRvAiw].f313.webm (pass -k to keep)
[EmbedSubtitle] Embedding subtitles in "Scammer Can't Get His Chicken to be Quiet!  [k00UASRvAiw].mkv"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:Scammer Can't Get His Chicken to be Quiet!  [k00UASRvAiw].mkv" -i "file:Scammer Can't Get His Chicken to be Quiet!  [k00UASRvAiw].en.ass" -map 0 -dn -ignore_unknown -c copy -map "-0:s" -map "1:0" "-metadata:s:s:0" "language=eng" -movflags "+faststart" "file:Scammer Can't Get His Chicken to be Quiet!  [k00UASRvAiw].temp.mkv"
Deleting original file Scammer Can't Get His Chicken to be Quiet!  [k00UASRvAiw].en.ass (pass -k to keep)
[debug] ffprobe command line: ffprobe -hide_banner -show_format -show_streams -print_format json "file:Scammer Can't Get His Chicken to be Quiet!  [k00UASRvAiw].mkv"
[Metadata] Adding metadata to "Scammer Can't Get His Chicken to be Quiet!  [k00UASRvAiw].mkv"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:Scammer Can't Get His Chicken to be Quiet!  [k00UASRvAiw].mkv" -i "file:Scammer Can't Get His Chicken to be Quiet!  [k00UASRvAiw].meta" -map 0 -dn -ignore_unknown -c copy -map_metadata 1 -movflags "+faststart" "file:Scammer Can't Get His Chicken to be Quiet!  [k00UASRvAiw].temp.mkv"
```

**Comment by RafeeDaBoy** [comment]
![image](https://user-images.githubusercontent.com/69535896/156873081-c97449e4-3573-41c0-850b-82bb83cef628.png)
Issue still present

**Comment by saood06** [comment]
> Issue still present

He committed a fix, you can wait for the next release, or if you need the fix before then, checkout and build the master branch yourself.

https://github.com/yt-dlp/yt-dlp#compile

**Comment by RafeeDaBoy** [comment]
Oh alright, understood. Thanks

**Comment by avih** [comment]
> He committed a fix,

Would anyone be able to describe what the fix does? Specifically does it make it work correctly for auto-subs? or does it avoid some kinds of auto-subs to prevent the new junk - but also prevent the auto-subs completely in such cases?

It's not obvious to me by looking at the relevant commit https://github.com/yt-dlp/yt-dlp/commit/d49669acad71f640ffd8b78f0ea7911ae1f67720

**Comment by pukkandan** [comment]
Auto-sub URLs normally look like `https://www.youtube.com/...lang=so&...tlang=en&...`. But now, when lang and tlang are same, youtube doesn't want us to pass `tlang` in the URL. Doing so causes the damaged subs to be returned

**Comment by avih** [comment]
> But now, when lang and tlang are same, youtube doesn't want us to pass `tlang`

Thanks.

Is there a way to identify auto-subs (transcripted) by examining at the URL?

I think before this change the presence of `tlang` was such indication, but now that it can be removed, can it still be identified somehow?

**Comment by pukkandan** [comment]
Not entirely sure, but I believe you can look for `kind=asr`

**Comment by avih** [comment]
Thanks. Appreciate the info/tips.

**Comment by Fraa-124** [comment]
@pukkandan This issue is still occurring in the latest release 2022.03.08.1.

But it only occurs when sub langs are <en-en>, on <es-en> for example it is ok.

**Comment by pukkandan** [comment]
Provide verbose log

**Comment by Fraa-124** [comment]
yt-dlp 'https://www.youtube.com/watch?v=AT3fCgxEAJE' --skip-download --write-auto-subs --write-subs   --sub-langs en-en-nP7-2PuUl7o  --verbose -o 'tmp/%(id)s/s'
[debug] Command-line config: ['https://www.youtube.com/watch?v=AT3fCgxEAJE', '--skip-download', '--write-auto-subs', '--write-subs', '--sub-langs', ',en-en-nP7-2PuUl7o', '--verbose', '-o', 'tmp/%(id)s/s']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, err UTF-8, pref UTF-8
[debug] yt-dlp version 2022.03.08.1 [c0c2c57d3]
[debug] Python version 3.6.13 (CPython 64bit) - Darwin-21.2.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Optional libraries: brotli, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=AT3fCgxEAJE
[youtube] AT3fCgxEAJE: Downloading webpage
[youtube] AT3fCgxEAJE: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[debug] Downloading subtitles: en, en-en-nP7-2PuUl7o
[debug] Default format spec: best/bestvideo+bestaudio
[info] AT3fCgxEAJE: Downloading 1 format(s): 22
Deleting existing file tmp/AT3fCgxEAJE/s.en.vtt
[info] Writing video subtitles to: tmp/AT3fCgxEAJE/s.en.vtt
[debug] Invoking downloader on "https://www.youtube.com/api/timedtext?v=AT3fCgxEAJE&asr_langs=de%2Cen%2Ces%2Cfr%2Cid%2Cit%2Cja%2Cko%2Cnl%2Cpt%2Cru%2Ctr%2Cvi&caps=asr&exp=xctw&xoaf=5&hl=en&ip=0.0.0.0&ipbits=0&expire=1646850707&sparams=ip%2Cipbits%2Cexpire%2Cv%2Casr_langs%2Ccaps%2Cexp%2Cxoaf&signature=DF42CD76201958731864CC1B91B55D1D6F6338EB.3FEC425F6797374F623EA9F0BADD1A6E911C23BC&key=yt8&kind=asr&lang=en&fmt=vtt"
[download] Destination: tmp/AT3fCgxEAJE/s.en.vtt
[download] 100% of 29.01KiB in 00:00
Deleting existing file tmp/AT3fCgxEAJE/s.en-en-nP7-2PuUl7o.vtt
[info] Writing video subtitles to: tmp/AT3fCgxEAJE/s.en-en-nP7-2PuUl7o.vtt
[debug] Invoking downloader on "https://www.youtube.com/api/timedtext?v=AT3fCgxEAJE&asr_langs=de%2Cen%2Ces%2Cfr%2Cid%2Cit%2Cja%2Cko%2Cnl%2Cpt%2Cru%2Ctr%2Cvi&caps=asr&exp=xctw&xoaf=5&hl=en&ip=0.0.0.0&ipbits=0&expire=1646850707&sparams=ip%2Cipbits%2Cexpire%2Cv%2Casr_langs%2Ccaps%2Cexp%2Cxoaf&signature=DF42CD76201958731864CC1B91B55D1D6F6338EB.3FEC425F6797374F623EA9F0BADD1A6E911C23BC&key=yt8&lang=en&name=en&tlang=en-en-nP7-2PuUl7o&fmt=vtt"
[download] Destination: tmp/AT3fCgxEAJE/s.en-en-nP7-2PuUl7o.vtt
[download] 100% of 5.85KiB in 00:00
[debug] Proxy map: {}
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=AT3fCgxEAJE
[youtube] AT3fCgxEAJE: Downloading webpage
[youtube] AT3fCgxEAJE: Downloading android player API JSON

**Comment by pukkandan** [comment]
idk why the language code looks like `en-nP7-2PuUl7o`. Will need to look into it more
