### ISSUE TITLE
Special characters in output -o

### ISSUE THREAD

**Issue by mike2003** [yt-dlp/yt-dlp#2958]
### Checklist
- [X] I'm asking a question and **not** reporting a bug/feature request

### Question

I want to get the list of videos, title and link from the playlist into a separate file.

**yt-dlp --get-filename -o "%%(upload_date>%%d-%%m-%%Y)s | %%(title)s | %%(webpage_url)s" "https://www.youtube.com/playlist?list=...."**

But some characters are not displayed.

**15-11-2021 # TITLES # https -_www.youtube.com_watchv=qT77.....**

No ://
no | = #

Did not help:
--no-restrict-filenames
--no-windows-filenames 

And another similar question - how can I make a newline between variables? Like

**15-11-2021 - TITLES
https -_www.youtube.com_watchv=qT77.....**

**Comment by pukkandan** [comment]
`--get-filename` obviously converts it into a valid filename. Use `--print`

> how can I make a newline between variables? 

However you can type newline in your shell. If inside a config-file, POSIX compliant quoting can be used

**Comment by mike2003** [comment]
> type newline in your shell
I didn't really understand. You can details. I have windows and bat file.

**Comment by pukkandan** [comment]
Better to ask this in appropriate forums. Perhaps this can get you started: https://stackoverflow.com/questions/9393391
