### ISSUE TITLE
[Feature Request] Add support for ec-3, dtsc

### ISSUE THREAD

**Issue by girod2033** [yt-dlp/yt-dlp#296]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running yt-dlp version **2021.04.22**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description

Hello.
Please add support for ec-3, dtsc.

yt-dlp.exe --allow-unplayable-formats -F "http://prod-stpeter-mss.verizon.cdn.rakuten.tv/1/4/7/147569feb106401d61f0a677799acd3d-mc-0-139-0-0_DS2/stream.ism/Manifest"

yt-dlp.exe -F "https://smstr01.dmm.t-online.de/smooth24/smoothstream_m1/streaming/sony/9221438342941275747/636887760842957027/25_km_h-Trailer-9221571562372022953_deu_20_1300k_HD_H_264_ISMV.ism/Manifest"

WARNING: [generic] EC-3 is not a supported codec
WARNING: [generic] dtsc is not a supported codec

**Comment by pukkandan** [comment]
Give non-DRM example

**Comment by girod2033** [comment]
The second link is DRM-free, but alas, only for ec-3.

https://smstr01.dmm.t-online.de/smooth24/smoothstream_m1/streaming/sony/9221438342941275747/636887760842957027/25_km_h-Trailer-9221571562372022953_deu_20_1300k_HD_H_264_ISMV.ism/Manifest

**Comment by pukkandan** [comment]
Related: https://github.com/ytdl-org/youtube-dl/issues/20968

**Comment by nixxo** [comment]
@girod2033 do you have another url for the `dtsc` codec? the one linked is 404
