### ISSUE TITLE
How to choose a format for thumbnail download? --write-thumbnail

### ISSUE THREAD

**Issue by mike2003** [yt-dlp/yt-dlp#2962]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

I see many formats with the **--list-thumbnails** command and **--write-all-thumbnails**.

But **--write-thumbnail** downloads only one *.webp **720р**

I want a different format (jpg) and larger size **1080р**. How to do it? Is there a filter like for video -f ?

**Comment by pukkandan** [comment]
No #237
