### ISSUE TITLE
--print does not support formatting fixed length string?

### ISSUE THREAD

**Issue by rieje** [yt-dlp/yt-dlp#2968]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

I want to write my own version of the output of `--download-archive` to include more information about the video. The command:

    yt-dlp --print "%(uploader)s | %(title)15s | upload_date: %(upload_date)s | view_count: %(view_count)s | duration: %(duration_string)s | playlist_title: %(playlist_title)s | playlist_count: %(playlist_count)s" "https://www.youtube.com/watch?v=37ONcQX2BxU"

shows the output:

    Catch N Cook California | 48 HR SURVIVAL W/ TRASH FOR A KIT: WE FOUND A GUN!!!!!!!!!! | upload_date: 20220303 | view_count: 1475 | duration: 41:20 | playlist_title: NA | playlist_count: NA

Here, the title `48 HR SURVIVAL W/ TRASH FOR A KIT: WE FOUND A GUN!!!!!!!!!!` is not formatted to just 15 characters as specified by `%(title)15s`. My goal is to have the output of each video in a nicely formatted table with fixed length strings and consistent indentation in each column.

Is my attempt correct and/or does yt-dlp not support string formatting this way?

**Comment by pukkandan** [comment]
Your formatting syntax is wrong. It should be `%(title).15s` to limit string to 15 chars. Go through https://docs.python.org/3/library/stdtypes.html#printf-style-string-formatting and https://github.com/yt-dlp/yt-dlp#output-template

**Comment by pukkandan** [comment]
> I want to write my own version of the output of --download-archive to include more information about the video. 

You may also want to look into the (new) `--print-to-file` option which will allow you to write this data into a file and download the video in a single command (without sacrificing the normal console output)

**Comment by rieje** [comment]
Thanks. `--print-to-file` would work but it prints as soon as the file starts downloading which IMO doesn't make much sense (just like `--download-archive` it should print only after complete download).

**Comment by pukkandan** [comment]
--print-to-file [WHEN:]TEMPLATE FILE
                                     Append given template to the file. The
                                     values of WHEN and TEMPLATE are same as
                                     that of --print. FILE uses the same syntax
                                     as the output template. This option can be
                                     used multiple times

    --use-postprocessor NAME[:ARGS]  ...
                                     The "when" argument determines when the
                                     postprocessor is invoked. It can be one of
                                     "pre_process" (after video extraction),
                                     "after_filter" (after video passes filter),
                                     "before_dl" (before each video download),
                                     "post_process" (after each video download;
                                     default), "after_move" (after moving video
                                     file to it's final locations),
                                     "after_video" (after downloading and
                                     processing all formats of a video), or
                                     "playlist" (at end of playlist). ...
