### ISSUE TITLE
[ARD] Support for seasons

### ISSUE THREAD

**Issue by rassie** [yt-dlp/yt-dlp#2975]
### Checklist

- [X] I'm reporting a site feature request
- [X] I've verified that I'm running yt-dlp version **2022.02.04**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Germany

### Example URLs

https://www.ardmediathek.de/sendung/beforeigners/beforeigners/staffel-2/Y3JpZDovL2Rhc2Vyc3RlLmRlL2JlZm9yZWlnbmVycw/2

### Description

ARD Mediathek seems to have added season numbers to their URL, therefore `showId` is `2` in the example URL, which obviously fails to query (with `'NoneType' object is not subscriptable` as error message of all thngs).

### Verbose log

```shell
$ yt-dlp -vU https://www.ardmediathek.de/sendung/beforeigners/beforeigners/staffel-2/Y3JpZDovL2Rhc2Vyc3RlLmRlL2JlZm9yZWlnbmVycw/2[debug] Command-line config: ['-vU', 'https://www.ardmediathek.de/sendung/beforeigners/beforeigners/staffel-2/Y3JpZDovL2Rhc2Vyc3RlLmRlL2JlZm9yZWlnbmVycw/2']
[debug] User config "/home/nikolai/.config/yt-dlp/config": ['--all-subs', '--embed-sub', '--sub-langs', 'all,-live_chat']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.02.04 [c1653e9ef]
[debug] Python version 3.8.10 (CPython 64bit) - Linux-5.13.0-30-generic-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4, rtmpdump 2.4
[debug] Optional libraries: Cryptodome, secretstorage, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.02.04, Current version: 2022.02.04
yt-dlp is up to date (2022.02.04)
[debug] Using fake IP 53.101.205.146 (DE) as X-Forwarded-For
[debug] [ARDBetaMediathek] Extracting URL: https://www.ardmediathek.de/sendung/beforeigners/beforeigners/staffel-2/Y3JpZDovL2Rhc2Vyc3RlLmRlL2JlZm9yZWlnbmVycw/2
[ARDBetaMediathek] [Playlist] beforeigners/beforeigners/staffel-2/Y3JpZDovL2Rhc2Vyc3RlLmRlL2JlZm9yZWlnbmVycw: Downloading JSON metadata
ERROR: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/home/nikolai/.local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 1381, in wrapper
    return func(self, *args, **kwargs)
  File "/home/nikolai/.local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 1451, in __extract_info
    ie_result = ie.extract(url)
  File "/home/nikolai/.local/lib/python3.8/site-packages/yt_dlp/extractor/common.py", line 612, in extract
    ie_result = self._real_extract(url)
  File "/home/nikolai/.local/lib/python3.8/site-packages/yt_dlp/extractor/ard.py", line 572, in _real_extract
    return self._ARD_extract_playlist(url, video_id, display_id, client, playlist_type)
  File "/home/nikolai/.local/lib/python3.8/site-packages/yt_dlp/extractor/ard.py", line 536, in _ARD_extract_playlist
    for teaser in show_page['teasers']:  # process playlist items
TypeError: 'NoneType' object is not subscriptable
```

**Comment by pukkandan** [comment]
https://github.com/yt-dlp/yt-dlp/commit/f1f07af8d64dc3639410d49cba15ff0b27e2a6dd fixes the extractor, but all seasons are downloaded for now, not just the one in URL

**Comment by rassie** [comment]
Thanks, this helps a lot already!
