### ISSUE TITLE
Site support for ltv.lsm.lv

### ISSUE THREAD

**Issue by Burve** [yt-dlp/yt-dlp#2978]
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.02.04**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Latvia, but works also globally

### Example URLs

https://ltv.lsm.lv/lv/raksts/05.03.2022-ielas-garuma-sievietes-tels-eku-dekora.id254828
https://ltv.lsm.lv/lv/raidijums/ielas-garuma
https://ltv.lsm.lv/lv/raidijumi

### Description

ltv.lsm.lv is an online repository for Latvian public television that allow rewatching any content shown on the public TV broadcast.

While direct m3u8 URL from the site works perfectly, having a working extractor would be preferable.

### Verbose log

```shell
[debug] Command-line config: ['-vU', 'https://ltv.lsm.lv/lv/raksts/05.03.2022-ielas-garuma-sievietes-tels-eku-dekora.id254828']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.02.04 [c1653e9ef]
[debug] Python version 3.10.1 (CPython 64bit) - Windows-10-10.0.22000-SP0
[debug] exe versions: ffmpeg n4.4.1-1-g0204d4fd91-20211030 (setts), ffprobe n4.4.1-1-g0204d4fd91-20211030
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.02.04, Current version: 2022.02.04
yt-dlp is up to date (2022.02.04)
[debug] [generic] Extracting URL: https://ltv.lsm.lv/lv/raksts/05.03.2022-ielas-garuma-sievietes-tels-eku-dekora.id254828
[generic] 05.03.2022-ielas-garuma-sievietes-tels-eku-dekora: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] 05.03.2022-ielas-garuma-sievietes-tels-eku-dekora: Downloading webpage
[generic] 05.03.2022-ielas-garuma-sievietes-tels-eku-dekora: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://ltv.lsm.lv/lv/raksts/05.03.2022-ielas-garuma-sievietes-tels-eku-dekora.id254828
Traceback (most recent call last):
  File "C:\Users\AlexI\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 1381, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\AlexI\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 1451, in __extract_info
    ie_result = ie.extract(url)
  File "C:\Users\AlexI\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\extractor\common.py", line 612, in extract
    ie_result = self._real_extract(url)
  File "C:\Users\AlexI\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\extractor\generic.py", line 3986, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://ltv.lsm.lv/lv/raksts/05.03.2022-ielas-garuma-sievietes-tels-eku-dekora.id254828
```

**Comment by coletdjnz** [comment]
Dor devs:
1. Get embed id from NUXT JS on page (_search_nuxt_data might help)
2. request `https://ltv.lsm.lv/embed?c=<embed id>&enablesdkjs=1`, extract embed window json
   - looks like `window['P3yGy3Jl'] = {...}` for me, but may have a different id
3. extract embed_url from embed window json (this should be a embed.cloudycdn.services url)

From here I think we would need another extractor for `embed.cloudycdn.services` (looking up this domain I get hits for other videos that do not appear to be ltv)

- The embed url is in the form `https://embed.cloudycdn.services/<name>/media/<video id>?autoplay&playertype=regular&protocol=hls`
- Request player JSON API at POST `https://player.cloudycdn.services/player/<name>/media/<video id>/` (this may need a "referer" json key in the payload)
- streaming url is under source -> sources in the JSON response

https://www.tavaklase.lv/video/latgali-i-latgalisi/ also uses the same cloudycdn embed
