### ISSUE TITLE
[Question] Update issues (Solved)

### ISSUE THREAD

**Issue by ACR-Jeff** [yt-dlp/yt-dlp#298]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

I have had yt-dlp installed for a few weeks now and it's been working fine until today, I was unable to download videos. I have been trying to update yt-dlp since I noticed my version number is 2021.04.11 and there is a new update available. 
I originally installed using the master file. I read that the only way to update is through the same method I originally installed. Here I am with the master file and read the README.md File states using "make" to install the new version?
Here is my output after using "make" in terminal:
`make
/usr/bin/env python3 devscripts/make_issue_template.py .github/ISSUE_TEMPLATE_tmpl/1_broken_site.md .github/ISSUE_TEMPLATE/1_broken_site.md
/usr/bin/env python3 devscripts/make_issue_template.py .github/ISSUE_TEMPLATE_tmpl/2_site_support_request.md .github/ISSUE_TEMPLATE/2_site_support_request.md
/usr/bin/env python3 devscripts/make_issue_template.py .github/ISSUE_TEMPLATE_tmpl/3_site_feature_request.md .github/ISSUE_TEMPLATE/3_site_feature_request.md
/usr/bin/env python3 devscripts/make_issue_template.py .github/ISSUE_TEMPLATE_tmpl/4_bug_report.md .github/ISSUE_TEMPLATE/4_bug_report.md
/usr/bin/env python3 devscripts/make_issue_template.py .github/ISSUE_TEMPLATE_tmpl/5_feature_request.md .github/ISSUE_TEMPLATE/5_feature_request.md
/usr/bin/env python3 devscripts/make_supportedsites.py supportedsites.md
git shortlog -s -e -n | awk '!(out[$NF]++) { $1="";sub(/^[ \t]+/,""); print}' > .mailmap
(reading log message from standard input)
`

**Comment by ACR-Jeff** [comment]
I got it updated using these commands on in the README.md
`sudo wget https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -O /usr/local/bin/yt-dlp
sudo chmod a+rx /usr/local/bin/yt-dlp`
Yet I have another issue I will ask in another question. Marking this as solved

**Comment by pukkandan** [comment]
> originally installed using the master file

What do you mean master file?

Make is for compiling the application, not for users to install it. Basically, if you don't know what `make` does, don't use it

Anyway, now you have installed it using the release binary. So `yt-dlp -U` will update it from now
