### ISSUE TITLE
Add cookies support for LibreWolf

### ISSUE THREAD

**Issue by ItsPizzaTime1501** [yt-dlp/yt-dlp#2983]
### Checklist

- [X] I'm reporting a feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.02.04**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

[LibreWolf ](https://librewolf.net/) is just a fork of FireFox, profiles folder is located at `%APPDATA%/librewolf/Profiles` (on windows at least, totally forgot what it is on linux but should be pretty similar to FF). I'm thinking this wouldn't be very difficult to add.

**Comment by pukkandan** [comment]
https://github.com/yt-dlp/yt-dlp/issues/2903#issuecomment-1053567469

**Comment by ItsPizzaTime1501** [comment]
I guess not wanting to add support for every subset of each browser is understandable. Pointing it to the LibreWolf folder worked, thanks!
