### ISSUE TITLE
Site Request: netverse.id - All Programs NET.TV

### ISSUE THREAD

**Issue by cx410** [yt-dlp/yt-dlp#2984]
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.02.04**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Indonesian

### Example URLs

- Single video: https://netverse.id/watch/tetangga-baru
- Playlist video: https://netverse.id/webseries/tetangga-masa-gitu
- M3U8: https://www.dailymotion.com/cdn/manifest/video/x8278vk.m3u8?sec=ZvtOzbF3ouo22MlBQOpdsm_FcIrwN3BaoY-APu4ILYghTvwTR0Bl2Nn8Advcx77cAxFuGI_gS9Qy1omrBf4b6Q&dmTs=710095&dmV1st=2F93EE6A12FF72D77113A4E603E66316

### Description

Use VPN if play videos in this website.

### Verbose log

```shell
C:\Users\Administrator\Downloads\Compressed>yt-dlp -vU https://www.dailymotion.com/cdn/manifest/video/x8278vk.m3u8?sec=ZvtOzbF3ouo22MlBQOpdsm_FcIrwN3BaoY-APu4ILYghTvwTR0Bl2Nn8Advcx77cAxFuGI_gS9Qy1omrBf4b6Q&dmTs=710095&dmV1st=2F93EE6A12FF72D77113A4E603E66316
[debug] Command-line config: ['-vU', 'https://www.dailymotion.com/cdn/manifest/video/x8278vk.m3u8?sec=ZvtOzbF3ouo22MlBQOpdsm_FcIrwN3BaoY-APu4ILYghTvwTR0Bl2Nn8Advcx77cAxFuGI_gS9Qy1omrBf4b6Q']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.02.04 [c1653e9] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.17763-SP0
[debug] exe versions: ffmpeg 2021-04-18-git-d43b26b30d-essentials_build-www.gyan.dev (setts), ffprobe 2021-04-18-git-d43b26b30d-essentials_build-www.gyan.dev
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.02.04, Current version: 2022.02.04
yt-dlp is up to date (2022.02.04)
[debug] [dailymotion:user] Extracting URL: https://www.dailymotion.com/cdn/manifest/video/x8278vk.m3u8?sec=ZvtOzbF3ouo22MlBQOpdsm_FcIrwN3BaoY-APu4ILYghTvwTR0Bl2Nn8Advcx77cAxFuGI_gS9Qy1omrBf4b6Q
[download] Downloading playlist: cdn
[dailymotion:user] Downloading Access Token
[dailymotion:user] cdn: Downloading page 1
ERROR: Can't find object userchannel for `cdn`.
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1381, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1685, in <lambda>
  File "yt_dlp\utils.py", line 2795, in __getitem__
  File "yt_dlp\utils.py", line 2786, in getslice
  File "yt_dlp\utils.py", line 2818, in _getslice
  File "yt_dlp\utils.py", line 2780, in getpage
  File "yt_dlp\extractor\dailymotion.py", line 328, in _fetch_page
  File "yt_dlp\extractor\dailymotion.py", line 89, in _call_api
yt_dlp.utils.ExtractorError: Can't find object userchannel for `cdn`.
```

**Comment by pukkandan** [comment]
Closed by: https://github.com/yt-dlp/yt-dlp/commit/60ba603ab5c720c1fa09cdeabb5087ae607027ae
