### ISSUE TITLE
[Broken] Pluto TV On Demand Movies

### ISSUE THREAD

**Issue by ACR-Jeff** [yt-dlp/yt-dlp#299]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running yt-dlp version **2021.04.22**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
yt-dlp --verbose https://pluto.tv/on-demand/movies/30-days-of-night-dark-days-2010-1-1
[debug] Command-line config: ['--verbose', 'https://pluto.tv/on-demand/movies/30-days-of-night-dark-days-2010-1-1']
[debug] Loading archive file None
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] yt-dlp version 2021.04.22 (zip)
[debug] Python version 3.8.5 (CPython 64bit) - Linux-5.4.0-70-generic-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4
[debug] Proxy map: {}
[PlutoTV] 30-days-of-night-dark-days-2010-1-1: Downloading JSON metadata
[PlutoTV] 6058cdaeb58b22001a46e0de: Downloading m3u8 information
[PlutoTV] 6058cdaeb58b22001a46e0de: Downloading m3u8 playlist
[PlutoTV] 6058cdaeb58b22001a46e0de: Downloading m3u8 playlist
[PlutoTV] 6058cdaeb58b22001a46e0de: Downloading m3u8 playlist
[PlutoTV] 6058cdaeb58b22001a46e0de: Downloading m3u8 playlist
[PlutoTV] 6058cdaeb58b22001a46e0de: Downloading m3u8 playlist
ERROR: No video formats found; please report this issue on https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/acr-linux/.local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1059, in wrapper
    return func(self, *args, **kwargs)
  File "/home/acr-linux/.local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1080, in __extract_info
    ie_result = ie.extract(url)
  File "/home/acr-linux/.local/bin/yt-dlp/yt_dlp/extractor/common.py", line 558, in extract
    ie_result = self._real_extract(url)
  File "/home/acr-linux/.local/bin/yt-dlp/yt_dlp/extractor/plutotv.py", line 164, in _real_extract
    return self._get_video_info(video_json, info_slug)
  File "/home/acr-linux/.local/bin/yt-dlp/yt_dlp/extractor/plutotv.py", line 119, in _get_video_info
    'formats': self._to_ad_free_formats(video_id, formats),
  File "/home/acr-linux/.local/bin/yt-dlp/yt_dlp/extractor/plutotv.py", line 103, in _to_ad_free_formats
    self._sort_formats(ad_free_formats)
  File "/home/acr-linux/.local/bin/yt-dlp/yt_dlp/extractor/common.py", line 1687, in _sort_formats
    raise ExtractorError('No video formats found')
yt_dlp.utils.ExtractorError: No video formats found; please report this issue on https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.

```

## Description

I can watch the movie on pluto tv through my browser yet I get this issue when I am trying to download using yt-dlp

**Comment by ACR-Jeff** [comment]
Update I can download Pluto TV shows and other Movies on Pluto TV without any problems using yt-dlp. This one specific movie will not download.

**Comment by pukkandan** [comment]
What does `yt-dlp -F --allow-unplayable-formats URL` give?

**Comment by MexiAmeri** [comment]
@pukkandan 

I tried running this example and got the below error:

yt-dlp -F --allow-unplayable-formats https://pluto.tv/on-demand/movies/30-days-of-night-dark-days-2010-1-1
[PlutoTV] 30-days-of-night-dark-days-2010-1-1: Downloading JSON metadata
[PlutoTV] 6058cdaeb58b22001a46e0de: Downloading m3u8 information
[PlutoTV] 6058cdaeb58b22001a46e0de: Downloading m3u8 playlist
[PlutoTV] 6058cdaeb58b22001a46e0de: Downloading m3u8 playlist
[PlutoTV] 6058cdaeb58b22001a46e0de: Downloading m3u8 playlist
[PlutoTV] 6058cdaeb58b22001a46e0de: Downloading m3u8 playlist
[PlutoTV] 6058cdaeb58b22001a46e0de: Downloading m3u8 playlist
ERROR: No video formats found; please report this issue on https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
