### ISSUE TITLE
ERROR: unable to write data: [Errno 28] No space left on device

### ISSUE THREAD

**Issue by Donfu007** [yt-dlp/yt-dlp#2990]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

ISSUE: On a Synology server, I am getting this error when downloading:

[download] Destination: gavintoobe/gavintoobe - Videos/gavintoobe - Videos - S01E003 - Mark 7 APEX 10 Autodrive Unboxing, Setup, Overview, Loading 45 ACP [k-y_dY2ZUG8].f140.m4a
[download]   0.0% of 14.46MiB at  1.44MiB/s ETA 00:10

   ERROR: unable to write data: [Errno 28] No space left on device
   Traceback (most recent call last):
     File "/usr/local/bin/yt-dlp/yt_dlp/downloader/http.py", line 281, in download
          ctx.stream.write(data_block)
   OSError: [Errno 28] No space left on device

When I perform the following command, I can see that /dev/md0 is full.: 

   root@coddiwomple:~# df -h

   Filesystem         Size  Used Avail Use% Mounted on
   /dev/md0           2.3G  2.3G     0 100% /
   devtmpfs           874M     0  874M   0% /dev
   tmpfs              877M   64K  877M   1% /dev/shm
   tmpfs              877M   31M  847M   4% /run
   tmpfs              877M     0  877M   0% /sys/fs/cgroup
   tmpfs              877M  2.2M  875M   1% /tmp
   /dev/vg1/volume_1  7.0T  1.1T  5.9T  16% /volume1

QUESTION: What is this directory?  How to I access it?  Is there a way to work around this?  Or have I just hit a limitation of the software?  I probably have 400 movies, and about 30 YouTube videos on the system.

**Comment by fstirlitz** [comment]
This is not a general Unix support forum. Please only ask questions specific to yt-dlp itself here.

That said, it looks like you download everything into a partition that is meant to host the OS, not the one meant for user data, which is mounted at `/volume1`. I say ‘looks like’, because you didn’t even include the full log and command line. (Don’t bother though; this is not the place to ask such things.)

**Comment by Donfu007** [comment]
To me working as a dev for 30 years(not unix) and trying to debug the issue here, this to me is a yt-dlp issue.
This Synology machine has been set up clean yesterday with standard DSM 7.0, and standard installation of PLEX...nothing else.

INSTALLATION of yt-dlp
-----------------------
sudo curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp

COMMAND LINE:
-------------
yt-dlp \
--dateafter now-2weeks \
--compat-options youtube-dlc \
--socket-timeout 60 \
-vU \
--download-archive /volume1/PlexData/YouTube/subscription_list_downloaded.txt \
-i \
-o "%(uploader)s/%(playlist)s/%(playlist)s - S01E%(playlist_index)s - %(title)s [%(id)s].%(ext)s" \
--add-metadata \
--write-thumbnail \
--batch-file=/volume1/PlexData/YouTube/subscription_list.txt

STACK TRACE
------------
...I can give you the debug trace before this but does not offer anything to the issue here. 
[debug] Invoking downloader on "https://rr1---sn-nx5s7n7y.googlevideo.com/videoplayback?expire=1646780345&ei=WYsnYq3SLuOEsfIPzNOD4AQ&ip=24.113.11.109&id=o-AI6RY2qJqwm00E6Pf2Uq897oP12YVwzZKVIftcg2YR29&itag=313&source=youtube&requiressl=yes&mh=zw&mm=31%2C26&mn=sn-nx5s7n7y%2Csn-o097znsr&ms=au%2Conr&mv=m&mvi=1&pl=20&initcwndbps=1561250&vprv=1&mime=video%2Fwebm&gir=yes&clen=1609058926&dur=937.036&lmt=1646501543816407&mt=1646758411&fvip=1&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=5432434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIgOahK7z_H6IFwrMzYQ8yqZQhmAJz5XusZgDEDJW9SgZACIQDMektIbSZT5kyd8IGSxPLclieAZFoS9j2RYVRMfaB7SA%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhAMAc9VDj-n8M2Hm2DbM5aA1it6SraDr2HLHcohvn1Pw7AiAoN4i0A7VzQvbkIoj4JyRdwrPVARqvMJ1zxFJxXOsMfw%3D%3D"
[download] Resuming download at byte 464097280
[download] Destination: gavintoobe/gavintoobe - Videos/gavintoobe - Videos - S01E003 - Mark 7 APEX 10 Autodrive Unboxing, Setup, Overview, Loading 45 ACP [k-y_dY2ZUG8].f313.webm
[download]  28.8% of 1.50GiB at  1.39MiB/s ETA 13:06

ERROR: unable to write data: [Errno 28] No space left on device
Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/downloader/http.py", line 281, in download
    ctx.stream.write(data_block)
OSError: [Errno 28] No space left on device

REASON OF FAILURE I THINK
----------------------------
Filesystem         Size   Used   Avail   Use%   Mounted on
/dev/md0           2.3G   2.3G   0       100%   /
/dev/vg1/volume_1  7.0T   1.1T   5.9T    16%    /volume1

COMMENTS
-----------
What is yt-dlp using /dev/md0 for?  Note the user data you mentioned in on /dev/vg1/volume_1
Should I be installing yt-dlp using a different argument for -o?
Should the command line for running tp-dlp be different?

**Comment by coletdjnz** [comment]
`/dev/md0` is the system root partition for DSM. It sounds like your current directory you are downloading to is on this partition. You need to change your current directory to one where your user data is (usually` /volume1/<share folder name>`).

**Comment by Donfu007** [comment]
My apologies, I should have given you the whole command line. I think I am doing that?

#!/bin/sh
cd /volume1/PlexData/YouTube
yt-dlp \
--dateafter now-2weeks \
--compat-options youtube-dlc \
--socket-timeout 60 \
-vU \
--download-archive /volume1/PlexData/YouTube/subscription_list_downloaded.txt \
-i \
-o "%(uploader)s/%(playlist)s/%(playlist)s - S01E%(playlist_index)s - %(title)s [%(id)s].%(ext)s" \
--add-metadata \
--write-thumbnail \
--batch-file=/volume1/PlexData/YouTube/subscription_list.txt

**Comment by Donfu007** [comment]
Thanks Cole, I think I am doing that in the scheduled task, sorry, I should have added that.  Is this what you ae talking about? 

#!/bin/sh
cd /volume1/PlexData/YouTube
yt-dlp \
--dateafter now-2weeks \
--compat-options youtube-dlc \
--socket-timeout 60 \
-vU \
--download-archive /volume1/PlexData/YouTube/subscription_list_downloaded.txt \
-i \
-o "%(uploader)s/%(playlist)s/%(playlist)s - S01E%(playlist_index)s - %(title)s [%(id)s].%(ext)s" \
--add-metadata \
--write-thumbnail \
--batch-file=/volume1/PlexData/YouTube/subscription_list.txt

**Comment by Donfu007** [comment]
I think everyone here is correct here.  I might have(not sure) ran the yt-dlp on the SSH command line and may not have changed directories.  I'm clean re-installed everything and am monitoring the memory with DSM7/Plex/yt-dlp and not seeing the memory getting eaten up.  Closing, thanks or the help here :-)
