### ISSUE TITLE
[Rokfin] Search & login

### ISSUE THREAD

**Issue by P-reducible** [yt-dlp/yt-dlp#2991]
### Checklist

- [X] I'm reporting a site feature request
- [ ] I've verified that I'm running yt-dlp version **2022.03.08**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Example URLs

https://www.rokfin.com/discover

### Description

See title.

### Verbose log

```shell
Not applicable.
```

**Comment by P-reducible** [comment]
[PR](https://github.com/yt-dlp/yt-dlp/pull/2992)

**Comment by pukkandan** [comment]
This is not a properly filed issue. But idk why you even opened it, you should've just made the PR 🤷
