### ISSUE TITLE
Build Failure:  FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt' 

### ISSUE THREAD

**Issue by bevanjkay** [yt-dlp/yt-dlp#2995]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.03.08.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

We are currently seeing a build failure for Homebrew
https://github.com/Homebrew/homebrew-core/pull/96535

Related to https://github.com/yt-dlp/yt-dlp/commit/4390d5ec12349e5b5bba30af6b4e7f08678af41a#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7

### Verbose log

```shell
Traceback (most recent call last):
      File "<string>", line 2, in <module>
      File "<pip-setuptools-caller>", line 34, in <module>
      File "/private/tmp/yt-dlp-20220308-98604-1sbju7t/yt-dlp-2022.3.8.1/setup.py", line 26, in <module>
        REQUIREMENTS = open('requirements.txt', encoding='utf-8').read().splitlines()
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
    error: subprocess-exited-with-error
```

**Comment by Lesmiscore** [comment]
There are 2 options to fix this:
1. Remove reference to requirements.txt
2. Include requirements.txt into tgz archive in PyPI, like https://github.com/ytdl-patched/ytdl-patched/blob/ytdlp/MANIFEST.in

**Comment by pukkandan** [comment]
Yeah, I'm on it. When I saw https://github.com/yt-dlp/homebrew-taps/issues/2, I just didn't realize what the issue was

**Comment by pukkandan** [comment]
Pls update with https://pypi.org/manage/project/yt-dlp/release/2022.3.8.2/
