### ISSUE TITLE
'<' not supported between instances of 'float' and 'str' and --throttled-rate error after update?

### ISSUE THREAD

**Issue by modernCRTuser** [yt-dlp/yt-dlp#2996]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.03.08.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

After update I get error

'<' not supported between instances of 'float' and 'str'

I found out that it is somewhat related to --throttled-rate setting? When I remove it I can download from YT no issues
If I leave it, I get the following message

[download]   0.0% of 714.94MiB at 499.98KiB/s ETA 24:24ERROR: '<' not supported between instances of 'float' and 'str'

### Verbose log

```shell
Microsoft Windows [Version 6.1.7601]

>yt-dlp https://www.youtube.com/watch?v=XUp9pe1T-UE --throttled-rate 999k
[youtube] XUp9pe1T-UE: Downloading webpage
[youtube] XUp9pe1T-UE: Downloading android player API JSON
[info] XUp9pe1T-UE: Downloading 1 format(s): 571+251
WARNING: Requested formats are incompatible for merge and will be merged into mkv
[download] Destination: 8k VIDEOS _ Beauty of Nature 8K (60 FPS) HDR  UltraHD  _ Sony Demo [XUp9pe1T-UE].f571.mp4
[download]   0.0% of 505.86MiB at 90.90KiB/s ETA 01:34:58ERROR: '<' not supported between instances of 'float' and 'str'

yt>
```

**Comment by pukkandan** [comment]
It's a typo in d1b5f70bc9f9dcda1544b88b42ecc25f7f7aa1c7. You can roll back to https://github.com/yt-dlp/yt-dlp/releases/tag/2022.03.08 for the time-being as a workaround. The 2 releases are almost identical, so it shouldn't be an issue

**Comment by mechanical-snail** [comment]
I was about to report the copy-paste error but found this.

Specifically, This line: `opts.ratelimit = parse_bytes('throttled rate limit', opts.throttledratelimit)` (https://github.com/yt-dlp/yt-dlp/commit/d1b5f70bc9f9dcda1544b88b42ecc25f7f7aa1c7#L258)

should be `opts.throttledratelimit = parse_bytes('throttled rate limit', opts.throttledratelimit)`

**Comment by coreyoilar** [comment]
I have the same problem after just updating to the latest version 2022.03.08.1

**Comment by madindehead** [comment]
> It's a typo in [d1b5f70](https://github.com/yt-dlp/yt-dlp/commit/d1b5f70bc9f9dcda1544b88b42ecc25f7f7aa1c7). You can roll back to https://github.com/yt-dlp/yt-dlp/releases/tag/2022.03.08 for the time-being as a workaround. The 2 releases are almost identical, so it shouldn't be an issue

Sorry to bother, but how do I rollback a version if installed using `pip`?

**Comment by mkaraki** [comment]
@madindehead 
I think you can rollback with following command
```
pip install -U yt-dlp==2022.03.08
```

**Comment by Leonetienne** [comment]
@mkaraki This has been bugging me for days, and, the faulty update was right in time with me re-installing my operating system, so I've been combing through my installation forever.
Thanks for this easy solution!
