### ISSUE TITLE
Faster but more limited --dump-json

### ISSUE THREAD

**Issue by VikoRifeo** [yt-dlp/yt-dlp#2997]
### Checklist

- [X] I'm reporting a feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.03.08.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

`--dump-json` does extra work to collect all available metadata about an item before listing it. This can be very slow. I just need URLs and (ideally) titles, both of which are available from the item list without doing any extra work per-item (we already have them by the time we check whether an item is in the download archive). So it would be convenient if there was a `--dump-short-json` option (or some other name) that reports less information, but earlier.

**Comment by pukkandan** [comment]
--flat-playlist

**Comment by VikoRifeo** [comment]
Thank you!
