### ISSUE TITLE
7plus DRM on most videos.

### ISSUE THREAD

**Issue by sourpatched** [yt-dlp/yt-dlp#2999]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.03.08.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Australia

### Description

Most videos are now DRM. 7plus is free to air channel that has started  to DRM the videos

### Verbose log

```shell
[7plus] STRF01-001: Downloading JSON metadata
[7plus] STRF01-001: Downloading m3u8 information
[7plus] STRF01-001: Downloading MPD manifest
[7plus] STRF01-001: Downloading MPD manifest
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[7plus] STRF01-001: Downloading JSON metadata
ERROR: [7plus] STRF01-001: This video is DRM protected
Traceback (most recent call last):
  File "/home/buzas/.local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1389, in wrapper
    return func(self, *args, **kwargs)
  File "/home/bob/.local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1473, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/home/bob/.local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1529, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/home/bob/.local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 2460, in process_video_result
    self.raise_no_formats(info_dict)
  File "/home/bob/.local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 970, in raise_no_formats
    raise ExtractorError(msg, video_id=info['id'], ie=info['extractor'],
yt_dlp.utils.ExtractorError: [7plus] STRF01-001: This video is DRM protected
```

**Comment by pukkandan** [comment]
1. That is not the full verbose log
2. What is the issue here? If the video is DRM protected, we can't download it. That is expected. Do you have any reason to believe the DRM warning is wrong?

**Comment by sourpatched** [comment]
> 1. That is not the full verbose log
> 
>     2. What is the issue here? If the video is DRM protected, we can't download it. That is expected. Do you have any reason to believe the DRM warning is wrong?

No i don't, wasn't sure if you're able to support removing DRM on sites that only have some DRM videos?

**Comment by pukkandan** [comment]
yt-dlp will work for the videos don't have DRM. Nothing to be done about the videos that do. If/when all  videos add DRM, we will remove the site from supported list

**Comment by sourpatched** [comment]
I was hoping this wasn't going to be the case since it's a free to air channel.
