### ISSUE TITLE
Some videos cannot be downloaded at a specified resolution, and they will only be downloaded at the highest resolution if parameters are added.

### ISSUE THREAD

**Issue by netlovehf** [yt-dlp/yt-dlp#3003]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.03.08.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

Some videos cannot be downloaded at a specified resolution, and they will only be downloaded at the highest resolution if parameters are added.

### Verbose log

```shell
yt-dlp.exe https://www.youtube.com/watch?v=8pEK-LoOCC4&t=6s -f299+140
[youtube] 8pEK-LoOCC4: Downloading webpage
[youtube] 8pEK-LoOCC4: Downloading android player API JSON
[info] 8pEK-LoOCC4: Downloading 1 format(s): 315+251
[info] Downloading video thumbnail 41 ...
[info] Writing video thumbnail 41 to: C:\Users\Administrator\Downloads\Vedio Talk\新品：全新来袭 N5105软路由 四口2.5G I225 B3网卡 NMVE硬盘-3840x2160.webp
[SubtitlesConvertor] There aren't any subtitles to convert
[download] Destination: C:\Users\Administrator\Downloads\Vedio Talk\新品：全新来袭 N5105软路由 四口2.5G I225 B3网卡 NMVE硬盘-3840x2160.f315.webm
[download]   4.3% of 776.29MiB at 11.10MiB/s ETA 01:06
```

**Comment by lvqcl** [comment]
https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command
