### ISSUE TITLE
Spurious/confusing warning when downloading Youtube video with live chat

### ISSUE THREAD

**Issue by mechanical-snail** [yt-dlp/yt-dlp#3006]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.03.08.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

When running `yt-dlp -vU --format=sb2 --write-subs --sub-langs=live_chat 'https://www.youtube.com/watch?v=PCy1IKPev4w'` (a premiered video with a live chat replay), yt-dlp displays what seems to be a spurious warning:

```
WARNING: Live chat download runs until the livestream ends. If you wish to download the video simultaneously, run a separate yt-dlp instance
```

The message was added in this commit: https://github.com/yt-dlp/yt-dlp/blame/08d30158ec8e7e08c1d83dcfde6dba18c95b2640/yt_dlp/downloader/youtube_live_chat.py#L25

and shows unconditionally when downloading a live chat replay, unless `skip_download` is active. I'm not sure what the message is warning about exactly, and the downloads of both the `live_chat` and the video (here `sb2`) proceed successfully.

Maybe this warning was only meant to display for *ongoing* live premieres, in which case the message makes sense.

### Verbose log

```shell
[debug] Command-line config: ['-vU', '--format=sb2', '--write-subs', '--sub-langs=live_chat', 'https://www.youtube.com/watch?v=PCy1IKPev4w']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.03.08.2 [e491d06d3]
[debug] Python version 3.8.10 (CPython 64bit) - Linux-5.11.0-27-generic-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4, rtmpdump 2.4
[debug] Optional libraries: brotli, Cryptodome, secretstorage, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.03.08.1, Current version: 2022.03.08.2
yt-dlp is up to date (2022.03.08.2)
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=PCy1IKPev4w
[youtube] PCy1IKPev4w: Downloading webpage
[youtube] PCy1IKPev4w: Downloading android player API JSON
[debug] Loading youtube-nsig.2fd2ad45 from cache
[debug] [youtube] Decrypted nsig jOwVsnBJ-fvpn4u6q80N => QffZD1ey18Celw
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[debug] Downloading subtitles: live_chat
[info] PCy1IKPev4w: Downloading 1 format(s): sb2
Deleting existing file Fastest CPU PC or Mainframe [PCy1IKPev4w].live_chat.json
[info] Writing video subtitles to: Fastest CPU PC or Mainframe [PCy1IKPev4w].live_chat.json
[debug] Invoking downloader on "https://www.youtube.com/watch?v=PCy1IKPev4w"
[youtube_live_chat] Downloading live chat
WARNING: Live chat download runs until the livestream ends. If you wish to download the video simultaneously, run a separate yt-dlp instance
[youtube_live_chat] Total fragments: unknown (live)
[download] Destination: Fastest CPU PC or Mainframe [PCy1IKPev4w].live_chat.json
[download] 100% of 287.71KiB in 00:01
[debug] Invoking downloader on "https://i.ytimg.com/sb/PCy1IKPev4w/storyboard3_L0/default.jpg?sqp=-oaymwENSDfyq4qpAwVwAcABBqLzl_8DBgjaou-OBg==&sigh=rs$AOn4CLCm9hQfHa-_cB_daBRwSC7ri9OPEw"
[mhtml] Total fragments: 1
[download] Destination: Fastest CPU PC or Mainframe [PCy1IKPev4w].mhtml
[download] 100% of 36.55KiB in 00:00
```

**Comment by pukkandan** [comment]
You are right. The warning is for currently live videos. I totally forgot that we supported live replays
