### ISSUE TITLE
next question from austria

### ISSUE THREAD

**Issue by khk58** [yt-dlp/yt-dlp#3007]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

I#M downloading the following playlist

'yt-dlp --download-archive ..\archive.txt  -i --geo-bypass -o "%%(title)s.%%(ext)s"  https://www.youtube.com/playlist?list=UUYQrOSpSj3qFaGHShcs4_zQ'.

In this playlist are some videos with _**different**_ urls, but the same names ('MAMUZ Wissen - Experimentelle Archäologie erklärt!'), which were produced on different dates.

So yt-dlp tells me at the second download of such a 'duplicate' name. that it has already been donwloaded, and marks that in the 'archive.txt'.

Dear all - what to do now ??

**Comment by nyuszika7h** [comment]
The download archive only contains the video IDs, so that's not the issue. The issue is that the file already exists. If you want to avoid identical titles being skipped as duplicates, include the ID in the output template (or just use the default one that already includes it: `-o "%%(title)s [%%(id)s].%%(ext)s".

**Comment by khk58** [comment]
I thought, yt-dlp would name the new file with 'name + (2)' or 'name + (3)' ....

**Comment by khk58** [comment]
I closed it unfortunately.

**Comment by pukkandan** [comment]
> I thought, yt-dlp would name the new file with 'name + (2)' or 'name + (3)' ....

No

**Comment by khk58** [comment]
You said 'no', but wouldn't that be nice for the whole community?

Or am I the first one who asked for that possibility?

**Comment by pukkandan** [comment]
Just add a unique id to the filename with `id` or `epoch`
