### ISSUE TITLE
yt-dlp --live-from-start feature

### ISSUE THREAD

**Issue by random29** [yt-dlp/yt-dlp#3008]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

Hello, thanks for your work!
Have a question - yt-dlp --live-from-start feature in Linux uses too much RAM, maybe caching all parts somehow, but on Windows it doesn't take RAM.
Is this a feature or not?
Both systems using latest 2022.03.08.1 version from pip install.

**Comment by pukkandan** [comment]
It shouldn't take much more RAM than normal downloads

**Comment by random29** [comment]
> It shouldn't take much more RAM than normal downloads

Should I submit it as bug? 'Cause for me it takes more than 16 gb of ram

**Comment by pukkandan** [comment]
yes, but I'm not sure the normal logs would help here.

@Lesmiscore, can u reproduce? or have any idea how we can debug this

**Comment by Lesmiscore** [comment]
a sort of, probably

https://discord.com/channels/807245652072857610/807245652072857613/952195812438450236

> -N 32 could freeze the system :pain:

https://discord.com/channels/807245652072857610/807245652072857613/952206614088282133 and the next message

> my VPS with 4 GB memory
> with 8GB memory laptop and file server, it usually won't be a problem

https://discord.com/channels/807245652072857610/807245652072857613/952207707639787530

> ~7MiB isn't probly
> but the process is killed by OOM Killer

context: I was trying to reproduce #3043.

Here's `yt-dlp -v` of the VPS in the quotes:

```
$ yt-dlp -v
[debug] Command-line config: ['-v']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.03.08.2 [e491d06d3]
[debug] Python version 3.9.10 (CPython 64bit) - Linux-5.13.0-30-generic-x86_64-with-glibc2.34
[debug] exe versions: ffmpeg 4.4 (setts), ffprobe 4.4
[debug] Optional libraries: Crypto, sqlite
[debug] Proxy map: {}
Usage: yt-dlp [OPTIONS] URL [URL...]

yt-dlp: error: You must provide at least one URL.
Type yt-dlp --help to see a list of all options.
```

Since --live-from-start for YT itself shouldn't take memory so much, I suspect there could be problem(s?) on parallel fragment downloads.

Anyway it looks like I have to try to reproduce it too.

**Comment by random29** [comment]
> a sort of, probably
> 
> https://discord.com/channels/807245652072857610/807245652072857613/952195812438450236
> 
> > -N 32 could freeze the system :pain:
> 
> https://discord.com/channels/807245652072857610/807245652072857613/952206614088282133 and the next message
> 
> > my VPS with 4 GB memory
> > with 8GB memory laptop and file server, it usually won't be a problem
> 
> https://discord.com/channels/807245652072857610/807245652072857613/952207707639787530
> 
> > ~7MiB isn't probly
> > but the process is killed by OOM Killer
> 
> context: I was trying to reproduce #3043.
> 
> Here's `yt-dlp -v` of the VPS in the quotes:
> 
> ```
> $ yt-dlp -v
> [debug] Command-line config: ['-v']
> [debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
> [debug] yt-dlp version 2022.03.08.2 [e491d06d3]
> [debug] Python version 3.9.10 (CPython 64bit) - Linux-5.13.0-30-generic-x86_64-with-glibc2.34
> [debug] exe versions: ffmpeg 4.4 (setts), ffprobe 4.4
> [debug] Optional libraries: Crypto, sqlite
> [debug] Proxy map: {}
> Usage: yt-dlp [OPTIONS] URL [URL...]
> 
> yt-dlp: error: You must provide at least one URL.
> Type yt-dlp --help to see a list of all options.
> ```
> 
> Since --live-from-start for YT itself shouldn't take memory so much, I suspect there could be problem(s?) on parallel fragment downloads.
> 
> Anyway it looks like I have to try to reproduce it too.
> 
> ![image](https://user-images.githubusercontent.com/10355528/158156507-6ad6a318-345b-47da-aa4e-7e405fbf6858.png)
> 
> @random29 Did you use `-N` option at that time? If yes, what value did you set?

Yes, I use it, N = 16. Tried without it - no noticable RAM drain. Guess that's there the problem. 
But man, without concurrent fragments stream loads quite slow, and this is not a problem on windows

**Comment by pukkandan** [comment]
> Yes, I use it, N = 16. Tried without it - no noticable RAM drain

In that case, I believe we have found the issue and the fix 👍 

@Lesmiscore You can directly commit the fix (that we discussed on discord) if your tests are giving good results. In future, it may be useful to cache a few fragments instead of reading everything back from disk, but that is low priority and we can address it later

**Comment by Lesmiscore** [comment]
@pukkandan Can I change it not to read fragments at download time completely?

```
diff --git a/yt_dlp/downloader/fragment.py b/yt_dlp/downloader/fragment.py
index 95fb2f9e7..9358ea6f7 100644
--- a/yt_dlp/downloader/fragment.py
+++ b/yt_dlp/downloader/fragment.py
@@ -133,19 +133,19 @@ class FragmentFD(FileDownloader):
         }
         success = ctx['dl'].download(fragment_filename, fragment_info_dict)
         if not success:
-            return False, None
+            return False
         if fragment_info_dict.get('filetime'):
             ctx['fragment_filetime'] = fragment_info_dict.get('filetime')
         ctx['fragment_filename_sanitized'] = fragment_filename
+        return True
+
+    def _read_fragment(self, ctx):
         try:
-            return True, self._read_fragment(ctx)
+            down, frag_sanitized = self.sanitize_open(ctx['fragment_filename_sanitized'], 'rb')
         except FileNotFoundError:
-            if not info_dict.get('is_live'):
+            if not ctx.get('live'):
                 raise
-            return False, None
-
-    def _read_fragment(self, ctx):
-        down, frag_sanitized = self.sanitize_open(ctx['fragment_filename_sanitized'], 'rb')
+            return False
         ctx['fragment_filename_sanitized'] = frag_sanitized
         frag_content = down.read()
         down.close()
@@ -467,11 +467,10 @@ class FragmentFD(FileDownloader):
                 headers['Range'] = 'bytes=%d-%d' % (byte_range['start'], byte_range['end'] - 1)
 
             # Never skip the first fragment
-            fatal = is_fatal(fragment.get('index') or (frag_index - 1))
-            count, frag_content = 0, None
+            fatal, count = is_fatal(fragment.get('index') or (frag_index - 1)), 0
             while count <= fragment_retries:
                 try:
-                    success, frag_content = self._download_fragment(ctx, fragment['url'], info_dict, headers)
+                    success = self._download_fragment(ctx, fragment['url'], info_dict, headers)
                     if not success:
                         return False, frag_index
                     break
@@ -497,7 +496,7 @@ class FragmentFD(FileDownloader):
                 ctx['dest_stream'].close()
                 self.report_error('Giving up after %s fragment retries' % fragment_retries)
                 return False, frag_index
-            return frag_content, frag_index
+            return True, frag_index
 
         def append_fragment(frag_content, frag_index, ctx):
             if not frag_content:
@@ -520,23 +519,23 @@ class FragmentFD(FileDownloader):
 
             def _download_fragment(fragment):
                 ctx_copy = ctx.copy()
-                frag_content, frag_index = download_fragment(fragment, ctx_copy)
-                return fragment, frag_content, frag_index, ctx_copy.get('fragment_filename_sanitized')
+                _, frag_index = download_fragment(fragment, ctx_copy)
+                return fragment, frag_index, ctx_copy.get('fragment_filename_sanitized')
 
             self.report_warning('The download speed shown is only of one thread. This is a known issue and patches are welcome')
             with tpe or concurrent.futures.ThreadPoolExecutor(max_workers) as pool:
-                for fragment, frag_content, frag_index, frag_filename in pool.map(_download_fragment, fragments):
+                for fragment, frag_index, frag_filename in pool.map(_download_fragment, fragments):
                     ctx['fragment_filename_sanitized'] = frag_filename
                     ctx['fragment_index'] = frag_index
-                    result = append_fragment(decrypt_fragment(fragment, frag_content), frag_index, ctx)
+                    result = append_fragment(decrypt_fragment(fragment, self._read_fragment(ctx)), frag_index, ctx)
                     if not result:
                         return False
         else:
             for fragment in fragments:
                 if not interrupt_trigger[0]:
                     break
-                frag_content, frag_index = download_fragment(fragment, ctx)
-                result = append_fragment(decrypt_fragment(fragment, frag_content), frag_index, ctx)
+                _, frag_index = download_fragment(fragment, ctx)
+                result = append_fragment(decrypt_fragment(fragment, self._read_fragment(ctx)), frag_index, ctx)
                 if not result:
                     return False
 ```

**Comment by pukkandan** [comment]
That is a bigger change since mhtml and ism also use the `_download_fragment` function. Can u make a PR?

**Comment by Lesmiscore** [comment]
Expected answer :sweat_smile: 
No problem
