### ISSUE TITLE
Stuck on "Last message repeated xxxx times" for a long while after stream ends

### ISSUE THREAD

**Issue by KaitoCross** [yt-dlp/yt-dlp#3013]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

How can I teach yt-dlp to end this "Last message repeated xxxx times" loop much sooner once the recorded YouTube stream ended? It often goes for 10-40 minutes AFTER the stream has ended and blocks further processing.
Example of end of last stream:
~~~~
frame=216481 fps= 60 q=-1.0 size= 1915904kB time=01:00:08.05 bitrate=4350.0kb  
[https @ 0x1be9000] Opening 'https://manifest.googlevideo.com/api/manifest/hls_playlist/expire/LONGURLWITHPRIVATEINFO/playlist/index.m3u8' for reading  
Last message repeated 3750 times (still counting as I type this)
~~~~

I'm merely using the --wait-for-video option

**Comment by pukkandan** [comment]
It has nothing to do with --wait-for-video. This is just how ffmpeg behaves for live streams. You can press Ctrl+C to end at any time, or wait for it to end by itself

**Comment by bashonly** [comment]
to mitigate this you can pass the `m3u8_hold_counters` option to ffmpeg, like so:

    --downloader-args "ffmpeg:-m3u8_hold_counters 12"

the value is how many times ffmpeg will reload an empty playlist before closing out of the stream. the default value is 1000, which is why it takes such a long time. a reasonable value is something like 12.

**Comment by KaitoCross** [comment]
> ```
> --downloader-args "ffmpeg:-m3u8_hold_counters 12"
> ```
This leads to the following error:
```
[download] Destination: 【Karaoke】 Ina Sing Sing Ina Ina Sing Sing 2022-03-10 23_00 [HJ5Zwzd6h18].mp4
Unrecognized option 'm3u8_hold_counters'.
Error splitting the argument list: Option not found


ERROR: ffmpeg exited with code 1
```

**Comment by bashonly** [comment]
in that case you will need to update to a newer version of ffmpeg if you want to use that arg. 4.4 or above
