### ISSUE TITLE
How to escape parenthesis in the metadata fields?

### ISSUE THREAD

**Issue by eexit** [yt-dlp/yt-dlp#3017]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

Hello,

Using this example: `%(uploader|Unknown)s`, I wonder how to escape `()` in the default value.
For instance:  `%(uploader|Unknown \(foo\))s`

Generally speaking, I'm trying to override/add missing metadata so I'm doing it this way: 

    --parse-metadata "%%(artist|%s)s:%%(meta_artist)s"

Where `%s` is replaced by a given artist value (which may contain parenthesis).
If you know a better way of doing this, it would be helpful.

Thanks!

**Comment by pukkandan** [comment]
> For instance: %(uploader|Unknown \(foo\))s

Not possible atm

> --parse-metadata "%%(artist|%s)s:%%(meta_artist)s"

But this can be achieved using:

```
--parse-metadata "Unknown (foo):%(meta_artist)s" --parse-metadata "%(artist|)s:%(meta_artist)s"
```

**Comment by eexit** [comment]
Thanks a lot @pukkandan!

**Comment by eexit** [comment]
Hi @pukkandan,

Quick question: how can I force a metadata value?
For instance, will this line force the artist to "Foo"?

```
--parse-metadata "Foo:%(meta_artist)s" --parse-metadata "%(artist)s:%(meta_artist)s"
```

Thanks!

**Comment by pukkandan** [comment]
Due to legacy reasons, `Foo` is interpretted as a field name here. Add a space to work around it

```
--parse-metadata " Foo: %(meta_artist)s"
```
