### ISSUE TITLE
Cant download from viki

### ISSUE THREAD

**Issue by BLSTR13** [yt-dlp/yt-dlp#3021]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.03.08.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Philippines

### Description

cant download from viki

### Verbose log

```shell
D:\ytdl>yt-dlp.exe -vU https://www.viki.com/videos/1165864v-is-this-love-checkmate-meeting-episode-1
[debug] Command-line config: ['-vU', 'https://www.viki.com/videos/1165864v-is-this-love-checkmate-meeting-episode-1']
[debug] User config "C:\Users\Cherri Estudillo\AppData\Roaming\yt-dlp\config.txt": ['-o', 'D:/ytdl/%(title)s.%(ext)s', '--no-mtime']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.03.08.1 [c0c2c57] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] exe versions: ffmpeg n5.0-5-g4769d77c8c-20220310 (setts), ffprobe n5.0-5-g4769d77c8c-20220310, phantomjs 2.1.1
[debug] Optional libraries: brotli, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.03.08.1, Current version: 2022.03.08.1
yt-dlp is up to date (2022.03.08.1)
[debug] [viki] Extracting URL: https://www.viki.com/videos/1165864v-is-this-love-checkmate-meeting-episode-1
[viki] 1165864v: Downloading video JSON
[viki] 1165864v: Downloading video streams JSON
Traceback (most recent call last):
  File "yt_dlp\extractor\common.py", line 735, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 3591, in urlopen
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 401: Unauthorized

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\extractor\common.py", line 617, in extract
  File "yt_dlp\extractor\viki.py", line 255, in _real_extract
  File "yt_dlp\extractor\viki.py", line 71, in _call_api
  File "yt_dlp\extractor\common.py", line 997, in _download_json
  File "yt_dlp\extractor\common.py", line 976, in _download_json_handle
  File "yt_dlp\extractor\common.py", line 768, in _download_webpage_handle
  File "yt_dlp\extractor\common.py", line 753, in _request_webpage
yt_dlp.utils.ExtractorError: Unable to download JSON metadata: HTTP Error 401: Unauthorized (caused by <HTTPError 401: 'Unauthorized'>); please report this issue on  https://github.com/yt-dlp/yt-dlp , filling out the "Broken site" issue template properly. Confirm you are on the latest version using  yt-dlp -U

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1389, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1459, in __extract_info
  File "yt_dlp\extractor\common.py", line 643, in extract
yt_dlp.utils.ExtractorError: [viki] 1165864v: Unable to download JSON metadata: HTTP Error 401: Unauthorized (caused by <HTTPError 401: 'Unauthorized'>); please report this issue on  https://github.com/yt-dlp/yt-dlp , filling out the "Broken site" issue template properly. Confirm you are on the latest version using  yt-dlp -U

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\__main__.py", line 19, in <module>
  File "yt_dlp\__init__.py", line 864, in main
  File "yt_dlp\__init__.py", line 854, in _real_main
  File "yt_dlp\YoutubeDL.py", line 3254, in download
  File "yt_dlp\YoutubeDL.py", line 3227, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1380, in extract_info
  File "yt_dlp\YoutubeDL.py", line 1407, in wrapper
  File "yt_dlp\utils.py", line 1088, in format_traceback
TypeError: format_exception() missing 2 required positional arguments: 'value' and 'tb'
[2860] Failed to execute script '__main__' due to unhandled exception!
```

**Comment by zackmark29** [comment]
Patched again
```
{'vcode': 6460, 'error': 'DRM playback unsupported', 'details': 'cannot serve non-drm content'}
```

**Comment by digiotaku** [comment]
Here same issue, 
![Screenshot_2](https://user-images.githubusercontent.com/74442422/157959437-1b63f5da-04ce-43da-9ed6-bf5d80436fe4.jpg)

try with multiple urls but it doesn't work.

**Comment by BLSTR13** [comment]
at first thats what it showed and then the one on the verbose log

**Comment by zackmark29** [comment]
> at first thats what it showed and then the one on the verbose log

Non-DRM method already patched again.

**Comment by BLSTR13** [comment]
?

**Comment by pandamoon21** [comment]
> ?

This one maybe, https://github.com/yt-dlp/yt-dlp/issues/2907
https://github.com/yt-dlp/yt-dlp/issues/2907#issuecomment-1060042978

**Comment by BLSTR13** [comment]
So uh what doew this means? Im not into coding and stuff

**Comment by zackmark29** [comment]
> So uh what does this means? Im not into coding and stuff

It means, Viki already patched the method again and it's not gonna work for now until somebody find another solution to download Non-DRM or Non-Protected stream/video.

**Comment by BLSTR13** [comment]
I already understand DRM, I just didnt understand what you said, anyways I understand now thanks!

**Comment by pukkandan** [comment]
@zackmark29 @nyuszika7h The underlying issue is same as https://github.com/yt-dlp/yt-dlp/issues/1379 + https://github.com/yt-dlp/yt-dlp/issues/2907, right? Should I close this as duplicate in favor of tracking those issues?

**Comment by zackmark29** [comment]
> @zackmark29 @nyuszika7h The underlying issue is same as #1379 + #2907, right? Should I close this as duplicate in favor of tracking those issues?

Yes
