### ISSUE TITLE
output redirected to file contains terminal sequences

### ISSUE THREAD

**Issue by flashdagger** [yt-dlp/yt-dlp#3023]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.03.08.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

When redirecting yt-dlp's output to a file terminal sequences are not suppressed. Either at the beginning or the end you will find strings like `]0;yt-dlp Concat started]0;yt-dlp Concat finished`.

Prerequisites to reproduce:
* run yt-dlp in POSIX shell (`$TERM=xterm-256color`)
* use yt-dlp version >= 2022.1.21
* the url must refer to a playlist
* parameter `--console-title` is set
* parameter `--concat-playlist` is set to _always_ or _multi_video_

### Verbose log

```shell
$ yt-dlp --no-config --verbose --console-title --dump-single-json https://www.youtube.com/channel/UCUBl5r0qPEY7130xVVWv6Zw > dump.json
[debug] Command-line config: ['--no-config', '--verbose', '--console-title', '--dump-single-json', 'https://www.youtube.com/channel/UCUBl5r0qPEY7130xVVWv6Zw']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8 (No ANSI), err utf-8, pref UTF-8
[debug] yt-dlp version 2022.03.08.2 [e491d06d3]
[debug] Python version 3.10.2 (CPython 64bit) - Linux-4.19.104-microsoft-standard-x86_64-with-glibc2.31
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4
[debug] Optional libraries: brotli, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [youtube:tab] Extracting URL: https://www.youtube.com/channel/UCUBl5r0qPEY7130xVVWv6Zw
[youtube:tab] UCUBl5r0qPEY7130xVVWv6Zw: Downloading webpage
[youtube:tab] A channel/user page was given. All the channel's videos will be downloaded. To download only the videos in the home page, add a "/featured" to the URL
[debug] [youtube:tab] Final URL: https://www.youtube.com/channel/UCUBl5r0qPEY7130xVVWv6Zw/videos
[download] Downloading playlist: Martin Schulz - Videos
[youtube:tab] playlist Martin Schulz - Videos: Downloading 0 videos
[download] Finished downloading playlist: Martin Schulz - Videos
```

**Comment by pukkandan** [comment]
Can't reproduce. And there are a few issues in your bug report:

> parameter --concat-playlist is set to always or multi_video

It isn't in the log you have given though. Even if it is, since there are 0 videos, it won't do anything

> $ yt-dlp --no-config --verbose --console-title --dump-single-json https://www.youtube.com/channel/UCUBl5r0qPEY7130xVVWv6Zw > dump.json

Since you are doing `--dump-single-json`, only the json is being redirected to the file, not the normal console output...

> strings like �]0;yt-dlp Concat started��]0;yt-dlp Concat finished�.

yt-dlp never prints "concat started"

**Comment by flashdagger** [comment]
> > parameter --concat-playlist is set to always or multi_video
> 
> It isn't in the log you have given though. Even if it is, since there are 0 videos, it won't do anything

It does not to be set because the default is `multi_video`

> > $ yt-dlp --no-config --verbose --console-title --dump-single-json https://www.youtube.com/channel/UCUBl5r0qPEY7130xVVWv6Zw > dump.json
> 
> Since you are doing `--dump-single-json`, only the json is being redirected to the file, not the normal console output...

It is. But so are the terminal sequences. I assume these are for setting the console title.

> > strings like �]0;yt-dlp Concat started��]0;yt-dlp Concat finished�.
> 
> yt-dlp never prints "concat started"

It does in my case. After some research I could track it down to the `report_progress()` method of `PostProcessor` class.

It prints the events from the progress hooks using `to_console_title()`. So class `FFmpegConcatPP` where the `Concat` is derived from is executed on the playlist videos.

The message of `to_console_title()` is then printed to `self._screen_file` which in this case is redirected to a file.

**Comment by pukkandan** [comment]
I was able to reproduce. The situation is a bit more complicated than just the console title printing to file. With other combination of options, I also got the download progress bar to wrongly get printed to file

**Comment by pukkandan** [comment]
In UNIX, console title is set by sending a code to stdout. I can't figure out how to change the title when stdout is being piped to a file. So for now, I'll just forcefully disable `--console-title` in such cases

**Comment by Lesmiscore** [comment]
It's not necessarily written to stdout. stderr works too as long as it points to (S)TTY.

![image](https://user-images.githubusercontent.com/10355528/157880933-cecc7566-2251-46ea-8e41-941f5de19367.png)
![image](https://user-images.githubusercontent.com/10355528/157881364-5d89dbf7-263c-46ad-81a8-2ce0cf96867e.png)

**Comment by pukkandan** [comment]
Yes, but both can be redirected

**Comment by flashdagger** [comment]
You could create a file descriptor that will write to the controlling terminal of the process:

```
if os.name != "nt":
    console_out = open(os.ctermid(), "w")
```

**Comment by pukkandan** [comment]
I didn't know about `ctermid`. Do you know what happens with it when there is no attached terminal?

**Comment by pukkandan** [comment]
Perfect. We can catch and check the error code. Due to https://github.com/yt-dlp/yt-dlp/commit/cf4f42cb9776eaa3166d2d234c3ec7651f05d7a9, this is the only thing that'd need to be changed: https://github.com/yt-dlp/yt-dlp/blob/592b748582f67309ac79670ba6a4bb7a62c4506f/yt_dlp/YoutubeDL.py#L548-L549
