### ISSUE TITLE
Can't download a video stream. It's live at the time point of reporting.

### ISSUE THREAD

**Issue by TheK0tYaRa** [yt-dlp/yt-dlp#3024]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.03.08.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Ukraine

### Description

I have attempted to list formats for a video stream on youtube. To attempt downloading later. It did not succeed. I do not know why as i remember downloading a video stream via ffmpeg before.

### Verbose log

```shell
$ yt-dlp -vU --list-formats "https://youtu.be/ttxYyl-Q_oY"
[debug] Command-line config: ['-vU', '--list-formats', 'https://youtu.be/ttxYyl-Q_oY']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.03.08.1 [c0c2c57d3]
[debug] Python version 3.10.2 (CPython 64bit) - Linux-5.15.27-1-lts-x86_64-with-glibc2.35
[debug] exe versions: ffmpeg 5.0 (setts), ffprobe 5.0, phantomjs 3.0.0, rtmpdump 2.4
[debug] Optional libraries: Crypto, mutagen, sqlite
[debug] Proxy map: {}
Latest version: 2022.03.08.1, Current version: 2022.03.08.1
yt-dlp is up to date (2022.03.08.1)
[debug] [youtube] Extracting URL: https://youtu.be/ttxYyl-Q_oY
[youtube] ttxYyl-Q_oY: Downloading webpage
[youtube] ttxYyl-Q_oY: Downloading android player API JSON
[youtube] ttxYyl-Q_oY: Downloading m3u8 information
WARNING: [youtube] Failed to download m3u8 information: <urlopen error [Errno 111] Connection refused>
[youtube] ttxYyl-Q_oY: Downloading m3u8 information
WARNING: [youtube] Failed to download m3u8 information: <urlopen error [Errno 111] Connection refused>
ERROR: [youtube] ttxYyl-Q_oY: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp , filling out the "Broken site" issue template properly. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1389, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1473, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1529, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 2460, in process_video_result
    self.raise_no_formats(info_dict)
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 970, in raise_no_formats
    raise ExtractorError(msg, video_id=info['id'], ie=info['extractor'],
yt_dlp.utils.ExtractorError: [youtube] ttxYyl-Q_oY: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp , filling out the "Broken site" issue template properly. Confirm you are on the latest version using  yt-dlp -U
```

**Comment by dirkf** [comment]
Currently "Private video. Sign in if you've been granted access to this video".

**Comment by TheK0tYaRa** [comment]
Yes. That's why i wanted to save it live.

**Comment by coletdjnz** [comment]
I briefly checked this earlier when it was live and it worked for me. Likely a network issue your side.

**Comment by coletdjnz** [comment]
> > Likely a network issue your side.
> 
> I will be appreciative if you check it currently with [this stream](https://youtu.be/5yN-lqjYpGE) .
> As i have tried doing such just now and the result is quite the same.

Hmm still works for me 😕

Possibly try checking that you can ping `manifest.googlevideo.com`

To me it sounds like a DNS issue. I recall similar happened to someone else and they found it was blocked on their pihole.

**Comment by TheK0tYaRa** [comment]
It does ping, but i will check pihole

**Comment by TheK0tYaRa** [comment]
Please do suggest me how to trace any connection that yt-dlp does so that i know what to seek for xD

**Comment by pukkandan** [comment]
`--print-traffic`

**Comment by TheK0tYaRa** [comment]
yeah basically it was pihole blocking `manifest.googlevideo.com`
