### ISSUE TITLE
oreilly.com downloading incomplete videos

### ISSUE THREAD

**Issue by Cerulean-Code** [yt-dlp/yt-dlp#3027]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.03.08.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

UK

### Description

When trying to download from this url: [1.1 Why would I take the Oracle Certified Associate Java Programmer Exam](https://learning.oreilly.com/videos/oca-java-se/9780134427201/9780134427201-OCA8_M01_L01_01/)
yt-dlp downloads a version of the video that is cut off after 1 minute while using cookies

I can provide cookies if anyone wants to take a look at this.

### Verbose log

```shell
sh-5.1$ python3 yt-dlp -vU  --cookies cookies.txt https://learning.oreilly.com/videos/oca-java-se/9780134427201/9780134427201-OCA8_M01_L01_01/
[debug] Command-line config: ['-vU', '--cookies', 'cookies.txt', 'https://learning.oreilly.com/videos/oca-java-se/9780134427201/9780134427201-OCA8_M01_L01_01/']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.03.08.1 [c0c2c57d3] (zip)
[debug] Lazy loading extractors is disabled
[debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
[debug] Python version 3.9.9 (CPython 64bit) - Linux-5.13.0-30-generic-x86_64-with-glibc2.33
[debug] exe versions: ffmpeg 4.3.3 (fdk), ffprobe 4.3.3
[debug] Optional libraries: sqlite
[debug] Proxy map: {}
Latest version: 2022.03.08.1, Current version: 2022.03.08.1
yt-dlp is up to date (2022.03.08.1)
[debug] [safari] Extracting URL: https://learning.oreilly.com/videos/oca-java-se/9780134427201/9780134427201-OCA8_M01_L01_01/
[debug] [Kaltura] Extracting URL: https://cdnapisec.kaltura.com/html5/html5lib/v2.37.1/mwEmbedFrame.php?wid=_1926081&uiconf_id=29375172&flashvars%5BreferenceId%5D=9780134427201-OCA8_M01_L01_01
[Kaltura] 9780134427201-OCA8_M01_L01_01: Downloading webpage
[Kaltura] 0_d43u8x5o: Downloading video info JSON
[Kaltura] 0_d43u8x5o: Checking mp4-14340 URL
[Kaltura] 0_d43u8x5o: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 0_d43u8x5o: Downloading 1 format(s): mp4-14340
[debug] Invoking downloader on "http://cdnapi.kaltura.com/p/1926081/sp/192608100/playManifest/entryId/0_d43u8x5o/format/url/protocol/http/flavorId/0_pnhv1pc9"
[download] 1.1 Why would I take the Oracle Certified Associate Java Programmer Exam [0_d43u8x5o].mp4 has already been downloaded
[download] 100% of 96.72MiB
```

**Comment by pukkandan** [comment]
Cookies are not supported for this site https://github.com/yt-dlp/yt-dlp/issues/1027. Try with username+password
