### ISSUE TITLE
[Crunchyroll] Edit Metadata Season 

### ISSUE THREAD

**Issue by CZeil** [yt-dlp/yt-dlp#3028]
### Checklist

- [X] I'm reporting a feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.03.08.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

Currently for series that have only one season the season number appears as 0 (when I use %(season_number)s), this request is to change this to 1. Unless these are problems directly from the Crunchyroll website.

**Comment by pukkandan** [comment]
Open a "Site feature request" with all necessary details

**Comment by CZeil** [comment]
> Open a "Site feature request" with all necessary details

Ok
