### ISSUE TITLE
[Request] TikTok Downloader

### ISSUE THREAD

**Issue by seniorm0ment** [yt-dlp/yt-dlp#303]
Requesting a downloader for TikTok, it just tries a generic download then fails.

**Comment by pukkandan** [comment]
There is already a tikok extractor. If you are having issues with some URL, open a bug report with the necessary details. DONOT ignore the template

**Comment by pukkandan** [comment]
Whatever the reason, I can't do anything without more details. Open a new issue with the necessary details such as URL and verbose log
