### ISSUE TITLE
[Feature Request] Using plugin to override an existing extractor.

### ISSUE THREAD

**Issue by brpy** [yt-dlp/yt-dlp#304]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

Is it possible to override an already supported extractor with a custom extractor using plugin?

**Comment by pukkandan** [comment]
Not currently possible, but this can be easily implemented

**Comment by pukkandan** [comment]
Actually it looks like it is possible by using the same class name. But this is not intentional behavior (and I will disable this). The correct way should be by using the same `_VALID_URL` (which I'll implement)
