### ISSUE TITLE
[Crunchyroll] Edit Metadata Season

### ISSUE THREAD

**Issue by CZeil** [yt-dlp/yt-dlp#3040]
### Checklist

- [X] I'm reporting a site feature request
- [X] I've verified that I'm running yt-dlp version **2022.03.08.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

US

### Example URLs

https://www.crunchyroll.com/parasyte-the-maxim-/episode-1-metamorphosis-662583

### Description

When I use in my output template %(season_number)s for series that only have one season it appears as 0 and I wanted to see if you can update it to 1. The series that have more than one season if it appears well, if it can identify the seasons (1, 2, 3, etc).

For example the verbose log shows what I say, resulting in the link I attached this:
Parasyte -the maxim- (S0E1) - Metamorphosis.mp4

### Verbose log

```shell
[debug] Command-line config: ['--config-location', 'bin/crunchyroll.conf', 'https://www.crunchyroll.com/parasyte-the-maxim-/episode-1-metamorphosis-662583']
[debug] | Config "bin/crunchyroll.conf": ['-f', '(b[height<=1080])', '--extractor-args', 'crunchyroll:hardsub=enUS', '-o', 'storage/external-1/%(extractor_key)s/%(uploader)s/%(series)s (S%(season_number)sE%(episode_number)s) - %(episode)s.%(ext)s', '-n', '--downloader', 'm3u8:aria2c', '--add-metadata', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.03.08.1 [c0c2c57d3]
[debug] Python version 3.10.2 (CPython 32bit) - Linux-4.9.190+-armv7l-with-libc
[debug] exe versions: ffmpeg 5.0 (setts), ffprobe 5.0
[debug] Optional libraries: brotli, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[crunchyroll] Getting session id
[crunchyroll] Logging in
[debug] [crunchyroll] Extracting URL: https://www.crunchyroll.com/parasyte-the-maxim-/episode-1-metamorphosis-662583
[crunchyroll] 662583: Downloading webpage
[crunchyroll] 662583: Downloading adaptive_hls-audio-jaJP-hardsub-enUS information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[crunchyroll] 662583: Downloading media info
WARNING: [crunchyroll] Unable to download XML: HTTP Error 404: Not Found
[info] 662583: Downloading 1 format(s): adaptive_hls-audio-jaJP-hardsub-enUS-8119-1
[debug] Invoking downloader on "https://pl.crunchyroll.com/evs1/a9978adb04c865707e49027fa0eb3b90/assets/dnt2yqadg5wwmk4_2098097.mp4/index-v1-a1.m3u8?Expires=1647195347&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9wbC5jcnVuY2h5cm9sbC5jb20vZXZzMS9hOTk3OGFkYjA0Yzg2NTcwN2U0OTAyN2ZhMGViM2I5MC9hc3NldHMvZG50MnlxYWRnNXd3bWs0XyoubTN1OD8qIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNjQ3MTk1MzQ3fX19XX0_&Signature=f5uzIkKqi-hWpl-a7RgJQ4ztEgCw5cjjmIm-U3yQZBO8SiCQqhk3oGOAEHAav909t-M0petHOpdvLbcIApIXs054pGeCEk4xbWkr0BXYg0A67W1zzBNZlaIfDYjx~fLigv5X~aXQLO9FCd60SZxWYEZjdO471bXfBiooWjuawpLPn47GuPhtHJgFKqqIkGyQ9qwVMynoCtkpz~p-txKirUFH6BV9vHN7mIB-8D1fyWO~W9MsM0YYYpAsGOBAqkyjimCFkHYwf3ERz2ooOu16Gq-Y7st-TIMoU2gdz-TU3g1LSJ~Kt9meOL-2uIlWPbEJSAtqVD2wnwYuPnFLnKRH2w__&Key-Pair-Id=APKAJMWSQ5S7ZB3MF5VA&cdn=fy-prod"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Fragment downloads will be delegated to aria2c
[hlsnative] Total fragments: 686
[download] Destination: storage/external-1/Crunchyroll/ntv/Parasyte -the maxim- (S0E1) - Metamorphosis.mp4
[debug] aria2c command line: aria2c -c --console-log-level=warn --summary-interval=0 --download-result=hide --http-accept-gzip=true --file-allocation=none -x16 -j16 -s16 --allow-overwrite=true --allow-piece-length-change=true --header 'User-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36' --header 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8' --header 'Accept-encoding: gzip, deflate, br' --header 'Accept-language: en-us,en;q=0.5' --header 'Sec-fetch-mode: navigate' --header 'Cookie: session_id=62e579c6a1dce84c0085bc9508c3ad48; __cf_bm=0qUzMNH0AKmKyBfunDO4cUwUFvZwn2_GFPu7fHY57nc-1647022545-0-AanxnR4yaZANNXhMJsACwrGPFHzgtk6fUHLusIUHknbLhZZ9AQXlNtIEuTpCiPQ88/v9Ji6468VsUMZJz82fEWU7vKIG1yUBpASDbWBJmaks; etp_rt=4df10f29-ede9-4bd1-862b-bd40ca549149; __cfruid=9534dff4b93e57f2f4fce5f0bbfcbb76e89cbbe2-1647022544; c_visitor=35021ccb-ff79-444e-a4a1-9c725b9712df' --check-certificate=true --remote-time=true --show-console-readout=true --dir ./storage/external-1/Crunchyroll/ntv/ --auto-file-renaming=false --file-allocation=none --uri-selector=inorder -i 'storage/external-1/Crunchyroll/ntv/Parasyte -the maxim- (S0E1) - Metamorphosis.mp4.part.frag.urls'
```

**Comment by CZeil** [comment]
> ### Checklist
> * [x]  I'm reporting a site feature request
> * [x]  I've verified that I'm running yt-dlp version **2022.03.08.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
> * [x]  I've checked that all provided URLs are alive and playable in a browser
> * [x]  I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
> * [x]  I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
> * [x]  I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required
> 
> ### Region
> US
> 
> ### Example URLs
> https://www.crunchyroll.com/parasyte-the-maxim-/episode-1-metamorphosis-662583
> 
> ### Description
> When I use in my output template %(season_number)s for series that only have one season it appears as 0 and I wanted to see if you can update it to 1. The series that have more than one season if it appears well, if it can identify the seasons (1, 2, 3, etc).
> 
> For example the verbose log shows what I say, resulting in the link I attached this: Parasyte -the maxim- (S0E1) - Metamorphosis.mp4
> 
> ### Verbose log
> ```shell
> [debug] Command-line config: ['--config-location', 'bin/crunchyroll.conf', 'https://www.crunchyroll.com/parasyte-the-maxim-/episode-1-metamorphosis-662583']
> [debug] | Config "bin/crunchyroll.conf": ['-f', '(b[height<=1080])', '--extractor-args', 'crunchyroll:hardsub=enUS', '-o', 'storage/external-1/%(extractor_key)s/%(uploader)s/%(series)s (S%(season_number)sE%(episode_number)s) - %(episode)s.%(ext)s', '-n', '--downloader', 'm3u8:aria2c', '--add-metadata', '-v']
> [debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
> [debug] yt-dlp version 2022.03.08.1 [c0c2c57d3]
> [debug] Python version 3.10.2 (CPython 32bit) - Linux-4.9.190+-armv7l-with-libc
> [debug] exe versions: ffmpeg 5.0 (setts), ffprobe 5.0
> [debug] Optional libraries: brotli, Cryptodome, mutagen, sqlite, websockets
> [debug] Proxy map: {}
> [crunchyroll] Getting session id
> [crunchyroll] Logging in
> [debug] [crunchyroll] Extracting URL: https://www.crunchyroll.com/parasyte-the-maxim-/episode-1-metamorphosis-662583
> [crunchyroll] 662583: Downloading webpage
> [crunchyroll] 662583: Downloading adaptive_hls-audio-jaJP-hardsub-enUS information
> [debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
> [crunchyroll] 662583: Downloading media info
> WARNING: [crunchyroll] Unable to download XML: HTTP Error 404: Not Found
> [info] 662583: Downloading 1 format(s): adaptive_hls-audio-jaJP-hardsub-enUS-8119-1
> [debug] Invoking downloader on "https://pl.crunchyroll.com/evs1/a9978adb04c865707e49027fa0eb3b90/assets/dnt2yqadg5wwmk4_2098097.mp4/index-v1-a1.m3u8?Expires=1647195347&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9wbC5jcnVuY2h5cm9sbC5jb20vZXZzMS9hOTk3OGFkYjA0Yzg2NTcwN2U0OTAyN2ZhMGViM2I5MC9hc3NldHMvZG50MnlxYWRnNXd3bWs0XyoubTN1OD8qIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNjQ3MTk1MzQ3fX19XX0_&Signature=f5uzIkKqi-hWpl-a7RgJQ4ztEgCw5cjjmIm-U3yQZBO8SiCQqhk3oGOAEHAav909t-M0petHOpdvLbcIApIXs054pGeCEk4xbWkr0BXYg0A67W1zzBNZlaIfDYjx~fLigv5X~aXQLO9FCd60SZxWYEZjdO471bXfBiooWjuawpLPn47GuPhtHJgFKqqIkGyQ9qwVMynoCtkpz~p-txKirUFH6BV9vHN7mIB-8D1fyWO~W9MsM0YYYpAsGOBAqkyjimCFkHYwf3ERz2ooOu16Gq-Y7st-TIMoU2gdz-TU3g1LSJ~Kt9meOL-2uIlWPbEJSAtqVD2wnwYuPnFLnKRH2w__&Key-Pair-Id=APKAJMWSQ5S7ZB3MF5VA&cdn=fy-prod"
> [hlsnative] Downloading m3u8 manifest
> [hlsnative] Fragment downloads will be delegated to aria2c
> [hlsnative] Total fragments: 686
> [download] Destination: storage/external-1/Crunchyroll/ntv/Parasyte -the maxim- (S0E1) - Metamorphosis.mp4
> [debug] aria2c command line: aria2c -c --console-log-level=warn --summary-interval=0 --download-result=hide --http-accept-gzip=true --file-allocation=none -x16 -j16 -s16 --allow-overwrite=true --allow-piece-length-change=true --header 'User-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36' --header 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8' --header 'Accept-encoding: gzip, deflate, br' --header 'Accept-language: en-us,en;q=0.5' --header 'Sec-fetch-mode: navigate' --header 'Cookie: session_id=62e579c6a1dce84c0085bc9508c3ad48; __cf_bm=0qUzMNH0AKmKyBfunDO4cUwUFvZwn2_GFPu7fHY57nc-1647022545-0-AanxnR4yaZANNXhMJsACwrGPFHzgtk6fUHLusIUHknbLhZZ9AQXlNtIEuTpCiPQ88/v9Ji6468VsUMZJz82fEWU7vKIG1yUBpASDbWBJmaks; etp_rt=4df10f29-ede9-4bd1-862b-bd40ca549149; __cfruid=9534dff4b93e57f2f4fce5f0bbfcbb76e89cbbe2-1647022544; c_visitor=35021ccb-ff79-444e-a4a1-9c725b9712df' --check-certificate=true --remote-time=true --show-console-readout=true --dir ./storage/external-1/Crunchyroll/ntv/ --auto-file-renaming=false --file-allocation=none --uri-selector=inorder -i 'storage/external-1/Crunchyroll/ntv/Parasyte -the maxim- (S0E1) - Metamorphosis.mp4.part.frag.urls'
> ```

**Comment by Bricio** [comment]
Easier fix ever?

https://github.com/yt-dlp/yt-dlp/blob/a825ffbffa0bea322e3ccb44c6f8e01d8d9572fb/yt_dlp/extractor/crunchyroll.py#L620-L622

Just change default to 1?

**Comment by pukkandan** [comment]
As far as I can tell, the website never calls it Season 1. Moreover, the webpage explicitly states that this is season_number=0

> `"partOfSeason":{"@type":"TVSeason","@id":"https:\/\/www.crunchyroll.com\/parasyte-the-maxim-","name":"Parasyte -the maxim-","seasonNumber":"0"}`

So there is nothing to be done
