### ISSUE TITLE
Support for wasd.tv?

### ISSUE THREAD

**Issue by mesb1** [yt-dlp/yt-dlp#3041]
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.03.08.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Europe

### Example URLs

https://wasd.tv/StasSatori?record=919135
https://wasd.tv/spacemita/videos
https://wasd.tv/spacemita/videos?record=907755
https://wasd.tv/spacemita/clips
https://wasd.tv/spacemita/clips?clip=26804

### Description

Hi.
It would be nice to add wasd.tv support.
For now it looks like only some patches for youtube-dl doing it.

https://gitea.datahoarding.agency/ZenulAbidin/youtube-dl/commit/cdf98a34eae6a6d31f4b2c5a9ef36cace4cb3d92
https://copr.fedorainfracloud.org/coprs/vr5/wasd.tv/

### Verbose log

```shell
./yt-dlp -vU "https://wasd.tv/StasSatori?record=919135"
[debug] Command-line config: ['-vU', 'https://wasd.tv/StasSatori?record=919135']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.03.08.1 [c0c2c57d3] (zip)
[debug] Python version 3.10.2 (CPython 64bit) - Linux-5.16.12-200.fc35.x86_64-x86_64-with-glibc2.34
[debug] exe versions: ffmpeg 4.4.1 (setts), ffprobe 4.4.1
[debug] Optional libraries: Crypto, sqlite
[debug] Proxy map: {}
Latest version: 2022.03.08.1, Current version: 2022.03.08.1
yt-dlp is up to date (2022.03.08.1)
[debug] [generic] Extracting URL: https://wasd.tv/StasSatori?record=919135
[generic] StasSatori?record=919135: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] StasSatori?record=919135: Downloading webpage
[generic] StasSatori?record=919135: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://wasd.tv/StasSatori?record=919135
Traceback (most recent call last):
  File "/home/anleal/./yt-dlp/yt_dlp/YoutubeDL.py", line 1389, in wrapper
    return func(self, *args, **kwargs)
  File "/home/anleal/./yt-dlp/yt_dlp/YoutubeDL.py", line 1459, in __extract_info
    ie_result = ie.extract(url)
  File "/home/anleal/./yt-dlp/yt_dlp/extractor/common.py", line 617, in extract
    ie_result = self._real_extract(url)
  File "/home/anleal/./yt-dlp/yt_dlp/extractor/generic.py", line 3985, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://wasd.tv/StasSatori?record=919135
```

**Comment by ZenulAbidin** [comment]
Hey guys, I'm the owner of the gitea.datahoarding.agency fork mentioned in the OP. My Gitea instance is currently down, to free up memory for some other services of mine, but I will reupload it on Gitlab shortly.
