### ISSUE TITLE
How to download all available subtitles and two auto generated subtitles

### ISSUE THREAD

**Issue by snwefly** [yt-dlp/yt-dlp#3042]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

`--sub-lang "en.*,ja"` works globally so its ignore native other  language subtitles

Is there any way to use` --all-subs`  and `--write-auto-subs` (en,ja) for two specific languages at the same time?

Thanks

**Comment by pukkandan** [comment]
Not currently possible https://github.com/yt-dlp/yt-dlp/issues/2262
