### ISSUE TITLE
How to download twitter videos without Emoji file name?

### ISSUE THREAD

**Issue by kxxc** [yt-dlp/yt-dlp#3047]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

How to download twitter videos without Emoji file name?
But also keeps the original words?

thanks!

**Comment by pukkandan** [comment]
--restrict-filename

**Comment by kxxc** [comment]
> --restrict-filename

Thank you for your solution, but it can't support non-English words 😢

**Comment by pukkandan** [comment]
Try `--replace-in-metadata title "[\U00010000-\U0010ffff]" ""`

See [this gist](https://gist.github.com/Alex-Just/e86110836f3f93fe7932290526529cd1?permalink_comment_id=3208085#gistcomment-3208085) for regexes that cover even more emojis

**Comment by error-reporting** [comment]
try --replace-in-metadata "video:title" " ?[\U00010000-\U0010ffff]+" ""

**Comment by kxxc** [comment]
> try --replace-in-metadata "video:title" " ?[\U00010000-\U0010ffff]+" ""

amazing

**Comment by kxxc** [comment]
> try --replace-in-metadata "video:title" " ?[\U00010000-\U0010ffff]+" ""

nice, but still some emoji exist like ⬇️

**Comment by error-reporting** [comment]
send me the URL that has ⬇️ like you said

**Comment by error-reporting** [comment]
--replace-in-metadata "video:title" " ?[\U0002B07-\U0010ffff]+" ""

**Comment by error-reporting** [comment]
try --replace-in-metadata "video:title" " ?[\U00002B07-\U0010ffff]+" ""

**Comment by kxxc** [comment]
> do you need Greek characters in your filename

is there a list that I could pick up the code I need?

I'm using Big5, zh-tw

**Comment by error-reporting** [comment]
> > do you need Greek characters in your filename
> 
> is there a list that I could pick up the code I need?
> 
> I'm using Big5, zh-tw

character set and language is irrelevant look at the question above

**Comment by sebma** [comment]
> > > do you need Greek characters in your filename
> > 
> > 
> > is there a list that I could pick up the code I need?
> > I'm using Big5, zh-tw
> --replace-in-metadata "video:title" " ?[\U00002B07-\U00002E7F]+" ""
> --replace-in-metadata "video:title" " ?[\U0000U+2FF0-\U0000U+2FFF]+" ""
> --replace-in-metadata "video:title" " ?[\U00002B00-\U0000DFFF]+" ""
> --replace-in-metadata "video:title" " ?[\U0000E000-\U0000F8FF]+" ""
> --replace-in-metadata "video:title" " ?[\U0000FE00-\U0000FE2F]+" ""
> --replace-in-metadata "video:title" " ?[\U0000FF00-\U0000FFFF]+" ""
> --replace-in-metadata "video:title" " ?[\U00010B40-\U0010ffff]+" ""

Can you please implement a new `--strip-emojis` option for that ?

**Comment by bashonly** [comment]
@sebma you can do it yourself. add an alias to your config file

```
--alias strip-emojis '--replace-in-metadata "video:title" " ?[\U00002B07-\U00002E7F]+" "" --replace-in-metadata "video:title" " ?[\U0000U+2FF0-\U0000U+2FFF]+" "" --replace-in-metadata "video:title" " ?[\U00002B00-\U0000DFFF]+" "" --replace-in-metadata "video:title" " ?[\U0000E000-\U0000F8FF]+" "" --replace-in-metadata "video:title" " ?[\U0000FE00-\U0000FE2F]+" "" --replace-in-metadata "video:title" " ?[\U0000FF00-\U0000FFFF]+" "" --replace-in-metadata "video:title" " ?[\U00010B40-\U0010ffff]+" ""'
```

**Comment by sebma** [comment]
> [@sebma](https://github.com/sebma) you can do it yourself. add an alias to your config file
> 
> ```
> --alias strip-emojis '--replace-in-metadata "video:title" " ?[\U00002B07-\U00002E7F]+" "" --replace-in-metadata "video:title" " ?[\U0000U+2FF0-\U0000U+2FFF]+" "" --replace-in-metadata "video:title" " ?[\U00002B00-\U0000DFFF]+" "" --replace-in-metadata "video:title" " ?[\U0000E000-\U0000F8FF]+" "" --replace-in-metadata "video:title" " ?[\U0000FE00-\U0000FE2F]+" "" --replace-in-metadata "video:title" " ?[\U0000FF00-\U0000FFFF]+" "" --replace-in-metadata "video:title" " ?[\U00010B40-\U0010ffff]+" ""'
> ```

I was not aware of yt-dlp aliases, I'll do that, thanks a lot 👍

**Comment by sebma** [comment]
@bashonly The alias you gave me returns an error message : 
```shell
$ grep ^--alias.*emojis ~/.config/yt-dlp.conf
--alias strip-emojis '--replace-in-metadata "video:title" " ?[\U00002B07-\U00002E7F]+" "" --replace-in-metadata "video:title" " ?[\U0000U+2FF0-\U0000U+2FFF]+" "" --replace-in-metadata "video:title" " ?[\U00002B00-\U0000DFFF]+" "" --replace-in-metadata "video:title" " ?[\U0000E000-\U0000F8FF]+" "" --replace-in-metadata "video:title" " ?[\U0000FE00-\U0000FE2F]+" "" --replace-in-metadata "video:title" " ?[\U0000FF00-\U0000FFFF]+" "" --replace-in-metadata "video:title" " ?[\U00010B40-\U0010ffff]+" ""'
$ yt-dlp -e https://youtu.be/GJzJ0zXoM7k
L'ÉVANGILE : LA RÉVÉLATION DE CHRIST 🔥🔥🔥🔥
$ yt-dlp -e https://youtu.be/GJzJ0zXoM7k --strip-emojis

Usage: yt-dlp [OPTIONS] URL [URL...]

yt-dlp: error: --replace-in-metadata title ' ?[\U0000U+2FF0-\U0000U+2FFF]+' '' is invalid; incomplete escape \U0000 at position 3
$
```

**Comment by sebma** [comment]
> --replace-in-metadata "video:title" " ?[\U0000U+2FF0-\U0000U+2FFF]+" ""

@error-reporting It seems this specific line in incorrect : 
```shell
$ yt-dlp -e https://youtu.be/GJzJ0zXoM7k --replace-in-metadata "video:title" " ?[\U0000U+2FF0-\U0000U+2FFF]+" ""

Usage: yt-dlp.exe [OPTIONS] URL [URL...]

yt-dlp.exe: error: --replace-in-metadata title " ?[\U0000U+2FF0-\U0000U+2FFF]+" "" is invalid; incomplete escape \U0000 at position 3
$
```
Do you have the correct regexp ?

**Comment by error-reporting** [comment]
@sebma change these --replace-in-metadata "video:title" " ?[\U00002B07-\U00002E7F]+" ""
        --replace-in-metadata "video:title" " ?[\U0000U+2FF0-\U0000U+2FFF]+" ""
        --replace-in-metadata "video:title" " ?[\U00002B00-\U0000DFFF]+" ""
        --replace-in-metadata "video:title" " ?[\U0000E000-\U0000F8FF]+" ""
        --replace-in-metadata "video:title" " ?[\U0000FE00-\U0000FE2F]+" ""
        --replace-in-metadata "video:title" " ?[\U0000FF00-\U0000FFFF]+" ""
        --replace-in-metadata "video:title" " ?[\U00010B40-\U0010ffff]+" "" to this --replace-in-metadata "video:title" " ?[\U00002B07-\U00002E7F]+" ""
        --replace-in-metadata "video:title" " ?[\U00002FF0-\U00002FFF]+" ""
        --replace-in-metadata "video:title" " ?[\U00002B00-\U0000DFFF]+" ""
        --replace-in-metadata "video:title" " ?[\U0000E000-\U0000F8FF]+" ""
        --replace-in-metadata "video:title" " ?[\U0000FE00-\U0000FE2F]+" ""
        --replace-in-metadata "video:title" " ?[\U0000FF00-\U0000FFFF]+" ""
        --replace-in-metadata "video:title" " ?[\U00010B40-\U0010ffff]+" ""

**Comment by sebma** [comment]
@error-reporting In other words, I have to replace `--replace-in-metadata "video:title" " ?[\U0000U+2FF0-\U0000U+2FFF]+" ""` by ` --replace-in-metadata "video:title" " ?[\U00002FF0-\U00002FFF]+" ""` in the complete regexp list, right ?

**Comment by error-reporting** [comment]
yes

**Comment by kxxc** [comment]
config

--replace-in-metadata "video:title" " ?[\U00002B07-\U00002E7F\U0000E000-\U0000F8FF\U0000FE00-\U0000FE2F\U00010B40-\U0010FFFF]+" ""
