### ISSUE TITLE
Autrenaming files when downloading in bulk?

### ISSUE THREAD

**Issue by Shohreh** [yt-dlp/yt-dlp#3050]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

Hello,

The command-line help and searching here for "rename" returned no hits.

Am I correct in understanding that, unlike youtube-dl, youtube-dlp doesn't support autorenaming files when downloading in bulk, eg. `youtube-dlp -A -a input.txt` ?

Thank you.

**Comment by pukkandan** [comment]
```
These are all the deprecated options and the current alternative to achieve the same effect
...
These options were deprecated since 2014 and have now been entirely removed

    -A, --auto-number                -o "%(autonumber)s-%(id)s.%(ext)s"
```
https://github.com/yt-dlp/yt-dlp#removed
