### ISSUE TITLE
Identify onion services with their respective (already yt-dlp supported) websites

### ISSUE THREAD

**Issue by resulin** [yt-dlp/yt-dlp#3053]
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.03.08.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Tor Network

### Example URLs

- [ ] Twitter has an onion service: https://twitter3e4tixl4xyajtrzo62zg5vztmjuricljdp2c5kshju4avyoid.onion/TwitterBlue/status/1484226494708662273 (source: https://en.wikipedia.org/wiki/Twitter#External_links )
- [x] Facebook has an onion service: https://www.facebookwkhpilnemxj7asaniu7vnjjbiltxjqhye3mhbshg7kx5tfyd.onion/ (source: https://en.wikipedia.org/wiki/Facebook_onion_address )
- [ ] BBC: https://www.bbcnewsd73hkzno2ini43t4gblxvycyac5aw4gnv7t2rccijh7745uqd.onion/

### Description

Identify onion services with their respective (already yt-dlp supported) websites (for example twitter is already supported by yt-dlp but its onion service is dealt with by the fallback generic extractor instead of the twitter specific one)

### Verbose log

```shell
Example for the Twitter onion service:


emily@emily:~/Videos$ yt-dlp https://twitter3e4tixl4xyajtrzo62zg5vztmjuricljdp2c5kshju4avyoid.onion/TwitterBlue/status/1484226494708662273
[generic] 1484226494708662273: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] 1484226494708662273: Downloading webpage
[generic] 1484226494708662273: Extracting information
ERROR: Unsupported URL: https://twitter3e4tixl4xyajtrzo62zg5vztmjuricljdp2c5kshju4avyoid.onion/TwitterBlue/status/1484226494708662273
```
```

**Comment by dirkf** [comment]
Related: https://github.com/ytdl-org/youtube-dl/issues/30731

Especially right now, this is a very significant issue.

There are two aspects here:
1. the extractor needs to recognise the onion URL pattern;
2. as I understand, it needs to use the same base domain when accessing resources from the service, such as APIs, or the extraction will potentially be subject to the same blocking or interception that the user is trying to avoid by using the Tor site.

As far as the listed sites are concerned, the Facebook yt-dlp and yt-dl extractors address point 1 but not point 2. For both yt-dlp and yt-dl, neither Twitter nor BBC Tor sites are handled at all, and although the YouTube extractors know about some Invidious Tor sites point 2 is not addressed.

Depending on how each extractor is structured, it may be possible to patch in support for the Tor site, or it may be easier to make a new or subclass extractor class (or classes).

**Comment by pukkandan** [comment]
It is easy enough to add the valid URLs to the extractors, but I don't think (2) is worth doing. After all, we don't do that for invidious, nitter or the other already supported onion sites

**Comment by dirkf** [comment]
Surely any API used by site JS must be supported, or the Tor site would not successfully circumvent whatever the user needs to bypass? Confirmed at least for [Twitter](https://github.com/ytdl-org/youtube-dl/issues/30736#issuecomment-1066264558).

**Comment by pukkandan** [comment]
> Surely any API used by site JS must be supported in the onion domain, or the Tor site would not successfully circumvent whatever the user needs to bypass? 

The point of onion sites is not to bypass any restrictions (using tor on clearsites already covers that), but to avoid trusting exit-nodes. But I see your point

My initial thought was that the onion websites could be still using the normal API, and most end-users would be none-the-wiser. But on second thought, this would probably be a terrible PR move for the service

**Comment by pukkandan** [comment]
Since this work has to be done for each site separately, having a single issue to track multiple sites is a bad idea. For this issue, I will just add the onion links to valid URLs for the mentioned sites.

Once that is done, please open **separate issues** for adding "full onion support" **for each site**. Issues could also be opened for adding similar support to youtube/invidious (though I dont even know if invidious provides youtube-like API)

**Comment by dirkf** [comment]
This [List of Real-World Onion Sites](https://github.com/alecmuffett/real-world-onion-sites/blob/master/README.md#social-networks) might be consulted for other candidates, eg DW, NYT.

**Comment by gamer191** [comment]
> It is easy enough to add the valid URLs to the extractors, but I don't think (2) is worth doing. After all, we don't do that for invidious, nitter or the other already supported onion sites. It is also unlikely that the API endpoints exist in onion domains, making it even more complicated

That seems like a terrible idea. No one accidentally enters the .onion site when they want to use the standard site. If you can't support the .onion site, just give an "unsupported url" error. In fact, in my opinion, yt-dl/yt-dlp should probably remove .onion support from the facebook and invidious/nitter support from the Youtube extractor


> My initial thought was that the onion websites could be still using the normal API, and most end-users would be none-the-wiser.

So deliberately doing something contrary to the user's intentions, because you don't think the user will realise? That's called malware.

**Comment by resulin** [comment]
@pukkandan 
> The point of onion sites is not to bypass any restrictions (using tor on clearsites already covers that), but to avoid trusting exit-nodes. 

The main point is that onion sites don't use exit nodes so they're faster since exit bandwidth is limited (**IF** they're [single onion services](https://support.torproject.org/glossary/single-onion-service/), i.e. 3 hops in the circuit instead of 6).

**Comment by gamer191** [comment]
@resulin [They are marketed as a way to avoid trusting exit nodes*, and to let people create accounts for free, anonymously](https://tb-manual.torproject.org/en-US/onion-services/). Also, [clearnet sites only have 3 nodes in a circuit](https://support.torproject.org/glossary/circuit/).

*As the hyperlinked article notes, using https achieves that already (it's slightly less secure, but it's probably good enough). However, python isn't as good at ssl verification as tor browser (https://revoked.badssl.com/ doesn't raise an ssl error, for example).

Actually, now that I think about it, I'm not sure whether yt-dlp would block exit nodes from performing MitM attacks on onion sites 👀
