### ISSUE TITLE
--dump-user-agent outputting more than it should

### ISSUE THREAD

**Issue by barkoder** [yt-dlp/yt-dlp#3055]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.03.08.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

I use `--dump-user-agent` to randomly generate a user-agent string for a script.

Up until version `2022.02.04`, it would just dump 1 line and quit.  
And I love that.

````
$ yt-dlp --dump-user-agent
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.85 Safari/537.36

````

But since `2022.03.08.1` I get

````
$ yt-dlp --dump-user-agent
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.71 Safari/537.36
Usage: youtube-dl.exe [OPTIONS] URL [URL...]

youtube-dl.exe: error: You must provide at least one URL.
Type yt-dlp --help to see a list of all options.

````
I could `2>&1 | head -1` my way to the former output but `--dump-user-agent` really should work like it used to.

Thanks.

### Verbose log

```shell
-v log for this issue would go against demonstrating the 1 line output of --dump-user-agent so I'm not including it.

Thanks.
```

**Comment by pukkandan** [comment]
> I use --dump-user-agent to randomly generate a user-agent string for a script.

There are easier ways to do that though...
