### ISSUE TITLE
How to only download subtitles in a specific format？

### ISSUE THREAD

**Issue by zhongfly** [yt-dlp/yt-dlp#3058]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

I only want subtitles in a specific format in all languages, if there is no specific format then don't download any subtitles.
```
yt-dlp -s -vU --sub-format "ass/srt" --proxy http://127.0.0.1:7890 --all-subs -- https://www.youtube.com/watch?v=YjtC7kw0SRI
```
But it will download vtt format.

### Verbose log

```shell
[debug] Command-line config: ['-s', '-vU', '--sub-format', 'ass/srt', '--proxy', 'http://127.0.0.1:7890', '--all-subs', '--', 'https://www.youtube.com/watch?v=YjtC7kw0SRI']
[debug] Encodings: locale cp936, fs utf-8, out utf-8, err utf-8, pref cp936
[debug] yt-dlp version 2022.03.13.43044 [29003cf] (win_exe)
[debug] ** This build is unofficial daily builds, provided for ease of use.
[debug] ** Please do not ask for any support.
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] exe versions: ffmpeg git-2022-02-22-570fda56 (setts), ffprobe 2022-02-21-git-b8e58f0858-essentials_build-www.gyan.dev
[debug] Optional libraries: brotli, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {'http': 'http://127.0.0.1:7890', 'https': 'http://127.0.0.1:7890'}
Latest version: 2022.03.13.43044, Current version: 2022.03.13.43044
yt-dlp is up to date (2022.03.13.43044)
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=YjtC7kw0SRI
[youtube] YjtC7kw0SRI: Downloading webpage
[youtube] YjtC7kw0SRI: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[debug] Downloading subtitles: zh-Hans, zh-Hant, en, id
WARNING: No subtitle format found matching "ass/srt" for language zh-Hans, using vtt
WARNING: No subtitle format found matching "ass/srt" for language zh-Hant, using vtt
WARNING: No subtitle format found matching "ass/srt" for language en, using vtt
WARNING: No subtitle format found matching "ass/srt" for language id, using vtt
[debug] Default format spec: bestvideo*+bestaudio/best
[info] YjtC7kw0SRI: Downloading 1 format(s): 248+251
```

**Comment by zhongfly** [comment]
I read the code and found that yt-dlp is designed that way.
I would suggest adding an option to allow users to reject this fallback behavior

**Comment by pukkandan** [comment]
youtube never has ass or srt subs. So what are you trying to achieve?

**Comment by zhongfly** [comment]
> youtube never has ass or srt subs. So what are you trying to achieve?

this is just using youtube as an example

**Comment by zhongfly** [comment]
> youtube never has ass or srt subs. So what are you trying to achieve?

I'll give a more complicated example, most of the videos on www.bilibili.com have only one subtitle (a special xml file), but this subtitle will stop mpv from running, so I don't want yt-dlp to download This xml subtitle.
So I plan to use the --sub-format option to restrict the format of the subtitles, such as ass/srt, so that the xml subtitles will not be downloaded if there are only xml subtitles.

**Comment by eladkarako** [comment]
youtube will only give you <a href="https://en.wikipedia.org/wiki/.vtt">VTT</a> (pretty much srt).  

<details><summary>notes</summary>

if you want to get subtitles with a specific format, for processing them later (for example) with your favorite subtitle editor (mine is subtitle workshop), you can always use ffmpeg to convert them back and forth to whatever format you wish.

note 1: youtube gives Unicode (UTF-16 Without BOM) encoded VTT. some editor won't like it, you can always use Notepad++ to convert it to UTF-8 Without BOM, or just plain ANSII (ASCII). you can convert them back to Unicode afterwards (some FFMPEG filters for burning subtitles will require it).

note 2 (regarding note1): VTT and srt are basically just timed text (although VTT theoretically can hold much more - YT does not make use of those features and just includes text and timing), formats such as <a href="https://en.wikipedia.org/wiki/SubStation_Alpha">.ass</a> also include color and relative position on screen (mostly used in anime), so converting them to other formats will cause you to loose that information.

also,  
and this is not strictly related,  
if you can't find subtitles for a video, try using `--write-auto-subs` and `--sub-langs "all"`,  
whatever you got from that you can "pipe through" https://www.syedgakbar.com/projects/dst
for a 'machine translation' (of your choice of service), and you can continue fixing it manually.

</details>

**Comment by Yay295** [comment]
> VTT and srt are basically just timed text (although VTT theoretically can hold much more - YT does not make use of those features and just includes text and timing)

Here's a video with colored subtitles and karaoke: https://www.youtube.com/watch?v=_VIeV_LZXHM

**Comment by eladkarako** [comment]
@Yay295 thank you  
<details><summary>that's an awesome example for the VTT format, which I will keep for reference.</summary>  

<a href="https://github.com/yt-dlp/yt-dlp/files/8933044/Original.Animation.MV.Unison.hololive_._VIeV_LZXHM.en.vtt.txt"><code>【Original Animation MV】Unison【hololive_宝鐘マリン】 [_VIeV_LZXHM].en.vtt.txt</code></a>

<a href="https://github.com/yt-dlp/yt-dlp/files/8933045/Original.Animation.MV.Unison.hololive_._VIeV_LZXHM.ja.vtt.txt"><code>【Original Animation MV】Unison【hololive_宝鐘マリン】 [_VIeV_LZXHM].ja.vtt.txt</code></a>

it isn't as feature-rich as SubStation Alpha with all the function,  
so they add the characters one by one,  
that's an interesting workaround, I wonder how the YT conversion works..  

<img width="816" alt="2022-06-18_091142" src="https://user-images.githubusercontent.com/415238/174425466-39f387cc-297a-4bca-bf7a-5d81f4622dc8.png">

</details>

**Comment by nyuszika7h** [comment]
`—-convert-subs ass`

**Comment by XXiaoA** [comment]
May we can check [here](https://github.com/yt-dlp/yt-dlp/issues/9237)

**Comment by zhongfly** [comment]
> May we can check [here](https://github.com/yt-dlp/yt-dlp/issues/9237)

Not exactly the same functionality as what is being requested for this issue. But maybe I should make a feature request

**Comment by bashonly** [comment]
This is the feature request
