### ISSUE TITLE
Support for Yahoo Gyao!

### ISSUE THREAD

**Issue by ualaa1** [yt-dlp/yt-dlp#3063]
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.03.08.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Japan

### Example URLs

Single Video: https://gyao.yahoo.co.jp/store/episode/A300364001999H01
Playlist: https://gyao.yahoo.co.jp/store/title/300364

### Description

Only accessible in Japan. Only the first episode of shows are free. The rest requires payment.

### Verbose log

```shell
yt-dlp -v "https://gyao.yahoo.co.jp/store/episode/A300364001999H01"
[debug] Command-line config: ['-v', 'https://gyao.yahoo.co.jp/store/episode/A300364001999H01']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.03.08.2 [e491d06d3]
[debug] Python version 3.9.0 (CPython 64bit) - macOS-12.2.1-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1, rtmpdump 2.4
[debug] Optional libraries: brotli, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [generic] Extracting URL: https://gyao.yahoo.co.jp/store/episode/A300364001999H01
[generic] A300364001999H01: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] A300364001999H01: Downloading webpage
[generic] A300364001999H01: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://gyao.yahoo.co.jp/store/episode/A300364001999H01
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1389, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1459, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 617, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/extractor/generic.py", line 3998, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://gyao.yahoo.co.jp/store/episode/A300364001999H01
```

**Comment by pukkandan** [comment]
Some URL patters on the site is supported already, but this isn't

**Comment by garret1317** [comment]
gyao is no more
https://www.oricon.co.jp/news/2264237/full/
https://www.animenewsnetwork.com/daily-briefs/2023-01-17/japanese-streaming-service-gyao-shuts-down-on-march-31/.193904
