### ISSUE TITLE
[vk.com] direct access can't watch, but Sign In page can watch

### ISSUE THREAD

**Issue by jazz1611** [yt-dlp/yt-dlp#3068]
### Checklist

- [X] I'm reporting a site feature request
- [X] I've verified that I'm running yt-dlp version **2022.03.08.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Example URLs

Can watch: https://vk.com/login?u=2&to=/al_im.php?sel=167478049&z=video-128731116_456245041/1cfd7d8d5de1a8633e/pl_post_-128731116_36828

Can't watch: https://vk.com/video-128731116_456245041

### Description

Hello,

It same video. This URL can't watch at direct. But other method URL can watch at normal.

![image](https://user-images.githubusercontent.com/1846222/158187281-ed48d4e1-b06e-4012-b5d7-1cec9afeb24c.png)

### Verbose log

```shell
C:\Users\Administrator>youtube-dl -FUv "https://vk.com/login?u=2&to=/al_im.php?sel=167478049&z=video-128731116_456245041/1cfd7d8d5de1a8633e/pl_post_-128731116_36828"
[debug] Command-line config: ['-FUv', 'https://vk.com/login?u=2&to=/al_im.php?sel=167478049&z=video-128731116_456245041/1cfd7d8d5de1a8633e/pl_post_-128731116_36828']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.03.08.1 [c0c2c57] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19042-SP0
[debug] exe versions: ffmpeg 5.0-full_build-www.gyan.dev (setts), ffprobe 4.4.1-full_build-www.gyan.dev
[debug] Optional libraries: brotli, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.03.08.1, Current version: 2022.03.08.1
yt-dlp is up to date (2022.03.08.1)
[debug] [vk] Extracting URL: https://vk.com/login?u=2&to=/al_im.php?sel=167478049&z=video-128731116_456245041/1cfd7d8d5de1a8633e/pl_post_-128731116_36828
[vk] -128731116_456245041: Downloading JSON metadata
ERROR: [vk] Access to this video has been restricted by the community's managers
  File "yt_dlp\extractor\common.py", line 617, in extract
  File "yt_dlp\extractor\vk.py", line 338, in _real_extract
  File "yt_dlp\extractor\vk.py", line 72, in _download_payload


C:\Users\Administrator>youtube-dl -FUv "https://vk.com/video-128731116_456245041"
[debug] Command-line config: ['-FUv', 'https://vk.com/video-128731116_456245041']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.03.08.1 [c0c2c57] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19042-SP0
[debug] exe versions: ffmpeg 5.0-full_build-www.gyan.dev (setts), ffprobe 4.4.1-full_build-www.gyan.dev
[debug] Optional libraries: brotli, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.03.08.1, Current version: 2022.03.08.1
yt-dlp is up to date (2022.03.08.1)
[debug] [vk] Extracting URL: https://vk.com/video-128731116_456245041
[vk] -128731116_456245041: Downloading JSON metadata
ERROR: [vk] Access to this video has been restricted by the community's managers
  File "yt_dlp\extractor\common.py", line 617, in extract
  File "yt_dlp\extractor\vk.py", line 338, in _real_extract
  File "yt_dlp\extractor\vk.py", line 72, in _download_payload
```

**Comment by DetachHead** [comment]
it looks you can't watch any videos without signing in anymore

**Comment by megapro17** [comment]
![image](https://user-images.githubusercontent.com/16743370/193425117-d4cfd85d-2106-476c-a576-30e4b5497583.png)
Right, this video no longer avaliable without account and joining group
I suggest closing this issue
