### ISSUE TITLE
Can it download Instagram pictures?

### ISSUE THREAD

**Issue by hasnogaems** [yt-dlp/yt-dlp#3071]
### Checklist

- [X] I'm reporting a feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.03.08.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

Subj

**Comment by pukkandan** [comment]
No https://github.com/yt-dlp/yt-dlp/issues/1693

**Comment by shakakibara12** [comment]
Have a look at [gallery-dl](https://github.com/mikf/gallery-dl) and if you are specifically downloading images from instagram you can also check out [instaloader](https://instaloader.github.io/)
