### ISSUE TITLE
Joyn Site Support Request

### ISSUE THREAD

**Issue by G-Utopia** [yt-dlp/yt-dlp#3072]
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.03.08.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Germany

### Example URLs

- Single Episode: https://www.joyn.de/play/serien/clannad/1-1-wo-die-kirschblueten-fallen
- Single Epsiode: https://www.joyn.de/play/serien/black-clover/1-47-eine-einzigartige-waffe-bptsqvtq9w6s
- Series Overview: https://www.joyn.de/serien/black-clover

### Description

Only accessable in the D/A/CH Countries. 
About the premium service and the account managment I gathered following information. There are three kinds on how a video is to whom accessable:
1. Requiring no account at all (Like the two example links).
2. Requiring an account but not a paid subscription.
3. Requiring both an account and a paid subscription.

### Verbose log

```shell
gu-unix@Expurgation-German:~$ yt-dlp -vU https://www.joyn.de/play/serien/clannad/1-1-wo-die-kirschblueten-fallen
[debug] Command-line config: ['-vU', 'https://www.joyn.de/play/serien/clannad/1-1-wo-die-kirschblueten-fallen']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.03.08.1 [c0c2c57d3] (zip)
[debug] Python version 3.9.2 (CPython 64bit) - Linux-5.10.60.1-microsoft-standard-WSL2-x86_64-with-glibc2.31
[debug] exe versions: ffmpeg 4.3.3-0, ffprobe 4.3.3-0, rtmpdump 2.4
[debug] Optional libraries: sqlite
[debug] Proxy map: {}
Latest version: 2022.03.08.1, Current version: 2022.03.08.1
yt-dlp is up to date (2022.03.08.1)
[debug] [generic] Extracting URL: https://www.joyn.de/play/serien/clannad/1-1-wo-die-kirschblueten-fallen
[generic] 1-1-wo-die-kirschblueten-fallen: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] 1-1-wo-die-kirschblueten-fallen: Downloading webpage
[generic] 1-1-wo-die-kirschblueten-fallen: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://www.joyn.de/play/serien/clannad/1-1-wo-die-kirschblueten-fallen
Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1389, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1459, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 617, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/generic.py", line 3985, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.joyn.de/play/serien/clannad/1-1-wo-die-kirschblueten-fallen
```

**Comment by spookyahell** [comment]
The problem is:
AFAIK, all videos come with DRM by default.

**Comment by Hrxn** [comment]
How would I test if (some) videos there are available without any DRM?

**Comment by bashonly** [comment]
> How would I test if (some) videos there are available without any DRM?

@Hrxn https://github.com/yt-dlp/yt-dlp/issues/4062#issuecomment-1153474056

**Comment by Hrxn** [comment]
@bashonly thanks, appreciate it!
