### ISSUE TITLE
Option to save certain metadata for videos

### ISSUE THREAD

**Issue by tripleo1** [yt-dlp/yt-dlp#3073]
### Checklist

- [X] I'm reporting a site feature request
- [X] I've verified that I'm running yt-dlp version **2022.03.08.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

USA

### Example URLs

https://videosite.xxx/y7h6gg9/video_name

(obviously not real)

### Description

"Certain" websites provide what I call metadata on the page, such as tags or categories, and an uploader name. (Even y*utube lets you know the channel name).  I would like a command line option that would save this metadata in a file adjacent to the actual download, maybe in JSON or TOML format (the format doesn't really matter, as long as it's machine readable).

Some fields I can think of are:

- Video Name
- Uploader or Channel
- Tags/Categories
- Upload Date
- Download Date (`datetime.now()`)
- Original URL
- Maybe even cookies?

### Verbose log

```shell
Not provided
```

**Comment by Lesmiscore** [comment]
`--write-info-json` does the job.

**Comment by tripleo1** [comment]
I'll try it now.

**Comment by tripleo1** [comment]
You have to do `--write-pages` along with it and it requires a little postprocessing, but it worked for my first test.

You guys are great.
