### ISSUE TITLE
proxy error downloads video anyway 

### ISSUE THREAD

**Issue by himanss** [yt-dlp/yt-dlp#3078]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.03.08.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

I wanted the audio to a YT video at work. due to controversial paired gif, the video is age restricted to the network members.

after some testing I have concluded that it is NOT a fault of the proxy and rather a fault of yt-dlp.

NOTE: I assumed curl proxy syntax for yt-dlp

using the following command downloads the video over the non proxy internet after attempting an HTTP proxy connection.
```
yt-dlp "*video url*" --geo-verification-proxy socks://localhost:9050 --proxy socks://localhost:9050 -x
```
note that I asked for a SOCKS connection

proxy logs the event when this happens
```
Mar 15 11:22:55.000 [warn] Socks version 67 not recognized. (This port is not an HTTP proxy)
```

intentionally wrong curl 
```
curl --proxy http://localhost:9050 google.com --output - -i
```
response
```
HTTP/1.0 501 not an HTTP Proxy
Content-Type: text/html; charset=iso-8859-1

<html>
<head>
<title>This is a SOCKS Proxy, Not An HTTP Proxy</title>
</head>
<body>
<h1>This is a SOCKs proxy, not an HTTP proxy.</h1>
</body>
</html>
```
looking at yt-dlp -v logs this line stands out
```
[debug] Proxy map: {'http': 'socks://localhost:9050', 'https': 'socks://localhost:9050'}
```
it took the URL header in without parsing it. (lol)

same line from yt-dlp -v with no proxy/geo-proxy set
```
[debug] Proxy map: {}
```

### Verbose log

```shell
[debug] Command-line config: 'https://www.youtube.com/watch?v=EQOpCyvAhlY', '-vU']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.03.08.1 [c0c2c57d3] (zip)
[debug] Python version 3.8.10 (CPython 64bit) - Linux-5.13.0-35-generic-x86_64-with-glibc2.29
[debug] exe versions: none
[debug] Optional libraries: secretstorage, sqlite
[debug] Proxy map: {}
Latest version: 2022.03.08.1, Current version: 2022.03.08.1
yt-dlp is up to date (2022.03.08.1)
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=5510-jn_w1I
[youtube] 5510-jn_w1I: Downloading webpage
[youtube] 5510-jn_w1I: Downloading android player API JSON
ERROR: [youtube] 5510-jn_w1I: Video unavailable. This video is restricted. Please check the Google Workspace administrator and/or the network administrator restrictions.
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 617, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/youtube.py", line 3339, in _real_extract
    self.raise_no_formats(reason, expected=True)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 1126, in raise_no_formats
    raise ExtractorError(msg, expected=expected, video_id=video_id)
```

**Comment by pukkandan** [comment]
> looking at yt-dlp -v logs this line stands out
> [debug] Proxy map: {'http': 'socks://localhost:9050', 'https': 'socks://localhost:9050'}
> it took the URL header in without parsing it. (lol)

That is just saying that http and https requests will go through that proxy

---

The verbose log you have given is useless since it doesn't use the proxy options. Please provide verbose log with those options

**Comment by Lesmiscore** [comment]
Suppose you're trying to download over Tor,
>     socks://localhost:9050
It's `socks5` not socks. They're different thing.

**Comment by coletdjnz** [comment]
> ERROR: [youtube] 5510-jn_w1I: Video unavailable. This video is restricted. Please check the Google Workspace administrator and/or the network administrator restrictions

On this note, it might be possible to bypass this without a proxy depending on the type of restriction. 

see: https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass/issues/55#issuecomment-905899487

there's a whole bunch of alternative Innertube domains that are not documented by YouTube and hence are probably not blocked by your average network administrator. We'll just need some way of switching between them, whether automatic or manually.

**Comment by coletdjnz** [comment]
> Suppose you're trying to download over Tor,
> 
> > ```
> > socks://localhost:9050
> > ```
> 
> It's `socks5` not socks. They're different thing.

Yeah, `socks` is treated as `socks4` not `socks5`

**Comment by coletdjnz** [comment]
> > ERROR: [youtube] 5510-jn_w1I: Video unavailable. This video is restricted. Please check the Google Workspace administrator and/or the network administrator restrictions
> 
> On this note, it might be possible to bypass this without a proxy depending on the type of restriction.
> 
> see: [zerodytrash/Simple-YouTube-Age-Restriction-Bypass#55 (comment)](https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass/issues/55#issuecomment-905899487)
> 
> there's a whole bunch of alternative Innertube domains that are not documented by YouTube and hence are probably not blocked by your average network administrator. We'll just need some way of switching between them, whether automatic or manually.

I think it's technically already possible to bypass this in the current release.

`--extractor-args youtube:player-client=default,web_music`

**Comment by pukkandan** [comment]
> there's a whole bunch of alternative Innertube domains that are not documented by YouTube and hence are probably not blocked by your average network administrator. We'll just need some way of switching between them, whether automatic or manually.

The message "This video is restricted. Please check the Google Workspace administrator and/or the network administrator restrictions" is due to the video being [restricted using Google workspace](https://support.google.com/a/answer/6212415?hl=en), not using DNS. So all domains are likely restricted

**Comment by coletdjnz** [comment]
> > there's a whole bunch of alternative Innertube domains that are not documented by YouTube and hence are probably not blocked by your average network administrator. We'll just need some way of switching between them, whether automatic or manually.
> 
> The message "This video is restricted. Please check the Google Workspace administrator and/or the network administrator restrictions" is due to the video being [restricted using Google workspace](https://support.google.com/a/answer/6212415?hl=en), not using DNS. So all domains are likely restricted

The DNS/HTTP header restriction method gives the same error message too, from my testing. 

In the case for users signed in to their organisation account it probably wouldn't work. At the top of that page: "...you can help restrict which YouTube videos are viewable by **signed-in users in your organization**". 

DNS/HTTP header method is used for users that are signed out or logged in to an account not controlled by the organization imposing the restrictions, which is what we can bypass. At least from my understanding from the articles.

But, adding a workaround might not be worth it considering this would be a rare edge case.
