### ISSUE TITLE
[Feature Request]Add faster download for ism files

### ISSUE THREAD

**Issue by m0ck69** [yt-dlp/yt-dlp#308]
Hi.
Please add the possibility to use  -N 16 and aria2c for manifest ism files (ismv, isma).
Currently such files are downloaded very slowly.
ism example
`https://redir.cache.orange.pl/canal/v/canal/vod/store01/NOV_M0QSRDmgctKWjRYjTl1q/_/hd4-hssdrm02.ism/Manifest`

**Comment by m0ck69** [comment]
any chances for such enhancement or not?

**Comment by pukkandan** [comment]
Not in the near future. ISM files are more complex to work with

cc @shirt-dev

**Comment by pukkandan** [comment]
Closing in favor of keeping track of all multithreading requests in #1918
