### ISSUE TITLE
[Site Request] RMCStory (https://rmcstory.bfmtv.com/)

### ISSUE THREAD

**Issue by MantaRayDeeJay** [yt-dlp/yt-dlp#309]
## Checklist

- [x] I'm reporting a new site support request
- [ ] I've verified that I'm running yt-dlp version **2021.05.11**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [ ] I've checked that none of provided URLs violate any copyrights
- [ ] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

- Single video: https://rmcstory.bfmtv.com/terre-en-danger-catastrophes-modernes_21923/les-crashs-du-boeing-737_25843/
- Single video: https://rmcstory.bfmtv.com/le-lait-et-le-bio-enquete-sur-les-produits-vedettes_25824/
- Playlist: none

## Description

I think that the **RMCStory** website is structured in the same way as the **RMCDecouverte** website which is currently taked in charge by the application.
There is currently 2 links format :
- https://rmcstory.bfmtv.com/category/video/
- https://rmcstory.bfmtv.com/video/

**Comment by MantaRayDeeJay** [comment]
MAJ : "RMC Story" and "RMC Decouverte" Web Sites have been restructured.
Now, website examples are :
**RMC Story**
https://www.rmcbfmplay.com/video/rmc-story/les-secrets-du-saint-graal?contentId=Product::NEUF_NUM23_N23547185992527&universe=PROVIDER
**RMC Decouverte**
https://www.rmcbfmplay.com/video/rmc-decouverte/sousmarin-nucleaire-deconstruction-xxl?contentId=Product::NEUF_RMCDEC_RMC00126347&universe=PROVIDER

**Comment by floviolleau** [comment]
Hi,

I could be a very nice to have

**Comment by pukkandan** [comment]
See https://github.com/yt-dlp/yt-dlp/issues/3594
