### ISSUE TITLE
C-SPAN - unable to download Zelenskyy address to U.S. Congress

### ISSUE THREAD

**Issue by 1seekr** [yt-dlp/yt-dlp#3090]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.03.08.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

Though I did download the video using youtube-dl, yt-dlp, which I tried first, failed.  However, I ran yt-dlp on a commercial server machine, which may not be running the latest version of Python.  (It's running 2.7.18, while my own machine, where I was able to download the video using youtube-dl, runs 2.7.12 -- yes, I know it's apples v. oranges here, since it's possible the older Python version is good enough for youtube-dl, but 2.7.18 may not be good enough for yt-dlp.)

I don't know the meaning of the phrase "not related to a specific site."  Maybe the problem is only related to the C-SPAN site, but I have no easy way to know or find out.  So I ticked that box, though I was unsure of the correct answer to that question, since I could not submit this report without doing so.  :)

### Verbose log

```shell
[debug] Command-line config: ['-vU', 'https://www.c-span.org/video/?518685-1/ukrainian-president-zelensky-calls-us-back-fly-zone-provide-defensive-weapons']
WARNING: Assuming --restrict-filenames since file system encoding cannot encode all characters. Set the LC_ALL environment variable to fix this.
[debug] Encodings: locale ANSI_X3.4-1968, fs ascii, out ANSI_X3.4-1968 (No ANSI), err ANSI_X3.4-1968 (No ANSI), pref ANSI_X3.4-1968
[debug] yt-dlp version 2022.03.08.1 [c0c2c57d3] (zip)
[debug] Python version 3.6.8 (CPython 64bit) - Linux-4.18.0-193.28.1.lve1.el8.x86_64-x86_64-with-glibc2.3.4
[debug] exe versions: none
[debug] Optional libraries: sqlite
[debug] Proxy map: {}
Latest version: 2022.03.08.1, Current version: 2022.03.08.1
yt-dlp is up to date (2022.03.08.1)
[debug] [CSpan] Extracting URL: https://www.c-span.org/video/?518685-1/ukrainian-president-zelensky-calls-us-back-fly-zone-provide-defensive-weapons
[CSpan] 518685: Downloading webpage
Traceback (most recent call last):
  File "/home/foo/bin/yt/yt_dlp/extractor/common.py", line 735, in _request_webpage
  File "/home/foo/bin/yt/yt_dlp/YoutubeDL.py", line 3591, in urlopen
  File "/usr/lib64/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib64/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/lib64/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib64/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/foo/bin/yt/yt_dlp/extractor/common.py", line 617, in extract
  File "/home/foo/bin/yt/yt_dlp/extractor/cspan.py", line 90, in _real_extract
  File "/home/foo/bin/yt/yt_dlp/extractor/common.py", line 903, in _download_webpage
  File "/home/foo/bin/yt/yt_dlp/extractor/common.py", line 768, in _download_webpage_handle
  File "/home/foo/bin/yt/yt_dlp/extractor/common.py", line 753, in _request_webpage
yt_dlp.utils.ExtractorError: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on  https://github.com/yt-dlp/yt-dlp , filling out the "Broken site" issue template properly. Confirm you are on the latest version using  yt-dlp -U

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/foo/bin/yt/yt_dlp/YoutubeDL.py", line 1389, in wrapper
  File "/home/foo/bin/yt/yt_dlp/YoutubeDL.py", line 1459, in __extract_info
  File "/home/foo/bin/yt/yt_dlp/extractor/common.py", line 643, in extract
yt_dlp.utils.ExtractorError: [CSpan] 518685: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on  https://github.com/yt-dlp/yt-dlp , filling out the "Broken site" issue template properly. Confirm you are on the latest version using  yt-dlp -U

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/foo/bin/yt/__main__.py", line 19, in <module>
  File "/home/foo/bin/yt/yt_dlp/__init__.py", line 864, in main
  File "/home/foo/bin/yt/yt_dlp/__init__.py", line 854, in _real_main
  File "/home/foo/bin/yt/yt_dlp/YoutubeDL.py", line 3255, in download
  File "/home/foo/bin/yt/yt_dlp/YoutubeDL.py", line 3227, in wrapper
  File "/home/foo/bin/yt/yt_dlp/YoutubeDL.py", line 1380, in extract_info
  File "/home/foo/bin/yt/yt_dlp/YoutubeDL.py", line 1407, in wrapper
  File "/home/foo/bin/yt/yt_dlp/utils.py", line 1088, in format_traceback
TypeError: format_exception() missing 2 required positional arguments: 'value' and 'tb'
```

**Comment by fossdd** [comment]
I can successfully download your file.

The 403 Forbidden HTTP exit code looks like the issue is on your side. Maybe try running yt-dlp thorugh Tor.

**Comment by pukkandan** [comment]
Works for me

```
❯ yt-dlp "https://www.c-span.org/video/?518685-1/ukrainian-president-zelensky-calls-us-back-fly-zone-provide-defensive-weapons"
[CSpan] 518685: Downloading webpage
[CSpan] 518685: Downloading m3u8 information
[info] 518685: Downloading 1 format(s): hls-4367
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 136
[download] Destination: Ukrainian President Zelensky Addresses Congress [518685].mp4
[download]   0.7% of ~67.23MiB at 528.69KiB/s ETA 02:09 (frag 1/136)
ERROR: Interrupted by user
```

> - [X] I've checked that all provided URLs are alive and playable in a browser

Check again

**Comment by pukkandan** [comment]
> I don't know the meaning of the phrase "not related to a specific site." Maybe the problem is only related to the C-SPAN site, but I have no easy way to know or find out. So I ticked that box, though I was unsure of the correct answer to that question, since I could not submit this report without doing so. :)

That is because there are separate templates for site-specific issues. No matter now, just explaining for future

![image](https://user-images.githubusercontent.com/6623388/158899128-268eb522-f126-4d32-af1a-ab4df09ac7b7.png)

**Comment by jxu** [comment]
Python 2 is not supported for yt-dlp

**Comment by 1seekr** [comment]
I now accept that this problem is not really a problem.  I probably should not have reported it as such, since I don't and can't control the environment in which yt-dlp runs, given that it's on a commercial server (while I'm working to repair my main computer, where I can provide the proper environment to run yt-dlp).

Thanks to everyone who has tried to reproduce the problem and has commented.  Perhaps some who have done so have found the video containing President Zelenskyy's address to the U.S. Congress worthwhile.  I'm finding it hard to think of anything else these days, especially since some experts on such matters are saying that we're already well into World War III, which for me is a very scary thought.  :-\  I suppose such statements are made mostly for "dramatic effect," but I think this to be one of these "slippery slope" sorts of situations.  [Apologies for these admittedly off-topic musings.]
