### ISSUE TITLE
Sponsorblock in config file gives out python error

### ISSUE THREAD

**Issue by cinbunnaps** [yt-dlp/yt-dlp#3093]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.03.08.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

This is my first issue posted anywhere so please let me know if I'm missing any info.

I've done some trial and error to find what exactly is casuing this error and it seems to be only when sponsorblock options are placed in yt-dlp.conf. This is the error I get (and output of -vU) with the full config I'm trying to use:

Also to check my theory this is the output without the sponsorblock options:
[debug] Command-line config: ['-vU']
[debug] Home config "yt-dlp.conf": ['-f', 'bv*[ext=mp4]+ba[ext=m4a]/b[ext=mp4] / bv*+ba/b', '--write-thumbnail', '--force-write-archive', '--write-subs', '--write-auto-subs', '--convert-subs', 'srt', '--sub-langs', 'en', '--embed-subs', '--embed-thumbnail', '--embed-metadata', '--embed-chapters', '-o', '/server/downloads/yt-dlp/%(title)s/%(title)s.%(ext)s']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.03.08.1 [c0c2c57d3] (zip)
[debug] Python version 3.9.11 (CPython 64bit) - Linux-5.13.0-35-generic-x86_64-with-glibc2.31
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4
[debug] Optional libraries: mutagen, sqlite
[debug] Proxy map: {}
Latest version: 2022.03.08.1, Current version: 2022.03.08.1
yt-dlp is up to date (2022.03.08.1)

This is the configuration file I'm attempting to use:
# Full Episodes from Youtube
-f "bv*[ext=mp4]+ba[ext=m4a]/b[ext=mp4] / bv*+ba/b"
--write-thumbnail
--download-archive
--force-write-archive
--write-subs
--write-auto-subs
--convert-subs srt
--sub-langs en
--embed-subs
--embed-thumbnail
--embed-metadata
--embed-chapters
--sponsorblock-remove sponsor, selfpromo, preview
--sponsorblock-mark intro, filler, interaction, music_offtopic, poi_highlight
-o "/server/downloads/yt-dlp/%(title)s/%(title)s.%(ext)s"

I could very well be using the conf wrong, what I'm trying to achieve is downloading the best mp4 with best audio, embed thumbnail and metadata, extract and format subtitles, and of course the sponsorblock options listed. This is placed with each video placed in it's own folder with subtitles and the .webd in it. Please correct me if I'm just using the commands incorrectly, that is entirely possible!

I've gone through and removed option by option to test everything else and only those last two options produce the error. I've tried multiple video URLs as well. I also updated Python3 yesterday but it didn't help this issue at all.

### Verbose log

```shell
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/bin/yt-dlp/__main__.py", line 19, in <module>
  File "/usr/local/bin/yt-dlp/yt_dlp/__init__.py", line 864, in main
  File "/usr/local/bin/yt-dlp/yt_dlp/__init__.py", line 815, in _real_main
  File "/usr/local/bin/yt-dlp/yt_dlp/__init__.py", line 614, in parse_options
  File "/usr/local/bin/yt-dlp/yt_dlp/options.py", line 106, in parseOpts
  File "/usr/local/bin/yt-dlp/yt_dlp/options.py", line 102, in load_configs
  File "/usr/local/bin/yt-dlp/yt_dlp/options.py", line 95, in add_config
  File "/usr/local/bin/yt-dlp/yt_dlp/utils.py", line 5405, in append_config
  File "/usr/local/bin/yt-dlp/yt_dlp/utils.py", line 5350, in init
  File "/usr/lib/python3.9/optparse.py", line 1387, in parse_args
    stop = self._process_args(largs, rargs, values)
  File "/usr/lib/python3.9/optparse.py", line 1427, in _process_args
    self._process_long_opt(rargs, values)
  File "/usr/lib/python3.9/optparse.py", line 1501, in _process_long_opt
    option.process(opt, value, values, self)
  File "/usr/lib/python3.9/optparse.py", line 784, in process
    return self.take_action(
  File "/usr/lib/python3.9/optparse.py", line 805, in take_action
    self.callback(self, opt, value, parser, *args, **kwargs)
  File "/usr/local/bin/yt-dlp/yt_dlp/options.py", line 173, in _set_from_options_callback
IndexError: string index out of range
```

**Comment by pukkandan** [comment]
> - [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)

Arguments with spaces should be quoted

(I'll add a better error message though)

**Comment by cinbunnaps** [comment]
You're the best, thank you so much!
