### ISSUE TITLE
Errors: Unable to download webpage: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED]

### ISSUE THREAD

**Issue by mike2003** [yt-dlp/yt-dlp#3102]
### Question

Yesterday I tried yt-dlp, but any time I try to download YouTube I get a lot of errors:
**WARNING: [youtube] Unable to download webpage: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)>**

I tried the same thing on another computer and everything works fine.
Both Windows 10 x64, why doesn't it work and what's the difference???

PS I know about **--no-check-certificate**, it helps. But I want to get off the problem.

**Comment by coletdjnz** [comment]
Likely an issue with your OS certificates (outdated or missing certs?).

https://github.com/yt-dlp/yt-dlp/pull/3115 will workaround issues such as this once merged.

**Comment by mike2003** [comment]
What am I supposed to do? There are no problems with other programs. Browsers are working.

**Comment by pukkandan** [comment]
That is because browsers (except IE) have their own certificate store. Since #3115 has been merged now, next yt-dlp versions will also come with it own certificates
