### ISSUE TITLE
ZEE5 Broken Site ( HTTP Error 400: Bad Request )

### ISSUE THREAD

**Issue by kr-v** [yt-dlp/yt-dlp#3105]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.03.08.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Description

Unable to download a lot of URLs from ZEE5, I have confirmed they are playable on non-DRM Browsers.

URL : https://www.zee5.com/kids/kids-shows/indias-best-dramebaaz-2018/0-6-tvshow_225807515/indias-best-dramebaaz-2018/0-1-tvshow_225807515-season_1636655307-episode_1767761271

### Verbose log

```shell
[debug] Command-line config: ['https://www.zee5.com/kids/kids-shows/indias-best-dramebaaz-2018/0-6-tvshow_225807515/indias-best-dramebaaz-2018/0-1-tvshow_225807515-season_1636655307-episode_1767761271', '--verbose', '-o', 'Downloads/%(title)s.%(ext)s', '--cookies-from-browser', 'chrome', '-N', '20']
[Cookies] Extracting cookies from chrome
[debug] Extracting cookies from: "/Users/dd/Library/Application Support/Google/Chrome/Default/Cookies"
[debug] using find-generic-password to obtain password from OSX keychain
[Cookies] Extracted 3274 cookies from chrome
[debug] cookie version breakdown: {'v10': 3207, 'other': 0, 'unencrypted': 67}
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.03.08.1 [c0c2c57d3] (zip)
[debug] Lazy loading extractors is disabled
[debug] Python version 3.9.10 (CPython 64bit) - macOS-12.1-arm64-arm-64bit
[debug] exe versions: ffmpeg 5.0 (setts), ffprobe 5.0, rtmpdump 2.4
[debug] Optional libraries: Cryptodome, sqlite
[debug] Proxy map: {}
[debug] Using fake IP 117.254.45.16 (IN) as X-Forwarded-For
[debug] [Zee5] Extracting URL: https://www.zee5.com/kids/kids-shows/indias-best-dramebaaz-2018/0-6-tvshow_225807515/indias-best-dramebaaz-2018/0-1-tvshow_225807515-season_1636655307-episode_1767761271
[Zee5] 0-1-tvshow_225807515-season_1636655307-episode_1767761271: Downloading access token
[Zee5] 0-1-tvshow_225807515-season_1636655307-episode_1767761271: Downloading JSON metadata
ERROR: [Zee5] 0-1-tvshow_225807515-season_1636655307-episode_1767761271: Unable to download JSON metadata: HTTP Error 400: Bad Request (caused by <HTTPError 400: 'Bad Request'>); please report this issue on  https://github.com/yt-dlp/yt-dlp , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 617, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/zee5.py", line 136, in _real_extract
    json_data = self._download_json(
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 997, in _download_json
    res = self._download_json_handle(
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 976, in _download_json_handle
    res = self._download_webpage_handle(
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 768, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query, expected_status=expected_status)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 753, in _request_webpage
    raise ExtractorError(errmsg, cause=err)

  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 735, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3589, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/opt/homebrew/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/opt/homebrew/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/opt/homebrew/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/opt/homebrew/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/opt/homebrew/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: Bad Request
```

**Comment by kr-v** [comment]
@Ashish0804 @pukkandan

**Comment by GetPHP-IR** [comment]
I have same problem even I use cookies or indian vpn

**Comment by rossanmol** [comment]
Same issue here, seems like they changed the API slightly.

**Comment by rossanmol** [comment]
@pukkandan no account needed to download or view.

**Comment by kr-v** [comment]
@pukkandan  @Ashish0804  I am willing to share account, please tell how to share account.

**Comment by rossanmol** [comment]
@pukkandan I could offer to help, is there any process documented on how to test the python files (extractors)? This is my first time so I would need some more time.

**Comment by pukkandan** [comment]
https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#developer-instructions

**Comment by GetPHP-IR** [comment]
Is there any solutions??
no suggest???

**Comment by ParitoshBh** [comment]
Updating the `_DETAIL_API_URL` from

`https://spapi.zee5.com/singlePlayback/getDetails?content_id={}&device_id={}&platform_name=desktop_web&country=IN&check_parental_control=false`

to

`https://spapi.zee5.com/singlePlayback/getDetails/secure?content_id={}&device_id={}&platform_name=desktop_web&country=IN&check_parental_control=false`

worked for me. If those who have reported issue above can test this, I can then create a PR.

**Comment by Vikassm73** [comment]
How fix device ID is working for all? Are you not getting premium content using this add on?
