### ISSUE TITLE
yt-dlp does not respect output option

### ISSUE THREAD

**Issue by masterkain** [yt-dlp/yt-dlp#3106]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.03.08.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

`yt-dlp -o test.mp4 https://youtube.com/blabla`

I expected a `test.mp4` to be present on the filesystem but I get a `test.mp4.webm`

### Verbose log

```shell
[youtube] ltZKAe12neg: Downloading webpage
[youtube] ltZKAe12neg: Downloading android player API JSON
[info] ltZKAe12neg: Downloading 1 format(s): 248+251
[download] Destination: /usr/src/app/downloads/1647629624688.mp4.f248.webm
[download] 100% of 68.19MiB in 00:02
[download] Destination: /usr/src/app/downloads/1647629624688.mp4.f251.webm
[download] 100% of 6.88MiB in 00:00
[Merger] Merging formats into "/usr/src/app/downloads/1647629624688.mp4.webm"
Deleting original file /usr/src/app/downloads/1647629624688.mp4.f251.webm (pass -k to keep)
Deleting original file /usr/src/app/downloads/1647629624688.mp4.f248.webm (pass -k to keep)
```
```

**Comment by pukkandan** [comment]
You are actually downloading a webm file despite the filename set. Use `-f` or `-S` to select an actual mp4 format.

**Comment by masterkain** [comment]
true but the documentation says that `-o`, even along with a full path, should not alter the final filename.
this behavior is also different from the original youtube-dl

**Comment by pukkandan** [comment]
> this behavior is also different from the original youtube-dl

No, it is the same

**Comment by masterkain** [comment]
> > this behavior is also different from the original youtube-dl
> 
> No, it is the same

I just switched to yt-dlp and it's not the same, at least in my tests, with the same params I was able to keep the filename I specified in the output without any changes

**Comment by masterkain** [comment]
maybe the behavior depends on the source? that would explain it since I've tested only youtube in yt-dlp and other sources in youtube-dl

**Comment by pukkandan** [comment]
The file extension is forced if a merge is needed. ffmpeg doesn't merge the files properly unless the extension is right.


I have considered forcing the extension always for consistent behavior (and coz I've seen too many issues due to user passing wrong extension), but then people would genuinely complain that the behavior is different from youtube-dl. So I'll need to make a compat option, document the change and stuff...
