### ISSUE TITLE
AlfredWorkflow (macOS) for yt-dlp

### ISSUE THREAD

**Issue by becauseim** [yt-dlp/yt-dlp#3110]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

Hi! I'm sure there are people here who are willing to help you write a simple workflow for Alfred (macOS) to quickly download videos from the clipboard.
Unfortunately, I was not able to do it myself.
Thank you!

**Comment by pukkandan** [comment]
> - [X] I'm asking a question and **not** reporting a bug/feature request

Do not abuse the "Question" template to post incomplete issues/feature requests.

> - [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-your-question-about-yt-dlp

This is a question about mac workflows which you should ask in appropriate forums, not here
