### ISSUE TITLE
Merging fails if one part is already downloaded

### ISSUE THREAD

**Issue by ballo** [yt-dlp/yt-dlp#3111]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.03.08.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

If you tell yt-dlp to merge two streams and one of the streams is already downloaded, it will say it's already downloaded and fail to attempt to download the 2nd stream.

### Verbose log

```shell
Example:
yt-dlp -f 160 https://www.youtube.com/watch?v=NFngc_8RiVc
yt-dlp -f 160+139 https://www.youtube.com/watch?v=NFngc_8RiVc                                 [youtube] NFngc_8RiVc: Downloading webpage      [youtube] NFngc_8RiVc: Downloading android player API JSON                                      [info] NFngc_8RiVc: Downloading 1 format(s): 160+139                                            [download] Former top Pentagon advisor Col. Doug Macgregor on Russia-Ukraine war [NFngc_8RiVc].mp4 has already been downloaded
```

**Comment by pukkandan** [comment]
How is yt-dlp to know that the existing file is a different format? Either use `--force-overwrite`, or set different filenames for the 2 runs
