### ISSUE TITLE
How to pass extra argument to the progress_hooks function?

### ISSUE THREAD

**Issue by phantom2152** [yt-dlp/yt-dlp#3122]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

Hello, I'm attempting to incorporate yt-dlp into Python. I'm creating a bot that will download and send video to the user. So I'd like to add a feature that informs the user about the status of the video download on the server. The progress hooks function informs us of the status of the video download. Now, how do I pass more arguments to that function?

I tried
```
def prog_hook(response,msg):
    msg.edit_text(" Video downloading:",response.get("status"))
```
and in my options I set the argumets like this
```
ydlp_opts={
'progress_hooks': [prog_hook(_,msg)],
}
```

I assumed that by passing ```_``` as an argument, the function would only consider the second argument, but this was not the case. So, how can I give the function more arguments?

**Comment by pukkandan** [comment]
https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-your-question-about-yt-dlp
This is a python question. Research about functools.partial or lambdas, or ask in appropriate forums

**Comment by phantom2152** [comment]
Yea sorry about that after searching for a while I came up with this 

We can use lambda
Like 
`progress_hooks': [lambda d: progress_hook(d,msg)]`

Putting this up here so anyone having similar issues can use this
