### ISSUE TITLE
how to fixi 

### ISSUE THREAD

**Issue by MyGoodbye** [yt-dlp/yt-dlp#3128]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

'yt-dlp' is not recognized as an internal or external command,
operable program or batch file.
how to solve this

### Verbose log

```shell
C:\Users\52240>yt-dlp -F https://www.youtube.com/watch?v=Dl_2-sQOhqE
'yt-dlp' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by Bricio** [comment]
Configure your PATH variable to have yt-dlp folder
https://www.java.com/en/download/help/path.html
