### ISSUE TITLE
Embedded Tor support

### ISSUE THREAD

**Issue by karam72** [yt-dlp/yt-dlp#3129]
### Checklist

- [X] I'm reporting a feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.03.08.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

Hi,

As you know better, there is no any extension for Tor Browser to download media files from all web sites (because of new Firefox API). We require to use apps like yt-dlp.

Is there any possibility to download media files via tor?

I have tried on Debian based disto to download videos using "tor" and "torsocks" command. I was able to download videos via yt-dlp. But now I changed my OS and now I'm not able to do it. It is complex for me. I always do something wrong and I install new commands/dependencies and I change some configs on my OS which makes some inconsistencies in the future. 

But yt-dlp is standalone. It would be great if we have the freedom to download from blocked web sites.

Thank in advance

**Comment by pukkandan** [comment]
Start a tor socks proxy and use `--proxy`

**Comment by karam72** [comment]
So I don't need tor-socks package install? Only tor command is enough?

**Comment by 1sixth** [comment]
> So I don't need tor-socks package install? Only tor command is enough?

There is no need to install `torsocks`. `tor` itself provides [SocksPort](https://2019.www.torproject.org/docs/tor-manual.html.en#SocksPort), which can be used by `yt-dlp` via the flag `--proxy` as mentioned.

> I try but I could not start tor locally.

I guess you need to read the manual, like [this](https://man.archlinux.org/man/tor.1).

> Also to install tor and run it I need sudo password.

Try downloading binaries from reliable sources if the official package manager of your distro is unavailable for some reason. 

> But if tor was embedded yt-dlp I could be able to run with user permissions.

You can always run `tor` and `yt-dlp` as unprivileged users anyway.

**Comment by karam72** [comment]
Ok Thank you. I tried again but I have problems. Its technically difficult for me. Maybe I will try a new OS (Tails) inside virtual machine and I will try to run yt-dlp.

This ticket can be closed if tor will not support directly by yt-dlp. Thank you for your interest.

**Comment by pukkandan** [comment]
wdym directly support? It does "directly" support using `--proxy`.

You want yt-dlp to have tor embedded in it? That won't be done! Why would you even think that is in scope?

**Comment by karam72** [comment]
> wdym directly support? It does "directly" support using --proxy.

I mean like "Tor browser". "Tor browser" includes inside itself.

> You want yt-dlp to have tor embedded in it? That won't be done! Why would you even think that is in scope?

I just want to download things which they block by my ISP. I have installed Fedora which is one of the easiest for end-user but I could not start tor. It is difficult for me. Anyway, I just asked. If not, no problem. We can close the task.

**Comment by sebma** [comment]
You can use torify : https://linuxaria.com/howto/how-to-anonymize-the-programs-from-your-terminal-with-torify
