### ISSUE TITLE
Embed subs +sponsorblock does not embed subs, and wrong time removal

### ISSUE THREAD

**Issue by dabreadman** [yt-dlp/yt-dlp#3130]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.03.08.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

I was trying to download a video that has sponsor segment removed, and embed subs.   

I was expecting a file with sponsor segments removed and with embedded subtitles.

What I got was instead a file that has embedded subtitles (that is blank), and part of the sponsor segment **NOT** removed (result is 4:06 long, and expect as 4:01). Part of the segments was preserved (file starts at around 0:25, but should start at 0:30 instead)

`yt-dlp -f "ba" -o "test/%(uploader)s/%(playlist_index)s - %(title)s.%(ext)s" --embed-subs --sponsorblock-remove all --sub-langs "en,zh-Hans",-live_chat --force-overwrites --windows-filenames "https://www.youtube.com/watch?v=impSuIygMiQ" -vU
`

Embedded Subtitle
![image](https://user-images.githubusercontent.com/43485369/159161899-bf41f47e-2818-4f3c-a058-9a6be3d24bb9.png)  

Subtitle in Player
![image](https://user-images.githubusercontent.com/43485369/159162021-9948751a-df04-4941-b167-6353002483b2.png)

Confirmed Source has subtitles
![image](https://user-images.githubusercontent.com/43485369/159162045-3f04911e-c0d3-4513-b76a-233f8d852d7f.png)

File Length
![image](https://user-images.githubusercontent.com/43485369/159162163-0530d7dc-9287-4feb-b465-a308edf0eb2f.png)

Actual length
![image](https://user-images.githubusercontent.com/43485369/159162184-a2d06930-9366-48f6-962d-9b068577f05c.png)

### Verbose log

```shell
PS C:\Users\jello> yt-dlp -f "ba" -o "test/%(uploader)s/%(playlist_index)s - %(title)s.%(ext)s" --embed-subs --sponsorblock-remove all --sub-langs "en,zh-Hans",-live_chat --force-overwrites --windows-filenames "https://www.youtube.com/watch?v=impSuIygMiQ" -vU

[debug] Command-line config: ['-f', 'ba', '-o', 'test/%(uploader)s/%(playlist_index)s - %(title)s.%(ext)s', '--embed-subs', '--sponsorblock-remove', 'all', '--sub-langs', 'en,zh-Hans,-live_chat', '--force-overwrites', '--windows-filenames', 'https://www.youtube.com/watch?v=impSuIygMiQ', '-vU']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.03.08.1 [c0c2c57] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] exe versions: ffmpeg N-106313-g31916d3d9f-20220318 (setts), ffprobe N-106313-g31916d3d9f-20220318
[debug] Optional libraries: brotli, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.03.08.1, Current version: 2022.03.08.1
yt-dlp is up to date (2022.03.08.1)
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=impSuIygMiQ
[youtube] impSuIygMiQ: Downloading webpage
[youtube] impSuIygMiQ: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[debug] Downloading subtitles: en
[SponsorBlock] Fetching SponsorBlock segments
[debug] SponsorBlock query: https://sponsor.ajay.app/api/skipSegments/da54?service=YouTube&categories=%5B%22preview%22%2C+%22filler%22%2C+%22intro%22%2C+%22interaction%22%2C+%22selfpromo%22%2C+%22outro%22%2C+%22music_offtopic%22%2C+%22sponsor%22%5D&actionTypes=%5B%22skip%22%2C+%22poi%22%5D
[SponsorBlock] Found 4 segments in the SponsorBlock database
[info] impSuIygMiQ: Downloading 1 format(s): 251
[info] Writing video subtitles to: test\THE FIRST TAKE\NA - LiSA×Uru - 再会 (produced by Ayase) _ THE FIRST TAKE.en.vtt
[debug] Invoking downloader on "https://www.youtube.com/api/timedtext?v=impSuIygMiQ&xoaf=5&hl=en&ip=0.0.0.0&ipbits=0&expire=1647803464&sparams=ip%2Cipbits%2Cexpire%2Cv%2Cxoaf&signature=B5EFE16E0AE2DCB1BA8B3DF273BD47C5A91640FD.60BFEC07A53826EC5D14E8897DBA59771D01F505&key=yt8&lang=en&fmt=vtt"
[download] Destination: test\THE FIRST TAKE\NA - LiSA×Uru - 再会 (produced by Ayase) _ THE FIRST TAKE.en.vtt
[download] 100% of 3.24KiB in 00:00
Deleting existing file test\THE FIRST TAKE\NA - LiSA×Uru - 再会 (produced by Ayase) _ THE FIRST TAKE.webm
[debug] Invoking downloader on "https://rr1---sn-q0c7rn76.googlevideo.com/videoplayback?expire=1647799864&ei=2Bk3YoLDOJCAWYaLibAJ&ip=80.111.182.195&id=o-AI5HVkf-f3pbE0j-0WlonGlQZIG6iSA8DvB3DEBoBW-u&itag=251&source=youtube&requiressl=yes&mh=Yl&mm=31%2C26&mn=sn-q0c7rn76%2Csn-aigzrn7d&ms=au%2Conr&mv=m&mvi=1&pl=18&initcwndbps=1673750&vprv=1&mime=audio%2Fwebm&gir=yes&clen=4571055&dur=296.941&lmt=1605361363082736&mt=1647777889&fvip=2&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=5531432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRAIgR4nqF7ZbSQoXznDKuqdYzPNTnm5mx4XIGtC06jsMG1sCIAbpn0j_xDJuEvPzOvs_HYWqentwspuw1WAbnziCNyRm&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAIF4CkBsei6r2wjC3YvOpmTEabZMDLZ0CFYl55Tm1JZwAiEArlLnr_IhbMC60-1240QZpM9XOkoFEBrBPCMLC2sTsDA%3D"
[download] Destination: test\THE FIRST TAKE\NA - LiSA×Uru - 再会 (produced by Ayase) _ THE FIRST TAKE.webm
[download] 100% of 4.36MiB in 00:00
[EmbedSubtitle] Embedding subtitles in "test\THE FIRST TAKE\NA - LiSA×Uru - 再会 (produced by Ayase) _ THE FIRST TAKE.webm"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:test\THE FIRST TAKE\NA - LiSA×Uru - 再会 (produced by Ayase) _ THE FIRST TAKE.webm" -i "file:test\THE FIRST TAKE\NA - LiSA×Uru - 再会 (produced by Ayase) _ THE FIRST TAKE.en.vtt" -map 0 -dn -ignore_unknown -c copy -map "-0:s" -map "1:0" "-metadata:s:s:0" "language=eng" "-metadata:s:s:0" "handler_name=English" "-metadata:s:s:0" "title=English" -movflags "+faststart" "file:test\THE FIRST TAKE\NA - LiSA×Uru - 再会 (produced by Ayase) _ THE FIRST TAKE.temp.webm"
Deleting original file test\THE FIRST TAKE\NA - LiSA×Uru - 再会 (produced by Ayase) _ THE FIRST TAKE.en.vtt (pass -k to keep)
[debug] ffprobe command line: ffprobe -hide_banner -show_format -show_streams -print_format json "file:test\THE FIRST TAKE\NA - LiSA×Uru - 再会 (produced by Ayase) _ THE FIRST TAKE.webm"
[debug] Concat spec = 30.000000-271.775000
[ModifyChapters] Removing chapters from test\THE FIRST TAKE\NA - LiSA×Uru - 再会 (produced by Ayase) _ THE FIRST TAKE.webm
[debug] Writing concat spec to test\THE FIRST TAKE\NA - LiSA×Uru - 再会 (produced by Ayase) _ THE FIRST TAKE.temp.webm.concat
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -hide_banner -nostdin -f concat -safe 0 -i "file:test\THE FIRST TAKE\NA - LiSA×Uru - 再会 (produced by Ayase) _ THE FIRST TAKE.temp.webm.concat" -map 0 -dn -ignore_unknown -c copy -movflags "+faststart" "file:test\THE FIRST TAKE\NA - LiSA×Uru - 再会 (produced by Ayase) _ THE FIRST TAKE.temp.webm"
Deleting original file test\THE FIRST TAKE\NA - LiSA×Uru - 再会 (produced by Ayase) _ THE FIRST TAKE.uncut.webm (pass -k to keep)
PS C:\Users\jello>
```

**Comment by pukkandan** [comment]
> part of the sponsor segment NOT removed 

https://github.com/yt-dlp/yt-dlp/issues/3104#issuecomment-1072872963

**Comment by dabreadman** [comment]
> > part of the sponsor segment NOT removed
> 
> [#3104 (comment)](https://github.com/yt-dlp/yt-dlp/issues/3104#issuecomment-1072872963)

Right, got it! What about the part where the subtitle is blank?

Should I change the title since we figured out that it being slightly off is something known?

**Comment by pukkandan** [comment]
Does vlc show subs for audio-only files? I can see the subs in mpv, but not in vlc

**Comment by pukkandan** [comment]
If I download video too, both shows the subs. So definitely VLC's fault

**Comment by dabreadman** [comment]
> Does vlc show subs for audio-only files? I can see the subs in mpv, but not in vlc

Gonna try download mpv and test

**Comment by dabreadman** [comment]
> > Does vlc show subs for audio-only files? I can see the subs in mpv, but not in vlc
> 
> Gonna try download mpv and test

Can confirm it does show on mpv, but not on VLC nor `Films and TV` (win10 built-in media playback software), but if I were to remove `-f "ba"` the subtitles would show on VLC, what's going on?

**Comment by pukkandan** [comment]
> but if I were to remove -f "ba" the subtitles would show on VLC, what's going on?

https://github.com/yt-dlp/yt-dlp/issues/3130#issuecomment-1073308205

You will need to ask VLC devs
