### ISSUE TITLE
Cannot get stream info on Viu

### ISSUE THREAD

**Issue by BLSTR13** [yt-dlp/yt-dlp#3133]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.03.08.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Philippines, mostly Asian countries

### Description

cant download on viu

### Verbose log

```shell
[debug] Command-line config: ['-vU', '--no-playlist', 'https://www.viu.com/ott/ph/en-us/vod/429151/Attack-on-Titan-Final-Season']
[debug] User config "C:\Users\Cherri Estudillo\AppData\Roaming\yt-dlp\config.txt": ['-o', 'D:/ytdl/%(title)s.%(ext)s', '--no-mtime']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.03.08.1 [c0c2c57] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] exe versions: ffmpeg n5.0-5-g4769d77c8c-20220310 (setts), ffprobe n5.0-5-g4769d77c8c-20220310, phantomjs 2.1.1
[debug] Optional libraries: brotli, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.03.08.1, Current version: 2022.03.08.1
yt-dlp is up to date (2022.03.08.1)
[debug] [viu:ott] Extracting URL: https://www.viu.com/ott/ph/en-us/vod/429151/Attack-on-Titan-Final-Season
[viu:ott] 429151: Downloading video info
[viu:ott] Downloading just the video 429151 because of --no-playlist
[viu:ott] 429151: Downloading stream info
ERROR: [viu:ott] 429151: Cannot get stream info
  File "yt_dlp\extractor\common.py", line 617, in extract
  File "yt_dlp\extractor\viu.py", line 348, in _real_extract
```

**Comment by zackmark29** [comment]
Could you test this first?
https://github.com/zackmark29/yt-dlp/commit/ba5fcdbfd447650eb2bacb1be4e8d8f64653116c

I haven't tried to download because of my internet connection. But it's now fixed the error you are getting.

**Comment by uwuuuu** [comment]
> Could you test this first? #3136
> 
> I haven't tried to download because of my internet connection. But it's now fixed the error you are getting.

Did not work for me. Still get the same error.


```:~/ytdl/yt-dlp$ sudo -H ./yt-dlp.sh -vU --no-playlist https://www.viu.com/ott/sg/en-us/vod/428051/Amazing-Saturday-2022
[debug] Command-line config: ['-vU', '--no-playlist', 'https://www.viu.com/ott/sg/en-us/vod/428051/Amazing-Saturday-2022']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, err UTF-8, pref UTF-8
[debug] yt-dlp version 2022.03.08.1 [c0c2c57d3] (source)
[debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
[debug] Git HEAD: ba5fcdbfd
[debug] Python version 3.6.9 (CPython 64bit) - Linux-4.15.0-163-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.8, ffprobe 3.4.8
[debug] Optional libraries: brotli, Cryptodome, secretstorage, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.03.08.1, Current version: 2022.03.08.1
yt-dlp is up to date (2022.03.08.1)
[debug] [viu:ott] Extracting URL: https://www.viu.com/ott/sg/en-us/vod/428051/Amazing-Saturday-2022
[viu:ott] 428051: Downloading video info
[viu:ott] Downloading just the video 428051 because of --no-playlist
[viu:ott] 428051: Downloading stream info
ERROR: [viu:ott] 428051: Cannot get stream info
  File "/home/theo/ytdl/yt-dlp/yt_dlp/extractor/common.py", line 637, in extract
    ie_result = self._real_extract(url)
  File "/home/theo/ytdl/yt-dlp/yt_dlp/extractor/viu.py", line 332, in _real_extract
    raise ExtractorError('Cannot get stream info', expected=True)```

**Comment by zackmark29** [comment]
> > Could you test this first? #3136
> > I haven't tried to download because of my internet connection. But it's now fixed the error you are getting.
> 
> Did not work for me. Still get the same error.
> 
> ```
> [debug] Command-line config: ['-vU', '--no-playlist', 'https://www.viu.com/ott/sg/en-us/vod/428051/Amazing-Saturday-2022']
> [debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, err UTF-8, pref UTF-8
> [debug] yt-dlp version 2022.03.08.1 [c0c2c57d3] (source)
> [debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
> [debug] Git HEAD: ba5fcdbfd
> [debug] Python version 3.6.9 (CPython 64bit) - Linux-4.15.0-163-generic-x86_64-with-Ubuntu-18.04-bionic
> [debug] exe versions: ffmpeg 3.4.8, ffprobe 3.4.8
> [debug] Optional libraries: brotli, Cryptodome, secretstorage, mutagen, sqlite, websockets
> [debug] Proxy map: {}
> Latest version: 2022.03.08.1, Current version: 2022.03.08.1
> yt-dlp is up to date (2022.03.08.1)
> [debug] [viu:ott] Extracting URL: https://www.viu.com/ott/sg/en-us/vod/428051/Amazing-Saturday-2022
> [viu:ott] 428051: Downloading video info
> [viu:ott] Downloading just the video 428051 because of --no-playlist
> [viu:ott] 428051: Downloading stream info
> ERROR: [viu:ott] 428051: Cannot get stream info
>   File "/home/theo/ytdl/yt-dlp/yt_dlp/extractor/common.py", line 637, in extract
>     ie_result = self._real_extract(url)
>   File "/home/theo/ytdl/yt-dlp/yt_dlp/extractor/viu.py", line 332, in _real_extract
>     raise ExtractorError('Cannot get stream info', expected=True)```
> ```

Alright just wait. Because I'll check if this is different for each country

![image](https://user-images.githubusercontent.com/62680932/159213461-3fb2639a-c891-4369-9418-c8fd56406960.png)

**Comment by zackmark29** [comment]
@uwuuuu  you may try now the updated one

**Comment by uwuuuu** [comment]
@zackmark29 This commit works for me: https://github.com/zackmark29/yt-dlp/commit/b7a8affe719b500ef5d17683be4fa1abf911bd91

```
:~/ytdl/yt-dlp$ sudo -H ./yt-dlp.sh -vU -F --no-playlist https://www.viu.com/ott/sg/en-us/vod/429116/Amazing-Saturday-2022
[debug] Command-line config: ['-vU', '-F', '--no-playlist', 'https://www.viu.com/ott/sg/en-us/vod/429116/Amazing-Saturday-2022']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, err UTF-8, pref UTF-8
[debug] yt-dlp version 2022.03.08.1 [c0c2c57d3] (source)
[debug] Lazy loading extractors is disabled
[debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
[debug] Git HEAD: a31b4fd5f
[debug] Python version 3.6.9 (CPython 64bit) - Linux-4.15.0-163-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.8, ffprobe 3.4.8
[debug] Optional libraries: brotli, Cryptodome, secretstorage, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.03.08.1, Current version: 2022.03.08.1
yt-dlp is up to date (2022.03.08.1)
[debug] [viu:ott] Extracting URL: https://www.viu.com/ott/sg/en-us/vod/429116/Amazing-Saturday-2022
[viu:ott] 429116: Downloading video info
[viu:ott] Downloading just the video 429116 because of --no-playlist
[viu:ott] Getting bearer token
[viu:ott] 429116: Downloading stream info
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[info] Available formats for 429116:
ID     EXT RESOLUTION │   FILESIZE PROTO │ VCODEC  ACODEC
──────────────────────────────────────────────────────────
s240p  mp4 240p       │  358.41MiB m3u8  │ unknown unknown
s480p  mp4 480p       │  827.23MiB m3u8  │ unknown unknown
s720p  mp4 720p       │    1.54GiB m3u8  │ unknown unknown
s1080p mp4 1080p      │    2.96GiB m3u8  │ unknown unknown
```



Your latest commit breaks something again. Tested it with playlist/--no-playlist and a few diff videos. https://github.com/zackmark29/yt-dlp/commit/a31b4fd5f8f37e21f2a261e967cadf3ca836b616



```
:~/ytdl/yt-dlp$ sudo -H ./yt-dlp.sh -vU --no-playlist https://www.viu.com/ott/sg/en-us/vod/429116/Amazing-Saturday-2022
[debug] Command-line config: ['-vU', '--no-playlist', 'https://www.viu.com/ott/sg/en-us/vod/429116/Amazing-Saturday-2022']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, err UTF-8, pref UTF-8
[debug] yt-dlp version 2022.03.08.1 [c0c2c57d3] (source)
[debug] Lazy loading extractors is disabled
[debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
[debug] Git HEAD: a31b4fd5f
[debug] Python version 3.6.9 (CPython 64bit) - Linux-4.15.0-163-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.8, ffprobe 3.4.8
[debug] Optional libraries: brotli, Cryptodome, secretstorage, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.03.08.1, Current version: 2022.03.08.1
yt-dlp is up to date (2022.03.08.1)
[viu:ott] Downloading location info
[viu:ott] Getting bearer token
ERROR: [viu:ott] 429116: Unable to download JSON metadata: HTTP Error 422: Unprocessable Content (caused by <HTTPError 422: 'Unprocessable Content'>); please report this issue on  https://github.com/yt-dlp/yt-dlp , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/home/theo/ytdl/yt-dlp/yt_dlp/extractor/common.py", line 635, in extract
    self.initialize()
  File "/home/theo/ytdl/yt-dlp/yt_dlp/extractor/common.py", line 543, in initialize
    self._real_initialize()
  File "/home/theo/ytdl/yt-dlp/yt_dlp/extractor/viu.py", line 236, in _real_initialize
    note='Getting bearer token')['token']
  File "/home/theo/ytdl/yt-dlp/yt_dlp/extractor/common.py", line 1029, in _download_json
    expected_status=expected_status)
  File "/home/theo/ytdl/yt-dlp/yt_dlp/extractor/common.py", line 1007, in _download_json_handle
    expected_status=expected_status)
  File "/home/theo/ytdl/yt-dlp/yt_dlp/extractor/common.py", line 796, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query, expected_status=expected_status)
  File "/home/theo/ytdl/yt-dlp/yt_dlp/extractor/common.py", line 781, in _request_webpage
    raise ExtractorError(errmsg, cause=err)

  File "/home/theo/ytdl/yt-dlp/yt_dlp/extractor/common.py", line 763, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/home/theo/ytdl/yt-dlp/yt_dlp/YoutubeDL.py", line 3588, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 422: Unprocessable Content
```

**Comment by uwuuuu** [comment]
Upon further testing, your latest commit works when testing from an in-region IP that allows browser playback. It does not work when accessing from an out of region IP.

In the past (and on https://github.com/zackmark29/yt-dlp/commit/b7a8affe719b500ef5d17683be4fa1abf911bd91), yt-dlp has worked on Viu regardless of the IP used to access.

**Comment by zackmark29** [comment]
> 

Ahm I justed again it works fine for me. I'm using Express VPN connected to SG

```
[debug] Optional libraries: Cryptodome, sqlite
[debug] Proxy map: {}
[viu:ott] Downloading location info
[viu:ott] Getting bearer token
[debug] [viu:ott] Extracting URL: https://www.viu.com/ott/sg/en-us/vod/429116/Amazing-Saturday-2022
[viu:ott] 429116: Downloading video info
[viu:ott] Downloading just the video 429116 because of --no-playlist
[viu:ott] 429116: Downloading stream info
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[info] Available formats for 429116:
ID     EXT RESOLUTION │   FILESIZE PROTO │ VCODEC  ACODEC
──────────────────────────────────────────────────────────
s240p  mp4 240p       │  358.41MiB m3u8  │ unknown unknown
s480p  mp4 480p       │  827.23MiB m3u8  │ unknown unknown
s720p  mp4 720p       │    1.54GiB m3u8  │ unknown unknown
s1080p mp4 1080p      │    2.96GiB m3u8  │ unknown unknown
```
Could you test again? I want to know why you are getting that error

**Comment by zackmark29** [comment]
> HTTP Error 422: Unprocessable Content

Well maybe let's just revert without caching the token? since it's work for you when requesting new token for each request

**Comment by zackmark29** [comment]
> Upon further testing, your latest commit works when testing from an in-region IP that allows browser playback. It does not work when accessing from an out of region IP.
> 
> In the past (and on [zackmark29@b7a8aff](https://github.com/zackmark29/yt-dlp/commit/b7a8affe719b500ef5d17683be4fa1abf911bd91)), yt-dlp has worked on Viu regardless of the IP used to access.

I tested on HK/SG/PH they both return the location info. for ID/MY not yet supported for now they should have separated Class because API are different.
If you still get the same error, maybe we can just revert it for now

**Comment by zackmark29** [comment]
@uwuuuu could you test now the new commit?

**Comment by uwuuuu** [comment]
Your latest commit (https://github.com/zackmark29/yt-dlp/commit/2aba16c5cfab13898a69234530564ce2715cc5c1) is working for me now regardless of IP used to access. No need to VPN with this version.

```
:~/ytdl/yt-dlp$ sudo -H ./yt-dlp.sh -F -vU --no-playlist https://www.viu.com/ott/sg/en-us/vod/429116/Amazing-Saturday-2022
[debug] Command-line config: ['-F', '-vU', '--no-playlist', 'https://www.viu.com/ott/sg/en-us/vod/429116/Amazing-Saturday-2022']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, err UTF-8, pref UTF-8
[debug] yt-dlp version 2022.03.08.1 [c0c2c57d3] (source)
[debug] Lazy loading extractors is disabled
[debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
[debug] Git HEAD: 2aba16c5c
[debug] Python version 3.6.9 (CPython 64bit) - Linux-4.15.0-163-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.8, ffprobe 3.4.8
[debug] Optional libraries: brotli, Cryptodome, secretstorage, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.03.08.1, Current version: 2022.03.08.1
yt-dlp is up to date (2022.03.08.1)
[debug] [viu:ott] Extracting URL: https://www.viu.com/ott/sg/en-us/vod/429116/Amazing-Saturday-2022
[viu:ott] Getting bearer token
[viu:ott] 429116: Downloading video info
[viu:ott] Downloading just the video 429116 because of --no-playlist
[viu:ott] 429116: Downloading stream info
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[info] Available formats for 429116:
ID     EXT RESOLUTION │   FILESIZE PROTO │ VCODEC  ACODEC
──────────────────────────────────────────────────────────
s240p  mp4 240p       │  358.41MiB m3u8  │ unknown unknown
s480p  mp4 480p       │  827.23MiB m3u8  │ unknown unknown
s720p  mp4 720p       │    1.54GiB m3u8  │ unknown unknown
s1080p mp4 1080p      │    2.96GiB m3u8  │ unknown unknown
```

Thanks for fixing this!

**Comment by zackmark29** [comment]
> Your latest commit ([zackmark29@2aba16c](https://github.com/zackmark29/yt-dlp/commit/2aba16c5cfab13898a69234530564ce2715cc5c1)) is working for me now regardless of IP used to access. No need to VPN with this version.
> 
> ```
> :~/ytdl/yt-dlp$ sudo -H ./yt-dlp.sh -F -vU --no-playlist https://www.viu.com/ott/sg/en-us/vod/429116/Amazing-Saturday-2022
> [debug] Command-line config: ['-F', '-vU', '--no-playlist', 'https://www.viu.com/ott/sg/en-us/vod/429116/Amazing-Saturday-2022']
> [debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, err UTF-8, pref UTF-8
> [debug] yt-dlp version 2022.03.08.1 [c0c2c57d3] (source)
> [debug] Lazy loading extractors is disabled
> [debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
> [debug] Git HEAD: 2aba16c5c
> [debug] Python version 3.6.9 (CPython 64bit) - Linux-4.15.0-163-generic-x86_64-with-Ubuntu-18.04-bionic
> [debug] exe versions: ffmpeg 3.4.8, ffprobe 3.4.8
> [debug] Optional libraries: brotli, Cryptodome, secretstorage, mutagen, sqlite, websockets
> [debug] Proxy map: {}
> Latest version: 2022.03.08.1, Current version: 2022.03.08.1
> yt-dlp is up to date (2022.03.08.1)
> [debug] [viu:ott] Extracting URL: https://www.viu.com/ott/sg/en-us/vod/429116/Amazing-Saturday-2022
> [viu:ott] Getting bearer token
> [viu:ott] 429116: Downloading video info
> [viu:ott] Downloading just the video 429116 because of --no-playlist
> [viu:ott] 429116: Downloading stream info
> [debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
> [info] Available formats for 429116:
> ID     EXT RESOLUTION │   FILESIZE PROTO │ VCODEC  ACODEC
> ──────────────────────────────────────────────────────────
> s240p  mp4 240p       │  358.41MiB m3u8  │ unknown unknown
> s480p  mp4 480p       │  827.23MiB m3u8  │ unknown unknown
> s720p  mp4 720p       │    1.54GiB m3u8  │ unknown unknown
> s1080p mp4 1080p      │    2.96GiB m3u8  │ unknown unknown
> ```
> 
> Thanks for fixing this!

Great! Try also downloading. I haven't tested with downloading part :) I have limited data only

**Comment by uwuuuu** [comment]
I did. Tested on a couple different SG & PH locale videos. It works. 😃 

I just wasn't about to post a log of downloading a million m3u8 parts lol.

**Comment by zackmark29** [comment]
> I did. Tested on a couple different SG & PH locale videos. It works. 😃
> 
> I just wasn't about to post a log of downloading a million m3u8 parts lol.

Nice! happy to hear that.
