### ISSUE TITLE
How to remove "←[" ?

### ISSUE THREAD

**Issue by zohozer** [yt-dlp/yt-dlp#3134]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

I recently updated the yt-dlp using the "pip" package manager and I can see in console a lot of characters like this one `←[` and I want to replace them with spaces to be more readable and I can't find a way to do so. Any help will be appreciated.

`←[K[download] ←[0;94m 34.6%←[0m of 158.64MiB at ←[0;32m 3.76MiB/s←[0m ETA ←[0;33m00:27←[0mm`

**Comment by pukkandan** [comment]
`--no-colors` would probably work around the issue, but can't say what the actual issue is without verbose log
