### ISSUE TITLE
Write Subtitle file without ID

### ISSUE THREAD

**Issue by akovia** [yt-dlp/yt-dlp#3137]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

I feel like I'm overlooking something, but when I download a subtitle file with `--write-subs` the file generated includes the ID in the filename.

My -o is `%(title)s.%(ext)s`
All the files generated follow this same format except the subtitle files. 
They end up with the ID squeezed between the sub language and the vtt extension.

example
Some Video Title._en-nP7-2PuUl7o.vtt_

I process files after downloading and it's been hard dealing with this one odd file. 
Is there a way to exclude the ID?

Thanks!

**Comment by pukkandan** [comment]
`en-nP7-2PuUl7o` is the "language code" of that subtitle. See `--list-subs`

**Comment by akovia** [comment]
`en-nP7-2PuUl7o is the "language code"`

I knew I was missing something. That's really unfortunate for post processing, but at least I know I'm not doing anything wrong.

Many Thanks!
