### ISSUE TITLE
Craftsy Website Support Request

### ISSUE THREAD

**Issue by lukemax47** [yt-dlp/yt-dlp#3140]
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.03.08.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Global (I believe)

### Example URLs

https://www.craftsy.com/class/sew-your-own-designer-handbag/

### Description

Uses brightcove video player.

Can provide login details. 

### Verbose log

```shell
❯ yt-dlp craftsy.com/class/sew-your-own-designer-handbag
WARNING: [generic] The url doesn't specify the protocol, trying with http
[generic] sew-your-own-designer-handbag: Requesting header
[redirect] Following redirect to https://www.craftsy.com/class/sew-your-own-designer-handbag/
[generic] sew-your-own-designer-handbag: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] sew-your-own-designer-handbag: Downloading webpage
[generic] sew-your-own-designer-handbag: Extracting information
ERROR: Unsupported URL: https://www.craftsy.com/class/sew-your-own-designer-handbag/
```

**Comment by Bricio** [comment]
@lukemax47 
I created the new extractor. But i don't have account to see if it works for premium videos. 

For free videos and previews, it works.

Can you check if it works?
If does not works, please pm me with account info so I can check the code.

**Comment by pukkandan** [comment]
https://github.com/yt-dlp/yt-dlp/pull/3208
