### ISSUE TITLE
YouTube livestream mutli thread download (livechat+video/audio)

### ISSUE THREAD

**Issue by EraYaN** [yt-dlp/yt-dlp#3143]
### Checklist

- [X] I'm reporting a feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.03.08.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

Essentially add the live chat download to this functionality: https://github.com/yt-dlp/yt-dlp/pull/1036

Right now on live stream without any rewind/time shift function the video is lost since it will get "stuck" on downloading the livechat, and after try to grab any video and fail at that.

**Comment by pukkandan** [comment]
Requests for multithreading are tracked in https://github.com/yt-dlp/yt-dlp/issues/1918. Specifically, see point 3 of https://github.com/yt-dlp/yt-dlp/issues/1918#issuecomment-988071897
