### ISSUE TITLE
OR in --match-filter

### ISSUE THREAD

**Issue by dabreadman** [yt-dlp/yt-dlp#3144]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

Is there a way to exclude videos of a certain length when downloading a playlist? 

For example for [this](https://www.youtube.com/playlist?list=PL_aodymM3IOd-s1SSxDBaOVm87obl7gP-) playlist, I'd like to exclude videos that are between `2 minutes 30 seconds` to `4 minutes`.

**Comment by pukkandan** [comment]
See --match-filter

**Comment by pukkandan** [comment]
I did not notice that the condition you asked for needs `OR`. This is currently not possible

**Comment by pukkandan** [comment]
With b1a7cd056a4613b49f93aa249f6c7ecf5a828185, you can now do `--match-filter="duration<150" --match-filter "duration>360"`
