### ISSUE TITLE
--restrict-filenames doesn't use square brackets around video ID

### ISSUE THREAD

**Issue by bquast** [yt-dlp/yt-dlp#3147]
### Checklist

- [X] I'm reporting a feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.03.08.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

I want to have no square brackets around the video ID when using the flag --restrict-filenames

This would greatly simplify my life. Is this possible?

**Comment by pukkandan** [comment]
Use `--output`

**Comment by bquast** [comment]
Thanks, in the end I found the compatibility filename option.
