### ISSUE TITLE
--add-metadata vs --embed-metadata

### ISSUE THREAD

**Issue by afterdelight** [yt-dlp/yt-dlp#3149]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

What's the differences?

**Comment by pukkandan** [comment]
```
    --embed-metadata                 Embed metadata to the video file. Also
                                     embeds chapters/infojson if present unless
                                     --no-embed-chapters/--no-embed-info-json
                                     are used (Alias: --add-metadata)
```

**Comment by pukkandan** [comment]
Tip: Searching `--embed-metadata` in the webpage would have immediately brought this up

**Comment by afterdelight** [comment]
ok ty, sorry i just woke up
