### ISSUE TITLE
[Site Request] Audius artist pages

### ISSUE THREAD

**Issue by Dullscy** [yt-dlp/yt-dlp#315]
## Checklist

- [x] I'm reporting a site feature request
- [x] I've verified that I'm running yt-dlp version **2021.05.11**
- [x] I've searched the bugtracker for similar site feature requests including closed ones

## Description

Currently the Audius extractor supports single track urls (example: https://audius.co/pzl/tamale-100456) and playlist urls (ex: https://audius.co/pzl/playlist/pzlwip-12770). Both are working well.

My request is, if possible, support for artist page urls (example: https://audius.co/pzl) which would download all of the artist's tracks. Currently when given this url, yt-dlp goes to generic extractor and says unsupported url. thanks!

**Comment by king-millez** [comment]
API call for tracks on a user profile: [https://discovery-a.mainnet.audius.radar.tech/v1/full/users/handle/PZL/tracks?sort=date&limit=99999999](https://discovery-a.mainnet.audius.radar.tech/v1/full/users/handle/PZL/tracks?sort=date&limit=99999999)

Using '99999999' as *arbitrary big number*.

**Comment by pukkandan** [comment]
Closed in https://github.com/yt-dlp/yt-dlp/commit/98784ef8d6982a9e9dbc8893fe1206c67c371d43
