### ISSUE TITLE
-w and --no-post-overwrites

### ISSUE THREAD

**Issue by afterdelight** [yt-dlp/yt-dlp#3160]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

What does                 
--no-post-overwrites 
--no-overwrites
do in detail? 
I still don't get it after reading it. Can u provide examples for each command?

**Comment by pukkandan** [comment]
What part of its description are you confused about?

**Comment by afterdelight** [comment]
with 'yt-dlp BaW_jenozKc --write-thumbnail -x' i get:

[youtube] BaW_jenozKc: Downloading webpage
[youtube] BaW_jenozKc: Downloading android player API JSON
[info] BaW_jenozKc: Downloading 1 format(s): 140
[info] Downloading video thumbnail 41 ...
WARNING: Unable to download video thumbnail 41: HTTP Error 404: Not Found
[info] Downloading video thumbnail 40 ...
[info] Writing video thumbnail 40 to: youtube-dl test video ''_ä↭𝕐  [BaW_jenozKc].jpg
[download] Destination: youtube-dl test video ''_ä↭𝕐  [BaW_jenozKc].m4a
[download] 100% of 154.06KiB in 00:00
[FixupM4a] Correcting container of "youtube-dl test video ''_ä↭𝕐  [BaW_jenozKc].m4a"
[ExtractAudio] Skipping audio extraction since the file is already in a common audio format
[Metadata] Adding metadata to "youtube-dl test video ''_ä↭𝕐  [BaW_jenozKc].m4a"

**Comment by afterdelight** [comment]
with 'yt-dlp BaW_jenozKc --write-thumbnail -x --no-post-overwrites --no-overwrites' i get: 

[youtube] BaW_jenozKc: Downloading webpage
[youtube] BaW_jenozKc: Downloading android player API JSON
[info] BaW_jenozKc: Downloading 1 format(s): 140
[info] Downloading video thumbnail 41 ...
WARNING: Unable to download video thumbnail 41: HTTP Error 404: Not Found
[info] Downloading video thumbnail 40 ...
[info] Writing video thumbnail 40 to: youtube-dl test video ''_ä↭𝕐  [BaW_jenozKc].jpg
[download] Destination: youtube-dl test video ''_ä↭𝕐  [BaW_jenozKc].m4a
[download] 100% of 154.06KiB in 00:00
[FixupM4a] Correcting container of "youtube-dl test video ''_ä↭𝕐  [BaW_jenozKc].m4a"
[ExtractAudio] Skipping audio extraction since the file is already in a common audio format
[Metadata] Adding metadata to "youtube-dl test video ''_ä↭𝕐  [BaW_jenozKc].m4a"

**Comment by afterdelight** [comment]
no differences in output, in local storage i also get same two files:
youtube-dl test video ''_ä↭𝕐 [BaW_jenozKc].m4a
and
youtube-dl test video ''_ä↭𝕐 [BaW_jenozKc].jpg

**Comment by pukkandan** [comment]
Run the commands back to back, without deleting the files. Then `--no-overwrites` would have prevented new files from being downloaded.

I honestly don't know how to explain it any better than what the option description says

```
    -w, --no-overwrites              Do not overwrite any files
```

Once you understand `-w`, `--no-post-overwrites` is the same, but for `-x`'s output file. You cannot see this effect because you are downloading m4a format. The default format for the command I gave should be webm. You seem to have some other options in a config file that is changing the format. Try adding an `--ignore-config`

**Comment by afterdelight** [comment]
even with --no-overwrites its still deosnt downloading new file? i dont have any config connected to format changes

**Comment by afterdelight** [comment]
with only --no-post-overwrites i got .opus lie
and with --no-post-overwrites and--no-overwrites  i got .webm file
now i got even moe confused

**Comment by pukkandan** [comment]
I really have no idea how to explain this any better. Perhaps you don't know the meaning of overwrite? This might help: https://www.thefreedictionary.com/overwrite
```
Overwrite:
a. To destroy or lose (old data) by recording new data over it: accidentally overwrote an important document.
b. To record (new data) on top of already stored data, thus destroying the old data: overwrote an updated document on top of an earlier draft.
...
4. (Computer Science) to record on a storage medium, such as a magnetic disk, thus destroying what was originally recorded there
```

**Comment by afterdelight** [comment]
Fix `--no-overwrite` for playlist infojson. I saw this in release log. whats the difference --no-overwrite` vs --continue?
