### ISSUE TITLE
Don't Download Shorts when Downloading YouTube Channels/Playlists

### ISSUE THREAD

**Issue by Rockpods** [yt-dlp/yt-dlp#3165]
### Checklist

- [X] I'm reporting a site feature request
- [X] I've verified that I'm running yt-dlp version **2022.03.08.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Example URLs

https://www.youtube.com/user/Vsauce2/videos

### Description

When I try to download a youtube channel it downloads the shorts and the full-length videos. I would like an option to only download full-length videos and not shorts; for example, when I download VSauce2 it will download "The Pi Alphabet Clock #shorts" when I would like to not download any YouTube Shorts content. I hope this is clear enough.

### Verbose log

```shell
-dlp -vU https://www.youtube.com/user/Vsauce2/videos
[debug] Command-line config: ['-vU', 'https://www.youtube.com/user/Vsauce2/videos']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.03.08.2 [e491d06d3]
[debug] Python version 3.10.2 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] exe versions: ffmpeg 2022-03-03-git-72684d2c2d-full_build-www.gyan.dev (setts), ffprobe 2022-03-03-git-72684d2c2d-full_build-www.gyan.dev
[debug] Optional libraries: brotli, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.03.08.1, Current version: 2022.03.08.2
yt-dlp is up to date (2022.03.08.2)
[debug] [youtube:tab] Extracting URL: https://www.youtube.com/user/Vsauce2/videos
[youtube:tab] Vsauce2: Downloading webpage
[debug] [youtube:tab] Final URL: https://www.youtube.com/user/Vsauce2/videos
[download] Downloading playlist: Vsauce2 - Videos
[youtube:tab] UCqmugCqELzhIMNYnsjScXXw page 1: Downloading API JSON
[youtube:tab] UCqmugCqELzhIMNYnsjScXXw page 2: Downloading API JSON
[youtube:tab] UCqmugCqELzhIMNYnsjScXXw page 3: Downloading API JSON
[youtube:tab] UCqmugCqELzhIMNYnsjScXXw page 4: Downloading API JSON
[youtube:tab] UCqmugCqELzhIMNYnsjScXXw page 5: Downloading API JSON
[youtube:tab] UCqmugCqELzhIMNYnsjScXXw page 6: Downloading API JSON
[youtube:tab] UCqmugCqELzhIMNYnsjScXXw page 7: Downloading API JSON
[youtube:tab] UCqmugCqELzhIMNYnsjScXXw page 8: Downloading API JSON
[youtube:tab] UCqmugCqELzhIMNYnsjScXXw page 9: Downloading API JSON
[youtube:tab] UCqmugCqELzhIMNYnsjScXXw page 10: Downloading API JSON
[youtube:tab] UCqmugCqELzhIMNYnsjScXXw page 11: Downloading API JSON
[youtube:tab] UCqmugCqELzhIMNYnsjScXXw page 12: Downloading API JSON
[youtube:tab] UCqmugCqELzhIMNYnsjScXXw page 13: Downloading API JSON
[youtube:tab] UCqmugCqELzhIMNYnsjScXXw page 14: Downloading API JSON
[youtube:tab] playlist Vsauce2 - Videos: Downloading 423 videos
[download] Downloading video 1 of 423
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=PvPI7yxvRyY
[youtube] PvPI7yxvRyY: Downloading webpage
[youtube] PvPI7yxvRyY: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] PvPI7yxvRyY: Downloading 1 format(s): 247+251
[debug] Invoking downloader on "https://rr3---sn-q4fl6nsy.googlevideo.com/videoplayback?expire=1648021727&ei=f3w6Yr-HD6qjir4Pp8WCoAg&ip=68.0.49.129&id=o-ADfsp0pev-CI-bbcW2a_p3wPGH5P6zSYpwEFQgjX9gZc&itag=247&source=youtube&requiressl=yes&mh=eT&mm=31%2C29&mn=sn-q4fl6nsy%2Csn-q4flrnsk&ms=au%2Crdu&mv=m&mvi=3&pl=20&initcwndbps=1621250&vprv=1&mime=video%2Fwebm&gir=yes&clen=3069368&dur=40.208&lmt=1647286483139405&mt=1647999654&fvip=1&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=5437434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIgVpJC1XJEkp-LNMPV6DNtm9Bski2AXYgwSQ6LAf0L4DwCIQC-JPHwnlmm1o2nIF1leqtmGqCf3mlYISKgp0T5uODe_w%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAORFVz4NoH96QV3iFd-W4H2rCCZ4HVl5siM2AeQ3LoXVAiEAkL4QGivIF4oPrN2XOp5GIdVLyvXRm_LT-n0rkRPja94%3D"
[download] Destination: The Pi Alphabet Clock #shorts [PvPI7yxvRyY].f247.webm
[download] 100% of 2.93MiB in 00:00
[debug] Invoking downloader on "https://rr3---sn-q4fl6nsy.googlevideo.com/videoplayback?expire=1648021727&ei=f3w6Yr-HD6qjir4Pp8WCoAg&ip=68.0.49.129&id=o-ADfsp0pev-CI-bbcW2a_p3wPGH5P6zSYpwEFQgjX9gZc&itag=251&source=youtube&requiressl=yes&mh=eT&mm=31%2C29&mn=sn-q4fl6nsy%2Csn-q4flrnsk&ms=au%2Crdu&mv=m&mvi=3&pl=20&initcwndbps=1621250&vprv=1&mime=audio%2Fwebm&gir=yes&clen=554972&dur=40.241&lmt=1647285440943924&mt=1647999654&fvip=1&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=5432434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRgIhAKzsIO3Sg9scskKhGsFGuc9V3tQDm9NtrNkvPBVq6FJ-AiEApWQoNuUQ41NEjkRNGgilNDFHAvkBuNhVJYSzAuTLZxU%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAORFVz4NoH96QV3iFd-W4H2rCCZ4HVl5siM2AeQ3LoXVAiEAkL4QGivIF4oPrN2XOp5GIdVLyvXRm_LT-n0rkRPja94%3D"
[download] Destination: The Pi Alphabet Clock #shorts [PvPI7yxvRyY].f251.webm
[download] 100% of 541.96KiB in 00:00
[Merger] Merging formats into "The Pi Alphabet Clock #shorts [PvPI7yxvRyY].webm"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:The Pi Alphabet Clock #shorts [PvPI7yxvRyY].f247.webm" -i "file:The Pi Alphabet Clock #shorts [PvPI7yxvRyY].f251.webm" -c copy -map "0:v:0" -map "1:a:0" -movflags "+faststart" "file:The Pi Alphabet Clock #shorts [PvPI7yxvRyY].temp.webm"
Deleting original file The Pi Alphabet Clock #shorts [PvPI7yxvRyY].f251.webm (pass -k to keep)
Deleting original file The Pi Alphabet Clock #shorts [PvPI7yxvRyY].f247.webm (pass -k to keep)
[download] Downloading video 2 of 423
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=ofneDHUlhM0
[youtube] ofneDHUlhM0: Downloading webpage
[youtube] ofneDHUlhM0: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id

ERROR: Interrupted by user
```

**Comment by coletdjnz** [comment]
I believe shorts are <=60 seconds in length, so you could filter by that with `--match-filter`. But you might miss out on non-short videos that are less than a minute long.

One way we could implement this is for playlists, feeds etc, if a video is a short (given by the badge), we could return it using the `/shorts/` url. Then you could filter by that.

Note that I don't think there is any way to differentiate a short on the watch page.

~~technically right now you could filter by duration=None due to a bug, but that will likely be fixed soon~~

**Comment by Rockpods** [comment]
I was considering that, but the downside pushed me to open an issue. Some channels' videos are almost all under one minute. [Example 1](https://www.youtube.com/c/kraccbacc/videos); [Example 2](https://www.youtube.com/c/MemeZee); [Example 3](https://www.youtube.com/channel/UCTMGgU2G_Zz2eGA5tPFJrPg/videos)

**Comment by pukkandan** [comment]
For the given channel, I notice all shorts have `#shorts` in title. Is this always the case?

**Comment by coletdjnz** [comment]
> For the given channel, I notice all shorts have `#shorts` in title. Is this always the case?

doesn't seem like it

e.g. https://youtu.be/nNfWqnCfwl8

**Comment by Lesmiscore** [comment]
`#Shorts` is optional but mandatory to be detected as Shorts in mobile
https://support.google.com/youtube/answer/10343433

**Comment by mechanical-snail** [comment]
Note that the duration extraction for Shorts is currently broken (#3171), so `--match-filter` won't work until that is fixed, presumably in the next release.

**Comment by coletdjnz** [comment]
With https://github.com/yt-dlp/yt-dlp/commit/fd2ad7cb245423e49db1be9d9654c7dd3103619a you should be able to do

`--match-filter "original_url!*=/shorts/&url!*=/shorts/"` to filter out shorts

Note this only works in places where youtube shows the shorts thumbnail overlay, or if the link on the webpage directs you to the shorts viewer.

**Comment by eladkarako** [comment]
f.y.i. youtube now redirects `/shorts/` by itself with `HTTP 303` back to `/watch?v=`  
at least at UK (started at April 5th 2022).

**Comment by coletdjnz** [comment]
> f.y.i. youtube now redirects `/shorts/` by itself with `HTTP 303` back to `/watch?v=` at least at UK (started at April 5th 2022). https://www.youtube.com/shorts/mNj-f7CW5AM

Seeing this too. I'm assuming they are still test/rolling it out.

However for yt-dlp, as long as YouTube provides the /shorts/ link or shorts overlay (even if it redirects to /watch) then this filter should still work

**Comment by rebane2001** [comment]
> f.y.i. youtube now redirects `/shorts/` by itself with `HTTP 303` back to `/watch?v=`  

I have not seen this happening to anyone with shorts. Can you recreate a scenario where a short /shorts/ video redirects to the watchpage? (the video you linked in the example is not a short)

**Comment by 1sixth** [comment]
> With [fd2ad7c](https://github.com/yt-dlp/yt-dlp/commit/fd2ad7cb245423e49db1be9d9654c7dd3103619a) you should be able to do
> 
> `--match-filter "original_url!*=/shorts/ & url!*=/shorts/"` to filter out shorts
> 
> Note this only works in places where youtube shows the shorts thumbnail overlay, or if the link on the webpage directs you to the shorts viewer.

There seems to be some false positives:

```
$ yt-dlp --ignore-config --match-filter "original_url!*=/shorts/ & url!*=/shorts/" --verbose "https://www.youtube.com/watch?v=20hyzmP9TPg"
[debug] Command-line config: ['--ignore-config', '--match-filter', 'original_url!*=/shorts/ & url!*=/shorts/', '--verbose', 'https://www.youtube.com/watch?v=20hyzmP9TPg']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.05.18 [b14d52355]
[debug] Python version 3.9.13 (CPython 64bit) - Linux-5.18.0-x86_64-with-glibc2.34
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: ffmpeg -bsfs
[debug] exe versions: ffmpeg 4.4.1 (setts), ffprobe 4.4.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.14.1, brotli-1.0.9, certifi-2021.10.08, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.1
[debug] Proxy map: {}
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=20hyzmP9TPg
[youtube] 20hyzmP9TPg: Downloading webpage
[youtube] 20hyzmP9TPg: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 20hyzmP9TPg: Downloading 1 format(s): 313+251
[download] The Bad Science of Eyewitness Testimony does not pass filter (original_url!*=/shorts/ & url!*=/shorts/), skipping ..
$ yt-dlp --ignore-config --print "%(original_url)s" "https://www.youtube.com/watch?v=20hyzmP9TPg"
https://www.youtube.com/watch?v=20hyzmP9TPg
$ yt-dlp --ignore-config --print "%(urls)s" "https://www.youtube.com/watch?v=20hyzmP9TPg"
https://rr5---sn-oguesnd7.googlevideo.com/videoplayback?expire=1654501554&ei=UlydYri2NMzR2roP8tGT8AE&ip=[REDACTED]&id=o-ABu3dQDgtCgPf2_Hfl4qkUSpd10ItO9hILWAcbHZFcWy&itag=313&source=youtube&requiressl=yes&mh=tJ&mm=31%2C29&mn=sn-oguesnd7%2Csn-oguelnsk&ms=au%2Crdu&mv=m&mvi=5&pl=23&initcwndbps=1831250&vprv=1&mime=video%2Fwebm&gir=yes&clen=1192596189&dur=826.491&lmt=1650679592444117&mt=1654479662&fvip=3&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=5532434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIhAMemmIsmlliTGHfy7vJZ5nzZLhSnjYOYbdq7Y5KSD8jSAiBUJe_laO99BeCmlYTdPNOchqakSNTPJntfNWq9oW9j4Q%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhANQFm1boQPMj3kTxzFh3vUHway5NXK-z45WvfN81DEo5AiAmFfodZ_JKvF-ve26RY2v6cMTFseSSY4qCRBAV7PyJnw%3D%3D
https://rr5---sn-oguesnd7.googlevideo.com/videoplayback?expire=1654501554&ei=UlydYri2NMzR2roP8tGT8AE&ip=[REDACTED]&id=o-ABu3dQDgtCgPf2_Hfl4qkUSpd10ItO9hILWAcbHZFcWy&itag=251&source=youtube&requiressl=yes&mh=tJ&mm=31%2C29&mn=sn-oguesnd7%2Csn-oguelnsk&ms=au%2Crdu&mv=m&mvi=5&pl=23&initcwndbps=1831250&vprv=1&mime=audio%2Fwebm&gir=yes&clen=13967444&dur=826.521&lmt=1650677003436540&mt=1654479662&fvip=3&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=5532434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRAIgcnr28zSQKyKWpsMOdrjnf7eSItLlIaK-KeOe1to08xMCIA6lhsJzXKGOrqXU0moQTyJS24_Ytn64xF-e4_NdcmxB&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhANQFm1boQPMj3kTxzFh3vUHway5NXK-z45WvfN81DEo5AiAmFfodZ_JKvF-ve26RY2v6cMTFseSSY4qCRBAV7PyJnw%3D%3D
```

Maybe `--match-filter "original_url!*=/shorts/"` will do?

**Comment by coletdjnz** [comment]
> > With [fd2ad7c](https://github.com/yt-dlp/yt-dlp/commit/fd2ad7cb245423e49db1be9d9654c7dd3103619a) you should be able to do
> > `--match-filter "original_url!*=/shorts/ & url!*=/shorts/"` to filter out shorts
> > Note this only works in places where youtube shows the shorts thumbnail overlay, or if the link on the webpage directs you to the shorts viewer.
> 
> There seems to be some false positives:
> 
> ```
> $ yt-dlp --ignore-config --match-filter "original_url!*=/shorts/ & url!*=/shorts/" --verbose "https://www.youtube.com/watch?v=20hyzmP9TPg"
> [debug] Command-line config: ['--ignore-config', '--match-filter', 'original_url!*=/shorts/ & url!*=/shorts/', '--verbose', 'https://www.youtube.com/watch?v=20hyzmP9TPg']
> [debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
> [debug] yt-dlp version 2022.05.18 [b14d52355]
> [debug] Python version 3.9.13 (CPython 64bit) - Linux-5.18.0-x86_64-with-glibc2.34
> [debug] Checking exe version: ffprobe -bsfs
> [debug] Checking exe version: ffmpeg -bsfs
> [debug] exe versions: ffmpeg 4.4.1 (setts), ffprobe 4.4.1, rtmpdump 2.4
> [debug] Optional libraries: Cryptodome-3.14.1, brotli-1.0.9, certifi-2021.10.08, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.1
> [debug] Proxy map: {}
> [debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=20hyzmP9TPg
> [youtube] 20hyzmP9TPg: Downloading webpage
> [youtube] 20hyzmP9TPg: Downloading android player API JSON
> [debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
> [debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
> [debug] Default format spec: bestvideo*+bestaudio/best
> [info] 20hyzmP9TPg: Downloading 1 format(s): 313+251
> [download] The Bad Science of Eyewitness Testimony does not pass filter (original_url!*=/shorts/ & url!*=/shorts/), skipping ..
> $ yt-dlp --ignore-config --print "%(original_url)s" "https://www.youtube.com/watch?v=20hyzmP9TPg"
> https://www.youtube.com/watch?v=20hyzmP9TPg
> $ yt-dlp --ignore-config --print "%(urls)s" "https://www.youtube.com/watch?v=20hyzmP9TPg"
> https://rr5---sn-oguesnd7.googlevideo.com/videoplayback?expire=1654501554&ei=UlydYri2NMzR2roP8tGT8AE&ip=[REDACTED]&id=o-ABu3dQDgtCgPf2_Hfl4qkUSpd10ItO9hILWAcbHZFcWy&itag=313&source=youtube&requiressl=yes&mh=tJ&mm=31%2C29&mn=sn-oguesnd7%2Csn-oguelnsk&ms=au%2Crdu&mv=m&mvi=5&pl=23&initcwndbps=1831250&vprv=1&mime=video%2Fwebm&gir=yes&clen=1192596189&dur=826.491&lmt=1650679592444117&mt=1654479662&fvip=3&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=5532434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIhAMemmIsmlliTGHfy7vJZ5nzZLhSnjYOYbdq7Y5KSD8jSAiBUJe_laO99BeCmlYTdPNOchqakSNTPJntfNWq9oW9j4Q%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhANQFm1boQPMj3kTxzFh3vUHway5NXK-z45WvfN81DEo5AiAmFfodZ_JKvF-ve26RY2v6cMTFseSSY4qCRBAV7PyJnw%3D%3D
> https://rr5---sn-oguesnd7.googlevideo.com/videoplayback?expire=1654501554&ei=UlydYri2NMzR2roP8tGT8AE&ip=[REDACTED]&id=o-ABu3dQDgtCgPf2_Hfl4qkUSpd10ItO9hILWAcbHZFcWy&itag=251&source=youtube&requiressl=yes&mh=tJ&mm=31%2C29&mn=sn-oguesnd7%2Csn-oguelnsk&ms=au%2Crdu&mv=m&mvi=5&pl=23&initcwndbps=1831250&vprv=1&mime=audio%2Fwebm&gir=yes&clen=13967444&dur=826.521&lmt=1650677003436540&mt=1654479662&fvip=3&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=5532434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRAIgcnr28zSQKyKWpsMOdrjnf7eSItLlIaK-KeOe1to08xMCIA6lhsJzXKGOrqXU0moQTyJS24_Ytn64xF-e4_NdcmxB&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhANQFm1boQPMj3kTxzFh3vUHway5NXK-z45WvfN81DEo5AiAmFfodZ_JKvF-ve26RY2v6cMTFseSSY4qCRBAV7PyJnw%3D%3D
> ```
> 
> Maybe `--match-filter "original_url!*=/shorts/"` will do?

you are passing a non-shorts url so it has no way of knowing if it is a short or not.

Regardless I think the match-filter should be an OR, which wasn't supported at the time:
`--match-filter "original_url!*=/shorts/" --match-filter "url!*=/shorts/"` I think
