### ISSUE TITLE
Possibility to download a password protected vimeo link via URL

### ISSUE THREAD

**Issue by Kulturserver** [yt-dlp/yt-dlp#3170]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

Hi, we are using yt-dlp with a GUI in which you are able to post the desired video URL. This naturally doesn't work with password protected videos, so we tried it using the "--video-password" parameter like this: https://vimeo.com/12345%20--video-password%20password - but the download is not started then, the error log telling me to come here: 

> Unable to download webpage: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on  https://github.com/yt-dlp/yt-dlp , filling out the "Broken site" issue template properly. Confirm you are on the latest version using -U (caused by <HTTPError 404: 'Not Found'>); 

Since the problem seems to be the form of the URL and not yt-dlp itself, I posted this as a question and not a broken site. Any help or suggestion on how to handle this would be appreciated, thanks!

**Comment by pukkandan** [comment]
`--video-password` should be passed as an argument to yt-dlp, not as a part of the URL. You should ask how to pass args to the devs of the GUI you are using. Nothing we can help with.

You can also try asking in https://www.reddit.com/r/youtubedl/ if you are willing to give the name/link of the GUI

**Comment by Kulturserver** [comment]
Thanks! Was afraid that it would only work that way, but we'll probalby find a way to make the GUI listen...
