### ISSUE TITLE
Banbye support

### ISSUE THREAD

**Issue by pococito** [yt-dlp/yt-dlp#3175]
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.03.08.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Europe

### Example URLs

https://banbye.com/watch/v_ytfmvkVYLE8T

### Description

New popular video site, unsupported yet

### Verbose log

```shell
./yt-dlp https://banbye.com/watch/v_ytfmvkVYLE8T
[generic] v_ytfmvkVYLE8T: Requesting header
[redirect] Following redirect to https://banbye.com/en/watch/v_ytfmvkVYLE8T
[generic] v_ytfmvkVYLE8T: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] v_ytfmvkVYLE8T: Downloading webpage
[generic] v_ytfmvkVYLE8T: Extracting information
ERROR: Unsupported URL: https://banbye.com/en/watch/v_ytfmvkVYLE8T
```

**Comment by mm1992** [comment]
Here is a problem with BanBye support on some their videos, an example below:
`I:\Programy\yt-dlp.exe --list-formats https://banbye.com/watch/v_kb6_o1Kyq-CD
[BanBye] Extracting URL: https://banbye.com/watch/v_kb6_o1Kyq-CD
[BanBye] v_kb6_o1Kyq: Downloading JSON metadata
ERROR: [BanBye] v_kb6_o1Kyq: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U`
Same error appears on loading yt-dlp with no parameters on this video.

**Comment by nicolaasjan** [comment]
> https://banbye.com/watch/v_kb6_o1Kyq-CD

It happens on all videos with a hyphen (`-`) in the ID.

What does work, is copying the video URL via right-click and feed that to yt-dlp.
But then it saves as `480 [480].mp4`...

```shell
yt-dlp -vU --ignore-config "https://vod.banbye.com:31005/video/v_kb6_o1Kyq-CD/480.mp4"
[debug] Command-line config: ['-vU', '--ignore-config', 'https://vod.banbye.com:31005/video/v_kb6_o1Kyq-CD/480.mp4']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2023.08.14.182926 [876b70c8e] (zip)
[debug] Python 3.8.10 (CPython x86_64 64bit) - Linux-5.4.0-156-generic-x86_64-with-glibc2.29 (OpenSSL 1.1.1f  31 Mar 2020, glibc 2.31)
[debug] exe versions: ffmpeg N-111711-gd295b6b693-Nico-20230808 (fdk,setts), ffprobe N-111711-gd295b6b693-Nico-20230808, phantomjs 2.1.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.07.22, mutagen-1.46.0, secretstorage-3.3.3, sqlite3-2.6.0, websockets-11.0.3, xattr-0.9.6
[debug] Proxy map: {}
[debug] Loaded 1863 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Available version: nightly@2023.08.14.182926, Current version: nightly@2023.08.14.182926
Current Build Hash: d66b5383fd468d11b0400e423e6db8704cc0f5fcfd3db28e06d0e821ceb3a546
yt-dlp is up to date (nightly@2023.08.14.182926)
[generic] Extracting URL: https://vod.banbye.com:31005/video/v_kb6_o1Kyq-CD/480.mp4
[generic] 480: Downloading webpage
[debug] Identified a direct video link
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 480: Downloading 1 format(s): mp4
[debug] Invoking http downloader on "https://vod.banbye.com:31005/video/v_kb6_o1Kyq-CD/480.mp4"
[download] Destination: 480 [480].mp4
[download] 100% of   88.91MiB in 00:00:08 at 10.24MiB/s
```
@pukkandan

**Comment by bashonly** [comment]
@mm1992 @nicolaasjan could one of you open a new issue about this, please?

**Comment by nicolaasjan** [comment]
Done, see #7895
