### ISSUE TITLE
[youtube] Age-gate bypass gives 404 intermittently

### ISSUE THREAD

**Issue by GraOrigin** [yt-dlp/yt-dlp#319]
I updated today and noticed the new version 2021.05.11 is breaking the circumvention of age restricted content. Went back to 2021.04.22 and it works again, see terminal history 

GraOrigin@MacBook-Pro % yt-dlp -f best "obeMVmnHVjA"
[youtube] obeMVmnHVjA: Downloading webpage
[youtube] obeMVmnHVjA: Refetching age-gated info webpage
WARNING: [youtube] unable to download video info webpage: HTTP Error 404: Not Found
ERROR: Sign in to confirm your age
This video may be inappropriate for some users.
GraOrigin@MacBook-Pro % su root
Password:
root@MacBook-Pro Public % cp yt-dlp /usr/local/bin
root@MacBook-Pro Public % exit
GraOrigin@MacBook-Pro % yt-dlp -f best "obeMVmnHVjA"
[youtube] obeMVmnHVjA: Downloading webpage
[youtube] obeMVmnHVjA: Refetching age-gated info webpage
[youtube] obeMVmnHVjA: Downloading player 08244190
[youtube] obeMVmnHVjA: Downloading MPD manifest
[info] obeMVmnHVjA: Downloading format(s) 22
[download] Destination: Making Compost Extract with Jonna [obeMVmnHVjA].mp4
[download] 100% of 109.41MiB in 00:33

**Comment by pukkandan** [comment]
I will overlook it just this once, but next time, OBEY THE ISSUE TEMPLATE

---

It is not broken. But the API is sending a 404 sometimes. This could be an issue from youtube's side. If so, it will fix it self in a day or so. If not, it is generally a sign that the endpoint will be removed by youtube soon 😢

For now, just retrying the download solves the issue.

```
$ yt-dlp obeMVmnHVjA -v -F
[debug] Command-line config: ['obeMVmnHVjA', '-v', '-F']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] yt-dlp version 2021.05.11 (exe)
[debug] Plugin Extractors: ['SamplePlugin']
[debug] Python version 3.8.9 (CPython 64bit) - Windows-10-10.0.19041-SP0
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] obeMVmnHVjA: Downloading webpage
[youtube] obeMVmnHVjA: Refetching age-gated info webpage
WARNING: [youtube] unable to download video info webpage: HTTP Error 404: Not Found
ERROR: Sign in to confirm your age
This video may be inappropriate for some users.
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1117, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1138, in __extract_info
  File "yt_dlp\extractor\common.py", line 557, in extract
  File "yt_dlp\extractor\youtube.py", line 2083, in _real_extract
  File "yt_dlp\extractor\common.py", line 991, in raise_no_formats
yt_dlp.utils.ExtractorError: Sign in to confirm your age
This video may be inappropriate for some users.


$ yt-dlp obeMVmnHVjA -v -F
[debug] Command-line config: ['obeMVmnHVjA', '-v', '-F']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] yt-dlp version 2021.05.11 (exe)
[debug] Plugin Extractors: ['SamplePlugin']
[debug] Python version 3.8.9 (CPython 64bit) - Windows-10-10.0.19041-SP0
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] obeMVmnHVjA: Downloading webpage
[youtube] obeMVmnHVjA: Refetching age-gated info webpage
[youtube] obeMVmnHVjA: Downloading MPD manifest
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[info] Available formats for obeMVmnHVjA:
ID  EXT  RESOLUTION FPS |  FILESIZE   TBR PROTO | VCODEC        VBR ACODEC     ABR  ASR    NOTE
--- ---- ---------- --- - --------- ----- ----- - ----------- ----- --------- ---- ------- -----------------------------
139 m4a  audio only     |  2.29MiB    50k dash  |                   mp4a.40.5  50k 22050Hz DASH audio, m4a_dash, 22050Hz
140 m4a  audio only     |  6.08MiB   129k https |                   mp4a.40.2 129k 44100Hz tiny, m4a_dash, 44100Hz
251 webm audio only     |  6.32MiB   134k https |                   opus      134k 48000Hz tiny, webm_dash, 48000Hz
160 mp4  256x144    30  |            108k dash  | avc1.4d400b  108k                        DASH video, mp4_dash
278 webm 256x144    30  |             95k dash  | vp9           95k                        DASH video, webm_dash
133 mp4  426x240    30  |            242k dash  | avc1.4d400c  242k                        DASH video, mp4_dash
242 webm 426x240    30  |            220k dash  | vp9          220k                        DASH video, webm_dash
134 mp4  640x360    30  |  29.13MiB  620k https | avc1.4d401e  620k                        360p, mp4_dash
18  mp4  640x360    30  |  33.97MiB  723k https | avc1.42001E  723k mp4a.40.2   0k 44100Hz 360p, 44100Hz
243 webm 640x360    30  |            405k dash  | vp9          405k                        DASH video, webm_dash
135 mp4  854x480    30  |           1155k dash  | avc1.4d4014 1155k                        DASH video, mp4_dash
244 webm 854x480    30  |            752k dash  | vp9          752k                        DASH video, webm_dash
136 mp4  1280x720   30  |           2310k dash  | avc1.4d4016 2310k                        DASH video, mp4_dash
22  mp4  1280x720   30  |           2331k https | avc1.64001F 2331k mp4a.40.2   0k 44100Hz 720p, 44100Hz
247 webm 1280x720   30  |           1505k dash  | vp9         1505k                        DASH video, webm_dash
137 mp4  1920x1080  30  |           4331k dash  | avc1.64001e 4331k                        DASH video, mp4_dash
248 webm 1920x1080  30  |           2646k dash  | vp9         2646k                        DASH video, webm_dash
```

**Comment by GraOrigin** [comment]
thank you for your fast reply. Also for keeping this project alive

**Comment by colethedj** [comment]
Experiencing similar behaviour when fetching the youtube-music page (as added in commit https://github.com/yt-dlp/yt-dlp/commit/9297939ec358f24678b566b2bd2211c51f9f99ed). This is using similar method/API as the age-gate bypass.

```
[debug] Command-line config: ['https://music.youtube.com/watch?v=REDACTED', '--cookies', 'cookies.txt, '--verbose', '--skip-download']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] yt-dlp version 2021.05.11 (source)
[debug] Plugin Extractors: ['SamplePlugin']
[debug] Git HEAD: ff2751ac9
[debug] Python version 3.9.4 (CPython 64bit) - Linux-5.10.32-1-MANJARO-x86_64-with-glibc2.33
[debug] exe versions: ffmpeg 4.3.2, ffprobe 4.3.2, rtmpdump 2.4
[debug] Proxy map: {}
[youtube] REDACTED: Downloading webpage
[debug] [youtube] Extracting URL: https://music.youtube.com/watch?v=REDACTED
[youtube] REDACTED: Fetching youtube music info webpage
WARNING: [youtube] unable to download youtube music info webpage: HTTP Error 404: Not Found
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] REDACTED: Downloading format(s) 248+251
```

**Comment by colethedj** [comment]
Possibly related: https://github.com/ytdl-org/youtube-dl/issues/29037

**Comment by llacb47** [comment]
Youtube is shutting off all of their older endpoints in favor of their `youtubei` ones. `get_video_info` will probably be gone in a month of two.

![image](https://user-images.githubusercontent.com/16567977/118744489-6ce0c200-b822-11eb-951b-8e0e0240b92b.png)

**Comment by colethedj** [comment]
> Youtube is shutting off all of their older endpoints in favor of their `youtubei` ones. `get_video_info` will probably be gone in a month of two.
> 
> ![image](https://user-images.githubusercontent.com/16567977/118744489-6ce0c200-b822-11eb-951b-8e0e0240b92b.png)

Definitely seems like it. This might be worth reporting upstream, especially as I'm not sure how we'd get the age-gate bypass to work with the new endpoint. 

I'll work on migrating the new YTM info page fetch to the new API (didn't even make it to release before the API got deprecated :cry: ). 

I think the only other place we use a non-`youtubei` endpoint is for comments, but that still seems to be in use by the web UI.

**Comment by sam9116** [comment]
@colethedj  what is this `youtubei` endpoint you are talking about

**Comment by colethedj** [comment]
> @colethedj what is this `youtubei` endpoint you are talking about?

`https://www.youtube.com/youtubei/v1/<ep>`
Innertube API endpoint that YouTube Web uses (similar goes for mobile/ytm etc. clients).

**Comment by StanNieuwmans** [comment]
@colethedj 
I dont know if this helps but if you want to let get_video_info link to work for now you can add : &html5=1 to the link.
You will get something like this: https://www.youtube.com/get_video_info?html5=1&video_id={videoID}.

**Comment by colethedj** [comment]
> @colethedj
> I dont know if this helps but if you want to let get_video_info link to work for now you can add : &html5=1 to the link.
> You will get something like this: [https://www.youtube.com/get_video_info?html5=1&video_id={videoID}](https://www.youtube.com/get_video_info?html5=1&video_id=%7BvideoID%7D).

Good find! Running some tests when I'm getting 404s, this does seem to be still working for now.

**Comment by MikeTester21** [comment]
Does this youtubei way work with age restricted videos (getting video links etc)? If get_video_info dies then isn't this a big problem?

**Comment by colethedj** [comment]
We've worked out how to use the new API for the player data but yet to find a way to get around the age-gate with it :pensive:

**Comment by pukkandan** [comment]
Since there currently doesn't seem to be any way to use the new API for age-gate bypass and the old API works for now, I am closing this issue. We can open a new issue when the API breaks again

**Comment by colethedj** [comment]
Going to reopen this for the time being as we are observing intermittent 404's again. Not related to being in the EU. Possibly this time YouTube is actually shutting this endpoint down, unless there is another param that will make it work. I no longer see this API being used on some clients e.g. PS4 web, tho I haven't thoroughly checked.

If this is true, unless someone finds a new bypass/workaround (using the new API endpoint?), then we will likely require cookies to get age-restricted videos in the future, regardless of if you are in the EU or not.

https://github.com/ytdl-org/youtube-dl/issues/29086
https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass/issues/18

**Comment by MikeTester21** [comment]
so right now there is no way to get URLs of age-restricted videos anymore with this script?

**Comment by colethedj** [comment]
Do you mean downloading the age-restricted videos? If so, sort of. You'll have to use cookies from an age-verified account.

@girst has found a partial bypass using the new API, however only seems to work with some videos (apparently ones that have "embedding enabled", but not ones that have it disabled/neither). From my initial observations it's unlikely your average age-restricted video comes under this, but it's an area of investigation.
 I've implemented a draft of this into https://github.com/yt-dlp/yt-dlp/pull/328 though that PR still needs a lot of work.

**Comment by MikeTester21** [comment]
>You'll have to use cookies from an age-verified account

colethedj , so if I use this cookie method in a script and get the URL of a video - can this video be viewed (for example embed it in a page via player ) by others or only by me? I am trying to understand if cookie method is showing video just for this particular user or it just means that user with cookies can get video URL then share it with anyone like it was with get_video_info method (for few hours at least)

**Comment by colethedj** [comment]
> > You'll have to use cookies from an age-verified account
> 
> colethedj , so if I use this cookie method in a script and get the URL of a video - can this video be viewed (for example embed it in a page via player ) by others or only by me? I am trying to understand if cookie method is showing video just for this particular user or it just means that user with cookies can get video URL then share it with anyone like it was with get_video_info method (for few hours at least)

? not quite sure what you're saying sorry.
Passing cookies is letting yt-dlp access youtube through _your_ youtube account. So, if you have access to the video under your account (e.g. can view age restricted vids), yt-dlp will be able to as well.

In saying that, **do not** share your account cookies, since its providing access to your Youtube/google account.

**Comment by llacb47** [comment]
https://github.com/ytdl-org/youtube-dl/issues/29333#issuecomment-864049544 ?

**Comment by tzarebczan** [comment]
The above fix would be awesome to get in, or the one metioned here: https://github.com/ytdl-patched/ytdl-patched/commit/7371d30ec1040afcbe94b3d6ff1a28b137dc65b5

**Comment by 89z** [comment]
@tzarebczan I just checked and ytdl-patched is still using `get_video_info` for age-gated videos [1]. They do have some code using the new API [2], but in practice, it just fails every time, and falls back to the old code.

1. https://github.com/ytdl-patched/ytdl-patched/blob/d0242be2/youtube_dl/extractor/youtube.py#L1546-L1556
2. https://github.com/ytdl-patched/ytdl-patched/blob/d0242be2/youtube_dl/extractor/youtube.py#L1538-L1544

**Comment by 89z** [comment]
https://github.com/iv-org/invidious/issues/2189

https://github.com/yt-dlp/yt-dlp/issues/319
https://github.com/ytdl-org/youtube-dl/issues/29086

**Comment by pukkandan** [comment]
@89z

The patch @tzarebczan mentioned is https://github.com/yt-dlp/yt-dlp/commit/4e6767b5f2e2523ebd3dd1240584ead53e8c8905, which was applied in both ytdl-patched and yt-dlp around the same time. In fact, the dev of ytdlp-patched @nao20010128nao is an active contributor to yt-dlp

**Comment by 89z** [comment]
@pukkandan no, no its not. As can be very clearly seen by just reading this page, the patch is:

ytdl-patched/ytdl-patched@7371d30

**Comment by pukkandan** [comment]
oh right.. that was implemented by #328

**Comment by 89z** [comment]
@pukkandan I have no idea what you are talking about. My interested in this issue, is that some videos work with new API:

https://www.youtube.com/watch?v=HtVdAasjOgU

and some dont:

https://www.youtube.com/watch?v=SkRSXFQerZs

**Comment by pukkandan** [comment]
Yes, correct. We have both methods implemented in yt-dlp so that if one breaks, the other is used as fallback

**Comment by pukkandan** [comment]
This should have been closed in #328. Now with #492, we have covered all the cases of this that we possibly can. There are still some age-gate videos (See tier 3 in https://github.com/yt-dlp/yt-dlp/pull/328#issuecomment-864117168) that don't work (without cookies), but it doesn't look like anything can be done about it

**Comment by 89z** [comment]
@pukkandan https://www.youtube.com/watch?v=XgnwCQzjau8 is not a valid video...

**Comment by pukkandan** [comment]
@d9z It was at the time. I have edited the comment with a working link

**Comment by 89z** [comment]
> @D9Z It was at the time.

Thats not my username...

> I have edited the comment with a working link

@pukkandan fix here for the updated video:

https://github.com/iv-org/invidious/issues/2189#issuecomment-880139314

**Comment by pukkandan** [comment]
> Thats not my username...

oops, sorry

**Comment by rubyFeedback** [comment]
I am super-confused. Yesterday yt-dlp worked on some videos.

Today I am trying it and ... it does not work. Is Google changing things so
quickly or is the code not absolutely reliable? I can't tell.  It's even more
confusing because other people on github say it works for them but then
I try to re-produce what they did and it does not work for me. It's very
confusing.

**Comment by MinePlayersPE** [comment]
They have definitely dropped TVHTML5 as a client for get_video_info. ANDROID seems to work, however it also randomly returns a 404 as of now.

**Comment by pukkandan** [comment]
Yes, we are aware of the issue. More clients have now stopped working with `get_video_info` that is used for age-gate bypass. As soon as we find one that works, I'll update.

However, it is only a stopgap. In the long run, expect google to completely block that endpoint. Once that happens, only embeddable videos can be bypassed without auth
