### ISSUE TITLE
Website specific output template? 

### ISSUE THREAD

**Issue by atom-smasher** [yt-dlp/yt-dlp#3194]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

Is there a way to specify a special output template per website, in the config file?

eg, I want to specify a "normal" output template in the config file that I use on most websites - and I want to specify a "special" output template for use with a specific website.

Ideally, I'd like to do this automagically via the config file.

Conceptually, this might be similar to a "Host" spec in an ssh config file.

**Comment by atom-smasher** [comment]
Playing around with this, I almost kind of sort of maybe got close to something that works:

`yt-dlp --simulate --ignore-config --download-archive archive.txt --exec before_dl:'echo %(extractor)s | grep -q Bandcamp && yt-dlp -v  --config-locations ~/.config/yt-dlp/config-bandcamp --no-simulate %(webpage_url)s '   https://steviasphere.bandcamp.com/`

This actually doesn't work at all. It seems that `--simulate` is inherited by the command being run in `--exec`, even though that command explicitly invokes `--no-simulate`.

Getting rid of the `--simulate` option causes files to be downloaded twice: First with the output template specified in `~/.config/yt-dlp/config-bandcamp`, and then with the default output template. This is kind of a fail. Curiously, `archive.txt` will then contain duplicate lines, presumably because both processes have it opened for writing at the same time.

I was hoping this would work, so I could just test for a given extractor via `--exec` in my default config file, and the rest would sort itself out. I'm not there yet.

It sort of works with this in my default config:

`--exec playlist:'echo %(extractor)s | grep -q Bandcamp && yt-dlp -v  --config-locations ~/.config/yt-dlp/config-bandcamp --no-simulate %(webpage_url)s'`

But… I have to manually specify `--simulate` on the command line, so it's not fully automatic, and even then it goes into some kind of death-loop.

So, sharing some progress, and looking for better solutions, hacks, workarounds, fixes, etc.

In the meantime, I can manually specify an alternative config to do what I need. It's not ideal, but it works:

`yt-dlp    --config-locations ~/.config/yt-dlp/config-bandcamp [URL]`

**Comment by pukkandan** [comment]
The simulate is not being inherited, it looks to me like the syntax is just wrong. I could have gleamed more info only if u would provide verbose log 🤷 

Anyway, to answer your original question, (it's a bit of a gimick, but) try this: 
```shell
--parse-metadata "%(title)s-%(upload_date)s:^(?P<mytitle>.+)$"  # title-upload_date as default
--parse-metadata "%(extractor_key)s-%(title)s:^Bandcamp-(?P<mytitle>.+)$"  # title for bandcamp
--parse-metadata "%(extractor_key)s-%(title)s-%(id)s:^Youtube-(?P<mytitle>.+)$"  # title-id for youtube
-o "%(mytitle)s.%(ext)s
```

**Comment by atom-smasher** [comment]
What I'm trying/hoping to do with `--exec` is test for a condition (eg "extractor = Bandcamp") and run an alternate command, with an alternate config file, specifying alternate options.

eg, for "normal" videos I want to `--embed-thumbnail`, but for downloading an "album" that would only consume drive space by embedding the same thumbnail into multiple files; so instead, for albums, I want to specify `--no-embed-thumbnail` and `--write-thumbnail`. This seems to require a different config file (or the hassle of doing it all on the command line).

As I understand it, `--parse-metadata` can manipulate the metadata, but can't manipulate other options.

So maybe what I really want is a (feature request) new option that can regex-match a given field (eg "extractor = Bandcamp", "original_url" = "\*bandcamp\*"), then switch to a new config file as specified, and continue with the new config file, then exit. Or, is there a way to do this via `--exec`?

**Comment by pukkandan** [comment]
> What I'm trying/hoping to do with --exec is test for a condition (eg "extractor = Bandcamp") and conditionally run an alternate command, with an alternate config file, specifying alternate options.

That was not your original question! Your question was specifically about output template, which is why I replied accordingly

> So maybe what I really want is a (feature request) new option that can regex-match a given field (eg "extractor = Bandcamp", "original_url" = "*bandcamp*"), then switch to a new config file as specified, and continue with the new config file, then exit

This would be quite difficult (if not impossible) to implement properly. Many of the options have to take effect before we determine the extractor. It's also not obvious how to handle redirects etc (Since extractor can change on redirect, should config be re-applied after each redirect?). Feel free to open a feature request for this anyway

Unlike for a general implementation, these kinds of issues are probably not a concern for your own personal use. So you can stitch together a mostly working implementation using `--exec` (like you did above) or better, using a proper script. If needed, `--load-info-json`+`--write-info-json` can be used to prevent extracting the information twice

---

> Playing around with this, I almost kind of sort of maybe got close to something that works:
> 
> `yt-dlp --simulate --ignore-config --download-archive archive.txt --exec before_dl:'echo %(extractor)s | grep -q Bandcamp && yt-dlp -v --config-locations ~/.config/yt-dlp/config-bandcamp --no-simulate %(webpage_url)s ' https://steviasphere.bandcamp.com/`

The issue here is that `--exec before_dl:` is never run since you are using `--simulate`. Using `--exec pre_process:` instead should fix this

**Comment by atom-smasher** [comment]
Yeah, a short wrapper/shell script is probably best here.

```
#!/bin/sh

yt-dlp --config-locations ~/.config/yt-dlp/config-bandcamp "${@}"
```

Or, if I was really ambitious about it, I could use conditional regex matching in the shell script to select a config file. Under some use cases, that would make sense, but for me, just making a one-liner script like this for the each of the "special" cases that I need will be fine.

nb, the `"${@}"` construct allows options and arguments to be passed to yt-dlp, in addition to URLs. Different shells/environments/options may require different use of quotes.
