### ISSUE TITLE
[Question] Update Directory Name On Channel Name Change

### ISSUE THREAD

**Issue by fosam** [yt-dlp/yt-dlp#320]
## Checklist

- [X] I'm asking a question
- [X] I've looked through the README and FAQ for similar questions
- [X] I've searched the bugtracker for similar questions including closed ones

## Question

Hello!

I'm asking a question.. based on the below scenario :

for example, I'm downloading a channel called `LearningVideos` to a folder on my desktop called `LearningVideos`.

After some days the channel changes its name to `FunnyVideos`.

Is there any possible way to make yt-dlp rename the folder from the old channel name to the new one automatically when a name change is detected?

The reason i'm asking this is sometimes when i download multiple channels to folders named after each channel's name and when some of these channels make a name change on YouTube, it becomes then a tough task to verify which channels from those i downloaded have changed their name.

I hope i put this in the correct way.

**Comment by pukkandan** [comment]
> Is there any possible way to make yt-dlp rename the folder from the old channel name to the new one automatically when a name change is detected?

No. And such a feature is beyond the scope of this program

> it becomes then a tough task to verify which channels from those i downloaded have changed their name.

In the folder name (or elsewhere), record the `channel_id` as well. Since this id does not change, it should now be easy to find when a channel changes name

**Comment by fosam** [comment]
Thank you for this tip!
Will `channel_id` be recorded in a txt file or similar or will it be saved in the videos title?

**Comment by pukkandan** [comment]
> Will channel_id be recorded in a txt file or similar or will it be saved in the videos title?

Either can be done

**Comment by pukkandan** [comment]
Closing since you didnt reply. Can reopen if needed

**Comment by fosam** [comment]
> Either can be done

Sorry for the delay,

I recorded the `id` in the video title but that makes the name of the video too long, would you provide me the command(s) that can recorded the `id` to a file?

**Comment by pukkandan** [comment]
If you want to print the video id, use `--print id`, for channel id, use `--print channel_id` etc. You can also print multiple fields at once using syntax like the output template. For example, `--print "%(id)s,%(channel_id)s,%(filename)s"`

**Comment by fosam** [comment]
Thanks!

**Comment by fosam** [comment]
@pukkandan I just tested this now on Windows and it is only printed in a `CMD` window while i would like to record that info in a txt file as i mentioned above.

What do i need?

**Comment by pukkandan** [comment]
You can redirect any cmd output to a file. See https://ss64.com/nt/syntax-redirection.html
