### ISSUE TITLE
I have decryption keys, how to download Widevine L3 DRM content so I can later decrypt it on PC?

### ISSUE THREAD

**Issue by rajhlinux** [yt-dlp/yt-dlp#3201]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

I have decryption keys.

Website: Udemy.com

It seems to me that the video are cut into hundreds of little pieces which are encrypted.

How can I download all of these little chunks of encrypted video in the proper synchronized order file name?
Example: Video_1, Video_2, Video_3?

I have some tools which can do some automation to decrypt and stich the video into one piece.

Thanks.

**Comment by pukkandan** [comment]
https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy

**Comment by rajhlinux** [comment]
I bought the courses on Udemy.com and would like to download the "encrypted" video, that's all I'm trying to do here.

Not asking to break the DRM encryption or what not, just download the "encrypted" video.

Hope that's clear, if you want to be unnecessarily super strict for downloading encrypted video thats understandable, just have to ask someone who told me that I can use this "honest" tool to download "encrypted" video.

Your public image of being all "piracy" abiding is pathetic when people just want to download encrypted DRM video.

**Comment by rajhlinux** [comment]
here are for the clowns that hides this tool for not being "helpful" for piracy:

this is the command you use to download encrypted video using this "honest" program (yt-dlp):

`--allow-unplayable-formats`

thanks fake piracy abiders, now all I need to do is decrypted the video, which is hella easy.

**Comment by shirt-dev** [comment]
No support will be provided for DRM on this repo.
