### ISSUE TITLE
Download first seconds of video

### ISSUE THREAD

**Issue by MrXyfir** [yt-dlp/yt-dlp#3202]
### Checklist

- [X] I'm reporting a site feature request
- [X] I've verified that I'm running yt-dlp version **2022.03.08.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

US

### Example URLs

https://www.youtube.com/watch?v=XCspzg9-bAg

### Description

I'd like to be able to choose to download the first X seconds of a provided YouTube. For example if the video is an hour long and I only want the first minute, or it's a minute and I only want the first 10 seconds.

### Verbose log

```shell
N/A
```

**Comment by mehq** [comment]
This can be achieved using **ffmpeg**. e.g. to download first 10 seconds
```
yt_dlp --downloader ffmpeg --downloader-args "ffmpeg:-t 10"  "https://www.youtube.com/watch?v=aqz-KE-bpKQ"
```

**Comment by MrXyfir** [comment]
Amazing! Thank you.

**Comment by moschlegbz** [comment]
`yt_dlp --downloader .... `

Just a point there, on linux that's usually "yt-dlp"   (dash not underscore)
