### ISSUE TITLE
please add supervideo

### ISSUE THREAD

**Issue by Davide2009** [yt-dlp/yt-dlp#3210]
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.03.08.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

italy

### Example URLs

https://supervideo.tv/6tuwn8fexp1d

### Description

https://supervideo.tv

### Verbose log

```shell
https://supervideo.tv/6tuwn8fexp1d
```

**Comment by Bricio** [comment]
just wondering...

This link have an option to download video. 
![image](https://user-images.githubusercontent.com/216170/160308630-cf1b12f8-b647-40c5-963b-82617424e554.png)

And it works without any registration
![image](https://user-images.githubusercontent.com/216170/160308535-f1cea1ba-f48e-4b3a-b606-0914855fbf99.png)

Why do you need to someone codes yt-dlp to download it?

btw, description is not a link, verbose log is not a link either.
