### ISSUE TITLE
Possible to override --playlist-end #?

### ISSUE THREAD

**Issue by Jeeaaasus** [yt-dlp/yt-dlp#3214]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

I have `--playlist-end 10` (for downloading channels) in my config but when I want to download a full playlist, I want to disable `--playlist-end` for that run.
I'm looking for the exact the same behavior that `--no-playlist-reverse` does for `--playlist-reverse` but for `--playlist-end` instead.

The documentation says:
> --playlist-end NUMBER              -    Playlist video to end at (default is last)

But neither `--playlist-end ''` or `--playlist-end 'last'` is allowed.

Is this possible? 
Thank you for your time! :)

**Comment by pukkandan** [comment]
`--playlist-end -1` (undocumented)

When #2853 is done, there will be a better way to do this

**Comment by Jeeaaasus** [comment]
@pukkandan quick and helpful as always!

Many many thanks :)
