### ISSUE TITLE
Is there anyway to detect and download unlisted videos

### ISSUE THREAD

**Issue by Nothunpple** [yt-dlp/yt-dlp#3216]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

For example for the series drama show: https://www.youtube.com/watch?v=9TjfkXmwbTs, by the end of a video it will give user option to choose what video is gonna to play next but the all the videos will be unlisted.
We can know all the unlisted videos links but need to manual click on each video jump to get the link, is there any efficent way to grab all the unlisted videos from a channel

**Comment by pukkandan** [comment]
How is this a yt-dlp question?
