### ISSUE TITLE
bitchute intermittently fails, see plaintext output:

### ISSUE THREAD

**Issue by orgonesystems** [yt-dlp/yt-dlp#3217]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.03.08.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

usa

### Description

when downloading bitchute videos from a known good channel, where i've downloaded before using yt-dlp, without error, i get "404" video not found, and "no video formats found" concurrently.

Video link is valid, and plays.  

### Verbose log

```shell
omar@atonement:~/Videos/dailymessenger$ yt-dlp -vU https://www.bitchute.com/video/lUZf9y9NfrzI
[debug] Command-line config: ['-vU', 'https://www.bitchute.com/video/lUZf9y9NfrzI']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.03.08.1 [c0c2c57d3] (zip)
[debug] Python version 3.9.2 (CPython 64bit) - Linux-5.10.0-12-amd64-x86_64-with-glibc2.31
[debug] exe versions: ffmpeg 4.3.3-0, ffprobe 4.3.3-0, rtmpdump 2.4
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.03.08.1, Current version: 2022.03.08.1
yt-dlp is up to date (2022.03.08.1)
[debug] [BitChute] Extracting URL: https://www.bitchute.com/video/lUZf9y9NfrzI
[BitChute] lUZf9y9NfrzI: Downloading webpage
[BitChute] lUZf9y9NfrzI: Checking video URL
[BitChute] lUZf9y9NfrzI: video URL is invalid, skipping: HTTP Error 404: Not Found
ERROR: [BitChute] lUZf9y9NfrzI: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp , filling out the "Broken site" issue template properly. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1389, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1473, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1529, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 2460, in process_video_result
    self.raise_no_formats(info_dict)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 970, in raise_no_formats
    raise ExtractorError(msg, video_id=info['id'], ie=info['extractor'],
yt_dlp.utils.ExtractorError: [BitChute] lUZf9y9NfrzI: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp , filling out the "Broken site" issue template properly. Confirm you are on the latest version using  yt-dlp -U

omar@atonement:~/Videos/dailymessenger$
```

**Comment by pukkandan** [comment]
> - [X] I've checked that all provided URLs are alive and playable in a browser

Is it?

**Comment by orgonesystems** [comment]
it was last week.

i just checked again and its not playing.

sorry.   

does bitchute censor videos silently like this, and yet leave them up?

you can unfile my report, if you wish.
-- 
 Sent with Tutanota, the secure & ad-free mailbox. 



Mar 27, 2022, 00:06 by ***@***.***:

**Comment by pukkandan** [comment]
Bitchute videos can become inaccessible if there are no seeders
