### ISSUE TITLE
Add support for Wikimedia Commons in extractors

### ISSUE THREAD

**Issue by JimKillock** [yt-dlp/yt-dlp#3221]
### Checklist

- [X] I'm reporting a site feature request
- [X] I've verified that I'm running yt-dlp version **2022.03.08.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Example URLs

https://commons.wikimedia.org/wiki/File:Kunst_in_der_Steinzeit.webm

### Description

Include an extractor for Wikimedia Commons to ensure that licence information, author information and subtitle files are carried across when downloading or extracting a video file. This would be particularly useful for Peertube users who want to import creative commons videos for republication, while ensuring they comply with the CC licence conditions correctly.  

* Subtitle files are not currently named correctly; they are currently picked up but downloaded as PHP files 

### Verbose log

```shell
JIms-MacBook:kunst jimkillock$ yt-dlp --write-subs  -vU https://commons.wikimedia.org/wiki/File:Kunst_in_der_Steinzeit.webm
[debug] Command-line config: ['--write-subs', '-vU', 'https://commons.wikimedia.org/wiki/File:Kunst_in_der_Steinzeit.webm']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.03.08.1 [c0c2c57d3] (zip)
[debug] Python version 3.8.2 (CPython 64bit) - macOS-12.2.1-arm64-arm-64bit
[debug] exe versions: none
[debug] Optional libraries: sqlite
[debug] Proxy map: {}
Latest version: 2022.03.08.1, Current version: 2022.03.08.1
yt-dlp is up to date (2022.03.08.1)
[debug] [generic] Extracting URL: https://commons.wikimedia.org/wiki/File:Kunst_in_der_Steinzeit.webm
[generic] File:Kunst_in_der_Steinzeit: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] File:Kunst_in_der_Steinzeit: Downloading webpage
[generic] File:Kunst_in_der_Steinzeit: Extracting information
[debug] Looking for video embeds
[debug] Identified a HTML5 media
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[download] Downloading playlist: File:Kunst in der Steinzeit.webm - Wikimedia Commons
[generic] playlist File:Kunst in der Steinzeit.webm - Wikimedia Commons: Collected 1 videos; downloading 1 of them
[download] Downloading video 1 of 1
[debug] Downloading subtitles: en
[debug] Default format spec: best/bestvideo+bestaudio
[info] File:Kunst_in_der_Steinzeit: Downloading 1 format(s): 13
[info] Writing video subtitles to: File -Kunst in der Steinzeit.webm - Wikimedia Commons [File -Kunst_in_der_Steinzeit].en.php
[debug] Invoking downloader on "https://commons.wikimedia.org/w/api.php?action=timedtext&title=File%3AKunst_in_der_Steinzeit.webm&lang=en&trackformat=srt"
[download] Destination: File -Kunst in der Steinzeit.webm - Wikimedia Commons [File -Kunst_in_der_Steinzeit].en.php
[download] 100% of 1.13KiB in 00:00
[debug] Invoking downloader on "https://upload.wikimedia.org/wikipedia/commons/transcoded/3/38/Kunst_in_der_Steinzeit.webm/Kunst_in_der_Steinzeit.webm.360p.vp9.webm"
[download] File -Kunst in der Steinzeit.webm - Wikimedia Commons [File -Kunst_in_der_Steinzeit].webm has already been downloaded
[download] 100% of 4.74MiB
[download] Finished downloading playlist: File:Kunst in der Steinzeit.webm - Wikimedia Commons
JIms-MacBook:kunst jimkillock$ ls
File -Kunst in der Steinzeit.webm - Wikimedia Commons [File -Kunst_in_der_Steinzeit].en.php
File -Kunst in der Steinzeit.webm - Wikimedia Commons [File -Kunst_in_der_Steinzeit].webm
```

**Comment by JimKillock** [comment]
Hi there, we ended up doing the work at the yt-download repository; can I check, I assume the extractor files are easy enough to add here as well, once finished?

**Comment by pukkandan** [comment]
The extractor files can be technically copied over here as-is, but we have slightly different [coding conventions](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#yt-dlp-coding-conventions).

But if it is merged in youtube-dl, I'll just directly pull the code. So unless you want to merge it here before youtube-dl does, a separate PR is unnecessary
