### ISSUE TITLE
No longer possible to override --match-filter in cli?

### ISSUE THREAD

**Issue by Jeeaaasus** [yt-dlp/yt-dlp#3223]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

Hello, with the changes in b1a7cd0, #3144 is it still possible to override a `--match-filter` from config file?

My use case is this, I never want to download livestreams, therefore I use `--match-filter '!is_live'` in config.
Then from certain urls I want to regex match titles and add this to the command, `--match-filter '!is_live & title~=(?i)match.*words'`

But now it's not overridden anymore, how could this be done now?
Is there a better/separate way to exclude livestreams?

Thank you!

**Comment by pukkandan** [comment]
```
--no-match-filter --match-filter '!is_live & title~=(?i)match.*words'
```

**Comment by Jeeaaasus** [comment]
That works.
Thank you :)
