### ISSUE TITLE
download-archive documentation

### ISSUE THREAD

**Issue by atom-smasher** [yt-dlp/yt-dlp#3227]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

Documentation request - I'm not seeing a proper place to suggest updates to the documentation, so here I am.

From the built-in help:

``
    --download-archive FILE          Download only videos not listed in the
                                     archive file. Record the IDs of all
                                     downloaded videos in it
``

I think it should say: Record the IDs of all **newly** downloaded videos **into** it

**Comment by pukkandan** [comment]
That is not correct though. It also records videos that "has already been downloaded". See this example:
```
❯ del archive.txt && yt-dlp -f wa d-u_7WV1Yl8 DRjbuXjNwrk --download-archive archive.txt
[youtube] d-u_7WV1Yl8: Downloading webpage
[youtube] d-u_7WV1Yl8: Downloading android player API JSON
[info] d-u_7WV1Yl8: Downloading 1 format(s): 139
[download] Destination: Feel Deep Black 12K HDR 60fps ( Dolby Vision ) [d-u_7WV1Yl8].m4a
[download] 100% of 1.09MiB in 00:00
[FixupM4a] Correcting container of "Feel Deep Black 12K HDR 60fps ( Dolby Vision ) [d-u_7WV1Yl8].m4a"
[youtube] DRjbuXjNwrk: Downloading webpage
[youtube] DRjbuXjNwrk: Downloading android player API JSON
[info] DRjbuXjNwrk: Downloading 1 format(s): 139
[download] F-22 Raptor Demo Thunder Over Michigan 2016 5.1 Surround Sound Video (4K) [DRjbuXjNwrk].m4a has already been downloaded
[download] 100% of 22.40MiB
WARNING: DRjbuXjNwrk: writing DASH m4a. Only some players support this container

❯ type archive.txt
youtube d-u_7WV1Yl8
youtube DRjbuXjNwrk
```

**Comment by atom-smasher** [comment]
> That is not correct though. It also records videos that "has already been downloaded". See this example:

That's not entirely correct, either. Your example breaks if certain assumptions are not met:

1. If the title of the downloaded video changes
2. If the OUTPUT TEMPLATE changes
3. If `--restrict-filenames` is changed
4. If a different format/extension is downloaded

Also, saying  "already been downloaded" is misleading. If I have 100 downloaded videos in a directly, and delete the "archive.txt", that "archive.txt" will only re-populate with files that I attempt to re-download, and even then accounting for the assumptions listed above (and other assumptions?) that effect file-names.

Saying that “It also records videos that "has already been downloaded"” gives the impression that it reads the file-names of the videos already downloaded to the directory, and populates the "archive.txt" based on the directory contents, even if there's no attempt to -re-download those videos.

Here's two ways to break your example, every time the "archive.txt" file is deleted:
`yt-dlp -f wa d-u_7WV1Yl8 DRjbuXjNwrk -o '%(title)s-%(epoch)s.%(ext)s' --download-archive archive.txt`
`yt-dlp -f wa d-u_7WV1Yl8 DRjbuXjNwrk -o '%(title)s-%(autonumber)s.%(ext)s' --download-archive archive.txt`

**Comment by pukkandan** [comment]
> > It also records videos that "has already been downloaded"

> Also, saying "already been downloaded" is misleading.

Sorry, I should have been more clear about this. What I meant is - archive does record videos that are skipped due to being detected to have already been downloaded; and so saying that it only records newly downloaded videos is wrong. (I assumed the quotes along with the log makes that clear. But evidently not)

**Comment by atom-smasher** [comment]
I'm figuring it out, and you're helping me to figure it out, but I'm starting to see why maybe it's not yet fully/accurately documented. It's easy to see it and learn it, but it's tricky to describe and document.
