### ISSUE TITLE
CNN+

### ISSUE THREAD

**Issue by MattTheQuick** [yt-dlp/yt-dlp#3238]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.03.08.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

USA

### Description

Tried to pull down a video from CNN+. Tried passing various header data as well as a cookies.txt and the best I ever got was a .mp4 of the correct length but with no audio and no video. 

### Verbose log

```shell
.\yt-dlp.exe -vU https://plus.cnn.com/plus/title-2055653
[debug] Command-line config: ['-vU', 'https://plus.cnn.com/plus/title-2055653']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.03.08.1 [c0c2c57] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.22000-SP0
[debug] exe versions: ffmpeg N-105236-gebf1d0f4bb-20220109 (setts), ffprobe N-105236-gebf1d0f4bb-20220109
[debug] Optional libraries: brotli, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.03.08.1, Current version: 2022.03.08.1
yt-dlp is up to date (2022.03.08.1)
[debug] [generic] Extracting URL: https://plus.cnn.com/plus/title-2055653
[generic] title-2055653: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] title-2055653: Downloading webpage
[generic] title-2055653: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://plus.cnn.com/plus/title-2055653
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1389, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1459, in __extract_info
  File "yt_dlp\extractor\common.py", line 617, in extract
  File "yt_dlp\extractor\generic.py", line 3985, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://plus.cnn.com/plus/title-2055653
```

**Comment by MattTheQuick** [comment]
How should I go about getting credentials to the team for this site?

**Comment by pukkandan** [comment]
If someone wants to start working on this but don't have an account, they will ask. Some private communication (probably email) can be established at the time

**Comment by m4tu4g** [comment]
Can you link me to free content if there's any, else you can send credentials to matuag#9049 at discord

**Comment by m4tu4g** [comment]
@pukkandan 
DRMed content, can close the issue
