### ISSUE TITLE
[Question] How to select the stream quality?

### ISSUE THREAD

**Issue by serena13** [yt-dlp/yt-dlp#324]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

Excuse my English, I am not a native speaker

How can I select the quality I want in a Dash MPD stream
I read the format selection, but I don't understand how to do it, I am new to this

In my command line I put the following:

yt-dlp --allow-unplayable-formats --audio-multistreams --concurrent-fragments 5 "MyURL" -f bestvideo+bestaudio -o "%%(title)s.%%(ext)s"

In the streams that I want to download there are always two audio options, in English [en] and in Spanish [es-MX], one or the other is always downloaded randomly, I want to download the Spanish audio always

I can't select the audio ID because that number always changes randomly in the different streams

In the video when I put "bestivideo", it always downloads the one with the highest resolution (768x576, 900 ~ k) even when it does not have the highest quality, the weight of the file is always 250 mb more or less, and it looks very pixelated

I want to download the highest quality one, which is 720x540 (5000 ~ k) and it weighs between 1.5 gb to 2 gb, and it looks very good

And I can't select the video ID either because it changes randomly in different streams

These are the parameters that I get when I download:

[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] yt-dlp version 2021.05.11 (exe)
[debug] Python version 3.8.9 (CPython 64bit) - Windows-2012ServerR2-6.3.9600-SP0

[debug] exe versions: ffmpeg 2021-05-16-git-f53414a038-full_build-www.gyan.dev
[debug] Proxy map: {}
[generic] stream: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] stream: Downloading webpage
[generic] stream: Extracting information
WARNING: [generic] Unknown MIME type image/jpeg in DASH manifest
WARNING: [generic] Unknown MIME type image/jpeg in DASH manifest
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, vcodec:vp9.
2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasau
d, source, id
[info] Available formats for stream:
ID EXT RESOLUTION |   TBR PROTO | VCODEC        VBR ACODEC     ABR  ASR    NOTE
-- --- ---------- - ----- ----- - ----------- ----- --------- ---- ------- -----
2  m4a audio only |  130k dash  | mp4a.40.2 130k 48000Hz [en], DASH audio, m4a_dash, 48000Hz
3  m4a audio only |  130k dash  | mp4a.40.2 130k 48000Hz [es-MX], DASH audio, m4a_dash, 48000Hz
7  mp4 640x480    |  495k dash  | avc1.640028  495k DASH video, mp4_dash
6  mp4 720x540    | 1964k dash  | avc1.640028 1964k DASH video, mp4_dash
5  mp4 720x540    | 2698k dash  | avc1.640028 2698k DASH video, mp4_dash
4  mp4 720x540    | 3856k dash  | avc1.640028 3856k DASH video, mp4_dash
9  mp4 720x540    | 5834k dash  | avc1.640028 5834k DASH video, mp4_dash
8  mp4 768x576    |  981k dash  | avc1.640028  981k DASH video, mp4_dash

**Comment by pukkandan** [comment]
Try: `-f bv+ba[language^=es] -S br`

**Comment by serena13** [comment]
Thank you

With this command `-f bv+ba[language^=es] -S br` I get this:

```
[generic] stream: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] stream: Downloading webpage
[generic] stream: Extracting information
WARNING: [generic] Unknown MIME type image/jpeg in DASH manifest
WARNING: [generic] Unknown MIME type image/jpeg in DASH manifest
ERROR: Requested format is not available
```

I have put it like this `-f bv+ba[language^=es-MX] -S br` and it works very well
