### ISSUE TITLE
Mediaset problem after fix of nixxo

### ISSUE THREAD

**Issue by ilpadrinocl** [yt-dlp/yt-dlp#3242]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

C:\ytdlp>yt-dlp https://www.mediasetplay.mediaset.it/video/lisoladeifamosi/terza-puntata_F310817401000301 -F
[Mediaset] F310817401000301: Downloading JSON metadata
[Mediaset] F310817401000301: Downloading MPEG4 SMIL data
[Mediaset] F310817401000301: Downloading M3U SMIL data
[Mediaset] F310817401000301: Downloading m3u8 information
[Mediaset] F310817401000301: Downloading m3u8 information
WARNING: [Mediaset] Failed to download m3u8 information: HTTP Error 404: Not Found
[Mediaset] F310817401000301: Downloading JSON metadata
[info] Available formats for F310817401000301:
ID            EXT RESOLUTION │ PROTO │ VCODEC MORE INFO
──────────────────────────────────────────────────────────────
imagestream-1 fs  unknown    │ https │ images SMIL storyboards

C:\ytdlp>yt-dlp https://www.mediasetplay.mediaset.it/video/lisoladeifamosi/terza-puntata_F310817401000301
[Mediaset] F310817401000301: Downloading JSON metadata
[Mediaset] F310817401000301: Downloading MPEG4 SMIL data
[Mediaset] F310817401000301: Downloading M3U SMIL data
[Mediaset] F310817401000301: Downloading m3u8 information
[Mediaset] F310817401000301: Downloading m3u8 information
WARNING: [Mediaset] Failed to download m3u8 information: HTTP Error 404: Not Found
[Mediaset] F310817401000301: Downloading JSON metadata
ERROR: [Mediaset] F310817401000301: Requested format is not available

where i wrong?is impossible extract this file?

### Verbose log

```shell
C:\ytdlp>yt-dlp https://www.mediasetplay.mediaset.it/video/lisoladeifamosi/terza-puntata_F310817401000301 -vU
[debug] Command-line config: ['https://www.mediasetplay.mediaset.it/video/lisoladeifamosi/terza-puntata_F310817401000301', '-vU']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.03.08.1 [c0c2c57] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] exe versions: ffmpeg git-2020-08-31-4a11a6f, ffprobe git-2020-08-31-4a11a6f
[debug] Optional libraries: brotli, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.03.08.1, Current version: 2022.03.08.1
yt-dlp is up to date (2022.03.08.1)
[debug] [Mediaset] Extracting URL: https://www.mediasetplay.mediaset.it/video/lisoladeifamosi/terza-puntata_F310817401000301
[Mediaset] F310817401000301: Downloading JSON metadata
[Mediaset] F310817401000301: Downloading MPEG4 SMIL data
[Mediaset] F310817401000301: Downloading M3U SMIL data
[Mediaset] F310817401000301: Downloading m3u8 information
[Mediaset] F310817401000301: Downloading m3u8 information
WARNING: [Mediaset] Failed to download m3u8 information: HTTP Error 404: Not Found
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[Mediaset] F310817401000301: Downloading JSON metadata
[debug] Default format spec: bestvideo*+bestaudio/best
ERROR: [Mediaset] F310817401000301: Requested format is not available
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1389, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1473, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1529, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2621, in process_video_result
yt_dlp.utils.ExtractorError: [Mediaset] F310817401000301: Requested format is not available
```

**Comment by pukkandan** [comment]
By default yt-dlp tries to download only video/audio. You have to specifically request the storyboards with `-f`, like this: `-f imagestream-1`

**Comment by sulyi** [comment]
We tried that only 8mb was downloaded.

**Comment by sulyi** [comment]
Confirmed on e7870111e83033e0ac728d5a2d565d1eb146c335, but better? error.
```sh
[debug] Command-line config: ['-v', 'https://www.mediasetplay.mediaset.it/video/lisoladeifamosi/terza-puntata_F310817401000301']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8 (No ANSI), err utf-8 (No ANSI), pref UTF-8
[debug] yt-dlp version 2022.03.08.1 [c0c2c57d3] (source)
[debug] Lazy loading extractors is disabled
[debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
[debug] Git HEAD: e7870111e
[debug] Python version 3.10.2 (CPython 64bit) - Linux-5.16.13-arch1-1-x86_64-with-glibc2.35
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 5.0 (setts), ffprobe 5.0, rtmpdump 2.4
[debug] Optional libraries: sqlite
[debug] Proxy map: {}
[Mediaset] F310817401000301: Downloading JSON metadata
[debug] [Mediaset] Extracting URL: https://www.mediasetplay.mediaset.it/video/lisoladeifamosi/terza-puntata_F310817401000301
[Mediaset] F310817401000301: Downloading MPEG4 SMIL data
[Mediaset] F310817401000301: Downloading M3U SMIL data
ERROR: [Mediaset] F310817401000301: None of the available releases match the specified AssetType, ProtectionScheme, and/or Format preferences
  File "/home/arsene/PycharmProjects/_dlp/yt-dlp/yt_dlp/extractor/common.py", line 639, in extract
    ie_result = self._real_extract(url)
  File "/home/arsene/PycharmProjects/_dlp/yt-dlp/yt_dlp/extractor/mediaset.py", line 247, in _real_extract
    raise geo_e or first_e
  File "/home/arsene/PycharmProjects/_dlp/yt-dlp/yt_dlp/extractor/mediaset.py", line 229, in _real_extract
    tp_formats, tp_subtitles = self._extract_theplatform_smil(
  File "/home/arsene/PycharmProjects/_dlp/yt-dlp/yt_dlp/extractor/theplatform.py", line 48, in _extract_theplatform_smil
    raise ExtractorError(
```

**Comment by ilpadrinocl** [comment]
is impossible download?what is method for fix extractor?

**Comment by pukkandan** [comment]
Your original question gave me the impression you are asking how to download the storyboard

> C:\ytdlp>yt-dlp https://www.mediasetplay.mediaset.it/video/lisoladeifamosi/terza-puntata_F310817401000301 -F
...
imagestream-1 fs unknown │ https │ images SMIL storyboards
...
> where i wrong?is impossible extract **this file**?

But if you are trying to download the video, it appears to be DRM protected.

@nixxo can you confirm?

**Comment by nixxo** [comment]
I think the problem is that yt-dlp does not report DRM content but 404 error. I'll check why.

The video cannot be download because is DRM protected. You can only download the storyboard.

**Comment by nixxo** [comment]
I checked and the extractor works as expected. The extractor does not raise DRM exception because something is downloadable (the storyboard).

> We tried that only 8mb was downloaded.
Because is the only thing downloadable. Like reported in the formal list with `-F`

**Comment by pukkandan** [comment]
With c0b6e5c74d59d5260441ceaeb5dac3626780b31b, having only storyboards should raise a warning. Does it not in this case?

**Comment by nixxo** [comment]
To me it seems that it works has expected.

If you `--list-formats` it only gives you the storyboard.
If you force `-f bestvideo` anyway it reports that the video is DRM protected...

```
ydpm https://www.mediasetplay.mediaset.it/video/lisoladeifamosi/terza-puntata_F310817401000301 -f bestvideo
[Mediaset] F310817401000301: Downloading JSON metadata
[Mediaset] F310817401000301: Downloading MPEG4 SMIL data
[Mediaset] F310817401000301: Downloading M3U SMIL data
[Mediaset] F310817401000301: Downloading m3u8 information
[Mediaset] F310817401000301: Downloading m3u8 information
WARNING: [Mediaset] Failed to download m3u8 information: HTTP Error 404: Not Found
[Mediaset] F310817401000301: Downloading JSON metadata
WARNING: This video is DRM protected and only images are available for download. Use --list-formats to see them
ERROR: [Mediaset] F310817401000301: Requested format is not available. Use --list-formats for a list of available formats
```

**Comment by sulyi** [comment]
When trying to bypass `GeoLocationBlocked` it may change to  **ignored** `AnonymousProxyBlocked`, resulting reported `NoAssetTypeFormatMatches` exception.
