### ISSUE TITLE
TikTok userID URL does not work

### ISSUE THREAD

**Issue by Hoovier** [yt-dlp/yt-dlp#3243]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.03.08.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United States California

### Description

Attempting to give yt-dlp a link to a tiktok account using the userID does not work. Inputting the link for pokemonlife22 using the id like 'https://www.tiktok.com/@6820838815978423302' instead of 'https://www.tiktok.com/@pokemonlife22' works in browser and brings the users account up totally fine but gives an error when using yt-dlp to do it. This would be useful to fix because while users URLs change occasionally, the userID will not. 
This is my first bug report, thank you!

### Verbose log

```shell
E:\tiktok>yt-dlp.exe -vU https://www.tiktok.com/@6820838815978423302
[debug] Command-line config: ['-vU', 'https://www.tiktok.com/@6820838815978423302']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.03.08.1 [c0c2c57] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19042-SP0
[debug] exe versions: none
[debug] Optional libraries: brotli, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.03.08.1, Current version: 2022.03.08.1
yt-dlp is up to date (2022.03.08.1)
[debug] [tiktok:user] Extracting URL: https://www.tiktok.com/@6820838815978423302
[tiktok:user] 6820838815978423302: Downloading webpage
ERROR: [tiktok:user] 6820838815978423302: Unable to extract user ID; please report this issue on  https://github.com/yt-dlp/yt-dlp , filling out the "Broken site" issue template properly. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 617, in extract
  File "yt_dlp\extractor\tiktok.py", line 595, in _real_extract
  File "yt_dlp\extractor\common.py", line 1201, in _html_search_regex
  File "yt_dlp\extractor\common.py", line 1192, in _search_regex
```

**Comment by github-account1111** [comment]
Is there a way to quickly get this ID, other than Ctrl+f in source for "authorId"?

**Comment by Hoovier** [comment]
Not sure, I was just using the uploader_id that is provided by yt-dl when I run it with the -j flag with the normal username link for JSON.
