### ISSUE TITLE
[YouTube] Unable to download age-restricted video

### ISSUE THREAD

**Issue by user7230724** [yt-dlp/yt-dlp#3249]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.03.08.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Any region.

### Description

The following age-restricted video cannot be downloaded: [EuQLMXyGQOE](https://www.youtube.com/watch?v=EuQLMXyGQOE). Cookies are provided for Firefox. I am properly logged into my YT account in Firefox and can play the video. It was working few days ago, but stopped working today.

### Verbose log

```txt
[debug] Command-line config: ['-vU', '--no-cache-dir', '--ffmpeg-location', 'C:/Other/ffmpeg.exe', '--retries', 'infinite', '--fragment-retries', 'infinite', '--cookies', 'firefox', 'https://www.youtube.com/watch?v=EuQLMXyGQOE']
[debug] Encodings: locale cp65001, fs utf-8, out utf-8, err utf-8, pref cp65001
[debug] yt-dlp version 2022.03.08.1 [c0c2c57] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] exe versions: ffmpeg 4.4-full_build (setts), ffprobe 4.4-full_build
[debug] Optional libraries: brotli, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.03.08.1, Current version: 2022.03.08.1
yt-dlp is up to date (2022.03.08.1)
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=EuQLMXyGQOE
[youtube] EuQLMXyGQOE: Downloading webpage
[youtube] EuQLMXyGQOE: Downloading android player API JSON
[youtube] EuQLMXyGQOE: Downloading android agegate player API JSON
[youtube] EuQLMXyGQOE: Downloading web agegate player API JSON
ERROR: [youtube] EuQLMXyGQOE: Sign in to confirm your age. This video may be inappropriate for some users.
  File "yt_dlp\extractor\common.py", line 617, in extract
  File "yt_dlp\extractor\youtube.py", line 3339, in _real_extract
  File "yt_dlp\extractor\common.py", line 1126, in raise_no_formats
```

**Comment by user7230724** [comment]
Ok, nice! I couldn't find that issue for some reason.

@pukkandan Can you please publish a new release that includes the fix from #3233?

**Comment by Lesmiscore** [comment]
You have mistaken cookies-related option. You have to use `--cookies-from-browser firefox` to extract cookies.

**Comment by Lesmiscore** [comment]
Ah okay, makes sense

**Comment by pukkandan** [comment]
Were you using logged in cookies? If so, this is not a duplicate of #3233 and something else is going on

**Comment by pukkandan** [comment]
The log doesn't say `Extracted SAPISID cookie`, so I assume not. Then why are you even passing cookies? 🤔

**Comment by Doktor-X** [comment]
Can you guys get this video http://www.youtube.com/watch?v=FKYMogG5Y0U
