### ISSUE TITLE
[Question]Download only subtitles without A/V.

### ISSUE THREAD

**Issue by p2mgrup** [yt-dlp/yt-dlp#325]
Hello,
Could you tell me if is it possible to download only subtitles, without audio/video.
I tried to command yt-dlp --write-subs --allow-unplayable-formats "link to mpd" and subtitles has been downloaded but also audio/video is downloading.
Thanks!

**Comment by pukkandan** [comment]
Add `--skip-download`

**Comment by p2mgrup** [comment]
Thanks.
