### ISSUE TITLE
Cannot download playlist single video, link in description

### ISSUE THREAD

**Issue by rishabh3354** [yt-dlp/yt-dlp#3250]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.03.08.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

**Playlist url:**  

`https://www.youtube.com/watch?v=_vd2JyX6C1Y&list=PLKERDLXpXl_jJQiQOHDLimnulasAK3T5b&index=7
`
i am trying to dowload this video, but its giving this error. other than that i am able to download only one format at 360p, For other formats, its giving this error:-

**Version:**

i am using yt-dlp 2022.3.8.2 version released on 9 march 2022

**Os:**

ubuntu 20.04 lts

![Screenshot from 2022-03-30 23-57-19](https://user-images.githubusercontent.com/26843758/160905606-6e75c2c1-72d3-4ab9-b922-9a4e11c7debb.png)

**Output:**

```
[youtube:tab] Downloading just video _vd2JyX6C1Y because of --no-playlist
[youtube] _vd2JyX6C1Y: Downloading webpage
[youtube] _vd2JyX6C1Y: Downloading android player API JSON
[youtube] _vd2JyX6C1Y: Downloading MPD manifest
[youtube] _vd2JyX6C1Y: Downloading MPD manifest
[info] _vd2JyX6C1Y: Downloading 1 format(s): 248+251-dash
[dashsegments] Total fragments: 110
[download] Destination: /home/warlord/Downloads/YOUTUBE_DL/youtube/video/basic-player-health-with-unit-tests-tdd-in-unity-7_video_1080p (fhd).f248.webm
[download] Unknown % of ~0.00B at  224.54B/s ETA -1:59:57
downloading
could not convert string to float: 'Unknown '
```

### Verbose log

```shell
[youtube:tab] Downloading just video _vd2JyX6C1Y because of --no-playlist
[youtube] _vd2JyX6C1Y: Downloading webpage
[youtube] _vd2JyX6C1Y: Downloading android player API JSON
[youtube] _vd2JyX6C1Y: Downloading MPD manifest
[youtube] _vd2JyX6C1Y: Downloading MPD manifest
[info] _vd2JyX6C1Y: Downloading 1 format(s): 248+251-dash
[dashsegments] Total fragments: 110
[download] Destination: /home/warlord/Downloads/YOUTUBE_DL/youtube/video/basic-player-health-with-unit-tests-tdd-in-unity-7_video_1080p (fhd).f248.webm
[download] Unknown % of ~0.00B at  224.54B/s ETA -1:59:57
downloading
could not convert string to float: 'Unknown '
```

**Comment by pukkandan** [comment]
You have not provided verbose log. The issue template had clear instructions on how to do so

**Comment by pukkandan** [comment]
I see you are using some python project (that is calling yt-dlp?) Provide minimum reproducible code so we can check the issue

**Comment by pukkandan** [comment]
`process_video` is not a function in yt-dlp. So the issue is most likely in your code
