### ISSUE TITLE
[TikTok] Private Accounts/Videos "ERROR: 'NoneType' object is not iterable"

### ISSUE THREAD

**Issue by JaxonPlays** [yt-dlp/yt-dlp#3255]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

How does one be able to grab private accounts' TikToks?

**Comment by pukkandan** [comment]
https://github.com/ytdl-org/youtube-dl/blob/master/README.md#how-do-i-pass-cookies-to-youtube-dl may help
