### ISSUE TITLE
Make --downlaod-archive output same as -o template

### ISSUE THREAD

**Issue by afterdelight** [yt-dlp/yt-dlp#3259]
### Checklist

- [X] I'm reporting a feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.03.08.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

Since I use yt-dlp alot to download from generic sites, sometimes the files have same names but they dont heave unique id
currently i used upload_date as file name identifier, -o "%%(title)s [%%(upload_date)s].%%(ext)s"

Examples url:
https://www.koreanfakes.com/wp-content/uploads/2019/04/Irene-nude-Koreanfakes-1.jpg
https://www.koreanfakes.com/wp-content/uploads/2019/06/Irene-nude-Koreanfakes-1.jpg
https://www.koreanfakes.com/wp-content/uploads/2019/07/Irene-nude-Koreanfakes-1.jpg

archive download result would be
generic Irene-nude-Koreanfakes-1

and then skipped other two downloads which is bad

Solution:
Make --downlaod-archive output same as -o template to check each unique file name

new archive download result would be
generic Irene-nude-Koreanfakes-1 [20190412].jpg
generic Irene-nude-Koreanfakes-1 [20190612].jpg
generic Irene-nude-Koreanfakes-1 [20190712].jpg

TY

**Comment by pukkandan** [comment]
That will not be done. You can however use `--parse-metadata` to set whatever you want to the `id`

PS: yt-dlp is not an image downloader!

**Comment by afterdelight** [comment]
uhh , i dont really understand. so with --parse-metadata, can i modify --download-archive template?

**Comment by pukkandan** [comment]
No, but you can modify the `id`. This is not generally recommended, but I can see how this is useful for generic.

Eg:
```
❯ yt-dlp https://media.w3.org/2010/05/sintel/trailer.mp4 --download-archive x.txt --parse-metadata "webpage_url:%(id)s"
[generic] trailer: Requesting header
[MetadataParser] Parsed id from '%(webpage_url)s': 'https://media.w3.org/2010/05/sintel/trailer.mp4'
[info] https://media.w3.org/2010/05/sintel/trailer.mp4: Downloading 1 format(s): mp4
[download] trailer [https -_media.w3.org_2010_05_sintel_trailer.mp4].mp4 has already been downloaded
[download] 100% of 4.17MiB

❯ yt-dlp https://media.w3.org/2010/05/sintel/trailer.mp4 --download-archive x.txt --parse-metadata "webpage_url:%(id)s"
[generic] trailer: Requesting header
[MetadataParser] Parsed id from '%(webpage_url)s': 'https://media.w3.org/2010/05/sintel/trailer.mp4'
[download] trailer has already been recorded in the archive

❯ type x.txt
generic https://media.w3.org/2010/05/sintel/trailer.mp4
```

**Comment by pukkandan** [comment]
https://github.com/yt-dlp/yt-dlp#output-template

**Comment by afterdelight** [comment]
all right. its all good now. thank you again :))
