### ISSUE TITLE
Add `--plugin-dir` and/or `--no-plugins` options

### ISSUE THREAD

**Issue by atom-smasher** [yt-dlp/yt-dlp#3260]
### Checklist

- [X] I'm reporting a feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.03.08.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

I've got a directory: `${HOME}/bin/ytdlp_plugins/`

On the command line, if I type `yt<TAB>` in the command position, it gives me options to expand for both `yt-dlp` and `ytdlp_plugins`. This is annoying, since I'm not running anything from ytdlp_plugins directly from the command line.

Request: Can there be an option to put the `ytdlp_plugins` directory in an alternate location? So it doesn't trip up tab-completion on the command line?

Ideally, I'd like to have a `--plugins-dir` (or similar) option, so I can put the plugins directly **not** in my executables path.

**Comment by coletdjnz** [comment]
With https://github.com/yt-dlp/yt-dlp/commit/8e40b9d1ec132ae1bcac50b3ee520ece46ac9c55 there are now more locations to install plugins.

For other locations, you can modify `PYTHONPATH` to add them. However, this doesn't work for binaries and is a bit of a pain to use (especially if you want to specify a directory of plugin packages, which may be useful for GUIs) .

https://github.com/yt-dlp/yt-dlp#installing-plugins

Will keep this open to track the ability to specify a custom location that works for all distributions.

**Comment by pukkandan** [comment]
We do need `--plugin-dir` and `--no-plugin` options for future
