### ISSUE TITLE
Fixing MPEG-TS in MP4 container of videos takes more time than expected

### ISSUE THREAD

**Issue by shortthirdman** [yt-dlp/yt-dlp#3269]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.03.08.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

Fixing MPEG-TS in MP4 container process for FixupM3U8 takes more time than expected when embedding [yt-dlp](https://www.github.com/yt-dlp/yt-dlp) into Python program.

But the same finishes up in a few seconds while using command-line feature.

P.S.: I pass the same options for configuration in both the cases

### Verbose log

```shell
Downloading video from hotstar
[hotstar] 1000100150: Downloading JSON metadata
[hotstar] 1000100150: Downloading webpage
[hotstar] 1000100150: Downloading token
[hotstar] 1000100150: Downloading JSON metadata
[hotstar] 1000100150: Downloading MPD manifest
[hotstar] 1000100150: Downloading m3u8 information
[hotstar] 1000100150: Downloading m3u8 information
[hotstar] 1000100150: Downloading MPD manifest
[hotstar] 1000100150: Downloading MPD manifest
[hotstar] 1000100150: Downloading m3u8 information
[info] 1000100150: Downloading 1 format(s): sdr-hls-683-0
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 449
[download] Destination: D:\Entertainment - TV Shows\Ishqbaaaz\Episode 1 - 27 June 2016 - Meet Shivay And His Brothers.mp4
[download] 100% of 146.29MiB in 00:54
Done downloading, now converting ...

[FixupM3u8] Fixing MPEG-TS in MP4 container of "D:\Entertainment - TV Shows\Ishqbaaaz\Episode 1 - 27 June 2016 - Meet Shivay And His Brothers.mp4"
```

**Comment by pukkandan** [comment]
> when embedding [yt-dlp](https://www.github.com/yt-dlp/yt-dlp) into Python program.

Provide minimum code that we can use to reproduce your issue

**Comment by shortthirdman** [comment]
@pukkandan I am sharing a small LOC below.

Latest version of yt-dlp module is being used on `Python 3.8.10`

```
ffmpeg_path = str(Path(os.getenv('FFMPEG_HOME')) / "bin")
ydl_opts.update({'format': fid, 'outtmpl': file_name, 'merge_output_format': 'mp4', 'paths': {'home': parent},
                         'cachedir': False, 'geo_bypass': True, 'nopart': True,
                         'windowsfilenames': True, 'allow_multiple_audio_streams': True, 'no_warnings': True,
                         'config_locations': str(default_config),
                         'ffmpeg_location': ffmpeg_path, 'final_ext': 'mp4',
                         'progress_hooks': [util.ytdlp_hook],
                         'consoletitle': True,
                         'debug_printtraffic': False,
                         'postprocessor_args': {
                             'ffmpeg': {'loglevel': 'quiet'}
                         },
                         # 'postprocessors': [{
                         #     # Embed metadata in video using ffmpeg.
                         #     # ℹ️ See yt_dlp.postprocessor.FFmpegMetadataPP for the arguments it accepts
                         #     'key': 'FFmpegMetadata',
                         #     'add_chapters': False,
                         #     'add_metadata': True}]
                         })
        with yt_dlp.YoutubeDL(ydl_opts) as ydl:
            ydl.download([url])
```

**Comment by pukkandan** [comment]
`ydl_opts.update(...)`? Where is it defined? I need to be able to **run** your code to reproduce it, bruh

**Comment by pukkandan** [comment]
Also, `config_locations` is not something that can be passed in `ydl_opts`

**Comment by shortthirdman** [comment]
Okay. But `config_locations` is available in `options.py`.

```
ytdlp_opts = {
    'simulate': True,
    'quiet': True
}

default_config = Path.home() / "yt-dlp.conf"
```

**Comment by pukkandan** [comment]
options.py parses the CLI options. It is not the same as the params that `YoutubeDL` class accepts. See https://github.com/yt-dlp/yt-dlp#embedding-yt-dlp

**Comment by pukkandan** [comment]
Do I need to ask for URL now? Do you not understand what REPRODUCIBLE code means?

**Comment by pukkandan** [comment]
You are passing `simulate: True`, yet the video is downloading? 🤣

**Comment by shortthirdman** [comment]
> Do I need to ask for URL now? Do you not understand what REPRODUCIBLE code means?

You could have tried with any URL from any streaming platform. It's not specific to that..
Anyway you can try this : `https://www.hotstar.com/in/tv/ishqbaaz/9567/anika-shivaay-meet-again/1000100272`

**Comment by shortthirdman** [comment]
> You are passing `simulate: True`, yet the video is downloading? 🤣

I have cleared it first using `ydl_opts.clear()`.

**Comment by pukkandan** [comment]
not in the code you gave me

**Comment by shortthirdman** [comment]
> not in the code you gave me

You should have assumed it, since you are one of the developers/maintainers/contributors. :roll_eyes:  :unamused:

**Comment by pukkandan** [comment]
I should assume what is in your code!?

**Comment by pukkandan** [comment]
After a log of "assuming", found the issue. This is wrong
```py
    'postprocessor_args': {
        'ffmpeg': {'loglevel': 'quiet'}
    },
```

**Comment by shortthirdman** [comment]
Okay, thanks for the suggestion. Will check and revert back with the results.
