### ISSUE TITLE
How to get newest video information (description, title) from channel url using yt-dlp.

### ISSUE THREAD

**Issue by trueauracoral** [yt-dlp/yt-dlp#3273]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

I am doing some scripting with yt-dlp to get information like description `--get-description`, title `--get-title`, thumbnail `--get-thumbnail`. This works really well for video links however I would also like to be able to get this information from a channel url. I only want it from the **newest** video. I am wondering if there is some flag I can use so it only gives me info about the **newest** video from the channel url.

**Video link**:
![image](https://user-images.githubusercontent.com/87541524/161329713-4f8e4a7b-66c0-4e89-9acb-b5b15baf1f3d.png)

**Channel link**
![image](https://user-images.githubusercontent.com/87541524/161329998-3216464e-7ee4-47ca-8b66-73087049a022.png)

**Comment by pukkandan** [comment]
--playlist-end 1

**Comment by trueauracoral** [comment]
Thank you.
