### ISSUE TITLE
Youtube ID beginning with '-' not parsed correctly

### ISSUE THREAD

**Issue by rieje** [yt-dlp/yt-dlp#3274]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.03.08.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

Youtube ID beginning with '-' not parsed correctly. A Youtube ID seems to consist of 11 characters containing alphanumeric characters and `-`. If `-` is in the beginning of the ID, it is parsed as a command line option.

### Verbose log

```shell
yt-dlp -vU --merge-output-format webm --embed-metadata -o '/videos/luke-smith/Bitcoin Actually Explained - Luke Smith (20210123) -Zr7PHNAjJI.webm' '-Zr7PHNAjJI'
Usage: yt-dlp [OPTIONS] URL [URL...]
```

**Comment by jxu** [comment]
Does a full url with https prefix work? Usually in command line options, you specify `--` to indicate flags have ended.

**Comment by rieje** [comment]
Ahh yes, both full url and `--` before the last argument work. I'm guessing single quotes is not enough to prevent string beginning with `-` from being interpreted as command line option? I'll close the issue.

**Comment by nyuszika7h** [comment]
Quotes are a feature of the shell, they do not get passed to yt-dlp. They're just used to escape symbols and put spaces in an argument.

**Comment by jxu** [comment]
I didn't know yt-dl supported just plain IDs and defaulting to YouTube? Anyhow I've seen `--` mentioned in some other command line manpages. I haven't looked into how yt-dl actually parses input.

**Comment by pukkandan** [comment]
https://github.com/ytdl-org/youtube-dl#how-do-i-download-a-video-starting-with-a--
