### ISSUE TITLE
Lazy Extractors

### ISSUE THREAD

**Issue by CZeil** [yt-dlp/yt-dlp#3275]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

I have seen that it is said that it is optional to create the lazy extractors using pyinstaller, but I want to know how this affects or helps the code.

**Comment by pukkandan** [comment]
It reduces startup time

**Comment by CZeil** [comment]
But this is automatically configured when the code is installed via pip?

**Comment by pukkandan** [comment]
When you use `pip install yt-dlp`, yes. If you are installing from the git master, no

**Comment by CZeil** [comment]
Ok, thanks
