### ISSUE TITLE
Cant download video from WBM: CDX HTTP error 403?

### ISSUE THREAD

**Issue by justsandro** [yt-dlp/yt-dlp#3278]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.03.08.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

As I'm trying to launch and download a video using YT-DLP

I pasted the URL from The Wayback Machine, which was a YouTube video.

It started processing, but got stuck at: _"yt_dlp.utils.EaxtractorError: Unable to download JSON metadata: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); 
please report this issue on  https://github.com/yt-dlp/yt-dlp , filling out the "Broken site" issue template properly. Confirm you are on the latest version using  yt-dlp -U"_

Using the latest version available.

Screenshot: https://imgur.com/a/Y2K5Or
![NVIDIA_Share_gsQZQTSxVc](https://user-images.githubusercontent.com/48700575/161356548-d4b0c866-965d-47f2-a413-c0d59ca8d63a.png)

### Verbose log

```shell
[debug] Command-line config: ['-vU', 'https://web.archive.org/web/20200206160356/https://www.youtube.com/watch?v=n0G5wbk4klA']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.03.08.1 [c0c2c57] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.22000-SP0
[debug] exe versions: ffmpeg 2021-10-24-git-9df3f147f5-full_build-www.gyan.dev (setts), ffprobe 2021-10-24-git-9df3f147f5-full_build-www.gyan.dev
[debug] Optional libraries: brotli, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
```

**Comment by coletdjnz** [comment]
Hmm. I'm getting the same thing

The CDX api is returning `org.archive.util.io.RuntimeIOException: org.archive.wayback.exception.AdministrativeAccessControlException: Blocked Site Error`

**Comment by justsandro** [comment]
> Hmm. I'm getting the same thing
> 
> The CDX api is returning `org.archive.util.io.RuntimeIOException: org.archive.wayback.exception.AdministrativeAccessControlException: Blocked Site Error`
> 
> This was definitely working a couple days ago 😕

Yeah, seems weird. Not sure if this is due to bug inside the yt-dlp program or its thanks to way back machine URL.
By the way, thank you for editing the labels. This is my first post ever on GitHub, regarding a error for a software program :)

**Comment by coletdjnz** [comment]
I've pushed a partial fix that'll make this request non-fatal - it's technically not required since the download will still go through without it. Just getting metadata may not work as reliably. 

As for the actual issue, I'm not sure why the Internet Archive has blocked all YouTube watch urls in their CDX API. I've talked to some others that know a bit about the CDX API but they have no clue either.

There is *technically* a way to bypass this by using a different CDX domain/CDX server. However, their webserver for it is misconfigured and doesn't pass through duplicate queries (a requirement for our queries to function correctly) :confused:.

Hopefully this is just temporary block.

**Comment by MinePlayersPE** [comment]
> What's the "partial-fix"

@JaxonPlays It's listed in the timeline above his comment: https://github.com/yt-dlp/yt-dlp/commit/c8e856a551730c289d9ef8f0674620753de6c5be

**Comment by Diacius** [comment]
I'm also having this issue, this is the problem as YouTube will only use JW Player 360p video. Any updates?

**Comment by justsandro** [comment]
EDIT: Seems like it has errors again?
Not sure what the issue is here. It always used to work, what is going on here?

![Dy96iaXUgS](https://user-images.githubusercontent.com/48700575/165406530-146ebc41-0865-4390-96db-0077a2dcdbde.png)

**Comment by coletdjnz** [comment]
> EDIT: Seems like it has errors again? Not sure what the issue is here. It always used to work, what is going on here?
> 
> ![Dy96iaXUgS](https://user-images.githubusercontent.com/48700575/165406530-146ebc41-0865-4390-96db-0077a2dcdbde.png)
> 
> The video is in fact archived, and available on the Wayback machine. I played it myself.

This is something different

Works for me:
```
yt-dlp ytarchive:fosz5mKY9iA
[web.archive:youtube] fosz5mKY9iA: Fetching archived video file url
[web.archive:youtube] fosz5mKY9iA: Downloading CDX API JSON
[web.archive:youtube] fosz5mKY9iA: Downloading capture webpage
[web.archive:youtube] fosz5mKY9iA: Downloading CDX API JSON
[info] fosz5mKY9iA: Downloading 1 format(s): 22
```

I did notice the other day when testing this CDX issue that wayback was sometimes showing an archived video as not archived. I've seen this happen in the past too. Not sure why it happens, but I don't think there is much we can do about it since it's a server-side issue.

also make sure to put quotes around your url to escape the `&`

**Comment by coletdjnz** [comment]
Also looks like the CDX API block for /watch urls has been fixed, so will close this issue. :smiley:

**Comment by justsandro** [comment]
> Also looks like the CDX API block for /watch urls has been fixed, so will close this issue. 😃

Thanks for the reply! Appreciate all help very much
