### ISSUE TITLE
Request Support Vootkids site too

### ISSUE THREAD

**Issue by IAMMADHACKER** [yt-dlp/yt-dlp#3287]
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.03.08.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Example URLs

Single Video:- https://www.vootkids.com/movies/chhota-bheem-the-rise-of-kirmada/764459
Single Video:- https://www.vootkids.com/movies/motu-patlu-in-the-game-of-zones/939896 
Playlist Mode:- https://www.vootkids.com/shows/shiva/622158 

https://www.aha.video/kids 
Single Video:-https://www.aha.video/movie/kirshna-and-balaram-kalvakra-returns 
Playlist Mode:-https://www.aha.video/webseries/maha-ganesha 

### Description

I am requesting to add vootkids site too 
please support vootkids site to download videos and also add a feature in yt-dlp tool to login in drm protected video download like voot, vootkids ,sonyliv, aha.video etc. but only single time in a perticular dexice and then do according to account if account is able to play suscribed video so tool shoud download them and also supports multi-audio extract as well as subtitles for all sites enforcrd subtitles in every video which contains subtitles 

I also requesr to add aha.video telugu site with all above features 

### Verbose log

```shell
Nothing
```

**Comment by Ashish0804** [comment]
I already have an extractor for the mobile version (which i won't make public) but the whole platform is DRM'd.
If this has changed with the site then let me know.

**Comment by pukkandan** [comment]
> and also add a feature in yt-dlp tool to login in drm protected video download like voot, vootkids ,sonyliv, aha.video etc. 

> - [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
