### ISSUE TITLE
Reverse --batch-file

### ISSUE THREAD

**Issue by JaxonPlays** [yt-dlp/yt-dlp#3290]
### Checklist

- [X] I'm reporting a feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.03.08.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

Pretty much when using a .txt with a list of URLs, it will do it in reverse order (descending to ascending)

**Comment by coletdjnz** [comment]
I think this is out of scope / unnecessary feature - the order of the batch file / urls passed (api/cli) is a matter that should be handled externally before it is passed to yt-dlp.
