### ISSUE TITLE
Add Kodi compatible .nfo export

### ISSUE THREAD

**Issue by JimKillock** [yt-dlp/yt-dlp#3292]
### Checklist

- [X] I'm reporting a feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.03.08.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

Provide export support for Kodi .nfo files, so that metadata collected by yt-dlp can be outputted to a file that can be read by Kodi. 

Ideally, the user would have options for (a) movie NFO or (b) TV show NFO types, 

See 
* https://kodi.wiki/view/NFO_files 
* https://kodi.wiki/view/NFO_files/Templates 

The formats are, for TV shows:

```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<tvshow>
    <title></title>
    <plot></plot>
    <userrating></userrating>
    <mpaa></mpaa>
    <uniqueid type="" default="true"></uniqueid>  <!-- add a value to type="" eg imdb, tmdb, home, sport, docu, see sample below -->
    <genre></genre>
    <premiered></premiered> <!-- yyyy-mm-dd -->
    <status></status>
    <studio></studio>
    <actor>
        <name></name>
        <role></role>
        <order></order>
    </actor>
    <namedseason number="1"></namedseason>
</tvshow>
```

and for movies

```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<movie>
    <title></title>
    <originaltitle></originaltitle>
    <userrating>0</userrating>
    <plot></plot>
    <mpaa></mpaa>
    <uniqueid type="" default="true"></uniqueid> <!-- add a value to type="" eg imdb, tmdb, home, sport, docu, see sample below -->
    <genre></genre>
    <tag></tag>
    <country></country>
    <credits></credits>
    <director></director>
    <premiered></premiered> <!-- yyyy-mm-dd -->
    <studio></studio>
    <actor>
        <name></name>
        <role></role>
        <order></order>
    </actor>
</movie>
```

yt-dlp could supply`<title>` date (`<premiered>`) and description (into `<plot>`) easily enough. Optionally, it could add `<license>` in a tag, or extend it with other tags so that all the metadata (other than subs) that yt-dlp gathers is in single, standardised and machine readable file.

NB: this feature has been request at least twice (now three times!) at yt-download, see [#13588](https://github.com/ytdl-org/youtube-dl/issues/13588)

**Comment by pukkandan** [comment]
You could just use `--print-to-file` to achieve the same

**Comment by JimKillock** [comment]
@pukkandan thanks - I guess this would be similar but still require tags etc to be applied?

**Comment by pukkandan** [comment]
I don't understand your question

**Comment by pukkandan** [comment]
> so that all the metadata (other than subs) that yt-dlp gathers is in single, standardised and machine readable file.

We already do provide all information in a machine readable format! `--write-info-json`/`-j`/`-J`

But what you want is for the output to be in a very specific format. I don't think it's in scope to try and support Kodi's nfo-format natively. There are countless such formats used by various programs (even kodi uses multiple templates). You can either programmatically read the `info.json` and parse it into your desired xml format, or use `--print-to-file`. Eg:

```shell
--print-to-file '
<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<movie>
    <title>%(title)s</title>
    <originaltitle></originaltitle>
    <userrating>%(average_rating)s</userrating>
    <plot>%(description)s</plot>
    <genre>%(genre)s</genre>
    <tag>%(tag)l</tag>
    <country></country>
    <credits></credits>
    <director>%(uploader)s</director>
    <premiered>%(upload_date)s</premiered>
    <studio>%(channel)s</studio>
</movie>
' "%(id)s.nfo"
```

In this example, there is an issue of escaping the fields to be valid xml. This can be achieved by using `--replace-in-metadata`, but can be difficult. I would be willing to add a string formatting option for html-escaping (which is compatible with xml escaping), similar to what we already have for json.

**Comment by dirkf** [comment]
See also: https://github.com/ytdl-org/youtube-dl/issues/13588#issuecomment-1179046387.
