### ISSUE TITLE
Interrupted youtube live stream recordings

### ISSUE THREAD

**Issue by tokon2000** [yt-dlp/yt-dlp#3293]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

Recordings of youtube live streams are often interrupted.
yt-dlp is merging the final file, but the live stream is still online.

Is the experimental --live-from-start option the problem or can I add other options to improve the recording of youtube live streams and prevent interruptions?

> 2: [download] 120.52MiB at 12.68KiB/s (01:14:04) (frag 1541)
> 2: [download] 120.53MiB at 16.02KiB/s (01:14:04) (frag 1541)
> 2: [download] 120.53MiB at 16.02KiB/s (01:14:04) (frag 1542)
> 1: [download] 3.48GiB at  218.87B/s (01:14:04) (frag 1540)
> 1: [download] 3.48GiB at  656.55B/s (01:14:04) (frag 1540)
> 1: [download] 3.48GiB at  1.50KiB/s (01:14:04) (frag 1540)
> 1: [download] 3.48GiB at  3.21KiB/s (01:14:04) (frag 1540)
> 1: [download] 3.48GiB at  6.59KiB/s (01:14:04) (frag 1540)
> 1: [download] 3.48GiB at 13.33KiB/s (01:14:04) (frag 1540)
> 1: [download] 3.48GiB at 26.74KiB/s (01:14:04) (frag 1540)
> 1: [download] 3.48GiB at 53.29KiB/s (01:14:04) (frag 1540)
> 1: [download] 3.48GiB at 106.02KiB/s (01:14:04) (frag 1540)
> 1: [download] 3.48GiB at 210.76KiB/s (01:14:04) (frag 1540)
> 1: [download] 3.48GiB at 416.46KiB/s (01:14:04) (frag 1540)
> 1: [download] 3.48GiB at 462.51KiB/s (01:14:04) (frag 1540)
> 1: [download] 3.48GiB at 462.45KiB/s (01:14:04) (frag 1541)[youtube] 0QtJurULRi0: Downloading webpage
> [youtube] 0QtJurULRi0: Downloading android player API JSON
> [youtube] 0QtJurULRi0: Downloading MPD manifest
> [youtube] 0QtJurULRi0: Downloading MPD manifest
> [youtube] 0QtJurULRi0: Downloading webpage
> 
> 2: [download] 100% of 120.53MiB in 01:14:23[youtube] 0QtJurULRi0: Downloading android player API JSON
> [youtube] 0QtJurULRi0: Downloading MPD manifest
> [youtube] 0QtJurULRi0: Downloading MPD manifest
> 
> 1: [download] 100% of 3.48GiB in 01:14:25
> [Merger] Merging formats into "./downloads/World Surf League/20220327 Surfest - Day 6 2022-04-02 23_51 (0QtJurULRi0).mp4"
> [debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:./downloads/World Surf League/20220327 Surfest - Day 6 2022-04-02 23_51 (0QtJurULRi0).f137.mp4' -i 'file:./downloads/World Surf League/20220327 Surfest - Day 6 2022-04-02 23_51 (0QtJurULRi0).f140.mp4' -c copy -map 0:v:0 -map 1:a:0 -movflags +faststart 'file:./downloads/World Surf League/20220327 Surfest - Day 6 2022-04-02 23_51 (0QtJurULRi0).temp.mp4'
> Deleting original file ./downloads/World Surf League/20220327 Surfest - Day 6 2022-04-02 23_51 (0QtJurULRi0).f137.mp4 (pass -k to keep)
> Deleting original file ./downloads/World Surf League/20220327 Surfest - Day 6 2022-04-02 23_51 (0QtJurULRi0).f140.mp4 (pass -k to keep)

### Verbose log

```shell
[debug] Command-line config: ['--ignore-config', '--hls-prefer-native', '--hls-use-mpegts', '-f', 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best', '--retries', '5', '--cookies', 'cookies.txt', '--no-part', '--live-from-start', '-v', '-o', './downloads/World Surf League/20220327 Surfest - Day 6 2022-04-02 23_51 (0QtJurULRi0)', 'https://www.youtube.com/watch?v=0QtJurULRi0']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8 (No ANSI), err utf-8 (No ANSI), pref UTF-8
[debug] yt-dlp version 2022.03.08.1 [c0c2c57d3] (zip)
[debug] Lazy loading extractors is disabled
[debug] Python version 3.10.4 (CPython 64bit) - Linux-4.4.180+-x86_64-with-glibc2.31
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.3.3-0, ffprobe 4.3.3-0
[debug] Optional libraries: certifi, Crypto, sqlite
[debug] Proxy map: {}
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=0QtJurULRi0
```

**Comment by pukkandan** [comment]
You didn't provide verbose log, but this is likely https://github.com/yt-dlp/yt-dlp/issues/2137
