### ISSUE TITLE
`Requested format is not available` when it's available on m3u8 link (and it works with youtube-dl, but broken with yt-dlp)

### ISSUE THREAD

**Issue by dzek69** [yt-dlp/yt-dlp#3296]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.03.08.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

I have a HLS/m3u8 link (from reddit) that contains just mp4 formats (separate audio and video). If I request the mp4 format with `--format mp4` it fails, while it works with `youtube-dl`.

I red README to find a differences between `youtube-dl` and `yt-dlp` formats handling, but found no information that I should manifest my desired format in another way.

There is a little bit difference in available formats detected by `yt-dlp` and `youtube-dl` (latter has more) but I think it shouldn't matter here anyway.

EDIT: I did some more tests and it looks like it does matter probably. `youtube-dl` with `-f mp4` downloads `dash-video_2365388` format only (without an audio). And this is the format `yt-dlp` don't see. I re-read README again and requesting just the file type equals single file download, so this is a describet behavior.

So this report is more about `yt-dlp` not seeing the `dash-` formats.

```
dzek@dzek-dell:/tmp$ yt-dlp "https://v.redd.it/rne9b782td781/HLSPlaylist.m3u8?a=1651607682%2CNTUyYTU2ZTFjOTM5ZDcxYzM5YWQyOTMxZjM3MGExODk3OWQwZjU1YjdlYjNkZTUzMmUwNDg3NjU2ZTY2ZjNjYQ%3D%3D&v=1&f=hd" --list-formats
[generic] HLSPlaylist: Requesting header
[generic] HLSPlaylist: Downloading m3u8 information
[info] Available formats for HLSPlaylist:
ID        EXT RESOLUTION │   TBR PROTO  │ VCODEC        VBR ACODEC     MORE INFO
────────────────────────────────────────────────────────────────────────────────
0-audio_0 mp4 audio only │       m3u8_n │ audio only        unknown    audio 0
1-audio_0 mp4 audio only │       m3u8_n │ audio only        unknown    audio 0
349       mp4 292x288    │  349k m3u8_n │ avc1.42001e  349k video only
446       mp4 292x288    │  446k m3u8_n │ avc1.42001e  446k video only
551       mp4 324x320    │  551k m3u8_n │ avc1.42001e  551k video only
648       mp4 324x320    │  648k m3u8_n │ avc1.42001e  648k video only
952       mp4 436x432    │  952k m3u8_n │ avc1.4d001e  952k video only
1049      mp4 436x432    │ 1049k m3u8_n │ avc1.4d001e 1049k video only
1447      mp4 648x640    │ 1447k m3u8_n │ avc1.4d001f 1447k video only
1544      mp4 648x640    │ 1544k m3u8_n │ avc1.4d001f 1544k video only
```

```
dzek@dzek-dell:/tmp$ youtube-dl "https://v.redd.it/rne9b782td781/HLSPlaylist.m3u8?a=1651607682%2CNTUyYTU2ZTFjOTM5ZDcxYzM5YWQyOTMxZjM3MGExODk3OWQwZjU1YjdlYjNkZTUzMmUwNDg3NjU2ZTY2ZjNjYQ%3D%3D&v=1&f=hd" --list-fo
rmats
[Reddit] rne9b782td781: Downloading m3u8 information
[Reddit] rne9b782td781: Downloading MPD manifest
[info] Available formats for rne9b782td781:
format code          extension  resolution note
hls-0-audio_0        mp4        audio only
hls-1-audio_0        mp4        audio only
dash-audio_0_131683  m4a        audio only DASH audio  131k , m4a_dash container, mp4a.40.2 (48000Hz)
hls-349              mp4        292x288     349k , avc1.42001e, video only
hls-446              mp4        292x288     446k , avc1.42001e, video only
hls-551              mp4        324x320     551k , avc1.42001e, video only
dash-video_598829    mp4        242x240    DASH video  598k , mp4_dash container, avc1.4D401E, 30fps, video only
hls-648              mp4        324x320     648k , avc1.42001e, video only
dash-video_794222    mp4        364x360    DASH video  794k , mp4_dash container, avc1.4D401E, 30fps, video only
hls-952              mp4        436x432     952k , avc1.4d001e, video only
hls-1049             mp4        436x432    1049k , avc1.4d001e, video only
dash-video_1191980   mp4        486x480    DASH video 1191k , mp4_dash container, avc1.4D401F, 30fps, video only
hls-1447             mp4        648x640    1447k , avc1.4d001f, video only
hls-1544             mp4        648x640    1544k , avc1.4d001f, video only
dash-video_2365388   mp4        728x720    DASH video 2365k , mp4_dash container, avc1.4D401F, 30fps, video only (best)
```

### Verbose log

```shell
dzek@dzek-dell:/tmp$ yt-dlp -vU "https://v.redd.it/rne9b782td781/HLSPlaylist.m3u8?a=1651607682%2CNTUyYTU2ZTFjOTM5ZDcxYzM5YWQyOTMxZjM3MGExODk3OWQwZjU1YjdlYjNkZTUzMmUwNDg3NjU2ZTY2ZjNjYQ%3D%3D&v=1&f=hd" --format
"mp4"
[debug] Command-line config: ['-vU', 'https://v.redd.it/rne9b782td781/HLSPlaylist.m3u8?a=1651607682%2CNTUyYTU2ZTFjOTM5ZDcxYzM5YWQyOTMxZjM3MGExODk3OWQwZjU1YjdlYjNkZTUzMmUwNDg3NjU2ZTY2ZjNjYQ%3D%3D&v=1&f=hd', '--format', 'mp4']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.03.08.1 [c0c2c57d3] (zip)
[debug] Python version 3.9.2 (CPython 64bit) - Linux-5.10.16.3-microsoft-standard-WSL2-x86_64-with-glibc2.31
[debug] exe versions: ffmpeg 4.3.3-0, ffprobe 4.3.3-0
[debug] Optional libraries: sqlite
[debug] Proxy map: {}
Latest version: 2022.03.08.1, Current version: 2022.03.08.1
yt-dlp is up to date (2022.03.08.1)
[debug] [generic] Extracting URL: https://v.redd.it/rne9b782td781/HLSPlaylist.m3u8?a=1651607682%2CNTUyYTU2ZTFjOTM5ZDcxYzM5YWQyOTMxZjM3MGExODk3OWQwZjU1YjdlYjNkZTUzMmUwNDg3NjU2ZTY2ZjNjYQ%3D%3D&v=1&f=hd
[generic] HLSPlaylist: Requesting header
[debug] Identified a direct video link
[generic] HLSPlaylist: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
ERROR: [generic] HLSPlaylist: Requested format is not available
Traceback (most recent call last):
  File "/home/dzek/.local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1389, in wrapper
    return func(self, *args, **kwargs)
  File "/home/dzek/.local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1473, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/home/dzek/.local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1529, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/home/dzek/.local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 2621, in process_video_result
    raise ExtractorError('Requested format is not available', expected=True,
yt_dlp.utils.ExtractorError: [generic] HLSPlaylist: Requested format is not available
```

**Comment by pukkandan** [comment]
You are passing the hls manifest to yt-dlp, so we only extract that specific m3u8. But youtube-dl (for some reason) extracts that entire reddit post and so gives the formats in the corresponding DASH manifest as well. In my opinion, yt-dlp's behavior is correct in this case. @dirkf, what do you think?

**Comment by dirkf** [comment]
>... for some reason ...

yt-dlp:   `RedditIE._VALID_URL = r'https?://(?P<subdomain>[^/]+\.)?reddit(?:media)?\.com/r/(?P<slug>[^/]+/comments/(?P<id>[^/?#&]+))'`
yt-dl:    `RedditIE._VALID_URL = r'https?://v\.redd\.it/(?P<id>[^/?#&]+)'`
          `RedditRIE._VALID_URL = r'(?P<url>https?://(?:[^/]+\.)?reddit\.com/r/[^/]+/comments/(?P<id>[^/?#&]+))'

Obvs yt-dlp is much more specific, but doesn't catch `redd.it`. Equally yt-dl doesn't catch `redditmedia.com`.

In this case yt-dlp is doing the right thing and yt-dl ought to have sent the manifests to the generic extractor, even if yt-dl's behaviour might sometimes be more helpful.

Once yt-dl has matched for `RedditIE`, it uses secret knowledge to try for both the HLS and DASH manifests corresponding to the ID. In this case

**Comment by dzek69** [comment]
Ok, I understand.

But shouldn't `-f mp4` download the best video only format available? 
> You can also use a file extension (...) to download the best quality format of a particular file extension served as a single file, e.g. -f webm will download the best quality format with the webm extension served as a single file.

Or this is because dash/hls is not a single file so it skips that?

**Comment by pukkandan** [comment]
You are correct. Will fix that part

**Comment by rudolphos** [comment]
@bashonly I don't have time for that.. Yes, generally it works when subreddit is **public**, but download isn't working when subreddit has been set to **private**/**unlisted**.

**Comment by bashonly** [comment]
@rudolphos are you passing cookies?

**Comment by pukkandan** [comment]
> I don't have time for that..

Then we don't have time for it either. Feel free to open a proper issue if u want
