### ISSUE TITLE
YouTube won't download any res higher 1080p even if 4k available

### ISSUE THREAD

**Issue by modernCRTuser** [yt-dlp/yt-dlp#3297]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.03.08.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

Hello
For some reason yt-dlp won't download higher res than 1080p (in some rare occasions It may grab 1440p) even thought ALL videos are 100% available in 4k or higher
I download batch file from txt and use bestvideo[height<2160] and merge to mkv later on
For example 1440p only https://www.youtube.com/watch?v=LqoH4uqm9XU and https://www.youtube.com/watch?v=2trbFv8JhRw

But if I insert into cmd yt-dlp [link] it will download 4k

So I investigate and by listing formats with -F I see that only 1 4k format is available for some reason when there is usually 2-3? Whats going on with YT where did all formats go suddenly? It happens with almost every 4k video I see now and saw before
30 fps SDR of that video are also gone https://www.youtube.com/watch?v=LXb3EKWsInQ
Many of new recent 4k videos are also 1080p only even thought they are already processed and available in 1440p/4k in browser...are they moving to AV1 or something?

### Verbose log

```shell
not sure if needed plus does not work with line
```

**Comment by coletdjnz** [comment]
Please provide verbose log(s) of the command you are using

**Comment by dzek69** [comment]
4k videos are 2160px tall

With `bestvideo[height<2160]` you are specificallyasking to download anything lower than 2160px, lower than 4k, so `yt-dlp` downloads smaller videos (1440p for example). What's the problem?

Fix your command.

**Comment by modernCRTuser** [comment]
> 4k videos are 2160px tall
> 
> With `bestvideo[height<2160]` you are specifically asking to download anything lower than 2160px, lower than 4k, so `yt-dlp` downloads smaller videos (1440p for example). What's the problem?
> 
> Fix your command.

My problem is, everything up to this point was working perfectly fine for years. I did not chose 2159 for it to not work. Usually it means 'including'. It was that way in yt-dl and yt-dlp recently, too. I will try to change that to a higher value at home and test once again but I don't think it is what causes that. For some reason -F gave me less formats when I was checking, maybe youtube is up to something. I don't see webm results for example in many cases anymore. Only mp4 and av1. You probably will be able to confirm that yourself (https://www.youtube.com/watch?v=LqoH4uqm9XU have no 4k mp4 and av1 too, only one 4k option is available?)

I will try to do verbose log thing but when I tried it gave me an error that it is not possible to run with my command. But this one might be my fault

**Comment by dzek69** [comment]
Missing webm formats may be related to this bug (fixed, but not released: #3270)

**Comment by fennectech** [comment]
im still seeing this with master pulled today   https://www.youtube.com/watch?v=Ax0XD0qAekc&list=PLTNHoJyuC-XTV4U7Zx-DmdKT5McXEGqSh on this video

**Comment by pukkandan** [comment]
@fennectech 
![image](https://user-images.githubusercontent.com/6623388/187007814-3cc14503-03c3-4ddc-9f63-1a60fdfee15c.png)

**Comment by fennectech** [comment]
Im an idiot.   There are very similar videos that *ARE* 4k.

**Comment by lgis80boy** [comment]
if your os installed ffmpeg , yt-dlp can download 1080P or 4K video
