### ISSUE TITLE
[Feature Request] Add yt-dlp to chocolatey

### ISSUE THREAD

**Issue by MrDemous** [yt-dlp/yt-dlp#330]
- [x ] I'm reporting a feature request
- [ x] I've verified that I'm running yt-dlp version **2021.05.20**
- [x ] I've searched the bugtracker for similar feature requests including closed ones

## Description

Is it possible to add yt-dlp to chocolatey package manager repository? It'll make it easier to install and update yt-dlp on Windows.

**Comment by pukkandan** [comment]
I don't use chocolatey and am not familiar with their packaging system. If you can make a PR to expand build.yml to including choco packaging, I will merge it

**Comment by MrDemous** [comment]
I'm sorry I don't code so I don't know how to do it. I just made the request so that if you or anyone else can do it in the future that'd be a great addition.

**Comment by TheCakeIsNaOH** [comment]
I've created a package, it is current in moderation:
https://community.chocolatey.org/packages/yt-dlp/2021.09.02
