### ISSUE TITLE
rename downloaded files

### ISSUE THREAD

**Issue by afterdelight** [yt-dlp/yt-dlp#3301]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

So I downloaded the files with format "%(title)s.%(ext)s". Now i want to rename all downloaded files in the folder 
to "%(title)s [%(id)s].%(ext)s"
How to do that with downloaded .json and jq? I'm clueless. TY.

**Comment by flashdagger** [comment]
Will this bash script do? You don't even need jq.
```bash
#!/bin/bash

for file in *.info.json; do
    old_name=$(yt-dlp --load-info-json "$file" --print filename -o "%(title)s.%(ext)s")
    new_name=$(yt-dlp --load-info-json "$file" --print filename -o "%(title)s [%(id)s].%(ext)s")
    mv -v "$old_name" "$new_name"
done
```

**Comment by afterdelight** [comment]
TY. i'm on windows 10. will that script works on windows?

**Comment by flashdagger** [comment]
On Windows you can use a batch file script. It's almost the same.
```batch
@ECHO OFF
setlocal enableDelayedExpansion

FOR /R %%F in (*.info.json) DO (
    FOR /F "tokens=* delims=" %%g IN ('yt-dlp --load-info-json "%%F" --print filename -o "%%(title)s.%%(ext)s"') DO (SET "old_name=%%g")
    FOR /F "tokens=* delims=" %%g IN ('yt-dlp --load-info-json "%%F" --print filename -o "%%(title)s [%%(id)s].%%(ext)s"') DO (SET "new_name=%%g")
    RENAME "!old_name!" "!new_name!"
)
```

**Comment by flashdagger** [comment]
That's awesome! If it's only one file, then it can be renamed manually.

**Comment by afterdelight** [comment]
all right, thanks!
