### ISSUE TITLE
yt-dlp postprocessing not merging all file formats together

### ISSUE THREAD

**Issue by gimmeAll** [yt-dlp/yt-dlp#3305]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.03.08.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

yt-dlp's postprocessing doesnt seem to combine the video, audio, and subs together into the webm container, and due to this those files stay seperate and unplayable. It cannot combine these files from a postprocessing error stating that the video file directory cannot be found, when indeed it can, and it does exist. Some videos this issue does not transpire upon, but it seems that this video, and certain others, have this issue. If my wording is off when trying to explain this bug, i hope the verbose log will clear that up.

### Verbose log

```shell
[youtube] CXUKjHzoMl4: Downloading webpage
[youtube] CXUKjHzoMl4: Downloading android player API JSON
[info] CXUKjHzoMl4: Downloading 1 format(s): 313+258
[info] Writing video subtitles to: Pop 'er in Reverse! [CXUKjHzoMl4].en.vtt
[download] Destination: Pop 'er in Reverse! [CXUKjHzoMl4].en.vtt
[download] 100% of 3.26KiB in 00:00
WARNING: Requested formats are incompatible for merge and will be merged into mkv
[download] Destination: Pop 'er in Reverse! [CXUKjHzoMl4].f313.webm
[download] 100% of 201.33MiB in 00:10
[download] Destination: Pop 'er in Reverse! [CXUKjHzoMl4].f258.m4a
[download] 100% of 6.49MiB in 00:01
[Merger] Merging formats into "Pop 'er in Reverse! [CXUKjHzoMl4].mkv"
ERROR: Postprocessing: file:Pop 'er in Reverse! [CXUKjHzoMl4].f313.webm: No such file or directory
```

**Comment by pukkandan** [comment]
From the limited information you have given, I cannot reproduce. Provide proper verbose logs
