### ISSUE TITLE
Request: Can we add a new option `--no-multifeed` and have the existing `--no-playlist` not apply to multifeed videos?

### ISSUE THREAD

**Issue by danielyli** [yt-dlp/yt-dlp#3306]
### Checklist

- [X] I'm reporting a feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.03.08.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

## Background info

Currently the `--no-playlist` option causes yt-dlp to download only the video when a URL refers to both a video and a playlist. However, it also causes yt-dlp to download only one video when the URL refers to a multifeed video.

Multifeed videos are sometimes used in live broadcasts. They are not playlists, but instead are different “angles” of a live event.

## Feature request

It would be great if yt-dlp had the following pair of changes:

1. The existing `--no-playlist` option no longer has any effect on multifeed videos.
2. A new option, `--no-multifeed`, is added that does what `--no-playlist` currently does for multifeed videos.

## Example video

For example, see these two videos:

```
https://www.youtube.com/watch?v=7jQ5wLZ6Pj4
https://www.youtube.com/watch?v=mp0TW8vkCLg
```

When downloading either video above, we see:

```
$ yt-dlp 7jQ5wLZ6Pj4
[youtube] 7jQ5wLZ6Pj4: Downloading webpage
[youtube] 7jQ5wLZ6Pj4: Downloading android player API JSON
[youtube] Downloading multifeed video (mp0TW8vkCLg, 7jQ5wLZ6Pj4) - add --no-playlist to just download video 7jQ5wLZ6Pj4
[download] Downloading playlist: Iridium-5 Mission - Countdown Net - Audio Only
[youtube] playlist Iridium-5 Mission - Countdown Net - Audio Only: Collected 2 videos; downloading 2 of them
[download] Downloading video 1 of 2
(... etc ...)
```

```
$ yt-dlp mp0TW8vkCLg
[youtube] mp0TW8vkCLg: Downloading webpage
[youtube] mp0TW8vkCLg: Downloading android player API JSON
[youtube] Downloading multifeed video (mp0TW8vkCLg, 7jQ5wLZ6Pj4) - add --no-playlist to just download video mp0TW8vkCLg
[download] Downloading playlist: Iridium-5 Mission
[youtube] playlist Iridium-5 Mission: Collected 2 videos; downloading 2 of them
[download] Downloading video 1 of 2
```

**Comment by pukkandan** [comment]
Keep in mind that yt-dlp is not just a youtube downloader, but instead supports many other sites. Generally speaking, a multifeed video is just a playlist where the URL also refers to a single video. Hence why `--no-playlist` is used. Many other sites have playlist-like URLs that are not quite playlists in the strictest sense. Would they need new options like `--no-anthology` (for billibilli) etc?

in practice, why do you want it to be 2 separate options? You could permanently keep `--no-playlist` in the config and just remove the `v=` part from the URL when downloading a playlist

FYI, It is also possible to do `yt-dlp 'https://www.youtube.com/watch?v=mp0TW8vkCLg#__youtubedl_smuggle={"force_singlefeed":true}'` to force single feed

**Comment by fstirlitz** [comment]
Wouldn’t it make sense to handle YouTube multifeed like a case of #389?

**Comment by pukkandan** [comment]
This is not different formats of the same video. The videos in a multifeed have different id, title and other metadata
