### ISSUE TITLE
[facebook] unable to extract uploader

### ISSUE THREAD

**Issue by FattsoCattso** [yt-dlp/yt-dlp#3310]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.03.08.1**. ([update instructions](https://github.com/yt-dlp/yt-dlp#update))
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Germany

### Description

yt-dpl is showing that its unable to extract uploader from facebook. Im trying to download a private live video that I want to watch later. its still downloading but 50KiB/s.

### Verbose log

```shell
yt-dlp -vU "https://www.facebook.com/XXXXXX/videos/XXXXXX" --cookies-from-browser chrome -f b
[Cookies] Extracting cookies from chrome
[Cookies] Extracted 52 cookies from chrome
[facebook] XXXXXXXXX: Downloading webpage
[facebook] XXXXXXXXX: Downloading MPD manifest
WARNING: [facebook] unable to extract uploader; please report this issue on  https://github.com/yt-dlp/yt-dlp , filling out the "Broken site" issue template properly. Confirm you are on the latest version using  yt-dlp -U
```

**Comment by FattsoCattso** [comment]
later on it shows me Got server HTTP error: Downloaded 69158355 bytes, expected 102822497 bytes. Retrying (attempt 2 of 10)

**Comment by pukkandan** [comment]
Provide full verbose logs without redacting URL. Also, take a look at existing facebook issues first

**Comment by FattsoCattso** [comment]
> Provide full verbose logs. Also, take a look at existing facebook issues first

yt-dlp -vU "https://www.facebook.com/100002799937746/videos/680525866590264/" --cookies-from-browser chrome -f b
