### ISSUE TITLE
You are using an unsupported version of Python

### ISSUE THREAD

**Issue by mayeaux** [yt-dlp/yt-dlp#3317]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

You are using an unsupported version of Python

Nothing works

**Comment by mayeaux** [comment]
`python3.9` is installed but it will never use it

**Comment by gamer191** [comment]
What operating system are you using?

**Comment by gamer191** [comment]
And are you able to post verbose logs? Or is the entire output:
```
You are using an unsupported version of Python
```

**Comment by Ashish0804** [comment]
No question asked. No logs provided. 

Sad that we don't have a troll tag

**Comment by pukkandan** [comment]
> python3.9 is installed but it will never use it

You need to give more information than that...

If you are on UNIX and using the binary from release, it looks for `python3`. So change `python3` alias to a version that is 3.9 or above
