### ISSUE TITLE
Hotstar videos are not downloading These days 

### ISSUE THREAD

**Issue by DikshaBB** [yt-dlp/yt-dlp#3321]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.03.08.1** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

Hotstar videos are not downloading These days.

### Verbose log

```shell
final_cmd = f"yt-dlp --continue --embed-subs --no-warnings -f bestvideo[ext=mp4]+bestaudio[ext=m4a]/best --hls-prefer-ffmpeg --prefer-ffmpeg -o {output_folder}/%(title)s.%(ext)s {url}"
```

**Comment by pukkandan** [comment]
* Check duplicate issues
* Provide verbose log
