### ISSUE TITLE
Broken site rtve.es

### ISSUE THREAD

**Issue by sidvicio** [yt-dlp/yt-dlp#3325]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.03.08.1** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Spain

### Description

Hi. Doesn't work with rtve.es videos like: https://www.rtve.es/play/videos/cachitos-de-hierro-y-cromo/bis/6437558/
Thank you very much.

### Verbose log

```shell
C:\youtube-dlp>yt-dlp.exe -vU https://www.rtve.es/play/videos/cachitos-de-hierro-y-cromo/bis/6437558/
[debug] Command-line config: ['-vU', 'https://www.rtve.es/play/videos/cachitos-de-hierro-y-cromo/bis/6437558/']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.03.08.1 [c0c2c57] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19042-SP0
[debug] exe versions: ffmpeg N-105642-g538be75a69-20220215 (setts), ffprobe N-105642-g538be75a69-20220215
[debug] Optional libraries: brotli, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.03.08.1, Current version: 2022.03.08.1
yt-dlp is up to date (2022.03.08.1)
[debug] [generic] Extracting URL: https://www.rtve.es/play/videos/cachitos-de-hierro-y-cromo/bis/6437558/
[generic] 6437558: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] 6437558: Downloading webpage
[generic] 6437558: Extracting information
[debug] Looking for video embeds
WARNING: [generic] 6437558: Failed to parse JSON Invalid control character at: line 13 column 275 (char 827)
ERROR: Unsupported URL: https://www.rtve.es/play/videos/cachitos-de-hierro-y-cromo/bis/6437558/
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1389, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1459, in __extract_info
  File "yt_dlp\extractor\common.py", line 617, in extract
  File "yt_dlp\extractor\generic.py", line 3985, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.rtve.es/play/videos/cachitos-de-hierro-y-cromo/bis/6437558/
```

**Comment by dirkf** [comment]
See #1346.

Also https://github.com/ytdl-org/youtube-dl/pull/29816.

**Comment by graphic-parse** [comment]
It's not working again.

**Comment by mildsunrise** [comment]
I can confirm the video posted (https://www.rtve.es/play/videos/cachitos-de-hierro-y-cromo/bis/6437558/) works with https://github.com/ytdl-org/youtube-dl/pull/31241 applied (from a spanish IP).

**Comment by dincel** [comment]
I don't know how you apply this to your script codes but I found a manual way of extract rtve.es/play content on Celluloid player;
example content: https://www.rtve.es/play/videos/carlos-rey-emperador/carlos-rey-emperador-capitulo-1/3312421/ 
1) While playing the media, goto devtools (F12) > Network tab and search for ".m3u8"
there will be two results:
https://rtvehlsvodlote7.rtve.es/mediavodv2/resources/TE_SCARLOS/mp4/5/9/1641318615695.mp4/video.m3u8?hls_no_audio_only=true&idasset=3312421
https://rtvehlsvodlote7.rtve.es/mediavodv2/resources/TE_SCARLOS/mp4/5/9/1641318615695.mp4/1641318615695-audio=192975-video=2759000.m3u8?idasset=3312421
2) take either one and remove the part after .mp4
3) change the URL's "https://rtvehlsvodlote7.rtve.es/mediavodv2/" part to "https://mediavod-lvlt.rtve.es/" resulting the final working URL: https://mediavod-lvlt.rtve.es/resources/TE_SCARLOS/mp4/5/9/1641318615695.mp4
4) Now the subtitles. As in step (1) this time search for ".vtt" and directly copy the link "https://www.rtve.es/resources/vtt/0/3/1648225256930.vtt" (you don't have to download it)
add both links to your .m3u playlist (e.g. play.m3u)
5) When you open Celluloid player it only plays .mp4 file. And you can copy the .vtt link address from the next and open it wiht Ctrl + L shortcut. This will activate subtitles too.
This may seem a bit player specific in the and but at least I found a way to retrieve both video and subs.
But manually it takes too long. I don't want to download the content, I just want to watch them without using the browser. I would be very grateful if you find a way to apply above steps to a yt-dlp update and allow us to watch shows directly from the visible URLs like https://www.rtve.es/play/videos/blah-blah/blah-blah-capitulo-1/1234567/
thank you.

**Comment by spinbilly** [comment]
I tried today, and it doesn't download videos from the www.rtve.es website
