### ISSUE TITLE
[feature request] YouTube - hide short videos (search results, feed, suggestions)

### ISSUE THREAD

**Issue by eladkarako** [yt-dlp/yt-dlp#3327]
<details><summary>checklist</summary>

### Checklist

- [X] I'm reporting a site feature request
- [X] I've verified that I'm running yt-dlp version **2022.03.08.1** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

UK

### Example URLs

https://www.youtube.com/shorts/mNj-f7CW5AM

### Verbose log

```shell
no need.
```

</details>

Ability to hide results of less than 2 minutes (or a specific time),  
from various sections, based on video length.

(YouTube's `#shorts` thing, created an upward-spike in that garbage content,  
as of April 5th 2022 `/shorts/` links started redirecting back to `/watch?v=`,  
but a lot of content creators still put out two versions of the same video (one < 1min. and a full one),  
or simply ton of <1min. garbage content to get the views).

(on my desktop I've applied <a href="https://gist.github.com/eladkarako/2549ac9cdfd7eae43a957404ec5e339b">a uBlock Origin rule</a> with `:upward` for DOM-traversing,  
but yt-dlp should have it much easier since you already have most of the video details already).

**Comment by coletdjnz** [comment]
https://github.com/yt-dlp/yt-dlp/issues/3165#issuecomment-1079843184

you can alternatively skip videos based on duration using `--match-filter "duration>120"`

note that either requires building from master atm to work properly with shorts.
