### ISSUE TITLE
Extract original music of tiktok video

### ISSUE THREAD

**Issue by kietheros** [yt-dlp/yt-dlp#3328]
### Checklist

- [X] I'm reporting a feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.03.08.1** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

A video on Tiktok refers to an original music. This audio file can be considered an additional format of this tiktok video. yt-dlp should extract this format.

Example:
- Video: https://www.tiktok.com/@nicktalksmoney/video/7081275873499860267?is_copy_url=1&is_from_webapp=v1
- Reference to this audio: https://www.tiktok.com/music/Jit-trippin-7061678640970484527 (direct link of file can easily extract from html)

Thank you!

**Comment by kietheros** [comment]
I found field music_info in tiktok extractor. All info are available.

**Comment by MinePlayersPE** [comment]
> This audio file can be considered an additional format of this tiktok video.
Disagree, because the audio can be cut, filtered, voiceover'd, and even go unused on the video so this might cause confusion
Agree in how the attached music ID should have a field in the infojson tho, since multiple platforms (YT Shorts, IG Reels, TT) started supporting it + it's useful for archival/context reasons
