### ISSUE TITLE
add '--client-certificate some.pem' to authenticate a site user to the remote machine

### ISSUE THREAD

**Issue by A-nglea** [yt-dlp/yt-dlp#3333]
### Checklist

- [X] I'm reporting a feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.03.08.1** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

Some sites offer the feature of higher format downloads to selected users with a certificate.pem

**Comment by pukkandan** [comment]
Related https://github.com/ytdl-org/youtube-dl/pull/29590

**Comment by coletdjnz** [comment]
> Related [ytdl-org/youtube-dl#29590](https://github.com/ytdl-org/youtube-dl/pull/29590)

I'm thinking we implement this within the SSLContext

https://docs.python.org/3/library/ssl.html?highlight=ssl#ssl.SSLContext.load_cert_chain

Think we might also need options for:
- providing password to decrypt private key (if required)
- private key file (if it is not included in the certfile. though upstream PR makes the requirement they must be combined, not sure if we should do this same).
