### ISSUE TITLE
[instagram]: Unable to download all videos from an account

### ISSUE THREAD

**Issue by dragonite44** [yt-dlp/yt-dlp#3335]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.03.08.1** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Australia

### Description

Trying to download all videos from an Instagram page (e.g. https://www.instagram.com/richiehawtin/) results in the error below. Individual videos (e.g. https://www.instagram.com/p/Cb5OocLAC45/) can be downloaded without issue. Both example links can be accessed in a browser without issue.

### Verbose log

```shell
[debug] Command-line config: ['https://www.instagram.com/richiehawtin/', '--cook
ies', 'C:\\Users\\Kyle\\Downloads\\cookies.txt', '-vU']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8 (No ANSI), err utf-8 (No A
NSI), pref cp1252
[debug] yt-dlp version 2022.03.08.1 [c0c2c57] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg 2021-01-27-git-149bfc2445-full_build-www.gyan.dev,
ffprobe 2021-01-27-git-149bfc2445-full_build-www.gyan.dev
[debug] Optional libraries: brotli, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.03.08.1, Current version: 2022.03.08.1
yt-dlp is up to date (2022.03.08.1)
[debug] [instagram:user] Extracting URL: https://www.instagram.com/richiehawtin/

[instagram:user] richiehawtin: Downloading webpage
[download] Downloading playlist: richiehawtin
ERROR: 'User-Agent'
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1389, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1698, in <lambda>
  File "yt_dlp\utils.py", line 2793, in __getitem__
  File "yt_dlp\extractor\instagram.py", line 505, in _extract_graphql
KeyError: 'User-Agent'

[instagram:user] playlist richiehawtin: Downloading 0 videos
[download] Finished downloading playlist: richiehawtin
```

**Comment by MinePlayersPE** [comment]
Should already be fixed in https://github.com/yt-dlp/yt-dlp/commit/76aa99137475698941a86edd010d67ff4caa88a2
