### ISSUE TITLE
yt-dlp stucked when a try to download a whole channel

### ISSUE THREAD

**Issue by frashersam** [yt-dlp/yt-dlp#3338]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.03.08.1** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

Hello, I have a issue with yt-dlp, when I try to download a whole yt-channel, yt-dlp get stucked in #24 video - #30 video of 134 videos (then not download more videos even if a leave 3 hours, nothing change ) , I currently using ubuntu 20.10

version of yt-dlp 2022-03-08.1

comand line:
yt-dlp -vU  -f "bv*[ext=mp4]+ba[ext=m4a]/b[ext=mp4]/bv*+ba/b" https://www.youtube.com/channel/UCDho7W6FJyhkT_MrH_ac6-Q/videos?view=0&sort=da&flow=grid

### Verbose log

```shell
yt-dlp -vU  -f "bv*[ext=mp4]+ba[ext=m4a]/b[ext=mp4]/bv*+ba/b" https://www.youtube.com/channel/UCDho7W6FJyhkT_MrH_ac6-Q/videos?view=0&sort=da&flow=grid


[youtube] m2GbIeYyJtI: Downloading MPD manifest
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[info] m2GbIeYyJtI: Downloading 1 format(s): 22
[debug] Invoking downloader on "https://rr2---sn-ab5l6n6e.googlevideo.com/videoplayback?expire=1649370547&ei=UxFPYtb7L4WxhgbS6bzICA&ip=143.198.28.136&id=o-AGJDdvuzmyZSXyHCZWoQ1mO_jnH0wwVmaR7an8V5CYVa&itag=22&source=youtube&requiressl=yes&mh=Lm&mm=31%2C29&mn=sn-ab5l6n6e%2Csn-ab5sznze&ms=au%2Crdu&mv=m&mvi=2&pl=22&initcwndbps=178750&vprv=1&mime=video%2Fmp4&cnr=14&ratebypass=yes&dur=5965.415&lmt=1647619324762892&mt=1649348464&fvip=4&fexp=24001373%2C24007246&c=ANDROID&txp=6211224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Ccnr%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRQIgBASjKIr4vZkDAPsLZcKntCE8ongMn1b0SnjNOnccB7ACIQCeeFUxdOzwWxtfOcmSCyDvTezw88XujTEU9xrC8nwNew%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhALW5NK4x6ckOBFRL_VNapfzoLTVoDngx38ZsQhMk2hgAAiEAiilkrg7vJH5d1nD0qjT5naO9vEuM4gvqJ8w6vPAeTTk%3D"
[download] GEOGRAFIA PAMER SEMINARIO 1 [m2GbIeYyJtI].mp4 has already been downloaded
[download] 100% of 201.39MiB
[download] Downloading video 24 of 134
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=1pE-jXzAdQc
[youtube] 1pE-jXzAdQc: Downloading webpage
[youtube] 1pE-jXzAdQc: Downloading android player API JSON
[youtube] 1pE-jXzAdQc: Downloading MPD manifest
[youtube] 1pE-jXzAdQc: Downloading MPD manifest
```

**Comment by pukkandan** [comment]
Where's the rest of the log?

**Comment by pukkandan** [comment]
When it's stuck, press Ctrl+C and then copy paste the **whole** log

**Comment by frashersam** [comment]
hello, I just notice than having 1 gb of ram on my vps is not enough for use yt-dlp, because yt-dlp use about 1 gb, so when I download with my personal computer (8gb Ram, not problem to download)......

the program just crashed when I was downloading with 1 Gb of ram, and the comand line where showing  "[youtube] 1pE-jXzAdQc: Downloading MPD manifest"....I was thinking that were a bug of yt-dlp. but not.

thank you anyway for you help.
have a good day

**Comment by pukkandan** [comment]
It is true that yt-dlp uses excessive memory when downloading large playlists https://github.com/yt-dlp/yt-dlp/issues/1399. But it should not take anywhere near 1G to download this playlist of just 134 items
