### ISSUE TITLE
[Feature Request] [Windows] Add longpath support

### ISSUE THREAD

**Issue by MrDemous** [yt-dlp/yt-dlp#334]
- [ x] I'm reporting a feature request
- [ x] I've verified that I'm running yt-dlp version **2021.05.20**
- [ x] I've searched the bugtracker for similar feature requests including closed ones

## Description

Is it possible to add support for Windows long path? Currently, any filenames that are more than 260 characters long fail to download due to Windows legacy character limit.

It has been requested on Youtube-DL's repo but never implemented [Here](https://github.com/ytdl-org/youtube-dl/issues/23192)

And these projects implemented it successfully in case more info is needed about the subject.

https://github.com/staxrip/staxrip/issues/338
https://github.com/staxrip/staxrip/wiki/Windows-10-long-path-support

**Comment by nao20010128nao** [comment]
As far as I know, PyInstaller adds `longPathAware` in generated executables. So, if we build EXE binaries with latest version of PyInstaller, we can assume that we're already done.

ref. https://github.com/pyinstaller/pyinstaller/pull/5424

**Comment by pukkandan** [comment]
I dont remember why this was never closed. yt-dlp.exe already had longpath support enabled. Now our [custom ffmpeg builds](https://github.com/yt-dlp/FFmpeg-Builds) has the same
