### ISSUE TITLE
CBS Site broken

### ISSUE THREAD

**Issue by kucksdorfs** [yt-dlp/yt-dlp#3344]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.03.08.1** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United States

### Description

It looks like CBS changed their URL scheme. The following URL does not work, but the second one works

- Not Working: https://www.cbs.com/shows/video/hCgKXKncHU0KVm_EhnWkMKAt1TNgQdMu/

- Working: https://www.cbs.com/shows/the-late-show-with-stephen-colbert/video/hCgKXKncHU0KVm_EhnWkMKAt1TNgQdMu/

The Working URL works with yt-dlp, but not in browser (404 error). The only difference is between shows/ and /videos is the name of the show.

yt-dlp is at version 2022.03.08.2 (checklist above says .1)

### Verbose log

```shell
debug] Command-line config: ['-F', 'https://www.cbs.com/shows/video/hCgKXKncHU0KVm_EhnWkMKAt1TNgQdMu/', '--verbose']
[debug] User config "/home/stephen/.config/yt-dlp/config": ['--all-sub', '-f', '[ext=mp4][height<=720]/[ext=mp4][height<=1080]/[ext=mp4][height<=720]+bestaudio/[ext=mp4][height<=1080]+bestaudio/best']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.03.08.2 [e491d06d3]
[debug] Python version 3.8.10 (CPython 64bit) - Linux-5.4.0-107-generic-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4, rtmpdump 2.4
[debug] Optional libraries: brotli, Cryptodome, secretstorage, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [generic] Extracting URL: https://www.cbs.com/shows/video/hCgKXKncHU0KVm_EhnWkMKAt1TNgQdMu/
[generic] hCgKXKncHU0KVm_EhnWkMKAt1TNgQdMu: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] hCgKXKncHU0KVm_EhnWkMKAt1TNgQdMu: Downloading webpage
[generic] hCgKXKncHU0KVm_EhnWkMKAt1TNgQdMu: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://www.cbs.com/shows/video/hCgKXKncHU0KVm_EhnWkMKAt1TNgQdMu/
Traceback (most recent call last):
  File "/home/stephen/.local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 1389, in wrapper
    return func(self, *args, **kwargs)
  File "/home/stephen/.local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 1459, in __extract_info
    ie_result = ie.extract(url)
  File "/home/stephen/.local/lib/python3.8/site-packages/yt_dlp/extractor/common.py", line 617, in extract
    ie_result = self._real_extract(url)
  File "/home/stephen/.local/lib/python3.8/site-packages/yt_dlp/extractor/generic.py", line 3998, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.cbs.com/shows/video/hCgKXKncHU0KVm_EhnWkMKAt1TNgQdMu/
```

**Comment by dirkf** [comment]
See #3096.
