### ISSUE TITLE
Unable to download from france.tv

### ISSUE THREAD

**Issue by caspyartist** [yt-dlp/yt-dlp#3357]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.04.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

France

### Description

greetings all

this is my first time typing these things, so sorry if i'm reporting in the wrong section. anyway, so earlier today I wanted to download an episode from a cartoon, but when I went to actually download it, I got all these errors. I haven't been on [france.tv](https://france.tv/) since mid last year, so I'm not too sure when this problem happened. I can also view the video just fine with Surfshark VPN on the site's player.

cheers!

### Verbose log

```shell
[debug] Command-line config: ['-vU', '-f', 'bv+ba/b', '--all-subs', 'https://www.france.tv/france-5/ernest-et-celestine/saison-2/2979979-le-club-souris.html']
[debug] User config "/Users/[user]/.config/yt-dlp/config": ['-o', '~/Documents/yt-dlp/%(title)s.%(ext)s']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.04.08 [7884ade65]
[debug] Python version 3.10.1 (CPython 64bit) - macOS-12.2.1-arm64-arm-64bit
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.4.1 (setts), ffprobe 4.4.1, rtmpdump 2.4
[debug] Optional libraries: brotli, certifi, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.04.08, Current version: 2022.04.08
yt-dlp is up to date (2022.04.08)
[debug] [FranceTVSite] Extracting URL: https://www.france.tv/france-5/ernest-et-celestine/saison-2/2979979-le-club-souris.html
[FranceTVSite] 2979979-le-club-souris: Downloading webpage
[debug] [FranceTV] Extracting URL: francetv:be838975-eaae-4fcc-9bf0-4ed7c0c595fd
[FranceTV] be838975-eaae-4fcc-9bf0-4ed7c0c595fd: Downloading desktop video JSON
[FranceTV] be838975-eaae-4fcc-9bf0-4ed7c0c595fd: Downloading mobile video JSON
[FranceTV] be838975-eaae-4fcc-9bf0-4ed7c0c595fd: Downloading signed dash manifest URL
[FranceTV] be838975-eaae-4fcc-9bf0-4ed7c0c595fd: Downloading MPD manifest
WARNING: [FranceTV] Failed to download MPD manifest: HTTP Error 403: Forbidden
[FranceTV] be838975-eaae-4fcc-9bf0-4ed7c0c595fd: Downloading signed hls manifest URL
[FranceTV] be838975-eaae-4fcc-9bf0-4ed7c0c595fd: Downloading m3u8 information
WARNING: [FranceTV] Failed to download m3u8 information: HTTP Error 403: Forbidden
ERROR: [FranceTV] be838975-eaae-4fcc-9bf0-4ed7c0c595fd: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "/Users/[user]/.pyenv/versions/3.10.1/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1408, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/[user]/.pyenv/versions/3.10.1/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1492, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/Users/[user]/.pyenv/versions/3.10.1/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1548, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/Users/[user]/.pyenv/versions/3.10.1/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 2487, in process_video_result
    self.raise_no_formats(info_dict)
  File "/Users/[user]/.pyenv/versions/3.10.1/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 981, in raise_no_formats
    raise ExtractorError(msg, video_id=info['id'], ie=info['extractor'],
yt_dlp.utils.ExtractorError: [FranceTV] be838975-eaae-4fcc-9bf0-4ed7c0c595fd: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

**Comment by m4tu4g** [comment]
Can't reproduce the issue to fix, working fine, try now once and report again.

**Comment by caspyartist** [comment]
> 

I've tried multiple times today with different VPNs and still not allowing me to download episodes.

**Comment by m4tu4g** [comment]
I did with NordVPN incase if you want to give it a try.

**Comment by caspyartist** [comment]
> I did with NordVPN incase if you want to give it a try.

tried it just now with NordVPN and it worked! phew.
