### ISSUE TITLE
get artist metadata from Jamendo

### ISSUE THREAD

**Issue by zakiloki0** [yt-dlp/yt-dlp#3359]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

Hi guys, how can I save the "artist" name in the metadata when I download from Jamendo? i use this

yt-dlp --embed-metadata --embed-thumbnail -o "%(title)s.%(ext)s" *url*

All working fine, picture cover and other metadata, but artist name is not save, how can I fix it?

**Comment by hatienl0i261299** [comment]
@zakiloki0 Pls show the verbose log and url as well

**Comment by zakiloki0** [comment]
> @zakiloki0 Pls show the verbose log and url as well

yt-dlp --embed-metadata --embed-thumbnail -o "%(title)s.%(ext)s" --verbose https://www.jamendo.com/track/1901140/under-water
[debug] Command-line config: ['--embed-metadata', '--embed-thumbnail', '-o', '%(title)s.%(ext)s', '--verbose', 'https://www.jamendo.com/track/1901140/under-water']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.03.08.1 [c0c2c57d3]
[debug] Python version 3.10.4 (CPython 64bit) - Linux-5.17.1-arch1-1-x86_64-with-glibc2.35
[debug] exe versions: ffmpeg 5.0 (setts), ffprobe 5.0
[debug] Optional libraries: brotlicffi, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [Jamendo] Extracting URL: https://www.jamendo.com/track/1901140/under-water
[Jamendo] 1901140: Downloading JSON metadata
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 1901140: Downloading 1 format(s): flac
[info] Downloading video thumbnail size100 ...
[info] Writing video thumbnail size100 to: Under Water.com
[debug] Invoking downloader on "https://flac.jamendo.com/?trackid=1901140&format=flac&from=app-97dab294"
[download] Destination: Under Water.flac
[download] 100% of 24.84MiB in 00:03
[Metadata] Adding metadata to "Under Water.flac"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:Under Water.flac' -map 0 -dn -ignore_unknown -c copy -metadata 'title=Under Water' -metadata date=20211119 -metadata 'description=Simple but meaningful: &quot;You can'"'"'t run under water&quot;... It'"'"'s all about life and love with all the obstacles, but also about getting stronger.' -metadata 'synopsis=Simple but meaningful: &quot;You can'"'"'t run under water&quot;... It'"'"'s all about life and love with all the obstacles, but also about getting stronger.' -metadata purl=https://www.jamendo.com/track/1901140/under-water -metadata comment=https://www.jamendo.com/track/1901140/under-water -movflags +faststart 'file:Under Water.temp.flac'
[ThumbnailsConvertor] Converting thumbnail "Under Water.com" to png
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -f image2 -pattern_type none -i 'file:Under Water.com' -movflags +faststart 'file:Under Water.png'
[EmbedThumbnail] mutagen: Adding thumbnail to "Under Water.flac"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:Under Water.png'
Deleting original file Under Water.com (pass -k to keep)
Deleting original file Under Water.png (pass -k to keep)

**Comment by pukkandan** [comment]
The Jamedo extractor currently does not extract artist metadata

**Comment by zakiloki0** [comment]
> The Jamedo extractor currently does not extract artist metadata

There is no way to fix it then?
