### ISSUE TITLE
[Question] Chapter markings in MP4 (from Youtube)

### ISSUE THREAD

**Issue by shakeyourbunny** [yt-dlp/yt-dlp#336]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE

Is there a possibility to have chapter markings saved from youtube videos? When I'm watching videos on Youtube, I always am curious how to save the segmented markings (which are chapters?) offline directly into the mp4 file.

Technically, MP4 should be able to do this (with the help of fmpeg): https://medium.com/@dathanbennett/adding-chapters-to-an-mp4-file-using-ffmpeg-5e43df269687

Is this already implemented, and if so, how do I do it? 
Example video is https://www.youtube.com/watch?v=8ktY12GiO18

**Comment by pukkandan** [comment]
`--add-metadata`

**Comment by pukkandan** [comment]
Since you havent responded, I assume this worked?
