### ISSUE TITLE
Only storyboard formats listed for "free with ads" video

### ISSUE THREAD

**Issue by MrSmite** [yt-dlp/yt-dlp#3361]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

URL: [https://www.youtube.com/watch?v=USZl1aq_wl4](url)
yt-dlp: 2022.03.08.1

I have _**Youtube Video and Audio downloader**_ addon for firefox which offers a bunch of "video only" and "audio only" formats for the above URL. I chose the 4.3 GB 1080p "video only" stream and a M4A 256K "audio only" stream but it was downloading at 10 kb/s.. unacceptable.

The problem is when I tried my yt-dlp script which simply tries to get the bestvideo, I kept getting "that format is not available". So I manually typed the following into a command prompt:

yt-dlp.exe --list-formats --simulate https://youtu.be/USZl1aq_wl4

And the result was only "storyboard" formats:

[info] Available formats for USZl1aq_wl4:
ID  EXT   RESOLUTION | PROTO | VCODEC MORE INFO
------------------------------------------------
sb2 mhtml 48x27      | mhtml | images storyboard
sb1 mhtml 106x45     | mhtml | images storyboard
sb0 mhtml 212x90     | mhtml | images storyboard
ERROR: [youtube] USZl1aq_wl4: Requested format is not available

I tried one of the storyboard formats but all I got was 95 images, not the full movie. Is there something I'm missing? Why is the addon able to provide multiple MP4 formats from 1080p to 144p but yt-dlp can only find these storyboards?

**Comment by pukkandan** [comment]
The video has DRM. If you update yt-dlp to the latest version, it will show an appropriate error message/warning

**Comment by pukkandan** [comment]
> I have Youtube Video and Audio downloader addon for firefox which offers a bunch of "video only" and "audio only" formats for the above URL. I chose the 4.3 GB 1080p "video only" stream and a M4A 256K "audio only" stream but it was downloading at 10 kb/s.. unacceptable.

You can try, but I bet the resulting file will not be playable

**Comment by MrSmite** [comment]
> You can try downloading it, but I bet the resulting files will not be playable

You're right, I downloaded the 144p and only the first few seconds of the logo plays then it becomes unwatchable.
