### ISSUE TITLE
Exclude a video and its metadata from downloading and processing if the video file is already on disk

### ISSUE THREAD

**Issue by mike2003** [yt-dlp/yt-dlp#3365]
### Question

I download videos from my playlist, which I replenish. But I don't want to download old videos on disk. My command:

**--no-overwrites --no-force-overwrites --no-post-overwrites --no-mtime --no-cache-dir --ffmpeg-location *** --embed-thumbnail --embed-metadata --embed-chapters --write-description --write-thumbnail --convert-thumbnails jpg**

The problem is that each time the metadata is downloaded and embedded in the video again. Although the video itself is not downloaded from YouTube.

How can I completely exclude a video and its metadata from downloading and processing if the video file is already on disk?

**Comment by pukkandan** [comment]
`--download-archive`

**Comment by mike2003** [comment]
It might help, but no. I need this to happen with files. If I delete the file it won't help me download it again.

**Comment by csadam** [comment]
I think it's the same issue #1467

**Comment by pukkandan** [comment]
#1467 specifically asks this for **embedded** metadata, while this is asking to skip the various **metadata files** (in addition to skipping embedding) depending on whether the **video file** is present or not. This is not possible to implement. If you only want to avoid overwriting the files, `--no-overwrites` can be used

**Comment by csadam** [comment]
Maybe I misunderstand, please tell what do you think about this example:

1. the video is downloaded on the first run
```
 yt-dlp --ignore-config --no-overwrites --no-force-overwrites --no-post-overwrites https://www.youtube.com/watch?v=noMeoI87G80
[youtube] noMeoI87G80: Downloading webpage
[youtube] noMeoI87G80: Downloading android player API JSON
[youtube] noMeoI87G80: Downloading MPD manifest
[youtube] noMeoI87G80: Downloading MPD manifest
[info] noMeoI87G80: Downloading 1 format(s): 243+251
[dashsegments] Total fragments: 6
[download] Destination: How They Rob Men in Chicago (1900) - Wallace McCutcheon [noMeoI87G80].f243.webm
[download] 100% of 779.24KiB in 00:06
[download] Destination: How They Rob Men in Chicago (1900) - Wallace McCutcheon [noMeoI87G80].f251.webm
[download] 100% of 11.38KiB in 00:00
[Merger] Merging formats into "How They Rob Men in Chicago (1900) - Wallace McCutcheon [noMeoI87G80].webm"
Deleting original file How They Rob Men in Chicago (1900) - Wallace McCutcheon [noMeoI87G80].f243.webm (pass -k to keep)
Deleting original file How They Rob Men in Chicago (1900) - Wallace McCutcheon [noMeoI87G80].f251.webm (pass -k to keep)
```
2. I run same command, the video is not downloaded again, this is OK
```
yt-dlp --ignore-config --no-overwrites --no-force-overwrites --no-post-overwrites https://www.youtube.com/watch?v=noMeoI87G80
[youtube] noMeoI87G80: Downloading webpage
[youtube] noMeoI87G80: Downloading android player API JSON
[youtube] noMeoI87G80: Downloading MPD manifest
[youtube] noMeoI87G80: Downloading MPD manifest
[info] noMeoI87G80: Downloading 1 format(s): 243+251
[download] How They Rob Men in Chicago (1900) - Wallace McCutcheon [noMeoI87G80].webm has already been downloaded
```
3. I add `--embed-metadata` to the command. While it doesn't download the file again, but it overwrites the file, because it embeds the metadata.
```
yt-dlp --ignore-config --no-overwrites --no-force-overwrites --no-post-overwrites --embed-metadata https://www.youtube.com/watch?v=noMeoI87G80
[youtube] noMeoI87G80: Downloading webpage
[youtube] noMeoI87G80: Downloading android player API JSON
[youtube] noMeoI87G80: Downloading MPD manifest
[youtube] noMeoI87G80: Downloading MPD manifest
[info] noMeoI87G80: Downloading 1 format(s): 243+251
[download] How They Rob Men in Chicago (1900) - Wallace McCutcheon [noMeoI87G80].webm has already been downloaded
[Metadata] Adding metadata to "How They Rob Men in Chicago (1900) - Wallace McCutcheon [noMeoI87G80].webm"
```
4. If I run the same command, then the file is changed again, because it embeds the metadata again despite of the three no-overwrite parameters.

There is already a case where it detects and logs that the file is already downloaded. Isn't the solution just to stop processing the file at that point and skip the additional metadata processing?

**Comment by pukkandan** [comment]
@csadam What you are asking is #1467. But from what I understand, that is not what the OP of this issue wants

**Comment by mike2003** [comment]
"the file is changed again, because it embeds the metadata again despite of the three no-overwrite parameters."
This is exactly what I don't want to do.

**Comment by pukkandan** [comment]
alright, then seems I misunderstood. You can track #1467
