### ISSUE TITLE
Please add support for www.chorki.com

### ISSUE THREAD

**Issue by noob-af-bd** [yt-dlp/yt-dlp#3369]
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.04.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Anywhere

### Example URLs

https://www.chorki.com/videos/shortfilm/fagun-theke-fagune
https://www.chorki.com/videos/movie/chorabali
https://www.chorki.com/bn/series/aaj-robibar

### Description

ERROR: Unsupported URL

### Verbose log

```shell
[generic] Falling back on generic information extractor.
ERROR: Unsupported URL: https://www.chorki.com/videos/movie/chorabali
```

**Comment by coletdjnz** [comment]
For devs: This uses viewlift, so I think updating the ViewLift extractor _VALID_URL,  _SITE_MAP and  _DOMAINS_REGEX to add support may work.

(also could be worth looking into seeing if ViewLiftIE can be converted into an exclusive webpage embed extractor in the future instead of having to whitelist sites)
