### ISSUE TITLE
subtitle support for tubitv

### ISSUE THREAD

**Issue by rezad1393** [yt-dlp/yt-dlp#3374]
### Checklist

- [X] I'm reporting a site feature request
- [X] I've verified that I'm running yt-dlp version **2022.04.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Iraq

### Example URLs

https://tubitv.com/movies/508841/battle-for-sevastopol

### Description

many movies on this website have subtitle in a simple english format.
can subtitle download be added for those?

### Verbose log

```shell
yt-dlp -vU https://tubitv.com/movies/508841/battle-for-sevastopol
[debug] Command-line config: ['-vU', 'https://tubitv.com/movies/508841/battle-for-sevastopol']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.04.08 [7884ade65]
[debug] Python version 3.10.4 (CPython 64bit) - Linux-5.17.1-arch1-1-x86_64-with-glibc2.35
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 5.0 (setts), ffprobe 5.0, rtmpdump 2.4
[debug] Optional libraries: certifi, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.04.08, Current version: 2022.04.08
yt-dlp is up to date (2022.04.08)
[debug] Using fake IP 6.204.80.241 (US) as X-Forwarded-For
[debug] [TubiTv] Extracting URL: https://tubitv.com/movies/508841/battle-for-sevastopol
[TubiTv] 508841: Downloading JSON metadata
[TubiTv] 508841: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 508841: Downloading 1 format(s): 2661
[debug] Invoking downloader on "https://manifest.production-public.tubi.io/707d1c66-ea7b-4601-bcdf-7658c2acd33b/2y97ls06/stream.m3u8?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjZG5fcHJlZml4IjoiaHR0cHM6Ly9jbG91ZGZyb250LnR1YmkudmlkZW8iLCJjb3VudHJ5IjoiVU5LTk9XTl9DT1VOVFJZIiwiZGV2aWNlX2lkIjoiNjRjNDAyNzgtOTZlMi00MzE5LWFhNzctYjkyYjI2ZDE2OGY1IiwiZXhwIjoxNjQ5Nzk5MDAwLCJwbGF0Zm9ybSI6IldFQiIsInVzZXJfaWQiOjB9.j_Bs97qup7q3gSAwDy0ncXHSgrtbst6c3kYRBf3dZo4&manifest=true"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 2202
[download] Destination: Battle for Sevastopol [508841].mp4
[download]   0.1% of ~1.62GiB at 835.59KiB/s ETA 45:40 (frag 3/2202)^C
ERROR: Interrupted by user
```

**Comment by pukkandan** [comment]
Show full output of `yt-dlp -vU --list-subs https://tubitv.com/movies/508841/battle-for-sevastopol`

**Comment by rezad1393** [comment]
yt-dlp -vU --list-subs https://tubitv.com/movies/508841/battle-for-sevastopol 
[debug] Command-line config: ['-vU', '--list-subs', 'https://tubitv.com/movies/508841/battle-for-sevastopol']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.04.08 [7884ade65]
[debug] Python version 3.10.4 (CPython 64bit) - Linux-5.17.1-arch1-1-x86_64-with-glibc2.35
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 5.0 (setts), ffprobe 5.0, rtmpdump 2.4
[debug] Optional libraries: certifi, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.04.08, Current version: 2022.04.08
yt-dlp is up to date (2022.04.08)
[debug] Using fake IP 6.247.235.154 (US) as X-Forwarded-For
[debug] [TubiTv] Extracting URL: https://tubitv.com/movies/508841/battle-for-sevastopol
[TubiTv] 508841: Downloading JSON metadata
[TubiTv] 508841: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[info] Available subtitles for 508841:
Language Formats
English  srt

**Comment by pukkandan** [comment]
You have to use `--write-subtitles`. Go through the readme
