### ISSUE TITLE
authored vs. compiled playlists ...

### ISSUE THREAD

**Issue by Albretch** [yt-dlp/yt-dlp#3378]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

some people authored their own videos, some other just compile them; both ways have their merits (or not).
Which kinds of heuristics could be used to tell apart both cases?
lbrtchx

**Comment by pukkandan** [comment]
https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-your-question-about-yt-dlp
