### ISSUE TITLE
Latest version completely fails to run, it looks like.

### ISSUE THREAD

**Issue by mzso** [yt-dlp/yt-dlp#3381]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.04.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

So I upgraded just now. And the same command line that was running a minute ago now fails to download anything.
Some file not found error. Not sure what it misses, it seems like some python files, which is strange, because it's a static executable.

### Verbose log

```shell
>"D:\Programok\videó\CLI\youtube-dl.exe" --no-playlist -o D:\Letöltés\%(title)s.%(ext)s https://www.youtube.com/watch?v=vp7d1DV0sFI
[debug] Command-line config: ['--no-playlist', '-o', 'D:\\Letöltés\\%(title)s.%(ext)s', 'https://www.youtube.com/watch?v=vp7d1DV0sFI']
[debug] Portable config "D:\Programok\videó\CLI\yt-dlp.conf": ['-f', '(bestvideo[vcodec^=av01]/bestvideo[vcodec=vp9]/bestvideo[vcodec^=avc]/bestvideo[vcodec!=vp8])[height<=2160]+(258/256/bestaudio[acodec=opus]/bestaudio[acodec=vorbis]/bestaudio[acodec^=m4a]/bestaudio)/(best[vcodec^=av01]/best[vcodec=vp9]/best[vcodec^=avc]/best[vcodec!=vp8])[height<=1440]/best', '--verbose', '--video-password', 'PRIVATE', '--ignore-errors', '--write-description', '--write-sub', '--write-thumbnail', '--sub-lang', 'en,en-GB,en-US,en-CA,en-AU,en-NZ,hu', '--no-playlist', '--embed-metadata', '--embed-chapters', '--no-mtime', '-o', '.\\%(title)s.%(ext)s']
Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "yt_dlp\__init__.pyc", line 869, in main
  File "yt_dlp\__init__.pyc", line 830, in _real_main
  File "yt_dlp\YoutubeDL.pyc", line 667, in __init__
  File "yt_dlp\YoutubeDL.pyc", line 3743, in _setup_opener
  File "yt_dlp\utils.pyc", line 1027, in make_HTTPS_handler
FileNotFoundError: [Errno 2] No such file or directory
```

**Comment by mzso** [comment]
It seems like with yt-dlp 2022.03.08.1 it still works. The download from Youtube is excruciatingly slow though.

**Comment by Lesmiscore** [comment]
Are you using _min.exe variant of yt-dlp? Then duplicatr of https://github.com/yt-dlp/yt-dlp/issues/3353

**Comment by gamer191** [comment]
By the way, if you aren't sure, run yt-dlp 2022.03.08.1 with --verbose and then send us the logs

**Comment by mzso** [comment]
[**@Lesmiscore**](https://github.com/Lesmiscore) commented on [2022. ápr. 10. 12:45 CEST](https://github.com/yt-dlp/yt-dlp/issues/3381#issuecomment-1094242564 "2022-04-10T10:45:24Z - Replied by Github Reply Comments"):
> Are you using \_min.exe variant of yt-dlp? Then see [#3353](https://github.com/yt-dlp/yt-dlp/issues/3353)

No I think I was using the full exe. How is the "min" different?
In any way I was upgrading with -U like I did before, so it should be the same version as before. And it only broke now.

**Comment by gamer191** [comment]
@mzso
I have 3 questions for you:
1. How did you downgrade to yt-dlp 2022.03.08.1
2. if you still have the exe that gave the above error, can you please run it with `--compat-options no-certifi --verbose`
3. if you update back to the latest version, does it still break? If yes, can you please run it with `--verbose` and send the logs, and then run it again with `--compat-options no-certifi --verbose` and send the logs?

> No I think I was using the full exe. How is the "min" different?

yt-dlp_min.exe is the py2exe build. It is faster, but has known issues, which is why it isn't recommended

**Comment by dajare** [comment]
> It seems like with yt-dlp 2022.03.08.1 it still works. The download from Youtube is excruciatingly slow though.

This is a "+1" on "excruciatingly slow" from Youtube. It _was_ excruciatingly slow, so I upgraded to 2022.04.08, and nothing changed. It's still excruciatingly slow.

Platform: MacOS 10.14.6 Mojave

**Comment by mzso** [comment]
[**@gamer191**](https://github.com/gamer191) commented on [2022. ápr. 10. 16:22 CEST](https://github.com/yt-dlp/yt-dlp/issues/3381#issuecomment-1094285679 "2022-04-10T14:22:50Z - Replied by Github Reply Comments"):
> [@mzso](https://github.com/mzso)  
> I have 3 questions for you:
> 
> 1.  How did you downgrade to yt-dlp 2022.03.08.1
> 2.  if you still have the exe that gave the above error, can you please run it with `--compat-options no-certifi --verbose`
> 3.  if you update back to the latest version, does it still break? If yes, can you please run it with `--verbose` and send the logs, and then run it again with `--compat-options no-certifi --verbose` and send the logs?
> 
> > No I think I was using the full exe. How is the "min" different?
> 
> yt-dlp\_min.exe is the py2exe build. It is faster, but has known issues, which is why it isn't recommended
> 
> PS: I will most likely not respond to your reply to this message, until Friday

Hmm. It might have been the min after all, which got broken for some reason. (I have updated via -U before mutliple times)
Anyway. I downloaded the normal exe and now it seems to work.

(The slow download may have been because of a long SD video.  )
