### ISSUE TITLE
Special characters like Slashes are not dealt with properly

### ISSUE THREAD

**Issue by KrischnaGabriel** [yt-dlp/yt-dlp#3385]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.04.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

**YTID:** UnIhRpIT7nc
**Full Title:**
inabakumori - Lagtrain (Vo. Kaai Yuki) / 稲葉曇『ラグトレイン』Vo. 歌愛ユキ
**yt-dlp output title:**
稲葉曇『ラグトレイン』Vo. 歌愛ユキ [UnIhRpIT7nc]
**Command:**
yt-dlp -x https://www.youtube.com/watch?v=UnIhRpIT7nc
**Issue:**
The title is truncated to the part after the slash.

**YTID:** MhyTR_M8QnA
**Full Title:**
Nightcore - Lonely Ones // LOVA (Lyrics)
**yt-dlp output title:**
Nightcore - Lonely Ones _ LOVA (Lyrics) [MhyTR_M8QnA]
**Command:**
yt-dlp -x https://www.youtube.com/watch?v=MhyTR_M8QnA
**Issue:**
The slashes are substituted with underscores.

**YTID:** _bHXZvm2hUY
**Full Title:**
10 | Wait, he has a point
**yt-dlp output title:**
10 _ Wait, he has a point [_bHXZvm2hUY]
**Command:**
yt-dlp -x https://www.youtube.com/watch?v=_bHXZvm2hUY
**Issue:**
"|" is substituted with an underscore.

**YTID:** Z53VDLjBZhY
**Full Title:**
96 | Cat? I'm a kitty cat.
**yt-dlp output title:**
96 _ Cat I'm a kitty cat. [Z53VDLjBZhY]
**Command:**
yt-dlp -x https://www.youtube.com/watch?v=Z53VDLjBZhY
**Issue:**
"|" is substituted with an underscore and the questionmark is non-existent. * whispers *: (on ext4 filesystems you can have a questionmark in a filename)

**Note:** i know the id can be removed with ´-o "%(title)s.%(ext)s"´. The yt-video-id is not in question.

### Verbose log

```shell
$ yt-dlp -x -vU https://www.youtube.com/watch?v=UnIhRpIT7nc
[debug] Command-line config: ['-x', '-vU', 'https://www.youtube.com/watch?v=UnIhRpIT7nc']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.04.08 [7884ade65] (zip)
[debug] Python version 3.8.10 (CPython 64bit) - Linux-5.4.0-107-generic-x86_64-with-glibc2.29
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4
[debug] Optional libraries: brotli, certifi, Crypto, secretstorage, sqlite
[debug] Proxy map: {}
Latest version: 2022.04.08, Current version: 2022.04.08
yt-dlp is up to date (2022.04.08)
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=UnIhRpIT7nc
[youtube] UnIhRpIT7nc: Downloading webpage
[youtube] UnIhRpIT7nc: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[info] UnIhRpIT7nc: Downloading 1 format(s): 251
[debug] Invoking downloader on "https://rr4---sn-8xgn5uxa-4g5s.googlevideo.com/videoplayback?expire=1649631462&ei=hgxTYqHfIIbVgAedzLH4BQ&ip=94.134.114.152&id=o-AIzPOZnFyM1auRd6hQjOVWzlVYzAeeCAiPFS0lMYHw5C&itag=251&source=youtube&requiressl=yes&mh=8b&mm=31%2C29&mn=sn-8xgn5uxa-4g5s%2Csn-4g5ednds&ms=au%2Crdu&mv=m&mvi=4&pl=24&initcwndbps=1471250&vprv=1&mime=audio%2Fwebm&gir=yes&clen=3957278&dur=251.881&lmt=1615029428068029&mt=1649609085&fvip=4&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=5531432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRgIhAPRRQ818o8gfhe27t8ZFLnolE-p53CTm2qcXdOk3_-gBAiEAwXX85NhT_eHrzddGfMfwFgxqxSRvhgwzpvBvX3BFtd4%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgfYy92rYLFF17tGu0Q9vtMBOIv4GDM70KEolgy3YcIvICIFSkDWMeJjtB7MZCmC6EV5egXtA2af5rWmK3Uq9A_7vm"
[download] Destination: 稲葉曇『ラグトレイン』Vo. 歌愛ユキ [UnIhRpIT7nc].webm
[download] 100% of 3.77MiB in 00:00
[debug] ffmpeg command line: ffprobe -show_streams 'file:稲葉曇『ラグトレイン』Vo. 歌愛ユキ [UnIhRpIT7nc].webm'
[ExtractAudio] Destination: 稲葉曇『ラグトレイン』Vo. 歌愛ユキ [UnIhRpIT7nc].opus
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:稲葉曇『ラグトレイン』Vo. 歌愛ユキ [UnIhRpIT7nc].webm' -vn -acodec copy -movflags +faststart 'file:稲葉曇『ラグトレイン』Vo. 歌愛ユキ [UnIhRpIT7nc].opus'
Deleting original file 稲葉曇『ラグトレイン』Vo. 歌愛ユキ [UnIhRpIT7nc].webm (pass -k to keep)
```

**Comment by pukkandan** [comment]
> YTID: UnIhRpIT7nc
Full Title:
inabakumori - Lagtrain (Vo. Kaai Yuki) / 稲葉曇『ラグトレイン』Vo. 歌愛ユキ
yt-dlp output title:
稲葉曇『ラグトレイン』Vo. 歌愛ユキ [UnIhRpIT7nc]
Command:
yt-dlp -x [youtube.com/watch?v=UnIhRpIT7nc](https://www.youtube.com/watch?v=UnIhRpIT7nc)
Issue:
The title is truncated to the part after the slash

That is the correct title. The rest is translated title which yt-dlp doesn't currently extract https://github.com/yt-dlp/yt-dlp/issues/387

```
❯ yt-dlp UnIhRpIT7nc -O filename= -O title=
filename = '稲葉曇『ラグトレイン』Vo. 歌愛ユキ [UnIhRpIT7nc].webm'
title = '稲葉曇『ラグトレイン』Vo. 歌愛ユキ'
```

The rest are not bugs - as in they are intentional changes. We can definitely discuss if/how it is possible to detect compatible filesystems and avoid those "translations"
