### ISSUE TITLE
Designating an output file for subtitles

### ISSUE THREAD

**Issue by 2011** [yt-dlp/yt-dlp#3396]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

I will describe this as a question that possibly indicates suboptimal behavior.

Yes, I read the warning about trying to directly assign an output file  name via the "-o" option (that appears to apply here, but I don't really understand the details). Should an output template that downloads **only** a subtitles file not directly follow -o? Perhaps the documentation could explain the default subtitles template (and provide examples).

Does some way exist to assign a specific file name? I particularly want to remove the language ("en") part, because otherwise my media player won't detect the existence of a subtitles file, and then I have to rename it manually, but don't believe the program should duplicate the extension in this case anyway.

Don't really need the verbose log for this (and obviously, I obfuscated the show URL).

Thank you in advance.

### Verbose log

```shell
$ yt-dlp-2022.04.08 --sub-format vtt --write-subs --skip-download 'https://www.cbs.com/shows/video/00000000000000000000000000000000/' -o foo.vtt 
[CBS] 00000000000000000000000000000000: Downloading XML
[CBS] 00000000000000000000000000000000: Downloading JSON metadata
[CBS] 00000000000000000000000000000000: Downloading StreamPack SMIL data
[CBS] 00000000000000000000000000000000: Downloading m3u8 information
[info] 00000000000000000000000000000000: Downloading 1 format(s): hls-4600
[info] Writing video subtitles to: foo.vtt.en.vtt
[download] Destination: foo.vtt.en.vtt
[download] 100% of 100.00KiB in 00:01
```

**Comment by pukkandan** [comment]
> Should an output template that downloads only a subtitles file not directly follow -o? 

Use `foo.%(ext)s`

> I particularly want to remove the language ("en") part,

This is currently not possible
