### ISSUE TITLE
How to Download Highest Quality Video+Audio and Merge to MP4?

### ISSUE THREAD

**Issue by AlexLandherr** [yt-dlp/yt-dlp#3398]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

I’m new to yt-dlp and am wondering how to download the highest quality (in terms of bitrate and resolution) for both video and audio and have them be merged to an .mp4 file?

Is there a single command for this? My OS is Windows 10.

I’ve done this with youtube-dl but it has been getting very slow (around 50 KiB/s usually and peaks at around 80 KiB/s) which is strange to me as my connection according to [Speedtest](https://www.speedtest.net/) is a few hundred Megabits/s.

I’ve tried a VPN but no real change there.

**Comment by dirkf** [comment]
YT decided to throttle the download links unless they were transformed according to some JavaScript logic in the YT player. This has been defeated in the released yt-dlp and the git master of yt-dl.

So basically, just use the defaults. yt-dlp has a slightly different idea of 'highest quality' but you should be fine either way.

**Comment by pukkandan** [comment]
>  ... and have them be merged to an .mp4 file?


Add a `-S ext:mp4:m4a` to the command

**Comment by AlexLandherr** [comment]
> >  ... and have them be merged to an .mp4 file?
> 
> 
> 
> 
> 
> Add a `-S ext:mp4:m4a` to the command

Thanks for the reply!

Will that handle any incoming audio and video format?

Say I want to download a 3840x2160 (or I don't know the maximum resolution) resolution video will the command `yt-dlp VIDEO_URL -S ext:mp4:m4a` give me an .mp4 with a the highest bitrate for both audio and video?

I'm entirely new to this fork as I come over from youtube-dl. If you can I would really appreciate any help on this.

**Comment by kipkaev** [comment]
> > ... and have them be merged to an .mp4 file?
> 
> Add a `-S ext:mp4:m4a` to the command

Even shortier. According to this example in official README at https://github.com/yt-dlp/yt-dlp
![image](https://github.com/yt-dlp/yt-dlp/assets/122740751/cc3fe4f4-8c8f-45ec-a477-f43650459191)
that's enough to specify just `-S ext`
