### ISSUE TITLE
Use project one name, not two different ones

### ISSUE THREAD

**Issue by axcore** [yt-dlp/yt-dlp#34]
## Checklist

- [x ] I'm reporting a feature request
- [x ] I've verified that I'm running yt-dlp version **2021.01.24**
- [x ] I've searched the bugtracker for similar feature requests including closed ones

## Description

[Tartube](https://github.com/axcore/tartube) is a GUI front-end for youtube-dl, youtube-dlc and other compatible downloaders.

At the moment, Tartube is not compatible with yt-dlp because the latter is using two different names. On [PyPI](https://pypi.org/project/yt-dlp/) your project is called yt-dlp, but the binary is still called youtube-dlc. Tartube assumes that both names are the same (and so will everything else).

So, my features request is to choose just one name.

**Comment by pukkandan** [comment]
When I changed the project name to yt-dlp, there were a few reasons I decided to keep the binary and module name as youtube-dlc. Most of them are small things, but the main reason is that it is honestly quite a bit of work to change it everywhere without messing anything up while there are almost no benefits for doing so.

It is probably easier to change tartube's code to allow for different package and binary names. But, if instead, you or anyone else wants to make a PR here with the necessary changes, I'd be glad to merge it.

**Comment by candrapersada** [comment]
or use [Releases · pukkandan_yt-dlp](https://github.com/pukkandan/yt-dlp/releases/) for a while
![image](https://user-images.githubusercontent.com/36833664/105754177-55807f00-5f7c-11eb-91f5-0743338cdaac.png)

**Comment by axcore** [comment]
>but the main reason is that it is honestly quite a bit of work to change it everywhere without messing anything up

How would you feel about using the name `youtube-dlp`?  blackjack4494 has already done the hard work of converting `youtube-dl` to `youtube-dlc` throughout the code, but only where necessary. So, in theory, we only need to update that subset of changes.

Anyway, I'm happy to do the work, I just need your go-ahead for it.

**Comment by pukkandan** [comment]
> Anyway, I'm happy to do the PR

Thanks

> you can decide for yourself whether it's worth merging or not

If you make the PR, I'll definitely merge it. I just dont wanna put in the effort

> I just need your preferred choice of name.

    yt-dlp

**Comment by pukkandan** [comment]
I just saw this: https://github.com/axcore/tartube/issues/254, which I assume is the reason you opened this issue here.

I would actually suggest you give an option in tartube to choose the package name and binary name separately. This will allow your users to install any fork using the `git+https://github.com/pukkandan/yt-dlp.git@release` even if the fork they want to use has no pypi package

**Comment by axcore** [comment]
As far as I can tell, not practical.

Consider this situation: the user installs youtube-dlc, then later installs yt-dlp. Later they decide to switch back to youtube-dlc (from Tartube, or from the command line). Only someone who has examine the source code knows that the earlier installation has been overwritten.

**Comment by axcore** [comment]
As far as I can tell, not practical.

Consider this situation: the user installs youtube-dlc, then later installs yt-dlp. Later they decide to switch back to youtube-dlc (from Tartube, or from the command line). Only someone who has examine the source code knows that the earlier installation has been overwritten.

Now the user tries to uninstall youtube-dlc. Suddenly yt-dlp doesn't work any more, because yt-dlp's executable has been removed.

Pic related: youtube-dl, youtube-dlc and yt-dlp installed on my system.

![bin](https://user-images.githubusercontent.com/37951926/106016244-2a4e7a80-60b7-11eb-8354-cd611ebd14ae.png)

**Comment by pukkandan** [comment]
I understand. While I can think of ways to workaround this problem, I can see how this could be annoying, especially to non tech-savy users

**Comment by candrapersada** [comment]
tartube can use the yt-dlp custom path by using
`python3 Downloads/youtube-dlc https://www.youtube.com/watch?v=CG8CX5mx2mk` or `python3 /home/user/Downloads/youtube-dl https://www.youtube.com/watch?v=CG8CX5mx2mk` without without installing the yt-dlp package to pypi
![image](https://user-images.githubusercontent.com/36833664/106035338-986e5e00-6106-11eb-8b46-61dc80b88132.png)
![image](https://user-images.githubusercontent.com/36833664/106035384-a4f2b680-6106-11eb-8004-c9d2eadb97ed.png)

**Comment by axcore** [comment]
Yes, but I will remove that soon, for the reasons above.

**Comment by pukkandan** [comment]
The module name has been completely changed to yt-dlp

**Comment by candrapersada** [comment]
how to remove youtube-dlc from pip3?

**Comment by pukkandan** [comment]
If you just want to overwrite it with youtube-dlc, use `pip3 install youtube-dlc`

Or uninstall and reinstall yt-dlp
```
pip3 uninstall yt-dlp
pip3 install yt-dlp
```
