### ISSUE TITLE
%(formats)j

### ISSUE THREAD

**Issue by tjsnowfun** [yt-dlp/yt-dlp#3403]
### Checklist

- [X] I'm reporting a feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.04.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

cmd：yt_dlp.exe url --print %(formats)j

How can I shorten and simplify the "formats" content to exclude the content I don't want?

formats:[
{ a:1,
b:2,
c:3,
d:4
} ,
{ a:1,
b:2,
c:3,
d:4
}
]

to

formats:[
{ a:1,
b:2
} ,
{ a:1,
b:2
}
]

**Comment by pukkandan** [comment]
I answered your question in #2932... This is not possible to do. You can use external tools (like `jq`?) to achieve what you want. 

Or are you requesting a feature to do this be added? If so, how would you propose the syntax for this look like? I can't think of how this can be done through the CLI

Don't spam!!! (#3402)

**Comment by tjsnowfun** [comment]
jq   how to do？

**Comment by tjsnowfun** [comment]
> I answered your question in #2932... This is not possible to do. You can use external tools (like `jq`?) to achieve what you want.
> 
> Or are you requesting a feature to do this be added? If so, how would you propose the syntax for this look like? I can't think of how this can be done through the CLI
> 
> Don't spam!!! (#3402)


jq     how to do?    thanks.

--print { id: %(id)j, title : %(title)j, formats : %(formats)j }

%(format.:.format_id)s
In this writing style, only one field could be extracted and used. The : format doesn't work effectively and it doesn't allow people to extract multiple fields.

**Comment by pukkandan** [comment]
With https://github.com/yt-dlp/yt-dlp/commit/07a1250e0e90515ff8142161536f9dafa6eaba1b, you can do:

```
❯ yt-dlp -O %(formats.:.{format_id,height})j test:youtube
[{"format_id": "139"}, {"format_id": "249"}, {"format_id": "250"}, {"format_id": "140"}, {"format_id": "251"}, {"format_id": "17", "height": 144}, {"format_id": "160", "height": 144}, {"format_id": "278", "height": 144}, {"format_id": "133", "height": 240}, {"format_id": "242", "height": 240}, {"format_id": "134", "height": 360}, {"format_id": "18", "height": 360}, {"format_id": "243", "height": 360}, {"format_id": "135", "height": 480}, {"format_id": "244", "height": 480}, {"format_id": "22", "height": 720}, {"format_id": "136", "height": 720}, {"format_id": "247", "height": 720}, {"format_id": "137", "height": 1080}, {"format_id": "248", "height": 1080}]
```
