### ISSUE TITLE
Best option to regularly crawl a channel and download new videos

### ISSUE THREAD

**Issue by jbreitbart** [yt-dlp/yt-dlp#3405]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

I am wondering what the best option is to check a youtube channel regularly (say every hour or so) and download a new video if it was uploaded? It seems like yt-dlp always checks every video, which can take quite a while for large channels and only causes unnecessary load. I have tried a few options, but I cannot figure out a way to prevent the check of every video that the channel ever uploaded.

I am currently using something like

yt-dlp --playlist-reverse --dateafter now-1week --download-archive downloaded.txt -i -o "%(uploader)s/S01E%(playlist_index)s - %(title)s.%(ext)s" -f "bestvideo[ext=mp4]+bestaudio[ext=m4a]" --merge-output-format mp4 --add-metadata --write-thumbnail --batch-file=channel_list.txt

Does anyone have a recommendation?

**Comment by pukkandan** [comment]
Try `--break-on-existing --break-per-input`

**Comment by jbreitbart** [comment]
Thanks a lot! That seems to work great. :)

**Comment by Myzel394** [comment]
Hey I'm facing the same issue. However, `--break-on-existing --break-per-input` doesn't seem to work. yt-dlp still downloads every video. Let's say I just want to download video from now - 1 week, how do I tell yt-dlp to break on all videos that are older than this?

**Comment by bashonly** [comment]
@Myzel394 `--dateafter "today-1week"` `--break-on-reject`

**Comment by jbreitbart** [comment]
> Hey I'm facing the same issue. However, `--break-on-existing --break-per-input` doesn't seem to work. yt-dlp still downloads every video. Let's say I just want to download video from now - 1 week, how do I tell yt-dlp to break on all videos that are older than this?

Btw: There is also https://github.com/jmbannon/ytdl-sub Maybe useful, depending on what you are trying to achieve

**Comment by Myzel394** [comment]
@bashonly That worked, thank you!

**Comment by wagler** [comment]
@bashonly Is there a way to extend this where only new videos which have a title containing a specific substring will be downloaded? For example, suppose there is a channel and I want to download only their new videos which contain "foo" within the video title. Does yt-dlp have a built in way to do this?

**Comment by bashonly** [comment]
@wagler
you're looking for the `--match-filters` option
`--match-filters "title*='foo'"`
which is interpreted by yt-dlp as: match videos where `title` contains (`*=`) `foo`

it can be used in conjunction with the `--date`... options:
`--match-filters "title*='foo'" --dateafter "today-1week"`

or you could do it this way, only using the `--match-filters` option:
`--match-filters "title*='foo' & upload_date>20230210"`

```
--match-filters FILTER          Generic video filter. Any "OUTPUT TEMPLATE"
                                field can be compared with a number or a
                                string using the operators defined in
                                "Filtering Formats". You can also simply
                                specify a field to match if the field is
                                present, use "!field" to check if the field
                                is not present, and "&" to check multiple
                                conditions. Use a "\" to escape "&" or
                                quotes if needed. If used multiple times,
                                the filter matches if atleast one of the
                                conditions are met. E.g. --match-filter
                                !is_live --match-filter "like_count>?100 &
                                description~='(?i)\bcats \& dogs\b'" matches
                                only videos that are not live OR those that
                                have a like count more than 100 (or the like
                                field is not available) and also has a
                                description that contains the phrase "cats &
                                dogs" (caseless). Use "--match-filter -" to
                                interactively ask whether to download each
                                video
```

**Comment by wagler** [comment]
> @wagler you're looking for the `--match-filters` option `--match-filters "title*='foo'"` which is interpreted by yt-dlp as: match videos where `title` contains (`*=`) `foo`
> 
> it can be used in conjunction with the `--date`... options: `--match-filters "title*='foo'" --dateafter "today-1week"`
> 
> or you could do it this way, only using the `--match-filters` option: `--match-filters "title*='foo' & upload_date>20230210"`
> 
> ```
> --match-filters FILTER          Generic video filter. Any "OUTPUT TEMPLATE"
>                                 field can be compared with a number or a
>                                 string using the operators defined in
>                                 "Filtering Formats". You can also simply
>                                 specify a field to match if the field is
>                                 present, use "!field" to check if the field
>                                 is not present, and "&" to check multiple
>                                 conditions. Use a "\" to escape "&" or
>                                 quotes if needed. If used multiple times,
>                                 the filter matches if atleast one of the
>                                 conditions are met. E.g. --match-filter
>                                 !is_live --match-filter "like_count>?100 &
>                                 description~='(?i)\bcats \& dogs\b'" matches
>                                 only videos that are not live OR those that
>                                 have a like count more than 100 (or the like
>                                 field is not available) and also has a
>                                 description that contains the phrase "cats &
>                                 dogs" (caseless). Use "--match-filter -" to
>                                 interactively ask whether to download each
>                                 video
> ```

@bashonly Thanks. Works like a charm. :)
