### ISSUE TITLE
Request: add before_merger to POSTPROCESS_WHEN 

### ISSUE THREAD

**Issue by CeruleanSky** [yt-dlp/yt-dlp#3409]
### Checklist

- [X] I'm reporting a feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.04.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

When downloading a youtube video yt-dlp goes through the following abbreviated stages:
[Exec before_dl]->[download]->[Merger]->[Metadata]->[Exec post_process]

I'd like an step before [Merger] that is called after the files are downloaded and concatenated but before the video and audio is merged.

Live streams can be several gigabytes of video with a few hundred for audio and can have some guests with terrible mic volume issues, and I'd like to do some 2-pass EBU R128 normalization on just the faster to process and smaller audio file with ffmpeg-normalize before yt-dlp merges things together.

[download] Destination: TEST_VIDEO-C0DPdy98e4c.f135.mp4
[download] Destination: TEST_VIDEO-C0DPdy98e4c.f140.m4a
**right here I'd like to call `ffmpeg-normalize TEST_VIDEO-C0DPdy98e4c.f140.m4a`  and use a batch file replace the old m4a file with one with better audio**
[Merger] Merging formats into "TEST_VIDEO-C0DPdy98e4c.mkv"

This is the workaround to fixup the audio for the latest episode on daily podcast playlist I download
```
for /f "delims=" %%a in ('yt-dlp -f 140 --playlist-item 1 https://www.youtube.com/playlist?list^=PLxxxxxxxxxxxxxxxxxxxxxxxxxxxx-xxx --get-filename -o "%%(id)s"') do @set youtube_id=%%a
for /f "delims=" %%a in ('yt-dlp -f 140 --get-filename https://www.youtube.com/watch?v^=%youtube_id%') do @set audio_filename=%%a
yt-dlp -f 140 --no-add-metadata --fixup=never --output "%%(title)s [%(id)s].f140.%%(ext)s"  %* https://www.youtube.com/watch?v=%youtube_id%
for /f "delims=" %%a in ('yt-dlp -f 136 --get-filename https://www.youtube.com/watch?v^=%youtube_id%') do @set video_filename=%%a
yt-dlp -f 136 --no-add-metadata --fixup=never --output "%%(title)s [%(id)s].f136.%%(ext)s" %* https://www.youtube.com/watch?v=%youtube_id%
ren %audio_filename% %audio_filename%.unormalized.m4a
ffmpeg-normalize %audio_filename%.unormalized.m4a -c:a aac -b:a 128k -o %audio_filename%
del %audio_filename%.unormalized.m4a
yt-dlp -f 136+140 https://www.youtube.com/watch?v=%youtube_id%
del %video_file% %audio_file%
```

**Comment by pukkandan** [comment]
Why not just run `-f bv,ba`, then normalize and merge the files with `--exec after_video:`?

Or, even better, you could pass the args for normalization into `--ppa Merger:`
