### ISSUE TITLE
How to Download Highest Available Resolution

### ISSUE THREAD

**Issue by AlexLandherr** [yt-dlp/yt-dlp#3410]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

I have trouble getting any higher resolution than 1920x1080 on the downloaded clips. And I know the videos I want to download have a higher resolution, namely 3840x2160 and up.

How do I modify this command `yt-dlp -S ext:mp4:m4a [url]` so that I can download the highest available resolution?

Or is it so that the command as it is now stops any higher resolutions?

**Comment by pukkandan** [comment]
I'm assuming this is continued from https://github.com/yt-dlp/yt-dlp/issues/3398 (You shouldve just followed up there...)

Use `-F` to check what formats are available. There is likely no mp4 format for that video above 1080p. If you want mp4 anyway, but also want the highest resolution, you need to re-encode the video using `--recode-video`

Go though the format selection/postprocessing options of the readme for more info

**Comment by AlexLandherr** [comment]
> I'm assuming this is continued from https://github.com/yt-dlp/yt-dlp/issues/3398 (You shouldve just followed up there...)
> 
> 
> 
> Use `-F` to check what formats are available. There is likely no mp4 format for that video above 1080p. If you want mp4 anyway, but also want the highest resolution, you need to re-encode the video using `--recode-video`
> 
> 
> 
> Go though the format selection/postprocessing option sections of the readme for more info

Would this work for my purposes?:
`yt-dlp --merge-output-format mp4 -f "bestvideo+bestaudio[ext=m4a]/best" [url]`

How can I make it work with the webm audio format? Is it better in quality than m4a?

**Comment by pukkandan** [comment]
You can put vp9 inside mp4 (if there is error, update ffmpeg), but that generally defeats the purpose of download mp4. If that is enough for your needs, sure, go ahead

**Comment by AlexLandherr** [comment]
Thanks! According to the -F option it seems m4a has the highest bitrate if "TBR" is bitrate.
