### ISSUE TITLE
Parallel's Toolbox, a paid commercial software, is using yt-dlp as it's video downloader

### ISSUE THREAD

**Issue by Aholicknight** [yt-dlp/yt-dlp#3411]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

[Parallel's Toolbox](https://www.parallels.com/ca/products/toolbox/) is a paid program suite for MacOS, which has a lot of tools such as convert video, record screen, recognize text, focus on window, and many more tools. 

One of the tools is called "Download Video" which as the title suggests, downloads videos from online sources. ![Screen Shot 2022-04-12 at 2 02 46 PM](https://user-images.githubusercontent.com/7843719/163044206-97219bd8-eb44-4b8b-a002-a2bf9c97efaf.png)

If you are using a security program on your macbook that allows you to deny or allow internet access, such as [LuLu](https://objective-see.com/products/lulu.html), or [Little Snitch](https://www.obdev.at/products/littlesnitch/index.html) you will notice that Parallel's Toolbox uses yt-dlp to download videos as seen here:

![yt-dlp](https://user-images.githubusercontent.com/7843719/163049702-42eda543-89f2-4743-ad4b-0dea2a2b5eb1.png)

I do not know if you allow people/companies to use your GitHub fork for commercial products, but I just thought I'd let you know.

**Comment by pukkandan** [comment]
yt-dlp and youtube-dl are currently distributed under [Unlicense](https://unlicense.org) which effectively puts all code in Public domain. Anyone is free to use it as they please, whether it be for other FOSS projects, or for commercial use.

See #2345 and linked issues for discussion regarding changing the license

**Comment by Aholicknight** [comment]
> yt-dlp and youtube-dl are currently distributed under [Unlicense](https://unlicense.org) which effectively puts all code in Public domain. Anyone is free to use it as they please, whether it be for other FOSS projects, or for commercial use.
> 
> See #2345 and linked issues for discussion regarding changing the license

Ah, sorry I did not know that this github repo + youtube-dl uses Unlicense
