### ISSUE TITLE
Spotify Extractor not working!

### ISSUE THREAD

**Issue by LonelyGuy12** [yt-dlp/yt-dlp#3415]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.04.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

Hey so I was using yt_dlp and looks like the [Spotify Extractor](https://github.com/ytdl-org/youtube-dl/blob/master/youtube_dl/extractor/spotify.py) ain't working properly

Reproducible Code :-
```from __future__ import unicode_literals
from yt_dlp import YoutubeDL
import os

ydl_opts = {
    'format': 'bestaudio/best',
    'postprocessors': [{
        'key': 'FFmpegExtractAudio',
        'preferredcodec': 'mp3',
        'preferredquality': '192'
    }],
    'postprocessor_args': [
        '-ar', '16000'
    ],
    'prefer_ffmpeg': True,
    'keepvideo': False,
    'outtmpl':'./audio.mp3'
}

try:
    os.remove(ydl_opts['outtmpl'])
except:
    pass

with YoutubeDL(ydl_opts) as ydl:
    ydl.download(['https://open.spotify.com/track/2OfQvGrr83FGpdLA1nAR01?si=c2b05ef071db451c'])
```

### Verbose log

```shell
[generic] 2OfQvGrr83FGpdLA1nAR01?si=c2b05ef071db451c: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] 2OfQvGrr83FGpdLA1nAR01?si=c2b05ef071db451c: Downloading webpage
[generic] 2OfQvGrr83FGpdLA1nAR01?si=c2b05ef071db451c: Extracting information
ERROR: Unsupported URL: https://open.spotify.com/track/2OfQvGrr83FGpdLA1nAR01?si=c2b05ef071db451c
```

**Comment by pukkandan** [comment]
The extractor only supports podcasts. Music on spotify is DRM protected and cannot be supported

**Comment by ole-tange** [comment]
Can we detect if an URL has DRM? If so, it would be helpful if the error message said: "Sorry, DRM restricted content."

**Comment by garret1317** [comment]
army of rabid copyright lawyers

**Comment by exorcist365** [comment]
> army of rabid copyright lawyers

Who they gonna sue tho

**Comment by exorcist365** [comment]
> Github does actually take down other repos that share drm breaking code.

bruh... thats why you dont host on gh...
