### ISSUE TITLE
add support for mashable

### ISSUE THREAD

**Issue by 2011** [yt-dlp/yt-dlp#3420]
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.04.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

global

### Example URLs

https://mashable.com/video/why-life-on-venus-is-better-than-mars

### Description

Fairly straightforward URLs (even a direct .mp4 download in addition to the .m3u8) in line 384 of the source. I hoped that the generic extractor might pick it up, but no luck there. :( Having yt-dlp find the URL, strip the escape characters, download the file and (I hope) add the page URL as a title (beyond the pana5xwYnW identifier) would definitely save some time. Thanks.

### Verbose log

```shell
$ yt-dlp-2022.04.08 -v 'https://mashable.com/video/why-life-on-venus-is-better-than-mars'
[debug] Command-line config: ['--restrict-filenames', '-o', '%(title)s-%(id)s-%(uploader)s.%(ext)s', '-w', '-v', 'https://mashable.com/video/why-life-on-venus-is-better-than-mars']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.04.08 [7884ade65] (zip)
[debug] Python version 3.9.9 (CPython 64bit) - Linux-5.15.11-with-glibc2.34
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.4.1 (setts), ffprobe 4.4.1
[debug] Optional libraries: certifi, Crypto
[debug] Proxy map: {}
[debug] [generic] Extracting URL: https://mashable.com/video/why-life-on-venus-is-better-than-mars
[generic] why-life-on-venus-is-better-than-mars: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] why-life-on-venus-is-better-than-mars: Downloading webpage
[generic] why-life-on-venus-is-better-than-mars: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://mashable.com/video/why-life-on-venus-is-better-than-mars
Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1408, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1478, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 641, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/generic.py", line 4039, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://mashable.com/video/why-life-on-venus-is-better-than-mars
```

**Comment by pukkandan** [comment]
@2011 Let us know if this is good enough or whether you still desire a dedicated extractor.

**Comment by 2011** [comment]
Does indeed work with the generic extractor now. I don't need anything more.
