### ISSUE TITLE
Run `--exec` command in the background

### ISSUE THREAD

**Issue by archiif** [yt-dlp/yt-dlp#3424]
### Checklist

- [X] I'm reporting a feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.04.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

Sometimes, we don't want to wait for the command executed by `--exec` to finish before exiting from yt-dlp.
On Linux, you can just append `&` to the end of the command, but there is no equivalent feature on Windows unless you install additional programs like Git Bash or WSL.
So it would be nice to have a built-in flag like `--exec-background`, which would run the command in the background using `subprocess.Popen` instead of `subprocess.call`.

**Comment by Jules-A** [comment]
Huh? Can't you already do it? I'm doing `--exec "start /B yt-dlp --config-location funimation.conf -q --fixup force --embed-subs --load-info-json %%(__infojson_filename)q"` and it launches in background for me.

**Comment by pukkandan** [comment]
See `help start` for windows

**Comment by archiif** [comment]
Ah, didn't realize that's a thing. Still, would be nice to have something consistent that works across platform.
Another question: is there a way to hide the program's output?

**Comment by pukkandan** [comment]
By its very nature, `--exec` is going to be OS-specific

> Another question: is there a way to hide the program's output?

`start /b cmd > nul`

These questions don't belong here. Ask them in appropriate forums
