### ISSUE TITLE
ArteTV: Video not available error on working video

### ISSUE THREAD

**Issue by tpikonen** [yt-dlp/yt-dlp#3428]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.04.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Europe

### Description

This URL fails with yt-dlp, but works in a browser: https://www.arte.tv/en/videos/108769-000-A/

Most other videos from Arte work fine.

### Verbose log

```shell
$ yt-dlp -vU https://www.arte.tv/en/videos/108769-000-A/
[debug] Command-line config: ['-vU', 'https://www.arte.tv/en/videos/108769-000-A/']
[debug] User config "/home/tpikonen/.config/yt-dlp/config": ['--sponsorblock-mark', 'all']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.04.08 [7884ade65] (source)
[debug] Lazy loading extractors is disabled
[debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
[debug] Git HEAD: cda1bc519
[debug] Python version 3.9.12 (CPython 64bit) - Linux-5.16.0-6-amd64-x86_64-with-glibc2.33
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.4.1-3 (setts), ffprobe 4.4.1-3
[debug] Optional libraries: brotli, certifi, Cryptodome, sqlite
[debug] Proxy map: {}
Latest version: 2022.04.08, Current version: 2022.04.08
yt-dlp is up to date (2022.04.08)
[debug] [ArteTV] Extracting URL: https://www.arte.tv/en/videos/108769-000-A/
[ArteTV] 108769-000-A: Downloading JSON metadata
ERROR: [ArteTV] 108769-000-A: Video 108769-000-A is not available
  File "/home/tpikonen/src/yt-dlp/git-yt-dlp/yt_dlp/extractor/common.py", line 634, in extract
    ie_result = self._real_extract(url)
  File "/home/tpikonen/src/yt-dlp/git-yt-dlp/yt_dlp/extractor/arte.py", line 66, in _real_extract
    raise ExtractorError(error, expected=True)
```

**Comment by fstirlitz** [comment]
#3302 extracts it fine.

**Comment by pukkandan** [comment]
https://github.com/yt-dlp/yt-dlp/issues/3622#issuecomment-1116756526
