### ISSUE TITLE
"make install" fails on macOS with "illegal option -- D"

### ISSUE THREAD

**Issue by jmayer** [yt-dlp/yt-dlp#3429]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.04.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

YT-DLP Version:
jmayer@newegg:~/work/video/youtube-dl/yt-dlp(master)$ git describe
fatal: No annotated tags can describe 'cda1bc51973c89b72b916dcc40dbe3d7f457097d'.

macOS Version:
System Version:	macOS 12.3.1 (21E258)
Kernel Version:	Darwin 21.4.0

Error:
jmayer@newegg:~/work/video/youtube-dl/yt-dlp(master)$ sudo make install
COLUMNS=80 /usr/bin/env python3 yt_dlp/__main__.py --help | /usr/bin/env python3 devscripts/make_readme.py
/usr/bin/env python3 devscripts/prepare_manpage.py yt-dlp.1.temp.md
pandoc -s -f markdown -t man yt-dlp.1.temp.md -o yt-dlp.1
rm -f yt-dlp.1.temp.md
install -Dm755 yt-dlp ./usr/local/bin/yt-dlp
install: illegal option -- D
...
make: *** [install] Error 64

### Verbose log

```shell
dummy
```

**Comment by jmayer** [comment]
jmayer@newegg:~/work/video/youtube-dl/yt-dlp(master)$ xcodebuild -version
Xcode 13.3
Build version 13E113

**Comment by Lesmiscore** [comment]
The Makefile from yt-dlp assumes GNU coreutils.

manpages are here for reference
https://man7.org/linux/man-pages/man1/install.1.html
https://ss64.com/osx/install.html

Can you please try either:
- Install GNU coreutils via `brew install coreutils` and replace `install` commands with `ginstall` (no option translation required),
- Or replace all occurrences of `-Dm` with `-dm`

**Comment by jmayer** [comment]
I have ginstall - but it isn't used.
I just tried replacing -D with -d but while -d and -D are  are doing similar things they not sufficiently similar (treats the file at the end as a directory and fails if the binary already exists).

Maybe I should close this bug and open a new one that ginstall isn't used if available instead of install?

**Comment by dirkf** [comment]
`-d` isn't what you want. yt-dlp is the executable archive here, no?

Try
`mkdir -p ./usr/local/bin && install -m755 yt-dlp ./usr/local/bin`

**Comment by pukkandan** [comment]
```diff
diff --git a/Makefile b/Makefile
index a254afa86..e62e302f1 100644
--- a/Makefile
+++ b/Makefile
@@ -43,11 +43,16 @@ SYSCONFDIR = $(shell if [ $(PREFIX) = /usr -o $(PREFIX) = /usr/local ]; then ech
 MARKDOWN = $(shell if [ `pandoc -v | head -n1 | cut -d" " -f2 | head -c1` = "2" ]; then echo markdown-smart; else echo markdown; fi)

 install: lazy-extractors yt-dlp yt-dlp.1 completions
-       install -Dm755 yt-dlp $(DESTDIR)$(BINDIR)/yt-dlp
-       install -Dm644 yt-dlp.1 $(DESTDIR)$(MANDIR)/man1/yt-dlp.1
-       install -Dm644 completions/bash/yt-dlp $(DESTDIR)$(SHAREDIR)/bash-completion/completions/yt-dlp
-       install -Dm644 completions/zsh/_yt-dlp $(DESTDIR)$(SHAREDIR)/zsh/site-functions/_yt-dlp
-       install -Dm644 completions/fish/yt-dlp.fish $(DESTDIR)$(SHAREDIR)/fish/vendor_completions.d/yt-dlp.fish
+       mkdir -p $(DESTDIR)$(BINDIR)
+       install -m755 yt-dlp $(DESTDIR)$(BINDIR)/yt-dlp
+       mkdir -p $(DESTDIR)$(MANDIR)/man1
+       install -m644 yt-dlp.1 $(DESTDIR)$(MANDIR)/man1/yt-dlp.1
+       mkdir -p $(DESTDIR)$(SHAREDIR)/bash-completion/completions
+       install -m644 completions/bash/yt-dlp $(DESTDIR)$(SHAREDIR)/bash-completion/completions/yt-dlp
+       mkdir -p $(DESTDIR)$(SHAREDIR)/zsh/site-functions
+       install -m644 completions/zsh/_yt-dlp $(DESTDIR)$(SHAREDIR)/zsh/site-functions/_yt-dlp
+       mkdir -p $(DESTDIR)$(SHAREDIR)/fish/vendor_completions.d
+       install -m644 completions/fish/yt-dlp.fish $(DESTDIR)$(SHAREDIR)/fish/vendor_completions.d/yt-dlp.fish

 codetest:
        flake8 .
```
Does this fix your issue? If so, I can commit it since it's not a big change. But in general, it's impractical to try and support the various configurations that don't have GNU coreutils.

PRs for supporting `ginstall` is welcome though as long as it falls back to `install`

**Comment by jmayer** [comment]
Yes, that solved the problem. While I agree that "in general, it's impractical to try and support the various configurations that don't have GNU coreutills" coreutils in general support being installed with a leading "g" and so the build process should first search for coreutils starting with "g" before using a version without leading "g". This may become even more impractical  without using something like configure or cmake :-)

I also needed to apply another change to get things to actually install properly:
 PREFIX ?= /usr/local
-DESTDIR ?= .
+# DESTDIR ?= .
 BINDIR ?= $(PREFIX)/bin
What's the idea behind using the current directory as DESTDIR if DESTDIR is unset?

**Comment by pukkandan** [comment]
> What's the idea behind using the current directory as DESTDIR if DESTDIR is unset?

It was done for #386. Though I see how that wasn't the right way to implement it. I was, at the time, not familiar with makefile conventions at all (even worse than now)
