### ISSUE TITLE
Python Package Seems Broken

### ISSUE THREAD

**Issue by hl2guide** [yt-dlp/yt-dlp#344]
## Checklist

- [N/A] I'm reporting a broken site support issue
- [x] I've verified that I'm running yt-dlp version **2021.05.20**
- [N/A] I've checked that all provided URLs are alive and playable in a browser
- [N/A] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

`yt-dlp.exe`

```
Traceback (most recent call last):
  File "c:\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Python39\Scripts\yt-dlp.exe\__main__.py", line 4, in <module>
ModuleNotFoundError: No module named 'yt_dlp'

```

## Description

I'm using cached yt_dlp-2021.5.20-py2.py3-none-any.whl (2.1 MB).

Python package seems non-functional.

**Comment by hl2guide** [comment]
hmm, now its woring for me (same version). Strange.

**Comment by pukkandan** [comment]
I was gonna write "cant reproduce", but I see you've gotten it working too. If you encounter this again, please reopen with the exact steps needed to reproduce
