### ISSUE TITLE
[niconico] KeyError occurs when using `--load-info-json`

### ISSUE THREAD

**Issue by i6t** [yt-dlp/yt-dlp#3440]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.04.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Description

This problem occurs when trying to download videos using `--load-info-json`. It does not occur when entering the URL directly.

```
$ yt-dlp --write-info-json --skip-download https://www.nicovideo.jp/watch/sm39334235
[niconico] sm39334235: Downloading webpage
[info] sm39334235: Downloading 1 format(s): h264_1080p-aac_192kbps-http
[info] Writing video metadata as JSON to: God-ish feat. Hatsune Miku [sm39334235].info.json
```
[God-ish feat. Hatsune Miku [sm39334235].info.json.txt](https://github.com/yt-dlp/yt-dlp/files/8497513/God-ish.feat.Hatsune.Miku.sm39334235.info.json.txt)

### Verbose log

```shell
[debug] Command-line config: ['-vU', '--load-info-json', 'God-ish feat. Hatsune Miku [sm39334235].info.json']
[debug] Encodings: locale cp932, fs utf-8, out utf-8, err utf-8, pref cp932
[debug] yt-dlp version 2022.04.08 [7884ade] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg n5.0.1-20220405 (setts), ffprobe n5.0.1-20220405
[debug] Optional libraries: brotli, certifi, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.04.08, Current version: 2022.04.08
yt-dlp is up to date (2022.04.08)
[debug] Default format spec: bestvideo*+bestaudio/best
[info] sm39334235: Downloading 1 format(s): h264_1080p-aac_192kbps-http
[debug] Invoking downloader on "niconico_dmc:sm39334235/archive_h264_1080p/archive_aac_192kbps"
[niconico_dmc] Downloading from DMC
Traceback (most recent call last):
  File "yt_dlp\__main__.py", line 19, in <module>
  File "yt_dlp\__init__.py", line 869, in main
  File "yt_dlp\__init__.py", line 857, in _real_main
  File "yt_dlp\YoutubeDL.py", line 3276, in download_with_info_file
  File "yt_dlp\YoutubeDL.py", line 3237, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1548, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2648, in process_video_result
  File "yt_dlp\YoutubeDL.py", line 3138, in process_info
  File "yt_dlp\YoutubeDL.py", line 2846, in dl
  File "yt_dlp\downloader\common.py", line 457, in download
  File "yt_dlp\downloader\niconico.py", line 21, in real_download
  File "yt_dlp\extractor\niconico.py", line 218, in _get_heartbeat_info
KeyError: '_expected_protocol'
[6908] Failed to execute script '__main__' due to unhandled exception!
```

**Comment by pukkandan** [comment]
The heartbeat mechanism don't work with `--load-info-json`. We could look into this when implementing #3048

**Comment by pukkandan** [comment]
actually, nvm. I was thinking of the old implementation. this should be easy to fix
