### ISSUE TITLE
Facebook video and special characters

### ISSUE THREAD

**Issue by wankio** [yt-dlp/yt-dlp#3444]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.04.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

`ERROR: unable to open for writing: [Errno 22] Invalid argument: 'C:\\youtube-dl\\facebook\\�.. _ Tr&#x1b0;&#x1edd;ng h&#x1ee3;p n&#xe0;y ph&#x1ea3;i c&#xe1;c c&#x1ee5; khi b&#x1ead;t d&#x1ea1;y c&#xf3; cho thanh ni&#xea;n kia m&#x1ed9;t tr&#x1ead;n kh&#xf4;ng , ch&#x1a1;i ki&#x1ec3;u n&#xe0;y kh&#xe1;c n&#xe0;o g.i.&#xea;.t ng&#x1b0;&#x1edd;i &#xfffd;...-NA-NA-3214644252147296.f1023329444972024a.m4a.part'`

i can still download with yt-dlp [link] [-o I:\1.mp4]

### Verbose log

```shell
ERROR: unable to open for writing: [Errno 22] Invalid argument: 'I:\\youtube-dl\\facebook\\�... _ Tr&#x1b0;&#x1edd;ng h&#x1ee3;p n&#xe0;y ph&#x1ea3;i c&#xe1;c c&#x1ee5; khi b&#x1ead;t d&#x1ea1;y c&#xf3; cho thanh ni&#xea;n kia m&#x1ed9;t tr&#x1ead;n kh&#xf4;ng , ch&#x1a1;i ki&#x1ec3;u n&#xe0;y kh&#xe1;c n&#xe0;o g.i.&#xea;.t ng&#x1b0;&#x1edd;i &#xfffd;...-NA-NA-3214644252147296.f1023329444972024a.m4a.part'
Traceback (most recent call last):
  File "C:\Users\GEN32UC\AppData\Local\Programs\Python\Python38\lib\site-packages\yt_dlp\utils.py", line 690, in sanitize_open
    raise LockingUnsupportedError()
yt_dlp.utils.LockingUnsupportedError: File locking is not supported on this platform

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\GEN32UC\AppData\Local\Programs\Python\Python38\lib\site-packages\yt_dlp\downloader\http.py", line 263, in download
    ctx.stream, ctx.tmpfilename = self.sanitize_open(
  File "C:\Users\GEN32UC\AppData\Local\Programs\Python\Python38\lib\site-packages\yt_dlp\downloader\common.py", line 221, in inner
    return func(self, *args, **kwargs)
  File "C:\Users\GEN32UC\AppData\Local\Programs\Python\Python38\lib\site-packages\yt_dlp\downloader\common.py", line 238, in sanitize_open
    f, filename = sanitize_open(filename, open_mode)
  File "C:\Users\GEN32UC\AppData\Local\Programs\Python\Python38\lib\site-packages\yt_dlp\utils.py", line 693, in sanitize_open
    stream = open(filename, open_mode)
OSError: [Errno 22] Invalid argument: 'I:\\youtube-dl\\facebook\\�... _ Tr&#x1b0;&#x1edd;ng h&#x1ee3;p n&#xe0;y ph&#x1ea3;i c&#xe1;c c&#x1ee5; khi b&#x1ead;t d&#x1ea1;y c&#xf3; cho thanh ni&#xea;n kia m&#x1ed9;t tr&#x1ead;n kh&#xf4;ng , ch&#x1a1;i ki&#x1ec3;u n&#xe0;y kh&#xe1;c n&#xe0;o g.i.&#xea;.t ng&#x1b0;&#x1edd;i &#xfffd;...-NA-NA-3214644252147296.f1023329444972024a.m4a.part'
```

**Comment by dirkf** [comment]
Isn't this what `--windows-filenames` is for? Or `--restrict-filenames` if OP were actually using yt-dl as the directory name suggests.

**Comment by pukkandan** [comment]
Provide ENTIRE verbose log

**Comment by pukkandan** [comment]
> Isn't this what `--windows-filenames` is for? Or `--restrict-filenames` 

Who knows what command OP is even running. The title shouldn't have escape chars in the first place. And even if it does, the `&` should be automatically sanitized by yt-dlp/youtube-dl even without any options. If OP had atleast given the URL, we could test...

> if OP were actually using yt-dl as the directory name suggests.

They are using yt-dlp

**Comment by dirkf** [comment]
There, 'were' is 3rd person singular subjunctive as I reckon OP as 1 person. For some reason I confused the log here with another that I previously studied where ytdl-patched masqueraded as yt-dl in its top-level directory, so the whole comment was pointless.

**Comment by modelD-svg** [comment]
Hello, sorry for bumping this issue.

I ran into the same problem. From what I can tell it's caused on windows in utils.py on line 695 if the length of `(current path + filename)` exceeds 255. 
I am executing using python and the following parameters: `ydl_opts = {"windowsfilenames": True, "trim_file_name": 40}` - windowsfilenames and trim do not seem to fix this.

Adding these two lines as a quick fix worked for me:
```
                if len(filename) > 200:
                    filename = filename[:200] + ".mp4"
```
I chose 200 because the length of the path the file is written to, is approx. 40. Of course this is a shitty fix for a multitude of reasons, but I just needed to quickly download a couple of videos :p

Thanks for the great work you do.

Full snippet for better understanding:
```
    for attempt in range(2):
        try:
            try:
                if sys.platform == 'win32':
                    # FIXME: An exclusive lock also locks the file from being read.
                    # Since windows locks are mandatory, don't lock the file on windows (for now).
                    # Ref: https://github.com/yt-dlp/yt-dlp/issues/3124
                    raise LockingUnsupportedError()
                stream = locked_file(filename, open_mode, block=False).__enter__()
            except LockingUnsupportedError:

                if len(filename) > 255:
                    filename = filename[:200] + ".mp4"

                stream = open(filename, open_mode)
            return (stream, filename)
        except (IOError, OSError) as err:
            if attempt or err.errno in (errno.EACCES,):
                raise
            old_filename, filename = filename, sanitize_path(filename)
            if old_filename == filename:
                raise
```

**Comment by dirkf** [comment]
If the filename is too long, just modify the [output template](https://github.com/yt-dlp/yt-dlp#user-content-output-template), limiting the length of the overlong field, as in `%(title).50s`.

See also yt-dl PR https://github.com/ytdl-org/youtube-dl/pull/29989, where the discussion shows why a proper solution is tricky.

**Comment by pukkandan** [comment]
> limiting the length of the overlong field, as in %(title).50s

Note that the actual limit is in bytes. If the title has unicode characters, `.Ns` may contain upto 2N bytes. To account for this, yt-dlp supports the syntax `%(title).200B` instead to trim to 200 bytes. This is recommended when trimming to limit path length

>  and trim do not seem to fix this

While the output template method is recommended, `trim_file_name` should also do the job. If it does not work, provide verbose log (preferably in a new issue)
