### ISSUE TITLE
[cbs] Damaged downloads

### ISSUE THREAD

**Issue by 2011** [yt-dlp/yt-dlp#3445]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

I have encountered some difficulties recently with downloads that have many fragments, where one corrupted fragment messes up the entire video. With youtube-dl, the success or failure of every fragment got logged to the screen, and I could easily see (before even playing the media) that a problem existed. With yt-dlp, I don't see any error messages, although options might exist that I don't know about that could warn me that something went wrong. In almost all cases, simply running yt-dlp a second (or sometimes a third) time correctly fetches the media. The non-corrupt file usually comes in maybe ~.5 MB smaller, and (per mediainfo) ~30 seconds shorter in duration.

The log below came from a download that ended up unsuccessful (within the first five minutes, scenes started repeating and the video/audio became completely unsynchronized with the subtitles), without any indication of an error while fetching any of the fragments. Does some way exist (without some super debug mode such as writing all http traffic to a file) of displaying an error message when a fragment download fails?

### Verbose log

```shell
$ yt-dlp -f hls-4597 -v 'https://www.cbs.com/shows/video/EUieoC5GJgbXdacM5OWQMrN7WamQVS2t/' 
[debug] Command-line config: ['--restrict-filenames', '-o', '%(title)s-%(id)s-%(uploader)s.%(ext)s', '-w', '-f', 'hls-4597', '-v', 'https://www.cbs.com/shows/video/EUieoC5GJgbXdacM5OWQMrN7WamQVS2t/']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.04.08 [7884ade65] (zip)
[debug] Python version 3.9.9 (CPython 64bit) - Linux-5.15.11-with-glibc2.34
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.4.1 (setts), ffprobe 4.4.1
[debug] Optional libraries: certifi, Crypto
[debug] Proxy map: {}
[debug] [CBS] Extracting URL: https://www.cbs.com/shows/video/EUieoC5GJgbXdacM5OWQMrN7WamQVS2t/
[CBS] EUieoC5GJgbXdacM5OWQMrN7WamQVS2t: Downloading XML
[CBS] EUieoC5GJgbXdacM5OWQMrN7WamQVS2t: Downloading JSON metadata
[CBS] EUieoC5GJgbXdacM5OWQMrN7WamQVS2t: Downloading StreamPack SMIL data
[CBS] EUieoC5GJgbXdacM5OWQMrN7WamQVS2t: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[info] EUieoC5GJgbXdacM5OWQMrN7WamQVS2t: Downloading 1 format(s): hls-4597
[debug] Invoking downloader on "https://cbsios-vh.akamaihd.net/i/temp_hd_gallery_video/CBS_Production_Outlet_VMS/video_robot/CBS_Production_Entertainment/2022/03/08/2010692675993/SURVIVOR_4203_TR_2997_8CH_1920x1080_1246927_,2228,4628,3128,1628,848,503,000.mp4.csmil/index_1_av.m3u8?null=0&id=AgBZu7GjFys7nBl0WWKI%2flEBy5AkYXonW+Q63FODp%2fwkZH3xE48T7n1I2hjybkF75%2fshd6mKbAnTsQ%3d%3d&hdntl=exp=1650115993~acl=%2fi%2ftemp_hd_gallery_video%2fCBS_Production_Outlet_VMS%2fvideo_robot%2fCBS_Production_Entertainment%2f2022%2f03%2f08%2f2010692675993%2fSURVIVOR_4203_TR_2997_8CH_1920x1080_1246927_*~data=hdntl~hmac=11332071dbdebbe60f8a868e96ba52654d1c225f5164504bb495e4114474c600"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 258
[download] Destination: Survivor_-_Go_for_the_Gusto-EUieoC5GJgbXdacM5OWQMrN7WamQVS2t-CBSI-NEW.mp4
[download] 100% of 1.42GiB in 15:56
[debug] ffprobe command line: ffprobe -hide_banner -show_format -show_streams -print_format json file:Survivor_-_Go_for_the_Gusto-EUieoC5GJgbXdacM5OWQMrN7WamQVS2t-CBSI-NEW.mp4
[FixupM3u8] Fixing MPEG-TS in MP4 container of "Survivor_-_Go_for_the_Gusto-EUieoC5GJgbXdacM5OWQMrN7WamQVS2t-CBSI-NEW.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i file:Survivor_-_Go_for_the_Gusto-EUieoC5GJgbXdacM5OWQMrN7WamQVS2t-CBSI-NEW.mp4 -map 0 -dn -ignore_unknown -c copy -f mp4 -bsf:a aac_adtstoasc -movflags +faststart file:Survivor_-_Go_for_the_Gusto-EUieoC5GJgbXdacM5OWQMrN7WamQVS2t-CBSI-NEW.temp.mp4
```

**Comment by pukkandan** [comment]
If some fragment fails to download, yt-dlp will show that in log, the same way as youtube-dl. Possible issues I can think of are:

* the video is damaged at source - Does the video play correctly in browser at same resolution with DRM disabled?
* There is some bug in yt-dlp's download process - Does it work if you use `--downloader ffmpeg`?
* ffmpeg is damaging the file - Try updating your ffmpeg or using `--fixup never`

I would prefer not to have to download this big video for testing. Can you check if you are able to reproduce the issue with the smaller formats or with a smaller video?

**Comment by 2011** [comment]
> If some fragment fails to download, yt-dlp will show that in log, the same way as youtube-dl. Possible issues I can think of are:

I never saw any log messages (yt-dlp generally produces far less output, which I generally prefer, unless, of course, something goes wrong).

> * the video is damaged at source - Does the video play correctly in browser at same resolution with DRM disabled?

I would reject this possibility. In every case, I could simply try the download again (although occasionally I had to make a third attempt), and would get the uncorrupted file). Historically (with youtuble-dl in previous years), this would randomly happen about once per season of a series (but the youtube-dl output always indicated the error). When I filed this bug, I had encountered this three or four weeks in a row, but (a week or two later), the problem disappeared, and I have not encountered it since.

> * There is some bug in yt-dlp's download process - Does it work if you use `--downloader ffmpeg`?
> * ffmpeg is damaging the file - Try updating your ffmpeg or using `--fixup never`

I will check these if and when I see the problem in the future. I do have a fairly recent ffmpeg, though.

> I would prefer not to have to download this big video for testing. Can you check if you are able to reproduce the issue with the smaller formats or with a smaller video?

I believe that CBS places most of their content behind their paywall four weeks after the air date, so it would require a subscription to access the given video at this time. Again, I successfully downloaded this simply by retrying after I discovered the corruption in the file. Sorry that this behavior doesn't reproduce more consistently.

**Comment by pukkandan** [comment]
Were you able to reproduce the issue again?

**Comment by 2011** [comment]
Haven't tried. I will look for something I want to watch there, but it might take a couple of weeks.

**Comment by pukkandan** [comment]
Can reopen if you can repro again

**Comment by 2011** [comment]
Not a problem. Thanks.

**Comment by 2011** [comment]
@pukkandan I don't want to open a new bug for this issue for a number of reasons (first, I didn't use the -v option, second, I used the .mpd file, which calls the generic extractor instead of the site-specific extractor, and third, I used the frowned-upon --allow-unplayable-formats option), but I did want to pass along some output (and ask a couple of questions).

It seems I get a lot of errors that cause retries (an average of about 40 for a 1.4 GB video download):

```
[generic] stream: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] stream: Extracting information
[info] stream: Downloading 2 format(s): 5, 6
[dashsegments] Total fragments: 432
[download] Destination: stream-stream-NA.mp4

[...]

[download]  66.6% of ~   1.34GiB at   16.67KiB/s ETA 11:53 (frag 288/432)[download] Got error: Downloaded 179980 bytes, expected 4060533 bytes. Retrying (1/10)...
[download] Got error: <urlopen error EOF occurred in violation of protocol (_ssl.c:1145)>. Retrying (2/10)...
[download]  73.2% of ~   1.34GiB at   40.97KiB/s ETA 09:30 (frag 316/432)[download] Got error: Downloaded 442363 bytes, expected 3061843 bytes. Retrying (1/10)...
[download]  73.3% of ~   1.34GiB at   86.86KiB/s ETA 09:31 (frag 316/432)[download] Got error: Downloaded 1875612 bytes, expected 3061843 bytes. Retrying (2/10)...
[download]  75.2% of ~   1.35GiB at  355.37KiB/s ETA 08:49 (frag 324/432)[download] Got error: Downloaded 3837632 bytes, expected 3854083 bytes. Retrying (1/10)...
[download]  75.5% of ~   1.34GiB at   61.09KiB/s ETA 08:46 (frag 326/432)[download] Got error: Downloaded 659578 bytes, expected 3161690 bytes. Retrying (1/10)...
[download]  77.0% of ~   1.34GiB at  183.24KiB/s ETA 08:15 (frag 332/432)[download] Got error: Downloaded 1979159 bytes, expected 2508457 bytes. Retrying (1/10)...
[download]  80.0% of ~   1.34GiB at  243.34KiB/s ETA 07:07 (frag 345/432)[download] Got error: Downloaded 2628400 bytes, expected 3626504 bytes. Retrying (1/10)...
[download]  84.1% of ~   1.34GiB at  100.42KiB/s ETA 05:38 (frag 363/432)[download] Got error: Downloaded 1084750 bytes, expected 3641608 bytes. Retrying (1/10)...
[download]  86.0% of ~   1.34GiB at  116.17KiB/s ETA 04:57 (frag 371/432)[download] Got error: Downloaded 1254838 bytes, expected 3120869 bytes. Retrying (1/10)...
[download]  86.9% of ~   1.34GiB at   88.59KiB/s ETA 04:40 (frag 375/432)[download] Got error: Downloaded 956612 bytes, expected 3406826 bytes. Retrying (1/10)...
[download]  89.7% of ~   1.34GiB at  233.59KiB/s ETA 03:38 (frag 387/432)[download] Got error: Downloaded 2523128 bytes, expected 3572695 bytes. Retrying (1/10)...
[download]  91.7% of ~   1.34GiB at   51.54KiB/s ETA 02:57 (frag 396/432)[download] Got error: Downloaded 556911 bytes, expected 3148938 bytes. Retrying (1/10)...
[download]  99.5% of ~   1.35GiB at  405.52KiB/s ETA 00:09 (frag 430/432)

ERROR: Did not get any data blocks
[download] fragment not found; Skipping fragment 431 ...
[download] 100% of    1.34GiB in 00:35:16 at 664.76KiB/s
[dashsegments] Total fragments: 432
[download] Destination: stream-stream-NA.m4a
[download]  13.7% of ~  59.04MiB at   67.39KiB/s ETA 16:07 (frag 59/432)[download] Got error: <urlopen error EOF occurred in violation of protocol (_ssl.c:1145)>. Retrying (1/10)...
[download]  26.4% of ~  59.52MiB at   75.45KiB/s ETA 13:22 (frag 114/432)[download] Got error: Remote end closed connection without response. Retrying (1/10)...
[download]  45.1% of ~  59.74MiB at   33.52KiB/s ETA 10:46 (frag 195/432)ERROR: unable to download video data: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1145)>
```

First, any idea about what causes these errors?

Second, how can a SSL: CERTIFICATE_VERIFY_FAILED error occur on fragment 195 of 432 (and not before)?

Once again, the downloads (both video and audio) succeeded on the second attempt, but still with numerous "Remote end closed connection without response," "<urlopen error EOF occurred in violation of protocol (_ssl.c:1145)>," and "Downloaded i bytes, expected j bytes" errors.
