### ISSUE TITLE
[Feature Request] Tags and Categories without square brackets or quotation marks

### ISSUE THREAD

**Issue by MrDemous** [yt-dlp/yt-dlp#345]
## Checklist

- [ x] I'm reporting a feature request
- [x ] I've verified that I'm running yt-dlp version **2021.05.20**
- [ x] I've searched the bugtracker for similar feature requests including closed ones

## Description

Is it possible to make yt-dlp write categories and tags that get embedded in a video file without square brackets or quotation marks? *[] ' "*

Currently, they get written like this:

 ['A Quiet Place Part II', 'Movie Review', 'Chris Stuckmann', 'A Quiet Place 2', 'Reviews', 'Film', 'Scene', 'Clip', 'Trailer', 'Teaser', 'Horror', 'Emily Blunt', 'Millicent Simmonds', 'Cillian Murphy', 'Noah Jupe', 'Djimon Hounsou', 'John Krasinski']

It'd be better if they get written like this:

A Quiet Place Part II, Movie Review, Chris Stuckmann, A Quiet Place 2, Reviews, Film, Scene, Clip, Trailer, Teaser, Horror, Emily Blunt, Millicent Simmonds, Cillian Murphy, Noah Jupe, Djimon Hounsou, John Krasinski

Makes it better for apps like Plex media server to scan the tags and present them properly.

P.S. I mentioned it on discord a couple of days ago but I thought I'd make a request here so that it can be tracked or accepted/rejected easily.

**Comment by pukkandan** [comment]
right now, the easiest solution is to use `--exec` to rename it after download. While I do plan to add a metadata search-replacer, I cannot promise on any timeline or it

**Comment by MrDemous** [comment]
Okay, I've been googling for a bit trying to figure this out but can't figure it out.

Might telling me how I can achieve this with ffmpeg or atomicparsley using `--exec` ?

**Comment by pukkandan** [comment]
With https://github.com/yt-dlp/yt-dlp/commit/db81f83fdd8086b7641bc50a1e438b06488600d7, you can use `%(tags)l`
