### ISSUE TITLE
yt-dlp (subtitles help)

### ISSUE THREAD

**Issue by HondaTooru97** [yt-dlp/yt-dlp#3450]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

Hi! Does anyone know a way to be able to put subtitles as the default track? **--embed-subs --sub-format ass --remux-video mkv** with this command it muxes them together in the video but I have to select them by hand as the first track, can someone help me please? T_T

### Verbose log

```shell
yt-dlp --cookies .\cookies.txt -o "%(series)s.%(season)s.S%(season_number)02dE%(episode_number)02d.%(height)sp.Crunchyroll.WEB-DL.%(ext)s" --restrict-filenames -v --sub-lang itIT --write-sub --hls-prefer-ffmpeg --embed-subs --sub-format ass --remux-video mkv https://www.crunchyroll.com/love-all-play/episode-3-entering-school-842280
```

**Comment by pukkandan** [comment]
This is more of an ffmpeg question than a yt-dlp one...

Try this https://stackoverflow.com/a/35235287. Also see https://github.com/yt-dlp/yt-dlp/issues/2799

**Comment by CZeil** [comment]
You could do the following, off the top of my head I assume it would work.

```--ppa "VideoRemuxer: -disposition:s:0 default"```
