### ISSUE TITLE
[BBC iPlayer] Currently live programmes fail to download with error similar to #2979

### ISSUE THREAD

**Issue by whitebear60** [yt-dlp/yt-dlp#3452]
### Checklist

- [X] I'm reporting a site feature request
- [X] I've verified that I'm running yt-dlp version **2022.04.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United Kingdom

### Example URLs

https://www.bbc.co.uk/iplayer/episode/m0016l94/the-wall-series-4-versus-celebrities-5-martin-shirlie-kemp
https://www.bbc.co.uk/iplayer/episode/p0c00vfl/snooker-world-championship-2022-live-selby-v-jones-table-1

(basically, any programme episode with the "live" mark, that is currently airing on BBC iPlayer or BBC channels)

### Description

When I'm trying to invoke yt-dlp on the link to the programme, that is currently live on BBC channels/BBC iPlayer, I'm getting an error "local variable programme_id referenced before assignment". When I'm trying to download video that is avialavle "On Demand", it works correctly.

Is this error with live videos related with #2979, and possible to fix? 

Thank you

### Verbose log

```shell
C:\Users\WhiteBear60> yt-dlp -Uv https://www.bbc.co.uk/iplayer/episode/m0016l94/the-wall-series-4-versus-celebrities-5-martin-shirlie-kemp
[debug] Command-line config: ['-Uv', 'https://www.bbc.co.uk/iplayer/episode/m0016l94/the-wall-series-4-versus-celebrities-5-martin-shirlie-kemp']
[debug] Encodings: locale cp1251, fs utf-8, out utf-8, err utf-8, pref cp1251
[debug] yt-dlp version 2022.04.08 [7884ade] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.22000-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 2022-02-24-git-8ef03c2ff1-full_build-www.gyan.dev (setts), ffprobe 2022-02-24-git-8ef03c2ff1-full_build-www.gyan.dev
[debug] Optional libraries: brotli, certifi, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.04.08, Current version: 2022.04.08
yt-dlp is up to date (2022.04.08)
[debug] [bbc.co.uk] Extracting URL: https://www.bbc.co.uk/iplayer/episode/m0016l94/the-wall-series-4-versus-celebrities-5-martin-shirlie-kemp
[bbc.co.uk] m0016l94: Downloading video page
[bbc.co.uk] m0016l94: Downloading playlist JSON
ERROR: local variable 'programme_id' referenced before assignment
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1408, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1478, in __extract_info
  File "yt_dlp\extractor\common.py", line 641, in extract
  File "yt_dlp\extractor\bbc.py", line 582, in _real_extract
  File "yt_dlp\extractor\bbc.py", line 479, in _download_playlist
UnboundLocalError: local variable 'programme_id' referenced before assignment```

**Comment by pukkandan** [comment]
It's the same exact issue as https://github.com/yt-dlp/yt-dlp/issues/2979
