### ISSUE TITLE
Add support for Hotmart

### ISSUE THREAD

**Issue by ahm750** [yt-dlp/yt-dlp#3453]
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.04.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Example URLs

- Course playlist: https://hotmart.com/product/platinum-yoga-su-misura/E39738113D?sck=HOTMART_SITE

### Description

Would it be possible to add support for videos from hotmart.com? It requires users to be logged in before they can view videos.

### Verbose log

```shell
The output log is very log and my terminal doesn't display the whole things.
```

**Comment by pukkandan** [comment]
> The output log is very log and my terminal doesn't display the whole things.

I still need to see it!!

```
yt-dlp -sUv "URL" --cookies-from-browser chrome > log.txt 2>&1
```
Then upload `log.txt` here

**Comment by svenop5** [comment]
There a few issues here:

- the page scraping extractor is broken as the video provider has changed to hotmart
- hotmart authentication is probably different to the previous video provider
- video segments are encrypted and although segment decryption is supported, the URL for the encryption key itself (m3u8 EXT-X-KEY) is also encrypted

So even if you deal with the first two issues you still have the last one. How practical a solution is would depend on how often the video provider changes their EXT-X-KEY encryption strategy and how easy those changes are to determined.

**Comment by walksonair** [comment]
How can I DM you a hotmart URL to try?

**Comment by muhamed-didovic** [comment]
@pukkandan here is log file
[log.txt](https://github.com/yt-dlp/yt-dlp/files/13612816/log.txt)
