### ISSUE TITLE
Feature request: List videos that are present in my archive.txt, but not on youtube

### ISSUE THREAD

**Issue by NavinF** [yt-dlp/yt-dlp#3468]
### Checklist

- [X] I'm reporting a feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.04.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

Context: I've got many terabytes of videos in my collection and would like to make offsite backups of only the rare ones where I might be the only one with  a copy. 

I am using this command to download videos:

`yt-dlp --retries 4 --write-info-json --write-description --write-thumbnail --all-subs --download-archive archive.txt --batch-file playlist.txt`

Adding `--simulate`  only queries youtube for videos present in a playlist, but not in my archive which is the opposite of what I want. 

`--simulate --dump-json`  seems to be the closest to what I want (query youtube for every video and check if it's available), but requires converting archive.txt to a playlist txt and processing the output to discard the jsons.

**Comment by NavinF** [comment]
Here's what I use right now: 

```
#!/usr/bin/bash
set -xeo pipefail
ionice -c 3 nice -n 20 yt-dlp --retries 4 --batch-file <(cat archive.txt | cut -d ' ' -f 2) --simulate --dump-json | grep ERROR
```

Video IDs can be extracted from this with `cut -d' ' -f 3 |cut -d':' -f 1`

**Comment by pukkandan** [comment]
There isn't really any feature request here. The format b/w archive and --batch-file are  different because they serve different purposes. You could use `--print-to-file` to write the URLs to another file if you so desire. But since you only have the archive, all you can do is convert it to the right format

PS: Instead of `--dump-json 2>&1`, you can just do `-q`
