### ISSUE TITLE
Need short alias for --config-location

### ISSUE THREAD

**Issue by DaVyper** [yt-dlp/yt-dlp#3469]
### Checklist

- [X] I'm reporting a feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.04.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

--config-location is excessively long especially if one uses it more than once. even using it only once it is still longer than some thing the config might be holding.
Ex:
```
yt-dlp --config-location MusicAlbums.conf <url>
vs
ytdlp -x --audio-format mp3 <url>
```
so something like `-CL <config-location>` would shorten it and make it much less annoying for short but less memorable strings

**Comment by pukkandan** [comment]
Option names can be shortened as long as there is no ambiguity. So --config works

**Comment by DaVyper** [comment]
well why not -conf or -cf/-cl does -config really make it all that much less ambiguous?
heck --ignore-warnings is shortened to -i ...

**Comment by afterdelight** [comment]
-cl is better

**Comment by afterdelight** [comment]
I agree with --config

**Comment by pukkandan** [comment]
Both of you seem to have misunderstood my comment. I am saying **you** can shorten any option as long as yt-dlp can uniquely match it to an existing option. So you can **already** reduce `--config-locations` to `--config-location`, `--config-loc`, `--config` or even `--conf`

Anyway, I am also working on a feature that lets you define custom aliases: https://github.com/pukkandan/yt-dlp-dev/tree/features/alias

**Comment by DaVyper** [comment]
Ahh, I just interpreted that as you were just saying it could be done in the code, not that I could do it by just typing in less :P  Thanks for that, I'll go try that out

**Comment by DaVyper** [comment]
```
yt-dlp --conf
Usage: yt-dlp [OPTIONS] URL [URL...]

yt-dlp: error: --config-locations option requires 1 argument
```
Yep it works fine, thanks again

**Comment by rahaaatul** [comment]
> ```
> yt-dlp --conf
> Usage: yt-dlp [OPTIONS] URL [URL...]
> 
> yt-dlp: error: --config-locations option requires 1 argument
> ```
> Yep it works fine, thanks again

How to fix this error?

**Comment by DaVyper** [comment]
It's not an error, you need to specify a config file after --conf/-config-location as yt-dlp isn't a mind reader
