### ISSUE TITLE
Retrieving just the extractor and video ID without network

### ISSUE THREAD

**Issue by legraphista** [yt-dlp/yt-dlp#3471]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

I'm looking for a way to pass the URL and retrieve just the extractor and video ID without doing any network requests, just by leveraging the extractor's regexes.

Is there a possibility for this?

**Comment by legraphista** [comment]
I've written a small PY script to do so, but i'd love for someone to confirm that it is the proper way to do so:
```python
from yt_dlp import extractor

url = 'https://www.youtube.com/watch?v=2J7xlDH4QkA'

extractors = extractor.gen_extractors()
info_list = [(ie.IE_NAME, ie.get_temp_id(url) or url) for ie in extractors if ie.suitable(url) and ie.working()]

print(info_list[0])
```

**Comment by pukkandan** [comment]
This works for youtube, but will not work on all sites. If fact it is impossible to have a general implementation for this:
1. It's not necessary that ID is present in the URL
2. The temp_id may not be the actual video_id

Btw, you don't need to check for ie.working. Excluding GenericIE, there will always only be one match for suitable

**Comment by legraphista** [comment]
Ah yes, you're right! 
For example, those 2 facebook URLs point to the same video 
- https://fb.watch/ct0YPSGXqH/ 
- https://www.facebook.com/watch?v=2650205305123883

but while my small script returns only a generic extractor for `https://fb.watch/ct0YPSGXqH/`, running `yt-dlp -J https://fb.watch/ct0YPSGXqH/ | jq ".id"` will return `2650205305123883`

**Comment by legraphista** [comment]
Thanks for the quick response!
