### ISSUE TITLE
Metadata error since commit 19a0394

### ISSUE THREAD

**Issue by vagabondshrimp** [yt-dlp/yt-dlp#3472]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.04.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

Error since commit [19a0394](https://github.com/yt-dlp/yt-dlp/commit/19a0394044bfad36cd665450271b8eb048a41c02).

### Verbose log

```shell
yt-dlp -F -v https://www.youtube.com/watch?v=kUKinGYoeDA
[debug] Command-line config: ['-F', '-v', 'https://www.youtube.com/watch?v=kUKinGYoeDA']
[debug] User config "C:\Users\rizky\AppData\Roaming\yt-dlp\config.txt": ['-4', '--geo-bypass', '--cookies', 'C:\\Users\\rizky\\AppData\\Roaming\\yt-dlp\\cookies.txt', '-S', 'fps,tbr', '--downloader', 'aria2c', '--downloader-args', 'aria2c:-c -x 10 -s 10', '--add-metadata', '--parse-metadata', ':(?P<meta_comment>)(?P<meta_description>)(?P<meta_synopsis>)', '--embed-subs', '--sub-lang', 'en,en-US', '--embed-thumbnail', '-o', 'E:/Data/ytdl/%(title)s.%(ext)s', '-f', 'bv*[height<=720]+ba/bv*[height<=720]/b', '--remux-video', 'mkv']
Usage: yt-dlp [OPTIONS] URL [URL...]

yt-dlp: error: --parse-metadata ":(?P<meta_comment>)(?P<meta_description>)(?P<meta_synopsis>)" is invalid; 'function' object has no attribute 'value'
```

**Comment by pukkandan** [comment]
I have no clue how I made this mistake 🤦. Thanks for catching
