### ISSUE TITLE
Partially downloaded files have the executable bit set

### ISSUE THREAD

**Issue by fstirlitz** [yt-dlp/yt-dlp#3473]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.04.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

I noticed that while a stream download is in progress, the .part files with the partially-download data have the executable permission bit set. This is nonsensical, as the files are not actually executable.

The final download files do not have the executable bit set, making this problem transient and mostly cosmetic.

### Verbose log

```sh-session
$ yt-dlp --version
2022.04.08
$ ls -l   # while yt-dlp https://www.youtube.com/channel/UCaJzpFqRQa0Bcu9BWi_drKw -f bestaudio is active in another terminal
[SNIP]
-rw-r--r-- 1 stirlitz stirlitz 3539889 2019-11-23  'The X2 Anthem GM [Cw_KFkaDRtA].webm'
-rwxr-xr-x 1 stirlitz stirlitz  261120 04-18 17:21 'Thinking of You [yoXZMdmUlyQ].webm.part'
-rw-r--r-- 1 stirlitz stirlitz 3544772 2020-05-19  'Time Machine 2019 [3zjtMpBkVSE].webm'
[SNIP]
```

**Comment by pukkandan** [comment]
Even you don't provide verbose log!? 😭 

The issue is supposed to be fixed by https://github.com/yt-dlp/yt-dlp/commit/98804d034d04d21cbeb8cd43d1e1d90f1cdae836. But Idk whether you are using master or release

**Comment by fstirlitz** [comment]
I thought it wouldn’t be particularly relevant. No, this is not a (homebrew) nightly build, it’s the normal release. (I normally use those only for development.)

I guess the ticket can be closed then.

**Comment by pukkandan** [comment]
> I thought it wouldn’t be particularly relevant. 

The verbose head is always relevant, at least to get the exact version info
```
[debug] yt-dlp version 2022.04.08 [7884ade65] (source)
[debug] Lazy loading extractors is disabled
[debug] Git HEAD: 6f638d325
[debug] Python version 3.10.4 (CPython 64bit) - Windows-10-10.0.22000-SP0
```

**Comment by fstirlitz** [comment]
Granted. What can I say, laziness got the best of me.

Wouldn’t it be good to include that detailed version info in `--version` output, though?

**Comment by pukkandan** [comment]
It is possible other apps (like GUIs) depend on `--version` output to check for updates. So changing it's structure could be problematic
