### ISSUE TITLE
[Help] Truncating of filename doesn't work for sidecar files like info.json

### ISSUE THREAD

**Issue by GlassedSilver** [yt-dlp/yt-dlp#3476]
The args I'm using are these, I'll have to get un-429's by YT before I can retry and provide verbose logs I think. Sorry :/ But maybe the args already tell the story?

```
    '-o',
        'subscriptions/channels/イル_フローラ/%(uploader)s [%(channel_id)s]/%(upload_date)s - %(title)200B [%(id)s].%(ext)s',
        '--write-info-json',
        '--print-json',
        '-f',
        'bestvideo+bestaudio',
        '--merge-output-format',
        'mp4',
        '--cookies',
        'appdata/cookies.txt',
        '--download-archive',
        '/app/subscriptions/archives/イル_フローラ/merged_video.txt',
        '--write-thumbnail',
        '--no-call-home',
        '--write-info-json',
        '--no-clean-infojson',
        '--write-subs',
        '--sub-langs',
        'en.*,de,fr,jp,ko,zh.*,live_chat',
        '--sub-format',
        'srt/ass/best',
        '--write-thumbnail',
        '--write-comments',
        '--extractor-args',
        'youtube:comment_sort=top',
        '--extractor-args',
        'funimation:version=uncut',
        '--geo-bypass',
        '--sponsorblock-mark',
        'all',
        '--no-call-home',
        '--write-info-json',
        '--no-clean-infojson',
        '--write-subs',
        '--sub-langs',
        'en.*,de,fr,jp,ko,zh.*,live_chat',
        '--sub-format',
        'srt/ass/best',
        '--write-thumbnail',
        '--write-comments',
        '--extractor-args',
        'youtube:comment_sort=top',
        '--extractor-args',
        'funimation:version=uncut',
        '--geo-bypass',
        '--sponsorblock-mark',
        'all',
        '--no-clean-infojson'
```

Context:

1) I am using yt-dlp within a project I (try to) help maintain (I'm not a programmer, but I like to think I'm not bad at troubleshooting, support and some other stuff. Currently I'm keeping the ship afloat whilst the creator of the app is on a needed hiatus, so I'm trying to do my best)

2) the previous comment trail:  
> Use `.200s` for 200 characters and `.200B` for 200 bytes

Could it be that this only propagates to the video file name and the info.json can still fail? Either that or the application I'm trying to maintain interferes with yt-dlp handling this well otherwise.

_Originally posted by @GlassedSilver in https://github.com/yt-dlp/yt-dlp/issues/1837#issuecomment-1101469382_

**Comment by pukkandan** [comment]
> 'subscriptions/channels/イル_フローラ/%(uploader)s [%(channel_id)s]/%(upload_date)s - %(title)200B [%(id)s].%(ext)s',

It should be `.200B`. You missed the dot. But since your video download is fine, I assume that isn't the issue. Nothing else looks wrong in the config. Provide the log when you are able to

**Comment by GlassedSilver** [comment]
I added the period, and it seems to have fixed it. I'll close the issue now and if I encounter the bug again or if I just got lucky on some files I'll comment again, but so far so good I guess! :D

Thank you so much!
