### ISSUE TITLE
NBC Saturday Night Live

### ISSUE THREAD

**Issue by jriker1** [yt-dlp/yt-dlp#3478]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.04.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

US

### Description

I'm trying to download Saturday Night Live like every week.  Erroring now.  Tried updating my cookie file but still no joy. 

yt-dlp -U
Latest version: 2022.04.08, Current version: 2022.04.08

### Verbose log

```shell
[debug] Command-line config: ['--audio-quality', '0', '--add-metadata', '--ap-mso', 'Comcast_SSO', '--ap-username', 'PRIVATE', '--ap-password', 'PRIVATE', 'https://www.nbc.com/saturday-night-live/video/april-16-lizzo/9000199375', '-o', 'Saturday Night Live S47E18.mp4', '--cookies', 'c:\\temp\\nbc.com_cookies.txt', '--ffmpeg-location', 'z:\\ffmpeg\\bin', '--verbose']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.04.08 [7884ade65]
[debug] Python version 3.9.0 (CPython 64bit) - Windows-10-10.0.19041-SP0
[debug] Checking exe version: "z:\ffmpeg\bin\ffmpeg" -bsfs
[debug] Checking exe version: "z:\ffmpeg\bin\ffprobe" -bsfs
[debug] exe versions: ffmpeg 4.4-full_build-www.gyan.dev (setts), ffprobe 4.4-full_build-www.gyan.dev, phantomjs 2.1.1
[debug] Optional libraries: brotli, certifi, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [NBC] Extracting URL: https://www.nbc.com/saturday-night-live/video/april-16-lizzo/9000199375
[NBC] 9000199375: Downloading JSON metadata
[NBC] 9000199375: Downloading JSON metadata
[debug] Loading ap-mvpd.nbcentertainment from cache
[NBC] 9000199375: Downloading Provider Redirect Page
ERROR: [NBC] 9000199375: Unable to extract post url; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "C:\Users\jriker\AppData\Local\Programs\Python\Python39\lib\site-packages\yt_dlp\extractor\common.py", line 641, in extract
    ie_result = self._real_extract(url)
  File "C:\Users\jriker\AppData\Local\Programs\Python\Python39\lib\site-packages\yt_dlp\extractor\nbc.py", line 144, in _real_extract
    query['auth'] = self._extract_mvpd_auth(
  File "C:\Users\jriker\AppData\Local\Programs\Python\Python39\lib\site-packages\yt_dlp\extractor\adobepass.py", line 1489, in _extract_mvpd_auth
    provider_login_page_res = post_form(
  File "C:\Users\jriker\AppData\Local\Programs\Python\Python39\lib\site-packages\yt_dlp\extractor\adobepass.py", line 1396, in post_form
    post_url = self._html_search_regex(r'<form[^>]+action=(["\'])(?P<url>.+?)\1', form_page, 'post url', group='url')
  File "C:\Users\jriker\AppData\Local\Programs\Python\Python39\lib\site-packages\yt_dlp\extractor\common.py", line 1238, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "C:\Users\jriker\AppData\Local\Programs\Python\Python39\lib\site-packages\yt_dlp\extractor\common.py", line 1229, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
```

**Comment by pukkandan** [comment]
Are you saying this used to work till last week 🤔? Comcast support is known to be broken for a while now https://github.com/yt-dlp/yt-dlp/issues/516

**Comment by jriker1** [comment]
Yes used to work until now, with SNL being once a week of course.  And oddly it started working again this morning.
