### ISSUE TITLE
Error of cutting srt file

### ISSUE THREAD

**Issue by kebinzhi** [yt-dlp/yt-dlp#3480]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.04.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

https://youtu.be/6Af6b_wyiwI

yt-dlp -f mp4 -f 136+140/298+140 -o /data/data/com.termux/files/home/storage/movies/YouTube/%(title)s-%(release_date,upload_date)s.%(ext)s -R, --retries 20 --sponsorblock-remove all --sub-langs "en.\*,zh.\*" --sub-format srt --convert-subs srt --write-subs

There is a bug when postprocessing try to cut a srt file from the "--sponsorblock-remove all" parameter. And it works good to cut a video file.
Can you guys fix that? Thanks very much.

![1](https://user-images.githubusercontent.com/20044735/164021367-1bd3b615-b87e-4ce2-8a38-6182c7c2601c.jpg)
![2](https://user-images.githubusercontent.com/20044735/164022627-14350002-a1c4-4efc-87cf-0be0f51591bd.jpg)

By the way, I know yt-dlp save the title with the original title by the uploader. But, is there a parameter to save the translated title?

### Verbose log

```shell
[ModifyChapters] Removing chapters from /data/data/com.termux/files/home/storage/movies/YouTube/Bill Gates - The next outbreak We’re not ready _ TED-20150403.mp4
[ModifyChapters] Removing chapters from /data/data/com.termux/files/home/storage/movies/YouTube/Bill Gates - The next outbreak We’re not ready _ TED-20150403.en.srt
ERROR: Postprocessing: file:/data/data/com.termux/files/home/storage/movies/YouTube/Bill Gates - The next outbreak We’re not ready _ TED-20150403.en.temp.srt.concat: Math result not representable
```

**Comment by nihil-admirari** [comment]
Same as https://github.com/yt-dlp/yt-dlp/issues/2753.

This time SRT starts at ~17 sec.:
```
1
00:00:17,504 --> 00:00:19,398
When I was a kid,

...
```
and cutting ends at ~12 sec.:
```
ffconcat version 1.0
file 'file:YouTube/Bill Gates - The next outbreak We’re not ready _ TED-20150403.en.srt'
inpoint 12.366479
outpoint 511.673340
```

FFmpeg devs have not reacted to the previous bug report: https://trac.ffmpeg.org/ticket/9646. You can try to ping them once more.
