### ISSUE TITLE
ERROR: 'Video' is not a valid URL.

### ISSUE THREAD

**Issue by OscarTAG** [yt-dlp/yt-dlp#3484]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

Hi, it's my first time using GitHub, if I make any mistakes, I apologise.
I attempted to download a paywalled livestream which uses .m3u8 format using --cookies and this error popped up.
I first used the HLS Downloader Extension to get the .m3u8 file I needed, then used the EditThisCookie Extention to get the cookies and paste them in a .txt. The command has the file path of the .txt file.
I'm not tech-savvy so I don't know what is going wrong, is the .m3m8 file broken, or is there some other error?
Any help would be greatly appreciated. :)

### Verbose log

```shell
C:\Users\User\Desktop\VTUBERS\ホロライブ\YouTube Video Downloader>youtube-dl.exe -vU --cookies C:\Users\User\Desktop\VTUBERS\ホロライブ\YouTube Video Downloader\spwn.jp_cookies.txt "https://vod2.spwn.jp/spwn-vod2/22031901-jphololive3rdfes/grp1/cam1_v1/index_12.m3u8"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-vU', '--cookies', 'C:\\Users\\User\\Desktop\\VTUBERS\\ホロライブ\\YouTube', 'Video', 'Downloader\\spwn.jp_cookies.txt', 'https://vod2.spwn.jp/spwn-vod2/22031901-jphololive3rdfes/grp1/cam1_v1/index_12.m3u8']
[debug] Encodings: locale cp932, fs mbcs, out cp932, pref cp932
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg 4.3.1-2020-11-19-full_build-www.gyan.dev
[debug] Proxy map: {}
youtube-dl is up-to-date (2021.12.17)
ERROR: 'Video' is not a valid URL. Set --default-search "ytsearch" (or run  youtube-dl "ytsearch:Video" ) to search YouTube
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\generic.py", line 2364, in _real_extract
youtube_dl.utils.ExtractorError: 'Video' is not a valid URL. Set --default-search "ytsearch" (or run  youtube-dl "ytsearch:Video" ) to search YouTube
```

**Comment by MinePlayersPE** [comment]
wrap the cookies location path in quotes

**Comment by OscarTAG** [comment]
C:\Users\User\Desktop\VTUBERS\ホロライブ\YouTube Video Downloader>youtube-dl.exe -vU --cookies "C:\Users\User\Desktop\VTUBERS\ホロライブ\YouTube Video Downloader\spwn.jp_cookies.txt" "https://vod2.spwn.jp/spwn-vod2/22031901-jphololive3rdfes/grp1/cam1_v1/index_12.m3u8"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-vU', '--cookies', 'C:\\Users\\User\\Desktop\\VTUBERS\\ホロライブ\\YouTube Video Downloader\\spwn.jp_cookies.txt', 'https://vod2.spwn.jp/spwn-vod2/22031901-jphololive3rdfes/grp1/cam1_v1/index_12.m3u8']
WARNING: skipping cookie file entry due to invalid length 1: '[\n'
WARNING: skipping cookie file entry due to invalid length 1: '{\n'
WARNING: skipping cookie file entry due to invalid length 1: '    "domain": ".spwn.jp",\n'
WARNING: skipping cookie file entry due to invalid length 1: '    "hostOnly": false,\n'
WARNING: skipping cookie file entry due to invalid length 1: '    "httpOnly": false,\n'
WARNING: skipping cookie file entry due to invalid length 1: '    "name": "CloudFront-Key-Pair-Id",\n'
WARNING: skipping cookie file entry due to invalid length 1: '    "path": "/",\n'
WARNING: skipping cookie file entry due to invalid length 1: '    "sameSite": "unspecified",\n'
WARNING: skipping cookie file entry due to invalid length 1: '    "secure": false,\n'
WARNING: skipping cookie file entry due to invalid length 1: '    "session": true,\n'
WARNING: skipping cookie file entry due to invalid length 1: '    "storeId": "0",\n'
WARNING: skipping cookie file entry due to invalid length 1: '    "value": "K33HSRY3XILYEV",\n'
WARNING: skipping cookie file entry due to invalid length 1: '    "id": 1\n'
WARNING: skipping cookie file entry due to invalid length 1: '},\n'
WARNING: skipping cookie file entry due to invalid length 1: '{\n'
WARNING: skipping cookie file entry due to invalid length 1: '    "domain": ".spwn.jp",\n'
WARNING: skipping cookie file entry due to invalid length 1: '    "hostOnly": false,\n'
WARNING: skipping cookie file entry due to invalid length 1: '    "httpOnly": false,\n'
WARNING: skipping cookie file entry due to invalid length 1: '    "name": "CloudFront-Policy",\n'
WARNING: skipping cookie file entry due to invalid length 1: '    "path": "/",\n'
WARNING: skipping cookie file entry due to invalid length 1: '    "sameSite": "unspecified",\n'
WARNING: skipping cookie file entry due to invalid length 1: '    "secure": false,\n'
WARNING: skipping cookie file entry due to invalid length 1: '    "session": true,\n'
WARNING: skipping cookie file entry due to invalid length 1: '    "storeId": "0",\n'
WARNING: skipping cookie file entry due to invalid length 1: '    "value": "eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly92b2QyLnNwd24uanAvc3B3bi12b2QyLzIyMDMxOTAxLWpwaG9sb2xpdmUzcmRmZXMvZ3JwMS9jYW0xX3YxLyoiLCJDb25kaXRpb24iOnsiSXBBZGRyZXNzIjp7IkFXUzpTb3VyY2VJcCI6IjAuMC4wLjAvMCJ9LCJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTY1MDQ2Njc5OTAwMH19fV19",\n'
WARNING: skipping cookie file entry due to invalid length 1: '    "id": 2\n'
WARNING: skipping cookie file entry due to invalid length 1: '},\n'
WARNING: skipping cookie file entry due to invalid length 1: '{\n'
WARNING: skipping cookie file entry due to invalid length 1: '    "domain": ".spwn.jp",\n'
WARNING: skipping cookie file entry due to invalid length 1: '    "hostOnly": false,\n'
WARNING: skipping cookie file entry due to invalid length 1: '    "httpOnly": false,\n'
WARNING: skipping cookie file entry due to invalid length 1: '    "name": "CloudFront-Signature",\n'
WARNING: skipping cookie file entry due to invalid length 1: '    "path": "/",\n'
WARNING: skipping cookie file entry due to invalid length 1: '    "sameSite": "unspecified",\n'
WARNING: skipping cookie file entry due to invalid length 1: '    "secure": false,\n'
WARNING: skipping cookie file entry due to invalid length 1: '    "session": true,\n'
WARNING: skipping cookie file entry due to invalid length 1: '    "storeId": "0",\n'
WARNING: skipping cookie file entry due to invalid length 1: '    "value": "GrgM3ay2CWLzwMhg77NmVGQY1kJvKQGEc-r7XZ7U1fZR5Cp4PsX~6hcrf6uOmPGZASggo/k6XcHxh7O444TG8CdXOlQDSr+KDUloajEEhh9yiFZOjBh1KP7hDJMfg0rH4Djju3Wj/+eaYU90tN/THHtAoo8Zy34OI5qmyKWP2cjapaf5TYtnW/cSuWJ0awQWEbhHENyCMwy/cVodqUAEEASoF0wDCI6BfH2yvHT70JFX8D6S4NrcdSN3fAHLP1tYQsYIgqqxwN/I+hyEVJyDOb/LLQt/Eln24ZXQom6pu94t5MJXbYFSA5GrBypptRQG79aQRz96xz53f/tnYOJfZQ_=",\n'
WARNING: skipping cookie file entry due to invalid length 1: '    "id": 3\n'
WARNING: skipping cookie file entry due to invalid length 1: '},\n'
WARNING: skipping cookie file entry due to invalid length 1: '{\n'
WARNING: skipping cookie file entry due to invalid length 1: '    "domain": ".spwn.jp",\n'
WARNING: skipping cookie file entry due to invalid length 1: '    "hostOnly": false,\n'
WARNING: skipping cookie file entry due to invalid length 1: '    "httpOnly": false,\n'
WARNING: skipping cookie file entry due to invalid length 1: '    "name": "last-domain",\n'
WARNING: skipping cookie file entry due to invalid length 1: '    "path": "/",\n'
WARNING: skipping cookie file entry due to invalid length 1: '    "sameSite": "unspecified",\n'
WARNING: skipping cookie file entry due to invalid length 1: '    "secure": true,\n'
WARNING: skipping cookie file entry due to invalid length 1: '    "session": true,\n'
WARNING: skipping cookie file entry due to invalid length 1: '    "storeId": "0",\n'
WARNING: skipping cookie file entry due to invalid length 1: '    "value": "virtual.spwn.jp",\n'
WARNING: skipping cookie file entry due to invalid length 1: '    "id": 4\n'
WARNING: skipping cookie file entry due to invalid length 1: '},\n'
WARNING: skipping cookie file entry due to invalid length 1: '{\n'
WARNING: skipping cookie file entry due to invalid length 1: '    "domain": ".spwn.jp",\n'
WARNING: skipping cookie file entry due to invalid length 1: '    "hostOnly": false,\n'
WARNING: skipping cookie file entry due to invalid length 1: '    "httpOnly": false,\n'
WARNING: skipping cookie file entry due to invalid length 1: '    "name": "uid",\n'
WARNING: skipping cookie file entry due to invalid length 1: '    "path": "/",\n'
WARNING: skipping cookie file entry due to invalid length 1: '    "sameSite": "unspecified",\n'
WARNING: skipping cookie file entry due to invalid length 1: '    "secure": true,\n'
WARNING: skipping cookie file entry due to invalid length 1: '    "session": true,\n'
WARNING: skipping cookie file entry due to invalid length 1: '    "storeId": "0",\n'
WARNING: skipping cookie file entry due to invalid length 1: '    "value": "9QScLy4trrVjMRwuj3AqkLe3vai2",\n'
WARNING: skipping cookie file entry due to invalid length 1: '    "id": 5\n'
WARNING: skipping cookie file entry due to invalid length 1: '}\n'
WARNING: skipping cookie file entry due to invalid length 1: ']'
Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\__init__.py", line 475, in main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\__init__.py", line 442, in _real_main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 422, in __init__
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 2379, in _setup_opener
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\utils.py", line 2841, in load
  File "C:\Python\Python34\lib\http\cookiejar.py", line 2005, in _really_load
http.cookiejar.LoadError: 'C:\\Users\\User\\Desktop\\VTUBERS\\ホロライブ\\YouTube Video Downloader\\spwn.jp_cookies.txt' does not look like a Netscape format cookies file

my cookies are wrong???

**Comment by MinePlayersPE** [comment]
yes, that's a json-formatted file and not a netscape-formatted one

use something like https://chrome.google.com/webstore/detail/get-cookiestxt/bgaddhkoddajcdgocldbbfleckgcbcid to export your cookies

**Comment by OscarTAG** [comment]
C:\Users\User\Desktop\VTUBERS\ホロライブ\YouTube Video Downloader>youtube-dl.exe -vU --cookies "C:\Users\User\Desktop\VTUBERS\ホロライブ\YouTube Video Downloader\spwn.jp_cookies.txt" "https://vod2.spwn.jp/spwn-vod2/22031901-jphololive3rdfes/grp1/cam1_v1/index_12.m3u8"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-vU', '--cookies', 'C:\\Users\\User\\Desktop\\VTUBERS\\ホロライブ\\YouTube Video Downloader\\spwn.jp_cookies.txt', 'https://vod2.spwn.jp/spwn-vod2/22031901-jphololive3rdfes/grp1/cam1_v1/index_12.m3u8']
[debug] Encodings: locale cp932, fs mbcs, out cp932, pref cp932
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg 4.3.1-2020-11-19-full_build-www.gyan.dev
[debug] Proxy map: {}
youtube-dl is up-to-date (2021.12.17)
[generic] index_12: Requesting header
WARNING: Could not send HEAD request to https://vod2.spwn.jp/spwn-vod2/22031901-jphololive3rdfes/grp1/cam1_v1/index_12.m3u8: HTTP Error 403: Forbidden
[generic] index_12: Downloading webpage
ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 634, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 2288, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default

**Comment by OscarTAG** [comment]
are the cookies wrong? I used the Netscape one this time🤔

**Comment by OscarTAG** [comment]
Now Windows is telling me that "This app can't run on your PC." 🤔 
maybe i'll try reinstalling it

**Comment by OscarTAG** [comment]
C:\Users\User\Desktop\VTUBERS\ホロライブ\YouTube Video Downloader>youtube-dl.exe -vU
Access is denied.

**Comment by OscarTAG** [comment]
switched to yt-dlp.exe, now usable, still getting 403 error.

**Comment by pukkandan** [comment]
Are you able to open that URL in a browser?

**Comment by OscarTAG** [comment]
the .m3u8?

**Comment by pukkandan** [comment]
yes

**Comment by OscarTAG** [comment]
that leads to a download and when you open it with VLC it's a video with nothing in it.

**Comment by pukkandan** [comment]
Clicking on https://vod2.spwn.jp/spwn-vod2/22031901-jphololive3rdfes/grp1/cam1_v1/index_12.m3u8 leads you to a download!?

**Comment by pukkandan** [comment]
Your cookies may not have the relevant keys, or some headers may be needed to access it

Nothing we can do to help

**Comment by OscarTAG** [comment]
what do you mean? are the cookies wrong, or is the link wrong?

**Comment by OscarTAG** [comment]
solved and downloading.
there were many "vod2" links and "vod" links, and the latter one worked, I guess they just use different cookies. :)
