### ISSUE TITLE
(not a bug of yt-dlp) how to explain mp4 video/audio hard to download?

### ISSUE THREAD

**Issue by joshatt** [yt-dlp/yt-dlp#3485]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

Recently I find mp4 video/audio file ( NOT stream format that does not need merging ) hard to download - more and more downloading show error. I'm using a GUI that uses yt-dlp as engine. The log did not tell much detail of the error. I guess it's not a bug of yt-dlp, since I also try other download methods like online transfer or other third party website that downloads it for me, all showing error. But if I download M4V directly, it's ok.
I often try to download mp4 720p format, if I see download error, I try mp4 480p, which downloads ok but at the end it says "fail to merge audio". Then I'll try download 720p webm, which usually works fine.
All and all, I use the same proxy.
So, could anybody please explain this?

**Comment by pukkandan** [comment]
We can't read your mind or see your computer screen. We don't know what command you ran, what error you got or even what you are downloading... Show verbose logs!
