### ISSUE TITLE
[ArteTV] The video download no longer works as the site seems to have updated their video streaming format, please help!!

### ISSUE THREAD

**Issue by NiesmialyGosc** [yt-dlp/yt-dlp#3502]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.04.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

France

### Description

```shell
C:\Users\DELL\video\TEST2>yt-dlp --list-formats https://www.arte.tv/fr/videos/060173-000-A/le-harem-du-pharaon-soleil/
[ArteTV] 060173-000-A: Downloading JSON metadata
ERROR: [ArteTV] 060173-000-A: Unable to download JSON metadata: HTTP Error 500: Internal Server Error (caused by <HTTPError 500: 'Internal Server Error'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

C:\Users\DELL\video\TEST2>
```

### Verbose log

```shell
C:\Users\DELL\video\TEST2>yt-dlp -v https://www.arte.tv/fr/videos/060173-000-A/le-harem-du-pharaon-soleil/
[debug] Command-line config: ['-v', 'https://www.arte.tv/fr/videos/060173-000-A/le-harem-du-pharaon-soleil/']
[debug] Encodings: locale cp936, fs utf-8, out utf-8, err utf-8, pref cp936
[debug] yt-dlp version 2022.04.08 [7884ade] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.18363-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg N-89508-g1f1207145a, ffprobe N-89508-g1f1207145a
[debug] Optional libraries: brotli, certifi, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {'http': 'http://192.168.3.26:8080', 'https': 'https://192.168.3.26:8080', 'ftp': 'ftp://192.168.3.26:8080'}
[debug] [ArteTV] Extracting URL: https://www.arte.tv/fr/videos/060173-000-A/le-harem-du-pharaon-soleil/
[ArteTV] 060173-000-A: Downloading JSON metadata
ERROR: [ArteTV] 060173-000-A: Unable to download JSON metadata: HTTP Error 500: Internal Server Error (caused by <HTTPError 500: 'Internal Server Error'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 641, in extract
  File "yt_dlp\extractor\arte.py", line 57, in _real_extract
  File "yt_dlp\extractor\common.py", line 1029, in _download_json
  File "yt_dlp\extractor\common.py", line 1008, in _download_json_handle
  File "yt_dlp\extractor\common.py", line 800, in _download_webpage_handle
  File "yt_dlp\extractor\common.py", line 785, in _request_webpage

  File "yt_dlp\extractor\common.py", line 767, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 3601, in urlopen
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 500: Internal Server Error


C:\Users\DELL\video\TEST2>
```

**Comment by fstirlitz** [comment]
> please help!!

You know how counterproductive it is to write such things, do you?

Anyway, #3302 seems to extract it fine.

**Comment by StephaneAscoet** [comment]
What does this sentence mean ? However(and note that I’m a computer scientist), I read the content of the linked Webpage and didn’t understand anything except that there is two ways of fetching Arte videos and that the first one didn’t worked some times ago, and should be back now. However, if I lost hours trying to understand all of this, it’s because it’s not the case for me, even after having installed « 2022.04.08-1 ». So what are we supposed to do to get it working in yt-dlp and youtube-dl ? I guess a huge lot of people in the world are confused with this problem, why isn’t there a real Webpage with currents main issues and their fixing status, readable by regular brains instead of this awfully unfriendly Github witch is only usable by developers and theses abstruse debates understandable by themselves only too.

**Comment by jlemonde** [comment]
I get the almost same issue, using Ubuntu 22.04 LTS and yt-dlp version 2022.04.08 (which is the latest):

```
$ yt-dlp https://www.arte.tv/fr/videos/050724-001-A/l-histoire-de-l-electricite-1-3/ 
[ArteTV] 050724-001-A: Downloading JSON metadata
ERROR: [ArteTV] 050724-001-A: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

**Comment by andreygursky** [comment]
@jlemonde, it's a known issue. One possible solution has been already mentioned here: https://github.com/yt-dlp/yt-dlp/issues/3502#issuecomment-1104770251.
