### ISSUE TITLE
videos of particular duration

### ISSUE THREAD

**Issue by ROSH0518** [yt-dlp/yt-dlp#3505]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

can we download videos of  whose duration is  less than some predefined time duration?

**Comment by ROSH0518** [comment]
@pukkandan This --match-filter " duration >=?60"  works in terminal, but I am not able to use it in python script and can't find any documentation of how to use it.

**Comment by Lesmiscore** [comment]
```
'match_filter': match_filter_func("duration >=?60")
```

**Comment by pukkandan** [comment]
```python
import yt_dlp

URLS = ['https://www.youtube.com/watch?v=BaW_jenozKc']

def longer_than_a_minute(info, *, incomplete):
    """Download only videos longer than a minute (or with unknown duration)"""
    duration = info.get('duration')
    if duration and duration < 60:
        return 'The video is too short'

ydl_opts = {
    'match_filter': longer_than_a_minute,
}

with yt_dlp.YoutubeDL(ydl_opts) as ydl:
    error_code = ydl.download(URLS)
```

OR

```python
import yt_dlp

URLS = ['https://www.youtube.com/watch?v=BaW_jenozKc']

ydl_opts = {
    'match_filter': yt_dlp.utils.match_filter_func('duration >=?60'),
}

with yt_dlp.YoutubeDL(ydl_opts) as ydl:
    error_code = ydl.download(URLS)
```
