### ISSUE TITLE
AttributeError: module 'importlib._bootstrap_external' has no attribute '_w_long'

### ISSUE THREAD

**Issue by AtomicNess123** [yt-dlp/yt-dlp#3506]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.04.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

I install the last version using `python3 -m pip install -U yt-dlp `.
I do a simple:  `yt-dlp BaW_jenozKc  ` 
And get this error:

`
AttributeError: module 'importlib._bootstrap_external' has no attribute '_w_long'`

### Verbose log

```shell
Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp", line 10, in <module>
    from importlib.metadata import distribution
  File "/Users/user/opt/anaconda3/lib/python3.7/importlib/__init__.py", line 51, in <module>
    _w_long = _bootstrap_external._w_long
AttributeError: module 'importlib._bootstrap_external' has no attribute '_w_long'
```

**Comment by pukkandan** [comment]
Looks like there is something wrong with your python install. Are you able to open python and import any third party package? What happens if you `import yt_dlp`?

**Comment by flashdagger** [comment]
Could be conflicting Python installations in $PATH environment variable. (https://stackoverflow.com/questions/46509441/module-importlib-bootstrap-has-no-attribute-w-long)
If you call `python3 -m pip` then try `python3 -m yt_dlp <url>`.

**Comment by AtomicNess123** [comment]
Thank you! 

> Could be conflicting Python installations in $PATH environment variable. (https://stackoverflow.com/questions/46509441/module-importlib-bootstrap-has-no-attribute-w-long) If you call `python3 -m pip` then try `python3 -m yt_dlp <url>`.

Thank you! Indeed, my default call to python is not python3. It worked well now.

**Comment by AtomicNess123** [comment]
Just one more question: I have been using youtube-dl until now. Shall I only change `youtube-dl` by `yl_dlp` in my scripts or the syntax has changed also?

**Comment by pukkandan** [comment]
It's mostly the same, but there are some changes. See https://github.com/yt-dlp/yt-dlp#differences-in-default-behavior

**Comment by AtomicNess123** [comment]
Thanks. I see that 

`-t, -l, --title, --literal       -o "%(title)s-%(id)s.%(ext)s"`

is deprecated. What shall we use instead? It's not clear. All my scripts contain one of these. Thanks!

**Comment by pukkandan** [comment]
> -f "best[height<=240]" --format mp4

This is wrong - even for youtube-dl.

But yes, this command will behave in yt-dlp exactly as it did in youtube-dl

**Comment by AtomicNess123** [comment]
Ok, thanks. But the rest of the code is I assume. Thanks!
