### ISSUE TITLE
[youtube] Failed to download m3u8 information: HTTP Error 503: Service Unavailable

### ISSUE THREAD

**Issue by TapasKumarKundu** [yt-dlp/yt-dlp#3508]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.04.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

san diego, USA

### Description

I verified that my yt-dlp is most up to date: 

$yt-dlp -U
Command 'yt-dlp' not found, but can be installed with:
sudo snap install yt-dlp
tkundu@tkundu-ThinkPad-L430:~$ /home/tkundu/.local/bin/yt-dlp -U
Latest version: 2022.04.08, Current version: 2022.04.08
yt-dlp is up to date (2022.04.08)

I am seeing below error : 
"Failed to download m3u8 information: HTTP Error 503: Service Unavailable"

### Verbose log

```shell
/home/tkundu/.local/bin/yt-dlp --cookies /home/tkundu/cookies.txt --match-filter 'is_live' --flat-playlist -g -f "(bestvideo[width>=1920]/bestvideo)+bestaudio[ext=m4a]/best" --verbose 'https://www.youtube.com/channel/xxxxxxxxxxxxxxxxxxxxxxx/live'
[debug] Command-line config: ['--cookies', '/home/tkundu/cookies.txt', '--match-filter', 'is_live', '--flat-playlist', '-g', '-f', '(bestvideo[width>=1920]/bestvideo)+bestaudio[ext=m4a]/best', '--verbose', 'https://www.youtube.com/channel/xxxxxxxxxxxxxxxxxxxxxxx/live']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.04.08 [7884ade65]
[debug] Python version 3.8.10 (CPython 64bit) - Linux-5.8.0-63-generic-x86_64-with-glibc2.32
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1, rtmpdump 2.4
[debug] Optional libraries: brotli, certifi, Cryptodome, secretstorage, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [youtube:tab] Extracting URL: https://www.youtube.com/channel/xxxxxxxxxxxxxxxxxxxxxxx/live
[youtube:tab] xxxxxxxxxxxxxxxxxxxxxxx: Downloading webpage
[debug] [youtube:tab] Final URL: https://www.youtube.com/channel/xxxxxxxxxxxxxxxxxxxxxxx/live
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=xxxxxxxxxxxxxxxxxxxxxxx
[youtube] xxxxxxxxxxxxxxxxxxxxxxx: Downloading webpage
[debug] [youtube] Extracted SAPISID cookie
[youtube] xxxxxxxxxxxxxxxxxxxxxxx: Downloading android player API JSON
[youtube] xxxxxxxxxxxxxxxxxxxxxxx: Downloading m3u8 information
WARNING: [youtube] Failed to download m3u8 information: HTTP Error 503: Service Unavailable
[youtube] xxxxxxxxxxxxxxxxxxxxxxx: Downloading m3u8 information
WARNING: [youtube] Failed to download m3u8 information: HTTP Error 503: Service Unavailable
ERROR: [youtube] xxxxxxxxxxxxxxxxxxxxxxx: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "/home/tkundu/.local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 1408, in wrapper
    return func(self, *args, **kwargs)
  File "/home/tkundu/.local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 1492, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/home/tkundu/.local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 1548, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/home/tkundu/.local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 2487, in process_video_result
    self.raise_no_formats(info_dict)
  File "/home/tkundu/.local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 981, in raise_no_formats
    raise ExtractorError(msg, video_id=info['id'], ie=info['extractor'],
yt_dlp.utils.ExtractorError: [youtube] xxxxxxxxxxxxxxxxxxxxxxx: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

```

**Comment by pukkandan** [comment]
Could possibly be your firewall. Otherwise, you need to give the actual URL so we can try to reproduce

**Comment by TapasKumarKundu** [comment]
> Could possibly be your firewall. Otherwise, you need to give the actual URL so we can try to reproduce

https://www.youtube.com/channel/UCof_LNFpv3TiNR0d4SEE2ew/live

**Comment by TapasKumarKundu** [comment]
It is definitely not firewall. It was working fine for last few months. It stopped working today only !!

**Comment by TapasKumarKundu** [comment]
> Cant reproduce.
> 
> ```
> ❯ yt-dlp.exe --ignore-config -v https://www.youtube.com/channel/UCof_LNFpv3TiNR0d4SEE2ew/live --flat-playlist -g -f "(bestvideo[width>=1920]/bestvideo)+bestaudio[ext=m4a]/best"
> [debug] Command-line config: ['--ignore-config', '-v', 'https://www.youtube.com/channel/UCof_LNFpv3TiNR0d4SEE2ew/live', '--flat-playlist', '-g', '-f', '(bestvideo[width>=1920]/bestvideo)+bestaudio[ext=m4a]/best']
> [debug] Encodings: locale cp65001, fs utf-8, out utf-8, err utf-8, pref cp65001
> [debug] yt-dlp version 2022.04.08 [7884ade65]
> [debug] Python version 3.10.4 (CPython 64bit) - Windows-10-10.0.22000-SP0
> [debug] Checking exe version: ffmpeg -bsfs
> [debug] Checking exe version: ffprobe -bsfs
> [debug] exe versions: ffmpeg N-106550-g072101bd52-20220410 (setts,fdk), ffprobe N-106624-g391ce570c8-20220415, phantomjs 2.1.1
> [debug] Optional libraries: brotli, certifi, Cryptodome, mutagen, sqlite, websockets
> [debug] Proxy map: {}
> [debug] [youtube:tab] Extracting URL: https://www.youtube.com/channel/UCof_LNFpv3TiNR0d4SEE2ew/live
> [youtube:tab] UCof_LNFpv3TiNR0d4SEE2ew: Downloading webpage
> [debug] [youtube:tab] Final URL: https://www.youtube.com/channel/UCof_LNFpv3TiNR0d4SEE2ew/live
> [debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=wyP4vpMC7ao
> [youtube] wyP4vpMC7ao: Downloading webpage
> [youtube] wyP4vpMC7ao: Downloading android player API JSON
> [youtube] wyP4vpMC7ao: Downloading m3u8 information
> [youtube] wyP4vpMC7ao: Downloading m3u8 information
> [debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
> [debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
> [info] wyP4vpMC7ao: Downloading 1 format(s): 96
> https://manifest.googlevideo.com/api/manifest/hls_playlist/expire/1650583789/ei/jZRhYqWEG4SivwSslLu4Ag/ip/49.37.228.255/id/wyP4vpMC7ao.1/itag/96/source/yt_live_broadcast/requiressl/yes/ratebypass/yes/live/1/sgoap/gir%3Dyes%3Bitag%3D140/sgovp/gir%3Dyes%3Bitag%3D137/hls_chunk_host/rr4---sn-gwpa-jv36.googlevideo.com/playlist_duration/30/manifest_duration/30/vprv/1/playlist_type/DVR/initcwndbps/1510/mh/wQ/mm/44/mn/sn-gwpa-jv36/ms/lva/mv/m/mvi/4/pl/23/dover/11/pacing/0/keepalive/yes/fexp/24001373,24007246/mt/1650561877/sparams/expire,ei,ip,id,itag,source,requiressl,ratebypass,live,sgoap,sgovp,playlist_duration,manifest_duration,vprv,playlist_type/sig/AOq0QJ8wRAIgSW2nYvSea9Ipm0zTMGSJ-Plz2X5uvZw9jG3XjSOWTzECIGQUYh6_GVmhHOkKVgpD4HJDzRzfTNqcO5HTcEtbrbcx/lsparams/hls_chunk_host,initcwndbps,mh,mm,mn,ms,mv,mvi,pl/lsig/AG3C_xAwRgIhALDpVpVq5QUrqdnKBikO5oIaHNPaH8fXJRrfQnzMCXrBAiEA-J8AB9nmqhpGYQ-JCuKHfAac-DPBn2IfRVRfAv_3Tkg%3D/playlist/index.m3u8
> ```
> 
> Is this a one time thing, or is happening consistently? Can you check without cookies?

It happens randomly . If you try 20 times then you might be able to see it

**Comment by TapasKumarKundu** [comment]
It also happens without cookies

**Comment by pukkandan** [comment]
> It happens randomly . If you try 20 times then you might be able to see it

The question still remains. Did you try 20 times and it happened once (not reproducible - likely some temporary issue)? Or did you run it 100s of times over a span of time with approx 1 failure every 20 tries (reproducible - possibly some systemic issue)

PS: The channel is not currently live. So I cannot test your claim rn. I'll see if I can test when it becomes live again

**Comment by dirkf** [comment]
Also: https://github.com/ytdl-org/youtube-dl/issues/30880

**Comment by larryqiann** [comment]
I'm also having this issue. macOS/Homebrew, also on the same newest version. I am in Canada West.

This problem is definitely reproducible. It has occurred on every try today, across 3 live stream downloads. Restarting the download immediately works correctly. I'm wondering if there's any way to make it automatically retry when the error occurs.

**Comment by pukkandan** [comment]
> While It would be unwise to share the specific links, the live streams are rather popular and have many viewers

If you are unwilling share the link, there is nothing we can do. If anyone can share verbose logs with unredacted URL, this can be re-opened
