### ISSUE TITLE
can you create a symlink - current version

### ISSUE THREAD

**Issue by ds2k5** [yt-dlp/yt-dlp#3510]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

Hi,
is it possibile that you create a link like this:

https://github.com/yt-dlp/yt-dlp/releases/download/current/yt-dlp

so that can download the newst version by the same link 

thanks

**Comment by pukkandan** [comment]
https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp

**Comment by ds2k5** [comment]
thanks
