### ISSUE TITLE
Hotstar link is broken

### ISSUE THREAD

**Issue by jim-hopper011** [yt-dlp/yt-dlp#3517]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.04.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [x] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Description

ERROR: [hotstar] [1000054227] Unable to download JSON metadata: HTTP Error 475: Unknown (caused by  HTTPError 475: 'Unknown' )

### Verbose log

```shell
[debug] Command-line config: ['-vU', 'https://www.hotstar.com/1000054227']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8 (No ANSI), err utf-8 (No ANSI), pref UTF-8
[debug] yt-dlp version 2022.04.08 [7884ade65]
[debug] Python version 3.9.2 (CPython 64bit) - Linux-4.4.0-1101-aws-x86_64-with-glibc2.31
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg N-60236-gffb000fff8-static (setts), ffprobe N-60236-gffb000fff8-static
[debug] Optional libraries: brotli, certifi, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.04.08, Current version: 2022.04.08
yt-dlp is up to date (2022.04.08)
[debug] [hotstar] Extracting URL: https://www.hotstar.com/1000054227
[hotstar] 1000054227: Downloading JSON metadata
ERROR: [hotstar] 1000054227: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by ); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/app/.heroku/python/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 641, in extract
    ie_result = self._real_extract(url)
  File "/app/.heroku/python/lib/python3.9/site-packages/yt_dlp/extractor/hotstar.py", line 181, in _real_extract
    video_data = self._call_api(f'o/v1/{video_type}/detail', video_id)['body']['results']['item']
  File "/app/.heroku/python/lib/python3.9/site-packages/yt_dlp/extractor/hotstar.py", line 62, in _call_api
    return self._download_json('https://api.hotstar.com/' + path, video_id=video_id, query={
  File "/app/.heroku/python/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 1029, in _download_json
    res = self._download_json_handle(
  File "/app/.heroku/python/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 1008, in _download_json_handle
    res = self._download_webpage_handle(
  File "/app/.heroku/python/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 800, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query, expected_status=expected_status)
  File "/app/.heroku/python/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 785, in _request_webpage
    raise ExtractorError(errmsg, cause=err)

  File "/app/.heroku/python/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 767, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/app/.heroku/python/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 3601, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/app/.heroku/python/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/app/.heroku/python/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/app/.heroku/python/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/app/.heroku/python/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/app/.heroku/python/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```

**Comment by pukkandan** [comment]
> - [X] I've checked that all provided URLs are alive and playable in a browser

Check again from the same IP

**Comment by pukkandan** [comment]
Workaround: pass the full URL like `https://www.hotstar.com/in/tv/ek-veer-ki-ardaas-veera/316/ratan-returns-home/1000054227`

**Comment by jim-hopper011** [comment]
`u30191:~$ yt-dlp https://www.hotstar.com/in/tv/ek-veer-ki-ardaas-veera/316/ratan-returns-home/1000054227
[hotstar] 1000054227: Downloading JSON metadata
[hotstar] 1000054227: Downloading webpage
[hotstar] 1000054227: Downloading token
ERROR: [hotstar] 1000054227: Unable to download JSON metadata: HTTP Error 400: Bad Request (caused by ); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
u30191:~$`

**Comment by pukkandan** [comment]
Works for me. Are you sure you can access the URL in browser from same IP?

```
❯ yt-dlp -vU https://www.hotstar.com/in/tv/ek-veer-ki-ardaas-veera/316/ratan-returns-home/1000054227
[debug] Command-line config: ['--ignore-config', '-vU', 'https://www.hotstar.com/in/tv/ek-veer-ki-ardaas-veera/316/ratan-returns-home/1000054227']
[debug] Encodings: locale cp65001, fs utf-8, out utf-8, err utf-8, pref cp65001
[debug] yt-dlp version 2022.04.08 [7884ade65] (source)
[debug] Lazy loading extractors is disabled
[debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
[debug] Git HEAD: 6766c10b9
[debug] Python version 3.10.4 (CPython 64bit) - Windows-10-10.0.22000-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg N-106550-g072101bd52-20220410 (fdk,setts), ffprobe N-106624-g391ce570c8-20220415, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome, brotli (1.0.9), certifi (2021.10.08), mutagen, sqlite3, websockets (10.1)
[debug] Proxy map: {}
Latest version: 2022.04.08, Current version: 2022.04.08
yt-dlp is up to date (2022.04.08)
[debug] [hotstar] Extracting URL: https://www.hotstar.com/in/tv/ek-veer-ki-ardaas-veera/316/ratan-returns-home/1000054227
[hotstar] 1000054227: Downloading JSON metadata
[hotstar] 1000054227: Downloading webpage
[hotstar] 1000054227: Downloading token
[hotstar] 1000054227: Downloading JSON metadata
[hotstar] 1000054227: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 1000054227: Downloading 1 format(s): sdr-hls-2186
[debug] Invoking downloader on "https://staragvodweb1-vh.akamaihd.net/i/videos/plus/veera/681/1000054227_,16,54,106,180,400,800,1300,2000,3000,4500,_STAR.mp4.csmil/index_7_av.m3u8?null=0&hdntl=exp=1650692950~acl=%2fi%2fvideos%2fplus%2fveera%2f681%2f1000054227_,16,54,106,180,400,800,1300,2000,3000,4500,_STAR.mp4.csmil%2f*~data=hdntl~hmac=0b8ba7fa1422b82852d621b2c34490c998dbab185febd6701fd611e15abc89b0"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 218
[download] Destination: Ratan returns home [1000054227].mp4
[debug] File locking is not supported on this platform. Proceeding without locking
[download]   0.6% of ~329.45MiB at  2.50MiB/s ETA 02:53 (frag 1/218
ERROR: Interrupted by user
```

**Comment by jim-hopper011** [comment]
> Works for me. Are you sure you can access the URL in browser from same IP?
> 
> ```
> ❯ yt-dlp -vU https://www.hotstar.com/in/tv/ek-veer-ki-ardaas-veera/316/ratan-returns-home/1000054227
> [debug] Command-line config: ['--ignore-config', '-vU', 'https://www.hotstar.com/in/tv/ek-veer-ki-ardaas-veera/316/ratan-returns-home/1000054227']
> [debug] Encodings: locale cp65001, fs utf-8, out utf-8, err utf-8, pref cp65001
> [debug] yt-dlp version 2022.04.08 [7884ade65] (source)
> [debug] Lazy loading extractors is disabled
> [debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
> [debug] Git HEAD: 6766c10b9
> [debug] Python version 3.10.4 (CPython 64bit) - Windows-10-10.0.22000-SP0
> [debug] Checking exe version: ffmpeg -bsfs
> [debug] Checking exe version: ffprobe -bsfs
> [debug] exe versions: ffmpeg N-106550-g072101bd52-20220410 (fdk,setts), ffprobe N-106624-g391ce570c8-20220415, phantomjs 2.1.1
> [debug] Optional libraries: Cryptodome, brotli (1.0.9), certifi (2021.10.08), mutagen, sqlite3, websockets (10.1)
> [debug] Proxy map: {}
> Latest version: 2022.04.08, Current version: 2022.04.08
> yt-dlp is up to date (2022.04.08)
> [debug] [hotstar] Extracting URL: https://www.hotstar.com/in/tv/ek-veer-ki-ardaas-veera/316/ratan-returns-home/1000054227
> [hotstar] 1000054227: Downloading JSON metadata
> [hotstar] 1000054227: Downloading webpage
> [hotstar] 1000054227: Downloading token
> [hotstar] 1000054227: Downloading JSON metadata
> [hotstar] 1000054227: Downloading m3u8 information
> [debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
> [debug] Default format spec: bestvideo*+bestaudio/best
> [info] 1000054227: Downloading 1 format(s): sdr-hls-2186
> [debug] Invoking downloader on "https://staragvodweb1-vh.akamaihd.net/i/videos/plus/veera/681/1000054227_,16,54,106,180,400,800,1300,2000,3000,4500,_STAR.mp4.csmil/index_7_av.m3u8?null=0&hdntl=exp=1650692950~acl=%2fi%2fvideos%2fplus%2fveera%2f681%2f1000054227_,16,54,106,180,400,800,1300,2000,3000,4500,_STAR.mp4.csmil%2f*~data=hdntl~hmac=0b8ba7fa1422b82852d621b2c34490c998dbab185febd6701fd611e15abc89b0"
> [hlsnative] Downloading m3u8 manifest
> [hlsnative] Total fragments: 218
> [download] Destination: Ratan returns home [1000054227].mp4
> [debug] File locking is not supported on this platform. Proceeding without locking
> [download]   0.6% of ~329.45MiB at  2.50MiB/s ETA 02:53 (frag 1/218
> ERROR: Interrupted by user
> ```

I'm trying inside telegram

**Comment by jim-hopper011** [comment]
> Workaround: pass the full URL like `https://www.hotstar.com/in/tv/ek-veer-ki-ardaas-veera/316/ratan-returns-home/1000054227`

How can I get the full url like this?

**Comment by MLGMAG** [comment]
>ERROR: [hotstar] [1000054227] Unable to download JSON metadata: HTTP Error 475: Unknown (caused by HTTPError 475: 'Unknown' )

You will get 475 error if something is wrong with proxy (it is not Indian proxy, it is banned or something else...)

I have achieved the successful HLS stream download with help of curl.
