### ISSUE TITLE
Videos of particular title

### ISSUE THREAD

**Issue by ROSH0518** [yt-dlp/yt-dlp#3519]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

I have read the documentations, but can't find a solution to download videos with a particular keyword in the title. Is there a way to do this?

**Comment by dirkf** [comment]
Probably best to [read it again](https://github.com/yt-dlp/yt-dlp#user-content-video-selection), then. Hint: `--match-filters ...`.

**Comment by ROSH0518** [comment]
The solution mentioned is for using yt-dlp directly from terminal, but I was looking for documentation to embed it into a python script using the ydl_opts method. Is there a way to do that?

**Comment by pukkandan** [comment]
> but I was looking for documentation to embed it into a python script using the ydl_opts method. 

You should say that in the question... How are people replying supposed to know that!?
