### ISSUE TITLE
All4 support

### ISSUE THREAD

**Issue by fmchris10** [yt-dlp/yt-dlp#3520]
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.04.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

United Kingdom

### Example URLs

https://www.channel4.com/programmes/balls-of-steel/on-demand/39878-001

https://www.channel4.com/programmes/britains-greatest-hoaxer/on-demand/63202-001

https://www.channel4.com/programmes/trigger-happy-tv/on-demand/27669-001

### Description

All4 is a popular UK free streaming service, it's actually the UK's biggest free service (although you need an account). It's similar to ITV Hub and BBC iPlayer.

### Verbose log

```shell
I don't follow this
```

**Comment by fstirlitz** [comment]
> - [x] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge

Last I checked, Channel 4 had DRM. Anything changed in that respect?

**Comment by fstirlitz** [comment]
#3150
