### ISSUE TITLE
Add YAPPY

### ISSUE THREAD

**Issue by gohoski** [yt-dlp/yt-dlp#3522]
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.04.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Russian Federation

### Example URLs

- Single video: https://yappy.media/video/47fea6d8586f48d1a0cf96a7342aabd2
- Single video: https://yappy.media/video/ec14622a56f54990893215da3dc7e66e?utm_source=url&utm_medium=share&utm_campaign=video

### Description

`47fea6d8586f48d1a0cf96a7342aabd2` is the id from the URL.
To get the video (with watermark):

1. Create a `GET` request to `https://bl.ritm.media/route/47fea6d8586f48d1a0cf96a7342aabd2.m3u8?guids=fab9c340-09b8-4844-bc62-ae314715e374_368x640_1266859_avc1.42c01f_mp4a.40.5,9033cfae-52fd-440f-8275-95079c3eca54_480x848_1451802_avc1.4d401f_mp4a.40.5,2eb6cad8-a483-4363-a87d-1b2f1d6d95b9_720x1280_2794100_avc1.640029_mp4a.40.2,95c8e3c0-5b82-471c-8fb3-3bbac285973c_1072x1920_4041424_avc1.640029_mp4a.40.2&sign=UMwlS-iDXkF6RnNZuDKZYg&expire=1650724789` (I don't know where the GUIDs, the sign and the expire date are coming from)
2. Download desired video quality from the URL given in the response of the previous request. For 1072p, it's: `https://ant-cdn-1.uma.media/hls-vod/mYsJXS5sT-kr_I-Io3WgyA/1650652983/137/0x5000c500b6da1268/95c8e3c05b82471c8fb33bbac285973c.mp4/index.m3u8?i=1072x1920_4041`
3. Download the files listed in the request in the 2nd step. Example: `https://ant-cdn-1.uma.media/hls-vod/D-MBuA39IwZ94B6AYP6w9w/1650652982/87/0x5000c500b364a3fc/fab9c34009b84844bc62ae314715e374.mp4/[FILENAME].ts`
4. If needed, merge them.
5. Done!

_(Sorry for the bad explanation)_

### Verbose log

```shell
D:\Program Files (x86)\yt-dlp>yt-dlp -vU https://yappy.media/video/47fea6d8586f48d1a0cf96a7342aabd2
[debug] Command-line config: ['-vU', 'https://yappy.media/video/47fea6d8586f48d1a0cf96a7342aabd2']
[debug] Encodings: locale cp1251, fs utf-8, out utf-8, err utf-8, pref cp1251
[debug] yt-dlp version 2022.04.08 [7884ade] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.4.1-full_build-www.gyan.dev (setts), ffprobe 4.4.1-full_build-www.gyan.dev
[debug] Optional libraries: brotli, certifi, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.04.08, Current version: 2022.04.08
yt-dlp is up to date (2022.04.08)
[debug] [generic] Extracting URL: https://yappy.media/video/47fea6d8586f48d1a0cf96a7342aabd2
[generic] 47fea6d8586f48d1a0cf96a7342aabd2: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] 47fea6d8586f48d1a0cf96a7342aabd2: Downloading webpage
[generic] 47fea6d8586f48d1a0cf96a7342aabd2: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://yappy.media/video/47fea6d8586f48d1a0cf96a7342aabd2
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1408, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1478, in __extract_info
  File "yt_dlp\extractor\common.py", line 641, in extract
  File "yt_dlp\extractor\generic.py", line 4039, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://yappy.media/video/47fea6d8586f48d1a0cf96a7342aabd2
```

**Comment by Ashish0804** [comment]
>I don't know where the GUIDs, the sign and the expire date are coming from

This url can be obtained from the webpage.

Nice issue :)

**Comment by gohoski** [comment]
By the way, there is a way to get the video without the watermark, but that probably requires setting up root on my phone. Will send the instructions for that though when I will somehow install Wireshark or something on my phone or an Android emulator.
