### ISSUE TITLE
Requested format is not available. Use --list-formats for a list of available formats

### ISSUE THREAD

**Issue by CrDevUno** [yt-dlp/yt-dlp#3527]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.04.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

While using Google Colab for search YouTube videos. I've created this [Google Colab sample](https://colab.research.google.com/drive/1f2CO5uqyJvEfJ_Zwz0gumtioLz2OeMtb?usp=sharing) that contains the code. 

The specific code is as follows: 

    # Set ydl options: 
    # Sources: 
    # https://stackoverflow.com/q/60489888/12511801
    # https://stackoverflow.com/a/49222737/12511801
    ydl_opts = {
        'format': 'bestvideo[ext=mp4]+bestaudio[ext=mp4]/mp4+best[height<=480]', 
        "quiet": True}

    # Use ydl for search videos: 
    with YoutubeDL(ydl_opts) as ydl: 
      try:
        # The error "Requested format is not available. Use --list-formats for a list of available formats" raises here: 
        info = ydl.extract_info(f"ytsearch{amount}:{searchTerm.strip()}", download=False, ie_key="YoutubeSearch")

    [the rest of the code goes here]

While searching with _using this specific term_: **_batman arkham knight all cutscenes_**, I got the following error: 

> ERROR: [youtube] Za3zaBo_n7o: Requested format is not available. Use --list-formats for a list of available formats

Oddly enough, this error does not appear with other search terms, like:

- Team APS
- The house of the dead remake all animations
- Ancient Egypt flute ceremonial music
- Yugioh master duel meme
- and so on...

----

_`yt-dlp`_ version information is as follows:

```
Name: yt-dlp
Version: 2022.4.8
Summary: A youtube-dl fork with additional features and patches
Home-page: https://github.com/yt-dlp/yt-dlp
Author: None
Author-email: None
License: UNKNOWN
Location: /usr/local/lib/python3.7/dist-packages
Requires: certifi, pycryptodomex, websockets, mutagen, brotli
Required-by: 
```

### Verbose log

```shell
This is the complete stacktrace: 

> Searching 4 videos that matches with (batman arkham knight all cutscenes)...
> Please wait...
> ERROR: [youtube] Za3zaBo_n7o: Requested format is not available. Use --list-formats for a list of available formats
> Error at searching videos. See details bellow
> ERROR: [youtube] Za3zaBo_n7o: Requested format is not available. Use --list-formats for a list of available formats
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.7/dist-packages/yt_dlp/YoutubeDL.py", line 1408, in wrapper
>     return func(self, *args, **kwargs)
>   File "/usr/local/lib/python3.7/dist-packages/yt_dlp/YoutubeDL.py", line 1492, in __extract_info
>     return self.process_ie_result(ie_result, download, extra_info)
>   File "/usr/local/lib/python3.7/dist-packages/yt_dlp/YoutubeDL.py", line 1548, in process_ie_result
>     ie_result = self.process_video_result(ie_result, download=download)
>   File "/usr/local/lib/python3.7/dist-packages/yt_dlp/YoutubeDL.py", line 2632, in process_video_result
>     expected=True, video_id=info_dict['id'], ie=info_dict['extractor'])
> yt_dlp.utils.ExtractorError: [youtube] Za3zaBo_n7o: Requested format is not available. Use --list-formats for a list of available formats
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "<ipython-input-3-a5fba6dd3487>", line 88, in searchVideos
>     info = ydl.extract_info(f"ytsearch{amount}:{searchTerm.strip()}", download=False, ie_key="YoutubeSearch")
>   File "/usr/local/lib/python3.7/dist-packages/yt_dlp/YoutubeDL.py", line 1399, in extract_info
>     return self.__extract_info(url, self.get_info_extractor(ie_key), download, extra_info, process)
>   File "/usr/local/lib/python3.7/dist-packages/yt_dlp/YoutubeDL.py", line 1408, in wrapper
>     return func(self, *args, **kwargs)
>   File "/usr/local/lib/python3.7/dist-packages/yt_dlp/YoutubeDL.py", line 1492, in __extract_info
>     return self.process_ie_result(ie_result, download, extra_info)
>   File "/usr/local/lib/python3.7/dist-packages/yt_dlp/YoutubeDL.py", line 1613, in process_ie_result
>     return self.__process_playlist(ie_result, download)
>   File "/usr/local/lib/python3.7/dist-packages/yt_dlp/YoutubeDL.py", line 1812, in __process_playlist
>     entry_result = self.__process_iterable_entry(entry, download, extra)
>   File "/usr/local/lib/python3.7/dist-packages/yt_dlp/YoutubeDL.py", line 1408, in wrapper
>     return func(self, *args, **kwargs)
>   File "/usr/local/lib/python3.7/dist-packages/yt_dlp/YoutubeDL.py", line 1835, in __process_iterable_entry
>     entry, download=download, extra_info=extra_info)
>   File "/usr/local/lib/python3.7/dist-packages/yt_dlp/YoutubeDL.py", line 1570, in process_ie_result
>     extra_info=extra_info)
>   File "/usr/local/lib/python3.7/dist-packages/yt_dlp/YoutubeDL.py", line 1399, in extract_info
>     return self.__extract_info(url, self.get_info_extractor(ie_key), download, extra_info, process)
>   File "/usr/local/lib/python3.7/dist-packages/yt_dlp/YoutubeDL.py", line 1426, in wrapper
>     self.report_error(str(e), e.format_traceback())
>   File "/usr/local/lib/python3.7/dist-packages/yt_dlp/YoutubeDL.py", line 950, in report_error
>     self.trouble(f'{self._format_err("ERROR:", self.Styles.ERROR)} {message}', *args, **kwargs)
>   File "/usr/local/lib/python3.7/dist-packages/yt_dlp/YoutubeDL.py", line 895, in trouble
>     raise DownloadError(message, exc_info)
> yt_dlp.utils.DownloadError: ERROR: [youtube] Za3zaBo_n7o: Requested format is not available. Use --list-formats for a list of available formats
```

**Comment by pukkandan** [comment]
> Use --list-formats for a list of available formats

Maybe try what the error message asks you to do!

Your format string is wrong. Neither `bestaudio[ext=mp4]` nor `best[height<=480]` exists. I think you meant `bv[ext=mp4]+ba[ext=m4a]/b`, but only you know what your actual requirement is

**Comment by CrDevUno** [comment]
Sorry, but, this does not solve the error. I changed the options as you write in your answer, but, the video is returned without audio and in lower quality; while with my current options - `bestvideo[ext=mp4]+bestaudio[ext=mp4]/mp4+best[height<=480]` the returned videos has audio and higher video quality. 

Can you test the Google Colab sample I provided in my post (*or built one*) in order to check youself the error?

**Comment by pukkandan** [comment]
> bestvideo[ext=mp4]+bestaudio[ext=mp4]/mp4+best[height<=480] the returned videos has audio and higher video quality.

Depending on the formats it has available, it may work for some videos. But in general, this is wrong, hence why it does not return anything for the video in OP

**Comment by pukkandan** [comment]
> I changed the options as you write in your answer, but, the video is returned without audio and in lower quality; while with my current options

I was not asking you to use that string as-is. I do not know what format you want to elect. You will have to decide that for yourself
