### ISSUE TITLE
match_filter_func takes multiple arguements is there a way to apply AND condition for both the arguements?

### ISSUE THREAD

**Issue by jaxxstar** [yt-dlp/yt-dlp#3530]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

match_filter_func takes multiple arguments but applies OR condition, is there a way to apply AND condition for both the arguments
>yt_dlp.utils.match_filter_func(['duration >=?60','title ~= (?i)cat'])
>Tamada Media does not pass filter (duration >=?60) | (title ~= (?i)cat), skipping ..

**Comment by pukkandan** [comment]
You can use `&`. Though, if you are using it from API, it's recommended to write your own filter function instead. Why translate your logic to this mini-language and then parse it back to a function
