### ISSUE TITLE
Would a website Mech+ be able to be downloadable if using brightcove.

### ISSUE THREAD

**Issue by Danker1990** [yt-dlp/yt-dlp#3533]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

A new website has recently opened in the UK called Mech+ which has the complete classic series of Robot Wars in HD for the first time however when trying all the tricks to attempt a download it claims it is unsupported and is using the Brightcove method of streaming so presume it could be downloadable. Is this possible?

If anyone wants to attempt a download or research I have left a link here:

https://www.mech-plus.com/player/24892/stream?assetType=episodes&playlist_id=6

https://www.mech-plus.com/details/25240?playlist_id=6

**Comment by pukkandan** [comment]
It appears to be DRM protected
