### ISSUE TITLE
How to stop live stream recording

### ISSUE THREAD

**Issue by vden89** [yt-dlp/yt-dlp#3535]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

I'm downloading the live stream. After completion, it is immediately removed. And the program keeps trying to download it. She doesn't stop. I have to force stop it. How to make the program stop itself?

**Comment by krichbanana** [comment]
AFAIK this is an issue with ffmpeg, as yt-dlp delegates the download of the HLS playlist to this program and ffmpeg has no way of knowing whether the stream has been interrupted temporarily or permanently.

You can use the experimental `--live-from-start` option to download directly with yt-dlp, although there is an currently outstanding issue where if a YouTube has hiccups then the download may end prematurely.

**Comment by pukkandan** [comment]
>  And the program keeps trying to download it. She doesn't stop.

It will stop after some time. Like kirchbanana said, it's waiting to make sure the video isn't just down temporarily

>  I have to force stop it. How to make the program stop itself?

I don't recommend force-stopping it, but you can sent SIGINT <kbd>Ctrl</kbd>+<kbd>C</kbd> for it. Unless `--hls-prefer-mpegts` is being used, make sure to press Ctrl+C **ONLY ONCE**. ffmpeg may take some time after the keypress to shut down - This is normal. Trying to interrupt it again could lead to a damaged download
