### ISSUE TITLE
how can I download multiple audio track in the same time.

### ISSUE THREAD

**Issue by lowprofileusername** [yt-dlp/yt-dlp#3540]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

I use --list-format and result as follow
```
[info] Available formats for index:
ID                      EXT RESOLUTION FPS │   TBR PROTO  │ VCODEC        VBR ACODEC     MORE INFO
──────────────────────────────────────────────────────────────────────────────────────────────────────
audio-AACL-128-Chinese  mp4 audio only     │       m3u8_n │ audio only        unknown    [zh] Chinese
audio-AACL-193-Japanese mp4 audio only     │       m3u8_n │ audio only        unknown    [ja] Japanese
758                     mp4 480x270     30 │  758k m3u8_n │ avc1.42c01e  758k video only
823                     mp4 480x270     30 │  823k m3u8_n │ avc1.42c01e  823k video only
1317                    mp4 640x360     30 │ 1317k m3u8_n │ avc1.4d401f 1317k video only
1382                    mp4 640x360     30 │ 1382k m3u8_n │ avc1.4d401f 1382k video only
2072                    mp4 960x540     30 │ 2072k m3u8_n │ avc1.4d401f 2072k video only
2137                    mp4 960x540     30 │ 2137k m3u8_n │ avc1.4d401f 2137k video only
3114                    mp4 1280x720    30 │ 3114k m3u8_n │ avc1.640028 3114k video only
3179                    mp4 1280x720    30 │ 3179k m3u8_n │ avc1.640028 3179k video only
6196                    mp4 1920x1080   30 │ 6196k m3u8_n │ avc1.640028 6196k video only
6260                    mp4 1920x1080   30 │ 6260k m3u8_n │ avc1.640028 6260k video only
```
I knew I Can select specfic track by use  -f 'bestvideo+bestaudio[language=zh]. what if I want to download both tracks. what should I do?
Thank you.

### Verbose log

```shell
No log
```

**Comment by pukkandan** [comment]
`--audio-multistreams -f bestvideo+all[vcodec=none]`

**Comment by lowprofileusername** [comment]
Thank you.

**Comment by lowprofileusername** [comment]
so I used  --audio-multistreams -f bestvideo+all[vcodec=none] output as below

info] index: Downloading 2 format(s): 6260+audio-AACL-193-Japanese, 6260+audio-AACL-128-Chinese
[download] index [index].f6260.mp4 has already been downloaded
[download] 100% of 1017.12MiB
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 725
[download] Destination: index [index].faudio-AACL-193-Japanese.mp4
[download] 100% of 43.01MiB in 11:29
[Merger] Merging formats into "index [index].mp4"
Deleting original file index [index].f6260.mp4 (pass -k to keep)
Deleting original file index [index].faudio-AACL-193-Japanese.mp4 (pass -k to keep)
[download] index [index].mp4 has already been downloaded

even though that it shjows started downloading two audios however when it comes to merege and download. only single audio contain and download by the tool. 
is it becaused that the problem of mp4 container ?
Thank you

**Comment by pukkandan** [comment]
Just apply a filter that selects the correct audio, or directly give the format_id. Eg: `--audio-multistreams -f bv+ba[language=zh]+ba[language=ja]`

**Comment by lowprofileusername** [comment]
Thankyou for your kindly help.  so I tried --audio-multistreams -f bv+ba[language=zh]+ba[language=ja]
result as below
[generic] index: Requesting header
[generic] index: Downloading m3u8 information
[info] index: Downloading 1 format(s): 6445+audio-AACL-128-Chinese+audio-AACL-128-Japanese+audio-AACL-128-Japanese+audio-AACL-128-Chinese
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 242

and finally the output files contains 4 audio trackers instead of 2.

and I tried  -f bv+ba[language=zh]+ba[language=ja]+mergeall[vcodec=none] without --audio-multistreams. only one audio track :/
[generic] index: Requesting header
[generic] index: Downloading m3u8 information
[info] index: Downloading 1 format(s): 6445+audio-AACL-128-Chinese

any suggestions?

**Comment by pukkandan** [comment]
Provide full verbose log

**Comment by lowprofileusername** [comment]
D:\Backup\Downloads\Documents\yt-dlp_win\yt-dlp>
D:\Backup\Downloads\Documents\yt-dlp_win\yt-dlp>yt-dlp.exe --proxy socks5://127.0.0.1:7890 --add-header "Referer":"https://hamivideo.hinet.net" "https://webvod-hamivideo.cdn.hinet.net/vod/hamivideo2/hamivideo-2251-2251104643_f_001/_/hd_6840-hls-ae-all-ma-6s/index.m3u8?url_type=&token=xxx&expires=xxx&content_id=xxx&product_id=xxx6&serial_no=xxx&auth_type=sn&auth_by=google_xxxx3&sales_plan_id=xx2&ts_id=&chsm=xxxx6a&auth_login_id=google_xxx3" --audio-multistreams -f bv+ba[language=zh]+ba[language=ja]+mergeall[vcodec=none] -o "12353231" -N 16 -R infinite --merge-output-format mkv
[generic] index: Requesting header
[generic] index: Downloading m3u8 information
[info] index: Downloading 1 format(s): 6445+audio-AACL-128-Chinese+audio-AACL-128-Japanese+audio-AACL-128-Japanese+audio-AACL-128-Chinese
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 242
[download] Destination: 12353231.f6445.mp4
WARNING: The download speed shown is only of one thread. This is a known issue and patches are welcome
[download]  16.2% of ~981.81MiB at 399.39KiB/s ETA 01:37 (frag 39/242)[download] Got server HTTP error: <urlopen error [WinError 10054] An existing connection was forcibly closed by the remote host。>. Retrying (attempt 1 of inf) ...
[download]  23.6% of ~1000.12MiB at  1.68MiB/s ETA 01:28 (frag 57/242)[download] Got server HTTP error: <urlopen error [WinError 10054] An existing connection was forcibly closed by the remote host。>. Retrying (attempt 1 of inf) ...
[download]  57.2% of ~1.01GiB at 183.64KiB/s ETA 00:49 (frag 139/242)[download] Got server HTTP error: <urlopen error [WinError 10054] An existing connection was forcibly closed by the remote host。>. Retrying (attempt 1 of inf) ...
[download]  58.0% of ~1022.53MiB at  3.96MiB/s ETA 00:48 (frag 140/242)[download] Got server HTTP error: <urlopen error [WinError 10054] An existing connection was forcibly closed by the remote host。>. Retrying (attempt 2 of inf) ...
[download]  67.4% of ~1.00GiB at  3.91MiB/s ETA 00:38 (frag 163/242)[download] Got server HTTP error: <urlopen error [WinError 10054] An existing connection was forcibly closed by the remote host。>. Retrying (attempt 1 of inf) ...
[download]  67.8% of ~1.00GiB at  1.53MiB/s ETA 00:38 (frag 164/242)[download] Got server HTTP error: <urlopen error [WinError 10054] An existing connection was forcibly closed by the remote host。>. Retrying (attempt 1 of inf) ...
[download] 100% of 1.03GiB in 02:00
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 242
[download] Destination: 12353231.faudio-AACL-128-Chinese.mp4
WARNING: The download speed shown is only of one thread. This is a known issue and patches are welcome
[download]  14.9% of ~34.09MiB at  2.23MiB/s ETA 00:19 (frag 36/242)[download] Got server HTTP error: <urlopen error [WinError 10054] An existing connection was forcibly closed by the remote host。>. Retrying (attempt 1 of inf) ...
[download]  22.7% of ~34.09MiB at  1.48MiB/s ETA 00:16 (frag 54/242)[download] Got server HTTP error: <urlopen error [WinError 10054] An existing connection was forcibly closed by the remote host。>. Retrying (attempt 1 of inf) ...
[download]  57.9% of ~34.08MiB at 216.12KiB/s ETA 00:09 (frag 140/242)[download] Got server HTTP error: <urlopen error [WinError 10054] An existing connection was forcibly closed by the remote host。>. Retrying (attempt 1 of inf) ...
[download]  67.9% of ~34.08MiB at  5.15MiB/s ETA 00:06 (frag 164/242)[download] Got server HTTP error: <urlopen error [WinError 10054] An existing connection was forcibly closed by the remote host。>. Retrying (attempt 1 of inf) ...
[download]  72.9% of ~34.08MiB at 374.79KiB/s ETA 00:05 (frag 176/242)[download] Got server HTTP error: <urlopen error [WinError 10054] An existing connection was forcibly closed by the remote host。>. Retrying (attempt 1 of inf) ...
[download]  74.8% of ~34.08MiB at 669.13KiB/s ETA 00:05 (frag 181/242)[download] Got server HTTP error: <urlopen error [WinError 10054] An existing connection was forcibly closed by the remote host。>. Retrying (attempt 1 of inf) ...
[download] 100% of 34.06MiB in 00:23
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 242
[download] Destination: 12353231.faudio-AACL-128-Japanese.mp4
WARNING: The download speed shown is only of one thread. This is a known issue and patches are welcome
[download]  15.3% of ~34.09MiB at 76.91KiB/s ETA 00:22 (frag 37/242)[download] Got server HTTP error: <urlopen error [WinError 10054] An existing connection was forcibly closed by the remote host。>. Retrying (attempt 1 of inf) ...
[download]  40.9% of ~34.04MiB at  2.16MiB/s ETA 00:14 (frag 99/242)[download] Got server HTTP error: <urlopen error [WinError 10054] An existing connection was forcibly closed by the remote host。>. Retrying (attempt 1 of inf) ...
[download]  78.7% of ~34.04MiB at 39.15MiB/s ETA 00:05 (frag 190/242)[download] Got server HTTP error: <urlopen error [WinError 10054] An existing connection was forcibly closed by the remote host。>. Retrying (attempt 1 of inf) ...
[download]  99.2% of ~34.05MiB at 977.28KiB/s ETA 00:00 (frag 240/242)[download] Got server HTTP error: <urlopen error [WinError 10054] An existing connection was forcibly closed by the remote host。>. Retrying (attempt 1 of inf) ...
[download] Got server HTTP error: <urlopen error [WinError 10054] An existing connection was forcibly closed by the remote host。>. Retrying (attempt 1 of inf) ...
[download] 100% of 34.03MiB in 00:26
[download] 12353231.faudio-AACL-128-Japanese.mp4 has already been downloaded
[download] 100% of 34.03MiB
[download] 12353231.faudio-AACL-128-Chinese.mp4 has already been downloaded
[download] 100% of 34.06MiB
[Merger] Merging formats into "12353231.mkv"
Deleting original file 12353231.faudio-AACL-128-Japanese.mp4 (pass -k to keep)
Deleting original file 12353231.faudio-AACL-128-Chinese.mp4 (pass -k to keep)
Deleting original file 12353231.f6445.mp4 (pass -k to keep)

here is how it looks like 
<a href="https://ibb.co/7K6d908"><img src="https://i.ibb.co/BBS51Yd/xxx012238.png" alt="xxx012238" border="0"></a>



yt-dlp.exe --proxy socks5://127.0.0.1:7890 -vU --add-header "Referer":"https://hamivideo.hinet.net" "https://webvod-hamivideo.cdn.hinet.net/vod/hamivideo2/hamivideo-2251-2251104643_f_001/_/hd_6840-hls-ae-all-ma-6s/index.m3u8?url_type=&token=xxx&expires=xxx&content_id=xxx&product_id=xxx6&serial_no=xxx&auth_type=sn&auth_by=google_xxxx3&sales_plan_id=xx2&ts_id=&chsm=xxxx6a&auth_login_id=google_xxx3" --audio-multistreams -f bv+ba[language=zh]+ba[language=ja]+mergeall[vcodec=none] -o "12353231" -N 16 -R infinite --merge-output-format mkv
[debug] Command-line config: ['--proxy', 'socks5://127.0.0.1:7890', '-vU', '--add-header', 'Referer:https://hamivideo.hinet.net', 'https://webvod-hamivideo.cdn.hinet.net/vod/hamivideo2/hamivideo-2251-2251104643_f_001/_/hd_6840-hls-ae-all-ma-6s/index.m3u8?url_type=&token=xxx&expires=xxx&content_id=xxx&product_id=xxx6&serial_no=xxx&auth_type=sn&auth_by=google_xxxx3&sales_plan_id=xx2&ts_id=&chsm=xxxx6a&auth_login_id=google_xxx3', '--audio-multistreams', '-f', 'bv+ba[language=zh]+ba[language=ja]+mergeall[vcodec=none]', '-o', '12353231', '-N', '16', '-R', 'infinite', '--merge-output-format', 'mkv']
[debug] Encodings: locale cp936, fs utf-8, out utf-8, err utf-8, pref cp936
[debug] yt-dlp version 2022.04.08 [7884ade] (win_dir)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 2022-04-14-git-ea84eb2db1-essentials_build-www.gyan.dev (setts), ffprobe 2022-04-14-git-ea84eb2db1-essentials_build-www.gyan.dev
[debug] Optional libraries: brotli, certifi, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {'http': 'socks5://127.0.0.1:7890', 'https': 'socks5://127.0.0.1:7890'}
Latest version: 2022.04.08, Current version: 2022.04.08
yt-dlp is up to date (2022.04.08)
[debug] [generic] Extracting URL: https://webvod-hamivideo.cdn.hinet.net/vod/hamivideo2/hamivideo-2251-2251104643_f_001/_/hd_6840-hls-ae-all-ma-6s/index.m3u8?url_type=&token=xxx&expires=xxx&content_id=xxx&product_id=xxx6&serial_no=xxx&auth_type=sn&auth_by=google_xxxx3&sales_plan_id=xx2&ts_id=&chsm=xxxx6a&auth_login_id=google_xxx3
[generic] index: Requesting header
[debug] Identified a direct video link
[generic] index: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[info] index: Downloading 1 format(s): 6445+audio-AACL-128-Chinese+audio-AACL-128-Japanese+audio-AACL-128-Japanese+audio-AACL-128-Chinese
[download] 12353231.mkv has already been downloaded

**Comment by lowprofileusername** [comment]
let me use this video as sample. it contains multiple audios and can be public reach
yt-dlp --list-formats https://www.zdf.de/serien/greyzone/zugriff-100.html
[ZDF] zugriff-100: Downloading webpage
[ZDF] zugriff-100: Downloading JSON content
[ZDF] zugriff-100: Downloading JSON metadata
[ZDF] 181004_2015_sendung_gzo: Downloading m3u8 information
[ZDF] 181004_2015_sendung_gzo: Downloading m3u8 information
[ZDF] 181004_2015_sendung_gzo: Downloading m3u8 information
[ZDF] 181004_2015_sendung_gzo: Downloading m3u8 information
[info] Available formats for 181004_2015_sendung_gzo:
ID                                      EXT RESOLUTION │   FILESIZE   TBR PROTO  │ VCODEC        VBR ACODEC     ABR MORE INFO
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
hls-aac-Originalton-0                   mp4 audio only │                  m3u8_n │ audio only        unknown        [dan] Originalton
hls-aac-TV_Ton-0                        mp4 audio only │                  m3u8_n │ audio only        unknown        [deu] TV Ton
hls-96-0                                mp4 audio only │ ~ 28.79MiB   96k m3u8_n │ audio only        mp4a.40.2  96k [dan] auto, ot
hls-aac-Originalton-1                   mp4 audio only │                  m3u8_n │ audio only        unknown        [dan] Originalton
hls-aac-TV_Ton-1                        mp4 audio only │                  m3u8_n │ audio only        unknown        [deu] TV Ton
hls-96-1                                mp4 audio only │ ~ 28.79MiB   96k m3u8_n │ audio only        mp4a.40.2  96k [deu] auto, main
hls-aac-Originalton-2                   mp4 audio only │                  m3u8_n │ audio only        unknown        [dan] Originalton
hls-aac-TV_Ton-2                        mp4 audio only │                  m3u8_n │ audio only        unknown        [deu] TV Ton
hls-96-2                                mp4 audio only │ ~ 28.79MiB   96k m3u8_n │ audio only        mp4a.40.2  96k [dan] med, ot
hls-aac-Originalton-3                   mp4 audio only │                  m3u8_n │ audio only        unknown        [dan] Originalton
hls-aac-TV_Ton-3                        mp4 audio only │                  m3u8_n │ audio only        unknown        [deu] TV Ton
hls-96-3                                mp4 audio only │ ~ 28.79MiB   96k m3u8_n │ audio only        mp4a.40.2  96k [deu] med, main
hls-374-0                               mp4 480x272    │ ~112.17MiB  374k m3u8_n │ avc1.77.30   374k video only     [dan] auto, ot
hls-374-1                               mp4 480x272    │ ~112.17MiB  374k m3u8_n │ avc1.77.30   374k video only     [deu] auto, main
hls-374-2                               mp4 480x272    │ ~112.17MiB  374k m3u8_n │ avc1.77.30   374k video only     [dan] med, ot
hls-374-3                               mp4 480x272    │ ~112.17MiB  374k m3u8_n │ avc1.77.30   374k video only     [deu] med, main
hls-603-0                               mp4 640x360    │ ~180.86MiB  603k m3u8_n │ avc1.77.30   603k video only     [dan] auto, ot
hls-603-1                               mp4 640x360    │ ~180.86MiB  603k m3u8_n │ avc1.77.30   603k video only     [dan] auto, ot
hls-603-2                               mp4 640x360    │ ~180.86MiB  603k m3u8_n │ avc1.77.30   603k video only     [deu] auto, main
hls-603-3                               mp4 640x360    │ ~180.86MiB  603k m3u8_n │ avc1.77.30   603k video only     [deu] auto, main
hls-603-4                               mp4 640x360    │ ~180.86MiB  603k m3u8_n │ avc1.77.30   603k video only     [dan] med, ot
hls-603-5                               mp4 640x360    │ ~180.86MiB  603k m3u8_n │ avc1.77.30   603k video only     [dan] med, ot
hls-603-6                               mp4 640x360    │ ~180.86MiB  603k m3u8_n │ avc1.77.30   603k video only     [deu] med, main
hls-603-7                               mp4 640x360    │ ~180.86MiB  603k m3u8_n │ avc1.77.30   603k video only     [deu] med, main
hls-1155-0                              mp4 852x480    │ ~346.42MiB 1155k m3u8_n │ avc1.77.30  1155k video only     [dan] auto, ot
hls-1155-1                              mp4 852x480    │ ~346.42MiB 1155k m3u8_n │ avc1.77.30  1155k video only     [deu] auto, main
hls-1155-2                              mp4 852x480    │ ~346.42MiB 1155k m3u8_n │ avc1.77.30  1155k video only     [dan] med, ot
hls-1155-3                              mp4 852x480    │ ~346.42MiB 1155k m3u8_n │ avc1.77.30  1155k video only     [deu] med, main
hls-1796-0                              mp4 1024x576   │ ~538.67MiB 1796k m3u8_n │ avc1.77.30  1796k video only     [dan] auto, ot
hls-1796-1                              mp4 1024x576   │ ~538.67MiB 1796k m3u8_n │ avc1.77.30  1796k video only     [deu] auto, main
hls-2577-0                              mp4 1280x720   │ ~772.91MiB 2577k m3u8_n │ avc1.640028 2577k video only     [dan] auto, ot
hls-2577-1                              mp4 1280x720   │ ~772.91MiB 2577k m3u8_n │ avc1.640028 2577k video only     [deu] auto, main
http-h264_aac_mp4_http_na_na-low-0      mp4 unknown    │                  https  │ h264              aac            [dan] low, ot
http-h264_aac_mp4_http_na_na-low-1      mp4 unknown    │                  https  │ h264              aac            [deu] low, main
http-h264_aac_mp4_http_na_na-high-0     mp4 unknown    │                  https  │ h264              aac            [dan] high, ot
http-h264_aac_mp4_http_na_na-high-1     mp4 unknown    │                  https  │ h264              aac            [dan] high, ot
http-h264_aac_mp4_http_na_na-high-2     mp4 unknown    │                  https  │ h264              aac            [deu] high, main
http-h264_aac_mp4_http_na_na-high-3     mp4 unknown    │                  https  │ h264              aac            [deu] high, main
http-h264_aac_mp4_http_na_na-veryhigh-0 mp4 unknown    │                  https  │ h264              aac            [dan] veryhigh, ot
http-h264_aac_mp4_http_na_na-veryhigh-1 mp4 unknown    │                  https  │ h264              aac            [dan] veryhigh, ot
http-h264_aac_mp4_http_na_na-veryhigh-2 mp4 unknown    │                  https  │ h264              aac            [deu] veryhigh, main
http-h264_aac_mp4_http_na_na-veryhigh-3 mp4 unknown    │                  https  │ h264              aac            [deu] veryhigh, main


eg I only want to download two of audio from the video. so I perform.

D:\Backup\Downloads\Documents\yt-dlp_win\yt-dlp>yt-dlp.exe -vU https://www.zdf.de/serien/greyzone/zugriff-100.html --audio-multistreams -f bv+hls-aac-Originalton-0+hls-aac-TV_Ton-0+mergeall[vcodec=none] --merge-output-format mkv
[debug] Command-line config: ['-vU', 'https://www.zdf.de/serien/greyzone/zugriff-100.html', '--audio-multistreams', '-f', 'bv+hls-aac-Originalton-0+hls-aac-TV_Ton-0+mergeall[vcodec=none]', '--merge-output-format', 'mkv']
[debug] Encodings: locale cp936, fs utf-8, out utf-8, err utf-8, pref cp936
[debug] yt-dlp version 2022.04.08 [7884ade] (win_dir)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 2022-04-14-git-ea84eb2db1-essentials_build-www.gyan.dev (setts), ffprobe 2022-04-14-git-ea84eb2db1-essentials_build-www.gyan.dev
[debug] Optional libraries: brotli, certifi, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {'http': 'http://127.0.0.1:7890', 'https': 'https://127.0.0.1:7890', 'ftp': 'ftp://127.0.0.1:7890'}
Latest version: 2022.04.08, Current version: 2022.04.08
yt-dlp is up to date (2022.04.08)
[debug] Using fake IP 53.203.173.99 (DE) as X-Forwarded-For
[debug] [ZDF] Extracting URL: https://www.zdf.de/serien/greyzone/zugriff-100.html
[ZDF] zugriff-100: Downloading webpage
[ZDF] zugriff-100: Downloading JSON content
[ZDF] zugriff-100: Downloading JSON metadata
[ZDF] 181004_2015_sendung_gzo: Downloading m3u8 information
[ZDF] 181004_2015_sendung_gzo: Downloading m3u8 information
[ZDF] 181004_2015_sendung_gzo: Downloading m3u8 information
[ZDF] 181004_2015_sendung_gzo: Downloading m3u8 information
[debug] Sort order given by extractor: hasaud, res, quality, language_preference
[debug] Formats sorted by: hasvid, ie_pref, hasaud, res, quality, lang, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, source, id
[info] 181004_2015_sendung_gzo: **Downloading 1 format(s): hls-2577-1+hls-aac-Originalton-0+hls-aac-TV_Ton-0+hls-96-3+hls-aac-TV_Ton-3+hls-aac-Originalton-3+hls-96-2+hls-aac-TV_Ton-2+hls-aac-Originalton-2+hls-96-1+hls-aac-TV_Ton-1+hls-aac-Originalton-1+hls-96-0+hls-aac-TV_Ton-0+hls-aac-Originalton-0**
[debug] Invoking downloader on "https://zdfvodde-vh.akamaihd.net/i/zdf/18/10/181004_2015_sendung_gzo/7/181004_2015_sendung_gzo_a,1a2_476k_p9,1a2_776k_p11,3a4_776k_p11,1a2_1496k_p13,1a2_2296k_p14,1a2_3296k_p15,v14.mp4.csmil/index_5_av.m3u8?null=0"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 247
[download] Destination: Zugriff [181004_2015_sendung_gzo].fhls-2577-1.mp4
[debug] File locking is not supported on this platform. Proceeding without locking

ERROR: Interrupted by user

see the font in bold .seems the command --audio-multistreams will download all the audios by default

**Comment by pukkandan** [comment]
Remove `+mergeall[vcodec=none]`

**Comment by lowprofileusername** [comment]
Thank you. how stupid I am. I didn't check the readme carefully.
Have a good day sir.
