### ISSUE TITLE
Site support request for Pokeflix.tv

### ISSUE THREAD

**Issue by Wilann** [yt-dlp/yt-dlp#3541]
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.04.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Canada

### Example URLs

Season Playlist: `https://www.pokeflix.tv`
Movie Playlist: `https://www.pokeflix.tv/movies/`
Specials Playlist: `https://www.pokeflix.tv/specials/`

### Description

Hoping support can be added for pokeflix.tv 

Thank you for checking out this issue! 

### Verbose log

```shell
yt-dlp https://www.pokeflix.tv/movies/ --verbose
[debug] Command-line config: ['https://www.pokeflix.tv/movies/', '--verbose']
[debug] User config "/Users/wilsonchan/.config/yt-dlp/config": ['--add-metadata']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, err UTF-8, pref UTF-8
[debug] yt-dlp version 2022.04.08 [7884ade65]
[debug] Python version 3.7.4 (CPython 64bit) - Darwin-21.4.0-x86_64-i386-64bit
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1, rtmpdump 2.4
[debug] Optional libraries: brotli, certifi, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [generic] Extracting URL: https://www.pokeflix.tv/movies/
[generic] movies: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] movies: Downloading webpage
[generic] movies: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://www.pokeflix.tv/movies/
Traceback (most recent call last):
  File "/Users/wilsonchan/opt/anaconda3/lib/python3.7/site-packages/yt_dlp/YoutubeDL.py", line 1408, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/wilsonchan/opt/anaconda3/lib/python3.7/site-packages/yt_dlp/YoutubeDL.py", line 1478, in __extract_info
    ie_result = ie.extract(url)
  File "/Users/wilsonchan/opt/anaconda3/lib/python3.7/site-packages/yt_dlp/extractor/common.py", line 641, in extract
    ie_result = self._real_extract(url)
  File "/Users/wilsonchan/opt/anaconda3/lib/python3.7/site-packages/yt_dlp/extractor/generic.py", line 4039, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.pokeflix.tv/movies/
```
```

**Comment by pukkandan** [comment]
> - [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)

Are you sure!?

**Comment by Jules-A** [comment]
This site isn't legal, use https://watch.pokemon.com instead, many specials/semi-recent series are free to watch and they rotate movies every week or 2 afaik.
