### ISSUE TITLE
Philo unsupported site

### ISSUE THREAD

**Issue by scarng63** [yt-dlp/yt-dlp#3544]
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.04.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

USA

### Example URLs

https://www.philo.com/player/player/vod/Vk9EOjYwODU0ODg5OTY0ODY0OTQ5NA
https://www.philo.com/player/player/recording/UmVjb3JkaW5nOjYwODU0ODg5OTg5NDgzMTA2Mg

### Description

Unable to download from my account on Philo using Windows 10 and chrome browser.  

### Verbose log

```shell
[debug] Command-line config: ['-Uv', 'https://www.philo.com/player/player/vod/Vk9EOjYwODU0ODg5OTY0ODY0OTQ5NA']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.04.08 [7884ade] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 2021-09-01-git-c500dc7cca-full_build-www.gyan.dev (setts), ffprobe 2021-09-01-git-c500dc7cca-full_build-www.gyan.dev
[debug] Optional libraries: brotli, certifi, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.04.08, Current version: 2022.04.08
yt-dlp is up to date (2022.04.08)
[debug] [generic] Extracting URL: https://www.philo.com/player/player/vod/Vk9EOjYwODU0ODg5OTY0ODY0OTQ5NA
[generic] Vk9EOjYwODU0ODg5OTY0ODY0OTQ5NA: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] Vk9EOjYwODU0ODg5OTY0ODY0OTQ5NA: Downloading webpage
[generic] Vk9EOjYwODU0ODg5OTY0ODY0OTQ5NA: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://www.philo.com/player/player/vod/Vk9EOjYwODU0ODg5OTY0ODY0OTQ5NA
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1408, in wrapper
    if diff is None and ie_result.get('live_status') == 'is_upcoming':
  File "yt_dlp\YoutubeDL.py", line 1478, in __extract_info
  File "yt_dlp\extractor\common.py", line 641, in extract
  File "yt_dlp\extractor\generic.py", line 4039, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.philo.com/player/player/vod/Vk9EOjYwODU0ODg5OTY0ODY0OTQ5NA
```

**Comment by pased** [comment]
Philo is DRM'd

**Comment by pukkandan** [comment]
@pased Do you only mean that the video that plays in browser has DRM, or that the video refuses to play on a browser without DRM? (You can check by disabling DRM module in firefox)

**Comment by scarng63** [comment]
I wouldn't know if it is DRM'd.   I have chrome and edge.   I login to my
Philo with phone number and the it sends me confirmation to the phone.

**Comment by pased** [comment]
@pukkandan It sends a license request to a Widevine license server, and will refuse to play on a browser if you have DRM turned off.

![image](https://user-images.githubusercontent.com/84234926/166091055-45d76af3-c472-4454-9717-e0e4fa8b06e2.png)
