### ISSUE TITLE
how to use --parse-metadata option in python

### ISSUE THREAD

**Issue by sourabhkv** [yt-dlp/yt-dlp#3546]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

I want to replace video url with video description in comment. i used these options but it was not working
`ydl_opts = {
            'format': 'bv+ba',
            'outtmpl':output,
            'no_color':True,
            'updatetime':False,
            'parse_metadata':"description:(?s)(?P<meta_comment>.+)",
            'postprocessors': [
                {'key': 'FFmpegMetadata', 'add_metadata': 'True',},
                ],
            }`

**Comment by pukkandan** [comment]
parse-metadata and replace-in-metadata are handled by the `MetadataParserPP` postprocessor.
```py
from yt_dlp.postprocessor import MetadataParserPP
ydl_opts = {
    'postprocessors': [{
        'key': 'MetadataParser',
        'when': 'pre_process',
        'actions': [(MetadataParserPP.Actions.INTERPRET, 'description', r'(?s)(?P<meta_comment>.+)')]
    }, ...]
    ...
}
```


But these options really aren't designed to be used via the API. Imho, it is much better to just write your own postprocessor for your specific needs. See https://github.com/yt-dlp/yt-dlp#add-a-custom-postprocessor

**Comment by sourabhkv** [comment]
thanks
