### ISSUE TITLE
YouTube multi audio track

### ISSUE THREAD

**Issue by Alp1821** [yt-dlp/yt-dlp#3548]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

What is the command to embed multi audio track video?
Like this video: https://www.youtube.com/watch?v=LnlKwzc_TNA
This video has 7 audio tracks. I want to download those 7 tracks and embed them.

_-f "bv*+mergeall[vcodec=none]" --audio-multistreams_ this command downloading all differnt audio formats, which I don't want. I only need 7 different languange audio. I don't care about audio formats. Auto audio format selection is fine for me.

**Comment by pukkandan** [comment]
This is not currently possible https://github.com/yt-dlp/yt-dlp/issues/1176

**Comment by CZeil** [comment]
What I can think of is to choose the audio formats manually so that it can work well.
´´´yt-dlp -f "(bv[height<=1080]+251-0+251-1+251-2+251-3+251-4+251-5+251-6)[ext*=webm]"´´´

**Comment by pukkandan** [comment]
if you are sure the format ids are always named 251-n, you could do `-f bv+mergeall[format_id^=251]`

**Comment by Alp1821** [comment]
> This is not currently possible #1176

Is there any possibility of getting this feature in near future?
With proper short command.

**Comment by pukkandan** [comment]
Subscribe to #1176 to be notified when there is any update on this
