### ISSUE TITLE
Requesting Klikk.tv site support

### ISSUE THREAD

**Issue by byomkesh462** [yt-dlp/yt-dlp#3550]
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.04.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

India

### Example URLs

![https://klikk.tv/](https://user-images.githubusercontent.com/88849299/165103064-ecfa8d43-2b5f-412d-be52-10b553b47471.png)

- Site URL: https://klikk.tv/
- Shows Link: https://klikk.tv/video/3286/prankenstein/
- Movie Link: https://klikk.tv/video/309/aparajito/
- Audio Story Link: https://klikk.tv/song/3284/jhorer-raate/
- Free Video Link: https://klikk.tv/video/258/simabaddha/

### Description

This is a Bengali regional OTT platform from West Bengal, India.

This site is using **Brightcove** to host the contents.

I tried to gather the information using `yt-dlp` but it's not supported yet.

That's why requesting this to be added.

### Verbose log

```shell
[debug] Command-line config: ['-vU', 'https://klikk.tv/video/3286/prankenstein/']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.04.08 [7884ade65]
[debug] Python version 3.9.5 (CPython 64bit) - Windows-10-10.0.22000-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg N-105919-g546afd0d49-20220313 (setts), ffprobe N-105919-g546afd0d49-20220313
[debug] Optional libraries: brotli, certifi, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.04.08, Current version: 2022.04.08
yt-dlp is up to date (2022.04.08)
[debug] [generic] Extracting URL: https://klikk.tv/video/3286/prankenstein/
[generic] prankenstein: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] prankenstein: Downloading webpage
[generic] prankenstein: Extracting information
[debug] Looking for video embeds
[download] Downloading playlist: Watch Prankenstein Online
[generic] playlist Watch Prankenstein Online: Downloading 1 videos
[download] Downloading video 1 of 1
[debug] [youtube] Extracting URL: https://www.youtube.com/embed/6303435999001?rel=0
[youtube] 63034359990: Downloading webpage
[youtube] 63034359990: Downloading android player API JSON
ERROR: [youtube] 63034359990: Video unavailable
  File "C:\Users\souvi\AppData\Roaming\Python\Python39\site-packages\yt_dlp\extractor\common.py", line 641, in extract
    ie_result = self._real_extract(url)
  File "C:\Users\souvi\AppData\Roaming\Python\Python39\site-packages\yt_dlp\extractor\youtube.py", line 3377, in _real_extract
    self.raise_no_formats(reason, expected=True)
  File "C:\Users\souvi\AppData\Roaming\Python\Python39\site-packages\yt_dlp\extractor\common.py", line 1161, in raise_no_formats
    raise ExtractorError(msg, expected=expected, video_id=video_id)

[download] Finished downloading playlist: Watch Prankenstein Online
```

**Comment by pukkandan** [comment]
> Free Video Link: [klikk.tv/video/258/simabaddha](https://klikk.tv/video/258/simabaddha/)

Even this is asking for login. Try passing cookies and see if this downloads
