### ISSUE TITLE
Please add season link support for dr.dk

### ISSUE THREAD

**Issue by yiveynod** [yt-dlp/yt-dlp#3567]
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.04.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Worldwide

### Example URLs

Season link: https://www.dr.dk/drtv/saeson/frank-and-kastaniegaarden_9008
1st episode of the above season: https://www.dr.dk/drtv/episode/frank-and-kastaniegaarden_53167

### Description

Downloading from DR.dk works fine, but yt-dlp cannot see season links and returns unsupported URL.

### Verbose log

```shell
yt-dlp -vU --embed-subs https://www.dr.dk/drtv/saeson/frank-and-kastaniegaarden_9008
[debug] Command-line config: ['-vU', '--embed-subs', 'https://www.dr.dk/drtv/saeson/frank-and-kastaniegaarden_9008']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.04.08 [7884ade65]
[debug] Python version 3.9.12 (CPython 64bit) - macOS-12.3-x86_64-i386-64bit
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 5.0.1 (setts), ffprobe 5.0.1, rtmpdump 2.4
[debug] Optional libraries: brotli, certifi, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.04.08, Current version: 2022.04.08
yt-dlp is up to date (2022.04.08)
[debug] [generic] Extracting URL: https://www.dr.dk/drtv/saeson/frank-and-kastaniegaarden_9008
[generic] frank-and-kastaniegaarden_9008: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] frank-and-kastaniegaarden_9008: Downloading webpage
[generic] frank-and-kastaniegaarden_9008: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://www.dr.dk/drtv/saeson/frank-and-kastaniegaarden_9008
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1408, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1478, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 641, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.9/site-packages/yt_dlp/extractor/generic.py", line 4039, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.dr.dk/drtv/saeson/frank-and-kastaniegaarden_9008
```

**Comment by coletdjnz** [comment]
Site makes a request to https://production-cdn.dr-massive.com/api/page?device=web_browser&ff=idp%2Cldp%2Crpt&item_detail_expand=all&lang=da&list_page_size=24&max_list_prefetch=3&path=%2Fsaeson%2Ffrank-and-kastaniegaarden_9008&segments=drtv%2Coptedin&sub=Anonymous&text_entry_format=html to get episode details.

path param can be calculated from the url

Alternatively could try using the API the main extractor is using. It redirects you to documentation at its base url.
