### ISSUE TITLE
Why is there a Github Pages branch

### ISSUE THREAD

**Issue by MrRawes** [yt-dlp/yt-dlp#3572]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

i am wondering why is there a [gh-pages](https://github.com/yt-dlp/yt-dlp/tree/gh-pages) branch, since there is nothing in  that branch

**Comment by pukkandan** [comment]
https://github.com/ytdl-org/youtube-dl/tree/gh-pages. The branch is not deleted just because there is no reason to delete it
