### ISSUE TITLE
Amazon MiniTV (https://www.amazon.in/minitv)

### ISSUE THREAD

**Issue by z8512** [yt-dlp/yt-dlp#3576]
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.04.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

India

### Example URLs

- Single episode: https://www.amazon.in/minitv/tp/74271cb6-e19e-445b-a648-e15a3912b8ef

### Description

Free OTT service by Jeff uncle. 
Not related to Amazon Prime.
100% DRM free!

### Verbose log

```shell
yt-dlp -vU https://www.amazon.in/minitv/tp/74271cb6-e19e-445b-a648-e15a3912b8ef
[debug] Command-line config: ['-vU', 'https://www.amazon.in/minitv/tp/74271cb6-e19e-445b-a648-e15a3912b8ef']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.04.08 [7884ade65]
[debug] Python version 3.9.5 (CPython 64bit) - Linux-5.11.0-49-generic-x86_64-with-glibc2.33
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: avconv -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: avprobe -bsfs
[debug] exe versions: none
[debug] Optional libraries: brotli, certifi, Cryptodome, secretstorage, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.04.08, Current version: 2022.04.08
yt-dlp is up to date (2022.04.08)
[debug] [generic] Extracting URL: https://www.amazon.in/minitv/tp/74271cb6-e19e-445b-a648-e15a3912b8ef
[generic] 74271cb6-e19e-445b-a648-e15a3912b8ef: Requesting header
WARNING: [generic] Could not send HEAD request to https://www.amazon.in/minitv/tp/74271cb6-e19e-445b-a648-e15a3912b8ef: HTTP Error 405: Method Not Allowed
[generic] 74271cb6-e19e-445b-a648-e15a3912b8ef: Downloading webpage
WARNING: [generic] Falling back on generic information extractor.
[generic] 74271cb6-e19e-445b-a648-e15a3912b8ef: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://www.amazon.in/minitv/tp/74271cb6-e19e-445b-a648-e15a3912b8ef
Traceback (most recent call last):
  File "/home/z8512/.local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1408, in wrapper
    return func(self, *args, **kwargs)
  File "/home/z8512/.local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1478, in __extract_info
    ie_result = ie.extract(url)
  File "/home/z8512/.local/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 641, in extract
    ie_result = self._real_extract(url)
  File "/home/z8512/.local/lib/python3.9/site-packages/yt_dlp/extractor/generic.py", line 4039, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.amazon.in/minitv/tp/74271cb6-e19e-445b-a648-e15a3912b8ef
```

**Comment by pukkandan** [comment]
The URL only opens in the app? If so, it is likely not possible to support

**Comment by pukkandan** [comment]
The issue is if the app is using any private information to sign the requests. Unlike a webpage where the code is visible to the public, extracting private keys from apps can be considered a DMCA violation. This is why I said it "may not be possible to support". I did not mean that the site request is invalid

**Comment by shirt-dev** [comment]
It appears to work with a mobile user agent.

**Comment by m4tu4g** [comment]
Is there any manifest to confirm that it's DRM free? Or on which point you're saying it's DRM free

**Comment by pukkandan** [comment]
As shirt discovered, you can play it in browser (without DRM support) with a User-Agent switcher

**Comment by nyuszika7h** [comment]
Indeed, it's playable on mobile web with just an Indian VPN and no login, and the manifests seem to be DRM-free:

https://d3s0ximcru5bdx.cloudfront.net/ruskmedia-series3-firston-s3e1-1640783520196/hls/ruskmedia-series3-firston-s3e1.m3u8

https://d3s0ximcru5bdx.cloudfront.net/ruskmedia-series3-firston-s3e1-1640783520196/dash/ruskmedia-series3-firston-s3e1.mpd"

**Comment by m4tu4g** [comment]
yeah, saw non-drm now, I remember seeing these shows in primevideo with same ASINs and encrypted. (could be glitch in my mind)

**Comment by nyuszika7h** [comment]
It's possible, since the bitrate on Mini TV seems to be like half or less compared to Amazon Prime Video.

**Comment by m4tu4g** [comment]
and as usual CBR, CVBR and AVC, HEVC ... all at S/W level security (L3 to be specific)

**Comment by z8512** [comment]
> The URL only opens in the app? If so, it is likely not possible to support

No no

**Comment by z8512** [comment]
> It appears to work with a mobile user agent.

It does. I tested with curl

**Comment by z8512** [comment]
Please add minitv asap 🙏
