### ISSUE TITLE
yt-dlp-macos.zip file contains no files

### ISSUE THREAD

**Issue by elliotnev27** [yt-dlp/yt-dlp#3584]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.04.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

The yt-dlp_macos.zip file contains no binaries, just empty directories

### Verbose log

```shell
~/Downloads > unzip yt-dlp_macos.zip                                                                          
Archive:  yt-dlp_macos.zip
   creating: dist/yt-dlp_macos/

~ > find Downloads/dist                                                                         
Downloads/dist
Downloads/dist/yt-dlp_macos
```

**Comment by pukkandan** [comment]
Interesting how the bad file has been downloaded a couple thousand times, but this is the first time it's being reported!
