### ISSUE TITLE
[spotify] All links are handled by generic extractor instead of spotify.py

### ISSUE THREAD

**Issue by someziggyman** [yt-dlp/yt-dlp#3585]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.04.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

anywhere

### Description

For some reason all Spotify links are handled by generic extractor instead of spotify extractor. Maybe, link validator should be updated.
https://open.spotify.com/album/3YxZiSLKq2XIQkSONNie9G

Individual track link:
https://open.spotify.com/track/2st7jkwJTgZcyeiR2wCJys?si=4e5a395cd1ff4c47

### Verbose log

```shell
./yt-dlp -v -F "https://open.spotify.com/album/3YxZiSLKq2XIQkSONNie9G"
[debug] Command-line config: ['-v', '-F', 'https://open.spotify.com/album/3YxZiSLKq2XIQkSONNie9G']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.04.08 [7884ade65] (zip)
[debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
[debug] Python version 3.9.12 (CPython 64bit) - macOS-11.6.5-arm64-arm-64bit
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: avprobe -bsfs
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: avconv -bsfs
[debug] exe versions: none
[debug] Optional libraries: sqlite3
[debug] Proxy map: {}
[debug] [generic] Extracting URL: https://open.spotify.com/album/3YxZiSLKq2XIQkSONNie9G
[generic] 3YxZiSLKq2XIQkSONNie9G: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] 3YxZiSLKq2XIQkSONNie9G: Downloading webpage
[generic] 3YxZiSLKq2XIQkSONNie9G: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://open.spotify.com/album/3YxZiSLKq2XIQkSONNie9G
Traceback (most recent call last):
  File "/Users/zig/yt-dlp/./yt-dlp/yt_dlp/YoutubeDL.py", line 1393, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/zig/yt-dlp/./yt-dlp/yt_dlp/YoutubeDL.py", line 1463, in __extract_info
    ie_result = ie.extract(url)
  File "/Users/zig/yt-dlp/./yt-dlp/yt_dlp/extractor/common.py", line 635, in extract
    ie_result = self._real_extract(url)
  File "/Users/zig/yt-dlp/./yt-dlp/yt_dlp/extractor/generic.py", line 4028, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://open.spotify.com/album/3YxZiSLKq2XIQkSONNie9G
```

**Comment by pukkandan** [comment]
Spotify music has DRM and is therefore not supported. Only podcasts are supported
