### ISSUE TITLE
[reddit] Infinite Redirect Loop

### ISSUE THREAD

**Issue by chapmanjacobd** [yt-dlp/yt-dlp#3588]
### Checklist

- [X] I'm reporting a feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.04.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

It seems like this URL is broken on reddit's website https://www.reddit.com/r/MovieStunts/comments/geywlx/besouro_brazilian_martial_arts_film_ocal/

It would be nice if there was some redirect loop detection somehow....

```
[generic] r2rqsh8zg9x41: Requesting header
[redirect] Following redirect to https://www.reddit.com/r/MovieStunts/comments/geywlx/besouro_brazilian_martial_arts_film_ocal/
[Reddit] geywlx: Downloading JSON metadata
[generic] r2rqsh8zg9x41: Requesting header
[redirect] Following redirect to https://www.reddit.com/r/MovieStunts/comments/geywlx/besouro_brazilian_martial_arts_film_ocal/
[Reddit] geywlx: Downloading JSON metadata
[generic] r2rqsh8zg9x41: Requesting header
[redirect] Following redirect to https://www.reddit.com/r/MovieStunts/comments/geywlx/besouro_brazilian_martial_arts_film_ocal/
[Reddit] geywlx: Downloading JSON metadata
[generic] r2rqsh8zg9x41: Requesting header
[redirect] Following redirect to https://www.reddit.com/r/MovieStunts/comments/geywlx/besouro_brazilian_martial_arts_film_ocal/
[Reddit] geywlx: Downloading JSON metadata
[generic] r2rqsh8zg9x41: Requesting header
... this does not stop (although I only waited 3 hours)
```

**Comment by chapmanjacobd** [comment]
hmmm maybe I will just use `timeout` in my CLI script

**Comment by pukkandan** [comment]
This needs to be fixed

**Comment by pukkandan** [comment]
Note that the video is not currently downloadable. The only think I can fix is the infinite loop

**Comment by chapmanjacobd** [comment]
throwing an error is very welcome 🐱
