### ISSUE TITLE
RMC Decouverte : https://www.rmcbfmplay.com

### ISSUE THREAD

**Issue by nara20** [yt-dlp/yt-dlp#3594]
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.04.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

France

### Example URLs

https://www.rmcbfmplay.com/video/rmc-decouverte/les-plus-grandes-places-de-paris?contentId=Product::NEUF_RMCDEC_RMC00165599&universe=PROVIDER

### Description

I would like to download from RMC decouverte replay site.

### Verbose log

```shell
[debug] Command-line config: ['-vU', 'https://www.rmcbfmplay.com/video/rmc-decouverte/les-plus-grandes-places-de-paris']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.04.08 [7884ade] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg N-86098-g3fefaea, ffprobe N-86098-g3fefaea
[debug] Optional libraries: brotli, certifi, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.04.08, Current version: 2022.04.08
yt-dlp is up to date (2022.04.08)
[debug] [generic] Extracting URL: https://www.rmcbfmplay.com/video/rmc-decouverte/les-plus-grandes-places-de-paris
[generic] les-plus-grandes-places-de-paris: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] les-plus-grandes-places-de-paris: Downloading webpage
[generic] les-plus-grandes-places-de-paris: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://www.rmcbfmplay.com/video/rmc-decouverte/les-plus-grandes-places-de-paris
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1408, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1478, in __extract_info
  File "yt_dlp\extractor\common.py", line 641, in extract
  File "yt_dlp\extractor\generic.py", line 4039, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.rmcbfmplay.com/video/rmc-decouverte/les-plus-grandes-places-de-paris
```

**Comment by pukkandan** [comment]
Did you try passing cookies?

**Comment by elyse0** [comment]
All formats have DRM 😢 😢    Same applies for #309

### Log
```bash
yt-dlp -vU --cookies-from-browser firefox "https://www.rmcbfmplay.com/video/rmc-decouverte/les-plus-grandes-places-de-paris?contentId=Product::NEUF_RMCDEC_RMC00165599&universe=PROVIDER" --check-formats
```

```bash
[Cookies] Extracting cookies from firefox
[Cookies] Extracted 3207 cookies from firefox
[rmc-bfmplay] Product::NEUF_RMCDEC_RMC00165599: Downloading webpage
[rmc-bfmplay] Product::NEUF_RMCDEC_RMC00165599: Downloading JSON metadata
[rmc-bfmplay] Product::NEUF_RMCDEC_RMC00165599: Downloading MPD manifest
[rmc-bfmplay] Product::NEUF_RMCDEC_RMC00165599: Downloading MPD manifest
[rmc-bfmplay] Product::NEUF_RMCDEC_RMC00165599: Downloading m3u8 information
[rmc-bfmplay] Product::NEUF_RMCDEC_RMC00165599: Downloading ISM manifest
[rmc-bfmplay] Product::NEUF_RMCDEC_RMC00165599: Downloading MPD manifest
[rmc-bfmplay] Product::NEUF_RMCDEC_RMC00165599: Downloading MPD manifest
[rmc-bfmplay] Product::NEUF_RMCDEC_RMC00165599: Downloading m3u8 information
[rmc-bfmplay] Product::NEUF_RMCDEC_RMC00165599: Downloading ISM manifest
[info] Testing format 2104-1
ERROR: This video is DRM protected; Try selecting another format with --format or add --check-formats to automatically fallback to the next best format
[info] Unable to download format 2104-1. Skipping...
[info] Testing format 1104-1
ERROR: This video is DRM protected; Try selecting another format with --format or add --check-formats to automatically fallback to the next best format
[info] Unable to download format 1104-1. Skipping...
[info] Testing format 704-1
ERROR: This video is DRM protected; Try selecting another format with --format or add --check-formats to automatically fallback to the next best format
[info] Unable to download format 704-1. Skipping...
[info] Testing format 4604
ERROR: This video is DRM protected; Try selecting another format with --format or add --check-formats to automatically fallback to the next best format
[info] Unable to download format 4604. Skipping...
[info] Testing format 3104
ERROR: This video is DRM protected; Try selecting another format with --format or add --check-formats to automatically fallback to the next best format
[info] Unable to download format 3104. Skipping...
[info] Testing format 2104-0
ERROR: This video is DRM protected; Try selecting another format with --format or add --check-formats to automatically fallback to the next best format
[info] Unable to download format 2104-0. Skipping...
[info] Testing format 1104-0
ERROR: This video is DRM protected; Try selecting another format with --format or add --check-formats to automatically fallback to the next best format
[info] Unable to download format 1104-0. Skipping...
[info] Testing format 704-0
ERROR: This video is DRM protected; Try selecting another format with --format or add --check-formats to automatically fallback to the next best format
[info] Unable to download format 704-0. Skipping...
[info] Testing format mp4a.40.5-64000-48000-2-FRE-1
ERROR: This video is DRM protected; Try selecting another format with --format or add --check-formats to automatically fallback to the next best format
[info] Unable to download format mp4a.40.5-64000-48000-2-FRE-1. Skipping...
[info] Testing format mp4a.40.5-64000-48000-2-FRE-0
ERROR: This video is DRM protected; Try selecting another format with --format or add --check-formats to automatically fallback to the next best format
[info] Unable to download format mp4a.40.5-64000-48000-2-FRE-0. Skipping...
ERROR: [rmc-bfmplay] Product::NEUF_RMCDEC_RMC00165599: Requested format is not available. Use --list-formats for a list of available formats
```

**Comment by pukkandan** [comment]
Can you confirm the video does not play in firefox with the "content decryption module" disabled?

**Comment by elyse0** [comment]
I confirm it doesn't play

![image](https://user-images.githubusercontent.com/26639800/168443229-f879a727-1230-4167-b77e-53766c5b0aba.png)

**Comment by pukkandan** [comment]
Same for #309?

**Comment by elyse0** [comment]
> Same for #309?

Yep, https://rmcstory.bfmtv.com now redirects to https://rmcbfmplay.com/chaine/mc-story

![image](https://user-images.githubusercontent.com/26639800/168482136-8bc164aa-5b50-4507-929b-5ad714637d13.png)

**Comment by floviolleau** [comment]
Hi,

So you closed it because there is no solution?

Kind regards

**Comment by elyse0** [comment]
> Hi,
> 
> So you closed it because there is no solution?
> 
> Kind regards

> Hi,
> 
> So you closed it because there is no solution?
> 
> Kind regards

Yeah, unfortunately it won't be supported because it only serves **DRM protected content**, as I showed in the screenshots and logs

**Comment by campones** [comment]
I meant, rmc story not decouverte afaik

**Comment by ytrezq** [comment]
@elyse0 disagree. Some shows such as https://www.rmcbfmplay.com/video/rmc-decouverte/retour-a-linstinct-primaire-s6/s6e1-lune-de-miel-dans-la-jungle?contentId=Product::NEUF_RMCDEC_RMC00174485&universe=PROVIDER  don t use drm and can be played on my rooted Android device.

**Comment by elyse0** [comment]
It still can't be played on firefox with drm disabled. I doubt there is a mobile api that provides formats without drm, but feel free to prove me wrong

![image](https://user-images.githubusercontent.com/26639800/191905722-fe4103ae-8d8f-46ed-9d6d-41e6d9807a4e.png)

**Comment by ytrezq** [comment]
@elyse0 Google chrome based browsers uses the Android infrastructure for decoding drm. If the device is rooted, the keys are missing and decoding fails. Maybe the video use some drm infrastructure but in the end it is in clear text as I can t read drm videos even in browser in the case of Android.

**Comment by pukkandan** [comment]
Being rooted does not necessarily imply you cant play DRM. Confirm with an browser that doesn't support DRM at all - like Brave

**Comment by pukkandan** [comment]
> Brave (at least the desktop version) does support DRM, though it's disabled by default

The android version does not - https://github.com/brave/brave-browser/issues/20424
