### ISSUE TITLE
descarga mp4 o mkv

### ISSUE THREAD

**Issue by ibanana** [yt-dlp/yt-dlp#3596]
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.04.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

españa

### Example URLs

https://www.youtube.com/playlist?list=PL0mpJxYq493HTUTH_0VttxHjH9XrLOfWX

### Description

buenas soy nuevo, vengo de youtube-dl donde solo ponia el enlace y em auto hacia el postprocesamiento, ahora solo consigo bajar en webm, y no soy muy experto alguien me podria ayudar? gracias

### Verbose log

```shell
root@ns305455:/opt# yt-dlp -f bestvideo*+bestaudio/best https://www.youtube.com/playlist?list=PL0mpJxYq493HTUTH_0VttxHjH9XrLOfWX
[youtube:tab] PL0mpJxYq493HTUTH_0VttxHjH9XrLOfWX: Downloading webpage
[youtube:tab] PL0mpJxYq493HTUTH_0VttxHjH9XrLOfWX: Downloading API JSON with unavailable videos
[download] Downloading playlist: Material formativo - Avanzado
[youtube:tab] playlist Material formativo - Avanzado: Downloading 3 videos
[download] Downloading video 1 of 3
[youtube] fplR7uCzsCM: Downloading webpage
[youtube] fplR7uCzsCM: Downloading android player API JSON
[info] fplR7uCzsCM: Downloading 1 format(s): 247+251
[download] Destination: Bandas de Bollinger con Pablo Gil [fplR7uCzsCM].f247.webm
[download] 100% of 14.44MiB in 00:01
[download] Destination: Bandas de Bollinger con Pablo Gil [fplR7uCzsCM].f251.webm
[download] 100% of 8.09MiB in 00:01
[Merger] Merging formats into "Bandas de Bollinger con Pablo Gil [fplR7uCzsCM].webm"
Deleting original file Bandas de Bollinger con Pablo Gil [fplR7uCzsCM].f251.webm (pass -k to keep)
Deleting original file Bandas de Bollinger con Pablo Gil [fplR7uCzsCM].f247.webm (pass -k to keep)
[download] Downloading video 2 of 3
[youtube] ZCBW029WeaY: Downloading webpage
[youtube] ZCBW029WeaY: Downloading android player API JSON
[info] ZCBW029WeaY: Downloading 1 format(s): 247+251
[download] Destination: ¿Cómo hacer trading con Medias Móviles [ZCBW029WeaY].f247.webm
[download] 100% of 95.55MiB in 00:13
[download] Destination: ¿Cómo hacer trading con Medias Móviles [ZCBW029WeaY].f251.webm
[download] 100% of 50.02MiB in 00:07
[Merger] Merging formats into "¿Cómo hacer trading con Medias Móviles [ZCBW029WeaY].webm"
Deleting original file ¿Cómo hacer trading con Medias Móviles [ZCBW029WeaY].f247.webm (pass -k to keep)
Deleting original file ¿Cómo hacer trading con Medias Móviles [ZCBW029WeaY].f251.webm (pass -k to keep)
[download] Downloading video 3 of 3
[youtube] GMjEw6BX17g: Downloading webpage
[youtube] GMjEw6BX17g: Downloading android player API JSON
[info] GMjEw6BX17g: Downloading 1 format(s): 247+251
[download] Destination: Sistema de Trading basado en la combinación de RSI y Media Móvil Ponderada [GMjEw6BX17g].f247.webm
[download] 100% of 8.41MiB in 00:01
[download] Destination: Sistema de Trading basado en la combinación de RSI y Media Móvil Ponderada [GMjEw6BX17g].f251.webm
[download] 100% of 5.47MiB in 00:00
[Merger] Merging formats into "Sistema de Trading basado en la combinación de RSI y Media Móvil Ponderada [GMjEw6BX17g].webm"
Deleting original file Sistema de Trading basado en la combinación de RSI y Media Móvil Ponderada [GMjEw6BX17g].f251.webm (pass -k to keep)
Deleting original file Sistema de Trading basado en la combinación de RSI y Media Móvil Ponderada [GMjEw6BX17g].f247.webm (pass -k to keep)
[download] Finished downloading playlist: Material formativo - Avanzado
```

**Comment by NanaMizukiAnother7** [comment]
Translation:
> Good, I'm new, I came from youtube-dl where I only put the link and auto to post-processing, now I can only download on webm, and I'm not very expert, could someone help me? thank you

Use "--merge-output-format mkv". Otherwise, "-f 136+140" for MP4.

**Comment by ibanana** [comment]
Muchas gracias, funciona perfectamente

**Comment by ibanana** [comment]
Seria muy complicado bajar todas las listas de un canal ordenadas en carpetas?

**Comment by pukkandan** [comment]
See https://github.com/yt-dlp/yt-dlp#output-template-examples

Translation: https://github-com.translate.goog/yt-dlp/yt-dlp?_x_tr_sl=auto&_x_tr_tl=es&_x_tr_hl=en-US&_x_tr_pto=wapp#output-template-examples

**Comment by ibanana** [comment]
yt-dlp --merge-out-format mkv -o "%(uploader)s/%(playlist)s/%(playlist_index)s - %(title)s.%(ext)s" "https://www.youtube.com/c/x"
da error al añadir el formato, y sin formato descarga en webm.

**Comment by pukkandan** [comment]
--merge-out**put**-format mkv

**Comment by ibanana** [comment]
yt-dlp -merge-output-format mkv -o "%(uploader)s/%(playlist)s/%(playlist_index)s - %(title)s.%(ext)s" "https://www.youtube.com/c/TradingyBolsa/playlists"
Usage: yt-dlp [OPTIONS] URL [URL...]

yt-dlp: error: no such option: -m
root@ns305455:/opt/files/files/files/Trading/Cursos#

**Comment by ibanana** [comment]
yt-dlp --merge-output-format mkv -o "%(uploader)s/%(playlist)s/%(playlist_index)s - %(title)s.%(ext)s" "https://www.youtube.com/c/TradingyBolsa/playlists"

sigue saliendo webm, creo que optare por mp4
