### ISSUE TITLE
errors while downloading videos

### ISSUE THREAD

**Issue by ROSH0518** [yt-dlp/yt-dlp#3598]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

how to make it  ignore errors while downloading videos from youtube search?
the program stopped after downloading few videos due to some error.

**Comment by pukkandan** [comment]
Step 1: actually do this instead of blindly ticking it

> - [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

Step 2: Provide more details including a verbose log

**Comment by ROSH0518** [comment]
I got the following error  when i downloaded videos from youtube search

`yt_dlp.utils.DownloadError:ERROR: [youtube] qF-sS1fJhww: Video unavailable. This video is no longer available because the YouTube account associated with this video has been terminated.`
