### ISSUE TITLE
[odysee] Cannot download from a channel

### ISSUE THREAD

**Issue by vadimhp** [yt-dlp/yt-dlp#3601]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.04.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Canada

### Description

Was able to download from this particular channel last in October 2021 - https://odysee.com/@enlightenedones!:1
Since then - nothing, keep getting this error. Maybe because there's an exclamation mark in the URL

### Verbose log

```shell
[debug] Command-line config: ['--output', '/path/%(upload_date)s - enlightened-ones - %(title)s.%(ext)s', '--download-archive', '/path/_download-archive.log', 'https://odysee.com/@enlightenedones--output']
[debug] Home config "yt-dlp.conf": ['--download-archive', '~/.config/youtube-dl/downloaded', '--write-info-json', '--write-thumbnail', '--console-title', '--ignore-errors', '--format', 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best', '--no-overwrites', '--verbose', '--age-limit', '30', '--output', '~/Downloads/%(upload_date)s - %(uploader)s - %(title)s.%(ext)s']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8 (No ANSI), err utf-8 (No ANSI), pref UTF-8
[debug] yt-dlp version 2022.04.08 [7884ade65] (zip)
[debug] Python version 3.8.10 (CPython 64bit) - Linux-5.13.0-40-generic-x86_64-with-glibc2.29
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4, rtmpdump 2.4
[debug] Optional libraries: certifi, secretstorage, sqlite
[debug] Proxy map: {}
[debug] Loading archive file '/path/_download-archive.log'
[debug] [lbry:channel] Extracting URL: https://odysee.com/@enlightenedones--output
[lbry:channel] @enlightenedones--output: Downloading channel JSON metadata
ERROR: @enlightenedones--output: An extractor error has occurred. (caused by KeyError('claim_id')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 641, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/lbry.py", line 273, in _real_extract
    claim_id = result['claim_id']
KeyError: 'claim_id'
```

**Comment by flashdagger** [comment]
Exactly. On bash you need to escape the exclamation mark in the channel name or put it in single quotes:
`yt-dlp <options> 'https://odysee.com/@enlightenedones!:1'`
`yt-dlp <options> https://odysee.com/@enlightenedones\!:1`
