### ISSUE TITLE
How to solve cannot upload youtube MP4 video to twitter

### ISSUE THREAD

**Issue by abdulbadii** [yt-dlp/yt-dlp#3607]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

Try to upload video to twitter from the result of youtube video downloaded by :

`yt-dlp -o vid.mp4 -f 135+139 https://youtu.be/NFTZbSU7X9I`

but when it's uploaded in the place prepared in Twitter tweet it will fail

Never fail such on video downloaded from Twitter video itself.. Please show the solving steps,

### Verbose log

```shell
yt-dlp --version
2022.04.08
```

**Comment by Bricio** [comment]
From the first result on google about twitter video formats https://www.google.com/search?q=twitter+upload+video+formats
Your video must be no longer that 2 min and 20 seconds.

```
Twitter video upload requirements

When uploading videos to Twitter you’ll need to make sure that your video file meets the limitations of video resolution and length. Here are some notes to keep in mind:

    Videos must be 2 minutes and 20 seconds or less.
    The minimum resolution for Twitter videos is 32 x 32 and the maximum resolution is 1920 x 1200 or 1200 x 1900.
    Supported formats are MP4 and MOV on the Twitter mobile apps and, on the web, MP4 with H264 format with AAC audio.
    The maximum file size is 512MB.

```

Your video has 2:37
![image](https://user-images.githubusercontent.com/216170/166148702-3ebfd8cf-99ee-4f9b-9bd6-0ee94174ed97.png)



Did you tried another video?

**Comment by pukkandan** [comment]
The question is clearly not related to yt-dlp

**Comment by abdulbadii** [comment]
So how to trim MP4 by use of yt-dlp ?
