### ISSUE TITLE
[Question] DEPRECATED OPTIONS

### ISSUE THREAD

**Issue by fosam** [yt-dlp/yt-dlp#361]
## Checklist

- [X] I'm asking a question
- [X] I've looked through the README and FAQ for similar questions
- [X] I've searched the bugtracker for similar questions including closed ones

## Question

Are the options on the right the current ones that replace the options on the left? if yes, why can't i find **`--print description`** for example under **`USAGE AND OPTIONS`**?

![Capture 30_05_2021_00_25_14](https://user-images.githubusercontent.com/52612348/120086419-0475c880-c0df-11eb-8fbd-9708b4e780f9.png)

**Comment by pukkandan** [comment]
`--print` is the switch that replaces all those options. The field name (or output template) is the argument that you pass to that option.

**Comment by fosam** [comment]
I see,

I just took that as an example, but if those options on the right are "newer" and "current" why are they not explained [here](https://github.com/yt-dlp/yt-dlp#usage-and-options)? that is exactly the question i asked myself but i didn't have any answer :)

**Comment by pukkandan** [comment]
They are! Just search for `--print` or `--ppa` or `--downloader` etc

**Comment by fosam** [comment]
Yes, i found 1 result for `--print filename` for example which is the one under DEPRECATED OPTIONS

![Capture 30_05_2021_01_07_23](https://user-images.githubusercontent.com/52612348/120086963-29b90580-c0e4-11eb-87c8-072f382405e5.png)


But what i mean is there is no more info about it like these kind of explanations:

![Capture 30_05_2021_01_08_16](https://user-images.githubusercontent.com/52612348/120086971-3f2e2f80-c0e4-11eb-924d-5dd79741c7cb.png)

**Comment by fosam** [comment]
I finally found it, instead of listing every option for `--print`, they are summarized into `--print`+`filed name` which i coudn't see at first.

I use both `dl` and `dlp` and there is a slight difference between the two, hence this small confusion, but everyday we learn new things!

Thanks!
