### ISSUE TITLE
[Youtube] Lower sized `248` (`vp9`) is not better than `137` (`avc1`)

### ISSUE THREAD

**Issue by AlttiRi** [yt-dlp/yt-dlp#3611]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.04.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

Why does it download webm video from Youtube when there is mp4 with 10-100+ % bigger size?

For example in this case:

![image](https://user-images.githubusercontent.com/16310547/166161602-4bbb29eb-9aba-48d3-b027-cb4a64ae6964.png)

- `137 mp4` 378.33 MiB avc1 (4141k)
- `248 webm` 162.19 MiB vp9 (1775k)

yt-dlp selects vp9 as "best".

---

Just compare:
- `https://www.youtube.com/watch?v=eBfIORVLNUA`
- `https://www.youtube.com/watch?v=eBfIORVLNUA -f 137+140`

![image](https://user-images.githubusercontent.com/16310547/166161564-66644bc8-da56-417b-bdd4-964b92f156af.png)

`00:01:12.072` in both videos is a key-frame, the screenshots:
- https://i.imgur.com/b3K8LjK.png (`248 webm`, `125.42 MiB 2594k`default)
- https://i.imgur.com/NRY3vje.png (`137 mp4`, `195.10 MiB 4036k`)

### Verbose log

```shell
[debug] Command-line config: ['--write-thumbnail', '--write-description', '-o', '[%(webpage_url_domain)s] %(uploader,creator,playlist_title)s—%(upload_date>%Y.%m.%d)s—%(id)s—%(fu
lltitle|)s.%(ext)s', '-o', 'pl_thumbnail:[%(webpage_url_domain)s][thumbnail] %(uploader,creator,playlist_title)s—%(upload_date>%Y.%m.%d)s—%(playlist_id,id)s—%(fulltitle|)s.%(ext)
s', 'https://www.youtube.com/watch?v=eBfIORVLNUA', '-vU']

[debug] yt-dlp version 2022.04.08 [7884ade65]

Latest version: 2022.04.08, Current version: 2022.04.08
yt-dlp is up to date (2022.04.08)
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=eBfIORVLNUA

[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasa
ud, id

[debug] Default format spec: bestvideo*+bestaudio/best
[info] eBfIORVLNUA: Downloading 1 format(s): 248+251

```
```

**Comment by pukkandan** [comment]
See https://github.com/yt-dlp/yt-dlp/issues/1232#issuecomment-939635345
