### ISSUE TITLE
So how to trim MP4 while downloading at once by use of yt-dlp ?

### ISSUE THREAD

**Issue by abdulbadii** [yt-dlp/yt-dlp#3614]
So how to trim MP4 while downloading at once by use of yt-dlp ?

_Originally posted by @abdulbadii in https://github.com/yt-dlp/yt-dlp/issues/3607#issuecomment-1114387354_

**Comment by pukkandan** [comment]
https://github.com/yt-dlp/yt-dlp/issues/686#issuecomment-904191812

**Comment by pukkandan** [comment]
IGNORING THE ISSUE TEMPLATE WILL RESULT IN ISSUE CLOSED AS INCOMPLETE

and repeated offense will be treated as spam
