### ISSUE TITLE
Is there any way to specify the file name?

### ISSUE THREAD

**Issue by Nagatochyan** [yt-dlp/yt-dlp#3618]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

I want to change the file name like Video.mp4

**Comment by MarcosDevs** [comment]
before asking you have to README.md. The answer to your question is there. 

https://github.com/yt-dlp/yt-dlp#filesystem-options >>> -o, --output [TYPES:]TEMPLATE

**Comment by Nagatochyan** [comment]
like how to do with python?

**Comment by MarcosDevs** [comment]
> like how to do with python?

https://github.com/yt-dlp/yt-dlp#embedding-examples

The key: "outtmpl"

**Comment by Nagatochyan** [comment]
?

**Comment by MarcosDevs** [comment]
> ?

Just include the key after the name

**Comment by Nagatochyan** [comment]
you mean like this?
'key': 'FFmpegExtractAudio', 'qwerty.mp4'

**Comment by pukkandan** [comment]
> you mean like this? 'key': 'FFmpegExtractAudio', 'qwerty.mp4'

That makes no sense! See https://github.com/yt-dlp/yt-dlp#embedding-examples

**Comment by MarcosDevs** [comment]
> > Você quer dizer assim? 'key': 'FFmpegExtractAudio', 'qwerty.mp4'
> 
> Isso não faz sentido! Consulte https://github.com/yt-dlp/yt-dlp#embedding-examples

I'm guessing you're new to python.

**Comment by MarcosDevs** [comment]
> > Você quer dizer assim? 'key': 'FFmpegExtractAudio', 'qwerty.mp4'
> 
> Isso não faz sentido! Consulte https://github.com/yt-dlp/yt-dlp#embedding-examples

I'm guessing he's new to python.

**Comment by MarcosDevs** [comment]
> Você quer dizer assim? 'key': 'FFmpegExtractAudio', 'qwerty.mp4'

I recommend you search for some python lessons on YouTube.


I'll give you a complete example, but you really need to study a little more. Just dedicate yourself 😉

```python
import yt_dlp

URLS = ['https://www.youtube.com/watch?v=BaW_jenozKc']

ydl_opts = {
    'outtmpl': 'video.mp4'
}

with yt_dlp.YoutubeDL(ydl_opts) as ydl:
    error_code = ydl.download(URLS)
```

**Comment by Nagatochyan** [comment]
thank you

**Comment by T-burger** [comment]
Hey, I am trying to do something similar, but I would like to modify the path for the temporary files, do I need to pass something else to outtmpl to specify the temp path?

**Comment by pukkandan** [comment]
```py
ydl_opts = {
    'paths': {'home': 'D:\Downloads', 'temp': 'D:\Trash'},
    'outtmpl': 'video.mp4'
}
```

Seriously, pls read the docs before asking questions!

**Comment by T-burger** [comment]
Hey, thanks for that.
Sorry, I did read through the documentation and couldn't quite figure it out how to pass the paths values. I know my python isn't great, but do you think it would be helpful if I tried to add this to the examples in the README ?

**Comment by pukkandan** [comment]
I can't possibly add examples for all `params` one by one, and `paths` is not a particularly complex case. It's documentation is pretty clear imo. If you think it can be improved, feel free to make suggestions. But adding example is not the solution

API:
```
    paths:             Dictionary of output paths. The allowed keys are 'home'
                       'temp' and the keys of OUTTMPL_TYPES (in utils.py)
```
CLI:
```

    -P, --paths [TYPES:]PATH        The paths where the files should be
                                    downloaded. Specify the type of file and the
                                    path separated by a colon ":". All the same
                                    TYPES as --output are supported.
                                    Additionally, you can also provide "home"
                                    (default) and "temp" paths. All intermediary
                                    files are first downloaded to the temp path
                                    and then the final files are moved over to
                                    the home path after download is finished.
                                    This option is ignored if --output is an
                                    absolute path
```
