### ISSUE TITLE
Can I record a chat in a broadcast?

### ISSUE THREAD

**Issue by vden89** [yt-dlp/yt-dlp#3621]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

Hello. Tell me, is it possible to record a chat along with YouTube live broadcast? And then add it to the video, for example, overlay it on top of the video.

**Comment by pukkandan** [comment]
> Hello. Tell me, is it possible to record a chat along with YouTube live broadcast?

Run a separate yt-dlp with `--skip-download --write-subs --sub-lang live_chat`

> And then add it to the video, for example, overlay it on top of the video.

No
