### ISSUE TITLE
Can't download Udemy video: "No video formats found!"

### ISSUE THREAD

**Issue by matusbielik** [yt-dlp/yt-dlp#3626]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.04.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Europe

### Description

Simple as that, the script says "No video formats found!" for provided url (see log).

Curious thing is, when I download the whole playlist `https://www.udemy.com/unrealcourse`, the first mp4 video downloads, then the rest get the error.

Can this be something with encrypted content? I am also not able to play these videos on Linux Chromium, browser console mentions similar error: 
`VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) No compatible source was found for this media. It {code: 4, message: 'No compatible source was found for this media.'}`

 The urls are correct though, Firefox plays the player on them (the playback stutters on high speeds though, so I want to download the videos locally)

Thanks!

### Verbose log

```shell
yt-dlp "https://www.udemy.com/unrealcourse/learn/v4/t/lecture/31718252" --cookies ../udemy.com_cookies.txt -vU
[debug] Command-line config: ['https://www.udemy.com/unrealcourse/learn/v4/t/lecture/31718252', '--cookies', '../udemy.com_cookies.txt', '-vU']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.04.08 [7884ade65] (zip)
[debug] Python version 3.9.2 (CPython 64bit) - Linux-5.17.0-1-amd64-x86_64-with-glibc2.31
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.3.4-0, ffprobe 4.3.4-0, phantomjs 139972463130560, rtmpdump 2.4
[debug] Optional libraries: certifi, Cryptodome, sqlite
[debug] Proxy map: {}
Latest version: 2022.04.08, Current version: 2022.04.08
yt-dlp is up to date (2022.04.08)
[debug] [udemy] Extracting URL: https://www.udemy.com/unrealcourse/learn/v4/t/lecture/31718252
[udemy] 31718252: Downloading webpage
[udemy] 31718252: Downloading lecture JSON
ERROR: [udemy] 40638444: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1408, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1492, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1548, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 2487, in process_video_result
    self.raise_no_formats(info_dict)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 981, in raise_no_formats
    raise ExtractorError(msg, video_id=info['id'], ie=info['extractor'],
yt_dlp.utils.ExtractorError: [udemy] 40638444: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

**Comment by dirkf** [comment]
Related: https://github.com/ytdl-org/youtube-dl/issues/29925
