### ISSUE TITLE
Pornhub avatar

### ISSUE THREAD

**Issue by afterdelight** [yt-dlp/yt-dlp#3629]
### Checklist

- [X] I'm reporting a site feature request
- [X] I've verified that I'm running yt-dlp version **2022.04.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

indonesia

### Example URLs

https://www.pornhub.com/model/eroneko-adult-ch

https://www.pornhub.com/view_video.php?viewkey=ph626cd646a7346

https://di.phncdn.com/pics/users/u/002/166/956/341/avatar1627874003/(m=ewILGCjadOf)(mh=vmb1DaCV4DVPwKmf)200x200.jpg

### Description

add profile avatar download support

avatar can be seen on single link

### Verbose log

```shell
xxx
```

**Comment by gamer191** [comment]
I did not open the url, but I'm guessing that it's an image. If that's the case, then I'm afraid yt-dlp doesn't support images. Please use [Gallery-dl](https://github.com/mikf/gallery-dl) instead

**Comment by afterdelight** [comment]
its just one image, so its ok i guess
