### ISSUE TITLE
Add support for Scroller.com (A Reddit scroller website)

### ISSUE THREAD

**Issue by frans77frans** [yt-dlp/yt-dlp#3635]
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.04.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [x] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

United States

### Example URLs

Example of image: https://scrolller.com/how-do-i-look-now-9sy8ply9ri
Example of video: https://scrolller.com/a-helping-hand-1k9pxikxkw

### Description

Scroller is a site to view subreddits in their own "scroller" interface. Support for this site would be appreciated.

### Verbose log

```shell
[debug] Command-line config: ['-vu', 'URL', 'https://scrolller.com/a-helping-hand-1k9pxikxkw']
Type account password and press [Return]:
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.04.08 [7884ade] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.2.2, ffprobe 2021-06-30-git-de8e6e67e7-full_build-www.gyan.dev, phantomjs 2.1.1
[debug] Optional libraries: brotli, certifi, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [generic] Extracting URL: https://scrolller.com/a-helping-hand-1k9pxikxkw
[generic] a-helping-hand-1k9pxikxkw: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] a-helping-hand-1k9pxikxkw: Downloading webpage
[generic] a-helping-hand-1k9pxikxkw: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://scrolller.com/a-helping-hand-1k9pxikxkw
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1408, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1478, in __extract_info
  File "yt_dlp\extractor\common.py", line 641, in extract
  File "yt_dlp\extractor\generic.py", line 4039, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://scrolller.com/a-helping-hand-1k9pxikxkw
```

**Comment by pukkandan** [comment]
For devs: All info is in `scrolllerConfig` variable in the webpage. There is also a graphql endpoint available. Either implementation seems easy
