### ISSUE TITLE
download-archive

### ISSUE THREAD

**Issue by Spp595** [yt-dlp/yt-dlp#3638]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

I use the download-archive command downloaded.txt --no-post-overwrites -ciwx in order not to download the same tracks several times, but is it possible to make it so that when deleting a track and entering a command, he checks if there is a track in the playlist and if not, deletes it from the download file (I think it's clear)
I will be glad if you throw off a ready-made command
My command
yt-dlp --download-archive downloaded.txt --no-post-overwrites -ciwx --audio-format mp3  --audio-quality 0 --format bestaudio --embed-thumbnail -o '/home/user/YouTubeMusic%(playlist_title)s/%(uploader)s.%(title)s.%(ext)s' URL

**Comment by pukkandan** [comment]
No, if you want to check for if the file exists in disk, just don't use --download-archive

**Comment by Spp595** [comment]
> Нет, если вы хотите проверить, существует ли файл на диске, просто не используйте --download-archive

then what instead of him?

**Comment by afterdelight** [comment]
i think you misundestand hi squestion

**Comment by Spp595** [comment]
> я думаю, вы неправильно поняли вопрос привет

how to understand his question correctly?)))

**Comment by afterdelight** [comment]
who knows lol

**Comment by dirkf** [comment]
Isn't OP asking how to remove a previously indexed item from the download archive if the item no longer exists on the site?

пожалуйста, задайте [ваш вопрос](https://github.com/yt-dlp/yt-dlp/issues/3638#issue-1225154649) по русски.

**Comment by Spp595** [comment]
> Isn't OP asking how to remove a previously indexed item from the download archive if the item no longer exists on the site?
> 
> пожалуйста, задайте [ваш вопрос](https://github.com/yt-dlp/yt-dlp/issues/3638#issue-1225154649) по русски.
Я использую команду downloaded.txt --no-post-overwrites -ciwx для того чтобы не скачивать по несколько раз одни и те же треки, но можно ли сделать так чтобы при повторном использование команды она проверяла находиться ли песня в плейлисте и если нет то удаляла ее из списка и из устройства

**Comment by pukkandan** [comment]
> Isn't OP asking how to remove a previously indexed item from the download archive if the item no longer exists on the site?

If this is indeed the question, the answer is No. yt-dlp is not a "media manager"!

**Comment by afterdelight** [comment]
unneeded feature
