### ISSUE TITLE
[YouTube] Can't download region restricted videos

### ISSUE THREAD

**Issue by MimuraKyosuke** [yt-dlp/yt-dlp#3641]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

This video is probably only available in Japan.
But I'm trying to download from Japan.
Is there a way to download it?

### Verbose log

```shell
[debug] Command-line config: ['-vU', '-f', 'b', 'https://www.youtube.com/watch?v=jwCz9KmGuYY']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.04.08 [7884ade65] (zip)
[debug] Python version 3.8.10 (CPython 64bit) - Linux-5.4.0-94-generic-x86_64-with-glibc2.29
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: avconv -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: avprobe -bsfs
[debug] exe versions: none
[debug] Optional libraries: certifi, secretstorage, sqlite
[debug] Proxy map: {}
Latest version: 2022.04.08, Current version: 2022.04.08
yt-dlp is up to date (2022.04.08)
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=jwCz9KmGuYY
[youtube] jwCz9KmGuYY: Downloading webpage
[youtube] jwCz9KmGuYY: Downloading android player API JSON
ERROR: [youtube] jwCz9KmGuYY: Video unavailable. The uploader has not made this video available in your country
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 641, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/youtube.py", line 3377, in _real_extract
    self.raise_no_formats(reason, expected=True)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 1161, in raise_no_formats
    raise ExtractorError(msg, expected=expected, video_id=video_id)
```

**Comment by NanaMizukiAnother7** [comment]
Use proxy or VPN.

**Comment by pukkandan** [comment]
In general, yt-dlp cannot download videos that you cannot access in browser

**Comment by MimuraKyosuke** [comment]
Thank you for your reply.
I live in Japan so I can access it with a browser.
I can watch this video normally.

**Comment by pukkandan** [comment]
Are you using the same IP for yt-dlp as you are in browser? Confirm that you can access the video in an incognito tab without login

**Comment by KonoVitoDa** [comment]
> --source-address

What IP you used?

**Comment by MimuraKyosuke** [comment]
--source-address was irrelevant.
It was my mistake.
