### ISSUE TITLE
[TikTok] Videos with empty title show erroneous warning message and set empty title

### ISSUE THREAD

**Issue by UnlimitedCookies** [yt-dlp/yt-dlp#3644]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.04.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Description

`WARNING: Extractor failed to obtain "title". Creating a generic title instead` is shown on videos with an empty title. This means that the predefined output file name is ignored.

### Verbose log

```shell
[debug] Command-line config: ['-vU', 'https://www.tiktok.com/@derverruecktejunge78/video/7085629691561889029']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.04.08 [7884ade65]
[debug] Python version 3.10.4 (CPython 64bit) - Linux-5.17.4-arch1-1-x86_64-with-glibc2.35
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 5.0 (setts), ffprobe 5.0, rtmpdump 2.4
[debug] Optional libraries: brotli, certifi, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.03.08.1, Current version: 2022.04.08
yt-dlp is up to date (2022.04.08)
[debug] [TikTok] Extracting URL: https://www.tiktok.com/@derverruecktejunge78/video/7085629691561889029
[TikTok] 7085629691561889029: Downloading video details
[debug] Sort order given by extractor: quality, codec, size, br
[debug] Formats sorted by: hasvid, ie_pref, quality, vcodec, acodec, filesize, fs_approx, tbr, vbr, abr, lang, res, fps, hdr:12(7), asr, proto, vext, aext, hasaud, source, id
WARNING: Extractor failed to obtain "title". Creating a generic title instead
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 7085629691561889029: Downloading 1 format(s): bytevc1_720p_1054024-2
[debug] Invoking downloader on "https://v39-eu.tiktokcdn.com/7ee44fe37df7ff62d76d25d7e3bd6f4e/627375a2/video/tos/useast2a/tos-useast2a-ve-0068c001/105e9a6b67c54a179b2afb24bea1b911/?a=1180&br=2058&bt=1029&cd=0%7C0%7C0%7C3&ch=0&cr=3&cs=2&cv=1&dr=0&ds=3&er=&ft=aEAqiq4fmo0-CSzKvjJcIs~nRf-Z4V8_4k&l=2022050500582701024501910601D68394&lr=all&mime_type=video_mp4&net=0&pl=0&qs=14&rc=ajRkeTk6ZnNtPDMzNzczM0ApZmc4aDs2NGU1NzY2ZWk1OGcyMTRhcjRfYF5gLS1kMTZzczNeYGAuMzZeXy9fMF8yMF46Yw%3D%3D&vl=&vr="
[download] Destination: TikTok video #7085629691561889029 [7085629691561889029].mp4
[download] 100% of 1.90MiB in 00:00
```

**Comment by pukkandan** [comment]
The warning is correct

> This means that the predefined output file name is ignored.

What "predefined output filename"?

**Comment by UnlimitedCookies** [comment]
> The warning is correct
> 
> > This means that the predefined output file name is ignored.
> 
> What "predefined output filename"?

The output name is specified with `-o cool video %(title)s.%(ext)s`. Instead of the correct  title "" "TikTok video #235743245785325" is used.
There warning is false because the title is "" and it could be retrieved successfully.

**Comment by sulyi** [comment]
> that case the file name would be totally fine

True, generating general title can be postponed after filenames validation, but I don't remember it checking if basename stars with `.`, if it contains `..`, or if it is completely empty.

Also extractors doesn't return `None` as not found `'title'` only `''`, afaik.

**Comment by UnlimitedCookies** [comment]
I can only say that the behavior has changed, because about 6 months ago yt-dlp didn't show the warning and happily used the empty string for the title. That's why I created this issue, presuming it's a regression.

**Comment by pukkandan** [comment]
> The output name is specified with -o cool video %(title)s.%(ext)s. Instead of the correct title "" "TikTok video #235743245785325" is used.

No, title and filename are different things! If you set a custom filename, that will be used. But you haven't set any in the given logs. 

> I can only say that the behavior has changed, because about 6 months ago yt-dlp didn't show the warning and happily used the empty string for the title. That's why I created this issue, presuming it's a regression.

yt-dlp should never have accepted empty title. If it did, that was a bug. If you want the title without the generated "generic title", use `fulltitle` field

> - `title` (string): Video title
> - `fulltitle` (string): Video title ignoring live timestamp and generic title

**Comment by UnlimitedCookies** [comment]
I'll try out `fulltitle`, but what does `ignoring live timestamp and generic title` mean?

And perhaps it should be documented that a generic title is used, if the title from the api is empty.

**Comment by pukkandan** [comment]
> it should be documented that a generic title is used, if the title from the api is empty.

> WARNING: Extractor failed to obtain "title". Creating a generic title instead

---

> but what does ignoring live timestamp and generic title mean?

See https://github.com/yt-dlp/yt-dlp/issues/1573 https://github.com/yt-dlp/yt-dlp/issues/2760
