### ISSUE TITLE
[ctvnews] error: DRM protected

### ISSUE THREAD

**Issue by shawn8888** [yt-dlp/yt-dlp#3647]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.04.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Canada

### Description

Starting yesterday, new video links reports "DRM protected" error.

Here are two sample links that cannot download.

https://www.ctvnews.ca/video?clipId=2428781&playlistId=1.5887610&binId=1.810415&playlistPageNum=1&binPageNum=1
https://www.ctvnews.ca/video?clipId=2428785&playlistId=1.5889452&binId=1.810415&playlistPageNum=1&binPageNum=1

Please help!

### Verbose log

```shell
yt-dlp -vU https://www.ctvnews.ca/video?clipId=2428781&playlistId=1.5887610&binId=1.810415&playlistPageNum=1&binPageNum=1
[debug] Command-line config: ['-vU', 'https://www.ctvnews.ca/video?clipId=2428781']
[debug] Encodings: locale cp936, fs utf-8, out utf-8, err utf-8, pref cp936
[debug] yt-dlp version 2022.03.08.1 [c0c2c57] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.17763-SP0
[debug] exe versions: ffmpeg N-94014-g80e68ce116, ffprobe N-94014-g80e68ce116, phantomjs 0
[debug] Optional libraries: brotli, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.03.08.1, Current version: 2022.03.08.1
yt-dlp is up to date (2022.03.08.1)
[debug] [CTVNews] Extracting URL: https://www.ctvnews.ca/video?clipId=2428781
[debug] Using fake IP 99.226.119.120 (CA) as X-Forwarded-For
[debug] [9c9media] Extracting URL: 9c9media:ctvnews_web:2428781
[9c9media] 2428781: Downloading JSON metadata
[9c9media] 2428781: Downloading JSON metadata
ERROR: [9c9media] 2428781: This video is DRM protected
  File "yt_dlp\extractor\common.py", line 617, in extract
  File "yt_dlp\extractor\ninecninemedia.py", line 36, in _real_extract
  File "yt_dlp\extractor\common.py", line 1081, in report_drm
  File "yt_dlp\extractor\common.py", line 1126, in raise_no_formats

'playlistId' is not recognized as an internal or external command,
operable program or batch file.
'binId' is not recognized as an internal or external command,
operable program or batch file.
'playlistPageNum' is not recognized as an internal or external command,
operable program or batch file.
'binPageNum' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by pukkandan** [comment]
That is because they are!

https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#:~:text=serves%20only%20DRM%20protected%20content

**Comment by gamer191** [comment]
On a side note, @shawn8888 I would highly recommend putting the URLs you enter between quotes, like this:
`yt-dlp "URL"`. I doubt that this will fix this issue, but it's still recommended, otherwise you might have problems with URLs that have one or more `&` symbols in them (such as your example URL)

**Comment by shawn8888** [comment]
@gamer191  adding quotes doesn't fix it.
@pukkandan 
It's funny because the DRM protection was introduced 2 days ago.
If yt-dlp doesn't support CTVNews any more, Is there any other tools out there does?
