### ISSUE TITLE
why do I get incomplete download fragments despite my configurations?

### ISSUE THREAD

**Issue by LovelyBloom** [yt-dlp/yt-dlp#3650]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

why do I get incomplete download fragments despite my configurations?
I have solid connection and that's not the issue and:

[this is my config](https://pastebin.com/Scm6WtVS)

and I have ffmpeg, ffprobe, aria2c and AtomicParsley in path

what is causing this and if an adjustment to the config file will fix this how do I do it?

**Comment by pukkandan** [comment]
We can't read your mind or see your computer screen. We don't know what error you got or even what you are downloading... Show verbose logs!

**Comment by LovelyBloom** [comment]
But they come and go. I don't know when it will happen.
could it be there is something wrong with the config file?

# Version and Generic -v Output (Hope It Helps)
`[debug] Command-line config: ['-v']
[debug] User config "C:\Users\sakur\AppData\Roaming\yt-dlp\config.txt": ['-o', 'F:\\yt-dlp\\%(uploader)s/%(playlist)s/%(playlist_index)s - %(title)s.%(ext)s', '--compat-options', 'multistreams', '--compat-options', 'format-spec', '--format', 'bestvideo[ext=avc1]+bestaudio[ext=opus]/bestvideo[ext=mp4_dash]+bestaudio[ext=m4a_dash]/bestvideo[ext=mp4]+bestaudio[ext=m4a]/bestvideo+bestaudio/best', '--merge-output-format', 'mkv', '--concurrent-fragments', '8', '--retries', 'infinite', '--file-access-retries', 'infinite', '--fragment-retries', 'infinite', '--no-resize-buffer', '--downloader', 'http:aria2c', '--downloader', 'ftp:aria2c', '--downloader', 'aria2c', '--downloader-args', 'aria2c:--continue=true --check-integrity=true --enable-http-pipelining=true --max-connection-per-server=8 --enable-http-keep-alive=true --max-tries=15 --retry-wait=5  --timeout=10 --ca-certificate=ca-bundle.crt --log=F:\\yt-dlp\\aria2c\\log.txt', '--continue', '--cache-dir', 'F:\\yt-dlp\\cache-dir', '--embed-thumbnail', '--embed-subs', '--xattrs', '--embed-metadata']
[debug] Encodings: locale cp1256, fs utf-8, out utf-8, err utf-8, pref cp1256
[debug] yt-dlp version 2022.04.08 [7884ade] (win_exe)
[debug] Compatibility options: format-spec, multistreams
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.22000-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 5.0.1-full_build-www.gyan.dev (setts), ffprobe 5.0.1-full_build-www.gyan.dev
[debug] Optional libraries: brotli, certifi, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Usage: yt-dlp.exe [OPTIONS] URL [URL...]

yt-dlp.exe: error: You must provide at least one URL.
Type yt-dlp --help to see a list of all options.`

**Comment by LovelyBloom** [comment]
found it:
changed aria2c argument --max-tries from a positive integer to **--max-tries=0** meaning infinite tries

can we close this?
thanx

**Comment by LovelyBloom** [comment]
found it:
changed aria2c argument --max-tries from a positive integer to **--max-tries=0** meaning infinite tries

can we close this?
thanx
