### ISSUE TITLE
yt-dlp version issue.

### ISSUE THREAD

**Issue by stormlord44** [yt-dlp/yt-dlp#3653]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

Hi. I ran **sudo yt-dlp -U** a few minutes ago and I got this response

Latest version: **2022.03.08.1**, Current version: **2022.04.08**
yt-dlp is up to date (**2022.04.08**)

Version **2022.04.08** was installed on my Linux system using the same command. Was yt-dlp downgraded for some reason? Is there a problem with version **2022.04.08**? Do I need to downgrade to version **2022.03.08.1**?

Thank you.

**Comment by pukkandan** [comment]
The 04.08 release was not pulled. It appears to be some issue with GH. If it doesn't resolve itself in a day or two, I'll look into what else could be the issue

**Comment by gamer191** [comment]
@pukkandan IIRC it's possible to re-release it by visiting https://github.com/yt-dlp/yt-dlp/tags and clicking the 3 dots to the right of 2022.04.08, then clicking "create release"

**Comment by adithya-s-sekhar** [comment]
This seems fixed.

**Comment by MrRawes** [comment]
IIRC youtube-dl had the same issue with showing version 2021.06.06 instead of 2021.12.17

**Comment by gamer191** [comment]
> IIRC youtube-dl had the same issue with showing version 2021.06.06 instead of 2021.12.17

https://github.com/ytdl-org/youtube-dl/issues/30825

**Comment by nicolaasjan** [comment]
And again version 2022.03.08.1 is shown as the latest...

**Comment by coletdjnz** [comment]
Some other repos have been reporting similar issues too
https://github.com/Genymobile/scrcpy/issues/3253
https://github.com/helm/helm/issues/10947

**Comment by pukkandan** [comment]
Doesn't seem to be happening anymore
