### ISSUE TITLE
[vk.com] Some videos are not downloadable

### ISSUE THREAD

**Issue by Offert4324** [yt-dlp/yt-dlp#3656]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.04.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Description

https://vk.com/video156436801_456241609
https://vk.com/video156436801_456241224

The above links are not downloadable, showing the same error.
This does not apply to all vk.com videos.

### Verbose log

```shell
[debug] Command-line config: ['--verbose', '-f', 'b', 'https://vk.com/video156436801_456241609']
[debug] Encodings: locale cp949, fs utf-8, out utf-8, err utf-8, pref cp949
[debug] yt-dlp version 2022.04.08 [7884ade65]
[debug] Python version 3.10.4 (CPython 64bit) - Windows-10-10.0.22000-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 5.0.1-essentials_build-www.gyan.dev (setts), ffprobe 5.0.1-essentials_build-www.gyan.dev
[debug] Optional libraries: brotli, certifi, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [vk] Extracting URL: https://vk.com/video156436801_456241609
[vk] 156436801_456241609: Downloading JSON metadata
ERROR: [vk] Error
  File "C:\Users\lg\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\extractor\common.py", line 641, in extract
    ie_result = self._real_extract(url)
  File "C:\Users\lg\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\extractor\vk.py", line 331, in _real_extract
    payload = self._download_payload('al_video', video_id, data)
  File "C:\Users\lg\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\extractor\vk.py", line 65, in _download_payload
    raise ExtractorError(clean_html(payload[0][1:-1]), expected=True)
```

**Comment by pukkandan** [comment]
It appears login is needed to access the video. Pass username+password to yt-dlp

**Comment by Offert4324** [comment]
Login didn't work, but then I tried with cookies and it worked. Thanks anyways.
