### ISSUE TITLE
Piped: More instances support

### ISSUE THREAD

**Issue by mizzunet** [yt-dlp/yt-dlp#3661]
### Checklist

- [X] I'm reporting a site feature request
- [X] I've verified that I'm running yt-dlp version **2022.04.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Example URLs

https://piped.silkky.cloud
https://piped.tokhmi.xyz
https://piped.moomoo.me
https://il.ax
https://piped.mha.fi
https://piped.mint.lgbt
https://piped.privacy.com.de

### Description

These are some other instances of Piped. `yt-dlp` doesn't play from these but only from the official instance https://piped.kavin.rocks

Would you be add support for these URLs?

Thanks

### Verbose log

```shell
[debug] Command-line config: ['https://piped.tokhmi.xyz/watch?v=QD9H353AzAA', '-vU']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.04.08 [7884ade65]
[debug] Python version 3.10.4 (CPython 64bit) - Linux-5.15.37-1-lts-x86_64-with-glibc2.35
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 5.0 (setts), ffprobe 5.0
[debug] Optional libraries: brotlicffi, certifi, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.04.08, Current version: 2022.04.08
yt-dlp is up to date (2022.04.08)
[debug] [generic] Extracting URL: https://piped.tokhmi.xyz/watch?v=QD9H353AzAA
[generic] watch?v=QD9H353AzAA: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] watch?v=QD9H353AzAA: Downloading webpage
[generic] watch?v=QD9H353AzAA: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://piped.tokhmi.xyz/watch?v=QD9H353AzAA
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1408, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1478, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 641, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.10/site-packages/yt_dlp/extractor/generic.py", line 4039, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://piped.tokhmi.xyz/watch?v=QD9H353AzAA
```

**Comment by jakoblm** [comment]
Would you also add the following instance?
https://piped.sp-codes.de/

**Comment by pc00per** [comment]
nstances are closing & opening every month so far. In this pace, yt-dlp kinda can't keep up with em. Some form of other workaround needs to be discovered.
I'm currently using https://api-piped.shimul.me/ & it doesn't work. But there are lot more others, refer https://github.com/TeamPiped/Piped/wiki/Instances
