### ISSUE TITLE
[Niconico] Merging niconico extractor from animelover1984/youtube-dl

### ISSUE THREAD

**Issue by rivke41levp656** [yt-dlp/yt-dlp#367]
Since yt-dlp no longer supports python2, is it possible to merge https://github.com/animelover1984/youtube-dl 's niconico live implementation now? I think your original reason for not wanting to was python2 support.

**Comment by pukkandan** [comment]
> I think your original reason for not wanting to was python2 support.

Yes, that was part of the reason. But even with py3.6 being the minimum version, there are a few issues
1. The danmaku to subs code is under GPL3 and thus cannot be copy-pasted. It can perhaps be added as an optional dependancy
2. There must be no required dependancies, only optional ones. This can be achieved by wrapping the import in `try...except` and checking for its availability before use.
3. A lot of the niconico extractor was modified in yt-dlp independently (See #49). We will need to compare and fix conflicts for these
4. There seems to be a lot of obsolete code (like the rtmp download)

I am not familiar enough with the extractor to fix these issues myself

**Comment by Lesmiscore** [comment]
So the remaining is conversion and Niconico Live?

**Comment by pukkandan** [comment]
Yeah

Idk if there is any point in adding a dependency for danmaku conversion. Someone can easily implement https://github.com/m13253/danmaku2ass as a custom PP (or even just use it with --exec)

The main thing remaining is nico live
