### ISSUE TITLE
[kicker.de] site support request

### ISSUE THREAD

**Issue by artcs** [yt-dlp/yt-dlp#3670]
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.04.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Germany

### Example URLs

- Single Video: https://www.kicker.de/rose-erklaert-das-bringt-schlotterbeck-dem-bvb-901149/video

### Description

Site www.kicker.de has some short interview videos (kicker.tv), which seem to be delivered by dailymotion. All are playable in a browser but fail to download with yt-dlp. Maybe georestricted (<script src="https://geo.dailymotion.com/libs/player/xslz.js"></script>). No idea how to check, if there is DRM involved...

### Verbose log

```shell
$ yt-dlp --ignore-config --verbose https://www.kicker.de/rose-erklaert-das-bringt-schlotterbeck-dem-bvb-901149/video
[debug] Command-line config: ['--ignore-config', '--verbose', 'https://www.kicker.de/rose-erklaert-das-bringt-schlotterbeck-dem-bvb-901149/video']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.04.08 [7884ade65]
[debug] Python version 3.9.10 (CPython 64bit) - macOS-10.13.6-x86_64-i386-64bit
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.4 (setts), ffprobe 4.4
[debug] Optional libraries: brotli, certifi, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [generic] Extracting URL: https://www.kicker.de/rose-erklaert-das-bringt-schlotterbeck-dem-bvb-901149/video
[generic] video: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] video: Downloading webpage
[generic] video: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://www.kicker.de/rose-erklaert-das-bringt-schlotterbeck-dem-bvb-901149/video
Traceback (most recent call last):
  File "/Users/whoever/Library/Python/3.9/lib/python/site-packages/yt_dlp/YoutubeDL.py", line 1408, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/whoever/Library/Python/3.9/lib/python/site-packages/yt_dlp/YoutubeDL.py", line 1478, in __extract_info
    ie_result = ie.extract(url)
  File "/Users/whoever/Library/Python/3.9/lib/python/site-packages/yt_dlp/extractor/common.py", line 641, in extract
    ie_result = self._real_extract(url)
  File "/Users/whoever/Library/Python/3.9/lib/python/site-packages/yt_dlp/extractor/generic.py", line 4039, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.kicker.de/rose-erklaert-das-bringt-schlotterbeck-dem-bvb-901149/video
```

**Comment by HobbyistDev** [comment]
I found an url that not get geo-blocked : https://www.kicker.de/pogba-dembel-co-die-top-11-der-abloesefreien-spieler-905049/video
It seems url that OP give not avaiable anymore (The url give error 404)

**Comment by HobbyistDev** [comment]
This site use dailymotion. In this url (https://www.kicker.de/pogba-dembel-co-die-top-11-der-abloesefreien-spieler-905049/video), we can get the from `div class="kick__js-video-player"` in that tag, we can found `data-dmprivateid=<video_id>` attribute and then we can pass it as `https://www.dailymotion.com/video/<video_id>` in `dailymotion.py`

**Comment by artcs** [comment]
Thank you both! Works flawlessly now.
