### ISSUE TITLE
Generate random cookies

### ISSUE THREAD

**Issue by sulyi** [yt-dlp/yt-dlp#3673]
### Checklist

- [X] I'm reporting a feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.04.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

I'd like it if name and/or value of the cookie is not provided in `InfoExtractor._set_cookie` these parameters generated randomly.

**Comment by pukkandan** [comment]
This is not needed just for https://github.com/yt-dlp/yt-dlp/pull/3624 imo. If such a function becomes useful for other extractors, it can eventually be moved into utils.

Also, there is no reason for this to be a separate issue. This is simply a implementation detail of #3624, and can just be discussed in that PR
