### ISSUE TITLE
[enhancement] Add cookie as a string

### ISSUE THREAD

**Issue by bbilly1** [yt-dlp/yt-dlp#3674]
### Checklist

- [X] I'm reporting a feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.04.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

We have recently implemented cookie import into our project *Tube Archivist*. How that is currently implemented in *yt-dlp* makes sense for a command line software, passing the cookie file as an argument. 

But for an embedded implementation, it would be very beneficial if the cookie could also be passed as a string. This would allow that to be stored in a database instead of a file, which makes that much easier to handle as the application wouldn’t have to depend on user created files. Has also the additional security benefit, that this cookie file doesn’t have to stay on the filesystem as a plain text file and can be protected better in the application database.

I see two approaches, how this could be done:
1. Handle that automatically with the *cookiefile* option and detect that this value is not a file but a string.
2. Add an additional option, for example *cookiestring* where this could be passed as a value.

Thank you for your consideration.

**Comment by pukkandan** [comment]
Is `--add-header cookie:...` not sufficient?

**Comment by pukkandan** [comment]
If you are using the enbedded API, you can also create a `MozillaCookieJar` and inject it into `YoutubeDL`

```py
cookiejar = MozillaCookieJar(...)
with YoutubeDL(...) as ydl:
    ydl.cookiejar = cookiejar
    ...
```

**Comment by bbilly1** [comment]
Thanks for your quick reply. I've been trying and failing to get this to work. This is what I have done so far:

Exporting the cookie into a *Netscape HTTP Cookie File* called *cookie.txt* and appending this as *cookiefile* works as expected to extract your *watch later* videos for example:

```python
url = "https://www.youtube.com/playlist?list=WL"
yt_obs = {
    "skip_download": True,
    "extract_flat": True,
    "cookiefile": "cookie.txt",
}
response = yt_dlp.YoutubeDL(yt_obs).extract_info(url)
```

To use `http_headers`, I assume that expects the cookie as a [name-value list](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cookie)?

So quick and dirty parser:
```python
def cookie_converter(netscape_cookie):
    """convert netscape cookie to cookie-list name value string"""

    cookie_str = str()
    lines = [i for i in netscape_cookie.split('\n') if ".youtube" in i]
    for line in lines:
        name, value = line.split("\t")[5:7]
        cookie_str = f"{cookie_str}{name}={value}; "

    return cookie_str.rstrip("; ")
```

Then adding this to yt_obs like so:
```python
yt_obs = {
    "skip_download": True,
    "extract_flat": True,
    "verbose": True,
    "http_headers": {"Cookie": cookie_str},
}
```
This will throw a `DownloadError: ERROR: [youtube:tab] WL: YouTube said: The playlist does not exist.` indicating that this didn't actually pass the cookie or that there is another problem.

It's very much possible that I've missed something obvious but I'm not sure where I went wrong and I'd appreciate any help. I'd prefere to be able to do this in *yt_obs* instead of your other suggestion of injecting a cookiejar into the *YoutubeDL* context manager as so far all configurations happen in *yt_obs*.

**Comment by coletdjnz** [comment]
Multiple Cookie headers is not allowed in HTTP/1.1 iirc. You'll need to add the cookie to the cookiejar

We could maybe look at adding a cookies opt (dict) which merges into the internal cookiejar. something similar to how requests handles it. Then we could add a --add-cookie CLI arg

**Comment by bbilly1** [comment]
Thank you for looking into this. As far as I can tell, this won't add multiple headers, just one header with a list of cookies, or is yt-dlp is doing that under the hood? Take this example Netscape cookie:
```
.youtube.com	TRUE	/	FALSE	1648457338	cookiename1	cookievalue1
.youtube.com	TRUE	/	FALSE	1648459698	cookiename2	cookievalue2
.youtube.com	TRUE	/	FALSE	1648460233	cookiename3	cookievalue3
```
parsed would look like this:
```
cookiename1=cookievalue1; cookiename2=cookievalue2; cookiename3=cookievalue3
```
which would make yt_obs:
```python
yt_obs = {
    "skip_download": True,
    "extract_flat": True,
    "http_headers": {"Cookie": "cookiename1=cookievalue1; cookiename2=cookievalue2; cookiename3=cookievalue3"},
}
```
adding one *Cookie* key with the parsed string to the *http_headers* key. This would match the format as for example here [Document.cookie](https://developer.mozilla.org/en-US/docs/Web/API/Document/cookie#notes).

**Comment by pukkandan** [comment]
Try this:
```py
cookies = {
    'SAPISID': 'xxx',
    ...
}

from http.cookiejar import Cookie
from yt_dlp import YoutubeDL

with YoutubeDL({'debug_printtraffic': True}) as ydl:
    for key, value in cookies.items():
        ydl.cookiejar.set_cookie(Cookie(
            name=key, value=value, domain='.youtube.com', 
            version=0, port=None, path='/', secure=True, expires=None, discard=False,
            comment=None, comment_url=None, rest={'HttpOnly': None},
            domain_initial_dot=True, port_specified=False, domain_specified=True, path_specified=False))
    response = ydl.extract_info('WL', download=False)
```

**Comment by bbilly1** [comment]
Thank you very much for providing this example. Trying to replicate this with my cookie resulted in a **HTTP Error 413** for me:
```
WARNING: [youtube:tab] Unable to download webpage: HTTP Error 413: Request Entity Too Large (caused by <HTTPError 413: 'Request Entity Too Large'>);
```

Not sure how this is different to the *cookiefile* yt_obs approach as I assume this will create the same request at the end?

All in all, the cookiejar injection into the YoutubeDL context manager is a much less elegant approach than doing this in **yt_obs** and it makes more sense to have all configurations happening in one place. 

Do you think that would make sense to implement this in yt_obs?

**Comment by pukkandan** [comment]
> WARNING: [youtube:tab] Unable to download webpage: HTTP Error 413: Request Entity Too Large (caused by <HTTPError 413: 'Request Entity Too Large'>);

This is likely an issue in your parsing of the cookies. Maybe you added all cookies of all sites under the `.youtube.com` domain?

> Do you think that would make sense to implement this in yt_obs?

For this, we will need to use a standardized format (say, netscape). So if you want to save the cookies in a database, you will have to convert the data to and from this format anyway. I believe adding `Cookies` is easier than doing that

**Comment by bbilly1** [comment]
I'm using a slight adaptation from the example above:
```python
def build_cookies_dict(netscape_cookie):
    """create cookie dict"""

    cookies = {}
    lines = [i for i in netscape_cookie.split('\n') if ".youtube" in i]
    for line in lines:
        name, value = line.split("\t")[5:7]
        cookies.update({name: value})

    return cookies
```
Only adding *.youtube* cookies. Looks like there are 140 of them. But with the *cookiefile* option this works fine and doesn't throw the 413 error.

> For this, we will need to use a standardized format (say, netscape). 

That is fine, it's just a long multi line string. The application would have a ingest functionality storing that string as is, there are a bunch of browser extensions out there that can create that file. 

Could also be JSON, key value pairs that match the name-value from the cookie? That might be a little bit more compact as it doesn't need the rest of the 7 fields of a cookie line. Either way, as long as it's documented what format is expected, the application can adapt to the standard. And crucially, all configuration could be done in the yt_obs dict.

**Comment by pukkandan** [comment]
We can allow a `StringIO` to be passed as the `cookiefile` instead of filename. This implies the stringIO should be in Netscape format. Try out https://github.com/pukkandan/yt-dlp-dev/tree/features/cookies-stream and let me know

Test code:
```py
from io import StringIO
from yt_dlp import YoutubeDL

# For demonstration purpose. The data can be generated in any way
contents = open('cookies.txt').read()

cookies = StringIO(contents)
with YoutubeDL({'cookiefile': cookies}) as ydl:
    ydl.extract_info('WL', download=False)

# If cookies were modified during extraction, that change is reflected in the object
print(contents.getvalue())
```

---

> And crucially, all configuration could be done in the yt_obs dict.

btw, this already isn't the case. Some of the advanced functionality of the API (Eg: custom PPs) cannot be used with just the params

**Comment by bbilly1** [comment]
Excellent, thank you for implementing this so fast. That worked without any issues!

Then I assume the modified cookie be used for next requests? Or what would be the best approach?

**Comment by pukkandan** [comment]
Yes, it is recommended to use the modified cookies for subsequent downloads. The original cookies, if left unmodified, will expire after a while.

**Comment by karim23657** [comment]
just use this, very easy `ydl.cookiejar.load`    :

```python

from yt_dlp import YoutubeDL
def get_info(url):
    with YoutubeDL() as ydl:
        ydl.cookiejar.load('cookies.txt', ignore_discard=True, ignore_expires=True)
        return ydl.sanitize_info(ydl.extract_info(url, download=False))
```
