### ISSUE TITLE
Re-enable file URLs

### ISSUE THREAD

**Issue by jxu** [yt-dlp/yt-dlp#3675]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

Is it possible to force yt-dlp to read a file with generic extractor like it were a url? I have a RSS XML file and file:// prefix is forbidden, so I used a local python http.server as a workaround.

**Comment by pukkandan** [comment]
`file://` is disabled due to security concerns

> so I used a local python http.server as a workaround.

Doesn't that work? So what is the question again?

**Comment by jxu** [comment]
Title. How do I get it to read a local podcast XML file? Is that just disabled due to file://

**Comment by jxu** [comment]
Also I don't see how parsing and downloading from a file on disk is more dangerous than parsing and downloading from some URL online

**Comment by coletdjnz** [comment]
We could add a switch to enable it (with a warning).

See https://github.com/ytdl-org/youtube-dl/issues/8227 for why it was disabled

**Comment by jxu** [comment]
The limitation does not prevent malicious URLs and is pretty easy to circumvent, and shouldn't be an issue if yt-dlp not run with elevated permissions (which it should never need to be). I can open a PR but if you can make a quick fix with like `--enable-file-url` then that would be nice

**Comment by pukkandan** [comment]
> The limitation does not prevent malicious URLs hosted online and is pretty easy to circumvent with a local server

It does not appear you have understood the problem. Read the linked issues again.

That said, an option to enable it should be fine. PR is welcome

**Comment by gamer191** [comment]
> We could add a switch to enable it (with a warning).

Why would we need a warning? You'd expect a server administrator to be smart enough not to enable it, and afaik it doesn't pose any security risks to regular users (I could be wrong)

**Comment by pukkandan** [comment]
> Why would we need a warning? You'd expect a server administrator to be smart enough not to enable it, and afaik it doesn't pose any security risks to regular users (I could be wrong)

I agree. Passing switches from untrusted sources is already not safe due to `--exec` and similar. The original issue is a vulnerability because it works with just the URL. As long as the new switch is not enabled by default, there is no issue and no warning is necessary

**Comment by gamer191** [comment]
> afaik it doesn't pose any security risks to regular users (I could be wrong)

Now that I think about it though, I wonder if it would be possible for websites to maliciously gain access to yt-dlp's output. I doubt it, but I'm not 100% sure.

Also, I wonder if this could potentially be a privilege escalation vulnerability (which isn't necessarily enough reason to not do it)

**Comment by coletdjnz** [comment]
I have added an option to enable file urls in #2861
