### ISSUE TITLE
incorrect final URL -- channel "m"

### ISSUE THREAD

**Issue by Shaun-F** [yt-dlp/yt-dlp#3676]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.04.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Switzerland

### Description

attempting to download the following playlist:

"https://www.youtube.com/playlist?list=PLmz7AKJLwXIO5DpCgJABJ7GoFM72Xph7G"

with the command 

yt-dlp --cookies-from-browser firefox --yes-playlist --verbose --continue --extract-audio --embed-thumbnail --xattrs --output "%(title)s.%(ext)s" "https://www.youtube.com/playlist\?list\=PLmz7AKJLwXIO5DpCgJABJ7GoFM72Xph7G"

'FINAL URL' displayed in the terminal output following issuance of the above command is incorrect and points to some youtube channel called "m", which is completely different from the requested playlist's channel. Moreover, the 'FINAL URL' seems to contain the requested URL (the one listed above), but random ASCII characters have been inserted at random points.

command successfully completes but has downloaded 0 files from the incorrect channel. 

Desired behavior is to download to disk the complete playlist from the channel pointed to by the above URL.

OS: Ubuntu 21.10 impish
Kernel: x86_64 Linux 5.13.0-40-generic
Shell: zsh 5.8
DE: GNOME 40.0

### Verbose log

```shell
[debug] Command-line config: ['--cookies-from-browser', 'firefox', '--yes-playlist', '--verbose', '--continue', '--extract-audio', '--embed-thumbnail', '--xattrs', '--output', '%(title)s.%(ext)s', 'https://www.youtube.com/playlist\\?list\\=PLmz7AKJLwXIO5DpCgJABJ7GoFM72Xph7G']
[Cookies] Extracting cookies from firefox
[debug] Extracting cookies from: "/home/<user>/.mozilla/firefox/pzev2zkg.default-release-3/cookies.sqlite"
[Cookies] Extracted 1391 cookies from firefox
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.04.08 [7884ade65] (zip)
[debug] Python version 3.9.7 (CPython 64bit) - Linux-5.13.0-40-generic-x86_64-with-glibc2.34
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.4 (setts), ffprobe 4.4, rtmpdump 2.4
[debug] Optional libraries: brotli, certifi, secretstorage, sqlite
[debug] Proxy map: {}
[debug] [generic] Extracting URL: https://www.youtube.com/playlist\?list\=PLmz7AKJLwXIO5DpCgJABJ7GoFM72Xph7G
[generic] playlist\?list\=PLmz7AKJLwXIO5DpCgJABJ7GoFM72Xph7G: Requesting header
[redirect] Following redirect to https://consent.youtube.com/m?continue=https%3A%2F%2Fwww.youtube.com%2Fplaylist%255C%3Flist%255C%3DPLmz7AKJLwXIO5DpCgJABJ7GoFM72Xph7G%26cbrd%3D1&gl=CH&m=0&pc=yt&uxe=eomty&hl=en&src=1
[debug] [youtube:tab] Extracting URL: https://consent.youtube.com/m?continue=https%3A%2F%2Fwww.youtube.com%2Fplaylist%255C%3Flist%255C%3DPLmz7AKJLwXIO5DpCgJABJ7GoFM72Xph7G%26cbrd%3D1&gl=CH&m=0&pc=yt&uxe=eomty&hl=en&src=1
[youtube:tab] m: Downloading webpage
[youtube:tab] A channel/user page was given. All the channel's videos will be downloaded. To download only the videos in the home page, add a "/featured" to the URL
[debug] [youtube:tab] Final URL: https://www.youtube.com/m/videos?continue=https%3A%2F%2Fwww.youtube.com%2Fplaylist%255C%3Flist%255C%3DPLmz7AKJLwXIO5DpCgJABJ7GoFM72Xph7G%26cbrd%3D1&gl=CH&m=0&pc=yt&uxe=eomty&hl=en&src=1
[download] Downloading playlist: m - Videos
[debug] Skipping writing playlist thumbnail
[youtube:tab] playlist m - Videos: Downloading 0 videos
[download] Finished downloading playlist: m - Videos
```

**Comment by pukkandan** [comment]
> [debug] [generic] Extracting URL: https://www.youtube.com/playlist\?list\=PLmz7AKJLwXIO5DpCgJABJ7GoFM72Xph7G

Your URL is quoted wrong
