### ISSUE TITLE
how to use build in format selector with ytdlp embedded

### ISSUE THREAD

**Issue by crbyxwpzfl** [yt-dlp/yt-dlp#3679]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

first off all thanks for this relly great advanced verion of ytdl. really love it!

in short I would like to convert 
`yt-dlp -f 'ba,bv/b' -o "filename-vc:%(vcodec)s-ac:%(acodec)s.%(ext)s"' --print filename --print urls  URL`
into a embedded version.
I got the filename part but still want to get the url.
Is there a fuction like `ydl.prepare_filename()` for the format selector?

In advance feel free to close this issue at any point. this problem is pobably not very common and does not need a lot of attetntion. just asking for tips here.

I have a python script passing the extracted url and generated filename to aria2 daemon.
```python
URL = 'https://www.youtube.com/watch?v=BaW_jenozKc'
NAME = "test"
cmd = ['yt-dlp', '-f', 'ba,bv/b', '-o', f'"{NAME}-vc:%(vcodec)s-ac:%(acodec)s.%(ext)s"', '--print', 'filename', '--print', 'urls', URL]
process = subprocess.Popen(cmd, universal_newlines=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
# pass process.stdout lines to aria2 daemon
```
I would like to use ytdlp embedded insted to get the url like ``-f 'ba,bv/b'``
Since there is the option implace for`ydl.download()` like
`ydl_opts = {'format': 'bv,ba/b',}`
Is ther a way to pass `ydl.extract_info()` the same option to just get the desired urls?

There is the option of `simulate: True` in combination with `forceurl: Ture` and `forcefilename: True`  
But this just prints to stdout as far as I see.
Plus `help(yt_dlp.YoutubeDL)` says  `forceurl:` and `forcefilename:` are Deprecated.

`ydl.prepare_filename(info_dict, outtmpl='filename-vc:%(vcodec)s-ac:%(acodec)s.%(ext)s'))` does exactly what I want for the filename.
But still how do I avoid writing my own selector? Is there a fuction like `ydl.prepare_filename()` for the format selector?

this is my current selector. this wokrs somewhat ok
```python
#Selector works fine with example url 'https://www.youtube.com/watch?v=BaW_jenozKc'
ydl_opts = {}
with yt_dlp.YoutubeDL(ydl_opts) as ydl:
    info = ydl.extract_info(URL, download=False) #get info
    #print(json.dumps(ydl.sanitize_info(info), indent=4 )) #prints serialised json info for debuging
    
    print(ydl.list_formats(info)) #lists formats to check if correct format was choosen by selector
    
    mydict = ydl.sanitize_info(info) #convert info to dict
    #print(type(mydict))                  #confirm type dict for debuging
    #for key in mydict.keys() :         #print all keys of dict  for debuging
    #    print (key)
    
    formatslist = mydict['formats']        #key 'formats' in mydict has value of type list containing all formats as dicts
    #print(formatslist[-1]['format_id'])   #e.g. print key 'format_id' of last dict format in list

    #this selector has its problems e.g. some reddit urls
    revlist = formatslist[::-1] #reverse list so formats are sorted best to worst from top to bottom  
    if revlist[1].get('vcodec'):
        best_video = next(f for f in revlist if f['vcodec'] != 'none' and f['acodec'] == 'none')
        print(best_video['format_id'])
        best_audio = next(f for f in revlist if f['acodec'] != 'none' and f['vcodec'] == 'none')
        print(best_audio['format_id'])
    else:
        print("no best audio only or video only avalible just best overall is", revlist[0]['format_id'])
```

**Comment by pukkandan** [comment]
You can just pass `format`, like in the example https://github.com/yt-dlp/yt-dlp#extract-audio

**Comment by crbyxwpzfl** [comment]
thanky very much for your quick response and tips!
I tried to use `ydl.build_format_selector('ba,bv/b')` but I think I am not using it right.
```py
selected_url = ydl.build_format_selector( 'ba,bv/b' )
print(selected_url)
```
output:`<function YoutubeDL.build_format_selector.<locals>._build_selector_function.<locals>.selector_function at 0x102cbf0d0>`

how do I youse this right? how do I retrive a url from this function?
I feel like this is a stupid question. I dont know much python sorry

**Comment by pukkandan** [comment]
> You can just pass format, like in the example [yt-dlp/yt-dlp#extract-audio](https://github.com/yt-dlp/yt-dlp#extract-audio).

Did you try this first? Is there any reason that is not sufficient for you?

> so this builds a selector for me righ? But how do I now use this Selector?

I just showed you in the above comment https://github.com/yt-dlp/yt-dlp/blob/d7a1aa00c65dd516c70c10bd070113b87b96d1c8/yt_dlp/YoutubeDL.py#L2611-L2619

**Comment by crbyxwpzfl** [comment]
OK got it! thank you for your help!
```py
myformat_selector = ydl.build_format_selector('b')
selected_format_as_list = list( myformat_selector( { 'formats': myformats_as_list } ) ) 
print(selected_format[0]['url']) #print first item in list, wich is a dict, only print ['url']  
```
output:`https...`

> 
> Did you try this first? Is there any reason that is not sufficient for you?
> 
I want to pass the extracted url to aria2 daemon to handle the download.
This example shows how a download with ytdl embedded would work. or am I missing something form that example?

just a follow up question feel free to ignore it
what are the `'has_merged_format': ...` and `'incomplete_formats': ....` parameters for?
I only passed `'formats': myformats_as_list`

**Comment by pukkandan** [comment]
> I want to pass the extracted url to aria2 daemon to handle the download.
This example shows how a download with ytdl embedded would work. or am I missing something form that example?

Just replace the `download` with `extract_info`

> what are the 'has_merged_format': ... and 'incomplete_formats': .... parameters for?

There is some special handling for `best` under certain situations. These parameters are needed for that

**Comment by crbyxwpzfl** [comment]
thank you verry much again! have a nice day!
