### ISSUE TITLE
[Feature Request] Scoop Support

### ISSUE THREAD

**Issue by djfdat** [yt-dlp/yt-dlp#368]
- [x] I'm reporting a feature request
- [x] I've verified that I'm running yt-dlp version **2021.05.20**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description
Could this be added to the [Scoop](https://scoop.sh) package manager for Windows to handle installs?

**Comment by pukkandan** [comment]
See: #330

**Comment by Ashish0804** [comment]
https://github.com/ScoopInstaller/Main/pull/2249

If this get's merged then I'll add the command to README.

**Comment by pukkandan** [comment]
@Ashish0804 I see that the version is hard-coded. Does scoop not have support for auto-updating? If not, then this will not be added to the readme since I will not have full control over what version is available. This is a similar situation to various UNIX packages

**Comment by pukkandan** [comment]
hm.. looks like auto-update is possible
https://github.com/ScoopInstaller/Main/blob/master/bucket/youtube-dl.json

**Comment by Ashish0804** [comment]
> @Ashish0804 I see that the version is hard-coded. Does scoop not have support for auto-updating? If not, then this will not be added to the readme since I will not have full control over what version is available. This is a similar situation to various UNIX packages
> 
> Edit: nvm, I see that there is auto-update

Afaik the hardcoded version is what will be installed
after that it can check version from github and auto update.
The only catch is the hardcoded version. Someone will have to update it once in a while for people who are using it out of the box.


So either we will have to add a note in the readme `[Warning] Version in scoop maybe outdated.` or add some check in yt-dlp to automatically warn when a old version is being used.

**Comment by pukkandan** [comment]
If a new installation method is to be added to the readme, it **must** have some **automated** mechanism to always point to the latest version and to ensure that the installation specs are approved. If you take PIP as an example, build.yml automatically creates an up to date package for pip on every release and, only the admins of the package (ie. me manually, or using the PyPI token I've generated for the repo) can push a release, thus ensuring both conditions.

Scoop on the other hand seems to not only require a manual update of the version, but I have no control whether any changes are made to the manifest.

---

The second point can be adressed by having a sha2 test in the build.yml that looks something like this (untested):

```yaml
    - name: Test scoop package
    - env:
        SHA2_SCOOP: 'sha-of-manifest-goes-here'
      run: |
        sha=$(curl -sL "https://raw.githubusercontent.com/ScoopInstaller/Main/master/bucket/yt-dlp.json" | sha256sum - | awk '{print $1}');
        if [ $sha != ${{env:SHA2_SCOOP}} ];
          then exit 1;
        fi
```

This would make sure that I get notified if/when the manifest changes. Then I can manually review the changes and edit the hard-coded SHA2

---

After some testing. I can think of 2 ways to ensure that the latest version is installed

1. Use `post_install` to update

```json
{
    "version": "2021.06.01",
    "description": "A youtube-dl fork with lots of additional features and fixes",
    "homepage": "https://github.com/yt-dlp/yt-dlp",
    "license": "Unlicense",
    "suggest": {
            "vcredist": "extras/vcredist2010", // Should this be depends?
            "FFmpeg": [
                "ffmpeg",
                "ffmpeg-nightly"
            ]
    },
    "architecture": {
        "64bit": {
            "url": "https://github.com/yt-dlp/yt-dlp/releases/download/2021.06.01/yt-dlp.exe",
            "bin": "yt-dlp.exe",
            "hash": "0c33e4f06104fd9f5989a54dcc5cdac65259d042eac72e537bc3a38b0e0bf7e9",
            "autoupdate": {
                "url": "https://github.com/yt-dlp/yt-dlp/releases/download/$version/yt-dlp.exe"
            },
        },
        "32bit": {
            "url": "https://github.com/yt-dlp/yt-dlp/releases/download/2021.06.01/yt-dlp_x86.exe",
            "bin": [["yt-dlp_x86.exe", "yt-dlp"]],
            "hash": "xxx",
            "autoupdate": {
                "url": "https://github.com/yt-dlp/yt-dlp/releases/download/$version/yt-dlp_x86.exe"
            },
        }
    },
    "post_install": "yt-dlp -U",
    "checkver": "github",
    "autoupdate": { // I am not sure if this can be split b/w architecture and here
        "hash": {
            "url": "$baseurl/SHA2-256SUMS"
        }
    }
}
```

OR

2. Don't actually hardcode the version info. I am not sure what scoop's policies are on this though

```json
{
    "version": "latest",
    "description": "A youtube-dl fork with lots of additional features and fixes",
    "homepage": "https://github.com/yt-dlp/yt-dlp",
    "license": "Unlicense",
    "suggest": {
            "vcredist": "extras/vcredist2010",
            "FFmpeg": [
                "ffmpeg",
                "ffmpeg-nightly"
            ]
    },
    "architecture": {
        "64bit": {
            "url": "https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp.exe",
            "bin": "yt-dlp.exe"
        },
        "32bit": {
            "url": "https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp_x86.exe",
            "bin": [["yt-dlp_x86.exe", "yt-dlp"]]
        }
    }
}
```

**Comment by Ashish0804** [comment]
> If a new installation method is to be added to the readme, it **must** have some **automated** mechanism to always point to the latest version and to ensure that the installation specs are approved. If you take PIP as an example, build.yml automatically creates an up to date package for pip on every release and, only the admins of the package (ie. me manually, or using the PyPI token I've generated for the repo) can push a release, thus ensuring both conditions.
> 
> Scoop on the other hand seems to not only require a manual update of the version, but I have no control whether any changes are made to the manifest.
> 
> The second point can be adressed by having a sha2 test in the build.yml that looks something like this (untested):
> 
> ```yaml
>     - name: Test scoop package
>     - env:
>         SHA2_SCOOP: 'sha-of-manifest-goes-here'
>       run: |
>         sha=$(curl -sL "https://raw.githubusercontent.com/ScoopInstaller/Main/master/bucket/yt-dlp.json" | sha256sum - | awk '{print $1}');
>         if [ $sha != ${{env:SHA2_SCOOP}} ];
>           then exit 1;
>         fi
> ```
> 
> This would make sure that I get notified if/when the manifest changes. Then I can manually review the changes and edit the hard-coded SHA2
> 
> After some testing. I can think of 2 ways to ensure that the latest version is installed
> 
> 1. Use `post_install` to update
> 
> ```json
> {
>     "version": "2021.06.01",
>     "description": "A youtube-dl fork with lots of additional features and fixes",
>     "homepage": "https://github.com/yt-dlp/yt-dlp",
>     "license": "Unlicense",
>     "suggest": {
>             "vcredist": "extras/vcredist2010", // Should this be depends?
>             "FFmpeg": [
>                 "ffmpeg",
>                 "ffmpeg-nightly"
>             ]
>     },
>     "architecture": {
>         "64bit": {
>             "url": "https://github.com/yt-dlp/yt-dlp/releases/download/2021.06.01/yt-dlp.exe",
>             "bin": "yt-dlp.exe",
>             "hash": "0c33e4f06104fd9f5989a54dcc5cdac65259d042eac72e537bc3a38b0e0bf7e9",
>             "autoupdate": {
>                 "url": "https://github.com/yt-dlp/yt-dlp/releases/download/$version/yt-dlp.exe"
>             },
>         },
>         "32bit": {
>             "url": "https://github.com/yt-dlp/yt-dlp/releases/download/2021.06.01/yt-dlp_x86.exe",
>             "bin": [["yt-dlp_x86.exe", "yt-dlp"]],
>             "hash": "xxx",
>             "autoupdate": {
>                 "url": "https://github.com/yt-dlp/yt-dlp/releases/download/$version/yt-dlp_x86.exe"
>             },
>         }
>     },
>     "post_install": "yt-dlp -U",
>     "checkver": "github",
>     "autoupdate": { // I am not sure if this can be split b/w architecture and here
>         "hash": {
>             "url": "$baseurl/SHA2-256SUMS"
>         }
>     }
> }
> ```
> 
> OR
> 
> 1. Don't actually hardcode the version info. I am not sure what scoop's policies are on this though
> 
> ```json
> {
>     "version": "latest",
>     "description": "A youtube-dl fork with lots of additional features and fixes",
>     "homepage": "https://github.com/yt-dlp/yt-dlp",
>     "license": "Unlicense",
>     "suggest": {
>             "vcredist": "extras/vcredist2010",
>             "FFmpeg": [
>                 "ffmpeg",
>                 "ffmpeg-nightly"
>             ]
>     },
>     "architecture": {
>         "64bit": {
>             "url": "https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp.exe",
>             "bin": "yt-dlp.exe"
>         },
>         "32bit": {
>             "url": "https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp_x86.exe",
>             "bin": [["yt-dlp_x86.exe", "yt-dlp"]]
>         }
>     }
> }
> ```

2nd will not work since their guidelines require a proper hardcoded version.
1st can work with post_install 
also yes u can have arch in update.

**Comment by pukkandan** [comment]
> I don't think we need this "vcredist": "extras/vcredist2010", idk what it even is since the extras repo only shows first 10k files and i don't wanna clone a repo this big

The vc++2010 redistributable package which is a necessary requirement for yt-dlp to run. I took `"vcredist": "extras/vcredist2010"` from the `youtube-dl` manifest

**Comment by Ashish0804** [comment]
i didn't see it in other other packages. Also if it's necessary it shouldn't be in `suggest`.

Anyways I'll close my PR.
You can add the 1st one with few modifications.

**Comment by pukkandan** [comment]
> Anyways I'll close my PR. You can add the 1st one with few modifications.

Just modify ur PR. what's the point in closing and then me opening another

**Comment by Ashish0804** [comment]
> Just modify ur PR. what's the point in closing and then me opening another

I don't have a proper and robust way to test your changes.
Especially the `vcredist`.
I don't know what happens if someone installed it using the installer...does scoop pick as installed or what.
I can't test the 32bit version.

Also does the `-U` require special permissions? scoop may or may not be able to run it. 
I'll keep my PR open for now ig since it does the bare minimum.
Feel free to @ me with an updated manifest if u want me to commit or to close to PR if u plan on making one yourself.

**Comment by pukkandan** [comment]
Since this is not actually anything to do with yt-dlp itself and I cant do anything about it, I am closing this as `external-issue`. If you want support, you should follow @Ashish0804 's PR and ask the scoop devs instead of here. Despite closing this, you are free to continue any related discussion here

**Comment by pukkandan** [comment]
https://github.com/ScoopInstaller/Main/pull/2610
