### ISSUE TITLE
yt-dlp doesn't handle or display the proper string in log

### ISSUE THREAD

**Issue by bachig26** [yt-dlp/yt-dlp#3681]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.04.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

[Blank line if other language present instead of English in Logs #135](https://github.com/database64128/youtube-dl-wpf/issues/135)

**_I find that the yt-dlp doesn't provide the proper strings/ characters if the context is not English._**
Please also have look via the above link to see more of my explanation that I made in the [youtube-dl-wpf, yt-dlp GUI wrapper](https://github.com/database64128/youtube-dl-wpf).

![yt-dlp cmd output](https://user-images.githubusercontent.com/96393348/167301590-70ee77a1-aac9-40dd-8506-6a2d540275ba.jpg)

_**The korean characters are displayed as unknown context.**_

### Verbose log

```shell
C:\WINDOWS\system32>yt-dlp.exe -vU -f 137+140 https://www.youtube.com/watch?v=Y8JFxS1HlDo
[debug] Command-line config: ['-vU', '-f', '137+140', 'https://www.youtube.com/watch?v=Y8JFxS1HlDo']
[debug] User config "C:\Users\USER\AppData\Roaming\yt-dlp\config.txt": ['--downloader', 'aria2c', '--downloader-args', 'aria2c:-c -j 3 -x 3 -s 3 -k 1M']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.04.08 [7884ade] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg N-106796-ge561d16d49-20220503 (setts), ffprobe N-106796-ge561d16d49-20220503
[debug] Optional libraries: brotli, certifi, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.04.08, Current version: 2022.04.08
yt-dlp is up to date (2022.04.08)
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=Y8JFxS1HlDo
[youtube] Y8JFxS1HlDo: Downloading webpage
[youtube] Y8JFxS1HlDo: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[info] Y8JFxS1HlDo: Downloading 1 format(s): 137+140
[download] IVE 아이브 'LOVE DIVE' MV [Y8JFxS1HlDo].mp4 has already been downloaded
```

**Comment by pukkandan** [comment]
Your cmd is simply unable to display them. See https://stackoverflow.com/questions/56943271/displaying-unicode-characters-in-windows-10-cmd
