### ISSUE TITLE
External downloader filtering for better performance

### ISSUE THREAD

**Issue by crat0z** [yt-dlp/yt-dlp#3685]
### Checklist

- [X] I'm reporting a feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.04.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

When using the aria2c external downloader, downloading audio parts can be extremely slow. For example downloading 1.5MB audio file can take up to a minute. This is probably more of an issue with aria2c, and on a per video basis the user could just not use aria2c. But it is quite annoying to switch arguments especially when using a config file.

As far as I can tell, currently yt-dlp selects downloader with the protocol. I propose to allow for external download impls to filter via reading of info dict, e.g. 

```
--- a/yt_dlp/downloader/external.py
+++ b/yt_dlp/downloader/external.py
@@ -100,7 +100,11 @@ def supports(cls, info_dict):
 
     @classmethod
     def can_download(cls, info_dict, path=None):
-        return cls.available(path) and cls.supports(info_dict)
+        return cls.available(path) and cls.supports(info_dict) and cls._filter(info_dict)
+
+    def _filter(info_dict):
+        """ External downloaders can overwrite this to filter arbitrarily """
+        return True
 
     def _option(self, command_option, param):
         return cli_option(self.params, command_option, param)
@@ -260,6 +264,11 @@ def supports_manifest(manifest):
         check_results = (not re.search(feature, manifest) for feature in UNSUPPORTED_FEATURES)
         return all(check_results)
 
+    def _filter(info_dict):
+        if info_dict.get('extractor') == 'youtube' and 'audio only' in info_dict.get('format'):
+            return False
+        return True
+
     def _make_cmd(self, tmpfilename, info_dict):
         cmd = [self.exe, '-c',
                '--console-log-level=warn', '--summary-interval=0', '--download-result=hide',

```
I haven't run the tests but this vastly improves download speed for many videos. I think this could be tweaked a little bit more since it seems longer videos (with larger audio files) are not as fast as using aria2c.

**Comment by pukkandan** [comment]
Are you suggesting this specific filter be built-in? aria2c CAN download those files - so there is no reason to exclude it being selected as the downloader when the user has asked for it. So this won't be done.

We can however discuss some way to let the **user** have more control over the downloader
