### ISSUE TITLE
Other format options for time in file naming

### ISSUE THREAD

**Issue by viktorrauch** [yt-dlp/yt-dlp#3688]
### Checklist

- [X] I'm reporting a feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.04.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

Would be great to have other format options for upload time in the file names like "2022-05-09" or "2022 05 09".

At the moment it seems that only "20220509" is possible. Sadly Plex for example can't handle this.

**Comment by pukkandan** [comment]
See https://github.com/yt-dlp/yt-dlp#:~:text=Date/time%20Formatting
