### ISSUE TITLE
Can you use a "latest" folder on Github and put the latest builds there?

### ISSUE THREAD

**Issue by rgiuffre** [yt-dlp/yt-dlp#369]
Hello:
Seems like right now, the builds are in folders that use the current revision/version of the software.  I am trying to automate the process of downloading the latest builds automatically.  Every time there's a new release, I need to change the link to include the latest revision number...

For example, the current build is located here:
https://github.com/yt-dlp/yt-dlp/releases/download/2021.06.01/yt-dlp.exe

Looking for something like:
https://github.com/yt-dlp/yt-dlp/releases/download/latest/yt-dlp.exe

Thank you!

**Comment by fstirlitz** [comment]
This seems to work:

https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp.exe

**Comment by rgiuffre** [comment]
Windows Defender is throwing a Trojan with this release.  I'm done. No more yt-dlp for me.
Laters

**Comment by Ashish0804** [comment]
> Windows Defender is throwing a Trojan with this release.


https://github.com/yt-dlp/yt-dlp/issues/25
