### ISSUE TITLE
The spankbang extractor doesn't seem to work right...

### ISSUE THREAD

**Issue by LonelyGuy12** [yt-dlp/yt-dlp#3693]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.04.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Description

So I was just trying to download vid and it raises an error

### Verbose log

```shell
PS C:\Users\phoen\OneDrive\Desktop\New folder (3)> & C:/Users/phoen/AppData/Local/Programs/Python/Python310/python.exe "c:/Users/phoen/OneDrive/Desktop/New folder (3)/TEST.py"
[SpankBang] 5u5ej: Downloading webpage
[SpankBang] 5u5ej: Downloading stream JSON
[SpankBang] 5u5ej: Downloading m3u8 information
[SpankBang] 5u5ej: Downloading m3u8 information
[SpankBang] 5u5ej: Downloading m3u8 information
[info] 5u5ej: Downloading 1 format(s): hls-1082-1
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 50
[download] Destination: Rias Gremory fuck [5u5ej].mp4
[download]  38.0% of ~30.75MiB at 40.27KiB/s ETA 07:52 (frag 19/50)ERROR: giving up after 0 retries
Traceback (most recent call last):
  File "c:\Users\phoen\OneDrive\Desktop\New folder (3)\TEST.py", line 5, in <module>
    ydl.download(URLS)
  File "C:\Users\phoen\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 3263, in download
    self.__download_wrapper(self.extract_info)(
  File "C:\Users\phoen\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 3236, in wrapper
    res = func(*args, **kwargs)
  File "C:\Users\phoen\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 1398, in extract_info
    return self.__extract_info(url, self.get_info_extractor(ie_key), download, extra_info, process)
  File "C:\Users\phoen\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 1407, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\phoen\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 1491, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "C:\Users\phoen\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 1547, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "C:\Users\phoen\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 2647, in process_video_result
    self.process_info(new_info)
  File "C:\Users\phoen\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 3137, in process_info
    success, real_download = self.dl(temp_filename, info_dict)
  File "C:\Users\phoen\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 2845, in dl
    return fd.download(name, new_info, subtitle)
  File "C:\Users\phoen\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\downloader\common.py", line 457, in download
    ret = self.real_download(filename, info_dict)
  File "C:\Users\phoen\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\downloader\hls.py", line 358, in real_download
    return self.download_and_append_fragments(ctx, fragments, info_dict)
  File "C:\Users\phoen\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\downloader\fragment.py", line 531, in download_and_append_fragments
    result = append_fragment(decrypt_fragment(fragment, self._read_fragment(ctx)), fragment['frag_index'], ctx)
  File "C:\Users\phoen\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\downloader\fragment.py", line 144, in _read_fragment
    down, frag_sanitized = self.sanitize_open(ctx['fragment_filename_sanitized'], 'rb')
KeyError: 'fragment_filename_sanitized'
```

**Comment by pukkandan** [comment]
Show ENTIRE verbose log. The top part of this log is cut off

**Comment by LonelyGuy12** [comment]
> 

Reproducible code
```from yt_dlp import YoutubeDL

URLS = ['https://spankbang.com/5u5ej/video/rias+gremory+fuck']
with YoutubeDL() as ydl:
    ydl.download(URLS)
    ```
    And hey that's the entire log

**Comment by Lesmiscore** [comment]
```
$ yt-dlp https://spankbang.com/5u5ej/video/rias+gremory+fuck -v
[debug] Command-line config: ['https://spankbang.com/5u5ej/video/rias+gremory+fuck', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.04.08 [7884ade65]
[debug] Python version 3.9.12 (CPython 64bit) - Linux-5.13.0-30-generic-x86_64-with-glibc2.34
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.4 (setts), ffprobe 4.4, rtmpdump 2.4
[debug] Optional libraries: certifi, Cryptodome, sqlite
[debug] Proxy map: {}
[debug] [SpankBang] Extracting URL: https://spankbang.com/5u5ej/video/rias+gremory+fuck
[SpankBang] 5u5ej: Downloading webpage
[SpankBang] 5u5ej: Downloading stream JSON
[SpankBang] 5u5ej: Downloading m3u8 information
[SpankBang] 5u5ej: Downloading m3u8 information
[SpankBang] 5u5ej: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 5u5ej: Downloading 1 format(s): hls-1082-1
[debug] Invoking downloader on "https://hls-uranus.sb-cd.com/hls/9/8/9804763-480p.mp4/index-v1-a1.m3u8?_tid=9804763&d=6&m=31&secure=0ysOXXNTH7QWjhnLflRtpg,1652215189"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 50
[download] Destination: Rias Gremory fuck [5u5ej].mp4
[download] 100% of 38.09MiB in 00:46
[debug] ffprobe command line: ffprobe -hide_banner -show_format -show_streams -print_format json 'file:Rias Gremory fuck [5u5ej].mp4'
[FixupM3u8] Fixing MPEG-TS in MP4 container of "Rias Gremory fuck [5u5ej].mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:Rias Gremory fuck [5u5ej].mp4' -map 0 -dn -ignore_unknown -c copy -f mp4 -bsf:a aac_adtstoasc -movflags +faststart 'file:Rias Gremory fuck [5u5ej].temp.mp4'
```
I cannot reproduce. Most likely your internet connection went wrong for a short period.

**Comment by LonelyGuy12** [comment]
> ```
> $ yt-dlp https://spankbang.com/5u5ej/video/rias+gremory+fuck -v
> [debug] Command-line config: ['https://spankbang.com/5u5ej/video/rias+gremory+fuck', '-v']
> [debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
> [debug] yt-dlp version 2022.04.08 [7884ade65]
> [debug] Python version 3.9.12 (CPython 64bit) - Linux-5.13.0-30-generic-x86_64-with-glibc2.34
> [debug] Checking exe version: ffmpeg -bsfs
> [debug] Checking exe version: ffprobe -bsfs
> [debug] exe versions: ffmpeg 4.4 (setts), ffprobe 4.4, rtmpdump 2.4
> [debug] Optional libraries: certifi, Cryptodome, sqlite
> [debug] Proxy map: {}
> [debug] [SpankBang] Extracting URL: https://spankbang.com/5u5ej/video/rias+gremory+fuck
> [SpankBang] 5u5ej: Downloading webpage
> [SpankBang] 5u5ej: Downloading stream JSON
> [SpankBang] 5u5ej: Downloading m3u8 information
> [SpankBang] 5u5ej: Downloading m3u8 information
> [SpankBang] 5u5ej: Downloading m3u8 information
> [debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
> [debug] Default format spec: bestvideo*+bestaudio/best
> [info] 5u5ej: Downloading 1 format(s): hls-1082-1
> [debug] Invoking downloader on "https://hls-uranus.sb-cd.com/hls/9/8/9804763-480p.mp4/index-v1-a1.m3u8?_tid=9804763&d=6&m=31&secure=0ysOXXNTH7QWjhnLflRtpg,1652215189"
> [hlsnative] Downloading m3u8 manifest
> [hlsnative] Total fragments: 50
> [download] Destination: Rias Gremory fuck [5u5ej].mp4
> [download] 100% of 38.09MiB in 00:46
> [debug] ffprobe command line: ffprobe -hide_banner -show_format -show_streams -print_format json 'file:Rias Gremory fuck [5u5ej].mp4'
> [FixupM3u8] Fixing MPEG-TS in MP4 container of "Rias Gremory fuck [5u5ej].mp4"
> [debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:Rias Gremory fuck [5u5ej].mp4' -map 0 -dn -ignore_unknown -c copy -f mp4 -bsf:a aac_adtstoasc -movflags +faststart 'file:Rias Gremory fuck [5u5ej].temp.mp4'
> ```
> 
> I cannot reproduce. Most likely your internet connection went wrong for a short period.

Well maybe it happened cuz it was triggered from script. That makes no sense tho....

**Comment by LonelyGuy12** [comment]
Anyways I will try again and see if it works...

**Comment by pukkandan** [comment]
> And hey that's the entire log

But that is not the **verbose** log! Pass `{'verbose': True}` to `YoutubeDL`
