### ISSUE TITLE
Unable to change download directory

### ISSUE THREAD

**Issue by kayPUNK** [yt-dlp/yt-dlp#3694]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

I can't seem to figure out how to change the download directory for this. I am new to this, but I thought I was following the instructions well enough. I wrote a ytp-dl.conf file in my home directory and this is what I have written inside of it:

-o /Videos/youtube-dl

Does anybody know how I might fix this?

**Comment by Lesmiscore** [comment]
```
-P, --paths [TYPES:]PATH         The paths where the files should be
                                 downloaded. Specify the type of file and
                                 the path separated by a colon ":". All the
                                 same TYPES as --output are supported.
                                 Additionally, you can also provide "home"
                                 (default) and "temp" paths. All
                                 intermediary files are first downloaded to
                                 the temp path and then the final files are
                                 moved over to the home path after download
                                 is finished. This option is ignored if
                                 --output is an absolute path
```

**Comment by kayPUNK** [comment]
> https://github.com/yt-dlp/yt-dlp#filesystem-options
> 
> ```
> -P, --paths [TYPES:]PATH         The paths where the files should be
>                                  downloaded. Specify the type of file and
>                                  the path separated by a colon ":". All the
>                                  same TYPES as --output are supported.
>                                  Additionally, you can also provide "home"
>                                  (default) and "temp" paths. All
>                                  intermediary files are first downloaded to
>                                  the temp path and then the final files are
>                                  moved over to the home path after download
>                                  is finished. This option is ignored if
>                                  --output is an absolute path
> ```

I am now getting an error message saying "Is a directory"?

**Comment by pukkandan** [comment]
Check if you have access to the folder! We can't see or access your computer. Atleast, show us the verbose log so we have some idea of what is happening...
