### ISSUE TITLE
What means "Fixing MPEG-TS in MP4 container" ?

### ISSUE THREAD

**Issue by ElektroStudios** [yt-dlp/yt-dlp#3695]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

I just would like to know what is the exact meaning of the "Fixing MPEG-TS in MP4 container" message.

What does **yt-dlp** with the original downloaded MP4 video file at this point?.

I can see this message after a MP4 file is downloaded:

> [download] Destination: C:\ASSASSINS PRIDE Episodio 10 – Biblioteca laberinto.mp4
> [download] 100% of 1.42GiB in 04:03
> [FixupM3u8] Fixing MPEG-TS in MP4 container of "C:\ASSASSINS PRIDE Episodio 10 – Biblioteca laberinto.mp4"

it takes a lot of time to finish to "fix" the video, and it is a message that does not really explain what thing it is doing with the MP4 video file.

The only thing I could notice is that the "fixed" video results in a file with less file size than the original non-fixed video file. And that the '[FixupM3u8]' mark seems to be related with a playlist (m3u8) of fragmented chunks. 

"Fixing MPEG-TS" message It is not anything explanatory for me.

Someone could explain what this means and how it affects the original downloaded MP4 file?. Thanks in advance.

**Comment by Lesmiscore** [comment]
Especially when you downloaded HLS formats, the downloaded mp4 is actually not mp4; [it's a MPEG-TS (.ts) file.](https://en.wikipedia.org/wiki/MPEG_transport_stream)

`FixupM3u8` is to convert MPEG-TS format to a real mp4 file, without re-encoding.
