### ISSUE TITLE
Converts from MPEG-TS to MP4 despite `--hls-use-mpegts`

### ISSUE THREAD

**Issue by barsnick** [yt-dlp/yt-dlp#3697]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.04.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

According to [the manual](https://github.com/yt-dlp/yt-dlp/blob/fe1daad3cb224904cc72462204da5f6427be6f44/README.md?plain=1#L522), I expect the option `--hls-use-mpegts` to not convert a downloaded video from MPEG-TS (concatenated HLS segments) to MP4 container.

```
    --hls-use-mpegts                 Use the mpegts container for HLS videos;
                                     allowing some players to play the video
                                     while downloading, and reducing the chance
                                     of file corruption if download is
                                     interrupted. This is enabled by default for
                                     live streams
```

The conversion happens nevertheless. At least according to the manual, this is surprising. Especially if you're playing while downloading, doesn't the file being played disappear after conversion? (I am aware that, under Linux, the file will remain accessible while a file descriptor on it is still open.)

I make use of `--fixup=never` to avoid the conversion, but it's not documented for this use case. (I'm not saying this is a documentation issue.)

(BTW, my use case for keeping MPEG-TS is: My PVR plays MPEG-TS best natively, and I do not wish to convert back and forth, which takes extra disk space, and CPU time, network transfer to/from the PVR.)

The example in the verbose log is chosen to be relatively small and non-geo-blocked.

Another BTW: I consider the message "Fixing MPEG-TS in MP4 container" technically incorrect - both are container formats in this context, one is not "in" the other. The issue is "Fixing downloaded MPEG-TS container to requested MP4 container.

Version is: yt-dlp master HEAD (2022.04.08), revision fe1daad3cb224904cc72462204da5f6427be6f44.

### Verbose log

```shell
[15:14:03 barsnick@moonlight yt-dlp]$ python -m yt_dlp -Uv --hls-use-mpegts --hls-prefer-native https://tv.nrk.no/serie/koe/sesong/2/episode/8/avspiller
[debug] Command-line config: ['-Uv', '--hls-use-mpegts', '--hls-prefer-native', 'https://tv.nrk.no/serie/koe/sesong/2/episode/8/avspiller']
[debug] User config "/home/barsnick/.config/yt-dlp/config": ['-o', '%(title)s [%(extractor)s %(id)s].%(ext)s']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.04.08 [7884ade65] (source)
[debug] Lazy loading extractors is disabled
[debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
[debug] Git HEAD: fe1daad3c
[debug] Python version 3.10.4 (CPython 64bit) - Linux-5.17.4-200.fc35.x86_64-x86_64-with-glibc2.34
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: ffmpeg -bsfs
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2
[debug] Optional libraries: Cryptodome-3.14.1, brotli-1.0.9, certifi-2020.12.05, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.0
[debug] Proxy map: {}
Latest version: 2022.03.08, Current version: 2022.04.08
yt-dlp is up to date (2022.04.08)
[debug] [NRKTVEpisode] Extracting URL: https://tv.nrk.no/serie/koe/sesong/2/episode/8/avspiller
[NRKTVEpisode] koe/sesong/2/episode/8: Downloading webpage
[debug] Using fake IP 84.212.170.156 (NO) as X-Forwarded-For
[debug] [NRK] Extracting URL: nrk:MUHH71005821
[NRK] MUHH71005821: Downloading manifest JSON
[NRK] MUHH71005821: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[NRK] MUHH71005821: Downloading metadata JSON
[NRK] MUHH71005821: Downloading programs JSON
[debug] Default format spec: bestvideo*+bestaudio/best
[info] MUHH71005821: Downloading 1 format(s): 2276
[debug] Invoking downloader on "https://nrk-od-32.akamaized.net/world/1249732/0/hls/muhh71005821/1853524312-1203177498-prog_index.m3u8?version_hash=474047e4"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 21
[download] Destination: Kø - 8. Kan vi snakke norsk [NRK MUHH71005821].mp4
[download] 100% of 57.91MiB in 00:23
[debug] ffprobe command line: ffprobe -hide_banner -show_format -show_streams -print_format json 'file:Kø - 8. Kan vi snakke norsk [NRK MUHH71005821].mp4'
[FixupM3u8] Fixing MPEG-TS in MP4 container of "Kø - 8. Kan vi snakke norsk [NRK MUHH71005821].mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:Kø - 8. Kan vi snakke norsk [NRK MUHH71005821].mp4' -map 0 -dn -ignore_unknown -c copy -f mp4 -bsf:a aac_adtstoasc -movflags +faststart 'file:Kø - 8. Kan vi snakke norsk [NRK MUHH71005821].temp.mp4'
```

**Comment by pukkandan** [comment]
The option was originally designed only for ffmpeg downloader
