### ISSUE TITLE
Did the version string just change?

### ISSUE THREAD

**Issue by seagull** [yt-dlp/yt-dlp#3699]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

I have a script that invokes YT-DLP and downloads the latest version.
Until earlier today the version of YT-DLP-min I had saved had the version string "2022.04.08".
When I ran the script last I saw that I was now running "2022.03.08" (one month prior) and that the releases page, despite not showing a new update, does not list file hashes for this "new" version.
What happened?

### Verbose log

```shell
PS C:\Program Files\YTDLP> .\yt-dlp_min.exe --version
2022.03.08
```

**Comment by pukkandan** [comment]
> When I ran the script last I saw that I was now running "2022.03.08" (one month prior) and that the releases page, despite not showing a new update, does not list file hashes for this "new" version.

Always check versions with `<`, not `=`!

---

But yeah, the issue is #3653
