### ISSUE TITLE
ERROR: 706388554: An extractor error has occurred. (caused by KeyError('title'))

### ISSUE THREAD

**Issue by InteXX** [yt-dlp/yt-dlp#3711]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.04.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

USA

### Description

If I'm not mistaken, my issue is _not_ a duplicate of [this issue](https://github.com/yt-dlp/yt-dlp/issues/2606). The other issue is with a PBS URL, mine is with a series of Vimeo URLs. The stack trace differs as well. There's also a certain nuance that tends to make this a unique situation. I'll get to that in a sec, so as to keep it in context.

(Note: I tried the `--no-geo-bypass` switch as suggested there, but it had no effect.)

The website URL for this video is https://go2.propaganda-exposed.com/docuseries/episode-2/, but it has expired by this time.

The way these series work is that a given HTML page is available for a 24-hour window, after which it no longer provides access to the video. (This is a marketing technique, to focus attention on DVD sales. On a side note, I maintain that downloading these videos for personal safekeeping and offline viewing is both legal and ethical. See the recent Github/youtube-dl conflict resolution for more information.)

Even though the hosting HTML page may expire, however, its underlying video URL remains active. For example, the page for the first episode, originally aired May 4, has expired by now:

https://go2.propaganda-exposed.com/docuseries/episode-1/

...but its video URL is still available:

https://player.vimeo.com/video/706371837?h=bbc46a7068

It can be successfully download using this command:

```
yt-dlp.exe --newline -i -o "C:\Videos\%(title)s.%(ext)s" -f mp4 --ignore-config --hls-prefer-native --referer https://go2.propaganda-exposed.com/ "https://player.vimeo.com/video/706371837?h=bbc46a7068"
```

The problem URL is from Episode 2:

https://go2.propaganda-exposed.com/docuseries/episode-2/
https://player.vimeo.com/video/706388554?h=7a039893c4

Here are all the video URLs so far, 7 of 8:

```
1. https://player.vimeo.com/video/706371837?h=bbc46a7068
2. https://player.vimeo.com/video/706388554?h=7a039893c4
3. https://player.vimeo.com/video/706391277?h=f86f11b355
4. https://player.vimeo.com/video/706393504?h=dfbef2581a
5. https://player.vimeo.com/video/706595914?h=e1a21e4b2f
6. https://player.vimeo.com/video/707168786?h=ca50626506
7. https://player.vimeo.com/video/707406814?h=45266f055e
```

Only 1 and 7 in this list work currently; all others exhibit the same error. The 8th episode becomes available tonight, starting at 9pm US Eastern time.

I suspect this issue might be unique from the one linked above because all 7 of these URLs did indeed work at one time. In fact, I've been able to successfully download ALL of the listed videos, each on the day of its original airing. I only ran into problems just now, when I sought to explain to an online friend how to download them.

In the issue prerequisites above, I had to select the checkbox `I've checked that all provided URLs are alive and playable in a browser` in order to be able to post this report. However, due to the page expiry construct, this is not the case for all URLs. The expired HTML pages won't permit display of the videos, nor will a separate browser tab accessing the Vimeo URL directly (because of the `--referer` requirement).

As of today, the only way to get these is via the still-active Vimeo URLs (excepting, of course, Episode 7, which is airing today for another 6 hours or so). But 2-6 above are all exhibiting the same failure. Omitting the `?h=` query string provides no relief.

### Verbose log

```shell
C:\yt-dlg>yt-dlp.exe -vU --newline -i -o "C:\Videos\%(title)s.%(ext)s" -f mp4 --ignore-config --hls-prefer-native --referer https://go2.propaganda-exposed.com/ "https://player.vimeo.com/video/706388554?h=7a039893c4"
[debug] Command-line config: ['-vU', '--newline', '-i', '-o', 'C:\\Videos\\%(title)s.%(ext)s', '-f', 'mp4', '--ignore-config', '--hls-prefer-native', '--referer', 'https://go2.propaganda-exposed.com/', 'https://player.vimeo.com/video/706388554?h=7a039893c4']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.04.08 [7884ade] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg N-91482-g8aa6d9a8d3, ffprobe N-91482-g8aa6d9a8d3
[debug] Optional libraries: brotli, certifi, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.04.08, Current version: 2022.04.08
yt-dlp is up to date (2022.04.08)
[debug] [vimeo] Extracting URL: https://player.vimeo.com/video/706388554?h=7a039893c4
[vimeo] 706388554: Downloading webpage
ERROR: 706388554: An extractor error has occurred. (caused by KeyError('title')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 641, in extract
  File "yt_dlp\extractor\vimeo.py", line 884, in _real_extract
  File "yt_dlp\extractor\vimeo.py", line 126, in _parse_config
KeyError: 'title'
```

**Comment by pukkandan** [comment]
The uploader has marked all videos except episode 1 as private. You can verify by opening the links in browser using [Referer Control](https://chrome.google.com/webstore/detail/referer-control/hnkcfpcejkafcihlgbojoidoihckciin) or another similar extension

**Comment by InteXX** [comment]
Thank you, @pukkandan.

That's a _very_ handy control; I didn't know such a thing existed. I'll be making extensive use of it.
