### ISSUE TITLE
Loom

### ISSUE THREAD

**Issue by upintheairsheep** [yt-dlp/yt-dlp#3715]
### Checklist

- [X] I'm reporting a new site support request
- [x] I've verified that I'm running yt-dlp version **2022.04.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

USA, North America, Earth, Solar System, The Milky Way galaxy, The Frontrooms, the multiverse

### Example URLs

"Video with lots of metadata: https://www.loom.com/share/24351eb8b317420289b158e4b7e96ff2
*More links: http://web.archive.org/web/*/https://www.loom.com/share/*/

### Description

Please add support for Loom, a screen recording software. There is a download option but yt dlp is great for automating the download and adding metadata like thumbnail, description, miscilanios metadata, comments, and profile pictures. 

### Verbose log

```shell
Not attempted.
```

**Comment by pukkandan** [comment]
> Not attempted.

The field exists so that you will "attempt"!

```
❯ yt-dlp loom.com/share/24351eb8b317420289b158e4b7e96ff2 -v
[debug] Command-line config: ['--ignore-config', 'loom.com/share/24351eb8b317420289b158e4b7e96ff2', '-v']
[debug] Encodings: locale cp65001, fs utf-8, out utf-8, err utf-8, pref cp65001
[debug] yt-dlp version 2022.04.08 [7884ade65] (source)
[debug] Lazy loading extractors is disabled
[debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
[debug] Git HEAD: 8dcce6a89
[debug] Python version 3.10.4 (CPython 64bit) - Windows-10-10.0.22000-SP0
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: ffmpeg -bsfs
[debug] exe versions: ffmpeg N-106550-g072101bd52-20220410 (fdk,setts), ffprobe N-106624-g391ce570c8-20220415, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.14.1, brotli-1.0.9, certifi-2021.10.08, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.1
[debug] Proxy map: {}
[debug] [generic] Extracting URL: loom.com/share/24351eb8b317420289b158e4b7e96ff2
WARNING: [generic] The url doesn't specify the protocol, trying with http
[debug] [generic] Extracting URL: http://loom.com/share/24351eb8b317420289b158e4b7e96ff2
[generic] 24351eb8b317420289b158e4b7e96ff2: Requesting header
[redirect] Following redirect to https://www.loom.com:443/share/24351eb8b317420289b158e4b7e96ff2
[debug] [generic] Extracting URL: https://www.loom.com:443/share/24351eb8b317420289b158e4b7e96ff2
[generic] 24351eb8b317420289b158e4b7e96ff2: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] 24351eb8b317420289b158e4b7e96ff2: Downloading webpage
[generic] 24351eb8b317420289b158e4b7e96ff2: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://www.loom.com:443/share/24351eb8b317420289b158e4b7e96ff2
Traceback (most recent call last):
  File "D:\Programs\Source\yt-dlp\yt-dlp\yt_dlp\YoutubeDL.py", line 1400, in wrapper
    return func(self, *args, **kwargs)
  File "D:\Programs\Source\yt-dlp\yt-dlp\yt_dlp\YoutubeDL.py", line 1470, in __extract_info
    ie_result = ie.extract(url)
  File "D:\Programs\Source\yt-dlp\yt-dlp\yt_dlp\extractor\common.py", line 641, in extract
    ie_result = self._real_extract(url)
  File "D:\Programs\Source\yt-dlp\yt-dlp\yt_dlp\extractor\generic.py", line 4037, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.loom.com:443/share/24351eb8b317420289b158e4b7e96ff2
```

**Comment by gamer191** [comment]
There is a fix available at https://github.com/ytdl-org/youtube-dl/pull/28039, although I haven't tested it and https://github.com/ytdl-org/youtube-dl/pull/28039#issuecomment-1086906096 suggests that that patch is currently broken

**Comment by ahm750** [comment]
Will support be added for Loom?

**Comment by ryanhugh** [comment]
+1

**Comment by aik099** [comment]
Here is a project, that can download Loom videos: https://github.com/EcomGraduates/loom-downloader (tested myself).

**Comment by hruzgar** [comment]
Guys im trying to bring some attention here. I found this loom downloader written in python [https://github.com/Ecno92/loom-dl](https://github.com/Ecno92/loom-dl). The code is only 50 lines. I just read the creating a new extractor part and could actually create an extractor for loom. Can I do that? Or did somebody already do it?

**Comment by pukkandan** [comment]
You can make a PR. Nobody has done so yet

**Comment by hruzgar** [comment]
ok thanks. Im working on it

**Comment by hruzgar** [comment]
I already finished the extractor 😃. Here is the branch: [https://github.com/hruzgar/yt-dlp/tree/loomextractor](https://github.com/hruzgar/yt-dlp/tree/loomextractor). I might have to add some more tests and read the yt-dlp guidelines for good formatting etc but its working 🎉

**Comment by hruzgar** [comment]
Pull request was made 👍
