### ISSUE TITLE
Is it possible to get the names of the video chapters without download the video?

### ISSUE THREAD

**Issue by SeyRyuu** [yt-dlp/yt-dlp#3720]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

Hey there,

I am making an example to describe my question. 

Let's say we have a video called "TestVideo" and the (youtube) video contains three chapters (chA, chB, chC). Now I would like to get these chapter names without downloading the whole video as print in the console.
This question is quite similar to what the options "--get-filename -o "%(title)s" does (printing the format-string to the console --> "TestVideo"), but I want the same behavior but for the chapter names (e.g. output on the console --> "001_chA" \n "002_chB" \n "003_chC", or similar). 

Is there any way to do this? I experimented a bit with the "--get-filenames"-option and the "chapter:" output specifier but i failed. Any idea and may an example without downloading the whole video would be nice, if there is one (or more).

Kind regards

**Comment by pukkandan** [comment]
See `--print` option

**Comment by SeyRyuu** [comment]
Yes, this worked perfectly!

E.g. `yt-dlp.exe --print chapters https://www.youtube.com/watch?v=GIq3pcdz4Sw`.

-> `[{'start_time': 0.0, 'title': 'Typical James', 'end_time': 12.0}, {'start_time': 12.0, 'title': 'Anandtech 11700K review', 'end_time': 82.0}, {'start_time': 82.0, 'title': 'RTX 3080 Ti and 3050 Ti leaks', 'end_time': 142.0}, {'start_time': 142.0, 'title': 'Nintendo Switch Pro rumors', 'end_time': 190.0}, {'start_time': 190.0, 'title': 'Seasonic', 'end_time': 230.0}, {'start_time': 230.0, 'title': 'QUICK BITS', 'end_time': 234.0}, {'start_time': 234.0, 'title': 'No default app switching on iOS', 'end_time': 270.0}, {'start_time': 270.0, 'title': 'Facebook AI supervise themselves', 'end_time': 304.0}, {'start_time': 304.0, 'title': 'Fingerprint-reading credit cards', 'end_time': 336.0}, {'start_time': 336.0, 'title': "Bungie won't fix Destiny 2 bug", 'end_time': 360.0}, {'start_time': 360.0, 'title': '8-year old pro Fortnite player', 'end_time': 400}]`

Thanks for your reply @pukkandan.

Regards
