### ISSUE TITLE
Substack

### ISSUE THREAD

**Issue by fstirlitz** [yt-dlp/yt-dlp#3722]
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.04.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Example URLs

- Video: https://haleynahman.substack.com/p/i-made-a-vlog
- Podcast: https://haleynahman.substack.com/p/-dear-danny-i-found-my-boyfriends

Those two are publicly available; I imagine extraction from a subscriber-only post should be substantially the same.

### Description

Video extraction involves capturing the script tag whose contents are `window._preloads = {/* JSON */}`, then reading off `_preloads['post']['videoUpload']['id']` and plugging the value into `/api/v1/video/upload/$UPLOAD_ID/src?type={hls,mp4}`. Podcasts are slightly easier, as the URL is directly stored in `_preloads['post']['podcast_url']`. Substack doesn’t seem to transcode or downscale media at all, so there should be usually only one or two media URLs.

Player JS link: <https://substackcdn.com/min/main.bundle.js?v=185519-180bb37adb0>. The source code mentions some kind of `reaction_token` that may or may not be necessary to pass for paid posts; I have no way to test, and I have not dug through it to see where it comes from.

### Verbose log

```sh-session
[debug] Command-line config: ['-vF', 'https://haleynahman.substack.com/p/i-made-a-vlog']
[debug] User config "/home/stirlitz/.config/yt-dlp/config": [REDACTED]
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.04.08 [7884ade65]
[debug] Python version 3.10.4 (CPython 64bit) - Linux-5.17.0-1-amd64-x86_64-with-glibc2.33
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.4.2-1 (setts), ffprobe 4.4.2-1, rtmpdump 2.4
[debug] Optional libraries: brotli, certifi, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [generic] Extracting URL: https://haleynahman.substack.com/p/i-made-a-vlog
[generic] i-made-a-vlog: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] i-made-a-vlog: Downloading webpage
[generic] i-made-a-vlog: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://haleynahman.substack.com/p/i-made-a-vlog
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/yt_dlp/YoutubeDL.py", line 1408, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/yt_dlp/YoutubeDL.py", line 1478, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/common.py", line 641, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/generic.py", line 4039, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://haleynahman.substack.com/p/i-made-a-vlog
```

**Comment by elyse0** [comment]
@fstirlitz I've implemented an extractor for this, it works okay for the links you provided and some others I tried.

Before I make a PR, I would like to test if it works on suscriber-only media too, so... could you try using it with your account?
I guess you need to pass cookies

This is my branch: https://github.com/elyse0/yt-dlp/tree/substack

### Verbose log

```bash
[debug] Command-line config: ['-v', 'https://haleynahman.substack.com/p/i-made-a-vlog']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.04.08 [7884ade65]
[debug] Lazy loading extractors is disabled
[debug] Python version 3.8.10 (CPython 64bit) - Linux-5.4.0-110-generic-x86_64-with-glibc2.29
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: ffmpeg -bsfs
[debug] exe versions: ffmpeg N-106673-g058a1ff9b4-20220424 (setts), ffprobe N-106673-g058a1ff9b4-20220424, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.14.1, brotli-1.0.9, certifi-2021.10.08, mutagen-1.45.1, secretstorage-2.3.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] [Substack] Extracting URL: https://haleynahman.substack.com/p/i-made-a-vlog
[Substack] i-made-a-vlog: Downloading webpage
[Substack] a7315fa8-8027-4432-a7e3-652479bc5275: Downloading m3u8 information
[debug] Default format spec: bestvideo*+bestaudio/best
[info] i-made-a-vlog: Downloading 1 format(s): 1
[debug] Invoking http downloader on "https://substackcdn.com/video_upload/post/47660949/a7315fa8-8027-4432-a7e3-652479bc5275/transcoded.mp4?Expires=1652762172&Key-Pair-Id=APKAIVDA3NPSMPSPESQQ&Signature=NL~Nqw8yeTWDxWLUhpHyyV1XzFtw4~s56PgKV4~jm4as2VbtyxsSMHkQwCxCPgnM2O~do-UFMcxsBEoUnV~o0v-JRuJH-C~MRTKzaffoQXCayTnIAySAYHFTf43uIA7oXpcQITcAtogjhosdimUqoKbuZGa1qBzNxvmLwO6dckV~tmtNJfHE-F917sSsB-3N4dGVkTb5SVovncORgiZ7RFc4fXtq98D3M3qDsZlmjD9AV63hNjQJaoY7om~~gbk-bmJ8AOuKcM9gsghoBZCi-2ARcEMTR8IWqG-dsT0dnp3A4iDigoOcsM8mC73yxyJBgyo9JCJyq8ZtCAoAyXEdHg__"
[download] Destination: I MADE A VLOG [i-made-a-vlog].mp4
[download]   1.0% of 1.13GiB at  5.09MiB/s ETA 03:44
```


### Command to install my branch
```bash
python3 -m pip install --force-reinstall https://github.com/elyse0/yt-dlp/archive/substack.tar.gz
```

### Command to re-install yt-dlp latest version
```bash
python3 -m pip install --force-reinstall https://github.com/yt-dlp/yt-dlp/archive/master.tar.gz
```

**Comment by tom-huntington** [comment]
>Video extraction involves capturing the script tag whose contents are window._preloads = {/* JSON */}, then reading off _preloads['post']['videoUpload']['id'] and plugging the value into /api/v1/video/upload/$UPLOAD_ID/src?type={hls,mp4}.

The video extractor was broken for me. I was able to find the video id at `window._preloads.post.video_upload_id` rather than `window._preloads.post.videoUpload.id`
