### ISSUE TITLE
Filter search results by length

### ISSUE THREAD

**Issue by Explosion-Scratch** [yt-dlp/yt-dlp#3726]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

How do I filter the search results by length, for example in a `ytsearch1:query` type search, is there a way that I could for example when searching for a video not download something over 20 minutes and/or filter those out?

**Comment by flashdagger** [comment]
e.g. ` yt-dlp ytsearch5:query --match-filter "duration<1200" --print "%(duration_string)5s - %(title)s"`

**Comment by Explosion-Scratch** [comment]
Thanks!
