### ISSUE TITLE
srt subtitles and yt-dlp

### ISSUE THREAD

**Issue by estaf1001** [yt-dlp/yt-dlp#3728]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

If you just download subtitles automatically, vtt subtitles will be downloaded.
If subtitles need to be translated, the markup inside this format does not allow for this to be done easily. When converting such subtitles online you get mush. I can't figure out what to do with them so I can easily copy subtitle text to and from the translator.
https://prnt.sc/sQYCLuc9k5QY
Any advice?

### Verbose log

```shell
yt-dlp --write-subs --sub-langs en https://www.youtube.com/watch?v=hFIWUo0Dauc&t=435s
This way only the video file will be uploaded, although the same program downie perfectly downloads English subtitles from this link.

then we choose the automaton:
yt-dlp --write-auto-subs https://www.youtube.com/watch?v=hFIWUo0Dauc&t=435s
so subtitles are downloaded, but have a lot of tags that are hard to work with later.

Example:
00:00:13.440 --> 00:00:15.749 align:start position:0%
[Music]
hello<00:00:13.840><c> everyone</c><00:00:14.639><c> and</c><00:00:14.880><c> welcome</c><00:00:15.280><c> to</c><00:00:15.440><c> the</c><00:00:15.519><c> new</c>
```

**Comment by pukkandan** [comment]
`--convert-subtitles srt`
