### ISSUE TITLE
A Question?

### ISSUE THREAD

**Issue by KoshikKumar17** [yt-dlp/yt-dlp#3729]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

@pukkandan Did the latest version of yt-dlp support extracting from hotstar?

I mean through using it can I  download hotstar videos using latest build of yt-dlp?

Please help me.

**Comment by pukkandan** [comment]
https://tryitands.ee/
