### ISSUE TITLE
[bug] `-N` skipping fragments?

### ISSUE THREAD

**Issue by pukkandan** [yt-dlp/yt-dlp#373]
Sometimes file will fail to download (or merge, I'm really not sure since I haven't seen any errors, though maybe I just missed them). This happened before I started using --path temp:D:\Temp\  but since using that, temporary files are getting left behind there for files that didn't completely download (in this case fragments 377-745 and respective .part and .ytdl files. I understand the default is to resume downloads with previously downloaded fragments but it should still clear up all the fragments for that respective download on completion. The skipping of download might not be a bug but I was curious as to what --fragment-retries "infinite" really does since I have it set, I assume it is regarding that fragment as unavailable and by default getting skipped but I want it to retry until it finds it instead (at least for a minute).

Command (temporary switched back to batch files since the frontend I was using didn't like some stuff):

`yt-dlp -a "CR todownload - valarian.txt" -o "crunchyroll.com\%%(series)s - S%%(season_number)sE%%(episode_number)s - %%(episode)s - %%(epoch)s.%%(ext)s" --embed-subs --sub-lang en --cookies cookies-crunchyroll-com.txt --user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:89.0) Gecko/20100101 Firefox/89.0" --fragment-retries "infinite" -N 3 --no-mtime --download-archive archive.txt --path temp:D:\Temp\`

_Originally posted by @Jules-A in https://github.com/yt-dlp/yt-dlp/issues/359#issuecomment-853906485_

**Comment by pukkandan** [comment]
@Jules-A, Can u check if the resulting file has missing fragments? "377-745" is quite a large range to have unavailable fragments. So my initial guess is that the fragments are in fact getting appended, but just not deleted from disk

**Comment by pukkandan** [comment]
Also, if you could find a verbose log of when this happened, it would be helpful

**Comment by Jules-A** [comment]
I basically just ran the batch again and it re-downloaded the file (not sure if from scratch) with a file size similar to the rest. Actually I think there's a larger issue at play, I just tried playing the file and MPV wouldn't open, MPC opened but didn't play anything. I then checked the rest of the files and none of them play, they seem to all be corrupted... This is the series I was trying to download: https://www.crunchyroll.com/valerian-and-laureline/

It's probably worth noting I tried entering the url to download the playlist but it would just return a 403 even with latest cookies so I used [my greasemonkey script ](https://pastebin.com/raw/4jUQ95E6) to grab the urls and put in to a text file for batch.

No verbose log of when it happened, I will try again though. This was with my build of https://github.com/yt-dlp/yt-dlp/commit/eb03899192e79f824a3c269ddbbf623c6f903e51 with latest stable Python/PiP/Pyinstaller/Windows 10

**Comment by pukkandan** [comment]
It was such a dumb mistake. I forgot to decrypt the fragment when reading from disk. I didn't notice the issue since I only tested with non-encrypted media. Will fix asap

**Comment by pukkandan** [comment]
@Jules-A Please confirm this is fixed. I don't have a crunchyroll account and hence was only able to test on trailers

**Comment by Jules-A** [comment]
> @Jules-A Please confirm this is fixed. I don't have a crunchyroll account and hence was only able to test on trailers

Hmm... That's weird, in Australia pretty much everything that is older than a week (and a few exceptions for specials/ovas/uncensored versions) is available for free without an account at 1080p. Instead we get a heap of region locked content. As far as I'm aware I think it's similar except for some European countries?
Are you sure you aren't just trying to do a playlist download or trying without cookies file? The playlist download is currently broken but they are in the process of rolling out their new website update so no point fixing that yet. The cookies are required for CR and they expire fairly quickly. If you try watch for example: https://www.crunchyroll.com/welcome-to-demon-school-iruma-kun/episode-1-iruma-kun-from-demon-school-789490  does it say it requires a CR sub?

I will test it soonish and update this comment when I have but I haven't seen any left over files since I reverted to an older build.

**Comment by pukkandan** [comment]
> in Australia pretty much everything that is older than a week (and a few exceptions for specials/ovas/uncensored versions) is available for free without an account at 1080p. Instead we get a heap of region locked content. As far as I'm aware I think it's similar except for some European countries?

I didn't know that... I assumed all content required a subscription

> Okay so I tested just 1 show so far and it plays but I haven't watched the whole file to check if there's stuttering or anything.

If it starts playing, then there shouldn't be any other issue

>  I just realised that's probably my fault since the filename is changing due to my output template using epoch. 

Nothing can be done about it

> resuming a download probably should have a way that doesn't fully rely on filename.

What do you suggest? I cannot think of any other way that is more reliable

> I want a number that is sequential for the watch order (the order I list them to download in the batch text file I send to yt-dlp) that is unique so it doesn't play a file from another season or another show entirely. It would also need to take in to account editing the batch text file 

`id` and `extractor_key` together is always unique (except for the generic extractor). As for a sequential number, there is no single method that can work across all websites and can keep working when you edit the batch files. It would be possible if you are willing to put the episode numbers manually in the batch file along with the URL

> so it doesn't need to download the webpage 50 times unnecessarily when I already have the files (I feel like this is an area that could really use some improvement...)

Using `--download-archive` should normally help with this, but I see that crunchyroll uses a non-standard regex group for getting id which is causing the pre-checking to fail. I'll fix it

**Comment by Jules-A** [comment]
> What do you suggest? I cannot think of any other way that is more reliable

You could try searching for the .part file or .ytdl that is created and resuming using the filename of that file. 

> id and extractor_key together is always unique (except for the generic extractor). As for a sequential number, there is no single method that can work across all websites and can keep working when you edit the batch files. It would be possible if you are willing to put the episode numbers manually in the batch file along with the URL

Id isn't always sequential but I haven't tried extractor_key but I doubt that is either. Adding numbers manually would require writing some code but I'm not really that familar with batch files and I'm too lazy to start writing my own front-end right now... 
If you mean the batch text file (the line separated list of urls in a txt file) that's possible is you allow optional reading of an index number I guess?

>Using --download-archive should normally help with this, but I see that crunchyroll uses a non-standard regex group for getting id which is causing the pre-checking to fail. I'll fix it

Ah I see, thanks.

**Comment by pukkandan** [comment]
> If you mean the batch text file (the line separated list of urls in a txt file) that's possible if you allow optional reading of an index number I guess?

Yes, I did mean the text file containing the URLs. There is no need for me to implement reading of the index. You can parse it out of the URL using `--parse-metadata`

1. Append `#num` at the end of the URLs. Eg: `https://www.crunchyroll.com/welcome-to-demon-school-iruma-kun/episode-1-iruma-kun-from-demon-school-789490#10`
2. Use `--parse-meta "webpage_url:#%(mynum)s"` to extract the number into `mynum`
3. Use that in the outtmpl like ` -o "%(mynum)03d - %(title)s.%(ext)s"`
Eg:
```
$ yt-dlp "https://www.twitch.tv/videos/1047573539#10" --get-filename --parse-meta "webpage_url:#%(mynum)s" -o "%(mynum)03d - %(title)s.%(ext)s"
010 - PARTIDO COMPLETO # Real Madrid 3-2 Real Sociedad # Primera Iberdrola.mp4
```

Alternatively, if you know that the URL contains the episode number already (like in the example you gave), you can directly parse it as well using `--parse-metadata "webpage_url:episode-(?P<mynum>\d+)"`

**Comment by pukkandan** [comment]
> You could try searching for the .part file or .ytdl that is created and resuming using the filename of that file.

There would be no way to know if those files belong to the same video or not

**Comment by Jules-A** [comment]
> 
> 
> > You could try searching for the .part file or .ytdl that is created and resuming using the filename of that file.
> 
> There would be no way to know if those files belong to the same video or not

Then why not store the id in the .ytdl file?

**Comment by Jules-A** [comment]
Sorry about another unrelated question but how can I change the template so that if any of the output templates fail to return a value (I'm using 5 including the new parse-metadata value, 6 soon once I work out how to use metadata to get the domain) then simply return the title and video id instead? There's placeholder option which I can probably set to "" but I'm currently placing text in front like S and E and - .

**Comment by pukkandan** [comment]
It is not directly possible. It can (probably) be done using `--parse-metadata` again, but the command would be quite lengthy. What is the output template that you are using?

**Comment by Jules-A** [comment]
> It is not directly possible. It can (probably) be done using `--parse-metadata` again, but the command would be quite lengthy. What is the output template that you are using?

Right now: 
`yt-dlp -a "CR todownload - Kekkaishi.txt" -o "crunchyroll.com\%%(series)s - S%%(season_number)sE%%(episode_number)s - %%(episode)s - %%(index)s.%%(ext)s" --parse-meta "webpage_url:#%(index)s" --embed-subs --sub-langs en,enUS --cookies cookies-crunchyroll-com.txt --user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:89.0) Gecko/20100101 Firefox/89.0" --fragment-retries "infinite" -N 3 --no-mtime --download-archive archive.txt -P temp:D:\Temp\
pause`

**Comment by pukkandan** [comment]
> I need some way to check if mytitle contains a certain string so it can use the fallback but I'm hopeless at this....
-o "%%(extractor)s\%%(mytitle|title)s - %%(myindex)s.%%(ext)s" --parse-metadata "webpage_url:#%%(myindex)s" --parse-metadata "%%(series)s - S%%(season_number)sE%%(episode_number)s:%%(mytitle)s"

You were on the right track. But there are 2 issues
1. Even if the fields are absent, mytitle will still be popylated with something like `NA - SNAENA`
2. The right side of `|` is treated literally, not as the name of a field

This is what you want:
```
$ yt-dlp "https://www.zee5.com/movies/details/krishna-the-birth/0-0-63098#50" "https://zee5.com/tvshows/details/krishna-balram/0-6-1871/episode-1-the-test-of-bramha/0-1-233402#20" -O "%(extractor)s\%(title)s - %(myindex)s.%(ext)s" --parse-metadata "webpage_url:#%(myindex)s" --parse-metadata "%(series)s - S%(season_number)sE%(episode_number)s:^(?P<title>.+ - S\d+E\d+)$" --output-na-placeholder ""
WARNING: Could not interpret video %(series)s - S%(season_number)sE%(episode_number)s as "^(?P<title>.+ - S\d+E\d+)$"
Zee5\Krishna - The Birth - 50.mp4
Zee5\Krishna Balram - S1E1 - 20.mp4
```

This will use `%(series)s - S%(season_number)sE%(episode_number)s` if all 3 of these fields are present, else it will use `%(title)s`. ofc, change `-O` to `-o` and escape the `%` as needed

**Comment by Jules-A** [comment]
I see, thanks a tonne! Still can't seem to wrap my head around Python regex (regex in general gives me headaches so I usually try to avoid it even in other languages...).
