### ISSUE TITLE
Is it possible to get a double quoted output from the option "--print chapters" instead of single quoted one?

### ISSUE THREAD

**Issue by SeyRyuu** [yt-dlp/yt-dlp#3734]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

Hey there,

i am forcing an issue to get the returned data from the `--print chapters` option as double quoted string to archive a valid parse-able json syntax. Is it possible to get the result of this option as double quoted (") output instead of single quoted (')? 

For example i get the following output from this command (full exec to reproduce in "verbose log"): 
`yt-dlp.exe --print chapters https://www.youtube.com/watch?v=GIq3pcdz4Sw`
returns -> `[{'start_time': 0.0, 'title': 'Typical James', 'end_time': 12.0}, ........`

I want something like this returned:
-> `[{"start_time": 0.0, "title": "Typical James", "end_time": 12.0}, ........`

Target is to be able to parse the output from the option  `--print chapters` as json, but the json standard requires double quotes.

Any solutions on this?

Kind regards

### Verbose log

```shell
Cmd: yt-dlp.exe -vU --print chapters https://www.youtube.com/watch?v=GIq3pcdz4Sw

[debug] Command-line config: ['-vU', '--print', 'chapters', 'https://www.youtube.com/watch?v=GIq3pcdz4Sw']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.04.08 [7884ade] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.22000-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: avprobe -bsfs
[debug] exe versions: ffmpeg 2022-02-03-git-e1a14479a8-full_build-www.gyan.dev (setts)
[debug] Optional libraries: brotli, certifi, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.04.08, Current version: 2022.04.08
yt-dlp is up to date (2022.04.08)
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=GIq3pcdz4Sw
[youtube] GIq3pcdz4Sw: Downloading webpage
[youtube] GIq3pcdz4Sw: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] GIq3pcdz4Sw: Downloading 1 format(s): 313+251
[{'start_time': 0.0, 'title': 'Typical James', 'end_time': 12.0}, {'start_time': 12.0, 'title': 'Anandtech 11700K review', 'end_time': 82.0}, {'start_time': 82.0, 'title': 'RTX 3080 Ti and 3050 Ti leaks', 'end_time': 142.0}, {'start_time': 142.0, 'title': 'Nintendo Switch Pro rumors', 'end_time': 190.0}, {'start_time': 190.0, 'title': 'Seasonic', 'end_time': 230.0}, {'start_time': 230.0, 'title': 'QUICK BITS', 'end_time': 234.0}, {'start_time': 234.0, 'title': 'No default app switching on iOS', 'end_time': 270.0}, {'start_time': 270.0, 'title': 'Facebook AI supervise themselves', 'end_time': 304.0}, {'start_time': 304.0, 'title': 'Fingerprint-reading credit cards', 'end_time': 336.0}, {'start_time': 336.0, 'title': "Bungie won't fix Destiny 2 bug", 'end_time': 360.0}, {'start_time': 360.0, 'title': '8-year old pro Fortnite player', 'end_time': 400}]
```

**Comment by Lesmiscore** [comment]
I think you want to get it in JSON format, try this: `--print "%(chapters)j`

**Comment by SeyRyuu** [comment]
Yes, that is exactly what i was looking for! 

Thanks for your reply @Lesmiscore.

Kind regards
