### ISSUE TITLE
AudioDraft

### ISSUE THREAD

**Issue by upintheairsheep** [yt-dlp/yt-dlp#3735]
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.04.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

USA, North America, Earth, Solar System, The Milky Way galaxy, The Frontrooms, the multiverse

### Example URLs

http://nokiatune.audiodraft.com/

### Description

Please also support all metadata

### Verbose log

```shell
Not attempted
```

**Comment by gamer191** [comment]
By the way, if you want to get an actual link to a specific audio track, you have to add /entry to the end of the URL, followed by a / and the number to the left of the name of the audio track. For example: http://nokiatune.audiodraft.com/entry/708
Here's a verbose log:
```
[debug] Command-line config: ['http://nokiatune.audiodraft.com/entry/708', '--verbose']
[debug] User config "C:\Users\redacted\AppData\Roaming\yt-dlp\config.txt": ['--ffmpeg-location', 'C:\\Users\\redacted\\ffmpeg\\bin', '--update', '-P', 'C:\\Users\\redacted\\youtube.dl', '--audio-quality', '0', '--write-subs', '--write-auto-subs', '--embed-subs', '--compat-options', 'no-keep-subs']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.04.08 [7884ade] (win_exe)
[debug] Compatibility options: no-keep-subs
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] Checking exe version: "C:\Users\redacted\ffmpeg\bin\ffmpeg" -bsfs
[debug] Checking exe version: "C:\Users\redacted\ffmpeg\bin\ffprobe" -bsfs
[debug] exe versions: ffmpeg N-106498-g854615adf2-20220405 (setts), ffprobe N-106498-g854615adf2-20220405
[debug] Optional libraries: brotli, certifi, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.04.08, Current version: 2022.04.08
yt-dlp is up to date (2022.04.08)
[debug] [generic] Extracting URL: http://nokiatune.audiodraft.com/entry/708
[generic] 708: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] 708: Downloading webpage
[generic] 708: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: http://nokiatune.audiodraft.com/entry/708
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1408, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1478, in __extract_info
  File "yt_dlp\extractor\common.py", line 641, in extract
  File "yt_dlp\extractor\generic.py", line 4039, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: http://nokiatune.audiodraft.com/entry/708
```

**Comment by HobbyistDev** [comment]
Duplicate / related : #4028
