### ISSUE TITLE
[Site Request] Support for twitcasting livestreams

### ISSUE THREAD

**Issue by Lytexx** [yt-dlp/yt-dlp#374]
## Checklist

- [x] I'm reporting a site feature request
- [x] I've verified that I'm running yt-dlp version **2021.06.01**
- [x] I've searched the bugtracker for similar site feature requests including closed ones

## Description

currently when trying to download a running twitcasting livestream yt-dlp gives out this error
`ERROR: Unsupported URL: https://ssl.twitcasting.tv/c:kurokuroyami/twplayer?r9975`

active livestreams can be found here https://twitcasting.tv/?ch0

the m3u8 url is always `http://twitcasting.tv/[id]/metastream.m3u8`
where [id] is the username of the streamer

using yt-dlp with `--downloader ffmpeg` already works but it would be nice if it could be properly supported

**Comment by nao20010128nao** [comment]
NOTE for contributors/collaborators: Looks like such URLs don't appear in websites, it's better to specify m3u8 URL above directly like this;
https://github.com/ytdl-patched/ytdl-patched/blob/master/youtube_dl/extractor/twitcasting.py#L107
