### ISSUE TITLE
item selection by -F list designator - wrong item downloaded

### ISSUE THREAD

**Issue by jimlynnjulian** [yt-dlp/yt-dlp#3740]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

When I use the '-F' option too list all possible download options, there is a designator for each possibility in the table. Can a choice be downloaded by using the designator, such as 'mobile' or 'hls-165' in the example below?

C:\yt-dlp>yt-dlp -F https://ok.ru/video/1661091908134
[Odnoklassniki] 1661091908134: Downloading desktop webpage
[Odnoklassniki] 1661091908134: Downloading m3u8 information
[info] Available formats for 1661091908134:
ID      EXT RESOLUTION FPS │    FILESIZE  TBR PROTO  │ VCODEC       VBR ACODEC    ABR     ASR MORE INFO
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────
mobile  mp4 unknown        │                  https  │ unknown          unknown
hls-165 mp4 192x144     30 │ ~ 218.53MiB 165k m3u8_n │ unknown     165k unknown    0k
mpd-0   mp4 192x144     30 │ ~ 162.29MiB 122k https  │ avc1.64000C 122k mp4a.40.2  0k 44100Hz DASH video, mp4_dash
lowest  mp4 unknown        │                  https  │ unknown          unknown
hls-421 mp4 320x240     30 │ ~ 557.16MiB 421k m3u8_n │ unknown     421k unknown    0k
mpd-1   mp4 320x240     30 │ ~ 474.76MiB 359k https  │ avc1.64000D 359k mp4a.40.2  0k 44100Hz DASH video, mp4_dash
low     mp4 unknown        │                  https  │ unknown          unknown
hls-773 mp4 480x360     30 │ ~1022.52MiB 773k m3u8_n │ unknown     773k unknown    0k
mpd-2   mp4 480x360     30 │ ~ 904.95MiB 684k https  │ avc1.64001E 684k mp4a.40.2  0k 44100Hz DASH video, mp4_dash

**Comment by elyse0** [comment]
Yep, you can select a format with the option -f 

In your case, this should work

```bash
yt-dlp -f 'hls-165' https://ok.ru/video/1661091908134 -o video.mp4
```
**Note:** I'm using `-o video.mp4` to specify a different filename, because the original is too long


You can find more details about format selection here: https://github.com/yt-dlp/yt-dlp#format-selection

**Comment by jimlynnjulian** [comment]
> 

Hello Elyse, 
I tried your suggestion, but I got this error when I tried:

"C:\yt-dlp>yt-dlp -f 'hls-165' https://ok.ru/video/1661091908134 -o video.mp4
[Odnoklassniki] 1661091908134: Downloading desktop webpage
[Odnoklassniki] 1661091908134: Downloading m3u8 information
ERROR: [Odnoklassniki] 1661091908134: Requested format is not available. Use --list-formats for a list of available formats"

I ran the suggested option and the 'hls-165' option was listed.

  Addendum: I tried another option 'mobile' but that didn't work either. Then I had the idea of eliminating the single quotes and tried that. Oddly, that worked on the 'hls-165' but not on the 'mobile' selection. I've posted the results below. Thanks.

C:\yt-dlp>yt-dlp -f 'mobile' https://ok.ru/video/1661091908134 -o video.mp4
[Odnoklassniki] 1661091908134: Downloading desktop webpage
[Odnoklassniki] 1661091908134: Downloading m3u8 information
ERROR: [Odnoklassniki] 1661091908134: Requested format is not available. Use --list-formats for a list of available formats

C:\yt-dlp>yt-dlp -f mobile https://ok.ru/video/1661091908134 -o video.mp4
[Odnoklassniki] 1661091908134: Downloading desktop webpage
[Odnoklassniki] 1661091908134: Downloading m3u8 information
[info] 1661091908134: Downloading 1 format(s): mobile
ERROR: unable to download video data: HTTP Error 400: Bad Request

C:\yt-dlp>yt-dlp -f hls-165 https://ok.ru/video/1661091908134 -o video.mp4
[Odnoklassniki] 1661091908134: Downloading desktop webpage
[Odnoklassniki] 1661091908134: Downloading m3u8 information
[info] 1661091908134: Downloading 1 format(s): hls-165
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 1083
[download] Destination: video.mp4
[download]   0.7% of ~222.21MiB at 174.43KiB/s ETA 22:17 (frag 8/1083) <--- ongoing download

**Comment by jimlynnjulian** [comment]
Thanks elyse0. Both problems solved, item selection method and long filename issue.

**Comment by elyse0** [comment]
Great! 😄  Can you also close #3741 ?

**Comment by jimlynnjulian** [comment]
> Great! 😄 Can you also close #3741 ?

Yes, but the other issue may need to be reopened. I selected the 'hls-773' version, which was supposed to be 480x360 and got a 192x124 version instead, along with the following error:
"WARNING: 1661091908134: Possible MPEG-TS in MP4 container or malformed AAC timestamps. Install ffmpeg to fix this automatically"
The command line:
"yt-dlp -f hls-773 https://ok.ru/video/1661091908134 -o video.mp4"

What do you think?

**Comment by jimlynnjulian** [comment]
Re-oening this issue as a bug report.

**Comment by elyse0** [comment]
Can you paste your verbose log? 

Pass the option `-vU` to get it
```
yt-dlp -vU -f hls-773 https://ok.ru/video/1661091908134 -o video.mp4
```

**Comment by jimlynnjulian** [comment]
> Can you paste your verbose log?
> 
> Pass the option `-vU` to get it
> 
> ```
> yt-dlp -vU -f hls-773 https://ok.ru/video/1661091908134 -o video.mp4
> ```

Here it is:


C:\yt-dlp>yt-dlp -vU -f hls-773 https://ok.ru/video/1661091908134 -o video.mp4
[debug] Command-line config: ['-vU', '-f', 'hls-773', 'https://ok.ru/video/1661091908134', '-o', 'video.mp4']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.04.08 [7884ade] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.22000-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: avconv -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: avprobe -bsfs
[debug] exe versions: none
[debug] Optional libraries: brotli, certifi, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.04.08, Current version: 2022.04.08
yt-dlp is up to date (2022.04.08)
[debug] [Odnoklassniki] Extracting URL: https://ok.ru/video/1661091908134
[Odnoklassniki] 1661091908134: Downloading desktop webpage
[Odnoklassniki] 1661091908134: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[info] 1661091908134: Downloading 1 format(s): hls-773
[debug] Invoking downloader on "https://vd168.mycdn.me/expires/1652669534715/srcIp/24.158.192.34/srcAg/CHROME/ms/45.136.21.15/type/1/sig/2icbu4scd4A/ct/8/urls/185.226.52.38/clientType/0/zs/43/id/656297167398/video/"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 1083
[download] Destination: video.mp4
[debug] File locking is not supported on this platform. Proceeding without locking
[download]   0.2% of ~1.01GiB at 36.45KiB/s ETA 34:45 (frag 2/1083)

**Comment by jimlynnjulian** [comment]
This download will take approximately 20 more minutes.

**Comment by elyse0** [comment]
I've streamed both formats and for me it works as expected 🤔  

'hls-773' (480x360) is definitely better than ''hls-165'' (192x144)

### hls-773
![image](https://user-images.githubusercontent.com/26639800/168455270-ac9f1796-97d0-4e6a-a1fe-233f62be7b3a.png)

### hls-165
![image](https://user-images.githubusercontent.com/26639800/168455294-0490ae3a-c209-4d7e-871e-e9cb60b1ac4a.png)


Maybe you can try setting another filename? For example `video-773-mp4`, so we can avoid overwriting the same file

**Comment by elyse0** [comment]
> This download will take approximately 20 more minutes.

By the way, if you want to reduce the download time, you can set the option -N for multi-threaded fragment downloads

```
yt-dlp -f hls-165 -N 10 https://ok.ru/video/1661091908134 -o video-165.mp4
```

**Comment by jimlynnjulian** [comment]
> > This download will take approximately 20 more minutes.
> 
> By the way, if you want to reduce the download time, you can set the option -N for multi-threaded fragment downloads
> 
> ```shell
> yt-dlp -f hls-165 -N 10 https://ok.ru/video/1661091908134 -o video-165.mp4
> ```

Thanks.

**Comment by jimlynnjulian** [comment]
The download finished. This time a 480x360 was downloaded. Correct. I compared my command line with yours, including looking for text code differences, e.x. unicode, and found none. Except for the -vU

> I've streamed both formats and for me it works as expected 🤔
> 
> 'hls-773' (480x360) is definitely better than ''hls-165'' (192x144)
> 
> ### hls-773
> ![image](https://user-images.githubusercontent.com/26639800/168455270-ac9f1796-97d0-4e6a-a1fe-233f62be7b3a.png)
> 
> ### hls-165
> ![image](https://user-images.githubusercontent.com/26639800/168455294-0490ae3a-c209-4d7e-871e-e9cb60b1ac4a.png)
> 
> Maybe you can try setting another filename? For example `video-773.mp4`, so we can avoid overwriting the same file

I removed the files as soon as done.

**Comment by jimlynnjulian** [comment]
I'm going to assume I made a typo and close this. I'll do a couple of runs and if anything pops up, I'll re-open.
Thanks for your help. Good night and good luck.
