### ISSUE TITLE
[Question] `yt-dlp is not recognized as an internal or external command` in Batch file.

### ISSUE THREAD

**Issue by fosam** [yt-dlp/yt-dlp#3744]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

I created a very small batch file on Windows where i can put the link of the video and the path where it will be downloaded.

I'm 100% sure that it worked as it should when i created it, but now after i put the path where to download the video, i get his:

```
'yt-dlp' is not recognized as an internal or external command,
operable program or batch file.
```

And of course i have my yt-dlp folder added to the path.

<details>
<summary>These are the commands in the <b>.bat</b> file. </summary>

```
@echo off
set /p URL="Video Link "
set /p Path="Where to download "
yt-dlp -o "%Path%\%%(title)s %%(id)s.%%(ext)s" "%URL%"
```
</details>

It's not possible to generate any verbose log when running this batch.
<br />
<br />

Help is appreciated!

**Comment by gamer191** [comment]
Are you sure that you have yt-dlp added to your path? What happens if you navigate to a completely random folder and run 'yt-dlp —verbose'?

**Comment by pukkandan** [comment]
Question doesn't belong here. It is user error - The error is being generated by your shell, not yt-dlp

**Comment by fosam** [comment]
> Are you sure that you have yt-dlp added to your path? What happens if you navigate to a completely random folder and run 'yt-dlp —verbose'?

Then it works

**Comment by fosam** [comment]
> Question doesn't belong here. It is user error - The error is being generated by your shell, not yt-dlp

Please, any tips?
