### ISSUE TITLE
add download archive templete

### ISSUE THREAD

**Issue by afterdelight** [yt-dlp/yt-dlp#3745]
### Checklist

- [X] I'm reporting a feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.04.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

add download archive templete such as -download-archive "%(uploader)s\%(uploader)s_downloaded.txt"

i need to put the archive file into each download f0lders

**Comment by pukkandan** [comment]
What is your problem? From your comments in https://github.com/yt-dlp/yt-dlp/issues/953 and related issues, you clearly know this is a duplicate. If you continue to spam, I will be forced to block you

**Comment by afterdelight** [comment]
what!?

**Comment by pukkandan** [comment]
What what? You don't think this is a duplicate? Justify why you don't think this issue is spam
