### ISSUE TITLE
Nhaccuatui

### ISSUE THREAD

**Issue by zeref-dragneel** [yt-dlp/yt-dlp#3754]
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.04.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Vietnam

### Example URLs

https://www.nhaccuatui.com/video/tam-su-tuoi-30-the-first-show-trinh-thang-binh.Rcavsna6iCKkg.html

### Description

Nhaccuatui

### Verbose log

```shell
[debug] Command-line config: ['-vU', 'https://www.nhaccuatui.com/video/tam-su-tuoi-30-the-first-show-trinh-thang-binh.Rcavsna6iCKkg.html']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.04.08 [7884ade] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: avconv -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: avprobe -bsfs
[debug] exe versions: none
[debug] Optional libraries: brotli, certifi, Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.04.08, Current version: 2022.04.08
yt-dlp is up to date (2022.04.08)
[debug] [generic] Extracting URL: https://www.nhaccuatui.com/video/tam-su-tuoi-30-the-first-show-trinh-thang-binh.Rcavsna6iCKkg.html
[generic] tam-su-tuoi-30-the-first-show-trinh-thang-binh.Rcavsna6iCKkg: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] tam-su-tuoi-30-the-first-show-trinh-thang-binh.Rcavsna6iCKkg: Downloading webpage
[generic] tam-su-tuoi-30-the-first-show-trinh-thang-binh.Rcavsna6iCKkg: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://www.nhaccuatui.com/video/tam-su-tuoi-30-the-first-show-trinh-thang-binh.Rcavsna6iCKkg.html
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1408, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1478, in __extract_info
  File "yt_dlp\extractor\common.py", line 641, in extract
  File "yt_dlp\extractor\generic.py", line 4039, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.nhaccuatui.com/video/tam-su-tuoi-30-the-first-show-trinh-thang-binh.Rcavsna6iCKkg.html
```

**Comment by elyse0** [comment]
Hey @zeref-dragneel, I've been implementing an extractor for this site but currently it only downloads free formats

I noticed that we can get better qualities (i.e 720p, 1080p) with a vip account, so... do you have one?  So I can add them to the extractor

### Verbose log

```bash
[debug] Command-line config: ['-vU', 'https://www.nhaccuatui.com/video/tam-su-tuoi-30-the-first-show-trinh-thang-binh.Rcavsna6iCKkg.html']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.04.08 [7884ade65] (source)
[debug] Lazy loading extractors is disabled
[debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
[debug] Git HEAD: 66805aa30
[debug] Python version 3.8.10 (CPython 64bit) - Linux-5.4.0-113-generic-x86_64-with-glibc2.29
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: ffmpeg -bsfs
[debug] exe versions: ffmpeg N-106673-g058a1ff9b4-20220424 (setts), ffprobe N-106673-g058a1ff9b4-20220424, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.14.1, brotli-1.0.9, certifi-2021.10.08, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
Latest version: 2022.05.18, Current version: 2022.04.08
ERROR: You cannot update when running from source code; Use git to pull the latest changes
[debug] [Nct] Extracting URL: https://www.nhaccuatui.com/video/tam-su-tuoi-30-the-first-show-trinh-thang-binh.Rcavsna6iCKkg.html
[Nct] Rcavsna6iCKkg: Downloading webpage
[Nct] Rcavsna6iCKkg: Downloading XML
[debug] Default format spec: bestvideo*+bestaudio/best
[info] Rcavsna6iCKkg: Downloading 1 format(s): 0
[debug] Invoking http downloader on "https://f9-stream.nixcdn.com/PreNCT21/TamSuTuoi30TheFirstShow-TrinhThangBinh-7204083.mp4?st=S7JB4-4qTmxzOM81YqocGw&e=1653624281"
[download] Resuming download at byte 57227160
[download] Destination: Tâm Sự Tuổi 30 (The First Show) [Rcavsna6iCKkg].mp4
[download]  66.7% of 81.88MiB at 72.56KiB/s ETA 06:24
```

**Comment by zeref-dragneel** [comment]
I have a VIP account

**Comment by zeref-dragneel** [comment]
May I ask if this list is a complete list?
https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md

**Comment by gamer191** [comment]
> May I ask if this list is a complete list? https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md

It's a complete list of sites that are supported by yt-dlp, but not a complete list of sites that work with yt-dlp. There's also no guarantee that sites on that list will currently work, especially because yt-dlp currently has 541 open issues. Also, you're welcome to report problems occurring in sites not on that list. One could argue that that list has no real purpose beyond marketing.
