### ISSUE TITLE
[QUESTION] how to extract links from iwara.tv page

### ISSUE THREAD

**Issue by afterdelight** [yt-dlp/yt-dlp#3758]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

sometimes the uploaders from iwara.tv provide links to 1080p version such as mega.nz etc 
how to parse/extract them from iwara.tv video page description 

example link:
https://www.iwara.tv/videos/LolAcbK0Upy63Jb

**Comment by Lesmiscore** [comment]
Use `--print description` to get the field.
```
$ yt-dlp --print description https://www.iwara.tv/videos/LolAcbK0Upy63Jb
New Encoder "Natsurenko" Test<br />
1920x1080 fps60 143.98MB</p>
<p>motion<br />
<a href="http://u3.getuploader.com/madcatz/download/1035/yazawa_niko_motion.zip">http://u3.getuploader.com/madcatz/download/1035/yazawa_niko_motion.zip</a></p>
```
And do the fuck you want.

**Comment by pukkandan** [comment]
Use `--parse-metadata` to extract it into a new field

**Comment by Lesmiscore** [comment]
Google or DuckDuckGo is your friend.
https://www.google.com/search?q=how+to+extract+url+from+console+output
https://duckduckgo.com/?q=how+to+extract+url+from+console+output

Further discussion beyond extracting description must continue at different forums.

**Comment by afterdelight** [comment]
nice, thanks
