### ISSUE TITLE
issues skipping live streams

### ISSUE THREAD

**Issue by phyzical** [yt-dlp/yt-dlp#3763]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

Hey there, ive found a similar question asked which suggested `--match-filter !is_live`, but i also use other match-filters for public videos only.

ive tried ` --match-filter "!is_live & availability = 'public'" ` and ` --match-filter !is_live   --match-filter "availability = 'public'" ` 
i also tried ` --match-filter "live_status='not_live' & availability = 'public'" `

but i keep getting items listed as "starting soon" or "offline.". any idea why i might still be getting live streams?

an example that is returned is this one https://www.youtube.com/watch?v=ZFVIiC4M1Sg

thanks!

### Verbose log

```shell
-f "bv*[ext=mp4]+ba[ext=m4a]" --download-archive "$channelName.txt" --write-thumbnail --add-metadata --no-write-playlist-metafiles --compat-options no-youtube-unavailable-videos --sponsorblock-remove "default"  --write-auto-sub --cookies cookies.txt --write-info-json --convert-subs=srt --sub-lang "en"  --match-filter "availability = 'public'" --datebefore $(date -d "-1 months" '+%Y%m%d') --merge-output-format mp4 -o "%(upload_date)s.%(title)s.%(ext)s" "UUlnDI2sdehVm1zm_LmUHsjQ"

Tue May 17 13:15:40 2022 [download] Downloading video 526 of 577
Tue May 17 13:15:40 2022 [youtube] ZFVIiC4M1Sg: Downloading webpage
Tue May 17 13:15:40 2022 [youtube] ZFVIiC4M1Sg: Downloading android player API JSON
ERROR: [youtube] ZFVIiC4M1Sg: Offline.
```

**Comment by pukkandan** [comment]
That is expected. The example given isn't live (has a live_status=upcoming). You could use something like `--ignore-no-formats --match-filter live_status=not_live`, but I don't see why you'd bother tbh. The offline video obv will not download either way

**Comment by phyzical** [comment]
@pukkandan thanks support as always,

sorry i don't want to download it i want to skip it so the run doesn't return a non 0 exit code (i loop over multiple urls one by one)

i havnt tried yet but why would `--ignore-no-formats --match-filter live_status=not_live` skip it out of curiosity?

i would have thought my attempt of `--match-filter "live_status='not_live' & availability = 'public'"` would have sufficed?

**Comment by pukkandan** [comment]
You need to add `--ignore-no-formats` or yt-dlp will raise "Stream offline" error before checking the filter. This behavior cannot be changed for compatibility reasons. That is why that switch was added

**Comment by pukkandan** [comment]
btw, It's not clear from your question, but you may want to allow `was_live` too

> `live_status` (string): One of "is_live", "was_live", "is_upcoming", "not_live"

**Comment by phyzical** [comment]
ahhh thatll be why 👍 yeah i saw `was_live` and tried that too as was suspicious at the time, thanks for the clarifications :)

**Comment by phyzical** [comment]
@pukkandan one more clarification does the match-filter support mutliple for the same filter or do i do multiple & s i.e

`--match-filter "live_status='not_live, was_live' & availability = 'public'"` or `--match-filter "live_status='not_live' & live_status='was_live' & availability = 'public'"`

**Comment by pukkandan** [comment]
--match-filter "!is_live & live_status!=is_upcoming & availability=public"

**Comment by estatistics** [comment]
```yt-dlp  --username oauth2 --password '' --check-formats  --retries 1000 --fragment-retries 20 --retry-sleep 120 --cookies-from-browser firefox --limit-rate 800k --write-description  --download-archive archive.txt -o "%(title)s_[%(id)s].%(ext)s" --match-filter "!is_live & live_status!=is_upcoming" --match-title "lipa" -- "ytsearch400:dua lipa"  ohL-jzgFLto zUirCbVfSFg uOz-vvp1wxY```

`bash: !is_live: event not found`

**Comment by estatistics** [comment]
```yt-dlp  --username oauth2 --password '' --check-formats  --retries 1000 --fragment-retries 20 --retry-sleep 120 --limit-rate 800k --write-description  --download-archive archive.txt -o "%(title)s_[%(id)s].%(ext)s" --match-filter "live_status!~='post_live|is_live'" --match-title "lipa" -- "ytsearch400:dua lipa"  ohL-jzgFLto zUirCbVfSFg uOz-vvp1wxY```
bash: !~='post_live: event not found
