### ISSUE TITLE
spotify podcast

### ISSUE THREAD

**Issue by Brandhand** [yt-dlp/yt-dlp#3768]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.04.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Germany

### Description

For almost a week it's not possible to download the podcast show with the url
https://open.spotify.com/show/1OLcQdw2PFDPG1jo3s0wbp
anymore.

### Verbose log

```shell
yt-dlp  https://open.spotify.com/show/1OLcQdw2PFDPG1jo3s0wbp  --verbose
[debug] Command-line config: ['https://open.spotify.com/show/1OLcQdw2PFDPG1jo3s0wbp', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.04.08 [7884ade65] (zip)
[debug] Python version 3.9.2 (CPython 64bit) - Linux-5.16.0-0.bpo.4-amd64-x86_64-with-glibc2.31
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.3.4-0, ffprobe 4.3.4-0, rtmpdump 2.4
[debug] Optional libraries: brotli, certifi, mutagen, sqlite
[debug] Proxy map: {}
[spotify:show] Downloading JSON metadata
[debug] [spotify:show] Extracting URL: https://open.spotify.com/show/1OLcQdw2PFDPG1jo3s0wbp
[spotify:show] 1OLcQdw2PFDPG1jo3s0wbp: Downloading JSON metadata
ERROR: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/home/meikel/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1408, in wrapper
    return func(self, *args, **kwargs)
  File "/home/meikel/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1478, in __extract_info
    ie_result = ie.extract(url)
  File "/home/meikel/bin/yt-dlp/yt_dlp/extractor/common.py", line 641, in extract
    ie_result = self._real_extract(url)
  File "/home/meikel/bin/yt-dlp/yt_dlp/extractor/spotify.py", line 141, in _real_extract
    podcast = self._call_api('ShowEpisodes', show_id, {
TypeError: 'NoneType' object is not subscriptable
```

**Comment by Brandhand** [comment]
Found something. The Limit is set to high. Reducing it works but won't get all episodes:
```shell
modified   yt_dlp/extractor/spotify.py
@@ -147,7 +147,7 @@ class SpotifyShowIE(SpotifyBaseIE):
     def _real_extract(self, url):
         show_id = self._match_id(url)
         podcast = self._call_api('ShowEpisodes', show_id, {
-            'limit': 1000000000,
+            'limit': 100,
             'offset': 0,
             'uri': 'spotify:show:' + show_id,
         })['podcast']
 ```
So the requests have to be paginated (if that's the right word). But that's beyond my capabilities.

**Comment by joonas-foo** [comment]
Hi! I'm having a problem downloading podcasts from Spotify, I get this error:

--
joonas@joonas-MS-7D95:~$ yt-dlp --no-mtime https://open.spotify.com/episode/3zqQZaet8MKdbeXF9Z9guF
WARNING: The program functionality for this site has been marked as broken, and will probably not work.
[spotify] Downloading JSON metadata
[spotify] Extracting URL: https://open.spotify.com/episode/3zqQZaet8MKdbeXF9Z9guF
[spotify] 3zqQZaet8MKdbeXF9Z9guF: Downloading JSON metadata
ERROR: [spotify] 3zqQZaet8MKdbeXF9Z9guF: Unable to download JSON metadata: HTTP Error 400: Bad Request (caused by <HTTPError 400: Bad Request>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
--
