### ISSUE TITLE
discovery+ subtitle

### ISSUE THREAD

**Issue by ilpadrinocl** [yt-dlp/yt-dlp#3779]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

I download https://www.discoveryplus.com/it/video/johnny-depp-contro-amber-heard-il-processo/stagione-1-episodio-1-la-versione-di-johnny but download me episode in english and subtitle a file in mp4..how i merge video with subtitle in mp4?

thanks

**Comment by pukkandan** [comment]
You can't with yt-dlp. See https://github.com/yt-dlp/yt-dlp/issues/656#issuecomment-894867089
