### ISSUE TITLE
ERROR: unable to open for writing

### ISSUE THREAD

**Issue by Explosion-Scratch** [yt-dlp/yt-dlp#3780]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.05.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

I'm getting the error seen in the log below (`ERROR: unable to open for writing: [Errno 95] Operation not supported`), this is **not due to missing write permissions in the output folder**. I can create and edit files with `nano` and `touch <filename>`. I also ran `sudo chmod 777 ./` and tried again. I also gave permissions on the cache folder and it still seems to not work.

### Verbose log

```shell
explosion@penguin:/mnt/chromeos/MyFiles/Downloads/.movies$ sudo yt-dlp https://www.youtube.com/playlist?list=PL96C35uN7xGIEA87qPL0DVYqfLm25WHC_ --verbose
[debug] Command-line config: ['https://www.youtube.com/playlist?list=PL96C35uN7xGIEA87qPL0DVYqfLm25WHC_', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.05.18 [b14d52355] (zip)
[debug] Python version 3.9.2 (CPython 64bit) - Linux-5.10.106-15290-g6e9d70c8a9b4-x86_64-with-glibc2.31
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: avprobe -bsfs
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: avconv -bsfs
[debug] exe versions: none
[debug] Optional libraries: sqlite3-2.6.0
[debug] Proxy map: {}
[debug] [youtube:tab] Extracting URL: https://www.youtube.com/playlist?list=PL96C35uN7xGIEA87qPL0DVYqfLm25WHC_
[youtube:tab] PL96C35uN7xGIEA87qPL0DVYqfLm25WHC_: Downloading webpage
[debug] [youtube:tab] Final URL: https://www.youtube.com/playlist?list=PL96C35uN7xGIEA87qPL0DVYqfLm25WHC_
AwRAIgV6_fhKtHbPa9Okm6-n_YIPvcd42h_nkNt-JMAXL-4f4CIHgSDCj0Vi_jM4rLz5nXn4Y3WfHsXQOn1sC6iY5tqrid"
ERROR: unable to open for writing: [Errno 95] Operation not supported
Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/utils.py", line 1999, in _lock_file
    fcntl.flock(f, flags)
OSError: [Errno 95] Operation not supported

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/downloader/http.py", line 267, in download
    ctx.stream, ctx.tmpfilename = self.sanitize_open(
  File "/usr/local/bin/yt-dlp/yt_dlp/downloader/common.py", line 224, in inner
    return func(self, *args, **kwargs)
  File "/usr/local/bin/yt-dlp/yt_dlp/downloader/common.py", line 241, in sanitize_open
    f, filename = sanitize_open(filename, open_mode)
  File "/usr/local/bin/yt-dlp/yt_dlp/utils.py", line 621, in sanitize_open
    stream = locked_file(filename, open_mode, block=False).__enter__()
  File "/usr/local/bin/yt-dlp/yt_dlp/utils.py", line 2045, in __enter__
    _lock_file(self.f, exclusive, self.block)
  File "/usr/local/bin/yt-dlp/yt_dlp/utils.py", line 2003, in _lock_file
    fcntl.lockf(f, flags)
OSError: [Errno 95] Operation not supported
```

**Comment by sulyi** [comment]
What does `flock -xn <filename> -c sleep 1 && echo locked || echo failed` do on mounted fs?
(See also: flock manual under notes about deadlock, NFS and CIFS.)

Also how can this even happen before: https://github.com/yt-dlp/yt-dlp/blob/926ccc84ef91498f3147b07d15eb5f40cd070471/yt_dlp/YoutubeDL.py#L1646

**Comment by Explosion-Scratch** [comment]
I tried installing yt-dlp in gitpod.io and then downloading and it worked fine, anyways, here is the `flock` output:
```bash
$ pwd
/mnt/chromeos/MyFiles/Downloads/.movies
$ flock -xn /mnt/chromeos -c "sleep 1" && echo locked || echo failed
locked
```

Here is the (partial) output of `findmnt` (scroll right to see permissions):
```
├─/mnt/chromeos                       9p                                           9p         rw,nosuid,nodev,relatime,sync,dirsync,access=any,trans=fd,rfd=26,wfd=26
├─/mnt/external                       tmpfs                                        tmpfs      rw,nosuid,nodev,noexec,relatime,mode=755
└─/opt/google/cros-containers         /dev/vda                                     ext4       ro,relatime
```

**Comment by Explosion-Scratch** [comment]
And here's my linux OS (Running Linux in a VM on a chromebook):
```
         _,met$$$$$gg.           explosion@penguin
      ,g$$$$$$$$$$$$$$$P.        OS: Debian 
    ,g$$P""       """Y$$.".      Kernel: x86_64 Linux 5.10.106-15290-g6e9d70c8a9b4
   ,$$P'              `$$$.      Uptime: 11m
  ',$$P       ,ggs.     `$$b:    Packages: 697
  `d$$'     ,$P"'   .    $$$     Shell: bash 5.1.4
   $$P      d$'     ,    $$P     Resolution: 1920x1080
   $$:      $$.   -    ,d$$'     WM: Sommelier
   $$\;      Y$b._   _,d$P'      GTK Theme: CrosAdapta [GTK2/3]
   Y$$.    `.`"Y$$$$P"'          Font: Roboto 11
   `$$b      "-.__               Disk: 4.3G / 24G (19%)
    `Y$$                         CPU: Intel Celeron N4020 @ 2x 1.094GHz
     `Y$$.                       RAM: 5MiB / 2775MiB
       `$$b.                    
         `Y$$b.                 
            `"Y$b._             
                `""""           
                                
```

**Comment by sulyi** [comment]
I'm shooting in the dark here, sorry, but how about `trans=virtio` instead `trans=fd,rfd=26,wfd=26`?

**Comment by Explosion-Scratch** [comment]
Where do I set that? A bash variable? Editing the python script?

**Comment by sulyi** [comment]
For testing you could try remounting it manually. For more permanent, you need to find what mounts it in the first place (like in vm volume settings).
But if that's causing this issue, it's not related to yt-dlp.

**Comment by Explosion-Scratch** [comment]
> For testing you could try remounting it manually. For more permanent, you need to find what mounts it in the first place (like in vm volume settings). But if that's causing this issue, it's not related to yt-dlp.

I can't remount, and this issue isn't happening with:
1) An online VM (gitpod)
2) `youtube-dl`

And I just installed the VM which this is all run on, vanilla frameworks, no nothing messing with permissions

**Comment by sulyi** [comment]
Default VM setting may differ and might not suite all needs. But comparing them might be helpful.
Mentioned, youtube-dl does not use file locking.

Just to rule out for sure. Does this occur even when downloading with same VM, but to location not on a `9p` filesystem?

**Comment by Explosion-Scratch** [comment]
Wait, that fixed it? Thanks!

**Comment by pukkandan** [comment]
It doesn't fix whatever was preventing the lock (that is not a yt-dlp issue), but I made this error non-fatal. So the download now proceeds without locking

**Comment by cameronj86** [comment]
It could be Chromebook-related as I'm experiencing the same thing. With me, the difference is that I'm using SMB to connect to a desktop PC. I too have read/write access to the file though (and can create/delete files using the Chromebook VM (or accessing the desktop PC via Chromebook's file explorer).

My current workaround will be to save files locally on the Chromebook and eventually create a script to push the files manually to the desktop.

**Comment by Explosion-Scratch** [comment]
Not happening for me anymore ironically

**Comment by cameronj86** [comment]
It saves when I use Downloads/MyFiles fwiw (which I believe was what you were using initially), just not the mounted SMB. #FirstWorldProblems
