### ISSUE TITLE
Download only the info-json file

### ISSUE THREAD

**Issue by Lucabenj** [yt-dlp/yt-dlp#3781]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

Can you download only the info-json file without downloading the video file?

**Comment by pukkandan** [comment]
`--skip-download --write-info-json`
