### ISSUE TITLE
Show auto-generated subtitle on top.

### ISSUE THREAD

**Issue by Rexadev** [yt-dlp/yt-dlp#3782]
### Checklist

- [X] I'm reporting a feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.05.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

`yt-dlp --list-subs --skip-download URL ` gives a list of all subtitles then below than is the list of auto-generated sub mixed with its translation.
Example their are 2 for English

```
en-orig  English (Original)    vtt, ttml, srv3, srv2, srv1, json3
en       English               vtt, ttml, srv3, srv2, srv1, json3
```

I believe original is the auto generated and English is translated to English

I would like the English Original (or *Language Original) to be show on top or be marked with a * to indicate that it is the non-translated version

**Comment by pukkandan** [comment]
`en` and `en-orig` are actually the same in this case. It is repeated to maintain compat while also allowing user to easily select the original langauge (`--sub-lang .+-orig`)

> I would like the English Original (or *Language Original) to be show on top or be marked with a * to indicate that it is the non-translated version

Why is the `-orig` and `(Original)` labels not sufficient?
