### ISSUE TITLE
[Instagram] Main webpage is locked behind the login page.

### ISSUE THREAD

**Issue by RingoTheDog** [yt-dlp/yt-dlp#3785]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.05.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

canada

### Description

This was previously fixed in https://github.com/yt-dlp/yt-dlp/pull/2095  
...but maybe Instagram changed something again?

URL: https://www.instagram.com/p/Cds4SYElpYz/

**The download DOES WORK if you use: 
--cookies instagram.com_cookies.txt

### Verbose log

```shell
>yt-dlp.py -v "https://www.instagram.com/p/Cds4SYElpYz/"
[debug] Command-line config: ['-v', 'https://www.instagram.com/p/Cds4SYElpYz/']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.05.18 [b14d52355] (zip)
[debug] Python version 3.6.6 (CPython 64bit) - Windows-10-10.0.14393-SP0
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: ffmpeg -bsfs
[debug] exe versions: ffmpeg 4.3.2-2021-02-02-full_build-www.gyan.dev, ffprobe 4.3.2-2021-02-02-full_build-www.gyan.dev, rtmpdump 2.4
[debug] Optional libraries: sqlite3-2.6.0
[debug] Proxy map: {}
[debug] [Instagram] Extracting URL: https://www.instagram.com/p/Cds4SYElpYz/
[Instagram] Cds4SYElpYz: Downloading webpage
WARNING: [Instagram] Main webpage is locked behind the login page. Retrying with embed webpage (Note that some metadata might be missing)
[Instagram] Cds4SYElpYz: Downloading embed webpage
ERROR: [Instagram] Cds4SYElpYz: You need to log in to access this content. Use --cookies, --cookies-from-browser, --username and --password, or --netrc (instagram) to provide account credentials
  File "C:\Transmogrifier\yt-dlp.py\yt_dlp\extractor\common.py", line 642, in extract
    ie_result = self._real_extract(url)
  File "C:\Transmogrifier\yt-dlp.py\yt_dlp\extractor\instagram.py", line 393, in _real_extract
    self.raise_login_required('You need to log in to access this content')
  File "C:\Transmogrifier\yt-dlp.py\yt_dlp\extractor\common.py", line 1140, in raise_login_required
    raise ExtractorError(msg, expected=True)
```

Thanks,
Ringo

**Comment by pukkandan** [comment]
Are you able to open the webpage in an incognito window from the same IP?

**Comment by pukkandan** [comment]
> Both "normal" and incognito prompt for instagram login...

Then how do you expect yt-dlp to work without cookies?

**Comment by laura01143** [comment]
After four years of ownership, a burglar updated the related phone number and email address to take control of my Instagram account. It took me less than two hours to get back into my account thanks to the assistance of a recovery agent named Marie_Consultancy who was suggested by a friend. For help with account recovery, I heartily suggest Marie_Consultancy, who works at META, as she has shown herself to be dependable and trustworthy. If you need assistance with something similar, reach her at Marieconsultancyoz@gmail com or on Instagram at Marie_consultancy.
