### ISSUE TITLE
Download speed causes jitter in terminal output

### ISSUE THREAD

**Issue by valtism** [yt-dlp/yt-dlp#3790]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.05.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

Encountered while downloading this video: https://www.youtube.com/watch?v=8qP2H1d8XXI

The download indicator in the terminal would jitter horizontally because the speed indicator seems to not be padded to a single size.

You can look at how the issue works in this REPL: https://replit.com/@DanielWood2/yt-dlp-console-speed?v=1 (uses functions from `common.py` and `utils.py`)

```
Actual output
-    0.00B/s -
- 1023.00B/s -
-  1.00KiB/s -
- 999.99KiB/s -
- 1000.00KiB/s -
-  1.91MiB/s -

Expected output
-    0.00B/s   -
- 1023.00B/s   -
-    1.00KiB/s -
-  999.99KiB/s -
- 1000.00KiB/s -
-    1.91MiB/s -
```

You can see how the current `format_speed` implementation does not properly pad the output string and leads to jitter on the download output.

### Verbose log

```shell
[debug] Command-line config: ['-vU', 'https://www.youtube.com/watch?v=8qP2H1d8XXI&t=1810s']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.05.18 [b14d52355]
[debug] Python version 3.10.4 (CPython 64bit) - macOS-12.3.1-x86_64-i386-64bit
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: ffmpeg -bsfs
[debug] exe versions: ffmpeg 5.0.1 (setts), ffprobe 5.0.1
[debug] Optional libraries: Cryptodome-3.14.1, brotli-1.0.9, certifi-2021.10.08, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
Latest version: 2022.05.18, Current version: 2022.05.18
yt-dlp is up to date (2022.05.18)
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=8qP2H1d8XXI&t=1810s
[youtube] 8qP2H1d8XXI: Downloading webpage
[youtube] 8qP2H1d8XXI: Downloading android player API JSON
[youtube] 8qP2H1d8XXI: Downloading m3u8 information
[youtube] 8qP2H1d8XXI: Downloading MPD manifest
[youtube] 8qP2H1d8XXI: Downloading m3u8 information
[youtube] 8qP2H1d8XXI: Downloading MPD manifest
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 8qP2H1d8XXI: Downloading 1 format(s): 301
[debug] Invoking hlsnative downloader on "https://manifest.googlevideo.com/api/manifest/hls_playlist/expire/1652956343/ei/V8iFYvyxN7DnrtoPtauDwAY/ip/2406:3400:209:420:a57d:e93b:ef18:a595/id/8qP2H1d8XXI.1/itag/301/source/yt_live_broadcast/requiressl/yes/ratebypass/yes/live/1/sgoap/gir%3Dyes%3Bitag%3D140/sgovp/gir%3Dyes%3Bitag%3D299/hls_chunk_host/rr2---sn-xmxuxa-ntql.googlevideo.com/force_finished/1/vprv/1/playlist_type/CLEAN/initcwndbps/11860/mh/mW/mm/44/mn/sn-xmxuxa-ntql/ms/lva/mv/m/mvi/2/pl/40/dover/11/pacing/0/keepalive/yes/fexp/24001373,24007246/beids/24153469/mt/1652934272/sparams/expire,ei,ip,id,itag,source,requiressl,ratebypass,live,sgoap,sgovp,force_finished,vprv,playlist_type/sig/AOq0QJ8wRAIgArr3kDOQGMI-yTBV6uZgFg4yozmd1GRJpkVv62sL0YYCIDewBDypkO3N8NvOf_KqXT7ldX0eFBt9VgMyZDs8h78I/lsparams/hls_chunk_host,initcwndbps,mh,mm,mn,ms,mv,mvi,pl/lsig/AG3C_xAwRQIhAIehiD1qGcbPe-MCMIA3AuEz34oaBpU-9prwHDpr4BGtAiBRBNbhy7-evaExp9I3ae-8yHTVgSHS4CiG6pljwNu00w%3D%3D/playlist/index.m3u8"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 2312
[download] Destination: STOP USING CREATE REACT APP - Web Dev Wednesday VOD [8qP2H1d8XXI].mp4
[download]   1.1% of ~530.35MiB at 442.41KiB/s ETA 20:18 (frag 25/2312)
```
```

**Comment by Lesmiscore** [comment]
This should reproduce on any video with fragmented formats (widely known for people as HLS and DASH) though.
So the point in this issue is that position of the floating point isn't at consistent location on terminal, right?

**Comment by valtism** [comment]
Yes, the floating point moves, and the rest of the string (in this case ` ETA 20:18 (frag 25/2312)`) moves back and forth because the length of the string behind it keeps changing.

**Comment by Lesmiscore** [comment]
I see, but that would be a weird trick to keep it in line...

**Comment by valtism** [comment]
As you can see from the actual output listed above, there already is string padding implemented, it is just done so in a broken way. Percentage downloaded is also padded.

I think that it would also be reasonable to limit the size of the speeds (convert `1000.00KiB/s` to `1.00MiB/s`) to save a character so the spacing doesn't look too big / awkward

**Comment by Lesmiscore** [comment]
I don't think the padding for percentage is broken, but certainly speed is. The text for speed is padded to 10 characters aligned to the end. The broken case reaches 11 (`999.99KiB/s`) or 12 (`1000.00KiB/s`), moving the point.


P.S. `1000.00KiB/s` is actually `0.97MiB/s`, `MiB` isn't a SI unit.
