### ISSUE TITLE
Virus found in latest update through homebrew 

### ISSUE THREAD

**Issue by KwisatzJim** [yt-dlp/yt-dlp#3791]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

I updated yt-dlp with 'brew upgrade' and my antivirus software found Win.Virus.Tirusor-9950253-0 in parser.py which is in one of the subdirectories used.  Anyone else seeing this?  is there a proper forum to notify such things?

yt-dlp: stable 2022.5.18 (bottled), HEAD
Fork of youtube-dl with additional features and fixes
https://github.com/yt-dlp/yt-dlp
/opt/homebrew/Cellar/yt-dlp/2022.5.18 (2,211 files, 24.4MB) *
  Poured from bottle on 2022-05-18 at 17:55:16
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/yt-dlp.rb

**Comment by KwisatzJim** [comment]
<img width="1290" alt="9F3F5015-DD56-47AC-8E5C-E255257C520D" src="https://user-images.githubusercontent.com/131250/169225885-0e1d2501-9b18-455c-bfe3-df1ef91f6f44.png">

**Comment by Lesmiscore** [comment]
That's an false positive related to pip, and it should be reported to that. Closing as external issue.
