### ISSUE TITLE
twitch.tv 403 error downloading vod

### ISSUE THREAD

**Issue by Fixles** [yt-dlp/yt-dlp#3793]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.05.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

UK

### Description

Ubuntu 22.04 
https://www.twitch.tv/videos/1486560463
Getting 403 Error trying to download vod

Looked similar to this bug closed last year https://github.com/yt-dlp/yt-dlp/issues/125

### Verbose log

```shell
[~]$ yt-dlp -vU https://www.twitch.tv/videos/1486560463
[debug] Command-line config: ['-vU', 'https://www.twitch.tv/videos/1486560463']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.05.18 [b14d52355] (zip)
[debug] Python version 3.10.4 (CPython 64bit) - Linux-5.15.0-30-generic-x86_64-with-glibc2.35
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: ffmpeg -bsfs
[debug] exe versions: ffmpeg 4.4.1 (setts), ffprobe 4.4.1
[debug] Optional libraries: certifi-2020.06.20, secretstorage-3.3.1, sqlite3-2.6.0
[debug] Proxy map: {}
Latest version: 2022.05.18, Current version: 2022.05.18
yt-dlp is up to date (2022.05.18)
[debug] [twitch:vod] Extracting URL: https://www.twitch.tv/videos/1486560463
[twitch:vod] 1486560463: Downloading stream metadata GraphQL
[twitch:vod] 1486560463: Downloading video access token GraphQL
[twitch:vod] 1486560463: Downloading m3u8 information
ERROR: [twitch:vod] 1486560463: Failed to download m3u8 information: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 642, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/twitch.py", line 392, in _real_extract
    formats = self._extract_m3u8_formats(
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 2128, in _extract_m3u8_formats
    fmts, subs = self._extract_m3u8_formats_and_subtitles(*args, **kwargs)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 2139, in _extract_m3u8_formats_and_subtitles
    res = self._download_webpage_handle(
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 801, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query, expected_status=expected_status)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 786, in _request_webpage
    raise ExtractorError(errmsg, cause=err)

  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 768, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3596, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/usr/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

**Comment by ryouxin** [comment]
same question

**Comment by Fixles** [comment]
> Twitch url looks like it's for subscribers only. 
> cc @ryouxin

Oh boy I didn't even know that was a thing. Sorry for wasting your time. I guess as it gives a 403 you cant tell for sure if its a subscriber video or not. I wonder if the error for twitch 403 could be updated to say please check the video plays in a web browser when not logged in.

Thank you for looking at it.

**Comment by pukkandan** [comment]
> I wonder if the error for twitch 403 could be updated to say please check the video plays in a web browser when not logged in.

This applies for ALL errors!

> - [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
