### ISSUE TITLE
[Vimeo] Unable to detect Original and source files for some videos

### ISSUE THREAD

**Issue by hyungz** [yt-dlp/yt-dlp#3795]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

Did Vimeo removed the `Original` or `source` files in some of the recent uploads or did they added a feature for the uploader that can block or prevent the extractor from getting the said files? Usually, the maximum time you can still download the source files is 1 week after the upload date but, now some of them is gone (not all uploader have this issue, some still have the source files) even if the file was just 20 minutes old. [https://vimeo.com/711583321](url) (Here is the example link uploaded on Thursday, May 19, 2022 at 6:14 AM EST). I am running on the latest version of yt-dlp 2022.05.18. This is going for a week now and I thought it will be fixed on the latest update (fixed vimeo extractors) so I waited but, still no luck. Original or source files can no longer be detected by yt-dlp (just the re-encoded versions of the videos HLSs and DASHs). For the sake of still having the source file, this is the example link ([https://vimeo.com/711071144](url)) uploaded on Wednesday, May 18, 2022 at 1:04 AM EST.

**Comment by pukkandan** [comment]
> Did Vimeo removed the Original or source files in some of the recent uploads 

Why are you asking us? Ask vimeo...

If the format can be accessed in browser, but don't work in yt-dlp, open a "broken site" report
