### ISSUE TITLE
Conversion failed!

### ISSUE THREAD

**Issue by khk58** [yt-dlp/yt-dlp#3798]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

Dear all,

on downloading a video using this command 'yt-dlp --check-format --cookies-from-browser firefox --download-archive ..\archive.txt  -i --geo-bypass -o %%(title)s.%%(ext)s https://www.youtube.com/watch?v=istAMvTyHmw'

I get a 'Conversion failed! at the end and the url is written into '..\archive.txt'.

Deleting it from '..\archive.txt' - I tried it several times with the same result.

Kind regards Kurt, Austria

**Comment by NanaMizukiAnother7** [comment]
Can you please send a verbose log?

**Comment by khk58** [comment]
How to get a verbose log?

Which option(s)?

**Comment by khk58** [comment]
I hope that will do:


D:\Youtube\filme>rem

D:\Youtube\filme>yt-dlp -vU --check-format --cookies-from-browser firefox --download-archive ..\archive.txt  -i --geo-bypass -o %(title)s.%(ext)s https://www.youtube.com/watch?v=istAMvTyHmw
[debug] Command-line config: ['-vU', '--check-format', '--cookies-from-browser', 'firefox', '--download-archive', '..\\archive.txt', '-i', '--geo-bypass', '-o', '%(title)s.%(ext)s', 'https://www.youtube.com/watch?v=istAMvTyHmw']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.05.18 [b14d523] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: ffmpeg -bsfs
[debug] exe versions: ffmpeg git-2020-06-28-4cfcfb3, ffprobe git-2020-06-28-4cfcfb3
[debug] Optional libraries: Cryptodome-3.14.1, brotli-1.0.9, certifi-2021.10.08, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[Cookies] Extracting cookies from firefox
[debug] Extracting cookies from: "C:\Users\khk59\AppData\Roaming\Mozilla\Firefox\Profiles\czhw2lsu.default-release-1623234895724\cookies.sqlite"
[Cookies] Extracted 288 cookies from firefox
[debug] Proxy map: {}
[debug] Loading archive file '..\\archive.txt'
Latest version: 2022.05.18, Current version: 2022.05.18
yt-dlp is up to date (2022.05.18)
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=istAMvTyHmw
[youtube] istAMvTyHmw: Downloading webpage
[debug] [youtube] Extracted SAPISID cookie
[youtube] istAMvTyHmw: Downloading android player API JSON
[youtube] istAMvTyHmw: Downloading MPD manifest
[youtube] istAMvTyHmw: Downloading MPD manifest
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] Testing format 302
[dashsegments] Total fragments: 1
[download] Destination: D:\Youtube\filme\tmpz6dpz8xy.tmp
[debug] File locking is not supported on this platform. Proceeding without locking
[download] 100% of 699.00B in 00:01
[info] Testing format 251
[download] Destination: D:\Youtube\filme\tmp7wiy2opd.tmp
[download] 100% of 10.00KiB in 00:01
[info] istAMvTyHmw: Downloading 1 format(s): 302+251
[debug] Invoking dashsegments downloader on "https://manifest.googlevideo.com/api/manifest/dash/expire/1653013389/ei/LaeGYva3J9GRWsuhuqgB/ip/89.46.223.139/id/8acb4032f4f21e6c/source/youtube/requiressl/yes/playback_host/rr2---sn-5hnednss.googlevideo.com/mh/wm/mm/31%2C29/mn/sn-5hnednss%2Csn-5hne6nsd/ms/au%2Crdu/mv/m/mvi/2/pl/27/hfr/all/as/fmp4_audio_clear%2Cwebm_audio_clear%2Cwebm2_audio_clear%2Cfmp4_sd_hd_clear%2Cwebm2_sd_hd_clear/gcr/nl/initcwndbps/1212500/spc/4ocVCxHvlVUN4x3ppne9g8fDwG0cz3rCVMcpbVohnA/vprv/1/mt/1652991425/fvip/1/keepalive/yes/fexp/24001373%2C24007246/itag/0/sparams/expire%2Cei%2Cip%2Cid%2Csource%2Crequiressl%2Chfr%2Cas%2Cgcr%2Cspc%2Cvprv%2Citag/sig/AOq0QJ8wRgIhANpaa1R_cJg9GGyQk1uNiTVxNqwv1-T7MgcLQoVqjf7oAiEA4LGh4udWZ7HFR9J8Kq1ql3mPH7Q-rOpBFjOSG3__YO8%3D/lsparams/playback_host%2Cmh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps/lsig/AG3C_xAwRAIgAW0M82FAhB2RBvkV18D1p8Iym1UIMl0--QDGLj_k2o0CIB6xNFQ5Gl0nfsYUatXyIcy2zP9HXuF8EcFZcYEtvN8Y"
[dashsegments] Total fragments: 862
[download] Destination: Polizeiruf 110 - [69]  Der Teufel hat den Schnaps gemacht  (DDR 1981).f302.webm
[download] 100% of 1.02GiB in 23:50
[debug] Invoking http downloader on "https://rr2---sn-5hnednss.googlevideo.com/videoplayback?expire=1653013390&ei=LqeGYqy7GsyH6dsPo9KloAI&ip=89.46.223.139&id=o-AHSHdN7hCDJ3X9PQQp1maRgwrF8AjFW-7mkhFzjglO8P&itag=251&source=youtube&requiressl=yes&mh=wm&mm=31%2C29&mn=sn-5hnednss%2Csn-5hne6nsd&ms=au%2Crdu&mv=m&mvi=2&pl=27&gcr=nl&initcwndbps=1212500&vprv=1&mime=audio%2Fwebm&gir=yes&clen=57928076&otfp=1&dur=4806.021&lmt=1614301825717200&mt=1652991425&fvip=1&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=6211222&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cgcr%2Cvprv%2Cmime%2Cgir%2Cclen%2Cotfp%2Cdur%2Clmt&sig=AOq0QJ8wRQIgDLzsKLCpmRU2ij92P3qhh2empCFD_nZpJpx8NlZMlI0CIQDwwnkf8toH9QglonFudbEIpi8L---HLgPD6M8jkbad2g%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhANfi3tzpiPNrSkdcwk4QdpOhIzIdctmXbKUSQpWwmV_CAiAkDfMxeibOnVnPnCfDNzBBXc45trf2XgZQsa5CnjgjDg%3D%3D"
[download] Destination: Polizeiruf 110 - [69]  Der Teufel hat den Schnaps gemacht  (DDR 1981).f251.webm
[download] 100% of 55.24MiB in 00:17
[Merger] Merging formats into "Polizeiruf 110 - [69]  Der Teufel hat den Schnaps gemacht  (DDR 1981).webm"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:Polizeiruf 110 - [69]  Der Teufel hat den Schnaps gemacht  (DDR 1981).f302.webm" -i "file:Polizeiruf 110 - [69]  Der Teufel hat den Schnaps gemacht  (DDR 1981).f251.webm" -c copy -map "0:v:0" -map "1:a:0" -movflags "+faststart" "file:Polizeiruf 110 - [69]  Der Teufel hat den Schnaps gemacht  (DDR 1981).temp.webm"
[debug] ffmpeg version git-2020-06-28-4cfcfb3 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 9.3.1 (GCC) 20200621
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libsrt --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libgsm --disable-w32threads --enable-libmfx --enable-ffnvcodec --enable-cuda-llvm --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt --enable-amf
  libavutil      56. 55.100 / 56. 55.100
  libavcodec     58. 93.100 / 58. 93.100
  libavformat    58. 47.100 / 58. 47.100
  libavdevice    58. 11.100 / 58. 11.100
  libavfilter     7. 86.100 /  7. 86.100
  libswscale      5.  8.100 /  5.  8.100
  libswresample   3.  8.100 /  3.  8.100
  libpostproc    55.  8.100 / 55.  8.100
Input #0, matroska,webm, from 'file:Polizeiruf 110 - [69]  Der Teufel hat den Schnaps gemacht  (DDR 1981).f302.webm':
  Metadata:
    encoder         : google/video-file
    http://youtube.com/streaming/otf/durations/112015: Segment-Count: 861
                    : Segment-Durations-Ms: 5600(r=47),5040,5200,5760,5600(r=99),5160,5240,5600(r=8),5200(r=1),5600(r=16),5000,5400,5600(r=14),5280,5120,5600(r=72),5000,5400,5600(r=14),5160,5240,5600(r=3),5400,5000,5600(r=22),5440,5760,5600(r=10),5000,5400,5600(r=98),5520,5680
                    :
                    :
  Duration: N/A, start: 0.000000, bitrate: N/A
    Stream #0:0(eng): Video: vp9 (Profile 0), yuv420p(tv, bt709/unknown/unknown), 1280x720, SAR 1:1 DAR 16:9, 50 fps, 50 tbr, 1k tbn, 1k tbc (default)
Input #1, matroska,webm, from 'file:Polizeiruf 110 - [69]  Der Teufel hat den Schnaps gemacht  (DDR 1981).f251.webm':
  Metadata:
    encoder         : google/video-file
  Duration: 01:20:06.02, start: -0.007000, bitrate: 96 kb/s
    Stream #1:0(eng): Audio: opus, 48000 Hz, stereo, fltp (default)
Output #0, webm, to 'file:Polizeiruf 110 - [69]  Der Teufel hat den Schnaps gemacht  (DDR 1981).temp.webm':
  Metadata:
    http://youtube.com/streaming/otf/durations/112015: Segment-Count: 861
                    : Segment-Durations-Ms: 5600(r=47),5040,5200,5760,5600(r=99),5160,5240,5600(r=8),5200(r=1),5600(r=16),5000,5400,5600(r=14),5280,5120,5600(r=72),5000,5400,5600(r=14),5160,5240,5600(r=3),5400,5000,5600(r=22),5440,5760,5600(r=10),5000,5400,5600(r=98),5520,5680
                    :
                    :
    encoder         : Lavf58.47.100
    Stream #0:0(eng): Video: vp9 (Profile 0), yuv420p(tv, bt709/unknown/unknown), 1280x720 [SAR 1:1 DAR 16:9], q=2-31, 50 fps, 50 tbr, 1k tbn, 1k tbc (default)
    Stream #0:1(eng): Audio: opus, 48000 Hz, stereo, fltp (default)
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #1:0 -> #0:1 (copy)
Press [q] to stop, [?] for help
[webm @ 0000022625710040] Application provided invalid, non monotonically increasing dts to muxer in stream 0: 5620 >= 5600
av_interleaved_write_frame(): Invalid argument
frame=  283 fps=0.0 q=-1.0 Lsize=    1568kB time=00:00:05.62 bitrate=2285.1kbits/s speed=N/A
video:1530kB audio:78kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
Conversion failed!
ERROR: Conversion failed!
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 3340, in run_pp
  File "yt_dlp\postprocessor\common.py", line 25, in run
  File "yt_dlp\postprocessor\common.py", line 129, in wrapper
  File "yt_dlp\postprocessor\ffmpeg.py", line 827, in run
  File "yt_dlp\postprocessor\ffmpeg.py", line 282, in run_ffmpeg_multiple_files
  File "yt_dlp\postprocessor\ffmpeg.py", line 321, in real_run_ffmpeg
yt_dlp.postprocessor.ffmpeg.FFmpegPostProcessorError: Conversion failed!

[debug] Adding to archive: youtube istAMvTyHmw

D:\Youtube\filme>rem yt-dlp --check-format --cookies-from-browser firefox --download-archive ..\archive.txt  -i --geo-bypass -o %(title)s.%(ext)s https://www.youtube.com/watch?v=3IrI6RkC04w

D:\Youtube\filme>rem yt-dlp --check-format --cookies-from-browser firefox --download-archive ..\archive.txt  -i --geo-bypass -o %(title)s.%(ext)s https://www.youtube.com/watch?v=YMvqZS-YmO8

**Comment by NanaMizukiAnother7** [comment]
> ffmpeg version git-2020-06-28-4cfcfb3

Your ffmpeg version is too old. Use version 5.0.1.

**Comment by khk58** [comment]
Thanx, I'll try

**Comment by pukkandan** [comment]
See PINNED issue https://github.com/yt-dlp/yt-dlp/issues/3766 => https://github.com/yt-dlp/yt-dlp/issues/871
