### ISSUE TITLE
new version of yt-dlp

### ISSUE THREAD

**Issue by khk58** [yt-dlp/yt-dlp#3800]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

Dear all,

yesterday I got the new version of yt-dlp (option -U) and now I see (in difference to the version before) every position on downloading playlists;
is there an option to suppress the messages of already downloaded files?

Kind regards,

Kurt, Austria

**Comment by pukkandan** [comment]
We can't read your mind or see your computer screen. We don't know what command you ran, what error you got or even what you are downloading... Show verbose logs!

**Comment by khk58** [comment]
How to get a verbose log?

Which option(s)?

**Comment by pukkandan** [comment]
Did you even read anything in the issue template?

> If your question involves a yt-dlp command, provide the complete verbose output of that command.
> Add the `-vU` flag to **your** command line you run yt-dlp with (`yt-dlp -vU <your command line>`), copy the WHOLE output and insert it below.

**Comment by khk58** [comment]
I hope this will do:

D:\Youtube\_al>rem Abenteuer Leben

D:\Youtube\_al>yt-dlp -vU --playlist-end 100 --download-archive ..\archive.txt  -i --geo-bypass -o "%(title)s.%(ext)s"  https://www.youtube.com/playlist?list=UUyVg1YLHU6xu-spjmLlC-qA
[debug] Command-line config: ['-vU', '--playlist-end', '100', '--download-archive', '..\\archive.txt', '-i', '--geo-bypass', '-o', '%(title)s.%(ext)s', 'https://www.youtube.com/playlist?list=UUyVg1YLHU6xu-spjmLlC-qA']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.05.18 [b14d523] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: ffmpeg -bsfs
[debug] exe versions: ffmpeg git-2020-06-28-4cfcfb3, ffprobe git-2020-06-28-4cfcfb3
[debug] Optional libraries: Cryptodome-3.14.1, brotli-1.0.9, certifi-2021.10.08, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loading archive file '..\\archive.txt'
Latest version: 2022.05.18, Current version: 2022.05.18
yt-dlp is up to date (2022.05.18)
[debug] [youtube:tab] Extracting URL: https://www.youtube.com/playlist?list=UUyVg1YLHU6xu-spjmLlC-qA
[youtube:tab] UUyVg1YLHU6xu-spjmLlC-qA: Downloading webpage
[debug] [youtube:tab] Final URL: https://www.youtube.com/playlist?list=UUyVg1YLHU6xu-spjmLlC-qA
[youtube:tab] UUyVg1YLHU6xu-spjmLlC-qA: Downloading API JSON with unavailable videos
[download] Downloading playlist: Uploads from Abenteuer Leben
[youtube:tab] playlist Uploads from Abenteuer Leben: Downloading 100 videos
[download] Downloading video 1 of 100
[download] So schnell wird aus einem Hocker und ein paar Zeitschriftensammlern ein origineller Couchtisch! 😍 has already been recorded in the archive
[download] Downloading video 2 of 100
[download] So verrutscht das Schneidebrettchen beim Schnippeln nie mehr! has already been recorded in the archive
[download] Downloading video 3 of 100
[download] 3 Gänge für 3 Euro?! Budget-Küche vom Profi! | Abenteuer Leben | Kabel Eins has already been recorded in the archive
[download] Downloading video 4 of 100
[download] Cooler Keramik-Look für eure alten Vasen?🍾 #upcycling has already been recorded in the archive
[download] Downloading video 5 of 100
[download] Der perfekte Liebesbeweis für eure Männer❤ has already been recorded in the archive
[download] Downloading video 6 of 100
[download] Das Quäntchen mehr Geschmack - Pastagerichte | Abenteuer Leben | Kabel Eins has already been recorded in the archive
[

**Comment by pukkandan** [comment]
I don't see any diff with older versions. What exactly is the issue?

**Comment by khk58** [comment]
I tried with version 2022.04.08, which is much more quicker than version 2022.05.18; maybe because the new version changes colors (in every line 'video x of y' the 'x' to green and the 'y' to blue)?

**Comment by pukkandan** [comment]
https://github.com/yt-dlp/yt-dlp/issues/3786

**Comment by khk58** [comment]
How can I use/implement functools.cache (mentioned in #3786)??

Or is it integrated in the next version?

Kind regards

Kurt (Austria)

**Comment by pukkandan** [comment]
You can try to [compile](https://github.com/yt-dlp/yt-dlp#compile) it yourself or [install using PIP](https://github.com/yt-dlp/yt-dlp#:~:text=install%20the%20master%20branch) if you are able to follow the instructions. Otherwise, wait for new release
