### ISSUE TITLE
BitChute ERROR   |  Video Access Limited   (already used cookies file for login as well)

### ISSUE THREAD

**Issue by TrumanHW** [yt-dlp/yt-dlp#3805]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.05.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

ERROR: [BitChute]
**Video Access Limited**

Report issue at: https://github.com/yt-dlp/yt-dlp/issues?q=

Fill out appropriate issue-template. 
Confirm use of latest version  yt-dlp -U

❯ yt-dlp -U

Latest    version: 2022.05.18
Current version: 2022.05.18
yt-dlp is up to date (2022.05.18

**Command used:**
yt-dlp -vU  https://www.bitchute.com/video/JTaXVMz8q1A1/

ERROR: [BitChute] JTaXVMz8q1A1: Video Access Limited; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/usr/local/Cellar/yt-dlp/2022.5.18/libexec/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 642, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/Cellar/yt-dlp/2022.5.18/libexec/lib/python3.10/site-packages/yt_dlp/extractor/bitchute.py", line 75, in _real_extract
    raise ExtractorError(error)

I also ensured my cookies file was loaded (as I was logged in to verify my age).

<img width="1409" alt="Screen Shot 2022-05-19 at 15 59 13" src="https://user-images.githubusercontent.com/52586559/169417881-f50e2aeb-c2eb-458b-bce8-1458c896968e.png">

### Verbose log

```shell
❯ yt-dlp -vU  https://www.bitchute.com/video/JTaXVMz8q1A1/
[debug] Command-line config: ['-vU', 'https://www.bitchute.com/video/JTaXVMz8q1A1/']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.05.18 [b14d52355]
[debug] Python version 3.10.4 (CPython 64bit) - macOS-12.3.1-x86_64-i386-64bit
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: ffmpeg -bsfs
[debug] exe versions: ffmpeg 5.0.1 (setts), ffprobe 5.0.1
[debug] Optional libraries: Cryptodome-3.14.1, brotli-1.0.9, certifi-2021.10.08, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
Latest version: 2022.05.18, Current version: 2022.05.18
yt-dlp is up to date (2022.05.18)
[debug] [BitChute] Extracting URL: https://www.bitchute.com/video/JTaXVMz8q1A1/
[BitChute] JTaXVMz8q1A1: Downloading webpage
ERROR: [BitChute] JTaXVMz8q1A1: Video Access Limited; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/usr/local/Cellar/yt-dlp/2022.5.18/libexec/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 642, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/Cellar/yt-dlp/2022.5.18/libexec/lib/python3.10/site-packages/yt_dlp/extractor/bitchute.py", line 75, in _real_extract
    raise ExtractorError(error)
```

**Comment by pukkandan** [comment]
![image](https://user-images.githubusercontent.com/6623388/170587536-6b77bd29-db9e-440a-8215-e19e8c18e606.png)
