### ISSUE TITLE
tv.vevo.com

### ISSUE THREAD

**Issue by glomatico** [yt-dlp/yt-dlp#3809]
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.05.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Brazil

### Example URLs

https://tv.vevo.com/watch/artist/janet-jackson/US0450100550
https://tv.vevo.com/watch/artist/rick-astley/GB1108800260

### Description

The default Vevo extractor can't download some videos that are available in tv.vevo.com

### Verbose log

```shell
[debug] Command-line config: ['-vU', 'https://tv.vevo.com/watch/artist/janet-jackson/US0450100550']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.05.18 [b14d52355]
[debug] Python version 3.10.4 (CPython 64bit) - Windows-10-10.0.22000-SP0
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: ffmpeg -bsfs
[debug] exe versions: ffmpeg git-2022-03-27-c2d1597-ffmpeg-windows-build-helpers (fdk,setts), ffprobe git-2022-03-27-c2d1597-ffmpeg-windows-build-helpers
[debug] Optional libraries: Cryptodome-3.14.1, brotli-1.0.9, certifi-2021.10.08, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.2
[debug] Proxy map: {}
Latest version: 2022.05.18, Current version: 2022.05.18
yt-dlp is up to date (2022.05.18)
[debug] [generic] Extracting URL: https://tv.vevo.com/watch/artist/janet-jackson/US0450100550
[generic] US0450100550: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] US0450100550: Downloading webpage
[generic] US0450100550: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://tv.vevo.com/watch/artist/janet-jackson/US0450100550
Traceback (most recent call last):
  File "C:\Users\glomatico\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 1395, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\glomatico\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 1465, in __extract_info
    ie_result = ie.extract(url)
  File "C:\Users\glomatico\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\extractor\common.py", line 642, in extract
    ie_result = self._real_extract(url)
  File "C:\Users\glomatico\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\extractor\generic.py", line 4031, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://tv.vevo.com/watch/artist/janet-jackson/US0450100550
```

**Comment by pukkandan** [comment]
Could you show what `yt-dlp -v vevo:US0450100550` gives?

**Comment by glomatico** [comment]
> Could you show what `yt-dlp -v vevo:US0450100550` gives?

Hello! It shows this:
`[debug] Command-line config: ['-v', 'vevo:US0450100550']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.05.18 [b14d52355]
[debug] Python version 3.10.4 (CPython 64bit) - Windows-10-10.0.18362-SP0
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: ffmpeg -bsfs
[debug] exe versions: ffmpeg git-2022-05-16-e3580f6-ffmpeg-windows-build-helpers (fdk,setts), ffprobe git-2022-05-16-e3580f6-ffmpeg-windows-build-helpers
[debug] Optional libraries: Cryptodome-3.14.1, brotli-1.0.9, certifi-2022.05.18.1, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] [Vevo] Extracting URL: vevo:US0450100550
[Vevo] Retrieving oauth token
[Vevo] US0450100550: Downloading api video info
[Vevo] US0450100550: Downloading video versions info
ERROR: US0450100550: An extractor error has occurred. (caused by KeyError('quality')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "C:\Users\glomatico\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\extractor\common.py", line 642, in extract
    ie_result = self._real_extract(url)
  File "C:\Users\glomatico\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\extractor\vevo.py", line 152, in _real_extract
    'format_id': 'http-%s-%s' % (version, video_version['quality']),
KeyError: 'quality`

I actually managed to fix this issue by editing the extractor and changing the value of format_id in line 152 to something else.
