### ISSUE TITLE
[Broken]Viki

### ISSUE THREAD

**Issue by girod2033** [yt-dlp/yt-dlp#381]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running yt-dlp version **2021.06.01**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] Command-line config: ['--verbose', '--cookies', 'cookies.txt', '--userna
me', 'PRIVATE', '--password', 'PRIVATE', '-F', '--allow-unplayable-formats', 'ht
tps://www.viki.com/videos/1172967v']
[debug] Encodings: locale cp1251, fs utf-8, out utf-8, pref cp1251
[debug] yt-dlp version 2021.06.01 (exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg 4.2.1, ffprobe 4.2.1
[debug] Proxy map: {}
[viki] Logging in
[debug] [viki] Extracting URL: https://www.viki.com/videos/1172967v
[viki] 1172967v: Downloading video JSON
[viki] 1172967v: Downloading video streams JSON
ERROR: Unable to download JSON metadata: HTTP Error 400: Bad Request (caused by
<HTTPError 400: 'Bad Request'>); please report this issue on  https://github.com
/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github
.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose
flag and include its complete output.
  File "yt_dlp\extractor\common.py", line 675, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 3062, in urlopen
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 649, in http_error_default

```

## Description

Hello.
I have a subscription. If necessary, I will give you the account details.

**Comment by girod2033** [comment]
+ addition:

[debug] Command-line config: ['--verbose', '--cookies', 'cookies.txt', '--userna
me', 'PRIVATE', '--password', 'PRIVATE', '-F', '--allow-unplayable-formats', 'ht
tps://www.viki.com/movies/37182c-man-of-men']
[debug] Encodings: locale cp1251, fs utf-8, out utf-8, pref cp1251
[debug] yt-dlp version 2021.06.01 (exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg 4.2.1, ffprobe 4.2.1
[debug] Proxy map: {}
[viki:channel] Logging in
[debug] [viki:channel] Extracting URL: https://www.viki.com/movies/37182c-man-of
-men
[viki:channel] 37182c: Downloading channel JSON
[viki:channel] 37182c: Downloading episodes JSON page #1
[viki:channel] 37182c: Downloading clips JSON page #1
[viki:channel] 37182c: Downloading movies JSON page #1
[download] Downloading playlist: Man of Men
[viki:channel] playlist Man of Men: Collected 1 videos; downloading 1 of them
[download] Downloading video 1 of 1
[viki] Logging in
ERROR: Unable to download JSON metadata: HTTP Error 429: Too Many Requests (caus
ed by <HTTPError 429: 'Too Many Requests'>); please report this issue on  https:
//github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  ht
tps://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with th
e --verbose flag and include its complete output.
  File "yt_dlp\extractor\common.py", line 675, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 3062, in urlopen
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 649, in http_error_default

[download] Finished downloading playlist: Man of Men

**Comment by pukkandan** [comment]
> HTTP Error 429: Too Many Requests (caused by <HTTPError 429: 'Too Many Requests'>);

Looks like you are being blocked by the server due to downloading too fast. Open the URL in browser, export fresh cookies and try again

**Comment by girod2033** [comment]
With fresh cookies:

[debug] Command-line config: ['--verbose', '--cookies', 'cookies.txt', '--userna
me', 'PRIVATE', '--password', 'PRIVATE', '-F', '--allow-unplayable-formats', 'ht
tps://www.viki.com/movies/37182c-man-of-men']
[debug] Encodings: locale cp1251, fs utf-8, out utf-8, pref cp1251
[debug] yt-dlp version 2021.06.01 (exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg 4.2.1, ffprobe 4.2.1
[debug] Proxy map: {}
[viki:channel] Logging in
[debug] [viki:channel] Extracting URL: https://www.viki.com/movies/37182c-man-of
-men
[viki:channel] 37182c: Downloading channel JSON
[viki:channel] 37182c: Downloading episodes JSON page #1
[viki:channel] 37182c: Downloading clips JSON page #1
[viki:channel] 37182c: Downloading movies JSON page #1
[download] Downloading playlist: Man of Men
[viki:channel] playlist Man of Men: Collected 1 videos; downloading 1 of them
[download] Downloading video 1 of 1
[viki] Logging in
[debug] [viki] Extracting URL: https://www.viki.com/videos/1172967v
[viki] 1172967v: Downloading video JSON
[viki] 1172967v: Downloading video streams JSON
ERROR: Unable to download JSON metadata: HTTP Error 400: Bad Request (caused by
<HTTPError 400: 'Bad Request'>); please report this issue on  https://github.com
/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github
.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose
flag and include its complete output.
  File "yt_dlp\extractor\common.py", line 675, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 3062, in urlopen
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 649, in http_error_default

[download] Finished downloading playlist: Man of Men

**Comment by pukkandan** [comment]
I was trying to check if the issue exists for "free to watch" content as well. It seems that everything in viki is now DRM protected. I could not find any links without DRM. If there are any, let me know

**Comment by girod2033** [comment]
I used the "--allow-unplayable-formats" parameter to get streams in the manifest (mpd with DRM).
Then I will use the link to mpd as before.
https://manifest-viki.viki.io/v1/1172967v/cloudfront/main/mpd/normal/viki/high/hd/ww/dt2_dt3/manifest.mpd...

**Comment by pukkandan** [comment]
Related: https://github.com/ytdl-org/youtube-dl/issues/29218

**Comment by pukkandan** [comment]
https://github.com/ytdl-org/youtube-dl/issues/29227
