### ISSUE TITLE
[VK.COM] This video is only available for registered users

### ISSUE THREAD

**Issue by vden89** [yt-dlp/yt-dlp#3811]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

**_ERROR: [vk] This video is only available for registered users. Use --cookies, --cookies-from-browser, --username and --password, or --netrc to provide account credentials_**

I use file --cookies File.txt however it still gives me an error.
I also tried using --cookies-from-browser Chrome. The result is the same.

If I don't use cookies it gives me another error -
**_ERROR: [vk] Error_**

**Comment by pukkandan** [comment]
Can't be bothered to read the instructions in the issue template?

> If your question contains "isn't working" or "can you add", this is most likely the wrong template.
> If you are in doubt if this is the right template, use another template!

Open a "broken site" issue with all necessary details including verbose log
