### ISSUE TITLE
i cant download  and embed the subs from a certain channel

### ISSUE THREAD

**Issue by githubuser872349** [yt-dlp/yt-dlp#3817]

**Comment by Lesmiscore** [comment]
Post verbose log. We have nothing to do without it.

**Comment by githubuser872349** [comment]
yt-dlp --sub-langs en,de --embed-subs

**Comment by githubuser872349** [comment]
this is the request i used
i didnt get an error it just didnt download the subtitles

**Comment by Lesmiscore** [comment]
I mean post what you see by running `yt-dlp -v --sub-langs en,de --embed-subs` in console.

**Comment by githubuser872349** [comment]
it downloads everything normal but i jumps straight in the download of the video file instead of first downloading the subtitles.
Thats like if you just type yt-dlp with the link afterwards

**Comment by eladkarako** [comment]
no problem I can tell in (recent) 2022.05.18 [b14d52355].

<details><summary>might help.</summary>

maybe it is not available in the language you ask, 
you can still ask for a machine translated ones too.

here is what I write to get English translated when only Japanese is available:
`--embed-subs --write-subs --write-auto-subs --sub-langs "en,en-ja"`  
(it also keeps the sub files, for debug purposes, first `en` won't do anything if no actual English subtitle was attached to the video, `en-ja` means I know (or queried) the video before-hand and know it has a Japanese subtitles, so I ask for machine translated English from the existing subtitle).

</details>

**Comment by githubuser872349** [comment]
Thanks that could solve the problem but somehow i can not download the newest version with pacman i already syncronized the database but it didnt help.
when i search for yt-dlp in the terminal with pacman it still shows the older version.
however when i search in the repository i find the newer version.
Do you know why i have that issue

**Comment by githubuser872349** [comment]
The video i wanted to download has english subtitle not auto-generated or translated or anything like that. And i can download it seperately but not together with the video so that it gets embeded.

**Comment by eladkarako** [comment]
> Do you know why i have that issue

<details><summary>hmm.. sounds familiar.</summary>

not sure how that package manager works,  

but I'm using yt-dlp as a package on native python,  
installed with pip.  

and for some reason `python -m pip install --force-reinstall "https://github.com/yt-dlp/yt-dlp/archive/master.zip"` (similar to you) was kept giving me an old version. 
didn't made any sense!  

anyway, instead, I was switching to standard installation, using `python -m pip install --verbose --no-color --disable-pip-version-check --upgrade yt-dlp`, which fixed it for me.

<sub>(all other dependencies gathered manually into a (windows) kit <a href="https://github.com/eladkarako/yt-dlp_kit">.</a>)</sub>

not sure if it helps.

</details>

**Comment by githubuser872349** [comment]
ok thanks.
i think that they maybe updated the cover but not the package itsself.
so you see the new package when you look it up in the internet,
but if you really want to download it or search the database in the terminal the files are still the same. maybe they are going to fix it.

**Comment by githubuser872349** [comment]
anyway i wonder why i can download the subs of every other video and embed the subtitle in every other video that i tried only the videos of this one channel wont let me do that. can you somehow set the subtitle to not downloadable in the video settings in youtube or do you think that this is a channel with the yt-dlp software itsself?

**Comment by eladkarako** [comment]
🤷.  
try appending `--verbose --print-traffic  1>log.txt  2>&1` 
or `--verbose --print-traffic  2>&1 | tee.exe log.txt`  
to the end of your command.
attach it in here,  
maybe someone can help with that..
