### ISSUE TITLE
[TwitCasting] Some archive downloads only the first hour of it

### ISSUE THREAD

**Issue by Lesmiscore** [yt-dlp/yt-dlp#382]
## Checklist

- [ ] I'm reporting a broken site support
- [x] I've verified that I'm running yt-dlp version **2021.06.01**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
WIP
```

## Description/Background
For some TwitCasting archive, it sometimes split the archive 1 hour each.
This especially happens when the video is longer than an hour, with high bitrate.

Here's an example video: https://twitcasting.tv/loft_heaven/movie/685979292
And another one: https://twitcasting.tv/nana_fujisawa/movie/686749195 

With current yt-dlp, it can only download the first split(=hour). But there's more big problem:
1. TC allows downloading only one stream simultaneously. Failing to follow this **causes all playlists to expire.**
    - Some `ffmpeg` hack like `ffmpeg -i STREAM1.m3u8 -i STREAM2.m3u8 -filter_complex "blablabla" -map [v] -map [a] outpur.mp4.part` don't work because of this.
    - It seems we have to request the next playlist after we download last segment of previous playlist.
    - (More to say, it should be realtime. Download breaks sometimes)
1. ~~Current youtube-dl/yt-dlp architecture doesn't support such videos.~~ ... but still not able to concat them.
    - I think it's okay to ask users to download these splits manually, but who likes it?
    - They do not have a proper method to download multiple videos separately and combine later.

I'm also trying to work better with these problems, but I want to hear idea from you.

Thanks.

**Comment by pukkandan** [comment]
> TC allows downloading only one stream simultaneously.

But then, how does the browser play the video + audio?

**Comment by nao20010128nao** [comment]
> > TC allows downloading only one stream simultaneously.
> 
> But then, how does the browser play the video + audio?

They do not deliver audio and video separately. On browser, when the first split reaches to the end, player replaced by new split and start from zero seconds.

**Comment by pukkandan** [comment]
Seems I misunderstood your issue. If the streams are split in time, the general approach is to implement it as a `multi_video`. There is currently no support for concatting the parts together though. However, something like https://github.com/ytdl-org/youtube-dl/pull/28153 can be implemented for it using the concat demuxer of #360

**Comment by pukkandan** [comment]
> It seems we have to request the next playlist after we download last segment of previous playlist.

This is still an issue though 🤔

**Comment by nao20010128nao** [comment]
> If the streams are split in time, the general approach is to implement it as a multi_video. 

Wow, `multi_video` looks good for such purpose. My bad.

It's better if we're able to complete downloading and joining multiple video as a format. This behavior makes newbies happy.

> > It seems we have to request the next playlist after we download last segment of previous playlist.
> 
> This is still an issue though thinking

This means that we must not download two or more streams in parallel. Don't think it too difficult.

**Comment by pukkandan** [comment]
> This means that we must not download two or more streams in parallel. Don't think it too difficult.

Again, I seem to have misunderstood. I thought you have to fetch the second stream's URL after the download of first stream is finished. Due to the strict separation of extraction and downloading in youtube-dl, this is difficult to achieve without creating a custom downloader like for niconico

**Comment by nao20010128nao** [comment]
Yes, we probably need new FD. But to confirm, all m3u8 playlists needed to download all splits are all provided in the webpage. We don't have to make a request for each splits every time.

**Comment by pukkandan** [comment]
> Yes, we probably need new FD

Why?

**Comment by nao20010128nao** [comment]
> > Yes, we probably need new FD
> 
> Why?

Oh, maybe not. When `multi_video` supports joining after downloading, we don't need it at all.

**Comment by pukkandan** [comment]
Does #399 close this?

**Comment by nao20010128nao** [comment]
> Does #399 close this?

No. Unrelated PR.
