### ISSUE TITLE
"Incomplete data received" When downloading from Youtube

### ISSUE THREAD

**Issue by 424778940z** [yt-dlp/yt-dlp#3827]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.05.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Japan

### Description

Getting "Incomplete data received" error when download from Youtube membership page.
In the browser the page will keep circling when it reaches the last item.
This should be a Youtube issue actually, but yt-dlp seems dropped the last not "fully" loaded page all together, even the last page contains videos to be downloaded.
It is unlikely Youtube gonna fix it any time soon, I really hope yf-dlp provide a workaround

### Verbose log

```shell
[debug] Command-line config: ['-vU', 'https://www.youtube.com/channel/UC_vMYWcDjmfdpH6r4TTn1MQ/membership', '--download-archive', 'archive_list_member.txt', '--cookies', 'youtube.com_cookies.txt', '-o', 'membership\\%(release_date)s_%(title)s_%(id)s.%(ext)s']
[debug] Portable config "E:\Iroha ch. 風真いろは - holoX -\yt-dlp.conf": ['-f', 'bestvideo*+bestaudio/best', '--write-description', '--write-thumbnail', '--write-info-json', '--no-write-comments', '--continue', '--concurrent-fragments', '20', '-R', 'infinite', '--http-chunk-size', '10M', '--proxy', 'socks5://127.0.0.1:10808/']
[debug] Encodings: locale cp936, fs utf-8, pref cp936, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.05.18 [b14d523] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: ffmpeg -bsfs
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.14.1, brotli-1.0.9, certifi-2021.10.08, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {'http': 'socks5://127.0.0.1:10808/', 'https': 'socks5://127.0.0.1:10808/'}
[debug] Loading archive file 'archive_list_member.txt'
Latest version: 2022.05.18, Current version: 2022.05.18
yt-dlp is up to date (2022.05.18)
[debug] [youtube:tab] Extracting URL: https://www.youtube.com/channel/UC_vMYWcDjmfdpH6r4TTn1MQ/membership
[youtube:tab] UC_vMYWcDjmfdpH6r4TTn1MQ: Downloading webpage
[debug] [youtube:tab] Final URL: https://www.youtube.com/channel/UC_vMYWcDjmfdpH6r4TTn1MQ/membership
[download] Downloading playlist: Iroha ch. 風真いろは - holoX - - Membership
[debug] [youtube:tab] Extracted SAPISID cookie
[youtube:tab] UC_vMYWcDjmfdpH6r4TTn1MQ page 1: Downloading API JSON
[youtube:tab] UC_vMYWcDjmfdpH6r4TTn1MQ page 2: Downloading API JSON
[youtube:tab] UC_vMYWcDjmfdpH6r4TTn1MQ page 3: Downloading API JSON
WARNING: [youtube:tab] Incomplete data received. Retrying ...
[youtube:tab] UC_vMYWcDjmfdpH6r4TTn1MQ page 3: Downloading API JSON (retry #1)
WARNING: [youtube:tab] Incomplete data received. Retrying ...
[youtube:tab] UC_vMYWcDjmfdpH6r4TTn1MQ page 3: Downloading API JSON (retry #2)
WARNING: [youtube:tab] Incomplete data received. Retrying ...
[youtube:tab] UC_vMYWcDjmfdpH6r4TTn1MQ page 3: Downloading API JSON (retry #3)
ERROR: Incomplete data received; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1395, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1700, in <lambda>
  File "yt_dlp\utils.py", line 2630, in __getitem__
  File "yt_dlp\extractor\youtube.py", line 4098, in _entries
  File "yt_dlp\extractor\youtube.py", line 835, in _extract_response
yt_dlp.utils.ExtractorError: Incomplete data received; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

**Comment by coletdjnz** [comment]
Nothing we can do, it is a youtube server-side issue. On the UI as you noted it it gets stuck on the same page too.

> This should be a Youtube issue actually, but yt-dlp seems dropped the last not "fully" loaded page all together, even the last page contains videos to be downloaded.

The last page doesn't contain _anything_ useful (i.e. zero videos, posts) when it should (hence the incomplete data error we throw).

By default yt-dlp should still download the videos it was able to extract before then.
