### ISSUE TITLE
Prevent excessive use of external programs

### ISSUE THREAD

**Issue by reallyuniquename** [yt-dlp/yt-dlp#3830]
### Checklist

- [X] I'm reporting a feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.05.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

EVery time yt-dlp starts it launches multiple external programs that might be not required. This brings some overhead. For instance, if you launch yt-dlp often enough just to get direct URL to the content delay becomes very noticable. Especially on slower systems.

1. `ffprobe -bsfs` / `ffmpeg -bsfs`

These are very large binaries, almost 100MB each, launched every time. I don't see a reason to run them just to get their version unless extractor requires it.

2. `cmd /c ver` / `cmd /c ""`

The first command is launched over a dozen of times which is bonkers. I'm not sure but I reckon this is what modern Python does on Windows to get its version. Maybe cache output the first time? It's not like OS version is going to change mid-run.
I don't even know what's the point of the second one, probably part of the same routine.

It would be nice to add an option to disable ^1 and also fix ^2.

**Comment by pukkandan** [comment]
> `ffprobe -bsfs` / `ffmpeg -bsfs`

This is run only when needed (or when using `-v` - to show version in head)

> `cmd /c ver` / `cmd /c ""`

The `cmd /c ""` is a hack to get ANSI codes working. Removing this call is tricky. See https://bugs.python.org/issue30075

`cmd /c ver` is definitely not being launched by yt-dlp directly. Might be better to open an issue on Python for caching this. That said, if this has a significant performance impact, we can look at caching it (assuming we can figure out exactly what is running it)

**Comment by pukkandan** [comment]
`ver` is being called by `platform.win32_ver()` in `utils.get_windows_version`

> The first command is launched over a dozen of times which is bonkers.

Is this observation from the current master, or the release? I have already implemented cache for `get_windows_version` in master, so this should only be run once

**Comment by reallyuniquename** [comment]
> This is run only when needed

Why would `yt-dlp -F https://www.youtube.com/watch?v=OOu-xloMDlY` need `ffmpeg` or `ffprobe?`

> Is this observation from the current master, or the release?

That's release.

>The cmd /c "" is a hack to get ANSI codes working. Removing this call is tricky.

Oh. Don't bother then, it's only launched once.

**Comment by pukkandan** [comment]
> Why would `yt-dlp -F https://www.youtube.com/watch?v=OOu-xloMDlY` need `ffmpeg` or `ffprobe?`

hm.. I see the issue. Let me see what can be done

**Comment by reallyuniquename** [comment]
That was quick! 

> The `cmd /c ""` is a hack to get ANSI codes working. Removing this call is tricky

I'm giving this a second thought. This is only relevant when user expects to visually inspect terminal output, right? If you simply pipe yt-dlp to other tools there is no point doing that. Maybe add an option to disable it? Randomly popping up cmd.exe is always a worrisome thing.
