### ISSUE TITLE
yt-dlp wont download from MTV Lebanon

### ISSUE THREAD

**Issue by SweatyGamer546** [yt-dlp/yt-dlp#3834]
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.05.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Worldwide

### Example URLs

- Top site: https://www.mtv.com.lb/vod/en/
- Video i want to download: https://www.mtv.com.lb/vod/en/video/212090

### Description

Video won't download through yt-dlp, always getting unsupported url errors

### Verbose log

```shell
yt-dlp -vU https://www.mtv.com.lb/vod/en/video/212090
[debug] Command-line config: ['-vU', 'https://www.mtv.com.lb/vod/en/video/212090']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.05.18 [b14d52355]
[debug] Python version 3.9.5 (CPython 64bit) - macOS-10.13.6-x86_64-i386-64bit
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: avprobe -bsfs
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: avconv -bsfs
[debug] exe versions: none
[debug] Optional libraries: certifi-2021.05.30, sqlite3-2.6.0
[debug] Proxy map: {}
Latest version: 2022.05.18, Current version: 2022.05.18
yt-dlp is up to date (2022.05.18)
[debug] [generic] Extracting URL: https://www.mtv.com.lb/vod/en/video/212090
[generic] 212090: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] 212090: Downloading webpage
[generic] 212090: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://www.mtv.com.lb/vod/en/video/212090
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1395, in wrapper
    return func(self, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1465, in __extract_info
    ie_result = ie.extract(url)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 642, in extract
    ie_result = self._real_extract(url)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/yt_dlp/extractor/generic.py", line 4031, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.mtv.com.lb/vod/en/video/212090
```

**Comment by SweatyGamer546** [comment]
New comment: site works with news replays which doesn’t require an account but video i'm looking for still gives error above

**Comment by pukkandan** [comment]
I assume you have already tried passing cookies

**Comment by SweatyGamer546** [comment]
> I assume you have already tried passing cookies

haven’t tried that but someone in the server recommended to try to find the m3u8 link in the dev menu and that worked

**Comment by pukkandan** [comment]
That would pretty much always work. The point of site request is so that you don't have to manually do that.

Please check with cookies and provide verbose log
