### ISSUE TITLE
Having trouble with --match-filter

### ISSUE THREAD

**Issue by cinbunnaps** [yt-dlp/yt-dlp#3840]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

I'm marking this as a question rather than a bug because I'm fairly certain this is user error. I'm trying to specify to download a playlist but only videos over a certain duration. I'm using --match-filter "duration>7200" (trying to get the fill unedited court recording of Depp's lawsuit, that's why so long lol) and coming back with an error saying 'command not found' then it skips ahead to download all videos of the playlist. I've looked through the documentation up and down to figure out what I'm missing and can't figure it out. I do have a yt-dlp.conf file I usually use but I also ran the same command from a different folder to see if it was clashing and came across the same issue.

**Comment by pukkandan** [comment]
Something wrong with your quoting
