### ISSUE TITLE
[Instagram] Live Support

### ISSUE THREAD

**Issue by JaxonPlays** [yt-dlp/yt-dlp#3843]
### Checklist

- [X] I'm reporting a site feature request
- [X] I've verified that I'm running yt-dlp version **2022.05.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Example URLs

https://www.instagram.com/user/live

### Description

Seen no one request this.

### Verbose log

```shell
N/A

Comes as generic and forbidden.
```

**Comment by gamer191** [comment]
> ```shell
> N/A
> 
> Comes as generic and forbidden.
> ```

Please explain why it's not applicable
