### ISSUE TITLE
yt-dlp python module not compiling with pyinstaller

### ISSUE THREAD

**Issue by sourabhkv** [yt-dlp/yt-dlp#3845]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

I updated yt_dlp to 22.05.18 verion and compiled code using pyinstaller but application never started
![Screenshot 2022-05-23 140122](https://user-images.githubusercontent.com/55890376/169778340-e396bf1e-425a-46d4-982f-a436737a4e39.png)
Then i installed 22.04.08 and it was working
Is there any issue with latest version ?

**Comment by pukkandan** [comment]
Running `pyinstaller` by itself was never meant to work properly with yt-dlp. Use `pyinst.py` as explained in https://github.com/yt-dlp/yt-dlp#compile

**Comment by pukkandan** [comment]
If you are unable to run pyinst for some reason, `pyinstaller --hidden-import yt_dlp.compat._legacy` is currently a good approximation. But I cannot guarantee that this will not break in future versions

**Comment by sourabhkv** [comment]
Thanks hidden import worked

**Comment by bashonly** [comment]
An update since this issue is listed in the [FAQ](https://github.com/yt-dlp/yt-dlp/issues/3766):

`pyinst.py` has been removed from the repository. The new solution is using `python -m bundle.pyinstaller`
