### ISSUE TITLE
SHA2-256SUMS cannot be verified using standard Linux tools

### ISSUE THREAD

**Issue by nihil-admirari** [yt-dlp/yt-dlp#385]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running yt-dlp version **2021.06.01**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```bash
$ sha256sum -c SHA2-256SUMS
sha256sum: SHA2-256SUMS: no properly formatted SHA256 checksum lines found
```

## Description

SHA256 provided with the release cannot be verified using standard Linux tools. The reason is two-fold:
1. `file:hash` is not a standard checksum syntax, `coreutils` understands only GNU `hash file` or BSD `SHA256(file) = hash` styles.
2. For some reason, `SHA2-256SUMS` has Windows line endings, not Unix ones.

The current format was inherited from `youtube-dlc`. Autoupdater depends on it, but will only issue a warning when the format is changed. Support for the new format was added in https://github.com/yt-dlp/yt-dlp/pull/383.

When a substantial number of people have updated their `yt-dlp`s, checksum format should change to comply with UNIX standards.

**Comment by redactedscribe** [comment]
I was about to report the same essentially.

I had to use the SHA2-*512*SUMS file for my tool in question to be able to extract the hash. Hopefully the *256* SUMS file generation can be updated to output the same format as what is in the 512 file.
