### ISSUE TITLE
Cartoon Network: Unable to extract post url

### ISSUE THREAD

**Issue by lishremix** [yt-dlp/yt-dlp#3859]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.05.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

USA

### Description

I'm trying to download from the Cartoon Network site. I have done this successfully in the past, using cookies, I believe. This time I hit an error. The log indicated that I need to use the --ap-mso, --ap-username and --ap-password options. I updated my command to include these options and received the error below. 

ERROR: [CartoonNetwork] whodundidit: Unable to extract post url; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

### Verbose log

```shell
[debug] Command-line config: ['-vU', '--write-subs', '--sub-langs', 'en', '--sub-format', 'srt', '--ffmpeg-location', 'C:\\ffmpeg\\bin', '--ap-mso', 'DTV', '--ap-username', 'PRIVATE', '--ap-password', 'PRIVATE', 'https://www.cartoonnetwork.com/video/teen-titans-go/whodundidit-episode.html']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.05.18 [b14d523] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] Checking exe version: "C:\ffmpeg\bin\ffprobe" -bsfs
[debug] Checking exe version: "C:\ffmpeg\bin\ffmpeg" -bsfs
[debug] exe versions: ffmpeg 2022-05-16-git-e3580f6077-full_build-www.gyan.dev (setts), ffprobe 2022-05-16-git-e3580f6077-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.14.1, brotli-1.0.9, certifi-2021.10.08, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
Latest version: 2022.05.18, Current version: 2022.05.18
yt-dlp is up to date (2022.05.18)
[debug] [CartoonNetwork] Extracting URL: https://www.cartoonnetwork.com/video/teen-titans-go/whodundidit-episode.html
[CartoonNetwork] whodundidit: Downloading webpage
[CartoonNetwork] c7029d3afb37967d5bf73ffea6c798d9c5bf6ac3: Downloading JSON metadata
[CartoonNetwork] c7029d3afb37967d5bf73ffea6c798d9c5bf6ac3: Downloading Provider Redirect Page
[CartoonNetwork] c7029d3afb37967d5bf73ffea6c798d9c5bf6ac3: Downloading Provider Login Page
ERROR: [CartoonNetwork] whodundidit: Unable to extract post url; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 642, in extract
  File "yt_dlp\extractor\cartoonnetwork.py", line 36, in _real_extract
  File "yt_dlp\extractor\turner.py", line 234, in _extract_ngtv_info
  File "yt_dlp\extractor\turner.py", line 38, in _add_akamai_spe_token
  File "yt_dlp\extractor\adobepass.py", line 1713, in _extract_mvpd_auth
  File "yt_dlp\extractor\adobepass.py", line 1393, in post_form
  File "yt_dlp\extractor\common.py", line 1235, in _html_search_regex
  File "yt_dlp\extractor\common.py", line 1226, in _search_regex
```

**Comment by pukkandan** [comment]
It's not CN, but DTV login that is broken - Same issue as https://github.com/yt-dlp/yt-dlp/issues/2188
