### ISSUE TITLE
[Feature Request]: Release shell completions

### ISSUE THREAD

**Issue by nihil-admirari** [yt-dlp/yt-dlp#386]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running yt-dlp version **2021.06.01**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description

Currently it seems that the only way to get shell completions is to clone the repository and run `make`. Wouldn't it be better if completions were released along with other artefacts?

**Comment by pukkandan** [comment]
The same issue exists for the manpage as well. Instead of releasing each of these files seperately, what do you think of simply releasing the tar generated by `make tar`, similar to what youtube-dl does?
