### ISSUE TITLE
radiko.jp premium

### ISSUE THREAD

**Issue by noname89610** [yt-dlp/yt-dlp#3860]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

Can I download using radiko's premium account?

**Comment by pukkandan** [comment]
https://tryitands.ee/
