### ISSUE TITLE
[QUESTION] Make archive faster after changing file archive list structure

### ISSUE THREAD

**Issue by afterdelight** [yt-dlp/yt-dlp#3864]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

So i changed file archive list structure from lines in `'_make_archive_id'` function

from
`return f'{extractor} {video_id}'`

to
`return f'{extractor.lower()} {uploader} {title} ({video_id})'`
 
it makes the archiving changed

from
`iwara 4jqbmudrwcwmoqwl`

to
`Iwara 000MMD クソガキでCHUNG HA - Dream of You (18kqetlxjt3w8wd3)`

Now instead of fast loading archive like this

```
F:\downloader\iwara.tv\dl>ytdl-patched -a 000MMD_links.txt --conf config_iwara
[Iwara] 03yedh9lbizq1kq8: has already been recorded in the archive
[Iwara] 18kqetlxjt3w8wd3: has already been recorded in the archive
[Iwara] 25xbni92aixod0wo: has already been recorded in the archive
[Iwara] 4jqbmudrwcwmoqwl: has already been recorded in the archive
[iwara] 6a8als43auo2aezk: Downloading webpage
```

I get a slow loading archive like this

```
F:\downloader\iwara.tv\dl>ytdl-patched` -a 000MMD_links.txt --conf config_iwara
[iwara] 03yedh9lbizq1kq8: Downloading webpage
[iwara] 03yedh9lbizq1kq8: Downloading JSON metadata
WARNING: [iwara] unable to extract upload_date; please report this issue on  https://github.com/ytdl-patched/ytdl-patched/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[download] ミニスカポリスなミクたちでSOLAR - Spit it out has already been recorded in the archive
[iwara] 18kqetlxjt3w8wd3: Downloading webpage
[iwara] 18kqetlxjt3w8wd3: Downloading JSON metadata
WARNING: [iwara] unable to extract upload_date; please report this issue on  https://github.com/ytdl-patched/ytdl-patched/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[download] クソガキでCHUNG HA - Dream of You has already been recorded in the archive
```

The question is
What other lines i need to change to make it load archive faster like it used to be?

**Comment by gamer191** [comment]
Please do not report issues or ask questions related to ytdl-patched in the yt-dlp repo, they should be reported [here](https://github.com/ytdl-patched/ytdl-patched/issues?q=)

**Comment by coletdjnz** [comment]
you will need to edit how it reads and parses the file

**Comment by pukkandan** [comment]
You are not supposed to change the archive format! If you want a file with other metadata, use `--print-to-file`

As for why it slow, it is because yt-dlp cannot determine `title` and `uploader` without extracting the video information. When it is just the `id`, we can determine it from the URL without making any network requests (not for all sites, but works here) and so the entire extraction process is skipped

**Comment by afterdelight** [comment]
ty for the explanation. can --print-to-file be used to read as download archive file?
so no way around to pre-load the title and uploader when first time reading the channel link?

**Comment by afterdelight** [comment]
when i use channel link https://ecchi.iwara.tv/users/000MMD
it showed up as the normal fast reading archive file
```
[download] Downloading video 1 of 152
[Iwara] gallrtxovhye3j7z: has already been recorded in the archive
[download] Downloading video 2 of 152
[Iwara] 4jqbmudrwcwmoqwl: has already been recorded in the archive
[download] Downloading video 3 of 152
[Iwara] 25xbni92aixod0wo: has already been recorded in the archive
[download] Downloading video 4 of 152
```
then probably can be pre-loaded first when first time reading channel links?

**Comment by afterdelight** [comment]
> you probably need to edit how it reads and parses the file

how to do that?

**Comment by afterdelight** [comment]
can this issue re-opened again? its still hanging
