### ISSUE TITLE
[Site Request] Support translated/localized YouTube titles and descriptions

### ISSUE THREAD

**Issue by dude22072** [yt-dlp/yt-dlp#387]
## Checklist

- [x] I'm reporting a site feature request
- [x] I've verified that I'm running yt-dlp version **2021.06.08**
- [x] I've searched the bugtracker for similar site feature requests including closed ones

## Description

An official feature of YouTube is allowing uploaders to provide translated titles/descriptions for their videos. Which title displays depends upon the language you have YouTube set to display in. When writing the infojson file or the description file youtube-dl and its forks only have the title/description in the original language and has no mentions of other languages. This feature should be included for the sake of those who use this program for archiving purposes. A solution would be to turn "title" in the infojson into a tree instead of a string, or to not break compatibility have a separate tree named "title_translated" or similar and use the language identifier (en_US, ja_JP, etc) as the key for objects in the tree.

**Comment by dude22072** [comment]
Additional note: the title of the channel itself as well as the channel descriptions can also have translated versions.

**Comment by colethedj** [comment]
Related upstream PR for titles: https://github.com/ytdl-org/youtube-dl/pull/28538

**Comment by pukkandan** [comment]
I am against implementing https://github.com/ytdl-org/youtube-dl/pull/28538 as-is. This only converts the issue of not having the translated title to not having the original title instead. We could instead put the translated title in `alt_title`. Not sure what to do with the description

> have a separate tree named "title_translated" or similar and use the language identifier (en_US, ja_JP, etc) as the key for objects in the tree.

A seperate webpage will need to be requested just for each language afaik, not to mention there is no list of translated languages available

**Comment by dude22072** [comment]
Perhaps this is something that could be added as a command line switch then, such as `--langs "en_US,ja_JP"` for example. YouTube killed off the community submitted translations feature, so in theory the only translated titles and descriptions should be ones set by the uploader themselves, and users will probably be able to make educated guesses about what languages a creator uses on their channel.

**Comment by msikma** [comment]
> @msikma Lol, that endpoint worked on Innertube API key from MWEB client, meaning we don't need to get an API key just for it for now.

Oh, that's interesting. I'm not familiar with it, is that like a "free" internal API that Youtube uses in its frontend?

**Comment by coletdjnz** [comment]
> > @msikma Lol, that endpoint worked on Innertube API key from MWEB client, meaning we don't need to get an API key just for it for now.
> 
> Oh, that's interesting. I'm not familiar with it, is that like a "free" internal API that Youtube uses in its frontend?

Yes Innertube is the undocumented API YouTube uses for their apps, and is what yt-dlp and the like use too.

Funny thing is, as @nao20010128nao found, a few of the Innertube API keys also work with the official YouTube data API :wink: (but they tend to hit their quota, so not much use)

AFAIK we cannot use the YouTube Data API in yt-dlp, so we are stuck to Innertube.

**Comment by coletdjnz** [comment]
#1018 added some boilerplate that would allow us to set the language used for webpages/API calls for all YouTube extractors. Currently it is set to English to prevent metadata parsing issues in a few places.

Currently we could probably add a way of users specifying the language for extraction to get the localised title and description for that language, with the cost of missing some other metadata.

Extracting all localised titles I still don't believe is possible atm- I am not aware of any Innertube endpoints that do not require auth and do not require you to be the owner of the video to get translations.

**Comment by coletdjnz** [comment]
> We could probably add a way of users specifying the language for extraction to get the localised title and description for that language, with the cost of missing some other metadata.

I'm thinking, at least for now, we should do this since it shouldn't be too hard to do.

Right now we are currently extracting the original and english translated fields (preferring original where applicable).

We could add an extractor arg that takes a supported language code (as per YouTube's list). In which when set, extraction will prefer the translated fields where applicable. 

Something like `--extractor-args youtube:lang=ja`

It's not the best solution but should be enough for those just wanting the translated title for yt.

Of course, as mentioned before, there will be metadata extraction issues in some places (e.g. relative time text, but should be rather limited)

**Comment by pukkandan** [comment]
Alright, you can implement it. But do warn that metadata may be missing
