### ISSUE TITLE
Fix for "Sign in to confirm your age. This video may be inappropriate for some users" ?

### ISSUE THREAD

**Issue by nmr50** [yt-dlp/yt-dlp#3873]
### Checklist

- [X] I'm reporting a site feature request
- [X] I've verified that I'm running yt-dlp version **2022.05.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Russia

### Example URLs

https://youtu.be/gdEuD9MMZd0

### Description

This video _can_ be viewed when user is logged into youtube, but it is (almost?) impossible to get this video with yt_dlp:
>yt-dlp.exe -F https://youtu.be/gdEuD9MMZd0
[youtube] gdEuD9MMZd0: Downloading webpage
[youtube] gdEuD9MMZd0: Downloading android player API JSON
[youtube] gdEuD9MMZd0: Downloading tv embedded player API JSON
[youtube] gdEuD9MMZd0: Downloading web embedded client config
[youtube] gdEuD9MMZd0: Downloading player d1783cbe
[youtube] gdEuD9MMZd0: Downloading web embedded player API JSON
ERROR: [youtube] gdEuD9MMZd0: Sign in to confirm your age. This video may be inappropriate for some users.

I have heard info about cookies and other stuff those are supposed to help to solve this case, but I never got this scheme working...

Dear author: can you PLEASE make new feature that will assure youtube that yt_dlp is 42 years old user - to get videos like mentioned earlier w/o problems ?

Thank You in advance !

### Verbose log

```shell
>yt-dlp.exe -Fv https://youtu.be/gdEuD9MMZd0
[debug] Command-line config: ['-Fv', 'https://youtu.be/gdEuD9MMZd0']
[debug] Encodings: locale cp1251, fs utf-8, pref cp1251, out utf-8 (No ANSI), error utf-8 (No
 ANSI), screen utf-8 (No ANSI)
[debug] yt-dlp version 2022.05.18 [b14d523] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-7-6.1.7601-SP1
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: ffmpeg -bsfs
[debug] exe versions: ffmpeg n5.0-48-gcffa10a0cb-20220401 (setts), ffprobe n5.0-48-gcffa10a0cb-20220401
[debug] Optional libraries: Cryptodome-3.14.1, brotli-1.0.9, certifi-2021.10.08, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] [youtube] Extracting URL: https://youtu.be/gdEuD9MMZd0
[youtube] gdEuD9MMZd0: Downloading webpage
[youtube] gdEuD9MMZd0: Downloading android player API JSON
[youtube] gdEuD9MMZd0: Downloading tv embedded player API JSON
[youtube] gdEuD9MMZd0: Downloading web embedded client config
[youtube] gdEuD9MMZd0: Downloading player d1783cbe
[youtube] gdEuD9MMZd0: Downloading web embedded player API JSON
ERROR: [youtube] gdEuD9MMZd0: Sign in to confirm your age. This video may be inappropriate for some users.
  File "yt_dlp\extractor\common.py", line 642, in extract
  File "yt_dlp\extractor\youtube.py", line 3437, in _real_extract
  File "yt_dlp\extractor\common.py", line 1158, in raise_no_formats
```

**Comment by coletdjnz** [comment]
Due to the age-restriction on this video it requires cookies/an account to view as you alluded to. 

Try adding `--cookies-from-browser browser` e.g. `--cookies-from-browser chrome`

**Comment by nmr50** [comment]
> Due to the age-restriction on this video it requires cookies/an account to view as you alluded to.
> Try adding `--cookies-from-browser browser` e.g. `--cookies-from-browser chrome`
as I said - I have tried to use those - but it _never_ worked, alas...

**Comment by Lesmiscore** [comment]
The best way to bypass this restriction is to make an account with 20+ yrs old and pass logged in cookies of the account.

**Comment by nmr50** [comment]
R:\OUT>yt-dlp.exe -F https://youtu.be/gdEuD9MMZd0 --cookies-from-browser chrome
[Cookies] Extracting cookies from chrome
ERROR: no encrypted key in Local State
[Cookies] Extracted 285 cookies from chrome
[youtube] gdEuD9MMZd0: Downloading webpage
[youtube] gdEuD9MMZd0: Downloading android player API JSON
[youtube] gdEuD9MMZd0: Downloading tv embedded player API JSON
[youtube] gdEuD9MMZd0: Downloading web embedded client config
[youtube] gdEuD9MMZd0: Downloading player d1783cbe
[youtube] gdEuD9MMZd0: Downloading web embedded player API JSON
ERROR: [youtube] gdEuD9MMZd0: Sign in to confirm your age. This video may be inappropriate for some users.
-- no success as I said...

**Comment by nmr50** [comment]
>yt-dlp.exe -F https://youtu.be/gdEuD9MMZd0 --cookies-from-browser chromium
[Cookies] Extracting cookies from chromium
[Cookies] Extracted 879 cookies from chromium
[youtube] gdEuD9MMZd0: Downloading webpage
[youtube] gdEuD9MMZd0: Downloading android player API JSON
[youtube] gdEuD9MMZd0: Downloading tv embedded player API JSON
[youtube] gdEuD9MMZd0: Downloading web embedded client config
[youtube] gdEuD9MMZd0: Downloading player d1783cbe
[youtube] gdEuD9MMZd0: Downloading web embedded player API JSON
ERROR: [youtube] gdEuD9MMZd0: Sign in to confirm your age. This video may be inappropriate for some users.

-- no matter, chrome, chromium, firefox - yt_dl loads cookies but exits with the same 'sign in' error.. ;/

**Comment by gamer191** [comment]
> no matter, chrome, chromium, firefox - yt_dl loads cookies but exits with the same 'sign in' error.. ;/

are you logged in on all 3 browsers?

**Comment by nmr50** [comment]
> > no matter, chrome, chromium, firefox - yt_dl loads cookies but exits with the same 'sign in' error.. ;/
> 
> are you logged in on all 3 browsers?

No, I use SrWare Iron (portable), iron itself and Seamonkey portable. I have Chrome (portable) and FF (portable) on my PC.

**Comment by pukkandan** [comment]
If you are not logged in to browser, how do you expect `--cookies-from-browser` to work? Manually export cookies instead. See https://www.reddit.com/r/youtubedl/wiki/cookies

**Comment by nmr50** [comment]
> If you are not logged in to browser, how do you expect `--cookies-from-browser` to work? Manually export cookies instead. See https://www.reddit.com/r/youtubedl/wiki/cookies
Yes, it worked with plugin that exported exactly youtube cookies to the files. Thanks for help !

**Comment by nmr50** [comment]
heck, can someone close this one as solved case ?:)

**Comment by jaziel-lopez** [comment]
suggestion worked for me. In my case I have installed brave as default browser so it ended up looking like:

```
yt-dlp https://www.youtube.com/watch\?v\=VIDEOID --cookies-from-browser brave
[Cookies] Extracting cookies from brave
[Cookies] Extracted 3058 cookies from brave
[youtube] JObEWzsHyvU: Downloading webpage
[youtube] JObEWzsHyvU: Downloading android player API JSON
[info] JObEWzsHyvU: Downloading 1 format(s): 248+251
```
