### ISSUE TITLE
[YouTube] `youtube:skip=translated_subs` doesn't work for some videos.

### ISSUE THREAD

**Issue by 1sixth** [yt-dlp/yt-dlp#3875]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.05.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Description

The `translated_subs` argument introduced in version `2022.04.08` only works in some cases.

`yt-dlp` works as intended in this example:

```
yt-dlp --ignore-config --write-subs --write-auto-subs --sub-langs all --extractor-args "youtube:skip=translated_subs" "https://www.youtube.com/watch?v=T2kS1gAbxhc"
```

It downloads 26 subtitles, skipping all the auto-translated ones.

But it doesn't work for this video: <https://www.youtube.com/watch?v=bOXCLR3Wric>

### Verbose log

```shell
[debug] Command-line config: ['--verbose', '--ignore-config', '--write-subs', '--write-auto-subs', '--sub-langs', 'all', '--extractor-args', 'youtube:skip=translated_subs', 'https://www.youtube.com/watch?v=bOXCLR3Wric']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.05.18 [b14d52355]
[debug] Python version 3.9.12 (CPython 64bit) - Linux-5.17.9-x86_64-with-glibc2.34
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: ffmpeg -bsfs
[debug] exe versions: ffmpeg 4.4.1 (setts), ffprobe 4.4.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.14.1, brotli-1.0.9, certifi-2021.10.08, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.1
[debug] Proxy map: {'no': '127.0.0.1,localhost', 'ftp': 'http://127.0.0.1:1081', 'https': 'http://127.0.0.1:1081', 'http': 'http://127.0.0.1:1081', 'all': 'http://127.0.0.1:1081', 'rsync': 'http://127.0.0.1:1081'}
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=bOXCLR3Wric
[youtube] bOXCLR3Wric: Downloading webpage
[youtube] bOXCLR3Wric: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[debug] Downloading subtitles: en, af, sq, am, ar, hy, az, bn, eu, be, bs, bg, my, ca, ceb, zh-Hans, zh-Hant, co, hr, cs, da, nl, en-orig, eo, et, fil, fi, fr, gl, ka, de, el, gu, ht, ha, haw, iw, hi, hmn, hu, is, ig, id, ga, it, ja, jv, kn, kk, km, rw, ko, ku, ky, lo, la, lv, lt, lb, mk, mg, ms, ml, mt, mi, mr, mn, ne, no, ny, or, ps, fa, pl, pt, pa, ro, ru, sm, gd, sr, sn, sd, si, sk, sl, so, st, es, su, sw, sv, tg, ta, tt, te, th, tr, tk, uk, ur, ug, uz, vi, cy, fy, xh, yi, yo, zu
[debug] Default format spec: bestvideo*+bestaudio/best
[info] bOXCLR3Wric: Downloading 1 format(s): 313+251
[info] Writing video subtitles to: The unreasonable effectiveness of complex numbers in discrete math [bOXCLR3Wric].en.vtt
[debug] Invoking http downloader on "https://www.youtube.com/api/timedtext?v=bOXCLR3Wric&caps=asr&xoaf=5&xosf=1&hl=en&ip=0.0.0.0&ipbits=0&expire=1653592120&sparams=ip%2Cipbits%2Cexpire%2Cv%2Ccaps%2Cxoaf&signature=CE03F84903AC811E4A7EC49EEAA05D7F498B2C3C.ADF5D40DE8FEAA19172D9F174D18C543149E267E&key=yt8&lang=en&fmt=vtt"
[download] Destination: The unreasonable effectiveness of complex numbers in discrete math [bOXCLR3Wric].en.vtt
[download] 100% of 65.30KiB in 00:00
[info] Writing video subtitles to: The unreasonable effectiveness of complex numbers in discrete math [bOXCLR3Wric].af.vtt
[debug] Invoking http downloader on "https://www.youtube.com/api/timedtext?v=bOXCLR3Wric&caps=asr&xoaf=5&xosf=1&hl=en&ip=0.0.0.0&ipbits=0&expire=1653592120&sparams=ip%2Cipbits%2Cexpire%2Cv%2Ccaps%2Cxoaf&signature=CE03F84903AC811E4A7EC49EEAA05D7F498B2C3C.ADF5D40DE8FEAA19172D9F174D18C543149E267E&key=yt8&kind=asr&lang=en&tlang=af&fmt=vtt"
[download] Destination: The unreasonable effectiveness of complex numbers in discrete math [bOXCLR3Wric].af.vtt
[download] 100% of 354.51KiB in 00:00
[info] Writing video subtitles to: The unreasonable effectiveness of complex numbers in discrete math [bOXCLR3Wric].sq.vtt
[debug] Invoking http downloader on "https://www.youtube.com/api/timedtext?v=bOXCLR3Wric&caps=asr&xoaf=5&xosf=1&hl=en&ip=0.0.0.0&ipbits=0&expire=1653592120&sparams=ip%2Cipbits%2Cexpire%2Cv%2Ccaps%2Cxoaf&signature=CE03F84903AC811E4A7EC49EEAA05D7F498B2C3C.ADF5D40DE8FEAA19172D9F174D18C543149E267E&key=yt8&kind=asr&lang=en&tlang=sq&fmt=vtt"
[download] Destination: The unreasonable effectiveness of complex numbers in discrete math [bOXCLR3Wric].sq.vtt
[download] 100% of 376.53KiB in 00:00
^C
ERROR: Interrupted by user
```

**Comment by 1sixth** [comment]
> `skip=translated_subs` hides subs that are auto-translated from normal subtitles. These are just auto-generated subs of different languages.

It feels somewhat counterintuitive to me because initially I thought `skip=translated_subs` would skip everything in *Auto-translate*:

![image](https://user-images.githubusercontent.com/67363572/170532295-4d3c9e7e-2219-49be-b848-95eea8aeb835.png)

I wonder if there is a way to achieve that.

**Comment by pukkandan** [comment]
There is always only one "original" auto-subs. This is labeled as `(Original)` (lang ends with `-orig`) in `--list-subs`

**Comment by 1sixth** [comment]
Thank you for your explanation. My use case is to download all non auto-subs + *English (auto-generated)*. Now I am able to do that with:
```
yt-dlp --write-subs --sub-langs all "https://www.youtube.com/watch?v=bOXCLR3Wric"
yt-dlp --write-auto-subs --sub-langs en-orig "https://www.youtube.com/watch?v=bOXCLR3Wric"
```

**Comment by pukkandan** [comment]
Don't use `--write-auto-subs`? All auto-subs are machine translated

**Comment by NewUserHa** [comment]
The "auto-generated" speech-to-text sub/caption (e.g. English sub of English video) is the special case. Because non-native speakers or accent problems in some videos, It makes it easier for many audiences to watch.
Therefore the "auto-generated speech-to-text sub/caption" could be an exception from "-auto-subs".

**Comment by pukkandan** [comment]
```
[info] Available automatic captions for xxx:
Language        Name                                               
en-orig         English                                            Speech to text, in spoken language
es              Spanish                                            Speech to text
en-es           English from Spanish                               Auto-translated from en subs

[info] Available subtitles for xxx:
Language Name                    
en       English                 Uploaded by creator
```

**Comment by NewUserHa** [comment]
The both "en-orig" and "en".
Because the former contains additional: "sound effects, relevant musical cues, and other relevant audio information", and any missing translation in the latter.

I usually only saw one "auto-generated" sub, which is usually english on youtube web, so what is the "Spanish                                            Speech to text"?

**Comment by pukkandan** [comment]
I wrote it to explain

**Comment by pukkandan** [comment]
Issues are closed when solved. Which means, #2262 is not yet implemented and running 2 commands is your best workaround for now
