### ISSUE TITLE
[Broken] split-chapters is broken in 2021.06.08

### ISSUE THREAD

**Issue by vishytk** [yt-dlp/yt-dlp#388]
Just updated yt-dlp to 2021.06.08 and found that split-chapters is broken. I confirm that it is working with 2021.06.01

With 2021.06.08 I get "ERROR: %d format: a number is required, not str"

Debug output:

$ yt-dlp -v --split-chapters RGOj5yH7evk          
[debug] Command-line config: ['-v', '--split-chapters', 'RGOj5yH7evk']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] yt-dlp version 2021.06.08 (zip)
[debug] Python version 3.9.5 (CPython 64bit) - Linux-5.12.9-300.fc34.x86_64-x86_64-with-glibc2.33
[debug] exe versions: ffmpeg 4.4, ffprobe 4.4
[debug] Proxy map: {}
[debug] [youtube] Extracting URL: RGOj5yH7evk
[youtube] RGOj5yH7evk: Downloading webpage
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[info] RGOj5yH7evk: Downloading 1 format(s): 137+140
[youtube] RGOj5yH7evk: Downloading thumbnail  ...
[youtube] RGOj5yH7evk: Writing thumbnail to: Git and GitHub for Beginners - Crash Course.webp
[download] Git and GitHub for Beginners - Crash Course.mp4 has already been downloaded
[ThumbnailsConvertor] Converting thumbnail "Git and GitHub for Beginners - Crash Course.webp" to png
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -f image2 -pattern_type none -i 'file:Git and GitHub for Beginners - Crash Course.webp' 'file:Git and GitHub for Beginners - Crash Course.png'
[debug] ffprobe command line: ffprobe -hide_banner -show_format -show_streams -print_format json 'file:Git and GitHub for Beginners - Crash Course.mp4'
[EmbedThumbnail] ffmpeg: Adding thumbnail to "Git and GitHub for Beginners - Crash Course.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:Git and GitHub for Beginners - Crash Course.mp4' -i 'file:Git and GitHub for Beginners - Crash Course.png' -c copy -map 0 -dn -map 1 -map -0:2 -disposition:2 attached_pic 'file:Git and GitHub for Beginners - Crash Course.temp.mp4'
Deleting original file Git and GitHub for Beginners - Crash Course.webp (pass -k to keep)
Deleting original file Git and GitHub for Beginners - Crash Course.png (pass -k to keep)
[SplitChapters] Splitting video by chapters; 23 chapters found
ERROR: %d format: a number is required, not str
Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1128, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1160, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1197, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 2166, in process_video_result
    self.process_info(new_info)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 2716, in process_info
    info_dict = self.post_process(dl_filename, info_dict, files_to_move)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 2856, in post_process
    info = self.run_pp(pp, info)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 2805, in run_pp
    files_to_delete, infodict = pp.run(infodict)
  File "/usr/local/bin/yt-dlp/yt_dlp/postprocessor/ffmpeg.py", line 816, in run
    destination, opts = self._ffmpeg_args_for_chapter(idx + 1, chapter, info)
  File "/usr/local/bin/yt-dlp/yt_dlp/postprocessor/ffmpeg.py", line 797, in _ffmpeg_args_for_chapter
    destination = self._prepare_filename(number, chapter, info)
  File "/usr/local/bin/yt-dlp/yt_dlp/postprocessor/ffmpeg.py", line 794, in _prepare_filename
    return self._downloader.prepare_filename(info, 'chapter')
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 990, in prepare_filename
    filename = self._prepare_filename(info_dict, dir_type or 'default')
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 965, in _prepare_filename
    filename = expand_path(outtmpl).replace(sep, '') % template_dict
TypeError: %d format: a number is required, not str

**Comment by colethedj** [comment]
Doesn't seem limited to split-chapters. Looks like an issue with the output formatting code. Reported on discord:
```
yt-dlp https://www.youtube.com/playlist\?list\=PLY-ZbHfZ45-WZxxUTIvfc-vkKCRX6HSe4 -o '%(playlist_index)s - %(title)s.%(ext)s'
[youtube:tab] PLY-ZbHfZ45-WZxxUTIvfc-vkKCRX6HSe4: Downloading webpage
[youtube:tab] PLY-ZbHfZ45-WZxxUTIvfc-vkKCRX6HSe4: Downloading API JSON with unavailable videos
[download] Downloading playlist: A sesh Playlist DNB
ERROR: %d format: a number is required, not str
```

**Comment by pukkandan** [comment]
@vishytk I have made a release with a patch for this. Please update to it

**Comment by vishytk** [comment]
thank you.
