### ISSUE TITLE
Python crash when connection closed by remote host

### ISSUE THREAD

**Issue by FredMSloniker** [yt-dlp/yt-dlp#3882]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.05.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

I was checking the metadata of a video on YouTube (using `yt-dlp.exe -j https://www.youtube.com/watch?v=lsmwngrXyDc`), and apparently the connection was closed by the remote host for some reason. (Running the command again got me the data, so I can't show the results of the `-vU` flag.) However, yt-dlp handled this somewhat less than gracefully, crashing with a slew of Python errors rather than simply reporting the error.

### Verbose log

```shell
ERROR: [youtube] lsmwngrXyDc: Signature extraction failed: Traceback (most recent call last):
  File "urllib\request.py", line 1354, in do_open
  File "http\client.py", line 1252, in request
  File "http\client.py", line 1298, in _send_request
  File "http\client.py", line 1247, in endheaders
  File "http\client.py", line 1007, in _send_output
  File "http\client.py", line 947, in send
  File "http\client.py", line 1421, in connect
  File "ssl.py", line 500, in wrap_socket
  File "ssl.py", line 1040, in _create
  File "ssl.py", line 1309, in do_handshake
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\extractor\common.py", line 768, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 3596, in urlopen
  File "urllib\request.py", line 525, in open
  File "urllib\request.py", line 542, in _open
  File "urllib\request.py", line 502, in _call_chain
  File "yt_dlp\utils.py", line 1419, in https_open
  File "urllib\request.py", line 1357, in do_open
urllib.error.URLError: <urlopen error [WinError 10054] An existing connection was forcibly closed by the remote host>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\extractor\youtube.py", line 2540, in _decrypt_signature
  File "yt_dlp\extractor\youtube.py", line 2454, in _extract_signature_function
  File "yt_dlp\extractor\youtube.py", line 2435, in _load_player
  File "yt_dlp\extractor\common.py", line 933, in _download_webpage
  File "yt_dlp\extractor\common.py", line 801, in _download_webpage_handle
  File "yt_dlp\extractor\common.py", line 786, in _request_webpage
yt_dlp.utils.ExtractorError: Download of https://www.youtube.com/s/player/c403842a/player_ias.vflset/en_US/base.js failed: <urlopen error [WinError 10054] An existing connection was forcibly closed by the remote host> (caused by URLError(ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)))
 (caused by ExtractorError("Download of https://www.youtube.com/s/player/c403842a/player_ias.vflset/en_US/base.js failed: <urlopen error [WinError 10054] An existing connection was forcibly closed by the remote host> (caused by URLError(ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)))")); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

**Comment by NanaMizukiAnother7** [comment]
It might be your network issue. It works for me:
```
yt-dlp lsmwngrXyDc
[youtube] lsmwngrXyDc: Downloading webpage
[youtube] lsmwngrXyDc: Downloading android player API JSON
[youtube] lsmwngrXyDc: Downloading player c403842a
[youtube] lsmwngrXyDc: Downloading MPD manifest
[youtube] lsmwngrXyDc: Downloading MPD manifest

ERROR: Interrupted by user
```
Bye the way, can you please send your complete (verbose) log?

**Comment by Lesmiscore** [comment]
> (Running the command again got me the data, so I can't show the results of the `-vU` flag.)

We have to forgive sometimes...

**Comment by pukkandan** [comment]
* Can't reproduce
* The provided log looks like just a part of the warning message "nsig extraction failed ...". Even if they could not re-run the command, atleast the full (non-verbose) log could be provided
* It's most likely a network issue anyway. If even OP can't reproduce it, not much point in looking into it

**Comment by coletdjnz** [comment]
> @coletdjnz Should failure of signature (not nsig) extraction be fatal?

hmm yeah, probably should not be since we have the fallback.

**Comment by FredMSloniker** [comment]
I'm a novice at Python, and I don't understand why raising an exception for anything that isn't a bug in the program is a good thing. Can you explain?
Also, I'm using yt-dlp as part of a Python script that checks the videos in a playlist and keeps a record of their status; that way, if a video becomes unavailable, I can search for a suitable replacement. (This is especially important if someone makes a video private, as the script will make a note of the video's previous name, so I know what it was.) Should this error happen again, what information should the script record? Should I just have it always use -vU?

**Comment by pukkandan** [comment]
Note that **the root cause is most likely a network issue on your side**. In that case, the linked patch (or anything we can do) would not have prevented the error. However, the way the error was reported revealed an issue with the related error handling-code, which is what is fixed now

**Comment by FredMSloniker** [comment]
Yeah, I wasn't complaining about the failure; I was complaining about the way the failure was handled. I appreciate the fix!
