### ISSUE TITLE
[youtube] Community Post support

### ISSUE THREAD

**Issue by upintheairsheep** [yt-dlp/yt-dlp#3883]
### Checklist

- [X] I'm reporting a site feature request
- [X] I've verified that I'm running yt-dlp version **2022.05.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Southern California, USA

### Example URLs

https://www.youtube.com/c/TheGreatUnknownProductions/community
https://www.youtube.com/channel/UCgP9fheyDumxpk_35IgB3bw/community

### Description

Community posts are text, links to videos, images, polls, and comments on youtube. Although it may be out-of-scope, you should add support for downloading community posts, their metadata, and their comments. 

### Verbose log

```shell
not done yet
```

**Comment by Lesmiscore** [comment]
![image](https://user-images.githubusercontent.com/10355528/236827098-438cb3ac-4206-45ee-b830-77de0fdab13a.png)
