### ISSUE TITLE
[Likee] can't download some videos

### ISSUE THREAD

**Issue by Neurotoxin001** [yt-dlp/yt-dlp#3887]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.05.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Russia

### Description

When I copy link on video from Likee app (for iOS) I got link like this:
https://l.likee.video/v/qe6tdo
And yt-dlp can't download video from this link.

### Verbose log

```shell
D:\PROGRAMS\TikTok Download>!dl https://l.likee.video/v/qe6tdo -vU
[debug] Command-line config: ['https://l.likee.video/v/qe6tdo', '-vU']
[debug] Encodings: locale cp1251, fs utf-8, pref cp1251, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.05.18 [b14d523] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: ffmpeg -bsfs
[debug] exe versions: ffmpeg n4.4.2-1-g8e98dfc57f-20220507 (setts), ffprobe n4.4.2-1-g8e98dfc57f-20220507
[debug] Optional libraries: Cryptodome-3.14.1, brotli-1.0.9, certifi-2021.10.08, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
Latest version: 2022.05.18, Current version: 2022.05.18
yt-dlp is up to date (2022.05.18)
[debug] [generic] Extracting URL: https://l.likee.video/v/qe6tdo
[generic] qe6tdo: Requesting header
[redirect] Following redirect to https://likee.video/trending?postId=7087181733124333126&c=cp
[debug] [likee:user] Extracting URL: https://likee.video/trending?postId=7087181733124333126&c=cp
[likee:user] trending?postId=7087181733124333126&c=cp: Downloading webpage
ERROR: [likee:user] trending?postId=7087181733124333126&c=cp: Unable to extract user info; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 642, in extract
  File "yt_dlp\extractor\likee.py", line 190, in _real_extract
  File "yt_dlp\extractor\common.py", line 1226, in _search_regex
```
```

**Comment by pukkandan** [comment]
That link just seems to take me to the home page

**Comment by Neurotoxin001** [comment]
https://l.likee.video/v/RdsdCl
try this.
you can get links like this by copy link on video from Likee app (for iOS)

**Comment by shreateh** [comment]
Its a site bug, link only playable on ios app

**Comment by Neurotoxin001** [comment]
It playable in browser too

**Comment by shreateh** [comment]
for some likee videos not for all videos, such as this one : https://l.likee.video/v/v9UpVo
try on iphone and browser, it only works on likee app

**Comment by JailSeed** [comment]
Hi! The same problem for me, every link from Android app can be opened via browser, but yt-dlp crashes with "Unable to extract user info".
Examples:
https://l.likee.video/v/mKT3N0
https://l.likee.video/v/L0HgEZ
https://l.likee.video/v/BSLxYi
https://l.likee.video/v/W9YdU9
https://l.likee.video/v/ISYo5h

**Comment by AhmadAlwaeily** [comment]
WARNING: [generic] Falling back on generic information extractor
ERROR: Unsupported URL: https://likee.video/
