### ISSUE TITLE
Vista support of x86 Windows build

### ISSUE THREAD

**Issue by pukkandan** [yt-dlp/yt-dlp#390]
Originally reported by @Vangelis66 [here](https://github.com/yt-dlp/yt-dlp/commit/aa75e51f992c206b07ab4de592f11a871827bf4b#commitcomment-51904831)

There is an error in the "supported windows versions" given in https://www.python.org/downloads/windows
See: https://bugs.python.org/issue38704

The correct versions are:

WinXP SP3 => EOLed by 3.4.x
Vista SP2 => EOLed by 3.7.x
Win7 SP1 => EOLed by 3.8.x
3.9.x and higher require at least Win8.1

So we should build windows x86 using py3.7

**Comment by Vangelis66** [comment]
> Originally reported by @Vangelis66 [here](https://github.com/yt-dlp/yt-dlp/commit/aa75e51f992c206b07ab4de592f11a871827bf4b#commitcomment-51906089)
> (snipped)
> The correct versions are:

Being pedantic, my **original** report of **CPython** version support among **Windows** OSes 
was first posted in _this very repo_ last February 18th: 

https://github.com/yt-dlp/yt-dlp/pull/93#issuecomment-780914024 😉  😆 

If there's any interest, third party (non-PSF) installers/packages for **3.7.10** can be found [here](https://github.com/adang1345/PythonWindows/tree/master/3.7.10) 👍 ...

Thanks, kindest regards 😄 .

**Comment by pukkandan** [comment]
> Being pedantic, my original report of CPython version support among Windows OSes
was first posted in this very repo last February 18th:

Yes, I do remember that. However, it is only normal that when a comment and the official sources differ, I go by the official one. Hence why it is important for me to note down that it is in-fact the official source that is incorrect in this case

**Comment by Vangelis66** [comment]
> it is only normal that when a comment and the official sources differ, I go by the official one.

... Understood 😄 ; with me, I tend to stick to the "if it's coming straight from the horse's mouth" adage 😉 ; ie. **actual Vista user** vs the **PSF**, who never tested their binaries on Vista... 👎 

Additionally, you'll probably find that several other "official" documentations remain un-updated/flawed/misleading, case-in-point a recent "upstream" issue I had to comment on: 

https://github.com/ytdl-org/youtube-dl/issues/29222

Once again, many thanks for your coding efforts! 👍
