### ISSUE TITLE
Full YouTube links report no matches found in Zsh while they work fine in Bash

### ISSUE THREAD

**Issue by CosmicHeron** [yt-dlp/yt-dlp#3902]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.05.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

If running Zsh as shell full YouTube links do not appear to work. For instance using:
`yt-dlp https://www.youtube.com/watch?v=fq3abPnEEGE` will return `zsh: no matches found: https://www.youtube.com/watch?v=fq3abPnEEGE` but using a shortened `https://youtu.be/fq3abPnEEGE` will work fine. If Bash is run from within Zsh and then yt-dlp is used with the full link the video downloads fine so the issue must be with running yt-dlp from within Zsh.

This has been observed using the latest 2022.05.18 version of yt-dlp from the Community Arch Linux repository.

### Verbose log

```shell
% yt-dlp -uV https://www.youtube.com/watch?v=fq3abPnEEGE
zsh: no matches found: https://www.youtube.com/watch?v=fq3abPnEEGE
```

**Comment by SpraxDev** [comment]
This is not a bug with yt-dlp but how you use zsh – It already tells you with the `zsh:` at the beginning that it is the one reporting the error and not yt-dlp.

You have to put the URL inside `'` (`"` might work too) and escape whatever zsh is trying to do: `yt-dlp 'https://www.youtube.com/watch?v=fq3abPnEEGE'`

**Comment by CosmicHeron** [comment]
That was it, thanks!

**Comment by lnfel** [comment]
> This is not a bug with yt-dlp but how you use zsh – It already tells you with the `zsh:` at the beginning that it is the one reporting the error and not yt-dlp.
> 
> You have to put the URL inside `'` (`"` might work too) and escape whatever zsh is trying to do: `yt-dlp 'https://www.youtube.com/watch?v=fq3abPnEEGE'`

you just save me! Thank you!

**Comment by jtheletter** [comment]
Could the README and all other docs be updated to include quotation marks around URLs?

**Comment by bashonly** [comment]
> Could the README and all other docs be updated to include quotation marks around URLs?

Out-of-scope. The quotes are required by your shell, not yt-dlp. We can't start teaching people how to use their shells in the readme
