### ISSUE TITLE
Add support for Reddit Gallery URLs

### ISSUE THREAD

**Issue by SpraxDev** [yt-dlp/yt-dlp#3903]
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.05.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Example URLs

* https://www.reddit.com/r/Catloaf/comments/v087su/i_caught_the_loaf_mid_yawn/
* https://www.reddit.com/r/Catloaf/comments/uzzd8n/my_loafs/
* https://www.reddit.com/r/birb/comments/ux2a8i/i_made_stickers_of_my_pigeon_birbfriend_which_one/
* https://www.reddit.com/r/birb/comments/ujjoa4/birb/

### Description

Sometimes user upload multiple images in one post and yt-dlp seems to not support such posts while normal posts with one image or video download just fine.

### Verbose log

```shell
$ ./yt-dlp -vU https://www.reddit.com/r/Catloaf/comments/v087su/i_caught_the_loaf_mid_yawn/
[debug] Command-line config: ['-vU', 'https://www.reddit.com/r/Catloaf/comments/v087su/i_caught_the_loaf_mid_yawn/']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.05.18 [b14d52355] (zip)
[debug] Python version 3.9.2 (CPython 64bit) - Linux-5.10.0-13-amd64-x86_64-with-glibc2.31
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: ffmpeg -bsfs
[debug] exe versions: ffmpeg N-106766-gb67572c7c7 (fdk,setts), ffprobe N-106766-gb67572c7c7
[debug] Optional libraries: certifi-2020.06.20, pyxattr-0.7.2, secretstorage-3.3.1, sqlite3-2.6.0
[debug] Proxy map: {}
Latest version: 2022.05.18, Current version: 2022.05.18
yt-dlp is up to date (2022.05.18)
[debug] [Reddit] Extracting URL: https://www.reddit.com/r/Catloaf/comments/v087su/i_caught_the_loaf_mid_yawn/
[Reddit] v087su: Downloading JSON metadata
[debug] [generic] Extracting URL: https://www.reddit.com/gallery/v087su
[generic] v087su: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] v087su: Downloading webpage
[generic] v087su: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://www.reddit.com/gallery/v087su
Traceback (most recent call last):
  File "/home/christian/Subreddit-Downloader/./yt-dlp/yt_dlp/YoutubeDL.py", line 1395, in wrapper
    return func(self, *args, **kwargs)
  File "/home/christian/Subreddit-Downloader/./yt-dlp/yt_dlp/YoutubeDL.py", line 1465, in __extract_info
    ie_result = ie.extract(url)
  File "/home/christian/Subreddit-Downloader/./yt-dlp/yt_dlp/extractor/common.py", line 642, in extract
    ie_result = self._real_extract(url)
  File "/home/christian/Subreddit-Downloader/./yt-dlp/yt_dlp/extractor/generic.py", line 4031, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.reddit.com/gallery/v087su
```

**Comment by Lesmiscore** [comment]
We won't (actively) add support for downloading images, except storyboards (e.g. thumbnails shown above seekbar)
The same goes for #3904.

It maybe worth looking at https://github.com/mikf/gallery-dl for downloading them.
