### ISSUE TITLE
Imgur broken for non-video URLs

### ISSUE THREAD

**Issue by SpraxDev** [yt-dlp/yt-dlp#3904]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.05.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Description

I stumbled accros this issue when testing reddit downloads. Some content is hostet on external services like Imgur.
These links seem to not work with yt-dlp: `No sources found for video THE_ID. Maybe an image?`

URLs to test with:
* https://i.imgur.com/VBvekmb.jpg
* https://imgur.com/VBvekmb
* https://www.reddit.com/r/Catloaf/comments/uzt292/a_nicely_baked_kitty_loaf/

### Verbose log

```shell
$ ./yt-dlp -vU https://i.imgur.com/VBvekmb.jpg
[debug] Command-line config: ['-vU', 'https://i.imgur.com/VBvekmb.jpg']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.05.18 [b14d52355] (zip)
[debug] Python version 3.9.2 (CPython 64bit) - Linux-5.10.0-13-amd64-x86_64-with-glibc2.31
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: ffmpeg -bsfs
[debug] exe versions: ffmpeg N-106766-gb67572c7c7 (fdk,setts), ffprobe N-106766-gb67572c7c7
[debug] Optional libraries: certifi-2020.06.20, pyxattr-0.7.2, secretstorage-3.3.1, sqlite3-2.6.0
[debug] Proxy map: {}
Latest version: 2022.05.18, Current version: 2022.05.18
yt-dlp is up to date (2022.05.18)
[debug] [Imgur] Extracting URL: https://i.imgur.com/VBvekmb.jpg
[Imgur] VBvekmb: Downloading webpage
ERROR: [Imgur] VBvekmb: No sources found for video VBvekmb. Maybe an image?
  File "/home/christian/Subreddit-Downloader/./yt-dlp/yt_dlp/extractor/common.py", line 642, in extract
    ie_result = self._real_extract(url)
  File "/home/christian/Subreddit-Downloader/./yt-dlp/yt_dlp/extractor/imgur.py", line 48, in _real_extract
    raise ExtractorError(
```

**Comment by gamer191** [comment]
yt-dlp doesn't support images

**Comment by gamer191** [comment]
please use [Gallery-dl](https://github.com/mikf/gallery-dl) instead

**Comment by SpraxDev** [comment]
> yt-dlp doesn't support images. Please use [Gallery-dl](https://github.com/mikf/gallery-dl) instead

Oh sad, because for Reddit Posts having their media on reddit servers it downloads them without trouble, which is really nice

**Comment by gamer191** [comment]
wait, what did you mean by "non-gallery URLs"? The example urls you gave are definitely images, aren't they?

**Comment by SpraxDev** [comment]
Oh right, should have mentioned that:
For example https://imgur.com/gallery/ZihyziQ downloads just fine

**Comment by SpraxDev** [comment]
Example URL for an working image download outside of Imgur: https://www.reddit.com/r/Catloaf/comments/uzwjz9/tobys_loaf/

```shell
$ ./yt-dlp -vU https://www.reddit.com/r/Catloaf/comments/uzwjz9/tobys_loaf/
[debug] Command-line config: ['-vU', 'https://www.reddit.com/r/Catloaf/comments/uzwjz9/tobys_loaf/']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.05.18 [b14d52355] (zip)
[debug] Python version 3.9.2 (CPython 64bit) - Linux-5.10.0-13-amd64-x86_64-with-glibc2.31
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: ffmpeg -bsfs
[debug] exe versions: ffmpeg N-106766-gb67572c7c7 (fdk,setts), ffprobe N-106766-gb67572c7c7
[debug] Optional libraries: certifi-2020.06.20, pyxattr-0.7.2, secretstorage-3.3.1, sqlite3-2.6.0
[debug] Proxy map: {}
Latest version: 2022.05.18, Current version: 2022.05.18
yt-dlp is up to date (2022.05.18)
[debug] [Reddit] Extracting URL: https://www.reddit.com/r/Catloaf/comments/uzwjz9/tobys_loaf/
[Reddit] uzwjz9: Downloading JSON metadata
[debug] [generic] Extracting URL: https://i.redd.it/e65qeochba291.jpg
[generic] e65qeochba291: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] e65qeochba291: Downloading webpage
WARNING: [generic] URL could be a direct video link, returning it as such.
[debug] Default format spec: bestvideo*+bestaudio/best
[info] e65qeochba291: Downloading 1 format(s): 0
[debug] Invoking http downloader on "https://i.redd.it/e65qeochba291.jpg"
[download] Toby's loaf [e65qeochba291].jpg has already been downloaded
[download] 100% of 967.80KiB
```

**Comment by gamer191** [comment]
> Example URL for an working image download outside of Imgur: https://www.reddit.com/r/Catloaf/comments/uzwjz9/tobys_loaf/

That's strange. I must be wrong about yt-dlp not supporting images. Feel free to leave this issue open for now

**Comment by Lesmiscore** [comment]
We won't (actively) add support for downloading images, except storyboards (e.g. thumbnails shown above seekbar).

(see https://github.com/yt-dlp/yt-dlp/issues/3903#issuecomment-1140696149 )

**Comment by pukkandan** [comment]
> > Example URL for an working image download outside of Imgur: [reddit.com/r/Catloaf/comments/uzwjz9/tobys_loaf](https://www.reddit.com/r/Catloaf/comments/uzwjz9/tobys_loaf/)
> 
> That's strange. I must be wrong about yt-dlp not supporting images. Feel free to leave this issue open for now

Sometimes the code for downloading videos just happen to download images too. While this is technically a bug, I doubt anyone would ever complain about it, so no point in "fixing" it (ie, make the extractor throw error for images). Other than this, images are not supported
