### ISSUE TITLE
Could not send HEAD request

### ISSUE THREAD

**Issue by SillyBilly10** [yt-dlp/yt-dlp#3907]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.05.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

WARNING: [generic] Could not send HEAD request to https://www.youtube.com/watch\?v\=NiTpzE4s4j0: HTTP Error 404: Not Found
[generic] watch\?v\=NiTpzE4s4j0: Downloading webpage
ERROR: [generic] Unable to download webpage: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
 %

### Verbose log

```shell
WARNING: [generic] Could not send HEAD request to https://www.youtube.com/watch\?v\=NiTpzE4s4j0: HTTP Error 404: Not Found
[generic] watch\?v\=NiTpzE4s4j0: Downloading webpage
ERROR: [generic] Unable to download webpage: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
 %
```

**Comment by SillyBilly10** [comment]
nvm it fixed when I did the share link

**Comment by coletdjnz** [comment]
> https://www.youtube.com/watch\?v\=NiTpzE4s4j0

yeah not a valid link
