### ISSUE TITLE
Cellebrite 

### ISSUE THREAD

**Issue by upintheairsheep** [yt-dlp/yt-dlp#3908]
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.05.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Southern California, USA

### Example URLs

https://cellebrite.com/en/collect-data-from-android-devices-with-cellebrite-ufed/

### Description

Blog website

### Verbose log

```shell
Not yet
```

**Comment by HobbyistDev** [comment]
Duplicate / related #4014

**Comment by upintheairsheep** [comment]
Btw the reason why you got all these is GitHub flagged my account but they
finally unflagged it. I made another account to make issues.
