### ISSUE TITLE
[Question] --print TEMPLATE Confusion

### ISSUE THREAD

**Issue by fosam** [yt-dlp/yt-dlp#391]
## Checklist

- [X] I'm asking a question
- [X] I've looked through the README and FAQ for similar questions
- [X] I've searched the bugtracker for similar questions including closed ones

## Question

Hello!

I'm only trying to print the channel ID of a Youtube channel, but why is it printed so many times? **(32 times to be exact)** as you can see below:

The desired/expected output is only one item for the channel ID.

Maybe i'm not using this in the correct way?

<pre>
C:\Users\user><b>yt-dlp --print channel_id https://www.youtube.com/c/DNpro/</b> 
WARNING: [youtube:tab] A channel/user page was given. All the channel's videos will be downloaded. To download only the videos in the home page, add a "/featured" to the URL
UCM3VeyJKRr78wITQZhb1NRQ
UCM3VeyJKRr78wITQZhb1NRQ
UCM3VeyJKRr78wITQZhb1NRQ
UCM3VeyJKRr78wITQZhb1NRQ
UCM3VeyJKRr78wITQZhb1NRQ
UCM3VeyJKRr78wITQZhb1NRQ
UCM3VeyJKRr78wITQZhb1NRQ
UCM3VeyJKRr78wITQZhb1NRQ
UCM3VeyJKRr78wITQZhb1NRQ
UCM3VeyJKRr78wITQZhb1NRQ
UCM3VeyJKRr78wITQZhb1NRQ
UCM3VeyJKRr78wITQZhb1NRQ
UCM3VeyJKRr78wITQZhb1NRQ
UCM3VeyJKRr78wITQZhb1NRQ
UCM3VeyJKRr78wITQZhb1NRQ
UCM3VeyJKRr78wITQZhb1NRQ
UCM3VeyJKRr78wITQZhb1NRQ
UCM3VeyJKRr78wITQZhb1NRQ
UCM3VeyJKRr78wITQZhb1NRQ
UCM3VeyJKRr78wITQZhb1NRQ
UCM3VeyJKRr78wITQZhb1NRQ
UCM3VeyJKRr78wITQZhb1NRQ
UCM3VeyJKRr78wITQZhb1NRQ
UCM3VeyJKRr78wITQZhb1NRQ
UCM3VeyJKRr78wITQZhb1NRQ
UCM3VeyJKRr78wITQZhb1NRQ
UCM3VeyJKRr78wITQZhb1NRQ
UCM3VeyJKRr78wITQZhb1NRQ
UCM3VeyJKRr78wITQZhb1NRQ
UCM3VeyJKRr78wITQZhb1NRQ
UCM3VeyJKRr78wITQZhb1NRQ
UCM3VeyJKRr78wITQZhb1NRQ

C:\Users\user>
</pre>

**Comment by pukkandan** [comment]
`--print` prints **video** metadata. So your command is going through all the videos of that playlist and printing each of its `channel_id`. To print it only once, use `--playlist-end 1`

**Comment by fosam** [comment]
Indeed `--playlist-end 1` makes the print stop at one video only although with an extra command `(--playlist-end)`

Speaking of metadata, is it possible to include `channel_id` when using `--add-metadata`? i checked a video that was downloaded using `--add-metadata` but `channel_id` is not embedded in the video.

**Comment by pukkandan** [comment]
In what field of the video metadata would you embed it?

**Comment by fosam** [comment]
Something like the one marked at the bottom, it would be amazing if you could add something like that.

<pre>
General
Unique ID                   : 
Complete name               : 
Format                      : 
Format version              : 
File size                   : 
Duration                    : 
Overall bit rate            : 
Movie name                  : 
Description                 :  
Writing application         : 
Writing library             : 
Comment                     : 
ErrorDetectionType          : 
ARTIST                      : 
DATE                        : 
PURL                        : 
SYNOPSIS                    :  

<b>User/Channel ID</b>             :
</pre>

**Comment by pukkandan** [comment]
What metadata fields are allowed in a file depends on the container. See:
https://kdenlive.org/en/project/adding-meta-data-to-mp4-video/
https://wiki.multimedia.cx/index.php/FFmpeg_Metadata
https://kodi.wiki/view/Video_file_tagging


You can add the data to any arbitrary field with yt-dlp. Eg: `--parse-metadata "channel_id:%(meta_user_id)s"` will put the `channel_id` in the metadata field `user_id`. However, depending on your file format, this maynot actually do anything. Also, most tools will not be able to read the data from such arbitrary fields

**Comment by fosam** [comment]
I see, i will try it and let you know asap

**Comment by fosam** [comment]
Although it does not work for all file formats, in my test it worked for `MKV`, so `--parse-metadata` is definitely an accepted solution.

My last question is: is it possible to change the order of  the [metadata](https://github.com/yt-dlp/yt-dlp/issues/391#issuecomment-858047182)? like if i want to have `PURL` displayed at the top rather than the buttom for example?

**Comment by pukkandan** [comment]
No, there is no "order" for metadata. The order in which it is shown is decided by MediaInfo or whatever other tool you use to view it
