### ISSUE TITLE
youtube 

### ISSUE THREAD

**Issue by MyGoodbye** [yt-dlp/yt-dlp#3910]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

請問油管的訂閱頻道的視頻該怎麼下載呢?我己經訂閱了該視頻

**Comment by MyGoodbye** [comment]
我用了--cookies-from-browser這個,但是我不知以什麼方式穫得cookie,我用的editthiscookie導出的,但是我複制到txt文檔失敗了,希望能稍作一下指導,謝謝.

**Comment by coletdjnz** [comment]
`--cookies-from-browser browser` e.g. `--cookies-from-browser firefox`
Make sure you are logged in on the browser you specify. 

or export cookies and use `--cookies`:
https://github.com/ytdl-org/youtube-dl#how-do-i-pass-cookies-to-youtube-dl

**Comment by MyGoodbye** [comment]
謝謝

coletdev ***@***.***>於 2022年5月30日 週一，下午2:59寫道：

**Comment by MyGoodbye** [comment]
另外，用這個下載下一會會莫名的卡一下，導致整體下載時間比較久，這個是什麼原因呢？

陳峯 ***@***.***>於 2022年5月30日 週一，下午3:03寫道：

**Comment by gamer191** [comment]
> 另外，用這個下載下一會會莫名的卡一下，導致整體下載時間比較久，這個是什麼原因呢？

run it with `--verbose` and send the output

**Comment by pukkandan** [comment]
A general advice when asking for help online: Ask in English! Use google translate if needed. Sure, others can use a translator instead, but the harder you make it for someone to help you, the less likely you are to get help

**Comment by dirkf** [comment]
Also, if you're responding to someone's non-English issue, it can be helpful to post your (or that of G translate, etc) English version in case (a) the translation missed something that the OP might notice (b) other commenters who don't know the OP's language may be able to contribute (c) the exchange could be useful to future readers who don't know the OP's language.

**Comment by MyGoodbye** [comment]
this is the output，it just downloaded it for a while, and then the progress
below didn't move at all. After a while, it ran again.

gamer191 ***@***.***>於 2022年5月30日 週一，下午5:42寫道：

**Comment by gamer191** [comment]
@MyGoodbye can you please send a log of it happening?

**Comment by MyGoodbye** [comment]
How to check log,—verbose isn’t log?

gamer191 ***@***.***>於 2022年5月31日 週二，下午9:25寫道：

**Comment by pukkandan** [comment]
> this is the output，it just downloaded it for a while, and then the progress below didn't move at all. After a while, it ran again.

You haven't posted any log

**Comment by MyGoodbye** [comment]
Is this?
pukkandan ***@***.***>於 2022年5月31日 週二，下午10:29寫道：

**Comment by krichbanana** [comment]
> this is the output，it just downloaded it for a while, and then the progress below didn't move at all. After a while, it ran again.

If the download is stalling, try adding a short 3 second read timeout with `--socket-timeout 3`. If needed, you can increase the maximum number of retries to 30 retries (as an example) with `--retries 30`

There is still no log posted, GitHub may be accidentally cutting it out. If you are trying to post the verbose log as an email attachment, try copy-pasting the text into the email body directly, at the top of the email.

**Comment by MyGoodbye** [comment]
![61AF3A04-43C7-43DB-A2E6-24129BDED8DD](https://user-images.githubusercontent.com/44659435/171689186-a32dfffd-b766-4429-a13c-9b2d2d159be8.png)
now can you see it?

**Comment by gamer191** [comment]
> now can you see it?

yes. Unfortunately I don't know what's causing the issue, but someone else probably does!

**Comment by krichbanana** [comment]
> this is the output，it just downloaded it for a while, and then the progress below didn't move at all. After a while, it ran again.

(for reference: WinError 10054 = Connection Reset by Peer)

Try adding `--socket-timeout 3` to the command line. You cut off the top of the log, so I can't see what command you used, but it should make your command faster.

**Comment by MyGoodbye** [comment]
The command I use is

.\yt-dlp --cookies-from-browser chrome "
https://www.youtube.com/watch?v=izxvV9WzRqg&t=495s" -f 271+140
--socket-timeout 30

But the problem still exists.

krichbanana ***@***.***>於 2022年6月4日 週六，上午12:21寫道：

**Comment by pukkandan** [comment]
yt-dlp automatically retries and downloads the full video, right? What is the issue then?

**Comment by MyGoodbye** [comment]
My problem is that he will download it for a while and then won't download
it, although the download rate is displayed. After a while, the download
will start again, resulting in a longer overall download time.

pukkandan ***@***.***>於 2022年6月4日 週六，上午12:43寫道：

**Comment by pukkandan** [comment]
Approximately how long is the delay you are mentioning?

**Comment by MyGoodbye** [comment]
Download a few seconds and get stuck for a few seconds

pukkandan ***@***.***>於 2022年6月4日 週六，上午12:49寫道：

**Comment by pukkandan** [comment]
That is to be expected as long as the delay is never more than the number of seconds given in `--socket-timeout`

**Comment by MyGoodbye** [comment]
Is this can see some problems?
krichbanana ***@***.***>於 2022年6月3日 週五，上午1:27寫道：
