### ISSUE TITLE
An extractor error has occurred. (caused by KeyError('quality'));

### ISSUE THREAD

**Issue by hoffohoffo** [yt-dlp/yt-dlp#3919]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.05.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

The vevo URLs are not playable in the browser, so I was not able to check this. But this error appears, and I don't know how to handle it. Can you help out?

### Verbose log

```shell
./yt-dlp --verbose -F http://www.vevo.com/watch/ES1022200025
[debug] Command-line config: ['--verbose', '-F', 'http://www.vevo.com/watch/ES1022200025']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.05.18 [b14d52355] (zip)
[debug] Python version 3.9.12 (CPython 64bit) - macOS-12.4-x86_64-i386-64bit
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: avprobe -bsfs
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: avconv -bsfs
[debug] exe versions: rtmpdump 2.4
[debug] Optional libraries: sqlite3-2.6.0
[debug] Proxy map: {}
[debug] [Vevo] Extracting URL: http://www.vevo.com/watch/ES1022200025
[Vevo] Retrieving oauth token
[Vevo] ES1022200025: Downloading api video info
[Vevo] ES1022200025: Downloading video versions info
ERROR: ES1022200025: An extractor error has occurred. (caused by KeyError('quality')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/Users/michaelhornke/Development/youtube-song-downloader/youtube-dl/bin/./yt-dlp/yt_dlp/extractor/common.py", line 642, in extract
    ie_result = self._real_extract(url)
  File "/Users/michaelhornke/Development/youtube-song-downloader/youtube-dl/bin/./yt-dlp/yt_dlp/extractor/vevo.py", line 152, in _real_extract
    'format_id': 'http-%s-%s' % (version, video_version['quality']),
KeyError: 'quality'
```

**Comment by gklasen** [comment]
I have the same experience.
