### ISSUE TITLE
Remove extractor for Viafree and more sites

### ISSUE THREAD

**Issue by zettimetti** [yt-dlp/yt-dlp#3920]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.05.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Description

Hello.

I could not find anywhere else to report this

viafree.fi is redirecting to a payment service viaplay.fi

All these sites is redirecting to pluto.tv:
viafree.se
viafree.dk
viafree.no
viasat4play.no
tv3play.no
tv8play.se
tv6play.se
tv3play.se

tv6play.no is closed

### Verbose log

```shell
none
```

**Comment by dirkf** [comment]
>viafree.dk

Also tv3play.dk, tv10play.se

Extractors TVPlayIE, ViafreeIE in tvplay.py (same in yt-dl, but slightly different matching of URLs to extractors).

Baltic services aren't affected.

**Comment by gamer191** [comment]
https://play.tv3.lv/ still exists though
