### ISSUE TITLE
[ytmusic] parse Album Name as metadata

### ISSUE THREAD

**Issue by Rexadev** [yt-dlp/yt-dlp#3924]
### Checklist

- [X] I'm reporting a feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.05.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

example - `music.youtube.com/watch?v=J9BQRMBjUOY`
Album there is `Blizzard Of Ozz (40th Anniversary Expanded Edition)`
Now yt-dlp only copies if is available in description of www. subdomain version `www.youtube.com/watch?v=J9BQRMBjUOY`

**Comment by coletdjnz** [comment]
dup of https://github.com/yt-dlp/yt-dlp/issues/622

We currently extract all metadata from the equivalent youtube.com page.
