### ISSUE TITLE
www. and music. subdomains have different titles. Add option to select which title to use

### ISSUE THREAD

**Issue by Rexadev** [yt-dlp/yt-dlp#3926]
### Checklist

- [X] I'm reporting a feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.05.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

 example - 
`www.youtube.com/watch?v=f-e8-DUqt0I` is War Pigs and 
`music.youtube.com/watch?v=f-e8-DUqt0I` is War Pigs (2009 - Remaster). 
Add option to select which title to use
or to use whichever is longer.

**Comment by coletdjnz** [comment]
`--extractor-args youtube:player-client=web_music`
