### ISSUE TITLE
Embedding First Frame as thumbnail

### ISSUE THREAD

**Issue by someonenameguy** [yt-dlp/yt-dlp#3933]
### Checklist

- [X] I'm asking a question and **not** reporting a bug/feature request
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones

### Question

I am unsure how/if it is possible to embed the first frame of the video instate of the video thumbnail.

I know using ffmpeg might be able to do something like that but I looked around but couldn't find any answers to do it with yt-dlp without running a secound line.

I'm asking this because of youtube music thumbnails are low res. (Sorry For Any Spelling errors)

**Comment by pukkandan** [comment]
> I know using ffmpeg might be able to do something like that but I looked around but couldn't find any answers to do it with yt-dlp without running a secound line.

How do you do this with ffmpeg?

**Comment by flashdagger** [comment]
> > I know using ffmpeg might be able to do something like that but I looked around but couldn't find any answers to do it with yt-dlp without running a secound line.
> 
> How do you do this with ffmpeg?

` ffmpeg -i <url> -map 0:a:0 -map 0:v:0 -id3v2_version 3 -metadata:s:v comment="Cover (Front)" out.mp3`

**Comment by pukkandan** [comment]
Then the equivalent yt-dlp command would be

    yt-dlp --use-postprocessor FFmpegCopyStream --ppa "copystream:-id3v2_version 3 -metadata:s:v comment=Cover\ (Front)" "URL"

**Comment by someonenameguy** [comment]
Noted Thank You.

**Comment by someonenameguy** [comment]
Changed title so other can find this issue easier when searching.

**Comment by BhaturaGuy** [comment]
Can you help me here I can't seem to work it out.

```
-x
--audio-format mp3
--audio-quality 320K
--format "bestvideo+bestaudio/best"
--concurrent-fragments 50
--sponsorblock-mark all
--embed-metadata
--use-postprocessor FFmpegCopyStream --ppa "copystream:-id3v2_version 3 -metadata:s:v comment=Cover\ (Front)" "URL"
--embed-thumbnail
-o "D:\Downloads\%(artist,uploader,channel)s\%(artist,uploader,channel)s - %(track,title)s.%(ext)s"
```

**Comment by someonenameguy** [comment]
> Can you help me here I can't seem to work it out.
> 
> ```
> -x
> --audio-format mp3
> --audio-quality 320K
> --format "bestvideo+bestaudio/best"
> --concurrent-fragments 50
> --sponsorblock-mark all
> --embed-metadata
> --use-postprocessor FFmpegCopyStream --ppa "copystream:-id3v2_version 3 -metadata:s:v comment=Cover\ (Front)"
> --embed-thumbnail
> -o "D:\Downloads\%(artist,uploader,channel)s\%(artist,uploader,channel)s - %(track,title)s.%(ext)s"
> ```

I don't think 50 concurrent fragments is needed for one audio file.
I used:
```
yt-dlp -N 2 --windows-filenames --check-formats --no-write-subs --no-write-thumbnail -f "ba" -o "%(title)s-%(artist)s[%(id)s.%(ext)s" --use-postprocessor FFmpegCopyStream --ppa "copystream:-id3v2_version 3 -metadata:s:v comment=Cover\ (Front) [URL]"
```
You could modify it so it matches your code more closer.

*I no longer use yt-dlp to embed metadata and cover images, so will not work if anything has changed that might have broken it but it seem to work fine. I use a second program to add coverart and metadata as it has higher res coverart and more detailed metadata.*

**Comment by BhaturaGuy** [comment]
> I use a second program to add coverart and metadata as it has higher res coverart and more detailed metadata.


Might I ask what program is that? Since it is better, also pls state if it can add metadata and coverart in batch or manually one-by-one.

**Comment by someonenameguy** [comment]
> Might I ask what program is that?

I use a app on my android phone called '[AutomaTag](https://play.google.com/store/apps/details?id=com.fillobotto.mp3tagger)'. 

**It can do batch but it's manual(*You can select multiple files but it will show you them one by one for you check and press next*).**

The Full auto batch is Paid tho... I don't use the full auto because it can misidentify songs as it uses the title and/or the metadata in the file to try to find the right one(*It does shows more than one option for you to pick.*)
