### ISSUE TITLE
kenh14

### ISSUE THREAD

**Issue by zeref-dragneel** [yt-dlp/yt-dlp#3937]
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.05.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Vietnam

### Example URLs

Video: https://video.kenh14.vn/video-mo-hop-iphone-14-pro-max-nguon-unbox-therapy-316173.chn
Playlist: https://video.kenh14.vn/playlist/tran-tinh-naked-love-mua-2-71.chn

### Description

Video

### Verbose log

```shell
[debug] Command-line config: ['-vU', 'https://video.kenh14.vn/video-mo-hop-iphone-14-pro-max-nguon-unbox-therapy-316173.chn']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.05.18 [b14d523] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19042-SP0
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: avprobe -bsfs
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: avconv -bsfs
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.14.1, brotli-1.0.9, certifi-2021.10.08, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
Latest version: 2022.05.18, Current version: 2022.05.18
yt-dlp is up to date (2022.05.18)
[debug] [generic] Extracting URL: https://video.kenh14.vn/video-mo-hop-iphone-14-pro-max-nguon-unbox-therapy-316173.chn
[generic] video-mo-hop-iphone-14-pro-max-nguon-unbox-therapy-316173: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] video-mo-hop-iphone-14-pro-max-nguon-unbox-therapy-316173: Downloading webpage
[generic] video-mo-hop-iphone-14-pro-max-nguon-unbox-therapy-316173: Extracting information
[debug] Looking for video embeds
[debug] Identified a JW Player JS loader
[debug] Default format spec: best/bestvideo+bestaudio
[info] P3Q5XYacz5E-1652782450168278389637: Downloading 1 format(s): 0
[debug] Invoking http downloader on "https://hls.mediacdn.vn//203336854389633024/2022/5/17/P3Q5XYacz5E-1652782450168278389637.mp4"
ERROR: unable to download video data: HTTP Error 404: NOT FOUND
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 3130, in process_info
  File "yt_dlp\YoutubeDL.py", line 2838, in dl
  File "yt_dlp\downloader\common.py", line 445, in download
  File "yt_dlp\downloader\http.py", line 373, in real_download
  File "yt_dlp\downloader\http.py", line 130, in establish_connection
  File "yt_dlp\YoutubeDL.py", line 3596, in urlopen
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: NOT FOUND
```

**Comment by HobbyistDev** [comment]
Note to Dev:
The video file is in `div ... data-vid-id=<video_id> data-vid=<video_url>`, the `<video_url> need to prepended with `https` and then it will download the video correctly. More video can obtained in `https://<video_url>.json`.
