### ISSUE TITLE
ERROR: [Instagram] CdbWgSjAPdT: Unable to extract video url (using authentication)

### ISSUE THREAD

**Issue by tucomel** [yt-dlp/yt-dlp#3938]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.05.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

Error while trying to download any instagram video while using cookies.
While try to download public videos without cookies works fine, but even this public videos cause error while try to download with cookies (my default option - alfred workflow)
cookies generated by getcookies chrome extension

**edit**
Im tested right now using .netrc file and -u and -p parameters and got the same error (unable to extract url)

### Verbose log

```shell
arthur@blackpower ~ % yt-dlp https://www.instagram.com/p/CdbWgSjAPdT/ --cookies ~/instagram.com_cookies.txt --verbose
[debug] Command-line config: ['https://www.instagram.com/p/CdbWgSjAPdT/', '--cookies', '/Users/arthur/instagram.com_cookies.txt', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.05.18 [b14d52355]
[debug] Python version 3.10.4 (CPython 64bit) - macOS-11.3-x86_64-i386-64bit
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: ffmpeg -bsfs
[debug] exe versions: ffmpeg 5.0.1 (setts), ffprobe 5.0.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.14.1, brotli-1.0.9, certifi-2021.10.08, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] [Instagram] Extracting URL: https://www.instagram.com/p/CdbWgSjAPdT/
[Instagram] CdbWgSjAPdT: Downloading webpage
WARNING: [Instagram] unable to extract username; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
ERROR: [Instagram] CdbWgSjAPdT: Unable to extract video url; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/usr/local/Cellar/yt-dlp/2022.5.18/libexec/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 642, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/Cellar/yt-dlp/2022.5.18/libexec/lib/python3.10/site-packages/yt_dlp/extractor/instagram.py", line 415, in _real_extract
    video_url = self._og_search_video_url(webpage, secure=False)
  File "/usr/local/Cellar/yt-dlp/2022.5.18/libexec/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 1340, in _og_search_video_url
    return self._html_search_regex(regexes, html, name, **kargs)
  File "/usr/local/Cellar/yt-dlp/2022.5.18/libexec/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 1235, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/usr/local/Cellar/yt-dlp/2022.5.18/libexec/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 1226, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
```

**Comment by tucomel** [comment]
I closed the other issue, since it wasn't solved and the description here brings more detailed info about authentication error, im not spamming, I just commented twice, with a difference of MONTHS between comments

**Comment by tucomel** [comment]
> Don't spam! Duplicate of #3077

I closed the other issue, since it wasn't solved and the description here brings more detailed info about authentication error, im not spamming, I just commented twice, with a difference of MONTHS between comments

**Comment by pukkandan** [comment]
> I closed the other issue, since it wasn't solved and the description here brings more detailed info about authentication error,

That is not a reason to open duplicate issues!
