### ISSUE TITLE
Add Metadata recorded_date field.

### ISSUE THREAD

**Issue by trumblejoe** [yt-dlp/yt-dlp#3956]
### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.05.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

Recorded_date is a fairly common metadata field that isn't being picked up by yt-dlp. It has many uses for accurate recordkeeping over upload_date. Often times something will be listed as occurring on the start time of an event but with a longer event the duration will carry it into a new days date, which can then lead to upload_date being one day off. It sounds simple but once you start seeing it, you see it everywhere.

**Comment by pukkandan** [comment]
Give examples
