### ISSUE TITLE
[Feature Request] --embed-comments

### ISSUE THREAD

**Issue by MrRawes** [yt-dlp/yt-dlp#3958]
### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.05.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

--embed-comments would embed comments into a mkv/mka file without getting written to a .info.json file

**Comment by pukkandan** [comment]
embed how?

**Comment by MrRawes** [comment]
this would embed the json comments data to a mkv/mka file without writing to a seperate .info.json file
