### ISSUE TITLE
Request for traffic camera site

### ISSUE THREAD

**Issue by johny1** [yt-dlp/yt-dlp#3965]
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.05.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Anywhere

### Example URLs

https://49-d2.divas.cloud/CHAN-8228/CHAN-8228_1.stream/playlist.m3u8

### Description

Hello. I'm trying to download live traffic camera streams from this website,
https://fl511.com/cctv

Click on "Show Video" below the thumbnail to start playing the live video for any camera. In my example below, I used the third video on the page. After I did this, I grabbed the playlist m3u8 using Chrome. Note, the link contained my IP address, so I removed that part here and in the verbose log.

Here is that link: https://49-d2.divas.cloud/CHAN-8228/CHAN-8228_1.stream/playlist.m3u8?(IP redacted)&vdswztokenhash=6FmNXfNFHtVL2_lRVfS981tbXvb8a5NoLbUc6TwG2Yg=

I also tried downloading it by removing the last part of the link as below, but still experienced the same errors in the verbose log,
https://49-d2.divas.cloud/CHAN-8228/CHAN-8228_1.stream/playlist.m3u8

Thanks for any help.

### Verbose log

```shell
[debug] Command-line config: ['-vU', 'https://49-d2.divas.cloud/CHAN-8228/CHAN-8228_1.stream/playlist.m3u8?(IP REDACTED)']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.05.18 [b14d523] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: avprobe -bsfs
[debug] Checking exe version: ffmpeg -bsfs
[debug] exe versions: ffmpeg 4.4.1-essentials_build-www.gyan.dev (setts)
[debug] Optional libraries: Cryptodome-3.14.1, brotli-1.0.9, certifi-2021.10.08, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
Latest version: 2022.05.18, Current version: 2022.05.18
yt-dlp is up to date (2022.05.18)
[debug] [generic] Extracting URL: https://49-d2.divas.cloud/CHAN-8228/CHAN-8228_1.stream/playlist.m3u8?(IP REDACTED)
[generic] playlist.m3u8?(IP REDACTED): Requesting header
WARNING: [generic] Could not send HEAD request to https://49-d2.divas.cloud/CHAN-8228/CHAN-8228_1.stream/playlist.m3u8?(IP REDACTED): <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)>
[generic] playlist.m3u8?(IP REDACTED): Downloading webpage
ERROR: [generic] Unable to download webpage: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)> (caused by URLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))
  File "yt_dlp\extractor\common.py", line 642, in extract
  File "yt_dlp\extractor\generic.py", line 2737, in _real_extract
  File "yt_dlp\extractor\common.py", line 786, in _request_webpage

  File "urllib\request.py", line 1354, in do_open
  File "http\client.py", line 1252, in request
  File "http\client.py", line 1298, in _send_request
  File "http\client.py", line 1247, in endheaders
  File "http\client.py", line 1007, in _send_output
  File "http\client.py", line 947, in send
  File "http\client.py", line 1421, in connect
  File "ssl.py", line 500, in wrap_socket
  File "ssl.py", line 1040, in _create
  File "ssl.py", line 1309, in do_handshake
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\extractor\common.py", line 768, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 3596, in urlopen
  File "urllib\request.py", line 525, in open
  File "urllib\request.py", line 542, in _open
  File "urllib\request.py", line 502, in _call_chain
  File "yt_dlp\utils.py", line 1419, in https_open
  File "urllib\request.py", line 1357, in do_open
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)>

'vdswztokenhash' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by pukkandan** [comment]
1. Quote the URL
2. Try `--no-check-certificate`

**Comment by johny1** [comment]
> 1. Quote the URL
> 
>     2. Try `--no-check-certificate`

Thanks pukkandan. I added quotes to the original full URL and the no check certificate option. However, it only downloads a 1 MB file that is 22 seconds of the video. I tried some different camera links on that page and observed the same thing. I'm wondering why that is, I don't see any other playlist file

**Comment by pukkandan** [comment]
Add `--downloader ffmpeg` too

**Comment by johny1** [comment]
> Add `--downloader ffmpeg` too

Thank you. Adding this option fixed it. It's downloading the entire stream now.
