### ISSUE TITLE
Question: robots.txt compliance

### ISSUE THREAD

**Issue by Lucabenj** [yt-dlp/yt-dlp#3969]
### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Question

Is the software compatible with robots.txt rules?

**Comment by MinePlayersPE** [comment]
If compatible means forbidding disallowed paths from being extracted by yt-dlp:
Why should it look at robots.txt in the first place, let alone obey it over what the user requested?

**Comment by flashdagger** [comment]
I just tested it on youmaker.com and it seems to work. 😛

```
$ curl https://www.youmaker.com/robots.txt
# https://www.robotstxt.org/robotstxt.html
User-agent: *
Disallow: /search
Disallow: /ads/

User-Agent: omgilibot
Disallow: /

User-Agent: omgili
Disallow: /

Sitemap: https://www.youmaker.com/sitemap/sitemap.xml
```

```
$ yt-dlp https://youmaker.com/search -s
[generic] search: Requesting header
WARNING: [generic] Could not send HEAD request to https://youmaker.com/search: HTTP Error 404: Not Found
[generic] search: Downloading webpage
WARNING: [generic] Falling back on generic information extractor.
[generic] search: Extracting information
ERROR: Unsupported URL: https://youmaker.com/search
```

**Comment by pukkandan** [comment]
What does robots.txt have anything to do with video downloading??

**Comment by ischmidt20** [comment]
Many people use yt-dlp as a bot to extract data from a website? Just that in these specific cases, the data are videos.

I don't think a robots.txt is legally binding or anything but it is not like it is completely unrelated to yt-dlp

**Comment by pukkandan** [comment]
robots.txt is applicable only for crawlers. yt-dlp is not a crawler, and only processes the URLs that are passed to it by the user...
