### ISSUE TITLE
Add more powerful thumbnail conversion options

### ISSUE THREAD

**Issue by Oondanomala** [yt-dlp/yt-dlp#3970]
### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.05.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

`--convert-thumbnails` should accept more advanced parameters such as "webp>png/jpg" to convert webp to png and anything else to jpeg, like `--remux-video` does.

This would be helpful if for example I don't want webp files but don't want to convert jpeg to png (as that would be space inefficient).

**Comment by lionderful** [comment]
hi,  anyone help me ? what is the right arguments for ThumbnailsConvertor in Postprocessors ? 
'postprocessors': [{  # KeyError: 'ThumbnailsConvertorPP'
        'key': 'ThumbnailsConvertor',
        'preferredcodec': 'jpg',
    }]

**Comment by pukkandan** [comment]
https://github.com/yt-dlp/yt-dlp/blob/5ec1b6b71689d2f0cbdcd2b6c4dd861fb2fcf911/yt_dlp/__init__.py#L534-L535
