### ISSUE TITLE
Instagram broken

### ISSUE THREAD

**Issue by kclauhk** [yt-dlp/yt-dlp#3972]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.05.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Description

It seems that videos on Instagram raise error (same result from any video tried)

### Verbose log

```shell
[debug] Command-line config: ['-u', 'PRIVATE', '-p', 'PRIVATE', '-F', 'https://www.instagram.com/p/xxxxxxxxxxx/', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.05.18 [b14d52355]
[debug] Python version 3.8.12 (CPython 64bit) - Linux-4.4.180+-x86_64-with-glibc2.2.5
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: avprobe -bsfs
[debug] Checking exe version: ffmpeg -bsfs
[debug] exe versions: ffmpeg 4.1.8
[debug] Optional libraries: Cryptodome-3.14.1, brotli-1.0.9, certifi-2022.05.18, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[Instagram] Downloading login webpage
[Instagram] Logging in
[debug] [Instagram] Extracting URL: https://www.instagram.com/p/xxxxxxxxxxx/
[Instagram] xxxxxxxxxxx: Downloading webpage
WARNING: [Instagram] unable to extract username; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
ERROR: [Instagram] CeLlL_xARkv: Unable to extract video url; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/volume1/web/bin/yt-dlp/yt_dlp/extractor/common.py", line 642, in extract
    ie_result = self._real_extract(url)
  File "/volume1/web/bin/yt-dlp/yt_dlp/extractor/instagram.py", line 415, in _real_extract
    video_url = self._og_search_video_url(webpage, secure=False)
  File "/volume1/web/bin/yt-dlp/yt_dlp/extractor/common.py", line 1340, in _og_search_video_url
    return self._html_search_regex(regexes, html, name, **kargs)
  File "/volume1/web/bin/yt-dlp/yt_dlp/extractor/common.py", line 1235, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/volume1/web/bin/yt-dlp/yt_dlp/extractor/common.py", line 1226, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
```

**Comment by MinePlayersPE** [comment]
https://github.com/yt-dlp/yt-dlp/issues?q=is%3Aissue+is%3Aopen+instagram
