### ISSUE TITLE
BiliBili cannot download mp4

### ISSUE THREAD

**Issue by lcc-666** [yt-dlp/yt-dlp#3973]
### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.05.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

When I am downloading BiliBili videos using yt-dlp（windown os），I can only get one m4s file.I want to get a complete MP4 file
for example，
url：https://www.bilibili.com/video/BV1iL4y1K71o

### Verbose log

```shell
(spider) D:\learn\video>yt-dlp https://www.bilibili.com/video/BV1iL4y1K71o
[BiliBili] 1iL4y1K71o: Grabbing original ID via API
[BiliBili] 854718080: Downloading webpage
[BiliBili] 854718080: Extracting videos in anthology
[BiliBili] Downloading anthology 854718080 - add --no-playlist to just download video
[download] Downloading playlist: 《斗破苍穹后传》天邪神破阵，萧炎·林动救场.
[BiliBili] playlist 《斗破苍穹后传》天邪神破阵，萧炎·林动救场.: Downloading 1 videos
[download] Downloading video 1 of 1
[BiliBili] 1iL4y1K71o: Grabbing original ID via API
[BiliBili] 854718080: Downloading webpage
[BiliBili] 854718080: Extracting videos in anthology
[BiliBili] 854718080: Downloading tags
[info] 854718080_part1: Downloading 1 format(s): 32
[download] Destination: 《斗破苍穹后传》天邪神破阵，萧炎·林动救场. [854718080_part1].m4s
[download] 100% of 2.69MiB in 00:00
[download] Finished downloading playlist: 《斗破苍穹后传》天邪神破阵，萧炎·林动救场.
```

**Comment by gamer191** [comment]
please run `yt-dlp https://www.bilibili.com/video/BV1iL4y1K71o --verbose` and send a log of the result

**Comment by lcc-666** [comment]
(spider) D:\learn\enviroment\spider\Scripts>yt-dlp https://www.bilibili.com/video/BV1iL4y1K71o --verbose
[debug] Command-line config: ['https://www.bilibili.com/video/BV1iL4y1K71o', '--verbose']
[debug] Encodings: locale cp936, fs utf-8, pref cp936, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.05.18 [b14d52355]
[debug] Python version 3.7.9 (CPython 32bit) - Windows-10-10.0.22499-SP0
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: avprobe -bsfs
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: avconv -bsfs
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.14.1, brotli-1.0.9, certifi-2021.10.08, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] [BiliBili] Extracting URL: https://www.bilibili.com/video/BV1iL4y1K71o
[BiliBili] 1iL4y1K71o: Grabbing original ID via API
[BiliBili] 854718080: Downloading webpage
[BiliBili] 854718080: Extracting videos in anthology
[BiliBili] Downloading anthology 854718080 - add --no-playlist to just download video
[download] Downloading playlist: 《斗破苍穹后传》天邪神破阵，萧炎·林动救场.
[BiliBili] playlist 《斗破苍穹后传》天邪神破阵，萧炎·林动救场.: Downloading 1 videos
[download] Downloading video 1 of 1
[debug] [BiliBili] Extracting URL: https://www.bilibili.com/video/BV1iL4y1K71o?p=1
[BiliBili] 1iL4y1K71o: Grabbing original ID via API
[BiliBili] 854718080: Downloading webpage
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[BiliBili] 854718080: Extracting videos in anthology
[BiliBili] 854718080: Downloading tags
[debug] Default format spec: best/bestvideo+bestaudio
[info] 854718080_part1: Downloading 1 format(s): 32
[debug] Invoking http downloader on "https://upos-sz-mirrorhwb.bilivideo.com/upgcxcode/41/30/738873041/738873041_nb2-1-30232.m4s?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0MvXg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M=&uipk=5&nbs=1&deadline=1654659067&gen=playurlv2&os=hwbbv&oi=0&trid=0fd3013cc7b64b01a4debbf9bfd9b457u&mid=0&platform=pc&upsig=ca92f8fd0ee80f376f0ddf6d0a612c1d&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,mid,platform&bvc=vod&nettype=0&orderid=2,3&agrr=0&bw=16611&logo=40000000"
[debug] File locking is not supported on this platform. Proceeding without locking
[download] Destination: 《斗破苍穹后传》天邪神破阵，萧炎·林动救场. [854718080_part1].m4s
[download] 100% of 2.69MiB in 00:00
[download] Finished downloading playlist: 《斗破苍穹后传》天邪神破阵，萧炎·林动救场.

**Comment by lcc-666** [comment]
(spider) D:\learn\enviroment\spider\Scripts>yt-dlp https://www.bilibili.com/video/BV1iL4y1K71o --verbose
[debug] Command-line config: ['https://www.bilibili.com/video/BV1iL4y1K71o', '--verbose']
[debug] Encodings: locale cp936, fs utf-8, pref cp936, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.05.18 [b14d52355]
[debug] Python version 3.7.9 (CPython 32bit) - Windows-10-10.0.22499-SP0
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: avprobe -bsfs
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: avconv -bsfs
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.14.1, brotli-1.0.9, certifi-2021.10.08, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] [BiliBili] Extracting URL: https://www.bilibili.com/video/BV1iL4y1K71o
[BiliBili] 1iL4y1K71o: Grabbing original ID via API
[BiliBili] 854718080: Downloading webpage
[BiliBili] 854718080: Extracting videos in anthology
[BiliBili] Downloading anthology 854718080 - add --no-playlist to just download video
[download] Downloading playlist: 《斗破苍穹后传》天邪神破阵，萧炎·林动救场.
[BiliBili] playlist 《斗破苍穹后传》天邪神破阵，萧炎·林动救场.: Downloading 1 videos
[download] Downloading video 1 of 1
[debug] [BiliBili] Extracting URL: https://www.bilibili.com/video/BV1iL4y1K71o?p=1
[BiliBili] 1iL4y1K71o: Grabbing original ID via API
[BiliBili] 854718080: Downloading webpage
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[BiliBili] 854718080: Extracting videos in anthology
[BiliBili] 854718080: Downloading tags
[debug] Default format spec: best/bestvideo+bestaudio
[info] 854718080_part1: Downloading 1 format(s): 32
[debug] Invoking http downloader on "https://upos-sz-mirrorhwb.bilivideo.com/upgcxcode/41/30/738873041/738873041_nb2-1-30232.m4s?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0MvXg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M=&uipk=5&nbs=1&deadline=1654659067&gen=playurlv2&os=hwbbv&oi=0&trid=0fd3013cc7b64b01a4debbf9bfd9b457u&mid=0&platform=pc&upsig=ca92f8fd0ee80f376f0ddf6d0a612c1d&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,mid,platform&bvc=vod&nettype=0&orderid=2,3&agrr=0&bw=16611&logo=40000000"
[debug] File locking is not supported on this platform. Proceeding without locking
[download] Destination: 《斗破苍穹后传》天邪神破阵，萧炎·林动救场. [854718080_part1].m4s
[download] 100% of 2.69MiB in 00:00
[download] Finished downloading playlist: 《斗破苍穹后传》天邪神破阵，萧炎·林动救场.

**Comment by pukkandan** [comment]
```
❯ yt-dlp https://www.bilibili.com/video/BV1iL4y1K71o
[BiliBili] 1iL4y1K71o: Grabbing original ID via API
[BiliBili] 854718080: Downloading webpage
[BiliBili] 854718080: Extracting videos in anthology
[BiliBili] Downloading anthology 854718080 - add --no-playlist to just download video
[download] Downloading playlist: 《斗破苍穹后传》天邪神破阵，萧炎·林动救场.
[BiliBili] Playlist 《斗破苍穹后传》天邪神破阵，萧炎·林动救场.: Downloading 1 videos of 1
[download] Downloading video 1 of 1
[BiliBili] 1iL4y1K71o: Grabbing original ID via API
[BiliBili] 854718080: Downloading webpage
[BiliBili] 854718080: Extracting videos in anthology
[BiliBili] 854718080: Downloading tags
[info] 854718080_part1: Downloading 1 format(s): 14+2
[download] Destination: 《斗破苍穹后传》天邪神破阵，萧炎·林动救场. [854718080_part1].f14.mp4
[download]  21.5% of 32.72MiB at    3.08MiB/s ETA 00:08Exception ignored in: <_io.FileIO name='《斗破苍穹后传》天邪神破阵，萧炎·林动救场. [854718080_part1].f14.mp4.part' mode='wb' closefd=True>
ResourceWarning: unclosed file <_io.BufferedWriter name='《斗破苍穹后传》天邪神破阵，萧炎·林动救场. [854718080_part1].f14.mp4.part'>

ERROR: Interrupted by user
```

**Comment by pukkandan** [comment]
@Icc can you show output of `yt-dlp https://www.bilibili.com/video/BV1iL4y1K71o -vF`

**Comment by pukkandan** [comment]
You can see the mp4 formats. Just install ffmpeg and download again

**Comment by lcc-666** [comment]
I fix this question use "formats:worst" or merge bestvideo+bestaudio

**Comment by icc** [comment]
@pukkandan Good work!
