### ISSUE TITLE
problem with asii name

### ISSUE THREAD

**Issue by 104979058** [yt-dlp/yt-dlp#3978]
### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Question

yt: https://www.youtube.com/watch?v=fsG1XaZEa78
title : 【女團門面接力唱～忠羽、若潼、Kimi甜美合唱「喜歡你」！好聽到建議組團了！？】綜藝大熱門  精華

 --restrict-filenames
----------
D:\down\Kimi_137.mp4
Kimi_137.mp4 ?? Names only have letters?

### Verbose log

```shell
yt-dlp.exe --restrict-filenames --no-playlist --format 137,140 --proxy "127.0.0.1:4780" --continue --output "D:\down\%(fulltitle)s_%(format_id)s.%(ext)s" "https://www.youtube.com/watch?v=DIE7Bkjcc7s"
[youtube] DIE7Bkjcc7s: Downloading webpage
[youtube] DIE7Bkjcc7s: Downloading android player API JSON
[info] DIE7Bkjcc7s: Downloading 2 format(s): 137, 140
[download] Resuming download at byte 132837367
[download] Destination: D:\down\Kimi_137.mp4
[download]  56.8% of 234.76MiB at  2.88MiB/s ETA 00:35
```

**Comment by pukkandan** [comment]
what is your question??

**Comment by 104979058** [comment]
> what is your question??

Chinese also supports asii encoding, why is there no Chinese in the title (%(fulltitle)s)?

**Comment by pukkandan** [comment]
Because you used `--restrict-filenames`!
```
    --restrict-filenames            Restrict filenames to only ASCII characters,
                                    and avoid "&" and spaces in filenames
```

**Comment by 104979058** [comment]
> 
If restrict-filenames is not used, if the title includes unicode characters, it will cause some channels to fail to obtain the correct download file name.

**Comment by pukkandan** [comment]
> If restrict-filenames is not used, if the title includes unicode characters, it will cause some channels to fail to obtain the correct download file name.

It will not "fail to get the right title", but either your filesystem or console may not be set to use correct encoding to handle this. You will need to fix that from your side. Since you dont show the error (+verbose), I have no idea where the exact issue even is

> Chinese also supports asii encoding, 

The chinese characters are non-ASCII

**Comment by 104979058** [comment]
> 
yt-dlp.exe --no-playlist --format 137,140 --proxy "127.0.0.1:4780" --continue --output "D:\down\%(fulltitle)s_%(format_id)s.%(ext)s" "https://www.youtube.com/watch?v=fsG1XaZEa78"

https://www.youtube.com/watch?v=fsG1XaZEa78: SQL Index |¦| Indexes in SQL |¦| Database Index

The title has special characters: |¦| , the file name output by the interface is inconsistent with the actual downloaded file name.
![2222222](https://user-images.githubusercontent.com/28974521/172093816-8f77a271-6f6d-4bac-9b61-ac465bda0ee8.png)

**Comment by pukkandan** [comment]
The `form 1` "interface" isn't part of yt-dlp. You look to be using some third party program. Everything looks correct in the console

**Comment by 104979058** [comment]
> ‎“接口”不是yt-dlp的一部分。您希望使用某些第三方程序。控制台中一切看起来都正确‎`form 1`
The third-party cmd channel does not handle non-asii characters very well now, and the restrict-filenames that comes with yt-dlp, according to the explanation, are for compatible encoding output, but I don't understand why all Chinese are filtered out?
--restrict-filenames https://www.youtube.com/watch?=fsG1XaZEa78 Added, perfect.
But when I change the link of the Chinese title, there is a problem again. There is no Chinese at all,

**Comment by pukkandan** [comment]
Because Chinese characters are NOT ASCII !!

**Comment by 104979058** [comment]
> Because Chinese characters are NOT ASCII !!
Is there a parameter to remove special characters in the title? Make it output standard utf8 encoded characters

**Comment by pukkandan** [comment]
You can use `--replace-in-metadata` to remove the specific characters you want

**Comment by 104979058** [comment]
> You can use `--replace-in-metadata` to remove the specific characters you want.
> 
> Eg: `--replace-in-metadata title " &" ""` will remove only `&` and space

I don't know which characters to replace, such as the title above: ¦ It must not be typed by the keyboard, what is this kind of code called? How to remove all such characters uniformly?

**Comment by pukkandan** [comment]
> I don't know which characters to replace

you don't know what characters YOU want to replace, but I would?

> ¦ It must not be typed by the keyboard

You copied it here, no? Just copy paste it into the command the same way...

**Comment by 104979058** [comment]
> > I don't know which characters to replace
> 
> you don't know what characters YOU want to replace, but I would?
> 
> > ¦ It must not be typed by the keyboard
> 
> You copied it here, no? Just copy paste it into the command the same way...

Temporarily found that there is a problem with this character, but there may be other special characters/full-width characters, there seem to be many, found one to replace the other? Is there a better way?

**Comment by xbliss** [comment]
This one is breaking. https://www.youtube.com/watch?v=EadgCH_V4kQ 

What ways can we make this work?
