### ISSUE TITLE
Split-chapters: FFmpegSplitChaptersPP is not respecting the output template containing a path 

### ISSUE THREAD

**Issue by georgekav2** [yt-dlp/yt-dlp#3979]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.05.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

When the postprocessor of split files is used together with the output template that includes directory tree, the output chapter files are not respecting the parent directories. 

e.g for `yt-dlp -v --split-chapters -o "/downloads/%(title)s.%(ext)s" https://www.youtube.com/watch?v=pvkTC2xIbeY`
we get the bellow log. 

The important point is here where we see that ffmpeg gets passed an output file name without the directory structure that is given in the input. This is unlike how the other postprocessor (e.g extract audio) respecting properly their input and output path. 

> ffmpeg command line: ffmpeg -y -loglevel repeat+info -ss 0.0 -t 10.0 -i 'file:/downloads/How to Add Chapters to YouTube Videos _ Chapters Explained.webm' -map 0 -dn -ignore_unknown -c copy -movflags +faststart '**file:H**ow to Add Chapters to YouTube Videos _ Chapters Explained - 001 Intro 

I think it makes sense that in the _ffmpeg_args_for_chapter of FFmpegSplitChaptersPP the path provided in info['filepath'] to be considered for the FFmpeg opts

### Verbose log

```shell
[debug] Command-line config: ['-v', '--split-chapters', '-o', '/downloads/%(title)s.%(ext)s', 'https://www.youtube.com/watch?v=pvkTC2xIbeY']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.05.18 [b14d52355]
[debug] Python version 3.8.13 (CPython 32bit) - Linux-5.10.103-v8+-aarch64-with
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: ffmpeg -bsfs
[debug] exe versions: ffmpeg 4.4.1 (setts), ffprobe 4.4.1
[debug] Optional libraries: Cryptodome-3.14.1, brotli-1.0.9, certifi-2022.05.18, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=pvkTC2xIbeY
[youtube] pvkTC2xIbeY: Downloading webpage
[youtube] pvkTC2xIbeY: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] pvkTC2xIbeY: Downloading 1 format(s): 248+251
[download] /downloads/How to Add Chapters to YouTube Videos _ Chapters Explained.webm has already been downloaded
[SplitChapters] Splitting video by chapters; 7 chapters found
[SplitChapters] Chapter 001; Destination: How to Add Chapters to YouTube Videos _ Chapters Explained - 001 Intro [pvkTC2xIbeY].webm
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -ss 0.0 -t 10.0 -i 'file:/downloads/How to Add Chapters to YouTube Videos _ Chapters Explained.webm' -map 0 -dn -ignore_unknown -c copy -movflags +faststart 'file:How to Add Chapters to YouTube Videos _ Chapters Explained - 001 Intro [pvkTC2xIbeY].webm'
[debug] ffmpeg version 4.4.1 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 10.3.1 (Alpine 10.3.1_git20211027) 20211027
  configuration: --prefix=/usr --enable-avresample --enable-avfilter --enable-gnutls --enable-gpl --enable-libass --enable-libmp3lame --enable-libvorbis --enable-libvpx --enable-libxvid --enable-libx264 --enable-libx265 --enable-libtheora --enable-libv4l2 --enable-libdav1d --enable-postproc --enable-pic --enable-pthreads --enable-shared --enable-libxcb --enable-libsrt --enable-libssh --enable-libvidstab --disable-stripping --disable-static --disable-librtmp --enable-libaom --enable-libopus --enable-libsoxr --enable-libwebp --enable-vaapi --enable-vdpau --enable-vulkan --disable-debug
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Input #0, matroska,webm, from 'file:/downloads/How to Add Chapters to YouTube Videos _ Chapters Explained.webm':
  Metadata:
    ENCODER         : Lavf58.76.100
  Duration: 00:04:10.78, start: -0.007000, bitrate: 886 kb/s
  Stream #0:0(eng): Video: vp9 (Profile 0), yuv420p(tv, bt709), 1920x1080, SAR 1:1 DAR 16:9, 25 fps, 25 tbr, 1k tbn, 1k tbc (default)
    Metadata:
      DURATION        : 00:04:10.760000000
  Stream #0:1(eng): Audio: opus, 48000 Hz, stereo, fltp (default)
    Metadata:
      DURATION        : 00:04:10.781000000
file:How to Add Chapters to YouTube Videos _ Chapters Explained - 001 Intro [pvkTC2xIbeY].webm: Permission denied
ERROR: Postprocessing: file:How to Add Chapters to YouTube Videos _ Chapters Explained - 001 Intro [pvkTC2xIbeY].webm: Permission denied
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 3204, in process_info
    replace_info_dict(self.post_process(dl_filename, info_dict, files_to_move))
  File "/usr/local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 3374, in post_process
    info = self.run_all_pps('post_process', info, additional_pps=info.get('__postprocessors'))
  File "/usr/local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 3361, in run_all_pps
    info = self.run_pp(pp, info)
  File "/usr/local/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 3340, in run_pp
    files_to_delete, infodict = pp.run(infodict)
  File "/usr/local/lib/python3.8/site-packages/yt_dlp/postprocessor/common.py", line 25, in run
    ret = func(self, info, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/yt_dlp/postprocessor/common.py", line 129, in wrapper
    return func(self, info)
  File "/usr/local/lib/python3.8/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 1050, in run
    self.real_run_ffmpeg([(in_file, opts)], [(destination, self.stream_copy_opts())])
  File "/usr/local/lib/python3.8/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 321, in real_run_ffmpeg
    raise FFmpegPostProcessorError(stderr.split('\n')[-1])
yt_dlp.postprocessor.ffmpeg.FFmpegPostProcessorError: file:How to Add Chapters to YouTube Videos _ Chapters Explained - 001 Intro [pvkTC2xIbeY].webm: Permission denied
```

**Comment by pukkandan** [comment]
Set `-o chapter:...`. See docs of --split-chapters

**Comment by georgekav2** [comment]
Thanks for the reply. Yes well aware of `chapter` modifier in the output template. My question was on if it is intended to drop silently the path when the output template for chapter is not provided, given that we have a default template for the file name when user does not provide one. 
That is why I gave the example of extract audio post processor that respects the path (agreed though that this pp does not have dedicated prefix). 
Feel free to close the ticket if it was intended.

**Comment by pukkandan** [comment]
The normal `-o` obv cannot be used for chapter as-is. This would cause the original file and all chapters to share the same filename. So to respect `-o`, yt-dlp will need to split the user-provided `-o` at some point and add the chapter name to it. But it is not obvious where to make that split. This is why splitchapters is made to completely ignore the `-o` instead.

If on the other hand, you were to split your filepath b/w `-P` and `-o`, it would be obvious what to use for chapters and what not to. Eg: `-P /downloads -o %(title)s.%(ext)s` would know to put the original file as `/downloads/title.mp4` and chapters as `/downloads/title - 1. chapter.mp4`

**Comment by georgekav2** [comment]
Correct, the implicit allowance of path on `-o` creates such edge cases. As you said is better to pass it with `-P` while the templates remain for each filename independent depending of output type
