### ISSUE TITLE
Add support for installing from Winget

### ISSUE THREAD

**Issue by NSExceptional** [yt-dlp/yt-dlp#3982]
### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

[Winget](https://docs.microsoft.com/en-us/windows/package-manager/) is Windows' official package manager. Scoop and Chocolatey are nice, but Winget is built into the OS now and receives support from Microsoft. It would be great if I could install it with this!

**Comment by pukkandan** [comment]
Anyone can submit packages to winget. I won't be creating/maintaining it

**Comment by pukkandan** [comment]
Seems someone has already requested it: https://github.com/microsoft/winget-pkgs/issues/35475

**Comment by NSExceptional** [comment]
I see, thanks!

Looks like it's blocked by https://github.com/microsoft/winget-cli/issues/182 o_O

**Comment by KaranKad** [comment]
yt-dlp is now available from winget. You can install it by running `winget install yt-dlp`

**Comment by NSExceptional** [comment]
Awesome! Thanks!
