### ISSUE TITLE
CrunchyRoll HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by LunarFang416** [yt-dlp/yt-dlp#3992]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.05.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Canada

### Description

I am unable to download an episode from CrunchyRoll. It works fine for free (non-premium) episodes, however for premium episodes it gives the following error. I tried downloading with both cookies and direct username and password using -u and -p, however i am still receiving the error below.

### Verbose log

```shell
[debug] Command-line config: ['-u', 'PRIVATE', '-p', 'PRIVATE', 'https://beta.crunchyroll.com/watch/GN7UDPD1V/show-off-how-in-love-you-are', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.05.18 [b14d52355] (zip)
[debug] Python version 3.10.1 (CPython 64bit) - macOS-12.1-x86_64-i386-64bit
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: avprobe -bsfs
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: avconv -bsfs
[debug] exe versions: none
[debug] Optional libraries: certifi-2022.05.18.1, sqlite3-2.6.0
[debug] Proxy map: {}
[crunchyroll:beta] Getting session id
[crunchyroll:beta] Logging in
[debug] [crunchyroll:beta] Extracting URL: https://beta.crunchyroll.com/watch/GN7UDPD1V/show-off-how-in-love-you-are
[crunchyroll:beta] Retrieving main page
[crunchyroll:beta] Authenticating with cookie
[crunchyroll:beta] Retrieving signed policy
[crunchyroll:beta] show-off-how-in-love-you-are: Retrieving episode metadata
ERROR: [crunchyroll:beta] GN7UDPD1V: Unable to download JSON metadata: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 642, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/crunchyroll.py", line 815, in _real_extract
    episode_response = self._download_json(
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 1030, in _download_json
    res = self._download_json_handle(
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 1009, in _download_json_handle
    res = self._download_webpage_handle(
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 801, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query, expected_status=expected_status)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 786, in _request_webpage
    raise ExtractorError(errmsg, cause=err)

  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 768, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3596, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

**Comment by october262** [comment]
> ### Checklist
> * [x]  I'm reporting a broken site
> * [x]  I've verified that I'm running yt-dlp version **2022.05.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
> * [x]  I've checked that all provided URLs are playable in a browser with the same IP and same login details
> * [x]  I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
> * [x]  I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
> * [x]  I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
> * [x]  I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required
> 
> ### Region
> Canada
> 
> ### Description
> I am unable to download an episode from CrunchyRoll. It works fine for free (non-premium) episodes, however for premium episodes it gives the following error. I tried downloading with both cookies and direct username and password using -u and -p, however i am still receiving the error below.
> 
> ### Verbose log
> ```shell
> [debug] Command-line config: ['-u', 'PRIVATE', '-p', 'PRIVATE', 'https://beta.crunchyroll.com/watch/GN7UDPD1V/show-off-how-in-love-you-are', '-v']
> [debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
> [debug] yt-dlp version 2022.05.18 [b14d52355] (zip)
> [debug] Python version 3.10.1 (CPython 64bit) - macOS-12.1-x86_64-i386-64bit
> [debug] Checking exe version: ffprobe -bsfs
> [debug] Checking exe version: avprobe -bsfs
> [debug] Checking exe version: ffmpeg -bsfs
> [debug] Checking exe version: avconv -bsfs
> [debug] exe versions: none
> [debug] Optional libraries: certifi-2022.05.18.1, sqlite3-2.6.0
> [debug] Proxy map: {}
> [crunchyroll:beta] Getting session id
> [crunchyroll:beta] Logging in
> [debug] [crunchyroll:beta] Extracting URL: https://beta.crunchyroll.com/watch/GN7UDPD1V/show-off-how-in-love-you-are
> [crunchyroll:beta] Retrieving main page
> [crunchyroll:beta] Authenticating with cookie
> [crunchyroll:beta] Retrieving signed policy
> [crunchyroll:beta] show-off-how-in-love-you-are: Retrieving episode metadata
> ERROR: [crunchyroll:beta] GN7UDPD1V: Unable to download JSON metadata: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
>   File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 642, in extract
>     ie_result = self._real_extract(url)
>   File "/usr/local/bin/yt-dlp/yt_dlp/extractor/crunchyroll.py", line 815, in _real_extract
>     episode_response = self._download_json(
>   File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 1030, in _download_json
>     res = self._download_json_handle(
>   File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 1009, in _download_json_handle
>     res = self._download_webpage_handle(
>   File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 801, in _download_webpage_handle
>     urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query, expected_status=expected_status)
>   File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 786, in _request_webpage
>     raise ExtractorError(errmsg, cause=err)
> 
>   File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 768, in _request_webpage
>     return self._downloader.urlopen(url_or_request)
>   File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3596, in urlopen
>     return self._opener.open(req, timeout=self._socket_timeout)
>   File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 525, in open
>     response = meth(req, response)
>   File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 634, in http_response
>     response = self.parent.error(
>   File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 563, in error
>     return self._call_chain(*args)
>   File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 496, in _call_chain
>     result = func(*args)
>   File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 643, in http_error_default
>     raise HTTPError(req.full_url, code, msg, hdrs, fp)
> urllib.error.HTTPError: HTTP Error 403: Forbidden
> ```

what cookies did you try ??  cookies.txt or cookies from browser ??

**Comment by LunarFang416** [comment]
@october262 I downloaded by browser cookies for crunchyroll using a chrome extension and saved those in `cookies.txt`. 

That gave an error, then I directly used my username and password which also led to the same error.

**Comment by darkxex** [comment]
the compiled version is outdated from crunchyroll beta. if you want it to work you should update it like this.
python3 -m pip install --force-reinstall https://github.com/yt-dlp/yt-dlp/archive/master.tar.gz

https://github.com/yt-dlp/yt-dlp/pull/3801

**Comment by pukkandan** [comment]
ah, right! Fixed by 88d62206b41723ba85174bd4d33469089d23334b

**Comment by meap98** [comment]
> ah, right! Fixed by [88d6220](https://github.com/yt-dlp/yt-dlp/commit/88d62206b41723ba85174bd4d33469089d23334b)

if you don't mind me asking how do I fix the downloader

**Comment by pukkandan** [comment]
Wait for update

**Comment by aniplayIt** [comment]
> Wait for next release

Still getting the error with latest version 2022.07.18:

```
Cannot download episode: https://www.crunchyroll.com/it/classroom-of-the-elite/episode-6-adversity-is-the-first-path-to-truth-853080
Process detail: [crunchyroll] Getting session id
[crunchyroll] Logging in
[crunchyroll] 853080: Downloading webpage
ERROR: [crunchyroll] 853080: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using yt-dlp -U
```
