### ISSUE TITLE
[utils] improper class matching by get_elements_by_class/get_elements_html_by_class

### ISSUE THREAD

**Issue by krichbanana** [yt-dlp/yt-dlp#3993]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.05.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

The value-matching regex for the functions `get_elements_by_class` and `get_elements_html_by_class` improperly matches word boundaries: for example, `get_elements_html_by_class('video-item', webpage)` will return the element with class `list-video-item` rather than the elements inside it with the class 'video-item'.

Our example webpage element:
```html
<ul class="list-video-item stream-wrapper">
  <li class="video-item" data-id="316972">a</li>
  <li class="video-item" data-id="316705">b</li>
  <li class="video-item" data-id="316403">c</li>
  <li class="video-item" data-id="316178">d</li>
</ul>
```

Currently, `get_elements_html_by_class('video-item', webpage)` would return the `ul` element, when it should be returning each of the 4 `li` elements. Only `get_elements_html_by_attribute('class', 'video-item', webpage)` observes the correct behavior, however it's less flexible to use.

The \b sequence matches the space and end-of-line boundary properly, but also believe `-` to be a word boundary:
```python
>>> re.search(r'[^\'"]*\bCCC\b[^\'"]*', 'AAA BBB-CCC-DDD EEE')
<re.Match object; span=(0, 19), match='AAA BBB-CCC-DDD EEE'>
```

-----
Solution:
I suggest adding adding negative lookbehind/lookahead assertions like so:
`r'[^\'"]*(?<!-)\b%s\b(?!-)[^\'"]*'`

Trying to match class names "-AAA" and "BBB-" in a value like "-AAA BBB- CCC" won't work, but they didn't work to begin with and they would be weird names, so it seems fine to keep that behavior broken.

### Verbose log

```shell
[debug] Command-line config: ['-vU']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.05.18 [b14d52355] (source)
[debug] Lazy loading extractors is disabled
[debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
[debug] Git HEAD: 00bbc5f17
[debug] Python version 3.10.4 (CPython 64bit) - Linux-5.17.4-arch1-1-x86_64-with-glibc2.35
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 5.0 (setts), ffprobe 5.0, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.12.0, brotlicffi-1.0.9.2, certifi-2021.10.08, mutagen-1.45.1, secretstorage-3.3.2, sqlite3-2.6.0, websockets-10.1
[debug] Proxy map: {}
Latest version: 2022.05.18, Current version: 2022.05.18
yt-dlp is up to date (2022.05.18)
```

**Comment by pukkandan** [comment]
I believe this would be best:

```py
r'[^\'"]*(?<[\'"\s])%s(?=[\'"\s])[^\'"]*' % re.escape(class_name),
```

**Comment by dirkf** [comment]
See https://github.com/ytdl-org/youtube-dl/issues/30230#issuecomment-967179993 and https://github.com/ytdl-org/youtube-dl/pull/29845/commits/7d1059d6b8c817cc37d7598c7372ba832e6b55e2:

```py
    return get_elements_by_attribute(
        # class names can contain alphanumeric, -, _ and \ for escapes
        # don't allow a word break at -
        'class', r'(?:[\w\s\\-]*?[\w\s])?\b%s\b(?:[\w\s\\][\w\s\\-]*?)?' % re.escape(class_name),
        html, escape_value=False)
```
Ie: 
* 0 or more class name(s), followed by a space if 1 or more,
 followed by
* the target class name, followed by
* 0 or more class name(s), preceded by a space if 1 or more.

Historically (ie WHATWG), a single class name doesn't have to be quoted.
