### ISSUE TITLE
Question：How to fix when download links need to add url-patch ？

### ISSUE THREAD

**Issue by huliad2022** [yt-dlp/yt-dlp#3998]
### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Question

Just an example to ask, because there are other cases like this.

`MPD: https://vsu.play.kakao.com/vod/rvl390uo8872t9ih140lym4e2/dash/vhs/cenc/adaptive.mpd?px-time=1654576515&px-path=%2Fvod%2Frvl390uo8872t9ih140lym4e2%2Fdash%2Fvhs%2Fcenc%2F&px-hash=9da221a9c40d623303f0e810ad17d20f`

`ip： korea`

I need to add a url-patch `px-time=1654576515&px-path=%2Fvod%2Frvl390uo8872t9ih140lym4e2%2Fdash%2Fvhs%2Fcenc%2F&px-hash=9da221a9c40d623303f0e810ad17d20f` to download this MPD, how should I add it?

**Comment by HobbyistDev** [comment]
Hi @huliad2022, i can't understand what do you mean about 'url-patch'. Do you mean to change the query of url ? 
if yes, just change the parameter after `?` to your query. Hope this can help you.

**Comment by huliad2022** [comment]
> Hi @huliad2022, i can't understand what do you mean about 'url-patch'. Do you mean to change the query of url ? if yes, just change the parameter after to your query. Hope this can help you.`?`

Hello,  what do I need to add specific to download properly? I use other tools are required to add that part can work properly

**Comment by huliad2022** [comment]
Normally it can be parsed, but the download will be wrong

**Comment by Lesmiscore** [comment]
Since you don't seem to be using yt-dlp, things about general downloading jave to be asked at other forums
