### ISSUE TITLE
String not supported by Windows

### ISSUE THREAD

**Issue by shimiaoyerin** [yt-dlp/yt-dlp#4005]
### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Question

This should be an occasional failure.  When I test it alone, there is no problem, but sometimes it cannot be synthesized, and a bunch of files are left behind. Could this be related to my use of "aria2"?

![QQ截图20220607200010](https://user-images.githubusercontent.com/45694554/172374684-c0dfd6bb-282b-4e79-bfa9-1ad00b3ffe03.png)
![QQ截图20220607200142](https://user-images.githubusercontent.com/45694554/172374693-6204e8c5-4f89-4d51-bfdf-e3555d246bf7.png)
![QQ图片20220607200323](https://user-images.githubusercontent.com/45694554/172374704-46220839-edb5-4573-a720-71e590b83230.png)

### Verbose log

```shell
yt-dlp -vU --playlist-start 4000 -S "res,vbr,abr" --config-location "I:\youtube暂时下载文件\yt-dlp配置文件.txt" https://www.youtube.com/playlist?list=xxxxxxxxxxxxxxxxxxxx
[debug] Command-line config: ['-vU', '--playlist-start', '4000', '-S', 'res,vbr,abr', '--config-location', 'I:\\youtube 暂时下载文件\\yt-dlp配置文件.txt', 'https://www.youtube.com/playlist?list=xxxxxxxxxxm_JPPBj9oqJEme6n']
[debug] | Config "I:\youtube暂时下载文件\yt-dlp配置文件.txt": ['--sleep-interval', '0', '-o', '%(title)s-宽度%(width)s- 码率%(vbr)s-编码%(vcodec)s-频道名(%(uploader)s)-网页地址%(id)s.%(ext)s', '--external-downloader', 'aria2c', '--extractor-args', 'youtube:player_client=android,web', '--abort-on-error', '-f', 'bestvideo[width> 15360]+bestaudio/bestvideo[width> 10000]+bestaudio/bestvideo[width> 9900]+bestaudio/bestvideo[width> 9800]+bestaudio/bestvideo[width> 9700]+bestaudio/bestvideo[width> 9600]+bestaudio/bestvideo[width> 9500]+bestaudio/bestvideo[width> 9400]+bestaudio/bestvideo[width> 9200]+bestaudio/bestvideo[width> 9100]+bestaudio/bestvideo[width> 8900]+bestaudio/bestvideo[width> 8800]+bestaudio/bestvideo[width> 8700]+bestaudio/bestvideo[width> 8600]+bestaudio/bestvideo[width> 8500]+bestaudio/bestvideo[width> 8400]+bestaudio/bestvideo[width> 8300]+bestaudio/bestvideo[width> 8200]+bestaudio/bestvideo[width> 8100]+bestaudio/bestvideo[width> 8000]+bestaudio/bestvideo[width> 7900]+bestaudio/bestvideo[width> 7800]+bestaudio/bestvideo[width> 7700]+bestaudio/bestvideo[width> 7600]+bestaudio/bestvideo[width> 7500]+bestaudio/bestvideo[width> 7400]+bestaudio/bestvideo[width> 7300]+bestaudio/bestvideo[width> 7200]+bestaudio/bestvideo[width> 7100]+bestaudio/bestvideo[width> 7000]+bestaudio/bestvideo[width> 6900]+bestaudio/bestvideo[width> 6800]+bestaudio/bestvideo[width> 6700]+bestaudio/bestvideo[width> 6600]+bestaudio/bestvideo[width> 6500]+bestaudio/bestvideo[width> 6400]+bestaudio/bestvideo[width> 6300]+bestaudio/bestvideo[width> 6200]+bestaudio/bestvideo[width> 6100]+bestaudio/bestvideo[width> 6000]+bestaudio/bestvideo[width> 5900]+bestaudio/bestvideo[width> 5800]+bestaudio/bestvideo[width> 5700]+bestaudio/bestvideo[width> 5600]+bestaudio/bestvideo[width> 5500]+bestaudio/bestvideo[width> 5400]+bestaudio/bestvideo[width> 5300]+bestaudio/bestvideo[width> 5200]+bestaudio/bestvideo[width> 5100]+bestaudio/bestvideo[width> 5000]+bestaudio/bestvideo[width> 4900]+bestaudio/bestvideo[width> 4800]+bestaudio/bestvideo[width> 4700]+bestaudio/bestvideo[width> 4600]+bestaudio/bestvideo[width> 4500]+bestaudio/bestvideo[width> 4400]+bestaudio/bestvideo[width> 4300]+bestaudio/bestvideo[width> 4200]+bestaudio/bestvideo[width> 4100]+bestaudio/bestvideo[width> 4000]+bestaudio/bestvideo[width> 3900]+bestaudio/bestvideo[width> 3800]+bestaudio/bestvideo[width> 3700]+bestaudio/bestvideo[width> 3600]+bestaudio/bestvideo[width> 3500]+bestaudio/bestvideo[width> 3400]+bestaudio/bestvideo[width> 3300]+bestaudio/bestvideo[width> 3200]+bestaudio/bestvideo[width> 3100]+bestaudio/bestvideo[width> 3000]+bestaudio/bestvideo[width> 2900]+bestaudio/bestvideo[width> 2800]+bestaudio/bestvideo[width> 2700]+bestaudio/bestvideo[width> 2600]+bestaudio/bestvideo[width> 2500]+bestaudio/bestvideo[width> 2400]+bestaudio/bestvideo[width> 2300]+bestaudio/bestvideo[width> 2200]+bestaudio/bestvideo[width> 2100]+bestaudio/bestvideo[width> 2000]+bestaudio/bestvideo[width> 1900]+bestaudio/bestvideo[width> 1800]+bestaudio/bestvideo[width> 1800]+bestaudio/bestvideo[width> 1700]+bestaudio/bestvideo[width> 1600]+bestaudio/bestvideo[width> 1500]+bestaudio/bestvideo[width> 1400]+bestaudio/bestvideo[width> 1300]+bestaudio/bestvideo[width> 1200]+bestaudio/bestvideo[width> 1100]+bestaudio/bestvideo[width> 1000]+bestaudio/bestvideo[width> 900]+bestaudio/bestvideo[width> 800]+bestaudio/bestvideo[width> 700]+bestaudio/bestvideo+bestaudio']
[debug] Encodings: locale cp936, fs utf-8, pref cp936, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.05.18 [b14d523] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: ffmpeg -bsfs
[debug] exe versions: ffmpeg n4.4-177-gc989427c16-20211008 (setts), ffprobe n4.4-177-gc989427c16-20211008
[debug] Optional libraries: Cryptodome-3.14.1, brotli-1.0.9, certifi-2021.10.08, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {'https': 'http://127.0.0.1:10081', 'http': 'http://127.0.0.1:10081'}
Latest version: 2022.05.18, Current version: 2022.05.18
yt-dlp is up to date (2022.05.18)
[debug] [youtube:tab] Extracting URL: https://www.youtube.com/playlist?list=PLj1kwHPxxxxxxxxm_JPPBj9oqJEme6n

**Comment by shimiaoyerin** [comment]
aria2 cuts the video into a bunch of small packets, and finally because the file names do not match, it cannot be synthesized with ffmpeg

**Comment by pukkandan** [comment]
verbose log? And why is this a question and not a bug report?

**Comment by shimiaoyerin** [comment]
> verbose log? And why is this a question and not a bug report?

I can't reproduce the failure, so there is no detailed log, and I don't think it's a yt-dlp failure, so I'm posting on "problems" instead of "bug reports"

**Comment by shimiaoyerin** [comment]
> verbose log? And why is this a question and not a bug report?

![Uploading QQ截图20220607205105.png…]()

**Comment by shimiaoyerin** [comment]
> verbose log? And why is this a question and not a bug report?

![QQ截图20220607205105](https://user-images.githubusercontent.com/45694554/172384237-5de0f22d-24b7-4c46-b276-62f383de3dd6.png)

**Comment by pukkandan** [comment]
Without proper logs, I have no idea what the issue is, much less how to fix it

**Comment by Ashish0804** [comment]
Unless the resultant file is cursed, u can get rid of these files with a simple exec statement

**Comment by shimiaoyerin** [comment]
> Unless the resultant file is cursed, u can get rid of these files with a simple exec statement

I usually download thousands of videos, and if I have these problems too many times in the middle, it can be very troublesome

**Comment by shimiaoyerin** [comment]
> Without proper logs, I have no idea what the issue is, much less how to fix it

I really can't reproduce the accident, 

As can be seen from the figure, the source file will be deleted after the download is generally completed.↓
![QQ截图20220608005315](https://user-images.githubusercontent.com/45694554/172439455-d4669c95-e6a9-4847-8902-198d4e88da91.png)

But occasionally there will be a few that are not merged and deleted↓
![QQ截图20220608005842](https://user-images.githubusercontent.com/45694554/172440069-c78a227e-0b3e-4480-91b7-0bfc3564c70d.png)

**Comment by flashdagger** [comment]
@shimiaoyerin 
Do you work as a software project manager?

**Comment by shimiaoyerin** [comment]
> @shimiaoyerin Do you work as a software project manager?

not
