### ISSUE TITLE
[site request] Israel National News

### ISSUE THREAD

**Issue by M1Aston** [yt-dlp/yt-dlp#4019]
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.05.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Example URLs

https://www.israelnationalnews.com/news/354520
https://www.israelnationalnews.com/news/354518

### Description

I am a new user of yt-dlp, combined with mpc-be. So far it works pretty well, but now I bumped into a problem were embedded YT videos are not detected (?).

### Verbose log

```shell
Microsoft Windows [Version 10.0.19044.1706]
(c) Microsoft Corporation. Alle rechten voorbehouden.

C:\WINDOWS\system32>"C:\Users\a\Desktop\MPC-BE\yt-dlp.exe" -vU https://www.israelnationalnews.com/news/354520
[debug] Command-line config: ['-vU', 'https://www.israelnationalnews.com/news/354520']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.05.18 [b14d523] (win_exe)
[debug] Python version 3.7.9 (CPython 32bit) - Windows-10-10.0.19041-SP0
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: avprobe -bsfs
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: avconv -bsfs
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.14.1, brotli-1.0.9, certifi-2021.10.08, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
Latest version: 2022.05.18, Current version: 2022.05.18
yt-dlp is up to date (2022.05.18)
[debug] [generic] Extracting URL: https://www.israelnationalnews.com/news/354520
[generic] 354520: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] 354520: Downloading webpage
[generic] 354520: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://www.israelnationalnews.com/news/354520
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1395, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1465, in __extract_info
  File "yt_dlp\extractor\common.py", line 642, in extract
  File "yt_dlp\extractor\generic.py", line 4031, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.israelnationalnews.com/news/354520


C:\WINDOWS\system32>
```

**Comment by coletdjnz** [comment]
This site doesn't appear to directly embed Youtube, rather it calls its own API to get the youtube video id and then creates the embed. A specific site extractor would probably be needed.

relevant api call: https://www.israelnationalnews.com/Generic/NewAPI/Item?type=0&Item=354520

**Comment by M1Aston** [comment]
Ah, I see. But I think adding an extractor just for this website (not really big or important) is perhaps overkill. :-)

Thanks for your quick reply.

**Comment by eladkarako** [comment]
it's a mess.

as far I can tell, there are text to speech mp3 on the page:

<img width="633" alt="2022-06-08_205844" src="https://user-images.githubusercontent.com/415238/172685314-b57cd363-0bd1-4993-8fb0-6189e448868b.png">

that uses 
https://vd.trinitymedia.ai/text2speech/israelnationalnews.com/a3f2a2f8ee1dfccf45c9be9bd036abce0c003074325db956942409d0209d3ede_en-US-JennyNeural_neural/audio.mp3  

it isn't exists on the page, and needs js-rendering.

<img width="898" alt="2022-06-08_210247" src="https://user-images.githubusercontent.com/415238/172686070-03634fc6-0f0b-43da-abd2-c368e96f96e0.png">

<hr/>

there are plain youtube players wrapped with some style..

<img width="757" alt="2022-06-08_210432" src="https://user-images.githubusercontent.com/415238/172686282-d246495e-6df1-46ed-afd8-0adc366c6be4.png">

they are wrapped within `noembed`:  
https://noembed.com/embed?url=https://www.youtube.com/watch?v=jA84wQhVvg8

<img width="929" alt="2022-06-08_210806" src="https://user-images.githubusercontent.com/415238/172686856-384dd02e-e37b-4484-91f8-3f4f1fe914e4.png">

<hr/>

and there are also videos hosted on the local cdn of the website.
that also just exists on the DOM (requires js rendering), 
you can just download normally from the video source element
<img width="629" alt="2022-06-08_211140" src="https://user-images.githubusercontent.com/415238/172688128-998f7167-5a8c-4a18-a72e-454cbbff0e0a.png">

<img width="927" alt="2022-06-08_211411" src="https://user-images.githubusercontent.com/415238/172687969-7b1bd157-a769-4960-86e3-32c3a384978a.png">

**Comment by eladkarako** [comment]
I wish yt-dlp would enable https://github.com/puppeteer/puppeteer  
I have phantomjs (https://github.com/eladkarako/yt-dlp_kit) but it's super old and very buggy.

**Comment by coletdjnz** [comment]
It is very unlikely you will need js for an extractor for this site. we do not need to be rendering anything. just grab details from relevant HTML pages/API responses.

The text to speech might be an embed too, which details for are prob returned in a similar api response. It may require an additional extractor for that embed site. But I don't think that is something we are wanting to extract anyways.

**Comment by gamer191** [comment]
> Ah, I see. But I think adding an extractor just for this website (not really big or important) is perhaps overkill. :-)

There's already [over 900](https://github.com/yt-dlp/yt-dlp/tree/master/yt_dlp/extractor) extractors. And most are for sites you won't even have heard of ;)

**Comment by pukkandan** [comment]
Any website that does not fall under https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy is acceptable for a `site-request` - irrespective of popularity. If possible, we will try to improve `generic` extractor to handle the website, but if that is not feasible, it is a valid candidate for a new extractor.

Ofc, each developer may prioritize the requests based on the site's popularity, it's complexity, or for any other reason. The truth is, there simply isn't enough devs to ever be able to complete all the site requests. It only acts as a way to let contributors know that there is interest in the site.

I mark issues like this one, where we have already determined that the extraction process is relatively easy, with `good-first-issue` label in hopes that potential new contributors can use these as a good starting point.
