### ISSUE TITLE
live-from-start with VK video

### ISSUE THREAD

**Issue by shadowzoom** [yt-dlp/yt-dlp#4024]
### Checklist

- [X] I'm requesting a site-specific feature
- [X] I've verified that I'm running yt-dlp version **2022.05.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

everywhere

### Example URLs

vk.com

### Description

Hi, pls make option for vk --live-from-start

### Verbose log

```shell
Hi, pls make option for vk --live-from-start
```

**Comment by gamer191** [comment]
> ### Verbose log
> 
> ```shell
> Hi, pls make option for vk --live-from-start
> ```

That's not a verbose log
