### ISSUE TITLE
Batch usage for bulk video download

### ISSUE THREAD

**Issue by remizik** [yt-dlp/yt-dlp#4026]
### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Question

Hi,

I'd like to feed yt-dlp.exe with a text file containing one youtube video url per line.

the source file "youtubeDL_list.txt" looks like this : 

> https://www.youtube.com/watch?v=w4Alntxxxxx
> https://www.youtube.com/watch?v=yVDekZ1xxxx
> https://www.youtube.com/watch?v=fQGhstxxxxx

my batch file for the bulk download looks like this : 

> @echo off
> for /F "tokens=*" %%a in (C:\Users\test\Desktop\youtubeDL_list.txt) do (
> rem echo %%a
> start "" E:\Dropbox\IT_STUFF\POWERSHELL_BATCHS\yt-dlp.exe --ffmpeg-location "E:\TOOLS\ffmpeg\bin\ffmpeg.exe" -f > "bestvideo[height<=?1080]+bestaudio/best" -o G:\youtube\%%(title)s-%%(id)s.%%(ext)s %%a --no-mtime
> )

It doesn't work.
If I comment the main line and uncomment the echo %aa, I see the 3 youtube links.

Any idea ?
thanks

**Comment by coletdjnz** [comment]
`-a "C:\Users\test\Desktop\youtubeDL_list.txt"`

```
-a, --batch-file FILE           File containing URLs to download ("-" for
                                stdin), one URL per line. Lines starting
                                with "#", ";" or "]" are considered as
                                comments and ignored
```

**Comment by remizik** [comment]
> `-a "C:\Users\test\Desktop\youtubeDL_list.txt"`
> 
> ```
> -a, --batch-file FILE           File containing URLs to download ("-" for
>                                 stdin), one URL per line. Lines starting
>                                 with "#", ";" or "]" are considered as
>                                 comments and ignored
> ```

omfg how did I miss that -_-
I'm sorry and thanks, I'll try right away

**Comment by remizik** [comment]
yep, works perfectly. Thanks again
