### ISSUE TITLE
`-O filesize_approx` outputs a floating point number?

### ISSUE THREAD

**Issue by NSExceptional** [yt-dlp/yt-dlp#4027]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.05.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

Why does the output filesize have a decimal point?

```
> url=https://www.funimation.com/en/shows/attack-on-titan/assault-d040331a-5e6a-11eb-9026-0242ac110002
> yt-dlp.exe -O filesize_approx $url --no-check-certificate --cookies-from-browser chrome
1322737152.0
```

While I'm here, is there a way to get the approx filesize formatted like `325 MB`?

### Verbose log

```shell
[debug] Command-line config: ['-O', 'filesize_approx', '-u', 'PRIVATE', '-p', 'PRIVATE', 'https://www.funimation.com/en/shows/attack-on-titan/assault-d040331a-5e6a-11eb-9026-0242ac110002', '--no-check-certificate', '--cookies-from-browser', 'chrome', '-v']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8 
[debug] yt-dlp version 2022.05.18 [b14d523] (win_exe) 
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19041-SP0 
[debug] Checking exe version: ffprobe -bsfs 
[debug] Checking exe version: avprobe -bsfs
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: avconv -bsfs 
[debug] exe versions: none 
[debug] Optional libraries: Cryptodome-3.14.1, brotli-1.0.9, certifi-2021.10.08, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[Cookies] Extracting cookies from chrome
[debug] Extracting cookies from: "C:\Users\Tanner\AppData\Local\Google\Chrome\User Data\Default\Cookies" 
[debug] Found local state file at "C:\Users\Tanner\AppData\Local\Google\Chrome\User Data\Local State" 
[Cookies] Extracted 2087 cookies from chrome 
[debug] cookie version breakdown: {'v10': 2087, 'other': 0, 'unencrypted': 0} 
[debug] Proxy map: {} 
[funimation:page] Logging in 
[debug] [funimation:page] Extracting URL: https://www.funimation.com/en/shows/attack-on-titan/assault-d040331a-5e6a-11eb-9026-0242ac110002
[funimation:page] attack-on-titan_assault-d040331a-5e6a-11eb-9026-0242ac110002: Downloading JSON metadata 
[debug] [Funimation] Extracting URL: https://www.funimation.com/player/4039623 
[Funimation] 4039623: Downloading player webpage for 4039623 
[Funimation] assault-d040331a-5e6a-11eb-9026-0242ac110002: Downloading Simulcast portuguese (brazil) (2680561) JSON 
[Funimation] assault-d040331a-5e6a-11eb-9026-0242ac110002: Downloading Simulcast portuguese (brazil) (2680561) m3u8 information 
[Funimation] assault-d040331a-5e6a-11eb-9026-0242ac110002: Downloading Simulcast spanish (latin am) (2680462) JSON 
[Funimation] assault-d040331a-5e6a-11eb-9026-0242ac110002: Downloading Simulcast spanish (latin am) (2680462) m3u8 information 
[Funimation] assault-d040331a-5e6a-11eb-9026-0242ac110002: Downloading Uncut japanese (4100237) JSON 
[Funimation] assault-d040331a-5e6a-11eb-9026-0242ac110002: Downloading Uncut japanese (4100237) m3u8 information 
[Funimation] assault-d040331a-5e6a-11eb-9026-0242ac110002: Downloading Simulcast japanese (1341062) JSON 
[Funimation] assault-d040331a-5e6a-11eb-9026-0242ac110002: Downloading Simulcast japanese (1341062) m3u8 information 
[Funimation] assault-d040331a-5e6a-11eb-9026-0242ac110002: Downloading Uncut english (4039623) JSON 
[Funimation] assault-d040331a-5e6a-11eb-9026-0242ac110002: Downloading Uncut english (4039623) m3u8 information 
[Funimation] assault-d040331a-5e6a-11eb-9026-0242ac110002: Downloading Simulcast english (1379370) JSON 
[Funimation] assault-d040331a-5e6a-11eb-9026-0242ac110002: Downloading Simulcast english (1379370) m3u8 information 
[debug] Sort order given by extractor: lang, source 
[debug] Formats sorted by: hasvid, ie_pref, lang, source, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best 
[info] 1341060: Downloading 1 format(s): 4100237-hls-7117+4100237-hls-audio-aacl-256-Japanese 
1322737152.0
```

**Comment by flashdagger** [comment]
With Bash you can use numfmt:
`yt-dlp -O filesize_approx $url | numfmt --to=iec-i --suffix=B --format='%.2f'`

But since you are using Windows you need to find an alternative...

**Comment by NSExceptional** [comment]
@pukkandan i looked at the code and it _is_ casted to an int first, that's the weird thing. It must be being casted back to a float somewhere else.

**Comment by NSExceptional** [comment]
Also I'm on windows, do those tricks work on windows…?

**Comment by NSExceptional** [comment]
Gotcha, thanks :)

Can we talk about this?
> We could technically cast it to int, but I don't see the point.

Why don't you see a point? Shouldn't we be consistent?

**Comment by NSExceptional** [comment]
I'm just digging around the codebase looking for culprits, but is it possible this is the code being run in my case? It results in a float, and isn't casted:

https://github.com/yt-dlp/yt-dlp/blob/6837633a4a614920b6e43ffc6b4b8590dca8c9d7/yt_dlp/YoutubeDL.py#L2573

Related to my other request, seeing the output formatted: there is already some code to do just that. Can we add a flag to output the cleanly formatted size instead of telling people to do it themselves? It automatically approximates to the highest factor (KB, MB, GB, etc, instead of just MB or something). I'm happy to make a PR if someone can guide me through the process of adding a flag like that.

https://github.com/yt-dlp/yt-dlp/blob/6837633a4a614920b6e43ffc6b4b8590dca8c9d7/yt_dlp/YoutubeDL.py#L3554
https://github.com/yt-dlp/yt-dlp/blob/6837633a4a614920b6e43ffc6b4b8590dca8c9d7/yt_dlp/utils.py#L2158-L2159
https://github.com/yt-dlp/yt-dlp/blob/6837633a4a614920b6e43ffc6b4b8590dca8c9d7/yt_dlp/utils.py#L2144-L2157

**Comment by pukkandan** [comment]
> Related to my other request, seeing the output formatted: there is already some code to do just that. Can we add a flag to output the cleanly formatted size instead of telling people to do it themselves? It automatically approximates to the highest factor (KB, MB, GB, etc, instead of just MB or something). I'm happy to make a PR if someone can guide me through the process of adding a flag like that.

Did you even read my answer?

**Comment by NSExceptional** [comment]
Yes, did you even read mine? (Can we be polite please?)

> @pukkandan i looked at the code and it is casted to an int first, that's the weird thing. It must be being casted back to a float somewhere else.

It is [casted to an int somewhere else](https://github.com/yt-dlp/yt-dlp/blob/6837633a4a614920b6e43ffc6b4b8590dca8c9d7/yt_dlp/extractor/esri.py#L44, so I think I just realized that value is not used everywhere. Sorry for the confusion.

**Comment by pukkandan** [comment]
> I'm just digging around the codebase looking for culprits, but is it possible this is the code being run in my case? It results in a float, and isn't casted:
> 
> https://github.com/yt-dlp/yt-dlp/blob/6837633a4a614920b6e43ffc6b4b8590dca8c9d7/yt_dlp/YoutubeDL.py#L2573

Fixed



> Related to my other request, seeing the output formatted: there is already some code to do just that. Can we add a flag to output the cleanly formatted size instead of telling people to do it themselves? It automatically approximates to the highest factor (KB, MB, GB, etc, instead of just MB or something). I'm happy to make a PR if someone can guide me through the process of adding a flag like that.

Already answered

**Comment by NSExceptional** [comment]
> Already answered

Bro, bear with me, sorry if I'm a fucking idiot or something, but can you show me where you told me how to use yt-dlp's built-in file size formatting to output a formatted number?

**Comment by pukkandan** [comment]
`-O "%(filesize_approx)#.0D"`

Read "output template" section of readme for details

**Comment by NSExceptional** [comment]
Oh gotcha, I see now. Thanks for your patience. Sorry
