### ISSUE TITLE
Roblox Audio and Video assets

### ISSUE THREAD

**Issue by upintheairsheep2** [yt-dlp/yt-dlp#4029]
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.05.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

USA (southern California)

#### Individual Assets
Video: https://www.roblox.com/library/5608304953/
Audio: https://www.roblox.com/library/7910582982/
#### ”Playlists”
User Favorite Audio: https://www.roblox.com/users/1276530838/favorites#!/audio
User Favorite Video: https://www.roblox.com/users/1276530838/favorites#!/video
User Inventory Video: https://www.roblox.com/users/1276530838/inventory/#!/video
User Inventory Audio: https://www.roblox.com/users/1276530838/inventory/#!/audio
Audio Recommended: https://www.roblox.com/develop/library?CatalogContext=2&SortAggregation=5&LegendExpanded=true&Category=9
Audio Search: https://www.roblox.com/develop/library?CatalogContext=2&Keyword=Fnf&SortAggregation=5&LegendExpanded=true&Category=9
Video recommended: https://www.roblox.com/develop/library?CatalogContext=2&SortAggregation=5&LegendExpanded=true&Category=14
Video search: https://www.roblox.com/develop/library?CatalogContext=2&Keyword=Space&SortAggregation=5&LegendExpanded=true&Category=14

### Verbose log

```shell
Not attempted.
```

### Description

Roblox asset IDs can be downloaded via a specific URL. See Anaminus/roblox-bug-tracker#71 for more information about this. Roblox audios can be previewed in the browser but not as reliable as in the asset ID method but for people who prefer the website method for audios, make a flag called —use-website-audio for that. When downloaded roblox asset ids have no extension so append it. Metadata: comments, stars, owner, date, name, description, genre, thumbnail. Please also support extraction from a favorite list or owned list or a search in place of playlists. If you think neither of these seem to contain any audio or video, only audios contain audio, and videos need to be extracted directly via the asset id. Audios have an option to be extracted from the preview. Most of long Roblox audio are wiped out due to Roblox getting a lawsuit from all of recording companies in March 22, 2022. There still remains video and short audio. Even though the audios are unable to be played, we are still able to play them via Roblox games owned by the player. In the future we can fool Roblox into downloading unlisted audios via finding the creators game and pretending to request a download from there.

### Verbose log

```shell
Not attempted
```

**Comment by gamer191** [comment]
This has definitely been requested before, but I can't find the old site request. Did the OP of that site request delete it?

**Comment by upintheairsheep2** [comment]
It was me. My account was mistakenly flagged by GitHub as a spambot and the
support team is being assholes and not responding. I'm putting it here to
get it back into the light. I merged all the comments of the issue together
in the description.

**Comment by upintheairsheep2** [comment]
> This has definitely been requested before, but I can't find the old site request. Did the OP of that site request delete it?
> 
> EDIT: it was #3667 and yes, it was deleted

It’s not deleted. It’s just privated.
