### ISSUE TITLE
[Site Feature Request] bandcamp user page

### ISSUE THREAD

**Issue by lperez509** [yt-dlp/yt-dlp#403]
- [x ] I'm reporting a broken site support
- [ x] I've verified that I'm running yt-dlp version **2021.06.09**
- [ x] I've checked that all provided URLs are alive and playable in a browser
- [ x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ x] I've searched the bugtracker for similar issues including closed ones

```[debug] User config file: C:\Users\09515\AppData\Roaming\yt-dlp\config.txt
[debug] User config: ['-x', '--audio-format', 'mp3', '-o', 'D:/download/%(uploader)s/%(playlist)s/%(title)s.%(ext)s', '--no-mtime', '--embed-thumbnail', '-i', '--split-chapters', '--parse-metadata', 'playlist:(?s)(?P<meta_album>.+)', '--add-metadata', '--download-archive', 'dataarchive.txt']
[debug] Command-line config: ['https://steviasphere.bandcamp.com/music', '--verbose']
[debug] Loading archive file 'dataarchive.txt'

[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] yt-dlp version 2021.06.09
[debug] Python version 3.9.5 (CPython 64bit) - Windows-10-10.0.19042-SP0
[debug] exe versions: ffmpeg N-101865-g3e16d1c8a6, ffprobe N-101865-g3e16d1c8a6
[debug] Proxy map: {}
[debug] [Bandcamp:album] Extracting URL: https://steviasphere.bandcamp.com/music
[Bandcamp:album] steviasphere: Downloading webpage
ERROR: The page doesn't contain any tracks; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "c:\users\09515\appdata\local\programs\python\python39\lib\site-packages\yt_dlp\YoutubeDL.py", line 1133, in wrapper
    return func(self, *args, **kwargs)
  File "c:\users\09515\appdata\local\programs\python\python39\lib\site-packages\yt_dlp\YoutubeDL.py", line 1154, in __extract_info
    ie_result = ie.extract(url)
  File "c:\users\09515\appdata\local\programs\python\python39\lib\site-packages\yt_dlp\extractor\common.py", line 567, in extract
    ie_result = self._real_extract(url)
  File "c:\users\09515\appdata\local\programs\python\python39\lib\site-packages\yt_dlp\extractor\bandcamp.py", line 303, in _real_extract
    raise ExtractorError('The page doesn\'t contain any tracks')
yt_dlp.utils.ExtractorError: The page doesn't contain any tracks; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.```

im downloading a bandcamp artist on a windows 10 and it says there is no albums

**Comment by pukkandan** [comment]
I don't think Artist pages were ever supported, only albums like https://steviasphere.bandcamp.com/album/reality-is-not-a-computer-simulation

**Comment by lperez509** [comment]
then can you please make it so artists pages are supported?

**Comment by Ashish0804** [comment]
the url u gave has few albums
U got an example of an atrist with 100+ albums so i can confirm if the links are hardcoded or they use api or something?

**Comment by lperez509** [comment]
i dont think i know an artist with that many albums but i can find one with alot

**Comment by lyz-code** [comment]
I made looooong time ago [a PR in youtube-dl](https://github.com/ytdl-org/youtube-dl/pull/20207/files) adding support for bandcamp user urls, I've seen that @Ashish0804 made another [PR](https://github.com/yt-dlp/yt-dlp/pull/668/files) but we cover different cases. Would you be interested if I made the same PR in this project?

**Comment by pukkandan** [comment]
How does it "cover different cases"? If it is an improvement over the current implementation, feel free to make a PR

**Comment by lyz-code** [comment]
The current implementation doesn't support user pages with the format:

https://adrianvonziegler.bandcamp.com
https://nightcallofficial.bandcamp.com
http://dotscale.bandcamp.com

I've created the [PR](https://github.com/yt-dlp/yt-dlp/pull/2800), if it gets accepted I'm going to cry of joy after 3 years waiting for it to be merged
