### ISSUE TITLE
Wasting time and bandwidth with "--dateafter"

### ISSUE THREAD

**Issue by atom-smasher** [yt-dlp/yt-dlp#4034]
### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Question

Sometimes I just want to grab some recent videos from a few channels, and enjoy them on VLC, or whatever.

To download videos from three YT channels, and only grab videos that were uploaded in the last few weeks, I may something like this:
`yt-dlp --dateafter 20220401 https://www.youtube.com/c/Goldsilver https://www.youtube.com/c/VeganGains https://www.youtube.com/c/SebAlex`

That's great and all, but it won't even start looking at the second channel until after it checks that most of the ≈800 videos on the first channel are older than what I'm looking for. Then similar when going to all subsequent channels.

Since the default sort order for most platforms (eg Youtube, Odysee) is most recent first, I'd like to think there's a way to stop checking, after 1 (or n) videos are older than specified via "--dateafter".

I haven't needed to try it, but I'm guessing that "--datebefore" is similarly inefficient.

Are there any tricks to get this running faster? Or should this push me to write a feature request?

**Comment by coletdjnz** [comment]
For your purpose this should work: `--extractor-args youtubetab:approximate_date --break-on-reject --dateafter now-2weeks`

YouTube doesn't provide us with an exact upload date in feeds so we have to make do with using the relative upload date.

**Comment by atom-smasher** [comment]
Good to know about that, thanks.

Looks like just adding "--break-on-reject" can also work with "--dateafter" on at least some other websites.
```
[download] 2022-03-16 upload date is not in range 2022-04-01 - 9999-12-31
[info] Encountered a video that did not match filter, stopping due to --break-on-reject
Aborting remaining downloads
```

I'm guessing that "--break-on-reject" would also work with "--datebefore" and "--playlist-reverse" (or a URL that sorts videos in reverse date order)…? Not sure if there's any tricks to make it work with both "--dateafter" and "--datebefore", but right now I don't have any excuse to fight with it.

**Comment by branch-predictor** [comment]
@atom-smasher this won't work if you use ``-a`` to download from multiple Youtube channels in one `yt-dlp` invocation (it'll break **entirely**, not just that single channel).

**Comment by pukkandan** [comment]
`--break-per-input`

**Comment by pukkandan** [comment]
> For your purpose this should work: `--extractor-args youtubetab:approximate_date --break-on-reject --dateafter now-2weeks`

Now `--break-on-reject --lazy-playlist --dateafter now-2weeks` should be a more reliable way to do this
