### ISSUE TITLE
Zoom - Chat Support

### ISSUE THREAD

**Issue by upintheairsheep2** [yt-dlp/yt-dlp#4037]
### Checklist

- [X] I'm requesting a site-specific feature
- [X] I've verified that I'm running yt-dlp version **2022.05.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Southern California, USA

### Example URLs

https://zoom.us/rec/play/6JV_c-36-DM3T9GQsASDC_F7W46_J6msgSQZ-vcEn0q9VCVVNlKiNLcaYuNMjek9LoEdvtcD0YiquC00

### Description

Please add support for zoom’s chat replays. They can be accessed via a button.

### Verbose log

```shell
Not attempted
```

**Comment by gamer191** [comment]
> Not attempted

Can you please attempt it (using `--list-subs`)

**Comment by Lesmiscore** [comment]
`--write-subs --sub-langs cc` gives what you want.
