### ISSUE TITLE
[Question] Where does yt-dlp get formats from

### ISSUE THREAD

**Issue by tyuhas** [yt-dlp/yt-dlp#404]
## Checklist

- [x ] I'm asking a question
- [x ] I've looked through the README and FAQ for similar questions
- [x ] I've searched the bugtracker for similar questions including closed ones

## Question

I'm curious how the list formats (-F) gets the available resolutions.  Using this show's episode as an example (at this point unlocked to the public):

https://play.history.com/shows/the-secret-of-skinwalker-ranch/season-2/episode-4

When I open it in Chrome developer tools and look at the master.m3u8?xxxx file, the best resolution that's available is 960x540.  Using yt-dlp with -F, it finds a resolution of 1280x720.

Thanks!

**Comment by pukkandan** [comment]
It gets it from the API. See `AENetworksBaseIE` in aenetworks.py

**Comment by tyuhas** [comment]
Thanks!  I will check it out
