### ISSUE TITLE
Odysee Truncated Video Download

### ISSUE THREAD

**Issue by iCeOhL8TR** [yt-dlp/yt-dlp#4041]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.05.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

USA

### Description

Tried to download video from Odysee and video is truncated only 1:10 minutes downloaded 1:20 minutes in web player and it is truncated at the end of the yt-dlp downloaded one.  Feels like there is another part of the blockchain stream its not catching....
:

### Verbose log

```shell
The log is just going to show that it operated correctly. Seems like its missing some transfer in the way the blockchain streaming works but if it shows up correctly in the webplayer the truncated portion must somehow be available. The log is normal nothing to see here.......  Rather not divulge what I was watching........
```

**Comment by pukkandan** [comment]
Irrespective of the excuses, we need to see log
