### ISSUE TITLE
[Site Request] can you please add a downloading feature for an artists bandcamp page?

### ISSUE THREAD

**Issue by lperez509** [yt-dlp/yt-dlp#405]
- [x ] I'm reporting a site feature request
- [x ] I've verified that I'm running yt-dlp version **2021.06.09**
- [ x] I've searched the bugtracker for similar site feature requests including closed ones

## Description
i would like a feature so i can download an artists page on bandcamp instead of downloading each individual album. 
for example, this artist in the screenshot: 
![image](https://user-images.githubusercontent.com/84653175/121760376-4f301100-cadf-11eb-9446-9da21df5c810.png)

**Comment by pukkandan** [comment]
Related: #403
