### ISSUE TITLE
[YouTube] Downloading live chat for videos containing self-harm fails

### ISSUE THREAD

**Issue by rebane2001** [yt-dlp/yt-dlp#4051]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.05.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [x] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Description

Downloading videos containing both the self-harm warning and a live chat fails, probably due to the live chat not being visible without accepting the warning.

To reproduce the bug, just run this command:
`yt-dlp -vU --write-sub --sub-langs live_chat https://www.youtube.com/watch?v=kvKzRFonN90`

This bug seems to affect both Windows and Linux. Accepting the warning does not require a YouTube account, since it is not the age restriction.

Here is a screenshot of the warning that seems to cause the issue:
![image](https://user-images.githubusercontent.com/6316541/173184140-860d268b-07d5-4e7e-b226-2016d4b35529.png)

As can be seen, the live chat only appears on the website after accepting the warning:
![image](https://user-images.githubusercontent.com/6316541/173184169-cfe3ade3-0d6a-430d-8e64-be46454cbb1e.png)

### Verbose log

```shell
[debug] Command-line config: ['-vU', '--write-sub', '--sub-langs', 'live_chat', 'https://www.youtube.com/watch?v=kvKzRFonN90']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.05.18 [b14d52355]
[debug] Python version 3.10.2 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: ffmpeg -bsfs
[debug] exe versions: ffmpeg git-2019-11-13-a7245ad, ffprobe git-2019-11-13-a7245ad
[debug] Optional libraries: Cryptodome-3.12.0, brotli-1.0.9, certifi-2021.10.08, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.1
[debug] Proxy map: {}
Latest version: 2022.05.18, Current version: 2022.05.18
yt-dlp is up to date (2022.05.18)
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=kvKzRFonN90
[youtube] kvKzRFonN90: Downloading webpage
[youtube] kvKzRFonN90: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[debug] Downloading subtitles: live_chat
[debug] Default format spec: bestvideo*+bestaudio/best
[info] kvKzRFonN90: Downloading 1 format(s): 248+251
[info] Writing video subtitles to: Caught In The Act (Self-Harm Comfort) ASMR Girlfriend Roleplay (F4A) [kvKzRFonN90].live_chat.json
[debug] Invoking youtube_live_chat downloader on "https://www.youtube.com/watch?v=kvKzRFonN90"
[youtube_live_chat] Downloading live chat
[youtube_live_chat] Total fragments: unknown (live)
[download] Destination: Caught In The Act (Self-Harm Comfort) ASMR Girlfriend Roleplay (F4A) [kvKzRFonN90].live_chat.json
[debug] File locking is not supported on this platform. Proceeding without locking
[download] 335.80KiB at  1.07MiB/s (00:00) (frag 1)ERROR: can only concatenate str (not "NoneType") to str
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 1395, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Program Files\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 1479, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "C:\Program Files\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 1535, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "C:\Program Files\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 2640, in process_video_result
    self.process_info(new_info)
  File "C:\Program Files\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 2892, in process_info
    sub_files = self._write_subtitles(info_dict, temp_filename)
  File "C:\Program Files\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 3862, in _write_subtitles
    self.dl(sub_filename, sub_copy, subtitle=True)
  File "C:\Program Files\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 2838, in dl
    return fd.download(name, new_info, subtitle)
  File "C:\Program Files\Python310\lib\site-packages\yt_dlp\downloader\common.py", line 445, in download
    ret = self.real_download(filename, info_dict)
  File "C:\Program Files\Python310\lib\site-packages\yt_dlp\downloader\youtube_live_chat.py", line 165, in real_download
    chat_page_url = 'https://www.youtube.com/live_chat_replay?continuation=' + continuation_id
TypeError: can only concatenate str (not "NoneType") to str
```

**Comment by coletdjnz** [comment]
the request likely requires the first two parameters we have here https://github.com/yt-dlp/yt-dlp/blob/master/yt_dlp/extractor/youtube.py#L3339

or the the Innertube API equivalents (`contentCheckOk` etc.)
