### ISSUE TITLE
How to reset the file date ? 

### ISSUE THREAD

**Issue by Menard01** [yt-dlp/yt-dlp#4052]
### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Question

Is there a feature not to keep the date of the downloaded file ? 
Often the dates are far older than the download's date and Linux only keep this old date (modified) when moving or copying on an NTFS partition, that's why I want to get rid of this useless dates that make lose the download date

**Comment by pukkandan** [comment]
--no-mtime

**Comment by Menard01** [comment]
Yes, I ve checked, this work on my system, thanks a lot

**Comment by dirkf** [comment]
Also see https://github.com/yt-dlp/yt-dlp/issues/3514#issuecomment-1105875575.
