### ISSUE TITLE
Customize multiple clarity codes

### ISSUE THREAD

**Issue by Honglong22** [yt-dlp/yt-dlp#4053]
### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Question

I want to download YouTube's highest-definition video, but the minimum resolution is not lower than 1440P code 271 or 400, Audio is also downloaded with the highest bitrate，But only video can be downloaded, audio can't be downloaded

The code I use is

AV1: 702/703/571/701/401/400+328/380/258/256/140

VP9: 272/337/315/313/308/271+328/380/258/256/140

### Verbose log

```shell
D:\高清修复音乐录影带>yt-dlp --proxy http://127.0.0.1:10809 --merge-output-format mp4 --audio-multistreams --video-multistreams --compat-options no-live-chat --all-subs --embed-subs --add-metadata --external-downloader aria2c --external-downloader-args "-x 16 -k 1M" -o "%(title)s" -i -f 272/337/315/313/308/271+328/380/258/256/140 https://www.youtube.com/watch?v=N6tv11_KMiM
WARNING: external downloader arguments given without specifying name. The arguments will be given to all external downloaders
[youtube] N6tv11_KMiM: Downloading webpage
WARNING: [youtube] Unable to download webpage: Remote end closed connection without response
[youtube] N6tv11_KMiM: Downloading android player API JSON
[youtube] N6tv11_KMiM: Downloading iframe API JS
[youtube] N6tv11_KMiM: Downloading player 23010b46
[youtube] N6tv11_KMiM: Downloading web player API JSON
[youtube] N6tv11_KMiM: Downloading initial data API JSON
[info] N6tv11_KMiM: Downloading 1 format(s): 313
[info] Writing video subtitles to: Halsey - So Good (Official Video).en-nP7-2PuUl7o.vtt
[download] Destination: Halsey - So Good (Official Video).en-nP7-2PuUl7o.vtt
[aria2c] Downloaded 3724 bytes
[download] 100% of 3.64KiB in 00:01
[download] Destination: Halsey - So Good (Official Video)
[aria2c] Downloaded 210805730 bytes 60KiB]
[download] 100% of 201.04MiB in 01:54
[EmbedSubtitle] Embedding subtitles in "Halsey - So Good (Official Video)"
ERROR: file:Halsey - So Good (Official Video).temp: Invalid argument
[Metadata] Adding metadata to "Halsey - So Good (Official Video)"
ERROR: file:Halsey - So Good (Official Video).temp: Invalid argument
```

**Comment by Honglong22** [comment]
This method is mainly used to download playlists

**Comment by pukkandan** [comment]
Use brackets like `(v1/v2)+(a1/a2)`

**Comment by Honglong22** [comment]
> 使用括号，如`(v1/v2)+(a1/a2)`

Only two at most?

**Comment by pukkandan** [comment]
No, you can use any number of items. My point is that you should use **brackets** to group the video and audio separately

> AV1: 702/703/571/701/401/400+328/380/258/256/140

becomes

`(702/703/571/701/401/400)+(328/380/258/256/140)`

**Comment by Honglong22** [comment]
> 不，您可以使用任意数量的物品。我的观点是您应该使用**括号**将视频和音频分开分组
> 
> > AV1：702/703/571/701/401/400+328/380/258/256/140
> 
> 变成
> 
> `(702/703/571/701/401/400)+(328/380/258/256/140)`

It works, thanks a lot
