### ISSUE TITLE
TVer AttributeError: 'list' object has no attribute 'isdigit'

### ISSUE THREAD

**Issue by cangyuyao** [yt-dlp/yt-dlp#4054]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.05.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Japan

### Description

#4033 Still not works with some url like: https://tver.jp/episodes/epswy2pl7x

Link can be opened in browser and downloaded with m3u8 link retrieved in console. 

### Verbose log

```shell
> yt-dlp --geo-bypass-country JP --all-subs https://tver.jp/episodes/epswy2pl7x -v
[debug] Command-line config: ['--geo-bypass-country', 'JP', '--all-subs', 'https://tver.jp/episodes/epswy2pl7x', '-v']
[debug] Encodings: locale cp936, fs utf-8, pref cp936, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.05.18 [b14d52355]
[debug] Python version 3.9.6 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.1.3, ffprobe 4.1.3
[debug] Optional libraries: Cryptodome-3.14.1, brotli-1.0.9, certifi-2018.01.18, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.2
[debug] Proxy map: {}
[debug] Using fake IP 133.144.188.99 (JP) as X-Forwarded-For
[TVer] Creating session
[debug] [TVer] Extracting URL: https://tver.jp/episodes/epswy2pl7x
[TVer] epswy2pl7x: Downloading JSON metadata
[TVer] epswy2pl7x: Downloading JSON metadata
ERROR: 'list' object has no attribute 'isdigit'
Traceback (most recent call last):
  File "D:\Python39\lib\site-packages\yt_dlp\YoutubeDL.py", line 1420, in wrapper
    return func(self, *args, **kwargs)
  File "D:\Python39\lib\site-packages\yt_dlp\YoutubeDL.py", line 1490, in __extract_info
    ie_result = ie.extract(url)
  File "D:\Python39\lib\site-packages\yt_dlp\extractor\common.py", line 642, in extract
    ie_result = self._real_extract(url)
  File "D:\Python39\lib\site-packages\yt_dlp\extractor\tver.py", line 82, in _real_extract
    if not r_id.isdigit():
AttributeError: 'list' object has no attribute 'isdigit'
```

**Comment by Lesmiscore** [comment]
```
$ git diff
diff --git a/yt_dlp/extractor/tver.py b/yt_dlp/extractor/tver.py
index df12e9702..cebd027c8 100644
--- a/yt_dlp/extractor/tver.py
+++ b/yt_dlp/extractor/tver.py
@@ -76,7 +76,7 @@ def _real_extract(self, url):
                 'Referer': 'https://tver.jp/',
             })
         p_id = video_info['video']['accountID']
-        r_id = traverse_obj(video_info, ('video', ('videoRefID', 'videoID')))
+        r_id = traverse_obj(video_info, ('video', ('videoRefID', 'videoID')), get_all=False)
         if not r_id:
             raise ExtractorError('Failed to extract reference ID for Brightcove')
         if not r_id.isdigit():
```
@pukkandan Can I commit this directly? Or you'll mix it in the next minor changes?

**Comment by pukkandan** [comment]
In the future, if there are bugs in your own commit, feel free fix it directly with a commit message like:
```
[extractor/tvver] Fix bug in h6837633a4a614920b6e43ffc6b4b8590dca8c9d7
```
