### ISSUE TITLE
cartoonnetwork.com "unlocked" episodes failing.

### ISSUE THREAD

**Issue by zang74** [yt-dlp/yt-dlp#4059]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.05.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United States

### Description

I'm trying to download unlocked Cartoon Network episodes and YT-DLP is failing.

These don't require a cable company login, and should be available to anyone (region-locked of course). I can view these episodes in a browser, but they fail in YT-DLP.

### Verbose log

```shell
yt-dlp -vU http://cartoonnetwork.com/video/we-baby-bears/sheep-bears-episode.html
[debug] Command-line config: ['-vU', 'http://cartoonnetwork.com/video/we-baby-bears/sheep-bears-episode.html']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.05.18 [b14d52355]
[debug] Python version 3.10.4 (CPython 64bit) - Linux-5.17.5-meson64-aarch64-with-glibc2.35
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: ffmpeg -bsfs
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2
[debug] Optional libraries: Cryptodome-3.14.1, brotli-1.0.9, certifi-2021.10.08, mutagen-1.45.1, secretstorage-3.3.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
Latest version: 2022.05.18, Current version: 2022.05.18
yt-dlp is up to date (2022.05.18)
[debug] [CartoonNetwork] Extracting URL: http://cartoonnetwork.com/video/we-baby-bears/sheep-bears-episode.html
[CartoonNetwork] sheep-bears: Downloading webpage
ERROR: [CartoonNetwork] sheep-bears: Unable to extract media id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/home/pi/.local/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 642, in extract
    ie_result = self._real_extract(url)
  File "/home/pi/.local/lib/python3.10/site-packages/yt_dlp/extractor/cartoonnetwork.py", line 33, in _real_extract
    media_id = find_field('mediaId', 'media id', 'id', '[0-9a-f]{40}', True)
  File "/home/pi/.local/lib/python3.10/site-packages/yt_dlp/extractor/cartoonnetwork.py", line 29, in find_field
    return self._search_regex(
  File "/home/pi/.local/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 1226, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
```

**Comment by pukkandan** [comment]
Works for me
```
❯ yt-dlp https://www.cartoonnetwork.com/video/we-baby-bears/sheep-bears-episode.html
[CartoonNetwork] sheep-bears: Downloading webpage
[CartoonNetwork] 2bc8fe88ced079aaf6c092cfab2f580bc18cbd64: Downloading JSON metadata
[CartoonNetwork] 2bc8fe88ced079aaf6c092cfab2f580bc18cbd64: Downloading XML
[CartoonNetwork] 2bc8fe88ced079aaf6c092cfab2f580bc18cbd64: Downloading m3u8 information
[info] 2bc8fe88ced079aaf6c092cfab2f580bc18cbd64: Downloading 1 format(s): hls-5021
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 114
[download] Destination: Sheep Bears [2bc8fe88ced079aaf6c092cfab2f580bc18cbd64].mp4
[download]   0.9% of ~387.53MiB at  825.55KiB/s ETA 07:56 (frag 1/114)
```

**Comment by zang74** [comment]
With no other change, it seems back to a working state. Perhaps a bug or a typo in the Cartoon Network site code.
