### ISSUE TITLE
[Site Request] Extract cast list from pornhub

### ISSUE THREAD

**Issue by MrDemous** [yt-dlp/yt-dlp#406]
- [ x] I'm reporting a site feature request
- [ x] I've verified that I'm running yt-dlp version **2021.06.09**
- [x ] I've searched the bugtracker for similar site feature requests including closed ones

## Description

Is it possible to add the ability to extract cast members from video's page on Pornhub?

Someone made a pull request to youtube-dl's repo a while ago but they didn't merge it.

https://github.com/ytdl-org/youtube-dl/pull/27384

**Comment by pukkandan** [comment]
I agree with @dstftw that the data should be in the form of a list similar to tags, categories, etc. It will be possible to convert this to a comma delimited string by the user if needed once #345 is resolved

**Comment by MrDemous** [comment]
@pukkandan You're amazing and thank you for the amazing work you're doing.
