### ISSUE TITLE
www.ndr.de

### ISSUE THREAD

**Issue by M1Aston** [yt-dlp/yt-dlp#4063]
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.05.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Example URLs

https://www.ndr.de/nachrichten/niedersachsen/oldenburg_ostfriesland/Hotelneubau-an-der-Strandpromenade-Wangerooger-sagen-Nein,wangerooge608.html
https://www.ndr.de/nachrichten/info/Warum-eine-Oel-Raffinerie-im-Norden-auf-gruenen-Wasserstoff-setzt,gruenerwasserstoff100.html

### Description

Embedded audio and video not detected.

### Verbose log

```shell
C:\WINDOWS\system32>"C:\Users\a\Desktop\MPC-BE\yt-dlp.exe" -vU https://www.ndr.de/nachrichten/niedersachsen/oldenburg_ostfriesland/Hotelneubau-an-der-Strandpromenade-Wangerooger-sagen-Nein,wangerooge608.html
[debug] Command-line config: ['-vU', 'https://www.ndr.de/nachrichten/niedersachsen/oldenburg_ostfriesland/Hotelneubau-an-der-Strandpromenade-Wangerooger-sagen-Nein,wangerooge608.html']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.05.18 [b14d523] (win_exe)
[debug] Python version 3.7.9 (CPython 32bit) - Windows-10-10.0.19041-SP0
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: avprobe -bsfs
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: avconv -bsfs
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.14.1, brotli-1.0.9, certifi-2021.10.08, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
Latest version: 2022.05.18, Current version: 2022.05.18
yt-dlp is up to date (2022.05.18)
[debug] [ndr] Extracting URL: https://www.ndr.de/nachrichten/niedersachsen/oldenburg_ostfriesland/Hotelneubau-an-der-Strandpromenade-Wangerooger-sagen-Nein,wangerooge608.html
[ndr] Hotelneubau-an-der-Strandpromenade-Wangerooger-sagen-Nein: Downloading webpage
[ndr] wangerooge608: Downloading JSON metadata
ERROR: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1395, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1465, in __extract_info
  File "yt_dlp\extractor\common.py", line 642, in extract
  File "yt_dlp\extractor\ndr.py", line 19, in _real_extract
  File "yt_dlp\extractor\ndr.py", line 92, in _extract_embed
TypeError: 'NoneType' object is not iterable
```

**Comment by HobbyistDev** [comment]
To Dev:
in this url (https://www.ndr.de/nachrichten/niedersachsen/oldenburg_ostfriesland/Hotelneubau-an-der-Strandpromenade-Wangerooger-sagen-Nein,wangerooge608.html), the video is in `div class="player video embedded`. We can get video from `ld+json` inside the tag and get the video from `contentUrl`

Here's the `ld+json` from the url:
```json
{
  "@context": "https://schema.org",
  "@type": "VideoObject",
  "name": "Der Inselmakler (23.03.2022)",
  "description": "Immobilien auf den Ostfriesischen Inseln sind sehr gefragt, das Preisniveau entsprechend hoch. Einer, der sich besonders gut damit auskennt, ist Inselmakler Martin Ullrich. Der gebürtige Ostfriese muss für seine Geschäfte viel Fingerspitzengefühl mitbringen, denn oft geht es um Millionenbeträge und die Insulaner betrachten jeden Hauserverkauf mit Argwohn. Ullrichs Kunden kommen oft vom Festland, bewohnen das Objekt später nur sporadisch und bringen sich nicht in die Inselgemeinschaft ein.",
  "thumbnailUrl": "https://www.ndr.de/fernsehen/screenshot1305086_v-contentxl.jpg",
  "uploadDate": "2022-06-13T09:27:46.200+02:00",
  "duration": "PT28M19S",
  "expires": "2023-03-24T01:30:00.000+01:00",
  "contentUrl": "https://mediandr-a.akamaihd.net/progressive/2022/0323/TV-20220323-1553-5000.hq.mp4",
  "embedUrl": "https://www.ndr.de/fernsehen/sendungen/die_nordreportage/dienordreportage1822-ardplayer.html",
  "publisher": {
    "@type": "Organization",
    "name": "NDR",
    "url": "https://www.ndr.de",
    "sameAs": [
      "https://www.facebook.com/NDR.de",
      "https://twitter.com/ndr"
    ],
    "logo": {
      "@type": "ImageObject",
      "url": "https://www.ndr.de/resources/images/logos/ndr_printlogo.gif",
      "width": 53,
      "height": 51
    }
  }
}
```

**Comment by dirkf** [comment]
yt-dl extracts two formats but also some warnings:
```shellsession
$ python -m youtube_dl --ignore-config -v -F 'https://www.ndr.de/nachrichten/niedersachsen/oldenburg_ostfriesland/Hotelneubau-an-der-Strandpromenade-Wangerooger-sagen-Nein,wangerooge608.html'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--ignore-config', u'-v', u'-F', u'https://www.ndr.de/nachrichten/niedersachsen/oldenburg_ostfriesland/Hotelneubau-an-der-Strandpromenade-Wangerooger-sagen-Nein,wangerooge608.html']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Git HEAD: cc179df34
[debug] Python version 2.7.17 (CPython) - Linux-4.4.0-210-generic-i686-with-Ubuntu-16.04-xenial
[debug] exe versions: avconv 4.3, avprobe 4.3, ffmpeg 4.3, ffprobe 4.3
[debug] Proxy map: {}
[ndr] Hotelneubau-an-der-Strandpromenade-Wangerooger-sagen-Nein: Downloading webpage
[ndr:embed] wangerooge614: Downloading JSON metadata
[ndr:embed] wangerooge614: Downloading f4m manifest
WARNING: Unable to download f4m manifest: HTTP Error 400: Bad Request
[ndr:embed] wangerooge614: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 502: Bad Gateway
[info] Available formats for wangerooge614:
format code  extension  resolution note
l            mp4        unknown    
xl           mp4        unknown    (best)
$
```
A pending PR behaves the same.

**Comment by gamer191** [comment]
@dirkf see #21

**Comment by dirkf** [comment]
Different but the same, I think. In this case, the target JSON URL is valid but its JSON doesn't have the `._mediaArray[0]._mediaStreamArray` member that is being sought. It would be fixed by the yt-dl PR by finding the `sophoraID`; the `ld+json` as above actually has a playable URL that the yt-dl code would ignore, using it just for additional metadata.

**Comment by M1Aston** [comment]
After the latest update, video seems to be working perfectly now.
However. audio doesn't.
Example: https://www.ndr.de/nachrichten/hamburg/Gruenes-Kerosin-fuer-Flugzeuge-Produktion-in-Hamburg-geplant,treibstoff100.html



C:\WINDOWS\system32>"C:\Users\a\Desktop\MPC-BE\yt-dlp.exe" https://www.ndr.de/nachrichten/hamburg/Gruenes-Kerosin-fuer-Flugzeuge-Produktion-in-Hamburg-geplant,treibstoff100.html
[ndr] Gruenes-Kerosin-fuer-Flugzeuge-Produktion-in-Hamburg-geplant: Downloading webpage
[ndr:embed] treibstoff100: Downloading JSON metadata
ERROR: [ndr:embed] treibstoff100: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

**Comment by M1Aston** [comment]
Still some problems. Not with all videos on NDR, but some still don't work.



[debug] Command-line config: ['-vU', 'https://www.ndr.de/nachrichten/info/Teures-Brennholz-Diebe-auf-Beutezug-im-Wald,ndrinfo37112.html']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.10.04 [4e0511f] (win32_exe)
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1690 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.10.04, Current version: 2022.10.04
yt-dlp is up to date (2022.10.04)
[debug] [ndr] Extracting URL: https://www.ndr.de/nachrichten/info/Teures-Brennholz-Diebe-auf-Beutezug-im-Wald,ndrinfo37112.html
[ndr] Teures-Brennholz-Diebe-auf-Beutezug-im-Wald: Downloading webpage
[debug] [ndr:embed] Extracting URL: https://www.ndr.de/nachrichten/info/ndrinfo37112-ardplayer.html
[ndr:embed] ndrinfo37112: Downloading JSON metadata
ERROR: [ndr:embed] ndrinfo37112: Unable to download JSON metadata: HTTP Error 500: Internal Server Error (caused by <HTTPError 500: 'Internal Server Error'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 672, in extract
  File "yt_dlp\extractor\ndr.py", line 236, in _real_extract
  File "yt_dlp\extractor\common.py", line 1032, in download_content
  File "yt_dlp\extractor\common.py", line 996, in download_handle
  File "yt_dlp\extractor\common.py", line 866, in _download_webpage_handle
  File "yt_dlp\extractor\common.py", line 823, in _request_webpage

  File "yt_dlp\extractor\common.py", line 805, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 3682, in urlopen
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 563, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 755, in http_error_302
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 500: Internal Server Error
