### ISSUE TITLE
Unknown error occurred during API check (code -403) for some Bilibili videos

### ISSUE THREAD

**Issue by Dioxaz** [yt-dlp/yt-dlp#4071]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.05.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

Hello there. As usual with me, I'm posting because I can't find anything related anywhere and this is the first time I come across such error or problematic video. I was trying to download video mentioned in the output below (I own the original product, this is for an audio remastering project) but none of the tools I've tried to use (youtube-dl, you-get, annie or in this case yt-dlp) is able to download the video. I have no idea of what's happening for the moment. I also tried behind a VPN and the same things happens. The alternate URL (older Bilibili format) for that video is this one for the curious: http://www.bilibili.com/video/av2386757/

Unfortunately, I don't have any suggested solution so far. I'd like to understand why I have trouble download only this video and not others.

Here's the output:

### Verbose log

```shell
[debug] Command-line config: ['-vU', 'https://www.bilibili.com/video/BV17s411U7BF']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8 (No ANSI), error utf-8 (No ANSI), screen utf-8 (No ANSI)
[debug] yt-dlp version 2022.05.18 [b14d523] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-7-6.1.7601-SP1
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: ffmpeg -bsfs
[debug] exe versions: ffmpeg N-89369-g5a93a85fd0, ffprobe N-89369-g5a93a85fd0
[debug] Optional libraries: Cryptodome-3.14.1, brotli-1.0.9, certifi-2021.10.08, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
Latest version: 2022.05.18, Current version: 2022.05.18
yt-dlp is up to date (2022.05.18)
[debug] [BiliBili] Extracting URL: https://www.bilibili.com/video/BV17s411U7BF
[BiliBili] 17s411U7BF: Grabbing original ID via API
ERROR: [BiliBili] 17s411U7BF: Unknown error occurred during API check (code -403)
```

**Comment by pukkandan** [comment]
```
❯ yt-dlp -v https://www.bilibili.com/video/BV17s411U7BF
[debug] Command-line config: ['--ignore-config', '-v', 'https://www.bilibili.com/video/BV17s411U7BF']
[debug] Encodings: locale cp65001, fs utf-8, pref cp65001, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.05.18 [b14d52355] (source)
[debug] Lazy loading extractors is disabled
[debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
[debug] Git HEAD: 83f448508
[debug] Python version 3.10.4 (CPython 64bit) - Windows-10-10.0.22000-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg N-106550-g072101bd52-20220410 (fdk,setts), ffprobe N-106624-g391ce570c8-20220415, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.14.1, brotli-1.0.9, certifi-2021.10.08, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.1
[debug] Proxy map: {}
[debug] [BiliBili] Extracting URL: https://www.bilibili.com/video/BV17s411U7BF
[BiliBili] 17s411U7BF: Grabbing original ID via API
ERROR: [BiliBili] 17s411U7BF: Unknown error occurred during API check (code -403)
  File "D:\Programs\Source\yt-dlp\yt-dlp\yt_dlp\extractor\common.py", line 642, in extract
    ie_result = self._real_extract(url)
  File "D:\Programs\Source\yt-dlp\yt-dlp\yt_dlp\extractor\bilibili.py", line 159, in _real_extract
    av_id, bv_id = self._get_video_id_set(video_id, mobj.group('id_bv') is not None)
  File "D:\Programs\Source\yt-dlp\yt-dlp\yt_dlp\extractor\bilibili.py", line 409, in _get_video_id_set
    raise ExtractorError(f'Unknown error occurred during API check (code {response["code"]})',
```

**Comment by Dioxaz** [comment]
Little update. It looks like the video in question is only "private" and not deleted. It looks like it can only be watched when logged in (I couldn't access the video when logged out, getting the typical "视频不见了，你可以试试" error page). So I will try to download it with a cookie.txt file see what will happen.

**Comment by Dioxaz** [comment]
Another update. I've tried to feed yt-dlp a cookie file exported in Netscape HTTP cookie format and got the same exact error:

```[debug] Command-line config: ['-v', '--cookies', 'cookies_bilibili.txt', 'https://www.bilibili.com/video/BV17s411U7BF']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8 (No ANSI), error utf-8 (No ANSI), screen utf-8 (No ANSI)
[debug] yt-dlp version 2022.05.18 [b14d523] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-7-6.1.7601-SP1
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: ffmpeg -bsfs
[debug] exe versions: ffmpeg N-89369-g5a93a85fd0, ffprobe N-89369-g5a93a85fd0
[debug] Optional libraries: Cryptodome-3.14.1, brotli-1.0.9, certifi-2021.10.08, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] [BiliBili] Extracting URL: https://www.bilibili.com/video/BV17s411U7BF
[BiliBili] 17s411U7BF: Grabbing original ID via API
ERROR: [BiliBili] 17s411U7BF: Unknown error occurred during API check (code -403)
  File "yt_dlp\extractor\common.py", line 642, in extract
  File "yt_dlp\extractor\bilibili.py", line 159, in _real_extract
  File "yt_dlp\extractor\bilibili.py", line 409, in _get_video_id_set

But! I managed to download the file successfully with the same exact cookie file using an older build of youtube-dl. So what cookie format does yt-dlp expect?

By the way, this is the first time I come across a video only watchable when logged in.

**Comment by lockmatrix** [comment]
https://github.com/yt-dlp/yt-dlp/pull/4221 fix this, 
by remove this API call (https://github.com/yt-dlp/yt-dlp/pull/4221/commits/356e214174f910c31d0257bd563ceb170ec643ff)
