### ISSUE TITLE
24syv.dk

### ISSUE THREAD

**Issue by ole-tange** [yt-dlp/yt-dlp#4077]
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.05.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Denmark

### Example URLs

https://24syv.dk/episode/isabella-arendt-stiller-op-for-de-konservative-2

### Description

Should download: 

curl 'https://d1bxy2pveef3fq.cloudfront.net/episodes/original/37010239?episode_id=50183310&show_id=5196630&user_id=12256190&organization_id=472&tenant=SPREAKER&timestamp=1655322989&media_type=static&Expires=1655582189&Key-Pair-Id=K2KSORR5FSJ5FK&Signature=mqm1lsgz~acjuBkgu4xcQX9DGc6WyOumgFefRpu5pIS8xHGF03gIcVvw-2QJa3SyWqUtQbsSSSjyKNXymX0DV-6V2DyMhy~w5Rco-EzjOyNfpP1Th1FPH6vVGcuRhJikHZ3X3mIKoBlo84pEZKq1yZ0pD5bkb0VbKadaR9CXb0ALa4FGJr3lwOLU7RMe7nBqhf-GEiMwTNhGVdY99bGJy34AXPYUjg4ZrMqigtxdYosro1S42YhyUabNDBnNJ-T5CmmXrcDM6kxFH1EIE~s5~9euxz~n51KNw4iyaL6K5BhIorA7JvA9azYRK4wMJTAz3TqfiwQoPMT-2OUaeVr-KA__' -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:101.0) Gecko/20100101 Firefox/101.0' -H 'Accept: audio/webm,audio/ogg,audio/wav,audio/*;q=0.9,application/ogg;q=0.7,video/*;q=0.6,*/*;q=0.5' -H 'Accept-Language: en-US,en;q=0.5' -H 'Accept-Encoding: gzip, deflate, br' -H 'Range: bytes=0-' -H 'Referer: https://24syv.dk/' -H 'Connection: keep-alive' -H 'Sec-Fetch-Dest: audio' -H 'Sec-Fetch-Mode: no-cors' -H 'Sec-Fetch-Site: cross-site' -H 'DNT: 1' -H 'Sec-GPC: 1' -H 'Pragma: no-cache' -H 'Cache-Control: no-cache' -H 'TE: trailers'

### Verbose log

```shell
$ yt-dlp -vU 'https://24syv.dk/episode/isabella-arendt-stiller-op-for-de-konservative-2'
[debug] Command-line config: ['-vU', 'https://24syv.dk/episode/isabella-arendt-stiller-op-for-de-konservative-2']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.05.18 [b14d52355] (zip)
[debug] Python version 3.10.4 (CPython 64bit) - Linux-5.15.0-33-generic-x86_64-with-glibc2.35
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: ffmpeg -bsfs
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2
[debug] Optional libraries: brotli-1.0.9, certifi-2020.06.20, pyxattr-0.7.2, secretstorage-3.3.1, sqlite3-2.6.0
[debug] Proxy map: {}
Latest version: 2022.05.18, Current version: 2022.05.18
yt-dlp is up to date (2022.05.18)
[debug] [generic] Extracting URL: https://24syv.dk/episode/isabella-arendt-stiller-op-for-de-konservative-2
[generic] isabella-arendt-stiller-op-for-de-konservative-2: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] isabella-arendt-stiller-op-for-de-konservative-2: Downloading webpage
[generic] isabella-arendt-stiller-op-for-de-konservative-2: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://24syv.dk/episode/isabella-arendt-stiller-op-for-de-konservative-2
Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1395, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1465, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 642, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/generic.py", line 4031, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://24syv.dk/episode/isabella-arendt-stiller-op-for-de-konservative-2
```

**Comment by HobbyistDev** [comment]
From this url (https://24syv.dk/episode/isabella-arendt-stiller-op-for-de-konservative-2), i get the json data from webpage ( in `__NEXT_DATA__`) and then we can get `enclosure` from `['props']['pageProps']['episodeDetails']['details']` and then we can download this with downloader

Here's the json in `details`:
```json
"details": {
    "ID": 12215,
    "post_content": "Isabella Arendt stiller op for De Konservative",
    "post_title": "Tidligere formand for Kristendemokraterne Isabella Arendt stiller op til folketingsvalget for Det Konservative Folkeparti. Men hvorfor netop de konservative? og hvordan harmonisere det med hendes ønske om en mere human udlændinge- og integrationspolitikken.  Hun er med fra start og fortæller hvorfor. \u003cbr /\u003e\u003cbr /\u003eVi har også LOKK - Landsorganisation af Kvindekrisecentre’s formand Karin Gaardsted i programmet. Vi får talt om handleplanen mod partnerdrab. Og om der behov for at ændre den generelle samtale om vold i nære relationer og kvindedrab.",
    "slug": "isabella-arendt-stiller-op-for-de-konservative-2",
    "episode_id": "50183310",
    "publication_date": "1655121723",
    "image_url": "https://d1bm3dmew779uf.cloudfront.net/rss/show/5196630/4ceb292fd51c555feb652edfdf7291ed.png",
    "enclosure": "https://chtbl.com/track/GFDE3G/api.spreaker.com/download/episode/50183310/isabella.mp3",
    "duration": "3218",
    "episode_author": "24syv",
    "podcast_id": "380",
    "show_id": "5196630"
}
```
I hope this can help the dev. 

PS: I don't check other sites, so feel free to correct me if i'm wrong

**Comment by pukkandan** [comment]
Many sites that use `__NEXT_DATA__` have similar code, but the name of the keys are are slightly different from each other. Wonder if there is a way way to generalize them into `GenericIE`
