### ISSUE TITLE
Steam Live Stream

### ISSUE THREAD

**Issue by guillaumesoucy94** [yt-dlp/yt-dlp#4083]
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.05.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Canada

### Example URLs

https://steamcommunity.com/broadcast/watch/76561198373527746

### Description

Hello, 

Could you please add support for Steam live streams?

Please note that the provided content at this URL: https://steamcommunity.com/broadcast/watch/76561198373527746 is a live stream and will probably not available for an undefined period of time. 

I'd look on the Issues section and Pull Requests and I wasn't able to find anything. 

Best regards, 

Guillaume

### Verbose log

```shell
root@livestream-dc:/mnt/disk/livestream# yt-dlp https://steamcommunity.com/broadcast/watch/76561198373527746
[generic] 76561198373527746: Requesting header
WARNING: [generic] Could not send HEAD request to https://steamcommunity.com/broadcast/watch/76561198373527746: HTTP Error 503: Service Unavailable
[generic] 76561198373527746: Downloading webpage
WARNING: [generic] Falling back on generic information extractor.
[generic] 76561198373527746: Extracting information
ERROR: Unsupported URL: https://steamcommunity.com/broadcast/watch/76561198373527746
root@livestream-dc:/mnt/disk/livestream#
```

**Comment by HobbyistDev** [comment]
From your link, i found the url from `https://steamcommunity.com/broadcast/getbroadcastmpd/?steamid=76561198373527746`. I think the `steamid` is the `id` in the url. We can get `url` and `hls_url` from there.

Here's the log:
```
(python_proj2) D:\user\Computer\python_proj\python_proj2\yt-dlp>curl "https://steamcommunity.com/broadcast/getbroadcastmpd/?steamid=76561198373527746" | jq
  % Total    % Received % Xferd  Average Speed   T
i(python_proj2) D:\user\Computer\python_proj\python_proj2\yt-dlp>mC:\Users\USER\Downloads\jq_file\jq-win64.exe
e    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   740  100   740    0     0    922      0 --:--:-- --:--:-- --:--:--   925
{
  "success": "ready",
  "retry": 0,
  "broadcastid": "3550491766225840735",
  "eresult": 1,
  "url": "https://steambroadcast.akamaized.net/broadcast/76561198373527746/6306454638476489979/manifest/0/steambroadcast.akamaized.net/?broadcast_origin=repo-01-ord1.broadcast.steamcontent.com:80",
  "viewertoken": "2180820111620473797",
  "hls_url": "https://steambroadcast.akamaized.net/broadcast/76561198373527746/6306454638476489979/hls_manifest/0/steambroadcast.akamaized.net/master.m3u8?broadcast_origin=repo-01-ord1.broadcast.steamcontent.com:80",
  "heartbeat_interval": 30,
  "is_rtmp": 1,
  "title": "",
  "num_viewers": 522,
  "is_webrtc": null,
  "webrtc_session_id": null,
  "webrtc_offer_sdp": null,
  "webrtc_turn_server": null,
  "is_replay": 0,
  "cdn_auth_url_parameters": null
}
```

**Comment by guillaumesoucy94** [comment]
I thing its working 

`root@livevideo-dc:/mnt/disk/steam# yt-dlp https://steambroadcast.akamaized.net/broadcast/76561198373527746/6306454638476489979/hls_manifest/0/steambroadcast.akamaized.net/master.m3u8?broadcast_origin=repo-01-ord1.broadcast.steamcontent.com:80
[generic] master.m3u8?broadcast_origin=repo-01-ord1.broadcast.steamcontent: Requesting header
[generic] master.m3u8?broadcast_origin=repo-01-ord1.broadcast.steamcontent: Downloading m3u8 information
[info] master.m3u8?broadcast_origin=repo-01-ord1.broadcast.steamcontent: Downloading 1 format(s): 7187+aac-Default
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 64
[download] Destination: master [master.m3u8broadcast_origin=repo-01-ord1.broadcast.steamcontent].f7187.mp4
[download]  27.6% of ~89.29MiB at  2.66MiB/s ETA 00:23 (frag 17/64)^C
ERROR: Interrupted by user
root@livevideo-dc:/mnt/disk/steam#`

(I'd stop it).

However, I was needed to verify if the resulting file is playable and yes it is but can't move in the file, I'd record for about 32 seconds and the video player is showing this: 

![Steam Rec Example 001](https://user-images.githubusercontent.com/22561876/174302910-26e26608-1953-424b-b872-204f9bd3caa7.png)

Knowing the content is actually a live feed, it is probably normal because it don't have the beginning of the content. Can you please correct me if I"m wrong? ;-)
