### ISSUE TITLE
disney+ israel

### ISSUE THREAD

**Issue by D00oo00M** [yt-dlp/yt-dlp#4088]
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.05.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Israel

### Example URLs

https://hsesn.apps.disneyplus.com/hses25/videos/hotstarint/v3/1260091751/1649323907984/52c00cab79ea700623db005b11805403/master-15dca5f176-1655295670-tv.mpd?hdnea=st=1655368830~exp=1655369430~data=ip%3dgGH9JxQzDQihx5x8xwsmdqIQE2i0N0jzjkyTrGMSOF3zjm3p8jjJNoC-userid%3d42wy5EhQ5fEuBKrgqBER2WQ5EiQvTr5SLbwoz7KOO7Ms-did%3dGUc5x359uHtHudzJVuo3KYqImH0sSRldD1kwLtOoAHE2KDiubv6u9m8-cc%3dil-~hmac=65fd62a2a13fac069ee163f687b53cd34f77b22dfae9e8fad56a8eadc47ae51b&ttl=1800&type=paid

### Description

when i try to download this mpd
https://hsesn.apps.disneyplus.com/hses25/videos/hotstarint/v3/1260091751/1649323907984/52c00cab79ea700623db005b11805403/master-15dca5f176-1655295670-tv.mpd?hdnea=st=1655368830~exp=1655369430~data=ip%3dgGH9JxQzDQihx5x8xwsmdqIQE2i0N0jzjkyTrGMSOF3zjm3p8jjJNoC-userid%3d42wy5EhQ5fEuBKrgqBER2WQ5EiQvTr5SLbwoz7KOO7Ms-did%3dGUc5x359uHtHudzJVuo3KYqImH0sSRldD1kwLtOoAHE2KDiubv6u9m8-cc%3dil-~hmac=65fd62a2a13fac069ee163f687b53cd34f77b22dfae9e8fad56a8eadc47ae51b&ttl=1800&type=paid
i got error
ERROR: [generic] Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>)

i know this is drm stream i need to download the video and audio
any help?

### Verbose log

```shell
[debug] Encodings: locale cp1255, fs utf-8, pref cp1255, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.05.18 [b14d523] (win_exe)
[debug] Python version 3.7.9 (CPython 32bit) - Windows-10-10.0.19041-SP0
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: avprobe -bsfs
[debug] Checking exe version: ffmpeg -bsfs
[debug] exe versions: ffmpeg 4.3.2-2021-02-27-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.14.1, brotli-1.0.9, certifi-2021.10.08, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] [generic] Extracting URL: https://hsesn.apps.disneyplus.com/hses25/videos/hotstarint/v3/1260091751/1649323907984/52c00cab79ea700623db005b11805403/master-15dca5f176-1655295670-tv.mpd?hdnea=st=1655368830~exp=1655369430~data=ip%3dgGH9JxQzDQihx5x8xwsmdqIQE2i0N0jzjkyTrGMSOF3zjm3p8jjJNoC-userid%3d42wy5EhQ5fEuBKrgqBER2WQ5EiQvTr5SLbwoz7KOO7Ms-did%3dGUc5x359uHtHudzJVuo3KYqImH0sSRldD1kwLtOoAHE2KDiubv6u9m8-cc%3dil-~hmac=65fd62a2a13fac069ee163f687b53cd34f77b22dfae9e8fad56a8eadc47ae51b
[generic] master-15dca5f176-1655295670-tv: Requesting header
WARNING: [generic] Could not send HEAD request to https://hsesn.apps.disneyplus.com/hses25/videos/hotstarint/v3/1260091751/1649323907984/52c00cab79ea700623db005b11805403/master-15dca5f176-1655295670-tv.mpd?hdnea=st=1655368830~exp=1655369430~data=ip%3dgGH9JxQzDQihx5x8xwsmdqIQE2i0N0jzjkyTrGMSOF3zjm3p8jjJNoC-userid%3d42wy5EhQ5fEuBKrgqBER2WQ5EiQvTr5SLbwoz7KOO7Ms-did%3dGUc5x359uHtHudzJVuo3KYqImH0sSRldD1kwLtOoAHE2KDiubv6u9m8-cc%3dil-~hmac=65fd62a2a13fac069ee163f687b53cd34f77b22dfae9e8fad56a8eadc47ae51b: HTTP Error 403: Forbidden
```

**Comment by HobbyistDev** [comment]
> i know this is drm stream i need to download the video and audio

Do you know any non-drm content ? if not, it will not added (see https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy)

**Comment by D00oo00M** [comment]
its drm i got the keys. i need to download the files to decrypt it...
