### ISSUE TITLE
Not a list of available for help(yt_dlp.postprocessor) or help(yt_dlp.postprocessor.PostProcessor)

### ISSUE THREAD

**Issue by lionderful** [yt-dlp/yt-dlp#4089]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.05.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

My code:

import yt_dlp
help(yt_dlp.postprocessor)
help(yt_dlp.postprocessor.PostProcessor)

My output:
Help on package yt_dlp.postprocessor in yt_dlp:

NAME
    yt_dlp.postprocessor - # flake8: noqa: F401

PACKAGE CONTENTS
    common
    embedthumbnail
    exec
    ffmpeg
    metadataparser
    modify_chapters
    movefilesafterdownload
    sponskrub
    sponsorblock
    xattrpp

CLASSES
    builtins.object
        yt_dlp.postprocessor.common.PostProcessor
            yt_dlp.postprocessor.exec.ExecPP
                yt_dlp.postprocessor.exec.ExecAfterDownloadPP
            yt_dlp.postprocessor.ffmpeg.FFmpegPostProcessor
                yt_dlp.postprocessor.embedthumbnail.EmbedThumbnailPP

### Verbose log

```shell
[debug] Command-line config: ['-vU', 'help(yt_dlp.postprocessor)']
[debug] Encodings: locale cp936, fs utf-8, pref cp936, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.05.18 [b14d52355]
[debug] Lazy loading extractors is disabled
[debug] Python version 3.9.13 (CPython 64bit) - Windows-10-10.0.22000-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 2022-04-03-git-1291568c98-full_build-www.gyan.dev (setts), ffprobe 2022-04-03-git-1291568c98-full_build-www.gyan.dev
```

**Comment by pukkandan** [comment]
I don't understand what the bug you are trying to report is

**Comment by fxavierho123** [comment]
It seems you just need to install the master bench version, it fixed many of the `help()` function.
`python3 -m pip install --force-reinstall https://github.com/yt-dlp/yt-dlp/archive/master.tar.gz`

**Comment by AnnanFay** [comment]
Is there a way to see this output without installing through python?

I'll probably install it, but feels like something that should also have a doc page somewhere. Don't most people just use the exe?

**Comment by bashonly** [comment]
That line in the main readme is from the embedding examples, which are only relevant if you are using the Python API
