### ISSUE TITLE
[Question] - Information on Adding Provider Login to Existing Extractor

### ISSUE THREAD

**Issue by timethrow** [yt-dlp/yt-dlp#409]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

I'm looking to add support for logging in with a TV Provider to a particular extractor, so we don't have to use cookies as the cookies have a very short life. I have looked at a few other extractors that I now use this, but i'm not quite sure I understand how it works, so that I can try and implement it.

Does anyone have some information on this, or some pointers that may be of use?

**Comment by pukkandan** [comment]
You have to make a `_real_initialize` that gets the user/pass with `self._get_login_info()` and then perform whatever requests are needed for auth. If you need to save some kind of toke, it can be put in `self._auth_token` for example. Or, if only cookies are needed, yt-dlp automatically keeps the cookies for use in future requests

Search the extractors for `_get_login_info` to see example implementations

> I'm looking to add support for logging in with a TV Provider to a particular extractor

If you mean an AdobePass MSO, it's implementation is different. See `AdobePassIE._extract_mvpd_auth`

**Comment by timethrow** [comment]
Thanks, the `AdobePassIE._extract_mvpd_auth` seems to be what I need here.
