### ISSUE TITLE
Extract the comments count for any YouTube Video.

### ISSUE THREAD

**Issue by MrBotDeveloper** [yt-dlp/yt-dlp#4091]
### Checklist

- [X] I'm requesting a site-specific feature
- [X] I've verified that I'm running yt-dlp version **2022.05.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

India

### Example URLs

https://www.youtube.com/watch?v=BaW_jenozKc

### Description

Kindly also provide the **comments count** on any YouTube Video which is currently not provided by `yt-dlp`.

### Verbose log

```shell
[debug] Command-line config: ['-vU', 'https://www.youtube.com/watch?v=BaW_jenozKc', '--skip-download', '--write-info-json']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.05.18 [b14d52355]
[debug] Python version 3.9.11 (CPython 64bit) - Linux-4.4.0-1104-aws-x86_64-with-glibc2.31
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: avprobe -bsfs
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: avconv -bsfs
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.14.1, brotli-None, certifi-2021.10.08, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
Latest version: 2022.05.18, Current version: 2022.05.18
yt-dlp is up to date (2022.05.18)
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=BaW_jenozKc
[youtube] BaW_jenozKc: Downloading webpage
[youtube] BaW_jenozKc: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[debug] Default format spec: best/bestvideo+bestaudio
[info] BaW_jenozKc: Downloading 1 format(s): 22
[info] Writing video metadata as JSON to: youtube-dl test video ''_ä↭𝕐 [BaW_jenozKc].info.json
```

**Comment by pukkandan** [comment]
To get comment count, you need to use `--write-comments`

**Comment by pukkandan** [comment]
Actually, the webpage shows the comment count (not sure how accurate it is), which we can extract without --write-comments

**Comment by MrBotDeveloper** [comment]
No, I think the webpage almost every time shows the accurate number of comments (not the reply threads). So, add that comments count with the info json would be better. It only shows incorrect counts in the case of huge amount of comments at a time.

**Comment by MrBotDeveloper** [comment]
Like if anyone just wants the comments count of a video with high number of comments, using `--write-comments` will take much of time and memory.
