### ISSUE TITLE
Is there a way to print each --print option  separately

### ISSUE THREAD

**Issue by acoolstraw** [yt-dlp/yt-dlp#4094]
### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Question

Is there a way to print each `--print` option (e.g. title, description) separately, or rather, in a parsable way, without repeating the yt-dlp command?

**Comment by pukkandan** [comment]
```
-O, --print [WHEN:]TEMPLATE     ...
                                This option can be used multiple times
```

**Comment by acoolstraw** [comment]
I am aware, but what about separating them? Multiple strings of text aren't useful if you can't distinguish what's what

**Comment by pukkandan** [comment]
They are separated by a newline. Or, you can make a print some delimiter, make a json from them, etc based on what is easy for you to parse
Examples:
```
❯ yt-dlp test:youtube -O title -O description
youtube-dl test video "'/\ä↭𝕐
test chars:  "'/\ä↭𝕐
test URL: https://github.com/rg3/youtube-dl/issues/1892

This is a test video for youtube-dl.

For more information, contact phihag@phihag.de .

❯ yt-dlp test:youtube -O title= -O description=
title = 'youtube-dl test video "\'/\\ä↭𝕐'
description = 'test chars:  "\'/\\ä↭𝕐\ntest URL: https://github.com/rg3/youtube-dl/issues/1892\n\nThis is a test video for youtube-dl.\n\nFor more information, contact phihag@phihag.de .'

❯ yt-dlp test:youtube -O title -O ---- -O description
youtube-dl test video "'/\ä↭𝕐
----
test chars:  "'/\ä↭𝕐
test URL: https://github.com/rg3/youtube-dl/issues/1892

This is a test video for youtube-dl.

For more information, contact phihag@phihag.de .

❯ yt-dlp test:youtube -O "{\"title\": %(title)j, \"description\": %(description)j}"
{"title": "youtube-dl test video \"'/\\\u00e4\u21ad\ud835\udd50", "description": "test chars:  \"'/\\\u00e4\u21ad\ud835\udd50\ntest URL: https://github.com/rg3/youtube-dl/issues/1892\n\nThis is a test video for youtube-dl.\n\nFor more information, contact phihag@phihag.de ."}
```

**Comment by pukkandan** [comment]
or just parse it from `-j` output tbh

**Comment by acoolstraw** [comment]
There is no bandwidth difference, it uses the same amount regardless, right?

**Comment by pukkandan** [comment]
Yes

**Comment by acoolstraw** [comment]
Alright, thank you!
