### ISSUE TITLE
A working example for --use-postprocessor

### ISSUE THREAD

**Issue by marcello-pietrobon** [yt-dlp/yt-dlp#4095]
### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Question

Hello,

while waiting for the proper documentation, see [Add "postprocessing" section to readme #2766](https://github.com/yt-dlp/yt-dlp/issues/2766),  I need a working example for using the `--use-postprocessor` option but it's not clear to me what should I do.

I tried to go around this lack of knowledge on my side by doing it as follows (this is  a partial code, but I believe it should be clear the intent):

    def pre_process_test(info_dict):
        print('this is a postprocess_test')
        return

    def before_dl_test(info_dict):
        print('this is a postprocess_test')
        return

    def post_process_test(info_dict):
        print('this is a postprocess_test')
        return

    def download_video(ydl_opts, urls):
        try:
            ydl_opts['pre_process'] = [pre_process_test]
            ydl_opts['before_dl'] = [before_dl_test]
            ydl_opts['post_process'] = [post_process_test]

            with yt_dlp.YoutubeDL(ydl_opts) as ydl:
                ydl.download(urls)
        except BaseException as e:
            raise
        finally:
            pass

but it doesn't work,

What is the correct syntax to be used?

**Comment by pukkandan** [comment]
> this is a partial code, but I believe it should be clear the intent

Nope, no clue what you are trying to do or how it is related to the CLI option `--use-postprocessor`.

If you are trying to add custom PPs, see https://github.com/yt-dlp/yt-dlp#add-a-custom-postprocessor

**Comment by pukkandan** [comment]
Or, if you are trying to add hooks, see https://github.com/yt-dlp/yt-dlp#adding-logger-and-progress-hook

**Comment by marcello-pietrobon** [comment]
Thank you,

I thought to use that example, but I guess by the name that I'll be able to run a custom code only at the end of the entire ydl.download(urls) routine for each url in the list.

Yet I'm understanding that I can run some custom code in some crucial part of the code, and exactly
pre_process, after_filter, before_dl, after_move, post_process, after_video, playlist

Is that possible and what syntax should I use for it? Just a single working example, for example 'before_dl', would be what I'm looking for. Thanks.

**Comment by pukkandan** [comment]
In the example, just change
```diff
-     ydl.add_post_processor(MyCustomPP())
+     ydl.add_post_processor(MyCustomPP(), when='before_dl')
```

**Comment by marcello-pietrobon** [comment]
So simple?
How beautiful. It works :)

**Comment by marcello-pietrobon** [comment]
> In the example, just change
> 
> ```diff
> -     ydl.add_post_processor(MyCustomPP())
> +     ydl.add_post_processor(MyCustomPP(), when='before_dl')
> ```

I'd suggest to place this change also in the documentation of 
https://github.com/yt-dlp/yt-dlp#add-a-custom-postprocessor ,
to me it would have saved at least a day of reading and analysis.

Thank you for the help.

**Comment by franksodre** [comment]
How is that in the CLI? I'm trying to printout the filepaths of the downloaded files.

**Comment by InvalidUsernameException** [comment]
@franksodre Please don't necro-post on old issues. Open a new issue or [ask on Discord](https://discord.gg/H5MNcFW63r).
