### ISSUE TITLE
Cancel download in code

### ISSUE THREAD

**Issue by ElissonRodrigues** [yt-dlp/yt-dlp#4103]
### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Question

```python
from yt_dlp import YoutubeDL

ydl = YoutubeDL({
		"no_warnings": True, 
		"quiet": True,
		"skip_download": True, 
		"nocheckcertificate": True, 
		"noplaylist": True, 
		"nocheckcertificate": True,
		"no_color": True,
		 "socket_timeout": 11,
		}
	)
ydl.add_progress_hook(self.progress_hooks)
ydl.download([self.url])
```

I'm using yt-dlp in my code like this. I would like to know if it is possible to cancel this download (interrupt when necessary)?

**Comment by pukkandan** [comment]
You can raise a `utils.DownloadCancelled` error in the progress hook

**Comment by ElissonRodrigues** [comment]
> You can raise a `utils.DownloadCancelled` error in the progress hook

Worked, thank you.
