### ISSUE TITLE
Embedded Vimeo video 404 error failed retries fragment not found

### ISSUE THREAD

**Issue by djrbos** [yt-dlp/yt-dlp#4108]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.05.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

usa

### Description

I made this account just to report this, i looked for a solution but can't seem to find one. I've always been able to download from this site using the link to the master.json file untill today. I've also tried this on 2 different systems (destop and laptop; win7 & win10) with and without vpn, same result. 

Trying to download an embedded vimeo video from the same site i have every week for the last few months, it's been working fine on the latest version up till today. I tried using cookies file and i tried using login credentials and both together but neither worked.
I attached the log, but canceled it after a few fragments, it will run to completion and make an mp4 file that has the first fragment of a few seconds but that is all. 

### Verbose log

```shell
C:\youtube-dl>yt-dlp -vU https://17vod-adaptive.akamaized.net/exp=1655604193~acl
=%2F237cf77f-cee6-4ef6-9e8e-043e6c701ab0%2F%2A~hmac=03fa989a0359f8b2a4066889961b
14f0b9d842183b9653a8569dec14cd1cfed6/237cf77f-cee6-4ef6-9e8e-043e6c701ab0/video/
74484e5e,e0e398e3,13983fbb,cba0091d,0ea30f4d/master.m3u8
[debug] Command-line config: ['-vU', 'https://17vod-adaptive.akamaized.net/exp=1
655604193~acl=%2F237cf77f-cee6-4ef6-9e8e-043e6c701ab0%2F%2A~hmac=03fa989a0359f8b
2a4066889961b14f0b9d842183b9653a8569dec14cd1cfed6/237cf77f-cee6-4ef6-9e8e-043e6c
701ab0/video/74484e5e,e0e398e3,13983fbb,cba0091d,0ea30f4d/master.m3u8']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8 (No ANSI), er
ror utf-8 (No ANSI), screen utf-8 (No ANSI)
[debug] yt-dlp version 2022.05.18 [b14d523] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-7-6.1.7601-SP1
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: avprobe -bsfs
[debug] Checking exe version: ffmpeg -bsfs
[debug] exe versions: ffmpeg n4.4.1-14-g5a7763bdfa-20220109 (setts)
[debug] Optional libraries: Cryptodome-3.14.1, brotli-1.0.9, certifi-2021.10.08,
 mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
Latest version: 2022.05.18, Current version: 2022.05.18
yt-dlp is up to date (2022.05.18)
[debug] [generic] Extracting URL: https://17vod-adaptive.akamaized.net/exp=16556
04193~acl=%2F237cf77f-cee6-4ef6-9e8e-043e6c701ab0%2F%2A~hmac=03fa989a0359f8b2a40
66889961b14f0b9d842183b9653a8569dec14cd1cfed6/237cf77f-cee6-4ef6-9e8e-043e6c701a
b0/video/74484e5e,e0e398e3,13983fbb,cba0091d,0ea30f4d/master.m3u8
[generic] master: Requesting header
[debug] Identified a direct video link
[generic] master: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7),
vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext,
aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] master: Downloading 1 format(s): 5249
[debug] Invoking hlsnative downloader on "https://17vod-adaptive.akamaized.net/e
xp=1655604193~acl=%2F237cf77f-cee6-4ef6-9e8e-043e6c701ab0%2F%2A~hmac=03fa989a035
9f8b2a4066889961b14f0b9d842183b9653a8569dec14cd1cfed6/237cf77f-cee6-4ef6-9e8e-04
3e6c701ab0/video/cba0091d/playlist.m3u8"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 918
[download] Destination: master [master].mp4
[debug] File locking is not supported on this platform. Proceeding without locki
ng
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 2
 (attempt 1 of 10) ...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 2
 (attempt 2 of 10) ...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 2
 (attempt 3 of 10) ...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 2
 (attempt 4 of 10) ...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 2
 (attempt 5 of 10) ...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 2
 (attempt 6 of 10) ...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 2
 (attempt 7 of 10) ...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 2
 (attempt 8 of 10) ...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 2
 (attempt 9 of 10) ...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 2
 (attempt 10 of 10) ...
[download] fragment not found; Skipping fragment 2 ...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 3
 (attempt 1 of 10) ...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 3
 (attempt 2 of 10) ...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 3
 (attempt 3 of 10) ...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 3
 (attempt 4 of 10) ...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 3
 (attempt 5 of 10) ...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 3
 (attempt 6 of 10) ...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 3
 (attempt 7 of 10) ...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 3
 (attempt 8 of 10) ...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 3
 (attempt 9 of 10) ...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 3
 (attempt 10 of 10) ...
[download] fragment not found; Skipping fragment 3 ...
.
.
and so on...
```

**Comment by pukkandan** [comment]
Provide verbose log with actual URL, not m3u8

**Comment by pukkandan** [comment]
Or, if you want to download with the m3u8, you are likely missing some headers. We can't help you find them

**Comment by djrbos** [comment]
Thanks for responding. 

Is the actually URL the one i trimmed and added .m3u8 to, its the one i found under network inspection in the master.json 

https://17vod-adaptive.akamaized.net/exp=1655610714~acl=/237cf77f-cee6-4ef6-9e8e-043e6c701ab0/*~hmac=b4c1994733467eb4b115a818e0a47977ed0527180a3f89666913285cd5fc19eb/237cf77f-cee6-4ef6-9e8e-043e6c701ab0/video/74484e5e,e0e398e3,13983fbb,cba0091d,0ea30f4d/master.json?query_string_ranges=1&base64_init=1

As for headers, i'm at a loss on that, never used them and not sure how to, is there an example you could point me to.

**Comment by pukkandan** [comment]
I mean the URL of the webpage!

**Comment by djrbos** [comment]
This is what I got

C:\youtube-dl>yt-dlp -uV https://dlc.tokyo/live/ls0618/
Type account password and press [Return]:
[generic] ls0618: Requesting header
WARNING: [generic] Falling back on generic information
[generic] ls0618: Downloading webpage
[generic] ls0618: Extracting information
ERROR: Unsupported URL: https://dlc.tokyo/live/ls0618/

**Comment by pukkandan** [comment]
There is no video on that page! Maybe there is one behind the paywall, but obv I can't access that - and neither can yt-dlp unless you atleast pass `--cookies`

> As for headers, i'm at a loss on that, never used them and not sure how to, is there an example you could point me to.

See:
https://www.reddit.com/r/youtubedl/wiki/errors-403forbidden 
https://www.reddit.com/r/youtubedl/wiki/cookies 
https://www.reddit.com/r/youtubedl/wiki/howdoidownloadembeddedvimeovideos

You can also try asking on the subreddit. But this is definitely not a valid bug report...

**Comment by djrbos** [comment]
Thanks for the info, but I tried cookies and several headers and still won't work. Could something have changed with Vimeo? This is a pay per view vimeo video that i have paid for and have access to. I can watch it fine. yt-dlp can access the master.json file and show me all the versions it even grabs the fist fragment like i mentioned but then cuts me off and sends 404 error.  I'm at a loss

**Comment by djrbos** [comment]
So today i tried using differnt links that end in .mp4, there are differnt liniks for each quality ie 240 504 720 1080 some of the lower res links worth out of the box, no headers no cookies, the higher res do not work with cookies or headers, in fact it says it can't send headers. 

First one is the 720p link, Second one is the 1080p link both fail, the last one is the 504p version and it works. 

C:\youtube-dl>yt-dlp --verbose https://17vod-adaptive.akamaized.net/exp=16557720
61~acl=%2F237cf77f-cee6-4ef6-9e8e-043e6c701ab0%2F%2A~hmac=ab26adba64ac7933551d96
d8396c8ccce2eb1fcd3455769fa6d1413b40f04d82/237cf77f-cee6-4ef6-9e8e-043e6c701ab0/
parcel/video/0ea30f4d.mp4
[debug] Command-line config: ['--verbose', 'https://17vod-adaptive.akamaized.net
/exp=1655772061~acl=%2F237cf77f-cee6-4ef6-9e8e-043e6c701ab0%2F%2A~hmac=ab26adba6
4ac7933551d96d8396c8ccce2eb1fcd3455769fa6d1413b40f04d82/237cf77f-cee6-4ef6-9e8e-
043e6c701ab0/parcel/video/0ea30f4d.mp4']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8 (No ANSI), er
ror utf-8 (No ANSI), screen utf-8 (No ANSI)
[debug] yt-dlp version 2022.05.18 [b14d523] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-7-6.1.7601-SP1
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: avprobe -bsfs
[debug] Checking exe version: ffmpeg -bsfs
[debug] exe versions: ffmpeg n4.4.1-14-g5a7763bdfa-20220109 (setts)
[debug] Optional libraries: Cryptodome-3.14.1, brotli-1.0.9, certifi-2021.10.08,
 mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] [generic] Extracting URL: https://17vod-adaptive.akamaized.net/exp=16557
72061~acl=%2F237cf77f-cee6-4ef6-9e8e-043e6c701ab0%2F%2A~hmac=ab26adba64ac7933551
d96d8396c8ccce2eb1fcd3455769fa6d1413b40f04d82/237cf77f-cee6-4ef6-9e8e-043e6c701a
b0/parcel/video/0ea30f4d.mp4
[generic] 0ea30f4d: Requesting header
WARNING: [generic] Could not send HEAD request to https://17vod-adaptive.akamaiz
ed.net/exp=1655772061~acl=%2F237cf77f-cee6-4ef6-9e8e-043e6c701ab0%2F%2A~hmac=ab2
6adba64ac7933551d96d8396c8ccce2eb1fcd3455769fa6d1413b40f04d82/237cf77f-cee6-4ef6
-9e8e-043e6c701ab0/parcel/video/0ea30f4d.mp4: HTTP Error 403: Forbidden
[generic] 0ea30f4d: Downloading webpage
ERROR: [generic] Unable to download webpage: HTTP Error 403: Forbidden (caused b
y <HTTPError 403: 'Forbidden'>); please report this issue on  https://github.com
/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm y
ou are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 642, in extract
  File "yt_dlp\extractor\generic.py", line 2737, in _real_extract
  File "yt_dlp\extractor\common.py", line 786, in _request_webpage

  File "yt_dlp\extractor\common.py", line 768, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 3596, in urlopen
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden


C:\youtube-dl>yt-dlp --verbose https://17vod-adaptive.akamaized.net/exp=16557720
61~acl=%2F237cf77f-cee6-4ef6-9e8e-043e6c701ab0%2F%2A~hmac=ab26adba64ac7933551d96
d8396c8ccce2eb1fcd3455769fa6d1413b40f04d82/237cf77f-cee6-4ef6-9e8e-043e6c701ab0/
parcel/video/cba0091d.mp4
[debug] Command-line config: ['--verbose', 'https://17vod-adaptive.akamaized.net
/exp=1655772061~acl=%2F237cf77f-cee6-4ef6-9e8e-043e6c701ab0%2F%2A~hmac=ab26adba6
4ac7933551d96d8396c8ccce2eb1fcd3455769fa6d1413b40f04d82/237cf77f-cee6-4ef6-9e8e-
043e6c701ab0/parcel/video/cba0091d.mp4']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8 (No ANSI), er
ror utf-8 (No ANSI), screen utf-8 (No ANSI)
[debug] yt-dlp version 2022.05.18 [b14d523] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-7-6.1.7601-SP1
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: avprobe -bsfs
[debug] Checking exe version: ffmpeg -bsfs
[debug] exe versions: ffmpeg n4.4.1-14-g5a7763bdfa-20220109 (setts)
[debug] Optional libraries: Cryptodome-3.14.1, brotli-1.0.9, certifi-2021.10.08,
 mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] [generic] Extracting URL: https://17vod-adaptive.akamaized.net/exp=16557
72061~acl=%2F237cf77f-cee6-4ef6-9e8e-043e6c701ab0%2F%2A~hmac=ab26adba64ac7933551
d96d8396c8ccce2eb1fcd3455769fa6d1413b40f04d82/237cf77f-cee6-4ef6-9e8e-043e6c701a
b0/parcel/video/cba0091d.mp4
[generic] cba0091d: Requesting header
WARNING: [generic] Could not send HEAD request to https://17vod-adaptive.akamaiz
ed.net/exp=1655772061~acl=%2F237cf77f-cee6-4ef6-9e8e-043e6c701ab0%2F%2A~hmac=ab2
6adba64ac7933551d96d8396c8ccce2eb1fcd3455769fa6d1413b40f04d82/237cf77f-cee6-4ef6
-9e8e-043e6c701ab0/parcel/video/cba0091d.mp4: HTTP Error 403: Forbidden
[generic] cba0091d: Downloading webpage
ERROR: [generic] Unable to download webpage: HTTP Error 403: Forbidden (caused b
y <HTTPError 403: 'Forbidden'>); please report this issue on  https://github.com
/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm y
ou are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 642, in extract
  File "yt_dlp\extractor\generic.py", line 2737, in _real_extract
  File "yt_dlp\extractor\common.py", line 786, in _request_webpage

  File "yt_dlp\extractor\common.py", line 768, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 3596, in urlopen
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden


C:\youtube-dl>yt-dlp --verbose https://17vod-adaptive.akamaized.net/exp=16557720
61~acl=%2F237cf77f-cee6-4ef6-9e8e-043e6c701ab0%2F%2A~hmac=ab26adba64ac7933551d96
d8396c8ccce2eb1fcd3455769fa6d1413b40f04d82/237cf77f-cee6-4ef6-9e8e-043e6c701ab0/
parcel/video/74484e5e.mp4
[debug] Command-line config: ['--verbose', 'https://17vod-adaptive.akamaized.net
/exp=1655772061~acl=%2F237cf77f-cee6-4ef6-9e8e-043e6c701ab0%2F%2A~hmac=ab26adba6
4ac7933551d96d8396c8ccce2eb1fcd3455769fa6d1413b40f04d82/237cf77f-cee6-4ef6-9e8e-
043e6c701ab0/parcel/video/74484e5e.mp4']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8 (No ANSI), er
ror utf-8 (No ANSI), screen utf-8 (No ANSI)
[debug] yt-dlp version 2022.05.18 [b14d523] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-7-6.1.7601-SP1
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: avprobe -bsfs
[debug] Checking exe version: ffmpeg -bsfs
[debug] exe versions: ffmpeg n4.4.1-14-g5a7763bdfa-20220109 (setts)
[debug] Optional libraries: Cryptodome-3.14.1, brotli-1.0.9, certifi-2021.10.08,
 mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] [generic] Extracting URL: https://17vod-adaptive.akamaized.net/exp=16557
72061~acl=%2F237cf77f-cee6-4ef6-9e8e-043e6c701ab0%2F%2A~hmac=ab26adba64ac7933551
d96d8396c8ccce2eb1fcd3455769fa6d1413b40f04d82/237cf77f-cee6-4ef6-9e8e-043e6c701a
b0/parcel/video/74484e5e.mp4
[generic] 74484e5e: Requesting header
[debug] Identified a direct video link
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7),
vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext,
aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 74484e5e: Downloading 1 format(s): mp4
[debug] Invoking http downloader on "https://17vod-adaptive.akamaized.net/exp=16
55772061~acl=%2F237cf77f-cee6-4ef6-9e8e-043e6c701ab0%2F%2A~hmac=ab26adba64ac7933
551d96d8396c8ccce2eb1fcd3455769fa6d1413b40f04d82/237cf77f-cee6-4ef6-9e8e-043e6c7
01ab0/parcel/video/74484e5e.mp4"
[debug] File locking is not supported on this platform. Proceeding without locki
ng
[download] Destination: 74484e5e [74484e5e].mp4
[download]   9.3% of 1.13GiB at  3.37MiB/s ETA 05:11

any idea what the reason is?
