### ISSUE TITLE
Extractors

### ISSUE THREAD

**Issue by CZeil** [yt-dlp/yt-dlp#4119]
### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Question

How can I know which fields are available for each extractor, as there are some that are not available (and it happens in the extractors I use). I ask this because when I try a new output template and use the fields when it is not available in the extractor it appears as NA. Then the doubt would be which output template fields are available for the extractors.

**Comment by pukkandan** [comment]
Check the `-j`/`--write-info-json` output

**Comment by CZeil** [comment]
Nice!!!!
Thanks! 😉
