### ISSUE TITLE
tvnz.co.nz

### ISSUE THREAD

**Issue by sourpatched** [yt-dlp/yt-dlp#4122]
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.05.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

New Zeeland

### Example URLs

https://www.tvnz.co.nz/shows/ice-airport-alaska/episodes/s1-e1
https://www.tvnz.co.nz/shows/ice-airport-alaska
https://www.tvnz.co.nz

### Description

Add support for TVNZ :)

### Verbose log

```shell
yt-dlp -vU https://www.tvnz.co.nz/shows/ice-airport-alaska/episodes/s1-e1
[debug] Command-line config: ['-vU', 'https://www.tvnz.co.nz/shows/ice-airport-alaska/episodes/s1-e1']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.05.18 [b14d52355]
[debug] Python version 3.10.4 (CPython 64bit) - Linux-5.18.3-051803-generic-x86_64-with-glibc2.35
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: ffmpeg -bsfs
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.11.0, brotli-1.0.9, certifi-2020.06.20, mutagen-1.45.1, pyxattr-0.7.2, secretstorage-3.3.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
Latest version: 2022.05.18, Current version: 2022.05.18
yt-dlp is up to date (2022.05.18)
[debug] [generic] Extracting URL: https://www.tvnz.co.nz/shows/ice-airport-alaska/episodes/s1-e1
[generic] s1-e1: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] s1-e1: Downloading webpage
[generic] s1-e1: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://www.tvnz.co.nz/shows/ice-airport-alaska/episodes/s1-e1
Traceback (most recent call last):
  File "/home/buzas/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1395, in wrapper
    return func(self, *args, **kwargs)
  File "/home/buzas/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1465, in __extract_info
    ie_result = ie.extract(url)
  File "/home/buzas/.local/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 642, in extract
    ie_result = self._real_extract(url)
  File "/home/buzas/.local/lib/python3.10/site-packages/yt_dlp/extractor/generic.py", line 4031, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.tvnz.co.nz/shows/ice-airport-alaska/episodes/s1-e1
```

**Comment by coletdjnz** [comment]
The content you linked has DRM. I'm pretty sure most of TVNZ is DRMed (except for live TV), so we will not be able to support it.
