### ISSUE TITLE
How to write the info.json of every video in a playlist?

### ISSUE THREAD

**Issue by Etim-Orb** [yt-dlp/yt-dlp#4124]
### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Question

When I use the --write-info-json flag and use only the URL of a playlist, only the playlist's own info json get's exported. What do I need to do in order to have a json for every video in that playlist?

**Comment by pukkandan** [comment]
Normally, each infojson will be written. You must be adding some other option that is preventing it. Show verbose log

**Comment by Etim-Orb** [comment]
I left the --download-archive flag in while not backing away the archive file, my bad, it works as intended.

**Comment by Etim-Orb** [comment]
@pukkandan I have another question though, I don't want to flood with another issue. Is it possible to reverse the playlist index -output flag? What I mean is often videos in playlists are listed the other way around i.e. the 5th episode is at the 1st index the 4th at the 2nd etc. So when I download the files will look like this: 01 - Episode 5, 02 - Episode 4. Is there a way to reverse this index flag?

**Comment by Etim-Orb** [comment]
The latter worked thank you.
