### ISSUE TITLE
[youtube] auto-generated subtitles from livestream-vods

### ISSUE THREAD

**Issue by shirishag75** [yt-dlp/yt-dlp#4130]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.05.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

Unable to get subtitles from specific  YT videos. Sharing an example, The warning comes at the very last and it doesn't tell what the issue is :(

### Verbose log

```shell
$ yt-dlp -vvv -c -f 137 kBnTxqqadfo --write-auto-sub
[debug] Command-line config: ['-vvv', '-c', '-f', '137', 'kBnTxqqadfo', '--write-auto-sub']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.05.18 [b14d52355]
[debug] Python version 3.10.5 (CPython 64bit) - Linux-5.18.0-1-amd64-x86_64-with-glibc2.33
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: ffmpeg -bsfs
[debug] exe versions: ffmpeg 4.4.2-1 (setts), ffprobe 4.4.2-1, phantomjs 2.1.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.11.0, brotli-1.0.9, certifi-2020.06.20, mutagen-1.45.1, secretstorage-3.3.2, sqlite3-2.6.0, websockets-10.2, xattr-0.9.9
[debug] Proxy map: {}
[debug] [youtube] Extracting URL: kBnTxqqadfo
[youtube] kBnTxqqadfo: Downloading webpage
[youtube] kBnTxqqadfo: Downloading android player API JSON
[youtube] kBnTxqqadfo: Downloading m3u8 information
WARNING: [youtube] Ignoring subtitle tracks found in the HLS manifest; if any subtitle tracks are missing, please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

**Comment by pukkandan** [comment]
Related: https://github.com/yt-dlp/yt-dlp/issues/2039

**Comment by shirishag75** [comment]
The bit of code that you shared, would that be in the new release, and if yes, when will you be releasing the new release?  As far as the subtitle is extracted into proper <release-filename>.en.vtt on the same path as the  .webm media file I don't think I need to worry. MPV will read it. Looking forward to know when you are releasing the new release. ytdl 22.06.22 perhaps ???

**Comment by pukkandan** [comment]
No, this code is useless without fixing the parser

**Comment by shirishag75** [comment]
> No, this code is useless without fixing the parser

Oh, so that's why you called the attention to the other gentleman, perhaps he might be able to fix the parser end of things. Thank you for responding so quickly to the issue.

**Comment by fstirlitz** [comment]
YouTube uses [obsolete metadata headers](https://www.w3.org/TR/2015/WD-webvtt1-20151208/#webvtt-metadata-header) in its WebVTT files that were [removed from the standard back in 2017](https://www.w3.org/TR/2017/WD-webvtt1-20170713/#file-structure) (Because following standards is for the hoi polloi and Google knows better, right? Yet another case of <https://nitter.42l.fr/Rich_Harris/status/1220412711768666114>.) This isn’t a problem for non-segmented subtitles, because we don’t parse them at all.

I guess we can pass them through as-is or strip them. There is a `Kind` header we may be interested in, which can probably differentiate between (transcribed) captions and (translated) subtitles.

**Comment by shirishag75** [comment]
@pukkandan any update on this ???

**Comment by fstirlitz** [comment]
I actually have a ready patch for this in my drafts:

```diff
--- a/yt_dlp/webvtt.py
+++ b/yt_dlp/webvtt.py
@@ -161,6 +161,15 @@ class Magic(HeaderBlock):
     _REGEX_TSMAP_MPEGTS = re.compile(r'MPEGTS:([0-9]+)')
     _REGEX_TSMAP_SEP = re.compile(r'[ \t]*,[ \t]*')
 
+    # This was removed from the spec in the 2017 revision;
+    # the last spec draft to describe this syntax element is
+    # <https://www.w3.org/TR/2015/WD-webvtt1-20151208/#webvtt-metadata-header>.
+    # Nevertheless, YouTube keeps serving those, because Google
+    # knows better than those pesky standards bodies, right?
+
+    _REGEX_META = re.compile(
+        r'(?:(?!-->)[^\r\n])+:(?:(?!-->)[^\r\n])+(?:\r\n|[\r\n])')
+
     @classmethod
     def __parse_tsmap(cls, parser):
         parser = parser.child()
@@ -200,13 +209,19 @@ def parse(cls, parser):
             raise ParseError(parser)
 
         extra = m.group(1)
+        meta = ''
         local, mpegts = None, None
-        if parser.consume(cls._REGEX_TSMAP):
-            local, mpegts = cls.__parse_tsmap(parser)
-        if not parser.consume(_REGEX_NL):
+        while not parser.consume(_REGEX_NL):
+            m = parser.consume(cls._REGEX_META)
+            if m:
+                meta += m.group(0)
+                continue
+            if parser.consume(cls._REGEX_TSMAP):
+                local, mpegts = cls.__parse_tsmap(parser)
+                continue
             raise ParseError(parser)
         parser.commit()
-        return cls(extra=extra, mpegts=mpegts, local=local)
+        return cls(extra=extra, mpegts=mpegts, local=local, meta=meta)
 
     def write_into(self, stream):
         stream.write('WEBVTT')
@@ -219,6 +234,8 @@ def write_into(self, stream):
             stream.write(',MPEGTS:')
             stream.write(str(self.mpegts if self.mpegts is not None else 0))
             stream.write('\n')
+        if self.meta:
+            stream.write(self.meta)
         stream.write('\n')
```

Perhaps the headers could be parsed more meaningfully (e.g. into an ordered multi-map), but this is enough for them not to generate errors and to be preserved in the final file.

**Comment by pukkandan** [comment]
Do you want me to merge the patch directly, or do you want to make a PR?

**Comment by fstirlitz** [comment]
Too busy currently to make a PR. Also, I don’t remember the last time I actually exercised this code, so consider it untested.

**Comment by pukkandan** [comment]
No worries. I'll test and merge this directly

**Comment by pukkandan** [comment]
No worries. I'll test and merge this directly

**Comment by shirishag75** [comment]
nice, looking forward to seeing this :)

**Comment by fstirlitz** [comment]
Eh, of course I got it wrong. The way I wrote it at first, `X-TIMESTAMP-MAP` would be stuffed into `.meta` and never captured by `__parse_tsmap`. See the corrected version.
