### ISSUE TITLE
Some downloads do not work from aws

### ISSUE THREAD

**Issue by mrzenwiz** [yt-dlp/yt-dlp#4132]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.05.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

USA

### Description

I just finished downloading another mp3 from aws with similar URL and this one failed.

### Verbose log

```shell
14:47 [admar@marbase:/htera/flash] $ yt-dlp -vU https://fhtj22.s3.amazonaws.com/final/Pam_Oslie.mp3
[debug] Command-line config: ['-vU', 'https://fhtj22.s3.amazonaws.com/final/Pam_Oslie.mp3']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.05.18 [b14d52355] (zip)
[debug] Python version 3.10.4 (CPython 64bit) - Linux-5.15.0-39-generic-x86_64-with-glibc2.35
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: ffmpeg -bsfs
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2
[debug] Optional libraries: secretstorage-3.3.1, sqlite3-2.6.0
[debug] Proxy map: {}
Latest version: 2022.05.18, Current version: 2022.05.18
yt-dlp is up to date (2022.05.18)
[debug] [generic] Extracting URL: https://fhtj22.s3.amazonaws.com/final/Pam_Oslie.mp3
[generic] Pam_Oslie: Requesting header
WARNING: [generic] Could not send HEAD request to https://fhtj22.s3.amazonaws.com/final/Pam_Oslie.mp3: HTTP Error 403: Forbidden
[generic] Pam_Oslie: Downloading webpage
ERROR: [generic] Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/home/admar/bin/yt-dlp/yt_dlp/extractor/common.py", line 642, in extract
    ie_result = self._real_extract(url)
  File "/home/admar/bin/yt-dlp/yt_dlp/extractor/generic.py", line 2737, in _real_extract
    full_response = self._request_webpage(request, video_id)
  File "/home/admar/bin/yt-dlp/yt_dlp/extractor/common.py", line 786, in _request_webpage
    raise ExtractorError(errmsg, cause=err)

  File "/home/admar/bin/yt-dlp/yt_dlp/extractor/common.py", line 768, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/home/admar/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3596, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/usr/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

14:56 [admar@marbase:/htera/flash] $
```

**Comment by pukkandan** [comment]
The URL gives 403 in browser as well

**Comment by mrzenwiz** [comment]
This is the base URL where the above one was embedded: https://fhtjoy.com/replay/?simplero_object_id=su_tuWAVBXNs3LAtJ42emfZc8A8#Pam

Does that help?

**Comment by pukkandan** [comment]
If you want to open a "site request" for that site, you can - and hopefully someone will add support. I'm not going to spend my time figuring out how to get working stream URLs from the site and teaching that to each user.

If you don't really want the site supported, but just want to know how to manually get the manifest, you'll have better luck asking in community forums like r/youtube-dl - definitely not in the project's issue tracker!
