### ISSUE TITLE
2022.06.22 build missing yt-dlp.exe

### ISSUE THREAD

**Issue by n-buna404** [yt-dlp/yt-dlp#4133]
### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.06.22** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Question

Hi I found that the recently released autobuild  do not have yt-dlp.exe. Is this behavior intended?

**Comment by pukkandan** [comment]
The build was still running when you checked...

**Comment by n-buna404** [comment]
ah ok cuz i receive email notifying the build release maybe i was a bit too early

**Comment by pukkandan** [comment]
The build process took abnormally long today https://github.com/yt-dlp/yt-dlp/runs/6995636521?check_suite_focus=true

**Comment by n-buna404** [comment]
Alright thanks for the explanation. I will wait longer or check for ongoing actions next time,
