### ISSUE TITLE
Issues using --parse-metadata

### ISSUE THREAD

**Issue by Brainimon** [yt-dlp/yt-dlp#4142]
### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.06.22.1** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Question

I'm not really sure if I'm doing anything wrong, I'm very new to this.
For whatever reason, it's saying `Could not interpret "'title" as "%(title)s'"`, and I've tested this with other metadata types as well.
Can anyone help? Thanks!

### Verbose log

```shell
C:\yt-dlp>yt-dlp.exe --audio-format vorbis --parse-metadata 'title:%(title)s' https://www.youtube.com/watch?v=y-f8pEX1Q1M
[youtube] y-f8pEX1Q1M: Downloading webpage
[youtube] y-f8pEX1Q1M: Downloading android player API JSON
[MetadataParser] Could not interpret "'title" as "%(title)s'"
[info] y-f8pEX1Q1M: Downloading 1 format(s): 248+251
[download] Destination: Infinite Amethyst [y-f8pEX1Q1M].f248.webm
[download] 100% of 15.63MiB in 00:00
[download] Destination: Infinite Amethyst [y-f8pEX1Q1M].f251.webm
[download] 100% of 4.62MiB in 00:00
[Merger] Merging formats into "Infinite Amethyst [y-f8pEX1Q1M].webm"
Deleting original file Infinite Amethyst [y-f8pEX1Q1M].f248.webm (pass -k to keep)
Deleting original file Infinite Amethyst [y-f8pEX1Q1M].f251.webm (pass -k to keep)
```

**Comment by pukkandan** [comment]
Windows doesn't allow single quotes, only double

**Comment by Brainimon** [comment]
> Windows doesn't allow single quotes, only double

Ah, ok! Thanks you so much!
