### ISSUE TITLE
Mediafire 

### ISSUE THREAD

**Issue by upintheairsheep** [yt-dlp/yt-dlp#4143]
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.06.22.1** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Southern California, USA (not telling the exact town I'm living in for privacy reasons unless required)

### Example URLs

http://www.mediafire.com/file/bgv7rnx2bqngtiz/mp4/file

### Description

Mediafire is a popular site for sharing files. It would be nice if you added it.

### Verbose log

```shell
None
```

**Comment by pukkandan** [comment]
Out of scope! Mediafire is a general file hosting service with no feature to even play videosme
