### ISSUE TITLE
Multiple Client-side IP address Management

### ISSUE THREAD

**Issue by adapana** [yt-dlp/yt-dlp#4149]
### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.06.22.1** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Question

Hello,

There is `--source-address IP` to set client-side IP for download. I have one question related to this.

Suppose I have 5 different IPs in my server, without using `--source-address IP` yt-dlp uses random IP from that 5 IPS or I have to manually assign IP using command?

**Comment by adapana** [comment]
So, the best way to get different IP is to use `--source-address` every time, right?

**Comment by pukkandan** [comment]
Yes

**Comment by adapana** [comment]
Thanks for your help.
