### ISSUE TITLE
Please add an option to wait for keystroke after everything is complete

### ISSUE THREAD

**Issue by pboettcher** [yt-dlp/yt-dlp#4152]
### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.06.22.1** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

Could you please add a command line option to make yt-dlp wait for a keystroke after it completed? I see three variants possible:

- Do not pause (default)
- Always pause and wait for a keystroke
- Pause on errors only

Profit: no need to create an additional shell script file for that. No need to think how build an universal batch file to pass an unlimited number of command line parameters through it. Ability to start directly with CreateProcess in Windows.

**Comment by pukkandan** [comment]
Just do `yt-dlp ... & pause`

**Comment by pboettcher** [comment]
> Just do `yt-dlp ... & pause`

Doesn't work with CreateProcess API call. Seems that I should call CMD.EXE, not yt-dlp.exe.

**Comment by Ashish0804** [comment]
How is this feature even useful?
