### ISSUE TITLE
Update script with auto-backup function

### ISSUE THREAD

**Issue by pboettcher** [yt-dlp/yt-dlp#4153]
### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.06.22.1** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

A BASH script to update the executable, producing a versioned backup (I wish yt-dlp -U could do that).

```
#!/bin/bash
ExeName="yt-dlp"
ExeDir="/usr/local/bin/"
UpdateSource="https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp"

function BackupFile {
  if [ ! -f "$ExeName" ]; then
    return
  fi
  local version=$(./$ExeName --version)
  if [ -z "$version" ]; then
    return
  fi
  local fname="$ExeName.$version"
  if [ ! -f "$fname" ]; then
    cp "./$ExeName" "./$fname"
  fi
}
cd "$ExeDir"
BackupFile
TargetPath="$ExeDir$ExeName"
curl -L "$UpdateSource" -o "$TargetPath"
chown root:root "$TargetPath"
chmod 755 "$TargetPath"
BackupFile

```

**Comment by pukkandan** [comment]
Why do you consider this to be in scope of the project?
