### ISSUE TITLE
--downloader native not recogized as a valid option in release 2022.06.22.1

### ISSUE THREAD

**Issue by xpalidotious** [yt-dlp/yt-dlp#4157]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.06.22.1** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

I've just updated to the latest release (2022.06.22.1) and found that my download script failed because the argument "--downloader native" is no longer recognized as a valid option.

### Verbose log

```shell
[debug] Command-line config: ['-vU', '--downloader', 'native', '--ignore-config', 'https://www.youtube.com/watch?v=oHLOYrG5fHU']

Usage: yt-dlp.exe [OPTIONS] URL [URL...]

yt-dlp.exe: error: No such external downloader "native"
```

**Comment by pukkandan** [comment]
Fixed in https://github.com/yt-dlp/yt-dlp/commit/28163422a667d63cceb0e8bf27d150951e78d313
