### ISSUE TITLE
Using bestvideo+bestaudio with certain websites gives an error

### ISSUE THREAD

**Issue by parasiteoflife** [yt-dlp/yt-dlp#416]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running yt-dlp version **2021.06.09**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
[debug] Command-line config: ['-R', '15', '-v', '-i', '-o', 'z:\\video\\%(title)s (%(id)s) [%(height)sp].%(ext)s', '--cookies', 'Z:\\cookies.txt', '-f', 'bestvideo+bestaudio', '--fixup', 'detect_or_warn', '--add-metadata', 'https://www.metacafe.com/watch/11636649/dancer4/']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] yt-dlp version 2021.06.09 (exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19042-SP0
[debug] exe versions: ffmpeg 2021-05-19-git-2261cc6d8a-full_build-www.gyan.dev, ffprobe 2021-05-19-git-2261cc6d8a-full_build-www.gyan.dev
[debug] Proxy map: {}
[debug] [metacafe] Extracting URL: https://www.metacafe.com/watch/11636649/dancer4/
[metacafe] 11636649: Downloading webpage
[metacafe] 11636649: Extracting information
[metacafe] 11636649: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
ERROR: Requested format is not available
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1133, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1165, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1202, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2158, in process_video_result
yt_dlp.utils.ExtractorError: Requested format is not available
```

## Description

This error is not only happening with certain videos nor with only metacafe, it happens also with xvideos and xhamster. IIRC this didn't happened on youtube-dl, please fix this.

**Comment by pukkandan** [comment]
Metacafe doesn't have a `bestvideo` or a `bestaudio`. Just don't use any `-f`

**Comment by parasiteoflife** [comment]
It is happening also with xvideos and xhamster, try with any url. Isn't there any way you guys could make it to automatically ignore betvideo+bestaudio if it's missing from the supported formats? I'm downloading all URL in an automated way just giving any URL I found so editing the command line for certain videos will break the automation.

**Comment by pukkandan** [comment]
Use `bv+ba/b` then...

**Comment by pukkandan** [comment]
>  Isn't there any way you guys could make it to automatically ignore betvideo+bestaudio if it's missing from the supported formats

No. The app downloads exactly what you request it. Just use the correct options

**Comment by parasiteoflife** [comment]
Thank you, didn't thought about that, I was of course using the wrong commands.

**Comment by parasiteoflife** [comment]
@pukkandan Hey, one question. I'm using `bv*+ba/b` now and I'm getting this with several metacafe videos:

```
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] yt-dlp version 2021.06.09 (exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19042-SP0
[debug] exe versions: ffmpeg 2021-05-19-git-2261cc6d8a-full_build-www.gyan.dev, ffprobe 2021-05-19-git-2261cc6d8a-full_build-www.gyan.dev
[debug] Proxy map: {}
[debug] [metacafe] Extracting URL: https://www.metacafe.com/watch/3354402/lorena_orozco_besame/
[metacafe] 3354402: Downloading webpage
[metacafe] 3354402: Extracting information
ERROR: the JSON object must be str, bytes or bytearray, not NoneType
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1133, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1154, in __extract_info
  File "yt_dlp\extractor\common.py", line 567, in extract
  File "yt_dlp\extractor\metacafe.py", line 230, in _real_extract
  File "yt_dlp\extractor\common.py", line 950, in _parse_json
  File "json\__init__.py", line 341, in loads
TypeError: the JSON object must be str, bytes or bytearray, not NoneType
```

Is that a bug? Video link is working fine.

**Comment by pukkandan** [comment]
That video doesn't play for me in browser either

**Comment by parasiteoflife** [comment]
I can't access metacafe anymore now, it seems the website is suffering some problems. I got a bad gateway and I can't even access my profile, is giving me errors.

Will try later and see if it happens again because some videos downloaded correctly.

**Comment by pukkandan** [comment]
I can access the site, and other videos play correctly, but this one doesn't. For now, lets assume its an issue on their side. If the video becomes playable in browser but still doesn't download, open a new issue
