### ISSUE TITLE
[gaia.com] AttributeError: 'NoneType' object has no attribute 'items'

### ISSUE THREAD

**Issue by someziggyman** [yt-dlp/yt-dlp#4164]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.06.22.1** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

anywhere

### Description

Test link:
https://www.gaia.com/video/connecting-universal-consciousness?fullplayer=feature

### Verbose log

```shell
./yt-dlp -v -F "https://www.gaia.com/video/connecting-universal-consciousness?fullplayer=feature"
[debug] Command-line config: ['-v', '-F', 'https://www.gaia.com/video/connecting-universal-consciousness?fullplayer=feature']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.06.22.1 [a86e01e74] (zip)
[debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
[debug] Python version 3.9.13 (CPython 64bit) - macOS-12.4-arm64-arm-64bit
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: avconv -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: avprobe -bsfs
[debug] exe versions: none
[debug] Optional libraries: sqlite3-2.6.0
[debug] Proxy map: {}
[debug] [Gaia] Extracting URL: https://www.gaia.com/video/connecting-universal-consciousness?fullplayer=feature
[Gaia] connecting-universal-consciousness: Downloading JSON metadata
[Gaia] 113091: Downloading JSON metadata
[Gaia] 89356: Downloading JSON metadata
ERROR: 'NoneType' object has no attribute 'items'
Traceback (most recent call last):
  File "./yt-dlp/yt_dlp/YoutubeDL.py", line 1427, in wrapper
    return func(self, *args, **kwargs)
  File "./yt-dlp/yt_dlp/YoutubeDL.py", line 1497, in __extract_info
    ie_result = ie.extract(url)
  File "./yt-dlp/yt_dlp/extractor/common.py", line 647, in extract
    ie_result = self._real_extract(url)
  File "./yt-dlp/yt_dlp/extractor/gaia.py", line 86, in _real_extract
    media = self._download_json(
  File "./yt-dlp/yt_dlp/extractor/common.py", line 1009, in download_content
    res = getattr(self, download_handle.__name__)(url_or_request, video_id, **kwargs)
  File "./yt-dlp/yt_dlp/extractor/common.py", line 973, in download_handle
    res = self._download_webpage_handle(
  File "./yt-dlp/yt_dlp/extractor/common.py", line 841, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query, expected_status=expected_status)
  File "./yt-dlp/yt_dlp/extractor/common.py", line 780, in _request_webpage
    return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query))
  File "./yt-dlp/yt_dlp/extractor/common.py", line 746, in _create_request
    return sanitized_Request(url_or_request, data, headers)
  File "./yt-dlp/yt_dlp/utils.py", line 770, in sanitized_Request
    return compat_urllib_request.Request(url, *args, **kwargs)
  File "/opt/homebrew/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 326, in __init__
    for key, value in headers.items():
AttributeError: 'NoneType' object has no attribute 'items'
```

**Comment by dirkf** [comment]
Working in yt-dl master:
```shellsession
$ python -m youtube_dl -v -F 'https://www.gaia.com/video/connecting-universal-consciousness?fullplayer=feature'
[debug] System config: [u'--prefer-ffmpeg']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-F', u'https://www.gaia.com/video/connecting-universal-consciousness?fullplayer=feature']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Git HEAD: e0ec049d5
[debug] Python version 2.7.17 (CPython) - Linux-4.4.0-210-generic-i686-with-Ubuntu-16.04-xenial
[debug] exe versions: avconv 4.3, avprobe 4.3, ffmpeg 4.3, ffprobe 4.3
[debug] Proxy map: {}
[Gaia] connecting-universal-consciousness: Downloading JSON metadata
[Gaia] 113091: Downloading JSON metadata
[Gaia] 89356: Downloading JSON metadata
[Gaia] 89356: Downloading m3u8 information
[info] Available formats for 89356:
format code        extension  resolution note
audio-0-en__Main_  mp4        audio only [en] 
audio-1-en__Main_  mp4        audio only [en] 
audio-2-en__Main_  mp4        audio only [en] 
audio-3-en__Main_  mp4        audio only [en] 
563                mp4        480x270     563k , avc1.420015, video only
872                mp4        640x360     872k , avc1.42001e, video only
1126               mp4        640x360    1126k , avc1.4d001e, video only
1525               mp4        960x540    1525k , avc1.4d001f, video only
2072               mp4        960x540    2072k , avc1.4d001f, video only
2401               mp4        1280x720   2401k , avc1.4d001f, video only
4050               mp4        1920x1080  4050k , avc1.640028, video only (best)
$
```
Same with Py 3.9.

On a quick diff, some code was moved from `_real_initialize()` to `_perform_login()` and I believe is now only run if credentials have been provided. OP could probably revert to `youtube_dl/extractor/gaia.py` as a work-around.

**Comment by pukkandan** [comment]
This bug actually exists in ytdl as well, but is triggered only when `data is not None and headers is None`. See https://github.com/ytdl-org/youtube-dl/blob/8a158a936c8b002ef536e9e2b778ded02c09c0fa/youtube_dl/extractor/common.py#L628-L629

**Comment by dirkf** [comment]
My thought was that _urllib2_ ought to be handling the `headers=None` case.

**Comment by someziggyman** [comment]
I've got a quick follow up for this case. 

Test links:
https://www.gaia.com/video/highest-pass?fullplayer=feature
https://www.gaia.com/video/a-treacherous-ride-home?fullplayer=feature

These fail with:
ERROR: [Gaia] highest-pass: Unable to download JSON metadata: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

but if I use https://www.gaia.com/video/highest-pass cutting off the ?fullplayer=feature junk, it downloads just a trailer. 
I assume to get full video I need to login and pass cookies but extractor does not detect this case(though I see there's is some code for this at a quick glance).

at the same time this link works fine even with "fullplayer junk": https://www.gaia.com/video/connecting-universal-consciousness?fullplayer=feature

So, it's a bit inconsistent.
