### ISSUE TITLE
yt-dlp (latest version) does not honor "--" to end options (Noticeable if 11 char ID starts with "-")

### ISSUE THREAD

**Issue by joeschmoe40** [yt-dlp/yt-dlp#4167]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.06.22.1** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

For various reasons, I use the "11 character ID" rather than a full URL to access things on YouTube.  So, a typical command line is like:

yt-dlp --restrict-filenames -f mp4 -j -- 11character

This works fine as long as the 11 character ID doesn't start with a -.  If it does, then I get an error message as it tried to parse that as a command line option.

The "--" is supposed to stop this from happening, and it did in youtube-dl.  I've been using it yt-dlp for about a year now (since when youtube-dl broke) and this is the first time I've hit the error (since it is, obviously, going to be rare).  I just assumed it would work correctly as it does (did) in youtube-dl.

### Verbose log

```shell
I don't know how to fill this in.
```

**Comment by pukkandan** [comment]
```
❯ yt-dlp -v --restrict-filenames -f mp4 -j -- -1234567890
[debug] Encodings: locale cp65001, fs utf-8, pref cp65001, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.06.22.1 [a86e01e74] (source)
[debug] Lazy loading extractors is disabled
[debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
[debug] Git HEAD: 14f25df2b
[debug] Python version 3.10.4 (CPython 64bit) - Windows-10-10.0.22000-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg N-106550-g072101bd52-20220410 (fdk,setts), ffprobe N-106624-g391ce570c8-20220415, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.14.1, brotli-1.0.9, certifi-2021.10.08, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.1
[debug] Proxy map: {}
[debug] [youtube] Extracting URL: -1234567890
[youtube] -1234567890: Downloading webpage
[youtube] -1234567890: Downloading android player API JSON
ERROR: [youtube] -1234567890: Video unavailable
  File "D:\Programs\Source\yt-dlp\yt-dlp\yt_dlp\extractor\common.py", line 639, in extract
    ie_result = self._real_extract(url)
  File "D:\Programs\Source\yt-dlp\yt-dlp\yt_dlp\extractor\youtube.py", line 3476, in _real_extract
    self.raise_no_formats(reason, expected=True)
  File "D:\Programs\Source\yt-dlp\yt-dlp\yt_dlp\extractor\common.py", line 1123, in raise_no_formats
    raise ExtractorError(msg, expected=expected, video_id=video_id)
```

**Comment by joeschmoe40** [comment]
$ yt-dlp -v -f mp4 --restrict-filenames -j -- -FJNiQaYbWE

Usage: yt-dlp [OPTIONS] URL [URL...]

yt-dlp: error: option -N: invalid integer value: 'iQaYbWE'
$

**Comment by joeschmoe40** [comment]
The issue is real.  What do I have to do to "unclose" it?

**Comment by pukkandan** [comment]
It was closed because issue is fixed in https://github.com/yt-dlp/yt-dlp/commit/c800598cd1a3467e53b479c5efc8c6d603d94e5c

**Comment by joeschmoe40** [comment]
OK, good.  I misunderstood why it was closed.
I assume this means that it will be fixed on the next public release (yes?)

**Comment by pukkandan** [comment]
Yes
