### ISSUE TITLE
yt-dlp.exe: error: No such dash external downloader "native"

### ISSUE THREAD

**Issue by PLN** [yt-dlp/yt-dlp#4170]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.06.22.1** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

I've been using an option that is actually listed in the command line documentation: --downloader aria2c --downloader "dash,m3u8:native"
The recent update seems to have broken this, returning the error message: No such dash external downloader "native"
Removing these command line options allows the video to be downloaded, but obviously without using the aria2c downloader for the main file.

### Verbose log

```shell
C:\Temp>yt-dlp --version
2022.06.22.1

C:\Temp>yt-dlp.exe -vU --downloader aria2c --downloader "dash,m3u8:native" https://www.youtube.com/watch?v=kRE1j55aLRo
[debug] Command-line config: ['-vU', '--downloader', 'aria2c', '--downloader', 'dash,m3u8:native', 'https://www.youtube.com/watch?v=kRE1j55aLRo']

Usage: yt-dlp.exe [OPTIONS] URL [URL...]

yt-dlp.exe: error: No such dash external downloader "native"

C:\Temp>yt-dlp.exe -vU https://www.youtube.com/watch?v=kRE1j55aLRo
[debug] Command-line config: ['-vU', 'https://www.youtube.com/watch?v=kRE1j55aLRo']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.06.22.1 [a86e01e] (win32_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 2021-09-01-git-c500dc7cca-full_build-www.gyan.dev (setts), ffprobe 2021-09-01-git-c500dc7cca-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.14.1, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.06.22.1, Current version: 2022.06.22.1
yt-dlp is up to date (2022.06.22.1)
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=kRE1j55aLRo
[youtube] kRE1j55aLRo: Downloading webpage
[youtube] kRE1j55aLRo: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] kRE1j55aLRo: Downloading 1 format(s): 248+251
[download] Drinker's Chasers - What Happened To Westworld [kRE1j55aLRo].webm has already been downloaded
```

**Comment by pukkandan** [comment]
See pinned issue
