### ISSUE TITLE
"-j" conflicts with "--download-archive"

### ISSUE THREAD

**Issue by atom-smasher** [yt-dlp/yt-dlp#4177]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.06.22.1** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

If a video is recorded in the download-archive, option `-j` or `--dump-json`  fails silently.

Options `-F`, `-J` or `--dump-single-json` work as expected, by failing with a notice.

eg, after downloading of `https://www.youtube.com/watch?v=Ao5XcORsYxA` and recording it in `archive.txt`, this command fails silently:
`yt-dlp -vU --ignore-config --download-archive archive.txt -j 'https://www.youtube.com/watch?v=Ao5XcORsYxA' `
(verbose log, below)

(**Edit**: That command, **without `-v`**, fails silently)

I don't necessarily think it's a problem that it fails, but:

1.  it should give a notice about why it fails, eg:
`[download] xxxx has already been recorded in the archive`
2. the behaviour of `-j` and `-J` (and any option that implies `--simulate`) should be consistent

### Verbose log

```shell
[debug] Command-line config: ['-vU', '--ignore-config', '--download-archive', 'archive.txt', '-j', 'https://www.youtube.com/watch?v=Ao5XcORsYxA']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.06.22.1 [a86e01e] (zip)
[debug] Plugins: ['Youtube_AgeGateBypassIE']
[debug] Python version 3.8.10 (CPython 64bit) - Linux-5.4.0-120-generic-x86_64-with-glibc2.29
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.2.7, ffprobe 4.2.7, phantomjs 2.1.1, rtmpdump 2.4
[debug] Optional libraries: certifi-2019.11.28, mutagen-1.45.1, pycrypto-2.6.1, pyxattr-0.6.1, secretstorage-2.3.1, sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Loading archive file 'archive.txt'
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.06.22.1, Current version: 2022.06.22.1
yt-dlp is up to date (2022.06.22.1)
[debug] [youtube:AGB] Extracting URL: https://www.youtube.com/watch?v=Ao5XcORsYxA
[youtube:AGB] Ao5XcORsYxA: Downloading webpage
[youtube:AGB] Ao5XcORsYxA: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[download] Easiest ESP8266 Tutorial (Using arduino) has already been recorded in the archive
```

**Comment by pukkandan** [comment]
It does say!

> [download] Easiest ESP8266 Tutorial (Using arduino) has already been recorded in the archive

**Comment by pukkandan** [comment]
am I missing something?

**Comment by atom-smasher** [comment]
Try it without the `-v`. On my machine, it's fails silently.

**Comment by pukkandan** [comment]
No logs are printed when using `-j` since it automatically implies `-q`. Maybe what you want is a `--no-quiet` option? though I don't really see much benefit for it over just using `-v`

**Comment by atom-smasher** [comment]
I don't think the problem is the implied `-q`. I think the problem is `--download-archive archive.txt` being implied. Why is that implied when using `-j`, but not implied when using `-J` or `-F`?

But even then… With `-J` it "just does what I ask", even if I do specify `--download-archive archive.txt`.

It's just wildly inconsistent. The behaviour of `-F` (failing with a message) makes sense. The behaviour of `-J` (just doing what I ask, since `--simulate` is implied) makes sense.

The behaviour of `-j` (failing silently) makes no sense.

**Comment by pukkandan** [comment]
> I think the problem is --download-archive archive.txt being implied. Why is that implied when using -j, but not implied when using -J or -F?

What? It is not being "implied". You are passing it!

**Comment by atom-smasher** [comment]
Oops, Right… But it's being ignored by `-J`, which does what I ask, regardless of whether the video is recorded in the archive:

`yt-dlp --download-archive archive.txt -J --ignore-config  'https://www.youtube.com/watch?v=Ao5XcORsYxA'`

That one works as expected: Show me information about the video I previously downloaded.

Change the `-J` to `-j`, and it just fails silently:

`yt-dlp --download-archive archive.txt -j --ignore-config  'https://www.youtube.com/watch?v=Ao5XcORsYxA'`

I think I confused myself by using `-download-archive archive.txt` to compensate for `--ignore-config`, but the problem is still these similar options are resulting in wildly inconsistent behaviour.

**Comment by pukkandan** [comment]
That is correct behavior though... The only difference b/w `-j` and `-J` is that the former (`-j`) acts on each **video**, while the latter (`-J`) on each **input URL**. Since the given URL was processed, `-J` outputted it's results. But the actual video was skipped - so `-j` does not output anything

**Comment by atom-smasher** [comment]
If it's skipped because it's recorded in the archive, shouldn't it give a notice about that? Like `-F` does?

Regardless of the reasoning, if I request information about a video/URL, and yt-dlp doesn't give me that info, it should give a notice.

**Comment by atom-smasher** [comment]
Another way I'm looking at this, this command does what I expect: Don't download the video because it's been recorded in the archive, and give a notice about "already been recorded in the archive":

`yt-dlp --download-archive archive.txt  --ignore-config  'https://www.youtube.com/watch?v=Ao5XcORsYxA'`

Just adding `-j` results in the same action (do nothing) but it does so silently:

`yt-dlp --download-archive archive.txt  --ignore-config -j 'https://www.youtube.com/watch?v=Ao5XcORsYxA' `

It's the silent failure that I'm seeing as a problem.

**Comment by pukkandan** [comment]
https://github.com/yt-dlp/yt-dlp/issues/4177#issuecomment-1166316163
