### ISSUE TITLE
"Bestaudio" should be ignored if there's no audio streams

### ISSUE THREAD

**Issue by DuendeInexistente** [yt-dlp/yt-dlp#4179]
### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.06.22.1** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

When watching a video through mpv, my default quality is `bestvideo[height<=?480]+bestaudio/best`. This works fine in most websites, but some don't have separate audio streams and so fail the bestaudio check, moving over to the best available quality. This affects peer.tube instances, for example.

As any site that lacks a separate audio stream will have it included in the video itself, perhaps the bestaudio format could be ignored if no audio streams are found? I realize this can be fixed just by using `bestvideo[height<=?480]+bestaudio/bestvideo[height<=?480]/best` instead and have already done so in my mpv.conf, but it's not the most intuitive thing and a less experienced user might trip over.

**Comment by pukkandan** [comment]
There is probably a simpler way to achieve what you want. But can't really say without example URL and verbose logs

**Comment by pukkandan** [comment]
But no, yt-dlp will not be made to "ignore" `bestaudio` if you asked it to download that format!

**Comment by dirkf** [comment]
Surely `bestvideo` only matches streams with `acodec=='none'`, so `bestvideo[height<=?480]+bestaudio/bestvideo[height<=?480]/best` will give you in order of preference:
1. a merger of the "best" video-only and audio-only streams where the height of the video, if known, is not more than 480 pixels, or if none
2. a video-only stream where the height of the video, if known, is not more than 480 pixels, or if none
3. the "best" combined video and audio format, if there is one.

As reading TFM would show, yt-dlp understands `bestvideo*` to mean the best video format including formats that also have audio streams.
