### ISSUE TITLE
How i can install in my windows? please help

### ISSUE THREAD

**Issue by shahidhasanzai** [yt-dlp/yt-dlp#418]
hello .please tell me how i can install yt-dlp in my windows 10 and how i can download from youtube ,hotstar.com ,sonyliv.com etc websites, wwe.com .

**Comment by MinePlayersPE** [comment]
Please read https://github.com/yt-dlp/yt-dlp#installation (downloading the binary is probably the easiest way) and https://github.com/yt-dlp/yt-dlp#usage-and-options (tl;dr `yt-dlp <URL>` should get the best video)

**Comment by shahidhasanzai** [comment]
cant understanmd this all ,could you please come with any desk and install it for me , i wanna download wwe, tv shows from hotstar , sonyliv ,youtube etc

**Comment by pukkandan** [comment]
The instructions are as basic as it can be: (1) Download [this binary](https://github.com/yt-dlp/yt-dlp/releases/latest), (2) Run it from a terminal. If you search "how to install youtube-dl", you will find videos and articles explaining this same thing

Nobody is going to "come and install it" for you. If you are not interested in even trying to figure this out, then we can't help you

**Comment by shahidhasanzai** [comment]
could you please add sonyliv.com episode , its DRM protected , i cant download from  there ,,

**Comment by MinePlayersPE** [comment]
Did you set --allow-unplayable-formats? If you did and it still failed, then open a new issue because it seems like sonyliv is supported

P.S. yt-dlp does not decrypt DRM-protected videos.
