### ISSUE TITLE
Can't fetch bilibili channel name

### ISSUE THREAD

**Issue by seldron333** [yt-dlp/yt-dlp#4193]
### Checklist

- [X] I'm reporting a broken site
- [x] I've verified that I'm running yt-dlp version **2022.06.22.1** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Description

When trying to fetch the name of any bilibili channel it always outputs "NA".

### Verbose log

```shell
yt-dlp -vU --get-filename -o '%(channel)s' https://www.bilibili.com/video/BV1MS4y1p7UU                                                                                                                               ✔ 
[debug] Command-line config: ['-vU', '--get-filename', '-o', '%(channel)s', 'https://www.bilibili.com/video/BV1MS4y1p7UU']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.06.22.1 [a86e01e]
[debug] Python version 3.10.5 (CPython 64bit) - Linux-5.18.6-1-MANJARO-x86_64-with-glibc2.35
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 5.0.1 (setts), ffprobe 5.0.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.12.0, certifi-2021.10.08, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.06.22.1, Current version: 2022.06.22.1
yt-dlp is up to date (2022.06.22.1)
[debug] [BiliBili] Extracting URL: https://www.bilibili.com/video/BV1MS4y1p7UU
[BiliBili] 1MS4y1p7UU: Grabbing original ID via API
[BiliBili] 727844126: Downloading webpage
[BiliBili] 727844126: Extracting videos in anthology
[BiliBili] Downloading anthology 727844126 - add --no-playlist to just download video
[download] Downloading playlist: 你从未见过的光影版本饥荒！【假如饥荒有光影和山脉】
[BiliBili] Playlist 你从未见过的光影版本饥荒！【假如饥荒有光影和山脉】: Downloading 1 videos of 1
[download] Downloading video 1 of 1
[debug] [BiliBili] Extracting URL: https://www.bilibili.com/video/BV1MS4y1p7UU?p=1
[BiliBili] 1MS4y1p7UU: Grabbing original ID via API
[BiliBili] 727844126: Downloading webpage
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[BiliBili] 727844126: Extracting videos in anthology
[BiliBili] 727844126: Downloading tags
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 727844126_part1: Downloading 1 format(s): 14+2
NA
[download] Finished downloading playlist: 你从未见过的光影版本饥荒！【假如饥荒有光影和山脉】
```

**Comment by dirkf** [comment]
The diagnostic should say that the page has no video.

Playlist support would require (eg) pulling https://github.com/ytdl-org/youtube-dl/pull/31010, without which yt-dl gives the same result.

**Comment by pukkandan** [comment]
Use `uploader`

**Comment by seldron333** [comment]
> Use `uploader`

ok thanks
