### ISSUE TITLE
Allow piping output

### ISSUE THREAD

**Issue by digitalheir** [yt-dlp/yt-dlp#4214]
### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.06.22.1** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

I used to save output messages to disk through `yt-dlp xyz > yt-dlp-output.txt`, but now that I've updated the program it seems like a separate process is started and piping output messages is not straightforward anymore. Whenever iI run `yt-dlp`, I'm thrown immediately back to the terminal while it pushes messages seemingly from the background. Jarring experience. Can you please make it like it was again?

Related: https://github.com/yt-dlp/yt-dlp/issues/661

**Comment by digitalheir** [comment]
Perhaps this is superseded by https://github.com/yt-dlp/yt-dlp/issues/2668

**Comment by pukkandan** [comment]
> Whenever iI run yt-dlp, I'm thrown immediately back to the terminal while it pushes messages seemingly from the background. Jarring experience. 

This is not expected behavior, and I cannot reproduce. Show me the output of `yt-dlp -v` and some demonstration of what is happening (a screen recording will do)

**Comment by digitalheir** [comment]
I suppose it happens for playlists which also contain a video. It doesn't seem to occur if I remove the `v` parameter.

https://user-images.githubusercontent.com/178797/176479332-2c39795b-2c00-402b-811b-d12903c93b06.mov

```
[debug] Command-line config: ['-vU']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.06.22.1 [a86e01e] (zip)
[debug] Python version 3.8.10 (CPython 64bit) - Linux-5.4.0-92-generic-x86_64-with-glibc2.29
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.2.7, ffprobe 4.2.7
[debug] Optional libraries: certifi-2019.11.28, secretstorage-2.3.1, sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.06.29, Current version: 2022.06.22.1
Current Build Hash 28ae7c14e9b5e85708fc292c1e2767c14e9f7c72db71bd629b285a442e9cbe69
Updating to version 2022.06.29 ...
```
