### ISSUE TITLE
homebrew: command not found: yt-dlp

### ISSUE THREAD

**Issue by AniOSDeveloper** [yt-dlp/yt-dlp#4223]
### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.06.29** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Question

”zsh: command not found: yt-dlp“ when I run the command below I run into such error.
yt-dlp "https://www.youtube.com/watch?v=4obxmYn2AoI"

While yt-dlp is installed via Homebrew to my Mac, the command is
brew install yt-dlp/taps/yt-dlp

I have checked that yt-dlp have installed on Mac by the command "brew list".

What should I do to work it out, any suggestion is appreciated.

**Comment by pukkandan** [comment]
Not a yt-dlp issue. You should ask elsewhere like https://stackoverflow.com/questions/65619529/fixing-zsh-command-not-found-brew-installing-homebrew

**Comment by rpendleton** [comment]
It seems an update to either homebrew, yt-dlp or some related package is resulting in the symlink in `/usr/local/bin` not being created. I'm guessing this is happening because the `yt-dlp` executable is in the `libexec/bin` directory instead of `bin`, so homebrew skips creating the symlink.

To temporarily get around this, you can create a symlink manually:

```
ln -s /usr/local/Cellar/yt-dlp/*/libexec/bin/yt-dlp /usr/local/bin
```

Unfortunately, that command will need to be executed any time the formula is updated. I'm not familiar enough with Homebrew or Python to know what might have introduced this issue or how to fix it properly though.

**Comment by pukkandan** [comment]
@rpendleton What commands are you using to install and update yt-dlp?

**Comment by rpendleton** [comment]
I originally installed with this command a few months ago, which worked fine:
```
brew install yt-dlp/taps/yt-dlp
```

I updated today using this command, after which yt-dlp executable could no longer be found:
```
brew upgrade yt-dlp/taps/yt-dlp
```

After doing the upgrade, I also noticed that my shell had yt-dlp in the auto complete, but when I restarted my shell, it was no longer there. So I for sure had yt-dlp in my PATH before upgrading, but not after.

For what it's worth, I also tried reinstalling using `brew reinstall` but that didn't seem to change anything.

**Comment by pukkandan** [comment]
Could be an issue with the tap. @Lesmiscore Can you have a look

**Comment by AniOSDeveloper** [comment]
> ommands are you using to install and update y

I followed the instructions of the link you post, and tried every suggestion to add PATH to the .zshrc file, but the error is still there.
However, I find there are many formulaes installed by homebrew, curl is one of them, so I try to use curl to execute a command like this, it prints the version correctly.
curl --version

So I think this might be a bug. Now I manually install it by downloading the release package and adding the path to .zshrc . It works great and has successfully downloaded three youtube videos.

BTW  My MacBook Pro uses Intel chips and the system version is macOS Big Sur 11.6.7.

**Comment by Lesmiscore** [comment]
It doesn't seem to be working for yt-dlp taps but core tap. I'll take a look

**Comment by Lesmiscore** [comment]
@AniOSDeveloper @rpendleton @tgy Can you please run `brew reinstall yt-dlp/taps/yt-dlp` and try yt-dlp command again?

to devs: do not close this issue after successful reports. I have some more things to do

**Comment by tgy** [comment]
hi @Lesmiscore
thanks for your reply.
i did run this exact command, before opening this issue, re-ran my shell, and it did not work. `yt-dlp` binary still can't be found. i also checked under `/opt/homebrew/bin` and it's not there :-/

**Comment by tgy** [comment]
```
vi ❯ /opt/homebrew/Cellar/yt-dlp/2022.6.29/libexec/bin/yt-dlp --version
2022.06.29
```
```
vi ❯ brew --version
Homebrew 3.5.3
Homebrew/homebrew-core (git revision 3c4e5cf7186; last commit 2022-06-30)
Homebrew/homebrew-cask (git revision e3eeb80155; last commit 2022-06-30)
```

**Comment by Lesmiscore** [comment]
Please do it again now.

**Comment by tgy** [comment]
done. restarted shell. still not in PATH

**Comment by Lesmiscore** [comment]
Weird.
How about `brew update; brew reinstall yt-dlp/taps/yt-dlp`?

**Comment by rpendleton** [comment]
> Can you please run `brew reinstall yt-dlp/taps/yt-dlp` and try yt-dlp command again?

@Lesmiscore Looks like that fixed it for me!

```
$ rm /usr/local/bin/yt-dlp

$ brew update
Updated Homebrew from 74e933caa to e4dab6384.
Updated 4 taps (yt-dlp/taps, homebrew/cask-versions, homebrew/core and homebrew/cask).
...

$ brew reinstall yt-dlp
...
==> Reinstalling yt-dlp/taps/yt-dlp
...

$ yt-dlp --version
2022.06.29
```

**Comment by tgy** [comment]
confirm this worked for me too!

**Comment by AniOSDeveloper** [comment]
Just now I ran the command below, and it prints out the version number, it works now!

`brew install yt-dlp/taps/yt-dlp`
`yt-dlp --version`

**Comment by tuckcodes** [comment]
`brew reinstall yt-dlp
brew link --overwrite yt-dlp`
