### ISSUE TITLE
Request to add extractor for kimcartoon.li

### ISSUE THREAD

**Issue by mohit83k** [yt-dlp/yt-dlp#4224]
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.06.29** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Example URLs

- Single Video: https://kimcartoon.li/Cartoon/Swan-Boy/Episode-1-Swan-Boy-and-Noel-Get-In-A-Fight
- Playlist: https://kimcartoon.li/Cartoon/Swan-Boy

### Description

This website have many cartoon. It would be cool if we can download cartoons in batch from this website. 
Site: https://kimcartoon.li

### Verbose log

```shell
[debug] Command-line config: ['-vU', 'https://kimcartoon.li/Cartoon/Swan-Boy/Episode-1-Swan-Boy-and-Noel-Get-In-A-Fight']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.06.29 [9d339c4]
[debug] Python 3.9.6 (CPython 64bit) - Windows-10-10.0.19042-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.4-full_build-www.gyan.dev (setts), ffprobe 4.4-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.11.0, brotli-1.0.9, certifi-2019.03.09, mutagen-1.45.1, sqlite3-2.6.0, websockets-9.1
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
[debug] Downloading _update_spec from https://github.com/yt-dlp/yt-dlp/releases/download/2022.06.29/_update_spec
Latest version: 2022.06.29, Current version: 2022.06.29
yt-dlp is up to date (2022.06.29)
[debug] [generic] Extracting URL: https://kimcartoon.li/Cartoon/Swan-Boy/Episode-1-Swan-Boy-and-Noel-Get-In-A-Fight
[generic] Episode-1-Swan-Boy-and-Noel-Get-In-A-Fight: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] Episode-1-Swan-Boy-and-Noel-Get-In-A-Fight: Downloading webpage
[generic] Episode-1-Swan-Boy-and-Noel-Get-In-A-Fight: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://kimcartoon.li/Cartoon/Swan-Boy/Episode-1-Swan-Boy-and-Noel-Get-In-A-Fight
Traceback (most recent call last):
  File "C:\Users\mohit\AppData\Roaming\Python\Python39\site-packages\yt_dlp\YoutubeDL.py", line 1420, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\mohit\AppData\Roaming\Python\Python39\site-packages\yt_dlp\YoutubeDL.py", line 1490, in __extract_info
    ie_result = ie.extract(url)
  File "C:\Users\mohit\AppData\Roaming\Python\Python39\site-packages\yt_dlp\extractor\common.py", line 640, in extract
    ie_result = self._real_extract(url)
  File "C:\Users\mohit\AppData\Roaming\Python\Python39\site-packages\yt_dlp\extractor\generic.py", line 4130, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://kimcartoon.li/Cartoon/Swan-Boy/Episode-1-Swan-Boy-and-Noel-Get-In-A-Fight
```

**Comment by nyuszika7h** [comment]
> * [x]  I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)
