### ISSUE TITLE
ffmpeg location

### ISSUE THREAD

**Issue by codethinki** [yt-dlp/yt-dlp#4225]
### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.06.29** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Question

every time i specify -x for only audio i get "ERROR: Postprocessing: ffprobe and ffmpeg not found. Please install or provide the path using --ffmpeg-location" at the end of the download, even tho i specifiy the correct directory containing the binarys (i installed it via pip so maybe thats wrong)

**Comment by MrRawes** [comment]
Verboose log?

**Comment by codethinki** [comment]
> Verboose log?

![image](https://user-images.githubusercontent.com/89145039/176470024-c5414e2f-5cf6-4a30-aaaf-00becb004d89.png)

**Comment by codethinki** [comment]
![image](https://user-images.githubusercontent.com/89145039/176478554-d3a4094a-c1b7-4688-b09c-7a2da3de8c2e.png)

**Comment by codethinki** [comment]
also there is no ffmpeg.py in the ffmpeg dir it contains video.py, __init__.py, audio.py, image.py, stream.py idk why it says ffmpeg.py in the log. There is only ffprobe.py in the ffprobe dir

**Comment by pukkandan** [comment]
You have the ffmpeg Python module, which is not what is needed. Download the executable from https://github.com/yt-dlp/ffmpeg-builds
