### ISSUE TITLE
Cannot Download from Spankbang

### ISSUE THREAD

**Issue by SuperPoorMan** [yt-dlp/yt-dlp#4226]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.06.29** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Canada

### Description

Here is my shameful link that I cannot download
https://spankbang.com/6xojj/video/kati3kat+mommy+milkers
This happens on all videos from this website lately and I am not entirely sure why. The error message is just "I can't do it" kinda situation.

This is the error message that it spits out

yt-dlp https://spankbang.com/6xojj/video/kati3kat+mommy+milkers [SpankBang] 6xojj: Downloading webpage ERROR: [SpankBang] 6xojj: Unable to download webpage: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using yt-dlp -U

### Verbose log

```shell
yt-dlp https://spankbang.com/6xojj/video/kati3kat+mommy+milkers [SpankBang] 6xojj: Downloading webpage ERROR: [SpankBang] 6xojj: Unable to download webpage: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using yt-dlp -U


I don't know what this section is really for, so imma put the error message here again. I am using Tartube to download the videos.
```

**Comment by Dean-Corso** [comment]
The reason why you get response "404 Not Found" is that the video is set to private mode ("This Video Is Private") and yt-dlp dosen't support grabbing private video datas from Spankbang so far I know. So in this case it's no bug.

**Comment by SuperPoorMan** [comment]
but it isn't a private video... and other videos don't work either

**Comment by SuperPoorMan** [comment]
Sorry, I check the link in a seperate chrome profile and it is indeed private, however it doesn't fix the issue with regular videos also not working.
