### ISSUE TITLE
New site request:  gizmoplex

### ISSUE THREAD

**Issue by gaming-hacker** [yt-dlp/yt-dlp#4232]
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.06.29** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Worldwide

### Example URLs

https://www.gizmoplex.com/mst3k-season01/videos/mst3k-022-thecrawlingeye

### Provide a description that is worded well enough to be understood

I am looking to old episodes which have no DRM and free (no cost) to download.  Free account with username/password is easy to generate.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '-u', 'PRIVATE', '-p', 'PRIVATE', 'https://www.gizmoplex.com/mst3k-season01/videos/mst3k-022-thecrawlingeye']
[debug] User config "/Users/glen/.config/yt-dlp.conf": ['--ignore-errors', '--no-warnings', '--geo-bypass', '--yes-playlist', '--no-mtime', '--progress', '--continue', '--no-part', '--console-title', '--restrict-filenames', '--encoding', 'UTF-8', '--prefer-ffmpeg', '--downloader', 'm3u8:native', '--retries', '100', '--buffer-size', '16k', '--bidi-workaround', '--fragment-retries', '100', '--audio-format', 'best', '--audio-quality', '0', '--recode-video', 'mp4', '--concurrent-fragments', '2', '--rm-cache-dir', '--format', 'mp4', '--audio-format', 'flac', '--remux-video', 'mp4', '--recode-video', 'mp4', '--output=%(playlist_index)s_%(title)s.%(ext)s']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.06.29 [9d339c4] (zip)
[debug] Python 3.10.5 (CPython 64bit) - macOS-10.13.6-x86_64-i386-64bit 
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.4.git (fdk,setts), ffprobe 4.4.git, rtmpdump 2.4
[debug] Optional libraries: sqlite3-2.6.0
[debug] Proxy map: {}
.emoving cache dir /Users/glen/.cache/yt-dlp .
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
[debug] Downloading _update_spec from https://github.com/yt-dlp/yt-dlp/releases/download/2022.06.29/_update_spec
Latest version: 2022.06.29, Current version: 2022.06.29
yt-dlp is up to date (2022.06.29)
[debug] [generic] Extracting URL: https://www.gizmoplex.com/mst3k-season01/videos/mst3k-022-thecrawlingeye
[generic] mst3k-022-thecrawlingeye: Requesting header
[generic] mst3k-022-thecrawlingeye: Downloading webpage
[generic] mst3k-022-thecrawlingeye: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://www.gizmoplex.com/mst3k-season01/videos/mst3k-022-thecrawlingeye
Traceback (most recent call last):
  File "/Users/glen/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1420, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/glen/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1490, in __extract_info
    ie_result = ie.extract(url)
  File "/Users/glen/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 640, in extract
    ie_result = self._real_extract(url)
  File "/Users/glen/local/bin/yt-dlp/yt_dlp/extractor/generic.py", line 4130, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.gizmoplex.com/mst3k-season01/videos/mst3k-022-thecrawlingeye
```

**Comment by Ashish0804** [comment]
Assuming u have confirmed the linked video doesn't have drm for sure, feel free to email me the account details @ `Ashish08@protonmail.com` if u want me to give a try.

**Comment by pukkandan** [comment]
Could you try passing logged in cookies to yt-dlp?

**Comment by gooseears** [comment]
Just for anyone searching, gizmoplex does work.  Log in first from the browser, and you will also need ffmpeg to encode the file properly: https://github.com/yt-dlp/FFmpeg-Builds

`yt-dlp --cookies-from-browser firefox --ffmpeg-location "ffmpeg\bin" https://www.gizmoplex.com/mst3k/season:1/videos/mst3k-022-thecrawlingeye -o "1.mp4"`
