### ISSUE TITLE
southpark.lat not working

### ISSUE THREAD

**Issue by Scrooge200FES** [yt-dlp/yt-dlp#4233]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.06.29** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United States, Spain

### Provide a description that is worded well enough to be understood

I am on the latest version and trying to download from southpark.lat, but it seems unable to get the HTML page. This site is region locked to Spanish-speaking countries, and I am trying to access it from the United States. I have checked and my yt-dlp installation is complete.

URLs:
https://www.southpark.lat/episodios/46s8wh/south-park-bajalo-temporada-21-ep-2 (Spanish)
https://www.southpark.lat/en/episodes/46s8wh/south-park-put-it-down-season-21-ep-2 (English)

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
C:\[...]>yt-dlp -vU https://www.southpark.lat/episodios/46s8wh/south-park-bajalo-temporada-21-ep-2
[debug] Command-line config: ['-vU', 'https://www.southpark.lat/episodios/46s8wh/south-park-bajalo-temporada-21-ep-2']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.06.29 [9d339c4] (win32_exe)
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 2022-05-12-git-30e2bb0f64-full_build-www.gyan.dev (setts), ffprobe 2022-05-12-git-30e2bb0f64-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
[debug] Downloading _update_spec from https://github.com/yt-dlp/yt-dlp/releases/download/2022.06.29/_update_spec
Latest version: 2022.06.29, Current version: 2022.06.29
yt-dlp is up to date (2022.06.29)
[debug] [southpark.lat] Extracting URL: https://www.southpark.lat/episodios/46s8wh/south-park-bajalo-temporada-21-ep-2
[southpark.lat] south-park-bajalo-temporada-21-ep-2: Downloading webpage
ERROR: [southpark.lat] 46s8wh: Unable to download webpage: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 640, in extract
  File "yt_dlp\extractor\mtv.py", line 325, in _real_extract
  File "yt_dlp\extractor\common.py", line 1051, in _download_webpage
  File "yt_dlp\extractor\common.py", line 1002, in download_content
  File "yt_dlp\extractor\common.py", line 834, in _download_webpage_handle
  File "yt_dlp\extractor\common.py", line 791, in _request_webpage

  File "yt_dlp\extractor\common.py", line 773, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 3596, in urlopen
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 563, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 755, in http_error_302
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found
```

**Comment by gamer191** [comment]
> This site is region locked to Spanish-speaking countries, and I am trying to access it from the United States

So why do you expect it to work with yt-dlp?

**Comment by pukkandan** [comment]
> - [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details

**Comment by Scrooge200FES** [comment]
I was hoping that I could use this to rip the Spanish versions of episodes. If I use yt-dlp on southpark.cc's Spanish episodes, they just download in English, even though they have Spanish audio when played in a browser.
