### ISSUE TITLE
For the latest Windows .zip version(s), should I be replacing the entire folder or just overwriting the existing files?

### ISSUE THREAD

**Issue by rgiuffre** [yt-dlp/yt-dlp#4234]
### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.06.29** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Instead of using the compiled .exe version, I normally use the .zip version and extract it to a folder. Should I delete the old contents of the folder, or is it ok (or preferred) to just overwrite the files that are contained in the .zip version.

Thanks!

Bobby G.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
Don't think it matters, but if you want to be on the safe side, delete everything first
