### ISSUE TITLE
Store all downloads in a local directory before copying the final file out

### ISSUE THREAD

**Issue by peterhoeg** [yt-dlp/yt-dlp#4235]
### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.06.29** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

When saving to a NAS, the downloaded file needs to cross the network multiple times before the final file is written out which makes things slow.

The workaround is of course to download to a local directory and then manually copy the final file out afterwards, but it would be neat if it was possible to do the following:

1. go the directory where the final file should end up
2. start the download
3. the downloaded file as well as all temporary files are written to a configurable location (ideally through yt-dlp.conf)
4. once the final file is ready, it is moved out to $(pwd) (item 1 above)

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
See `--paths`

**Comment by peterhoeg** [comment]
That does indeed do the trick!
