### ISSUE TITLE
[Reddit] add comments & replies from pushshift API

### ISSUE THREAD

**Issue by upintheairsheep** [yt-dlp/yt-dlp#4236]
### Checklist

- [X] I'm requesting a site-specific feature
- [X] I've verified that I'm running yt-dlp version **2022.06.29** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Southern California, USA (not telling the exact town I'm living in for privacy reasons unless required)

### Example URLs

https://www.reddit.com/r/DanteTimberwolf/comments/pf8x37/i_visualized_a1_of_anywhere_at_the_end_of_the/

### Provide a description that is worded well enough to be understood

The pushshift API has Reddit comments to download.

see  https://www.reddit.com/r/pushshift/comments/htysaw/generating_tree_of_comments_again_from_comment/

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
W
```

**Comment by Ashish0804** [comment]
ah yes
the new compression algorithms are amazing. It compressed the whole verbose output to just `W`.  Science is truly amazing.

**Comment by pukkandan** [comment]
I warned you multiple times not to post incomplete issues. You have been temporarily blocked for spamming with them. If you continue this when the block lifts, you will be permanently banned
