### ISSUE TITLE
How do I download <=1080p video as an mp4 and the best audio as an mp3 in Python

### ISSUE THREAD

**Issue by kevinlinxc** [yt-dlp/yt-dlp#4237]
### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.06.29** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I read through the README options but it's a firehose of information and I really just want to know if there is an abstracted way to download the best .mp4 video (but not higher than 1080p) and best .mp3 audio given a link. I typically use 4k Video Downloader for this kind of stuff and they seem to have it figured out, but I'm making a Python webapp for my family members to make it easier for them than an extension, app, or site with limitations.  I used 'b' and 'ba' format which I thought would be best but I did not get the best.

Here's what I have:

```Python
import os
import yt_dlp

cur_dir = os.getcwd()

def download_video(link, id):
    youtube_dl_options = {
        "format": "b",  # This will select the specific resolution typed here
        "outtmpl": os.path.join(cur_dir, f"{id}.mp4")
    }
    with yt_dlp.YoutubeDL(youtube_dl_options) as ydl:
        return ydl.download([link])


def download_audio(link, id):
    youtube_dl_options = {
        "format": "ba",  # This will select the specific resolution typed here
        "outtmpl": os.path.join(cur_dir, f"{id}.mp3")
    }
    with yt_dlp.YoutubeDL(youtube_dl_options) as ydl:
        return ydl.download([link])
```

The video seems to have downloaded the 720p, and the audio is unplayable and seems to actually be a .webm file

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Python's output

```shell
[youtube] WajEW5HPnuw: Downloading webpage
[youtube] WajEW5HPnuw: Downloading android player API JSON
[youtube] WajEW5HPnuw: Downloading webpage
[youtube] WajEW5HPnuw: Downloading android player API JSON
[info] WajEW5HPnuw: Downloading 1 format(s): 22
[download] Destination: K:\Big_Pycharm_Projects\streamlit-yt-downloader\WajEW5HPnuw.mp4
[download] 100% of 24.98MiB in 00:00                   
[youtube] WajEW5HPnuw: Downloading webpage
[youtube] WajEW5HPnuw: Downloading android player API JSON
[info] WajEW5HPnuw: Downloading 1 format(s): 251
[download] Destination: K:\Big_Pycharm_Projects\streamlit-yt-downloader\WajEW5HPnuw.mp3
[download] 100% of 5.90MiB in 00:00
```

**Comment by pukkandan** [comment]
> download the best .mp4 video (but not higher than 1080p)

`'format_sort': ['res:1080', 'ext:mp4:m4a']`

> and best .mp3 audio given a link

Youtube does not serve mp3. You have to download and convert it. See https://github.com/yt-dlp/yt-dlp#Extract_audio

> and the audio is unplayable and seems to actually be a .webm file

Naming the file mp4/mp3 does not make it so. Use `%(ext)s` in the output template to get the current extension

**Comment by kevinlinxc** [comment]
Will ext:mp4:m4a download m4a files sometimes? Can I just put mp4 to only get mp4s?

**Comment by pukkandan** [comment]
It downloads mp4 video, m4a audio and merges them into mp4

**Comment by kevinlinxc** [comment]
Seems to work, thank you. I ended up using moviepy to convert mp4 to mp3, I'm not sure how good that audio will be but I usually don't need max quality anyway
