### ISSUE TITLE
Storage Location and small feature request

### ISSUE THREAD

**Issue by xWass** [yt-dlp/yt-dlp#4238]
### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.06.29** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

So by default, my yt-dlp stores all of the downloads inside of my user folder, not in a subdirectory. I think that it should at least create a new folder and store all downloads inside of it. I believe there is a way to specify output location, but I simply don't remember it and spent some time cleaning out my user folder instead. 

(also at end of completion, open location of last output in file explorer thx)

windows 10 btw^

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by xWass** [comment]
edit: question is how do i actually specify an output location outside of default

**Comment by pukkandan** [comment]
See `--paths` and `--output` options on readme
