### ISSUE TITLE
Do I need to know about the cookie so that youtube knows I have downloaded/seen that video ???

### ISSUE THREAD

**Issue by shirishag75** [yt-dlp/yt-dlp#4239]
### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.06.29** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I just filed for a new release the day you packaged it and lo-behold couple of days later, we have the new release in Debian. 

```
$ apt-cache policy yt-dlp
yt-dlp:
  Installed: 2022.06.29-1
  Candidate: 2022.06.29-1
  Version table:
 *** 2022.06.29-1 100
        100 http://deb.debian.org/debian unstable/main amd64 Packages
        100 /var/lib/dpkg/status
     2022.06.22.1-1 900
        900 http://deb.debian.org/debian testing/main amd64 Packages
```

Kudos to the Debian maintainer. He closed the issue even though he did the needful. 

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1014040

Now my question starts due to the  new feature that has been added which was missing for a long-time i.e. 

https://github.com/yt-dlp/yt-dlp/commit/9d339c41e25b1a77495cebe3fbdc95e2cb837776

 [extractor/youtube] Mark videos as fully watched by [Brett824](https://github.com/Brett824)

Now do I store the youtube cookie somewhere or would yt-dlp know automatically that it is me. I tried to find more about the bug/issue/code but couldn't find anything at 

https://github.com/Brett824

Looking forward to know more, and thank you for you continously developing it and making it easier and more powerful for all of us :)

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
See `--cookies` and `--cookies-from-browser` options in the readme

Note that there are reports of the "fully watched" feature not working

**Comment by shirishag75** [comment]
For cookies I get - 

--cookies FILE                  Netscape formatted file to read cookies from
                                    and dump cookie jar in

```
 --cookies-from-browser BROWSER[+KEYRING][:PROFILE]
                                    The name of the browser and (optionally) the
                                    name/path of the profile to load cookies
                                    from, separated by a ":". Currently
                                    supported browsers are: brave, chrome,
                                    chromium, edge, firefox, opera, safari,
                                    vivaldi. By default, the most recently
                                    accessed profile is used. The keyring used
                                    for decrypting Chromium cookies on Linux can
                                    be (optionally) specified after the browser
                                    name separated by a "+". Currently supported


```

What I wanna do is to have that cookie in a file or something so that yt-dlp shares it automatically without me telling it every time, go read firefox or chrome or chromium. That makes no sense. 

If there is a way to do that, please share that. Right now I got an empty file at - 

```
~/.config/yt-dlp$ cat config  
~/.config/yt-dlp$
```

**Comment by pukkandan** [comment]
> --cookies FILE Netscape formatted file to read cookies from
and dump cookie jar in

Add this to your config file! I don't get what you are confused about here

**Comment by shirishag75** [comment]
> --cookies FILE

Would this work, I ask so that ot gets the latest cookies from my firefox profile - 
`
--cookies ~/.mozilla/abcdefgh.default/cookies.sqlite`

I have just a fictious profile just as an example.

**Comment by pukkandan** [comment]
No, see https://www.reddit.com/r/youtubedl/wiki/cookies

**Comment by pukkandan** [comment]
> Would this work, I ask so that ot gets the latest cookies from my firefox profile -
--cookies ~/.mozilla/abcdefgh.default/cookies.sqlite

If this is what you want, use `--cookies-from-browser`. But you just said above you don't want it to read from browser profile...

**Comment by shirishag75** [comment]
> > Would this work, I ask so that ot gets the latest cookies from my firefox profile -
> > --cookies ~/.mozilla/abcdefgh.default/cookies.sqlite
> 
> If this is what you want, use `--cookies-from-browser`. But you just said above you don't want it to read from browser profile...

Think we are misunderstanding each other. What I meant was it should read it automatically. from the config file so I shouldn't have to use the command `--cookies-from-browser. Is this good enough 

```
~/.config/yt-dlp$ cat config 
--cookies-from-browser firefox-esr
```

**Comment by pukkandan** [comment]
that option doesnt take path to the exe... Is the doc that hard to understand?

     --cookies-from-browser BROWSER[+KEYRING][:PROFILE]
                                    The name of the browser and (optionally) the
                                    name/path of the profile to load cookies
                                    from, separated by a ":". ...

So `--cookies-from-browser firefox:~/.mozilla/abcdefgh.default`

**Comment by shirishag75** [comment]
> that option doesnt take path to the exe... Is the doc that hard to understand?
> 
> ```
>  --cookies-from-browser BROWSER[+KEYRING][:PROFILE]
>                                 The name of the browser and (optionally) the
>                                 name/path of the profile to load cookies
>                                 from, separated by a ":". ...
> ```
> 
> So `--cookies-from-browser firefox:~/.mozilla/abcdefgh.default`

cool, that was what I was looking for, thak you very much :)
