### ISSUE TITLE
[Feature Request] embed author, title, description directly into the video itself

### ISSUE THREAD

**Issue by shakeyourbunny** [yt-dlp/yt-dlp#424]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running yt-dlp version **2021.06.09**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description

Would it be possible to embed the author, title and date of the video in the corresponding fields in the video itself withlike eg --embed-default-metadata?

In addition, it would be really helpful if there would be a way to embed the video description of Youtube videos into the description field with an --embed-description or such?

WRITE DESCRIPTION HERE

**Comment by pukkandan** [comment]
`--embed-metadata`

**Comment by pukkandan** [comment]
Can re-open if you can clarify how the requested feature is any different from --add-metadata
