### ISSUE TITLE
Allow multiple file output with repeated `-o` options

### ISSUE THREAD

**Issue by za3k** [yt-dlp/yt-dlp#4243]
### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.06.29** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

This is a feature request to support a usecase I have. I have a suggested fix, but first let me give context, in case someone has a better idea for this class of problem. I'm writing an auto-downloader, which periodically runs youtube-dl and saves the files. I want to save things by playlist, by creator, by date, to a master archive, etc. The problem I run into, is that a video usually appears in multiple folders in my use case, with different names. Ideally, the downloader would detect this (see a file is already downloaded by youtube ID) and avoid downloading it again, instead re-using the existing download.

My proposed fix is to allow multiple `--output` options, saving a file multiple places with a single command. The files could be copied, symlinked, or even hardlinked. There are a few advantages to this over running multiple commands:
- Only a single copy of the video is downloaded (saves bandwidth)
- Only a single copy of the video is stored on disk, depending on implementation (saves disk space)
- This allows the use case at ALL if using the option `--download-archive`. Otherwise, the second and later commands would fail because the ID is already listed in the archive.

This isn't a perfect solution, in that a later download will still fail to "know about" the existing copies. But it has the advantage of being easy to understand, and maybe being easy to implement.

Currently I've written a workaround wrapper program that something very similar this with some dry-run metadata outputs, but it's not pretty. It would be cool if yt-dlp supported this directly. My workaround looks more like instead adding a "--master-output" option. If neither file exists, it saves two output files. If the "master" output version exists, it instead uses that existing copy. My feeling is that while my workaround solves *my* use case better, multiple `-o` outputs seems easier to explain.

I don't think anything in the problem is youtube-specific except maybe `--download-archive`, and certainly nothing in the proposed solution is.

### Provide verbose output that clearly demonstrates the problem
(N/A)
- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by ischmidt20** [comment]
You can probably already do this by passing the copy/symlink command with `--exec`

**Comment by Ashish0804** [comment]
>The files could be copied, symlinked, or even hardlinked.

Not see how this is in scope of dlp tbh. @ischmidt20 is correct that this should be handled by by u via exec. or via some wrapper. 

Also adding multiple `-o` will proly be a headache to agree upon how multiple -o plays along with other options.

**Comment by za3k** [comment]
`-exec` sounds great, I just didn't realize it could have multiple arguments with template formatting. Let me give it a try and see if I run into issues with `--download-archive` still. If you don't hear back in a week or two, feel free to close this :)

**Comment by za3k** [comment]
I agree, this works much better. It looks like --exec handles quotes in a reasonable way, too. I would still love multiple --exec options, which I will open as a separate issue.

And yes, as I expected `--download-archive` stops any --exec, even using `before_dl:`.

**Comment by za3k** [comment]
So I initially thought this would work out, and to some extent it does, but I run into issues down the line with the fact that it's plain string substitution. This means it's very hard to deal with videos with special characters in the title: quotes, slashes, etc. If I was on windows I would have even more issues.

My best bet currently looks to be giving up on constructing a command line, and instead writing a custom shell script and calling exec on that. Even then I expect quotes inside video names to break things.

Any bright ideas would be appreciated!

**Comment by pukkandan** [comment]
Use `%(...)q` to make `--exec` quote arguments correctly

**Comment by za3k** [comment]
That is useful, thanks for the help! I feel dumb for skipping that manpage section--I assumed it was just copied python string formatting documentation. Like a dummy. There are so many useful new options.

There's no way to ex. chain `S` (sanitize) and `q` (quote), right?
