### ISSUE TITLE
ABC iView Extractor Error (KeyError: 'Playlist')

### ISSUE THREAD

**Issue by naigy81** [yt-dlp/yt-dlp#4244]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.06.29** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Australia

### Provide a description that is worded well enough to be understood

Hi, I have been using yt-dlp to download from ABC iview for months without issue. Today I have had the following error

`yt-dlp.exe -v https://iview.abc.net.au/show/rosehaven/series/3/video/CO1710T003S00
[debug] Command-line config: ['-v', 'https://iview.abc.net.au/show/rosehaven/series/3/video/CO1710T003S00']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.06.29 [9d339c4] (win32_exe)
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.22000-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg git-2020-08-31-4a11a6f, ffprobe git-2020-08-31-4a11a6f
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Using fake IP 1.158.159.9 (AU) as X-Forwarded-For
[debug] [abc.net.au:iview] Extracting URL: https://iview.abc.net.au/show/rosehaven/series/3/video/CO1710T003S00
[abc.net.au:iview] CO1710T003S00: Downloading JSON metadata
ERROR: CO1710T003S00: An extractor error has occurred. (caused by KeyError('playlist')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 640, in extract
  File "yt_dlp\extractor\abc.py", line 198, in _real_extract
KeyError: 'playlist'`

I need an account when viewing in a web browser and have for about 3 - 4 months however have been able to download through yt-dlp without any credentials up until about 2 - 3 weeks ago when I last downloaded a show. I have tried running this with my user credentials as well and still get the same error. 

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp.exe -vU https://iview.abc.net.au/show/rosehaven/series/3/video/CO1710T003S00
[debug] Command-line config: ['-vU', 'https://iview.abc.net.au/show/rosehaven/series/3/video/CO1710T003S00']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.06.29 [9d339c4] (win32_exe)
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.22000-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg git-2020-08-31-4a11a6f, ffprobe git-2020-08-31-4a11a6f
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
[debug] Downloading _update_spec from https://github.com/yt-dlp/yt-dlp/releases/download/2022.06.29/_update_spec
Latest version: 2022.06.29, Current version: 2022.06.29
yt-dlp is up to date (2022.06.29)
[debug] Using fake IP 1.142.121.192 (AU) as X-Forwarded-For
[debug] [abc.net.au:iview] Extracting URL: https://iview.abc.net.au/show/rosehaven/series/3/video/CO1710T003S00
[abc.net.au:iview] CO1710T003S00: Downloading JSON metadata
ERROR: CO1710T003S00: An extractor error has occurred. (caused by KeyError('playlist')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 640, in extract
  File "yt_dlp\extractor\abc.py", line 198, in _real_extract
KeyError: 'playlist'
```

**Comment by gamer191** [comment]
Out of interest, are you using a VPN?

**Comment by gamer191** [comment]
NOTE: this isn't an anti-piracy bullshit legal question (and using a VPN is legal anyways). I'm simply asking because it seems lots of iview errors are related to VPNs

**Comment by pukkandan** [comment]
Pls show verbose log adding cookies and `--no-geo-bypass`

**Comment by gamer191** [comment]
@pukkandan I'll test it tomorrow, but, from past experience, I'm pretty sure that downloading abc iview videos through yt-dlp doesn't require an account

**Comment by naigy81** [comment]
Think you may be on to it. Appears when I tried it not connected to VPN it works (starts to anyway). When I reconnected to VPN I got the following. Will play with my VPN settings and see if I can sort it out as prefer it to work when on VPN. 

[debug] Command-line config: ['-v', '--no-geo-bypass', '--cookies-from-browser', 'chrome', 'https://iview.abc.net.au/video/ZW2030A001S00']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.06.29 [9d339c4] (win32_exe)
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.22000-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg git-2020-08-31-4a11a6f, ffprobe git-2020-08-31-4a11a6f
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[Cookies] Extracting cookies from chrome
[debug] Extracting cookies from: "C:\Users\craig\AppData\Local\Google\Chrome\User Data\Default\Network\Cookies"
[debug] Found local state file at "C:\Users\craig\AppData\Local\Google\Chrome\User Data\Local State"
[Cookies] Extracted 3256 cookies from chrome
[debug] cookie version breakdown: {'v10': 3256, 'other': 0, 'unencrypted': 0}
[debug] Proxy map: {}
[debug] [abc.net.au:iview] Extracting URL: https://iview.abc.net.au/video/ZW2030A001S00
[abc.net.au:iview] ZW2030A001S00: Downloading JSON metadata
ERROR: ZW2030A001S00: An extractor error has occurred. (caused by KeyError('playlist')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 640, in extract
  File "yt_dlp\extractor\abc.py", line 198, in _real_extract
KeyError: 'playlist'

**Comment by naigy81** [comment]
Now working fine on a different VPN server (PrivateVPN Melbourne instead of Brisbane). Not sure why but its working so will keep this in mind for future. Thanks all for your assistance.
