### ISSUE TITLE
yt-dlp configuration issue ???

### ISSUE THREAD

**Issue by shirishag75** [yt-dlp/yt-dlp#4248]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.06.29** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Provide a description that is worded well enough to be understood

I get a traceback whenever I try to download the video, something I probably misunderstood or something/ This is what I came up with. -
```

 ~/.config/yt-dlp$ cat config
--cookies ~/.mozilla/9dzivtwy.default/cookies.sqlite
 --no-keep-fragments
```
Please let me know if I did do any mistakes. 

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
$ yt-dlp -vu -c -f 247 --write-auto-sub
[debug] Command-line config: ['-vu', '-c', '-f', '247', '--write-auto-sub']
[debug] User config "/home/shirish/.config/yt-dlp/config": ['--cookies-from-browser', 'firefox=~/.mozilla/9dzivtwy.default/cookies.sqlite', '--no-keep-fragments']

Usage: yt-dlp [OPTIONS] URL [URL...]

yt-dlp: error: unsupported browser specified for cookies: "firefox=~/.mozilla/9dzivtwy.default/cookies.sqlite". Supported browsers are: brave, chrome, chromium, edge, firefox, opera, safari, vivaldi
shirish@debian:"02 Jul 2022 19:48:16"
```

**Comment by pukkandan** [comment]
https://github.com/yt-dlp/yt-dlp/issues/4239#issuecomment-1172289573

**Comment by shirishag75** [comment]
I actually used what you shared but it doesn't work :( - 

https://github.com/yt-dlp/yt-dlp/issues/4239#issuecomment-1172289573

**Comment by shirishag75** [comment]
I modified the configuration file and now it works - 
```

$ yt-dlp -c -f 247 6PYl7cosPsM --write-auto-sub
[Cookies] Extracting cookies from firefox
[Cookies] Extracted xxxx cookies from firefox
[youtube] 6PYl7cosPsM: Downloading webpage
[youtube] 6PYl7cosPsM: Downloading android player API JSON
[info] 6PYl7cosPsM: Downloading 1 format(s): 247
[info] Writing video subtitles to: Diving Station _ Subsistence Gameplay _ Part 36 [6PYl7cosPsM].en.vtt
[download] Destination: Diving Station _ Subsistence Gameplay _ Part 36 [6PYl7cosPsM].en.vtt
[download] 100% of 246.26KiB in 00:00
[download] Destination: Diving Station _ Subsistence Gameplay _ Part 36 [6PYl7cosPsM].webm
[download] 100% of 293.18MiB in 00:41
```
$ cat config
--cookies-from-browser firefox
 --no-keep-fragment
