### ISSUE TITLE
VLIVE (vlive.tv) subtitles support for videos and posts

### ISSUE THREAD

**Issue by chiarnglin** [yt-dlp/yt-dlp#4253]
### Checklist

- [X] I'm requesting a site-specific feature
- [X] I've verified that I'm running yt-dlp version **2022.06.29** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United States

### Example URLs

https://www.vlive.tv/video/274092
https://www.vlive.tv/post/0-29172771

### Provide a description that is worded well enough to be understood

Videos and posts from vlive.tv will download, but subtitles don't seem to be discovered for downloading. 
Many videos have English, Spanish, Japanese, Korean subtitles, among other languages. 
Expectation is that the subtitle features ['--write-sub', '--embed-subs', '--sub-lang', 'en'] work for vlive.tv videos. 

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.vlive.tv/post/0-29172771']
[debug] Home config "yt-dlp.conf": ['--write-sub', '--embed-subs', '--sub-lang', 'en', '--ignore-errors', '--continue', '--no-overwrites', '--download-archive', 'progress.txt', '--ffmpeg-location', 'C:\\Users\\chiarng\\ffmpeg\\bin']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.06.29 [9d339c4]
[debug] Python 3.10.5 (CPython 64bit) - Windows-10-10.0.22000-SP0
[debug] Checking exe version: "C:\Users\chiarng\ffmpeg\bin\ffmpeg" -bsfs
[debug] Checking exe version: "C:\Users\chiarng\ffmpeg\bin\ffprobe" -bsfs
[debug] exe versions: ffmpeg 5.0.1-essentials_build-www.gyan.dev (setts), ffprobe 5.0.1-essentials_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loading archive file 'progress.txt'
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
[debug] Downloading _update_spec from https://github.com/yt-dlp/yt-dlp/releases/download/2022.06.29/_update_spec
Latest version: 2022.06.29, Current version: 2022.06.29
yt-dlp is up to date (2022.06.29)
[debug] [vlive:post] Extracting URL: https://www.vlive.tv/post/0-29172771
[vlive:post] 0-29172771: Downloading post JSON metadata
[debug] [vlive] Extracting URL: http://www.vlive.tv/video/283595
[vlive] 283595: Downloading officialVideoPost JSON metadata
[vlive] 283595: Downloading inkey JSON metadata
[vlive] 283595: Downloading JSON metadata
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 283595: Downloading 1 format(s): avc1_1080P
[debug] Invoking http downloader on "http://globalv.p.naverrmc.edgesuite.net/c/read/v2/VOD_ALPHA/global_v_2022_05_16_161/distribution_pathfinder_pf2448100_bac939f2-d4ed-11ec-bd34-a0369ffdada8.mp4?__gda__=1656844769_5f76cae0e425c66f6beea1f834404a7a"
[debug] File locking is not supported. Proceeding without locking
[download] Destination: 헌이 향수 공방 🌹 [283595].mp4
[download] 100% of 414.03MiB in 01:07
[EmbedSubtitle] There aren't any subtitles to embed
[debug] Adding to archive: vlive 283595
```

**Comment by pukkandan** [comment]
The language code is wrong. See `--list-subs` for the correct code

**Comment by chiarnglin** [comment]
Thanks!! I made it work with your suggestion, woo!
