### ISSUE TITLE
Embedding subtitles doesn't work with yt-dlp

### ISSUE THREAD

**Issue by pavel167** [yt-dlp/yt-dlp#4255]
### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.06.29** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Hello,

It seems that embedding subtitles doesn't work.
Probably the problems concerns the type of subtitles.
Anyway the arte.tv provides only .vtt subtitles.
Please see output below.
When I read the output file, there are no subtitles... although in the log there is no indication that the embedding failed.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
(arte_env) pavel@ALABAMA:~/arte_env$ yt-dlp --embed-subs --sub-langs "fr" https://www.arte.tv/fr/videos/104769-000-A/antonio-banderas-et-pedro-almodovar/
[ArteTV] 104769-000-A: Downloading JSON metadata
[ArteTV] 104769-000-A: Downloading m3u8 information
[ArteTV] 104769-000-A: Downloading m3u8 information
[ArteTV] 104769-000-A: Downloading m3u8 information
[ArteTV] 104769-000-A: Downloading m3u8 information
[ArteTV] 104769-000-A: Downloading m3u8 information
[ArteTV] 104769-000-A: Downloading m3u8 information
[info] 104769-000-A: Downloading 1 format(s): VOF-STF-2323+VOF-STF-program_audio_0-VOF
[info] Writing video subtitles to: Antonio Banderas et Pedro Almodovar [104769-000-A].fr.vtt
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 1
[download] Destination: Antonio Banderas et Pedro Almodovar [104769-000-A].fr.vtt
[download] 100% of 95.78KiB in 00:00
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 525
[download] Destination: Antonio Banderas et Pedro Almodovar [104769-000-A].fVOF-STF-2323.mp4
[download] 100% of 1.61GiB in 06:26
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 526
[download] Destination: Antonio Banderas et Pedro Almodovar [104769-000-A].fVOF-STF-program_audio_0-VOF.mp4
[download] 100% of 97.99MiB in 01:59
[Merger] Merging formats into "Antonio Banderas et Pedro Almodovar [104769-000-A].mp4"
Deleting original file Antonio Banderas et Pedro Almodovar [104769-000-A].fVOF-STF-2323.mp4 (pass -k to keep)
Deleting original file Antonio Banderas et Pedro Almodovar [104769-000-A].fVOF-STF-program_audio_0-VOF.mp4 (pass -k to keep)
[EmbedSubtitle] Embedding subtitles in "Antonio Banderas et Pedro Almodovar [104769-000-A].mp4"
Deleting original file Antonio Banderas et Pedro Almodovar [104769-000-A].fr.vtt (pass -k to keep)
(arte_env) pavel@ALABAMA:~/arte_env$
```

**Comment by Ashish0804** [comment]
What is the question?

>When I read the output file, there are no subtitles

proly ur media player is retarded. Dump the mediainfo of the file to be sure

**Comment by eladkarako** [comment]
I've got a suspicion regarding the cause of it,  
can you please try play the same video on it latest mpv from 
https://sourceforge.net/projects/mpv-player-windows/files/64bit/

**Comment by pavel167** [comment]
I guess there are two approaches to embedding subtitles:

- embedding subtitles as metadata and some smart players render particular subtitles in particular frames when playing the video
- render subtitles directly into particular frames so that any player can show subtitles

I think, **yt-dlp** uses 1st approach, correct ?
When I embed subtitles using **GiliSoft** editor, the subtitles are visible with any editor, while yt-dlp embeds the subtitles in such a way that they are not viewed with the default Ubuntu **"Videos"** player and with the default Windows **"Movies & TV"** player. But, Ok, they can be viewed with **VLC** player.
Is there an option to render the subtitles directly in the video frames.

**Comment by eladkarako** [comment]
yep yt-dlp (via ffmpeg) is <a href="https://gist.github.com/eladkarako/db1973f358e6187301abc724d809ca97#file-add-srt-subtitle-to-video-file-mux-no-encoding-using-ffmpeg-md">soft</a>-embedding subtitle streams with a bit of meta-data for labels (fast, multiple subtitles). <a href="https://trac.ffmpeg.org/wiki/HowToBurnSubtitlesIntoVideo">hard</a>-embedding (burn) render the subtitle of your choice as part of the frames (re-encode the video stream - slow).

**Comment by Ashish0804** [comment]
burning subs in video is not in scope of dlp imo. U can play around with downloader and/or post-processor args to do it tho. 

>But, Ok, they can be viewed with VLC player


>default Ubuntu "Videos" player and with the default Windows "Movies & TV" player.

Ask the developers of these software to support .vtt subs.
