### ISSUE TITLE
uninstalling yt-dlp

### ISSUE THREAD

**Issue by honx4amiga** [yt-dlp/yt-dlp#4256]
### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.06.29** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

since my question is called "offtopic" in dropping python 3.6 topic i have to open new topic.

how do i uninstall yt-dlp on linux mint 19 tara (which doesn't have python 3.7) and replace it by that binary file instead?
back in the day i used following two commands to install yt-dlp:
sudo wget https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -O /usr/local/bin/yt-dlp
sudo chmod a+rx /usr/local/bin/yt-dlp

has there been copied only one binary to /usr/local/bin/yt-dlp? no other files?
so do i only have to replace that yt-dlp script file by that standalone yt-dlp file in that same /usr/local/bin folder yt-dlp script used to be?

and is https://github.com/yt-dlp/yt-dlp/releases/download/2022.06.29/yt-dlp_linux that standalone executable for linux we are talking about?

btw. i already searched in readme file (https://github.com/yt-dlp/yt-dlp#readme) for the word "uninstall" but search didn't find anything. and by searching in bugtracker i only find that dropping python 3.6 topic where my questions about uninstalling are hidden and not answered because marked "offtopic".

since my question is no bug report, there is also no output to be attached. this question is only about uninstalling yt-dlp script based on no longer supported python 3.6 and replacing that by yt-dlp standalone...

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by nicolaasjan** [comment]
> how do i uninstall yt-dlp on linux mint 19 tara (which doesn't have python 3.7) and replace it by that binary file instead? back in the day i used following two commands to install yt-dlp: sudo wget https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -O /usr/local/bin/yt-dlp sudo chmod a+rx /usr/local/bin/yt-dlp
> 
> has there been copied only one binary to /usr/local/bin/yt-dlp? no other files?

Those commands only place one file (`yt-dlp`) in `/usr/local/bin` and make it executable.

> so do i only have to replace that yt-dlp script file by that standalone yt-dlp file in that same /usr/local/bin folder yt-dlp script used to be?
> 
> and is https://github.com/yt-dlp/yt-dlp/releases/download/2022.06.29/yt-dlp_linux that standalone executable for linux we are talking about?

Yes and yes. 🙂
You can rename it to just `yt-dlp`, if you wish.
Then usage is the same.

**Comment by gamer191** [comment]
1. run `yt-dlp --rm-cache-dir` (I'm not sure if the standalone executable can reuse the other executable's cache, but better safe than sorry)
2. delete the binary in `/usr/local/bin/yt-dlp`
3. add `yt-dlp-linux` to that folder, and rename it to `yt-dlp`

**Comment by nicolaasjan** [comment]
>     3. add `yt-dlp-linux` to that folder, and rename it to `yt-dlp`

Doesn't that give problems when you want update with `sudo yt-dlp U`?
That's why I suggested the symlink.

**Comment by observeroftime01** [comment]
> > ```
> > 3. add `yt-dlp-linux` to that folder, and rename it to `yt-dlp`
> > ```
> 
> Doesn't that give problems when you want update with `sudo yt-dlp U`? That's why I suggested the symlink.

No, I _think_ you can rename the executable, and _theoretically_ yt-dlp should find the right version to update with. 

I can only speak to Windows systems though, where I rename yt-dlp_min to youtube-dl for comparability's sake, and when I update it, it seems to find the right windows executable (yt_dlp_min.exe) to update with. 

Though I don't see anything wrong with a symlink either. Why rename the executable when you can just create an arbitrarily named link, and leave the executable alone?

**Comment by pukkandan** [comment]
> Doesn't that give problems when you want update with `sudo yt-dlp -U`?

No. The executable variant is determined by other factors, not by filename

**Comment by nicolaasjan** [comment]
> I can only speak to Windows systems though, where I rename yt-dlp_min to youtube-dl for comparability's sake, and when I update it, it seems to find the right windows executable (yt_dlp_min.exe) to update with.

And does that leave your custom name `youtube-dl.exe` intact?

**Comment by observeroftime01** [comment]
> And does that leave your custom name `youtube-dl.exe` intact?

It does. When it updates, it keeps whatever filename I gave it.

**Comment by honx4amiga** [comment]
another question: why is yt-dlp_linux that big in filesize (30mb)? on windows standalone yt-dlp.exe only takes about 14mb so linux standalone is twice as big...

**Comment by nicolaasjan** [comment]
> another question: why is yt-dlp_linux that big in filesize (30mb)? on windows standalone yt-dlp.exe only takes about 14mb so linux standalone is twice as big...

Maybe that's because the Windows executable is [UPX-compressed](https://en.wikipedia.org/wiki/UPX)?
I don't know why UPX is not applied on the Linux executable.

**Comment by pukkandan** [comment]
> > another question: why is yt-dlp_linux that big in filesize (30mb)? on windows standalone yt-dlp.exe only takes about 14mb so linux standalone is twice as big...
> 
> Maybe that's because the Windows executable is [UPX-compressed](https://en.wikipedia.org/wiki/UPX)? I don't know why UPX is not applied on the Linux executable.

I don't know either - and honestly, I can't be bothered to look into it. If anyone wants to "fix" this, feel free to try

Closing since original question is answered

**Comment by Lesmiscore** [comment]
All binaries (including embedded shared libraries) from yt-dlp doesn't have UPX applied.

**Comment by nicolaasjan** [comment]
> All binaries (including embedded shared libraries) from yt-dlp doesn't have UPX applied.

Oh, I saw UPX being applied when compiling myself (I have UPX in my PATH).
There is also [this line](https://github.com/yt-dlp/yt-dlp/blob/385f7f38957e21701593ff1229295bf4ca00eba0/pyinst.py#L31) in `pyinst.py`:
`'--upx-exclude=vcruntime140.dll'`

**Comment by gamer191** [comment]
Would UPX compression make yt-dlp slower?

**Comment by nicolaasjan** [comment]
> Would UPX compression make yt-dlp slower?

From:
https://upx.github.io/

> very fast decompression: ~10 MB/sec on an ancient Pentium 133, ~200 MB/sec on an Athlon XP 2000+.

Pyinstaller will use UPX by default if that's installed and in PATH.

There is ~1MB difference in file size (Windows .exe):
`13.484.821 bytes` vs `12.307.928 bytes` with UPX.
