### ISSUE TITLE
[youtube] can't get playlist id if the first video is not available

### ISSUE THREAD

**Issue by idMysteries** [yt-dlp/yt-dlp#4257]
### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.06.29** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Because of this, I can't get information about the playlist:
```
ERROR: [youtube] M_tpbaqFMKA: Premieres in 2 hours
```
This command will not output anything:
``` ps1
yt-dlp --print "%(playlist_id)s" --no-download-archive --no-mark-watched --playlist-end 1 https://www.youtube.com/playlist?list=WL
```

Is it possible to make the parser work normally with premieres on YouTube?
Why does it display an error when I explicitly request a "--print"?

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
To answer the original question, it is because that is how youtube-dl behaves. Changing this default behavior can be problematic. That is why I added the new option `--ignore-no-formats-error` instead
