### ISSUE TITLE
[Question] How to show download progress in file size percents format when downloading with aria2c

### ISSUE THREAD

**Issue by S-hdyn** [yt-dlp/yt-dlp#426]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE
So I just discovered aria2c in yt-dlp. It was great because without -N option, the downloads didn't got errors yet. But when downloading with aria2c, there's no download precentage and file size yet. Any idea how to show that? And sorry for my duplicate issue yesterday.

**Comment by pukkandan** [comment]
Currently not possible. We are not parsing the output and aria2c seems to only want to show each fragment's progress separately. If you know any way to make aria itself show a total percent, let me know

**Comment by pukkandan** [comment]
> Any idea how to show that? And sorry for my duplicate issue yesterday.

No worries

**Comment by S-hdyn** [comment]
> Currently not possible. We are not parsing the output and aria2c seems to only want to show each fragment's progress separately. If you know any way to make aria itself show a total percent, let me know

Okay. No problems. Unfortunately I didn't know about programming stuff. So I cannot tell you. But I hope in the future this will be realized for enhancements.  Closed thanks. :)
