### ISSUE TITLE
Windows .exe version vs. the .zip version

### ISSUE THREAD

**Issue by rgiuffre** [yt-dlp/yt-dlp#4265]
### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.06.29** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Are there any differences between running the solo .exe Windows version vs using the .zip Windows version and extracting all of the files into a folder?

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
See https://github.com/yt-dlp/yt-dlp/issues/1024 and related issues

**Comment by rgiuffre** [comment]
I read through #1024, but I don't see a simple answer to my question. Does the compiled .exe have everything the .zip has, or is it missing something/anything? If they are exactly the same, then the single .exe would obviously be easier to update than 118 files from the .zip file overwriting the entire folder...

**Comment by pukkandan** [comment]
They are not "exactly" the same. The zip file is the solution to https://github.com/yt-dlp/yt-dlp/issues/661 and https://github.com/yt-dlp/yt-dlp/issues/890. If you don't care about those, the exe is obviously recommended.
