### ISSUE TITLE
Naver TV download not working

### ISSUE THREAD

**Issue by lunamoth** [yt-dlp/yt-dlp#4271]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.06.29** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

South Korea

### Provide a description that is worded well enough to be understood

Naver TV download not working

https://tv.naver.com/

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
C:\UTIL\yt-dlg>yt-dlp -vu https://tv.naver.com/v/27746776
[debug] Command-line config: ['-vu', 'https://tv.naver.com/v/27746776']
Type account password and press [Return]:
[debug] Encodings: locale cp949, fs utf-8, pref cp949, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.06.29 [9d339c4] (win32_exe)
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg N-107010-g0dcbe1c1aa-20220526 (setts), ffprobe N-107010-g0dcbe1c1aa-20220526
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
```

**Comment by gamer191** [comment]
That's not a full verbose log and doesn't demonstrate the error

**Comment by Lesmiscore** [comment]
The correct spelling you're asked to type is `-vU` (a dash, little V, capital U).
With little U, you're setting username for log in!

**Comment by gamer191** [comment]
Apologies @lunamoth, I assumed you had just only posted a partial verbose log (believe it or not, lots of people do that). Anyway, can you please do what Lesmiscore said and then post a new verbose log?

**Comment by lunamoth** [comment]
Sorry for the inconvenience. log again

---

C:\UTIL\yt-dlg>yt-dlp -vU https://tv.naver.com/v/27746776
[debug] Command-line config: ['-vU', 'https://tv.naver.com/v/27746776']
[debug] Encodings: locale cp949, fs utf-8, pref cp949, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.06.29 [9d339c4] (win32_exe)
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg N-107010-g0dcbe1c1aa-20220526 (setts), ffprobe N-107010-g0dcbe1c1aa-20220526
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
[debug] Downloading _update_spec from https://github.com/yt-dlp/yt-dlp/releases/download/2022.06.29/_update_spec
Latest version: 2022.06.29, Current version: 2022.06.29
yt-dlp is up to date (2022.06.29)
[debug] [Naver] Extracting URL: https://tv.naver.com/v/27746776
[Naver] 27746776: Downloading JSON metadata
[Naver] 27746776: Downloading JSON metadata
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 27746776: Downloading 1 format(s): avc1_1080P
[debug] Invoking http downloader on "http://b01-kr-cdn.vod.naver.net/navertv/c/read/v2/VOD_ALPHA/navertv_2022_07_04_308/551f73ff-fb76-11ec-ba5e-48df37269fd0.mp4?_lsu_sa_=6665b1fb21d462e637dbd58a6c75b6b32e0c3e68d50e5f6334076cc5871636e5f527aa316b75db06601735320e3ecb49610bfee0615069055294ed96784afd3f672bfe7a8f2bd590460cef1c94f0626d"
[download] Got server HTTP error: <urlopen error [Errno 11004] getaddrinfo failed>. Retrying (attempt 1 of 10) ...
[download] Got server HTTP error: <urlopen error [Errno 11004] getaddrinfo failed>. Retrying (attempt 2 of 10) ...
[download] Got server HTTP error: <urlopen error [Errno 11004] getaddrinfo failed>. Retrying (attempt 3 of 10) ...
[download] Got server HTTP error: <urlopen error [Errno 11004] getaddrinfo failed>. Retrying (attempt 4 of 10) ...
[download] Got server HTTP error: <urlopen error [Errno 11004] getaddrinfo failed>. Retrying (attempt 5 of 10) ...
[download] Got server HTTP error: <urlopen error [Errno 11004] getaddrinfo failed>. Retrying (attempt 6 of 10) ...
[download] Got server HTTP error: <urlopen error [Errno 11004] getaddrinfo failed>. Retrying (attempt 7 of 10) ...
[download] Got server HTTP error: <urlopen error [Errno 11004] getaddrinfo failed>. Retrying (attempt 8 of 10) ...
[download] Got server HTTP error: <urlopen error [Errno 11004] getaddrinfo failed>. Retrying (attempt 9 of 10) ...
[download] Got server HTTP error: <urlopen error [Errno 11004] getaddrinfo failed>. Retrying (attempt 10 of 10) ...
[download] Got server HTTP error: <urlopen error [Errno 11004] getaddrinfo failed>
ERROR: giving up after 10 retries
  File "yt_dlp\__main__.py", line 17, in <module>
  File "yt_dlp\__init__.py", line 921, in main
  File "yt_dlp\__init__.py", line 913, in _real_main
  File "yt_dlp\YoutubeDL.py", line 3249, in download
  File "yt_dlp\YoutubeDL.py", line 3225, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1411, in extract_info
  File "yt_dlp\YoutubeDL.py", line 1420, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1504, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1561, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2630, in process_video_result
  File "yt_dlp\YoutubeDL.py", line 3129, in process_info
  File "yt_dlp\YoutubeDL.py", line 2829, in dl
  File "yt_dlp\downloader\common.py", line 444, in download
  File "yt_dlp\downloader\http.py", line 386, in real_download
  File "yt_dlp\YoutubeDL.py", line 962, in report_error
  File "yt_dlp\YoutubeDL.py", line 894, in trouble

**Comment by pukkandan** [comment]
Seems like a network issue. Confirm that you can access the video in browser from same IP

```
❯ yt-dlp -v https://tv.naver.com/v/27746776
[debug] Command-line config: ['--ignore-config', '-v', 'https://tv.naver.com/v/27746776']
[debug] Encodings: locale cp65001, fs utf-8, pref cp65001, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.06.29 [9d339c41e] (source)
[debug] Lazy loading extractors is disabled
[debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
[debug] Git HEAD: 385f7f389
[debug] Python 3.10.4 (CPython 64bit) - Windows-10-10.0.22000-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg N-106550-g072101bd52-20220410 (fdk,setts), ffprobe N-106624-g391ce570c8-20220415, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.14.1, brotli-1.0.9, certifi-2021.10.08, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.1
[debug] Proxy map: {}
[debug] [Naver] Extracting URL: https://tv.naver.com/v/27746776
[Naver] 27746776: Downloading JSON metadata
[Naver] 27746776: Downloading JSON metadata
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 27746776: Downloading 1 format(s): avc1_1080P
[debug] Invoking http downloader on "http://a01-g-cdn.vod.naver.net/navertv/c/read/v2/VOD_ALPHA/navertv_2022_07_04_308/551f73ff-fb76-11ec-ba5e-48df37269fd0.mp4?__gda__=1657018606_697971a488f5aa44be483f370018ccec"
[download] Resuming download at byte 16035264
[debug] File locking is not supported. Proceeding without locking
[download] Destination: 친구들 맞이하는 SON '동료들의 기대, 걱정이에요' [스포츠타임] [27746776].mp4
[download]  14.8% of 116.51MiB at    2.47MiB/s ETA 00:40
```

**Comment by lunamoth** [comment]
The problem was caused by blocking b01-kr-cdn.vod.naver.net in NextDNS. It wasn't a problem. Sorry to bother everyone.
