### ISSUE TITLE
Output filename using metadata title

### ISSUE THREAD

**Issue by porjo** [yt-dlp/yt-dlp#4275]
### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.06.29** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I am downloading MP3 files which have a randomly generated filename. I then re-encode using Opus. I would like for the final filename to use the metadata title value (from inside the original MP3) as the output filename. I have searched the doco and issues but can't see a way to do this in one step. Is it possible? I played with `--parse-metadata` but couldn't get it to work. Currently, I run `ffprobe` afterwards to fetch the title and rename the file.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
# yt-dlp -vU --audio-format opus https://rss.art19.com/episodes/89b56c1f-97a7-4a68-b9a0-ae344b28a755.mp3
[debug] Command-line config: ['-vU', '--audio-format', 'opus', 'https://rss.art19.com/episodes/89b56c1f-97a7-4a68-b9a0-ae344b28a755.mp3']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.06.29 [9d339c4] (zip)
[debug] Python 3.10.4 (CPython 64bit) - Linux-3.10.0-1160.66.1.el7.x86_64-x86_64-with 
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 5.0.1 (setts), ffprobe 5.0.1
[debug] Optional libraries: sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
[debug] Downloading _update_spec from https://github.com/yt-dlp/yt-dlp/releases/download/2022.06.29/_update_spec
Latest version: 2022.06.29, Current version: 2022.06.29
yt-dlp is up to date (2022.06.29)
[debug] [generic] Extracting URL: https://rss.art19.com/episodes/89b56c1f-97a7-4a68-b9a0-ae344b28a755.mp3
[generic] 89b56c1f-97a7-4a68-b9a0-ae344b28a755: Requesting header
[redirect] Following redirect to https://rss.art19.com/external/episodes/89b56c1f-97a7-4a68-b9a0-ae344b28a755.mp3
[debug] [generic] Extracting URL: https://rss.art19.com/external/episodes/89b56c1f-97a7-4a68-b9a0-ae344b28a755.mp3
[generic] 89b56c1f-97a7-4a68-b9a0-ae344b28a755: Requesting header
[debug] Identified a direct video link
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 89b56c1f-97a7-4a68-b9a0-ae344b28a755: Downloading 1 format(s): mpeg
[debug] Invoking http downloader on "https://rss.art19.com/external/episodes/89b56c1f-97a7-4a68-b9a0-ae344b28a755.mp3"
[download] 89b56c1f-97a7-4a68-b9a0-ae344b28a755 [89b56c1f-97a7-4a68-b9a0-ae344b28a755].mp3 has already been downloaded
[download] 100% of 64.30MiB
```

**Comment by pukkandan** [comment]
No, this is not possible. It could be implemented in https://github.com/yt-dlp/yt-dlp/issues/613
