### ISSUE TITLE
Question about "begins with" and "contains" syntax for formats

### ISSUE THREAD

**Issue by someziggyman** [yt-dlp/yt-dlp#4276]
### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.06.29** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

This one is bit random, but I wanted to learn and use some of the Filtering Formats syntax, but failing a bit or not using it properly. My interest is *= (contains) ^= (starts with)

My Test link:
https://www.arte.tv/fr/videos/103364-000-A/julian-assange-chronique-d-une-extradition-annoncee/ 

Listed formats with -F and we see: 

video format ID - **VA-STA-2254** with format_note - **Allemand [VA]**
audio format ID - **VA-STA-program_audio_0-VA** with format_note **[de] Allemand [VA]**

Now for the sake of the syntax experiment let's try two cases.
1) Both IDs **start with "VA-STA"** so I tried this command:
./yt-dlp -v -f "bestvideo[id^=VA-STA],bestaudio[id^=VA-STA]" "https://www.arte.tv/fr/videos/103364-000-A/julian-assange-chronique-d-une-extradition-annoncee/" 

2) or let's try best audio with format_note that contains - Allemand [VA]
./yt-dlp -v -f "bestaudio[format_note*=Allemand [VA]]" "https://www.arte.tv/fr/videos/103364-000-A/julian-assange-chronique-d-une-extradition-annoncee/" 

as a side note, tried these params as well:
./yt-dlp -f "best*[vcodec=none][id^=VA-STA]"

Still failing with the same result - ERROR: [ArteTV] 103364-000-A: Requested format is not available. Use --list-formats for a list of available formats

What am I doing wrong?  Log below, it's the same for all the cases above.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
./yt-dlp -vU -f "bestvideo[id^=VA-STA],bestaudio[id^=VA-STA]" "https://www.arte.tv/fr/videos/103364-000-A/julian-assange-chronique-d-une-extradition-annoncee/" 
[debug] Command-line config: ['-vU', '-f', 'bestvideo[id^=VA-STA],bestaudio[id^=VA-STA]', 'https://www.arte.tv/fr/videos/103364-000-A/julian-assange-chronique-d-une-extradition-annoncee/']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.06.29 [9d339c41e] (zip)
[debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
[debug] Python 3.9.13 (CPython 64bit) - macOS-12.4-arm64-arm-64bit 
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: avconv -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: avprobe -bsfs
[debug] exe versions: none
[debug] Optional libraries: sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.06.29, Current version: 2022.06.29
yt-dlp is up to date (2022.06.29)
[debug] [ArteTV] Extracting URL: https://www.arte.tv/fr/videos/103364-000-A/julian-assange-chronique-d-une-extradition-annoncee/
[ArteTV] 103364-000-A: Downloading JSON metadata
[ArteTV] 103364-000-A: Downloading m3u8 information
[ArteTV] 103364-000-A: Downloading m3u8 information
[ArteTV] 103364-000-A: Downloading m3u8 information
[ArteTV] 103364-000-A: Downloading m3u8 information
[ArteTV] 103364-000-A: Downloading m3u8 information
[ArteTV] 103364-000-A: Downloading m3u8 information
[ArteTV] 103364-000-A: Downloading m3u8 information
[ArteTV] 103364-000-A: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
ERROR: [ArteTV] 103364-000-A: Requested format is not available. Use --list-formats for a list of available formats
Traceback (most recent call last):
  File "./yt-dlp/yt_dlp/YoutubeDL.py", line 1418, in wrapper
    return func(self, *args, **kwargs)
  File "./yt-dlp/yt_dlp/YoutubeDL.py", line 1502, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "./yt-dlp/yt_dlp/YoutubeDL.py", line 1559, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "./yt-dlp/yt_dlp/YoutubeDL.py", line 2591, in process_video_result
    raise ExtractorError(
yt_dlp.utils.ExtractorError: [ArteTV] 103364-000-A: Requested format is not available. Use --list-formats for a list of available formats
```

**Comment by Lesmiscore** [comment]
The key for format ID is `format_id`. So it should be `-f "bestvideo[format_id^=VA-STA],bestaudio[format_id^=VA-STA]"`

**Comment by someziggyman** [comment]
Thank you so much! I know, I was just a newbie :-)

**Comment by someziggyman** [comment]
> The key for format ID is `format_id`. So it should be `-f "bestvideo[format_id^=VA-STA],bestaudio[format_id^=VA-STA]"`

Format ID worked fine, but what about format note? What is wrong with this one? 
./yt-dlp -v -f "bestaudio[format_note*=Allemand [VA]]" "https://www.arte.tv/fr/videos/103364-000-A/julian-assange-chronique-d-une-extradition-annoncee/"

**Comment by Lesmiscore** [comment]
I thunk `[VA]` part is language... You can only filter by `Allemand` part.

**Comment by pukkandan** [comment]
The `-F` output is designed to be easily human readable, not to show you the exact value of each field. Use `--print` for that. Eg: `-O %(formats)#j`
