### ISSUE TITLE
[Franceinter/FranceCulture]  Support playlists

### ISSUE THREAD

**Issue by someziggyman** [yt-dlp/yt-dlp#4282]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.06.29** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

anywhere

### Provide a description that is worded well enough to be understood

Test link1:
https://www.radiofrance.fr/franceinter/podcasts/concert-inter/festival-jazz-a-vienne-avec-michael-kiwanuka-black-pumas-du-mardi-05-juillet-2022-2188789
**Error: Unable to extract audio data**

Test link2: (maybe need a separate issue for this one?)
https://www.radiofrance.fr/franceinter/grille-programmes?date=04-07-2022
**ERROR: Unsupported URL**

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
=================================================================
Log for Test link 1:
=================================================================
./yt-dlp -vU -F "https://www.radiofrance.fr/franceinter/podcasts/concert-inter/festival-jazz-a-vienne-avec-michael-kiwanuka-black-pumas-du-mardi-05-juillet-2022-2188789"
[debug] Command-line config: ['-vU', '-F', 'https://www.radiofrance.fr/franceinter/podcasts/concert-inter/festival-jazz-a-vienne-avec-michael-kiwanuka-black-pumas-du-mardi-05-juillet-2022-2188789']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.06.29 [9d339c41e] (zip)
[debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
[debug] Python 3.9.13 (CPython 64bit) - macOS-12.4-arm64-arm-64bit 
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: avconv -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: avprobe -bsfs
[debug] exe versions: none
[debug] Optional libraries: sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.06.29, Current version: 2022.06.29
yt-dlp is up to date (2022.06.29)
[debug] [FranceCulture] Extracting URL: https://www.radiofrance.fr/franceinter/podcasts/concert-inter/festival-jazz-a-vienne-avec-michael-kiwanuka-black-pumas-du-mardi-05-juillet-2022-2188789
[FranceCulture] festival-jazz-a-vienne-avec-michael-kiwanuka-black-pumas-du-mardi-05-juillet-2022: Downloading webpage
ERROR: [FranceCulture] 2188789: Unable to extract audio data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "./yt-dlp/yt_dlp/extractor/common.py", line 640, in extract
    ie_result = self._real_extract(url)
  File "./yt-dlp/yt_dlp/extractor/radiofrance.py", line 87, in _real_extract
    video_data = self._search_json('', webpage, 'audio data', display_id, contains_pattern=r'\s*"@type"\s*:\s*"AudioObject"\s*.+')
  File "./yt-dlp/yt_dlp/extractor/common.py", line 1206, in _search_json
    json_string = self._search_regex(
  File "./yt-dlp/yt_dlp/extractor/common.py", line 1192, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)

=================================================================
Log for Test link 2:
=================================================================
./yt-dlp -vU -F "https://www.radiofrance.fr/franceinter/grille-programmes?date=04-07-2022"
[debug] Command-line config: ['-vU', '-F', 'https://www.radiofrance.fr/franceinter/grille-programmes?date=04-07-2022']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.06.29 [9d339c41e] (zip)
[debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
[debug] Python 3.9.13 (CPython 64bit) - macOS-12.4-arm64-arm-64bit 
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: avconv -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: avprobe -bsfs
[debug] exe versions: none
[debug] Optional libraries: sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.06.29, Current version: 2022.06.29
yt-dlp is up to date (2022.06.29)
[debug] [generic] Extracting URL: https://www.radiofrance.fr/franceinter/grille-programmes?date=04-07-2022
[generic] grille-programmes?date=04-07-2022: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] grille-programmes?date=04-07-2022: Downloading webpage
[generic] grille-programmes?date=04-07-2022: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://www.radiofrance.fr/franceinter/grille-programmes?date=04-07-2022
Traceback (most recent call last):
  File "./yt-dlp/yt_dlp/YoutubeDL.py", line 1418, in wrapper
    return func(self, *args, **kwargs)
  File "./yt-dlp/yt_dlp/YoutubeDL.py", line 1488, in __extract_info
    ie_result = ie.extract(url)
  File "./yt-dlp/yt_dlp/extractor/common.py", line 640, in extract
    ie_result = self._real_extract(url)
  File "./yt-dlp/yt_dlp/extractor/generic.py", line 4130, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.radiofrance.fr/franceinter/grille-programmes?date=04-07-2022
```

**Comment by HobbyistDev** [comment]
It seems related to https://github.com/yt-dlp/yt-dlp/pull/4065#issuecomment-1153959809 and https://github.com/yt-dlp/yt-dlp/pull/4065#issuecomment-1158040287

**Comment by nicolaasjan** [comment]
For some reason it works here (latest `master` build):

```bash
yt-dlp -vU https://www.radiofrance.fr/franceinter/podcasts/concert-inter/festival-jazz-a-vienne-avec-michael-kiwanuka-black-pumas-du-mardi-05-juillet-2022-2188789
[debug] Command-line config: ['-vU', 'https://www.radiofrance.fr/franceinter/podcasts/concert-inter/festival-jazz-a-vienne-avec-michael-kiwanuka-black-pumas-du-mardi-05-juillet-2022-2188789']
[debug] User config "/home/nico/.config/yt-dlp/config": ['-o', '/dev/shm/test-dlp/%(title)s.%(ext)s', '-f', 'bestvideo[height<=1080][ext=mp4][vcodec!*=av01]+bestaudio[ext=m4a]/best[ext=mp4]/best', '--no-mtime', '--convert-thumbnails', 'jpg', '--embed-thumbnail', '--ppa', 'ThumbnailsConvertor:-q:v 1', '--force-ipv4', '--sponsorblock-remove', 'all', '--console-title', '--downloader', 'aria2c', '--downloader-args', 'aria2c:--http-accept-gzip=true -x 10 -s 10 -j 10 -k 1M --log-level=info --file-allocation=none']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.07.03 [385f7f389] (zip)
[debug] Python 3.8.10 (CPython 64bit) - Linux-5.4.0-121-generic-x86_64-with-glibc2.29 (glibc 2.31)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg N-107246-g59a58d1a85-Nico-20220626 (fdk,setts), ffprobe N-107246-g59a58d1a85-Nico-20220626, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.12.0, brotli-1.0.9, certifi-2019.11.28, mutagen-1.45.1, secretstorage-2.3.1, sqlite3-2.6.0, websockets-10.1
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.06.29, Current version: 2022.07.03
yt-dlp is up to date (2022.07.03)
[debug] [FranceCulture] Extracting URL: https://www.radiofrance.fr/franceinter/podcasts/concert-inter/festival-jazz-a-vienne-avec-michael-kiwanuka-black-pumas-du-mardi-05-juillet-2022-2188789
[FranceCulture] festival-jazz-a-vienne-avec-michael-kiwanuka-black-pumas-du-mardi-05-juillet-2022: Downloading webpage
[SponsorBlock] SponsorBlock is not supported for FranceCulture
[info] 2188789: Downloading 1 format(s): 0
[info] Downloading video thumbnail 0 ...
[info] Writing video thumbnail 0 to: /dev/shm/test-dlp/Festival Jazz à Vienne avec Michael Kiwanuka et Black Pumas.jpg
[ThumbnailsConvertor] Not converting thumbnail "/dev/shm/test-dlp/Festival Jazz à Vienne avec Michael Kiwanuka et Black Pumas.jpg"; already is in target format jpg
[debug] Invoking aria2c downloader on "https://media.radiofrance-podcast.net/podcast09/15361-05.07.2022-ITEMA_23080098-2022F23111S0186-22.mp3"
[download] Destination: /dev/shm/test-dlp/Festival Jazz à Vienne avec Michael Kiwanuka et Black Pumas.mp3
[debug] aria2c command line: aria2c -c --console-log-level=warn --summary-interval=0 --download-result=hide --http-accept-gzip=true --file-allocation=none -x16 -j16 -s16 --min-split-size 1M --header 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.54 Safari/537.36' --header 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8' --header 'Accept-Language: en-us,en;q=0.5' --header 'Sec-Fetch-Mode: navigate' --interface 0.0.0.0 --check-certificate=true --remote-time=false --show-console-readout=true --http-accept-gzip=true -x 10 -s 10 -j 10 -k 1M --log-level=info --file-allocation=none --dir /dev/shm/test-dlp/ --out './Festival Jazz à Vienne avec Michael Kiwanuka et Black Pumas.mp3.part' --auto-file-renaming=false -- https://media.radiofrance-podcast.net/podcast09/15361-05.07.2022-ITEMA_23080098-2022F23111S0186-22.mp3
[aria2c] Downloaded 168815484 bytes:8.9MiB]                                    
[download] 100% of 160.99MiB in 00:19
[ModifyChapters] SponsorBlock information is unavailable
[EmbedThumbnail] ffmpeg: Adding thumbnail to "/dev/shm/test-dlp/Festival Jazz à Vienne avec Michael Kiwanuka et Black Pumas.mp3"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:/dev/shm/test-dlp/Festival Jazz à Vienne avec Michael Kiwanuka et Black Pumas.mp3' -i 'file:/dev/shm/test-dlp/Festival Jazz à Vienne avec Michael Kiwanuka et Black Pumas.jpg' -c copy -map 0:0 -map 1:0 -write_id3v1 1 -id3v2_version 3 -metadata:s:v 'title="Album cover"' -metadata:s:v 'comment="Cover (front)"' -movflags +faststart 'file:/dev/shm/test-dlp/Festival Jazz à Vienne avec Michael Kiwanuka et Black Pumas.temp.mp3'
```

**Comment by elyse0** [comment]
The second [link](https://www.radiofrance.fr/franceinter/grille-programmes?date=04-07-2022) is more like a "playlist", and it's not currently supported

So I would call it a feature request instead of a bug

**Comment by someziggyman** [comment]
> For some reason the first URL works here (latest `master` build):
> 
> ```python
> yt-dlp -vU https://www.radiofrance.fr/franceinter/podcasts/concert-inter/festival-jazz-a-vienne-avec-michael-kiwanuka-black-pumas-du-mardi-05-juillet-2022-2188789
> [debug] Command-line config: ['-vU', 'https://www.radiofrance.fr/franceinter/podcasts/concert-inter/festival-jazz-a-vienne-avec-michael-kiwanuka-black-pumas-du-mardi-05-juillet-2022-2188789']
> [debug] User config "/home/nico/.config/yt-dlp/config": ['-o', '/dev/shm/test-dlp/%(title)s.%(ext)s', '-f', 'bestvideo[height<=1080][ext=mp4][vcodec!*=av01]+bestaudio[ext=m4a]/best[ext=mp4]/best', '--no-mtime', '--convert-thumbnails', 'jpg', '--embed-thumbnail', '--ppa', 'ThumbnailsConvertor:-q:v 1', '--force-ipv4', '--sponsorblock-remove', 'all', '--console-title', '--downloader', 'aria2c', '--downloader-args', 'aria2c:--http-accept-gzip=true -x 10 -s 10 -j 10 -k 1M --log-level=info --file-allocation=none']
> [debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
> [debug] yt-dlp version 2022.07.03 [385f7f389] (zip)
> [debug] Python 3.8.10 (CPython 64bit) - Linux-5.4.0-121-generic-x86_64-with-glibc2.29 (glibc 2.31)
> [debug] Checking exe version: ffmpeg -bsfs
> [debug] Checking exe version: ffprobe -bsfs
> [debug] exe versions: ffmpeg N-107246-g59a58d1a85-Nico-20220626 (fdk,setts), ffprobe N-107246-g59a58d1a85-Nico-20220626, phantomjs 2.1.1
> [debug] Optional libraries: Cryptodome-3.12.0, brotli-1.0.9, certifi-2019.11.28, mutagen-1.45.1, secretstorage-2.3.1, sqlite3-2.6.0, websockets-10.1
> [debug] Proxy map: {}
> [debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
> Latest version: 2022.06.29, Current version: 2022.07.03
> yt-dlp is up to date (2022.07.03)
> [debug] [FranceCulture] Extracting URL: https://www.radiofrance.fr/franceinter/podcasts/concert-inter/festival-jazz-a-vienne-avec-michael-kiwanuka-black-pumas-du-mardi-05-juillet-2022-2188789
> [FranceCulture] festival-jazz-a-vienne-avec-michael-kiwanuka-black-pumas-du-mardi-05-juillet-2022: Downloading webpage
> [SponsorBlock] SponsorBlock is not supported for FranceCulture
> [info] 2188789: Downloading 1 format(s): 0
> [info] Downloading video thumbnail 0 ...
> [info] Writing video thumbnail 0 to: /dev/shm/test-dlp/Festival Jazz à Vienne avec Michael Kiwanuka et Black Pumas.jpg
> [ThumbnailsConvertor] Not converting thumbnail "/dev/shm/test-dlp/Festival Jazz à Vienne avec Michael Kiwanuka et Black Pumas.jpg"; already is in target format jpg
> [debug] Invoking aria2c downloader on "https://media.radiofrance-podcast.net/podcast09/15361-05.07.2022-ITEMA_23080098-2022F23111S0186-22.mp3"
> [download] Destination: /dev/shm/test-dlp/Festival Jazz à Vienne avec Michael Kiwanuka et Black Pumas.mp3
> [debug] aria2c command line: aria2c -c --console-log-level=warn --summary-interval=0 --download-result=hide --http-accept-gzip=true --file-allocation=none -x16 -j16 -s16 --min-split-size 1M --header 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.54 Safari/537.36' --header 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8' --header 'Accept-Language: en-us,en;q=0.5' --header 'Sec-Fetch-Mode: navigate' --interface 0.0.0.0 --check-certificate=true --remote-time=false --show-console-readout=true --http-accept-gzip=true -x 10 -s 10 -j 10 -k 1M --log-level=info --file-allocation=none --dir /dev/shm/test-dlp/ --out './Festival Jazz à Vienne avec Michael Kiwanuka et Black Pumas.mp3.part' --auto-file-renaming=false -- https://media.radiofrance-podcast.net/podcast09/15361-05.07.2022-ITEMA_23080098-2022F23111S0186-22.mp3
> [aria2c] Downloaded 168815484 bytes:8.9MiB]                                    
> [download] 100% of 160.99MiB in 00:19
> [ModifyChapters] SponsorBlock information is unavailable
> [EmbedThumbnail] ffmpeg: Adding thumbnail to "/dev/shm/test-dlp/Festival Jazz à Vienne avec Michael Kiwanuka et Black Pumas.mp3"
> [debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:/dev/shm/test-dlp/Festival Jazz à Vienne avec Michael Kiwanuka et Black Pumas.mp3' -i 'file:/dev/shm/test-dlp/Festival Jazz à Vienne avec Michael Kiwanuka et Black Pumas.jpg' -c copy -map 0:0 -map 1:0 -write_id3v1 1 -id3v2_version 3 -metadata:s:v 'title="Album cover"' -metadata:s:v 'comment="Cover (front)"' -movflags +faststart 'file:/dev/shm/test-dlp/Festival Jazz à Vienne avec Michael Kiwanuka et Black Pumas.temp.mp3'
> ```
> 
> The second one gives the same error.

Indeed, the first link works for me now as well. Maybe some temporary glitch or my test build got messed up. My apologies for the confusion.

as for the second one - it's "playlist-like" for sure. Should I be creating a new issue for that one and just close this one?

**Comment by elyse0** [comment]
No need, just update the title and description on this one

**Comment by nicolaasjan** [comment]
> as for the second one - it's "playlist-like" for sure.

Indeed, it downloads (very slowly) with this:

yt-dlp --downloader ffmpeg --hls-use-mpegts https://stream.radiofrance.fr/franceinter/franceinter_hifi.m3u8?id=radiofrance

**Comment by dirkf** [comment]
Link 2 is just a programme guide with 4 items, no?

Expect a PR at yt-dl for revamped radiofrance.py handling (unpaginated) lists, RF podcasts, francebleu.fr, hyperradio.fr, and deleting/superseding france(culture|inter).py.

The RF audio pages generally have the audio media in a ld+json block, if only the json_ld processing could find it, as well as most of the other desired metadata.

**Comment by elyse0** [comment]
> Link 2 is just a programme guide with 4 items, no?

Yep, but I see +20 items 🤔 

![image](https://user-images.githubusercontent.com/26639800/177858406-478fd4fc-0b0b-4878-8dd2-c3422f089e29.png)

**Comment by dirkf** [comment]
4's wrong:
```shellsession
python -m youtube_dl -j --flat-playlist 'https://www.radiofrance.fr/franceinter/grille-programmes?date=04-07-2022' | wc -l
18
$
```

**Comment by neitsab** [comment]
Commenting here instead of opening a new issue as asked by the issue template:

Trying to download the playlist at `https://www.radiofrance.fr/franceculture/podcasts/serie/projet-orloff` gives an "Unsupported URL" error.

Full debug output:

```
[debug] Command-line config: ['-vU', 'https://www.radiofrance.fr/franceculture/podcasts/serie/projet-orloff']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.10.01.232843 from yt-dlp/yt-dlp-nightly-builds (linux_exe)
[debug] Python 3.11.10 (CPython x86_64 64bit) - Linux-6.11.1-arch1-1-x86_64-with (OpenSSL 3.1.7 3 Sep 2024)
[debug] exe versions: ffmpeg 7.0.2 (setts), ffprobe 7.0.2, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.08.30, curl_cffi-0.7.1, mutagen-1.47.0, requests-2.32.3, secretstorage-3.3.3, sqlite3-3.44.2, urllib3-2.2.3, websockets-13.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1838 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Latest version: nightly@2024.10.01.232843 from yt-dlp/yt-dlp-nightly-builds
yt-dlp is up to date (nightly@2024.10.01.232843 from yt-dlp/yt-dlp-nightly-builds)
[generic] Extracting URL: https://www.radiofrance.fr/franceculture/podcasts/serie/projet-orloff
[generic] projet-orloff: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] projet-orloff: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://www.radiofrance.fr/franceculture/podcasts/serie/projet-orloff
Traceback (most recent call last):
  File "yt_dlp/YoutubeDL.py", line 1626, in wrapper
  File "yt_dlp/YoutubeDL.py", line 1761, in __extract_info
  File "yt_dlp/extractor/common.py", line 741, in extract
  File "yt_dlp/extractor/generic.py", line 2526, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.radiofrance.fr/franceculture/podcasts/serie/projet-orloff
```

Thanks for your help
