### ISSUE TITLE
Downloading the wrong video

### ISSUE THREAD

**Issue by vksputnik** [yt-dlp/yt-dlp#4287]
### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.06.29** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

When trying to download this video https://24tv.ua/news/showPlayer.do?objectId=2074790&videoUrl=2022/07/2074790&w=640&h=360, the extractor downloads another, apparently mistakenly following the address https://streamvideoL.luxnet.ua /vodorigin/_definst_/smil:tv24/2022/07/2074461_FHD_20220706000157.smil/playlist.m3u8. What option should I use to exclude "m3u8" files and only download "mp4" files or somehow solve the problem?

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
Generic extractor is unable to handle the custom player used by the site. Probably, new extractor needs to be added

**Comment by dirkf** [comment]
The page has alternative links:
* the m3u8 link, which resolves in yt-dlp to `mp4 640x360    │ 898k`, with this URL https://streamvideoL.luxnet.ua/vodorigin/_definst_/smil:tv24/2022/07/2074790_FHD_20220706144051.smil/chunklist_b898000_slukr.m3u8,
* a separate mp4 link https://videocdnL.luxnet.ua/tv24/resources/videos/2022/07/2074790_main.mp4, apparently the same content and roughly the same resolution.

Where is the different video?

**Comment by vksputnik** [comment]
> На странице есть альтернативные ссылки:
> 
> * ссылка m3u8, которая разрешается в yt-dlp в `mp4 640x360    │ 898k`, с этим URL https://streamvideoL.luxnet.ua/vodorigin/_definst_/smil:tv24/2022/07/2074790_FHD_20220706144051.smil/chunklist_b898000_slukr.m3u8 ,
> * отдельная ссылка на mp4 https://videocdnL.luxnet.ua/tv24/resources/videos/2022/07/2074790_main.mp4 , видимо тот же контент и примерно такое же разрешение.
> 
> Где другое видео?

There is already one video in the source code, but earlier this one was downloaded from another m3u8 file https://24tv.ua/news/showPlayer.do?objectId=2074461&videoUrl=2022/07/2074461&w=640&h=360 instead of the required one.

**Comment by dirkf** [comment]
That is/так
> The page https://24tv.ua/news/showPlayer.do?objectId=2074790&videoUrl=2022/07/2074790&w=640&h=360 has alternative links:
> На странице https://24tv.ua/news/showPlayer.do?objectId=2074790&videoUrl=2022/07/2074790&w=640&h=360 есть альтернативные ссылки:

https://24tv.ua/news/showPlayer.do?objectId=2074790&videoUrl=2022/07/2074790&w=640&h=360 -> 3 links/ссылки 
* https://streamvideol.luxnet.ua/vodorigin/_definst_/smil:tv24/2022/07/2074790_FHD_20220706144051.smil/playlist.m3u8 -> https://streamvideol.luxnet.ua/vodorigin/_definst_/smil:tv24/2022/07/2074790_FHD_20220706144051.smil/chunklist_b898000_slukr.m3u8

* https://videocdnl.luxnet.ua/tv24/resources/videos/2022/07/2074790_main.mp4

* https://videocdnl.luxnet.ua/tv24/resources/videos_download/2022/07/2074790_mobile.mp4, but this gives/но дает 404.

Did the site fix the page/сайт исправил страницу?
