### ISSUE TITLE
[Feature Request] Crop to square thumbnail when embedding in MP3s

### ISSUE THREAD

**Issue by nogarcia** [yt-dlp/yt-dlp#429]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running yt-dlp version **2021.06.09**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description

Music thumbnails from YouTube are always in 16:9 format, but the album art pictured is always 1:1. As a result, embedded thumbnails are letterboxed and get distorted in music players. Youtube-DL has an identitical issue at ytdl-org/youtube-dl#20011, but it and its respective pull request has since been ignored; I'm hoping this fork will be more receptive.

A pull request already exists for Youtube-DL to do this (ytdl-org/youtube-dl#20022,) and it turns out that it's a pretty simple adjustment to [the `embed_thumbnail` postprocessor](https://github.com/yt-dlp/yt-dlp/blob/4c7853de1495619e0ace5ba24503600d9e4f49a1/yt_dlp/postprocessor/embedthumbnail.py#L102-L105) to filter the thumbnail.

**Comment by pukkandan** [comment]
You can already do this using `--ppa`. 

Just put this in your config file:

```py
--ppa '''EmbedThumbnail+ffmpeg_o:-c:v mjpeg -vf crop="'if(gt(ih,iw),iw,ih)':'if(gt(iw,ih),ih,iw)'"'''
```

Eg:
```
$ yt-dlp -x --audio-format mp3 "3_Nn1Ihr1jI" --embed-thumbnail -v --convert-thumbnail jpg --ppa "EmbedThumbnail+ffmpeg_o:-c:v mjpeg -vf crop=\"'if(gt(ih,iw),iw,ih)':'if(gt(iw,ih),ih,iw)'\"" --exec ffprobe
[debug] Command-line config: ['-x', '--audio-format', 'mp3', '3_Nn1Ihr1jI', '--embed-thumbnail', '-v', '--convert-thumbnail', 'jpg', '--ppa', 'EmbedThumbnail+ffmpeg_o:-c:v mjpeg -vf crop="\'if(gt(ih,iw),iw,ih)\':\'if(gt(iw,ih),ih,iw)\'"', '--exec', 'ffprobe']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] yt-dlp version 2021.06.09 (source)
[debug] Plugin Extractors: ['SamplePlugin']
[debug] Git HEAD: 4c7853de14
[debug] Python version 3.9.5 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] exe versions: ffmpeg 2021-04-11-git-309e3cc15c-full_build-www.gyan.dev, ffprobe 2021-04-11-git-309e3cc15c-full_build-www.gyan.dev, phantomjs 2.1.1
[debug] Proxy map: {}
[debug] [youtube] Extracting URL: 3_Nn1Ihr1jI
[youtube] 3_Nn1Ihr1jI: Downloading webpage
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[info] 3_Nn1Ihr1jI: Downloading 1 format(s): 251
[youtube] 3_Nn1Ihr1jI: Downloading thumbnail  ...
[youtube] 3_Nn1Ihr1jI: Writing thumbnail to: Don't Worry About Me - Episode 29 [3_Nn1Ihr1jI].webp
[ThumbnailsConvertor] Converting thumbnail "Don't Worry About Me - Episode 29 [3_Nn1Ihr1jI].webp" to jpg
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -f image2 -pattern_type none -i "file:Don't Worry About Me - Episode 29 [3_Nn1Ihr1jI].webp" "-bsf:v" mjpeg2jpeg "file:Don't Worry About Me - Episode 29 [3_Nn1Ihr1jI].jpg"
Deleting original file Don't Worry About Me - Episode 29 [3_Nn1Ihr1jI].webp (pass -k to keep)
[download] Don't Worry About Me - Episode 29 [3_Nn1Ihr1jI].mp3 has already been downloaded
[debug] ffmpeg command line: ffprobe -show_streams "file:Don't Worry About Me - Episode 29 [3_Nn1Ihr1jI].mp3"
[ExtractAudio] Post-process file Don't Worry About Me - Episode 29 [3_Nn1Ihr1jI].mp3 exists, skipping
[EmbedThumbnail] ffmpeg: Adding thumbnail to "Don't Worry About Me - Episode 29 [3_Nn1Ihr1jI].mp3"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:Don't Worry About Me - Episode 29 [3_Nn1Ihr1jI].mp3" -i "file:Don't Worry About Me - Episode 29 [3_Nn1Ihr1jI].jpg" -c copy -map "0:0" -map "1:0" -id3v2_version 3 "-metadata:s:v" "title=\"Album cover\"" "-metadata:s:v" "comment=\"Cover (front)\"" "-c:v" mjpeg -vf "crop='if(gt(ih,iw),iw,ih)':'if(gt(iw,ih),ih,iw)'" "file:Don't Worry About Me - Episode 29 [3_Nn1Ihr1jI].temp.mp3"
Deleting original file Don't Worry About Me - Episode 29 [3_Nn1Ihr1jI].jpg (pass -k to keep)
[Exec] Executing command: ffprobe "D:\AKJ\Progs\yt-dlc\Don't Worry About Me - Episode 29 [3_Nn1Ihr1jI].mp3"
ffprobe version 2021-04-11-git-309e3cc15c-full_build-www.gyan.dev Copyright (c) 2007-2021 the FFmpeg developers
  built with gcc 10.2.0 (Rev6, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-lzma --enable-libsnappy --enable-zlib --enable-librist --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libdav1d --enable-libzvbi --enable-librav1e --enable-libsvtav1 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-libglslang --enable-vulkan --enable-opencl --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint
  libavutil      56. 72.100 / 56. 72.100
  libavcodec     58.136.101 / 58.136.101
  libavformat    58. 78.100 / 58. 78.100
  libavdevice    58. 14.100 / 58. 14.100
  libavfilter     7.111.100 /  7.111.100
  libswscale      5. 10.100 /  5. 10.100
  libswresample   3. 10.100 /  3. 10.100
  libpostproc    55. 10.100 / 55. 10.100
Input #0, mp3, from 'D:\AKJ\Progs\yt-dlc\Don't Worry About Me - Episode 29 [3_Nn1Ihr1jI].mp3':
  Metadata:
    encoder         : Lavf58.78.100
  Duration: 00:40:07.63, start: 0.023021, bitrate: 69 kb/s
  Stream #0:0: Audio: mp3, 48000 Hz, stereo, fltp, 69 kb/s
    Metadata:
      encoder         : Lavc58.13
  Stream #0:1: Video: mjpeg (Baseline), yuvj420p(pc, bt470bg/unknown/unknown), 720x720, 90k tbr, 90k tbn, 90k tbc (attached pic)
    Metadata:
      title           : "Album cover"
      comment         : Other
```

**Comment by radiohazard-dev** [comment]
This looks super useful; thanks! I appear to be getting some conversion errors with the way I'm using it, but I think it's simply some shell oddities with nested quotes; I'll close this since it looks like it works in a normal context.

**Comment by pukkandan** [comment]
The tricky part is escaping the quotes. I already gave example for config file and Windows. On UNIX, it becomes:
```
--ppa 'EmbedThumbnail+ffmpeg_o:-c:v mjpeg -vf crop="'"'"'if(gt(ih,iw),iw,ih)'"':'"'if(gt(iw,ih),ih,iw)'"'"'"'
```

**Comment by radiohazard-dev** [comment]
Yeah, the quotes are totally driving me nuts. Both Powershell, Python, and ffmpeg all seem to take issue with the variations I'm trying on Windows. Using the config option in the first block you gave, ffmpeg gives `[AVFilterGraph @ 000001a0f312b3c0] No such filter: 'iw)'`. When I copy the options from the `Command-line config:` line, Python SyntaxErrors when it encounters the parentheses, which doesn't seem to be able to be fixed by adding \` or \\.

**Comment by pukkandan** [comment]
ah, sorry. I was thinking of python strings and not posix when writing that. What you need to put in config is same as the UNIX one I gave above.

> When I copy the options from the Command-line config: line, Python SyntaxErrors when it encounters the parentheses, which doesn't seem to be able to be fixed by adding ` or \.

Don't do that. That string has already been interpreted by cmd and then escaped by python. Use exactly what I am passing in the cmd

```
--ppa "EmbedThumbnail+ffmpeg_o:-c:v mjpeg -vf crop=\"'if(gt(ih,iw),iw,ih)':'if(gt(iw,ih),ih,iw)'\""
```

**Comment by radiohazard-dev** [comment]
That works perfectly. Thanks so much.

**Comment by A4r0nLF** [comment]
For me it worked on Linux but only with png as thumbnail format:
--ppa "EmbedThumbnail+ffmpeg_o:-c:v png -vf crop=\"'if(gt(ih,iw),iw,ih)':'if(gt(iw,ih),ih,iw)'\""

**Comment by matant94** [comment]
Sorry I copy pasted the setting you get but still have a 1270x720 thumb 
here are my configs actually 'cause no one hve worked

```
#Video Format Options
--check-formats
-f bestaudio -S "proto:https,acodec,+asr:44100" --audio-quality 0

#Subtitle Options

#Authentication
-n
--netrc-location "D:\Launcher\YTMusicDownloader\yt-dlp"

#Post-Processing Options
--ffmpeg-location "D:\Launcher\YTMusicDownloader\yt-dlp"
-x
--audio-format wav
--add-metadata

#SponsorBlock Options
--sponsorblock-mark all
--sponsorblock-remove sponsor,selfpromo

#Extractor Options
--extractor-args "youtube:player-client=android_music;include_live_dash"
--extractor-retries 15
--allow-dynamic-mpd
```

**Comment by Tom60chat** [comment]
After a few tries, I was able to create a script to automatically download the music with its metadata and crop thumbnail.

Tested with music.youtube.com url and 2022.07.18 version of yt-dlp.

```batch
@echo off

echo Downloading: %1=%2
echo(

REM Download the music
yt-dlp.exe %1=%2^
 --extract-audio^
 --audio-format mp3^
 --audio-quality 0^
 --add-metadata^
 --ffmpeg-location ..\FFMpeg\bin^
 --embed-thumbnail^
 --ppa "EmbedThumbnail+ffmpeg_o:-c:v mjpeg -vf crop=\"'if(gt(ih,iw),iw,ih)':'if(gt(iw,ih),ih,iw)'\""

echo(
echo Done!
REM 4s pause
ping 127.0.0.1 > nul
```

**Comment by MagmaSlimeMC** [comment]
@Tom60chat Thank You!
I was frustrated by this for so long but when I pasted the arg you have in your script into my config file, all my thumbnails are nice squares now!

--ppa "EmbedThumbnail+ffmpeg_o:-c:v mjpeg -vf crop=\"'if(gt(ih,iw),iw,ih)':'if(gt(iw,ih),ih,iw)'\""

**Comment by Legnatbird** [comment]
Someone know how to do that on Windows?

**Comment by Mattwmaster58** [comment]
dropping in here to hopefully help some googlers, as of the current version, it seems you need to set the ppa for ThumbnailConvertor, not EmbedThumbnail, here's a full example I use:

```bash
yt-dlp "https://music.youtube.com/watch?v=Oncu0bgdcXU" --ppa "ThumbnailsConvertor+FFmpeg_o:-c:v mjpeg -vf crop=\"'if(gt(ih,iw),iw,ih)':'if(gt(iw,ih),ih,iw)'\"" --extract-audio --embed-thumbnail --audio-format opus
```

**Comment by juancarlangas** [comment]
For me works for **png** with:
```bash
--embed-thumbnail --convert-thumb png --ppa "ThumbnailsConvertor+ffmpeg_o:-c:v png -vf crop=\"'if(gt(ih,iw),iw,ih)':'if(gt(iw,ih),ih,iw)'\""
```
Maybe works also with **jpeg** with:
```bash
--embed-thumbnail --convert-thumb jpg --ppa "ThumbnailsConvertor+ffmpeg_o:-c:v mjpeg -vf crop=\"'if(gt(ih,iw),iw,ih)':'if(gt(iw,ih),ih,iw)'\""
```
...I dont know

**Comment by fillwithjoy1** [comment]
> dropping in here to hopefully help some googlers, as of at most 2023.03.04, it seems you need to set the ppa for ThumbnailConvertor, not EmbedThumbnail, here's a full example I use:
> 
> ```shell
> yt-dlp "https://music.youtube.com/watch?v=Oncu0bgdcXU" --ppa "ThumbnailsConvertor+FFmpeg_o:-c:v mjpeg -vf crop=\"'if(gt(ih,iw),iw,ih)':'if(gt(iw,ih),ih,iw)'\"" --extract-audio --embed-thumbnail --audio-format opus
> ```

--ppa formating: no escaped character/no closing quotation on all of these different solutions I tried

**Comment by pukkandan** [comment]
Powershell has different quoting rules.

**Comment by garylkz** [comment]
For me, `--ppa "ThumbnailsConvertor+ffmpeg_o:-c:v png -vf crop='ih'" --embed-thumbnail` worked good enough for me plus it doesn't require escaping character. 

Bonus: But, if you insist, instead of `\` you can actually escape quote on PowerShell with ``` ` ```. Using examples from above: `--embed-thumbnail --convert-thumb png --ppa "ThumbnailsConvertor+ffmpeg_o:-c:v png -vf crop=`"'if(gt(ih,iw),iw,ih)':'if(gt(iw,ih),ih,iw)'`""`

(That said, I still get error from the commands above AND apparently the error literally has NO solution online, if anyone know anything about ffmpeg's `ERROR: Postprocessing: Filter not found` I'd appreciate an explanation for it.)

**Comment by Mattwmaster58** [comment]
Is your version of yt-dlp outdated?

**Comment by garylkz** [comment]
pretty sure ive updated it yesterday

**Comment by Andriwll** [comment]
> For me, `--ppa "ThumbnailsConvertor+ffmpeg_o:-c:v png -vf crop='ih'" --embed-thumbnail` worked good enough for me plus it doesn't require escaping character.
> 
> Bonus: But, if you insist, instead of `\` you can actually escape quote on PowerShell with `` ` ``.
> 
> (That said, I still get error from the commands above AND apparently the error literally has NO solution online, if anyone know anything about ffmpeg's `ERROR: Postprocessing: Filter not found` I'd appreciate an explanation for it.)
> 
> PS: Author can you please integrate this feature request into `yt-dlp`? (Or at least provide example on README) tq.

Thank you so much, was hard to find this

**Comment by Rikiub** [comment]
Anyone know how do this with the [yt-dlp library](https://github.com/yt-dlp/yt-dlp?tab=readme-ov-file#embedding-yt-dlp)?

**Comment by bashonly** [comment]
> Anyone know how do this with the [yt-dlp library](https://github.com/yt-dlp/yt-dlp?tab=readme-ov-file#embedding-yt-dlp)?

use https://github.com/yt-dlp/yt-dlp/blob/master/devscripts/cli_to_api.py

**Comment by Rikiub** [comment]
> > Anyone know how do this with the [yt-dlp library](https://github.com/yt-dlp/yt-dlp?tab=readme-ov-file#embedding-yt-dlp)?
> 
> use https://github.com/yt-dlp/yt-dlp/blob/master/devscripts/cli_to_api.py

Oh yeah, thanks so much!

**Comment by MaxenceVacheron** [comment]
Could you post here how to do it please :) ?
I didn't manage to use the cli_to_api script... 😢

**Comment by Rikiub** [comment]
> @Rikiub Could you post here how to do it please :) ? I didn't manage to use the cli_to_api script... 😢

Just download the script and execute as main:

`python -m cli-to-api`

And then add your **options**:

`python -m cli-to-api -x --flat-playlist --skip-downloads`

You will get a dict with the options.

**Comment by Quinntyx** [comment]
There's an error i'm getting: 
```
ERROR: Preprocessing: Error opening output files: Filter not found
...
ERROR: Postprocessing: Error opening output files: Filter not found
```

Here's the command I'm using: `yt-dlp -x --audio-format flac --audio-quality 0 --embed-metadata --embed-thumbnail --convert-thumbnail jpg --ppa "ThumbnailsConvertor+FFmpeg_o:-c:v mjpeg -vf crop=\"'if(gt(ih,iw),iw,ih)':'if(gt(iw,ih),ih,iw)'\""`

**Comment by Quinntyx** [comment]
update: it works fine if I call it directly but if I make it a function in `~/.zshrc` it doesn't work

might just be me being stupid you can probably ignore this

**Comment by zeromiind** [comment]
> ah, sorry. I was thinking of python strings and not posix when writing that. What you need to put in config is same as the UNIX one I gave above.
> 
> > When I copy the options from the Command-line config: line, Python SyntaxErrors when it encounters the parentheses, which doesn't seem to be able to be fixed by adding ` or .
> 
> Don't do that. That string has already been interpreted by cmd and then escaped by python. Use exactly what I am passing in the cmd
> 
> ```
> --ppa "EmbedThumbnail+ffmpeg_o:-c:v mjpeg -vf crop=\"'if(gt(ih,iw),iw,ih)':'if(gt(iw,ih),ih,iw)'\""
> ```

@pukkandan Hello, how are you? I'm new to yt-dlp, so I just copied and inserted this:
`yt-dlp -x --audio-format m4a "I3oUsW9bXvQ" --embed-thumbnail -v --convert-thumbnail j
pg --ppa "EmbedThumbnail+ffmpeg_o:-c:v mjpeg -vf crop="'if(gt(ih,iw),iw,ih)':'if(gt(iw,ih),ih,iw)'\""`
And as a result I got the audio file but without the cropped cover art and no metadata, not even the artist name. So I wanted to see if you could help me maybe, it would be of great help.

**Comment by AzureArmageddon** [comment]
Would love if this got an option `--square-thumb` to tidy up the messy command.

**Comment by bashonly** [comment]
@AzureArmageddon you can do it yourself by adding this line to your [configuration file](https://github.com/yt-dlp/yt-dlp#configuration):
```
--alias square-thumb '--embed-metadata --embed-thumbnail --convert-thumbnail jpg --ppa "ThumbnailsConvertor+FFmpeg_o:-c:v mjpeg -vf crop=\"'"'"'if(gt(ih,iw),iw,ih)'"'"':'"'"'if(gt(iw,ih),ih,iw)'"'"'\""'
```

**Comment by HironoKenta** [comment]
Looks like to me thumbnail convertor is skipped when the thumbnail is yet in output format
ie:

> [ThumbnailsConvertor] Not converting thumbnail "thumb_filename.jpg"; already is in target format jpg

there is a way to force it?

**Comment by bashonly** [comment]
you could change `jpg` to `png` , e.g.
```
--alias square-thumb '--embed-thumbnail --convert-thumbnail png --ppa "ThumbnailsConvertor+FFmpeg_o:-c:v png -vf crop=\"'"'"'if(gt(ih,iw),iw,ih)'"'"':'"'"'if(gt(iw,ih),ih,iw)'"'"'\""'
```

**Comment by HironoKenta** [comment]
> you could change `jpg` to `png` , e.g.
> 
> ```
> --alias square-thumb '--embed-thumbnail --convert-thumbnail png --ppa "ThumbnailsConvertor+FFmpeg_o:-c:v png -vf crop=\"'"'"'if(gt(ih,iw),iw,ih)'"'"':'"'"'if(gt(iw,ih),ih,iw)'"'"'\""'
> ```

But this way I'll get png thumbnails. 😟

**Comment by kaybet35** [comment]
> Looks like to me thumbnail convertor is skipped when the downloaded thumbnail is in output format ie:
> 
> > [ThumbnailsConvertor] Not converting thumbnail "thumb_filename.jpg"; already is in target format jpg
> 
> there is a way to force it?

Try using mjpeg.

**Comment by agreselin** [comment]
Is there a way to make it work without first converting the thumbnail to jpeg?

**Comment by bashonly** [comment]
You can convert to png, which should minimize quality loss. A conversion needs to happen though, or else there's no postprocessor invoked that can accept ffmpeg args

**Comment by agreselin** [comment]
Thank @bashonly. I wouldn't call this feature request closed since YT Music has square thumbnails and we need convoluted ways to get a converted version, but still..

Adding ` -qmin 1 -qscale:v 1` to `mjpeg`'s arguments improves the quality a lot:
~~~
--alias embed-square-thumbnail '--embed-thumbnail --convert-thumbnail jpg --ppa "ThumbnailsConvertor+FFmpeg_o:-c:v mjpeg -qmin 1 -qscale:v 1 -vf crop=\"'"'"'if(gt(ih,iw),iw,ih)'"'"':'"'"'if(gt(iw,ih),ih,iw)'"'"'\""'
~~~

**Comment by error-reporting** [comment]
> > [@Rikiub](https://github.com/Rikiub) Could you post here how to do it please :) ? I didn't manage to use the cli_to_api script... 😢
> 
> Just download the script and execute as main:
> 
> `python -m cli-to-api`
> 
> And then add your **options**:
> 
> `python -m cli-to-api -x --flat-playlist --skip-downloads`
> 
> You will get a dict with the options.

the script import does not work if I only have yt-dlp executable and yt-dlp in not installed using pip

**Comment by bashonly** [comment]
if you only have the yt-dlp executable then you don't need to use `cli_to_api.py`

**Comment by Misterodd** [comment]
While I also don't see this as closed, you can fix this manually 🫠 with software like mp3tag (can do also vorbis comments and others) and insert (via extended tags) the image of the music.-playlist, that is squared.
And here comes my confusion: I see in the debug message, that it downloads the playlist image, but it seems to be 16:9 and not squared. But if I insert via right-click copy link, it is squared. 
I suspect this is the good all "music. makes it difficult for yt-dlp", and that would make it even more annoying. 

If I would have time, I would do a deep dive on this. But that's a plague for every open source project, free time. I am very thankful for your work.

**Comment by davidstroia26** [comment]
I  am a noob but I found a solution that worked for me, using chatgpt to write a script.
Just download the music or video like normal with --embed-thumbnail argument

You need python and pip.

Install the dependencies for python
`pip install mutagen pillow`

! The script works with m4a files !
copy the code in a txt file and rename it to something like crop.py
The script should be in the same folder as the music you want to modify,
then right click and use the Open in terminal option and type `python crop.py`
Hope this helps some noobs like me.


```
import os
from mutagen.mp4 import MP4, MP4Cover
from PIL import Image

def extract_thumbnail_from_m4a(file_path):
    try:
        audio = MP4(file_path)
        if 'covr' in audio:
            cover = audio['covr'][0]
            ext = "jpg" if cover.imageformat == MP4Cover.FORMAT_JPEG else "png"
            output_file = os.path.splitext(file_path)[0] + f".{ext}"
            with open(output_file, "wb") as img_out:
                img_out.write(cover)
            print(f"🟢 Extracted thumbnail: {output_file}")
        else:
            print(f"⚠️ No thumbnail in: {file_path}")
    except Exception as e:
        print(f"❌ Error extracting {file_path}: {e}")

def crop_center_square(img):
    width, height = img.size
    min_edge = min(width, height)
    left = (width - min_edge) // 2
    top = (height - min_edge) // 2
    right = left + min_edge
    bottom = top + min_edge
    return img.crop((left, top, right, bottom))

def crop_png(file_path):
    try:
        with Image.open(file_path) as img:
            cropped_img = crop_center_square(img)
            cropped_img.save(file_path)
            print(f"✂️ Cropped: {file_path}")
    except Exception as e:
        print(f"❌ Failed to crop {file_path}: {e}")

def embed_cover(m4a_path, image_path):
    if not os.path.exists(image_path):
        print(f"⚠️ Image missing for: {m4a_path}")
        return
    try:
        audio = MP4(m4a_path)
        with open(image_path, "rb") as img:
            cover_data = img.read()
        audio["covr"] = [MP4Cover(cover_data, imageformat=MP4Cover.FORMAT_PNG)]
        audio.save()
        print(f"✅ Embedded cover in: {m4a_path}")
    except Exception as e:
        print(f"❌ Failed to embed in {m4a_path}: {e}")

def delete_png_files(folder_path="."):
    for filename in os.listdir(folder_path):
        if filename.lower().endswith(".png"):
            file_path = os.path.join(folder_path, filename)
            try:
                os.remove(file_path)
                print(f"🗑️ Deleted: {filename}")
            except Exception as e:
                print(f"❌ Failed to delete {filename}: {e}")

def process_all_m4a_in_folder(folder_path="."):
    for filename in os.listdir(folder_path):
        if filename.lower().endswith(".m4a"):
            m4a_path = os.path.join(folder_path, filename)
            base_name = os.path.splitext(filename)[0]
            png_name = base_name + ".png"
            png_path = os.path.join(folder_path, png_name)

            extract_thumbnail_from_m4a(m4a_path)
            if os.path.exists(png_path):
                crop_png(png_path)
                embed_cover(m4a_path, png_path)

    # Final cleanup
    delete_png_files(folder_path)

if __name__ == "__main__":
    process_all_m4a_in_folder(".")

```

**Comment by TreesPlay** [comment]
This worked for me in Windows command line:

HQ jpeg:
```batchfile
--embed-thumbnail --convert-thumbnail jpg --ppa "ThumbnailsConvertor+FFmpeg_o:-c:v mjpeg -qmin 1 -qscale:v 1 -vf crop=\"min(iw\,ih)\":\"min(iw\,ih)\"" 
``` 

Scaling the album cover to a lower res:
```batchfile
--embed-thumbnail --convert-thumbnail jpg --ppa "ThumbnailsConvertor+FFmpeg_o:-c:v mjpeg -qmin 1 -qscale:v 1 -vf scale=320:320:force_original_aspect_ratio=increase,crop=320:320"
```

**Comment by ghost** [comment]
This command works very well in the ytdlnis app.

```
--embed-thumbnail --convert-thumbnail png --ppa "ThumbnailsConvertor:-vf crop=\"'if(gt(ih,iw),iw,ih)':'if(gt(iw,ih),ih,iw)'\""
```
