### ISSUE TITLE
setup.py legacy code

### ISSUE THREAD

**Issue by Alienmaster** [yt-dlp/yt-dlp#4296]
### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.06.29** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Hi,
we looked into the setup.py and found the import of distutils and setuptools.
See: https://github.com/yt-dlp/yt-dlp/blob/master/setup.py#L7L13

Is the legacy import of distutils obsolote because yt-dlp is supposed to run under python 3.7+ in contrast to youtube-dl with support of 2.6+/3.2+ ?
If this is the case we can create a pull request if you like.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
`distutils.spawn` could however be replaced

**Comment by Alienmaster** [comment]
We just want to get ahead of the deprication in [3.12](https://docs.python.org/3/library/distutils.html) :)

Is [self.dry_run](https://github.com/yt-dlp/yt-dlp/blob/master/setup.py#L110) mandatory?
