### ISSUE TITLE
Add support for Philharmonie de Paris (philharmoniedeparis.fr)

### ISSUE THREAD

**Issue by jesus2099** [yt-dlp/yt-dlp#4297]
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.06.29** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

France

### Example URLs

- random example: https://philharmoniedeparis.fr/live/concert/1139191-hisaishi-symphonique
- list of other examples: https://philharmoniedeparis.fr/live/concerts

### Provide a description that is worded well enough to be understood

Those videos are not downloadable with yt-dlp.
They don't require account to be watched from within the browser.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--list-formats', 'https://philharmoniedeparis.fr/live/concert/1139191-hisaishi-symphonique']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.06.29 [9d339c4] (win32_exe)
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.19042-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg N-92132-g0a41a8bf29, ffprobe N-92132-g0a41a8bf29
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
[debug] Downloading _update_spec from https://github.com/yt-dlp/yt-dlp/releases/download/2022.06.29/_update_spec
Latest version: 2022.06.29, Current version: 2022.06.29
yt-dlp is up to date (2022.06.29)
[debug] [generic] Extracting URL: https://philharmoniedeparis.fr/live/concert/1139191-hisaishi-symphonique
[generic] 1139191-hisaishi-symphonique: Requesting header
[redirect] Following redirect to https://philharmoniedeparis.fr/fr/live/concert/1139191-hisaishi-symphonique
[debug] [generic] Extracting URL: https://philharmoniedeparis.fr/fr/live/concert/1139191-hisaishi-symphonique
[generic] 1139191-hisaishi-symphonique: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] 1139191-hisaishi-symphonique: Downloading webpage
[generic] 1139191-hisaishi-symphonique: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://philharmoniedeparis.fr/fr/live/concert/1139191-hisaishi-symphonique
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1420, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1490, in __extract_info
  File "yt_dlp\extractor\common.py", line 640, in extract
  File "yt_dlp\extractor\generic.py", line 4130, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://philharmoniedeparis.fr/fr/live/concert/1139191-hisaishi-symphonique
```

**Comment by sqrtNOT** [comment]
So there are actually 2 different types of concerts on this page: standard which is just a single stream of video and Extraits which have chapter timestamps. These are usually to split out individual songs.

For reference the same concert in both types:
https://philharmoniedeparis.fr/fr/live/concert/1129666-danses-symphoniques
https://philharmoniedeparis.fr/fr/live/concert/1125599-danses-symphoniques

In either case the video is streamed in chunks from m3u8 files. These are dynamically populated on page load so there's nothing we can scrape without loading the page with something like phantomjs first.

However, There is also an embed url which seems to have all the same content and works for both types of concert:
Extraits: https://otoplayer.philharmoniedeparis.fr/fr/embed/1135426
standard: https://otoplayer.philharmoniedeparis.fr/fr/embed/1139513

The .m3u8 files from the embed videos seem to be referencing static paths:

For standard videos we have an .m3u8 that contains the entire stream at:
https://otoplayer.philharmoniedeparis.fr/fr/m3u8/########.m3u8
If you try to use this url with an Extraits video it will 404 however.

For Extraits each segment has its own .m3u8 file numbered seemingly from 01 to 99:
https://otoplayer.philharmoniedeparis.fr/fr/m3u8/########/01.m3u8
I couldn't find one with 100+ segments and even if it only has 3 segments it's still 0 padded so seems reliable.
This url also works with standard streams as well with 01 being the entire concert. However, downloading with this .m38u gives me "malformed AAC bitstream" warnings. The files seem quality enough though.

Not sure what would be the best way to approach this site but I can see 3 options:
1. load the page and grab the generated .m3u8.
2. loop through 01-99 and download each chunk individually then stop once a file is not found.
3. assume we're on a normal video and use the standard url and if that fails default to point 2 to download the Extraits.

@jesus2099 
For a workaround until we have an extractor written you can just open the video with either the normal or embed link, use the network tab in firefox or chrome's page inspector and grab the .m3u8 from there. You can then pass that to yt-dlp directly and it will download the video.

**Comment by jesus2099** [comment]
Thanks very much for your analyse and final tip!

**Comment by HobbyistDev** [comment]
> For Extraits each segment has its own .m3u8 file numbered seemingly from 01 to 99:
https://otoplayer.philharmoniedeparis.fr/fr/m3u8/########/01.m3u8
I couldn't find one with 100+ segments and even if it only has 3 segments it's still 0 padded so seems reliable.
This url also works with standard streams as well with 01 being the entire concert. However, downloading with this .m3u8 gives me "malformed AAC bitstream" warnings. The files seem quality enough though.

You can get the Extraits video from webpage source. I found a javascript variable that define where the m3u8 located.
For [this](https://otoplayer.philharmoniedeparis.fr/fr/embed/1135426) link, i found the javascript variable like this:
```js
document.otoLivePlayer.initialize({
	'id': 'otoPlay',
	'notitle': true,
	'config_file': 'https://otoplayer.philharmoniedeparis.fr/fr/config/1135426.json'
});
```
And then we can get the video(or maybe chapter?) from `config_file`. Here's `config_file` that i get:
```json
{
	"video_type": "Live",
	"language": "fr",
	"localization": null,
	"autorized": false,
	"ip": "192.168.22.10 -  -  - 0 - CONTRAT_1",
	"date_start": "2022-01-20T20:30+02:00",
	"date_end": "2022-01-20T23:59+02:00",
	"date_available": null,
	"title": "Quatuor Jérusalem, Miguel da Silva, Gary Hoffman : Dvorák",
	"recorded": "Concert enregistré à la Philharmonie de Paris (Salle des concerts - Cité de la musique) le 20 janvier 2022",
	"broadcasted": "",
	"mention": null,
	"tagline": "\u003cp style=\"margin-left:0cm; margin-right:0cm\"\u003e\u003cstrong\u003eLe Quatuor de Jérusalem interprète\u0026#160;le célèbre \u003cem\u003eQuatuor «\u0026#160;Américain\u0026#160;\u003c/em\u003e» de Dvořák. Il est rejoint par l’altiste Miguel da Silva et le violoncelliste Gary Hoffman pour le\u0026#160;non moins inspiré \u003cem\u003eSextuor à cordes\u003c/em\u003e du compositeur.\u003c/strong\u003e\u003c/p\u003e\r\n",
	"courtesy": null,
	"image": "https://gs1.wpc.edgecastcdn.net/008F13/http/images/poster/PPVI000312800.png",
	"aspectratio": "16:9",
	"mode": "sample",
	"mode_name": "Extrait",
	"startTrack": null,
	"composers": [{
		"name": "Dvorák Anton",
		"concerts": null,
		"link": null
	}, {
		"name": "Tchaikovski Piotr Ilitch",
		"concerts": null,
		"link": null
	}],
	"performers": [{
		"name": "Pavlovsky Alexander",
		"concerts": null,
		"link": null
	}, {
		"name": "Bresler Sergei",
		"concerts": null,
		"link": null
	}, {
		"name": "Kam Ori",
		"concerts": null,
		"link": null
	}, {
		"name": "Zlotnikov Kyril",
		"concerts": null,
		"link": null
	}, {
		"name": "Da Silva Miguel",
		"concerts": null,
		"link": null
	}, {
		"name": "Hoffman Gary",
		"concerts": null,
		"link": null
	}, {
		"name": "Quatuor Jérusalem ",
		"concerts": null,
		"link": null
	}],
	"chaptersfile": "https://otoplayer.philharmoniedeparis.fr/fr/vtt/1135426.vtt",
	"thumbnailsfile": "https://otoplayer.philharmoniedeparis.fr/fr/thumbnails/1135426.vtt",
	"chapters": [{
		"title": "Quatuor n° 12 en fa majeur, op 96 \"américain\" , Anton Dvorák",
		"start": "00:00:00",
		"end": "00:27:21.0660000",
		"index": "1",
		"startSample": "00:00:09.1100000",
		"endSample": "00:02:37.5840000",
		"files": {
			"desktop": {
				"file": "https://otoplayer.philharmoniedeparis.fr/fr/m3u8/1135426/01.m3u8"
			},
			"mobile": {
				"file": "https://otoplayer.philharmoniedeparis.fr/fr/m3u8/1135426/01.m3u8"
			}
		},
		"thumbnail": "https://gs1.wpc.edgecastcdn.net/008F13/http/images/vignette/PPVI000312801_01.png",
		"ccaptions": null
	}, {
		"title": "Sextuor à cordes en la majeur, op. 48 , Anton Dvorák",
		"start": "00:27:21.0660000",
		"end": "01:02:20.8640000",
		"index": "2",
		"startSample": "00:41:13.9310000",
		"endSample": "00:42:22.9250000",
		"files": {
			"desktop": {
				"file": "https://otoplayer.philharmoniedeparis.fr/fr/m3u8/1135426/02.m3u8"
			},
			"mobile": {
				"file": "https://otoplayer.philharmoniedeparis.fr/fr/m3u8/1135426/02.m3u8"
			}
		},
		"thumbnail": "https://gs1.wpc.edgecastcdn.net/008F13/http/images/vignette/PPVI000312801_02.png",
		"ccaptions": null
	}, {
		"title": "Aria de Lenski extrait de \"Eugène Oneguine\" op.24 (Acte 2, n° 17) (arrangement pour sextuor à cordes) [Rappel] , Piotr Ilitch Tchaikovski, Ori Kam",
		"start": "01:02:20.8640000",
		"end": "01:08:44.1800000",
		"index": "3",
		"startSample": "01:03:22.8550000",
		"endSample": "01:05:22.3030000",
		"files": {
			"desktop": {
				"file": "https://otoplayer.philharmoniedeparis.fr/fr/m3u8/1135426/03.m3u8"
			},
			"mobile": {
				"file": "https://otoplayer.philharmoniedeparis.fr/fr/m3u8/1135426/03.m3u8"
			}
		},
		"thumbnail": "https://gs1.wpc.edgecastcdn.net/008F13/http/images/vignette/PPVI000312801_03.png",
		"ccaptions": null
	}],
	"files": null,
	"embed": {
		"active": true,
		"url": "https://otoplayer.philharmoniedeparis.fr/embed/1135426/quatuor-jerusalem-miguel-da-silva-gary-hoffman-dvorak.html",
		"iframe": "https://otoplayer.philharmoniedeparis.fr/embed/1135426/quatuor-jerusalem-miguel-da-silva-gary-hoffman-dvorak.html"
	},
	"reload_interval": 0,
	"skin": {
		"name": "live",
		"url": "//otoplayer.philharmoniedeparis.fr/content/jw-player-skin/styles.css"
	},
	"ccaptions": null,
	"flags": null,
	"message": null,
	"stream": null
}
```

**Comment by sqrtNOT** [comment]
Nice find @HobbyistDev I totally neglected to check the source for the embed page. It seems like both Extraits and normal videos have a config.json and we don't even need to parse the html for it we can just go directly to https://otoplayer.philharmoniedeparis.fr/fr/config/########.json for the .m3u8 files in all cases. 

Some other things I noticed:
Mobile and Desktop seem to be the same urls so not sure what's up with that; might as well parse both.
The .m3u8 files are themselves just a container for multiple .m3u8 files which map onto different resolutions: SHQ, HQ, and LQ. Just passing the .m3u8 to the generic extractor pulls out the SHQ one (probably because it's listed first) but it's likely worth it to support them by format. Music isn't exactly the most visual medium so being able to archive the lower resolution streams is reasonably valuable if you just want to listen.
The thumbnails of each section in an Extraits video are pretty low quality pngs that I think are just used for the preview on the timeline in the player. We'd probably get better results pulling an actual frame from the video or just letting the OS handle it. They do however not have the watermark that the videos come with so maybe someone wants this preserved: https://gs1.wpc.edgecastcdn.net/008F13/http/images/vignette/PPVI000312801_01.png

As for how to deal with the Extraits videos we have some options in terms of output format. The most straightforward method is obviously just dl'ing each .m3u8 as its own file like it's a playlist and naming them accordingly. We could also potentially stitch the video back together from the parts and add chapters for what the song is. Not sure if it's worth the effort though or if users would prefer to just have individual files and they can playlist them on their own. Any opinion @jesus2099?

**Comment by jesus2099** [comment]
I have used an m3u8 in which I could choose between 3 formats.
I chose one called something like _720p_HD_, that I identified as the best.
Even if it's music, visuals are very important for a concert. 😉

I did not check the _Extraits_ (extracts) playlist, yet. 
I don't know if it really matches the concert program, splitting between each song, like chapters in a DVD, or just arbitrary regular splits.

I expect downloading the concert as a whole single big video, not as small parts, but if it can be translated to metadata chapters of the big video then it's very good.

But maybe as a secondary feature, later?

**Comment by pukkandan** [comment]
The extractor can implement it as a `multi_video` in which case yt-dlp will automatically concat the pieces together

**Comment by HobbyistDev** [comment]
By the way, this site already supported (see https://github.com/yt-dlp/yt-dlp/blob/master/yt_dlp/extractor/philharmoniedeparis.py). It didn't match with OP url so it raise `UnsupportedError`

**Comment by sqrtNOT** [comment]
@HobbyistDev I think it's actually the same API but the urls have changed recently. The currently supported ones are pad.philharmoniedeparis.fr and live.philharmoniedeparis.fr.
The pad. urls seem to still be up but I can't get the current extractor to download them: http://pad.philharmoniedeparis.fr/doc/CIMU/1086697/jazz-a-la-villette-knower gives me a 'NoneType' object does not support item assignment error. 
The live. urls on the other hand just redirect to what we're currently seeing and they work with the current extractor (when the urls are added to the regex). http://live.philharmoniedeparis.fr/concert/1032066.html

**Comment by HobbyistDev** [comment]
We can rewrite the 'live' url. From my machine, the pad url you provide only show 30 second of the opening. The api url we found ( `https://otoplayer.philharmoniedeparis.fr/fr/config/<id>.json` is also give the video info with `id=1086697` from the pad url and it works. I believe they migrated their video to this api

**Comment by sqrtNOT** [comment]
Works is relative for that video it seems. I also only get the 30 seconds of video in the player but even with the otoplayer json only chapter 9 has an m3u8 the rest of them are null. I'll replace it with a more reasonable test case and leave the pad. urls as supported even if they seem to be somewhat deprecated.
