### ISSUE TITLE
Does yt-dlp support multi-period mpd?

### ISSUE THREAD

**Issue by anhtule88** [yt-dlp/yt-dlp#4308]
### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.06.29** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I have a mpd which contains two periods. When I use yt-dlp to download, it only downloads the first part. Does yt-dlp support multi-period file? And if it does, can I specify which period to download?
Updated: I managed to get the format for the second period, but it seems that the file being download is incorrect.

### Provide verbose output that clearly demonstrates the problem

- [x] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [x] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output
```
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.06.29 [9d339c4] (zip)
[debug] Python 3.9.0 (CPython 64bit) - macOS-10.16-x86_64-i386-64bit
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: avprobe -bsfs
[debug] exe versions: ffmpeg N-101405-g2570663966-tessus (setts), phantomjs 2.1.1, rtmpdump 2.4
[debug] Optional libraries: certifi-2021.10.08, sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
[debug] Downloading _update_spec from https://github.com/yt-dlp/yt-dlp/releases/download/2022.06.29/_update_spec
Latest version: 2022.06.29, Current version: 2022.06.29
yt-dlp is up to date (2022.06.29)
[debug] [generic] Extracting URL: https://manifests.api.hbo.com/dash.mpd?f.audioTrack=en-US%7Cprogram&f.audioTrack=es-419%7Cprogram&r.duration=5.005000&r.duration=5641.469238&r.host=https%3A%2F%2Fcmaf.cf.us.hbomaxcdn.com&r.keymod=2&r.main=1&r.manifest=videos%2FGXrXxCwqQJZkiiwEAAABZ%2F1%2Fcb6d6e%2F1.mpd&r.manifest=videos%2FGYDVmsQYWETTCwwEAAAAR%2F1%2Fff45b7%2F1.mpd&r.origin=cmaf
[generic] dash.mpd?f.audioTrack=en-US|program&f.audioTrack=es-419|program&r.duration=5.005000&r.duration=5641.469238&r.host=https://cmaf.cf.us.hbomaxcdn.com&r.keymod=2&r.main=1&r.manifest=videos/GXrXxCwqQJZkiiwEAAABZ/1/cb6d6e/1.mpd&r.manifest=videos/GYDVmsQYWETTCwwEAAAAR/1/ff45b7/1.mpd&r: Requesting header
WARNING: [generic] Could not send HEAD request to https://manifests.api.hbo.com/dash.mpd?f.audioTrack=en-US%7Cprogram&f.audioTrack=es-419%7Cprogram&r.duration=5.005000&r.duration=5641.469238&r.host=https%3A%2F%2Fcmaf.cf.us.hbomaxcdn.com&r.keymod=2&r.main=1&r.manifest=videos%2FGXrXxCwqQJZkiiwEAAABZ%2F1%2Fcb6d6e%2F1.mpd&r.manifest=videos%2FGYDVmsQYWETTCwwEAAAAR%2F1%2Fff45b7%2F1.mpd&r.origin=cmaf: HTTP Error 404: Not Found
[generic] dash.mpd?f.audioTrack=en-US|program&f.audioTrack=es-419|program&r.duration=5.005000&r.duration=5641.469238&r.host=https://cmaf.cf.us.hbomaxcdn.com&r.keymod=2&r.main=1&r.manifest=videos/GXrXxCwqQJZkiiwEAAABZ/1/cb6d6e/1.mpd&r.manifest=videos/GYDVmsQYWETTCwwEAAAAR/1/ff45b7/1.mpd&r: Downloading webpage
WARNING: [generic] Falling back on generic information extractor.
[generic] dash.mpd?f.audioTrack=en-US|program&f.audioTrack=es-419|program&r.duration=5.005000&r.duration=5641.469238&r.host=https://cmaf.cf.us.hbomaxcdn.com&r.keymod=2&r.main=1&r.manifest=videos/GXrXxCwqQJZkiiwEAAABZ/1/cb6d6e/1.mpd&r.manifest=videos/GYDVmsQYWETTCwwEAAAAR/1/ff45b7/1.mpd&r: Extracting information
[debug] Identified a DASH manifest
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[info] dash.mpd?f.audioTrack=en-US|program&f.audioTrack=es-419|program&r.duration=5.005000&r.duration=5641.469238&r.host=https://cmaf.cf.us.hbomaxcdn.com&r.keymod=2&r.main=1&r.manifest=videos/GXrXxCwqQJZkiiwEAAABZ/1/cb6d6e/1.mpd&r.manifest=videos/GYDVmsQYWETTCwwEAAAAR/1/ff45b7/1.mpd&r: Downloading 1 format(s): a5
[debug] Invoking http downloader on "https://cmaf.cf.us.hbomaxcdn.com/videos/GYDVmsQYWETTCwwEAAAAR/1/ff45b7/a/a5.mp4"
[download] testhbo.m4a has already been downloaded
[download] 100% of 78.41KiB
```

**Comment by pukkandan** [comment]
Each period should show up as one or more formats. Without any examples or details, it is hard to say what your actual issue is...

**Comment by anhtule88** [comment]
> Each period should show up as one or more formats. Without any examples or details, it is hard to say what your actual issue is...

Thanks. I see the two formats now. But it seems that when I try to download 2nd period's video, it's working, but for the audio it's always the same with the first period (only about 80KB). When I use `curl` to check for the remote file's size (https://cmaf.cf.us.hbomaxcdn.com/videos/GYDVmsQYWETTCwwEAAAAR/1/ff45b7/a/a5.mp4), it should be 46018394 (more than 40MB instead). I don't know why it's not working.

**Comment by pukkandan** [comment]
1. You removed the top of the verbose
2. `[download] testhbo.m4a has already been downloaded` => delete this file and show log of the new run

**Comment by m0hamedessam** [comment]
For dynamic live multi period dash how to get current live period format to download because i see yt-dlp not choose current live period any idea ?
