### ISSUE TITLE
Slight Modification needed for Pluto Extractor

### ISSUE THREAD

**Issue by RedPenguin2** [yt-dlp/yt-dlp#431]
I just wanted to give a heads-up that it appears the Pluto Exactor just needs a slight modification to properly get the "new" Pluto URLs.

Pluto On-Demand gave me the URL of:
https://pluto.tv/en/on-demand/series/manhunters-fugitive-task-force/seasons/1/episode/third-times-the-charm-1-1
but it failed right away and was trying to use the "Generic" extractor.

I went to the GitHub Source and noticed the Extractor is looking for pluto.tv/on-demand NOT pluto.tv/en/on-demand.

It works instantly if I erase the /en/ off the URL but I don't know if that trick will always work or not.

**Comment by Sipherdrakon** [comment]
So has anyone tried this with the new commit? Because even though it recognizes the valid url with the ```/en/``` it will not grab the json and throws ```404 not found``` unless the ```/en/``` is omitted. Or is it just me?

**Comment by pukkandan** [comment]
It was working when I committed it. Maybe it has broken again since

**Comment by Sipherdrakon** [comment]
I just tested all the urls from the ```TESTS_``` and the only one that doesn't work is the last one with the ```/en/```. Maybe I can get python to use the given url and have it redirect to a url without it.

I'll edit this post when I get around my computer and can post the logs from the working and not working urls.

Or should I make a new issue?
