### ISSUE TITLE
Video Huaping

### ISSUE THREAD

**Issue by shimiaoyerin** [yt-dlp/yt-dlp#4316]
### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.06.29** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

In the process of downloading videos and videos, I found that some videos have abnormal screen flickering, and this is the case with a large number of videos, but when I use the same settings to download the same video again, this does not appear. That's a problem, I don't know how many of these videos are mixed in now. The following are the settings I usually download and the abnormal video

![QQ截图20220709192awd423](https://user-images.githubusercontent.com/45694554/178109491-6ec5b96c-b2d1-4599-9af3-45e4b2f43645.png)
![QQ图片20220709awd192305](https://user-images.githubusercontent.com/45694554/178109497-97533e9a-7714-47e7-a186-8fb310cefeb7.png)

https://drive.google.com/drive/folders/164TVmwWh6qnAjQ_GApLVSk-pMHOON1XM?usp=sharing

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
C:\Users\yerin>yt-dlp -vU
[debug] Command-line config: ['-vU']
[debug] Encodings: locale cp936, fs utf-8, pref cp936, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.06.29 [9d339c4] (win32_exe)
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.19042-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg n5.0.1-5-g240d82f26e-20220613 (setts), ffprobe n5.0.1-5-g240d82f26e-20220613
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {'http': 'http://127.0.0.1:10081', 'https': 'https://127.0.0.1:10081', 'ftp': 'ftp://127.0.0.1:10081'}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
[debug] Downloading _update_spec from https://github.com/yt-dlp/yt-dlp/releases/download/2022.06.29/_update_spec
Latest version: 2022.06.29, Current version: 2022.06.29
yt-dlp is up to date (2022.06.29)
```

**Comment by pukkandan** [comment]
> #### Make sure you are **only** asking a question and not reporting a bug or requesting a feature.
> If your question contains "isn't working" or "can you add", this is most likely the wrong template.
> If you are in doubt whether this is the right template, **use another template**!

Which part of this did you not understand?

---

Show the verbose log **THAT DEMONSTRATES YOUR PROBLEM**, not just some random log. In this case, that would be the download logs of when you got the damaged video and the correct video
