### ISSUE TITLE
featreq: CLI flag to only download video if any matching subtitles/autosubtitles are available

### ISSUE THREAD

**Issue by chapmanjacobd** [yt-dlp/yt-dlp#4324]
### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.06.29** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

There are a couple times when downloading media that I don't know the language for, where I would like to skip downloading video or audio if subtitles or autosubtitles are unavailable. 

For example https://www.youtube.com/playlist?list=PL-8EmzhQgHI_87XKvYa5GqEQzoDGi09qk

Of course, there aren't that many videos in the playlist that have matching subs: 49 of 177, about 28%, which I found by running --skip-download.

But for automated use--for periodically checking an undownloaded link to see if a new subtitle or autosub is available--it would nice to have an explicit CLI arg to provide this behavior.

Something like `--subs-required` or  `--any-subs-required`:

```
yt-dlp --subs-required --sub-lang en,EN,eng,ENG,en-gb,en-us,en-GB,en-US,EN-GB,EN-US,english,English,ENGLISH,en-CA,en-IE --write-subs --write-auto-subs --embed-subs --compat-options no-keep-subs $url
```

---

or more generically:

```
# Download video if any subtitle available
yt-dlp --download-depends subs --download-depends autosubs
yt-dlp --download-depends any-subs # shortcut
```

```
# Download video only if both matching subtitle and matching autosubtitle is available
yt-dlp --download-depends 'subs & autosubs'
```

---

or perhaps this fits as a format configuration?

```
yt-dlp -f bestvideo[height<=576]+bestaudio+any-subs/best[height<=576]+any-subs/best+any-subs
yt-dlp -f best[subs!=none][autosubs!=none]
```

ahh maybe this is already possible with --match-filter. not sure....

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
Already possible with `--match-filter`
```
❯ yt-dlp --match-filter requested_subtitles "https://www.youtube.com/playlist?list=PL-8EmzhQgHI_87XKvYa5GqEQzoDGi09qk" --write-auto-subs -I :10 -O playlist_index=
WARNING: [youtube:tab] YouTube said: INFO - Unavailable videos are hidden
WARNING: [youtube:tab] YouTube said: INFO - Unavailable videos will be hidden during playback
playlist_index = 1
ERROR: [youtube] hA-pkmcksrE: Video unavailable. This video contains content from ViewinTVRightsManagement, who has blocked it on copyright grounds
playlist_index = 6
```
