### ISSUE TITLE
[youtube_live_chat] Member's only chat can't be downloaded

### ISSUE THREAD

**Issue by pukkandan** [yt-dlp/yt-dlp#433]
Issue reported by @Lytexx in #422

_Originally posted by @siikamiika in https://github.com/yt-dlp/yt-dlp/issues/422#issuecomment-866110395_

---

I tested this with a stream that @Lytexx linked to me. While the `authorization` header makes Youtube think that you're logged in (`{ "key": "logged_in", "value": "1" }`), there's some additional layer of checks that prevents it from working and instead of `continuationContents` youtube replies with
```
  "contents": {
    "messageRenderer": {
      "text": {
        "runs": [
          {
            "text": "チャットは現在ご利用いただけません。" // chat is not currently available
          }
        ]
      }
    }
  }
```

Some things that Youtube does and might be required but I didn't have time to try:
- POST `https://www.youtube.com/youtubei/v1/updated_metadata?key=<key>`
- POST `https://www.youtube.com/youtubei/v1/player/heartbeat?alt=json&key=<key>`

I also managed to get some of the recent messages by requesting `https://www.youtube.com/live_chat?continuation=<continuation_id>` and parsing `ytInitialData` before starting to use the API, but that didn't help with the main issue, although in theory you could get all chat by polling the page frequently enough and filtering out duplicates.

One more thing I tried was requesting a specific chat from the live chat iframe page instead of `invalidationContinuationData` but that didn't help either
```diff
             continuation_data_getters = [
+                lambda x: x['header']['liveChatHeaderRenderer']['viewSelector']['sortFilterSubMenuRenderer']['subMenuItems'][0]['continuation']['reloadContinuationData'],
                 lambda x: x['continuations'][0]['invalidationContinuationData'],
                 lambda x: x['continuations'][0]['timedContinuationData'],
             ]
```

Here's the testing branch if someone wants to try https://github.com/siikamiika/yt-dlp/commit/5cb38040b2a00a27b9a294069f473f22854231b4

**Comment by siikamiika** [comment]
Did some testing on the pop-out chat frame at `https://www.youtube.com/live_chat?is_popout=1&v=<video_id>` and filtered out static downloads. Here's what Youtube does before starting to POST to `/youtubei/v1/live_chat/get_live_chat`:
- GET a script from where `ytcfg.GAPI_HINT_PARAMS` points to (not sure if that's relevant)
- POST `https://signaler-pa.youtube.com/punctual/v1/chooseServer?key=<innertube api key>`
```
to server:
application/json+protobuf
[
    [null,null,null,[3,5],null,[
        ["youtube_live_chat_web"],
        [true],
        [[[ytInitialData.contents.liveChatRenderer.continuations[0].invalidationContinuationData.invalidationId.topic]]]
    ]]
]

from server:
application/json+protobuf; charset=UTF-8
after base64 decoding: ["<gsessionid>", 1]
```
- POST `https://signaler-pa.youtube.com/punctual/multi-watch/channel?gsessionid=<gsessionid>&key=<innertube api key>&VER=8&RID=29521&CVER=22&zx=1r3do77uvrtb&t=1` (not sure about RID or xz)
```
to server:
application/x-www-form-urlencoded
count=1&ofs=0&req0___data__=<almost same as above url encoded>

from server:
text/plain; charset=utf-8
51 [[0,["c","<SID>","",8,12,30000]]]

51 is probably length not including the length itself
```

- GET `https://signaler-pa.youtube.com/punctual/multi-watch/channel?gsessionid=<gsessionid>&key=<innertube api key>&VER=8&RID=rpc&SID=<SID>&CI=0&AID=0&TYPE=xmlhttp&zx=eewk6rwk2br0&t=1` (again no idea about xz, it's different here)
```
from server:
text/plain; charset=utf-8
22[[1,[[[["1",[[]]]]]]]]
245[[2,[[[["1",[null,[[[null,null,"1624460973110362","1624460973174543",["1624460973110715","1624460973109488","1624460973110922","1624460973136025","1624460973174543","1624460973213042","1624460973213504"],[[[null,"935302147923119869"]]]]]]]]]]]]]
247[[3,[[[["1",[null,[[[null,null,"1624460974108161","1624460974164383",["1624460974108461","1624460974107502","1624460974108675","1624460974133804","1624460974164383","1624460974233359","1624460974233993"],[[[null,"-7355042483388648323"]]]]]]]]]]]]]
246[[4,[[[["1",[null,[[[null,null,"1624460975252680","1624460975312495",["1624460975253088","1624460975251947","1624460975253378","1624460975278517","1624460975312495","1624460975373667","1624460975374064"],[[[null,"3643716131321051560"]]]]]]]]]]]]]
...

Looks like timestamps in the beginning and random integers in the end of the lines
```

After this there's the first POST to `https://www.youtube.com/youtubei/v1/live_chat/get_live_chat?key=<innertube api key>`. The last GET doesn't at least seem to be used for the chat requests, so just the POST requests could be enough. The POST payload to get_live_chat doesn't seem to contain anything that isn't available from the context easily except `adSignalsInfo`.

`heartbeat` doesn't seem to be used on this page and `updated_metadata` is probably just view count and such.

I think the next thing I'm going to do is try to figure out the missing pieces and write a client that does the above as closely as possible and if it works, start removing irrelevant parts and adapt it to yt-dlp

**Comment by siikamiika** [comment]
It appears that most of the above was irrelevant to the actual issue which was not using `clickTrackingParams`
