### ISSUE TITLE
Youtube throws error for new signature

### ISSUE THREAD

**Issue by AiAe** [yt-dlp/yt-dlp#4331]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.06.29** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Finland

### Provide a description that is worded well enough to be understood

Looks like youtube has new signature

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
# yt-dlp JjOLTJXiXT4 --ignore-config --no-progress -f bestaudio -x --audio-format wav --add-metadata -vU
[debug] Command-line config: ['JjOLTJXiXT4', '--ignore-config', '--no-progress', '-f', 'bestaudio', '-x', '--audio-format', 'wav', '--add-metadata', '-vU']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.02.04 [c1653e9ef]
[debug] Python version 3.8.10 (CPython 64bit) - Linux-5.4.0-97-generic-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.7, ffprobe 4.2.7
[debug] Optional libraries: Cryptodome, secretstorage, mutagen, sqlite, websockets
[debug] Proxy map: {}
Latest version: 2022.06.29, Current version: 2022.02.04
ERROR: It looks like you installed yt-dlp with a package manager, pip or setup.py; Use that to update
[debug] [youtube] Extracting URL: JjOLTJXiXT4
[youtube] JjOLTJXiXT4: Downloading webpage
[youtube] JjOLTJXiXT4: Downloading android player API JSON
[youtube] JjOLTJXiXT4: Downloading player 0e7373c2
WARNING: [youtube] nsig extraction failed: You may experience throttling for some formats
n = m9V_uPJd49tm8AUSW ; player = https://www.youtube.com/s/player/0e7373c2/player_ias.vflset/en_US/base.js
JjOLTJXiXT4: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/extractor/youtube.py", line 2415, in _decrypt_nsig
    self._player_cache[player_id] = self._extract_n_function(video_id, player_url)
  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/extractor/youtube.py", line 2441, in _extract_n_function
    funcname = self._extract_n_function_name(jscode)
  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/extractor/youtube.py", line 2424, in _extract_n_function_name
    nfunc, idx = self._search_regex(
  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/extractor/common.py", line 1186, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
yt_dlp.utils.RegexNotFoundError: Unable to extract Initial JS player n function name; please report this issue on  https://github.com/yt-dlp/yt-dlp , filling out the "Broken site" issue template properly. Confirm you are on the latest version using -U
 (caused by RegexNotFoundError('Unable to extract \x1b[0;94mInitial JS player n function name\x1b[0m; please report this issue on  https://github.com/yt-dlp/yt-dlp , filling out the "Broken site" issue template properly. Confirm you are on the latest version using -U')); please report this issue on  https://github.com/yt-dlp/yt-dlp , filling out the "Broken site" issue template properly. Confirm you are on the latest version using -U
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[info] JjOLTJXiXT4: Downloading 1 format(s): 251
[download] XTREME Album Mix [JjOLTJXiXT4].wav has already been downloaded
[debug] ffmpeg command line: ffprobe -show_streams 'file:XTREME Album Mix [JjOLTJXiXT4].wav'
[ExtractAudio] Destination: XTREME Album Mix [JjOLTJXiXT4].wav
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:XTREME Album Mix [JjOLTJXiXT4].wav' -vn -f wav -movflags +faststart 'file:XTREME Album Mix [JjOLTJXiXT4].temp.wav'
Deleting original file XTREME Album Mix [JjOLTJXiXT4].orig.wav (pass -k to keep)
[Metadata] Adding metadata to "XTREME Album Mix [JjOLTJXiXT4].wav"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:XTREME Album Mix [JjOLTJXiXT4].wav' -i 'file:XTREME Album Mix [JjOLTJXiXT4].meta' -map 0 -dn -ignore_unknown -c copy -map_metadata 1 -metadata 'title=XTREME Album Mix' -metadata date=20210128 -metadata 'description=Stream / Buy : https://t.co/yVLjWDLG7x
```

**Comment by NanaMizukiAnother7** [comment]
I can't reproduce:
`[debug] Command-line config: ['JjOLTJXiXT4', '--ignore-config', '--no-progress', '-f', 'bestaudio', '-x', '--audio-format', 'wav', '--add-metadata', '-vU']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8 (No VT), error utf-8 (No VT), screen utf-8 (No VT)
[debug] yt-dlp version 2022.06.29 [9d339c4] (win32_exe)
[debug] Python 3.8.10 (CPython 64bit) - Windows-7-6.1.7601-SP1
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 2022-07-06-git-03d81a044a-full_build-www.gyan.dev (setts), ffprobe 2022-07-06-git-03d81a044a-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
[debug] Downloading _update_spec from https://github.com/yt-dlp/yt-dlp/releases/download/2022.06.29/_update_spec
Latest version: 2022.06.29, Current version: 2022.06.29
yt-dlp is up to date (2022.06.29)
[debug] [youtube] Extracting URL: JjOLTJXiXT4
[youtube] JjOLTJXiXT4: Downloading webpage
[youtube] JjOLTJXiXT4: Downloading android player API JSON
[debug] Loading youtube-nsig.0e7373c2 from cache
[debug] [youtube] Decrypted nsig Vd7dP8YQxnWyVPtyH => z95IKF_oHyt56g
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[info] JjOLTJXiXT4: Downloading 1 format(s): 251
[debug] Invoking http downloader on "https://rr3---sn-5fo-0u2l.googlevideo.com/videoplayback?expire=1657566669&ei=bSHMYoHwCcHDrtoPm5ibgAs&ip=184.22.41.208&id=o-AIkqTq5iO-FaHcKtCTdCC0ooczrRvw-mzXXXvEbmJLYg&itag=251&source=youtube&requiressl=yes&mh=Oz&mm=31%2C29&mn=sn-5fo-0u2l%2Csn-5fo-c33l7&ms=au%2Crdu&mv=m&mvi=3&pl=22&initcwndbps=1418750&vprv=1&mime=audio%2Fwebm&gir=yes&clen=39905978&dur=2555.421&lmt=1611859140796629&mt=1657544715&fvip=7&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=5432434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRAIgJGkBDTR8iFi_8GXsfJ8CMS8GzA2eSOjzTyhJ0nCANs0CIFd1gWwhMV_J5T4AGdGaGKyRSUu1I4mBwkOnK26-3h-u&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgKGPZJLXa-RFx71kdv5EoZUIy2P_yd1rglarrX0UJw1cCIQDEVruYi57_E1I-KBH2nX4cTIfDyyU5UkwRhO5XHVk0sw%3D%3D"
[debug] File locking is not supported. Proceeding without locking
[download] Destination: XTREME Album Mix [JjOLTJXiXT4].webm
[download] Download completed
[debug] ffmpeg command line: ffprobe -show_streams "file:XTREME Album Mix [JjOLTJXiXT4].webm"
[ExtractAudio] Destination: XTREME Album Mix [JjOLTJXiXT4].wav
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:XTREME Album Mix [JjOLTJXiXT4].webm" -vn -movflags "+faststart" "file:XTREME Album Mix [JjOLTJXiXT4].wav"
Deleting original file XTREME Album Mix [JjOLTJXiXT4].webm (pass -k to keep)
[Metadata] Adding metadata to "XTREME Album Mix [JjOLTJXiXT4].wav"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:XTREME Album Mix [JjOLTJXiXT4].wav" -i "file:XTREME Album Mix [JjOLTJXiXT4].meta" -map 0 -dn -ignore_unknown -c copy -map_metadata 1 -write_id3v1 1 -metadata "title=XTREME Album Mix" -metadata "date=20210128" -metadata "description=Stream / Buy : https://t.co/yVLjWDLG7x
Bandcamp : https://t.co/cd9RE7Rlsk
CD Media : TANO*C STORE
https://www.tanocstore.net/shopdetail/000000002634/
BOOTH https://usao926.booth.pm/

Tracklist
00:00 XTREME
01:20 XTREME (Extended Mix)
03:05 WildFire
06:01 Super Mega Jumbo
09:11 Blows Up Everything
11:12 Knight Rider (Extended Mix)
14:44 Knight Rider (Camellia's \"Knightstyle Razor-psy-  harp\" Remix)
19:08 Chariot (Extended Mix)
22:36 Cyaegha (Extended Mix)
25:41 Cyaegha (Laur Remix)
28:34 Climax (Extended Mix)
32:03 Enter The Rave
35:15 最強STRONGER (Extended Mix)
39:16 Climax (Kobaryo's FTN-Remix)

Album : XTREME
UOM Records / USAO-017
Design: NC Empire
https://ncempire.net/
illust: zunta
https://zuntapc.wixsite.com/undercontrol

Special Thanks
©lowiro
©SEGA
©Marvelous Inc. / Supported by HARDCORE TANO*C

Twitter : https://twitter.com/USAO926
Spotify : https://open.spotify.com/artist/25iPl8VJFDu38JMFF6uMXI?si=SBYaDHekROWYxiwiGXATNQ
bandcamp : http://usao.bandcamp.com
Apple Music : https://music.apple.com/jp/artist/usao/484358287
LINE MUSIC : https://music.line.me/artist/mi000000000009cf0b


##XTREME #WACCA #CHUNITHM #Arcaea" -metadata "synopsis=Stream / Buy : https://t.co/yVLjWDLG7x
Bandcamp : https://t.co/cd9RE7Rlsk
CD Media : TANO*C STORE
https://www.tanocstore.net/shopdetail/000000002634/
BOOTH https://usao926.booth.pm/

Tracklist
00:00 XTREME
01:20 XTREME (Extended Mix)
03:05 WildFire
06:01 Super Mega Jumbo
09:11 Blows Up Everything
11:12 Knight Rider (Extended Mix)
14:44 Knight Rider (Camellia's \"Knightstyle Razor-psy-  harp\" Remix)
19:08 Chariot (Extended Mix)
22:36 Cyaegha (Extended Mix)
25:41 Cyaegha (Laur Remix)
28:34 Climax (Extended Mix)
32:03 Enter The Rave
35:15 最強STRONGER (Extended Mix)
39:16 Climax (Kobaryo's FTN-Remix)

Album : XTREME
UOM Records / USAO-017
Design: NC Empire
https://ncempire.net/
illust: zunta
https://zuntapc.wixsite.com/undercontrol

Special Thanks
©lowiro
©SEGA
©Marvelous Inc. / Supported by HARDCORE TANO*C

Twitter : https://twitter.com/USAO926
Spotify : https://open.spotify.com/artist/25iPl8VJFDu38JMFF6uMXI?si=SBYaDHekROWYxiwiGXATNQ
bandcamp : http://usao.bandcamp.com
Apple Music : https://music.apple.com/jp/artist/usao/484358287
LINE MUSIC : https://music.line.me/artist/mi000000000009cf0b


##XTREME #WACCA #CHUNITHM #Arcaea" -metadata "purl=https://www.youtube.com/watch?v=JjOLTJXiXT4" -metadata "comment=https://www.youtube.com/watch?v=JjOLTJXiXT4" -metadata "artist=USAO" -movflags "+faststart" "file:XTREME Album Mix [JjOLTJXiXT4].temp.wav"`

**Comment by AiAe** [comment]
> I can't reproduce:
> 
> ```
> [debug] Command-line config: ['JjOLTJXiXT4', '--ignore-config', '--no-progress', '-f', 'bestaudio', '-x', '--audio-format', 'wav', '--add-metadata', '-vU']
> [debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8 (No VT), error utf-8 (No VT), screen utf-8 (No VT)
> [debug] yt-dlp version 2022.06.29 [9d339c4] (win32_exe)
> [debug] Python 3.8.10 (CPython 64bit) - Windows-7-6.1.7601-SP1
> [debug] Checking exe version: ffmpeg -bsfs
> [debug] Checking exe version: ffprobe -bsfs
> [debug] exe versions: ffmpeg 2022-07-06-git-03d81a044a-full_build-www.gyan.dev (setts), ffprobe 2022-07-06-git-03d81a044a-full_build-www.gyan.dev
> [debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
> [debug] Proxy map: {}
> [debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
> [debug] Downloading _update_spec from https://github.com/yt-dlp/yt-dlp/releases/download/2022.06.29/_update_spec
> Latest version: 2022.06.29, Current version: 2022.06.29
> yt-dlp is up to date (2022.06.29)
> [debug] [youtube] Extracting URL: JjOLTJXiXT4
> [youtube] JjOLTJXiXT4: Downloading webpage
> [youtube] JjOLTJXiXT4: Downloading android player API JSON
> [debug] Loading youtube-nsig.0e7373c2 from cache
> [debug] [youtube] Decrypted nsig Vd7dP8YQxnWyVPtyH => z95IKF_oHyt56g
> [debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
> [debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
> [info] JjOLTJXiXT4: Downloading 1 format(s): 251
> [debug] Invoking http downloader on "https://rr3---sn-5fo-0u2l.googlevideo.com/videoplayback?expire=1657566669&ei=bSHMYoHwCcHDrtoPm5ibgAs&ip=184.22.41.208&id=o-AIkqTq5iO-FaHcKtCTdCC0ooczrRvw-mzXXXvEbmJLYg&itag=251&source=youtube&requiressl=yes&mh=Oz&mm=31%2C29&mn=sn-5fo-0u2l%2Csn-5fo-c33l7&ms=au%2Crdu&mv=m&mvi=3&pl=22&initcwndbps=1418750&vprv=1&mime=audio%2Fwebm&gir=yes&clen=39905978&dur=2555.421&lmt=1611859140796629&mt=1657544715&fvip=7&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=5432434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRAIgJGkBDTR8iFi_8GXsfJ8CMS8GzA2eSOjzTyhJ0nCANs0CIFd1gWwhMV_J5T4AGdGaGKyRSUu1I4mBwkOnK26-3h-u&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgKGPZJLXa-RFx71kdv5EoZUIy2P_yd1rglarrX0UJw1cCIQDEVruYi57_E1I-KBH2nX4cTIfDyyU5UkwRhO5XHVk0sw%3D%3D"
> [debug] File locking is not supported. Proceeding without locking
> [download] Destination: XTREME Album Mix [JjOLTJXiXT4].webm
> [download] Download completed
> [debug] ffmpeg command line: ffprobe -show_streams "file:XTREME Album Mix [JjOLTJXiXT4].webm"
> [ExtractAudio] Destination: XTREME Album Mix [JjOLTJXiXT4].wav
> [debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:XTREME Album Mix [JjOLTJXiXT4].webm" -vn -movflags "+faststart" "file:XTREME Album Mix [JjOLTJXiXT4].wav"
> Deleting original file XTREME Album Mix [JjOLTJXiXT4].webm (pass -k to keep)
> [Metadata] Adding metadata to "XTREME Album Mix [JjOLTJXiXT4].wav"
> [debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:XTREME Album Mix [JjOLTJXiXT4].wav" -i "file:XTREME Album Mix [JjOLTJXiXT4].meta" -map 0 -dn -ignore_unknown -c copy -map_metadata 1 -write_id3v1 1 -metadata "title=XTREME Album Mix" -metadata "date=20210128" -metadata "description=Stream / Buy : https://t.co/yVLjWDLG7x
> Bandcamp : https://t.co/cd9RE7Rlsk
> CD Media : TANO*C STORE
> https://www.tanocstore.net/shopdetail/000000002634/
> BOOTH https://usao926.booth.pm/
> 
> Tracklist
> 00:00 XTREME
> 01:20 XTREME (Extended Mix)
> 03:05 WildFire
> 06:01 Super Mega Jumbo
> 09:11 Blows Up Everything
> 11:12 Knight Rider (Extended Mix)
> 14:44 Knight Rider (Camellia's \"Knightstyle Razor-psy-  harp\" Remix)
> 19:08 Chariot (Extended Mix)
> 22:36 Cyaegha (Extended Mix)
> 25:41 Cyaegha (Laur Remix)
> 28:34 Climax (Extended Mix)
> 32:03 Enter The Rave
> 35:15 最強STRONGER (Extended Mix)
> 39:16 Climax (Kobaryo's FTN-Remix)
> 
> Album : XTREME
> UOM Records / USAO-017
> Design: NC Empire
> https://ncempire.net/
> illust: zunta
> https://zuntapc.wixsite.com/undercontrol
> 
> Special Thanks
> ©lowiro
> ©SEGA
> ©Marvelous Inc. / Supported by HARDCORE TANO*C
> 
> Twitter : https://twitter.com/USAO926
> Spotify : https://open.spotify.com/artist/25iPl8VJFDu38JMFF6uMXI?si=SBYaDHekROWYxiwiGXATNQ
> bandcamp : http://usao.bandcamp.com
> Apple Music : https://music.apple.com/jp/artist/usao/484358287
> LINE MUSIC : https://music.line.me/artist/mi000000000009cf0b
> 
> 
> ##XTREME #WACCA #CHUNITHM #Arcaea" -metadata "synopsis=Stream / Buy : https://t.co/yVLjWDLG7x
> Bandcamp : https://t.co/cd9RE7Rlsk
> CD Media : TANO*C STORE
> https://www.tanocstore.net/shopdetail/000000002634/
> BOOTH https://usao926.booth.pm/
> 
> Tracklist
> 00:00 XTREME
> 01:20 XTREME (Extended Mix)
> 03:05 WildFire
> 06:01 Super Mega Jumbo
> 09:11 Blows Up Everything
> 11:12 Knight Rider (Extended Mix)
> 14:44 Knight Rider (Camellia's \"Knightstyle Razor-psy-  harp\" Remix)
> 19:08 Chariot (Extended Mix)
> 22:36 Cyaegha (Extended Mix)
> 25:41 Cyaegha (Laur Remix)
> 28:34 Climax (Extended Mix)
> 32:03 Enter The Rave
> 35:15 最強STRONGER (Extended Mix)
> 39:16 Climax (Kobaryo's FTN-Remix)
> 
> Album : XTREME
> UOM Records / USAO-017
> Design: NC Empire
> https://ncempire.net/
> illust: zunta
> https://zuntapc.wixsite.com/undercontrol
> 
> Special Thanks
> ©lowiro
> ©SEGA
> ©Marvelous Inc. / Supported by HARDCORE TANO*C
> 
> Twitter : https://twitter.com/USAO926
> Spotify : https://open.spotify.com/artist/25iPl8VJFDu38JMFF6uMXI?si=SBYaDHekROWYxiwiGXATNQ
> bandcamp : http://usao.bandcamp.com
> Apple Music : https://music.apple.com/jp/artist/usao/484358287
> LINE MUSIC : https://music.line.me/artist/mi000000000009cf0b
> 
> 
> ##XTREME #WACCA #CHUNITHM #Arcaea" -metadata "purl=https://www.youtube.com/watch?v=JjOLTJXiXT4" -metadata "comment=https://www.youtube.com/watch?v=JjOLTJXiXT4" -metadata "artist=USAO" -movflags "+faststart" "file:XTREME Album Mix [JjOLTJXiXT4].temp.wav"
> ```

I closed the issue since my issue was not related to this, because I ran ytdlp on the wrong user and it was outdated version, thats why I closed the issue. 😅
