### ISSUE TITLE
[Compile] SyntaxError: invalid syntax when loading module hook 'hook-yt_dlp.py'

### ISSUE THREAD

**Issue by nicolaasjan** [yt-dlp/yt-dlp#4332]
### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.06.29** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

When compiling in a Windows 7 VM, I get:

```python
11124 INFO: Loading module hook 'hook-yt_dlp.py' from 'C:\\Program Files\\Python38\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
  File "<string>", line 3
    import yt-dlp
             ^
SyntaxError: invalid syntax
```
Installed all the latest requirements, including Pyinstaller from this repo.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU']
[debug] User config "C:\Users\Nico\AppData\Roaming\yt-dlp\config.txt": ['--list-formats-as-table', '--no-mtime', '-o', '~/Desktop/%(title)s.%(ext)s', '-f', 'bestvideo[height<=1080][ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best', '--embed-thumbnail', '--add-metadata', '--convert-thumbnails', 'jpg', '--ppa', 'ThumbnailsConvertor:-q:v 1', '--ppa', 'ffmpeg:-metadata synopsis=""', '--force-ipv4', '--sponsorblock-remove', 'all', '--external-downloader', 'aria2c', '--external-downloader-args', 'aria2c:-x 10 -s 10 -j 10 -k 1M --log-level=info --file-allocation=none']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out cp1252 (No VT), error cp1252 (No VT), screen cp1252 (No VT)
[debug] yt-dlp version 2022.07.11 [4e7f375c9] (win32_exe)
[debug] Python 3.8.10 (CPython 64bit) - Windows-7-6.1.7601-SP1 
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg N-107363-gc6fdbe26ef-20220710 (setts), ffprobe N-107363-gc6fdbe26ef-20220710
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.06.29, Current version: 2022.07.11
yt-dlp is up to date (2022.07.11)
```

**Comment by nicolaasjan** [comment]
yt-dlp is just working fine however.
Can I ignore this "error"?

**Comment by nicolaasjan** [comment]
> > 11124 INFO: Loading module hook 'hook-yt_dlp.py' from 'C:\Program Files\Python38\lib\site-packages\_pyinstaller_hooks_contrib\hooks\stdhooks'...
> 
> There seems to be an error in your pyinstaller. I can't reproduce it on the latest pyinstaller version, so try updating if you are on an older version

I deliberately uninstalled and reinstalled [Pyinstaller](https://yt-dlp.github.io/Pyinstaller-Builds/x86_64/pyinstaller-4.10-py3-none-any.whl) before posting, just to be sure.

**Comment by pukkandan** [comment]
Why are you using our custom builds? They are meant only for use in our release process. Install the actual pyinstaller

**Comment by nicolaasjan** [comment]
> Why are you using our custom builds? They are meant only for use in our release process. Install the actual pyinstaller

Thanks!
I thought the custom one was somehow better. Cant remember where I read that.
Will try again with the official one. 🙂
