### ISSUE TITLE
How to embedd yt-dlp and download into buffer/memory

### ISSUE THREAD

**Issue by FirefoxMetzger** [yt-dlp/yt-dlp#4338]
### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.06.29** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I was wondering if there is an option to download into a `BytesIO` object instead of downloading to a file that lives on disk when embedding yt-dlp (i.e. when using it inside python). I.e., I'd like to do something like the following (perhaps with a nicer syntax):

```python
import io
from yt-dlp import YoutubeDL

buffer = io.BytesIO()
YoutubeDL.download(["some_YT_code"], out=buffer)
# the video is now stored inside `buffer`
```

Is this possible already? I don't know the API well, so chances are I am missing something which is why I am asking how to do this.

---

Background: My overall goal is to extract a specific section/interval from a youtube video. I can do this directly using `yt-dlp` to get the video URL and then relying on `av`/`pyav` to access the section of the stream I need. This, however, is much slower than downloading the whole video and then extracting the section locally instead. The downside is that this currently touches the filesystem, and it would be great if I could avoid that since my immediate next step is to discard 90% of the video anyway.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
This is not possible directly https://github.com/yt-dlp/yt-dlp/issues/3298. But assuming your code is single threaded, you can use `contextlib.redirect_stdout` with `'outtmpl': '-'` to workaround.

For your specific usecase, using `download_ranges` is probably better (it uses ffmpeg) https://github.com/yt-dlp/yt-dlp/blob/13aac8dd58a7c8043dcada6a1552a7a059d182dd/yt_dlp/YoutubeDL.py#L433-L439

**Comment by FirefoxMetzger** [comment]
Ah, so it would be a new feature. In this case I'll close this one in favor of #3298.

**Comment by FirefoxMetzger** [comment]
@pukkandan Sorry if me closing the issue came across as rude or disappointed; that wasn't my thinking. 

It's moreso that the issue title suggests that it's about combining `io.BytesIO` and yt-dlp and that is better tracked by #3298. To avoid confusion for others coming across this issue I figured the clean thing to do would be to close here in favor of the other issue. That said, feel free to reopen if you think it would be more useful this way :)

---

 > Do either of the other solutions not suite your use case?

Printing to stdout sounds like a nice idea. I'll check if I can piece together a workaround for this. Is it possible to suppress any other logging to `stdout` so that the only thing fed into the pipe is the video?

Using `download_ranges` might be useful, but I will have to do some benchmarking and digging into what is happening under the hood. 

Based on the docstring I'd assume that FFmpeg will re-encode the video to honor the exact start and end time specified. FFmpeg doesn't ship with a VP9 (webm) encoder by default (only the decoder is included), but I would like to preserve that encoding because it tends to produce fewer movement artifacts. So one part I'll have to work out is how yt-dlp uses FFmpeg, if it includes the VP9 encoder, and if I can supply my own version.

My current solution via `pyav` (also using FFmpeg under the hood) simply remuxes the interval of interest and if needed rounds the starting time to the nearest keyframe. This is faster than re-encoding on the FFmpeg side, but streaming via FFmpeg seems slower than what yt-dlp is doing. Hence the need to benchmark :)

**Comment by pukkandan** [comment]
> It's moreso that the issue title suggests that it's about combining io.BytesIO and yt-dlp and that is better tracked by https://github.com/yt-dlp/yt-dlp/issues/3298. To avoid confusion for others coming across this issue I figured the clean thing to do would be to close here in favor of the other issue. That said, feel free to reopen if you think it would be more useful this way :)

No, closing issue is perfectly fine.

> Printing to stdout sounds like a nice idea. I'll check if I can piece together a workaround for this. Is it possible to suppress any other logging to stdout so that the only thing fed into the pipe is the video?


You can either set `'logtostderr': True`, or use a custom `logger` according to your exact needs

> Based on the docstring I'd assume that FFmpeg will re-encode the video to honor the exact start and end time specified.

Re-encoding is not done by default and the cuts are therefore not exact. If you want to re-encode, you must specify `'force_keyframes_at_cuts': True`.


> My current solution via pyav (also using FFmpeg under the hood) simply remuxes the interval of interest and if needed rounds the starting time to the nearest keyframe. This is faster than re-encoding on the FFmpeg side, but streaming via FFmpeg seems slower than what yt-dlp is doing. Hence the need to benchmark :)

I didn't realize pyav is using ffmpeg as well. Ffmpeg's downloader is generally slower than yt-dlp's native one. If that is the bottleneck you are experiencing, using download_ranges is likely to suffer the same slowdown

**Comment by FirefoxMetzger** [comment]
> You can either set 'logtostderr': True, or use a custom logger according to your exact needs

Perfect, if it is possible to control the logs then I think writing to `stdout` is a doable workaround. I'll leave a comment in #3298 once I have it up and running.

> Re-encoding is not done by default and the cuts are therefore not exact. If you want to re-encode, you must specify 'force_keyframes_at_cuts': True.

Oh, then this solution doesn't work for my use-case; I tried it and it appears to discard the original timestamp of the first frame being used. This way I can't work out my desired range retrospectively because I can't say how many frames I need to discard initially until I get to the start of the range. I also just tried `'force_keyframes_at_cuts': True`, but that is the slowest option so far.

@pukkandan  On a tangent: Would you welcome a PR that improves the documentation of `download_ranges`? The callback signature doesn't seem current. It is documented as `(info_dict, *, ydl) -> Iterable[Section]`, but that signature doesn't work for me. Instead, I had to use `(info_dict, ydl) -> Iterable[Section]`. Also `Section` is only sparsely defined and it might make it more clear to say `Each Section is a dict with the following keys` instead of saying `Each Section contains`.

> I didn't realize pyav is using ffmpeg as well.

Yes, pyav is a set of cython bindings into libavcodec, libavformat, etc. Essentially trading ease of use (compared to the FFmpeg CLI) for performance.

**Comment by pukkandan** [comment]
> On a tangent: Would you welcome a PR that improves the documentation of download_ranges

Sure

I also just realized that `force_keyframes_at_cuts` is not documented atm
