### ISSUE TITLE
Restore functionality of webpage_url_domain token

### ISSUE THREAD

**Issue by robjwells** [yt-dlp/yt-dlp#4344]
### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.06.29** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

The `webpage_url_domain` output template token currently may only produce a portion of the domain, for instance a URL at the domain `www.bbc.co.uk` produces `co.uk`.

This is due to a recent change to `utils.get_domain` in ae61d108dd83a951b6e8a27e1fb969682416150d, where the new implementation only returns a portion of the end of the `netloc`. Here's the relevant diff from that commit:

```diff
 def get_domain(url):
-    domain = re.match(r'(?:https?:\/\/)?(?:www\.)?(?P<domain>[^\n\/]+\.[^\n\/]+)(?:\/(.*))?', url)
-    return domain.group('domain') if domain else None
+    return '.'.join(urllib.parse.urlparse(url).netloc.rsplit('.', 2)[-2:])
```

Here's a CSV showing the difference in output for domains that appear in the yt-dlp repository: [get_domain-differences.csv](https://github.com/yt-dlp/yt-dlp/files/9102603/get_domain-differences.csv)

Note: I filed this as a feature request as it's not site-specific, and there isn't a template for non-site-specific bug report.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU']
[debug] User config "/Users/robjwells/.config/yt-dlp/config": ['--output', '%(modified_date>%Y-%m-%d,upload_date>%Y-%m-%d)s - %(creator,uploader.:20)s - %(webpage_url_domain)s - %(id)s - %(title.:60)s.%(ext)s', '--no-call-home', '--format-sort', 'quality,codec:h265:m4a', '--remux-video=mkv>mp4/mov>mp4/webm>mp4', '--write-auto-subs', '--embed-subs', '--embed-thumbnail', '--add-metadata', '--xattrs']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.06.29 [9d339c4]
[debug] Python 3.10.5 (CPython 64bit) - macOS-12.3.1-x86_64-i386-64bit
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 5.0.1 (setts), ffprobe 5.0.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.14.1, brotli-1.0.9, certifi-2022.05.18.1, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3, xattr-0.9.9
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
[debug] Downloading _update_spec from https://github.com/yt-dlp/yt-dlp/releases/download/2022.06.29/_update_spec
Latest version: 2022.06.29, Current version: 2022.06.29
yt-dlp is up to date (2022.06.29)
```

**Comment by pukkandan** [comment]
The documentation is not clear about whether the subdomain is supposed to be in the field. But it turns out both implementations are wrong whichever way it is interpreted 😢

* The older implementation gets the entire netloc except when `subdomain=www` which is inconsistent.
* The new implementation tries to return only the registered domain, but breaks for URLs like `www.bbc.co.uk`. A foolproof implementation of what I intended here seems to be impossible except for hardcoding the [PSL](https://publicsuffix.org/list/).

I could instead make it return the netloc always to maintain consistency. But for now, I'll just revert the change to keep backward compat

**Comment by dirkf** [comment]
Clearly the new code doesn't match the regex-based code. Just `split` instead of `rsplit` would bring it closer.

Should the spec for this be to remove any of a set of standard prefixes? Eg: 
```
www|api|app|cdn|clips|content|embeds?|live|m|mobile|media|play(?:er)?|static|tv|videos?|view|vod|watch
```

**Comment by pukkandan** [comment]
> Clearly the new code doesn't match the regex-based code

How so?

**Comment by pukkandan** [comment]
Ah, ok. I thought you were talking about the new new code
