### ISSUE TITLE
Is extract_info reusing its connection, or is it possible to make it so?

### ISSUE THREAD

**Issue by FirefoxMetzger** [yt-dlp/yt-dlp#4346]
### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.06.29** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I am interested in getting info objects from `extract_info` in bulk (from youtube videos). In doing so I've noticed that the call to `extract_info` takes about 700ms on my machine and is the most costly part of my particular application. The returned object is only a small json-like object, so I'd expect it to be much faster than that.

My guess is that this behavior is due to `extract_info` using a new connection each time. Hence **I am wondering if it is possible to re-use an existing connection to bring down the overhead of re-connecting**. If the high runtime has another reason I'm also happy for other solutions that reduce this :)

Here is an example snippet of what I am doing

```python
import yt_dlp

sample_ids = [
    "000QsbOC-a4",
    "0010FaFAuEQ",
    "007GCFjxwDE",
    "009PTx5MQoo",
    "00_9wTz_ME4",
    "00BGAaAAQmQ",
    "00caf-lbOJ0",
    "00CmBayT6J8",
    "00cTcpXlNrY",
    "00Cu74634lk",
    "00DHtI093U4",
    "00DJ8xwhlwg",
]

with yt_dlp.YoutubeDL({"format": "bv"}) as ydl:
    for youtube_id in sample_ids:
        stream_info = ydl.extract_info(youtube_id, download=False)

        # in my application there is some post-processing here, but this is comparatively cheap
        # I do need stream_info["url"] though ... not sure if relevant.
```

The snippet above has the following timings on my machine (times are in seconds):

```python
9.121 <module>  <string>:1
   [4 frames hidden]  <string>, runpy
      9.121 _run_code  runpy.py:64
      └─ 9.121 <module>  delete_me.py:1
         ├─ 8.860 extract_info  yt_dlp\YoutubeDL.py:1369
         │     [1738 frames hidden]  yt_dlp, urllib, http, socket, ssl, <b...
         │        3.435 _SSLSocket.read  <built-in>:0
         └─ 0.198 <module>  yt_dlp\__init__.py:1
               [418 frames hidden]  yt_dlp, Cryptodome, <built-in>, ntpat...
```

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by coletdjnz** [comment]
Currently there is not support for persistent connections, but we are working on it!  See https://github.com/yt-dlp/yt-dlp/pull/3668


Feel free to try it out and see if it improves performance in your case - would be interesting to see.

**Comment by FirefoxMetzger** [comment]
@coletdjnz Thanks for pointing that out. Using the PR as is resulted in a minor improvement of the timings. Down to about 600 ms from the original 700ms.

```python
7.814 <module>  <string>:1
   [8 frames hidden]  <string>, runpy, pkgutil, <frozen zip...
      7.813 _run_code  runpy.py:63
      └─ 7.813 <module>  delete_me.py:1
         ├─ 7.124 extract_info  yt_dlp\YoutubeDL.py:1379
         │     [2148 frames hidden]  yt_dlp, urllib3, http, socket, ssl, <...
         │        3.579 _SSLSocket.read  <built-in>:0
         ├─ 0.463 __init__  yt_dlp\YoutubeDL.py:540
         │     [323 frames hidden]  yt_dlp, <built-in>, re, sre_compile, ...
         └─ 0.225 <module>  yt_dlp\__init__.py:1
               [666 frames hidden]  yt_dlp, urllib3, re, sre_compile, sre...
```

While skiming the PR I saw the new option `no_persistent_connections`. Do I have to take any steps to explicitly enable connection sharing?

**Comment by coletdjnz** [comment]
Persistent connections is on by default. The rest of delay is likely from other stuff e.g. all the requests that have to be made (which differs between videos and extractors), extractor regex matching, etc. 600ms is already pretty fast.

For youtube you can always have a play around with the extractor arguments to try optimize things for you use (e.g. disabling DASH videos or going API only/webpage only). https://github.com/yt-dlp/yt-dlp#youtube
