### ISSUE TITLE
[Site Request] [Funimation] Playlist extractor

### ISSUE THREAD

**Issue by Jules-A** [yt-dlp/yt-dlp#436]
## Checklist

- [X] I'm reporting a site feature request
- [X] I've verified that I'm running yt-dlp version **2021.06.23**
- [X] I've searched the bugtracker for similar site feature requests including closed ones

## Description

@Mevious I tried your changes but I still can't get it to work unless I did something wrong? https://github.com/Jules-A/yt-dlp/tree/funplaylist 

```
[funimation:playlist] Logging in
[debug] [funimation:playlist] Extracting URL: https://www.funimation.com/shows/c3-anime
[funimation:playlist] c3-anime: Downloading webpage
WARNING: [funimation:playlist] c3-anime: Failed to parse JSON Expecting value: line 1 column 1 (char 0)
[funimation:playlist] c3-anime: Downloading JSON metadata
[download] Downloading playlist: None
[funimation:playlist] playlist None: Collected 0 videos; downloading 0 of them
[download] Finished downloading playlist: None
```

**Comment by Mevious** [comment]
Same here. I think Funimation has made some site changes which break it, possibly as recently as today. Yesterday this was working by visiting the URL which includes the language code. Using your example that would be https://www.funimation.com/en/shows/c3-anime. Notice the added "/en". This directed to the old version of the page which was working. Trying now it appears that _all_ show sites are now redirecting to the new version which is failing to parse. My change will probably need to be rewritten.

**Comment by Mevious** [comment]
It turns out it isn't so bad. I updated the show ID lookup and I think this branch should work, at least for URLs including "/en". https://github.com/Mevious/yt-dlp/tree/mevious/funimation-playlist

```
[debug] [funimation:playlist] Extracting URL: https://www.funimation.com/en/shows/sk8-the-infinity/
[funimation:playlist] sk8-the-infinity: Downloading JSON metadata
[funimation:playlist] sk8-the-infinity: Downloading JSON metadata
[download] Downloading playlist: SK8 the Infinity
[funimation:playlist] playlist SK8 the Infinity: Collected 13 videos; downloading 13 of them
[download] Downloading video 1 of 13
[debug] [Funimation] Extracting URL: https://www.funimation.com/en/shows/sk8-the-infinity/part-01-snowfall-on-a-hot-night
[Funimation] part-01-snowfall-on-a-hot-night: Downloading webpage
[Funimation] 1370616: Downloading JSON metadata
[Funimation] 1370616: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 1370616: Downloading 1 format(s): hls-9998
[download] Downloading video 2 of 13
[debug] [Funimation] Extracting URL: https://www.funimation.com/en/shows/sk8-the-infinity/part-02-awesome-for-the-first-time
[Funimation] part-02-awesome-for-the-first-time: Downloading webpage
[Funimation] 1375282: Downloading JSON metadata
[Funimation] 1375282: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 1375282: Downloading 1 format(s): hls-10037
[download] Downloading video 3 of 13
[debug] [Funimation] Extracting URL: https://www.funimation.com/en/shows/sk8-the-infinity/part-03-undesired-hero
[Funimation] part-03-undesired-hero: Downloading webpage
[Funimation] 1320867: Downloading JSON metadata
[Funimation] 1320867: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 1320867: Downloading 1 format(s): hls-8094
[download] Downloading video 4 of 13
[debug] [Funimation] Extracting URL: https://www.funimation.com/en/shows/sk8-the-infinity/part-04-adam-the-matador-of-love
[Funimation] part-04-adam-the-matador-of-love: Downloading webpage
[Funimation] 1320865: Downloading JSON metadata

ERROR: Interrupted by user
```

**Comment by Jules-A** [comment]
Problem for me is the playlist page just redirects me to the version without the language code.

**Comment by Mevious** [comment]
Could you post the full command you're using? It's working for me when I add /en/ to the URL. Here's a full example command that works for me.
`python.exe "c:\my_clones\yt-dlp\yt_dlp\__main__.py" --username my_email@emailservice.com --password "my_password" --cookies "C:\path_to\cookies.txt" https://www.funimation.com/en/shows/blood-blockade-battlefront/`
It appears login is required for mature rated shows. This much simpler example also works for me.
`python.exe "c:\my_clones\yt-dlp\yt_dlp\__main__.py" https://www.funimation.com/en/shows/noragami/`
I'm not seeing that error for either of these examples.

**Comment by Jules-A** [comment]
```

yt-dlp -v https://www.funimation.com/en/shows/blood-blockade-battlefront/ -o "%%(extractor)s\%%(title)s - %%(myindex)s.%%(ext)s" --parse-metadata "original_url:#%%(myindex)s" --parse-metadata "%%(series)s - S%%(season_number)sE%%(episode_number)s - %%(episode)s:^(?P<title>.+ - S\d+E\d+ - \S+.*)$" --cookies cookies-funimation-com.txt --output-na-placeholder "" --embed-subs --sub-langs enUS,en --user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:89.0) Gecko/20100101 Firefox/89.0" -n --fragment-retries "infinite" -N 3 --no-mtime --download-archive archive.txt -P temp:D:\Temp\

```

In this case the episode numbers I add to the url (#1, #2 ect.) don't get parsed but it still shouldn't cause that error, I will check with simpler cmd.

**Comment by Mevious** [comment]
I think you're running into an authentication issue. When I run your command, I successfully find 25 episodes, but they are failing to download.
`ERROR: An extractor error has occurred. (caused by KeyError('items')); please report this issue on  https://github.com/yt-dlp/yt-dlp ...`

This is the exact same error I get when I try to download a specific episode from that series.
`c:\programs\python\python39\python.exe "C:\my_clones\yt-dlp\yt_dlp\__main__.py" https://www.funimation.com/en/shows/blood-blockade-battlefront/secret-society-of-the-magic-sealed-city`
```
[Funimation] secret-society-of-the-magic-sealed-city: Downloading webpage
[Funimation] 138334: Downloading JSON metadata
ERROR: An extractor error has occurred. (caused by KeyError('items')); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
```

When I authenticate with `--username my_email@emailservice.com --password "my_password" --cookies "C:\path_to\cookies.txt"` as shown above, it works for me. I also tried your command on a free non-mature show (Noragami), and it appears to work fine.

**Comment by Jules-A** [comment]
> I think you're running into an authentication issue. When I run your command, I successfully find 25 episodes, but they are failing to download.

Nah, they do actually download but there's a warning given. I'm logging in with netrc and using cookies.

**Comment by Mevious** [comment]
Makes sense. Looks like my run was failing because I don't have netrc.
`WARNING: [Funimation] parsing .netrc: [Errno 2] No such file or directory: 'C:\\Users\\Mevious\\.netrc'`
Now I'm able to see that warning if I replace -n with username and password. I also see the same warning when downloading an individual episode, so I think it is unrelated to playlists.

**Comment by Jules-A** [comment]
Ah you are right... I'm seeing it even using a build based on master and using basic cmdl options (including doing --username and --password)... Looks like something else broke unrelated to playlists.
