### ISSUE TITLE
Setting download options for a specific source_preference in Python

### ISSUE THREAD

**Issue by BarnameESF** [yt-dlp/yt-dlp#4360]
### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.06.29** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Hello
Do not be tired
I use your script to download from YouTube.
I wanted to know how to set the option so that it only downloads for example **source_preference with a value of -1**?

I download the best available mp4 file for the requested YouTube link with the following codes in Python, Ubuntu operating system.
`
import yt_dlp
URL = 'https://www.youtube.com/watch?v=dsfsfdsfdsfdsfds'
ydl_opts = {
    'format' : 'mp4/bestvideo/best',
    'outtmpl': "./data/dl/133121-1001111111111"+".%(ext)s",
}
with yt_dlp.YoutubeDL(ydl_opts) as ydl:
    filename = ydl.extract_info(URL, download=True)
`

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
Add an appropriate filter to your `format`. Eg: `'format': '(bv*+ba)[source_preference=-1]'`

By I don't recommend filtering by souce_preference, preference etc. These fields are only meant for sorting and their actual values don't mean anything. As such, they may change in future with no warning
