### ISSUE TITLE
no-playlist support for instagram post/stories

### ISSUE THREAD

**Issue by pritam20ps05** [yt-dlp/yt-dlp#4364]
### Checklist

- [X] I'm requesting a site-specific feature
- [X] I've verified that I'm running yt-dlp version **2022.06.29** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

India

### Example URLs

multi video post: https://www.instagram.com/p/BQ0eAlwhDrw/
highlights: https://www.instagram.com/stories/highlights/18090946048123978/

### Provide a description that is worded well enough to be understood

When no-playlist parameter is specified then a multi video post or a highlight must return the first valid entry rather than a playlist. 

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.06.29 [9d339c41e] (source)
[debug] Lazy loading extractors is disabled
[debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
[debug] Git HEAD: 2c55e0b6c
[debug] Python 3.9.2 (CPython 64bit) - Linux-5.10.0-kali9-amd64-x86_64-with-glibc2.33 (glibc 2.33)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.4.1-1 (setts), ffprobe 4.4.1-1
[debug] Optional libraries: Cryptodome-3.9.7, brotli-1.0.9, certifi-2020.06.20, sqlite3-2.6.0, websockets-8.1
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.06.29, Current version: 2022.06.29
yt-dlp is up to date (2022.06.29)
```

**Comment by pukkandan** [comment]
Does the individual posts have unique URLs? If so, when a user passes the "multi video post's" URL is there any ambiguity whether they are expecting to download the video vs the playlist?

If the answer is no to either of these, `--no-playlist` is not suitable for this situation. You can always use `--playlist-items` to controll what you want to download

**Comment by pukkandan** [comment]
From the linked PR, it looks like you are just always downloading the first item. `--no-playlist` is not a substitute for `-I 1`!

**Comment by pritam20ps05** [comment]
but playlist items still returns in the form of a playlist. How to get a single entry in its original form except in a playlist?

**Comment by pukkandan** [comment]
You didn't answer my questions though. And what do you mean by "original form"?

**Comment by pritam20ps05** [comment]
> You didn't answer my questions though. And what do you mean by "original form"?

Just raw data of an entry, i.e `entries[0]` of a playlist.

**Comment by pukkandan** [comment]
I don't understand. Why can't you get that from the current implementation?

**Comment by pritam20ps05** [comment]
So whats the actual work of no-playlist

**Comment by pukkandan** [comment]
When it's ambiguous whether a URL points to playlist or video. Like `youtube.com/watch?v=xxx&list=yyy`

**Comment by pukkandan** [comment]
Closing the issue since it seems you don't intend to answer any of my questions

**Comment by pritam20ps05** [comment]
> When it's ambiguous whether a URL points to playlist or video. Like `youtube.com/watch?v=xxx&list=yyy`

After a little bit of digging found that `no-playlist` is only valid for such urls pointing to a specific video. Ok thanks for the help.
