### ISSUE TITLE
Add equivalent to --no-progress-bar to disable printing "Remaining time until next attempt" with --wait-for-video

### ISSUE THREAD

**Issue by fuzxi** [yt-dlp/yt-dlp#4365]
### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.06.29** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

I frequently use scripts to invoke yt-dlp and pipe the output to a log file for review. I also use the `--wait-for-video` flag, so I can download livestreams in case I miss them. Running yt-dlp with `--wait-for-video` before a live stream starts results in it printing `[wait] Remaining time until next attempt: XX:XX:XX` and updating this value every second. This can potentially result in writing hundreds of additional lines to the log file for a single download - one stream yesterday had a wait of 14 minutes before the next attempt, printing 860 lines.

I am requesting a switch equivalent to `--no-progress-bar` that either disables printing `[wait]` lines, or only prints one, at the beginning of a wait, rather than updating every second.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by gamer191** [comment]
In my opinion this should be the default for `--no-progress`

**Comment by spam100011** [comment]
Ymsymsymdym

**Comment by spam100011** [comment]
Smysmdhnd

**Comment by spam100011** [comment]
Gsmsyndynd

**Comment by spam100011** [comment]
Mhnshnshnd

**Comment by spam100011** [comment]
Koqowowkw

**Comment by spam100011** [comment]
8126+26/$
