### ISSUE TITLE
[tvthek.orf.at] download entire video as one file

### ISSUE THREAD

**Issue by someziggyman** [yt-dlp/yt-dlp#4368]
### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.06.29** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Not sure if this is a bug, so just decided to post it as a question first.

Test link:
https://tvthek.orf.at/profile/Starnacht-am-Woerthersee/13887541/Starnacht-am-Woerthersee/14142769

It seems to download just fine, but downloads in chunks. Tried with --no-playlist and the result is still the same.
Anything I'm missing here? How do I get an entire media file?

./yt-dlp --no-playlist "https://tvthek.orf.at/profile/Starnacht-am-Woerthersee/13887541/Starnacht-am-Woerthersee/14142769"

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
Wdym "in chunks"? Show verbose log

**Comment by someziggyman** [comment]
Chunks=parts, pieces 
If you open the link and look at the video timeline you'll see "dots" on it like timecodes (chapters). when used with yt-dlp it will download everything just fine. But I guess the server responds with a "playlist" format of some sort and  resulting output is 30 files which match those timecodes. I thought, --no-playlist should let me download an entire video with all of those merged together. Thought the log was not needed cause it all downloads well and looking on the page and problem description should have been clear. My apologies for the confusion. Please see the log below:


./yt-dlp -vU --no-playlist "https://tvthek.orf.at/profile/Starnacht-am-Woerthersee/13887541/Starnacht-am-Woerthersee/14142769"
[debug] Command-line config: ['-vU', '--no-playlist', 'https://tvthek.orf.at/profile/Starnacht-am-Woerthersee/13887541/Starnacht-am-Woerthersee/14142769']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.06.29 [9d339c41e] (zip)
[debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
[debug] Python 3.9.13 (CPython 64bit) - macOS-12.4-arm64-arm-64bit 
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: avconv -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: avprobe -bsfs
[debug] exe versions: none
[debug] Optional libraries: sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.06.29, Current version: 2022.06.29
yt-dlp is up to date (2022.06.29)
[debug] [orf:tvthek] Extracting URL: https://tvthek.orf.at/profile/Starnacht-am-Woerthersee/13887541/Starnacht-am-Woerthersee/14142769
[orf:tvthek] 14142769: Downloading webpage
[download] Downloading playlist: 14142769
[orf:tvthek] 15201725: Downloading hls-Q1A-Niedrig m3u8 manifest
[orf:tvthek] 15201725: Downloading hls-Q4A-Mittel m3u8 manifest
[orf:tvthek] 15201725: Downloading hls-Q6A-Hoch m3u8 manifest
[orf:tvthek] 15201725: Downloading hls-Q8C-Sehr hoch m3u8 manifest
[orf:tvthek] 15201725: Downloading hls-QXB-Adaptiv m3u8 manifest
[orf:tvthek] 15201725: Downloading f4m manifest
[orf:tvthek] 15201725: Downloading f4m manifest
[orf:tvthek] 15201725: Downloading f4m manifest
[orf:tvthek] 15201725: Downloading f4m manifest
[orf:tvthek] 15201725: Downloading f4m manifest
[orf:tvthek] 15201725: Downloading dash-Q1A-Niedrig mpd manifest
[orf:tvthek] 15201725: Downloading dash-Q4A-Mittel mpd manifest
[orf:tvthek] 15201725: Downloading dash-Q6A-Hoch mpd manifest
[orf:tvthek] 15201725: Downloading dash-Q8C-Sehr hoch mpd manifest
[orf:tvthek] 15201725: Downloading dash-QXB-Adaptiv mpd manifest
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[orf:tvthek] 15201726: Downloading hls-Q1A-Niedrig m3u8 manifest
[orf:tvthek] 15201726: Downloading hls-Q4A-Mittel m3u8 manifest
[orf:tvthek] 15201726: Downloading hls-Q6A-Hoch m3u8 manifest
[orf:tvthek] 15201726: Downloading hls-Q8C-Sehr hoch m3u8 manifest
[orf:tvthek] 15201726: Downloading hls-QXB-Adaptiv m3u8 manifest
[orf:tvthek] 15201726: Downloading f4m manifest
[orf:tvthek] 15201726: Downloading f4m manifest
[orf:tvthek] 15201726: Downloading f4m manifest
[orf:tvthek] 15201726: Downloading f4m manifest
[orf:tvthek] 15201726: Downloading f4m manifest
[orf:tvthek] 15201726: Downloading dash-Q1A-Niedrig mpd manifest
[orf:tvthek] 15201726: Downloading dash-Q4A-Mittel mpd manifest
[orf:tvthek] 15201726: Downloading dash-Q6A-Hoch mpd manifest
[orf:tvthek] 15201726: Downloading dash-Q8C-Sehr hoch mpd manifest
[orf:tvthek] 15201726: Downloading dash-QXB-Adaptiv mpd manifest
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[orf:tvthek] 15201727: Downloading hls-Q1A-Niedrig m3u8 manifest
[orf:tvthek] 15201727: Downloading hls-Q4A-Mittel m3u8 manifest
[orf:tvthek] 15201727: Downloading hls-Q6A-Hoch m3u8 manifest
[orf:tvthek] 15201727: Downloading hls-Q8C-Sehr hoch m3u8 manifest
[orf:tvthek] 15201727: Downloading hls-QXB-Adaptiv m3u8 manifest
[orf:tvthek] 15201727: Downloading f4m manifest
[orf:tvthek] 15201727: Downloading f4m manifest
[orf:tvthek] 15201727: Downloading f4m manifest
[orf:tvthek] 15201727: Downloading f4m manifest
[orf:tvthek] 15201727: Downloading f4m manifest
[orf:tvthek] 15201727: Downloading dash-Q1A-Niedrig mpd manifest
[orf:tvthek] 15201727: Downloading dash-Q4A-Mittel mpd manifest
[orf:tvthek] 15201727: Downloading dash-Q6A-Hoch mpd manifest
[orf:tvthek] 15201727: Downloading dash-Q8C-Sehr hoch mpd manifest
[orf:tvthek] 15201727: Downloading dash-QXB-Adaptiv mpd manifest
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[orf:tvthek] 15201728: Downloading hls-Q1A-Niedrig m3u8 manifest
[orf:tvthek] 15201728: Downloading hls-Q4A-Mittel m3u8 manifest
[orf:tvthek] 15201728: Downloading hls-Q6A-Hoch m3u8 manifest
[orf:tvthek] 15201728: Downloading hls-Q8C-Sehr hoch m3u8 manifest
[orf:tvthek] 15201728: Downloading hls-QXB-Adaptiv m3u8 manifest
[orf:tvthek] 15201728: Downloading f4m manifest
[orf:tvthek] 15201728: Downloading f4m manifest
[orf:tvthek] 15201728: Downloading f4m manifest
[orf:tvthek] 15201728: Downloading f4m manifest
[orf:tvthek] 15201728: Downloading f4m manifest
[orf:tvthek] 15201728: Downloading dash-Q1A-Niedrig mpd manifest
[orf:tvthek] 15201728: Downloading dash-Q4A-Mittel mpd manifest
[orf:tvthek] 15201728: Downloading dash-Q6A-Hoch mpd manifest
[orf:tvthek] 15201728: Downloading dash-Q8C-Sehr hoch mpd manifest
[orf:tvthek] 15201728: Downloading dash-QXB-Adaptiv mpd manifest
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[orf:tvthek] 15201729: Downloading hls-Q1A-Niedrig m3u8 manifest
[orf:tvthek] 15201729: Downloading hls-Q4A-Mittel m3u8 manifest
[orf:tvthek] 15201729: Downloading hls-Q6A-Hoch m3u8 manifest
[orf:tvthek] 15201729: Downloading hls-Q8C-Sehr hoch m3u8 manifest
[orf:tvthek] 15201729: Downloading hls-QXB-Adaptiv m3u8 manifest
[orf:tvthek] 15201729: Downloading f4m manifest
[orf:tvthek] 15201729: Downloading f4m manifest
[orf:tvthek] 15201729: Downloading f4m manifest
[orf:tvthek] 15201729: Downloading f4m manifest
[orf:tvthek] 15201729: Downloading f4m manifest
[orf:tvthek] 15201729: Downloading dash-Q1A-Niedrig mpd manifest
[orf:tvthek] 15201729: Downloading dash-Q4A-Mittel mpd manifest
[orf:tvthek] 15201729: Downloading dash-Q6A-Hoch mpd manifest
[orf:tvthek] 15201729: Downloading dash-Q8C-Sehr hoch mpd manifest
[orf:tvthek] 15201729: Downloading dash-QXB-Adaptiv mpd manifest
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[orf:tvthek] 15201730: Downloading hls-Q1A-Niedrig m3u8 manifest
[orf:tvthek] 15201730: Downloading hls-Q4A-Mittel m3u8 manifest
[orf:tvthek] 15201730: Downloading hls-Q6A-Hoch m3u8 manifest
[orf:tvthek] 15201730: Downloading hls-Q8C-Sehr hoch m3u8 manifest
[orf:tvthek] 15201730: Downloading hls-QXB-Adaptiv m3u8 manifest
[orf:tvthek] 15201730: Downloading f4m manifest
[orf:tvthek] 15201730: Downloading f4m manifest
[orf:tvthek] 15201730: Downloading f4m manifest
hls-audio0-Originalton-1[orf:tvthek] 15201730: Downloading f4m manifest
[orf:tvthek] 15201730: Downloading f4m manifest
[orf:tvthek] 15201730: Downloading dash-Q1A-Niedrig mpd manifest
[orf:tvthek] 15201730: Downloading dash-Q4A-Mittel mpd manifest
[orf:tvthek] 15201730: Downloading dash-Q6A-Hoch mpd manifest
[orf:tvthek] 15201730: Downloading dash-Q8C-Sehr hoch mpd manifest
^Z
zsh: suspended  ./yt-dlp -vU --no-playlist

**Comment by pukkandan** [comment]
The extractor should be returning it as a `multi_video`. For now, you can use `--concat always` to work around this

**Comment by Ottaviocr** [comment]
Hi, I am able to download the videos from orf as one using `--no-playlist` and `--concat always` but the subtitles are still split in multiple chunks. Is there a workaround? I can post full verbose log, but let me know if I can do it here or if I have to open a new issue.

**Comment by seproDev** [comment]
The tvthek is no longer available. Segmented episodes are supported by the new orf:on extractor as of 8b46ad4d8b8ee8c5472af0cde863baa89ca3f425
