### ISSUE TITLE
-J with --download-archive returns undesirable 4-field-object entries

### ISSUE THREAD

**Issue by progonkpa** [yt-dlp/yt-dlp#4369]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.06.29** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

UK

### Provide a description that is worded well enough to be understood

- I'm testing this with a Bitchute channel with only 3 videos.
- I remove the newest ID from the archive file. Video with title ""Wat er echt gaande is en de uitweg voor de mensheid.".
- I fetch the channel a 2nd time with ` yt-dlp -J --download-archive "archive-file" https://www.bitchute.com/channel/sasaDelmundo/`
- The resulting JSON below.

```
  "entries": [
    {
      "id": "1pLYanHQcpcB",
      "title": "Wat er echt gaande is en de uitweg voor de mensheid.",
      "description": "",
      "thumbnail": "https://static-3.bitchute.com/live/cover_images/0NAnZgQgZ6Hf/1pLYanHQcpcB_640x360.jpg",
      "uploader": "SasaDelmundo",
      "upload_date": "20220208",
      "webpage_url": "https://www.bitchute.com/video/1pLYanHQcpcB",
      "original_url": "https://www.bitchute.com/video/1pLYanHQcpcB",
      "webpage_url_basename": "1pLYanHQcpcB",
      "webpage_url_domain": "bitchute.com",
      "extractor": "BitChute",
      "extractor_key": "BitChute",
      "n_entries": 3,
      "__last_playlist_index": 3,
      "playlist_count": 3,
      "playlist_index": 1,
      "playlist_autonumber": 1,
      "playlist": "sasaDelmundo",
      "playlist_id": "sasaDelmundo",
      "playlist_title": null,
      "playlist_uploader": null,
      "playlist_uploader_id": null,
      "display_id": "1pLYanHQcpcB",
      "fulltitle": "Wat er echt gaande is en de uitweg voor de mensheid.",
      "requested_subtitles": null,
      "_has_drm": null,
      "ext": "mp4",
      "width": null,
      "height": null,
      "tbr": null,
      "format_id": "0",
      "url": "https://zn21g5kls-n995.bitchute.com/0NAnZgQgZ6Hf/1pLYanHQcpcB.mp4",
      "vcodec": null,
      "http_headers": {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36",
        "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
        "Accept-Language": "en-us,en;q=0.5",
        "Sec-Fetch-Mode": "navigate",
        "Referer": "https://www.bitchute.com/video/1pLYanHQcpcB"
      },
      "protocol": "https",
      "video_ext": "mp4",
      "audio_ext": "none",
      "format": "0 - unknown",
      "resolution": null,
      "dynamic_range": "SDR"
    },
    {
      "ie_key": "BitChute",
      "id": "D2QCFBgrlmCW",
      "_type": "url",
      "url": "https://www.bitchute.com/video/D2QCFBgrlmCW"
    },
    {
      "ie_key": "BitChute",
      "id": "bG1jvzEhR4UM",
      "_type": "url",
      "url": "https://www.bitchute.com/video/bG1jvzEhR4UM"
    }
  ]
 ```

The problematic part now is the last 2 JSON objects which are the two videos that were downloaded before.

```
    {
      "ie_key": "BitChute",
      "id": "D2QCFBgrlmCW",
      "_type": "url",
      "url": "https://www.bitchute.com/video/D2QCFBgrlmCW"
    },
    {
      "ie_key": "BitChute",
      "id": "bG1jvzEhR4UM",
      "_type": "url",
      "url": "https://www.bitchute.com/video/bG1jvzEhR4UM"
    }
```
Is this working as designed because I can't see the point of those objects and they are messing up my application atm. Is it possible to remove these objects from the output?

Ideally only the full entries of new videos would be in the entries array, none of those 4-field objects.

Regardless from all that's been said in this issue, what I want to accomplish is, fetch metadata only for new videos and create a new updated JSON file with all old and new intries (from the 2nd command run).

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-J', '--download-archive', '/home/freetalk/Videos/DLV/downloaded/https_--www_bitchute_com-channel-sasaDelmundo-', '-vU', 'https://www.bitchute.com/channel/sasaDelmundo/']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8 (No ANSI), error utf-8, screen utf-8
[debug] yt-dlp version 2022.06.29 [9d339c4]
[debug] Python 3.10.5 (CPython 64bit) - Linux-5.16.20-2-MANJARO-x86_64-with-glibc2.35 (glibc 2.35)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 5.0.1 (setts), ffprobe 5.0.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.12.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loading archive file '/home/freetalk/Videos/DLV/downloaded/https_--www_bitchute_com-channel-sasaDelmundo-'
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
[debug] Downloading _update_spec from https://github.com/yt-dlp/yt-dlp/releases/download/2022.06.29/_update_spec
Latest version: 2022.06.29, Current version: 2022.06.29
yt-dlp is up to date (2022.06.29)
[debug] [BitChuteChannel] Extracting URL: https://www.bitchute.com/channel/sasaDelmundo/
[download] Downloading playlist: sasaDelmundo
[BitChuteChannel] sasaDelmundo: Downloading channel page 1
[BitChuteChannel] sasaDelmundo: Downloading channel page 2
[BitChuteChannel] Playlist sasaDelmundo: Downloading 3 videos of 3
[download] Downloading video 1 of 3
[debug] [BitChute] Extracting URL: https://www.bitchute.com/video/1pLYanHQcpcB
[BitChute] 1pLYanHQcpcB: Downloading webpage
[BitChute] 1pLYanHQcpcB: Checking video URL
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 1pLYanHQcpcB: Downloading 1 format(s): 0
[download] D2QCFBgrlmCW has already been recorded in the archive
[download] bG1jvzEhR4UM has already been recorded in the archive
[download] Finished downloading playlist: sasaDelmundo
```

**Comment by dirkf** [comment]
Is your point that items recorded in the download archive should be filtered from the `-J` output, so that the JSON  only includes items that would have been downloaded otherwise?

**Comment by pukkandan** [comment]
Yes. See https://www.reddit.com/r/youtubedl/comments/vzvhq0/unexpected_output_from_downloadarchive/

**Comment by progonkpa** [comment]
> Is your point that items recorded in the download archive should be filtered from the `-J` output, so that the JSON  only includes items that would have been downloaded otherwise?

Yes. I uodate the OP.
"Ideally only the full entries of new videos would be in the entries array, none of those 4-field objects."

**Comment by progonkpa** [comment]
Fyi, I found a workaround for my application using jq.
` command_dump_json_using_downloaded_archive | jq 'del(.entries[] | select(.ie_key))'`
