### ISSUE TITLE
Small audio glitch after 10 seconds

### ISSUE THREAD

**Issue by Chartman123** [yt-dlp/yt-dlp#4370]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.06.29** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Germany

### Provide a description that is worded well enough to be understood

When I download music from Youtube Music I get a small audio glitch after 10 seconds. I could reproduce it on two different machines with the latest yt-dlp version. I don't know if it's yt-dlp related or if it also happens with youtube-dl

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://music.youtube.com/watch?v=Z7cuTnbF-2c']
[debug] User config "/home/chris/.config/yt-dlp/config": ['-x', '-o', '~/Downloads/%(playlist)s/%(title)s_%(id)s.%(ext)s', '--cookies', '~/.config/yt-dlp/cookies.txt', '--download-archive', '~/.config/yt-dlp/archive.txt', '--no-mtime', '--audio-quality', '0', '--add-metadata', '-f', '141/ba']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.06.29 [9d339c4] (zip)
[debug] Python 3.10.5 (CPython 64bit) - Linux-5.18.9-2-default-x86_64-with-glibc2.35 (glibc 2.35)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.4.2 (fdk,setts), ffprobe 4.4.2
[debug] Optional libraries: certifi-2021.10.08, mutagen-1.45.1, sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Loading archive file '/home/chris/.config/yt-dlp/archive.txt'
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
[debug] Downloading _update_spec from https://github.com/yt-dlp/yt-dlp/releases/download/2022.06.29/_update_spec
Latest version: 2022.06.29, Current version: 2022.06.29
yt-dlp is up to date (2022.06.29)
[debug] [youtube] Extracting URL: https://music.youtube.com/watch?v=Z7cuTnbF-2c
[youtube] Z7cuTnbF-2c: Downloading webpage
[debug] [youtube] Extracted SAPISID cookie
[youtube] Z7cuTnbF-2c: Downloading android player API JSON
[youtube] Z7cuTnbF-2c: Downloading android music player API JSON
[youtube] Z7cuTnbF-2c: Downloading web music client config
[youtube] Z7cuTnbF-2c: Downloading player dfd2e197
[youtube] Z7cuTnbF-2c: Downloading web music player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[info] Z7cuTnbF-2c: Downloading 1 format(s): 141
[debug] Invoking http downloader on "https://rr1---sn-4g5edndl.googlevideo.com/videoplayback?expire=1658109969&ei=sWvUYrDvK4XJgQfs1oi4Cw&ip=31.19.146.44&id=o-AIPw0Wxv9klp9Spn-irJxysIjGRFVWKCUHmeGhq9F0EP&itag=141&source=youtube&requiressl=yes&mh=FT&mm=31%2C29&mn=sn-4g5edndl%2Csn-4g5e6nzz&ms=au%2Crdu&mv=m&mvi=1&pl=24&ctier=A&pfa=5&gcr=de&initcwndbps=1785000&hightc=yes&vprv=1&mime=audio%2Fmp4&gir=yes&clen=6953288&dur=215.933&lmt=1588190860896242&mt=1658088063&fvip=2&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID_MUSIC&txp=5531432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cctier%2Cpfa%2Cgcr%2Chightc%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIgfi_dxs7SwChuV_8MnikvMYaAo9C5u8uZkc7YgyxmsUUCIQC_ysNyU6sQtZ3lCISUxTIaL-TOqo4B7Zx5r6xHeO3aeg%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgKOC4c1ccTGh7kX6CLrLgICEaOO49VcTrE0m3bl1QGu0CIQDvRcKbXpeoHqA1dDsE4zdlnYQ0B5xr3Jr7Of0jeCEBUA%3D%3D"
[download] Destination: /home/chris/Downloads/NA/Je veux_Z7cuTnbF-2c.m4a
[download] 100% of 6.63MiB in 00:00
[FixupM4a] Correcting container of "/home/chris/Downloads/NA/Je veux_Z7cuTnbF-2c.m4a"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:/home/chris/Downloads/NA/Je veux_Z7cuTnbF-2c.m4a' -map 0 -dn -ignore_unknown -c copy -f mp4 -movflags +faststart 'file:/home/chris/Downloads/NA/Je veux_Z7cuTnbF-2c.temp.m4a'
[ExtractAudio] Not converting audio /home/chris/Downloads/NA/Je veux_Z7cuTnbF-2c.m4a; the file is already in a common audio format
[Metadata] Adding metadata to "/home/chris/Downloads/NA/Je veux_Z7cuTnbF-2c.m4a"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:/home/chris/Downloads/NA/Je veux_Z7cuTnbF-2c.m4a' -map 0 -dn -ignore_unknown -vn -acodec copy -write_id3v1 1 -metadata 'title=Je veux' -metadata date=20170209 -metadata 'description=Provided to YouTube by Parlophone (France)

Je veux · Zaz

Zaz

℗ 2010 Play On / Warner Music France

Lead  Vocals: Zaz
Composer, Writer: Kerredine Soltani
Composer: Tryss

Auto-generated by YouTube.' -metadata 'synopsis=Provided to YouTube by Parlophone (France)

Je veux · Zaz

Zaz

℗ 2010 Play On / Warner Music France

Lead  Vocals: Zaz
Composer, Writer: Kerredine Soltani
Composer: Tryss

Auto-generated by YouTube.' -metadata 'purl=https://www.youtube.com/watch?v=Z7cuTnbF-2c' -metadata 'comment=https://www.youtube.com/watch?v=Z7cuTnbF-2c' -metadata artist=Zaz -metadata album=Zaz -movflags +faststart 'file:/home/chris/Downloads/NA/Je veux_Z7cuTnbF-2c.temp.m4a'
[debug] Adding to archive: youtube Z7cuTnbF-2c
```

**Comment by pukkandan** [comment]
I can't check format 141 because I don't have premium. On testing with 140, I don't hear any issues. Can you check whether the issue is only in format 141? If so, double check that it does not happen in browser

**Comment by Chartman123** [comment]
HI @pukkandan 

thank you for your quick reply... I can confirm that it's not happening with format 140, just tried it. It also doesn't happen in the browser, I have already checked that before opening this issue.

**Comment by Chartman123** [comment]
I just tried the download link from the above debug output and couldn't hear the glitch there either...

**Comment by pukkandan** [comment]
From your own debug output? That is weird.

Can you reproduce the issue consistently if you re-download and overwrite? Also, can you check removing the `--embed-metadata`?

**Comment by Chartman123** [comment]
I will try to reproduce it as soon as I have the time for it :) 

The last time I couldn't here the glitch even with format 141. There has been one difference to my last download with the glitch: I now tried it only for a single download whereas the problematic downloads have been a playlist

**Comment by Chartman123** [comment]
I cannot reproduce it anymore at the moment, so I will close this issue for now... thanks for your support!
