### ISSUE TITLE
Using Japanese titles on niconico

### ISSUE THREAD

**Issue by My-MC** [yt-dlp/yt-dlp#4374]
### Checklist

- [X] I'm requesting a site-specific feature
- [X] I've verified that I'm running yt-dlp version **2022.07.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Japan

### Example URLs

https://www.nicovideo.jp/watch/sm39257413

### Provide a description that is worded well enough to be understood

I'm Japanese. So I want to use the Japanese title in niconico. But  I can't use the Japanese title in niconico. 

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.nicovideo.jp/watch/sm39257413']
[debug] Encodings: locale cp932, fs utf-8, pref cp932, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.07.18 [135f05e]
[debug] Python 3.10.4 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg n5.0.1-7-g7389a49fd3-20220716 (setts), ffprobe n5.0.1-7-g7389a49fd3-20220716
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.07.18, Current version: 2022.07.18
yt-dlp is up to date (2022.07.18)
[debug] [niconico] Extracting URL: https://www.nicovideo.jp/watch/sm39257413
[niconico] sm39257413: Downloading webpage
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] sm39257413: Downloading 1 format(s): h264_720p-aac_192kbps-http
[debug] Invoking niconico_dmc downloader on "niconico_dmc:sm39257413/archive_h264_720p/archive_aac_192kbps"
[niconico_dmc] Downloading from DMC
[niconico] sm39257413: Downloading JSON metadata for h264_720p-aac_192kbps-http
[niconico] sm39257413: Acquiring permission for downloading video
[niconico_dmc] Heartbeat with 40 second interval ...
[debug] File locking is not supported. Proceeding without locking
[download] Destination: Kyu-kurarin _ Iyowa feat. KAFU [sm39257413].mp4
[download] 100% of 38.45MiB in 01:43
```

**Comment by pukkandan** [comment]
I don't see any Japanese title on the webpage 
![image](https://user-images.githubusercontent.com/6623388/179433125-c4979dc7-194d-45d7-b043-7732e18b6591.png)

**Comment by xtkoba** [comment]
Use `--add-header 'Accept-Language:ja'`:

```
$ yt-dlp --add-header 'Accept-Language:ja' https://www.nicovideo.jp/watch/sm39257413
[niconico] sm39257413: Downloading webpage
[info] sm39257413: Downloading 1 format(s): h264_720p-aac_192kbps-http
[niconico_dmc] Downloading from DMC
[niconico] sm39257413: Downloading JSON metadata for h264_720p-aac_192kbps-http
[niconico] sm39257413: Acquiring permission for downloading video
[niconico_dmc] Heartbeat with 40 second interval ...
[download] Destination: きゅうくらりん _ いよわ feat.可不 [sm39257413].mp4
[...]
```

**Comment by My-MC** [comment]
Oh, I can use Japanese. But it's hard to understand at first. I want to add the `lang` option

**Comment by pukkandan** [comment]
Whether this works or not depends on the specific site. So a general option won't really work. We could make it an `--extractor-arg`, but something like `--extractor-arg niconico:lang=ja` is no better than just using `--add-header 'Accept-Language:ja'` imho

If you want an easy way to enable/disable this, you can put this in your config file:

    --alias --lang "--add-header Accept-Language:{}"

and use as `--lang ja`
