### ISSUE TITLE
Various ways of generating playlist JSON

### ISSUE THREAD

**Issue by dirkf** [yt-dlp/yt-dlp#4375]
### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.07.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

In https://github.com/ytdl-org/youtube-dl/issues/31092, OP would like to write a JSON file for a playlist, which is not yet a yt-dl feature. Supposing that yt-dl doesn't adopt the processing associated with `--[no-]write-playlist-metafiles`, it could implement playlist JSON output for the case `--flat-playlist --write-info-json` (`--skip-download` implied by `--flat-playlist`).

Looking at this I saw various output differences. 

1. Should the `__*` metadata, which are omitted in the `--write-info-json` output, be shown for `--dump-single-json` (yt-dl is similar, if the values are not null)?
2. Should the metadata with value `null` be shown for `--dump-single-json` (omitted from the yt-dl output)?

----

With yt-dl, `--flat-playlist --dump-single-json` can be used:
```
$ youtube-dl -v --flat-playlist --dump-single-json 'https://www.youtube.com/playlist?list=PLW_omwEM1aic5BpJJUEyteXnpbaMdT3MJ' | jq .
[debug] System config: ['--prefer-ffmpeg']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--flat-playlist', '--dump-single-json', 'https://www.youtube.com/playlist?list=PLW_omwEM1aic5BpJJUEyteXnpbaMdT3MJ']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.5.2 (CPython) - Linux-4.4.0-210-generic-i686-with-Ubuntu-16.04-xenial
[debug] exe versions: avconv 4.3, avprobe 4.3, ffmpeg 4.3, ffprobe 4.3
[debug] Proxy map: {}
{
  "extractor": "youtube:tab",
  "title": "Argofox Music Playlist | Label",
  "entries": [
    {
      "title": "Adventures - A Himitsu | Royalty Free Music - No Copyright Music | Argofox Music",
      "url": "NzvOEKhk1UQ",
      "view_count": null,
      "_type": "url",
      "id": "NzvOEKhk1UQ",
      "description": null,
      "ie_key": "Youtube",
      "uploader": "Royalty Free Music - No Copyright Music",
      "duration": 225
    },
    {
      "title": "Cloud 9 - Valesco | Royalty Free Music - No Copyright Music | Argofox Music",
      "url": "1uvSkDDACeo",
      "view_count": null,
      "_type": "url",
      "id": "1uvSkDDACeo",
      "description": null,
      "ie_key": "Youtube",
      "uploader": "Royalty Free Music - No Copyright Music",
      "duration": 259
    },
    {
      "title": "Explorers - Hinkik | Royalty Free Music - No Copyright Music | SoundCloud Music",
      "url": "Zby0Ug8b9ns",
      "view_count": null,
      "_type": "url",
      "id": "Zby0Ug8b9ns",
      "description": null,
      "ie_key": "Youtube",
      "uploader": "Royalty Free Music - No Copyright Music",
      "duration": 266
    }
  ],
  "webpage_url_basename": "playlist",
  "uploader_url": "https://www.youtube.com/c/RoyaltyFreeMusicNoCopyrightMusic",
  "_type": "playlist",
  "id": "PLW_omwEM1aic5BpJJUEyteXnpbaMdT3MJ",
  "extractor_key": "YoutubeTab",
  "uploader": "Royalty Free Music - No Copyright Music",
  "uploader_id": "UCQsBfyc5eOobgCzeY8bBzFg",
  "webpage_url": "https://www.youtube.com/playlist?list=PLW_omwEM1aic5BpJJUEyteXnpbaMdT3MJ"
}
$
```
With yt-dlp, we can use the same options, with more detailed metadata due to extractor improvements (slightly snipped), but also `null` values:
```shellsession
$ python3.9 -m yt_dlp --flat-playlist --dump-single-json  'https://www.youtube.com/playlist?list=PLW_omwEM1aic5BpJJUEyteXnpbaMdT3MJ' ) | jq .
{
  "uploader": "Royalty Free Music - No Copyright Music",
  "uploader_id": "UCQsBfyc5eOobgCzeY8bBzFg",
  "uploader_url": "https://www.youtube.com/c/RoyaltyFreeMusicNoCopyrightMusic",
  "thumbnails": [
    /* skipped 4 thumbnail entries */
  ],
  "tags": [],
  "view_count": 1968,
  "availability": null,
  "modified_date": "20201114",
  "playlist_count": 3,
  "channel_follower_count": null,
  "channel": "Royalty Free Music - No Copyright Music",
  "channel_id": "UCQsBfyc5eOobgCzeY8bBzFg",
  "channel_url": "https://www.youtube.com/c/RoyaltyFreeMusicNoCopyrightMusic",
  "id": "PLW_omwEM1aic5BpJJUEyteXnpbaMdT3MJ",
  "title": "Argofox Music Playlist | Label",
  "description": "",
  "_type": "playlist",
  "entries": [
    {
      "_type": "url",
      "ie_key": "Youtube",
      "id": "NzvOEKhk1UQ",
      "url": "https://www.youtube.com/watch?v=NzvOEKhk1UQ",
      "title": "Adventures - A Himitsu | Royalty Free Music - No Copyright Music | Argofox Music",
      "description": null,
      "duration": 225,
      "view_count": null,
      "uploader": "Royalty Free Music - No Copyright Music",
      "channel_id": "UCQsBfyc5eOobgCzeY8bBzFg",
      "thumbnails": [
        /* skipped 4 thumbnail entries */
      ],
      "upload_date": null,
      "live_status": null,
      "release_timestamp": null,
      "availability": null,
      "__x_forwarded_for_ip": null
    },
    {
      "_type": "url",
      "ie_key": "Youtube",
      "id": "1uvSkDDACeo",
      "url": "https://www.youtube.com/watch?v=1uvSkDDACeo",
      "title": "Cloud 9 - Valesco | Royalty Free Music - No Copyright Music | Argofox Music",
      "description": null,
      "duration": 259,
      "view_count": null,
      "uploader": "Royalty Free Music - No Copyright Music",
      "channel_id": "UCQsBfyc5eOobgCzeY8bBzFg",
      "thumbnails": [
        /* skipped 4 thumbnail entries */
      ],
      "upload_date": null,
      "live_status": null,
      "release_timestamp": null,
      "availability": null,
      "__x_forwarded_for_ip": null
    },
    {
      "_type": "url",
      "ie_key": "Youtube",
      "id": "Zby0Ug8b9ns",
      "url": "https://www.youtube.com/watch?v=Zby0Ug8b9ns",
      "title": "Explorers - Hinkik | Royalty Free Music - No Copyright Music | SoundCloud Music",
      "description": null,
      "duration": 266,
      "view_count": null,
      "uploader": "Royalty Free Music - No Copyright Music",
      "channel_id": "UCQsBfyc5eOobgCzeY8bBzFg",
      "thumbnails": [
        /* skipped 4 thumbnail entries */
      ],
      "upload_date": null,
      "live_status": null,
      "release_timestamp": null,
      "availability": null,
      "__x_forwarded_for_ip": null
    }
  ],
  "webpage_url": "https://www.youtube.com/playlist?list=PLW_omwEM1aic5BpJJUEyteXnpbaMdT3MJ",
  "original_url": "https://www.youtube.com/playlist?list=PLW_omwEM1aic5BpJJUEyteXnpbaMdT3MJ",
  "webpage_url_basename": "playlist",
  "webpage_url_domain": "youtube.com",
  "extractor": "youtube:tab",
  "extractor_key": "YoutubeTab",
  "requested_entries": [
    1,
    2,
    3
  ],
  "__files_to_move": {},
  "epoch": 1658108140
}
$
```
Using `--flat-playlist --write-info-json`, yt-dlp produces output where yt-dl doesn't (yet):
```shellsession
$ python3.9 -m yt_dlp --flat-playlist --write-info-json --skip-download -o test1 'https://www.youtube.com/playlist?list=PLW_omwEM1aic5BpJJUEyteXnpbaMdT3MJ'; <test1.info.json jq .
[youtube:tab] PLW_omwEM1aic5BpJJUEyteXnpbaMdT3MJ: Downloading webpage
[youtube:tab] PLW_omwEM1aic5BpJJUEyteXnpbaMdT3MJ: Downloading API JSON with unavailable videos
[download] Downloading playlist: Argofox Music Playlist | Label
[info] Writing playlist metadata as JSON to: test1.info.json
[youtube:tab] Playlist Argofox Music Playlist | Label: Downloading 3 videos of 3
[download] Downloading video 1 of 3
[download] Downloading video 2 of 3
[download] Downloading video 3 of 3
[info] Writing updated playlist metadata as JSON to: test1.info.json
[download] Finished downloading playlist: Argofox Music Playlist | Label
{
  "uploader": "Royalty Free Music - No Copyright Music",
  "uploader_id": "UCQsBfyc5eOobgCzeY8bBzFg",
  "uploader_url": "https://www.youtube.com/c/RoyaltyFreeMusicNoCopyrightMusic",
  "thumbnails": [
    /* skipped 4 thumbnail entries */
  ],
  "tags": [],
  "view_count": 1968,
  "modified_date": "20201114",
  "playlist_count": 3,
  "channel": "Royalty Free Music - No Copyright Music",
  "channel_id": "UCQsBfyc5eOobgCzeY8bBzFg",
  "channel_url": "https://www.youtube.com/c/RoyaltyFreeMusicNoCopyrightMusic",
  "id": "PLW_omwEM1aic5BpJJUEyteXnpbaMdT3MJ",
  "title": "Argofox Music Playlist | Label",
  "description": "",
  "_type": "playlist",
  "webpage_url": "https://www.youtube.com/playlist?list=PLW_omwEM1aic5BpJJUEyteXnpbaMdT3MJ",
  "webpage_url_basename": "playlist",
  "webpage_url_domain": "youtube.com",
  "extractor": "youtube:tab",
  "extractor_key": "YoutubeTab",
  "epoch": 1658108868
}
$ 
```
If `--flat-playlist` is omitted, we get playlist JSON without entry data, because the entries are written to their own files.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
# see above
```

**Comment by pukkandan** [comment]
> Should the __* metadata, which are omitted in the --write-info-json output, be shown for --dump-single-json (yt-dl is similar, if the values are not null)?

In general, --dump options are used for introspection and --write for archival. So it makes sense to show the private fields in --dump but not in --write

> Should the metadata with value null be shown for --dump-single-json (omitted from the yt-dl output)?

`None` in infodict is always treated the same as absence of value. So either is fine imho

> In addition, I observed that yt-dlp, the main fork of yt-dl, has implemented something similar but does not produce the same output, since the entries list is not included. 

The entries are written only if `--no-clean-infojson` is passed. There are a few reasons why I made this decision:
1. Including the entries can result in the infojson becoming massive in size (often GBs) - related: https://github.com/yt-dlp/yt-dlp/issues/1399)
2. Unless the user forbids it, the entries are written to their individual infojsons, and is therefore redundant in the main infojson
3. yt-dlp extends `--load-infojson` to load playlist infojson as well. If the loaded json contains `entries`, we load that as well. While this feature is useful in certain circumstances, it can be unexpected if enabled by default since the loaded entries may be out of date with the actual playlist. The easiest way to solve this is to just not write/load entries by default

However, if you want to implement `--write-infojson --flat-playlist` as writing the entries too, go ahead. As long ytdl don't write "json with entries" in the absence of --flat-playlist, I will be easily able to maintain compatibility.

In this case, (1) and (2) are not applicable. And I can workaround (3) by filtering at load-time even if it is not filtered during write. I suspect the code to add this special case will be a bit ugly, but it is not a big deal.

PS: In future, feel free to directly @ me for matters like this rather than splitting the discussion b/w 2 issues
