### ISSUE TITLE
m3u8 that hides video streams inside PNGs

### ISSUE THREAD

**Issue by lockmatrix** [yt-dlp/yt-dlp#4381]
### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.07.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

some m3u8 / website add fake_png_header to ts, [this](https://twitter.com/comex/status/1201795684950626304) explains.

I find some website use this tech, like https://www.yhdmp.cc/
there is a m3u8 example `https://yun.66dm.net/SBDM/LycorisRecoil03.m3u8?dpvt=92119799994611210910010412146119119119`
(video page: https://www.yhdmp.cc/vp/22224-1-2.html)
content like this
```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-ALLOW-CACHE:YES
#EXT-X-TARGETDURATION:15
#EXTINF:6.047722,
https://ali-ec.static.yximgs.com/udata/pkg/ks-merchant/541150223-0d3770cc-734f-4cfc-aa6b-11f98fef4d94-1658033371466.png
#EXTINF:4.504511,
https://ali-ec.static.yximgs.com/udata/pkg/ks-merchant/541150223-b191e769-b239-4154-b97a-8a7fd69d3fdd-1658033371081.png
#EXTINF:6.339678,
https://ali-ec.static.yximgs.com/udata/pkg/ks-merchant/541150223-7ea4719c-75ef-44af-a015-cb3b5d07f3c1-1658033371926.png
```

I know this is not related to supported websites now, 
while it is simple to support this, and can be infrastructure for future websites.

Here is the patch:
* Extractor mark this, like `'protocol': 'm3u8_with_fake_header'`
* force use hlsnative to download. ffmpeg seems cannot just skip png.
* drop bytes before ts header ( b'\x47\x40' ) for each fragment, code add in [here](https://github.com/yt-dlp/yt-dlp/blob/bc83b4b06cd2648276c7f075754ace8be22f889a/yt_dlp/downloader/fragment.py#L520=) likes

```
for fragment in fragments:
	if not interrupt_trigger[0]:
		break
	try:
		download_fragment(fragment, ctx)
		frag_bytes = self._read_fragment(ctx)
		if info_dict.get('m3u8_frag_fake_image_header'):              ## here
			ts_start_pos = frag_bytes.find(b'\x47\x40')           ## here
			frag_bytes = frag_bytes[ts_start_pos:]                ## here
		result = append_fragment(
			decrypt_fragment(fragment, frag_bytes), fragment['frag_index'], ctx)
	except KeyboardInterrupt:
		if info_dict.get('is_live'):
			break
		raise
	if not result:
		return False
```

**Comment by pukkandan** [comment]
Is this for just that one site,or do you have other examples? Do other sites perform similar padding, but with other headers?

**Comment by lockmatrix** [comment]
> Is this for just that one site,or do you have other examples? Do other sites perform similar padding, but with other headers?

I dont have other site exmple now,
if I find some in future, I will add it to this issue

Image header make it can use free image hosting service as video hosting, I cannot imagine other type headers now.

**Comment by lockmatrix** [comment]
I found https://ddrk.me/ used this tech in 2021, [from this article](https://blog.csdn.net/feiyu361/article/details/121196667)
But it seems it do not use this tech anymore today.

**Comment by lockmatrix** [comment]
other related:
* https://forum.videohelp.com/threads/399113-m3u8-has-jpg-files , site offline
* https://stackoverflow.com/questions/71845715/download-m3u8-but-its-a-jpg-file-not-a-ts , unknown site
* https://community.cloudflare.com/t/you-can-bypass-cloudflare-stream-by-converting-m3u8-ts-to-false-jpg-ending/374043

**Comment by lockmatrix** [comment]
another site use this:
https://www.sbdm.net/

**Comment by avary** [comment]
https://m3u8-rd.playm4u.xyz/m3u8/v3/5/60cd72a18e55c2726c489fb5/1683844833/515ca8032dd10fdf4b1f71502f2af280.m3u8
this also uses png to hide video streams
content is like blow :
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:10
#EXT-X-PLAYLIST-TYPE:VOD
#EXTINF:10,
https://cdn01z6.strntt001z6.xyz/stream/v5/51b72a648ebe6f2185e0955708d4ea415b17e7b80f6bfca4d2d38729ea61344c52ef7a0bcf1b41fe5515049f3cb5975a.html
#EXTINF:10,
https://api-rd.apirdntt.cfd/rdv1/5e8dd16b70eac4137a676553/d5927e2fde955cf26f27be41f270805f691605543d9c9385832c550a2f904a4d6412b6281585a83cbeb137c5707633de/9ea9aa2d2adcd3a39ddd1cba80a19dce
#EXTINF:10,
https://api-rd.apirdntt.cfd/rdv1/5e8dd16b70eac4137a676553/7946833d37b5f0d381cd0378314afd4c847c32d63bd2170fc207708719ce291954a8bf835f7d50459334551c3f3cca1b/6b3d10327db647f392d4196cc21e9cc9
#EXTINF:10,
https://api-rd.apirdntt.cfd/rdv1/5e8dd16b70eac4137a676553/3d5934d042663a929e86f79fa5292c1201bacc8d137706d67cb0f246a9317c3bf9272dc708e93a10fc91d90700ea7739/bd3cde62cb5e6f4372ce0a1ab9ff4ece
#EXTINF:10,

**Comment by bashonly** [comment]
@avary that looks like a piracy link

**Comment by lossefanya** [comment]
I wrote some shell script which you can use meanwhile.
```
n=50

# Download ts files
base="https://some.base.url/"
for ((i=0; i<=n; i++))
do
  file="file$i.png"
  url=$base$file
  echo $url
  curl "$url" --output "file$i.png"
done

# Remove first 8 bytes (fake png header)
for ((i=0; i<=n; i++))
do
  dd if=file$i.png of=file$i.ts bs=1 skip=8
done

# Make list file
for ((i=0; i<=n; i++))
do
    echo "file 'file$i.ts'" >> list.txt
done

# Concat using ffmpeg
ffmpeg -f concat -safe 0 -i list.txt -c copy output.mp4
```

**Comment by punisher018** [comment]
this [site](https://www.dizibox.in) uses this method too in DBX Pro Player tab. (Turkey's largest TV series platform) Is there any codes for downloading videos from there?

**Comment by X-Gorn** [comment]
@lockmatrix saw your fork. any example to use it?
