### ISSUE TITLE
[facebook] Certain public URLs die on "ERROR: Did not get any data blocks"

### ISSUE THREAD

**Issue by zx2c4** [yt-dlp/yt-dlp#4382]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.07.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

...

### Provide a description that is worded well enough to be understood

Fetching the *public* URL https://www.facebook.com/... results in errors and the video portion does not get downloaded:

```
$ ./yt-dlp https://www.facebook.com/...
...: Downloading webpage
[facebook] ...: Downloading MPD manifest
[info] ...: Downloading 1 format(s): ...
[download] Destination: ....mp4
[download]   0.5% of ...GiB at   ...MiB/s ETA 01:22[download] Got server HTTP error: Downloaded ... bytes, expected ... bytes. Retrying (attempt 1 of 10) ...


ERROR: Did not get any data blocks

[download] Destination: ....m4a
[download] 100% of ...MiB in 00:01
```

It starts downloading the video, then fails part way, and then downloads the audio just fine. If I then try to run it again, using the partial file, I get:

```
$ ./yt-dlp https://www.facebook.com/...
[facebook] ...: Downloading webpage
[facebook] ...: Downloading MPD manifest
[info] ...: Downloading 1 format(s): ...
[download] Resuming download at byte ...
ERROR: unable to download video data: HTTP Error 403: Forbidden
```

Any idea how I can download this video?

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.07.18 [135f05e] (zip)
[debug] Python 3.9.13 (CPython 64bit) - Linux-5.19.0-rc7+-x86_64-11th_Gen_Intel-R-_Core-TM-_i7-11850H_@_2.50GHz-with-glibc2.35 (glibc 2.35)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.4.2 (fdk,setts), ffprobe 4.4.2, rtmpdump 2.4
[debug] Optional libraries: Crypto-3.14.1, certifi-3021.03.16, mutagen-1.45.1, sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.07.18, Current version: 2022.07.18
yt-dlp is up to date (2022.07.18)
```

**Comment by zx2c4** [comment]
@pukkandan Assuming this is a serverside issue, yt-dlp's http.py should just skip/fill-in this block and move onto the next one. Presumably this is what the web browser does when encountering similar things.

**Comment by pukkandan** [comment]
The verbose log should demonstrate the issue!

**Comment by zx2c4** [comment]
Looks like they fixed the issue serverside, so I can't repro any more. Shucks. Sorry!

**Comment by GabMgt** [comment]
I have the same issue with this command (probably related):

```shell
$ yt-dlp 'https://www.youtube.com/watch?v=QbTrTaFylOs'
WARNING: Assuming --restrict-filenames since file system encoding cannot encode all characters. Set the LC_ALL environment variable to fix this.
[youtube] QbTrTaFylOs: Downloading webpage
[youtube] QbTrTaFylOs: Downloading android player API JSON
[info] QbTrTaFylOs: Downloading 1 format(s): 22
[download] Destination: ITER_est_il_obsolete_-_L_avenir_de_la_fusion_nucleaire_-_Monsieur_Bidouille-[QbTrTaFylOs].mp4
[download]   0.2% of 424.68MiB at  315.84KiB/s ETA 22:54[download] Got server HTTP error: Downloaded 755404 bytes, expected 445311505 bytes. Retrying (attempt 1 of 10) ...


ERROR: Did not get any data blocks
```
