### ISSUE TITLE
Skip a playlist while downloading entire channel

### ISSUE THREAD

**Issue by vacekj** [yt-dlp/yt-dlp#4383]
### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.07.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I am trying to archive all of my playlists, including private ones. I want to, however, skip Liked videos. I got this working using the following command: 
```bash
yt-dlp -o "%(playlist)s/%(title)s.%(ext)s" "https://www.youtube.com/channel/UCTN922lH_bSva0xNHfFrhcg/playlists" --cookies-from-browser brave --match-filters 'playlist_id!=LLTN922lH_bSva0xNHfFrhcg' --download-archive downloaded.txt
```

but the way it skips the videos is downloading the metadata of each, and then rejecting it one by one. This takes a long time (1500 liked videos) and is not needed, since I just need to download every playlist minus liked videos.
Is there a better way of doing this via the CLI? I'm thinking something like `--skip-playlist xyz`, or do I need to use the Python API.

Thanks.

**Comment by dirkf** [comment]
Somewhat related: https://github.com/ytdl-org/youtube-dl/issues/31096.

**Comment by unityconstruct** [comment]
> Somewhat related: https://github.com/ytdl-org/youtube-dl/issues/31096.

muchly related in essense, 
_though I suspect ( without any knowledge of codebase ) addressing all the permutations requires architectural restructuring... this makes me think of how a [normalized studio patchbay] works & its placement in audio signal paths._

> spew start

## Thinking out loud here... [Patchbay Metaphor]
If url list management is occurring within in each extractor machine, it might prove useful to create some interfaces extractors can optionally support:
- EVERYTHING goes to the patchbay, then there is some autotastic routing that occurs based on what is plugged in & where. 
- so without it, sound sources ( keyboards, drum machines, PCs ) reside on the periphery 
  - making routing painful & requiring long cables between devices to bring it all together to one unified output
- and with it, sound sources are drawn inward toward a central location first
  - and routing is done with identical [patch cables] which are short & easily moved about.

## So...
If url list management is occurring within in each extractor machine, it might prove useful to create some interfaces extractors can optionally support:
- [URL List Management] duties would reside in a [Utility Class] 
  - and functionality exposed via interfaces
  - (not sure how this relates to python, but interface specifies methods & I/O, but not statements therein )
- implementing an interface for an extractor would entail calling into this [Utility Class] with required parameters/arguments & consuming anything returned.
  - extractor MUST have supporting methods with correct I/O
- configuration template would flag interface support
  - so if a CLI option is called that an extractor hasn't implemented
    -  the framework can preemptively throw an exception end user without actually have the extractor BORK
- so a given extractor could implement one or more interfaces:
  - IFilterLiked
  - IOutputURLList
  - IURLListPreExtractorManagement
  - IURLListPostExtractorManagement


### Patchbay Metaphor: Craptastic Audio Patchbay routing based on what is jacked in
`
-o-->|    o
-o<--|    o

-o-->|-->o-
-o<--|    o

-o----->o-
-o<-----o-
`
figured I'd at least pose an abstract solution to the issue I raised... 

> spew end

**Comment by pukkandan** [comment]
@vasekj Your requirement is only that --match-filter playlist_id ... needs to work without iterating through the playlist, correct? If so, `--break-on-reject --break-per-playlist` should adress it. You may also want to add --lazy-playlist, but make sure to read it's caveats in the docs

@unityconstruct Your usecase, while somewhat related, seem to be fundamentally different. Let us continue its discussion on the ytdl thread

**Comment by pukkandan** [comment]
Closing since neither OP is responding
