### ISSUE TITLE
[TwitCasting] Failed to get m3u8 playlist

### ISSUE THREAD

**Issue by iuriuriur61** [yt-dlp/yt-dlp#4385]
### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.07.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I downloaded TwitCasting and got an error.
How can I download this one?

 [TwitCasting] Failed to get m3u8 playlist; please report this issue on https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the Confirm you are on the latest version using yt-dlp -U

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by u-spec-png** [comment]
Can you post a full output of `yt-dlp -vU`.
