### ISSUE TITLE
Separate danmaku from subtitles

### ISSUE THREAD

**Issue by lockmatrix** [yt-dlp/yt-dlp#4387]
### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.07.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

reason:
* danmaku is not subtitles, and do not have lang-attr, danmaku do not distinguish users who speak different languages, danmaku data may have all languages.
* danmaku often has too many to show as subtitles, it needs other display mode.
* danmaku data do not follow subtitle schema, which is hard to convert to srt or else.
* danmaku is often changed or is emptied periodically by site, do not like subtitles.
* treat danmaku as a subtitle make current subtitle download confusing, Now I need to add `--sub-langs en*,zh*` for all site has danmaku (like bilibili) to skip danmaku but download subtitles, I think the default behavier should be no-danmaku when download subtitles, and use `--download-danmaku` to explicitly specify.

**Comment by Lesmiscore** [comment]
> danmaku is not subtitles, and do not have lang-attr, danmaku do not distinguish users who speak different languages, danmaku data may have all languages.

The reason that Danmaku (e.g. so-called comments from NicoNico) is treated as subtitles is that, it has timeline.
We do understand that there can be any language in it, like Chinese and Japanese mixed in a video.

The same goes for live chat from YouTube. It has timeline, too. Comments on videos doesn't.

> danmaku often has too many to show as subtitles

Yes :)

> it needs other display mode.

yt-dlp itself doesn't render. It's the responsible for the player to render.

> danmaku data do not follow subtitle schema, which is hard to convert to srt or else.

Here's a go: https://github.com/m13253/danmaku2ass
Yes. It doesn't follow any schema so you'll have to convert by yourself.

> danmaku is often changed or is emptied periodically by site, do not like subtitles.

Any example that yt-dlp supports?
On NicoNico, comments will expire and replaced by new ones, but did you mean this?

> treat danmaku as a subtitle make current subtitle download confusing, Now I need to add `--sub-langs en*,zh*` for all site has danmaku (like bilibili) to skip danmaku but download subtitles, (snip)

What Bilibili provides is internally treated as "comments" (but it has timeline too right??? confusing) so it doesn't apply for now.
The possibly only case, NicoNico, declares the language as `comments` (so the "comments" language). So unless you're specifying Corsican (`--sub-langs co*`), it doesn't download.

**Comment by lockmatrix** [comment]
>> danmaku is often changed or is emptied periodically by site, do not like subtitles.

>Any example that yt-dlp supports?
>On NicoNico, comments will expire and replaced by new ones, but did you mean this?

Bilibili, comment update logic is complex, and I do not know it accurately.


> What Bilibili provides is internally treated as "comments" (but it has timeline too right??? confusing) so it doesn't apply for now.
The possibly only case, NicoNico, declares the language as comments (so the "comments" language). So unless you're specifying Corsican (--sub-langs co*), it doesn't download.

I add real subtitle support for bilibili in https://github.com/yt-dlp/yt-dlp/pull/4221 
Bilibili now have subtitles and danmaku.

Maybe I should change it to comments?
I think it may still be downloaded when use `--write-subs`

**Comment by pukkandan** [comment]
> Maybe I should change it to comments?

No

> I think it may still be downloaded when use --write-subs and there is no real subtitles

Doesn't matter. User should control this with --sub-langs as they need

**Comment by pukkandan** [comment]
We won't add new options for danmaku, live chat etc. Also, changing them from being subtitle breaks backward compat.

The most that can be done regarding your request is to extend `--compat-option no-live-chat` to exclude danmaku as well

**Comment by lockmatrix** [comment]
get it
