### ISSUE TITLE
Crunchyroll ERROR: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by Burve** [yt-dlp/yt-dlp#4399]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.07.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Crunchyroll is being not consistent and buggy, that leads to some rare errors that need to be addressed somehow.
Currently, with example URL "https://beta.crunchyroll.com/watch/GPWUK48VJ/the-hand-that-rocks-the-cradle" issue is, that Crunchyroll forgot to provide a thumbnail image. 

As a result, thumbnail processing code in crunchyroll.py on line 825 is not happy
```
        for thumbnails_data in traverse_obj(episode_response, ('images', 'thumbnail')):
            for thumbnail_data in thumbnails_data:
                thumbnails.append({
                    'url': thumbnail_data.get('source'),
                    'width': thumbnail_data.get('width'),
                    'height': thumbnail_data.get('height'),
                })
```
I tried to bypass the exception with a simple try catch
```
        try:
        for thumbnails_data in traverse_obj(episode_response, ('images', 'thumbnail')):
            for thumbnail_data in thumbnails_data:
                thumbnails.append({
                    'url': thumbnail_data.get('source'),
                    'width': thumbnail_data.get('width'),
                    'height': thumbnail_data.get('height'),
                })
        except TypeError:
            thumbnails.append({
                'url': "none",
                'width': 0,
                'height': 0,
            })
```
That technically worked (in console), but returned JSON from yt-dlp got messed up and not usable at all :(

I am not 100% sure where exactly error happens, but I feel it is inside `traverse_obj` somewhere and can be related to the same 'NoneType' errors in other cases.

Any ideas for the proper fix?

Ideally, thumbnail needs to come as empty or "none" if it is missing or not processable.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-u', 'PRIVATE', '-p', 'PRIVATE', '-F', 'https://beta.crunchyroll.com/watch/GPWUK48VJ/the-hand-that-rocks-the-cradle', '-vU']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.07.18 [135f05e]
[debug] Python 3.10.1 (CPython 64bit) - Windows-10-10.0.22000-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg n4.4.1-1-g0204d4fd91-20211030 (setts), ffprobe n4.4.1-1-g0204d4fd91-20211030
[debug] Optional libraries: Cryptodome-3.11.0, brotli-1.0.9, certifi-2021.10.08, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.0
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.07.18, Current version: 2022.07.18
yt-dlp is up to date (2022.07.18)
[crunchyroll:beta] Getting session id
[crunchyroll:beta] Logging in
[debug] [crunchyroll:beta] Extracting URL: https://beta.crunchyroll.com/watch/GPWUK48VJ/the-hand-that-rocks-the-cradle
[crunchyroll:beta] Retrieving main page
[crunchyroll:beta] Authenticating with cookie
[crunchyroll:beta] Retrieving signed policy
[crunchyroll:beta] the-hand-that-rocks-the-cradle: Retrieving episode metadata
[crunchyroll:beta] the-hand-that-rocks-the-cradle: Retrieving stream info
ERROR: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "C:\Users\AlexI\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 1431, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\AlexI\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 1506, in __extract_info
    ie_result = ie.extract(url)
  File "C:\Users\AlexI\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\extractor\common.py", line 644, in extract
    ie_result = self._real_extract(url)
  File "C:\Users\AlexI\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\extractor\crunchyroll.py", line 825, in _real_extract
    for thumbnails_data in traverse_obj(episode_response, ('images', 'thumbnail')):
TypeError: 'NoneType' object is not iterable
```

**Comment by pukkandan** [comment]
Try:
```diff
- for thumbnails_data in traverse_obj(episode_response, ('images', 'thumbnail')):
+ for thumbnails_data in traverse_obj(episode_response, ('images', 'thumbnail')) or []:
```
or even better:
```diff
-        for thumbnails_data in traverse_obj(episode_response, ('images', 'thumbnail')):
-            for thumbnail_data in thumbnails_data:
-                thumbnails.append({
+        for thumbnails_data in traverse_obj(episode_response, ('images', 'thumbnail', ...)) or []:
+            thumbnails.append({
```

If it works, pls open a PR
