### ISSUE TITLE
vgtv.no moving to new domain: tv.vg.no

### ISSUE THREAD

**Issue by solbu** [yt-dlp/yt-dlp#4400]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.07.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Norway

### Provide a description that is worded well enough to be understood

The video site vgtv.no is moving to tv.vg.no, which is not recognized by the program.

The links below are the same video. (Edit: And they work in a browser.)
This link works: https://www.vgtv.no/video/241779/politiets-ekstremkjoering
This does Not work: https://tv.vg.no/video/241779/politiets-ekstremkjoering

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
First: I am running a packaged version (I am the packager btw), I am therefore _unable_ to use the -U switch. But I _am_ running the latest version.

$ yt-dlp --version
2022.07.18

$ yt-dlp -v https://tv.vg.no/video/241779/politiets-ekstremkjoering
[debug] Command-line config: ['-v', 'https://tv.vg.no/video/241779/politiets-ekstremkjoering']
[debug] User config "/home/solbu/.config/yt-dlp/config": ['--restrict-filenames', '--compat-options', 'filename']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out UTF-8, error UTF-8, screen UTF-8
[debug] yt-dlp version 2022.07.18 [135f05e] (zip)
[debug] Compatibility options: filename
[debug] Python 3.7.10 (CPython 64bit) - Linux-5.10.46-desktop-1.mga7-x86_64-with-mageia-7-Official (glibc 2.2.5)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.1.6, ffprobe 4.1.6
[debug] Optional libraries: sqlite3-2.6.0
[debug] Proxy map: {}
[debug] [generic] Extracting URL: https://tv.vg.no/video/241779/politiets-ekstremkjoering
[generic] politiets-ekstremkjoering: Downloading webpage
WARNING: [generic] Falling back on generic information extractor.
[generic] politiets-ekstremkjoering: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://tv.vg.no/video/241779/politiets-ekstremkjoering
Traceback (most recent call last):
  File "/usr/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1431, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1506, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/bin/yt-dlp/yt_dlp/extractor/common.py", line 644, in extract
    ie_result = self._real_extract(url)
  File "/usr/bin/yt-dlp/yt_dlp/extractor/generic.py", line 4108, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://tv.vg.no/video/241779/politiets-ekstremkjoering
```

**Comment by sqrtNOT** [comment]
It seems like nothing has changed except for the url so should be an easy fix.
