### ISSUE TITLE
add qutebrowser support to --cookies-from-browser

### ISSUE THREAD

**Issue by rivke41levp656** [yt-dlp/yt-dlp#4402]
### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.07.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

I would like for `--cookies-from-browser` to support qutebrowser. It is a chromium fork with cookies (as far as I can tell) located in `~/.local/share/qutebrowser/webengine/Cookies`

**Comment by pukkandan** [comment]
See #2903

**Comment by MrRawes** [comment]
you can use `--cookies-from-browser chromium:~/.local/share/qutebrowser`
