### ISSUE TITLE
Add support for the Rutube.ru/live video stream links

### ISSUE THREAD

**Issue by VFomich** [yt-dlp/yt-dlp#4418]
### Checklist

- [X] I'm requesting a site-specific feature
- [X] I've verified that I'm running yt-dlp version **2022.07.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Russia

### Example URLs

https://rutube.ru/live/video/1da5d92af8c55b16241f1eb12a27f00c/ 
https://rutube.ru/live/video/406973c72e9d0449feef05ef7811ad01/

### Provide a description that is worded well enough to be understood

I would like to be able to watch rutube.ru/live streams in the yt-dlp based external player, but judging by the "Unsupported URL" error that type of links are unsupported. It is possible to extract the link to the corresponding .m3u8 file via browser's tools and open it, but since those links change over time, it is not too convenient to use those.

Please add support for that type of links, since the corresponding .m3u8 links are available I suspect it shouldn't be too difficult to implement.

Example URL: https://rutube.ru/live/video/1da5d92af8c55b16241f1eb12a27f00c/ is playable in the Firefox browser, no account is needed to open it, also there doesn't seem to be any sort of a geoblock.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://rutube.ru/live/video/1da5d92af8c55b16241f1eb12a27f00c/']
[debug] Encodings: locale cp1251, fs utf-8, pref cp1251, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.07.18 [135f05e] (win32_exe)
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: avconv -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: avprobe -bsfs
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.07.18, Current version: 2022.07.18
yt-dlp is up to date (2022.07.18)
[debug] [generic] Extracting URL: https://rutube.ru/live/video/1da5d92af8c55b16241f1eb12a27f00c/
[generic] 1da5d92af8c55b16241f1eb12a27f00c: Downloading webpage
WARNING: [generic] Falling back on generic information extractor.
[generic] 1da5d92af8c55b16241f1eb12a27f00c: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://rutube.ru/live/video/1da5d92af8c55b16241f1eb12a27f00c/
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1431, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1506, in __extract_info
  File "yt_dlp\extractor\common.py", line 644, in extract
  File "yt_dlp\extractor\generic.py", line 4108, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://rutube.ru/live/video/1da5d92af8c55b16241f1eb12a27f00c/
```

**Comment by coletdjnz** [comment]
Should be fairly straightforward to integrate into the existing RuTube extractor.

Live stream url is under `live_streams` in the API options request. Should be able to edit `RutubeBaseIE._extract_formats` to extract live stream support.

\+ adjust VALID_URL for RutubeIE

**Comment by vstavrinov** [comment]
@coletdjnz :

> Live stream url is under `live_streams` in the API options request. Should be able to edit `RutubeBaseIE._extract_formats` to extract live stream support.

This url returns 404.   The url  being working is generated by javascript and protected by token.

**Comment by zaeboba** [comment]
джва года прошло, а так и не реализовали 🥲
