### ISSUE TITLE
How to download TikTok video WITH watermark?

### ISSUE THREAD

**Issue by ahm750** [yt-dlp/yt-dlp#4424]
### Checklist

- [X] I'm requesting a site-specific feature
- [X] I've verified that I'm running yt-dlp version **2022.07.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Example URLs

https://www.tiktok.com/@andcarli/video/7109616178955422982?is_copy_url=1&is_from_webapp=v1

### Provide a description that is worded well enough to be understood

Hi,

When I download videos from TikTok, the watermark is not present. Is there an option to download the videos with TikTok's watermark on them?

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
N/A
```

**Comment by pukkandan** [comment]
The verbose log is mandatory for a reason! Show output of `yt-dlp -vF "URL"`

**Comment by gamer191** [comment]
`yt-dlp "URL" -f download_addr-2`

(I hope Pukkandan doesn't mind me answering this issue, even though OP hasn't attached a verbose log)

**Comment by MinePlayersPE** [comment]
re [reddit](https://www.reddit.com/r/youtubedl/comments/q46wkx/comment/hg0pe50/?utm_source=share&utm_medium=web2x&context=3):
> Either `-f best[format_note*=watermarked]` or `-f best[format_id*=download_addr]` should work

**Comment by ahm750** [comment]
> The verbose log is mandatory for a reason! Show output of `yt-dlp -vF "URL"`

Why would I provide the verbose when it’s not required? Others clearly answered my question without seeing the verbose. Always closing issues for things that aren’t required.
