### ISSUE TITLE
Add support for Caracoltv.com

### ISSUE THREAD

**Issue by denaunistic** [yt-dlp/yt-dlp#4425]
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.07.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Colombia

### Example URLs

https://www.caracoltv.com/se-dice-de-mi/pedro-rendon-fue-contagiado-con-una-enfermedad-de-transmision-sexual-pr30
https://www.caracoltv.com/se-dice-de-mi/asi-fue-como-jairo-varela-contacto-a-mauro-castillo-para-ser-parte-del-grupo-niche-pr30
https://www.caracoltv.com/se-dice-de-mi/deje-la-actuacion-y-dediquese-a-cantar-asi-fue-como-fernando-allende-se-apropio-de-los-escenarios-pr30

### Provide a description that is worded well enough to be understood

yt-dlp can't list the formats available and neither download any type of video or audio stream from the website.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vF', 'https://www.caracoltv.com/se-dice-de-mi/asi-fue-como-jairo-varela-contacto-a-mauro-castillo-para-ser-parte-del-grupo-niche-pr30']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.07.18 [135f05e] (win32_exe)
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 2022-07-14-git-882aac99d2-essentials_build-www.gyan.dev (setts), ffprobe 2022-07-14-git-882aac99d2-essentials_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] [generic] Extracting URL: https://www.caracoltv.com/se-dice-de-mi/asi-fue-como-jairo-varela-contacto-a-mauro-castillo-para-ser-parte-del-grupo-niche-pr30
[generic] asi-fue-como-jairo-varela-contacto-a-mauro-castillo-para-ser-parte-del-grupo-niche-pr30: Downloading webpage
WARNING: [generic] Falling back on generic information extractor.
[generic] asi-fue-como-jairo-varela-contacto-a-mauro-castillo-para-ser-parte-del-grupo-niche-pr30: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://www.caracoltv.com/se-dice-de-mi/asi-fue-como-jairo-varela-contacto-a-mauro-castillo-para-ser-parte-del-grupo-niche-pr30
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1431, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1506, in __extract_info
  File "yt_dlp\extractor\common.py", line 644, in extract
  File "yt_dlp\extractor\generic.py", line 4108, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.caracoltv.com/se-dice-de-mi/asi-fue-como-jairo-varela-contacto-a-mauro-castillo-para-ser-parte-del-grupo-niche-pr30
```

**Comment by HobbyistDev** [comment]
Geo-block
![geo_block](https://user-images.githubusercontent.com/105957301/180672482-e5b78565-e05e-4fd7-a065-80b632f48742.JPG)

Translation from google translate:
> Due to your location you cannot see the content, but we invite you to stay connected with the best information at Caracoltv.com.

**Comment by HobbyistDev** [comment]
To Dev:
There's an attribute that possibly define the video location. Here's what i mean:
```data-mediastream='[{"playerId":"f8dfd039d955c4181a9ff8b2a0eca362a","sourceUrl":"https://mdstrm.com/embed/","videoId":"62c0dab657e59e082e39a803" }]```
Maybe we can get the video in `<sourceUrl>/<videoId>`. In this i got the same notice ( about the geo-block), so consider this untested
