### ISSUE TITLE
YT-DLP GIVING A ERROR

### ISSUE THREAD

**Issue by guiworldtv** [yt-dlp/yt-dlp#4428]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.07.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

I'm trying download a video no GloboPlay - STREAM BRAZILIAN
and the site say only its possible for subscribers, i'm a subscriber, how can i use my password and username to give permitions for the yt-dlp download the video?
thanks

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
touch ./GLOBOPLAY.m3u8
  sudo cat >./GLOBOPLAY.m3u8 <<EOL
  #EXTM3U
  #EXT-X-VERSION:3
  #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5400000
  $(youtube-dl -g https://globoplay.globo.com/v/10764248/?s=0s/)
  EOL
  shell: /usr/bin/bash -e {0}
ERROR: Globo returned error: Video is for subscribers only. Authorization required.
```

**Comment by pukkandan** [comment]
Use --cookies-from-browser or --cookies. If that doesnt work, provide verbose log like the template asked you to

**Comment by gamer191** [comment]
or use `--username USERNAME` (it will ask you interactively for the password)

**Comment by guiworldtv** [comment]
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-g', '-u', 'PRIVATE', '-p', 'PRIVATE', '--verbose', 'https://globoplay.globo.com/v/10764248/?s=0s/']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.8.10 (CPython) - Linux-5.15.0-1014-azure-x86_64-with-glibc2.29
[debug] exe versions: phantomjs 2.1.1
[debug] Proxy map: {}
ERROR: Unable to download JSON metadata: HTTP Error 406: Not Acceptable (caused by <HTTPError 406: 'Not Acceptable'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 634, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2288, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)

**Comment by pukkandan** [comment]
That is not even yt-dlp
