### ISSUE TITLE
Use yt-dlp to download the part of the video

### ISSUE THREAD

**Issue by aizawaaiza** [yt-dlp/yt-dlp#4430]
### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [ ] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.07.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [ ] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [ ] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I have been trying to write the code to download the part of the video, but it ends up download the whole video. I don't know what I did wrong. Please, if you have time, help me to check my code.

[code]yt-dlp -F URL [code]
[code]yt-dlp -f 303+140 URL --download-sections * 3:30:00-3:33:00[code]

And that's it, the downloaded file is the whole video.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
# SHOW VERBOSE LOG

**Comment by aizawaaiza** [comment]
You mean this? I am new to yt-dlp, if I misunderstand, just tell me.
![圖片](https://user-images.githubusercontent.com/109920216/180711148-9ca677ef-5bf5-4763-8138-451aeeae14ed.png)

**Comment by pukkandan** [comment]
![image](https://user-images.githubusercontent.com/6623388/180739868-c3cddf18-be40-4503-8d1c-1e0fb543c472.png)

**Comment by aizawaaiza** [comment]
How about this? Do I still do it wrong?

D:\trans video\youtube_dlp>yt-dlp -vU yt-dlp -f https://youtu.be/QoCs2Bv_mWo --download-sections *00:25:00-00:35:00
[debug] Command-line config: ['-vU', 'yt-dlp', '-f', 'https://youtu.be/QoCs2Bv_mWo', '--download-sections', '*00:25:00-00:35:00']
[debug] Encodings: locale cp950, fs utf-8, pref cp950, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.07.18 [135f05e] (win32_exe)
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: avprobe -bsfs
[debug] exe versions: ffmpeg 5.0.1-essentials_build-www.gyan.dev (setts)
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.07.18, Current version: 2022.07.18
yt-dlp is up to date (2022.07.18)
[debug] [generic] Extracting URL: yt-dlp
ERROR: [generic] 'yt-dlp' is not a valid URL. Set --default-search "ytsearch" (or run  yt-dlp "ytsearch:yt-dlp" ) to search YouTube
  File "yt_dlp\extractor\common.py", line 644, in extract
  File "yt_dlp\extractor\generic.py", line 2790, in _real_extract

**Comment by pukkandan** [comment]
yt-dlp -vU youtu.be/QoCs2Bv_mWo --download-sections *00:25:00-00:35:00

**Comment by aizawaaiza** [comment]
D:\trans video\youtube_dlp>yt-dlp -vU "youtu.be/QoCs2Bv_mWo" --download-sections "*00:25:00-00:35:00"
[debug] Command-line config: ['-vU', 'youtu.be/QoCs2Bv_mWo', '--download-sections', '*00:25:00-00:35:00']
[debug] Encodings: locale cp950, fs utf-8, pref cp950, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.07.18 [135f05e] (win32_exe)
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: avprobe -bsfs
[debug] exe versions: ffmpeg 5.0.1-essentials_build-www.gyan.dev (setts)
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.07.18, Current version: 2022.07.18
yt-dlp is up to date (2022.07.18)
[debug] [generic] Extracting URL: youtu.be/QoCs2Bv_mWo
WARNING: [generic] The url doesn't specify the protocol, trying with http
[debug] [youtube] Extracting URL: http://youtu.be/QoCs2Bv_mWo
[youtube] QoCs2Bv_mWo: Downloading webpage
[youtube] QoCs2Bv_mWo: Downloading android player API JSON
[debug] Loading youtube-nsig.afeb58ff from cache
[debug] [youtube] Decrypted nsig OAZbQlp_Tnk9-Ew => istMO44xqxZcZQ
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] QoCs2Bv_mWo: Downloading 1 format(s): 303+251
[info] QoCs2Bv_mWo: Downloading 1 time ranges: 1500-2100
[debug] Invoking ffmpeg downloader on "https://rr5---sn-ipoxu-un5el.googlevideo.com/videoplayback?expire=1658777824&ei=gJzeYt64I8OL1d8P55-G6As&ip=114.45.19.24&id=o-AFs0oyDHmfkO0Q_PpSkkBm0VEYnfs9iShG-1ZD9UMgoT&itag=303&source=youtube&requiressl=yes&mh=nS&mm=31%2C29&mn=sn-ipoxu-un5el%2Csn-un57sn76&ms=au%2Crdu&mv=m&mvi=5&pl=20&initcwndbps=623750&vprv=1&mime=video%2Fwebm&gir=yes&clen=3765944158&dur=11127.432&lmt=1647767435696164&mt=1658755745&fvip=6&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=5432432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRgIhAJR8bUk8GyvB579U-2_tc9s-JFpI5y3HKyvHDzduNLExAiEAzlJW4ymrLIAWcCsG34eAws8LseZzlMBIfb4ZK8uvTkI%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgTZc5zkX867KSs2mTjAsCZgtYlSHOnaoDzQ35-JvHPQkCIQD-ysxcHA8CwWH73WoztJ1NVZt3Fn5gB5KZtEONenZVSg%3D%3D", "https://rr5---sn-ipoxu-un5el.googlevideo.com/videoplayback?expire=1658777824&ei=gJzeYt64I8OL1d8P55-G6As&ip=114.45.19.24&id=o-AFs0oyDHmfkO0Q_PpSkkBm0VEYnfs9iShG-1ZD9UMgoT&itag=251&source=youtube&requiressl=yes&mh=nS&mm=31%2C29&mn=sn-ipoxu-un5el%2Csn-un57sn76&ms=au%2Crdu&mv=m&mvi=5&pl=20&initcwndbps=623750&vprv=1&mime=audio%2Fwebm&gir=yes&clen=194848544&dur=11127.501&lmt=1647762055669024&mt=1658755745&fvip=6&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=5431432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRAIgNuoIC2kf8u3fgF1bAYONDrw2OnV-LQ7buTsYIk9_thYCIFckP3hJNqhwQjiaG68uhj-Qzmroex40wB02HZWkODnu&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgTZc5zkX867KSs2mTjAsCZgtYlSHOnaoDzQ35-JvHPQkCIQD-ysxcHA8CwWH73WoztJ1NVZt3Fn5gB5KZtEONenZVSg%3D%3D"
[download] Destination: MSPaint but in a game (Passpartout - The Starving Artist)【NIJISANJI EN _ Shu Yamino】 [QoCs2Bv_mWo].webm
[debug] ffmpeg command line: ffmpeg -y -loglevel verbose -headers "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.106 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-us,en;q=0.5
Sec-Fetch-Mode: navigate
" -ss 1500.0 -t 600.0 -i "https://rr5---sn-ipoxu-un5el.googlevideo.com/videoplayback?expire=1658777824&ei=gJzeYt64I8OL1d8P55-G6As&ip=114.45.19.24&id=o-AFs0oyDHmfkO0Q_PpSkkBm0VEYnfs9iShG-1ZD9UMgoT&itag=303&source=youtube&requiressl=yes&mh=nS&mm=31%2C29&mn=sn-ipoxu-un5el%2Csn-un57sn76&ms=au%2Crdu&mv=m&mvi=5&pl=20&initcwndbps=623750&vprv=1&mime=video%2Fwebm&gir=yes&clen=3765944158&dur=11127.432&lmt=1647767435696164&mt=1658755745&fvip=6&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=5432432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRgIhAJR8bUk8GyvB579U-2_tc9s-JFpI5y3HKyvHDzduNLExAiEAzlJW4ymrLIAWcCsG34eAws8LseZzlMBIfb4ZK8uvTkI%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgTZc5zkX867KSs2mTjAsCZgtYlSHOnaoDzQ35-JvHPQkCIQD-ysxcHA8CwWH73WoztJ1NVZt3Fn5gB5KZtEONenZVSg%3D%3D" -headers "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.106 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-us,en;q=0.5
Sec-Fetch-Mode: navigate
" -ss 1500.0 -t 600.0 -i "https://rr5---sn-ipoxu-un5el.googlevideo.com/videoplayback?expire=1658777824&ei=gJzeYt64I8OL1d8P55-G6As&ip=114.45.19.24&id=o-AFs0oyDHmfkO0Q_PpSkkBm0VEYnfs9iShG-1ZD9UMgoT&itag=251&source=youtube&requiressl=yes&mh=nS&mm=31%2C29&mn=sn-ipoxu-un5el%2Csn-un57sn76&ms=au%2Crdu&mv=m&mvi=5&pl=20&initcwndbps=623750&vprv=1&mime=audio%2Fwebm&gir=yes&clen=194848544&dur=11127.501&lmt=1647762055669024&mt=1658755745&fvip=6&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=5431432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRAIgNuoIC2kf8u3fgF1bAYONDrw2OnV-LQ7buTsYIk9_thYCIFckP3hJNqhwQjiaG68uhj-Qzmroex40wB02HZWkODnu&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgTZc5zkX867KSs2mTjAsCZgtYlSHOnaoDzQ35-JvHPQkCIQD-ysxcHA8CwWH73WoztJ1NVZt3Fn5gB5KZtEONenZVSg%3D%3D" -c copy -map "0:0" -map "1:0" -f webm "file:MSPaint but in a game (Passpartout - The Starving Artist)【NIJISANJI EN _ Shu Yamino】 [QoCs2Bv_mWo].webm.part"
ffmpeg version 5.0.1-essentials_build-www.gyan.dev Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 11.2.0 (Rev7, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-lzma --enable-zlib --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-sdl2 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-libass --enable-libfreetype --enable-libfribidi --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-libgme --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libtheora --enable-libvo-amrwbenc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-librubberband
  libavutil      57. 17.100 / 57. 17.100
  libavcodec     59. 18.100 / 59. 18.100
  libavformat    59. 16.100 / 59. 16.100
  libavdevice    59.  4.100 / 59.  4.100
  libavfilter     8. 24.100 /  8. 24.100
  libswscale      6.  4.100 /  6.  4.100
  libswresample   4.  3.100 /  4.  3.100
  libpostproc    56.  3.100 / 56.  3.100
[tcp @ 000001a6e4181f00] Starting connection attempt to 203.66.169.80 port 443
[tcp @ 000001a6e4181f00] Successfully connected to 203.66.169.80 port 443
[tcp @ 000001a6e430c100] Starting connection attempt to 203.66.169.80 port 443
[tcp @ 000001a6e430c100] Successfully connected to 203.66.169.80 port 443
Input #0, matroska,webm, from 'https://rr5---sn-ipoxu-un5el.googlevideo.com/videoplayback?expire=1658777824&ei=gJzeYt64I8OL1d8P55-G6As&ip=114.45.19.24&id=o-AFs0oyDHmfkO0Q_PpSkkBm0VEYnfs9iShG-1ZD9UMgoT&itag=303&source=youtube&requiressl=yes&mh=nS&mm=31%2C29&mn=sn-ipoxu-un5el%2Csn-un57sn76&ms=au%2Crdu&mv=m&mvi=5&pl=20&initcwndbps=623750&vprv=1&mime=video%2Fwebm&gir=yes&clen=3765944158&dur=11127.432&lmt=1647767435696164&mt=1658755745&fvip=6&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=5432432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRgIhAJR8bUk8GyvB579U-2_tc9s-JFpI5y3HKyvHDzduNLExAiEAzlJW4ymrLIAWcCsG34eAws8LseZzlMBIfb4ZK8uvTkI%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgTZc5zkX867KSs2mTjAsCZgtYlSHOnaoDzQ35-JvHPQkCIQD-ysxcHA8CwWH73WoztJ1NVZt3Fn5gB5KZtEONenZVSg%3D%3D':
  Metadata:
    encoder         : google/video-file
  Duration: 03:05:27.43, start: 0.000000, bitrate: 2707 kb/s
  Stream #0:0(eng): Video: vp9 (Profile 0), 1 reference frame, yuv420p(tv, bt709), 1920x1080, SAR 1:1 DAR 16:9, 60 fps, 60 tbr, 1k tbn (default)
[tcp @ 000001a6e4324180] Starting connection attempt to 203.66.169.80 port 443
[tcp @ 000001a6e4324180] Successfully connected to 203.66.169.80 port 443
[tcp @ 000001a6e4307400] Starting connection attempt to 203.66.169.80 port 443
[tcp @ 000001a6e4307400] Successfully connected to 203.66.169.80 port 443
Input #1, matroska,webm, from 'https://rr5---sn-ipoxu-un5el.googlevideo.com/videoplayback?expire=1658777824&ei=gJzeYt64I8OL1d8P55-G6As&ip=114.45.19.24&id=o-AFs0oyDHmfkO0Q_PpSkkBm0VEYnfs9iShG-1ZD9UMgoT&itag=251&source=youtube&requiressl=yes&mh=nS&mm=31%2C29&mn=sn-ipoxu-un5el%2Csn-un57sn76&ms=au%2Crdu&mv=m&mvi=5&pl=20&initcwndbps=623750&vprv=1&mime=audio%2Fwebm&gir=yes&clen=194848544&dur=11127.501&lmt=1647762055669024&mt=1658755745&fvip=6&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=5431432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRAIgNuoIC2kf8u3fgF1bAYONDrw2OnV-LQ7buTsYIk9_thYCIFckP3hJNqhwQjiaG68uhj-Qzmroex40wB02HZWkODnu&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgTZc5zkX867KSs2mTjAsCZgtYlSHOnaoDzQ35-JvHPQkCIQD-ysxcHA8CwWH73WoztJ1NVZt3Fn5gB5KZtEONenZVSg%3D%3D':
  Metadata:
    encoder         : google/video-file
  Duration: 03:05:27.50, start: -0.007000, bitrate: 140 kb/s
  Stream #1:0(eng): Audio: opus, 48000 Hz, stereo, fltp, delay 312 (default)
Output #0, webm, to 'file:MSPaint but in a game (Passpartout - The Starving Artist)【NIJISANJI EN _ Shu Yamino】 [QoCs2Bv_mWo].webm.part':
  Metadata:
    encoder         : Lavf59.16.100
  Stream #0:0(eng): Video: vp9 (Profile 0), 1 reference frame, yuv420p(tv, bt709), 1920x1080 (0x0) [SAR 1:1 DAR 16:9], q=2-31, 60 fps, 60 tbr, 1k tbn (default)
  Stream #0:1(eng): Audio: opus, 48000 Hz, stereo, fltp, delay 312 (default)
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #1:0 -> #0:1 (copy)
Press [q] to stop, [?] for help
Automatically inserted bitstream filter 'vp9_superframe'; args=''
frame=  890 fps= 69 q=-1.0 size=    5120kB time=00:00:14.26 bitrate=2941.1kbits/s speed=1.11x

**Comment by aizawaaiza** [comment]
> ```
> yt-dlp -vU "youtu.be/QoCs2Bv_mWo" --download-sections "*00:25:00-00:35:00"
> ```

@pukkandan Thank you for the help. The command is working!
