### ISSUE TITLE
Add support for Winsports.co 

### ISSUE THREAD

**Issue by denaunistic** [yt-dlp/yt-dlp#4431]
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.07.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [x] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Colombia

### Example URLs

https://www.winsports.co/videos/observa-aqui-los-goles-del-empate-entre-tolima-y-nacional-60548
https://www.winsports.co/videos/siempre-castellanos-gran-atajada-del-portero-cardenal-para-evitar-la-caida-de-su-arco-60536

### Provide a description that is worded well enough to be understood

Yt-dlp can't download video or audio from the site 

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vF', 'https://www.winsports.co/videos/observa-aqui-los-goles-del-empate-entre-tolima-y-nacional-60548']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.07.18 [135f05e] (win32_exe)
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 2022-07-14-git-882aac99d2-essentials_build-www.gyan.dev (setts), ffprobe 2022-07-14-git-882aac99d2-essentials_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] [generic] Extracting URL: https://www.winsports.co/videos/observa-aqui-los-goles-del-empate-entre-tolima-y-nacional-60548
[generic] observa-aqui-los-goles-del-empate-entre-tolima-y-nacional-60548: Downloading webpage
WARNING: [generic] Falling back on generic information extractor.
[generic] observa-aqui-los-goles-del-empate-entre-tolima-y-nacional-60548: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://www.winsports.co/videos/observa-aqui-los-goles-del-empate-entre-tolima-y-nacional-60548
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1431, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1506, in __extract_info
  File "yt_dlp\extractor\common.py", line 644, in extract
  File "yt_dlp\extractor\generic.py", line 4108, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.winsports.co/videos/observa-aqui-los-goles-del-empate-entre-tolima-y-nacional-60548
```

**Comment by HobbyistDev** [comment]
In webpage source, we can get video id in `<script type="application/json" data-drupal-selector="drupal-settings-json">` especially in this section
```
"mediastream_formatter": {
            "60548": {
              "autoplay": "1",
              "view_mode": "default",
              "mediastream_id": "62dcb875ef12a5526790b552",
              "node_id": "60548"
            }
```
We can get the video in `https://mdstrm.com/video/<mediastream_id>.m3u8`. However this link seems cannot played well in ffmpeg but it's work in mpv. Sometimes mpv raise warning like this :
```
[ffmpeg/demuxer] hls: Failed to reload playlist 3
[ffmpeg/demuxer] hls: Error when loading first segment 'https://us-b4-p-e-cg11.cdn.mdstrm.com/video/h/57890c0a86d00c7b205e863a/62dcb875ef12a5526790b552_62dcb875ef12a5526790b557.mp4/seg-1-v1-a1.ts?cP=4017000&pid=3Z9HKxPpM6j1mJufgO1NejiSUnrgaJ0r&sid=PnwqKbQepq2Mja3yGAnFgmlbKJe4jUL1&uid=Leisqnyi0IKeCtkldI0X9O8U4nOItEuC&aid=57890c0a86d00c7b205e863a&access_token=4QHFy9mQQCUrLdEn1Qhq1KQGUJcuJhGX2NuwYs5yTFOu96ZUNa9kG8solL9XP7oIzCmaZBsvH4h&es=us-b4-p-e-cg11.cdn.mdstrm.com&proto=https&ote=1658800112070&ot=Hf1mhMR7abnJUxpAIv2Ldg'
[lavf] avformat_open_input() failed
[lavf] Leaking 1 nested connections (FFmpeg bug)
```

**Comment by pukkandan** [comment]
> However this link seems cannot played well in ffmpeg

We don't need ffmpeg except for livestreams
