### ISSUE TITLE
Vimeo videos fails to download forbidden 403

### ISSUE THREAD

**Issue by leconte112** [yt-dlp/yt-dlp#4442]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.07.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Taiwan

### Provide a description that is worded well enough to be understood

Vimeo protected files master.mpd is no longer working. tried all suggestions from reddit https://www.reddit.com/r/youtubedl/wiki/errors-403forbidden

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp.exe "https://12vod-adaptive.akamaized.net/exp=1658769671~acl=%2F8f16cf1d-2082-4cf1-a755-105fd1efcfcb%2F%2A~hmac=ce615995abf8bc79077873e2672485dd7fe2817118b54e902e83f21987f7e487/8f16cf1d-2082-4cf1-a755-105fd1efcfcb/sep/video/cf382a73,f8560e2b,86564ab6,71374f40,9e13467c/audio/db4a53eb,01416a80,21f8913c/master.mpd" --no-check-certificate --user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.54 Safari/537.36" --add-header "Origin: https://player.vimeo.com" --cookies-from-browser chrome --referer "https://player.vimeo.com" --verbose
[debug] Command-line config: ['https://12vod-adaptive.akamaized.net/exp=1658769671~acl=%2F8f16cf1d-2082-4cf1-a755-105fd1efcfcb%2F%2A~hmac=ce615995abf8bc79077873e2672485dd7fe2817118b54e902e83f21987f7e487/8f16cf1d-2082-4cf1-a755-105fd1efcfcb/sep/video/cf382a73,f8560e2b,86564ab6,71374f40,9e13467c/audio/db4a53eb,01416a80,21f8913c/master.mpd', '--no-check-certificate', '--user-agent', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.54 Safari/537.36', '--add-header', 'Origin: https://player.vimeo.com', '--cookies-from-browser', 'chrome', '--referer', 'https://player.vimeo.com', '--verbose']
[debug] Encodings: locale cp950, fs utf-8, pref cp950, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.07.18 [135f05e] (win32_exe)
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.4.1-full_build-www.gyan.dev (setts), ffprobe 4.4.1-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[Cookies] Extracting cookies from chrome
[debug] Extracting cookies from: "C:\Users\pwpw2\AppData\Local\Google\Chrome\User Data\Default\Network\Cookies"
[debug] Found local state file at "C:\Users\pwpw2\AppData\Local\Google\Chrome\User Data\Local State"
[Cookies] Extracted 51 cookies from chrome
[debug] cookie version breakdown: {'v10': 51, 'other': 0, 'unencrypted': 0}
[debug] Proxy map: {}
[debug] [generic] Extracting URL: https://12vod-adaptive.akamaized.net/exp=1658769671~acl=%2F8f16cf1d-2082-4cf1-a755-105fd1efcfcb%2F%2A~hmac=ce615995abf8bc79077873e2672485dd7fe2817118b54e902e83f21987f7e487/8f16cf1d-2082-4cf1-a755-105fd1efcfcb/sep/video/cf382a73,f8560e2b,86564ab6,71374f40,9e13467c/audio/db4a53eb,01416a80,21f8913c/master.mpd
[generic] master: Downloading webpage
WARNING: [generic] Falling back on generic information extractor.
[generic] master: Extracting information
[debug] Identified a DASH manifest
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] master: Downloading 1 format(s): video-71374f40+audio-01416a80
[debug] Invoking http downloader on "https://12vod-adaptive.akamaized.net/exp=1658769671~acl=%2F8f16cf1d-2082-4cf1-a755-105fd1efcfcb%2F%2A~hmac=ce615995abf8bc79077873e2672485dd7fe2817118b54e902e83f21987f7e487/8f16cf1d-2082-4cf1-a755-105fd1efcfcb/sep/video/cf382a73,f8560e2b,86564ab6,71374f40,9e13467c/audio/db4a53eb,01416a80,21f8913c/../../../../../parcel/video/71374f40.mp4?r=dXM%3D"
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 3142, in process_info
  File "yt_dlp\YoutubeDL.py", line 2860, in dl
  File "yt_dlp\downloader\common.py", line 444, in download
  File "yt_dlp\downloader\http.py", line 375, in real_download
  File "yt_dlp\downloader\http.py", line 131, in establish_connection
  File "yt_dlp\YoutubeDL.py", line 3639, in urlopen
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 563, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 755, in http_error_302
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

**Comment by leconte112** [comment]
use webpage url and cookie file fixed the issue

yt-dlp.exe --cookies cookie.txt "https://vimeo.com/ondemand/jacquespalais/728288583?autoplay=1" --no-check-certificate --user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.54 Safari/537.36" --add-header "Origin: https://player.vimeo.com" --cookies-from-browser chrome --referer "https://player.vimeo.com" --verbose

**Comment by Sogl** [comment]
> use webpage url and cookie file fixed the issue
> 
> yt-dlp.exe --cookies cookie.txt "https://vimeo.com/ondemand/jacquespalais/728288583?autoplay=1" --no-check-certificate --user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.54 Safari/537.36" --add-header "Origin: https://player.vimeo.com" --cookies-from-browser chrome --referer "https://player.vimeo.com" --verbose

@leconte112 Doesn't work for me. I use `master.mpd` URL.
