### ISSUE TITLE
RTBF Broken

### ISSUE THREAD

**Issue by Virusf** [yt-dlp/yt-dlp#4443]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.07.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

belgum 

### Provide a description that is worded well enough to be understood

No debug order plays
So I give the error message and the link
Lien : https://www.rtbf.be/auvio/detail_formule-1-grand-prix-de-france?id=2920922

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--cookies', 'cookies.txt', '--output', 'E:\\Youtube-DL\\Download\\%(title)s.%(ext)s', 'https://www.rtbf.be/auvio/detail_formule-1-grand-prix-de-france?id=2920922']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.07.18 [135f05e] (win32_exe)
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.22000-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.4-full_build-www.gyan.dev (setts), ffprobe 5.0.1-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.07.18, Current version: 2022.07.18
yt-dlp is up to date (2022.07.18)
[debug] [RTBF] Extracting URL: https://www.rtbf.be/auvio/detail_formule-1-grand-prix-de-france?id=2920922
[RTBF] 2920922: Downloading webpage
ERROR: [RTBF] 2920922: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1431, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1521, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1578, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2481, in process_video_result
  File "yt_dlp\YoutubeDL.py", line 1002, in raise_no_formats
yt_dlp.utils.ExtractorError: [RTBF] 2920922: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

**Comment by dirkf** [comment]
Possibly related: https://github.com/ytdl-org/youtube-dl/issues/31114.

**Comment by Virusf** [comment]
It's good I understood for the Debug mode
And yes it is the same problem
And here are the logs

`[debug] Command-line config: ['-vU', '--cookies', 'cookies.txt', '--output', 'E:\\Youtube-DL\\Download\\%(title)s.%(ext)s', 'https://www.rtbf.be/auvio/detail_formule-1-grand-prix-de-france?id=2920922']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.07.18 [135f05e] (win32_exe)
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.22000-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.4-full_build-www.gyan.dev (setts), ffprobe 5.0.1-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.07.18, Current version: 2022.07.18
yt-dlp is up to date (2022.07.18)
[debug] [RTBF] Extracting URL: https://www.rtbf.be/auvio/detail_formule-1-grand-prix-de-france?id=2920922
[RTBF] 2920922: Downloading webpage
ERROR: [RTBF] 2920922: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1431, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1521, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1578, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2481, in process_video_result
  File "yt_dlp\YoutubeDL.py", line 1002, in raise_no_formats
yt_dlp.utils.ExtractorError: [RTBF] 2920922: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U`

**Comment by ArturiaPendragon** [comment]
It's Widevine.

**Comment by MichelLopez** [comment]
Not geo-blocked for news.

For example https://www.rtbf.be/auvio/detail_jt-19h30?id=2921981

**Comment by MichelLopez** [comment]
Don't know if this is related or maybe exposing another issue.
With cookies from Firefox the proposed fix is working ok
.\yt-dlp.cmd  --cookies-from-browser firefox https://www.rtbf.be/auvio/detail_jt-19h30?id=292349
[download] 100% of 376.84MiB in 00:49
[download] 100% of 29.43MiB in 05:32
while the same with cookies from Edge it is not
 .\yt-dlp.cmd  --cookies-from-browser edge https://www.rtbf.be/auvio/detail_jt-19h30?id=2923494
ERROR: 2923494: An extractor error has occurred. (caused by KeyError('id_token'))

**Comment by elyse0** [comment]
@MichelLopez I've just updated it, can you try using username and password?

**Comment by MichelLopez** [comment]
@elyse0 it is working perfectly with just username and password 
 .\yt-dlp.cmd  --username xxxxxx@test.com --password yyyyyy https://www.rtbf.be/auvio/detail_jt-19h30?id=2923494
[RTBF] Downloading JSON metadata
[RTBF] 2923494: Downloading webpage
[RTBF] 2923494: Downloading JSON metadata
[RTBF] 2923494: Downloading JSON metadata
[RTBF] 2923494: Downloading JSON metadata
[RTBF] 2923494: Downloading MPD manifest
[RTBF] 2923494: Downloading m3u8 information
[RTBF] 2923494: Downloading ISM manifest
[info] 2923494: Downloading 1 format(s): 1826+audio_eng-128
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 333
[download] Destination: 30.07.2022 [2923494].f1826.mp4
[download] 100% of 376.84MiB in 00:59
[ism] Total fragments: 999
[download] Destination: 30.07.2022 [2923494].faudio_eng-128.isma
[download] 100% of 29.43MiB in 01:25
[Merger] Merging formats into "30.07.2022 [2923494].mp4"
Deleting original file 30.07.2022 [2923494].f1826.mp4 (pass -k to keep)
Deleting original file 30.07.2022 [2923494].faudio_eng-128.isma (pass -k to keep)

**Comment by stemy2** [comment]
Still not working for me, it says "unsupported url: https://auvio.rtbf.be/emission/[emission-title]".
