### ISSUE TITLE
Clip audio through Python

### ISSUE THREAD

**Issue by jerryga** [yt-dlp/yt-dlp#4445]
How can I clip audio from a specified time range? Here are my code snips. It has no effect on the audio result.

`ydl_opts = {
    'start_time': 10,
    'end_time': 30,
    'format': 'm4a/bestaudio/best',
    'postprocessors': [{  
        'key': 'FFmpegExtractAudio',
        'preferredcodec': 'm4a',
        }],

}

with yt_dlp.YoutubeDL(ydl_opts) as ydl:
    ydl.download(URLS)`

**Comment by pukkandan** [comment]
You realize the issue templates exist for a reason, right?

> How can I clip audio from a specified time range?

During download or during PP? For the former, use:

https://github.com/yt-dlp/yt-dlp/blob/f5ea47488a2c59b2520b4988b7eab4d8830e3077/yt_dlp/YoutubeDL.py#L433-L439

To do it in PP, you can define a custom PP derived `FFmpegCopyStreamPP`

**Comment by jerryga** [comment]
> 

Sorry for being not familiar with Python or PP. I'm using python code from the Readme.md. I just add start_time and end_time in ydl_opts. Do you mean that  I should add start_time in the postprocessors?

**Comment by pukkandan** [comment]
```py
from yt_dlp.utils import download_range_func

ydl_opts = {
    'download_ranges': download_range_func([], [(10, 30)]),
    ...
})
...

**Comment by jerryga** [comment]
> ```python
> from yt_dlp.utils import download_range_func
> 
> ydl_opts = {
>     'download_ranges': download_range_func([], [(10, 30)]),
>     ...
> })
> ...
> ```

Thank you very much! You saved my life.
Have a good day!

**Comment by jerryga** [comment]
thank you!
