### ISSUE TITLE
why Multi-threaded only works for fragment downloads

### ISSUE THREAD

**Issue by candrapersada** [yt-dlp/yt-dlp#4448]
### Checklist

- [ ] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.07.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [ ] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [ ] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

why Multi-threaded only works for fragment downloads and doesn't work for non-fragment downloads?
and is there any other way to use concurrent download?

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
Use external downloaders like aria2c

**Comment by candrapersada** [comment]
how to use Multi-threaded for fragment downloads and aria2 for non-fragment downloads?

**Comment by pukkandan** [comment]
--downloader aria2c --downloader m3u8,dash:native -N 8

**Comment by candrapersada** [comment]
does [wget2](https://gitlab.com/gnuwget/wget2) support HLS/DASH or not? #4169

**Comment by pukkandan** [comment]
Maybe.. Obviously, it depends on whether such a feature is implemented. Currently HLS/DASH support is only added to ffmpeg/aria2c, but PRs to add it to any downloader is welcome
