### ISSUE TITLE
[Crunchyroll] Does not gives all available subtitles

### ISSUE THREAD

**Issue by jomp16** [yt-dlp/yt-dlp#4452]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.07.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Brazil

### Provide a description that is worded well enough to be understood

Crunchyroll now forces to use the beta website, but yt-dlp can't find any subtitles other than en-us.

By using `https://beta.crunchyroll.com/watch/G8WUN8VKP/the-ruler-of-conspiracy` as example.

yt-dlp first checks the URL `<API>/cms/v2/BR/M3/crunchyroll/episodes/G8WUN8VKP`

Then it fetches the stream data from `playback` URL in API response.

But looking at where the beta website gets the subtitles list and downloads.

Beta website, get the available streams from endpoint `/cms/v2/BR/M3/crunchyroll/videos/GQ9FG10XZ/streams`.

The above URL is avaiable at `episodes` endpoint, at path `'__links__'->'streams'`

The `streams` endpoint, has all the streams available for the video, and also, the subtitles, check print:

![Screenshot_20220726_160040](https://user-images.githubusercontent.com/2255920/181090049-a7f722ec-5d00-453b-900b-08c618306919.png)

---

I hope that was helpful to implement the missing functionality.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['--cookies', '/home/jomp16/cookies.txt', '--list-subs', '--skip-download', '-vU', 'https://beta.crunchyroll.com/watch/G8WUN8VKP/the-ruler-of-conspiracy']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.07.18 [135f05e]
[debug] Python 3.10.5 (CPython 64bit) - Linux-5.18.14-lqx1-1-lqx-x86_64-with-glibc2.35 (glibc 2.35)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 5.0.1 (setts), ffprobe 5.0.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.12.0, brotlicffi-1.0.9.2, certifi-2022.06.15, secretstorage-3.3.2, sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.07.18, Current version: 2022.07.18
yt-dlp is up to date (2022.07.18)
[debug] [crunchyroll:beta] Extracting URL: https://beta.crunchyroll.com/watch/G8WUN8VKP/the-ruler-of-conspiracy
[crunchyroll:beta] Retrieving main page
[crunchyroll:beta] Authenticating with cookie
[crunchyroll:beta] Retrieving signed policy
[crunchyroll:beta] the-ruler-of-conspiracy: Retrieving episode metadata
[crunchyroll:beta] the-ruler-of-conspiracy: Retrieving stream info
[crunchyroll:beta] the-ruler-of-conspiracy: Downloading adaptive_hls information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[info] Available subtitles for G8WUN8VKP:
Language Formats
en-US    ass
```

**Comment by ArturiaPendragon** [comment]
Crunchyroll now forces to use the beta website, same problems for me for `https://beta.crunchyroll.com/fr/watch/GWDU8WM9J/how-to-have-a-wicked-time-in-jinbocho`

**Comment by jomp16** [comment]
Maybe Crunchyroll has done something, because the exact comand right now gives all availables subtitles.

```
❯ yt-dlp --cookies /home/jomp16/cookies.txt --list-subs --skip-download -vU https://beta.crunchyroll.com/watch/G8WUN8VKP/the-ruler-of-conspiracy
[debug] Command-line config: ['--cookies', '/home/jomp16/cookies.txt', '--list-subs', '--skip-download', '-vU', 'https://beta.crunchyroll.com/watch/G8WUN8VKP/the-ruler-of-conspiracy']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.07.18 [135f05e]
[debug] Python 3.10.5 (CPython 64bit) - Linux-5.18.14-lqx1-1-lqx-x86_64-with-glibc2.35 (glibc 2.35)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 5.0.1 (setts), ffprobe 5.0.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.12.0, brotlicffi-1.0.9.2, certifi-2022.06.15, secretstorage-3.3.2, sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.07.18, Current version: 2022.07.18
yt-dlp is up to date (2022.07.18)
[debug] [crunchyroll:beta] Extracting URL: https://beta.crunchyroll.com/watch/G8WUN8VKP/the-ruler-of-conspiracy
[crunchyroll:beta] Retrieving main page
[crunchyroll:beta] Authenticating with cookie
[crunchyroll:beta] Retrieving signed policy
[crunchyroll:beta] the-ruler-of-conspiracy: Retrieving episode metadata
[crunchyroll:beta] the-ruler-of-conspiracy: Retrieving stream info
[crunchyroll:beta] the-ruler-of-conspiracy: Downloading adaptive_hls information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[info] Available subtitles for G8WUN8VKP:
Language Formats
en-US    ass
pt-BR    ass
ru-RU    ass
es-LA    ass
```

**Comment by ArturiaPendragon** [comment]
Here again this night :

```
[debug] Command-line config: ['--cookies', 'cookies.txt', '-U', 'https://www.crunchyroll.com/fr/lucifer-and-the-biscuit-hammer/episode-4-asahina-hisame-and-shinonome-hangetsu-852956', '--user-agent', 'Mozilla/5.0 (X11; Linux x86_64; rv:91.0) Gecko/20100101 Firefox/91.0', '--write-sub', '--no-download', '--list-subs', '--skip-download', '-vU']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.07.18 [135f05e] (zip)
[debug] Python 3.9.2 (CPython 64bit) - Linux-4.19.0-18-amd64-x86_64-with-glibc2.31 (glibc 2.31)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg N-105731-gb14321e307 (fdk,setts), ffprobe N-105731-gb14321e307
[debug] Optional libraries: Crypto-3.14.1, certifi-2020.06.20, sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.07.18, Current version: 2022.07.18
yt-dlp is up to date (2022.07.18)
[debug] [crunchyroll] Extracting URL: https://www.crunchyroll.com/fr/lucifer-and-the-biscuit-hammer/episode-4-asahina-hisame-and-shinonome-hangetsu-852956
[crunchyroll] 852956: Downloading webpage
[crunchyroll] 852956: Redirected to beta site - https://beta.crunchyroll.com/watch/GN7UD9J3Q/asahina-hisame-and-shinonome-hangetsu
[debug] [crunchyroll:beta] Extracting URL: https://beta.crunchyroll.com/watch/GN7UD9J3Q/asahina-hisame-and-shinonome-hangetsu
[crunchyroll:beta] Retrieving main page
[crunchyroll:beta] Authenticating with cookie
[crunchyroll:beta] Retrieving signed policy
[crunchyroll:beta] asahina-hisame-and-shinonome-hangetsu: Retrieving episode metadata
[crunchyroll:beta] asahina-hisame-and-shinonome-hangetsu: Retrieving stream info
[crunchyroll:beta] asahina-hisame-and-shinonome-hangetsu: Downloading adaptive_hls information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Downloading subtitles: en-US
[info] Available subtitles for GN7UD9J3Q:
Language Formats
en-US    ass
```

but on the website : https://i.imgur.com/R1VlWfA.png

**Comment by jomp16** [comment]
@ArturiaPendragon and now the same command lists all available subtitles.

Maybe Crunchyroll is releasing the incomplete playback stream and then later releasing the subtitles as an alternative stream, and then later merging them into one stream.

I think that YT-DLP should use the `/cms/v2/[...]/videos/<ID>/streams` listed above, that the player uses to list all the available subtitles and hardcoded videos instead of getting the single, playback stream URL that at times doesn't have all the subtitles available.

**Comment by ArturiaPendragon** [comment]
@jomp16 Yes I think that's probably it, and yes taking `/cms/v2/[...]/videos/<ID>/streams` would be a good idea to get the subtitles directly without waiting sometimes several days for them to realize it.

**Comment by pukkandan** [comment]
@tejing1

**Comment by tejing1** [comment]
I could never see any difference between the `playback` url and the `streams` url in testing, but perhaps the difference only appears in non-US regions? Or else the difference is rare and just a result of failure to invalidate a cache somewhere, given that the playback url is hosted on a different server?

Anyway, iirc the data returned by `streams` isn't in quite the same format, so it'd be a bit of work to change it. I should have some time to look into it soon.

**Comment by pukkandan** [comment]
According to @jomp16's theory, the difference exists only for new releases

**Comment by tejing1** [comment]
@jomp16 @ArturiaPendragon If you're able to run yt-dlp from a PR, and can find a video that's currently misbehaving this way with the existing extractor, could you verify that the PR does in fact fix it for you?

**Comment by jomp16** [comment]
Will do, if I find any video that’s missing the subtitles but on web player
it does exist.

Thanks!

Em qui., 4 de ago. de 2022 às 12:52 PM, Jeff Huffman <
***@***.***> escreveu:

**Comment by jomp16** [comment]
Unfortunately I’m at work, but my friend found that this url doesn’t list
all subtitles with latest yt-dlp (not your PR version)

https://beta.crunchyroll.com/watch/GQJUG1Z92/kirishimas-day-off


Em qui., 4 de ago. de 2022 às 12:58 PM, José Olivio Pedrosa <
***@***.***> escreveu:

**Comment by tejing1** [comment]
Confirmed. It apparently affects US users as well:
```
BASH python3.10-yt-dlp-2022.6.29 שׂcr-beta-use-stream yt-dlp 4s $ ./yt-dlp --cookies-from-browser brave --list-subs https://beta.crunchyroll.com/watch/GQJUG1Z92/kirishimas-day-off
[Cookies] Extracting cookies from brave
[Cookies] Extracted 2584 cookies from brave
[crunchyroll:beta] Retrieving main page
[crunchyroll:beta] Authenticating with cookie
[crunchyroll:beta] Retrieving signed policy
[crunchyroll:beta] kirishimas-day-off: Retrieving episode metadata
[crunchyroll:beta] kirishimas-day-off: Retrieving stream info
[crunchyroll:beta] kirishimas-day-off: Downloading adaptive_hls HLS manifest
[info] Available subtitles for GQJUG1Z92:
Language Formats
de-DE    ass
en-US    ass
es-ES    ass
es-LA    ass
fr-FR    ass
it-IT    ass
pt-BR    ass
ru-RU    ass
BASH python3.10-yt-dlp-2022.6.29 שׂcr-beta-use-stream yt-dlp 2s $ git checkout master
Switched to branch 'master'
Your branch is up to date with 'upstream/master'.
BASH python3.10-yt-dlp-2022.6.29 שׂmaster yt-dlp $ ./yt-dlp.sh --cookies-from-browser brave --list-subs https://beta.crunchyroll.com/watch/GQJUG1Z92/kirishimas-day-off
[Cookies] Extracting cookies from brave
[Cookies] Extracted 2584 cookies from brave
[crunchyroll:beta] Retrieving main page
[crunchyroll:beta] Authenticating with cookie
[crunchyroll:beta] Retrieving signed policy
[crunchyroll:beta] kirishimas-day-off: Retrieving episode metadata
[crunchyroll:beta] kirishimas-day-off: Retrieving stream info
[crunchyroll:beta] kirishimas-day-off: Downloading adaptive_hls HLS manifest
[info] Available subtitles for GQJUG1Z92:
Language Formats
en-US    ass
```

**Comment by tejing1** [comment]
Probably only non-english regions are noticing it because CR gets their english subs out differently/more quickly than their other language subs.

**Comment by jomp16** [comment]
Yeah that was my guess, because only later (some hours later), it works
without changing anything (maybe they updated their playlist data).

But since the web player gets the subtitles from another stream, everything
is a-ok in their side.

Thanks for improving and testing it!


Em qui., 4 de ago. de 2022 às 2:10 PM, Jeff Huffman <
***@***.***> escreveu:

**Comment by tejing1** [comment]
I'm a bit surprised github doesn't recognize and censor the unsubscribe link from your replies @jomp16. I hope that means that after following the link you still need to authenticate to change anything...

**Comment by jomp16** [comment]
Yeah, opening that unsubscribe link in a new private browser session, opens the login page. But if I open logged-in with my account, it successfully unsubscribe from this issue.

**Comment by tejing1** [comment]
Good to know. :relieved:
