### ISSUE TITLE
yt-dlp Says a Video is Private Even Though it is Not

### ISSUE THREAD

**Issue by amarakon** [yt-dlp/yt-dlp#4455]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.07.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

I tried to download the video `https://www.youtube.com/watch?v=M7mKMWjAxG8` by running the command `yt-dlp "https://www.youtube.com/watch?v=M7mKMWjAxG8"` but it gave me the following error:

```
[youtube] M7mKMWjAxG8: Downloading webpage
[youtube] M7mKMWjAxG8: Downloading android player API JSON
ERROR: [youtube] M7mKMWjAxG8: Private video. Sign in if you've been granted access to this video
```

I tried signing in by using the `--cookies` option and it gave me a different error:

```
[youtube] M7mKMWjAxG8: Downloading webpage
[youtube] M7mKMWjAxG8: Downloading android player API JSON
ERROR: [youtube] M7mKMWjAxG8: Video unavailable. This video is private
```

The video is not private, I can view it in my web browser whether I am signed in or not.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.youtube.com/watch?v=M7mKMWjAxG8']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.07.18 [135f05e] (zip)
[debug] Python 3.8.10 (CPython 64bit) - Linux-5.4.0-120-generic-x86_64-with-glibc2.29 (glibc 2.31)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.2.7, ffprobe 4.2.7, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.6.1, certifi-2019.11.28, mutagen-1.44.0, pyxattr-0.6.1, secretstorage-2.3.1, sqlite3-2.6.0, websockets-8.1
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.07.18, Current version: 2022.07.18
yt-dlp is up to date (2022.07.18)
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=M7mKMWjAxG8
[youtube] M7mKMWjAxG8: Downloading webpage
[youtube] M7mKMWjAxG8: Downloading android player API JSON
ERROR: [youtube] M7mKMWjAxG8: Private video. Sign in if you've been granted access to this video
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 644, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/youtube.py", line 3486, in _real_extract
    self.raise_no_formats(reason, expected=True)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 1126, in raise_no_formats
    raise ExtractorError(msg, expected=expected, video_id=video_id)
```

**Comment by clusterized** [comment]
YouTube shows the video as private in my browser. But if you can really watch it, you could try `--cookies-from-browser BROWSER` (instead of just `--cookies`).

**Comment by amarakon** [comment]
The video was private when I first opened it in my browser. But you're right, the video is indeed private now. I should have double-checked by refreshing my browser tab, my bad.
