### ISSUE TITLE
video not download

### ISSUE THREAD

**Issue by ludo77** [yt-dlp/yt-dlp#4460]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.07.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

france

### Provide a description that is worded well enough to be understood

the video is downloaded, but the video cannot be viewed.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp -vU https://prod-avod-pmd-edgecast.cdn.rakuten.tv/2/b/c/2bce8e0c66bd3cb63840d52ed6ff08c2-mc-0-144-0-0_DS2BB/video-avc1-3.ismv
[debug] Command-line config: ['-vU', 'https://prod-avod-pmd-edgecast.cdn.rakuten.tv/2/b/c/2bce8e0c66bd3cb63840d52ed6ff08c2-mc-0-144-0-0_DS2BB/video-avc1-3.ismv']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.07.18 [135f05e] (zip)
[debug] Python 3.8.10 (CPython 64bit) - Linux-5.4.0-122-generic-x86_64-with-glibc2.29 (glibc 2.31)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.2.7, ffprobe 4.2.7, phantomjs 2.1.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, pyxattr-0.6.1, secretstorage-2.3.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.07.18, Current version: 2022.07.18
yt-dlp is up to date (2022.07.18)
[debug] [generic] Extracting URL: https://prod-avod-pmd-edgecast.cdn.rakuten.tv/2/b/c/2bce8e0c66bd3cb63840d52ed6ff08c2-mc-0-144-0-0_DS2BB/video-avc1-3.ismv
[generic] video-avc1-3: Downloading webpage
[debug] Identified a direct video link
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] video-avc1-3: Downloading 1 format(s): fmp4
[debug] Invoking http downloader on "https://prod-avod-pmd-edgecast.cdn.rakuten.tv/2/b/c/2bce8e0c66bd3cb63840d52ed6ff08c2-mc-0-144-0-0_DS2BB/video-avc1-3.ismv"
[download] Resuming download at byte 152341901
[download] Destination: video-avc1-3 [video-avc1-3].ismv
```

**Comment by sqrtNOT** [comment]
That file is corrupt but downloads just fine. It doesn't play in browser either so I'd say yt-dlp is working as intended.
