### ISSUE TITLE
Crunchyroll (non-beta) redirect to Crunchyroll (beta)

### ISSUE THREAD

**Issue by CZeil** [yt-dlp/yt-dlp#4464]
### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.07.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Yesterday I tried to download a chapter of the series and I just realized that it redirected to the beta site. And it did not extract the url from the beta site it always made this redirection.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp -vF -n https://www.crunchyroll.com/es/overlord/episode-4-the-ruler-of-conspiracy-852480
[debug] Command-line config: ['-vF', '-n', 'https://www.crunchyroll.com/es/overlord/episode-4-the-ruler-of-conspiracy-852480']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.07.18 [135f05e]
[debug] Python 3.10.5 (CPython 32bit) - Linux-4.19.127-armv7l-with-libc (libc)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 5.0.1 (setts), ffprobe 5.0.1
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[crunchyroll] Getting session id
[crunchyroll] Logging in
[debug] [crunchyroll] Extracting URL: https://www.crunchyroll.com/es/overlord/episode-4-the-ruler-of-conspiracy-852480
[crunchyroll] 852480: Downloading webpage
[crunchyroll] 852480: Redirected to beta site - https://beta.crunchyroll.com/watch/G8WUN8VKP/the-ruler-of-conspiracy
[debug] [crunchyroll:beta] Extracting URL: https://beta.crunchyroll.com/watch/G8WUN8VKP/the-ruler-of-conspiracy
[crunchyroll:beta] Retrieving main page
[crunchyroll:beta] Authenticating with cookie
[crunchyroll:beta] Retrieving signed policy
[crunchyroll:beta] the-ruler-of-conspiracy: Retrieving episode metadata
[crunchyroll:beta] the-ruler-of-conspiracy: Retrieving stream info
[crunchyroll:beta] the-ruler-of-conspiracy: Downloading adaptive_hls information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[info] Available formats for G8WUN8VKP:
ID                  EXT RESOLUTION FPS │   FILESIZE   TBR PROTO │ VCODEC        VBR ACODEC    ABR MORE INFO
───────────────────────────────────────────────────────────────────────────────────────────────────────────
adaptive_hls-195-0  mp4 144x80      24 │ ~ 34.33MiB  195k m3u8  │ avc1.42c00c  195k mp4a.40.2  0k [ja-JP]
adaptive_hls-195-1  mp4 144x80      24 │ ~ 34.33MiB  195k m3u8  │ avc1.42c00c  195k mp4a.40.2  0k [ja-JP]
adaptive_hls-563-0  mp4 428x240     24 │ ~ 99.03MiB  563k m3u8  │ avc1.42c015  563k mp4a.40.2  0k [ja-JP]
adaptive_hls-563-1  mp4 428x240     24 │ ~ 99.03MiB  563k m3u8  │ avc1.42c015  563k mp4a.40.2  0k [ja-JP]
adaptive_hls-1093-0 mp4 640x360     24 │ ~192.18MiB 1093k m3u8  │ avc1.4d401e 1093k mp4a.40.2  0k [ja-JP]
adaptive_hls-1093-1 mp4 640x360     24 │ ~192.18MiB 1093k m3u8  │ avc1.4d401e 1093k mp4a.40.2  0k [ja-JP]
adaptive_hls-2090-0 mp4 848x480     24 │ ~367.59MiB 2091k m3u8  │ avc1.4d401f 2091k mp4a.40.2  0k [ja-JP]
adaptive_hls-2090-1 mp4 848x480     24 │ ~367.59MiB 2091k m3u8  │ avc1.4d401f 2091k mp4a.40.2  0k [ja-JP]
adaptive_hls-4127-0 mp4 1280x720    24 │ ~725.67MiB 4128k m3u8  │ avc1.640028 4128k mp4a.40.2  0k [ja-JP]
adaptive_hls-4127-1 mp4 1280x720    24 │ ~725.67MiB 4128k m3u8  │ avc1.640028 4128k mp4a.40.2  0k [ja-JP]
adaptive_hls-8103-0 mp4 1920x1080   24 │ ~  1.39GiB 8104k m3u8  │ avc1.640028 8104k mp4a.40.2  0k [ja-JP]
adaptive_hls-8103-1 mp4 1920x1080   24 │ ~  1.39GiB 8104k m3u8  │ avc1.640028 8104k mp4a.40.2  0k [ja-JP]
```

**Comment by pukkandan** [comment]
Which version do you get in browser when logged in?

**Comment by CZeil** [comment]
@pukkandan i use chrome for Android version=102.0.5005.125 / yt-dlp installed on termux

**Comment by pukkandan** [comment]
You seem to have misunderstood my question.

Do you get the non-beta site on your browser when logged in?

**Comment by CZeil** [comment]
Yes, in fact if I try to enter the beta site it automatically redirects me to the classic Crunchyroll site.

**Comment by CZeil** [comment]
> Yes, in fact if I try to enter the beta site it automatically redirects me to the classic Crunchyroll site.

![Screenshot_20220727-103307](https://user-images.githubusercontent.com/92319318/181301181-4dfcc709-d30f-40b9-91bf-6c2f5c6d06fa.png)

**Comment by pukkandan** [comment]
Bruh, you are not logged in! Pls read what I am asking before answering...

**Comment by CZeil** [comment]
😒

**Comment by pukkandan** [comment]
Afaik, crunchyroll now redirects all logged in users to the beta site. This is why yt-dlp does the same

**Comment by CZeil** [comment]
> Afaik, crunchyroll now redirects all logged in users to the beta site. This is why yt-dlp does the same. The non-beta site (when logged in) does not have any extractable content

https://www.crunchyroll.com/es/my-stepmoms-daughter-is-my-ex/episode-4-thats-not-what-youre-supposed-to-say-852612
