### ISSUE TITLE
Need help with Vimeo

### ISSUE THREAD

**Issue by tonytkachenko** [yt-dlp/yt-dlp#4465]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.07.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Provide a description that is worded well enough to be understood

I can't download some videos from Vimeo. It starts and downloads a few fragments but then throws 404
The sample video is accessible on https://derma.medknowhub.com/webinars-online/top-10-metodiv-likuvannia-virusnykh-borodavok

Thanks!

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-Uv', 'https://player.vimeo.com/video/725243146?h=8393a7dd0e', '--referer', 'https://derma.medknowhub.com/']
[debug] Encodings: locale cp1251, fs utf-8, pref cp1251, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.07.18 [135f05e] (win32_exe)
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.22000-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 5.1-essentials_build-www.gyan.dev (setts), ffprobe 5.1-essentials_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.07.18, Current version: 2022.07.18
yt-dlp is up to date (2022.07.18)
[debug] [vimeo] Extracting URL: https://player.vimeo.com/video/725243146?h=8393a7dd0e
[vimeo] 725243146: Downloading webpage
[vimeo] 725243146: Downloading akfire_interconnect_quic m3u8 information
[vimeo] 725243146: Downloading fastly_skyfire m3u8 information
[vimeo] 725243146: Downloading akfire_interconnect_quic MPD information
[vimeo] 725243146: Downloading fastly_skyfire MPD information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, lang, vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 725243146: Downloading 1 format(s): hls-fastly_skyfire-4336
[debug] Invoking hlsnative downloader on "https://skyfire.vimeocdn.com/1658976376-0x6ae1cb0167f43077624cc482a6030e6e5f37b25d/a6b1822a-dbdf-4719-9d34-9b12dbbe8104/video/436666ef/playlist.m3u8?query_string_ranges=1"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 936
[download] Destination: 1.07.2022 GR_Топ 10 методів лікування вірусних бородавок [725243146].mp4
[debug] File locking is not supported. Proceeding without locking
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 2 (attempt 1 of 10) ...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 2 (attempt 2 of 10) ...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 2 (attempt 3 of 10) ...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 2 (attempt 4 of 10) ...
[download] Got server HTTP error: HTTP Error 404: Not Found. Retrying fragment 2 (attempt 5 of 10) ...
```

**Comment by flashdagger** [comment]
Many formats are not available. Try with `--format dash-akfire_interconnect_quic-video-436666ef`
