### ISSUE TITLE
What about changing -P home/temp behavior ?

### ISSUE THREAD

**Issue by nmr50** [yt-dlp/yt-dlp#4469]
### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.07.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

I dl some video streams from ytube, and I found that ydl is downloading video to temp file, then fixing its TS state, and the writes  output down to the final name on the same folder.  
When I tried to use **-P temp:F:\ -P home:. url** - I found that ydl doing the same - downloading video to temp file, fixing its TS state on the F:\ drive where temp files is located - writing finalized file there, and then moving this final file to the source dir (-P home:.).  
What I am supposing is to change behavior of those -P types so ydl will download temp file to the specified temp location (F:\ as in my case), but fixed TS stuff will give output directly to the home: type (. in my case), without writing to the temp folder and then moving final file to the home: folder.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
*not needed*
```

**Comment by pukkandan** [comment]
It is not possible because the last processing step can be anything. For example, if you have any of --add-metadata, --embed-thumb etc, there is further processing that happens after fixing TS. So we can only move the file to final destination after all processing is complete

**Comment by nmr50** [comment]
> It is not possible because the last processing step can be anything. For example, if you have any of --add-metadata, --embed-thumb etc, there is further processing that happens after fixing TS. So we can only move the file to final destination after all processing is complete
  
Ok, then it will be useful to check out additional parameters and use old scheme - download, fix TS thingie in one folder, and then move to where user asked... AND if there are NO --add-metadata, --embed-thumb etc - use my scheme - download, fix TS thingie while writing final version to specified home folder - is it ok ?

**Comment by pukkandan** [comment]
> I think it is pretty simple to apply this scheme along with the old one

As I just said above, it is not! This will need to be implemented in each PP and each will need to "look at" all other PPs in order to decide whether to enable this code path. It is quite complicated to make it work correctly and consistently, which is why `-P temp:` is implemented like it is.

Besides, you never explained **why** you need the feature. As I see it, this is a difficult and complicated request that has little to no real benefit

**Comment by nmr50** [comment]
I have had a thought to keep hdds life with downloading temp file onto one hdd, and moving fixed file to another hdd.
anyway, I tried **--fixup never** and found no difference - my media player just plays this 'unfixed' version without no problems.
Can you explain what this 'fixing TS' is doing at all ?

**Comment by pukkandan** [comment]
https://roundup.ffmpeg.org/ffmpeg-bitstream-filters.html#aac_005fadtstoasc

**Comment by nmr50** [comment]
the case cannot be solved, so it has to be closed now.
