### ISSUE TITLE
[Feature Request]  MTV.COM - Automerge Multiple MP4 outputs:  MTV.com Splits their Episodes in to multiple *"Acts".MP4

### ISSUE THREAD

**Issue by ohmybahgosh** [yt-dlp/yt-dlp#447]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running yt-dlp version **2021.06.23**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description

Like the title states.. MTV.com formats their episodes in to multiple Acts, so the output is normally 10-11 unique MP4 files per episode that I then need to manually merge. 
  
Is there a way to automatically merge this single episode with multiple MP4 outputs, in to a single mp4 episode file  via a flag? 
  
**Example Episode URL**  
*https://www.mtv.com/episodes/viogcs/jersey-shore-family-vacation-welcome-to-the-poconos-season-4-ep-18*
   
**Example Command for YT-DLP that I use**  
*yt-dlp -f 'bv+ba/b' --convert-subtitles=srt --add-metadata --write-all-thumbnails --embed-thumbnail --write-info-json -N35*
  
**Example Output via YT-DLP**  
[Multiple MP4 Files For Single Episode](https://i.imgur.com/OG3NH0Z.jpg)
  
Now these are definitely unique MP4 files, each divided in to "Act [NUM]", but for shits and giggles I tried using no-part flags etc.
  
Currently I have to use ffmpeg to merge these multiple MP4 episodes.  The Multiple MP4 files are commercial free, so I assume that MTV uses the multiple MP4 files to insert commercials in-between.
  
**For anyone who needs it, here's my current script using YT-DLP to download an episode and Automerge the multiple output mp4 files.  It lacks automatic naming from source URL, but it's working as a bandaid:**

https://github.com/ohmybahgosh/MTV-YTDLP

**Comment by pukkandan** [comment]
Related:
https://github.com/ytdl-org/youtube-dl/pull/28153
https://github.com/yt-dlp/yt-dlp/pull/360
https://github.com/yt-dlp/yt-dlp/issues/382

**Comment by pukkandan** [comment]
https://github.com/yt-dlp/yt-dlp/commit/3b603dbdf139efe187f961dbe8b1b24ba16ae194 should fix this
