### ISSUE TITLE
yt-dlp can't download after use SponsorBlock

### ISSUE THREAD

**Issue by Bonnary** [yt-dlp/yt-dlp#4474]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.07.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

I have tried installing yt-dlp in wsl and working normal but when I tried using SponsorBlock it just stuck in this state 
 yt-dlp https://youtu.be/ZstsPUKT5CI
[youtube] ZstsPUKT5CI: Downloading webpage
[youtube] ZstsPUKT5CI: Downloading android player API JSON
[info] ZstsPUKT5CI: Downloading 1 format(s): 303+251
[download] Got server HTTP error: <urlopen error timed out>. Retrying (attempt 1 of 10) ...

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
PS C:\Users\Bonnary\Desktop> yt-dlp -vU https://youtu.be/ZstsPUKT5CI
[debug] Command-line config: ['-vU', 'https://youtu.be/ZstsPUKT5CI']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.06.29 [9d339c4] (win32_exe)
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.22000-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 2022-07-06-git-03d81a044a-full_build-www.gyan.dev (setts), ffprobe 2022-07-06-git-03d81a044a-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
[debug] Downloading _update_spec from https://github.com/yt-dlp/yt-dlp/releases/download/2022.07.18/_update_spec
Latest version: 2022.07.18, Current version: 2022.06.29
Current Build Hash 579d8f37a2d2e2fb8f100890f585462c8566e91f6890728c18bd741417478b08
Updating to version 2022.07.18 ...
[debug] Downloading yt-dlp.exe from https://github.com/yt-dlp/yt-dlp/releases/download/2022.07.18/yt-dlp.exe
[debug] Downloading SHA2-256SUMS from https://github.com/yt-dlp/yt-dlp/releases/download/2022.07.18/SHA2-256SUMS
Updated yt-dlp to version 2022.07.18
[debug] Restarting: "C:\MPV\yt-dlp.exe" -vU "https://youtu.be/ZstsPUKT5CI"
[debug] Command-line config: ['-vU', 'https://youtu.be/ZstsPUKT5CI']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.07.18 [135f05e] (win32_exe)
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.22000-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 2022-07-06-git-03d81a044a-full_build-www.gyan.dev (setts), ffprobe 2022-07-06-git-03d81a044a-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.07.18, Current version: 2022.07.18
yt-dlp is up to date (2022.07.18)
[debug] [youtube] Extracting URL: https://youtu.be/ZstsPUKT5CI
[youtube] ZstsPUKT5CI: Downloading webpage
[youtube] ZstsPUKT5CI: Downloading android player API JSON
[debug] [youtube] Extracting signature function js_240bde48_112
[debug] Loading youtube-sigfuncs.js_240bde48_112 from cache
[debug] Loading youtube-nsig.240bde48 from cache
[debug] [youtube] Decrypted nsig _kjLTZXZLD1Uv8-d => nq6_2OrRgh1z1w
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] ZstsPUKT5CI: Downloading 1 format(s): 303+251
[debug] Invoking http downloader on "https://rr6---sn-8pxuuxaj5hcvqp5-2oiz.googlevideo.com/videoplayback?expire=1659038615&ei=N5fiYrGPMM3N2roPr9q7-A0&ip=175.100.62.104&id=o-AFoam6asrg4wZFOxU0IYR4lHBOpRAyE9OwCKOPCbmmtn&itag=303&source=youtube&requiressl=yes&mh=7K&mm=31%2C29&mn=sn-8pxuuxaj5hcvqp5-2oiz%2Csn-npoe7nsl&ms=au%2Crdu&mv=m&mvi=6&pl=24&pcm2=no&gcr=kh&initcwndbps=142500&vprv=1&mime=video%2Fwebm&gir=yes&clen=104592845&dur=262.999&lmt=1574974319215825&mt=1659016644&fvip=1&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&rbqsm=fr&txp=5535432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cpcm2%2Cgcr%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRgIhAJM89bkNaR-eaxNk99sqAHUdvDW4X-MRkR_R8wX0UJbYAiEAuU-yO8I-NIUDrBjIx1h1ZpKyMSTIzBb8BYdzt5oNpeU%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgDEXv8_pWmeC2zqhBsCDMRqgCyrQP1IKDZlV0R9iCv1ICIFzKVu6HgQN0eQcStkKAO7QwIAxPsByGLWiZlrON8v9N"
[download] Got server HTTP error: <urlopen error timed out>. Retrying (attempt 1 of 10) ...
[download] Got server HTTP error: <urlopen error timed out>. Retrying (attempt 2 of 10) ...
[download] Got server HTTP error: <urlopen error timed out>. Retrying (attempt 3 of 10) ...
[download] Got server HTTP error: <urlopen error timed out>. Retrying (attempt 4 of 10) ...
```

**Comment by pukkandan** [comment]
You are not using sponsorblock in the given log. Besides, this looks like a network issue

**Comment by Bonnary** [comment]
This is the command that I use. but my point is everything breaks after I use this even the normal download, yes I have read try my internet to the mobile hotspot but everything stay the same.

PS C:\Users\Bonnary\Music\English> yt-dlp -vU -x --audio-format mp3 --sponsorblock-remove all https://youtube.com/playlist?list=PLmqNpXXv9rUGru8ChIwHYe0vYpBEJBIcs
[debug] Command-line config: ['-vU', '-x', '--audio-format', 'mp3', '--sponsorblock-remove', 'all', 'https://youtube.com/playlist?list=PLmqNpXXv9rUGru8ChIwHYe0vYpBEJBIcs']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.07.18 [135f05e] (win32_exe)
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.22000-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 2022-07-06-git-03d81a044a-full_build-www.gyan.dev (setts), ffprobe 2022-07-06-git-03d81a044a-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.07.18, Current version: 2022.07.18
yt-dlp is up to date (2022.07.18)
[debug] [youtube:tab] Extracting URL: https://youtube.com/playlist?list=PLmqNpXXv9rUGru8ChIwHYe0vYpBEJBIcs
[youtube:tab] PLmqNpXXv9rUGru8ChIwHYe0vYpBEJBIcs: Downloading webpage
[debug] [youtube:tab] Final URL: https://www.youtube.com/playlist?list=PLmqNpXXv9rUGru8ChIwHYe0vYpBEJBIcs
[youtube:tab] PLmqNpXXv9rUGru8ChIwHYe0vYpBEJBIcs: Downloading API JSON with unavailable videos
[download] Downloading playlist: English music
[youtube:tab] PLmqNpXXv9rUGru8ChIwHYe0vYpBEJBIcs page 1: Downloading API JSON
[youtube:tab] Playlist English music: Downloading 180 videos of 180
[download] Downloading video 1 of 180
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=ZstsPUKT5CI
[youtube] ZstsPUKT5CI: Downloading webpage
[youtube] ZstsPUKT5CI: Downloading android player API JSON
[debug] [youtube] Extracting signature function js_c8b8a173_107
[debug] Loading youtube-sigfuncs.js_c8b8a173_107 from cache
[debug] Loading youtube-nsig.c8b8a173 from cache
[debug] [youtube] Decrypted nsig gijbT2YQnxRIiaGH => 3CwI-WYpxUh9Iw
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[SponsorBlock] Fetching SponsorBlock segments
[debug] SponsorBlock query: https://sponsor.ajay.app/api/skipSegments/ea21?service=YouTube&categories=%5B%22interaction%22%2C+%22outro%22%2C+%22selfpromo%22%2C+%22filler%22%2C+%22intro%22%2C+%22music_offtopic%22%2C+%22preview%22%2C+%22sponsor%22%5D&actionTypes=%5B%22skip%22%2C+%22poi%22%5D
[SponsorBlock] Found 2 segments in the SponsorBlock database
[info] ZstsPUKT5CI: Downloading 1 format(s): 251
[debug] Invoking http downloader on "https://rr6---sn-8pxuuxaj5hcvqp5-2oiz.googlevideo.com/videoplayback?expire=1659076055&ei=dynjYrW5EPO02roP0fGk2AM&ip=175.100.62.188&id=o-ADGto7gia9KPLeUI17VU4IJT2GgVMJ839lqw8LzDU0Kg&itag=251&source=youtube&requiressl=yes&mh=7K&mm=31%2C29&mn=sn-8pxuuxaj5hcvqp5-2oiz%2Csn-npoldn7e&ms=au%2Crdu&mv=m&mvi=6&pl=24&gcr=kh&initcwndbps=331250&vprv=1&mime=audio%2Fwebm&gir=yes&clen=4324115&dur=263.021&lmt=1574971047650691&mt=1659054052&fvip=1&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&d_tmro=no&txp=5531432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cgcr%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRAIgPqjEVlRnrjQzJvPh_1ju7xbeh-sRNjaePABNKPwGyYsCIGQrxLb7trt3_9y-e96VDy_taHleJtAS-eHvI_SnNsjK&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgJ4pMlKpnP_FnipCNWpuFIzv0NVmUfXIdeBbU01kK0xwCIQDc_wY6JgZ3c4roysmk5SMcqq2gHbGTmAfYAZQHlavtFQ%3D%3D"
[download] Got server HTTP error: <urlopen error timed out>. Retrying (attempt 1 of 10) ...

**Comment by eladkarako** [comment]
https://github.com/eladkarako/yt-dlp_kit/blob/master/yt-dlp_conf_base.conf#L80


I opt for using their dev server as a second alternative/fallback, and setting a shorter timeout for fail/re-try.

**Comment by Bonnary** [comment]
now I got it to work with VPN, but can't download a list of videos.

**Comment by pukkandan** [comment]
```
❯ yt-dlp -vU -x --audio-format mp3 --sponsorblock-remove all youtube.com/playlist?list=PLmqNpXXv9rUGru8ChIwHYe0vYpBEJBIcs
[debug] Command-line config: ['--ignore-config', '-vU', '-x', '--audio-format', 'mp3', '--sponsorblock-remove', 'all', 'youtube.com/playlist?list=PLmqNpXXv9rUGru8ChIwHYe0vYpBEJBIcs']
[debug] Encodings: locale cp65001, fs utf-8, pref cp65001, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.07.18 [135f05ef6] (source)
[debug] Lazy loading extractors is disabled
[debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
[debug] Git HEAD: 3df53810f
[debug] Python 3.10.5 (CPython 64bit) - Windows-10-10.0.22000-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg N-106550-g072101bd52-20220410 (fdk,setts), ffprobe N-106624-g391ce570c8-20220415, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.14.1, brotli-1.0.9, certifi-2021.10.08, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.1
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.07.18, Current version: 2022.07.18
yt-dlp is up to date (2022.07.18)
[debug] [youtube:playlist] Extracting URL: youtube.com/playlist?list=PLmqNpXXv9rUGru8ChIwHYe0vYpBEJBIcs
[debug] [youtube:tab] Extracting URL: https://www.youtube.com/playlist?list=PLmqNpXXv9rUGru8ChIwHYe0vYpBEJBIcs
[youtube:tab] PLmqNpXXv9rUGru8ChIwHYe0vYpBEJBIcs: Downloading webpage
[debug] [youtube:tab] Final URL: https://www.youtube.com/playlist?list=PLmqNpXXv9rUGru8ChIwHYe0vYpBEJBIcs
[youtube:tab] PLmqNpXXv9rUGru8ChIwHYe0vYpBEJBIcs: Downloading API JSON with unavailable videos
[download] Downloading playlist: English music
[youtube:tab] PLmqNpXXv9rUGru8ChIwHYe0vYpBEJBIcs page 1: Downloading API JSON
[youtube:tab] Playlist English music: Downloading 180 videos of 180
[download] Downloading video 1 of 180
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=ZstsPUKT5CI
[youtube] ZstsPUKT5CI: Downloading webpage
[youtube] ZstsPUKT5CI: Downloading android player API JSON
[debug] [youtube] Extracting signature function js_c8b8a173_107
[youtube] ZstsPUKT5CI: Downloading player c8b8a173
[debug] Saving youtube-sigfuncs.js_c8b8a173_107 to cache
[debug] Loading youtube-nsig.c8b8a173 from cache
[debug] [youtube] Decrypted nsig _j2Qe6KWojn5jlv- => dcHIRC4qaX-Wvg
[debug] [youtube] Extracting signature function js_c8b8a173_103
[debug] Saving youtube-sigfuncs.js_c8b8a173_103 to cache
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[SponsorBlock] Fetching SponsorBlock segments
[debug] SponsorBlock query: https://sponsor.ajay.app/api/skipSegments/ea21?service=YouTube&categories=%5B%22preview%22%2C+%22interaction%22%2C+%22intro%22%2C+%22outro%22%2C+%22selfpromo%22%2C+%22music_offtopic%22%2C+%22filler%22%2C+%22sponsor%22%5D&actionTypes=%5B%22skip%22%2C+%22poi%22%5D
[SponsorBlock] Found 2 segments in the SponsorBlock database
[info] ZstsPUKT5CI: Downloading 1 format(s): 251
[debug] Invoking http downloader on "https://rr1---sn-gwpa-jv36.googlevideo.com/videoplayback?expire=1659193249&ei=QfPkYpicGsOd4t4Ph5ii2AI&ip=49.37.230.6&id=o-AKr6zjD0gnvNFLJZS9MhShRe6TQ-53uzXNO5O9uwpXkh&itag=251&source=youtube&requiressl=yes&mh=7K&mm=31%2C29&mn=sn-gwpa-jv36%2Csn-gwpa-h55e7&ms=au%2Crdu&mv=m&mvi=1&pl=20&gcr=in&initcwndbps=315000&vprv=1&mime=audio%2Fwebm&gir=yes&clen=4324115&dur=263.021&lmt=1574971047650691&mt=1659171172&fvip=4&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&rbqsm=fr&txp=5531432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cgcr%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIhAPgGkUued8hhraA9IJ7uQcz0kKnb1gUajGtKJiY6gyu_AiBc3_6NRELSmTiZ5-jtF6Yy4TDwGu-TX4080Lg-XbixPA%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgSGp0C3yU2ipzY55PnEWp5f5tCoNir2xX4_RQzuNSsf0CICnFR6g8lR8Xlchx9SdzBkgb9dx9OlLk0eTd5lV3FPIc"
[debug] File locking is not supported. Proceeding without locking
[download] Destination: BENDY AND THE INK MACHINE SONG (Build Our Machine) LYRIC VIDEO - DAGames [ZstsPUKT5CI].webm
[download] 100% of 4.12MiB in 00:01
[debug] ffmpeg command line: ffprobe -show_streams "file:BENDY AND THE INK MACHINE SONG (Build Our Machine) LYRIC VIDEO - DAGames [ZstsPUKT5CI].webm"
[ExtractAudio] Destination: BENDY AND THE INK MACHINE SONG (Build Our Machine) LYRIC VIDEO - DAGames [ZstsPUKT5CI].mp3
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:BENDY AND THE INK MACHINE SONG (Build Our Machine) LYRIC VIDEO - DAGames [ZstsPUKT5CI].webm" -vn -acodec libmp3lame "-q:a" 5.0 -movflags "+faststart" "file:BENDY AND THE INK MACHINE SONG (Build Our Machine) LYRIC VIDEO - DAGames [ZstsPUKT5CI].mp3"
Deleting original file BENDY AND THE INK MACHINE SONG (Build Our Machine) LYRIC VIDEO - DAGames [ZstsPUKT5CI].webm (pass -k to keep)
[debug] ffprobe command line: ffprobe -hide_banner -show_format -show_streams -print_format json "file:BENDY AND THE INK MACHINE SONG (Build Our Machine) LYRIC VIDEO - DAGames [ZstsPUKT5CI].mp3"
[debug] Concat spec = 0.0-241.585940, 263.000000-inf
[ModifyChapters] Removing chapters from BENDY AND THE INK MACHINE SONG (Build Our Machine) LYRIC VIDEO - DAGames [ZstsPUKT5CI].mp3
[debug] Writing concat spec to BENDY AND THE INK MACHINE SONG (Build Our Machine) LYRIC VIDEO - DAGames [ZstsPUKT5CI].temp.mp3.concat
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -hide_banner -nostdin -f concat -safe 0 -i "file:BENDY AND THE INK MACHINE SONG (Build Our Machine) LYRIC VIDEO - DAGames [ZstsPUKT5CI].temp.mp3.concat" -map 0 -dn -ignore_unknown -c copy -movflags "+faststart" "file:BENDY AND THE INK MACHINE SONG (Build Our Machine) LYRIC VIDEO - DAGames [ZstsPUKT5CI].temp.mp3"
Deleting original file BENDY AND THE INK MACHINE SONG (Build Our Machine) LYRIC VIDEO - DAGames [ZstsPUKT5CI].uncut.mp3 (pass -k to keep)
[download] Downloading video 2 of 180
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=J61u3wFzl68
[youtube] J61u3wFzl68: Downloading webpage

ERROR: Interrupted by user
```
