### ISSUE TITLE
[instagram] "url" field is missing or empty - skipping format, there is an error in extractor

### ISSUE THREAD

**Issue by someziggyman** [yt-dlp/yt-dlp#4475]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.07.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Not sure if this is critical or not, but figured it need to be reported.

Test link:
https://www.instagram.com/p/CgH0HgMt7hg/

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
./yt-dlp -vU -F "https://www.instagram.com/p/CgH0HgMt7hg/"
[debug] Command-line config: ['-vU', '-F', 'https://www.instagram.com/p/CgH0HgMt7hg/']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.06.29 [9d339c41e] (zip)
[debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
[debug] Python 3.9.13 (CPython 64bit) - macOS-12.4-arm64-arm-64bit 
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: avconv -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: avprobe -bsfs
[debug] exe versions: none
[debug] Optional libraries: sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.07.18, Current version: 2022.06.29
[debug] Downloading _update_spec from https://github.com/yt-dlp/yt-dlp/releases/download/2022.07.18/_update_spec
Current Build Hash 2af833b5e770b0df2492c728d3c3e809a0ab221fd508b44610827255c5a8c8d1
Updating to version 2022.07.18 ...
[debug] Downloading yt-dlp from https://github.com/yt-dlp/yt-dlp/releases/download/2022.07.18/yt-dlp
[debug] Downloading SHA2-256SUMS from https://github.com/yt-dlp/yt-dlp/releases/download/2022.07.18/SHA2-256SUMS
Updated yt-dlp to version 2022.07.18
WARNING: Restart yt-dlp to use the updated version
[debug] [Instagram] Extracting URL: https://www.instagram.com/p/CgH0HgMt7hg/
[Instagram] CgH0HgMt7hg: Downloading JSON metadata
WARNING: [Instagram] CgH0HgMt7hg: General metadata extraction failed
[Instagram] CgH0HgMt7hg: Downloading video info
[Instagram] CgH0HgMt7hg: Downloading embed webpage
[download] Downloading playlist: <Untitled>
[Instagram] Playlist <Untitled>: Downloading 7 videos of 7
[download] Downloading video 1 of 7
[info] Available formats for CgHzApVjip4:
ID EXT RESOLUTION │ PROTO │ VCODEC  ACODEC
───────────────────────────────────────────
0  mp4 750x750    │ https │ unknown unknown
[download] Downloading video 2 of 7
WARNING: "url" field is missing or empty - skipping format, there is an error in extractor
CgHzLMNDqRt has no formats
[download] Downloading video 3 of 7
[info] Available formats for CgHzWWAji3i:
ID EXT RESOLUTION │ PROTO │ VCODEC  ACODEC
───────────────────────────────────────────
0  mp4 750x750    │ https │ unknown unknown
[download] Downloading video 4 of 7
[info] Available formats for CgHzcY9jO5K:
ID EXT RESOLUTION │ PROTO │ VCODEC  ACODEC
───────────────────────────────────────────
0  mp4 750x750    │ https │ unknown unknown
[download] Downloading video 5 of 7
[info] Available formats for CgHzqYMDPGL:
ID EXT RESOLUTION │ PROTO │ VCODEC  ACODEC
───────────────────────────────────────────
0  mp4 750x750    │ https │ unknown unknown
[download] Downloading video 6 of 7
[info] Available formats for CgHz3yuDAkc:
ID EXT RESOLUTION │ PROTO │ VCODEC  ACODEC
───────────────────────────────────────────
0  mp4 750x750    │ https │ unknown unknown
[download] Downloading video 7 of 7
[info] Available formats for CgH0Ci_DslF:
ID EXT RESOLUTION │ PROTO │ VCODEC  ACODEC
───────────────────────────────────────────
0  mp4 750x750    │ https │ unknown unknown
[download] Finished downloading playlist: <Untitled>
```

**Comment by bashonly** [comment]
> Latest version: 2022.07.18, Current version: 2022.06.29
> WARNING: Restart yt-dlp to use the updated version

**Comment by pritam20ps05** [comment]
Use cookies and report again as nothing can be said if you are not logged in. IG can totally restrict non logged in users too.

**Comment by pritam20ps05** [comment]
So looking into it I found that IG no longer shares codec data of videos. Btw check out this PR #4657 fixing error outputs.

**Comment by pritam20ps05** [comment]
Ok for that missing url its missing from their embed site only and seems like an exception. Its recomended to use cookies, this issue can now be closed

**Comment by pukkandan** [comment]
All 7 videos are playable in browser without cookies. So the bug report is valid

**Comment by pritam20ps05** [comment]
Yea but it's a bug with IG embeds and switching extraction from embeds to main webpage would cause other things to break. So I would see if can manage something but this might not get fixed
