### ISSUE TITLE
Can't download Instagram videos (I'm not using cookies)

### ISSUE THREAD

**Issue by holygamer** [yt-dlp/yt-dlp#4484]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.07.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

UK

### Provide a description that is worded well enough to be understood

I can't download Instagram videos such as this for example: https://www.instagram.com/p/CgGAHtyFoHg/?hl=en
The error message says "Unable to extract uploader ID.

This is my script:

```
@echo off
cd /D "%~dp0"
setlocal enableDelayedExpansion
yt-dlp -vU -U  
set /p video="Paste the video link to download: "
youtube-dl ^
-f ("bestvideo[width>=1920]"/bestvideo)+bestaudio/best --ignore-errors --merge-output-format mkv  --no-playlist ^
--output "F:/    USA Instagram %%(height)sp %%(vcodec)s %%(acodec)s FPS %%(fps)s.%%(ext)s" ^
!video!

PAUSE
```

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '-U']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8 (No VT), erro
r utf-8 (No VT), screen utf-8 (No VT)
[debug] yt-dlp version 2022.07.18 [135f05e] (win32_exe)
[debug] Python 3.8.10 (CPython 64bit) - Windows-7-6.1.7601-SP1
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg N-65018-gad91bf8 (needs_adtstoasc), ffprobe N-65018
-gad91bf8
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15,
 mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releas
es/latest
Latest version: 2022.07.18, Current version: 2022.07.18
yt-dlp is up to date (2022.07.18)
Paste the video link to download: https://www.instagram.com/p/CgGAHtyFoHg/?hl=en

[Instagram] CgGAHtyFoHg: Downloading webpage
WARNING: unable to extract uploader id; please report this issue on https://yt-d
l.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to
update. Be sure to call youtube-dl with the --verbose flag and include its compl
ete output.
ERROR: local variable 'title' referenced before assignment
Press any key to continue . . .
```

**Comment by pukkandan** [comment]
The -vU should be added to the actual download command, not ran separately!

**Comment by pukkandan** [comment]
```
❯ yt-dlp https://www.instagram.com/p/CgGAHtyFoHg/
[Instagram] CgGAHtyFoHg: Downloading JSON metadata
[Instagram] CgGAHtyFoHg: Downloading video info
[Instagram] CgGAHtyFoHg: Downloading embed webpage
[info] CgGAHtyFoHg: Downloading 1 format(s): 0
[download] Destination: Video by __jodiii__ [CgGAHtyFoHg].mp4
[download] 100% of 2.00MiB in 00:00
```

**Comment by holygamer** [comment]
I only did what your instructions said:
`yt-dlp -vU <your command line>`

If I didn't put it in the correct please can you please edit my script to show me where the -VU part goes.

Where you able to download the video then using my script? Why isn't it working for me?

**Comment by pukkandan** [comment]
> If I didn't put it in the correct place then can you please edit my script to show me where the -VU part goes.

No, just don't use any shell script. I am not going to debug your script for you.

---

First off, are you sure you have done this?
![image](https://user-images.githubusercontent.com/6623388/182028431-ca450508-90f2-4821-91c3-b14320e87496.png)
Since you aren't passing any login details to yt-dlp, this means trying to play the video in an incognito window

After you confirm that, run `yt-dlp -vU --write-page "URL"`, and attach the `.dump` files created alongside the complete console output

**Comment by bashonly** [comment]
the script is running `youtube-dl` not `yt-dlp`

**Comment by pukkandan** [comment]
damn! I didn't even notice coz of the verbose head above 😮‍💨
