### ISSUE TITLE
[Tubi] Extract audio language metadata if available.

### ISSUE THREAD

**Issue by antiops** [yt-dlp/yt-dlp#4488]
### Checklist

- [X] I'm requesting a site-specific feature
- [X] I've verified that I'm running yt-dlp version **2022.07.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

USA

## Film
English (Default, no language listed):
https://tubitv.com/movies/531743/yu-gi-oh-the-movie?start=true

Spanish: https://tubitv.com/movies/532867/una-familia-de-tantas?start=true
Swedish: https://tubitv.com/movies/475177/all-things-fair?start=true
Japanese: https://tubitv.com/movies/646274/the-legend-of-the-stardust-brothers?start=true
Chinese: https://tubitv.com/movies/522280/operation-mekong?start=true

## Show
English: https://tubitv.com/tv-shows/365497/s01-e01-the-heart-of-the-cards?start=true
Spanish: https://tubitv.com/tv-shows/520360/s01-e01-el-corazon-de-los-naipes?start=true

### Provide a description that is worded well enough to be understood

Currently yt-dlp sets the audio language metadata to English on any download from Tubi. On the video pages they include labels within the webpage for any media that is non-English and if there is no label then it is English (Default/No Label = English). There seems to be no other place than the webpage that mentions the language.

I've listed some links for different languages above, for both movies and shows. I've also noticed that some pages have multiple listed to be specific like:
`Chinese, Mandarin, Sanskrit` https://tubitv.com/movies/449366/extraordinary-mission?start=true

Not sure how or if this could be implemented but seeing as there was no open issue for it I thought I'd bring it up to see if there's a way to do it natively instead of the hacky way I'm getting it with xidel.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
# peepee@poopoo:[~]: ./yt-dlp_linux -vU https://tubitv.com/tv-shows/520360/s01-e01-el-corazon-de-los-naipes?start=true
[debug] Command-line config: ['-vU', 'https://tubitv.com/tv-shows/520360/s01-e01-el-corazon-de-los-naipes?start=true']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.07.18 [135f05e] (linux_exe)
[debug] Python 3.10.5 (CPython 64bit) - Linux-5.11.0-41-generic-x86_64-with-glibc2.33 (glibc 2.33)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.3.2-0, ffprobe 4.3.2-0, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, secretstorage-3.3.2, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.07.18, Current version: 2022.07.18
yt-dlp is up to date (2022.07.18)
[debug] Using fake IP 6.191.242.113 (US) as X-Forwarded-For
[debug] [TubiTv] Extracting URL: https://tubitv.com/tv-shows/520360/s01-e01-el-corazon-de-los-naipes?start=true
[TubiTv] 520360: Downloading JSON metadata
[TubiTv] 520360: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 520360: Downloading 1 format(s): 1406
[debug] Invoking hlsnative downloader on "https://manifest.production-public.tubi.io/e8ea92fa-9af7-4c12-876c-6c2758b65f53/un9bncei/stream.m3u8?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjZG5fcHJlZml4IjoiaHR0cHM6Ly9mYXN0bHkudHViaS52aWRlbyIsImNvdW50cnkiOiJVUyIsImRldmljZV9pZCI6IjNkMDk2NGE2LTUzNDctNDI1My05YTA1LThiODQzZDk2ZTY5MyIsImV4cCI6MTY1OTQxNDkwMCwicGxhdGZvcm0iOiJXRUIiLCJ1c2VyX2lkIjowfQ.G5FlgIrt1_GLsMPquA2EgvnaZvOdbcgS1hIhN0dqXVE&manifest=true"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 374
[download] Destination: S01 -E01 - El Corazon De Los Naipes! [520360].mp4
[download] 100% of 208.86MiB in 00:35
[debug] ffprobe command line: ffprobe -hide_banner -show_format -show_streams -print_format json 'file:S01 -E01 - El Corazon De Los Naipes! [520360].mp4'
[FixupM3u8] Fixing MPEG-TS in MP4 container of "S01 -E01 - El Corazon De Los Naipes! [520360].mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:S01 -E01 - El Corazon De Los Naipes! [520360].mp4' -map 0 -dn -ignore_unknown -c copy -f mp4 -bsf:a aac_adtstoasc -movflags +faststart 'file:S01 -E01 - El Corazon De Los Naipes! [520360].temp.mp4'


# peepee@poopoo:[~]: mediainfo "S01 -E01 - El Corazon De Los Naipes! [520360].mp4" | grep 'Language'
Language                                 : English
```

**Comment by pukkandan** [comment]
> On the video pages they include labels within the webpage for any media that is non-English and if there is no label then it is English

I don't see the labels. Could you show a screenshot?

**Comment by antiops** [comment]
Sorry for the late reply, it seems that since my original message they updated the site and removed the language label on the webpage. The only place I could find it was in the [page source](https://images2.imgbox.com/d8/1a/IfprA3gJ_o.png) but at that point it's not worth the trouble.

Not sure if it's a bug with the new design or whatever but if they ever properly display it on the page again I'll reopen the issue.
