### ISSUE TITLE
Why can some extractors return `filesize_approx` and some not?

### ISSUE THREAD

**Issue by ischmidt20** [yt-dlp/yt-dlp#4498]
### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.07.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I have recently moved to a new compute environment that requires me to limit the size of the files I download. I know yt-dlp has a "max filesize" option, however this was not working on some videos (particularly, my ESPN+ extractor). Digging deeper, I realized that my ESPN+ extractor does not return any information on filesize, whereas Paramount+ for example, does. I looked at the Paramount+ extractor (and its super classes), and didn't notice anything obvious that would tell it to look at file sizes. I checked the m3u8s from each service as well, and I cannot find a difference there either. What gives? yt-dlp being able to return any (approximate) file size information is very important for me.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
This is difficult to answer, especially since I don't have access to either of these services. If, as you say, the filesize are not in the manifest, it may be calculated as `tbr * duration`. Also, Paramount IE doesn't just get it's format info from the m3u8, but from the associated SMIL manifests. So maybe it contains the info

The short answer is just that ESPN probably doesn't provide tbr/filesize info. Or, if you find relevent data in the webpage, manifests or any API calls, let us know.

**Comment by ischmidt20** [comment]
Thanks, both extractors definitely return `tbr`, but maybe ESPN+ does not return duration? Verbose `-F` commands, first Paramount+:

```
yt-dlp -F https://www.paramountplus.com/shows/video/kaWvMpPYbGBFzNVASW8sT6JxB226Mwul/ -v
[debug] Command-line config: ['-F', 'https://www.paramountplus.com/shows/video/kaWvMpPYbGBFzNVASW8sT6JxB226Mwul/', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.07.18 [135f05e]
[debug] Python 3.9.13 (CPython 64bit) - macOS-12.5-arm64-arm-64bit 
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 5.1 (fdk,setts), ffprobe 5.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] [ParamountPlus] Extracting URL: https://www.paramountplus.com/shows/video/kaWvMpPYbGBFzNVASW8sT6JxB226Mwul/
[ParamountPlus] kaWvMpPYbGBFzNVASW8sT6JxB226Mwul: Downloading JSON metadata
[ParamountPlus] kaWvMpPYbGBFzNVASW8sT6JxB226Mwul: Downloading JSON metadata
[ParamountPlus] kaWvMpPYbGBFzNVASW8sT6JxB226Mwul: Downloading DASH_CENC_PRECON SMIL data
[ParamountPlus] kaWvMpPYbGBFzNVASW8sT6JxB226Mwul: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[info] Available formats for kaWvMpPYbGBFzNVASW8sT6JxB226Mwul:
ID       EXT RESOLUTION │   FILESIZE   TBR PROTO │ VCODEC        VBR ACODEC    ABR
──────────────────────────────────────────────────────────────────────────────────
hls-95   mp4 audio only │ ~ 69.74MiB   95k m3u8  │ audio only        mp4a.40.2 95k
hls-495  mp4 640x360    │ ~363.39MiB  495k m3u8  │ avc1.640028  495k mp4a.40.2  0k
hls-838  mp4 768x432    │ ~615.20MiB  838k m3u8  │ avc1.640028  838k mp4a.40.2  0k
hls-1616 mp4 960x540    │ ~  1.16GiB 1616k m3u8  │ avc1.640028 1616k mp4a.40.2  0k
hls-2214 mp4 1024x576   │ ~  1.59GiB 2214k m3u8  │ avc1.640028 2214k mp4a.40.2  0k
hls-3112 mp4 1280x720   │ ~  2.23GiB 3112k m3u8  │ avc1.640028 3112k mp4a.40.2  0k
hls-4610 mp4 1280x720   │ ~  3.31GiB 4610k m3u8  │ avc1.640028 4610k mp4a.40.2  0k
```

And ESPN+:

```
yt-dlp -F https://www.espn.com/watch/player/_/id/f9230b4a-2beb-43c5-84f2-a4a09cf73547 --cookies espn.com_cookies.txt -v
[debug] Command-line config: ['-F', 'https://www.espn.com/watch/player/_/id/f9230b4a-2beb-43c5-84f2-a4a09cf73547', '--cookies', 'espn.com_cookies.txt', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.07.18 [135f05e]
[debug] Python 3.9.13 (CPython 64bit) - macOS-12.5-arm64-arm-64bit 
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 5.1 (fdk,setts), ffprobe 5.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] [WatchESPN] Extracting URL: https://www.espn.com/watch/player/_/id/f9230b4a-2beb-43c5-84f2-a4a09cf73547
[WatchESPN] f9230b4a-2beb-43c5-84f2-a4a09cf73547: Downloading JSON metadata
[WatchESPN] f9230b4a-2beb-43c5-84f2-a4a09cf73547: Downloading JSON metadata
[WatchESPN] f9230b4a-2beb-43c5-84f2-a4a09cf73547: Downloading JSON metadata
[WatchESPN] f9230b4a-2beb-43c5-84f2-a4a09cf73547: Downloading JSON metadata
[WatchESPN] f9230b4a-2beb-43c5-84f2-a4a09cf73547: Downloading JSON metadata
[WatchESPN] f9230b4a-2beb-43c5-84f2-a4a09cf73547: Downloading JSON metadata
[WatchESPN] f9230b4a-2beb-43c5-84f2-a4a09cf73547: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[info] Available formats for f9230b4a-2beb-43c5-84f2-a4a09cf73547:
ID       EXT RESOLUTION FPS │   TBR PROTO │ VCODEC        VBR ACODEC    ABR
───────────────────────────────────────────────────────────────────────────
hls-250  mp4 320x180     30 │  250k m3u8  │ avc1.4d001f  250k mp4a.40.2  0k
hls-550  mp4 384x216     30 │  550k m3u8  │ avc1.4d001f  550k mp4a.40.2  0k
hls-1000 mp4 512x288     30 │ 1000k m3u8  │ avc1.4d001f 1000k mp4a.40.2  0k
hls-1420 mp4 640x360     30 │ 1420k m3u8  │ avc1.4d001f 1420k mp4a.40.2  0k
hls-2150 mp4 896x504     30 │ 2150k m3u8  │ avc1.4d001f 2150k mp4a.40.2  0k
hls-2980 mp4 960x540     30 │ 2980k m3u8  │ avc1.4d0020 2980k mp4a.40.2  0k
hls-4190 mp4 1280x720    30 │ 4190k m3u8  │ avc1.640028 4190k mp4a.40.2  0k
hls-6600 mp4 1280x720    60 │ 6600k m3u8  │ avc1.640028 6600k mp4a.40.2  0k
hls-8250 mp4 1280x720    60 │ 8250k m3u8  │ avc1.640028 8250k mp4a.40.2  0k
```

ESPN+ definitely has a duration floating around in the APIs somewhere that I can reference. I'll toy around and see if adding that fixes the issue, and if it does, submit a pull request

**Comment by pukkandan** [comment]
>  but maybe ESPN+ does not return duration?

You can check with `yt-dlp -O duration "URL"`

**Comment by ischmidt20** [comment]
I figured it didn't because I didn't include it in the extractor, but yes, that prints `NA`

**Comment by pukkandan** [comment]
Note that the filesize calculated from tbr is often wildly inaccurate since many sites give peak tbr and not average tbr

**Comment by ischmidt20** [comment]
> Note that the filesize calculated from tbr is often wildly inaccurate since many sites give peak tbr and not average tbr

I understand, but the approximate filesize is still better than nothing. My use case is really to pick better or worse formats depending on the filesize (and ESPN+ seems to have consistent bitrates across videos, so really this is just a function of duration).

This is delving away from the original question I asked, so I just want to make sure the following is correct before I close this issue:

1. If the returned URL is a direct mp4 link, then yt-dlp reports the filesize exactly.
2. If the returned URL is an hls/dash manifest, and the formats include size information (or that information is found somewhere else in the API for the service), yt-dlp reports those filesizes.
3. If the URL is a manifest, but does not include any size information, then yt-dlp estimates the filesize as `tbr * duration`, and returns that.
4. If either or both of `tbr` or `duration` is not included in the manifest or returned by the extractor, then no filesize is reported by yt-dlp.

I don't think this information exists anywhere else, hence the question

**Comment by pukkandan** [comment]
(1) is not true. Even for manifest-less video, the filesize has to come from some API

**Comment by ischmidt20** [comment]
Thanks, noted. Is the updated sequence correct?

**Comment by pukkandan** [comment]
yes

**Comment by ischmidt20** [comment]
Cheers, thanks for the quick clarifications. It may be worth updating the documentation with some of this, as currently it does not describe when exactly `filesize` vs `filesize_approx` is returned, or when we get neither.

**Comment by pukkandan** [comment]
The same applies for all fields though... The field is returned if either present in API or can be computed from other fields

**Comment by pukkandan** [comment]
It is not feasible to document the exact mechanism for computing each field
