### ISSUE TITLE
[Feature request] download from shahid vip 

### ISSUE THREAD

**Issue by hossam1111199** [yt-dlp/yt-dlp#450]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running yt-dlp version **2021.06.23**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description

cant download from shahid I have my subscription VIP and program says this content is for vip user only

**Comment by pukkandan** [comment]
Provide more information including verbose log and example URLs
