### ISSUE TITLE
-start flag record from a given time

### ISSUE THREAD

**Issue by danielehrhardt** [yt-dlp/yt-dlp#4503]
### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.07.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

it would be nice to see a feature like this:

Parameter:
-start 

Features:
[-start=[YYYYMMDD:hhmm], -start=[YYYYMMDD:hhmmss]]
[-start=[Y:hhmm], -start=[Y:hhmmss]]
[-start=[T:hhmm], -start=[T:hhmmss]]
[-start=beginning, -start=b]
[-start=live, -start=l]
[-start=-[minutes]]
[-start=+[minutes]]

This parameter specifies the point in time from which to save the stream. It's calculated relative to the moment the program was started (displayed in the first line). If the parameter is missing, program saves ongoing livestream in real time, scheduled and finished - from the beginning. Depending on technical parameters of the livestream, start point may be shifted from the requested one by several seconds (in a larger direction).

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by gamer191** [comment]
Doesn't `--download-sections` already do that?

**Comment by danielehrhardt** [comment]
> Is there a reason why `--download-sections` doesn't meet your needs?

Not really because i want to record a LiveStream, and the recording should continue if it is live. So for example, the Livestream is running for 10 hours. My Recording will start -5 hours and will continue after i interrupt or the live stream ends.

**Comment by pukkandan** [comment]
I don't understand. Could you explain more, possibly with an example

**Comment by Friskygote** [comment]
Isn't it #3451?

**Comment by danielehrhardt** [comment]
> I don't understand. Could you explain more, possibly with an example

These examples are for Live Streams:
To rewind the livestream or delay the start of recording, use the `-start` parameter. It has several spellings:

##### [**` -start=[YYYYMMDD:hhmm], -start=[YYYYMMDD:hhmmss] `**](#)
##### [**` -start=[Y:hhmm], -start=[Y:hhmmss] `**](#)
##### [**` -start=[T:hhmm], -start=[T:hhmmss] `**](#)
##### [**` -start=beginning, -start=b `**](#)
##### [**` -start=-[minutes] `**](#)
##### [**` -start=+[minutes] `**](#)

This parameter specifies the point in time from which to save the stream. It's calculated relative to the moment the program was started (displayed in the first line). If the parameter is missing, program saves ongoing livestream in real time, scheduled and finished - from the beginning. Depending on technical parameters of the livestream, start point may be shifted from the requested one by several seconds (in a larger direction).

To download the time interval from 7:10AM to 8:10AM on July 15, 2020:
>     yt-dlp https://www.youtube.com/watch?v=9Auq9mYxFEE -start=20200715:0710

To download the time interval from yesterday 10:15PM to 11:15PM:
>     yt-dlp https://www.youtube.com/watch?v=9Auq9mYxFEE -start=Y:2215

To download the time interval from today 02:00AM to 03:00AM:
>     yt-dlp https://www.youtube.com/watch?v=9Auq9mYxFEE -start=T:020000

To download from the first currently available moment:
>     yt-dlp https://www.youtube.com/watch?v=9Auq9mYxFEE -start=beginning

To download the time interval from 3 hours ago to 2 hours ago:
>     yt-dlp https://www.youtube.com/watch?v=9Auq9mYxFEE -start=-180

To wait 2 hours, then record for 1 hour:
>     yt-dlp https://www.youtube.com/watch?v=9Auq9mYxFEE -start=+120

**Comment by pukkandan** [comment]
You are asking for a few distinct features under the guise of one option. 

1. Delayed start of download

yt-dlp is not an "all in one" program suite. Why not have a script to wait till the given time and then run yt-dlp? In windows, it would be like `timeout 100 && yt-dlp "URL"`

2. Download from the past

This needs to be implemented for each site. For youtube, see #3451

3. Download for x hours

`--download-sections`

**Comment by danielehrhardt** [comment]
> You are asking for a few distinct features under the guise of one option.
> 
> 1. Delayed start of download
> 
> yt-dlp is not an "all in one" program suite. Why not have a script to wait till the given time and then run yt-dlp? In windows, it would be like `timeout 100 && yt-dlp "URL"`
> 
> 2. Download from the past
> 
> This needs to be implemented for each site. For youtube, see #3451
> 
> 3. Download for x hours
> 
> `--download-sections`

I think the most important Feature would be #3451 
Ok thank you.
