### ISSUE TITLE
[feature] youtube-dl wrapper around yt-dlp

### ISSUE THREAD

**Issue by pirate486743186** [yt-dlp/yt-dlp#4505]
### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.07.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

They are a bunch of legacy applications that are hard coded to use youtube-dl. A wrapper around yt-dlp would allow them to use it.

Some thing like this:
```
#!/usr/bin/python3

import sys
from yt_dlp import *

if __name__ == "__main__":

    args=sys.argv.copy()
    args.pop(0)
    args=['--compat-options','youtube-dl']+args

    main(args)
```

This acts as a module pretending to be youtube_dl and also as the executable youtube-dl. It was tested with mpv(as an executable) and fapy (as a module). In theory, it should work with almost all applications that need it. The wrapper should stay relevant for a few years.

Because this would conflict with the real youtube-dl, it should be hidden out of path of binaries and python modules. Interested users would create symlinks appropriately named to the appropriate locations.

In my system:
```
/usr/local/bin/youtube-dl
/usr/local/lib/python3.9/dist-packages/youtube_dl.py
```

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
Feel free to create a separate package that does this. I will not maintain/distribute it
