### ISSUE TITLE
match-filter fields not always available

### ISSUE THREAD

**Issue by chapmanjacobd** [yt-dlp/yt-dlp#4508]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.07.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

I would like a flag to skip match-filter expression parsing for any fields not available in the extractor

maybe something like:

- `--ignore-missing-fields`
- `--match-filter-ignore-missing`

Sorry I shoulda used the feature request template but my understanding of this issue has evolved after submitting the report

```
$ yt-dlp -j https://www.youtube.com/watch?v=1Nqyz0a6e7s | jq | grep -i live
  ...
  "is_live": false,
  "was_live": false,
  "live_status": "not_live",
  ...
```
great!

```
$ yt-dlp -j https://www.nfb.ca/film/qimmiq-canadas-arctic-dog/ | jq | grep -i live
598 1.7s [0|0|1] $
```
ugh :/

This makes match-filter skip URLs where the extractor or website has not implemented live-streaming.

```
--match-filter "duration > 59 & duration < 14399 & !is_live & !was_live"
```

The same argument could be made for extractors which don't implement the `duration` field... I am not sure if an extractor like that exists but if so perhaps a complete solution here would be to have a flag to skip undefined fields from the match-filter expression parsing.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp -v --match-filter "duration > 59 & duration < 14399 & !is_live & !was_l
ive" https://www.nfb.ca/film/qimmiq-canadas-arctic-dog/
[debug] Command-line config: ['-v', '--match-filter', 'duration > 59 & duration < 14399 & !is_live & !was_live', 'https://www.nfb.ca/film/qimmiq-canadas-arctic-dog/']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.07.18 [135f05e]
[debug] Python 3.10.5 (CPython 64bit) - Linux-5.18.13-200.fc36.x86_64-x86_64-with-glibc2.35 (glibc 2.35)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 5.0.1 (setts), ffprobe 5.0.1, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, secretstorage-3.3.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] [NFB] Extracting URL: https://www.nfb.ca/film/qimmiq-canadas-arctic-dog/
[NFB] qimmiq-canadas-arctic-dog: Downloading webpage
[NFB] qimmiq-canadas-arctic-dog: Downloading webpage
[NFB] qimmiq-canadas-arctic-dog: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[download] Qimmiq: Canada's Arctic Dog does not pass filter (duration > 59 & duration < 14399 & !is_live & !was_live), skipping ..
```

**Comment by chapmanjacobd** [comment]
Looks like this should work:

```
--match-filter "duration > 59 & duration < 14399 & extractor_key != 'Youtube'" \
--match-filter "duration > 59 & duration < 14399 & !is_live & !was_live"
```

**Comment by chapmanjacobd** [comment]
big oof. NFB is missing the duration as well field lol

```
$ yt-dlp -j https://www.nfb.ca/film/qimmiq-canadas-arctic-dog/ | jq | grep -i duration
623 1.5s [0|0|1]🥨 
```

**Comment by pukkandan** [comment]
![image](https://user-images.githubusercontent.com/6623388/182034538-9ce25500-0344-42f1-abda-93d13528fb22.png)

**Comment by chapmanjacobd** [comment]
for boolean should it be `!?is_live` or `!is_live?` or is that not supported?
