### ISSUE TITLE
WatchESPN plugin fails with "Unable to extract post url"

### ISSUE THREAD

**Issue by MatthewWest** [yt-dlp/yt-dlp#4511]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.07.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United States

### Provide a description that is worded well enough to be understood

The WatchESPN functionality with the `--ap-mso` flag and login information doesn't seem to work. It fails with the error "Unable to extract post url", and an instruction to report an issue.

I imagine the WatchESPN plugin needs to be updated to handle a site change.

I don't have a proposed solution because I don't understand the yt-dlp architecture well enough to propose a solution.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--ap-mso', 'DTV', '--ap-username', 'PRIVATE', '--ap-password', 'PRIVATE', 'https://www.espn.com/watch/player/_/id/55a598f5-7e07-4e81-86bf-cf71e0c3a172']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.07.18 [135f05e]
[debug] Python 3.10.5 (CPython 64bit) - macOS-12.5-arm64-arm-64bit
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 5.1 (setts), ffprobe 5.1
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.07.18, Current version: 2022.07.18
yt-dlp is up to date (2022.07.18)
[debug] [WatchESPN] Extracting URL: https://www.espn.com/watch/player/_/id/55a598f5-7e07-4e81-86bf-cf71e0c3a172
[WatchESPN] 55a598f5-7e07-4e81-86bf-cf71e0c3a172: Downloading JSON metadata
[WatchESPN] 55a598f5-7e07-4e81-86bf-cf71e0c3a172: Downloading Provider Redirect Page
[WatchESPN] 55a598f5-7e07-4e81-86bf-cf71e0c3a172: Downloading Provider Login Page
ERROR: [WatchESPN] 55a598f5-7e07-4e81-86bf-cf71e0c3a172: Unable to extract post url; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/opt/homebrew/Cellar/yt-dlp/2022.7.18/libexec/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 644, in extract
    ie_result = self._real_extract(url)
  File "/opt/homebrew/Cellar/yt-dlp/2022.7.18/libexec/lib/python3.10/site-packages/yt_dlp/extractor/espn.py", line 390, in _real_extract
    auth = self._extract_mvpd_auth(url, video_id, 'ESPN', resource).encode()
  File "/opt/homebrew/Cellar/yt-dlp/2022.7.18/libexec/lib/python3.10/site-packages/yt_dlp/extractor/adobepass.py", line 1710, in _extract_mvpd_auth
    mvpd_confirm_page_res = post_form(provider_login_page_res, 'Logging in', form_data)
  File "/opt/homebrew/Cellar/yt-dlp/2022.7.18/libexec/lib/python3.10/site-packages/yt_dlp/extractor/adobepass.py", line 1390, in post_form
    post_url = self._html_search_regex(r'<form[^>]+action=(["\'])(?P<url>.+?)\1', form_page, 'post url', group='url')
  File "/opt/homebrew/Cellar/yt-dlp/2022.7.18/libexec/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 1230, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/opt/homebrew/Cellar/yt-dlp/2022.7.18/libexec/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 1194, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
```

**Comment by pukkandan** [comment]
DTV support is broken. See pinned issues
