### ISSUE TITLE
Yandex.Music: High quality mode support

### ISSUE THREAD

**Issue by TheAndrey** [yt-dlp/yt-dlp#4512]
### Checklist

- [X] I'm requesting a site-specific feature
- [X] I've verified that I'm running yt-dlp version **2022.07.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Example URLs

https://music.yandex.ru/album/22958040/track/105364767

### Provide a description that is worded well enough to be understood

Please add the ability to download tracks in high quality (320 kbps instead of 128). I don't know much about Python and I can't offer PR myself.
Experimentally, I found out that it is enough to add a GET parameter `hq=1` [to this request](https://github.com/yt-dlp/yt-dlp/blob/master/yt_dlp/extractor/yandexmusic.py#L117) so that the service returns a link to the track in high quality.

> **NOTE:** High Quality mode is available only if you have an active subscription. Otherwise, the request parameter is ignored.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
Absent
```

**Comment by pukkandan** [comment]
```diff
             'https://music.yandex.ru/api/v2.1/handlers/track/%s:%s/web-album_track-track-track-main/download/m' % (track_id, album_id),
-            track_id, 'Downloading track location url JSON',
+            track_id, 'Downloading track location url JSON', query={'hq': 1},
```

If your finding is correct, this change should be sufficient

**Comment by TheAndrey** [comment]
I'm checked the file download and format selection.
```
$ yt-dlp --cookies-from-browser chrome -F https://music.yandex.ru/album/22958040/track/105364767
[Cookies] Extracting cookies from chrome
[Cookies] Loading cookie      0/90
[Cookies] Extracted 87 cookies from chrome (3 could not be decrypted)
[yandexmusic:track] 105364767: Downloading track JSON
[yandexmusic:track] 105364767: Downloading track location url JSON
[yandexmusic:track] 105364767: Downloading track location JSON
[info] Available formats for 105364767:
ID EXT RESOLUTION │ FILESIZE PROTO │ VCODEC  ACODEC  ABR
────────────────────────────────────────────────────────
0  mp3 unknown    │    0.00B http  │ unknown mp3    320k  <--
```

**Comment by pukkandan** [comment]
and what happens if you didn't pass cookies?

**Comment by TheAndrey** [comment]
Without logging in to the account (with cookies), the service returns as 128 kbps.
