### ISSUE TITLE
[afreecatv] age-restricted videos do not extract even with cookies

### ISSUE THREAD

**Issue by Zythrickal** [yt-dlp/yt-dlp#4514]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.07.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Australia

### Provide a description that is worded well enough to be understood

VODs that are age restricted do not download correctly, showing the message "Unable to extract station".

Previously, the `--cookies` argument had to be used to download age restricted videos but the above message is returned with and without `--cookies` on 2022.07.18.

```
yt-dlp -vU --cookies "C:\scripts\cookies.txt" https://vod.afreecatv.com/player/70395877
```

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
C:\Windows>yt-dlp -vU --cookies "C:\scripts\cookies.txt" https://vod.afreecatv.com/player/70395877
[debug] Command-line config: ['-vU', '--cookies', 'C:\\scripts\\cookies.txt', 'https://vod.afreecatv.com/player/70395877']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.07.18 [135f05e] (win32_exe)
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.4-full_build-www.gyan.dev (setts), ffprobe 4.4-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.07.18, Current version: 2022.07.18
yt-dlp is up to date (2022.07.18)
[debug] [afreecatv] Extracting URL: https://vod.afreecatv.com/player/70395877
[afreecatv] 70395877: Downloading webpage
ERROR: [afreecatv] 70395877: Unable to extract station; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 644, in extract
  File "yt_dlp\extractor\afreecatv.py", line 232, in _real_extract
  File "yt_dlp\extractor\common.py", line 1194, in _search_regex


C:\Windows>
```

**Comment by Zythrickal** [comment]
Still occurring on 2022.11.11

```
C:\Scripts>yt-dlp -vU --cookies "C:\scripts\cookies.txt" https://vod.afreecatv.com/player/70395877
[debug] Command-line config: ['-vU', '--cookies', 'C:\\scripts\\cookies.txt', 'https://vod.afreecatv.com/player/70395877']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.11.11 [8b64402] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19043-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 4.4-full_build-www.gyan.dev (setts), ffprobe 4.4-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1723 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.11.11, Current version: 2022.11.11
yt-dlp is up to date (2022.11.11)
[debug] [afreecatv] Extracting URL: https://vod.afreecatv.com/player/70395877
[afreecatv] 70395877: Downloading webpage
ERROR: [afreecatv] 70395877: Unable to extract station; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 674, in extract
  File "yt_dlp\extractor\afreecatv.py", line 232, in _real_extract
  File "yt_dlp\extractor\common.py", line 1228, in _search_regex


C:\Scripts>
```

I'm not all that knowledgeable about python but all the information seems to be there so i'm not quite sure why this isn't working?

Here's what I've found out...

this code

```python
        station_id = self._search_regex(
            r'nStationNo\s*=\s*(\d+)', webpage, 'station')
```

is looking at the page source for "nStationNo", which is there?

![image](https://user-images.githubusercontent.com/98439027/201588623-8724584a-7953-42b9-86de-da8b7ea4e624.png)

and the regex (not a master of regex, although who is right?) pulls out the station_id using the regex that worked on regex101.com (unlike python regex works differently?)

![image](https://user-images.githubusercontent.com/98439027/201588961-6930ad7c-5338-42a9-991e-f72db6319699.png)

but for reasons that still elude me, the regex fails (fatally), which gets to this code and displays the message shown in the console:

```python
        elif fatal:
            raise RegexNotFoundError('Unable to extract %s' % _name)
```

**Comment by flashdagger** [comment]
I exported my cookies from Chrome and could download the video. 
Could you please check your cookie file?

```
# Netscape HTTP Cookie File
# This file is generated by yt-dlp.  Do not edit.

.afreecatv.com	TRUE	/	FALSE	0	AbroadChk	OK
.afreecatv.com	TRUE	/	FALSE	1668428065	AbroadVod	OK
.afreecatv.com	TRUE	/	FALSE	0	PdboxBbs	[...]
.afreecatv.com	TRUE	/	FALSE	0	PdboxTicket	[...]
.afreecatv.com	TRUE	/	FALSE	0	PdboxUser	[...]
.afreecatv.com	TRUE	/	FALSE	0	RDB	[...]
.afreecatv.com	TRUE	/	FALSE	1668420921	TempCook	[...]
.afreecatv.com	TRUE	/	FALSE	1702977265	_au	[...]
.afreecatv.com	TRUE	/	FALSE	1668419785	_ausa	0xdeadbeef
.afreecatv.com	TRUE	/	FALSE	1668421285	_ausb	0xdeadbeef
.afreecatv.com	TRUE	/	FALSE	0	isBbs	1
vod.afreecatv.com	FALSE	/	FALSE	1669022234	ChatArea	off
```

The `Pdbox` session cookies with expire=0 are mandatory. Though they will not be used with `--cookies-from-browser`.
