### ISSUE TITLE
[Facebook] Extracted video metadata is incorrect (upload_date, uploader, description)

### ISSUE THREAD

**Issue by jblaufuss** [yt-dlp/yt-dlp#453]
## Checklist

- [X] I'm reporting a broken site support
- [X] I've verified that I'm running yt-dlp version **2021.06.23**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
$ yt-dlp --format "best[vcodec^=avc1][height=720]/best[vcodec^=avc1]/best" --verbose --force-ipv4 --sleep-interval 15 --max-sleep-interval 60 --ignore-errors --no-continue --no-overwrites --add-metadata --write-description --write-info-json --write-annotations --write-thumbnail --all-subs --sub-format "srt" --restrict-filenames --output "%(upload_date)s-%(title).75s-[%(id)s]/%(upload_date)s-[%(id)s]-%(title).20s.%(ext)s" --merge-output-format "mkv" -r 2M https://www.facebook.com/100043972247152/videos/519006262132020
[debug] Command-line config: ['--format', 'best[vcodec^=avc1][height=720]/best[vcodec^=avc1]/best', '--verbose', '--force-ipv4', '--sleep-interval', '15', '--max-sleep-interval', '60', '--ignore-errors', '--no-continue', '--no-overwrites', '--add-metadata', '--write-description', '--write-info-json', '--write-annotations', '--write-thumbnail', '--all-subs', '--sub-format', 'srt', '--restrict-filenames', '--output', '%(upload_date)s-%(title).75s-[%(id)s]/%(upload_date)s-[%(id)s]-%(title).20s.%(ext)s', '--merge-output-format', 'mkv', '-r', '2M', 'https://www.facebook.com/100043972247152/videos/519006262132020']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] yt-dlp version 2021.06.23
[debug] Python version 3.7.9 (CPython 64bit) - FreeBSD-11.4-RELEASE-p3-amd64-64bit-ELF
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1
[debug] Proxy map: {}
[debug] [facebook] Extracting URL: https://www.facebook.com/100043972247152/videos/519006262132020
[facebook] 519006262132020: Downloading webpage
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Downloading subtitles: en
[info] 519006262132020: Downloading 1 format(s): dash_hd_src
WARNING: There's no description to write.
WARNING: There are no annotations to write.
[info] Writing video subtitles to: 20210624-Amazing_Rocket_Takeoff_from_St_Maarten_SXM_for_this_KLM_Royal_Dutch_Airline-[519006262132020]/20210624-[519006262132020]-Amazing_Rocket_Takeo.en.srt
[debug] Invoking downloader on "https://scontent.ffcm1-1.fna.fbcdn.net/v/t39.2093-6/206186223_518939896134759_8625291978557424939_n.srt?_nc_cat=109&ccb=1-3&_nc_sid=bf5691&_nc_ohc=asV4z3cyNbMAX_oQEnJ&_nc_ht=scontent.ffcm1-1.fna&oh=8c6f76016b6ebae60e77da3f9f96dfdf&oe=60DEC57A"
[download] Destination: 20210624-Amazing_Rocket_Takeoff_from_St_Maarten_SXM_for_this_KLM_Royal_Dutch_Airline-[519006262132020]/20210624-[519006262132020]-Amazing_Rocket_Takeo.en.srt
[download] 100% of 1.71KiB in 00:00
[info] Writing video metadata as JSON to: 20210624-Amazing_Rocket_Takeoff_from_St_Maarten_SXM_for_this_KLM_Royal_Dutch_Airline-[519006262132020]/20210624-[519006262132020]-Amazing_Rocket_Takeo.info.json
[facebook] 519006262132020: Downloading thumbnail  ...
[facebook] 519006262132020: Writing thumbnail to: 20210624-Amazing_Rocket_Takeoff_from_St_Maarten_SXM_for_this_KLM_Royal_Dutch_Airline-[519006262132020]/20210624-[519006262132020]-Amazing_Rocket_Takeo.jpg
[debug] Invoking downloader on "https://scontent.ffcm1-2.fna.fbcdn.net/v/t66.36240-6/10000000_100499385575059_812033675567113067_n.mp4?_nc_cat=106&ccb=1-3&_nc_sid=985c63&efg=eyJ2ZW5jb2RlX3RhZyI6Im9lcF9oZCJ9&_nc_ohc=BIyDsfDRBq4AX9PP3xo&_nc_ht=scontent.ffcm1-2.fna&oh=1c29c18f3006da076f56f9068906dcc1&oe=60DF17FC"
[download] Sleeping 23.19 seconds ...
[download] Destination: 20210624-Amazing_Rocket_Takeoff_from_St_Maarten_SXM_for_this_KLM_Royal_Dutch_Airline-[519006262132020]/20210624-[519006262132020]-Amazing_Rocket_Takeo.mp4
[download] 100% of 53.99MiB in 00:27
[Metadata] Adding metadata to '20210624-Amazing_Rocket_Takeoff_from_St_Maarten_SXM_for_this_KLM_Royal_Dutch_Airline-[519006262132020]/20210624-[519006262132020]-Amazing_Rocket_Takeo.mp4'
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:20210624-Amazing_Rocket_Takeoff_from_St_Maarten_SXM_for_this_KLM_Royal_Dutch_Airline-[519006262132020]/20210624-[519006262132020]-Amazing_Rocket_Takeo.mp4' -map 0 -dn -c copy -metadata 'title=Amazing Rocket Takeoff from St Maarten SXM for this KLM Royal Dutch Airlines ...' -metadata date=20210624 -metadata purl=https://www.facebook.com/100043972247152/videos/519006262132020 -metadata comment=https://www.facebook.com/100043972247152/videos/519006262132020 -metadata 'artist=AMAZING! Rocket Takeoff at St Maarten' 'file:20210624-Amazing_Rocket_Takeoff_from_St_Maarten_SXM_for_this_KLM_Royal_Dutch_Airline-[519006262132020]/20210624-[519006262132020]-Amazing_Rocket_Takeo.temp.mp4'
$

```

## Description

I've also submitted this to the youtube-dl project, which has the same issue: https://github.com/ytdl-org/youtube-dl/issues/29421.  The below description and logs have been updated in this issue for yt-dlp.

The video metadata that yt-dlp is extracting for a Facebook video is incorrect:
* upload_date (this appears to be getting pulled from a related video suggestion in some cases, instead of the video being downloaded)
* uploader (this is sometimes a truncation of the video title or description)
* description (this doesn't seem to be getting set at all, even through it could, it appears that sometimes a truncated form of the description text is used for the title).

Example Video URL: https://www.facebook.com/100043972247152/videos/519006262132020

The date that displays with the video is March 22, 2020:
![image](https://user-images.githubusercontent.com/12689535/123584025-45c4cb00-d7a6-11eb-8327-4a4a89732249.png)

However, the `upload_date` in the metadata and in the file names is June 24, 2021: ```"upload_date": "20210624"```.  As far as I can tell the correct date of March 22, 2020 appears no where in the metadata:

[20210624-[519006262132020]-Amazing_Rocket_Takeo.info.json.txt](https://github.com/yt-dlp/yt-dlp/files/6727873/20210624-.519006262132020.-Amazing_Rocket_Takeo.info.json.txt)

The correct date from the page should be used for the filenames and metadata.

It looks like the problem is that it's incorrectly pulling the date off of a related video suggestion:

![image](https://user-images.githubusercontent.com/12689535/123588168-fcc44500-d7ac-11eb-8c2b-85965fe4f681.png)

Here's the HTML for the highlighted element:
```
<div class="_50f8">145K views  · <abbr data-utime="1624555814" title="Thursday, June 24, 2021 at 10:30 AM"><span class="timestampContent">June 24</span></abbr></div>
```

`data-utime="1624555814"` from the HTML == `"timestamp": 1624555814` from the yt-dlp JSON metadata.

It's also extracting the uploader incorrectly, and using part of the title instead. From the screenshots it looks like it should be "Noel Philips" but in the json metadata it's: `"uploader": "AMAZING! Rocket Takeoff at St Maarten"`

https://jdownloader.org/ appears to be able to extract the upload date and uploader name for these videos correctly and reliably, I don't know if a fix for this issue can be cribbed from there.

**Comment by pukkandan** [comment]
Sorry, didnt mean to close this. Only the title and description issues have been fixed

- [ ] Wrong timestamp (takes from related vids)
- [ ] uploader is not extracted and title is used instead
- [x] ~~description is not extracted~~
- [x] ~~Description is used as title even when title is available~~

**Comment by pukkandan** [comment]
Related: https://github.com/ytdl-org/youtube-dl/pull/29796
