### ISSUE TITLE
javquick

### ISSUE THREAD

**Issue by UriF** [yt-dlp/yt-dlp#4531]
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.07.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

U.S.

### Example URLs

https://javquick.com/movie/aRYFZYCk/oyc-134-amateur-men-and-women-observe-monitoring-av-brother-sister-s-brother-sister-love-thorough-verification-when-my-brother-hears-from-my-sister-my-first-experience-or-erogenous-zone-which-i-usually-do-not-speak-absolutely-prize-money-if-i-can-answer-i-will-give-you-a-question-that-gradually-becomes-extreme-and-my-brother-also-erects-unexpectedly-thoughtlessly-to-my-sister-s-answer

### Provide a description that is worded well enough to be understood

I got a link from Video Download Helper and tried this (with header and without headers)
yt-dlp  --add-header "User-Agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36" --add-header "Referer:https://javquick.com/" "https://mmxdvrgkezexerxeeogpa.xyz/serve/gd2/NDT1q1r4c13nVAiYnlGrCuEmCCr6X2BJKThpuMjUd1coroEUbZGsPSU5uHzus3mHoUkQYlIGkty_M7kvYC2fG01MLTVXdQf06XxqarRHrmvOR9LX1ohwGQaaY5CW-819idHcDHkkqZ2XeOwaDQJ8cl6d9tjKnBGJrZElUJrpRxQPsRW0rs1j34SuqIOtLTrvn78uXrYuXrNshCY22uS7W4JSDKYnt4ieVRlKBZ55bg3hTa6Q5q7ffUA8yiwys20ONC4IRFzAA45uMXoPiM2wTG-a4vG4Dp-iteskzhcvh5TAIAsIbTFE0PUWhVhbjMZrY8ipAbWuddKuw3dADE3fyMH8PTu1l2FbK1Ekukw5vpaUi_I3BLWKfRRfEalpuiNtF5KwvQ1R5mK8yCpFS2B8g9rS6lbEatMNIGBob8i4iaYXNd57_PEd-8flPPpDFik0wBCSvSSXlpgRhAqwu9y1JgZVqj43hRQO7WPTDuhLMEr1RQg5WV_w.mp4"

The problem is that I am able to download only first chunk ~3Mb size.  If I check Google Development Tools I see a lot a 3Mb file with the same file name.  Therefore server get first 3 Mb chaunk and after it finish to play goes to next one and so on.   I tried Ant Downloader and ffmpeg and they returned me just a first 3 mb chunk.  VDH return me a proper file size.  

P.S.  I can survive without this site but I believe that it is a new type of protection???

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[generic] NDT1q1r4c13nVAiYnlGrCuEmCCr6X2BJKThpuMjUd1coroEUbZGsPSU5uHzus3mHoUkQYl
IGkty_M7kvYC2fG01MLTVXdQf06XxqarRHrmvOR9LX1ohwGQaaY5CW-819idHcDHkkqZ2XeOwaDQJ8cl
6d9tjKnBGJrZElUJrpRxQPsRW0rs1j34SuqIOtLTrvn78uXrYuXrNshCY22uS7W4JSDKYnt4ieVRlKBZ
55bg3hTa6Q5q7ffUA8yiwys20ONC4IRFzAA45uMXoPiM2wTG-a4vG4Dp-iteskzhcvh5TAIAsIbTFE0P
UWhVhbjMZrY8ipAbWuddKuw3dADE3fyMH8PTu1l2FbK1Ekukw5vpaUi_I3BLWKfRRfEalpuiNtF5KwvQ
1R5mK8yCpFS2B8g9rS6lbEatMNIGBob8i4iaYXNd57_PEd-8flPPpDFik0wBCSvSSXlpgRhAqwu9y1Jg
ZVqj43hRQO7WPTDuhLMEr1RQg5WV_w: Downloading webpage
[info] NDT1q1r4c13nVAiYnlGrCuEmCCr6X2BJKThpuMjUd1coroEUbZGsPSU5uHzus3mHoUkQYlIGk
ty_M7kvYC2fG01MLTVXdQf06XxqarRHrmvOR9LX1ohwGQaaY5CW-819idHcDHkkqZ2XeOwaDQJ8cl6d9
tjKnBGJrZElUJrpRxQPsRW0rs1j34SuqIOtLTrvn78uXrYuXrNshCY22uS7W4JSDKYnt4ieVRlKBZ55b
g3hTa6Q5q7ffUA8yiwys20ONC4IRFzAA45uMXoPiM2wTG-a4vG4Dp-iteskzhcvh5TAIAsIbTFE0PUWh
VhbjMZrY8ipAbWuddKuw3dADE3fyMH8PTu1l2FbK1Ekukw5vpaUi_I3BLWKfRRfEalpuiNtF5KwvQ1R5
mK8yCpFS2B8g9rS6lbEatMNIGBob8i4iaYXNd57_PEd-8flPPpDFik0wBCSvSSXlpgRhAqwu9y1JgZVq
j43hRQO7WPTDuhLMEr1RQg5WV_w: Downloading 1 format(s): mp4
ERROR: unable to open for writing: [Errno 2] No such file or directory: 'NDT1q1r
4c13nVAiYnlGrCuEmCCr6X2BJKThpuMjUd1coroEUbZGsPSU5uHzus3mHoUkQYlIGkty_M7kvYC2fG01
MLTVXdQf06XxqarRHrmvOR9LX1ohwGQaaY5CW-819idHcDHkkqZ2XeOwaDQJ8cl6d9tjKnBGJrZElUJr
pRxQPsRW0rs1j34SuqIOtLTrvn78uXrYuXrNshCY22uS7W4JSDKYnt4ieVRlKBZ55bg3hTa6Q5q7ffUA
8yiwys20ONC4IRFzAA45uMXoPiM2wTG-a4vG4Dp-iteskzhcvh5TAIAsIbTFE0PUWhVhbjMZrY8ipAbW
uddKuw3dADE3fyMH8PTu1l2FbK1Ekukw5vpaUi_I3BLWKfRRfEalpuiNtF5KwvQ1R5mK8yCpFS2B8g9r
S6lbEatMNIGBob8i4iaYXNd57_PEd-8flPPpDFik0wBCSvSSXlpgRhAqwu9y1JgZVqj43hRQO7WPTDuh
LMEr1RQg5WV_w [NDT1q1r4c13nVAiYnlGrCuEmCCr6X2BJKThpuMjUd1coroEUbZGsPSU5uHzus3mHo
UkQYlIGkty_M7kvYC2fG01MLTVXdQf06XxqarRHrmvOR9LX1ohwGQaaY5CW-819idHcDHkkqZ2XeOwaD
QJ8cl6d9tjKnBGJrZElUJrpRxQPsRW0rs1j34SuqIOtLTrvn78uXrYuXrNshCY22uS7W4JSDKYnt4ieV
RlKBZ55bg3hTa6Q5q7ffUA8yiwys20ONC4IRFzAA45uMXoPiM2wTG-a4vG4Dp-iteskzhcvh5TAIAsIb
TFE0PUWhVhbjMZrY8ipAbWuddKuw3dADE3fyMH8PTu1l2FbK1Ekukw5vpaUi_I3BLWKfRRfEalpuiNtF
5KwvQ1R5mK8yCpFS2B8g9rS6lbEatMNIGBob8i4iaYXNd57_PEd-8flPPpDFik0wBCSvSSXlpgRhAqwu
9y1JgZVqj43hRQO7WPTDuhLMEr1RQg5WV_w].mp4.part'
```

**Comment by Lesmiscore** [comment]
> I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)

**Comment by pukkandan** [comment]
@Lesmiscore Appreciate if you could add the relevant labels when closing
