### ISSUE TITLE
Instagram: Unable to extract additional data, username, & video URL.

### ISSUE THREAD

**Issue by scruffyeagle** [yt-dlp/yt-dlp#4532]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.07.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

U.S.

### Provide a description that is worded well enough to be understood

Downloading from Instagram used to work properly about 99% of the time - but as of a little more than a week ago, it entirely stopped working.  I uninstalled the repo version, then downloaded & installed the up to date version from Github.  It worked for one day, but I've hit the same wall again.

-------------------------------

This is the verbose output of a failed download:

```
$ yt-dlp --verbose https://www.instagram.com/p/Cfo4kgugFV4/
[debug] Command-line config: ['--verbose', 'https://www.instagram.com/p/Cfo4kgugFV4/']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.07.18 [135f05e] (zip)
[debug] Python 3.9.2 (CPython 64bit) - Linux-5.10.57-antix.1-amd64-smp-x86_64-with-glibc2.31 (glibc 2.31)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.3.4-0, ffprobe 4.3.4-0, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.9.7, certifi-2020.06.20, mutagen-1.45.1, pyxattr-0.7.2, sqlite3-2.6.0, websockets-8.1
[debug] Proxy map: {}
[debug] [Instagram] Extracting URL: https://www.instagram.com/p/Cfo4kgugFV4/
[Instagram] Cfo4kgugFV4: Downloading JSON metadata
WARNING: [Instagram] Cfo4kgugFV4: General metadata extraction failed
[Instagram] Cfo4kgugFV4: Downloading video info
[Instagram] Cfo4kgugFV4: Downloading embed webpage
WARNING: [Instagram] unable to extract additional data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [Instagram] unable to extract username; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
ERROR: [Instagram] Cfo4kgugFV4: Unable to extract video url; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 644, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/instagram.py", line 433, in _real_extract
    video_url = self._og_search_video_url(webpage, secure=False)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 1335, in _og_search_video_url
    return self._html_search_regex(regexes, html, name, **kargs)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 1230, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 1194, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
```
-------------------------

---------------------------
This is the output using the -vu flag:

```
$ yt-dlp -vu https://www.instagram.com/p/Cfo4kgugFV4/
[debug] Command-line config: ['-vu', 'https://www.instagram.com/p/Cfo4kgugFV4/']
Type account password and press [Return]: 
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.07.18 [135f05e] (zip)
[debug] Python 3.9.2 (CPython 64bit) - Linux-5.10.57-antix.1-amd64-smp-x86_64-with-glibc2.31 (glibc 2.31)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.3.4-0, ffprobe 4.3.4-0, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.9.7, certifi-2020.06.20, mutagen-1.45.1, pyxattr-0.7.2, sqlite3-2.6.0, websockets-8.1
[debug] Proxy map: {}

Usage: yt-dlp [OPTIONS] URL [URL...]

yt-dlp: error: You must provide at least one URL.
Type yt-dlp --help to see a list of all options.
```
-------------------------

As you can see, I DID provide a URL.  But -vu couldn't recognize it.
NOTE:  -vu requests the user to type in the account password.  That's quite vague.  I tried my desktop user password, and my Instagram account password.  Neither worked.

The URL I was trying to download from was
https://www.instagram.com/p/Cfo4kgugFV4/

---------------------------

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
$ yt-dlp --verbose https://www.instagram.com/p/Cfo4kgugFV4/
[debug] Command-line config: ['--verbose', 'https://www.instagram.com/p/Cfo4kgugFV4/']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.07.18 [135f05e] (zip)
[debug] Python 3.9.2 (CPython 64bit) - Linux-5.10.57-antix.1-amd64-smp-x86_64-with-glibc2.31 (glibc 2.31)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.3.4-0, ffprobe 4.3.4-0, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.9.7, certifi-2020.06.20, mutagen-1.45.1, pyxattr-0.7.2, sqlite3-2.6.0, websockets-8.1
[debug] Proxy map: {}
[debug] [Instagram] Extracting URL: https://www.instagram.com/p/Cfo4kgugFV4/
[Instagram] Cfo4kgugFV4: Downloading JSON metadata
WARNING: [Instagram] Cfo4kgugFV4: General metadata extraction failed
[Instagram] Cfo4kgugFV4: Downloading video info
[Instagram] Cfo4kgugFV4: Downloading embed webpage
WARNING: [Instagram] unable to extract additional data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [Instagram] unable to extract username; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
ERROR: [Instagram] Cfo4kgugFV4: Unable to extract video url; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 644, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/instagram.py", line 433, in _real_extract
    video_url = self._og_search_video_url(webpage, secure=False)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 1335, in _og_search_video_url
    return self._html_search_regex(regexes, html, name, **kargs)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 1230, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 1194, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
```

**Comment by pukkandan** [comment]
It should have been `-vU`, not `-vu`. No matter now. You have given all necessary info

**Comment by pukkandan** [comment]
Related https://github.com/ytdl-org/youtube-dl/issues/31098

**Comment by scruffyeagle** [comment]
The current state of downloads using the up to date version of yt-dlp, is that it's working about 90% of the time.  Those times when it doesn't work, the error condition always displays the 3 failures of can't extract additional data, uploader ID, & video URL.
-------------------------------

$ yt-dlp -vU https://www.instagram.com/p/CEmq3tBD2cc/
[debug] Command-line config: ['-vU', 'https://www.instagram.com/p/CEmq3tBD2cc/']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.07.18 [135f05e] (zip)
[debug] Python 3.9.2 (CPython 64bit) - Linux-5.10.57-antix.1-amd64-smp-x86_64-with-glibc2.31 (glibc 2.31)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.3.4-0, ffprobe 4.3.4-0, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.9.7, certifi-2020.06.20, mutagen-1.45.1, pyxattr-0.7.2, sqlite3-2.6.0, websockets-8.1
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.07.18, Current version: 2022.07.18
yt-dlp is up to date (2022.07.18)
[debug] [Instagram] Extracting URL: https://www.instagram.com/p/CEmq3tBD2cc/
[Instagram] CEmq3tBD2cc: Downloading JSON metadata
WARNING: [Instagram] CEmq3tBD2cc: General metadata extraction failed
[Instagram] CEmq3tBD2cc: Downloading video info
[Instagram] CEmq3tBD2cc: Downloading embed webpage
WARNING: [Instagram] unable to extract additional data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [Instagram] unable to extract username; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
ERROR: [Instagram] CEmq3tBD2cc: Unable to extract video url; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 644, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/instagram.py", line 433, in _real_extract
    video_url = self._og_search_video_url(webpage, secure=False)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 1335, in _og_search_video_url
    return self._html_search_regex(regexes, html, name, **kargs)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 1230, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 1194, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)

**Comment by scruffyeagle** [comment]
Sorry.  "Uploader ID" was the failure before upgrading to v2022.07.18.  Now, it's saying it can't extract the username.

**Comment by pritam20ps05** [comment]
Just use cookies it would work fine. You are just getting rate limited.

**Comment by pukkandan** [comment]
@scruffyeagle When the download is not working, can you access the video in an incognito browser (from same IP)?

**Comment by pritam20ps05** [comment]
@pukkandan it will work in browser for public content but they are getting rate limited. After many attempts their IPs are getting flagged that's why it works 90% of the times, in some cases their IPs are already flagged(eg. VPS, cloud compute units etc). It is recommended to use cookies and the extractor will work 100% of the time.

**Comment by pukkandan** [comment]
If it works in browser, then it is a valid bug report and your PR does not fix it

**Comment by pritam20ps05** [comment]
It's very hard to confirm as here only embed pages are getting rate limited but seeing them do so is preety rare, but will definitely try to look into this matter.

**Comment by pritam20ps05** [comment]
So after doing a test with a post and no cookies embed extraction was successful for more than 100 attemps after which i stopped the test. The extraction never failed and feels like its not about rate limiting but opening the link in private window failed to load. So i guess @pukkandan is right about the browser thing and it does not work

**Comment by pukkandan** [comment]
I don't think we are on the same page here. It doesn't matter if the embed page or API is blocked. The URL that the user passed to yt-dlp does open/play in browser (without cookies), but does not download in yt-dlp. That means the extractor is broken!

Is using cookies a workaround? yes. That does not mean the issue is resolved or should be closed

**Comment by pritam20ps05** [comment]
It's actually a bug or exception from IG and trying to fix it in the extractor would require extraction from the main webpage which is very much prone to changes, rate limiting etc. Changing the extraction method might cause other things to break so I think this issue might not be resolvable.

**Comment by bashonly** [comment]
sometimes the embed page itself does not load the video or any useful JSON, and it requires a click through to the actual webpage. the current instagram extractor does not try to extract the actual webpage (it tries graphQL, then API, then falls back to the embed page). the reason why the reels are loading in a browser without cookies but failing with yt-dlp is because it is not even attempting to load the actual webpage (`instagram.com/p/{shortcode}`). so i think actual webpage extraction needs to be implemented as a fallback if embed page extraction fails.

the issue with the actual webpage though is without cookies instagram enforces strict rate-limiting. i can typically only load 5 post webpages in 24 hours before i start to be redirected to the login page.

**Comment by pritam20ps05** [comment]
@bashonly a good one I was thinking the same but the rate limiting bothered me. Then also I would give it a try

**Comment by bashonly** [comment]
> @bashonly a good one I was thinking the same but the rate limiting bothered me. Then also I would give it a try

the rate-limiting is the culprit for some of the issues at play here, but i think actual webpage extraction is necessary at this point, and a "login required" error should only be raised after the extractor detects a redirect to the login page

**Comment by pritam20ps05** [comment]
But here comes another problem what if the content never existed the webpage won't return a 404 error

**Comment by bashonly** [comment]
good point re: embed extraction not failing.

another thing i am noticing: 
the graphQL extraction should not be failing all the time (it is failing in all of the verbose logs posted in these issues). 
instagram still utilizes the graphQL flow for logged-out users. 

i think the graphQL request may require the `X-CSRFToken` http header and/or some non-authenticated cookies passed (likely `ig_did` and `csrftoken`, maybe `mid` `datr` and `ig_nrcb`) in order to succeed. 

it looks like before a graphQL request is made, the actual webpage script sends an XHR request to this endpoint:
`https://i.instagram.com/api/v1/web/get_ruling_for_content/?content_type=MEDIA&target_id={numeric_pk}`
and some of these cookies are set in the response headers

**Comment by scruffyeagle** [comment]
Here are some more URL's which all failed for me, after working properly in the browser:

https://www.instagram.com/p/CgwvwT9AxBt/
https://www.instagram.com/p/CEmq3tBD2cc/
https://www.instagram.com/p/CJ1kOM6DvhC/
https://www.instagram.com/p/CgwDHQSl4KG/
https://www.instagram.com/p/CgEmtIJsMuX/
https://www.instagram.com/p/CgjeNKrq1c2/
https://www.instagram.com/p/CgtpDsEKj76/
https://www.instagram.com/p/Cg36NkrKEJL/
https://www.instagram.com/p/Cg3NZMoAAbT/

Note, failing seems to be the rule, not the exception.

**Comment by pritam20ps05** [comment]
I know why they are not working, because they are reel videos and the current extractor is having a hard time extracting those.

**Comment by pritam20ps05** [comment]
You all can check this PR #4657 which fixes this issue. All these urls can be extracted until you get rate limited which means that you can extract these links till you can view them in browser.

**Comment by bashonly** [comment]
> You all can check this PR #4657 which fixes this issue. All these urls can be extracted until you get rate limited which means that you can extract these links till you can view them in browser.

in my testing, instagram is no longer putting any useful JSON in webpages for non-authenticated users. all media info is being fetched by graphql XHR requests. graphql extraction needs to be fixed. see my above comment

**Comment by pritam20ps05** [comment]
The current extractor behaves the way it has been intended to work. If you can't see the content in your browser then it won't get extracted but still i will review your findings. Also any further improvement to the extractor might not visible.

**Comment by pritam20ps05** [comment]
I checked it but I am seeing that without cookies graphQL returns not logged in page so it didn't work for me. I would recomend you to send the code which is expected to fix it.

**Comment by scruffyeagle** [comment]
The only time I've ever tried to download an Instagram video, was when I was already logged in at Instagram in my browser.  That also means my browser had already downloaded the Instagram cookies, including any for the given video I was trying to download.

**Comment by pukkandan** [comment]
yt-dlp will use cookies only if you ask it to - which you have not

**Comment by scruffyeagle** [comment]
I'm about 90% sure the problem downloading is connected with the "reel" format, because whenever anyone admits to using reel, the vids NEVER download.
