### ISSUE TITLE
This Old House Insider (Ask This Old House)

### ISSUE THREAD

**Issue by scarng63** [yt-dlp/yt-dlp#4536]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.07.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

USA

### Provide a description that is worded well enough to be understood

Unable to pull episode [ASK-TOH S18E23](https://www.thisoldhouse.com/season-18-ask-toh/21249520/s18-e23-mantel-too-many-light-switches)  or any other episodes.

Try both --cookies and --username/--password too no avail.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp -Uv --cookies thisoldhouse.com_cookies.txt https://www.thisoldhouse.com/season-18-ask-toh/21249520/s18-e23-mantel-too-many-light-switches
[debug] Command-line config: ['-Uv', '--cookies', 'thisoldhouse.com_cookies.txt', 'https://www.thisoldhouse.com/season-18-ask-toh/21249520/s18-e23-mantel-too-many-light-switches']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.07.18 [135f05e] (win32_exe)
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 2021-09-01-git-c500dc7cca-full_build-www.gyan.dev (setts), ffprobe 2021-09-01-git-c500dc7cca-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.07.18, Current version: 2022.07.18
yt-dlp is up to date (2022.07.18)
[debug] [ThisOldHouse] Extracting URL: https://www.thisoldhouse.com/season-18-ask-toh/21249520/s18-e23-mantel-too-many-light-switches
[ThisOldHouse] s18-e23-mantel-too-many-light-switches: Downloading webpage
[debug] [Zype] Extracting URL: https://player.zype.com/embed/5eb2de558bdf6400017edb68.html?api_key=hsOk_yMSPYNrT22e9pu8hihLXjaZf0JW5jsOWv4ZqyHJFvkJn6rtToHl09tbbsbe
[Zype] 5eb2de558bdf6400017edb68: Downloading JSON metadata
ERROR: [Zype] 5eb2de558bdf6400017edb68: This video requires a purchase entitlement in order to watch.
  File "yt_dlp\extractor\common.py", line 644, in extract
    and self._GEO_BYPASS
  File "yt_dlp\extractor\zype.py", line 48, in _real_extract
    r'\.(?:js|html)\?', '.json?', url), video_id)['response']
```

**Comment by scarng63** [comment]
@pukkandan Not sure how to share account information?  email or pm????

**Comment by pukkandan** [comment]
The labels are just a hint for maintainers/contributors that account is needed to work on the issue. If any developer needs account details for working on this, they will let you know how to share it privately.

**Comment by scarng63** [comment]
Upgraded, login to streaming site, downloaded current cookies and now it is working. Closing Issue.
