### ISSUE TITLE
doodstream

### ISSUE THREAD

**Issue by thevoy** [yt-dlp/yt-dlp#4538]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.07.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Philippines

### Provide a description that is worded well enough to be understood

[DoodStream] vv5mt1wkvsqm: Downloading webpage
ERROR: [DoodStream] vv5mt1wkvsqm: Unable to extract token; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[root@vm-websrv-8 public_html]# yt-dlp https://dood.watch/d/vv5mt1wkvsqm -vU
[debug] Command-line config: ['https://dood.watch/d/vv5mt1wkvsqm', '-vU']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8 (No ANSI), error utf-8 (No ANSI), screen utf-8 (No ANSI)
[debug] yt-dlp version 2022.07.18 [135f05e] (zip)
[debug] Python 3.7.3 (CPython 64bit) - Linux-4.19.0-21-amd64-x86_64-with-debian-10.12 (glibc 2.28)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.1.9-0, ffprobe 4.1.9-0
[debug] Optional libraries: certifi-2018.08.24, sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.07.18, Current version: 2022.07.18
yt-dlp is up to date (2022.07.18)
[debug] [DoodStream] Extracting URL: https://dood.watch/d/vv5mt1wkvsqm
[DoodStream] vv5mt1wkvsqm: Downloading webpage
ERROR: [DoodStream] vv5mt1wkvsqm: Unable to extract token; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 644, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/doodstream.py", line 49, in _real_extract
    token = self._html_search_regex(r'[?&]token=([a-z0-9]+)[&\']', webpage, 'token')
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 1230, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 1194, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
```

**Comment by mp3butcher** [comment]
I have a working d0odstream extractor. Is it worth a pull request?

**Comment by Grub4K** [comment]
No. The extractor was removed for piracy reasons
