### ISSUE TITLE
could not decode downloader output: json: cannot unmarshal number 52748 into Go struct field YTDLFormat.abr oy type int

### ISSUE THREAD

**Issue by vinisilv4** [yt-dlp/yt-dlp#454]
## Checklist

- [x ] I'm reporting a broken site support issue
- [x ] I've verified that I'm running yt-dlp version **2021.06.23**
- [x ] I've checked that all provided URLs are alive and playable in a browser
- [ x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ x] I've searched the bugtracker for similar bug reports including closed ones
- [x ] I've read bugs section in FAQ

## Verbose log

```
could not decode downloader output: json: cannot unmarshal number 52748 into Go struct field YTDLFormat.abr oy type int

```

## Description

Could someone help me with this error?

**Comment by nao20010128nao** [comment]
Both youtube-dl and yt-dlp never output such error.
