### ISSUE TITLE
Ubuntu 22.04: ImportError: libffi.so.7

### ISSUE THREAD

**Issue by spirillen** [yt-dlp/yt-dlp#4541]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.07.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

```python
yt-dlp https://www.example.com
Traceback (most recent call last):
  File "$USER/.local/bin/yt-dlp", line 5, in <module>
    from yt_dlp import main
  File "$USER/.local/lib/python3.10/site-packages/yt_dlp/__init__.py", line 14, in <module>
    from .cookies import SUPPORTED_BROWSERS, SUPPORTED_KEYRINGS
  File "$USER/.local/lib/python3.10/site-packages/yt_dlp/cookies.py", line 3, in <module>
    import ctypes
  File "/usr/local/lib/python3.10/ctypes/__init__.py", line 8, in <module>
    from _ctypes import Union, Structure, Array
ImportError: libffi.so.7: cannot open shared object file: No such file or directory
```

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp -vU https://www.example.uri -F
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/local/bin/yt-dlp/__main__.py", line 14, in <module>
  File "/usr/local/bin/yt-dlp/yt_dlp/__init__.py", line 14, in <module>
  File "/usr/local/bin/yt-dlp/yt_dlp/cookies.py", line 3, in <module>
  File "/usr/local/lib/python3.10/ctypes/__init__.py", line 8, in <module>
    from _ctypes import Union, Structure, Array
ImportError: libffi.so.7: cannot open shared object file: No such file or directory
```

**Comment by pukkandan** [comment]
Technically the issue is your system not having the correct dependencies for your Python version. But we can easily work around this. The only caveat is that `--console-title` will not work for you

**Comment by pukkandan** [comment]
Just to clarify, this is not the standalone binary, correct?

**Comment by pukkandan** [comment]
standalone as in the `yt-dlp` file, or the `yt-dlp_linux` file?

**Comment by pukkandan** [comment]
> and a dependency isn't correctly listed in the pipy package manager

I don't mean a dependency of yt-dlp, but a dep of Python itself. I suggest you ask around in some Python/Ubuntu forums if you want to to figure out the exact root cause.

If you just want to get yt-dlp working, I have added a workaround. Wait for release on [install master branch](https://github.com/yt-dlp/yt-dlp#with-pip)

**Comment by spirillen** [comment]
I'll just wait a minute then :) i'm all busy rebuilding mypdns.org
