### ISSUE TITLE
zoom.py desktop to mobile user agent changing

### ISSUE THREAD

**Issue by ananth-28** [yt-dlp/yt-dlp#4542]
### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.07.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

in zoom youtube-dl uses desktop mode user-agent but when mobile user agent are used on zoom both Screen share stream and Camera stream are show as one video but in desktop user agent (used by youtube-dl) it shows them differently and i need both as one video #
so i edited zoom.py but it didnt work out insted gave error

 _ERROR: [zoom] 8dbJxGJHAhQhoVMV73pGFTAcRFCxbjOgt_rLbdhb4PH9VUO1feUEtoL91o-9QyOW.MyezmvHOIciMpBso: Unable to extract data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U_ 

my edited code below
![image](https://user-images.githubusercontent.com/106482929/182447240-e1acc655-1425-4861-af8e-0c81503cf694.png)
then i reslised that some thing needs to be changed here also (ref below image)
![image](https://user-images.githubusercontent.com/106482929/182447426-73629f7f-ca2d-4ab3-91a7-09dcf67b2955.png)
i need help regarding it
i dont know what should come in place of 'shareMp4Url' here if we are using mobile user agent
        if data.get('shareMp4Url')

Thank you

example link -
https://api.zoom.us/rec/share/8dbJxGJHAhQhoVMV73pGFTAcRFCxbjOgt_rLbdhb4PH9VUO1feUEtoL91o-9QyOW.MyezmvHOIciMpBso 

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
Undo all edits you made. Then show verbose logs of the yt-dlp command with and without `--user-agent ...`

**Comment by dirkf** [comment]
With my browser spoofing `Mozilla/5.0 (Linux; Android 8.0.0; Pixel XL Build/OPR6.170623.012) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.107 Mobile Safari/537.36`, I got a nice plain  HTML5 video page:
```html
...
<video class="video-js" id="video" ...>
<source src="https://ssrweb.zoom.us/replay03/...
```
