### ISSUE TITLE
download afreeca.tv video error

### ISSUE THREAD

**Issue by v2wy** [yt-dlp/yt-dlp#4543]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.07.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

if i use this command, it's working.
`yt-dlp --concurrent-fragments 16 https://vod.afreecatv.com/player/90410063`
[afreecatv] 90410063: Downloading webpage
[afreecatv] 90410063: Downloading video info XML
[afreecatv] 90410063: Downloading part 1 m3u8 information
[afreecatv] 90410063: Downloading part 2 m3u8 information
[download] Downloading multi_video: 피넛
[afreecatv] Playlist 피넛: Downloading 2 videos of 2
[download] Downloading video 1 of 2
[info] 20220801_000338AD_241922993_1: Downloading 1 format(s): hls-original
[download] 피넛 (part 1) [20220801_000338AD_241922993_1].mp4 has already been downloaded
[download] 100% of 300.19MiB
[download] Downloading video 2 of 2
[info] 20220801_1F807A8D_241922993_2: Downloading 1 format(s): hls-original
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 3028
[download] Destination: 피넛 (part 2) [20220801_1F807A8D_241922993_2].mp4
WARNING: The download speed shown is only of one thread. This is a known issue and patches are welcome
[download]  29.3% of ~9.41GiB at  324.33KiB/s ETA 01:26 (frag 886/3028)[download] Got server HTTP error: timed out. Retrying (attempt 1 of 10) ...
[download]  29.3% of ~9.41GiB at    1.21MiB/s ETA 01:26 (frag 886/3028)[download] Got server HTTP error: timed out. Retrying (attempt 1 of 10) ...
[download] 100% of 9.41GiB in 01:57
[FixupM3u8] Fixing MPEG-TS in MP4 container of "피넛 (part 2) [20220801_1F807A8D_241922993_2].mp4"
[Concat] Concatenating 2 files; Destination: 피넛 [90410063].mp4
Deleting original file /root/morty/test/피넛 (part 1) [20220801_000338AD_241922993_1].mp4 (pass -k to keep)
Deleting original file /root/morty/test/피넛 (part 2) [20220801_1F807A8D_241922993_2].mp4 (pass -k to keep)
[download] Finished downloading playlist: 피넛
root@racknerd-eb0eb4:~/morty/test# ls
'피넛 [90410063].mp4'

but when i use following command, it's not working. Only the first video will be downloaded, then it will delete the donwloaded videos. You can reproduce this bug.
`yt-dlp -o 'test.%(ext)s' --concurrent-fragments 16 https://vod.afreecatv.com/player/90410063`
[afreecatv] 90410063: Downloading webpage
[afreecatv] 90410063: Downloading video info XML
[afreecatv] 90410063: Downloading part 1 m3u8 information
[afreecatv] 90410063: Downloading part 2 m3u8 information
[download] Downloading multi_video: 피넛
[afreecatv] Playlist 피넛: Downloading 2 videos of 2
[download] Downloading video 1 of 2
[info] 20220801_000338AD_241922993_1: Downloading 1 format(s): hls-original
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 97
[download] Destination: test.mp4
WARNING: The download speed shown is only of one thread. This is a known issue and patches are welcome
[download] 100% of 311.97MiB in 00:04
[FixupM3u8] Fixing MPEG-TS in MP4 container of "test.mp4"
[download] Downloading video 2 of 2
[info] 20220801_1F807A8D_241922993_2: Downloading 1 format(s): hls-original
[download] test.mp4 has already been downloaded
[download] 100% of 300.19MiB
[Concat] Concatenating 2 files; Destination: test.mp4
Deleting original file /root/morty/test/test.mp4 (pass -k to keep)
[download] Finished downloading playlist: 피넛

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
root@racknerd-eb0eb4:~/morty/test# yt-dlp -v
[debug] Command-line config: ['-v']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.07.18 [135f05e]
[debug] Python 3.8.10 (CPython 64bit) - Linux-5.4.0-28-generic-x86_64-with-glibc2.29 (glibc 2.31)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.2.7, ffprobe 4.2.7
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2019.11.28, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}

Usage: yt-dlp [OPTIONS] URL [URL...]

yt-dlp: error: You must provide at least one URL.
Type yt-dlp --help to see a list of all options.
```

**Comment by dirkf** [comment]
Don't use an output template with a constant name part (`test` in your example) when downloading multiple videos, even if it's really a single video that will be concatenated from the downloaded videos.

**Comment by v2wy** [comment]
Thanks for your reply.
