### ISSUE TITLE
play.history.com Unable to download webpage: HTTP Error 500

### ISSUE THREAD

**Issue by crorcutt** [yt-dlp/yt-dlp#4546]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.07.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [x] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

US

### Provide a description that is worded well enough to be understood

Trying to download a video from play.history.com, specifically https://play.history.com/shows/modern-marvels/season-21/episode-11 and getting the error **Unable to download webpage: HTTP Error 500**

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
C:\WINDOWS\system32>yt-dlp https://play.history.com/shows/modern-marvels/season-21/episode-11 -vU
[debug] Command-line config: ['https://play.history.com/shows/modern-marvels/season-21/episode-11', '-vU']
[debug] User config "C:\Users\<name>\yt-dlp.conf": ['-o', '~/Videos/%(title)s.%(ext)s', '--download-archive', '\\\\ASGARD\\Media\\Software\\youtube-dl\\YTDLArchive.txt', '--force-write-archive', '--ffmpeg-location', 'C:\\Program Files\\ffmpeg-2021-07-06-git-758e2da289-full_build\\bin', '--cookies-from-browser', 'chrome:', '--sub-lang', 'en,en-US,en-UK', '--sub-format', 'ass/srt/best/scc/vtt', '--embed-subs', '--batch-file', '~/Desktop/Batch.txt', '--merge-output-format', 'mkv', '--ap-mso', 'Charter_Direct', '--ap-username', 'PRIVATE', '--ap-password', 'PRIVATE']
[debug] Batch file urls: []
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.07.18 [135f05e] (win32_exe)
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] Checking exe version: "C:\Program Files\ffmpeg-2021-07-06-git-758e2da289-full_build\bin\ffmpeg" -bsfs
[debug] Checking exe version: "C:\Program Files\ffmpeg-2021-07-06-git-758e2da289-full_build\bin\ffprobe" -bsfs
[debug] exe versions: ffmpeg 2021-07-06-git-758e2da289-full_build-www.gyan.dev (setts), ffprobe 2021-07-06-git-758e2da289-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[Cookies] Extracting cookies from chrome
[debug] Extracting cookies from: "C:\Users\<name>\AppData\Local\Google\Chrome\User Data\Default\Network\Cookies"
[debug] Found local state file at "C:\Users\<name>\AppData\Local\Google\Chrome\User Data\Local State"
[Cookies] Extracted 3240 cookies from chrome
[debug] cookie version breakdown: {'v10': 3240, 'other': 0, 'unencrypted': 0}
[debug] Proxy map: {}
[debug] Loading archive file '\\\\ASGARD\\Media\\Software\\youtube-dl\\YTDLArchive.txt'
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.07.18, Current version: 2022.07.18
yt-dlp is up to date (2022.07.18)
[debug] [aenetworks] Extracting URL: https://play.history.com/shows/modern-marvels/season-21/episode-11
[aenetworks] /shows/modern-marvels/season-21/episode-11: Downloading JSON metadata
[aenetworks] 2057163843570: Downloading JSON metadata
[aenetworks] 2057163843570: Downloading Provider Redirect Page
[aenetworks] 2057163843570: Downloading Provider Login Page
[aenetworks] 2057163843570: Logging in
[aenetworks] 2057163843570: Confirming Login
ERROR: [aenetworks] shows/modern-marvels/season-21/episode-11: Unable to download webpage: HTTP Error 500:  (caused by <HTTPError 500: ''>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 644, in extract
  File "yt_dlp\extractor\aenetworks.py", line 169, in _real_extract
  File "yt_dlp\extractor\aenetworks.py", line 86, in _extract_aetn_info
  File "yt_dlp\extractor\adobepass.py", line 1712, in _extract_mvpd_auth
  File "yt_dlp\extractor\adobepass.py", line 1395, in post_form
  File "yt_dlp\extractor\adobepass.py", line 1361, in _download_webpage_handle
  File "yt_dlp\extractor\common.py", line 838, in _download_webpage_handle
  File "yt_dlp\extractor\common.py", line 795, in _request_webpage

  File "yt_dlp\extractor\common.py", line 777, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 3639, in urlopen
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 500:
```

**Comment by october262** [comment]
> 



> ### Checklist
> * [x]  I'm reporting a broken site
> * [x]  I've verified that I'm running yt-dlp version **2022.07.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
> * [x]  I've checked that all provided URLs are playable in a browser with the same IP and same login details
> * [x]  I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
> * [x]  I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
> * [x]  I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
> * [x]  I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required
> 
> ### Region
> US
> 
> ### Provide a description that is worded well enough to be understood
> Trying to download a video from play.history.com, specifically https://play.history.com/shows/modern-marvels/season-21/episode-11 and getting the error **Unable to download webpage: HTTP Error 500**
> 
> ### Provide verbose output that clearly demonstrates the problem
> * [x]  Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
> * [x]  Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below
> 
> ### Complete Verbose Output
> ```shell
> C:\WINDOWS\system32>yt-dlp https://play.history.com/shows/modern-marvels/season-21/episode-11 -vU
> [debug] Command-line config: ['https://play.history.com/shows/modern-marvels/season-21/episode-11', '-vU']
> [debug] User config "C:\Users\<name>\yt-dlp.conf": ['-o', '~/Videos/%(title)s.%(ext)s', '--download-archive', '\\\\ASGARD\\Media\\Software\\youtube-dl\\YTDLArchive.txt', '--force-write-archive', '--ffmpeg-location', 'C:\\Program Files\\ffmpeg-2021-07-06-git-758e2da289-full_build\\bin', '--cookies-from-browser', 'chrome:', '--sub-lang', 'en,en-US,en-UK', '--sub-format', 'ass/srt/best/scc/vtt', '--embed-subs', '--batch-file', '~/Desktop/Batch.txt', '--merge-output-format', 'mkv', '--ap-mso', 'Charter_Direct', '--ap-username', 'PRIVATE', '--ap-password', 'PRIVATE']
> [debug] Batch file urls: []
> [debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
> [debug] yt-dlp version 2022.07.18 [135f05e] (win32_exe)
> [debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
> [debug] Checking exe version: "C:\Program Files\ffmpeg-2021-07-06-git-758e2da289-full_build\bin\ffmpeg" -bsfs
> [debug] Checking exe version: "C:\Program Files\ffmpeg-2021-07-06-git-758e2da289-full_build\bin\ffprobe" -bsfs
> [debug] exe versions: ffmpeg 2021-07-06-git-758e2da289-full_build-www.gyan.dev (setts), ffprobe 2021-07-06-git-758e2da289-full_build-www.gyan.dev
> [debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
> [Cookies] Extracting cookies from chrome
> [debug] Extracting cookies from: "C:\Users\<name>\AppData\Local\Google\Chrome\User Data\Default\Network\Cookies"
> [debug] Found local state file at "C:\Users\<name>\AppData\Local\Google\Chrome\User Data\Local State"
> [Cookies] Extracted 3240 cookies from chrome
> [debug] cookie version breakdown: {'v10': 3240, 'other': 0, 'unencrypted': 0}
> [debug] Proxy map: {}
> [debug] Loading archive file '\\\\ASGARD\\Media\\Software\\youtube-dl\\YTDLArchive.txt'
> [debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
> Latest version: 2022.07.18, Current version: 2022.07.18
> yt-dlp is up to date (2022.07.18)
> [debug] [aenetworks] Extracting URL: https://play.history.com/shows/modern-marvels/season-21/episode-11
> [aenetworks] /shows/modern-marvels/season-21/episode-11: Downloading JSON metadata
> [aenetworks] 2057163843570: Downloading JSON metadata
> [aenetworks] 2057163843570: Downloading Provider Redirect Page
> [aenetworks] 2057163843570: Downloading Provider Login Page
> [aenetworks] 2057163843570: Logging in
> [aenetworks] 2057163843570: Confirming Login
> ERROR: [aenetworks] shows/modern-marvels/season-21/episode-11: Unable to download webpage: HTTP Error 500:  (caused by <HTTPError 500: ''>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
>   File "yt_dlp\extractor\common.py", line 644, in extract
>   File "yt_dlp\extractor\aenetworks.py", line 169, in _real_extract
>   File "yt_dlp\extractor\aenetworks.py", line 86, in _extract_aetn_info
>   File "yt_dlp\extractor\adobepass.py", line 1712, in _extract_mvpd_auth
>   File "yt_dlp\extractor\adobepass.py", line 1395, in post_form
>   File "yt_dlp\extractor\adobepass.py", line 1361, in _download_webpage_handle
>   File "yt_dlp\extractor\common.py", line 838, in _download_webpage_handle
>   File "yt_dlp\extractor\common.py", line 795, in _request_webpage
> 
>   File "yt_dlp\extractor\common.py", line 777, in _request_webpage
>   File "yt_dlp\YoutubeDL.py", line 3639, in urlopen
>   File "urllib\request.py", line 531, in open
>   File "urllib\request.py", line 640, in http_response
>   File "urllib\request.py", line 569, in error
>   File "urllib\request.py", line 502, in _call_chain
>   File "urllib\request.py", line 649, in http_error_default
> urllib.error.HTTPError: HTTP Error 500:
> ```

are you signed in with your tv / cable provider ??
also try using  the cookies.txt file command.

**Comment by crorcutt** [comment]
Yes, I am signed in and include those credentials in my config file as well. I normally use the pass from-browser for cookies but for additional testing I disabled that in the conf and added --cookies "path/to/cookies.txt" in my command but got the same results.

**Comment by october262** [comment]
> Yes, I am signed in and include those credentials in my config file as well. I normally use the pass from-browser for cookies but for additional testing I disabled that in the conf and added --cookies "path/to/cookies.txt" in my command but got the same results.
play the video and press F12 on your keyboard to open the developer tools
switch to the network tab and type master.m3u8 in the search box,
copy the link and feed that into yt-dlp to download the video.

**Comment by crorcutt** [comment]
> play the video and press F12 on your keyboard to open the developer tools
switch to the network tab and type master.m3u8 in the search box,
copy the link and feed that into yt-dlp to download the video.

I gave that a shot and got a new error: **Unable to download webpage: HTTP Error 403: Forbidden**. Here's the verbose output if that helps:
C:\WINDOWS\system32>yt-dlp -v https://aesop-video.akamaized.net/AETN-History_VMS/BRAND_THC_MDRN_268170_GLB_433204_5994_60_20220726_01_0728066_S3_,18,13,10,7,4,2,1,00.mp4.csmil/master.m3u8?__b__=700&hdnts=st=1659561364~exp=1659572194~acl=/*~hmac=b42b3fce1f9e98cba6f81e13c36c1f7923f4c10394fce4db537501acbca9d690
[debug] Command-line config: ['-v', 'https://aesop-video.akamaized.net/AETN-History_VMS/BRAND_THC_MDRN_268170_GLB_433204_5994_60_20220726_01_0728066_S3_,18,13,10,7,4,2,1,00.mp4.csmil/master.m3u8?__b__=700']
[debug] User config "C:\Users\<name>\yt-dlp.conf": ['-o', '~/Videos/%(title)s.%(ext)s', '--download-archive', '\\\\ASGARD\\Media\\Software\\youtube-dl\\YTDLArchive.txt', '--force-write-archive', '--ffmpeg-location', 'C:\\Program Files\\ffmpeg-2021-07-06-git-758e2da289-full_build\\bin', '--cookies-from-browser', 'chrome:', '--sub-lang', 'en,en-US,en-UK', '--sub-format', 'ass/srt/best/scc/vtt', '--embed-subs', '--batch-file', '~/Desktop/Batch.txt', '--merge-output-format', 'mkv', '--ap-mso', 'Charter_Direct', '--ap-username', 'PRIVATE', '--ap-password', 'PRIVATE']
[debug] Batch file urls: []
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.07.18 [135f05e] (win32_exe)
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] Checking exe version: "C:\Program Files\ffmpeg-2021-07-06-git-758e2da289-full_build\bin\ffmpeg" -bsfs
[debug] Checking exe version: "C:\Program Files\ffmpeg-2021-07-06-git-758e2da289-full_build\bin\ffprobe" -bsfs
[debug] exe versions: ffmpeg 2021-07-06-git-758e2da289-full_build-www.gyan.dev (setts), ffprobe 2021-07-06-git-758e2da289-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[Cookies] Extracting cookies from chrome
[debug] Extracting cookies from: "C:\Users\<name>\AppData\Local\Google\Chrome\User Data\Default\Network\Cookies"
[debug] Found local state file at "C:\Users\<name>\AppData\Local\Google\Chrome\User Data\Local State"
[Cookies] Extracted 3226 cookies from chrome
[debug] cookie version breakdown: {'v10': 3226, 'other': 0, 'unencrypted': 0}
[debug] Proxy map: {}
[debug] Loading archive file '\\\\ASGARD\\Media\\Software\\youtube-dl\\YTDLArchive.txt'
[debug] [generic] Extracting URL: https://aesop-video.akamaized.net/AETN-History_VMS/BRAND_THC_MDRN_268170_GLB_433204_5994_60_20220726_01_0728066_S3_,18,13,10,7,4,2,1,00.mp4.csmil/master.m3u8?__b__=700
[generic] master: Downloading webpage
ERROR: [generic] Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 644, in extract
  File "yt_dlp\extractor\generic.py", line 2816, in _real_extract
  File "yt_dlp\extractor\common.py", line 795, in _request_webpage

  File "yt_dlp\extractor\common.py", line 777, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 3639, in urlopen
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden

'hdnts' is not recognized as an internal or external command,
operable program or batch file.

**Comment by october262** [comment]
> https://aesop-video.akamaized.net/AETN-History_VMS/BRAND_THC_MDRN_268170_GLB_433204_5994_60_20220726_01_0728066_S3_,18,13,10,7,4,2,1,00.mp4.csmil/master.m3u8?__b__=700&hdnts=st=1659561364~exp=1659572194~acl=/*~hmac=b42b3fce1f9e98cba6f81e13c36c1f7923f4c10394fce4db537501acbca9d690

this first link works - https://aesop-video.akamaized.net/AETN-History_VMS/BRAND_THC_MDRN_268170_GLB_433204_5994_60_20220726_01_0728066_S3_,18,13,10,7,4,2,1,00.mp4.csmil/master.m3u8?__b__=700&hdnts=st=1659561364~exp=1659572194~acl=/*~hmac=b42b3fce1f9e98cba6f81e13c36c1f7923f4c10394fce4db537501acbca9d690

just do yt-dlp "https://aesop-video.akamaized.net/AETN-History_VMS/BRAND_THC_MDRN_268170_GLB_433204_5994_60_20220726_01_0728066_S3_,18,13,10,7,4,2,1,00.mp4.csmil/master.m3u8?__b__=700&hdnts=st=1659561364~exp=1659572194~acl=/*~hmac=b42b3fce1f9e98cba6f81e13c36c1f7923f4c10394fce4db537501acbca9d690"
the video will now download.

**Comment by crorcutt** [comment]
That absolutely worked! I had tried quotes with the initial url but not with the master.m3u8 and that did the trick, thank you!
