### ISSUE TITLE
[bandcamp] maximum recursion depth exceeded while calling a Python object

### ISSUE THREAD

**Issue by chapmanjacobd** [yt-dlp/yt-dlp#4548]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.07.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Provide a description that is worded well enough to be understood

I know this is kind of dumb but `yt-dlp -v -j https://bandcamp.com/` causes a near-infinite loop

as well as collection pages like `yt-dlp -v -j https://bandcamp.com/user`

Most URLs don't do this so I feel like this is a bug in the bandcamp extractor--it should exit after falling back to the generic extractor once--or if the generic extractor needs to cycle through once more maybe this could be limited to `--extractor-retries * 2` ??

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp -v -j https://bandcamp.com/
[debug] Command-line config: ['-v', '-j', 'https://bandcamp.com/']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.07.18 [135f05e]
[debug] Python 3.10.5 (CPython 64bit) - Linux-5.18.13-200.fc36.x86_64-x86_64-with-glibc2.35 (glibc 2.35)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 5.0.1 (setts), ffprobe 5.0.1, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, secretstorage-3.3.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] [generic] Extracting URL: https://bandcamp.com/
[generic] bandcamp: Downloading webpage
WARNING: [generic] Falling back on generic information extractor.
[generic] bandcamp: Extracting information
[debug] Looking for video embeds
[debug] [generic] Extracting URL: https://bandcamp.com
[generic] bandcamp: Downloading webpage
WARNING: [generic] Falling back on generic information extractor.
[generic] bandcamp: Extracting information
[debug] Looking for video embeds
[debug] [generic] Extracting URL: https://bandcamp.com
[generic] bandcamp: Downloading webpage
WARNING: [generic] Falling back on generic information extractor.
[generic] bandcamp: Extracting information
[debug] Looking for video embeds
[debug] [generic] Extracting URL: https://bandcamp.com
[generic] bandcamp: Downloading webpage
WARNING: [generic] Falling back on generic information extractor.
[generic] bandcamp: Extracting information
[debug] Looking for video embeds
[debug] [generic] Extracting URL: https://bandcamp.com
[generic] bandcamp: Downloading webpage
WARNING: [generic] Falling back on generic information extractor.
^C
```
```

**Comment by coletdjnz** [comment]
Seems to be  "fixed" in master. 

Git bisect gives me https://github.com/yt-dlp/yt-dlp/commit/bfd973ece3369c593b5e82a88cc16de80088a73e as fixing it.

Don't think this was intentional though, might be worth checking. cc @pukkandan

**Comment by pukkandan** [comment]
Bandcamp's embed detection code was too broad. And yes, the issue got fixed because the new system checks it against valid url
