### ISSUE TITLE
funimation: login with token

### ISSUE THREAD

**Issue by Rafawell** [yt-dlp/yt-dlp#4549]
.

**Comment by pukkandan** [comment]
No clue what you are asking. Elaborate

**Comment by Rafawell** [comment]
Hi pukkandan. Sorry for the poorly worded question.
Could put the option to access Funimation with the user token?
Being able to access without having to enter the username and password, if the person already has the token

![image](https://user-images.githubusercontent.com/45123500/182741722-5e5b7787-16a6-4f1f-8dd1-054297d2a41b.png)

**Comment by Rafawell** [comment]
I was quite confused about how to proceed, and if the question would lead to an improvement.
I'm really sorry!!!
