### ISSUE TITLE
Bunkr.is

### ISSUE THREAD

**Issue by reahari** [yt-dlp/yt-dlp#4556]
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.07.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

India

### Example URLs

- Single Video https://cdn4.bunkr.is/bigbuckbunny-b4VHMTTI.mp4
- Album/playlist https://bunkr.is/a/hNJhvMle

### Provide a description that is worded well enough to be understood

Please add support for single videos and playlists hosted on bunkr.is.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://cdn4.bunkr.is/bigbuckbunny-b4VHMTTI.mp4']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.07.18 [135f05e]
[debug] Python 3.10.4 (CPython 64bit) - Linux-5.15.0-43-generic-x86_64-with-glibc2.35 (glibc 2.35)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.14.1, brotli-1.0.9, certifi-2021.10.08, mutagen-1.45.1, pyxattr-0.7.2, secretstorage-3.3.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.07.18, Current version: 2022.07.18
yt-dlp is up to date (2022.07.18)
[debug] [generic] Extracting URL: https://cdn4.bunkr.is/bigbuckbunny-b4VHMTTI.mp4
[generic] bigbuckbunny-b4VHMTTI: Downloading webpage
[redirect] Following redirect to https://stream.bunkr.is/v/bigbuckbunny-b4VHMTTI.mp4
[debug] [generic] Extracting URL: https://stream.bunkr.is/v/bigbuckbunny-b4VHMTTI.mp4
[generic] bigbuckbunny-b4VHMTTI: Downloading webpage
WARNING: [generic] Falling back on generic information extractor.
[generic] bigbuckbunny-b4VHMTTI: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://stream.bunkr.is/v/bigbuckbunny-b4VHMTTI.mp4
Traceback (most recent call last):
  File "/home/$USER/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1431, in wrapper
    return func(self, *args, **kwargs)
  File "/home/$USER/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1506, in __extract_info
    ie_result = ie.extract(url)
  File "/home/$USER/.local/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 644, in extract
    ie_result = self._real_extract(url)
  File "/home/$USER/.local/lib/python3.10/site-packages/yt_dlp/extractor/generic.py", line 4108, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://stream.bunkr.is/v/bigbuckbunny-b4VHMTTI.mp4
```

**Comment by october262** [comment]
did you try the download button in the upper right corner of the video ??

**Comment by reahari** [comment]
Yes, of course. The url is an example video. The request is for yt-dlp to support the site, not a question about how to download the video

**Comment by HobbyistDev** [comment]
Your url redirect to `https://stream.bunkr.is/v/bigbuckbunny-b4VHMTTI.mp4` and we can extract the video from the webpage, escpecially from this part:
```html
<script id="__NEXT_DATA__" type="application/json">
      {
        "props": {
          "pageProps": {
            "file": {
              "name": "bigbuckbunny-b4VHMTTI.mp4",
              "size": "4233370",
              "mediafiles": "https://media-files4.bunkr.is"
            }
          },
          "__N_SSG": true
        },
        "page": "/v/[videoId]",
        "query": {
          "videoId": "bigbuckbunny-b4VHMTTI.mp4"
        },
        "buildId": "LakDNa2po0X6HoGr8Tfkc",
        "isFallback": false,
        "gsp": true,
        "scriptLoader": []
      }
    </script>
```
To get the video, we can just request to `<mediafiles>/<name>`

Here's the log:
```shell
(python_proj2) ~\yt-dlp>python -m yt_dlp -v "https://media-files4.bunkr.is/bigbuckbunny-b4VHMTTI.mp4" --ignore-config
[debug] Command-line config: ['-v', 'https://media-files4.bunkr.is/bigbuckbunny-b4VHMTTI.mp4', '--ignore-config']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.08.08 [3157158f7] (source)
[debug] Lazy loading extractors is disabled
[debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
[debug] Git HEAD: cd4df5ffa
[debug] Python 3.10.4 (CPython 64bit) - Windows-10-10.0.22000-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 5.1-full_build-www.gyan.dev (setts), ffprobe 5.1-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.14.1, brotli-1.0.9, certifi-2022.05.18.1, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] [generic] Extracting URL: https://media-files4.bunkr.is/bigbuckbunny-b4VHMTTI.mp4
[generic] bigbuckbunny-b4VHMTTI: Downloading webpage
[debug] Identified a direct video link
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), channels, vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] bigbuckbunny-b4VHMTTI: Downloading 1 format(s): mp4
[debug] Invoking http downloader on "https://media-files4.bunkr.is/bigbuckbunny-b4VHMTTI.mp4"
[debug] File locking is not supported. Proceeding without locking
[download] Destination: bigbuckbunny-b4VHMTTI [bigbuckbunny-b4VHMTTI].mp4
[download]  24.7% of 4.04MiB at  599.56KiB/s ETA 00:05
ERROR: Interrupted by user
```

**Comment by reahari** [comment]
I've updated the original issue to add in a link to an album featuring multiple videos https://bunkr.is/a/hNJhvMle

**Comment by pukkandan** [comment]
> - [x] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge

Looks like a piracy site. Explain your reason to believe otherwise

**Comment by seproDev** [comment]
https://github.com/yt-dlp/yt-dlp/wiki/FAQ#why-is-there-a-rule-against-websites-primarily-used-for-piracy
