### ISSUE TITLE
Bad performance (requires over 5 seconds for simple --dump-json)

### ISSUE THREAD

**Issue by AgentSmith0** [yt-dlp/yt-dlp#4558]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.07.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

If you request `yt-dlp --dump-json <any video link>`, it can take up to 5 seconds to get the information. Is there any way to speed up the process?

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
not needed for this problem
```

**Comment by pukkandan** [comment]
First off, use verbose log to figure out which steps are contributing most to the slowdown. Then according to the specifics, any of these may help: https://github.com/yt-dlp/yt-dlp/pull/860#issuecomment-911141453 https://github.com/yt-dlp/yt-dlp/issues/4090#issuecomment-1158102032 https://github.com/yt-dlp/yt-dlp/pull/3234

I could have tried to guess by seeing the verbose, but since you have determined it is "not needed" despite being MANDATORY, nothing to be done

**Comment by pukkandan** [comment]
> I've also noticed that yt-dlp downloads many files when trying to extract the URL: first it says "Downloading webpage", then "Downloading android player API JSON". Is this really necessary?

It is necessary for robustness and future proofing. If you don't care about them, there are `--extractor-args` to disable many of the steps. See the documentation for details

Note: Disabling webpage/android API can actually slow down some videos. See https://github.com/ytdl-org/youtube-dl/issues/30641#issuecomment-1042655621

> Also, are these checks really relevant for a simple JSON dump?

The checks are only done when using `--verbose`

> Using time command, I measured 4.159 seconds until I receive the JSON dump. You can try this with any video link.

Sure, but my question is, what steps are slow? Just the verbose head doesn't help much either. Use [this](https://github.com/yt-dlp/yt-dlp/issues/1866#issuecomment-985086619) (with `-v`) to figure out how long each step takes. Then you can look into disabling those steps 

---

Also, if yt-dlp is too slow for you despite any of these optimizations, I suggest looking at other libraries. This project primarily aims to be feature rich and robust. Extraction speed is a secondary concern.

**Comment by pukkandan** [comment]
> You can try this with any video link.

Why can't you just show your results!? `yt-dlp -j BaW_jenozKc > nul` only takes 1.9 secs for me

**Comment by pukkandan** [comment]
> Sorry, unfortunately `ts` command is not available and `while IFS= read -r line; do printf '%s %s\n' "$(date)" "$line"; done` didn't worked.

Then record your screen or something... As I have said multiple times, how do you expect anyone to help without knowing the details??

**Comment by CryZo** [comment]
@pukkandan thanks for your idea about the `--extractor-args`! I try to get metas about a whole channel. With default args this takes about 155s, but with `--extractor-args "youtube:player-client=web"` it "just" need 140s. So you gifted me 15s :tada:

**Comment by CryZo** [comment]
For anyone else facing this issue: There is a `--flat-playlist` argument. This makes the process lightning fast. However, there will be many fields missing like the like count or the comment count. If you don't care about them this arg is for you! ;)

**Comment by habibalamin** [comment]
>For anyone else facing this issue: There is a `--flat-playlist` argument. This makes the process lightning fast. However, there will be many fields missing like the like count or the comment count. If you don't care about them this arg is for you! ;)

Bro, thank you. I've been getting really annoyed with the looong wait times before YouTube videos start playing in IINA/mpv. I have zero use for likes and comments >99.9999% of the time, and testing a few runs with `time` with and without the flag reports that this literally shaves off ~95% off my waiting time.
