### ISSUE TITLE
"--ffmpeg-location" directory PATH breaks in config file, unless it's surrounded by quotations.

### ISSUE THREAD

**Issue by Raarl** [yt-dlp/yt-dlp#4559]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.07.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

When using a custom config file and contains the "--ffmpeg-location" argument, it requires that a user must place quotations on the PATH directory or an error occurs. The error displays the typed path but without its "/" in their respective places. 
In contrast, when writing on the command line quotations aren't required but optional.
Even when the config file has the encoding set to "UTF-8-BOM", the error occurs on the console.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--config-location', 'C:\\Users\\Computer\\Videos\\Youtube\\3.txt', 'https://www.youtube.com/watch?v=kkwiQmGWK4c']
[debug] | Config "C:\Users\Computer\Videos\Youtube\3.txt": ['--ffmpeg-location', 'C:UsersComputerVideosYoutubeffmpeg-5.0.1-full_buildbin']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.07.18 [135f05e] (win32_exe)
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
WARNING: ffmpeg-location C:UsersComputerVideosYoutubeffmpeg-5.0.1-full_buildbin does not exist! Continuing without ffmpeg
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
WARNING: ffmpeg-location C:UsersComputerVideosYoutubeffmpeg-5.0.1-full_buildbin does not exist! Continuing without ffmpeg
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.07.18, Current version: 2022.07.18
yt-dlp is up to date (2022.07.18)
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=kkwiQmGWK4c
[youtube] kkwiQmGWK4c: Downloading webpage
[youtube] kkwiQmGWK4c: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
WARNING: ffmpeg-location C:UsersComputerVideosYoutubeffmpeg-5.0.1-full_buildbin does not exist! Continuing without ffmpeg
[debug] Default format spec: best/bestvideo+bestaudio
[info] kkwiQmGWK4c: Downloading 1 format(s): 22
[debug] Invoking http downloader on "https://rr1---sn-aigl6nzs.googlevideo.com/videoplayback?expire=1659678971&ei=m1zsYoqMGNPdmwfCnpfADQ&ip=89.44.201.163&id=o-AM4tbnld8nQGPny1uk5YpAN5VnWjakHWHmY2B5T_wJtz&itag=22&source=youtube&requiressl=yes&mh=qo&mm=31%2C29&mn=sn-aigl6nzs%2Csn-aigzrne7&ms=au%2Crdu&mv=m&mvi=1&pl=24&initcwndbps=405000&vprv=1&mime=video%2Fmp4&cnr=14&ratebypass=yes&dur=38.939&lmt=1577675264659456&mt=1659656941&fvip=1&fexp=24001373%2C24007246&beids=23886212&c=ANDROID&rbqsm=fr&txp=5535432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Ccnr%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRgIhAMxwvPOMPdbwXlTRdSh677fcYKwulViR_WRsJHmifsVBAiEA9Ntn1r_YA1mO87QisqxkzF1r1tjeBQQon8q3KONlArM%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAIhtAFMzbD-kIQjcRLwDUev7BkV9Le8ijsnoKBkojG6sAiEA6Ud9F_yol1ijpv1_ZBZIgngJQIySt4sjYFVg7UH2v7g%3D"
[debug] File locking is not supported. Proceeding without locking
[download] Destination: Talking cat says Oh Long Johnson [kkwiQmGWK4c].mp4
[download] 100% of 3.10MiB in 00:02
```

**Comment by Lesmiscore** [comment]
Escape the backslashes.
Presumably be `C:\\Users\\Computer\\Videos\\Youtube\\ffmpeg-5.0.1-full_build\\bin`

**Comment by pukkandan** [comment]
Yes, that is how command lines work 😐
