### ISSUE TITLE
[vhx:embed] /subscriptions/ URLs

### ISSUE THREAD

**Issue by wxolp** [yt-dlp/yt-dlp#4560]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.07.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Provide a description that is worded well enough to be understood

`/videos/` URLs work, but not `/subscriptions/`

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://embed.vhx.tv/subscriptions/28599?vimeo=1']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.07.18 [135f05e]
[debug] Python 3.10.4 (CPython 64bit) - Windows-10-10.0.18363-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: avprobe -bsfs
[debug] exe versions: ffmpeg 2022-06-09-git-5d5a014199-essentials_build-www.gyan.dev (setts)
[debug] Optional libraries: Cryptodome-3.15.0, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.07.18, Current version: 2022.07.18
yt-dlp is up to date (2022.07.18)
[debug] [generic] Extracting URL: https://embed.vhx.tv/subscriptions/28599?vimeo=1
[generic] 28599?vimeo=1: Downloading webpage
WARNING: [generic] Falling back on generic information extractor.
[generic] 28599?vimeo=1: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://embed.vhx.tv/subscriptions/28599?vimeo=1
Traceback (most recent call last):
  File "C:\python\lib\site-packages\yt_dlp\YoutubeDL.py", line 1431, in wrapper
    return func(self, *args, **kwargs)
  File "C:\python\lib\site-packages\yt_dlp\YoutubeDL.py", line 1506, in __extract_info
    ie_result = ie.extract(url)
  File "C:\python\lib\site-packages\yt_dlp\extractor\common.py", line 644, in extract
    ie_result = self._real_extract(url)
  File "C:\python\lib\site-packages\yt_dlp\extractor\generic.py", line 4108, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://embed.vhx.tv/subscriptions/28599?vimeo=1
```

**Comment by pukkandan** [comment]
Using alt accounts to bypass ban is not appreciated. Let's see what GitHub support has say about this
