### ISSUE TITLE
FIFA: HTTPError 404: 'Not Found'

### ISSUE THREAD

**Issue by RingoTheDog** [yt-dlp/yt-dlp#4566]
URL: https://www.fifa.com/fifaplus/en/watch/4V8H8qv7QM1LNVk5gUwYFa

> 
> yt-dlp.py -v "https://www.fifa.com/fifaplus/en/watch/4V8H8qv7QM1LNVk5gUwYFa" [debug] Command-line config: ['-v', 'https://www.fifa.com/fifaplus/en/watch/4V8H8qv7QM1LNVk5gUwYFa'] [debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8 [debug] yt-dlp version 2022.07.18 [[135f05e](https://github.com/yt-dlp/yt-dlp/commit/135f05ef667851869756ad3bf892726e376db27c)] (zip) [debug] Python 3.10.6 (CPython 64bit) - Windows-10-10.0.17763-SP0 [debug] Checking exe version: ffmpeg -bsfs [debug] Checking exe version: ffprobe -bsfs [debug] exe versions: ffmpeg 4.3.2-2021-02-02-full_build-www.gyan.dev, ffprobe 4.3.2-2021-02-02-full_build-www.gyan.dev, rtmpdump 2.4 [debug] Optional libraries: sqlite3-2.6.0 [debug] Proxy map: {} [debug] [Fifa] Extracting URL: https://www.fifa.com/fifaplus/en/watch/4V8H8qv7QM1LNVk5gUwYFa [Fifa] 4V8H8qv7QM1LNVk5gUwYFa: Downloading webpage [Fifa] 4V8H8qv7QM1LNVk5gUwYFa: Downloading Video Details [Fifa] 4V8H8qv7QM1LNVk5gUwYFa: Downloading Preplay Parameters ERROR: [Fifa] 4V8H8qv7QM1LNVk5gUwYFa: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using yt-dlp -U File "C:\Transmogrifier\yt-dlp.py\yt_dlp\extractor\common.py", line 644, in extract ie_result = self._real_extract(url) File "C:\Transmogrifier\yt-dlp.py\yt_dlp\extractor\fifa.py", line 62, in _real_extract preplay_parameters = self._download_json( File "C:\Transmogrifier\yt-dlp.py\yt_dlp\extractor\common.py", line 1004, in download_content res = getattr(self, download_handle.**name**)(url_or_request, video_id, **kwargs) File "C:\Transmogrifier\yt-dlp.py\yt_dlp\extractor\common.py", line 968, in download_handle res = self._download_webpage_handle( File "C:\Transmogrifier\yt-dlp.py\yt_dlp\extractor\common.py", line 838, in _download_webpage_handle urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query, expected_status=expected_status) File "C:\Transmogrifier\yt-dlp.py\yt_dlp\extractor\common.py", line 795, in _request_webpage raise ExtractorError(errmsg, cause=err)
> 
> File "C:\Transmogrifier\yt-dlp.py\yt_dlp\extractor\common.py", line 777, in _request_webpage return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query)) File "C:\Transmogrifier\yt-dlp.py\yt_dlp\YoutubeDL.py", line 3639, in urlopen return self._opener.open(req, timeout=self._socket_timeout) File "C:\Program Files\Python310\lib\urllib\request.py", line 525, in open response = meth(req, response) File "C:\Program Files\Python310\lib\urllib\request.py", line 634, in http_response response = self.parent.error( File "C:\Program Files\Python310\lib\urllib\request.py", line 563, in error return self._call_chain(*args) File "C:\Program Files\Python310\lib\urllib\request.py", line 496, in _call_chain result = func(*args) File "C:\Program Files\Python310\lib\urllib\request.py", line 643, in http_error_default raise HTTPError(req.full_url, code, msg, hdrs, fp) urllib.error.HTTPError: HTTP Error 404: Not Found
> 

Looks like Fifa has changed API's url.

Just need to change
https://github.com/yt-dlp/yt-dlp/blob/aeaf905e22614812e29c652a8140feaae08ce279/yt_dlp/extractor/fifa.py#L62-L63

to
```
        preplay_parameters = self._download_json(
            f'{preconnect_link}/videoPlayerData/{video_id}', video_id, 'Downloading Preplay Parameters')['preplayParameters']
```

_Originally posted by @Bricio in https://github.com/yt-dlp/yt-dlp/issues/3633#issuecomment-1205953337_

**Comment by pukkandan** [comment]
How is this different from #3633?

**Comment by Bricio** [comment]
> How is this different from #3633?

#3633 is a problem in the matching url, that should not match urls with something between /watch and video id. And to add the support for that urls.
https://github.com/yt-dlp/yt-dlp/blob/aeaf905e22614812e29c652a8140feaae08ce279/yt_dlp/extractor/fifa.py#L11

> I think it's any URL with /movies/ or /series/ in URL between /watch/ and video id, so any video that's not a match replay.

To solve that we need to create extractors, or some program flow, to identify this urls, and process it correctly. 
That is what #3640 is about.

---

This one is a change in FIFA's API.
Every url are not working right now. Even urls that was working before. Like the first test.
https://github.com/yt-dlp/yt-dlp/blob/aeaf905e22614812e29c652a8140feaae08ce279/yt_dlp/extractor/fifa.py#L13

```
D:\ytdlp>yt-dlp.exe -Uv "https://www.fifa.com/fifaplus/en/watch/7on10qPcnyLajDDU3ntg6y"
[debug] Command-line config: ['-Uv', 'https://www.fifa.com/fifaplus/en/watch/7on10qPcnyLajDDU3ntg6y']
[debug] Portable config "D:\ytdlp\yt-dlp.conf": ['--ffmpeg-location', '.\\ffmpeg\\bin', '--ignore-config']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8 (No VT), error utf-8 (No VT), screen utf-8 (No VT)
[debug] yt-dlp version 2022.07.18 [135f05e] (win32_exe)
[debug] Python 3.8.10 (CPython 64bit) - Windows-7-6.1.7601-SP1
[debug] Checking exe version: ".\ffmpeg\bin\ffmpeg" -bsfs
[debug] Checking exe version: ".\ffmpeg\bin\ffprobe" -bsfs
[debug] exe versions: ffmpeg N-105453-gcc5eb2e662-20220204 (setts), ffprobe N-105453-gcc5eb2e662-20220204
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.07.18, Current version: 2022.07.18
yt-dlp is up to date (2022.07.18)
[debug] [Fifa] Extracting URL: https://www.fifa.com/fifaplus/en/watch/7on10qPcnyLajDDU3ntg6y
[Fifa] 7on10qPcnyLajDDU3ntg6y: Downloading webpage
[Fifa] 7on10qPcnyLajDDU3ntg6y: Downloading Video Details
[Fifa] 7on10qPcnyLajDDU3ntg6y: Downloading Preplay Parameters
ERROR: [Fifa] 7on10qPcnyLajDDU3ntg6y: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 644, in extract
  File "yt_dlp\extractor\fifa.py", line 62, in _real_extract
  File "yt_dlp\extractor\common.py", line 1004, in download_content
  File "yt_dlp\extractor\common.py", line 968, in download_handle
  File "yt_dlp\extractor\common.py", line 838, in _download_webpage_handle
  File "yt_dlp\extractor\common.py", line 795, in _request_webpage

  File "yt_dlp\extractor\common.py", line 777, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 3639, in urlopen
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

```

It is an easy fix, but a different kind of problem.

**Comment by yashkc2025** [comment]
Hey, I am a newbie so I have a question does this fix include modifying fifa.py only. Can i give it a try ?
