### ISSUE TITLE
Add support for javmix.tv (NSFW)

### ISSUE THREAD

**Issue by thomco** [yt-dlp/yt-dlp#4568]
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.07.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

United States

### Example URLs

https://javmix.tv/fc2ppv/fc2ppv-3049947
https://javmix.tv/fc2ppv/fc2ppv-3064666

### Provide a description that is worded well enough to be understood

Attempts to download from the site result in Unsupported URL errors

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://javmix.tv/fc2ppv/fc2ppv-3064328/']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.07.18 [135f05e] (win32_exe)
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.22622-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: avconv -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: avprobe -bsfs
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.07.18, Current version: 2022.07.18
yt-dlp is up to date (2022.07.18)
[debug] [generic] Extracting URL: https://javmix.tv/fc2ppv/fc2ppv-3064328/
[generic] fc2ppv-3064328: Downloading webpage
WARNING: [generic] Falling back on generic information extractor.
[generic] fc2ppv-3064328: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://javmix.tv/fc2ppv/fc2ppv-3064328/
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1431, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1506, in __extract_info
  File "yt_dlp\extractor\common.py", line 644, in extract
  File "yt_dlp\extractor\generic.py", line 4108, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://javmix.tv/fc2ppv/fc2ppv-3064328/
```

**Comment by thomco** [comment]
@pukkandan why was this closed?

**Comment by pukkandan** [comment]
![image](https://user-images.githubusercontent.com/6623388/183105284-78b5fdcc-b70f-4fe5-8fdf-cf1c9d4ee84e.png)

**Comment by pukkandan** [comment]
![image](https://user-images.githubusercontent.com/6623388/183105366-6bbc2167-ae41-42bd-be74-4a7cc2f3ebbe.png)

**Comment by thomco** [comment]
@pukkandan Does that label mean that the site contains illegal or pirated content?
