### ISSUE TITLE
Disney

### ISSUE THREAD

**Issue by heroku-miraheze** [yt-dlp/yt-dlp#4572]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.07.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Worldwide

### Provide a description that is worded well enough to be understood

Disney sites is broken.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
WARNING: [Disney] Failed to download m3u8 information: HTTP Error 404: Not Found
<!DOCTYPE html>
<html lang="es-419">
  <head>
    <title>Aviso importante</title>
    <link rel="stylesheet" type="text/css" href="https://static-mh.content.disney.io/matterhorn/assets/waystation/emea-exit-4e9e8d79e0d7.css">
    <link rel="canonical" href="https://mh-kaltura.akamaized.net/s/p/1068292/sp/106829200/serveFlavor/entryId/1_ljvu5ii7/v/1/pv/1/ev/6/flavorId/1_k2z8pbj8/fileName/Aprendiendo_con_Mickey_(DIS-HD_1080_-_WEB_(H264_4000)).mp4/forceproxy/true/name/a.mp4?__hdnea__=st=1659741806~exp=1659767006~acl=/s/p/1068292/sp/106829200/serveFlavor/entryId/1_ljvu5ii7/v/1/pv/1/ev/6/flavorId/1*~hmac=48ad41029f5372a9872b5fb38f4c20d9ec091013f3a2236db2aa602fd47a7a19">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>
  <body dir="ltr">
    <div class="container">
      <div id="message">
        <div class="header">Estás saliendo de Disney</div>
        <div class="body">La página web que estás a punto de visitar no se encuentra gestionada ni controlada por Disney. Ten en cuenta que se aplicarán distintos términos de uso y políticas de privacidad.</div>
      </div>
      <div id="options">
        <a id="cancel" href="javascript:void(0);" class="button">Volver a Disney</a>
        <a id="continue" class="button primary" href="https://mh-kaltura.akamaized.net/s/p/1068292/sp/106829200/serveFlavor/entryId/1_ljvu5ii7/v/1/pv/1/ev/6/flavorId/1_k2z8pbj8/fileName/Aprendiendo_con_Mickey_(DIS-HD_1080_-_WEB_(H264_4000)).mp4/forceproxy/true/name/a.mp4?__hdnea__=st=1659741806~exp=1659767006~acl=/s/p/1068292/sp/106829200/serveFlavor/entryId/1_ljvu5ii7/v/1/pv/1/ev/6/flavorId/1*~hmac=48ad41029f5372a9872b5fb38f4c20d9ec091013f3a2236db2aa602fd47a7a19">Sí, continuar</a>
      </div>
    </div>
    <script type="text/javascript" src="https://static-mh.content.disney.io/matterhorn/assets/waystation/exit-9a193a4d7551.js"></script>
  </body>
</html>
```

**Comment by gamer191** [comment]
That's not a verbose log
