### ISSUE TITLE
tviplayer just one url tipe work.

### ISSUE THREAD

**Issue by nunotfc** [yt-dlp/yt-dlp#4578]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.07.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Portugal

### Provide a description that is worded well enough to be understood

this particular site, tvi player, we have one url tipes that work, "https://tviplayer.iol.pt/programa/jornal-da-uma/53c6b2633004dc00624392e1/video/62e296370cf26256cd2f3a99
but in the same site, this doesnt work:
https://tviplayer.iol.pt/programa/para-sempre/61716c360cf2365a5ed894c4/episodio/t1e187

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://tviplayer.iol.pt/programa/para-sempre/61716c360cf2365a5ed894c4/episodio/t1e187']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out cp1252 (No ANSI), error cp1252 (No ANSI), screen cp1252 (No ANSI)
[debug] yt-dlp version 2022.07.18 [135f05e] (win32_exe)
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0 
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: avprobe -bsfs
[debug] exe versions: ffmpeg n5.0-ffmpeg-windows-build-helpers (setts)
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.07.18, Current version: 2022.07.18
yt-dlp is up to date (2022.07.18)
[debug] [generic] Extracting URL: https://tviplayer.iol.pt/programa/para-sempre/61716c360cf2365a5ed894c4/episodio/t1e187
[generic] t1e187: Downloading webpage
WARNING: [generic] Falling back on generic information extractor.
[generic] t1e187: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://tviplayer.iol.pt/programa/para-sempre/61716c360cf2365a5ed894c4/episodio/t1e187
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1431, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1506, in __extract_info
  File "yt_dlp\extractor\common.py", line 644, in extract
  File "yt_dlp\extractor\generic.py", line 4108, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://tviplayer.iol.pt/programa/para-sempre/61716c360cf2365a5ed894c4/episodio/t1e187
```

**Comment by HobbyistDev** [comment]
This patch is work
```diff
@@ -3,7 +3,7 @@
 class TVIPlayerIE(InfoExtractor):
-    _VALID_URL = r'https?://tviplayer\.iol\.pt(/programa/[\w-]+/[a-f0-9]+)?/video/(?P<id>[a-f0-9]+)'
+    _VALID_URL = r'https?://tviplayer\.iol\.pt(/programa/[\w-]+/[a-f0-9]+)?/\w+/(?P<id>\w+)'
     _TESTS = [{
         'url': 'https://tviplayer.iol.pt/programa/jornal-das-8/53c6b3903004dc006243d0cf/video/61c8e8b90cf2c7ea0f0f71a9',
         'info_dict': {
```

**Comment by pukkandan** [comment]
> This patch works (at least for OP url)
> 
> ```diff
> @@ -3,7 +3,7 @@
>  class TVIPlayerIE(InfoExtractor):
> -    _VALID_URL = r'https?://tviplayer\.iol\.pt(/programa/[\w-]+/[a-f0-9]+)?/video/(?P<id>[a-f0-9]+)'
> +    _VALID_URL = r'https?://tviplayer\.iol\.pt(/programa/[\w-]+/[a-f0-9]+)?/\w+/(?P<id>\w+)'
>      _TESTS = [{
>          'url': 'https://tviplayer.iol.pt/programa/jornal-das-8/53c6b3903004dc006243d0cf/video/61c8e8b90cf2c7ea0f0f71a9',
>          'info_dict': {
> ```
> 
> I didn't check other url type

Since OP only gave this one URL. I'll merge if someone PRs this patch and adds a relevant test

**Comment by nunotfc** [comment]
"https://tviplayer.iol.pt/programa/para-sempre/61716c360cf2365a5ed894c4/episodio/t1e187"
[generic] t1e187: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] t1e187: Extracting information
ERROR: Unsupported URL: https://tviplayer.iol.pt/programa/para-sempre/61716c360cf2365a5ed894c4/episodio/t1e187

**Comment by pukkandan** [comment]
Wait for next release

**Comment by nunotfc** [comment]
i'm testing directly compiling in latest commit, but ok, thanks! i will wait.

**Comment by pukkandan** [comment]
```
❯ yt-dlp https://tviplayer.iol.pt/programa/para-sempre/61716c360cf2365a5ed894c4/episodio/t1e187
[TVIPlayer] wmsAuthSign: Trying to get wmsAuthSign token
[TVIPlayer] t1e187: Downloading webpage
[TVIPlayer] t1e187: Downloading m3u8 information
[info] t1e187: Downloading 1 format(s): 2500
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 126
[download] Destination: Quem denunciou Pedro？ [t1e187].mp4
[download]   0.1% of ~341.75MiB at  192.69KiB/s ETA 30:14 (frag 0/126)
ERROR: Interrupted by user
```
