### ISSUE TITLE
[youtube] Video codec selected by yt-dlp doesn't provide the highest quality

### ISSUE THREAD

**Issue by Pyxia-Code** [yt-dlp/yt-dlp#458]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running yt-dlp version **2021.06.23**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
[debug] Command-line config: ['--skip-download', 'https://www.youtube.com/watch?v=Dnw6-ntk3SY', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] yt-dlp version 2021.06.23 
[debug] Python version 3.9.5 (CPython 64bit) - Linux-5.12.7-gnu-hardened1-1-hardened-x86_64-with-glibc2.33
[debug] exe versions: ffmpeg 4.4, ffprobe 4.4, rtmpdump 2.4
[debug] Proxy map: {}
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=Dnw6-ntk3SY
[youtube] Dnw6-ntk3SY: Downloading webpage
[youtube] Dnw6-ntk3SY: Downloading MPD manifest
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] Dnw6-ntk3SY: Downloading 1 format(s): 303+251
```

## Description

By default yt-dlp seems to download videos encoded with the VP9 codec first which from my tests doesn't seem to offer the best possible quality when downloading from youtube.
When youtube only offers a video in VP9 and H.264 then H.264 has the highest quality:
![comparison-redone](https://user-images.githubusercontent.com/61087807/123873790-5b1d2f00-d937-11eb-8b40-c9a2e2fceb76.png)
https://www.youtube.com/watch?v=Dnw6-ntk3SY

![comparison](https://user-images.githubusercontent.com/61087807/123873894-86a01980-d937-11eb-8a31-752b94d95815.png)
https://www.youtube.com/watch?v=fy16LjNLWjk

And in the case when youtube also offers the video in AV1, then it seems that AV1 > VP9 > H.264 in terms of quality:
![comparison](https://user-images.githubusercontent.com/61087807/123874072-d4b51d00-d937-11eb-8289-6573a8c23a42.png)
https://www.youtube.com/watch?v=spcauG9AnGI

![comparison](https://user-images.githubusercontent.com/61087807/123874114-e72f5680-d937-11eb-9751-2673263acdaf.png)
https://www.youtube.com/watch?v=RAhqxvgQYn0

My guess is that the quality depends on which codec was used by the original video. I think that most people use H.264 so the version reencoded to VP9 has lower quality and when a video is available in AV1 then it was the original codec used to encode the video so it has the highest quality.
VBR reported by youtube doesn't seem to play a role here, because when comparing the quality of these videos:
https://www.youtube.com/watch?v=spcauG9AnGI (Highest VBR - H.264)
https://www.youtube.com/watch?v=rXHpFOG-fcY (Highest VBR - VP9)
https://www.youtube.com/watch?v=RAhqxvgQYn0 (Highest VBR - AV1)
all of them seem to have the highest quality in AV1 even though the codec with the highest VBR seem to be different for every video.

It should be possible to solve this by changing the format sort used by the youtube extractor to first check for AV1 then for H.264 and only then for VP9.

Command I've used to download videos for comparison:
```
yt-dlp VIDEO_URL -f FORMAT
```
All of the screenshots were taken using mpv with screenshot-format=png

**Comment by Jules-A** [comment]
AV1 isn't really widely supported yet but users can just use something like `-S res,codec:av1` if they prefer AV1. As for VP9/H.264, in my experience VP9 produces slight better results on average with decently lower bitrates but can slip up on some videos. If you want to prefer AV1>H.264>VP9 then I think you can just use `-S res,codec:av1,codec:avc' (not sure what yt-dlp uses to identify h.264).

**Comment by Pyxia-Code** [comment]
> AV1 isn't really widely supported yet but users can just use something like `-S res,codec:av1` if they prefer AV1. As for VP9/H.264, in my experience VP9 produces slight better results on average with decently lower bitrates but can slip up on some videos. If you want to prefer AV1>H.264>VP9 then I think you can just use `-S res,codec:av1,codec:avc' (not sure what yt-dlp uses to identify h.264).

-S res,codec:av1,codec:h264,codec:vp9 does what I want.
In my case in 2 videos I've tested where only these 2 codecs were available H.264 performed better than VP9 but it might depend on the content of the video and the strengths and weaknesses of codecs so as you said it might sometimes perform better and sometimes worse. I guess I'll wait for the opinion of the devs on this.

**Comment by pukkandan** [comment]
> When youtube only offers a video in VP9 and H.264 then H.264 has the highest quality:
> And in the case when youtube also offers the video in AV1, then it seems that AV1 > VP9 > H.264 in terms of quality:

This is not a general rule. The relative quality of different encodings depends on a lot of factors including the actual content of the video itself. There is no objective way of testing the actual "quality" of the video formats without downloading them first. Generally, `av01>vp9>h264` in terms of quality. But `av01` is not yet playable by most devices. So yt-dlp choses `vp9>h264>av1` (this is an over-simplification based on youtube only). You can make it prefer av1 with `vcodec:av1` in `-S` if you want

> -S res,codec:av1,codec:h264,codec:vp9 does what I want.

No. This is equivalent to just using `-S res,codec:av1` (gives av1>vp9>h264). `-S` is a format **sorting** option. The command you gave is like asking to sort the alphabets starting at `N`, then sort again starting at `D` - Only the last sort will have any effect. There is an (untracked) request to allow multiple entries for the sort-preference, but no such feature is yet implemented.

Currently, the only way to do `av1>h264>vp9` is to use `-f`

**Comment by hronro** [comment]
@pukkandan 

This is really confusing for me.

When I saw this in `README.md`:

> The default format sorting options have been changed so that higher resolution and better codecs will be now preferred instead of simply using larger bitrate.

Until I saw this issue, I thought it would prefer av1 codec by default since av1 is the best codec before h266(VVC) is coming out.

> But av01 is not yet playable by most devices.

This is not true. There are some free and open-source decoders like [dav1d](https://code.videolan.org/videolan/dav1d), which uses CPU to decode instead of some specific hardware. With proper player apps, most of my devices can play av1 videos (including my 3-years-old iPhone, my 4-years-old Google Pixel, my MacBook Pro, and my Windows PC).

**Comment by hronro** [comment]
@Pyxia-Code 

> My guess is that the quality depends on which codec was used by the original video. I think that most people use H.264 so the version reencoded to VP9 has lower quality and when a video is available in AV1 then it was the original codec used to encode the video so it has the highest quality.

This is not true. YouTube re-encodes every video no matter that the original codec of the video is. After re-encodes, every format YouTube offers would be lossy. From my experience, `av01` is always the best choice for best quality.

**Comment by pukkandan** [comment]
The readme was recently edited to clarify this.

```
the default order used is: lang,quality,res,fps,codec:vp9.2,...

Note that the default has codec:vp9.2; i.e. av1 is not prefered
```

I will make AV1 default only after atleast all major OSes start supporting it See [this list](https://www.wikiwand.com/en/AV1#/Operating_system_support). Hopefully, most new devices will also have hardware support for it by then

I don't understand why people complain about this. You have the option to just put something like `-S res,vcodec:av1` in a config file and forget about it. 

The default option should work for the most non-techie users and a codec that is still not natively supported on popular OSes is not a good default

**Comment by hronro** [comment]
@pukkandan 

I respect the decision you made, I just want to point out the container formats that `yt-dlp` currently used for vp9 (mkv/webm), are not supported by most OSes neither.

**Comment by chrizilla** [comment]
> @pukkandan [said](https://github.com/yt-dlp/yt-dlp/issues/458#issuecomment-872654985):
> Currently, the only way to do `av1>h264>vp9` is to use `-f`

like  `-f "(bv*+ba/b)[vcodec=av01] / (bv*+ba/b)[vcodec=h264] / (bv*+ba/b)[vcodec=vp9] / (bv*+ba/b)"` ?

**Comment by milahu** [comment]
https://github.com/yt-dlp/yt-dlp/issues/458#issuecomment-1007917391 did not work for me

currently im using multiple calls to yt-dlp

```sh
H=720
f="bestvideo[height<=$H][ext=mp4]+bestaudio[ext=m4a]/0/iphone-$Hp/best[height<=$H]"

# h264 > av1 > vp9
yt-dlp -f "$f" -S vcodec:h264 "$@" ||
yt-dlp -f "$f" -S vcodec:av1 "$@" ||
yt-dlp -f "$f" "$@"
```

**Comment by Xan-Kun** [comment]
I dont really see this as a 'feature'. Lots of machines have no HW support for it. Furthermore it is MUCH easier to make AV1 prefered via filters, than the other way around. Esp. when using the by far most popular parameter [height].
