### ISSUE TITLE
Split Chapters -- Chapter Title Too Long

### ISSUE THREAD

**Issue by pp611** [yt-dlp/yt-dlp#4582]
### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.07.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I am using the --split-chapters option. It works well until today it ran into really long chapter titles (basically descriptions. one example: https://www.youtube.com/watch?v=xF1-4kiG03o).

I am looking either a way, with one or two examples, to specify a template for the split chapter output files. Or a way just to simply truncate the file names within certain length.

If it is not achievable now, can it be made an enhancement request?

Thanks

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
Please explain which part of this you did not understand
![image](https://user-images.githubusercontent.com/6623388/183257537-f983d0a0-ee77-4cff-956d-27ce05d2f555.png)
---

Show verbose log

**Comment by pp611** [comment]
Here is the log: (which shows the file name too long)

[SplitChapters] Splitting video by chapters; 37 chapters found
[SplitChapters] Chapter 001; Destination: Beethoven - Symphony no.1 - Score and Analysis - 001 Introduction. The symphony jokingly begins with a series of endings (perfect cadences), followed by a gorgeous chorale passage that builds tension by avoiding the home key of C major, reserving its appearance for the start of the exposition. [xF1-4kiG03o].opus
ERROR: Postprocessing: file:Beethoven - Symphony no.1 - Score and Analysis - 001 Introduction. The symphony jokingly begins with a series of endings (perfect cadences), followed by a gorgeous chorale passage that builds tension by avoiding the home key of C major, reserving its appearance for the start of the exposition. [xF1-4kiG03o].opus: File name too long

What I  did not figure out was that the "-o" option is for the output file naming of the download before split, could not figure out how to specify a template for the --split-chapters options

**Comment by pukkandan** [comment]
See https://github.com/yt-dlp/yt-dlp/issues/1136#issuecomment-932077195

**Comment by Flashwalker** [comment]
> See [#1136 (comment)](https://github.com/yt-dlp/yt-dlp/issues/1136#issuecomment-932077195)


Actually, the '`-o "%(title).250s.%(ext)s"`' is ignored for '`--split-chapters`'.


```
yt-dlp -c -f ba --concurrent-fragments 4 --sponsorblock-remove all --output-na-placeholder "" --embed-metadata --embed-thumbnail --no-mtime -o "%(title).250s.%(ext)s" https://www.youtube.com/watch?v=Qj_cpIJCSCU

[youtube] Extracting URL: https://www.youtube.com/watch?v=Qj_cpIJCSCU https://www.youtube.com/watch?v=-DfpODKC7VU https://w.../watch?v=BrWKXqOD_RU
[youtube] Qj_cpIJCSCU: Downloading webpage
[youtube] Qj_cpIJCSCU: Downloading ios player API JSON
[youtube] Qj_cpIJCSCU: Downloading player bd3293c9
WARNING: [youtube] Qj_cpIJCSCU: nsig extraction failed: Some formats may be missing
         n = 586HWpoliosAqWx2ypW ; player = https://www.youtube.com/s/player/bd3293c9/player-plasma-ias-tablet-en_US.vflset/base.js
WARNING: [youtube] Qj_cpIJCSCU: nsig extraction failed: Some formats may be missing
         n = lry8uYCEmygBZF4gQh5 ; player = https://www.youtube.com/s/player/bd3293c9/player-plasma-ias-tablet-en_US.vflset/base.js
[youtube] Qj_cpIJCSCU: Downloading m3u8 information
WARNING: [youtube] unable to extract yt initial data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [youtube] Incomplete data received in embedded initial data; re-fetching using API.
[youtube] Qj_cpIJCSCU: Downloading initial data API JSON
[SponsorBlock] Fetching SponsorBlock segments
[SponsorBlock] No matching segments were found in the SponsorBlock database
[info] Qj_cpIJCSCU: Downloading 1 format(s): 140
[info] Downloading video thumbnail 42 ...
[info] Writing video thumbnail 42 to: #692 Разговор вайшнава с Кришной. Санскрит, Курукшетра. Волга, Самара, Тула. Ангелы-проводники. Ч.1..webp
[download] Destination: #692 Разговор вайшнава с Кришной. Санскрит, Курукшетра. Волга, Самара, Тула. Ангелы-проводники. Ч.1..m4a
[download] 100% of   33.25MiB in 00:00:37 at 919.82KiB/s
[FixupM4a] Correcting container of "#692 Разговор вайшнава с Кришной. Санскрит, Курукшетра. Волга, Самара, Тула. Ангелы-проводники. Ч.1..m4a"
[ModifyChapters] SponsorBlock information is unavailable
[Metadata] Adding metadata to "#692 Разговор вайшнава с Кришной. Санскрит, Курукшетра. Волга, Самара, Тула. Ангелы-проводники. Ч.1..m4a"
[ThumbnailsConvertor] Converting thumbnail "#692 Разговор вайшнава с Кришной. Санскрит, Курукшетра. Волга, Самара, Тула. Ангелы-проводники. Ч.1..webp" to png
[EmbedThumbnail] mutagen: Adding thumbnail to "#692 Разговор вайшнава с Кришной. Санскрит, Курукшетра. Волга, Самара, Тула. Ангелы-проводники. Ч.1..m4a"
[SplitChapters] Splitting video by chapters; 7 chapters found
[SplitChapters] Chapter 001; Destination: #692 Разговор вайшнава с Кришной. Санскрит, Курукшетра. Волга, Самара, Тула. Ангелы-проводники. Ч.1. - 001 ＜Untitled Chapter 1＞ [Qj_cpIJCSCU].m4a
[SplitChapters] Chapter 002; Destination: #692 Разговор вайшнава с Кришной. Санскрит, Курукшетра. Волга, Самара, Тула. Ангелы-проводники. Ч.1. - 002 Вопросы о родине Кришны [Qj_cpIJCSCU].m4a
[SplitChapters] Chapter 003; Destination: #692 Разговор вайшнава с Кришной. Санскрит, Курукшетра. Волга, Самара, Тула. Ангелы-проводники. Ч.1. - 003 Происхождение языка и названия рек [Qj_cpIJCSCU].m4a
ERROR: Postprocessing: file:#692 Разговор вайшнава с Кришной. Санскрит, Курукшетра. Волга, Самара, Тула. Ангелы-проводники. Ч.1. - 003 Происхождение языка и названия рек [Qj_cpIJCSCU].m4a: File name too long
```

**Comment by bashonly** [comment]
@Flashwalker use `section_title` instead of `title` for sections
