### ISSUE TITLE
Booyah.com support 

### ISSUE THREAD

**Issue by denaunistic** [yt-dlp/yt-dlp#4583]
### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.07.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

United states

### Example URLs

Single video: https://booyah.live/clips/13887261322952306617
Single video: https://booyah.live/clips/13620401526858573419?source=3
User: https://booyah.live/studio/10843280

### Provide a description that is worded well enough to be understood

yt-dlp is currently unable to extract video or audio from the website.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://booyah.live/clips/13887261322952306617']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.07.18 [135f05e] (win32_exe)
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 2022-07-14-git-882aac99d2-essentials_build-www.gyan.dev (setts), ffprobe 2022-07-14-git-882aac99d2-essentials_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.07.18, Current version: 2022.07.18
yt-dlp is up to date (2022.07.18)
[debug] [generic] Extracting URL: https://booyah.live/clips/13887261322952306617
[generic] 13887261322952306617: Downloading webpage
WARNING: [generic] Falling back on generic information extractor.
[generic] 13887261322952306617: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://booyah.live/clips/13887261322952306617
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1431, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1506, in __extract_info
  File "yt_dlp\extractor\common.py", line 644, in extract
  File "yt_dlp\extractor\generic.py", line 4108, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://booyah.live/clips/13887261322952306617
```

**Comment by HobbyistDev** [comment]
The video api json can be found in `https://booyah.live/api/v3/playbacks/<video_id>`. We can extract the video in `json['playback']['endpoint_list']`

Here's the sample of `endpoint_list`:
```
"endpoint_list": [
    {
      "stream_url": "https://google-gcp.cdn.booyah.live/Clip/10843280/10843280-6c109a02-719a-4059-844d-67d863c5987e.mp4",
      "download_url": "https://google-gcp.cdn.booyah.live/Clip/10843280/10843280-6c109a02-719a-4059-844d-67d863c5987e_watermark.mp4",
      "resolution": 640,
      "bitrate": 1544258
    },
    {
      "stream_url": "https://google-gcp.cdn.booyah.live/Clip/10843280/10843280-6c109a02-719a-4059-844d-67d863c5987e_480.mp4",
      "download_url": "https://google-gcp.cdn.booyah.live/Clip/10843280/10843280-6c109a02-719a-4059-844d-67d863c5987e_watermark.mp4",
      "resolution": 480,
      "bitrate": 1344000
    },
    {
      "stream_url": "https://google-gcp.cdn.booyah.live/Clip/10843280/10843280-6c109a02-719a-4059-844d-67d863c5987e_360.mp4",
      "download_url": "https://google-gcp.cdn.booyah.live/Clip/10843280/10843280-6c109a02-719a-4059-844d-67d863c5987e_watermark.mp4",
      "resolution": 360,
      "bitrate": 784000
    },
    {
      "stream_url": "https://google-gcp.cdn.booyah.live/Clip/10843280/10843280-6c109a02-719a-4059-844d-67d863c5987e_240.mp4",
      "download_url": "https://google-gcp.cdn.booyah.live/Clip/10843280/10843280-6c109a02-719a-4059-844d-67d863c5987e_watermark.mp4",
      "resolution": 240,
      "bitrate": 424000
    },
    {
      "stream_url": "https://google-gcp.cdn.booyah.live/Clip/10843280/10843280-6c109a02-719a-4059-844d-67d863c5987e_160.mp4",
      "download_url": "https://google-gcp.cdn.booyah.live/Clip/10843280/10843280-6c109a02-719a-4059-844d-67d863c5987e_watermark.mp4",
      "resolution": 160,
      "bitrate": 304000
    }
  ]
```
The video url is both `stream_url` and `download_url`. However, link in `download_url` get watermark.
However, this api url require `Booyah-Session-Key` in the header. At the moment, i don't know where this value came from. I guess it's from cookie.

**Comment by HobbyistDev** [comment]
The `Booyah-Session-Key` seems returned from this url "https://booyah.live/api/v3/auths/sessions". However, this url need request body (at least `""`). This url needs to send in POST Method. We can get `Booyah-Session-Key` either from header or cookie (with `session_key` key)
