### ISSUE TITLE
Youtube DASH downloads time out on specific video/format combinations

### ISSUE THREAD

**Issue by EIREXE** [yt-dlp/yt-dlp#4584]
### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.07.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Western Europe, Peninsular Spain

### Provide a description that is worded well enough to be understood

On some specific videos, for example https://www.youtube.com/watch?v=YanU3nQC4v0, using yt-dlp to obtain a DASH video stream, such as the second smallest webm-dash video in the above video:

`247      webm  1280x720    24 │ ~ 16.54MiB 1505k dash  │ vp9         1505k video only          DASH video, webm_dash`

This might not be a yt-dlp bug, but rather some form of youtube throttling, although I have seen this same issue on actual browsers, so I don't know what to believe anymore with this cursed website.

I believe this is caused by some form of youtube mechanism to ensure you watch an AD before the video is played, similar issues from normal youtube users using ublock origin (such as myself, although this only happens to me on my parent's home machine, not on my own).

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
./yt-dlp.sh -vU -f 247 'https://www.youtube.com/watch?v=YanU3nQC4v0'
[debug] Command-line config: ['-vU', '-f', '247', 'https://www.youtube.com/watch?v=YanU3nQC4v0']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.07.18 [135f05ef6] (source)
[debug] Lazy loading extractors is disabled
[debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
[debug] Git HEAD: 43aebb7db
[debug] Python 3.10.5 (CPython 64bit) - Linux-5.18.15-arch1-1-x86_64-with-glibc2.36 (glibc 2.36)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 5.0.1 (setts), ffprobe 5.0.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.14.1, brotli-1.0.9, certifi-2021.10.08, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.2
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.07.18, Current version: 2022.07.18
yt-dlp is up to date (2022.07.18)
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=YanU3nQC4v0
[youtube] YanU3nQC4v0: Downloading webpage
[youtube] YanU3nQC4v0: Downloading android player API JSON
[youtube] YanU3nQC4v0: Downloading MPD manifest
[youtube] YanU3nQC4v0: Downloading MPD manifest
[info] YanU3nQC4v0: Downloading 1 format(s): 247
[dashsegments] Total fragments: 19
[download] Destination: ermoanga sensei intro (tv-size) (original) [YanU3nQC4v0].webm
[download]  73.7% of ~10.51MiB at   11.26MiB/s ETA 00:00 (frag 14/19)[download] Got error: The read operation timed out. Retrying (1/10)...
[download] Got error: <urlopen error _ssl.c:980: The handshake operation timed out>. Retrying (2/10)...
[download]  94.7% of ~10.75MiB at    1.41MiB/s ETA 00:09 (frag 18/19)[download] Got error: The read operation timed out. Retrying (1/10)...
[download] Got error: <urlopen error _ssl.c:980: The handshake operation timed out>. Retrying (2/10)...
[download] 100% of 10.61MiB in 01:29 at 121.57KiB/s
```

**Comment by pukkandan** [comment]
1. That is not the "complete verbose log"
2. What exactly is the issue? From the limited log given, it looks like yt-dlp automatically retried and finished the download

**Comment by EIREXE** [comment]
> 1. That is not the "complete verbose log"
> 
>     2. What exactly is the issue? From the limited log given, it looks like yt-dlp automatically retried and finished the download

my bad, botched copy paste job, it should be ok now

The issue is that these timeouts massively reduce download speeds, and they seem to happen randomly without any issue on the network.

**Comment by pukkandan** [comment]
I doubt the timeouts are the cause of slow speed. DASH downloads are just slow by nature. Use `-N` or `--downloader aria2c` to speed it up

Anyway, this is not an issue we can do anything about
