### ISSUE TITLE
9gag.com - NineGagIE - InfoExtractor - add Uploader info to the returned metadata

### ISSUE THREAD

**Issue by DjesonPV** [yt-dlp/yt-dlp#4587]
### Checklist

- [X] I'm requesting a site-specific feature
- [X] I've verified that I'm running yt-dlp version **2022.07.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Example URLs

https://9gag.com/gag/a119eY2 (Anonymous Uploader)
https://9gag.com/gag/ajgp66G (Non-Anonymous Uploader)

### Provide a description that is worded well enough to be understood

9gag recently added the uploader of a post on the website.

I would like to know if you could add uploader informations to the return metadata if the uploader isn't anonymous.

That could be done with the already extracted JSON stored by the variable `post`.
Then it's a matter of getting the `creator = post.get('creator')`, if it is not `null` we can get :

`uploader =  creator['fullName']`,
`uploader_id = creator['username']`,
`uploader_url = url_or_none(creator[('profileUrl'])`

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
No verbose it's just a request feature to add addiotional metadata to an already existing InfoExtractor.
```

**Comment by pukkandan** [comment]
> No verbose it's just a request feature to add addiotional metadata to an already existing InfoExtractor.

You realize the field is mandatory for a reason, right? I am sick of people evading the issue template 😩 

The point is to show us what you have tried to get the requested "feature" and so make sure it doesn't already exist. Too many times, we get requests for features that are already supported

**Comment by DjesonPV** [comment]
> The point is to show us what you have tried to get the requested "feature" and so make sure it doesn't already exist.

I looked up at the NineGag InfoExtractor it's only 128 lines, it never return nor get this specific data. So no matter how hard you will try, how many verbose you print, it will never appear.

`./extractor/ninegag.py` lines 115-128
```python
  class NineGagIE(InfoExtractor):
    def _real_extract(self, url) :
        return {
            'id': post_id,
            'title': title,
            'timestamp': int_or_none(post.get('creationTs')),
            'duration': duration,
            'formats': formats,
            'thumbnails': thumbnails,
            'like_count': get_count('upVote'),
            'dislike_count': get_count('downVote'),
            'comment_count': get_count('comments'),
            'age_limit': 18 if post.get('nsfw') == 1 else None,
            'categories': [section] if section else None,
            'tags': tags,
        }
```

**Comment by pukkandan** [comment]
Sure, you were competent enough to provide sufficient information without needing verbose log. Hence why I did not mark the issue as `incomplete`. But the fact is that those who are not similarly competent also generally think that they are! Having the verbose makes it easier to look for user error at a glance without me actually having to check the code/trying to reproduce. When I am dealing with dozens of issues every day, it does make a difference. It often also reveals issues that even experienced users may overlook. I hope you get where I am coming from

---

That aside, since this is a pretty simple issue, and you seem comfortable modifying the code, would you like to make a PR?

**Comment by DjesonPV** [comment]
Working on it !
