### ISSUE TITLE
dailymotion.com links are not downloading 

### ISSUE THREAD

**Issue by DikshaBB** [yt-dlp/yt-dlp#4588]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.07.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

https://www.dailymotion.com/video/x8cwd60

You can try this.
Unable to download any videos from Dailymotion.com.

I am using these commads
commands = [
    "yt-dlp",
    "--continue",
    "--embed-subs",
    "--no-warnings",
    "-f",
    video_format,
    "--hls-prefer-ffmpeg",
    "--prefer-ffmpeg",
    "-o",
    output_directory,
    input_url,
]

**Comment by gamer191** [comment]
Please post a verbose log. You can look at your posts edit history to see what a verbose log is.
