### ISSUE TITLE
Add Fancy Extractors/Webpage Name

### ISSUE THREAD

**Issue by DjesonPV** [yt-dlp/yt-dlp#4589]
### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.07.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

I work on a private Discord Bot, and I use yt-dlp to basically make a music bot.
When the bot is playing it displays data about the current track.
Thanks to all the extractors provided, there is a lot of websites to get media content to play.

When displaying media metadata, I like to print the name of the website of the video playing.
Currently this can be done by using either the `webpage_url_domain` or the `extractor` or the `extractor_key`.

As exemples :
- YouTube
`webpage_url_domain: 'youtube.com'`
`extractor: 'youtube'`
`extractor_key: 'Youtube'`

- 9GAG
`webpage_url_domain: '9gag.com'`
`extractor: '9gag'`
`extractor_key: 'NineGag'`

- Twitch Clips
`webpage_url_domain: 'twitch.tv'`
`extractor: 'twitch:clips'`
`extractor_key: 'TwitchClips'`

My request is then : Could you provide a `website_name` value to the returned metadata of InfoExtractors?

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
What would that contain? How is it different from domain/extractor?

**Comment by DjesonPV** [comment]
The `website_name` would give the brand/web name in its "Human form" with space and punctuation, which could be transcriptions of their logo.

It would be used for a display/esthetics need rather than a technical functionality.

- youtube.com : `'YouTube'`, 
- 9gag.com : `'9GAG'`,
- twitch.com/clips : `'Twitch Clips'`,
- abc.net.au : `'ABC (Australian Broadcasting Corporation)'`,
- adobeconnect.com : `'Adobe Connect'`,
- cbs.com : `'CBS TV Network'`,
- nytimes.com : `'The New York Times'`,
- washingtonpost.com : `'The Washington Post'`,
- francetvinfo.fr : `'franceinfo:'`
- bfmtv.com : `'BFM TV.'`

**Comment by pukkandan** [comment]
So `IE_DESC`? (See `yt-dlp --extractor-desc`

Though, most sites don't currently define this field. PR to add it for more extractors is welcome

**Comment by DjesonPV** [comment]
Exactly !
Sorry my bad

**Comment by pukkandan** [comment]
No worries. Would you like to contribute descriptions for the above-mentioned extractors?

**Comment by DjesonPV** [comment]
I'll probably do it soon
