### ISSUE TITLE
How to ignore errors?

### ISSUE THREAD

**Issue by cochraneserver** [yt-dlp/yt-dlp#4598]
### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.07.18** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I am trying to configure my docker-compose file to ignore errors. I was running into an issue where failure to retrieve/download a thumbnail would cause the entire download to fail.

This is my working file (in bold), and I am trying to add an option to ignore the error

**version: "3"
services:
  metube:
    image: alexta69/metube
    container_name: metube
    restart: unless-stopped
    ports:
      - "8081:8081"
    volumes:
      - /mnt/media/Downloads/MeTube:/downloads
    environment:
      UID: 1000
      GID: 1002**
      YTDL_OPTIONS: "{ignoreerrors:download_only}"

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
Set ignoreerrors to True

**Comment by cochraneserver** [comment]
Is there a better way to do the formatting? I'm trying what's below which docker accepts but MeTube logs show it's an invalid option. I had played around with setting it to true previously and was getting the same problem- no doubt my formatting is wrong I'm just not sure how to set it properly.

YTDL_OPTIONS: "{ignoreerrors:true}"


Thanks,

**Comment by pukkandan** [comment]
No idea. This is not metube's issue tracker
