### ISSUE TITLE
featreq: Exception-less break_on_existing with skip_download=True

### ISSUE THREAD

**Issue by chapmanjacobd** [yt-dlp/yt-dlp#4602]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.08.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

I would like to be able to use the `break-on-existing` feature but still get back the downloaded metadata up to that point.

In the app that I'm writing I create a [fake download archive](https://github.com/chapmanjacobd/lb/blob/main/xklb/tube_extract.py#L33) so that existing metadata does not need to be re-downloaded while getting information about new videos of known playlists--but I get an `ExistingVideoReached` exception and the data is not returned.

```shell
python -m xklb.lb tubeadd test.db --yt-dlp-config 'playlist_start=5' https://www.youtube.com/user/billwurtz/videos
python -m xklb.lb tubeupdate test.db -vv https://www.youtube.com/user/billwurtz/videos
```
I'm using this config:

```
    "skip_download": True,
    "force_write_download_archive": True,
    "check_formats": False,
    "no_check_certificate": True,
    "no_warnings": True,
    "ignore_no_formats_error": True,
    "ignoreerrors": "only_download", # I also tried True
    "skip_playlist_after_errors": 20,
    "quiet": True,
    "dynamic_mpd": False,
    "youtube_include_dash_manifest": False,
    "youtube_include_hls_manifest": False,
    "extract_flat": True,
    "clean_infojson": False,
```

Alternatively, if `playliststart` could be optimized such that `50-100` takes a similar amount of time as `1-50` I could go about this by iterating through each playlist chunks at a time until there is no more metadata... that would be a better solution. or if there is a way to stream metadata one dict at a time...? right now getting playlist items 50-100 seems to take ~2x the time as 1-50. I get the feeling the playlist indexing might be impossible to speed up due to differences across extractors

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
--break-on-existing was modelled off of --max-downloads, which was only ever designed to properly work in CLI. I'll see what I can do. At minimum, I should be able to return the info as a property of the exception

> Alternatively, if playliststart could be optimized such that 50-100 takes a similar amount of time as 1-50

This is not possible because of how youtube's paging works. For sites where this is optimizable, we do

> or if there is a way to stream metadata one dict at a time...?

This is possible by registering a postprocessor (that acts as a callback). See https://github.com/yt-dlp/yt-dlp#add-a-custom-postprocessor

**Comment by chapmanjacobd** [comment]
> This is possible by registering a postprocessor

kind of... but after playing with it for a couple hours I've realized it is not quite early enough

What does `playlist POSTPROCESS_WHEN` mean? I tried it but could not get it to trigger. Would it be possible to add a callback for pagination (after each page is downloaded in a playlist?

The main issue with postprocessor hooks is that the full playlist (all the pages) are still being downloaded before it goes to the first `pre_process`  post_processor.

**Comment by pukkandan** [comment]
> that kind of defeats the point of a break-on-existing alternative in my usecase

I was thinking you'd use it alongside `break-on-existing`. That way, the PP saves info_dicts while yt-dlp handles breaking

> The main issue with postprocessor hooks is that the full playlist (all the pages) are still being downloaded before it goes to the first pre_process post_processor 

You can use `'lazy_playlist': True`

    lazy_playlist:     Process playlist entries as they are received.

> What does playlist POSTPROCESS_WHEN mean?

After the entire playlist is downloaded. Definitely not what you want

> Would it be possible to add a callback with the infodict for pagination (after each page of metadata is downloaded in a playlist, before downloading the next page of metadata)

This would be difficult. The way pagination happens is an implementation detail and is different b/w extractors.

**Comment by chapmanjacobd** [comment]
> alongside break-on-existing

I tried this initially but it didn't trigger the PP. I think that was my fault though. I'll try it again with better testing data if lazy_playlist doesn't work for me

I am feeling confident that some combination of `lazy_playlist`  will allow me to easily get the results that I want. I'm surprised I hadn't seen that one before.

I will close this but feel free to reopen or reference it in patches

**Comment by chapmanjacobd** [comment]
Yeah `lazy-playlist` is awesome!! I got it working without needing to hack around `skip_download` or `break_on_existing`

```py
class AddToArchivePP(yt_dlp.postprocessor.PostProcessor):
  current_video_count = 0

  def run(self, info):
      entry = self._add_media(deepcopy(info))
      self._add_playlist(deepcopy(info), entry)

      self.current_video_count += 1
      sys.stdout.write("\033[K\r")
      print(f"{playlist_path}: added {self.current_video_count} videos", end="\r", flush=True)
      return [], info

  def _add_media(self, entry):
      entry = consolidate(playlist_path, entry)
      if entry:
          if video_known(args, playlist_path, entry["path"]):
              raise ExistingPlaylistVideoReached
          save_entries(args, [entry])
      return entry

  def _add_playlist(self, pl, entry):
      pl = dict(
          ie_key=safe_unpack(pl.get("ie_key"), pl.get("extractor_key"), pl.get("extractor")),
          title=pl.get("playlist_title"),
          path=playlist_path,
          uploader=safe_unpack(pl.get("playlist_uploader_id"), pl.get("playlist_uploader")),
          id=pl.get("playlist_id"),
      )
      if entry["path"] == pl["path"] or not pl.get("id"):
          log.warning("Importing playlist-less media %s", pl["path"])
      elif playlist_known(args, playlist_path):
          pass
      else:
          plDF = pd.DataFrame([pl])
          plDF.convert_dtypes().to_sql("playlists", con=args.con, if_exists="append", index=False)

with yt_dlp.YoutubeDL(args.ydl_opts) as ydl:
    ydl.add_post_processor(AddToArchivePP(), when="pre_process")

    try:
        pl = ydl.extract_info(playlist_path, download=False, process=True)
    except ExistingPlaylistVideoReached:
        log_problem(args, playlist_path)
    else:
        if not pl:
            log_problem(args, playlist_path)
```

https://github.com/chapmanjacobd/lb/blob/9b01003749b4aac99145e134f2268026636ff213/xklb/tube_extract.py#L247

https://github.com/chapmanjacobd/lb#quick-start----virtual

![tubeadd_multi](https://user-images.githubusercontent.com/7908073/184713492-af3b2676-9a9d-4dde-808a-fa4076607f85.svg)

**Comment by chapmanjacobd** [comment]
hmmm... one issue I'm having with this is that playlists of playlists are not be fully resolved/iterated over. I need to have 1:1 path => media for various reasons (streaming one media at a time instead of the whole playlist, lineage tracking...). I need to figure out how to get video objects instead of playlist objects because that is what my program is expecting.

I found this comment super helpful: https://github.com/yt-dlp/yt-dlp/issues/1918#issuecomment-988565697

my first attempt is not good:
```
    class AddToArchivePP(yt_dlp.postprocessor.PostProcessor):
        current_video_count = 0

        def run(self, info) -> Tuple[list, dict]:
            if info:
                if hasattr(info, 'playlist_count'): # this doesn't actually trigger anything because when="pre_process"
                    url = safe_unpack(info.get("webpage_url", None), info.get("url", None))
                    super.extract_info(url, download=False, process=True)  # recursive call...
                    return [], info
                entry = self._add_media(deepcopy(info))
```

second attempt: I feel like I'm getting closer...

```
    class AddToArchivePP(yt_dlp.postprocessor.PostProcessor):
        current_video_count = 0

        def run(self, info) -> Tuple[list, dict]:
            if info:
                if hasattr(info, 'webpage_url_basename') and info['webpage_url_basename'] == 'playlist':
                    processed_info = super.process_ie_result(info)
                    breakpoint()
                    return [], info
                entry = self._add_media(deepcopy(info))
```


Looking through https://github.com/swolegoal/squid-dl/blob/main/squid_dl/downloader.py 
what does this do?
```
        "extractor_args": {
            "youtube": {"player_skip": ["webpage"]},
            "youtubetab": {"skip": ["webpage"]},
        },
```

hmm

```
  /home/xk/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py(3385)run_pp()
   3383             infodict['__files_to_move'] = {}
   3384         try:
-> 3385             files_to_delete, infodict = pp.run(infodict)
   3386         except PostProcessingError as e:
   3387             # Must be True and not 'only_download'

  /home/xk/.local/lib/python3.10/site-packages/yt_dlp/postprocessor/common.py(24)run()
     22             info_copy = self._copy_infodict(info)
     23             self._hook_progress({'status': 'started'}, info_copy)
---> 24             ret = func(self, info, *args, **kwargs)
     25             if ret is not None:
     26                 _, info = ret

> /home/xk/github/xk/lb/xklb/tube_backend.py(370)run()
    368 
    369         def run(self, info) -> Tuple[list, dict]:
--> 370             raise
    371             if info:
    372                 if hasattr(info, 'playlist_count'):

ipdb> super.process_ie_result(info)
*** AttributeError: type object 'super' has no attribute 'process_ie_result'
ipdb> print(info)
{
    'ie_key': 'YoutubeTab',
    'id': 'OLAK5uy_nmtgIjf-fGR7QD5UCFYAGkHWDdv1i2jrc',
    'title': "Don't Stop (Remixes)",
    '_type': 'url',
    'url': 'https://www.youtube.com/playlist?list=OLAK5uy_nmtgIjf-fGR7QD5UCFYAGkHWDdv1i2jrc',
    '__x_forwarded_for_ip': None,
    'webpage_url': 'https://www.youtube.com/playlist?list=OLAK5uy_nmtgIjf-fGR7QD5UCFYAGkHWDdv1i2jrc',
    'original_url': 'https://www.youtube.com/playlist?list=OLAK5uy_nmtgIjf-fGR7QD5UCFYAGkHWDdv1i2jrc',
    'webpage_url_basename': 'playlist',
    'webpage_url_domain': 'youtube.com',
    'extractor': 'youtube:tab',
    'extractor_key': 'YoutubeTab',
    'playlist_count': None,
    'playlist': 'Drömhus - Topic - Playlists',
    'playlist_id': 'UCi0cyXmLBP5dNEItUufv9kg',
    'playlist_title': 'Drömhus - Topic - Playlists',
    'playlist_uploader': 'Drömhus - Topic',
    'playlist_uploader_id': 'UCi0cyXmLBP5dNEItUufv9kg',
    'n_entries': None,
    'playlist_index': 1,
    '__last_playlist_index': 0,
    'playlist_autonumber': 1,
    '__files_to_move': {}
}
```

maybe there needs to be another post-processor `WHEN` which can run per video (after redirect/playlists are processed) ?

**Comment by chapmanjacobd** [comment]
nevermind! this works just fine

```py
def process_playlist(args, playlist_path, ydl_opts) -> Union[List[Dict], None]:
    class ExistingPlaylistVideoReached(yt_dlp.DownloadCancelled):
        pass

    class AddToArchivePP(yt_dlp.postprocessor.PostProcessor):
        current_video_count = 0

        def run(self, info) -> Tuple[list, dict]:
            if info:
                if info.get('webpage_url_basename') == 'playlist':
                    url = safe_unpack(info.get("webpage_url", None), info.get("url", None), info.get("original_url", None))
                    process_playlist(args, url, ydl_opts) # I just needed to do this lol..
                    return [], info
                entry = self._add_media(deepcopy(info))
                if entry:
...
```

**Comment by pukkandan** [comment]
Just so we are on the same page, you are using extract_flat, correct?

**Comment by chapmanjacobd** [comment]
yep. I just realized it's probably not possible to know if something is a playlist or not without fetching more metadata... kinda sad

**Comment by pukkandan** [comment]
the simplest solution is indeed to remove flat extraction. If that is not an option for you, as you guessed, distinguishing playlist from video is indeed tricky in general. But if you are only concerned about youtube, your best bet would be to look at `ie_key`. Alternatively, you can try and match the URL against known video URL patterns
