### ISSUE TITLE
[EmbedThumbnail] Error The system cannot find the file specified

### ISSUE THREAD

**Issue by HDark15** [yt-dlp/yt-dlp#4604]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.08.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

The video [https://youtu.be/ZgvglIhHwp4](url)
Fail to [EmbedThumbnail], the file cannot be found because of different name.

The error, ERROR: [WinError 2] The system cannot find the file specified: '[20220808] 【ASMR】スリスリとぞくぞくとろける様に眠れる。聞くだけで寝る！睡眠誘導。 氷・耳かき・マッサージ・顔そり 99.99% of You Will DEEP SLEEP, Relax【周防パトラ 】 - ZgvglIhHwp4.png'

The files it creates
- [20220808] 【ASMR】スリスリとぞくぞくとろける様に眠れる。聞くだけで寝る！睡眠誘導。氷・耳かき・マッサージ・顔そり 99.99% of You Will DEEP SLEEP, Relax【周防パトラ 】 - ZgvglIhHwp4.m4a
- [20220808] 【ASMR】スリスリとぞくぞくとろける様に眠れる。聞くだけで寝る！睡眠誘導。氷・耳かき・マッサージ・顔そり 99.99% of You Will DEEP SLEEP, Relax【周防パトラ 】 - ZgvglIhHwp4.webp
- [20220808] 【ASMR】スリスリとぞくぞくとろける様に眠れる。聞くだけで寝る！睡眠誘導。氷・耳かき・マッサージ・顔そり 99.99%% of You Will DEEP SLEEP, Relax【周防パトラ 】 - ZgvglIhHwp4.png

Comparing the files of png we can see that the file it wants to find has one (%) in (99.99%), But the existing file has two % (99.99%%).  The same problem occurs with YouTube video that has (%) on the title. 

Edit: deleting metadata

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '-r', '3M', '--windows-filenames', '-S', 'aext:m4a', '-f', 'bestaudio', '--embed-metadata', '--embed-thumbnail', '-o', '[%(upload_date)s] %(title)s - %(id)s.%(ext)s', 'https://youtu.be/ZgvglIhHwp4']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.08.08 [3157158] (win32_exe)
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.19041-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg N-107703-g68e017c487-20220808 (setts), ffprobe N-107703-g68e017c487-20220808
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.08.08, Current version: 2022.08.08
yt-dlp is up to date (2022.08.08)
[debug] [youtube] Extracting URL: https://youtu.be/ZgvglIhHwp4
[youtube] ZgvglIhHwp4: Downloading webpage
[youtube] ZgvglIhHwp4: Downloading android player API JSON
[debug] Loading youtube-nsig.0d77e7db from cache
[debug] [youtube] Decrypted nsig kU0Fn4lnlDf1NvDB => Ekd4-k1LRglrdA
[debug] Sort order given by user: aext:m4a
[debug] Sort order given by extractor: quality, res, fps, hdr:12, channels, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, aext:m4a(8), quality, res, fps, hdr:12(7), channels, source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, hasaud, id
[info] ZgvglIhHwp4: Downloading 1 format(s): 140
[info] Downloading video thumbnail 44 ...
[info] Writing video thumbnail 44 to: [20220808] 【ASMR】スリスリとぞくぞくとろける様に眠れる。聞くだけで寝る！睡眠誘導。氷・耳かき・マッサージ・顔
そり 99.99% of You Will DEEP SLEEP, Relax【周防パトラ 】 - ZgvglIhHwp4.webp
[debug] Invoking http downloader on "https://rr3---sn-jx25uoxu-jb3l.googlevideo.com/videoplayback?expire=1660051624&ei=SAzyYtrxGLiA9fwPzOuzuAg&ip=103.83.93.138&id=o-AIq5-QryN-apK-KTZh9H3GFFQ2qF6TZXTf6_xxOPBUeL&itag=140&source=youtube&requiressl=yes&mh=B6&mm=31%2C29&mn=sn-jx25uoxu-jb3l%2Csn-npoe7ney&ms=au%2Crdu&mv=m&mvi=3&pcm2cms=yes&pl=24&initcwndbps=578750&spc=lT-Khk1TBqAjgemjgb1zsN_j1FSGbOc&vprv=1&svpuc=1&mime=audio%2Fmp4&gir=yes&clen=120604076&dur=7452.049&lmt=1659979374375708&mt=1660029432&fvip=4&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&rbqsm=fr&txp=7318224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRgIhALb_V6IOGfiAabmrnsWgZuNgWhIncdQGrZ6S1QYVvsIFAiEAg4FlnJ3gp0nTpOHONu20ZdDRSYddFDiAkI1CZt7jLA8%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAPNRdWziiBY0Xm-THyaC6sNZYbNzIUiO6X5Wgjxzhx6yAiEA6m-XVUbuD73HlSJun3ikp34GCnq3rx-XUnNO-TU6zQI%3D"
[debug] File locking is not supported. Proceeding without locking
[download] Destination: [20220808] 【ASMR】スリスリとぞくぞくとろける様に眠れる。聞くだけで寝る！睡眠誘導。氷・耳かき・マッサージ・顔そり 99.99% of You Will DEEP SLEEP, Relax【周防パトラ 】 - ZgvglIhHwp4.m4a
[download] 100% of 115.02MiB in 01:23 at 1.37MiB/s
[FixupM4a] Correcting container of "[20220808] 【ASMR】スリスリとぞくぞくとろける様に眠れる。聞くだけで寝る！睡眠誘導。氷・耳かき・マッサージ・顔そ
り 99.99% of You Will DEEP SLEEP, Relax【周防パトラ 】 - ZgvglIhHwp4.m4a"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:[20220808] 【ASMR】スリスリとぞくぞくとろける様に眠れる。聞くだけで寝る！睡
眠誘導。氷・耳かき・マッサージ・顔そり 99.99% of You Will DEEP SLEEP, Relax【周防パトラ 】 - ZgvglIhHwp4.m4a" -map 0 -dn -ignore_unknown -c copy -f mp4 -movflags "+faststart" "file:[20220808] 【ASMR】スリスリとぞくぞくとろける様に眠れる。聞くだけで寝る！睡眠誘導。氷・耳かき・マッサージ・顔そり 99.99% of You Will DEEP SLEEP, Relax【周防パトラ 】 - ZgvglIhHwp4.temp.m4a"
[ThumbnailsConvertor] Converting thumbnail "[20220808] 【ASMR】スリスリとぞくぞくとろける様に眠れる。聞くだけで寝る！睡眠誘導。氷・耳かき・マッサー
ジ・顔そり 99.99% of You Will DEEP SLEEP, Relax【周防パトラ 】 - ZgvglIhHwp4.webp" to png
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -f image2 -pattern_type none -i "file:[20220808] 【ASMR】スリスリとぞくぞくとろける様に眠れる。聞くだけで寝る！睡眠誘導。氷・耳かき・マッサージ・顔そり 99.99% of You Will DEEP SLEEP, Relax【周防パトラ 】 - ZgvglIhHwp4.webp" -movflags "+faststart" "file:[20220808] 【ASMR】スリスリとぞくぞくとろける様に眠れる。聞くだけで寝る！睡眠誘導。氷・耳かき・マッサージ・顔そり 99.99%% of You Will DEEP SLEEP, Relax【周防パトラ 】 - ZgvglIhHwp4.png"
[EmbedThumbnail] mutagen: Adding thumbnail to "[20220808] 【ASMR】スリスリとぞくぞくとろける様に眠れる。聞くだけで寝る！睡眠誘導。氷・耳かき・マッサージ・顔そり 99.99% of You Will DEEP SLEEP, Relax【周防パトラ 】 - ZgvglIhHwp4.m4a"
WARNING: unable to embed using mutagen; [Errno 2] No such file or directory: '[20220808] 【ASMR】スリスリとぞくぞくとろける様に眠れる。聞くだけで寝 る！睡眠誘導。氷・耳かき・マッサージ・顔そり 99.99% of You Will DEEP SLEEP, Relax【周防パトラ 】 - ZgvglIhHwp4.png'
[EmbedThumbnail] Neither mutagen nor AtomicParsley was found. Falling back to ffmpeg
[debug] ffprobe command line: ffprobe -hide_banner -show_format -show_streams -print_format json "file:[20220808] 【ASMR】スリスリとぞくぞくとろける様に眠れる。聞くだけで寝る！睡眠誘導。氷・耳かき・マッサージ・顔そり 99.99% of You Will DEEP SLEEP, Relax【周防パトラ 】 - ZgvglIhHwp4.m4a"
[EmbedThumbnail] ffmpeg: Adding thumbnail to "[20220808] 【ASMR】スリスリとぞくぞくとろける様に眠れる。聞くだけで寝る！睡眠誘導。氷・耳かき・マッサ
ージ・顔そり 99.99% of You Will DEEP SLEEP, Relax【周防パトラ 】 - ZgvglIhHwp4.m4a"
ERROR: [WinError 2] The system cannot find the file specified: '[20220808] 【ASMR】スリスリとぞくぞくとろける様に眠れる。聞くだけで寝る！睡眠誘導。 氷・耳かき・マッサージ・顔そり 99.99% of You Will DEEP SLEEP, Relax【周防パトラ 】 - ZgvglIhHwp4.png'
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1441, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1538, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1596, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2694, in process_video_result
  File "yt_dlp\YoutubeDL.py", line 3245, in process_info
  File "yt_dlp\YoutubeDL.py", line 3415, in post_process
  File "yt_dlp\YoutubeDL.py", line 3397, in run_all_pps
  File "yt_dlp\YoutubeDL.py", line 3376, in run_pp
  File "yt_dlp\postprocessor\common.py", line 24, in run
  File "yt_dlp\postprocessor\common.py", line 125, in wrapper
  File "yt_dlp\postprocessor\embedthumbnail.py", line 185, in run
  File "yt_dlp\postprocessor\ffmpeg.py", line 317, in run_ffmpeg_multiple_files
  File "yt_dlp\postprocessor\ffmpeg.py", line 324, in real_run_ffmpeg
  File "yt_dlp\postprocessor\ffmpeg.py", line 325, in <genexpr>
FileNotFoundError: [WinError 2] The system cannot find the file specified: '[20220808] 【ASMR】スリスリとぞくぞくとろける様に眠れる。聞くだけで寝る ！睡眠誘導。氷・耳かき・マッサージ・顔そり 99.99% of You Will DEEP SLEEP, Relax【周防パトラ 】 - ZgvglIhHwp4.png'
```

**Comment by dirkf** [comment]
This is in yt_dlp/postprocessor/ffmpeg.py:1087-1089 since 337e0c62f8:
```
        self.real_run_ffmpeg(
            [(thumbnail_filename, [] if source_ext == '.gif' else ['-f', 'image2', '-pattern_type', 'none'])],
            [(thumbnail_conv_filename.replace('%', '%%'), self._options(target_ext))])
```
This would be appropriate if the output filename was going to be the target of a % format, but it doesn't seem to be processed further and not in any way that the input filename isn't.

Perhaps you're the first person in the last 13 months to run a command embedding a .webp thumbnail as .png using the default to _ffmpeg_?

**Comment by heywolf15** [comment]
I remember having this problem before, but I just embed it using media player and never report it, what I download rarely has (%) on it. I'm always embedding the thumbnail, isn't it always download .webp then automatically convert it to .png? At least for me on the audio with .m4a and not on the video with .mkv, that's why there's an open issue for .webp being embedded as an attachment.

Sorry, I didn't get the question and EN isn't my first language.

**Comment by pukkandan** [comment]
I can't repro
```
❯ yt-dlp --embed-thumb ZgvglIhHwp4 -f wa -v -o "[%(upload_date)s] %(title)s - %(id)s.%(ext)s" --windows-filenames
[debug] Command-line config: ['--ignore-config', '--embed-thumb', 'ZgvglIhHwp4', '-f', 'wa', '-v', '-o', '[%(upload_date)s] %(title)s - %(id)s.%(ext)s', '--windows-filenames']
[debug] Encodings: locale cp65001, fs utf-8, pref cp65001, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.08.08 [3157158f7] (source)
[debug] Lazy loading extractors is disabled
[debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
[debug] Git HEAD: a6125983a
[debug] Python 3.10.6 (CPython 64bit) - Windows-10-10.0.22000-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg N-106550-g072101bd52-20220410 (fdk,setts), ffprobe N-106624-g391ce570c8-20220415, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.14.1, brotli-1.0.9, certifi-2021.10.08, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.1
[debug] Proxy map: {}
[debug] [youtube] Extracting URL: ZgvglIhHwp4
[youtube] ZgvglIhHwp4: Downloading webpage
[youtube] ZgvglIhHwp4: Downloading android player API JSON
[debug] Loading youtube-nsig.4c3f79c5 from cache
[debug] [youtube] Decrypted nsig IzVHKgAHrvCGUlHwlu => uTr3NaUIRlKcsg
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[info] ZgvglIhHwp4: Downloading 1 format(s): 599
[info] Downloading video thumbnail 44 ...
[info] Writing video thumbnail 44 to: [20220808] 【ASMR】スリスリとぞくぞくとろける様に眠れる。聞くだけで寝る！睡眠誘導。氷・耳かき・マッサージ・顔そり 99.99% of You Will DEEP SLEEP, Relax【周防パトラ
】 - ZgvglIhHwp4.webp
[debug] Invoking http downloader on "https://rr6---sn-gwpa-jv3z.googlevideo.com/videoplayback?expire=1660509813&ei=FQr5YvfrKIDlrtoPvbKmkAc&ip=49.37.226.108&id=o-ABtqkeK_7kexcdUNCGS9B6W7ouUAmcDUsrN-H_YaAP-q&itag=599&source=youtube&requiressl=yes&mh=B6&mm=31%2C29&mn=sn-gwpa-jv3z%2Csn-gwpa-jwce&ms=au%2Crdu&mv=m&mvi=6&pcm2cms=yes&pl=20&initcwndbps=275000&spc=lT-KhjV1rprNLoqAJsQGOrnqZMZdR-M&vprv=1&svpuc=1&mime=audio%2Fmp4&gir=yes&clen=28675287&dur=7452.118&lmt=1659979021431653&mt=1660488053&fvip=6&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&rbqsm=fr&txp=7318224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIhAIHqCspJVyDrKF1CDqNphVknxjntH3dKLY5FR-_CjYXfAiAYPhvte3UOWFV3SJcJS0N15iQKBImPw0Bq-eLhgNZJFg%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhAMAT625bbJeMCmWxQePnokfbdTGw9dARiUqlvdtaoB_3AiBakP443H5H22a_OOUwfIXYqmVcG72NfUx1d--PT76kNw%3D%3D"
[download] [20220808] 【ASMR】スリスリとぞくぞくとろける様に眠れる。聞くだけで寝る！睡眠誘導。氷・耳かき・マッサージ・顔そり 99.99% of You Will DEEP SLEEP, Relax【周防パトラ 】 - ZgvglIhHwp4.m4a has already been downloaded
[download] 100% of 28.70MiB
[ThumbnailsConvertor] Converting thumbnail "[20220808] 【ASMR】スリスリとぞくぞくとろける様に眠れる。聞くだけで寝る！睡眠誘導。氷・耳かき・マッサージ・顔そり 99.99% of You Will DEEP SLEEP, Relax【周防パトラ 】 - ZgvglIhHwp4.webp" to png
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -f image2 -pattern_type none -i "file:[20220808] 【ASMR】スリスリとぞくぞくとろける様に眠れる。聞くだけで寝る！睡眠誘導。氷・耳かき・マッサージ・顔そり 99.99% of You Will DEEP SLEEP, Relax【周防パトラ 】 - ZgvglIhHwp4.webp" -movflags "+faststart" "file:[20220808] 【ASMR】スリスリとぞくぞくとろける様に眠れる。聞くだけで寝る！睡眠誘導。氷・ 耳かき・マッサージ・顔そり 99.99%% of You Will DEEP SLEEP, Relax【周防パトラ 】 - ZgvglIhHwp4.png"
WARNING: Cannot update utime of file
[EmbedThumbnail] mutagen: Adding thumbnail to "[20220808] 【ASMR】スリスリとぞくぞくとろける様に眠れる。聞くだけで寝る！睡眠誘導。氷・耳かき・マッサージ・顔そり 99.99% of You Will DEEP SLEEP, Relax【周 防パトラ 】 - ZgvglIhHwp4.m4a"
```

**Comment by pukkandan** [comment]
I can actually reproduce with ffmpeg 5.1, but not with 5.0. So it is most likely an ffmpeg bug. We can try to wok around it, but first will need make sure whether this is intentional or not. Try opening an issue against ffmpeg

**Comment by ShockedCoder** [comment]
> I can actually reproduce with ffmpeg 5.1, but not with 5.0.

So, a temp fix would be to just downgrade FFmpeg, right?

**Comment by pukkandan** [comment]
Yes

**Comment by heywolf15** [comment]
@pukkandan Thanks, I haven't been checking this issue for a while

**Comment by mkhl** [comment]
i've filed a ticket upstream:
https://trac.ffmpeg.org/ticket/9994

**Comment by mkhl** [comment]
https://trac.ffmpeg.org/ticket/9748
the change seems to have been intentional, let's see what kind of discussion comes of it

**Comment by pukkandan** [comment]
Thanks

> the change seems to have been intentional, let's see what kind of discussion comes of it

Then, we should figure out how we can handle both old and new ffmpeg versions. Looking at version numbers is insufficient since ffmpeg builds from various sources use different versioning schemes - a lot of them dont include "5.1" or even a timestamp

**Comment by dirkf** [comment]
So isn't this what is happening?
1. yt-dlp's `FFmpegThumbnailsConvertorPP` doubles any raw `%` character in the output filename as an escape for printf-like processing by the `image2` muxer, as in https://github.com/yt-dlp/yt-dlp/issues/4604#issuecomment-1210699124
2. In the [indirectly linked commit](http://git.videolan.org/?p=ffmpeg.git;a=commitdiff;h=b54f3e32fa228095867cd9edd6f4bf540ffa2eb3), _ffmpeg_ changed the `image2` muxer so that a string with only escaped `%`(s) is not treated as a pattern, with this warning:
```
The specified filename ... does not contain an image sequence pattern or a pattern is invalid.
Use a pattern such as %03d for an image sequence or use the -update option (with -frames:v 1 if needed) to write a single image.
```
3. Consequently any "escaped" `%` in such an output filename are passed through without unescaping.
4. Subsequent postprocessing stages are then unable to find the image file.

As hinted in the warning, and assuming _ffmpeg_ didn't also break the documentation, the `-update 1` option of the `image2` muxer is the equivalent of the `-pattern_type none` for the `image2` demuxer, as already used in the `FFmpegThumbnailsConvertorPP` problem code. The `image2` muxer `-update ...` option is supported in 4.3.2 and at least since the [start of 2015](https://halfface.se/wiki/index.php?title=Commands&diff=12282&oldid=12281).

As the input filename in the problem code is fixed, it shouldn't be a problem to fix the output filename too.

**Comment by pukkandan** [comment]
I know there are users who still use ffmpeg 3, so a solution that works that far back would have been ideal. But in the absence of another fix, `-update` does look like an acceptable solution

**Comment by dirkf** [comment]
I just remembered a legacy version (on the machines that run yt-dl with Py 2.7.1). Good news!
```shellsession
# rm -f bunny*
# ffmpeg-2.8 -v error -i Big_Buck_Bunny_720_10s_2MB_H264.mp4 -frames 1 -an 
-f image2 bunny%-%d.jpg
# ls bunny*
bunny
# rm -f bunny*
# ffmpeg-2.8 -v error -i Big_Buck_Bunny_720_10s_2MB_H264.mp4 -frames 1 -an 
-f image2 bunny%%-%d.jpg
# ls bunny*
bunny%-1.jpg
# rm -f bunny*
# ffmpeg-2.8 -v error -i Big_Buck_Bunny_720_10s_2MB_H264.mp4 -frames 1 -an 
-f image2 -update 1 bunny%-%d.jpg
# ls bunny*
bunny%-%d.jpg
# rm -f bunny*
# ffmpeg-2.8 -v error -i Big_Buck_Bunny_720_10s_2MB_H264.mp4 -frames 1 -an 
-f image2 -update 1 bunny%%-%d.jpg
# ls bunny*
bunny%%-%d.jpg
# 
```

**Comment by ShockedCoder** [comment]
I've updated to the latest version and it still doesn't embed thumbnails for me.
At first, I thought it was just my DE's fault for not showing it properly, so I used `ffmpegthumbnailer -s0 -o/tmp/test.png -q10 -m -w -i [videoname].mkv` and it still didn't return the thumbnail but instead a random frame from the video

**Comment by ShockedCoder** [comment]
I've updated to the latest version through pip and it still doesn't embed thumbnails for me. (I also tried downloading the repo and using `yt-dlp.sh`)
At first, I thought it was just my DE's fault for not showing it properly, so I used `ffmpegthumbnailer -s0 -o/tmp/test.png -q10 -m -w -i [videoname].mkv` and it still didn't return the thumbnail but instead a random frame from the video.

both yt-dlp versions: 2022.11.11
FFmpeg version: 5.1.2
