### ISSUE TITLE
[patreon] unable to download video data: HTTP Error 404: Not Found

### ISSUE THREAD

**Issue by hzrDgit** [yt-dlp/yt-dlp#4608]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.08.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Provide a description that is worded well enough to be understood

I saw that the most recent release (yt-dlp 2022.08.08) was supposed to fix the extractor for patreon but I still can not download patreon videos. I'm talking about the ones hosted on patreon itself, not external ones.
It doesn't matter if I give it a link to a single video or try to download the entire /posts site.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--cookies', 'D:\\Downloads\\cookies.txt', '-o', 'D:\\Downloads\\pat', 'https://www.patreon.com/posts/premium-access-70282931']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.08.08 [3157158] (pip)
[debug] Python 3.10.6 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 5.1-full_build-www.gyan.dev (setts), ffprobe 5.1-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.08.08, Current version: 2022.08.08
yt-dlp is up to date (2022.08.08)
[debug] [Patreon] Extracting URL: https://www.patreon.com/posts/premium-access-70282931
[Patreon] 70282931: Downloading API JSON
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 70282931: Downloading 1 format(s): 0
[debug] Invoking http downloader on "https://c10.patreonusercontent.com/4/patreon-media/p/post/70282931/2f021b39942c41e991996c6d3b6c4f7b/eyJhIjoxLCJwIjoxfQ%3D%3D/1?token-time=1660176000&token-hash=KXCG7MKA2tOS-rnUS9Z2tJ9U9BQse9gdOWikIoan71Q%3D"
ERROR: unable to download video data: HTTP Error 404: Not Found
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 3169, in process_info
    success, real_download = self.dl(temp_filename, info_dict)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 2893, in dl
    return fd.download(name, new_info, subtitle)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\downloader\common.py", line 442, in download
    ret = self.real_download(filename, info_dict)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\downloader\http.py", line 371, in real_download
    establish_connection()
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\downloader\http.py", line 129, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 3647, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 525, in open
    response = meth(req, response)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 634, in http_response
    response = self.parent.error(
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 563, in error
    return self._call_chain(*args)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```

**Comment by pukkandan** [comment]
@coletdjnz

**Comment by coletdjnz** [comment]
I don't have access to any creator that uses this video format.

does `--user-agent "Patreon/7.6.28 (Android; Android 11; Scale/2.10)"` help by any chance?

**Comment by jawbroken** [comment]
Specifying the user agent above doesn't work for me. This new video hosting method is current in [invitation-only beta](https://support.patreon.com/hc/en-us/articles/6598555214477-Patreon-Video-BETA) so it will likely be difficult to track down public examples.

**Comment by hzrDgit** [comment]
> I don't have access to any creator that uses this video format.
> 
> does `--user-agent "Patreon/7.6.28 (Android; Android 11; Scale/2.10)"` help by any chance?

I could give you my account if that helps. The membership will expire at the end of this month.

**Comment by coletdjnz** [comment]
Hmm ok.

If you're happy to share creds that would be great. You can send them to me at [coletdjnz@proton.me](mailto:coletdjnz@proton.me) or coletdjnz#6639 on discord.

Being a beta is problematic for us as they are more likely to change things around, but nevertheless I can have a look into it.

**Comment by hzrDgit** [comment]
> If you're happy to share creds that would be great. You can send them to me at [coletdjnz@proton.me](mailto:coletdjnz@proton.me) or coletdjnz#6639 on discord.

I just sent them to your email.
