### ISSUE TITLE
Possible to apply --restrict-filenames sanitization to %(title)

### ISSUE THREAD

**Issue by 40ZqTYY4ag3tAO4hdlxR1** [yt-dlp/yt-dlp#4611]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.08.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

**Expected behavior :** 
`'--exec before_dl:'echo "%(id)s | %(title).60s" >> log.txt'` will write title to log.txt

**Current behavior :** 
unexpected EOF failure due to special characters in `%(title)`

**Description :**

This is an edgecase, sometimes video titles contain special characters e.g. double quotes " , single quotes ' , back ticks ` , )  (  /  \ $ .
> e.g yt-dlp -e https://www.youtube.com/watch?v=YCjN96uOriU
> "I Don't Really Buy That" - Rep. Jamie Raskin On The Secret Service Losing Jan 6 Texts
 
The two double quotes and one single quote get sanitized in the filename using --restrict-filenames , which is expected Post Processing behavior 
> I_Don_t_Really_Buy_That_-_Rep._Jamie_Raskin_On_The_Secret_Service_Losing_Jan_6_Texts-[YCjN96uOriU].mp4

however `%(title)` is passed un-sanitized to both `--exec before_dl:` & `--exec` , which is how yt-dlp is currently designed.

trying to `echo` or `printf` the `%(title)` to a logfile using  `--exec before_dl:` or `--exec` results in an error due to the special characters
> /bin/sh: -c: line 1: unexpected EOF while looking for matching `''

One partial solution was to use `filepath`  as suggested in https://github.com/yt-dlp/yt-dlp/issues/1310#issuecomment-944965463 , however that is not a perfect solution... though it does show that filename sanitation happens even before the file gets downloaded. 
> e.g.  yt-dlp -f 139 --exec before_dl:'echo "%(id)s | %(filepath).60s" >> log.txt' --exec 'echo "%(id)s | %(filepath).60s" >> log.txt' --restrict-filenames https://www.youtube.com/watch?v=YCjN96uOriU

Any suggestions on a way to get the cleaned up  `%(title)` without special characters, as we have no control over what the content creator puts in the title.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp -vU -f 139 --exec before_dl:'echo "%(id)s | %(title).60s" >> log.txt' --restrict-filenames https://www.youtube.com/watch?v=YCjN96uOriU
[debug] Command-line config: ['-vU', '-f', '139', '--exec', 'before_dl:echo "%(id)s | %(title).60s" >> log.txt', '--restrict-filenames', 'https://www.youtube.com/watch?v=YCjN96uOriU']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.08.08 [3157158] (zip)
[debug] Python 3.10.5 (CPython 64bit) - Linux-5.15.59-1-MANJARO-x86_64-with-glibc2.36 (glibc 2.36)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 5.0.1 (setts), ffprobe 5.0.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.12.0, brotlicffi-1.0.9.2, certifi-2022.06.15, secretstorage-3.3.2, sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.08.08, Current version: 2022.08.08
yt-dlp is up to date (2022.08.08)
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=YCjN96uOriU
[youtube] YCjN96uOriU: Downloading webpage
[youtube] YCjN96uOriU: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, channels, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), channels, source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[info] YCjN96uOriU: Downloading 1 format(s): 139
[Exec] Executing command: echo "YCjN96uOriU | "I Don't Really Buy That" - Rep. Jamie Raskin On The Secret " >> log.txt
/bin/sh: -c: line 1: unexpected EOF while looking for matching `''
/bin/sh: -c: line 2: syntax error: unexpected end of file
ERROR: Preprocessing: Command returned error code 2
Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3404, in pre_process
    info = self.run_all_pps(key, info)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3397, in run_all_pps
    info = self.run_pp(pp, info)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3376, in run_pp
    files_to_delete, infodict = pp.run(infodict)
  File "/usr/local/bin/yt-dlp/yt_dlp/postprocessor/common.py", line 24, in run
    ret = func(self, info, *args, **kwargs)
  File "/usr/local/bin/yt-dlp/yt_dlp/postprocessor/exec.py", line 33, in run
    raise PostProcessingError('Command returned error code %d' % retCode)
yt_dlp.utils.PostProcessingError: Command returned error code 2

[debug] Invoking http downloader on "https://rr3---sn-5hnednss.googlevideo.com/videoplayback?expire=1660123939&ei=wybzYqrXNNCTgQe4_6SICg&ip=190.2.138.14&id=o-ABYgS6AKV4PwHc0J-VOXLZgLvEs3C0St2yA-zcixeqHQ&itag=139&source=youtube&requiressl=yes&mh=rg&mm=31%2C29&mn=sn-5hnednss%2Csn-5hne6n6l&ms=au%2Crdu&mv=m&mvi=3&pl=23&initcwndbps=25000&spc=lT-KhqWkHVvuzRzBPgiQJM5P0kAvYmQ&vprv=1&svpuc=1&mime=audio%2Fmp4&gir=yes&clen=2252933&dur=369.290&lmt=1658872188029006&mt=1660102154&fvip=2&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&rbqsm=fr&txp=5532434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIhAMRWjDfeFY4peehnRn3dge-e0SfUQB-ndVcS8eTp9otcAiA_eI8Ob4CtfOul3YCW4jOq8FMJR4mYYUp6V2GzJs-jLg%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhANGo_fi5ENabh1D-5RvKEljme06znFC4kmX16kPqPPbbAiEA3sF7lVSFI_j85UfSBv0riV0Iz5I3VLXrqXhF1IQHGTg%3D"
[download] I_Don_t_Really_Buy_That_-_Rep._Jamie_Raskin_On_The_Secret_Service_Losing_Jan_6_Texts-[YCjN96uOriU].m4a has already been downloaded
[download] 100% of 2.14MiB
ERROR: Preprocessing: Command returned error code 2
```

**Comment by pukkandan** [comment]
> Any suggestions on a way to get the cleaned up %(title) without special characters, as we have no control over what the content creator puts in the title.

![image](https://user-images.githubusercontent.com/6623388/183809385-ee9ed22c-ddef-428b-bdb1-2a1a403cf2cc.png)

So `%(title)#S`

---

But reading your full post, I don't think this is what you actually want. What you are really looking for is the `--print-to-file` option

**Comment by 40ZqTYY4ag3tAO4hdlxR1** [comment]
Thank you pukkandan ... your suggestion worked as required.... I should have fully read and understood the readme better 

**solution**
`--print-to-file before_dl:"(id)s | %(title).60s" log.txt --print-to-file after_video:"(id)s | %(title).60s" log.txt`

_the solution was always there at_ 

- https://github.com/yt-dlp/yt-dlp#verbosity-and-simulation-options `--print-to-file` options
- https://github.com/yt-dlp/yt-dlp#post-processing-options `--use-postprocessor` options for the "when" argument


appreciate your time, closing the issue
