### ISSUE TITLE
what is the difference between --remux-video with --merge-output-format?

### ISSUE THREAD

**Issue by candrapersada** [yt-dlp/yt-dlp#4614]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.08.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

what is the difference between `--remux-video FORMAT` and `--merge-output-format FORMAT`?

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
`--merge-output-format` is used when merging. Remux is done after download/merge irrespective of whether merge is needed. It is often recommended to use both together. Eg: `--merge mp4 --remux mp4`

**Comment by candrapersada** [comment]
is there any option to use Configuration: yt-dlp.conf other than in the home path given by -P like command prompt or terminal
for example like this picture
![yt-dlp](https://user-images.githubusercontent.com/36833664/184058371-3d0a9d38-48ae-4125-85a4-6ef4c2ca2d5b.PNG)

**Comment by pukkandan** [comment]
https://github.com/yt-dlp/yt-dlp#configuration explains all the options

**Comment by pukkandan** [comment]
actually, I may have misunderstood. What do you mean "other than in the home path given by -P like command prompt and terminal"?

**Comment by candrapersada** [comment]
can use yt-dlp.conf the same location as this
![image](https://user-images.githubusercontent.com/36833664/184069459-8a5cddca-6a71-4f23-b9ac-8ded755e22e1.png)

**Comment by pukkandan** [comment]
If you are not using any `-P`

**Comment by candrapersada** [comment]
then is there an option to choose the location to save the video other than using `-P`

**Comment by pukkandan** [comment]
Why not just do `--config .`?

**Comment by candrapersada** [comment]
what i mean is to use `--paths download: .` or `--paths location: .` to select the location to save the download video without using `--path home: .` because it can change the location of `yt-dlp.conf`

**Comment by pukkandan** [comment]
No, the point of "home config" is that they are loaded from `-P home:`... There is no reason to add a new option for that. If you want different location, the option `--config-location` already exists!

Also using `-o` instead of `-P` is always an option

You didn't answer my question though

**Comment by candrapersada** [comment]
then why can't you use the `yt-dlp.conf` location in the command prompt as shown below when using `-P .`
`D:\Transfer data>yt-dlp
![image](https://user-images.githubusercontent.com/36833664/184129251-c7218ea1-94b5-48a8-a898-37cf2d7a475d.png)

**Comment by pukkandan** [comment]
read my reply again

**Comment by jvschiavo** [comment]
> It is often recommended to use both together.

Hi, sorry to bother you, but why do you say that?

**Comment by bashonly** [comment]
>> It is often recommended to use both together.
>
> ...why do you say that?

If no merging is required (e.g. a single format containing both video and audio was downloaded), `--merge-output-format` will have no effect. So then you'd want to have also passed `--remux-video` to ensure you end up with the container you want

**Comment by jvschiavo** [comment]
> If no merging is required (e.g. a single format containing both video and audio was downloaded), `--merge-output-format` will have no effect. So then you'd want to have also passed `--remux-video` to ensure you end up with the container you want

Thanks, now I understand this.

But it still seems somewhat confusing. Couldn't we have a single flag that combines the effect of both `--remux-video` and `--merge-output-format` instead? I think it would make things easier for the end user.

**Comment by bashonly** [comment]
> But it still seems somewhat confusing. Couldn't we have a single flag that combines the effect of both `--remux-video` and `--merge-output-format` instead? I think it would make things easier for the end user.

@jvschiavo You can do it yourself by adding this line to your [config file](https://github.com/yt-dlp/yt-dlp#configuration):
```
--alias container '--remux-video {0} --merge-output-format {0}'
```

Then you can use it like:
```
yt-dlp --container mp4 "URL"
```
