### ISSUE TITLE
ERROR: Unable to download webpage

### ISSUE THREAD

**Issue by throwaway234432** [yt-dlp/yt-dlp#4617]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.08.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

```G:\Documents\yt-dlp_win>yt-dlp -F https://play.ninetyvieoprogood.xyz/player/62e5dd969f7271aa6f0b1fe2/playlist.m3u8?v=3
[generic] playlist: Downloading webpage
ERROR: [generic] Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

I get this error when trying to view the formats for this m3u8 playlist link, how can I download the video?

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '-F', 'https://play.ninetyvieoprogood.xyz/player/62e5dd969f7271aa6f0b1fe2/playlist.m3u8?v=3']
[debug] Encodings: locale cp936, fs utf-8, pref cp936, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.08.08 [3157158] (win32_exe)
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg git-2020-08-14-a762fd2, ffprobe git-2020-08-14-a762fd2
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.08.08, Current version: 2022.08.08
yt-dlp is up to date (2022.08.08)
```

**Comment by pukkandan** [comment]
Double check:
> - [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details

> - [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by throwaway234432** [comment]
> Double check:
> 
> > * [x]  I've checked that all provided URLs are playable in a browser with the same IP and same login details
> The website doesn't require any login details and no the URL is not playable in any browsers
> > * [x]  Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by throwaway234432** [comment]
Can someone please help me????????

**Comment by pukkandan** [comment]
Why do you think the checkboxes exist? They are instructions for you to follow and then confirm, not to blindly tick!

If the URL doesn't open in browser, ytdlp cannot download it
