### ISSUE TITLE
Sit Support request for vidyard.com

### ISSUE THREAD

**Issue by Karlheinz-B** [yt-dlp/yt-dlp#4618]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.08.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Germany

### Example URLs

vidyard.com/watch/d4vqPjs7Q5EzVEis5QT3jd?

### Provide a description that is worded well enough to be understood

I want to download a file splittet into chapters (not playlists, because only one link exists), however only the first chapter gets downloaded. The total Video is e.g. 20mins and the first Chapter 30s => only the file of teh first 30s has been downloaded.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
❯ yt-dlp -vF https://anonymized.vidyard.com/watch/d4vqPjs7Q5EzVEis5QT3jd
[debug] Command-line config: ['--ignore-config', '-vF', 'https://anonymized.vidyard.com/watch/d4vqPjs7Q5EzVEis5QT3jd']
[debug] Encodings: locale cp65001, fs utf-8, pref cp65001, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.08.08 [3157158f7] (source)
[debug] Lazy loading extractors is disabled
[debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
[debug] Git HEAD: d7ac82d06
[debug] Python 3.10.5 (CPython 64bit) - Windows-10-10.0.22000-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg N-106550-g072101bd52-20220410 (fdk,setts), ffprobe N-106624-g391ce570c8-20220415, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.14.1, brotli-1.0.9, certifi-2021.10.08, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.1
[debug] Proxy map: {}
[debug] [generic] Extracting URL: https://anonymized.vidyard.com/watch/d4vqPjs7Q5EzVEis5QT3jd
[generic] d4vqPjs7Q5EzVEis5QT3jd: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] d4vqPjs7Q5EzVEis5QT3jd: Extracting information
[debug] Looking for Brightcove embeds
[debug] Looking for embeds
[debug] Identified a Twitter card
[info] Available formats for sd:
ID EXT RESOLUTION │ PROTO │ VCODEC  ACODEC
───────────────────────────────────────────
0  mp4 unknown    │ https │ unknown unknown
```

edit: anonimized links

**Comment by HobbyistDev** [comment]
Related upstream https://github.com/ytdl-org/youtube-dl/issues/11338

**Comment by coletdjnz** [comment]
Metadata and streaming links can be fetched from this JSON API request:
`https://play.vidyard.com/player/<video id>.json`
Chapters appear under `chapters` key. If its a single video then there is one chapter.


Referer is probably required on all requests.

Likely will need embed detection, some resources I found:
- https://knowledge.vidyard.com/hc/en-us/articles/360009871054-How-to-use-the-Vidyard-Player-API
- https://knowledge.vidyard.com/hc/en-us/articles/360010001713-Embed-your-video-on-a-webpage

direct urls appear to look like
- `https://<name>.vidyard.com/watch/<video id>`
- `https://play.vidyard.com/<video id>`
- `https://share.vidyard.com/watch/<video id>`
- `https://video.vidyard.com/watch/<video id>`

you also have "hubs" which seem to contain the video library from  `<name>`: `https://<name>.hubs.vidyard.com` e.g. `https://thelink.hubs.vidyard.com`

**Comment by swiftgeek** [comment]
With curl and `full_hd.mp4` url from json, `https://play.vidyard.com/` is enough for me as referrer to fetch in 1080p quality.

**Comment by dirkf** [comment]
The embedded video at Altium follows the scheme documented [above](https://github.com/yt-dlp/yt-dlp/issues/4618#issuecomment-1592076290).

**Comment by meokey** [comment]
I'm trying to download an AWS learning video and notice that it ends up to vidyard.com too but I cann't download it - not sure if the extractor has not yet been part of the latest release or we need to update the extractor for more wider scenarios?
please @coletdjnz @dirkf @HobbyistDev   kindly help.

AWS video URL:
https://pages.awscloud.com/GLOBAL_AWSMP_WEBINAR_SEC-NGFW-NGFW-webinar_20240411_701RU000002ehxFYAQ_Confirmation-Page-Decanter-B.html

vidyard URL:
https://play.vidyard.com/zAUnp2u1eS2Xa3SV14eJ5Z.html

#10155 https://github.com/ytdl-org/youtube-dl/issues/11338 #5371 


```
[debug] Command-line config: ['-vU', 'https://play.vidyard.com/zAUnp2u1eS2Xa3SV14eJ5Z.html']
[debug] Portable config "/var/services/homes/bill/.local/bin/yt-dlp.conf": ['-f', 'bv*+ba/b', '-o', '%(title)s.f%(format_id)s.%(ext)s', '--write-info-json', '--write-playlist-metafiles']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.05.27 from yt-dlp/yt-dlp [12b248ce6] (zip)
[debug] Python 3.8.15 (CPython x86_64 64bit) - Linux-4.4.302+-x86_64-with-glibc2.34 (OpenSSL 3.0.9 30 May 2023, glibc 2.36)
[debug] exe versions: ffmpeg 4.1.9
[debug] Optional libraries: certifi-2022.12.07, requests-2.31.0, sqlite3-3.40.0, urllib3-1.26.11
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Loaded 1820 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2024.05.27 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2024.05.27 from yt-dlp/yt-dlp)
[generic] Extracting URL: https://play.vidyard.com/zAUnp2u1eS2Xa3SV14eJ5Z.html
[generic] zAUnp2u1eS2Xa3SV14eJ5Z: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] zAUnp2u1eS2Xa3SV14eJ5Z: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://play.vidyard.com/zAUnp2u1eS2Xa3SV14eJ5Z.html
Traceback (most recent call last):
  File "/var/services/homes/bill/.local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1606, in wrapper
    return func(self, *args, **kwargs)
  File "/var/services/homes/bill/.local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1741, in __extract_info
    ie_result = ie.extract(url)
  File "/var/services/homes/bill/.local/bin/yt-dlp/yt_dlp/extractor/common.py", line 734, in extract
    ie_result = self._real_extract(url)
  File "/var/services/homes/bill/.local/bin/yt-dlp/yt_dlp/extractor/generic.py", line 2514, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://play.vidyard.com/zAUnp2u1eS2Xa3SV14eJ5Z.html
```
