### ISSUE TITLE
consider audio transparency of different audio codecs for format sorting

### ISSUE THREAD

**Issue by Rexadev** [yt-dlp/yt-dlp#4619]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.08.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood
---------------------------------------------------------------------------------------------------------

For lossy(non surround) audio codecs sort different codecs depending on bitrate and codec's efficiency because of transparency.

### Example -
1. AAC is transparent at 128 kbit/s stereo and 320 kbit/s 5.1
https://en.wikipedia.org/wiki/Advanced_Audio_Coding#:~:text=AAC%20meets%20the%20requirements%20referred%20to%20as%20%22transparent%22%20for%20the%20ITU%20at%20128%C2%A0kbit/s%20for%20stereo%2C%20and%20320%C2%A0kbit/s%20for%205.1%20audio

2. Opus - Stereo 128 KB/s (VBR) is transparent - https://wiki.xiph.org/Opus_Recommended_Settings

If same bitrate then Opus>AAC - because better codec, free and open source.

### Where it is Useful
This idea is useful for `YouTube Music Premium` as it's AAC 256kbps - ttps://support.google.com/youtubemusic/answer/9076559
This will not work if codec is prioritized

### For this feature to work -
1. create a list of transparency bitrate equivalency for each lossy(non-surround) codec.
2. Using it sorting format can prefer "lower" codec when a higher bitrate is available.
3. Create a list of tier for codecs for format sorting to choose format same bitrate is available for 2 codecs

---------------------------------------------------------------------------------------------------------

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
Not valid
```

**Comment by pukkandan** [comment]
> This idea is useful for YouTube Music Premium as it's AAC 256kbps - ttps://support.google.com/youtubemusic/answer/9076559
> This will not work if codec is prioritized

Show log of it "not working"

**Comment by pukkandan** [comment]
As for the actual request (as explained in #1232), I won't consider it unless you can provide an **authoritative** source that defines an algorithm for comparing bitrates b/w codecs
