### ISSUE TITLE
[viki] HTTP Error 422: Unprocessable Entity

### ISSUE THREAD

**Issue by NomaanMalick** [yt-dlp/yt-dlp#462]
```
[debug] Command-line config: ['-v', 'https://www.viki.com/videos/1080865v', '--c
ookies', 'C:UsersNomaanDesktopcookies.txt']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] yt-dlp version 2021.06.23
[debug] Python version 3.9.5 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] exe versions: ffmpeg 4.4-full_build-www.gyan.dev, ffprobe 4.4-full_build
-www.gyan.dev
[debug] Proxy map: {}
[debug] [viki] Extracting URL: https://www.viki.com/videos/1080865v
[viki] 1080865v: Downloading video JSON
ERROR: Unable to download JSON metadata: HTTP Error 422: Unprocessable Entity (c
aused by <HTTPError 422: 'Unprocessable Entity'>); please report this issue on
https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; s
ee  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp w
ith the --verbose flag and include its complete output.
  File "C:\Users\Nomaan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3
.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\yt_dlp\extract
or\common.py", line 679, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "C:\Users\Nomaan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3
.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\yt_dlp\Youtube
DL.py", line 3089, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.152
0.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 523, in open
    response = meth(req, response)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.152
0.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 632, in http_response
    response = self.parent.error(
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.152
0.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 561, in error
    return self._call_chain(*args)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.152
0.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 494, in _call_chain
    result = func(*args)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.152
0.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
```

**Comment by MinePlayersPE** [comment]
please follow the [issue template](https://github.com/yt-dlp/yt-dlp/blob/master/.github/ISSUE_TEMPLATE/1_broken_site.md) and [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md)

In any case... I can reproduce it too, even with the test video
```
yt-dlp -F -v https://www.viki.com/videos/1175236v-choosing-spouse-by-lottery-episode-1
[debug] Command-line config: ['-F', '-v', 'https://www.viki.com/videos/1175236v-choosing-spouse-by-lottery-episode-1']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] yt-dlp version 2021.06.23 (exe)
[debug] Plugin Extractors: ['SamplePlugin']
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] exe versions: ffmpeg 2021-06-09-git-e01bf559df-full_build-www.gyan.dev, ffprobe 2021-06-09-git-e01bf559df-full_build-www.gyan.dev
[debug] Proxy map: {}
[debug] [viki] Extracting URL: https://www.viki.com/videos/1175236v-choosing-spouse-by-lottery-episode-1
[viki] 1175236v: Downloading video JSON
ERROR: Unable to download JSON metadata: HTTP Error 422: Unprocessable Entity (caused by <HTTPError 422: 'Unprocessable Entity'>); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
  File "yt_dlp\extractor\common.py", line 679, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 3089, in urlopen
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 649, in http_error_default
```
Looks like the main culprit is the [hardcoded app version](https://github.com/yt-dlp/yt-dlp/blob/169dbde946e290982fd0d15130217079324cf4f2/yt_dlp/extractor/viki.py#L274) (latest one from the site is 4.0.74, but seems like it can go as far back as 3.1.0)

**Comment by NomaanMalick** [comment]
[debug] Command-line config: ['-v', 'https://www.viki.com/videos/1080865v', '--c
ookies', 'C:UsersNomaanDesktopcookies.txt']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] yt-dlp version 2021.06.23
[debug] Python version 3.9.5 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] exe versions: ffmpeg 4.4-full_build-www.gyan.dev, ffprobe 4.4-full_build
-www.gyan.dev
[debug] Proxy map: {}
[debug] [viki] Extracting URL: https://www.viki.com/videos/1080865v
[viki] 1080865v: Downloading video JSON
ERROR: Unable to download JSON metadata: HTTP Error 422: Unprocessable Entity (c
aused by <HTTPError 422: 'Unprocessable Entity'>); please report this issue on
https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; s
ee  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp w
ith the --verbose flag and include its complete output.
  File "C:\Users\Nomaan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3
.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\yt_dlp\extract
or\common.py", line 679, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "C:\Users\Nomaan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3
.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\yt_dlp\Youtube
DL.py", line 3089, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.152
0.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 523, in open
    response = meth(req, response)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.152
0.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 632, in http_response
    response = self.parent.error(
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.152
0.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 561, in error
    return self._call_chain(*args)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.152
0.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 494, in _call_chain
    result = func(*args)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.152
0.0_x64__qbz5n2kfra8p0\lib\urllib\request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)

**Comment by NomaanMalick** [comment]
> 
> ### **_please follow the [issue template](https://github.com/yt-dlp/yt-dlp/blob/master/.github/ISSUE_TEMPLATE/1_broken_site.md) and [contributing guidelines](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md)!!_**
> 
> In any case... I can reproduce it too, even with the test video
> 
> ```
> yt-dlp -F -v https://www.viki.com/videos/1175236v-choosing-spouse-by-lottery-episode-1
> [debug] Command-line config: ['-F', '-v', 'https://www.viki.com/videos/1175236v-choosing-spouse-by-lottery-episode-1']
> [debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
> [debug] yt-dlp version 2021.06.23 (exe)
> [debug] Plugin Extractors: ['SamplePlugin']
> [debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19043-SP0
> [debug] exe versions: ffmpeg 2021-06-09-git-e01bf559df-full_build-www.gyan.dev, ffprobe 2021-06-09-git-e01bf559df-full_build-www.gyan.dev
> [debug] Proxy map: {}
> [debug] [viki] Extracting URL: https://www.viki.com/videos/1175236v-choosing-spouse-by-lottery-episode-1
> [viki] 1175236v: Downloading video JSON
> ERROR: Unable to download JSON metadata: HTTP Error 422: Unprocessable Entity (caused by <HTTPError 422: 'Unprocessable Entity'>); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
>   File "yt_dlp\extractor\common.py", line 679, in _request_webpage
>   File "yt_dlp\YoutubeDL.py", line 3089, in urlopen
>   File "urllib\request.py", line 531, in open
>   File "urllib\request.py", line 640, in http_response
>   File "urllib\request.py", line 569, in error
>   File "urllib\request.py", line 502, in _call_chain
>   File "urllib\request.py", line 649, in http_error_default
> ```
> 
> Looks like the main culprit is the [hardcoded app version](https://github.com/yt-dlp/yt-dlp/blob/169dbde946e290982fd0d15130217079324cf4f2/yt_dlp/extractor/viki.py#L274) (latest one from the site is 4.0.74, but seems like it can go as far back as 3.1.0 for now)

Is there any solution to this? A fix?

**Comment by MinePlayersPE** [comment]
EDIT: Changing the app version seems to have fixed the initial error, but it seems like there is another underlying issue with format extraction (everything is in mhtml now)
I'm definitely not experienced in this site either, so hopefully someone else could pick this up?

**Comment by october262** [comment]
i got this link - https://www.viki.com/videos/1080865v to download 
using the HTTP-TRACKER firefox addon  and finding the mp4 
but the file is DRM encrypted

**Comment by zackmark29** [comment]
There's still hope. Just wait for the dev. They might just busy

This is not drm.
![image](https://user-images.githubusercontent.com/62680932/124415611-cf1c6480-dd87-11eb-835b-2c7155862207.png)

Try this url:
Video Url >> https://m-content6-viki.s.llnwi.net/1180911v/dash/1180911v_dash_high_1080p_32327f_2107020646_track1_dashinit.mp4
Audio Url >> https://m-content6-viki.s.llnwi.net/1180911v/dash/1180911v_dash_high_1080p_32327f_2107020646_track2_dashinit.mp4

**Comment by zackmark29** [comment]
> i got this link - https://www.viki.com/videos/1080865v to download
> using the HTTP-TRACKER firefox addon and finding the mp4
> but the file is DRM encrypted

I could give you the download links. Which episode?

**Comment by zackmark29** [comment]
> i got this link - https://www.viki.com/videos/1080865v to download
> using the HTTP-TRACKER firefox addon and finding the mp4
> but the file is DRM encrypted

All of viki videos are DRM protected already. 
but non drm still exist but using another method and android api

**Comment by pukkandan** [comment]
Even the example videos seems to have DRM now. Unless someone can provide examples without DRM, the site will no longer be supported

> but non drm still exist but using another method and android api

That is not the least bit helpful. Explain the method so that someone can have a look at implementing it @zackmark29

**Comment by zackmark29** [comment]
> Even the example videos seems to have DRM now. Unless someone can provide examples without DRM, the site will no longer be supported
> 
> > but non drm still exist but using another method and android api
> 
> That is not the least bit helpful. Explain the method so that someone can have a look at implementing it @zackmark29

Yes I'm trying now to implement the method. But since this is my first time to edit ydl codes, this might be a little ugly :)
![image](https://user-images.githubusercontent.com/62680932/124636412-18b99c00-debb-11eb-8bc1-8d6f673286c5.png)

**Comment by pukkandan** [comment]
> Yes I'm trying now to implement the method. 

Awesome

> But since this is my first time to edit ydl codes, this might be a little ugly :) Because my coding style is different.

Don't worry too much about it. We can fix it in reviews. Once you have a working implementation, feel free to open a PR

**Comment by zackmark29** [comment]
> > Yes I'm trying now to implement the method.
> 
> Awesome
> 
> > But since this is my first time to edit ydl codes, this might be a little ugly :) Because my coding style is different.
> 
> Don't worry too much about it. We can fix it in reviews. Once you have a working implementation, feel free to open a PR

This is good now I think.
I'll fix now the subtitle

![image](https://user-images.githubusercontent.com/62680932/124638554-aa2a0d80-debd-11eb-95d1-e37eae0abc39.png)

**Comment by zackmark29** [comment]
@pukkandan can you take a look? https://github.com/yt-dlp/yt-dlp/pull/473
