### ISSUE TITLE
Linux standalone executable does not retain the executable bits on update

### ISSUE THREAD

**Issue by joeschmoe40** [yt-dlp/yt-dlp#4621]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.08.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

I've found that while the Linux "standalone executable" does indeed "self-update", the resulting new file is not marked executable (in the Linux/Unix sense). That is, its "mode" is 644 when it should be 755. This problem does not manifest with the "pure Python" (Actually, zipped) version; there, the resulting file will be executable (assuming the original was).

I believe this is a result of the fact that replacing a running (binary) executable is tricky, on all platforms, and that in order to do it, some trickery involving downloading the new file to another name and then renaming it back to the original is involved. And that somewhere along the way, the "x" bits on the file get lost. So, the result is you have to do an explicit "chmod +x yt-dlp_linux" after using "-U" to update it.

It would be good if this could be fixed.

Addendum: Maybe it would be better if the executable were distributed in some kind of envelope, e.g., a .tar file, so that the executable bits are preserved.  I.e., I note that the first time I download it, it was not executable - need to be "chmod'd".

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
$ ls -lsa yt-dlp_linux 
30108 -rwxr-xr-x 1 user group       30,828,280 Jul 18 yt-dlp_linux*
$ ./yt-dlp_linux -U
Latest version: 2022.08.08, Current version: 2022.07.18
Current Build Hash 2c624c76153e9bb83ca596b18fda284118d05bc81109c3a1c03ff7ee65375821
Updating to version 2022.08.08 ...
Updated yt-dlp to version 2022.08.08
$ ls -lsa yt-dlp_linux
30116 -rw-r--r-- 1 user group       30,838,080 Aug 10 yt-dlp_linux
$ ./yt-dlp_linux -v
./yt-dlp_linux: Permission denied.
$
```

**Comment by joeschmoe40** [comment]
I don't think I like chmod'ing it to 777. That would be dangerous in a multi-user Linux/Unix system.

Ideally, it should be whatever the original was, but 755 is much safer than 777.

**Comment by Lesmiscore** [comment]
https://github.com/yt-dlp/yt-dlp/commit/6440c45ff3c3209593c0f39af075e71e4ca0299a
(though I'm not sure it should be okay)

**Comment by joeschmoe40** [comment]
Your patch first tries to chmod it to 777, then tries to chmod it to the original mask.

I still think the 777 is wrong.  It should be 755 (or, maybe, 775, since many modern Linux systems make a group for each user, so that might be OK).  Note, just for clarification, that chmod'ing it to 755 makes it executable for everybody, but only writable (i.e., changeable) by the owner.

**Comment by pukkandan** [comment]
> Your patch first tries to chmod it to 777, then tries to chmod it to the original mask.


No it doesnt

**Comment by joeschmoe40** [comment]
Sorry for the confusion.  I was addressing "Lesmiscore" as "you".
I was talking about his (Lesmiscore's) patch to somebody's (not sure who at this point) patch.  Lesmiscore's patch contains the lines:

 os.chmod(self.filename, 0o777)
 os.chmod(self.filename, mask)

Which, to be clear, is, I think, the right idea, but the first line should have 755, not 777.

**Comment by csehszlovakze** [comment]
I just updated to version 2022.08.14 and the file still lost the executable flag! Please reopen unless it was fixed after the current release.

**Comment by pukkandan** [comment]
Updating from last release to current uses the old updater. The issue should disappear during next update
