### ISSUE TITLE
[Documentation] Age Gated content: could the main README explain on this: "Supports some (but not all) age-gated content without cookies"?

### ISSUE THREAD

**Issue by rubyFeedback** [yt-dlp/yt-dlp#4622]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.08.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

So first some background information, to explain the context of this issue.

A few years ago I noticed that youtube blocks many videos behind an age-gate aka
"how old are you".

This is not really an issue if you log in; when I am logged in I don't see the age-keeping
block. But when I am not logged in, I see the block.

A few years ago, on a related problem, I started to question myself whether I want to
give up information to Google/Youtube, Facebook and what not, and decided that I
really don't want to give out my information when I can avoid it. So I no longer 
browse the www when logged in and I use tons of add-ons, such as ublock origin
and what not. Anyway. So for me it is kind of important to be able to download
videos. And any gate-keeping is just annoying me mostly.

I noticed that some proxies can work around the age-gating, and I managed to
download some videos that were age-gated that way. But it was slow and prone
to errors, so I'd love to have youtube-dl support this more easily.

youtube-dl unfortunately became ... semi-inactive, so I am looking at yt-dlp, I think,
2 years ago or so?

Now to the issue here to explain the "Supports some (but not all) age-gated
content without cookies" part.

This is currently mentioned in the main README.

Would it be possible to add a longer article about this? This can be in the
wiki, or in the doc/ subdirectory or somewhere. And it does not have to
be long! A single paragraph written by someone who has MORE information
on the topic, should suffice. I'd like to understand a bit better how this all
works, e. g. how youtube can block people so easily, and how one can 
still find the video at hand (after all it has to be somewhere). And then
I would also like a longer explanation where yt-dlp can work with SOME
age-gated content but not others. Any information here would be nice to
have, just for educational purposes, and for trying to understand what is
going on.

PS: Yikes, the issue tracker template is pretty verbose. Could you guys
shorten it? My above documentation-related issue really doesn't
need things such as "I've verified that I'm running yt-dlp version
2022.08.08", because what difference does that make when I refer
to documentation on the main README or elsewhere? I tried to
look for an issue template that is more similar to "documentation",
but this is not an issue about a question per se either. I think the
project in itself should explain this a little better so more people
can quickly understand what is going on. Not everyone understands
the problem domain. I for instance don't. I am sure many others 
don't either, so this should be useful either way for many people.

Thanks for reading nonetheless.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
> Would it be possible to add a longer article about this? 

No. Our documentation is not the place to document youtube's inner workings. I can try to explain it here, but I'm no teacher and it is kinda hard to do so without dumping a lot of technical information on you

> Yikes, the issue tracker template is pretty verbose. Could you guys shorten it?

For the sake of my sanity, no!

---

> how youtube can block people so easily

The same way login to any website works. When you go to youtube's site to access a video, some JS in the page talks to youtube servers and tells the browser the URL to the actual video content. If google servers cannot authenticate you, they doesn't give you the URL

> And then I would also like a longer explanation where yt-dlp can work with SOME
age-gated content but not others.

Some of the APIs youtube uses are not as "well-protected" as others. We can try to guess why that is the case, but we'll probably never know for sure. Developers research/experiment with these API endpoints and come up with bypasses to access this URL without authentication. So the reason some videos don't work is simply that we don't currently know of any bypass to access them.

Here's a technical breakdown of the various methods we currently employ. https://github.com/revanced/revanced-suggestions/discussions/118#discussioncomment-2703959
