### ISSUE TITLE
excecutable crashes immediately on launch

### ISSUE THREAD

**Issue by JohnSmith2007** [yt-dlp/yt-dlp#4623]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.08.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

When i try to open the .exe file, it just closes itself. I'm using yt-dlp.exe (because I have no experience with python and I'm not about to deal with the headache of installing a bunch of prerequisites that I already have.) I don't understand what I'm doing wrong. All I want is to download a geo-restricted video, then be done with it.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
N/A, because the program doesn't stay open.
```

**Comment by pukkandan** [comment]
yt-dlp is not a GUI program, but a console app. You can try googling "how to run a console app" or "how to use youtube-dl" to get help on how to run it.

But you'll probably find it more helpful to use one of the third party GUIs available. See a list here: https://www.reddit.com/r/youtubedl/wiki/info-guis

If you don't know which one to pick, my personal suggestion for beginners would be https://github.com/mhogomchungu/media-downloader
