### ISSUE TITLE
2022 - YouTube Premium high quality audio (255kbps) via stream id=141 missing

### ISSUE THREAD

**Issue by TSkaalrud** [yt-dlp/yt-dlp#4624]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.08.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Hi! I got excited when I realized that this continuation of yt-dl offered support for the high quality audio of YouTube premium users but I'm struggling to actually find it. By my understanding it should be possible to find audio only source id=141 if you're a premium member (which I am).

-  I've used the "get cookies.txt" Chrome extension, trying both my regular YouTube premium homepage, as well as the associated YouTube Music homepage, so I'm not sure how I could have messed up the cookies. 
- I've checked a variety of urls to try and sus out if I was just using urls with low quality audio but between several urls I've picked and recommendations of Vevo or the link used below, as suggested in issue #1091, but no matter what I've done, I can only find ~128kbps audio sources and none of them are id=141.
- I've used fresh installs of both the regular pip installation and the cutting edge branch, so I'm up to date and I don't think that's the issue either.

Is there something I'm missing here? Other folks seem to be able to return stream 141 using the same/similar commands as I am, which leads me to believe maybe YouTube has changed since these tickets or I've entirely missed a step somewhere? Any clarity would be appreciated, thanks!

yt-dlp --cookies=cookie.txt -vFU -f bestaudio https://music.youtube.com/watch?v=XclachpHxis
![cmd_SPf5eCGGSp](https://user-images.githubusercontent.com/35578683/184022427-ca3d0640-62af-4b60-b234-d506f7724051.png)

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['--cookies=cookie.txt', '-vFU', '-f', 'bestaudio', 'https://music.youtube.com/watch?v=XclachpHxis']    
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8                                        
[debug] yt-dlp version 2022.08.08 [3157158f7]                                                                                        
[debug] Lazy loading extractors is disabled                                                                                          
[debug] Python 3.10.1 (CPython 64bit) - Windows-10-10.0.19044-SP0                                                                    
[debug] Checking exe version: ffmpeg -bsfs                                                                                           
[debug] Checking exe version: ffprobe -bsfs                                                                                          
[debug] exe versions: ffmpeg 5.1-essentials_build-www.gyan.dev (setts), ffprobe 5.1-essentials_build-www.gyan.dev                    
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3      
[debug] Proxy map: {}                                                                                                                
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest                                            
Latest version: 2022.08.08, Current version: 2022.08.08                                                                              
yt-dlp is up to date (2022.08.08)                                                                                                    
[debug] [youtube] Extracting URL: https://music.youtube.com/watch?v=XclachpHxis                                                      
[youtube] XclachpHxis: Downloading webpage                                                                                           
[youtube] XclachpHxis: Downloading android player API JSON                                                                           
[youtube] XclachpHxis: Downloading android music player API JSON                                                                     
[youtube] XclachpHxis: Downloading web music client config                                                                           
[youtube] XclachpHxis: Downloading player 0d77e7db                                                                                   
[youtube] XclachpHxis: Downloading web music player API JSON                                                                         
[debug] Sort order given by extractor: quality, res, fps, hdr:12, channels, source, codec:vp9.2, lang, proto                         
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), channels, source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id                                                                        
[info] Available formats for XclachpHxis:                                                                                            
ID  EXT   RESOLUTION FPS CH │   FILESIZE  TBR PROTO │ VCODEC         VBR ACODEC      ABR ASR MORE INFO                               
──────────────────────────────────────────────────────────────────────────────────────────────────────────────                       
sb2 mhtml 48x27        0    │                 mhtml │ images                                 storyboard                              
sb1 mhtml 45x45        1    │                 mhtml │ images                                 storyboard                              
sb0 mhtml 90x90        1    │                 mhtml │ images                                 storyboard                              
139 m4a   audio only      2 │    1.49MiB  49k https │ audio only         mp4a.40.5   49k 22k low, m4a_dash                           
249 webm  audio only      2 │    1.49MiB  49k https │ audio only         opus        49k 48k low, webm_dash                          
250 webm  audio only      2 │    1.97MiB  64k https │ audio only         opus        64k 48k low, webm_dash                          
140 m4a   audio only      2 │    3.96MiB 130k https │ audio only         mp4a.40.2  130k 44k medium, m4a_dash                        
251 webm  audio only      2 │    3.92MiB 128k https │ audio only         opus       128k 48k medium, webm_dash                       
17  3gp   176x144      6  1 │    1.25MiB  41k https │ mp4v.20.3      41k mp4a.40.2    0k 22k 144p                                    
394 mp4   144x144     25    │  578.69KiB  18k https │ av01.0.00M.08  18k video only          144p, mp4_dash                          
160 mp4   144x144     25    │  265.63KiB   8k https │ avc1.4d400b     8k video only          144p, mp4_dash                          
278 webm  144x144     25    │  569.01KiB  18k https │ vp9            18k video only          144p, webm_dash                         
395 mp4   240x240     25    │  832.62KiB  27k https │ av01.0.00M.08  27k video only          240p, mp4_dash                          
133 mp4   240x240     25    │  348.18KiB  11k https │ avc1.4d400c    11k video only          240p, mp4_dash                          
242 webm  240x240     25    │  900.29KiB  29k https │ vp9            29k video only          240p, webm_dash                         
396 mp4   360x360     25    │    1.02MiB  33k https │ av01.0.00M.08  33k video only          360p, mp4_dash                          
134 mp4   360x360     25    │  498.17KiB  16k https │ avc1.4d4015    16k video only          360p, mp4_dash                          
243 webm  360x360     25    │    1.12MiB  37k https │ vp9            37k video only          360p, webm_dash                         
18  mp4   360x360     25  2 │    5.06MiB 165k https │ avc1.42001E   165k mp4a.40.2    0k 44k 360p                                    
397 mp4   480x480     25    │    1.43MiB  47k https │ av01.0.01M.08  47k video only          480p, mp4_dash                          
135 mp4   480x480     25    │  687.59KiB  22k https │ avc1.4d401e    22k video only          480p, mp4_dash                          
244 webm  480x480     25    │    1.82MiB  59k https │ vp9            59k video only          480p, webm_dash                         
398 mp4   720x720     25    │    1.82MiB  59k https │ av01.0.04M.08  59k video only          720p, mp4_dash                          
136 mp4   720x720     25    │  976.23KiB  31k https │ avc1.4d401f    31k video only          720p, mp4_dash                          
247 webm  720x720     25    │    5.46MiB 179k https │ vp9           179k video only          720p, webm_dash                         
22  mp4   720x720     25  2 │ ~  5.03MiB 160k https │ avc1.64001F   160k mp4a.40.2    0k 44k 720p                                    
399 mp4   1080x1080   25    │    9.83MiB 322k https │ av01.0.08M.08 322k video only          1080p, mp4_dash                         
137 mp4   1080x1080   25    │    2.15MiB  70k https │ avc1.640020    70k video only          1080p, mp4_dash                         
248 webm  1080x1080   25    │   16.66MiB 545k https │ vp9           545k video only          1080p, webm_dash

```

**Comment by pukkandan** [comment]
From your log, it doesn't look like the cookies contain login information. Can you try re-exporting the cookies, or even better, with `--cookies-from-browser`

**Comment by pukkandan** [comment]
When yt-dlp detects login info, you should see a message like:

    [debug] [youtube] Extracted SAPISID cookie

**Comment by TSkaalrud** [comment]
Brilliant! I can find 141 and that sweet sweet audio on [some] videos now! I guess that just comes down to whatever is uploaded/what YouTube decides to support? Either way, that fixes my problem, thanks! :D

**Comment by LAGlitch19** [comment]
Facing similar issue but the log also mentions Found YouTube account cookies:

yt-dlp --cookies=cookies.txt -vFU -f bestaudio https://music.youtube.com/watch?v=XclachpHxis
[debug] Command-line config: ['--cookies=cookies.txt', '-vFU', '-f', 'bestaudio', 'https://music.youtube.com/watch?v=XclachpHxis']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8 
[debug] yt-dlp version stable@2025.02.19 from yt-dlp/yt-dlp [4985a4041] (pip)
[debug] Python 3.12.0 (CPython AMD64 64bit) - Windows-11-10.0.22631-SP0 (OpenSSL 3.0.11 19 Sep 2023) 
[debug] exe versions: ffmpeg 7.1-full_build-www.gyan.dev (setts), ffprobe 7.1-full_build-www.gyan.dev 
[debug] Optional libraries: certifi-2024.02.02, mutagen-1.47.0, requests-2.32.3, sqlite3-3.42.0, urllib3-2.2.1, websockets-14.2
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1841 extractors 
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2025.02.19 from yt-dlp/yt-dlp 
yt-dlp is up to date (stable@2025.02.19 from yt-dlp/yt-dlp)
[debug] [youtube] Found YouTube account cookies 
[youtube] Extracting URL: https://music.youtube.com/watch?v=XclachpHxis
[youtube] XclachpHxis: Downloading webpage
[youtube] XclachpHxis: Downloading tv client config 
[youtube] XclachpHxis: Downloading player c8dbda2a 
[youtube] XclachpHxis: Downloading tv player API JSON 
[youtube] XclachpHxis: Downloading web music client config 
[youtube] XclachpHxis: Downloading web music player API JSON 
[debug] [youtube] Extracting signature function js_c8dbda2a_105 
[debug] Loading youtube-sigfuncs.js_c8dbda2a_105 from cache
[debug] Loading youtube-nsig.c8dbda2a from cache
[debug] [youtube] Decrypted nsig JpO8u3W3xnQ7y6R => HZFkWZErhAWwPg 
[debug] Loading youtube-nsig.c8dbda2a from cache
[debug] [youtube] Decrypted nsig 637-syPArCHWV5Y => By0klu2RuiYPrQ 
[debug] [youtube] Extracting signature function js_c8dbda2a_101
[debug] Loading youtube-sigfuncs.js_c8dbda2a_101 from cache
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec, channels, acodec, lang, proto 
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec, channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id        
[info] Available formats for XclachpHxis: 
ID  EXT   RESOLUTION FPS CH │   FILESIZE  TBR PROTO │ VCODEC         VBR ACODEC      ABR ASR MORE INFO
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────
sb3 mhtml 48x27        0    │                 mhtml │ images                                 storyboard
sb2 mhtml 45x45        1    │                 mhtml │ images                                 storyboard
sb1 mhtml 90x90        1    │                 mhtml │ images                                 storyboard
sb0 mhtml 180x180      1    │                 mhtml │ images                                 storyboard
249 webm  audio only      2 │    1.49MiB  49k https │ audio only         opus        49k 48k low, TV, webm_dash
250 webm  audio only      2 │    1.97MiB  64k https │ audio only         opus        64k 48k low, TV, webm_dash
140 m4a   audio only      2 │    3.96MiB 130k https │ audio only         mp4a.40.2  130k 44k medium, TV, m4a_dash
251 webm  audio only      2 │    3.92MiB 128k https │ audio only         opus       128k 48k medium, TV, webm_dash
160 mp4   144x144     25    │  265.63KiB   8k https │ avc1.4d400b     8k video only          144p, TV, mp4_dash
278 webm  144x144     25    │  569.01KiB  18k https │ vp9            18k video only          144p, TV, webm_dash
394 mp4   144x144     25    │  578.69KiB  18k https │ av01.0.00M.08  18k video only          144p, TV, mp4_dash
133 mp4   240x240     25    │  348.18KiB  11k https │ avc1.4d400c    11k video only          240p, TV, mp4_dash
242 webm  240x240     25    │  900.29KiB  29k https │ vp9            29k video only          240p, TV, webm_dash
395 mp4   240x240     25    │  832.62KiB  27k https │ av01.0.00M.08  27k video only          240p, TV, mp4_dash
134 mp4   360x360     25    │  498.17KiB  16k https │ avc1.4d4015    16k video only          360p, TV, mp4_dash
18  mp4   360x360     25  2 │ ≈  4.43MiB 145k https │ avc1.42001E        mp4a.40.2       44k 360p, TV
243 webm  360x360     25    │    1.12MiB  37k https │ vp9            37k video only          360p, TV, webm_dash
396 mp4   360x360     25    │    1.02MiB  33k https │ av01.0.00M.08  33k video only          360p, TV, mp4_dash
135 mp4   480x480     25    │  687.59KiB  22k https │ avc1.4d401e    22k video only          480p, TV, mp4_dash
244 webm  480x480     25    │    1.82MiB  59k https │ vp9            59k video only          480p, TV, webm_dash
397 mp4   480x480     25    │    1.43MiB  47k https │ av01.0.01M.08  47k video only          480p, TV, mp4_dash
136 mp4   720x720     25    │  976.23KiB  31k https │ avc1.4d401f    31k video only          720p, TV, mp4_dash
247 webm  720x720     25    │    5.46MiB 179k https │ vp9           179k video only          720p, TV, webm_dash
398 mp4   720x720     25    │    1.82MiB  59k https │ av01.0.04M.08  59k video only          720p, TV, mp4_dash
137 mp4   1080x1080   25    │    2.15MiB  70k https │ avc1.640020    70k video only          1080p, TV, mp4_dash
248 webm  1080x1080   25    │   16.66MiB 545k https │ vp9           545k video only          1080p, TV, webm_dash
399 mp4   1080x1080   25    │    9.83MiB 322k https │ av01.0.08M.08 322k video only          1080p, TV, mp4_dash
