### ISSUE TITLE
[viki.com] DRM-protected video but subtitles are user-submitted; would like to download subtitles

### ISSUE THREAD

**Issue by snowbie** [yt-dlp/yt-dlp#4629]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a site-specific feature
- [X] I've verified that I'm running yt-dlp version **2022.08.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

South Korea/Global*

### Example URLs

https://www.viki.com/videos/1150631v-ask-us-anything-lee-seung-gi-episode-124
https://www.viki.com/videos/1146077v
episode list: https://www.viki.com/tv/36478c#episodes

### Provide a description that is worded well enough to be understood

The title covers it + is as brief as it'll get, but I'll provide some additional info.
The website hosts broadcasted Korean shows. Often you can find it with hard-encoded subtitles, but this website appears to use a separate stream for multilanguage subtitles. Unlike the video stream, the subtitles are user-made and submitted, so the DRM-restriction wouldn't be applicable in this case (correct me if I'm wrong)

There is a "subtitle editor" that I think only Korean IPs can connect to. I can't explore this as I'm not in Korea. Otherwise, everything else seems globally accessible.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--list-formats', 'https://www.viki.com/videos/1166733v']
[debug] Encodings: locale cp65001, fs utf-8, pref cp65001, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.08.08 [3157158] (win32_exe)
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.22000-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg N-107742-g55c3c5a485-gbc109a53c7 (fdk,setts), ffprobe N-107742-g55c3c5a485-gbc109a53c7, rtmpdump 2.4-20220520-g922b131-GnuTLS_3.6.16-x86_64-static
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.08.08, Current version: 2022.08.08
yt-dlp is up to date (2022.08.08)
[debug] [viki] Extracting URL: https://www.viki.com/videos/1166733v
[viki] 1166733v: Downloading video JSON
[viki] 1166733v: Downloading video streams JSON
[viki] 1166733v: Downloading initial MPD manifest
[viki] 1166733v: Downloading MPD manifest
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), channels, vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
WARNING: This video is DRM protected and only images are available for download. Use --list-formats to see them
[info] Available formats for 1166733v:
ID         EXT   RESOLUTION │ PROTO │ VCODEC MORE INFO
────────────────────────────────────────────────────────────────────
image_jpeg mhtml unknown    │ mhtml │ images DASH storyboards (jpeg)
```

**Comment by pukkandan** [comment]
`--write-subtitles --ignore-no-formats`

**Comment by snowbie** [comment]
ahh thanks. I ran the following command and was able to obtain them.
```
yt-dlp --write-subs --ignore-no-formats --sub-format srt https://www.viki.com/videos/1146077v
```
