### ISSUE TITLE
[salttv] broken extractor (zattoo clone) 

### ISSUE THREAD

**Issue by omueller** [yt-dlp/yt-dlp#4630]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.08.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

First of all, thanks a lot to @goggle and team for the recent fixes, Zattoo looks fine now!   The issue here is about tv.salt.ch which is a rebranded zattoo.com: here the extractor doesn't seem to work at all (anymore). 

For a specific stream from today, zattoo download is working, Salt-TV (tv.salt.ch) is not.   For example for this stream it is ok with the Zattoo Extractor: 

```
$ yt-dlp --netrc https://zattoo.com/watch/telezueri/263168737
Zattoo] Downloading session token
[Zattoo] Opening session
[Zattoo] Logging in
[Zattoo] 263168737: Downloading video information (...)
```

but it fails with for the same show on Salt TV: 

```
$ yt-dlp --netrc https://tv.salt.ch/watch/telezueri/263052803
[SaltTV] Downloading session token
[SaltTV] Opening session
[SaltTV] Logging in
ERROR: This method must be implemented by subclasses
```

It is not a login issue (it then fails with a "Unable to login" message).      Not sure why this happens on SaltTv, as everything else seems to be the same as on the zattoo frontend. 

Do you have an idea how to fix this ?  I will also try 2-3 things the next days or weeks.  
Thanks & best regards. 

PS: Other small thing (possibly for another ticket), recorded shows extraction doesn't seem to work yet, or not always: 

```
$ yt-dlp --netrc https://tv.salt.ch/recording/463479573
[generic] 463479573: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] 463479573: Extracting information
ERROR: Unsupported URL: https://tv.salt.ch/recording/463479573

$ yt-dlp --netrc https://zattoo.com/recording/444173552
[generic] 444173552: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] 444173552: Extracting information
ERROR: Unsupported URL: https://zattoo.com/recording/444173552
```

but interesting enough, when switching to the another url scheme, it then works (stream from May 2022): 
```
yt-dlp --netrc https://zattoo.com/series/france-2/103863/2?recording=444173552
[ZattooRecordings] Downloading session token
[ZattooRecordings] Opening session
[ZattooRecordings] Logging in
[ZattooRecordings] 444173552: Downloading playlist
[ZattooRecordings] 254811212: Downloading video information (...)
```

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
$ yt-dlp -vU --netrc https://tv.salt.ch/watch/telezueri/263052803
[debug] Command-line config: ['-vU', '--netrc', 'https://tv.salt.ch/watch/telezueri/263052803']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.08.08 [3157158] (pip)
[debug] Python 3.10.6 (CPython 64bit) - macOS-12.5-x86_64-i386-64bit 
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 5.1 (setts), ffprobe 5.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.08.08, Current version: 2022.08.08
yt-dlp is up to date (2022.08.08)
[SaltTV] Downloading session token
[SaltTV] Opening session
[SaltTV] Logging in
[debug] [SaltTV] Extracting URL: https://tv.salt.ch/watch/telezueri/263052803
ERROR: This method must be implemented by subclasses
Traceback (most recent call last):
  File "/usr/local/Cellar/yt-dlp/2022.8.8/libexec/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1441, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/Cellar/yt-dlp/2022.8.8/libexec/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1517, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/Cellar/yt-dlp/2022.8.8/libexec/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 666, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/Cellar/yt-dlp/2022.8.8/libexec/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 739, in _real_extract
    raise NotImplementedError('This method must be implemented by subclasses')
NotImplementedError: This method must be implemented by subclasses
```

**Comment by goggle** [comment]
@omueller If you or someone else can provide account credentials for Salt TV, i can have a look (you find my email on my profile page).

I do not expect any of the Zattoo resellers to work because I could never test any of them... but it's good to hear that at least the login seems to work.

**Comment by pukkandan** [comment]
The first issue should be fixed now. Pls confirm

Re-opening for the the URL pattern issue. But next time, make sure to open separate issues

**Comment by omueller** [comment]
Thanks for the patch and the ticket updates!  Now after patching the zattoo.py file manually, a new error appears:  `ERROR: no such group`.  

Full output:
```
$ yt-dlp -vU --netrc https://tv.salt.ch/watch/telezueri/263052803
[debug] Command-line config: ['-vU', '--netrc', 'https://tv.salt.ch/watch/telezueri/263052803']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.08.08 [3157158] (pip)
[debug] Python 3.10.6 (CPython 64bit) - macOS-12.5-x86_64-i386-64bit 
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 5.1 (setts), ffprobe 5.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.08.08, Current version: 2022.08.08
yt-dlp is up to date (2022.08.08)
[SaltTV] Downloading session token
[SaltTV] Opening session
[SaltTV] Logging in
[debug] [SaltTV] Extracting URL: https://tv.salt.ch/watch/telezueri/263052803
ERROR: no such group
Traceback (most recent call last):
  File "/usr/local/Cellar/yt-dlp/2022.8.8/libexec/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1441, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/Cellar/yt-dlp/2022.8.8/libexec/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1517, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/Cellar/yt-dlp/2022.8.8/libexec/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 666, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/Cellar/yt-dlp/2022.8.8/libexec/lib/python3.10/site-packages/yt_dlp/extractor/zattoo.py", line 241, in _real_extract
    vid1, vid2 = self._match_valid_url(url).group('vid1', 'vid2')
IndexError: no such group
```

**Comment by pukkandan** [comment]
It seems I was too hasty with the patch. Will need account details to properly test and fix

Contact: discord (pukkandan#4207) / reddit (/u/pukkandan) / email (pukkandan.ytdlp@gmail.com)

**Comment by omueller** [comment]
> It seems I was too hasty with the patch. Will need account details to properly test and fix

Thanks & done (to you and @goggle).   Also available for any testing whenever needed.

**Comment by omueller** [comment]
> It seems I was too hasty with the patch. Will need account details to properly test and fix

@pukkandan: Thanks & done (to you and @goggle). Also available for any testing whenever needed.

**Comment by pukkandan** [comment]
I can't access the content due to geo-blocking

**Comment by omueller** [comment]
Confirmed working with SaltTV, thanks a lot for the PR @goggle and for the push @pukkandan, it is really nice to see this working now ! 

About the geo-blocking you would need to have a VPN located in Switzerland @pukkandan, if needed (for another issue for example) I should be able to setup something for you on a VM or similar, even if just for a few days/weeks.  

Best regards & thanks again!
