### ISSUE TITLE
ManyVids Extractor Enhancement - Description

### ISSUE THREAD

**Issue by A-Random-Mf** [yt-dlp/yt-dlp#4634]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a site-specific feature
- [X] I've verified that I'm running yt-dlp version **2022.08.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

USA

### Example URLs

https://www.manyvids.com/Video/1514661/How-to-leave-a-review-on-Manyvids/

### Provide a description that is worded well enough to be understood

I noticed that the manyvids extractor doesn't support scraping a video's description. Is it possible for this to be added.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vUO', 'description=', 'https://www.manyvids.com/Video/1514661/How-to-leave-a-review-on-Manyvids/']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.08.08 [3157158] (pip)
[debug] Python 3.10.4 (CPython 64bit) - Linux-4.15.0-189-generic-x86_64-with-glibc2.27 (glibc 2.27)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: avconv -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: avprobe -bsfs
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, secretstorage-3.3.2, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.08.08, Current version: 2022.08.08
yt-dlp is up to date (2022.08.08)
[debug] [ManyVids] Extracting URL: https://www.manyvids.com/Video/1514661/How-to-leave-a-review-on-Manyvids/
[ManyVids] 1514661: Downloading webpage
[ManyVids] 1514661: Downloading webpage
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 1514661: Downloading 1 format(s): 0
description = 'NA'
```

**Comment by dirkf** [comment]
The description is in several metadata fields and also in the text of the page. Probably best is to get the `<div>` with `id="pageMetaDetail"` of which the description and several other useful and currently not extracted, or wrongly extracted, fields are attributes:
```py
        info = self._search_regex(
            r'''(<div\b[^>]*\bid\s*=\s*(['"])pageMetaDetails\2[^>]*>)''',
            webpage, 'meta details', default='')
        info = extract_attributes(info)
```
Later:
```py
...
            'description': strip_or_none(info.get('data-meta-description')),
            'uploader': strip_or_none(info.get('data-meta-author')),
            'thumbnail': url_or_none(info.get('data-meta-image')),
...
```

**Comment by A-Random-Mf** [comment]
Forgive me. I appreciate your response but I had very little understanding of what you are talking about. Please elaborate

**Comment by A-Random-Mf** [comment]
Thank you
