### ISSUE TITLE
Extractor option `language` for `crunchyrollbeta`

### ISSUE THREAD

**Issue by m1karii** [yt-dlp/yt-dlp#4640]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a site-specific feature
- [ ] I've verified that I'm running yt-dlp version **2022.08.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

USA / most, if not all of Europe

### Example URLs

https://beta.crunchyroll.com/series/G1XHJVEXE/shadows-house

### Provide a description that is worded well enough to be understood

Extractor option `language` for `crunchyrollbeta`, it 'd have same function as extractor option `language` for `crunchyroll` which is already implemented. basically if i enter show URL, and not a specific video URL I want all episodes downloaded (which currently works) but I want to narrow it down to specific language so it doesnt download the same episode in multiple languages (portuguese, spanish, russian,...)

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

since this is a feature request and not a bug report i don't really know what to put in here.
i can't run `yt-dlp -vU <your command line>` since 'my command' doesn't exist because that syntax wasn't yet implemented - hence this issue

**Comment by pukkandan** [comment]
Explain why `--match-filter` or `-f` is insufficient for your usecase

**Comment by m1karii** [comment]
before i answer your question let me clarify that:
i don't have the latest version of `yt-dlp` because i run Manjaro and its repos are usually about 2-3 weeks behind Arch.
i have latest version currently available in the repos
i tried running `yt-dlp -U` but i got:
```
Latest version: 2022.08.08, Current version: 2022.07.18
ERROR: It looks like you installed yt-dlp with a package manager, pip or setup.py; Use that to update
```

**Comment by m1karii** [comment]
to my understanding `-f` is used for different video quality versions of the same video/url
however crunchyroll/crunchyrollbeta handles different dubs as completely different videos with different URLs
and i don't know how/if `--match-filter` would be applicable in this case -which could also be my ignorance

**Comment by pukkandan** [comment]
If you run `yt-dlp -J https://beta.crunchyroll.com/series/G1XHJVEXE/shadows-house > crunchyroll.json` and attach the json here, I can check whether match-filter is applicable. However, you need to be on the latest version first. Otherwise, I have no way of knowing whether some already implemented patch has fixed your issue

In either case, this is not a job for --extractor-args

**Comment by m1karii** [comment]
ok, i've downloaded the standalone build from releases and ran the command. this is what i've got:
[crunchyroll.json.txt](https://github.com/yt-dlp/yt-dlp/files/9316183/crunchyroll.json.txt)
(had to change filetype to `.txt` otherwise github wouldnt upload)

**Comment by m1karii** [comment]
i forgot to specify - my fault sry: im trying to download the japanese dub which doesnt have " (xx dub) appended to it
thats kinda the whole problem

**Comment by pukkandan** [comment]
Then --match-filter "title!*= Dub)"

**Comment by m1karii** [comment]
i ran 
```
yt-dlp --prefer-free-formats --paths "temp:./temp" --concurrent-fragments 8 --write-subs --sub-langs en-US --cookies cookies.txt --match-filter "title!*=' Dub)'" https://beta.crunchyroll.com/series/G1XHJVEXE/shadows-house
```
and got 
```
[crunchyroll:playlist:beta] Retrieving main page
[crunchyroll:playlist:beta] Authenticating with cookie
[crunchyroll:playlist:beta] Retrieving signed policy
[crunchyroll:playlist:beta] shadows-house: Retrieving series metadata
[crunchyroll:playlist:beta] shadows-house: Retrieving season list
[download] Downloading playlist: SHADOWS HOUSE
[crunchyroll:playlist:beta] shadows-house: Retrieving episode list for shadows-house-english-dub
ERROR: Invalid filter part "title--prefer-free-formats --paths temp:./temp --cookies cookies.txt https://beta.crunchyroll.com/series/G1XHJVEXE/shadows-house=' Dub)'"

```

**Comment by pukkandan** [comment]
Some quoting issue. Show verbose

**Comment by m1karii** [comment]
```
[debug] Command-line config: ['-v', '--prefer-free-formats', '--paths', 'temp:./temp', '--concurrent-fragments', '8', '--write-subs', '--sub-langs', 'en-US', '--cookies', 'cookies.txt', '--match-filter', 'title--prefer-free-formats --paths temp:./temp --concurrent-fragments 12 --write-subs --sub-langs en-US --cookies cookies.txt --match-filter title--prefer-free-formats', '--paths', 'temp:./temp', '--cookies', 'cookies.txt', "https://beta.crunchyroll.com/series/G1XHJVEXE/shadows-house=Dub https://beta.crunchyroll.com/series/G1XHJVEXE/shadows-house=' Dub)'", 'https://beta.crunchyroll.com/series/G1XHJVEXE/shadows-house']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.08.08 [3157158] (linux_exe)
[debug] Python 3.10.5 (CPython 64bit) - Linux-5.15.59-1-MANJARO-x86_64-with-glibc2.36 (glibc 2.36)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg present (needs_adtstoasc), ffprobe present, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, secretstorage-3.3.2, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] [generic] Extracting URL: https://beta.crunchyroll.com/series/G1XHJVEXE/shadows-house=Dub https://beta.crunchyroll.com/series/G1XHJVEXE/shadows-house=' Dub)'
[generic] shadows-house=' Dub)': Downloading webpage
ERROR: [generic] Unable to download webpage: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp/extractor/common.py", line 666, in extract
  File "yt_dlp/extractor/generic.py", line 2641, in _real_extract
  File "yt_dlp/extractor/common.py", line 817, in _request_webpage

  File "yt_dlp/extractor/common.py", line 799, in _request_webpage
  File "yt_dlp/YoutubeDL.py", line 3647, in urlopen
  File "urllib/request.py", line 525, in open
  File "urllib/request.py", line 634, in http_response
  File "urllib/request.py", line 563, in error
  File "urllib/request.py", line 496, in _call_chain
  File "urllib/request.py", line 643, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

[debug] [crunchyroll:playlist:beta] Extracting URL: https://beta.crunchyroll.com/series/G1XHJVEXE/shadows-house
[crunchyroll:playlist:beta] Retrieving main page
[crunchyroll:playlist:beta] Authenticating with cookie
[crunchyroll:playlist:beta] Retrieving signed policy
[crunchyroll:playlist:beta] shadows-house: Retrieving series metadata
[crunchyroll:playlist:beta] shadows-house: Retrieving season list
ERROR: Invalid filter part 'title--prefer-free-formats --paths temp:./temp --concurrent-fragments 12 --write-subs --sub-langs en-US --cookies cookies.txt --match-filter title--prefer-free-formats'
Traceback (most recent call last):
  File "yt_dlp/YoutubeDL.py", line 1441, in wrapper
  File "yt_dlp/YoutubeDL.py", line 1538, in __extract_info
  File "yt_dlp/YoutubeDL.py", line 1666, in process_ie_result
  File "yt_dlp/YoutubeDL.py", line 1726, in __process_playlist
  File "yt_dlp/YoutubeDL.py", line 1375, in _match_entry
  File "yt_dlp/YoutubeDL.py", line 1354, in check_filter
  File "yt_dlp/utils.py", line 3710, in _match_func
  File "yt_dlp/utils.py", line 3710, in <genexpr>
  File "yt_dlp/utils.py", line 3695, in match_str
  File "yt_dlp/utils.py", line 3696, in <genexpr>
  File "yt_dlp/utils.py", line 3685, in _match_one
ValueError: Invalid filter part 'title--prefer-free-formats --paths temp:./temp --concurrent-fragments 12 --write-subs --sub-langs en-US --cookies cookies.txt --match-filter title--prefer-free-formats'
```

**Comment by pukkandan** [comment]
Try `--match-filter 'title!*=" Dub)"'`

**Comment by m1karii** [comment]
works.

though i still think it'd be easier to have that extractor option.

**Comment by pukkandan** [comment]
This is not what extractor-args are for!

Ideally, we want to extract the language and put it in `language` field. But as I remember, @tejing1 had tried this but was unable to extract it

**Comment by m1karii** [comment]
> Ideally, we want to extract the language and put it in language field. But as I remember, @tejing1 had tried this but was unable to extract it

i think that might be because of the whole

> crunchyroll/crunchyrollbeta handles different dubs as completely different videos with different URLs

am not an expert though

how im seeing this is both `funimation` and `crunchyroll` have `language` extractor-arg and with both sites eventually going away in favor of what is currently `crunchyrollbeta` it'd be nice to have the ability to phase out unnecessary languages from the selection without having to do what the two of us were doing for the past 4 hours to find out its `--match-filter 'title!*=" Dub)"'` or something similar for other languages...

**Comment by tejing1** [comment]
We already do put the audio language into the per-format `language` field, but this results in a rather ugly UX, particularly for series extraction, as:
- It errors out when supplied a url for a video in another language, due to not finding any formats.
- It has to do the full episode extraction to discover that the language was wrong.

The first issue could be remedied by allowing a `language` field at the episode level in yt-dlp, to allow it to be used with `--match-filter`, but the second is kind of a clincher. The api just doesn't give us the information we need where we need it. And it's a quite significant time waster. It's not uncommon to have a show where ~90% of the videos are not in the language you want. Running the full extractor for all of those is just too unreasonably slow.

All of which means `--match-filter 'title!*=" Dub)"'` really is the best solution, I'm afraid. It's possible we should leave a note about this under crunchyroll:beta in the extractor args section of the README?

**Comment by pukkandan** [comment]
I'm not gonna put tips for different sites in readme. I'll pin it to #3766 for now

**Comment by tejing1** [comment]
There is at least some hope that crunchyroll will improve their api in this regard, since it relates to UX issues on the actual website. Right now all the seasons are thrown into 1 drop-down list, and most of them are completely uninteresting to most users due to the audio language. If they want to fix that, they'll need this data available at the season level in the api, so the javascript can filter by audio language.

**Comment by Jules-A** [comment]
> All of which means `--match-filters 'season !~= "([^()]+ Dub)"'` really is the best solution, I'm afraid.

That won't work for movies though where they lump the dubs and subs in same category.

**Comment by tejing1** [comment]
> That won't work for movies though where they lump the dubs and subs in same category.

Movies don't extract correctly yet in yt-dlp anyway, since their urls looks just like episode urls, but they actually have their own namespace in the api... but checking the requests made, it looks like they suffer from the same problem, with the added issue that there's literally no distinguishing metadata to separate the versions besides the audio language in the streams response. The web UI has an even worse UX here than with seasons, since you can't actually tell the version apart except by playing them...
