### ISSUE TITLE
[Site Request] Animelon (subs only)

### ISSUE THREAD

**Issue by m1karii** [yt-dlp/yt-dlp#4641]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [ ] I've verified that I'm running yt-dlp version **2022.08.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

NA, Europe, possibly worldwide

### Example URLs

https://animelon.com/video/57e51919e0afb465b74b544c
https://animelon.com/video/57e51919e0afb465b74b544d
https://animelon.com/video/6250f480d4168d1270c219e0
https://animelon.com/video/6250f480d4168d1270c219de
I'd also be like to bulk download with URLs like:
https://animelon.com/series/Hunter%20x%20Hunter%20(2011)
https://animelon.com/series/World%20Trigger

### Provide a description that is worded well enough to be understood

first of all i don't have the latest version of `yt-dlp` because i run Manjaro and its repos are usually about 2-3 weeks behind Arch.
i have latest version currently available in the repos
i tried running `yt-dlp -U` but i got:
```
Latest version: 2022.08.08, Current version: 2022.07.18
ERROR: It looks like you installed yt-dlp with a package manager, pip or setup.py; Use that to update
```
---
second of all Animelon is a site targeted for japanese language learners. theres anime with multiple subtitle tracks and builtin dictionary. it also could (depending on how you look at it) be in violation of some copirights, but according to them:

> Disclaimer: Animelon is a non-profit, educational entity. We do not intend to claim ownership of any anime content on this site nor do we monetize them. All anime content on this website belongs to the studios who created them.

> As per the Copyright Disclaimer under section 107 of the Copyright Act of 1976, allowance is made for “fair use” for purposes such as criticism, comment, news reporting, teaching, scholarship, education and research. Fair use is a use permitted by copyright statute that might otherwise be infringing. Non-profit, educational or personal use tips the balance in favor of fair use. 

this site is a grey area and i'm *not* creating this issue to get videos from it. on the other hand i'd like to be able list and download all the various subtitles it provides (which are to my knowledge created by the site's personnel) including bulk downloading using URLs like `https://animelon.com/series/Hunter%20x%20Hunter%20(2011)`.
as a side note the videos aren't even hosted on the site itself - if you Inspect Element the page you are able to get to `*.googlevideo.com` (which is also unsupported site atm) where the videos are actually stored and there you can just right-click Download As.
to summarize: I'm asking for subs. implement or consider implementing non-sub content downloading from Animelon or `*.googlevideo.com` at your own best discretion

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--prefer-free-formats', '--paths', 'temp:./temp', '--skip-download', '--list-subs', 'https://animelon.com/video/57e51919e0afb465b74b544c']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.07.18 [135f05e]
[debug] Python 3.10.5 (CPython 64bit) - Linux-5.15.59-1-MANJARO-x86_64-with-glibc2.36 (glibc 2.36)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 5.0.1 (setts), ffprobe 5.0.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.12.0, brotlicffi-1.0.9.2, certifi-2022.06.15, mutagen-1.45.1, secretstorage-3.3.2, sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.08.08, Current version: 2022.07.18
[debug] Downloading _update_spec from https://github.com/yt-dlp/yt-dlp/releases/download/2022.08.08/_update_spec
ERROR: It looks like you installed yt-dlp with a package manager, pip or setup.py; Use that to update
[debug] [generic] Extracting URL: https://animelon.com/video/57e51919e0afb465b74b544c
[generic] 57e51919e0afb465b74b544c: Downloading webpage
WARNING: [generic] Falling back on generic information extractor.
[generic] 57e51919e0afb465b74b544c: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://animelon.com/video/57e51919e0afb465b74b544c
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1431, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1506, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 644, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.10/site-packages/yt_dlp/extractor/generic.py", line 4108, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://animelon.com/video/57e51919e0afb465b74b544c
```

**Comment by Lesmiscore** [comment]
I don't think reposting the whole anime is "fair use"

**Comment by m1karii** [comment]
> I don't think reposting the whole anime is "fair use"

i agree but as i said

> this site is a grey area and i'm not creating this issue to get videos from it. on the other hand i'd like to be able list and download all the various subtitles it provides (which are to my knowledge created by the site's personnel) including bulk downloading using URLs like `https://animelon.com/series/Hunter%20x%20Hunter%20(2011)`.
as a side note the videos aren't even hosted on the site itself - if you Inspect Element the page you are able to get to `*.googlevideo.com` (which is also unsupported site atm) where the videos are actually stored and there you can just right-click Download As.
**to summarize: I'm asking for subs. implement or consider implementing non-sub content downloading from Animelon or `*.googlevideo.com` at your own best discretion**

did you even read the whole issue?

**Comment by pukkandan** [comment]
yt-dlp is a video downloader, not a subtitle downloader. It allows you to download subtitles and other metadata associated with the videos, but that doesn't mean we will support subtitles by itself

**Comment by m1karii** [comment]
*Fine, I'll Do It Myself*

1.) if somebody was to implement this would you accept the pull request?
2.) can you at least remove the piracy tag?

**Comment by Lesmiscore** [comment]
1. No
2. No

**Comment by m1karii** [comment]
@Lesmiscore I feel like you don't like me
