### ISSUE TITLE
TypeError: object of type 'generator' has no len()

### ISSUE THREAD

**Issue by pranshuthegamer** [yt-dlp/yt-dlp#4650]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [x] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.08.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

my ydl_opts
```
ydl_opts_playlist_extractor = {
        'extract-flat': True,
        'skip_download': True,
        'verbose': True,
    }
```

here i have a small script:
```
    info_dict = ydl_extractor.extract_info(playlist, download=False, process=False)

    # get the urls to perform download
    playlist_urls = []
    playlist_entries = info_dict['entries]
    # create tuples in a list with can be mapped to a multiprocessing pool
    for i in range( 0, len(playlist_entries) ):
        playlist_urls.append( (index, playlist_entries[index]['url']) )
```
this returns an error: `TypeError: object of type 'generator' has no len()`

However i found a workaround:
```
 # get the urls to perform download
    playlist_urls = []
    index = 0
    # create tuples in a list with can be mapped to a multiprocessing pool
    for video in info_dict['entries']:
        playlist_urls.append( (index, video['url']) )
        index += 1

```
i still would like to be able to access info_dict['entries']'s len if possible without downloading

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
~/bin ./yt-dlp-batch.py https://music.youtube.com/playlist\?list\=OLAK5uy_nF6-ijLz9eO-DMZzhzneNclNBj74Jvjgo
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.08.08 [3157158] (pip)
[debug] Python 3.10.5 (CPython 64bit) - Linux-5.18.14-arch1-1-x86_64-with-glibc2.36 (glibc 2.36)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 5.0.1 (setts), ffprobe 5.0.1
[debug] Optional libraries: Cryptodome-3.12.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] [youtube:tab] Extracting URL: https://music.youtube.com/playlist?list=OLAK5uy_nF6-ijLz9eO-DMZzhzneNclNBj74Jvjgo
[youtube:tab] OLAK5uy_nF6-ijLz9eO-DMZzhzneNclNBj74Jvjgo: Downloading webpage
WARNING: [youtube:tab] <urlopen error [Errno -3] Temporary failure in name resolution>. Retrying (1/3)...
[youtube:tab] OLAK5uy_nF6-ijLz9eO-DMZzhzneNclNBj74Jvjgo: Downloading webpage
[debug] [youtube:tab] Final URL: https://www.youtube.com/playlist?list=OLAK5uy_nF6-ijLz9eO-DMZzhzneNclNBj74Jvjgo
[youtube:tab] OLAK5uy_nF6-ijLz9eO-DMZzhzneNclNBj74Jvjgo: Downloading API JSON with unavailable videos
Traceback (most recent call last):
  File "/home/pranshutg/bin/./yt-dlp-batch.py", line 75, in <module>
    main()
  File "/home/pranshutg/bin/./yt-dlp-batch.py", line 50, in main
    print(len(info_dict['entries']))
TypeError: object of type 'generator' has no len()
```

**Comment by pukkandan** [comment]
> this returns an error: `TypeError: object of type 'generator' has no len()`

Do you not know what a generator is? If not, google it. I am not gonna teach you Python

https://github.com/yt-dlp/yt-dlp#embedding-yt-dlp

![image](https://user-images.githubusercontent.com/6623388/184480734-a23de4e3-b978-4d43-b112-87e879b056b1.png)

---

> i still would like to be able to access info_dict['entries']'s len if possible without downloading

You can look for `info['playlist_count']` but it may not always exist. If it doesn't you have to download all pages to get the number of videos

---

> 'extract-flat': True,

There is no such option. I think you are looking for:

```
    extract_flat:      Whether to resolve and process url_results further
                       ...
                       * 'in_playlist': Do not process inside playlist/multi_video
                       ...
```
