### ISSUE TITLE
Check existing chapter files before downloading?

### ISSUE THREAD

**Issue by changbowen** [yt-dlp/yt-dlp#4659]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.08.08** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

When using `--split-chapter`, It looks like the program will download the video, then split it to chapter files. Is it possible to check if all splitted chapter files exist first (if yes skip the download)?
And are there ways to delete the original (non-splitted) file after the split?

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
>  Is it possible to check if all splitted chapter files exist first (if yes skip the download)?

No, use --download-archive

> And are there ways to delete the original (non-splitted) file after the split?

`--exec rm` (unix) or `--exec del` (windows)

**Comment by changbowen** [comment]
Thanks for the info. I ended up with the embed version using the below code. Posted [here](https://gist.github.com/changbowen/7d8dd9ae2e00b91de1e67ed64522dd66) in case anyone is interested.
