### ISSUE TITLE
Choose audio format according to video format.

### ISSUE THREAD

**Issue by Senrt** [yt-dlp/yt-dlp#4664]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [x] I've verified that I'm running yt-dlp version **2022.08.14** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Existing yt-dlp cannot choose audio format according to video format.

or the other way around, choose video format according to the audio format.

Because yt-dlp uses the best quality to download video, it may produce for example MP4+OPUS=MKV or WEBM+M4A=MKV.

Both formats can cause strange playback issues on some devices, solution is to provide a new option.

Related discussion on the [yt-dlp discord](https://discord.com/channels/807245652072857610/807247901981016094/1007709450867585074).

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
Closing in favor of #8377
