### ISSUE TITLE
Installtion is still broken with devscripts directory

### ISSUE THREAD

**Issue by marillat** [yt-dlp/yt-dlp#4667]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.08.14** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Installation is still broken with devscripts under Ubuntu/Debian
The really best is to change the devscripts name. Why not to changes in dev-scripts ?

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp (1:2022.08.14-dmo1) over (1:2022.08.08-dmo2) ...
dpkg: error processing archive /srv/dak/ftp/pool/main/y/yt-dlp-dmo/yt-dlp_2022.08.14-dmo1_all.deb (--unpack):
 trying to overwrite '/usr/lib/python3/dist-packages/devscripts/__init__.py', which is also in package devscripts 2.22.2
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Errors were encountered while processing:
 /srv/dak/ftp/pool/main/y/yt-dlp-dmo/yt-dlp_2022.08.14-dmo1_all.deb
```

**Comment by Lesmiscore** [comment]
Ask the package distributor to fix this issue. We don't provide debian packages.

**Comment by marillat** [comment]
We already have a discusion about this isue in https://github.com/yt-dlp/yt-dlp/issues/4603

Why devscipts files are installed when they are only needed when yt-dlp is installed ?

**Comment by Lesmiscore** [comment]
Ar you currently trying to build the yt-dlp package? devscripts/ must not be contained in production package.

**Comment by marillat** [comment]
Yes I'm packaging yt-dlp since the beginning.

Then why these files are installed ?

**Comment by marillat** [comment]
To be sure, the debian package don't install the devscripts directory.

These files are installed by pybuild

**Comment by Lesmiscore** [comment]
Maybe setup.py is declaring itself to include devscripts/...

Can you try this patch then rebuild it?

```diff
$ git diff
diff --git a/setup.py b/setup.py
index 03f413081..81a701fe4 100644
--- a/setup.py
+++ b/setup.py
@@ -28,7 +28,7 @@
 
 def packages():
     if setuptools_available:
-        return find_packages(exclude=('youtube_dl', 'youtube_dlc', 'test', 'ytdlp_plugins'))
+        return find_packages(exclude=('youtube_dl', 'youtube_dlc', 'test', 'ytdlp_plugins', 'devscripts'))
 
     return [
         'yt_dlp', 'yt_dlp.extractor', 'yt_dlp.downloader', 'yt_dlp.postprocessor', 'yt_dlp.compat',
```

**Comment by marillat** [comment]
Thanks, this fix this issue.
