### ISSUE TITLE
Need to filter youtube video description with --match-filter but I don't understand reg expressions

### ISSUE THREAD

**Issue by masterofobzene** [yt-dlp/yt-dlp#4672]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **hugged** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.08.14** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I need to use match-filters; I've looked at documentation but its writen too technicaly for me and I couldn't find any logic on the commands needed to be passed to youtube-dlp. I don't understand reg expressions language.

```
--match-filters FILTER          Generic video filter. Any "OUTPUT TEMPLATE"
                                field can be compared with a number or a
                                string using the operators defined in
                                "Filtering Formats". 
                                You can also simply
                                specify a field to match if the field is
                                present, use "!field" to check if the field
                                is not present, and "&" to check multiple
                                conditions. Use a "\" to escape "&" or
                                quotes if needed. If used multiple times,
                                the filter matches if atleast one of the
                                conditions are met. E.g. --match-filter
                                !is_live --match-filter "like_count>?100 &
                                description~='(?i)\bcats \& dogs\b'" matches 
                                only videos that are not live OR those that
                                have a like count more than 100 (or the like
                                field is not available) and also has a
                                description that contains the phrase "cats &
                                dogs" (caseless). Use "--match-filter -" to
                                interactively ask whether to download each
                                 video 
```

I need to filter (discard) videos that have a phrase on their description in youtube for example "news of today".
I don't understand reg expressions or whatever is being used by Y-dlp here. 
Can anybody tell be what is the exact command to filter e.g: --match-filter "description~='(?i)\btnews \of today\b'"

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
No Verbose since its a question about functionality, not a bug.
```

**Comment by pukkandan** [comment]
idk what you are expecting of me here. To teach you regex?

Anyway, for the specific use-case you have asked for, regex is not needed, only `*=`.

    --match-filter "description*='news of today'"


Refer the documentation of the operators for more info - `using the operators defined in "Filtering Formats"`

**Comment by pukkandan** [comment]
glad I could help. I was confused because of the emphasis on regex in your question
