### ISSUE TITLE
Channel having live stream isn't shown

### ISSUE THREAD

**Issue by WINOFFRG** [yt-dlp/yt-dlp#4679]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.08.14** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

I want to list all live stream of a channel. Just their IDs and Title. This issue is much better discussed on [reddit](https://www.reddit.com/r/youtubedl/comments/wq16xz/live_videos_of_a_channel/)  as it didn't even worked for them

The Channel: https://www.youtube.com/c/News18Rajasthan/ at the time of posting already has 2 live videos on going. 

![image](https://user-images.githubusercontent.com/61311751/184965367-6b520d2e-9ac7-43b1-a0e1-6854bc954e7c.png)

Upon using the command ```yt-dlp --flat-playlist --print "%(id)s # %(live_status)s # %(title)s" --match-filter "live_status != not_live"  --playlist-end 50 https://www.youtube.com/c/News18Rajasthan/``` I don't get those videos. Where could the issue be?

I tried increasing the playlist end limit till 500 but still no success.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--flat-playlist', '--print', '%(id)s # %(live_status)s # %(title)s', '--match-filter', 'live_status != not_live', '--playlist-end', '10', 'https://www.youtube.com/c/News18Rajasthan']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.08.14 [5593720] (pip)
[debug] Python 3.8.10 (CPython 64bit) - Linux-5.13.0-1031-x86_64-with-glibc2.29 (glibc 2.31)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.2.7, ffprobe 4.2.7
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2019.11.28, mutagen-1.45.1, secretstorage-2.3.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.08.14, Current version: 2022.08.14
yt-dlp is up to date (2022.08.14)
[debug] [youtube:tab] Extracting URL: https://www.youtube.com/c/News18Rajasthan
[youtube:tab] News18Rajasthan: Downloading webpage
[youtube:tab] A channel/user page was given. All the channel's videos will be downloaded. To download only the videos in the home page, add a "/featured" to the URL
[debug] [youtube:tab] Final URL: https://www.youtube.com/c/News18Rajasthan/videos
[download] Downloading playlist: News18 Rajasthan - Videos
[youtube:tab] Playlist News18 Rajasthan - Videos: Downloading 10 videos
[debug] The information of all playlist entries will be held in memory
[download] Downloading video 1 of 10
1dn3zUEnrf8 # was_live # Rajasthan Heavy Rain Alert News Live I भारी बारिश का ऑरेंज अलर्ट जारी, अगले 24 घंटे राजस्थान पर भारी
[download] Downloading video 2 of 10
vP8zI7TzGR0 # NA # Jaipur News | संत हनुमानदास ने दी आत्मदाह की चेतावनी, आश्रम की ज़मीन पर कब्जे का लगाया आरोप
[download] Downloading video 3 of 10
9l9aya5WUH8 # NA # Jalore Student Death News | BJP MLA Jogeshwar Garg का बयान, 'घड़े का पानी पीने वाली बात गलत'
[download] Downloading video 4 of 10
n9Z3SYJ8Mi4 # was_live # Jalore Student Death News Updates Live | Jalore में नेताओं का मेला, इलाज के वक्त परिवार था अकेला!
[download] Downloading video 5 of 10
Ju5exQD2PxU # NA # PM Modi का सोशल मीडिया पर जलवा,  Youtube पर Trending No 1 पर आए | Red Fort | Hindi News
[download] Downloading video 6 of 10
SdPfto9WuaQ # NA # Jaisalmer News | कोतवाली थाने के सामने खुद को आग लगाने वाले बुजुर्ग की इलाज के दौरान मौत
[download] Downloading video 7 of 10
lGM1BEbZy9c # was_live # Live: Heavy Rain in Rajasthan | भारी बारिश ने डुबाए राजस्थान के कई शहर | Weather Update | Monsoon
[download] Downloading video 8 of 10
QtFYLmDOqJE # NA # Today's Top News | देखिए आज की बड़ी खबरें | Pradesh Hamara | Top Headlines | News18 Rajasthan
[download] Downloading video 9 of 10
_Fcz7AeBuvE # NA # Amul Milk Price Hike: अमूल और Mother Dairy का दूध हुआ महंगा, नई दरें कल से लागू
[download] Downloading video 10 of 10
oBewWtGKoGg # NA # Russia Ukraine War | रूस ने अब America को दी धमकी! | Vladimir Putin | Hindi news
[download] Finished downloading playlist: News18 Rajasthan - Videos
```

**Comment by pukkandan** [comment]
Your command is asking yt-dlp to look at the last 50 uploaded videos of the channel and tell you which ones are/were live. So if the livestream isn't in the last 50, it returns nothing.


Your options are:
* Let yt-dlp parse the whole channel (ie, remove --playlist-end)
* Ask yt-dlp to parse the `/featured` page (https://www.youtube.com/c/News18Rajasthan/featured)
* Use the url of the the link to the "Live now" shelf/playlist on the channel page. In this case, it's https://www.youtube.com/c/News18Rajasthan/videos?view=2&sort=dd&live_view=501&shelf_id=0

**Comment by pukkandan** [comment]
@coletdjnz Why do you think it's a site bug?

**Comment by WINOFFRG** [comment]
Understood, Thanks! Need one confirmation, The link format you mentioned in iii, Does that work for all channels? Or does it have some edge cases where a video is actually live but not listed?

Also, As you mentioned that `--playlist-end` looks for the whole list till limit (50) and return nothing if none of the videos are live, In my case I still get 50 videos where `live_status` is printed as `NA` and fliter is `live_status = is_live`, is it a bug or expected behaviour?

**Comment by pukkandan** [comment]
Not all metadata is available when using `--flat-playlist`. Remove that option. I can look at if `live_status` can be extracted with that option, but no guarantee

> The link format you mentioned in iii, Does that work for all channels? Or does it have some edge cases where a video is actually live but not listed?

The link I gave was copied specifically from that channel's home page. I don't know how universal that pattern is

**Comment by pukkandan** [comment]
> Not all metadata is available when using --flat-playlist. Remove that option. I can look at if live_status can be extracted with that option, but no guarantee

Update on this: yt-dlp is looking at the `live now` badge on the page and returning the correct live_status when the video is actually live. But when the badge is not present, we can't make sure it's not live and so NA is returned. Eg:

```
❯ yt-dlp -O url= -O live_status= https://www.youtube.com/c/IShowSpeed/videos --playlist-end 10 --flat-play
url = 'https://www.youtube.com/watch?v=9hcVzLYgs3I'
live_status = 'is_live'
url = 'https://www.youtube.com/watch?v=j55gbUSFFac'
live_status = 'was_live'
url = 'https://www.youtube.com/watch?v=G3FUym6rorQ'
live_status = 'was_live'
url = 'https://www.youtube.com/watch?v=dhTwCxXJeaA'
live_status = 'was_live'
url = 'https://www.youtube.com/watch?v=X9kqnWXm1jw'
live_status = 'was_live'
url = 'https://www.youtube.com/watch?v=epP0yucvYGc'
live_status = 'was_live'
url = 'https://www.youtube.com/watch?v=J75pIuPdZd8'
live_status = 'was_live'
url = 'https://www.youtube.com/watch?v=aK-9YFSgGvs'
live_status = 'was_live'
url = 'https://www.youtube.com/watch?v=VQTEruMn7zA'
live_status = 'was_live'
url = 'https://www.youtube.com/watch?v=YfsNy0uSJo0'
live_status = 'was_live'
```

**Comment by WINOFFRG** [comment]
Yeah understood, I personally feel that this should be improved that whenever a video live badge isnt present some kind of message or warnings should be shown so that user doesnt feel as if it is a bug but to make them realise the probability of identifiy, although just a suggestion.

BTW, How can I print the desirec fields like thumbnail, title, duration, id, streamUrl specfic fields in JSON format?
I tried using `--print-json` but that just prints some heavy object. Pardon if it's off the title.

**Comment by pukkandan** [comment]
I think you mean `--dump-json` and not `--print-json`. But yeah, that is the json containing all metadata. If you want to only print specific fields, you are gonna have to construct the json from the individual fields. Eg:

    yt-dlp URL -O '"{"title": %(title)j, "duration": %(duration)j, "id": %(id)j}'`

**Comment by WINOFFRG** [comment]
My bad yes `--dump-single-json`. I think it would then be better to get the data over API and parse it then. anyhow, Thanks! closing the issue.

**Comment by coletdjnz** [comment]
> > Not all metadata is available when using --flat-playlist. Remove that option. I can look at if live_status can be extracted with that option, but no guarantee
> 
> Update on this: yt-dlp is looking at the `live now` badge on the page and returning the correct live_status when the video is actually live. But when the badge is not present, we are not sure completely sure it's `not_live` and so NA is returned. Eg:
> 
> ```
> ❯ yt-dlp -O url= -O live_status= https://www.youtube.com/c/IShowSpeed/videos --playlist-end 10 --flat-play
> url = 'https://www.youtube.com/watch?v=9hcVzLYgs3I'
> live_status = 'is_live'
> url = 'https://www.youtube.com/watch?v=j55gbUSFFac'
> live_status = 'was_live'
> url = 'https://www.youtube.com/watch?v=G3FUym6rorQ'
> live_status = 'was_live'
> url = 'https://www.youtube.com/watch?v=dhTwCxXJeaA'
> live_status = 'was_live'
> url = 'https://www.youtube.com/watch?v=X9kqnWXm1jw'
> live_status = 'was_live'
> url = 'https://www.youtube.com/watch?v=epP0yucvYGc'
> live_status = 'was_live'
> url = 'https://www.youtube.com/watch?v=J75pIuPdZd8'
> live_status = 'was_live'
> url = 'https://www.youtube.com/watch?v=aK-9YFSgGvs'
> live_status = 'was_live'
> url = 'https://www.youtube.com/watch?v=VQTEruMn7zA'
> live_status = 'was_live'
> url = 'https://www.youtube.com/watch?v=YfsNy0uSJo0'
> live_status = 'was_live'
> ```

yes this is why I marked it as site bug

I fixed it in https://github.com/yt-dlp/yt-dlp/pull/4470

**Comment by WINOFFRG** [comment]
Hey, Just one more question. With
`yt-dlp --dump-single-json --flat-playlist --skip-download "https://www.youtube.com/user/disneyjunior/videos?view=2&sort=dd&live_view=501&shelf_id=0" `

I am able to get all the entities/metadata of all the live videos of that channel, Within the same command  is it possible to get the playback HLS URL as well?

**Comment by coletdjnz** [comment]
> @coletdjnz Why do you think it's a site bug?


I misunderstood the issue. I thought this was related to some variations of the live badge not being extracted which is fixed in #4470)

**Comment by coletdjnz** [comment]
> 

this should contain the formats and their urls

**Comment by WINOFFRG** [comment]
Sorry @coletdjnz  I just lost the reference.  

> this should contain

What should give me the metadata as well as the video urls? 

Are to referring to command above I wrote just above? Sorry but that doesn't gives me the video playback URL.

**Comment by pukkandan** [comment]
Show verbose log

**Comment by WINOFFRG** [comment]
Here it is 

```
yt-dlp -vU --dump-single-json --flat-playlist --skip-download --get-url "https://www.youtube.com/user/disneyjunior/videos?view=2&sort=dd&live_view=501&shelf_id=0" 
[debug] Command-line config: ['-vU', '--dump-single-json', '--flat-playlist', '--skip-download', '--get-url', 'https://www.youtube.com/user/disneyjunior/videos?view=2&sort=dd&live_view=501&shelf_id=0']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.08.14 [5593720] (pip)
[debug] Python 3.8.10 (CPython 64bit) - Linux-5.13.0-1031-azure-x86_64-with-glibc2.29 (glibc 2.31)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.2.7, ffprobe 4.2.7
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2019.11.28, mutagen-1.45.1, secretstorage-2.3.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.08.14, Current version: 2022.08.14
yt-dlp is up to date (2022.08.14)
[debug] [youtube:tab] Extracting URL: https://www.youtube.com/user/disneyjunior/videos?view=2&sort=dd&live_view=501&shelf_id=0
[youtube:tab] disneyjunior: Downloading webpage
[debug] [youtube:tab] Final URL: https://www.youtube.com/user/disneyjunior/videos?view=2&sort=dd&live_view=501&shelf_id=0
[download] Downloading playlist: Disney Junior - Videos
[youtube:tab] Playlist Disney Junior - Videos: Downloading 5 videos of 5
[debug] The information of all playlist entries will be held in memory
[download] Downloading video 1 of 5
https://www.youtube.com/watch?v=PWzUQZNc6mk
[download] Downloading video 2 of 5
https://www.youtube.com/watch?v=dX1jBiY5eeo
[download] Downloading video 3 of 5
https://www.youtube.com/watch?v=qkz0X3m93jM
[download] Downloading video 4 of 5
https://www.youtube.com/watch?v=QpOukjsjjJw
[download] Downloading video 5 of 5
https://www.youtube.com/watch?v=uGdmXdZZh0E
[download] Finished downloading playlist: Disney Junior - Videos
```

**Comment by pukkandan** [comment]
You can't get stream URL with `--flat-playlist`

**Comment by WINOFFRG** [comment]
My bad it makes sense. Thanks!
