### ISSUE TITLE
Aria2c not working on linux?

### ISSUE THREAD

**Issue by Hackermanswitch** [yt-dlp/yt-dlp#468]
Hi just installed yt-dlp and im a huge fan of the aria2c downloader cause its way faster as ffmpeg.
now im using this command: `yt-dlp --allow-unplayable-formats --external-downloader aria2c -f bestvideo "{0}" -o "{1}{2}_encrypted.mp4`

but it does look like its using ffmpeg instead of aria2c.
<img width="414" alt="Schermafbeelding 2021-07-05 om 14 18 24" src="https://user-images.githubusercontent.com/67789649/124470421-e06f6c00-dd9b-11eb-885e-4369b0d1c90b.png">

any thoughts?

**Comment by pukkandan** [comment]
### IGNORING THE ISSUE TEMPLATE WILL RESULT IN ISSUE CLOSED AS INCOMPLETE

Create a new issue using the correct template with all necessary information including the `--verbose` output (as text, not screenshot)
