### ISSUE TITLE
Downloading youtube clips in batch corrupts most of them

### ISSUE THREAD

**Issue by KraXen72** [yt-dlp/yt-dlp#4694]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.08.14** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Europe

### Provide a description that is worded well enough to be understood

```
https://www.youtube.com/clip/UgkxEM49kpk9FMdDW69vvagwxDlieRHbpmxI
https://www.youtube.com/clip/UgkxQ6ma88aW00WSoEJgdB0UUOGeZb5RLr7v
https://www.youtube.com/clip/Ugkx13AL-Q5R64es04_yB8GZB5g8OWOj1Mfn
https://www.youtube.com/clip/UgkxZRxphg5jf2GSF2NyqS7V83Pxkw2Jfnz_
https://www.youtube.com/clip/UgkxeHo_q9GdYWcZ6hnwU919-Xym7k_WJnAN
https://www.youtube.com/clip/Ugkx3dfp-bJN2943maQHEmiHW61yg0qjyLX1
https://www.youtube.com/clip/UgkxB9dgKFHXfwJuRrxPUeUdHCqU7ylgy6G3
https://www.youtube.com/clip/UgkxSXpM-UwxS82raEvCjAwnT56Zt2XAIjSI
https://www.youtube.com/clip/Ugkxw_9-sALttF3niOuXEFIU_v4wei7EtJx_
https://www.youtube.com/clip/UgkxOpVG82zDwPt3V4ZmqCmIqxjfOIDHcRxU
```
these are the clips i attempted to download with a simple
`yt-dlp -a batch.txt --remux-video mp4`

- UgkxQ6ma88aW00WSoEJgdB0UUOGeZb5RLr7v doesen't have **video** for the first part of the clip
- Ugkxw_9-sALttF3niOuXEFIU_v4wei7EtJx_ doesen't have **video** for the first part of the clip
- UgkxB9dgKFHXfwJuRrxPUeUdHCqU7ylgy6G3 doesen't have **video** for the first part of the clip
- Ugkx13AL-Q5R64es04_yB8GZB5g8OWOj1Mfn doesen't have **video** for the first part of the clip
- UgkxZRxphg5jf2GSF2NyqS7V83Pxkw2Jfnz_ doesen't have **audio** for the first part of the clip
- UgkxOpVG82zDwPt3V4ZmqCmIqxjfOIDHcRxU doesen't have **audio** for the first part of the clip
  
## config
--ffmpeg-location D:/coding/yt-dlp/ffmpeg-master-latest-win64-gpl-shared/bin/ffmpeg.exe
--audio-quality 0

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
https://pastebin.com/VP6GKicx
```

**Comment by pukkandan** [comment]
Use `--force-keyframes-at-cut`

**Comment by KraXen72** [comment]
will try this once im at the pc, but please mention this in the documentation that yt clips should be downloaded with this option.

**Comment by KraXen72** [comment]
with this option the downloading is extremly slow. 4 or so 40 second videos have been downloading for over 20 minutes and only one is downloaded. is there an alternative option?

**Comment by pukkandan** [comment]
No. We cannot accurately cut clips without reencoding (which is slow)
