### ISSUE TITLE
Cannot download ongoing or just endded YouTube livestream 

### ISSUE THREAD

**Issue by ForsakenRei** [yt-dlp/yt-dlp#4695]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.08.14** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

US

### Provide a description that is worded well enough to be understood

When downloading an on-going livestream or a recently ended livestream, returned WARNING <ulropen erro [Errno 11004] getaddrinfo failed> and following errors:

- If the link is an on-going stream, get Error: No video formats found. Tried both --live-from-start and --no-live-from-start but same result.

- If the link is a stream just ended shortly, get Error: This live event has ended.

yt-dlp version: 2022.8.14, verbose output in the following section. 1st one is on-going livestream at the time. 2nd one is ended stream lived 1 hour ago at the time.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['https://www.youtube.com/watch?v=fCdXbQmwf2A', '--no-live-from-start', '-vU']
[debug] Encodings: locale cp65001, fs utf-8, pref cp65001, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.08.14 [5593720] (win32_exe)
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 2022-05-26-git-0dcbe1c1aa-essentials_build-www.gyan.dev (setts), ffprobe 2022-05-26-git-0dcbe1c1aa-essentials_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.08.14, Current version: 2022.08.14
yt-dlp is up to date (2022.08.14)
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=fCdXbQmwf2A
[youtube] fCdXbQmwf2A: Downloading webpage
[youtube] fCdXbQmwf2A: Downloading android player API JSON
[youtube] fCdXbQmwf2A: Downloading m3u8 information
WARNING: [youtube] Failed to download m3u8 information: <urlopen error [Errno 11004] getaddrinfo failed>
[youtube] fCdXbQmwf2A: Downloading m3u8 information
WARNING: [youtube] Failed to download m3u8 information: <urlopen error [Errno 11004] getaddrinfo failed>
ERROR: [youtube] fCdXbQmwf2A: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1441, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1538, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1596, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2514, in process_video_result
  File "yt_dlp\YoutubeDL.py", line 1009, in raise_no_formats
yt_dlp.utils.ExtractorError: [youtube] fCdXbQmwf2A: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U



[debug] Command-line config: ['https://www.youtube.com/watch?v=XeV9fY_YKVM', '-vU']
[debug] Encodings: locale cp65001, fs utf-8, pref cp65001, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.08.14 [5593720] (win32_exe)
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 2022-05-26-git-0dcbe1c1aa-essentials_build-www.gyan.dev (setts), ffprobe 2022-05-26-git-0dcbe1c1aa-essentials_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.08.14, Current version: 2022.08.14
yt-dlp is up to date (2022.08.14)
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=XeV9fY_YKVM
[youtube] XeV9fY_YKVM: Downloading webpage
[youtube] XeV9fY_YKVM: Downloading android player API JSON
[youtube] XeV9fY_YKVM: Downloading m3u8 information
WARNING: [youtube] Failed to download m3u8 information: <urlopen error [Errno 11004] getaddrinfo failed>
[youtube] XeV9fY_YKVM: Downloading MPD manifest
WARNING: [youtube] Failed to download MPD manifest: <urlopen error [Errno 11004] getaddrinfo failed>
[youtube] XeV9fY_YKVM: Downloading m3u8 information
WARNING: [youtube] Failed to download m3u8 information: <urlopen error [Errno 11004] getaddrinfo failed>
[youtube] XeV9fY_YKVM: Downloading MPD manifest
WARNING: [youtube] Failed to download MPD manifest: <urlopen error [Errno 11004] getaddrinfo failed>
ERROR: [youtube] XeV9fY_YKVM: This live event has ended.
  File "yt_dlp\extractor\common.py", line 666, in extract
  File "yt_dlp\extractor\youtube.py", line 3519, in _real_extract
  File "yt_dlp\extractor\common.py", line 1148, in raise_no_formats
```

**Comment by pukkandan** [comment]
It's an issue with your network, firewall or the local CDN

**Comment by ForsakenRei** [comment]
> It's an issue with your network, firewall or the local CDN

Hmm, I just noticed it today but everything worked a few days ago. I will check my pi-hole setting when I get back home. Thanks!

**Comment by ForsakenRei** [comment]
Seems to be an issue related to pi-hole. Will investigate more on myself.
