### ISSUE TITLE
[Instagram:reels] Unable to extract video url

### ISSUE THREAD

**Issue by thebeautyofcoding** [yt-dlp/yt-dlp#4711]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.08.19** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

With the following code snippet I am able to download specific Reels. 
For example I can get this Reel: https://www.instagram.com/reel/CfJn72HA85l/

However, trying to get this Reel: https://www.instagram.com/reel/ChCc0z8AS1a/ won't work and the following error is thrown:
raise DownloadError(message, exc_info)
yt_dlp.utils.DownloadError: ERROR: [Instagram] ChCc0z8AS1a: Unable to extract video url; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```
import yt_dlp
ydl_opts = {}
        url=parser.parse_args()['url']
        print('url!',url)
        with yt_dlp.YoutubeDL(ydl_opts) as ydl:
            
            info = ydl.extract_info(url, download=True)
```

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.08.19 [48c88e0] (win32_exe)
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg N-104465-g08a501946f-20211104 (setts), ffprobe N-104465-g08a501946f-20211104
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.08.19, Current version: 2022.08.19
yt-dlp is up to date (2022.08.19)
```

**Comment by thebeautyofcoding** [comment]
This error also occurs when running 
`
yt-dlp "https://www.instagram.com/reel/ChCc0z8AS1a/"
`
in the terminal window. 
Other Reels can be downladed, but a few seem not to work on my machine.
However, I asked a friend to run the exact same command, and for him it seems to work and he is able to get that specific Reel.
What's going on here? Is it just a problem with my machine?

**Comment by october262** [comment]
> This error also occurs when running `yt-dlp "https://www.instagram.com/reel/ChCc0z8AS1a/"` in the terminal window. Other Reels can be downloaded, but a few do not seem to work on my machine. However, I asked a friend to run the exact same command, and for him it seems to work and he is able to get that specific Reel. What's going on here? Is it just a problem with my machine?

try with this link  yt-dlp "https://www.instagram.com/reel/ChCc0z8AS1a/?utm_source=ig_web_copy_link"

**Comment by SubZero5** [comment]
Here on my Laptop, is a similar issue:

```
>\xFer\yt-dlp.exe -vU http://instagram.com/honeybirdette
[debug] Command-line config: ['-vU', 'http://instagram.com/honeybirdette']
[debug] Encodings: locale cp1254, fs utf-8, pref cp1254, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.08.19 [48c88e0] (win32_exe)
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.08.19, Current version: 2022.08.19
yt-dlp is up to date (2022.08.19)
[debug] [instagram:user] Extracting URL: http://instagram.com/honeybirdette
[instagram:user] honeybirdette: Downloading webpage
ERROR: [instagram:user] honeybirdette: Unable to extract data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 666, in extract
  File "yt_dlp\extractor\instagram.py", line 582, in _real_extract
  File "yt_dlp\extractor\instagram.py", line 515, in _parse_graphql
  File "yt_dlp\extractor\common.py", line 1218, in _search_regex
```

```
>\xFer\yt-dlp.exe -vU https://instagram.com/honeybirdette
[debug] Command-line config: ['-vU', 'https://instagram.com/honeybirdette']
[debug] Encodings: locale cp1254, fs utf-8, pref cp1254, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.08.19 [48c88e0] (win32_exe)
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.08.19, Current version: 2022.08.19
yt-dlp is up to date (2022.08.19)
[debug] [instagram:user] Extracting URL: https://instagram.com/honeybirdette
[instagram:user] honeybirdette: Downloading webpage
ERROR: [instagram:user] honeybirdette: Unable to extract data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 666, in extract
  File "yt_dlp\extractor\instagram.py", line 582, in _real_extract
  File "yt_dlp\extractor\instagram.py", line 515, in _parse_graphql
  File "yt_dlp\extractor\common.py", line 1218, in _search_regex
```

**Comment by pukkandan** [comment]
@SubZero5 #4394
