### ISSUE TITLE
[YouTube] "--source-address" option not working

### ISSUE THREAD

**Issue by MimuraKyosuke** [yt-dlp/yt-dlp#4713]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.08.19** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

This video is probably only available in Japan.
I live in Japan so I can access it with a browser.
I can watch this video normally.

Until last month it was possible to download using the "--source-address" option.
But now I can't download it.
Not only this video, but all Japan-only videos cannot be downloaded.
Is the "--source-address" option no longer available?

Here is the previous question.
#3641

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--source-address', '123.456.789.123', '-f', 'b', 'https://www.youtube.com/watch?v=jwCz9KmGuYY']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.08.19 [48c88e0] (zip)
[debug] Python 3.8.10 (CPython 64bit) - Linux-5.4.0-94-generic-x86_64-with-glibc2.29 (glibc 2.31)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: none
[debug] Optional libraries: certifi-2019.11.28, secretstorage-2.3.1, sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.08.19, Current version: 2022.08.19
yt-dlp is up to date (2022.08.19)
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=jwCz9KmGuYY
[youtube] jwCz9KmGuYY: Downloading webpage
[youtube] jwCz9KmGuYY: Downloading android player API JSON
ERROR: [youtube] jwCz9KmGuYY: Video unavailable. The uploader has not made this video available in your country
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 666, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/youtube.py", line 3552, in _real_extract
    self.raise_no_formats(reason, expected=True)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 1148, in raise_no_formats
    raise ExtractorError(msg, expected=expected, video_id=video_id)
```

**Comment by Lesmiscore** [comment]
`--source-address` exists for choosing what network interface to originate connections from.

**Comment by MimuraKyosuke** [comment]
Thank you for your reply.
I was able to download with the same command until last month, I would like to know why I can't now.

**Comment by pukkandan** [comment]
The answer is same as your previous question. Nobody ever said source-address is a solution to geoblocking. You are the one who claimed so...

**Comment by MimuraKyosuke** [comment]
Thank you for your reply.
I don't understand why Japan-only videos can't be downloaded from Japan.

**Comment by pukkandan** [comment]
Are you able to view the video in browser without login, and from same IP?

**Comment by MimuraKyosuke** [comment]
yt-dlp is running on Linux server in Japan.
I can watch this video from my PC in Japan without logging in.
I can not tried with the same IP.
However, I confirmed that the IP of the server is from Japan.

**Comment by Lesmiscore** [comment]
It can indeed be played from Japan
![image](https://user-images.githubusercontent.com/10355528/185759476-1874aeab-580d-46f6-9b3f-089df5d3b3c4.png)

> However, I confirmed that the IP of the server is from Japan.

The easiest way to confirm what country YouTube is detecting, is to open [youtube.com](https://www.youtube.com/) via your server and look at left-top corner
![image](https://user-images.githubusercontent.com/10355528/185759537-dd51a2bb-16e2-499c-9c09-cde22d33f12b.png)

If it shows JP it's JP. Like the above example, if there's nothing, that IP is assumed to be from somewhere different

**Comment by MimuraKyosuke** [comment]
Thank you for your reply.
I will try it tomorrow.

**Comment by MimuraKyosuke** [comment]
My Linux server is a VPS.
I couldn't check that with the "lynx" or "curl" commands.
Do I need a proxy server setting on my linux server to check that?

**Comment by MimuraKyosuke** [comment]
When I built a proxy on my server and checked it via the server, I couldn't see this video.
I don't know why.
This server is located in Tokyo, Japan.

**Comment by pukkandan** [comment]
You'll have to ask youtube then...

**Comment by MimuraKyosuke** [comment]
Ok.
Thank you everyone.
