### ISSUE TITLE
Request for Channel 4 (UK)

### ISSUE THREAD

**Issue by 3guesses** [yt-dlp/yt-dlp#4718]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.08.19** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

UK

### Example URLs

https://www.channel4.com/programmes/channel-4-news/on-demand/73703-231
https://www.channel4.com/programmes/8-out-of-10-cats-does-countdown/on-demand/60792-001

### Provide a description that is worded well enough to be understood

The videos on this site are free to view once you have registered an account and signed in.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
Synaptic Package Manager reports that I have version 2022.05.19 installed (the latest available to me on antiX 21 Linux), so I am unsure why that is not what is reported in this output:

$ yt-dlp -vU
[debug] Command-line config: ['-vU']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2021.12.27 [6223f67a8]
[debug] Python version 3.9.2 (CPython 64bit) - Linux-5.10.57-antix.1-amd64-smp-x86_64-with-glibc2.31
[debug] exe versions: ffmpeg 4.3.4-0, ffprobe 4.3.4-0, rtmpdump 2.4
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
Usage: yt-dlp [OPTIONS] URL [URL...]

yt-dlp: error: yt-dlp's self-update mechanism is disabled on Debian.
Please update yt-dlp using apt(8).
See https://packages.debian.org/sid/yt-dlp for the latest packaged version.
```

**Comment by pukkandan** [comment]
> Synaptic Package Manager reports that I have version 2022.05.19 installed (the latest available to me on antiX 21 Linux), so I am unsure why that is not what is reported in this output:

You will have to ask the apt maintainers

**Comment by pukkandan** [comment]
> ![image](https://user-images.githubusercontent.com/6623388/185757700-b631ae14-e713-4c80-a629-b403f2890e71.png)


Did you really? 
![image](https://user-images.githubusercontent.com/6623388/185757670-5a97d220-e7e8-4cc4-b06e-35ceeab40f51.png)

**Comment by 3guesses** [comment]
> 



> > ![image](https://user-images.githubusercontent.com/6623388/185757700-b631ae14-e713-4c80-a629-b403f2890e71.png)
> 
> Did you really?

Yes, I did.  This is the first time I have tried making a request on github so admittedly I might not have known how to use it correctly, but I did do a search for Channel 4 and nothing came up.  I can only apologise if I did not search correctly.

Disappointing to learn that Channel 4 won't be supported 8-(
