### ISSUE TITLE
HOTSTAR [Broken]

### ISSUE THREAD

**Issue by sunilroy007** [yt-dlp/yt-dlp#472]
your download has been stopped due to: ERROR: Unable to download JSON metadata: HTTP Error 403: Forbidden (caused by  HTTPError 403: 'Forbidden' ); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.

hi hotstar videos are not downloading showing this error on free videos too

**Comment by pukkandan** [comment]
### IGNORING THE ISSUE TEMPLATE WILL RESULT IN ISSUE CLOSED AS INCOMPLETE

Create a new issue using the correct template with all necessary information including the `--verbose` output
