### ISSUE TITLE
Rather than downloading the video file in the backend, make it right away available on the client, so it can be downloaded. Is there a way?

### ISSUE THREAD

**Issue by thebeautyofcoding** [yt-dlp/yt-dlp#4721]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.08.19** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I can easily download a video file on my backend with yt-dlp, but can I send this file to my frontend without storing it on the backend, and make it downloadable there?
I want to build a website where user can provide an Instagram Url for downloading a specific video(post video, IGTV, Reel)

In Python and Flask, I was trying to use send_file() and send the file as "attachment" without success:

`
class DownloadReel(Resource):
    def post(self):
        ydl_opts = {"cookiesfrombrowser": ("chrome",)
         }
        url=parser.parse_args()['url']
        with yt_dlp.YoutubeDL(ydl_opts) as ydl:
            info = ydl.extract_info(url, download=True)
            print(info)           
            resp = make_response(info)
            resp.headers['Content-Type'] = 'video/mp4'
            
            resp.headers['Access-Control-Allow-Origin'] = '*'
            resp.headers['Content-Disposition'] = 'attachment;filename=SmartFileName.mp4'
            return send_file('Video by joeel56 [ChRtyT4jZTe].mp4', as_attachment=True, download_name="Video by joeel56 [ChRtyT4jZTe].mp4", mimetype="video/mp4")
`

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8 
[debug] yt-dlp version 2022.08.19 [48c88e0] (win32_exe) 
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0  
[debug] Checking exe version: ffmpeg -bsfs 
[debug] Checking exe version: ffprobe -bsfs 
[debug] exe versions: ffmpeg N-104465-g08a501946f-20211104 (setts), ffprobe N-104465-g08a501946f-20211104 
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3 
[debug] Proxy map: {} 
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest 
Latest version: 2022.08.19, Current version: 2022.08.19 
yt-dlp is up to date (2022.08.19)
```

**Comment by pukkandan** [comment]
Set `download=False`. The URL and headers needed are inside `info`

**Comment by thebeautyofcoding** [comment]
> Set `download=False`. The URL and headers needed are inside `info`

Thanks for the quick response. How do I exactly do it? I cannot use send_file(), when `download=False`, or?
Inside Info, I have this URL 
`https://scontent.cdninstagram.com/v/t50.2886-16/298477798_857908958506951_505799610353965839_n.mp4?efg=eyJ2ZW5jb2RlX3RhZyI6InZ0c192b2RfdXJsZ2VuLjEwODAuY2xpcHMuaGlnaCIsInFlX2dyb3VwcyI6IltcImlnX3dlYl9kZWxpdmVyeV92dHNfb3RmXCJdIn0&_nc_ht=instagram.fdtm2-2.fna.fbcdn.net&_nc_cat=107&_nc_ohc=dg18MfQYQxMAX9WRVF6&edm=ALQROFkBAAAA&vs=1255148741920730_3330023827&_nc_vs=HBksFQAYJEdPWm95aEhIcjdoX1F3d0RBQS1icmRZUTlnUUhicV9FQUFBRhUAAsgBABUAGCRHQTZkeVJHTnl3dUVsTDBBQUsyRE95d1F5X1ZZYnFfRUFBQUYVAgLIAQAoABgAGwAVAAAmkvaNx7nAwD8VAigCQzMsF0AmiDEm6XjVGBJkYXNoX2hpZ2hfMTA4MHBfdjERAHX%2BBwA%3D&_nc_rid=89069004cc&ccb=7-5&oe=6303C13C&oh=00_AT9hKsIdOqcFXJ0V-ly5WNxERTOg6fzMJx-BBavu00czJw&_nc_sid=30a2ef`
I can click with right mouse button and save it ond my machine, but I want to see it automatically downloading.

**Comment by pukkandan** [comment]
> How do I exactly do it? I cannot use send_file()

And how is that question related to yt-dlp?
