### ISSUE TITLE
ERROR: [FranceTVSite] 1289293-la-terre-vue-de-l-espace: Unable to extract video ID

### ISSUE THREAD

**Issue by ordilibre** [yt-dlp/yt-dlp#4730]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.08.19** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

fFrance

### Provide a description that is worded well enough to be understood

$ yt-dlp https://www.france.tv/france-2/la-terre-vue-de-l-espace/la-terre-vue-de-l-espace-saison-1/1289293-la-terre-vue-de-l-espace.html
[FranceTVSite] 1289293-la-terre-vue-de-l-espace: Downloading webpage
ERROR: [FranceTVSite] 1289293-la-terre-vue-de-l-espace: Unable to extract video ID; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

$ yt-dlp -U
Latest version: 2022.08.19, Current version: 2022.08.19
yt-dlp is up to date (2022.08.19)

Same URL play well in Firefox 103.0
https://www.france.tv/france-2/la-terre-vue-de-l-espace/la-terre-vue-de-l-espace-saison-1/1289293-la-terre-vue-de-l-espace.html

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
$ yt-dlp -vU https://www.france.tv/france-2/la-terre-vue-de-l-espace/la-terre-vue-de-l-espace-saison-1/1289293-la-terre-vue-de-l-espace.html
[debug] Command-line config: ['-vU', 'https://www.france.tv/france-2/la-terre-vue-de-l-espace/la-terre-vue-de-l-espace-saison-1/1289293-la-terre-vue-de-l-espace.html']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.08.19 [48c88e088]
[debug] Lazy loading extractors is disabled
[debug] Python 3.8.10 (CPython 64bit) - Linux-5.4.0-124-generic-x86_64-with-glibc2.29 (glibc 2.31)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.2.7, ffprobe 4.2.7, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, pyxattr-0.6.1, secretstorage-2.3.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.08.19, Current version: 2022.08.19
yt-dlp is up to date (2022.08.19)
[debug] [FranceTVSite] Extracting URL: https://www.france.tv/france-2/la-terre-vue-de-l-espace/la-terre-vue-de-l-espace-saison-1/1289293-la-terre-vue-de-l-espace.html
[FranceTVSite] 1289293-la-terre-vue-de-l-espace: Downloading webpage
ERROR: [FranceTVSite] 1289293-la-terre-vue-de-l-espace: Unable to extract video ID; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/home/christophe/.local/lib/python3.8/site-packages/yt_dlp/extractor/common.py", line 666, in extract
    ie_result = self._real_extract(url)
  File "/home/christophe/.local/lib/python3.8/site-packages/yt_dlp/extractor/francetv.py", line 292, in _real_extract
    video_id, catalogue = self._html_search_regex(
  File "/home/christophe/.local/lib/python3.8/site-packages/yt_dlp/extractor/common.py", line 1254, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/home/christophe/.local/lib/python3.8/site-packages/yt_dlp/extractor/common.py", line 1218, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
```

**Comment by elyse0** [comment]
Can you post a picture that it works in the browser?

![image](https://user-images.githubusercontent.com/26639800/185827022-6a26e5f0-f2f4-4e51-8643-f2034c3692f2.png)

**Comment by ordilibre** [comment]
Hi,
Today, after your message, I try to continue to show the video online (I begin to show yesterday), and it works.

> $ uptime
>  09:30:16 up 2 days, 19:44,  1 user,  load average: 0,75, 1,39, 0,93
> $ date
> lun. 22 août 2022 09:31:04 CEST

![Capture d’écran_2022-08-22_09-28-34](https://user-images.githubusercontent.com/2906290/185865511-dd934097-adc7-48a3-9a62-5486c0d12370.png)

But, after refreshing the page, I see the same message as you (and I cannot see the end now... sad)

**Comment by elyse0** [comment]
As the video is not available, can you close this issue?
