### ISSUE TITLE
Doesn't download all videos from a URL

### ISSUE THREAD

**Issue by yurivict** [yt-dlp/yt-dlp#4731]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.08.19** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

This [URL](https://www.youtube.com/watch?v=bL263_P4dEc&ab_channel=%E5%8A%89%E6%96%87%E6%AD%A3%E6%B0%B8%E6%81%92%E4%B9%8B%E6%98%9F%E5%8A%89%E6%96%87%E6%AD%A3StevenLiu) contains the ```ab_channel``` tag and in a browser plays a pre-defined sequence of videos.

yt-dlp only downloads one video and exits.

I think when the URL represents a sequence yt-dlp should at least ask the user would he like to download one video or all videos from a sequence.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
$ yt-dlp -vU "https://www.youtube.com/watch?v=bL263_P4dEc&ab_channel=%E5%8A%89%E6%96%87%E6%AD%A3%E6%B0%B8%E6%81%92%E4%B9%8B%E6%98%9F%E5%8A%89%E6%96%87%E6%AD%A3StevenLiu"
[debug] Command-line config: ['-vU', 'https://www.youtube.com/watch?v=bL263_P4dEc&ab_channel=%E5%8A%89%E6%96%87%E6%AD%A3%E6%B0%B8%E6%81%92%E4%B9%8B%E6%98%9F%E5%8A%89%E6%96%87%E6%AD%A3StevenLiu']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.08.19 [48c88e088]
[debug] Python 3.9.13 (CPython 64bit) - FreeBSD-13.1-STABLE-amd64-64bit-ELF (libc 7)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.12.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.08.19, Current version: 2022.08.19
yt-dlp is up to date (2022.08.19)
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=bL263_P4dEc&ab_channel=%E5%8A%89%E6%96%87%E6%AD%A3%E6%B0%B8%E6%81%92%E4%B9%8B%E6%98%9F%E5%8A%89%E6%96%87%E6%AD%A3StevenLiu
[youtube] bL263_P4dEc: Downloading webpage
[youtube] bL263_P4dEc: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] bL263_P4dEc: Downloading 1 format(s): 243+251
[download] 劉文正 【星星和花朵】沒有收錄在專輯的一首歌曲，串插在電影【愛情。文憑。牛仔褲】 [bL263_P4dEc].webm has already been downloaded
```
```

**Comment by coletdjnz** [comment]
> This [URL](https://www.youtube.com/watch?v=bL263_P4dEc&ab_channel=%E5%8A%89%E6%96%87%E6%AD%A3%E6%B0%B8%E6%81%92%E4%B9%8B%E6%98%9F%E5%8A%89%E6%96%87%E6%AD%A3StevenLiu) contains the ab_channel tag and in a browser plays a pre-defined sequence of videos.

I don't see this?

Even YouTube's own url-resolver API says it treats it like a normal video :confused: 

Can you share a screenshot or something of it showing this list of videos
