### ISSUE TITLE
[Site Request] hdrezka

### ISSUE THREAD

**Issue by DHYTFG** [yt-dlp/yt-dlp#4732]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.08.19** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Example URLs

https://hdrezka.ag/series/thriller/646-vo-vse-tyazhkie-2008.html#t:56-s:1-e:1

### Provide a description that is worded well enough to be understood

I can't give recommendations on this issue

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['с', '-vU', 'https://hdrezka.ag/series/thriller/646-vo-vse-tyazhkie-2008.html#t:56-s:1-e:1']
[debug] Encodings: locale cp1251, fs utf-8, pref cp1251, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.08.19 [48c88e0] (win32_exe)
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg N-107846-g0154fb43e3-20220821 (setts), ffprobe N-107846-g0154fb43e3-20220821
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.08.19, Current version: 2022.08.19
yt-dlp is up to date (2022.08.19)
[debug] [generic] Extracting URL: с
ERROR: [generic] 'с' is not a valid URL. Set --default-search "ytsearch" (or run  yt-dlp "ytsearch:с" ) to search YouTube
  File "yt_dlp\extractor\common.py", line 666, in extract
  File "yt_dlp\extractor\generic.py", line 2615, in _real_extract

[debug] [generic] Extracting URL: https://hdrezka.ag/series/thriller/646-vo-vse-tyazhkie-2008.html#t:56-s:1-e:1
[generic] 646-vo-vse-tyazhkie-2008: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] 646-vo-vse-tyazhkie-2008: Extracting information
[debug] Looking for Brightcove embeds
[debug] Looking for embeds
[debug] Identified a Open Graph video info
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 646-vo-vse-tyazhkie-2008: Downloading 1 format(s): 0
[debug] Invoking http downloader on "https://hdrezka.ag/series/thriller/646-vo-vse-tyazhkie-2008.html"
[download] Во все тяжкие (2008) [646-vo-vse-tyazhkie-2008].html has already been downloaded
[download] 100% of 147.75KiB
```

**Comment by sqrtNOT** [comment]
https://hdrezka.ag/collections/ Pirate site with content from netflix, paramount+, hulu, etc.
