### ISSUE TITLE
is there any option to use Configuration: `yt-dlp.conf` in temp

### ISSUE THREAD

**Issue by candrapersada** [yt-dlp/yt-dlp#4733]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.08.19** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

is there any option to use Configuration: `yt-dlp.conf` other than in the home path. like temp path?

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
`--config-location`

**Comment by candrapersada** [comment]
use temp path like `-P "temp:tmp"` without use `--config-location`

**Comment by pukkandan** [comment]
So?

**Comment by candrapersada** [comment]
like
![image](https://user-images.githubusercontent.com/36833664/185820625-962914da-4511-463e-bf69-1717a81204e0.png)
but use  `-P "temp:tmp"`

**Comment by pukkandan** [comment]
Use `-P temp:tmp --config-location tmp`. Not sure what your issue is

If you are asking to make that the default, it won't be done
