### ISSUE TITLE
why is `m4a` higher then `mp3` in format sorting when using `--prefer-free-formats`

### ISSUE THREAD

**Issue by MrRawes** [yt-dlp/yt-dlp#4735]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.08.19** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

the reason i bring this up is because [`mp3`'s patents expired in 2017](https://www.loc.gov/preservation/digital/formats/fdd/fdd000012.shtml)

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
Why shouldn't it be?

**Comment by MrRawes** [comment]
> Why shouldn't it be?

because m4a is not a free format (since it is a subset of mp4), `mp3` is a free format since 2017.
shouldn't mp3 be higher in format sorting when using `--prefer-free-formats` then

**Comment by pukkandan** [comment]
Ok, makes sense. This order was set long before the mp3 patents expired. But why is this a `question` and not a bug report? Give me an example URL where both formats are available

**Comment by pukkandan** [comment]
Actually, since this is a change that breaks compatibility, I suggest you request this in youtube-dl too

**Comment by MrRawes** [comment]
actually the description of the `--prefer-free-formats` option is inaccurate, since it says "Prefer video formats with free containers
                                over non-free ones of same quality." despite it working with audio

**Comment by gamer191** [comment]
On a side note, why, according to the readme, is Ogg preferred over Opus, unless `--prefer-free-formats` is passed? 

Also, while it's no longer an issue, why is aac preferred over mp3 unless `--prefer-free-formats` is passed?

**Comment by pukkandan** [comment]
The ordering b/w formats that are generally never encountered together is probably not implemented correctly. Instead of asking me why, tell me how you think it should be instead - with justifications

**Comment by gamer191** [comment]
> Actually, since this is a change that breaks compatibility, I suggest you request this in youtube-dl too

ping @dirkf

**Comment by dirkf** [comment]
Ping received and my thumbs support the two comments here regarding clarification of the desired functionality.

**Comment by dirkf** [comment]
The historic options in yt-dl and yt-dlp aren't necessarily well chosen. Eg `--recode-video` should have been `--remux-video`. Similarly, despite the fact that `format` is generally used throughout to describe a combination of video and/or audio codec parameters in a specific container type, we have `--prefer-free-formats` instead of `--prefer-free-container-formats` or similar

**Comment by dirkf** [comment]
> No, ytdl's --recode-video does re-encode the video, not just remux it. 

Yes, sorry for that misinformation.

Inquiring minds may like to know that _ffmpeg_ doesn't default to just copying the streams: rather, it associates a default video and audio encoder with each container type and transcodes each stream with that encoder, unless overridden, and even if the source stream actually has a compatible encoding. Contrary to my assumption, yt-dl doesn't use -c copy in the `--recode-video` option.

This behaviour is handy, improving the likelihood of a valid playable output file, unless (a) transcoding is not required but you lose a generation anyway (b) the platform is poorly matched to the transcoding task.
