### ISSUE TITLE
[Broken] Wrong timestamps on WebVTT parsed subtitles

### ISSUE THREAD

**Issue by MinePlayersPE** [yt-dlp/yt-dlp#474]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running yt-dlp version **2021.07.07**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
[debug] Command-line config: ['--write-subs', '--skip-download', '-v', 'https://devstreaming-cdn.apple.com/videos/streaming/examples/img_bipbop_adv_example_ts/master.m3u8']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] yt-dlp version 2021.07.07 (exe)
[debug] Plugin Extractors: ['SamplePlugin']
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] exe versions: ffmpeg 2021-06-09-git-e01bf559df-full_build-www.gyan.dev, ffprobe 2021-06-09-git-e01bf559df-full_build-www.gyan.dev
[debug] Proxy map: {}
[debug] [generic] Extracting URL: https://devstreaming-cdn.apple.com/videos/streaming/examples/img_bipbop_adv_example_ts/master.m3u8
[generic] master: Requesting header
[generic] master: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Downloading subtitles: en
[debug] Default format spec: bestvideo*+bestaudio/best
[info] master: Downloading 1 format(s): 8366+aud3-English
[info] Writing video subtitles to: master [master].en.vtt
[debug] Invoking downloader on "https://devstreaming-cdn.apple.com/videos/streaming/examples/img_bipbop_adv_example_ts/s1/en/prog_index.m3u8"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 100
[download] Destination: master [master].en.vtt
[download] 100% of 29.83KiB in 02:02
```

## Description

Parsed WebVTT subtitles have the wrong timestamps.
Expected (not parsed):
```
WEBVTT
X-TIMESTAMP-MAP=MPEGTS:900000,LOCAL:00:00:00.000

1
00:00:00.008 --> 00:00:00.992
Subtitles: Bip!

2
00:00:01.000 --> 00:00:01.992
Subtitles: Bop!

3
00:00:02.000 --> 00:00:02.992
Subtitles: Bip!

4
00:00:03.000 --> 00:00:03.992
Subtitles: Bop!

...
```
Got:
```
WEBVTT
X-TIMESTAMP-MAP=LOCAL:00:00:00.000,MPEGTS:900000

1
08:00:00.000 --> 32:00:16.000
Subtitles: Bip!

2
00:00:00.001 --> 32:00:16.001
Subtitles: Bop!

3
00:00:00.002 --> 32:00:16.002
Subtitles: Bip!

4
00:00:00.003 --> 32:00:16.003
Subtitles: Bop!

...
```
Also observed in:
https://www.vidio.com/watch/2234540-stand-by-me-doraemon-2 (geolocked and paywalled, verified by me)
https://roosterteeth.com/watch/gen-lock-season-1-1 (semi-geolocked, verified by XMarksTheSpot (discord), @nao20010128nao, and me)

**Comment by nao20010128nao** [comment]
> roosterteeth.com/watch/gen-lock-season-1-1 (geolocked(?), verified by XMarksTheSpot (discord), @nao20010128nao, and me)

absolutely get-restricted. atleast not accessible from Japan

**Comment by MinePlayersPE** [comment]
Note: This might be an external issue (as per my testing, this issue persisted even before the version that I had successfully tested subtitles on)

**Comment by fstirlitz** [comment]
Confirmed. And I even know where it is:

https://github.com/yt-dlp/yt-dlp/blob/73d829c144601c105f7ee1a3d8f2aed6d8e1b76d/yt_dlp/webvtt.py#L125-L127

The variables on the LHS should be swapped.

**Comment by MinePlayersPE** [comment]
@pukkandan I'm pretty sure you meant to close this issue for [`71543db`](https://github.com/yt-dlp/yt-dlp/commit/71543db7b31f9148f4d06d120245bd0ffad7f1a3)?

**Comment by pukkandan** [comment]
@MinePlayersPE thanks
