### ISSUE TITLE
facebook download suddenly fails for most links (Cannot parse data)

### ISSUE THREAD

**Issue by jheled** [yt-dlp/yt-dlp#4747]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.08.19** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

New Zealand 

### Provide a description that is worded well enough to be understood

facebook download suddenly fails for most links.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['--extract-audio', '--audio-format', 'mp3', '-vU', 'https://fb.watch/f3AjvZ85ZP/']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out UTF-8, error UTF-8, screen UTF-8
[debug] yt-dlp version 2022.08.19 [48c88e0] (zip)
[debug] Python 3.7.3 (CPython 64bit) - Linux-5.0.0-38-generic-x86_64-with-Ubuntu-19.04-disco (glibc 2.29)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.1.3, ffprobe 4.1.3
[debug] Optional libraries: certifi-2018.08.24, pycrypto-2.6.1, secretstorage-2.3.1, sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.08.19, Current version: 2022.08.19
yt-dlp is up to date (2022.08.19)
[debug] [generic] Extracting URL: https://fb.watch/f3AjvZ85ZP/
[generic] f3AjvZ85ZP: Downloading webpage
[redirect] Following redirect to https://www.facebook.com/watch/?v=2367903466782229&ref=sharing
[debug] [facebook] Extracting URL: https://www.facebook.com/watch/?v=2367903466782229&ref=sharing
[facebook] 2367903466782229: Downloading webpage
[facebook] 2367903466782229: Downloading webpage
ERROR: [facebook] 2367903466782229: Cannot parse data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/home/joseph/bin/yt-dlp/yt_dlp/extractor/common.py", line 666, in extract
    ie_result = self._real_extract(url)
  File "/home/joseph/bin/yt-dlp/yt_dlp/extractor/facebook.py", line 705, in _real_extract
    return self._extract_from_url(real_url, video_id)
  File "/home/joseph/bin/yt-dlp/yt_dlp/extractor/facebook.py", line 651, in _extract_from_url
    raise ExtractorError('Cannot parse data')
```

**Comment by pukkandan** [comment]
See pinned issue

**Comment by technix64** [comment]
I also have the issue, I am currently running version: 2022.09.01

After running yt-dlp -vU, I get the following output:

[debug] Command-line config: ['-vU']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.09.01 [5d7c7d6] (zip)
[debug] Python 3.10.4 (CPython 64bit) - Linux-5.15.0-47-generic-x86_64-with-glibc2.35 (glibc 2.35)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 5.0.1 (fdk,setts), ffprobe 5.0.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2020.06.20, mutagen-1.45.1, pyxattr-0.7.2, secretstorage-3.3.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1670 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.09.01, Current version: 2022.09.01
yt-dlp is up to date (2022.09.01)

The way I download a video from facebook is with a shell script, with the following inside:

#!/bin/bash
yt-dlp --format mp4                            \
       --audio-quality 0                       \
       --force-ipv4                            \
       --prefer-ffmpeg                         \
       --ffmpeg-location /usr/bin              \
       --ignore-errors                         \
       --socket-timeout 300                    \
       --retries 10                            \
       --add-header 'cookie: sb=9tdVYq1e2SO7EyIByPhHaaZk; datr=9tdVYh8FtIhzi3vGUz9yJSMD; locale=en_US; c_user=100010836366088; xs=34%3AbpDuezu_xa-zgA%3A2%3A1659916188%3A-1%3A11896%3A%3AAcWwlkdLPNTsjW49fimZZVWbChURcjq5CWj3u5SjeQ; fr=0MGOkQ6g4Dz1Oek5e.AWUg1FOZAH6sYMWFq4g7pzhgPhc.Bi8Gwh.v5.AAA.0.0.Bi8HP-.AWXHRywM334; presence=C%7B%22t3%22%3A%5B%5D%2C%22utc3%22%3A1659925513440%2C%22v%22%3A1%7D' \
       --output '/home/lamer86/Desktop/%(title)s.%(ext)s' "$1"

I just tried to download a video and got the following output:

[facebook] 1074854833175626: Downloading webpage
[facebook] 1074854833175626: Downloading webpage
ERROR: [facebook] 1074854833175626: Cannot parse data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
