### ISSUE TITLE
Get browser downloadable link

### ISSUE THREAD

**Issue by Deshdeepak1** [yt-dlp/yt-dlp#4756]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.08.19** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

yt-dlp -g doex give the direct link . But opening that link in browser for almost any service ( youtube, instagram, facebook ) results in the video being played. 
While sites like https://youtubemultidownloader.org/, https://igram.io/  provides link that after opening starts downloading. 
How to get these type of url instead?

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by SuperSonicHub1** [comment]
You can save a video or audio file being played in your browser by right-clicking on it and selecting 'Save As...'. The reason those links from the sites you mentioned work that way is because they set the [`Content-Disposition` header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Disposition) serverside; yt-dlp can't just "give" you a link that does that. Finally, if you ultimately plan to download a video, why not just use yt-dlp instead of your browser?

**Comment by Deshdeepak1** [comment]
Those websites also provide similar (official website links) , how are they able to set content disposition header for those links? Same can't be done?

The reason I want  those type link and not ise yt-dlp, is because I wan't to create a website with somewhat similar feature.

**Comment by SuperSonicHub1** [comment]
Yeah, `Content-Disposition`'s an HTTP server thing and yt-dlp is just a client. If you really want it to work that way, you could just download the video on the server and then send it in a HTTP response to your user with the header. You may also want to consider using [the `download` attribute of the anchor tag](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#attr-download).

**Comment by Deshdeepak1** [comment]
Yeah, but those websites are able to do it without downloading them first. I don't have that much bandwidth also. 
Also have tried download option multiple times doesn't work.

**Comment by dirkf** [comment]
The `download` attribute of the anchor tag only applies if the link has the same scheme://host:port as the page itself. So you have to proxy the link in your webserver.

**Comment by pukkandan** [comment]
Your question is unrelated to yt-dlp, and is a general webdev/youtube API question. This is not the appropriate place to ask such questions!

That said, the solution you want is to add a `title` query parameter to the URL generated

**Comment by Deshdeepak1** [comment]
> Your question is unrelated to yt-dlp, and is a general webdev/youtube API question. This is not the appropriate place to ask such questions!

It is related because if those websites can obtain and provide such urls, then so can yt-dlp which I think would be better for those who want to use on websites.

> That said, the solution you want is to add a `title` query parameter to the URL generated
It doesn't work checked many times.
yt-dlp -gf 18 "https://www.youtube.com/watch?v=_andnIwLKDk" 
https://rr1---sn-gwpa-o5by.googlevideo.com/videoplayback?expire=1661713443&ei=w2cLY-LdE_OW1d8Pl9GNKA&ip=49.38.186.63&id=o-AD5T1TDvBHa6YTzDFRN4-4-QJpTcjMtC1oQaykgO-hlI&itag=18&source=youtube&requiressl=yes&mh=bk&mm=31%2C29&mn=sn-gwpa-o5by%2Csn-gwpa-h55z&ms=au%2Crdu&mv=m&mvi=1&pl=20&initcwndbps=205000&spc=lT-Khs2m1rEwrDVlCCeNDsW6GyUm6uM&vprv=1&svpuc=1&mime=video%2Fmp4&gir=yes&clen=2725758&ratebypass=yes&dur=45.023&lmt=1654989243857745&mt=1661691192&fvip=6&fexp=24001373%2C24007246&c=ANDROID&rbqsm=fr&txp=4438434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRgIhAOQPsXhIWQdYN6rG6O1xTmxIj0fZhWEm0PLb4u6SsEEFAiEAuLDWHsLZZvR9x5cgk7v07-ytMKcG5Y33xOVDhVWIkwk%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhAPFIo0rNAlTSCm8km7X8hrUeQSETcbBQfjBuGzNsPYzqAiAN7Hob-9ENl4oD8Bn1enSfoFaDKX6vELtaqAEWc2zoVw%3D%3D&title=abc.mp4

**Comment by pukkandan** [comment]
Interesting - it works for BaW_jenozKc, but not with your example 🤔

**Comment by pukkandan** [comment]
This appear to work with only `-f22`

**Comment by Deshdeepak1** [comment]
Somehow working with -f 22 ? why so ? Why not with 18?

**Comment by pukkandan** [comment]
Ask youtube 🤷 

The same behavior is observed in the other downloaders you mentioned in OP

**Comment by Deshdeepak1** [comment]
Thank you are correct

**Comment by f-i-t-s-u-m** [comment]
am wonder if anyone have solution for this issue, seems other websites achieve this
