### ISSUE TITLE
[Feature Request] - Verify Duration of Downloaded File, Loop until Duration Matches

### ISSUE THREAD

**Issue by timethrow** [yt-dlp/yt-dlp#476]
## Checklist

- [X] I'm reporting a feature request
- [X] I've verified that I'm running yt-dlp version **2021.07.07**
- [X] I've searched the bugtracker for similar feature requests including closed ones

## Description

Sometimes when downloading videos, in particular with the Native HLS Downloader, there is some kind of corruption, where the duration does not match, typically one of the audio or video tracks is slightly longer or shorter than the actual duration and causes issues during playback. A good example of this is with the Paramount Plus (CBS) Extractor.

Generally if you download the video again (sometimes a couple of times), most of the time this sorts the issue out (thus showing the source video is correct), and the video and audio play as expected, and the duration of the video is correct.

Its quite hard to replicate on demand, but if you download a few videos, you will probably stumble on one like that.

As a way to workaround it, I was wondering if an option could be added, where yt-dlp verifies the length of the downloaded video against the expected duration of the video (from the Extractor), I know not all extractors capture this, so it would have to be an optional argument e.g. `--verify-duration` and would only work where a duration is captured and is not `None` or `0`. If there was a mismatch in the duration, the video is not added to the archive (if used) and the original file on disk is deleted and a new download starts, looping until the duration matches, or a specified number of attempts is exceeded.

Hope that all makes sense, any questions, please do let me know.

**Comment by pukkandan** [comment]
> Sometimes when downloading videos, in particular with the Native HLS Downloader, there is some kind of corruption, where the duration does not match, typically one of the audio or video tracks is slightly longer or shorter than the actual duration and causes issues during playback. A good example of this is with the Paramount Plus (CBS) Extractor.

This is not supposed to happen. Open an issue with the verbose log when you encounter the issue next time

---

As for the "workaround", it will not be added
