### ISSUE TITLE
alias: TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by ultrasound1372** [yt-dlp/yt-dlp#4760]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.08.19** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Within my config files I define a few useful aliases to make commands easier to write, especially when I have to do the same thing for multiple channels or playlists but the options differ just enough to need a separate command. At some point recently all such usage began immediately giving the titular type error. As far as I can tell these errors do not occur if I don't invoke any aliases, so the issue isn't with defining but with using them. I was able to make my build work again by branching at 13db4e7b9 and then reverting 822d66e59, but I'm not familiar enough with the code to submit a PR that works on the latest tip, as I didn't trust myself to branch at or after 5314b5219 and still revert due to the ordered set changes and the way they changed how the alias callback is handled. I can confirm though that simply branching but not reverting still leaves me with a build that does this. For consistency with ongoing work I've simply pulled down the tip of master (164b03c48 as I write this) and confirmed that this bug is still present. Based on peaking at the code that gives the error I can only infer that somehow `setattr` and `getattr` aren't properly working together, but without more knowledge of the internals of how these options are handled I wouldn't know how to go about fixing it. The only thing I can think of is that the options object is somehow being mutated before the callback receives it, or that the method of forcing an int to be there is failing somehow. I apologize for not being more help, and sincerely hope it's something relatively trivial that can be fixed quickly.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
$ yt-dlp -vU -i -E --download-archive ncs_youtube.dat -f bestaudio -x --audio-format vorbis --audio-quality 160k -o "no copyright sounds/%%(title)s.%%(ext)s" https://www.youtube.com/user/NoCopyrightSounds/videos 2>&1 | clip
[debug] Command-line config: ['-vU', '-i', '-E', '--download-archive', 'ncs_youtube.dat', '-f', 'bestaudio', '-x', '--audio-format', 'vorbis', '--audio-quality', '160k', '-o', 'no copyright sounds/%%(title)s.%%(ext)s', 'https://www.youtube.com/user/NoCopyrightSounds/videos']
[debug] User config "C:\Users\Colton\yt-dlp.conf": ['--downloader', 'aria2c', '--downloader-args', 'aria2c:-j 8 -s 8 -x 8', '-N', '16', '--abort-on-unavailable-fragment', '-P', 'temp:C:\\RAM\\Temp\\yt-dlp', '--no-colors', '--windows-filenames', '--alias', 'reprobe,-E', '--break-on-existing --break-per-input --lazy-playlist', '--alias', 'not-live', '--match-filter "live_status!=\'is_live\' & live_status!=\'is_upcoming\' & live_status!=\'post_live\'"']
Traceback (most recent call last):
  File "C:\Users\Colton\Documents\codestuff\yt-dlp\venv\Scripts\yt-dlp-script.py", line 33, in <module>
    sys.exit(load_entry_point('yt-dlp', 'console_scripts', 'yt-dlp')())
  File "c:\users\colton\documents\codestuff\yt-dlp\yt_dlp\__init__.py", line 954, in main
    _exit(*variadic(_real_main(argv)))
  File "c:\users\colton\documents\codestuff\yt-dlp\yt_dlp\__init__.py", line 900, in _real_main
    parser, opts, all_urls, ydl_opts = parse_options(argv)
  File "c:\users\colton\documents\codestuff\yt-dlp\yt_dlp\__init__.py", line 682, in parse_options
    parser, opts, urls = parseOpts(argv)
  File "c:\users\colton\documents\codestuff\yt-dlp\yt_dlp\options.py", line 121, in parseOpts
    root.configs[0].load_configs()  # Resolve any aliases using --config-location
  File "c:\users\colton\documents\codestuff\yt-dlp\yt_dlp\utils.py", line 5506, in load_configs
    opts, _ = self.parser.parse_known_args(self.own_args)
  File "c:\users\colton\documents\codestuff\yt-dlp\yt_dlp\options.py", line 195, in parse_known_args
    self._process_short_opts(self.rargs, self.values)
  File "C:\Python310\lib\optparse.py", line 1536, in _process_short_opts
    option.process(opt, value, values, self)
  File "C:\Python310\lib\optparse.py", line 784, in process
    return self.take_action(
  File "C:\Python310\lib\optparse.py", line 805, in take_action
    self.callback(self, opt, value, parser, *args, **kwargs)
  File "c:\users\colton\documents\codestuff\yt-dlp\yt_dlp\options.py", line 305, in _alias_callback
    counter[opt_str] += 1
TypeError: 'NoneType' object is not subscriptable
```
```

**Comment by dirkf** [comment]
`'--alias', 'not-live', '--match-filter "live_status!=\'is_live\'`

Presumably you want this to define an option alias `--not-live` that expands to `--match-filter "live_status!='is_live'"`

Apparently this is not being quoted properly (note the unmatched `"`), or the config that contains the definition is not being parsed properly. In the first case (since configs are parsed like command-line arguments), this may help:  https://ss64.com/nt/syntax-esc.html.

If the value is set in the extractor, the example `--match-filter !is_live` from the manual may be a way of avoiding the problem.

**Comment by ultrasound1372** [comment]
I was wondering about the quoting rules for those filters since I'm dealing with multiple levels of nesting here, but unless I'm seriously mistaken, the `--not-live` alias is unrelated to the issue. The reprobe one is the one I'm using as a test.

**Comment by dirkf** [comment]
The option-value pair `'--alias', 'reprobe,-E'` is valid. The group that I quoted isn't: it should be s/t like 
`'--alias', 'not-live,--match-filter "live_status!=\'is_live\'"'`

An alias value should be splittable at `,` but `not-live` on its own isn't. Presumably the `counter` is `None` because the expected attribute of `parser.values` was not set/could not be got.

Two sugggestions:
* try to create the minimal example that reproduces your problem
* run the program in the debugger to see what's actually happening.

**Comment by pukkandan** [comment]
@dirkf `--alias` consumes 2 arguments
