### ISSUE TITLE
[livenewsnow] 403 forbidden on m3u8 information

### ISSUE THREAD

**Issue by jpeeler** [yt-dlp/yt-dlp#4765]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.08.19** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United States

### Provide a description that is worded well enough to be understood

Livenewsnow site no longer is working, but it did in the past. I do not know if a 403 forbidden means that site is trying to prevent media downloading or if it's something in yt-dlp that needs fixing.

The version of yt-dlp in use is from [Macports](https://github.com/macports/macports-ports/blob/c933783ff49119298fd8727303b481d42fd0dca0/net/youtube-dl/Portfile#L41) using the [Github release](https://github.com/yt-dlp/yt-dlp/releases/download/2022.08.19/yt-dlp.tar.gz)

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
$ yt-dlp -vU "https://www.livenewsnow.com/american/cnbc.html"
[debug] Command-line config: ['-vU', 'https://www.livenewsnow.com/american/cnbc.html']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.08.19 [48c88e0]
[debug] Python 3.10.6 (CPython 64bit) - macOS-12.5.1-arm64-arm-64bit 
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2, rtmpdump 2.4
[debug] Optional libraries: Crypto-3.15.0, sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.08.19, Current version: 2022.08.19
yt-dlp is up to date (2022.08.19)
[debug] [generic] Extracting URL: https://www.livenewsnow.com/american/cnbc.html
[generic] cnbc: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] cnbc: Extracting information
[debug] Looking for Brightcove embeds
[debug] Looking for embeds
[generic] cnbc: Downloading m3u8 information
WARNING: [generic] Failed to download m3u8 information: HTTP Error 403: Forbidden
[debug] Identified a JW Player data
ERROR: [generic] cnbc: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1442, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1539, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1597, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 2515, in process_video_result
    self.raise_no_formats(info_dict)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1010, in raise_no_formats
    raise ExtractorError(msg, video_id=info['id'], ie=info['extractor'],
yt_dlp.utils.ExtractorError: [generic] cnbc: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```
```

**Comment by bashonly** [comment]
cable news channels for free? are you sure this site is legit?

**Comment by jpeeler** [comment]
No idea. I just assumed the error was either a regression or is something that would benefit parsing other websites as well.
