### ISSUE TITLE
`InfoExtractor._get_cookies` fails if values contain quotes

### ISSUE THREAD

**Issue by Grub4K** [yt-dlp/yt-dlp#4776]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.08.19** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

`InfoExtractor._get_cookies` uses `http.cookies.SimpleCookie` to process the cookies. Analogue to #4692 the parsing will fail fast instead of skipping the invalid values.

SimpleCookie allows values with quotes if set explicitly.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['--cookies-from-browser', 'firefox', '-j', 'https://beta.crunchyroll.com/de/watch/GG1U2Q50J/the-former-couple-refuses-to-say', '-vU']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8 
[debug] yt-dlp version 2022.08.19 [48c88e0] (pip) 
[debug] Python 3.10.5 (CPython 64bit) - Windows-10-10.0.22000-SP0  
[debug] Checking exe version: ffmpeg -bsfs 
[debug] Checking exe version: ffprobe -bsfs 
[debug] exe versions: ffmpeg n5.1-10-g6ee1996721-20220822 (setts), ffprobe n5.1-10-g6ee1996721-20220822 
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[Cookies] Extracting cookies from firefox
[debug] Extracting cookies from: "C:\Users\grub4k\AppData\Roaming\Mozilla\Firefox\Profiles\kbiex092.default-release\cookies.sqlite"
[Cookies] Extracted 790 cookies from firefox
[debug] Proxy map: {} 
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest 
Latest version: 2022.08.19, Current version: 2022.08.19 
yt-dlp is up to date (2022.08.19) 
[debug] [crunchyroll:beta] Extracting URL: https://beta.crunchyroll.com/de/watch/GG1U2Q50J/the-former-couple-refuses-to-say
[crunchyroll:beta] the-former-couple-refuses-to-say: Downloading webpage 
ERROR: GG1U2Q50J: An extractor error has occurred. (caused by KeyError('byId')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "C:\Users\grub4k\AppData\Local\pypoetry\Cache\virtualenvs\crunchyload-sk9Pq0JJ-py3.10\lib\site-packages\yt_dlp\extractor\common.py", line 666, in extract
    ie_result = self._real_extract(url)
  File "C:\Users\grub4k\AppData\Local\pypoetry\Cache\virtualenvs\crunchyload-sk9Pq0JJ-py3.10\lib\site-packages\yt_dlp\extractor\crunchyroll.py", line 805, in _real_extract
    return self._redirect_from_beta(url, lang, internal_id, display_id, True, CrunchyrollIE.ie_key())
  File "C:\Users\grub4k\AppData\Local\pypoetry\Cache\virtualenvs\crunchyload-sk9Pq0JJ-py3.10\lib\site-packages\yt_dlp\extractor\crunchyroll.py", line 752, in _redirect_from_beta
    content_data = initial_state['content']['byId'][internal_id]
KeyError: 'byId'
```

**Comment by tejing1** [comment]
To clarify, it's only related to later discussion in 4692, specifically https://github.com/yt-dlp/yt-dlp/issues/4692#issuecomment-1222455567 and onward.
Another instance: https://github.com/yt-dlp/yt-dlp/issues/3778
