### ISSUE TITLE
Initialization fragment found after media fragments, unable to download

### ISSUE THREAD

**Issue by madnesofjuice** [yt-dlp/yt-dlp#4777]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.08.19** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

I cannot download a specific audio from the m3u8. 
I tried with youtube-dl and its working, yt-dlp has a problem and i dont know why
Link: `https://vod-l3c-eu-east-2.media.dssott.com/ps01/disney/245691fe-e83f-417b-9c26-120de2482fc4/ctr-all-d6cbaddc-6ab6-44a3-b640-31917ecb6d37-f2f52c2f-4489-4f07-9a7b-bd80215ac033.m3u8?r=720&v=1&hash=0dd5c2945f832478f363944111678cf2f48cb254` (idk if it will work when you guys will try it)

`yt-dlp -f aac-128k-Română "https://vod-l3c-eu-east-2.media.dssott.com/ps01/disney/245691fe-e83f-417b-9c26-120de2482fc4/ctr-all-d6cbaddc-6ab6-44a3-b640-31917ecb6d37-f2f52c2f-4489-4f07-9a7b-bd80215ac033.m3u8?r=720&v=1&hash=0dd5c2945f832478f363944111678cf2f48cb254"
[generic] ctr-all-d6cbaddc-6ab6-44a3-b640-31917ecb6d37-f2f52c2f-4489-4f07-9a7b-bd80215ac033: Downloading webpage
[generic] ctr-all-d6cbaddc-6ab6-44a3-b640-31917ecb6d37-f2f52c2f-4489-4f07-9a7b-bd80215ac033: Downloading m3u8 information
[info] ctr-all-d6cbaddc-6ab6-44a3-b640-31917ecb6d37-f2f52c2f-4489-4f07-9a7b-bd80215ac033: Downloading 1 format(s): aac-128k-Română
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 416
[download] Destination: ctr-all-d6cbaddc-6ab6-44a3-b640-31917ecb6d37-f2f52c2f-4489-4f07-9a7b-bd80215ac033 [ctr-all-d6cbaddc-6ab6-44a3-b640-31917ecb6d37-f2f52c2f-4489-4f07-9a7b-bd80215ac033].mp4
ERROR: Initialization fragment found after media fragments, unable to download`

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
E:\Porno\Movies>yt-dlp -vU
[debug] Command-line config: ['-vU']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.08.19 [48c88e0] (win32_exe)
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 2022-01-10-git-f37e66b393-full_build-www.gyan.dev (setts), ffprobe 2022-01-10-git-f37e66b393-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.08.19, Current version: 2022.08.19
yt-dlp is up to date (2022.08.19)

E:\Porno\Movies>yt-dlp -f aac-128k-Română "https://vod-l3c-eu-east-2.media.dssott.com/ps01/disney/245691fe-e83f-417b-9c26-120de2482fc4/ctr-all-d6cbaddc-6ab6-44a3-b640-31917ecb6d37-f2f52c2f-4489-4f07-9a7b-bd80215ac033.m3u8?r=720&v=1&hash=0dd5c2945f832478f363944111678cf2f48cb254"
[generic] ctr-all-d6cbaddc-6ab6-44a3-b640-31917ecb6d37-f2f52c2f-4489-4f07-9a7b-bd80215ac033: Downloading webpage
[generic] ctr-all-d6cbaddc-6ab6-44a3-b640-31917ecb6d37-f2f52c2f-4489-4f07-9a7b-bd80215ac033: Downloading m3u8 information
[info] ctr-all-d6cbaddc-6ab6-44a3-b640-31917ecb6d37-f2f52c2f-4489-4f07-9a7b-bd80215ac033: Downloading 1 format(s): aac-128k-Română
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 416
[download] Destination: ctr-all-d6cbaddc-6ab6-44a3-b640-31917ecb6d37-f2f52c2f-4489-4f07-9a7b-bd80215ac033 [ctr-all-d6cbaddc-6ab6-44a3-b640-31917ecb6d37-f2f52c2f-4489-4f07-9a7b-bd80215ac033].mp4
ERROR: Initialization fragment found after media fragments, unable to download
```

**Comment by pukkandan** [comment]
![image](https://user-images.githubusercontent.com/6623388/187038669-e5c2a304-1946-4ece-93ae-73cf1061869d.png)

**Comment by madnesofjuice** [comment]
> ![image](https://user-images.githubusercontent.com/6623388/187038669-e5c2a304-1946-4ece-93ae-73cf1061869d.png)

just missed the first line, sorry

**Comment by pukkandan** [comment]
That's still not the verbose log... and I can't open the URL anyway

**Comment by bashonly** [comment]
This is a Disney+ link w/ DRM
