### ISSUE TITLE
Documentation bug: no such option: --use-extractors

### ISSUE THREAD

**Issue by atom-smasher** [yt-dlp/yt-dlp#4784]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.08.19** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Online documentation - https://github.com/yt-dlp/yt-dlp#general-options - includes this:
```
--use-extractors NAMES          Extractor names to use separated by commas.
                                You can also use regexes, "all", "default"
                                and "end" (end URL matching); e.g. --ies
                                "holodex.*,end,youtube". Prefix the name
                                with a "-" to exclude it, e.g. --ies
                                default,-generic. Use --list-extractors for
                                a list of extractor names. (Alias: --ies)
```

Attempting to use it results in this:
```
yt-dlp: error: no such option: --use-extractors
```

Output below from this command: `yt-dlp --ignore-config -vU --use-extractors youtube KjJdWl_zd0w`

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['--ignore-config', '-vU', '--use-extractors', 'youtube', 'KjJdWl_zd0w']

Usage: yt-dlp [OPTIONS] URL [URL...]

yt-dlp: error: no such option: --use-extractors
```

**Comment by pukkandan** [comment]
Is this with release or master? The option was added after the past release

**Comment by atom-smasher** [comment]
version 2022.08.19.

I guess I'll look for this in the next release.

**Comment by pukkandan** [comment]
For reference, the last release's readme is always available here: https://github.com/yt-dlp/yt-dlp/tree/release#readme
