### ISSUE TITLE
[Site support request] weverse.io

### ISSUE THREAD

**Issue by WeNewMi** [yt-dlp/yt-dlp#4786]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.08.19** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Worldwide

### Example URLs

Single video: 
- https://weverse.io/blackpink/live/2-102735330
- https://weverse.io/ohmygirl/live/2-103899888

Page with all video: 
- https://weverse.io/blackpink/live
- https://weverse.io/ohmygirl/live

### Provide a description that is worded well enough to be understood

Weverse is a website where musicians can interact with fans. 
The website also allows musicians to livestream but in order to view a livestream you have to be logged in. When the livestream ends it's uploaded as a video.
I found a reddit thread where an user mentioned they could get the m3u8/mpd files but they couldn't get past the 403 forbidden error.
[reddit thread](https://old.reddit.com/r/youtubedl/comments/wese0u/weverse_video_support)

Musicians can also post videos but these have a download button so I am not sure if support for this should be added.
Example url:
[https://weverse.io/blackpink/artist/1-101521998](https://weverse.io/blackpink/artist/1-101521998)

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://weverse.io/blackpink/live/2-102735330']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.08.19 [48c88e0] (zip)
[debug] Python 3.10.4 (CPython 64bit) - Linux-5.15.0-41-generic-x86_64-with-glibc2.35 (glibc 2.35)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2
[debug] Optional libraries: certifi-2020.06.20, secretstorage-3.3.1, sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.08.19, Current version: 2022.08.19
yt-dlp is up to date (2022.08.19)
[debug] [generic] Extracting URL: https://weverse.io/blackpink/live/2-102735330
[generic] 2-102735330: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] 2-102735330: Extracting information
[debug] Looking for Brightcove embeds
[debug] Looking for embeds
ERROR: Unsupported URL: https://weverse.io/blackpink/live/2-102735330
Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1442, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1518, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 666, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/generic.py", line 3077, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://weverse.io/blackpink/live/2-102735330
```

**Comment by zxcJosh** [comment]
Where could I send the credentials?

**Comment by pukkandan** [comment]
The labels are just a hint for maintainers/contributors that account is needed to work on the issue. If any developer needs account details for working on this, they will let you know how to share it privately.

**Comment by CrazyWolf13** [comment]
I'd also love to seee this, so i could watch BTS lol

**Comment by kevs926** [comment]
if you can find the link of the m3u8 file, and do some simple find and replace on the m3u8, you can download the weverse live video.

the problem is that if you find the m3u8 and just paste it on the command line, it will return the 403 error
for example:
```
yt-dlp https://weverse-rmcnmv.akamaized.net/c/read/v2/VOD_ALPHA/weverse_2022_10_29_0/hls/211decac-579b-11ed-ab80-48df37269fd0.m3u8?__gda__=1667213637_55d66afcafc74d033cf5e6affe0e7f43```

this will download the m3u8 and this is what the m3u8 contains:

```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-TARGETDURATION:4
#EXTINF:4.000000,
211decac-579b-11ed-ab80-48df37269fd0-000000.ts
#EXTINF:4.000000,
211decac-579b-11ed-ab80-48df37269fd0-000001.ts
#EXTINF:4.000000,
211decac-579b-11ed-ab80-48df37269fd0-000002.ts
.
.
```
the next part is yt-dlp downloads the fragments and probably uses the url:
``` https://weverse-rmcnmv.akamaized.net/c/read/v2/VOD_ALPHA/weverse_2022_10_29_0/hls/211decac-579b-11ed-ab80-48df37269fd0-000000.ts
https://weverse-rmcnmv.akamaized.net/c/read/v2/VOD_ALPHA/weverse_2022_10_29_0/hls/211decac-579b-11ed-ab80-48df37269fd0-000001.ts
https://weverse-rmcnmv.akamaized.net/c/read/v2/VOD_ALPHA/weverse_2022_10_29_0/hls/211decac-579b-11ed-ab80-48df37269fd0-000002.ts
.
.
```
this will result in 403 because you need the gda part on the original link. the link you need is:
```
https://weverse-rmcnmv.akamaized.net/c/read/v2/VOD_ALPHA/weverse_2022_10_29_0/hls/211decac-579b-11ed-ab80-48df37269fd0-000000.ts?__gda__=1667213637_55d66afcafc74d033cf5e6affe0e7f43
.
.
```

**Comment by CrazyWolf13** [comment]
> if you can find the link of the m3u8 file, and do some simple find and replace on the m3u8, you can download the weverse live video.
> 
> the problem is that if you find the m3u8 and just paste it on the command line, it will return the 403 error
> for example:
> ```
> yt-dlp https://weverse-rmcnmv.akamaized.net/c/read/v2/VOD_ALPHA/weverse_2022_10_29_0/hls/211decac-579b-11ed-ab80-48df37269fd0.m3u8?__gda__=1667213637_55d66afcafc74d033cf5e6affe0e7f43
> ```
> 
> this will download the m3u8 and this is what the m3u8 contains:
> 
> ```
> #EXTM3U
> #EXT-X-VERSION:3
> #EXT-X-MEDIA-SEQUENCE:0
> #EXT-X-TARGETDURATION:4
> #EXTINF:4.000000,
> 211decac-579b-11ed-ab80-48df37269fd0-000000.ts
> #EXTINF:4.000000,
> 211decac-579b-11ed-ab80-48df37269fd0-000001.ts
> #EXTINF:4.000000,
> 211decac-579b-11ed-ab80-48df37269fd0-000002.ts
> .
> .
> ```
> the next part is yt-dlp downloads the fragments and probably uses the url:
> ``` https://weverse-rmcnmv.akamaized.net/c/read/v2/VOD_ALPHA/weverse_2022_10_29_0/hls/211decac-579b-11ed-ab80-48df37269fd0-000000.ts
> https://weverse-rmcnmv.akamaized.net/c/read/v2/VOD_ALPHA/weverse_2022_10_29_0/hls/211decac-579b-11ed-ab80-48df37269fd0-000001.ts
> https://weverse-rmcnmv.akamaized.net/c/read/v2/VOD_ALPHA/weverse_2022_10_29_0/hls/211decac-579b-11ed-ab80-48df37269fd0-000002.ts
> .
> .
> ```
> this will result in 403 because you need the gda part on the original link. the link you need is:
> ```
> https://weverse-rmcnmv.akamaized.net/c/read/v2/VOD_ALPHA/weverse_2022_10_29_0/hls/211decac-579b-11ed-ab80-48df37269fd0-000000.ts?__gda__=1667213637_55d66afcafc74d033cf5e6affe0e7f43
> .
> .
> ```
> so what you need to do is replace each .ts in the m3u8 to include the extra part, and also to write the complete url (because relative url is not gonna work if you will use a different website to host your modified m3u8)

Sounds very complicated 😄

**Comment by godly-devotion** [comment]
> if you can find the link of the m3u8 file, and do some simple find and replace on the m3u8, you can download the weverse live video.
> 
> the problem is that if you find the m3u8 and just paste it on the command line, it will return the 403 error for example:
> 
> ```
> yt-dlp https://weverse-rmcnmv.akamaized.net/c/read/v2/VOD_ALPHA/weverse_2022_10_29_0/hls/211decac-579b-11ed-ab80-48df37269fd0.m3u8?__gda__=1667213637_55d66afcafc74d033cf5e6affe0e7f43
> ```
> 
> this will download the m3u8 and this is what the m3u8 contains:
> 
> ```
> #EXTM3U
> #EXT-X-VERSION:3
> #EXT-X-MEDIA-SEQUENCE:0
> #EXT-X-TARGETDURATION:4
> #EXTINF:4.000000,
> 211decac-579b-11ed-ab80-48df37269fd0-000000.ts
> #EXTINF:4.000000,
> 211decac-579b-11ed-ab80-48df37269fd0-000001.ts
> #EXTINF:4.000000,
> 211decac-579b-11ed-ab80-48df37269fd0-000002.ts
> .
> .
> ```
> 
> the next part is yt-dlp downloads the fragments and probably uses the url:
> 
> ```ts
> https://weverse-rmcnmv.akamaized.net/c/read/v2/VOD_ALPHA/weverse_2022_10_29_0/hls/211decac-579b-11ed-ab80-48df37269fd0-000001.ts
> https://weverse-rmcnmv.akamaized.net/c/read/v2/VOD_ALPHA/weverse_2022_10_29_0/hls/211decac-579b-11ed-ab80-48df37269fd0-000002.ts
> .
> .
> ```
> 
> this will result in 403 because you need the gda part on the original link. the link you need is:
> 
> ```
> https://weverse-rmcnmv.akamaized.net/c/read/v2/VOD_ALPHA/weverse_2022_10_29_0/hls/211decac-579b-11ed-ab80-48df37269fd0-000000.ts?__gda__=1667213637_55d66afcafc74d033cf5e6affe0e7f43
> .
> .
> ```
> 
> so what you need to do is replace each .ts in the m3u8 to include the extra part, and also to write the complete url (because relative url is not gonna work if you will use a different website to host your modified m3u8)

That worked great! For reference, the complete command looks like this after you created and edited your m3u8 file.

`ffmpeg -protocol_whitelist file,https,tls -allowed_extensions ALL -i YOUR_MODIFIED_FILE.m3u8 -c:v copy -bsf:a aac_adtstoasc VIDEO.mp4`

Remember to replace the placeholders with the location of your m3u8 file and output video filename.

**Comment by CrazyWolf13** [comment]
> > if you can find the link of the m3u8 file, and do some simple find and replace on the m3u8, you can download the weverse live video.
> > 
> > the problem is that if you find the m3u8 and just paste it on the command line, it will return the 403 error for example:
> > 
> > ```
> > yt-dlp https://weverse-rmcnmv.akamaized.net/c/read/v2/VOD_ALPHA/weverse_2022_10_29_0/hls/211decac-579b-11ed-ab80-48df37269fd0.m3u8?__gda__=1667213637_55d66afcafc74d033cf5e6affe0e7f43
> > ```
> > 
> > this will download the m3u8 and this is what the m3u8 contains:
> > 
> > ```
> > #EXTM3U
> > #EXT-X-VERSION:3
> > #EXT-X-MEDIA-SEQUENCE:0
> > #EXT-X-TARGETDURATION:4
> > #EXTINF:4.000000,
> > 211decac-579b-11ed-ab80-48df37269fd0-000000.ts
> > #EXTINF:4.000000,
> > 211decac-579b-11ed-ab80-48df37269fd0-000001.ts
> > #EXTINF:4.000000,
> > 211decac-579b-11ed-ab80-48df37269fd0-000002.ts
> > .
> > .
> > ```
> > 
> > the next part is yt-dlp downloads the fragments and probably uses the url:
> > 
> > ```ts
> > https://weverse-rmcnmv.akamaized.net/c/read/v2/VOD_ALPHA/weverse_2022_10_29_0/hls/211decac-579b-11ed-ab80-48df37269fd0-000001.ts
> > https://weverse-rmcnmv.akamaized.net/c/read/v2/VOD_ALPHA/weverse_2022_10_29_0/hls/211decac-579b-11ed-ab80-48df37269fd0-000002.ts
> > .
> > .
> > ```
> > 
> > this will result in 403 because you need the gda part on the original link. the link you need is:
> > 
> > ```
> > https://weverse-rmcnmv.akamaized.net/c/read/v2/VOD_ALPHA/weverse_2022_10_29_0/hls/211decac-579b-11ed-ab80-48df37269fd0-000000.ts?__gda__=1667213637_55d66afcafc74d033cf5e6affe0e7f43
> > .
> > .
> > ```
> > 
> > so what you need to do is replace each .ts in the m3u8 to include the extra part, and also to write the complete url (because relative url is not gonna work if you will use a different website to host your modified m3u8)
> 
> That worked great! For reference, the complete command looks like this after you created and edited your m3u8 file.
> 
> ```
> ffmpeg -protocol_whitelist file,https,tls -allowed_extensions ALL -i YOUR_MODIFIED_FILE.m3u8 -c:v copy -bsf:a aac_adtstoasc VIDEO.mp4
> ```
> 
> Remember to replace the placeholders with the location of your m3u8 file and output video filename.

Will this now be "implemented" in the yt-dlp to work without that compley m3u8 stuff?

**Comment by bashonly** [comment]
> Will this now be "implemented" in the yt-dlp to work without that compley m3u8 stuff?

I've submitted a PR (#5528) that addresses generic VOD HLS streams which need their playlist URL's query appended to their segment URLs

**Comment by Ogrlemonsoup** [comment]
Links to mp4 files can be found in json
Request URL example from devtools: https://global.apis.naver.com/rmcnmv/rmcnmv/vod/play/v2.0/716918EA67BE6341B670F4A411702290F678?key=V1282c79e9c02ce2015eaeb9b31ecc4c1e879b438141d115e07b41c8ac93f6a139459eb9b31ecc4c1e879&sid=2070&pid=4863db68-4449-461e-b770-170c67b0a9b6&nonce=1672536827601&devt=html5_pc&prv=N&aup=N&stpb=N&cpl=en&env=prod&lc=en&adi=%5B%7B%22adSystem%22%3A%22null%22%7D%5D&adu=%2F

**Comment by kpg-anon** [comment]
any update on this? i'd really like to be able to download/stream weverse videos in mpv now that vlive is shut down
