### ISSUE TITLE
viu issue

### ISSUE THREAD

**Issue by showkubii** [yt-dlp/yt-dlp#479]
```
C:\Users\neunghaha28\Downloads\viu>yt-dlp https://www.viu.com/ott/th/th-th/vod/307340/Delayed-Justice -v
[debug] Command-line config: ['https://www.viu.com/ott/th/th-th/vod/307340/Delayed-Justice', '-v']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] yt-dlp version 2021.06.23 (exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.22000-SP0
[debug] exe versions: ffmpeg 2021-06-30-git-de8e6e67e7-full_build-www.gyan.dev, ffprobe 2021-06-30-git-de8e6e67e7-full_build-www.gyan.dev
[debug] Proxy map: {}
[debug] [viu:ott] Extracting URL: https://www.viu.com/ott/th/th-th/vod/307340/Delayed-Justice
[viu:ott] 307340: Downloading video info
ERROR: Unable to download JSON metadata: [WinError 10054] An existing connection was forcibly closed by the remote host (caused by ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
  File "yt_dlp\extractor\common.py", line 679, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 3089, in urlopen
  File "urllib\request.py", line 525, in open
  File "urllib\request.py", line 542, in _open
  File "urllib\request.py", line 502, in _call_chain
  File "yt_dlp\utils.py", line 2668, in http_open
  File "urllib\request.py", line 1358, in do_open
  File "http\client.py", line 1344, in getresponse
  File "http\client.py", line 307, in begin
  File "http\client.py", line 268, in _read_status
  File "socket.py", line 669, in readinto
```

**Comment by zackmark29** [comment]
> ```
> C:\Users\neunghaha28\Downloads\viu>yt-dlp https://www.viu.com/ott/th/th-th/vod/307340/Delayed-Justice -v
> [debug] Command-line config: ['https://www.viu.com/ott/th/th-th/vod/307340/Delayed-Justice', '-v']
> [debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
> [debug] yt-dlp version 2021.06.23 (exe)
> [debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.22000-SP0
> [debug] exe versions: ffmpeg 2021-06-30-git-de8e6e67e7-full_build-www.gyan.dev, ffprobe 2021-06-30-git-de8e6e67e7-full_build-www.gyan.dev
> [debug] Proxy map: {}
> [debug] [viu:ott] Extracting URL: https://www.viu.com/ott/th/th-th/vod/307340/Delayed-Justice
> [viu:ott] 307340: Downloading video info
> ERROR: Unable to download JSON metadata: [WinError 10054] An existing connection was forcibly closed by the remote host (caused by ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
>   File "yt_dlp\extractor\common.py", line 679, in _request_webpage
>   File "yt_dlp\YoutubeDL.py", line 3089, in urlopen
>   File "urllib\request.py", line 525, in open
>   File "urllib\request.py", line 542, in _open
>   File "urllib\request.py", line 502, in _call_chain
>   File "yt_dlp\utils.py", line 2668, in http_open
>   File "urllib\request.py", line 1358, in do_open
>   File "http\client.py", line 1344, in getresponse
>   File "http\client.py", line 307, in begin
>   File "http\client.py", line 268, in _read_status
>   File "socket.py", line 669, in readinto
> ```

You need to use VPN or proxy. It looks like it's blocking your ip

```python
C:\Users\MARK\Documents\GitHub\yt-dlp>py -3.6 -m yt_dlp https://www.viu.com/ott/th/th-th/vod/307340/Delayed-Justice -v
[debug] Command-line config: ['https://www.viu.com/ott/th/th-th/vod/307340/Delayed-Justice', '-v']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] yt-dlp version 2021.07.07 (source)
[debug] Plugin Extractors: ['SamplePlugin']
[debug] Git HEAD: dc34f1943
[debug] Python version 3.6.0 (CPython 64bit) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg N-102009-gefdb564504
[debug] Proxy map: {}
[debug] [viu:ott] Extracting URL: https://www.viu.com/ott/th/th-th/vod/307340/Delayed-Justice
[viu:ott] 307340: Downloading video info
[viu:ott] Downloading playlist 16034 - add --no-playlist to just download video
[download] Downloading playlist: Delayed Justice
[viu:ott] playlist Delayed Justice: Collected 40 videos; downloading 40 of them
[download] Downloading video 1 of 40
[debug] [viu:ott] Extracting URL: http://www.viu.com/ott/th/th-th/vod/307340/#__youtubedl_smuggle=%7B%22force_noplaylist%22%3A+true%7D
[viu:ott] 307340: Downloading video info
[viu:ott] 307340: Downloading stream info
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 307340: Downloading 1 format(s): s1080p
[debug] Invoking downloader on "https://d1k2us671qcoau.cloudfront.net/vodapi/viu_thaws.m3u8?vid=90add74348c551dddb72a0adb80b2044&layer=Layer4&ts=202107100959&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9kMWsydXM2NzFxY29hdS5jbG91ZGZyb250Lm5ldC92b2RhcGkvKiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTYyNTg5Njc2OH19fV19&Signature=Ok2b24f8Hl6MCAlxLIDvQwj0JO3lo2gVw-KeON41~lLq-l8LTQAyL-~h1AZVMHoieyKvMJphSVJR4os3v8ETgwO9OL2wDLG7XbUeZGiz5-4YK5DQWRr9Zc7XxoWsq~9ZvtF4RZENjUgM8xo1v1dGMQ9pQCyqK7Ko9GRMeNF9205z6mza4U0mo1EdnE4zVAcs6CML1sGgEzwYnT9QBqd1D1AXGrn02RODPsfmVWRDwGJiSgU10yLu16aYGb4NFQoT~K822OKMFR9tRh4TKYDFXmUCRg4f156QxjojcnZD47ekexb1OIWv39pu3yRQPmC-Jn38KLpbVFZXSo~-2ICJMQ__&Key-Pair-Id=APKAJ6Z4RF5IYK7Y3SQQ"
[download] Destination: ตอนที่ 1 [307340].mp4
```

**Comment by Ashish0804** [comment]
Working for me aswell (Indian IP). Try to see if you can actually play the video in the browser.

**Comment by showkubii** [comment]
I can use it normally without VPN. Thank you very much.

> > ```
> > C:\Users\neunghaha28\Downloads\viu>yt-dlp https://www.viu.com/ott/th/th-th/vod/307340/Delayed-Justice -v
> > [debug] Command-line config: ['https://www.viu.com/ott/th/th-th/vod/307340/Delayed-Justice', '-v']
> > [debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
> > [debug] yt-dlp version 2021.06.23 (exe)
> > [debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.22000-SP0
> > [debug] exe versions: ffmpeg 2021-06-30-git-de8e6e67e7-full_build-www.gyan.dev, ffprobe 2021-06-30-git-de8e6e67e7-full_build-www.gyan.dev
> > [debug] Proxy map: {}
> > [debug] [viu:ott] Extracting URL: https://www.viu.com/ott/th/th-th/vod/307340/Delayed-Justice
> > [viu:ott] 307340: Downloading video info
> > ERROR: Unable to download JSON metadata: [WinError 10054] An existing connection was forcibly closed by the remote host (caused by ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
> >   File "yt_dlp\extractor\common.py", line 679, in _request_webpage
> >   File "yt_dlp\YoutubeDL.py", line 3089, in urlopen
> >   File "urllib\request.py", line 525, in open
> >   File "urllib\request.py", line 542, in _open
> >   File "urllib\request.py", line 502, in _call_chain
> >   File "yt_dlp\utils.py", line 2668, in http_open
> >   File "urllib\request.py", line 1358, in do_open
> >   File "http\client.py", line 1344, in getresponse
> >   File "http\client.py", line 307, in begin
> >   File "http\client.py", line 268, in _read_status
> >   File "socket.py", line 669, in readinto
> > ```
> 
> Try to use VPN or proxy. It looks like it's blocking your ip
> 
> ```
> C:\Users\MARK\Documents\GitHub\yt-dlp>py -3.6 -m yt_dlp https://www.viu.com/ott/th/th-th/vod/307340/Delayed-Justice -v
> [debug] Command-line config: ['https://www.viu.com/ott/th/th-th/vod/307340/Delayed-Justice', '-v']
> [debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
> [debug] yt-dlp version 2021.07.07 (source)
> [debug] Plugin Extractors: ['SamplePlugin']
> [debug] Git HEAD: dc34f1943
> [debug] Python version 3.6.0 (CPython 64bit) - Windows-10-10.0.19041-SP0
> [debug] exe versions: ffmpeg N-102009-gefdb564504
> [debug] Proxy map: {}
> [debug] [viu:ott] Extracting URL: https://www.viu.com/ott/th/th-th/vod/307340/Delayed-Justice
> [viu:ott] 307340: Downloading video info
> [viu:ott] Downloading playlist 16034 - add --no-playlist to just download video
> [download] Downloading playlist: Delayed Justice
> [viu:ott] playlist Delayed Justice: Collected 40 videos; downloading 40 of them
> [download] Downloading video 1 of 40
> [debug] [viu:ott] Extracting URL: http://www.viu.com/ott/th/th-th/vod/307340/#__youtubedl_smuggle=%7B%22force_noplaylist%22%3A+true%7D
> [viu:ott] 307340: Downloading video info
> [viu:ott] 307340: Downloading stream info
> [debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
> [debug] Default format spec: bestvideo*+bestaudio/best
> [info] 307340: Downloading 1 format(s): s1080p
> [debug] Invoking downloader on "https://d1k2us671qcoau.cloudfront.net/vodapi/viu_thaws.m3u8?vid=90add74348c551dddb72a0adb80b2044&layer=Layer4&ts=202107100959&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9kMWsydXM2NzFxY29hdS5jbG91ZGZyb250Lm5ldC92b2RhcGkvKiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTYyNTg5Njc2OH19fV19&Signature=Ok2b24f8Hl6MCAlxLIDvQwj0JO3lo2gVw-KeON41~lLq-l8LTQAyL-~h1AZVMHoieyKvMJphSVJR4os3v8ETgwO9OL2wDLG7XbUeZGiz5-4YK5DQWRr9Zc7XxoWsq~9ZvtF4RZENjUgM8xo1v1dGMQ9pQCyqK7Ko9GRMeNF9205z6mza4U0mo1EdnE4zVAcs6CML1sGgEzwYnT9QBqd1D1AXGrn02RODPsfmVWRDwGJiSgU10yLu16aYGb4NFQoT~K822OKMFR9tRh4TKYDFXmUCRg4f156QxjojcnZD47ekexb1OIWv39pu3yRQPmC-Jn38KLpbVFZXSo~-2ICJMQ__&Key-Pair-Id=APKAJ6Z4RF5IYK7Y3SQQ"
> [download] Destination: ตอนที่ 1 [307340].mp4
> ```

I can use it normally without VPN. Thank you very much.
