### ISSUE TITLE
How to use "--abort-on-unavailable-fragment" option inside a python script?

### ISSUE THREAD

**Issue by Ghostfreak803** [yt-dlp/yt-dlp#4795]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.08.19** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Is there a way to use "`--abort-on-unavailable-fragment`" option inside a python script (using module `yt_dlp`)? I know that YoutubeDL() uses a dictionary of options but I don't know how to make `--abort-on-unavailable-fragment` into a key value pair.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
https://github.com/yt-dlp/yt-dlp/blob/e0992d555879b07ac7622dfac1f88f9e76e32923/yt_dlp/downloader/fragment.py#L39-L40

**Comment by Ghostfreak803** [comment]
> https://github.com/yt-dlp/yt-dlp/blob/e0992d555879b07ac7622dfac1f88f9e76e32923/yt_dlp/downloader/fragment.py#L39-L40

I think it already skips unavailable fragments. I'm looking for a way to abort the whole download if a fragment is not available (which I think is why `--abort-on-unavailable-fragment` is used on the command-line?)

I'm basically talking about aborting download under following scenario:
```
[download] Got error: <urlopen error [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:997)>
[download]  80.7% of ~427.81MiB at   17.62MiB/s ETA 00:09 (frag 246/305)[download] fragment not found; Skipping fragment 247 ...
[download] Got error: <urlopen error [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:997)>
[download] Got error: <urlopen error [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:997)>
[download] Got error: <urlopen error [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:997)>
[download] Got error: <urlopen error [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:997)>
[download] Got error: <urlopen error [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:997)>
[download]  81.6% of ~428.06MiB at   11.56MiB/s ETA 00:09 (frag 249/305)[download] fragment not found; Skipping fragment 250 ...
[download] fragment not found; Skipping fragment 251 ...
[download]  82.0% of ~428.07MiB at    1.30MiB/s ETA 00:09 (frag 250/305)[download] fragment not found; Skipping fragment 254 ...
[download]  82.0% of ~428.12MiB at   49.05MiB/s ETA 00:09 (frag 250/305)[download] fragment not found; Skipping fragment 255 ...
[download] fragment not found; Skipping fragment 256 ...
[download] 100% of 418.76MiB in 00:58 at 7.21MiB/s

```

**Comment by Lesmiscore** [comment]
`{'skip_unavailable_fragments': False}` to do the same thing as `--abort-on-unavailable-fragment`

**Comment by Ghostfreak803** [comment]
> `{'skip_unavailable_fragments': False}` to do the same thing as `--abort-on-unavailable-fragment`

Although I'm unable to verify your solution right now (videos are downloading fine without skipped fragments), it seems logical enough (and I guess that's what @pukkandan was hinting at in the earlier comment), so I guess I'll close the issue. Thanks.

**Comment by SkyzcYou** [comment]
> `{'skip_unavailable_fragments': False}` to do the same thing as `--abort-on-unavailable-fragment`

This is useful
