### ISSUE TITLE
latest version cannot download youtube videos which require signing in to confirm one's age

### ISSUE THREAD

**Issue by lvmm** [yt-dlp/yt-dlp#4799]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.08.19** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

russia

### Provide a description that is worded well enough to be understood

2022.08.19 version cannot download youtube videos which require signing in to confirm one's age - displays what's pasted in the output window and then waits indefinitely without using any CPU.  2022.05.18 version downloads these videos with some JS error messages, but it downloads them, and even without throttling.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.youtube.com/watch?v=VHvjs0vQZkA']
[debug] User config "/home/lvm/.config/yt-dlp/config": ['--prefer-ffmpeg', '-o', '%(uploader)s--%(upload_date)s--%(title)s--%(id)s.%(ext)s', '-f', 'bestvideo[height<=1080]+bestaudio/best[height<=1080]', '--fragment-retries', 'infinite', '-R', 'infinite', '--no-mtime', '-i', '--merge-output-format', 'mkv']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.08.19 [48c88e0] (zip)
[debug] Python 3.10.6 (CPython 64bit) - Linux-5.4.0-122-generic-x86_64-with-glibc2.27 (glibc 2.27)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 3.4.11, ffprobe 3.4.11, phantomjs 2.1.1, rtmpdump 2.4
[debug] Optional libraries: certifi-2018.01.18, sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.08.19, Current version: 2022.08.19
yt-dlp is up to date (2022.08.19)
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=VHvjs0vQZkA
[youtube] VHvjs0vQZkA: Downloading webpage
[youtube] VHvjs0vQZkA: Downloading android player API JSON
[youtube] VHvjs0vQZkA: Downloading tv embedded player API JSON
[youtube] VHvjs0vQZkA: Downloading web embedded client config
[youtube] VHvjs0vQZkA: Downloading player 113ca41c
[youtube] VHvjs0vQZkA: Downloading web embedded player API JSON
[debug] Loading youtube-nsig.113ca41c from cache
WARNING: [youtube] VHvjs0vQZkA: Native nsig extraction failed: Trying with PhantomJS
         n = u7t2L-U4UZj8ps ; player = https://www.youtube.com/s/player/113ca41c/player_ias.vflset/en_US/base.js
[debug] [youtube] No terminating paren } in: {e=void 0===e?"":e;f=void 0===f?!1:f;if(a)if(c&...ack;d.level=b[c].level;g.eu(d)}Zw().set("errors",{; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[youtube] VHvjs0vQZkA: Executing signature code
[debug] [youtube] PhantomJS command line: phantomjs --ssl-protocol=any /tmp/tmpxv8z6659
```

**Comment by pukkandan** [comment]
See pinned issues
