### ISSUE TITLE
Unexpected change to Firefox `--cookies-from-browser` default behaviour

### ISSUE THREAD

**Issue by coletdjnz** [yt-dlp/yt-dlp#4800]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.08.19** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

On my Firefox setup I run automatic temporary containers with a few whitelisted sites in their own containers (e.g. Youtube). This worked fine before by default with `--cookies-from-browser` (assuming I didn't have multiple different containers of the same site).

This no longer works by default in master (see log), assuming regression after https://github.com/yt-dlp/yt-dlp/commit/9bd13fe5bbe1df6bb01d4edb68f2c63a4812bf94

It appears the default behaviour has been changed from extracting all cookies from all containers to ~~just using the most recent container~~? This is wildly different behaviour and is likely to cause many issues :confused:

We should maybe look at either reverting this default or having an option to revert it (compat-opt?).

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

Master:
```shell
yt-dlp --cookies-from-browser firefox :ytsubs --ignore-config -v
[debug] Command-line config: ['--cookies-from-browser', 'firefox', ':ytsubs', '--ignore-config', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.08.19.2 [48c88e088]
[debug] Lazy loading extractors is disabled
[debug] Python 3.10.5 (CPython 64bit) - Linux-5.19.1-3-MANJARO-x86_64-with-glibc2.36 (glibc 2.36)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 5.0.1 (setts), ffprobe 5.0.1, phantomjs 2.1.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, secretstorage-3.3.2, sqlite3-2.6.0, websockets-10.3
[Cookies] Extracting cookies from firefox
[debug] Extracting cookies from: "/home/coletdjnz/.mozilla/firefox/xxx-default/cookies.sqlite"
[Cookies] Extracted 23 cookies from firefox
[debug] Proxy map: {}
[debug] Loaded 1664 extractors
[debug] [youtube:subscriptions] Extracting URL: :ytsubs
[debug] [youtube:tab] Extracting URL: https://www.youtube.com/feed/subscriptions
[youtube:tab] subscriptions: Downloading webpage
[debug] [youtube:tab] Final URL: https://www.youtube.com/feed/subscriptions
[download] Downloading playlist: subscriptions
[youtube:tab] Playlist subscriptions: Downloading 0 videos of 0
[download] Finished downloading playlist: subscriptions
```

Release:
```
yt-dlp --cookies-from-browser firefox :ytsubs --ignore-config -v
[debug] Command-line config: ['--cookies-from-browser', 'firefox', ':ytsubs', '--ignore-config', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.08.19 [48c88e0] (pip)
[debug] Python 3.10.5 (CPython 64bit) - Linux-5.19.1-3-MANJARO-x86_64-with-glibc2.36 (glibc 2.36)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 5.0.1 (setts), ffprobe 5.0.1, phantomjs 2.1.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, secretstorage-3.3.2, sqlite3-2.6.0, websockets-10.3
[Cookies] Extracting cookies from firefox
[debug] Extracting cookies from: "/home/coletdjnz/.mozilla/firefox/xxx-default/cookies.sqlite"
[Cookies] Extracted 1739 cookies from firefox
[debug] Proxy map: {}
[debug] [youtube:subscriptions] Extracting URL: :ytsubs
[debug] [youtube:tab] Extracting URL: https://www.youtube.com/feed/subscriptions
[youtube:tab] subscriptions: Downloading webpage
[debug] [youtube:tab] Final URL: https://www.youtube.com/feed/subscriptions
[download] Downloading playlist: subscriptions
[debug] [youtube:tab] Extracted SAPISID cookie
[youtube:tab] subscriptions page 1: Downloading API JSON
[youtube:tab] subscriptions page 2: Downloading API JSON
```

**Comment by pukkandan** [comment]
> to just using the most recent container?

By default, it is using cookies **without any container** now. I think the previous default is buggy, but if we want to, it can be reinstated. Some way to select the "no container" cookies will need to be added though

cc @bashonly

**Comment by Lalarian** [comment]
I don't understand how to make practical use of yt-dlp like this. Are you people actually opening a terminal, manually copying the URL and typing the command for using yt-dlp? I am using the Fiefox extension (in Floorp) and I couldn't use it otherwise, because it's way to bothersome having to do this by hand each time.. isnt there a better way for doing this?
