### ISSUE TITLE
[Feature Request] Provide a switch to limit the scraper for comments

### ISSUE THREAD

**Issue by pvonmoradi** [yt-dlp/yt-dlp#481]
- [x] I'm reporting a feature request
- [x] I've verified that I'm running yt-dlp version **2021.07.07**
- [x] I've searched the bugtracker for similar feature requests including closed ones
## Description
Popular videos have >50k comments. It would be near impossible to download them all. Is it possible to limit the `--get-comments` feature to traverse only most up-voted ones or only root comments?   

If not, is it possible to get the already downloaded comments when the process is stopped? (Do data get appended?)

**Comment by pukkandan** [comment]
@colethedj would this be possible in #466 ?

**Comment by pukkandan** [comment]
> If not, is it possible to get the already downloaded comments when the process is stopped? (Do data get appended?)

This is not possible to implement because of the way youtube provides continuation tokens

**Comment by colethedj** [comment]
> @colethedj would this be possible in #466, pehaps by adding a `max_comments` and `max_comments_depth` ?
> 
> > If not, is it possible to get the already downloaded comments when the process is stopped
> 
> This should also be possible by catching `KeyboardInterrupt` inside the comment download code

`max_comments` should be fairly easy to implement in `_extract_comments`. On the other hand, `max_comments_depth` might be a bit trickier - I think that would have to be handled within `_comment_entries`

> This should also be possible by catching `KeyboardInterrupt` inside the comment download code

Will have a look at this.

#466 will allow sorting by popular (though note youtube doesn't provide all comments in that mode).
