### ISSUE TITLE
Embedded Youtube

### ISSUE THREAD

**Issue by M1Aston** [yt-dlp/yt-dlp#4812]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.09.01** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Netherlands

### Provide a description that is worded well enough to be understood

Embedded Youtube video is not found. 
I don't know what else to add. :-)

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://historiek.net/een-nieuwe-spelling-invoering-van-de-spelling-marchant-1934/150793/D:\\SOFTWARE\\MUZIEK\\MPC-BE\\yt-dlp.exe', '-vU', 'https://historiek.net/een-nieuwe-spelling-invoering-van-de-spelling-marchant-1934/150793/']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.09.01 [5d7c7d6] (win32_exe)
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1670 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.09.01, Current version: 2022.09.01
yt-dlp is up to date (2022.09.01)
[debug] [generic] Extracting URL: https://historiek.net/een-nieuwe-spelling-invoering-van-de-spelling-marchant-1934/150793/D:\SOFTWARE\MUZIEK\MPC-BE\yt-dlp.exe
[generic] D:\SOFTWARE\MUZIEK\MPC-BE\yt-dlp: Downloading webpage
[redirect] Following redirect to https://historiek.net/
[debug] [generic] Extracting URL: https://historiek.net/
[generic] historiek: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] historiek: Extracting information
[debug] Looking for Brightcove embeds
[debug] Looking for embeds
ERROR: Unsupported URL: https://historiek.net/
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1459, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1535, in __extract_info
  File "yt_dlp\extractor\common.py", line 670, in extract
  File "yt_dlp\extractor\generic.py", line 3078, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://historiek.net/

[debug] [generic] Extracting URL: https://historiek.net/een-nieuwe-spelling-invoering-van-de-spelling-marchant-1934/150793/
[generic] 150793: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] 150793: Extracting information
[debug] Looking for Brightcove embeds
[debug] Looking for embeds
ERROR: Unsupported URL: https://historiek.net/een-nieuwe-spelling-invoering-van-de-spelling-marchant-1934/150793/
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1459, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1535, in __extract_info
  File "yt_dlp\extractor\common.py", line 670, in extract
  File "yt_dlp\extractor\generic.py", line 3078, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://historiek.net/een-nieuwe-spelling-invoering-van-de-spelling-marchant-1934/150793/
```

**Comment by october262** [comment]
are you trying to download the 0:50  youtube video near the bottom of the page ??

**Comment by M1Aston** [comment]
Yes, that's the video I was referring to. I was trying to play it using yt-dlp and mpc-be, not download it.

**Comment by october262** [comment]
> Yes, that's the video I was referring to. I was trying to play it using yt-dlp and mpc-be, not download it.

try right clicking on the video, select copy url and then paste it into
your search bar and see if the video will play.

**Comment by eladkarako** [comment]
the website is dynamic,  
it uses iframe with `/embed/` code, yes,    
but it constructs it as the user scrolls down the placeholder into view  
(I.E. lazyloading with viewport intersection).  

I'm pretty sure the generic fallback only searches for complete `/embed/` links in the raw HTML, it is possible to add functionality to render DOM from HTML,  
but it is extra difficult when lazy-loading is triggering the structure of the page.  

for that there is a need to simulate user interaction using selenium,  
and since the website is built with some modern JS, also puppeteer (and headless browser in the background).

<hr/>

right click, copy url, paste it to yt-dlp.  

or use this quick and dirty generic scrapper as a middle-man for yt-dlp:  
https://github.com/eladkarako/nodejs_scrape_for_yt_links

**Comment by M1Aston** [comment]
I'm afraid I don't understand all of that. :-)
If it's just a site-specific issue I apologize for reporting it.
Anyway, there is Copy link option in the video window while the video is playing, so no problem.
