### ISSUE TITLE
How to request a certain ratio, example: 16:9 only?

### ISSUE THREAD

**Issue by romain130492** [yt-dlp/yt-dlp#4814]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.09.01** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Hey,

Im just wondering whether we can specify a certain ratio when request a video, like 16:9
We can do `yt-dlp --format "best[height >=? 1080]" "https://www.newgrounds.com/portal/video/853785"` and request a height, but what about keeping the right ratio ?

thanks

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
Doesn't all formats of a video have same aspect ratio?

**Comment by romain130492** [comment]
> Doesn't all formats of a video have same aspect ratio?

I doubt that

**Comment by pukkandan** [comment]
You "doubt that"??? Check it! Actually, show me output of `yt-dlp -F URL`

**Comment by romain130492** [comment]
> You "doubt that"??? Check it! Actually, show me output of `yt-dlp -F URL`

I thought you were asking a question.... =>  `Doesn't all formats of a video have same aspect ratio?`

**Comment by pukkandan** [comment]
Can be re-opened if you can show `yt-dlp -vF` output of a video with multiple aspect ratios

**Comment by romain130492** [comment]
right I got one here:  https://www.youtube.com/watch?v=3RIp7CwkBeA @pukkandan 
The ratio I'm getting is 2, the width is 3840 and the height 1920.

Here is how I was getting the video: 
```
`yt-dlp -f 'bv[ext=mp4]+ba[ext=m4a]' --merge-output-format mp4  https://www.youtube.com/watch?v=3RIp7CwkBeA -o  '${directory}/${title}.mp4'`
```

**Comment by pukkandan** [comment]
I don't understand. Which format of that video do you want to download?

**Comment by romain130492** [comment]
i want to have a 16:9 ratio. width/height = 16/9 @pukkandan

**Comment by pukkandan** [comment]
But youtube/uploader did not provide the video in 16/9

**Comment by romain130492** [comment]
so you mean, the video uploaded on youtube doesn't have a ratio of 16:9. hence there is no way to download it with that specific ratio.
Yes, in that case, I was expecting to be able to specify to `yt-dlp` the ratio, and get an error as a reponse.

**Comment by pukkandan** [comment]
That is not what you originally asked at all. So what you actually want is for an `aspect_ratio` field in `--match-filter`, correct?

**Comment by darrylrev** [comment]
I just found this thread when trying to find an option to filter by aspect ratio, and I just want to say that I feel like an aspect_ratio filter would be very useful. I've been trying to find a way to do this with current options and it doesn't seem like there is a way.

**Comment by pukkandan** [comment]
In `match-filter`, or in `-f`? If in `-f`, read my above comments. If in match-filter, pls open a new issue

**Comment by darrylrev** [comment]
> In `match-filter`, or in `-f`? If in `-f`, read my above comments. If in match-filter, pls open a new issue

I have made a new issue as requested here: https://github.com/yt-dlp/yt-dlp/issues/5402

Thank you!
