### ISSUE TITLE
Vider.info / vider.pl

### ISSUE THREAD

**Issue by burtek** [yt-dlp/yt-dlp#4815]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.09.01** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Poland

### Example URLs

- Single video: https://vider.info/vid/+fscxen5
- Single video: https://vider.pl/vid/+fscxen5 (available after logging in)
- Playlist (directory): https://vider.info/dir/+dcxv8ns
- Playlist (directory): https://vider.pl/dir/+dcxv8ns (available after logging in)

### Provide a description that is worded well enough to be understood

There are 2 almost equivalent domains: vider.info and vider.pl. The videos, video IDs and paths are the same. The key differences are:

vider.info | vider.pl
-----|-----
Available when unauthorized | Available after logging in
Requires captcha frequently (site with the captcha is returned with 404 code - example below) | Doesn't require captcha
Low download speed | Download speed varies and is higher with paid subscription

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://vider.info/vid/+fscxen5']
[debug] Encodings: locale cp1250, fs utf-8, pref cp1250, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.09.01 [5d7c7d6] (win32_exe)
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.2.3
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1670 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.09.01, Current version: 2022.09.01
yt-dlp is up to date (2022.09.01)
[debug] [generic] Extracting URL: https://vider.info/vid/+fscxen5
[generic] +fscxen5: Downloading webpage
ERROR: [generic] Unable to download webpage: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 670, in extract
  File "yt_dlp\extractor\generic.py", line 2641, in _real_extract
  File "yt_dlp\extractor\common.py", line 821, in _request_webpage

  File "yt_dlp\extractor\common.py", line 803, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 3656, in urlopen
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found
```

**Comment by avikowy** [comment]
![image](https://user-images.githubusercontent.com/57642491/188104080-0203264f-12c8-4998-ade3-b5872bc6cf94.png)
check page source, there is direct link inside, i didnt login, nie mam konta
`<html>
<body>


<link rel="image_src" type="image/png" href="https://img.vider.info/i/s81551/7/3/hit-ukraiski-onierz-przeprasza-polakw-za-uchodcw.png" />
--
  | <link rel="video_src" type="application/x-shockwave-flash" href="https://vider.info/static/player/v58/player.swf?file=https://stream.vider.info/video/356776/v.mp4?uid=0" />


</body>
</html>`

**Comment by pukkandan** [comment]
The example links don't open with a Poland VPN

**Comment by pukkandan** [comment]
And you still get 404 with yt-dlp?

**Comment by frasu** [comment]
Yes, I've got 404.

```
yt-dlp -vU https://vider.info/vid/+fnx1me8
[debug] Command-line config: ['-vU', 'https://vider.info/vid/+fnx1me8']
[debug] Encodings: locale cp65001, fs utf-8, pref cp65001, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2023.01.06 [6becd25] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19044-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 4.4.1-essentials_build-www.gyan.dev (setts), ffprobe 4.4.1-essentials_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.16.0, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1760 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2023.01.06, Current version: 2023.01.06
yt-dlp is up to date (2023.01.06)
[generic] Extracting URL: https://vider.info/vid/+fnx1me8
[generic] +fnx1me8: Downloading webpage
ERROR: [generic] None: Unable to download webpage: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 680, in extract
  File "yt_dlp\extractor\generic.py", line 2384, in _real_extract
  File "yt_dlp\extractor\common.py", line 825, in _request_webpage

  File "yt_dlp\extractor\common.py", line 807, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 3730, in urlopen
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found
```

But when I go to the page and resolve the CAPTCHA first then downloading works.

![image](https://user-images.githubusercontent.com/27282101/217385653-1a36ee04-0fbf-4f3b-ae7c-54ad9afe7dcb.png)

```
yt-dlp -vU https://vider.info/vid/+fnx1me8
[debug] Command-line config: ['-vU', 'https://vider.info/vid/+fnx1me8']
[debug] Encodings: locale cp65001, fs utf-8, pref cp65001, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2023.01.06 [6becd25] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19044-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 4.4.1-essentials_build-www.gyan.dev (setts), ffprobe 4.4.1-essentials_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.16.0, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1760 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2023.01.06, Current version: 2023.01.06
yt-dlp is up to date (2023.01.06)
[generic] Extracting URL: https://vider.info/vid/+fnx1me8
[generic] +fnx1me8: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] +fnx1me8: Extracting information
[debug] Looking for embeds
[debug] Identified a video file
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] v: Downloading 1 format(s): 0
[debug] Invoking http downloader on "https://stream.vider.info/video/126045/v.mp4?uid=0"
[debug] File locking is not supported. Proceeding without locking
[download] Destination: Sailor Moon R 047 Powrót Czarodziejek Lektor PL [DVD] [v].mp4
[download] 100% of  139.91MiB in 00:11:47 at 202.53KiB/s
```

And the same story is with the freedisc.pl (vider.info and freedisc.pl are on the same IP: 185.16.37.206)

So these websites conditionally work.

**Comment by bashonly** [comment]
Seems like completing the captcha challenge will whitelist your IP (temporarily? only for that specific video?)

If the generic extractor can download after solving the captcha, is an extractor even needed? It's not like yt-dlp will be able to solve the captchas for you

Has anyone tested passing logged-in cookies when trying to download a vider.pl URL?

**Comment by frasu** [comment]
> Seems like completing the captcha challenge will whitelist your IP (temporarily? only for that specific video?)

I think temporarily. Good to download a couple of videos.

> If the generic extractor can download after solving the captcha, is a dedicated extractor even needed? It's not like yt-dlp will be able to solve the captchas for you

I get it. Thanks.

> Has anyone tested passing logged-in cookies when trying to download a vider.pl URL?

I've tried the `--cookies` parameter with a file extracted from the `cookies.txt` extension but with no luck.

```
yt-dlp -v --cookies cookies.txt https://vider.pl/vid/+fnx11xe
[debug] Command-line config: ['-v', '--cookies', 'cookies.txt', 'https://vider.pl/vid/+fnx11xe']
[debug] Encodings: locale cp65001, fs utf-8, pref cp65001, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2023.01.06 [6becd25] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19044-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 4.4.1-essentials_build-www.gyan.dev (setts), ffprobe 4.4.1-essentials_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.16.0, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1760 extractors
[generic] Extracting URL: https://vider.pl/vid/+fnx11xe
[generic] +fnx11xe: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] +fnx11xe: Extracting information
[debug] Looking for embeds
[debug] Identified a html5 embed
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] +fnx11xe-1: Downloading 1 format(s): 0
[debug] Invoking http downloader on "https://vider.pl/static/multimedia/alert.mp3"
[download] Vider.info (1) [+fnx11xe-1].mp3 has already been downloaded
[download] 100% of   46.12KiB
```
Instead of a proper video file, I've received some `alert.mp3`. Should I try a different cookie extractor? Or a different parameter (don't know how to use `--cookies-from-browser`)? Or the website has some blocking mechanism to prevent such behavior?
