### ISSUE TITLE
Japanese text prevents program from running

### ISSUE THREAD

**Issue by shimizurei** [yt-dlp/yt-dlp#4824]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.09.01** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

The program seems to have a problem with some Japanese text. I could not run my code until I removed the lines `--match-filter "title*=あんさんぶるスターズ！！ Music"` and `# あんスタチャンネル`. I had to use `--match-filter "title *= MV"` to get the file to work. I updated to the latest version before starting the DL. My document is saved in UTF-8.

#### My Code

```
# Path
-o "\\\REDACTEDHERE!\Media\Videos, Other\YouTube\%(uploader)s [%(channel_id)s]\%(title)s [%(upload_date)s].%(ext)s"

# Archive Settings
--download-archive "~/FULLREDACTED!!!/ydl/archives/youtube-channels-dl-archive.txt"

# Get Just MVs
--match-filter "title*=あんさんぶるスターズ！！ Music"
#--match-title "SPECIAL MV"
#--match-title "ゲームサイズMV" 

# Quality/Audio/Video Formats
-S 'res:1080,codec:vp9.2:aac,br'

# Uniform Format: MKV
--merge-output-format mkv

# Get All Subs to SRT and embed them
--sub-langs all
--write-sub
--embed-subs
--convert-subs srt
#--convert-subs lrc #lyric file for MVs
# --sub-format srt

# Get metadata
--add-metadata
--write-info-json

# Get thumbnail
--write-thumbnail

# Continue when download errors are encountered
--ignore-errors

# Start partially downloaded files from the beginning
--no-continue

# Don't overwrite existing files
--no-overwrites

# Some hosting and VPNs providers don't support IPv6
# --force-ipv4

# Bypass HTTPS Cerificates
--no-check-certificate

# Debug
--verbose

# あんスタチャンネル
https://www.youtube.com/channel/UCuxfK38dUXj6oY_L4JjTCkA/videos
```

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp -vU --config-location "C:\Users\ME...REDACTED\ydl\confs\youtube-channels-dl-TEST.conf.txt"

Usage: yt-dlp [OPTIONS] URL [URL...]

yt-dlp: error: Unable to parse "C:\Users\ME...REDACTED\ydl\confs\youtube-channels-dl-TEST.conf.txt": 'charmap' codec can't decode byte 0x81 in position 274: character maps to <undefined>

(I then remove the first problematic line)

Usage: yt-dlp [OPTIONS] URL [URL...]

yt-dlp: error: Unable to parse "C:\Users\ME...REDACTED\ydl\confs\youtube-channels-dl-TEST.conf.txt": 'charmap' codec can't decode byte 0x81 in position 1039: character maps to <undefined>
```

**Comment by Lesmiscore** [comment]
Add `# coding: utf-8` as the first line of config files to make it work

**Comment by pukkandan** [comment]
https://github.com/yt-dlp/yt-dlp#config-file-encoding

**Comment by shimizurei** [comment]
Interesting. I never had this issue with the previous YouTube-DL, according to the other config file I haven't run since last year.

Also, in Notepad, you can do "Save As" and change the encoding to "UTF-8 with BOM" and it seems like it fixes the issue as well.
