### ISSUE TITLE
Having multiple YoutubeDL objects open simultaneously

### ISSUE THREAD

**Issue by emphoeller** [yt-dlp/yt-dlp#4826]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.09.01** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Instances of the `YoutubeDL` class are supposed to be used with a context manager:

```python
with YoutubeDL(opts) as ydl:
  ... # do stuff with ydl
```

I have looked at (though not fully understood) the `__enter__()` and `__exit__()` code. `__exit__()` saves cookies to a file if one is explicitly specified, which I don’t. Is there anything else I need to worry about or is it okay for me to do the following?

```python
with YoutubeDL(opts1) as ydl1, YoutubeDL(opts2) as ydl2:
  ...
```

To make clear why this is concerning me: The code might make the assumption that only one `YoutubeDL` object is open at a time, like the cookie file code probably does, and produce erroneous behavior if that is not the case and the multiple instances “interfere with each other.”

I want to do things this way because constructing a `YoutubeDL` instance is runtime-intensive, so I would like to to avoid doing that each time I switch between options.

I am using `{"cachedir": False}` as part of both `opts` in case that matters.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
As far as I know, it should be fine. But this use-case is not well tested, so I can't be 100% sure. If you find any issues, let me know and we can fix it

**Comment by emphoeller** [comment]
I just thought of this: Would it maybe be better to `__enter__()` and `__exit__()` the same instance multiple times? Is that supported?

**Comment by pukkandan** [comment]
Sure, but why though?

**Comment by emphoeller** [comment]
I want to do alternating downloads with different options.

Naive approach:

```python
for url in urls:
  with YoutubeDL(opts1) as ydl1:
    ydl1.download(url)
  with YoutubeDL(opts2) as ydl2:
    ydl2.download(url)
```

This loses a lot of time on the `YoutubeDL` constructor calls.

Parallel `__enter__()` approach:

```python
with YoutubeDL(opts1) as ydl1, YoutubeDL(opts2) as ydl2:
  for url in urls:
    ydl1.download(url)
    ydl2.download(url)
```

This saves the repeated constructor calls, but might run into problems if `__enter__()`ing another `YoutubeDL` object before `__exit__()`ing the first was not accounted for somewhere in the code.

Repeated `__enter__()` approach:

```python
ydl1 = YoutubeDL(opts1)
ydl2 = YoutubeDL(opts2)
for url in urls:
  with ydl1:
    ydl1.download(url)
  with ydl2:
    ydl2.download(url)
```

This sidesteps both of the above issues, but requires that we can `__enter__()` the same `YoutubeDL` object again after `__exit__()`ing it (which is not the case for, say, streams).

**Comment by pukkandan** [comment]
Do the two classes share any common resources? The same cookie file, for example. If not, all of these should work

**Comment by emphoeller** [comment]
At least I don’t explicitly specify any. Are there some by default? The cache, for instance?

**Comment by pukkandan** [comment]
No. Cache files are open and closed as required. Since your code isn't multithreaded, it is fine
