### ISSUE TITLE
Where does yt-dlp look for PhantomJS?

### ISSUE THREAD

**Issue by someziggyman** [yt-dlp/yt-dlp#4837]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.09.01** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I apologies if this one is obvious:

So, I installed PhantomJS via Brew on my macOS and yt-dlp works great with it. 

However, I sometimes use yt-dlp as a portable solution, so was wondering if PhantomJS path can somehow be specified? Is there a way? 
maybe via some config file? 
or maybe I can edit something in code for yt-dlp to just look for PhantomJS binary in the same folder as yt-dlp binary? 
Any advice is appreciated.  

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
not needed in this case
```

**Comment by pukkandan** [comment]
It is only searched for in `PATH`

**Comment by ForsakenRei** [comment]
Does User PATH or System `PATH` matter? 
It seems it cannot find phantomjs in user `PATH` but `phantomjs` works in Terminal already.

**Comment by pukkandan** [comment]
Show log

**Comment by ForsakenRei** [comment]
yt-dlp -v output
> yt-dlp -v https://www.youtube.com/watch?v=YsYvFTj025w -f bv+ba --remux-video mp4 --embed-thumbnail -o "%(uploader)s_%(upload_date)s_%(title)s_%(id)s.%(ext)s"
[debug] Command-line config: ['-v', 'https://www.youtube.com/watch?v=YsYvFTj025w', '-f', 'bv+ba', '--remux-video', 'mp4', '--embed-thumbnail', '-o', '%(uploader)s_%(upload_date)s_%(title)s_%(id)s.%(ext)s']
[debug] Encodings: locale cp65001, fs utf-8, pref cp65001, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.08.19 [48c88e0] (win32_exe)
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 2022-08-18-git-48be6616d0-essentials_build-www.gyan.dev (setts), ffprobe 2022-08-18-git-48be6616d0-essentials_build-www.gyan.dev, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=YsYvFTj025w
[youtube] YsYvFTj025w: Downloading webpage
[youtube] YsYvFTj025w: Downloading android player API JSON
[youtube] YsYvFTj025w: Downloading player c16db54a
WARNING: [youtube] YsYvFTj025w: nsig extraction failed: You may experience throttling for some formats
         Install PhantomJS to workaround the issue
         n = PJ7J5Y5HK7pR7SH ; player = https://www.youtube.com/s/player/c16db54a/player_ias.vflset/en_US/base.js
[debug] [youtube] No terminating paren } in: {var b=a.split(""),c=[1177998807,null,-59410018...lick=function(){this.G.Pa("onExpandMiniplayer")};}; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[info] YsYvFTj025w: Downloading 1 format(s): 303+251
[info] Downloading video thumbnail 44 ...
[info] Writing video thumbnail 44 to: るるどらいおん_20220905_カプとれやってみる_YsYvFTj025w.webp
WARNING: webm doesn't support embedding a thumbnail, mkv will be used
[debug] Invoking http downloader on "https://rr1---sn-jvhj5nu-2iae.googlevideo.com/videoplayback?expire=1662497834&ei=yl8XY9bFN7eQhwbjy7HQBg&ip=68.81.32.58&id=o-ADEQNp9_NZXB5HTbrKDnMEbKB9nBQGEYL8gZQ4Szjr5C&itag=303&source=youtube&requiressl=yes&mh=Wa&mm=31%2C29&mn=sn-jvhj5nu-2iae%2Csn-ab5sznzl&ms=au%2Crdu&mv=m&mvi=1&pl=22&initcwndbps=1582500&spc=lT-KhtW4J3SmBIw3LPN_Ab0aEBrvi1c&vprv=1&svpuc=1&mime=video%2Fwebm&gir=yes&clen=1026749046&dur=5026.053&lmt=1662419424342297&mt=1662475753&fvip=5&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&rbqsm=fr&txp=5437434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIhAM0r5RdxFi-GBFl1yTIqTafQ4bSSfXiOYBKbtG2bq1i_AiBBxF02Hgk42KqvlvZk59jbUj5YCVefB5kVTEQogMyEGg%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgWQXiDiqt34teUpKviFvsN1P8On9VrakztV8NWHdFf6gCIQDmWr-OCeyJmcKD2uxolsqCX7_tksKlqiT0Usj98VWo2g%3D%3D"
[debug] File locking is not supported. Proceeding without locking
[download] Destination: るるどらいおん_20220905_カプとれやってみる_YsYvFTj025w.f303.webm
[download] 100% of 979.18MiB in 00:39 at 24.75MiB/s
[debug] Invoking http downloader on "https://rr1---sn-jvhj5nu-2iae.googlevideo.com/videoplayback?expire=1662497834&ei=yl8XY9bFN7eQhwbjy7HQBg&ip=68.81.32.58&id=o-ADEQNp9_NZXB5HTbrKDnMEbKB9nBQGEYL8gZQ4Szjr5C&itag=251&source=youtube&requiressl=yes&mh=Wa&mm=31%2C29&mn=sn-jvhj5nu-2iae%2Csn-ab5sznzl&ms=au%2Crdu&mv=m&mvi=1&pl=22&initcwndbps=1582500&spc=lT-KhtW4J3SmBIw3LPN_Ab0aEBrvi1c&vprv=1&svpuc=1&mime=audio%2Fwebm&gir=yes&clen=78777947&dur=5026.081&lmt=1662415823351959&mt=1662475753&fvip=5&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&rbqsm=fr&txp=5432434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIgPAnYC_RgpXEL1SRCYmwzNBd09_Vqa7wPmAJ5Xs_fjkoCIQC5AtrKh4iHdRPbhMB-BvH0wueZqrsQ-KnIHBpu7kfSYw%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgWQXiDiqt34teUpKviFvsN1P8On9VrakztV8NWHdFf6gCIQDmWr-OCeyJmcKD2uxolsqCX7_tksKlqiT0Usj98VWo2g%3D%3D"
[download] Destination: るるどらいおん_20220905_カプとれやってみる_YsYvFTj025w.f251.webm
[download] 100% of 75.13MiB in 00:02 at 26.01MiB/s
[Merger] Merging formats into "るるどらいおん_20220905_カプとれやってみる_YsYvFTj025w.mkv"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:るるどらいおん_20220905_カプとれやってみる_YsYvFTj025w.f303.webm" -i "file:るるどらいおん_20220905_カプとれやってみる_YsYvFTj025w.f251.webm" -c copy -map "0:v:0" -map "1:a:0" -movflags "+faststart" "file:るるどらいおん_20220905_カプとれやってみる_YsYvFTj025w.temp.mkv"
Deleting original file るるどらいおん_20220905_カプとれやってみる_YsYvFTj025w.f303.webm (pass -k to keep)
Deleting original file るるどらいおん_20220905_カプとれやってみる_YsYvFTj025w.f251.webm (pass -k to keep)
[VideoRemuxer] Remuxing video from mkv to mp4; Destination: るるどらいおん_20220905_カプとれやってみる_YsYvFTj025w.mp4
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:るるどらいおん_20220905_カプとれやってみる_YsYvFTj025w.mkv" -map 0 -dn -ignore_unknown -c copy -movflags "+faststart" "file:るるどらいおん_20220905_カプとれやってみる_YsYvFTj025w.mp4"
Deleting original file るるどらいおん_20220905_カプとれやってみる_YsYvFTj025w.mkv (pass -k to keep)
[ThumbnailsConvertor] Converting thumbnail "るるどらいおん_20220905_カプとれやってみる_YsYvFTj025w.webp" to png
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -f image2 -pattern_type none -i "file:るるどらいおん_20220905_カプとれやってみる_YsYvFTj025w.webp" -movflags "+faststart" "file:るるどらいおん_20220905_カプとれやってみる_YsYvFTj025w.png"
[EmbedThumbnail] mutagen: Adding thumbnail to "るるどらいおん_20220905_カプとれやってみる_YsYvFTj025w.mp4"

Output for phantomjs:
>F:\>where phantomjs
C:\Tools\phantomjs\bin\phantomjs.exe

Note that I only added a new entry for phatomjs in user `PATH` but not in the system `PATH`.

**Comment by pukkandan** [comment]
Update yt-dlp!

**Comment by Abhinav-Bahuguna** [comment]
sudo apt-get update
sudo apt-get install build-essential chrpath libssl-dev libxft-dev -y
sudo apt-get install libfreetype6 libfreetype6-dev -y
sudo apt-get install libfontconfig1 libfontconfig1-dev -y
cd ~
export PHANTOM_JS="phantomjs-2.1.1-linux-x86_64"
wget https://github.com/Medium/phantomjs/releases/download/v2.1.1/$PHANTOM_JS.tar.bz2
sudo tar xvjf $PHANTOM_JS.tar.bz2
sudo mv $PHANTOM_JS /usr/local/share
sudo ln -sf /usr/local/share/$PHANTOM_JS/bin/phantomjs /usr/local/bin
phantomjs --version

This one worked for me!!

**Comment by slycordinator** [comment]
> 

The downloads from https://phantomjs.org/download.html for linux could be preferable, as they are statically built with no need for development libraries.

sudo apt-get update
sudo apt-get install libc6 libfontconfig1 libfreetype6 libgcc-s1 libstdc++6 zlib1g
cd ~
export PHANTOM_JS='phantomjs-2.1.1-linux-x86_64'
wget https://bitbucket.org/ariya/phantomjs/downloads/$PHANTOM_JS.tar.bz2
sudo tar xvjf $PHANTOM_JS.tar.bz2
sudo mv $PHANTOM_JS /usr/local/share
sudo ln -sf /usr/local/share/$PHANTOM_JS/bin/phantomjs /usr/local/bin
phantomjs --version

**Comment by life777eternal** [comment]
Tried to download a youtube video and found out about that phantomjs.

``` 
> yt-dlp.exe https://www.youtube.com/watch?v=dkE4VSr9x_I
[youtube] Extracting URL: https://www.youtube.com/watch?v=dkE4VSr9x_I
[youtube] dkE4VSr9x_I: Downloading webpage
[youtube] dkE4VSr9x_I: Downloading tv client config
[youtube] dkE4VSr9x_I: Downloading player 9a279502
[youtube] dkE4VSr9x_I: Downloading tv player API JSON
[youtube] dkE4VSr9x_I: Downloading ios player API JSON
WARNING: [youtube] dkE4VSr9x_I: nsig extraction failed: Some formats may be missing
         Install PhantomJS to workaround the issue. Please download it from https://phantomjs.org/download.html
         n = J-TB6JnOXlaJJY_1o ; player = https://www.youtube.com/s/player/9a279502/player_ias.vflset/en_US/base.js
WARNING: [youtube] dkE4VSr9x_I: nsig extraction failed: Some formats may be missing
         Install PhantomJS to workaround the issue. Please download it from https://phantomjs.org/download.html
         n = mkLyvCU5EqAnXEtdd ; player = https://www.youtube.com/s/player/9a279502/player_ias.vflset/en_US/base.js
WARNING: [youtube] dkE4VSr9x_I: nsig extraction failed: Some formats may be missing
         Install PhantomJS to workaround the issue. Please download it from https://phantomjs.org/download.html
         n = Nj8dkMu1WE1C7Dcf0 ; player = https://www.youtube.com/s/player/9a279502/player_ias.vflset/en_US/base.js
WARNING: [youtube] dkE4VSr9x_I: nsig extraction failed: Some formats may be missing
         Install PhantomJS to workaround the issue. Please download it from https://phantomjs.org/download.html
         n = Onv39ebiOx1edf1-U ; player = https://www.youtube.com/s/player/9a279502/player_ias.vflset/en_US/base.js
[youtube] dkE4VSr9x_I: Downloading m3u8 information
[info] Testing format 270
[info] Testing format 234
[info] dkE4VSr9x_I: Downloading 1 format(s): 270+234
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 50
[download] Destination: Flat Earth： A Biblical Perspective (With Russianvids) [dkE4VSr9x_I].f270.mp4
[download] 100% of   26.05MiB in 00:00:21 at 1.21MiB/s
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 50
[download] Destination: Flat Earth： A Biblical Perspective (With Russianvids) [dkE4VSr9x_I].f234.mp4
[download] 100% of    3.80MiB in 00:00:11 at 343.98KiB/s
[Merger] Merging formats into "Flat Earth： A Biblical Perspective (With Russianvids) [dkE4VSr9x_I].mp4"
Deleting original file Flat Earth： A Biblical Perspective (With Russianvids) [dkE4VSr9x_I].f270.mp4 (pass -k to keep)
Deleting original file Flat Earth： A Biblical Perspective (With Russianvids) [dkE4VSr9x_I].f234.mp4 (pass -k to keep)
```

After I downloaded phantomjs and copied it to the same folder as yt-dlp, it still showed the warning. 

``` 
> yt-dlp.exe https://www.youtube.com/watch?v=dkE4VSr9x_I
[youtube] Extracting URL: https://www.youtube.com/watch?v=dkE4VSr9x_I
[youtube] dkE4VSr9x_I: Downloading webpage
[youtube] dkE4VSr9x_I: Downloading tv client config
[youtube] dkE4VSr9x_I: Downloading player 9a279502
[youtube] dkE4VSr9x_I: Downloading tv player API JSON
[youtube] dkE4VSr9x_I: Downloading ios player API JSON
WARNING: [youtube] dkE4VSr9x_I: Native nsig extraction failed: Trying with PhantomJS
         n = DeWIdJGBYne0bmczm ; player = https://www.youtube.com/s/player/9a279502/player_ias.vflset/en_US/base.js
[youtube] dkE4VSr9x_I: Executing signature code
WARNING: [youtube] dkE4VSr9x_I: nsig extraction failed: Some formats may be missing
         n = DeWIdJGBYne0bmczm ; player = https://www.youtube.com/s/player/9a279502/player_ias.vflset/en_US/base.js
WARNING: [youtube] dkE4VSr9x_I: Native nsig extraction failed: Trying with PhantomJS
         n = _jkIoENS9FWPB_jhN ; player = https://www.youtube.com/s/player/9a279502/player_ias.vflset/en_US/base.js
[youtube] dkE4VSr9x_I: Executing signature code
WARNING: [youtube] dkE4VSr9x_I: nsig extraction failed: Some formats may be missing
         n = _jkIoENS9FWPB_jhN ; player = https://www.youtube.com/s/player/9a279502/player_ias.vflset/en_US/base.js
WARNING: [youtube] dkE4VSr9x_I: Native nsig extraction failed: Trying with PhantomJS
         n = caSGQ6-iEw0dLNFLC ; player = https://www.youtube.com/s/player/9a279502/player_ias.vflset/en_US/base.js
[youtube] dkE4VSr9x_I: Executing signature code
WARNING: [youtube] dkE4VSr9x_I: nsig extraction failed: Some formats may be missing
         n = caSGQ6-iEw0dLNFLC ; player = https://www.youtube.com/s/player/9a279502/player_ias.vflset/en_US/base.js
WARNING: [youtube] dkE4VSr9x_I: Native nsig extraction failed: Trying with PhantomJS
         n = YqX2mo85gN7HjrXnV ; player = https://www.youtube.com/s/player/9a279502/player_ias.vflset/en_US/base.js
[youtube] dkE4VSr9x_I: Executing signature code
WARNING: [youtube] dkE4VSr9x_I: nsig extraction failed: Some formats may be missing
         n = YqX2mo85gN7HjrXnV ; player = https://www.youtube.com/s/player/9a279502/player_ias.vflset/en_US/base.js
[youtube] dkE4VSr9x_I: Downloading m3u8 information
[info] Testing format 270
[info] Testing format 234
[info] dkE4VSr9x_I: Downloading 1 format(s): 270+234
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 50
[download] Destination: Flat Earth： A Biblical Perspective (With Russianvids) [dkE4VSr9x_I].f270.mp4
[download] 100% of   26.05MiB in 00:00:10 at 2.49MiB/s
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 50
[download] Destination: Flat Earth： A Biblical Perspective (With Russianvids) [dkE4VSr9x_I].f234.mp4
[download] 100% of    3.80MiB in 00:00:04 at 951.17KiB/s
[Merger] Merging formats into "Flat Earth： A Biblical Perspective (With Russianvids) [dkE4VSr9x_I].mp4"
Deleting original file Flat Earth： A Biblical Perspective (With Russianvids) [dkE4VSr9x_I].f234.mp4 (pass -k to keep)
Deleting original file Flat Earth： A Biblical Perspective (With Russianvids) [dkE4VSr9x_I].f270.mp4 (pass -k to keep)
```

Thank you, Shalom.
