### ISSUE TITLE
yt-dlp windows

### ISSUE THREAD

**Issue by IoanPaleru** [yt-dlp/yt-dlp#484]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

Hi. Where do I download yt-dlp as an already compiled windows program that I can use to download youtube videos? Do I also have to install python or can I just use yt-dlp without installing any extra software? I don't know how to compile a windows executable from source code. How do I use yt-dlp with windows without having to compile or install anything extra? Thanks.

WRITE QUESTION HERE

**Comment by llacb47** [comment]
`https://github.com/yt-dlp/yt-dlp/releases/latest` click `yt-dlp.exe`

**Comment by pukkandan** [comment]
Also, here's the direct link: https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp.exe
