### ISSUE TITLE
[Site support request] filemoon.sx

### ISSUE THREAD

**Issue by Testacda** [yt-dlp/yt-dlp#4848]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.09.01** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

United States

### Example URLs

Single video:

https://filemoon.sx/d/0fxcyc2ajhp1/GNOME_POWER.mp4
https://filemoon.sx/e/0fxcyc2ajhp1/GNOME_POWER.mp4

### Provide a description that is worded well enough to be understood

A place where people can upload videos and share them, like other video sharing websites.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://filemoon.sx/d/0fxcyc2ajhp1/GNOME_POWER.mp4']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.09.01 [5d7c7d6] (zip)
[debug] Python 3.8.10 (CPython 64bit) - Linux-5.15.57.1-microsoft-standard-WSL2-x86_64-with-glibc2.29 (glibc 2.31)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.2.7, ffprobe 4.2.7, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, pyxattr-0.6.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1670 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.09.01, Current version: 2022.09.01
yt-dlp is up to date (2022.09.01)
[debug] [generic] Extracting URL: https://filemoon.sx/d/0fxcyc2ajhp1/GNOME_POWER.mp4
[generic] GNOME_POWER: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] GNOME_POWER: Extracting information
[debug] Looking for Brightcove embeds
[debug] Looking for embeds
ERROR: Unsupported URL: https://filemoon.sx/d/0fxcyc2ajhp1/GNOME_POWER.mp4
Traceback (most recent call last):
  File "./yt-dlp/yt_dlp/YoutubeDL.py", line 1459, in wrapper
    return func(self, *args, **kwargs)
  File "./yt-dlp/yt_dlp/YoutubeDL.py", line 1535, in __extract_info
    ie_result = ie.extract(url)
  File "./yt-dlp/yt_dlp/extractor/common.py", line 670, in extract
    ie_result = self._real_extract(url)
  File "./yt-dlp/yt_dlp/extractor/generic.py", line 3078, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://filemoon.sx/d/0fxcyc2ajhp1/GNOME_POWER.mp4
```

**Comment by dirkf** [comment]
The input data for JWPlayer is encoded in self-decoding JS `eval(function(p,a,c,k,e,d){...}(...))`, for which we have a decoder in `utils.py`. There was a .m3u8 manifest in the one I checked.

**Comment by Testacda** [comment]
> 

I have tried downloading the with the m3u8 manifest one in the JS, but for me I I get "Unable to download webpage: HTTP Error 403: Forbidden", also tried --force-generic-extractor with it (something I saw on reddit) but that also didn't work. Unless you mean something else.

**Comment by dirkf** [comment]
Looking at https://filemoon.sx/d/0fxcyc2ajhp1/GNOME_POWER.mp4, with JS enabled for filemoon.sx and moon-storage-delivery-s01.filemoon.to, the browser requests like this:
```
GET /hls2/01/00076/0fxcyc2ajhp1_x/master.m3u8?t=m1UTtOjh0B8kzsjEbcMCWGZfj0xNt-4L07TT3tXKFG8&s=1662679183&e=43200&f=383371&srv=127.0.0.1&asn=6871&sp=2048 HTTP/1.1
Host: moon-storage-delivery-s01.filemoon.to
...
Referer: https://filemoon.sx/d/0fxcyc2ajhp1/GNOME_POWER.mp4
```
Try using `--referer "https://filemoon.sx/d/0fxcyc2ajhp1/GNOME_POWER.mp4"` (vary according to the page.

There's also this download link (presumably time-limited):
```
https://moon-storage-delivery-s01.filemoon.to/getttrwlu6iku47mq6j3ozofu5i2rdw6idozllesyfzvein7vdxmwlwpxbhq/GNOME_POWER.mp4
```

**Comment by Testacda** [comment]
I was able to download the file by grabbing the link from the button button and using `--referer "https://filemoon.sx/d/0fxcyc2ajhp1/GNOME_POWER.mp4"` but that is locked behind a captcha, currently I'm looking for a way without doing that if possible.

**Comment by Vangelis66** [comment]
> There's also this download link (presumably time-limited):

When I tried this over here, it produced: 

`error_wrong_ip`

so it must also be bound to a specific (**dirkf**'s in that case) **requesting IP address** 😞 ; presumably, the string `getttrwlu6iku47mq6j3ozofu5i2rdw6idozllesyfzvein7vdxmwlwpxbhq` has that encoded in, but a simple "base64 decode" got me nowhere...

**Comment by atgarcia78** [comment]
Im able to extract the video format with this simplified extractor code:

```
from .common import InfoExtractor
from ..utils import decode_packed_codes, try_get


class FilemoonIE(InfoExtractor):
    _VALID_URL = r'https?://filemoon\.sx/[e,d]/(?P<id>[^\/$]+)' 
    _SITE_URL = 'https://filemoon.sx'

    def _real_extract(self, url):
        videoid = self._match_id(url)
        _url = f"{self._SITE_URL}/d/{videoid}"
        webpage = try_get(ie._download_webpage(_url, videoid), lambda x: re.sub('[\t\n]', '', x))
        packed = self._search_regex(r'<script data-cfasync=[^>]+>eval\((.+)\)</script>', webpage, 'packed code')
        unpacked = decode_packed_codes(packed)
        m3u8_url = try_get(re.search(r'file:"(?P<url>[^"]+)"', unpacked), lambda x: x.group('url'))        
        formats = self._extract_m3u8_formats(m3u8_url, videoid, ext="mp4", entry_protocol='m3u8_native', m3u8_id="hls"
        title = self._html_extract_title(webpage)
        return {
            'id': videoid,
            'title': title,
            'formats': formats,
            'ext': 'mp4'
        }
```

Verbose output for: yt-dlp -j -v https://filemoon.sx/d/0fxcyc2ajhp1/GNOME_POWER.mp4

```
[debug] Command-line config: ['-o', '/testing/20220910/%(id)s_%(title)s.%(ext)s', '-j', '-v', 'https://filemoon.sx/d/0fxcyc2ajhp1/GNOME_POWER.mp4']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.09.01 [5d7c7d656]
[debug] Lazy loading extractors is disabled
[debug] Python 3.9.9 (CPython 64bit) - macOS-12.5.1-arm64-arm-64bit
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 5.1.1 (setts), ffprobe 5.1.1, phantomjs 2.1.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, secretstorage-3.3.3, sqlite3-2.6.0, websockets-10.3, xattr-0.9.9
[debug] Proxy map: {}
[debug] Loaded 1776 extractors
[debug] [filemoon] Extracting URL: https://filemoon.sx/d/0fxcyc2ajhp1/GNOME_POWER.mp4
[filemoon] https://filemoon.sx/d/0fxcyc2ajhp1/GNOME_POWER.mp4: Extracting information
[debug][filemoon][send_req] https://filemoon.sx//d/0fxcyc2ajhp1
[debug][filemoon][send_http_request][https://filemoon.sx//d/0fxcyc2ajhp1][GET] <Response [200 OK]>:
[filemoon] 0fxcyc2ajhp1: Downloading m3u8 information
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 0fxcyc2ajhp1: Downloading 1 format(s): hls-1870
{"id": "0fxcyc2ajhp1", "title": "GNOME_POWER", "formats": [{"format_id": "hls-1870", "format_index": null, "url": "https://moon-storage-delivery-s01.filemoon.to/hls2/01/00076/0fxcyc2ajhp1_x/index-v1-a1.m3u8?t=Ju_xAOXH6yjd054yVrrGIQ7XgKeA1xnFpW-LsWhKnGU&s=1662766462&e=43200&f=383371&srv=127.0.0.1&asn=15704&sp=2048", "manifest_url": "https://moon-storage-delivery-s01.filemoon.to/hls2/01/00076/0fxcyc2ajhp1_x/master.m3u8?t=Ju_xAOXH6yjd054yVrrGIQ7XgKeA1xnFpW-LsWhKnGU&s=1662766462&e=43200&f=383371&srv=127.0.0.1&asn=15704&sp=2048", "tbr": 1870.591, "ext": "mp4", "fps": 29.97, "protocol": "m3u8_native", "preference": null, "quality": null, "width": 1280, "height": 720, "vcodec": "avc1.4d401f", "acodec": "mp4a.40.2", "dynamic_range": "SDR", "video_ext": "mp4", "audio_ext": "none", "vbr": 1870.591, "abr": 0.0, "http_headers": {"User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:104.0) Gecko/20100101 Firefox/104.0", "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8", "Accept-Language": "en,es-ES;q=0.5", "Sec-Fetch-Mode": "navigate", "Accept-Encoding": "gzip,deflate", "Referer": "https://filemoon.sx/", "Origin": "https://filemoon.sx"}, "format": "hls-1870 - 1280x720", "resolution": "1280x720"}], "webpage_url": "https://filemoon.sx//d/0fxcyc2ajhp1", "ext": "mp4", "original_url": "https://filemoon.sx/d/0fxcyc2ajhp1/GNOME_POWER.mp4", "webpage_url_basename": "0fxcyc2ajhp1", "webpage_url_domain": "filemoon.sx", "extractor": "filemoon", "extractor_key": "Filemoon", "playlist": null, "playlist_index": null, "display_id": "0fxcyc2ajhp1", "fulltitle": "GNOME_POWER", "requested_subtitles": null, "_has_drm": null, "format_id": "hls-1870", "format_index": null, "url": "https://moon-storage-delivery-s01.filemoon.to/hls2/01/00076/0fxcyc2ajhp1_x/index-v1-a1.m3u8?t=Ju_xAOXH6yjd054yVrrGIQ7XgKeA1xnFpW-LsWhKnGU&s=1662766462&e=43200&f=383371&srv=127.0.0.1&asn=15704&sp=2048", "manifest_url": "https://moon-storage-delivery-s01.filemoon.to/hls2/01/00076/0fxcyc2ajhp1_x/master.m3u8?t=Ju_xAOXH6yjd054yVrrGIQ7XgKeA1xnFpW-LsWhKnGU&s=1662766462&e=43200&f=383371&srv=127.0.0.1&asn=15704&sp=2048", "tbr": 1870.591, "fps": 29.97, "protocol": "m3u8_native", "preference": null, "quality": null, "width": 1280, "height": 720, "vcodec": "avc1.4d401f", "acodec": "mp4a.40.2", "dynamic_range": "SDR", "video_ext": "mp4", "audio_ext": "none", "vbr": 1870.591, "abr": 0.0, "http_headers": {"User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:104.0) Gecko/20100101 Firefox/104.0", "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8", "Accept-Language": "en,es-ES;q=0.5", "Sec-Fetch-Mode": "navigate", "Accept-Encoding": "gzip,deflate", "Referer": "https://filemoon.sx/", "Origin": "https://filemoon.sx"}, "format": "hls-1870 - 1280x720", "resolution": "1280x720", "epoch": 1662766463, "_filename": "/testing/20220910/0fxcyc2ajhp1_GNOME_POWER.mp4", "filename": "/testing/20220910/0fxcyc2ajhp1_GNOME_POWER.mp4", "urls": "https://moon-storage-delivery-s01.filemoon.to/hls2/01/00076/0fxcyc2ajhp1_x/index-v1-a1.m3u8?t=Ju_xAOXH6yjd054yVrrGIQ7XgKeA1xnFpW-LsWhKnGU&s=1662766462&e=43200&f=383371&srv=127.0.0.1&asn=15704&sp=2048", "_type": "video", "_version": {"version": "2022.09.01", "current_git_head": null, "release_git_head": "5d7c7d656", "repository": "yt-dlp/yt-dlp"}}
```

**Comment by pukkandan** [comment]
It looks to me like the site is primarily for piracy. They don't even appear to have a "report content" link. If you have reason to believe otherwise, let me know

**Comment by XdekHckr** [comment]
> ### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE
> * [x]  I understand that I will be **blocked** if I remove or skip any mandatory* field
> 
> ### Checklist
> * [x]  I'm reporting a new site support request
> * [x]  I've verified that I'm running yt-dlp version **2022.09.01** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
> * [x]  I've checked that all provided URLs are playable in a browser with the same IP and same login details
> * [x]  I've checked that none of provided URLs [violate any copyrights](https://github.com/ytdl-org/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
> * [x]  I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
> * [x]  I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
> * [x]  I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required
> 
> ### Region
> United States
> 
> ### Example URLs
> Single video:
> 
> https://filemoon.sx/d/0fxcyc2ajhp1/GNOME_POWER.mp4 https://filemoon.sx/e/0fxcyc2ajhp1/GNOME_POWER.mp4
> 
> ### Provide a description that is worded well enough to be understood
> A place where people can upload videos and share them, like other video sharing websites.
> 
> ### Provide verbose output that clearly demonstrates the problem
> * [x]  Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
> * [x]  Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below
> 
> ### Complete Verbose Output
> ```shell
> [debug] Command-line config: ['-vU', 'https://filemoon.sx/d/0fxcyc2ajhp1/GNOME_POWER.mp4']
> [debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
> [debug] yt-dlp version 2022.09.01 [5d7c7d6] (zip)
> [debug] Python 3.8.10 (CPython 64bit) - Linux-5.15.57.1-microsoft-standard-WSL2-x86_64-with-glibc2.29 (glibc 2.31)
> [debug] Checking exe version: ffmpeg -bsfs
> [debug] Checking exe version: ffprobe -bsfs
> [debug] exe versions: ffmpeg 4.2.7, ffprobe 4.2.7, rtmpdump 2.4
> [debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, pyxattr-0.6.1, sqlite3-2.6.0, websockets-10.3
> [debug] Proxy map: {}
> [debug] Loaded 1670 extractors
> [debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
> Latest version: 2022.09.01, Current version: 2022.09.01
> yt-dlp is up to date (2022.09.01)
> [debug] [generic] Extracting URL: https://filemoon.sx/d/0fxcyc2ajhp1/GNOME_POWER.mp4
> [generic] GNOME_POWER: Downloading webpage
> WARNING: [generic] Falling back on generic information extractor
> [generic] GNOME_POWER: Extracting information
> [debug] Looking for Brightcove embeds
> [debug] Looking for embeds
> ERROR: Unsupported URL: https://filemoon.sx/d/0fxcyc2ajhp1/GNOME_POWER.mp4
> Traceback (most recent call last):
>   File "./yt-dlp/yt_dlp/YoutubeDL.py", line 1459, in wrapper
>     return func(self, *args, **kwargs)
>   File "./yt-dlp/yt_dlp/YoutubeDL.py", line 1535, in __extract_info
>     ie_result = ie.extract(url)
>   File "./yt-dlp/yt_dlp/extractor/common.py", line 670, in extract
>     ie_result = self._real_extract(url)
>   File "./yt-dlp/yt_dlp/extractor/generic.py", line 3078, in _real_extract
>     raise UnsupportedError(url)
> yt_dlp.utils.UnsupportedError: Unsupported URL: https://filemoon.sx/d/0fxcyc2ajhp1/GNOME_POWER.mp4
> ```

Guys anyone know what source code they use for their website? I only know that they use cdnjs but nothing about cms info. What code exactly for frontent & backend?
