### ISSUE TITLE
Cannot use --cookies with android (termux version )

### ISSUE THREAD

**Issue by ale82to** [yt-dlp/yt-dlp#4857]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.09.01** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

I cannot use --cookies="path to cookies " (--cookies="/data/data/org.mozilla.fenix/files/mozilla/q34i5xoo.default/cookies.sqlite")with YouTube dlp installed trought termux the relevant error I think is this :
File "/data/data/com.termux/files/usr/lib/python3.10/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x98 in position 35: invalid start byte
my test command is :
cd /storage/emulated/0/Download
/data/data/com.termux/files/usr/bin/yt-dlp --no-part --restrict-filenames --cookies="/data/data/org.mozilla.fenix/files/mozilla/q34i5xoo.default/cookies.sqlite" --user-agent "Mozilla/5.0 (Android 11; Mobile; rv:106.0) Gecko/106.0 Firefox/106.0" --referer "https://sbspeed.com/c/uq6hbc7eb5f5.html" --output "Watch Love The Villa Innamorarsi Verona 2022 iTALiAN WEBDL 1080p.%(ext)s" "https://delivery455.akamai-cdn-content.com/hls2/01/07170/uq6hbc7eb5f5_,l,n,.urlset/master.m3u8?t=V2nyFUmjRYy0IVIeqw1_mE62HzxNNgXMKg40vTcmG9o&s=1662483947&e=10800&f=35853393&srv=sto118&client=121.38.216.164"

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
WARNING: External Downloader arguments given without specifying name. The arguments will be given to aria2c
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/yt-dlp", line 8, in <module>
    sys.exit(main())
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/yt_dlp/__init__.py", line 962, in main
    _exit(*variadic(_real_main(argv)))
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/yt_dlp/__init__.py", line 924, in _real_main
    with YoutubeDL(ydl_opts) as ydl:
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 721, in __init__
    self._setup_opener()
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3763, in _setup_opener
    self.cookiejar = load_cookies(opts_cookiefile, opts_cookiesfrombrowser, self)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/yt_dlp/cookies.py", line 106, in load_cookies
    jar.load(ignore_discard=True, ignore_expires=True)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/yt_dlp/utils.py", line 1606, in load
    for line in f:
  File "/data/data/com.termux/files/usr/lib/python3.10/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x98 in position 35: invalid start byte
```

**Comment by xtkoba** [comment]
I don't know if this works but try something like

```
--cookies-from-browser firefox:/data/data/org.mozilla.fenix/files/mozilla/q34i5xoo.default
```

See also https://github.com/yt-dlp/yt-dlp/issues/4239.

**Comment by ale82to** [comment]
thank you you very much !!! it finally works !
