### ISSUE TITLE
error 403 on sbspeed.com

### ISSUE THREAD

**Issue by ale82to** [yt-dlp/yt-dlp#4859]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.09.01** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Italy

### Provide a description that is worded well enough to be understood

can please help me with error 403 access denied on this test url:

https://sbspeed.com/uq6hbc7eb5f5.html

after getting m3u8 url (with dev tool ),I issue this command but despite providing user agent ,cookie and refer I still get error 403 . command :

cd /storage/emulated/0/Download

/data/data/com.termux/files/usr/bin/yt-dlp --no-part --restrict-filenames --cookies-from-browser firefox:/data/data/org.mozilla.fenix/files/mozilla/q34i5xoo.default --user-agent "Mozilla/5.0 (Android 11; Mobile; rv:106.0) Gecko/106.0 Firefox/106.0" --referer "https://sbspeed.com/c/uq6hbc7eb5f5.html" --output "Watch1080p.%(ext)s" "https://delivery455.akamai-cdn-content.com/hls2/01/07170/uq6hbc7eb5f5_n/index-v1-a1.m3u8?t=EaZVhLwrUJ9V_xKY9ifY567dXOSUqQWGM8bUl34RFsw&s=1662507242&e=10800&f=35853393&srv=sto118&client=165.178.85.220"

I use it on Android but that's not the issue since same command works for other hosting site . thanks for helping .

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--no-part', '--restrict-filenames', '--cookies-from-browser', 'firefox:/data/data/org.mozilla.fenix/files/mozilla/q34i5xoo.default', '--user-agent', 'Mozilla/5.0 (Android 11; Mobile; rv:106.0) Gecko/106.0 Firefox/106.0', '--referer', 'https://sbspeed.com/c/uq6hbc7eb5f5.html', '--output', 'Watch1080p.%(ext)s', 'https://delivery455.akamai-cdn-content.com/hls2/01/07170/uq6hbc7eb5f5_n/index-v1-a1.m3u8?t=EaZVhLwrUJ9V_xKY9ifY567dXOSUqQWGM8bUl34RFsw&s=1662507242&e=10800&f=35853393&srv=sto118&client=185.178.95.240']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8 (No ANSI), error utf-8 (No ANSI), screen utf-8 (No ANSI)
[debug] yt-dlp version 2022.09.01 [5d7c7d6] (pip)
[debug] Python 3.10.6 (CPython 64bit) - Linux-4.19.242-BAALAM-2.1-Phantom-aarch64-with-libc (libc)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.12.0, brotli-1.0.9, certifi-2022.05.18.1, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.1
[debug] Extracting cookies from: "/data/data/org.mozilla.fenix/files/mozilla/q34i5xoo.default/cookies.sqlite"
[debug] Proxy map: {}
[debug] Loaded 1670 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
[debug] [generic] Extracting URL: https://delivery455.akamai-cdn-content.com/hls2/01/07170/uq6hbc7eb5f5_n/index-v1-a1.m3u8?t=EaZVhLwrUJ9V_xKY9ifY567dXOSUqQWGM8bUl34RFsw&s=1662507242&e=10800&f=35853393&srv=sto118&client=185.178.95.240
ERROR: [generic] Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 670, in extract
    ie_result = self._real_extract(url)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/yt_dlp/extractor/generic.py", line 2641, in _real_extract
    full_response = self._request_webpage(url, video_id, headers={'Accept-Encoding': '*'})
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 821, in _request_webpage
    raise ExtractorError(errmsg, cause=err)

  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 803, in _request_webpage
    return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query))
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3656, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/data/data/com.termux/files/usr/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/data/data/com.termux/files/usr/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/data/data/com.termux/files/usr/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/data/data/com.termux/files/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/data/data/com.termux/files/usr/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

**Comment by elyse0** [comment]
I fixed it adding ` --add-header 'Accept-Language: en-US,fr;q=0.7,en;q=0.3'`, the value may be different for you

Related  #4719

**Comment by ale82to** [comment]
> I fixed it adding ` --add-header 'Accept-Language: en-US,fr;q=0.7,en;q=0.3'`, the value may be different for you
> 
> Duplicate of #4719

thank you ,thank you ,thank you! it worked i ve spent countless hours on this issue (I'm very stubborn )thank you again !
