### ISSUE TITLE
[adobepass] Suddenlink MSO rebrand to Optimum

### ISSUE THREAD

**Issue by CplPwnies** [yt-dlp/yt-dlp#4874]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.09.01** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

US

### Provide a description that is worded well enough to be understood

Suddenlink has been rebranded to Optimum and is now using the Optimum.TV MSO login. The original Suddenlink MSO still works for the time being, so that code is not being removed, but support needs to be added for Optimum.TV MSO moving forward

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['https://episodeURL.com', '--ap-mso', 'AlticeOne', '--ap-username', 'PRIVATE', '--ap-password', 'PRIVATE', '--rm-cache-dir', '-vU']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.09.01 [5d7c7d656]
[debug] Lazy loading extractors is disabled
[debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
[debug] Python 3.8.2 (CPython 32bit) - Windows-10-10.0.19041-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: none
[debug] Optional libraries: certifi-2019.11.28, sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Loaded 1671 extractors
Removing cache dir C:\Users\USER/.cache\yt-dlp ...
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.09.01, Current version: 2022.09.01
yt-dlp is up to date (2022.09.01)
[debug] [Go] Extracting URL: episode.URL.com/vdka12345
[Go] vdka12345: Downloading JSON metadata
[Go] vdka12345: Downloading Provider Redirect Page
[Go] vdka12345: Downloading Provider Login Page
[Go] vdka12345: Logging in
[Go] vdka12345: Confirming Login
[Go] vdka12345: Retrieving Session
[debug] Saving ap-mvpd.dtci to cache
[Go] vdka12345: Retrieving Authorization Token
```

**Comment by pukkandan** [comment]
In future, you don't need to open issue when making PRs that fix site support. Simply describing the issue in the PR is sufficient
