### ISSUE TITLE
error 403 on trovo.live

### ISSUE THREAD

**Issue by 5a1711** [yt-dlp/yt-dlp#4878]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.09.01** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Russia

### Provide a description that is worded well enough to be understood

07/09/2022 it worked fine. 08/09/2022 returns 403

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://trovo.live/s/rizhaya/549788681771?vid=ltv-108151031_108151031_387702305443548828']
[debug] Encodings: locale cp1251, fs utf-8, pref cp1251, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.09.01 [5d7c7d6] (win32_exe)
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.18363-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg N-107408-g882aac99d2-20220714 (setts), ffprobe N-107408-g882aac99d2-20220714
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1670 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.09.01, Current version: 2022.09.01
yt-dlp is up to date (2022.09.01)
[debug] [TrovoVod] Extracting URL: https://trovo.live/s/rizhaya/549788681771?vid=ltv-108151031_108151031_387702305443548828
[TrovoVod] ltv-108151031_108151031_387702305443548828: Downloading JSON metadata
ERROR: [TrovoVod] ltv-108151031_108151031_387702305443548828: Unable to download JSON metadata: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 670, in extract
  File "yt_dlp\extractor\trovo.py", line 164, in _real_extract
  File "yt_dlp\extractor\trovo.py", line 26, in _call_api
  File "yt_dlp\extractor\common.py", line 1030, in download_content
  File "yt_dlp\extractor\common.py", line 994, in download_handle
  File "yt_dlp\extractor\common.py", line 864, in _download_webpage_handle
  File "yt_dlp\extractor\common.py", line 821, in _request_webpage

  File "yt_dlp\extractor\common.py", line 803, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 3656, in urlopen
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

**Comment by 5a1711** [comment]
#4880 seems to be the fix

**Comment by T4DM** [comment]
Здраствуй, я человек который не разбирается в этих кодах, программировании и прочем, но кое как смог разобраться в действиях, необходимых для скачивания видео в yt-dlp коде. С трово у меня аналогичная проблема, и как я вижу, ты похоже смог с ней разобраться. И если всё дело было в коде, то не мог бы ты мне пожалуйста скинуть готовый, правильный код, с помощью которого я смог бы скачать трансляцию с трово без этой ошибки?

**Comment by 5a1711** [comment]
> Здраствуй, я человек который не разбирается в этих кодах, программировании и прочем, но кое как смог разобраться в действиях, необходимых для скачивания видео в yt-dlp коде. С трово у меня аналогичная проблема, и как я вижу, ты похоже смог с ней разобраться. И если всё дело было в коде, то не мог бы ты мне пожалуйста скинуть готовый, правильный код, с помощью которого я смог бы скачать трансляцию с трово без этой ошибки? Кринжа я конечно навалил, потому что походу никакой другой код не поможет. Но тогда если ты знаешь как это решить, то обьясни простыми словами пожалуйста. Или просто стоит подождать выхода новой версии yt-dlp и там всё исправят?

тебе самому нужно скомпилировать вариант #4880. я сделал это, работает загрузка теперь. можешь разобраться сам, как это делать. лишним не будет. но могу и готовый файл скинуть, только тут ссылку может нельзя оставлять. 
ладно, пусть забанят, если что не так: https://dropmefiles.com/1ATIo

**Comment by T4DM** [comment]
Бог оказывается существует. Всё работает. Спасибо огромное! Если бы ты не скинул ссылку, то я долго бы сидел в попытка разобраться с этой скомпилитрацией, так что спасибо что заморочился с загрузкой файла на сайт.
