### ISSUE TITLE
add support for slider.kz

### ISSUE THREAD

**Issue by vehosah** [yt-dlp/yt-dlp#4887]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.09.01** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Greece

### Example URLs

slider.kz

### Provide a description that is worded well enough to be understood

I standardly used yt-dlp via windows terminal "yt-dlp URL" (if not DRM)

My-iMac:~ iMac$ yt-dlp --version
2022.09.01
My-iMac:~ iMac$ yt-dlp https://slider.kz/#jackie-o%20yet%20to%20come
[generic] jackie-o yet to come: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] jackie-o yet to come mp3: Extracting information
ERROR: Unsupported URL: https://slider.kz/download/-2001807524_110807524/197/cs3-1v4/s/v1/acmp/nD668w8967GpSKlRtu0sOh_qEzuJDIi5MKlMxZG1uu_u9kb0LUR-JpinNVVWE7cMWm3yNFVSmakpVkYmXMAWGHO1ZcqDn8RsV29-iT2DuMPhPaS8x2ytdIwbza_0TzMOcDcEpfMSceuB0xCpci2_JNDjVsE_cNIsMYETjpbOT3eSdfXtkg/Jackie-O%20feat.%20B-Lion%20-%20Yet%20To%20Come.mp3?extra=null
My-iMac:~ iMac$

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
My-iMac:~ iMac$ yt-dlp -vU
[debug] Command-line config: ['-vU']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.09.01 [5d7c7d6] (pip)
[debug] Python 3.10.6 (CPython 64bit) - macOS-11.6-x86_64-i386-64bit 
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 5.1 (setts), ffprobe 5.1
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1670 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.09.01, Current version: 2022.09.01
yt-dlp is up to date (2022.09.01)
```

**Comment by pukkandan** [comment]
Looks like a piracy site. Explain your reason to believe otherwise

**Comment by vehosah** [comment]
> Looks like a piracy site. Explain your reason to believe otherwise

I don't know it just a music downloader from vk
