### ISSUE TITLE
downloading live streams despite '--match-filter', '!is_live'

### ISSUE THREAD

**Issue by bani6809** [yt-dlp/yt-dlp#4894]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.09.01** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

the documentation says to skip live streams, use --match-filter !is_live, but this does not appear to be working.

it appears to still be downloading live streams, and explicitly mentions invoking youtube_live_chat downloader.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU']
[debug] User config "C:\Users\admin\yt-dlp.conf": ['-v', '-i', '-o', '%(uploader)s (%(uploader_id)s)/%(upload_date)s - %(title)s - (%(duration)ss) [%(resolution)s] [%(id)s].%(ext)s', '--no-colors', '--playlist-end', '50', '--sleep-requests', '1', '--sleep-interval', '2', '--max-sleep-interval', '5', '--extractor-args', 'youtube:player_client=android', '--throttled-rate', '600K', '--concurrent-fragments', '4', '--http-chunk-size', '2M', '--encoding', 'utf-8', '--download-archive', 'youtube-dl-archive.txt', '-a', 'youtube-dl-channels.txt', '--no-overwrites', '--match-filter', '!is_live', '--downloader', 'aria2c', '--downloader-args', 'aria2c:-j 8 -s 8', '--prefer-ffmpeg', '--merge-output-format', 'mkv', '--write-sub', '--all-subs', '--convert-subs', 'srt', '--embed-subs', '--add-metadata', '--write-description', '--write-annotations', '--write-all-thumbnails', '--write-info-json', '--format', '(bestvideo[vcodec^=av01][height>=4320][fps>30]/bestvideo[vcodec=vp9.2][height>=4320][fps>30]/bestvideo[vcodec=vp9][height>=4320][fps>30]/bestvideo[vcodec^=av01][height>=2160][fps>30]/bestvideo[vcodec=vp9.2][height>=2160][fps>30]/bestvideo[vcodec=vp9][height>=2160][fps>30]/bestvideo[vcodec^=av01][height>=1440][fps>30]/bestvideo[vcodec=vp9.2][height>=1440][fps>30]/bestvideo[vcodec=vp9][height>=1440][fps>30]/bestvideo[vcodec^=av01][height>=1080][fps>30]/bestvideo[vcodec=vp9.2][height>=1080][fps>30]/bestvideo[vcodec=vp9][height>=1080][fps>30]/bestvideo[vcodec^=av01][height>=1080]/bestvideo[vcodec=vp9.2][height>=1080]/bestvideo[vcodec=vp9][height>=1080]/bestvideo[height>=1080]/bestvideo[vcodec^=av01][height>=720][fps>30]/bestvideo[vcodec=vp9.2][height>=720][fps>30]/bestvideo[vcodec=vp9][height>=720][fps>30]/bestvideo[vcodec^=av01][height>=720]/bestvideo[vcodec=vp9.2][height>=720]/bestvideo[vcodec=vp9][height>=720]/bestvideo[height>=720]/bestvideo)+(bestaudio[acodec=opus]/bestaudio)/best', '--proxy', '', '--rm-cache-dir', '--user-agent', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3627.1 Safari/537.36', '--cookies', 'youtube-cookies.txt', '-v']
[debug] Batch file urls: ['https://www.youtube.com/channel/UCGy6uV7yqGWDeUWTZzT3ZEg']
[debug] Encodings: locale cp1252, fs utf-8, pref utf-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.09.01 [5d7c7d6] (win32_exe)
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 5.0.1-full_build-www.gyan.dev (setts), ffprobe 5.0.1-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1670 extractors
[debug] Loading archive file 'youtube-dl-archive.txt'
Removing cache dir C:\Users\admin/.cache\yt-dlp ..
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.09.01, Current version: 2022.09.01
yt-dlp is up to date (2022.09.01)
[debug] [youtube:tab] Extracting URL: https://www.youtube.com/channel/UCGy6uV7yqGWDeUWTZzT3ZEg
[youtube:tab] UCGy6uV7yqGWDeUWTZzT3ZEg: Downloading webpage
[youtube:tab] A channel/user page was given. All the channel's videos will be downloaded. To download only the videos in the home page, add a "/featured" to the URL
[debug] [youtube:tab] Final URL: https://www.youtube.com/channel/UCGy6uV7yqGWDeUWTZzT3ZEg/videos
[download] Downloading playlist: Rebel News - Videos
[debug] [youtube:tab] Extracted SAPISID cookie
[youtube:tab] Sleeping 1.0 seconds ...
[youtube:tab] UCGy6uV7yqGWDeUWTZzT3ZEg page 1: Downloading API JSON
[info] Playlist metadata is already present
[info] Playlist description is already present
[info] Playlist thumbnail avatar_uncropped is already present
[info] Playlist thumbnail 17 is already present
[info] Playlist thumbnail banner_uncropped is already present
[info] Playlist thumbnail 15 is already present
[info] Playlist thumbnail 14 is already present
[info] Playlist thumbnail 13 is already present
[info] Playlist thumbnail 12 is already present
[info] Playlist thumbnail 11 is already present
[info] Playlist thumbnail 10 is already present
[info] Playlist thumbnail 9 is already present
[info] Playlist thumbnail 8 is already present
[info] Playlist thumbnail 7 is already present
[info] Playlist thumbnail 6 is already present
[info] Playlist thumbnail 5 is already present
[info] Playlist thumbnail 4 is already present
[info] Playlist thumbnail 3 is already present
[info] Playlist thumbnail 2 is already present
[info] Playlist thumbnail 1 is already present
[info] Playlist thumbnail 0 is already present
[youtube:tab] Playlist Rebel News - Videos: Downloading 50 videos
[download] Downloading video 1 of 50
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=MblEtpX0ytU
[youtube] Sleeping 1.0 seconds ...
[youtube] MblEtpX0ytU: Downloading webpage
[debug] [youtube] Extracted SAPISID cookie
[youtube] Sleeping 1.0 seconds ...
[youtube] MblEtpX0ytU: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[info] MblEtpX0ytU: Downloading subtitles: live_chat
[info] MblEtpX0ytU: Downloading 1 format(s): 247+251
[info] Video description is already present
[info] Writing video subtitles to: Rebel News (UCGy6uV7yqGWDeUWTZzT3ZEg)\20220910 - LIVE COVERAGE： Conservative Party of Canada leadership election results! - (15370s) [1280x720] [MblEtpX0ytU].live_chat.json
[debug] Invoking youtube_live_chat downloader on "https://www.youtube.com/watch?v=MblEtpX0ytU&bpctr=9999999999&has_verified=1"
[youtube_live_chat] Downloading live chat
[youtube_live_chat] Total fragments: unknown (live)
[download] Destination: Rebel News (UCGy6uV7yqGWDeUWTZzT3ZEg)\20220910 - LIVE COVERAGE： Conservative Party of Canada leadership election results! - (15370s) [1280x720] [MblEtpX0ytU].live_chat.json
[debug] File locking is not supported. Proceeding without locking
```

**Comment by pukkandan** [comment]
The video is not live. It is a VOD and the live chat replay is being downloaded since you requested `--all-subs`. If you want to not download VODs, use `--match-filter "!is_live && !was_live"`. Or, if you just don't want to download chat, replace `--all-subs` with `--sub-langs all,-live_chat`

**Comment by bani6809** [comment]
so i just realized it's not live, but was_live. but strangely, the stream is downloading very slowly as if it were livestream. 25KiB/s. i have yt-dlp running in another window on other channel videos and it's downloading them at 2MB/s. not sure if this is expected.

**Comment by pukkandan** [comment]
The video is downloading slow, or just the chat? If chat, that is expected. If video, show verbose output demonstrating the slow speed

**Comment by bani6809** [comment]
seems just the chat. so i tried --sub-langs all,-live-chat and it still seems to be trying to download the chat. so i have new problem ;)

[debug] Command-line config: ['-vU']
[debug] User config "C:\Users\admin\yt-dlp.conf": ['-v', '-i', '-o', '%(uploader)s (%(uploader_id)s)/%(upload_date)s - %(title)s - (%(duration)ss) [%(resolution)s] [%(id)s].%(ext)s', '--no-colors', '--playlist-end', '50', '--sleep-requests', '1', '--sleep-interval', '2', '--max-sleep-interval', '5', '--extractor-args', 'youtube:player_client=android', '--throttled-rate', '600K', '--concurrent-fragments', '4', '--http-chunk-size', '2M', '--encoding', 'utf-8', '--download-archive', 'youtube-dl-archive.txt', '-a', 'youtube-dl-channels.txt', '--no-overwrites', '--match-filter', '!is_live', '--downloader', 'aria2c', '--downloader-args', 'aria2c:-j 8 -s 8', '--prefer-ffmpeg', '--merge-output-format', 'mkv', '--write-sub', '--sub-langs', 'all,-live-chat', '--convert-subs', 'srt', '--embed-subs', '--add-metadata', '--write-description', '--write-annotations', '--write-all-thumbnails', '--write-info-json', '--format', '(bestvideo[vcodec^=av01][height>=4320][fps>30]/bestvideo[vcodec=vp9.2][height>=4320][fps>30]/bestvideo[vcodec=vp9][height>=4320][fps>30]/bestvideo[vcodec^=av01][height>=2160][fps>30]/bestvideo[vcodec=vp9.2][height>=2160][fps>30]/bestvideo[vcodec=vp9][height>=2160][fps>30]/bestvideo[vcodec^=av01][height>=1440][fps>30]/bestvideo[vcodec=vp9.2][height>=1440][fps>30]/bestvideo[vcodec=vp9][height>=1440][fps>30]/bestvideo[vcodec^=av01][height>=1080][fps>30]/bestvideo[vcodec=vp9.2][height>=1080][fps>30]/bestvideo[vcodec=vp9][height>=1080][fps>30]/bestvideo[vcodec^=av01][height>=1080]/bestvideo[vcodec=vp9.2][height>=1080]/bestvideo[vcodec=vp9][height>=1080]/bestvideo[height>=1080]/bestvideo[vcodec^=av01][height>=720][fps>30]/bestvideo[vcodec=vp9.2][height>=720][fps>30]/bestvideo[vcodec=vp9][height>=720][fps>30]/bestvideo[vcodec^=av01][height>=720]/bestvideo[vcodec=vp9.2][height>=720]/bestvideo[vcodec=vp9][height>=720]/bestvideo[height>=720]/bestvideo)+(bestaudio[acodec=opus]/bestaudio)/best', '--proxy', '', '--rm-cache-dir', '--user-agent', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3627.1 Safari/537.36', '--cookies', 'youtube-cookies.txt', '-v']
[debug] Batch file urls: ['https://www.youtube.com/channel/UCGy6uV7yqGWDeUWTZzT3ZEg']
[debug] Encodings: locale cp1252, fs utf-8, pref utf-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.09.01 [5d7c7d6] (win32_exe)
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 5.0.1-full_build-www.gyan.dev (setts), ffprobe 5.0.1-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1670 extractors
[debug] Loading archive file 'youtube-dl-archive.txt'
Removing cache dir C:\Users\admin/.cache\yt-dlp ..
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.09.01, Current version: 2022.09.01
yt-dlp is up to date (2022.09.01)
[debug] [youtube:tab] Extracting URL: https://www.youtube.com/channel/UCGy6uV7yqGWDeUWTZzT3ZEg
[youtube:tab] UCGy6uV7yqGWDeUWTZzT3ZEg: Downloading webpage
[youtube:tab] A channel/user page was given. All the channel's videos will be downloaded. To download only the videos in the home page, add a "/featured" to the URL
[debug] [youtube:tab] Final URL: https://www.youtube.com/channel/UCGy6uV7yqGWDeUWTZzT3ZEg/videos
[download] Downloading playlist: Rebel News - Videos
[debug] [youtube:tab] Extracted SAPISID cookie
[youtube:tab] Sleeping 1.0 seconds ...
[youtube:tab] UCGy6uV7yqGWDeUWTZzT3ZEg page 1: Downloading API JSON
[info] Playlist metadata is already present
[info] Playlist description is already present
[info] Playlist thumbnail avatar_uncropped is already present
[info] Playlist thumbnail 17 is already present
[info] Playlist thumbnail banner_uncropped is already present
[info] Playlist thumbnail 15 is already present
[info] Playlist thumbnail 14 is already present
[info] Playlist thumbnail 13 is already present
[info] Playlist thumbnail 12 is already present
[info] Playlist thumbnail 11 is already present
[info] Playlist thumbnail 10 is already present
[info] Playlist thumbnail 9 is already present
[info] Playlist thumbnail 8 is already present
[info] Playlist thumbnail 7 is already present
[info] Playlist thumbnail 6 is already present
[info] Playlist thumbnail 5 is already present
[info] Playlist thumbnail 4 is already present
[info] Playlist thumbnail 3 is already present
[info] Playlist thumbnail 2 is already present
[info] Playlist thumbnail 1 is already present
[info] Playlist thumbnail 0 is already present
[youtube:tab] Playlist Rebel News - Videos: Downloading 50 videos
[download] Downloading video 1 of 50
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=MblEtpX0ytU
[youtube] Sleeping 1.0 seconds ...
[youtube] MblEtpX0ytU: Downloading webpage
[debug] [youtube] Extracted SAPISID cookie
[youtube] Sleeping 1.0 seconds ...
[youtube] MblEtpX0ytU: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[info] MblEtpX0ytU: Downloading subtitles: live_chat
[info] MblEtpX0ytU: Downloading 1 format(s): 247+251
[info] Video description is already present
[info] Writing video subtitles to: Rebel News (UCGy6uV7yqGWDeUWTZzT3ZEg)\20220910 - LIVE COVERAGE： Conservative Party of Canada leadership election results! - (15370s) [1280x720] [MblEtpX0ytU].live_chat.json
[debug] Invoking youtube_live_chat downloader on "https://www.youtube.com/watch?v=MblEtpX0ytU&bpctr=9999999999&has_verified=1"
[youtube_live_chat] Downloading live chat
[youtube_live_chat] Total fragments: unknown (live)
[download] Destination: Rebel News (UCGy6uV7yqGWDeUWTZzT3ZEg)\20220910 - LIVE COVERAGE： Conservative Party of Canada leadership election results! - (15370s) [1280x720] [MblEtpX0ytU].live_chat.json
[debug] File locking is not supported. Proceeding without locking
[download] 28.47MiB at   32.10KiB/s (00:09) (frag 2)[debug] [YoutubeBaseInfoExtract] Extracted SAPISID cookie
[download] 30.27MiB at   40.65KiB/s (00:57) (frag 15)

**Comment by pukkandan** [comment]
live_chat, not live-chat

**Comment by bani6809** [comment]
i feel really stupid now  ಠ_ಠ
