### ISSUE TITLE
How to get a video with the exactly same file name? Is it a bug or ?

### ISSUE THREAD

**Issue by lionderful** [yt-dlp/yt-dlp#4895]
We will get a different file name from the original video, for example: 

$ yt-dlp --print filename -o "%(title)s.%(ext)s" BaW_jenozKc
We will get a file name: '''youtube-dl test video ＂'⧸⧹ä↭𝕐''',
 which is slightly differty from the original one: '''youtube-dl test video "'/\ä↭𝕐'''
Is this a bug? if not, how to get a file with the exactly same file name from youtube?

my pc: win 11, chinese language, Python 3.9.13

**Comment by pukkandan** [comment]
Try manually creating a file with the name you want and see what happens

**Comment by coletdjnz** [comment]
> if not, how to get a file with the exactly same file name from youtube?
also you are excluding the video id in the filename, which acts as a unique identifier making the filename unique

**Comment by lionderful** [comment]
> Try manually creating a file with the name you want and see what happens

thank you, man! Got it! 
We could not create some file names. So  yt-dlp give a similar one.
for example, we could not create a file named "'ä↭𝕐" in our disk. but we can use it as youtube video title.

**Comment by lionderful** [comment]
> > if not, how to get a file with the exactly same file name from youtube?
> 
> also you are excluding the video id in the filename, which acts as a unique identifier making the filename unique

yeah, it is a prety good alternative way.  
But we could not read any information form a file named as "BaW_jenozKc.mp4". 
Does yt-dlp gives us a function or keyword to call the right name of the final file?
It would save a few lines in a python script

**Comment by lionderful** [comment]
> > if not, how to get a file with the exactly same file name from youtube?
> 
> also you are excluding the video id in the filename, which acts as a unique identifier making the filename unique

yeah, it is a prety good alternative way.
But we could not read any information form a file named as "BaW_jenozKc.mp4".
Does yt-dlp gives us a function or keyword to call the right name of the final file?
I could use it directly in my python script
