### ISSUE TITLE
[AudioDraft] Playlist support

### ISSUE THREAD

**Issue by Jadoo4QFan** [yt-dlp/yt-dlp#4910]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a site-specific feature
- [X] I've verified that I'm running yt-dlp version **2022.09.01** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

California, USA

### Example URLs

http://nokiatune.audiodraft.com/

### Provide a description that is worded well enough to be understood

The AudioDraft extractor does not work for playlist URLs, only entries.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[Documents]$ yt-dlp http://nokiatune.audiodraft
.com/ -v > audiodraft.txt 
[debug] Command-line config: ['http://nokiatune
.audiodraft.com/', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, pref
 UTF-8, out utf-8 (No ANSI), error utf-8 (No AN
SI), screen utf-8 (No ANSI)
[debug] yt-dlp version 2022.08.14 [5593720] (pi
p)
[debug] Python 3.9.10+ (CPython 64bit) - macOS-
15.4.1-iPhone14,5-arm-64bit 
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg n5.0.1-4-ga5ebb3d2
5e (setts), ffprobe n5.0.1-4-ga5ebb3d25e, phant
omjs present, rtmpdump present
[debug] Optional libraries: Crypto-3.15.0, cert
ifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, 
websockets-10.3
[debug] Proxy map: {}
[debug] [generic] Extracting URL: http://nokiatune.audiodraft.com/
WARNING: [generic] Falling back on generic information extractor
[debug] Looking for Brightcove embeds
[debug] Looking for embeds
ERROR: Unsupported URL: http://nokiatune.audiodraft.com/
Traceback (most recent call last):
  File "/var/mobile/Containers/Data/Application/60CD8846-C866-41CA-929F-06D7C03F9F05/Library/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1441, in wrapper
    return func(self, *args, **kwargs)
  File "/var/mobile/Containers/Data/Application/60CD8846-C866-41CA-929F-06D7C03F9F05/Library/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1517, in __extract_info
    ie_result = ie.extract(url)
  File "/var/mobile/Containers/Data/Application/60CD8846-C866-41CA-929F-06D7C03F9F05/Library/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 666, in extract
    ie_result = self._real_extract(url)
  File "/var/mobile/Containers/Data/Application/60CD8846-C866-41CA-929F-06D7C03F9F05/Library/lib/python3.9/site-packages/yt_dlp/extractor/generic.py", line 3077, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL:
 http://nokiatune.audiodraft.com/
```

**Comment by gamer191** [comment]
This could be done by downloading `http://nokiatune.audiodraft.com/entry/1` and then continuing to increase that number up to `http://nokiatune.audiodraft.com/entry/6239`

**Comment by Jadoo4QFan** [comment]
> This could be done by downloading `http://nokiatune.audiodraft.com/entry/1` and then continuing to increase that number up to `http://nokiatune.audiodraft.com/entry/6239`

Remember some people may remove their uploads resulting in an error.

**Comment by pukkandan** [comment]
Is the request just to support this one URL? Or are their other playlists in the site?

**Comment by gamer191** [comment]
>are their other playlists in the site?

There's technically other sub-domains (such as http://nelonenmedia.audiodraft.com/). This seems to be the only one that anyone ever cares about though
Also, I'm not sure if downloading all audio entries would be the expected behaviour for all sub-domains (eg: http://vikinggrace.audiodraft.com/ )

> Is the request just to support this one URL?

the individual audio urls are already supported by `AudiodraftCustomIE`, so it's a request to add support for this one url to `audiodraft.py`
