### ISSUE TITLE
[NSFL/GORE] Deep Gore Tube

### ISSUE THREAD

**Issue by Jadoo4QFan** [yt-dlp/yt-dlp#4912]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.09.01** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

California, USA

### Example URLs

https://deepgoretube.site/ronnie-mcnutts-suicide/

### Provide a description that is worded well enough to be understood

Please add support for deepgoretube. I personally would like to download the infamous Ronnie McNutt video from there for the purpose of archival. Metadata would also be nice too, the site has a lot. Please, for the sake of your mental health, only implement this if you confirmed you are fully desensitized to gore.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[Documents]$ yt-dlp https://deepgoretube.site/r
onnie-mcnutts-suicide/ -vU --write-info-json --
write-all-thumbnails --write-subs --sub-langs a
ll --write-description  
[debug] Command-line config: ['https://deepgore
tube.site/ronnie-mcnutts-suicide/', '-vU', '--w
rite-info-json', '--write-all-thumbnails', '--w
rite-subs', '--sub-langs', 'all', '--write-desc
ription']
[debug] Encodings: locale UTF-8, fs utf-8, pref
 UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.09.01 [5d7c7d6] (pi
p)
[debug] Python 3.9.10+ (CPython 64bit) - macOS-
15.4.1-iPhone14,5-arm-64bit 
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg n5.0.1-4-ga5ebb3d25e (setts), ffprobe n5.0.1-4-ga5ebb3d25e, phantomjs present, rtmpdump present
[debug] Optional libraries: Crypto-3.15.0, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1670 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.09.01, Current version: 2022.09.01
yt-dlp is up to date (2022.09.01)
[debug] [generic] Extracting URL: https://deepgoretube.site/ronnie-mcnutts-suicide/
[generic] ronnie-mcnutts-suicide: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] ronnie-mcnutts-suicide: Extracting information
[debug] Looking for Brightcove embeds
[debug] Looking for embeds
ERROR: Unsupported URL: https://deepgoretube.site/ronnie-mcnutts-suicide/
Traceback (most recent call last):
  File "/var/mobile/Containers/Data/Application/87BE3170-A2E1-4D77-98F2-3C7FE2FA6E42/Library/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1459, in wrapper
    return func(self, *args, **kwargs)
  File "/var/mobile/Containers/Data/Application/87BE3170-A2E1-4D77-98F2-3C7FE2FA6E42/Library/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1535, in __extract_info
    ie_result = ie.extract(url)
  File "/var/mobile/Containers/Data/Application/87BE3170-A2E1-4D77-98F2-3C7FE2FA6E42/Library/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 670, in extract
    ie_result = self._real_extract(url)
  File "/var/mobile/Containers/Data/Application/87BE3170-A2E1-4D77-98F2-3C7FE2FA6E42/Library/lib/python3.9/site-packages/yt_dlp/extractor/generic.py", line 3078, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://deepgoretube.site/ronnie-mcnutts-suici
de/
```

**Comment by pukkandan** [comment]
> I personally would like to download the infamous Ronnie McNutt video from there for the purpose of archival.

If you simply want to download a single video, I honestly wouldn't recommend waiting for someone to implement this. There are other (more manual) ways to download a single video

**Comment by Jadoo4QFan** [comment]
> > I personally would like to download the infamous Ronnie McNutt video from there for the purpose of archival.
> 
> If you simply want to download a single video, I honestly wouldn't recommend waiting for someone to implement this. There are other (more manual) ways to download a single video

And there are more footage of historical incidents to download for archival purposes, and it would come in handy.

**Comment by pukkandan** [comment]
Sure, I am not rejecting your site request. Just a small advise if your primary objective is to download the one video

**Comment by Jadoo4QFan** [comment]
OK.
