### ISSUE TITLE
Vivaldi cookies can't be extracted "no such table: cookies"

### ISSUE THREAD

**Issue by tueksta** [yt-dlp/yt-dlp#4915]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.09.01** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

I call yt-dlp from zsh with this line: ```yt-dlp -o "%(title)s.%(ext)s" --extract-audio --audio-format mp3 --cookies-from-browser vivaldi https://www.youtube.com/watch?v=y8trd3gjJt0``` and it worked fine until now. Now it complains that the sql file has no table named cookies.

attaching my vivaldi version:
```
Vivaldi | 5.4.2753.47 (Stable channel) (x86_64)
-- | --
Revision | 9fb7fdb85e69a976cc6784ef2de077e88b01995d
OS | macOS Version 12.3.1 (Build 21E258)
JavaScript | V8 10.4.132.23
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.115 Safari/537.36
Command Line | /Applications/Vivaldi.app/Contents/MacOS/Vivaldi --enable-features --disable-features --flag-switches-begin --disable-features=HardwareMediaKeyHandling --flag-switches-end --restore-last-session --disable-smooth-scrolling --save-page-as-mhtml
Executable Path | /Applications/Vivaldi.app/Contents/MacOS/Vivaldi
Profile Path | /Users/andreasbeer/Library/Application Support/Vivaldi/Default
Linker | lld
```

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '-o', '%(title)s.%(ext)s', '--extract-audio', '--audio-format', 'mp3', '--cookies-from-browser', 'vivaldi', 'https://www.youtube.com/watch?v=y8trd3gjJt0']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.09.01 [5d7c7d6] (pip)
[debug] Python 3.10.6 (CPython 64bit) - macOS-12.3.1-x86_64-i386-64bit 
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 5.1.1 (setts), ffprobe 5.1.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[Cookies] Extracting cookies from vivaldi
[debug] Extracting cookies from: "/Users/andreasbeer/Library/Application Support/Vivaldi/Default/Cookies"
[debug] using find-generic-password to obtain password from OSX keychain
Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp", line 33, in <module>
    sys.exit(load_entry_point('yt-dlp==2022.9.1', 'console_scripts', 'yt-dlp')())
  File "/usr/local/Cellar/yt-dlp/2022.9.1/libexec/lib/python3.10/site-packages/yt_dlp/__init__.py", line 962, in main
    _exit(*variadic(_real_main(argv)))
  File "/usr/local/Cellar/yt-dlp/2022.9.1/libexec/lib/python3.10/site-packages/yt_dlp/__init__.py", line 924, in _real_main
    with YoutubeDL(ydl_opts) as ydl:
  File "/usr/local/Cellar/yt-dlp/2022.9.1/libexec/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 681, in __init__
    self.print_debug_header()
  File "/usr/local/Cellar/yt-dlp/2022.9.1/libexec/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3734, in print_debug_header
    self._setup_opener()
  File "/usr/local/Cellar/yt-dlp/2022.9.1/libexec/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3763, in _setup_opener
    self.cookiejar = load_cookies(opts_cookiefile, opts_cookiesfrombrowser, self)
  File "/usr/local/Cellar/yt-dlp/2022.9.1/libexec/lib/python3.10/site-packages/yt_dlp/cookies.py", line 97, in load_cookies
    extract_cookies_from_browser(browser_name, profile, YDLLogger(ydl), keyring=keyring, container=container))
  File "/usr/local/Cellar/yt-dlp/2022.9.1/libexec/lib/python3.10/site-packages/yt_dlp/cookies.py", line 118, in extract_cookies_from_browser
    return _extract_chrome_cookies(browser_name, profile, keyring, logger)
  File "/usr/local/Cellar/yt-dlp/2022.9.1/libexec/lib/python3.10/site-packages/yt_dlp/cookies.py", line 291, in _extract_chrome_cookies
    cursor.execute(f'SELECT host_key, name, value, encrypted_value, path, expires_utc, {secure_column} FROM cookies')
sqlite3.OperationalError: no such table: cookies
```

**Comment by pukkandan** [comment]
It does work for me on windows. So the issue is possibly Mac specific. Does chrome or other chromium browsers work?

cc @mbway

**Comment by tueksta** [comment]
I tried with Chromium, works fine.

**Comment by mbway** [comment]
So @tueksta  I don't know why your cookies database doesn't have a cookies table. Perhaps the profile is corrupt because the clean vivaldi install still seems to be using the same schema as every other chromium based browser.
perhaps you could run
```
sqlite3 "/Users/andreasbeer/Library/Application Support/Vivaldi/Default/Cookies" ".schema"
```
and post the output?

**Comment by tueksta** [comment]
I have no idea, I actively use vivaldi and cookies are working fine. But I noticed on the last browser update that all my cookies disappeared, so maybe somehow the db got corrupted? The sqlite output looks fine:

```
sqlite3 "/Users/andreasbeer/Library/Application Support/Vivaldi/Default/Cookies" ".schema"
CREATE TABLE meta(key LONGVARCHAR NOT NULL UNIQUE PRIMARY KEY, value LONGVARCHAR);
CREATE TABLE cookies(creation_utc INTEGER NOT NULL,host_key TEXT NOT NULL,top_frame_site_key TEXT NOT NULL,name TEXT NOT NULL,value TEXT NOT NULL,encrypted_value BLOB NOT NULL,path TEXT NOT NULL,expires_utc INTEGER NOT NULL,is_secure INTEGER NOT NULL,is_httponly INTEGER NOT NULL,last_access_utc INTEGER NOT NULL,has_expires INTEGER NOT NULL,is_persistent INTEGER NOT NULL,priority INTEGER NOT NULL,samesite INTEGER NOT NULL,source_scheme INTEGER NOT NULL,source_port INTEGER NOT NULL,is_same_party INTEGER NOT NULL,last_update_utc INTEGER NOT NULL);
CREATE UNIQUE INDEX cookies_unique_index ON cookies(host_key, top_frame_site_key, name, path);
```

**Comment by pukkandan** [comment]
> ```diff
> -            return stdout or '', stderr or '', proc.returncode
> +            return stdout or b'', stderr or b'', proc.returncode
> ```

This should be:
```diff
-            return stdout or '', stderr or '', proc.returncode
+            default = '' if proc.text_mode else b''
+            return stdout or default, stderr or default, proc.returncode
```
according to https://github.com/python/cpython/blob/8fc2635995797b18eb88fd8a1374597dfc9c55f0/Lib/subprocess.py#L929-L935

**Comment by pukkandan** [comment]
Should I merge your patch directly?

**Comment by mbway** [comment]
> I think catching this case is still a good thing, and giving some output that hints at what the problem is

I don't think there is much else we can report in that case though. The error already says `no such table: cookies`. I suppose we could continue the download (without cookies) if any SQL queries fail though?

> This should be

Good point.

> Should I merge your patch directly?

You can do. I thought it was a bit small to bother with a PR but I can open one if you prefer
