### ISSUE TITLE
Nebula.tv is an unrecognised domain, should be treated the same as nebula.app

### ISSUE THREAD

**Issue by tannertechnology** [yt-dlp/yt-dlp#4917]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.09.01** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Provide a description that is worded well enough to be understood

If you paste a link to nebula.tv yt-dlp returns Unsupported URL. If you change the nebula.tv link to nebula.app everything works as anticipated. Logic should be added to treat nebula.tv the same as nebula.app.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
ERROR: Unsupported URL: https://nebula.tv/videos/polymatter-the-myth-that-china-lifted-800-million-people-out-of-poverty
```

**Comment by Jimi-James** [comment]
It's a good thing nebula.app still functions as a domain, because in the meantime I seem to be unable to workaround this by forcing use of a specific extractor. Why is this argument not working?

```
$ youtube-dl -F --use-extractors "nebula.*" "https://nebula.tv/videos/rareearth-the-remote-island-with-a-statue-that-nobody-can-explain/"
ERROR: No suitable extractor found for URL https://nebula.tv/videos/rareearth-the-remote-island-with-a-statue-that-nobody-can-explain/
```

**Comment by pukkandan** [comment]
You cannot "force" the use of an extractor. Extractors cannot do anything with URL patterns they don't understand. `--use-extractors` only restricts the possible extractors to the given list

**Comment by Lamieur** [comment]
Calling @hheimbuerger :)

I got it to work in 30 seconds, just s/nebula.app/nebula.tv/g + adding "|nebula\.tv" to _VALID_URL

I don't know how to even check if tests pass, but .netrc login worked, it remembers auth token in my yt-dlp cookies, it really seems nothing changed but the domain name.

**Comment by tannertechnology** [comment]
@Lamieur check the PR linked to this issue
