### ISSUE TITLE
[Twitter] Platform posted on support

### ISSUE THREAD

**Issue by Jadoo4QFan** [yt-dlp/yt-dlp#4926]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a site-specific feature
- [X] I've verified that I'm running yt-dlp version **2022.09.01** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

California, USA

### Example URLs

https://mobile.twitter.com/Unknown_Tags/status/1537089670504398849

### Provide a description that is worded well enough to be understood

Please extract the platform that the video was posted on. For example, Twitter for Android, Twitter for iPhone, etc.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp
Unknown_Tags/status/1537089670504398849 -s -vU 

debug] Command-line config: ['https://mobile.t
witter.com/Unknown_Tags/status/1537089670504398849', '-s', '-vU', '-j']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.09.01 [5d7c7d6] (pip)
[debug] Python 3.9.10+ (CPython 64bit) - macOS-15.4.1-iPhone14,5-arm-64bit 
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg n5.0.1-4-ga5ebb3d25e (setts), ffprobe n5.0.1-4-ga5ebb3d25e, phantomjs present, rtmpdump present
[debug] Optional libraries: Crypto-3.15.0, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1670 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.09.01, Current version: 2022.09.01
yt-dlp is up to date (2022.09.01)
[debug] [twitter] Extracting URL: https://mobile.twitter.com/Unknown_Tags/status/1537089670504
398849
[twitter] 1537089670504398849: Downloading gues
t token
[twitter] 1537089670504398849: Downloading JSON
 metadata
[debug] Sort order given by extractor: res, br,
 size, proto
[debug] Formats sorted by: hasvid, ie_pref, res
, tbr, vbr, abr, filesize, fs_approx, proto, la
ng, quality, fps, hdr:12(7), vcodec:vp9.2(10), 
channels, acodec, asr, vext, aext, hasaud, sour
ce, id
[debug] Default format spec: bestvideo*+bestaud
io/best

```

**Comment by pukkandan** [comment]
I don't understand. Please elaborate

**Comment by pukkandan** [comment]
There is currently no field for this. Do you have any suggestions for what field can be created to handle this? Note that the field should make sense to be generalized to more websites. If you cannot think of any such generalization, then the data is out of scope for us

**Comment by Jadoo4QFan** [comment]
Name the field “platform” or “platform-posted-on”

**Comment by nixxo** [comment]
`uploader_client` or `upload_client` maybe?

**Comment by Jadoo4QFan** [comment]
> `uploader_client` or `upload_client` maybe?

Yes

**Comment by Jadoo4QFan** [comment]
> There is currently no field for this. Do you have any suggestions for what field can be created to handle this? Note that the field should make sense to be generalized to more websites. If you cannot think of any such generalization, then the data is out of scope for us

So how far does the “info standardization” rule go? For example, does it have to be used in more than one site if it is still standardized?

**Comment by pukkandan** [comment]
It doesn't have to be used in other extractors right now. But it should make sense to be generalizable. We don't want to end up with `star_count`, `thumbsup_count` and `heart_count` for what should just be a single `like_count`. It would help if you can point out other sites where the same field can be used even if those sites arent supported atm
