### ISSUE TITLE
[YouTube] Report History

### ISSUE THREAD

**Issue by Jadoo4QFan** [yt-dlp/yt-dlp#4929]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a site-specific feature
- [X] I've verified that I'm running yt-dlp version **2022.09.01** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

California, USA

### Example URLs

youtube.com/reporthistory 

### Provide a description that is worded well enough to be understood

Make a feature to download the report history video list, as well as embed the report reason and report date in the info json. Remember report histories have more than a page sometimes!

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp https://www.youtube.com/rep
orthistory
[generic] reporthistory: Downloading webpage
WARNING: [generic] Falling back on generic info
rmation extractor
[generic] reporthistory: Extracting information
ERROR: Unsupported URL: https://www.youtube.com
/reporthistory
[Documents]$ yt-dlp https://www.youtube.com/rep
orthistory -v 
[debug] Command-line config: ['https://www.yout
ube.com/reporthistory', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, pref
 UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.09.01 [5d7c7d6] (pi
p)
[debug] Python 3.9.10+ (CPython 64bit) - macOS-
15.4.1-iPhone14,5-arm-64bit 
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg n5.0.1-4-ga5ebb3d25e (setts), ffprobe n5.0.1-4-ga5ebb3d25e, phantomjs present, rtmpdump present
[debug] Optional libraries: Crypto-3.15.0, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1670 extractors
[debug] [generic] Extracting URL: https://www.youtube.com/reporthistory
[generic] reporthistory: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] reporthistory: Extracting information
[debug] Looking for Brightcove embeds
[debug] Looking for embeds
ERROR: Unsupported URL: https://www.youtube.com/reporthistory
Traceback (most recent call last):
  File "/var/mobile/Containers/Data/Application/87BE3170-A2E1-4D77-98F2-3C7FE2FA6E42/Library/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1459, in wrapper
    return func(self, *args, **kwargs)
  File "/var/mobile/Containers/Data/Application/87BE3170-A2E1-4D77-98F2-3C7FE2FA6E42/Library/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1535, in __extract_info
    ie_result = ie.extract(url)
  File "/var/mobile/Containers/Data/Application/87BE3170-A2E1-4D77-98F2-3C7FE2FA6E42/Library/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 670, in extract
    ie_result = self._real_extract(url)
  File "/var/mobile/Containers/Data/Application/87BE3170-A2E1-4D77-98F2-3C7FE2FA6E42/Library/lib/python3.9/site-packages/yt_dlp/extractor/generic.py", line 3078, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.youtube.com/reporthistory
[Documents]$ 

Note: would rather not put my account cookie for privacy reasons. My Google account holds almost my entire life.
```

**Comment by Jadoo4QFan** [comment]
> ### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE
> * [x]  I understand that I will be **blocked** if I remove or skip any mandatory* field
> 
> ### Checklist
> * [x]  I'm requesting a site-specific feature
> * [x]  I've verified that I'm running yt-dlp version **2022.09.01** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
> * [x]  I've checked that all provided URLs are playable in a browser with the same IP and same login details
> * [x]  I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
> * [x]  I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
> * [ ]  I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required
> 
> ### Region
> California, USA
> 
> ### Example URLs
> youtube.com/reporthistory
> 
> ### Provide a description that is worded well enough to be understood
> Make a feature to download the report history video list, as well as embed the report reason and report date in the info json. Remember report histories have more than a page sometimes!
> 
> ### Provide verbose output that clearly demonstrates the problem
> * [x]  Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
> * [x]  Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below
> 
> ### Complete Verbose Output
> ```shell
> yt-dlp https://www.youtube.com/rep
> orthistory
> [generic] reporthistory: Downloading webpage
> WARNING: [generic] Falling back on generic info
> rmation extractor
> [generic] reporthistory: Extracting information
> ERROR: Unsupported URL: https://www.youtube.com
> /reporthistory
> [Documents]$ yt-dlp https://www.youtube.com/rep�
> orthistory -v 
> [debug] Command-line config: ['https://www.yout
> ube.com/reporthistory', '-v']
> [debug] Encodings: locale UTF-8, fs utf-8, pref
>  UTF-8, out utf-8, error utf-8, screen utf-8
> [debug] yt-dlp version 2022.09.01 [5d7c7d6] (pi
> p)
> [debug] Python 3.9.10+ (CPython 64bit) - macOS-
> 15.4.1-iPhone14,5-arm-64bit 
> [debug] Checking exe version: ffmpeg -bsfs
> [debug] Checking exe version: ffprobe -bsfs
> [debug] exe versions: ffmpeg n5.0.1-4-ga5ebb3d25e (setts), ffprobe n5.0.1-4-ga5ebb3d25e, phantomjs present, rtmpdump present
> [debug] Optional libraries: Crypto-3.15.0, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
> [debug] Proxy map: {}
> [debug] Loaded 1670 extractors
> [debug] [generic] Extracting URL: https://www.youtube.com/reporthistory
> [generic] reporthistory: Downloading webpage
> WARNING: [generic] Falling back on generic information extractor
> [generic] reporthistory: Extracting information
> [debug] Looking for Brightcove embeds
> [debug] Looking for embeds
> ERROR: Unsupported URL: https://www.youtube.com/reporthistory
> Traceback (most recent call last):
>   File "/var/mobile/Containers/Data/Application/87BE3170-A2E1-4D77-98F2-3C7FE2FA6E42/Library/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1459, in wrapper
>     return func(self, *args, **kwargs)
>   File "/var/mobile/Containers/Data/Application/87BE3170-A2E1-4D77-98F2-3C7FE2FA6E42/Library/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1535, in __extract_info
>     ie_result = ie.extract(url)
>   File "/var/mobile/Containers/Data/Application/87BE3170-A2E1-4D77-98F2-3C7FE2FA6E42/Library/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 670, in extract
>     ie_result = self._real_extract(url)
>   File "/var/mobile/Containers/Data/Application/87BE3170-A2E1-4D77-98F2-3C7FE2FA6E42/Library/lib/python3.9/site-packages/yt_dlp/extractor/generic.py", line 3078, in _real_extract
>     raise UnsupportedError(url)
> yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.youtube.com/reporthistory
> [Documents]$ �
> 
> Note: would rather not put my account cookie for privacy reasons. My Google account holds almost my entire life.
> ```

A nice shortcut should be :ytreports

**Comment by pukkandan** [comment]
> Remember report histories have more than a page sometimes!

My own report history is just one page. So I have no way to implement paging support. Will add the rest

**Comment by coletdjnz** [comment]
> as well as embed the report reason and report date in the info json.

I think this is out of scope

> So I have no way to implement paging support.

I imagine it will be one of the two continuation forms we have seen, so it may work automagically with some of the existing code. I have no way of testing too, though.

**Comment by pukkandan** [comment]
> > as well as embed the report reason and report date in the info json.
> 
> I think this is out of scope

Agreed. I was just talking about implementing the video downloads
