### ISSUE TITLE
Possible bug (Crunchyroll)

### ISSUE THREAD

**Issue by HondaTooru97** [yt-dlp/yt-dlp#493]
![20210712_132116](https://user-images.githubusercontent.com/87310799/125279410-3603c580-e314-11eb-8bc4-5fbe91ffd6d5.jpg)

Initially I thought it was a connection problem, but now that error has been appearing for more than a week and I don't understand why O.o, could someone explain to me?

**Comment by pukkandan** [comment]
### IGNORING THE ISSUE TEMPLATE WILL RESULT IN ISSUE CLOSED AS INCOMPLETE

Create a new issue using the correct template with all necessary information including the `--verbose` output (NOT picture)
