### ISSUE TITLE
European Parliament Multimedia Centre (multimedia.europarl.europa.eu)

### ISSUE THREAD

**Issue by selfisekai** [yt-dlp/yt-dlp#4933]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.09.01** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

at least European Union, probably worldwide

### Example URLs

- full session: https://multimedia.europarl.europa.eu/pl/webstreaming/plenary-session_20220914-0900-PLENARY
- fragments: https://multimedia.europarl.europa.eu/en/event_20220914-0900-PLENARY_vd?start=20220914122648&end=20220914122800
- embed: https://webstreaming.europarl.europa.eu/ep/embed/embed.html?event=20220914-0900-PLENARY&language=en&autoplay=true&logo=true

### Provide a description that is worded well enough to be understood

DRM is asked by the website but not required, I successfully downloaded videos with a url I found in my browser's network logs: `yt-dlp https://d1asa0nzfd3bqt.cloudfront.net/groupc/live/bcaa1db4-76ef-7e06-8da7-839bd0ad1dbe/live.isml/.mpd\?t\=2022-09-14T12:26:48-2022-09-14T12:28:00 -f 'bestvideo+bestaudio[language=en]'`

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://multimedia.europarl.europa.eu/en/event_20220914-0900-PLENARY_vd?start=20220914122648&end=20220914122800']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.09.01 [5d7c7d6]
[debug] Python 3.10.7 (CPython 64bit) - Linux-5.15.67-0-lts-x86_64-with 
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 5.1.1 (setts), ffprobe 5.1.1
[debug] Optional libraries: Crypto-3.15.0, brotli-1.0.9, certifi-2022.06.15, sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Loaded 1670 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.09.01, Current version: 2022.09.01
yt-dlp is up to date (2022.09.01)
[debug] [generic] Extracting URL: https://multimedia.europarl.europa.eu/en/event_20220914-0900-PLENARY_vd?start=20220914122648&end=20220914122800
[generic] event_20220914-0900-PLENARY_vd?start=20220914122648&end=20220914122800: Downloading webpage
[redirect] Following redirect to https://multimedia.europarl.europa.eu/en/webstreaming/event_20220914-0900-PLENARY?start=20220914122648&end=20220914122800
[debug] [generic] Extracting URL: https://multimedia.europarl.europa.eu/en/webstreaming/event_20220914-0900-PLENARY?start=20220914122648&end=20220914122800
[generic] event_20220914-0900-PLENARY?start=20220914122648&end=20220914122800: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] event_20220914-0900-PLENARY?start=20220914122648&end=20220914122800: Extracting information
[debug] Looking for Brightcove embeds
[debug] Looking for embeds
ERROR: Unsupported URL: https://multimedia.europarl.europa.eu/en/webstreaming/event_20220914-0900-PLENARY?start=20220914122648&end=20220914122800
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1459, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1535, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 670, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.10/site-packages/yt_dlp/extractor/generic.py", line 3078, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://multimedia.europarl.europa.eu/en/webstreaming/event_20220914-0900-PLENARY?start=20220914122648&end=20220914122800
```

**Comment by gamer191** [comment]
> at least European Union, probably worldwide

I can access it here in Australia, so it's definitely not geoblocked


> DRM is asked by the website but not required

I can confirm

**Comment by gamer191** [comment]
@pukkandan Oh, that message wasn't meant to be me triaging this (also, I didn't attempt to reproduce the issue)

**Comment by gamer191** [comment]
1. I'm not sure what the process of triaging an issue even involves (just that it involves reproducing the issue)
2. Theoretically I could check if I can reproduce the generic extractor not supporting that site

**Comment by pukkandan** [comment]
@gamer191 Triaging site request involve:
1. Try to confirm if it's actually a site request. Often site-bug tends to get reported as site request. Though, there are also circumstances where it can be difficult for even devs to distinguish them.
2. Check if the video is playable in browser (without DRM)
3. Make sure the site is not for piracy
4. Add relevant labels for geo-blocked and account-needed

Trying to reproduce isn't often needed when the log is properly filled up. I'm only looking for user errors and tend to assume lack of any malicious intend. So when the posted log has updated yt-dlp and says unsupported URL, it is blindly trusted

So yes, you did triage it even if that wasn't your intention

**Comment by gpt4thewin** [comment]
It seems the duration is not extracted when it is available (it is for non live content).

See this example
`yt-dlp --write-info-json --skip-download "https://multimedia.europarl.europa.eu/fr/webstreaming/econ-committee-meeting_20231204-1530-COMMITTEE-ECON"`

**Comment by gpt4thewin** [comment]
Is it possible to add support this url :
```
https://multimedia.europarl.europa.eu/en/video/press-conference-by-sabine-verheyen-epp-de-lead-rapporteur-and-ramona-strugariu-renew-ro-opinion-rapporteur-ernest-urtasun-spanish-minister-for-culture-and-vera-jourova-vice-president-of-the-european-commission_I250920
```

_Note: I forced matching the extractor, it didn't work_

**Comment by bashonly** [comment]
@gpt4thewin open a new issue or issues
