### ISSUE TITLE
Simply add a string into a tag field

### ISSUE THREAD

**Issue by thomas-mc-work** [yt-dlp/yt-dlp#4934]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.09.01** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I only want to add a simple string into the description field of the target file. I failed using the parameter `--replace-in-metadata`, since there wasn't anything to replace.

Example: `yt-dlp --add-tag "description:my custom string" https://…`

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
Read https://github.com/yt-dlp/yt-dlp#modifying-metadata

**Comment by pukkandan** [comment]
Did you even read the link I gave? What you want is `--parse-metadata`, not `--replace-in-metadata`

    --parse-meta "ABC :%(meta_description)s "

**Comment by gamer191** [comment]
> Given the following example:
> 
> ```
> yt-dlp -v --add-metadata --replace-in-metadata 'description' '(.*)' 'ABC' --extract-audio https://yewtu.be/watch?v=wZpIR4pzTPs
> ```
> 
> My goal is to have the string "ABC" in the description

Off topic, but just so you know, yt-dlp doesn't support invidious, and will instead silently redirect the videos to youtube, see https://github.com/yt-dlp/yt-dlp/issues/3053

**Comment by thomas-mc-work** [comment]
Yes, multiple times. And I wouldn't ever have concluded that `--parse-metadata` is the way to go, since there is nothing to parse. 

Anyway, your hint didn't work. Description still shows the URL.

**Comment by pukkandan** [comment]
Show verbose

**Comment by thomas-mc-work** [comment]
```
$ yt-dlp -v --add-metadata --parse-meta "ABC :%(meta_description)s " --extract-audio https://www.youtube.com/watch?v=AH961FlVH4E
[debug] Command-line config: ['-v', '--add-metadata', '--parse-meta', 'ABC :%(meta_description)s ', '--extract-audio', 'https://www.youtube.com/watch?v=AH961FlVH4E']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.07.18 [135f05e]
[debug] Python 3.8.10 (CPython 64bit) - Linux-5.4.0-125-generic-x86_64-with-glibc2.29 (glibc 2.31)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.2.7, ffprobe 4.2.7, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.9.8, brotli-1.0.9, certifi-2019.11.28, mutagen-1.45.0, pyxattr-0.6.1, secretstorage-2.3.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=AH961FlVH4E
[youtube] AH961FlVH4E: Downloading webpage
[youtube] AH961FlVH4E: Downloading android player API JSON
[youtube] AH961FlVH4E: Downloading MPD manifest
[youtube] AH961FlVH4E: Downloading MPD manifest
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[debug] Searching for '(?P<meta_description>.+)\\ ' in 'ABC '
[MetadataParser] Parsed meta_description from 'ABC ': 'ABC'
[info] AH961FlVH4E: Downloading 1 format(s): 251
[debug] Invoking http downloader on "https://rr3---sn-i5heen7d.googlevideo.com/videoplayback?expire=1663355170&ei=wnQkY6yEM4aP1wK4tqXICQ&ip=77.10.161.178&id=o-AIpaK_axyujk3kTX0TCoAFnuf1Bkkt--W9Eu0NVdzadl&itag=251&source=youtube&requiressl=yes&mh=vR&mm=31%2C29&mn=sn-i5heen7d%2Csn-i5h7lnll&ms=au%2Crdu&mv=m&mvi=3&pl=18&initcwndbps=1206250&vprv=1&mime=audio%2Fwebm&gir=yes&clen=422135&otfp=1&dur=27.701&lmt=1564484476675782&mt=1663333262&fvip=3&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&rbqsm=fr&txp=2201222&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cotfp%2Cdur%2Clmt&sig=AOq0QJ8wRQIhAPgs19IOrY3oYe-PLNQ4BpPeewFfS33Hsl0bC8zSgL6bAiBSfNBkdyVMwXCoclXjDorpzazI6eTsyVlHeqhNBnc0qw%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgaQJIVF3X-UnxwtLRNKhcR87zIaEpWvccHRaD0ocHstsCIHp8VKM04rXmadQix1iXsRyXex70NWJwFKwZ2g5x1Y4f"
[download] Destination: Quick-Demo - Groove Drum Co. Mahogany Bop Kit 18,12,14' [AH961FlVH4E].webm
[download] 100% of 412.24KiB in 00:00
[debug] ffmpeg command line: ffprobe -show_streams 'file:Quick-Demo - Groove Drum Co. Mahogany Bop Kit 18,12,14'"'"' [AH961FlVH4E].webm'
[ExtractAudio] Destination: Quick-Demo - Groove Drum Co. Mahogany Bop Kit 18,12,14' [AH961FlVH4E].opus
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:Quick-Demo - Groove Drum Co. Mahogany Bop Kit 18,12,14'"'"' [AH961FlVH4E].webm' -vn -acodec copy -movflags +faststart 'file:Quick-Demo - Groove Drum Co. Mahogany Bop Kit 18,12,14'"'"' [AH961FlVH4E].opus'
Deleting original file Quick-Demo - Groove Drum Co. Mahogany Bop Kit 18,12,14' [AH961FlVH4E].webm (pass -k to keep)
[Metadata] Adding metadata to "Quick-Demo - Groove Drum Co. Mahogany Bop Kit 18,12,14' [AH961FlVH4E].opus"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:Quick-Demo - Groove Drum Co. Mahogany Bop Kit 18,12,14'"'"' [AH961FlVH4E].opus' -map 0 -dn -ignore_unknown -c copy -write_id3v1 1 -metadata 'title=Quick-Demo - Groove Drum Co. Mahogany Bop Kit 18,12,14"' -metadata date=20190730 -metadata description=ABC -metadata 'synopsis=Mahogany shells, 18x14" BD with Maple Hoops, 12x6" Tom Tom and a 14x10" Floor Tom. 1,6mm Hoops, Vintage Tom Holder, Remo Heads. 30º Round over edges.
WWW.GROOVEDRUMCO.COM' -metadata 'purl=https://www.youtube.com/watch?v=AH961FlVH4E' -metadata 'comment=https://www.youtube.com/watch?v=AH961FlVH4E' -metadata 'artist=Groove Drum Company' -movflags +faststart 'file:Quick-Demo - Groove Drum Co. Mahogany Bop Kit 18,12,14'"'"' [AH961FlVH4E].temp.opus'
```

**Comment by pukkandan** [comment]
> -metadata description=ABC 

yt-dlp is writing the correct description. Why do you think it isn't?

If you are depending on your video player to see the fields, it is possible that what the player calls "Description" is what ffmpeg calls `comment`. So you'll need to tweak the command accordingly

**Comment by thomas-mc-work** [comment]
I couldn't see it when investigating using kid3qt. But your latest comment helped me find the solution: `--parse-meta "ABC :%(meta_comment)s "`.

Thank you for your patience!
