### ISSUE TITLE
OS environment variable

### ISSUE THREAD

**Issue by lollita** [yt-dlp/yt-dlp#4938]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.09.01** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Do it is possible to add support for OS environment variable (f.e. %TEMP% in windows)?

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
Add support where? Elaborate

**Comment by lollita** [comment]
In command line or config file.
F.e.
--ffmpeg-location %CommonProgramFiles%\\ffmpeg
--config-location %APPDATA%\youtube-dl-Video.conf

**Comment by pukkandan** [comment]
The OS should already expand it in commandline. In config, path-like options (--cache, -o, -P etc) allow  them, but other options don't. I noticed that `--ffmpeg-location` doesnt support it currently. I can add it just for that option

**Comment by lollita** [comment]
You are right.
Command line work.
If you can add "--ffmpeg-location" it would be very useful.

**Comment by lollita** [comment]
Ty.

**Comment by lollita** [comment]
I installed
python -m pip install --force-reinstall https://github.com/yt-dlp/yt-dlp/archive/master.tar.gz
but os env for ffmpeg not work: ffmpeg could not be found

**Comment by pukkandan** [comment]
Pull from master again, and try with `$var`. The config file is treated like a UNIX shell

**Comment by lollita** [comment]
It now is working, also for cookie.
Ty.
I not undstand _try with $var_.

**Comment by pukkandan** [comment]
nvm, both are accepted
