### ISSUE TITLE
Beginning Extractor

### ISSUE THREAD

**Issue by lollita** [yt-dlp/yt-dlp#4943]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.09.01** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I have a simple HTML page with m3u8 link to download that I can extract with a RegEx.
I read the extractor tutorial, but it is very complicated.
Do it have a more simple template to adapt to my case to try to implement?

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
Not really, no. Each site is very different that the only common boilerplate is the template given in Contributing.md. You can find an existing extractor that is similar to the one you are trying to add use that as a starting point.

**Comment by lollita** [comment]
Where i find a estractor list to see?
I simple have to:
Load url
parse a RegEx
Download m3u8 result

**Comment by pukkandan** [comment]
https://github.com/yt-dlp/yt-dlp/blob/master/yt_dlp/extractor

**Comment by lollita** [comment]
I'm tryng to test extractor in localhost to avoid band consume:
yt-dlp.exe --test -F http:/localhost:8080/test/Test.html
but i get:
_ERROR: [generic] Unable to download webpage: <urlopen error no host given> (caused by URLError('no host given'))_
Why?
the url work in browser.
