### ISSUE TITLE
What does the P stand for?

### ISSUE THREAD

**Issue by Jadoo4QFan** [yt-dlp/yt-dlp#4951]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.09.01** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

What does the p stand for in YT-DLP? I know the YT and DL means (YouTube Downloader), but what does the p mean? Plus, Pro, Pukkandan, etc?

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
This does not describe any problem.
```

**Comment by clusterized** [comment]
_Patched_?

**Comment by pukkandan** [comment]
https://www.reddit.com/r/youtubedl/comments/q7a8h6/what_is_meaning_of_p_in_ytdlp/

**Comment by pukkandan** [comment]
> _Patched_?

There is a different fork ytdl-patched 🤣
