### ISSUE TITLE
Piano Adventures

### ISSUE THREAD

**Issue by Jadoo4QFan** [yt-dlp/yt-dlp#4955]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.09.01** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

California, USA

### Example URLs

https://pianoadventures.com/products/piano-adventures-primer-level-lesson-book-enhanced-cd/
https://pianoadventures.com/products/piano-adventures-level-1-lesson-book-enhanced-cd/
https://pianoadventures.com/products/piano-adventures-level-2a-lesson-book-enhanced-cd/
https://pianoadventures.com/products/piano-adventures-level-2b-lesson-book-enhanced-cd/
Example to drop an error: https://pianoadventures.com/products/piano-adventures-level-3a-lesson-book-enhanced-cd/

### Provide a description that is worded well enough to be understood

Please add support for extracting Piano Adventures songs from the store page.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[Documents]$ yt-dlp https://pianoadventures.com
/products/piano-adventures-level-1-lesson-book-
enhanced-cd/ -vU 
[debug] Command-line config: ['https://pianoadv
entures.com/products/piano-adventures-level-1-l
esson-book-enhanced-cd/', '-vU']
[debug] Encodings: locale UTF-8, fs utf-8, pref
 UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.09.01 [5d7c7d6] (pi
p)
[debug] Python 3.9.10+ (CPython 64bit) - macOS-
15.4.1-iPhone14,5-arm-64bit 
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg n5.0.1-4-ga5ebb3d25e (setts), ffprobe n5.0.1-4-ga5ebb3d25e, phantomjs present, rtmpdump present
[debug] Optional libraries: Crypto-3.15.0, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1670 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.09.01, Current version: 2022.09.01
yt-dlp is up to date (2022.09.01)
[debug] [generic] Extracting URL: https://pianoadventures.com/products/piano-adventures-level-1-lesson-book-enhanced-cd/
[generic] piano-adventures-level-1-lesson-book-enhanced-cd: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] piano-adventures-level-1-lesson-book-enhanced-cd: Extracting information
[debug] Looking for Brightcove embeds
[debug] Looking for embeds
ERROR: Unsupported URL: https://pianoadventures.com/products/piano-adventures-level-1-lesson-book-enhanced-cd/
Traceback (most recent call last):
  File "/var/mobile/Containers/Data/Application/87BE3170-A2E1-4D77-98F2-3C7FE2FA6E42/Library/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1459, in wrapper
    return func(self, *args, **kwargs)
  File "/var/mobile/Containers/Data/Application/87BE3170-A2E1-4D77-98F2-3C7FE2FA6E42/Library/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1535, in __extract_info
    ie_result = ie.extract(url)
  File "/var/mobile/Containers/Data/Application/87BE3170-A2E1-4D77-98F2-3C7FE2FA6E42/Library/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 670, in extract
    ie_result = self._real_extract(url)
  File "/var/mobile/Containers/Data/Application/87BE3170-A2E1-4D77-98F2-3C7FE2FA6E42/Library/lib/python3.9/site-packages/yt_dlp/extractor/generic.py", line 3078, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://pianoadventures.com/products/piano-adventures-level-1-lesson-book-enhanced-cd/
```

**Comment by jhwgh1968** [comment]
This site appears to use a [very obscure open source audio player](https://mymediaelements.github.io/mejs-player/).

This is not currently detected by current embeds, because the audio is linked with `<a>` tags, with either `href` or `data-value` attributes with the audio URL. They are otherwise completely unremarkable compared to any other link on the page, and so are skipped over.

This would not seem difficult to add support for. The tricky part would be not slowing down generic extractor for nearly any other website, which would be the effect of obvious ways to support this.

**Comment by pukkandan** [comment]
Like you said, that sounds too broad for generic extractor. It's better to have a dedicated extractor for this

**Comment by coletdjnz** [comment]
This look to be using some wordpress playlist, where the metadata and streaming urls are all contained within what seems to be a standarized JSON payload (wp-playlist-script). So I think this can be made generic.

```html
<script type="application/json" class="wp-playlist-script">{"type":"audio","tracklist":true,"tracknumbers":true,"images":false,"artists":false,"tracks":[{"src":"https:\/\/pianoadventures.com\/wp-content\/uploads\/sites\/13\/2015\/11\/CD1001-03.mp3","type":"audio\/mpeg","title":"03 The Old Clock","caption":"","description":"\"03 The Old C[...]
```

https://github.com/birgire/wpse-playlist
Demo with multiple playlists: https://xlino.com/wordpress-playlist-shortcode-with-external-audio-or-video-files/

> This site appears to use a [very obscure open source audio player](https://mymediaelements.github.io/mejs-player/).

This looks to be generated at runtime from the wordpress playlist data above
