### ISSUE TITLE
Keys for progress in the --progress-template

### ISSUE THREAD

**Issue by nmills3** [yt-dlp/yt-dlp#4956]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.09.01** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

What are the available keys in the progress object or the progress template? The readme doesn't seem to mention it and the only bit i can find in the source code just had a todo saying to document it in the readme. I know from the info in the readme that it has an eta key but are there keys for things like the download percentage?

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
not reporting an issue
```

**Comment by pukkandan** [comment]
Easiest way to find out is to just try and print it
```
❯ yt-dlp test:youtube --force-over --newline --progress-template %(progress)j
[TestURL] Test URL: https://www.youtube.com/watch?v=BaW_jenozKc&t=1s&end=9
[youtube] BaW_jenozKc: Downloading webpage
[youtube] BaW_jenozKc: Downloading android player API JSON
[info] BaW_jenozKc: Downloading 1 format(s): 248+251
[download] Destination: youtube-dl test video ＂'⧸⧹ä↭𝕐 [BaW_jenozKc].f248.webm
{"status": "downloading", "downloaded_bytes": 1024, "total_bytes": 988479, "tmpfilename": "youtube-dl test video ＂'⧸⧹ä↭𝕐 [BaW_jenozKc].f248.webm.part", "filename": "youtube-dl test video ＂'⧸⧹ä↭𝕐 [BaW_jenozKc].f248.webm", "eta": 1, "speed": 512342.51413575094, "elapsed": 0.10804963111877441, "ctx_id": null, "_eta_str": "\u001b[0;33m   00:01\u001b[0m", "_speed_str": "\u001b[0;32m 500.33KiB/s\u001b[0m", "_percent_str": "\u001b[0;94m  0.1%\u001b[0m", "_total_bytes_str": "965.31KiB", "_total_bytes_estimate_str": "N/A", "_downloaded_bytes_str": "\u001b[0;94m1.00KiB\u001b[0m", "_elapsed_str": "\u001b[1;37m   00:00\u001b[0m", "_default_template": "\u001b[0;94m  0.1%\u001b[0m of 965.31KiB at \u001b[0;32m 500.33KiB/s\u001b[0m ETA \u001b[0;33m   00:01\u001b[0m"}
...
```

If you are going to parse this, I suggest not relying on any of the fields that start with an `_`. The other fields should be sufficient

**Comment by nmills3** [comment]
thanks. that's all the info i needed

**Comment by pukkandan** [comment]
The fields in `progress` are pretty much these, but without info_dict

https://github.com/yt-dlp/yt-dlp/blob/19b4e59a1e1bf368078f90e7f735fa4576f97b64/yt_dlp/YoutubeDL.py#L347-L371

**Comment by Akczht** [comment]
is there a way I can get thr default progress template remove the [download] in the start and eta from the end
