### ISSUE TITLE
yt-dlp doesn't get all video formats

### ISSUE THREAD

**Issue by KastriotH** [yt-dlp/yt-dlp#4959]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.09.01** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Hello, when i want to download from this live stream 4K quality, yt-dlp doesn't report/detects additional 1440p&2160p, also this happens on other 4K live streams, for normal videos ie non streaming everything is OK.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '-f', '-', 'https://www.youtube.com/watch?v=HpZAez2oYsA']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.09.01 [5d7c7d6] (win32_exe)
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.22622-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 2021-07-04-git-301d275301-full_build-www.gyan.dev (setts), ffprobe 2021-07-04-git-301d275301-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1670 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.09.01, Current version: 2022.09.01
yt-dlp is up to date (2022.09.01)
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=HpZAez2oYsA
[youtube] HpZAez2oYsA: Downloading webpage
[youtube] HpZAez2oYsA: Downloading android player API JSON
[youtube] HpZAez2oYsA: Downloading m3u8 information
[youtube] HpZAez2oYsA: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[info] Available formats for HpZAez2oYsA:
ID EXT RESOLUTION FPS │   TBR PROTO │ VCODEC        VBR ACODEC    ABR
─────────────────────────────────────────────────────────────────────
91 mp4 256x144     15 │  290k m3u8  │ avc1.42c00b  290k mp4a.40.5  0k
92 mp4 426x240     30 │  546k m3u8  │ avc1.4d4015  546k mp4a.40.5  0k
93 mp4 640x360     30 │ 1210k m3u8  │ avc1.4d401e 1210k mp4a.40.2  0k
94 mp4 854x480     30 │ 1569k m3u8  │ avc1.4d401f 1569k mp4a.40.2  0k
95 mp4 1280x720    30 │ 2969k m3u8  │ avc1.4d401f 2969k mp4a.40.2  0k
96 mp4 1920x1080   30 │ 5421k m3u8  │ avc1.640028 5421k mp4a.40.2  0k
```

**Comment by heroku-miraheze** [comment]
https://www.avpasion.com/youtube-premium-contenido-4k/

**Comment by pukkandan** [comment]
YouTube only offers higher quality formats as DASH streams. yt-dlp can download these only with `--live-from-start`
