### ISSUE TITLE
Modular Cashing Handler (Redis)

### ISSUE THREAD

**Issue by Commandcracker** [yt-dlp/yt-dlp#4960]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.09.01** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Currently the the [Cashing Handler](https://github.com/yt-dlp/yt-dlp/blob/master/yt_dlp/cache.py) is cashing to a file/folder (that can be changed),
it can only be disabled and enabled,
and [the Cashing Handler cant be changed](https://github.com/yt-dlp/yt-dlp/blob/19b4e59a1e1bf368078f90e7f735fa4576f97b64/yt_dlp/YoutubeDL.py#L584).

It would be nice to handle cashing like in [spotipy](https://github.com/plamere/spotipy/blob/master/spotipy/cache_handler.py).
```python
from spotipy import Spotify, SpotifyClientCredentials, MemoryCacheHandler
from redis import Redis

redis = Redis(host='localhost', port=6379, db=0, password="*****")

spotipy = Spotify(
    auth_manager=SpotifyClientCredentials(
        client_id="*****",
        client_secret="*****",
        cache_handler=RedisCacheHandler(redis, "spotipy_token_info")
    )
)
```

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
Explain the use-case

**Comment by Commandcracker** [comment]
Use Cases:
- a discord bot
- an application that servers as a server to provide info about videos
- every application that uses yt-dlp to provide a large amount of users

**Comment by pukkandan** [comment]
You didn't explain anything... It actually sounds like you have no clue how yt-dlp even uses cache and are just suggesting this because it sounds like a "cool" idea. If you have an actual usecase that YOU want to use, explain it. Make sure to read this first: https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-anyone-going-to-need-the-feature

**Comment by pukkandan** [comment]
Actually, this is Python! You can already use other cache handlers. Just set `ydl.cache = ...` and make sure your cache objects implements the same interface as the in-built cache. Since the variable wasn't named `_cache`, but `cache`, you can treat it as a public member by convention
