### ISSUE TITLE
[zeenews.india.com] Site support request.

### ISSUE THREAD

**Issue by angentanewbe** [yt-dlp/yt-dlp#4967]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.09.01** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

India

### Example URLs

https://zeenews.india.com/hindi/world/video/the-china-files-how-did-xi-jinping-become-the-most-powerful-and-only-leader-of-chinas-power/1322750

https://zeenews.india.com/hindi/india/video/videsh-superfast-queen-elizabeth-iis-funeral-today/1357710

### Provide a description that is worded well enough to be understood

Hello
Although I have no experience and mastery in programming yt-dlp. But it might be useful for you to know that the blob url is available for the video. for eg: 
blob:https://zeenews.india.com/605a3e30-d354-4358-84d5-3dfdebe6b539

I extracted this from "https://zeenews.india.com/hindi/world/video/the-china-files-how-did-xi-jinping-become-the-most-powerful-and-only-leader-of-chinas-power/1322750" this url.

It might be possible to get the video file from this url and can be easily downloaded through yt-dlp.
If this does not work then I apologize. 

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp -vU https://zeenews.india.com/hindi/world/video/the-china-files-how-did-xi-jinping-become-the-most-powerful-and-only-leader-of-chinas-power/1322750
[debug] Command-line config: ['-vU', 'https://zeenews.india.com/hindi/world/video/the-china-files-how-did-xi-jinping-become-the-most-powerful-and-only-leader-of-chinas-power/1322750']
[debug] User config "C:\Users\user\AppData\Roaming\yt-dlp\config.txt": ['--all-subs', '--embed-subs', '--embed-thumbnail', '--add-metadata', '--write-annotations', '--download-archive=All Youtube History.txt', '--write-annotations', '--write-description', '--write-info-json', '--write-thumbnail', '-f', 'bv+ba/best', '--merge-output-format', 'mp4', '-ciw', '--retries', 'infinite', '-o', '%(title)s-%(id)s-%(format_id)s.%(ext)s']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.09.01 [5d7c7d6] (win32_exe)
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.4-full_build-www.gyan.dev (setts), ffprobe 4.4-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1670 extractors
[debug] Loading archive file 'All Youtube History.txt'
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.09.01, Current version: 2022.09.01
yt-dlp is up to date (2022.09.01)
[debug] [generic] Extracting URL: https://zeenews.india.com/hindi/world/video/the-china-files-how-did-xi-jinping-become-the-most-powerful-and-only-leader-of-chinas-power/1322750
[generic] 1322750: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] 1322750: Extracting information
[debug] Looking for Brightcove embeds
[debug] Looking for embeds
ERROR: Unsupported URL: https://zeenews.india.com/hindi/world/video/the-china-files-how-did-xi-jinping-become-the-most-powerful-and-only-leader-of-chinas-power/1322750
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1459, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1535, in __extract_info
  File "yt_dlp\extractor\common.py", line 670, in extract
  File "yt_dlp\extractor\generic.py", line 3078, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://zeenews.india.com/hindi/world/video/the-china-files-how-did-xi-jinping-become-the-most-powerful-and-only-leader-of-chinas-power/1322750
```

**Comment by coletdjnz** [comment]
Appears to use Kaltura player but with it's own playback url and initialization process, so I don't think this can be generic or redirect to Kaltura IE.

streaming url can be extracted from `var videourl= "...";` (note the lack of space; relax the regex) 
thumbnail can be extracted from `var thumbnail = "..."`
video id can be extracted from `var mediaid = "..."`

description and upload date can be extracted from the html

e.g.
```
<h1>Namaste India : क्या PFI पर लगेगा बैन?  </h1><div class="articleauthor_details"><span class="aaticleauthor_name"></span><span class="padLR5">|</span><span>Updated: </span><span>Sep 24, 2022, 10:00 AM IST</span></div><div class="video_decription">NIA ने PFI पर बहुत बड़ा खुलासा किया है. PFI, मुस्लिम युवकों की भर्ती ISIS में कर रहा है और आतंकी हमले की साजिश रची जा रही थी.</div>
```

note that below the video appear to be "recommended" videos which appear as json ld video objects. These may include the current video. Also all include the m3u8 streaming url for some strange reason.
