### ISSUE TITLE
[Youtube] -ij --flat-playlist for Channels tab does not return the complete list of channels subscribed to

### ISSUE THREAD

**Issue by shoxie007** [yt-dlp/yt-dlp#4970]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.09.01** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

India

### Provide a description that is worded well enough to be understood

Example:
```yt-dlp -ij --flat-playlist "https://www.youtube.com/channel/UCqxoeXwW0IZoHTdyw49NQgg/channels" | jq -r '.title'```

should return 65 channels which the channel is subscribed to. Instead it only returns about 10 to 12 results. So basically, yt-dlp doesn't handle the continuation requests (to load the rest of the webpage with more channels) properly. I guess Youtube must have made changes to their source code, cos yt-dlp was working just a few days ago.

Anyway, please update yt-dlp's handling of the continuation of the loading of the webpage so that the remainder of the channels on the Channels tab can be captured. 

Thanks

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '-ij', '--flat-playlist', 'https://www.youtube.com/channel/UCqxoeXwW0IZoHTdyw49NQgg/channels']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8 (No ANSI), error utf-8, screen utf-8
[debug] yt-dlp version 2022.09.01 [5d7c7d6] (zip)
[debug] Python 3.8.10 (CPython 64bit) - Linux-5.4.72-microsoft-standard-WSL2-x86_64-with-glibc2.29 (glibc 2.31)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg n4.4-154-g79c114e1b2-20210923 (setts)
[debug] Optional libraries: certifi-2019.11.28, secretstorage-2.3.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1670 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.09.01, Current version: 2022.09.01
yt-dlp is up to date (2022.09.01)
[debug] [youtube:tab] Extracting URL: https://www.youtube.com/channel/UCqxoeXwW0IZoHTdyw49NQgg/channels
[youtube:tab] UCqxoeXwW0IZoHTdyw49NQgg: Downloading webpage
[debug] [youtube:tab] Final URL: https://www.youtube.com/channel/UCqxoeXwW0IZoHTdyw49NQgg/channels
[download] Downloading playlist: NeoEyeBeLeave - Channels
[youtube:tab] UCqxoeXwW0IZoHTdyw49NQgg page 1: Downloading API JSON
[youtube:tab] Playlist NeoEyeBeLeave - Channels: Downloading 10 videos of 10
[debug] The information of all playlist entries will be held in memory
[download] Downloading video 1 of 10
[download] Downloading video 2 of 10
SteveHoca
[download] Downloading video 3 of 10
GrizzlyRising News, Politics and opinion.
Jay Truth II
[download] Downloading video 4 of 10
Morph
[download] Downloading video 5 of 10
1on1 with Tommy Sotomayor
[download] Downloading video 6 of 10
Frozen Mgtow
[download] Downloading video 7 of 10
[download] Downloading video 8 of 10
Shakaama
[download] Downloading video 9 of 10
SUBHA CHOWDHURY
Bachelor Insight
[download] Downloading video 10 of 10
RadioClassics
[download] Finished downloading playlist: NeoEyeBeLeave - Channels
```

**Comment by pukkandan** [comment]
Was fixed by 1fb53b946c5aca3755bf72cc1c204925043b04f7
