### ISSUE TITLE
Consider adding a GUI to yt-dlp

### ISSUE THREAD

**Issue by rubyFeedback** [yt-dlp/yt-dlp#4972]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.09.01** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

It is suggested to add a GUI to yt-dlp, ideally with the same unified base code.

In particular for tk/tkinter and gtk3. Perhaps also a small add-on as a web-interface.

This would be useful on windows. On linux I can just use the commandline but
on windows it may be nice if one can offer this for elderly people who don't know
how to use the commandline there.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by rubyFeedback** [comment]
To clarify: I really propose a super SIMPLE interface:

- an entry box for input
- a button for the download activity
- a notification to indicate success or failure

That's it mostly for the base.

**Comment by pukkandan** [comment]
There are multiple third party GUIs available. There will never be one as part of yt-dlp itself

**Comment by coletdjnz** [comment]
in case anyone stumbles across this looking for a GUI: https://www.reddit.com/r/youtubedl/wiki/info-guis/

**Comment by dirkf** [comment]
Candidate for addition to Wiki FAQ?

**Comment by bashonly** [comment]
There is a stale PR to add a GUIs section the wiki. Anyone is free to take it over
