### ISSUE TITLE
How to download 135(video format) and 251(Audio format) and  return a merged output.mp4 in a single command?

### ISSUE THREAD

**Issue by AnirbanPatragithub** [yt-dlp/yt-dlp#4974]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.09.01** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

My approach While downloading videos from youtube
Check all the available formats with this code
`yt-dlp --no-playlist -F 'https://www.youtube.com/watch?v=MLARYBpFH40&list=PLZoTAELRMXVPiyueAqA_eQnsycC_DSBns&index=2'`

Format 135 is a video format and 251 is an audio format.

To download video:

`yt-dlp --no-playlist -f 135 'https://www.youtube.com/watch?v=MLARYBpFH40&list=PLZoTAELRMXVPiyueAqA_eQnsycC_DSBns&index=2'`

To download audio:

`yt-dlp --no-playlist -f 251 'https://www.youtube.com/watch?v=MLARYBpFH40&list=PLZoTAELRMXVPiyueAqA_eQnsycC_DSBns&index=2'`

I merge audio and video formats with

`ffmpeg -i 'Day 1- Live  Deep Learning Community Session [MLARYBpFH40].mp4' -i 'Day 1- Live  Deep Learning Community Session [MLARYBpFH40].webm' -c:v copy -c:a aac 'Day 1- Live  Deep Learning Community SessionC [MLARYBpFH40].mp4'
`

I need a one line code to download 135 and 251 formats and get the merged file as output.mp4

`
`

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by Lesmiscore** [comment]
`-f 135+251`

**Comment by gamer191** [comment]
If you need an MP4 file, use `-f 135+251 --merge-output-format mp4`, otherwise just use `-f 135+251` (the video format has to be on the left side of the `+`)
Since `251` is the highest quality audio format, you could also use `-f 135+bestaudio` (or `-f 135+ba`)

**Comment by Lesmiscore** [comment]
@Trit34 MP4 with H.264+Opus is possible. You can try by youself

**Comment by AnirbanPatragithub** [comment]
@Lesmiscore  @Trit34  @gamer191  
Thanks For the help.
It will be great if you include this even in the readme.md.

**Comment by Trit34** [comment]
> @Trit34 MP4 with H.264+Opus is possible. You can try by yourself

Already tried, but let’s say that by default, FFmpeg gives me a MKV file as a result when I try this combination.

**Comment by pukkandan** [comment]
![image](https://user-images.githubusercontent.com/6623388/191319382-638d02cb-aaa4-4f3e-88de-d1ced7ae721f.png)
https://github.com/yt-dlp/yt-dlp#format-selection
