### ISSUE TITLE
Update www.sciencechannel.com with link provider

### ISSUE THREAD

**Issue by sonzin** [yt-dlp/yt-dlp#4980]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.09.01** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

US

### Provide a description that is worded well enough to be understood

I tried by MSO DTV and ATT with my account but it asked account from Discovery Plus (i don't have this account), is there anyway use MSO to get download. Thanks

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--ap-mso', 'ATT', '--ap-username', 'PRIVATE', '--ap-password', 'PRIVATE', 'https://www.sciencechannel.com/video/unearthed-science/lost-city-of-persia', '--simulate', '--verbose']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.09.01 [5d7c7d6] (win32_exe)
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg N-108207-g4ba68639ca-20220919 (setts), ffprobe N-108207-g4ba68639ca-20220919
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1670 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.09.01, Current version: 2022.09.01
yt-dlp is up to date (2022.09.01)
[debug] [ScienceChannel] Extracting URL: https://www.sciencechannel.com/video/unearthed-science/lost-city-of-persia
[debug] Using fake IP 6.240.29.57 (US) as X-Forwarded-For
[ScienceChannel] unearthed-science/lost-city-of-persia: Downloading JSON metadata
ERROR: [ScienceChannel] unearthed-science/lost-city-of-persia: This video is only available for registered users. You may want to use --cookies.
  File "yt_dlp\extractor\common.py", line 670, in extract
  File "yt_dlp\extractor\dplay.py", line 367, in _real_extract
  File "yt_dlp\extractor\dplay.py", line 90, in _get_disco_api_info
  File "yt_dlp\extractor\dplay.py", line 48, in _process_errors
```

**Comment by Mr-Jake** [comment]
You have to use cookies. Username and password is not implemented for any of the Discovery sites.

You do not need a DiscoveryPlus account for Science. It will work using your cable tv account. Login using the browser and then have yt-dlp use cookies.

**Comment by leszekm1** [comment]
With cookies it's also broken:
[debug] Command-line config: ['-vU', '--cookies', 'co.txt', 'https://go.discovery.com/video/mythbusters-discovery/jet-assisted-chevy']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.09.01 [5d7c7d6] (win32_exe)
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg git-2020-03-27-e34157f, ffprobe git-2020-03-27-e34157f
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1670 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.09.01, Current version: 2022.09.01
yt-dlp is up to date (2022.09.01)
[debug] [GoDiscovery] Extracting URL: https://go.discovery.com/video/mythbusters-discovery/jet-assisted-chevy
[debug] Using fake IP 6.193.130.110 (US) as X-Forwarded-For
[GoDiscovery] mythbusters-discovery/jet-assisted-chevy: Downloading JSON metadata
ERROR: [GoDiscovery] mythbusters-discovery/jet-assisted-chevy: This video is only available for registered users. You may want to use --cookies.
  File "yt_dlp\extractor\common.py", line 670, in extract
  File "yt_dlp\extractor\dplay.py", line 367, in _real_extract
  File "yt_dlp\extractor\dplay.py", line 90, in _get_disco_api_info
  File "yt_dlp\extractor\dplay.py", line 48, in _process_errors

**Comment by Mr-Jake** [comment]
Cookies works for me.

Looking at the issues for "This video is only available for registered users. You may want to use --cookies." it seems other users reported it is caused by an invalid cookie or a region issue.

For example: 
Invalid cookie
https://github.com/yt-dlp/yt-dlp/issues/2233

Region
https://github.com/yt-dlp/yt-dlp/issues/2073

**Comment by sonzin** [comment]
> Cookies works for me.
> 
> Looking at the issues for "This video is only available for registered users. You may want to use --cookies." it seems other users reported it is caused by an invalid cookie or a region issue.
> 
> For example: Invalid cookie #2233
> 
> Region #2073



> 

Thank you, i tried nightly version and it worked ok with my cookies

**Comment by leszekm1** [comment]
same - nightly works.  TY!
