### ISSUE TITLE
Store timestamp/datetime of system before downloading video

### ISSUE THREAD

**Issue by AtticFinder65536** [yt-dlp/yt-dlp#4997]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.09.01** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

4cca2eb1bf8bb830df15cbcda21a93fe2392573a on master

Videos and video metadata often change over time (comments and likes changing, YouTuber edits something out after upload date). I want to store the date and time of when I ran yt-dlp, so I can specify it in the output template of a download and more easily differentiate between changes.

I could store the date/time of when I ran yt-dlp in an external script, but I run channel DL and playlist DL scripts which can take a long time to complete, so the extractor will start downloading later videos in the playlist/channel hours or days later the date/time of when I ran yt-dlp. My proposed solution is for yt-dlp to store the unix timestamp and/or date/time that the extractor begins downloading a video so that I can display it in the output template.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by coletdjnz** [comment]
There is an `epoch` key in the infojson
