### ISSUE TITLE
Please support https://www.rmcbfmplay.com/ tv channels

### ISSUE THREAD

**Issue by ytrezq** [yt-dlp/yt-dlp#4999]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.09.01** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

France

### Example URLs

https://www.rmcbfmplay.com/video/rmc-decouverte/retour-a-linstinct-primaire-s6/s6e1-lune-de-miel-dans-la-jungle?contentId=Product::NEUF_RMCDEC_RMC00174485&universe=PROVIDER

### Provide a description that is worded well enough to be understood

Please support downloading replays from https://www.rmcbfmplay.com/ as their player is ads bloated to the point of not working.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--xattrs', '--add-metadata', '--embed-thumbnail', '--embed-subs', '--no-continue', '--hls-prefer-native', '--audio-quality', '0', '--all-subs', 'https://www.rmcbfmplay.com/video/rmc-decouverte/retour-a-linstinct-primaire-s6/s6e1-lune-de-miel-dans-la-jungle']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.09.01 [5d7c7d656]
[debug] Lazy loading extractors is disabled
[debug] Python 3.11.0rc2 (CPython 64bit) - Linux-3.18.115-17011592-aarch64-with-glibc2.36.9000 (glibc 2.36.9000)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 5.1.1 (setts), ffprobe 5.1.1
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2021.10.08, mutagen-1.45.1, pyxattr-0.7.2, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1670 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.09.01, Current version: 2022.09.01
yt-dlp is up to date (2022.09.01)
[debug] [generic] Extracting URL: https://www.rmcbfmplay.com/video/rmc-decouverte/retour-a-linstinct-primaire-s6/s6e1-lune-de-miel-dans-la-jungle
[generic] s6e1-lune-de-miel-dans-la-jungle: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] s6e1-lune-de-miel-dans-la-jungle: Extracting information
[debug] Looking for Brightcove embeds
[debug] Looking for embeds
ERROR: Unsupported URL: https://www.rmcbfmplay.com/video/rmc-decouverte/retour-a-linstinct-primaire-s6/s6e1-lune-de-miel-dans-la-jungle
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1459, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1535, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 670, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/extractor/generic.py", line 3078, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.rmcbfmplay.com/video/rmc-decouverte/retour-a-linstinct-primaire-s6/s6e1-lune-de-miel-dans-la-jungle
```

**Comment by coletdjnz** [comment]
Duplicate: https://github.com/yt-dlp/yt-dlp/issues/3594

It looks like content of this site has DRM, so we cannot support it.

**Comment by ytrezq** [comment]
@coletdjnz some videos have drm but other ones can be played on my rooted Android device. Please reopen!
