### ISSUE TITLE
`--write-thumbnail` forces mkv to be used instead of webm even when `--embed-thumbnail` is not specified

### ISSUE THREAD

**Issue by colethedj** [yt-dlp/yt-dlp#500]
## Checklist

- [X] I'm reporting a broken site support issue
- [X] I've verified that I'm running yt-dlp version **2021.07.07**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar bug reports including closed ones
- [X] I've read bugs section in FAQ

## Verbose log

```
yt-dlp --verbose --write-thumbnail "https://www.youtube.com/watch?v=3v7DvR7mzog"
[debug] Command-line config: ['--verbose', '--write-thumbnail', 'https://www.youtube.com/watch?v=3v7DvR7mzog']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] yt-dlp version 2021.07.07 
[debug] Python version 3.9.5 (CPython 64bit) - Linux-5.12.9-1-MANJARO-x86_64-with-glibc2.33
[debug] exe versions: ffmpeg 4.4, ffprobe 4.4, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=3v7DvR7mzog
[youtube] 3v7DvR7mzog: Downloading webpage
[youtube] 3v7DvR7mzog: Downloading android player API JSON
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 3v7DvR7mzog: Downloading 1 format(s): 313+251
[youtube] 3v7DvR7mzog: Downloading thumbnail  ...
[youtube] 3v7DvR7mzog: Writing thumbnail to: Why Joey Blocked his Dad on All Social Media [3v7DvR7mzog].jpg
WARNING: webm doesn't support embedding a thumbnail, mkv will be used.
[debug] Invoking downloader on "REDACTED"
[download] Destination: Why Joey Blocked his Dad on All Social Media [3v7DvR7mzog].f313.webm
[download] 100% of 455.81MiB in 00:18
[debug] Invoking downloader on "REDACTED"
[download] Destination: Why Joey Blocked his Dad on All Social Media [3v7DvR7mzog].f251.webm
[download] 100% of 3.21MiB in 00:00
[Merger] Merging formats into "Why Joey Blocked his Dad on All Social Media [3v7DvR7mzog].mkv"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:Why Joey Blocked his Dad on All Social Media [3v7DvR7mzog].f313.webm' -i 'file:Why Joey Blocked his Dad on All Social Media [3v7DvR7mzog].f251.webm' -c copy -map 0:v:0 -map 1:a:0 'file:Why Joey Blocked his Dad on All Social Media [3v7DvR7mzog].temp.mkv'
Deleting original file Why Joey Blocked his Dad on All Social Media [3v7DvR7mzog].f313.webm (pass -k to keep)
Deleting original file Why Joey Blocked his Dad on All Social Media [3v7DvR7mzog].f251.webm (pass -k to keep)

```
Behaviour without `--write-thumbnail` for reference:

```
yt-dlp --verbose "https://www.youtube.com/watch?v=3v7DvR7mzog"                  
[debug] Command-line config: ['--verbose', 'https://www.youtube.com/watch?v=3v7DvR7mzog']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] yt-dlp version 2021.07.07 
[debug] Python version 3.9.5 (CPython 64bit) - Linux-5.12.9-1-MANJARO-x86_64-with-glibc2.33
[debug] exe versions: ffmpeg 4.4, ffprobe 4.4, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=3v7DvR7mzog
[youtube] 3v7DvR7mzog: Downloading webpage
[youtube] 3v7DvR7mzog: Downloading android player API JSON
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 3v7DvR7mzog: Downloading 1 format(s): 313+251
[debug] Invoking downloader on "REDACTED"
[download] Destination: Why Joey Blocked his Dad on All Social Media [3v7DvR7mzog].f313.webm
[download] 100% of 455.81MiB in 00:18
[debug] Invoking downloader on "REDACTED"
[download] Destination: Why Joey Blocked his Dad on All Social Media [3v7DvR7mzog].f251.webm
[download] 100% of 3.21MiB in 00:00
[Merger] Merging formats into "Why Joey Blocked his Dad on All Social Media [3v7DvR7mzog].webm"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:Why Joey Blocked his Dad on All Social Media [3v7DvR7mzog].f313.webm' -i 'file:Why Joey Blocked his Dad on All Social Media [3v7DvR7mzog].f251.webm' -c copy -map 0:v:0 -map 1:a:0 'file:Why Joey Blocked his Dad on All Social Media [3v7DvR7mzog].temp.webm'
Deleting original file Why Joey Blocked his Dad on All Social Media [3v7DvR7mzog].f313.webm (pass -k to keep)
Deleting original file Why Joey Blocked his Dad on All Social Media [3v7DvR7mzog].f251.webm (pass -k to keep)
```

## Description

Originally reported on discord.

`writethumbnail` is defined as `writethumbnail:    Write the thumbnail image to a file`.
However it seems to trigger use of mkv container if the video extension is webm, even though we did not specify for the thumbnail to be embedded.

Relevant code here: https://github.com/yt-dlp/yt-dlp/blob/182b6ae8a6b12ad49f2fa880f8db436f9a79a8ba/yt_dlp/YoutubeDL.py#L2598-L2603

Added in https://github.com/yt-dlp/yt-dlp/commit/4d971a16b831a45147b6ae7ce53b3e105d204da7

**Comment by sschmitz** [comment]
This is a bit of a disappointing fix since it removes useful functionality, even if yt-dlp was overzealous in its application. When you _do_ specify `--embed-thumbnail` on the above video (or e. g. the much smaller https://www.youtube.com/watch?v=EngW7tLk6R8), yt-dlp now (again?) throws an `ERROR: Postprocessing: Supported filetypes for thumbnail embedding are: mp3, mkv/mka, ogg/opus/flac, m4a/mp4/mov`.

I dug through the code just enough to see that a proper fix may not be as straightforward. As an end-user, though, it's weird to have yt-dlp refuse to do what it is told and then label it an error, even though the circumstances are hardly exceptional and it is obvious how to deal with them.

I wonder if there is an option that takes care of this case? `--remux-video 'webm>mkv'` seems to work, but I know far too little about container formats to really know what I'm doing ...

**Comment by pukkandan** [comment]
> This is a bit of a disappointing fix since it removes useful functionality, even if yt-dlp was overzealous in its application. 

Yes, I am aware of it, but not entirely sure how to go about fixing the same

> I wonder if there is an option that takes care of this case? --remux-video 'webm>mkv' seems to work, but I know far too little about container formats to really know what I'm doing ...

Yes, that will work perfectly as a workaround. webm is a subset of mkv and can always be safely remuxed to it
