### ISSUE TITLE
South Park, Season 9, Episode 4 "Best Friends Forever" will not download from Comedy Central

### ISSUE THREAD

**Issue by rgiuffre** [yt-dlp/yt-dlp#5007]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.09.01** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United States/Los Angeles, CA

### Provide a description that is worded well enough to be understood

https://southpark.cc.com/episodes/5gkuf7/south-park-best-friends-forever-season-9-ep-4

Similar issue as #2621, but all of the other videos can be downloaded (In chapters, of course) by me without problems.
I did not have the same issue as #2621. Those videos downloaded fine for me, so I'm sorry that I opened a new issue.

And yes, I am using the latest patched yt-dlp of 2022.09.23.43044 and not 2022-09-01. I thought it would help.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--all-subs', '--convert-subs', 'srt', '-f', 'best[width=1280]/best[height=720]/best', '--verbose', '-a', 'Links.txt', '-o', 'S%(season_number)02dE%(episode_number)02d-%(title)s.%(ext)s']
[debug] Batch file urls: ['https://southpark.cc.com/episodes/5gkuf7/south-park-best-friends-forever-season-9-ep-4']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] ytdl-patched/yt-dlp version 2022.09.23.43044 [9e28f9a] (win32_dir)
[debug] ** This build is unofficial daily builds, provided for ease of use.
[debug] ** Please do not ask for any support.
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 2022-09-22-git-af919cf780-full_build-www.gyan.dev (setts), ffprobe 2022-09-22-git-af919cf780-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.09.14, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1672 extractors
[debug] Fetching release info: https://api.github.com/repos/ytdl-patched/yt-dlp/releases/latest
Latest version: 2022.09.23.43044, Current version: 2022.09.23.43044
yt-dlp is up to date (2022.09.23.43044)
[debug] [southpark.cc.com] Extracting URL: https://southpark.cc.com/episodes/5gkuf7/south-park-best-friends-forever-season-9-ep-4
[southpark.cc.com] south-park-best-friends-forever-season-9-ep-4: Downloading webpage
[southpark.cc.com] 5ffda56c-ecfd-11e0-aca6-0026b9414f30: Downloading info
[download] Downloading playlist: Best Friends Forever
[southpark.cc.com] Playlist Best Friends Forever: Downloading 0 videos of 0
[download] Finished downloading playlist: Best Friends Forever
```

**Comment by gamer191** [comment]
Note for maintainers: `geo-blocked`
Also, created using Lesmiscore's yt-dlp daily builds

**Comment by pukkandan** [comment]
> I did not have the same issue as #2621. Those videos downloaded fine for me, so I'm sorry that I opened a new issue.

It looks like the exact same issue though
