### ISSUE TITLE
Question: i need help in identifiying problem in direct media links at some videos which can be downloaded with yt-dlp

### ISSUE THREAD

**Issue by TCH68k** [yt-dlp/yt-dlp#5011]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.09.01** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I'm actually looking for some help, to identify a problem within my software, not `yt-dlp`, that works fine.
This video: https://youtube.com/watch?v=hD4KMp22jBg can be perfectly downloaded via `yt-dlp`. However if i try to get the direct links with my software, the resulting links will give 403 from every software (VLC, MPV, wget, etc.)
What i know, it's not the `n` signature, because it's not throttled, but blocked. If i pass referer and origin in the HTTP headers with MPV
```
--user-agent="Mozilla/5.0 (Windows NT 10.0; rv:95.0) Gecko/20100101 Firefox/68.0" --http-header-fields="Referer: https://youtube.com/watch?v=hD4KMp22jBg, Origin: https://youtube.com"
```
, then it still does not work. `--cookies --cookies-file=/path/to/whatever.txt` also does not work.

Also, it's only appearing on some videos, not all videos; some of the extracted links works without problem, but some of them give 403.

Can anybody give a hint what could be wrong with this extracted direct link? (IP is changed.)
```
https://rr3---sn-qpbpu8-c0qr.googlevideo.com/videoplayback?expire=1663988508&ei=vB4uY9qlD_zjx_APgYCz8Ao&ip=0.0.0.0&id=o-AG60d-zFIhhlEKexFujMwWndWO7AD09eSVZRUgLoVt2s&itag=247&aitags=133%2C134%2C135%2C136%2C160%2C242%2C243%2C244%2C247%2C278%2C394%2C395%2C396%2C397%2C398&source=youtube&requiressl=yes&mh=__&mm=31%2C29&mn=sn-qpbpu8-c0qr%2Csn-c0q7lns7&ms=au%2Crdu&mv=m&mvi=3&pl=24&initcwndbps=1578750&vprv=1&mime=video%2Fwebm&ns=RT7A8nFEyXTBwWsN3HGfbfUI&gir=yes&clen=27242369&dur=472.405&lmt=1557034892954880&mt=1663966401&fvip=3&keepalive=yes&fexp=24001373%2C24007246&c=WEB&txp=5535432&n=C0QsYUPrvvvOWw&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgA2672iCsY7zFbgUjuIuDtMYrWCESQEP6-oWokHq1ypQCIHqIvOjpEheyVA5Sm3FqLMsE2yM7__LQ80YicZut7Nu6&sig=8OqhOq0QJ8wRgIuAO-H-F48zcDdMnuq82IcuCihrUCJK-3cDpSBzogjZqQrAAEAxhUsLK5NcpZdiCu3SeVO1zrRZ8f-zvKBkY9y0NkWf80=
```

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://youtube.com/watch?v=hD4KMp22jBg']
DeprecationWarning: Support for Python version 3.6 has been deprecated. See  https://github.com/yt-dlp/yt-dlp/issues/3764  for more details.
                    You will no longer receive updates on this version! Please update to Python 3.7 or above
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out UTF-8, error UTF-8, screen UTF-8
[debug] yt-dlp version 2022.07.18 [135f05e] (zip)
[debug] Python 3.6.3 (CPython 64bit) - Linux-4.9.0-19-amd64-x86_64-with-debian-9 (glibc 2.9)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.2.2, ffprobe 4.2.2, rtmpdump 2.4
[debug] Optional libraries: sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.09.01, Current version: 2022.07.18
[debug] Downloading _update_spec from https://github.com/yt-dlp/yt-dlp/releases/download/2022.09.01/_update_spec
WARNING: yt-dlp cannot be updated any further since you are on an older Python version
[debug] [youtube] Extracting URL: https://youtube.com/watch?v=hD4KMp22jBg
[youtube] hD4KMp22jBg: Downloading webpage
[youtube] hD4KMp22jBg: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] hD4KMp22jBg: Downloading 1 format(s): 247+251
[debug] Invoking http downloader on "https://rr3---sn-qpbpu8-c0qr.googlevideo.com/videoplayback?expire=1663989733&ei=hSMuY6PfGNeh-gar_6_ACg&ip=188.143.111.29&id=o-ADTZnZR8P-So7FSHnmK2ZY4fh81KmaqyGh0ZY4y6CLBH&itag=247&source=youtube&requiressl=yes&mh=__&mm=31%2C29&mn=sn-qpbpu8-c0qr%2Csn-c0q7lns7&ms=au%2Crdu&mv=m&mvi=3&pl=24&initcwndbps=1692500&vprv=1&mime=video%2Fwebm&gir=yes&clen=27242369&dur=472.405&lmt=1557034892954880&mt=1663967613&fvip=3&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=5535432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRAIgXYD-jT9oUxfhAOHnEXGw_--6Yan26xowGJCeOlOhP8kCIFVcUp8SdvDf2tM-WrgKSSstOr0bA9Yq3ui6MyFUjyTj&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIfPU9nPVXQs2_Ary_pI4bIaI4yL-3ZKqqG6hg1SrCYJwIhAIjqtFj5ie3TaeXBggg8QOhzab42QzHED7cPCk0D-kLQ"
[download] Destination: Jean Michel Jarre - Oxygen II [hD4KMp22jBg].f247.webm
[download] 100% of 25.98MiB in 00:02
[debug] Invoking http downloader on "https://rr3---sn-qpbpu8-c0qr.googlevideo.com/videoplayback?expire=1663989733&ei=hSMuY6PfGNeh-gar_6_ACg&ip=188.143.111.29&id=o-ADTZnZR8P-So7FSHnmK2ZY4fh81KmaqyGh0ZY4y6CLBH&itag=251&source=youtube&requiressl=yes&mh=__&mm=31%2C29&mn=sn-qpbpu8-c0qr%2Csn-c0q7lns7&ms=au%2Crdu&mv=m&mvi=3&pl=24&initcwndbps=1692500&vprv=1&mime=audio%2Fwebm&gir=yes&clen=8480102&dur=472.481&lmt=1532816459038867&mt=1663967613&fvip=3&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRAIgCagIEV8BDOGRzYrRBMI7LjihK-WuinaHGUuBIwOCESkCIHWCaKLwETIaRPDRKW-UC3mbQV7lfxePaieerMr8wz4v&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIfPU9nPVXQs2_Ary_pI4bIaI4yL-3ZKqqG6hg1SrCYJwIhAIjqtFj5ie3TaeXBggg8QOhzab42QzHED7cPCk0D-kLQ"
[download] Destination: Jean Michel Jarre - Oxygen II [hD4KMp22jBg].f251.webm
[download] 100% of 8.09MiB in 00:00
[Merger] Merging formats into "Jean Michel Jarre - Oxygen II [hD4KMp22jBg].webm"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:Jean Michel Jarre - Oxygen II [hD4KMp22jBg].f247.webm' -i 'file:Jean Michel Jarre - Oxygen II [hD4KMp22jBg].f251.webm' -c copy -map 0:v:0 -map 1:a:0 -movflags +faststart 'file:Jean Michel Jarre - Oxygen II [hD4KMp22jBg].temp.webm'
Deleting original file Jean Michel Jarre - Oxygen II [hD4KMp22jBg].f247.webm (pass -k to keep)
Deleting original file Jean Michel Jarre - Oxygen II [hD4KMp22jBg].f251.webm (pass -k to keep)
```

**Comment by pukkandan** [comment]
The URL given in your log does not match the example URL given above. So I'll have to ignore the log. With just the URL, my guesses are:
1. The extraction was performed logged in and the relevent cookies are not being passed to mpv
2. nsig failure can cause 403 too. Considering your yt-dlp is old, this could happen
3. You tried after the URL was already expired? YouTube's direct URLs have a life of 6hrs from generation


Provide log of that same video so I can rule out 1/2 and maybe get some more insight

**Comment by TCH68k** [comment]
The link is not made by `yt-dlp`. I said, i am looking for some help debugging my program. `yt-dlp` works fine and the links it give are fine too.

1. So, now cookies are needed? But then why only some links throws 403? My program does not pass any cookies to `mpv` or `wget` and yet, some of the links are working.
2. You misunderstood. I said `yt-dlp` works. My program does not works. The links it extracts are giving back 403. The ones `yt-dlp` give are working.
3. No, i tried it immediately.

**Comment by pukkandan** [comment]
I thought you meant that the link generated through yt-dlp doesnt work when downloaded through your program. If your program is generating the link itself, we cant help you much without knowing exactly how you are generating the link

> So, now cookies are needed?

In general, no. But idk if the video u r trying is age-restricted/private. Is it the same video from the log?

> You misunderstood. I said `yt-dlp` works. My program does not works. The links it extracts are giving back 403. The ones `yt-dlp` give are working.

My point still stands. Failure to decrypt nsig can sometimes cause a 403. The video may also have a `signatureSipher` which needs to be decrypted and added to the URL

I suggest you go through this code to see all the steps involved in getting a playable URL https://github.com/yt-dlp/yt-dlp/blob/f55523cfdd18dcd578f5d96cbb06266663169d35/yt_dlp/extractor/youtube.py#L3448-L3488

**Comment by TCH68k** [comment]
> But idk if the video u r trying is age-restricted/private.

No, it's public and not age-restricted.

> Is it the same video from the log?

Yes, it is the same.

> My point still stands. Failure to decrypt nsig can sometimes cause a 403. The video may also have a signatureSipher which needs to be decrypted and added to the URL

I know. My program deciphers them both. Only some of the videos are not working, that is what is not understandable for me. If none of them would work, then it would mean, that either of the ciphers are deciphered erroneously in my program.

> I suggest you go through this code to see all the steps involved in getting a playable URL

Thanks. I'm gonna dig myself into it.

**Comment by TCH68k** [comment]
The problem is the `signatureCipher`; google has rewritten the cipher and ruined my decoder. The new decipher is much more complex and it seems to rely browser-only components like `window` or `document`.

Is there any easy way to decipher `signatureCipher` with `nodejs` for instance?

**Comment by pukkandan** [comment]
yt-dlp's signature decryption is still working though, correct? Then you shouldn't need DOM

**Comment by pukkandan** [comment]
Could you show output of 
```
yt-dlp --extractor-args youtube:player-client=web -g -f 247 hD4KMp22jBg -v
```
so that I can confirm you arent getting some new player that youtube is A/B testing

**Comment by TCH68k** [comment]
Here it is:
```
[debug] Command-line config: ['--extractor-args', 'youtube:player-client=web', '-g', '-f', '247', 'hD4KMp22jBg', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out UTF-8, error UTF-8, screen UTF-8
[debug] yt-dlp version 2022.09.01 [5d7c7d6] (zip)
[debug] Python 3.7.9 (CPython 64bit) - Linux-4.9.0-19-amd64-x86_64-with-debian-9 (glibc 2.17)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.2.2, ffprobe 4.2.2, rtmpdump 2.4
[debug] Optional libraries: sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Loaded 1670 extractors
[debug] [youtube] Extracting URL: hD4KMp22jBg
[youtube] hD4KMp22jBg: Downloading webpage
[debug] [youtube] Extracting signature function js_abfb84fe_103
[youtube] hD4KMp22jBg: Downloading player abfb84fe
[debug] Saving youtube-sigfuncs.js_abfb84fe_103 to cache
[debug] Saving youtube-nsig.abfb84fe to cache
[debug] [youtube] Decrypted nsig 3tibsCfqiiH1IXPPR => MSPiHxa69_9Scw
[debug] [youtube] Extracting signature function js_abfb84fe_107
[debug] Saving youtube-sigfuncs.js_abfb84fe_107 to cache
[debug] Loading youtube-nsig.abfb84fe from cache
[debug] [youtube] Decrypted nsig bg01iJUvWqjcTcG6i => E-MYUY8y8ZaX2w
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[info] hD4KMp22jBg: Downloading 1 format(s): 247
https://rr3---sn-qpbpu8-c0qr.googlevideo.com/videoplayback?expire=1664046460&ei=HAEvY-j3CYSRgAfd-pSABQ&ip=188.143.111.100&id=o-ADg0RnA9uHcSVX7AeCmCnuNi84huWqXD0sZzShesJy7H&itag=247&aitags=133%2C134%2C135%2C136%2C160%2C242%2C243%2C244%2C247%2C278%2C394%2C395%2C396%2C397%2C398&source=youtube&requiressl=yes&mh=__&mm=31%2C29&mn=sn-qpbpu8-c0qr%2Csn-c0q7lns7&ms=au%2Crdu&mv=m&mvi=3&pl=24&initcwndbps=1310000&vprv=1&mime=video%2Fwebm&ns=Gyl71zu0P2EMreRlS-YRRXsI&gir=yes&clen=27242369&dur=472.405&lmt=1557034892954880&mt=1664024468&fvip=3&keepalive=yes&fexp=24001373%2C24007246&c=WEB&txp=5535432&n=E-MYUY8y8ZaX2w&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgLDp80JIwn6oVGbHreyuy-ghW4eWcy-tuY4M-_w1YeGUCIQCnGdBcSjVySWYTtRUvz2gk2cU7RpnfiOPJ8x_jeV6q-A%3D%3D&sig=AOq0QJ8wRQIhALhklV1i3Eej7ALThxjsqGSVSPV5rpSFgt8mw8Mv5nSKAiAS8Zs69fFecISw0xEJR9rN74BwUPzq62HqnkYMht0XNw%3D%3D
```
(I've updated Python to 3.7 and `yt-dlp` to the latest in the meantime.)

**Comment by TCH68k** [comment]
This is the player i get from youtube: http://oscomp.hu/depot/ytplayer-20220924.js

Until this point, the deciphering was simple, i located the function, splitted it to subfunctions and emulated the operations. Now this is much more complex. The deciphering is done in function `BB()` at line #2304.

**Comment by pukkandan** [comment]
Everything looks fine. DOM is defenitely not needed - yt-dlp is also just extracting the function code and emulating js functions. You might want to double check your code

> This is what i would like to with the signatureCipher -> sig stuff too, but i have no idea how could i extract all the necessary parts from this player.

https://github.com/yt-dlp/yt-dlp/blob/f55523cfdd18dcd578f5d96cbb06266663169d35/yt_dlp/extractor/youtube.py#L2755-L2777

**Comment by TCH68k** [comment]
My "emulation" was rather vestigal (implemented only the used functions) and the parts the code extractor was looking for are vastly changed, thus my decipher is rendered broken already.

How `yt-dlp` extracts the needed functon code? What is `jscode` containing in this function?
I know that the function needed to be called is `BB`, but i cannot even call that, it has tons of other dependencies scattered across the entire player. Can you please pinpoint what function does the exact deciphering of the `sig` string? `BB` takes an object, containing `signatureCipher`.

**Comment by pukkandan** [comment]
`jsi.extract_function` extracts the function body and any dependencies are resolved during the js emulation (when an unknown variable name is encountered, it is searched for in the whole player)

Since your objective is to use nodejs, you really only need to find the function name and call it. Node should automatically run the dependencies as needed. The regexes posted above is how yt-dlp extracts the name

**Comment by TCH68k** [comment]
If i try to load the whole player into `nodejs`, then it dies with the error:
```
/tmp/yttest-20220924.js:6911
kk.prototype.u=function(a){return Cga(this,a,!0)};var mra={OSa:0,LSa:1,ISa:2,JSa:3,KSa:4,NSa:5,MSa:6};var fm;fm=["av.default","js","unreleased"].slice(-1)[0];var bl=new function(a,b){this.key=a;this.defaultValue=void 0===b?!1:b;this.valueType="boolean"}("45378663");var Vl=document,Ik=window;var Iga={NONE:0,ipa:1},nha={GU:0,KRa:1,JRa:2,LRa:3},cl={tU:"a",Loa:"d",VIDEO:"v"};uk.prototype.isVisible=function(){return this.Ts?.3<=this.Jd:.5<=this.Jd};var Ek={Pia:0,qta:1},lha={NONE:0,dya:1,Ava:2};vk.prototype.getValue=function(){return this.wd};
                                                                                                                                                                                                                                                                                 ^

ReferenceError: document is not defined
    at /tmp/yttest-20220924.js:6911:274
    at Object.<anonymous> (/tmp/yttest-20220924.js:11148:235)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:140:18)
    at node.js:1043:3
```

**Comment by TCH68k** [comment]
By adding
```
var document = {};
var window = {location: {hostname: ""}};
var XMLHttpRequest = {prototype: {fetch: ""}};
var navigator = {};
```
into `_yt_player` it finally loads, but the needed function is not available...
http://oscomp.hu/depot/yttest-20220924.js
```

**Comment by pukkandan** [comment]
wdym "not available"? https://regex101.com/r/Myvsyj/1

**Comment by TCH68k** [comment]
I meant, that it is not available in the object `_yt_player`.

But now, that you pinpointed where and how to look, i think i can now adapt my code.
Thank you for your help, i really appreciate it.

**Comment by TCH68k** [comment]
Also, by putting the signature into the extracted JS code and replace the one in the URL with the gotten result made the link work again.
This question is answered masterfully, it can be closed.
And thank you again.

**Comment by TCH68k** [comment]
Footnote: One of my users reported that before the fix, the breakage only affected "music videos". So, YT applies the signature cipher differently to music videos.
