### ISSUE TITLE
Uncommon Info

### ISSUE THREAD

**Issue by Jadoo4QFan** [yt-dlp/yt-dlp#5013]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.09.01** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Earlier when I talked about TikTok, and later found stuff in Zoom and Loom’s HTML code, I realized there are settings to non-general to add to the Info Json, like specific privacy settings, wheaten a feature is enabled, or WhatsApp share count for example. Can we make a new info field for that that holds the obscure info and info about them. 

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
N/A
```

**Comment by Jadoo4QFan** [comment]
Sorry for being hard to read like bad English

**Comment by pukkandan** [comment]
No. All metadata must conform to a specific schema. We will not allow arbitrary metadata. If you want them, plugins are the way to go
