### ISSUE TITLE
Can't download from Crunchyroll

### ISSUE THREAD

**Issue by SamusAranX** [yt-dlp/yt-dlp#5023]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.09.01** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

US

### Provide a description that is worded well enough to be understood

There's really not much beyond the verbose output below that I can say about this. I can watch episodes in my browser no problem, but using yt-dlp yields this "This video is for premium members only." message.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--cookies', '../crunchyroll.com_cookies.txt', '--write-subs', '--embed-subs', 'https://beta.crunchyroll.com/watch/G9DUEP2JW/pressure']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.09.01 [5d7c7d6] (pip)
[debug] Python 3.10.6 (CPython 64bit) - macOS-12.6-arm64-arm-64bit
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 5.1.1 (setts), ffprobe 5.1.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.13.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.1
[debug] Proxy map: {}
[debug] Loaded 1670 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.09.01, Current version: 2022.09.01
yt-dlp is up to date (2022.09.01)
[debug] [crunchyroll:beta] Extracting URL: https://beta.crunchyroll.com/watch/G9DUEP2JW/pressure
[crunchyroll:beta] Retrieving main page
[crunchyroll:beta] Authenticating with grant_type=client_id
[crunchyroll:beta] Retrieving signed policy
[crunchyroll:beta] pressure: Retrieving episode metadata
ERROR: [crunchyroll:beta] G9DUEP2JW: This video is for premium members only.
  File "/opt/homebrew/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 670, in extract
    ie_result = self._real_extract(url)
  File "/opt/homebrew/lib/python3.10/site-packages/yt_dlp/extractor/crunchyroll.py", line 799, in _real_extract
    raise ExtractorError('This video is for premium members only.', expected=True)
```

**Comment by metita** [comment]
Switch to username and password authentication and it will work but yeah, using cookies is not working for some reason, can confirm.

**Comment by pukkandan** [comment]
Your cookies does not seem to contain authentication data. Try with `--cookies-from-browser`

**Comment by metita** [comment]
@pukkandan I can confirm using --cookies-from-browser method works and... that the --cookies method was working before but seems a good workaround, I was forced to download chrome to use the parameter because I am a Opera GX user and only normal Opera is supported, if there is a chance to allow Opera GX too that would be cool.

**Comment by Grub4K** [comment]
`--cookies-from-browser "opera:path/to/gx/profile"` should for Opera GX, though it would be interesting to know why the `cookies.txt` did not work. Did it contain a cookie entry named `etp_rt`?

**Comment by metita** [comment]
Yes for me, there is a etp_rt with a unique ID i guess? As I said this was working yesterday

**Comment by Grub4K** [comment]
That seems strange as it specifically tries to use `grant_type=client_id` not `grant_type=etp_rt_cookie`. Is the unique id the same as the one your browser uses? Try extracting the cookies again and comparing those files.

As for using `--cookies-from-browser`, you will have to replace the dummy path I provided with the actual path to the Opera GX Profile directory.

**Comment by metita** [comment]
--cookies-from-browser is working now (didn't notice that you need to change the path, my bad) but looks like videos are requiring premium access still, seems weird?

`2022-09-25 04:36:00,826-DEBUG-Worker_1-[debug] Extracting cookies from: "C:\Users\Administrator\AppData\Roaming\Opera Software\Opera GX Stable\Network\Cookies"
2022-09-25 04:36:00,827-DEBUG-Worker_1-[debug] Found local state file at "C:\Users\Administrator\AppData\Roaming\Opera Software\Opera GX Stable\Local State"
2022-09-25 04:36:00,827-DEBUG-Worker_1-[debug] cookie version breakdown: {'v10': 1093, 'other': 0, 'unencrypted': 0}
2022-09-25 04:36:00,827-DEBUG-Worker_1-[debug] Proxy map: {}
2022-09-25 04:36:00,827-DEBUG-Worker_1-[debug] Loaded 1670 extractors
2022-09-25 04:36:00,827-DEBUG-Worker_1-[debug] [crunchyroll:beta] Extracting URL: https://beta.crunchyroll.com/es/watch/GYJQKNP46/springtime
2022-09-25 04:36:00,828-DEBUG-Worker_1-ERROR: [crunchyroll:beta] GYJQKNP46: This video is for premium members only.
2022-09-25 04:36:00,828-DEBUG-Worker_1-  File "yt_dlp\extractor\common.py", line 670, in extract
2022-09-25 04:36:00,828-DEBUG-Worker_1-  File "yt_dlp\extractor\crunchyroll.py", line 799, in _real_extract
2022-09-25 04:36:00,828-DEBUG-Worker_1-Child process exited with non-zero code: 1`

**Comment by pukkandan** [comment]
> EDIT: Looks like replacing https to http and removing the language prefix is doing the work, pretty weird tho.

It works from chrome even without this, correct?

Can you copy the `etp_rt` cookie from the file and post it here? **Redact the actual cookie value** - I just want to see the other fields

**Comment by SamusAranX** [comment]
Using username/password works flawlessly, I didn't even know that was an option 😅
Cheers!

**Comment by metita** [comment]
> # Netscape HTTP Cookie File
# http://curl.haxx.se/rfc/cookie_spec.html
# This is a generated file!  Do not edit.

www.crunchyroll.com	FALSE	/anime-news/2022/09/24-1	FALSE	1695543346	initial_referrer	https%3A%2F%2Ft.co%2FzeqrwxFasF
www.crunchyroll.com	FALSE	/es/videos	FALSE	1695337648	initial_referrer	
beta.crunchyroll.com	FALSE	/es	FALSE	1697934590	_evidon_consent_cookie	{"consent_date":"2022-09-22T00:29:50.907Z","consent_type":1}
beta.crunchyroll.com	FALSE	/es	FALSE	1697934590	_evidon_gdpr_consent_cookie	1
.crunchyroll.com	TRUE	/	FALSE	1679353647	c_visitor	aec33fcf-103b-48ee-8586-74bd86e68cc2
.crunchyroll.com	TRUE	/	TRUE	0	__cfruid	6e8ad1e695066fa56123579b5140d7cbe47620ef-1663801985
.crunchyroll.com	TRUE	/	FALSE	1665300899	etp_rt	xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
.crunchyroll.com	TRUE	/	FALSE	1698651299	c_locale	en-US
beta.crunchyroll.com	FALSE	/	FALSE	1695360891	_evidon_suppress_notification_cookie	{"date":"2022-09-22T05:34:51.894Z"}
.crunchyroll.com	TRUE	/	FALSE	1671698484	_gcl_au	1.1.176933923.1663922485
.crunchyroll.com	TRUE	/	FALSE	1671867303	_fbp	fb.1.1663922485507.1606296701
.crunchyroll.com	TRUE	/	FALSE	1697787302	_tt_enable_cookie	1
.crunchyroll.com	TRUE	/	FALSE	1697787302	_ttp	2d46ae7b-6e3a-46d2-b4cb-e6d8ebc1a2cf
.crunchyroll.com	TRUE	/	FALSE	1695627303	ajs_user_id	%22e9320266-8262-568a-ac95-9fd129d0e6d1%22
.crunchyroll.com	TRUE	/	FALSE	1695627303	ajs_anonymous_id	%22b535ae70-4656-4e3a-aae9-24b0c466b319%22
.crunchyroll.com	TRUE	/	FALSE	1666599344	c_market_ref	community_cr_twitter_news
.crunchyroll.com	TRUE	/	FALSE	1664093746	_gid	GA1.2.590358297.1664007203
.crunchyroll.com	TRUE	/	FALSE	1698651301	_ga	GA1.1.70539188.1663922485
.crunchyroll.com	TRUE	/	TRUE	0	session_id	163d496820c904ffd7e937b23565b2d9
.crunchyroll.com	TRUE	/	FALSE	1664091599	etp_jwt	eyJhbGciOiJSUzI1NiIsImtpZCI6IjZrN0NmZWNTT3VBSU9BaHR6OTZyZmciLCJ0eXAiOiJKV1QifQ.eyJhbm9ueW1vdXNfaWQiOiJiNTM1YWU3MC00NjU2LTRlM2EtYWFlOS0yNGIwYzQ2NmIzMTkiLCJiZW5lZml0cyI6WyJjYXRhbG9nIiwiY29uY3VycmVudF9zdHJlYW1zLjEiLCJjcl9wcmVtaXVtIiwibWFuZ2FfbGlicmFyeSIsIm5vX2FkcyIsInNpbXVsY2FzdCJdLCJjbGllbnRfaWQiOiJjcl9iYWNrZW5kIiwiY2xpZW50X3RhZyI6IjEuMS4xIGxlZ2FjeSIsImNvdW50cnkiOiJDTCIsImV0cF91c2VyX2lkIjoiZTkzMjAyNjYtODI2Mi01NjhhLWFjOTUtOWZkMTI5ZDBlNmQxIiwiZXhwIjoxNjY0MDkxNTk5LCJqdGkiOiIxNTdlYmQ1NC04NWQzLTQ2NDEtYmY1OC1mMTc2NTQwZTY3NTAiLCJtYXR1cml0eSI6Ik0zIiwib2F1dGhfc2NvcGVzIjoiYWNjb3VudCBjb250ZW50IG9mZmxpbmVfYWNjZXNzIHJldmlld3MgdGFsa2JveCIsInJ0X2lkIjoiY2NscGwyM2oyNjJ0czgwZWN0OWciLCJzY29wZXMiOnsiY3IiOnsiYWNjX2lkIjoiZTkzMjAyNjYtODI2Mi01NjhhLWFjOTUtOWZkMTI5ZDBlNmQxIiwiZXh0X2lkIjoiMTA2Mjg0MzM0MiJ9fSwic3RhdHVzIjoiQUNUSVZFIiwidG50IjoiY3IifQ.cJNem6PYkGcWL8czn_ZcUHwxAjFa-ljRN_GqsYNVDnC2cSLYU57zaqRFnVvGAV6xfVeQV0uo1nRMIGPBOaTq5BL09cJUlizYJRTqnNaX2tPM_UzMOUSZuBmG__y4_gGKzkwYdnOwtFaqFj9Jly3U0MVsSm0pq26Fn75SH3UzpcfvFAtz25BtRJD-3iyuAoysz7Z3ZDGg_dIi9j1G-tXsRptwlwqp_iZ7-pOqawgHUFj_ZyMMLZ07y-Sqfmlu5ZlvAkXyhcx92APzigkD8Js1nLcwgiMb7dbdGD_5GLD0A_7fNl36YnPcI2iTaFxfS7V7N1GpO1QMdcGX6QlejAzQOA
.crunchyroll.com	TRUE	/	TRUE	1664093099	__cf_bm	XgcoBxdvIn81JjZP59kLIWUSBePC4yrPJoRSZcXh9QE-1664091300-0-ARK1ocqqaFP2i42l8SmNjoUULumb681JCRc1/YcKmxtnDt45oMJGyaU6f7t87rq24JGrkuov4kA17a6tgL+jwJ+zU9+z5h33RHfHw605+WAx
.crunchyroll.com	TRUE	/	FALSE	1698651301	_ga_SYYQC1VW88	GS1.1.1664091301.10.0.1664091301.0.0.0
.crunchyroll.com	TRUE	/	FALSE	1698651304	ab.storage.sessionId.80f403d2-1c18-471d-b0ef-243d1d646436	%7B%22g%22%3A%220a5d04d9-db85-f48a-da1d-1a17293c7e51%22%2C%22e%22%3A1664093104137%2C%22c%22%3A1664091304138%2C%22l%22%3A1664091304138%7D
.crunchyroll.com	TRUE	/	FALSE	1698651304	ab.storage.deviceId.80f403d2-1c18-471d-b0ef-243d1d646436	%7B%22g%22%3A%22e2d19182-3cf6-3547-32fd-5bd9d6a211b1%22%2C%22c%22%3A1663802013784%2C%22l%22%3A1664091304139%7D
.crunchyroll.com	TRUE	/	FALSE	1698651304	ab.storage.userId.80f403d2-1c18-471d-b0ef-243d1d646436	%7B%22g%22%3A%22e9320266-8262-568a-ac95-9fd129d0e6d1%22%2C%22c%22%3A1663802013774%2C%22l%22%3A1664091304139%7D

@SamusAranX yep that works, problem is that recurrent login will flag your IP and won't be able to download for like 5 minutes

**Comment by pukkandan** [comment]
It looks fine to me 🤔

**Comment by metita** [comment]
Did way more testing...

https://beta.crunchyroll.com/es/watch/GYJQKNP46/springtime (cannot download, requires premium account)
https://beta.crunchyroll.com/watch/GYJQKNP46/springtime (will download properly)

Note that this is NOT happening with every episode.

**Comment by SamusAranX** [comment]
I just tried `--cookies-from-browser`, but that has the same effect as using `--cookies`. The only thing that works at all for me is the username/password combination.

**Comment by Grub4K** [comment]
> On initial glance, it looks fine to me 🤔

This might be related to #4776 since I see `_evidon_consent_cookie`, which I remember containing quotes. That would also explain why it does not work only if the language is provided, since the path for the cookie is explicitly `/es`.

@metita @SamusAranX Do one of the cookies contain `"`? Try running yt-dlp from latest GitHub source (or maybe use [ytdl-patched/yt-dlp](https://github.com/ytdl-patched/yt-dlp/releases)) and see if the problem persists. #4780 is not yet in the latest manual release.

**Comment by pukkandan** [comment]
You are right, I totally forgot about that issue. One of the cookies do contain quotes

**Comment by metita** [comment]
Can confirm that using the yt-patched build links are working again
