### ISSUE TITLE
Twitter DM (video.twimg.com) tag and container "is not recognized as an internal or external command"

### ISSUE THREAD

**Issue by AdamSaketume26** [yt-dlp/yt-dlp#5026]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.09.01** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Provide a description that is worded well enough to be understood

1. Get m3u8 of twitter dm video
2. open cmd
3. run yt-dlp m3u8link
4.  after download complete it gives the error

> 'tag' is not recognized as an internal or external command,
> operable program or batch file.
> 'container' is not recognized as an internal or external command,
> operable program or batch file.

it downloads the video but gives this error i dont know why. I am not including the dm video link.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
F:\>yt-dlp -vU https://video.twimg.com/dm_video/hide/pl/hide.m3u8?variant_version=1&tag=1&container=fmp4
[debug] Command-line config: ['-vU', 'https://video.twimg.com/dm_video/hide/pl/hide.m3u8?variant_version=1']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.09.01 [5d7c7d6] (win32_exe)
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-hide
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 5.1.1-essentials_build-www.gyan.dev (setts), ffprobe 5.1.1-essentials_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1670 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.09.01, Current version: 2022.09.01
yt-dlp is up to date (2022.09.01)
[debug] [generic] Extracting URL: https://video.twimg.com/dm_video/hide/pl/hide.m3u8?variant_version=1
[generic] hide: Downloading webpage
[debug] Identified a direct video link
[generic] hide: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] hide: Downloading 1 format(s): 350
[debug] Invoking hlsnative downloader on "https://video.twimg.com/dm_video/hide/pl/720x720/hide.m3u8?container=fmp4"
[download] hide [hide].mp4 has already been downloaded
[download] 100% of 870.10KiB
'tag' is not recognized as an internal or external command,
operable program or batch file.
'container' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by coletdjnz** [comment]
you need to put quotes around your url, as `&` has a special meaning in your shell:

`yt-dlp -vU "https://video.twimg.com/dm_video/hide/pl/hide.m3u8?variant_version=1&tag=1&container=fmp4"

**Comment by pukkandan** [comment]
> I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
