### ISSUE TITLE
Is there any way to use aria2 only for downloads from certain sites?

### ISSUE THREAD

**Issue by raki-can** [yt-dlp/yt-dlp#5027]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.09.01** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I use yt-dlp for downloads from several sites, but niconico downloads are very slow and have taken over 24 hours to process a playlist with many videos in it.
I saw aria2 mentioned as a solution to that, but I have no complaints about download speeds from sites other than niconico and don't want to add unnecessary load.
Also, I have not been able to find an article that adequately explains (by Japanese) what I need to do to use aria2 with yt-dlp in the first place, and I am unable to determine the proper configuration for me.

I would like to enable aria2 only for downloads from niconico if possible, but if such a sorting is not possible what should I do to apply aria2 to all downloads?
(Perhaps this is a rather silly question, but I really couldn't find enough information about the proper settings)

By the way, my current conf file is as follows:
```
-U
-o "F:\Nico-down\%(upload_date)s - %(title)s.%(ext)s"
-f "bestvideo+bestaudio/best"
--embed-thumbnail
--default-search error
--cookies-from-browser chrome
--no-mark-watched
--no-mtime
--console-title
--download-archive "F:\VideoDownLog.log"
-a "F:\VideoDownList.txt"
```

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
No. Track https://github.com/yt-dlp/yt-dlp/issues/4949 and https://github.com/yt-dlp/yt-dlp/issues/4680
