### ISSUE TITLE
Odysee Description Missing lbry URL and Claim ID

### ISSUE THREAD

**Issue by turquoispandabear10** [yt-dlp/yt-dlp#5028]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a site-specific feature
- [X] I've verified that I'm running yt-dlp version **2022.09.01** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United States

### Example URLs

https://odysee.com/@veritasium:f/world's-highest-jumping-robot:8

### Provide a description that is worded well enough to be understood

Downloading the description works perfectly well but it is missing this part of the description:

URL
lbry://@veritasium#f/world's-highest-jumping-robot#8
Claim ID
8579dbcb43b02be07f4a83e76836e4f272424e8d
236.45 MB

The lbry link is distinct from the odysee one/site url, so it would be nice if this whole section could be included when running "--write-description", though I understand it could be a pain in some setups depending on how the files/metadata are being used/displayed.  Another possibility could be a new command like "--write-full/complete-description".

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
This is a  feature request, not a bug, and don't feel comfortable posting personal info.  Apologies.
```

**Comment by flashdagger** [comment]
According to the LBRY API the missing parts do not belong to the description but are separate properties:

`> yt-dlp "https://odysee.com/@veritasium:f/world's-highest-jumping-robot:8#f/world's-highest-jumping-robot#8" --print "URL: %(webpage_url)s" --print "Claim ID: %(id)s" --print "file size: %(filesize).2DiB"`

```
URL: https://odysee.com/@veritasium:f/world's-highest-jumping-robot:8#f/world's-highest-jumping-robot#8
Claim ID: 8579dbcb43b02be07f4a83e76836e4f272424e8d
file size: 247.93MiB
```
