### ISSUE TITLE
South Park locked episodes not working

### ISSUE THREAD

**Issue by Scrooge200FES** [yt-dlp/yt-dlp#5034]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.09.01** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United States

### Provide a description that is worded well enough to be understood

I used to be able to download any episode from southpark.cc, but the latest version isn't letting me. I tried downloading a locked episode (https://southpark.cc.com/episodes/t9jqji/south-park-the-poor-kid-season-15-ep-14), and I got an error that it couldn't find the MGID. Episodes that are freely playable online (like https://southpark.cc.com/episodes/me0b40/south-park-casa-bonita-season-7-ep-11) will download normally.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
C:\[...]>yt-dlp -vU https://southpark.cc.com/episodes/t9jqji/south-park-the-poor-kid-season-15-ep-14
[debug] Command-line config: ['-vU', 'https://southpark.cc.com/episodes/t9jqji/south-park-the-poor-kid-season-15-ep-14']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.09.01 [5d7c7d6] (win32_exe)
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 2022-05-12-git-30e2bb0f64-full_build-www.gyan.dev (setts), ffprobe 2022-05-12-git-30e2bb0f64-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1670 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.09.01, Current version: 2022.09.01
yt-dlp is up to date (2022.09.01)
[debug] [southpark.cc.com] Extracting URL: https://southpark.cc.com/episodes/t9jqji/south-park-the-poor-kid-season-15-ep-14
[southpark.cc.com] south-park-the-poor-kid-season-15-ep-14: Downloading webpage
ERROR: [southpark.cc.com] t9jqji/south-park-the-poor-kid-season-15-ep-14: Could not extract mgid; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 670, in extract
  File "yt_dlp\extractor\mtv.py", line 326, in _real_extract
  File "yt_dlp\extractor\mtv.py", line 319, in _extract_mgid
```

**Comment by october262** [comment]
for me, the website says THIS EPISODE IS CURRENTLY UNAVAILABLE
DUE TO CURRENT RIGHTS AND RESTRICTIONS, THIS VIDEO IS UNAVAILABLE, BUT FEEL FREE TO CHECK BACK LATER. IN THE MEANTIME, WHY NOT WATCH SOMETHING ELSE?

**Comment by Scrooge200FES** [comment]
Yeah, but I used to still be able to rip these episodes, even when they were unavailable.

**Comment by pukkandan** [comment]
If yt-dlp accidentally works on blocked content, great for you. But we cannot accept it as a bug/request
