### ISSUE TITLE
Blerp

### ISSUE THREAD

**Issue by Jadoo4QFan** [yt-dlp/yt-dlp#5035]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.09.01** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

California, USA

### Example URLs

https://blerp.com/soundbites/6320fe8745636cb4dd677a5a
https://blerp.com/soundbites/5bc94ef4796001000498429f
User: https://blerp.com/u/the_mariocrafter_csed5x
Search: https://blerp.com/search?q=Friday-Night-Funkin-&r=R
Category: https://blerp.com/categories/sound-effects

### Provide a description that is worded well enough to be understood

Please add support for extracting Blerp sounds and their metadata.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
dlp -U
[Documents]$ yt-dlp -vU https://blerp.com/sound
bites/5bc94ef4796001000498429f
[debug] Command-line config: ['-vU', 'https://b
lerp.com/soundbites/5bc94ef4796001000498429f']
[debug] Encodings: locale UTF-8, fs utf-8, pref
 UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.09.01 [5d7c7d6] (pi
p)
[debug] Python 3.9.10+ (CPython 64bit) - macOS-
16.0-iPhone14,5-arm-64bit 
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg n5.0.1-4-ga5ebb3d2
5e (setts), ffprobe n5.0.1-4-ga5ebb3d25e, phantomjs present, rtmpdump present
[debug] Optional libraries: Cryptodome-3.15.0, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1670 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.09.01, Current version: 2022.09.01
yt-dlp is up to date (2022.09.01)
[debug] [generic] Extracting URL: https://blerp.com/soundbites/5bc94ef4796001000498429f
[generic] 5bc94ef4796001000498429f: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] 5bc94ef4796001000498429f: Extracting information
[debug] Looking for Brightcove embeds
[debug] Looking for embeds
[debug] Identified a twitter:player iframe
[debug] [generic] Extracting URL: https://blerp.com/embed/5bc94ef4796001000498429f
[generic] 5bc94ef4796001000498429f: Downloading webpage
ERROR: [generic] Unable to download webpage: HTTP Error 500: Internal Server Error (caused by <HTTPError 500: 'Internal Server Error'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/var/mobile/Containers/Data/Application/C53C35F9-CF23-4488-A35D-C0112FE31C26/Library/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 670, in extract
    ie_result = self._real_extract(url)
  File "/var/mobile/Containers/Data/Application/C53C35F9-CF23-4488-A35D-C0112FE31C26/Library/lib/python3.9/site-packages/yt_dlp/extractor/generic.py", line 2641, in _real_extract
    full_response = self._request_webpage(url, video_id, headers={'Accept-Encoding': '*'})
  File "/var/mobile/Containers/Data/Application/C53C35F9-CF23-4488-A35D-C0112FE31C26/Library/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 821, in _request_webpage
    raise ExtractorError(errmsg, cause=err)

  File "/var/mobile/Containers/Data/Application/C53C35F9-CF23-4488-A35D-C0112FE31C26/Library/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 803, in _request_webpage
    return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query))
  File "/var/mobile/Containers/Data/Application/C53C35F9-CF23-4488-A35D-C0112FE31C26/Library/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 3656, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/private/var/containers/Bundle/Application/F6A7107F-3997-4B5E-BAF5-D05C11A148A5/a-Shell-mini.app/Library/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/private/var/containers/Bundle/Application/F6A7107F-3997-4B5E-BAF5-D05C11A148A5/a-Shell-mini.app/Library/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/private/var/containers/Bundle/Application/F6A7107F-3997-4B5E-BAF5-D05C11A148A5/a-Shell-mini.app/Library/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/private/var/containers/Bundle/Application/F6A7107F-3997-4B5E-BAF5-D05C11A148A5/a-Shell-mini.app/Library/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/private/var/containers/Bundle/Application/F6A7107F-3997-4B5E-BAF5-D05C11A148A5/a-Shell-mini.app/Library/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 500: Internal Server Error
[Documents]$ 
```

**Comment by HobbyistDev** [comment]
This site actually use json+ld too but the generic extract twitter:player (maybe because it listed first ?). Not tested yet, but i assume #4517 will work (with filtering the ie).
json ld:
```html
 <script type="application/ld+json">
      [{
        "@context": "http://schema.org",
        "@type": ["MediaObject", "AudioObject", "CreativeWork", "MusicRecording"],
        "url": "https://blerp.com/soundbites/5bc94ef4796001000498429f",
        "byArtist": {
          "@type": "MusicGroup",
          "name": "179617322678353920",
          "@id": "https://blerp.com/user/5ba99cf71386730004552c42"
        },
        "embedUrl": "https://blerp.com/embed/5bc94ef4796001000498429f",
        "encodingFormat": "audio/mpeg",
        "name": "Yee",
        "image": "https://cdn.blerp.com/thumbnails/4cd92b90-195b-11e9-944f-470c2f71db8e",
        "keywords": "YEE,YEET,wo ha haah catchy tune yee,yee",
        "contentUrl": "https://cdn.blerp.com/normalized/cd4e4a10-d34e-11e8-a867-4741c3fed662"
      }]
    </script>
```

**Comment by coletdjnz** [comment]
> This site actually use json+ld too but the generic extract twitter:player (maybe because it listed first ?). Not tested yet, but i assume #4517 will work (with filtering the ie). json ld:
> 
> ```
>  <script type="application/ld+json">
>       [{
>         "@context": "http://schema.org",
>         "@type": ["MediaObject", "AudioObject", "CreativeWork", "MusicRecording"],
>         "url": "https://blerp.com/soundbites/5bc94ef4796001000498429f",
>         "byArtist": {
>           "@type": "MusicGroup",
>           "name": "179617322678353920",
>           "@id": "https://blerp.com/user/5ba99cf71386730004552c42"
>         },
>         "embedUrl": "https://blerp.com/embed/5bc94ef4796001000498429f",
>         "encodingFormat": "audio/mpeg",
>         "name": "Yee",
>         "image": "https://cdn.blerp.com/thumbnails/4cd92b90-195b-11e9-944f-470c2f71db8e",
>         "keywords": "YEE,YEET,wo ha haah catchy tune yee,yee",
>         "contentUrl": "https://cdn.blerp.com/normalized/cd4e4a10-d34e-11e8-a867-4741c3fed662"
>       }]
>     </script>
> ```

Hm. This should be being picked up by generic, and preferred over the twitter:player. There might be an issue with the core JSON LD extraction.

**Comment by pukkandan** [comment]
oh! I misread the logs :/

**Comment by pukkandan** [comment]
I've fixed the json+ld extraction, so single videos now download. The playlist request still remains
