### ISSUE TITLE
[BiliBiliChannel] Inconsistency and failure to download whole channels videos

### ISSUE THREAD

**Issue by kruumy** [yt-dlp/yt-dlp#5038]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.09.01** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Does not get the information from all the channel pages. The BiliBili channel is https://space.bilibili.com/6444277/video.

It used to work, I used yt-dlp to dump the data from each page easily but now it does not. I would assume something has changed on BiliBili's side which has broken [BiliBiliChannel] yt-dlp.

Edit: The channel has 7308 videos, yet yt-dlp reports none.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://space.bilibili.com/6444277/video']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.09.01 [5d7c7d6] (win32_exe)
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.22000-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 2022-06-30-git-03b2ed9a50-full_build-www.gyan.dev (setts), ffprobe 2022-06-30-git-03b2ed9a50-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1670 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.09.01, Current version: 2022.09.01
yt-dlp is up to date (2022.09.01)
[debug] [BilibiliChannel] Extracting URL: https://space.bilibili.com/6444277/video
[download] Downloading playlist: 6444277
[BilibiliChannel] 6444277: Downloading page 1
[BilibiliChannel] Playlist 6444277: Downloading 0 videos of 0
[download] Finished downloading playlist: 6444277
```

**Comment by lockmatrix** [comment]
https://github.com/yt-dlp/yt-dlp/pull/4468 has fixed this, it is in master now, but not released.

**Comment by lockmatrix** [comment]
I have tried it on master, but get 
```
[debug] Command-line config: ['-vU', 'https://space.bilibili.com/6444277/video']
[debug] Encodings: locale cp936, fs utf-8, pref cp936, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.09.26.002903 [0500ee3] (win32_exe)
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg N-108089-gc92edd969a-20220910 (setts), ffprobe N-108089-gc92edd969a-20220910, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1674 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.09.01, Current version: 2022.09.26.002903
yt-dlp is up to date (2022.09.26.002903)
[debug] [BilibiliSpaceVideo] Extracting URL: https://space.bilibili.com/6444277/video
[BilibiliSpaceVideo] 6444277: Downloading page 1
ERROR: [BilibiliSpaceVideo] 6444277: Unable to download JSON metadata: HTTP Error 412: Precondition Failed (caused by <HTTPError 412: 'Precondition Failed'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 672, in extract
  File "yt_dlp\extractor\bilibili.py", line 555, in _real_extract
  File "yt_dlp\extractor\bilibili.py", line 511, in _extract_playlist
  File "yt_dlp\extractor\bilibili.py", line 538, in fetch_page
  File "yt_dlp\extractor\common.py", line 1032, in download_content
  File "yt_dlp\extractor\common.py", line 996, in download_handle
  File "yt_dlp\extractor\common.py", line 866, in _download_webpage_handle
  File "yt_dlp\extractor\common.py", line 823, in _request_webpage

  File "yt_dlp\extractor\common.py", line 805, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 3680, in urlopen
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 412: Precondition Failed
```

I'm working on it

**Comment by lockmatrix** [comment]
It seems will be blocked when request list api too fast, it is hard to download huge playlist like this case.
I dont know how to solve this problem elegantly.

I think should add a message for this first:
```
diff --git a/yt_dlp/extractor/bilibili.py b/yt_dlp/extractor/bilibili.py
--- a/yt_dlp/extractor/bilibili.py	(revision 0500ee3d81c5d31500d7093512deee2b0ff8aacd)
+++ b/yt_dlp/extractor/bilibili.py	(revision 41cbfede5d78d9145232913abc482bbc200c58cc)
@@ -7,6 +7,7 @@
 
 from .common import InfoExtractor, SearchInfoExtractor
 from ..compat import (
+    compat_HTTPError,
     compat_parse_qs,
     compat_urlparse,
     compat_urllib_parse_urlparse
@@ -535,10 +536,16 @@
                            'To download audios, add a "/audio" to the URL')
 
         def fetch_page(page_idx):
-            return self._download_json(
-                'https://api.bilibili.com/x/space/arc/search', playlist_id,
-                note=f'Downloading page {page_idx}',
-                query={'mid': playlist_id, 'pn': page_idx, 'jsonp': 'jsonp'})['data']
+            try:
+                data = self._download_json('https://api.bilibili.com/x/space/arc/search', playlist_id,
+                                            note=f'Downloading page {page_idx}',
+                                            query={'mid': playlist_id, 'pn': page_idx,
+                                                   'jsonp': 'jsonp'})['data']
+            except ExtractorError as e:
+                if isinstance(e.cause, compat_HTTPError) and e.cause.code == 412:
+                    raise ExtractorError('Request is blocked by server, please add cookies, wait and try later.', expected=True)
+                raise
+            return data
 
         def get_metadata(page_data):
             page_size = page_data['page']['ps']
```

**Comment by lockmatrix** [comment]
@kruumy 
I create a PR let you can control page fetching, https://github.com/yt-dlp/yt-dlp/pull/5043
build of this can be found at https://github.com/lockmatrix/yt-dlp/releases/tag/2022.09.26.031645

but it still can not solve this issue, downloading progress can still be blocked.

**Comment by kruumy** [comment]
Appreciate your work @lockmatrix 

I was playing around with the sleep time but even with something like 10 sec it still blocks the request after a few pages. I got no clue on a permanent workaround sadly but I do appreciate your help and contribution a ton!

**Comment by lockmatrix** [comment]
> Appreciate your work @lockmatrix
> 
> I was playing around with the sleep time but even with something like 10 sec it still blocks the request after a few pages. I got no clue on a permanent workaround sadly but I do appreciate your help and contribution a ton!

you need to login, use cookie from browers. It seems can fetch all pages, but still blocked when download

**Comment by lockmatrix** [comment]
Now, I dont know how to auto let site return the cookie for new user. I follow the network traffic, but can not find where the site gen the cookie

**Comment by lockmatrix** [comment]
I tested it now, it works (select 10 pages), if you are block, it seems you should wait a few hours.
```
yt-dlp.exe -vU --cookies-from-browser chrome  --extractor-args "BilibiliSpaceVideo:request_page_sleep_time=2;start_page=1;end_page=10" https://space.bilibili.com/6444277/video
```

**Comment by kruumy** [comment]
Seems to work well enough, not a complete fix but for what I am using it for (dumping all the pages and downloading certain videos individually based on some other logic from the dump), is a perfect workaround for now

**Comment by lockmatrix** [comment]
I updated the PR, now can use yt-dlp core feature to control download:
```
yt-dlp -vU https://space.bilibili.com/3985676/video --cookies-from-browser chrome --sleep-requests 2 --simulate --playlist-items 100:110
```

Note: playlist-items is based on video index, not page
