### ISSUE TITLE
ERROR: unable to open for writing: [Errno 36] File name too long:

### ISSUE THREAD

**Issue by rubyFeedback** [yt-dlp/yt-dlp#5060]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.09.01** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

The following website fails:

    ydl "https://twitter.com/JuliaDavisNews/status/1574860347697205262"

ydl is just my alias to yt-dlp on the commandline.

My browser does not play twitter videos for some reason so I download
via yt-dlp.

The error I get is:

    [twitter] 1574860347697205262: Downloading guest token
    [twitter] 1574860347697205262: Downloading JSON metadata
    [twitter] 1574860347697205262: Downloading m3u8 information
    [info] 1574860347697205262: Downloading 1 format(s): http-10368

    ERROR: unable to open for writing: [Errno 36] File name too long: "Julia Davis - Top Russian propagandist Vladimir 
    Solovyov is quite upset with how Putin's ＂partial mobilization＂ is going and everything the supposed ＂superpower＂ is 
    lacking. So much in this video, just watch. It fits right in with what I described in my latest article⤵️     
    [1574860347697205262].mp4.part"

Proposal to fix:

"if too long file name, and python is too stupid to handle long names, then rename
to a shorter name such as:

"Julia Davis - Top Russian _video_shortened_byyt_dlp.mp4"

or something like this. Right now it fails to download because of some weird
assumption it appears to be doing.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
See above.

PS: The template is really annoying to use. Do we also have to do sit ups
and leg push ups before filing a new bug report?

I mean it's just a simple bug. There is no magic behind it; I just fed
yt-dlp one remote URL. It failed. What more is there to show really? I
get that for some bug reports you need to know more information but 
the error reporting "too long file name" is not good. In ruby I'd just
check for the file size and automatically rename (and notify the user
about this too).
```

**Comment by dirkf** [comment]
Related: https://github.com/ytdl-org/youtube-dl/issues/29912

**Comment by october262** [comment]
try again with  yt-dlp -o "%(id)s.%(ext)s" "https://twitter.com/JuliaDavisNews/status/1574860347697205262"
the video will now download.

**Comment by pukkandan** [comment]
Read pinned issue
