### ISSUE TITLE
[Archive.org] Users, collections, and searches

### ISSUE THREAD

**Issue by Jadoo4QFan** [yt-dlp/yt-dlp#5061]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a site-specific feature
- [X] I've verified that I'm running yt-dlp version **2022.09.01** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

USA 

### Example URLs

https://archive.org/details/@kayvonkamyar (User)
https://archive.org/details/mirrortube (Collection)
https://archive.org/search.php?query=Bandu (Search)

### Provide a description that is worded well enough to be understood

Please add support for downloading a list of items on the Internet Archive. Please also add metadata to the playlists so we don’t have to worry about it later.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[Documents]$ 
[Documents]$ yt-dlp https://archive.org/details
/@kayvonkamyar -vU 
[debug] Command-line config: ['https://archive.
org/details/@kayvonkamyar', '-vU']
[debug] Encodings: locale UTF-8, fs utf-8, pref
 UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.09.01 [5d7c7d6] (pi
p)
[debug] Python 3.9.10+ (CPython 64bit) - macOS-
16.0-iPhone14,5-arm-64bit 
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg n5.0.1-4-ga5ebb3d2
5e (setts), ffprobe n5.0.1-4-ga5ebb3d25e, phant
omjs present, rtmpdump present
[debug] Optional libraries: Cryptodome-3.15.0, 
certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6
.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1670 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.09.01, Current version: 2022.09.01
yt-dlp is up to date (2022.09.01)
[debug] [archive.org] Extracting URL: https://archive.org/details/@kayvonkamyar
[archive.org] @kayvonkamyar: Downloading webpage
ERROR: list index out of range
Traceback (most recent call last):
  File "/var/mobile/Containers/Data/Application/BE92A072-84F0-4DB1-8FB4-0C9E11A11159/Library/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1459, in wrapper
    return func(self, *args, **kwargs)
  File "/var/mobile/Containers/Data/Application/BE92A072-84F0-4DB1-8FB4-0C9E11A11159/Library/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1535, in __extract_info
    ie_result = ie.extract(url)
  File "/var/mobile/Containers/Data/Application/BE92A072-84F0-4DB1-8FB4-0C9E11A11159/Library/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 670, in extract
    ie_result = self._real_extract(url)
  File "/var/mobile/Containers/Data/Application/BE92A072-84F0-4DB1-8FB4-0C9E11A11159/Library/lib/python3.9/site-packages/yt_dlp/extractor/archiveorg.py", line 227, in _real_extract
    playlist = self._playlist_data(embed_page)
  File "/var/mobile/Containers/Data/Application/BE92A072-84F0-4DB1-8FB4-0C9E11A11159/Library/lib/python3.9/site-packages/yt_dlp/extractor/archiveorg.py", line 210, in _playlist_data
    element = re.findall(r'''(?xs)
IndexError: list index out of range
[Documents]$ 
```

**Comment by Lesmiscore** [comment]
I, personally, recommend you to think about what "media downloader"s are, and what they can do for these Items on archive.org.

Items on archive.org can hold arbitrary files. For instance, .zip, .tiff or .tar can be stored.
Also, they have directory structures. It's too hard for yt-dlp to handle these kinds of structure.

So here's an another solution that should do what you want: https://github.com/rclone/rclone/

**Comment by Jadoo4QFan** [comment]
I know, but a portion of the collections are video and audio.

**Comment by chapmanjacobd** [comment]
I made a little tool that can help with this, extracting sublinks from pages:

For example:

    $ pip install xklb
    $ yt-dlp $(lb links --path-include /details/ --scroll 'https://archive.org/search?query=creator%3A%22Kinji+Fukasaku%22')
