### ISSUE TITLE
How to fix this error?

### ISSUE THREAD

**Issue by GhostShadow0316** [yt-dlp/yt-dlp#5067]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.09.01** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

When I start a yt-dlp download, it shows this:

`[youtube] nMfPqeZjc2c: Downloading webpage`
`[youtube] nMfPqeZjc2c: Downloading android player API JSON`
`[info] nMfPqeZjc2c: Downloading 1 format(s): 248+251`
`[download] Destination: White Noise Black Screen ｜ Sleep, Study, Focus ｜ 10 Hours [nMfPqeZjc2c].f248.webm`
`[download] 100% of 49.00MiB in 00:30 at 1.62MiB/s`
`[download] Destination: White Noise Black Screen ｜ Sleep, Study, Focus ｜ 10 Hours [nMfPqeZjc2c].f251.webm`
`[download] 100% of 507.62MiB in 05:02 at 1.68MiB/s`
`[Merger] Merging formats into "White Noise Black Screen ｜ Sleep, Study, Focus ｜ 10 Hours [nMfPqeZjc2c].webm"`
`ERROR: Postprocessing: Could not write header for output file #0 (incorrect codec parameters ?): Error number -22 occurred`

then it just stops.

how to fix this? I really want to download youtube videos

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
Provide complete verbose log

**Comment by gamer191** [comment]
@GhostShadow0316 Please read the full issue template
