### ISSUE TITLE
How can I check Duration without make 2 requests?

### ISSUE THREAD

**Issue by ghost** [yt-dlp/yt-dlp#5071]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.09.01** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Hi!

I'm using yt-dlp since beginning. Everything works fine but I have a problem. I make 2 requests 

1. --get-title, get-duration (So if Video is longer than 60 Min I down download it because of Server Resource)
2. yt-dlp "YouTube-video"

My question is: Is it somehow possible to make yt-dlp https://www.youtube.com/watch?v=.... (if duration >60 min) don't download it - else download it.

So that I don't have to make 2 requests - because google will ban IP. 

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by flashdagger** [comment]
```
yt-dlp --match-filter "duration>3600" <url>
```
