### ISSUE TITLE
bongacams.com moved to bongacams.net

### ISSUE THREAD

**Issue by MegaIO** [yt-dlp/yt-dlp#5075]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.09.01** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Provide a description that is worded well enough to be understood

bongacams.com has been moved to the new bongacams.net domain, please fix the code to work in the bongacams.net domain

**Comment by pukkandan** [comment]
> Provide verbose output that clearly demonstrates the problem

Could you explain to me how you think the log given demonstrates your problem?

**Comment by MegaIO** [comment]
> > Надайте докладні результати, які чітко демонструють проблему
> 
> Чи могли б ви пояснити мені, як, на вашу думку, наданий журнал демонструє вашу проблему?



> > Provide verbose output that clearly demonstrates the problem
> 
> Could you explain to me how you think the log given demonstrates your problem?
I don't know, it was written that this is part of the required template. I don't know English well, maybe I misunderstood something.

**Comment by pukkandan** [comment]
Atleast give example URLs. idk what you expect anyone to do to fix the issue without even that

**Comment by dirkf** [comment]
Same issue as https://github.com/ytdl-org/youtube-dl/issues/31262, with a patch that should equally apply here.
