### ISSUE TITLE
AbemaTV is not downloadable now

### ISSUE THREAD

**Issue by kpeejp** [yt-dlp/yt-dlp#5078]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.09.01** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Japan

### Provide a description that is worded well enough to be understood

 yt-dlp --version
2022.09.29.1664434149
An error occur and abort: message is,
ERROR: 'AbemaTVIE' object has no attribute '_LICENSE_HANDLER'

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-i', '-f', 'bestvideo+bestaudio/best', '-o', '%(title)s.%(ext)s', '--no-check-certificate', '-N', '3', '-vU', 'https://abema.tv/video/episode/90-1609_s41_p1']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] ytdl-patched version 2022.09.29.1664434149 [099269b] (zip)
[debug]      from commit 099269b89
[debug]      based on a5642f2c4
[debug] ** The command you are running is not yt-dlp.
[debug] ** Please make bug reports at https://github.com/ytdl-patched/ytdl-patched/issues/new/choose instead.
[debug] Lazy loading extractors is disabled
[debug] Python 3.8.12 (CPython 64bit) - CYGWIN_NT-10.0-19044-3.3.6-341.x86_64-x86_64-64bit-WindowsPE
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 5.1.2 (fdk,setts), ffprobe 5.1.2, phantomjs 2.1.1
[debug] Optional libraries: Crypto-3.10.1, WebSocketClientWrapper-None, certifi-2021.05.30, sqlite3-2.6.0, websockets-10.1
[debug] Proxy map: {}
[debug] Loaded 1713 extractors
[debug] Fetching release info: https://api.github.com/repos/ytdl-patched/ytdl-patched/releases/latest
Latest version: 2022.09.29.1664434149, Current version: 2022.09.29.1664434149
yt-dlp is up to date (2022.09.29.1664434149)
[debug] [AbemaTV] Extracting URL: https://abema.tv/video/episode/90-1609_s41_p1
[AbemaTV] Authorizing
[AbemaTV] [debug] Fetching webpage from https://api.abema.io/v1/users
[AbemaTV] 90-1609_s41_p1: Downloading webpage
[AbemaTV] [debug] Fetching webpage from https://abema.tv/video/episode/90-1609_s41_p1
[AbemaTV] 90-1609_s41_p1: Checking playability
[AbemaTV] [debug] Fetching webpage from https://api.abema.io/v1/video/programs/90-1609_s41_p1
[AbemaTV] 90-1609_s41_p1: Downloading m3u8 information
[AbemaTV] [debug] Fetching webpage from https://vod-abematv.akamaized.net/program/90-1609_s41_p1/playlist.m3u8
ERROR: 'AbemaTVIE' object has no attribute '_LICENSE_HANDLER'
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/yt_dlp/YoutubeDL.py", line 1542, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/youtube-dl/yt_dlp/YoutubeDL.py", line 1628, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/yt_dlp/extractor/common.py", line 702, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/yt_dlp/extractor/abematv.py", line 501, in _real_extract
    'callback': self._LICENSE_HANDLER.augment_hls_handler,
AttributeError: 'AbemaTVIE' object has no attribute '_LICENSE_HANDLER'

[debug] Cleaning up 1 streams
```

**Comment by llacb47** [comment]
```
[debug] ** The command you are running is not yt-dlp.
[debug] ** Please make bug reports at https://github.com/ytdl-patched/ytdl-patched/issues/new/choose instead.
```

?

**Comment by kpeejp** [comment]
I'm sorry.
