### ISSUE TITLE
udemy course download does not work: http 403, -u me@subdomain.domain.tld -p myStupidPass https://www.udemy.com/course/...

### ISSUE THREAD

**Issue by openfnord** [yt-dlp/yt-dlp#5081]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.09.01** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Germany

### Provide a description that is worded well enough to be understood

 I tried to download a free udemy course, which I can see in my webbrowser, also I did not click "enable DRM" and was able to see the video and to listen to the sound.
Webbrowser is firefox esr.
  
With yt-dlp, which I built from the repo today I got 403 with my credentials:
 
$ yt-dlp -Uv -u user@subdomain.domain.tld -p myStupidPass  https://www.udemy.com/course/some_course_url/?start=0#overview 
[debug] Command-line config: ['-Uv', '-u', 'PRIVATE', '-p', 'PRIVATE', 'https://www.udemy.com/course/some_course/learn/lecture/1234567890?start=0#overview']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.09.01 [5d7c7d656] (debian*)
[debug] Python 3.10.7 (CPython 64bit) - Linux-5.18.0-kali7-amd64-x86_64-with-glibc2.34 (glibc 2.34)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 5.1.1-2 (setts), ffprobe 5.1.1-2, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.11.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, pyxattr-0.7.2, sqlite3-2.6.0, websockets-10.2
[debug] Proxy map: {}
[debug] Loaded 1670 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.09.01, Current version: 2022.09.01
yt-dlp is up to date (2022.09.01)
[udemy:course] Downloading login popup
[udemy:course] Logging in
ERROR: [udemy:course] course: Unable to log in; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/common.py", line 668, in extract
    self.initialize()
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/common.py", line 574, in initialize
    self._perform_login(username, password)
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/udemy.py", line 198, in _perform_login
    raise ExtractorError('Unable to log in')

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
??$ yt-dlp -Uv -u user@subdomain.domain.tld -p myStupidPass  https://www.udemy.com/course/some_course_url/?start=0#overview 
[debug] Command-line config: ['-Uv', '-u', 'PRIVATE', '-p', 'PRIVATE', 'https://www.udemy.com/course/some_course/learn/lecture/1234567890?start=0#overview']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.09.01 [5d7c7d656] (debian*)
[debug] Python 3.10.7 (CPython 64bit) - Linux-5.18.0-kali7-amd64-x86_64-with-glibc2.34 (glibc 2.34)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 5.1.1-2 (setts), ffprobe 5.1.1-2, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.11.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, pyxattr-0.7.2, sqlite3-2.6.0, websockets-10.2
[debug] Proxy map: {}
[debug] Loaded 1670 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.09.01, Current version: 2022.09.01
yt-dlp is up to date (2022.09.01)
[udemy:course] Downloading login popup
[udemy:course] Logging in
ERROR: [udemy:course] course: Unable to log in; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/common.py", line 668, in extract
    self.initialize()
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/common.py", line 574, in initialize
    self._perform_login(username, password)
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/udemy.py", line 198, in _perform_login
    raise ExtractorError('Unable to log in')
```

**Comment by pukkandan** [comment]
https://github.com/yt-dlp/yt-dlp/issues/1164
