### ISSUE TITLE
[TikTok] Interaction Stickers

### ISSUE THREAD

**Issue by Jadoo4QFan** [yt-dlp/yt-dlp#5093]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a site-specific feature
- [X] I've verified that I'm running yt-dlp version **2022.09.01** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

USA

### Example URLs

https://www.tiktok.com/t/ZTRmCRKfv/
https://www.tiktok.com/t/ZTRmCRjNF/
https://www.tiktok.com/t/ZTRmCYwgH/
https://www.tiktok.com/t/ZTRmCN3uG/
https://www.tiktok.com/@newlinersseries/video/7148181531603897643?_r=1&u_code=e26e3635964a9j&preview_pb=0&language=en&_d=e2dmmdf2jd7k6j&share_item_id=7148181531603897643&source=h5_m&timestamp=1664588428&ug_btm=b8727,b2878&sec_user_id=MS4wLjABAAAAWRTxa9TmYNrI8T-5s9uJDRAEjUK47kceEtCRyFUIEsMang6XJwIvZMYGqCObcv8g&utm_source=copy&utm_campaign=client_share&utm_medium=ios&tt_from=copy&user_id=7106641030017270830&share_link_id=143EF17A-B3EB-4233-820F-4CDC664C3DFC&share_app_id=1233

### Provide a description that is worded well enough to be understood

Please add support for interaction stickers on TikTok. I need them personally for future searching and upscaling, but there are many other applications available for this data as well. I seen the code, and it seems like you tried to implement it as a subtitle format. You can either put it in the .info.json or make a new subtitle format called the .interaction_stickers.json .

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
Documents]$ yt-dlp -vU https://www.tiktok.com/
n 1 (char 0). Retrying... (attempt 1 of 5)
[TikTok] 7147358339746532654: Downloading video
 details
WARNING: [TikTok] Expecting value: line 1 colum
n 1 (char 0). Retrying... (attempt 2 of 5)
[TikTok] 7147358339746532654: Downloading video
 details
WARNING: [TikTok] Expecting value: line 1 colum
n 1 (char 0). Retrying... (attempt 3 of 5)
[TikTok] 7147358339746532654: Downloading video
 details
WARNING: [TikTok] Expecting value: line 1 colum
n 1 (char 0). Retrying... (attempt 4 of 5)
[TikTok] 7147358339746532654: Downloading video
 details
WARNING: [TikTok] 7147358339746532654: Failed t
o parse JSON; trying feed workaround
[TikTok] 7147358339746532654: Downloading video
 feed
[debug] Sort order given by extractor: quality,
 codec, size, br
[debug] Formats sorted by: hasvid, ie_pref, qua
lity, vcodec, acodec, filesize, fs_approx, tbr,
 vbr, abr, lang, res, fps, hdr:12(7), channels,
 asr, proto, vext, aext, hasaud, source, id
7147358339746532654 has no subtitles
```

**Comment by pukkandan** [comment]
You'll need to first explain to me what "interaction stickers" even are

**Comment by MinePlayersPE** [comment]
You need yt-dlp to do _what_ with the stickers? Also I don't visually see them on the 1st nor 2nd video

**Comment by Jadoo4QFan** [comment]
Download them to the info json or a caption json

**Comment by Jadoo4QFan** [comment]
![6FA00F9F-0BBD-4D9D-9F65-387A689FC3A0](https://user-images.githubusercontent.com/113491050/193420081-028ab215-8a9a-4d84-877e-77e564585cfb.png)
![DFC67008-F525-4D68-B192-6973C0A18507](https://user-images.githubusercontent.com/113491050/193420084-9e8eabff-91bb-4c43-936a-757ff07b2a02.png)
![95D31140-D411-4B73-B40C-5BFF43253E23](https://user-images.githubusercontent.com/113491050/193420086-c3841795-3410-47bb-aafc-191d7b2cdf53.png)
![CACA99ED-E59D-4CED-9C3B-5062EDFF5BA0](https://user-images.githubusercontent.com/113491050/193420087-2f9a97b2-aab8-422f-980f-92b39a1880c9.png)

**Comment by Jadoo4QFan** [comment]
Interaction Stickers are a field in the TikTok api json that has all the information about the stickers, including contents and timeframe. This includes text people put on TikTok, reply stickers, image stickers, and more. My use case is to archive TikTok videos and be able to search them easier with the text info, however you can upscale videos or interact with the videos (like supporting a nonprofit or viewing a reply)

**Comment by pukkandan** [comment]
I don't see any timed text/images in the webpage of the example URLs you have given

**Comment by Jadoo4QFan** [comment]
> I don't see any timed text/images in the webpage of the example URLs you have given

https://media.discordapp.net/attachments/1010778636976144394/1026178944682176582/RPReplay_Final1664730424.mp4

These stickers aren’t always interactive, most of the time, the text is static, however replies are in that coffee table video. They look static to desktop browsers and they are. It’s handy for interacting with replies and other interaction stickers, or searching text content of TikTok videos

**Comment by Jadoo4QFan** [comment]
Interaction Stickers are a field in the TikTok api json that has all the
information about the stickers, including contents and timeframe. This
includes text people put on TikTok, reply stickers, image stickers, and
more. My use case is to archive TikTok videos and be able to search them
easier with the text info, however you can upscale videos or interact with
the videos (like supporting a nonprofit or viewing a reply)
