### ISSUE TITLE
Man page generation mis-parses pairs of asterisks as emphasis

### ISSUE THREAD

**Issue by ninedotnine** [yt-dlp/yt-dlp#5108]
This paragraph in `README.md` has two asterisks in it:

```
    --download-sections REGEX       Download only chapters whose title matches
                                    the given regular expression. Time ranges
                                    prefixed by a "*" can also be used in place
                                    of chapters to download the specified range.
                                    Needs ffmpeg. This option can be used
                                    multiple times to download multiple
                                    sections, e.g. --download-sections
                                    "*10:15-inf" --download-sections "intro"
```

After the man page is generated by sending the text through `devscripts/prepare_manpage.py` and then `pandoc` (invoked in the `Makefile`), those asterisks are gone and the text between them is emphasized; it looks like this:

![scrot-12022-10-02-004418](https://user-images.githubusercontent.com/4495727/193438500-1ceb0103-7ff3-45f0-ab74-ef1d89584091.png)

**Comment by pukkandan** [comment]
Which part of this did you not understand?

> ### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE
> I understand that I will be blocked if I remove or skip any mandatory* field
