### ISSUE TITLE
[vimeo]support webinars/events link types

### ISSUE THREAD

**Issue by someziggyman** [yt-dlp/yt-dlp#5113]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.09.01** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

came across this link recently:
https://vimeo.com/webinars/events/71d8491c-6a00-46e1-b9c6-f0dde7b1b40e

yt-dlp uses generic extractor to handle it and fails with unsupported URL error. 
Still managed to get the video after clicking on Vimeo logo and getting direct video link:
https://vimeo.com/743057068?embedded=false&source=vimeo_logo&owner=138243006

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
./yt-dlp -vU -F "https://vimeo.com/webinars/events/71d8491c-6a00-46e1-b9c6-f0dde7b1b40e"
[debug] Command-line config: ['-vU', '-F', 'https://vimeo.com/webinars/events/71d8491c-6a00-46e1-b9c6-f0dde7b1b40e']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.09.01 [5d7c7d656] (zip)
[debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
[debug] Python 3.10.6 (CPython 64bit) - macOS-12.6-arm64-arm-64bit 
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: phantomjs 2.1.1
[debug] Optional libraries: sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Loaded 1721 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.09.01, Current version: 2022.09.01
yt-dlp is up to date (2022.09.01)
[debug] [generic] Extracting URL: https://vimeo.com/webinars/events/71d8491c-6a00-46e1-b9c6-f0dde7b1b40e
[generic] 71d8491c-6a00-46e1-b9c6-f0dde7b1b40e: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] 71d8491c-6a00-46e1-b9c6-f0dde7b1b40e: Extracting information
[debug] Looking for Brightcove embeds
[debug] Looking for embeds
ERROR: Unsupported URL: https://vimeo.com/webinars/events/71d8491c-6a00-46e1-b9c6-f0dde7b1b40e
Traceback (most recent call last):
  File "./yt-dlp/yt_dlp/YoutubeDL.py", line 1477, in wrapper
    return func(self, *args, **kwargs)
  File "./yt-dlp/yt_dlp/YoutubeDL.py", line 1553, in __extract_info
    ie_result = ie.extract(url)
  File "./yt-dlp/yt_dlp/extractor/common.py", line 672, in extract
    ie_result = self._real_extract(url)
  File "./yt-dlp/yt_dlp/extractor/generic.py", line 3074, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://vimeo.com/webinars/events/71d8491c-6a00-46e1-b9c6-f0dde7b1b40e
```

**Comment by pukkandan** [comment]
https://github.com/yt-dlp/yt-dlp/issues/1608
