### ISSUE TITLE
"No video formats found" error on Paramount+

### ISSUE THREAD

**Issue by heliosyne** [yt-dlp/yt-dlp#5119]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.09.01** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

USA

### Provide a description that is worded well enough to be understood

Downloading Twin Peaks from Paramount+ and all of the episodes downloaded except two: episodes 8 and 21 from season 2. 

URLs for those episodes:
https://www.paramountplus.com/shows/video/723621733/
https://www.paramountplus.com/shows/video/723703091/

These are both playable in a browser. Another tool I have for archiving content was able to retrieve the hls-4xxx (4.5 Mbps) format and subtitles streams, so the video is definitely there. 

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
$ yt-dlp -vU --embed-subs --check-formats --remux-video mkv -o '%(series)s s%(season_number)02de%(episode_number)02d %(title)s.%(ext)s' --cookies ../../_cookies/paramount+.txt https://www.paramountplus.com/shows/video/723621733/ https://www.paramountplus.com/shows/video/723703091/
[debug] Command-line config: ['-vU', '--embed-subs', '--check-formats', '--remux-video', 'mkv', '-o', '%(series)s s%(season_number)02de%(episode_number)02d %(title)s.%(ext)s', '--cookies', '../../_cookies/paramount+.txt', 'https://www.paramountplus.com/shows/video/723621733/', 'https://www.paramountplus.com/shows/video/723703091/']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.09.01 [5d7c7d6] (pip)
[debug] Python 3.9.14 (CPython 64bit) - FreeBSD-12.3-RELEASE-p6-amd64-64bit-ELF (libc 7)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.09.14, mutagen-1.45.1, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1670 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.09.01, Current version: 2022.09.01
yt-dlp is up to date (2022.09.01)
[debug] [ParamountPlus] Extracting URL: https://www.paramountplus.com/shows/video/723621733/
[ParamountPlus] 723621733: Downloading JSON metadata
[ParamountPlus] 723621733: Downloading JSON metadata
[ParamountPlus] 723621733: Downloading DASH_CENC_PRECON SMIL data
[ParamountPlus] 723621733: Downloading m3u8 information
WARNING: [ParamountPlus] Failed to download m3u8 information: HTTP Error 404: Not Found
[info] 723621733: Downloading subtitles: en
ERROR: [ParamountPlus] 723621733: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "/home/melissa/.local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1459, in wrapper
    return func(self, *args, **kwargs)
  File "/home/melissa/.local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1556, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/home/melissa/.local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1614, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/home/melissa/.local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 2546, in process_video_result
    self.raise_no_formats(info_dict)
  File "/home/melissa/.local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1025, in raise_no_formats
    raise ExtractorError(msg, video_id=info['id'], ie=info['extractor'],
yt_dlp.utils.ExtractorError: [ParamountPlus] 723621733: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

[debug] [ParamountPlus] Extracting URL: https://www.paramountplus.com/shows/video/723703091/
[ParamountPlus] 723703091: Downloading JSON metadata
[ParamountPlus] 723703091: Downloading JSON metadata
[ParamountPlus] 723703091: Downloading DASH_CENC_PRECON SMIL data
[ParamountPlus] 723703091: Downloading m3u8 information
WARNING: [ParamountPlus] Failed to download m3u8 information: HTTP Error 404: Not Found
[info] 723703091: Downloading subtitles: en
ERROR: [ParamountPlus] 723703091: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "/home/melissa/.local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1459, in wrapper
    return func(self, *args, **kwargs)
  File "/home/melissa/.local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1556, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/home/melissa/.local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1614, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/home/melissa/.local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 2546, in process_video_result
    self.raise_no_formats(info_dict)
  File "/home/melissa/.local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1025, in raise_no_formats
    raise ExtractorError(msg, video_id=info['id'], ie=info['extractor'],
yt_dlp.utils.ExtractorError: [ParamountPlus] 723703091: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

**Comment by bashonly** [comment]
After doing some testing with an account, I think those 2 episodes are only available as DASH formats w/ DRM

**Comment by pukkandan** [comment]
@bashonly Would it be possible to make the extractor detect this and raise appropriate error?

**Comment by bashonly** [comment]
@heliosyne I am able to find the HLS format you mention but it is DRM protected. Are you sure you're able to play the format downloaded by this other tool?

**Comment by heliosyne** [comment]
> @heliosyne I am able to find the HLS format you mention but it is DRM protected. Are you sure you're able to play the format downloaded by this other tool?

Yes.

**Comment by bashonly** [comment]
@heliosyne Any information you could provide about this playable HLS format or this other tool would help to fix this issue with yt-dlp. Otherwise, all I can find is DRM formats for those 2 episodes.

**Comment by heliosyne** [comment]
The other tool and is retrieving the DRM version. I think what threw me is that the other 28 episodes in the series are DRM-free, and yt-dlp didn't give the usual error when it encounters encrypted formats.

Are there command-line options to yt-dlp that would let me check for this on my own so that I can give better information when I encounter this behaviour (erroring out on DRM without saying it's due to DRM) in the future?

**Comment by bashonly** [comment]
If my current PR is merged, the ParamountPlus extractor will give an appropriate error message if only DRM formats are detected
