### ISSUE TITLE
Foxnews, updated website, unsupported URL

### ISSUE THREAD

**Issue by Nhb93** [yt-dlp/yt-dlp#5133]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.09.01** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

US

### Provide a description that is worded well enough to be understood

Very recently (sometime in the last week), Fox News changed their website for video playback, and apparently broke yt-dlp compatibility in the process. It had previously worked without fail under the previous design, so I'm just (hopefully correctly) bringing this issue up.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.foxnews.com/video/6313058664112']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.09.01 [5d7c7d6] (win32_exe)
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1670 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.09.01, Current version: 2022.09.01
yt-dlp is up to date (2022.09.01)
[debug] [generic] Extracting URL: https://www.foxnews.com/video/6313058664112
[generic] 6313058664112: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] 6313058664112: Extracting information
[debug] Looking for Brightcove embeds
[debug] Looking for embeds
ERROR: Unsupported URL: https://www.foxnews.com/video/6313058664112
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1459, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1535, in __extract_info
  File "yt_dlp\extractor\common.py", line 670, in extract
  File "yt_dlp\extractor\generic.py", line 3078, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.foxnews.com/video/6313058664112
```

**Comment by gamer191** [comment]
Does `yt-dlp https://video.foxnews.com/v/6313058664112` work?

Please leave this issue open, even if that workaround does work.

Note for maintainers: I didn't remove the `triage` label, because I haven't had time to read the triaging checklist yet

**Comment by Nhb93** [comment]
That command does work, which for now is very helpful. It just adds another step to copy-pasting the URL in the future, unless fixed of course.

**Comment by someziggyman** [comment]
Here's another link that works, but for some reason is handled with generic extractor instead of FOX extractor:
./yt-dlp -F "https://www.foxnews.com/video/6313788518112"
[generic] 6313788518112: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] 6313788518112: Extracting information
[generic] 6313788518112: Downloading webpage
[info] Available formats for 6313788518112:
ID  EXT RESOLUTION │ PROTO │ VCODEC  ACODEC
────────────────────────────────────────────
mp4 mp4 unknown    │ http  │ unknown unknown

**Comment by vitkhab** [comment]
Does the problem still persist?

The link (https://www.foxnews.com/video/6313058664112) provided by topic starter doesn't work anymore. I get 404 HTTP code in my browser. The direct link to video (https://video.foxnews.com/v/6313058664112) still works through yt-dlp. Maybe because it's still in CDN cache or something.

One of the recent videos does work (https://www.foxnews.com/video/6313896675112) both in browser and yt-dlp
```
yt-dlp https://www.foxnews.com/video/6313896675112 -Uv --skip-download
[debug] Command-line config: ['https://www.foxnews.com/video/6313896675112', '-Uv', '--skip-download']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.10.04 [4e0511f] (pip) API
[debug] Python 3.10.6 (CPython 64bit) - macOS-12.6-arm64-arm-64bit 
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 5.1.1 (setts), ffprobe 5.1.1
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1690 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.10.04, Current version: 2022.10.04
yt-dlp is up to date (2022.10.04)
[debug] [generic] Extracting URL: https://www.foxnews.com/video/6313896675112
[generic] 6313896675112: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] 6313896675112: Extracting information
[debug] Looking for Brightcove embeds
[debug] Looking for embeds
[debug] Identified a JSON LD
[debug] [generic] Extracting URL: http://vod.foxnews.com/media/v1/pmp4/static/clear/694940094001/088aee0d-7df2-4278-bf4c-eda935ac4769/24d84f52-06c9-4a3d-adac-da613f561016/main.mp4#__youtubedl_smuggle=%7B%22force_videoid%22%3A+%226313896675112%22%2C+%22to_generic%22%3A+true%2C+%22http_headers%22%3A+%7B%22Referer%22%3A+%22https%3A%2F%2Fwww.foxnews.com%2Fvideo%2F6313896675112%22%7D%7D
[generic] 6313896675112: Downloading webpage
[debug] Identified a direct video link
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 6313896675112: Downloading 1 format(s): mp4
```

**Comment by Nhb93** [comment]
Sorry for the delay in answering, but yes. Using a link in the format of the OP (www.foxnews.com/video/) still doesn't work, but using the workaround in the first reply (video.foxnews.com/v/) does. I personally use yt-dlg for it's GUI and that no longer shows the size while downloading or the speed while using the workaround.

**Comment by Nhb93** [comment]
Still getting this for a full episode, but it works on non-episode videos, at least through command line. I still need to figure out what's wrong with passing the update to yt-dlg.

yt-dlp https://www.foxnews.com/video/6314779941112
[generic] 6314779941112: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] 6314779941112: Extracting information
WARNING: [DetikEmbed] 6314779941112: Failed to parse JSON: Expecting ',' delimiter in '"{\n      "@type": "P': line 39 column 8 (char 2043)
WARNING: [generic] 6314779941112: Failed to parse JSON: Expecting ',' delimiter in '"{\n      "@type": "P': line 39 column 8 (char 2043)
ERROR: Unsupported URL: https://www.foxnews.com/video/6314779941112
