### ISSUE TITLE
How do stop yt-dlp from redownloading a video from a playlist that the name has been changed but video id remains the same?

### ISSUE THREAD

**Issue by voun-github** [yt-dlp/yt-dlp#5136]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.10.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

This is the method I used to embed yt-dlp in my script.

    def playlist_downloader(self, playlist_download_location):
        start = time.perf_counter()
        logger.info("..........Downloading videos from playlist..........")

        def my_hook(d):
            if d['status'] == 'error':
                logger.exception('An error has occurred ...')
            if d['status'] == 'finished':
                logger.info('Done downloading file, now post-processing ...')

        ydl_opts = {
            'logger': logger.getChild('ydl'),
            'progress_hooks': [my_hook],
            'noprogress': 'True',
            'format': 'bestvideo[ext=mp4]+bestaudio[ext=m4a]',
            'ffmpeg_location': 'ffmpeg/bin',
            'outtmpl': str(playlist_download_location) + '/%(title)s.%(ext)s'
        }
        with YoutubeDL(ydl_opts) as ydl:
            logger.debug(ydl.download(self.playlist_id))
        end = time.perf_counter()
        total_time = end - start
        logger.info(f"Total time downloading playlist took: {total_time}")

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by Grub4K** [comment]
Provide the `YoutubeDL` object with a `set` of already downloaded ids as its `download_archive` parameter. How you generate that set depends on how you can get back those ids from the already downloaded files.

The format is `<extractor_key> <video_id>`. Look at the output of `yt-dlp ---download-archive <file> <URL>` (or `YoutubeDL._make_archive_id`+`utils.make_archive_id`) to get more info on the used format.

**Comment by voun-github** [comment]
Thanks for your reply.

**Comment by pukkandan** [comment]
If it is more convenient, you can also give a filename instead of a set to use that file as the archive
