### ISSUE TITLE
Difference between quoted and unquoted mpd link

### ISSUE THREAD

**Issue by zhenyahacker** [yt-dlp/yt-dlp#5140]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.10.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

I have a link to the mpd manifest. Link contains no characters to be escaped but it contains second FQDN as its part.
When I pass it quoted onto brackets everything works fine, but when I pass it unquoted it gets a 404.
Investigated into this with fiddler proxy: the only difference is that quoted call makes yt-dlp use http user-agent with chrome version 91.0.4472.114, and unquoted call makes it to use user-agent with chrome 96.0.4664.93.
Why does webserver give 404 with one but not with another - dunno.

See link below at the debug output section.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
C:\Users\username>"C:\Programs\yt-dlp.exe" "https://htv-mag2-moscow2.mts.ru/htv-rrs.mts.ru/88888888/16/20210812/268628773/268628773.mpd" -vU
[debug] Command-line config: ['https://htv-mag2-moscow2.mts.ru/htv-rrs.mts.ru/88888888/16/20210812/268628773/268628773.mpd', '-vU']
[debug] Encodings: locale cp1251, fs utf-8, pref cp1251, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.10.04 [4e0511f] (win32_exe)
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 2020-09-30-git-9d8f9b2e40-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1690 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.10.04, Current version: 2022.10.04
yt-dlp is up to date (2022.10.04)
[debug] [generic] Extracting URL: https://htv-mag2-moscow2.mts.ru/htv-rrs.mts.ru/88888888/16/20210812/268628773/268628773.mpd
[generic] 268628773: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] 268628773: Extracting information
[debug] Identified a DASH manifest
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
ERROR: [generic] 268628773: This video is DRM protected
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1477, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1574, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1632, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2569, in process_video_result
  File "yt_dlp\YoutubeDL.py", line 1027, in raise_no_formats
yt_dlp.utils.ExtractorError: [generic] 268628773: This video is DRM protected


C:\Users\username>"C:\Programs\yt-dlp.exe" https://htv-mag2-moscow2.mts.ru/htv-rrs.mts.ru/88888888/16/20210812/268628773/268628773.mpd -vU
[debug] Command-line config: ['https://htv-mag2-moscow2.mts.ru/htv-rrs.mts.ru/88888888/16/20210812/268628773/268628773.mpd', '-vU']
[debug] Encodings: locale cp1251, fs utf-8, pref cp1251, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.10.04 [4e0511f] (win32_exe)
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 2020-09-30-git-9d8f9b2e40-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1690 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.10.04, Current version: 2022.10.04
yt-dlp is up to date (2022.10.04)
[debug] [generic] Extracting URL: https://htv-mag2-moscow2.mts.ru/htv-rrs.mts.ru/88888888/16/20210812/268628773/268628773.mpd
[generic] 268628773: Downloading webpage
ERROR: [generic] Unable to download webpage: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 672, in extract
  File "yt_dlp\extractor\generic.py", line 2614, in _real_extract
  File "yt_dlp\extractor\common.py", line 823, in _request_webpage

  File "yt_dlp\extractor\common.py", line 805, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 3682, in urlopen
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found


C:\Users\username>
```

**Comment by pukkandan** [comment]
yt-dlp randomly sets a user-agent for each call. If that UA is rejected by server for generic links, there is nothing we can do about it. You can force a specific UA using the `--add-headers` option

**Comment by pukkandan** [comment]
Just noticed example is DRM!

**Comment by zhenyahacker** [comment]
DRM is next step, so pls dont bother about it. I`ll force --allow-unplayable to download it.

**Comment by zhenyahacker** [comment]
> 



> yt-dlp randomly sets a user-agent for each call. If that UA is rejected by server for generic links, there is nothing we can do about it. You can force a specific UA using the `--add-headers` option

Okay, thak you. Could you please say variance limits of this randomness, and close the issue.

**Comment by pukkandan** [comment]
It may change from version to version. Currently it's https://github.com/yt-dlp/yt-dlp/blob/98d4ec1ef287cc5655ce6afd7b17755c57a245cb/yt_dlp/utils.py#L76-L118
