### ISSUE TITLE
https://www.autoweek.nl

### ISSUE THREAD

**Issue by M1Aston** [yt-dlp/yt-dlp#5143]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.10.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Netherlands

### Example URLs

https://www.autoweek.nl/autotests/artikel/porsche-911-gt3-rs-rij-impressie-2/
https://www.autoweek.nl/autotests/artikel/test-porsche-911-gt3-touring/

### Provide a description that is worded well enough to be understood

''list'' object has no attribute ''get''

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.10.04 [4e0511f] (win32_exe)
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1690 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.10.04, Current version: 2022.10.04
yt-dlp is up to date (2022.10.04)
[debug] [generic] Extracting URL: https://www.autoweek.nl/autotests/artikel/porsche-911-gt3-rs-rij-impressie-2/
[generic] porsche-911-gt3-rs-rij-impressie-2: Downloading webpage
[redirect] Following redirect to https://myprivacy.dpgmedia.nl/consent?siteKey=ujm6mv0jrqiz5syr&callbackUrl=https%3A%2F%2Fwww.autoweek.nl%2Fprivacygate-confirm%3FredirectUri%3D%252Fautotests%252Fartikel%252Fporsche-911-gt3-rs-rij-impressie-2%252F
[debug] [generic] Extracting URL: https://myprivacy.dpgmedia.nl/consent?siteKey=ujm6mv0jrqiz5syr&callbackUrl=https%3A%2F%2Fwww.autoweek.nl%2Fprivacygate-confirm%3FredirectUri%3D%252Fautotests%252Fartikel%252Fporsche-911-gt3-rs-rij-impressie-2%252F
[generic] consent?siteKey=ujm6mv0jrqiz5syr&callbackUrl=https://www.autoweek: Downloading webpage
[redirect] Following redirect to https://www.autoweek.nl/autotests/artikel/porsche-911-gt3-rs-rij-impressie-2/
[debug] [generic] Extracting URL: https://www.autoweek.nl/autotests/artikel/porsche-911-gt3-rs-rij-impressie-2/
[generic] porsche-911-gt3-rs-rij-impressie-2: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] porsche-911-gt3-rs-rij-impressie-2: Extracting information
[debug] Looking for Brightcove embeds
[debug] Looking for embeds
ERROR: 'list' object has no attribute 'get'
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1477, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1553, in __extract_info
  File "yt_dlp\extractor\common.py", line 672, in extract
  File "yt_dlp\extractor\generic.py", line 2793, in _real_extract
  File "yt_dlp\extractor\common.py", line 3881, in extract_from_webpage
  File "yt_dlp\extractor\detik.py", line 122, in _extract_from_webpage
  File "yt_dlp\extractor\common.py", line 1450, in _search_json_ld
  File "yt_dlp\extractor\common.py", line 1631, in _json_ld
  File "yt_dlp\extractor\common.py", line 1576, in traverse_json_ld
  File "yt_dlp\extractor\common.py", line 1624, in traverse_json_ld
AttributeError: 'list' object has no attribute 'get'
```

**Comment by pukkandan** [comment]
Due to #5145, the generic extractor now handles the given URL. If you have examples where generic is insufficient, the issue can be reopened
