### ISSUE TITLE
youtube av01 video playback no picture

### ISSUE THREAD

**Issue by shimiaoyerin** [yt-dlp/yt-dlp#5148]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.10.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

It can be seen that this video does not have an 8k option, but there is an 8k option in the background of the server, and it cannot be played after downloading. Why is this?

https://www.youtube.com/watch?v=1F_k5US20Ks
https://www.youtube.com/watch?v=6_yT1RLXC60

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
C:\Users\yerin>yt-dlp -vU
[debug] Command-line config: ['-vU']
[debug] Encodings: locale cp936, fs utf-8, pref cp936, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.09.01 [5d7c7d6] (win32_exe)
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg N-107627-g8e6759f10c-20220801 (setts), ffprobe N-107627-g8e6759f10c-20220801
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {'http': 'http://127.0.0.1:10081', 'https': 'https://127.0.0.1:10081', 'ftp': 'ftp://127.0.0.1:10081'}
[debug] Loaded 1670 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.10.04, Current version: 2022.09.01
[debug] Downloading _update_spec from https://github.com/yt-dlp/yt-dlp/releases/download/2022.10.04/_update_spec
Current Build Hash fc932a7478e536945895185abe529ad94d2385862df6e1b41fb970568dce7f7a
Updating to version 2022.10.04 ...
[debug] Downloading yt-dlp.exe from https://github.com/yt-dlp/yt-dlp/releases/download/2022.10.04/yt-dlp.exe
[debug] Downloading SHA2-256SUMS from https://github.com/yt-dlp/yt-dlp/releases/download/2022.10.04/SHA2-256SUMS
Updated yt-dlp to version 2022.10.04


--------------------------------------


C:\Users\yerin>yt-dlp https://www.youtube.com/watch?v=1F_k5US20Ks -F
[youtube] 1F_k5US20Ks: Downloading webpage
[youtube] 1F_k5US20Ks: Downloading android player API JSON
[info] Available formats for 1F_k5US20Ks:
ID  EXT   RESOLUTION FPS CH │   FILESIZE    TBR PROTO │ VCODEC           VBR ACODEC      ABR ASR MORE INFO
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
sb0 mhtml 48x27       14    │                   mhtml │ images                                   storyboard
599 m4a   audio only      2 │   26.96KiB    32k https │ audio only           mp4a.40.5   32k 22k ultralow, m4a_dash
600 webm  audio only      2 │   25.23KiB    31k https │ audio only           opus        31k 48k ultralow, webm_dash
139 m4a   audio only      2 │   41.95KiB    50k https │ audio only           mp4a.40.5   50k 22k low, m4a_dash
249 webm  audio only      2 │   37.31KiB    45k https │ audio only           opus        45k 48k low, webm_dash
250 webm  audio only      2 │   46.89KiB    57k https │ audio only           opus        57k 48k low, webm_dash
140 m4a   audio only      2 │  108.21KiB   130k https │ audio only           mp4a.40.2  130k 44k medium, m4a_dash
251 webm  audio only      2 │   84.65KiB   103k https │ audio only           opus       103k 48k medium, webm_dash
17  3gp   176x144      7  1 │   70.64KiB    85k https │ mp4v.20.3        85k mp4a.40.2    0k 22k 144p
597 mp4   144x256     15    │   37.39KiB    45k https │ avc1.4d400b      45k video only          144p, mp4_dash
598 webm  144x256     15    │   35.63KiB    43k https │ vp9              43k video only          144p, webm_dash
394 mp4   144x256     30    │   61.71KiB    75k https │ av01.0.00M.08    75k video only          144p, mp4_dash
160 mp4   144x256     30    │   97.62KiB   119k https │ avc1.4d400c     119k video only          144p, mp4_dash
278 webm  144x256     30    │   83.44KiB   101k https │ vp9             101k video only          144p, webm_dash
395 mp4   240x426     30    │  124.82KiB   152k https │ av01.0.00M.08   152k video only          240p, mp4_dash
133 mp4   240x426     30    │  211.18KiB   257k https │ avc1.4d4015     257k video only          240p, mp4_dash
242 webm  240x426     30    │  176.51KiB   215k https │ vp9             215k video only          240p, webm_dash
18  mp4   270x480     30  2 │  356.49KiB   430k https │ avc1.42001E     430k mp4a.40.2    0k 48k 240p
396 mp4   360x640     30    │  256.69KiB   312k https │ av01.0.01M.08   312k video only          360p, mp4_dash
134 mp4   360x640     30    │  489.65KiB   595k https │ avc1.4d401e     595k video only          360p, mp4_dash
243 webm  360x640     30    │  274.24KiB   333k https │ vp9             333k video only          360p, webm_dash
397 mp4   480x854     30    │  448.04KiB   545k https │ av01.0.04M.08   545k video only          480p, mp4_dash
135 mp4   480x854     30    │  920.36KiB  1119k https │ avc1.4d401f    1119k video only          480p, mp4_dash
244 webm  480x854     30    │  435.65KiB   529k https │ vp9             529k video only          480p, webm_dash
22  mp4   720x1280    30  2 │ ~  2.01MiB  2348k https │ avc1.64001F    2348k mp4a.40.2    0k 44k 720p
398 mp4   720x1280    30    │  911.30KiB  1108k https │ av01.0.05M.08  1108k video only          720p, mp4_dash
136 mp4   720x1280    30    │    1.78MiB  2219k https │ avc1.64001f    2219k video only          720p, mp4_dash
247 webm  720x1280    30    │  753.31KiB   916k https │ vp9             916k video only          720p, webm_dash
399 mp4   1080x1920   30    │    1.51MiB  1876k https │ av01.0.08M.08  1876k video only          1080p, mp4_dash
137 mp4   1080x1920   30    │    3.51MiB  4367k https │ avc1.640028    4367k video only          1080p, mp4_dash
248 webm  1080x1920   30    │    1.25MiB  1553k https │ vp9            1553k video only          1080p, webm_dash
400 mp4   1440x2560   30    │    4.56MiB  5677k https │ av01.0.12M.08  5677k video only          1440p, mp4_dash
271 webm  1440x2560   30    │    4.88MiB  6079k https │ vp9            6079k video only          1440p, webm_dash
401 mp4   2160x3840   30    │    9.17MiB 11408k https │ av01.0.12M.08 11408k video only          2160p, mp4_dash
313 webm  2160x3840   30    │    8.18MiB 10180k https │ vp9           10180k video only          2160p, webm_dash
571 mp4   4320x7680   30    │   18.07MiB 22493k https │ av01.0.16M.08 22493k video only          4320p, mp4_dash
```

**Comment by gamer191** [comment]
According to Wikipedia `4320x7680` is 8K. Do you have reason to believe otherwise?
> and it cannot be played after downloading

Is format `571` unplayable?

Note for maintainers: I have not triaged this issue

**Comment by shimiaoyerin** [comment]
> 

It is indeed 8k, but when you go to the video page, you cannot select 8K stream, but the server background can download to 8k

571 format can't be played after downloading

**Comment by pukkandan** [comment]
The browser tries to play the 8k format, and when it fails, it falls back to 4k. Not sure what we can do about this

**Comment by shimiaoyerin** [comment]
> The browser tries to play the 8k format, and when it fails, it falls back to 4k. Not sure what we can do about this

My program strategy is to choose the highest quality, it is really troublesome to encounter this, and it has to be screened out separately

**Comment by kribjo** [comment]
Do I understand correctly - the issue here is that your player setup does not support 8k video, and therefore you want to download the best video that is not above 4K?
Proposed solution: Add `--format "bestvideo*[width<=3840][height<=2160]+bestaudio"` to your yt-dlp command line options and it should do just what you want. (If you don't want to add that every time on the command line, you can put it in the yt-dlp config file.)

**Comment by shimiaoyerin** [comment]
> pukkandan

I can play 8K av1 video, but the 571 in this video can't be played, even pukkandan can't do anything

**Comment by pukkandan** [comment]
> Do I understand correctly - the issue here is that your player setup does not support 8k video, and therefore you want to download the best video that is not above 4K?

Issue is not with OP's setup. The video that YouTube provides in this case is damaged

**Comment by kribjo** [comment]
> I can play 8K av1 video, but the 571 in this video can't be played, even pukkandan can't do anything 

I see. That is good for you, and not so good for YouTube then.
I think it is unlikely to expect yt-dlp to know that YouTube serves up a damaged video and that you will have to check manually to catch cases such as these.
Perhaps you could use another tool to check the download afterwards, but since they seem OK also in MediaInfo, I am not sure how to do it. 

> Issue is not with OP's setup. The video that YouTube provides in this case is damaged

Yes, I agree, after testing properly. I can see other 8K YouTube videos, of 571 as well as other format ids, but not these ones.

**Comment by shimiaoyerin** [comment]
> > I can play 8K av1 video, but the 571 in this video can't be played, even pukkandan can't do anything
> 
> I see. That is good for you, and not so good for YouTube then. I think it is unlikely to expect yt-dlp to know that YouTube serves up a damaged video and that you will have to check manually to catch cases such as these. Perhaps you could use another tool to check the download afterwards, but since they seem OK also in MediaInfo, I am not sure how to do it.
> 
> > Issue is not with OP's setup. The video that YouTube provides in this case is damaged
> 
> Yes, I agree, after testing properly. I can see other 8K AV1 YouTube videos, of 571 as well as other format ids, but not these ones.

It's not a good thing for me because I'm collecting videos at the highest quality and it's frustrating to see this

**Comment by kribjo** [comment]
> It's not a good thing for me because I'm collecting videos at the highest quality and it's frustrating to see this

Since it is bad from YouTube I guess the only thing you could do is contact the account putting it up and alert them to the problem. Good luck!

**Comment by gamer191** [comment]
If browsers are able to detect that the video is corrupted and yt-dlp can't, couldn't a site like Tiktok soon start intentionally doing this to block/fingerprint yt-dlp? I'm not saying this is a high priority issue, but imo it's still a bug that should be reopened
