### ISSUE TITLE
[instagram] Problems logging in using netrc / -u / -p

### ISSUE THREAD

**Issue by RealDeviil** [yt-dlp/yt-dlp#5154]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.10.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Germany

### Provide a description that is worded well enough to be understood

Some Instagram videos that require a login are not downloading. So, I'm wondering if there is some issue with logging in (or using other means of authentication), and I suspect it may be due (at least, in part) to not getting valid ["shared_data"](https://github.com/yt-dlp/yt-dlp/blob/master/yt_dlp/extractor/instagram.py#L60) from the previous request to login URL. I think perhaps there have been some changes to the content of the login page. But I see that verbose output indicates login succeeded (when maybe it actually didn't??), so I'm pretty confused. 

I did find one [closed issue that was similar](https://github.com/yt-dlp/yt-dlp/issues/4750), but I was not sure if it was exactly the same issue or not. It seemed to be related to metadata extraction (or something like that), and it was closed with commit https://github.com/yt-dlp/yt-dlp/commit/2e7675489f4323c17c8de1e1fd264365c2c36e26. Also, I'm not sure if it resulted in complete failure. In this case, the issue results in complete failure, even when providing valid login/auth credentials with the yt-dlp command.

I hope at least some of this was intelligible. I tried to explain an issue that I don't really understand. 

I will also try to find at least one more video example that demonstrates this issue.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
root@vmi298562:/tmp/yt-dlp# python3.7 /usr/local/bin/yt-dlp -vU --write-pages -u username -p 'password' https://www.instagram.com/p/CjVGN-eqEfQ/
[debug] Command-line config: ['-vU', '--write-pages', '-u', 'PRIVATE', '-p', 'PRIVATE', 'https://www.instagram.com/p/CjVGN-eqEfQ/']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out UTF-8, error UTF-8, screen UTF-8
[debug] yt-dlp version 2022.10.04 [4e0511f27] API
[debug] Lazy loading extractors is disabled
[debug] Python 3.7.3 (CPython 64bit) - Linux-4.9.0-13-amd64-x86_64-with-debian-9.13 (glibc 2.17)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.2.2-static, ffprobe 4.2.2-static
[debug] Optional libraries: Cryptodome-3.11.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, websockets-9.1
[debug] Proxy map: {}
[debug] Loaded 1691 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.10.04, Current version: 2022.10.04
yt-dlp is up to date (2022.10.04)
[Instagram] Downloading login webpage
[Instagram] Saving request to None_https_-_www.instagram.com_accounts_login_.dump
[Instagram] Logging in
[Instagram] Saving request to None_https_-_www.instagram.com_accounts_login_ajax_.dump
[debug] [Instagram] Extracting URL: https://www.instagram.com/p/CjVGN-eqEfQ/
[Instagram] CjVGN-eqEfQ: Setting up session
[Instagram] Saving request to CjVGN-eqEfQ_https_-_i.instagram.com_api_v1_web_get_ruling_for_content_content_type=MEDIA_target_id=2942285280275089360.dump
[Instagram] CjVGN-eqEfQ: Downloading JSON metadata
WARNING: [Instagram] CjVGN-eqEfQ: General metadata extraction failed (some metadata might be missing).
[Instagram] CjVGN-eqEfQ: Downloading webpage
[Instagram] Saving request to CjVGN-eqEfQ_https_-_www.instagram.com_p_CjVGN-eqEfQ_.dump
WARNING: [Instagram] unable to extract shared data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [Instagram] Main webpage is locked behind the login page. Retrying with embed webpage (some metadata might be missing).
[Instagram] CjVGN-eqEfQ: Downloading embed webpage
[Instagram] Saving request to CjVGN-eqEfQ_https_-_www.instagram.com_p_CjVGN-eqEfQ_embed_.dump
WARNING: [Instagram] unable to extract additional data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
ERROR: [Instagram] CjVGN-eqEfQ: Requested content is not available, rate-limit reached or login required. Use --cookies, --cookies-from-browser, --username and --password, or --netrc (instagram) to provide account credentials
  File "/usr/local/lib/python3.7/site-packages/yt_dlp/extractor/common.py", line 672, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.7/site-packages/yt_dlp/extractor/instagram.py", line 457, in _real_extract
    self.raise_login_required('Requested content is not available, rate-limit reached or login required')
  File "/usr/local/lib/python3.7/site-packages/yt_dlp/extractor/common.py", line 1136, in raise_login_required
    raise ExtractorError(msg, expected=True)
```

**Comment by gamer191** [comment]
> It looks like there's a problem with yt-dlp logging in with credentials/netrc.
There is no sessionid cookie being set after login, which causes yt-dlp to bypass the authenticated extraction flow.

Is that only an instagram issue, or is it happening with all sites?

**Comment by bashonly** [comment]
> Is that only an instagram issue, or is it happening with all sites?

afaik only instagram. sorry, didn't mean to imply otherwise. edited my original comment to clarify

**Comment by RealDeviil** [comment]
I see that the original IG URL does not work without login as well:

```
root@vmi298562:/tmp/yt-dlp# python3.7 /usr/local/bin/yt-dlp -vU --write-pages https://www.instagram.com/p/CjVGN-eqEfQ/
[debug] Command-line config: ['-vU', '--write-pages', 'https://www.instagram.com/p/CjVGN-eqEfQ/']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out UTF-8, error UTF-8, screen UTF-8
[debug] yt-dlp version 2022.10.04 [4e0511f27] API
[debug] Lazy loading extractors is disabled
[debug] Python 3.7.3 (CPython 64bit) - Linux-4.9.0-13-amd64-x86_64-with-debian-9.13 (glibc 2.17)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.2.2-static, ffprobe 4.2.2-static
[debug] Optional libraries: Cryptodome-3.11.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, websockets-9.1
[debug] Proxy map: {}
[debug] Loaded 1691 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.10.04, Current version: 2022.10.04
yt-dlp is up to date (2022.10.04)
[debug] [Instagram] Extracting URL: https://www.instagram.com/p/CjVGN-eqEfQ/
[Instagram] CjVGN-eqEfQ: Setting up session
[Instagram] Saving request to CjVGN-eqEfQ_https_-_i.instagram.com_api_v1_web_get_ruling_for_content_content_type=MEDIA_target_id=2942285280275089360.dump
WARNING: [Instagram] CjVGN-eqEfQ: No csrf token set by Instagram API
[Instagram] CjVGN-eqEfQ: Downloading JSON metadata
WARNING: [Instagram] CjVGN-eqEfQ: General metadata extraction failed (some metadata might be missing).
[Instagram] CjVGN-eqEfQ: Downloading webpage
[Instagram] Saving request to CjVGN-eqEfQ_https_-_www.instagram.com_p_CjVGN-eqEfQ_.dump
WARNING: [Instagram] unable to extract shared data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [Instagram] Main webpage is locked behind the login page. Retrying with embed webpage (some metadata might be missing).
[Instagram] CjVGN-eqEfQ: Downloading embed webpage
[Instagram] Saving request to CjVGN-eqEfQ_https_-_www.instagram.com_p_CjVGN-eqEfQ_embed_.dump
WARNING: [Instagram] unable to extract additional data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
ERROR: [Instagram] CjVGN-eqEfQ: Requested content is not available, rate-limit reached or login required. Use --cookies, --cookies-from-browser, --username and --password, or --netrc (instagram) to provide account credentials
  File "/usr/local/lib/python3.7/site-packages/yt_dlp/extractor/common.py", line 672, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.7/site-packages/yt_dlp/extractor/instagram.py", line 457, in _real_extract
    self.raise_login_required('Requested content is not available, rate-limit reached or login required')
  File "/usr/local/lib/python3.7/site-packages/yt_dlp/extractor/common.py", line 1136, in raise_login_required
    raise ExtractorError(msg, expected=True)
```
I also see that using any kind of login/auth with IG consistently will result in what appears to be rate limiting (or maybe bot mitigation??) in the guise of a HTTP 403 Forbidden response. And it does not take many requests (using login credentials) to elicit this 403 response. In fact, in my case, as soon as I nixed the login credentials, I was able to resume downloading just about any IG video via the embed URLs.

Practically speaking, I have no problem forgoing login if I can still download the majority of IG videos (using the embed URLs). My only remaining question is: How is yt-dlp formatting the download requests for these embed URLs to circumvent bandwidth throttling? I have tried downloading the embed URLs independent of yt-dlp, and the downloads are very, very slow. So, I'd be interested to know what cookies/headers/etc. are being passed to the embed URL download requests (to circumvent this bandwidth throttling). (Note: I have reviewed the yt-dlp code, but I must be missing something.)

Thank you.

**Comment by RealDeviil** [comment]
> By "embed URLs" do you mean the CDN mp4 links? If so, you need to set a referer header of https://www.instagram.com/ or else the download speed will be throttled.

I tried this, and it had no effect for me. Ultimately, I had to adjust the download chunk size to fix the speed issue.

> Again, if you're talking about the CDN mp4 links, you do not need to pass cookies to download those. All required auth is handled in the query string and it's a different domain anyways from the .instagram.com cookies.

The cookie file is for requests to get download URLs prior to any download request. 

> The yt-dlp IG extractor does not do this. 

I'm not so familiar with yt-dlp that I know exactly how it functions and in what sequence it tries various things. But, what I can plainly see (as per my experience) is that, currently, it is relying almost exclusively on embed URLs for downloads -- because other extraction methods are generally not working. I also know that you can absolutely retrieve download URLs from the i.instagram.com API endpoint, because I've done it. (Or, rather, I was doing it when it was working.) I've experimented with the graphql endpoint, but, in my experience, it is not very effective for most videos.

**Comment by nitrofoska-g** [comment]
> It looks like there's a problem with the IG extractor logging in with credentials/netrc. There is no `sessionid` cookie being set after login, which causes yt-dlp to bypass the authenticated extraction flow.
> 
> You could try using `--cookies-from-browser` or `--cookies` instead of `-u` `-p`
> 
> Disclaimer: Using an IG account with yt-dlp is risky. IG employs various methods of detecting automated tool usage and if detected the account could be banned

It seems that they are detecting where the connections come from (connections from houses or hosting).
In my house it works perfect, in my vps it doesn't work. With the same posts.
I got banned like 10 accounts in 1 week btw be careful.

**Comment by RealDeviil** [comment]
> > It looks like there's a problem with the IG extractor logging in with credentials/netrc. There is no `sessionid` cookie being set after login, which causes yt-dlp to bypass the authenticated extraction flow.
> > You could try using `--cookies-from-browser` or `--cookies` instead of `-u` `-p`
> > Disclaimer: Using an IG account with yt-dlp is risky. IG employs various methods of detecting automated tool usage and if detected the account could be banned
> 
> It seems that they are detecting where the connections come from (connections from houses or hosting). In my house it works perfect, in my vps it doesn't work. With the same posts. I got banned like 10 accounts in 1 week btw be careful.

Even using cookies does not help much, on a commercial server...even if I manually and regularly update/maintain a cookie file, the cookies don't seem to last very long before they are deemed invalid...So, without a reliable means to **automatically** authenticate access to Insta videos and downloads, I may very well need to **manually** update the login cookie file as frequently as 1 once per week or even every X number of days (i.e., more than once per week)....What a headache!

I'm betting the bottom line is less about the origin of the Insta requests and more about the frequency of the requests. A server application is almost certainly sending more requests to Insta on the regular as opposed to someone only using yt-dlp for personal, home use -- since the former application is generally handling Insta requests for many people while the latter use-case only addresses the needs of a single person.

[nitrofoska-g](https://github.com/nitrofoska-g), are you sending the same frequency of Insta requests from your VPS vs. your home device/network?

**Comment by nitrofoska-g** [comment]
the vps was sending like 1k requests to ig per day or so, im really don't count it vs. my home like 5 or 10 requests max. Now im setting up a home server with dynamic ip from a mobile isp, just to see
