### ISSUE TITLE
ERROR: [facebook] 492246029437731: Cannot parse data; please report this issue on ...

### ISSUE THREAD

**Issue by sunsande** [yt-dlp/yt-dlp#5155]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.10.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Europe/Germany

### Provide a description that is worded well enough to be understood

I used `.\yt-dlp.exe https://www.facebook.com/watch?v=492246029437731 --cookies-from-browser firefox:...` to download the video and got the following message:
``
[Cookies] Extracting cookies from firefox
[Cookies] Extracted 318 cookies from firefox
[facebook] 492246029437731: Downloading webpage
[facebook] 492246029437731: Downloading webpage
ERROR: [facebook] 492246029437731: Cannot parse data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
``

There is definitely a problem with the facebook videos. I could download videos from other sites with/without cookies without problems.
I had the same problems with facebook videos with the last 3-4 releases of yt-dlp - and the problem is at least 4-5 months old.
Sites like savevideo.me do not have any problems downloading the video mentioned above.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['https://www.facebook.com/watch?v=492246029437731', '-vU', '--cookies-from-browser', 'firefox:x8lcuocw.dev-edition-default']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.10.04 [4e0511f] (win32_exe)
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[Cookies] Extracting cookies from firefox
[debug] Extracting cookies from: "C:\Users\XXXXXXXXXXXXXXXXX\AppData\Roaming\Mozilla\Firefox\Profiles\x8lcuocw.dev-edition-default\cookies.sqlite"
[Cookies] Extracted 330 cookies from firefox
[debug] Proxy map: {}
[debug] Loaded 1690 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.10.04, Current version: 2022.10.04
yt-dlp is up to date (2022.10.04)
[debug] [facebook] Extracting URL: https://www.facebook.com/watch?v=492246029437731
[facebook] 492246029437731: Downloading webpage
[facebook] 492246029437731: Downloading webpage
ERROR: [facebook] 492246029437731: Cannot parse data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 672, in extract
  File "yt_dlp\extractor\facebook.py", line 705, in _real_extract
  File "yt_dlp\extractor\facebook.py", line 651, in _extract_from_url
```

**Comment by pukkandan** [comment]
https://github.com/yt-dlp/yt-dlp/issues/4311 https://github.com/yt-dlp/yt-dlp/issues/4289

**Comment by gamer191** [comment]
@sunsande Does it work if you don't pass cookies?

**Comment by gamer191** [comment]
Actually, nevermind, this issue is a duplicate of those two issues

**Comment by sunsande** [comment]
> ~@sunsande Does it work if you don't pass cookies? (send verbose log)~

Yes, it works. Thank you!

**Comment by jimmy-1000** [comment]
> > ~@sunsande Does it work if you don't pass cookies? (send verbose log)~
> 
> Yes, it works. Thank you!

It works one or two times, no more that 🙁

**Comment by sunsande** [comment]
> It works one or two times, no more that 🙁

I've just tried it 3 consecutive times (without the cookies) and it worked without problems.  (I used `.\yt-dlp.exe https://www.facebook.com/watch?v=492246029437731`)

**Comment by jimmy-1000** [comment]
> > It works one or two times, no more that slightly_frowning_face
> 
> I've just tried it 3 consecutive times (without the cookies) and it worked without problems. (I used `.\yt-dlp.exe https://www.facebook.com/watch?v=492246029437731`)

I did it again, and it works only two times, and the third time I get "cannot parse data".
