### ISSUE TITLE
webvtt parser error for styled subtitles: Parse error at position 35 (near 'Style:\n::cue(c.color')

### ISSUE THREAD

**Issue by bennymi** [yt-dlp/yt-dlp#5158]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.10.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

I was trying to download the English subtitles for the following video and parse them with the webvtt.py file, but got a parser error due to the styling defined at the beginning of the file.

Video with styled captions: Tom Scott - "YouTube's Copyright System Isn't Broken. The World's Is."
URL: https://www.youtube.com/watch?v=1Jwo5qc78QU

My code:
```python
import requests
from yt_dlp import YoutubeDL, webvtt

v = 'https://www.youtube.com/watch?v=1Jwo5qc78QU'

YDL_OPTS = {
    'writesubtitles': True,
}
    
with YoutubeDL(YDL_OPTS) as ydl:
    videoInfo = ydl.extract_info(v, download=False)

    en_vtt_subs = [s for s in videoInfo['subtitles']['en'] if s['ext'] == 'vtt'][0]

    response = requests.get(en_vtt_subs['url'], stream=True)

    vtt_parser = webvtt.parse_fragment(response.content)

    for p_line in vtt_parser:
        print(p_line)
```

Perhaps the regular expression for the style block is no longer up to date?
https://github.com/yt-dlp/yt-dlp/blob/master/yt_dlp/webvtt.py

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[youtube] 1Jwo5qc78QU: Downloading webpage 
[youtube] 1Jwo5qc78QU: Downloading android player API JSON 
[info] 1Jwo5qc78QU: Downloading subtitles: en 
Traceback (most recent call last):
  File "c:\Users\user\Documents\Coding\My Projects\testing-code\test-captions.py", line 33, in <module>
    for p_line in vtt_parser:
  File "C:\Users\user\Anaconda3\envs\yt-dlp\lib\site-packages\yt_dlp\webvtt.py", line 363, in parse_fragment
    yield Magic.parse(parser)
  File "C:\Users\user\Anaconda3\envs\yt-dlp\lib\site-packages\yt_dlp\webvtt.py", line 217, in parse
    raise ParseError(parser)
yt_dlp.webvtt.ParseError: Parse error at position 35 (near 'Style:\n::cue(c.color')
```

**Comment by pukkandan** [comment]
The webvtt submodule is not meant for parsing arbitrary subtitles. It has the specific purpose of assembling fragmented subtitles - which this is not

**Comment by davidleboblai** [comment]
https://youtu.be/2EVn1z4DYXg
This video cant by donlad in y_dlp python in any way
Its bug
Can you cheak it?
