### ISSUE TITLE
[iq.com] subprocess.TimeoutExpired in call to phantomjs

### ISSUE THREAD

**Issue by TomasLoow** [yt-dlp/yt-dlp#5161]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.10.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Asia

### Provide a description that is worded well enough to be understood

When downloading from iq.com with a VIP account, the downloads fail with a `TimeoutExpired` error in the call to PhantomJS. None of the videos we've tried to download seem to work at the moment.

We're using the latest yt-dlp and phantomJS 2.1.1. We have tried it both with and without VPN connection.

It was working fine two weeks ago, so it seems like some update on their end broke things. 

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['--write-sub', '--sub-format', 'en', 'https://www.iq.com/play/love-in-the-air-episode-8-1uws9fp99kw?lang=en_us', '--cookies-from-browser', 'chrome', '-f', 'mp4', '-vU', '-o', 'loveair8.mp4']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.10.04 [4e0511f] (win32_exe)
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg n4.4.1-2-gcc33e73618-20211222 (setts), ffprobe n4.4.1-2-gcc33e73618-20211222, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[Cookies] Extracting cookies from chrome
[debug] Extracting cookies from: "C:\Users\Projekt Leia\AppData\Local\Google\Chrome\User Data\Default\Network\Cookies"
[debug] Found local state file at "C:\Users\Projekt Leia\AppData\Local\Google\Chrome\User Data\Local State"
[Cookies] Extracted 3472 cookies from chrome
[debug] cookie version breakdown: {'v10': 3472, 'other': 0, 'unencrypted': 0}
[debug] Proxy map: {}
[debug] Loaded 1690 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.10.04, Current version: 2022.10.04
yt-dlp is up to date (2022.10.04)
[debug] [iq.com] Extracting URL: https://www.iq.com/play/love-in-the-air-episode-8-1uws9fp99kw?lang=en_us
[iq.com] 1uws9fp99kw: Downloading webpage
[debug] Loading iq.player_js from cache
[iq.com] 1uws9fp99kw: Downloading VIP data
[debug] Loading iq.player_js from cache
[iq.com] 1uws9fp99kw: Executing signature code
[debug] [iq.com] PhantomJS command line: phantomjs "--ssl-protocol=any" "C:\Users\PROJEK~1\AppData\Local\Temp\tmprvl3wna6"
ERROR: [iq.com] 1uws9fp99kw: Executing signature code failed: Unable to run PhantomJS binary (caused by TimeoutExpired(['phantomjs', '--ssl-protocol=any', 'C:\\Users\\PROJEK~1\\AppData\\Local\\Temp\\tmprvl3wna6'], 10.0)); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 672, in extract
  File "yt_dlp\extractor\iqiyi.py", line 591, in _real_extract
  File "yt_dlp\extractor\openload.py", line 215, in get
  File "yt_dlp\extractor\openload.py", line 239, in execute

  File "yt_dlp\extractor\openload.py", line 236, in execute
  File "yt_dlp\utils.py", line 895, in run
  File "yt_dlp\utils.py", line 881, in communicate_or_kill
  File "subprocess.py", line 1028, in communicate
  File "subprocess.py", line 1401, in _communicate
subprocess.TimeoutExpired: Command '['phantomjs', '--ssl-protocol=any', 'C:\\Users\\PROJEK~1\\AppData\\Local\\Temp\\tmprvl3wna6']' timed out after 10.0 seconds
```

**Comment by pukkandan** [comment]
```diff
diff --git a/yt_dlp/extractor/iqiyi.py b/yt_dlp/extractor/iqiyi.py
index 6a43846c1..faf518232 100644
--- a/yt_dlp/extractor/iqiyi.py
+++ b/yt_dlp/extractor/iqiyi.py
@@ -588,7 +588,7 @@ def _real_extract(self, url):
             ut_list = ['0']

         # bid 0 as an initial format checker
-        dash_paths = self._parse_json(PhantomJSwrapper(self).get(
+        dash_paths = self._parse_json(PhantomJSwrapper(self, timeout=100_000).get(
             url, html='<!DOCTYPE html>', video_id=video_id, note2='Executing signature code', jscode=self._DASH_JS % {
                 'tvid': video_info['tvId'],
                 'vid': video_info['vid'],
```
will fix this. But someone has to experimentally determine what's a "just large enough" value to not timeout

**Comment by TomasLoow** [comment]
Thanks for the help @pukkadan! 

I applied the your patch locally and tested different values. On my computer, a value of 50_000 worked about 7 out of 10 attempts, a value of 55_000 worked 9 out of 10 and a value of 60_000 worked on all my attempts. 

So 60_000 might be a decent value to use based on that. Though timings will of course vary from computer to computer, so adding some slack might of course be reasonable.
