### ISSUE TITLE
Help modifying format options

### ISSUE THREAD

**Issue by JediMaster25** [yt-dlp/yt-dlp#5169]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.10.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I want to change the current format options to refuse to download a video without audio stream, and to choose a video with the closest `tbr` to 2000 kbps if there are no videos with the `720` option.
```
--format 'bestvideo[height<=?720][fps<=?30]+(worstaudio[abr>=64]/bestaudio)/best' 
```

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
This question smells like https://xyproblem.info. I can answer your question, but I suspect it actually wont help you unless you ask what u really want

    -f best -S res:720,tbr~7200

**Comment by JediMaster25** [comment]
Ok, I want the best video equal or lower to 720p, or the closest to 2000 kbps, and the worst audio above a bitrate of 64 kbps without exception. And if there is no audio I don't want the video. That is the broadest picture I can think of to avoid [the XY problem](https://xyproblem.info/).

So you are not mentioning the audio in the solution.

**Comment by pukkandan** [comment]
gotcha.

> to refuse to download a video without audio stream

This gave me the impression you wanted only pre-merged formats. Hence why I gave `best` in my solution

> or the closest bitrate to 2000 kbps 

Just to clarify, you want the bitrate **closest** to 2000k, not necessarily less than, correct? So 2400k would be preferred over 1000k. Then, use:

    -f bv+ba[abr<64] -S res,tbr~2000

If you actually mean less than, replace `~` with `:`

**Comment by pukkandan** [comment]
btw, if you are only concerned with youtube, you don't need any of this complexity. Youtube always provides abr=128k and height<=720

**Comment by JediMaster25** [comment]
> `-f bv+wa[abr>=64] -S res:720,tbr~2000`

Why doesn't -S require the less than or equal for the resolution? I haven't seen it on the README.

> btw, if you are only concerned with youtube, you don't need any of this complexity. Youtube always provides abr=128k and height<=720

I'm doing this because I've encountered a website that defaults to generic extractor and was giving me an error about an option not found. I was using this before and I needed to generalize it:
```
-f 'best[height<=720]'
```

Thanks you can mark the discussion as solved. I don't know how to do it.

**Comment by pukkandan** [comment]
> Why doesn't -S require the less than or equal for the resolution?

[Filtering formats](https://github.com/yt-dlp/yt-dlp#filtering-formats) (`-f`) and [sorting formats](https://github.com/yt-dlp/yt-dlp#sorting-formats) (`-S`) uses different syntax. Your problem was easiest to solve using a combination of both - it would get complicated with just `-f`

**Comment by JediMaster25** [comment]
This isn't working. I get
```
ERROR: Requested format is not available. Use --list-formats for a list of available formats
```

I need something generic that works with any extractor.

**Comment by gamer191** [comment]
> ERROR: Requested format is not available. Use --list-formats for a list of available formats

Can you please send the output of `yt-dlp URL --list-formats`?

**Comment by JediMaster25** [comment]
```
ID         EXT RESOLUTION FPS │   FILESIZE   TBR PROTO │ VCODEC        VBR ACODEC    ABR
────────────────────────────────────────────────────────────────────────────────────────
240p       mp4 240p           │                  https │ unknown           unknown
hls-386    mp4 426x240     30 │ ~ 30.17MiB  387k m3u8  │ avc1.640015  387k mp4a.40.2  0k
480p       mp4 480p           │                  https │ unknown           unknown
hls-816-0  mp4 854x480     30 │ ~ 63.65MiB  816k m3u8  │ avc1.64001f  816k mp4a.40.2  0k
hls-816-1  mp4 854x480     30 │ ~ 63.65MiB  816k m3u8  │ avc1.64001f  816k mp4a.40.2  0k
720p       mp4 720p           │                  https │ unknown           unknown
hls-1605-0 mp4 1280x720    30 │ ~125.25MiB 1606k m3u8  │ avc1.640020 1606k mp4a.40.2  0k
hls-1605-1 mp4 1280x720    30 │ ~125.25MiB 1606k m3u8  │ avc1.640020 1606k mp4a.40.2  0k

[debug] Sort order given by user: res:720, tbr~2000
[debug] Sort order given by extractor: height, width, fps, format_id
[debug] Formats sorted by: hasvid, ie_pref, res:720(720.0), tbr~2000(2000.0), height, width, fps, id, lang, quality, hdr:12(7), vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, vbr, abr, asr, proto, vext, aext, hasaud, source
```

**Comment by pukkandan** [comment]
There is no format matching your conditions. Specifically, yt-dlp doesn't know the bitrate of the audio formats. So it cant tell if they are >64k

**Comment by pukkandan** [comment]
If you also want to allow formats with unknown info, use the `?` operator

**Comment by gamer191** [comment]
> `ID EXT RESOLUTION FPS │ FILESIZE TBR PROTO │ VCODEC VBR ACODEC ABR ──────────────────────────────────────────────────────────────────────────────────────── 240p mp4 240p │ https │ unknown unknown hls-386 mp4 426x240 30 │ ~ 30.17MiB 387k m3u8 │ avc1.640015 387k mp4a.40.2 0k 480p mp4 480p │ https │ unknown unknown hls-816-0 mp4 854x480 30 │ ~ 63.65MiB 816k m3u8 │ avc1.64001f 816k mp4a.40.2 0k hls-816-1 mp4 854x480 30 │ ~ 63.65MiB 816k m3u8 │ avc1.64001f 816k mp4a.40.2 0k 720p mp4 720p │ https │ unknown unknown hls-1605-0 mp4 1280x720 30 │ ~125.25MiB 1606k m3u8 │ avc1.640020 1606k mp4a.40.2 0k hls-1605-1 mp4 1280x720 30 │ ~125.25MiB 1606k m3u8 │ avc1.640020 1606k mp4a.40.2 0k`

How can formats have an ABR of 0k? That looks like a bug to me 🤷‍♂️

**Comment by JediMaster25** [comment]
If it can't get the worst audio above 64k, I want to get the best audio. Would that be like this?
```
-f bv+wa[abr>=64]/ba -S res:720,tbr~2000
```

**Comment by pukkandan** [comment]
Previously, you explicitly said you do not want to download anything if there is no matching audio...

> If it can't get the worst audio above 64k, I want to get the best audio. Would that be like this?
> 
> ```
> -f bv+wa[abr>=64]/ba -S res:720,tbr~2000
> ```

Almost. That still does not account for pre-merged formats

    -f (bv+(wa[abr>=64]/ba))/b -S res:720,tbr~2000

Should cover everything

but then it's easier to give:

    -S res:720,vbr~2000,+abr:64

which accomplishes nearly the same thing


I strongly recommend you go through the docs I linked above

**Comment by JediMaster25** [comment]
I don't want to download videos without an audio stream. But if there is audio and I can't find the worst above 64k, I still want to find one.

I'll try this for a couple of days and then close it if it works fine, so we are not opening and closing the issue.

**Comment by gamer191** [comment]
> I don't want to download videos without an audio stream

According to my understanding of the documentation, `-f (bv+(wa[abr>=64]/ba))/b -S res:720,tbr~2000` shouldn't download anything if there is either no video or no audio. 
But by my understanding, the default option (`bv*+ba/b`) also shouldn't download anything if there is either no video or no audio, and yt-dlp definitely works on Spotify podcasts, so now I'm confused

**Comment by pukkandan** [comment]
> and yt-dlp definitely works on Spotify podcasts, so now I'm confused

There's some special handling for this case

---

Why'd u re-open?

**Comment by gamer191** [comment]
> There's some special handling for this case

I see

> Why'd u re-open?

I thought that my question related to OP's question enough that I could just reuse this issue. I'll open a new issue next time

**Comment by pukkandan** [comment]
Don't remove your post
