### ISSUE TITLE
ERROR: unable to download video data: [Errno 13] Permission denied:

### ISSUE THREAD

**Issue by nochlab1** [yt-dlp/yt-dlp#517]
## Checklist

- [ ] I'm reporting a broken site support issue
- [ ] I've verified that I'm running yt-dlp version **2021.07.07**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] yt-dlp version 2021.07.07 (exe)
[debug] Python version 3.9.6 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] exe versions: ffmpeg 4.3.1-2020-11-19-full_build-www.gyan.dev, ffprobe 4.3.1-2020-11-19-full_build-www.gyan.dev
[debug] Proxy map: {}
[debug] [generic] Extracting URL: _Link Redacted_
[generic] master: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] master: Downloading webpage
[generic] master: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Downloading subtitles: de, he, fr, es, en, ru, yi

```

## Description

when using native downloader a lot of times it fails with error "ERROR: unable to download video data: [Errno 13] Permission denied:" but if i retry it works, how do i make it retry automatically ? i tried --retries infinite but its not retrying

(i didnt checkbox latest version  **2021.07.07** because i am using version built today but also fails on latest "stable")

**Comment by pukkandan** [comment]
I assume you are on https://github.com/yt-dlp/yt-dlp/commit/ccc7795ca3523be07c69afb95f08b2f583197327?

Also, please add the **entire** verbose log upto and including the error, not just the head

**Comment by nochlab1** [comment]
i am on da1c94e

**Comment by nochlab1** [comment]
C:\Users\nochl\Desktop\New folder (7)>yt-dlp -v https://deybpcaja6zfo.cloudfront.net/cbb7f4e0-e8e4-4fb1-9252-c73300bbd5bf/hls_264/hd/master.m3u8
[debug] Command-line config: ['-v', 'https://deybpcaja6zfo.cloudfront.net/cbb7f4e0-e8e4-4fb1-9252-c73300bbd5bf/hls_264/hd/master.m3u8']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] yt-dlp version 2021.07.07 (exe)
[debug] Python version 3.9.6 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] exe versions: ffmpeg 4.3.1-2020-11-19-full_build-www.gyan.dev, ffprobe 4.3.1-2020-11-19-full_build-www.gyan.dev
[debug] Proxy map: {}
[debug] [generic] Extracting URL: https://deybpcaja6zfo.cloudfront.net/cbb7f4e0-e8e4-4fb1-9252-c73300bbd5bf/hls_264/hd/master.m3u8
[generic] master: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] master: Downloading webpage
[generic] master: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] master: Downloading 1 format(s): 6016+audio-Hebrew-1
[debug] Invoking downloader on "https://deybpcaja6zfo.cloudfront.net/cbb7f4e0-e8e4-4fb1-9252-c73300bbd5bf/hls_264/hd/video/1080_6000_264.m3u8"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 161
[download] Destination: master [master].f6016.mp4
[download]   6.8% of ~592.80MiB at  8.08MiB/s ETA 01:12    ERROR: unable to download video data: [Errno 13] Permission denied: 'master [master].f6016.mp4.ytdl'
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 2651, in process_info
  File "yt_dlp\YoutubeDL.py", line 2336, in dl
  File "yt_dlp\downloader\common.py", line 385, in download
  File "yt_dlp\downloader\hls.py", line 324, in real_download
  File "yt_dlp\downloader\fragment.py", line 420, in download_and_append_fragments
  File "yt_dlp\downloader\fragment.py", line 398, in append_fragment
  File "yt_dlp\downloader\fragment.py", line 148, in _append_fragment
  File "yt_dlp\downloader\fragment.py", line 107, in _write_ytdl_file
  File "yt_dlp\utils.py", line 2062, in sanitize_open
PermissionError: [Errno 13] Permission denied: 'master [master].f6016.mp4.ytdl'

**Comment by ehoogeveen-medweb** [comment]
This occasionally happens on my laptop but I've never seen it on my desktop. I was wondering if it could be virus scanner related but excluding the download folder from the locations to monitor doesn't help. I imagine my stack is the same as above but I can try to get a log as well.

**Comment by nochlab1** [comment]
if i rerun the command it continues good, sometimes it errors again but at different places

**Comment by pukkandan** [comment]
@nochlab1 Are you running multiple instances of yt-dlp? Is there some other application that may be locking the `.ytdl` file?

If neither of these is the issue, there may be some bug in yt-dlp that is causing the `.ytdl` file to be kept locked and thus inaccessible to other parts of the code. In that case, I'll investigate

**Comment by nochlab1** [comment]
last time it happened i did have multiple instances open

**Comment by nochlab1** [comment]
but it also happened when i let something run for a long time

**Comment by nochlab1** [comment]
i just got it with only 1 instance open (shows same line numbers in the py file so not not posting verbose again if needed i can send)

**Comment by nochlab1** [comment]
C:\Users\nochl\Desktop\New folder (10)>yt-dlp -v --all-subs --embed-subs --audio-multistreams -o "It’s Up To Us - 875" -f bestvideo+audio-English-1+audio-Hebrew-1 https://deybpcaja6zfo.cloudfront.net/c59463ab-e8e5-4d89-b5d2-5e2a382e689c/hls_264/hd/master.m3u8
[debug] Command-line config: ['-v', '--all-subs', '--embed-subs', '--audio-multistreams', '-o', 'It’s Up To Us - 875', '-f', 'bestvideo+audio-English-1+audio-Hebrew-1', 'https://deybpcaja6zfo.cloudfront.net/c59463ab-e8e5-4d89-b5d2-5e2a382e689c/hls_264/hd/master.m3u8']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] yt-dlp version 2021.07.07 (exe)
[debug] Python version 3.9.6 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] exe versions: ffmpeg 4.3.1-2020-11-19-full_build-www.gyan.dev, ffprobe 4.3.1-2020-11-19-full_build-www.gyan.dev
[debug] Proxy map: {}
[debug] [generic] Extracting URL: https://deybpcaja6zfo.cloudfront.net/c59463ab-e8e5-4d89-b5d2-5e2a382e689c/hls_264/hd/master.m3u8
[generic] master: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] master: Downloading webpage
[generic] master: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Downloading subtitles: en, fr, es
[info] master: Downloading 1 format(s): 5991+audio-English-1+audio-Hebrew-1
[info] Writing video subtitles to: It’s Up To Us - 875.en.vtt
[debug] Invoking downloader on "https://deybpcaja6zfo.cloudfront.net/c59463ab-e8e5-4d89-b5d2-5e2a382e689c/hls_264/hd/text/en.m3u8"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 133
[download] Destination: It’s Up To Us - 875.en.vtt
**[download]  92.5% of ~23.81KiB at 179.72KiB/s ETA 00:02WARNING: Unable to download subtitle for "en": [Errno 13] Permission denied: 'It’s Up To Us - 875.en.vtt.ytdl'**
[info] Writing video subtitles to: It’s Up To Us - 875.fr.vtt
[debug] Invoking downloader on "https://deybpcaja6zfo.cloudfront.net/c59463ab-e8e5-4d89-b5d2-5e2a382e689c/hls_264/hd/text/fr.m3u8"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 133
[download] Destination: It’s Up To Us - 875.fr.vtt
**[download]  12.0% of ~4.46KiB at 160.41KiB/s ETA 00:27WARNING: Unable to download subtitle for "fr": [Errno 13] Permission denied: 'It’s Up To Us - 875.fr.vtt.ytdl'**
[info] Writing video subtitles to: It’s Up To Us - 875.es.vtt
[debug] Invoking downloader on "https://deybpcaja6zfo.cloudfront.net/c59463ab-e8e5-4d89-b5d2-5e2a382e689c/hls_264/hd/text/es.m3u8"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 133
[download] Destination: It’s Up To Us - 875.es.vtt
[download] 100% of 15.60KiB in 00:20
[debug] Invoking downloader on "https://deybpcaja6zfo.cloudfront.net/c59463ab-e8e5-4d89-b5d2-5e2a382e689c/hls_264/hd/video/1080_6000_264.m3u8"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 151
[download] Destination: It’s Up To Us - 875.f5991
[download]  82.8% of ~631.07MiB at 11.05MiB/s ETA 00:23    ERROR: unable to download video data: [Errno 13] Permission denied: 'It’s Up To Us - 875.f5991.ytdl'
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 2651, in process_info
  File "yt_dlp\YoutubeDL.py", line 2336, in dl
  File "yt_dlp\downloader\common.py", line 385, in download
  File "yt_dlp\downloader\hls.py", line 324, in real_download
  File "yt_dlp\downloader\fragment.py", line 420, in download_and_append_fragments
  File "yt_dlp\downloader\fragment.py", line 398, in append_fragment
  File "yt_dlp\downloader\fragment.py", line 148, in _append_fragment
  File "yt_dlp\downloader\fragment.py", line 107, in _write_ytdl_file
  File "yt_dlp\utils.py", line 2062, in sanitize_open
PermissionError: [Errno 13] Permission denied: 'It’s Up To Us - 875.f5991.ytdl' #

**Comment by nochlab1** [comment]
also in this one i am downloading subtitles and when it fails in subtitles it just goes to next one so even if i rerun it i am missing that subtitle

**Comment by nochlab1** [comment]
it seems like if i download in the "dist" folder where i built it its not failing

**Comment by ehoogeveen-medweb** [comment]
Had this failure on my laptop again. Here's the verbose log:
```
[debug] User config file: C:\Users\[username]\AppData\Roaming\yt-dlp\config.txt
[debug] User config: ['--verbose', '--ignore-errors', '--retries', '100', '--fragment-retries', '100', '--skip-unavailable-fragments', '--merge-output-format', 'mkv', '--buffer-size', '16K', '--ffmpeg-location', 'C:/ffmpeg/bin', '--cookies', 'C:/Users/[username]/yt-dlp-cookies.txt', '--write-sub', '--sub-lang', 'en-GB,en-US,en', '--audio-quality', '0', '--throttled-rate', '100K', '-o', '%(uploader)s - %(playlist_autonumber)03d - %(upload_date)s - %(title)s (%(resolution)sp%(fps).0f %(vcodec)s, %(abr).0fkbps %(acodec)s).%(ext)s']
[debug] Command-line config: ['https://www.twitch.tv/videos/1091603358']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] yt-dlp version 2021.07.07
[debug] Python version 3.9.6 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] exe versions: ffmpeg 2021-07-14-git-ca56299fb3-full_build-www.gyan.dev, ffprobe 2021-07-14-git-ca56299fb3-full_build-www.gyan.dev
[debug] Proxy map: {}
[debug] [twitch:vod] Extracting URL: https://www.twitch.tv/videos/1091603358
[twitch:vod] 1091603358: Downloading stream metadata GraphQL
[twitch:vod] 1091603358: Downloading video access token GraphQL
[twitch:vod] 1091603358: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Downloading subtitles:
[debug] Default format spec: bestvideo*+bestaudio/best
[info] v1091603358: Downloading 1 format(s): 720p60-1
[debug] Invoking downloader on "https://d1ymi26ma8va5x.cloudfront.net/2da10fafc9d3284f42c5_kikoskia_42688534684_1626716400/chunked/index-dvr.m3u8"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 1051
[download] Destination: Kikoskia - NA - 20210719 - Let's Stream Pokemon Crystal! [We Kanto Back Now] (1280x720p60 avc1.640020, 0kbps mp4a.40.2).mp4
[download]  97.0% of ~7.87GiB at 26.97MiB/s ETA 00:17      ERROR: unable to download video data: [Errno 13] Permission denied: "Kikoskia - NA - 20210719 - Let's Stream Pokemon Crystal! [We Kanto Back Now] (1280x720p60 avc1.640020, 0kbps mp4a.40.2).mp4.ytdl"
Traceback (most recent call last):
  File "c:\users\[username]\appdata\local\programs\python\python39\lib\site-packages\yt_dlp\YoutubeDL.py", line 2672, in process_info
    success, real_download = self.dl(temp_filename, info_dict)
  File "c:\users\[username]\appdata\local\programs\python\python39\lib\site-packages\yt_dlp\YoutubeDL.py", line 2335, in dl
    return fd.download(name, new_info, subtitle)
  File "c:\users\[username]\appdata\local\programs\python\python39\lib\site-packages\yt_dlp\downloader\common.py", line 385, in download
    return self.real_download(filename, info_dict), True
  File "c:\users\[username]\appdata\local\programs\python\python39\lib\site-packages\yt_dlp\downloader\hls.py", line 324, in real_download
    return self.download_and_append_fragments(ctx, fragments, info_dict, pack_fragment)
  File "c:\users\[username]\appdata\local\programs\python\python39\lib\site-packages\yt_dlp\downloader\fragment.py", line 420, in download_and_append_fragments
    result = append_fragment(decrypt_fragment(fragment, frag_content), frag_index, ctx)
  File "c:\users\[username]\appdata\local\programs\python\python39\lib\site-packages\yt_dlp\downloader\fragment.py", line 398, in append_fragment
    self._append_fragment(ctx, pack_func(frag_content, frag_index))
  File "c:\users\[username]\appdata\local\programs\python\python39\lib\site-packages\yt_dlp\downloader\fragment.py", line 148, in _append_fragment
    self._write_ytdl_file(ctx)
  File "c:\users\[username]\appdata\local\programs\python\python39\lib\site-packages\yt_dlp\downloader\fragment.py", line 107, in _write_ytdl_file
    frag_index_stream, _ = sanitize_open(self.ytdl_filename(ctx['filename']), 'w')
  File "c:\users\[username]\appdata\local\programs\python\python39\lib\site-packages\yt_dlp\utils.py", line 2062, in sanitize_open
    stream = open(encodeFilename(filename), open_mode)
PermissionError: [Errno 13] Permission denied: "Kikoskia - NA - 20210719 - Let's Stream Pokemon Crystal! [We Kanto Back Now] (1280x720p60 avc1.640020, 0kbps mp4a.40.2).mp4.ytdl"
```
The Python built-in `open` function is failing with a permission denied error. I have no idea why it's failing, but since it usually works (in this case the download was 97% done), I think it would probably work if `sanitize_open` tried it a 2nd time.

**Comment by pukkandan** [comment]
Even after multiple tries I could not reproduce this. I also looked for all places in the code where the file handle could have been left open. I found one potential issue, but could not find any workflow that could trigger this issue. In any case, I have patched that in https://github.com/yt-dlp/yt-dlp/commit/ad3dc496bbf2e2a574a16244ddde0740778e5daf. Let me know if the issue still happens after it

**Comment by nochlab1** [comment]
Ok thanks will try new build and let you know

**Comment by nochlab1** [comment]
i dont have my computer now and trying on a different computer even the build that fails worked so will have to wait till i get my other computer back to confirm its fixed

**Comment by ehoogeveen-medweb** [comment]
I got the error again on my laptop the other day, it seems less frequent recently but the update didn't fix it. I'll see if I can get set up locally and experiment with working around it myself.

**Comment by nochlab1** [comment]
thanks hopefully you figure it out

**Comment by ehoogeveen-medweb** [comment]
I'm having a lot of trouble reproducing this with a local build. I think I'll switch back and see if it happens again or if some external change made this go away. If it does happen again, I wonder if there's something different about the version distributed via `pip` (which uses a wrapper executable and the python files stored in `%LocalAppdata%\Programs\Python\Python39\Lib\site-packages\yt_dlp`).

**Comment by kenorb** [comment]
```
$ yt-dlp -vci -R5 -f mp4,webm --write-description --write-info-json --all-subs --write-thumbnail --add-metadata https://www.youtube.com/c/DecimalZ/videos
...
[youtube:tab] UCpzhzlCa-QgORPIkddepgSg page 1: Downloading API JSON
[info] Writing playlist metadata as JSON to: Decimal Z - Videos [UCpzhzlCa-QgORPIkddepgSg].info.json
ERROR: Cannot write playlist metadata to JSON file Decimal Z - Videos [UCpzhzlCa-QgORPIkddepgSg].info.json
Traceback (most recent call last):
  File "/snap/yt-dlp/1/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 3591, in _write_info_json
    write_json_file(self.sanitize_info(ie_result, self.params.get('clean_infojson', True)), infofn)
  File "/snap/yt-dlp/1/lib/python3.8/site-packages/yt_dlp/utils.py", line 1842, in write_json_file
    tf = tempfile.NamedTemporaryFile(**compat_kwargs(args))
  File "/usr/lib/python3.8/tempfile.py", line 679, in NamedTemporaryFile
    (fd, name) = _mkstemp_inner(dir, prefix, suffix, flags, output_type)
  File "/usr/lib/python3.8/tempfile.py", line 389, in _mkstemp_inner
    fd = _os.open(file, flags, 0o600)
PermissionError: [Errno 13] Permission denied: 'Decimal Z - Videos [UCpzhzlCa-QgORPIkddepgSg].info.json.y1jfkxmi.tmp'
```

**Comment by ehoogeveen-medweb** [comment]
If it fails consistently then the retry logic from #2066 wouldn't help - this issue is about intermittent failures in `open`.

Having said that, #2066 only covers uses of `sanitize_open`; `write_json_file` doesn't have the retry logic. I think there are a few other paths that don't have any retry logic (e.g. downloading livechat).
