### ISSUE TITLE
--cookies-from-browser doesn't support the Snap version of Firefox

### ISSUE THREAD

**Issue by patalexandre** [yt-dlp/yt-dlp#5175]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.10.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Ubuntu is switching to bundle a Firefox version that is build as a Snap package. This results in the Firefox's cache being at a different location than an uncontainerized Firefox installation, and that does not look to be supported by the yt-dlp's `--cookies-from-browser` option.

yt-dlp expects the Firefox directory to be located at `~/.mozilla/firefox`, but with a snap install, it is located under `~/snap/firefox/common/.mozilla/firefox`.

Could it be possible to enhance yt-dlp by detecting a user's Firefox profile when using a Snap-packaged release? (Maybe it could be implemented as a new browser option i.e. `--cookies-from-browser firefox-snap`, to prevent conflicts with uncontainerized Firefox profiles.)

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU']
[debug] Home config "yt-dlp.conf": ['--cookies', './cookies.txt', '-f', '141', '-P', '$HOME/Téléchargements/ytdl']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.10.04 [4e0511f] (zip)
[debug] Python 3.10.7 (CPython 64bit) - Linux-5.19.0-76051900-generic-x86_64-with-glibc2.36 (glibc 2.36)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 5.1.1 (setts), ffprobe 5.1.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.11.0, brotli-1.0.9, certifi-2022.06.15, pyxattr-0.7.2, secretstorage-3.3.3, sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Loaded 1690 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.10.04, Current version: 2022.10.04
yt-dlp is up to date (2022.10.04)
```

**Comment by pukkandan** [comment]
See PINNED issues https://github.com/yt-dlp/yt-dlp/issues/2903
