### ISSUE TITLE
How does the exponential sleep work?

### ISSUE THREAD

**Issue by JediMaster25** [yt-dlp/yt-dlp#5179]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.10.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I've added `--retry-sleep exp=1:20` to the options, but I'm still getting skipped fragments.
```
[download] Got error: HTTP Error 429: Too Many Requests. Giving up after 10 retries
ERROR: fragment 1 not found, unable to continue
```
As I understand this should wait 2, 4, 8, 16... seconds until 2^20. Or what does it do?

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
Like I asked in discord, show verbose log! The answer to your question obviously will not help you.

But if you really want an answer anyway, it goes 1,2,4,8,16,20,20,20...

**Comment by JediMaster25** [comment]
And if I wanted to sleep for 2, 4, 8, 16, 32, 64 seconds would it be something like this?
```
--retries 6
--retry-sleep exp=2:
```

**Comment by pukkandan** [comment]
Yes, change the 20 to the upper limit. See the readme for detailed explanation
