### ISSUE TITLE
Get SubTitles URL

### ISSUE THREAD

**Issue by dardo82** [yt-dlp/yt-dlp#5184]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.10.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Can you tell me the option to get the subtitles URL like the `—get-url` for audio and video or add one if there isn't one?
A workaround is extracting it from the JSON with `awk` or `jq`, but it’s not robust or easy, so how should this be done?

```
#!/bin/zsh
# Play the last video watched on YouTube in MPV with subtitles.

L="${1-${${LANG%.*}%_*}}"; SIZE="${2-48}"; EXT="${3-vtt}"; FMT="${4-135+140}"			# Set variables.
ID=$(yt-dlp -v --get-id --playlist-items 1 --cookies-from-browser chrome :ythistory)		# Set the video's ID.
SUB=$(yt-dlp -j youtu.be/$ID | jq . | awk -F'"' -v RE="=$L&.*$EXT" '{if ($0~RE) print $4}')	# Set the subtitles' URL.

mpv --ytdl-format="$FMT" --sub-file="$SUB" --sub-font-size="$SIZE" "ytdl://$ID"			# Play the video.
```

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
--print %(subtitles.en.0.url)s

**Comment by flashdagger** [comment]
You could use the `requested_subtitles` field with some jq query.
Don't forget to specify which subtitles, formats and languages you'd like to extract.

Example:
```sh
> yt-dlp https://youtu.be/UTSfYDzpjqI --write-subs --sub-format json3 --sub-langs 'en-.*' --print '%(requested_subtitles)j' | jq '.[] | [.name, .url] | @tsv'
"English - CC1\thttps://www.youtube.com/api/timedtext?v=UTSfYDzpjqI&caps=asr&xoaf=5&hl=en&ip=0.0.0.0&ipbits=0&expire=1665297362&sparams=ip%2Cipbits%2Cexpire%2Cv%2Ccaps%2Cxoaf&signature=9921DED303A512EB4A7B9390AC0F050D9D0CBADE.53395A095DF6745BA2A0BD9791D54687731F8C3A&key=yt8&lang=en&name=CC1&fmt=json3"
"English - DTVCC1\thttps://www.youtube.com/api/timedtext?v=UTSfYDzpjqI&caps=asr&xoaf=5&hl=en&ip=0.0.0.0&ipbits=0&expire=1665297362&sparams=ip%2Cipbits%2Cexpire%2Cv%2Ccaps%2Cxoaf&signature=9921DED303A512EB4A7B9390AC0F050D9D0CBADE.53395A095DF6745BA2A0BD9791D54687731F8C3A&key=yt8&lang=en&name=DTVCC1&fmt=json3"
"English (United States)\thttps://www.youtube.com/api/timedtext?v=UTSfYDzpjqI&caps=asr&xoaf=5&hl=en&ip=0.0.0.0&ipbits=0&expire=1665297362&sparams=ip%2Cipbits%2Cexpire%2Cv%2Ccaps%2Cxoaf&signature=9921DED303A512EB4A7B9390AC0F050D9D0CBADE.53395A095DF6745BA2A0BD9791D54687731F8C3A&key=yt8&lang=en-US&fmt=json3"
```

**Comment by pukkandan** [comment]
> You could use the `requested_subtitles` field with some jq query. Don't forget to specify which subtitles, formats and languages you'd like to extract.
> 
> Example:
> 
> ```shell
> > yt-dlp https://youtu.be/UTSfYDzpjqI --write-subs --sub-format json3 --sub-langs 'en-.*' --print '%(requested_subtitles)j' | jq '.[] | [.name, .url] | @tsv'
> "English - CC1\thttps://www.youtube.com/api/timedtext?v=UTSfYDzpjqI&caps=asr&xoaf=5&hl=en&ip=0.0.0.0&ipbits=0&expire=1665297362&sparams=ip%2Cipbits%2Cexpire%2Cv%2Ccaps%2Cxoaf&signature=9921DED303A512EB4A7B9390AC0F050D9D0CBADE.53395A095DF6745BA2A0BD9791D54687731F8C3A&key=yt8&lang=en&name=CC1&fmt=json3"
> "English - DTVCC1\thttps://www.youtube.com/api/timedtext?v=UTSfYDzpjqI&caps=asr&xoaf=5&hl=en&ip=0.0.0.0&ipbits=0&expire=1665297362&sparams=ip%2Cipbits%2Cexpire%2Cv%2Ccaps%2Cxoaf&signature=9921DED303A512EB4A7B9390AC0F050D9D0CBADE.53395A095DF6745BA2A0BD9791D54687731F8C3A&key=yt8&lang=en&name=DTVCC1&fmt=json3"
> "English (United States)\thttps://www.youtube.com/api/timedtext?v=UTSfYDzpjqI&caps=asr&xoaf=5&hl=en&ip=0.0.0.0&ipbits=0&expire=1665297362&sparams=ip%2Cipbits%2Cexpire%2Cv%2Ccaps%2Cxoaf&signature=9921DED303A512EB4A7B9390AC0F050D9D0CBADE.53395A095DF6745BA2A0BD9791D54687731F8C3A&key=yt8&lang=en-US&fmt=json3"
> ```

jq isnt even needed

    --print "%(requested_subtitles.0.url)s"

OR, to get all URLs,

    --print "%(requested_subtitles.:.url)#l"

**Comment by flashdagger** [comment]
> jq isnt even needed
> 
> ```
> --print "%(requested_subtitles.0.url)s"
> ```
> 

Hmm. This doesn't work for me, since `requested_subtitles` itself is a JSON object and not an array.
But then you could your latter example and filter with `... | head -n 1`

**Comment by pukkandan** [comment]
My bad, u r right

**Comment by dirkf** [comment]
Isn't OP's real ("Y") problem with _mpv_'s ytdl hook which could (if it doesn't already ...) respond to appropriate combinations of _mpv_ subtitle options and `--ytdl-raw-options ...` by loading and/or displaying the desired subtitles. So https://github.com/mpv-player/mpv/issues ...

**Comment by dardo82** [comment]
Thanks for the interest everyboby.

I think that `yt-dlp` should provide
the URL for the subtitles alongside
the ones for audio and video in the
output of the `-g` option,why not?

**Comment by pukkandan** [comment]
Because `-g` is to print video URLs, not subtitles

**Comment by dardo82** [comment]
No, it's to --get-url: audio, video and subs one! 🤔
