### ISSUE TITLE
Date/time with strftime formatting no longer works

### ISSUE THREAD

**Issue by djasil** [yt-dlp/yt-dlp#5185]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.10.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

```
yt-dlp.exe -f 249 https://www.youtube.com/watch?v=RK27RX54EJU -o "%(duration>%H-%M-%S)s.ogg
```

The command above downloads the audio track as **00-03-10.ogg** on version **2022.09.01**. The version **2022.10.04** gives me the error **ERROR: [Errno 22] Invalid argument**.

It works fine using duration alone.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '-f', '249', 'https://www.youtube.com/watch?v=RK27RX54EJU', '-o', '%(duration>%H-%M-%S)s.ogg']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.10.04 [4e0511f] (win32_exe)
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 2022-09-05-git-2ed5925e26-full_build-www.gyan.dev (setts)
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1690 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.10.04, Current version: 2022.10.04
yt-dlp is up to date (2022.10.04)
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=RK27RX54EJU
[youtube] RK27RX54EJU: Downloading webpage
[youtube] RK27RX54EJU: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[info] RK27RX54EJU: Downloading 1 format(s): 249
ERROR: [Errno 22] Invalid argument
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1477, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1574, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1632, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2733, in process_video_result
  File "yt_dlp\YoutubeDL.py", line 2952, in process_info
  File "yt_dlp\YoutubeDL.py", line 1335, in prepare_filename
  File "yt_dlp\YoutubeDL.py", line 1306, in _prepare_filename
  File "yt_dlp\YoutubeDL.py", line 1297, in evaluate_outtmpl
  File "yt_dlp\YoutubeDL.py", line 1294, in prepare_outtmpl
  File "yt_dlp\YoutubeDL.py", line 1231, in create_key
  File "yt_dlp\YoutubeDL.py", line 1198, in get_value
  File "yt_dlp\utils.py", line 2581, in strftime_or_none
OSError: [Errno 22] Invalid argument
```

**Comment by pukkandan** [comment]
The issue seems to be a manifestation of https://github.com/python/cpython/issues/94414. I will push a workaround.

PS: `duration_string` is the recommended way to get duration as string. Your current code will give wrong results for duration > 24hrs
