### ISSUE TITLE
[youtube] force uploader_id to give id not nickname?

### ISSUE THREAD

**Issue by Gage-Irwin** [yt-dlp/yt-dlp#5192]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.10.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

When using the output option of uploader_id some channels get the channel id that starts with UC while some return channel nickname. 
For example when downloading any video from https://www.youtube.com/c/LinusTechTips uploader_id = LinusTechTips
While downloading any video from https://www.youtube.com/c/ShortCircuit uploader_id = UCdBK94H6oZT2Q7l0-b0xmMg
I want it to only give the channel id not nickname.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
you can use `channel_id` instead of `uploader_id`

**Comment by Gage-Irwin** [comment]
> you can use `channel_id` instead of `uploader_id`

Thank you.  Just looked at my old batch script and I seem to have switched from using channel_id to uploader_id for some reason.
