### ISSUE TITLE
Replacement for the removed -A (--auto-number) option

### ISSUE THREAD

**Issue by joelthelion** [yt-dlp/yt-dlp#5194]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.10.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Prepending an index is a very common requirement when downloading multiple files, such as a playlist, in order to retain order when playing it.

In the past, there used to be a shorthand option for doing this quickly, "-A" or auto-number. It was deprecated and later removed for reasons I have not been able to identify.

As mentioned in the Readme, the current replacement for this is "-o "%(autonumber)s-%(id)s.%(ext)s". It works, but it's very hard to remember and long to type.

So I would like to request a simpler flag for people who don't care too much about naming but just want to retain order.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.09.01 [5d7c7d656]
[debug] Lazy loading extractors is disabled
[debug] Python 3.10.7 (CPython 64bit) - Linux-5.19.12-200.fc36.x86_64-x86_64-with-glibc2.35 (glibc 2.35)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 5.0.1 (setts), ffprobe 5.0.1
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2021.10.08, mutagen-1.45.1, secretstorage-3.3.1, sqlite3-2.6.0, websockets-10.1
[debug] Proxy map: {}
[debug] Loaded 1670 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.10.04, Current version: 2022.09.01
[debug] Downloading _update_spec from https://github.com/yt-dlp/yt-dlp/releases/download/2022.10.04/_update_spec
ERROR: You installed yt-dlp with a package manager or setup.py; Use that to update
```

**Comment by pukkandan** [comment]
You can add a custom alias to your config files. See `--alias`
Eg:

    --alias -A "-o=%(autonumber)s-%(id)s.%(ext)s"

**Comment by joelthelion** [comment]
@pukkandan Thanks, that's useful.

For the record, why the wontfix? This would be widely useful, fairly easy to implement, and probably not a big deal to maintain. I don't understand why the option was deprecated in the first place.

**Comment by pukkandan** [comment]
yt-dlp already has a lot of options. I will not add an option for something that can already be done with `-o`. `-A` and friends were removed from yt-dlp since they were deprecated (but not removed) even in youtube-dl some 8 years ago.
