### ISSUE TITLE
Different error code for update failure

### ISSUE THREAD

**Issue by JediMaster25** [yt-dlp/yt-dlp#5198]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.10.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I'm downloading many files in parallel using the following configuration
```
ytvp () {
        TIMESTAMP=$( date +%y%m%d%H%M%S )
        NAME=$( sanitize_linux_filename "$1" )
        LOG_NAME="yt-dlp_${TIMESTAMP}_${NAME}.log"
        yt-dlp --format "(bv+(wa[abr>=64]/ba))/b" --format-sort res:720,tbr~2000 --continue --no-overwrites --no-post-overwrites --verbose --update --restrict-filenames --retry-sleep exp=2:64 --download-archive "downloaded.txt" --output "%(upload_date>%Y-%m-%d|)s%(upload_date& |)s%(title)s-%(id)s.%(ext)s" "$1" >> "/tmp/$LOG_NAME" 2>&1 &
}
```

I'm getting the process exit with status 1 meaning they have failed. But they have actually managed to download the video without problem. But they haven't been able to get the program version form the github API so they've given an error.

I don't want to see `exit 1` when a process finishes unless it has actually failed to download the video.

I don't want to remove `--update` from the configuration since it is required to open an issue.

What can I do to fix this?

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
Nothing. An error code will be returned when there's any error - whether it be for update, download or anything else. That is exactly how error codes are supposed to work

I could change the updater error code from 1 to some other non-zero value. Would that help you?

> I don't want to remove --update from the configuration since it is required to open an issue.

You can open issue without it, just make sure your it is actually up to date.

PS: if you cannot re-run the command with `-vU` and reproduce the problem, it's likely not a yt-dlp issue and you probably shouldn't be reporting it 🤷

**Comment by JediMaster25** [comment]
> I could change the updater error code from 1 to some other non-zero value. Would that help you
That would help.

**Comment by gamer191** [comment]
> I could change the updater error code from 1 to some other non-zero value. Would that help you?

Then what would be returned if both the updater and the download fail?

**Comment by pukkandan** [comment]
A common practice is to bitwise or them together. But yt-dlp does not do that for the other error codes.  So I'll just give priority to download error for now
