### ISSUE TITLE
newly broken- Youtube watch later playlist

### ISSUE THREAD

**Issue by fsiler** [yt-dlp/yt-dlp#5203]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.10.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United States

### Provide a description that is worded well enough to be understood

I'd been using `yt-dlp https://www.youtube.com/playlist\?list\=WL` for many months, perhaps years, as part of a script, and it broke today.  I did have a Google password reset, so just to be sure I re-downloaded the cookie jar from the browser.  `yt-dlp` is still able to download from other private playlists I have, so I'm not sure what's going on here exactly.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
% yt-dlp https://www.youtube.com/playlist\?list\=WL -vU      
[debug] Command-line config: ['https://www.youtube.com/playlist?list=WL', '-vU']
[debug] User config "/Users/fms/.config/yt-dlp/config": ['-f', 'bestvideo[height<=?1080][height>?720][ext=mp4]+bestaudio/bestvideo[ext=mp4]+bestaudio/best[ext=mp4]/best', '-o', '~/Movies/%(title)s %(id)s %(uploader)s.ytd.%(ext)s', '--cookies', '~/.config/youtube-dl/ytcookies.txt', '--default-search', 'ytsearch', '--mark-watched', '--sub-lang', 'en', '--write-auto-sub', '--write-sub', '--embed-subs', '--add-metadata', '--xattrs']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.10.04 [4e0511f] (pip) API
[debug] Python 3.9.14 (CPython 64bit) - macOS-12.6-x86_64-i386-64bit 
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 5.1.2 (setts), ffprobe 5.1.2, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1690 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.10.04, Current version: 2022.10.04
yt-dlp is up to date (2022.10.04)
[debug] [youtube:tab] Extracting URL: https://www.youtube.com/playlist?list=WL
[youtube:tab] WL: Downloading webpage
WARNING: [youtube:tab] YouTube said: The playlist does not exist.
[debug] [youtube:tab] Final URL: https://www.youtube.com/playlist?list=WL
ERROR: [youtube:tab] WL: YouTube said: The playlist does not exist.
  File "/Users/fms/build/brew/Cellar/yt-dlp/2022.10.4/libexec/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 672, in extract
    ie_result = self._real_extract(url)
  File "/Users/fms/build/brew/Cellar/yt-dlp/2022.10.4/libexec/lib/python3.9/site-packages/yt_dlp/extractor/youtube.py", line 4223, in wrapper
    info_dict = func(self, url, smuggled_data)
  File "/Users/fms/build/brew/Cellar/yt-dlp/2022.10.4/libexec/lib/python3.9/site-packages/yt_dlp/extractor/youtube.py", line 5807, in _real_extract
    self._extract_and_report_alerts(data, only_once=True)
  File "/Users/fms/build/brew/Cellar/yt-dlp/2022.10.4/libexec/lib/python3.9/site-packages/yt_dlp/extractor/youtube.py", line 711, in _extract_and_report_alerts
    return self._report_alerts(self._extract_alerts(data), *args, **kwargs)
  File "/Users/fms/build/brew/Cellar/yt-dlp/2022.10.4/libexec/lib/python3.9/site-packages/yt_dlp/extractor/youtube.py", line 708, in _report_alerts
    raise ExtractorError('YouTube said: %s' % errors[-1][1], expected=expected)
```

**Comment by pukkandan** [comment]
It works for me. Your log suggests that the cookie file is not logged in. Could you try directly with `--cookies-from-browser`?

**Comment by fsiler** [comment]
Sorry, I wasn't familiar with that option- but you are correct, it does work when I use `--cookies-from-browser`, closing.  Thanks!

**Comment by gamer191** [comment]
quick tip: if you put the url in quotation marks then you don't have to worry about cancelling special characters
