### ISSUE TITLE
Handling 403's by skipping the download?

### ISSUE THREAD

**Issue by trapexit** [yt-dlp/yt-dlp#5204]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.10.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Are there any settings which would cause yt-dlp to give up on a particular request (but not the whole execution) if it receives a HTTP 403 error? I'm running into a situation where a video will return a 403 and instead of skipping the video it tries every fragment N retry times. Preferably this particular error could be treated differently so it doesn't sit there for perhaps hours trying something that will never work. None of the settings I've tried seem to keep the fragment retry for random errors but give up if a 403.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
--abort-on-unavailable-fragment

**Comment by trapexit** [comment]
Sorry, I totally missed that option. Thanks.
