### ISSUE TITLE
PhantomJS in Termux

### ISSUE THREAD

**Issue by nel997** [yt-dlp/yt-dlp#5206]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.10.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Good day. I noticed that due to throttling, PhantomJS is needed now.
I downloaded it, decompressed it and put the binary somewhere in my PATH, as I saw in another issue, but the message still persists. 

I am in the most recent version.

`~ $ yd -U
Latest version: 2022.10.04, Current version: 2022.10.04
yt-dlp is up to date (2022.10.04)`

When I try to "run" it from terminal, I get the following message, but I don't know whether that is because of some Android thing or just because the program isn't supposed to be run that way, but at least it shows it is on PATH.

`~ $ phantomjs
bash: /storage/emulated/0/ydl/phantomjs: Permission denied`

Is there anything I'm doing wrong? Also, is there any way to point to PhantomJS from the config as with ffmpeg? I saw nothing on the guide.

Thanks.

Note on verbose: ydl is just an alias to a config file. Other than the throttling, it works fine, so maybe it was not needed.

`alias yd="yt-dlp --config-location /storage/emulated/0/ydl/base.txt"`

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
~ $ yd -vU https://youtu.be/SSCDAjUWKnU
[debug] Command-line config: ['--config-location', '/storage/emulated/0/ydl/base.txt', '-vU', 'https://youtu.be/SSCDAjUWKnU']
[debug] | Config "/storage/emulated/0/ydl/base.txt": ['-o', '/storage/emulated/0/ydl/Videos/%(title)s-%(extractor)s.%(ext)s', '-f', 'bestvideo[height<=720][vcodec!=vp9][fps<=?30]+bestaudio', '--downloader', 'aria2c', '--sponsorblock-remove', 'sponsor,selfpromo']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.10.04 [4e0511f] (pip) API
[debug] Python 3.10.7 (CPython 64bit) - Linux-4.14.199-23784803-abX200XXU1AVC1-aarch64-with-libc (libc)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 5.1 (setts), ffprobe 5.1
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1690 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.10.04, Current version: 2022.10.04
yt-dlp is up to date (2022.10.04)
[debug] [youtube] Extracting URL: https://youtu.be/SSCDAjUWKnU
[youtube] SSCDAjUWKnU: Downloading webpage
[youtube] SSCDAjUWKnU: Downloading android player API JSON
[debug] Loading youtube-nsig.7a062b77 from cache
WARNING: [youtube] SSCDAjUWKnU: nsig extraction failed: You may experience throttling for some formats
         Install PhantomJS to workaround the issue. Please download it from https://phantomjs.org/download.html
         n = m2OmM8PptRuWpMK5 ; player = https://www.youtube.com/s/player/7a062b77/player_ias.vflset/en_US/base.js
[debug] [youtube] No terminating paren ] in: [/[),\\],,/,-179969746,230642284,105421641,3077..."enhanced_except_y5YBtOn-_w8_"+a}return b.join(""); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[SponsorBlock] Fetching SponsorBlock segments
[debug] SponsorBlock query: https://sponsor.ajay.app/api/skipSegments/8202?service=YouTube&categories=%5B%22selfpromo%22%2C+%22sponsor%22%5D&actionTypes=%5B%22skip%22%2C+%22poi%22%5D
[SponsorBlock] No segments were found in the SponsorBlock database
[info] SSCDAjUWKnU: Downloading 1 format(s): 136+251
```

**Comment by xtkoba** [comment]
You can use <a href="https://github.com/termux/termux-packages/tree/master/x11-packages/phantomjs">the `phantomjs` package provided by Termux</a>:

```bash
pkg install x11-repo # if not yet subscribed to
pkg install phantomjs
```

**Comment by xtkoba** [comment]
P.S. Note that you cannot execute binaries placed in an SD card that is not set up as an internal storage. Also I wonder where you obtained that `phantomjs` binary.

**Comment by nel997** [comment]
Thanks. I got the binary from the link that appears with the error message, since it had a direct download I didn't check my package manager. Also it was running from the main memory, not SD.
