### ISSUE TITLE
Make pandoc optional rather than mandatory

### ISSUE THREAD

**Issue by rubyFeedback** [yt-dlp/yt-dlp#5207]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.10.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Right now I can not install yt-dlp - it fails with the below output:

    git shortlog -s -e -n | awk '!(out[$NF]++) { $1="";sub(/^[ \t]+/,""); print}' > .mailmap git shortlog -s -n | cut -f2 | sort > AUTHORS     
    /bin/sh: line 1: pandoc: command not found /bin/sh: line 1: [: =: unary operator expected pandoc -f markdown -t plain README.md -o README.txt make: pandoc: No such file or directory make: *** [Makefile:111: README.txt] Error 127 make install /bin/sh: line 1:     
    pandoc: command not found /bin/sh: line 1: [: =: unary operator expected /usr/bin/env python3 devscripts/prepare_manpage.py     
    yt-dlp.1.temp.md pandoc -s -f markdown -t man yt-dlp.1.temp.md -o yt-dlp.1 make: pandoc: No such file or directory make: ***     
    [Makefile:115: yt-dlp.1] Error 127

I don't have pandoc installed which is the reason the installation fails. It is a haskell program I think.

I think this should be optional. That is, first check if pandoc is installed or not, and if not, skip this requirement.

If I understand things correctly then pandoc only generates documentation. I already never read manpages or
local documentation; if I have a problem I google and try to find the solution so local docs are useless for me.
For others they may be useful, that is fine, but then pandoc shouid be optional rather than mandatory (or fail
like in my case).

I think python tools in general should avoid depending on other languages such as haskell here, so I consider
this more of a bug - it's less of a bug, though, and more a design decision to be decided by whoever maintains
the project here of course.

PS: The template really is way too verbose.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
See first field above.
```

**Comment by Lesmiscore** [comment]
Unless you're trying to build from source, GHC isn't required
https://github.com/jgm/pandoc/releases/tag/2.19.2

**Comment by pukkandan** [comment]
The point of "make install" is to create all supporting files and copy them to the right places. If you don't want them, just use `make yt-dlp` instead to just create the binary

**Comment by pukkandan** [comment]
> I think youtube-dl did not have that requirement, so this is weird IMO.

It's the same for ytdl
