### ISSUE TITLE
Ignore/Skip premium videos

### ISSUE THREAD

**Issue by phyzical** [yt-dlp/yt-dlp#521]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running yt-dlp version **2021.07.07**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description

Just wondering if we could add a feature to ignore/skip premium videos or instead have these be allowed errors when providing the  `--ignore-errors` flag

example youtube video id `Q7bJ_HIf6XI` 

at the moment these result in making yt-dlp return an error exit code so i am forced to manually add them to the cache file to "skip them"

**Comment by Ashish0804** [comment]
> at the moment these result in making yt-dlp return an error exit code so i am forced to manually add them to the cache file to "skip them"

I don't see any issue here. If you are using `--ignore-errors` then ytdlp will still download the next item.

**Comment by phyzical** [comment]
maybe this is more inline with my specific use case, but i loop over a list of channels in a bash script and use a trap on error codes as i do other processing aswell, when there is errors on a video i.e premium my trap is hit.

i guess its more of a should a premium video be regarded as an exit code error?

**Comment by colethedj** [comment]
afaik, currently there is no way of distinguishing, since we just extract the error message YouTube gives and throw an ExtractorError.

This might be something in implementing https://github.com/yt-dlp/yt-dlp/issues/457 could possibly allow.

**Comment by phyzical** [comment]
@colethedj ah i guess i didn't look hard enough.

i do agree if something like #457 was to be implemented then my request would be something along the lines of `--ignore-error-category "premium"` 

i will close this as its basically a dupe at this point
