### ISSUE TITLE
LBRY/Odysee timeout

### ISSUE THREAD

**Issue by csehszlovakze** [yt-dlp/yt-dlp#5214]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.10.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Hungary

### Provide a description that is worded well enough to be understood

video URL: https://odysee.com/@RobBraxmanTech:6/ipv6-2.mp4:b

It loads and plays perfectly fine in web browser (Vivaldi 5.5) with or without logging in, however, I can't download nor stream (mpv) the video via `yt-dlp_linux` (and I can't use normal yt-dlp due to system incompatibilities around python). The log includes -F because I originally wanted to find a lower res format in case only the video format is buggy (which happens with youtube often).

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['--rm-cache', '-vUF', 'https://odysee.com/@RobBraxmanTech:6/ipv6-2.mp4:b']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.10.04 [4e0511f] (linux_exe)
[debug] Python 3.10.7 (CPython 64bit) - Linux-4.15.0-144-generic-x86_64-with-glibc2.27 (glibc 2.27)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 3.4.11, ffprobe 3.4.11, phantomjs 2.1.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.45.1, secretstorage-3.3.3, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1690 extractors
Removing cache dir /home/csehszlovakze/.cache/yt-dlp ..
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.10.04, Current version: 2022.10.04
yt-dlp is up to date (2022.10.04)
[debug] [lbry] Extracting URL: https://odysee.com/@RobBraxmanTech:6/ipv6-2.mp4:b
[lbry] @RobBraxmanTech#6/ipv6-2.mp4#b: Downloading stream JSON metadata
ERROR: [lbry] @RobBraxmanTech:6/ipv6-2.mp4:b: Unable to download JSON metadata: The read operation timed out (caused by TimeoutError('The read operation timed out')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp/extractor/common.py", line 672, in extract
  File "yt_dlp/extractor/lbry.py", line 199, in _real_extract
  File "yt_dlp/extractor/lbry.py", line 42, in _resolve_url
  File "yt_dlp/extractor/lbry.py", line 27, in _call_api_proxy
  File "yt_dlp/extractor/common.py", line 1032, in download_content
  File "yt_dlp/extractor/common.py", line 996, in download_handle
  File "yt_dlp/extractor/common.py", line 866, in _download_webpage_handle
  File "yt_dlp/extractor/common.py", line 823, in _request_webpage

  File "yt_dlp/extractor/common.py", line 805, in _request_webpage
  File "yt_dlp/YoutubeDL.py", line 3682, in urlopen
  File "urllib/request.py", line 519, in open
  File "urllib/request.py", line 536, in _open
  File "urllib/request.py", line 496, in _call_chain
  File "yt_dlp/utils.py", line 1498, in https_open
  File "urllib/request.py", line 1352, in do_open
  File "http/client.py", line 1374, in getresponse
  File "http/client.py", line 318, in begin
  File "http/client.py", line 279, in _read_status
  File "socket.py", line 705, in readinto
  File "ssl.py", line 1274, in recv_into
  File "ssl.py", line 1130, in read
TimeoutError: The read operation timed out
```

**Comment by csehszlovakze** [comment]
p.s. I left the account credential box unchecked because it's not marked as mandatory nor applicable to the issue, and of course I don't want to share my account.

**Comment by pukkandan** [comment]
Can't repro. Double check it isnt a network issue from your side

```
❯ yt-dlp https://odysee.com/@RobBraxmanTech:6/ipv6-2.mp4:b
[lbry] @RobBraxmanTech#6/ipv6-2.mp4#b: Downloading stream JSON metadata
[lbry] bf961a53e2003d383e177ca365b925b0982b5986: Downloading streaming url JSON metadata
[lbry] @RobBraxmanTech#6/ipv6-2.mp4#b: Downloading streaming redirect url info
[lbry] @RobBraxmanTech#6/ipv6-2.mp4#b: Downloading m3u8 information
[info] bf961a53e2003d383e177ca365b925b0982b5986: Downloading 1 format(s): hls-4026
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 176
[download] Destination: How We Can Make IPv6 Safe for Privacy [bf961a53e2003d383e177ca365b925b0982b5986].mp4
[download]   0.1% of ~ 235.09MiB at  121.17KiB/s ETA 33:05 (frag 0/176)
ERROR: Interrupted by user
```

**Comment by csehszlovakze** [comment]
It works now, seems to have been a temporary issue on their side (since it always worked from web browser).
