### ISSUE TITLE
Scratch

### ISSUE THREAD

**Issue by Jadoo4QFan** [yt-dlp/yt-dlp#5226]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.10.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

USA

### Example URLs

https://scratch.mit.edu/projects/715234663/ (single project)
https://scratch.mit.edu/projects/733096124/ (Same as above)
https://scratch.mit.edu/search/projects?q=Jadoo (Search Playlist)
https://scratch.mit.edu/studios/25006615/ (Studio Playlist)
https://scratch.mit.edu/users/TheGreatUnknown/ (User Playlist)
https://scratch.mit.edu/projects/441947766/remixes (Remixes Playlist)
https://scratch.mit.edu/about/ (About videos)

### Provide a description that is worded well enough to be understood

Scratch is a site to learn code, and is a programming language for beginners. I found out something, when I put my debugger on a computer while loading a scratch project, each asset is downloaded separately, including sound effects. Please add support for scratch project audio downloading, including its metadata and comments. Also please support playlist extraction. Did some research in the comments side and found this json, just like normal comment extractors as YT-DLP seems to have a lack of them for other sites other than YouTube. https://api.scratch.mit.edu/users/-Rex-/projects/441947766/comments?offset=0&limit=20 , and found out that replies are like this
https://api.scratch.mit.edu/studios/25006615/comments/104298479/replies?offset=0&limit=25 , however user comments are alienated from project and studio playlists: https://scratch.mit.edu/site-api/comments/user/TheGreatUnknown/?page=1

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
/projects/715234663/
Traceback (most recent call last):
  File "/var/mobile/Containers/Data/Application
/30BFEB40-94F0-43F6-B73A-054FFF42DD1B/Library/l
ib/python3.9/site-packages/yt_dlp/YoutubeDL.py"
, line 1477, in wrapper
    return func(self, *args, **kwargs)
  File "/var/mobile/Containers/Data/Application
/30BFEB40-94F0-43F6-B73A-054FFF42DD1B/Library/l
ib/python3.9/site-packages/yt_dlp/YoutubeDL.py"
, line 1553, in __extract_info
    ie_result = ie.extract(url)
  File "/var/mobile/Containers/Data/Application
/30BFEB40-94F0-43F6-B73A-054FFF42DD1B/Library/l
ib/python3.9/site-packages/yt_dlp/extractor/com
mon.py", line 672, in extract
    ie_result = self._real_extract(url)
  File "/var/mobile/Containers/Data/Application
/30BFEB40-94F0-43F6-B73A-054FFF42DD1B/Library/l
ib/python3.9/site-packages/yt_dlp/extractor/gen
eric.py", line 3062, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL:
 https://scratch.mit.edu/projects/715234663/
[Documents]$ 
```

**Comment by denaunistic** [comment]
please for god sake stop

**Comment by flashdagger** [comment]
@Jadoo4QFan I appreciate the effort and the proper use of the issue template.
@denaunistic https://duckduckgo.com/?q=howto+politely+reject+a+feature+request

**Comment by gamer191** [comment]
Please add a proper verbose log

**Comment by Jadoo4QFan** [comment]
[Documents]$ yt-dlp https://scratch.mit.edu/pro
jects/715234663/ -vU 
[debug] Command-line config: ['https://scratch.
mit.edu/projects/715234663/', '-vU']
[debug] Encodings: locale UTF-8, fs utf-8, pref
 UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.10.04 [4e0511f] (pi
p) API
[debug] Python 3.9.10+ (CPython 64bit) - macOS-
16.0-iPhone14,5-arm-64bit 
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg n5.0.1-4-ga5ebb3d2
5e (setts), ffprobe n5.0.1-4-ga5ebb3d25e, phant
omjs present, rtmpdump present
[debug] Optional libraries: Cryptodome-3.15.0, 
certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6
.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1690 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.10.04, Current version: 2022.10.04
yt-dlp is up to date (2022.10.04)
[debug] [generic] Extracting URL: https://scratch.mit.edu/projects/715234663/
[generic] 715234663: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] 715234663: Extracting information
[debug] Looking for Brightcove embeds
[debug] Looking for embeds
ERROR: Unsupported URL: https://scratch.mit.edu/projects/715234663/
Traceback (most recent call last):
  File "/var/mobile/Containers/Data/Application/30BFEB40-94F0-43F6-B73A-054FFF42DD1B/Library/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1477, in wrapper
    return func(self, *args, **kwargs)
  File "/var/mobile/Containers/Data/Application/30BFEB40-94F0-43F6-B73A-054FFF42DD1B/Library/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1553, in __extract_info
    ie_result = ie.extract(url)
  File "/var/mobile/Containers/Data/Application/30BFEB40-94F0-43F6-B73A-054FFF42DD1B/Library/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 672, in extract
    ie_result = self._real_extract(url)
  File "/var/mobile/Containers/Data/Application/30BFEB40-94F0-43F6-B73A-054FFF42DD1B/Library/lib/python3.9/site-packages/yt_dlp/extractor/generic.py", line 3062, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://scratch.mit.edu/projects/715234663/

**Comment by Jadoo4QFan** [comment]
> Please add a proper verbose log if you would like this site support request to be considered

`

[Documents]$ yt-dlp https://scratch.mit.edu/pro
jects/715234663/ -vU 
[debug] Command-line config: ['https://scratch.
mit.edu/projects/715234663/', '-vU']
[debug] Encodings: locale UTF-8, fs utf-8, pref
 UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.10.04 [4e0511f] (pi
p) API
[debug] Python 3.9.10+ (CPython 64bit) - macOS-
16.0-iPhone14,5-arm-64bit 
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg n5.0.1-4-ga5ebb3d2
5e (setts), ffprobe n5.0.1-4-ga5ebb3d25e, phant
omjs present, rtmpdump present
[debug] Optional libraries: Cryptodome-3.15.0, 
certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6
.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1690 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.10.04, Current version: 2022.10.04
yt-dlp is up to date (2022.10.04)
[debug] [generic] Extracting URL: https://scratch.mit.edu/projects/715234663/
[generic] 715234663: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] 715234663: Extracting information
[debug] Looking for Brightcove embeds
[debug] Looking for embeds
ERROR: Unsupported URL: https://scratch.mit.edu/projects/715234663/
Traceback (most recent call last):
  File "/var/mobile/Containers/Data/Application/30BFEB40-94F0-43F6-B73A-054FFF42DD1B/Library/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1477, in wrapper
    return func(self, *args, **kwargs)
  File "/var/mobile/Containers/Data/Application/30BFEB40-94F0-43F6-B73A-054FFF42DD1B/Library/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1553, in __extract_info
    ie_result = ie.extract(url)
  File "/var/mobile/Containers/Data/Application/30BFEB40-94F0-43F6-B73A-054FFF42DD1B/Library/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 672, in extract
    ie_result = self._real_extract(url)
  File "/var/mobile/Containers/Data/Application/30BFEB40-94F0-43F6-B73A-054FFF42DD1B/Library/lib/python3.9/site-packages/yt_dlp/extractor/generic.py", line 3062, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://scratch.mit.edu/projects/715234663/

`
I did. Sorry for the terminal not fully copying the first time.

**Comment by coletdjnz** [comment]
Out of scope
