### ISSUE TITLE
[NSFW] BoyFriendTV doesn't work with videos that require an account

### ISSUE THREAD

**Issue by lightninghydra24** [yt-dlp/yt-dlp#5228]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.10.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Worldwide

### Provide a description that is worded well enough to be understood

Downloading public videos on BoyFriend.TV such as https://www.boyfriendtv.com/videos/832593/cody-smith/ works fine; but ones requiring a (free) login to view e.g. https://www.boyfriendtv.com/videos/831026/4some-jaxton-wheeler-cody-smith-max-wilde-and-pierce-paris/ aren't downloadable even with cookies

Thanks! :)

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
$ yt-dlp -vU https://www.boyfriendtv.com/videos/831026/4some-jaxton-wheeler-cody-smith-max-wilde-and-pierce-paris/
[debug] Command-line config: ['-vU', 'https://www.boyfriendtv.com/videos/831026/4some-jaxton-wheeler-cody-smith-max-wilde-and-pierce-paris/']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.07.18 [135f05e]
[debug] Python 3.10.5 (CPython 64bit) - macOS-12.6-arm64-arm-64bit 
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 5.0.1 (setts), ffprobe 5.0.1
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.10.04, Current version: 2022.07.18
[debug] Downloading _update_spec from https://github.com/yt-dlp/yt-dlp/releases/download/2022.10.04/_update_spec
ERROR: It looks like you installed yt-dlp with a package manager, pip or setup.py; Use that to update
[debug] [generic] Extracting URL: https://www.boyfriendtv.com/videos/831026/4some-jaxton-wheeler-cody-smith-max-wilde-and-pierce-paris/
[generic] 4some-jaxton-wheeler-cody-smith-max-wilde-and-pierce-paris: Downloading webpage
WARNING: [generic] Falling back on generic information extractor.
[generic] 4some-jaxton-wheeler-cody-smith-max-wilde-and-pierce-paris: Extracting information
[debug] Looking for video embeds
ERROR: Unsupported URL: https://www.boyfriendtv.com/videos/831026/4some-jaxton-wheeler-cody-smith-max-wilde-and-pierce-paris/
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/yt-dlp/2022.7.18/libexec/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1431, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/homebrew/Cellar/yt-dlp/2022.7.18/libexec/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1506, in __extract_info
    ie_result = ie.extract(url)
  File "/opt/homebrew/Cellar/yt-dlp/2022.7.18/libexec/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 644, in extract
    ie_result = self._real_extract(url)
  File "/opt/homebrew/Cellar/yt-dlp/2022.7.18/libexec/lib/python3.10/site-packages/yt_dlp/extractor/generic.py", line 4108, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.boyfriendtv.com/videos/831026/4some-jaxton-wheeler-cody-smith-max-wilde-and-pierce-paris
```

**Comment by pukkandan** [comment]
There is no cookies passed in the given log

**Comment by lightninghydra24** [comment]
Shit, my bad. I ran the -vU in a different terminal when compiling this which was my laptop and not my server. Sorry about that!

Fixing the formatting from [Get cookies.txt](https://chrome.google.com/webstore/detail/get-cookiestxt/bgaddhkoddajcdgocldbbfleckgcbcid) (spaces to tabs?) seems to have it work now. 😳 

Sorry for the noise, not sure what was up with me last night.

Thanks for all your hard work!
