### ISSUE TITLE
Wanted to know about Timeout and Rate Limit

### ISSUE THREAD

**Issue by WINOFFRG** [yt-dlp/yt-dlp#5234]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.10.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Hi!

I am running the command ` yt-dlp.exe --dump-single-json --skip-download "https://www.youtube.com/c/ATNNewsLive/videos?view=2&sort=dd&live_view=501&shelf_id=0"`

What I am trying to do is to get top live videos of that channel. And if there are more then just break it once 5 videos are collected. What I have observed is that, In case there are no videos it keeps on looking for it and never returns. How can I handle this case?

1. One way could be add timeout if it takes more than 10 seconds, Then return the currently collected results. How can I do this?
2. Break the process if threshold eg: 5 Limit has reached and return the results.
3. I will be running this command every 30 mins, Is there any Rate Limiting implemented from YT's side, Since I am scraping Channel Live Video's Title and Desc.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
NA
```

**Comment by october262** [comment]
> 

try with yt-dlp "https://www.youtube.com/c/ATNNewsLive/videos?view=2&sort=dd&live_view=501&shelf_id=0" --playlist-end 5
it will only download the 5 videos.

**Comment by WINOFFRG** [comment]
Yes I tried that flag as well, Forgot to mention that it doesnt scrape live videos then but all the upcoming VOD.

**Comment by october262** [comment]
> scrape live videos

how about limit the number of videos processed ?? - https://www.reddit.com/r/youtubedl/comments/p9jqvv/limit_number_of_videos_processed/

**Comment by october262** [comment]
> Yes I tried that flag as well, Forgot to mention that it doesnt scrape live videos then but all the upcoming VOD.

how about limit the number of videos processed ?? - https://www.reddit.com/r/youtubedl/comments/p9jqvv/limit_number_of_videos_processed/

**Comment by pukkandan** [comment]
I don't fully understand your question.

> What I have observed is that, In case there are no videos it keeps on looking for it and never returns.

Can you elaborate on this part, preferably showing verbose log of it
