### ISSUE TITLE
Use different template if name too long

### ISSUE THREAD

**Issue by JediMaster25** [yt-dlp/yt-dlp#5239]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.10.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

In the following command I want to use the template `%(id)s.%(ext)s` if the name is too long. But I think I need a specific error code to do that, to check the error and call yt-dlp again with a different template.
```
ytv() {
  TIMESTAMP=$( date +%y%m%d%H%M%S )
  NAME=$( sanitize_linux_filename "$1" )
  LOG_NAME="yt-dlp_${TIMESTAMP}_${NAME}.log"
  yt-dlp \
    --format "(bv+(wa[abr>=64]/ba))/b" \
    --format-sort res:720,tbr~2000 \
    --continue \
    --no-overwrites \
    --no-post-overwrites \
    --verbose \
    --no-playlist \
    --restrict-filenames \
    --retry-sleep fragment:exp=2:64 \
    --download-archive "~/Documents/Text/downloaded.txt" \
    --output "%(upload_date>%Y-%m-%d|)s%(upload_date& |)s%(title)s-%(id)s.%(ext)s" \
    "$1" \
    >> "/tmp/$LOG_NAME" 2>&1 &
}
```

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
Not possible. See the workarounds given in pinned issue

**Comment by JediMaster25** [comment]
https://github.com/yt-dlp/yt-dlp/issues/1136#issuecomment-932077195
