### ISSUE TITLE
How to distinguish between video and audio downloads in stdout?

### ISSUE THREAD

**Issue by m4heshd** [yt-dlp/yt-dlp#5244]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.10.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I am parsing yt-dlp output through another application at the moment and I need to be able to tell the difference between a video download and an audio download, to be displayed to the user. Everything else is all good and dandy so far.

Only thing separating these download outputs I found so far is the `faudio` portion of the filename. I'm not sure that's consistent enough to be regexed and parsed.

Is there any other way to format the output? Like having `[download:video]` and `[download:audio]` or something?

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['--format', 'worstvideo[height=720][fps=30][ext=mp4]+bestaudio', '--output', 'E:\\Downloads\\video_file.%(ex
t)s', '--ffmpeg-location', '.\\bin', '--no-mtime', '--output-na-placeholder', '', '--add-metadata', '--no-cache-dir', '--ignore-config', '--no-check-certificate', '-vU', 'https://videosite.net/MjAxOQ/Mw/M_jc/MTAw-NzA0_/SE-xT_/MQ/master.m3u8?hdnea=exp=1665737395~acl=/MjAxOQ/Mw/M_jc/MTAw-NzA0_/SE-xT_/MQ/*~id=123456']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8 
[debug] yt-dlp version 2022.10.04 [4e0511f] (win32_exe)
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.22621-SP0  
[debug] Checking exe version: ".\bin\ffmpeg" -bsfs
[debug] Checking exe version: ".\bin\ffprobe" -bsfs 
[debug] exe versions: ffmpeg 4.4.1-full_build-www.gyan.dev (setts), ffprobe 4.4.1-full_build-www.gyan.dev 
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1690 extractors 
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.10.04, Current version: 2022.10.04 
yt-dlp is up to date (2022.10.04)
[debug] [generic] Extracting URL: https://videosite.net/MjAxOQ/Mw/M_jc/MTAw-NzA0_/SE-xT_/MQ/master.m3u8?hdnea=exp=1665737395~acl=/MjAxOQ/Mw/M_jc/MTAw-NzA0_/SE-xT_/MQ/*~id=123456
[generic] *~id=123456: Downloading webpage
[debug] Identified a direct video link 
[generic] *~id=123456: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id 
[info] *~id=123456: Downloading 1 format(s): 1680+audio-64000-default
[debug] Invoking hlsnative downloader on "https://videosite.net/MjAxOQ/Mw/M_jc/MTAw-NzA0_/SE-xT_/MQ/video/1512000/index.m3u8?hdntl=exp=1665823787~acl=%2f*~id=123456~data=hdntl~hmac=werf23asdg1"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 17 
[download] Destination: E:\Downloads\video_file.f1680.mp4
[debug] File locking is not supported. Proceeding without locking
[download] 100% of   18.85MiB in 00:00:02 at 6.54MiB/s
[debug] Invoking hlsnative downloader on "https://videosite.net/MjAxOQ/Mw/M_jc/MTAw-NzA0_/SE-xT_/MQ/audio/1/64000/index.m3u8?hdntl=exp=1665823787~acl=%2f*~id=123456~data=hdntl~hmac=werf23asdg1"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 17 
[download] Destination: E:\Downloads\video_file.faudio-64000-default.mp4
[download] 100% of  824.89KiB in 00:00:01 at 530.77KiB/s
[debug] ffmpeg command line: ".\bin\ffprobe" -show_streams "file:E:\Downloads\video_file.faudio-64000-default.mp4"
[Merger] Merging formats into "E:\Downloads\video_file.mp4" 
[debug] ffmpeg command line: ".\bin\ffmpeg" -y -loglevel "repeat+info" -i "file:E:\Downloads\video_file.f1680.mp4" -i "file:E:\Movies & TV\Vi
deos\Downloads\UFC\video_file.faudio-64000-default.mp4" -c copy -map "0:v:0" -map "1:a:0" "-bsf:a:0" aac_adtstoasc -movflags "+faststart" "file:E:\Downloads\video_file.temp.mp4"
Deleting original file E:\Downloads\video_file.faudio-64000-default.mp4 (pass -k to keep) 
Deleting original file E:\Downloads\video_file.f1680.mp4 (pass -k to keep)
[Metadata] Adding metadata to "E:\Downloads\video_file.mp4"
[debug] ffmpeg command line: ".\bin\ffmpeg" -y -loglevel "repeat+info" -i "file:E:\Downloads\video_file.mp4" -map 0 -dn -ignore_unknown -c co
py -write_id3v1 1 -metadata "title=master" -metadata "purl=https://videosite.net/MjAxOQ/Mw/M_jc/MTAw-NzA0_/SE-xT_/MQ/master.m3u8?hdnea=exp=1665737395~acl=/MjAxOQ/Mw/M_jc/MTAw-NzA0_/SE-xT_/MQ/*~id=123456~hmac=werf23asdg1" -metadata "comment=https://videosite.net/MjAxOQ/Mw/M_jc/MTAw-NzA0_/SE-xT_/MQ/master.m3u8?hdnea=exp=1665737395~acl=/MjAxOQ/Mw/M_jc/MTAw-NzA
0_/SE-xT_/MQ/*~id=123456" -movflags "+faststart" "file:E:\Downloads\video_file.temp.mp4"
```

**Comment by dirkf** [comment]
Are you trying to show some progress information, or just the final result?

Probably some `--print ...` incantation involving `acodec` and `vcodec` of the result would do the latter. Also, could you be invoking yt-dlp in a way that downloads neither media type?

**Comment by m4heshd** [comment]
@dirkf Thank you for the response.

> Are you trying to show some progress information

I am currently parsing the progress using a custom JSON output from `--progress-template` .  I actually ended up using `info.video_ext` to get the downloading media type since It's `"none"` if the download is an audio file.

One thing I have to mention, the documentation around this functionality is lacking a lot. I had to go through the source code and do so much testing to get to this stage.

Do you know if I could get all the outputs in JSON format? Like the `[Merger]`, `[info]`, `[hlsnative]` steps? I've tried a bunch of JSON related options but none does what I want them to do. Also it's weird that `Deleting original file` step isn't tagged. Something like `[cleanup]`?

**Comment by dirkf** [comment]
If you're interested in progress output, are you considering a combined video and audio download as video? What about subtitle-only, etc?

You can't rely on `video_ext`: see #5257.

Other people will know more about using `--progress-template ...`.

**Comment by m4heshd** [comment]
> What about subtitle-only, etc?

This tool of mine will always stick to the same source and will always download only video + audio in the same format + codec.

> are you considering a combined video and audio download as video?

You mean a simultaneous download inside a single instance right? 🤔 I did consider that, searched around but never found anything except `--downloader ffmpeg`. So I just coded around that. Do you have any suggestions?

> You can't rely on `video_ext`

I only went with it since the download sources will be consistent and as mentioned in that issue, `acodec` and `vcodec` were very inconsistent for me. Found a few other options but `video_ext` was the best I found.

**Comment by pukkandan** [comment]
> You can't rely on video_ext: see https://github.com/yt-dlp/yt-dlp/issues/5257.

The most reliable way to tell video apart is `vcodec="none"` - anything except `"none"` (including `nul`) indicate that there is a video stream. This method will always work, assuming no bugs in yt-dlp. Checking `video_ext` also technically works right now, but it's not a documented field and I cannot guarantee it'll keep working in future versions. #5257 is clearly a bug, and even ytdl/p's own format selectors will be broken for it.


> > are you considering a combined video and audio download as video?
> 
> You mean a simultaneous download inside a single instance right?

They mean pre-merged format (like `18`/`22` on Youtube). It probably makes sense for you to consider them as video. If not, you can do a similar check for `acodec` to distinguish them


> Do you know if I could get all the outputs in JSON format? Like the [Merger], [info], [hlsnative] steps?

You cannot get all outputs in json format. Only video info (`-j`), playlist info (`-J`), download progress (`--progress-template`) and postprocessing progress (`--progress-template postprocess:`) are available as JSON. For the rest of the output, idk what data you'd want to parse from them. If you just want to show it to the user, you can mirror the messages as-is. Otherwise, you'll need to explain your use-case better for me to do anything about it.

**Comment by m4heshd** [comment]
@pukkandan Thank you for the very in-depth info.

> The most reliable way to tell video apart is `vcodec="none"` - anything except "none" (including nul) indicate that there is a video stream

I'm gonna take your advice and refactor my code on this one.

> They mean pre-merged format (like `18`/`22` on Youtube). It probably makes sense for you to consider them as video.

Oh I actually wanted to do it that way originally but unfortunately my source doesn't have a combined format.

```md
ID                   EXT RESOLUTION FPS │   TBR PROTO │ VCODEC        VBR ACODEC     MORE INFO
───────────────────────────────────────────────────────────────────────────────────────────────────────
audio-1-Undetermined mp4 audio only     │       m3u8  │ audio only        unknown    [und] Undetermined
audio-2-Undetermined mp4 audio only     │       m3u8  │ audio only        unknown    [und] Undetermined
audio-3-Undetermined mp4 audio only     │       m3u8  │ audio only        unknown    [und] Undetermined
451                  mp4 512x288     30 │  452k m3u8  │ avc1.42c01f  452k video only
771                  mp4 640x360     30 │  771k m3u8  │ avc1.42c01f  771k video only
1150                 mp4 896x504     30 │ 1151k m3u8  │ avc1.4d4028 1151k video only
1701                 mp4 1280x720    30 │ 1701k m3u8  │ avc1.640029 1701k video only
3585                 mp4 1280x720    30 │ 3585k m3u8  │ avc1.640029 3585k video only
5115                 mp4 1920x1080   30 │ 5115k m3u8  │ avc1.640029 5115k video only
8161                 mp4 1920x1080   30 │ 8162k m3u8  │ avc1.64002a 8162k video only
```

> You cannot get all outputs in json format. Only video info (`-j`), playlist info (`-J`), download progress (`--progress-template`) and postprocessing progress (`--progress-template postprocess:`) are available as JSON.

Now I know. 😊 

> If you just want to show it to the user, you can mirror the messages as-is.

I'm already parsing those messages with some regex. I just wanted to make sure that those will be consistent enough for the application to not break.
