### ISSUE TITLE
requested format not avaliable [filesize]

### ISSUE THREAD

**Issue by notsolowki** [yt-dlp/yt-dlp#5245]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.10.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Im trying to download a video and i know the filze sizes of the avaliable formats. But for some reason i keep getting  

`ERROR: [GoDiscovery] 2546481: Requested format is not available. Use --list-formats for a list of available formats`

when i list the formats, 

```
[GoDiscovery] battlebots-discovery-atve-us/its-robot-fighting-time: Downloading MPD manifest
[info] Available formats for 2546481:
ID                    EXT   RESOLUTION │   FILESIZE   TBR PROTO │ VCODEC        VBR ACODEC      ABR ASR MORE INFO
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
dash-thumbnails       mhtml unknown    │                  mhtml │ images                                DASH storyboards (jpeg)
dash-audio_eng=125000 m4a   audio only │ ~ 38.45MiB  125k dash  │ audio only        mp4a.40.2  125k 48k [en] DASH audio, m4a_dash
dash-video=142000     mp4   416x234    │ ~ 43.68MiB  142k dash  │ avc1.4D400C  142k video only          DASH video, mp4_dash
dash-video=268000     mp4   416x234    │ ~ 82.43MiB  268k dash  │ avc1.4D400C  268k video only          DASH video, mp4_dash
dash-video=512000     mp4   640x360    │ ~157.49MiB  512k dash  │ avc1.4D4016  512k video only          DASH video, mp4_dash
dash-video=976000     mp4   960x540    │ ~300.21MiB  976k dash  │ avc1.4D401F  976k video only          DASH video, mp4_dash
dash-video=1694000    mp4   1280x720   │ ~521.06MiB 1694k dash  │ avc1.4D401F 1694k video only          DASH video, mp4_dash
dash-video=3051000    mp4   1280x720   │ ~938.46MiB 3051k dash  │ avc1.4D401F 3051k video only          DASH video, mp4_dash
dash-video=5411000    mp4   1280x720   │ ~  1.63GiB 5411k dash  │ avc1.4D401F 5411k video only          DASH video, mp4_dash
dash-video=9766000    mp4   1280x720   │ ~  2.93GiB 9766k dash  │ avc1.4D401F 9766k video only          DASH video, mp4_dash`

but why the error? am i doing somthing wrong?


### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

_No response_
```

**Comment by bashonly** [comment]
> `filesize`: The number of bytes, if known in advance
> `filesize_approx`: An estimate for the number of bytes

all formats listed in your log only have approximate filesizes. without seeing a verbose log, the commands you're running, or an example URL, my guess would be you are doing format selection with `filesize` when you need to be doing it with `filesize_approx`
