### ISSUE TITLE
Embed English auto generated subtitles possible?

### ISSUE THREAD

**Issue by AtomicNess123** [yt-dlp/yt-dlp#5248]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.10.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Simple question: is it possible to embed the auto-generated English subtitles? It seems it is only possible for the real subtitles only.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
--write-auto-sub --embed-sub

**Comment by gamer191** [comment]
https://github.com/yt-dlp/yt-dlp/issues/630#issuecomment-893659460

**Comment by AtomicNess123** [comment]
Thanks. If I may ask this too: How to download it as mp4 with embeded subs?
When I use:

`yt-dlp --write-auto-sub --embed-subs ext:mp4 [URL]`

It won't download as mp4

**Comment by pukkandan** [comment]
> Thanks. Is it possible to have them by default embedded?

Not for now. See https://github.com/yt-dlp/yt-dlp/pull/3709



> When I use:
> 
> `yt-dlp --write-auto-sub --embed-subs ext:mp4 [URL]`
> 
> It won't download as mp4

I'm curious what made you think that's valid syntax



> How to download it as mp4 with embeded subs?

Use either `-f` or `-S` to select mp4 format. Or, use `--remux`/`--recode` to convert it. Can't give a more detailed answer without knowing what u r downloading and your exact requirements. I suggest going through the "format selection" section of the readme
