### ISSUE TITLE
Redownloading subtitles When Rerunning It Even Though It Already Finished

### ISSUE THREAD

**Issue by nochlab1** [yt-dlp/yt-dlp#525]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running yt-dlp version **2021.07.07**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
C:\Users\nochl\Desktop\New folder (7)>yt-dlp -v --audio-multistreams -o "test" -f bestvideo+audio-English-1+audio-Hebrew-1 --all-subs --embed-subs _Link Redacted_
[debug] Command-line config: ['-v', '--audio-multistreams', '-o', 'test', '-f', 'bestvideo+audio-English-1+audio-Hebrew-1', '--all-subs', '--embed-subs', '_Link Redacted_']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] yt-dlp version 2021.07.07 (exe)
[debug] Python version 3.9.6 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] exe versions: ffmpeg 4.3.1-2020-11-19-full_build-www.gyan.dev, ffprobe 4.3.1-2020-11-19-full_build-www.gyan.dev
[debug] Proxy map: {}
[debug] [generic] Extracting URL: _Link Redacted_
[generic] master: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] master: Downloading webpage
[generic] master: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Downloading subtitles: en, fr, es
[info] master: Downloading 1 format(s): 5991+audio-English-1+audio-Hebrew-1
[info] Writing video subtitles to: test.en.vtt
[debug] Invoking downloader on "_Link Redacted_"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 133
[download] Destination: test.en.vtt
[download] 100% of 14.77KiB in 00:18
[info] Writing video subtitles to: test.fr.vtt
[debug] Invoking downloader on "_Link Redacted_"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 133
[download] Destination: test.fr.vtt
[download] 100% of 15.68KiB in 00:14
[info] Writing video subtitles to: test.es.vtt
[debug] Invoking downloader on "_Link Redacted_"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 133
[download] Destination: test.es.vtt
[download] 100% of 15.60KiB in 00:13
[download] test.mp4 has already been downloaded
WARNING: master: malformed AAC bitstream detected
[EmbedSubtitle] Embedding subtitles in "test.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:test.mp4" -i "file:test.en.vtt" -i "file:test.fr.vtt" -i "file:test.es.vtt" -c copy -map 0 -dn -map "-0:s" -map "-0:d" "-c:s" mov_text -map "1:0" "-metadata:s:s:0" "language=eng" -map "2:0" "-metadata:s:s:1" "language=fra" -map "3:0" "-metadata:s:s:2" "language=spa" "file:test.temp.mp4"
Deleting original file test.es.vtt (pass -k to keep)
Deleting original file test.en.vtt (pass -k to keep)
Deleting original file test.fr.vtt (pass -k to keep)

```

## Description

when I rerun a command to download something with same file name it says file already downloaded and doesn't redownload it but when I have a command with downloading subtitles included it redownloads the subtitles and readds them to the file.
the reason why this is a issue for me is because I make a bat file with a few links and when it fails I just run the script again but when using subtitles it goes thru all the finishes ones and redoes the subtitles when I don't need them

**Comment by Ashish0804** [comment]
just use download archive 

`--download-archive archive.log`

**Comment by nochlab1** [comment]
i tried but it just gave the id "generic master" so it doesnt download any of my other videos

**Comment by pukkandan** [comment]
Unless the files have a unique id, it is not possible for yt-dlp to properly use archive. And without archive, it is not possible to detect whether subs are already embedded and whether they are the right ones.

If you are batch downloading, you must be using some kind of unique id for the filename, no? If so, we can force that field to become the `id` and you can then use the archive with it. Otherwise, there is no way

**Comment by nochlab1** [comment]
Can a option be added to be like audio and video that it doesn't check the quality or anything just if the file name is already present

**Comment by pukkandan** [comment]
> If you are batch downloading, you must be using some kind of unique id for the filename, no? If so, we can force that field to become the id and you can then use the archive with it.

You never answered my question in the first place. Before even thinking of adding a new option, I'd need to know whether it can be accomplished by an existing option

**Comment by nochlab1** [comment]
It is not catching any id i manually set the name for each file

**Comment by pukkandan** [comment]
> It is not catching any id i manually set the name for each file

If that is the case, you can easily first check if the file exists before trying to download it.

Another way would be to force the manually set filename to be the id of the video and use `--download-archive`:

    --download-archive archive.txt  -o "%(id)s.%(ext)s" --parse-metadata " file-name-set-manually: %(id)s"

**Comment by nochlab1** [comment]
How do i check if the file exists before downloading?

**Comment by nochlab1** [comment]
I dont really have a script its just a .bat file with all the links

**Comment by pukkandan** [comment]
> Another way would be to force the manually set filename to be the id of the video and use --download-archive:
--download-archive archive.txt  -o "%(id)s.%(ext)s" --parse-metadata " file-name-set-manually: %(id)s"

**Comment by nochlab1** [comment]
the issue is there is no video id its just generic master

**Comment by nochlab1** [comment]
how do i set a custom name for what it says in the archive file?

**Comment by pukkandan** [comment]
> how do i set a custom name for what it says in the archive file?

I already answered this multiple times

This is how you can do it!

> Another way would be to force the manually set filename to be the id of the video and use `--download-archive`:
> 
> ```
> --download-archive archive.txt  -o "%(id)s.%(ext)s" --parse-metadata " file-name-set-manually: %(id)s"
> ```

**Comment by nochlab1** [comment]
sorry i dont really know much and i tried what you wrote and it wasnt working

**Comment by nochlab1** [comment]
imagine the name i wanted was 1.mp4 how would i put it in

**Comment by nochlab1** [comment]
yt-dlp -v --all-subs --embed-subs --audio-multistreams -o "1 2.mp4" -f bestvideo+audio-English-1+audio-Hebrew-1 test.com/master.m3u8 this is the command where do i add it and what do i change

**Comment by pukkandan** [comment]
yt-dlp  -- URL
```
yt-dlp -v --all-subs --embed-subs --audio-multistreams --download-archive archive.txt -o "%(id)s.%(ext)s" --parse-metadata " 1: %(id)s" -f bestvideo+audio-English-1+audio-Hebrew-1 test.com/master.m3u8
```

**Comment by nochlab1** [comment]
yt-dlp: error: You must provide at least one URL.

**Comment by nochlab1** [comment]
yt-dlp -v --all-subs --embed-subs --audio-multistreams --download-archive archive.txt -o "%(id)s.%(ext)s" --parse-metadata " A Loving Approach - 879: %(id)s" -f bestvideo+audio-English-1+audio-Hebrew-1 https://deybpcaja6zfo.cloudfront.net/cbb7f4e0-e8e4-4fb1-9252-c73300bbd5bf/hls_264/hd/master.m3u8

**Comment by pukkandan** [comment]
```
$ yt-dlp -v --all-subs --embed-subs --audio-multistreams --download-archive archive.txt -o "%(id)s.%(ext)s" --parse-metadata " A Loving Approach - 879: %(id)s" -f bestvideo+audio-English-1+audio-Hebrew-1 deybpcaja6zfo.cloudfront.net/cbb7f4e0-e8e4-4fb1-9252-c73300bbd5bf/hls_264/hd/master.m3u8
[debug] Command-line config: ['-v', '--all-subs', '--embed-subs', '--audio-multistreams', '--download-archive', 'archive.txt', '-o', '%(id)s.%(ext)s', '--parse-metadata', ' A Loving Approach - 879: %(id)s', '-f', 'bestvideo+audio-English-1+audio-Hebrew-1', 'deybpcaja6zfo.cloudfront.net/cbb7f4e0-e8e4-4fb1-9252-c73300bbd5bf/hls_264/hd/master.m3u8']
[debug] Loading archive file 'archive.txt'

[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] yt-dlp version 2021.08.10 (source)
[debug] Plugin Extractors: ['SamplePlugin']
[debug] Git HEAD: d20a7e3c2e
[debug] Python version 3.9.6 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] exe versions: ffmpeg n4.4-79-gde1132a891-20210809, ffprobe 2021-04-11-git-309e3cc15c-full_build-www.gyan.dev, phantomjs 2.1.1
[debug] Optional libraries: mutagen, pycryptodome, sqlite, websockets
[debug] Proxy map: {}
[debug] [generic] Extracting URL: deybpcaja6zfo.cloudfront.net/cbb7f4e0-e8e4-4fb1-9252-c73300bbd5bf/hls_264/hd/master.m3u8
WARNING: [generic] The url doesn't specify the protocol, trying with http
[debug] [generic] Extracting URL: http://deybpcaja6zfo.cloudfront.net/cbb7f4e0-e8e4-4fb1-9252-c73300bbd5bf/hls_264/hd/master.m3u8
[generic] master: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] master: Downloading webpage
[generic] master: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Downloading subtitles: de, he, fr, es, en, ru, yi
[debug] Searching for '\\ (?P<id>.+)' in ' A Loving Approach - 879'
[MetadataParser] Parsed id from ' A Loving Approach - 879': 'A Loving Approach - 879'
[info] A Loving Approach - 879: Downloading 1 format(s): 6016+audio-English-1+audio-Hebrew-1
[info] Writing video subtitles to: A Loving Approach - 879.de.vtt
[debug] Invoking downloader on "http://deybpcaja6zfo.cloudfront.net/cbb7f4e0-e8e4-4fb1-9252-c73300bbd5bf/hls_264/hd/text/de.m3u8"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 152
[download] Destination: A Loving Approach - 879.de.vtt
[download]   1.3% of ~1.19KiB at Unknown speed ETA 02:14
ERROR: Interrupted by user

```

**Comment by nochlab1** [comment]
thanks so much working  now

**Comment by nochlab1** [comment]
didn't actually work still saved "generic master"

**Comment by nochlab1** [comment]
do you know why its not working in a bat file
but if i put it into cmd it works?

**Comment by nochlab1** [comment]
If possible can you either remove the link from your post or delete as its a private link
Thanks
