### ISSUE TITLE
How can I get a python event after the .webm file is converted to mp3 ?

### ISSUE THREAD

**Issue by ThurstyWonk** [yt-dlp/yt-dlp#5252]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.10.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Hello, I'm making a python program and I would like to have an event that get fired once the mp3 and .webm files are merged ? I managed to make something happen once the download was finished using the progress_hooks but not for when the post processing is done...

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
Add a postprocessor. See https://github.com/yt-dlp/yt-dlp#add-a-custom-postprocessor

**Comment by ThurstyWonk** [comment]
> Add a postprocessor. See https://github.com/yt-dlp/yt-dlp#add-a-custom-postprocessor

Thank you for the reply, I did what you said and it seems to work fine except that I get this error...
![image](https://user-images.githubusercontent.com/78755503/196028963-a106b3f7-8e14-4725-96a4-27dee732aa65.png)

**Comment by pukkandan** [comment]
Show me minimum reproducible code

**Comment by ThurstyWonk** [comment]
@pukkandan
`
import yt_dlp
import os

url = "https://youtu.be/lh0w01S7Jnk?list=RDgjdLAsnR_Ws"
ydl_opts = {'no-part': True,"external_downloader_args": ['-loglevel', 'panic'],'format': 'bestaudio/best','outtmpl': "C:/Users/gouth/Desktop/Musique/Werewolves of London (2007 Remaster).mp3",'ffmpeg_location': './ffmpeg-N-103380-ge41bd075dd-win64-gpl/bin', 'noplaylist': True,'postprocessors':[{'key':'FFmpegExtractAudio','preferredcodec': 'mp3','preferredquality': 'bitrate'}]}

def rename():
    mp3_path = "C:/Users/gouth/Desktop/Musique/Werewolves of London (2007 Remaster).mp3"
    os.rename(mp3_path, "C:/Users/gouth/Desktop/Musique/Warren Zevon - Werewolves of London.mp3")
            
yt_dlp.YoutubeDL(ydl_opts).download([url])
yt_dlp.YoutubeDL(ydl_opts).add_post_processor(rename())
`

**Comment by Grub4K** [comment]
You did not follow the example provided in the URL at all. You need to:
- create a class subclassing `yt_dlp.postprocessor.PostProcessor`
- create a `run` method in that class matching the required signature
- reuse the same `YoutubeDL` instance for adding the postprocessor and downloading
- call the `add_post_processor` method before downloading the url

Take a look at the [documentation](https://github.com/yt-dlp/yt-dlp#add-a-custom-postprocessor) and possibly `help(yt_dlp.postprocessor.PostProcessor)` please.

**Comment by ThurstyWonk** [comment]
Thank you @Grub4K, I'm sorry, I tough that creating a class was optional. 😖 But now it works! 👍
