### ISSUE TITLE
Download Livestream

### ISSUE THREAD

**Issue by yfreezer** [yt-dlp/yt-dlp#5266]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.10.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I'd like someone to explain to me how to download a livestream because im getting an error that i don't understand 

when i try to use the `--live-from-start` option i get an error saying `yt-dlp: error: no such option: --live-from-start`

i feel like im missing something but i don't understand

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by elyse0** [comment]
`--live-from-start` is only available for Youtube livestreams, but please show verbose log

**Comment by yfreezer** [comment]
it was for a youtube livestream
Im not sure how to show you the logs because when i try to run for instance
`yt-dlp -vU --live-from-start https://www.youtube.com/watch?v=PU6E0XBis5g`

all i get is 
`Usage: yt-dlp [OPTIONS] URL [URL...]
yt-dlp: error: no such option: --live-from-start`

**Comment by bashonly** [comment]
are you sure about this:
>     * [x]  I've verified that I'm running yt-dlp version **2022.10.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
