### ISSUE TITLE
[www.hotstar.com broken site] yt-dlp exits with HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by velw** [yt-dlp/yt-dlp#5267]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.10.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

India

### Provide a description that is worded well enough to be understood

I'm reporting this broken site: https://www.hotstar.com/in/tv/mahabharat/435/ashwatthama-kills-dhrishtadyumna/1000012031

I am running yt-dlp version 2022.10.04 --- it fails with an HTTP 403 error (full log below).

The video is accessible and watchable in the browser at that URL without logging in, and from the same IP address. I've tried running yt-dlp with the same command and also pulling the cookies from the browser, but it makes no difference.

No parameters need to be quoted or escaped, as far as I can see (the error message doesn't seem like that kind of problem, and this is also the same command I've been using previously with this same site for other episodes of the same show with no issue).

I've searched the bugtracker and can't find a previous issue that seems to explain what I'm seeing, and I've read the guidelines for opening an issue. Since no login is needed to access the video via a browser, there is no login to share.

The website is geolocked to Indian IP addresses so I use a VPN (.dump file output from --write-pages is attached). While I have had problems with other VPN services in the past, the VPN I'm using now has been very reliable until this point - in fact, until this evening. I was able to successfully access two files, and then this next one produced the error and now the other episodes (which I could reach hours ago) also produce the same error - but they are all still accessible via the browser.

The reason I try to download these videos is purely because my internet connection is slow and that makes it difficult to watch at a decent quality resolution unless I can download the video first.

Dump files:
[1000012031_https_-_api.hotstar.com_um_v3_users.dump.txt](https://github.com/yt-dlp/yt-dlp/files/9802662/1000012031_https_-_api.hotstar.com_um_v3_users.dump.txt)
[1000012031_https_-_www.hotstar.com_in.dump.txt](https://github.com/yt-dlp/yt-dlp/files/9802663/1000012031_https_-_www.hotstar.com_in.dump.txt)
[1000012031_https_-_api.hotstar.com_o_v1_episode_detailcontentId=1000012031_tas=10000.dump.txt](https://github.com/yt-dlp/yt-dlp/files/9802664/1000012031_https_-_api.hotstar.com_o_v1_episode_detailcontentId.1000012031_tas.10000.dump.txt)

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp.exe -vU --write-pages --no-check-certificate -F --socket-timeout 300 https://www.hotstar.com/in/tv/mahabharat/435/ashwatthama-kills-dhrishtadyumna/1000012031

[debug] Command-line config: ['-vU', '--write-pages', '--no-check-certificate', '-F', '--socket-timeout', '300', 'https://www.hotstar.com/in/tv/mahabharat/435/ashwatthama-kills-dhrishtadyumna/1000012031']
[debug] Encodings: locale cp932, fs utf-8, pref cp932, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.10.04 [4e0511f] (win32_exe)
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg git-2019-12-26-b0d0d7e
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1690 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.10.04, Current version: 2022.10.04
yt-dlp is up to date (2022.10.04)
[debug] [hotstar] Extracting URL: https://www.hotstar.com/in/tv/mahabharat/435/ashwatthama-kills-dhrishtadyumna/1000012031
[hotstar] 1000012031: Downloading JSON metadata
[hotstar] Saving request to 1000012031_https_-_api.hotstar.com_o_v1_episode_detailcontentId=1000012031_tas=10000.dump
[hotstar] 1000012031: Downloading webpage
[hotstar] Saving request to 1000012031_https_-_www.hotstar.com_in.dump
[hotstar] 1000012031: Downloading token
[hotstar] Saving request to 1000012031_https_-_api.hotstar.com_um_v3_users.dump
[hotstar] 1000012031: Downloading JSON metadata
ERROR: [hotstar] 1000012031: Unable to download JSON metadata: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 672, in extract
  File "yt_dlp\extractor\hotstar.py", line 176, in _real_extract
  File "yt_dlp\extractor\hotstar.py", line 74, in _call_api_v2
  File "yt_dlp\extractor\hotstar.py", line 48, in _call_api_impl
  File "yt_dlp\extractor\common.py", line 1032, in download_content
  File "yt_dlp\extractor\common.py", line 996, in download_handle
  File "yt_dlp\extractor\common.py", line 866, in _download_webpage_handle
  File "yt_dlp\extractor\common.py", line 823, in _request_webpage

  File "yt_dlp\extractor\common.py", line 805, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 3682, in urlopen
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

**Comment by pukkandan** [comment]
@m4tu4g

**Comment by m4tu4g** [comment]
can't reproduce
can you try again and update issue?

**Comment by velw** [comment]
> can't reproduce can you try again and update issue?

Thank you (both) for looking at this
I've just tried it again and tonight it seems to be working fine. How odd! 
But thank you again. If it happens again I will add a comment to this same report.
I'm not sure if I should close this issue as "completed" (because the problem seems to have resolved itself) or "not planned" (because it can no longer be reproduced), so I will just add this comment and let you close it as you see fit.

**Comment by selvinjack** [comment]
@velw Hey how do you fixed 403 error im using own server vpn
