### ISSUE TITLE
Hotst@r extract [Broken]

### ISSUE THREAD

**Issue by cvatricks** [yt-dlp/yt-dlp#527]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running yt-dlp version **2021.07.07**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
ERROR: Unable to download JSON metadata: HTTP Error 403: Forbidden (caused by ); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.

```

## Description

While Trying for hotstar, it shows 403 forbidden... So Please solve this ASAP

**Comment by Ashish0804** [comment]
paste the verbose log.

**Comment by pukkandan** [comment]
Closed due to inactivity
