### ISSUE TITLE
Request format not available when using best

### ISSUE THREAD

**Issue by Aphexus** [yt-dlp/yt-dlp#5272]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.10.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

I've h ad this issue on a few sites where using bestvideo+bestaudio fails. This also fails for youtube-dl but it fails regardless while yt-dlp works when I just call it without the extra commands, eg: "yt-dlp https://rumble.com/v1nmqdh". The problem is I typically use yt-dlp in a script that does bulk downloading and tries to get the best quality and it gets broke by this failure. I had to make a work around for the script to work by ignoring the best quality flag.

The fix is to figure out why bestvideo+bestaudio is failing as a format as it should work and possibly allow a failure that still downloads the video with a warning. (There probably is a failure format but I don't know what it is)

Regardless this is a bug since bestvideo+bestaudio should get whatever works and since no specification does work it means it is failing for no reason.

The command line is effectively:
 -c -f bestvideo+bestaudio --no-cache-dir --ignore-errors --no-check-certificate --merge-output-format mkv  --windows-filenames

The error.

[generic] v1nmqdh-albert-einstein-talks-about-war-nationalism-democracy-and-the-usa: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] v1nmqdh-albert-einstein-talks-about-war-nationalism-democracy-and-the-usa: Extracting information
[RumbleEmbed] v1l0kjv: Downloading JSON metadata
ERROR: [RumbleEmbed] v1l0kjv: Requested format is not available. Use --list-formats for a list of available formats

(1/1)WARNING: [generic] Falling back on generic information extractor --- https://rumble.com/v1nmqdh-albert-einstein-talks-about-war-nationalism-democracy-and-the-usa.html!

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
I can't run since I am using it in a script and, as I already pointed out, it is working fine when the -f bestvideo+bestaudio is not specified so I've already located the issue for you. Specifying that format should never fail if it passes for any format(there is always a best) and since it does download when not specified this means the code that determines the best is broken. It is not properly defaulting to the default format.
```

**Comment by pukkandan** [comment]
The default is `bv*+ba/b`, not `bv+ba`. See what each of these does in the docs


---

> I can't run since I am using it in a script 

Doesnt matter. In future, if you are reporting a bug, you MUST give verbose log
