### ISSUE TITLE
Mx Player problem with some URLs

### ISSUE THREAD

**Issue by bibsp** [yt-dlp/yt-dlp#5276]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.10.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

India

### Provide a description that is worded well enough to be understood

Not working with some movie URLs like:
https://www.mxplayer.in/movie/watch-bhagam-bhag-movie-online-b50750f485274cad5bd81e7ee1a021ef?watch=true

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.mxplayer.in/movie/watch-bhagam-bhag-movie-online-b50750f485274cad5bd81e7ee1a021ef?watch=true']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.10.04 [4e0511f] (win32_exe)
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 5.1.2-essentials_build-www.gyan.dev (setts)
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1690 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.10.04, Current version: 2022.10.04
yt-dlp is up to date (2022.10.04)
[debug] [Mxplayer] Extracting URL: https://www.mxplayer.in/movie/watch-bhagam-bhag-movie-online-b50750f485274cad5bd81e7ee1a021ef?watch=true
[Mxplayer] watch-bhagam-bhag-movie-online: Downloading JSON metadata
ERROR: b50750f485274cad5bd81e7ee1a021ef: An extractor error has occurred. (caused by KeyError('mpd')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 672, in extract
  File "yt_dlp\extractor\mxplayer.py", line 162, in _real_extract
KeyError: 'mpd'
```

**Comment by m4tu4g** [comment]
any other URLs that behave the same for testing modification?

**Comment by bibsp** [comment]
https://www.mxplayer.in/movie/watch-deewane-huye-paagal-movie-online-4f9175c40a11c3994182a65afdd37ec6?watch=true
This is another such URL.

Make sure that modification does not break currently working URLs.

**Comment by bibsp** [comment]
Update:
Mx player is now completely broken. Unable to download JSON. HTTP error 400.

Should I open new issue for that?

**Comment by pukkandan** [comment]
Does the linked PR fix it?

**Comment by m4tu4g** [comment]
> Update: Mx player is now completely broken. Unable to download JSON. HTTP error 400.
> 
> Should I open new issue for that?

error log?

**Comment by bibsp** [comment]
I don't know what happend then. Can't reproduce anymore. Everything seems fine now.
Maybe the problem was from website's side. And now it is fixed by them.
