### ISSUE TITLE
...

### ISSUE THREAD

**Issue by ghost** [yt-dlp/yt-dlp#5290]
...

**Comment by pukkandan** [comment]
Out of scope

> Right now I have to find the files find . -type f *ytdl, get the id from the file name and build the link.

That sounds like a good enough solution

**Comment by pukkandan** [comment]
> To create the link I think you'd need to use the download-archive to store a template of a link.

The archive only has one purpose - to not re-download the video again. If you want to save the URLs, you should do so with `--print-to-file`
