### ISSUE TITLE
selecting medium quality 720

### ISSUE THREAD

**Issue by notsolowki** [yt-dlp/yt-dlp#5298]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.10.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

It seems like every website has to use some different combination of format settings.... .....   
 
most of the examples in the documentation dont work for alot of sites. for example

-f -best.x or -f best.x / whatever the command is dont work for ivestigation discovery. 

neither does, -f "[filesize_approx<480MiB]" 

neither does -f "[tbr<10000]"

nor -f "[height<=?720][tbr<9500]"

and bv+ba[filesize_approx<480MiB]  just ignores the size limiter

it seems like a riddle trying to figure out what seetings will be accepted. How do i select the lowest/medium quality 720p video. or the video that is <MB. im my experience its 50/50 what sites work with what wuality settings. the documentation does not help me. am i using the commands wrong?

```
[info] Available formats for 2205448:
ID                    EXT   RESOLUTION │   FILESIZE   TBR PROTO │ VCODEC        VBR ACODEC      ABR ASR MORE INFO
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
dash-thumbnails       mhtml unknown    │                  mhtml │ images                                DASH storyboards (jpeg)
dash-audio_eng=125000 m4a   audio only │ ~ 39.89MiB  125k dash  │ audio only        mp4a.40.2  125k 48k [en] DASH audio, m4a_dash
dash-video=145000     mp4   640x360    │ ~ 46.27MiB  145k dash  │ avc1.4D4016  145k video only          DASH video, mp4_dash
dash-video=224000     mp4   640x360    │ ~ 71.48MiB  224k dash  │ avc1.4D4016  224k video only          DASH video, mp4_dash
dash-video=424000     mp4   960x540    │ ~135.30MiB  424k dash  │ avc1.4D401F  424k video only          DASH video, mp4_dash
dash-video=731000     mp4   1280x720   │ ~233.27MiB  731k dash  │ avc1.4D401F  731k video only          DASH video, mp4_dash
dash-video=1289000    mp4   1280x720   │ ~411.33MiB 1289k dash  │ avc1.4D401F 1289k video only          DASH video, mp4_dash
dash-video=2638000    mp4   1920x1080  │ ~841.81MiB 2638k dash  │ avc1.4D4028 2638k video only          DASH video, mp4_dash
dash-video=4654000    mp4   1920x1080  │ ~  1.45GiB 4654k dash  │ avc1.4D4028 4654k video only          DASH video, mp4_dash
dash-video=8672000    mp4   1920x1080  │ ~  2.70GiB 8672k dash  │ avc1.4D4028 8672k video only          DASH video, mp4_dash

```

I need to download multiple videos at onces in batch script so they all have slightly different bitrates. i cant select a single exact bitrate. however i cant get any format except get the best quality video. idk if i should report this as a BUG or a question.

how do i got about getting that first 720 entry

**Comment by gamer191** [comment]
> how do i got about getting that first 720 entry

Are you sure you want the first one, which won't necessarily be the smallest one.

If you are sure, do `-f "worstvideo*[height=720]+worstaudio/worst[height=720]"`

I'll write a more detailed answer and explanation later

**Comment by notsolowki** [comment]
But if there were 3 720p streams there how would i pick the middle stream?

Im assuming that i can get the best 720p stream like this?

`-f "bv*[height=720]+ba/best[height=720]"`

but if a third 720p steram was there how would i select the middle from the last or first 720p?

**Comment by notsolowki** [comment]
Also the example u showed me did not include the audio track in the file?

**Comment by pukkandan** [comment]
>  im my experience its 50/50 what sites work with what wuality settings
> but some sites wont let me use filesize_aprox

Not all fields are available for all sites

**Comment by notsolowki** [comment]
I just tried `-f "bv*[height=720]+ba/best[height=720]"` assuming it would select that snd 720p stream but it appears to selected some stream over a gb. How would i select the second 720p stream?

**Comment by pukkandan** [comment]
> -f -best.x or -f best.x / whatever the command is dont work for ivestigation discovery.
>
> neither does, -f "[filesize_approx<480MiB]"
>
> neither does -f "[tbr<10000]"
>
> nor -f "[height<=?720][tbr<9500]"
>
> and bv+ba[filesize_approx<480MiB] just ignores the size limiter

You will need to provide examples (with verbose log) of where these do not work, and what you are expecting each of these to do. All of these are valid syntax. If they dont appear to work, it's probably because you are misunderstanding what you are doing

**Comment by pukkandan** [comment]
> I just tried `-f "bv*[height=720]+ba/best[height=720]"` assuming it would select that snd 720p stream but it appears to selected some stream over a gb.

But did it select the 720p? Why do u think 720p cant be over 1G?

**Comment by notsolowki** [comment]
Well from the --list-formats it showed a 2nd 720p stream and said it was roughly 411.33MB so i assumed it would be much over 500.

here is a debug output with filesize_apro
```
`[debug] Command-line config: ['-f', '[filesize_approx<480MiB]', 'https://www.investigationdiscovery.com/video/see-no-evil-investigation-discovery/what-happened-to-skylar-neese', '--cookies-from-browser', 'chrome', '--ap-mso', 'Spectrum', '--ap-username', 'PRIVATE', '--ap-password', 'PRIVATE', '-vU']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.10.04 [4e0511f] (win32_exe)
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.22623-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 2022-10-06-git-2c2aaa5bd0-full_build-www.gyan.dev (setts), ffprobe 2022-10-06-git-2c2aaa5bd0-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[Cookies] Extracting cookies from chrome
[debug] Extracting cookies from: "C:\Users\Laptop\AppData\Local\Google\Chrome\User Data\Default\Network\Cookies"
[debug] Found local state file at "C:\Users\Laptop\AppData\Local\Google\Chrome\User Data\Local State"
[Cookies] Extracted 1537 cookies from chrome
[debug] cookie version breakdown: {'v10': 1537, 'other': 0, 'unencrypted': 0}
[debug] Proxy map: {}
[debug] Loaded 1690 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.10.04, Current version: 2022.10.04
yt-dlp is up to date (2022.10.04)
[debug] [InvestigationDiscovery] Extracting URL: https://www.investigationdiscovery.com/video/see-no-evil-investigation-discovery/what-happened-to-skylar-neese
[debug] Using fake IP 6.90.141.178 (US) as X-Forwarded-For
[InvestigationDiscovery] see-no-evil-investigation-discovery/what-happened-to-skylar-neese: Downloading JSON metadata
[InvestigationDiscovery] 2205448: Downloading JSON metadata
[InvestigationDiscovery] see-no-evil-investigation-discovery/what-happened-to-skylar-neese: Downloading MPD manifest
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
ERROR: [InvestigationDiscovery] 2205448: Requested format is not available. Use --list-formats for a list of available formats
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1477, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1574, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1632, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2698, in process_video_result
yt_dlp.utils.ExtractorError: [InvestigationDiscovery] 2205448: Requested format is not available. Use --list-formats for a list of available formats
`
```

**Comment by pukkandan** [comment]
> here is a debug output with filesize_apro
> 
> ```
> `[debug] Command-line config: ['-f', '[filesize_approx<480MiB]', 'https://www.investigationdiscovery.com/video/see-no-evil-investigation-discovery/what-happened-to-skylar-neese', '--cookies-from-browser', 'chrome', '--ap-mso', 'Spectrum', '--ap-username', 'PRIVATE', '--ap-password', 'PRIVATE', '-vU']
> [debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
> [debug] yt-dlp version 2022.10.04 [4e0511f] (win32_exe)
> [debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.22623-SP0
> [debug] Checking exe version: ffmpeg -bsfs
> [debug] Checking exe version: ffprobe -bsfs
> [debug] exe versions: ffmpeg 2022-10-06-git-2c2aaa5bd0-full_build-www.gyan.dev (setts), ffprobe 2022-10-06-git-2c2aaa5bd0-full_build-www.gyan.dev
> [debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
> [Cookies] Extracting cookies from chrome
> [debug] Extracting cookies from: "C:\Users\Laptop\AppData\Local\Google\Chrome\User Data\Default\Network\Cookies"
> [debug] Found local state file at "C:\Users\Laptop\AppData\Local\Google\Chrome\User Data\Local State"
> [Cookies] Extracted 1537 cookies from chrome
> [debug] cookie version breakdown: {'v10': 1537, 'other': 0, 'unencrypted': 0}
> [debug] Proxy map: {}
> [debug] Loaded 1690 extractors
> [debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
> Latest version: 2022.10.04, Current version: 2022.10.04
> yt-dlp is up to date (2022.10.04)
> [debug] [InvestigationDiscovery] Extracting URL: https://www.investigationdiscovery.com/video/see-no-evil-investigation-discovery/what-happened-to-skylar-neese
> [debug] Using fake IP 6.90.141.178 (US) as X-Forwarded-For
> [InvestigationDiscovery] see-no-evil-investigation-discovery/what-happened-to-skylar-neese: Downloading JSON metadata
> [InvestigationDiscovery] 2205448: Downloading JSON metadata
> [InvestigationDiscovery] see-no-evil-investigation-discovery/what-happened-to-skylar-neese: Downloading MPD manifest
> [debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
> ERROR: [InvestigationDiscovery] 2205448: Requested format is not available. Use --list-formats for a list of available formats
> Traceback (most recent call last):
>   File "yt_dlp\YoutubeDL.py", line 1477, in wrapper
>   File "yt_dlp\YoutubeDL.py", line 1574, in __extract_info
>   File "yt_dlp\YoutubeDL.py", line 1632, in process_ie_result
>   File "yt_dlp\YoutubeDL.py", line 2698, in process_video_result
> yt_dlp.utils.ExtractorError: [InvestigationDiscovery] 2205448: Requested format is not available. Use --list-formats for a list of available formats
> `
> ```

Didnt I already answer this in your previous question? https://github.com/yt-dlp/yt-dlp/issues/5284

**Comment by pukkandan** [comment]
Actually, now that I look at it, this seems to be a continuation of https://github.com/yt-dlp/yt-dlp/issues/5245. In future, please keep follow up questions in one thread so that context is not lost

**Comment by notsolowki** [comment]
I thought so but its not what i wanted. your example only gave the video stream and the video stream ignored the filesize_aprox.

**Comment by pukkandan** [comment]
> > here is a debug output with filesize_apro
> 
> Didnt I already answer this in your previous question? #5284

To elaborate on this:
`-f [...]` => Give me the best pre-merged video satisfying `...`.

But the video u r downloading has no pre-merged formats, so this fails.

`-f bv[...]` => Give me the best video-only format satisfying `...`

If you also want audio, you'd add `+ba` to it, like `bv[filesize_approx<480M]+ba`

> and the video stream ignored the filesize_aprox.

log?

**Comment by pukkandan** [comment]
> ``
> 
> like `-f "mediumvideo*[height=720]+mediumaudio/med[height=720]"`

huh? what does that even mean?

**Comment by notsolowki** [comment]
Out of these two streams i want the 2nd

```
dash-video=731000     mp4   1280x720   │ ~233.27MiB  731k dash  │ avc1.4D401F  731k video only          DASH video, mp4_dash
dash-video=1289000    mp4   1280x720   │ ~411.33MiB 1289k dash  │ avc1.4D401F 1289k video only          DASH video, mp4_dash
```

i can get the first/worst "720" with `-f "worstvideo*[height=720]+worstaudio/worst[height=720]"`

but how do i grab the 2nd 720 stream that claims to be around 411MB. because when i use best it grabs a much larger stream.

**Comment by pukkandan** [comment]
> how do i grab the 2nd 720 stream that claims to be around 411MB. because when i use best it grabs a much larger stream.

The approximate filesize shown can often be wrong

**Comment by pukkandan** [comment]
If the log says downloading `dash-video=1289000`, that's the format u r getting

**Comment by notsolowki** [comment]
the log shows its downloading the 1080p instead.  This is format selection just bv.2 

```
`[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.10.04 [4e0511f] (win32_exe)
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.22623-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 2022-10-06-git-2c2aaa5bd0-full_build-www.gyan.dev (setts), ffprobe 2022-10-06-git-2c2aaa5bd0-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[Cookies] Extracting cookies from chrome
[debug] Extracting cookies from: "C:\Users\Laptop\AppData\Local\Google\Chrome\User Data\Default\Network\Cookies"
[debug] Found local state file at "C:\Users\Laptop\AppData\Local\Google\Chrome\User Data\Local State"
[Cookies] Extracted 1537 cookies from chrome
[debug] cookie version breakdown: {'v10': 1537, 'other': 0, 'unencrypted': 0}
[debug] Proxy map: {}
[debug] Loaded 1690 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.10.04, Current version: 2022.10.04
yt-dlp is up to date (2022.10.04)
[debug] [InvestigationDiscovery] Extracting URL: https://www.investigationdiscovery.com/video/see-no-evil-investigation-discovery/what-happened-to-skylar-neese
[debug] Using fake IP 6.21.151.228 (US) as X-Forwarded-For
[InvestigationDiscovery] see-no-evil-investigation-discovery/what-happened-to-skylar-neese: Downloading JSON metadata
[InvestigationDiscovery] 2205448: Downloading JSON metadata
[InvestigationDiscovery] see-no-evil-investigation-discovery/what-happened-to-skylar-neese: Downloading MPD manifest
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[info] 2205448: Downloading 1 format(s): dash-video=4654000
[debug] Invoking dashsegments downloader on "https://dplus-northamerica-cloudfront-gcs.prod-vod.h264.io/1dac2b67-338f-418b-b46f-1e6c3e8e7936/dash_clear_fmp4/x-discovery-token=Expires=1666310964&KeyName=primary&Signature=PHEfGHlyBSAMeDLrDdOiU6sGmnc/master.mpd"
[dashsegments] Total fragments: 656
[download] Destination: What Happened to Skylar Neese [2205448].mp4
[debug] File locking is not supported. Proceeding without locking
[download]  14.6% of ~   1.39GiB at    2.98MiB/s ETA 10:11 (frag 96/656)`
```
i want to add about 100 videos to the list and download them all roughly the same quality highest 720p.

some reason i can only manage to get worst 720p or bestvideo

**Comment by notsolowki** [comment]
Okay, bv.4 picks the video i want but im not sure it can be reliable enough to always pick that video.. whats another way i can select that video more reliably

**Comment by notsolowki** [comment]
This is still trying to download a 1080p video,

`-f "bv[height=720]+worstaudio/worst[height=720]"`

**Comment by pukkandan** [comment]
Pls make up your mind. First u said u wanted the "first 720 entry", then u asked for "second 720p stream", then "medium 720p" (which doesnt make sense - unless medium => second best) etc... What do u really want? The best 720p (`-S res:720`)? The second best video (-f `bv.2+ba`)? The second best 720p (`-S res:720 -f bv.2+ba`? best video with filesize_approx < 480M (`-f bv[filesize_approx<480M]+ba`)? something else?

**Comment by pukkandan** [comment]
> This is still trying to download a 1080p video,
> 
> `-f "bv[height=720]+worstaudio/worst[height=720]"`

Why do u think that?

**Comment by notsolowki** [comment]
Sorry it appears to have been resuming the 1080p download i previously canceled even tho i specified different format. i think they both work now lol. When it downloads hopefully the audio works now. thanks.

**Comment by notsolowki** [comment]
Now it downloads the auio track as a sperate file. is this normal? how do i make it into 1 file automatically?

**Comment by notsolowki** [comment]
Does `--merge-output-format mp4` combine the audio and video formats together into 1 file? why is the audio stream seperate how do i make it into 1 file. or better yet download the video and audio together?

**Comment by pukkandan** [comment]
> Now it downloads the audio track as a sperate file. is this normal? how do i make it into 1 file automatically?

> but -f bv[filesize_approx<480M]+ba is the right size but downloads audio and video seperate

It will merge after download finishes


> when i do `-f bv+ba[filesize_approx<480M]` it downloads the 1080p

You are asking for best video + (best audio < 480M)

**Comment by gamer191** [comment]
> > how do i got about getting that first 720 entry
> 
> Are you sure you want the first one, which won't necessarily be the smallest one.
> 
> If you are sure, do `-f "worstvideo*[height=720]+worstaudio/worst[height=720]"`
> 
> I'll send an explanation later, because "give a person a fish, and you feed them for a day. Teach a person to fish, and you feed them for a lifetime."

Wait, do you want me to send an explanation of `-f "worstvideo*[height=720]+worstaudio/worst[height=720]"`, or do you already understand it/don't care etc?

**Comment by pukkandan** [comment]
I don't think they ever wanted the worst 720p. Judging from the emojis, they wanted one of these: https://github.com/yt-dlp/yt-dlp/issues/5298#issuecomment-1284734060
