### ISSUE TITLE
[Feature Request] Run the command in --exec for comments

### ISSUE THREAD

**Issue by moom0o** [yt-dlp/yt-dlp#530]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running yt-dlp version **2021.07.07**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description

I'm trying to download just comments (because I already have the videos downloaded) so I have --skip-download. However this means --exec won't run after each video's comments are saved. It would be great if the command could be run after comments are saved aswell.

**Comment by pukkandan** [comment]
Next release will have an option `--exec-before-download`
