### ISSUE TITLE
 command not found: xsel -ob 

### ISSUE THREAD

**Issue by JediMaster25** [yt-dlp/yt-dlp#5314]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.10.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

[I've changed my yt-dlp's zsh configuration][1] and now I get the following error:

    ❯ ytvp
    [3] 2988691
    [4] 2988692
    ytvp:8: command not found: xsel -ob
    
    [4]  + 2988692 exit 2     $yt_dlp $opts --output  >> "/tmp/$LOG_NAME" 2>&1
    [3]  + 2988691 exit 2     $yt_dlp $opts --output  "$($paste)" >> "/tmp/$LOG_NAME" 2>&1

The log shows:

    yt-dlp: error: no such option: --continue
      --no-overwrites
      --no-post-overwrites
      --verbose
      --restrict-filenames
      --retry-sleep fragment:exp

Why is it treating all options as a single one?

I've tried running the `paste` command on its own and it works fine.

How do I fix this error?

This is my configuration now

    opts="--continue
      --no-overwrites
      --no-post-overwrites
      --verbose
      --restrict-filenames
      --retry-sleep fragment:exp=2:64
      --print-to-file"
    
    if [ -f /usr/local/bin/youtube-dl ]; then
      yt_dlp="/usr/local/bin/yt-dlp"
    else
      yt_dlp="$(which yt-dlp)"
    fi
    
    # If using Mac
    if [[ "$(uname -a | awk '{print $1}')" == "Darwin" ]]; then
      paste="pbpaste"
      opts="${opts} --ffmpeg-location /usr/local/bin/ffmpeg"
    else # If using Linux
      paste="xsel -ob"
    fi
    
    sanitize_linux_filename() {
      echo "$1" | sed -e 's/[^a-zA-Z0-9._-]/_/g'
    }
    
    get_log_name() {
      TIMESTAMP=$( date +%y%m%d%H%M%S )
      NAME=$( sanitize_linux_filename "$1" )
      echo "yt-dlp_${TIMESTAMP}_${NAME}.log"
    }
        
    # Video Playlist
    ytvp() {
      LOG_NAME=$( get_log_name "$1" )
      opts="${opts}
        --format '(bv+(wa[abr>=64]/ba))/b'
        --format-sort res:720,tbr~2000
        --no-playlist
        --download-archive 'downloaded.txt'"
        
      if ! $yt_dlp $opts --output "%(upload_date>%Y-%m-%d|)s%(upload_date& |)s%(title)s-%(id)s.%(ext)s" "$($paste)" >> "/tmp/$LOG_NAME" 2>&1 &; then
        $yt_dlp $opts --output "%(upload_date>%Y-%m-%d|)s%(upload_date& |)%(webpage_url_domain)s-%(id)s.%(ext)s" >> "/tmp/$LOG_NAME" 2>&1 &
      fi
    }

[1]: https://git.disroot.org/hirrolot19/dotfiles/commit/5ab08359afd4be6d12cff817b31b39626c8f2e11#diff-6a0a53cfa400a5b85f7791056115eb86a4e7c783

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
Ask in some linux/bash forums https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-your-question-about-yt-dlp
