### ISSUE TITLE
Create folder only if there is a string

### ISSUE THREAD

**Issue by JediMaster25** [yt-dlp/yt-dlp#5317]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.10.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I want to create an uploader folder only if the video has an uploader but I don't know if this is the correct way
```
%(uploader|)s%(uploader&/)s
```
I understand this is saying "write uploader or nothing", and "if uploader, write `/`".

When I've tried this
```
ytvpc() {
  TIMESTAMP=$( date +%y%m%d%H%M%S )
  NAME=$( sanitize_linux_filename "$1" )
  LOG_NAME="yt-dlp_${TIMESTAMP}_${NAME}.log"
  yt-dlp \
    --format "(bv+(wa[abr>=64]/ba))/b" \
    --format-sort res:720,tbr~2000 \
    --continue \
    --no-overwrites \
    --no-post-overwrites \
    --verbose \
    --restrict-filenames \
    --retry-sleep fragment:exp=2:64 \
    --download-archive "downloaded.txt" \
    --write-info-json \
    --write-comments \
    --write-thumbnail \
    --output "%(extractor)s/%(uploader|)s%(uploader&/)s%(upload_date>%Y-%m-%d|)s%(upload_date& |)s%(title)s-%(id)s.%(ext)s" \
    $(xsel -ob) \
    >> "/tmp/$LOG_NAME" 2>&1 &
}
```
I've gotten `Extractor/uploader_2022-10-18_title`. So it has subsituted the `/` for `_` and hasn't created a folder.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by dirkf** [comment]
`--restrict-filenames` ?

**Comment by pukkandan** [comment]
`a//b` is automatically converted to `a/b`. So you can just do `%(uploader|)s/`
