### ISSUE TITLE
[iPrima.cz] `Unable to extract JSON-LD`

### ISSUE THREAD

**Issue by cotwitch** [yt-dlp/yt-dlp#5318]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.10.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Czech Republic / Czechia

### Provide a description that is worded well enough to be understood

I'm able to successfully log-in the webpage and watch whole video stream `https://prima.iprima.cz/prostreno/libor-paulik`

Because iPrima now requires user to be logged in, I'm supplying credentials beforehand:

`https://auth.iprima.cz/oauth2/login`
`brahma@mailmetrash.com`
`123456l`

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['--username=PRIVATE', '--password=PRIVATE', '-vU', 'https://prima.iprima.cz/prostreno/libor-paulik']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.10.04 [4e0511f] (pip) API
[debug] Python 3.10.8 (CPython 64bit) - macOS-12.1-x86_64-i386-64bit
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 5.1.2 (setts), ffprobe 5.1.2, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1690 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.10.04, Current version: 2022.10.04
yt-dlp is up to date (2022.10.04)
[IPrima] Downloading login page
[IPrima] Logging in
[IPrima] Downloading token
[debug] [IPrima] Extracting URL: https://prima.iprima.cz/prostreno/libor-paulik
[IPrima] libor-paulik: Downloading webpage
[IPrima] p1078412: Getting manifest URLs
[IPrima] p1078412: Downloading m3u8 information
[IPrima] p1078412: Downloading MPD manifest
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
ERROR: [IPrima] libor-paulik: Unable to extract JSON-LD; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/usr/local/Cellar/yt-dlp/2022.10.4/libexec/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 672, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/Cellar/yt-dlp/2022.10.4/libexec/lib/python3.10/site-packages/yt_dlp/extractor/iprima.py", line 153, in _real_extract
    final_result = self._search_json_ld(webpage, video_id) or {}
  File "/usr/local/Cellar/yt-dlp/2022.10.4/libexec/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 1458, in _search_json_ld
    raise RegexNotFoundError('Unable to extract JSON-LD')
```

**Comment by bashonly** [comment]
It looks like this may be all that's needed:

```diff
diff --git a/yt_dlp/extractor/iprima.py b/yt_dlp/extractor/iprima.py
index 5e0b523dc..c98fe5b42 100644
--- a/yt_dlp/extractor/iprima.py
+++ b/yt_dlp/extractor/iprima.py
@@ -150,7 +150,7 @@ def _real_extract(self, url):
                         manifest_url, video_id, mpd_id='dash', fatal=False)
             self._sort_formats(formats)
 
-        final_result = self._search_json_ld(webpage, video_id) or {}
+        final_result = self._search_json_ld(webpage, video_id, default={})
         final_result.update({
             'id': video_id,
             'title': title,
```

**Comment by cotwitch** [comment]
@bashonly Great! Kindly thank you for checking it 😎 Confirming, the change you've supplied is working fine 👍
