### ISSUE TITLE
Does yt-dlp support Fox Nation in the latest build?

### ISSUE THREAD

**Issue by vega69-ux** [yt-dlp/yt-dlp#5319]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.10.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I've have seen already a request for yt-dlp to support Fox Nation. I was wondering if yt-dlp now supports Fox Nation in the latest build? I currently don't have an active subscription to test but am thinking of getting one if yt-dlp supports it in the latest build.

Fox Nation:
https://nation.foxnews.com/

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
https://tryitands.ee - or do u expect me to remember all the 1500+ supported sites?
