### ISSUE TITLE
Cannot download specific episodes from site : PLAYER.STV.TV

### ISSUE THREAD

**Issue by scotquestion** [yt-dlp/yt-dlp#5320]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.10.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

UK

### Provide a description that is worded well enough to be understood

The site https://stv.tv 
I have no problem downloading most Episodes but others have errors and do not download.
**Examples of URLs that successfully download :**
- https://player.stv.tv/episode/4aq6/all31-black-widows
- https://player.stv.tv/episode/2tdx/another-murder
- https://player.stv.tv/episode/48q8/trigger-point
**Examples of URLs that fail :**
- https://player.stv.tv/episode/48uk/sony-artofmore
- https://player.stv.tv/episode/461g/banijay1-gracepoint
- https://player.stv.tv/episode/48p0/sony-mastersofsex

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
/home/user1  ==> yt-dlp -vU https://player.stv.tv/episode/461g/banijay1-gracepoint
[debug] Command-line config: ['-vU', 'https://player.stv.tv/episode/461g/banijay1-gracepoint']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.10.04 [4e0511f] (zip)
[debug] Python 3.9.2 (CPython 32bit) - Linux-5.10.0-18-686-pae-i686-with-glibc2.31 (glibc 2.31)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.3.4-0, ffprobe 4.3.4-0
[debug] Optional libraries: Cryptodome-3.15.0, certifi-2020.06.20, sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Loaded 1690 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.10.04, Current version: 2022.10.04
yt-dlp is up to date (2022.10.04)
[debug] [stv:player] Extracting URL: https://player.stv.tv/episode/461g/banijay1-gracepoint
[stv:player] 461g: Downloading webpage
[debug] [brightcove:new] Extracting URL: http://players.brightcove.net/1486976045/default_default/index.html?videoId=6273843933001#__youtubedl_smuggle=%7B%22geo_countries%22%3A+%5B%22GB%22%5D%7D
[debug] Using fake IP 25.252.3.193 (GB) as X-Forwarded-For
[debug] Loading brightcove.1486976045_default from cache
[brightcove:new] 6273843933001: Downloading JSON metadata
ERROR: [brightcove:new] Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/home/brian/bin/yt-dlp/yt_dlp/extractor/common.py", line 672, in extract
    ie_result = self._real_extract(url)
  File "/home/brian/bin/yt-dlp/yt_dlp/extractor/brightcove.py", line 648, in _real_extract
    json_data = self._download_json(api_url, video_id, headers=headers)
  File "/home/brian/bin/yt-dlp/yt_dlp/extractor/common.py", line 1032, in download_content
    res = getattr(self, download_handle.__name__)(url_or_request, video_id, **kwargs)
  File "/home/brian/bin/yt-dlp/yt_dlp/extractor/common.py", line 996, in download_handle
    res = self._download_webpage_handle(
  File "/home/brian/bin/yt-dlp/yt_dlp/extractor/adobepass.py", line 1366, in _download_webpage_handle
    return super(AdobePassIE, self)._download_webpage_handle(
  File "/home/brian/bin/yt-dlp/yt_dlp/extractor/common.py", line 866, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query, expected_status=expected_status)
  File "/home/brian/bin/yt-dlp/yt_dlp/extractor/common.py", line 823, in _request_webpage
    raise ExtractorError(errmsg, cause=err)

  File "/home/brian/bin/yt-dlp/yt_dlp/extractor/common.py", line 805, in _request_webpage
    return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query))
  File "/home/brian/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3682, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/usr/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

/home/user1  ==>
```

**Comment by coletdjnz** [comment]
These are all DRM protected so yt-dlp cannot support them. But the error message should be improved to reflect that, if possible.
