### ISSUE TITLE
How to download channel metadata after downloading videos

### ISSUE THREAD

**Issue by JediMaster25** [yt-dlp/yt-dlp#5321]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.10.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I've downloaded the videos from a channel and now when I try to download the metadata using this options
```
--continue
--no-overwrites
--no-post-overwrites
--verbose
--restrict-filenames
--retry-sleep fragment:exp=2:64
--format '(bv+(wa[abr>=64]/ba))/b'
--format-sort res:720,tbr~2000
--download-archive 'downloaded.txt'
--skip-download
--write-info-json
--write-comments
--write-thumbnail
```
it doesn't download it. How can I download the metadata for the channels in the video without having to remove all the files first?

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
> it doesn't download it.

doesnt download what?

> How can I download the metadata 

Elaborate "download the metadata"

**Comment by JediMaster25** [comment]
It wasn't downloading the `info.json` and the rest of files I'm asking in the options that I've copied and I'm copying again here
```
--write-info-json
--write-comments
--write-thumbnail
```
but after removing the `--download-archive` option it works. So it's solved.

**Comment by pukkandan** [comment]
> but after removing the `--download-archive` option it works

Well, the whole point of --download-archive is that the recorded videos arent processed again
