### ISSUE TITLE
Requesting a toggleable parameter to throw an exception when sponsorblock api cannot be reached for any reason.

### ISSUE THREAD

**Issue by Glynax** [yt-dlp/yt-dlp#5324]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.10.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Alright so I'm using ytdl-sub which uses yt-dlp, and I'm mass downloading entire channels for archival. I've noticed sometimes I can see dozens of videos where sponsorblock api timed out (due to too many requests or otherwise) but the video still downloads without an error when using sponsorblock. Kind of defeats the purpose though doesn't it? The video(s) downloading with sponsor content still intact, and then since I'm using the archive just being left in that state even when sponsorblock starts responding again. The dev said the title would help with our use case.

![image](https://user-images.githubusercontent.com/7043861/197317129-6fb32bd7-1e93-4a50-a0c3-4ba60ffea02a.png)
![image](https://user-images.githubusercontent.com/7043861/197317165-22ae8329-5cd9-4e51-9128-818acb23ffd5.png)

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
I have no precisely replicate-able commands but when downloading some large channels with sponsorblock enabled I get hit with time outs and it also seems occasionally sponsorblock is just not reachable by yt-dlp
```

**Comment by pukkandan** [comment]
Remove ignoreerrors=True from the options

**Comment by porjo** [comment]
Sponsorblock API seems to be down at the moment which brought me here.

@Glynax  when sponsorblock isn't available the video does still download like you've described, however I notice yt-dlp will exit with non zero return code. Could your script be modified to check for that and take action accordingly?

**Comment by jmbannon** [comment]
it calls yt-dlp via python api so can't read exit codes unfortunately

**Comment by pukkandan** [comment]
@jmbannon See my answer. You are specifically asking yt-dlp to ignore errors. Otherwise, yt-dlp wouldn't add the video to archive
