### ISSUE TITLE
add extractor in YoutubeDL

### ISSUE THREAD

**Issue by Nikola2222** [yt-dlp/yt-dlp#5325]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.10.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I want to add my extractor in YoutubeDL
```python 
from yt_dlp import YoutubeDL
from .animevost import AnimevostIE
params = {'extract_flat': 'in_playlist',
          'verbose': True}
url = 'https://v2.vost.pw/tip/tv/2884-futoku-no-guild.html'
with YoutubeDL(params) as ytdl:
    ytdl.add_info_extractor(AnimevostIE())
    ytdl_info = ytdl.extract_info(url, download=False)
```
I get an error "Unsupported URL": 
<details><summary>output</summary>

```
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.10.04 [4e0511f] (pip) API
[debug] Python 3.9.2 (CPython 64bit) - Linux-5.10.0-18-amd64-x86_64-with-glibc2.31 (glibc 2.31)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.3.4-0, ffprobe 4.3.4-0, phantomjs 139936841148352, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.9.7, brotli-1.0.9, certifi-2020.06.20, mutagen-1.45.1, pyxattr-0.7.2, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1690 extractors
[debug] [generic] Extracting URL: https://v2.vost.pw/tip/tv/2884-futoku-no-guild.html
[generic] 2884-futoku-no-guild: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] 2884-futoku-no-guild: Extracting information
[debug] Looking for Brightcove embeds
[debug] Looking for embeds
ERROR: Unsupported URL: https://v2.vost.pw/tip/tv/2884-futoku-no-guild.html
```

</details>

But if I add ie_key to extract_info function
```python
    ytdl_info = ytdl.extract_info(url, download=False, ie_key=AnimevostIE.ie_key())
```
<details>
<summary>Changed code</summary>

```python
from yt_dlp import YoutubeDL
from .animevost import AnimevostIE
params = {'extract_flat': 'in_playlist',
          'verbose': True}
url = 'https://v2.vost.pw/tip/tv/2884-futoku-no-guild.html'
with YoutubeDL(params) as ytdl:
    ytdl.add_info_extractor(AnimevostIE())
    ytdl_info = ytdl.extract_info(url, download=False, ie_key=AnimevostIE.ie_key())
```

</details>
works without errors
<details>
<summary>output </summary>

```
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.10.04 [4e0511f] (pip) API
[debug] Python 3.9.2 (CPython 64bit) - Linux-5.10.0-18-amd64-x86_64-with-glibc2.31 (glibc 2.31)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.3.4-0, ffprobe 4.3.4-0, phantomjs 139640679077824, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.9.7, brotli-1.0.9, certifi-2020.06.20, mutagen-1.45.1, pyxattr-0.7.2, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1690 extractors
[debug] [Animevost] Extracting URL: https://v2.vost.pw/tip/tv/2884-futoku-no-guild.html
[Animevost] 2884: Downloading webpage
[download] Downloading playlist: Развращённая гильдия / Futoku no Guild [1-3 из 12] [4 серия - 26 октября]
[Animevost] Playlist Развращённая гильдия / Futoku no Guild [1-3 из 12] [4 серия - 26 октября]: Downloading 3 videos of 3
[debug] The information of all playlist entries will be held in memory
[download] Downloading video 1 of 3
[download] Downloading video 2 of 3
[download] Downloading video 3 of 3
[download] Finished downloading playlist: Развращённая гильдия / Futoku no Guild [1-3 из 12] [4 серия - 26 октября]
```

</details>

Why is there an error in the code without ie_key?
Is there another way to add an extractor in YoutubeDL?

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by dirkf** [comment]
1. Read the [Manual](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#user-content-adding-support-for-a-new-site).
2. yt-dlp doesn't know that your imported module is an extractor for the given URL unless you tell it, either as described in the Manual, or as you did with `ie_key=...`.

**Comment by Nikola2222** [comment]
Found a solution, you need to add 'allow_extractors' to the parameters.

**Comment by dirkf** [comment]
`allowed_extractors`, or `--use-extractors ...` in the CLI.

That's just another way of doing what you already did with `ie_key=...`.

If you want to use extractors in addition to yours, you should add `default` to the list passed as `allowed_extractors`.

**Comment by pukkandan** [comment]
Since you did not show extractor code, I can only assume that it's implemented correctly and has either a `_VALID_URL`/`suitable` defined. In that case, the issue is that your extractor is being added after `GenericIE` and so will never be triggered. Try this:

```py
with YoutubeDL(params, False) as ytdl:
    ytdl.add_info_extractor(AnimevostIE)
    ytdl.add_default_info_extractors()
    ytdl_info = ytdl.extract_info(url, download=False)
```

If this does not work, show a minimum reproducible code of the extractor

**Comment by Nikola2222** [comment]
> In that case, the issue is that your extractor is being added after GenericIE and so will never be triggered.

```
{..., 'Generic': <class 'yt_dlp.extractor.lazy_extractors.GenericIE'>, 'Animevost': <class 'animevost.AnimevostIE'>}
```
My extractor is indeed after `GenericIE`. Everything turned out to be logical.
> Try this:
```
[debug] Loaded 1690 extractors
Traceback (most recent call last):
  File "/home/nikola/python/anime/utils.py", line 69, in <module>
    ytdl_info = ytdl.extract_info('https://v2.vost.pw/tip/tv/2884-futoku-no-guild.html', download=False)
  File "/home/nikola/.local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1466, in extract_info
    return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
  File "/home/nikola/.local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 776, in get_info_extractor
    ie = get_info_extractor(ie_key)()
  File "/home/nikola/.local/lib/python3.9/site-packages/yt_dlp/extractor/__init__.py", line 42, in get_info_extractor
    return getattr(extractors, f'{ie_name}IE')
AttributeError: module 'yt_dlp.extractor.extractors' has no attribute 'AnimevostIE'
```
But if you add parentheses:
```python
    ytdl.add_info_extractor(AnimevostIE()) #such a small thing causes an error
```
then it works fine. I think the issue is solved. Thanks.
