### ISSUE TITLE
Sponsorblock API does not need to be queried e.g. when doing 

### ISSUE THREAD

**Issue by stdedos** [yt-dlp/yt-dlp#5327]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.10.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

If I run the command:

```bash
yt-dlp --sponsorblock-mark all --download-archive ~/.yt-archive.txt --compat-options filename --no-clean-infojson -S ext --write-subs https://www.youtube.com/watch\?v=-5wpm-gesOY --list-subs
```

There is technically no need to download the Sponsorblock segments, since we won't go into downloading of the video anyway.

I understand that I could've skipped listing the argument, but most of the command (before `--write-subs`) is a bash alias command (and hence, internally expanded by the shell).

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
The segments are also added to info-json, can be printed using --print etc. So it needs to be fetched even when skipping download.

**Comment by pukkandan** [comment]
> but most of the command (before `--write-subs`) is a bash alias command (and hence, internally expanded by the shell).

This is why `--no-sponsorblock` option is provided. Adding this latter in the command will override the older option

**Comment by stdedos** [comment]
I see! Thank you for your suggestion 😃
