### ISSUE TITLE
vod.tvp.pl broken after redesign (new url schemes)

### ISSUE THREAD

**Issue by selfisekai** [yt-dlp/yt-dlp#5328]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.10.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Poland

### Provide a description that is worded well enough to be understood

after the redesign there are new URLs for both the series and episodes. the generic extractor doesn't handle them (on the example it downloads some 43 seconds trailer for the series).

series:
old: https://vod.tvp.pl/website/ranczo,1667874
new: https://vod.tvp.pl/seriale,18/ranczo-odcinki,316445

series episodes:
old: https://vod.tvp.pl/video/czas-honoru,i-seria-odc-13,194536
new: https://vod.tvp.pl/seriale,18/czas-honoru-odcinki,292065/odcinek-13,S01E13,313867

standalone movies:
old: https://vod.tvp.pl/website/ukrainski-sluga-narodu,51640041
new: https://vod.tvp.pl/filmy-dokumentalne,163/ukrainski-sluga-narodu,339667

the website seems to be more restrictive to region lock than the APIs we use, as I can download the episodes and standalones from NL. the series extractor is broken for everything, even from PL IPs, though it is freely available in NL as it's just metadata.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['--no-check-certificate', '-v', 'https://vod.tvp.pl/seriale,18/ranczo-odcinki,316445']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.10.04 [4e0511f27] (source)
[debug] Lazy loading extractors is disabled
[debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
[debug] Git HEAD: 2530b68d4
[debug] Python 3.10.8 (CPython 64bit) - Linux-5.15.73-0-lts-x86_64-with 
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 5.1.2 (setts), ffprobe 5.1.2
[debug] Optional libraries: Crypto-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {'https': '127.0.0.1:8080'}
[debug] Loaded 1700 extractors
[debug] [generic] Extracting URL: https://vod.tvp.pl/seriale,18/ranczo-odcinki,316445
[generic] ranczo-odcinki,316445: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] ranczo-odcinki,316445: Extracting information
[debug] Looking for embeds
[debug] Identified a JSON LD
[debug] [generic] Extracting URL: https://r.dcs.redcdn.pl/file/o2/TVP/video_trailer/c33e61d40cae4025b43f9dae6e62631f.mp4#__youtubedl_smuggle=%7B%22force_videoid%22%3A+%22ranczo-odcinki%2C316445%22%2C+%22to_generic%22%3A+true%2C+%22http_headers%22%3A+%7B%22Referer%22%3A+%22https%3A%2F%2Fvod.tvp.pl%2Fseriale%2C18%2Franczo-odcinki%2C316445%22%7D%7D
[generic] ranczo-odcinki,316445: Downloading webpage
[redirect] Following redirect to https://n-6-5.dcs.redcdn.pl/file/o2/TVP/video_trailer/c33e61d40cae4025b43f9dae6e62631f.mp4
[debug] [generic] Extracting URL: https://n-6-5.dcs.redcdn.pl/file/o2/TVP/video_trailer/c33e61d40cae4025b43f9dae6e62631f.mp4#__youtubedl_smuggle=%7B%22force_videoid%22%3A+%22ranczo-odcinki%2C316445%22%7D
[generic] ranczo-odcinki,316445: Downloading webpage
[debug] Identified a direct video link
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] ranczo-odcinki,316445: Downloading 1 format(s): mp4
[debug] Invoking http downloader on "https://n-6-5.dcs.redcdn.pl/file/o2/TVP/video_trailer/c33e61d40cae4025b43f9dae6e62631f.mp4"
[download] Ranczo [ranczo-odcinki,316445].mp4 has already been downloaded
[download] 100% of   16.62MiB
```

**Comment by selfisekai** [comment]
this API stinks enough for me to say it has something to do with Atende Software, as I've seen very similar structures with ID replacement/multiple ID systems in player.pl and ninateka.pl before, also coming together with their new frontends where they also were killing non-DRM access together with these changes.

to be checked: extraction with the new APIs, does the website use DRM now?

the website uses this API that we can also use to resolve Atende IDs to the TVP ones: https://vod.tvp.pl/api/products/vods/318284?lang=pl&platform=BROWSER

also for reference:
series metadata: https://vod.tvp.pl/api/products/vods/serials/273907?lang=pl&platform=BROWSER
season list: https://vod.tvp.pl/api/products/vods/serials/273907/seasons?lang=pl&platform=BROWSER
season episodes: https://vod.tvp.pl/api/products/vods/serials/273907/seasons/313852/episodes?lang=pl&platform=BROWSER

the Android app was using a different API but they released a redesign for it too: https://play.google.com/store/apps/details?id=com.tvp.vodtv.mobile, so I'm guessing it also switches it to this API.

**Comment by dirkf** [comment]
From the UK, (eg) `318284` --> `tvp:62209460` --> https://s.tvp.pl/files/player/video/material_niedostepny.mp4, which is a geo-block information video; same result with `--geo-bypass-country PL`. However this may be expected.

**Comment by selfisekai** [comment]
hmm, this is true for the ID you linked for me too, but e.g. `345139` -> `tvp:9845317` seems to work from PL, NL and even CA, even though the web doesn't allow me to watch that from NL, and the new VOD API returns this:
```json
"countries": [
	{
		"id": 92,
		"key": "polska",
		"name": "Polska"
	}
]
```

I finally got a browser profile with PL proxy setup. this is how the web app gets format, and this one indeed gets geoblocked from NL: https://vod.tvp.pl/api/products/345139/videos/playlist?platform=BROWSER&videoType=MOVIE. seems like a bonus to the dual-ID system is 2 separate geoblocks that are inconsistent.

to sum up the extraction methods I can list, other than this new API, all working for this ID from NL:
- ancient (first extractor): https://www.tvp.pl/pub/stat/videofileinfo?video_id=9845317
- TVPlayer v1 (still used in production in non-fancy places): https://www.tvp.pl/sess/tvplayer.php?object_id=9845317
- TVPlayer v2 iframe (JSON inside): https://www.tvp.pl/sess/TVPlayer2/embed.php?ID=9845317
- TVPlayer v2 JSONP (what yt-dlp uses currently, and seemingly preferred by TVP currently as their newest toy, swipeto.pl uses it): https://www.tvp.pl/sess/TVPlayer2/api.php?id=9845317&@method=getTvpConfig&@callback=jebacpis
I can also look on the [TVP Android apps](https://play.google.com/store/apps/developer?id=TVP+S.A.). I'm pretty sure the TVP.info had its own API, but I don't have the URLs written down

anyway, I guess we'll have to add a check like `any(('material_niedostepny.mp4' in format['url'] for format in formats))`.
