### ISSUE TITLE
How to Download Youtube Restricted Videos

### ISSUE THREAD

**Issue by sizzlingkenny** [yt-dlp/yt-dlp#5332]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.10.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Hello there I want to download youutbe videos which has some kind of restrictions and I'm not able to download them, I'm using this command for JSON over browser **`echo shell_exec("yt-dlp https://www.youtube.com/watch?v=WmFh_Ar1U5c -j");`** but the page goes blank same thing happening to many different videos, how to download such type of videos and what command should I write?

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp -vU https://www.youtube.com/watch?v=WmFh_Ar1U5c
[debug] Command-line config: ['-vU', 'https://www.youtube.com/watch?v=WmFh_Ar1U5c']
[debug] Encodings: locale ISO-8859-1, fs iso8859-1, pref ISO-8859-1, out ISO-8859-1, error ISO-8859-1, screen ISO-8859-1
[debug] yt-dlp version 2022.10.04 [4e0511f] (zip)
[debug] Python 3.7.13 (CPython 64bit) - Linux-5.4.0-88-generic-x86_64-with-Ubuntu-20.04-focal (glibc 2.29)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.2.7, ffprobe 4.2.7
[debug] Optional libraries: certifi-2019.11.28, sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Loaded 1690 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.10.04, Current version: 2022.10.04
yt-dlp is up to date (2022.10.04)
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=WmFh_Ar1U5c
[youtube] WmFh_Ar1U5c: Downloading webpage
[youtube] WmFh_Ar1U5c: Downloading android player API JSON
ERROR: [youtube] WmFh_Ar1U5c: Video unavailable. This video is not available
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 672, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/youtube.py", line 3813, in _real_extract
    self.raise_no_formats(reason, expected=True)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 1154, in raise_no_formats
    raise ExtractorError(msg, expected=expected, video_id=video_id)
```

**Comment by nicolaasjan** [comment]
If you enter that URL in the [YouTube region restriction checker](https://polsy.org.uk/stuff/ytrestrict.cgi?ytid=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DWmFh_Ar1U5c&auth=a7b7658ee5cbb4cf485df0d89b985cce), you'll see that the video is only available in a few countries.

**Comment by pukkandan** [comment]
yt-dlp cannot download anything you cannot access in browser

**Comment by sizzlingkenny** [comment]
I can access those videos on my browser, Its because my server is in the block list, can I use the proxy of one of the allowed countries to get those videos? If yes then how to pass proxy in the request?

**Comment by pukkandan** [comment]
--proxy

**Comment by sizzlingkenny** [comment]
Thanks for your reply, but I'm not that much expert to add an override, If there is any simple steps to follow to solve this problem then please do let me know.
