### ISSUE TITLE
Delete duplicities and/or get unique values from a multi-value field - how ?

### ISSUE THREAD

**Issue by John01Smith** [yt-dlp/yt-dlp#5335]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.10.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

How to **delete duplicities** and/or **get unique (set of) values** from a multi-value classification field - typically e.g. 'Keywords', 'Categories', 'Tags', ..., 
where the field contains string with space/' ' separated multiple non-unique values in a form like 'word1 word2 word3 word1 word4 ...' ?

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by John01Smith** [comment]
While waiting for GitHub account unflagging, I opened this question on **Reddit** as well:
[https://www.reddit.com/r/youtubedl/comments/ydqn3k/ytdlp_delete_duplicities_andor_get_unique_values/](https://www.reddit.com/r/youtubedl/comments/ydqn3k/ytdlp_delete_duplicities_andor_get_unique_values/)

Some comments to the topic are there therefore.

**Comment by pukkandan** [comment]
https://www.reddit.com/r/youtubedl/comments/ydqn3k/comment/iu44uop

**Comment by John01Smith** [comment]
It works, thank you. :-)
