### ISSUE TITLE
XMP:MOV-XMP:Subject metadata field/tag - write to .mp4 file - how ?

### ISSUE THREAD

**Issue by John01Smith** [yt-dlp/yt-dlp#5336]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.10.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

---

How to write **XMP:XMP-dc:MOV-XMP:Subject** metadata field/tag to a .**MP4** video file during download ?

---

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
how is this related to yt-dlp?

**Comment by John01Smith** [comment]
The specified field/tag is useful for storing **classification metadata** for downloaded **videos**, like `'Categories', 'Tags', 'Keywords'`.

While being similar to these tags is is better by being one of the few tags that properly support **multiple values** as a **list-type tag** storing individual values separately without the need to parse them on the level of tag value (as opposed to storing multiple values just as one long string with separators which is the case for most other tags). 
In effect it should mean better/cleaner/safer storing of the classification metadata.

That's why I need it and so I would like to know, whether it is possible to write this tag using **yt-dlp**.

---
Adding links to related questions on **Reddit**:

[https://www.reddit.com/r/youtubedl/comments/ydqrbo/ytdlp_xmpmovxmpsubject_metadata_fieldtag_write_to/](https://www.reddit.com/r/youtubedl/comments/ydqrbo/ytdlp_xmpmovxmpsubject_metadata_fieldtag_write_to/)

[https://www.reddit.com/r/ffmpeg/comments/yhggqf/xmpxmpdcmovxmpsubject_metadata_tag_write_to_mp4/](https://www.reddit.com/r/ffmpeg/comments/yhggqf/xmpxmpdcmovxmpsubject_metadata_tag_write_to_mp4/)

Thank you

**Comment by pukkandan** [comment]
> [reddit.com/r/ffmpeg/comments/yhggqf/xmpxmpdcmovxmpsubject_metadata_tag_write_to_mp4](https://www.reddit.com/r/ffmpeg/comments/yhggqf/xmpxmpdcmovxmpsubject_metadata_tag_write_to_mp4/)

If it is not possible with ffmpeg, then there is no way to do it with yt-dlp

**Comment by John01Smith** [comment]
**Not possible/supported** with/by `FFmpeg` according to **[u/Murky-Sector](https://www.reddit.com/user/Murky-Sector/)**.

---
Submitted the question to **[ffmpeg-user@ffmpeg.org](mailto:ffmpeg-user@ffmpeg.org)** mailing-list as well, waiting for answers.

**Comment by Lesmiscore** [comment]
> If it is not possible with ffmpeg, then there is no way to do it with yt-dlp

**Comment by John01Smith** [comment]
No answer/response in the **[ffmpeg-user@ffmpeg.org](mailto:ffmpeg-user@ffmpeg.org)** mailing-list.
