### ISSUE TITLE
[instagram] Error logging in, cannot download Instagram Highlights

### ISSUE THREAD

**Issue by AleksFimin** [yt-dlp/yt-dlp#5338]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.10.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Uzbekistan

### Provide a description that is worded well enough to be understood

I can't get information about instagram highlits. If you specify --cookies-from-browser, everything is fine

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp -j -vU https://www.instagram.com/stories/highlights/17945585140590250/ --username "my gmail" --password "my password"
[debug] Command-line config: ['-j', '-vU', 'https://www.instagram.com/stories/highlights/17921449453583708/', '--username', 'PRIVATE', '--password', 'PRIVATE']
[debug] Encodings: locale cp1251, fs utf-8, pref cp1251, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.10.04 [4e0511f] (win32_exe)
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg n5.0.1-5-g240d82f26e-20220614 (setts), ffprobe n5.0.1-5-g240d82f26e-20220614
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1690 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.10.04, Current version: 2022.10.04
yt-dlp is up to date (2022.10.04)
[instagram:story] Downloading login webpage
ERROR: 17921449453583708: An extractor error has occurred. (caused by KeyError('config')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 670, in extract
  File "yt_dlp\extractor\common.py", line 576, in initialize
  File "yt_dlp\extractor\instagram.py", line 67, in _perform_login
KeyError: 'config'
```

**Comment by bashonly** [comment]
Highlights are not accessible when not logged in (via web browser or yt-dlp).

This is an issue with logging in. See also: #5154, although this error is new.

**Comment by AleksFimin** [comment]
Is it possible to authorize automatically?

**Comment by bashonly** [comment]
> Is it possible to authorize automatically?

since login w/credentials seems to be broken for this extractor currently, the only way is to use `--cookies-from-browser` or `--cookies`

**Comment by AleksFimin** [comment]
And the cookie is temporary, it turns out it will need to update manually the cookie after some time?

**Comment by bashonly** [comment]
`--cookies-from-browser` will extract the instagram cookies from your browser's cookie storage each time you run yt-dlp with that option. If you have logged into instagram or browsed instagram while logged in with your browser recently, the cookies should be up-to-date.

I would caution you to use your login cookies only when absolutely necessary / sparingly, since usage of yt-dlp can be detected by instagram and it could lead to an account suspension or ban.

**Comment by AleksFimin** [comment]
Thanks for the advice, but isn't there a way to download a lot of videos automatically without getting blocked?

**Comment by bashonly** [comment]
Closing in favor of #5154
