### ISSUE TITLE
infojson not affected by filters

### ISSUE THREAD

**Issue by elfein727** [yt-dlp/yt-dlp#5350]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.10.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Currently, when applying filters via the `-f` option in conjunction with `--write-info-json`, the outputted formats in the infojson still contain formats that should be filtered out.

The command
```
yt-dlp --skip-download -f "bv[height<=720]" --no-playlist --write-info-json https://youtu.be/-CVLgseB5aE
```
will generate an infojson containing the following:
```js
        {
            ...,
            "height": 720,
            ...,
            "format": "247 - 1280x720 (720p)",
            "resolution": "1280x720",
        },
        // Should have been filtered out
        {
            ...,
            "height": 1080,
            ...,
            "format": "399 - 1920x1080 (1080p)",
            "resolution": "1920x1080",
        },
```
The expectation is that this infojson will not contain any formats where the height is greater than `720` as specified in the filter.
This could be fixed by serializing to json the filtered data rather than the whole data, however, the current behavior should remain the same to be less confusing. Instead, if `-f` was positional and affected what came either before or after, that might make things more featureful while still being intuitive.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--skip-download', '-f', 'bv[height<=720]', '--no-playlist', '--write-info-json', 'https://youtu.be/-CVLgseB5aE']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.10.04 [4e0511f27] API
[debug] Lazy loading extractors is disabled
[debug] Python 3.8.10 (CPython 64bit) - Linux-6.0.3-x64v1-xanmod1-x86_64-with-glibc2.29 (glibc 2.31)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.2.7, ffprobe 4.2.7
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1697 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.10.04, Current version: 2022.10.04
yt-dlp is up to date (2022.10.04)
[debug] [youtube] Extracting URL: https://youtu.be/-CVLgseB5aE
[youtube] -CVLgseB5aE: Downloading webpage
[youtube] -CVLgseB5aE: Downloading android player API JSON
[debug] Loading youtube-nsig.4bbf8bdb from cache
[debug] [youtube] Decrypted nsig Gb3S3zgBsHHplx62mD => mYDvp6K91vpxNA
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[info] -CVLgseB5aE: Downloading 1 format(s): 302
[info] Writing video metadata as JSON to: Pikamee's 'Natural Beauty'... [-CVLgseB5aE].info.json
```

**Comment by elfein727** [comment]
Alternatively, there could be a new field on the infojson called `filtered_formats` that contains only formats that passed the format filter.

**Comment by pukkandan** [comment]
There is no "selected formats". There will always only be only one selected format per infojson. The data of those format is directly written in the root of the infojson. See the keys `format_id`,`url` etc at the root.

**Comment by elfein727** [comment]
You are absolutely correct. Is there documentation on the fields in the infojson? Thank you very much!

**Comment by pukkandan** [comment]
https://github.com/yt-dlp/yt-dlp#output-template documents most of them (but not all)
