### ISSUE TITLE
--max-filesize with video quality alternatives does not post-process correctly

### ISSUE THREAD

**Issue by digitalheir** [yt-dlp/yt-dlp#5353]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [x] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.10.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

```
$ yt-dlp --max-filesize 20m -f "bv*+ba/b" https://www.youtube.com/watch?v=iogcY_4xGjo

[youtube] iogcY_4xGjo: Downloading webpage
[youtube] iogcY_4xGjo: Downloading android player API JSON
[info] iogcY_4xGjo: Downloading 1 format(s): 248+251
[download] Destination: $1 vs $1,000,000 Hotel Room! [iogcY_4xGjo].f248.webm
[download] File is larger than max-filesize (30418893 bytes > 20971520 bytes). Aborting.

[download] Destination: $1 vs $1,000,000 Hotel Room! [iogcY_4xGjo].f251.webm
[download] 100% of   14.30MiB in 00:00:00 at 18.99MiB/s
```

```
$ ls -lh

-rw-rw-r-- 1 20M Oct 25 14:36 '$1 vs $1,000,000 Hotel Room! [iogcY_4xGjo].f248.webm.part'
-rw-rw-r-- 1 15M Oct 23 14:02 '$1 vs $1,000,000 Hotel Room! [iogcY_4xGjo].f251.webm'
```

I would expect:

1. '$1 vs $1,000,000 Hotel Room! [iogcY_4xGjo].f248.webm.part' to be deleted
2. '$1 vs $1,000,000 Hotel Room! [iogcY_4xGjo].f251.webm' to be named ''$1 vs $1,000,000 Hotel Room! [iogcY_4xGjo].webm' (without the `.f251` qualifier)

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--max-filesize', '20m', '-f', 'bv*+ba/b', 'https://www.youtube.com/watch?v=iogcY_4xGjo']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.10.04 [4e0511f] (zip)
[debug] Python 3.8.10 (CPython 64bit) - Linux-5.4.0-92-generic-x86_64-with-glibc2.29 (glibc 2.31)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.2.7, ffprobe 4.2.7
[debug] Optional libraries: certifi-2019.11.28, sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Loaded 1690 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.10.04, Current version: 2022.10.04
yt-dlp is up to date (2022.10.04)
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=iogcY_4xGjo
[youtube] iogcY_4xGjo: Downloading webpage
[youtube] iogcY_4xGjo: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[info] iogcY_4xGjo: Downloading 1 format(s): 248+251
[debug] Invoking http downloader on "https://rr5---sn-5hnekn7d.googlevideo.com/videoplayback?expire=1666723370&ei=ytlXY-nmIYn81wL3yYewCg&ip=5.189.170.112&id=o-AEUT7nqPGDfM9FdPZ4ngeImTwL4E3XoHGvKo7s_UV1rq&itag=248&source=youtube&requiressl=yes&mh=kt&mm=31%2C26&mn=sn-5hnekn7d%2Csn-4g5lznez&ms=au%2Conr&mv=m&mvi=5&pl=24&initcwndbps=456250&spc=yR2vp0M2mrZtrAXvb2-zNQxSabl7PeM&vprv=1&svpuc=1&mime=video%2Fwebm&gir=yes&clen=266027434&dur=940.273&lmt=1666554224227702&mt=1666701460&fvip=5&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=5535434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRgIhAOqWqbpMeS0ruEHh9iBSvvFFYBrimYltg5CFlKvV10sZAiEAnbIxvZX7ZwnnfPyKStjVxD3v-_a69YI_0WVzOXqzbxo%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhAI1K38wNNqqiiR-D7IwZhtMEq38RO6kaHOS8ifQjBnYxAiB5Xq1njRLES7KKtBM7tr6w0P5GfuJlcRYsT_vucfQNog%3D%3D"
[download] Destination: $1 vs $1,000,000 Hotel Room! [iogcY_4xGjo].f248.webm
[download] File is larger than max-filesize (30200217 bytes > 20971520 bytes). Aborting.

[debug] Invoking http downloader on "https://rr5---sn-5hnekn7d.googlevideo.com/videoplayback?expire=1666723370&ei=ytlXY-nmIYn81wL3yYewCg&ip=5.189.170.112&id=o-AEUT7nqPGDfM9FdPZ4ngeImTwL4E3XoHGvKo7s_UV1rq&itag=251&source=youtube&requiressl=yes&mh=kt&mm=31%2C26&mn=sn-5hnekn7d%2Csn-4g5lznez&ms=au%2Conr&mv=m&mvi=5&pl=24&initcwndbps=456250&spc=yR2vp0M2mrZtrAXvb2-zNQxSabl7PeM&vprv=1&svpuc=1&mime=audio%2Fwebm&gir=yes&clen=14999868&dur=940.301&lmt=1666526533991500&mt=1666701460&fvip=5&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=5532434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRAIgA7H2SBIwNmHO8cuRYCFQR2-uQuCYABi58RT5-rBZsL4CIFtR7BOeR47kpbT0dfW8bK_zs0teRDkMX8qiGzDRZQ0S&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhAI1K38wNNqqiiR-D7IwZhtMEq38RO6kaHOS8ifQjBnYxAiB5Xq1njRLES7KKtBM7tr6w0P5GfuJlcRYsT_vucfQNog%3D%3D"
[download] Destination: $1 vs $1,000,000 Hotel Room! [iogcY_4xGjo].f251.webm
[download] 100% of   14.30MiB in 00:00:00 at 16.19MiB/s
```

**Comment by pukkandan** [comment]
> I would expect:
> 
> 1. '$1 vs $1,000,000 Hotel Room! [iogcY_4xGjo].f248.webm.part' to be deleted
> 2. '$1 vs $1,000,000 Hotel Room! [iogcY_4xGjo].f251.webm' to be named ''$1 vs $1,000,000 Hotel Room! [iogcY_4xGjo].webm' (without the `.f251` qualifier)

Why would you expect that? That is not how the option is documented. All it does is stop the download when the threshold is reached, nothing more, nothing less.

**Comment by dirkf** [comment]
Maybe OP wants something like `-f '(bv*+ba/b/ba)[filesize<20M]', which selects `133 - 426x240 (240p)+251 - audio only (medium)` (filesize_approx: 34422079).

**Comment by digitalheir** [comment]
> Why would you expect that? 

I suppose I misunderstood this option.

It makes more sense to me that the program will cycle to a lower quality if the download exceeds the maximum file size, and deletes the larger file. I don't really understand the point of the option otherwise. Why would any user want a half-downloaded file? Especially if it's actually two files, and one is an incomplete stream.

> That is not how the option is documented. All it does is stop the download when the threshold is reached, nothing more, nothing less.

Documentation on the GitHub main page says:

```
--max-filesize SIZE             Do not download any videos larger than SIZE,                                e.g. 50k or 44.6M
```

This is ambiguous, I'd say. Something like 'Abort download once the file size exceeds SIZE, leaving source files as is' would be clearer to me.

@dirkf Does this option work when the filesize is not known ahead of time? It is not possible in, for instance, Twitter I think.

**Comment by dirkf** [comment]
A filesize needs to have been extracted from the metadata before the download. This is true in your example but may not be for other sites.

Sometimes `filesize_approx` may be extracted instead of `filesize`. Arguably a filter on `filesize_approx` should match `filesize` if there is no `filesize_approx`, which doesn't seem to happen.

**Comment by pukkandan** [comment]
> This is ambiguous, I'd say. Something like 'Abort download once the file size exceeds SIZE, leaving source files as is' would be clearer to me.

Will do

> Why would any user want a half-downloaded file? Especially if it's actually two files, and one is an incomplete stream.

I have no idea either. But since that's how the option has been for years, I assume the devs at the time there was a reason for implementing it that way.

**Comment by pukkandan** [comment]
The docs change was made in 46d09f87072e112c363f4a573966d8e48a788562, forgot to close this.
