### ISSUE TITLE
Vimeo: RegexNotFoundError('Unable to extract %s' % _name)

### ISSUE THREAD

**Issue by richlv** [yt-dlp/yt-dlp#5361]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.10.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Latvia

### Provide a description that is worded well enough to be understood

Attempting to download a video that works in a browser fails (no credentials required).
Searching existing bugreports did not reveal anything matching.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
> yt-dlp -vU 'https://player.vimeo.com/video/762862842'
[debug] Command-line config: ['-vU', 'https://player.vimeo.com/video/762862842']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.10.04 [4e0511f] (zip)
[debug] Python 3.10.7 (CPython 64bit) - Linux-6.0.1-1-default-x86_64-with-glibc2.36 (glibc 2.36)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.4.3 (fdk,setts), ffprobe 4.4.3
[debug] Optional libraries: certifi-2021.10.08, sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Loaded 1690 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.10.04, Current version: 2022.10.04
yt-dlp is up to date (2022.10.04)
[debug] [vimeo] Extracting URL: https://player.vimeo.com/video/762862842
[vimeo] 762862842: Downloading webpage
ERROR: [vimeo] 762862842: Unable to extract info section; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/usr/bin/yt-dlp/yt_dlp/extractor/common.py", line 672, in extract
    ie_result = self._real_extract(url)
  File "/usr/bin/yt-dlp/yt_dlp/extractor/vimeo.py", line 872, in _real_extract
    config = self._parse_json(self._search_regex(
  File "/usr/bin/yt-dlp/yt_dlp/extractor/common.py", line 1224, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
```

**Comment by bashonly** [comment]
regex pattern for config JSON needs a tweak:

```diff
diff --git a/yt_dlp/extractor/vimeo.py b/yt_dlp/extractor/vimeo.py
index 25d2f200f..f369825b0 100644
--- a/yt_dlp/extractor/vimeo.py
+++ b/yt_dlp/extractor/vimeo.py
@@ -869,8 +869,8 @@ def _real_extract(self, url):
             raise
 
         if '://player.vimeo.com/video/' in url:
-            config = self._parse_json(self._search_regex(
-                r'\bconfig\s*=\s*({.+?})\s*;', webpage, 'info section'), video_id)
+            config = self._search_json(
+                r'(?:\bconfig|window\.playerConfig)\s*=', webpage, 'info section', video_id)
             if config.get('view') == 4:
                 config = self._verify_player_video_password(
                     redirect_url, video_id, headers)
```

**Comment by walksonair** [comment]
> regex pattern for config JSON needs a tweak:
> 
> ```diff
> diff --git a/yt_dlp/extractor/vimeo.py b/yt_dlp/extractor/vimeo.py
> index 25d2f200f..f369825b0 100644
> --- a/yt_dlp/extractor/vimeo.py
> +++ b/yt_dlp/extractor/vimeo.py
> @@ -869,8 +869,8 @@ def _real_extract(self, url):
>              raise
>  
>          if '://player.vimeo.com/video/' in url:
> -            config = self._parse_json(self._search_regex(
> -                r'\bconfig\s*=\s*({.+?})\s*;', webpage, 'info section'), video_id)
> +            config = self._search_json(
> +                r'(?:\bconfig|window\.playerConfig)\s*=', webpage, 'info section', video_id)
>              if config.get('view') == 4:
>                  config = self._verify_player_video_password(
>                      redirect_url, video_id, headers)
> ```

This worked in fixing the issue for me with `yt-dlp 2022.10.04`. Thanks for the fix!

**Comment by Tom003** [comment]
> > regex pattern for config JSON needs a tweak:
> > ```diff
> > diff --git a/yt_dlp/extractor/vimeo.py b/yt_dlp/extractor/vimeo.py
> > index 25d2f200f..f369825b0 100644
> > --- a/yt_dlp/extractor/vimeo.py
> > +++ b/yt_dlp/extractor/vimeo.py
> > @@ -869,8 +869,8 @@ def _real_extract(self, url):
> >              raise
> >  
> >          if '://player.vimeo.com/video/' in url:
> > -            config = self._parse_json(self._search_regex(
> > -                r'\bconfig\s*=\s*({.+?})\s*;', webpage, 'info section'), video_id)
> > +            config = self._search_json(
> > +                r'(?:\bconfig|window\.playerConfig)\s*=', webpage, 'info section', video_id)
> >              if config.get('view') == 4:
> >                  config = self._verify_player_video_password(
> >                      redirect_url, video_id, headers)
> > ```
> 
> This worked in fixing the issue for me with `yt-dlp 2022.10.04`. Thanks for the fix!

How do I apply this fix if I installed yt-dlp with brew? will this fix be released in a new version soon?

**Comment by walksonair** [comment]
> How do I apply this fix if I installed yt-dlp with brew? will this fix be released in a new version soon?

For my Mac the file is located at `/usr/local/Cellar/yt-dlp/2022.10.4/libexec/lib/python3.10/site-packages/yt_dlp/extractor/vimeo.py`. Open with a text editor and then search for the red text and replace it with the green text. 

If that file path doesn't work out for you @Tom003, then do a find in Finder for `Vimeo.py` and make sure to ensure `System files` `are included`...best of luck!

**Comment by pukkandan** [comment]
Since it has been solved upstream, it will be automatically fixed in next release

**Comment by Tom003** [comment]
it works, thank you!

**Comment by shimiaoyerin** [comment]
#4005

**Comment by hms54** [comment]
How can I run this fix in Python on a windows PC to test while waiting for the next executable to be compiled?
Python is installed, and I have downloaded the source code zip file, but don't know where to extract the contents of that file so Python can find the program.  Is there a standard location or path that must be used in Windows for Python code?

**Comment by Tom003** [comment]
I think you might want to try installing it with a package manager instead of extracting source: https://github.com/yt-dlp/yt-dlp/wiki/Installation

since you already have python installed, I think pip would the most straightforward.

**Comment by hms54** [comment]
Thanks, Tom.   Clearly, I'm a noob with Python and appreciate any help I can get. 

As per the reference you provided, I installed it using: python3 -m pip install -U yt-dlp.   Destination for the saved files was %LocalAppData%\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\Scripts' which is not on PATH.  

I added that directory to my PATH and edited the vimeo.py file found in the yt-dlp/extractors directory to include the new code mentioned above.  

python -m yt_dlp <url> is the correct syntax to download a video file and it works correctly with player.vimeo.com URLs.   

BTW:  Nothing was working right until I figured out the command to run in Python is yt_dlp, not yt-dlp.

**Comment by VuiMuich** [comment]
This is not in `master` yet, right?

**Comment by Letsplaybar** [comment]
On install current master I get the issue 
`ERROR: [vhx:embed] 2430231: Unable to extract ott data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/extractor/common.py", line 674, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/extractor/vimeo.py", line 1395, in _real_extract
    config_url = self._parse_json(self._search_regex(
  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/extractor/common.py", line 1228, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name) ` 

i used today to install `pip install --force-reinstall https://github.com/yt-dlp/yt-dlp/archive/master.tar.gz ` and get the erorr above.

**Comment by bashonly** [comment]
@Letsplaybar open a new issue and show full verbose log

**Comment by mrzenwiz** [comment]
This is still happening, on two different URLs today. Please reopen the issue or release the fix if there is one.

The first URL:

$ yt-dlp -vU 'https://player.vimeo.com/video/783324308?h=423c8b699e'
[debug] Command-line config: ['-vU', 'https://player.vimeo.com/video/783324308?h=423c8b699e']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2023.01.06 [https://github.com/yt-dlp/yt-dlp/commit/6becd2508c811969259f3f18bfb35630bc4feaed] (zip)
[debug] Python 3.10.6 (CPython x86_64 64bit) - Linux-5.15.0-60-generic-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2
[debug] Optional libraries: secretstorage-3.3.1, sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Loaded 1760 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2023.01.06, Current version: 2023.01.06
yt-dlp is up to date (2023.01.06)
[vimeo] Extracting URL: https://player.vimeo.com/video/783324308?h=423c8b699e
[vimeo] 783324308: Downloading webpage
ERROR: [vimeo] 783324308: Unable to extract info section; please report this issue on https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using yt-dlp -U
File "/home/admar/bin/yt-dlp/yt_dlp/extractor/common.py", line 680, in extract
ie_result = self._real_extract(url)
File "/home/admar/bin/yt-dlp/yt_dlp/extractor/vimeo.py", line 837, in _real_extract
config = self._parse_json(self._search_regex(
File "/home/admar/bin/yt-dlp/yt_dlp/extractor/common.py", line 1228, in _search_regex
raise RegexNotFoundError('Unable to extract %s' % _name)

The second URL:

$ yt-dlp -vU 'https://app.kartra.com/external_video/vimeo/797163741?h=0732af73ce'
[debug] Command-line config: ['-vU', 'https://app.kartra.com/external_video/vimeo/797163741?h=0732af73ce']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2023.01.06 [https://github.com/yt-dlp/yt-dlp/commit/6becd2508c811969259f3f18bfb35630bc4feaed] (zip)
[debug] Python 3.10.6 (CPython x86_64 64bit) - Linux-5.15.0-60-generic-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2
[debug] Optional libraries: secretstorage-3.3.1, sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Loaded 1760 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2023.01.06, Current version: 2023.01.06
yt-dlp is up to date (2023.01.06)
[generic] Extracting URL: https://app.kartra.com/external_video/vimeo/797163741?h=0732af73ce
[generic] 797163741?h=0732af73ce: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] 797163741?h=0732af73ce: Extracting information
[debug] Looking for embeds
[debug] Identified a vimeo embed
[vimeo] Extracting URL: https://player.vimeo.com/video/797163741?h=0732af73ce#__youtubedl_smuggle=%7B%22http_headers%22%3A+%7B%22Referer%22%3A+%22https%3A%2F%2Fapp.kartra.com%2Fexternal_video%2Fvimeo%2F797163741%3Fh%3D0732af73ce%22%7D%7D
[vimeo] 797163741: Downloading webpage
ERROR: [vimeo] 797163741: Unable to extract info section; please report this issue on https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using yt-dlp -U
File "/home/admar/bin/yt-dlp/yt_dlp/extractor/common.py", line 680, in extract
ie_result = self._real_extract(url)
File "/home/admar/bin/yt-dlp/yt_dlp/extractor/vimeo.py", line 837, in _real_extract
config = self._parse_json(self._search_regex(
File "/home/admar/bin/yt-dlp/yt_dlp/extractor/common.py", line 1228, in _search_regex
raise RegexNotFoundError('Unable to extract %s' % _name)

Thank you!

**Comment by pukkandan** [comment]
https://github.com/yt-dlp/yt-dlp/issues/6149
