### ISSUE TITLE
Stream videos directly to mpv without slow ffmpeg (e.g. using native or aria2c)

### ISSUE THREAD

**Issue by fritzrehde** [yt-dlp/yt-dlp#5379]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.10.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Hi, I want to stream youtube videos directly to `mpv`. Until now, I have just been using `mpv`'s builtin support for `yt-dlp`, but the download speeds are very slow compared to `--downloader aria2c` or `native`. Therefore, I tried the naive 
```
yt-dlp "$VIDEOLINK" -o - --downloader native | mpv -
``` 
and the video works perfectly (and downloads much faster), but there is no audio. Is this on purpose? The man page said something about only ffmpeg supporting multiple output streams (probably video and audio). But ffmpeg had the slow download speeds, so I am trying to avoid it for this purpose. Any help would be appreciated! Thanks!

### Provide verbose output that clearly demonstrates the problem

- [x] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [x] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[file] Reading from stdin...
[debug] Command-line config: ['https://www.youtube.com/watch?v=AaUl8VJ2dAc', '-o', '-', '-vU']
[debug] User config "/home/fritz/.config/yt-dlp/config": ['--downloader', 'native', '--downloader', 'dash,m3u8:aria2c', '--format', 'bestvideo[height<=?1080]+bestaudio/best', '--restrict-filenames']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.10.04 [4e0511f] API
[debug] Python 3.10.8 (CPython 64bit) - Linux-6.0.2-arch1-1-x86_64-with-glibc2.36 (glibc 2.36)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 5.1.2 (setts), ffprobe 5.1.2
[debug] Optional libraries: Cryptodome-3.12.0, brotlicffi-1.0.9.2, certifi-2022.09.24, mutagen-1.46.0, secretstorage-3.3.3, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1690 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.10.04, Current version: 2022.10.04
yt-dlp is up to date (2022.10.04)
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=AaUl8VJ2dAc
[youtube] AaUl8VJ2dAc: Downloading webpage
[youtube] AaUl8VJ2dAc: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[info] AaUl8VJ2dAc: Downloading 1 format(s): 248+251
WARNING: You have requested downloading multiple formats to stdout using a downloader other than ffmpeg. The formats will be streamed one after the other
[debug] Invoking http downloader on "https://rr2---sn-hoxu-h0jz.googlevideo.com/videoplayback?expire=1666969295&ei=b5pbY8LcJtOFgAeolquYAg&ip=212.204.102.90&id=o-ANm0DDptGUO-o0EzLFk1nMnh1DayzwePqAv_LCb-IJe9&itag=248&source=youtube&requiressl=yes&mh=97&mm=31%2C29&mn=sn-hoxu-h0jz%2Csn-h0jeener&ms=au%2Crdu&mv=m&mvi=2&pl=19&pcm2=no&gcr=de&initcwndbps=1881250&spc=yR2vp2qqq1uhIGb4TdHDguFA11noDxg&vprv=1&svpuc=1&mime=video%2Fwebm&gir=yes&clen=71678816&dur=271.320&lmt=1666909189526236&mt=1666947199&fvip=3&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=6319224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cpcm2%2Cgcr%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRAIgcTWhfHd_6dnmn5SwxvOcBGax1q7kpJoNqd_RX1gnoNoCID_mmOum-rs8HmrB7zxDLrWDEHRmfrwa_v4BMhVvB2r8&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgDUiSFoOwLztBfRafRRgXwT3tsb2wvcPo48ESJXyIWgUCIQCFq6PVVRvD8zFuVv2yweECDMFP73UkxlL7vjghbCBFKg%3D%3D"
[debug] File locking is not supported. Proceeding without locking
[download] Destination: -
[download]   0.1% of   68.36MiB at   13.00MiB/s ETA 00:05 (+) Video --vid=1 (*) (vp9 1920x1080 25.000fps)
[download]   2.9% of   68.36MiB at   18.84MiB/s ETA 00:03VO: [gpu] 1920x1080 yuv420p
[download] 100% of   68.36MiB in 00:00:01 at 55.64MiB/s
[debug] Invoking http downloader on "https://rr2---sn-hoxu-h0jz.googlevideo.com/videoplayback?expire=1666969295&ei=b5pbY8LcJtOFgAeolquYAg&ip=212.204.102.90&id=o-ANm0DDptGUO-o0EzLFk1nMnh1DayzwePqAv_LCb-IJe9&itag=251&source=youtube&requiressl=yes&mh=97&mm=31%2C29&mn=sn-hoxu-h0jz%2Csn-h0jeener&ms=au%2Crdu&mv=m&mvi=2&pl=19&pcm2=no&gcr=de&initcwndbps=1881250&spc=yR2vp2qqq1uhIGb4TdHDguFA11noDxg&vprv=1&svpuc=1&mime=audio%2Fwebm&gir=yes&clen=4003199&dur=271.341&lmt=1666909234012544&mt=1666947199&fvip=3&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=6318224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cpcm2%2Cgcr%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRAIgU3MPZeolHrCDOEdqjOm4xEiDtJBroZT4V3HOcCTC_58CICJkuRmeRn50QrrYlQg5IHQiDf-Si-MaG1plUloYhnIA&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgDUiSFoOwLztBfRafRRgXwT3tsb2wvcPo48ESJXyIWgUCIQCFq6PVVRvD8zFuVv2yweECDMFP73UkxlL7vjghbCBFKg%3D%3D"
[download] Destination: -
V: 00:00:06 / 00:04:31 (2%) Cache: 265s/69MB

Exiting... (Quit)
```

**Comment by Lesmiscore** [comment]
Read the warning again on log:
> You have requested downloading multiple formats to stdout using a downloader other than ffmpeg. The formats will be streamed one after the other

So far, it's streaming a video-only format and an audio-only format, in this order, because you refused ffmpeg.

Download the full video and play it. That's the "easiest" solution.

**Comment by fritzrehde** [comment]
Ok, I thought there might be another way, that's why I asked. `-f best` sometimes only gives me `720p` instead of `1080p`, so that's not really an option. I guess I'll have to stick to `ffmpeg` for now then.

**Comment by pukkandan** [comment]
There are a few reasons why such a feature is not available:
1. We dont currently have the framework to download audio and video in parallel.
2. aria2c does not allow downloading to stdout afaik
3. Even if these issues were to be solved, we cannot mux the video+audio without ffmpeg. Implementing this is beyond our scope
