### ISSUE TITLE
Basic use of `--replace-in-metadata` option: set `title` to new value

### ISSUE THREAD

**Issue by fritzrehde** [yt-dlp/yt-dlp#5383]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.10.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

How can I use the `--replace-in-metadata` option to set the title of the video to `$TITLE` or whatever other string (I specifically don't understand the regex part from the man page)?

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by fritzrehde** [comment]
I think this roughly works:
```
		yt-dlp.sh \
			--output "$FILE" \
			--replace-in-metadata "title" "%(title)s" "$TITLE" \
                        --embed-metadata \
			"$URL"
```
Is this the way to do what I wanted?
Another point: This also embeds a lot of metadata I am uninterested in, I would like to only embed the title that I changed. Is that possible?

**Comment by pukkandan** [comment]
--parse-metadata " your title: %(title)s"

**Comment by fritzrehde** [comment]
For some reason 
```
		yt-dlp.sh \
			--output "$FILE" \
			--parse-metadata "$TITLE:%(title)s" \
			"$URL"
```
isn't setting the Title metadata value (exiftool can't find a `Title` field once the video is downloaded). Does this support `.webm` videos, exiftool doesn't.

**Comment by pukkandan** [comment]
Show verbose log

**Comment by fritzrehde** [comment]
```
yt-dlp "<youtube link>" --parse-metadata "test metadata:%(title)s"
```
prints `[MetadataParser] Parsed title from 'test metadata': 'test metadata'`, but inspecting the video with exiftool afterwards still doesn't show a `Title`...

**Comment by fritzrehde** [comment]
Do I still need to use `-embed-metadata` or is `--parse-metadata` enough? Maybe that's my mistake?

**Comment by pukkandan** [comment]
> Do I still need to use `-embed-metadata`

Yes


> Maybe that's my mistake?

Maybe is all I can say too since you seem unwilling to show the log

**Comment by fritzrehde** [comment]
I added the verbose output now, sorry for the delay.

**Comment by pukkandan** [comment]
> > Do I still need to use `-embed-metadata`
> 
> Yes

You didn't add this

**Comment by ryanwwest** [comment]
> `--replace-in-metadata "title" "%(title)s" "$TITLE" \`
The variable expansion here hasn't been working for me in Python (it just literally changes the title to "%(title)s"), with, for example in Python options "postprocessors": [], 

```
        {'actions': [(youtube_dl.postprocessor.metadataparser.MetadataParserPP.replacer,
                                  'title',
                                  '.*',
                                  '%(section_title)s')],
                     'key': 'MetadataParser',
                     'when': 'pre_process'},
```
which changes the Title metadata to "%(section_title)s" literally. Not sure if this is a Python limitation or if I'm doing something wrong, but from this thread apparently the variable expansion works at least on the command line. Variable expansion also works in places like `outtmpl` in Python.

**Comment by ryanwwest** [comment]
@pukkandan Thank you, I've been using that script extensively and it's a godsend, though I'm unsure if CLI argument order matters there. My goal: extract m4a audio of video then split by chapters, changing each metadata Title -> section_title, Album -> original YT title, Track Number -> track number. I was commenting about the first part, though I haven't gotten any of the above to work yet. 

This is my Python configuration with the --replace-in-metadata commented out since I clearly don't understand it well enough yet. I had still hoped to use it to replace album with `%(title)s` perhaps, but that still doesn't do variable expansion. I presume there is a much simpler solution for the above and could have sworn that the above automatically occurred once, but maybe not.

```
        post_processors = [
        # {
        #     'actions': [
        #         (yt_dlp.postprocessor.metadataparser.MetadataParserPP.replacer,
        #         'title', '.*', '%(section_title)s')], 
        #     'key': 'MetadataParser',
        #     'when': 'pre_process'
        # },
        {
            'key': 'FFmpegExtractAudio',
            'nopostoverwrites': False,
            'preferredcodec': 'm4a',
            'preferredquality': '0',
        },
        {
            'add_chapters': True,
            'add_infojson': 'if_exists',
            'add_metadata': True,
            'key': 'FFmpegMetadata'
        },
        # TODO embedthumbnail should go above split chapters above, but it can't on opus until
        # this issue is resolved: https://github.com/yt-dlp/yt-dlp/issues/6225. Limited to m4a for now.
        { 'key': 'EmbedThumbnail', },
        {'force_keyframes': False, 'key': 'FFmpegSplitChapters'},
        # change metadata here?
        {'exec_cmd': ['rm'], 'key': 'Exec', 'when': 'after_move'},
        ]
        out_filepath = '/music/%(title)s/%(section_title)s %(section_number)03d. -%(id)s.%(ext)s' # this works
        outtmpl = {'default': out_filepath, 'chapter': out_filepath}
        ydl_opts = {
            # use mp3/mp4/m4a/opus format because other formats won't allow embedding thumbnails in ytdl
            'format': 'm4a/bestaudio/best',
            'writethumbnail':True,
            'embedthumbnail':True,
            'outtmpl': outtmpl,
            'postprocessors':post_processors,
            'postprocessor_args': {'metadata': ['-metadata',
                                     f'Album=%(title)s', #this doesn't expand either
                                     '-metadata',
                                     'Genre=YouTube']}, # this works
        }
        yt_dlp.YoutubeDL(ydl_opts).download(["https://www.youtube.com/watch?v=SijnXyH_Nhs"])
```

**Comment by pukkandan** [comment]
> My goal: extract m4a audio of video then split by chapters, changing each metadata Title -> section_title, Album -> original YT title, Track Number -> track number.

This is not possible without writing a custom postprocessor. There is currently no support for adding different metadata for different chapters of a video.

**Comment by ryanwwest** [comment]
Thanks. If there is no issue Feature Request currently tracking this, I can create one.

**Comment by pukkandan** [comment]
https://github.com/yt-dlp/yt-dlp/issues/951
