### ISSUE TITLE
Yt-dlp not downloading livestream when fed .m3u8 link?[Question]

### ISSUE THREAD

**Issue by Testing2134** [yt-dlp/yt-dlp#539]
## Checklist

- [x ] I'm asking a question
- [x ] I've looked through the README and FAQ for similar questions
- [x ] I've searched the bugtracker for similar questions including closed ones

## Question

Using yt-dlp on a link like this (https://live.gchao.cn/live/23331_m84p323q.m3u8) only downloads one chunk of the livestream. Using command "yt-dlp [url]". However doing the same thing with base youtube-dl downloads the entire stream, using command "youtube-dl [url]". Is this a bug or just me being a derp with yt-dlp?

**Comment by pukkandan** [comment]
Since I can't access that link, I am not sure whether yt-dlp detects it as a non-live manifest due to lack of information in the manifest itself, or due to some bug. Please attach the manifest file so that I can test.

In either case, you can use `--downloader ffmpeg` as a workaround

**Comment by Testing2134** [comment]
This is a manifest from the same site, but a different stream as the original I linked is no longer available. Confirmed to have the same behavior as the first as well. I was unable to attach it directly, https://gofile.io/d/Vcz2qa. I can try uploading it another way if you don't trust this link.

**Comment by pukkandan** [comment]
Like I thought, it is not possible to tell that it is a livestream just by the manifest. There is no option but to give `--downloader ffmpeg`

The only clue that it is live is `EXT-X-MEDIA-SEQUENCE` but that is not reliable. See c15c47d19bfeeacd42f44dd7736f175711a91346

**Comment by Testing2134** [comment]
Could you explain why youtube-dl handles it correctly while yt-dlp doesn't? I'm just curious, all good if you don't want to.

**Comment by pukkandan** [comment]
youtube-dl uses ffmpeg downloader by default while yt-dlp uses the native one

**Comment by Testing2134** [comment]
ah ok that makes sense. Thanks for your help, appreciate it. Will be closing this.
