### ISSUE TITLE
skyit extractor broken

### ISSUE THREAD

**Issue by bann0** [yt-dlp/yt-dlp#5392]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.10.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Italy

### Provide a description that is worded well enough to be understood

yt-dlp can't get the hls stream while the browser can.
In the past this type of URLs use to work.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['--no-config', '-v', 'https://video.sky.it/xfactor/puntate/video/hot-factor-2022-live-1-787593']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out UTF-8, error UTF-8, screen UTF-8
[debug] yt-dlp version 2022.10.04 [4e0511f27]
[debug] Python 3.7.3 (CPython 64bit) - Linux-4.19.0-22-amd64-x86_64-with-debian-10.13 (glibc 2.28)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.1.9-0, ffprobe 4.1.9-0, phantomjs ., rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2018.08.24, mutagen-1.45.1, pyxattr-0.6.1, secretstorage-2.3.1, sqlite3-2.6.0, websockets-9.1
[debug] Proxy map: {}
[debug] Loaded 1701 extractors
[debug] [video.sky.it] Extracting URL: https://video.sky.it/xfactor/puntate/video/hot-factor-2022-live-1-787593
[debug] [player.sky.it] Extracting URL: https://player.sky.it/player/external.html?id=787593&domain=sky
[player.sky.it] 787593: Downloading JSON metadata
[player.sky.it] 787593: Downloading f4m manifest
WARNING: [player.sky.it] Unable to download f4m manifest: HTTP Error 404: Not Found
[player.sky.it] 787593: Downloading m3u8 information
ERROR: 'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/yt_dlp/YoutubeDL.py", line 1478, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/yt_dlp/YoutubeDL.py", line 1554, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.7/dist-packages/yt_dlp/extractor/common.py", line 674, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.7/dist-packages/yt_dlp/extractor/skyit.py", line 75, in _real_extract
    return self._parse_video(video, video_id)
  File "/usr/local/lib/python3.7/dist-packages/yt_dlp/extractor/skyit.py", line 49, in _parse_video
    hls_url, video_id, {'http': 'videoplatform.sky.it'})
  File "/usr/local/lib/python3.7/dist-packages/yt_dlp/extractor/common.py", line 3343, in _extract_akamai_formats
    fmts, subs = self._extract_akamai_formats_and_subtitles(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/yt_dlp/extractor/common.py", line 3385, in _extract_akamai_formats_and_subtitles
    qualities = re.match(REPL_REGEX, m3u8_url).group(2).split(',')
AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by nixxo** [comment]
Fixed.

**Comment by bann0** [comment]
Tested nixxo PR with same URLs and it works.
