### ISSUE TITLE
Doodstream issue 

### ISSUE THREAD

**Issue by Don-Hai-Hum** [yt-dlp/yt-dlp#5399]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.10.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Sir i read your codes and see your ytdlp support old format link then i change link format to old but this issue comes. Solve this issue fast sir

![Screenshot_2022-10-30-04-49-27-724_org telegram plus](https://user-images.githubusercontent.com/116131095/198856016-e4c52d29-f6b3-4a96-8427-5b221c8603da.jpg)

Link of video :- old format https://dood.so/e/3ce8floblo03

New format:- https://dood.re/e/3ce8floblo03

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
Doodstream issue
```

**Comment by pukkandan** [comment]
Why are you spamming? Explain yourself, or I'll be forced to ban you https://github.com/yt-dlp/yt-dlp/issues/3298 https://github.com/yt-dlp/yt-dlp/pull/5400 https://github.com/yt-dlp/yt-dlp/issues/5399 https://github.com/yt-dlp/yt-dlp/issues/5398 https://github.com/yt-dlp/yt-dlp/issues/5391
