### ISSUE TITLE
`--replace-in-metadata` for playlist

### ISSUE THREAD

**Issue by jtagcat** [yt-dlp/yt-dlp#5401]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.10.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Playlist metadata does not use replaced metadata in the output template.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp 'https://www.youtube.com/channel/UC8xKL3JEqjedelwkTQr4r1A/videos' '--skip-download' '--write-info-json' '--replace-in-metadata' 'playlist_title' ' - Videos' '' '--output' '%(playlist_title).200s/%(id)s.%(ext)s'

yt-dlp 'https://www.youtube.com/playlist?list=PL7hjnogFKtnFpNQsYa68Sgj8Z-qSfYYqR' '--skip-download' '--write-info-json' '--replace-in-metadata' 'playlist_title' 'Videos' '' '--output' '%(playlist_title).200s/%(id)s.%(ext)s'
```

Expected: single directory for both
Actual: One directory with videos has replacement, directory with playlist info.json

**Comment by pukkandan** [comment]
The option is applied for each video, not playlists

**Comment by jtagcat** [comment]
I expected it to replace for all types. Should the behavior be changed? Unify or `--replace-in-playlist-metadata`?

**Comment by pukkandan** [comment]
This was added in fe74d5b592438c669f5717b34504f27c34ca9904, jut forgot to close this issue
