### ISSUE TITLE
BBC extract urls (-g/--print urls) prints same url twice

### ISSUE THREAD

**Issue by 1ManSmoking** [yt-dlp/yt-dlp#5404]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.10.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

All

### Provide a description that is worded well enough to be understood

Extracting urls from a page with a single video prints the same url twice.
See example below.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '-g', 'https://www.bbc.com/news/av/world-latin-america-63400249']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.10.04 [4e0511f] (pip) API
[debug] Python 3.10.8 (CPython 64bit) - macOS-12.3.1-x86_64-i386-64bit
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 5.1.2 (setts), ffprobe 5.1.2
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1690 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.10.04, Current version: 2022.10.04
yt-dlp is up to date (2022.10.04)
[debug] [bbc] Extracting URL: https://www.bbc.com/news/av/world-latin-america-63400249
[bbc] world-latin-america-63400249: Downloading webpage
[bbc] p0d9lqpq: Downloading media selection JSON
[bbc] p0d9lqpq: Downloading m3u8 information
[bbc] p0d9lqpq: Downloading m3u8 information
[bbc] p0d9lqpq: Downloading m3u8 information
[bbc] p0d9lqpq: Downloading m3u8 information
[bbc] p0d9lqpq: Downloading MPD manifest
[bbc] p0d9lqpq: Downloading MPD manifest
[bbc] p0d9lqpq: Downloading MPD manifest
[bbc] p0d9lqpq: Downloading MPD manifest
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[download] Downloading playlist: Brazil election: Why are the poor voting for Lula?
[bbc] Playlist Brazil election: Why are the poor voting for Lula?: Downloading 1 videos of 1
[download] Downloading video 1 of 1
[debug] Default format spec: bestvideo*+bestaudio/best
[info] p0d9lqpq: Downloading 1 format(s): mf_cloudfront-video=5070000-1+mf_cloudfront-audio_eng=96000-1
https://vod-dash-ww.live.cf.md.bbci.co.uk/usp/auth/vod/piff_abr_full_hd/5580a8-p0d9lqpq/vf_p0d9lqpq_d1b49969-1fdf-4d69-8f54-9bbdfce7252b.ism/pc_hd_abr_v2_dash_master.mpd?Expires=1666926133&Signature=C6UYL7ivtI1XPzADyG4hY6Bo93lNI2WbI7cKilhkwdy-aiDVIIW6xlaUiJT7tb5Q0bJohWumZ8Ebu-nTJIbAqSaN23MXizeXTC7~NqEChf9Jb1vHlyTQco4GVhCSrSvcO1hEI6jbPCxptHjD-ctjBjHieYcZLXDtbACgTq1GqN1Kv4PB6aKfeNpr-i8lA01i5ZFhrUiLmJfaKJs79P2i~Z2Mt3c1b3uaZkLHMeFK9nhVubEeame1FPphtcrq984dr-tKN9wMwkeKwo-eNfeAhrSEjoKKpG~YzoG0VORrBk9bYMXMfHf0XcUibF8bhbkAKSanozM7nYImTQdpFE-d3A__&Key-Pair-Id=K2VWLYKQ4HU1FJ
https://vod-dash-ww.live.cf.md.bbci.co.uk/usp/auth/vod/piff_abr_full_hd/5580a8-p0d9lqpq/vf_p0d9lqpq_d1b49969-1fdf-4d69-8f54-9bbdfce7252b.ism/pc_hd_abr_v2_dash_master.mpd?Expires=1666926133&Signature=C6UYL7ivtI1XPzADyG4hY6Bo93lNI2WbI7cKilhkwdy-aiDVIIW6xlaUiJT7tb5Q0bJohWumZ8Ebu-nTJIbAqSaN23MXizeXTC7~NqEChf9Jb1vHlyTQco4GVhCSrSvcO1hEI6jbPCxptHjD-ctjBjHieYcZLXDtbACgTq1GqN1Kv4PB6aKfeNpr-i8lA01i5ZFhrUiLmJfaKJs79P2i~Z2Mt3c1b3uaZkLHMeFK9nhVubEeame1FPphtcrq984dr-tKN9wMwkeKwo-eNfeAhrSEjoKKpG~YzoG0VORrBk9bYMXMfHf0XcUibF8bhbkAKSanozM7nYImTQdpFE-d3A__&Key-Pair-Id=K2VWLYKQ4HU1FJ
[download] Finished downloading playlist: Brazil election: Why are the poor voting for Lula?
```

**Comment by flashdagger** [comment]
This is because yt-dlp selects the best merged format as default. You see it in your debug output:
```
[debug] Default format spec: bestvideo*+bestaudio/best
[info] p0d9lqpq: Downloading 1 format(s): mf_cloudfront-video=5070000-1+mf_cloudfront-audio_eng=96000-1
```
In this case it is the same url, but one represents video, the other represents audio.
You can use `-f b` to select the best format containing video and audio in one url.

**Comment by 1ManSmoking** [comment]
Missed that.
My bad.
Thank you very much.
