### ISSUE TITLE
Did YouTube block yt-dlp? 

### ISSUE THREAD

**Issue by soulsucka** [yt-dlp/yt-dlp#5406]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.10.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I've been trying to download videos from YouTube for the past couple days but I've been getting the following:

~ $ yt-dlp -o in_a_perfect_world.mp4 https://youtu.be/q9w6yRQNRU
[generic] q9w6yRQNRU: Downloading webpage
[redirect] Following redirect to https://www.youtube.com/watch?v=q9w6yRQNRU&feature=youtu.be
[generic] watch?v=q9w6yRQNRU&feature=youtu: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] watch?v=q9w6yRQNRU&feature=youtu: Extracting information
ERROR: Unsupported URL: https://www.youtube.com/watch?v=q9w6yRQNRU&feature=youtu.be

yt-dlp is working with Twitter but not with YouTube.

Thanks in advance. 

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
are you sure you copied the full URL? Youtube video ID's have 11 characters, that one only has 10 (which is why it's not being recognized by the extractor). Link doesn't work in browser either

**Comment by soulsucka** [comment]
> are you sure you copied the full URL? Youtube video ID's have 11 characters, that one only has 10 (which is why it's not being recognized by the extractor). Link doesn't work in browser either

I copied the URL from the YouTube app. If it's missing a character where do I find the full URL?

**Comment by pukkandan** [comment]
The URL given is invalid. Also, don't abuse question template
