### ISSUE TITLE
[nbc] Support provider-locked nbc.com livestreams

### ISSUE THREAD

**Issue by tv21** [yt-dlp/yt-dlp#5407]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.10.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

If I go to this URL is a web browser
https://www.nbc.com/live?brand=nbc&callsign=nbc
And enter my provider's login credentials, I can start a live stream from the local NBC affiliate (which I assume is either based on the location of the account or the location of the IP address, not certain, but I assume you'd have to be inside the USA).

Before the stream begins playing, if I go into the browser's dev tools and enter "m3u8" in the search box, then once the stream begins I can see and copy the m3u8 link of the actual live stream.  If I take that link and put it in VLC it will play the stream, so I don't have to watch it in a web browser.

Unfortunately the link changes periodically, and I suspect rather frequently.  And I was hoping to get it without firing up a browser and going through all that.

I was told that there is a way to get yt-dlp to print out that m3u8 link, but I can't figure out how to do that.  None of the obvious options seem to work, even if I specify the username and password and MSO.

In the verbose output below I am not including the username and password, because the output seems to be about the same either way.  Is this telling me that your extractor is not capable of parsing the URL and that no option is going to work for this purpose?

My goal is not to save the live stream to a file, I am only trying to get the m3u8 link that I'd be able get using the dev tools, but do it from a command prompt, without using the web browser.  Is that possible?

I can file a feature request if you think that would help but I just wanted to make sure I'm not doing something wrong first.  If you want to test this you should be able to use the login for any USA provider that carries a local NBC affiliate, which I'd assume would include just about every MSO in the USA.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.nbc.com/live?brand=nbc&callsign=nbc']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.10.04 [4e0511f] (zip)
[debug] Python 3.8.10 (CPython 64bit) - Linux-5.4.0-131-generic-x86_64-with-glibc2.29 (glibc 2.31)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.4-static (setts), ffprobe 4.4-static
[debug] Optional libraries: certifi-2019.11.28, pycrypto-2.6.1, secretstorage-2.3.1, sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Loaded 1690 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.10.04, Current version: 2022.10.04
yt-dlp is up to date (2022.10.04)
[debug] [generic] Extracting URL: https://www.nbc.com/live?brand=nbc&callsign=nbc
[generic] live?brand=nbc&callsign=nbc: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] live?brand=nbc&callsign=nbc: Extracting information
[debug] Looking for Brightcove embeds
[debug] Looking for embeds
ERROR: Unsupported URL: https://www.nbc.com/live?brand=nbc&callsign=nbc
Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1477, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1553, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 672, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/generic.py", line 3062, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.nbc.com/live?brand=nbc&callsign=nbc
```

**Comment by pukkandan** [comment]
You seem to be passing some random page on the site and not a video URL. Try with an actual video URL alongside MSO details

**Comment by 2ShedsJackson** [comment]
> You seem to be passing some random page on the site and not a video URL. Try with an actual video URL alongside MSO details

That's not a random page. That's the page with the video of the network's livestream.

**Comment by pukkandan** [comment]
Even so, OP is not using cookies/MSO details
