### ISSUE TITLE
Extract video information like metadata without downloading video.

### ISSUE THREAD

**Issue by fosam** [yt-dlp/yt-dlp#5412]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [x] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.10.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Hi

Is there any method to print/extract or write video information similar to `metadata` without downloading the video itself?

The only one i got was the `infojson` but it has too much uneeded information, i'm looking for something simpler like metadata info or something similar to that to review before i download the actual video.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run your yt-dlp command with -vU flag added (yt-dlp -vU <your command line>)
- [ ] Copy the WHOLE output (starting with [debug] Command-line config) and insert it below

No verbose output needed

**Comment by pukkandan** [comment]
See `--print`. Eg:

```sh
❯ yt-dlp test:youtube --print "title,id,uploader="
title = "youtube-dl test video \"'/\\\u00e4\u21ad\ud835\udd50"
id = "BaW_jenozKc"
uploader = "Philipp Hagemeister"
```

If your objective is to decide whether the video should be downloaded or not, you can also do this:
```sh
❯ yt-dlp test:youtube --print "pre_process:title,id,uploader=" --match-filter - --no-simulate
title = "youtube-dl test video \"'/\\\u00e4\u21ad\ud835\udd50"
id = "BaW_jenozKc"
uploader = "Philipp Hagemeister"
Download "youtube-dl test video ＂'⧸⧹ä↭𝕐 [BaW_jenozKc].webm "? (Y/n): y
```

**Comment by fosam** [comment]
This is good, but unfortunately too litte data to analyze

I'm looking for something that could look similar to this that can be generic (any video site) and not only specifically for YouTube.

```
"filesize": 2284024,
"format_id": "299",
"format_note": "1080p60",
"source_preference": -1,
"fps": 60,
"height": 1080,
"width": 1920,
"quality": 9,
"has_drm": false,
"tbr": 563.382,
"url": "https://rr6---sn-uxaxovg-vnaee.googlevideo.com/videoplayback?expire=1667257919
"language": "",
"language_preference": -1,
"ext": "mp4",
"vcodec": "avc1.64002a",
"acodec": "none",
"dynamic_range": "SDR",
"vbr": 563.382,
"downloader_options": {
"http_chunk_size": 10485760
 },
```
Anything closer to this?

**Comment by pukkandan** [comment]
Like I said, see the documentation of `--print`. You can print any available field. WHat I showed was just an example

**Comment by fosam** [comment]
@pukkandan 

I tried this commad: `--print filesize --print resolution --print tbr --print fps` and what i got was this, which is Ok

```
NA
1920x1080
2401.958
24
```
But how can i achieve an output that looks similar to this?

```
Filesize:   NA
Resolution: 1920x1080
TBR:        2401.958
FPS:        24
```

**Comment by pukkandan** [comment]
--print "Filesize: %(filesize)s"

etc

**Comment by fosam** [comment]
That's great!

Any idea if it's possible to put a spearator between some fields, like this:

```
Filesize:   NA
Resolution: 1920x1080
══════════════════════════════════════════════════════════════════════════════════════════════════════════════════
TBR:        2401.958
FPS:        24
```

**Comment by pukkandan** [comment]
I'd think that's obvious from the previous commands...

    --print ===============================

**Comment by talwrii** [comment]
I used `-j`. This dumps a bunch of JSON and doesn't download.
