### ISSUE TITLE
automatic_captions missing on some YouTube video JSON despite subs existing

### ISSUE THREAD

**Issue by bard** [yt-dlp/yt-dlp#5414]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.10.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

UK

### Provide a description that is worded well enough to be understood

For some YouTube videos, automatic subtitle information is not available in the JSON dump (`automatic_captions` is an empty object), despite automatic subtitles themselves being available on the YouTube UI.

This started happening at some point in the second half of October. I haven't figured out what is the difference between videos where the information is available and videos where it isn't.

Example:

```sh
yt-dlp --dump-json https://www.youtube.com/watch?v=h2aWYjSA1Jc | jq .automatic_captions
```

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--dump-json', 'https://www.youtube.com/watch?v=h2aWYjSA1Jc']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8 (No ANSI), error utf-8, screen utf-8
[debug] yt-dlp version 2022.10.04 [4e0511f] API
[debug] Python 3.10.8 (CPython 64bit) - Linux-6.0.2-zen1-1-zen-x86_64-with-glibc2.36 (glibc 2.36)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 5.1.2 (setts), ffprobe 5.1.2, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.12.0, brotlicffi-1.0.9.2, certifi-2022.09.24, secretstorage-3.3.3, sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Loaded 1690 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.10.04, Current version: 2022.10.04
yt-dlp is up to date (2022.10.04)
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=h2aWYjSA1Jc
[youtube] h2aWYjSA1Jc: Downloading webpage
[youtube] h2aWYjSA1Jc: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] h2aWYjSA1Jc: Downloading 1 format(s): 248+251
```

**Comment by flashdagger** [comment]
In this case you have to trigger automated captions by adding `--write-auto-subs`.

**Comment by bard** [comment]
@flashdagger thank you, indeed with `--write-auto-sub` it works. Strangely enough, the specific video from the bug report did not need extra options previously.

I suppose there's no harm in always passing `--write-auto-sub` to ensure the earlier behavior?

**Comment by flashdagger** [comment]
The change was made more than 3 month ago to reduce processing time. See #4274

**Comment by bard** [comment]
I looked into this more, and the actual difference that bit me wasn't between mid-October and now, but instead between an Alpine system I used then and an Arch system I'm using now. The former still works without the flag, possibly because it packages 2022.10.04-r1.

Thanks again for helping me understand @flashdagger, closing as not a bug.
