### ISSUE TITLE
Is there a one-liner to download the best video + all audios languages + all subtitles languages → merged in a mkv container ?

### ISSUE THREAD

**Issue by ethicnology** [yt-dlp/yt-dlp#5422]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.10.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Hi fellows

Is there a one-liner that achieve the followings:
- I want to download the best available video
- I want to download all the available audio languages
- I want to download all the available subtitles languages
- Merge all these input in a mkv container

Currently I have to make multiple yt-dlp execution and merge outputs in MKV Toolnix

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
Not currently, see https://github.com/yt-dlp/yt-dlp/issues/1176

**Comment by pukkandan** [comment]
Everything except "all audio languages" can be done with `--embed-subtitles --subtitle-lang all --merge mkv`

**Comment by ethicnology** [comment]
Thanks for the tip, here is a fix for bash args:
```
yt-dlp --embed-subs --sub-langs all --merge mkv URL
```
