### ISSUE TITLE
youtube: /videos playlist call no longer returns shorts, requires 2nd api call to /shorts

### ISSUE THREAD

**Issue by tzarebczan** [yt-dlp/yt-dlp#5428]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.10.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Recently youtube add a shorts tab, and they are no longer returning shorts in the videos playlist, or even at the main URL. This would require anyone using that feature to call the shorts endpoint on top of the videos endpoint. 

Would YT-DLP consider supporting both underneath the hood? 

```
[lbry@ytsync2:~] 2s 1 $ yt-dlp --skip-download https://www.youtube.com/channel/UC5NofLGyaa9Q6PHsxSgXM0Q/videos --get-id --flat-playlist --cookies cookies.txt --playlist-end 9999 | grep "Vh-hSG7yn1U"
[lbry@ytsync2:~] 2s 1 $ yt-dlp --skip-download https://www.youtube.com/channel/UC5NofLGyaa9Q6PHsxSgXM0Q/ --get-id --flat-playlist --cookies cookies.txt --playlist-end 9999 | grep "Vh-hSG7yn1U"
[lbry@ytsync2:~] 2s 1 $ yt-dlp --skip-download https://www.youtube.com/channel/UC5NofLGyaa9Q6PHsxSgXM0Q/shorts --get-id --flat-playlist --cookies cookies.txt --playlist-end 9999 | grep "Vh-hSG7yn1U"
Vh-hSG7yn1U
```

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by coletdjnz** [comment]
Yep, we've been discussing reworking the redirect system to provide videos, live and stream tabs if the channel url without a tab is provided.

Related: https://github.com/yt-dlp/yt-dlp/issues/5419

**Comment by tzarebczan** [comment]
Appreciate the reply! Saw that issue, but didn't read closely enough to see if it was related...apologies.
