### ISSUE TITLE
CDA - support folders/collections/playlists for cda.pl 

### ISSUE THREAD

**Issue by burtek** [yt-dlp/yt-dlp#5429]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a site-specific feature
- [X] I've verified that I'm running yt-dlp version **2022.10.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Poland

### Example URLs

https://www.cda.pl/domino264/folder/30958787
https://www.cda.pl/kamil445/folder/18498552
https://www.cda.pl/kamil445/folder/18498552/2
https://www.cda.pl/kamil445/folder-glowny

### Provide a description that is worded well enough to be understood

CDA extractor only allows single videos links to be passed. Please add support for folders/collections (as with YouTube playlists) for urls in form:

- `https://www.cda.pl/<username>/folder/<num_id>` - user-created collection of videos. `<username>` is the user and can be any strnig. `<num_id>` is numeric id of the folder/collection.
- `https://www.cda.pl/<username>/folder-glowny` - root folder/collection of user's videos and subdirectories.

Keep in mind those lists can be paged (the links to pages have numeric `/<page>` appended), but the site will only show prev, current and next page below videos list (see https://www.cda.pl/domino264/folder/30958787 - only shows pages 1 and 2, but when visiting page 2, pages 1, 2 and 3 are visible), so whether the next page exists has to be discovered on a page-by-page basis

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['https://www.cda.pl/kamil445/folder/18498552', '-vU']
[debug] Encodings: locale cp1250, fs utf-8, pref cp1250, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.10.04 [4e0511f] (win32_exe)
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.2.3
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1690 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.10.04, Current version: 2022.10.04
yt-dlp is up to date (2022.10.04)
[debug] [generic] Extracting URL: https://www.cda.pl/kamil445/folder/18498552
[generic] 18498552: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] 18498552: Extracting information
[debug] Looking for Brightcove embeds
[debug] Looking for embeds
ERROR: Unsupported URL: https://www.cda.pl/kamil445/folder/18498552
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1477, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1553, in __extract_info
  File "yt_dlp\extractor\common.py", line 672, in extract
  File "yt_dlp\extractor\generic.py", line 3062, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.cda.pl/kamil445/folder/18498552
```

**Comment by MrGoraj** [comment]
I have the same problem. 

I see that the topic has been pending for 2 years and still folder support has not been added, so I would like to let you know that there are others who are waiting for this feature.

**Comment by mrnngbgs** [comment]
> I have the same problem.
> 
> I see that the topic has been pending for 2 years and still folder support has not been added, so I would like to let you know that there are others who are waiting for this feature.

I came here to say the same thing, it would be awesome if it was implemented in the future.

**Comment by pktiuk** [comment]
@burtek @MrGoraj @mrnngbgs   
Hi guys, could you provide me some links for folders with multiple pages?     
Maybe I will be able to impleme t this, but I need diverse examples to handle all the cases.

**Comment by mrnngbgs** [comment]
> @burtek @MrGoraj @mrnngbgs Hi guys, could you provide me some links for folders with multiple pages? Maybe I will be able to impleme t this, but I need diverse examples to handle all the cases.

You're a legend for even attempting doing this. Here is a few cda channels (chosen at random) with a variety of playlists to choose from containing between 1 and a few thousand videos each. 

1. [](https://www.cda.pl/TeoWGamelandii/vfilm)
2. [](https://www.cda.pl/nikogamesYt/vfilm)
3. [](https://www.cda.pl/Wilczek160/vfilm)
4. [](https://www.cda.pl/DeliciousBeauty/vfilm)
5. [](https://www.cda.pl/DED87/vfilm)

And here is a few playlists from the above mentioned channels:

1. [](https://www.cda.pl/DED87/folder-glowny/vfilm) = over 3,000 videos
2. [](https://www.cda.pl/DeliciousBeauty/folder-glowny/vfilm/16) = this one has over 900 videos in it but 1/3 is further split into different folders
3. [](https://www.cda.pl/Wilczek160/folder-glowny) = 107 videos
4. [](https://www.cda.pl/TeoWGamelandii/folder/24602906/vfilm) = 4 videos
5. [](https://www.cda.pl/TeoWGamelandii/folder/30713471/vfilm) = 75 videos
6. [](https://www.cda.pl/nikogamesYt/folder/27333024) = 8 videos

The "/vfilm" part of the URL doesn't seem to be necessary - the links seem to be working without it too. Let me know if I can help in any other way.

**Comment by pktiuk** [comment]
@mrnngbgs    
FYI I am going to implement downloading just folders not entire channels (without nested subfolders maybe I could deal with them later)

**Comment by mrnngbgs** [comment]
> @mrnngbgs FYI I am going to implement downloading just folders not entire channels (without nested subfolders, maybe I could deal with them later)

Being able to download folders from cda will be a massive mile stone! Please don't worry about downloading channels, nested folders, etc. You have done enough!!! :) I'm crossing my fingers they'll implement your code!
