### ISSUE TITLE
ERROR: [youtube:tab] UC3eYAvjCVwNHgkaGbXX3sig: The channel does not have a strea ms tab

### ISSUE THREAD

**Issue by suzumiyabi** [yt-dlp/yt-dlp#5430]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.10.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

M:\Videos\未整理\youtubelive\youtube-dl>yt-dlp --check-all-formats https://www.y
outube.com/channel/UC3eYAvjCVwNHgkaGbXX3sig/streams
[youtube:tab] UC3eYAvjCVwNHgkaGbXX3sig: Downloading webpage
ERROR: [youtube:tab] UC3eYAvjCVwNHgkaGbXX3sig: The channel does not have a strea
ms tab

M:\Videos\未整理\youtubelive\youtube-dl>pause
続行するには何かキーを押してください . . .

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
M:\Videos\未整理\youtubelive\youtube-dl>yt-dlp -vU --check-all-formats https://w
ww.youtube.com/channel/UC3eYAvjCVwNHgkaGbXX3sig/streams
[debug] Command-line config: ['-vU', '--check-all-formats', 'https://www.youtube
.com/channel/UC3eYAvjCVwNHgkaGbXX3sig/streams']
[debug] Encodings: locale cp932, fs utf-8, pref cp932, out utf-8 (No VT), error
utf-8 (No VT), screen utf-8 (No VT)
[debug] yt-dlp version 2022.10.04 [4e0511f] (win32_exe)
[debug] Python 3.8.10 (CPython 64bit) - Windows-7-6.1.7601-SP1
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 2022-10-27-git-00b03331a0-full_build-www.gyan.dev (
setts), ffprobe 2022-10-27-git-00b03331a0-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.09.24,
 mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1690 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releas
es/latest
Latest version: 2022.10.04, Current version: 2022.10.04
yt-dlp is up to date (2022.10.04)
[debug] [youtube:tab] Extracting URL: https://www.youtube.com/channel/UC3eYAvjCV
wNHgkaGbXX3sig/streams
[youtube:tab] UC3eYAvjCVwNHgkaGbXX3sig: Downloading webpage
ERROR: [youtube:tab] UC3eYAvjCVwNHgkaGbXX3sig: The channel does not have a strea
ms tab
  File "yt_dlp\extractor\common.py", line 672, in extract
  File "yt_dlp\extractor\youtube.py", line 4223, in wrapper
  File "yt_dlp\extractor\youtube.py", line 5798, in _real_extract


M:\Videos\未整理\youtubelive\youtube-dl>pause
続行するには何かキーを押してください . . .
```

**Comment by pukkandan** [comment]
https://github.com/yt-dlp/yt-dlp/issues/5419

**Comment by krichbanana** [comment]
For now, you can add `--compat-options no-youtube-channel-redirect` to disable the tab name check (it looks for a "Streams" tab but the tab is actually called "Live")
