### ISSUE TITLE
Odysee members-only videos using cookies results in "authentication required"

### ISSUE THREAD

**Issue by Ulmo** [yt-dlp/yt-dlp#5431]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.10.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Unknown, but the target audience is USA and worldwide

### Provide a description that is worded well enough to be understood

Members only content on Odysee is not getting authenticated from cookies file exported from either Firefox or Chrome (from a login session where it works fine in either browser), giving the error:  "ERROR: [lbry] @QuodVerumTV:3/VIP_01NOV22_Nobody:5: lbry said: -32603 - authentication required"

(Using -u and -p says that website isn't supported.)

Since the browsers work fine, I don't blame this on Odysee.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
$ yt-dlp  -vU --cookies odysee.com_cookies.txt https://odysee.com/@QuodVerumTV:3/VIP_01NOV22_Nobody:5
[debug] Command-line config: ['-vU', '--cookies', 'odysee.com_cookies.txt', 'https://odysee.com/@QuodVerumTV:3/VIP_01NOV22_Nobody:5']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.10.04 [4e0511f] (pip) API
[debug] Python 3.10.8 (CPython 64bit) - macOS-10.14.6-x86_64-i386-64bit 
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1690 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.10.04, Current version: 2022.10.04
yt-dlp is up to date (2022.10.04)
[debug] [lbry] Extracting URL: https://odysee.com/@QuodVerumTV:3/VIP_01NOV22_Nobody:5
[lbry] @QuodVerumTV#3/VIP_01NOV22_Nobody#5: Downloading stream JSON metadata
[lbry] 50560a01f771155f4db5a75d0b7b79767d30f7dd: Downloading streaming url JSON metadata
ERROR: [lbry] @QuodVerumTV:3/VIP_01NOV22_Nobody:5: lbry said: -32603 - authentication required
  File "/usr/local/Cellar/yt-dlp/2022.10.4/libexec/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 672, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/Cellar/yt-dlp/2022.10.4/libexec/lib/python3.10/site-packages/yt_dlp/extractor/lbry.py", line 202, in _real_extract
    streaming_url = self._call_api_proxy(
  File "/usr/local/Cellar/yt-dlp/2022.10.4/libexec/lib/python3.10/site-packages/yt_dlp/extractor/lbry.py", line 37, in _call_api_proxy
    raise ExtractorError(

$
```

**Comment by Ulmo** [comment]
If there are no yt-dlp developers who have memberships to membership only content on Odysee, let me know your integrity profile, so I can help you experiment with my situation.

**Comment by Grub4K** [comment]
This seems like a problem with lenient cookie parsing, do the cookies contain any special characters? Maybe it is considered invalid and therefore dropped.

**Comment by Ulmo** [comment]
I don't think it's any weird characters.  I even used "cat  -vv" to check, and nothing came out.

Here's the cookies files:  (I also attached them as well as pasted the ASCII here)

Firefox:
[cookies.firefox-private.txt](https://github.com/yt-dlp/yt-dlp/files/9925126/cookies.firefox-private.txt)
ASCII of that:
==========================
# Netscape HTTP Cookie File
# https://curl.haxx.se/rfc/cookie_spec.html
# This is a generated file! Do not edit.

.odysee.com	TRUE	/	TRUE	1698898909	auth_token	BNT9914LfjChmh6ntNt9XLoPUnjn2XVW
==========================


Chrome:
[odysee.com_cookies.txt](https://github.com/yt-dlp/yt-dlp/files/9925128/odysee.com_cookies.txt)
ASCII of that:
==========================
# Netscape HTTP Cookie File
# This file is generated by yt-dlp.  Do not edit.

.odysee.com	TRUE	/	FALSE	1714527788	_ga	GA1.2.1641272582.1651455777
.odysee.com	TRUE	/	FALSE	1714706911	_ga_BB8DNPB73F	GS1.1.1651634880.2.1.1651634911.29
.odysee.com	TRUE	/	TRUE	1667968292	auth_token	9o41FBsrLHHs2UR2CKvSSWgXkCjEMYv3
==========================

**Comment by Ulmo** [comment]
FlashDaggar, thank you!  I will check if that works!

**Comment by Ulmo** [comment]
I tried FlashDaggar's modification.  After modifiing yt-dlp, I made fresh cookies from browsers that are currently able to play the file, but when I fed them to the modified yt-dlp, it seemed to work better, but ended up in an uninformative error:

$ yt-dlp -vU --cookies cookies.firefox-private-all.txt 'https://odysee.com/@QuodVerumTV:3/VIP_01NOV22_Nobody:5'
[debug] Command-line config: ['-vU', '--cookies', 'cookies.firefox-private-all.txt', 'https://odysee.com/@QuodVerumTV:3/VIP_01NOV22_Nobody:5']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.10.04 [4e0511f27] (zip)
[debug] Python 3.10.8 (CPython 64bit) - macOS-10.14.6-x86_64-i386-64bit 
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: rtmpdump 2.4
[debug] Optional libraries: sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Loaded 1706 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.10.04, Current version: 2022.10.04
yt-dlp is up to date (2022.10.04)
[debug] [lbry] Extracting URL: https://odysee.com/@QuodVerumTV:3/VIP_01NOV22_Nobody:5
[lbry] @QuodVerumTV#3/VIP_01NOV22_Nobody#5: Downloading stream JSON metadata
[lbry] 50560a01f771155f4db5a75d0b7b79767d30f7dd: Downloading streaming url JSON metadata
[lbry] @QuodVerumTV#3/VIP_01NOV22_Nobody#5: Downloading streaming redirect url info
ERROR: [lbry] @QuodVerumTV:3/VIP_01NOV22_Nobody:5: Unable to download webpage: **HTTP Error 403: Forbidden** (caused by <HTTPError 403: 'Forbidden'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 674, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/lbry.py", line 208, in _real_extract
    final_url = self._request_webpage(
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 825, in _request_webpage
    raise ExtractorError(errmsg, cause=err)

  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 807, in _request_webpage
    return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query))
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3686, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

**Comment by flashdagger** [comment]
> Basically a Odysee backend call to a GET api has to be made wtih the authentication token + LBRY url, and then that URL needs to be used. This is a special URL generated that has signed information to validate IP and it also does a HTTP referer check for https://odysee.com/

Thanks for the info, Tom. We appreciate the effort Odysee puts in to make it a save and reliable platform.
Keep up the good work. 👍

**Comment by Ulmo** [comment]
> Be careful sharing tokens, they are like passwords to your entire account. I wiped them out for you.

Thank you very much!  I was concerned about them, but since yt-dlp couldn't use them and the cookies in Firefox and Chrome were different, they felt like single-use tokens but I didn't confirm.  Thanks for doing that!  So far, there isn't much in my account, but it could have been bad for sure.

**Comment by Ulmo** [comment]
#5435 fixes this!  Thank you!

**Comment by tzarebczan** [comment]
You guys rock!
