### ISSUE TITLE
Patreon: Can't get vimeo embded

### ISSUE THREAD

**Issue by AronDurkinSSS** [yt-dlp/yt-dlp#5440]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.10.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

UK

### Provide a description that is worded well enough to be understood

The website contains an embedded Vimeo player. To download, you pass in the url of the website.

`yt-dlp --cookies patreon.com_cookies.txt https://www.patreon.com/posts/maya-pipeline-py-74079575`

Note: You cannot pass in the url of the embed, due to the privacy settings on Vimeo.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--cookies', 'patreon.com_cookies.txt', 'https://www.patreon.com/posts/maya-pipeline-py-74079575']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.10.04 [4e0511f] (win32_exe)
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg N-105268-g8b9ef5a516-20220112 (setts), ffprobe N-105268-g8b9ef5a516-20220112
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1690 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.10.04, Current version: 2022.10.04
yt-dlp is up to date (2022.10.04)
[debug] [Patreon] Extracting URL: https://www.patreon.com/posts/maya-pipeline-py-74079575
[Patreon] 74079575: Downloading API JSON
[debug] [vimeo] Extracting URL: https://player.vimeo.com/video/765826498?h=3eeb0d9590&app_id=122963#__youtubedl_smuggle=%7B%22http_headers%22%3A+%7B%22Referer%22%3A+%22https%3A%2F%2Fpatreon.com%22%7D%7D
[vimeo] 765826498: Downloading webpage
ERROR: [vimeo] 765826498: Unable to extract info section; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 672, in extract
  File "yt_dlp\extractor\vimeo.py", line 872, in _real_extract
  File "yt_dlp\extractor\common.py", line 1224, in _search_regex
```

**Comment by gitAuss1e** [comment]
Having this same issue.
I used to use `--referer` and adding the website that the video is embedded on to download the vimeo embed, but that stopped working.
`[debug] Command-line config: ['-vU', 'https://player.vimeo.com/video/271037998?h=8f2d0d6978', '--referer', 'https://app.28bysamwood.com/load_user_workout?day=0&week_id=421&workout_variation_type=sam_workouts']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.10.04 [4e0511f] (win32_exe)
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg N-87130-g2b9fd15, ffprobe N-87130-g2b9fd15
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1690 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.10.04, Current version: 2022.10.04
yt-dlp is up to date (2022.10.04)
[debug] [vimeo] Extracting URL: https://player.vimeo.com/video/271037998?h=8f2d0d6978
[vimeo] 271037998: Downloading webpage
ERROR: [vimeo] 271037998: Unable to extract info section; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 672, in extract
  File "yt_dlp\extractor\vimeo.py", line 872, in _real_extract
  File "yt_dlp\extractor\common.py", line 1224, in _search_regex`

Then tried to use the actual website url and passthrough cookies (as you do) but no dice.
`[debug] Command-line config: ['-vU', 'https://app.28bysamwood.com/load_user_workout?day=0&week_id=421&workout_variation_type=sam_workouts', '--cookies', '28cookies.txt']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.10.04 [4e0511f] (win32_exe)
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg N-87130-g2b9fd15, ffprobe N-87130-g2b9fd15
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1690 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.10.04, Current version: 2022.10.04
yt-dlp is up to date (2022.10.04)
[debug] [generic] Extracting URL: https://app.28bysamwood.com/load_user_workout?day=0&week_id=421&workout_variation_type=sam_workouts
[generic] load_user_workout?day=0&week_id=421&workout_variation_type=sam_workouts: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] load_user_workout?day=0&week_id=421&workout_variation_type=sam_workouts: Extracting information
[debug] Looking for Brightcove embeds
[debug] Looking for embeds
[debug] Identified a vimeo embed
[debug] [vimeo] Extracting URL: https://player.vimeo.com/video/271037998?h=8f2d0d6978#__youtubedl_smuggle=%7B%22http_headers%22%3A+%7B%22Referer%22%3A+%22https%3A%2F%2Fapp.28bysamwood.com%2Fload_user_workout%3Fday%3D0%26week_id%3D421%26workout_variation_type%3Dsam_workouts%22%7D%7D
[vimeo] 271037998: Downloading webpage
ERROR: [vimeo] 271037998: Unable to extract info section; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 672, in extract
  File "yt_dlp\extractor\vimeo.py", line 872, in _real_extract
  File "yt_dlp\extractor\common.py", line 1224, in _search_regex`

**Comment by bashonly** [comment]
the root problem of both of the above issues is #5361, closing as duplicate

will be fixed in the next release
