### ISSUE TITLE
Is yt-dlp ever planning to add metadata to individual chapters when using --split-chapters?

### ISSUE THREAD

**Issue by mrbobo509** [yt-dlp/yt-dlp#5447]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.10.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

I read in the bugtracker how you would have to redo the --split-chapters feature for it to work, so is this ever gonna be a planned feature? If not, is there a way you can replace the (title) metadata with the file name in the config file? Right now it looks like this ![Screenshot_20221104-093712](https://user-images.githubusercontent.com/53325073/200051336-c02e652e-7214-4acc-91d2-09fd3bb5d006.png)
![Screenshot_20221104-114923](https://user-images.githubusercontent.com/53325073/200052794-2d9db9ed-9043-478c-a376-ea4aff22ade0.png) the top is the file name and the bottom is what vlc reads as the title metadata (theyre all the same name). 
![Screenshot_20221104-092949](https://user-images.githubusercontent.com/53325073/200053439-0f3f4095-f8af-4348-80f3-6d6dd25abd7c.png)
This is my config file if it helps

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by october262** [comment]
> ### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE
> * [x]  I understand that I will be **blocked** if I remove or skip any mandatory* field
> 
> ### Checklist
> * [x]  I'm requesting a feature unrelated to a specific site
> * [x]  I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
> * [x]  I've verified that I'm running yt-dlp version **2022.10.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
> * [x]  I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
> * [x]  I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
> 
> ### Provide a description that is worded well enough to be understood
> I read in the bugtracker how you would have to redo the --split-chapters feature for it to work, so is this ever gonna be a planned feature? If not, is there a way you can replace the (title) metadata with the file name in the config file? Right now it looks like this ![Screenshot_20221104-093712](https://user-images.githubusercontent.com/53325073/200051336-c02e652e-7214-4acc-91d2-09fd3bb5d006.png) ![Screenshot_20221104-114923](https://user-images.githubusercontent.com/53325073/200052794-2d9db9ed-9043-478c-a376-ea4aff22ade0.png) the top is the file name and the bottom is what vlc reads as the title metadata (theyre all the same name). ![Screenshot_20221104-092949](https://user-images.githubusercontent.com/53325073/200053439-0f3f4095-f8af-4348-80f3-6d6dd25abd7c.png) This is my config file if it helps
> 
> ### Provide verbose output that clearly demonstrates the problem
> * [ ]  Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
> * [ ]  Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below
> 
> ### Complete Verbose Output
> _No response_

see this here - https://superuser.com/questions/996223/using-ffmpeg-to-copy-metadata-from-one-file-to-another would this work ??

**Comment by mrbobo509** [comment]
im not that good with programming stuff. is there a certain command from this that i should paste into the config file?

**Comment by october262** [comment]
you should have ffmpeg already installed with yt-dlp.

**Comment by mrbobo509** [comment]
thank you, ill try this and post the results

**Comment by pukkandan** [comment]
https://github.com/yt-dlp/yt-dlp/issues/951

**Comment by mrbobo509** [comment]
i tried the code and it didnt seem to replace the chapters title metadata with the file name, but making the title metadata blank looks like it worked for vlc 
#--parse-metadata "chapter:(?P<title>)"

**Comment by candrapersada** [comment]
> i tried the code and it didnt seem to replace the chapters title metadata with the file name, but making the title metadata blank looks like it worked for vlc
> #--parse-metadata "chapter:(?P<title>)"

how to use for `-o "chapter:%%(title)s\%%(section_number)03d. %%(section_title)s.%%(ext)s"`
