### ISSUE TITLE
'-f' switch not working?

### ISSUE THREAD

**Issue by jimlynnjulian** [yt-dlp/yt-dlp#5452]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.10.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Simple question. I wanted to download a 4k version of a video. the -F list:

ID       EXT RESOLUTION FPS │   FILESIZE    TBR PROTO │ VCODEC         VBR ACODEC    ABR ASR MORE INFO
quad     mp4 unknown        │                   https │ unknown            unknown
ultra    mp4 unknown        │                   https │ unknown            unknown
hls-8147 mp4 2560x1440   25 │ ~  7.49GiB  8147k m3u8  │ unknown      8147k unknown    0k
mpd-6    mp4 2560x1440   25 │ ~  6.99GiB  7610k https │ avc1.640032  7610k mp4a.40.2  0k 44k DASH video, mp4_dash
hls-9071 mp4 3840x2160   25 │ ~  8.33GiB  9071k m3u8  │ unknown      9071k unknown    0k
mpd-7    mp4 3840x2160   25 │ ~ 15.51GiB 16876k https │ avc1.640033 16876k mp4a.40.2  0k 44k DASH video, mp4_dash

I tried the mpd-7 option in:
yt-dlp -f mpd-7  https://ok.ru/video/1492796246781
and consistently got a 7+gb version,

The output:
C:\yt-dlp>yt-dlp -f mpd-7  https://ok.ru/video/1492796246781
[Odnoklassniki] 1492796246781: Downloading desktop webpage
[Odnoklassniki] 1492796246781: Downloading m3u8 information
[info] 1492796246781: Downloading 1 format(s): mpd-7
[download] Destination: 1958-Ölüm Korkusu-Vertigo-James Stewart-1080p,TR.FHd [1492796246781].mp4
[download]   0.2% of    7.52GiB at    5.03MiB/s ETA 25:28

Did I miss something or is the file just not available?

Thank you.
Jim J.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
C:\yt-dlp>yt-dlp -vU -f mpd-7  https://ok.ru/video/1492796246781
[debug] Command-line config: ['-vU', '-f', 'mpd-7', 'https://ok.ru/video/1492796246781']
[debug] Encodings: locale cp65001, fs utf-8, pref cp65001, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.10.04 [4e0511f] (win32_exe)
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.22621-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 2022-06-16-git-5242ede48d-essentials_build-www.gyan.dev (setts), ffprobe 2022-06-16-git-5242ede48d-essentials_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1690 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.10.04, Current version: 2022.10.04
yt-dlp is up to date (2022.10.04)
[debug] [Odnoklassniki] Extracting URL: https://ok.ru/video/1492796246781
[Odnoklassniki] 1492796246781: Downloading desktop webpage
[Odnoklassniki] 1492796246781: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[info] 1492796246781: Downloading 1 format(s): mpd-7
[debug] Invoking http downloader on "https://vd341.mycdn.me/?expires=1667704996182&srcIp=24.158.83.79&pr=10&srcAg=CHROME&ms=185.226.52.62&type=7&sig=0VvwHilkxDA&ct=4&urls=45.136.21.53&clientType=0&id=670726753021"
[download] Resuming download at byte 590002943
[debug] File locking is not supported. Proceeding without locking
[download] Destination: 1958-Ölüm Korkusu-Vertigo-James Stewart-1080p,TR.FHd [1492796246781].mp4
[download]   7.5% of    7.52GiB at    5.05MiB/s ETA 23:31
```

**Comment by pukkandan** [comment]
The approx filesize yt-dlp reports (`~` prefix) can sometimes be wildly inaccurate
