### ISSUE TITLE
'yt-dlp -x -o -' throws Cannot download a video and extract audio into the same file!

### ISSUE THREAD

**Issue by EntityinArray** [yt-dlp/yt-dlp#5455]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.10.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

yt-dlp has a flag ```-o -``` that allows you to throw data into a pipe for processing, instead of writing to a file.
When using ```yt-dlp -x -o -``` to extract audio from video, the program throws an error:
```yt-dlp: error: Cannot download a video and extract audio into the same file! Use "-.%(ext)s" instead of "-"```
This error message wants you to change filename, despite the fact that we're writing to a pipe

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[entityinarray@asuspc PilotRedSun]$ yt-dlp -vU https://www.youtube.com/watch?v=VGQZItOMz6k -x -o - | ffplay -
[debug] Command-line config: ['-vU', 'https://www.youtube.com/watch?v=VGQZItOMz6k', '-x', '-o', '-']

Usage: yt-dlp [OPTIONS] URL [URL...]

yt-dlp: error: Cannot download a video and extract audio into the same file! Use "-.%(ext)s" instead of "-" as the output template
pipe:: Invalid data found when processing inputKB sq=    0B f=0/0
```

**Comment by pukkandan** [comment]
`-x` and other postprocessing options do not work with `-o -`
