### ISSUE TITLE
HTTP 405 on some of certain of site, eg: LiTV.

### ISSUE THREAD

**Issue by codenamedpkt** [yt-dlp/yt-dlp#5456]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.10.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

I have issue with HTTP 405 on certain video site with along by example: `https://testweb/myfolder`

If this happens on extractors, please modify like this so the videos downloads happily: `http://testweb/myfolder/`

These problem is documented [here](https://social.msdn.microsoft.com/Forums/zh-TW/5bd2162e-935c-4f8c-8656-f00ac09b9363/3553125945post26178652922998629983303404053767935492?forum=236) 

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp -vUcw --user-agent "Mozilla/5.0 (Windows NT 10.0.22623; Win64; arm64) HTTP/3.0 Chrome/107.0.5300.0 Edg/107.0.1379.1 yt-dlp/$VERSION aria2/$VERSION wget/$VERSION Transmission/3.00 IPTV Pro/$VERSION" --referer "%(referer)s" -N 4294967295 -f mergeall --video-multistreams --audio-multistreams --merge-output-format mp4 --embed-subs --sub-langs all --sub-format best --embed-thumbnail --embed-chapters --downloader aria2c "https://www.litv.tv/vod/drama/content.do?brc_id=root&id=VOD00219257&isUHEnabled=true&autoPlay=0" --yes-playlist
[debug] Command-line config: ['-vUcw', '--user-agent', 'Mozilla/5.0 (Windows NT 10.0.22623; Win64; arm64) HTTP/3.0 Chrome/107.0.5300.0 Edg/107.0.1379.1 yt-dlp/ aria2/ wget/ Transmission/3.00 IPTV Pro/', '--referer', '%(referer)s', '-N', '4294967295', '-f', 'mergeall', '--video-multistreams', '--audio-multistreams', '--merge-output-format', 'mp4', '--embed-subs', '--sub-langs', 'all', '--sub-format', 'best', '--embed-thumbnail', '--embed-chapters', '--downloader', 'aria2c', 'https://www.litv.tv/vod/drama/content.do?brc_id=root&id=VOD00219257&isUHEnabled=true&autoPlay=0', '--yes-playlist']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.10.04 [4e0511f] (pip) API
[debug] Python 3.10.8 (CPython 64bit) - Linux-4.9.186-22986754-aarch64-with-libc (libc)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 5.1.2 (setts), ffprobe 5.1.2
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1690 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.10.04, Current version: 2022.10.04
yt-dlp is up to date (2022.10.04)
[debug] [LiTV] Extracting URL: https://www.litv.tv/vod/drama/content.do?brc_id=root&id=VOD00219257&isUHEnabled=true&autoPlay=0
[LiTV] VOD00219257: Downloading webpage
[LiTV] VOD00219257: Downloading JSON metadata
ERROR: [LiTV] VOD00219257: Unable to download JSON metadata: HTTP Error 405: Method Not Allowed (caused by <HTTPError 405: 'Method Not Allowed'>); please report this issue on
https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using
yt-dlp -U
File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 672, in extract
ie_result = self._real_extract(url)
File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/yt_dlp/extractor/litv.py", line 98, in _real_extract
video_data = self._download_json(
File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 1032, in download_content
res = getattr(self, download_handle.__name__)(url_or_request, video_id, **kwargs)
File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 996, in download_handle
res = self._download_webpage_handle(
File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 866, in _download_webpage_handle
urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query, expected_status=expected_status)
File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 823, in _request_webpage
raise ExtractorError(errmsg, cause=err)
File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 805, in _request_webpage
return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query))
File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3682, in urlopen
return self._opener.open(req, timeout=self._socket_timeout)
File "/data/data/com.termux/files/usr/lib/python3.10/urllib/request.py", line 525, in open
response = meth(req, response)
File "/data/data/com.termux/files/usr/lib/python3.10/urllib/request.py", line 634, in http_response
response = self.parent.error(
File "/data/data/com.termux/files/usr/lib/python3.10/urllib/request.py", line 563, in error
return self._call_chain(*args)
File "/data/data/com.termux/files/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
result = func(*args)
File "/data/data/com.termux/files/usr/lib/python3.10/urllib/request.py", line 643, in http_error_default
raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 405: Method Not Allowed
```

**Comment by VoyagerXX** [comment]
Hi,
I have encountered this exact Error 405 too when using Odysee.  It began happening for me approx three days ago, i.e. November 15th.  I'm in Europe.  Now I cannot download anything on Odysee.

I would be grateful if a solution could be found to this issue as soon as possible.
Thank you!

**Comment by 1l6r5d** [comment]
C:\youtube-dl>yt-dlp "https://www.litv.tv/vod/movie/content.do?content_id=VOD00291422"
[LiTV] Extracting URL: https://www.litv.tv/vod/movie/content.do?content_id=VOD00291422
[LiTV] VOD00291422: Downloading webpage
[LiTV] VOD00291422: Downloading JSON metadata
ERROR: [LiTV] VOD00291422: Unable to download JSON metadata: HTTP Error 405: Method Not Allowed (caused by <HTTPError 405: Method Not Allowed>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

C:\youtube-dl>youtube-dl https://www.litv.tv/vod/movie/content.do?content_id=VOD00291422
[LiTV] VOD00291422: Downloading webpage
[LiTV] VOD00291422: Downloading JSON metadata
ERROR: Unable to download JSON metadata: HTTP Error 405: Method Not Allowed (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

I also got the same issue, any solution please
