### ISSUE TITLE
Vimeo error: HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by ahm750** [yt-dlp/yt-dlp#5459]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.10.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Provide a description that is worded well enough to be understood

This Vimeo link is returning a 403 Forbidden error even though the video is public and available: https://player.vimeo.com/video/767304016

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-J', 'https://player.vimeo.com/video/767304016', '--verbose', '-vU']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out UTF-8, error UTF-8, screen UTF-8
[debug] yt-dlp version 2022.10.04 [4e0511f] (zip)
[debug] Python 3.7.5 (CPython 64bit) - Linux-4.15.0-135-generic-x86_64-with-Ubuntu-18.04-bionic (glibc 2.26)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.14.1, brotli-1.0.9, certifi-2021.05.30, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.2
[debug] Proxy map: {}
[debug] Loaded 1690 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.10.04, Current version: 2022.10.04
yt-dlp is up to date (2022.10.04)
[debug] [vimeo] Extracting URL: https://player.vimeo.com/video/767304016
[vimeo] 767304016: Downloading webpage
ERROR: [vimeo] 767304016: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 672, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/vimeo.py", line 858, in _real_extract
    url, video_id, headers=headers)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 866, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query, expected_status=expected_status)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 823, in _request_webpage
    raise ExtractorError(errmsg, cause=err)

  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 805, in _request_webpage
    return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query))
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3682, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 563, in error
    result = self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 755, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

null
```

**Comment by bashonly** [comment]
I cannot reproduce.
With release `2022.10.04` and with master, I get [the expected RegexNotFoundError](https://github.com/yt-dlp/yt-dlp/issues/5361), but no 403 error (which should occur first if at all).
With the patch applied from the above-linked issue, I am able to download the video, no 403.

Just to confirm: Are you able to play that video in your browser (in a private tab, with the same internet connection)?

**Comment by ahm750** [comment]
> I cannot reproduce. With release `2022.10.04`, I get [the expected RegexNotFoundError](https://github.com/yt-dlp/yt-dlp/issues/5361), but no 403 error (which should occur first if at all). With the master branch, I am able to download the video, no 403.
> 
> Just to confirm: Are you able to play that video in your browser (in a private tab, with the same internet connection)?

That's strange. Yes, the video plays in a private tab.

**Comment by dirkf** [comment]
Working fine for me with defaults in yt-dl master, but `-f worstvideo` gives, for yt-dl (similar for latest yt-dlp):
```
[download] Got server HTTP error: HTTP Error 400: Bad Request. Retrying fragment 1 (attempt 1 of 10)...
[download] Got server HTTP error: HTTP Error 400: Bad Request. Retrying fragment 1 (attempt 2 of 10)...
[download] Got server HTTP error: HTTP Error 400: Bad Request. Retrying fragment 1 (attempt 3 of 10)...
[download] Got server HTTP error: HTTP Error 400: Bad Request. Retrying fragment 1 (attempt 4 of 10)...
[download] Got server HTTP error: HTTP Error 400: Bad Request. Retrying fragment 1 (attempt 5 of 10)...
[download] Got server HTTP error: HTTP Error 400: Bad Request. Retrying fragment 1 (attempt 6 of 10)...
[download] Got server HTTP error: HTTP Error 400: Bad Request. Retrying fragment 1 (attempt 7 of 10)...
[download] Got server HTTP error: HTTP Error 400: Bad Request. Retrying fragment 1 (attempt 8 of 10)...
[download] Got server HTTP error: HTTP Error 400: Bad Request. Retrying fragment 1 (attempt 9 of 10)...
[download] Got server HTTP error: HTTP Error 400: Bad Request. Retrying fragment 1 (attempt 10 of 10)...
[download] Skipping fragment 1...
...
```
The problem format is `hls-akfire_interconnect_quic-55`:
https://194vod-adaptive.akamaized.net/exp=1667928845~acl=%2F6857a8ce-60b2-4073-94c9-11e6d57e4c59%2F%2A~hmac=d145030c9159ce1a9413f39c17dab032e09827478c3f581f3e407d34643ff460/6857a8ce-60b2-4073-94c9-11e6d57e4c59/video/6564287e/playlist.m3u8?query_string_ranges=1

**Comment by ahm750** [comment]
> `hls-akfire_interconnect_quic-55`:

Did you try with the -J argument? A lot of my yt-dlp GUI users are reporting that they're getting the "HTTP Error 403" error.

**Comment by bashonly** [comment]
> Did you try with the -J argument?

I think this would be inconsequential as this option does not alter the requests being sent by the extractor

**Comment by scrutinizer11** [comment]
I confirm the issue is back in the latest nightly **2024.06.30.232744** and the previous one(s) from the June string of releases. However, it copes well in the stable **2024.05.27** tested on another machine.

**Comment by dirkf** [comment]
A verbose log would help to diagnose this, since the original report was some time ago (and so shows code that is no longer used). Also, it would be interesting to know the format_id(s) in the successful case.

**Comment by scrutinizer11** [comment]
Debug info:
```bash
[debug] Command-line config: ['-v', '--no-check-certificates', '--no-warnings', '--geo-bypass', 'https://vimeo.com/324146324']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2024.06.30.232744 from yt-dlp/yt-dlp-nightly-builds [24f3097ea] (darwin_legacy_exe)
[debug] Python 3.10.5 (CPython x86_64 64bit) - macOS-10.9.5-x86_64-i386-64bit (OpenSSL 1.1.1n  15 Mar 2022)
[debug] exe versions: ffmpeg N-101508-ge93403b (setts), ffprobe N-101508-ge93403b
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.06.02, mutagen-1.47.0, requests-2.32.3, sqlite3-3.37.2, urllib3-2.2.2, websockets-12.0
[debug] Proxy map: {'https': 'localhost:3128'}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1824 extractors
[vimeo] Extracting URL: https://vimeo.com/324146324
[vimeo] 324146324: Downloading webpage
ERROR: [vimeo] 324146324: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: Forbidden>)
  File "yt_dlp/extractor/common.py", line 740, in extract
  File "yt_dlp/extractor/vimeo.py", line 834, in _real_extract
  File "yt_dlp/extractor/common.py", line 960, in _download_webpage_handle
  File "yt_dlp/extractor/common.py", line 909, in _request_webpage

  File "yt_dlp/extractor/common.py", line 896, in _request_webpage
  File "yt_dlp/YoutubeDL.py", line 4141, in urlopen
  File "yt_dlp/networking/common.py", line 117, in send
  File "yt_dlp/networking/_helper.py", line 208, in wrapper
  File "yt_dlp/networking/common.py", line 337, in send
  File "yt_dlp/networking/_requests.py", line 361, in _send
yt_dlp.networking.exceptions.HTTPError: HTTP Error 403: Forbidden
```

**Comment by scrutinizer11** [comment]
Here's another debug message by running in a different configuration:

```bash
[debug] Command-line config: ['--proxy', 'localhost:3128', '--no-check-certificates', '--no-warnings', '--geo-bypass', '--force-overwrites', '--write-subs', '-sub-langs', '(en|ru)-orig,en', '--convert-subs', 'srt', '-S', 'res:1080', '-v', 'https://vimeo.com/324146324']
Type account password and press [Return]: 
```

**Comment by bashonly** [comment]
@scrutinizer11 could you create a new issue please? Seems unrelated to OP

**Comment by scrutinizer11** [comment]
How it's not with the same error?

**Comment by bashonly** [comment]
the type of URL is different, the reason is different, the mitigation strategy is different
