### ISSUE TITLE
How to delete unfinished cache files when download fails

### ISSUE THREAD

**Issue by shimiaoyerin** [yt-dlp/yt-dlp#5463]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.10.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Operating environment Windows10, cmd console

Software environment yt-dlp+ffmpeg+aria2

Detailed description：
How to automatically clear files with suffixes like "part" "aria2" when the download fails for any reason? It must be the function of yt-dlp and aria2. The usage like --paths + & del /f/s/q path\to\temp is not very suitable for me, because I have many processes sharing the same temp folder

--no-continue
I tried it, but it doesn't work for aria2, and it won't clear the cached part of the file, it will only wait for the next download to perform the clearing

--exec [WHEN:]CMD 
I noticed that this command might be the function I need, but English is not my native language and he became obscure You can condition on "%(title)s [%(id)s].%(ext)s" as an example

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-v']
[debug] Encodings: locale cp936, fs utf-8, pref cp936, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.10.04 [4e0511f] (win32_exe)
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg N-107627-g8e6759f10c-20220801 (setts), ffprobe N-107627-g8e6759f10c-20220801
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {'http': 'http://127.0.0.1:10081', 'https': 'https://127.0.0.1:10081', 'ftp': 'ftp://127.0.0.1:10081'}
[debug] Loaded 1690 extractors
```

**Comment by pukkandan** [comment]
As I already said in https://github.com/yt-dlp/yt-dlp/issues/5413, yt-dlp won't delete them. You have to do it with external scripts - you could use separate temp folder for each yt-dlp instance for example. `--exec` wont be trigered when download fails and so won't be usefull to you
