### ISSUE TITLE
Make language codes unique for Naver-related websites with multiple subtitles per language

### ISSUE THREAD

**Issue by PlaylistsTrance** [yt-dlp/yt-dlp#5467]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a site-specific feature
- [X] I've verified that I'm running yt-dlp version **2022.10.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Example URLs

https://www.vlive.tv/video/23383  
https://www.vlive.tv/video/23861  
https://www.vlive.tv/video/908

### Provide a description that is worded well enough to be understood

These VLIVE videos have multiple subtitles for the same language. yt-dlp only downloads one per language code, even though these subtitles are different. Sometimes fan subs are more detailed than official subs, or sometimes one of them is unfinished, or multiple fans used the same language code, even though one of them belongs to a different language. The problem lies in the [Naver extractor](https://github.com/yt-dlp/yt-dlp/blob/master/yt_dlp/extractor/naver.py#L91), as the [VLIVE extractor](https://github.com/yt-dlp/yt-dlp/blob/master/yt_dlp/extractor/vlive.py#L23) inherits from NaverBaseIE.

The captions look like the following in the JSON output:
```
			{
				"language": "ko",
				"country": "KR",
				"locale": "ko_KR",
				"label": "한국어",
				"source": "http://resources-rmcnmv.pstatic.net/globalv/c/read/v2/VOD_ALPHA/global_v_2017_02_27_1/6ee2Jz2kJsFl7x9cNXNeoiWB6g_rmcvideo_360P_640_1228_128-1488186834268_ko_KR_cp.vtt",
				"type": "cp",
				"fanName": ""
			},
			{
				"language": "ko",
				"country": "KR",
				"locale": "ko_KR",
				"label": "한국어",
				"source": "http://resources-rmcnmv.pstatic.net/globalv/c/read/v2/VOD_ALPHA/global_v_2017_02_27_1/6ee2Jz2kJsFl7x9cNXNeoiWB6g_rmcvideo_360P_640_1228_128-1488282198451_ko_KR_fan.vtt",
				"type": "fan",
				"fanName": "나옹이"
			}
```

To be able to download all subtitles, the type and fanName could be used to differentiate them, for example `ko_KR-fan-나옹이`, otherwise they all get added to the same URL list in [sub_dict](https://github.com/yt-dlp/yt-dlp/blob/e9ce4e92501fbe8cc0761ec94f16346d8ba65434/yt_dlp/extractor/naver.py#L91), resulting in only one file being downloaded.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['--list-subs', 'https://www.vlive.tv/video/23383', '--no-playlist', '-vU']
[debug] Portable config "D:\Documents\youtube-dl\yt-dlp.conf": ['-U']
[debug] User config "C:\Users\<user>\AppData\Roaming\yt-dlp\config": []
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.10.04 [4e0511f] (win32_exe)
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.4.1-full_build-www.gyan.dev (setts), ffprobe 4.4.1-full_build-www.gyan.dev, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1690 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.10.04, Current version: 2022.10.04
yt-dlp is up to date (2022.10.04)
[debug] [vlive] Extracting URL: https://www.vlive.tv/video/23383
[vlive] 23383: Downloading officialVideoPost JSON metadata
[vlive] Downloading just the video 23383 because of --no-playlist
[vlive] 23383: Downloading inkey JSON metadata
[vlive] 23383: Downloading JSON metadata
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[info] Available automatic captions for 23383:
Language Formats
es_ES    vtt, ttml
in_ID    vtt, ttml
pt_BR    vtt, ttml
ja_JP    vtt, ttml
[info] Available subtitles for 23383:
Language Formats
en_US    vtt, ttml
vi_VN    vtt, ttml
th_TH    vtt, ttml
zh_CN    vtt, ttml
zh_TW    vtt, ttml
ko_KR    vtt, ttml, vtt, ttml
```

**Comment by pukkandan** [comment]
Do you have an example with multiple fan subs? If not, just `language-type` should be enough

**Comment by PlaylistsTrance** [comment]
https://www.vlive.tv/video/908 This one has 3 languages with 2 fan subs (Italian, Russian, Turkish).
