### ISSUE TITLE
2020 Olympics

### ISSUE THREAD

**Issue by jriker1** [yt-dlp/yt-dlp#548]
Not sure if this is the right place for this, however anyone have plans to use youtube-dl to download certain olympic events?  I can record them off TV but hoping there is or will be some way to download focused events based on the sport only and just let it fly.  The let it fly part I can handle with a sites JSON but curious if people know where the good place or places will be to pull the events from.

**Comment by pukkandan** [comment]
Not really the right place for this. You can ask around in the discord if you want, but its better to ask in communities dedicated to the same
