### ISSUE TITLE
support for terabox.com site

### ISSUE THREAD

**Issue by suniljlandge** [yt-dlp/yt-dlp#5484]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.10.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Example URLs

https://terabox.com/s/1fgJnEjTkrixpGx0hpwoJUg

### Provide a description that is worded well enough to be understood

terabox.com is cloud hosing site where you can host files and videos like mega.nz, google drive

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['https://terabox.com/s/1_lChb2uNB38rX_zcTPEayw', '-vU']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out cp1252 (No ANSI), error cp1252 (No ANSI), screen cp1252 (No ANSI)
[debug] yt-dlp version 2022.10.04 [4e0511f27] (win32_exe)
[debug] Python 3.10.4 (CPython 64bit) - Windows-10-10.0.22000-SP0 (OpenSSL 1.1.1n  15 Mar 2022)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 2022-06-20-git-56419428a8-essentials_build-www.gyan.dev (setts), ffprobe 2022-06-20-git-56419428a8-essentials_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1718 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.10.04, Current version: 2022.10.04
yt-dlp is up to date (2022.10.04)
[debug] [generic] Extracting URL: https://terabox.com/s/1_lChb2uNB38rX_zcTPEayw
[generic] 1_lChb2uNB38rX_zcTPEayw: Downloading webpage
[redirect] Following redirect to https://www.terabox.com/sharing/link?surl=_lChb2uNB38rX_zcTPEayw
[debug] [generic] Extracting URL: https://www.terabox.com/sharing/link?surl=_lChb2uNB38rX_zcTPEayw
[generic] link?surl=_lChb2uNB38rX_zcTPEayw: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] link?surl=_lChb2uNB38rX_zcTPEayw: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://www.terabox.com/sharing/link?surl=_lChb2uNB38rX_zcTPEayw
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1478, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1554, in __extract_info
  File "yt_dlp\extractor\common.py", line 674, in extract
  File "yt_dlp\extractor\generic.py", line 2755, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.terabox.com/sharing/link?surl=_lChb2uNB38rX_zcTPEayw
```

**Comment by pukkandan** [comment]
Does the site offer watchable videos? If not, it will not be supported

**Comment by suniljlandge** [comment]
yes its offers watchable videos

**Comment by pukkandan** [comment]
This is what I get. Some issue on my side? 
![image](https://user-images.githubusercontent.com/6623388/200792158-8562c85d-8b27-4b7d-8628-d0b6751bb74f.png)

**Comment by suniljlandge** [comment]
maybe that link get broken try it with other link : https://terabox.com/s/1fgJnEjTkrixpGx0hpwoJUg
after opening player is displayed where you can play video directly in browser... you can even download it with IDM
![Untitled](https://user-images.githubusercontent.com/117426980/201281079-45be2159-e004-4799-8264-156afdc84d85.png)

**Comment by suniljlandge** [comment]
20 Days, No Updates!!!

**Comment by SurajBhari** [comment]
I would like to see some support for terabox and a huge ton of alternative name that the site have
like https://www.1024tera.com/

**Comment by impulse888** [comment]
I also would like support for terabox. Shared links and regular links.
Can get direct links with telegram bot, IDM and some browser extensions

**Comment by pukkandan** [comment]
The site seems to be flooded with pirated content

**Comment by impulse888** [comment]
Please add support for terabox.com  Links can be extracted with browser add-ons like video download helper, stream detector plus and live stream downloader  thanks
