### ISSUE TITLE
embedded Vimeo player  returns 403 Forbidden error

### ISSUE THREAD

**Issue by rizzyfring** [yt-dlp/yt-dlp#5492]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.10.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I am trying to download a video from an embedded Vimeo player
https://player.vimeo.com/video/_<video_code>_

I got the master.json from Chrome Developer Tools > Network tab. Then replaced ".json?..." suffix with ".mpd".

I tried both --cookies and --cookies-from-browser options -DIDN'T WORK
I added --user-agent and --referer options -STILL NO
I added all the headers using --add-header -NOPE
But still getting HTTP Error 403: Forbidden

The command looks like this now:
`yt-dlp --verbose --cookies-from-browser chrome -f video-xxxx --referer "https://player.vimeo.com/video/<video_code>" --user-agent "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36" --add-header "Origin: https://player.vimeo.com" --add-header "Host: XXvod-adaptive.akamaized.net" --add-header "sec-ch-ua: \"Chromium\";v=\"106\", \"Google Chrome\";v=\"106\", \"Not;A=Brand\";v=\"99\"" --add-header "sec-ch-ua-mobile: ?0". --add-header "sec-ch-ua-platform: \"macOS\"" --add-header "Sec-Fetch-Dest: empty" --add-header "Sec-Fetch-Mode: cors" --add-header "Sec-Fetch-Site: cross-site" --add-header "Accept: */*" --add-header "Accept-Encoding: gzip, deflate, br" "https://67vod-adaptive.akamaized.net/exp=1668052359~acl=%2FXXXXXXXX-XXXX-XXXX-XXXX-aa2040b3a19a%2F%2A~hmac=2ee0949d307022xxxxxxxxxxxxb0caa22978fc43exxxxx64d5667/xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx/sep/video/xxxxx,xxxxxxx,xxxxxxx,xxxxxxx,7xxxxxx1,9e3xxxxx2,axxxxxx4f/audio/4xxxxx93,dxxxxxxd,dxxxxxxb/master.mpd"`

exp from master.json = 1668054411
current epoch during command execution = 1668050540
so definitely the mpd file is still valid!

Please help~

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.10.04 [4e0511f] (pip) API
[debug] Python 3.10.8 (CPython 64bit) - macOS-12.5-x86_64-i386-64bit 
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 5.1.2 (setts), ffprobe 5.1.2, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[Cookies] Extracting cookies from chrome
[debug] Extracting cookies from: "/Users/eezthambai/Library/Application Support/Google/Chrome/Profile 1/Cookies"
[debug] using find-generic-password to obtain password from OSX keychain
[Cookies] Extracted 3311 cookies from chrome
[debug] cookie version breakdown: {'v10': 3292, 'other': 0, 'unencrypted': 19}
[debug] Proxy map: {}
[debug] Loaded 1690 extractors
[debug] [generic] Extracting URL: https://67vod-adaptive.akamaized.net/exp=1668052359~acl=%2FXXXXXXXX-XXXX-XXXX-XXXX-aa2040b3a19a%2F%2A~hmac=2ee0949d307022xxxxxxxxxxxxb0caa22978fc43exxxxx64d5667/xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx/sep/video/xxxxx,xxxxxxx,xxxxxxx,xxxxxxx,7xxxxxx1,9e3xxxxx2,axxxxxx4f/audio/4xxxxx93,dxxxxxxd,dxxxxxxb/master.mpd
[generic] master: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] master: Extracting information
[debug] Identified a DASH manifest
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[info] master: Downloading 1 format(s): video-7xxxxx
[debug] Invoking http downloader on "https://67vod-adaptive.akamaized.net/exp=1xxxxx~acl=%2xe6-7655xxxxx-xxxx-xxxx-xxxxxxxxx%2F%2A~hmac=2ee0949d30702xxxxxxxx7b0caa22978x3e5xxxxxxx5667/6exxxxxx6-xxxx-xxxx-823d-xxxxxxxxx/sep/video/0xxxxxx7,36xxxxf0,6xx520xxxxxc2,67xxxxx7f,7ssx1,9xxefsdfsdgs32,asdsadsadas44f/audio/426dadsa93,d64dsadc5ewrewrwebb/../../../../../parcel/video/79dasdsadas201.mp4?r=dXssssss%3D"
ERROR: unable to download video data: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "/usr/local/Cellar/yt-dlp/2022.10.4/libexec/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3196, in process_info
    success, real_download = self.dl(temp_filename, info_dict)
  File "/usr/local/Cellar/yt-dlp/2022.10.4/libexec/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 2920, in dl
    return fd.download(name, new_info, subtitle)
  File "/usr/local/Cellar/yt-dlp/2022.10.4/libexec/lib/python3.10/site-packages/yt_dlp/downloader/common.py", line 446, in download
    ret = self.real_download(filename, info_dict)
  File "/usr/local/Cellar/yt-dlp/2022.10.4/libexec/lib/python3.10/site-packages/yt_dlp/downloader/http.py", line 371, in real_download
    establish_connection()
  File "/usr/local/Cellar/yt-dlp/2022.10.4/libexec/lib/python3.10/site-packages/yt_dlp/downloader/http.py", line 129, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "/usr/local/Cellar/yt-dlp/2022.10.4/libexec/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3682, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 557, in error
    result = self._call_chain(*args)
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 749, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

**Comment by bashonly** [comment]
instead of trying to download the dash MPD directly, what happens when you pass `https://player.vimeo.com/video/<video_code>` as the URL to be downloaded and set `--referer` to the webpage it was embedded in?
(you'll need to [install the master branch with PIP](https://github.com/yt-dlp/yt-dlp/wiki/Installation#with-pip) for this to work)

**Comment by ahm750** [comment]
> ### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE
> * [x]  I understand that I will be **blocked** if I remove or skip any mandatory* field
> 
> ### Checklist
> * [x]  I'm asking a question and **not** reporting a bug or requesting a feature
> * [x]  I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
> * [x]  I've verified that I'm running yt-dlp version **2022.10.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
> * [x]  I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
> * [x]  I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
> 
> ### Please make sure the question is worded well enough to be understood
> I am trying to download a video from an embedded Vimeo player https://player.vimeo.com/video/_<video_code>_
> 
> I got the master.json from Chrome Developer Tools > Network tab. Then replaced ".json?..." suffix with ".mpd".
> 
> I tried both --cookies and --cookies-from-browser options -DIDN'T WORK I added --user-agent and --referer options -STILL NO I added all the headers using --add-header -NOPE But still getting HTTP Error 403: Forbidden
> 
> The command looks like this now: `yt-dlp --verbose --cookies-from-browser chrome -f video-xxxx --referer "https://player.vimeo.com/video/<video_code>" --user-agent "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36" --add-header "Origin: https://player.vimeo.com" --add-header "Host: XXvod-adaptive.akamaized.net" --add-header "sec-ch-ua: \"Chromium\";v=\"106\", \"Google Chrome\";v=\"106\", \"Not;A=Brand\";v=\"99\"" --add-header "sec-ch-ua-mobile: ?0". --add-header "sec-ch-ua-platform: \"macOS\"" --add-header "Sec-Fetch-Dest: empty" --add-header "Sec-Fetch-Mode: cors" --add-header "Sec-Fetch-Site: cross-site" --add-header "Accept: */*" --add-header "Accept-Encoding: gzip, deflate, br" "https://67vod-adaptive.akamaized.net/exp=1668052359~acl=%2FXXXXXXXX-XXXX-XXXX-XXXX-aa2040b3a19a%2F%2A~hmac=2ee0949d307022xxxxxxxxxxxxb0caa22978fc43exxxxx64d5667/xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx/sep/video/xxxxx,xxxxxxx,xxxxxxx,xxxxxxx,7xxxxxx1,9e3xxxxx2,axxxxxx4f/audio/4xxxxx93,dxxxxxxd,dxxxxxxb/master.mpd"`
> 
> exp from master.json = 1668054411 current epoch during command execution = 1668050540 so definitely the mpd file is still valid!
> 
> Please help~
> 
> ### Provide verbose output that clearly demonstrates the problem
> * [x]  Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
> * [x]  Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below
> 
> ### Complete Verbose Output
> ```shell
> [debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
> [debug] yt-dlp version 2022.10.04 [4e0511f] (pip) API
> [debug] Python 3.10.8 (CPython 64bit) - macOS-12.5-x86_64-i386-64bit 
> [debug] Checking exe version: ffmpeg -bsfs
> [debug] Checking exe version: ffprobe -bsfs
> [debug] exe versions: ffmpeg 5.1.2 (setts), ffprobe 5.1.2, phantomjs 2.1.1
> [debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
> [Cookies] Extracting cookies from chrome
> [debug] Extracting cookies from: "/Users/eezthambai/Library/Application Support/Google/Chrome/Profile 1/Cookies"
> [debug] using find-generic-password to obtain password from OSX keychain
> [Cookies] Extracted 3311 cookies from chrome
> [debug] cookie version breakdown: {'v10': 3292, 'other': 0, 'unencrypted': 19}
> [debug] Proxy map: {}
> [debug] Loaded 1690 extractors
> [debug] [generic] Extracting URL: https://67vod-adaptive.akamaized.net/exp=1668052359~acl=%2FXXXXXXXX-XXXX-XXXX-XXXX-aa2040b3a19a%2F%2A~hmac=2ee0949d307022xxxxxxxxxxxxb0caa22978fc43exxxxx64d5667/xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx/sep/video/xxxxx,xxxxxxx,xxxxxxx,xxxxxxx,7xxxxxx1,9e3xxxxx2,axxxxxx4f/audio/4xxxxx93,dxxxxxxd,dxxxxxxb/master.mpd
> [generic] master: Downloading webpage
> WARNING: [generic] Falling back on generic information extractor
> [generic] master: Extracting information
> [debug] Identified a DASH manifest
> [debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
> [info] master: Downloading 1 format(s): video-7xxxxx
> [debug] Invoking http downloader on "https://67vod-adaptive.akamaized.net/exp=1xxxxx~acl=%2xe6-7655xxxxx-xxxx-xxxx-xxxxxxxxx%2F%2A~hmac=2ee0949d30702xxxxxxxx7b0caa22978x3e5xxxxxxx5667/6exxxxxx6-xxxx-xxxx-823d-xxxxxxxxx/sep/video/0xxxxxx7,36xxxxf0,6xx520xxxxxc2,67xxxxx7f,7ssx1,9xxefsdfsdgs32,asdsadsadas44f/audio/426dadsa93,d64dsadc5ewrewrwebb/../../../../../parcel/video/79dasdsadas201.mp4?r=dXssssss%3D"
> ERROR: unable to download video data: HTTP Error 403: Forbidden
> Traceback (most recent call last):
>   File "/usr/local/Cellar/yt-dlp/2022.10.4/libexec/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3196, in process_info
>     success, real_download = self.dl(temp_filename, info_dict)
>   File "/usr/local/Cellar/yt-dlp/2022.10.4/libexec/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 2920, in dl
>     return fd.download(name, new_info, subtitle)
>   File "/usr/local/Cellar/yt-dlp/2022.10.4/libexec/lib/python3.10/site-packages/yt_dlp/downloader/common.py", line 446, in download
>     ret = self.real_download(filename, info_dict)
>   File "/usr/local/Cellar/yt-dlp/2022.10.4/libexec/lib/python3.10/site-packages/yt_dlp/downloader/http.py", line 371, in real_download
>     establish_connection()
>   File "/usr/local/Cellar/yt-dlp/2022.10.4/libexec/lib/python3.10/site-packages/yt_dlp/downloader/http.py", line 129, in establish_connection
>     ctx.data = self.ydl.urlopen(request)
>   File "/usr/local/Cellar/yt-dlp/2022.10.4/libexec/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3682, in urlopen
>     return self._opener.open(req, timeout=self._socket_timeout)
>   File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 525, in open
>     response = meth(req, response)
>   File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 634, in http_response
>     response = self.parent.error(
>   File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 557, in error
>     result = self._call_chain(*args)
>   File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 496, in _call_chain
>     result = func(*args)
>   File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 749, in http_error_302
>     return self.parent.open(new, timeout=req.timeout)
>   File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 525, in open
>     response = meth(req, response)
>   File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 634, in http_response
>     response = self.parent.error(
>   File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 563, in error
>     return self._call_chain(*args)
>   File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 496, in _call_chain
>     result = func(*args)
>   File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 643, in http_error_default
>     raise HTTPError(req.full_url, code, msg, hdrs, fp)
> urllib.error.HTTPError: HTTP Error 403: Forbidden
> ```

I'm facing the same issue.

**Comment by bashonly** [comment]
> I'm facing the same issue.

@ahm750 if you're referring to #5459, that looks like a different issue: in the log you posted, you are not trying to download the dash manifest URL directly, and you are getting a 403 error from the initial webpage download, not from the MPD.

**Comment by rizzyfring** [comment]
> instead of trying to download the dash MPD directly, what happens when you pass `https://player.vimeo.com/video/<video_code>` as the URL to be downloaded and set `--referer` to the webpage it was embedded in? (you'll need to [install the master branch with PIP](https://github.com/yt-dlp/yt-dlp/wiki/Installation#with-pip) for this to work)

master branch is OP!!!! it works now with just referer. THANK YOU SO MUCH!!!
