### ISSUE TITLE
How to use "--exec rmdir" for remove temp folder after download complete

### ISSUE THREAD

**Issue by candrapersada** [yt-dlp/yt-dlp#5496]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.10.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

how to use `"--exec rmdir"` to remove temp folder after download complete from temp path?
![gambar](https://user-images.githubusercontent.com/36833664/201224095-879eace8-912b-45f7-8ba1-8b86b001f35f.png)

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
Are u asking how to use `rmdir`? I don't understand... Pls elaborate

**Comment by candrapersada** [comment]
I mean how to use` "--exec"` to remove temp folder after download complete from temp path
![gambar](https://user-images.githubusercontent.com/36833664/201225732-daa6c38a-9473-4301-8446-95ad1be4c5b1.png)

**Comment by candrapersada** [comment]
to remove temp folder after download complete automatically

**Comment by pukkandan** [comment]
What's the issue with above command?

**Comment by candrapersada** [comment]
what i mean is alternative way to remove temp other than command on `yt-dlp.conf`

**Comment by pukkandan** [comment]
--exec is run only on **successfull** downloads - in which case, there are no temp files to delete anyway. What you want is not possible using exec
