### ISSUE TITLE
“--trim-filenames”  failure！pls check it.

### ISSUE THREAD

**Issue by dodolook8** [yt-dlp/yt-dlp#5499]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.11.11** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

“--trim-filenames”  failure！

eg：
yt-dlp -f 18 --trim-filenames 28 https://www.youtube.com/watch?v=SXBb7KsvDs0

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
“--trim-filenames”  failure！

eg：
yt-dlp -f 18 --trim-filenames 28 https://www.youtube.com/watch?v=SXBb7KsvDs0
```

**Comment by dodolook8** [comment]
“--trim-filenames”  failure！

eg：
yt-dlp -f 18 --trim-filenames 28 https://www.youtube.com/watch?v=SXBb7KsvDs0

**Comment by flashdagger** [comment]
There really seems to a problem. The current implementation is:
https://github.com/yt-dlp/yt-dlp/blob/08270da5c3454cec1d26c4e34add58158af19a1d/yt_dlp/YoutubeDL.py#L1328-L1331

The filename contains dots which are not indicating the start of the file extension. Also the whole path will be trimmed, not only the filename which causes that the file might end up in one of the parent directories.

**Comment by pukkandan** [comment]
Probably https://github.com/yt-dlp/yt-dlp/issues/2314. Also see https://github.com/yt-dlp/yt-dlp/issues/3494
