### ISSUE TITLE
How to print the description of a Youtube playlist to STDOUT?

### ISSUE THREAD

**Issue by rdrg109** [yt-dlp/yt-dlp#5500]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.11.11** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

# Table of Contents

1.  [The problem](#org05aeab3)
2.  [Additional information](#orgd94a72c)
3.  [The question](#orgff6a2e0)

<a id="org05aeab3"></a>

# The problem

Consider [this playlist](https://www.youtube.com/playlist?list=PLg5tKDNI_a86OO6J9HuIngyROBsUqcf_z) which only contains 8 videos. Its description (as of the time of writing) is shown below

    This is a lecture series on the philosophy of mathematics given at Oxford University in Michaelmas Term 2020 by Joel David Hamkins, Professor of Logic. 
    
    The lecture course information, including a syllabus of topics, is available at http://jdh.hamkins.org/lectures-on-the-philosophy-of-mathematics-oxford-mt20. 
    
    The lectures follow the topics and themes of Professor Hamkins's book, Lectures on the Philosophy of Mathematics, available from MIT Press at https://mitpress.mit.edu/books/lectures-philosophy-mathematics.

I want to retrieve the description of this playlist using `yt-dlp`.

<a id="orgd94a72c"></a>

# Additional information

I know that I can download the data of all videos of a playlist by executing the command. I checked the output and it didn't contain the description of the playlist.

    $ yt-dlp -j 'https://www.youtube.com/playlist?list=PLg5tKDNI_a86OO6J9HuIngyROBsUqcf_z'

I also know that I can list the videos of a playlist (without downloading their data) by executing the following command. This also didn't include the description of the playlist.

    $ yt-dlp --flat-playlist -j 'https://www.youtube.com/playlist?list=PLg5tKDNI_a86OO6J9HuIngyROBsUqcf_z'

I also know that with the following command I can download the data of a playlist without having to download the data of all videos in the playlist. The downloaded data is stored in a file with the extension `.info.json`.

    $ yt-dlp \
        --flat-playlist \
        --skip-download \
        --write-info-json \
        --write-playlist-metafiles \
        'https://www.youtube.com/playlist?list=PLg5tKDNI_a86OO6J9HuIngyROBsUqcf_z'

The command shown above creates a file with the name `Oxford Philosophy of Mathematics [PLg5tKDNI_a86OO6J9HuIngyROBsUqcf_z].info.json` which contains the following. The content has been prettified to make it easier to read.

```
{
  "uploader": "Joel David Hamkins",
  "uploader_id": "UCeMZeXYIhdxnQvZP360uoBg",
  "uploader_url": "https://www.youtube.com/channel/UCeMZeXYIhdxnQvZP360uoBg",
  "thumbnails": [
    {
      "url": "https://i.ytimg.com/vi/uo1xDbsYAcU/hqdefault.jpg?sqp=-oaymwEWCKgBEF5IWvKriqkDCQgBFQAAiEIYAQ==&rs=AOn4CLAR7saSfe7tvtGiuyY7f7Wd7UYGYw",
      "height": 94,
      "width": 168,
      "id": "0",
      "resolution": "168x94"
    },
    {
      "url": "https://i.ytimg.com/vi/uo1xDbsYAcU/hqdefault.jpg?sqp=-oaymwEWCMQBEG5IWvKriqkDCQgBFQAAiEIYAQ==&rs=AOn4CLApzTzkuoldZboguD1a-mvjUczyhw",
      "height": 110,
      "width": 196,
      "id": "1",
      "resolution": "196x110"
    },
    {
      "url": "https://i.ytimg.com/vi/uo1xDbsYAcU/hqdefault.jpg?sqp=-oaymwEXCPYBEIoBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLBU13T7AO9cuighRSjlU5BK-G3vZA",
      "height": 138,
      "width": 246,
      "id": "2",
      "resolution": "246x138"
    },
    {
      "url": "https://i.ytimg.com/vi/uo1xDbsYAcU/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLC7ippPpZCPwB4lCVIoJe2_ppc4Xw",
      "height": 188,
      "width": 336,
      "id": "3",
      "resolution": "336x188"
    }
  ],
  "tags": [],
  "view_count": 18573,
  "availability": "public",
  "modified_date": "20201202",
  "playlist_count": 8,
  "channel": "Joel David Hamkins",
  "channel_id": "UCeMZeXYIhdxnQvZP360uoBg",
  "channel_url": "https://www.youtube.com/channel/UCeMZeXYIhdxnQvZP360uoBg",
  "id": "PLg5tKDNI_a86OO6J9HuIngyROBsUqcf_z",
  "title": "Oxford Philosophy of Mathematics",
  "description": "This is a lecture series on the philosophy of mathematics given at Oxford University in Michaelmas Term 2020 by Joel David Hamkins, Professor of Logic. \n\nThe lecture course information, including a syllabus of topics, is available at http://jdh.hamkins.org/lectures-on-the-philosophy-of-mathematics-oxford-mt20. \n\nThe lectures follow the topics and themes of Professor Hamkins's book, Lectures on the Philosophy of Mathematics, available from MIT Press at https://mitpress.mit.edu/books/lectures-philosophy-mathematics.",
  "_type": "playlist",
  "webpage_url": "https://www.youtube.com/playlist?list=PLg5tKDNI_a86OO6J9HuIngyROBsUqcf_z",
  "webpage_url_basename": "playlist",
  "webpage_url_domain": "youtube.com",
  "extractor": "youtube:tab",
  "extractor_key": "YoutubeTab",
  "epoch": 1668185266,
  "_version": {
    "version": "2022.10.04",
    "release_git_head": "4e0511f",
    "repository": "yt-dlp/yt-dlp"
  }
}
```

As you can see above, the description has been downloaded and stored in the field `"description"`. As I mentioned in the title of this issue, I'm interested in printing that information to STDOUT, I don't want a file storing that information to be created.

<a id="orgff6a2e0"></a>

# The question

How to print the description of a Youtube playlist to STDOUT only by using yt-dlp options?

I'm explicitly mentioning "only by using yt-dlp options", because I'm aware that what I'm trying to accomplish can also be done by storing the downloaded data in a temporary file and then printing the contents of that file to STDOUT, but I prefer not to do that.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.10.04 [4e0511f] API
[debug] Python 3.10.8 (CPython 64bit) - Linux-6.0.7-arch1-1-x86_64-with-glibc2.36 (glibc 2.36)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 5.1.2 (setts), ffprobe 5.1.2, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.12.0, brotlicffi-1.0.9.2, certifi-2022.09.24, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1690 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.11.11, Current version: 2022.10.04
[debug] Downloading _update_spec from https://github.com/yt-dlp/yt-dlp/releases/download/2022.11.11/_update_spec
ERROR: You installed yt-dlp with a package manager or setup.py; Use that to update
```

**Comment by flashdagger** [comment]
Would using `jq` be an option for you?
```
$ yt-dlp --flat-playlist -J 'https://www.youtube.com/playlist?list=PLg5tKDNI_a86OO6J9HuIngyROBsUqcf_z' | jq .description
```

**Comment by pukkandan** [comment]
Or
```
❯ yt-dlp -I0 --print playlist:description https://www.youtube.com/playlist?list=PLg5tKDNI_a86OO6J9HuIngyROBsUqcf_z
This is a lecture series on the philosophy of mathematics given at Oxford University in Michaelmas Term 2020 by Joel David Hamkins, Professor of Logic.

The lecture course information, including a syllabus of topics, is available at http://jdh.hamkins.org/lectures-on-the-philosophy-of-mathematics-oxford-mt20.

The lectures follow the topics and themes of Professor Hamkins's book, Lectures on the Philosophy of Mathematics, available from MIT Press at https://mitpress.mit.edu/books/lectures-philosophy-mathematics.
```

**Comment by rdrg109** [comment]
Thanks for the help! Both solutions worked.
