### ISSUE TITLE
HTTP Error 403: Forbidden on trovo.live

### ISSUE THREAD

**Issue by ev0tto** [yt-dlp/yt-dlp#5501]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.11.11** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

I can not download past stream.
I got m3u8 from the F12 > DEV tool > network on my browser.
![2](https://user-images.githubusercontent.com/80548883/201403342-23ff60cc-bddd-4409-ad53-f1ec64f53c49.png)

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--cookies-from-browser', 'chrome', 'https://vod.trovo.live/a9ae8457voduse1301120758/c515085d387702307387365298/playlist_eof.m3u8']
[debug] Encodings: locale cp932, fs utf-8, pref cp932, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.11.11 [8b64402] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 4.2.3, ffprobe N-108785-g65f96a965a-20221023
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[Cookies] Extracting cookies from chrome
[debug] Extracting cookies from: "C:\Users\123AA\AppData\Local\Google\Chrome\User Data\Default\Network\Cookies"
[debug] Found local state file at "C:\Users\123AA\AppData\Local\Google\Chrome\User Data\Local State"
[Cookies] Extracted 521 cookies from chrome
[debug] cookie version breakdown: {'v10': 3005, 'other': 0, 'unencrypted': 0}
[debug] Proxy map: {}
[debug] Loaded 1723 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.11.11, Current version: 2022.11.11
yt-dlp is up to date (2022.11.11)
[debug] [generic] Extracting URL: https://vod.trovo.live/a9ae8457voduse1301120758/c515085d387702307387365298/playlist_eof.m3u8
[generic] playlist_eof: Downloading webpage
ERROR: [generic] Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 674, in extract
  File "yt_dlp\extractor\generic.py", line 2582, in _real_extract
  File "yt_dlp\extractor\common.py", line 825, in _request_webpage

  File "yt_dlp\extractor\common.py", line 807, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 3692, in urlopen
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

**Comment by pukkandan** [comment]
Try the actual webpage URL

**Comment by ev0tto** [comment]
> Try the actual webpage URL

I do not want to download the stream. I want to download past stream.
And the omnibox url does not change.
I am sorry for your inconvenience, can you try it?
Instructions are in [this ](https://user-images.githubusercontent.com/80548883/201403342-23ff60cc-bddd-4409-ad53-f1ec64f53c49.png).
For example: https://trovo.live/s/SibiRyak_Kras/549793711553

**Comment by pukkandan** [comment]
Then use the VOD's URL 😕 

```
❯ yt-dlp https://trovo.live/s/SibiRyak_Kras/549793711553?vid=ltv-109404096_109404096_387702308050262334
[TrovoVod] ltv-109404096_109404096_387702308050262334: Downloading JSON metadata
[info] ltv-109404096_109404096_387702308050262334: Downloading 1 format(s): 1080P
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 111
[download] Destination: ROAD TO OB 277 ｜ МОДЕРАТОР БЛАДИСТАНА НА СВЯЗИ [ltv-109404096_109404096_387702308050262334].mp4
[download]   0.5% of ~ 400.27MiB at  539.47KiB/s ETA 12:35 (frag 0/111)
ERROR: Interrupted by user
```

**Comment by pukkandan** [comment]
Just FYI, the issue with directly passing manifest is that u r missing headers

**Comment by ev0tto** [comment]
sorry
