### ISSUE TITLE
Downloading Youtube Music Playlist will only download premium audio (141) on first track

### ISSUE THREAD

**Issue by atmazzerexe** [yt-dlp/yt-dlp#5502]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.11.11** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Downloading one YouTube Music video/track will still able to fetch M4A 256kbps audio normally. I have tried multiple albums and all of them are showing the exact same behaviour. Using `--cookies` or `--cookies-from-browser` won't help either.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-f', 'bestaudio', '-vU', '--cookies', '/home/ubuntu/ytmusic-cookies.txt', 'https://music.youtube.com/playlist?list=OLAK5uy_kRPsLXSmFH4WDwWWudMaBqfdxLoAl2iOI']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.11.11 [8b64402] (zip)
[debug] Python 3.8.10 (CPython x86_64 64bit) - Linux-5.15.0-1022-aws-x86_64-with-glibc2.29 (OpenSSL 1.1.1f  31 Mar 2020, glibc 2.31)
[debug] exe versions: ffmpeg 4.4.3 (setts), ffprobe 4.4.3
[debug] Optional libraries: certifi-2019.11.28, secretstorage-2.3.1, sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Loaded 1723 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.11.11, Current version: 2022.11.11
yt-dlp is up to date (2022.11.11)
[debug] [youtube:tab] Extracting URL: https://music.youtube.com/playlist?list=OLAK5uy_kRPsLXSmFH4WDwWWudMaBqfdxLoAl2iOI
[youtube:tab] OLAK5uy_kRPsLXSmFH4WDwWWudMaBqfdxLoAl2iOI: Downloading webpage
[debug] [youtube:tab] Extracted SAPISID cookie
[youtube:tab] OLAK5uy_kRPsLXSmFH4WDwWWudMaBqfdxLoAl2iOI: Redownloading playlist API JSON with unavailable videos
[download] Downloading playlist: Album - Goliath (3 Track)
[youtube:tab] Playlist Album - Goliath (3 Track): Downloading 3 videos of 3
[download] Downloading video 1 of 3
[debug] [youtube] Extracting URL: https://music.youtube.com/watch?v=geWOmVpEAJc
[youtube] geWOmVpEAJc: Downloading webpage
[debug] [youtube] Extracted SAPISID cookie
[youtube] geWOmVpEAJc: Downloading android player API JSON
[youtube] geWOmVpEAJc: Downloading android music player API JSON
[youtube] geWOmVpEAJc: Downloading web music client config
[youtube] geWOmVpEAJc: Downloading player c4225c42
[youtube] geWOmVpEAJc: Downloading web music player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[info] geWOmVpEAJc: Downloading 1 format(s): 141
[debug] Invoking http downloader on "https://rr3---sn-npoldn7z.googlevideo.com/videoplayback?expire=1668212187&ei=e5FuY8rkA4mgvwTV6YK4AQ&ip=2406%3Ada18%3A2ef%3A9c02%3Ac2b%3A933f%3Ad660%3A9516&id=o-ACgFM_026DfPbaAlukHmDcsAW53hQERTKxHCbpWvO6Sj&itag=141&source=youtube&requiressl=yes&mh=x7&mm=31%2C26&mn=sn-npoldn7z%2Csn-30a7ynek&ms=au%2Conr&mv=m&mvi=3&pl=38&ctier=A&pfa=5&gcr=sg&initcwndbps=520000&hightc=yes&vprv=1&mime=audio%2Fmp4&gir=yes&clen=14030335&dur=435.826&lmt=1572828769254643&mt=1668190178&fvip=2&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID_MUSIC&txp=1311222&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cctier%2Cpfa%2Cgcr%2Chightc%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIgOip28XoAzEAPBC5Hk9ZEqVfGFgfqu4NGNBoQcXI2zwQCIQC6NHg9eRqVUovyqf75IlNMMm-WKGxdocWwnbI1_oA8QA%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAMeguTV_YB_FhWUTShlp3RdKBcKeS-bWxUwMvQlkr6SaAiEA1Lrd9glrtD6Zaij5p5_XwzQDv9IzDa8jNI1hv_QHKak%3D"
[download] Destination: Goliath [geWOmVpEAJc].m4a
[download] 100% of   13.38MiB in 00:00:00 at 37.04MiB/s
[FixupM4a] Correcting container of "Goliath [geWOmVpEAJc].m4a"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:Goliath [geWOmVpEAJc].m4a' -map 0 -dn -ignore_unknown -c copy -f mp4 -movflags +faststart 'file:Goliath [geWOmVpEAJc].temp.m4a'
[download] Downloading video 2 of 3
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=BI4PDRLJc6U
[youtube] BI4PDRLJc6U: Downloading webpage
[youtube] BI4PDRLJc6U: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[info] BI4PDRLJc6U: Downloading 1 format(s): 251
[debug] Invoking http downloader on "https://rr3---sn-npoldne7.googlevideo.com/videoplayback?expire=1668212192&ei=gJFuY9rXMIeK9fwPgaaswAc&ip=2406%3Ada18%3A2ef%3A9c02%3Ac2b%3A933f%3Ad660%3A9516&id=o-AMESBFruQOC7FvceXvdBjA59t6nSZW5MChlhSyMkBSmz&itag=251&source=youtube&requiressl=yes&mh=pl&mm=31%2C26&mn=sn-npoldne7%2Csn-30a7yney&ms=au%2Conr&mv=m&mvi=3&pl=38&ctier=A&pfa=5&gcr=sg&initcwndbps=450000&hightc=yes&spc=SFxXNsntQ1KL5jw5TimV6SdIe1Q0fSRK0NRqr69ISg2v&vprv=1&svpuc=1&mime=audio%2Fwebm&gir=yes&clen=3768407&dur=232.681&lmt=1572809379767393&mt=1668190178&fvip=3&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=1301222&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cctier%2Cpfa%2Cgcr%2Chightc%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRgIhALeAuHijv60toCP23qmfMNlqXBFEYWT-vLK__VVrDIpcAiEA-dk1sr9EhU_Ln6D7gdGzrql533PP9J_qEcRLEGwJPWs%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhAI_fBjSpmjU0AwFzRY_pFdQIpTHIlFs9ELWvqJdT9VTlAiAxiWB_bVKqWnsyDnLyh3v9nEbf6BWuZ7PgfeVCbak7Pg%3D%3D"
[download] Destination: Goliath (El-P Remix) [BI4PDRLJc6U].webm
[download] 100% of    3.59MiB in 00:00:00 at 49.41MiB/s
[download] Downloading video 3 of 3
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=Vsr6W4CUyt4
[youtube] Vsr6W4CUyt4: Downloading webpage
[youtube] Vsr6W4CUyt4: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[info] Vsr6W4CUyt4: Downloading 1 format(s): 251
[debug] Invoking http downloader on "https://rr1---sn-npoldn7d.googlevideo.com/videoplayback?expire=1668212193&ei=gZFuY6XWJsbKvATXnJqgBA&ip=2406%3Ada18%3A2ef%3A9c02%3Ac2b%3A933f%3Ad660%3A9516&id=o-ADdybatUeQ3r_mS6M90I6MaCD9iD7aUHQIRGPl6reCek&itag=251&source=youtube&requiressl=yes&mh=FT&mm=31%2C29&mn=sn-npoldn7d%2Csn-npoe7nez&ms=au%2Crdu&mv=m&mvi=1&pl=38&ctier=A&pfa=5&gcr=sg&initcwndbps=458750&hightc=yes&spc=SFxXNvebtnHPlfMdoULuyoxre5d1uZts62uYLDXMHIN6&vprv=1&svpuc=1&mime=audio%2Fwebm&gir=yes&clen=8404554&dur=490.541&lmt=1572820535033149&mt=1668190178&fvip=2&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=1301222&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cctier%2Cpfa%2Cgcr%2Chightc%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIhAOIyLuGKAgx335SKCZzAYmTspqcbd57rhKHUMEIyeqtoAiBS6OIPmYPyfCp87GoiHl_obJqrdszj1EAy5jq2dUWqIA%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgbo1-prkjYi4Rc6jc3_aV3cAyxG7IFm2vC1Hhr7yghLkCIQDkuItuLaGntlPOF5q7yGSgFhT_xpELjAtFIGo9knonXg%3D%3D"
[download] Destination: Tourniquet Man (Wes The Mes Remix) [Vsr6W4CUyt4].webm
[download] 100% of    8.02MiB in 00:00:00 at 79.32MiB/s
[download] Finished downloading playlist: Album - Goliath (3 Track)
```

**Comment by pukkandan** [comment]
Workaround `--extractor-args youtube:player-client=default,android_music`

**Comment by atmazzerexe** [comment]
> Workaround `--extractor-args youtube:player-client=default,android_music`

Yeah, it works now. Should I close the comment or not?

**Comment by kirgizmustafa17** [comment]
I am facing same issue and **--extractor-args youtube:player-client=default,android_music** is not solving the problem.

**--cookies-from-browser edge** working well and I can download single videos with that way.

`yt-dlp.exe -f 141 https://music.youtube.com/playlist?list=PL4fGSI1pDJn5tdVDtIAZArERm_vv4uFCR --cookies-from-browser edge -x --audio-quality 0 --audio-format mp3 -k --paths 'D:\Users\Mustafa\Music\' --output '%(extractor)s\%(playlist)s\%(title)s.%(ext)s' --embed-metadata --parse-metadata ":(?P<meta_synopsis>)" --parse-metadata ":(?P<description>)" --extractor-args youtube:player-client=default,android_music`

**Comment by coletdjnz** [comment]
> https://music.youtube.com/playlist?list=PL4fGSI1pDJn5tdVDtIAZArERm_vv4uFCR

not all the videos in that playlist have format 141

**Comment by kirgizmustafa17** [comment]
> > https://music.youtube.com/playlist?list=PL4fGSI1pDJn5tdVDtIAZArERm_vv4uFCR
> 
> not all the videos in that playlist have format 141

Yes not all videos have format 141 but many of them are 141. But still downloading format 251 for all videos.

For example this video (gPL0LfurxQQ) has format 141 but yt-dlp is downloading 251.

**Comment by kirgizmustafa17** [comment]
I found the problem, _gPL0LfurxQQ_ this is the **music.youtube.com** ID but yt-dlp is downloading from ### youtube.com with that ID _IqTyfYDhIoc_

Both of them are same song, one of them is music and other is video. I am not sure how to solve it but the it is the issue.

**Comment by atmazzerexe** [comment]
Looks like this is another problem altogether (Still within context of the title though I reckon). If your playlist type is "Playlist", you can download the premium audio with the workaround. But if your playlist type is "Chart", you can't download the premium audio (141).

"Chart" playlist example: https://music.youtube.com/playlist?list=PL4fGSI1pDJn6puJdseH2Rt9sMvt9E2M4i

![image](https://user-images.githubusercontent.com/14852623/201745238-a4c7037d-33ac-4dff-8a53-5c26f781f8e5.png)

Typical "Playlist" type would be anything else than chart, usually generated by YouTube like Personal Mix or artist albums.

![image](https://user-images.githubusercontent.com/14852623/201745448-c205600d-5594-41b5-905e-1a3b09bcf89f.png)

Personal playlist would be shown as "Public", "Private", or "Unlisted" and unaffected by this problem. Similar behaviour to "Playlist".

**Comment by pukkandan** [comment]
> The first music is named **Belki** (https://music.youtube.com/watch?v=AsnyAOaQ8so)

What makes you think that's the correct link for the item in the playlist?

**Comment by kirgizmustafa17** [comment]
> > The first music is named **Belki** (https://music.youtube.com/watch?v=AsnyAOaQ8so)
> 
> Why do u say that's the correct link for the item in the playlist?

First of all you need a mouse and then click the link (a string and usually blue colored) with your left side of your mouse. Than you will see many of music titles and find a title which start with 1. (usually at top of the list) and use your to click right side of your mouse to see some options of that links. So now you can see **share** button. Click it and you will see a new window, examine the strings and you will see the magic ID.

If you may handle theese steps, you can find later steps -I hope-.





> Looks like this is another problem altogether (Still within context of the title though I reckon). If your playlist type is "Playlist", you can download the premium audio with the workaround. But if your playlist type is "Chart", you can't download the premium audio (141).
> 
> "Chart" playlist example: https://music.youtube.com/playlist?list=PL4fGSI1pDJn6puJdseH2Rt9sMvt9E2M4i
> 
> ![image](https://user-images.githubusercontent.com/14852623/201745238-a4c7037d-33ac-4dff-8a53-5c26f781f8e5.png)
> 
> Typical "Playlist" type would be anything else than chart, usually generated by YouTube like Personal Mix or artist albums.
> 
> ![image](https://user-images.githubusercontent.com/14852623/201745448-c205600d-5594-41b5-905e-1a3b09bcf89f.png)
> 
> Personal playlist would be shown as "Public", "Private", or "Unlisted" and unaffected by this problem. Similar behaviour to "Playlist".

I will try it, thanks for **helpfull** reply

**Comment by pukkandan** [comment]
Interesting. What does premium users see with https://youtube.com/playlist?list=PL4fGSI1pDJn6puJdseH2Rt9sMvt9E2M4i ?

**Comment by pukkandan** [comment]
Let's continue in #5546
