### ISSUE TITLE
Nightly Builds Of Brave Browser Raise innumerous Errors

### ISSUE THREAD

**Issue by Rogue-Git-Dev** [yt-dlp/yt-dlp#5506]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.11.11** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

I use the nightly builds of Brave; never have I used the stable builds. Previously I used Safari but as of Mac OS 13.* a core framework is littered with bugs which Apple have neglected so effortlessly to patch – a practice for which they are quite infamous. Upon instllation of Brave I renamed the application to Brave rather than the Brave Nightly or whatever is the default. However, that should matter not for YT-DLP fails to fetch cookies for any other than stable builds of Brave. This raises multiple errors which are detailed in the output below. YT-DLP shall fetch cookies from any release channel build of Brave regardless of the name of the application. I believe the final path is the only path YT-DLP checks. The nightly builds use a folder called brave-browser-nightly although the solution may be more complicated than to add alternative paths.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: []
[debug] System config "/etc/yt-dlp.conf": ['--verbose', '--progress', '--newline', '--progress-template', 'download:%(info.title)s %(progress)j', '--no-colors', '--live-from-start', '--output', '/users/User/Downloads/tmp/%(playlist)s/%(playlist_index)s – %(title)s.%(ext)s', '--output-na-placeholder', '[]', '--continue', '--no-part', '--cookies-from-browser', 'brave', '--socket-timeout', '300', '--geo-bypass', '--legacy-server-connect', '--no-check-certificates', '--concurrent-fragments', '96', '--retries', 'infinite', '--file-access-retries', 'infinite', '--fragment-retries', 'infinite', '--buffer-size', '96M', '--http-chunk-size', '96M', '--hls-use-mpegts', '--yes-playlist', '--format', 'bv*+ba/b', '--merge-output-format', 'mkv', '--remux-video', 'mkv', '--audio-format', 'best', '--audio-quality', '0', '--embed-subs', '--embed-thumbnail', '--embed-metadata', '--fixup', 'detect_or_warn', '--extractor-retries', 'infinite', '--extractor-args', 'youtube:player-client=all']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.11.11 [8b64402] (pip)
[debug] Python 3.10.8 (CPython x86_64 64bit) - macOS-13.1-x86_64-i386-64bit (OpenSSL 1.1.1s  1 Nov 2022)
[debug] exe versions: ffmpeg 5.1.2 (fdk,setts), ffprobe 5.1.2, phantomjs 2.1.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.46.0, secretstorage-3.3.3, sqlite3-2.6.0, websockets-10.4
[Cookies] Extracting cookies from brave
Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/site-packages/yt_dlp/__init__.py", line 968, in main
    _exit(*variadic(_real_main(argv)))
  File "/usr/local/lib/python3.10/site-packages/yt_dlp/__init__.py", line 928, in _real_main
    with YoutubeDL(ydl_opts) as ydl:
  File "/usr/local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 641, in __init__
    self.print_debug_header()
  File "/usr/local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3777, in print_debug_header
    self._setup_opener()
  File "/usr/local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3806, in _setup_opener
    self.cookiejar = load_cookies(opts_cookiefile, opts_cookiesfrombrowser, self)
  File "/usr/local/lib/python3.10/site-packages/yt_dlp/cookies.py", line 99, in load_cookies
    extract_cookies_from_browser(browser_name, profile, YDLLogger(ydl), keyring=keyring, container=container))
  File "/usr/local/lib/python3.10/site-packages/yt_dlp/cookies.py", line 120, in extract_cookies_from_browser
    return _extract_chrome_cookies(browser_name, profile, keyring, logger)
  File "/usr/local/lib/python3.10/site-packages/yt_dlp/cookies.py", line 281, in _extract_chrome_cookies
    raise FileNotFoundError(f'could not find {browser_name} cookies database in "{search_root}"')
FileNotFoundError: could not find brave cookies database in "/Users/User/Library/Application Support/BraveSoftware/Brave-Browser"
```

**Comment by pukkandan** [comment]
When u pass `brave`, yt-dlp is looking at the standard location of stable brave. Give the correct profile path explicitly

**Comment by Rogue-Git-Dev** [comment]
I know not the path to it or its name.

**Comment by pukkandan** [comment]
You can check your profile path in `chrome://version`

**Comment by Rogue-Git-Dev** [comment]
Problem solved, thanks. I added a colon and the path in quotations to the profile and allowed upon reveal of the Keychain dialogue and everything works as intended. I was under the misapprehension Firefox is the only browser which required a profile's path to be specified explicitly.

**Comment by pukkandan** [comment]
The stable standard installs of brave, chrome, chromium, edge, firefox, opera, safari, and vivaldi don't need profile to be given. Anything else does
