### ISSUE TITLE
Filters should not be applied to channel playlists when downloading a YouTube channel

### ISSUE THREAD

**Issue by JeffreyMercado** [yt-dlp/yt-dlp#5509]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.11.11** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

```
yt-dlp --no-download --no-config https://www.youtube.com/c/lexfridman --match-title 'podcast' -vU
```

It seems like filters are being applied to the channel playlists when trying to download entire channels. It should not do this.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['--no-download', '--no-config', 'https://www.youtube.com/c/lexfridman', '--match-title', 'podcast', '-vU']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.11.11 [8b64402] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19044-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-108549-g3d6d127cd0-20221007 (setts), ffprobe N-108549-g3d6d127cd0-20221007, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1723 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.11.11, Current version: 2022.11.11
yt-dlp is up to date (2022.11.11)
[debug] [youtube:tab] Extracting URL: https://www.youtube.com/c/lexfridman
[youtube:tab] lexfridman: Downloading webpage
[debug] [youtube:tab] Selected tab: 'videos' (videos), Requested tab: ''
[youtube:tab] Downloading all uploads of the channel. To download only the videos in a specific tab, pass the tab's URL
[youtube:tab] lexfridman/streams: Downloading webpage
[debug] [youtube:tab] Selected tab: 'streams' (live), Requested tab: 'streams'
[youtube:tab] lexfridman/shorts: Downloading webpage
[debug] [youtube:tab] Selected tab: 'shorts' (shorts), Requested tab: 'shorts'
[youtube:tab] Downloading as multiple playlists, separated by tabs. To download as a single playlist instead, pass https://www.youtube.com/playlist?list=UUSHZKyawb77ixDdsGog4iWA
[download] Downloading playlist: Lex Fridman
[youtube:tab] Playlist Lex Fridman: Downloading 3 videos of 3
[download] "Lex Fridman - Videos" title did not match pattern "podcast"
[download] "Lex Fridman - Live" title did not match pattern "podcast"
[download] "Lex Fridman - Shorts" title did not match pattern "podcast"
[download] Finished downloading playlist: Lex Fridman
```

**Comment by pukkandan** [comment]
This issue has actually existed for over a year now (from https://github.com/yt-dlp/yt-dlp/commit/8f18aca8717bb0dd49054555af8d386e5eda3a88), but it's mostly just getting noticed now due to the youtube changes. Fixing this without sacrificing the performance improvements that commit brought is pretty tricky.

For the time-being, `--match-filter _type!=video --match-filter title~=(?i)podcast` will work around the issue

**Comment by JeffreyMercado** [comment]
The workaround works for me for now. My actual filters and commands in use are actually more complicated but this does the job. I wasn't sure how using multiple `--match-filter`s worked but I can understand it now (functionally like a logical or).

I'll see if I could whip up a fix for this. This is a special case where I don't think we would want to apply the filters, only explicit playlist or other downloads.

**Comment by pukkandan** [comment]
> I'll see if I could whip up a fix for this.

I'd like to hear any ideas for how it could be fixed. But I'm [working on a possible solution](https://github.com/yt-dlp/yt-dlp/compare/master...pukkandan:yt-dlp-dev:features/is_single_video), so I suggest not to write a fix without discussing first.

Note that the filter is applied **before** the URL is determined to be a playlist/video, which is what makes this a difficult problem

**Comment by pukkandan** [comment]
btw, another workaround would be:

> [youtube:tab] Downloading as multiple playlists, separated by tabs. To download as a single playlist instead, pass https://www.youtube.com/playlist?list=UUSHZKyawb77ixDdsGog4iWA

**Comment by JeffreyMercado** [comment]
> I'd like to hear any ideas for how it could be fixed. But I'm [working on a possible solution](https://github.com/yt-dlp/yt-dlp/compare/master...pukkandan:yt-dlp-dev:features/is_single_video), so I suggest not to write a fix without discussing first.

I didn't have any ideas yet, need to get caught up on how it's all structured so was just going to look over the code.

As for the other workaround, I have a bunch of scripts that I would have to have update the urls for so it's not feasible for me to do that (and I don't want to have to go around digging around for the channel ids for urls that don't have them).
