### ISSUE TITLE
All Client Names support for YouTube

### ISSUE THREAD

**Issue by heroku-miraheze** [yt-dlp/yt-dlp#5512]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.11.11** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Hello!
We need to support all client names (from https://github.com/zerodytrash/YouTube-Internal-Clients).
Thank you.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by Lesmiscore** [comment]
Why? I don't see why all remaining others are needed

**Comment by pukkandan** [comment]
> We need to support all client names (from https://github.com/zerodytrash/YouTube-Internal-Clients).

No, we dont

**Comment by heroku-miraheze** [comment]
why?

**Comment by pukkandan** [comment]
I would ask the same

**Comment by heroku-miraheze** [comment]
@pukkandan review #5516.

**Comment by pukkandan** [comment]
What??
