### ISSUE TITLE
Zen Yandex Extractor not working

### ISSUE THREAD

**Issue by mephisrussia** [yt-dlp/yt-dlp#5513]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.11.11** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Russia

### Provide a description that is worded well enough to be understood

Zen Yandex extraction does not work on any video or channel.

I tried the video from the extractor test. Neither the video nor the channel is downloaded. Same errors:

`Unable to extract metadata; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U`

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://dzen.ru/video/watch/6002240ff8b1af50bb2da5e3']
[debug] Encodings: locale cp1251, fs utf-8, pref cp1251, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.11.11 [8b64402] (pip)
[debug] Python 3.9.6 (CPython AMD64 64bit) - Windows-10-10.0.19044-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg n4.4-79-gde1132a891-20210724 (setts), ffprobe n4.4-79-gde1132a891-20210724
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2021.10.08, mutagen-1.45.1, sqlite3-2.6.0, websockets-9.1
[debug] Proxy map: {}
[debug] Loaded 1723 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.11.11, Current version: 2022.11.11
yt-dlp is up to date (2022.11.11)
[debug] [ZenYandex] Extracting URL: https://dzen.ru/video/watch/6002240ff8b1af50bb2da5e3
[ZenYandex] 6002240ff8b1af50bb2da5e3: Downloading webpage
[ZenYandex] 6002240ff8b1af50bb2da5e3: Redirecting
ERROR: [ZenYandex] 6002240ff8b1af50bb2da5e3: Unable to extract metadata; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\yt_dlp\extractor\common.py", line 674, in extract
    ie_result = self._real_extract(url)
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\yt_dlp\extractor\yandexvideo.py", line 262, in _real_extract
    data_json = self._search_json(
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\yt_dlp\extractor\common.py", line 1242, in _search_json
    json_string = self._search_regex(
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\yt_dlp\extractor\common.py", line 1228, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
```

**Comment by ilyapashuk** [comment]
I'm sorry, but is this issue planned to be fixed in near time?

**Comment by ilyapashuk** [comment]
attention:
I tested it just now with the unmodified yt-dlp 2022.11.11 and some random video on archlinux, and it works.

for interested users: please retest it now, may be something changed on the dzen side.
