### ISSUE TITLE
Support for piped.video

### ISSUE THREAD

**Issue by RetroAbstract** [yt-dlp/yt-dlp#5518]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.11.11** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Example URLs

https://piped.video/watch?v=ieHv_bJ7mog
https://piped.video/playlist?list=PL8mG-RkN2uTzXkU2tvwQGm7eL9SDufyOD

### Provide a description that is worded well enough to be understood

This request is to add piped.video support to yt-dlp. Piped URLs used to be https://piped.kavin.rocks/, which were supported by yt-dlp. 

However Piped changed from https://piped.kavin.rocks/ to https://piped.video/ recently, and yt-dlp does not support the piped.video URLs, hence this site support request.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://piped.video/watch?v=BeBDVQNqV0o', '-o', 'C:\\Downloads\\%(channel)s - %(playlist)s - %(playlist_index)s - %(title)s - %(upload_date)s.%(ext)s']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.11.11 [8b64402] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19044-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-109064-gc124981b79-20221111 (setts), ffprobe N-109064-gc124981b79-20221111
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1723 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.11.11, Current version: 2022.11.11
yt-dlp is up to date (2022.11.11)
[debug] [generic] Extracting URL: https://piped.video/watch?v=BeBDVQNqV0o
[generic] watch?v=BeBDVQNqV0o: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] watch?v=BeBDVQNqV0o: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://piped.video/watch?v=BeBDVQNqV0o
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1485, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1561, in __extract_info
  File "yt_dlp\extractor\common.py", line 674, in extract
  File "yt_dlp\extractor\generic.py", line 2721, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://piped.video/watch?v=BeBDVQNqV0o
```

**Comment by pukkandan** [comment]
Someone just needs to do #5441 again

**Comment by october262** [comment]
> https://piped.video/watch?v=ieHv_bJ7mog



> ### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE
> * [x]  I understand that I will be **blocked** if I remove or skip any mandatory* field
> 
> ### Checklist
> * [x]  I'm reporting a new site support request
> * [x]  I've verified that I'm running yt-dlp version **2022.11.11** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
> * [x]  I've checked that all provided URLs are playable in a browser with the same IP and same login details
> * [x]  I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
> * [x]  I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
> * [x]  I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
> * [x]  I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required
> 
> ### Region
> _No response_
> 
> ### Example URLs
> https://piped.video/watch?v=ieHv_bJ7mog https://piped.video/playlist?list=PL8mG-RkN2uTzXkU2tvwQGm7eL9SDufyOD
> 
> ### Provide a description that is worded well enough to be understood
> This request is to add piped.video support to yt-dlp. Piped URLs used to be https://piped.kavin.rocks/, which were supported by yt-dlp.
> 
> However Piped changed from https://piped.kavin.rocks/ to https://piped.video/ recently, and yt-dlp does not support the piped.video URLs, hence this site support request.
> 
> ### Provide verbose output that clearly demonstrates the problem
> * [x]  Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
> * [x]  Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below
> 
> ### Complete Verbose Output
> ```shell
> [debug] Command-line config: ['-vU', 'https://piped.video/watch?v=BeBDVQNqV0o', '-o', 'C:\\Downloads\\%(channel)s - %(playlist)s - %(playlist_index)s - %(title)s - %(upload_date)s.%(ext)s']
> [debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
> [debug] yt-dlp version 2022.11.11 [8b64402] (win_exe)
> [debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19044-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
> [debug] exe versions: ffmpeg N-109064-gc124981b79-20221111 (setts), ffprobe N-109064-gc124981b79-20221111
> [debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
> [debug] Proxy map: {}
> [debug] Loaded 1723 extractors
> [debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
> Latest version: 2022.11.11, Current version: 2022.11.11
> yt-dlp is up to date (2022.11.11)
> [debug] [generic] Extracting URL: https://piped.video/watch?v=BeBDVQNqV0o
> [generic] watch?v=BeBDVQNqV0o: Downloading webpage
> WARNING: [generic] Falling back on generic information extractor
> [generic] watch?v=BeBDVQNqV0o: Extracting information
> [debug] Looking for embeds
> ERROR: Unsupported URL: https://piped.video/watch?v=BeBDVQNqV0o
> Traceback (most recent call last):
>   File "yt_dlp\YoutubeDL.py", line 1485, in wrapper
>   File "yt_dlp\YoutubeDL.py", line 1561, in __extract_info
>   File "yt_dlp\extractor\common.py", line 674, in extract
>   File "yt_dlp\extractor\generic.py", line 2721, in _real_extract
> yt_dlp.utils.UnsupportedError: Unsupported URL: https://piped.video/watch?v=BeBDVQNqV0o
> ```

just go from this - yt-dlp "https://piped.video/watch?v=ieHv_bJ7mog"
to this - yt-dlp "eHv_bJ7mog"   the video will now download.

**Comment by 3hr80FEZwlir** [comment]
+1. I was to suggest it myself.
