### ISSUE TITLE
code usage

### ISSUE THREAD

**Issue by Honglong22** [yt-dlp/yt-dlp#5520]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.11.11** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I want to get the best video and the best multiple custom audio, let him skip if there is no one, how can I make this code successful

D:\高清修复音乐录影带>yt-dlp --proxy http://127.0.0.1:10809 --merge-output-format mp4 --audio-multistreams --video-multistreams --compat-options no-live-chat --all-subs --embed-subs --add-metadata --external-downloader aria2c --external-downloader-args "-x 16 -k 1M" -o "%(title)s" -f (272/337/315/313/308/271/303/248)+(258/-i)+(380/-i)+(328/-i)+ba+140 https://www.youtube.com/watch?v=G1NfAJGPps8
WARNING: External Downloader arguments given without specifying name. The arguments will be given to aria2c
[youtube] G1NfAJGPps8: Downloading webpage
WARNING: [youtube] Unable to download webpage: HTTP Error 429: Too Many Requests
[youtube] G1NfAJGPps8: Downloading android player API JSON
[youtube] G1NfAJGPps8: Downloading iframe API JS
[youtube] G1NfAJGPps8: Downloading player c4225c42
[youtube] G1NfAJGPps8: Downloading web player API JSON
[youtube] G1NfAJGPps8: Downloading initial data API JSON
WARNING: [youtube] IncompleteRead(29394 bytes read, 1236 more expected). Retrying (1/3)...
[youtube] G1NfAJGPps8: Downloading initial data API JSON
WARNING: [youtube] IncompleteRead(25221 bytes read, 6248 more expected). Retrying (2/3)...
[youtube] G1NfAJGPps8: Downloading initial data API JSON
WARNING: [youtube] IncompleteRead(30544 bytes read, 529 more expected). Retrying (3/3)...
[youtube] G1NfAJGPps8: Downloading initial data API JSON
ERROR: [youtube] G1NfAJGPps8: Requested format is not available. Use --list-formats for a list of available formats

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp --merge-output-format mp4 --audio-multistreams --video-multistreams --compat-options no-live-chat --all-subs --embed-subs --add-metadata --external-downloader aria2c --external-downloader-args "-x 16 -k 1M" -o “%(title)s” -f (272/337/315/313/308/271/303/248)+(258/-i)+(380/-i)+(328/-i)+ba+140 https://www.youtube.com/watch?v=G1NfAJGPps8
```

**Comment by coletdjnz** [comment]
Likely network issue your end (probably the proxy)

**Comment by Honglong22** [comment]
> Likely network issue your end (probably the proxy)

I want the best video +258+328+380+251+140 and let it skip if there is no 258/328/380 audio, instead of giving an error that there is no clarity available

**Comment by Honglong22** [comment]
yt-dlp --proxy http://127.0.0.1:10809 --merge-output-format mp4 --audio-multistreams --video-multistreams --compat-options no-live-chat --all-subs --embed-subs --add-metadata --external-downloader aria2c --external-downloader-args "-x 16 -k 1M" -o “%(title)s” -i -f (272/337/315/313/308/271/303/248)+(258+328+380+256+251+140) https://www.youtube.com/watch?v=lnOjB7UcM04&list=PLOS_sffDs6Q7X2QuYkeCUHvpSNDm-cC8O&index=52

this link is worked！

**Comment by Honglong22** [comment]
yt-dlp --proxy http://127.0.0.1:10809 --merge-output-format mp4 --audio-multistreams --video-multistreams --compat-options no-live-chat --all-subs --embed-subs --add-metadata --external-downloader aria2c --external-downloader-args "-x 16 -k 1M" -o “%(title)s” -i -f (272/337/315/313/308/271/303/248)+(258+328+380+256+251+140) https://www.youtube.com/watch?v=cEvDvJBTJW4

**this on is failed！**

D:\高清修复音乐录影带>yt-dlp --proxy http://127.0.0.1:10809 --merge-output-format mp4 --audio-multistreams --video-multistreams --compat-options no-live-chat --all-subs --embed-subs --add-metadata --external-downloader aria2c --external-downloader-args "-x 16 -k 1M" -o "%(title)s" -i -f (272/337/315/313/308/271/303/248)+(258+328+380+256+251+140) https://www.youtube.com/watch?v=cEvDvJBTJW4
WARNING: External Downloader arguments given without specifying name. The arguments will be given to aria2c
[youtube] cEvDvJBTJW4: Downloading webpage
WARNING: [youtube] Unable to download webpage: <urlopen error EOF occurred in violation of protocol (_ssl.c:1131)>
[youtube] cEvDvJBTJW4: Downloading android player API JSON
[youtube] cEvDvJBTJW4: Downloading iframe API JS
[youtube] cEvDvJBTJW4: Downloading player c4225c42
WARNING: [youtube] Download of https://www.youtube.com/s/player/c4225c42/player_ias.vflset/en_US/base.js failed: IncompleteRead(586838 bytes read, 2090 more expected)
[youtube] cEvDvJBTJW4: Downloading tv embedded player API JSON
[youtube] cEvDvJBTJW4: Downloading player c4225c42
[youtube] cEvDvJBTJW4: Downloading web player API JSON
[youtube] cEvDvJBTJW4: Downloading web embedded client config
[youtube] cEvDvJBTJW4: Downloading web embedded player API JSON
[youtube] cEvDvJBTJW4: Downloading initial data API JSON
WARNING: [youtube] Remote end closed connection without response. Retrying (1/3)...
[youtube] cEvDvJBTJW4: Downloading initial data API JSON
WARNING: [youtube] Remote end closed connection without response. Retrying (2/3)...
[youtube] cEvDvJBTJW4: Downloading initial data API JSON
ERROR: [youtube] cEvDvJBTJW4: Requested format is not available. Use --list-formats for a list of available formats

**Comment by pukkandan** [comment]
> let it skip if there is no 258/328/380 audio

Skip what?

**Comment by Honglong22** [comment]
> > let it skip if there is no 258/328/380 audio
> 
> Skip what?
Skip if not available

**Comment by Honglong22** [comment]
> > let it skip if there is no 258/328/380 audio
> 
> Skip what?

like this 
(272/337/315/313/308/271/303/248)+258+328+380+251+140

**Comment by Honglong22** [comment]
> Sorry, but I don't understand what u want. Unless you can explain better, I cannot help

I just want the best video and multiple audios with the highest bit rate. For example, YouTube has 384kb 5.1-channel audio, but few videos provide it. I want to keep all the 384KB audio, and skip it if it is not provided. Yes, just keep 128KB of audio

**Comment by Honglong22** [comment]
My current plan is like this (272/337/315/313/308/271/303)+(328/ba)+(380/140), but I can only keep two audios at most, otherwise it will be repeated, or else That is, when there is no available clarity, an error will be reported, and there is no way to download

**Comment by pukkandan** [comment]
Closed due to inactivity
