### ISSUE TITLE
Ideas for running on EL8 (Python <3.7)

### ISSUE THREAD

**Issue by slaway** [yt-dlp/yt-dlp#5525]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.11.11** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Hi all, I just had a question regarding this:

> Python versions 3.7+ (CPython and PyPy) are supported. Other versions and implementations may or may not work correctly.

I just tried installing `2022.11.11` on Rocky Linux 8, which obviously doesn't work because it ships Python 3.6.8.

I understand completely that this is not supported, so this is in no way a complaint, I was just wondering if there's any recommended way of getting it to work. Since the EOL of EL8 is far away (May 2029) I think it's unlikely an upgrade will happen on my end any time soon, and I have no idea if moving to 3.7 is happening for EL8.

I would assume it's technically possible to simply grab Python 3.11 or whatever and install it manually into `~/bin` and then do something like `virtualenv --python="/home/me/bin/python3.11" "/home/me/bin/ytdlp-env"`, and then running `yt-dlp` from within that environment, but before going too far down this rabbit hole I just wanted to check if there are any better ideas, like if there's an yt-dlp release available that is already env-contained or similar.

Thanks

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
$ yt-dlp -vU
[debug] Command-line config: ['-vU']
ERROR: Python version 3.6 is no longer supported! Please update to Python 3.7 or above; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
(...)
```

**Comment by dirkf** [comment]
This https://github.com/yt-dlp/yt-dlp/releases/download/2022.11.11/yt-dlp_linux, as described [here](https://github.com/yt-dlp/yt-dlp#user-content-alternatives)?

**Comment by slaway** [comment]
Well, that's on me, sorry about that :) 

If anyone's curious I did manage to get it to work in the meantime by compiling my own Python with the `--prefix` flag, grabbing the yt-dlp-branded ffmpeg release and creating an alias for it all as well, so that is an option, but completely unnecessary since there's a binary build.
