### ISSUE TITLE
[Youtube] api `get_video_info` not working

### ISSUE THREAD

**Issue by cuongtv51** [yt-dlp/yt-dlp#553]
It seem api `get_video_info` not working
I try with `https://youtube.com/get_video_info?html5=1&el=detailpage&hl=en&c=TVHTML5&cver=6.20180913&video_id=3U-agPOXj7s&eurl=https://youtube.googleapis.com/v/3U-agPOXj7s` but this not work, please help.

**Comment by pukkandan** [comment]
Yes, the TVHTML client is no longer working. The ANDROID/IOS clients works intermittently and is probably on its way out as well

**Comment by pukkandan** [comment]
The endpoint seems to be dead for good
