### ISSUE TITLE
yt-dlp with ffmpeg H.264 Nvidia NVEnc and H.265 Nvidia NVEnc

### ISSUE THREAD

**Issue by vega69-ux** [yt-dlp/yt-dlp#5530]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.11.11** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I place yt-dlp.exe and ffmpeg.exe in the same folder to download videos and use ffmpeg.exe to convert videos to different formats. Is there a way when after yt-dlp.exe finishes downloading a video, to have ffmpeg.exe use H.264 Nvidia NVEnc or H.265 Nvidia NVEnc when converting video formats to other video formats? Example webm to mp4 webm to mkv mp4 to mkv etc?

Thanks

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
> to have ffmpeg.exe use H.264 Nvidia NVEnc or H.265 Nvidia NVEnc when converting video formats to other video formats

Shouldn'y u be asking this in some ffmpeg forums? Once u figure out the answer to that, simply passthrough the relevent args using `--ppa`
