### ISSUE TITLE
brightcove:new error "Access to this resource is forbidden by access policy"

### ISSUE THREAD

**Issue by teijiIshida** [yt-dlp/yt-dlp#5539]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.11.11** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

US

### Provide a description that is worded well enough to be understood

The URL ( https://tvbanywherena.com/viet/videos/926-S%E1%BB%A9Gi%E1%BA%A3Si%C3%AAuN%C4%83ng/1747869620078899838 ) is georestricted, but I am in the supported region and can watch it on a Firefox browser fine. But when trying to download it with yt-dlp, it shows the error in the log. I've tried adding "--cookies-from-browser firefox" as well as "--referer "https://tvbanywherena.com/" but it still gives the same error. I've downloaded from this site in the past successfully before but hasn't in awhile so I don't know when this error came about.

I also see a similar issue a couple years ago on youtube-dl, so maybe this will help you fix the issue: https://github.com/ytdl-org/youtube-dl/issues/15486

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--no-check-certificate', '--retries', '20', '-f', 'bv*+hls-audio-1-vi__Dub_-1', '--audio-multistreams', 'https://tvbanywherena.com/viet/videos/926-S%E1%BB%A9Gi%E1%BA%A3Si%C3%AAuN%C4%83ng/1747869620078899838']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.11.11 [8b64402] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19044-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg n5.0.1-5-gc935240586-20220505 (setts), ffprobe n5.0.1-5-gc935240586-20220505
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1723 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.11.11, Current version: 2022.11.11
yt-dlp is up to date (2022.11.11)
[debug] [generic] Extracting URL: https://tvbanywherena.com/viet/videos/926-S%E1%BB%A9Gi%E1%BA%A3Si%C3%AAuN%C4%83ng/1747869620078899838
[generic] 1747869620078899838: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] 1747869620078899838: Extracting information
[debug] Looking for embeds
[debug] [brightcove:new] Extracting URL: http://players.brightcove.net/5324042807001/24aGoMbFs_default/index.html?videoId=1747869620078899838#__youtubedl_smuggle=%7B%22Referer%22%3A+%22https%3A%2F%2Ftvbanywherena.com%2Fviet%2Fvideos%2F926-S%25E1%25BB%25A9Gi%25E1%25BA%25A3Si%25C3%25AAuN%25C4%2583ng%2F1747869620078899838%22%7D
[debug] Loading brightcove.5324042807001_24aGoMbFs from cache
[brightcove:new] 1747869620078899838: Downloading JSON metadata
ERROR: [brightcove:new] Access to this resource is forbidden by access policy.
  File "yt_dlp\extractor\common.py", line 674, in extract
  File "yt_dlp\extractor\brightcove.py", line 660, in _real_extract
```

**Comment by bashonly** [comment]
this is happening because the generic extractor uses `smuggle_url` to smuggle `Referer`, but the brightcove extractors only unsmuggle `referrer`

**Comment by teijiIshida** [comment]
I just tried using an old version 2022.10.04, and it downloaded fine with the same command in starting post. I think there is regression in version 2022.11.11.

**Comment by bashonly** [comment]
> I just tried using an old version 2022.10.04, and it downloaded fine with the same command in starting post. I think there is regression in version 2022.11.11.

you are correct: https://github.com/yt-dlp/yt-dlp/commit/ade1fa70cbaaaadaa4772e5f0564870cea3167ef#diff-28ac72db5ec9cbb295cfe1f162c6947893d6f348cb3ce76b90a6459194770892L2798
