### ISSUE TITLE
Late Night with Stephen Colbert DRM'd

### ISSUE THREAD

**Issue by ParadoxGBB** [yt-dlp/yt-dlp#5550]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.11.11** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

USA

### Provide a description that is worded well enough to be understood

Full disclosure: this is a duplicate of reported issues that have been filed in the past, for example:

https://github.com/yt-dlp/yt-dlp/issues/240
https://github.com/yt-dlp/yt-dlp/issues/1868

I know we're not supposed to post duplicates, but I did a bit of sleuthing and would appreciate another set of eyes on this.

In the past it seems like The Late Show with Stephen Colbert randomly mis-publishes content on a one-off basis, but now the last two videos are getting this same error (DRM protected). It hasn't been a week yet so not sure if this will get "cleared up".

https://www.cbs.com/shows/video/wzkfcVqX0Eocw5SbmqwiBqft2mOiWPbB/
https://www.cbs.com/shows/video/cjrBln3Csm12_5QTsIYUdEnm7bJ8BTb5/

Oddly this doesn't seem to happen for other weekly CBS shows I'm tracking yet, such as Young Sheldon.

As this is network television, these play fine without an account on CBS's website. I don't use one. In some of the past issues I cited above, an account is requested but I don't think one should be needed, although it is probably geofenced.

I did a network trace via firefox and I don't see any references of a MPD or M3U8. I searched for the same on a video that works, and I found a MPD (for example, https://www.cbs.com/shows/video/8HuxbtPonfM6N_JhoUO1_iRel_A56CR0/):

"streamingUrl":"https:\/\/vod-gcs-cedexis.cbsaavideo.com\/intl_vms\/2022\/11\/03\/2098870851885\/1768377_cenc_dash\/stream.mpd

I suppose my big question / hangup is how the site can play I suppose DRM'd content without an account to license to? 

It does appear the the ad system on CBS.com is similar to Paramount+'s now and it will block playing content if you use an adblocker. That seems to be new to me.

I'm not sure if anything can be done but just hoping for a bit of insight how they managed to lock this if this is indeed not just a site shift that confused the CBS extractor.

(thanks in advance)

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-o', 'F:\\GREG\\DATA\\CinAdmin\\data\\Subscriptions\\hacl5uwp.cml\\%(title)s.%(ext)s', '--fixup', 'detect_or_warn', '--add-metadata', '--write-thumbnail', '--verbose', '--recode-video', 'mp4', '--ffmpeg-location', 'F:\\GREG\\OneDrive\\tools\\ffmpeg', '--sub-format', 'best', '--write-sub', 'https://www.cbs.com/shows/video/wzkfcVqX0Eocw5SbmqwiBqft2mOiWPbB/', '-vU']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.11.11 [8b644025b] (zip)
[debug] Lazy loading extractors is disabled
[debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
[debug] Python 3.9.0 (CPython AMD64 64bit) - Windows-10-10.0.22621-SP0 (OpenSSL 1.1.1g  21 Apr 2020)
[debug] exe versions: ffmpeg 5.0.1-essentials_build-www.gyan.dev (setts), ffprobe 5.0.1-essentials_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.10.4, certifi-2020.11.08, mutagen-1.45.1, sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Loaded 1725 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.11.11, Current version: 2022.11.11
yt-dlp is up to date (2022.11.11)
[debug] [CBS] Extracting URL: https://www.cbs.com/shows/video/wzkfcVqX0Eocw5SbmqwiBqft2mOiWPbB/
[CBS] wzkfcVqX0Eocw5SbmqwiBqft2mOiWPbB: Downloading XML
ERROR: [CBS] wzkfcVqX0Eocw5SbmqwiBqft2mOiWPbB: This video is DRM protected
  File "F:\GREG\OneDrive\Projects\yt-dlp\yt-dlp\yt_dlp\extractor\common.py", line 674, in extract
    ie_result = self._real_extract(url)
  File "F:\GREG\OneDrive\Projects\yt-dlp\yt-dlp\yt_dlp\extractor\cbs.py", line 70, in _real_extract
    return self._extract_video_info(self._match_id(url))
  File "F:\GREG\OneDrive\Projects\yt-dlp\yt-dlp\yt_dlp\extractor\cbs.py", line 156, in _extract_video_info
    self.report_drm(content_id)
  File "F:\GREG\OneDrive\Projects\yt-dlp\yt-dlp\yt_dlp\extractor\common.py", line 1114, in report_drm
    self.raise_no_formats('This video is DRM protected', expected=True, video_id=video_id)
  File "F:\GREG\OneDrive\Projects\yt-dlp\yt-dlp\yt_dlp\extractor\common.py", line 1158, in raise_no_formats
    raise ExtractorError(msg, expected=expected, video_id=video_id)
```

**Comment by pukkandan** [comment]
> I suppose my big question / hangup is how the site can play I suppose DRM'd content without an account to license to?

DRM licences are issued to browsers and devices, and is unrelated to account of the user

**Comment by pukkandan** [comment]
https://en.wikipedia.org/wiki/Widevine

**Comment by besweeet** [comment]
You can use --print-traffic to capture the MPD from the yt-dlp extractor. You can then feed that MPD into yt-dlp with --allow-u to download the decrypted MP4 and M4A chunks. You can then provide your own keys (up to you to figure all that out) to play them back.

**Comment by pukkandan** [comment]
@besweeet Don't post instructions for downloading DRM content

**Comment by ischmidt20** [comment]
I have noticed this issue as well with new episodes posted to Paramount+ within the last week. Episodes of shows that had been posted a while ago still download as normal, but new episodes show up as DRM (both with Paramount+ and CBS extractors)

It makes be believe something server-side has changed, but I wonder if there is a workaround to get an unprotected stream (like we do with the old episodes), or if the DRM is only active for a short time and it is just a matter of playing the waiting game until these new episodes get thrown in the "old" bin, or if this is a permanent change and all new episodes will be DRMed, and perhaps older episodes will become DRMed as well...

**Comment by ParadoxGBB** [comment]
It's a bit harder to debug as-is, but if you comment out the following lines in cbs.py at about line 140:

```
def _extract_video_info(self, content_id, site='cbs', mpx_acc=2198311517):
                 asset_type = 'fallback'
                 query['formats'] = 'M3U+none,MPEG4,M3U+appleHlsEncryption,MP3'
                 del query['assetTypes']
             if asset_type in asset_types:
                 continue
+          # elif any(excluded in asset_type for excluded in ('HLS_FPS', 'DASH_CENC', 'OnceURL')):
+          #     if 'DASH_CENC' in asset_type:
+          #          has_drm = True
+          #      continue
             if asset_type.startswith('HLS') or 'StreamPack' in asset_type:
                 query['formats'] = 'MPEG4,M3U'
             elif asset_type in ('RTMP', 'WIFI', '3G'):
                 query['formats'] = 'MPEG4,FLV'
             asset_types[asset_type] = query
 
+        # if not asset_types and has_drm:
+        #    self.report_drm(content_id)
 
         return self._extract_common_video_info(content_id, asset_types, mpx_acc, extra_info={
             'title': title,
             'series': xpath_text(video_data, 'seriesTitle'),
             'season_number': int_or_none(xpath_text(video_data, 'seasonNumber')),
```

It throws it back to the generic extractor and you can see more useful output if you use --list-formats with yt-dlp. That output also reports DRM when attempting to download so maybe the code has shifted around but I'd recommend removing this code unless I'm missing a case here.

You can also use the --write-pages option and flip through the m3u8 and see that the options there all appear to be DRM'd. So the assessment is correct I think but that wasn't clear to me from the get-go.

As for the site itself, it seems like a hard policy shift to me that is different from previous observations --- the five episodes published since 11/10 all still have DRM, so it's been 10 days from the first and it's still not published clear.
