### ISSUE TITLE
Report if a requested subtitle format is not available and change return code? 

### ISSUE THREAD

**Issue by RyanMarten** [yt-dlp/yt-dlp#5551]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.11.11** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Currently if command line options `--write-sub`, `--sub-lang`, and `--skip-download` are used, then the output does not indicate if a subtitle file has not been found and downloaded. 

Example:
```
yt-dlp -vU --write-auto-subs --write-sub --sub-lang en-orig,en-en --sub-format vtt --skip-download -o "%(id)s_auto.%(ext)s" https://www.youtube.com/watch?v=E4-tv3y60-I
```
There is no indication of not downloading. 

If you then do 
`echo $?` the return code is 0. 

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--write-auto-subs', '--write-sub', '--sub-lang', 'en-orig,en-en', '--sub-format', 'vtt', '--skip-download', '-o', '%(id)s_auto.%(ext)s', 'https://www.youtube.com/watch?v=E4-tv3y60-I']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.10.04 [4e0511f] (pip) API
[debug] Python 3.8.10 (CPython 64bit) - Linux-5.4.0-91-generic-x86_64-with-glibc2.29 (glibc 2.31)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.2.7, ffprobe 4.2.7
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2019.11.28, mutagen-1.46.0, secretstorage-2.3.1, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1690 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.11.11, Current version: 2022.10.04
[debug] Downloading _update_spec from https://github.com/yt-dlp/yt-dlp/releases/download/2022.11.11/_update_spec
ERROR: You installed yt-dlp with pip or using the wheel from PyPi; Use that to update
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=E4-tv3y60-I
[youtube] E4-tv3y60-I: Downloading webpage
[youtube] E4-tv3y60-I: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] E4-tv3y60-I: Downloading 1 format(s): 248+251
```

**Comment by pukkandan** [comment]
Error is issued if a subtitle exists, but fails to download. No error will be issued for subtitles simply not existing. We could however print a message to screen. Would that be sufficient for your usecase?

**Comment by RyanMarten** [comment]
Yes, that sounds great.
