### ISSUE TITLE
Audio format .mp3 is missing from my end?

### ISSUE THREAD

**Issue by koopa990** [yt-dlp/yt-dlp#5554]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.11.11** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I notice in the README.md that it includes .mp3 as a format to convert the video into. I typed in the terminal "yt-dlp _Link_ -f-mp3" and it says format is unavailable. Am I doing this wrong or..?
![Screenshot 2022-11-15 201908](https://user-images.githubusercontent.com/63154730/202067742-9d1381e9-5ab4-4c26-8b12-c1d10f3c31e9.png)

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '-f-mp3']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.11.11 [8b64402] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 2022-10-10-git-f3b5277057-full_build-www.gyan.dev (setts), ffprobe 2022-10-10-git-f3b5277057-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1723 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.11.11, Current version: 2022.11.11
yt-dlp is up to date (2022.11.11)
```

**Comment by pukkandan** [comment]
`-f` is not for converting format. You are likely trying to do `-x --audio-format mp3`

**Comment by a-raccoon** [comment]
YouTube doesn't provide mp3 formatted audio, just webm (opus/ogg) and m4a (aac).  As explained above, `-x mp3` aka `--audio-format mp3` will convert the downloaded format to mp3.  You must have ffmpeg/ffprobe installed.

**Comment by koopa990** [comment]
> YouTube doesn't provide mp3 formatted audio, just webm (opus/ogg) and m4a (aac). As explained above, `-x mp3` aka `--audio-format mp3` will convert the downloaded format to mp3. You must have ffmpeg/ffprobe installed.

Yeah, I have ffmpeg installed in the folder where yt-dlp content are.

**Comment by october262** [comment]
> > YouTube doesn't provide mp3 formatted audio, just webm (opus/ogg) and m4a (aac). As explained above, `-x mp3` aka `--audio-format mp3` will convert the downloaded format to mp3. You must have ffmpeg/ffprobe installed.
> 
> Yeah, I have ffmpeg installed in the folder where yt-dlp content are.

try with yt-dlp --extract-audio --audio-format mp3 "link"

**Comment by koopa990** [comment]
> > Yeah, I have ffmpeg installed in the folder where yt-dlp content are.
> 
> try with yt-dlp --extract-audio --audio-format mp3 "link"

Alright, I got it with the yt-dlp Link -x --audio-format mp3"
And what's the command to download the best audio quality? (like higher kbps)

**Comment by pukkandan** [comment]
> * [x]  I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)

Why don't you try this for a change

![image](https://user-images.githubusercontent.com/6623388/202292145-fecd5bdd-60b0-446f-b785-6b3a396501cb.png)
