### ISSUE TITLE
Broken dependencies show as 'present'

### ISSUE THREAD

**Issue by dirkf** [yt-dlp/yt-dlp#5561]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.11.11** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

>I've verified that I'm running yt-dlp version 2022.11.11 (update instructions) Git HEAD d7b460d0e

><strike>I've checked that all provided URLs are playable in a browser with the same IP and same login details</strike> N/A

The function `_get_exe_version_output()` used in checking the version of dependencies like _ffprobe_ doesn't check whether running the program failed. 

In the test below I aliased ffprobe to `wc`, the POSIX word count program, which returns error 1 when invoked as `wc -version`. Even though the supposed _ffprobe_ program couldn't respond to `-version`, its output was considered valid and led to the program being listed as `present`.

This is a possible improvement where the string `**broken**` would be shown instead of `present` in such a case, but doubtless there are other resolutions that would be as valid or better.
```diff
--- old/yt_dlp/utils.py
+++ new/yt_dlp/utils.py
@@ -2703,8 +2703,10 @@
         # STDIN should be redirected too. On UNIX-like systems, ffmpeg triggers
         # SIGTTOU if yt-dlp is run in the background.
         # See https://github.com/ytdl-org/youtube-dl/issues/955#issuecomment-209789656
-        stdout, _, _ = Popen.run([encodeArgument(exe)] + args, text=True,
+        stdout, _, ret = Popen.run([encodeArgument(exe)] + args, text=True,
                                  stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
+        if ret != 0:
+            return None
     except OSError:
         return False
     return stdout
@@ -2726,6 +2728,8 @@
     """ Returns the version of the specified executable,
     or False if the executable is not present """
     out = _get_exe_version_output(exe, args)
+    if out is None:
+        return '**broken**'
     return detect_exe_version(out, version_re, unrecognized) if out else False
 ```
For a real-life example of this in yt-dl see https://github.com/ytdl-org/youtube-dl/issues/31355.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the <strike>WHOLE</strike> output (starting with `[debug] Command-line config`) and insert it below: showing only debug output for the issue

### Complete Verbose Output

```shell
$ ln -s $(which ffmpeg) ./ffmpeg
$ ln -s $(which wc) ./ffprobe
$ python3.9 -m yt_dlp -v -F 'https://drive.google.com/file/d/1TJlxla4cNxKseUTZ7OKKJmE4ct2dxQSY/view?usp=drivesdk' --ffmpeg-location  .
[debug] Command-line config: ['-v', '-F', 'https://drive.google.com/file/d/1TJlxla4cNxKseUTZ7OKKJmE4ct2dxQSY/view?usp=drivesdk', '--ffmpeg-location', '.']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.11.11 [8b644025b] (source)
[debug] Lazy loading extractors is disabled
[debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
[debug] Git HEAD: d7b460d0e
[debug] Python 3.9.15 (CPython i686 32bit) - Linux-4.4.0-210-generic-i686-with-glibc2.23 (OpenSSL 1.1.1s  1 Nov 2022, glibc 2.23)
[debug] exe versions: ffmpeg 4.3, ffprobe present
[debug] Optional libraries: Cryptodome-3.11.0, certifi-2019.11.28, secretstorage-3.2.0, sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Loaded 1725 extractors
...
```

**Comment by Aromik** [comment]
So is this a bug that will get fixed or do I need to try fixing the ffprobe installation?

**Comment by dirkf** [comment]
Response in the yt-dl thread.

**Comment by dirkf** [comment]
The trick both here and in yt-dl is the logic whereby the broken program both gets listed as broken and is marked as not available.
