### ISSUE TITLE
Incorrect filenames with --print-json and -x

### ISSUE THREAD

**Issue by yellowsink** [yt-dlp/yt-dlp#5579]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.11.11** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

When using extract audio with print-json (I am invoking yt-dlp from another program), both the `filename` and `_filename` fields contain the filename of the file *before* audio extraction, with no way to get the actual resulting file.

This is a problem because I use these fields to read the resultant file off of the disk, yet the extension is often incorrect.

I suggest either changing one of these fields to take into account the final filename after extraction, or add a new field for this purpose.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
Output is too many characters for a Github issue body (presumably due to JSON).

Check this gist: https://gist.github.com/yellowsink/1ba2ae5ec6dc0ce86c412e3777ebbef6
```

**Comment by pukkandan** [comment]
The final filename can be obtained only after the download+postprocess

```
❯ yt-dlp test:youtube -O after_move:filepath -vx --no-sim
[debug] Command-line config: ['--ignore-config', 'test:youtube', '-O', 'after_move:filepath', '-vx', '--no-sim']
[debug] Encodings: locale cp65001, fs utf-8, pref cp65001, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.11.11 [8b644025b] (source)
[debug] Lazy loading extractors is disabled
[debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
[debug] Git HEAD: 9f14daf22
[debug] Python 3.11.0 (CPython AMD64 64bit) - Windows-10-10.0.22000-SP0 (OpenSSL 1.1.1q  5 Jul 2022)
[debug] exe versions: ffmpeg N-107787-gc469c3c3b1-20220814 (fdk,setts), ffprobe N-107787-gc469c3c3b1-20220814, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1725 extractors
[debug] [TestURL] Extracting URL: test:youtube
[TestURL] Test URL: https://www.youtube.com/watch?v=BaW_jenozKc&t=1s&end=9
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=BaW_jenozKc&t=1s&end=9
[youtube] BaW_jenozKc: Downloading webpage
[youtube] BaW_jenozKc: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[info] BaW_jenozKc: Downloading 1 format(s): 251
[debug] Invoking http downloader on "https://rr3---sn-gwpa-jjwe.googlevideo.com/videoplayback?expire=1668755760&ei=0Nx2Y6niJdW2rtoPgIekoAU&ip=49.37.234.125&id=o-ABFLaP209_RiQQFEkfUyGhZJEG97s9LTDns050ZbSZVA&itag=251&source=youtube&requiressl=yes&mh=Rf&mm=31%2C29&mn=sn-gwpa-jjwe%2Csn-gwpa-h55e7&ms=au%2Crdu&mv=m&mvi=3&pl=20&initcwndbps=218750&spc=SFxXNtaZdBUpFrJxFjKw9cC-NmTA_t0&vprv=1&svpuc=1&mime=audio%2Fwebm&gir=yes&clen=142292&dur=9.841&lmt=1506055557712479&mt=1668733735&fvip=1&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIhAP70gxktzy_ZDQFuTTxbNVfBviWsC_NilNBNwZLBGSx_AiBVamyCG6G_LNBQjdc0YA92ir0OhV_rxlIk3atn4HWfoQ%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgSTIuMLtS6eN55YuwdKrv7iWGtyqo8EzCh90XEaoB1CgCIQDZcugrF00KqNLZ_kDBkoxl6ZFngLJUrrDH_5mOtj6d_A%3D%3D"
[debug] File locking is not supported. Proceeding without locking
[download] Destination: youtube-dl test video ＂'⧸⧹ä↭𝕐 [BaW_jenozKc].webm
[debug] ffmpeg command line: ffprobe -show_streams "file:youtube-dl test video ＂'⧸⧹ä↭𝕐 [BaW_jenozKc].webm"
[ExtractAudio] Destination: youtube-dl test video ＂'⧸⧹ä↭𝕐 [BaW_jenozKc].opus
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:youtube-dl test video ＂'⧸⧹ä↭𝕐 [BaW_jenozKc].webm" -vn -acodec copy -movflags "+faststart" "file:youtube-dl test video ＂'⧸⧹ä↭𝕐
[BaW_jenozKc].opus"
Deleting original file youtube-dl test video ＂'⧸⧹ä↭𝕐 [BaW_jenozKc].webm (pass -k to keep)
D:\Programs\Source\yt-dlp\yt-dlp\youtube-dl test video ＂'⧸⧹ä↭𝕐 [BaW_jenozKc].opus
```

Replace `filepath` with `%()j` to get the full json

**Comment by yellowsink** [comment]
`-O after_move:filepath` is exactly what I needed, thank you very much :)
