### ISSUE TITLE
Ssl Error

### ISSUE THREAD

**Issue by niranjantechofficial** [yt-dlp/yt-dlp#5583]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.11.11** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I deployed one Telegram bot.. That was a Url to tg file convert bot

There when i put url it said SSL error 

Bot deployed on heroku. 

Can anyone say howto fix

![Screenshot_2022-11-18-11-52-49-858_org telegram messenger](https://user-images.githubusercontent.com/61946705/202635147-3bac6ed4-072e-4a2b-9620-aebde57aed30.jpg)

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
Try `--no-check-certificate`

---

Do not abuse the "Question" template to post incomplete issues/feature requests.

Properly fill out an appropriate issue form

**Comment by niranjantechofficial** [comment]
Where i need to use that brother... Can i send you source code once check for me

**Comment by niranjantechofficial** [comment]
> Try `--no-check-certificate`
> 
> Do not abuse the "Question" template to post incomplete issues/feature requests.
> 
> Properly fill out an appropriate issue form

Where i need to use that brother... Can i send you source code once check for me
