### ISSUE TITLE
Ubuntu support?

### ISSUE THREAD

**Issue by Karel4** [yt-dlp/yt-dlp#5584]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.11.11** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Ubuntu 18.04 not supported anymore because lastest Python there is 3.6.x?

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by flashdagger** [comment]
Python 3.6 support was dropped for further development. Would you consider to [install a higher Python version](https://askubuntu.com/questions/1086649/how-to-update-python-to-the-latest-version-on-ubuntu-18-04) or take a look into [pyenv](https://github.com/pyenv/pyenv#installation)?

**Comment by pukkandan** [comment]
Or, use the standalone executable

**Comment by csehszlovakze** [comment]
> Python 3.6 support was dropped for further development. Would you consider to [install a higher Python version](https://askubuntu.com/questions/1086649/how-to-update-python-to-the-latest-version-on-ubuntu-18-04) or take a look into [pyenv](https://github.com/pyenv/pyenv#installation)?

`apt` on ubuntu 18.04 doesn't work with any python newer than 3.6. @Karel4 you'll have to use `yt-dlp_linux` (which has a newer embedded python) or you can upgrade your ubuntu install, 22.04.1 is out (new LTS first point release).
