### ISSUE TITLE
Sometimes video from youtube videos are not loaded (only sound is loaded) when using mpv + ytdl_hook.lua

### ISSUE THREAD

**Issue by soredake** [yt-dlp/yt-dlp#5592]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.11.11** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Ukraine

### Provide a description that is worded well enough to be understood

Sometimes video from youtube videos are not loaded (only sound is loaded) when using mpv + ytdl_hook.lua, example log from mpv:
```
Could not read init fragment.
EDL: source file 'edl://!mp4_dash,init=<extremely long list of urls>' has unknown duration.
 (+) Audio --aid=1 --alang=eng (*) (opus 2ch 48000Hz)
File tags:
 Uploader: - PalarNIK -
 Channel_URL: https://www.youtube.com/channel/UCIHbm6fOAttI_HzIWTSBl_Q
AO: [wasapi] 48000Hz stereo 2ch float
```

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
Log is too long to paste there, so i uploaded it here https://privatebin.net/?009492a4c966be7f#6GovqgJUcjxSqcBKA1HqQ5jnn6JEEtEfLyYA4Fx1uofU
```

**Comment by soredake** [comment]
Initially reported [here](https://github.com/yt-dlp/yt-dlp/issues/985#issuecomment-1152968978), then [here ](https://github.com/mpv-player/mpv/issues/10873)

**Comment by pukkandan** [comment]
mpv uses yt-dlp to extract video URL and ffmpeg to do the actual streaming. The log you have provided is of ffmpeg. Does everything work as expected if you download the video directly with yt-dlp? If so, nothing we can do. If not, provide verbose log of the same

**Comment by soredake** [comment]
>Does everything work as expected if you download the video directly with yt-dlp?

I'll try to replicate it again with pure yt-dlp.

> If so, nothing we can do.

So, it's better for me to report this to ffmpeg directly?

**Comment by pukkandan** [comment]
Not sure. Assuming there is no issue from yt-dlp, you can try to bring it it to mpv devs attention again. They should be able to provide better debugging steps and help you figure out where exactly the issue is happening
