### ISSUE TITLE
I don't know anything about coding，is there can provide a Windows GUI exe,thanks

### ISSUE THREAD

**Issue by Ju9aad** [yt-dlp/yt-dlp#5598]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.11.11** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

I don't know anything about coding，is there can provide a Windows GUI exe,thanks！

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
No, you may use one of the third party GUIs https://www.reddit.com/r/youtubedl/wiki/info-guis/

**Comment by wtechgo** [comment]
Tartube is one of the better GUI afaik.

VidHop on GitHub from WTechGo is not GUI but removes the need to figure out all commands. It's available on Windows as a Docker app. Watch the videos.
