### ISSUE TITLE
Go extractor failing

### ISSUE THREAD

**Issue by tv21** [yt-dlp/yt-dlp#5616]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.11.11** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

USA

### Provide a description that is worded well enough to be understood

It appears that the Go extractor isn't working anymore, at least for disny channel content.  It was been working fine in the past (last week Wednesday), but not today.  The output shown below uses the exact same options that worked last week, except for the addition of -vU of course.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['--restrict-filenames', '--ap-mso', 'Redacted', '--ap-username', 'PRIVATE', '--ap-password', 'PRIVATE', '-vU', 'https://disneynow.com/shows/the-villains-of-valley-view/season-01/episode-16-we-dont-care/vdka30531362']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.11.11 [8b64402] (zip)
[debug] Python 3.8.10 (CPython x86_64 64bit) - Linux-5.4.0-132-generic-x86_64-with-glibc2.29 (OpenSSL 1.1.1f  31 Mar 2020, glibc 2.31)
[debug] exe versions: ffmpeg 4.4-static (setts), ffprobe 4.4-static
[debug] Optional libraries: certifi-2019.11.28, pycrypto-2.6.1, secretstorage-2.3.1, sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Loaded 1723 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.11.11, Current version: 2022.11.11
yt-dlp is up to date (2022.11.11)
[debug] [Go] Extracting URL: https://disneynow.com/shows/the-villains-of-valley-view/season-01/episode-16-we-dont-care/vdka30531362
[Go] vdka30531362: Downloading JSON metadata
[debug] Loading ap-mvpd.DisneyChannels from cache
[Go] VDKA30531362: Downloading Provider Redirect Page
ERROR: [Go] vdka30531362: Unable to extract post url; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 674, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/go.py", line 250, in _real_extract
    auth = self._extract_mvpd_auth(
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/adobepass.py", line 1707, in _extract_mvpd_auth
    provider_login_page_res = post_form(
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/adobepass.py", line 1395, in post_form
    post_url = self._html_search_regex(r'<form[^>]+action=(["\'])(?P<url>.+?)\1', form_page, 'post url', group='url')
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 1264, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 1228, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
```

**Comment by bashonly** [comment]
Not a Go extractor issue. This is an AdobePass issue, specifically with your MSO. related: #2188

it works for me with my MSO credentials:
```
[debug] [Go] Extracting URL: https://disneynow.com/shows/the-villains-of-valley-view/season-01/episode-16-we-dont-care/vdka30531362
[Go] vdka30531362: Downloading JSON metadata
[Go] VDKA30531362: Downloading Provider Redirect Page
[Go] VDKA30531362: Confirming auto login
[Go] VDKA30531362: Retrieving Session
[debug] Saving ap-mvpd.DisneyChannels to cache
[Go] VDKA30531362: Retrieving Authorization Token
[debug] Saving ap-mvpd.DisneyChannels to cache
[Go] VDKA30531362: Retrieving Media Token
[Go] VDKA30531362: Downloading JSON metadata
[Go] VDKA30531362: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[info] Available formats for VDKA30531362:
ID        EXT           RESOLUTION FPS │   FILESIZE   TBR PROTO │ VCODEC        VBR ACODEC    ABR
─────────────────────────────────────────────────────────────────────────────────────────────────
ULNK_MPD  unknown_video unknown        │                  http  │ unknown           unknown
ULNK-214  mp4           256x144     15 │ ~ 37.17MiB  215k m3u8  │ avc1.4d000c  215k mp4a.40.5  0k
ULNK-413  mp4           416x234     30 │ ~ 71.69MiB  414k m3u8  │ avc1.4d000d  414k mp4a.40.5  0k
ULNK-751  mp4           640x360     30 │ ~130.13MiB  751k m3u8  │ avc1.4d001e  751k mp4a.40.5  0k
ULNK-1702 mp4           960x540     30 │ ~294.97MiB 1703k m3u8  │ avc1.4d001f 1703k mp4a.40.5  0k
ULNK-3186 mp4           1280x720    60 │ ~551.91MiB 3186k m3u8  │ avc1.4d001f 3186k mp4a.40.5  0k
ULNK-4757 mp4           1280x720    60 │ ~824.11MiB 4758k m3u8  │ avc1.64001f 4758k mp4a.40.5  0k
ULNK-6165 mp4           1280x720    60 │ ~  1.04GiB 6165k m3u8  │ avc1.64001f 6165k mp4a.40.5  0k
```

since you have redacted your MSO's name, there is nothing much that can be done with this issue report

**Comment by bashonly** [comment]
> [debug] Loading ap-mvpd.DisneyChannels from cache

you could try clearing your cache to see if that helps

**Comment by tv21** [comment]
Well although I did not want to reveal who the MSO is, it is not DTV.  But anyway, how do you clear the cache?  I didn't know yt-dlp even had one.

**Comment by pukkandan** [comment]
> But anyway, how do you clear the cache?

--rm-cache



> WI did not want to reveal who the MSO is

We cannot do anything in that case. Closing

**Comment by tv21** [comment]
Clearing the cache did not help.

[debug] Command-line config: ['--restrict-filenames', '--ap-mso', 'REDACTED', '--ap-username', 'PRIVATE', '--ap-password', 'PRIVATE', '-vU', 'https://disneynow.com/shows/the-villains-of-valley-view/season-01/episode-16-we-dont-care/vdka30531362']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.11.11 [8b64402] (zip)
[debug] Python 3.8.10 (CPython x86_64 64bit) - Linux-5.4.0-132-generic-x86_64-with-glibc2.29 (OpenSSL 1.1.1f  31 Mar 2020, glibc 2.31)
[debug] exe versions: ffmpeg 4.4-static (setts), ffprobe 4.4-static
[debug] Optional libraries: certifi-2019.11.28, pycrypto-2.6.1, secretstorage-2.3.1, sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Loaded 1723 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.11.11, Current version: 2022.11.11
yt-dlp is up to date (2022.11.11)
[debug] [Go] Extracting URL: https://disneynow.com/shows/the-villains-of-valley-view/season-01/episode-16-we-dont-care/vdka30531362
[Go] vdka30531362: Downloading JSON metadata
[Go] VDKA30531362: Downloading Provider Redirect Page
ERROR: [Go] vdka30531362: Unable to extract post url; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 674, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/go.py", line 250, in _real_extract
    auth = self._extract_mvpd_auth(
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/adobepass.py", line 1707, in _extract_mvpd_auth
    provider_login_page_res = post_form(
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/adobepass.py", line 1395, in post_form
    post_url = self._html_search_regex(r'<form[^>]+action=(["\'])(?P<url>.+?)\1', form_page, 'post url', group='url')
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 1264, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 1228, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
