### ISSUE TITLE
Inconsistency between `--break-on-existing` and `--playlist-end` with `--break-per-input` enabled

### ISSUE THREAD

**Issue by Taion1** [yt-dlp/yt-dlp#5619]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.11.11** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

#5439 introduced a slight issue with `--break-on-existing` + `--break-per-input`. That option breaks per input URL but almost certainly what was intended was break per playlist. This is a subtle distinction that previously was not exposed to users. Unless there is a technical limitation, we should restore parity with `--playlist-end` and `-I`.

Options like `--break-on-reject` are affected as well but they are less closely related to `--playlist-end`. `--playlist-end` and `--break-on-existing` both have the lazy downloading and used to be superficially equivalent for this purpose.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--download-archive', 'test.txt', '--break-on-existing', '--break-per-input', 'https://www.youtube.com/@Rarran']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.11.11 [8b644025b]
[debug] Lazy loading extractors is disabled
[debug] Python 3.10.6 (CPython AMD64 64bit) - Windows-10-10.0.19044-SP0 (OpenSSL 1.1.1n  15 Mar 2022)
[debug] exe versions: ffmpeg 5.1-essentials_build-www.gyan.dev (setts), ffprobe 5.1-essentials_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1724 extractors
[debug] Loading archive file 'test.txt'
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.11.11, Current version: 2022.11.11
yt-dlp is up to date (2022.11.11)
[debug] [youtube:tab] Extracting URL: https://www.youtube.com/@Rarran
[youtube:tab] @Rarran: Downloading webpage
[debug] [youtube:tab] Selected tab: 'videos' (videos), Requested tab: ''
[youtube:tab] Downloading all uploads of the channel. To download only the videos in a specific tab, pass the tab's URL
[youtube:tab] @Rarran/streams: Downloading webpage
[debug] [youtube:tab] Selected tab: 'streams' (live), Requested tab: 'streams'
[youtube:tab] @Rarran/shorts: Downloading webpage
[debug] [youtube:tab] Selected tab: 'shorts' (shorts), Requested tab: 'shorts'
[youtube:tab] Downloading as multiple playlists, separated by tabs. To download as a single playlist instead, pass https://www.youtube.com/playlist?list=UUrWJQayN_0HTwgxsuqYMVIA
[download] Downloading playlist: Rarran
[youtube:tab] Playlist Rarran: Downloading 3 items of 3
[download] Downloading item 1 of 3
[download] Downloading playlist: Rarran - Videos
[youtube:tab] Playlist Rarran - Videos: Downloading 1 items
[download] The IMPOSSIBLE Grand Tournament Hearthstone Challenge has already been recorded in the archive
[info] Encountered a video that is already in the archive, stopping due to --break-on-existing
```

**Comment by pukkandan** [comment]
> That option breaks per input URL but almost certainly what was intended was break per playlist

No, it is meant to break **per input URL** exactly as the option name and docs suggest. If you want to break for each of the tabs, pass their URLs separately

**Comment by Taion1** [comment]
When I said "intended" I meant what the user probably intended, in that previously `--break-on-existing` + `--break-per-input` could be used to download all new videos from youtube channel URLs. That doesn't work anymore, but it is indeed working correctly according to the documentation. I was just politely suggesting that perhaps the "break-per-playlist" behavior would be more useful, for `--break-on-existing` at least.

Anyways, I am able to use `--playlist-end` instead. I also know about the alternative youtube playlist which contains all videos, but it also contains some junk items such as upcoming livestreams (including scheduled livestreams that never happened) and blocked copyrighted videos.
