### ISSUE TITLE
Unable to 'download JSON Metadata for Pluto TV stream,' HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>)

### ISSUE THREAD

**Issue by AmBintroGoof99** [yt-dlp/yt-dlp#5623]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.11.11** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Hi everyone. Excuse my mistakes in the way I'm reporting this. I am a noob trying to make sense of this. I'm trying to download a move off Pluto TV (URL: https://pluto.tv/en/on-demand/movies/philadelphia-1993-1-1) but keep on getting the following error:

`` C:\video downloader>yt-dlp https://pluto.tv/en/on-demand/movies/philadelphia-1993-1-1
[PlutoTV] philadelphia-1993-1-1: Downloading JSON metadata
ERROR: [PlutoTV] Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

C:\video downloader>yt-dlp -U
Latest version: 2022.11.11, Current version: 2022.11.11
yt-dlp is up to date (2022.11.11)

C:\video downloader> ``

Other URLs from the same website work just about fine, a few ones I've had success with:

https://pluto.tv/en/on-demand/movies/saving-private-ryan-paramount-pictures-lf-1998-1-1
https://pluto.tv/en/on-demand/movies/forrest-gump-1994-1-1

I dug through the forums and similar issues here, but couldn't figure exactly what should be done, so will greatly appreciate any feedback, and instructions-as simple as possible, PLEASE. It's a really favorite movie of mine, and may soon go away, so I want to grab it before it's gone. 

Thanks everyone, in advance!

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://pluto.tv/en/on-demand/movies/philadelphia-1993-1-1']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.11.11 [8b64402] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 2022-11-03-git-5ccd4d3060-full_build-www.gyan.dev (setts), ffprobe 2022-11-03-git-5ccd4d3060-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1723 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.11.11, Current version: 2022.11.11
yt-dlp is up to date (2022.11.11)
[debug] [PlutoTV] Extracting URL: https://pluto.tv/en/on-demand/movies/philadelphia-1993-1-1
[PlutoTV] philadelphia-1993-1-1: Downloading JSON metadata
ERROR: [PlutoTV] Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 674, in extract
  File "yt_dlp\extractor\plutotv.py", line 160, in _real_extract
  File "yt_dlp\extractor\common.py", line 1034, in download_content
  File "yt_dlp\extractor\common.py", line 998, in download_handle
  File "yt_dlp\extractor\common.py", line 868, in _download_webpage_handle
  File "yt_dlp\extractor\common.py", line 825, in _request_webpage

  File "yt_dlp\extractor\common.py", line 807, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 3692, in urlopen
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found
```

**Comment by bashonly** [comment]
> I dug through the forums and similar issues here, but couldn't figure exactly what should be done

This is indeed the same problem as #4625, which currently has no known solution or workaround AFAIK. If one is found, that issue will be updated. Closing this issue as a duplicate
