### ISSUE TITLE
xiaoheimi site support request

### ISSUE THREAD

**Issue by callista13** [yt-dlp/yt-dlp#5625]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.11.11** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Example URLs

- Single video : https://xiaoheimi.net/index.php/vod/play/id/42755/sid/1/nid/1.html
- Playlist : https://xiaoheimi.net/index.php/vod/detail/id/42755.html

### Provide a description that is worded well enough to be understood

request to be able to download single video and playlist from xiaoheimi

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://xiaoheimi.net/index.php/vod/play/id/42755/sid/1/nid/1.html']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.11.11 [8b644025b]
[debug] Lazy loading extractors is disabled
[debug] Python 3.9.12 (CPython AMD64 64bit) - Windows-10-10.0.19042-SP0 (OpenSSL 1.1.1n  15 Mar 2022)
[debug] exe versions: ffmpeg N-107541-g81ebf40efa-20220727 (setts), ffprobe N-107541-g81ebf40efa-20220727, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.15.0, brotli-None, certifi-2022.09.24, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1726 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.11.11, Current version: 2022.11.11
yt-dlp is up to date (2022.11.11)
[debug] [generic] Extracting URL: https://xiaoheimi.net/index.php/vod/play/id/42755/sid/1/nid/1.html
[generic] 1: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] 1: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://xiaoheimi.net/index.php/vod/play/id/42755/sid/1/nid/1.html
Traceback (most recent call last):
  File "C:\Users\cindyk\Anaconda3\lib\site-packages\yt_dlp\YoutubeDL.py", line 1495, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\cindyk\Anaconda3\lib\site-packages\yt_dlp\YoutubeDL.py", line 1571, in __extract_info
    ie_result = ie.extract(url)
  File "C:\Users\cindyk\Anaconda3\lib\site-packages\yt_dlp\extractor\common.py", line 678, in extract
    ie_result = self._real_extract(url)
  File "C:\Users\cindyk\Anaconda3\lib\site-packages\yt_dlp\extractor\generic.py", line 2471, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://xiaoheimi.net/index.php/vod/play/id/42755/sid/1/nid/1.html
```

**Comment by coletdjnz** [comment]
This site looks to be primarily used for piracy.
