### ISSUE TITLE
How to get response headers

### ISSUE THREAD

**Issue by villers3** [yt-dlp/yt-dlp#5626]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.11.11** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

  args = [
        # request to download with video ID
        "yt-dlp", id,
        # output to stdout (needed for streaming)
        "-o", "-"]

args.append('--add-header')
args.append('range:bytes=0-')

downloader_proc = subprocess.Popen(
        args,
        stdin=subprocess.DEVNULL,
        stdout=subprocess.PIPE,
        stderr=subprocess.DEVNULL # don't fill up server logs
    )

browser needs
headers = {
        "Accept-Ranges": "bytes",
        "Content-Length": str(filesize),
        "Content-Range": F"bytes {0}-{filesize-1}/{totalfilesize}"
 }

How to get response headers？

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
You can't. What are you actually trying to accomplish?

**Comment by villers3** [comment]
I need to respond to the client with the following information

"Accept-Ranges": "bytes",
"Content-Length": str(filesize),
"Content-Range": F"bytes {0}-{filesize-1}/{totalfilesize}"
status_code = 206

To achieve video preload playback or stream

**Comment by pukkandan** [comment]
Are you asking how to "**set request headers**", not "get response headers"? If so, just use `--add-headers`

**Comment by villers3** [comment]
I need to get response header

The previous code already used --add-headers

like this：
  args.append('--add-header')
  args.append('range:bytes=0-')

request process：
<video controls="" name="media" width="'.$width.'" height="'.$height.'" >
   <source  src="http://127.0.0.1:4000/down?v='.$id.'" type="video/mp4">
</video>

@app.get("/down")
async def api_dl(
    request:Request,
    v: str):
   stream = stream_from_yt(v,  request.headers)
   first_chunk = await stream.__anext__() # peek first chunk
   headers = {}
   async def joined_stream():
        # attach the first chunk back to the generator
        yield first_chunk

        # pass on the rest
        async for chunk in stream:
            yield chunk
   return StreamingResponse(joined_stream(), media_type = mime_type,headers=headers,status_code=206)

async def stream_from_yt(id: str, headers = None ,format: str = "best"):
   args = [
        # request to download with video ID
        "yt-dlp", id,
        # output to stdout (needed for streaming)
        "-o", "-",
        # specify output format
        "-f", format,]
   for i in headers:
        if i == 'range' and 'bytes=0-' ==headers[i]:
            args.append('--embed-metadata')
        args.append('--add-header')
        args.append(i+':'+headers[i])

    downloader_proc = subprocess.Popen(
        args,
        stdin=subprocess.DEVNULL,
        stdout=subprocess.PIPE,
        stderr=subprocess.DEVNULL # don't fill up server logs
    )
   while True:
            # print('try to read bucket from downloader proc...')
            bucket = downloader_proc.stdout.read(131072)

            if len(bucket) == 0:
                break

            total += len(bucket)
            print(f'{id} :sending {len(bucket)} bytes... (total sent: {total})')

            # return the result chunk
            yield bucket

            await aio_dummy()

**Comment by dirkf** [comment]
Well, `--print-traffic`?

On a larger point, consider calling the yt-dlp module directly rather than using `Popen()` (so `debug_printtraffic`).

**Comment by villers3** [comment]
Thanks!
Yes, I tried "--print-traffic", but how many responses does it return, I don't know how to separate the correct response headers.
I will try calling the yt-dlp module directly

**Comment by dirkf** [comment]
You just get the HTTP stream as received from the server, one header per line. I didn't go into details but I was able to parse somewhat similar output from _wget_ with a regex like this (no doubt further assembly is required) :
```
r'''(?x)
    \s*Location:\s+(?P<url>[\S]+?)($|\s+\[following\])|
    \s+HTTP/[\d.]+\s+(?P<code>[1-5]\d\d)(?:\s+(?P<reason>.*))?$|
    \s+Content-Type:\s+(?P<charset>.+)$|
    \s+Content-Encoding:\s+(?P<encoding>\S+)|
    (?P<other>\S.*)$
'''
```

**Comment by villers3** [comment]
currently implemented
`
headers = res['headers']
for i in headers:
    args.append('--add-header')
    args.append(i+':'+headers[i])
args.append('--print-traffic')

downloader_proc = subprocess.Popen(
    args,
    stdin=subprocess.DEVNULL,
    stdout=subprocess.PIPE,
    stderr=subprocess.DEVNULL # don't fill up server logs
)
while True:
  bucket = downloader_proc.stdout.read(131072)
  pattern=re.compile(rb"reply:",re.DOTALL)
  if pattern.search(bucket):
      bucket = re.sub(rb'.*?(?<=reply:)(?!.*?reply:).*?(?=header:)',b'',bucket,1,re.DOTALL)
    def dashrepl(matchobj):
      header=re.sub(rb'header:',b'',matchobj.group(1))
      header=header.decode('utf-8')
      header=header.split(":", 1)
      key = header[0].strip()
      val = header[1].strip()
      headers[key]=val
      return b''
    bucket = re.sub(rb'(header:.*)\r\n',dashrepl,bucket )
`
