### ISSUE TITLE
Default to downloading AV1 video 

### ISSUE THREAD

**Issue by orowith2os** [yt-dlp/yt-dlp#5629]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.11.11** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Currently, YouTube provides multiple codecs for video, such as AV1, VP9, VP8, and H264. 

From some recent tests I did, AV1 video is comparable to all other codecs *that have hardware decoding* (at ~1080p and below).

Thus, I believe it would be beneficial to default to downloading AV1 video if available, and other codecs should AV1 not be there.

It might also be possible to clean up the arguments for downloading videos so that it's easier to download videos in a specific way, as the current method seems to be very confusing.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
https://github.com/yt-dlp/yt-dlp/issues/458#issuecomment-913082217

**Comment by orowith2os** [comment]
interesting, I didn't notice that launch arg.

And IIRC Apple now provides AV1 support in their M1 macs, no clue on its current state in Windows.

**Comment by azzydoesgit** [comment]
> interesting, I didn't notice that launch arg.
> 
> And IIRC Apple now provides AV1 support in their M1 macs, no clue on its current state in Windows.

Windows supports it out of the box on newer installs, otherwise, they have the codec in their store just like HEVC.

So I think it's worth considering making the switch.

**Comment by pukkandan** [comment]
Yes, it is being planned. See https://github.com/yt-dlp/yt-dlp/issues/4846

**Comment by Xan-Kun** [comment]
Please add a legacy switch to disable AV1 (or only use av1 as a last resort) since lots of machines don't support HW-acceleration for AV1 and produce stutter and other artifacts.

**Comment by bashonly** [comment]
> Please add a legacy switch to disable AV1

`--compat-opt prefer-vp9-sort`

---

Closed by 3945677a75e94a1fecc085432d791e1c21220cd3
