### ISSUE TITLE
HTTP 406 EROR Not Acceptable

### ISSUE THREAD

**Issue by shahidhasanzai** [yt-dlp/yt-dlp#563]
https://www.sonyliv.com/shows/hero-gayab-mode-on-1700000278/amal-nanda-revived-1000127390?watch=true

this is not downloading Showing HTTP 406 EROR Not Acceptable

![image](https://user-images.githubusercontent.com/75906314/126869528-a544e248-45ba-4e90-b3f6-bcb7343aa92f.png)

**Comment by pukkandan** [comment]
406 means that you dont have permission to access the video

### IGNORING THE ISSUE TEMPLATE WILL RESULT IN ISSUE CLOSED AS INCOMPLETE

Create a new issue using the correct template with all necessary information including the `--verbose` output
