### ISSUE TITLE
[youtube] Specific video(s?) always results in download error, despite all other videos working fine

### ISSUE THREAD

**Issue by zpangwin** [yt-dlp/yt-dlp#5631]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.11.11** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

In general, `yt-dlp` works great for me on all other youtube videos but I have come across a particular video that gives me an error that *claims* to be due to a connection issue, but which does not appear to be related to connection dropping or me being unable to reach youtube  (e.g. `yt-dlp` works fine with other videos but *this* video *always* fails). The video in question is [https://www.youtube.com/watch?v=iafA9X6_IhM](https://www.youtube.com/watch?v=iafA9X6_IhM) which is a video on HVAC Blower motor repair/cleaning/maintenance and has no issues playing in web browser. I can live without the video but wanted to report this in case it has broader implications and there is something going on that might end up preventing other youtube videos from being downloaded as well.

My hope with the ticket is that this will lead to getting ahead of a potential edge-case scenario that could prevent other youtube videos from being downloaded, or if that is not applicable, then to possibly have an updated error message that is more descriptive of whatever the actual problem is.

I did search for other tickets with "[read operation timed out](https://github.com/yt-dlp/yt-dlp/issues?q=is%3Aissue+is%3Aopen+%22read+operation+timed+out%22)" and/or "[HTTP Error 503: Service Unavailable](https://github.com/yt-dlp/yt-dlp/issues?q=is%3Aissue+is%3Aopen+%22HTTP+Error+503%3A+Service+Unavailable%22+)" but all the results were either for different sites, specified parameters that I was *not* passing, and/or were for older versions of `yt-dlp`. Those also appeared to have slightly different error messages, although [2898](https://github.com/yt-dlp/yt-dlp/issues/2898)'s errors seemed the closest to mine, but again I was **not** using the `--live-from-start` option. [5535](https://github.com/yt-dlp/yt-dlp/issues/5535) also had some similarities but was for a different site and didn't mention anything about "read operation timed out" - so if this is a duplicate, then apologies; I did *try* at least. :-)

## Process steps / system info / app version

    $ yt-dlp --version
    2022.11.11
     
    $ inxi -S
    System:
      Host: <redacted> Kernel: 5.19.16-100.fc35.x86_64 arch: x86_64 bits: 64 Console: pty pts/1
        Distro: Fedora release 35 (Thirty Five)
     
    $ ping -c 1 www.youtube.com
    PING youtube-ui.l.google.com (64.233.177.93) 56(84) bytes of data.
    64 bytes from yx-in-f93.1e100.net (64.233.177.93): icmp_seq=1 ttl=104 time=13.5 ms
     
    --- youtube-ui.l.google.com ping statistics ---
    1 packets transmitted, 1 received, 0% packet loss, time 0ms
    rtt min/avg/max/mdev = 13.521/13.521/13.521/0.000 ms
     
    // don't worry - I captured the -vU output too (I have it in the verbose output section below)
    $ yt-dlp https://www.youtube.com/watch?v=iafA9X6_IhM
    [youtube] iafA9X6_IhM: Downloading webpage
    [youtube] iafA9X6_IhM: Downloading android player API JSON
    [youtube] iafA9X6_IhM: Downloading MPD manifest
    [youtube] iafA9X6_IhM: Downloading MPD manifest
    [info] iafA9X6_IhM: Downloading 1 format(s): 244+251
    [dashsegments] Total fragments: 34
    [download] Destination: Pull and Clean on a Blower Wheel (Blower Housing) (step 1-7) [iafA9X6_IhM].f244.webm
    [download] Got error: The read operation timed out. Retrying (1/10)...
    [download] Got error: The read operation timed out. Retrying (2/10)...
    [download] Got error: The read operation timed out. Retrying (3/10)...
    [download] Got error: The read operation timed out. Retrying (4/10)...
    [download] Got error: HTTP Error 503: Service Unavailable. Retrying (5/10)...
    [download] Got error: HTTP Error 503: Service Unavailable. Retrying (6/10)...
    [download] Got error: HTTP Error 503: Service Unavailable. Retrying (7/10)...
    [download] Got error: HTTP Error 503: Service Unavailable. Retrying (8/10)...
    [download] Got error: HTTP Error 503: Service Unavailable. Retrying (9/10)...
    [download] Got error: HTTP Error 503: Service Unavailable. Retrying (10/10)...
    [download] Got error: HTTP Error 503: Service Unavailable. Giving up after 10 retries
    ERROR: fragment 1 not found, unable to continue
     
    [download] Destination: Pull and Clean on a Blower Wheel (Blower Housing) (step 1-7) [iafA9X6_IhM].f251.webm
    [download] 100% of    2.45MiB in 00:00:00 at 6.95MiB/s
         
    $ ls -acl
    total 2512
    drwxr-xr-x. 1 me me     524 Nov 23 16:39  .
    drwxr-xr-x. 1 me me     706 Nov 23 16:37  ..
    -rw-rw----. 1 me me       0 Nov 23 16:37 'Pull and Clean on a Blower Wheel (Blower Housing) (step 1-7) [iafA9X6_IhM].f244.webm.part'
    -rw-rw----. 1 me me      50 Nov 23 16:37 'Pull and Clean on a Blower Wheel (Blower Housing) (step 1-7) [iafA9X6_IhM].f244.webm.ytdl'
    -rw-rw----. 1 me me 2565275 Nov 23 16:39 'Pull and Clean on a Blower Wheel (Blower Housing) (step 1-7) [iafA9X6_IhM].f251.webm'
     
    //file contents - basically same thing as cat command:
    $ echo "$(< *.ytdl)"
    {"downloader": {"current_fragment": {"index": 0}}}

Despite the `HTTP Error 503` that is reported, I am able to watch the video fine in Firefox, LibreWolf, and chromium *without* requiring a login. I am also able to use `yt-dlp` on other videos without any issue. I have tested this on *and* off VPN but that makes no difference. I have tested this on 2 different computers (both running Fedora 35) and have the same issue on both.

When I open the webm file in vlc, it appears to only have audio which is confirmed in `mediainfo`:

    $ mediainfo *.webm
    General
    Complete name                            : Pull and Clean on a Blower Wheel (Blower Housing) (step 1-7) [iafA9X6_IhM].f251.webm
    Format                                   : WebM
    Format version                           : Version 4
    File size                                : 2.45 MiB
    Duration                                 : 2 min 57 s
    Overall bit rate                         : 116 kb/s
    Writing application                      : google/video-file
    Writing library                          : google/video-file
    
    Audio
    ID                                       : 1
    Format                                   : Opus
    Codec ID                                 : A_OPUS
    Duration                                 : 2 min 57 s
    Channel(s)                               : 2 channels
    Channel layout                           : L R
    Sampling rate                            : 48.0 kHz
    Bit depth                                : 16 bits
    Compression mode                         : Lossy
    Language                                 : Japanese
    Default                                  : Yes
    Forced                                   : No

However, the source video *does* indeed have video steams:

    $ yt-dlp --list-formats https://www.youtube.com/watch?v=iafA9X6_IhM
    [youtube] iafA9X6_IhM: Downloading webpage
    [youtube] iafA9X6_IhM: Downloading android player API JSON
    [youtube] iafA9X6_IhM: Downloading MPD manifest
    [youtube] iafA9X6_IhM: Downloading MPD manifest
    [info] Available formats for iafA9X6_IhM:
    ID       EXT   RESOLUTION FPS CH │  FILESIZE   TBR PROTO │ VCODEC        VBR ACODEC      ABR ASR MORE INFO
    ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
    sb2      mhtml 48x27        1    │                 mhtml │ images                                storyboard
    sb1      mhtml 81x45        1    │                 mhtml │ images                                storyboard
    sb0      mhtml 163x90       1    │                 mhtml │ images                                storyboard
    139-dash m4a   audio only        │   1.03MiB   50k dash  │ audio only        mp4a.40.5   50k 22k DASH audio, m4a_dash
    139      m4a   audio only      2 │   1.03MiB   49k https │ audio only        mp4a.40.5   49k 22k low, m4a_dash
    140-dash m4a   audio only        │   2.73MiB  130k dash  │ audio only        mp4a.40.2  130k 44k DASH audio, m4a_dash
    251-dash webm  audio only        │   2.45MiB  122k dash  │ audio only        opus       122k 48k DASH audio, webm_dash
    140      m4a   audio only      2 │   2.73MiB  130k https │ audio only        mp4a.40.2  130k 44k medium, m4a_dash
    251      webm  audio only      2 │   2.45MiB  116k https │ audio only        opus       116k 48k medium, webm_dash
    17       3gp   176x144      7  1 │   1.62MiB   77k https │ mp4v.20.3     77k mp4a.40.2    0k 22k 144p
    160      mp4   256x140     30    │ ~ 2.33MiB  108k dash  │ avc1.4d400b  108k video only          DASH video, mp4_dash
    278      webm  256x140     30    │ ~ 2.05MiB   95k dash  │ vp9           95k video only          DASH video, webm_dash
    133      mp4   426x234     30    │ ~ 5.23MiB  242k dash  │ avc1.4d400c  242k video only          DASH video, mp4_dash
    242      webm  426x234     30    │ ~ 4.76MiB  220k dash  │ vp9          220k video only          DASH video, webm_dash
    134-dash mp4   640x352     30    │   9.08MiB  620k dash  │ avc1.4d401e  620k video only          DASH video, mp4_dash
    134      mp4   640x352     30    │   9.08MiB  430k https │ avc1.4d401e  430k video only          360p, mp4_dash
    18       mp4   640x352     30  2 │ ~12.08MiB  559k https │ avc1.42001E  559k mp4a.40.2    0k 44k 360p
    243      webm  640x352     30    │ ~ 8.77MiB  406k dash  │ vp9          406k video only          DASH video, webm_dash
    135      mp4   854x470     30    │ ~24.96MiB 1155k dash  │ avc1.4d400b 1155k video only          DASH video, mp4_dash
    244      webm  854x470     30    │ ~16.26MiB  753k dash  │ vp9          753k video only          DASH video, webm_dash

## Verbose output

Note: I made only 1 modification to the verbose output which was to replace both occurrences of my wan ip with `<REDACTED_WAN_IP>`. Everything else is unaltered. Prior to running with the verbose output flag, I had removed the temp files from the previous run. e.g.

    rm *.{webm,part,ytdl}

Everything else is identical down to the exact temp files created on the 2nd run having exactly the same number of bytes as in the first run (as reported by `ls -acl` for both).

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
$ yt-dlp -vU https://www.youtube.com/watch?v=iafA9X6_IhM
    [debug] Command-line config: ['-vU', 'https://www.youtube.com/watch?v=iafA9X6_IhM']
    [debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
    [debug] yt-dlp version 2022.11.11 [8b64402] (zip)
    [debug] Python 3.10.8 (CPython x86_64 64bit) - Linux-6.0.5-100.fc35.x86_64-x86_64-with-glibc2.34 (OpenSSL 1.1.1q  FIPS 5 Jul 2022, glibc 2.34)
    [debug] exe versions: ffmpeg 4.4.3 (setts), ffprobe 4.4.3
    [debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2020.12.05, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.0
    [debug] Proxy map: {}
    [debug] Loaded 1723 extractors
    [debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
    Latest version: 2022.11.11, Current version: 2022.11.11
    yt-dlp is up to date (2022.11.11)
    [debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=iafA9X6_IhM
    [youtube] iafA9X6_IhM: Downloading webpage
    [youtube] iafA9X6_IhM: Downloading android player API JSON
    [youtube] iafA9X6_IhM: Downloading MPD manifest
    [youtube] iafA9X6_IhM: Downloading MPD manifest
    [debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
    [debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
    [debug] Default format spec: bestvideo*+bestaudio/best
    [info] iafA9X6_IhM: Downloading 1 format(s): 244+251
    [debug] Invoking dashsegments downloader on "https://manifest.googlevideo.com/api/manifest/dash/expire/1669262182/ei/BZd-Y7amLJK1igTiw6v4AQ/ip/<REDACTED_WAN_IP>/id/89a7c0f57ebf2213/source/youtube/requiressl/yes/playback_host/rr3---sn-vgqsrnsd.googlevideo.com/mh/cp/mm/31%2C29/mn/sn-vgqsrnsd%2Csn-q4fl6n6d/ms/au%2Crdu/mv/m/mvi/3/pl/24/tx/24280135/txs/24280135%2C24280136%2C24280137%2C24280138%2C24280139/hfr/all/as/fmp4_audio_clear%2Cwebm_audio_clear%2Cwebm2_audio_clear%2Cfmp4_sd_hd_clear%2Cwebm2_sd_hd_clear/initcwndbps/2305000/vprv/1/mt/1669240385/fvip/5/keepalive/yes/fexp/24001373%2C24007246/itag/0/sparams/expire%2Cei%2Cip%2Cid%2Csource%2Crequiressl%2Ctx%2Ctxs%2Chfr%2Cas%2Cvprv%2Citag/sig/AOq0QJ8wRQIgcPjpWp0-spexgOH6iLe13GA4NDIGi0r1QgCbx3AtkQYCIQD_87Zmfc_NTWs_zuEzfOs7w49eSOD-Bp0ans-KnmB6zA%3D%3D/lsparams/playback_host%2Cmh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps/lsig/AG3C_xAwRAIgFm7sYKv-KLE9Py5Z7PY69W7pr-_ellGoyP_45s4uF24CIFY1y1tm-V_B50n8BtbxlQoRujMOe_nQIKul4__ZFN2u"
    [dashsegments] Total fragments: 34
    [download] Destination: Pull and Clean on a Blower Wheel (Blower Housing) (step 1-7) [iafA9X6_IhM].f244.webm
    [download] Got error: The read operation timed out. Retrying (1/10)...
    [download] Got error: The read operation timed out. Retrying (2/10)...
    [download] Got error: The read operation timed out. Retrying (3/10)...
    [download] Got error: HTTP Error 503: Service Unavailable. Retrying (4/10)...
    [download] Got error: HTTP Error 503: Service Unavailable. Retrying (5/10)...
    [download] Got error: HTTP Error 503: Service Unavailable. Retrying (6/10)...
    [download] Got error: HTTP Error 503: Service Unavailable. Retrying (7/10)...
    [download] Got error: The read operation timed out. Retrying (8/10)...
    [download] Got error: HTTP Error 503: Service Unavailable. Retrying (9/10)...
    [download] Got error: HTTP Error 503: Service Unavailable. Retrying (10/10)...
    [download] Got error: HTTP Error 503: Service Unavailable. Giving up after 10 retries
      File "/usr/lib64/python3.10/runpy.py", line 196, in _run_module_as_main
        return _run_code(code, main_globals, None,
      File "/usr/lib64/python3.10/runpy.py", line 86, in _run_code
        exec(code, run_globals)
      File "/usr/local/bin/yt-dlp/__main__.py", line 17, in <module>
        yt_dlp.main()
      File "/usr/local/bin/yt-dlp/yt_dlp/__init__.py", line 968, in main
        _exit(*variadic(_real_main(argv)))
      File "/usr/local/bin/yt-dlp/yt_dlp/__init__.py", line 958, in _real_main
        return ydl.download(all_urls)
      File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3322, in download
        self.__download_wrapper(self.extract_info)(
      File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3297, in wrapper
        res = func(*args, **kwargs)
      File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1474, in extract_info
        return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
      File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1485, in wrapper
        return func(self, *args, **kwargs)
      File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1582, in __extract_info
        return self.process_ie_result(ie_result, download, extra_info)
      File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1641, in process_ie_result
        ie_result = self.process_video_result(ie_result, download=download)
      File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 2737, in process_video_result
        self.process_info(new_info)
      File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3182, in process_info
        partial_success, real_download = self.dl(fname, new_info)
      File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 2924, in dl
        return fd.download(name, new_info, subtitle)
      File "/usr/local/bin/yt-dlp/yt_dlp/downloader/common.py", line 446, in download
        ret = self.real_download(filename, info_dict)
      File "/usr/local/bin/yt-dlp/yt_dlp/downloader/dash.py", line 54, in real_download
        return self.download_and_append_fragments_multiple(*args, is_fatal=lambda idx: idx == 0)
      File "/usr/local/bin/yt-dlp/yt_dlp/downloader/fragment.py", line 381, in download_and_append_fragments_multiple
        return self.download_and_append_fragments(*args[0], **kwargs)
      File "/usr/local/bin/yt-dlp/yt_dlp/downloader/fragment.py", line 519, in download_and_append_fragments
        download_fragment(fragment, ctx)
      File "/usr/local/bin/yt-dlp/yt_dlp/downloader/fragment.py", line 468, in download_fragment
        if not self._download_fragment(ctx, fragment['url'], info_dict, headers):
      File "/usr/local/bin/yt-dlp/yt_dlp/downloader/fragment.py", line 124, in _download_fragment
        success, _ = ctx['dl'].download(fragment_filename, fragment_info_dict)
      File "/usr/local/bin/yt-dlp/yt_dlp/downloader/common.py", line 446, in download
        ret = self.real_download(filename, info_dict)
      File "/usr/local/bin/yt-dlp/yt_dlp/downloader/http.py", line 369, in real_download
        for retry in RetryManager(self.params.get('retries'), self.report_retry):
      File "/usr/local/bin/yt-dlp/yt_dlp/utils.py", line 5921, in __iter__
        self.error_callback(self.error, self.attempt, self.retries)
      File "/usr/local/bin/yt-dlp/yt_dlp/downloader/common.py", line 391, in report_retry
        RetryManager.report_retry(
      File "/usr/local/bin/yt-dlp/yt_dlp/utils.py", line 5928, in report_retry
        return error(f'{e}. Giving up after {count - 1} retries') if count > 1 else error(str(e))
      File "/usr/local/bin/yt-dlp/yt_dlp/downloader/common.py", line 394, in <lambda>
        error=IDENTITY if not fatal else lambda e: self.report_error(f'\r[download] Got error: {e}'),
      File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1004, in report_error
        self.trouble(f'{self._format_err("ERROR:", self.Styles.ERROR)} {message}', *args, **kwargs)
      File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 933, in trouble
        tb_data = traceback.format_list(traceback.extract_stack())
    
    ERROR: fragment 1 not found, unable to continue
      File "/usr/lib64/python3.10/runpy.py", line 196, in _run_module_as_main
        return _run_code(code, main_globals, None,
      File "/usr/lib64/python3.10/runpy.py", line 86, in _run_code
        exec(code, run_globals)
      File "/usr/local/bin/yt-dlp/__main__.py", line 17, in <module>
        yt_dlp.main()
      File "/usr/local/bin/yt-dlp/yt_dlp/__init__.py", line 968, in main
        _exit(*variadic(_real_main(argv)))
      File "/usr/local/bin/yt-dlp/yt_dlp/__init__.py", line 958, in _real_main
        return ydl.download(all_urls)
      File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3322, in download
        self.__download_wrapper(self.extract_info)(
      File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3297, in wrapper
        res = func(*args, **kwargs)
      File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1474, in extract_info
        return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
      File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1485, in wrapper
        return func(self, *args, **kwargs)
      File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1582, in __extract_info
        return self.process_ie_result(ie_result, download, extra_info)
      File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1641, in process_ie_result
        ie_result = self.process_video_result(ie_result, download=download)
      File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 2737, in process_video_result
        self.process_info(new_info)
      File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3182, in process_info
        partial_success, real_download = self.dl(fname, new_info)
      File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 2924, in dl
        return fd.download(name, new_info, subtitle)
      File "/usr/local/bin/yt-dlp/yt_dlp/downloader/common.py", line 446, in download
        ret = self.real_download(filename, info_dict)
      File "/usr/local/bin/yt-dlp/yt_dlp/downloader/dash.py", line 54, in real_download
        return self.download_and_append_fragments_multiple(*args, is_fatal=lambda idx: idx == 0)
      File "/usr/local/bin/yt-dlp/yt_dlp/downloader/fragment.py", line 381, in download_and_append_fragments_multiple
        return self.download_and_append_fragments(*args[0], **kwargs)
      File "/usr/local/bin/yt-dlp/yt_dlp/downloader/fragment.py", line 520, in download_and_append_fragments
        result = append_fragment(
      File "/usr/local/bin/yt-dlp/yt_dlp/downloader/fragment.py", line 484, in append_fragment
        self.report_error(f'fragment {frag_index} not found, unable to continue')
      File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1004, in report_error
        self.trouble(f'{self._format_err("ERROR:", self.Styles.ERROR)} {message}', *args, **kwargs)
      File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 933, in trouble
        tb_data = traceback.format_list(traceback.extract_stack())
    
    
    [debug] Invoking http downloader on "https://rr3---sn-q4fzen7e.googlevideo.com/videoplayback?expire=1669262182&ei=Bpd-Y5mmMIzdNqTogdgF&ip=<REDACTED_WAN_IP>&id=o-AMBN020_FYLwHHjN0G2lmtPkkSvMMdm7FCA9AbrpiL6H&itag=251&source=youtube&requiressl=yes&mh=cp&mm=31%2C26&mn=sn-q4fzen7e%2Csn-vgqsrnsd&ms=au%2Conr&mv=m&mvi=3&pl=24&initcwndbps=336250&spc=SFxXNmmf0dumLfqR1lGdCwkAJKezZg4&vprv=1&svpuc=1&mime=audio%2Fwebm&gir=yes&clen=2565275&otfp=1&dur=177.001&lmt=1641612603427403&mt=1669240416&fvip=3&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=5311224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cotfp%2Cdur%2Clmt&sig=AOq0QJ8wRQIhAL1G-IcRI1ZnsDWG2DlwACCtAEznt9VE-p1bH6-NZKOHAiAb-UvzKcqAr7h7GzwwNXvJ6VI0EsebPgRGjHbBJ_67XQ%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhALDjU-AnKymjAZ7Jj57HjBsRF5wMd2WOppndAplHF-xzAiB67X2716-vKbwvRBmYc6rKVrp0fIaOvhwJw3jnStpfjA%3D%3D"
    [download] Destination: Pull and Clean on a Blower Wheel (Blower Housing) (step 1-7) [iafA9X6_IhM].f251.webm
    [download] 100% of    2.45MiB in 00:00:01 at 2.16MiB/s
```

**Comment by coletdjnz** [comment]
It's a YouTube server issue with that format. Try `--check-formats`

Possibly related: https://github.com/yt-dlp/yt-dlp/issues/1986

**Comment by zpangwin** [comment]
Wow, that was a fast response! thank you!

I wasn't specifying a format, so I had assumed that it would just implicitly use `bestvideo*+bestaudio/best` and fallback if something wasn't working... so you might be on to something with 1986

Here is the output I get with the suggested option but if meant that I could perhaps use that to request a different (working) format, I'm not really sure 

    $ yt-dlp --check-formats https://www.youtube.com/watch?v=iafA9X6_IhM
    [youtube] iafA9X6_IhM: Downloading webpage
    [youtube] iafA9X6_IhM: Downloading android player API JSON
    [youtube] iafA9X6_IhM: Downloading MPD manifest
    [youtube] iafA9X6_IhM: Downloading MPD manifest
    [info] Testing format 244
    [download] Got error: The read operation timed out
    ERROR: fragment 1 not found, unable to continue
    [info] Unable to download format 244. Skipping...
    [info] Testing format 135
    [download] Got error: HTTP Error 503: Service Unavailable
    ERROR: fragment 1 not found, unable to continue
    [info] Unable to download format 135. Skipping...
    [info] Testing format 243
    [info] Testing format 251
    [info] iafA9X6_IhM: Downloading 1 format(s): 243+251
    [dashsegments] Total fragments: 34
    [download] Destination: Pull and Clean on a Blower Wheel (Blower Housing) (step 1-7) [iafA9X6_IhM].f243.webm
    [download] 100% of    6.24MiB in 00:00:34 at 187.19KiB/s
    [download] Destination: Pull and Clean on a Blower Wheel (Blower Housing) (step 1-7) [iafA9X6_IhM].f251.webm
    [download] 100% of    2.45MiB in 00:00:00 at 2.46MiB/s
    [Merger] Merging formats into "Pull and Clean on a Blower Wheel (Blower Housing) (step 1-7) [iafA9X6_IhM].webm"
    Deleting original file Pull and Clean on a Blower Wheel (Blower Housing) (step 1-7) [iafA9X6_IhM].f243.webm (pass -k to keep)
    Deleting original file Pull and Clean on a Blower Wheel (Blower Housing) (step 1-7) [iafA9X6_IhM].f251.webm (pass -k to keep)

And running with different format options, I got:

    $ yt-dlp -f "wv*+wa/w" https://www.youtube.com/watch?v=iafA9X6_IhM
    [youtube] iafA9X6_IhM: Downloading webpage
    [youtube] iafA9X6_IhM: Downloading android player API JSON
    [youtube] iafA9X6_IhM: Downloading MPD manifest
    [youtube] iafA9X6_IhM: Downloading MPD manifest
    [info] iafA9X6_IhM: Downloading 1 format(s): 17
    [download] Destination: Pull and Clean on a Blower Wheel (Blower Housing) (step 1-7) [iafA9X6_IhM].3gp
    [download] 100% of    1.62MiB in 00:01:29 at 18.43KiB/s
    
    $ l
    total 1.7M
    -rw-rw----. 1 me me 1.7M Jan  7  2022 'Pull and Clean on a Blower Wheel (Blower Housing) (step 1-7) [iafA9X6_IhM].3gp'

and adjusting my original command (no mentioned above) to 360p:

    yt-dlp  -f "bestvideo+bestaudio/best" \
        --format-sort res:360,+size,+br,codec  \
        -o "%(uploader)s_-_%(title)s.%(ext)s" \
        --restrict-filenames --windows-filenames --trim-filenames 140 \
        --quiet --no-warnings \
        --ignore-errors --prefer-free-formats \
        --xattrs --no-overwrites \
        --sub-lang en --embed-subs --add-metadata --merge-output-format mkv --write-auto-subs --embed-metadata --embed-thumbnail \
        "https://www.youtube.com/watch?v=iafA9X6_IhM"

That seems to work fine and give me more or less what I had been after. So **Thank You !!** :-D

**Comment by coletdjnz** [comment]
https://github.com/yt-dlp/yt-dlp/issues/1986 might not be too relevant here since the fallback server appears to be failing too. But this issue with DASH manifest formats failing is not uncommon (too many issues to link), and `--check-formats` is pretty much the solution.
