### ISSUE TITLE
Running two different versions

### ISSUE THREAD

**Issue by HalvorRaknes** [yt-dlp/yt-dlp#5642]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.11.11** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I must have messed up updating. Ialways forget which method I have used to install. How do I get out of

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
$ sudo pip3 install yt-dlp
[sudo] password for halvor:          
Collecting yt-dlp
  Downloading yt_dlp-2022.11.11-py2.py3-none-any.whl (2.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.8/2.8 MB 4.2 MB/s eta 0:00:00
Collecting mutagen
  Downloading mutagen-1.46.0-py3-none-any.whl (193 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 193.6/193.6 KB 3.7 MB/s eta 0:00:00
Requirement already satisfied: certifi in /usr/lib/python3/dist-packages (from yt-dlp) (2020.6.20)
Collecting pycryptodomex
  Downloading pycryptodomex-3.15.0-cp35-abi3-manylinux2010_x86_64.whl (2.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.3/2.3 MB 3.3 MB/s eta 0:00:00
Collecting websockets
  Downloading websockets-10.4-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (106 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 106.8/106.8 KB 3.2 MB/s eta 0:00:00
Collecting brotli
  Downloading Brotli-1.0.9-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (2.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.7/2.7 MB 1.5 MB/s eta 0:00:00
Installing collected packages: brotli, websockets, pycryptodomex, mutagen, yt-dlp
Successfully installed brotli-1.0.9 mutagen-1.46.0 pycryptodomex-3.15.0 websockets-10.4 yt-dlp-2022.11.11
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
$ yt-dlp -U
Latest version: 2022.11.11, Current version: 2022.10.04
ERROR: You installed yt-dlp with pip or using the wheel from PyPi; Use that to update
```

**Comment by Evernow** [comment]
https://github.com/yt-dlp/yt-dlp/wiki/Installation#with-pip

**Comment by bashonly** [comment]
Maybe last time you installed yt-dlp with pip under your user, and this time you are installing it with pip as `root` (w/ sudo)? Does that sound plausible?

You could try this:
 1. `sudo pip3 uninstall yt-dlp`
 2. `pip3 uninstall yt-dlp`
 3. `which yt-dlp`

At this point, `which yt-dlp` should output that yt-dlp was not found in your PATH -- if it still finds yt-dlp, you'll need to investigate how yet another version had been installed on your system.

Then you could do a fresh install with pip (w/o sudo): `python3 -m pip install -U yt-dlp`
(and use that same command to update every time)
