### ISSUE TITLE
Download stopped in number 7 from udemy

### ISSUE THREAD

**Issue by adibpwd** [yt-dlp/yt-dlp#5647]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.11.11** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

first i use yt-dlp, and then use youtbe-dl, but same result

![image](https://user-images.githubusercontent.com/54851209/204073475-5f269632-c471-4659-8120-d034e5068be9.png)
![image](https://user-images.githubusercontent.com/54851209/204073720-274ac614-5624-438f-a815-30aa076b5fa4.png)

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
i can't copy paste error with -vU because not stopped to last video, and then i click ctrl + c
```

**Comment by pukkandan** [comment]
Do not abuse the "Question" template to post incomplete issues/feature requests.

Properly fill out an appropriate issue form. Make sure to check for duplicates https://github.com/yt-dlp/yt-dlp/issues?q=udemy

---

> ```shell
> i can't copy paste error with -vU because not stopped to last video, and then i click ctrl + c
> ```

That makes no sense
