### ISSUE TITLE
DRM Content video No pictures+Audio no sound have

### ISSUE THREAD

**Issue by shahidhasanzai** [yt-dlp/yt-dlp#565]
![image](https://user-images.githubusercontent.com/75906314/126869825-67eed897-ddf1-49c6-b395-bec989e44c60.png)

![image](https://user-images.githubusercontent.com/75906314/126869836-ec5660f8-e0b1-4f96-a1ac-9192f9af3844.png)

**Comment by pukkandan** [comment]
Obviously, DRM files are unplayable. Hence why the option is named `--allow-unplayable-formats`. The option exists for testing and debugging. No support will be given downloading them
