### ISSUE TITLE
Download video from Douyin.com

### ISSUE THREAD

**Issue by wptop-net** [yt-dlp/yt-dlp#5650]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.11.11** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

China

### Example URLs

- Single video: https://v.douyin.com/rVWFVso/
- All video from user: https://www.douyin.com/user/MS4wLjABAAAAjSt59B9Fst6-c6b-sZMXkophgfeImxS_W9tr88nppGmqouWwjsefF_X6EeK1t495

### Provide a description that is worded well enough to be understood

Like download single video from Tiktok.com

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
D:\Tiktok\Download>yt-dlp -vU https://v.douyin.com/rVWFVso/
[debug] Command-line config: ['-vU', 'https://v.douyin.com/rVWFVso/']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.11.11 [8b64402] (pip)
[debug] Python 3.11.0 (CPython AMD64 64bit) - Windows-10-10.0.19044-SP0 (OpenSSL 1.1.1q  5 Jul 2022)
[debug] exe versions: ffmpeg 2022-11-21-git-459527108a-full_build-www.gyan.dev (setts), ffprobe 2022-11-21-git-459527108a-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.1
[debug] Proxy map: {}
[debug] Loaded 1723 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.11.11, Current version: 2022.11.11
yt-dlp is up to date (2022.11.11)
[debug] [generic] Extracting URL: https://v.douyin.com/rVWFVso/
[generic] rVWFVso: Downloading webpage
[redirect] Following redirect to https://www.douyin.com/video/7168743658076900608?previous_page=app_code_link
[debug] [Douyin] Extracting URL: https://www.douyin.com/video/7168743658076900608?previous_page=app_code_link
[Douyin] 7168743658076900608: Downloading video feed
WARNING: [Douyin] 7168743658076900608: Unable to find video in feed; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U; trying with webpage
[Douyin] 7168743658076900608: Downloading webpage
ERROR: [Douyin] 7168743658076900608: Fresh cookies (not necessarily logged in) are needed; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "C:\Users\thien\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\extractor\common.py", line 674, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\thien\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\extractor\tiktok.py", line 871, in _real_extract
    raise ExtractorError('Fresh cookies (not necessarily logged in) are needed')
```

**Comment by pukkandan** [comment]
> Fresh cookies (not necessarily logged in) are needed

Did you try this?

**Comment by pukkandan** [comment]
https://github.com/yt-dlp/yt-dlp/issues/2267
