### ISSUE TITLE
How to download only the first matched subtitle language?

### ISSUE THREAD

**Issue by DanielKonopka** [yt-dlp/yt-dlp#5654]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.11.11** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I wish to download either one of en or en-en subtitle languages, not both. How to approach this?
I have tried regexp en|en-en, but then no subtitle gets downloaded. It should be as easy as it is to select format, where I use:

yt-dlp -f "303+251/248+251/247+251/244+251/243+251/242+251/278+251"

to select best video+audio available (webm, VP9 + Opus). Whatever is matched first, it gets chosen and nothing else. Obviously, "/" works as an OR here. Why isn't it the same with subtitles?

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
Not currently possible #5651 4178
