### ISSUE TITLE
[feature suggestion] Whisper.cpp integration

### ISSUE THREAD

**Issue by eladkarako** [yt-dlp/yt-dlp#5656]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.11.11** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

propose optional integration of [Whisper.cpp](https://github.com/ggerganov/whisper.cpp) into yt-dlp,  
to be able to use its srt output directly for embedding subs.

offline, supports translating other languages to English, alternative to other machine-translated.  

tiniest dataset was able to accurately transcribe 20 seconds of English audio (5 sentences, 50 words), in just 6 seconds.  

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
Out of scope
