### ISSUE TITLE
Feature Request: Normalize field

### ISSUE THREAD

**Issue by tim78245** [yt-dlp/yt-dlp#5666]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.11.11** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Today people have a habit of using fancy characters in titles, such as:

𝔭𝔯𝔬𝔤𝔯𝔞𝔪𝔪𝔦𝔫𝔤
𝐩𝐫𝐨𝐠𝐫𝐚𝐦𝐦𝐢𝐧𝐠
ｐｒｏｇｒａｍｍｉｎｇ

I just want it save it as "programming", and it would be easier to make a --match-title filter too if yt-dlp could normalize it beforehand (perhaps --match-title-normalize)

However I do not want just a simple iconv to ascii. I don't for example want "prögrāmmîng" to become "programming". It would also be useful to normalize whitespace (trim leading and trailing, have no more than one space between words, etc).

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
See "unicode normalization" section of https://github.com/yt-dlp/yt-dlp#output-template. The same can be done in `--parse-metadata` if you want to use the modified value in `--match-filter`
