### ISSUE TITLE
[zee5] FullHD streams no longer available?

### ISSUE THREAD

**Issue by machasundaram** [yt-dlp/yt-dlp#5667]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.11.11** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Zee5 non-DRM contents no longer shows 1080p streams, only up to 720p. Is this no longer available or is it now premium subscriber only option, much like hotstar. Older contents are still available in 1080p.  Example:

[debug] Command-line config: ['-vU', '-F', 'https://www.zee5.com/tv-shows/details/mukkupudaka/0-6-4z5177299/mukkupudaka-november-28-2022/0-1-6z5261193']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.11.11 [8b64402] (pip)
[debug] Python 3.9.12 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1n  15 Mar 2022)
[debug] exe versions: ffmpeg 2022-01-06-git-2b541b8c1d-full_build-www.gyan.dev (setts), ffprobe 2022-01-06-git-2b541b8c1d-full_build-www.gyan.dev, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.14.0, brotli-1.0.9, certifi-2021.10.08, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1723 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.11.11, Current version: 2022.11.11
yt-dlp is up to date (2022.11.11)
[debug] Using fake IP 117.254.251.192 (IN) as X-Forwarded-For
[debug] [Zee5] Extracting URL: https://www.zee5.com/tv-shows/details/mukkupudaka/0-6-4z5177299/mukkupudaka-november-28-2022/0-1-6z5261193
[Zee5] 0-1-6z5261193: Downloading access token
[Zee5] 0-1-6z5261193: Downloading JSON metadata
[Zee5] 0-1-6z5261193: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[info] Available formats for 0-1-6z5261193:
ID                   EXT RESOLUTION FPS │   FILESIZE   TBR PROTO │ VCODEC        VBR ACODEC     MORE INFO
───────────────────────────────────────────────────────────────────────────────────────────────────────────
program_audio-Telugu mp4 audio only     │                  m3u8  │ audio only        unknown    [te] Telugu
128                  mp4 170x96      25 │ ~ 20.38MiB  128k m3u8  │ avc1.4d401f  128k video only
149                  mp4 256x144     25 │ ~ 23.77MiB  150k m3u8  │ avc1.4d401f  150k video only
236                  mp4 428x240     25 │ ~ 37.54MiB  237k m3u8  │ avc1.4d401f  237k video only
447                  mp4 640x360     25 │ ~ 70.94MiB  447k m3u8  │ avc1.4d401f  447k video only
600                  mp4 854x480     25 │ ~ 95.26MiB  600k m3u8  │ avc1.4d401f  600k video only
769                  mp4 1024x576    25 │ ~122.15MiB  770k m3u8  │ avc1.4d4029  770k video only
1246                 mp4 1280x720    25 │ ~197.75MiB 1246k m3u8  │ avc1.4d4029 1246k video only
1437                 mp4 1280x720    25 │ ~228.09MiB 1437k m3u8  │ avc1.4d4029 1437k video only

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
Why ask us? Check in browser if higher formats are available. Or, ask zee5...

In the link you gave, I don't see any 1080p in browser

**Comment by machasundaram** [comment]
Sorry if my post bothered you guys. I was hoping someone here having zee5 premium account can just check if they get higher resolution, because i certainly can't on these new contents. Anyway thanks for your time.

**Comment by bibsp** [comment]
@machasundaram Zee5 is okay. Not all shows/movies are availabe in 1080p. How can you get 1080p stream if source has 720p highest.
1080p stream [URL](https://www.zee5.com/tv-shows/details/dance-bangla-dance-season-11/0-6-2455/dance-bangla-dance-season-11/0-1-manual-3pk40fhj5k10)
