### ISSUE TITLE
[feature?] prevent cookies leak for 0 chance.

### ISSUE THREAD

**Issue by NewUserHa** [yt-dlp/yt-dlp#5669]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.11.11** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

https://github.com/yt-dlp/yt-dlp/blob/a9d069f5b8540f15caaf696bc39ce6a969f8b11c/yt_dlp/YoutubeDL.py#L3833-L3873
Currently, it extracted all cookies from browsers regardless of what site it is. Maybe there're chances that the cookiejar and its underlying code have a vulnerability that causes cookies to leak.

What about only merging "the required sites" to the `urllib.request.build_opener`?
And it seems easy to upgrade.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
Not possible. We cannot know what domains are needed ahead of time. If you are concerned about yt-dlp reading all cookies, use `--cookies` and not `--cookies-from-browser`

**Comment by bashonly** [comment]
yt-dlp also supports reading only from a specified Firefox container with `--cookies-from-browser firefox:profile::container`
If you're generally concerned about cookies leaking you should be using Firefox containers for browsing anyways.

**Comment by NewUserHa** [comment]
It's not about concerned. There has been some vulnerability news that leaked things like cookies right? The cookiejar and urllib related things are not in yt-dlp's control.

Users inputted the sites already that want to download, and most sites are just 1 or 2 domains (like youtube, youtu.be). 
Only things like oauth will redirect to 3rd party site, so it seems that yt-dlp will not encounter that situation.

Probably a new switch default to use explicit sites/domains only to improve the security?

**Comment by pukkandan** [comment]
> Users inputted the sites already that want to download, and most sites are just 1 or 2 domains (like youtube, youtu.be).

This is incorrect. 

---

Even if we add an option to filter domains, we still have to read the full cookiejar and then discard unwanted entries. This does not inprove security

**Comment by pukkandan** [comment]
Also, any program that can read the cookiejar from yt-dlp's memory could just read it directly from browser 🤷

**Comment by NewUserHa** [comment]
Of course, the local programs can read the info and memory things, and decrypt cookies from browsers too.

I mean, I didn't read the `http.cookiejar` code. But if put all cookies to that urllib.requests instance, there's a probablity that it sends unrelated cookies to a site (which may be a malware one, like the middle attack or etc.)

I wonder how urllib works on cookies if it verifies domains and the TLS well before sending request.

**Comment by NewUserHa** [comment]
Compared to server codes, which only send cookies to users, and it's 'set-cookie' headers that can't be wrong basically. Also, the database that contains all info is usually on that same machine.

But the client side can be more risky than server codes, they send info and they can get attacked and cheated more likely.

**Comment by Lesmiscore** [comment]
What if **browsers** should do if that's the case? Why don't you post the same thing to browsers' issue tracker like Chrome, Firefox, Opera... etc.

**Comment by NewUserHa** [comment]
The Browsers have [Vulnerability Rewards Program](https://www.chromium.org/Home/chromium-security/vulnerability-rewards-program/). Therefore they have much more time to find and fix Vulnerabilities like the 0 days. So that's the reason didn't post the same thing to browsers' issue tracker.

The other maybe has lower update frequency to fix or update to the newest specificity than the browsers, probably like http.cookiejar.py

**Comment by Grub4K** [comment]
MITM for sites using https are unlikely since certificate checks would fail and therefore the request would fail fast. Only required cookies are sent, which is handled by the cookie handler. Please explain which part of the yt-dlp handling exactly you have a problem with.

If you are concerned by SSL security you need to disclose vulnerabilities in the Python implementation or the underlying SSL implementation directly. yt-dlp has nothing to do with that part.

**Comment by NewUserHa** [comment]
No. There's no issue about yt-dlp. But it's just about the dependency.

This issue is trying to discuss if there is any improvement can do about that question. If stands at a user's point, that puts all cookies of all sites into one jar and then uses it to request that websites (input by users themselves) seem to be a very heavy job on that request.
It would be great if only put the necessary cookies into that cookiejar.

**Comment by coletdjnz** [comment]
This issue does not really make any sense and does not appear to show a concrete problem. 

Please read and understand how cookies work and how cookies are applied to requests in urllib/http libs before making speculations with no basis.

A [cookiejar](https://docs.python.org/3/library/http.cookiejar.html) is _designed_  to be the central storage of cookies for multiple domains and only apply those that are relevant to a request based on the properties.

Malware and MITM attacks is not yt-dlp's problem. Certificate checking is enabled by default, and if the user disables that it's at their risk. 

---

If anyone does find a vulnerability, please do report to the relevant parties privately (be that Python, us or other dependencies)

**Comment by coletdjnz** [comment]
> It would be great if only put the necessary cookies into that cookiejar.

Then export the cookies manually and use `--cookies` if you know ahead of time what ones are required.
