### ISSUE TITLE
unable to download (DRM-free) videos from VrtNU (Vrt Max)

### ISSUE THREAD

**Issue by skaldener** [yt-dlp/yt-dlp#5671]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.11.11** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

I tried to download some (DRM-free) videos from VrtNU, but without success.
Error: unable to extract media element... 
ps: canvas is one of the TV-channels of VRT, where I tried to download from.
In the past, downloading was possible.
I can still download these DRM-free videos with the program "GemistDownloader", but I don't think they use yt-dlp. 

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '-f', '-mp4', '-o', 'D:\\videos\\winteruur.mp4', 'https://www.vrt.be/vrtnu/a-z/winteruur/8/winteruur-s8a11']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.11.11 [8b64402] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1723 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.11.11, Current version: 2022.11.11
yt-dlp is up to date (2022.11.11)
[debug] [VrtNU] Extracting URL: https://www.vrt.be/vrtnu/a-z/winteruur/8/winteruur-s8a11
[VrtNU] winteruur-s8a11: Downloading webpage
ERROR: [VrtNU] winteruur-s8a11: Unable to extract media element; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 674, in extract
  File "yt_dlp\extractor\canvas.py", line 317, in _real_extract
  File "yt_dlp\extractor\common.py", line 1228, in _search_regex
```

**Comment by bashonly** [comment]
geo-restricted to Belgium / Belgian citizens

**Comment by dirkf** [comment]
Yes, but the page found by yt-dlp and yt-dl (without login) is a loading page for the JS app that will display the media (with a `noscript` element that tells you to install JS in Flemish). It doesn't show any evidence of geo-blocking or login required at that stage.

Unless the page is different in BE, or after login, the tactic of loading the page and trying to find the `nui-media` element is obsolete and would need to be replaced by another API call.

Gemist(Missed)Downloader [partially knows about DRM](https://www-helpdeskweb-nl.translate.goog/forum/showthread.php?tid=3085&pid=12361&_x_tr_sl=nl&_x_tr_tl=en&_x_tr_hl=en#pid12361), but OP says that's not the issue.

**Comment by skaldener** [comment]
I agree with bashonly about geo-restriction to Belgium, but as I live in Belgium that's not a problem for me.
In the past I could download videos with yt-dlp. 
I suppose Vrtnu (Vrt max) has made some changes, so that downloading doesn't work anymore with yt-dlp?

**Comment by skaldener** [comment]
I see that the problem mentioned here, is nearly the same as the problem mentioned in #4908.
The fix suggested there by @bergoid (#4909) isn't implemented yet, or isn't working in this case?

**Comment by dirkf** [comment]
In the UK without login a yt-dl back-port reaches the stage of `Downloading video JSON` which is several steps in, with this target that gives `CONTENT_AVAILABLE_ONLY_FOR_BE_RESIDENTS_AND_EXPATS`:
`https://media-services-public.vrt.be/media-aggregator/v2/media-items/pbs-pub-a7739cef-20ff-4c4b-aa3c-36e949a76552$vid-50cee256-c83d-45b3-b69a-1199d842878e`

Seemingly it would be worth trying the PR branch in BE.

**Comment by bn326160** [comment]
> ❯ yt-dlp https://www.vrt.be/vrtnu/a-z/alles-kan-beter/1/alles-kan-beter-s1a1/
> [VrtNU] alles-kan-beter-s1a1: Downloading webpage
> ERROR: [VrtNU] alles-kan-beter-s1a1: Unable to extract media element; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
> ❯ yt-dlp -U
> Latest version: 2022.11.11, Current version: 2022.11.11
> yt-dlp is up to date (2022.11.11)

Can't even parse the page here

**Comment by dirkf** [comment]
No, that's just the original problem. Try PR #4909 instead.

**Comment by bashonly** [comment]
Fixed by 1a7dcca378e80a387923ee05c250d8ba122441c6

**Comment by kboghe** [comment]
Hi all, 

I'm getting internal server errors (HTTP error 500) as of late whenever I'm trying to use the VRTMAX extractors. The code worked fine 2 weeks ago; but it broke somewhere last week. Does anyone else experience the same issue? 

Thanks!

**Comment by bashonly** [comment]
@kboghe could you open a new issue, please? 

Also, if you are able to, you could test #7519 to see if that fixes the issue

**Comment by kboghe** [comment]
#7519 seems to work like a charm; many thanks!
