### ISSUE TITLE
[Broken] Raiplay

### ISSUE THREAD

**Issue by buscon** [yt-dlp/yt-dlp#5672]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.11.11** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Italy

### Provide a description that is worded well enough to be understood

When I try to download a video from raiplay, I get the following error.
Here is the command I use:
`yt-dlp.exe -vU https://www.raiplay.it/video/2022/11/Esterno-notte-E1-Aldo-Moro-98c416ed-dea5-434d-8402-6c84187a37d2.html`

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--cookies-from-browser', 'FIREFOX', 'https://www.raiplay.it/video/2022/11/Esterno-notte-E1-Aldo-Moro-98c416ed-dea5-434d-8402-6c84187a37d2.html']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.11.11 [8b64402] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22621-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[Cookies] Extracting cookies from firefox
[debug] Extracting cookies from: "C:\Users\walla\AppData\Roaming\Mozilla\Firefox\Profiles\bl8ce3xe.default-release\cookies.sqlite"
[Cookies] Extracted 275 cookies from firefox
[debug] Proxy map: {}
[debug] Loaded 1723 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.11.11, Current version: 2022.11.11
yt-dlp is up to date (2022.11.11)
[debug] [RaiPlay] Extracting URL: https://www.raiplay.it/video/2022/11/Esterno-notte-E1-Aldo-Moro-98c416ed-dea5-434d-8402-6c84187a37d2.html
[RaiPlay] 98c416ed-dea5-434d-8402-6c84187a37d2: Downloading video JSON
[RaiPlay] 98c416ed-dea5-434d-8402-6c84187a37d2: Downloading XML metadata for platform mon
[RaiPlay] 98c416ed-dea5-434d-8402-6c84187a37d2: Downloading XML metadata for platform flash
[RaiPlay] 98c416ed-dea5-434d-8402-6c84187a37d2: Downloading XML metadata for platform native
ERROR: [RaiPlay] 98c416ed-dea5-434d-8402-6c84187a37d2: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1485, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1582, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1641, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2573, in process_video_result
  File "yt_dlp\YoutubeDL.py", line 1035, in raise_no_formats
yt_dlp.utils.ExtractorError: [RaiPlay] 98c416ed-dea5-434d-8402-6c84187a37d2: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

**Comment by Heros99** [comment]
works

**Comment by Heros99** [comment]
[RaiPlay] 98c416ed-dea5-434d-8402-6c84187a37d2: Downloading video JSON
[RaiPlay] 98c416ed-dea5-434d-8402-6c84187a37d2: Downloading XML metadata for platform mon
[RaiPlay] 98c416ed-dea5-434d-8402-6c84187a37d2: Downloading m3u8 information
[RaiPlay] 98c416ed-dea5-434d-8402-6c84187a37d2: Downloading XML metadata for platform flash
[RaiPlay] 98c416ed-dea5-434d-8402-6c84187a37d2: Downloading XML metadata for platform native
[info] 98c416ed-dea5-434d-8402-6c84187a37d2: Downloading 1 format(s): https-5000
[download] Resuming download at byte 171965440
[download] Destination: Esterno notte - E1 - Aldo Moro [98c416ed-dea5-434d-8402-6c84187a37d2].mp4
[download]  10.8% of    2.28GiB at   30.08MiB/s ETA 01:09

**Comment by bashonly** [comment]
@Heros99 can you show a full log of it working? are you passing cookies?

**Comment by Heros99** [comment]
> can you show a full verbose log of it working? are you passing cookies?

try cookies

**Comment by pukkandan** [comment]
> * [x]  I've checked that all provided URLs are playable in a browser with the same IP and same login details

You sure? For me, the URL asks for login in browser. Try passing logged in cookies

**Comment by buscon** [comment]
> > * [x]   I've checked that all provided URLs are playable in a browser with the same IP and same login details
> 
> You sure? For me, the URL asks for login in browser. Try passing logged in cookies

I tried both:
yt-dlp --cookies-from-browser FIREFOX  https://www.raiplay.it/programmi/esternonotte
and
yt-dlp --cookies cookies.txt  https://www.raiplay.it/programmi/esternonotte
but I still get the same error.

@Heros99  what are your command line options?

**Comment by pukkandan** [comment]
> I tried both:
> yt-dlp --cookies-from-browser FIREFOX [raiplay.it/programmi/esternonotte](https://www.raiplay.it/programmi/esternonotte)
> and
> yt-dlp --cookies cookies.txt [raiplay.it/programmi/esternonotte](https://www.raiplay.it/programmi/esternonotte)
> but I still get the same error.

That is not what the log shows

**Comment by buscon** [comment]
> > I tried both:
> > yt-dlp --cookies-from-browser FIREFOX [raiplay.it/programmi/esternonotte](https://www.raiplay.it/programmi/esternonotte)
> > and
> > yt-dlp --cookies cookies.txt [raiplay.it/programmi/esternonotte](https://www.raiplay.it/programmi/esternonotte)
> > but I still get the same error.
> 
> That is not what the log shows

I can update the log above, still the error is the same.

**Comment by njam** [comment]
I can reproduce the error from the original ticket description when using an _IP outside of Italy_:
>  No video formats found!

With an IP address associated with Italy it works fine.

**Comment by bashonly** [comment]
Maybe if the extractor can detect the geo-block it should `raise_geo_restricted` instead?

**Comment by nixxo** [comment]
Did an overhaul of the extractor: https://github.com/yt-dlp/yt-dlp/pull/5940

**Comment by bashonly** [comment]
@nixxo Testing the PR with the OP's URL gives me a warning and then the "not available" video downloads
```
WARNING: [RaiPlay] Video not available. Likely due to geo-restriction.
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[info] Available formats for 98c416ed-dea5-434d-8402-6c84187a37d2:
ID    EXT RESOLUTION │ PROTO │ VCODEC  ACODEC
──────────────────────────────────────────────
https mp4 unknown    │ https │ unknown unknown
```
Is there a reason why it doesn't just `raise_geo_restricted` in this case?

**Comment by nixxo** [comment]
Not really. I just kept the original "logic" not to raise an error and warn the user and provide the resulting media anyway. (A video telling you the constant is not available)

I just made the message more detailed.

**Comment by pukkandan** [comment]
> Testing the PR with the OP's URL gives me a warning and then the "not available" video downloads

Does the video play in browser for you?

**Comment by bashonly** [comment]
> Does the video play in browser for you?

No, but it's because the site makes me login / register

**Comment by nixxo** [comment]
The login is "stupid". Just replace html with json at the end of the URL to get access to the contents anyway.

**Comment by Heros99** [comment]
some videos put DRM
ERROR: [RaiPlay] ****************************: This video is DRM protected

**Comment by bashonly** [comment]
> The login is "stupid". Just replace html with json at the end of the URL to get access to the contents anyway.

The link in the `content_url` field of the JSON redirects me to the geo-block/"not available" video

**Comment by Heros99** [comment]
> > The login is "stupid". Just replace html with json at the end of the URL to get access to the contents anyway.
> 
> The link in the `content_url` field of the JSON redirects me to the geo-block/"not available" video

Have you tried using VPN?

**Comment by pukkandan** [comment]
> * [x]  I've checked that all provided URLs are playable in a browser with the same IP and same login details

@buscon You claim it is playable? Pls double check and confirm

**Comment by peterlongx** [comment]
python3.7 -m yt_dlp --referer "https://www.raiplay.it/" --add-header "Cookie:COOKIE" --batch-file links_da_scaricare.txt -vU

Somes videos are downloaded, for example this

https://www.raiplay.it/video/2023/07/Camper-in-viaggio-4769561a-f364-44d1-a4f7-343e400616ec.html

but if you using same cookie, this url 
https://www.raiplay.it/video/2021/06/Submergence-82487727-fef4-408f-8b6e-a8d27fc1dc86.html

is not downloaded because error is "geo-blocked" - this is strange

Cookie is taken from **tracks-media-sequence** from _Network Tab_

**Comment by 0wwafa** [comment]
@njam @buscon  about raiplay, the proxy is needed ONLY for the "relinket" api call. Afterward the video can be downloaded without any proxy.
