### ISSUE TITLE
[RCS] corriere.it AttributeError: 'bytes' object has no attribute 'encode'

### ISSUE THREAD

**Issue by someziggyman** [yt-dlp/yt-dlp#5683]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.11.11** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

anywhere

### Provide a description that is worded well enough to be understood

https://video.corriere.it/cronaca/audio-telefonata-il-papa-becciu-santita-lettera-che-mi-ha-inviato-condanna/b94c0d20-70c2-11ed-9572-e4b947a0ebd2?vclk=video3CHP%7Caudio-telefonata-il-papa-becciu-santita-lettera-che-mi-ha-inviato-condanna

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
./yt-dlp -vU -F "https://video.corriere.it/cronaca/audio-telefonata-il-papa-becciu-santita-lettera-che-mi-ha-inviato-condanna/b94c0d20-70c2-11ed-9572-e4b947a0ebd2?vclk=video3CHP%7Caudio-telefonata-il-papa-becciu-santita-lettera-che-mi-ha-inviato-condanna"
[debug] Command-line config: ['-vU', '-F', 'https://video.corriere.it/cronaca/audio-telefonata-il-papa-becciu-santita-lettera-che-mi-ha-inviato-condanna/b94c0d20-70c2-11ed-9572-e4b947a0ebd2?vclk=video3CHP%7Caudio-telefonata-il-papa-becciu-santita-lettera-che-mi-ha-inviato-condanna']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.11.11 [8b644025b] (zip)
[debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
[debug] Python 3.10.8 (CPython arm64 64bit) - macOS-12.6.1-arm64-arm-64bit (OpenSSL 1.1.1s  1 Nov 2022)
[debug] exe versions: phantomjs 2.1.1
[debug] Optional libraries: sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Loaded 1731 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.11.11, Current version: 2022.11.11
yt-dlp is up to date (2022.11.11)
[debug] [RCS] Extracting URL: https://video.corriere.it/cronaca/audio-telefonata-il-papa-becciu-santita-lettera-che-mi-ha-inviato-condanna/b94c0d20-70c2-11ed-9572-e4b947a0ebd2?vclk=video3CHP%7Caudio-telefonata-il-papa-becciu-santita-lettera-che-mi-ha-inviato-condanna
[RCS] b94c0d20-70c2-11ed-9572-e4b947a0ebd2: Downloading webpage
[RCS] b94c0d20-70c2-11ed-9572-e4b947a0ebd2: Downloading webpage
[RCS] b94c0d20-70c2-11ed-9572-e4b947a0ebd2: Downloading m3u8 information
ERROR: 'bytes' object has no attribute 'encode'
Traceback (most recent call last):
  File "./yt-dlp/yt_dlp/YoutubeDL.py", line 1495, in wrapper
    return func(self, *args, **kwargs)
  File "./yt-dlp/yt_dlp/YoutubeDL.py", line 1571, in __extract_info
    ie_result = ie.extract(url)
  File "./yt-dlp/yt_dlp/extractor/common.py", line 678, in extract
    ie_result = self._real_extract(url)
  File "./yt-dlp/yt_dlp/extractor/rcs.py", line 256, in _real_extract
    formats = self._create_formats(
  File "./yt-dlp/yt_dlp/extractor/rcs.py", line 190, in _create_formats
    formats = self._extract_m3u8_formats(
  File "./yt-dlp/yt_dlp/extractor/common.py", line 1898, in _extract_m3u8_formats
    fmts, subs = self._extract_m3u8_formats_and_subtitles(*args, **kwargs)
  File "./yt-dlp/yt_dlp/extractor/common.py", line 1909, in _extract_m3u8_formats_and_subtitles
    res = self._download_webpage_handle(
  File "./yt-dlp/yt_dlp/extractor/common.py", line 866, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query, expected_status=expected_status)
  File "./yt-dlp/yt_dlp/extractor/common.py", line 805, in _request_webpage
    return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query))
  File "./yt-dlp/yt_dlp/extractor/common.py", line 771, in _create_request
    return sanitized_Request(url_or_request, data, headers or {})
  File "./yt-dlp/yt_dlp/utils.py", line 773, in sanitized_Request
    url, auth_header = extract_basic_auth(escape_url(sanitize_url(url)))
  File "./yt-dlp/yt_dlp/utils.py", line 3115, in escape_url
    netloc=url_parsed.netloc.encode('idna').decode('ascii'),
AttributeError: 'bytes' object has no attribute 'encode'
```

**Comment by bashonly** [comment]
It's a bug in the extractor that is encountered when there is no m3u8 URL extracted:
https://github.com/yt-dlp/yt-dlp/blob/ddf1e22d48530819d60220d0bdc36e20f5b8483b/yt_dlp/extractor/rcs.py#L188-L199
m3u8 extraction is always attempted even if there is no m3u8 URL, so `None` is passed as the url arg to `self._extract_m3u8_formats`. And the extractor also doesn't do anything with the mp3 URL, which is the only media URL found from the example link from the issue report.

This should fix it:
```diff
diff --git a/yt_dlp/extractor/rcs.py b/yt_dlp/extractor/rcs.py
index b905f8d2e..e0155533b 100644
--- a/yt_dlp/extractor/rcs.py
+++ b/yt_dlp/extractor/rcs.py
@@ -187,15 +187,24 @@ def _get_video_src(self, video):
 
     def _create_formats(self, urls, video_id):
         formats = []
-        formats = self._extract_m3u8_formats(
-            urls.get('m3u8'), video_id, 'mp4', entry_protocol='m3u8_native',
-            m3u8_id='hls', fatal=False)
+
+        if urls.get('m3u8'):
+            formats = self._extract_m3u8_formats(
+                urls['m3u8'], video_id, 'mp4', m3u8_id='hls', fatal=False)
 
         if urls.get('mp4'):
             formats.append({
                 'format_id': 'http-mp4',
                 'url': urls['mp4']
             })
+
+        if urls.get('mp3'):
+            formats.append({
+                'format_id': 'http-mp3',
+                'vcodec': 'none',
+                'url': urls['mp3']
+            })
+
         return formats
 
     def _real_extract(self, url):
```

**Comment by bashonly** [comment]
> Maybe we should allow None to be passed to _extract_m3u8_formats?

I like it, then `fatal=False` would make it truly non-fatal

**Comment by dirkf** [comment]
> Maybe we should allow None to be passed to _extract_m3u8_formats?

And suppress the warning if `errNote is False` ?
