### ISSUE TITLE
TikTok Parsing Feed Breaking Update Dec 1, 2022 (non-watermark version missing)

### ISSUE THREAD

**Issue by hanimourra** [yt-dlp/yt-dlp#5688]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.11.11** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Canada

### Provide a description that is worded well enough to be understood

Requesting the list of formats returns JSON feed error, which resorts to downloading webpage which now only shows one video (with watermark) ... which his not helpful.

yt-dlp -F https://www.tiktok.com/@repurposeio/video/7158191036513127685

[TikTok] 7158191036513127685: Downloading video feed
WARNING: [TikTok] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 1 of 4)
[TikTok] 7158191036513127685: Downloading video feed
WARNING: [TikTok] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 2 of 4)
[TikTok] 7158191036513127685: Downloading video feed
WARNING: [TikTok] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 3 of 4)
[TikTok] 7158191036513127685: Downloading video feed
WARNING: [TikTok] 7158191036513127685: Failed to parse JSON (caused by JSONDecodeError("Expecting value in '': line 1 column 1 (char 0)")); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U; trying with webpage
[TikTok] 7158191036513127685: Downloading webpage
[info] Available formats for 7158191036513127685:
ID EXT RESOLUTION │ PROTO │ VCODEC  ACODEC
───────────────────────────────────────────
0  mp4 576x1024   │ https │ unknown unknown

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
root@new-proc-ubuntu-2gb-nyc1-01-processing-01-1495731460959-8gb-nyc1:~/hani# /root/smpnode/yt-dlp-master/yt_dlp/__main__.py --proxy https://196.51.251.236:8800 --add-header 'user-agent:Mozilla/5.0' "https://www.tiktok.com/@repurposeio/video/7158191036513127685" -vU
[debug] Command-line config: ['--proxy', 'https://196.51.251.236:8800', '--add-header', 'user-agent:Mozilla/5.0', 'https://www.tiktok.com/@repurposeio/video/7158191036513127685', '-vU']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.11.11 [8b644025b]
[debug] Lazy loading extractors is disabled
[debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
[debug] Python 3.8.9 (CPython x86_64 64bit) - Linux-4.15.0-173-generic-x86_64-with-glibc2.17 (OpenSSL 1.0.2n  7 Dec 2017, glibc 2.27)
[debug] exe versions: ffmpeg 5.0.1-static (setts), ffprobe 5.0.1-static, rtmpdump 2.4
[debug] Optional libraries: certifi-2018.01.18, sqlite3-2.6.0
[debug] Proxy map: {'http': 'https://196.51.251.236:8800', 'https': 'https://196.51.251.236:8800'}
[debug] Loaded 1731 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.11.11, Current version: 2022.11.11
yt-dlp is up to date (2022.11.11)
[debug] [TikTok] Extracting URL: https://www.tiktok.com/@repurposeio/video/7158191036513127685
[TikTok] 7158191036513127685: Downloading video feed
WARNING: [TikTok] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 1 of 4)
[TikTok] 7158191036513127685: Downloading video feed
WARNING: [TikTok] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 2 of 4)
[TikTok] 7158191036513127685: Downloading video feed
WARNING: [TikTok] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 3 of 4)
[TikTok] 7158191036513127685: Downloading video feed
WARNING: [TikTok] 7158191036513127685: Failed to parse JSON (caused by JSONDecodeError("Expecting value in '': line 1 column 1 (char 0)")); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U; trying with webpage
[TikTok] 7158191036513127685: Downloading webpage
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 7158191036513127685: Downloading 1 format(s): 0
```

**Comment by Kusurisan** [comment]
encountered the same issue today.

Windows 10, Germany, same error message as op.

**Comment by bashonly** [comment]
It looks like TikTok has locked down their mobile API `feed` endpoint, which was our last working/known source of non-watermarked video URLs.

I get the same results with master, latest release, and every version going back to when we started using the mobile API.

I'm thinking that TikTok is now requiring/enforcing some sort of signature query param(s) and/or header(s) (e.g. `X-Gorgon`, `X-Argus` etc) for this endpoint. Which is probably also what happened with the `aweme/detail` endpoint.

If anyone has any knowledge to share that would be much appreciated!

Otherwise,
**please do not reply with "+1" or "me too" or a log demonstrating the exact same issue.**
This is not helpful for an issue that is already known to impact all users, and that's what the reaction emojis are for.

**Comment by koanapple** [comment]
This error repeats in Russian region too.

**Comment by hanimourra** [comment]
One option is to use https://developers.tiklydown.me/#/Download/download to download the video without watermark.  Maybe that can be incorporated or source code found to see how they do it?

**Comment by Neurotoxin001** [comment]
I have same problem. This is not advertising, but there are bots on Telegram that can still download videos without watermarks. How they do it is unknown, but it means that there is a way after all. All that remains is to find it. Here is one such bot: `https://t.me/TTFullBot`

**Comment by kyleissuper** [comment]
> One option is to use https://developers.tiklydown.me/#/Download/download to download the video without watermark. Maybe that can be incorporated or source code found to see how they do it?

Hah looks like we broke tiklydown
<img width="979" alt="image" src="https://user-images.githubusercontent.com/12404677/205213445-7000dd4b-a7e2-4def-9ed5-2113c8885bac.png">

**Comment by Nadock** [comment]
I think this is more than just the "non-watermark" copies, I'm getting the same errors trying to download a watermarked copy.

```shell
yt-dlp -P "./tmp" -o "%(id)s.%(ext)s" -f "best[format_note*=watermarked]" --restrict-filenames --verbose --dump-json --no-simulate --quiet "https://vt.tiktok.com/ZS8RQGLsN/" --list-formats -vU

[debug] Command-line config: ['-P', './tmp', '-o', '%(id)s.%(ext)s', '-f', 'best[format_note*=watermarked]', '--restrict-filenames', '--verbose', '--dump-json', '--no-simulate', '--quiet', 'https://vt.tiktok.com/ZS8RQGLsN/', '--list-formats', '-vU']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.10.04 [4e0511f] (pip) API
[debug] Python 3.9.15 (CPython 64bit) - macOS-13.0-arm64-arm-64bit
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 5.1.2 (setts), ffprobe 5.1.2, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1690 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.11.11, Current version: 2022.10.04
[debug] Downloading _update_spec from https://github.com/yt-dlp/yt-dlp/releases/download/2022.11.11/_update_spec
ERROR: You installed yt-dlp with pip or using the wheel from PyPi; Use that to update
[debug] [vm.tiktok] Extracting URL: https://vt.tiktok.com/ZS8RQGLsN/
[vm.tiktok] ZS8RQGLsN: Downloading webpage
[debug] [TikTok] Extracting URL: https://www.tiktok.com/@chinpals/video/7171489527658286379?_t=8XpmeEfrwWn&_r=1
[TikTok] 7171489527658286379: Downloading video feed
WARNING: [TikTok] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 1 of 4)
[TikTok] 7171489527658286379: Downloading video feed
WARNING: [TikTok] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 2 of 4)
[TikTok] 7171489527658286379: Downloading video feed
WARNING: [TikTok] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 3 of 4)
[TikTok] 7171489527658286379: Downloading video feed
WARNING: [TikTok] 7171489527658286379: Failed to parse JSON (caused by JSONDecodeError("Expecting value in '': line 1 column 1 (char 0)")); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U; trying with webpage
[TikTok] 7171489527658286379: Downloading webpage
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[info] Available formats for 7171489527658286379:
ID EXT RESOLUTION │ PROTO │ VCODEC  ACODEC
───────────────────────────────────────────
0  mp4 576x1024   │ https │ unknown unknown
ERROR: [TikTok] 7171489527658286379: Requested format is not available. Use --list-formats for a list of available formats
Traceback (most recent call last):
  File "/Users/riley.chase/.local/share/virtualenvs/dj_howard-mpRho0vp/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1477, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/riley.chase/.local/share/virtualenvs/dj_howard-mpRho0vp/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1574, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/Users/riley.chase/.local/share/virtualenvs/dj_howard-mpRho0vp/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1632, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/Users/riley.chase/.local/share/virtualenvs/dj_howard-mpRho0vp/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 2698, in process_video_result
    raise ExtractorError(
yt_dlp.utils.ExtractorError: [TikTok] 7171489527658286379: Requested format is not available. Use --list-formats for a list of available formats
```

**Comment by WalkerKnapp** [comment]
> I'm thinking that TikTok is now requiring/enforcing some sort of signature query param(s) and/or header(s) (e.g. `X-Gorgon`, `X-Argus` etc) for this endpoint. Which is probably also what happened with the `aweme/detail` endpoint.

Is this the issue circumvented in @redraskal's pr #4996 ? (relevant code: https://github.com/redraskal/yt-dlp/blob/3628e2bb9b7d6c9ad09cc3e2f531a933108ef182/yt_dlp/extractor/tiktok.py#L565) It uses playwright to make an API call that was broken by TT earlier. This PR will be broken right now too, but could a similar solution work for downloading videos if something similar is done with the `aweme/detail` endpoint?

> I think this is more than just the "non-watermark" copies, I'm getting the same errors trying to download a watermarked copy.

I'm sure that the devs who have worked on this already know, but just in case, watermarked copies are super easy to grab from the preload information that tiktok gives in the response to the video page itself. I.e.

```
curl 'https://www.tiktok.com/@tiktok/video/7172353889528761642' -H 'User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:106.0) Gecko/20100101 Firefox/106.0' --output testdl.html
```
has a huge object in one of the script tags, which has a `largeObjectThing["ItemModule"]["7172353889528761642"]["video"]["downloadAddr"]` giving a url to a watermarked video.

**Comment by redraskal** [comment]
The purpose of my PR is to fix fetching video ids associated with a user, not to download them. That branch is also broken

**Comment by Jo754709** [comment]
Hello, the issue still exists. How to download TikTok videos without watermark in the new update?

**Comment by bashonly** [comment]
> Hello, the issue still exists. How to download TikTok videos without watermark in the new update?

It has been fixed in master, but there has not been a new release yet. You can [install the master branch with PIP](https://github.com/yt-dlp/yt-dlp/wiki/Installation#with-pip) or try the current release of the [unofficial daily builds](https://github.com/ytdl-patched/yt-dlp)

**Comment by Jo754709** [comment]
> > Hello, the issue still exists. How to download TikTok videos without watermark in the new update?
> 
> It has been fixed in master, but there has not been a new release yet. You can [install the master branch with PIP](https://github.com/yt-dlp/yt-dlp/wiki/Installation#with-pip) or try the current release of the [unofficial daily builds](https://github.com/ytdl-patched/yt-dlp)

Thank you very much
