### ISSUE TITLE
Selective --dump-json (don't want to download loads of format data)

### ISSUE THREAD

**Issue by hedgehog90** [yt-dlp/yt-dlp#5701]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.11.11** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I'm using yt-dlp to probe the status of numerous live streams.
For this I'm simply calling `yt-dlp --dump-json <url>`
However for some live streamed videos on YouTube I receive masses of unnecessary format information, including a list of 5 second fragments that amounts to over 5 MB of JSON text.
But really all I'm after are a few values: is_live, live_status and the thumbnails.
I understand I could use the YouTube API to more efficently get this data, however the great thing about yt-dlp is it works for multiple video sites.
Is there any way to tell yt-dlp not to download a list of every format, particularly for live streams that include considerably more data?

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
you can use `--print` / `-O` to output only the specified values
e.g.
```shellsession
$ yt-dlp -O is_live -O live_status "URL"
False
not_live
```
you can also use it to output your own custom JSON:
```
yt-dlp -O "%(.{is_live,live_status,thumbnails})#j" "URL"
```
(remove the `#` flag if you don't want it pretty-printed)

**Comment by hedgehog90** [comment]
Sorry, I forgot to specify this point - I don't mind being served a load of information, but I don't want it to download unnecessary amounts of data. I haven't checked but I suspect those commands will still download the same amount of the data as my command?

**Comment by pukkandan** [comment]
There is no way to make yt-dlp fetch only specific metadata. In case of youtube, fetching metadata and formats generally takes the same number of API calls, except in case of hls/dash formats. These can be disabled using appropriate [Extractor arguments](https://github.com/yt-dlp/yt-dlp#extractor-arguments)

**Comment by hedgehog90** [comment]
Thanks, that was exactly what I was looking for.
