### ISSUE TITLE
Additional cookies parameter

### ISSUE THREAD

**Issue by watchingfun** [yt-dlp/yt-dlp#5703]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.11.11** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

I checked the documentation and found that there are only two ways to get cookies:
 "--cookies FILE", "--cookies-from-browser BROWSER"

Actually I need this parameter type: --cookies "k1=v1; k2=v2; k3=v3".
This is handy for some tools that wrap command line calls

cookies-from-browser This method is dangerous, and ordinary users often do not trust this method.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
`--add-header "Cookie:k1=v1; k2=v2; k3=v3"`

**Comment by watchingfun** [comment]
> `--add-header "Cookie:k1=v1; k2=v2; k3=v3"`

thanks
