### ISSUE TITLE
Can't embed thumbnail or metadata if use '+' symbol, like 398+251 or "bv*[height<=1440][ext=mp4]+ba", help me please

### ISSUE THREAD

**Issue by adibpwd** [yt-dlp/yt-dlp#5704]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.11.11** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I downloaded it in mkv format, and I just realized when everything has been downloaded, can I add thumbnails and metadata to the files that have been downloaded?

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by adibpwd** [comment]
I used playlist-start-end, and tried to add thumbnails but it didn't work

![image](https://user-images.githubusercontent.com/54851209/205487604-8bf887d6-f52f-4fa4-b91c-ddded64bac6a.png)

**Comment by pukkandan** [comment]
> can I add thumbnails and metadata to the files that have been downloaded?

Re-run the commands adding appropriate options. As long as you don't pass `--force-overwrite`, yt-dlp will detect the existing files and perform only the postprocessing without re-downloading

**Comment by adibpwd** [comment]
> > dapatkah saya menambahkan thumbnail dan metadata ke file yang telah diunduh?
> 
> Jalankan kembali perintah dengan menambahkan opsi yang sesuai. Selama Anda tidak lulus `--force-overwrite`, yt-dlp akan mendeteksi file yang ada dan hanya melakukan pemrosesan pasca tanpa mengunduh ulang

I've added force overwrite, but it's still the same, no thumbnails appear in VLC

![image](https://user-images.githubusercontent.com/54851209/205489061-1e13b66a-7013-4092-9ad6-5eb9615a0477.png)
![image](https://user-images.githubusercontent.com/54851209/205489117-05155d51-c288-486e-b14f-be5c65d6ceaf.png)

**Comment by adibpwd** [comment]
strangely I tried to force it to mp4 in -o but it still webm

![image](https://user-images.githubusercontent.com/54851209/205490753-8c440a7f-d42a-4987-a94f-679750d4167f.png)

**Comment by adibpwd** [comment]
How delete f299?

![image](https://user-images.githubusercontent.com/54851209/205492207-61dfc8bb-9713-488d-a315-5269d3a91d7c.png)

![image](https://user-images.githubusercontent.com/54851209/205492193-d7aee1ee-3e97-4a19-b771-0d1416d17a1d.png)

**Comment by adibpwd** [comment]
Success : 
-f 22
Failed : 
-f 398+251
-f "bv*[height<=1440][ext=mp4]+ba"

if you use the '+' symbol, it will fail to embed the thumbnail, but if without '+' it will succeed in adding a thumbnail, that's what I've tried, maybe other friends will get different results, please let me know on this issue

![image](https://user-images.githubusercontent.com/54851209/205494253-2aece980-a808-4959-9873-a9cf502b11aa.png)

**Comment by Lesmiscore** [comment]
Please post your command **in text** since no one wants to transcribe from your screenshot.

```
$ yt-dlp -f 398+251 --embed-thumb --embed-meta MnRik-uv_Zc
[youtube] MnRik-uv_Zc: Downloading webpage
[youtube] MnRik-uv_Zc: Downloading android player API JSON
[info] MnRik-uv_Zc: Downloading 1 format(s): 398+251
[info] Downloading video thumbnail 41 ...
[info] Writing video thumbnail 41 to: Si gadis dipaksa menikahi tuan muda playboy, ditindih olehnya dan digigit bibirnya丨PT EP 2 [MnRik-uv_Zc].webp
WARNING: webm doesn't support embedding a thumbnail, mkv will be used
[download] Destination: Si gadis dipaksa menikahi tuan muda playboy, ditindih olehnya dan digigit bibirnya丨PT EP 2 [MnRik-uv_Zc].f398.mp4
[download] 100% of   10.43MiB in 00:00:04 at 2.48MiB/s
[download] Destination: Si gadis dipaksa menikahi tuan muda playboy, ditindih olehnya dan digigit bibirnya丨PT EP 2 [MnRik-uv_Zc].f251.webm
[download] 100% of    1.54MiB in 00:00:00 at 3.48MiB/s
[Merger] Merging formats into "Si gadis dipaksa menikahi tuan muda playboy, ditindih olehnya dan digigit bibirnya丨PT EP 2 [MnRik-uv_Zc].mkv"
Deleting original file Si gadis dipaksa menikahi tuan muda playboy, ditindih olehnya dan digigit bibirnya丨PT EP 2 [MnRik-uv_Zc].f398.mp4 (pass -k to keep)
Deleting original file Si gadis dipaksa menikahi tuan muda playboy, ditindih olehnya dan digigit bibirnya丨PT EP 2 [MnRik-uv_Zc].f251.webm (pass -k to keep)
[Metadata] Adding metadata to "Si gadis dipaksa menikahi tuan muda playboy, ditindih olehnya dan digigit bibirnya丨PT EP 2 [MnRik-uv_Zc].mkv"
[EmbedThumbnail] ffmpeg: Adding thumbnail to "Si gadis dipaksa menikahi tuan muda playboy, ditindih olehnya dan digigit bibirnya丨PT EP 2 [MnRik-uv_Zc].mkv"
```

And the thumbnail is embedded in webp format with these options:

```
$ ffprobe Si\ gadis\ dipaksa\ menikahi\ tuan\ muda\ playboy\,\ ditindih\ olehnya\ dan\ digigit\ bibirnya丨PT\ EP\ 2\ \[MnRik-uv_Zc\].mkv 
ffprobe version n4.4.1-3-ge16ff82624-20211127 Copyright (c) 2007-2021 the FFmpeg developers
  built with gcc 11.2.0 (crosstool-NG 1.24.0.479_aa52493)
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-ffbuild-linux-gnu- --arch=x86_64 --target-os=linux --enable-gpl --enable-version3 --disable-debug --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-libvorbis --enable-opencl --enable-libvmaf --enable-libxcb --disable-xlib --enable-amf --enable-libaom --enable-avisynth --enable-libdav1d --enable-libdavs2 --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --disable-frei0r --enable-libgme --enable-libass --enable-libbluray --enable-libmp3lame --enable-libopus --enable-mbedtls --enable-librist --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --enable-libmfx --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-librav1e --enable-librubberband --disable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --enable-libdrm --enable-vaapi --enable-libvidstab --disable-vulkan --disable-libglslang --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-ldexeflags=-pie --extra-libs=-lgomp --extra-version=20211127
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
[libdav1d @ 0x55b994c59640] libdav1d a55ff11
[matroska,webm @ 0x55b994c53d40] Could not find codec parameters for stream 2 (Attachment: none): unknown codec
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
Input #0, matroska,webm, from 'Si gadis dipaksa menikahi tuan muda playboy, ditindih olehnya dan digigit bibirnya丨PT EP 2 [MnRik-uv_Zc].mkv':
  Metadata:
    title           : Si gadis dipaksa menikahi tuan muda playboy, ditindih olehnya dan digigit bibirnya丨PT EP 2
    PURL            : https://www.youtube.com/watch?v=MnRik-uv_Zc
    COMMENT         : https://www.youtube.com/watch?v=MnRik-uv_Zc
    COMPATIBLE_BRANDS: iso6av01mp41
    MAJOR_BRAND     : dash
    MINOR_VERSION   : 0
    ARTIST          : NovelToonTV
    DATE            : 20211120
    DESCRIPTION     : Diadaptasi dari novel dengan judul sama : Pernikahan Tersembunyi, klik link di bawah untuk download aplikasi NovelToon, temukan judul bukunya untuk baca kisah serunya
                    : https://go.onelink.me/hhRS/2a9a1bf5
    SYNOPSIS        : Diadaptasi dari novel dengan judul sama : Pernikahan Tersembunyi, klik link di bawah untuk download aplikasi NovelToon, temukan judul bukunya untuk baca kisah serunya
                    : https://go.onelink.me/hhRS/2a9a1bf5
    ENCODER         : Lavf58.76.100
  Duration: 00:01:33.62, start: -0.007000, bitrate: 1082 kb/s
  Stream #0:0: Video: av1 (Main), yuv420p(tv, bt709), 720x1226 [SAR 1:1 DAR 360:613], 25 fps, 25 tbr, 1k tbn, 1k tbc (default)
    Metadata:
      HANDLER_NAME    : ISO Media file produced by Google Inc.
      VENDOR_ID       : [0][0][0][0]
      DURATION        : 00:01:33.614000000
  Stream #0:1(eng): Audio: opus, 48000 Hz, stereo, fltp (default)
    Metadata:
      DURATION        : 00:01:33.621000000
  Stream #0:2: Attachment: none
    Metadata:
      filename        : cover.webp
      mimetype        : image/webp
[libdav1d @ 0x55b994ce6200] libdav1d a55ff11
Unsupported codec with id 0 for input stream 2
```

Most likely the player don't recognize this format

**Comment by pukkandan** [comment]
If you prefer the thumbnails to be in another format, use `--convert-thumbnail png` etc
