### ISSUE TITLE
Is there any way to extract Direct Download Link using Ytdlp without downloading the file?

### ISSUE THREAD

**Issue by missemily22** [yt-dlp/yt-dlp#5717]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.11.11** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I would like to extract Download Link just without downloading the file 

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
> * 
> * [x]  I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)

Did you though?

`--print urls` OR `-g`

**Comment by missemily22** [comment]
@pukkandan But I wanna do it using python not via terminal

**Comment by pukkandan** [comment]
See https://github.com/yt-dlp/yt-dlp#extracting-information

Then, do
```py
formats = info.get('requested_formats') or [info]
urls = [f['url'] for f in formats]
```

**Comment by missemily22** [comment]
@pukkandan Thanks Brother
