### ISSUE TITLE
Apple TV *Movie Trailers Only* (tv.apple.com)

### ISSUE THREAD

**Issue by rmarkham1** [yt-dlp/yt-dlp#5721]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.11.11** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

United States

### Example URLs

https://tv.apple.com/us/movie/cruel-intentions/umc.cmc.2wd45qpm08n0adzv8ug05v5rj

https://tv.apple.com/us/movie/call-me-by-your-name/umc.cmc.4qs91ldaqauuwed1v8i1dz1c7

https://tv.apple.com/us/movie/passion/umc.cmc.23p5yc51ui69fsk2dlz1wcwin

### Provide a description that is worded well enough to be understood

Movie trailers WILL download however, they are full of errors. The video skips, freezes and the times are also not correct.

I do not wish to download anything other than the movie trailers that are available freely on the pages, I am not interested in the actual film, just the trailer.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '-f', '10248-1', 'https://tv.apple.com/us/movie/cruel-intentions/umc.cmc.2wd45qpm08n0adzv8ug05v5rj']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.11.11 [8b64402] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-92190-gb2adc31697, ffprobe N-92190-gb2adc31697
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1723 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.11.11, Current version: 2022.11.11
yt-dlp is up to date (2022.11.11)
[debug] [generic] Extracting URL: https://tv.apple.com/us/movie/cruel-intentions/umc.cmc.2wd45qpm08n0adzv8ug05v5rj
[generic] umc.cmc: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] umc.cmc: Extracting information
[debug] Looking for embeds
[debug] Identified a Open Graph video info
[generic] playlist: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[info] playlist: Downloading 1 format(s): 10248-1
[debug] Invoking hlsnative downloader on "https://vod-ap-amt.tv.apple.com/itunes-assets/VideoPreview124/v4/a2/83/cc/a283cccd-7aa9-58a2-b29e-01aa1d9fd7a7/P137718664_A1529475473_FF.p_video_gr290_sdr_-.m3u8"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 16
[download] Destination: Cruel Intentions ｜ Apple TV [playlist].mp4
[debug] File locking is not supported. Proceeding without locking
[download] 100% of  161.31MiB in 00:00:29 at 5.40MiB/s
[debug] ffprobe command line: ffprobe -hide_banner -show_format -show_streams -print_format json "file:Cruel Intentions ｜ Apple TV [playlist].mp4"
```

**Comment by coletdjnz** [comment]
They play fine for me in mpv. Sounds like an issue with whatever player you are using?

**Comment by pukkandan** [comment]
Pls confirm with another player. If issue persists, the output of ffprobe on the video may be usefull

**Comment by rmarkham1** [comment]
> Pls confirm with another player. If issue persists, the output of ffprobe on the video may be usefull

I updated VLC and the video seems to playback properly now, thank-you.
