### ISSUE TITLE
How does YT-DLP figure out the resolutions of video?

### ISSUE THREAD

**Issue by metalune1** [yt-dlp/yt-dlp#5726]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.11.11** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I'm the developer of a PeerTube frontend called SimpleerTube, https://github.com/SimpleWeb/SimpleerTube and I want to add functionality so if users try to download videos from there using yt-dlp they can filter using the builtin resolutions options but I don't know how to give yt-dlp the information it needs for the generic extractor. Is it done using some HTML tags?

**Comment by dirkf** [comment]
As no-one else has bitten ...

Your project link is 404.

If your video page linked one of the manifest types known to yt-dlp in one of the standard ways, say as a .m3u8 in the `contentURL` of a ld+json script block, and ideally with other metadata defined for https://schema.org/MediaObject, such a manifest should be found and analyzed, including listing the available formats. Ditto for upstream. Your site code would have to generate the new block and the manifest: you could either generate the manifest along with the page, or construct it on-demand.

Alternatively you could restructure the video page using HTML5 video, which will be discovered, but that would be a bigger change, affecting the UI.

**Comment by pukkandan** [comment]
Pls give us the URL to your instance. It should *just work* if we add it to known Peertube instances

**Comment by dirkf** [comment]
It's a different page format, I think. I looked at https://st.vern.cc/tube.xy-space.de/videos/watch/2aa7fa9a-c21e-4dba-b5a7-078a24ec76bc/.

There are resolution links, each of which opens a new page with the selected resolution embedded. One "resolution" is an embedded PeerTube video that might be found already. Others are specific to SimpleerTube. I really don't understand why the site didn't use HTML5 video, unless something like Lynx doesn't understand it.

**Comment by pukkandan** [comment]
> Others are specific to SimpleerTube.

Doesn't look like it. Checking with a random video that has multiple formats, all the formats can be detected by our peertube extractor, though not with Generic

So extractor would be just

```py
class SimpleerTube(InfoExtractor):
    _VALID_URL = 'https?://https://st.vern.cc/(?P<domain>[^/#?]+)/videos/watch/(?P<id>[^/#?]+)'
    
    def _real_extract(self, url):
        domain, video_id = self._match_valid_url(url).group('domain', 'id')
        return self.url_result(f'peertube:{domain}:{video_id}', PeerTubeIE)
```

**Comment by dirkf** [comment]
As I read it, OP was interested in changing the page format in the ST project so that it would be detected automatically, without additional extractor code. OTOH if additional extraction is OK, that's certainly a minimal addition, but it would need to use the extract_embed() pattern like the other front-end sites that can't be detected from the URL alone.

**Comment by pukkandan** [comment]
The current peertube code doesn't have any way for a site to indicate itself as a peertube frontend. We could however easily implement such a method. I suggest using `link[rel=alternate]` like https://github.com/iv-org/invidious/pull/1730. But you might want to first discuss it with Peertube devs to standardize it.

If it becomes standardized, or you decide to use it anyway, pls let us know and I'll add the code to detect the same

**Comment by pukkandan** [comment]
Closing since OP hasn't responded to either of our comments. Can re-open as needed

**Comment by metalune1** [comment]
sorry, I was offline for a long time, I'm back now and open for questions (I don't check my github that often) https://codeberg.org/SimpleWeb/SimpleerTube is the new link of the project. I didn't know that HTML5 Video had a function to allow for video resolution switching. I'd kindly ask for a link to a resource explaining that, I haven't found anything myself so I just assumed that it didn't exist.

**Comment by dirkf** [comment]
[MDN](https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Video_and_audio_content)!
