### ISSUE TITLE
The downloaded videos often encounter videos with missing frames

### ISSUE THREAD

**Issue by shimiaoyerin** [yt-dlp/yt-dlp#5728]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.11.11** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

This is particularly common in "dash" videos,

-------------------------

https://www.youtube.com/watch?v=o8KkiAaDEVY
(Here is a sample of the video I downloaded with missing frames
"https://drive.google.com/file/d/1_jrBKZ_lnFVzRLEmHtFOrIcN4vwQsKWP/view?usp=share_link")
![QQ截图20221206192320](https://user-images.githubusercontent.com/45694554/205898799-44755f32-0128-4302-ba4e-d6cbfb988266.png)
You can see the missing frame at the beginning, but it does not hurt the whole video, and the following video clips can be played normally
I put the specific logs at the bottom

-------------------------

I also have a way to recreate similar cases manually

yt-dlp will create files with "part" extension, aria2 will create files with "aria2" extension, aria2 will create files with both extensions when downloading

1: First download a video with aria2 to download 30%, and then close it, there is still a file with the suffix "aria2" in the folder

2: Start the download again, don't start aria2 this time, download with yt-dlp alone, then download to 30%, and then close

3: Enable aria2 download again. After downloading, you will find a video with missing frames

All three trials were triggered with almost 100% chance of triggering

------------------------------------
I didn't capture the detailed logs, but given the description above, can we do something about it? I would love to know what ffmpeg does when compositing? But I can't see the synthesis process, maybe you can help me capture more information? Or can downloaded fragments be added to a proofreading process?

Why do I care so much? Because I download these files like an Internet history museum, most of the videos disappear from this network for some reason, so I need to record it, so once some videos are missed, there is no second chance to download them for you. The following picture is the missing frame video I selected from more than 4000 videos

![QQ截图20221206211607](https://user-images.githubusercontent.com/45694554/205922614-ecf19b61-13bf-49d8-97df-f1da3e4cf5b6.png)
I screened the video in the above picture by using the tool in the link below. The use method is very simple, you only need to input the path you need to screen, and the running environment must include ffmpeg. My own code knowledge is weak, and I paid someone else to do this tool

https://drive.google.com/file/d/1GkJLmhOM1UkCyPNkndFei9vDc6MBjl1n/view?usp=share_link

 

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['--playlist-start', '1', '-S', 'res,vbr,abr', '--config-location', '配置文件.txt', '-v']
[debug] | Config "配置文件.txt": ['--sleep-interval', '0', '-o', '%(title)s-宽度%(width)s-码率%(vbr)s-编码%(vcodec)s-频道名(%(uploader)s)-网页地址%(id)s.%(ext)s', '--paths', 'temp:C:\\Users\\yerin\\Desktop\\测试aria2下载失败的时候，删除未完成的文件\\yt-dlp下载暂存盘', '--paths', 'home:下载文件夹', '--no-continue', '--external-downloader', 'aria2c', '--extractor-args', 'youtube:player_client=android,web', '-f', 'bestvideo[width> 15360]+bestaudio/bestvideo[width> 10000]+bestaudio/bestvideo[width> 9900]+bestaudio/bestvideo[width> 9800]+bestaudio/bestvideo[width> 9700]+bestaudio/bestvideo[width> 9600]+bestaudio/bestvideo[width> 9500]+bestaudio/bestvideo[width> 9400]+bestaudio/bestvideo[width> 9200]+bestaudio/bestvideo[width> 9100]+bestaudio/bestvideo[width> 8900]+bestaudio/bestvideo[width> 8800]+bestaudio/bestvideo[width> 8700]+bestaudio/bestvideo[width> 8600]+bestaudio/bestvideo[width> 8500]+bestaudio/bestvideo[width> 8400]+bestaudio/bestvideo[width> 8300]+bestaudio/bestvideo[width> 8200]+bestaudio/bestvideo[width> 8100]+bestaudio/bestvideo[width> 8000]+bestaudio/bestvideo[width> 7900]+bestaudio/bestvideo[width> 7800]+bestaudio/bestvideo[width> 7700]+bestaudio/bestvideo[width> 7600]+bestaudio/bestvideo[width> 7500]+bestaudio/bestvideo[width> 7400]+bestaudio/bestvideo[width> 7300]+bestaudio/bestvideo[width> 7200]+bestaudio/bestvideo[width> 7100]+bestaudio/bestvideo[width> 7000]+bestaudio/bestvideo[width> 6900]+bestaudio/bestvideo[width> 6800]+bestaudio/bestvideo[width> 6700]+bestaudio/bestvideo[width> 6600]+bestaudio/bestvideo[width> 6500]+bestaudio/bestvideo[width> 6400]+bestaudio/bestvideo[width> 6300]+bestaudio/bestvideo[width> 6200]+bestaudio/bestvideo[width> 6100]+bestaudio/bestvideo[width> 6000]+bestaudio/bestvideo[width> 5900]+bestaudio/bestvideo[width> 5800]+bestaudio/bestvideo[width> 5700]+bestaudio/bestvideo[width> 5600]+bestaudio/bestvideo[width> 5500]+bestaudio/bestvideo[width> 5400]+bestaudio/bestvideo[width> 5300]+bestaudio/bestvideo[width> 5200]+bestaudio/bestvideo[width> 5100]+bestaudio/bestvideo[width> 5000]+bestaudio/bestvideo[width> 4900]+bestaudio/bestvideo[width> 4800]+bestaudio/bestvideo[width> 4700]+bestaudio/bestvideo[width> 4600]+bestaudio/bestvideo[width> 4500]+bestaudio/bestvideo[width> 4400]+bestaudio/bestvideo[width> 4300]+bestaudio/bestvideo[width> 4200]+bestaudio/bestvideo[width> 4100]+bestaudio/bestvideo[width> 4000]+bestaudio/bestvideo[width> 3900]+bestaudio/bestvideo[width> 3800]+bestaudio/bestvideo[width> 3700]+bestaudio/bestvideo[width> 3600]+bestaudio/bestvideo[width> 3500]+bestaudio/bestvideo[width> 3400]+bestaudio/bestvideo[width> 3300]+bestaudio/bestvideo[width> 3200]+bestaudio/bestvideo[width> 3100]+bestaudio/bestvideo[width> 3000]+bestaudio/bestvideo[width> 2900]+bestaudio/bestvideo[width> 2800]+bestaudio/bestvideo[width> 2700]+bestaudio/bestvideo[width> 2600]+bestaudio/bestvideo[width> 2500]+bestaudio/bestvideo[width> 2400]+bestaudio/bestvideo[width> 2300]+bestaudio/bestvideo[width> 2200]+bestaudio/bestvideo[width> 2100]+bestaudio/bestvideo[width> 2000]+bestaudio/bestvideo[width> 1900]+bestaudio/bestvideo[width> 1800]+bestaudio/bestvideo[width> 1800]+bestaudio/bestvideo[width> 1700]+bestaudio/bestvideo[width> 1600]+bestaudio/bestvideo[width> 1500]+bestaudio/bestvideo[width> 1400]+bestaudio/bestvideo[width> 1300]+bestaudio/bestvideo[width> 1200]+bestaudio/bestvideo[width> 1100]+bestaudio/bestvideo[width> 1000]+bestaudio/bestvideo[width> 900]+bestaudio/bestvideo[width> 800]+bestaudio/bestvideo[width> 700]+bestaudio/bestvideo+bestaudio']
[debug] Encodings: locale cp936, fs utf-8, pref cp936, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.11.11 [8b64402] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19044-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg n5.1.2-7-ga6e26053c2-20221123 (setts), ffprobe n5.1.2-7-ga6e26053c2-20221123
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {'https': 'http://127.0.0.1:10081', 'http': 'http://127.0.0.1:10081'}
[debug] Loaded 1723 extractors


-----------------
#( Here is a log captured on video of the appeal )
#I don't have a very detailed log of the network download process, since this is an occasional situation and the log output would be huge if we were to capture it in detail


[download] Downloading video 2026 of 2033
[youtube] o8KkiAaDEVY: Downloading webpage
[youtube] o8KkiAaDEVY: Downloading android player API JSON
[youtube] o8KkiAaDEVY: Downloading MPD manifest
[youtube] o8KkiAaDEVY: Downloading MPD manifest
[info] o8KkiAaDEVY: Downloading 1 format(s): 299+251-dash
[dashsegments] Total fragments: 120
[dashsegments] Fragment downloads will be delegated to aria2c
[download] Destination: C:\下载youtube用\yt-dlp下载暂存盘\181008  -宽度1920-码率5775.0-编码avc1.64001e-频道名(David Park)-网页地址o8KkiAaDEVY.f299.mp4

[aria2c] Downloaded 424258111 bytes
[download] Download completed
[dashsegments] Total fragments: 62
[dashsegments] Fragment downloads will be delegated to aria2c
[download] Destination: C:\下载youtube用\yt-dlp下载暂存盘\181008  -宽度1920-码率5775.0-编码avc1.64001e-频道名(David Park)-网页地址o8KkiAaDEVY.f251-dash.webm

[aria2c] Downloaded 9949013 bytes
[download] Download completed
[Merger] Merging formats into "C:\下载youtube用\yt-dlp下载暂存盘\181008  -宽度1920-码率5775.0-编码avc1.64001e-频道名(David Park)-网页地址o8KkiAaDEVY.mkv"
Deleting original file C:\下载youtube用\yt-dlp下载暂存盘\181008  -宽度1920-码率5775.0-编码avc1.64001e-频道名(David Park)-网页地址o8KkiAaDEVY.f251-dash.webm (pass -k to keep)
Deleting original file C:\下载youtube用\yt-dlp下载暂存盘\181008  -宽度1920-码率5775.0-编码avc1.64001e-频道名(David Park)-网页地址o8KkiAaDEVY.f299.mp4 (pass -k to keep)
[MoveFiles] Moving file "C:\下载youtube用\yt-dlp下载暂存盘\181008  -宽度1920-码率5775.0-编码avc1.64001e-频道名(David Park)-网页地址o8KkiAaDEVY.mkv" to "I:\youtube暂时下载文件\Youtube专用\总文件14\下载文件夹\181008  -宽度1920-码率5775.0-编码avc1.64001e-频道名(David Park)-网页地址o8KkiAaDEVY.mkv"
```

**Comment by pukkandan** [comment]
> yt-dlp will create files with "part" extension, aria2 will create files with "aria2" extension, aria2 will create files with both extensions when downloading
> 
> 1: First download a video with aria2 to download 30%, and then close it, there is still a file with the suffix "aria2" in the folder
> 
> 2: Start the download again, don't start aria2 this time, download with yt-dlp alone, then download to 30%, and then close
> 
> 3: Enable aria2 download again. After downloading, you will find a video with missing frames
> 
> All three trials were triggered with almost 100% chance of triggering

Why would you mix multiple downloaders on the same video?



> I would love to know what ffmpeg does when compositing?

Use `-v` to see the command yt-dlp passes to ffmpeg

**Comment by pukkandan** [comment]
> I didn't mix the downloaders, I was just trying to explain to you the problems with multi-threaded downloads,

Ok, but what is the actual problem then?



> The following log is my test process. We can find that at the beginning of downloading aria2 to 11%, I shut down the process, and then restart and start to download with yt-dlp. At this time, the previous downloaded process has been covered, but the arid2 suffix file has not been covered, and then when the download reaches 30%, I shut down the process. When I started aria2 again, it started downloading from 11%, but the previous file had been overwritten, but it still started downloading from 11%. What's worse, the video was synthesized successfully, and the video could be played, but some parts did not play properly

Interrupting one downloader and resuming with another is not a supported use case

**Comment by shimiaoyerin** [comment]
I am still testing it now, and would like to ask - does no-continue work for aria2?

**Comment by shimiaoyerin** [comment]
I am still testing it now, and would like to ask - does no-continue work for aria2?

**Comment by shimiaoyerin** [comment]
> Interrupting one downloader and resuming with another is not a supported use case

I'm not going to download the video like this, I'm just trying to reconstruct an event for you to explain to you what the problem is


> Ok, but what is the actual problem then?

I mean, due to the unstable network in our country, there are many cases of missing frames in videos downloaded by fragments.

According to my test, yt-dlp skips the clips that have been retried many times by default, but aria2 will not skip fragments that have been retried many times.  However, the following log shows that this video is downloaded successfully in one time without retrying, but there is also a phenomenon of missing frames, and most of the videos with missing frames are focused on dash videos


### Complete Verbose Output

```shell
[download] Downloading video 2026 of 2033
[youtube] o8KkiAaDEVY: Downloading webpage
[youtube] o8KkiAaDEVY: Downloading android player API JSON
[youtube] o8KkiAaDEVY: Downloading MPD manifest
[youtube] o8KkiAaDEVY: Downloading MPD manifest
[info] o8KkiAaDEVY: Downloading 1 format(s): 299+251-dash
[dashsegments] Total fragments: 120
[dashsegments] Fragment downloads will be delegated to aria2c
[download] Destination: C:\下载youtube用\yt-dlp下载暂存盘\181008  -宽度1920-码率5775.0-编码avc1.64001e-频道名(David Park)-网页地址o8KkiAaDEVY.f299.mp4

[aria2c] Downloaded 424258111 bytes
[download] Download completed
[dashsegments] Total fragments: 62
[dashsegments] Fragment downloads will be delegated to aria2c
[download] Destination: C:\下载youtube用\yt-dlp下载暂存盘\181008  -宽度1920-码率5775.0-编码avc1.64001e-频道名(David Park)-网页地址o8KkiAaDEVY.f251-dash.webm

[aria2c] Downloaded 9949013 bytes
[download] Download completed
[Merger] Merging formats into "C:\下载youtube用\yt-dlp下载暂存盘\181008  -宽度1920-码率5775.0-编码avc1.64001e-频道名(David Park)-网页地址o8KkiAaDEVY.mkv"
Deleting original file C:\下载youtube用\yt-dlp下载暂存盘\181008  -宽度1920-码率5775.0-编码avc1.64001e-频道名(David Park)-网页地址o8KkiAaDEVY.f251-dash.webm (pass -k to keep)
Deleting original file C:\下载youtube用\yt-dlp下载暂存盘\181008  -宽度1920-码率5775.0-编码avc1.64001e-频道名(David Park)-网页地址o8KkiAaDEVY.f299.mp4 (pass -k to keep)
[MoveFiles] Moving file "C:\下载youtube用\yt-dlp下载暂存盘\181008  -宽度1920-码率5775.0-编码avc1.64001e-频道名(David Park)-网页地址o8KkiAaDEVY.mkv" to "I:\youtube暂时下载文件\Youtube专用\总文件14\下载文件夹\181008  -宽度1920-码率5775.0-编码avc1.64001e-频道名(David Park)-网页地址o8KkiAaDEVY.mkv"
```


------------

I thought the missing frames were caused by too many retries, so I wanted to find a way to make aria2 download from the beginning instead of resuming the download, but the video without "retry download" also had missing frames

Note: When it comes to multi-fragment download, if I tamper with one fragment, he can still compose the video successfully

I also ran another experiment where I interrupted the yt-dlp download and replaced the original Frag(n).part with a fake file, which caused the same problem as in my previous video, although the ```--no-continue``` option prevented "Frag" from being tampered with. But in the face of a harsh network environment, I do not know how he produced the above results

I have the following guess

youtube videos, even at the same resolution, will change in size within a few days of release. For example, today 1080p is 100MB in size, tomorrow the same 1080P will become 200MB in size, and I am just in the middle of this time node to download

I'm still testing more. I need to capture the most critical logs to know what's going on. What is certain is that most of the videos with missing frames are dash

**Comment by jasoncbraatz** [comment]
Landed here after hitting the same symptom on a different extractor (`loom`), so dropping a note for the next traveler:

**Repro on Loom HLS (yt-dlp 2026.03.17, macOS arm64, ffmpeg 7.1.1):**

```bash
yt-dlp --concurrent-fragments 16 \
       --retries 30 --fragment-retries 30 \
       -f "hls-raw-3200+hls-raw-audio-audio" \
       --merge-output-format mp4 \
       https://www.loom.com/share/27a76b19d4bc4d568470bfc643852102
```

The manifest declares 303 video fragments / ~20:12 of content. Output file: silently 2:24 (88% truncated). yt-dlp reports `[download] Download completed` and exits 0. No errors, no warnings, nothing in `--verbose` indicating loss. `--abort-on-unavailable-fragments` does not help because from yt-dlp's perspective every fragment HTTP request returned 200.

The CDN (CloudFront in front of Loom's storage) appears to short-circuit some fragment responses under high concurrency — yt-dlp gets back what looks like a valid response but the resulting file is missing trailing data. Downstream the muxer happily produces a CFR mp4 truncated to whatever continuous run of frames did make it through.

**Workaround that consistently produces full files:**

```bash
yt-dlp --concurrent-fragments 1 \
       --retries 30 --fragment-retries 30 --retry-sleep 2 \
       -f "hls-raw-3200" -o video.mp4  URL
yt-dlp --concurrent-fragments 1 \
       --retries 30 --fragment-retries 30 --retry-sleep 2 \
       -f "hls-raw-audio-audio" -o audio.mp4  URL
```

Single-fragment serial downloads with 30 retries per fragment recover all 303 fragments every time on the same network. The cost is ~2× wall time per download.

**Suggestion for a defensive validation step**: after a successful HLS download, compare the actual delivered fragment count to the manifest's `#EXTINF:` count and warn (or error with `--abort-on-unavailable-fragments`) if they don't match. That would catch this CDN-induced truncation class without requiring users to re-encode and probe duration vs. expected manifest sum to discover the loss after the fact.

Sharing in case it saves anyone the multi-hour debugging detour we just took.

**Comment by bashonly** [comment]
> Suggestion for a defensive validation step: after a successful HLS download, compare the actual delivered fragment count to the manifest's #EXTINF: count

you could just use `--abort-on-unavailable-fragments`
