### ISSUE TITLE
i need to download video from a streaming website any help ??

### ISSUE THREAD

**Issue by mazen011** [yt-dlp/yt-dlp#5740]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.11.11** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

https://resource.inkryptvideos.com/v2-a83ns52/iframe/index.html#video_id=7999ea0f6e03439eb40d056258c2d736&otp=8d6830348a7a485cba0a6519683cb12cc62dcd19ec984e6d90444f2f88cd3948&api=api&license=license&config=eyJ0eXBlIjoicnRleHQiLCJ0ZXh0IjoiQ29weXJpZ2h0IHByb3RlY3RlZCIsImFscGhhIjowLjUsImNvbG9yIjoiI0ZGMDAwMCIsInNpemUiOjE1LCJpbnRlcnZhbCI6MTAwMDB9

--------

this is the website stream that iam trying to download from , is there anyway that i can download this video in my pc ??

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
from `https://inkryptvideos.com/`:
> Enjoy Safe & Encrypted Video Content You create engaging media; We’ll secure it for you. Learn More Secure Video Hosting Protect your video content breaching with our secure & encrypted server for video hosting. Find out more Prevent Video Download Eliminate video downloading & screen-recording risks with reliable DRM & security features

No help will be provided for downloading DRM-protected content
