### ISSUE TITLE
[AdultSwim] HTTPError 401 when attempting to use --ap-mso and credentials to download paywalled video

### ISSUE THREAD

**Issue by lordairivis** [yt-dlp/yt-dlp#5742]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.11.11** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United States

### Provide a description that is worded well enough to be understood

I'm attempting to download a video from adultswim.com which requires my cable subscription login, but I'm getting an HTTP 401 error in yt-dlp. I've confirmed the username and password are correct and can log in successfully directly on the site but authentication appears to fail when passing those same credentials through to yt-dlp.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['--ap-mso', 'Comcast_SSO', '--ap-username', 'PRIVATE', '--ap-password', 'PRIVATE', '-vU', 'https://www.adultswim.com/videos/off-the-air/bliss']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.11.11 [8b64402] (zip)
[debug] Python 3.8.10 (CPython x86_64 64bit) - Linux-5.15.0-56-generic-x86_64-with-glibc2.29 (OpenSSL 1.1.1f  31 Mar 2020, glibc 2.31)
[debug] exe versions: ffmpeg 4.2.7, ffprobe 4.2.7, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.6.1, certifi-2019.11.28, mutagen-1.45.1, pyxattr-0.6.1, secretstorage-2.3.1, sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Loaded 1723 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.11.11, Current version: 2022.11.11
yt-dlp is up to date (2022.11.11)
[debug] [AdultSwim] Extracting URL: https://www.adultswim.com/videos/off-the-air/bliss
[AdultSwim] bliss: Downloading JSON metadata
[AdultSwim] 8883d483655b9ab518ffe8bba117f9625c655a63: Downloading JSON metadata
[AdultSwim] 8883d483655b9ab518ffe8bba117f9625c655a63: Downloading Provider Redirect Page
[AdultSwim] 8883d483655b9ab518ffe8bba117f9625c655a63: Logging in
[AdultSwim] 8883d483655b9ab518ffe8bba117f9625c655a63: Retrieving Session
ERROR: [AdultSwim] Unable to download webpage: HTTP Error 401:  (caused by <HTTPError 401: ''>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 674, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/adultswim.py", line 152, in _real_extract
    info.update(self._extract_ngtv_info(media_id, {
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/turner.py", line 234, in _extract_ngtv_info
    m3u8_url = self._add_akamai_spe_token(
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/turner.py", line 38, in _add_akamai_spe_token
    query['accessToken'] = self._extract_mvpd_auth(ap_data['url'], content_id, ap_data['site_name'], ap_data['site_name'])
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/adobepass.py", line 1720, in _extract_mvpd_auth
    session = self._download_webpage(
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 1083, in _download_webpage
    return self.__download_webpage(url_or_request, video_id, note, errnote, None, fatal, *args, **kwargs)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 1034, in download_content
    res = getattr(self, download_handle.__name__)(url_or_request, video_id, **kwargs)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/adobepass.py", line 1366, in _download_webpage_handle
    return super(AdobePassIE, self)._download_webpage_handle(
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 868, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query, expected_status=expected_status)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 825, in _request_webpage
    raise ExtractorError(errmsg, cause=err)

  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 807, in _request_webpage
    return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query))
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3692, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 401:
```

**Comment by bashonly** [comment]
I've had success before with authenticating in-browser and then passing `--cookies-from-browser` in addition to the `--ap` opts. Worth a try. I'm not eligible to access this content though

**Comment by lordairivis** [comment]
I just tried with ``--cookies-from-browser`` and got the same error unfortunately.

**Comment by flashdagger** [comment]
@lordairivis Just to be sure. Could you export the cookies and try with `--cookies`? the results can sometimes differ.

**Comment by lordairivis** [comment]
I added ``--cookies cookies.txt`` to my command and it appears to be downloading fine now, not sure what changed.

**Comment by bashonly** [comment]
> I added `--cookies cookies.txt` to my command and it appears to be downloading fine now, not sure what changed.

Most likely related to #5534; the needed auth info was stored in your session cookies, which aren't extracted by `--cookies-from-browser` (and can't be extracted from other browsers like firefox)

Ideally though, AdobePassIE would be fixed so that passing session cookies is not necessary

**Comment by lordairivis** [comment]
Excellent, I will marked this as closed/resolved in that case. Hopefully this bug can be fixed soon!

**Comment by cds85** [comment]
@lordairivis - can you provide advice on how you extracted your cookies? I'm using a M1 Mac and want to make sure I'm replicating what has worked for you if possible. I tried the Firefox extension but it doesn't appear to give the same joy your having :)

**Comment by lordairivis** [comment]
@cds85 I believe I used the Firefox extension [cookies.txt](https://github.com/hrdl-github/cookies-txt) to extract the site's cookies.

**Comment by octavioj** [comment]
Even exporting the cookies it still does not work for me. I am trying to download an episode of The Ark.

An example:

https://www.nbc.com/the-ark/video/the-painful-way/9000326420

Here is the output of the yt-dlp command with -v:

[debug] Command-line config: ['--ap-mso', 'Charter_Direct', '--ap-username', 'PRIVATE', '--ap-password', 'PRIVATE', '-o', '%(series)s - S%(season_number)sE%(episode_number)s - %(episode)s.%(ext)s', '--cookies', '/userfiles/Downloads/Firefox Downloads/cookies.txt', '-v', 'https://www.nbc.com/the-ark/video/the-painful-way/9000326420']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (pip)
[debug] Python 3.10.6 (CPython x86_64 64bit) - Linux-5.15.0-69-generic-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.11.0, brotli-1.0.9, certifi-2020.06.20, mutagen-1.45.1, pyxattr-0.7.2, secretstorage-3.3.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
[NBC] Extracting URL: https://www.nbc.com/the-ark/video/the-painful-way/9000326420
[NBC] 9000326420: Downloading JSON metadata
[NBC] 9000326420: Downloading JSON metadata
[NBC] 9000326420: Downloading Provider Redirect Page
ERROR: [NBC] 9000326420: Unable to extract post url; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/home/vagrant/.local/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 694, in extract
    ie_result = self._real_extract(url)
  File "/home/vagrant/.local/lib/python3.10/site-packages/yt_dlp/extractor/nbc.py", line 204, in _real_extract
    query['auth'] = self._extract_mvpd_auth(
  File "/home/vagrant/.local/lib/python3.10/site-packages/yt_dlp/extractor/adobepass.py", line 1707, in _extract_mvpd_auth
    provider_login_page_res = post_form(
  File "/home/vagrant/.local/lib/python3.10/site-packages/yt_dlp/extractor/adobepass.py", line 1395, in post_form
    post_url = self._html_search_regex(r'<form[^>]+action=(["\'])(?P<url>.+?)\1', form_page, 'post url', group='url')
  File "/home/vagrant/.local/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 1278, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/home/vagrant/.local/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 1242, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)

**Comment by bashonly** [comment]
@octavioj try `Spectrum` instead of `Charter_Direct` as the MSO

**Comment by octavioj** [comment]
> @octavioj try `Spectrum` instead of `Charter_Direct` as the MSO

That did the trick. Thank you.
