### ISSUE TITLE
FutureWarning: Possible nested set at position 3 in jsinterp.py

### ISSUE THREAD

**Issue by ndren** [yt-dlp/yt-dlp#5749]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.11.11** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Unrestricted

### Provide a description that is worded well enough to be understood

Downloading https://youtube.com/watch?v=jzRrUPQgrpc leads to a FutureWarning on Python 3.10, Arch Linux. I can only reproduce this on that specific YouTube URL, suggesting that yt-dlp hit a parsing edge case. 

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://youtube.com/watch?v=jzRrUPQgrpc']
[debug] User config "/home/$USER/.config/yt-dlp/config": ['-f', 'mp4[height>=720]', '--restrict-filenames']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.11.11 [8b64402]
[debug] Python 3.10.8 (CPython x86_64 64bit) - Linux-5.15.81-1-lts-x86_64-with-glibc2.36 (OpenSSL 3.0.7 1 Nov 2022, glibc 2.36)
[debug] exe versions: ffmpeg 5.1.2 (setts), ffprobe 5.1.2
[debug] Optional libraries: certifi-2022.09.24, sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Loaded 1723 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.11.11, Current version: 2022.11.11
yt-dlp is up to date (2022.11.11)
[debug] [youtube] Extracting URL: https://youtube.com/watch?v=jzRrUPQgrpc
[youtube] jzRrUPQgrpc: Downloading webpage
[youtube] jzRrUPQgrpc: Downloading android player API JSON
[debug] Loading youtube-nsig.72d3c60a from cache
/usr/lib/python3.10/site-packages/yt_dlp/jsinterp.py:346: FutureWarning: Possible nested set at position 3
  inner = re.compile(inner[1:], flags=flags)
[debug] [youtube] Decrypted nsig 1GNC6u6XPSblJeLSe => HtSIq-cfYPC48A
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[info] jzRrUPQgrpc: Downloading 1 format(s): 22
[debug] Invoking http downloader on "https://rr2---sn-u5a3u5a3-h5oel.googlevideo.com/videoplayback?expire=1670540362&ei=6heSY4nPKJD1xgLJwrboCA&ip=88.106.28.171&id=o-AETkKx6duUr2V7PNK9VUoMLJFeuXrvzEh9MeHosUwdFV&itag=22&source=youtube&requiressl=yes&mh=M5&mm=31%2C29&mn=sn-u5a3u5a3-h5oel%2Csn-aigl6nzk&ms=au%2Crdu&mv=m&mvi=2&pl=20&initcwndbps=1433750&spc=SFxXNgfyIVYxZK50wZ0EkDNGEY3QeDI&vprv=1&svpuc=1&mime=video%2Fmp4&cnr=14&ratebypass=yes&dur=822.543&lmt=1670511366146582&mt=1670518404&fvip=4&fexp=24001373%2C24007246&c=ANDROID&txp=3318224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Ccnr%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRgIhAJHT4sZWnxCzFKTZiY-eXYsEwJigIcawkC6t59h-wApyAiEAm7ZF_keoLiPjiDn8LfFY8at-hMO9jNr0SGdOI-v1LMw%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgJyAONHJKm3_u5LidpOeyNSZwg5AJbxBFt16_GfEHHZkCICCSa_VMSNgOJHlWzOLqFqUn4wujtOZhHbFTrR93Aj-f"
[download] Destination: Verifying_AI_Black_Boxes_-_Computerphile-[jzRrUPQgrpc].mp4
[download] 100% of  137.98MiB in 00:00:09 at 15.33MiB/s
```

**Comment by pukkandan** [comment]
It's happening due to slight difference in how regex works b/w JS and Python. Despite the warning, everything's actually working fine

**Comment by ndren** [comment]
What about the following:
> [FutureWarning](https://docs.python.org/dev/library/exceptions.html#FutureWarning) is now emitted if a regular expression contains character set constructs that will change semantically in the future, such as nested sets and set operations. (Contributed by Serhiy Storchaka in [bpo-30349](https://bugs.python.org/issue?@action=redirect&bpo=30349).)

Is https://docs.python.org/dev/whatsnew/3.7.html incorrectly flagging this up, or is there a risk that this may break in a future version of Python?

Thanks for the help.

**Comment by jericjan** [comment]
Sorry for commenting on a closed issue but is there a flag that hides this message? `--no-warning` doesn't seem to have any effect on it.

**Comment by pukkandan** [comment]
It's controlled by an env var https://docs.python.org/3/using/cmdline.html#envvar-PYTHONWARNINGS

**Comment by nil-vr** [comment]
Setting the environment variable works if you've used `pip install` or similar, but does not work if you're using a version bundled by PyInstaller or py2exe. Those tell Python to ignore the usual environment variables during initialization.
