### ISSUE TITLE
Does not support urls with @ symbol on YouTube

### ISSUE THREAD

**Issue by mishav78** [yt-dlp/yt-dlp#5759]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.11.11** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

I ran this. It works with normal urls for channels but not those with @ 
yt-dlp -f best -ciw -o "%(title)s.%(ext)s" -v "https://www.youtube.com/channel/@Rezilienza"

got this 

ERROR: [youtube:tab] \@Rezilienza: Unable to download API page: HTTP Error 400: Bad Request (caused by <HTTPError 400: 'Bad Request'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/extractor/common.py", line 674, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/extractor/youtube.py", line 4285, in wrapper
    info_dict = func(self, url, smuggled_data)
  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/extractor/youtube.py", line 5999, in _real_extract
    data, ytcfg = self._extract_data(url, display_id)
  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/extractor/youtube.py", line 4937, in _extract_data
    data = self._extract_tab_endpoint(url, item_id, ytcfg, fatal=fatal, default_client=default_client)
  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/extractor/youtube.py", line 4942, in _extract_tab_endpoint
    resolve_response = self._extract_response(
  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/extractor/youtube.py", line 860, in _extract_response
    for retry in self.RetryManager():
  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/utils.py", line 5921, in __iter__
    self.error_callback(self.error, self.attempt, self.retries)
  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/extractor/common.py", line 3882, in _error_or_warning
    RetryManager.report_retry(
  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/utils.py", line 5929, in report_retry
    raise e
  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/extractor/youtube.py", lin

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
@ID720-2:~/dv# yt-dlp -uV -f best -ciw -o "%(title)s.%(ext)s" -v "https://www.youtube.com/channel/@Rezilienza"
[debug] Command-line config: ['-uV', '-f', 'best', '-ciw', '-o', '%(title)s.%(ext)s', '-v', 'https://www.youtube.com/channel/@Rezilienza']
Type account password and press [Return]: 
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.11.11 [8b64402] (pip)
[debug] Python 3.8.10 (CPython x86_64 64bit) - Linux-5.4.0-131-generic-x86_64-with-glibc2.29 (OpenSSL 1.1.1f  31 Mar 2020, glibc 2.31)
[debug] exe versions: ffmpeg 4.2.7, ffprobe 4.2.7, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.16.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.46.0, pyxattr-0.6.1, secretstorage-2.3.1, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
WARNING: "-f best" selects the best pre-merged format which is often not the best option.
         To let yt-dlp download and merge the best available formats, simply do not pass any format selection.
         If you know what you are doing and want only the best pre-merged format, use "-f b" instead to suppress this warning
[debug] Loaded 1723 extractors
WARNING: [youtube:tab] Login with password is not supported for this website. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies
[debug] [youtube:tab] Extracting URL: https://www.youtube.com/channel/@Rezilienza
[youtube:tab] @Rezilienza: Downloading webpage
```

**Comment by coletdjnz** [comment]
That's not a valid YouTube url

**Comment by Evernow** [comment]
Indeed that's not a valid URL.
