### ISSUE TITLE
Time based options readme is misleading.

### ISSUE THREAD

**Issue by Shituation** [yt-dlp/yt-dlp#5774]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.11.11** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

This is in the readme:
```
--date DATE                     Download only videos uploaded on this date.
                                The date can be "YYYYMMDD" or in the format 
                                [now|today|yesterday][-N[day|week|month|year]].
                                E.g. --date today-2weeks
```

This is real life:
![2](https://user-images.githubusercontent.com/43975882/206908369-2108f5e6-c665-4046-9ada-968a0d0569de.jpg)

The readme should explain a little more what this option does exactly. By reading the actual readme, I thought ` --date today-2weeks` was a range <<today and all videos until 2 weeks back in time>> its misleading. Readme should make explicit that we are not talking about ranges here. The example ` --date today-2weeks` is misleading since people can think its a range and not actually "video from today and a video from exactly 2 weeks back (<today> - 14 days backwards).

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
C:\Youtube-dlp>"C:\Youtube-dlp\yt-dlp.exe" -vU -x -4 --external-downloader aria2c --playlist-end 10 --restrict-filenames --match-filter "title*='XXXXXXXXXXXXXX'" --date today-2weeks --audio-format mp3 -o "E:\XXXXXXXXX\XXXXXXXXX\%(title)s.%(ext)s" "https://www.youtube.com/c/XXXXXXXXXXXXXX/videos"
[debug] Command-line config: ['-vU', '-x', '-4', '--external-downloader', 'aria2c', '--playlist-end', '10', '--restrict-filenames', '--match-filter', "title*='XXXXXXXXXXXXX'", '--date', 'today-2weeks', '--audio-format', 'mp3', '-o', 'E:\\XXXXXXXXXXX\\XXXXXX\\%(title)s.%(ext)s', 'https://www.youtube.com/c/XXXXXXXXXXXXX/videos']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.11.11 [8b64402] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19044-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 4.3.1-2020-11-08-full_build-www.gyan.dev, ffprobe 4.3.1-2020-11-08-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1723 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.11.11, Current version: 2022.11.11
yt-dlp is up to date (2022.11.11)
[debug] [youtube:tab] Extracting URL: https://www.youtube.com/c/XXXXXXXXX/videos
[youtube:tab] XXXXXXXXXX/videos: Downloading webpage
[debug] [youtube:tab] Selected tab: 'videos' (videos), Requested tab: 'videos'
[download] Downloading playlist: XXXXXXXXXXXXXXX - Videos
[youtube:tab] Playlist XXXXXXXXXXXXX - Videos: Downloading 10 videos
[download] Downloading video 1 of 10
[debug] [youtube] Extracting URL: https://www.youtube.com/XXXXXXXXXXXXXXX
[youtube] e1BgbhVjo6Y: Downloading webpage
[youtube] e1BgbhVjo6Y: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[download] 2022-12-08 upload date is not in range 2022-11-27 - 2022-11-27
```

**Comment by pukkandan** [comment]
Any specific suggestions for the wording?

**Comment by pukkandan** [comment]
The formatting is not manually controlled, but auto-generated. Only the text can be changed

How about
```
    --date DATE                     Download only videos uploaded on this single date.
                                    The date can be "YYYYMMDD" or in the format 
                                    [now|today|yesterday][-N[day|week|month|year]].
                                    E.g. --date today-2weeks downloads only
                                    videos uploaded on the same day two weeks ago
```

**Comment by Shituation** [comment]
Looks good but I would insist on being explicit about not being a range because thats what I thought all this time and just found out when I needed to change my script. Sometimes its better to explain like to a 5yo, you know many people from around the world comes here and the language is a barrier too.

```
    --date DATE                     Download only videos uploaded on this single date. 
                                    Not a range.
                                    The date can be "YYYYMMDD" or in the format 
                                    [now|today|yesterday][-N[day|week|month|year]].
                                    E.g. --date today-2weeks downloads only
                                    videos uploaded on the same day two weeks ago.
```
