### ISSUE TITLE
How do I understand the special name "best" (just bv or ba, not best in the narrow sense)? That is, what is the basis for yt-dlp to determine which is the best?

### ISSUE THREAD

**Issue by DOSforever** [yt-dlp/yt-dlp#5776]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.11.11** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

如何理解 special name "best" (仅仅 bv 或 ba ，非狭义上的 best) ？即 yt-dlp 是以什么为判断依据来认为哪个是 best 的？
以 youtube 上某段视频为例

ID  EXT   RESOLUTION FPS CH |   FILESIZE  TBR PROTO | VCODEC         VBR ACODEC      ABR ASR MORE INFO
--------------------------------------------------------------------------------------------------------------
sb2 mhtml 48x27        0    |                 mhtml | images                                 storyboard
sb1 mhtml 60x45        0    |                 mhtml | images                                 storyboard
sb0 mhtml 120x90       0    |                 mhtml | images                                 storyboard
139 m4a   audio only      2 |    3.82MiB  49k https | audio only         mp4a.40.5   49k 22k low, m4a_dash
249 webm  audio only      2 |    3.84MiB  49k https | audio only         opus        49k 48k low, webm_dash
250 webm  audio only      2 |    4.21MiB  54k https | audio only         opus        54k 48k low, webm_dash
**_140 m4a   audio only      2 |   10.14MiB 129k https | audio only         mp4a.40.2  129k 44k medium, m4a_dash_**
**_251 webm  audio only      2 |    8.85MiB 113k https | audio only         opus       113k 48k medium, webm_dash_**
17  3gp   176x144     12  1 |    3.53MiB  45k https | mp4v.20.3      45k mp4a.40.2    0k 22k 144p
394 mp4   192x144     30    |    1.52MiB  19k https | av01.0.00M.08  19k video only          144p, mp4_dash
160 mp4   192x144     30    |  853.79KiB  11k https | avc1.4d400c    11k video only          144p, mp4_dash
278 webm  192x144     30    |    1.51MiB  19k https | vp9            19k video only          144p, webm_dash
395 mp4   320x240     30    |    2.17MiB  28k https | av01.0.00M.08  28k video only          240p, mp4_dash
133 mp4   320x240     30    |    1.23MiB  16k https | avc1.4d400d    16k video only          240p, mp4_dash
242 webm  320x240     30    |    2.31MiB  30k https | vp9            30k video only          240p, webm_dash
396 mp4   480x360     30    |    3.28MiB  42k https | av01.0.01M.08  42k video only          360p, mp4_dash
134 mp4   480x360     30    |    2.21MiB  28k https | avc1.4d401e    28k video only          360p, mp4_dash
18  mp4   480x360     30  2 | ~ 12.60MiB 157k https | avc1.42001E   157k mp4a.40.2    0k 44k 360p
243 webm  480x360     30    |    3.74MiB  48k https | vp9            48k video only          360p, webm_dash
397 mp4   640x480     30    |    4.96MiB  63k https | av01.0.04M.08  63k video only          480p, mp4_dash
135 mp4   640x480     30    |    3.49MiB  45k https | avc1.4d401e    45k video only          480p, mp4_dash
244 webm  640x480     30    |    6.01MiB  77k https | vp9            77k video only          480p, webm_dash
22  mp4   960x720     30  2 | ~ 16.40MiB 204k https | avc1.64001F   204k mp4a.40.2    0k 44k 720p
398 mp4   960x720     30    |    8.41MiB 107k https | av01.0.05M.08 107k video only          720p, mp4_dash
136 mp4   960x720     30    |    5.91MiB  75k https | avc1.4d401f    75k video only          720p, mp4_dash
247 webm  960x720     30    |   11.56MiB 148k https | vp9           148k video only          720p, webm_dash
399 mp4   1440x1080   30    |   19.63MiB 251k https | av01.0.08M.08 251k video only          1080p, mp4_dash
137 mp4   1440x1080   30    |    9.77MiB 125k https | avc1.640028   125k video only          1080p, mp4_dash
**_248 webm  1440x1080   30    |   22.77MiB 291k https | vp9           291k video only          1080p, webm_dash_**

以单独的视频流和音频流来看，我认为 ID248 和 ID140 分别为最好的视频流和音频流，但是如果使用

`> yt-dlp -f ba,bv https://www.youtube.com/watch?v=jWU0WdMJ2Kw`
或
`> yt-dlp -f ba+bv https://www.youtube.com/watch?v=jWU0WdMJ2Kw`

它所下载的是 248 和 251，对于视频流我们的看法一致，但对音频流为什么它会认为 TBR 为 113k 的 251 的音频质量好于 TBR 为 129k 的 140 ？

我看了下默认的 Sorting Formats ，对音频编码默认的排序标准是
Audio Codec (flac/alac > wav/aiff > opus > vorbis > aac > mp4a > mp3 ac4 > > eac3 > ac3 > dts > other)
也就是说 yt-dlp 先按照此编码排序格式查找，在先找到的编码格式中再查找其中最好的一个，哪怕有其它编码格式的质量确实比那个更好，是吗？
我想，在差不多 TBR 的情况下，或许更好的编码格式意味着更好的质量，但如果 TBR 在相差很大的情况下，到底哪个更好呢？ yt-dlp 该如何判断？

---------------------------------------------------------------------------------------------------------------------------------------------

How do I understand the special name "best" (just bv or ba, not best in the narrow sense)? That is, what is the basis for yt-dlp to determine which is the best?

Take a video on youtube as an example

ID  EXT   RESOLUTION FPS CH |   FILESIZE  TBR PROTO | VCODEC         VBR ACODEC      ABR ASR MORE INFO
--------------------------------------------------------------------------------------------------------------
sb2 mhtml 48x27        0    |                 mhtml | images                                 storyboard
sb1 mhtml 60x45        0    |                 mhtml | images                                 storyboard
sb0 mhtml 120x90       0    |                 mhtml | images                                 storyboard
139 m4a   audio only      2 |    3.82MiB  49k https | audio only         mp4a.40.5   49k 22k low, m4a_dash
249 webm  audio only      2 |    3.84MiB  49k https | audio only         opus        49k 48k low, webm_dash
250 webm  audio only      2 |    4.21MiB  54k https | audio only         opus        54k 48k low, webm_dash
**_140 m4a   audio only      2 |   10.14MiB 129k https | audio only         mp4a.40.2  129k 44k medium, m4a_dash_**
**_251 webm  audio only      2 |    8.85MiB 113k https | audio only         opus       113k 48k medium, webm_dash_**
17  3gp   176x144     12  1 |    3.53MiB  45k https | mp4v.20.3      45k mp4a.40.2    0k 22k 144p
394 mp4   192x144     30    |    1.52MiB  19k https | av01.0.00M.08  19k video only          144p, mp4_dash
160 mp4   192x144     30    |  853.79KiB  11k https | avc1.4d400c    11k video only          144p, mp4_dash
278 webm  192x144     30    |    1.51MiB  19k https | vp9            19k video only          144p, webm_dash
395 mp4   320x240     30    |    2.17MiB  28k https | av01.0.00M.08  28k video only          240p, mp4_dash
133 mp4   320x240     30    |    1.23MiB  16k https | avc1.4d400d    16k video only          240p, mp4_dash
242 webm  320x240     30    |    2.31MiB  30k https | vp9            30k video only          240p, webm_dash
396 mp4   480x360     30    |    3.28MiB  42k https | av01.0.01M.08  42k video only          360p, mp4_dash
134 mp4   480x360     30    |    2.21MiB  28k https | avc1.4d401e    28k video only          360p, mp4_dash
18  mp4   480x360     30  2 | ~ 12.60MiB 157k https | avc1.42001E   157k mp4a.40.2    0k 44k 360p
243 webm  480x360     30    |    3.74MiB  48k https | vp9            48k video only          360p, webm_dash
397 mp4   640x480     30    |    4.96MiB  63k https | av01.0.04M.08  63k video only          480p, mp4_dash
135 mp4   640x480     30    |    3.49MiB  45k https | avc1.4d401e    45k video only          480p, mp4_dash
244 webm  640x480     30    |    6.01MiB  77k https | vp9            77k video only          480p, webm_dash
22  mp4   960x720     30  2 | ~ 16.40MiB 204k https | avc1.64001F   204k mp4a.40.2    0k 44k 720p
398 mp4   960x720     30    |    8.41MiB 107k https | av01.0.05M.08 107k video only          720p, mp4_dash
136 mp4   960x720     30    |    5.91MiB  75k https | avc1.4d401f    75k video only          720p, mp4_dash
247 webm  960x720     30    |   11.56MiB 148k https | vp9           148k video only          720p, webm_dash
399 mp4   1440x1080   30    |   19.63MiB 251k https | av01.0.08M.08 251k video only          1080p, mp4_dash
137 mp4   1440x1080   30    |    9.77MiB 125k https | avc1.640028   125k video only          1080p, mp4_dash
**_248 webm  1440x1080   30    |   22.77MiB 291k https | vp9           291k video only          1080p, webm_dash_**

In terms of separate video and audio streams, I think ID248 and ID140 are the best video and audio streams, respectively, but if you use

`> yt-dlp -f ba,bv https://www.youtube.com/watch?v=jWU0WdMJ2Kw`
or
`> yt-dlp -f ba+bv https://www.youtube.com/watch?v=jWU0WdMJ2Kw`

It is downloading 248 and 251, we are in agreement for video streams, but for audio streams why would it consider the audio quality of 251 with a TBR of 113k better than 140 with a TBR of 129k?

I looked at the default Sorting Formats and the default sorting criteria for audio codecs is
Audio Codec (flac/alac > wav/aiff > opus > vorbis > aac > mp4a > mp3 ac4 > > eac3 > ac3 > dts > other)
That means yt-dlp looks for this encoding format first, and then looks for the best one among the ones found first, even if there are other encoding formats that do have better quality than that one, right?
I think, in the case of similar TBR, maybe better encoding format means better quality, but if the TBR is very different, which one is better? How should yt-dlp determine that?

Translated with www.DeepL.com/Translator (free version)

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['--proxy', 'https://127.0.0.1:8580', '-svUf', 'bv,ba', 'https://www.youtube.com/watch?v=jWU0WdMJ2Kw']
[debug] Portable config "D:\X64\yt-dlp\yt-dlp.conf": ['--progress', '--write-link', '--write-subs', '--write-auto-subs', '--sub-langs', 'en-en,zh-hans-en', '--write-description', '--buffer-size', '4M', '--ffmpeg-location', 'D:/X64/ffmpeg-N-109398-g7e8b539389-win64-gpl-shared/bin']
[debug] Encodings: locale cp936, fs utf-8, pref cp936, out gbk (No VT), error gbk (No VT), screen gbk (No VT)
[debug] yt-dlp version 2022.11.11 [8b64402] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-7-6.1.7601-SP1 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-109398-g7e8b539389-20221210 (setts), ffprobe N-109398-g7e8b539389-20221210
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {'http': 'https://127.0.0.1:8580', 'https': 'https://127.0.0.1:8580'}
[debug] Loaded 1723 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.11.11, Current version: 2022.11.11
yt-dlp is up to date (2022.11.11)
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=jWU0WdMJ2Kw
[youtube] jWU0WdMJ2Kw: Downloading webpage
[youtube] jWU0WdMJ2Kw: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[info] jWU0WdMJ2Kw: Downloading subtitles: en-en, zh-Hans-en
[info] jWU0WdMJ2Kw: Downloading 2 format(s): 248, 251
```

**Comment by pukkandan** [comment]
See my answer to https://github.com/yt-dlp/yt-dlp/issues/1232 and many similar questions

**Comment by DOSforever** [comment]
> See my answer to #1232 and many similar questions

Thanks for your reply.
