### ISSUE TITLE
[Question] Why does this script fail to download multiple videos?

### ISSUE THREAD

**Issue by skwolvie** [yt-dlp/yt-dlp#578]
I have a list of 1000 URLs that I'd like to download. My internet speed is 400 MBPS. But the video was downloading at slower rates. I utilised threading to speed things up.

My Script:
```
import os
import pandas as pd
from threading import Thread

df= pd.read_csv('../metadata/V4_CEOs_Matched_filter_1030.csv')
urls=df['URL'].tolist()
len(urls)

urls1=urls[:100]
urls2=urls[100:200]
urls3=urls[200:300]
urls4=urls[300:400]
urls5=urls[400:500]
urls6=urls[500:600]
urls7=urls[600:700]
urls8=urls[700:800]
urls9=urls[800:900]
urls10=urls[900:]

del urls
len(urls1)

def thread_downloader(urls, threadname):
    for i in urls:
        print(threadname)
        os.system("yt-dlp {0} --extractor-args youtube:player_client=android --throttled-rate 1000K".format(i))

t0 = Thread(target=thread_downloader, args=(urls1, '1')) 
t1 = Thread(target=thread_downloader, args=(urls2, '2')) 
t2 = Thread(target=thread_downloader, args=(urls3, '3')) 
t3 = Thread(target=thread_downloader, args=(urls4, '4'))
t4 = Thread(target=thread_downloader, args=(urls5, '5'))
t5 = Thread(target=thread_downloader, args=(urls6, '6')) 
t6 = Thread(target=thread_downloader, args=(urls7, '7')) 
t7 = Thread(target=thread_downloader, args=(urls8, '8')) 
t8 = Thread(target=thread_downloader, args=(urls9, '9'))
t9 = Thread(target=thread_downloader, args=(urls10, '10'))

t0.start()
t1.start()
t2.start()
t3.start()
t4.start()
t5.start()
t6.start()
t7.start()
t8.start()
t9.start()


t0.join()
t1.join()
t2.join()
t3.join()
t4.join()
t5.join()
t6.join()
t7.join()
t8.join()
t9.join()
```
Most URLs fail to download. I'm running this script on a Jupiter notebook. it is not printing out any errors other than the thread name. However, when the script is finished running there shd be 1030 videos but I have only 740 videos. 
The URLs do not have any adult content nor are they private.

**Comment by pukkandan** [comment]
You haven't given any info that I can use to help you. Show the verbose output of the yt-dlp runs that fail

**Comment by Ashish0804** [comment]
Could be bcoz of hitting limit on the api and therefore some videos error out.
This is the wrong way of doing it anyways.

**Comment by skwolvie** [comment]
@pukkandan I am running it as a .py script now to handle the missed videos. If they fail again, i will have logs that i can share.

Is there any possible way to print the logs when i run the script on jupyter notebook?

**Comment by skwolvie** [comment]
Looks like all the videos that was missed in the first run are getting downloaded now. Im refreshing thr folder and seeing new videos.

**Comment by skwolvie** [comment]
@Ashish0804 can you please elaborate on why this is the wrong way of doing things? Thanks

**Comment by 89z** [comment]
This is a blatant and obvious abuse of not only YT-DLP, but YouTube TOS as well. Anyone reading this thread should just downvote the original post and move on.

**Comment by pukkandan** [comment]
Closed due to inactivity
