### ISSUE TITLE
yt-dlp error: urlopen error _ssl.c:1106

### ISSUE THREAD

**Issue by carmerlun** [yt-dlp/yt-dlp#5785]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.11.11** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Spain

### Provide a description that is worded well enough to be understood

I get an error when trying to download youtube videos using yt-dlp. I don't have any issues when downloading videos from other websites.

The error message is: Got error: urlopen error _ssl.c:1106: The handshake operation timed out.

In case this info could be of any help, my operating system is Debian 11 Bullseye, linux kernel 5.10.0-19-amd64 x86_64.

Any comments would be much appreciated.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line  config: ['-vU', 'https://www.youtube.com/watch?v=zpzdgmqIHOQ']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug]  yt-dlp version  2022.11.11 [8b644025b] (debian*)
[debug] Python  3.9.2 (CPython x86_64 64bit) - Linux-5.10.0-19-amd64-x86_64-with-glibc2.31 (OpenSSL 1.1.1n  15 Mar 2022, glibc 2.31)
[debug] exe versions: ffmpeg 4.3.5-0, ffprobe 4.3.5-0, rtmpdump 2.4
[debug] Optional  libraries: Cryptodome-3.9.7, brotli-1.0.9, certifi-2022.09.24, mutagen-1.45.1, pyxattr-0.7.2, sqlite3-2.6.0, websockets-8.1
[debug] Proxy  map: {}
[debug] Loaded 1723 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version:  2022.11.11, Current version:  2022.11.11
yt-dlp is up to date (2022.11.11)
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=zpzdgmqIHOQ
[youtube] zpzdgmqIHOQ:  Downloading webpage
[youtube] zpzdgmqIHOQ:  Downloading android player  API JSON
[debug] Sort order given by extractor:  quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by:  hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang,  proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best  
[info] zpzdgmqIHOQ: Downloading 1 format(s): 244+251 
[debug] Invoking  http downloader on "https://rr4---sn-h5nhv8pa-n89s.googlevideo.com/videoplayback?expire=1670865979&ei=2w-XY8zrG4X5WqewsOgP&ip=214.195.150.169&id=o-AFM_ms6Yx81q0GBjLOYRHTLO3jNhVeVT-LpHCj2Ebw_c&itag=244&source=youtube&requiressl=yes&mh=BJ&mm=31%2C29&mn=sn-h5nhv8pa-n89s%2Csn-h5q7knee&ms=au%2Crdu&mv=m&mvi=4&pl=20&initcwndbps=886250&spc=SFxXNgTjxI3QsRwfN3V6FlczSa929_I&vprv=1&svpuc=1&mime=video%2Fwebm&gir=yes&clen=12766009&dur=240.906&lmt=1641465865081337&mt=1670844298&fvip=1&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=4532434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt& sig=AOq0QJ8wRAIgd8PfFb5qRjLQ8G8439UGYUAl0KGiuLVjqap4BK1Us8ECIGIfBfhIuc0hcguvC1d6Sn-dfywwAUYgM6H3S5J7A6i4& lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhAPuZRz5GBw4adN6p-wqKbHOuo2SicWr-36W8WNACrLyPAiAN0Sd9riY4QCLnLTELoR7dsbEikWMrbCyTFn4Zl1nddg%3D%3D"
[download]  Got error: <urlopen error _ssl.c:1106:  The handshake operation timed out>.  Retrying (1/10)... 
```

**Comment by pukkandan** [comment]
Does this happen repeatedly, or only once? It was likely a transient network issue on your side

> ```shell
> [debug] Invoking http downloader on "https://rr4---sn-h5nhv8pa-n89s.googlevideo.com/videoplayback?expire=1670865979&ei=2w-XY8zrG4X5WqewsOgP&ip=213.194.160.163&id=o-AFM_ms6Yx81q0GBjLOYRHTLO3jNhVeVT-LpHCj2Ebw_c&itag=244&source=youtube&requiressl=yes&mh=BJ&mm=31%2C29&mn=sn-h5nhv8pa-n89s%2Csn-h5q7knee&ms=au%2Crdu&mv=m&mvi=4&pl=20&initcwndbps=886250&spc=SFxXNgTjxI3QsRwfN3V6FlczSa929_I&vprv=1&svpuc=1&mime=video%2Fwebm&gir=yes&clen=12766009&dur=240.906&lmt=1641465865081337&mt=1670844298&fvip=1&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=4532434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRAIgd8PfFb5qRjLQ8G8439UGYUAl0KGiuLVjqap4BK1Us8ECIGIfBfhIuc0hcguvC1d6Sn-dfywwAUYgM6H3S5J7A6i4&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhAPuZRz5GBw4adN6p-wqKbHOuo2SicWr-36W8WNACrLyPAiAN0Sd9riY4QCLnLTELoR7dsbEikWMrbCyTFn4Zl1nddg%3D%3D"
> ```

This link opens for me in browser, indicating there is no error in yt-dlp's extraction

**Comment by carmerlun** [comment]
Thank you @pukkandan for your reply.
Yes, I noticed this problem yesterday and still persists on the same videos. I have been testing other videos on youtube and seems kind of random, with no issue with some videos, but continuosly encountering the same error message with other videos.

**Comment by carmerlun** [comment]
When I try to open the link above my browser doesn't refuses to open it (message: The connection has timed out).

This is the output of: yt-dlp -vU --check-formats:

[debug] Command-line config: ['-vU', '--check-formats', 'https://www.youtube.com/watch?v=zpzdgmqIHOQ']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.11.11 [8b644025b] (debian*)
[debug] Python 3.9.2 (CPython x86_64 64bit) - Linux-5.10.0-19-amd64-x86_64-with-glibc2.31 (OpenSSL 1.1.1n  15 Mar 2022, glibc 2.31)
[debug] exe versions: ffmpeg 4.3.5-0, ffprobe 4.3.5-0, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.9.7, brotli-1.0.9, certifi-2022.09.24, mutagen-1.45.1, pyxattr-0.7.2, sqlite3-2.6.0, websockets-8.1
[debug] Proxy map: {}
[debug] Loaded 1723 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.11.11, Current version: 2022.11.11
yt-dlp is up to date (2022.11.11)
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=zpzdgmqIHOQ
[youtube] zpzdgmqIHOQ: Downloading webpage
[youtube] zpzdgmqIHOQ: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] Testing format 244
[download] Got error: <urlopen error _ssl.c:1106: The handshake operation timed out>
  File "/usr/bin/yt-dlp", line 33, in <module>
    sys.exit(load_entry_point('yt-dlp==2022.11.11', 'console_scripts', 'yt-dlp')())
  File "/usr/lib/python3/dist-packages/yt_dlp/__init__.py", line 968, in main
    _exit(*variadic(_real_main(argv)))
  File "/usr/lib/python3/dist-packages/yt_dlp/__init__.py", line 958, in _real_main
    return ydl.download(all_urls)
  File "/usr/lib/python3/dist-packages/yt_dlp/YoutubeDL.py", line 3322, in download
    self.__download_wrapper(self.extract_info)(
  File "/usr/lib/python3/dist-packages/yt_dlp/YoutubeDL.py", line 3297, in wrapper
    res = func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/yt_dlp/YoutubeDL.py", line 1474, in extract_info
    return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
  File "/usr/lib/python3/dist-packages/yt_dlp/YoutubeDL.py", line 1485, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/yt_dlp/YoutubeDL.py", line 1582, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/lib/python3/dist-packages/yt_dlp/YoutubeDL.py", line 1641, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/usr/lib/python3/dist-packages/yt_dlp/YoutubeDL.py", line 2685, in process_video_result
    formats_to_download = list(format_selector({
  File "/usr/lib/python3/dist-packages/yt_dlp/YoutubeDL.py", line 2201, in selector_function
    yield from f(ctx)
  File "/usr/lib/python3/dist-packages/yt_dlp/YoutubeDL.py", line 2300, in final_selector
    return selector_function(ctx_copy)
  File "/usr/lib/python3/dist-packages/yt_dlp/YoutubeDL.py", line 2212, in selector_function
    picked_formats = list(f(ctx))
  File "/usr/lib/python3/dist-packages/yt_dlp/YoutubeDL.py", line 2221, in selector_function
    for pair in itertools.product(selector_1(ctx), selector_2(ctx)):
  File "/usr/lib/python3/dist-packages/yt_dlp/YoutubeDL.py", line 2290, in selector_function
    yield matches[format_idx - 1]
  File "/usr/lib/python3/dist-packages/yt_dlp/utils.py", line 2800, in __getitem__
    self._cache.extend(itertools.islice(self._iterable, n))
  File "/usr/lib/python3/dist-packages/yt_dlp/YoutubeDL.py", line 2193, in _check_formats
    yield from self._check_formats(formats)
  File "/usr/lib/python3/dist-packages/yt_dlp/YoutubeDL.py", line 1964, in _check_formats
    success, _ = self.dl(temp_file.name, f, test=True)
  File "/usr/lib/python3/dist-packages/yt_dlp/YoutubeDL.py", line 2924, in dl
    return fd.download(name, new_info, subtitle)
  File "/usr/lib/python3/dist-packages/yt_dlp/downloader/common.py", line 446, in download
    ret = self.real_download(filename, info_dict)
  File "/usr/lib/python3/dist-packages/yt_dlp/downloader/http.py", line 369, in real_download
    for retry in RetryManager(self.params.get('retries'), self.report_retry):
  File "/usr/lib/python3/dist-packages/yt_dlp/utils.py", line 5921, in __iter__
    self.error_callback(self.error, self.attempt, self.retries)
  File "/usr/lib/python3/dist-packages/yt_dlp/downloader/common.py", line 391, in report_retry
    RetryManager.report_retry(
  File "/usr/lib/python3/dist-packages/yt_dlp/utils.py", line 5928, in report_retry
    return error(f'{e}. Giving up after {count - 1} retries') if count > 1 else error(str(e))
  File "/usr/lib/python3/dist-packages/yt_dlp/downloader/common.py", line 394, in <lambda>
    error=IDENTITY if not fatal else lambda e: self.report_error(f'\r[download] Got error: {e}'),
  File "/usr/lib/python3/dist-packages/yt_dlp/YoutubeDL.py", line 1004, in report_error
    self.trouble(f'{self._format_err("ERROR:", self.Styles.ERROR)} {message}', *args, **kwargs)
  File "/usr/lib/python3/dist-packages/yt_dlp/YoutubeDL.py", line 933, in trouble
    tb_data = traceback.format_list(traceback.extract_stack())
[info] Unable to download format 244. Skipping...
[info] Testing format 135

(I stop it there)

Thanks for any comments.

**Comment by pukkandan** [comment]
Do you have any firewall etc that may be blocking the server? You can also check with a VPN to make sure

**Comment by carmerlun** [comment]
Thank you @pukkandan. 
I've checked if there could be a firewall issue on my side. For this, I've entered my router settings by typing 192.168.1.1 on a browser. Firewall is ON, but set to LOW (three levels allowed: low; medium; high), this way allowing all connections LAN -> WAN and WAN -> LAN. 
I have also tried to set it OFF. However, the yt-dlp issue still persists. 
Lastly, I've connected through VPN and now the issue magically disappears!!

Any ideas why this might happen? Is this a firewall issue? How could I set my firewall to allow yt-dlp to download youtube videos. It's strange that I only can download some videos. I've checked that there are videos that I can download and others that I can't, even when they are hosted by the same youtube channel. 

I've used youtube-dl, first, and then yt-dlp for quite a long time and now is the first time I encountered this issue.

Any comments would be much appreciated.

**Comment by pukkandan** [comment]
> https://rr4---sn-h5nhv8pa-n89s.googlevideo.com

yt-dlp is unable to connect to this server (and possibly others) for whatever reason. It could be because of firewall, pihole, DNS, ISP, or any number of other things sitting b/w yt-dlp and the server

Also try with `-4`/`-6` in case the issue only affects one of them
