### ISSUE TITLE
Security question. Showing IP in the "yt-dlp -vU" output.

### ISSUE THREAD

**Issue by carmerlun** [yt-dlp/yt-dlp#5787]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.11.11** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

When having an issue with yt-dlp users looking for help here are asked to post the output using yt-dlp -vU. I notice that the personal IP of a machine is included in the "invoking" line of a youtube video link. Dummy example: 
[debug] Invoking  http downloader on "https://rr4---sn-h5nhv8pa-n69s.googlevideo.com/videoplayback?expire=1670865979&ei=2w-XY8zrG4X5WqewsOgP&ip=214.195.150.143.....

I would like to know if there is any security risk by showing one's IP in the output. 
Thanks in advance.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
Dummy example: 
[debug] Invoking  http downloader on "https://rr4---sn-h5nhv8pa-n69s.googlevideo.com/videoplayback?expire=1670865979&ei=2w-XY8zrG4X5WqewsOgP&ip=214.195.150.143.....
```

**Comment by bashonly** [comment]
It's certainly a privacy concern (e.g. if you don't want your github account publicly linked to your real world location/identity), but I don't think it poses that much of a security risk unless you have reason to believe somebody would want to specifically target you (or already is targeting you). 

It is perfectly acceptable to redact your IP/other PII from logs if it's not pertinent to your issue.

**Comment by carmerlun** [comment]
Thank you very much @bashonly  for the clarification.
