### ISSUE TITLE
Download progress bar update rate of 60+ Hz is too fast

### ISSUE THREAD

**Issue by Safari77** [yt-dlp/yt-dlp#5789]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.11.11** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Progress update rate of 60 Hz+ is too fast, cannot really see the real rate.
Maybe 1 Hz would be a better idea.
When I hold down enter while downloading, I see these updates in 0.33 seconds:

```
[download]  75.6% of    3.31GiB at   74.74MiB/s ETA 00:10
[download]  75.7% of    3.31GiB at   74.11MiB/s ETA 00:10
[download]  75.7% of    3.31GiB at   71.94MiB/s ETA 00:11
[download]  75.9% of    3.31GiB at   74.00MiB/s ETA 00:10
[download]  75.9% of    3.31GiB at   90.91MiB/s ETA 00:08
[download]  76.0% of    3.31GiB at  103.75MiB/s ETA 00:07
[download]  76.2% of    3.31GiB at  106.62MiB/s ETA 00:07
[download]  76.2% of    3.31GiB at   88.27MiB/s ETA 00:08
[download]  76.3% of    3.31GiB at  103.42MiB/s ETA 00:07
[download]  76.4% of    3.31GiB at  106.14MiB/s ETA 00:07
```

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
N/A
```

**Comment by flashdagger** [comment]
This reminds me of my PR #3345. The conversation shows that this is strongly opinionated. Maybe a configuration issue?

**Comment by Grub4K** [comment]
This could also easily be implemented in #5680. Interval updates and speed smoothing are things that could improve user experience and are very easy to put behind configuration (at least for that PR). What is the reason that the update interval should always be fixed?

**Comment by pukkandan** [comment]
A moving average on the speed can be done.

But changing default update rate is undesirable, especially when used with `--progress-template`. The option was added mainly to allow similar behavior to `progress_hooks` from non-python programs; so the template should print on every hook. But if there is sufficient use-case for it, we could discuss adding it as an argument.

**Comment by flashdagger** [comment]
> But changing default update rate is undesirable, especially when used with `--progress-template`.

The update rate can be left untouched. When I remember correctly, the solution was to calculate and return a new download rate every x milliseconds, no matter at which rate the function is called...

**Comment by pukkandan** [comment]
that is fine, but not what OP wants as far as I understand

**Comment by pukkandan** [comment]
I am just asking whether there is real use-case for it, or simply smoothing the speed is sufficient

**Comment by ehoogeveen-medweb** [comment]
Limiting the output rate might also be good for performance on slow terminals like the default Windows terminal (where I previously saw performance issues with the progress display for reading browser cookies). That might become less of an issue as Microsoft changes over to Windows Terminal, though IIRC that also had performance issues (but I think it's getting better).

**Comment by NewUserHa** [comment]
Windows terminal has GPU-Accelerated too, and it's faster than alacritty (A cross-platform, OpenGL terminal emulator.) on some benchmarks.
So the update frequency of the progress may be fine. For windows cmd, printing only one line at 60hz may be fine too.

**Comment by Grub4K** [comment]
This option is getting added in #5680 soon, where we can get it quite easily through `_OutputGroup`. My laptop is slow and VSCode terminal handles fast updates poorly on it, so thats one usecase at least for me. Also output rework is able to print multiple status lines so it might have heavier load. Currently unused but in the future maybe.

**Comment by chylex** [comment]
I'm using `--newline` because I'm piping yt-dlp output, right now it's printing out 100 lines of progress in a few seconds, so a way to limit the frequency would be helpful in this case too.

**Comment by stefanct** [comment]
It's totally wasting CPU cycles better spent otherwise that no one really appreciates anyway. Who is looking at such progress stats for a prolonged time? May I suggest touching some grass instead? :P
FWIW, I'd rather disable it because of that but I am currently downloading videos that take more than an hour to download and I'd like to have at least some indication on the progress... If I could configure it, I'd set it to about every every 5 seconds in most use cases.

**Comment by Jules-A** [comment]
I think that was coming with the output template rework grub4k was working on or at least he implied it. It really shouldn't be using much CPU even on a potato and would pale in comparison to the actual merging of fragments. It's definitely updates too fast though and having a configurable speed was something I wanted to implement but was waiting on Grub4k's PR.

**Comment by NewUserHa** [comment]
what about https://github.com/yt-dlp/yt-dlp/pull/8444 first for closing this issue, since the above PRs with big changes are still waiting for merging

**Comment by Jules-A** [comment]
> what about #8444 first for closing this issue, since the above PRs with big changes are still waiting for merging

Nah, Grub said he wanted the hook unchanged, besides if it's going to be implemented it really needs to be user configurable.

**Comment by NewUserHa** [comment]
Because it also seems that the #5680 PR will not be merged in any soon and there are still ppl keep posting new comments in the #5789 issue.
Therefore this is just a temporary solution if #5680 still needs more wait to close that issue.

The update rate progress is just a form of a simple UI, the update frequence should be at least <= 1s.
Who want to configure the update rate of the prograss bar of any UI really?

**Comment by m4heshd** [comment]
This would be so useful when embedding yt-dlp and it actually does waste a ton of resources when the output is parsed. Even if we slow it down on the host application's side, it still has to consider and parse each line that comes through stdout.

**Comment by Grub4K** [comment]
Just as a side note, this is somewhat trivial to implement as a plugin; see [this gist](<https://gist.github.com/Grub4K/701d90c94a802cdc8367c41d18b0d502>)
