### ISSUE TITLE
Bilibili `unsupported format string passed to NoneType.__format__`

### ISSUE THREAD

**Issue by fee1-dead** [yt-dlp/yt-dlp#5797]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.11.11** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Provide a description that is worded well enough to be understood

yt-dlp consistently fails when the command below is run:

```
yt-dlp https://www.bilibili.com/video/BV1zL411t7oR --no-playlist
```

I have tested this from a server and from my computer. This worked for `yt-dlp` version `2022.10.04`, but latest `2022.11.11` fails.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['https://www.bilibili.com/video/BV1zL411t7oR', '--no-playlist', '-vU']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.11.11 [8b64402] (pip)
[debug] Python 3.10.8 (CPython x86_64 64bit) - Linux-6.0.9-x86_64-with-glibc2.35 (OpenSSL 3.0.7 1 Nov 2022, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1723 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.11.11, Current version: 2022.11.11
yt-dlp is up to date (2022.11.11)
[debug] [BiliBili] Extracting URL: https://www.bilibili.com/video/BV1zL411t7oR
[BiliBili] 1zL411t7oR: Downloading webpage
[BiliBili] BV1zL411t7oR: Extracting videos in anthology
[BiliBili] Downloading just the video BV1zL411t7oR because of --no-playlist
ERROR: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "/nix/store/k0bqd3kkzyzwz012j2n9bh8lk05spvib-python3.10-yt-dlp-2022.11.11/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1485, in wrapper
    return func(self, *args, **kwargs)
  File "/nix/store/k0bqd3kkzyzwz012j2n9bh8lk05spvib-python3.10-yt-dlp-2022.11.11/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1561, in __extract_info
    ie_result = ie.extract(url)
  File "/nix/store/k0bqd3kkzyzwz012j2n9bh8lk05spvib-python3.10-yt-dlp-2022.11.11/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 674, in extract
    ie_result = self._real_extract(url)
  File "/nix/store/k0bqd3kkzyzwz012j2n9bh8lk05spvib-python3.10-yt-dlp-2022.11.11/lib/python3.10/site-packages/yt_dlp/extractor/bilibili.py", line 307, in _real_extract
    title += f' p{part_id:02d} {traverse_obj(page_list_json, ((part_id or 1) - 1, "part")) or ""}'
TypeError: unsupported format string passed to NoneType.__format__
```

**Comment by bashonly** [comment]
A quick fix would be to do this:
```diff
diff --git a/yt_dlp/extractor/bilibili.py b/yt_dlp/extractor/bilibili.py
index bc0424194..bec57effe 100644
--- a/yt_dlp/extractor/bilibili.py
+++ b/yt_dlp/extractor/bilibili.py
@@ -296,14 +296,14 @@ def _real_extract(self, url):
             'data', expected_type=list) or []
         is_anthology = len(page_list_json) > 1
 
-        part_id = int_or_none(parse_qs(url).get('p', [None])[-1])
+        part_id = int_or_none(parse_qs(url).get('p', [None])[-1]) or 1
         if is_anthology and not part_id and self._yes_playlist(video_id, video_id):
             return self.playlist_from_matches(
                 page_list_json, video_id, title, ie=BiliBiliIE,
                 getter=lambda entry: f'https://www.bilibili.com/video/{video_id}?p={entry["page"]}')
 
         if is_anthology:
-            title += f' p{part_id:02d} {traverse_obj(page_list_json, ((part_id or 1) - 1, "part")) or ""}'
+            title += f' p{part_id:02d} {traverse_obj(page_list_json, ((part_id) - 1, "part")) or ""}'
 
         aid = video_data.get('aid')
         old_video_id = format_field(aid, None, f'%s_part{part_id or 1}')
```

But presumably a proper patch would involve finding a better way to determine the `part_id` than relying on the query params, since they don't exist in the case of this example URL. And/or finding a better way to set the title without such a busy f-string
