### ISSUE TITLE
Nebula: Styled VTT subtitles results in parse error

### ISSUE THREAD

**Issue by DHandspikerWade** [yt-dlp/yt-dlp#5804]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.11.11** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Canada and US

### Provide a description that is worded well enough to be understood

When downloading videos from Nebula, if they have stylized subtitles the download will fail trying to parse the style block. Videos without the added styles downlaod without issue. Downloading the subtitle separately outside of YT-DLP will correctly play in VLC. 

Nebula seems to be providing the same subtitle file multiple times in the M3U8.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--write-subs', '--username', 'PRIVATE', '--password', 'PRIVATE', 'https://nebula.tv/videos/jetlag-who-can-get-to-the-most-states-in-4-days']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.11.11 [8b64402] (zip)
[debug] Python 3.10.8 (CPython x86_64 64bit) - Linux-5.10.0-16-amd64-x86_64-with (OpenSSL 3.0.7 1 Nov 2022)
[debug] exe versions: ffmpeg 5.1.2 (setts), ffprobe 5.1.2
[debug] Optional libraries: sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Loaded 1723 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.11.11, Current version: 2022.11.11
yt-dlp is up to date (2022.11.11)
[Nebula] Logging in to Nebula with supplied credentials
[Nebula] Authorizing to Nebula
[Nebula] Retrieving Zype access token
[debug] [Nebula] Extracting URL: https://nebula.tv/videos/jetlag-who-can-get-to-the-most-states-in-4-days
[Nebula] jetlag-who-can-get-to-the-most-states-in-4-days: Fetching video meta data
WARNING: [Zype] Login with password is not supported for this website. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies
[debug] [Zype] Extracting URL: https://player.zype.com/embed/638e6ef340407a0001123307.html?access_token=9fRJA-MZT7477xExHxHKUles6W3b7sqBj_racOIsLuc
[Zype] 638e6ef340407a0001123307: Downloading JSON metadata
[Zype] 638e6ef340407a0001123307: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[info] 638e6ef340407a0001123307: Downloading subtitles: en
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 638e6ef340407a0001123307: Downloading 1 format(s): hls-25006
[info] Writing video subtitles to: Who Can Get To The Most States In 4 Days [638e6ef340407a0001123307].en.vtt
[debug] Invoking hlsnative downloader on "https://storage.googleapis.com/zype-subtitles-prod/5c182d06649f0f134a001703/638e6ef340407a0001123307/subtitles/en.m3u8"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 2
[download] Destination: Who Can Get To The Most States In 4 Days [638e6ef340407a0001123307].en.vtt
[download]  50.0% of ~ 183.71KiB at  602.86KiB/s ETA 00:00 (frag 1/2)ERROR: Parse error at position 135 (near 'Style:\r\n::cue(v[voic')
Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1485, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1582, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1694, in process_ie_result
    return self.process_ie_result(
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1641, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 2737, in process_video_result
    self.process_info(new_info)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 2983, in process_info
    sub_files = self._write_subtitles(info_dict, temp_filename)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3950, in _write_subtitles
    self.dl(sub_filename, sub_copy, subtitle=True)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 2924, in dl
    return fd.download(name, new_info, subtitle)
  File "/usr/local/bin/yt-dlp/yt_dlp/downloader/common.py", line 446, in download
    ret = self.real_download(filename, info_dict)
  File "/usr/local/bin/yt-dlp/yt_dlp/downloader/hls.py", line 351, in real_download
    self.download_and_append_fragments(
  File "/usr/local/bin/yt-dlp/yt_dlp/downloader/fragment.py", line 520, in download_and_append_fragments
    result = append_fragment(
  File "/usr/local/bin/yt-dlp/yt_dlp/downloader/fragment.py", line 479, in append_fragment
    self._append_fragment(ctx, pack_func(frag_content, frag_index))
  File "/usr/local/bin/yt-dlp/yt_dlp/downloader/hls.py", line 266, in pack_fragment
    for block in webvtt.parse_fragment(frag_content):
  File "/usr/local/bin/yt-dlp/yt_dlp/webvtt.py", line 363, in parse_fragment
    yield Magic.parse(parser)
  File "/usr/local/bin/yt-dlp/yt_dlp/webvtt.py", line 217, in parse
    raise ParseError(parser)
yt_dlp.webvtt.ParseError: Parse error at position 135 (near 'Style:\r\n::cue(v[voic')
```

**Comment by DHandspikerWade** [comment]
Looking a bit further into the subtitle file and into the spec, to my limited knowledge it looks like the issue is caused by there not being a blank line between the header block the style block as expected in `webvtt.py`. However it does seem to meet the WebVTT spec except "Style" should be capitalized. 

Sample of the subtitle file:
```
WEBVTT
Kind: captions
Language: en
Station: Nebula
ProgramName: Jet Lag: The Game
Season: 4
Episode: 1
PublishDate: 2022-12-07
Style:
::cue(v[voice="SFX"]) { color: rgb(204,204,204); }
::cue(v[voice="Sam"]) { color: white; }
::cue(v[voice="Adam"]) { color: yellow; }
::cue(v[voice="Ben"]) { color: cyan; }
::cue(v[voice="Brian"]) { color: green; }
::cue(v[voice="Keaundra"]) { color: rgb(255,153,255);
 }
::cue(v[voice="Extra"]) { color: rgb(255,204,136);
 }
::cue(#credit) { background: transparent; }
::cue(c.logo) {
	font-family: 'Courier New', Courier, monospace;
	font-weight: bold;
	font-size: 250%;
}
::cue(c.credit) {
    color: cyan;
    font-style: italic;
}
##

NOTE
Caption+ by JS*

00:00:00.034 --> 00:00:02.034 align:end size:97% position:97% line:91%
- We're racing to see who can
visit the most American states
```

**Comment by JohnKFisher** [comment]
Hoping this gets assigned to someone - I can recreate, again with the (new) episode of Jet Lag

**Comment by DHandspikerWade** [comment]
As a manual workaround, downloading the video without subtitles still works and passing the subtitle M3U8 URL into yt-dlp directly will create a MP4 that only contains a subtitle track. These two files can then be remuxed together. 

When done this way, styles are also maintained instead of ffmpeg stripping the styles.

**Comment by pukkandan** [comment]
> Hoping this gets assigned to someone

This isn't a company. Issues don't "get assigned". Anyone can try to tackle the problem and make a PR

**Comment by DHandspikerWade** [comment]
While I don't know enough Python to fix the issue, I did throw together a quick&dirty script to use in the mean time. Figured I'd post it here in case it helps anyone else. 

https://gist.github.com/DHandspikerWade/f11067386aa785430c7f34040379cf1e

**Comment by linuxdaemon** [comment]
Has there been any progress on this? I am still experiencing this issue with several videos from Nebula.

**Comment by seproDev** [comment]
The main issue is that Nebula serves non-standard compliant WebVTT files. Specifically, the file mentioned here is missing the declaration of a `NOTE` section, and has an invalid `STYLE` section declaration.

A potential solution would be to just optimistically keep parsing the file, with something like this:
```diff
diff --git a/yt_dlp/webvtt.py b/yt_dlp/webvtt.py
index dd7298277..99aa48c9e 100644
--- a/yt_dlp/webvtt.py
+++ b/yt_dlp/webvtt.py
@@ -95,7 +95,7 @@ def __init__(self, parser):
 _REGEX_EOF = re.compile(r'\Z')
 _REGEX_NL = re.compile(r'(?:\r\n|[\r\n]|$)')
 _REGEX_BLANK = re.compile(r'(?:\r\n|[\r\n])+')
-
+_REGEX_SKIP_LINE = re.compile(r'.*')

 def _parse_ts(ts):
     """
@@ -214,7 +214,7 @@ def parse(cls, parser):
             if m:
                 meta += m.group(0)
                 continue
-            raise ParseError(parser)
+            parser.consume(_REGEX_SKIP_LINE)
         parser.commit()
         return cls(extra=extra, mpegts=mpegts, local=local, meta=meta)

@@ -394,4 +394,4 @@ def parse_fragment(frag_content):
             yield block
             continue

-        raise ParseError(parser)
+        parser.consume(_REGEX_SKIP_LINE)
```
If something like this were to be added, I think it should either be behind a flag or at least emit some form of warning.

**Comment by pukkandan** [comment]
Related: https://github.com/yt-dlp/yt-dlp/pull/2175

**Comment by DHandspikerWade** [comment]
Retested issue on 2023.12.30 as it included a Nebula extractor refactor and some WebVTT changes. 

Can confirm issue still exists with the same parse error.

**Comment by seproDev** [comment]
This has been partially addressed by https://github.com/yt-dlp/yt-dlp/commit/f24e44e8cbd88ce338d52f594a19330f64d38b50.

While downloading these non-spec-compliant files now works fine, the fix only addresses the symptoms.
Leaving this open as the issue of the WebVTT parser being too strict still applies to multi fragment HLS WebVTT downloads.

**Comment by pukkandan** [comment]
Closing in favor of #9357 since the underlying issue is same and youtube link is easier to work with for devs
