### ISSUE TITLE
Generated URL of geo-blocked YouTube video returns 403 error when played in any country besides where the command was run

### ISSUE THREAD

**Issue by keith-vivi** [yt-dlp/yt-dlp#5815]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.11.11** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Provide a description that is worded well enough to be understood

Repro steps:

1. From a machine located in Australia (or AWS service regionalised to Australia), run `yt-dlp -vU <URL of video that is geo-blocked in any country?', e.g. [this video](https://www.youtube.com/watch?v=GRxofEmo3HA) is blocked in Somaliland, Kosovo and North Cyprus.
2. Try to play the generated `"https://rr...` video URL from a browser on a machine in any country besides Australia (tested in USA and India, as well as using a VPN)

Expected behaviour: The video should play fine in any country besides the ones that are blocked
Actual behaviour: The video does not play and returns a 403 error

Additional notes:
- The video plays fine on a machine in Australia.
- When following the above steps for a YouTube video with no geo restrictions in any country, the generated URL plays fine outside of Australia.
- The generated URL of dailymotion videos plays fine outside of Australia even if the video is geoblocked in other countries (checked with [this video](https://www.dailymotion.com/video/x7ewza3) and verified its geo-blocked status using the dailymotion API). Because of this, this issue is likely to be specific to YouTube

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
$ yt-dlp -vU https://www.youtube.com/watch?v=GRxofEmo3HA
[debug] Command-line config: ['-vU', 'https://www.youtube.com/watch?v=GRxofEmo3HA']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.11.11 [8b64402] (pip)
[debug] Python 3.8.10 (CPython x86_64 64bit) - Linux-5.10.16.3-microsoft-standard-WSL2-x86_64-with-glibc2.29 (OpenSSL 1.1.1f  31 Mar 2020, glibc 2.31)
[debug] exe versions: ffmpeg 4.2.7, ffprobe 4.2.7
[debug] Optional libraries: Cryptodome-3.14.1, brotli-1.0.9, certifi-2019.11.28, mutagen-1.45.1, secretstorage-2.3.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1723 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.11.11, Current version: 2022.11.11
yt-dlp is up to date (2022.11.11)
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=GRxofEmo3HA
[youtube] GRxofEmo3HA: Downloading webpage
[youtube] GRxofEmo3HA: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] GRxofEmo3HA: Downloading 1 format(s): 244+251
[debug] Invoking http downloader on "https://rr4---sn-uxanug5-hxael.googlevideo.com/videoplayback?expire=1671187704&ei=mPibY__BOMKag8UP66qkyA4&ip=110.147.156.84&id=o-AENz_d-7GTn9TRg_u51CMJia4Xi_igP03LPT2aVeAHKG&itag=244&source=youtube&requiressl=yes&mh=xe&mm=31%2C29&mn=sn-uxanug5-hxael%2Csn-hxa7zn7z&ms=au%2Crdu&mv=m&mvi=4&pl=21&gcr=au&initcwndbps=1681250&spc=zIddbDEa1DgSt2fHlBeQUUx0ISzlbNg&vprv=1&svpuc=1&mime=video%2Fwebm&gir=yes&clen=56698563&dur=2519.566&lmt=1651238370545879&mt=1671165943&fvip=1&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=4532434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cgcr%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIhAJuUkZwlGTNOz-L0WDualkHrd5Q7iLMda43FmvWq45Q6AiBHIw4V95c7_AluBZIpJYQzlQtoUZ6sg_oFvjXhqzWGLg%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgQ5JT_lOnGEjG3J52SknZkZ3s2o68gLGACyv8mS5KYWgCIQCPUC-0tsP-XyXHWzctaqivetgzP86vaVzyoAr2l-jZZw%3D%3D"
[download] Resuming download at byte 51844643
[download] Destination: Four Seasons ~ Vivaldi [GRxofEmo3HA].f244.webm
[download] 100% of   54.07MiB in 00:00:00 at 64.38MiB/s
[debug] Invoking http downloader on "https://rr4---sn-uxanug5-hxael.googlevideo.com/videoplayback?expire=1671187704&ei=mPibY__BOMKag8UP66qkyA4&ip=110.147.156.84&id=o-AENz_d-7GTn9TRg_u51CMJia4Xi_igP03LPT2aVeAHKG&itag=251&source=youtube&requiressl=yes&mh=xe&mm=31%2C29&mn=sn-uxanug5-hxael%2Csn-hxa7zn7z&ms=au%2Crdu&mv=m&mvi=4&pl=21&gcr=au&initcwndbps=1681250&spc=zIddbDEa1DgSt2fHlBeQUUx0ISzlbNg&vprv=1&svpuc=1&mime=audio%2Fwebm&gir=yes&clen=43475726&dur=2519.641&lmt=1651238182519676&mt=1671165943&fvip=1&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=4532434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cgcr%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRAIgJdzLUS7_rAQbs5aYR5g5Ev3zwXKeUhl5pHtY92rwK3ACIDnDy6oq28wwcrPb7s-A-x44iKmCCrUecoZeOY3Fb_r-&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgQ5JT_lOnGEjG3J52SknZkZ3s2o68gLGACyv8mS5KYWgCIQCPUC-0tsP-XyXHWzctaqivetgzP86vaVzyoAr2l-jZZw%3D%3D"
[download] Destination: Four Seasons ~ Vivaldi [GRxofEmo3HA].f251.webm
[download] 100% of   41.46MiB in 00:00:07 at 5.88MiB/s
[Merger] Merging formats into "Four Seasons ~ Vivaldi [GRxofEmo3HA].webm"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:Four Seasons ~ Vivaldi [GRxofEmo3HA].f244.webm' -i 'file:Four Seasons ~ Vivaldi [GRxofEmo3HA].f251.webm' -c copy -map 0:v:0 -map 1:a:0 -movflags +faststart 'file:Four Seasons ~ Vivaldi [GRxofEmo3HA].temp.webm'
Deleting original file Four Seasons ~ Vivaldi [GRxofEmo3HA].f244.webm (pass -k to keep)
Deleting original file Four Seasons ~ Vivaldi [GRxofEmo3HA].f251.webm (pass -k to keep)
```

**Comment by coletdjnz** [comment]
yes... but this has nothing to do with yt-dlp. As you have looked into, it's YouTube that imposes the restrictions on the video playback urls **server side**.

https://github.com/yt-dlp/yt-dlp/wiki/FAQ#i-extracted-a-video-url-but-it-does-not-play-on-another-machine--in-my-web-browser

related: https://github.com/yt-dlp/yt-dlp/issues/5750
