### ISSUE TITLE
keeps downloading the entire playlist when I only want a single video

### ISSUE THREAD

**Issue by kevo885** [yt-dlp/yt-dlp#5816]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2022.11.11** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

I am trying to download something from youtube via the "copy link address", but the problem is, if it belongs to a playlist, it downloads the entire playlist instead. I am now copying the playlist link, rather, the single video link, I've always used "copy link address" but suddenly today, yt-dlp is downloading the entire playlist instead of a single video.

for reference, this is what I used:

yt-dlp -c -P "/Users/Macbook/Final Cut Pro/" -o "%(title)s.%(ext)s" -f "bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best" --cookies-from-browser chrome "https://www.youtube.com/watch?v=krQ0ITsn7zg&list=PLJAzFcYKyx4QBMgSXKieHNRU8zttGrk_l&index=1"

Tried removing all of my flags and commenting out my config file, still same problem. Running 2022.11.11

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp -vU "https://www.youtube.com/watch?v=krQ0ITsn7zg&list=PLJAzFcYKyx4QBMgSXKieHNRU8zttGrk_l&index=1"
[debug] Command-line config: ['-vU', 'https://www.youtube.com/watch?v=krQ0ITsn7zg&list=PLJAzFcYKyx4QBMgSXKieHNRU8zttGrk_l&index=1']
[debug] User config "/Users/MacBook/.config/yt-dlp/config": ['-c', '-o', '%(title)s.%(ext)s', '-f', 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best', '--cookies-from-browser', 'chrome', '--alias', '-B', '-P "/Users/Macbook/Final Cut Pro/" --batch-file="/Users/Macbook/Downloads/batch"', '--alias', '-S', '-P "/Users/Macbook/Final Cut Pro/"']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.11.11 [8b64402]
[debug] Python 3.10.8 (CPython arm64 64bit) - macOS-13.1-arm64-arm-64bit (OpenSSL 3.0.7 1 Nov 2022)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2, rtmpdump 2.4
[debug] Optional libraries: Crypto-3.15.0, sqlite3-2.6.0
[Cookies] Extracting cookies from chrome
[debug] Extracting cookies from: "/Users/MacBook/Library/Application Support/Google/Chrome/Default/Cookies"
[debug] using find-generic-password to obtain password from OSX keychain
[Cookies] Extracted 10575 cookies from chrome
[debug] cookie version breakdown: {'v10': 10463, 'other': 0, 'unencrypted': 112}
[debug] Proxy map: {}
[debug] Loaded 1723 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.11.11, Current version: 2022.11.11
yt-dlp is up to date (2022.11.11)
[debug] [youtube:tab] Extracting URL: https://www.youtube.com/watch?v=krQ0ITsn7zg&list=PLJAzFcYKyx4QBMgSXKieHNRU8zttGrk_l&index=1
[youtube:tab] Downloading playlist PLJAzFcYKyx4QBMgSXKieHNRU8zttGrk_l - add --no-playlist to download just the video krQ0ITsn7zg
[youtube:tab] PLJAzFcYKyx4QBMgSXKieHNRU8zttGrk_l: Downloading webpage
[debug] [youtube:tab] Extracting URL: https://www.youtube.com/playlist?list=PLJAzFcYKyx4QBMgSXKieHNRU8zttGrk_l
[youtube:tab] PLJAzFcYKyx4QBMgSXKieHNRU8zttGrk_l: Downloading webpage
[debug] [youtube:tab] Extracted SAPISID cookie
[youtube:tab] PLJAzFcYKyx4QBMgSXKieHNRU8zttGrk_l: Redownloading playlist API JSON with unavailable videos
[download] Downloading playlist: E3 2021
[youtube:tab] Playlist E3 2021: Downloading 4 videos of 4
[download] Downloading video 1 of 4
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=krQ0ITsn7zg
[youtube] krQ0ITsn7zg: Downloading webpage
[debug] [youtube] Extracted SAPISID cookie
[youtube] krQ0ITsn7zg: Downloading android player API JSON
[debug] Loading youtube-nsig.34f9b71c from cache
/opt/local/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/yt_dlp/jsinterp.py:346: FutureWarning: Possible nested set at position 18
  inner = re.compile(inner[1:], flags=flags)
[debug] [youtube] Decrypted nsig fJzT05N7jAAVeD => SuvRDDR0Zfqv9w
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[info] krQ0ITsn7zg: Downloading 1 format(s): 401+140
[debug] Invoking http downloader on "https://rr3---sn-q4flrnez.googlevideo.com/videoplayback?expire=1671281858&ei=YmidY8byKvOilu8PvsOE6As&ip=2600%3A1700%3A1476%3A4450%3A3d68%3Ac3b7%3A3e99%3A3305&id=o-ABk-SiqmSK0aLZ2AzjIqjTSFKdYVSVGiyOoadwNpi9Fh&itag=401&source=youtube&requiressl=yes&mh=Xq&mm=31%2C29&mn=sn-q4flrnez%2Csn-q4fl6nsk&ms=au%2Crdu&mv=m&mvi=3&pl=46&initcwndbps=1527500&spc=zIddbHT8fF3giU5bdvHkZVnlTNUlUfvIzGahz9Qg9mfM&vprv=1&svpuc=1&mime=video%2Fmp4&gir=yes&clen=1236963981&dur=831.349&lmt=1663334603831035&mt=1671259775&fvip=4&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=4532434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRgIhAMLzoXZj8l2pYGUIj4jsT5mb5XuyxN0wurVfjTj6DTpHAiEAg_5phoqtiXdaJ0vi9LcQmQrhWE3OP5rJH-jouQlB4zY%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgNfpCxRkQ_2l60YGiRQeRUNvnkgwiki0Qzhg2PUoQRIkCIAr4Ry92Ni0B_XYpYbpVMMF_md6DTOovYxPBdPfFOS7E"
```

**Comment by coletdjnz** [comment]
> [youtube:tab] Downloading playlist PLJAzFcYKyx4QBMgSXKieHNRU8zttGrk_l - add --no-playlist to download just the video krQ0ITsn7zg

**Comment by kevo885** [comment]
do you know why, It started downloading the entire playlist today? in the past I didn’t have this problem

**Comment by coletdjnz** [comment]
> do you know why, It started downloading the entire playlist today? in the past I didn’t have this problem

I wouldn't know, you'll have to look back at what you were doing. This behaviour has existed for a long time.

**Comment by m4gnify** [comment]
I don't know how it's "supposed" to act, but try removing the "list" part of the URL.
[&list=PLJAzFcYKyx4QBMgSXKieHNRU8zttGrk_l&index=1](https://www.youtube.com/watch?v=krQ0ITsn7zg&list=PLJAzFcYKyx4QBMgSXKieHNRU8zttGrk_l&index=1)"

So the command ends up being 
`yt-dlp -c -P "/Users/Macbook/Final Cut Pro/" -o "%(title)s.%(ext)s" -f "bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best" --cookies-from-browser chrome "https://www.youtube.com/watch?v=krQ0ITsn7zg"`
