### ISSUE TITLE
[neurips] Media Support (Videos + Slides)

### ISSUE THREAD

**Issue by Ashish0804** [yt-dlp/yt-dlp#5818]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2022.11.11** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Global

### Example URLs

- Single video: https://videos.neurips.cc/video/slideslive-38922815
- Single video: https://videos.neurips.cc/topic/machine%20learning/video/slideslive-38923348
- Playlist: https://videos.neurips.cc/category/2142/
- Playlist: https://videos.neurips.cc/topic/machine%20learning/

### Provide a description that is worded well enough to be understood

Site has slides side by side video, would appreciate if slides can be downloaded side by side of videos by default. 

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
❯ ytf 'https://videos.neurips.cc/video/slideslive-38922815' -v
[debug] Command-line config: ['-F', '--list-subs', 'https://videos.neurips.cc/video/slideslive-38922815', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.11.11 [8b64402] (pip)
[debug] Python 3.10.6 (CPython arm64 64bit) - macOS-13.0.1-arm64-arm-64bit (OpenSSL 1.1.1q  5 Jul 2022)
[debug] exe versions: ffmpeg 5.1.1 (setts), ffprobe 5.1.1
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1723 extractors
[debug] [generic] Extracting URL: https://videos.neurips.cc/video/slideslive-38922815
[generic] slideslive-38922815: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] slideslive-38922815: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://videos.neurips.cc/video/slideslive-38922815
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1485, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1561, in __extract_info
    ie_result = ie.extract(url)
  File "/opt/homebrew/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 674, in extract
    ie_result = self._real_extract(url)
  File "/opt/homebrew/lib/python3.10/site-packages/yt_dlp/extractor/generic.py", line 2721, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://videos.neurips.cc/video/slideslive-38922815
```

**Comment by bashonly** [comment]
Related: #5784

Looks like neurips uses the videoken API instead of the standard slideslive embed JS though. Will need an extractor for that

**Comment by bashonly** [comment]
> Site has slides side by side video, would appreciate if slides can be downloaded side by side of videos

The current version of the slideslive extractor PR will download all video slides by default, and download all image slides if `--write-all-thumbnails` is passed (the majority of slides are still images). The slides are numbered to coincide with the primary video's chapter numbers. I think actually having the slides displayed side-by-side with the video would require a custom postprocessor for the site. Not sure how to go about doing that or how feasible it is. Suggestions welcome

> slides ... downloaded ... **by default**.

@pukkandan Is this something that would be acceptable to do? The only way I can think of is to have the extractor set the `write_all_thumbnails` param to `True`. & then would there need to be something like a `skip_slides` extractor-arg since `--no-write-thumbnail` would not work?

**Comment by pukkandan** [comment]
> and download all image slides if `--write-all-thumbnails` is passed (the majority of slides are still images).
> I think actually having the slides displayed side-by-side with the video would require a custom postprocessor for the site.

This is out of scope. But, we could download all the images as a single mhtml file (like storyboards). This will put all images in a single file, but will still keep the videos separate from images - so I'm not sure whether it's worth it

> Is this something that would be acceptable to do? The only way I can think of is to have the extractor set the `write_all_thumbnails` param to `True`

No

**Comment by bashonly** [comment]
The site's API changed in the past week and now I can't get any of these example URLs to play in browser anymore (error 400 from API). @Ashish0804 are you still able to play any of these neurips videos?

**Comment by ferreirafabio** [comment]
Thanks for the update on the SlidesLive support. Download the video now is made super easy. However, how can I download the slides? When passing ```--write-all-thumbnails```, I get 403's:

```
$ yt-dlp --write-all-thumbnails https://slideslive.com/38983994
[SlidesLive] Extracting URL: https://slideslive.com/38983994
[SlidesLive] 38983994: Downloading webpage
[SlidesLive] 38983994: Downloading player info
[SlidesLive] 38983994: Downloading slides JSON
[SlidesLive] 38983994: Downloading m3u8 information
[SlidesLive] 38983994: Downloading MPD manifest
[info] 38983994: Downloading 1 format(s): hls-4+dash-5
[info] Downloading video thumbnail cover ...
[info] Writing video thumbnail cover to: Zero-Shot AutoML with Pretrained Models [38983994].cover.jpg
[info] Downloading video thumbnail 022 ...
WARNING: Unable to download video thumbnail 022: HTTP Error 403: Forbidden
[info] Downloading video thumbnail 021 ...
```

**Comment by bashonly** [comment]
> When passing `--write-all-thumbnails`, I get 403's as shown below.

This will fix that:
```diff
diff --git a/yt_dlp/extractor/slideslive.py b/yt_dlp/extractor/slideslive.py
index 4268bfeaf..73bc51823 100644
--- a/yt_dlp/extractor/slideslive.py
+++ b/yt_dlp/extractor/slideslive.py
@@ -431,7 +431,7 @@ def _real_extract(self, url):
         slides_version = int(self._search_regex(
             r'https?://slides\.slideslive\.com/\d+/v(\d+)/\w+\.(?:json|xml)',
             slides_info_url, 'slides version', default=0))
-        if slides_version < 4:
+        if slides_version < 3:
             slide_url_template = 'https://cdn.slideslive.com/data/presentations/%s/slides/big/%s.jpg'
         else:
             slide_url_template = 'https://slides.slideslive.com/%s/slides/original/%s.png'
```
I didn't have enough sample data for `v3` slides at the time. Now it looks like `.png` is the way to go with them. I'll fix

> Back in the old days, we were able to access the user-view video and slides-view video

Are you talking about with the extractor? Looking over the history of `slideslive.py` I am not seeing when this was ever possible

**Comment by ferreirafabio** [comment]
Thanks for the fix; tested and works! Sorry, with "back in the old days" I meant that SlidesLive would provide us links to separate videos for user-view and slides-view. What would be your suggestion how to best merge both video and slides into one video? I used to merge two videos (already in-sync) with ffmpeg but with the .png's the syncing with the video becomes an issue as I'm not sure how to access the chapter meta info in the video through ffmpeg.

**Comment by ferreirafabio** [comment]
btw

```yt-dlp --embed-chapters --write-all-thumbnails https://slideslive.com/38983994```

yields the error 
```ERROR: unsupported operand type(s) for *: 'NoneType' and 'int'```

**Comment by bashonly** [comment]
> `ERROR: unsupported operand type(s) for *: 'NoneType' and 'int'`

@ferreirafabio Thanks for bringing these issues to my attention, they should be fixed with #6024

Merging the slides with the video is out-of-scope for yt-dlp but it could possibly be done with a postprocessor plugin. When I have time I'll try looking into it

**Comment by ferreirafabio** [comment]
@bashonly I just wanted to quickly follow-up on the mentioned postprocessor plugin and ask, whether you had time to look into this to allow merging both video and slides into one video. Essentially, a large portion of the machine learning community (which submits their talks to slideslive.com) would immensely welcome this functionality :) Thanks a lot for the great work!

**Comment by jucor** [comment]
Ooh, I like the idea of a postprocessor to display the slides along with the video!

I checked  on ICLR 2025, which uses slideslides under the hood I believe. Arguments `--write-info-json --write-all-thumbnails` give us what we need. We could start with an external script, then look into adapting it as a post-processor.

The fields `chapters[].start_time` and `chapters[].end_time` tell us when to display each slide. The field `thumbnails[].id`, combined with the output name of the video, tell us the name of the image file to display. The extension at the end of `thumbnails[].url` tells us the extension of the saved thumbnail.

Then we need to call ffmpeg to generate a video of just the slides as fixed images (with a special case to handle slides that contain videos), keyed to the duration of each chapter.
And finally we could put embed the speaker either:
- side-by-side (which makes a very wide video)
- or embedded in a small vignette in the bottom right or top-right corner (thus keeping a regular aspect-ratio)
- or just ignore the image of the speaker, and keep only the video of the slides.

That behaviour could be an option of the post-processor.

As a bonus, we could concatenate the slides in a PDF (again, not sure about embedded videos, and that PDF might be heavy because we're just collating images).

**Comment by jucor** [comment]
@ferreirafabio : if I have a go at it, you fancy beta-testing it? Also, please say hi to Frank for me, long time no see :)

**Comment by jucor** [comment]
I've vibe-coded that "merge slides + speaker" into a script here: https://github.com/jucor/mlconf-dlp 
This _could_ become a postprocessor, but 
- I don't have the time to figure it out 
- I suspect machine learners will have an easier time with a script than with finding that `yt-dlp` has postprocessors :D 

Any feedback is welcome !
