### ISSUE TITLE
Hotstar Payment Required[Broken]

### ISSUE THREAD

**Issue by Karma2424** [yt-dlp/yt-dlp#583]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running yt-dlp version **2021.07.24**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
C:\Users\*\Downloads\Programs>yt-dlp.exe https://www.hotstar.com/in/tv/doraemon/1260021004/dont-take-my-jack-away-nobita-raises-moon-princess/1260021168 --verbose --cookies-from-browser chrome
[debug] Command-line config: ['https://www.hotstar.com/in/tv/doraemon/1260021004/dont-take-my-jack-away-nobita-raises-moon-princess/1260021168', '--verbose', '--cookies-from-browser', 'chrome']
[Cookies] Extracting cookies from chrome
[debug] extracting from: "C:\Users\*\AppData\Local\Google\Chrome\User Data\Default\Cookies"
[Cookies] Extracted 2541 cookies from chrome
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] yt-dlp version 2021.07.24 (exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] exe versions: ffmpeg 4.4-full_build-www.gyan.dev, ffprobe 4.4-full_build-www.gyan.dev
[debug] Proxy map: {}
[debug] [hotstar] Extracting URL: https://www.hotstar.com/in/tv/doraemon/1260021004/dont-take-my-jack-away-nobita-raises-moon-princess/1260021168
[hotstar] 1260021168: Downloading webpage
[hotstar] 1260021168: Downloading token
[hotstar] 1260021168: Downloading JSON metadata
ERROR: Unable to download JSON metadata: HTTP Error 402: Payment Required (caused by <HTTPError 402: 'Payment Required'>); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
  File "yt_dlp\extractor\common.py", line 679, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 3126, in urlopen
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 649, in http_error_default

```

## Description

Payment Required error even if cookies are passed

**Comment by Ashish0804** [comment]
Hotstar doesn't support cookies yet
see https://github.com/ytdl-org/youtube-dl/pull/29370

You can use using the `--username <mobile_number>` and then add the `opt` in the password.

**Comment by Karma2424** [comment]
@Ashish0804 as you said I added <code>--username</code> but I am still getting Payment Required

**Comment by Karma2424** [comment]
Also I am not getting opt on my phone

**Comment by Ashish0804** [comment]
Wait for the PR to be merged.

As of not getting otp, idk what you are doing wrong.

**Comment by Karma2424** [comment]
I am running this `yt-dlp.exe https://www.hotstar.com/in/tv/doraemon/1260021004/dont-take-my-jack-away-nobita-raises-moon-princess/1260021168 --username number --verbose`

**Comment by Ashish0804** [comment]
When u press enter first it will ask for a password...this is ytdlp just reminding u that u forgot to add password, u have to press enter without entering anything, then it will start making requests to hotstar and run the code to get otp. Once u get the otp it will ask for password/otp again, enter the code u got and continue.

**Comment by Karma2424** [comment]
I did as you said press enter first time it asks then it does not ask opt as you can see in this `[debug] Command-line config: ['https://www.hotstar.com/in/tv/doraemon/1260021004/dont-take-my-jack-away-nobita-raises-moon-princess/1260021168', '--username', 'PRIVATE', '--verbose']
Type account password and press [Return]:
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] yt-dlp version 2021.07.24 (exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] exe versions: ffmpeg 4.4-full_build-www.gyan.dev, ffprobe 4.4-full_build-www.gyan.dev
[debug] Proxy map: {}
[debug] [hotstar] Extracting URL: https://www.hotstar.com/in/tv/doraemon/1260021004/dont-take-my-jack-away-nobita-raises-moon-princess/1260021168
[hotstar] 1260021168: Downloading webpage
[hotstar] 1260021168: Downloading token
[hotstar] 1260021168: Downloading JSON metadata
ERROR: Unable to download JSON metadata: HTTP Error 402: Payment Required (caused by <HTTPError 402: 'Payment Required'>); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
  File "yt_dlp\extractor\common.py", line 679, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 3126, in urlopen
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 649, in http_error_default`
