### ISSUE TITLE
Is 15fps available for 240p Youtube

### ISSUE THREAD

**Issue by teeol** [yt-dlp/yt-dlp#5830]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.11.11** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I use 4K Downloader to download videos from youtube and i want to know if 240p 12fps is something that can be added to MX_ytdlp-32(located in C:\Users\c1\AppData\Roaming\4K Software\Common\Services )  since there is already an option for 256x144 12fps h264, but which is really 14-15fps when you check media info. Asking this because i want some video to be for archival purpose since a 15 minute video at 15fps 240p could easily take up 8MB of space.

This is with MX_ytdlp-32 allowed internet access
![2022-12-19_11h08_05](https://user-images.githubusercontent.com/85901531/208383381-94e2d784-fd71-47a2-92f6-7d187c78ce81.png)

Without
![2022-12-19_11h41_38](https://user-images.githubusercontent.com/85901531/208383727-9a2bf428-d934-4d34-be7a-bcc99c18a8e9.png)

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-your-question-about-yt-dlp
