### ISSUE TITLE
works with vk.com, but not works with vk.ru (mirror)

### ISSUE THREAD

**Issue by HasbersHz** [yt-dlp/yt-dlp#5832]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a site-specific feature
- [X] I've verified that I'm running yt-dlp version **2022.11.11** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [x] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Russsia

### Example URLs

"https://vk.ru/video_ext.php?oid=-180523271&id=456239085&hash=fcf31bd629441b35&hd=2"
"http://vk.ru/video205387401_165548505"

### Provide a description that is worded well enough to be understood

yt-dlp works with vk.com, but does not support his official mirror - vk.ru

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://vk.ru/video_ext.php?oid=-180523271&id=456239085&hash=fcf31bd629441b35&hd=2']
[debug] Encodings: locale cp1251, fs utf-8, pref cp1251, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.11.11 [8b64402] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19044-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 2022-03-17-git-242c07982a-essentials_build-www.gyan.dev (setts)
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1723 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.11.11, Current version: 2022.11.11
yt-dlp is up to date (2022.11.11)
[debug] [generic] Extracting URL: https://vk.ru/video_ext.php?oid=-180523271&id=456239085&hash=fcf31bd629441b35&hd=2
[generic] video_ext: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] video_ext: Extracting information
[debug] Looking for embeds
[redirect] Following redirect to https://vk.ru/badbrowser.php
[debug] [generic] Extracting URL: https://vk.ru/badbrowser.php
[generic] badbrowser: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] badbrowser: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://vk.ru/badbrowser.php
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1485, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1561, in __extract_info
  File "yt_dlp\extractor\common.py", line 674, in extract
  File "yt_dlp\extractor\generic.py", line 2721, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://vk.ru/badbrowser.php
```

**Comment by pukkandan** [comment]
> yt-dlp works with vk.com

Does not appear to work for me. Could you show verbose?

```
❯ yt-dlp -v "https://vk.com/video_ext.php?oid=-180523271&id=456239085&hash=fcf31bd629441b35&hd=2"
[debug] Command-line config: ['--ignore-config', '-v', 'https://vk.com/video_ext.php?oid=-180523271&id=456239085&hash=fcf31bd629441b35&hd=2']
[debug] Encodings: locale cp65001, fs utf-8, pref cp65001, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.11.11 [8b644025b] (source)
[debug] Lazy loading extractors is disabled
[debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
[debug] Git HEAD: 2cc4386b2
[debug] Python 3.11.0 (CPython AMD64 64bit) - Windows-10-10.0.22000-SP0 (OpenSSL 1.1.1q  5 Jul 2022)
[debug] exe versions: ffmpeg n5.1.2-8-g5746987bad-20221204 (fdk,setts), ffprobe N-109332-g45ab5307a6-20221201, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1736 extractors
[vk] Extracting URL: https://vk.com/video_ext.php?oid=-180523271&id=456239085&hash=fcf31bd629441b35&hd=2
[vk] -180523271_456239085: Downloading webpage
ERROR: [vk] 456239085: Unable to extract player params; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "D:\Programs\Source\yt-dlp\yt-dlp\yt_dlp\extractor\common.py", line 680, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programs\Source\yt-dlp\yt-dlp\yt_dlp\extractor\vk.py", line 427, in _real_extract
    player = self._parse_json(self._search_regex(
                              ^^^^^^^^^^^^^^^^^^^
  File "D:\Programs\Source\yt-dlp\yt-dlp\yt_dlp\extractor\common.py", line 1228, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
```

**Comment by dirkf** [comment]
Eg:
```
$ python3.9 -m yt_dlp -F -v 'https://vk.com/video_ext.php?oid=-180523271&id=456239085&hash=fcf31bd629441b35&hd=2'
[debug] Command-line config: ['-F', '-v', 'https://vk.com/video_ext.php?oid=-180523271&id=456239085&hash=fcf31bd629441b35&hd=2']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.11.11 [8b644025b] (source)
[debug] Lazy loading extractors is disabled
[debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
[debug] Git HEAD: c73355510
[debug] Python 3.9.15 (CPython i686 32bit) - Linux-4.4.0-210-generic-i686-with-glibc2.23 (OpenSSL 1.1.1s  1 Nov 2022, glibc 2.23)
[debug] exe versions: ffmpeg 4.3, ffprobe 4.3
[debug] Optional libraries: Cryptodome-3.11.0, certifi-2019.11.28, secretstorage-3.2.0, sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Loaded 1735 extractors
[vk] Extracting URL: https://vk.com/video_ext.php?oid=-180523271&id=456239085&hash=fcf31bd629441b35&hd=2
[vk] -180523271_456239085: Downloading webpage
[vk] -180523271_456239085: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[info] Available formats for -180523271_456239085:
ID       EXT           RESOLUTION FPS │    FILESIZE   TBR PROTO │ VCODEC    VBR ACODEC  ABR
───────────────────────────────────────────────────────────────────────────────────────────
hls-175  mp4           256x144     30 │ ~ 372.84KiB  175k m3u8  │ unknown  175k unknown  0k
url240   unknown_video 240p           │                   https │ unknown       unknown
hls-481  mp4           426x240     30 │ ~1022.20KiB  481k m3u8  │ unknown  481k unknown  0k
url360   unknown_video 360p           │                   https │ unknown       unknown
hls-1048 mp4           640x360     30 │ ~   2.18MiB 1049k m3u8  │ unknown 1049k unknown  0k
url480   unknown_video 480p           │                   https │ unknown       unknown
hls-1895 mp4           852x480     30 │ ~   3.93MiB 1896k m3u8  │ unknown 1896k unknown  0k
url720   unknown_video 720p           │                   https │ unknown       unknown
hls-4286 mp4           1280x720    30 │ ~   8.90MiB 4286k m3u8  │ unknown 4286k unknown  0k
url1080  unknown_video 1080p          │                   https │ unknown       unknown
hls-7499 mp4           1920x1080   30 │ ~  15.56MiB 7499k m3u8  │ unknown 7499k unknown  0k
$
```
The issue with this extractor is that references to vk.com are built into the source (including the login procedure). When vk.ru being used, is it the case that vk.com may be blocked? If so, the extractor needs to use vk.ru, perhaps through a sub-classed IE.

Are there other "mirrors"? Apparently not vk.kz or vk.by.

**Comment by HasbersHz** [comment]
> > yt-dlp works with vk.com
> 
> Does not appear to work for me. Could you show verbose?
> 
> ```
> ❯ yt-dlp -v "https://vk.com/video_ext.php?oid=-180523271&id=456239085&hash=fcf31bd629441b35&hd=2"
> [debug] Command-line config: ['--ignore-config', '-v', 'https://vk.com/video_ext.php?oid=-180523271&id=456239085&hash=fcf31bd629441b35&hd=2']
> [debug] Encodings: locale cp65001, fs utf-8, pref cp65001, out utf-8, error utf-8, screen utf-8
> [debug] yt-dlp version 2022.11.11 [8b644025b] (source)
> [debug] Lazy loading extractors is disabled
> [debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
> [debug] Git HEAD: 2cc4386b2
> [debug] Python 3.11.0 (CPython AMD64 64bit) - Windows-10-10.0.22000-SP0 (OpenSSL 1.1.1q  5 Jul 2022)
> [debug] exe versions: ffmpeg n5.1.2-8-g5746987bad-20221204 (fdk,setts), ffprobe N-109332-g45ab5307a6-20221201, phantomjs 2.1.1
> [debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
> [debug] Proxy map: {}
> [debug] Loaded 1736 extractors
> [vk] Extracting URL: https://vk.com/video_ext.php?oid=-180523271&id=456239085&hash=fcf31bd629441b35&hd=2
> [vk] -180523271_456239085: Downloading webpage
> ERROR: [vk] 456239085: Unable to extract player params; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
>   File "D:\Programs\Source\yt-dlp\yt-dlp\yt_dlp\extractor\common.py", line 680, in extract
>     ie_result = self._real_extract(url)
>                 ^^^^^^^^^^^^^^^^^^^^^^^
>   File "D:\Programs\Source\yt-dlp\yt-dlp\yt_dlp\extractor\vk.py", line 427, in _real_extract
>     player = self._parse_json(self._search_regex(
>                               ^^^^^^^^^^^^^^^^^^^
>   File "D:\Programs\Source\yt-dlp\yt-dlp\yt_dlp\extractor\common.py", line 1228, in _search_regex
>     raise RegexNotFoundError('Unable to extract %s' % _name)
> ```
```
yt-dlp -v "https://vk.com/video_ext.php?oid=-180523271&id=456239085&hash=fcf31bd629441b35&hd=2"
[debug] Command-line config: ['-v', 'https://vk.com/video_ext.php?oid=-180523271&id=456239085&hash=fcf31bd629441b35&hd=2']
[debug] Encodings: locale cp1251, fs utf-8, pref cp1251, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.11.11 [8b64402] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19044-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 2022-03-17-git-242c07982a-essentials_build-www.gyan.dev (setts)
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1723 extractors
[debug] [vk] Extracting URL: https://vk.com/video_ext.php?oid=-180523271&id=456239085&hash=fcf31bd629441b35&hd=2
[vk] -180523271_456239085: Downloading webpage
[vk] -180523271_456239085: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] -180523271_456239085: Downloading 1 format(s): hls-7499
[debug] Invoking hlsnative downloader on "https://vkvd41.mycdn.me/expires/1671820397797/srcIp/31.163.142.20/pr/40/srcAg/CHROME/ms/185.226.52.172/type/5/sig/nP5GQBfB60w/ct/8/urls/45.136.22.176/clientType/13/id/801583270611/video/"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 2
[download] Destination: это не самара [-180523271_456239085].mp4
[debug] File locking is not supported. Proceeding without locking
[download] 100% of   15.81MiB in 00:00:01 at 10.98MiB/s
WARNING: Unable to extract metadata: ffprobe not found. Please install or provide the path using --ffmpeg-location
[FixupM3u8] Fixing MPEG-TS in MP4 container of "это не самара [-180523271_456239085].mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:это не самара [-180523271_456239085].mp4" -map 0 -dn -ignore_unknown -c copy -f mp4 "-bsf:a" aac_adtstoasc -movflags "+faststart" "file:это не самара [-180523271_456239085].temp.mp4"
```

**Comment by HasbersHz** [comment]
> Eg:
> 
> ```
> $ python3.9 -m yt_dlp -F -v 'https://vk.com/video_ext.php?oid=-180523271&id=456239085&hash=fcf31bd629441b35&hd=2'
> [debug] Command-line config: ['-F', '-v', 'https://vk.com/video_ext.php?oid=-180523271&id=456239085&hash=fcf31bd629441b35&hd=2']
> [debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
> [debug] yt-dlp version 2022.11.11 [8b644025b] (source)
> [debug] Lazy loading extractors is disabled
> [debug] Plugins: ['SamplePluginIE', 'SamplePluginPP']
> [debug] Git HEAD: c73355510
> [debug] Python 3.9.15 (CPython i686 32bit) - Linux-4.4.0-210-generic-i686-with-glibc2.23 (OpenSSL 1.1.1s  1 Nov 2022, glibc 2.23)
> [debug] exe versions: ffmpeg 4.3, ffprobe 4.3
> [debug] Optional libraries: Cryptodome-3.11.0, certifi-2019.11.28, secretstorage-3.2.0, sqlite3-2.6.0
> [debug] Proxy map: {}
> [debug] Loaded 1735 extractors
> [vk] Extracting URL: https://vk.com/video_ext.php?oid=-180523271&id=456239085&hash=fcf31bd629441b35&hd=2
> [vk] -180523271_456239085: Downloading webpage
> [vk] -180523271_456239085: Downloading m3u8 information
> [debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
> [info] Available formats for -180523271_456239085:
> ID       EXT           RESOLUTION FPS │    FILESIZE   TBR PROTO │ VCODEC    VBR ACODEC  ABR
> ───────────────────────────────────────────────────────────────────────────────────────────
> hls-175  mp4           256x144     30 │ ~ 372.84KiB  175k m3u8  │ unknown  175k unknown  0k
> url240   unknown_video 240p           │                   https │ unknown       unknown
> hls-481  mp4           426x240     30 │ ~1022.20KiB  481k m3u8  │ unknown  481k unknown  0k
> url360   unknown_video 360p           │                   https │ unknown       unknown
> hls-1048 mp4           640x360     30 │ ~   2.18MiB 1049k m3u8  │ unknown 1049k unknown  0k
> url480   unknown_video 480p           │                   https │ unknown       unknown
> hls-1895 mp4           852x480     30 │ ~   3.93MiB 1896k m3u8  │ unknown 1896k unknown  0k
> url720   unknown_video 720p           │                   https │ unknown       unknown
> hls-4286 mp4           1280x720    30 │ ~   8.90MiB 4286k m3u8  │ unknown 4286k unknown  0k
> url1080  unknown_video 1080p          │                   https │ unknown       unknown
> hls-7499 mp4           1920x1080   30 │ ~  15.56MiB 7499k m3u8  │ unknown 7499k unknown  0k
> $
> ```
> 
> The issue with this extractor is that references to vk.com are built into the source (including the login procedure). When vk.ru being used, is it the case that vk.com may be blocked? If so, the extractor needs to use vk.ru, perhaps through a sub-classed IE.
> 
> Are there other "mirrors"? Apparently not vk.kz or vk.by.

To be honest, I didn't understand you. I'm wrong, I meant that in fact vk.ru is a different domain of the vk.com website. It is not difficult for me to change ru to com, but it seems to me that this is a problem, or have I misunderstood?

**Comment by dirkf** [comment]
The VKontakte site is hosted at vk.com and now also at vk.ru.

I wondered if there was an issue with the regulation of the site such that in some circumstances vk.com might not be accessible while vk.ru was. Then if the yt-dl[p] extractor processed a URL with the vk.ru domain in exactly the same way, fetching metadata and media links from vk.com URLs internally, the URL extraction would fail; on the other hand, the URLs used internally might not be valid at all with the vk.ru domain.

Secondly, given that vk.ru exists, perhaps other nations of the former Soviet Union might have VKontakte mirror sites (but, as I noted, not Kazakhstan, nor Belarus, nor even, or especially, Ukraine).
