### ISSUE TITLE
Public Instagram Reels Don't Download

### ISSUE THREAD

**Issue by goodboi69691** [yt-dlp/yt-dlp#5848]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2022.11.11** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

USA

### Provide a description that is worded well enough to be understood

When downloading a Reel from a public profile, it will not download.
The Reel in question: https://www.instagram.com/reel/Cl2N-hmMcXG/

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU']
[debug] User config "C:\Users\XXXX\AppData\Roaming\yt-dlp\config.txt": ['-o', '~/Desktop/%(title)s.%(ext)s', '-f', 'bestvideo+bestaudio[ext=m4a]', '--embed-chapters', '--add-metadata']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.11.11 [8b64402] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-93488-g52d8f35b14, ffprobe N-93488-g52d8f35b14
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1723 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.11.11, Current version: 2022.11.11
yt-dlp is up to date (2022.11.11)
```

**Comment by bashonly** [comment]
>>>  Run your yt-dlp command with -vU flag added (yt-dlp -vU <your command line>)
Copy the WHOLE output (starting with [debug] Command-line config) and insert it below

^^^

Can you view the instagram post in your browser without logging in? (use a private/incognito tab)

If not, then yt-dlp will not be able to download the post without login cookies. Since you have not posted a proper log, I am assuming you have reached the rate-limit -- instagram only lets you view a handful of posts while logged-out before redirecting you to the login page.

It works for me (I have not downloaded anything else from IG today). Here's my log:
```
$ yt-dlp --ignore-config -v "https://www.instagram.com/reel/Cl2N-hmMcXG/"
[debug] Command-line config: ['--ignore-config', '-v', 'https://www.instagram.com/reel/Cl2N-hmMcXG/']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.11.11 [8b64402]
[debug] Python 3.10.8 (CPython x86_64 64bit) - Linux-6.0.12-arch1-1-x86_64-with-glibc2.36 (OpenSSL 3.1.1q  5 Jul 2022, glibc 2.36)
[debug] exe versions: ffmpeg 5.1.2 (setts), ffprobe 5.1.2
[debug] Optional libraries: Cryptodome-3.12.0, brotlicffi-1.0.9.2, certifi-2022.09.24, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1723 extractors
[debug] [Instagram] Extracting URL: https://www.instagram.com/reel/Cl2N-hmMcXG/
[Instagram] Cl2N-hmMcXG: Setting up session
[Instagram] Cl2N-hmMcXG: Downloading JSON metadata
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] Cl2N-hmMcXG: Downloading 1 format(s): 0
[debug] Invoking http downloader on "https://instagram.ffcm1-2.fna.fbcdn.net/v/t66.30100-16/10000000_508048134616753_3382927852473974523_n.mp4?_nc_ht=instagram.ffcm1-2.fna.fbcdn.net&_nc_cat=101&_nc_ohc=j26h4Ll6PB4AX-pzPgu&edm=AP_V10EBAAAA&ccb=7-5&oh=00_AfDt6pus2_h07QAmyBy41HT-PlWmlhY4Eb1iLOKpGzkDjw&oe=63A5057C&_nc_sid=4f375e"
[download] Destination: Video by megansheley [Cl2N-hmMcXG].mp4
[download] 100% of   10.01MiB in 00:00:00 at 32.90MiB/s
```

**Comment by goodboi69691** [comment]
Yes, I can view the Instagram post in a private window with no problems.

**Comment by bashonly** [comment]
> Please ADD `-vU` to your instagram d/l command

post an actual log though

**Comment by goodboi69691** [comment]
> > Please ADD `-vU` to your instagram d/l command
> 
> post an actual log though

I'm sorry, I thought I did.

`[debug] Command-line config: ['-vU', 'https://www.instagram.com/reel/Cl2N-hmMcXG/']
[debug] User config "C:\Users\XXXX\AppData\Roaming\yt-dlp\config.txt": ['-o', '~/Desktop/%(title)s.%(ext)s', '-f', 'bestvideo+bestaudio[ext=m4a]', '--embed-chapters', '--add-metadata']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.11.11 [8b64402] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-93488-g52d8f35b14, ffprobe N-93488-g52d8f35b14
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1723 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.11.11, Current version: 2022.11.11
yt-dlp is up to date (2022.11.11)
[debug] [Instagram] Extracting URL: https://www.instagram.com/reel/Cl2N-hmMcXG/
[Instagram] Cl2N-hmMcXG: Setting up session
[Instagram] Cl2N-hmMcXG: Downloading JSON metadata
WARNING: [Instagram] Cl2N-hmMcXG: General metadata extraction failed (some metadata might be missing).
[Instagram] Cl2N-hmMcXG: Downloading webpage
WARNING: [Instagram] unable to extract shared data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [Instagram] Main webpage is locked behind the login page. Retrying with embed webpage (some metadata might be missing).
[Instagram] Cl2N-hmMcXG: Downloading embed webpage
WARNING: [Instagram] unable to extract additional data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
ERROR: [Instagram] Cl2N-hmMcXG: Requested content is not available, rate-limit reached or login required. Use --cookies, --cookies-from-browser, --username and --password, or --netrc (instagram) to provide account credentials
  File "yt_dlp\extractor\common.py", line 674, in extract
  File "yt_dlp\extractor\instagram.py", line 457, in _real_extract
  File "yt_dlp\extractor\common.py", line 1140, in raise_login_required`

**Comment by bashonly** [comment]
also, are you sure you're not logged into the site in that screenshot you posted? IG usually doesn't display "liked by" if you're logged out

**Comment by goodboi69691** [comment]
In the screenshot I posted I was in a private window.

**Comment by bashonly** [comment]
that didn't answer my question. you can log into sites while in private browsing mode.

regardless, the solution to your problem is in the error message:

> rate-limit reached or login required. Use --cookies, --cookies-from-browser, --username and --password, or --netrc (instagram) to provide account credentials

as explained above, IG has a rate-limit for logged out users, and it is not known exactly how this rate-limit is determined (e.g. what the limit exactly is, if it's limited per IP address or some other fingeprinting technique, etc). The only way to get around this rate-limit is to wait longer (usually ~24 hours) or use your account

**Comment by goodboi69691** [comment]
Ah I didn't know that. Sorry, I misread what you meant.
