### ISSUE TITLE
How to import a file containing video urls and download all the videos using a py file

### ISSUE THREAD

**Issue by Diaoxiaozhang** [yt-dlp/yt-dlp#5856]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.11.11** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I'm new to yt-dlp and I'm trying to write a py file to download videos. How can I implement the function of importing a file containing video urls and downloading all the videos?
I noticed that in readme there is a piece of sample code download using an info-json
```
import yt_dlp

INFO_FILE = 'path/to/video.info.json'

with yt_dlp.YoutubeDL() as ydl:
    error_code = ydl.download_with_info_file(INFO_FILE)

print('Some videos failed to download' if error_code
      else 'All videos successfully downloaded')
```
I tried this but I failed because I don't know how to write the json file. Can anyone teach me?T_T

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by dirkf** [comment]
Unless this is just an exercise for you, use `yt-dlp --batch-file ...`. Or look at how that is implemented.

The info JSON file in the example would have been generated by a previous run of the tool (read about `--write-info-json`).

**Comment by pukkandan** [comment]
> How can I implement the function of importing a file containing video urls

If you don't know how to read a text file, you should be [looking at python docs](https://docs.python.org/3/tutorial/inputoutput.html#reading-and-writing-files) or asking it in some Python forums, not here. If you are asking for exactly how yt-dlp reads it, see https://github.com/yt-dlp/yt-dlp/blob/8791e78cccd68db8161f06dc8567280e0d99a5e1/yt_dlp/__init__.py#L80-L82 https://github.com/yt-dlp/yt-dlp/blob/8791e78cccd68db8161f06dc8567280e0d99a5e1/yt_dlp/utils.py#L3127-L3143

Once you have read the URLs from the file, you can just do `ydl.download(URLS)`

**Comment by Diaoxiaozhang** [comment]
@pukkandan Thanks a lot!
