### ISSUE TITLE
How to write thumbnail to custom path with custom name via python package (NOT CMD)?

### ISSUE THREAD

**Issue by joon612** [yt-dlp/yt-dlp#5858]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.11.11** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I am trying to use `yt-dlp` python package to get video's metadata and thumbnail, I want to save metadata to the custom path with JSON format, meanwhile save the video's thumbnail to costom path with JPG format. I went through the documentation and found that there weren't many descriptions.
And also facing 429 too many request issue, I just got 15 videos metadata. I noticed someone say use `force_ipv4`, it works in seach not for get metadata.

Here is my code example:
```
    meta_dict = {}
    required_keys_list = ["id", "title", "description", "webpage_url"]
    optional_keys_list = ["duration", "thumbnail", "tags", "language"]

    ydl_opts = {'logger': CustomYDLogger(),
                'force_ipv4': True,
                'writethumbnail': True
                }

    with yt_dlp.YoutubeDL(ydl_opts) as ydl:
        try:
            info = ydl.extract_info(url, download=False)

            meta_dict = {key: info.get(key,'') for key in required_keys_list}
            for optional_key in optional_keys_list:
                if optional_key in info:
                    meta_dict.update({optional_key:info.get(optional_key)})

        except Exception as error:
            logging.error(error)

    return meta_dict
```
I really appreciate your advice. 

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

DONOT USE cmd in this case.

**Comment by pukkandan** [comment]
> I want to save metadata to the custom path with JSON format, meanwhile save the video's thumbnail to costom path with JPG format.

So, in CLI, this is what you want, correct?
```
--write-thumbnail -P thumbnail:path/to/thumbs --write-info-json -P infojson:path/to/json
```

See https://github.com/yt-dlp/yt-dlp/issues/5859#issuecomment-1363938900 for a quick way to translate CLI to API args. That gives:

```
>>> cli_to_api('--write-thumbnail', '-Pthumbnail:path/to/thumbs', '--write-info-json', '-Pinfojson:path/to/json')
{'paths': {'thumbnail': 'path/to/thumbs', 'infojson': 'path/to/json'}, 'writeinfojson': True, 'writethumbnail': True}
```

> And also facing 429 too many request issue, I just got 15 videos metadata. I noticed someone say use `force_ipv4`, it works in seach not for get metadata.

Need more information. If this is for youtube, slow down the webpage requests using `--sleep-requests`/`--sleep-subtitles`. Note that this is only a preventive measure - once you have already gotten 429, only way is to wait it out

**Comment by joon612** [comment]
Thanks for reply. Also want to convert thumbnail to JPG format, but I will also check the link later.
Yes, for YouTube, I am waiting for out(actually I'm not sure how long is enough).

**Comment by joon612** [comment]
hi @pukkandan, I hope you're well.
I tried `cli_to_api`, it works. But I got new issues:

1. I noticed I cannot custom filename (I want a id which generated by myself), they all named by title for now.
2. If I specific `download=false` in `info = ydl.extract_info(url)`, there is nothing happened, I want thumbnail, don't want video file.
3. `default = yt_dlp.parse_options([]).ydl_opts` seems to get my script options, since it raise error `OptParseError`: 
```
  File "C:\Users\USER\Miniconda3\envs\dp\lib\site-packages\yt_dlp\options.py", line 214, in error
    raise optparse.OptParseError(f'{self.get_usage()}\n{msg}' if self.usage else msg)
optparse.OptParseError: Usage: main.py [OPTIONS] URL [URL...]

main.py: error: no such option: --input_file
```

**Comment by joon612** [comment]
B.T.W. When I try to set '--match-filters', '!is_live'. I got ` 'match_filter': <function match_filter_func.<locals>._match_func at 0x00000250E52FFB80>,` from `cli_to_api`.

**Comment by pukkandan** [comment]
> B.T.W. When I try to set '--match-filters', '!is_live'. I got ` 'match_filter': <function match_filter_func.<locals>._match_func at 0x00000250E52FFB80>,` from `cli_to_api`.

Yes, match-filter accepts a function. The script is meant to be a helper, not a complete substitue for the docs. https://github.com/yt-dlp/yt-dlp/blob/8791e78cccd68db8161f06dc8567280e0d99a5e1/yt_dlp/YoutubeDL.py#L407-L415



> 1. I noticed I cannot custom filename (I want a id which generated by myself), they all named by title for now.

I don't understand

    'outtmpl': 'name.%(ext)s'


> * If I specific `download=false` in `info = ydl.extract_info(url)`, there is nothing happened, I want thumbnail, don't want video file.

Use https://github.com/yt-dlp/yt-dlp/blob/8791e78cccd68db8161f06dc8567280e0d99a5e1/yt_dlp/YoutubeDL.py#L283



> 3\. `default = yt_dlp.parse_options([]).ydl_opts` seems to get my script options, since it raise error `OptParseError`:

Appears to be a bug. Will fix

**Comment by joon612** [comment]
1. Thanks for explain. I figured out how to use it.
2. I means I want to set my custom string as filename, not a 'title'. Like top 2 files name.
![image](https://user-images.githubusercontent.com/34393671/209527000-68d60061-fc4f-458b-9b11-bfa3c4dbeb16.png)
3. Thanks!

**Comment by joon612** [comment]
I figured out about name issue. Thanks again.
Could you tell me the possible reason about this warning?  I just want one thumbnail from the video.
```
WARNING: Unable to download video thumbnail 40: HTTP Error 404: Not Found
WARNING: Unable to download video thumbnail 39: HTTP Error 404: Not Found
WARNING: Unable to download video thumbnail 38: HTTP Error 404: Not Found
WARNING: Unable to download video thumbnail 37: HTTP Error 404: Not Found
WARNING: Unable to download video thumbnail 36: HTTP Error 404: Not Found
WARNING: Unable to download video thumbnail 35: HTTP Error 404: Not Found
```

**Comment by pukkandan** [comment]
> Could you tell me the possible reason about this warning? I just want one thumbnail from the video.
> 
> ```
> WARNING: Unable to download video thumbnail 40: HTTP Error 404: Not Found
> WARNING: Unable to download video thumbnail 39: HTTP Error 404: Not Found
> WARNING: Unable to download video thumbnail 38: HTTP Error 404: Not Found
> WARNING: Unable to download video thumbnail 37: HTTP Error 404: Not Found
> WARNING: Unable to download video thumbnail 36: HTTP Error 404: Not Found
> WARNING: Unable to download video thumbnail 35: HTTP Error 404: Not Found
> ```

You can ignore them. It will retry till a working thumbnail is found

---

> 2\. I means I want to set my custom string as filename, not a 'title'. Like top 2 files name.



> 'outtmpl': 'name.%(ext)s'

**Comment by joon612** [comment]
How can I catch “too many requests “ warning when I get metadata info by API?
________________________________

**Comment by pukkandan** [comment]
catch `ExtractorError` and look at it's `.cause`
