### ISSUE TITLE
WhatsApp Status

### ISSUE THREAD

**Issue by Fidannyan** [yt-dlp/yt-dlp#5860]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [ ] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.11.11** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [ ] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

It would be nice if there was an option to download WhatsApp Status. Because I don't want to download an extra app.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
This is not possible.
```

**Comment by bibsp** [comment]
You don't need anything to download WhatsApp status.
Enable `Show hidden files` in your phone's file manager app.
Then inside internal storage go to `WhatsApp>Media>. Statuses`.

All statuses are stored here for 24 hours.
