### ISSUE TITLE
Can Google detect the use of yt-dlp?

### ISSUE THREAD

**Issue by maz22x** [yt-dlp/yt-dlp#5862]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.11.11** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Can Google know if one is using yt-dlp based on how requests are formulated? For example, are there slight differences between requests headers or bodies compared to a normal browser/device? Or can they detect missing other traffic like ads?

Maybe you can add this answer to the FAQ.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by hmadybinghith1999** [comment]
ً

**Comment by dirkf** [comment]
Read https://en.wikipedia.org/wiki/Device_fingerprint.

**Comment by pukkandan** [comment]
Can they? yes. Do they? You'd have to ask them
