### ISSUE TITLE
How to avoid downloading the same video with different file extension (remux) in yt-dlp

### ISSUE THREAD

**Issue by Fallenap** [yt-dlp/yt-dlp#5864]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.11.11** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

This is the command I'm using to download my videos: yt-dlp --remux "webm>avi" -o "%(upload_date)s %(title)s.%(ext)s" -f bv[format!*=248] -a List.txt

I have text files with tons of links So, if the videos are already downloaded in avi format yt-dlp doesn't detect it, instead it downloads the video again creating a webm.part file, then it remuxes the file and overwrites the old avi downloaded video

I know the cause of this is the ".%(ext)s" command but I cannot remove that part

So what I need is for yt-dlp to recognize the file name instead of the extension, because from time to time I will need to check those video lists again with yt-dlp, to check for missing videos, or if I add new link videos to those lists

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
Use `--download-archive`

**Comment by Fallenap** [comment]
The command works great, I just had to download everything again, but It is really helpful
also I don't have to wait for it to check each video
Although it won't help if there is a missing video I realized that the probability of that happening is really small. So this helped me so much thank you pukkandan

**Comment by pukkandan** [comment]
> I just had to download everything again

This could have been avoided with `--skip-download --force-write-archive`

**Comment by Fallenap** [comment]
Well, lesson learned.
Sorry If I ask here...
If I have a 10 mb speed connection, would be better to open three windows each one with limit rate of 3.3M
Or two windows with limit rate of 5M each one
Or would be better to open only one window with yt-dlp?
Or it doesn't have any importance?
I don't want corrupt files or failures of course
Thank you pukkandan

**Comment by pukkandan** [comment]
Never run multiple instances to download the same video. For multiple videos, it depends on the website, any other options used, and various other factors. I suggest you test it yourself and decide

**Comment by Fallenap** [comment]
Hey pukkandan I've just re-read the README but find nothing so probably the answer will be no, but is there a way to write the file name or the youtube video name in the archive file? (Along the recorded IDs)
I think that is the only thing I have left to know
Thank you so much

**Comment by pukkandan** [comment]
https://github.com/yt-dlp/yt-dlp/issues/1762#issuecomment-976441715

**Comment by Fallenap** [comment]
Hey thank you, I've just found out how to search words or letters in a text file so if I have missing videos I just have to search the IDs I want to delete, I was making things harder
