### ISSUE TITLE
[viki:channel] Unable to download JSON metadata: HTTP Error 403

### ISSUE THREAD

**Issue by kerohero** [yt-dlp/yt-dlp#587]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running yt-dlp version **2021.07.24**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

[viki:channel] Logging in
[viki:channel] 32311c: Downloading channel JSON
[download] Downloading playlist: Strong Woman Do Bong Soon
[viki:channel] 32311c: Downloading Episodes JSON page 1
WARNING: [viki:channel] Unable to download JSON metadata: HTTP Error 403: Forbidden
[viki:channel] 32311c: Downloading Movies JSON page 1
WARNING: [viki:channel] Unable to download JSON metadata: HTTP Error 403: Forbidden
[viki:channel] 32311c: Downloading Clips JSON page 1
WARNING: [viki:channel] Unable to download JSON metadata: HTTP Error 403: Forbidden
[viki:channel] 32311c: Downloading Trailers JSON page 1
WARNING: [viki:channel] Unable to download JSON metadata: HTTP Error 403: Forbidden
[viki:channel] playlist Strong Woman Do Bong Soon: Downloading 0 videos
[download] Finished downloading playlist: Strong Woman Do Bong Soon

## Description

I'm trying to download a series from Viki, but as you can see I'm getting "HTTP Error 403: Forbidden"
Here is the code I'm using if it helps

`import yt_dlp

url = "https://www.viki.com/tv/32311c-strong-woman-do-bong-soon"

ydl_options = {
    "username": '.................',
    "password": '..................',
    "playlist_items": "1, 3, 3",
    "writesubtitles": True,
    "subtitleslangs": ['en'],
    "subtitlesformat": "srt",
    "format": "best[height=720]",
}

yt_dlp.std_headers["x-viki-app-ver"] = "2.2.5.1428709186"
yt_dlp.std_headers["x-viki-as-id"] = "100005a"
with yt_dlp.YoutubeDL(ydl_options) as ydl:
    ydl.download([url])
`

**Comment by october262** [comment]
try using the authenticated cookies option instead of username & password

**Comment by zackmark29** [comment]
The updated codes for viki doesn't need custom headers. Please read first the changelogs.
https://github.com/yt-dlp/yt-dlp/releases/tag/2021.07.21

**Comment by pukkandan** [comment]
Try removing these

```
yt_dlp.std_headers["x-viki-app-ver"] = "2.2.5.1428709186"
yt_dlp.std_headers["x-viki-as-id"] = "100005a"
```

**Comment by kerohero** [comment]
Yeah removing the headers solved the error above "HTTP Error 403"
But now I'm getting "ERROR: Requested format is not available"

**Comment by kerohero** [comment]
Changing from "format": "best[height=720]" to "format": "bestvideo" 
Solved this issue, Thanks everyone for the support <3
