### ISSUE TITLE
python custom thumbnail format

### ISSUE THREAD

**Issue by jw-star** [yt-dlp/yt-dlp#5873]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.11.11** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

This is the command line way to download jpg normally
```
yt-dlp --skip-download --write-thumbnail --convert-thumbnails jpg 'https://www.youtube.com/watch?v=rNC2mmliL5I'
```
How to code it

```
ydl_optssx = {
    'format': 'bestvideo[height<=1080][ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best',
    "outtmpl": "downloads/%(id)s.%(ext)s",
    "geo_bypass": True,
    "nocheckcertificate": True,
    'quiet': True,
    'no_warnings': True,
    # 'external_downloader': 'aria2c',
    # 'external_downloader_args': ['-x', '16', '-s', '16', '-j', '16', '-k', '1M'],
    'writethumbnail': True,
    'convert_thumbnails': 'jpg', # How to configure here
    'skip_download': True
}
    ydl = YoutubeDL(ydl_optssx)
    info = ydl.extract_info(url, download=False)
    # print(info['title'])
    error_code = ydl.download(url)
```

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
There is no way to select thumbnails. See https://github.com/yt-dlp/yt-dlp/issues/237

You could however get `thumbnails` from the infodict and download the one you want yourself

**Comment by bashonly** [comment]
```diff
 ydl_optssx = {
     'format': 'bestvideo[height<=1080][ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best',
     "outtmpl": "downloads/%(id)s.%(ext)s",
     "geo_bypass": True,
     "nocheckcertificate": True,
     'quiet': True,
     'no_warnings': True,
     # 'external_downloader': 'aria2c',
     # 'external_downloader_args': ['-x', '16', '-s', '16', '-j', '16', '-k', '1M'],
     'writethumbnail': True,
-    'convert_thumbnails': 'jpg', # How to configure here
+    'postprocessors': [{'format': 'jpg',
+        'key': 'FFmpegThumbnailsConvertor',
+        'when': 'before_dl'}],
     'skip_download': True
 }
 ```

**Comment by jw-star** [comment]
thanks

**Comment by pukkandan** [comment]
oh.. I misunderstood the question 🤦
