### ISSUE TITLE
Special characters

### ISSUE THREAD

**Issue by noname278** [yt-dlp/yt-dlp#5892]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.11.11** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

**VERBOSE OUTPUT NOT NEEDED; NOT A TECHNICAL ISSUE**

Hello. Since an update to yt-dlp, I get these characters in video titles (This⧹is⧸a：video＊with？the＂symbols｜ [OORigQYUuoI].mp4). How can I disable them? (Ideal solution for me: replace with underscores, example: This_is_a_video_with_the_symbols_ [OORigQYUuoI]). I want to keep spaces. I only want to get rid of these characters. [For me, they look wrong](https://imgur.com/a/SSEwCfj). [This is the video with the characters (uploaded by me as a test)]: (https://www.youtube.com/watch?v=OORigQYUuoI). 

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by noname278** [comment]
[This is the video with the characters (uploaded by me as a test)]:(https://www.youtube.com/watch?v=OORigQYUuoI).

**Comment by pukkandan** [comment]
See pinned issues! 
![image](https://user-images.githubusercontent.com/6623388/209800416-05e82266-8eec-402d-a0c9-c4a1af922925.png)

**Comment by noname278** [comment]
Thank you for showing me! I looked at least 3 times at the pinned issues, but I couldn't see it.

**Comment by pukkandan** [comment]
Do you have any suggestion for what I could change so you could have found it easier?
