### ISSUE TITLE
playlist_index should always use leading zeros if total playlist length requires it (e.g. 10+ or 100+)

### ISSUE THREAD

**Issue by porg** [yt-dlp/yt-dlp#5895]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.11.11** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

## Proposal

- 👉  If a playlist requires leading zeros (=padding) for the `playlist_index` as the playlist has 10+ or 100+ etc items, then that padding shall be applied regardless whether you select only a subset for downloading with `--playlist-items`, which itself could suffice with no padding (e.g. selecting 1-3 from a 50 items playlist) or fewer padding (selecting 1-20 from a 120 items playlist).

## UX Design Rationale
- ✅ That way if a user decides to download further items, as the first few videos were ok/satisfying,  elder videos (e.g. <10 videos) and further downloaded videos (e.g. above the 10+ index) fit together neatly with a uniform naming.
- ✅ If downloading yet another batch later (e.g. above the 100+ index) the naming of the newer videos still fits.
- ℹ️ Only in the case of a dynamic playlist, whose amount changes drastically over time, with a 10+ or 100+ or 1000+ jump occurring, the padding would be outdated for later playlist download invocations.
  - But this is a total edge case. Batch renaming your elder files is acceptable then.
  - For 99% of the use cases the proposed behavior would ensure a friction free uniform naming.
  - I propose this to be the new default behavior which will satisfy 90% of users and use cases, and those rare users or edge cases could then use the explicit options:
    - `--leading-zeros-none` which totally deactivates padding
    - `--leading-zeros-minimally` which uses as little padding as your selection requires, not as much as the total playlist length would require.

## Searching for "leading zeros" in the manpage of yt-dlp yields exactly two consecutive paragraphs

> playlist_autonumber (numeric): Position of the video in the playlist download queue padded with leading zeros according to the total length of the playlist.
>
> playlist_index (numeric): Index of the video in the playlist padded with leading zeros according the final index.

## Reproduction

1. I plan to download a playlist with 19 videos in it.

2. I download videos 1-3.
    - User Intent: Check results, or first watch to decide whether I like the content.
    - If ok download further videos from that list. Also from index 10+.

          $ yt-dlp PLRERRyVDa16P34C-ffyoOm0C28ts-O-Ph --playlist-items "1:3" \
          -o "Series Name/Series Name - s01e%(playlist_index)s - %(title)s.%(ext)s"

- **Actual**: The `playlist_index` for the playlist items 1 to 3 is without **leading zeroes (=padding)**.

- **Expected**: As the playlist has 19 items in total, also a partial download of 1-3 already applies **leading zeroes (=padding)** on the `playlist_index`. Should you later download from index 10+ your previously downloaded files will fit into the naming pattern already. I should not need to be forced to download 10+ items just to get zero padding.

- **Failed workaround**: Once I also tried `--playlist-items "01:03"` with the intent to explicitly hint yt-dlp that I 'd like leading zeros. Made no difference. Same outcome.

3. I download videos 9-11.

        $ yt-dlp PLRERRyVDa16P34C-ffyoOm0C28ts-O-Ph --playlist-items "9:11" \
        -o "Series Name/Series Name - s01e%(playlist_index)s - %(title)s.%(ext)s"

4. I check the outcome.

        $ ls -lR "Series Name"
        'Series Name':
        total 77M
        -rw-rw-r--+ 1 me users 12M 13.05.2019 10:12:22 'Series Name - s01e09 - Sloth.webm'
        -rw-rw-r--+ 1 me users 12M 30.12.2019 18:30:50 'Series Name - s01e10 - Cow.webm'
        -rw-rw-r--+ 1 me users 11M 13.04.2022 02:45:44 'Series Name - s01e11 - Anglerfish.webm'
        -rw-rw-r--+ 1 me users 13M 16.04.2022 16:38:25 'Series Name - s01e1 - Zebra.webm'
        -rw-rw-r--+ 1 me users 14M 15.04.2022 22:03:09 'Series Name - s01e2 - Ant.webm'
        -rw-rw-r--+ 1 me users 19M 23.12.2019 22:16:36 'Series Name - s01e3 - Lion.webm'

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
This is a proposal and not a bug report. Hence no detailed log is necessary here. You can try it out yourself with the given playlist.

That you get at least the basic system info, I just ran `yt-dlp -vU` itself, without any concrete command.

yt-dlp -vU
[debug] Command-line config: ['-vU']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.11.11 [8b644025b] (debian*)
[debug] Python 3.9.2 (CPython armv7l 32bit) - Linux-5.4.199-odroidxu4-armv7l-with-glibc2.31 (OpenSSL 1.1.1n  15 Mar 2022, glibc 2.31)
[debug] exe versions: ffmpeg 4.3.5-0, ffprobe 4.3.5-0, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.9.7, brotli-1.0.9, certifi-2020.06.20, mutagen-1.45.1, sqlite3-2.6.0, websockets-8.1, xattr-0.9.7
[debug] Proxy map: {}
[debug] Loaded 1723 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.11.11, Current version: 2022.11.11
yt-dlp is up to date (2022.11.11)
```

**Comment by Lesmiscore** [comment]
You can pad the numbers by like `02s`, for example `%(playlist_index)02s`.

You can change 2 above to pad to an another length, e.g. `05s`, `020s`

**Comment by porg** [comment]
1) Cool. Will look into this to tweak it where necessary.
2) Nevertheless the default behavior should be safe and ultra compatible for the average user. So that proposal sill stands.

**Comment by pukkandan** [comment]
When downloading a playlist partially, yt-dlp often maynot even know the total number of items in the PL. Using the last index was an intentional design decision to account for this. 

Besides, padding based on total number doesn't necessarily fix your issue. What happens if new items are added to the playlist b/w the different runs? The best way to achieve what you want is to set a large enough padding using the numeric formatting options. Personally, I use `%(playlist_index)05d`

**Comment by porg** [comment]
@pukkandan wrote
> What happens if new items are added to the playlist b/w the different runs?

My initial report covered this:
> - Only in the case of a dynamic playlist, whose amount changes drastically over time, with a 10+ or 100+ or 1000+ jump occurring, the padding would be outdated for later playlist download invocations.

And my estimation was:
>   - But this is a total edge case. Batch renaming your elder files is acceptable then.

Anyhow, you decided this to be a **wontfix**, so I have to set a large enough padding, for easy download continuation of playlists with guaranteed uniform index naming.
- This number formatting syntax like `02s`, `05s` and `020s` seems cryptic to me, not knowing any such transformation syntax in general.
- manpage chapter **OUTPUT TEMPLATE** mentions various placeholder operations, but not how number formatting works, especially in terms of padding.
  - Would appreciate if that is explained in the manpage.
  - And if you could also explain it here or send a link to a documentation. Thanks!

**Comment by pukkandan** [comment]
> For numeric sequences you can use [numeric related formatting](https://docs.python.org/3/library/stdtypes.html#printf-style-string-formatting); e.g. `%(view_count)05d` will result in a string with view count padded with zeros up to 5 characters, like in `00042`.

For your usecase, you don't even need to read the link though. The given example covers it

**Comment by pukkandan** [comment]
> > What happens if new items are added to the playlist b/w the different runs?
> 
> My initial report covered this:
> 
> > * Only in the case of a dynamic playlist, whose amount changes drastically over time, with a 10+ or 100+ or 1000+ jump occurring, the padding would be outdated for later playlist download invocations.
> 
> And my estimation was:
> 
> > * But this is a total edge case. Batch renaming your elder files is acceptable then.

Missed it. The other reason still stands though

> When downloading a playlist partially, yt-dlp often maynot even know the total number of items in the PL.

There's also backward compatibility concerns for such a change

**Comment by porg** [comment]
OMG, the given URL is heavy technical reading 😮  — I'm a pro user / scripter, but no developer 😉

As I understand that syntax, e.g.`05d`
- First position `0` designates the character used for padding, which is `0`, a "zero".
- Second position `5`: What length the index shall have, e.g. for 5 this means a min of 00000 and a max of 99999.
- Third position `d`: This formatting applies for "digits".

If I understood that correctly then:
- `02d` to get 00-99
- `03d` to get 000-999
- `04d` to get 0000-9999

Correct?

**Comment by pukkandan** [comment]
yes

**Comment by porg** [comment]
1. Thanks for the support here!
2. Feel free to copy/paste my explanation into the manpage.
  - Ofc with adaptations as you please it.
  - But circa in that style: Comprehensible to average users + the given 3 concrete examples, so to have common needed formatting right away, and to confirm the reading comprehension of the user.

**Comment by porg** [comment]
Wanted to try out `%(playlist_index)02d` and its variants `03d` and `04d`, but now even the base `%(playlist_index)s` didn't work out:

     --playlist-items "1:3" -o "Series Name/s01e%(playlist_index)s - %(title)s.%(ext)s"

- Now gives `s01eNA` for all 3 shows. That same command gave at least `s01e1` `s01e2` `s01e3` yesterday. I ran it by going back in my command history, so it must be verbatim to what worked yesterday. Only the working directory was different.. Strange… Any ideas?

**Comment by pukkandan** [comment]
You sure the URL passed is of a playlist? Show log

**Comment by porg** [comment]
The same playlist `PLRERRyVDa16P34C-ffyoOm0C28ts-O-Ph` as used yesterday as featured in my initial post.

**Comment by porg** [comment]
✅ Was a false alarm!
-  I had copied the command not from up/down-arrow-kay history but from `history` which uses `less` which inserts linebreaks in long command lines. Interestingly it still partially worked despite the linebreak in between.
- After removing the (invisible linebreak) it worked normal again.
- `%(playlist_index)03d` created `s01e001`
