### ISSUE TITLE
Authentication fails when using AT&T TV login (ATTOTT)

### ISSUE THREAD

**Issue by tv21** [yt-dlp/yt-dlp#590]
## Checklist

- [ ] I'm reporting a broken site support issue
- [X] I've verified that I'm running yt-dlp version **2021.07.24**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar bug reports including closed ones
- [X] I've read bugs section in FAQ

## Verbose log

```
[debug] Command-line config: ['-v', '--ap-mso', 'ATTOTT', '--ap-username', 'PRIVATE', '--ap-password', 'PRIVATE', 'https://disneynow.com/shows/bunkd/season-05/episode-19-a-star-is-torn/vdka23900520']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] yt-dlp version 2021.07.24 (zip)
[debug] Python version 3.8.10 (CPython 64bit) - Linux-5.4.0-80-generic-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg N-53917-g5ff2ff6bd9-static, ffprobe N-53917-g5ff2ff6bd9-static
[debug] Proxy map: {}
[debug] [Go] Extracting URL: https://disneynow.com/shows/bunkd/season-05/episode-19-a-star-is-torn/vdka23900520
[Go] vdka23900520: Downloading JSON metadata
[Go] VDKA23900520: Downloading Provider Redirect Page
[Go] VDKA23900520: Downloading Provider Login Page
ERROR: Unable to extract post url; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/localyt-dlp/yt_dlp/YoutubeDL.py", line 1152, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/localyt-dlp/yt_dlp/YoutubeDL.py", line 1177, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/localyt-dlp/yt_dlp/extractor/common.py", line 572, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/localyt-dlp/yt_dlp/extractor/go.py", line 238, in _real_extract
    auth = self._extract_mvpd_auth(
  File "/usr/local/bin/localyt-dlp/yt_dlp/extractor/adobepass.py", line 1580, in _extract_mvpd_auth
    mvpd_confirm_page_res = post_form(provider_login_page_res, 'Logging in', {
  File "/usr/local/bin/localyt-dlp/yt_dlp/extractor/adobepass.py", line 1376, in post_form
    post_url = self._html_search_regex(r'<form[^>]+action=(["\'])(?P<url>.+?)\1', form_page, 'post url', group='url')
  File "/usr/local/bin/localyt-dlp/yt_dlp/extractor/common.py", line 1133, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/usr/local/bin/localyt-dlp/yt_dlp/extractor/common.py", line 1124, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
yt_dlp.utils.RegexNotFoundError: Unable to extract post url; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
```

## Description

This is not an issue with any one specific site, it is instead an authentication issue, so the above is just an example, I could have picked any show on any supported site and would have had the same problem.  From what I have read, what is now called AT&T TV was formerly DIRECTV NOW and was supported using "--ap-mso ATTOTT" option.  However, since they changed to AT&T TV, authentication apparently hasn't worked.

Things that do NOT work (at least not for me):

- Using the --cookies option and a valid cookies.txt file.  You get: "ERROR: This video is only available for users of participating TV providers. Use --ap-mso to specify Adobe Pass Multiple-system operator Identifier and --ap-username and --ap-password or --netrc to provide account credentials."

- Getting the source code and changing the adobepass.py file (in the extractors directory), specifically these lines near the top of the file:
```
    'ATTOTT': {
        'name': 'DIRECTV NOW',
        'username_field': 'email',
        'password_field': 'loginpassword',
    },
```
Perhaps I did not hit the right combination but I did inspect the elements on the login page in my web browser and it appears that 'username_field' should be 'userID' (not 'email') and 'password_field' should be just 'password', not 'loginpassword', but I can't be certain.  I also tried changing the name field to 'AT&T TV'.  I also tried a few variations but nothing seemed to work.  I can see that it is failing at the point of trying to authenticate but I know very little about programming or about effectively using browser tools, so I'm afraid I've reached the limit of my diagnostic abilities.  If you are in the USA you can get a free two week trial account, although you don't need even that to get to the login screen.  Playback works fine in the browser using the same user ID and password, so I would hope this isn't a difficult fix. If you have any suggestions for anything else I can try, I'd appreciate hearing them.

**Comment by shirt-dev** [comment]
You will need to provide an account if you want this to be fixed @tv21.

**Comment by tv21** [comment]
> You will need to provide an account if you want this to be fixed @tv21.

Unfortunately the problem with that is that it not only gives you open access to the account, but also to all the personal and billing information associated with the account, including payment info.  That is information I would not even give to most members of my family, let alone someone on the Internet.  No offense intended, but other that by your work on this software I don't know anything about you.  You might be the most trustworthy guy in the world (and I hope you are) but I have no way of knowing that.  Again, no offense intended, I would have the same reservations about giving this information to nearly every other person on the Internet, including almost all of the people that I have met personally.

So my question is this, if you went to a provider site (such as the link I tried to use in my original post) and attempted to do a login and specified AT&T TV (or whatever the DirectTV equivalent is if they have changed the name) would you have any way of observing what is being requested and seeing how that differs from what the ATTOTT code is expecting to see?  I have this feeling that it's just a matter of a changed string somewhere, for example maybe instead of "email" or "loginpassword" different strings are being used.  Thing is, if you can even take a educated guess as to what should be changed, I am more than willing to test it to see if it works.  I know how to run the program using the Python source code (even if I don't understand the code itself), so I can easily test any changes to the code if you can just tell me which file to change, and give me some hint as to what to try changing.  That way I would not have to reveal my login information, and I will be sure to let you know if it works.

But also, I had another thought.  Would it be possible to make yt-dlp accept cookies.txt files from more services?  I have no idea why with some sites you can use a cookies files and others you can't - it it just that the various extractors were never coded to accept the cookies files, or is it really that you just absolutely can't use a cookies file with certain  online services that require a provider login?  For example, would it be possible to make the go.py extractor accept a cookies file?  The nice thing about using a cookies files is that (I assume) it contains all the authentication information that the site needs.  What I find interesting is that I can log into the AT&T TV account in a browser window and even if I come back days later and attempt to watch something, it won't ask for my login info again, as long as I haven't cleared the cookies.  So this is why I would assume that a cookies file would include everything you need to do a successful authentication.  But attempting to use a cookies file with yt-dlp for the example link above gets me nowhere, and I don't know why, when that technique works fine on some other services.  Can you please enlighten us on why this is, and could the use of a cookies file possibly be expanded to more extractors and services?

**Comment by shirt-dev** [comment]
Closing this issue as ATT TV is not ATTOTT, and you have failed to provide the needed information to resolve this.

**Comment by tv21** [comment]
Um, shirt-dev, who are _you_?  I thought I was talking to pukkandan!  And yes, AT&T TV is ATTOTT, it was originally DirecTV Now I believe, then it was renamed to AT&T TV and at some point given the label ATTOTT (which I assume stands for AT&T's Over-The-Top service, to distinguish it from AT&T U-Verse and other services that were part of AT&T's wireline or satellite services.  And now it has come full circle and AT&T TV is now DirecTV something or other again, but many sites still refer to it as AT&T TV.

Anyway, I wish you had let pukkandan respond to this, especially since you seem to be under some misconceptions.  And I really would like to know about the cookies file thing.  But I'll create another issue for that.

**Comment by shirt-dev** [comment]
> Um, shirt-dev, who are you? I thought I was talking to pukkandan! And yes, AT&T TV is ATTOTT, it was originally DirecTV Now I believe, then it was renamed to AT&T TV and at some point given the label ATTOTT (which I assume stands for AT&T's Over-The-Top service, to distinguish it from AT&T U-Verse and other services that were part of AT&T's wireline or satellite services. And now it has come full circle and AT&T TV is now DirecTV something or other again, but many sites still refer to it as AT&T TV.
> 
> Anyway, I wish you had let pukkandan respond to this, especially since you seem to be under some misconceptions. And I really would like to know about the cookies file thing. But I'll create another issue for that.

I believe I'm the one who initially replied to this issue, pukkandan simply added the account-needed label.

ATT TV differs from ATT TV Now (formerly DirecTV Now), which was discontinued. Their API is different from ATT TV Now. The fact is that credentials are needed to add support for an AdobePass MSO. Once you provide those credentials, then we can look into adding support.

As for the question regarding the cookies, that is due to the nature of how the AdobePass authentication process works.

**Comment by tv21** [comment]
I think the reason most people would be reluctant to provide their login credentials is that it not only gives open access to their account, but also to all the personal and billing information associated with the account, including payment info.

I had been told in a forum thread that AT&T TV was the same as ATT Now and the former DirecTV Now, but maybe I was given wrong information.  If there is any way at all that you think you might be able to add support just from what you know about the service, I'd be happy to test it and report back the results.  But I cannot give you any credentials because the account is not in my name and the person whose name it is in (another family member) absolutely forbids it.

**Comment by pukkandan** [comment]
No, it is not possible to write an extractor without an account

**Comment by tv21** [comment]
shirt-dev, just FYI I was talking to someone else this afternoon who was looking at the inspector for another video on the same site as the one I mentioned in my original request, and he says that when he selects AT&T TV as the provider he can see ATTOTT in the inspector, and if you click on it, it shows this image:

https://cdn1.edgedatg.com/aws/v2/abc/consolidatedMVPDs/67883574-d995-4ec8-b85a-4c9b0bb058ac/454d1e59105976498d191c73d3b093c4/528x132-Q80_454d1e59105976498d191c73d3b093c4.png

So he thinks you are wrong about AT&T TV not using the ATTOTT MSO designation.  And that brings me back to the thought that if the ATTOTT extractor really is the correct one, then all that needs to be determined is what has changed in the login procedure.  And to me it would seem that this is information that should be available BEFORE a login and password is entered.  And that is why I said that if you have any thoughts at all on what may need to be changed, I'd be happy to try them.

The person I was talking to also said it sounded like you either just don't want to make this work, or that you really want an AT&T TV login for some reason, even though it would provide access to all the information related to the account and would therefore be a huge security failure for the person that provided it.  I do not know if either of those are true, I just know that I cannot give you the login that I use, I've been absolutely forbidden from doing that by the account holder.

**Comment by shirt-dev** [comment]
I could be wrong about ATTOTT, but that does not change that an account is needed to write an extractor.

Just so you're aware, you're coming across as very rude and confrontational. Do I need to remind you that this is free software that we develop in our spare time?

You're welcome to find someone else to write you  an extractor, but after your behavior, I wouldn't write it even if you provided the required account.

**Comment by tv21** [comment]
Exactly what makes you think you can demand users provide their private account details and they will not have reservations about doing so?  Something is very fishy about this, and I think what you really don't like is me pointing out that no sane person would just hand over their account details to someone they've never met on the Internet.  You find it "rude and confrontational" that I suggest that is an unreasonable demand.  I just don't know what to say to that, because I guess you must be living in an alternate reality where everyone is trustworthy, but clearly you never had any intention of trying to help unless I could meet that insane demand, so I guess I haven't lost a thing by you being pissed off about it.

**Comment by pukkandan** [comment]
Nobody is demanding that you provide account details. We are simply saying that we cannot fix the login unless we have access to an account. Since we dont have an account ourselves, you either need to give account details, or fix it yourself and make a PR
