### ISSUE TITLE
How to get desired specific format resolution codec

### ISSUE THREAD

**Issue by Fallenap** [yt-dlp/yt-dlp#5903]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.11.11** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Having lists of urls with old and new videos and all with different resolutions
I need the command to get the best video "bv" with the codec av01
-Except for 1080p 60fps I need it always with vp9 codec of which format is 303
-And also for 1080p 30, 24fps I need it always with h264 (or avc1) codec of which format is 137
of course old videos doesn't have av01 codec for which I need it to automatically download the vp9 version or the h264 version if vp9 isn't available
(But always taking into account the exceptions I made)
-I don't want to re-encode any video or change its container or format

I've been trying different commands with sorting also but didn't manage it so I hope it is possible
Edit: I also just noticed that HDR videos name codec is vp9.2 I would also want yt-dlp to automatically choose this codec if av01 isn't avaible

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
> I've been trying different commands with sorting also but didn't manage it so I hope it is possible

Would have been helpful if you showed us what u tried...

> I need the command to get the best video "bv" with the codec av01
> of course old videos doesn't have av01 codec for which I need it to automatically download the vp9 version or the h264 version if vp9 isn't available
> I don't want to re-encode any video or change its container or format
> I also just noticed that HDR videos name codec is vp9.2 I would also want yt-dlp to automatically choose this codec if av01 isn't avaible

`-S res,vcodec` will do exactly this

> -Except for 1080p 60fps I need it always with vp9 codec of which format is 303
> -And also for 1080p 30, 24fps I need it always with h264 (or avc1) codec of which format is 137

`-S` however cannot handle specific exceptions like this, so we get the help of `-f` for these:

    -f (bv[height>1080]/303/137/bv[height<1080])+ba

Combining these should get you exactly what you asked for

**Comment by Fallenap** [comment]
yes it gave me exactly what I asked, you are the goat pukkandan
I just need to know this, in the case that I would want to make the exception only for the format 137 which is the right command?
I managed to do it with the same command changing 303 to 399 but I think the command is large for only one exception, is there another short command?
Thank you

**Comment by pukkandan** [comment]
> I think the command is large for only one exception, is there another short command?

No



> It didn't take on account a video with the format 303, not even the next one, it did go to the 720p 60 fps vp9 version of the video so my try was a total failure

I don't understand, pls elaborate

**Comment by Fallenap** [comment]
Ok... I want almost the same, the best video with the codec av01 but now making only this exception :
-for 1080p 30, 24fps I need it always with h264 (or avc1) codec of which format is 137

In order to manage this I tried modifying the command you gave me, changing from 303 (1080p 60fps vp9) to 399 (1080p 60fps av01) it works if videos have av01 codec but with videos that only has vp9 avaible this command skips the formats 303 and 299 (1080p 60fps h264) and downloads the 720p 60fps version

So this is the reason why now I want to make only this exception:
-always 137 for 1080p

-All the resolutions higher or lower with av01 codec, if av01 is not avaible then automatically download vp9, and h264 if vp9 is not avaible
But always 137 for 1080p

**Comment by pukkandan** [comment]
> So this is the reason why now I want to make only one exception: -always 137 for 1080p
> 
> -All the other resolutions higher or lower with av01 codec, if av01 is not avaible then automatically download vp9, and h264 if vp9 is not avaible

    -S res,ext -f "(bv[height>1080]/137/bv[height<1080])+ba"

**Comment by Fallenap** [comment]
I copy pasted the command, it doesn't work, it skips the first three formats

**Comment by pukkandan** [comment]
show verbose

**Comment by Fallenap** [comment]
[debug] Command-line config: ['-vU', '-S', 'res,ext', '-f', '(bv[height>1080]/137/bv[height<1080])+ba', 'https://www.youtube.com/watch?v=hVS5TnrMZK4']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.11.11 [8b64402] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22621-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 2022-12-29-git-d39b34123d-full_build-www.gyan.dev (setts), ffprobe 2022-12-29-git-d39b34123d-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1723 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2022.11.11, Current version: 2022.11.11
yt-dlp is up to date (2022.11.11)
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=hVS5TnrMZK4
[youtube] hVS5TnrMZK4: Downloading webpage
[youtube] hVS5TnrMZK4: Downloading android player API JSON
[debug] Loading youtube-nsig.21149d65 from cache
[debug] [youtube] Decrypted nsig kdTTnopXzKR_aJg1j => o8F5Vq8nP1itQg
[debug] Sort order given by user: res, ext
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, res, vext, aext, quality, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, hasaud, id
[info] hVS5TnrMZK4: Downloading 1 format(s): 298+140
[debug] Invoking http downloader on "https://rr1---sn-o0x85uxa-a2cl.googlevideo.com/videoplayback?expire=1672560837&ei=ZeywY9rgFNCF1sQP4YKJgA4&ip=186.2.95.248&id=o-AAJmZbxjFuXR8HZaUaQ4rr2ef7i83geMEuwo_EoHDQXu&itag=298&source=youtube&requiressl=yes&mh=Ov&mm=31%2C29&mn=sn-o0x85uxa-a2cl%2Csn-njaeyn7s&ms=au%2Crdu&mv=m&mvi=1&pcm2cms=yes&pl=20&initcwndbps=341250&spc=zIddbGTnmvSFf05JJKAnAPkcv3tl_e0&vprv=1&svpuc=1&mime=video%2Fmp4&gir=yes&clen=5259720&dur=23.033&lmt=1666027502056756&mt=1672538930&fvip=2&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=1432434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRAIgB3shmX0IC4gkAWtJHAhDpFtfq9q23pMeZcyANTd5lhICIBsFTtZT5syvPHpMz6OH3gIjIqxdP0XOVQMlffrEjLe2&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgIPLF1r7AEAzOWSxhDsMGaer8Y7SUjSIqKc_DeAXEtY4CIFJ7WVZNNY1App3y87YUvzuni1FXGPVCWRyrNNDFTOM3"
[debug] File locking is not supported. Proceeding without locking
[download] Destination: Blender 75 000 particles fluid simulation 1080p⧸60fps [hVS5TnrMZK4].f298.mp4
[download] 100% of    5.02MiB in 00:00:03 at 1.49MiB/s
[debug] Invoking http downloader on "https://rr1---sn-o0x85uxa-a2cl.googlevideo.com/videoplayback?expire=1672560837&ei=ZeywY9rgFNCF1sQP4YKJgA4&ip=186.2.95.248&id=o-AAJmZbxjFuXR8HZaUaQ4rr2ef7i83geMEuwo_EoHDQXu&itag=140&source=youtube&requiressl=yes&mh=Ov&mm=31%2C29&mn=sn-o0x85uxa-a2cl%2Csn-njaeyn7s&ms=au%2Crdu&mv=m&mvi=1&pcm2cms=yes&pl=20&initcwndbps=341250&spc=zIddbGTnmvSFf05JJKAnAPkcv3tl_e0&vprv=1&svpuc=1&mime=audio%2Fmp4&gir=yes&clen=374735&dur=23.080&lmt=1666027009429793&mt=1672538930&fvip=2&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=1432434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRAIgdm-7Kek5GXUDG7aDbgV3sYNs8FS_iq9SAVpaZYAttp0CIBPvH0hdFAqNNdpXl2sCwImyPDKmpDyKdcjs_sNXVn6w&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgIPLF1r7AEAzOWSxhDsMGaer8Y7SUjSIqKc_DeAXEtY4CIFJ7WVZNNY1App3y87YUvzuni1FXGPVCWRyrNNDFTOM3"
[download] Destination: Blender 75 000 particles fluid simulation 1080p⧸60fps [hVS5TnrMZK4].f140.m4a
[download] 100% of  365.95KiB in 00:00:00 at 461.79KiB/s
[Merger] Merging formats into "Blender 75 000 particles fluid simulation 1080p⧸60fps [hVS5TnrMZK4].mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:Blender 75 000 particles fluid simulation 1080p⧸60fps [hVS5TnrMZK4].f298.mp4" -i "file:Blender 75 000 particles fluid simulation 1080p⧸60fps [hVS5TnrMZK4].f140.m4a" -c copy -map "0:v:0" -map "1:a:0" -movflags "+faststart" "file:Blender 75 000 particles fluid simulation 1080p⧸60fps [hVS5TnrMZK4].temp.mp4"
Deleting original file Blender 75 000 particles fluid simulation 1080p⧸60fps [hVS5TnrMZK4].f298.mp4 (pass -k to keep)
Deleting original file Blender 75 000 particles fluid simulation 1080p⧸60fps [hVS5TnrMZK4].f140.m4a (pass -k to keep)



As it shows, it downloaded the format 298 but it did skipped three formats: 303, 299, 302
So it isn't giving me the best video

**Comment by pukkandan** [comment]
You said u don't want any 1080p except 137...

**Comment by Fallenap** [comment]
No, I said that I want the best video with av01 codec,
 it can be 8k or 4k, or 720p or 480p, in 60 or 30 or 24 fps, HDR or SDR. Also if it is 1080p 60fps I want it with av01 codec, but if av01 isn't avaible then vp9, or h264
If vp9 isn't avaible

So, having a list with old and new videos with different resolutions, some are avaible with av01 some are not
Some are 4k some are only 1080p some are 480p 

But I need for yt-dlp to make this exception: for all the videos in the list.txt  that are only avaible in 1080p 30, or 25, 24 fps I want the format 137, because there are three formats for this resolution and frame rates: 137 for h264,  248 for vp9 and 399 for av01

**Comment by pukkandan** [comment]
That is not what you asked for - you literally said "always 137 for 1080p", but ok. Is this what you need?


    -S res,vcodec -f "(bv[height>1080]/bv[fps>30]/137/bv*)+ba"


Please try to read and understand the format string. It is not possible for me to answer every time you need to tweak the command

**Comment by Fallenap** [comment]
Sorry I made a mistake by not clarifying that always 137 for 1080p (but the 30fps version) not 60 
The last command you gave me does exactly what I need, thank you so much, sorry for making the conversation longer than it should

**Comment by Fallenap** [comment]
Hey pukkandan hope you are fine, I need your help,
I want to know how to put upload date with -o
I know "%(upload_date)s" but I want to put only the year
I tried this "%upload_date>%y" but it gave me an output with the number 21 I think it is for the year 2021
But I need the full year "2021" I tried other variations but I cannot manage it and also please tell me how to get the full year with full month eg "2021-04"
