### ISSUE TITLE
Q: How to download all videos from a channel correctly?

### ISSUE THREAD

**Issue by Feathered-Serpent** [yt-dlp/yt-dlp#5904]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.11.11** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Let's say one wants to download all videos from e.g. Kurzgesagt - In a Nutshell. There are multiple URLs to choose from:
- https://www.youtube.com/c/inanutshell/ (Main URL)
- https://www.youtube.com/@kurzgesagt/videos (Videos tab)
- https://www.youtube.com/@kurzgesagt/playlists (Playlists tab)

The goal would be to preserve the hierarchy, so playlists are placed in subfolders, but videos not within a playlist are also downloaded.

The main URL (log telling "[youtube:tab] Downloading all uploads of the channel. To download only the videos in a specific tab, pass the tab's URL") and the videos URL (log telling "[download] Downloading playlist: Kurzgesagt – In a Nutshell - Videos" with fetching five pages of videos) both only create one folder "Kurzgesagt – In a Nutshell - Videos" with 171 videos inside, no playlist folders (and no meta information in the files about e.g. playlists either)
Using the playlists URL gives me 249 videos, with 120 unique names, aka multiple copies in multiple playlist subfolders (see below for example), but missing 51 videos without a playlist.

e.g.
```
Kurzgesagt – In a Nutshell Playlists\Science and other stuff explained\[20141211] What Is Life？ Is Death Real？.mkv
Kurzgesagt – In a Nutshell Playlists\The Existential Crisis Playlist\[20141211] What Is Life？ Is Death Real？.mkv
```

So... currently one doesn't see any way to get playlists AND non-playlisted videos in one go without downloading everything twice and deleting copies manually afterwards. One can live with the copies in multiple playlists, as one can create a hard link between the files afterwards. But choosing between non-playlisted videos and playlists but missing videos is not fun.

Is there/Should there be an option to let yt-dlp download the playlists URL and then counterchecking with the videos URL to fetch any missing videos? If it stores the video URLs of the downloaded playlisted videos, it could then just skip those videos itself.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
Download the playlist URL with --download-archive, and then the main page with same archive

**Comment by Feathered-Serpent** [comment]
Tested and works like a charm, thanks.
