### ISSUE TITLE
The app seems to contact external IP addresses. Could you tell me why this is?

### ISSUE THREAD

**Issue by epidermalfrenzy** [yt-dlp/yt-dlp#5913]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2022.11.11** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Hello,

I wonder if you could provide insight into why newer versions of yt-dlp contact external IP addresses? If you compare and contrast the "Relations" tab on github you will notice the difference.

Version 2022.11.11:

https://www.virustotal.com/gui/file/3e73e80d5b29be0a6bd47cb8636d281ce8a53ba11533f3441ea7d12433165b41/relations

Version 2022.02.04:

https://www.virustotal.com/gui/file/030ef7cbf3141d02a499ed9a4a4181df591efb1f516e7e4a2ef3fa9d83d5e67a/relations

If I was to compile the app myself can I remove this functionality from it?

Kind regards.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
I cannot reproduce the behavior on local system. You'd have to contact virustotal to know what exactly is happening.

All the source code and build workflow is public - so you may inspect it as well if desired

**Comment by flashdagger** [comment]
Happy New Year, everybody!

As I don't host any media server in my internal network, yt-dlp has to make a connection to external servers, I don't have control over (e.g Youtube). Maybe some sites have redirects (depending on user agent string) to IP addresses considered suspicious by Virustotal.

**Comment by pukkandan** [comment]
I assume they would be testing by just running `yt-dlp`, not `yt-dlp URL`

**Comment by flashdagger** [comment]
Nowadays safety and security are an illusion, given by third party "certifications"...
https://processchecker.com/file/yt-dlp.exe.html

**Comment by juchmis** [comment]
That would just be background traffic on the Windows VM that VirusTotal initialized for the scan.

Possibly SmartScreen or some other dumb feature that causes the VM to contact a bunch of Microsoft IPs when the application is run. No, VirusTotal don't filter that stuff out.

**Comment by selfisekai** [comment]
I'm not sure what you're talking about here, because when I switch to the "Behavior" tab, I see "Network comms: NOT FOUND", and the "Relations" tab that OP is linking to is only listing "Execution Parents", which seem to be other applications using yt-dlp under the hood.

**Comment by juchmis** [comment]
> I'm not sure what you're talking about here, because when I switch to the "Behavior" tab, I see "Network comms: NOT FOUND", and the "Relations" tab that OP is linking to is only listing "Execution Parents", which seem to be other applications using yt-dlp under the hood.

I think you were talking to OP, but VirusTotal's "Behavior" tab specifies:
> Network comms
> 1 DNS 12 IP 

![image](https://user-images.githubusercontent.com/5906027/210280121-7a99d097-8409-4db1-9528-ba9cc6c7aeb9.png)

**Comment by juchmis** [comment]
As stated though, this issue is almost certainly nothing of concern. VirusTotal sandboxes don't try to differentiate between network traffic the application specifically sent and network traffic the VM sent at the direction of another process, possibly as a result of malicious behavior from the submitted sample. In this case it recorded some innocuous Windows feature as it's known to do.

**Comment by selfisekai** [comment]
ah, I looked at the second link thinking it was the latest version.

all of the IP addresses listed belong to either AS8075 (Microsoft Corporation) or AS20940 (Akamai International B.V.).
the first one is obvious. the second might not be, but [Microsoft was cooperating with Akamai back in 1999](https://news.microsoft.com/1999/09/27/microsoft-and-akamai-form-strategic-relationship-to-enhance-internet-content-delivery/), [still partners with Akamai for CDN services](https://azure.microsoft.com/en-us/blog/microsoft-and-akamai-bring-cdn-to-azure-customers/), and especially - [domains pointing to Akamai are listed by Microsoft as Windows services](https://learn.microsoft.com/en-us/windows/privacy/windows-endpoints-1903-non-enterprise-editions), including: "Enables connections to Windows Update", "Windows Defender", "Microsoft Store".

**Comment by epidermalfrenzy** [comment]
I wish you a belated happy new year lol. I did not get a response from virustotal. However I noticed the latest version also contacts domains and a comment was left explaining why the app could be doing this. Perhaps it could be compiled differently?

> This host is linked to Microsoft, and/or Microsoft application tracking. Because for instance, if you build a clean EXE in Visual Studio 2022 (my test case was: building "Windows Desktop Application" template without further modifications, in Release x64 mode) you'll end up with a main application binary that contacts this host (through its IP address 192.229.211.108 on TCP 80 while forming the DNS resolutions fp2e7a.wpc.2be4.phicdn.net and fp2e7a.wpc.phicdn.net) according to VirusTotal, therefore linking the EXE against it.

Of course, the same can happen with malware built using Visual Studio, or another environment that integrates something of which this is part. #EdgeCast (registrar of contacted host's IP 192.229.211.108) is clearly connected to #Microsoft and #VisualStudio produced applications in this context.

All considered, the IP alone (or its tree of correlations) isn't an indicator of malicious or not malicious. It's extremely generic to be placed on tons of application EXE files.

#fp2e7a.wpc.2be4.phicdn.net
#fp2e7a.wpc.phicdn.net
#phicdn part of #EdgeCast and tied to #Microsoft Visual Studio produced applications/EXE binaries, the nature of traffic could be telemetry directed by Microsoft

For the record, my test case is file SHA256 58fc9286c3aac58103b44af0bfaf798c7f404da8a30eb326d24fa5835ff89839 and you can as well see what i describe in VT behavior tab and from following correlations

// Update: in web page form, this host (at http://fp2e7a.wpc.2be4.phicdn.net/) calls itself a "CRL/CACERT Repository" so it can be a side station of Visual Studio-produced applications telemetry flow/stack.

https://www.virustotal.com/gui/domain/fp2e7a.wpc.2be4.phicdn.net/community

It also has this listed against your app:

Joe Sandbox Analysis: 
			
Verdict: SUS
Score: 29/100

HTML Report: https://www.joesandbox.com/analysis/832895/0/html	
PDF Report: https://www.joesandbox.com/analysis/832895/0/pdf
Executive Report: https://www.joesandbox.com/analysis/832895/0/executive
Incident Report: https://www.joesandbox.com/analysis/832895/0/irxml
IOCs: https://www.joesandbox.com/analysis/832895?idtype=analysisid

Thanks.

**Comment by pukkandan** [comment]
Can you reproduce on a local system? I cannot
