### ISSUE TITLE
How do I split Title to Series and Episode

### ISSUE THREAD

**Issue by mradrianmarsh** [yt-dlp/yt-dlp#5925]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.01.02** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I'm trying to work out how to use output templates, to pull out Series and Episode information so that the folder/filename is formatted correctly for loading into PLEX.

I've tried using -j to peek into the json data coming down, but it would appear not to contain directly season_number or episode_number, but instead appears to be embedded within the Titlefield itself as part of the string, eg:
"Some show, Series 12, Episode 1"

Python is not my strong suite yet, so how could I setup the -o option to present that in the format:
"Some show - S12E01.mp4" ?

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
If the data is not present in the info-json, you can open a site enhancement request with logs. Or, you can try to parse the data from title using `--parse-metadata`

**Comment by mradrianmarsh** [comment]
Could you expand a little on the latter there with that option?
I've read through the readme but not sure how to put the TO part in

I definitely can submit a site enhancement.  This originates in iPlayer so on the website it is split into Series/Episodes.

**Comment by bashonly** [comment]
If every episode's title is structured like `"Some show, Series 12, Episode 1"`, something similar to this this should work, but without an actual URL I wasn't able to test:
```
--parse-metadata "title:(?P<series>[^,]+), Series (?P<season_number>\d+), Episode (?P<episode_number>\d+)"
-o "%(series)s - S%(season_number)02dE%(episode_number)02d.%(ext)s"
```

**Comment by mradrianmarsh** [comment]
This is a sample URL which gives this Title:  "title": "Call the Midwife, Series 12, Episode 1"

"https://www.bbc.co.uk/iplayer/episode/m001gptj/call-the-midwife-series-12-episode-1"

So far I think your parsing look like it's working so thankyou !  And it'll also give me something to de-code and understand how that works, so thanks again!

**Comment by bashonly** [comment]
It looks like there is already a site enhancement issue open for this BBC metadata: #2976

My original workaround suggestion's regex pattern will fail if the series name has a comma in it. This should work more reliably:

```
--parse-metadata "title:(?P<series>.+?), Series \d+"
--parse-metadata "title:, Series (?P<season_number>\d+), Episode (?P<episode_number>\d+)"
-o "%(series)s - S%(season_number)02dE%(episode_number)02d.%(ext)s"
```
