### ISSUE TITLE
Embeded yt_dlp version 2023.01.02 not working in windowed mode

### ISSUE THREAD

**Issue by sourabhkv** [yt-dlp/yt-dlp#5936]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.01.02** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Without terminal

![Screenshot_20230103_123848](https://user-images.githubusercontent.com/55890376/210314094-4b2ea3d0-40cc-4e35-9748-4273d25b376d.png)

In terminal

![Screenshot_20230103_123920](https://user-images.githubusercontent.com/55890376/210314129-1b7b9dc7-5b06-4622-9cfd-2f26105c5726.png)

I recently installed yt-dlp 2023.01.02
The same code is working in terminal but refused to work in IDLE
I have not faced this problem in older releases , how to fix this?

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
#5927

**Comment by pukkandan** [comment]
Fixed by https://github.com/yt-dlp/yt-dlp/commit/12dea4c110844d45827f79b74823f0201fee8a9d
