### ISSUE TITLE
Prevent file from becoming glitchy/having broken metadata when aborting a livestream download?

### ISSUE THREAD

**Issue by ForHelvete** [yt-dlp/yt-dlp#5944]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.01.02** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Sometimes, stream downloads loses connection or times out, or I manually abort them by closing the command prompt window. When doing so, it just leaves me with a <filename>.mp4.part file, which when I open will sometimes have glitchy audio, skip all over the place, have incorrect metadata for how long it is, etc. 

What is the correct procedure for fixing the file after a download has been aborted prematurely? 

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
Here is the fixup ffmpeg command line that yt-dlp runs after a livestream download has concluded if you're using default options (e.g. not `--no-hls-use-mpegts`):
```
ffmpeg -i "file:input.mp4" -map 0 -dn -ignore_unknown -c copy -f mp4 -bsf:a aac_adtstoasc -movflags +faststart "file:output.mp4"
```

You could try that, but some of the symptoms you describe sound like there may have been fragments missed in the middle of the stream (possibly due to connection issues.) The fixup command won't be able to do anything about missing data.
