### ISSUE TITLE
[TVer] Whenever --mtime is used, file modification time is January 1, 2016

### ISSUE THREAD

**Issue by panam510** [yt-dlp/yt-dlp#5960]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a site-specific feature
- [X] I've verified that I'm running yt-dlp version **2023.01.02** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Japan

### Example URLs

https://tver.jp/episodes/ep3s73f9ke

### Provide a description that is worded well enough to be understood

Only one URL is pasted in the example, but the file modification time is January 1, 2016 for all videos on TVer.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
$ yt-dlp -vU --mtime https://tver.jp/episodes/ep3s73f9ke
[debug] Command-line config: ['-vU', '--mtime', 'https://tver.jp/episodes/ep3s73f9ke']
[debug] User config "/home/someuser/.config/yt-dlp/config": ['-o', '%(channel)s_%(title)s.%(ext)s']
[debug] System config: []
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2023.01.02 [d83b0ad] (zip)
[debug] Python 3.8.10 (CPython x86_64 64bit) - Linux-5.4.0-135-generic-x86_64-with-glibc2.29 (OpenSSL 1.1.1f  31 Mar 2020, glibc 2.31)
[debug] exe versions: ffmpeg 5.0.1-static (setts), ffprobe 5.0.1-static, rtmpdump 2.4
[debug] Optional libraries: Crypto-3.15.0, certifi-2019.11.28, mutagen-1.45.1, secretstorage-2.3.1, sqlite3-2.6.0, websockets-8.1
[debug] Proxy map: {}
[debug] Loaded 1754 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2023.01.02, Current version: 2023.01.02
yt-dlp is up to date (2023.01.02)
[TVer] Creating session
[TVer] Extracting URL: https://tver.jp/episodes/ep3s73f9ke
[TVer] ep3s73f9ke: Downloading JSON metadata
[TVer] ep3s73f9ke: Downloading JSON metadata
[brightcove:new] Extracting URL: http://players.brightcove.net/3971130137001/default_default/index.html?videoId=6318089958112#__youtubedl_smuggle=%7B%22geo_countries%22%3A+%5B%22JP%22%5D%7D
[debug] Using fake IP 133.181.8.117 (JP) as X-Forwarded-For
[debug] Loading brightcove.3971130137001_default from cache
[brightcove:new] 6318089958112: Downloading JSON metadata
[brightcove:new] 6318089958112: Downloading m3u8 information
[brightcove:new] 6318089958112: Downloading m3u8 information
[brightcove:new] 6318089958112: Downloading m3u8 information
[brightcove:new] 6318089958112: Downloading m3u8 information
[brightcove:new] 6318089958112: Downloading MPD manifest
[brightcove:new] 6318089958112: Downloading MPD manifest
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 6318089958112: Downloading 1 format(s): hls-2043-3
[debug] Invoking hlsnative downloader on "https://manifest.prod.boltdns.net/manifest/v1/hls/v3/aes128/3971130137001/5b793e83-79d7-48d4-9806-c8baf100892f/e62e71fd-95a5-4596-9cc6-0d12e855f20e/4c7a7765-aa83-4f07-9b18-c429a77f8c89/10s/rendition.m3u8?fastly_token=NjNkOTRkYWVfZGVkZTJlYjBlNGYyZGNlZGU3YTE2Y2YyNWQxYTMzZGY4MzM2YTE0NTUxZGYyZDBmYjU3Mjg1ZGI3NWFiOTVjZg%3D%3D"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 21
[download] Destination: テレビ東京_ミライの歩き方 高市大臣が語る「経済安全保障推進法」経済から日本を守るとは？.mp4
[download] 100% of   49.16MiB in 00:00:12 at 3.89MiB/s
[debug] ffprobe command line: ffprobe -hide_banner -show_format -show_streams -print_format json 'file:テレビ東京_ミライの歩き方 高市大臣が語る「経済安全保障推進法」経済から日本を守るとは？.mp4'
[FixupM3u8] Fixing MPEG-TS in MP4 container of "テレビ東京_ミライの歩き方 高市大臣が語る「経済安全保障推進法」経済から日本を守るとは？.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:テレビ東京_ミライの歩き方 高市大臣が語る「経済安全保障推進法」経済から日本を守るとは？.mp4' -map 0 -dn -ignore_unknown -c copy -f mp4 -bsf:a aac_adtstoasc -movflags +faststart 'file:テレビ東京_ミライの歩き方 高市大臣が語る「経済安全保障推進法」経済から日本を守るとは？.temp.mp4'

$ ls -la --time-style=full-iso 'テレビ東京_ミライの歩き方 高市大臣が語る「経済安全保障推進法」経済から日本を守るとは？.mp4'
-rw-rw-rw- 1 someuser someuser 49043609 2016-01-01 09:00:00.000000000 +0900 'テレビ東京_ミライの歩き方 高市大臣が語る「経済安全保障推進法」経済から日本を守るとは？.mp4'
```

**Comment by panam510** [comment]
By way of an addendum, the last modified time on the HTTP header is as follows. The delivery page itself returns a reasonable time, but the segment0.ts file returns 2016.

https://tver.jp/episodes/ep3s73f9ke
`last-modified: Thu, 05 Jan 2023 02:07:39 GMT`

https://ntv-vod-cdn.tver.jp/media/v1/hls/v5/aes128/4394098882001/af36b122-4020-478e-bf89-34623f04c370/311ab129-d681-45b3-94f8-028b8f63bb1d/8b8f13e4-fc0a-403d-b8c6-e8212cd6dd33/5x/segment0.ts
`last-modified: Fri, 01 Jan 2016 00:00:00 GMT`

**Comment by pukkandan** [comment]
https://github.com/yt-dlp/yt-dlp/issues/5942#issuecomment-1370600808
https://github.com/yt-dlp/yt-dlp/issues/5942#issuecomment-1371675740
