### ISSUE TITLE
Avoid Terminal Flooding in Case of Extractor Error

### ISSUE THREAD

**Issue by TurtleWilly** [yt-dlp/yt-dlp#5961]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.01.02** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

**Note:** _"I've verified that I'm running yt-dlp version 2023.01.02 (update instructions) or later (specify commit) *"_ <- I do NOT yet, but I had to activate the option to be able to report. I can't report the issue with the latest version, because it certainly will make the trigger for my issue go away again. Also a "verbose" output with `-vU` isn't helpful for my report.

---

When a site breaks with _yt-dlp_ (e.g. youtube) the at-that-point outdated version of _yt-dlp_ occasionally starts spamming a lot of random JavaScript code to the Terminal. I guess when the JavaScript code from the remote site is minified it's basically a single line of code which then gets printed out, but in some cases that fills the Terminal with 50, 60, or even more pages worth (I have to scroll a mile). E.g.:

```
$ yt-dlp 'https://www.youtube.com/watch?v=7pa3T2nRzX8'
[youtube] 7pa3T2nRzX8: Downloading webpage
[youtube] 7pa3T2nRzX8: Downloading android player API JSON
[youtube] 7pa3T2nRzX8: Downloading player e5f6cbd5
WARNING: [youtube] nsig extraction failed: You may experience throttling for some formats
n = uWBvMes7mxWfD-g4T ; player = https://www.youtube.com/s/player/e5f6cbd5/player_ias.vflset/en_US/base.js
7pa3T2nRzX8: Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/youtube.py", line 2563, in _decrypt_nsig
    self._player_cache[player_id] = self._extract_n_function(video_id, player_url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/youtube.py", line 2591, in _extract_n_function
    func_code = jsi.extract_function_code(funcname)
  File "/usr/local/bin/yt-dlp/yt_dlp/jsinterp.py", line 473, in extract_function_code
    code, _ = self._separate_at_paren(func_m.group('code'), '}')  # refine the match
  File "/usr/local/bin/yt-dlp/yt_dlp/jsinterp.py", line 94, in _separate_at_paren
    raise ExtractorError(f'No terminating paren {delim} in {expr}')
yt_dlp.utils.ExtractorError: No terminating paren } in {var b=a.split(""),c=[-382806166,2056665129,-888575707,1764770305,98308992,-1483961372,function(d,e,f,h,l){return e(f,h,l)},
function(d,e){for(e=(e%d.length+d.length)%d.length;e--;)d.unshift(d.pop())},
-825128129,null,function(d,e,f,h,l,m,n,p,q,r){return e(l,m,n,p,q,r)},
512565425,-1659495181,-103794430,null,1797616044,-1650451862,924590065,function(d,e){d=(d%e.length+e.length)%e.length;e.splice(0,1,e.splice(d,1,e[0])[0])},
b,function(d){for(var e=d.length;e;)d.push(d.splice(--e,1)[0])},

…
[cut-- REALLY A LOT OF MINIFIED JAVASCRIPT CODE HERE --cut]
…

*e/9));f=new zF(d,e,0,null,void 0,b,f);a=unescape(a.replace(/&quot;/g,\'"\'));return new DF(c,a,{audio:h,video:f})}; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[info] 7pa3T2nRzX8: Downloading 1 format(s): 303+251
[download] Destination: “Carnage and Cold Weather” - Being The Elite Ep. 329 [7pa3T2nRzX8].f303.webm
[download]  25.0% of 734.58MiB at  6.76MiB/s ETA 01:21
```

I cut the worst of it. Basically **it floods the Terminal** with junk information that is hardly useful for a mere user like me, especially if it's not a truly breaking issue (it continues to download fine afterwards after all).

**Feature Request**

* could dumped code from a remote site only be dumped when a verbose flag is used?

or alternatively:

* if to be dumped code exceeds a sane amount of characters could the code then be cut down to a relevant part (say 512 characters around the extractor's error location)?

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
Already fixed in latest version
