### ISSUE TITLE
How to add \/" to yt-dlp config file?

### ISSUE THREAD

**Issue by noname278** [yt-dlp/yt-dlp#5964]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.01.02** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Hello. I figured out how to replace :*?| with _. But, I can't replace \ /". (How) can I do that?

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.youtube.com/watch?v=OORigQYUuoI']

Usage: yt-dlp [OPTIONS] URL [URL...]

yt-dlp: error: Unable to parse "C:\Users\ydl\yt-dlp.conf": No closing quotation
```

**Comment by pukkandan** [comment]
replace where?? what have you tried?

**Comment by noname278** [comment]
I used this in the config file: --replace-in-metadata "title" "[\/:*?"|]" "_". If it's only --replace-in-metadata "title" "[:*?|]" "_", it works.

**Comment by pukkandan** [comment]
Try using single quotes. Or refer to https://www.gnu.org/software/bash/manual/html_node/Quoting.html
