### ISSUE TITLE
Download only audio from different services.

### ISSUE THREAD

**Issue by ivan-ivory** [yt-dlp/yt-dlp#5965]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.01.02** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I need to download audio streams from different sites with medium quality like mp3 128 kbps. I need a solution that is as non-demanding to computing resources as possible
1. And I do not understand can I use one universal script for different sites?
2. Can I download audio for all videos or sometimes I should use postprocessing?
3. If so what video I should download for postprocessing width required audio qulity?
4. Can I use universal script for postprocessing. 
5. Could someone provide me this script which I will use as a starting point for further modifications?

Sorry for the simple questions. I explored the documentation in detail, everything seems to be clear for YouTube, but there are still questions, especially for other sites.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
Most sites, including youtube does not provide mp3 format. So, if you need mp3, you have to convert it from another. `-x -f mp3/ba --audio-format mp3` will download mp3 if available and convert to it otherwise. For controling quality of conversion, see `--audio-quality` option

**Comment by ivan-ivory** [comment]
mp3 is not required, I will be satisfied with any popular format that will be played on most devices and which is the easiest to download. The quality should be average about as mp3 128

**Comment by pukkandan** [comment]
> The quality should be average about as mp3 128

We can't measure the subjective quality of a format...

> mp3 is not required, I will be satisfied with any popular format 

Then, is just `-x` not enough for you? Have you tried it?

**Comment by ivan-ivory** [comment]
> Then, is just -x not enough for you? Have you tried it?

No, but I will!
