### ISSUE TITLE
[Broken] Vimeo - Some original files downloadable with jdownloader not yt-dlp

### ISSUE THREAD

**Issue by remlap** [yt-dlp/yt-dlp#597]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running yt-dlp version **2021.07.24**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] User config file: /home/remlap/.config/yt-dlp.conf
[debug] User config: ['--hls-prefer-native', '--add-metadata', '--sub-langs', 'all', '--embed-subs', '--no-sponskrub']
[debug] Command-line config: ['https://vimeo.com/393756517', '--skip-download', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] yt-dlp version 2021.07.24 
[debug] Python version 3.8.10 (CPython 64bit) - Linux-5.4.0-80-generic-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4, rtmpdump 2.4
[debug] Proxy map: {}
[debug] [vimeo] Extracting URL: https://vimeo.com/393756517
[vimeo] 393756517: Downloading webpage
[vimeo] 393756517: Extracting information
[vimeo] 393756517: Downloading JSON metadata
[vimeo] 393756517: Downloading JSON metadata
WARNING: [vimeo] Unable to download JSON metadata: HTTP Error 403: Forbidden
[vimeo] 393756517: Downloading akfire_interconnect_quic m3u8 information
[vimeo] 393756517: Downloading akfire_interconnect_quic m3u8 information
[vimeo] 393756517: Downloading fastly_skyfire m3u8 information
[vimeo] 393756517: Downloading fastly_skyfire m3u8 information
[vimeo] 393756517: Downloading akfire_interconnect_quic MPD information
[vimeo] 393756517: Downloading akfire_interconnect_quic MPD information
[vimeo] 393756517: Downloading fastly_skyfire MPD information
[vimeo] 393756517: Downloading fastly_skyfire MPD information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 393756517: Downloading 1 format(s): hls-fastly_skyfire-5388

```

## Description

I was informed today some Vimeo videos are downloadable in their original upload form by using Jdownloader and it turns out to be true.

https://vimeo.com/393756517

I can download a 390.8MiB mov file with Jdownloader.

Neither yt-dlp or youtube-dl can download these.

Thought it was worth mentioning.

**Comment by october262** [comment]
add the words player & video like this - yt-dlp https://player.vimeo.com/video/393756517
the video will now download.

**Comment by Ashish0804** [comment]
Can you tell the bitrate of this `390.8MB` file?

Using the original url and one mentioned by @october262 show same available formats to me.

**Comment by remlap** [comment]
> Can you tell the bitrate of this `390.8MB` file?
> 
> Using the original url and one mentioned by @october262 show same available formats to me.

Same no mention of any original mov's

``General
Complete name                            : /media/remlap/Kiernan Shipka/Videos/Chilling Adventures of Sabrina/Extras/Straight to Hell Music Video/Straight To Hell - Sabrina_ Netflix_ORIGINAL_DOWNLOAD.mov
Format                                   : MPEG-4
Format profile                           : QuickTime
Codec ID                                 : qt   0000.00 (qt  )
File size                                : 391 MiB
Duration                                 : 2 min 55 s
Overall bit rate mode                    : Variable
Overall bit rate                         : 18.7 Mb/s
Encoded date                             : UTC 2020-02-12 02:56:18
Tagged date                              : UTC 2020-02-12 02:56:42
Writing library                          : Apple QuickTime

Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L4
Format settings                          : 2 Ref Frames
Format settings, CABAC                   : No
Format settings, Reference frames        : 2 frames
Format settings, GOP                     : M=2, N=120
Codec ID                                 : avc1
Codec ID/Info                            : Advanced Video Coding
Duration                                 : 2 min 55 s
Bit rate mode                            : Variable
Bit rate                                 : 16.4 Mb/s
Maximum bit rate                         : 768 kb/s
Width                                    : 1 920 pixels
Height                                   : 1 080 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 23.976 (24000/1001) FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.329
Stream size                              : 342 MiB (88%)
Title                                    : Core Media Video
Encoded date                             : UTC 2020-02-12 02:56:18
Tagged date                              : UTC 2020-02-12 02:56:42
Color range                              : Limited
Color primaries                          : BT.709
Matrix coefficients                      : BT.709
Codec configuration box                  : avcC

Audio
ID                                       : 2
Format                                   : PCM
Format settings                          : Little / Signed
Codec ID                                 : lpcm
Duration                                 : 2 min 55 s
Bit rate mode                            : Constant
Bit rate                                 : 2 304 kb/s
Channel(s)                               : 2 channels
Channel layout                           : L R
Sampling rate                            : 48.0 kHz
Bit depth                                : 24 bits
Stream size                              : 48.2 MiB (12%)
Title                                    : Core Media Audio
Encoded date                             : UTC 2020-02-12 02:56:18
Tagged date                              : UTC 2020-02-12 02:56:42

Other
ID                                       : 3
Type                                     : Time code
Format                                   : QuickTime TC
Duration                                 : 2 min 55 s
Frame rate                               : 23.976 (24000/1001) FPS
Time code of first frame                 : 01:00:00:00
Time code, striped                       : Yes
Title                                    : Core Media Time Code
Encoded date                             : UTC 2020-02-12 02:56:18
Tagged date                              : UTC 2020-02-12 02:56:42
