### ISSUE TITLE
[SSL: TLSV1_ALERT_INTERNAL_ERROR

### ISSUE THREAD

**Issue by shahidhasanzai** [yt-dlp/yt-dlp#598]
![image](https://user-images.githubusercontent.com/75906314/127731060-67ccb015-7446-48f1-807c-70358c3e5451.png)

**Comment by shahidhasanzai** [comment]
https://drmstreaming.sonyliv.net/DASH/cc9365a9-7e6c-4e8a-b967-0a6234ec013e/WWE_SMACKDOWN_MULTI_HLS_20210731T021800.mpd

**Comment by pukkandan** [comment]
1. IGNORING THE ISSUE TEMPLATE WILL RESULT IN ISSUE CLOSED AS INCOMPLETE
2. The server is rejecting your request and there is nothing I can do about it. You can check that the URL does not open in browser
3. This is DRM protected content. So we will not provide any further help for it
