### ISSUE TITLE
On Odysee cannot download playlist.

### ISSUE THREAD

**Issue by nttrock** [yt-dlp/yt-dlp#5982]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2023.01.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

When I try to download a playlist n Odysee, I get the following:

[lbry] Extracting URL: https://odysee.com/$/playlist/...
[lbry] $: Downloading stream JSON metadata
ERROR: $: An extractor error has occurred. (caused by KeyError('value')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[lbry] Extracting URL: https://odysee.com/$/playlist/...
[lbry] $: Downloading stream JSON metadata
ERROR: $: An extractor error has occurred. (caused by KeyError('value')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

**Comment by flashdagger** [comment]
I tried to load your playlist in the browser. Does it have private restriction?
![image](https://user-images.githubusercontent.com/17416271/211142512-8374f776-b5ce-438d-ba58-b56df0409a29.png)

**Comment by pukkandan** [comment]
### DO NOT BLINDLY TICK THE CHECK BOXES

They are instructions for you to follow and then confirm by ticking them. Issues were it is obvious that you have not followed the instructions will be closed as `incomplete`. Repeated offense **will be treated as spam**

**Comment by october262** [comment]
try it with the users home page - yt-dlp "https://odysee.com/@lenexists:a?view=home"

**Comment by nttrock** [comment]
Look, the issue is the same no matter what playlist you try it with. No difference. Right now, yt-dlp just can't download playlists from Odysee. Probably a parsing issue (I suspect).

**Comment by sysfu** [comment]
> Look, the issue is the same no matter what playlist you try it with. No difference. Right now, yt-dlp just can't download playlists from Odysee. Probably a parsing issue (I suspect).

Has the feature ever worked with Odysee? I'm trying to download a LBRY playlist that I've made public and it can't seem to parse it either.
