### ISSUE TITLE
Brand new to any of this, moving from yt-dl for faster speeds

### ISSUE THREAD

**Issue by Anubite51** [yt-dlp/yt-dlp#5990]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.01.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

So I do not know how to use this yt-dlp thing and I follow the instructions for installing, but winget isn't on my pc even though the microsoft store says the app installer is already on my pc.  When i try to open winget, it just opens and immediately closes.  Help plz

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
1. Download https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp.exe

2. Install ffmpeg (Optional, but recommended):
    1. Download https://github.com/yt-dlp/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-win64-gpl.zip
    2. Extract the files and find `ffmpeg.exe` and `ffprobe.exe` inside the `bin` folder
    3. Copy those two files to the same folder as `yt-dlp.exe`
    
3. Download a video:
    1. Open windows explorer to the folder where you downloaded yt-dlp.exe
    2. In the address bar of the the folder that yt-dlp.exe is in, type `cmd` and press enter
    3. Then in the terminal window that opens, type `yt-dlp "URL"`, replacing `URL` with the actual link you want to download.
    4. Wait for your video to finish downloading :smile:

4. Skim through the documentation https://github.com/yt-dlp/yt-dlp#readme to learn about more features
    * Make sure to do this before asking further questions. It's not expected that you to read and understand the whole thing, but skim through it so you have a rough idea what kinds of options are available.

5. [OPTIONAL] Add the yt-dlp folder to `PATH` https://www.java.com/en/download/help/path.html
