### ISSUE TITLE
live from start

### ISSUE THREAD

**Issue by anunasica** [yt-dlp/yt-dlp#5995]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.01.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Hi, is "live from start" intented for youtube only or for other sites too? thanks. (It failed on live conference on ORF TV Thek.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by october262** [comment]
live from start should work for other websites besides youtube
streamlink might be a better solution for live tv.

**Comment by Lesmiscore** [comment]
```
--live-from-start               Download livestreams from the start.
                                Currently only supported for YouTube
                                (Experimental)
```

**Comment by chrizilla** [comment]
Is it safe to use `--live-from-start` on all sites, assuming that yt-dlp falls back to `--no-live-from-start` on unsupported sites?
Or could this create problems ?

**Comment by pukkandan** [comment]
No, it does not "fall back". When the requested type of stream is unavailable, it throws error

**Comment by chrizilla** [comment]
> No, it does not "fall back". When the requested type of stream is unavailable, it throws error

From this [log](https://github.com/yt-dlp/yt-dlp/issues/6705#issuecomment-1498388797) it seems the generic extractor doesn't.

What is the reason for aborting with an error instead of just issuing a warning and trying to fall back to record from the current position (rather than recording nothing) ?

**Comment by pukkandan** [comment]
> From this [log](https://github.com/yt-dlp/yt-dlp/issues/6705#issuecomment-1498388797) it seems the generic extractor doesn't.

because it was not being detected as live, obviously. That was the whole issue that was being reported...
