### ISSUE TITLE
--print and --print-to-file return NA for %(filename)s when after_video: value is used

### ISSUE THREAD

**Issue by m3thm4th** [yt-dlp/yt-dlp#5997]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2023.01.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

When invoking the flag `--print` or `--print-to-file` the output is always `NA` if `after_video:` or `after_move:` flags are used.
If the `WHEN` flags are not used the output is the file name of the pre-processed file, for example when passing the `-x` flag the output is `/home/user/Downloads/Video Title.webm`, but it should be `/home/user/Downloads/Video Title.opus`

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp https://www.youtube.com/watch?v=BaW_jenozKc -o "/home/user/Downloads/%(title)s.%(ext)s" --print after_video:'%(filename)s' -vU
[debug] Command-line config: ['https://www.youtube.com/watch?v=BaW_jenozKc', '-o', '/home/user/Downloads/%(title)s.%(ext)s', '--print', 'after_video:%(filename)s', '-vU']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2023.01.06 [6becd25] (zip)
[debug] Python 3.9.2 (CPython x86_64 64bit) - Linux-5.10.0-20-amd64-x86_64-with-glibc2.31 (OpenSSL 1.1.1n  15 Mar 2022, glibc 2.31)
[debug] exe versions: ffmpeg 4.3.5-0, ffprobe 4.3.5-0
[debug] Optional libraries: Cryptodome-3.9.7, brotli-1.0.9, certifi-2020.06.20, mutagen-1.45.1, sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Loaded 1760 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2023.01.06, Current version: 2023.01.06
yt-dlp is up to date (2023.01.06)
[youtube] Extracting URL: https://www.youtube.com/watch?v=BaW_jenozKc
[youtube] BaW_jenozKc: Downloading webpage
[youtube] BaW_jenozKc: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] BaW_jenozKc: Downloading 1 format(s): 248+251
[debug] Invoking http downloader on "https://rr3---sn-uxaxpu5ap5-u5ge.googlevideo.com/videoplayback?expire=1673265352&ei=aKy7Y6i7NMXl7gOwwpbADg&ip=82.59.36.48&id=o-AIBeh7A55yRSOfOXCeIXJbNTbs3i3O8LM5AURBIN2pDt&itag=248&source=youtube&requiressl=yes&mh=Rf&mm=31%2C29&mn=sn-uxaxpu5ap5-u5ge%2Csn-hpa7znzr&ms=au%2Crdu&mv=m&mvi=3&pcm2cms=yes&pl=24&initcwndbps=1371250&spc=zIddbGYXxWVY2Ia2kRZ93lH2SUE2N3M&vprv=1&svpuc=1&mime=video%2Fwebm&gir=yes&clen=988479&dur=9.833&lmt=1544741703689523&mt=1673243363&fvip=1&keepalive=yes&fexp=24007246&c=ANDROID&txp=5432432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRAIgPBFTFjEVo0Ma5yk3XgXTWUY8KGZUdB-kUC5Vsa4KokYCIFjSbvmWpFwHkTAqdyGz9Am_G1hLP3ML_Md-WjQ119Kg&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAKJxaZcSEpsZfdBSVdce4cnfGeMtWPKfguzr-tNhVPEaAiEAv6eYZ1XfcXazCygAQoN1atClLtOdXMcxGkaeoI5tG8o%3D"
[download] Destination: /home/user/Downloads/youtube-dl test video ＂'⧸⧹ä↭𝕐.f248.webm
[debug] Invoking http downloader on "https://rr3---sn-uxaxpu5ap5-u5ge.googlevideo.com/videoplayback?expire=1673265352&ei=aKy7Y6i7NMXl7gOwwpbADg&ip=82.59.36.48&id=o-AIBeh7A55yRSOfOXCeIXJbNTbs3i3O8LM5AURBIN2pDt&itag=251&source=youtube&requiressl=yes&mh=Rf&mm=31%2C29&mn=sn-uxaxpu5ap5-u5ge%2Csn-hpa7znzr&ms=au%2Crdu&mv=m&mvi=3&pcm2cms=yes&pl=24&initcwndbps=1371250&spc=zIddbGYXxWVY2Ia2kRZ93lH2SUE2N3M&vprv=1&svpuc=1&mime=audio%2Fwebm&gir=yes&clen=142292&dur=9.841&lmt=1506055557712479&mt=1673243363&fvip=1&keepalive=yes&fexp=24007246&c=ANDROID&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRAIgRxLV6FABKpXQ-l5ESPT_6j-HaTbbsdayXHOc5t1hMtMCIB5283DAUfAbHC6BwNzR1Soxe-eLpWbJdFTlQAm2XF2h&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAKJxaZcSEpsZfdBSVdce4cnfGeMtWPKfguzr-tNhVPEaAiEAv6eYZ1XfcXazCygAQoN1atClLtOdXMcxGkaeoI5tG8o%3D"
[download] Destination: /home/user/Downloads/youtube-dl test video ＂'⧸⧹ä↭𝕐.f251.webm
[Merger] Merging formats into "/home/user/Downloads/youtube-dl test video ＂'⧸⧹ä↭𝕐.webm"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:/home/user/Downloads/youtube-dl test video ＂'"'"'⧸⧹ä↭𝕐.f248.webm' -i 'file:/home/user/Downloads/youtube-dl test video ＂'"'"'⧸⧹ä↭𝕐.f251.webm' -c copy -map 0:v:0 -map 1:a:0 -movflags +faststart 'file:/home/user/Downloads/youtube-dl test video ＂'"'"'⧸⧹ä↭𝕐.temp.webm'
Deleting original file /home/user/Downloads/youtube-dl test video ＂'⧸⧹ä↭𝕐.f248.webm (pass -k to keep)
Deleting original file /home/user/Downloads/youtube-dl test video ＂'⧸⧹ä↭𝕐.f251.webm (pass -k to keep)
NA
```

**Comment by bashonly** [comment]
related: discussion in https://github.com/yt-dlp/yt-dlp/issues/5846#issuecomment-1361219864

**Comment by pukkandan** [comment]
and for `after_move`, use `filepath`. Ref https://github.com/yt-dlp/yt-dlp#outtmpl-postprocess-note

---

https://github.com/yt-dlp/yt-dlp/blob/87ebab0615b1bf9b14b478b055e7059d630b4833/README.md#L1333-L1338

This section is only available in the default stage of `--print`

**Comment by m3thm4th** [comment]
So not possible to apply `WHEN` flag to `%(filename)s`?

**Comment by pukkandan** [comment]
> and for `after_move`, use `filepath`

**Comment by m3thm4th** [comment]
> > and for `after_move`, use `filepath`

Yes, `filepath`, unlike `filename`, works for `after_move`, but not for `after_video`, which is the one I need.

**Comment by pukkandan** [comment]
> or `after_video`, which is the one I need.

You are most likely misunderstanding and what you need is really `after_move`. The reason is explained here

> related: discussion in [#5846 (comment)](https://github.com/yt-dlp/yt-dlp/issues/5846#issuecomment-1361219864)

**Comment by m3thm4th** [comment]
If it's not possible to retrieve the path `after_video`, couldn't it be made to work so the output is saved `after_move` and printed `after_video`?

**Comment by pukkandan** [comment]
Pls read the posted link again

**Comment by m3thm4th** [comment]
> Pls read the posted link again

I read it, since the output for `after_video` will always be `NA` which is useless, the script might simply save the path for the previous stage and print it `after_video`. I don't know if I made myself clear. The output of `after_move:'%(filepath)s'` is good, but I want it printed after all operations are completed, so if I specify `after_video:'%(filepath)s'` the output would be saved `after_move`, but printed only `after_video`.

**Comment by m3thm4th** [comment]
> > Pls read the posted link again
> 
> I read it, since the output for `after_video` will always be `NA` which is useless, the script might simply save the path for the previous stage and print it `after_video`. I don't know if I made myself clear. The output of `after_move:'%(filepath)s'` is good, but I want it printed after all operations are completed, so if I specify `after_video:'%(filepath)s'` the output would be saved `after_move`, but printed only `after_video`.

@pukkandan would that be feasible?

**Comment by pukkandan** [comment]
I am sorry, I do not know how to explain it any better than I already did in #5846
