### ISSUE TITLE
[twitter] problem authenticating with `--cookies-from-browser`

### ISSUE THREAD

**Issue by traplover4200** [yt-dlp/yt-dlp#5998]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2023.01.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

us

### Provide a description that is worded well enough to be understood

im trying to download a video from twitter

config file 
--netrc
-f 'bv*+ba'
-o %(title)s_%(uploader)s_%(id)s.%(ext)s
--embed-thumbnail
--embed-metadata

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://twitter.com/BurstingSeas/status/1611922060359655424']
[debug] System config "/etc/yt-dlp.conf": ['--netrc', '-f', 'bv*+ba', '-o', '%(title)s_%(uploader)s_%(id)s.%(ext)s', '--embed-thumbnail', '--embed-metadata']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2023.01.06 [6becd25] (pip)
[debug] Python 3.10.6 (CPython x86_64 64bit) - Linux-6.0.12-76060006-generic-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.16.0, brotli-1.0.9, certifi-2020.06.20, mutagen-1.46.0, pyxattr-0.7.2, secretstorage-3.3.1, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1760 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2023.01.06, Current version: 2023.01.06
yt-dlp is up to date (2023.01.06)
[twitter] Extracting URL: https://twitter.com/BurstingSeas/status/1611922060359655424
[twitter] 1611922060359655424: Downloading guest token
[twitter] 1611922060359655424: Downloading JSON metadata
WARNING: [twitter] Twitter API gave 404 response, retrying with deprecated auth token. Only one media item can be extracted
[twitter] 1611922060359655424: Downloading guest token
[twitter] 1611922060359655424: Downloading JSON metadata
[debug] [twitter] Extracting from video info: 1611921625288515585
[twitter] 1611922060359655424: Downloading m3u8 information
[debug] Sort order given by extractor: res, br, size, proto
[debug] Formats sorted by: hasvid, ie_pref, res, tbr, vbr, abr, filesize, fs_approx, proto, lang, quality, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, asr, vext, aext, hasaud, source, id
ERROR: [twitter] 1611921625288515585: Requested format is not available. Use --list-formats for a list of available formats
Traceback (most recent call last):
  File "/home/traplover/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1502, in wrapper
    return func(self, *args, **kwargs)
  File "/home/traplover/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1599, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/home/traplover/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1658, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/home/traplover/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 2736, in process_video_result
    raise ExtractorError(
yt_dlp.utils.ExtractorError: [twitter] 1611921625288515585: Requested format is not available. Use --list-formats for a list of available formats
```

**Comment by bashonly** [comment]
The warning is given because the tweet is age-restricted. But the tweet only contains 1 media item (video) anyways, so this is not a problem.

The reason why you are getting "requested format is not available" is because of the `'-f "bv*+ba"` line in your system config. There is no audio-only format available. 

You can either remove that line from your system config (because it might cause problems on other sites as well), or you can add "-f 'bv*+ba/b'" to your command to override your system config for this one download.

**Comment by traplover4200** [comment]
i add my twitter login to yt-dlp .netrc but it look like it not loging

**Comment by bashonly** [comment]
> i add my twitter login to yt-dlp .netrc but it look like it not loging

netrc doesn't work with all sites. You need to pass cookies with `--cookies-from-browser` or `--cookies` for twitter auth.

This isn't relevant to the issue anyways. The issue is caused by your format selection argument.

**Comment by traplover4200** [comment]
my issue was with the 404 warning you say it was " age-restricted. Without logging in"

--cookies-from-browser firefox
i get this error
Error(s) while querying API: This request requires a matching csrf cookie and header

**Comment by bashonly** [comment]
Are you logged into the site with firefox? Post full verbose log.

Also, the 404 warning is not preventing you from downloading anything. Your format selection argument is.

**Comment by traplover4200** [comment]
[debug] Command-line config: ['-vU', 'https://twitter.com/BurstingSeas/status/1611922060359655424']
[debug] System config "/etc/yt-dlp.conf": ['--netrc', '--cookies-from-browser', 'firefox', '-o', '%(title)s_%(uploader)s_%(id)s.%(ext)s', '--embed-thumbnail', '--embed-metadata']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2023.01.06 [6becd25] (pip)
[debug] Python 3.10.6 (CPython x86_64 64bit) - Linux-6.0.12-76060006-generic-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.16.0, brotli-1.0.9, certifi-2020.06.20, mutagen-1.46.0, pyxattr-0.7.2, secretstorage-3.3.1, sqlite3-2.6.0, websockets-10.4
[Cookies] Extracting cookies from firefox
[debug] Extracting cookies from: "/home/hacker47/.mozilla/firefox/w4d7xv5l.default-release/cookies.sqlite"
[Cookies] Extracted 782 cookies from firefox
[debug] Proxy map: {}
[debug] Loaded 1760 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2023.01.06, Current version: 2023.01.06
yt-dlp is up to date (2023.01.06)
[twitter] Extracting URL: https://twitter.com/BurstingSeas/status/1611922060359655424
[debug] [twitter] Using GraphQL API (Auth = True)
[twitter] 1611922060359655424: Downloading JSON metadata
ERROR: [twitter] 1611922060359655424: Error(s) while querying API: This request requires a matching csrf cookie and header.
  File "/home/hacker47/.local/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 680, in extract
    ie_result = self._real_extract(url)
  File "/home/hacker47/.local/lib/python3.10/site-packages/yt_dlp/extractor/twitter.py", line 876, in _real_extract
    result = self._call_graphql_api('zZXycP0V6H7m-2r0mOnFcA/TweetDetail', twid)
  File "/home/hacker47/.local/lib/python3.10/site-packages/yt_dlp/extractor/twitter.py", line 165, in _call_graphql_api
    return traverse_obj(self._call_api(endpoint, media_id, query=query, graphql=True), 'data')
  File "/home/hacker47/.local/lib/python3.10/site-packages/yt_dlp/extractor/twitter.py", line 155, in _call_api
    raise ExtractorError(f'Error(s) while querying API: {error_message}', expected=True)

**Comment by bashonly** [comment]
> Are you logged into the site with firefox?

You did not answer the question. And I cannot reproduce:
```
[Cookies] Extracting cookies from firefox
[debug] Extracting cookies from: "/home/user/.mozilla/firefox/yu1ip1xa.default-release/cookies.sqlite"
[debug] Only loading cookies from firefox container "twitter", ID 20
[Cookies] Extracted 61 cookies from firefox
[debug] Proxy map: {}
[debug] Loaded 1761 extractors
[twitter] Extracting URL: https://twitter.com/BurstingSeas/status/1611922060359655424
[debug] [twitter] Using GraphQL API (Auth = True)
[twitter] 1611922060359655424: Downloading JSON metadata
[debug] [twitter] Extracting from video info: 1611921625288515585
[twitter] 1611922060359655424: Downloading m3u8 information
[debug] Sort order given by extractor: res, br, size, proto
[debug] Formats sorted by: hasvid, ie_pref, res, tbr, vbr, abr, filesize, fs_approx, proto, lang, quality, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, asr, vext, aext, hasaud, source, id
[info] Available formats for 1611921625288515585:
ID        EXT RESOLUTION │   FILESIZE   TBR PROTO │ VCODEC        VBR ACODEC    ABR
───────────────────────────────────────────────────────────────────────────────────
hls-256   mp4 480x270    │ ~253.86KiB  256k m3u8  │ avc1.4d001e  256k mp4a.40.2  0k
http-256  mp4 480x270    │ ~253.86KiB  256k https │ unknown      256k unknown    0k
hls-832   mp4 640x360    │ ~825.03KiB  832k m3u8  │ avc1.4d001f  832k mp4a.40.2  0k
http-832  mp4 640x360    │ ~825.03KiB  832k https │ unknown      832k unknown    0k
hls-2176  mp4 1280x720   │ ~  2.11MiB 2176k m3u8  │ avc1.640020 2176k mp4a.40.2  0k
http-2176 mp4 1280x720   │ ~  2.11MiB 2176k https │ unknown     2176k unknown    0k
```

**Comment by traplover4200** [comment]
yes im login to firefox

**Comment by bashonly** [comment]
I'll keep this open as a possible issue with twitter authentication.

If you want your download to succeed, though:
 - don't use the format selection argument from your system config
 - don't use `--cookies-from-browser`
 
 It will download just fine as long as you are not selecting a format that doesn't exist and not passing cookies unnecessarily

**Comment by dtaust** [comment]
I ran into this same issue with twitter, i was logged into twitter on firefox and using `--cookies-from-browser firefox` (which was working fine previously) and it just stopped working. Logging out and back in to twitter on firefox fixed it.

**Comment by korkey128k** [comment]
> > i add my twitter login to yt-dlp .netrc but it look like it not loging
> 
> netrc doesn't work with all sites. You need to pass cookies with `--cookies-from-browser` or `--cookies` for twitter auth.
> 
> This isn't relevant to the issue anyways. The issue is caused by your format selection argument.

@bashonly , quick question; why is `--netrc` it in the error message for when twitter needs auth?
```
ERROR: [twitter:spaces] xxxxxxxxxxxxx: This video is only available for registered users. Use --cookies, --cookies-from-browser, --username and --password, --netrc-cmd, or --netrc (twitter) to provide account credentials
```

**Comment by bashonly** [comment]
@korkey128k the discussion in this issue took place 4 months ago. Login/netrc support has since been added to the twitter extractor

**Comment by bashonly** [comment]
Closing since login with credentials support has been added, and the original issue was likely due to an expired session cookie
