### ISSUE TITLE
Embeded yt_dlp 2023.01.06 unable to execute when compiled with pyinstaller windowed flag

### ISSUE THREAD

**Issue by sourabhkv** [yt-dlp/yt-dlp#5999]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.01.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Previous version of yt_dlp 2022.11.11 used to work without any issues

My application is unable to load streams when windowed flag is set

`pyinstaller --icon=logo.ico --windowed --hidden-import yt_dlp.compat._legacy "Youtube-dl GUI.py"`

![Screenshot_20230109_191803](https://user-images.githubusercontent.com/55890376/211323823-5c4ab851-0acd-4e5a-bda4-db995fbdc1ca.png)

When I don't use windowed flag latest version works fine but console window appears

`pyinstaller --icon=logo.ico --hidden-import yt_dlp.compat._legacy "Youtube-dl GUI.py"`

![Screenshot_20230109_192224](https://user-images.githubusercontent.com/55890376/211323856-4492c370-5831-479b-8ff4-16d2c0e679c1.png)

Is there any issue with yt-dlp in windowed mode ? How to fix it?

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
Pls provide minimum code to reproduce the issue

cc @Grub4K - I suspect it's related to changes to VT mode code

**Comment by Grub4K** [comment]
This should fix it. This happens bc `self._out_files` assumes that the stdout/err are not `None`.
```diff
diff --git a/yt_dlp/utils.py b/yt_dlp/utils.py
index 15e1f97cb..8187ea399 100644
--- a/yt_dlp/utils.py
+++ b/yt_dlp/utils.py
@@ -2037,6 +2037,8 @@ def get_windows_version():
 def write_string(s, out=None, encoding=None):
     assert isinstance(s, str)
     out = out or sys.stderr
+    if not out:
+        return

     if compat_os_name == 'nt' and supports_terminal_sequences(out):
         s = re.sub(r'([\r\n]+)', r' \1', s)
```

**Comment by pukkandan** [comment]
> Previous version of yt_dlp 2022.11.11 used to work without any issues

I can reproduce the issue with older versions as well

**Comment by sourabhkv** [comment]
Downgrading to Pyinstaller 5.6.2 works for me

**Comment by pukkandan** [comment]
Interesting. We can apply Grub4k's patch anyway, but it might be worth reporting to Pyinstaller devs

**Comment by Grub4K** [comment]
This is expected (Ref: https://github.com/pyinstaller/pyinstaller/pull/7217). We should check `sys.stdout`/`sys.stderr` manually as per the changed pyinstaller information.

**Comment by Grub4K** [comment]
The above patch (https://github.com/yt-dlp/yt-dlp/issues/5999#issuecomment-1376170084) is still valid. It can be committed as is.

**Comment by pukkandan** [comment]
pls do, adding a comment pointing to https://github.com/pyinstaller/pyinstaller/pull/7217

**Comment by sourabhkv** [comment]
Will it work with Pyinstaller 5.8?

**Comment by Grub4K** [comment]
Yes, it should. We are no longer relying on non compliant behavior anymore.

Closing as completed in https://github.com/yt-dlp/yt-dlp/commit/3b479100df02e20dd949e046003ae96ddbfced57.
