### ISSUE TITLE
yt-dlp for macOS 10.7-10.8

### ISSUE THREAD

**Issue by scrutinizer11** [yt-dlp/yt-dlp#6004]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.01.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I want to ask if it's possible to produce a **yt-dlp** version compatible with older systems of OS X such as 10.7 (aka "Lion") and 10.8 (aka "Mountain Lion"). I have several old machines that can't be updated beyond these systems. Both 10.7 and 10.8 have Python 2.7 - the same version as 10.9 which is supported and allows **yt-dlp** good performance. **youtube-dl** connects via proxy to the Internet, and downloads content from many sites successfully but reports others as unsupported (especially top ones).

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by Grub4K** [comment]
The `yt-dlp` binary for Mac does not work I suppose?

Python 2.7 is not and will not be supported by yt-dlp anymore. If you need backwards compatibility it would make sense to use youtube-dl. Otherwise install the latest Python3 supported by your OS and try running it like that. Otherwise there is sadly not much we can do.

**Comment by RingoTheDog** [comment]
You CAN install python 3 on an older MACOS...however python 2.x will still be the default python install.  
So if you just type python in the terminal, it will initiate the default 2.x python.

In a terminal window you must type python3, then you should be able to run yt-dlp.
