### ISSUE TITLE
How to limit YouTube Music search to tracks only?

### ISSUE THREAD

**Issue by Kilohertz77** [yt-dlp/yt-dlp#6007]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.01.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Is there a way to return only tracks in a YTmusic search? Sometimes music videos have sound effects, while I'm only interested in the original song.

I'm using this command:
`yt-dlp -f bestaudio --playlist-items 1 --default-search "https://music.youtube.com/search?q=" -a list-of-tracks.txt`

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
Give example query, explaining what you are getting, what you expect to get and how you'd do this in website

**Comment by Kilohertz77** [comment]
This query returns the top result, which is the music video of the song:
`yt-dlp -f bestaudio --playlist-items 1 --default-search "https://music.youtube.com/search?q=" "Anna of the North - I Do You"`

The [video version](https://www.youtube.com/watch?v=PcGX3QGFtv8) (which is downloaded by the query above) starts with bird sounds and an alarm clock, while the [single/album track](https://www.youtube.com/watch?v=EsZvqL0jsu0) doesn't have those effects.

On the [YouTube Music search page](https://music.youtube.com/search?q=anna+of+the+north+i+do+you) it's possible to select only tracks. I'm wondering if this can be done by yt-dlp as well.

**Comment by pukkandan** [comment]
> while the [single/album track](https://www.youtube.com/watch?v=EsZvqL0jsu0) doesn't have those effects.

This link gives me "Video unavailable", but I think I understand what u want

![image](https://user-images.githubusercontent.com/6623388/211522728-c8af7130-c263-4bcd-9d06-7a1ae4a6ab0c.png)

You want the equivalent of clicking this, right?

If so, use <https://music.youtube.com/search?q=Anna+of+the+North+-+I+Do+You#songs> as the URL to yt-dlp. The known fragments (`#`) are https://github.com/yt-dlp/yt-dlp/blob/87ebab0615b1bf9b14b478b055e7059d630b4833/yt_dlp/extractor/youtube.py#L6676-L6683

Any other filter can also be used if you find it's params from the devtools. E.g. https://github.com/yt-dlp/yt-dlp/blob/87ebab0615b1bf9b14b478b055e7059d630b4833/yt_dlp/extractor/youtube.py#L6659

**Comment by Kilohertz77** [comment]
That's very helpful, thanks!

One more question: I usually use this with a bunch of tracks in a text file (as in my original question). Is there a way to add the #songs fragment to that query? If not, then I can just add that to every line in the text file.

**Comment by pukkandan** [comment]
No. You will need to add it to each query

**Comment by Kilohertz77** [comment]
That's no problem. Thanks again!

**Comment by vaaski** [comment]
> If so, use [music.youtube.com/search?q=Anna+of+the+North+-+I+Do+You#songs](https://music.youtube.com/search?q=Anna+of+the+North+-+I+Do+You#songs) as the URL to yt-dlp (Note the `#songs`)

This also fixed an issue I ran into where the simple search returned a weird version of the track I actually tried to download, because it seemingly skipped the "Top result" section.
So for the example query `https://music.youtube.com/search?q=Weekend+-+Schatz%2C+du+Arschloch` it chose a track called "Schnaps, du Arschloch! (MFDDNSODUWDDNU EP)" instead of "Schatz, du Arschloch!"

<img width="747" alt="image" src="https://github.com/yt-dlp/yt-dlp/assets/17879327/619db21d-302b-41b3-9912-fcc2d444fcaa">

Appending `#songs` chose the expect one.
