### ISSUE TITLE
Skeptoid.com authenticated podcast feed gets 401, works fine in other tools

### ISSUE THREAD

**Issue by DarkVirtue** [yt-dlp/yt-dlp#6009]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2023.01.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United States of America

### Provide a description that is worded well enough to be understood

When attempting to download the Skeptoid podcast's authenticated premium feed as per the method at the bottom of their page here: https://skeptoid.com/subscribe, yt-dlp reports a 401 error. The same URL works fine in Curl:
```
curl -I "https://NAME_REDACTED%40gmail.com:PASS_REDACTEDskeptoid.com/premium.xml"
HTTP/1.1 200 OK
Date: Tue, 10 Jan 2023 19:15:44 GMT
Server: Apache/2.2.15 (CentOS)
X-Powered-By: PHP/5.6.40
Content-Type: application/rss+xml
```
I'm happy to run tests or other tasks, but the account contains payment info so I will not share access.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--downloader', 'aria2c', '-N16', '--embed-metadata', '--embed-thumbnail', '-o', 'Skeptoid/%(title)s.%(ext)s', 'https://NAME_REDACTED%40gmail.com:PASS_REDACTED@skeptoid.com/premium.xml']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2023.01.06 [6becd25] (pip)
[debug] Python 3.9.2 (CPython x86_64 64bit) - Linux-5.10.0-20-amd64-x86_64-with-glibc2.31 (OpenSSL 1.1.1n  15 Mar 2022, glibc 2.31)
[debug] exe versions: ffmpeg 4.3.5-0, ffprobe 4.3.5-0
[debug] Optional libraries: Cryptodome-3.16.0, brotli-1.0.9, certifi-2020.06.20, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1760 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2023.01.06, Current version: 2023.01.06
yt-dlp is up to date (2023.01.06)
[generic] Extracting URL: https://NAME_REDACTED%40gmail.com:PASS_REDACTED@skeptoid.com/premium.xml
[generic] premium: Downloading webpage
ERROR: [generic] None: Unable to download webpage: HTTP Error 401: Unauthorized (caused by <HTTPError 401: 'Unauthorized'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/usr/local/lib/python3.9/dist-packages/yt_dlp/extractor/common.py", line 680, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.9/dist-packages/yt_dlp/extractor/generic.py", line 2384, in _real_extract
    full_response = self._request_webpage(url, video_id, headers={
  File "/usr/local/lib/python3.9/dist-packages/yt_dlp/extractor/common.py", line 825, in _request_webpage
    raise ExtractorError(errmsg, cause=err)

  File "/usr/local/lib/python3.9/dist-packages/yt_dlp/extractor/common.py", line 807, in _request_webpage
    return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query))
  File "/usr/local/lib/python3.9/dist-packages/yt_dlp/YoutubeDL.py", line 3730, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/usr/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 401: Unauthorized
```

**Comment by bashonly** [comment]
Things to try:

 - Don't replace `@` with `%40` in your username/email
 - If your password contains `$`, make sure you are quoting the URL in *single*-quotes (`'`)
 - Add this to your command `--add-header "Accept:*/*"`

**Comment by bashonly** [comment]
> Using %40 instead of @ is required - see the "Help Using the Premium version" on the podcast's [help page](https://skeptoid.com/subscribe).

Did you try it? It's not "required"; it's a *suggestion* for use with unsupported apps. yt-dlp is able to handle an `@` in the username field of a URL, so it's not needed

If you're not willing to share account details, I think there may be too many variables at play to try to troubleshoot this in the dark

**Comment by DarkVirtue** [comment]
Yes, I tried it. It results in the same 401 error.

I hope we can narrow it down at least a bit since `wget` and `curl` are able to retrieve the XML file from the URL without issue.

I won't share my account info, but I'd be happy to make a donation to the yt-dlp project so you can acquire your own for testing (if that's an option).

**Comment by bashonly** [comment]
Okay, I have a couple more things you could try. But first, if you have a colon (`:`) in your password, to make this easier, you should change your password so that it does not contain `:`

Run the following command in your shell, replacing `YOUR_USERNAME` and `YOUR_PASSWORD` with your actual username and password, and do not escape anything and do NOT use `%40` in place of `@`:
```
python3 -c 'username = r"""YOUR_USERNAME"""; password = r"""YOUR_PASSWORD"""; import base64; print(base64.b64encode(":".join((username, password)).encode()).decode("ascii"))'
```
and then run this yt-dlp command, replacing `OUTPUT` with the actual output of the above command:
```
yt-dlp "https://skeptoid.com/premium.xml" --add-header "Authorization:Basic OUTPUT" -v --downloader aria2c -N16 --embed-metadata --embed-thumbnail -o "Skeptoid/%(title)s.%(ext)s"
```
(note that the user/pass are NOT in the URL)

if that doesn't work, then run this command in your shell, again replacing `YOUR_USERNAME` and `YOUR_PASSWORD` with your actual username and password, again do not escape anything and do not use `%40` in place of `@`:
```
python3 -c 'username = r"""YOUR_USERNAME"""; password = r"""YOUR_PASSWORD"""; import base64; import urllib.parse; print(base64.b64encode(":".join(map(urllib.parse.quote, (username, password))).encode()).decode("ascii"))'
```
and again overwrite `OUTPUT` in the above yt-dlp command with the actual output and try running it again

**Comment by DarkVirtue** [comment]
Adding the `Authorization:Basic` header with the encoded credentials worked. Thanks a bunch!
