### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by Rings4** [yt-dlp/yt-dlp#601]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running yt-dlp version **2021.07.24**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description

Is it possible to record datestamps/timestamps of comments as the exact date they were posted? Currently a comment posted 7 years ago simply says "7 years ago" as its time_text. Really would appreciate an actual date, since relativity goes out the window when you don't even know when the info.json was recorded to begin with (and even if you do, it's still not as nice as an actual date).

**Comment by pukkandan** [comment]
See the `timestamp` field

**Comment by Rings4** [comment]
> 
> 
> See the `timestamp` field

My apologies, I didn't recognize the format the timestamp field was in and thought it simply meant whether or not the comment linked to a timestamp in the vid. I looked it up on the main page and it said it's in UNIX format, which I just looked up as well. Looks like I learned two things here haha. 

Thanks for the help, sorry about that!

**Comment by coletdjnz** [comment]
Note that the timestamp field is calculated based off the time text string, so it's not super accurate. YouTube doesn't provide the true timestamp for comments :(
