### ISSUE TITLE
[--downloader ffmpeg] keys in vk.com audio download not the whole stream, but only a part

### ISSUE THREAD

**Issue by qzmtch** [yt-dlp/yt-dlp#6012]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2023.01.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

when you click play audio on the VK website, you can see the m3u8 link in the developer tools
here is an example
https://cs1-41v4.vkuseraudio.net/s/v1/ac/HpCT4v3Hm5cFqZrR8siwUlcSZkiwznbOR4rnv3fyINnL_GlikhB-EEYy3tQ37_ietRtU3Tr3xJMNnYPtoyFxbjZh7CmuCX4-2hgvxEz2ZBGIO-hZdD74ylVtVV1wa-1ackduw6AbvIu2VvZHYFkQk0Lmo9EMTm3OnWm21Gm3IA/index.m3u8
there is a link to the key
#EXT-X-KEY:METHOD=AES-128,URI="https://cs1-........
everything is fine with this, yt-dlp can do it all
but when you pass the link to the program, it offers to download with the keys
`WARNING: Live HLS streams are not supported by the native downloader. If this is a livestream, please add "--downloader ffmpeg --hls-use-mpegts" to your command`
having tried to download with these keys, I got a file with a size and duration less than the source

check for yourself, here are two launches on the first one, the full record is downloaded as is, and on the second it is cropped, at 25 seconds it can be seen
`yt-dlp --downloader ffmpeg --hls-use-mpegts https://cs1-41v4.vkuseraudio.net/s/v1/ac/HpCT4v3Hm5cFqZrR8siwUlcSZkiwznbOR4rnv3fyINnL_GlikhB-EEYy3tQ37_ietRtU3Tr3xJMNnYPtoyFxbjZh7CmuCX4-2hgvxEz2ZBGIO-hZdD74ylVtVV1wa-1ackduw6AbvIu2VvZHYFkQk0Lmo9EMTm3OnWm21Gm3IA/index.m3u8`

`yt-dlp --hls-use-mpegts https://cs1-41v4.vkuseraudio.net/s/v1/ac/HpCT4v3Hm5cFqZrR8siwUlcSZkiwznbOR4rnv3fyINnL_GlikhB-EEYy3tQ37_ietRtU3Tr3xJMNnYPtoyFxbjZh7CmuCX4-2hgvxEz2ZBGIO-hZdD74ylVtVV1wa-1ackduw6AbvIu2VvZHYFkQk0Lmo9EMTm3OnWm21Gm3IA/index.m3u8`
you can also add -x key to immediately download mp3, but this is not necessary

I don’t know only with VK such a problem or with some other sites, or is it just a ffmpeg problem

taking this opportunity not to open a separate request, can I ask you to add a download for such links that are in the m3u file?
https://i.imgur.com/CdK3tgy.png
the program can download from these links, but to add names, this must be done separately with an extractor with authorization (I saw somewhere that this was in your plans by the way)
it is convenient to form such a list yourself with a browser extension, and then use such a playlist to listen to in players that support streams encrypted with a key e.g. aimp
but it would be convenient to transfer this file to yt-dlp and have it download these files and write down the names

so that you can download playlists without authorization with something like this request
`yt-dlp -x --hls-use-mpegts --m3u FILE`

Thank you 😘

### Provide verbose output that clearly demonstrates the problem

- [x] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [x] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
vk is serving mp3 audio fragmented as .ts files

remove `--downloader ffmpeg` and `--hls-use-mpegts`
add `--fixup never`

vk audio pages are not yet supported by the vk extractor, see #5886

**Comment by qzmtch** [comment]
> vk is serving mp3 audio fragmented as .ts files
> remove --downloader ffmpeg, remove --hls-use-mpegts
> add --fixup never
ok, i got it
> vk audio pages are not yet supported by the vk extractor, see https://github.com/yt-dlp/yt-dlp/issues/5886
I know that, but did you read my post? 
can you answer me here so that I do not create a request? (Or do I need to create a request?)
Can you add an m3u key so that you can download from these links from VK? so that yt-dlp itself save names from the m3u file to audio? 
on such a line so that you can download
`yt-dlp -x --fixup never --m3u FILE`

**Comment by qzmtch** [comment]
these links were obtained a long time ago, in the savefrom extension 
Can I add this function separately from the VK site?
you can get these links from wall posts and playlists with an extension and form an m3u playlist with names, and then download using yt-dlp

I don’t know how the savefrom extension works there now, but I want to make an extension later that will form such an m3u list, it’s convenient to listen to it in aimp, and if possible it would be convenient to download directly through yt-dlp

as an exception, please add this function, it's not difficult for you, just take the names from the line above the link and that's it, everything else already works for you
Oh please 😉👌

**Comment by qzmtch** [comment]
where did i get the links from?
well, for example, this link https://vk.com/wall-81977208_1369  opens without authorization, and the audio is played, you open the developer tools and there this link https://i.imgur.com/0cxRRqL.png

**Comment by bashonly** [comment]
Ah okay, it looks like I slightly misunderstood your OP. So the M3U playlist containing the m3u8 URLs is being generated by a browser extension and not served by the site itself?

M3U (not m3u8) playlist parsing would need to be implemented in order for this to work as you describe, and since I don't know of any sites that directly serve M3U playlists, I think this might be out-of-scope.

However, you can use the m3u file with `--batch-file` to download all of the URLs in it.

Ideally, support for vk audio would be added to yt-dlp, and then these browser-extension-generated m3u files would no longer be needed, yeah?

**Comment by qzmtch** [comment]
> ( `yt-dlp --fixup never -o "%(id)s-some_filename.mp3" "URL"` )

By the way, here you still need to add the X key, because without it the file in aimp is played back, so you can’t use the rewind bar
here is the first file with the X key, and the second one without https://i.imgur.com/m34EGjO.gif

**Comment by qzmtch** [comment]
> Ah okay, it looks like I slightly misunderstood your OP. So the M3U playlist containing the m3u8 URLs is being generated by a browser extension and not served by the site itself? 

yes, I used to make such lists in order to listen in the player without downloading, it’s convenient if you don’t want to clog your hard drive with music, it would be convenient if you could download these files directly from the same file

here is a link to the playlist https://vk.com/music/playlist/368679629_77069764 and here is such a m3u 
`#EXTM3U
#EXTINF:-1,Darren Mase - Take That Record Off (Original Mix)
https://cs1-78v4.vkuseraudio.net/s/v1/ac/ulk-Zm9v9V9bzUZX1HS1z16mwqBnaqdpEKH0H-hq9CQzDNX1uDqDDBIzgMqYteNE-1HRCugO9_G-JdprU-a-S2Z1l0qLo8y2JKL4hZe07E70SGZwoRne4K-JN-Zu6dgIXbp2KRAPHaSokI/index.m3u8
#EXTINF:-1,Laura Branigan - Self Control (Extended Version)
https://cs1-69v4.vkuseraudio.net/s/v1/ac/7vmeHhkT_WnGay33mEH3yt7mQaVSIp0vbed6nztxZf-yBO6q_DyBT8gLRjmux9ucO-pQisC9mVX6QtAL1RSytcuykryvUHtDxA-ZNuB2ZAzMysirkww0UxljDINX8h9uYBwNIzglw2v3HpRfWfF1N8/index.m3u8
#EXTINF:-1,Hi_Tack - Say Say Say [Waiting 4 U] (Extended Mix)
https://cs1-64v4.vkuseraudio.net/s/v1/ac/5LIrg9y9uz8woGiGpcSbY31Cg87NtIUtUE1bJZTipgesBx6DUSxadBnpeWTVcl9qMgHDm9OUrJyTt9IJsNuA3LqmnBlAilbDnLzKVY2gWibMTcyVMuw/index.m3u8
#EXTINF:-1,Bacon Popper - Free
https://cs1-50v4.vkuseraudio.net/s/v1/ac/B1q3ZykjQugZDy-Qz10BvIDtvatZiexuXeijDtppskkK0MUkOU6XkixQ_gE3s-bPZMqiJbQW8F0bGRT6jAya3xsqGLv5Rp2U6rPFKVr53qTz9rSh7OwPJ0W5GsjT7rNYw7C2-SPg/index.m3u8
#EXTINF:-1,Fentura - Live It
https://cs1-44v4.vkuseraudio.net/s/v1/ac/NQDLBuT7kCydblEwSffoBmDzYxASiW-69w6RwJiQeYi7hmBPUV3YCXzfp1dALTPi7I0o4EqX8MXMxBzxy0-G9UI6xWYz3XUqWhKEJYo8WC1jX3-yLao50j_qjglUIToqaAl_D3W4MTY/index.m3u8
#EXTINF:-1,Lower East Side - Sword Fight (Lee Cabrera Mix)    [stps]
https://cs1-80v4.vkuseraudio.net/s/v1/ac/ZC_7EtdpycAiVzx_LX6jVPvkxfGvorg1htzxROZPjEf9z_AH-4JQjbXofSO-xrIqzcSPnBqFLim8iGe4dW-MF2YtOKyu4wTYov54r9xcP4LM1DqPHAZpZibklEbhr8Q31UGlmYo/index.m3u8
#EXTINF:-1,Paul Van Dyk Feat. Rea Garvey - Let Go [320]
https://cs1-41v4.vkuseraudio.net/s/v1/ac/D8q0WFVxEeTQ3ZOZvfjyFWe1BVDlMvh5I4DEujj9t0_t8DGPIyHa0xyDkTdrXXt1XNO2-0KDRuZN94H9DJxHZMn9qm0Rieo-VNLfEG8Rww5HOwf1_zNLjaFV45fcy79XgAqo/index.m3u8
#EXTINF:-1,Colder - To The Music (Lotterboys Dub)
https://cs1-46v4.vkuseraudio.net/s/v1/ac/w9wAkGJ5AB21vWm2-KX4_QECaB0qSGlgUk154l7jAisDN3Qe8v2AMohYwvuB7KCC0xzJ6DD3hl7An-WHNJqgkZ1Rt04k1GfdW4-TXptKtv-JITi2DEJWUY8VOOdW86-dnVBcBmEsnF1scjo8/index.m3u8
#EXTINF:-1,I-F [Interr-Ference] - Space Invaders Are Smoking Grass
https://cs1-80v4.vkuseraudio.net/s/v1/ac/KiWAOmtj8GH-pOn8JksBfRetAJlbwaMy6MS3-IDCQB06kqpieeO6XUDve3d9FuwSZJFcP-9yqMOcyKV3yjM56EsRuP3yrDV7VRHfR-yUuoGqNX4tM2oVfXvZJjEP7BAWI/index.m3u8
#EXTINF:-1,The Youngsters - Third Knife
https://cs1-78v4.vkuseraudio.net/s/v1/ac/tsXC8-OcvHx0aeMXlcUZ55R0YFszw3vv4y3TjB19HwgkWYzTp9QGM7qOMhwPKbK0-S2KdxFiGO0d8kAi9tqOkh4dsUteNqO5ocvt0nstQ96i5EixF7k/index.m3u8
#EXTINF:-1,rekorder - Rekorder 0
https://cs1-58v4.vkuseraudio.net/s/v1/ac/YNdo1y3dYYT1c6-iUnD19Op3aYYFYyYImNwcdK-LIckP3_YhP87q9--8iMX9Jn1O7GZSn-Uffa6Ja3HOqS3YMePo5J5xJNf9ISqF_5KaOqRy69FzzldBf8bJfHWZ-OqBXkKU/index.m3u8
#EXTINF:-1,D.I.M. - Is You
https://cs1-52v4.vkuseraudio.net/s/v1/ac/lxCvIWRaT6irS3ZSb1sbJGEzQVBcn9tJvgtva4NcH08YuQBTX8fAmcMTQq-ghucdBL8JRZOXmeWNkc8hr6PmYF5T5qA497bAd64aqJRdA/index.m3u8
#EXTINF:-1,Luetzenkirchen - Lazy Dog Bites The Dirt
https://psv4.vkuseraudio.net/s/v1/a2/0JCDQaWJW3R2G5GGkoCbe5NaljhOR0mlETIxAjqGKKXM-Ha4MtRlLTEDoch1VsnXdFz7OJPpm7H5_M6gy7H7IX_dl7__MZleq5Ddppd6gJPMYch7w2Qtg/index.m3u8
#EXTINF:-1,Nenes & Pascal Feliz  -  Platinum (Original Mix)
https://cs1-60v4.vkuseraudio.net/s/v1/ac/SXUQ_mG1hkp9WLanK1UtsBhv-2WPceWLS9183sZmssO4fcBiybNf_gupsK09h8V_gWudnOWaIpO-uFcto90YiPA9Tmu7hPcGWMRQgeikZZ_zMCjiR-BG9Dqd10oI6phJy4/index.m3u8
#EXTINF:-1,DJ Layla feat. Dee-Dee - Single Lady
https://cs1-67v4.vkuseraudio.net/s/v1/ac/uFyHgwq_IXk61vUWM_2AxsUcN-PuyZkdR3bio-5WgsClkEG-7SWqVdIUMzU8v9cN15F86iKRlNDAPlnQiJ9ZuOX6rJc-XDYTwQ0SxqqkZLOqerU112E/index.m3u8`

it's big so that's enough, in these links, I randomly deleted some of the tokens
I made these links during authorization more than a year ago, I don’t know if they affect something or not, I checked without authorization in incognito, now links with other tokens, so I gave without my links

**Comment by qzmtch** [comment]
By the way, these links in VK access without authorization, and the audio is played
https://vk.com/hiphop?w=wall-29691388_175497 group wall posts
https://vk.com/music/album/-2000929577_16929577_a0bcbffe4fc6f9a008 artist albums
https://vk.com/music/playlist/-147845620_1337_316cb05651eec6d2f9 playlists
https://vk.com/audio-2001432294_35432294 audio
https://vk.com/artist/theegg_mtuyotk3mzizna artist
https://vk.com/artist/theegg_mtuyotk3mzizna/releases on this page, all releases of the artist are also without authorization using links such as https://vk.com/music/album/-2000508018_3508018
authorization is needed only for the user's pages https://vk.com/audios49476636 , playlists of his recommendations, and audio groups https://vk.com/audios-29691388
for now, you can add to the extractor those links that are available without authorization, and then finish with authorization 😉👌

**Comment by qzmtch** [comment]
full file is downloaded from the walls, and from playlists without audio authorization it takes 30 seconds, so yes, you need to do authorization 😉🤞

**Comment by pukkandan** [comment]
> M3U8 uses the same file structure as M3U [en.wikipedia.org/wiki/M3U](https://en.wikipedia.org/wiki/M3U)

That is exactly the problem. Given a manifest, we can't easily tell if the links are fragments of the same video (m3u8) or a playlist of multiple videos (m3u)



> `yt-dlp -x --fixup never --m3u FILE`

As bashonly said, a new switch just for this usecase is out of scope imo considering no known site actually provides such manifests

I also don't fully understand your usecase, specifically the part about "not needing authorization". You need to pass the same headers irrespective of whether the links are manually passed, or put inside an m3u. If all you want is to download the multiple URLs with different filenames, why not just write the file as a batch/sh script instead of as an m3u? It'll just look like:
```
yt-dlp -o "FILENAME1" "URL1"
yt-dlp -o "FILENAME2" "URL2"
```
instead of 
```
#EXTINF:-1,FILENAME1
URL1
#EXTINF:-1,FILENAME2
URL2
```

**Comment by qzmtch** [comment]
> As bashonly said, a new switch just for this usecase is out of scope imo considering no known site actually provides such manifests

OK, thanks


> I also don't fully understand your usecase, specifically the part about "not needing authorization". You need to pass the same headers irrespective of whether the links are manually passed, or put inside an m3u.

from group wall posts, attached audio is played in full size, without authorization https://vk.com/hiphop?w=wall-29691388_175501, and all other audio from other pages, such as playlists or tracks, is only played for 30 seconds https://vk.com/music/playlist/-1040165_73802259_51853ba3f01acaaef4



> If all you want is to download the multiple URLs with different filenames, why not just write the file as a batch/sh script instead of as an m3u?

write an extension to the browser that will immediately generate such a list? or in cmd immediately read m3u and transfer parameters to the program?
i have a m3u file with 1960 songs, how can I download them through yt-dlp so that each has its own name?
I understand that a batch file can be generated from m3u in some notepad++, but it seemed to me that it would be more convenient to just point m3u file to yt-dlp
ok, let's wait for authorization

But in the batch download option, you can’t add such an option, where there would be a name on one line, and a link on the second, and so that the program substitutes it itself?
to have a file like this, maybe in order for the program to understand that this is a file with names, make it with a different extension, not txt, but some other
```FREE FLOW FLAVA - Final Round
https://cs1-58v4.vkuseraudio.net/s/v1/ac/QY2qpuFLyDTsw8TocHhDdckL25Ouq4-BwMAnsCIvZNz4UhEUu0xO0jkwfvGBYtgtN45u9Y8BIV9nNmUoFvNqNwNueWs_ZeQTVIVfRPGZMAAfytubUvIBGta3W_A-tCmgk-LkR-Topp1MhouOWZDec5az8ZdRrxGmdJnSrBs8zYo-OsI/index.m3u8
22Bullets, Joe Kox - Hot
https://cs1-82v4.vkuseraudio.net/s/v1/ac/fSVUn3yspGwJfNVPc-fYbq9IBZqG8SfijAQBiv7Z5uQ0InUE6ZrQ1kqcg50yGL5-vEca6LfqZvSIHe9cFkW_NPVeqJ7cl3PEeBAVI08BbFl4qmakEQ06XeV1vTizCDYrGqSO_fszhubs0KhPya-tu01cWj61GUenp5CxGFMguuZTq_s/index.m3u8```

or one where both the title and the link are written on each line at once
```-o "FREE FLOW FLAVA - Final Round" https://cs1-58v4.vkuseraudio.net/s/v1/ac/QY2qpuFLyDTsw8TocHhDdckL25Ouq4-BwMAnsCIvZNz4UhEUu0xO0jkwfvGBYtgtN45u9Y8BIV9nNmUoFvNqNwNueWs_ZeQTVIVfRPGZMAAfytubUvIBGta3W_A-tCmgk-LkR-Topp1MhouOWZDec5az8ZdRrxGmdJnSrBs8zYo-OsI/index.m3u8
-o "22Bullets, Joe Kox - Hot" https://cs1-82v4.vkuseraudio.net/s/v1/ac/fSVUn3yspGwJfNVPc-fYbq9IBZqG8SfijAQBiv7Z5uQ0InUE6ZrQ1kqcg50yGL5-vEca6LfqZvSIHe9cFkW_NPVeqJ7cl3PEeBAVI08BbFl4qmakEQ06XeV1vTizCDYrGqSO_fszhubs0KhPya-tu01cWj61GUenp5CxGFMguuZTq_s/index.m3u8```
Can't this be added?

**Comment by pukkandan** [comment]
> or one where both the title and the link are written on each line at once
> 
> ```
> -o "FREE FLOW FLAVA - Final Round" https://cs1-58v4.vkuseraudio.net/s/v1/ac/QY2qpuFLyDTsw8TocHhDdckL25Ouq4-BwMAnsCIvZNz4UhEUu0xO0jkwfvGBYtgtN45u9Y8BIV9nNmUoFvNqNwNueWs_ZeQTVIVfRPGZMAAfytubUvIBGta3W_A-tCmgk-LkR-Topp1MhouOWZDec5az8ZdRrxGmdJnSrBs8zYo-OsI/index.m3u8
> -o "22Bullets, Joe Kox - Hot" https://cs1-82v4.vkuseraudio.net/s/v1/ac/fSVUn3yspGwJfNVPc-fYbq9IBZqG8SfijAQBiv7Z5uQ0InUE6ZrQ1kqcg50yGL5-vEca6LfqZvSIHe9cFkW_NPVeqJ7cl3PEeBAVI08BbFl4qmakEQ06XeV1vTizCDYrGqSO_fszhubs0KhPya-tu01cWj61GUenp5CxGFMguuZTq_s/index.m3u8
> ```
> 
> Can't this be added?

Just add a `yt-dlp` in front of the lines, and you have a shell script! So what's the point of natively supporting it?
