### ISSUE TITLE
Emergency Download

### ISSUE THREAD

**Issue by lollita** [yt-dlp/yt-dlp#6013]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.01.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

I normally use a ram disk as download destination.
Sometimes enough space is not enough and the download abort.
Do it is possible to add a secondary download location to use when not have space in primary?

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by flashdagger** [comment]
Did you consider an OS based solution (e.g. [mergerfs](https://github.com/trapexit/mergerfs))?

**Comment by lollita** [comment]
mergerfs is interessant.
but I refer to Windows and prefer to mantain file system distinction.

**Comment by pukkandan** [comment]
A native solution is not in scope imo. If an OS-based solution is not possible, you can write a script to look at the available disk space and pass the needed path to yt-dlp

**Comment by lollita** [comment]
But how I know the need space to download (file size + working space) in advance?

**Comment by pukkandan** [comment]
yt-dlp may not know it in advance either. If it does, you can get it with

    yt-dlp -O %(filesize,filesize_approx)s "URL"

During postprocessing, there can be 2 copies of the file at any given time. So assume total needed space is double this

**Comment by lollita** [comment]
yt-dlp -O %(filesize,filesize_approx)s "https://mediapolisvod.rai.it/relinker/relinkerServlet.htm?cont=XkEMRDhg1RssSlashpKJktohXbHgeeqqEEqualeeqqEEqual"

I get NA.

**Comment by pukkandan** [comment]
Like I said, we don't always know the filesize before download starts

**Comment by lollita** [comment]
ok, ty.
