### ISSUE TITLE
[plugins] precedence over native extractors

### ISSUE THREAD

**Issue by flashdagger** [yt-dlp/yt-dlp#6015]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.01.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Since native plugin support from python packages was shipped with the last release I started to detach some of my published packages from `ytdlp-plugins`. Thanks for the effort @coletdjnz and @pukkandan.

Here is my question:
Is it possible or planned to disable or replace an extractor from `yt_dlp.extractor`?

Extractors are looked up by `.ie_key()`. If a plugin uses an existing classname (or key) the matching process will still use the `_VALID_URL` of the native extractor or its `LazyLoadExtractor` class but then call `_real_extract()` of the plugin extractor.
This is due to the `yt_dlp.extractor.extractors._ALL_CLASSES` list, where plugin extractors are inserted at the beginning.
`YoutubeDL` will then build a mapping from that list. Duplicate keys will then cause that the plugin class will be overwritten with the native one.

My (dirty) solution so far is to set `_ENABLED=False` for the native class itself and its `LazyLoadExtractor` counterpart.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by Grub4K** [comment]
Doesn't an Override Plugin Extractor handle this case (`plugin_name="..."`)? Generally a name should not be duplicated in any case, if I understood correctly.

**Comment by coletdjnz** [comment]
Yes it's possible as Grub has mentioned, there's a mention of how to do it here (and check out pukkandans plugins which do it too): https://github.com/yt-dlp/yt-dlp#developing-plugins

**Comment by flashdagger** [comment]
I tried the example with `plugin_name=...` but it doesn't have an effect if you want to change `_VALID_URL` as it is sometimes the use case. So I understand you should chose an unused class name. This should be mentioned in the docs or maybe yt-dlp can output a warning.

In another case I wanted to explicitly disable an extractor to let deal `GenericIE` with the embedded urls and call `_extract_embed_urls()` of the plugin extractor. Is this possible?

**Comment by coletdjnz** [comment]
> I tried the example with `plugin_name=...` but it doesn't have an effect if you want to change `_VALID_URL` as it is sometimes the use case. So I understand you should chose an unused class name. This should be mentioned in the docs or maybe yt-dlp can output a warning.
> 
> In another case I wanted to explicitly disable an extractor to let deal `GenericIE` with the embedded urls and call `_extract_embed_urls()` of the plugin extractor. Is this possible?

You might be fighting with the likes of lazy loading among other things. If it's a built in one then it's probably better to use `--ies` to disable it.

@pukkandan not sure if you have any better ideas.

**Comment by flashdagger** [comment]
> You might be fighting with the likes of lazy loading among other things. If it's a built in one then it's probably better to use `--ies` to disable it.

Lazy loading is totally fine as it saves loading time and can be disabled by environment variable. But do you guys see it as legitimate that a plugin module can disable a builtin extractor to exclude it from the matching set?

**Comment by pukkandan** [comment]
> I tried the example with plugin_name=... but it doesn't have an effect if you want to change _VALID_URL as it is sometimes the use case.

Can you give example code? It is probably fixable in core code. Alternately, the plugin can just match the URL. For example:
```py
class My_YTIE(InfoExtractor):
    _VALID_URL = YoutubeIE._VALID_URL
    ...
```
will take precedence over `YoutubeIE` when a relevant URL is passed by user. But unlike plugins, this does not handle redirects from other extractors. E.g.

https://github.com/yt-dlp/yt-dlp/blob/87ebab0615b1bf9b14b478b055e7059d630b4833/yt_dlp/extractor/freespeech.py#L29

---

> But do you guys see it as legitimate that a plugin module can disable a builtin extractor to exclude it from the matching set?

I don't think this should be supported[^1]. But what is your use-case? Given sufficient reason, I may reconsider

[^1]: Ofc, we can't really prevent the plugin from achieving this with Python magic either

**Comment by flashdagger** [comment]
One example is the extractor for youmaker.com I want embedded URLs to be handled via GenericIE, but some domains like theepochtimes.com are now intercepted by a specialized extractor...

**Comment by pukkandan** [comment]
You could write an extractor like this, no?
```py
class YoumakerEmbedPassthroughIE(InfoExtractor):
    _VALID_URL = TheEpochIE._VALID_URL

    def _real_extract(self, url):
        return self.url_result(url, GenericIE)
```

**Comment by flashdagger** [comment]
This seems to work. So the basic conclusion is to intercept the undesired match by an additional extractor, which will also be reflected in the log.
