### ISSUE TITLE
ERROR: [generic] None: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>);

### ISSUE THREAD

**Issue by prisoneer** [yt-dlp/yt-dlp#6016]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2023.01.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

I am paying for online courses at softuni.bg and I was downloading the videos to watch them at work (no internet there). So far I was able to download everything but today I received this error

ERROR: [generic] None: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>);

Here's the full cmd text:

`C:\Users\user>yt-dlp "https://videos.softuni.bg/hls/PROFESSIONAL-MODULES/2023/FRONT-END/2023-01-HTML-CSS/20230110/20230110-HTML-1-,720p,480p,240p,.mp4/urlset/master.m3u8"
[generic] Extracting URL: https://videos.softuni.bg/hls/PROFESSIONAL-MODULES/2023/FRONT-END/2023-01-HTML-CSS/20230110/20230...4/urlset/master.m3u8
[generic] master: Downloading webpage
ERROR: [generic] None: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

C:\Users\user>yt-dlp -U
Latest version: 2023.01.06, Current version: 2023.01.06
yt-dlp is up to date (2023.01.06)`

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://videos.softuni.bg/hls/PROFESSIONAL-MODULES/2023/FRONT-END/2023-01-HTML-CSS/20230110/20230110-HTML-1-,720p,480p,240p,.mp4/urlset/master.m3u8']
[debug] User config "C:\Users\user\AppData\Roaming\yt-dlp\config.txt": ['-f', 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best', '-i', '-o', 'D:/Courses/%(title)s.%(ext)s', '--no-mtime']
[debug] Encodings: locale cp1251, fs utf-8, pref cp1251, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2023.01.06 [6becd25] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.17763-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 2021-02-02-git-2367affc2c-full_build-www.gyan.dev, ffprobe 2021-02-02-git-2367affc2c-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.16.0, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1760 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2023.01.06, Current version: 2023.01.06
yt-dlp is up to date (2023.01.06)
[generic] Extracting URL: https://videos.softuni.bg/hls/PROFESSIONAL-MODULES/2023/FRONT-END/2023-01-HTML-CSS/20230110/20230110-HTML-1-,720p,480p,240p,.mp4/urlset/master.m3u8
[generic] master: Downloading webpage
ERROR: [generic] None: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 680, in extract
  File "yt_dlp\extractor\generic.py", line 2384, in _real_extract
  File "yt_dlp\extractor\common.py", line 825, in _request_webpage

  File "yt_dlp\extractor\common.py", line 807, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 3730, in urlopen
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

**Comment by bashonly** [comment]
* add `--referer "URL"` to your yt-dlp command, replacing `URL` with the actual URL of the webpage that you are getting the m3u8 link from
* add `--cookies-from-browser chrome` to your yt-dlp command, or replace `chrome` with the name of the browser that you are logged into the site with

If that doesn't work, it's possible that there are other HTTP headers required by the site. You could look in your browser's dev tools and see what other headers your browser is sending with the request for the m3u8. You can use the `--add-header` option to pass these to yt-dlp, e.g. `--add-header "Accept:*/*"`

**Comment by sistematico** [comment]
> * add `--referer "URL"` to your yt-dlp command, replacing `URL` with the actual URL of the webpage that you are getting the m3u8 link from
> 
>     * add `--cookies-from-browser chrome` to your yt-dlp command, or replace `chrome` with the name of the browser that you are logged into the site with
> 
> 
> If that doesn't work, it's possible that there are other HTTP headers required by the site. You could look in your browser's dev tools and see what other headers your browser is sending with the request for the m3u8. You can use the `--add-header` option to pass these to yt-dlp, e.g. `--add-header "Accept:*/*"`

First two steps solved for me, thank you.

**Comment by jhriyaz** [comment]
> * add `--referer "URL"` to your yt-dlp command, replacing `URL` with the actual URL of the webpage that you are getting the m3u8 link from
> * add `--cookies-from-browser chrome` to your yt-dlp command, or replace `chrome` with the name of the browser that you are logged into the site with
> 
> If that doesn't work, it's possible that there are other HTTP headers required by the site. You could look in your browser's dev tools and see what other headers your browser is sending with the request for the m3u8. You can use the `--add-header` option to pass these to yt-dlp, e.g. `--add-header "Accept:*/*"`

it worked for me as well.thanks.

**Comment by trdaya** [comment]
> * add `--referer "URL"` to your yt-dlp command, replacing `URL` with the actual URL of the webpage that you are getting the m3u8 link from
> * add `--cookies-from-browser chrome` to your yt-dlp command, or replace `chrome` with the name of the browser that you are logged into the site with
> 
> If that doesn't work, it's possible that there are other HTTP headers required by the site. You could look in your browser's dev tools and see what other headers your browser is sending with the request for the m3u8. You can use the `--add-header` option to pass these to yt-dlp, e.g. `--add-header "Accept:*/*"`

Worked. Thanks mate!

**Comment by word4adobe** [comment]
> > * add `--referer "URL"` to your yt-dlp command, replacing `URL` with the actual URL of the webpage that you are getting the m3u8 link from
> >   
> >   * add `--cookies-from-browser chrome` to your yt-dlp command, or replace `chrome` with the name of the browser that you are logged into the site with
> > 
> > If that doesn't work, it's possible that there are other HTTP headers required by the site. You could look in your browser's dev tools and see what other headers your browser is sending with the request for the m3u8. You can use the `--add-header` option to pass these to yt-dlp, e.g. `--add-header "Accept:*/*"`
> 
> First two steps solved for me, thank you.

can you explain how to be ?

**Comment by Happosai17** [comment]
> [!CAUTION]
> This comment may contain links to malicious content. **DO NOT** follow any links below

I have the same error trying to download a google drive video. Any hints? 
C:\Users\m.toblini\Downloads>yt-dlp_x86 --cookies cookies.txt --no-check-certificates https://drive(dot)google.com/file/d/1ZoiOtjUGscrNVrHt5i3fF3Gl-gay3C3J/view?usp=drive_link
[GoogleDrive] Extracting URL: https://drive(dot)google.com/file/d/1ZoiOtjUGscrNVrHt5i3fF3Gl-gay3C3J/view?usp=drive_link
[GoogleDrive] 1ZoiOtjUGscrNVrHt5i3fF3Gl-gay3C3J: Downloading video webpage
ERROR: [GoogleDrive] 1ZoiOtjUGscrNVrHt5i3fF3Gl-gay3C3J: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: Forbidden>)
