### ISSUE TITLE
[Site Request] Paramount Plus Entire Shows

### ISSUE THREAD

**Issue by moom0o** [yt-dlp/yt-dlp#602]
## Checklist

- [x] I'm reporting a site feature request
- [x] I've verified that I'm running yt-dlp version **2021.07.24**
- [x] I've searched the bugtracker for similar site feature requests including closed ones

## Description

If I download a single episode it downloads fine, however I would like to bulk download entire shows. 
![image](https://user-images.githubusercontent.com/48740106/127751121-13367624-1eb9-4942-aa82-45d30baa490c.png)

**Comment by Ashish0804** [comment]
`https://www.paramountplus.com/shows/drake-josh/xhr/episodes/page/0/size/100000/xs/0/season/0/`
This gives the json with episodes
`season/0/` implies that you want all episodes for all seasons.
changing it to any other number will give you episodes for that season if it exists.
Only problem with getting all episodes is that they are not in any order(like tubitv)

I'll make a PR for this soon

**Comment by spookyahell** [comment]
This issue isn't really fixed yet.

yt-dlp is giving me 50 episodes, my show has
Season 1: 27 Episodes
Season 2: 45 Episodes
Season 3: 40 Episodes

[Link to show](https://www.paramountplus.com/shows/house-of-anubis/)
