### ISSUE TITLE
outtmpl incompatibility with youtube-dl

### ISSUE THREAD

**Issue by ThomasFreedman** [yt-dlp/yt-dlp#6028]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.01.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Why doesn't yt-dlp accept the outtmpl value I used with youtube-dl, and why does line 3350 refer to the self.params dictionary with an additional ['default'] string index?  

Python3 version is 3.9. 

This is the value of the outtmpl parameter: 
`/home/owner/Code/scripts/ytDL/PSMG/%(id)s~^~%(duration)s~^~.%(ext)s`

And this is the entire ydl.params dictionary I'm using. The value of the 'outtmpl' key is exactly as it was for youtube-dl. It includes a full path definition

{'retries': 5, 'format': 'best', 'continuedl': True, 'ignoreerrors': True, 'merge-output-format': 'mp4', 'downloader': 'aria2c', 'downloader-args': "aria2c:'-c -j 3 -x 3 -s 3 -k 1M'", 'writeinfojson': True, 'progress_hooks': [<bound callback method>], 'download_archive': '/home/owner/Code/scripts/ytDL/youtube-dl.history', 'restrictfilenames': True, 'compat_opts': set(), 'forceprint': {}, 'print_to_file': {}, 'outtmpl': '/home/owner/Code/scripts/ytDL/PSMG/%(id)s~^~%(duration)s~^~.%(ext)s', 'http_headers': {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.63 Safari/537.36', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'Accept-Language': 'en-us,en;q=0.5', 'Sec-Fetch-Mode': 'navigate'}, 'playlistend': 300}

The url list I'm passing to ydl.download is:
` ['https://www.youtube.com/watch?v=dzFKG6rkWpU', 'https://www.youtube.com/watch?v=0g1Q4fBDp2U']`

The program creates a set of generic options for all downloads in dlOpts, then:
```
with yt_dlp.YoutubeDL(dlOpts) as ydl:
   ...  <-- code to create specific options for this download operation & these URLs, such as:
   ydl.params['outtmpl'] = "/home/owner/Code/scripts/ytDL/PSMG/%(id)s~^~%(duration)s~^~.%(ext)s"
   ydl.download(newUrls) 

```
__exception__ = {tuple: 3} (<class 'TypeError'>, TypeError('string indices must be integers'), <traceback object at 0x7fb73edf5b00>)
 0 = {type} <class 'TypeError'>
 1 = {TypeError} string indices must be integers
 2 = {traceback} <traceback object at 0x7fb73edf5b00>
 __len__ = {int} 3

### NOTE: I am importing yt_dlp into my python3 program, not using yt-dlp from command line.
- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output
 From Pycharm debug console:
```
 params = {dict: 17} {'retries': 5, 'format': 'best', 'continuedl': True, 'ignoreerrors': True, 'merge-output-format': 'mp4', 'downloader': 'aria2c', 'downloader-args': "aria2c:'-c -j 3 -x 3 -s 3 -k 1M'", 'writeinfojson': True, 'progress_hooks': [<bound callback method>], 'download_archive': '/home/owner/Code/scripts/ytDL/youtube-dl.history', 'restrictfilenames': True, 'compat_opts': set(), 'forceprint': {}, 'print_to_file': {}, 'outtmpl': '/home/owner/Code/scripts/ytDL/PSMG/%(id)s~^~%(duration)s~^~.%(ext)s', 'http_headers': {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.63 Safari/537.36', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'Accept-Language': 'en-us,en;q=0.5', 'Sec-Fetch-Mode': 'navigate'}, 'playlistend': 300}
  'retries' = {int} 5
  'format' = {str} 'best'
  'continuedl' = {bool} True
  'ignoreerrors' = {bool} True
  'merge-output-format' = {str} 'mp4'
  'downloader' = {str} 'aria2c'
  'downloader-args' = {str} "aria2c:'-c -j 3 -x 3 -s 3 -k 1M'"
  'writeinfojson' = {bool} True
  'progress_hooks' = {list: 1} [<bound callback method>]
  'download_archive' = {str} '/home/owner/Code/scripts/ytDL/youtube-dl.history'
  'restrictfilenames' = {bool} True
  'compat_opts' = {set: 0} set()
  'forceprint' = {dict: 0} {}
  'print_to_file' = {dict: 0} {}
  'outtmpl' = {str} '/home/owner/Code/scripts/ytDL/PSMG/%(id)s~^~%(duration)s~^~.%(ext)s'
  'http_headers' = {dict: 4} {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.63 Safari/537.36', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'Accept-Language': 'en-us,en;q=0.5', 'Sec-Fetch-Mode': 'navigate'}
  'playlistend' = {int} 300
  __len__ = {int} 17
  _NUMERIC_FIELDS = {set: 28} {'age_limit', 'repost_count', 'asr', 'tbr', 'release_timestamp', 'abr', 'fps', 'timestamp', 'width', 'season_number', 'comment_count', 'end_time', 'dislike_count', 'filesize_approx', 'audio_channels', 'disc_number', 'duration', 'like_count', 'filesize', 't
  _allow_colors = {Namespace} Namespace(out=False, error=False, screen=False)
  _download_retcode = {int} 0
  _first_webpage_request = {bool} True
  _format_fields = {set: 49} {'flash_version', 'container', 'rtmp_conn', 'http_headers', 'language_preference', 'asr', 'source_preference', 'tc_url', 'fps', 'url', 'aspect_ratio', 'downloader_options', 'quality', 'filesize_approx', 'fragment_base_url', 'stretched_ratio', 'fragments', 
  _format_selection_exts = {dict: 3} {'audio': {'alac', 'm4a', 'aiff', 'mp3', 'mka', 'ogg', 'wav', 'flac', 'opus'}, 'video': {'mkv', 'mov', 'mp4', 'avi', '3gp', 'flv', 'webm'}, 'storyboards': {'mhtml'}}
  _ies = {dict: 1760} {'Youtube': <class 'yt_dlp.extractor.lazy_extractors.YoutubeIE'>, 'YoutubeClip': <class 'yt_dlp.extractor.lazy_extractors.YoutubeClipIE'>, 'YoutubeFavourites': <class 'yt_dlp.extractor.lazy_extractors.YoutubeFavouritesIE'>, 'YoutubeNotifications': <class '
  _ies_instances = {dict: 0} {}
  _num_downloads = {int} 0
  _num_videos = {int} 0
  _opener = {OpenerDirector} <urllib.request.OpenerDirector object at 0x7fb74c504880>
  _out_files = {Namespace} Namespace(out=<_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>, error=<_io.TextIOWrapper name='<stderr>' mode='w' encoding='utf-8'>, screen=<_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>, console=None)
  _playlist_level = {int} 0
  _playlist_urls = {set: 0} set()
  _post_hooks = {list: 0} []
  _postprocessor_hooks = {list: 0} []
  _pps = {dict: 8} {'pre_process': [], 'after_filter': [], 'video': [], 'before_dl': [], 'post_process': [], 'after_move': [], 'after_video': [], 'playlist': []}
  _printed_messages = {set: 0} set()
  _progress_hooks = {list: 1} [<bound callback method>]
  _socket_timeout = {int} 20
url_list = {list: 2} ['https://www.youtube.com/watch?v=dzFKG6rkWpU', 'https://www.youtube.com/watch?v=0g1Q4fBDp2U']
```

**Comment by Grub4K** [comment]
Mutating `YoutubeDL.params` after creating the object is not really supported. The output template needs to be prepared (`YoutubeDL._prepare_outtmpl`) to be used. This is called inside of `__init__`, so create a new `YoutubeDL` object with the params instead (or call the private method yourself and expect breakage). There also exists the now deprecated `YoutubeDL.parse_outtmpl`, which will give a deprecation warning.

The outtmpl now uses a dictionary as its value, to support different templates for playlists, episodes, ..., see `YoutubeDL.py`:
```
    outtmpl:           Dictionary of templates for output names. Allowed keys
                       are 'default' and the keys of OUTTMPL_TYPES (in utils.py).
                       For compatibility with youtube-dl, a single string can also be used
```

Additionally, *DO NOT* change the default template, but provide the regular verbose output, even when running as a package. You can do so by providing `verbose=True` as a param in the options dict on `YoutubeDL` creation and copying the text it writes out.

**Comment by ThomasFreedman** [comment]
> Mutating `YoutubeDL.params` after creating the object is not really supported. 

That's a bummer, and will require significant rework, if it's even possible. Will require some study to determine.

My app requires a dynamic path which the callback (progress_hook) relies on to process the downloads.

I recognize the utility of the change to add different templates for different purposes, but the way it was implemented broke compatibility with how youtube-dl handled output templates. That could have been avoided by using a new parameter rather than muck with the existing one, breaking old code.

**Comment by Grub4K** [comment]
> That's a bummer, and will require significant rework, if it's even possible. Will require some study to determine.

How does creating a new `YoutubeDL` object with the updated params not suit your needs? Mutating `params` was not fully supported on original `youtube-dl` as well, and so this working in the past is more of a coincidence? What do you require the dynamic path for and what do you want to do in `progress_hook`? Knowing those we might be able to provide you with better information on how to code this.

As I have mentioned, a workaround would be to set `outtmpl` to a string and call `_prepare_outtmpl()` afterwards.

**Comment by ThomasFreedman** [comment]
Sorry for my tone, I do apologize. As per your suggestion, I will avoid calling the private _prepare method.
The only thing I need to be sure of is I get a full path to where yt-dlp is downloading the files. I parse that path and make decisions based on it.

It will require some rework, but I believe creating a new object for each iteration will work. That's what I'll pursue any way.

**Comment by Grub4K** [comment]
> Sorry for my tone, I do apologize

No need to, I did not feel offended at all.

From what I gather there might be merit in using a [Postprocessor](https://github.com/yt-dlp/yt-dlp#add-a-custom-postprocessor). Depending on what you need, you can add one to the suported stages (`utils.POSTPROCESS_WHEN`), each at a different point in the download process, which may mutate the `info_dict`.

Unfortunately I cannot really help more without knowing what exactly you need to do with the files. If you just want the resulting file, `after_move` could be what you want. Otherwise you need to experiment.

**Comment by pukkandan** [comment]
> The outtmpl now uses a dictionary as its value, to support different templates for playlists, episodes, ..., see `YoutubeDL.py`:

Strings are also accepted for backward compatibility with youtube-dl. That is not the issue. Only mutating is the issue

As Grub4k mentoned, a quick and dirty fix would be to call `_parse_outtmpl` right after setting outtmpl. But remember that it is a private method and not guarenteed to keep working in future


> I get a full path to where yt-dlp is downloading the files. I parse that path and make decisions based on it.

You get it even with multiple YoutubeDL instances. Why can't you do:
```py
...  <-- code to create specific options for this download operation & these URLs, such as:
dlOpts['outtmpl'] = "/home/owner/Code/scripts/ytDL/PSMG/%(id)s~^~%(duration)s~^~.%(ext)s"
with yt_dlp.YoutubeDL(dlOpts) as ydl:
   ydl.download(newUrls) 
```

**Comment by ThomasFreedman** [comment]
The concern was to avoid setting all of the options each iteration rather than only those that needed to change. Foregoing that minor optimization and invoking the download after processing all options with:

`yt_dlp.YoutubeDL(dlOpts).download(newUrls)`

resolved the issue.
