### ISSUE TITLE
Chilloutzone: Unable to extract video data

### ISSUE THREAD

**Issue by Feathered-Serpent** [yt-dlp/yt-dlp#6029]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2023.01.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Germany

### Provide a description that is worded well enough to be understood

When trying to download a video from chilloutzone.net - e.g. https://www.chilloutzone.net/video/ordentlich-abgeschuettelt.html -  the correct extractor is chosen, but then throws the error "Unable to extract video data" is thrown.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.chilloutzone.net/video/ordentlich-abgeschuettelt.html']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2023.01.06 [6becd25] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19044-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 2022-10-13-git-9e8a327e68-full_build-www.gyan.dev (setts), ffprobe 2022-10-13-git-9e8a327e68-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.16.0, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1760 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2023.01.06, Current version: 2023.01.06
yt-dlp is up to date (2023.01.06)
[Chilloutzone] Extracting URL: https://www.chilloutzone.net/video/ordentlich-abgeschuettelt.html
[Chilloutzone] ordentlich-abgeschuettelt: Downloading webpage
ERROR: [Chilloutzone] ordentlich-abgeschuettelt: Unable to extract video data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 680, in extract
  File "yt_dlp\extractor\chilloutzone.py", line 56, in _real_extract
  File "yt_dlp\extractor\common.py", line 1264, in _html_search_regex
  File "yt_dlp\extractor\common.py", line 1228, in _search_regex
```

**Comment by bashonly** [comment]
The rest of the code could probably use a good modernizing, but this regex fix will at least get the extractor working again:
```diff
diff --git a/yt_dlp/extractor/chilloutzone.py b/yt_dlp/extractor/chilloutzone.py
index 1a2f77c4e..9f3c7db78 100644
--- a/yt_dlp/extractor/chilloutzone.py
+++ b/yt_dlp/extractor/chilloutzone.py
@@ -54,7 +54,7 @@ def _real_extract(self, url):
         webpage = self._download_webpage(url, video_id)
 
         base64_video_info = self._html_search_regex(
-            r'var cozVidData = "(.+?)";', webpage, 'video data')
+            r'var cozVidData\s*=\s*"([^"]+)"', webpage, 'video data')
         decoded_video_info = compat_b64decode(base64_video_info).decode('utf-8')
         video_info_dict = json.loads(decoded_video_info)
```
