### ISSUE TITLE
Information for age-gate bypass

### ISSUE THREAD

**Issue by thatDudo** [yt-dlp/yt-dlp#604]
I have found a website that successfully generates download links for age-gated content on youtube.

https://9xbuddy.com/process?url=http://www.youtube.com/watch?v=SV04P6YBuEY#download-image-play

**Comment by llacb47** [comment]
I hope you're trolling. That website uses its own closed server (not open source) and we cannot glean anything useful from it

**Comment by benggc** [comment]
Quoting release log:
"Youtube age-gate bypass is broken for non-embeddable videos unless logged-in cookies are given. You can provide cookies using either the --cookies or --cookies-from-browser options. There is currently no known way to circumvent the age-gate without authentication details. If you know any way to (or know any app that can) bypass the age-gate (without auth), let us know."

The website uses probably ytdl or yt-dlp for their backend with supplying their own cookies file. So this won't give us anything.

**Comment by pukkandan** [comment]
We have already figured it out and the age-gate bypass will be available in next release
