### ISSUE TITLE
Filter YouTube channel or playlist videos by date

### ISSUE THREAD

**Issue by ahm750** [yt-dlp/yt-dlp#6049]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a site-specific feature
- [X] I've verified that I'm running yt-dlp version **2023.01.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Example URLs

N/A

### Provide a description that is worded well enough to be understood

Hi, is there a way to filter YouTube channel or playlist videos by date? For example, I want to use the "-J" argument to get a list of all the videos for a specific channel that were uploaded after January 10, 2023.

I'm not sure if this feature is present and I couldn't find anything about it in the docs or the bug tracker.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
N/A
```

**Comment by pukkandan** [comment]
See `--match-filter` or the `--date` options

**Comment by ahm750** [comment]
> See `--match-filter` or the `--date` options

Nice! Do these work with the "-J" option?

**Comment by pukkandan** [comment]
Yes
