### ISSUE TITLE
[HELP] yt-dlp how to use --postprocessor-args?

### ISSUE THREAD

**Issue by benggc** [yt-dlp/yt-dlp#605]
Hello maintainers, on the beginning I would like to thank you for creating this amazing fork. Fixes most ytdl problems!
I have the following issue, when using this command on ytdl:
--postprocessor-args "-metadata year= -metadata date= -metadata description= -metadata comment= -metadata purl=  "
it works as expected, but I can't get it to work on yt-dlp. Anyone could supply some example how to get it to work? I can't understand the yt-dlp syntax.

And another question would be if it's possible to embed the track release year into the metadata?
I guess using --postprocessor-args with %(release_year)s could work, but i can't figure the syntax...

Thanks upfront to any replies!

**Comment by pukkandan** [comment]
> --postprocessor-args "-metadata year= -metadata date= -metadata description= -metadata comment= -metadata purl= "
it works as expected, but I can't get it to work on yt-dlp. Anyone could supply some example how to get it to work?

Show your verbose log

> And another question would be if it's possible to embed the track release year into the metadata?
I guess using --postprocessor-args with %(release_year)s could work, but i can't figure the syntax...

`--ppa` doesnt allow output templates. Look into `--parse-metadata`
https://github.com/yt-dlp/yt-dlp#modifying-metadata

**Comment by benggc** [comment]
> > --postprocessor-args "-metadata year= -metadata date= -metadata description= -metadata comment= -metadata purl= "
> > it works as expected, but I can't get it to work on yt-dlp. Anyone could supply some example how to get it to work?
> 
> Show your verbose log
> 
> > And another question would be if it's possible to embed the track release year into the metadata?
> > I guess using --postprocessor-args with %(release_year)s could work, but i can't figure the syntax...
> 
> `--ppa` doesnt allow output templates. Look into `--parse-metadata`
> https://github.com/yt-dlp/yt-dlp#modifying-metadata

Uhmmm.... Weirdly I reran the script and the --ppa issue dissapeared😵, mea culpa probably a typo from my side.

Adressing the second question, thanks for the hint.
I tried the following:
`--parse-metadata "%(playlist_index)s:%(track_number)s"
--parse-metadata "%(release_year)s:%(year)s"`
While running with the --verbose flag gives following output:
`[debug] Searching for r"(?P<track_number>.+)" in %(playlist_index)s
[MetadataFromField] parsed track_number from "%(playlist_index)s": 01
[debug] Searching for r"(?P<year>.+)" in %(release_year)s
[MetadataFromField] parsed year from "%(release_year)s": 1999`
But it doesn't add the release year to the final file. The output file is a untouched m4a file ( -f bestaudio[ext=m4a] ).

I still don't know what's wrong. Thanks for the input very appreciated.

Btw. how did you manage to bypass the youtube throttling?

**Comment by pukkandan** [comment]
yt-dlp doesnt normally add any `year` to the metadata, so it doesnt understand that you want to add the extracted `year` to the file. Prefix the fieldname with `meta_` to let yt-dlp know your intent. So `--parse-metadata "%(release_year)s:%(meta_year)s"`

I've also just added more information to the docs: https://github.com/yt-dlp/yt-dlp/commit/581fcb1d1e71cdfb7be39ad8602bf33b17674b6f

> Btw. how did you manage to bypass the youtube throttling?

We use the android client instead of web

**Comment by benggc** [comment]
> yt-dlp doesnt normally add any `year` to the metadata, so it doesnt understand that you want to add the extracted `year` to the file. Prefix the fieldname with `meta_` to let yt-dlp know your intent. So `--parse-metadata "%(release_year)s:%(meta_year)s"`
> 
> I've also just added more information to the docs: [c31be5b](https://github.com/yt-dlp/yt-dlp/commit/c31be5b009f0565f8fcea6037e9f51e4245b6c7d)
> 
> > Btw. how did you manage to bypass the youtube throttling?
> 
> We use the android client instead of web

Beautiful, worked flawlessly just changed (meta_year) to (meta_date)!

Nice workaround, couldn't fix this with the main version, tried various parameters.

Thank you again for the feedback.

P.S

Any plans to add option to parse main album artist and album's release year? ( not track's )? ( pic attached)
![image](https://user-images.githubusercontent.com/74107254/127922807-f7aaf0cf-b17d-4afb-afa8-02ffbe19054d.png)

**Comment by pukkandan** [comment]
Doesn't it already? If not, open a site-feature-request with relevent details
