### ISSUE TITLE
AppleTV 2023.01.02 

### ISSUE THREAD

**Issue by tekwarfare** [yt-dlp/yt-dlp#6055]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2023.01.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

UK

### Provide a description that is worded well enough to be understood

2022.11.11 is the last version able to download trailers from tv.apple.com
2023.01.02 and later can no longer download trailers from tv.apple.com as the site is flagged as DRM protected:
```
ERROR: [DRM] None: The requested site is known to use DRM protection. It will NOT be supported.
Please DO NOT open an issue, unless you have evidence that the video is not DRM protected
```
The trailers have never been (and are still not) DRM protected. 

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://tv.apple.com/gb/movie/transformers/umc.cmc.3fcj93vxd6o4wdku85sawi7in']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2023.01.06 [6becd25] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19044-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 4.4-full_build-www.gyan.dev (setts), ffprobe 4.4-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.16.0, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1760 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2023.01.06, Current version: 2023.01.06
yt-dlp is up to date (2023.01.06)
[DRM] Extracting URL: https://tv.apple.com/gb/movie/transformers/umc.cmc.3fcj93vxd6o4wdku85sawi7in
ERROR: [DRM] None: The requested site is known to use DRM protection. It will NOT be supported.
       Please DO NOT open an issue, unless you have evidence that the video is not DRM protected
  File "yt_dlp\extractor\common.py", line 680, in extract
  File "yt_dlp\extractor\unsupported.py", line 117, in _real_extract
```

**Comment by Lesmiscore** [comment]
As AppleTV was never supported website aside from `DRM`, and you're not willing to bypass DRM, so here's a possible workaround: you could try `--force-generic`

**Comment by coletdjnz** [comment]
`--ies all,-drm` or `--force-generic`

I recall @pukkandan adding support for KnownDRMIE redirecting to generic to this case, but not sure what happened to that.

We will not add built-in support for `tv.apple.com` due to DRM in general

**Comment by pukkandan** [comment]
Since OP never responded, I'm closing the under assumption https://github.com/yt-dlp/yt-dlp/issues/6055#issuecomment-1396987631 is sufficient. If not, let me know and this can be treated as site request for the trailers.

**Comment by pukkandan** [comment]
> I recall @pukkandan adding support for KnownDRMIE redirecting to generic to this case, but not sure what happened to that.

We had discussed (on discord) and decided it's not beneficial enough for now. If more similar issues arise, we can revisit the idea.
