### ISSUE TITLE
Video on videos.assemblee-nationale.fr cannot be downloaded

### ISSUE THREAD

**Issue by pitrou** [yt-dlp/yt-dlp#6058]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2023.01.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

France

### Provide a description that is worded well enough to be understood

The video from https://videos.assemblee-nationale.fr/video.12757531_63c949c31e170.souverainete-et-independance-energetique-de-la-france--m-philippe-de-ladoucette-ancien-pdt-de-la--19-janvier-2023 cannot be extracted.

Note that other similar pages on the same website do work, such as https://videos.assemblee-nationale.fr/video.12604236_6390b57141112.souverainete-et-independance-energetique-de-la-france--audition-de-representants-du-ministere-de-la-7-decembre-2022

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://videos.assemblee-nationale.fr/video.12757531_63c949c31e170.souverainete-et-independance-energetique-de-la-france--m-philippe-de-ladoucette-ancien-pdt-de-la--19-janvier-2023']
[debug] User config "/home/antoine/.config/yt-dlp/config": ['--no-playlist', '-S', 'height:1200', '--sub-langs', 'fr,en', '--embed-subs', '--write-subs']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2023.01.06 [6becd25] (pip)
[debug] Python 3.10.5 (CPython x86_64 64bit) - Linux-5.15.0-58-generic-x86_64-with-glibc2.35 (OpenSSL 3.0.5 5 Jul 2022, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1760 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2023.01.06, Current version: 2023.01.06
yt-dlp is up to date (2023.01.06)
[generic] Extracting URL: https://videos.assemblee-nationale.fr/video.12757531_63c949c31e170.souverainete-et-independance-energetique-de-la-france--m-philippe-de-ladoucette-ancien-pdt-de-la--19-janvier-2023
[generic] video.12757531_63c949c31e170: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] video.12757531_63c949c31e170: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://videos.assemblee-nationale.fr/video.12757531_63c949c31e170.souverainete-et-independance-energetique-de-la-france--m-philippe-de-ladoucette-ancien-pdt-de-la--19-janvier-2023
Traceback (most recent call last):
  File "/home/antoine/mambaforge/envs/youtube-dl/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1502, in wrapper
    return func(self, *args, **kwargs)
  File "/home/antoine/mambaforge/envs/youtube-dl/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1578, in __extract_info
    ie_result = ie.extract(url)
  File "/home/antoine/mambaforge/envs/youtube-dl/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 680, in extract
    ie_result = self._real_extract(url)
  File "/home/antoine/mambaforge/envs/youtube-dl/lib/python3.10/site-packages/yt_dlp/extractor/generic.py", line 2523, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://videos.assemblee-nationale.fr/video.12757531_63c949c31e170.souverainete-et-independance-energetique-de-la-france--m-philippe-de-ladoucette-ancien-pdt-de-la--19-janvier-2023
```

**Comment by dirkf** [comment]
This doesn't seem to be a supported site.

In the problem page, the video link, together with title, thumbnail, description, are available from `<meta property="og:...` elements, but the generic extraction doesn't find them.

Perhaps there should be a generic extraction using OpenGraph properties when the `og:video` has an explicit type (possibly also if `og:video:type` is a known media MIME type), similar to the ld+json extraction? It shouldn't be done in general since `og:video` might not specify an actual media link, but [just a canonical page containing the same video](https://stackoverflow.com/a/9598126).

**Comment by bashonly** [comment]
I can't reproduce the issue, the generic extractor works for me:
```
$ yt-dlp -vF --ignore-config "https://videos.assemblee-nationale.fr/video.12757531_63c949c31e170.souverainete-et-independance-energetique-de-la-france--m-philippe-de-ladoucette-ancien-pdt-de-la--19-janvier-2023"
[debug] Command-line config: ['-vF', '--ignore-config', 'https://videos.assemblee-nationale.fr/video.12757531_63c949c31e170.souverainete-et-independance-energetique-de-la-france--m-philippe-de-ladoucette-ancien-pdt-de-la--19-janvier-2023']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2023.01.06 [6becd25]
[debug] Python 3.10.9 (CPython x86_64 64bit) - Linux-6.1.6-arch1-3-x86_64-with-glibc2.36 (OpenSSL 1.1.1q  5 Jul 2022, glibc 2.36)
[debug] exe versions: ffmpeg 5.1.2 (setts), ffprobe 5.1.2
[debug] Optional libraries: Cryptodome-3.12.0, brotlicffi-1.0.9.2, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1760 extractors
[generic] Extracting URL: https://videos.assemblee-nationale.fr/video.12757531_63c949c31e170.souverainete-et-independance-energetique-de-la-france--m-philippe-de-ladoucette-ancien-pdt-de-la--19-janvier-2023
[generic] video.12757531_63c949c31e170: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] video.12757531_63c949c31e170: Extracting information
[debug] Looking for embeds
[debug] Identified a Open Graph video info
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[info] Available formats for 7040_20230119144644_1:
ID EXT RESOLUTION │ PROTO │ VCODEC  ACODEC
───────────────────────────────────────────
0  mp4 unknown    │ http  │ unknown unknown
```

**Comment by pitrou** [comment]
@pukkandan Interesting, I tried again and it works now. Perhaps the Web page was updated for some reason...
