### ISSUE TITLE
Playlist verify

### ISSUE THREAD

**Issue by Legnatbird** [yt-dlp/yt-dlp#6061]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.01.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Exist a option for verify the unsucessfull downloads?. I said this because i downloaded a playlist of 2317 songs and the download ends with 2193 songs :(.
And with this download that songs.
Thanks ^^

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
Just read the console output? Your requirement is not clear

**Comment by Legnatbird** [comment]
My playlist has 2317 songs, but ytl-dp just downloaded 2193, so I'm asking about if exist a way to know what songs not download

**Comment by Legnatbird** [comment]
On the console i dont look something for know what songs not downloaded

**Comment by Legnatbird** [comment]
![image](https://user-images.githubusercontent.com/50637445/213599653-26316557-2caa-4eaf-bbf9-a80d44253f6c.png)
Only that message in some songs and after that download the thumbnail with other number

**Comment by pukkandan** [comment]
> ### Provide verbose output that clearly demonstrates the problem
> * [ ]  Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
> * [ ]  Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

Do this

**Comment by Legnatbird** [comment]
And thats make me downloaded all the songs?
