### ISSUE TITLE
Output Template

### ISSUE THREAD

**Issue by xmha97** [yt-dlp/yt-dlp#6063]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2023.01.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

# Description

In the `.cmd`/`.bat` script files on Windows, the --print option does not work and we have to use two percent signs (%%) instead of one percent signs (%) in the output template.

For example, the following command does not work:
```
yt-dlp --print "%(id)s;%(title)s" "https://youtube.com/XXXX">VideosList.csv
```

But this command works:
```
yt-dlp --print "%%(id)s;%%(title)s" "https://youtube.com/XXXX">VideosList.csv
```

Please mention this point in this article because my friend thought that the Windows build of yt-dlp has a problem:
https://github.com/yt-dlp/yt-dlp/blob/master/README.md
Thanks.

# What is the cause of this problem?

Actually, there is no problem. Command Prompt variables comprise a % character followed by a name, for example:
```
FOR /f %f in ('dir /b .') DO ECHO %f
```

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
N/A
```

**Comment by pukkandan** [comment]
That is how batch files work! https://github.com/yt-dlp/yt-dlp/wiki/FAQ#output-template-and-windows-batch-files
