### ISSUE TITLE
[Youtube] Feed extractor pagination support

### ISSUE THREAD

**Issue by iBicha** [yt-dlp/yt-dlp#6064]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a site-specific feature
- [X] I've verified that I'm running yt-dlp version **2023.01.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Any

### Example URLs

https://www.youtube.com/feed/history

### Provide a description that is worded well enough to be understood

Give the command (which would print the video ids of my watch history into a file)
```
yt-dlp https://www.youtube.com/feed/history --cookies-from-browser chrome --flat-playlist --print '%(id)s' > history.txt
```

It takes a long time, and end up with a history.txt file with over 32k lines (long history).

### Solution 1
Make the video ids print as they are found, instead of fetching the full list before printing them

### Solution 2
Expose pagination args so that requests can be made in chunks

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.youtube.com/feed/history', '--cookies-from-browser', 'chrome', '--flat-playlist', '--print', '%(id)s']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2023.01.06 [6becd25] (pip)
[debug] Python 3.11.1 (CPython x86_64 64bit) - macOS-12.6.2-x86_64-i386-64bit (OpenSSL 1.1.1s  1 Nov 2022)
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.16.0, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[Cookies] Extracting cookies from chrome
[debug] Extracting cookies from: "/Users/brahim/Library/Application Support/Google/Chrome/Default/Cookies"
[debug] using find-generic-password to obtain password from OSX keychain
[Cookies] Extracted 3246 cookies from chrome
[debug] cookie version breakdown: {'v10': 3232, 'other': 0, 'unencrypted': 14}
[debug] Proxy map: {}
[debug] Loaded 1760 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2023.01.06, Current version: 2023.01.06
yt-dlp is up to date (2023.01.06)
[youtube:tab] Extracting URL: https://www.youtube.com/feed/history
[youtube:tab] history: Downloading webpage
[download] Downloading playlist: history
[debug] [youtube:tab] Extracted SAPISID cookie
[youtube:tab] history page 1: Downloading API JSON
[youtube:tab] history page 2: Downloading API JSON
[youtube:tab] history page 3: Downloading API JSON
[youtube:tab] history page 4: Downloading API JSON
[youtube:tab] history page 5: Downloading API JSON
[youtube:tab] history page 6: Downloading API JSON
[youtube:tab] history page 7: Downloading API JSON
[youtube:tab] history page 8: Downloading API JSON
[youtube:tab] history page 9: Downloading API JSON
[youtube:tab] history page 10: Downloading API JSON
[youtube:tab] history page 11: Downloading API JSON
[youtube:tab] history page 12: Downloading API JSON
[youtube:tab] history page 13: Downloading API JSON
[youtube:tab] history page 14: Downloading API JSON
[youtube:tab] history page 15: Downloading API JSON
[youtube:tab] history page 16: Downloading API JSON
^C
ERROR: Interrupted by user (well, it's going to take a while otherwise)
```

**Comment by pukkandan** [comment]
`--lazy-playlist`

**Comment by iBicha** [comment]
> > Make the video ids print as they are found, instead of fetching the full list before printing them
> 
> `--lazy-playlist`
> 
> > Expose pagination args so that requests can be made in chunks
> 
> `--playlist-items 1-N` can be used to get the first N items only. But due to the way Youtube works, it's impossible to get a chunk from the middle without downloading all previous pages

Amazing! I was searching for "pagination" and similar keywords in the docs, but couldn't find these. Thank you
