### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by apt42541** [yt-dlp/yt-dlp#607]
## Checklist

- [x] I'm asking a question
- [ ] I've looked through the README and FAQ for similar questions
- [ ] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE

i want to download dash fragment (mpd)  in allow-unplayable formats but there a lot of audio can i download one video and multi langauge or can i select audio by language auto? like lange=englsih?

![image](https://user-images.githubusercontent.com/12625408/127796288-5c1bdbf1-7c6f-400c-8b1c-d9480c0c2f2e.png)

**Comment by pukkandan** [comment]
`-f bv,ba[language=en],ba[language=hi]`

Read https://github.com/yt-dlp/yt-dlp#filtering-formats

**Comment by apt42541** [comment]
> `-f bv,ba[language=en],ba[language=hi]`
> 
> Read https://github.com/yt-dlp/yt-dlp#filtering-formats

can i download all audio ?

**Comment by pukkandan** [comment]
`-f bv,all[vcodec=none]`

> Read https://github.com/yt-dlp/yt-dlp#filtering-formats

### Read the documentation before asking questions
