### ISSUE TITLE
Return progress_hooks to the front end using fastapi or other libs

### ISSUE THREAD

**Issue by KaranTrivedi** [yt-dlp/yt-dlp#6070]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.01.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

If this is a feature req., please delete. I am wondering if it possible to return progress hook object in the download function to something like an angular front end over rest api. I am able to use progress hook to log something locally, but cannot have the function return till download is over.

Thanks.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
> but cannot have the function return till download is over.

Pls elaborate, preferably with minimal example code



> if it possible to return progress hook object in the download function to something like an angular front end over rest api.

That is related to yt-dlp how? I can help you if you have any issues with using progress_hooks itself. For more general programming questions, ask in appropriate forums

**Comment by KaranTrivedi** [comment]
```
def yt_dlp_hook(download):
    """
    Youtube download Hook

    Args:
        download (_type_): _description_
    """

    global TMP_KEYS

    if download.keys() != TMP_KEYS:
        logger.info(f'Status: {download["status"]}')
        logger.info(f'Dict Keys: {download.keys()}')
        TMP_KEYS = download.keys()
        # logger.info(download)
        # logger.info(json.dumps(download, indent=2))

@directory_router.get("/youtube-dl/{relative_path:path}", tags=["directory"])
def youtube_dl(relative_path, url, name=""):
    """
    Download videos from URL

    Args:
        relative_path ([type]): Path to directory
        url ([type]): [description]
        name (str, optional): [description]. Defaults to "".
    
    Returns:
        [type]: [description]
    """

    # youtube-dl --extract-audio --audio-format mp3 --output "%(uploader)s%(title)s.%(ext)s" http://www.youtube.com/watch?v=rtOvBOTyX00

    relative_path, _ = set_path(relative_path)

    logger.info(f"{DATA_PATH}{relative_path}")

    if name:
        name = f"{DATA_PATH}{relative_path}/{name}.%(ext)s"
    else:
        name = f"{DATA_PATH}{relative_path}/%(title)s.%(ext)s"

    ydl_opts = {
        "outtmpl": name,
        # "quiet": True
        "logger": logger,
        "progress_hooks": [yt_dlp_hook],
        # "force-overwrites": True
    }

    with yt_dlp.YoutubeDL(ydl_opts) as ydl:
        try:
            return ydl.download([url])
        except Exception as exp:
            logger.info(exp)
            return str(exp)

```

Code is essentially this route. I can use a front end to pass a URL and name to backend (python api) to download file to server. 
I would like to return or stream webhooks data as a RETURN value. I dont think yt dl allows for this. The code essentially 'blocks' on 

```
            return ydl.download([url])

```
line but the hooks function is executing and doing something in real time (outputting logs to file.

**Comment by pukkandan** [comment]
yt-dlp only provides a synchronous API. If you want `.download` to be non-blocking, start it in a new thread
