### ISSUE TITLE
Can a LATEST_VERSION file be added?

### ISSUE THREAD

**Issue by djlauria** [yt-dlp/yt-dlp#6077]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.01.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

The original youtube-dl included a top level text file called LATEST_VERSION which contained the code's latest version number and nothing else. Would the devs be willing to reinstate this? It was very useful to curl this file as a comparison against --version when running from a batch file to check if an update needed to be installed.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
# using youtube-dl as example
curl -L http://rg3.github.io/youtube-dl/update/LATEST_VERSION
2021.12.17                   

./yt-dlp_macos --version
2023.01.06

# versions don't match, run this
./yt-dlp_macos -U
```

**Comment by pukkandan** [comment]
* The updater already checks for versions before downloading the exe
* You can fetch the it from Github API 
* If neither of these is an option, there is the [version.py](https://github.com/yt-dlp/yt-dlp/blob/master/yt_dlp/version.py) file
