### ISSUE TITLE
Incorrect youtube url parsing when "v", "list", "index" arguments provided simulatenously (e.g. watch?v=VIDEO_ID&list=LIST_ID&index=INDEX_N)

### ISSUE THREAD

**Issue by vtuu** [yt-dlp/yt-dlp#6087]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2023.01.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Who cares

### Provide a description that is worded well enough to be understood

When I copy video url from youtube playlist i get link like ```watch?v=VIDEO_ID&list=LIST_ID&index=INDEX_N```, where 3 arguments provided: ```v```,```list```, ```index```.

Then i paste it to yt-dlp:
```yt-dlp https://www.youtube.com/watch?v=-l67Umih7x8&list=PLSIpIU2VZoWU_G8uq-pg81XT6ZpOiSTT-&index=1```

### Expected:
yt-dlp will work as usual, i can cancel it by pressing Ctrl+C

### Given:
yt-dlp creates two background tasks/processes (?), intercepts input, I can't cancel it by Ctrl-C
```bash
too@too-Inspiron-3542:~$ yt-dlp https://www.youtube.com/watch?v=-l67Umih7x8&list=PLSIpIU2VZoWU_G8uq-pg81XT6ZpOiSTT-&index=1
[1] 2507825
[2] 2507826
too@too-Inspiron-3542:~$ [youtube] Extracting URL: https://www.youtube.com/watch?v=-l67Umih7x8
[youtube] -l67Umih7x8: Downloading webpage
[youtube] -l67Umih7x8: Downloading android player API JSON
[SponsorBlock] Fetching SponsorBlock segments
[SponsorBlock] No matching segments were found in the SponsorBlock database
[info] -l67Umih7x8: Downloading 1 format(s): 137+251
[download] Resuming download at byte 154662554
[download] Destination: /var/tmp/yt-dlp/За что хейтить Реал и Барсу？ ⧸ Ищем новый ПСЖ ｜ Ла Ла Лига #56 [-l67Umih7x8].f137.mp4
[download]   9.2% of    1.67GiB at  151.88KiB/s ETA 02:54:00^C
[2]+  Done                    list=PLSIpIU2VZoWU_G8uq-pg81XT6ZpOiSTT-
[download]   9.2% of    1.67GiB at  188.38KiB/s ETA 02:20:16^C
[download]   9.2% of    1.67GiB at  257.28KiB/s ETA 01:42:42^C
[download]   9.3% of    1.67GiB at  619.45KiB/s ETA 42:38^C
too@too-Inspiron-3542:~$ ^C
[download]   9.3% of    1.67GiB at  895.41KiB/s ETA 29:29^C
[download]   9.3% of    1.67GiB at    1.41MiB/s ETA 18:15^C
...
```

### Steps to reproduce:
1. Go https://www.youtube.com/playlist?list=PLSIpIU2VZoWU_G8uq-pg81XT6ZpOiSTT-
4. Right click any video from playlist, copy link
5. Open terminal, run ```yt-dlp LINK```

Given output:

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
too@too-Inspiron-3542:~$ yt-dlp https://www.youtube.com/watch?v=-l67Umih7x8&list=PLSIpIU2VZoWU_G8uq-pg81XT6ZpOiSTT-&index=1
[1] 2507825
[2] 2507826
too@too-Inspiron-3542:~$ [youtube] Extracting URL: https://www.youtube.com/watch?v=-l67Umih7x8
[youtube] -l67Umih7x8: Downloading webpage
[youtube] -l67Umih7x8: Downloading android player API JSON
[SponsorBlock] Fetching SponsorBlock segments
[SponsorBlock] No matching segments were found in the SponsorBlock database
[info] -l67Umih7x8: Downloading 1 format(s): 137+251
[download] Resuming download at byte 154662554
[download] Destination: /var/tmp/yt-dlp/За что хейтить Реал и Барсу？ ⧸ Ищем новый ПСЖ ｜ Ла Ла Лига #56 [-l67Umih7x8].f137.mp4
[download]   9.2% of    1.67GiB at  151.88KiB/s ETA 02:54:00^C
[2]+  Done                    list=PLSIpIU2VZoWU_G8uq-pg81XT6ZpOiSTT-
[download]   9.2% of    1.67GiB at  188.38KiB/s ETA 02:20:16^C
[download]   9.2% of    1.67GiB at  257.28KiB/s ETA 01:42:42^C
[download]   9.3% of    1.67GiB at  619.45KiB/s ETA 42:38^C
too@too-Inspiron-3542:~$ ^C
[download]   9.3% of    1.67GiB at  895.41KiB/s ETA 29:29^C
[download]   9.3% of    1.67GiB at    1.41MiB/s ETA 18:15^C
[download]   9.5% of    1.67GiB at    2.18MiB/s ETA 11:46^C
too@too-Inspiron-3542:~$ ^C
too@too-Inspiron-3542:~$ ^C
[download]  12.7% of    1.67GiB at    2.70MiB/s ETA 09:11
too@too-Inspiron-3542:~$ [download] Got error: The read operation timed out. Retrying (1/10)...
[download] Destination: /var/tmp/yt-dlp/За что хейтить Реал и Барсу？ ⧸ Ищем новый ПСЖ ｜ Ла Ла Лига #56 [-l67Umih7x8].f137.mp4
[download]  37.2% of    1.67GiB at    9.56MiB/s ETA 01:51^C
[download]  37.3% of    1.67GiB at    8.10MiB/s ETA 02:12^C
[download]  37.3% of    1.67GiB at    8.67MiB/s ETA 02:03^C
[download]  37.5% of    1.67GiB at    9.22MiB/s ETA 01:55^C
[download]  49.2% of    1.67GiB at    9.68MiB/s ETA 01:29^C
```

**Comment by Grub4K** [comment]
[Quote the url](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
