### ISSUE TITLE
Make Cozytv faster. | Cozytv is faster with the '--hls-prefer-ffmpeg' perameter.

### ISSUE THREAD

**Issue by LalleSX** [yt-dlp/yt-dlp#6095]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a site-specific feature
- [X] I've verified that I'm running yt-dlp version **2023.01.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Denmark & USA.

### Example URLs

Normal front-end [https://cozy.tv/nick/replays/2023-01-26](https://cozy.tv/nick/replays/2023-01-26)

CDN: [https://cozycdn.foxtrotstream.xyz/replays/nick/2023-01-26/index.m3u8](https://cozycdn.foxtrotstream.xyz/replays/nick/2023-01-26/index.m3u8)

### Provide a description that is worded well enough to be understood

As stated in the title using `--hls-prefer-ffmpeg` makes the process go wayyy faster
It takes around **4 minutes** for a 1 hour and 47 minutes **with the parameter**
Without the parameter the ETA says it would take around **2 hours without** In the start but after around 5-7 minutes it's 15% done

Meta:
I have tried to fix it myself, but i simply doesn't know enough python to do so
I am willing to help with fixing the problem if needed.

Debug is without the --hls...

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://cozy.tv/nick/replays/2023-01-26']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2023.01.06 [6becd25]
[debug] Python 3.10.9 (CPython x86_64 64bit) - Linux-6.1.6-artix1-1-x86_64-with-glibc2.36 (OpenSSL 3.0.7 1 Nov 2022, glibc 2.36)
[debug] exe versions: ffmpeg 5.1.2 (setts), ffprobe 5.1.2, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.16.0, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1760 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2023.01.06, Current version: 2023.01.06
yt-dlp is up to date (2023.01.06)
```

**Comment by LalleSX** [comment]
Even tho there is a "fix" to it, it just seems like a temporary fix and not a solution.

This is also more for users who are noobs to this field

**Comment by dirkf** [comment]
This should have the desired effect, if the effect is worthwhile. It re-applies the yt-dl default which is (sensibly) changed in yt-dlp -- not that this extractor exists in yt-dl:
```diff
--- old/yt_dlp/extractor/cozytv.py
+++ new/yt_dlp/extractor/cozytv.py
@@ -24,7 +24,8 @@
         id = f'{uploader}-{date}'
         data_json = self._download_json(f'https://api.cozy.tv/cache/{uploader}/replay/{date}', id)
         formats, subtitles = self._extract_m3u8_formats_and_subtitles(
-            f'https://cozycdn.foxtrotstream.xyz/replays/{uploader}/{date}/index.m3u8', id, ext='mp4')
+            f'https://cozycdn.foxtrotstream.xyz/replays/{uploader}/{date}/index.m3u8', id, ext='mp4',
+            entry_protocol='m3u8')
         return {
             'id': id,
             'title': data_json.get('title'),
```

**Comment by pukkandan** [comment]
I have no intention of changing the default downloader unless the downloads are broken. You can use `-N`, `--downloader aria2c` or ffmpeg for better speeds

PS: The network rework will probably improve speed due to connection pooling
