### ISSUE TITLE
Convert after/while splitting chapters.

### ISSUE THREAD

**Issue by arcmags** [yt-dlp/yt-dlp#6098]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.01.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

When extracting audio, splitting chapters, and converting to a different format, the conversion happens before splitting chapters:

    yt-dlp -x --split-chapters --audio-format mp3 <URL>

This is problematic, as the splitting now occurs without re-encoding. When splitting without re-encoding some audio formats, a small gap/jump is often introduced at the split location. This can be heard when splitting audio that seamlessly transitions between tracks (example: https://www.youtube.com/watch?v=iXAbte4QXKs).

When splitting an *m4a* first, before converting to *mp3*, these gaps are far less noticeable, if existent at all:

    yt-dlp -x --split-chapters <URL>
    for m4a in *.m4a; do ffmpeg -i "$m4a" "${mp4%.*}.mp3"; done

Ideally, splitting and converting would happen in the same step.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
This is effectively same as https://github.com/yt-dlp/yt-dlp/issues/126. The request can be tracked there
