### ISSUE TITLE
Add support for zoom.iprima.cz

### ISSUE THREAD

**Issue by Tonda39** [yt-dlp/yt-dlp#6100]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2023.01.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Czech Republic / Czechia

### Example URLs

-Single video: https://zoom.iprima.cz/porady/valecni-kseftari-druha-svetova-z-druhe-ruky/blitz
-Playlist: https://zoom.iprima.cz/porady/valecni-kseftari-druha-svetova-z-druhe-ruky

### Provide a description that is worded well enough to be understood

I have no problems downloading from prima.iprima.cz website (for example: https://prima.iprima.cz/zoo-0/sestru-nezradim) however if I try to download from the zoom.iprima.cz using the same credentials I recieve an error (see below).

I am able to successfully log in to both of these sites (they use the same account) and watch the videos mentioned without any problems directly from the website. 

The credentials I've used:
Username: bejote2396@breazeim.com
Password: qwerty

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--username', 'PRIVATE', '--password', 'PRIVATE', 'https://zoom.iprima.cz/porady/valecni-kseftari-druha-svetova-z-druhe-ruky/blitz']
[debug] Encodings: locale cp1250, fs utf-8, pref cp1250, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2023.01.06 [6becd25] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.16.0, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1760 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2023.01.06, Current version: 2023.01.06
yt-dlp is up to date (2023.01.06)
[IPrima] Downloading login page
[IPrima] Logging in
[IPrima] Downloading token
[IPrima] Extracting URL: https://zoom.iprima.cz/porady/valecni-kseftari-druha-svetova-z-druhe-ruky/blitz
[IPrima] blitz: Downloading webpage
ERROR: [IPrima] blitz: Unable to extract real id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 680, in extract
  File "yt_dlp\extractor\iprima.py", line 122, in _real_extract
  File "yt_dlp\extractor\common.py", line 1228, in _search_regex
```

**Comment by bashonly** [comment]
The Zoom IPrima content uses the same API, but the necessary video ID is found an a different location in the page source. I think this might fix it:
```diff
diff --git a/yt_dlp/extractor/iprima.py b/yt_dlp/extractor/iprima.py
index 181820542..f134321fb 100644
--- a/yt_dlp/extractor/iprima.py
+++ b/yt_dlp/extractor/iprima.py
@@ -121,7 +121,8 @@ def _real_extract(self, url):
 
         video_id = self._search_regex((
             r'productId\s*=\s*([\'"])(?P<id>p\d+)\1',
-            r'pproduct_id\s*=\s*([\'"])(?P<id>p\d+)\1'),
+            r'pproduct_id\s*=\s*([\'"])(?P<id>p\d+)\1',
+            r'let videos\s*=\s*([\'"])(?P<id>p\d+)\1'),
             webpage, 'real id', group='id')
 
         metadata = self._download_json(
```
I'm geo-blocked, so with this patch I get this result:
```
[IPrima] Downloading login page
[IPrima] Logging in
[IPrima] Downloading token
[IPrima] Extracting URL: https://zoom.iprima.cz/porady/valecni-kseftari-druha-svetova-z-druhe-ruky/blitz
[IPrima] blitz: Downloading webpage
[IPrima] p1088279: Getting manifest URLs
ERROR: [IPrima] blitz: This video is not available from your location due to geo restriction
This video is available in Czech Republic.
You might want to use a VPN or a proxy server (with --proxy) to workaround.
```
is anyone in region able to test?

**Comment by stroodl** [comment]
Hello,
how do I change and run the iprima.py file?
Thank you,
ondra
