### ISSUE TITLE
What does a Website need to be automatically "compatible" with yt-dlp?

### ISSUE THREAD

**Issue by BergHeisen** [yt-dlp/yt-dlp#6101]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.01.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I made my own private video hosting website, and I want it to be completly compatible with yt-dlp generic info extractor. Content-* Headers are all set, but when extracting information/downloading with yt-dlp, it doesn't get the duration / videosize / mime-type 
right. I have tried Ktor and Flask that sends outputs the File. Both do not serve static files but get an id and they know the file path (Maybe that is the problem) . 

Do I need write my own private Information Extractor or is there a way to make it compatible?

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp -j http://127.0.0.1:4040/video/38e599f39279cab6bd41773c0dfca7ce -vU
[debug] Command-line config: ['-j', 'http://127.0.0.1:4040/video/38e599f39279cab6bd41773c0dfca7ce', '-vU']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2023.01.06 [6becd25] (pip)
[debug] Python 3.11.0rc2 (CPython x86_64 64bit) - Linux-5.10.16.3-microsoft-standard-WSL2-x86_64-with-glibc2.27 (OpenSSL 1.1.1  11 Sep 2018, glibc 2.27)
[debug] exe versions: ffmpeg 3.4.11, ffprobe 3.4.11
[debug] Optional libraries: Cryptodome-3.14.1, brotli-1.0.9, certifi-2021.10.08, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.2
[debug] Proxy map: {}
[debug] Loaded 1760 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2023.01.06, Current version: 2023.01.06
yt-dlp is up to date (2023.01.06)
[generic] Extracting URL: http://127.0.0.1:4040/video/38e599f39279cab6bd41773c0dfca7ce
[generic] 38e599f39279cab6bd41773c0dfca7ce: Downloading webpage
[debug] Identified a direct video link
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 38e599f39279cab6bd41773c0dfca7ce: Downloading 1 format(s): fmp4
{"id": "38e599f39279cab6bd41773c0dfca7ce", "title": "38e599f39279cab6bd41773c0dfca7ce", "timestamp": null, "direct": true, "formats": [{"format_id": "fmp4", "url": "http://127.0.0.1:4040/video/38e599f39279cab6bd41773c0dfca7ce", "vcodec": null, "protocol": "http", "ext": "unknown_video", "video_ext": "unknown_video", "audio_ext": "none", "format": "fmp4 - unknown", "resolution": null, "dynamic_range": "SDR", "aspect_ratio": null, "http_headers": {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36", "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8", "Accept-Language": "en-us,en;q=0.5", "Sec-Fetch-Mode": "navigate"}}], "subtitles": {}, "http_headers": {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36", "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8", "Accept-Language": "en-us,en;q=0.5", "Sec-Fetch-Mode": "navigate"}, "webpage_url": "http://127.0.0.1:4040/video/38e599f39279cab6bd41773c0dfca7ce", "original_url": "http://127.0.0.1:4040/video/38e599f39279cab6bd41773c0dfca7ce", "webpage_url_basename": "38e599f39279cab6bd41773c0dfca7ce", "webpage_url_domain": "127.0.0.1:4040", "extractor": "generic", "extractor_key": "Generic", "playlist": null, "playlist_index": null, "display_id": "38e599f39279cab6bd41773c0dfca7ce", "fulltitle": "38e599f39279cab6bd41773c0dfca7ce", "requested_subtitles": null, "_has_drm": null, "format_id": "fmp4", "url": "http://127.0.0.1:4040/video/38e599f39279cab6bd41773c0dfca7ce", "vcodec": null, "protocol": "http", "ext": "unknown_video", "video_ext": "unknown_video", "audio_ext": "none", "format": "fmp4 - unknown", "resolution": null, "dynamic_range": "SDR", "aspect_ratio": null, "epoch": 1674857172, "_filename": "38e599f39279cab6bd41773c0dfca7ce [38e599f39279cab6bd41773c0dfca7ce].unknown_video", "filename": "38e599f39279cab6bd41773c0dfca7ce [38e599f39279cab6bd41773c0dfca7ce].unknown_video", "urls": "http://127.0.0.1:4040/video/38e599f39279cab6bd41773c0dfca7ce", "_type": "video", "_version": {"version": "2023.01.06", "current_git_head": null, "release_git_head": "6becd25", "repository": "yt-dlp/yt-dlp"}}
```

**Comment by bashonly** [comment]
When the generic extractor detects a direct video link, the only response headers that it pays attention to are `last-modified`, the value of which is extracted as `timestamp`, and `content-type`, which it only uses to check for a dash/hls/f4m manifest and set the `format_id`. You can see some of the relevant code here:
https://github.com/yt-dlp/yt-dlp/blob/05997b6e98e638d97d409c65bb5eb86da68f3b64/yt_dlp/extractor/generic.py#L2397-L2431

The file extension is determined from the URL, so if that extension-less localhost URL doesn't redirect to one with an extension, then yt-dlp ends up using `unknown_video` as ext

If you want to provide yt-dlp with more metadata without writing your own custom extractor, one option would be to have your server return a JSON LD response that points to the actual file URL instead of returning the file itself. Something like this:

```html
<script type="application/ld+json">
{
    "@context": "https://schema.org",
    "@type": "VideoObject",
    "contentUrl": "http://127.0.0.1:4040/video/actual_file_url",
    "encodingFormat": "video/mp4",
    "name": "Custom title",
    "description": "Custom description",
    "duration": "PT1M33S",
    "uploadDate": "2023-01-29T05:57:54+02:00",
    "bitrate": "4128",
    "width": "1920",
    "height": "1080"
}
</script>
```

Note that the `<script type="application/ld+json">` and `</script>` html tags are required by yt-dlp, as is `"@type": "VideoObject"` in the JSON

**Comment by BergHeisen** [comment]
> When the generic extractor detects a direct video link, the only response headers that it pays attention to are `last-modified`, the value of which is extracted as `timestamp`, and `content-type`, which it only uses to check for a dash/hls/f4m manifest and set the `format_id`. You can see some of the relevant code here:
> 
> https://github.com/yt-dlp/yt-dlp/blob/05997b6e98e638d97d409c65bb5eb86da68f3b64/yt_dlp/extractor/generic.py#L2397-L2431
> 
> The file extension is determined from the URL, so if that extension-less localhost URL doesn't redirect to one with an extension, then yt-dlp ends up using `unknown_video` as ext
> 
> If you want to provide yt-dlp with more metadata without writing your own custom extractor, one option would be to have your server return a JSON LD response that points to the actual file URL instead of returning the file itself. Something like this:
> 
> ```
> <script type="application/ld+json">
> {
>     "@context": "https://schema.org",
>     "@type": "VideoObject",
>     "contentUrl": "http://127.0.0.1:4040/video/actual_file_url",
>     "encodingFormat": "video/mp4",
>     "name": "Custom title",
>     "description": "Custom description",
>     "duration": "PT1M33S",
>     "uploadDate": "2023-01-29T05:57:54+02:00",
>     "bitrate": "4128",
>     "width": "1920",
>     "height": "1080"
> }
> </script>
> ```
> 
> Note that the `<script type="application/ld+json">` and `</script>` html tags are required by yt-dlp, as is `"@type": "VideoObject"` in the JSON

Thanks alot, I wanted to implement this after making the Website for Discord, turns out that the open graph properties do the job as well.

**Comment by BergHeisen** [comment]
> When the generic extractor detects a direct video link, the only response headers that it pays attention to are `last-modified`, the value of which is extracted as `timestamp`, and `content-type`, which it only uses to check for a dash/hls/f4m manifest and set the `format_id`. You can see some of the relevant code here:
> 
> https://github.com/yt-dlp/yt-dlp/blob/05997b6e98e638d97d409c65bb5eb86da68f3b64/yt_dlp/extractor/generic.py#L2397-L2431
> 
> The file extension is determined from the URL, so if that extension-less localhost URL doesn't redirect to one with an extension, then yt-dlp ends up using `unknown_video` as ext
> 
> If you want to provide yt-dlp with more metadata without writing your own custom extractor, one option would be to have your server return a JSON LD response that points to the actual file URL instead of returning the file itself. Something like this:
> 
> ```
> <script type="application/ld+json">
> {
>     "@context": "https://schema.org",
>     "@type": "VideoObject",
>     "contentUrl": "http://127.0.0.1:4040/video/actual_file_url",
>     "encodingFormat": "video/mp4",
>     "name": "Custom title",
>     "description": "Custom description",
>     "duration": "PT1M33S",
>     "uploadDate": "2023-01-29T05:57:54+02:00",
>     "bitrate": "4128",
>     "width": "1920",
>     "height": "1080"
> }
> </script>
> ```
> 
> Note that the `<script type="application/ld+json">` and `</script>` html tags are required by yt-dlp, as is `"@type": "VideoObject"` in the JSON

I did end up doing the LD JSON method for maximum information, and it works, but yt-dlp priotizes the HTML5 Embed, so if I put the Video in a <video> tag, yt-dlp will get the metadata(Which are incomplete) from it instead of the json. Putting the video on <embed> makes yt-dlp read the json, but it breaks compatibility with the Safari Browser (Works on chrome). Is there a way to force it to read the LD json instead?

**Comment by bashonly** [comment]
> Is there a way to force it to read the LD json instead?

`--ies all,-html5`
or
`'allowed_extractors': ['all', '-html5']`
