### ISSUE TITLE
May I ask what command parameters are used to count the total number of views of all videos in the entire channel?

### ISSUE THREAD

**Issue by mS0gxokXEsg5ysJ7J79kzWiqO1fHgFA6ZR8eEls** [yt-dlp/yt-dlp#6105]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.01.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

May I ask what command parameters are used to count the total number of views of all videos in the entire channel?

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
You can `--print view_count` of all videos and sum it up yourself

**Comment by mS0gxokXEsg5ysJ7J79kzWiqO1fHgFA6ZR8eEls** [comment]
> You can `--print view_count` of all videos and sum it up yourself

I don't want to print, I want to display directly in the folder path.
Is there a separate parameter?
For example, something like %(channel_view_count)s, like this?
Check the official help documentation, it seems that there is no independent parameter.

**Comment by pukkandan** [comment]
No

**Comment by pukkandan** [comment]
> > 
> 
> I don't want to print, I want to display directly in the folder path.

I don't understand
