### ISSUE TITLE
Add support for Bilibili international (and download subtitles)

### ISSUE THREAD

**Issue by minhngoc25a** [yt-dlp/yt-dlp#611]
This is the issue [#29279](https://github.com/ytdl-org/youtube-dl/issues/29279) from the main youtube-dl repo.

## Checklist

- [x] I'm reporting a new site support request
- [x] I've verified that I'm running youtube-dl version **2021.06.06**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that none of the provided URLs violate any copyrights
- [x] I've searched the bug tracker for similar site support requests including closed ones

## Example URLs

- Single video: https://www.biliintl.com/en/play/35452
- Homepage: https://www.biliintl.com/

## Description

Bilibili is like Youtube but in China. It also has an international site, which is used for Chinese animation and anime. The international version doesn't have a search bar, and you can't switch the subtitle on your own. "What's Wrong with My Big Brother" is the series name of the example URLs. It was used as an example since it's not geo-restricted. To get to my point, the Bilibili app on Android and iOS has more features such as switching subtitles, commenting and searching series. I've looked for many ways to switch the subtitle language to another one to download it, but it always ends up with the top one (when sorted by A-Z). Therefore, along with video downloading, I would like someone with great knowledge in this field to implement a multilanguage subtitle download solution. Note that Bilibili subtitles are usually in the JSON format ([there is a converter for this](https://github.com/Sofronio/BilibiliSubtitle2Srt)) or CC and BCC ([related repo](https://github.com/Apollonyan/subtitle)).

**Comment by minhngoc25a** [comment]
Citing comments from SuperSonicHub1:

> @minhngoc25a Doing some early research, the single video link isn't a single video, it's a _season_. This is a single video: https://www.biliintl.com/en/play/35452/357787

> @minhngoc25a
> 
> > I've just recently found out that Subtitle Edit support Bilibili JSON subtitle format (.bcc or .json).
> 
> youtube-dl should still be able to parse and convert it without outside help, and we should also include the original JSON just for good measure.

> @minhngoc25a The site also supports Siamese, using the URL scheme https://www.biliintl.com/th/

> # How to Crack Bilibili International
> ## Parse URL
> ```
> https://www.biliintl.com/en/play/35452/357787
> https://www.biliintl.com/th/play/35452/357787
> https://www.biliintl.com/<lang>/play/<season_id>/<episode_id:optional>
> 
> == OR ==
> 
> https://www.biliintl.com/en/play/35452/357787?s_locale=en_US
> https://www.biliintl.com/en/play/35452/357787?s_locale=th_TH
> https://www.biliintl.com/en/play/<season_id>/<episode_id:optional>?s_locale=<locale>
> ```
> 
> ## Season
> * Get youtube-dl metadata from HTML page
> 
> ```
> title => meta[itemprop=name] || meta[property='og:title'] (remove `_bilibili`)
> description => meta[itemprop=description] || meta[property='og:type']
> ```
> 
> * Download JSON from `https://api.biliintl.com/intl/gateway/web/view/ogv_collection?s_locale=<locale>&season_id=<season_id>`
>   
>   * if `lang == 'th': locale == 'th_TH'`
>   * if `lang == 'en': locale == 'en_US'`
> * Iterate over each `episode` in `root["data"]["episodes"]`
>   
>   * use `episode['ep_id']` and `episode['long_title']` to create a [URL result](https://github.com/ytdl-org/youtube-dl/blob/master/youtube_dl/extractor/common.py#L951)
>     
>     * `InfoExtractor.url_result("https://www.biliintl.com/{lang}/play/{season_id}/{episode_id:optional}", video_title=long_title, video_id=ep_id)`
> 
> ## Episode
> * Get youtube-dl metadata through methods referenced in the season section
>   
>   * This website's API and HTML are surprisingly lean, so there isn't a lot of meat to pick off the bone.
> * Download JSON from `https://api.biliintl.com/intl/gateway/web/playurl?ep_id=<episode_id>&s_locale=<locale>&device=wap&platform=web&qn=64&tf=0&type=0`
>   
>   * Look to the season section for determining locale
> * Set `playurl` to `root['data']['playurl']`
> * Get youtube-dl metadata from `playurl`
>   
>   * "duration"
> * Get audio streams by iterating over `playurl['audio_resource']`
>   
>   * "url"
>   * metadata
>     
>     * "codecs"
>     * "mimetype"
>     * "size"
> * Get video streams by iterating over `playurl['video']`
>   
>   * "video_resource"
>     
>     * "url" (sometimes)
>     * "id"
>       
>       * Combine the path with domain `upos-bstar-mirrorakam.akamaized.net` to get a URL
>       * Requires the URL param `hdnts`; I don't get how it works: `exp=1623873893~hmac=b6f9ae587367bce35a28498735e7dcdf68795003b3f61ebf4f8387ac171c7dd2`
>     * "codecs"
>     * "mimetype"
>     * "size"
>     * "width"
>     * "height"
>   * "stream_info"
>     
>     * "desc_words", "desc_text"
> 
> youtube-dl will have to mux the video and audio streams in post using a post-processor, a la the YouTube extractor.
> 
> Input would be heavily appreciated on generating URLs for the other video streams. I'll probably not make the extractor myself, but I hope this is helpful to whoever does.

> Oh, totally forgot subtitles! Those can be requested with `https://api.biliintl.com/intl/gateway/m/subtitle?ep_id=<episode_id>&s_locale=<locale>`. They're in a proprietary JSON format; look to [OP](https://github.com/ytdl-org/youtube-dl/issues/29279#issue-919626089) for parsing them.

> Another amendment; in order to get the proper subtitle URL, you'll need to iterate over each item in `root["data"]["subtitles"]` to get the language (`item["key"]`) you want and request `item["url"]`. `item["title"]` gives a more formal subtitle name. Didn't want to forget this since downloading subtitles is the reason @minhngoc25a made this request in the first place!

> Yet another amendment; when doing that season request, if a "show" on BiliIntl has more than one season, there will be a `seasons` array within `root["data"]` giving us all the season IDs of a show.
> 
> ```json
> {
>     "seasons": [
>       {
>         "title": "S1",
>         "season_id": 37653
>       },
>       {
>         "title": "S2",
>         "season_id": 1005556
>       }
>     ]
> }
> ```
> 
> The episodes array will only contain the episodes relevant to the season ID requested. When a youtube-dl user gives us a URL that contains more than one season, should we download only the season from the season ID in the URL, or should we iterate over the seasons array and make multiple requests?

Citing comment from arnoldsecret:
> there's also global.bilibili.com, which is more of the same, best include that too.

**Comment by riyuejz** [comment]
add json to srt subtitle with this script
`https://github.com/y2361547758/bcc2ass`

**Comment by minhngoc25a** [comment]
@riyuejz Thanks for referring to that repo. I'll open another issue for that.

**Comment by cx410** [comment]
Hello
How to get resolution 1080p? I always get 480p resolution.

**Comment by minhngoc25a** [comment]
> Hello
> How to get resolution 1080p? I always get 480p resolution.

360p to 720p should be available for every non-VIP user. 1080p is locked on the VIP tier. Also, some series will restrict access to episodes if you're not logged in, so remember to pass in a cookie file.
