### ISSUE TITLE
How do I get "Title", "Upload_date" and "View_count" of videos into .txt files?

### ISSUE THREAD

**Issue by Koltinn** [yt-dlp/yt-dlp#6113]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.01.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Aware of both the "--write-info-json" (It downloads too much info and isn't easibly readable )  and  "--write-description" which doesnt download viewcount and upload date only description .

I did find a dude that did ask the same question and almost an accurate [ answer for it](https://github.com/ytdl-org/youtube-dl/issues/26831#issuecomment-706634271), but the code is for linux but only rips the metadata not the video file and audio.
I run Windows 10 have but I have both binaries for jq and yt-dlp. 

I am trying archive a couple of yt channels that I watch and I do not want the upload date and viewcount in the video title, like to keep it seperate

Hoping that I explained my issue, and is in the correct section.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output
[debug] Command-line config: ['-vU', '-f', 'best/bestaudio [vbr>16000]', '-ciw', '--write-info-json', '-o', '%(title)s.%(ext)s', '-v', 'https://www.youtube.com/watch?v=vVptaBz6BcA']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2023.01.06 [6becd25] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19044-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 4.2
[debug] Optional libraries: Cryptodome-3.16.0, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1760 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2023.01.06, Current version: 2023.01.06
yt-dlp is up to date (2023.01.06)

**Comment by bashonly** [comment]
```
--print-to-file [WHEN:]TEMPLATE FILE
                                Append given template to the file. The
                                values of WHEN and TEMPLATE are same as that
                                of --print. FILE uses the same syntax as the
                                output template. This option can be used
                                multiple times
```
`--print-to-file "title,upload_date,view_count" "%(title)s.txt"`
```
youtube-dl test video "'/\ä↭𝕐
20121002
52990
```
`--print-to-file "title,upload_date,view_count=" "%(title)s.txt"`
```
title = "youtube-dl test video \"'/\\\u00e4\u21ad\ud835\udd50"
upload_date = "20121002"
view_count = 52990
```
`--print-to-file "%(.{title,upload_date,view_count})#j" "%(title)s.json"`
```json
{
    "title": "youtube-dl test video \"'/\\\u00e4\u21ad\ud835\udd50",
    "upload_date": "20121002",
    "view_count": 52990
}
```

**Comment by Koltinn** [comment]
> ```
> --print-to-file [WHEN:]TEMPLATE FILE
>                                 Append given template to the file. The
>                                 values of WHEN and TEMPLATE are same as that
>                                 of --print. FILE uses the same syntax as the
>                                 output template. This option can be used
>                                 multiple times
> ```
> 
> `--print-to-file "title,upload_date,view_count" "%(title)s.txt"`
> 
> ```
> youtube-dl test video "'/\ä↭𝕐
> 20121002
> 52990
> ```
> 
> `--print-to-file "title,upload_date,view_count=" "%(title)s.txt"`
> 
> ```
> title = "youtube-dl test video \"'/\\\u00e4\u21ad\ud835\udd50"
> upload_date = "20121002"
> view_count = 52990
> ```
> 
> `--print-to-file "%(.{title,upload_date,view_count})#j" "%(title)s.json"`
> 
> ```json
> {
>     "title": "youtube-dl test video \"'/\\\u00e4\u21ad\ud835\udd50",
>     "upload_date": "20121002",
>     "view_count": 52990
> }
> ```
Thanks, using that from now on. It does it almost the thing I want it to do.

**Comment by wolfkrypter** [comment]
current_date=$(date -u)
#Variable zona horaria


echo -e "Buscar en Youtube:"
read varBusqueda


echo -e "\033[0;49;32m\n\n[Inicializando/descarga | BUSCADOR-MP3-STREAMING]\033[0m\n\n"

varINFORMACIÓN=$(mktemp)
# Variable temporal establecida para impresión e adjuntación de la información en este caso del title o el título de cada descarga e extracción, útil para la extracción multiple simultáneamente, e obtener un resultado favorable en cuanto a la la versatilidad para la constatación de descarga en cada descarga para el uso personal e inclusive para sub-aplicativos o sub-software compartidos en github como proyectos didácticos para ampliar el uso de forma recreacional de este aplicativo y como una forma de distracción saludable e educativa, al tomar de esta misma forma proyectos de GITHUB, y PYTHON en github,etcétera.

yt-dlp ytsearch:"$varBusqueda" -P "/storage/emulated/0/Download" -o "%(title)s.%(ext)s" --force-overwrites --no-warnings -f "ba[vcodec=none][abr<=153]" --print-to-file "%(title)s" "$varINFORMACIÓN" --extract-audio --audio-format mp3


# --force-overwrites , es útil en caso de un error de red la descarga no es efectuada completamente eliminé el archivo incompleto e inicie una descarga impecable para evitar problemas, e obtener un resultado impecable en cada descarga.


# -f "ba[vcodec=none][abr<=153]" , 'f' y 'ba' y 'vcodec=none' es útil junto a 'abr' en este caso para regular la calidad del audio y su tamaño en MB deacuerdo al 'abr' inferior en este caso a 153 kbps, lo cual ayuda a moderar el tamaño de cada archivo en MB, lo cuál ayuda a disminuir la cantidad de almacenamiento utilizado por archivos de audio u música conllevando a evitar llenar rápidamente el almacenamiento interno u externo al utilizar --audio-quality 0, e obteniendo la mejor calidad en cada descarga.


# Esta sentencia 'if' verifica si la variable temporal que contiene la información impresa en este caso del title o título, la contiene o no.

# Está forma evita en descargas múltiples una impresión multiple que claro está resultaría al resguardar en un archivo de TEXTO u en el mismo archivo de texto al utilizarla tal información de esta forma al finalizar la descarga en cada impresión de la información obtenida en múltiples sesiones simultáneamente o a la misma vez en diferentes ventanas.


if [ -s "$varINFORMACIÓN" ]
then



echo ""
echo -e "\n\033[0;666;32m[Descarga exitosa | BUSCADOR-MP3-STREAMING]\033[0m"
echo ""
echo ""
echo -e "\033[0;666;32mTítulo de descarga:\033[0m\n"

cat "$varINFORMACIÓN"

echo -e "\n\n\033[0;666;32mAlmacenado en:\033[0m\n\nstorage/emulated/0/Download\n"


echo -e "\n\033[0;666;32mFecha de descarga:\033[0m\n\n$current_date\n"


# Eliminación del contenido y variable temporal.

rm "$varINFORMACIÓN"
