### ISSUE TITLE
Rumble extractor occasionally prioritising lower quality formats

### ISSUE THREAD

**Issue by gamer191** [yt-dlp/yt-dlp#6119]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2023.01.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

USA

### Provide a description that is worded well enough to be understood

On some Rumble videos, the extractor prioritises the lower quality formats, presumably due to yt-dlp not being able to extract the higher quality format's resolution. This is odd, given it is able to extract the resolution when it [generates the format ID](https://github.com/yt-dlp/yt-dlp/blob/8aa0bd5d10627ece3c1815c01d02fb8bf22847a7/yt_dlp/extractor/rumble.py#L181)

DISCLAIMER: I do not in any way condone hate speech. I did not attempt to download this content, I was DMed the log on Discord by a user who wishes to remain anonymous. I have not watched the video, because the title makes it incredibly obvious that it is f***ed up hate speech.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vF', 'https://rumble.com/v26u984-gays-and-groomers-indoctrinating-your-children.html']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2023.01.06 [6becd25] (pip)
[debug] Python 3.8.6 (CPython AMD64 64bit) - Windows-10-10.0.19041-SP0 (OpenSSL 1.1.1g  21 Apr 2020)
[debug] exe versions: ffmpeg 2023-01-22-git-9d5e66942c-full_build-www.gyan.dev (setts), ffprobe 2023-01-22-git-9d5e66942c-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.9.8, brotli-1.0.9, certifi-2019.11.28, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.1
[debug] Proxy map: {}
[debug] Loaded 1760 extractors
[Rumble] Extracting URL: https://rumble.com/v26u984-gays-and-groomers-indoctrinating-your-children.html
[Rumble] v26u984-gays-and-groomers-indoctrinating-your-children.html: Downloading webpage
[RumbleEmbed] Extracting URL: https://rumble.com/embed/v2484h4
[RumbleEmbed] v2484h4: Downloading JSON metadata
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[info] Available formats for v2484h4:
ID        EXT  RESOLUTION FPS │   FILESIZE  TBR PROTO │ VCODEC   VBR ACODEC  ABR
────────────────────────────────────────────────────────────────────────────────
mp4-720p  mp4  unknown     30 │   72.97MiB   0k https │ unknown   0k unknown  0k
mp4-1080p mp4  unknown     30 │  100.12MiB   0k https │ unknown   0k unknown  0k
mp4-360p  mp4  640x360     30 │   23.61MiB 634k https │ unknown 634k unknown  0k
mp4-480p  mp4  854x480     30 │   30.29MiB 813k https │ unknown 813k unknown  0k
webm-480p webm 854x480     30 │   30.30MiB 814k https │ unknown 814k unknown  0k
```

**Comment by dirkf** [comment]
The known height that's used in the `format_id` is being overwritten by `0` values from the `meta`

**Comment by pukkandan** [comment]
It should just be using `merge_dicts` instead of `**`

**Comment by dirkf** [comment]
I thought so, but the `meta` values are `0` and aren't skipped by `merge_dicts()`.

**Comment by bashonly** [comment]
`default={}` is wrong, too:
```py
>>> meta = {'bitrate': 4128}
>>> traverse_obj(meta, {'tbr': 'bitrate', 'filesize': 'size', 'width': 'w', 'height': 'h'}, default={})
{'tbr': 4128, 'filesize': {}, 'width': {}, 'height': {}}

>>> meta = {}
>>> traverse_obj(meta, {'tbr': 'bitrate', 'filesize': 'size', 'width': 'w', 'height': 'h'}, default={})
{'tbr': {}, 'filesize': {}, 'width': {}, 'height': {}}
```
vs
```py
>>> meta = {'bitrate': 4128}
>>> traverse_obj(meta, {'tbr': 'bitrate', 'filesize': 'size', 'width': 'w', 'height': 'h'})
{'tbr': 4128}

>>> meta = {}
>>> traverse_obj(meta, {'tbr': 'bitrate', 'filesize': 'size', 'width': 'w', 'height': 'h'})
>>>
```

**Comment by bashonly** [comment]
`default={}` is wrong, too:
```py
>>> meta = {'bitrate': 4128}
>>> traverse_obj(meta, {'tbr': 'bitrate', 'filesize': 'size', 'width': 'w', 'height': 'h'}, default={})
{'tbr': 4128, 'filesize': {}, 'width': {}, 'height': {}}

>>> meta = {}
>>> traverse_obj(meta, {'tbr': 'bitrate', 'filesize': 'size', 'width': 'w', 'height': 'h'}, default={})
{'tbr': {}, 'filesize': {}, 'width': {}, 'height': {}}
```
vs
```py
>>> meta = {'bitrate': 4128}
>>> traverse_obj(meta, {'tbr': 'bitrate', 'filesize': 'size', 'width': 'w', 'height': 'h'})
{'tbr': 4128}

>>> meta = {}
>>> traverse_obj(meta, {'tbr': 'bitrate', 'filesize': 'size', 'width': 'w', 'height': 'h'})
{}
```
