### ISSUE TITLE
[Feature Request] Check if hoster is supported without doing any requests, list regex

### ISSUE THREAD

**Issue by kr4ssi** [yt-dlp/yt-dlp#612]
- [v] I'm reporting a feature request
- [v] I've verified that I'm running yt-dlp version **2021.08.02**
- [v] I've searched the bugtracker for similar feature requests including closed ones

I just found yt-dlp and I'm very happy to see that some of my feature requests (like info if a video is embeddable) I did at original youtube-dl already got merged in this project which got basically ignored by them.

Another one I though about a while ago is to check if a URL is supported by the program without doing an (unnecessary) request to the hoster, or an option to list all regex to do the check by a wrapper. [The way I'm doing it for now (I'm new to python)](https://github.com/kr4ssi/PonkBot/blob/master/balloons/add_youtube-dl_get_regex.py)

I would like to see something like this implemented in yt-dlp.

**Comment by pukkandan** [comment]
https://github.com/ytdl-org/youtube-dl#how-can-i-detect-whether-a-given-url-is-supported-by-youtube-dl

**Comment by kr4ssi** [comment]
That does a request though. So I'm basically requesting to include the regex in --list-extractors.

**Comment by pukkandan** [comment]
> It is not possible to detect whether a URL is supported or not. That's because youtube-dl contains a generic extractor which matches all URLs. You may be tempted to disable, exclude, or remove the generic extractor, but the generic extractor not only allows users to extract videos from lots of websites that embed a video from another service, but may also be used to extract video from a service that it's hosting itself. Therefore, we neither recommend nor support disabling, excluding, or removing the generic extractor.

You may think that you can just skip the GenericIE, but it does more work than what u'd think such as fixing URLs, handling redirects, finding html5 videos, downloading direct manifests etc

Also, just checking `VALID_URL` is not always sufficient to check if a url is supported. If you are sure you want to skip Generic, here's how u'd check support

```py
from yt_dlp.extractors import gen_extractor_classes

for ie in gen_extractor_classes():
    ie_key = ie.ie_key()
    if ie_key == 'Generic':
        continue
    if not ie.suitable(url):
        continue
    if not ie.working():
       print(f'Supported by {ie_key}, but marked as broken')
    else:
        print(f'Supported by {ie_key}')
    break
else:
    print('Unsupported')

**Comment by kr4ssi** [comment]
Thanks, but I just realized that's not even what I wanted.

Basically let's assume I want to whitelist certain hosters and I'm too lazy to do the regex by myself.

**Comment by pukkandan** [comment]
Same thing. Once you have an `ie_key` that is `suitable`, you can just check it against your whitelist

**Comment by pukkandan** [comment]
hey @kr4ssi, you didnt reply

If this does solve your issue, please close. Otherwise let me know why it doesn't

**Comment by pukkandan** [comment]
Closed due to inactivity
