### ISSUE TITLE
Unable to download m3u8, unknown type irvine

### ISSUE THREAD

**Issue by Adthrawn** [yt-dlp/yt-dlp#6120]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2023.01.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

I'm unable to download new videos from the site wrestle-universe.com. Previous videos are able to downloaded using the regular command of a direct link to the m3u8 file, however the video from today is not able to be downloaded. I've tried a couple other programs, as well as adding the cookies and referer flags, but am getting an error about this "unknown url type: irvine"

I downloaded the m3u8 locally and this line is in the file, hopefully it's just something that urllib or yt-dlp needs to learn how to handle

```#EXT-X-KEY:METHOD=AES-128,URI="irvine://aes",IV=0x5BAC71BEB33197D5600337CE86DE7862```

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://vod.asset.wrestle-universe.com/9WwMBERet9VdH52yMH3F5/live-a_1080p_2997fps.m3u8', '-o', 's2023e07.mp4']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2023.01.06 [6becd25] (pip)
[debug] Python 3.10.6 (CPython x86_64 64bit) - Linux-5.15.0-58-generic-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2020.06.20, mutagen-1.46.0, secretstorage-3.3.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1760 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2023.01.06, Current version: 2023.01.06
yt-dlp is up to date (2023.01.06)
[generic] Extracting URL: https://vod.asset.wrestle-universe.com/9WwMBERet9VdH52yMH3F5/live-a_1080p_2997fps.m3u8
[generic] live-a_1080p_2997fps: Downloading webpage
[debug] Identified a direct video link
[generic] live-a_1080p_2997fps: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] live-a_1080p_2997fps: Downloading 1 format(s): 0
[debug] Invoking hlsnative downloader on "https://vod.asset.wrestle-universe.com/9WwMBERet9VdH52yMH3F5/live-a_1080p_2997fps.m3u8"
[hlsnative] Downloading m3u8 manifest
WARNING: Live HLS streams are not supported by the native downloader. If this is a livestream, please add "--downloader ffmpeg --hls-use-mpegts" to your command
[hlsnative] Total fragments: 3113
[download] Destination: s2023e07.mp4
[download] s2023e07.mp4.part-Frag1 has already been downloaded
[download]   0.0% of ~   4.67GiB at   31.19MiB/s ETA Unknown (frag 1/3113)ERROR: unable to download video data: <urlopen error unknown url type: irvine>
Traceback (most recent call last):
  File "/home/mike/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3236, in process_info
    success, real_download = self.dl(temp_filename, info_dict)
  File "/home/mike/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 2959, in dl
    return fd.download(name, new_info, subtitle)
  File "/home/mike/.local/lib/python3.10/site-packages/yt_dlp/downloader/common.py", line 444, in download
    ret = self.real_download(filename, info_dict)
  File "/home/mike/.local/lib/python3.10/site-packages/yt_dlp/downloader/hls.py", line 354, in real_download
    return self.download_and_append_fragments(ctx, fragments, info_dict)
  File "/home/mike/.local/lib/python3.10/site-packages/yt_dlp/downloader/fragment.py", line 521, in download_and_append_fragments
    decrypt_fragment(fragment, self._read_fragment(ctx)), fragment['frag_index'], ctx)
  File "/home/mike/.local/lib/python3.10/site-packages/yt_dlp/downloader/fragment.py", line 363, in decrypt_fragment
    decrypt_info['KEY'] = decrypt_info.get('KEY') or _get_key(info_dict.get('_decryption_key_url') or decrypt_info['URI'])
  File "/home/mike/.local/lib/python3.10/site-packages/yt_dlp/downloader/fragment.py", line 353, in _get_key
    _key_cache[url] = self.ydl.urlopen(self._prepare_url(info_dict, url)).read()
  File "/home/mike/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3730, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/usr/lib/python3.10/urllib/request.py", line 541, in _open
    return self._call_chain(self.handle_open, 'unknown',
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 1419, in unknown_open
    raise URLError('unknown url type: %s' % type)
urllib.error.URLError: <urlopen error unknown url type: irvine>
```

**Comment by pukkandan** [comment]
It's not a standard URL scheme. We'll need to figure out how the website handles this and write an extractor and custom downloader. For that, the actual site URL is needed though

**Comment by Adthrawn** [comment]
I did a bit more digging myself, it's an encrypted stream. Was able to find the key and download it via hlsdl, but I guess it would need to be an actual proper site support for yt-dlp to be able to pull that info out without having to manually get the key

Is there anything I can do to help with the account part? It's a paid site, so I don't think you can create a free account

**Comment by Grub4K** [comment]
Please post the link to the page with any [more info](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-description-of-the-issue-itself-sufficient) you think might be helpful.
You may share the account details (read [this](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed)) with me through [E-Mail](mailto:contact@grub4k.xyz) or Discord (Grub4K#2417).

**Comment by Adthrawn** [comment]
I'll put a walkthrough of how I got the details on this one page and was able to download

this is the page: https://www.wrestle-universe.com/en/lives/buH9ibbfhdJAY4GKZcEuJX

- go to the ppv page, open the webdev tools
- go to the Souces tab and open to www.wrestle-universe.com->_next/static->chunks->pages->lives->some random bs
- click the curly brackets on the bottom
- search for 'aes128key' and then click the line number on the right to create a breakpoint. this variable exists like 5 times on the page, but any of them should be fine, i just picked the first one
- now click play on the video and it will play a bit then it should stop
- look over in the Scope area on the right. the key field is what you want

**Comment by codehound-00** [comment]
Abema golbal looks like identical API

wrestleuniverse url
https://www.wrestle-universe.com/en/lives/buH9ibbfhdJAY4GKZcEuJX

abema url
https://www.abema-global.com/en/lives/arb7fBhtMf86KJRPEfGvqV

Can abema extractor be added ? The old abematv extractors are outdated for this global API
