### ISSUE TITLE
add support to download multi row thumbnail photo from online video links

### ISSUE THREAD

**Issue by BahzBeih** [yt-dlp/yt-dlp#6121]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.01.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

peace, i hope you add support to download multi row thumbnail photo from online video links without downloading the whole video, there are a tool called "photojoiner" i think it can be used to do this with yt-dlp, so i hope you add support for this feature natively, or make yt-dlp use photojoiner as external tool like what it did with fmpeg.

https://github.com/darkoatanasovski/photojoiner

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
Out of scope
