### ISSUE TITLE
start/end time to download segment

### ISSUE THREAD

**Issue by mehargags** [yt-dlp/yt-dlp#6124]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.01.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

The documentation is quite exhaustive so I can't get my head around simple arguments that I can pass to be able to download:
1. Segment start and end time
2. Video 1080p Resolution MP4 format
3. Audio MP3 320kbps Stereo

Can someone please help me with exact line construct.
Many thanks

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
> * Segment start and end time

    --download-sections "*start-end"

> * Video 1080p Resolution MP4 format

    -S res:1080,ext:mp4:m4a

> * Audio MP3 320kbps Stereo

    -x --audio-quality 320k --audio-format mp3
