### ISSUE TITLE
https://www.primevideo.com/

### ISSUE THREAD

**Issue by mahiprime2001** [yt-dlp/yt-dlp#6125]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2023.01.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Example URLs

https://www.primevideo.com/region/eu/detail/0H3DDB4KBJFNDCKKLHNRLRLVKQ/ref=atv_br_def_r_br_c_unkc_1_10

### Provide a description that is worded well enough to be understood

i need the prime video url extractor 

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[generic] Extracting URL: https://www.primevideo.com/region/eu/detail/0H3DDB4KBJFNDCKKLHNRLRLVKQ/ref=atv_br_def_r_br_c_unkc_1_10
[generic] ref=atv_br_def_r_br_c_unkc_1_10: Downloading webpage
[generic] ref=atv_br_def_r_br_c_unkc_1_10: Extracting information
ERROR: Unsupported URL: https://www.primevideo.com/region/eu/detail/0H3DDB4KBJFNDCKKLHNRLRLVKQ/ref=atv_br_def_r_br_c_unkc_1_10
```

**Comment by mahiprime2001** [comment]
> > * [x]  I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) _**or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management)**_ to the best of my knowledge
> 
> Are you sure?

yes i am pretty sure if it is drm protected then how can i downloading the segments separately

**Comment by gamer191** [comment]
Can you please follow these instructions to check if the video is drm-protected https://github.com/yt-dlp/yt-dlp/issues/4062#issuecomment-1153474056

**Comment by mahiprime2001** [comment]
> Can you please follow these instructions to check if the video is drm-protected [#4062 (comment)](https://github.com/yt-dlp/yt-dlp/issues/4062#issuecomment-1153474056)

yep! it is drm protected but how does i can download the segments from the network log??

**Comment by Lesmiscore** [comment]
While you can still download the files, you can't decrypt them
