### ISSUE TITLE
WeVidi video download support

### ISSUE THREAD

**Issue by YTR76** [yt-dlp/yt-dlp#6129]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.01.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

I would like WeVidi video download support implemented into this as said in the title.
If you don't know what WeVidi is, it's basically a YouTube alternative that's like Vidlii but with actually good moderation as stated in the example video URL.
Example of a WeVidi video URL: https://wevidi.net/watch/UOxjNMyp70w

### Provide verbose output that clearly demonstrates the problem

- [x] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'test:youtube']
[debug] Portable config &quot;yt-dlp.conf&quot;: ['-i']
[debug] Encodings: locale cp65001, fs utf-8, pref cp65001, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2023.01.06 [9d339c4] (win32_exe)
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.22000-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg N-106550-g072101bd52-20220410 (fdk,setts), ffprobe N-106624-g391ce570c8-20220415, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2023.01.06, Current version: 2023.01.06
yt-dlp is up to date (2023.01.06)
"wevidi_video.mp4" is the filename for the WeVidi video
"https://wevidi.net/watch/" is the url for the video, and "video_id" is the id for the video
[command] yt-dlp -o wevidi_video.mp4 "https://wevidi.net/watch/video_id"
yes i know it probably doesn't meet up with the proper syntax but idk what does💀
```

**Comment by bashonly** [comment]
>  I'm requesting a feature unrelated to a specific site

Make sure to use the appropriate issue template. Read, don't just blindly check the boxes!

Post a verbose log attempting to d/l from the site being requested
`yt-dlp -vU "https://wevidi.net/watch/UOxjNMyp70w"`
