### ISSUE TITLE
[youtube] Native nsig extraction failed (Part 3)

### ISSUE THREAD

**Issue by Vangelis66** [yt-dlp/yt-dlp#6131]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2023.01.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Southern Europe

### Provide a description that is worded well enough to be understood

Since original #4635 has been a) **closed**, b) **locked**, I'm posting this (as a duplicate, I know - apologies 😉 ) to alert the team about the new breakage 😠 ...

In the last hours of **Jan 31st 2023** in my timezone, **Google** have shipped **yt player** `dac945fd`, which isn't palatable to the **native JS signature decryptor** 😭 ; the code falls back to `PhantomJS` and the **n-sig decryption** then succeeds...

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp -vUF "p7FCgw_GlWc" --ie youtube => 

[debug] Command-line config: ['--ffmpeg-location', '..\\FFmpeg', '--downloader-args', 'ffmpeg:-v 8 -stats', '-vUF', 'p7FCgw_GlWc', '--ie', 'youtube']
[debug] Encodings: locale cp1253, fs utf-8, pref cp1253, out utf-8 (No VT), error utf-8 (No VT), screen utf-8 (No VT)
[debug] yt-dlp version 2023.01.31 [83c4970e5] (win_x86_exe)
[debug] Python 3.7.16 (CPython x86 32bit) - Windows-Vista-6.0.6003-SP2 (OpenSSL 1.1.1s  1 Nov 2022)
[debug] exe versions: ffmpeg n5.2-dev-2245-N-109649-gab8cde6 (setts), ffprobe n5.2-dev-2245-N-109649-gab8cde6, phantomjs 2.1.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Extractor Plugins: AGB+NSIG (YoutubeIE)
[debug] Plugin directories: ['<redacted>\\yt-dlp\\yt-dlp-plugins\\YTAgeGateBypass.zip\\yt_dlp_plugins', '<redacted>\\yt-dlp\\yt-dlp-plugins\\YTNSigProxy.zip\\yt_dlp_plugins']
[debug] Loaded 1 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2023.01.06, Current version: 2023.01.31
yt-dlp is up to date (2023.01.31)
[youtube+AGB+NSIG] Extracting URL: p7FCgw_GlWc
[youtube+AGB+NSIG] p7FCgw_GlWc: Downloading webpage
[youtube+AGB+NSIG] p7FCgw_GlWc: Downloading android player API JSON
[youtube+AGB+NSIG] p7FCgw_GlWc: Downloading tv embedded player API JSON
[youtube+AGB+NSIG] p7FCgw_GlWc: Downloading web embedded client config
[youtube+AGB+NSIG] p7FCgw_GlWc: Downloading player dac945fd
[youtube+AGB+NSIG] p7FCgw_GlWc: Downloading web embedded player API JSON
[debug] [youtube+AGB+NSIG] Extracting signature function js_dac945fd_110
[debug] Saving youtube-sigfuncs.js_dac945fd_110 to cache
[debug] Saving youtube-nsig.dac945fd to cache
WARNING: [youtube+AGB+NSIG] p7FCgw_GlWc: Native nsig extraction failed: Trying with PhantomJS
         n = CM1X2GXxvV6DnIngBB_3JZ ; player = https://www.youtube.com/s/player/dac945fd/player_ias.vflset/en_US/base.js
[debug] [youtube+AGB+NSIG] Signature function returned an exception; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[youtube+AGB+NSIG] p7FCgw_GlWc: Executing signature code
[debug] [youtube+AGB+NSIG] PhantomJS command line: phantomjs "--ssl-protocol=any" "C:\Users\<redacted>\AppData\Local\Temp\tmp5jwo0rhl"
[debug] [youtube+AGB+NSIG] Decrypted nsig CM1X2GXxvV6DnIngBB_3JZ => 7_ThGFhQ0nuuyQ
[debug] Loading youtube-nsig.dac945fd from cache
WARNING: [youtube+AGB+NSIG] p7FCgw_GlWc: Native nsig extraction failed: Trying with PhantomJS
         n = 4sl9vdkJyZenf4-GQROY3b ; player = https://www.youtube.com/s/player/dac945fd/player_ias.vflset/en_US/base.js
[youtube+AGB+NSIG] p7FCgw_GlWc: Executing signature code
[debug] [youtube+AGB+NSIG] PhantomJS command line: phantomjs "--ssl-protocol=any" "C:\Users\<redacted>\AppData\Local\Temp\tmpptgw_phd"
[debug] [youtube+AGB+NSIG] Decrypted nsig 4sl9vdkJyZenf4-GQROY3b => PxVLDoRYUISU7A
[debug] [youtube+AGB+NSIG] Extracting signature function js_dac945fd_106
[debug] Saving youtube-sigfuncs.js_dac945fd_106 to cache
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[info] Available formats for p7FCgw_GlWc:
ID      EXT   RESOLUTION FPS CH |   FILESIZE   TBR PROTO | VCODEC          VBR ACODEC      ABR ASR MORE INFO
-------------------------------------------------------------------------------------------------------------------------
sb2     mhtml 48x27        0    |                  mhtml | images                   storyboard
sb1     mhtml 80x45        0    |                  mhtml | images                   storyboard
sb0     mhtml 160x90       0    |                  mhtml | images                   storyboard
249-drc webm  audio only      2 |    3.89MiB   51k https | audio only          opus        51k 48k low, DRC, webm_dash
250-drc webm  audio only      2 |    5.04MiB   66k https | audio only          opus        66k 48k low, DRC, webm_dash
249     webm  audio only      2 |    3.89MiB   51k https | audio only          opus        51k 48k low, webm_dash
250     webm  audio only      2 |    5.05MiB   67k https | audio only          opus        67k 48k low, webm_dash
140-drc m4a   audio only      2 |    9.83MiB  129k https | audio only          mp4a.40.2  129k 44k medium, DRC, m4a_dash
251-drc webm  audio only      2 |    9.65MiB  127k https | audio only          opus       127k 48k medium, DRC, webm_dash
140     m4a   audio only      2 |    9.83MiB  129k https | audio only          mp4a.40.2  129k 44k medium, m4a_dash
251     webm  audio only      2 |    9.70MiB  128k https | audio only          opus       128k 48k medium, webm_dash
394     mp4   256x144     30    |    6.40MiB   84k https | av01.0.00M.08   84k video only          144p, mp4_dash
160     mp4   256x144     30    |    2.53MiB   33k https | avc1.4d400c     33k video only          144p, mp4_dash
278     webm  256x144     30    |    6.12MiB   81k https | vp9             81k video only          144p, webm_dash
395     mp4   426x240     30    |   14.41MiB  190k https | av01.0.00M.08  190k video only          240p, mp4_dash
133     mp4   426x240     30    |    4.23MiB   56k https | avc1.4d4015     56k video only          240p, mp4_dash
242     webm  426x240     30    |    5.17MiB   68k https | vp9             68k video only          240p, webm_dash
396     mp4   640x360     30    |   22.87MiB  301k https | av01.0.01M.08  301k video only          360p, mp4_dash
134     mp4   640x360     30    |    8.67MiB  114k https | avc1.4d401e    114k video only          360p, mp4_dash
18      mp4   640x360     30  2 | ~ 12.63MiB  162k https | avc1.42001E    162k mp4a.40.2    0k 22k 360p
243     webm  640x360     30    |    9.90MiB  130k https | vp9            130k video only          360p, webm_dash
397     mp4   854x480     30    |   41.59MiB  548k https | av01.0.04M.08  548k video only          480p, mp4_dash
135     mp4   854x480     30    |   14.71MiB  194k https | avc1.4d401f    194k video only          480p, mp4_dash
244     webm  854x480     30    |   15.81MiB  208k https | vp9            208k video only          480p, webm_dash
22      mp4   1280x720    30  2 | ~ 45.22MiB  582k https | avc1.64001F    582k mp4a.40.2    0k 44k 720p
398     mp4   1280x720    30    |   84.46MiB 1112k https | av01.0.05M.08 1112k video only          720p, mp4_dash
136     mp4   1280x720    30    |   34.36MiB  453k https | avc1.4d401f    453k video only          720p, mp4_dash
247     webm  1280x720    30    |   30.57MiB  403k https | vp9            403k video only          720p, webm_dash
399     mp4   1920x1080   30    |  133.61MiB 1760k https | av01.0.08M.08 1760k video only          1080p, mp4_dash
137     mp4   1920x1080   30    |  216.45MiB 2851k https | avc1.640028   2851k video only          1080p, mp4_dash
248     webm  1920x1080   30    |  122.86MiB 1618k https | vp9           1618k video only          1080p, webm_dash
```

**Comment by gamer191** [comment]
I just noticed that #6169 (by Gr3kidd3r) contains a player we haven’t seen before `97ea7458`. I haven’t tested if it works in master, because I’m on my phone

**Comment by bashonly** [comment]
> `97ea7458`

It works in master. It breaks native nsig extraction in 2023.01.06 for the same reason as player `dac945fd`: an `if` statement in one of the array's functions, which is handled by 8b008d62544b82e24a0ba36c30e8e51855d93419

**Comment by gamer191** [comment]
New player (`f565d246`) reported [here](https://github.com/yt-dlp/yt-dlp/commit/8b008d62544b82e24a0ba36c30e8e51855d93419#commitcomment-99566542). Can someone please test it on master?

**Comment by pukkandan** [comment]
@anunasica is not on master. The player works fine for me

**Comment by Akczht** [comment]
I am facing the same issue on player "97ea7458"

**Comment by gamer191** [comment]
@akczht are you running from master? If you don’t know what that is then the answer is no

**Comment by gamer191** [comment]
@akczht are you running from master? If you don’t know what that is then the answer is no

**Comment by Akczht** [comment]
not from master, rel. 2023.01.06, answer of what is "no" ?

**Comment by pukkandan** [comment]
Use https://github.com/ytdl-patched/yt-dlp or wait for release

**Comment by DulusNo** [comment]
New player 6f20102c:
```powershell
λ yt-dlp_nightly.exe --ignore-config https://www.youtube.com/watch?v=32TU1ATIrjk -vU -F --extractor-args "youtube:player-client=web"
[debug] Command-line config: ['--ignore-config', 'https://www.youtube.com/watch?v=32TU1ATIrjk', '-vU', '-F', '--extractor-args', 'youtube:player-client=web']
[debug] Encodings: locale cp1251, fs utf-8, pref cp1251, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2023.04.19.042141 [8f0be90ec] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 6.0-full_build-www.gyan.dev (setts), ffprobe 6.0-full_build-www.gyan.dev, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.2
[debug] Proxy map: {}
[debug] Loaded 1801 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Available version: nightly@2023.04.19.042141, Current version: nightly@2023.04.19.042141
Current Build Hash: fdff0333689768f11466b1c8fde05c470a48aa9fef482d3f9ed58ae4083ec69b
yt-dlp is up to date (nightly@2023.04.19.042141)
[youtube] Extracting URL: https://www.youtube.com/watch?v=32TU1ATIrjk
[youtube] 32TU1ATIrjk: Downloading webpage
[youtube] 32TU1ATIrjk: Downloading player 6f20102c
[debug] Saving youtube-nsig.6f20102c to cache
WARNING: [youtube] 32TU1ATIrjk: Native nsig extraction failed: Trying with PhantomJS
         n = bHbfoOorqVPh3J ; player = https://www.youtube.com/s/player/6f20102c/player_ias.vflset/en_US/base.js
[debug] [youtube] Signature function returned an exception; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[youtube] 32TU1ATIrjk: Executing signature code
[debug] [youtube] PhantomJS command line: phantomjs "--ssl-protocol=any" "C:\Temp\tmpw1ptwsnw"
[debug] [youtube] Decrypted nsig bHbfoOorqVPh3J => jtv4awXd4Uxy7w
[debug] Loading youtube-nsig.6f20102c from cache
WARNING: [youtube] 32TU1ATIrjk: Native nsig extraction failed: Trying with PhantomJS
         n = 715xvBdpBOUmT9 ; player = https://www.youtube.com/s/player/6f20102c/player_ias.vflset/en_US/base.js
[youtube] 32TU1ATIrjk: Executing signature code
[debug] [youtube] PhantomJS command line: phantomjs "--ssl-protocol=any" "C:\Temp\tmpcwn70fqu"
[debug] [youtube] Decrypted nsig 715xvBdpBOUmT9 => a5BfIQLLNe202w
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[info] Available formats for 32TU1ATIrjk:
ID  EXT   RESOLUTION FPS CH │   FILESIZE   TBR PROTO │ VCODEC        VBR ACODEC      ABR ASR MORE INFO
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────
sb2 mhtml 48x27        0    │                  mhtml │ images                                storyboard
sb1 mhtml 80x45        0    │                  mhtml │ images                                storyboard
sb0 mhtml 160x90       0    │                  mhtml │ images                                storyboard
249 webm  audio only      2 │    6.20MiB   51k https │ audio only        opus        51k 48k low, WEB, webm_dash
250 webm  audio only      2 │    7.99MiB   66k https │ audio only        opus        66k 48k low, WEB, webm_dash
140 m4a   audio only      2 │   15.79MiB  129k https │ audio only        mp4a.40.2  129k 44k medium, WEB, m4a_dash
251 webm  audio only      2 │   14.59MiB  120k https │ audio only        opus       120k 48k medium, WEB, webm_dash
160 mp4   256x144     30    │    8.34MiB   68k https │ avc1.4d400c   68k video only          144p, WEB, mp4_dash
278 webm  256x144     30    │    8.14MiB   67k https │ vp9           67k video only          144p, WEB, webm_dash
133 mp4   426x240     30    │   18.14MiB  149k https │ avc1.4d4015  149k video only          240p, WEB, mp4_dash
242 webm  426x240     30    │   13.14MiB  108k https │ vp9          108k video only          240p, WEB, webm_dash
134 mp4   640x360     30    │   35.35MiB  290k https │ avc1.4d401e  290k video only          360p, WEB, mp4_dash
18  mp4   640x360     30  2 │   47.35MiB  388k https │ avc1.42001E  388k mp4a.40.2    0k 44k 360p, WEB
243 webm  640x360     30    │   22.61MiB  185k https │ vp9          185k video only          360p, WEB, webm_dash
135 mp4   854x480     30    │   62.75MiB  515k https │ avc1.4d401f  515k video only          480p, WEB, mp4_dash
244 webm  854x480     30    │   37.46MiB  307k https │ vp9          307k video only          480p, WEB, webm_dash
22  mp4   1280x720    30  2 │ ~138.57MiB 1110k https │ avc1.64001F 1110k mp4a.40.2    0k 44k 720p, WEB
136 mp4   1280x720    30    │  119.66MiB  981k https │ avc1.64001f  981k video only          720p, WEB, mp4_dash
247 webm  1280x720    30    │   70.62MiB  579k https │ vp9          579k video only          720p, WEB, webm_dash
137 mp4   1920x1080   30    │  229.41MiB 1882k https │ avc1.640028 1882k video only          1080p, WEB, mp4_dash
248 webm  1920x1080   30    │  112.90MiB  926k https │ vp9          926k video only          1080p, WEB, webm_dash
271 webm  2560x1440   30    │  375.37MiB 3079k https │ vp9         3079k video only          1440p, WEB, webm_dash
313 webm  3840x2160   30    │  765.04MiB 6275k https │ vp9         6275k video only          2160p, WEB, webm_dash
```

**Comment by dirkf** [comment]
Related: https://github.com/ytdl-org/youtube-dl/issues/32066

**Comment by pukkandan** [comment]
Instead of messing with operator precedence, we could tightly bind +/- in `_separate`. Both approaches have edge case that breaks, but this is much easier that your approach and solves all your current tests (incl the broken one)

**Comment by dirkf** [comment]
[Player `cfa9e7cb`](https://github.com/ytdl-org/youtube-dl/issues/32066#issuecomment-1544500953) wants to do `false << NaN`. `NaN` should be zeroised (!) but isn't.

**Comment by dirkf** [comment]
Simple fix: https://github.com/ytdl-org/youtube-dl/commit/a85a875fef2e9b097c3f6f93f1d0cead06f84e43

**Comment by onionware-github** [comment]
> Still broken for me:
> 
> ```shell
> $ yt-dlp -vUF "p7FCgw_GlWc" --ie youtube
> [debug] Command-line config: ['-vUF', 'p7FCgw_GlWc', '--ie', 'youtube']
> [debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
> [debug] yt-dlp version stable@2023.03.04 [392389b7d]
> [debug] Lazy loading extractors is disabled
> [debug] Python 3.11.3 (CPython x86_64 64bit) - Linux-6.3.1-skylake-xanmod1-2-x86_64-with-glibc2.37 (OpenSSL 3.0.8 7 Feb 2023, glibc 2.37)
> [debug] exe versions: ffmpeg 6.0 (setts), ffprobe 6.0, phantomjs 2.1.1, rtmpdump 2.4
> [debug] Optional libraries: Cryptodome-3.17, brotlicffi-1.0.9.2, certifi-2023.05.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
> [debug] Proxy map: {}
> [debug] Loaded 1 extractors
> [debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
> Available version: stable@2023.03.04, Current version: stable@2023.03.04
> yt-dlp is up to date (stable@2023.03.04)
> [youtube] Extracting URL: p7FCgw_GlWc
> [youtube] p7FCgw_GlWc: Downloading webpage
> [youtube] p7FCgw_GlWc: Downloading android player API JSON
> [youtube] p7FCgw_GlWc: Downloading tv embedded player API JSON
> [youtube] p7FCgw_GlWc: Downloading web embedded client config
> [youtube] p7FCgw_GlWc: Downloading player cfa9e7cb
> [youtube] p7FCgw_GlWc: Downloading web embedded player API JSON
> [debug] [youtube] Extracting signature function js_cfa9e7cb_103
> [debug] Loading youtube-sigfuncs.js_cfa9e7cb_103 from cache
> [debug] Loading youtube-nsig.cfa9e7cb from cache
> WARNING: [youtube] p7FCgw_GlWc: Native nsig extraction failed: Trying with PhantomJS
>          n = TLOOCHTl5bBmrTuIQc ; player = https://www.youtube.com/s/player/cfa9e7cb/player_ias.vflset/en_US/base.js
> [debug] [youtube] Signature function returned an exception; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
> [youtube] p7FCgw_GlWc: Executing signature code
> [debug] [youtube] PhantomJS command line: phantomjs --ssl-protocol=any /tmp/tmp9eesellp
> [debug] [youtube] Decrypted nsig TLOOCHTl5bBmrTuIQc => wAIxyrYUAMA8Pw
> [debug] Loading youtube-nsig.cfa9e7cb from cache
> WARNING: [youtube] p7FCgw_GlWc: Native nsig extraction failed: Trying with PhantomJS
>          n = aCi3iElgd2kq0bxVbQ ; player = https://www.youtube.com/s/player/cfa9e7cb/player_ias.vflset/en_US/base.js
> [youtube] p7FCgw_GlWc: Executing signature code
> [debug] [youtube] PhantomJS command line: phantomjs --ssl-protocol=any /tmp/tmpaphcympt
> [debug] [youtube] Decrypted nsig aCi3iElgd2kq0bxVbQ => QX1y8jGb2IbZ0w
> [debug] [youtube] Extracting signature function js_cfa9e7cb_107
> [debug] Loading youtube-sigfuncs.js_cfa9e7cb_107 from cache
> [debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
> [debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
> [info] Available formats for p7FCgw_GlWc:
> ID      EXT   RESOLUTION FPS CH │   FILESIZE   TBR PROTO │ VCODEC          VBR ACODEC      ABR ASR MORE INFO
> ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
> sb2     mhtml 48x27        0    │                  mhtml │ images                                  storyboard
> sb1     mhtml 80x45        0    │                  mhtml │ images                                  storyboard
> sb0     mhtml 160x90       0    │                  mhtml │ images                                  storyboard
> 249-drc webm  audio only      2 │    3.89MiB   51k https │ audio only          opus        51k 48k low, DRC, TV-E, webm_dash
> 250-drc webm  audio only      2 │    5.04MiB   66k https │ audio only          opus        66k 48k low, DRC, TV-E, webm_dash
> 249     webm  audio only      2 │    3.89MiB   51k https │ audio only          opus        51k 48k low, TV-E, webm_dash
> 250     webm  audio only      2 │    5.05MiB   67k https │ audio only          opus        67k 48k low, TV-E, webm_dash
> 140-drc m4a   audio only      2 │    9.83MiB  129k https │ audio only          mp4a.40.2  129k 44k medium, DRC, TV-E, m4a_dash
> 251-drc webm  audio only      2 │    9.65MiB  127k https │ audio only          opus       127k 48k medium, DRC, TV-E, webm_dash
> 140     m4a   audio only      2 │    9.83MiB  129k https │ audio only          mp4a.40.2  129k 44k medium, TV-E, m4a_dash
> 251     webm  audio only      2 │    9.70MiB  128k https │ audio only          opus       128k 48k medium, TV-E, webm_dash
> 394     mp4   256x144     30    │    6.40MiB   84k https │ av01.0.00M.08   84k video only          144p, TV-E, mp4_dash
> 160     mp4   256x144     30    │    2.53MiB   33k https │ avc1.4d400c     33k video only          144p, TV-E, mp4_dash
> 278     webm  256x144     30    │    6.12MiB   81k https │ vp9             81k video only          144p, TV-E, webm_dash
> 395     mp4   426x240     30    │   14.41MiB  190k https │ av01.0.00M.08  190k video only          240p, TV-E, mp4_dash
> 133     mp4   426x240     30    │    4.23MiB   56k https │ avc1.4d4015     56k video only          240p, TV-E, mp4_dash
> 242     webm  426x240     30    │    5.17MiB   68k https │ vp9             68k video only          240p, TV-E, webm_dash
> 396     mp4   640x360     30    │   22.87MiB  301k https │ av01.0.01M.08  301k video only          360p, TV-E, mp4_dash
> 134     mp4   640x360     30    │    8.67MiB  114k https │ avc1.4d401e    114k video only          360p, TV-E, mp4_dash
> 18      mp4   640x360     30  2 │ ~ 12.63MiB  162k https │ avc1.42001E    162k mp4a.40.2    0k 22k 360p, TV-E
> 243     webm  640x360     30    │    9.90MiB  130k https │ vp9            130k video only          360p, TV-E, webm_dash
> 397     mp4   854x480     30    │   41.59MiB  548k https │ av01.0.04M.08  548k video only          480p, TV-E, mp4_dash
> 135     mp4   854x480     30    │   14.71MiB  194k https │ avc1.4d401f    194k video only          480p, TV-E, mp4_dash
> 244     webm  854x480     30    │   15.81MiB  208k https │ vp9            208k video only          480p, TV-E, webm_dash
> 398     mp4   1280x720    30    │   84.46MiB 1112k https │ av01.0.05M.08 1112k video only          720p, TV-E, mp4_dash
> 136     mp4   1280x720    30    │   34.36MiB  453k https │ avc1.4d401f    453k video only          720p, TV-E, mp4_dash
> 247     webm  1280x720    30    │   30.57MiB  403k https │ vp9            403k video only          720p, TV-E, webm_dash
> 399     mp4   1920x1080   30    │  133.61MiB 1760k https │ av01.0.08M.08 1760k video only          1080p, TV-E, mp4_dash
> 137     mp4   1920x1080   30    │  216.45MiB 2851k https │ avc1.640028   2851k video only          1080p, TV-E, mp4_dash
> 248     webm  1920x1080   30    │  122.86MiB 1618k https │ vp9           1618k video only          1080p, TV-E, webm_dash
> ```
> 
> Installed from master ([`21b9413`](https://github.com/yt-dlp/yt-dlp/commit/21b9413cf7dd4830b2ece57af21589dd4538fc52)) with pip.

Can confirm. I tried to compile yt-dlp with phantomjs installed via pip and I still get this message:
```
WARNING: [youtube] JKoVD8Ev2gM: nsig extraction failed: You may experience throttling for some formats
         Install PhantomJS to workaround the issue. Please download it from https://phantomjs.org/download.html
         n = j_phm85tvMeiME2GOo ; player = https://www.youtube.com/s/player/cfa9e7cb/player_ias.vflset/en_US/base.js
```

**Comment by gamer191** [comment]
`youtube-nsig.cfa9e7cb` is throttled for everyone.  It is only throttled for some formats.
### Please do not post logs unless you encounter a warning for a player other then `cfa9e7cb`!

**Comment by gamer191** [comment]
> Is there another player that can be used to workaround this?

I highly doubt it, because yt-dlp has to use whichever player youtube.com is using


That said, even if you see that warning, it only affects a few formats (not the default ones*) and you can use `--list-formats` to pick formats that aren't throttled (you'll know if it's throttled, because it says `THROTTLED` in all caps)

*Excluding age-restricted videos, which are currently throttled for all formats. I found a complicated workaround though, and I'll post instructions later

**Comment by gamer191** [comment]
Throttling workaround for age-gated videos. This won't work for videos that are 1440p or above*:

1. log into Youtube in your browser. This doesn't seem to require your account to have access to age-restricted videos
2. add `--extractor-args "youtube:player-client=android_creator,default" --cookies-from-browser chrome` to your command, replacing `chrome` with the name of your web browser

*if you really want to bypass throttling, you can limit the download quality to 1080p, by adding `-f 137+ba` to the end of your command
