### ISSUE TITLE
[Bilibili] 互动视频 interactive split-path videos

### ISSUE THREAD

**Issue by pxssy** [yt-dlp/yt-dlp#6135]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2023.01.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Singapore

### Provide a description that is worded well enough to be understood

https://www.bilibili.com/video/BV14Q4y1q7nD

There are videos like these known in Chinese as 互动视频. Basically, they're interactive videos where you get to pick your own path through the videos. Usually they're like a few minutes long, then a option for 2 or more split paths. 

Currently, yt-dlp does not appear to support this at all. The sub-paths do not have unique or independent urls, so its quite impossible to download them. Nor is it feasible to do it manually, if there are say 5 levels and 2^5 is quite tedious.

What currently happens is, it downloads 1st level, and stops. It doesn't iterate through all of the sub-levels. 

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp -vU https://www.bilibili.com/video/BV14Q4y1q7nD
[debug] Command-line config: ['-vU', 'https://www.bilibili.com/video/BV14Q4y1q7nD']
[debug] User config "C:\Users\Pxssy\AppData\Roaming\yt-dlp\config": ['--cookies', 'C:/Users/Daryl/AppData/Roaming/yt-dlp/cookies', '--output', './yt-dlp/%(uploader,channel)s (%(uploader_id,channel_id)s)/[%(upload_date)s] %(title).150s [%(resolution)s@%(fps)sp] (%(id)s).%(format_id)s.%(ext)s', '--format', 'bestvideo+bestaudio/best', '--format-sort', 'res,fps,quality,size,br', '--retries', 'infinite', '--fragment-retries', 'infinite', '--ignore-errors', '--mtime', '--no-continue', '--no-overwrites', '--part', '--write-thumbnail', '--write-annotations', '--write-auto-subs', '--write-description', '--write-info-json', '--write-playlist-metafiles', '--write-subs']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2023.01.06 [6becd25] (pip)
[debug] Python 3.9.6 (CPython AMD64 64bit) - Windows-10-10.0.19044-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 4.2.3, ffprobe 5.0.1-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.11.0, brotli-1.0.9, certifi-2021.10.08, mutagen-1.45.1, sqlite3-2.6.0, websockets-9.1
[debug] Proxy map: {}
[debug] Loaded 1760 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2023.01.06, Current version: 2023.01.06
yt-dlp is up to date (2023.01.06)
[BiliBili] Extracting URL: https://www.bilibili.com/video/BV14Q4y1q7nD
[BiliBili] 14Q4y1q7nD: Downloading webpage
[BiliBili] BV14Q4y1q7nD: Extracting videos in anthology
[BiliBili] Format(s) 1080P 高码率, 1080P 高清, 720P 高清 are missing; you have to login or become premium member to download them. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies
[BiliBili] 721319002: Extracting chapters
[BiliBili] BV14Q4y1q7nD: Downloading JSON metadata
[info] BV14Q4y1q7nD: Downloading subtitles: danmaku
[debug] Sort order given by user: res, fps, quality, size, br
[debug] Formats sorted by: hasvid, ie_pref, res, fps, quality, filesize, fs_approx, tbr, vbr, abr, lang, hdr:12(7), vcodec:vp9.2(10), channels, acodec, asr, proto, vext, aext, hasaud, source, id
[info] BV14Q4y1q7nD: Downloading 1 format(s): 8+2
[info] Video description is already present
[info] Video subtitle danmaku.xml is already present
[info] Video thumbnail is already present
[info] Video metadata is already present
WARNING: There are no annotations to write.
[download] yt-dlp\绝不早到小吱吱 (11616487)\[20211028] 【互动】当你的女房东是个间谍，你会…… [852x480@25.0p] (BV14Q4y1q7nD).8+2.mp4 has already been downloaded
```

**Comment by z0z0r4** [comment]
互动视频是没法这样下载的吧...是特殊格式

**Comment by c-basalt** [comment]
I have tried writing a path-extractor to traverse all divisions. Each piece of video segment is identified with a unique `cid` (paired with `aid`) to locate video resources. The regular video link now serves as a playlist link instead.
However, it may require some major change to use `aid`-`cid` pair instead of url as minimal unit to get video. It looks hard to me to download an interactive-video link as a playlist link without refactoring the main code block.

Here are the code for getting `cid` of video segments:
```Python

class BilibiliBaseIE(InfoExtractor):
...
    def _get_divisions(self, aid, graph_version, edges={}, edge_id=""):
        division_data = self._download_json(
            f'https://api.bilibili.com/x/stein/edgeinfo_v2?graph_version={graph_version}&edge_id={edge_id}&aid={aid}',
            aid, note=f'Extracting divisions from edge {edge_id}', fatal=True)
        # extracting info from history nodes
        for node in traverse_obj(division_data, ('data', 'story_list'), default=[]):
            edges[node['edge_id']] = traverse_obj(node, {
                'title': ('title', {str_or_none}),
                'cid': ('cid', {int}),
            })
        # extracting info from current node and upcoming nodes
        edges[edge_id] = {
            **edges.get(edge_id, {}),
            'title': str_or_none(traverse_obj(division_data, ("data", "title"))),
            'choices': traverse_obj(division_data, ("data", "edges", "questions", ..., "choices", ..., {
                'edge_id': ('id', {int}),
                'cid': ('cid', {int}),
                'text': ('option', {str_or_none}),
            })),
        }
        # traverse choices and following nodes
        for choice in edges[edge_id]['choices']:
            if choice['edge_id'] not in edges:
                edges[choice['edge_id']] = {
                    'cid': choice['cid'],
                }
                self._get_divisions(aid, graph_version, edges=edges, edge_id=choice['edge_id'])
        return edges

class BiliBiliIE(BilibiliBaseIE):
...

    def _real_extract(self, url):
...

        is_interactive = traverse_obj(video_data, ("rights","is_stein_gate"))
        if is_interactive:
            graph_version = traverse_obj(
                self._download_json(
                    f'https://api.bilibili.com/x/player/wbi/v2?aid={aid}&cid={cid}',
                    aid, note=f'Extracting graph version for av{aid}', fatal=True),
                ('data', 'interaction', 'graph_version'))
            divisions = self._get_divisions(aid, graph_version, {1: {"cid": cid}}, 1)
            # TO DO: download each segment using aid-cid pair

**Comment by c-basalt** [comment]
@pxssy I've written a patch to download interactive videos as playlists. It would be nice if you can test this branch and provide some feedbacks:
https://github.com/c-basalt/yt-dlp/tree/bili-interactive

**Comment by c-basalt** [comment]
> https://www.ithome.com/0/694/102.htm

Also related to `BilibiliIE` so leave the memo here: code 87007 ("message":"87007") for `https://api.bilibili.com/x/player/playurl` of `playinfo` is for member-only video. Need to change `playinfo = ... ['data']` to `playinfo = ... .get('data')` and hint login
Additional info can be found at `initial_state['elecFullInfo']['show_info']`. Message can be obtained by `clean_html(get_element_by_class('tips-toast', webpage))`
