### ISSUE TITLE
Is there a way to extract the list of subscriptions? 

### ISSUE THREAD

**Issue by iBicha** [yt-dlp/yt-dlp#6144]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.01.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I would like to extract the list of youtube channels I'm subscripted to.
The list is in https://www.youtube.com/feed/channels

I tried something like 
```
yt-dlp https://www.youtube.com/feed/channels --lazy-playlist --cookies-from-browser chrome --print '%(channel_id)s'
```
But it is still looping through the videos instead of going through the channel list

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
Add `--flat-playlist`

**Comment by iBicha** [comment]
> Add `--flat-playlist` and print `id`/`url`

I added that option, but it's still iterating over videos, not channels. I can kinda let it go through all the videos, and read the channels, and remove duplicates, but that takes a long time

**Comment by iBicha** [comment]
You are right! I think the commend is fine, I had a typo somewhere
Thanks!
