### ISSUE TITLE
set a random delay between playlist downloads

### ISSUE THREAD

**Issue by G2G2G2G** [yt-dlp/yt-dlp#6145]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.01.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

When you download a playlist of videos (from any site) it downloads 1 video at a time
when it goes to the next video it immediately downloads the metadata etc then starts the video download

Is there a way to not do that immediately, but instead sleep a random amount of seconds before starting the next video?
Many sites have flood controls and some playlists are hundreds of videos, requiring stopping the DL every 5 mins and starting back up in like 30 mins.. I'd rather just have an auto wait for 3-10 mins each vid and they'd never block the DL at all

All I see is --playlist-random               Download playlist videos in random order 
which isn't what I want, but it'll probably help with what I am doing so I'd use that as well

thanks

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
See `--sleep-interval`/`--max-sleep-interval`

**Comment by G2G2G2G** [comment]
nice thanks

**Comment by G2G2G2G** [comment]
lmao that's each fragment of the download?
