### ISSUE TITLE
log all url for downloaded pages

### ISSUE THREAD

**Issue by her34** [yt-dlp/yt-dlp#6148]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.01.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

when downloading video from tiktok, the url used to get api json is not logged on console when using option "--print-traffic" or "--verbose".

the console currently shows this

> [TikTok] Extracting URL: https://www.tiktok.com/@patroxofficial/video/6742501081818877190
> [TikTok] 6742501081818877190: Downloading video feed
> [TikTok] Saving request to 

i am requesting it shows something like this:

> [TikTok] Extracting URL: https://www.tiktok.com/@patroxofficial/video/6742501081818877190
> [TikTok] 6742501081818877190: Downloading video feed
> [TikTok] https://api16-normal-useast5.us.tiktokv.com/aweme/v1/aweme/detail/?aweme_id=...
> [TikTok] Saving request to 

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
--print-traffic

**Comment by bashonly** [comment]
> the url used to get api json is not logged on console when using option "--print-traffic"

it is, though, in the GET request:
```
$ yt-dlp --print-traffic "https://www.tiktok.com/@patroxofficial/video/6742501081818877190"
[TikTok] Extracting URL: https://www.tiktok.com/@patroxofficial/video/6742501081818877190
[TikTok] 6742501081818877190: Downloading video feed
send: b'GET /aweme/v1/feed/?aweme_id=6742501081818877190&version_name=26.1.3&version_code=260103&build_number=26.1.3&manifest_version_code=260103&update_version_code=260103&openudid=5c3d0fb79b5e6a6c&uuid=2323611746315126&_rticket=1675521365356&ts=1675521365&device_brand=Google&device_type=Pixel+4&device_platform=android&resolution=1080%2A1920&dpi=420&os_version=10&os_api=29&carrier_region=US&sys_region=US&region=US&app_name=trill&app_language=en&language=en&timezone_name=America%2FNew_York&timezone_offset=-14400&channel=googleplay&ac=wifi&mcc_mnc=310260&is_my_cn=0&aid=1180&ssmix=a&as=a1qwert123&cp=cbfhckdckkde1 HTTP/1.1\r\nHost: api16-normal-c-useast1a.tiktokv.com\r\nCookie: odin_tt=a9768ce619a1d46f8aad701848f0ba34fa8baf6086c3543c19f6dbd72ec189ce84a72c4e9ccb2f43525d63162dfbc1b36ac72f8c31aa0c45a2a6b39dc89ccaccc692caf76e3a8ee8595a9c6f22825744\r\nUser-Agent: com.ss.android.ugc.trill/260103 (Linux; U; Android 10; en_US; Pixel 4; Build/QQ3A.200805.001; Cronet/58.0.2991.0)\r\nAccept: application/json\r\nAccept-Language: en-us,en;q=0.5\r\nSec-Fetch-Mode: navigate\r\nAccept-Encoding: gzip, deflate, br\r\nConnection: close\r\n\r\n'
```
