### ISSUE TITLE
[vimeo] Unable to extract info section

### ISSUE THREAD

**Issue by techfor** [yt-dlp/yt-dlp#6149]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2023.01.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Hello, I am getting increasingly more 'unable to extract info section' errors. The urls are from vimeo. On the same url, sometimes, this error appears and sometimes it doesn't.  at times,can get same error on same url for 6-10 consecutive time.  I'm go through big input text file and it is important for me to avoid as it breaks my operation.  

Using windows exe . Anything to avoid this would be appreciated.  Thank you.

 yt-dlp --get-title https://player.vimeo.com/video/786646692 -vU

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['--get-title', 'https://player.vimeo.com/video/786646692', '-vU']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2023.01.06 [6becd25] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19044-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 2023-01-30-git-2d202985b7-full_build-www.gyan.dev (setts), ffprobe 2023-01-30-git-2d202985b7-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.16.0, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1760 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2023.01.06, Current version: 2023.01.06
yt-dlp is up to date (2023.01.06)
[vimeo] Extracting URL: https://player.vimeo.com/video/786646692
[vimeo] 786646692: Downloading webpage
ERROR: [vimeo] 786646692: Unable to extract info section; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 680, in extract
  File "yt_dlp\extractor\vimeo.py", line 837, in _real_extract
  File "yt_dlp\extractor\common.py", line 1228, in _search_regex
```

**Comment by bashonly** [comment]
In some player pages, the config object var is no longer followed by a `;`, so the extractor's regex isn't finding the "info section" JSON

A quick fix:
```diff
diff --git a/yt_dlp/extractor/vimeo.py b/yt_dlp/extractor/vimeo.py
index 97b99fc50..8422f93fc 100644
--- a/yt_dlp/extractor/vimeo.py
+++ b/yt_dlp/extractor/vimeo.py
@@ -834,8 +834,8 @@ def _real_extract(self, url):
             raise
 
         if '://player.vimeo.com/video/' in url:
-            config = self._parse_json(self._search_regex(
-                r'\b(?:playerC|c)onfig\s*=\s*({.+?})\s*;', webpage, 'info section'), video_id)
+            config = self._search_json(
+                r'\b(?:playerC|c)onfig\s*=', webpage, 'info section', video_id)
             if config.get('view') == 4:
                 config = self._verify_player_video_password(
                     redirect_url, video_id, headers)
```

**Comment by techfor** [comment]
Thanks, I'm running .exe on windows.  How can I implement your changes.  I'm not sure the steps to follow. thanks

**Comment by techfor** [comment]
> In some player pages, the config object var is no longer followed by a `;`, so the extractor's regex isn't finding the "info section" JSON
> 
> A quick fix:
> 
> ```diff
> diff --git a/yt_dlp/extractor/vimeo.py b/yt_dlp/extractor/vimeo.py
> index 97b99fc50..8422f93fc 100644
> --- a/yt_dlp/extractor/vimeo.py
> +++ b/yt_dlp/extractor/vimeo.py
> @@ -834,8 +834,8 @@ def _real_extract(self, url):
>              raise
>  
>          if '://player.vimeo.com/video/' in url:
> -            config = self._parse_json(self._search_regex(
> -                r'\b(?:playerC|c)onfig\s*=\s*({.+?})\s*;', webpage, 'info section'), video_id)
> +            config = self._search_json(
> +                r'\b(?:playerC|c)onfig\s*=', webpage, 'info section', video_id)
>              if config.get('view') == 4:
>                  config = self._verify_player_video_password(
>                      redirect_url, video_id, headers)
> ```

Thanks, I'm running .exe on windows. How can I implement your changes. I'm not sure the steps to follow to add the patch. thanks.  what do the red highlighted text mean.  do we delete that lines and replace with green lines?

**Comment by bashonly** [comment]
It's a patch for the source code. Can't be applied to the .exe

As a workaround for now, with this video you can use this URL: `yt-dlp "https://vimeo.com/786646692"`

That URL conversion won't work for every player URL though

**Comment by dirkf** [comment]
Somewhat unexpectedly, yt-dl (the master version fixed according to https://github.com/ytdl-org/youtube-dl/issues/31311) isn't seeing the same problem with OP's URL.

**Comment by bashonly** [comment]
> Somewhat unexpectedly, yt-dl (the master version fixed according to https://github.com/ytdl-org/youtube-dl/issues/31311) isn't seeing the same problem with OP's URL.

I get the same regex error with youtube-dl master. Perhaps it's a regional thing?

**Comment by techfor** [comment]
It happens sometimes,not all the time. Say out of 100 tries, it happens around 20% on the same url. I guess I will have to wait for next update as I don't know how to use without exe files.

**Comment by dirkf** [comment]
Yes, I reproduced it. The new JS is probably being deployed across the CDN servers. The new format has `, "fastly_skyfire":{"avc_url":...` after the braced JSON instead of `;`.

Note the work-around mentioned above.

**Comment by techfor** [comment]
> Yes, I reproduced it. The new JS is probably being deployed across the CDN servers. The new format has `, "fastly_skyfire":{"avc_url":...` after the braced JSON instead of `;`.
> 
> Note the work-around mentioned above.

Hi, what's the difference in the solution mentioned by 'bashonly' and your commit solution. Looking to see which one to use.  For reference 
1. bashonly code:
`config = self._search_json(
r'\b(?:playerC|c)onfig\s*=', webpage, 'info section', video_id)`

2. your commit code:
`config = self._parse_json(self._search_regex(
r'\b(?:playerC|c)onfig\s*=\s*({.+?})\s*[;,]', webpage, 'info section'), video_id)`

Thank you

**Comment by pukkandan** [comment]
They are almost the same. youtube-dl just doesn't have `_search_json`

**Comment by bashonly** [comment]
> `config = self._parse_json(self._search_regex( r'\b(?:playerC|c)onfig\s*=\s*({.+?})\s*[;,]', webpage, 'info section'), video_id)`

This actually doesn't work:
```
[vimeo] 786646692: Downloading webpage
[vimeo] Saving request to 786646692_https_-_player.vimeo.com_video_786646692.dump
ERROR: 786646692: Failed to parse JSON  (caused by JSONDecodeError("Expecting ',' delimiter: line 1 column 870 (char 869)")); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

and `, "fastly_skyfire":{"avc_url":...` is part of the JSON that should be parsed

**Comment by KnownBugg** [comment]
Applying the patch provided by bashonly worked perfectly.

**Comment by dirkf** [comment]
In yt-dl the right patch adds `(?s)` at the start of the pattern, thanks @bashonly, so the actual problem was line breaks in the JS. How the patch shown above worked under test is a mystery.

**Comment by zalevskiy777** [comment]
yt-dlp --list-formats https://player.vimeo.com/video/509558858
[vimeo] Extracting URL: https://player.vimeo.com/video/509558858
[vimeo] 509558858: Downloading webpage
ERROR: [vimeo] 509558858: Unable to extract info section; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

C:\FFmpeg>yt-dlp -U
Latest version: 2023.01.06, Current version: 2023.01.06
yt-dlp is up to date (2023.01.06)

**Comment by LeoniePhiline** [comment]
Applying the patch https://github.com/dirkf/youtube-dl/commit/9910418f00ea8231e5acf1eebe88f4e03517a1cc  to yt-dlp fails for me:

```
[vimeo] 742596735: 742596735: Failed to parse JSON (caused by JSONDecodeError('Extra data in \'35"}}\\n    var fullsc\': line 2 column 5 (char 11622)'));
```

Note that `var fullscreen...` is the next line after `playerConfig`:

![grafik](https://user-images.githubusercontent.com/22329650/218076416-6d52dee6-ba71-42c2-aa01-fa7f73b26c97.png)

The patched regex seems to match too far down the file.

**Comment by LeoniePhiline** [comment]
I see. Thanks for the clarification! 

I lack any knowledge regarding the differences between `youtube-dl` and `yt-dlp`. 

I even thought `youtube-dl` was entirely unmaintained for years already. Turns out I was wrong!

**Comment by EmmaWebGH** [comment]
Hi
Not sure if I am in the right place, I've been trying to find a way to download a private embedded vimeo video for over a week now, and looked at many gists that claimed to work. Nothing does. So far I can't get YT DLP to do it either. 
Until a few days ago I was using a chrome extension, that would somehow parse the page (yes, even for private clips), and return a piece of code (including a reference to FFMPEG) that I would then paste into the terminal, and the clip would download. But they paywalled it just recently.
I wanted to ask in discussions but discussions are locked.
Not 100% confident I can repeat the steps to submit an issue without "getting blocked".
Is there documentation or a guide on how to use YTDLP to get vimeo videos? So far all my searching reveals similar issues to the above, with 403 errors, json parsing problems or similar.
Many thanks

**Comment by EmmaWebGH** [comment]
I'm up to date as of today, but I still can't get YT-DLP to download the clip. Not sure why.
```
[generic] master: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] master: Extracting information
[info] master: Downloading 1 format(s): video-ee878ba9+audio-befe08dd
ERROR: unable to download video data: HTTP Error 403: Forbidden
```
Clip is private but watchable on the page I am on, I used to be able to get these via the Chome Extension from Vimeomate... it's just collecting all the pieces and using FFMPEG to re-assemble them, right? If something is playable in the browser, I should be able to do this? Not sure how the extension worked, injecting something or other... it would add buttons to the actual Vimeo Embed. So maybe the problem here is login? As I have to be logged into the site to view, but via terminal command yt-dlp, obviously the request is not coming from the right page. 

How to solve this?

**Comment by bashonly** [comment]
@EmmaWebGH Downloading the m3u8/mpd links directly will not work, if that's what you were trying (but it's hard to tell from such a minimal log).

Try downloading the webpage URL and passing `--cookies-from-browser chrome` to see if yt-dlp can extract the Vimeo embed.

If not, then view the page source and find the vimeo embed URL (it should be `https://player.vimeo.com/video/...`). Download the embedded player URL and add pass the original webpage URL as the argument to the `--referer` option

**Comment by EmmaWebGH** [comment]
@bashonly Thanks, these also didn't work.
I'm now trying on a page that does not require a login, it's publicly accessible, but the vimeo clip is restricted to embedding on that domain only. YT-DLP fails. I am sorry to post here, I feel like this should be happening in a discussion, but discussions are locked so I have no choice.

Page is https://www.behance.net/gallery/151753533/BMWi-Oasis
Embed is https://player.vimeo.com/video/728945341
So I tried
`yt-dlp https://player.vimeo.com/video/728945341 --cookies-from-browser chrome`
and
`yt-dlp https://player.vimeo.com/video/728945341 --referer https://www.behance.net/gallery/151753533/BMWi-Oasis`
and
`yt-dlp https://player.vimeo.com/video/728945341 --referer https://www.behance.net/gallery/151753533/BMWi-Oasis --cookies-from-browser chrome`
The above 3 combinations don't work.

Also, terminal says no such option: --referer. On the main page, it lists that as deprecated?
Since it's not logged it, not sure cookies would do anything. But it's domain restricted still, so referer maybe, if it worked?

I didn't file a new issue as there's already one #6229 that leads back to here. Is this one really closed?

**Comment by bashonly** [comment]
@EmmaWebGH 

> My terminal reports " Unable to extract info section;" so that's still a thing.

it's been fixed in the master branch, meaning it will be fixed in the next release. If you don't want to wait for the next release, you can use the [newest unofficial daily build](https://github.com/ytdl-patched/yt-dlp), or [install from master with PIP](https://github.com/yt-dlp/yt-dlp/wiki/Installation#with-pip)

> `yt-dlp https://player.vimeo.com/video/728945341 --referer https://www.behance.net/gallery/151753533/BMWi-Oasis`

^ this works for me on master

> terminal says no such option: --referer. On the main page, it lists that as deprecated?

It still works though, at least for me. Weird that it doesn't for you. Alternatively you can do this:

`yt-dlp "https://player.vimeo.com/video/728945341" --add-header "Referer:https://www.behance.net/gallery/151753533/BMWi-Oasis"`

> Are they just running yt-dlp and having the same issue as you guys?

Possibly yeah, or youtube-dl
