### ISSUE TITLE
Add support for Vocaroo

### ISSUE THREAD

**Issue by Soundtoxin** [yt-dlp/yt-dlp#6152]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2023.01.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

United States

### Example URLs

- browser-playable URL: https://vocaroo.com/1mpjXGhi3dob

### Provide a description that is worded well enough to be understood

Vocaroo is a site where you can record yourself and share the recording, or optionally just upload an audio file to be shared in the same way. Currently the site is not supported. You can neither download a recording with yt-dlp nor play back a recording in mpv with its URL at the moment. I would like support added.

There are also download URLs that might be worth trying to support, but they give a 403 forbidden in the browser, so I did not include one. You can get them by following the example URL above and copying the link from the download button on that page. (perhaps you could just take the ID at the end of the URL that's the same between them and treat it like the non-download URL so that it still works, but if the main URLs work this is a minor issue)

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://vocaroo.com/1mpjXGhi3dob']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2023.01.06 [6becd2508]
[debug] Lazy loading extractors is disabled
[debug] Python 3.9.9 (CPython x86_64 64bit) - Linux-6.0.8-gnu-x86_64-with-glibc2.33 (OpenSSL 1.1.1s  1 Nov 2022, glibc 2.33)
[debug] exe versions: ffmpeg 5.1.2 (setts), ffprobe 5.1.2
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, secretstorage-3.3.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1760 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2023.01.06, Current version: 2023.01.06
yt-dlp is up to date (2023.01.06)
[generic] Extracting URL: https://vocaroo.com/1mpjXGhi3dob
[generic] 1mpjXGhi3dob: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] 1mpjXGhi3dob: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://vocaroo.com/1mpjXGhi3dob
Traceback (most recent call last):
  File "/gnu/store/qdb6f4kqgbsav9mnp6f29v209yw0c27s-yt-dlp-2023.01.06/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1502, in wrapper
    return func(self, *args, **kwargs)
  File "/gnu/store/qdb6f4kqgbsav9mnp6f29v209yw0c27s-yt-dlp-2023.01.06/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1578, in __extract_info
    ie_result = ie.extract(url)
  File "/gnu/store/qdb6f4kqgbsav9mnp6f29v209yw0c27s-yt-dlp-2023.01.06/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 680, in extract
    ie_result = self._real_extract(url)
  File "/gnu/store/qdb6f4kqgbsav9mnp6f29v209yw0c27s-yt-dlp-2023.01.06/lib/python3.9/site-packages/yt_dlp/extractor/generic.py", line 2523, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://vocaroo.com/1mpjXGhi3dob
```

**Comment by user7230724** [comment]
The "download" button works for me on all Vocaroo URLs.
