### ISSUE TITLE
[Question] Error using yt-dlp with php

### ISSUE THREAD

**Issue by triplesixman** [yt-dlp/yt-dlp#616]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

I'm on Debian 9 and I used to use youtube-dl with php (simple "exec"), for a local script but when I replace it with yt-dlp I realize that it does not work.

In the error logs, yt-dlp tries to use python 2.7, but I installed python 3.9.6 with pyenv, and when I do "python -V", I get 3.9.6.

When I execute the script in command line "/usr/bin/php script.php" there no worries, it is when I execute the script with my browser that the error occurs.

I must be missing something, but after a lot of research I couldn't find what. Any idea ?

**Comment by pukkandan** [comment]
yt-dlp has a `/usr/bin/env python3` shebang. So as long as it is set correctly, exec should work. But I know nothing about php to provide further help

**Comment by Ashish0804** [comment]
Probably your browser is running as sudo or as a third user.
afaik since u installed using pyenv, it only affects your user and not the other.
Why not install latest python using apt?

**Comment by nyuszika7h** [comment]
You need to have your script run yt-dlp as `/home/yourusername/.pyenv/shims/python /path/to/yt-dlp`.

**Comment by triplesixman** [comment]
> You need to have your script run yt-dlp as `/home/yourusername/.pyenv/shims/python /path/to/yt-dlp`.

This time I encounter a "Permission denied". However, running the script from the terminal everything works. Namely, my "script.php" file is in www-data:www-data. I use nginx and php 7.2
[03-Aug-2021 13:42:12] WARNING: [pool www] child 13068 said into stderr: "sh: 1: /root/.pyenv/shims/python: Permission denied"



> Probably your browser is running as sudo or as a third user.
> afaik since u installed using pyenv, it only affects your user and not the other.
> Why not install latest python using apt?

Because I use applications that are not yet compatible with a newer python from what I understand.

**Comment by pukkandan** [comment]
Since this is not related directly to yt-dlp and none of the devs here seems to know how to fix this, I am closing the issue. You are probably better off asking this somewhere that provides help for PHP
