### ISSUE TITLE
Dacast.com

### ISSUE THREAD

**Issue by churongcon** [yt-dlp/yt-dlp#6163]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2023.01.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

USA

### Example URLs

Single Video: https://iframe.dacast.com/vod/acae82153ef4d7a7344ae4eaa86af534/1c6143e3-5a06-371d-8695-19b96ea49090

### Provide a description that is worded well enough to be understood

Vzaar.com now is Dacast.com

Please support Dacast.com

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'test:dacast']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2023.01.06 [6becd25] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-109725-g2d202985b7-20230130 (setts), ffprobe N-109725-g2d202985b7-20230130
[debug] Optional libraries: Cryptodome-3.16.0, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1760 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2023.01.06, Current version: 2023.01.06
yt-dlp is up to date (2023.01.06)
[TestURL] Extracting URL: test:dacast
ERROR: [TestURL] None: No extractors matching 'dacast' found
  File "yt_dlp\extractor\common.py", line 680, in extract
  File "yt_dlp\extractor\testurl.py", line 24, in _real_extract
```

**Comment by bashonly** [comment]
Does the site provide any other type of URL for videos besides the iframe URL (which is presumably provided for embedding)?

**Comment by churongcon** [comment]
> RL (which is presumably provided for embedding)?
@bashonly

I have registered Dacast.com and upload demo video
It's provide only iframe link like this
<img width="1010" alt="Screenshot 2023-02-08 at 13 51 16" src="https://user-images.githubusercontent.com/26823364/217455922-26543839-b6aa-45a5-8c11-aeff9afa456e.png">
`<script id="587b1232-c5db-1739-e317-7503c9818117-vod-b43ef58d-fba8-41d7-8d65-59ca9c40e5b6" width="100%" height="100%" src="https://player.dacast.com/js/player.js?contentId=587b1232-c5db-1739-e317-7503c9818117-vod-b43ef58d-fba8-41d7-8d65-59ca9c40e5b6" class="dacast-video"></script>`

`<div style="position:relative;padding-bottom:56.25%;overflow:hidden;height:0;max-width:100%;"><iframe id="b43ef58d-fba8-41d7-8d65-59ca9c40e5b6" src="https://iframe.dacast.com/vod/587b1232-c5db-1739-e317-7503c9818117/b43ef58d-fba8-41d7-8d65-59ca9c40e5b6" width="100%" height="100%" frameborder="0" scrolling="no" allow="autoplay;encrypted-media" allowfullscreen webkitallowfullscreen mozallowfullscreen oallowfullscreen msallowfullscreen style="position:absolute;top:0;left:0;"></iframe></div>`

`https://iframe.dacast.com/vod/587b1232-c5db-1739-e317-7503c9818117/b43ef58d-fba8-41d7-8d65-59ca9c40e5b6`

**Comment by churongcon** [comment]
Expos link: https://dacastexpo.com/?id=be1e4442-f31a-eb28-d156-243e963e7405
Playlist link: https://iframe.dacast.com/playlist/587b1232-c5db-1739-e317-7503c9818117/a43b34f8-cd41-9cb5-f5e9-b858c978e934

**Comment by eoprede** [comment]
So, you can download dacast video, but you need to find the m3u8 link. I was not able to figure out how to get it from the embedded page, but if you open the page in your browser, then open developer tools and look at the network traffic - you'll see the browser making request to the file chunklist_somerandomstring.m3u8 i.e. (not a real link, just an example) https://dacastmmd.mmdlive.lldns.net/dacastmmd/480b7e1924834a99912ba0a51a09056a/chunklist_b2592000.m3u8
I believe if you are the creator of the video, you can also get the link to m3u8, but I don't know how to get it if you are just a viewer.
Then you can use ffmpeg external downloader and it will work fine.

**Comment by memmam** [comment]
The m3u8 link can be extracted easily with F12. The problem is that sometimes, on some videos, you may need to use something like Fiddler to get an encryption key. Once you have those two things, hlsdl works since it can take the encryption key as input and decrypt the video as it comes in from the playlist.

Can yt-dlp be extended to automate this entire process? It already is able to extract the video location from e.g. a YouTube or Twitter link, so I assume it's already doing a web request of some sort.

**Comment by bashonly** [comment]
>  The problem is that sometimes, on some videos, you may need to use something like Fiddler to get an encryption key

Are you able to share an example URL?

**Comment by memmam** [comment]
I mean, I COULD, but the only one I'm aware of is part one of a paid video series by Alex Jones, and I kinda don't wanna get sued.

Also, for all future onlookers, I am not an Alex Jones supporter by any means. I bought it for someone who has an academic interest in right-wing quasi-religious propaganda.

**Comment by bashonly** [comment]
discord: bashonly#4457
matrix: @bashonly:matrix.org
email: bashonly ( a t ) protonmail ( d o t ) com

**Comment by memmam** [comment]
Says I can't add you on either Discord or Matrix, Discord says you have friend requests closed.

**Comment by bashonly** [comment]
fixed, you can try again
