### ISSUE TITLE
Download photos from Instagram and other sites

### ISSUE THREAD

**Issue by Qaz-7** [yt-dlp/yt-dlp#6168]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.01.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Option to download photos from Instagram and other sites.I know this is a video and audio downloader project, but it can be added as an additional feature

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[Instagram] Extracting URL: https://www.instagram.com/p/CoS6wTEO9Rv/?igshid=NjcyZGVjMzk=
[Instagram] CoS6wTEO9Rv: Setting up session
[Instagram] CoS6wTEO9Rv: Downloading JSON metadata
[download] Downloading playlist: Post by feeh_hanzen
[Instagram] Playlist Post by feeh_hanzen: Downloading 0 items of 0
[download] Finished downloading playlist: Post by feeh_hanzen
```

**Comment by bashonly** [comment]
> this is a video and audio downloader project

As you noted, this is out-of-scope. Would be a good plugins project, though. Or if you want a recommendation for a good (unrelated) project that can do this right now, there is [gallery-dl](https://github.com/mikf/gallery-dl)
