### ISSUE TITLE
[Broken] nbcolympics stream

### ISSUE THREAD

**Issue by kyjb70** [yt-dlp/yt-dlp#617]
## Checklist

- [ X] I'm reporting a broken site support
- [ X] I've verified that I'm running yt-dlp version **2021.08.02**
- [ X] I've checked that all provided URLs are alive and playable in a browser
- [ X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ X] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] Command-line config: ['--verbose', '--ap-mso', 'slingtv', '--ap-username', 'PRIVATE', '--ap-password', 'PRIVATE', 'https://stream.nbcolympics.com/track-and-field-session-7-integrated-feed'
]
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] yt-dlp version 2021.08.02 (zip)
[debug] Python version 3.9.5 (CPython 64bit) - Linux-5.11.0-1014-gcp-x86_64-with-glibc2.33
[debug] exe versions: ffmpeg 4.3.2-0, ffprobe 4.3.2-0
[debug] Proxy map: {}
[debug] [nbcolympics:stream] Extracting URL: https://stream.nbcolympics.com/track-and-field-session-7-integrated-feed
[nbcolympics:stream] track-and-field-session-7-integrated-feed: Downloading webpage
ERROR: Unable to extract resource; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to upda
te. Be sure to call yt-dlp with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1179, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1204, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 572, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/nbc.py", line 523, in _real_extract
    resource = self._search_regex(
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 1126, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
yt_dlp.utils.RegexNotFoundError: Unable to extract resource; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-
dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.

```

## Description

I'm attempting to download VOD of the olympics from NBC using SlingTV and I am getting this error. 
I used the web url as well as trying to find m3u8 links in the dev menu, both resulted in a failure
I was told on discord to tag @wesnm
TY

**Comment by pukkandan** [comment]
Possibly related? https://github.com/ytdl-org/youtube-dl/pull/29688

**Comment by wesnm** [comment]
I don't have another MSO account to confirm this with, but I'm nearly 100% certain it's because the 2020 Olympics uses a different scheme now compared to 2018, and will require the extractor to be modified.

**Comment by wesnm** [comment]
> Related: [ytdl-org/youtube-dl#29665](https://github.com/ytdl-org/youtube-dl/issues/29665), [ytdl-org/youtube-dl#29688](https://github.com/ytdl-org/youtube-dl/pull/29688)

Yeah, it looks like that PR author has done some of the work to fix the extractor.

**Comment by nchilada** [comment]
Hi, I was just leaving a comment on ytdl-org/youtube-dl#29665! I think my youtube-dl PR is functional though maybe not yet ready to merge. I'm not sure how this project differs from that one but it looks like any merge on that end would eventually show up here?

**Comment by pukkandan** [comment]
@nchilada Yes, if your PR gets merged upstream, it will make its way here too. If possible, I would like to get it merged without waiting for if/when upstream merges it. I sometimes just take the PR and merge it myself. But since I cannot test this, you or someone else will have to make a PR here and work with me to get this merged

**Comment by kyjb70** [comment]
Want my account?

**Comment by pukkandan** [comment]
You can DM me on discord, but since I'm from India, I don't know whether it is actually accessible to me

**Comment by fosam** [comment]
You don't need any account to replicate this, just vpn your way to the us and try.

```
C:\Users\123>yt-dlp --verbose https://www.nbcolympics.com/videos/karsten-warholm-demolishes-400m-hurdles-wr-4594-gold
[debug] User config file: C:\Users\123\AppData\Roaming\yt-dlp\config.txt
[debug] User config: ['--output', 'C:\\Users\\123\\Desktop\\%(title)s-%(id)s.%(ext)s']
[debug] Command-line config: ['--verbose', 'https://www.nbcolympics.com/videos/karsten-warholm-demolishes-400m-hurdles-wr-4594-gold']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] yt-dlp version 2021.08.02 (exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg 2021-08-01-git-1f58503013, ffprobe 2021-08-01-git-1f58503013
[debug] Proxy map: {}
[debug] [generic] Extracting URL: https://www.nbcolympics.com/videos/karsten-warholm-demolishes-400m-hurdles-wr-4594-gold
[generic] karsten-warholm-demolishes-400m-hurdles-wr-4594-gold: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] karsten-warholm-demolishes-400m-hurdles-wr-4594-gold: Downloading webpage
[generic] karsten-warholm-demolishes-400m-hurdles-wr-4594-gold: Extracting information
ERROR: Unsupported URL: https://www.nbcolympics.com/videos/karsten-warholm-demolishes-400m-hurdles-wr-4594-gold
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1179, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1204, in __extract_info
  File "yt_dlp\extractor\common.py", line 572, in extract
  File "yt_dlp\extractor\generic.py", line 3713, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.nbcolympics.com/videos/karsten-warholm-demolishes-400m-hurdles-wr-4594-gold
```

**Comment by pukkandan** [comment]
@fosam Your log seems to be sowing a different problem than the one this issue is adressing

**Comment by fosam** [comment]
I tried the OP's link and i got the same error, with my link i got unsupported URL which is strange? because both of the sites are officially supported:

![Capture 03_08_2021_16_15_16](https://user-images.githubusercontent.com/52612348/128030975-5b87f98e-e644-443e-8b97-0d2f8f6db225.png)

**Comment by wesnm** [comment]
The _nbcolympics:stream_ extractor is currently not working, although @nchilada has a fix. This is slightly different, though: the URL doesn't match the _nbcolympics_ extractor `_VALID_URL` regex. The file format has changed as well, so the extractor won't work even if the regex is updated.

**Comment by pukkandan** [comment]
@wesnm
> One thing the "live" status does is determine if youtube-dl will delegate to alternate downloaders. If an event is flagged as live, it will only download using ffmpeg with a single worker, which is much much slower.

I think you are confusing yt-dlp features with youtube-dl. There are no multithreaded downloads in ytdl

**Comment by wesnm** [comment]
Well, I meant that the other downloaders (e.g. aria2c) themselves may have multiple workers.

**Comment by wesnm** [comment]
> @wesnm
> 
> > One thing the "live" status does is determine if youtube-dl will delegate to alternate downloaders. If an event is flagged as live, it will only download using ffmpeg with a single worker, which is much much slower.
> 
> I think you are confusing yt-dlp features with youtube-dl. There are no multithreaded downloads in ytdl

Well, I mean that the alternate downloaders (e.g. aria2c) themselves may have multiple workers.

**Comment by pukkandan** [comment]
Downloading fragmented videos with aria2c is also a yt-dlp only feature :D

**Comment by wesnm** [comment]
Alright, I keep getting my wires crossed somehow...!
