### ISSUE TITLE
[Gamespot] does not work anymore for some videos (missing videoStreams)

### ISSUE THREAD

**Issue by cataldor** [yt-dlp/yt-dlp#6179]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2023.01.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

France

### Provide a description that is worded well enough to be understood

I think gamespot has changed the video stream a bit;
the key `videoStreams` seems to not be available anymore (in some videos at least);

there is a newer one called `mrss_video_url` that seems to be the same (not sure), but it is embedded in another file referenced in `data-jw-media-id` (i.e., with the latter field, you can access a json file that contains the `mrss_video_url` key)

I am not familiar with yt-dlp APIs, that is why i did not open an MR (help is appreciated)

sample of videos without `videoStreams`:
https://www.gamespot.com/videos/16-best-zelda-breath-of-the-wild-glitches-of-2021/2300-6457045/

https://www.gamespot.com/videos/apex-legends-revelry-launch-trailer/2300-6460555/

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.gamespot.com/videos/16-best-zelda-breath-of-the-wild-glitches-of-2021/2300-6457045/']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2023.01.06 [6becd25] (zip)
[debug] Python 3.11.1 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1q  5 Jul 2022)
[debug] exe versions: ffmpeg 5.1.2-full_build-www.gyan.dev (setts), ffprobe 5.1.2-full_build-www.gyan.dev
[debug] Optional libraries: sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Loaded 1760 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2023.01.06, Current version: 2023.01.06
yt-dlp is up to date (2023.01.06)
[GameSpot] Extracting URL: https://www.gamespot.com/videos/16-best-zelda-breath-of-the-wild-glitches-of-2021/2300-6457045/
[GameSpot] 6457045: Downloading webpage
ERROR: 6457045: An extractor error has occurred. (caused by KeyError('videoStreams')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
File "E:\GitHub\xl\yt-dlp\yt_dlp\extractor\common.py", line 680, in extract
ie_result = self._real_extract(url)
            ^^^^^^^^^^^^^^^^^^^^^^^
File "E:\GitHub\xl\yt-dlp\yt_dlp\extractor\gamespot.py", line 44, in _real_extract
streams = data_video['videoStreams']
          ~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: 'videoStreams'
```

**Comment by bashonly** [comment]
As noted by OP, there is a `data-jw-media-id` attribute in an HTML `<div>` tag that is a JWPlatform video ID. There is also a `dai.google.com` m3u8 manifest URL in the `data-video` attribute's JSON, although this format may have ads, so JWPlatform embed extraction is probably preferable if possible. Older links should still be supported, as the 2nd test case in the Gamespot extractor still works with the current code.

**Comment by october262** [comment]
try again with yt-dlp --force-generic-extractor "https://www.gamespot.com/videos/16-best-zelda-breath-of-the-wild-glitches-of-2021/2300-6457045/"
the video will now download.

**Comment by cataldor** [comment]
Wow that is an interesting workaround! thank you

There is a JWPlatform parser in generic, probably that makes it work

**Comment by cataldor** [comment]
Good news, the `videoStreams` keys are back (including the videos that i posted)

I will be closing the issue
