### ISSUE TITLE
AdultSwim - Can't Download Episodes Without A 'space' In The Episode Name Or A '-' In The URL

### ISSUE THREAD

**Issue by RedFox134** [yt-dlp/yt-dlp#6184]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2023.01.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

US

### Provide a description that is worded well enough to be understood

I'm trying to download episodes of FLCL from [https://adultswim.com](https://adultswim.com) using the following URL EX: "[https://www.adultswim.com/videos/flcl/re-start](https://www.adultswim.com/videos/flcl/re-start)".  This works fine if the episode has a space in the name or a "-" in the url, but for episodes that do not have a space in the name such as EP 6 FLCLIMAX the url shows as "[https://www.adultswim.com/videos/flcl/flclimax](https://www.adultswim.com/videos/flcl/flclimax)" and fails to download.  I get the error message "ERROR: 'NoneType' object is not subscriptable'.

I'm executing the command using Powershell in the form of 
`PS P:\yt-dlp> .\yt-dlp.exe -vU https://www.adultswim.com/videos/flcl/flclimax`
This works fine for episodes with a space in the name and "-" in the url, but not for episodes without the space in the title or "-" in the url.

I tried searching for similar issues and it seems some work has been done in the past to correct this, but I couldn't make the connection to this current issue for how to resolve it.  I'm not the most familiar with python or web video streams so I very well could have missed something obvious.  If this is an easy fix (user error) I'm submitting to document the fix to try to help prevent future similar questions/issues from coming up.  Please let me know if more information is needed and I'll try my best to provide it!

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
PS P:\yt-dlp> .\yt-dlp.exe -vU https://www.adultswim.com/videos/flcl/flclimax
[debug] Command-line config: ['-vU', 'https://www.adultswim.com/videos/flcl/flclimax']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2023.01.06 [6becd25] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.16.0, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1760 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2023.01.06, Current version: 2023.01.06
yt-dlp is up to date (2023.01.06)
[AdultSwim] Extracting URL: https://www.adultswim.com/videos/flcl/flclimax
[AdultSwim] flclimax: Downloading JSON metadata
ERROR: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1502, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1578, in __extract_info
  File "yt_dlp\extractor\common.py", line 680, in extract
  File "yt_dlp\extractor\adultswim.py", line 128, in _real_extract
TypeError: 'NoneType' object is not subscriptable
```

**Comment by bashonly** [comment]
https://www.adultswim.com/videos/flcl/flclimax gives 404 in browser

**Comment by RedFox134** [comment]
Thank you!  I feel like an idiot now haha.  Sorry to waste those time for such an easy resolution!
