### ISSUE TITLE
𝙡𝙞𝙫𝙚𝙨𝙩𝙧𝙚𝙖𝙢 𝙢𝙥𝙙

### ISSUE THREAD

**Issue by 10362227** [yt-dlp/yt-dlp#619]
yt-dlp --allow-unplayable-formats "https://live.EXAMPLE.com/DRMprotected****/live.isml/.mpd"

Only Downloads Segments Available And Then Quits. Youtube-dl/Streamlink doesn't support DRM DL, please!

**Comment by MinePlayersPE** [comment]
Related (upstream issue): https://github.com/ytdl-org/youtube-dl/issues/10787

**Comment by Ashish0804** [comment]
IGNORING THE ISSUE TEMPLATE WILL RESULT IN ISSUE CLOSED AS INCOMPLETE
Create a new issue using the correct template with all necessary information including the `--verbose` output

**Comment by fstirlitz** [comment]
Also, please don’t abuse Unicode characters in issue titles.
