### ISSUE TITLE
[AdultSwim] Ignoring subtitle tracks found in the HLS manifest

### ISSUE THREAD

**Issue by dilliboy** [yt-dlp/yt-dlp#6191]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2023.01.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United States

### Provide a description that is worded well enough to be understood

Trying to grab the closed captions on the adult swim page. Posting here as per instructions.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.adultswim.com/videos/perfect-hair-forever/return-to-balding-victory']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2023.01.06 [6becd25] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22621-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-91217-g2bd24d4a37, ffprobe N-91217-g2bd24d4a37
[debug] Optional libraries: Cryptodome-3.16.0, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1760 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2023.01.06, Current version: 2023.01.06
yt-dlp is up to date (2023.01.06)
[AdultSwim] Extracting URL: https://www.adultswim.com/videos/perfect-hair-forever/return-to-balding-victory
[AdultSwim] return-to-balding-victory: Downloading JSON metadata
[AdultSwim] 0af6482e2443f47d0112ab0ad7d7830e7b905f7c: Downloading JSON metadata
[AdultSwim] 0af6482e2443f47d0112ab0ad7d7830e7b905f7c: Downloading XML
[AdultSwim] 0af6482e2443f47d0112ab0ad7d7830e7b905f7c: Downloading m3u8 information
[AdultSwim] 3nAzdvT3SHGEybjpeeaW1g: Downloading JSON metadata
[AdultSwim] 3nAzdvT3SHGEybjpeeaW1g: Downloading m3u8 information
WARNING: [AdultSwim] Ignoring subtitle tracks found in the HLS manifest; if any subtitle tracks are missing, please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 3nAzdvT3SHGEybjpeeaW1g: Downloading 1 format(s): hls-5130
[debug] Invoking hlsnative downloader on "https://tve-vod-lln.warnermediacdn.com/adultswim/b8297663496f0e292bdc52292ae70dcd/layer7/layer7_bk.m3u8"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 116
[download] Destination: Perfect Hair Forever - Return to Balding Victory [3nAzdvT3SHGEybjpeeaW1g].mp4
[debug] File locking is not supported. Proceeding without locking
[download] 100% of  423.93MiB in 00:06:40 at 1.06MiB/s
[debug] ffprobe command line: ffprobe -hide_banner -show_format -show_streams -print_format json "file:Perfect Hair Forever - Return to Balding Victory [3nAzdvT3SHGEybjpeeaW1g].mp4"
[FixupM3u8] Fixing MPEG-TS in MP4 container of "Perfect Hair Forever - Return to Balding Victory [3nAzdvT3SHGEybjpeeaW1g].mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:Perfect Hair Forever - Return to Balding Victory [3nAzdvT3SHGEybjpeeaW1g].mp4" -map 0 -dn -ignore_unknown -c copy -f mp4 "-bsf:a" aac_adtstoasc -movflags "+faststart" "file:Perfect Hair Forever - Return to Balding Victory [3nAzdvT3SHGEybjpeeaW1g].temp.mp4"
```

**Comment by pukkandan** [comment]
For devs:
https://github.com/yt-dlp/yt-dlp/blob/c588440d68d5bdeb6bb5b2896824551b13e7bd18/yt_dlp/extractor/adultswim.py#L172-L174

just needs to be be changed like https://github.com/yt-dlp/yt-dlp/blob/c588440d68d5bdeb6bb5b2896824551b13e7bd18/yt_dlp/extractor/acfun.py#L18-L20
