### ISSUE TITLE
get upload_date of all chanel videos with yt_dlp and python

### ISSUE THREAD

**Issue by metalalchemist** [yt-dlp/yt-dlp#6192]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.01.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

how can get all upload_dates of all videos in a specific chanel?
here is my code

import json
import yt_dlp as youtube_dl
options = {'ignoreerrors': True,'quiet': True,'extract_flat': 'in_playlist','dump_single_json': True, 'getcomments': True,"outtmpl": "%(upload_date)s"}
def getData(url):
	with youtube_dl.YoutubeDL(options) as ydl: return ydl.extract_info(url, download= False)
dictio= getData('https://www.youtube.com/@4everZyanya')

in dictio i don't found the key upload_date

anyone can helpme please? thanx my english is so bad

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
Remove extract_flat or see https://www.github.com/yt-dlp/yt-dlp#youtubetab

**Comment by metalalchemist** [comment]
i removed it but...


WARNING: [youtube] a5_fc5CVzL4: nsig extraction failed: You may experience throttling for some formats
         Install PhantomJS to workaround the issue. Please download it from https://phantomjs.org/download.html
         n = jNgaS3PS8HODvQ ; player = https://www.youtube.com/s/player/97ea7458/player_ias.vflset/en_US/base.js

what can i do?

**Comment by dirkf** [comment]
Update your yt-dlp, or show the version installed.

**Comment by metalalchemist** [comment]
i reinstalled yt_dlp and this is the version.


Successfully installed yt_dlp-2023.1.6


i tried run my code withouth extract_flat and gets the same error



WARNING: [youtube] a5_fc5CVzL4: nsig extraction failed: You may experience throttling for some formats
Install PhantomJS to workaround the issue. Please download it from https://phantomjs.org/download.html
n = jNgaS3PS8HODvQ ; player = https://www.youtube.com/s/player/97ea7458/player_ias.vflset/en_US/base.js

**Comment by pukkandan** [comment]
https://github.com/yt-dlp/yt-dlp/issues/6131#issuecomment-1424881166
