### ISSUE TITLE
How do download Audio Description along side other audio track?

### ISSUE THREAD

**Issue by VampiricAlien** [yt-dlp/yt-dlp#6194]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.01.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I have had no luck finding the answer, How do I go about downloading both audio tracks (best or default with AD) without selecting hls ID?  I've tried using --audio-multistreams and this gave me Audio Description audio only. What I am after is two audio tracks if available, one them being AD (Audio Description).

<pre><font color="#C4A000">ID</font>                                        <font color="#C4A000">EXT</font> <font color="#C4A000">RESOLUTION</font> <font color="#3465A4">│</font> <font color="#C4A000">  TBR</font> <font color="#C4A000">PROTO</font> <font color="#3465A4">│</font> <font color="#C4A000">VCODEC</font>      <font color="#C4A000">  VBR</font> <font color="#C4A000">ACODEC</font>     <font color="#C4A000">MORE INFO</font>
<font color="#3465A4">───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────</font>
<font color="#4E9A06">hls-audio_aac-English</font>                     mp4 audio only <font color="#3465A4">│</font>       m3u8  <font color="#3465A4">│</font> <font color="#88807C">audio only</font>        unknown    [en] English
<font color="#4E9A06">hls-audio_aac-English__Audio_Description_</font> mp4 audio only <font color="#3465A4">│</font>       m3u8  <font color="#3465A4">│</font> <font color="#88807C">audio only</font>        unknown    [eng] English (Audio Description)
<font color="#4E9A06">hls-326</font>                                   mp4 320x180    <font color="#3465A4">│</font>  327k m3u8  <font color="#3465A4">│</font> avc1.4D401E  327k <font color="#88807C">video only</font>
<font color="#4E9A06">hls-565</font>                                   mp4 512x288    <font color="#3465A4">│</font>  565k m3u8  <font color="#3465A4">│</font> avc1.4D401E  565k <font color="#88807C">video only</font>
<font color="#4E9A06">hls-683</font>                                   mp4 640x360    <font color="#3465A4">│</font>  683k m3u8  <font color="#3465A4">│</font> avc1.4D401E  683k <font color="#88807C">video only</font>
<font color="#4E9A06">hls-1021</font>                                  mp4 800x450    <font color="#3465A4">│</font> 1021k m3u8  <font color="#3465A4">│</font> avc1.640028 1021k <font color="#88807C">video only</font>
<font color="#4E9A06">hls-1462</font>                                  mp4 1024x576   <font color="#3465A4">│</font> 1463k m3u8  <font color="#3465A4">│</font> avc1.640028 1463k <font color="#88807C">video only</font>
<font color="#4E9A06">hls-2298</font>                                  mp4 1280x720   <font color="#3465A4">│</font> 2299k m3u8  <font color="#3465A4">│</font> avc1.640028 2299k <font color="#88807C">video only</font>
<font color="#4E9A06">hls-2602</font>                                  mp4 1280x720   <font color="#3465A4">│</font> 2603k m3u8  <font color="#3465A4">│</font> avc1.640028 2603k <font color="#88807C">video only</font>
</pre>

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
`-f all[vcodec=none]`?

**Comment by pukkandan** [comment]
> Is it possible to have an AD option in audio options?

I don't understand. Pls elaborate

**Comment by pukkandan** [comment]
Just use `-f`. Why does it need new option? Something like `-f ba[format_note*=description]` should work

PS: Normally, the `language` field has some indication that it's AD, but not in the video you posted. But since no URL was given, no idea if that can be fixed. Consider opening a "site feature" request with complete verbose log

**Comment by october262** [comment]
try with yt-dlp -f all "https://www.pbs.org/video/ken-burns-country-music-episode-1-the-rub/"
