### ISSUE TITLE
I wanna download twitch sub vods can you add that feature that would be SICK ♥

### ISSUE THREAD

**Issue by arshanarchi** [yt-dlp/yt-dlp#6195]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a site-specific feature
- [X] I've verified that I'm running yt-dlp version **2023.01.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

India

### Example URLs

URL: https://www.twitch.tv/videos/1716619459
		
		

### Provide a description that is worded well enough to be understood

URL: https://www.twitch.tv/videos/1716619459
		
ERROR: [twitch:vod] 1716619459: Failed to download m3u8 information: HTTP Error 403: Forbidden (caused by ); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

		

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
URL: https://www.twitch.tv/videos/1716619459
		
		ERROR: [twitch:vod] 1716619459: Failed to download m3u8 information: HTTP Error 403: Forbidden (caused by ); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

**Comment by pukkandan** [comment]
yt-dlp does not bypass access requirements. If you have access, pass cookies. And, read what you are ticking
