### ISSUE TITLE
Unable to use `--cookies-from-browser` for Flatpak applications

### ISSUE THREAD

**Issue by rambalachandran** [yt-dlp/yt-dlp#6199]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2023.01.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

How to pass the cookies from browser (`--cookies-from-browser`), if the browser (in this case Chrome) is installed through Flatpak.

I have installed chrome through flatpak that saves the config in `~/.var/app/com.google.Chrome`. When I try to run the command
```
yt-dlp --cookies-from-browser chrome "URL"
```
it throws the error  `'/home/<user>/.config/local': No such file or directory`

As a shortcut, I have symlinked the config folder and it works, but it might be useful to have a clean implementation, given flatpak is increasingly becoming a favored choice for most GUI applications in Linux.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--cookies-from-browser', 'chrome', 'https://www.youtube.com/watch?v=jRBksDVs4tg']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2023.01.06 [6becd25] (zip)
[debug] Python 3.10.6 (CPython x86_64 64bit) - Linux-5.15.0-58-generic-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2
[debug] Optional libraries: certifi-2020.06.20, secretstorage-3.3.1, sqlite3-2.6.0
[Cookies] Extracting cookies from chrome
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/local/bin/yt-dlp/__main__.py", line 17, in <module>
  File "/usr/local/bin/yt-dlp/yt_dlp/__init__.py", line 970, in main
  File "/usr/local/bin/yt-dlp/yt_dlp/__init__.py", line 930, in _real_main
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 649, in __init__
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3814, in print_debug_header
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3858, in _setup_opener
  File "/usr/local/bin/yt-dlp/yt_dlp/cookies.py", line 99, in load_cookies
  File "/usr/local/bin/yt-dlp/yt_dlp/cookies.py", line 120, in extract_cookies_from_browser
  File "/usr/local/bin/yt-dlp/yt_dlp/cookies.py", line 281, in _extract_chrome_cookies
FileNotFoundError: could not find chrome cookies database in "/home/ram/.config/google-chrome"
```

**Comment by pukkandan** [comment]
Pass the profile path like `--cookies-from-browser chrome:~/.var/app/com.google.Chrome/Default`

**Comment by rambalachandran** [comment]
Thank you. That's very helpful

**Comment by rambalachandran** [comment]
I have created a pull request to update the wiki in yt-dlp/yt-dlp-wiki#13 to include this information.
