### ISSUE TITLE
[South Park] Episode downloads don't work

### ISSUE THREAD

**Issue by Scrooge200FES** [yt-dlp/yt-dlp#6200]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2023.01.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United States

### Provide a description that is worded well enough to be understood

I can't download any South Park episodes; nothing downloads and no segments are detected. Before this, it would download each part of the episode, and I would concatenate them together. I realize this might be a problem with MTVServicesInfoExtractor. The URL I used: https://southpark.cc.com/episodes/2dhgcd/south-park-cupid-ye-season-26-ep-1.

Related issue: [https://github.com/yt-dlp/yt-dlp/issues/6156](https://github.com/yt-dlp/yt-dlp/issues/6156). Since I'm getting a different error between the sites, I split the issues separately.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
C:\[...]>yt-dlp -vU https://southpark.cc.com/episodes/2dhgcd/south-park-cupid-ye-season-26-ep-1
[debug] Command-line config: ['-vU', 'https://southpark.cc.com/episodes/2dhgcd/south-park-cupid-ye-season-26-ep-1']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2023.01.06 [6becd25] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 2022-05-12-git-30e2bb0f64-full_build-www.gyan.dev (setts), ffprobe 2022-05-12-git-30e2bb0f64-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.16.0, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1760 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2023.01.06, Current version: 2023.01.06
yt-dlp is up to date (2023.01.06)
[southpark.cc.com] Extracting URL: https://southpark.cc.com/episodes/2dhgcd/south-park-cupid-ye-season-26-ep-1
[southpark.cc.com] south-park-cupid-ye-season-26-ep-1: Downloading webpage
[southpark.cc.com] 94ad0b35-9036-11ed-ad8e-0e40cf2fc285: Downloading info
[download] Downloading playlist: Cupid Ye
[southpark.cc.com] Playlist Cupid Ye: Downloading 0 items of 0
[download] Finished downloading playlist: Cupid Ye
```

**Comment by ParadoxGBB** [comment]
Looks like dupe: https://github.com/yt-dlp/yt-dlp/issues/2621
