### ISSUE TITLE
don't want to download format data in a json

### ISSUE THREAD

**Issue by metalalchemist** [yt-dlp/yt-dlp#6207]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.01.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

hello it's posible download specific keys in a youtube video with yt_dlp in python?
for example upload_date, comment_count likes, views, ETC?
i don't need formats keys
i know that i can delete it but i thing that the requests will be faster
so, there's any way to do it?
sorry my english is so bad.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
No. Some options in https://github.com/yt-dlp/yt-dlp#extractor-arguments may reduce the number of requests, but there is no way to tell yt-dlp to extract only specific data

**Comment by metalalchemist** [comment]
thanx for ask my question
