### ISSUE TITLE
Blacklist domain names from being used

### ISSUE THREAD

**Issue by lifebarier** [yt-dlp/yt-dlp#6212]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.01.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

On some youtube videos I get :
[download] Got error: <urlopen error [Errno -2] Name or service not known>

This seems to happen because of failing (seems to be lithuania problem only, already asked isp that seems to own ip that this domain name leads to)
https://rr1---sn-hxb5oxu-30oe.googlevideo.com

Youtube player takes a while to fallback to working domain name too. But youtube side was solved by firewall blacklisting that domain so youtube falls back to working one instantly.

Is there a way to tell yt-dlp to not use that domain name?

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Invoking http downloader on "https://rr1---sn-hxb5oxu-30oe.googlevideo.com/videoplayback?expi.........."
[download] Got error: <urlopen error [Errno -2] Name or service not known>. Retrying (1/10)...
[download] Got error: <urlopen error [Errno -2] Name or service not known>. Retrying (2/10)...
[download] Got error: <urlopen error [Errno -2] Name or service not known>. Retrying (3/10)...
```

**Comment by october262** [comment]
are you by chance using any ad blockers ?? - https://github.com/yt-dlp/yt-dlp/issues/1941

**Comment by pukkandan** [comment]
Not possible, see https://github.com/yt-dlp/yt-dlp/issues/1986

**Comment by lifebarier** [comment]
> are you by chance using any ad blockers ?? - #1941

Not using pihole. Using opnsense firewall, but:

1. disabling it leads to same issues
2. On different internet provider in other city I am having same issue
3. Know other people with different setups experiencing same youtube video laod problems (presuming they would experience same problem when usind yt-dlp)

**Comment by lifebarier** [comment]
> Not possible, see #1986



> Not possible, see #1986

thanks, will keep an eye on that one.
