### ISSUE TITLE
[tiktok] convert slideshows to video

### ISSUE THREAD

**Issue by her34** [yt-dlp/yt-dlp#6217]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a site-specific feature
- [X] I've verified that I'm running yt-dlp version **2023.01.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Example URLs

https://www.tiktok.com/@t4beatles/video/7164505486715260203

### Provide a description that is worded well enough to be understood

please add option to convert tiktok slideshows to a video

example code:

https://tiktokpy.readthedocs.io/en/latest/users/usage.html

```
async def save_slideshow(video: Video):
    # this filter makes sure the images are padded to all the same size
    vf = "\"scale=iw*min(1080/iw\,1920/ih):ih*min(1080/iw\,1920/ih)," \
         "pad=1080:1920:(1080-iw)/2:(1920-ih)/2," \
         "format=yuv420p\""

    for i, image_data in enumerate(video.image_post.images):
        url = image_data.image_url.url_list[-1]
        # this step could probably be done with asyncio, but I didn't want to figure out how
        urllib.request.urlretrieve(url, path.join(directory, f"temp_{video.id}_{i:02}.jpg"))

    urllib.request.urlretrieve(video.music.play_url, path.join(directory, f"temp_{video.id}.mp3"))

    # use ffmpeg to join the images and audio
    command = [
        "ffmpeg",
        "-r 2/5",
        f"-i {directory}/temp_{video.id}_%02d.jpg",
        f"-i {directory}/temp_{video.id}.mp3",
        "-r 30",
        f"-vf {vf}",
        "-acodec copy",
        f"-t {len(video.image_post.images) * 2.5}",
        f"{directory}/temp_{video.id}.mp4",
        "-y"
    ]
    ffmpeg_proc = await asyncio.create_subprocess_shell(
        " ".join(command),
        stdout=asyncio.subprocess.PIPE,
        stderr=asyncio.subprocess.PIPE,
    )
    _, stderr = await ffmpeg_proc.communicate()
    generated_files = glob.glob(path.join(directory, f"temp_{video.id}*"))

    if not path.exists(path.join(directory, f"temp_{video.id}.mp4")):
        # optional ffmpeg logging step
        # logging.error(stderr.decode("utf-8"))
        for file in generated_files:
            os.remove(file)
        raise Exception("Something went wrong with piecing the slideshow together")

    with open(path.join(directory, f"temp_{video.id}.mp4"), "rb") as f:
        ret = io.BytesIO(f.read())

    for file in generated_files:
        os.remove(file)

    return ret
```

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['--verbose', '--print-traffic', '--write-pages', 'https://www.tiktok.com/@t4beatles/video/7164505486715260203']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2023.01.06 [6becd25] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.18362-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.16.0, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1760 extractors
[TikTok] Extracting URL: https://www.tiktok.com/@t4beatles/video/7164505486715260203
[TikTok] 7164505486715260203: Downloading video feed
```

**Comment by pukkandan** [comment]
Out of scope

**Comment by 0x464e** [comment]
I understand that yt-dlp wont/shouldn't do the photos to video conversion, but is there any chance yt-dlp could support downloading images from slideshow TikToks? Or is this somehow really problematic?

**Comment by MinePlayersPE** [comment]
[That's gallery-dl's job](https://github.com/mikf/gallery-dl/issues/3061), and besides(/because of) the principle, I'm pretty sure stuff like post processors simply aren't designed to handle them

**Comment by 0x464e** [comment]
Ok, I'd like to add that slideshow support was added for desktop TikTok just a few hrs ago, and it's now very simple to get the images. No mobile emulation needed or anything. E.g. just a plan get request with no headers or anything gives working image urls in the response:

```json
"imagePost": {
  "images": [
    {
      "imageURL": {
        "urlList": [
          "https:\u002F\u002Fp19-sign.tiktokcdn-us.com\u002Ftos-useast5-i-photomode-tx\u002Ff7cf550d212e450e8db0190589ba292e~tplv-photomode-image.jpeg?x-expires=1676498400&x-signature=gTcEwXN22VccCkqWZEV6oc44VLg%3D",
          "https:\u002F\u002Fp16-sign.tiktokcdn-us.com\u002Ftos-useast5-i-photomode-tx\u002Ff7cf550d212e450e8db0190589ba292e~tplv-photomode-image.jpeg?x-expires=1676498400&x-signature=gtDNxC%2F3%2BfoAd8Uhi%2BAoVNPCdeM%3D"
        ]
      },
      "imageWidth": 1399,
      "imageHeight": 1080
    },
    {
      "imageURL": {
        "urlList": [
          "https:\u002F\u002Fp19-sign.tiktokcdn-us.com\u002Ftos-useast5-i-photomode-tx\u002F7f496642d88540e3abb3c377629bd049~tplv-photomode-image.jpeg?x-expires=1676498400&x-signature=6ICcyMLKm8y7KWgPphgSXbixQ%2FM%3D",
          "https:\u002F\u002Fp16-sign.tiktokcdn-us.com\u002Ftos-useast5-i-photomode-tx\u002F7f496642d88540e3abb3c377629bd049~tplv-photomode-image.jpeg?x-expires=1676498400&x-signature=S4OoViBRSMaS5XrUHTMlJiuBRY0%3D"
        ]
      },
      "imageWidth": 1303,
      "imageHeight": 1080
    },
    ...
```

Does this change anything, or is this still not yt-dlp's job?  
It's just annoying that yt-dlp is so good for downloading TikTok videos, but then I'd need to have a different tool for the images, and need to make multiple requests to first determine if it's a video or photo TikTok, etc..

**Comment by pukkandan** [comment]
I have no intention of expanding yt-dlp's scope to downloading images.

On some other sites, gallery-dl can downloads images and pass videos through to ytdl/p - no manual filtering needed. This request should be further discussed there
