### ISSUE TITLE
yt-dlp CLI options equivalent in python

### ISSUE THREAD

**Issue by sourabhkv** [yt-dlp/yt-dlp#6223]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.01.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I want to download a  video and playlist with certain options
I looked through documentation but I could not find all the options in [embedding YT-DLP](https://github.com/yt-dlp/yt-dlp#embedding-yt-dlp) which I want to use

Here are the **CLI** options 

- Download a YT video embed thumbnail add metadata with `--no-mtime`
```powershell
.\yt-dlp_x86.exe --parse-metadata "description:(?s)(?P<meta_comment>.+)" --parse-metadata "uploader:(?s)(?P<meta_album_artist>.+)"  --parse-metadata "%(upload_date,release_year).4s:(?P<meta_date>.+)" --add-metadata --no-mtime --embed-metadata -f 134+140 -o "~D:/cob/%(title)s-%(channel)s.%(ext)s" https://www.youtube.com/watch?v=nVDjMbtQWMo -r 1.2M --embed-thumbnail
```

- Convert YT video to m4a music and add metadata
```powershell
.\yt-dlp_x86.exe --parse-metadata "description:(?s)(?P<meta_comment>.+)" --parse-metadata "uploader:(?s)(?P<meta_album_artist>.+)" --parse-metadata "%(upload_date,release_year).4s:(?P<meta_date>.+)" --add-metadata --embed-thumbnail --no-mtime -f ba -x --audio-format m4a --audio-quality 0  -o "~D:/cob/%(title)s-%(channel)s.%(ext)s" https://www.youtube.com/watch?v=nVDjMbtQWMo
```

- Download a YT playlist with specific items 
```powershell
.\yt-dlp_x86.exe --parse-metadata "description:(?s)(?P<meta_comment>.+)" --parse-metadata "%(upload_date,release_year).4s:(?P<meta_date>.+)" --add-metadata --no-mtime -S height:480,vext:mp4,aext:m4a -o "~D:/cob/%(uploader)s/%(playlist_title)s/%(playlist_index)s/%(title)s.%(ext)s" PLoSWVnSA9vG-9NTwPXTRLOU4Ltec7fGkg --playlist-items 1-2
```

- Also how to download specific part of YT video using embedded yt-dlp

**Can you help me writing the above commands using  yt-dlp lib in python**

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
See pinned FAQ: https://github.com/yt-dlp/yt-dlp/issues/5859#issuecomment-1363938900

**Comment by pukkandan** [comment]
PS: While --parse-metadata can be translated to API args, creating a custom PP would be generally easier/more flexible

**Comment by sourabhkv** [comment]
Can you help me with this `--parse-metadata "%(upload_date,release_year).4s:(?P<meta_date>.+)"`

```python
import yt_dlp

URLS = ['https://www.youtube.com/watch?v=BaW_jenozKc']

class Myparser(yt_dlp.postprocessor.PostProcessor):
    def run(self, info):
        self._configuration_args('--parse-metadata "%(upload_date,release_year).4s:(?P<meta_date>.+)"')
        return [], info


with yt_dlp.YoutubeDL() as ydl:
    ydl.add_post_processor(Myparser(), when='post_process')
    ydl.download(URLS)
```
It's not working

**Comment by pukkandan** [comment]
Where did you get that code? It does nothing!

If you are writing custom PP, you want to edit `info` in the PP. Like:
```
info['meta_date'] = (info.get('upload_date') or info.get('release_date') or '')[:4]
```

But what's the point of adding meta_ fields when you are not running `--embed-metadata`?

---

Did you check the link I gave above?
```py
>>> pprint(cli_to_api('--parse-metadata', '%(upload_date,release_year).4s:(?P<meta_date>.+)', '--add-metadata'))
{'postprocessors': [{'actions': [(yt_dlp.postprocessor.metadataparser.MetadataParserPP.interpretter,
                                  '%(upload_date,release_year).4s',
                                  '(?P<meta_date>.+)')],
                     'key': 'MetadataParser',
                     'when': 'pre_process'},
                    {'add_chapters': True,
                     'add_infojson': 'if_exists',
                     'add_metadata': True,
                     'key': 'FFmpegMetadata'}]}
```
