### ISSUE TITLE
Wrong subtitles

### ISSUE THREAD

**Issue by LonelyGuy12** [yt-dlp/yt-dlp#6226]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.01.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

For some reason the subtitles that I download are all wrong and fked up

Also... is yt-dlp not able to handle image based subtitles?

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by LonelyGuy12** [comment]
The command I used was 
```
yt-dlp --merge-output-format mkv --write-auto-sub -f "bestvideo+bestaudio[ext=m4a]/best" https://youtu.be/73gyp4i7Qeo```

**Comment by LonelyGuy12** [comment]
The subtitles in the output are just all messed up....
![image](https://user-images.githubusercontent.com/93421108/218517728-f40de149-77b5-48c0-8c7c-3b128c9ce4f8.png)

**Comment by pukkandan** [comment]
Do not abuse the "Question" template to post incomplete bug reports.

Properly fill out an appropriate issue form
