### ISSUE TITLE
How to remove URL from title when downloading a video from youtube?

### ISSUE THREAD

**Issue by erikfiala** [yt-dlp/yt-dlp#6230]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.01.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Hey guys I'm a complete newbie when it comes to coding and I don't understand many things, so sorry for not being able to find a probably very obvious solution. I looked through questions and couldn't find this, but what would be a command to download a youtube video without the url in the title?

This is how my video title is after the download:
`Billions Of Wealth Destroyed In 2022!! 🤯😱 #shorts #money #finance #wealth [8p0QWGZaoy4]`

This is how I want it to be:
`Billions Of Wealth Destroyed In 2022!! 🤯😱 #shorts #money #finance #wealth`

Thanks in advance.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
Add this to your command/config:
`-o "%(title)s.%(ext)s"`

The relevant sections of the readme:
https://github.com/yt-dlp/yt-dlp#output-template-examples
https://github.com/yt-dlp/yt-dlp#output-template

**Comment by erikfiala** [comment]
Thank you so much! Worked like a charm 🙏

**Comment by erikfiala** [comment]
Thank you so much! Worked like a charm 🙏
