### ISSUE TITLE
Download youtube video with worst premerged video quality, bad download rate

### ISSUE THREAD

**Issue by Gloster10** [yt-dlp/yt-dlp#6232]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.01.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Ubuntu Mate 22.04, download a youtube video playlist
I download a complete video playlist with the -f b option, that I can check the videos to decide whether its worst to save the films afterwards in a better quality (then e.g.: with -F, -f 137+140 ...).
But to check the videos, it is not necessary to get the "best" premerged version, its enough to get the "worst" premerged version.
So I did try the option "-f w", and it works. With the parameter -f w I will get the worst premerged version.
But unfortunately the youtube download rate slows down to 20Kib/s instead of normal values higher then 6Mib/s 
([download] Destination: Kampf um die 5. Galaxis.3gp
[download]   1.2% of   57.45MiB at   19.05KiB/s ETA 50:50^C
[download] Destination: Kampf um die 5. Galaxis.mp4
[download]   4.3% of  264.17MiB at    6.13MiB/s ETA 00:41^C)

On other download sides the parameter -f w works perfectly (https://www.ardmediathek.de).

It is possible to use an another parameter, to save the high download rate if I use "-f w" ?

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '-f', 'w', '-o', '%(title)s.%(ext)s', 'https://www.youtube.com/watch?v=weQqm2AhpXw']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2023.01.06 [6becd2508]
[debug] Lazy loading extractors is disabled
[debug] Python 3.10.6 (CPython x86_64 64bit) - Linux-5.15.0-60-generic-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.16.0, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, pyxattr-0.7.2, secretstorage-3.3.1, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1761 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2023.01.06, Current version: 2023.01.06
yt-dlp is up to date (2023.01.06)
[youtube] Extracting URL: https://www.youtube.com/watch?v=weQqm2AhpXw
[youtube] weQqm2AhpXw: Downloading webpage
[youtube] weQqm2AhpXw: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[info] weQqm2AhpXw: Downloading 1 format(s): 17
[debug] Invoking http downloader on "https://rr4---sn-uxax4vopj5qx-q0n6.googlevideo.com/videoplayback?expire=1676416737&ei=gcLrY8DrEtXfx_AP3dWOoAQ&ip=93.132.87.66&id=o-ALPscVHXxWTK1F1vULZsFqXTzYZbYzocTsmkC7Bo7ohg&itag=17&source=youtube&requiressl=yes&mh=Fx&mm=31%2C29&mn=sn-uxax4vopj5qx-q0n6%2Csn-i5h7lner&ms=au%2Crdu&mv=m&mvi=4&pl=18&initcwndbps=1001250&spc=H3gIhtzmB4MXXQzQF18vW_eu2hflWfM&vprv=1&svpuc=1&mime=video%2F3gpp&gir=yes&clen=60239224&dur=6132.240&lmt=1554863102697017&mt=1676394794&fvip=1&fexp=24007246&c=ANDROID&txp=5431432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIhALauBJMGFmNGSXd6munFG5JjjYSIf2wQCOfhbFYccrbaAiA1-Mj2cxgTFg6sumE-H4IlbrmXeSiPt53QTHdwOyjs2A%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgQySLDUrLfMsyhUAFkLockzMcn4yfGl1Z6dxIYTfvamsCID3zc_NK5RraRTaF8ncD8tDt6vExLeXCWq56Dr0VLybo"
[download] Resuming download at byte 729088
[download] Destination: Kampf um die 5. Galaxis.3gp
[download]   3.1% of   57.45MiB at   19.21KiB/s ETA 49:28^C
ERROR: Interrupted by user
```

**Comment by pukkandan** [comment]
The 3gp format is rete-limited at server side. You probably don't want to download that format anyway. Try `-f w[ext=mp4]`

**Comment by Gloster10** [comment]
@pukkanden : 
Thank you, it works (-f w[ext=mp4]), and that it is what I have want. 
Only to have a preview video, to minimize the download time of all videos of the play list (also to save the SSD healthy).
After all I can check the video whether its go through my "Quality assurance" and download then the best quality via " -F ...".
