### ISSUE TITLE
Vimeo : Incorrect Id returned (HTTP Error 400: Bad Request)

### ISSUE THREAD

**Issue by techfor** [yt-dlp/yt-dlp#6233]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2023.01.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Provide a description that is worded well enough to be understood

When I try to get title using the following:
 yt-dlp -vU  --get-filename -o "%(title)s" https://player.vimeo.com/video/793002971

The error that is returned outputs a different videoid (793123743)
 WARNING: [vimeo] Failed to download m3u8 information: HTTP Error 400: Bad Request
ERROR: [vimeo] 793123743: No video formats found!; 

What I'm looking for is the error returns with the requested id. 
What I've noticed is that the videos with this kind of behaviour  are on-demand so I think it is re-directing it somehow.

Expected Result: Give error with requested id.  
I have a list and it assumes that an id was skipped so it throws off my script.
Thanks

I 

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp -vU  --get-filename -o "%(title)s" https://player.vimeo.com/video/793002971
[debug] Command-line config: ['-vU', '--get-filename', '-o', '%(title)s', 'https://player.vimeo.com/video/793002971']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2023.01.06 [6becd25] (pip)
[debug] Python 3.11.1 (CPython AMD64 64bit) - Windows-10-10.0.19044-SP0 (OpenSSL 1.1.1q  5 Jul 2022)
[debug] exe versions: ffmpeg 2023-01-30-git-2d202985b7-full_build-www.gyan.dev (setts), ffprobe 2023-01-30-git-2d202985b7-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1760 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2023.01.06, Current version: 2023.01.06
yt-dlp is up to date (2023.01.06)
[vimeo] Extracting URL: https://player.vimeo.com/video/793002971
[vimeo] 793002971: Downloading webpage
[vimeo] 793002971: Downloading akfire_interconnect_quic m3u8 information
WARNING: [vimeo] Failed to download m3u8 information: HTTP Error 400: Bad Request
ERROR: [vimeo] 793123743: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "C:\python\Lib\site-packages\yt_dlp\YoutubeDL.py", line 1502, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\python\Lib\site-packages\yt_dlp\YoutubeDL.py", line 1599, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\python\Lib\site-packages\yt_dlp\YoutubeDL.py", line 1658, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\python\Lib\site-packages\yt_dlp\YoutubeDL.py", line 2606, in process_video_result
    self.raise_no_formats(info_dict)
  File "C:\python\Lib\site-packages\yt_dlp\YoutubeDL.py", line 1043, in raise_no_formats
    raise ExtractorError(msg, video_id=info['id'], ie=info['extractor'],
yt_dlp.utils.ExtractorError: [vimeo] 793123743: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

**Comment by bashonly** [comment]
This player.vimeo.com URL appears to be for paid content.

https://vimeo.com/793002971 redirects in browser to https://vimeo.com/ondemand/aweofgod/

If we manipulate the URL a bit, `yt-dlp https://vimeo.com/793002971` will download video_id `793123743` without any errors:
https://vimeo.com/ondemand/aweofgod/793123723 is the only free content available on https://vimeo.com/ondemand/aweofgod/

What is the webpage that this player.vimeo.com URL originated from? Can you give more information about the video you actually want to download?

> [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

If your example URL is indeed for paid content, maybe reconsider this

**Comment by techfor** [comment]
Hello, thanks for checking into this. 
I'm not sure if it is paid.  I was just getting the title and it was for testing.  For logging purposes,  I thought when the error is shown,it would show the original id not the redirected one.  Is this the expected output?

**Comment by Grub4K** [comment]
If your question is if the change in ID is expected, then yes. The first time we get an ID is from the URL directly. This id might be completely something else, since vimeo urls are generally unreliable. After that we start the extraction, which fails. That ID is taken from the player JSON, which might be different depending on different circumstances (hence why bashonly asked you these questions). In this particular case the player provides us with an id of 793123743, which will then be used in the error. If that was your only concern, feel free to close the issue.

Maybe a message clarifying that different content will be extracted could make sense? That will have to be considered in the new `VimeoOnDemandIE`.
The download failing is to be expected, as the same "Bad Request" also happens in a browser.

**Comment by techfor** [comment]
Ok thanks, my only concern was about reporting with the changed id.  So, this can be closed.
