### ISSUE TITLE
goplay extractor broken

### ISSUE THREAD

**Issue by MathiasDeWeerdt** [yt-dlp/yt-dlp#6235]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2023.01.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Belgium

### Provide a description that is worded well enough to be understood

goplay.be now loads newer videos in a new format. (DASH MPD)
which means the current extractor is broken. 

Extracted the following information so far; 

``` BASH
curl -X POST https://pubads.g.doubleclick.net/ondemand/dash/content/2615619/vid/10150078534976527/streams
```

``` JSON
{
  "stream_id": "091f9127-c615-4354-9006-af3fb09ac261",
  "duration": 2687.64,
  "stream_type": "on_demand",
  "stream_manifest": "https://pubads.g.doubleclick.net/ondemand/dash/content/2615619/vid/10150078534976527/GRQ/streams/091f9127-c615-4354-9006-af3fb09ac261/manifest.mpd",
  "manifest_format": "dash",
  "time_events_url": "https://pubads.g.doubleclick.net/ondemand/dash/content/2615619/vid/10150078534976527/GRQ/streams/091f9127-c615-4354-9006-af3fb09ac261/time-events.json"
}
```

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['--verbose', '-o', '/media/data2/series/Big Brother/Season 3/%(series)s - S0%(season_number)sE%(episode_number)s.%(ext)s', '--no-hls-use-mpegts', '-u', 'PRIVATE', '-p', 'PRIVATE', '-N', '8', '-f', 'bestvideo+bestaudio', '--merge-output-format', 'mp4', 'https://www.goplay.be/video/big-brother/big-brother-s3/big-brother-s3-aflevering-32']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8 (No ANSI), error utf-8 (No ANSI), screen utf-8 (No ANSI)
[debug] yt-dlp version 2023.01.06 [6becd2508] (linux_exe)
[debug] Python 3.10.6 (CPython x86_64 64bit) - Linux-5.15.0-60-generic-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, secretstorage-3.3.1, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1767 extractors
[GoPlay] Logging in
[GoPlay] Authenticating username
[GoPlay] Authenticating password
[GoPlay] Extracting URL: https://www.goplay.be/video/big-brother/big-brother-s3/big-brother-s3-aflevering-32
[GoPlay] big-brother-s3-aflevering-32: Downloading webpage
[GoPlay] 5bd06f78-6e20-439b-8d67-cfe152c0cd68: Downloading JSON metadata
ERROR: An extractor error has occurred. (caused by KeyError('manifestUrls')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp/extractor/common.py", line 693, in extract
  File "yt_dlp/extractor/goplay.py", line 83, in _real_extract
KeyError: 'manifestUrls'
```

**Comment by b12e** [comment]
Doesn't look like it's just newer videos - for example, I could download De Rechtbank S12E05 just fine last sunday using the "old" URL format, but S12E02 right now has the new format too.

Thanks for your investigation though, I thought I was going crazy.

**Comment by emversch** [comment]
@jeroenj do you have any insight?

**Comment by emversch** [comment]
@michaelarnauts @cnugteren do any of you have an idea how to fix this issue, since you were involved in older patches? De Mol is going to start again soon and I am desperate :(

**Comment by michaelarnauts** [comment]
Same for me, GoPlay moved over for some streams to the doubleclick service, where ads are injected directly in the stream. It's a totally different stream compared with the usual streams. 

You might find more info when searching about https://pubads.g.doubleclick.net/ondemand/dash

Maybe there is another service that is using doubleclick that had some more documentation.

**Comment by jeroenj** [comment]
I haven't looked into this yet either. Since the GoPlay app now supports AirPlay I'm using that instead of downloading it first.

**Comment by KevinDenys** [comment]
Currently receiving errors on https://github.com/yt-dlp/yt-dlp/blob/master/yt_dlp/extractor/goplay.py#L83

I checked it and indeed the request returns no object with 'manifestUrls' key.

--

I checked the network tab and found a 'https://pubads.g.doubleclick.net/ondemand/dash/content/' url and when downloading that using yt-dlp it downloads a 1080p file but only the first 18-19min..

**Comment by emversch** [comment]
> Currently receiving errors on https://github.com/yt-dlp/yt-dlp/blob/master/yt_dlp/extractor/goplay.py#L83
> 
> I checked it and indeed the request returns no object with 'manifestUrls' key.
> 
> --
> 
> I checked the network tab and found a 'https://pubads.g.doubleclick.net/ondemand/dash/content/' url and when downloading that using yt-dlp it downloads a 1080p file but only the first 18-19min..

I noticed the same. As @b12e said, the audio and video is now split up in 3 parts, probably to have 2 blocks of ads in-between. There should be a way to download the 3 parts and then merge them, but I'm not that knowledgeable about ffmpeg and did not have time yet

**Comment by emversch** [comment]
you can download all parts according to the wiki:
`yt-dlp -F <url to manifest>` will give a list of all formats, each leading with a tag
`yt-dlp -f <tag> <url to manifest>` will download that specific video

The problem that I have is that I don't know how to select what audio file to download together with the video, so I have the wrong audio file stitched to the video unfortunately. I also don't know how to merge all video parts

**Comment by KevinDenys** [comment]
I figured it out manually how to match the video + audio and indeed download every part. I guess stitching can be down using ffmpeg.. I can explain how I matched them on discord if you want, maybe someone can figure out how to do it automaticly and update the extractor

**Comment by emversch** [comment]
Would it be possible to explain it here? That way other people can also have a workaround and as you said, it might inspire people to write a workaround in the extractor

**Comment by emversch** [comment]
Thanks! Currently at work so I'll check myself later, much appreciated! How did you figure out what audio goes with what video?

**Comment by emversch** [comment]
I figured out how to merge the files successfully with the help of [this stackoverflow article](https://stackoverflow.com/questions/7333232/how-to-concatenate-two-mp4-files-using-ffmpeg): first make a document with all names of the files that looks like this
```
$ cat mylist.txt
file '/path/to/file1'
file '/path/to/file2'
file '/path/to/file3'
```
and then execute the following ffmpeg commando
    
`$ ffmpeg -f concat -safe 0 -i mylist.txt -c copy output.mp4`

**Comment by KevinDenys** [comment]
just tested the ffmpeg stitching works great :D 

now someone has to automate it

**Comment by alard** [comment]
As an alternative, you could concatenate the `fragments` list for all periods and have them downloaded by `yt-dlp` as a single file.

I made [an update to the goplay extractor](https://github.com/yt-dlp/yt-dlp/compare/master...alard:yt-dlp:f-goplay) that does this. It works on the recent De Mol streams.

It's not ideal to do this at the goplay extractor level, I guess. I assume other sources with multi-period MPD streams will have the same problem, so it would be better if the MPD code could separate the periods (and perhaps merge them).

**Comment by KevinDenys** [comment]
@alard thank you for your contribution, I tried automating the process above, but my python skills are “undefined”. JavaScript developer 😅

**Comment by KevinDenys** [comment]
@alard tested it, it only downloaded 22min instead of the full 44min: tested using https://www.goplay.be/video/assisen/assisen-s1/assisen-s1-aflevering-6#autoplay

**Comment by Donaldini** [comment]
@KevinDenys what exactly did you do to download the files manually?
> Then I downloaded them using
> part1: yt-dlp -f qualityID+audioID part2: yt-dlp -f qualityID+audioID part3: yt-dlp -f qualityID+audioID

I want to try this too myself but isnt there a need for a url or reference to the files?

**Comment by azertyalex** [comment]
It looks like the linked PR is done. Is there something that needs to be tested still?

**Comment by bashonly** [comment]
@azertyalex are there videos that aren't DRM protected on the site?

**Comment by azertyalex** [comment]
I went down the drm/widevine rabbit hole. I guess this is where it stops?

**Comment by alard** [comment]
The DRM seems to be limited to some of the shows. Here are three links to different shows that still work (from a Dutch IP address):

https://www.goplay.be/video/de-mol/de-mol-s11/de-mol-s11-aflevering-1 (published last year)
https://www.goplay.be/video/achter-de-schermen/achter-de-schermen-s2/achter-de-schermen-s2-aflevering-7 (published this week)
https://www.goplay.be/video/de-tafel-van-gert/de-tafel-van-gert-s3/de-tafel-van-gert-s3-aflevering-20 (this week)

For @azertyalex's link, https://www.goplay.be/video/de-slimste-mens-ter-wereld/de-slimste-mens-ter-wereld-s21/de-slimste-mens-ter-wereld-s21-aflevering-4 , I do get the DRM warning listed above.

**Comment by azertyalex** [comment]
It's nice to see some videos that don't have drm.

**Comment by mediaminister** [comment]
> I went down the drm/widevine rabbit hole. I guess this is where it stops?

It never stops.
![Screenshot at 2023-10-26 22-29-21](https://github.com/yt-dlp/yt-dlp/assets/45148099/7ae65a8f-fda3-4847-95f1-fc85e3d59bc0)

**Comment by alard** [comment]
This should now work. If you get any ffmpeg errors at the end, try a different ffmpeg version, such as the [yt-dlp custom builds](https://github.com/yt-dlp/FFmpeg-Builds) (see also #9262).
