### ISSUE TITLE
VK.com ERROR "Access to this video has been restricted by the community's managers" 

### ISSUE THREAD

**Issue by kimryak** [yt-dlp/yt-dlp#6238]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2023.01.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Russia

### Provide a description that is worded well enough to be understood

I have an error "Access to this video has been restricted by its creator" on my video that only I can watch and error "Access to this video has been restricted by the community's managers" which is available for donators.

Cookies are passed from browser and I tried pass them with a file exported via Get cookies.txt. But it's suspicious there is no an error like "Login failed" when cookies is not passed.

### What I have tried:

1. The first that I tried is [fix vk video extractor](https://github.com/yt-dlp/yt-dlp/pull/4128) for youtube_dl and it helped but a week later the errors occured. 
2. last release of yt_dlp and with "Fix vk video extractor".
3. yt_dlp_patched

I’d appreciate your help!

Here's my code:
```shell
import yt_dlp, pathlib

def download_video (URL):
     path = pathlib.Path(r"C:\users\Иван\Documents\Python_programs\DownloadKV\vk.com.txt")

     ydl_opts = { "cookies-from-browser": "chrome", "verbose": True, "ie": "vk" }
     with yt_dlp.YoutubeDL (ydl_opts) as ydl:
          ydl.download (URL)
          
download_video("https://vk.com/video/subscriptions?z=video-168725999_456240334%2Fpl_cat_subscribes") 
```
### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output
For some reason there is not the line [debug] Command-line config).
```
File "C:\Users\Иван\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\YoutubeDL.py", line 1491, in extract_info
    return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Иван\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\YoutubeDL.py", line 1520, in wrapper
    self.report_error(str(e), e.format_traceback())
  File "C:\Users\Иван\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\YoutubeDL.py", line 1012, in report_error
    self.trouble(f'{self._format_err("ERROR:", self.Styles.ERROR)} {message}', *args, **kwargs)
  File "C:\Users\Иван\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\YoutubeDL.py", line 952, in trouble
    raise DownloadError(message, exc_info)
yt_dlp.utils.DownloadError: ERROR: [vk] None: Access to this video has been restricted by the community's managers
PS C:\Users\Иван\Documents\Python_programs\DownloadKV> & C:/Users/Иван/AppData/Local/Programs/Python/Python311/python.exe c:/Users/Иван/Documents/Python_programs/DownloadKV/download_video.py
[debug] Encodings: locale cp1251, fs utf-8, pref cp1251, out utf-8, error utf-8, screen utf-8 
[debug] yt-dlp version 2023.01.06 [6becd2508] API 
[debug] params: {'verbose': True, 'ie': 'vk', 'compat_opts': set()}
[debug] Lazy loading extractors is disabled
[debug] Python 3.11.1 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1q  5 Jul 2022) 
[debug] exe versions: none 
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1767 extractors 
[vk] Extracting URL: https://vk.com/video/subscriptions?z=video-168725999_456240334%2Fpl_cat_subscribes 
[vk] -168725999_456240334: Downloading JSON metadata 
ERROR: [vk] None: Access to this video has been restricted by the community's managers 
  File "C:\Users\Иван\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\extractor\common.py", line 693, in extract 
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Иван\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\extractor\vk.py", line 329, in _real_extract
    payload = self._download_payload('al_video', video_id, data)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Иван\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\extractor\vk.py", line 84, in _download_payload
    raise ExtractorError(clean_html(payload[0][1:-1]), expected=True)
```

**Comment by pukkandan** [comment]
> * [x]  Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by kimryak** [comment]
> > * [x]   Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

It is all that was outputted. For some reason there is not the line [debug] Command-line config).

```
File "C:\Users\Иван\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\YoutubeDL.py", line 1491, in extract_info
    return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Иван\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\YoutubeDL.py", line 1520, in wrapper
    self.report_error(str(e), e.format_traceback())
  File "C:\Users\Иван\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\YoutubeDL.py", line 1012, in report_error
    self.trouble(f'{self._format_err("ERROR:", self.Styles.ERROR)} {message}', *args, **kwargs)
  File "C:\Users\Иван\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\YoutubeDL.py", line 952, in trouble
    raise DownloadError(message, exc_info)
yt_dlp.utils.DownloadError: ERROR: [vk] None: Access to this video has been restricted by the community's managers
PS C:\Users\Иван\Documents\Python_programs\DownloadKV> & C:/Users/Иван/AppData/Local/Programs/Python/Python311/python.exe c:/Users/Иван/Documents/Python_programs/DownloadKV/download_video.py
[debug] Encodings: locale cp1251, fs utf-8, pref cp1251, out utf-8, error utf-8, screen utf-8 
[debug] yt-dlp version 2023.01.06 [6becd2508] API 
[debug] params: {'verbose': True, 'ie': 'vk', 'compat_opts': set()}
[debug] Lazy loading extractors is disabled
[debug] Python 3.11.1 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1q  5 Jul 2022) 
[debug] exe versions: none 
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1767 extractors 
[vk] Extracting URL: https://vk.com/video/subscriptions?z=video-168725999_456240334%2Fpl_cat_subscribes 
[vk] -168725999_456240334: Downloading JSON metadata 
ERROR: [vk] None: Access to this video has been restricted by the community's managers 
  File "C:\Users\Иван\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\extractor\common.py", line 693, in extract 
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Иван\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\extractor\vk.py", line 329, in _real_extract
    payload = self._download_payload('al_video', video_id, data)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Иван\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\extractor\vk.py", line 84, in _download_payload
    raise ExtractorError(clean_html(payload[0][1:-1]), expected=True)

```

**Comment by kimryak** [comment]
> > > * [x]    Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below
> 
> It is all that was outputted. For some reason there is not the line [debug] Command-line config).
> 
> ```
> File "C:\Users\Иван\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\YoutubeDL.py", line 1491, in extract_info
>     return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\Иван\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\YoutubeDL.py", line 1520, in wrapper
>     self.report_error(str(e), e.format_traceback())
>   File "C:\Users\Иван\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\YoutubeDL.py", line 1012, in report_error
>     self.trouble(f'{self._format_err("ERROR:", self.Styles.ERROR)} {message}', *args, **kwargs)
>   File "C:\Users\Иван\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\YoutubeDL.py", line 952, in trouble
>     raise DownloadError(message, exc_info)
> yt_dlp.utils.DownloadError: ERROR: [vk] None: Access to this video has been restricted by the community's managers
> PS C:\Users\Иван\Documents\Python_programs\DownloadKV> & C:/Users/Иван/AppData/Local/Programs/Python/Python311/python.exe c:/Users/Иван/Documents/Python_programs/DownloadKV/download_video.py
> [debug] Encodings: locale cp1251, fs utf-8, pref cp1251, out utf-8, error utf-8, screen utf-8 
> [debug] yt-dlp version 2023.01.06 [6becd2508] API 
> [debug] params: {'verbose': True, 'ie': 'vk', 'compat_opts': set()}
> [debug] Lazy loading extractors is disabled
> [debug] Python 3.11.1 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1q  5 Jul 2022) 
> [debug] exe versions: none 
> [debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
> [debug] Proxy map: {}
> [debug] Loaded 1767 extractors 
> [vk] Extracting URL: https://vk.com/video/subscriptions?z=video-168725999_456240334%2Fpl_cat_subscribes 
> [vk] -168725999_456240334: Downloading JSON metadata 
> ERROR: [vk] None: Access to this video has been restricted by the community's managers 
>   File "C:\Users\Иван\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\extractor\common.py", line 693, in extract 
>     ie_result = self._real_extract(url)
>                 ^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\Иван\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\extractor\vk.py", line 329, in _real_extract
>     payload = self._download_payload('al_video', video_id, data)
>               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\Иван\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\extractor\vk.py", line 84, in _download_payload
>     raise ExtractorError(clean_html(payload[0][1:-1]), expected=True)
> ```

Oh, I forgot to put output  of verbose in the start. My bad

**Comment by dirkf** [comment]
The command-line debug output is only generated if you actually use the program's command-line wrapper, but you are calling the program as a module.

With https://vk.com/video-168725999_456240334 I get the same "Access ... restricted by the community's managers" error with yt-dlp and in the browser. Is it possible that that is in fact what has happened?

**Comment by bashonly** [comment]
"cookies-from-browser" is wrong, change to
```py
'cookiesfrombrowser': ('chrome', None, None, None),
```
the `path` variable is also not doing anything (if you were expecting it to)

**Comment by kimryak** [comment]
> "cookies-from-browser" is wrong, change to
> 
> ```python
> 'cookiesfrombrowser': ('chrome', None, None, None),
> ```
> 
> the `path` variable is also not doing anything (if you were expecting it to)

yeah! it works!! Thanks!
Can you point me at where is python syntax discribed for yt-dlp? Honestly I could not find it.

**Comment by bashonly** [comment]
https://github.com/yt-dlp/yt-dlp/blob/9ebac35577e61c3d25fafc959655fa3ab04ca7ef/yt_dlp/YoutubeDL.py#L308-L311

**Comment by kimryak** [comment]
> https://github.com/yt-dlp/yt-dlp/blob/9ebac35577e61c3d25fafc959655fa3ab04ca7ef/yt_dlp/YoutubeDL.py#L308-L311

Thank you!! Best of luck to you!!
