### ISSUE TITLE
How to bypass login and friend requirement for private videos via Cookies?

### ISSUE THREAD

**Issue by koopa990** [yt-dlp/yt-dlp#6242]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.01.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

So, I installed Get Cookie browser plugin for Brave, and I also executed the "--get-cookies-from-browser" following the link; no positive result from it. I am a bit lost here on how to make the bypass work?
The website is from **Thisvid.com**

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vu', 'https://thisvid.com/videos/peeing129/']
Type account password and press [Return]:
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2023.01.06 [6becd25] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 2022-10-10-git-f3b5277057-full_build-www.gyan.dev (setts), ffprobe 2022-10-10-git-f3b5277057-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.16.0, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1760 extractors

Usage: yt-dlp.exe [OPTIONS] URL [URL...]

yt-dlp.exe: error: You must provide at least one URL.
Type yt-dlp --help to see a list of all options.
```

**Comment by bashonly** [comment]
> "--get-cookies-from-browser"

The option is `--cookies-from-browser`, used like `--cookies-from-browser chrome` (or replace `chrome` with your browser of choice)

> how to make the bypass work?

It's not really a "bypass," `--cookies-from-browser` will only allow you to download the video if you are logged into the site in your browser *and* your account is authorized to view the content. If your account is not authorized to watch the video, yt-dlp cannot bypass this.

> '-vu'

Options are case-sensitive. `-U` (uppercase) will check for an update to yt-dlp, which is why the issue template recommends to add `-vU` to your command to get verbose output. `-u` (lowercase) will have yt-dlp process the next argument as the username and then it will prompt you for your password. In the log you posted you used `-vu` (lowercase), so yt-dlp interpreted the URL as your username and prompted you for your password, and then couldn't find a URL to download.

**Comment by koopa990** [comment]
> > "--get-cookies-from-browser"
> 
> The option is `--cookies-from-browser`, used like `--cookies-from-browser brave` (or replace `brave` with your browser of choice)
> 
> > how to make the bypass work?
> 
> It's not really a "bypass," `--cookies-from-browser` will only allow you to download the video if you are logged into the site in your browser _and_ your account is authorized to view the content. If your account is not authorized to watch the video, yt-dlp cannot bypass this.
> 
> > '-vu'
> 
> Options are case-sensitive. `-U` (uppercase) will check for an update to yt-dlp, which is why the issue template recommends to add `-vU` to your command to get verbose output. `-u` (lowercase) will have yt-dlp process the next argument as the username and then it will prompt you for your password. In the log you posted you used `-vu` (lowercase), so yt-dlp interpreted the URL as your username and prompted you for your password, and then couldn't find a URL to download.

OH, I see now. Well, the issue is the account sign-up is disabled unknowingly. So I guess it is impossible to snatch the vid?

**Comment by bashonly** [comment]
> OH, I see now. Well, the issue is the account sign-up is disabled unknowingly. So I guess it is impossible to snatch the vid?

If that's the case, then yes
