### ISSUE TITLE
[Crunchyroll] Allow to dump playlist json

### ISSUE THREAD

**Issue by tamodolo** [yt-dlp/yt-dlp#6243]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a site-specific feature
- [X] I've verified that I'm running yt-dlp version **2023.01.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Brazil

### Example URLs

https://www.crunchyroll.com/pt-br/series/GY5P48XEY/demon-slayer-kimetsu-no-yaiba

### Provide a description that is worded well enough to be understood

I made a script for personal use that reads episode json dumps from yt-dlp to control ongoing series but this can take a really long time... I see that yt-dlp downloads the season playlist before tracking episodes and I would like to be allowed to dump that json.

if available please add episode number and other infos to this json if possible.

The output is just to point what I want to be able to dump.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[Cookies] Extracting cookies from vivaldi
[Cookies] Extracted 2185 cookies from vivaldi
[crunchyroll:playlist] Extracting URL: https://www.crunchyroll.com/pt-br/series/GY5P48XEY/demon-slayer-kimetsu-no-yaiba
[crunchyroll:playlist] Retrieving main page (lang=pt-br/)
[crunchyroll:playlist] Authenticating with grant_type=etp_rt_cookie
[crunchyroll:playlist] GY5P48XEY: Downloading series JSON (I want to dump this file)
[download] Downloading playlist: Demon Slayer: Kimetsu no Yaiba
[crunchyroll:playlist] GY5P48XEY: Downloading seasons JSON (I want to dump this file)
[crunchyroll:playlist] demon-slayer-kimetsu-no-yaiba: Downloading episode list JSON (I want to dump this file)
[crunchyroll:playlist] demon-slayer--kimetsu-no-yaiba--the-movie-mugen-train: Downloading episode list JSON (I want to dump this file)
[crunchyroll:playlist] demon-slayer-kimetsu-no-yaiba-mugen-train-arc: Downloading episode list JSON (I want to dump this file)
[crunchyroll:playlist] demon-slayer-kimetsu-no-yaiba-entertainment-district-arc: Downloading episode list JSON (I want to dump this file)
[info] Writing playlist metadata as JSON to: C:\animetemp1\NA - NA.info.json
[crunchyroll:playlist] Playlist Demon Slayer: Kimetsu no Yaiba: Downloading 45 items of 45
[download] Downloading item 1 of 45
[crunchyroll] Extracting URL: https://www.crunchyroll.com/pt-br/watch/GRG5JD92R
[crunchyroll] Retrieving main page (lang=pt-br/)
[crunchyroll] Authenticating with grant_type=etp_rt_cookie
[crunchyroll] GRG5JD92R: Downloading object info JSON
[crunchyroll] GRG5JD92R: Downloading stream info JSON
[crunchyroll] To get all formats of a hardsub language, use "--extractor-args crunchyrollbeta:hardsub=<language_code or all>". See https://github.com/yt-dlp/yt-dlp#crunchyrollbeta-crunchyroll for more info
[crunchyroll] GRG5JD92R: Downloading adaptive_hls HLS manifest
[crunchyroll] GRG5JD92R: Downloading chapter info
[info] GRG5JD92R: Downloading 1 format(s): adaptive_hls-8097
[info] Writing video metadata as JSON to: C:\animetemp1\Demon Slayer Kimetsu no Yaiba - 1.0.info.json
[download] Downloading item 2 of 45
[crunchyroll] Extracting URL: https://www.crunchyroll.com/pt-br/watch/GR79JN9J6
[crunchyroll] GR79JN9J6: Downloading object info JSON
[crunchyroll] GR79JN9J6: Downloading stream info JSON
[crunchyroll] GR79JN9J6: Downloading adaptive_hls HLS manifest
[crunchyroll] GR79JN9J6: Downloading chapter info
```

**Comment by tamodolo** [comment]
@bashonly thanks for the help!

After tweaking a lot and discussing on the other issue I got this solution:

`"D:\Anime Tools\yt-dlp\yt-dlp.exe" --cookies-from-browser vivaldi --flat-playlist --print-to-file %(webpage_url)s,%(season)s,%(episode_number)s "list.txt" https://www.crunchyroll.com/pt-br/series/GY5P48XEY/demon-slayer-kimetsu-no-yaiba --paths "C:\animetemp1"`

That result in this:

![image](https://user-images.githubusercontent.com/9446795/219431356-cb2b6382-06f3-474c-85cb-279c29f18d2b.png)

It's missing some entries as dub season where listed here too. any ideas how to get that?

**Comment by bashonly** [comment]
The PR is still a work-in-progress, and that is something that still needs to be worked out. Meanwhile you can use the master branch, which just had the "premium-only" bug fixed, and still uses the old endpoints/playlist extraction

**Comment by tamodolo** [comment]
@bashonly you're right! Just compiled master and now I get all seasons.

![image](https://user-images.githubusercontent.com/9446795/219438724-2632f697-be98-428c-a0b1-e0a333f67d7d.png)

Thanks for that! Now I can fix my script.
