### ISSUE TITLE
yt_dlp (Python implementation) can't recognize language code for subtitles (i.e. 'em', 'fr', etc.)

### ISSUE THREAD

**Issue by pavel167** [yt-dlp/yt-dlp#6248]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2023.01.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

You can specify the language (i.e. 'en', 'fr', etc.) and download the correct subtitle file using yt-dlp from the command line, but you can't do the same using yt-dlp in Python. yt_dlp in Python can't recognize language codes.
Here is 2 examples:
1. Check subtitles:
import yt_dlp
link = ['https://www.arte.tv/fr/videos/108558-001-A/comment-voulons-nous-aimer/']
ydl_opts = {'skip_download': True, 'listsubtitles': True}
with yt_dlp.YoutubeDL(ydl_opts) as ydl:
    ydl.download(link)

**here is output:**

(env_video_dnld) pavel@MISSURI:~/env_video_dnld$ python check_subtitles.py
[ArteTV] Extracting URL: https://www.arte.tv/fr/videos/108558-001-A/comment-voulons-nous-aimer/
[ArteTV] 108558-001-A: Downloading JSON metadata
[ArteTV] 108558-001-A: Downloading m3u8 information
[ArteTV] 108558-001-A: Downloading m3u8 information
[ArteTV] 108558-001-A: Downloading m3u8 information
[ArteTV] 108558-001-A: Downloading m3u8 information
[ArteTV] 108558-001-A: Downloading m3u8 information
[ArteTV] 108558-001-A: Downloading m3u8 information
[ArteTV] 108558-001-A: Downloading m3u8 information
[info] Available subtitles for 108558-001-A:
Language Formats
fr       vtt
de       vtt
de_sdh   vtt
en       vtt
es       vtt
pl       vtt
it       vtt

2. Try to download English subtitles:
import yt_dlp
link = ['https://www.arte.tv/fr/videos/108558-001-A/comment-voulons-nous-aimer/']
ydl_opts = {'skip_download': True, 'subtitleslangs': 'en', 'writesubtitles': True}
with yt_dlp.YoutubeDL(ydl_opts) as ydl:
    ydl.download(link)

**here is output:**

(env_video_dnld) pavel@MISSURI:~/env_video_dnld$ python check_subtitles.py
[ArteTV] Extracting URL: https://www.arte.tv/fr/videos/108558-001-A/comment-voulons-nous-aimer/
[ArteTV] 108558-001-A: Downloading JSON metadata
[ArteTV] 108558-001-A: Downloading m3u8 information
[ArteTV] 108558-001-A: Downloading m3u8 information
[ArteTV] 108558-001-A: Downloading m3u8 information
[ArteTV] 108558-001-A: Downloading m3u8 information
[ArteTV] 108558-001-A: Downloading m3u8 information
[ArteTV] 108558-001-A: Downloading m3u8 information
[ArteTV] 108558-001-A: Downloading m3u8 information
[info] 108558-001-A: Downloading 1 format(s): VF-STF-2046+VF-STF-program_audio_0-VF
[info] There's no subtitles for the requested languages
(env_video_dnld) pavel@MISSURI:~/env_video_dnld$

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
(env_video_dnld) pavel@MISSURI:~/env_video_dnld$ yt-dlp -vU
[debug] Command-line config: ['-vU']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2023.01.06 [6becd25] (pip)
[debug] Python 3.10.6 (CPython x86_64 64bit) - Linux-5.15.0-60-generic-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2
[debug] Optional libraries: Cryptodome-3.16.0, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1760 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2023.01.06, Current version: 2023.01.06
yt-dlp is up to date (2023.01.06)
(env_video_dnld) pavel@MISSURI:~/env_video_dnld$
```

**Comment by pukkandan** [comment]
It should be a list of languages `['en']`, not a single string

https://github.com/yt-dlp/yt-dlp/blob/9ebac35577e61c3d25fafc959655fa3ab04ca7ef/yt_dlp/YoutubeDL.py#L278-L281

**Comment by pavel167** [comment]
Thanks. Works !
Is there a function, which allows to get the list of all available subtitles.
Or the only option is to use **extract_info**, then search in the info dictionary the "subtitles' key, then get all keys from the "subtitles' dictionary ?
Thanks in advance.

**Comment by pukkandan** [comment]
> Or the only option is to use **extract_info**, then search in the info dictionary the "subtitles' key, then get all keys from the "subtitles' dictionary ?

Yes. Why would a separate function be needed?

**Comment by pavel167** [comment]
In order to facilitate analysis of available subtitles.
Here is example. 
Download french subtitles. If **'fr_sdh'** is available, take it, and download, otherwise download **'fr'** (if it available), otherwise nothing.
I have also question concerning rendering subtitles in video (selecting font, color, etc.). Should I create another issue for that ?

**Comment by pukkandan** [comment]
> In order to facilitate analysis of available subtitles.
> Here is example.
> Download french subtitles. If **'fr_sdh'** is available, take it, and download, otherwise download **'fr'** (if it available), otherwise nothing.

You can override `ydl.process_subtitles`

```py
class MyYDL(YoutubeDL):
    def process_subtitles(self, video_id, normal_subtitles, automatic_captions):
        if normal_subtitles.get('fr_sdh'):
            return {'fr_sdh': normal_subs['fr_sdh'][-1]}
        elif normal_subtitles.get('fr_sdh'):
            return {'fr': normal_subs['fr'][-1]}

with MyYDL(...) as ydl:
    ...
```

If you think there should be an easier way, pls open a "feature request" explaining your proposal

---

> I have also question concerning rendering subtitles in video (selecting font, color, etc.). Should I create another issue for that ?

You can ask here, but yt-dlp don't edit the subtitles in any way and so has no control over how it's rendered. If you wish to edit it, you'd have to either write a subtitle parser or use a third party program

**Comment by pavel167** [comment]
Well, first of all I couldn't find a Python option that corresponds to the command-line option **--embed-subs**

**Comment by pavel167** [comment]
Understood. **'writesubtitles': True** corresponds to **--embed-subs**
Does exist an option just to download subtitles, NOT embed them into video ?

**Comment by pukkandan** [comment]
> **'writesubtitles': True** corresponds to **--embed-subs**

No. It corresponds to `--write-sub`. `--embed-subs` is a postprocessor.

https://github.com/yt-dlp/yt-dlp/issues/5859#issuecomment-1363938900 will help you

**Comment by pavel167** [comment]
Here is how subtitles look in original video playing on the website:
https://i.postimg.cc/2SN9QqbK/Screenshot-from-2023-02-16-16-16-31.png
and here is how it is rendered by yt-dlp:
https://i.postimg.cc/Y01nZkT3/Screenshot-from-2023-02-16-16-13-19.png
Is it possible to have the same style

When I specify  'writesubtitles': True in yt-dlp options in Python script, the subtitles are embedded into video ... I've just checked it.
Does exist an option for Python script allowing just to download subtitles as .vtt file, NOT embed them ?

**Comment by pukkandan** [comment]
> Here is how subtitles look in original video playing on the website: [i.postimg.cc/2SN9QqbK/Screenshot-from-2023-02-16-16-16-31.png](https://i.postimg.cc/2SN9QqbK/Screenshot-from-2023-02-16-16-16-31.png) and here is how it is rendered by yt-dlp: [i.postimg.cc/Y01nZkT3/Screenshot-from-2023-02-16-16-13-19.png](https://i.postimg.cc/Y01nZkT3/Screenshot-from-2023-02-16-16-13-19.png) Is it possible to have the same style

It's the player that's setting the style

---



> When I specify 'writesubtitles': True in yt-dlp options in Python script, the subtitles are embedded into video ... I've just checked it.

No, it does not. Delete the file you have already downloaded, run yt-dlp again, check if it's embedded and provide verbose logs if it is

**Comment by pavel167** [comment]
Yes, it's the case.
Thanks !
