### ISSUE TITLE
How To Get A List Of Episodes Or Seasons ?

### ISSUE THREAD

**Issue by iron-heart-x** [yt-dlp/yt-dlp#6260]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.01.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Hi, Bros.
I want to get a list of Episodes and Seasons in hotstar web series.
And I want to download specific items.
How I get a list of Episodes and Seasons in hotstar?
For Example I want to get a list of  Episodes and Seasons of this series.
https://www.hotstar.com/in/tv/mahabharatham/1877

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
See --print, -j and --flat-playlist in docs

**Comment by iron-heart-x** [comment]
Ok, Thank You
