### ISSUE TITLE
error cannot extract uploader

### ISSUE THREAD

**Issue by mohammadalha** [yt-dlp/yt-dlp#6262]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [x] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2023.01.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [x] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

saudi arabia

### Provide a description that is worded well enough to be understood

i was having error when i was colorizing a video

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[youtube] Extracting URL: https://youtu.be/6Fi6Jb5rYB4
[youtube] 6Fi6Jb5rYB4: Downloading webpage
[youtube] 6Fi6Jb5rYB4: Downloading android player API JSON
ERROR: [youtube] 6Fi6Jb5rYB4: Unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
---------------------------------------------------------------------------
RegexNotFoundError                        Traceback (most recent call last)
/usr/local/lib/python3.8/dist-packages/yt_dlp/YoutubeDL.py in wrapper(self, *args, **kwargs)
   1501                 try:
-> 1502                     return func(self, *args, **kwargs)
   1503                 except (DownloadCancelled, LazyList.IndexError, PagedList.IndexError):

12 frames
RegexNotFoundError: [youtube] 6Fi6Jb5rYB4: Unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

During handling of the above exception, another exception occurred:

DownloadError                             Traceback (most recent call last)
/usr/local/lib/python3.8/dist-packages/yt_dlp/YoutubeDL.py in trouble(self, message, tb, is_error)
    950             else:
    951                 exc_info = sys.exc_info()
--> 952             raise DownloadError(message, exc_info)
    953         self._download_retcode = 1
    954 

DownloadError: ERROR: [youtube] 6Fi6Jb5rYB4: Unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

**Comment by coletdjnz** [comment]
https://github.com/yt-dlp/yt-dlp/issues/6247

**Comment by mohammadalha** [comment]
ok

**Comment by mohammadalha** [comment]
ok
