### ISSUE TITLE
revoir.tv5monde.com not supported for a very long time

### ISSUE THREAD

**Issue by forapreder** [yt-dlp/yt-dlp#6268]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2023.02.17** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Downloading from [revoir.tv5monde.com](https://revoir.tv5monde.com) has not been supported for a very long time. Will this ever be fixed?

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
Microsoft Windows [Version 10.0.19045.2604]
(c) Корпорация Майкрософт (Microsoft Corporation). Все права защищены.

Microsoft Windows [Version 10.0.19045.2604]
(c) Корпорация Майкрософт (Microsoft Corporation). Все права защищены.

C:\Users\Internet>yt-dlp -vU https://revoir.tv5monde.com/toutes-les-videos/series-fictions/marjorie-l-age-de-raison
[debug] Command-line config: ['-vU', 'https://revoir.tv5monde.com/toutes-les-videos/series-fictions/marjorie-l-age-de-raison']
[debug] Encodings: locale cp1251, fs utf-8, pref cp1251, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2023.02.17 [a0a7c01] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 5.1.2-full_build-www.gyan.dev (setts)
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1782 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2023.02.17, Current version: 2023.02.17
yt-dlp is up to date (2023.02.17)
[TV5MondePlus] Extracting URL: https://revoir.tv5monde.com/toutes-les-videos/series-fictions/marjorie-l-age-de-raison
[TV5MondePlus] marjorie-l-age-de-raison: Downloading webpage
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 1956d125-5a52-4247-4f3a-63e5bf07b015: Downloading 1 format(s): unknown_video
[debug] Invoking http downloader on "tap:mgd:prd:106304847?application=revoir"
[download] Got error: <urlopen error unknown url type: tap>. Retrying (1/10)...
[download] Got error: <urlopen error unknown url type: tap>. Retrying (2/10)...
[download] Got error: <urlopen error unknown url type: tap>. Retrying (3/10)...
[download] Got error: <urlopen error unknown url type: tap>. Retrying (4/10)...
[download] Got error: <urlopen error unknown url type: tap>. Retrying (5/10)...
[download] Got error: <urlopen error unknown url type: tap>. Retrying (6/10)...
[download] Got error: <urlopen error unknown url type: tap>. Retrying (7/10)...
[download] Got error: <urlopen error unknown url type: tap>. Retrying (8/10)...
[download] Got error: <urlopen error unknown url type: tap>. Retrying (9/10)...
[download] Got error: <urlopen error unknown url type: tap>. Retrying (10/10)...
[download] Got error: <urlopen error unknown url type: tap>. Giving up after 10 retries
  File "yt_dlp\__main__.py", line 17, in <module>
  File "yt_dlp\__init__.py", line 967, in main
  File "yt_dlp\__init__.py", line 957, in _real_main
  File "yt_dlp\YoutubeDL.py", line 3353, in download
  File "yt_dlp\YoutubeDL.py", line 3328, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1491, in extract_info
  File "yt_dlp\YoutubeDL.py", line 1502, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1599, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1658, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2763, in process_video_result
  File "yt_dlp\YoutubeDL.py", line 3231, in process_info
  File "yt_dlp\YoutubeDL.py", line 2954, in dl
  File "yt_dlp\downloader\common.py", line 444, in download
  File "yt_dlp\downloader\http.py", line 374, in real_download
  File "yt_dlp\utils.py", line 6109, in __iter__
  File "yt_dlp\downloader\common.py", line 389, in report_retry
  File "yt_dlp\utils.py", line 6116, in report_retry
  File "yt_dlp\downloader\common.py", line 392, in <lambda>
  File "yt_dlp\YoutubeDL.py", line 1012, in report_error
  File "yt_dlp\YoutubeDL.py", line 941, in trouble
```

**Comment by forapreder** [comment]
Microsoft Windows [Version 10.0.19045.2604]
(c) Корпорация Майкрософт (Microsoft Corporation). Все права защищены.

C:\Users\Internet>yt-dlp -vU https://revoir.tv5monde.com/toutes-les-videos/series-fictions/marjorie-l-age-de-raison
[debug] Command-line config: ['-vU', 'https://revoir.tv5monde.com/toutes-les-videos/series-fictions/marjorie-l-age-de-raison']
[debug] Encodings: locale cp1251, fs utf-8, pref cp1251, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2023.02.17 [a0a7c01] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 5.1.2-full_build-www.gyan.dev (setts)
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1782 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2023.02.17, Current version: 2023.02.17
yt-dlp is up to date (2023.02.17)
[TV5MondePlus] Extracting URL: https://revoir.tv5monde.com/toutes-les-videos/series-fictions/marjorie-l-age-de-raison
[TV5MondePlus] marjorie-l-age-de-raison: Downloading webpage
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 1956d125-5a52-4247-4f3a-63e5bf07b015: Downloading 1 format(s): unknown_video
[debug] Invoking http downloader on "tap:mgd:prd:106304847?application=revoir"
[download] Got error: <urlopen error unknown url type: tap>. Retrying (1/10)...
[download] Got error: <urlopen error unknown url type: tap>. Retrying (2/10)...
[download] Got error: <urlopen error unknown url type: tap>. Retrying (3/10)...
[download] Got error: <urlopen error unknown url type: tap>. Retrying (4/10)...
[download] Got error: <urlopen error unknown url type: tap>. Retrying (5/10)...
[download] Got error: <urlopen error unknown url type: tap>. Retrying (6/10)...
[download] Got error: <urlopen error unknown url type: tap>. Retrying (7/10)...
[download] Got error: <urlopen error unknown url type: tap>. Retrying (8/10)...
[download] Got error: <urlopen error unknown url type: tap>. Retrying (9/10)...
[download] Got error: <urlopen error unknown url type: tap>. Retrying (10/10)...
[download] Got error: <urlopen error unknown url type: tap>. Giving up after 10 retries
  File "yt_dlp\__main__.py", line 17, in <module>
  File "yt_dlp\__init__.py", line 967, in main
  File "yt_dlp\__init__.py", line 957, in _real_main
  File "yt_dlp\YoutubeDL.py", line 3353, in download
  File "yt_dlp\YoutubeDL.py", line 3328, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1491, in extract_info
  File "yt_dlp\YoutubeDL.py", line 1502, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1599, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1658, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2763, in process_video_result
  File "yt_dlp\YoutubeDL.py", line 3231, in process_info
  File "yt_dlp\YoutubeDL.py", line 2954, in dl
  File "yt_dlp\downloader\common.py", line 444, in download
  File "yt_dlp\downloader\http.py", line 374, in real_download
  File "yt_dlp\utils.py", line 6109, in __iter__
  File "yt_dlp\downloader\common.py", line 389, in report_retry
  File "yt_dlp\utils.py", line 6116, in report_retry
  File "yt_dlp\downloader\common.py", line 392, in <lambda>
  File "yt_dlp\YoutubeDL.py", line 1012, in report_error
  File "yt_dlp\YoutubeDL.py", line 941, in trouble

**Comment by pukkandan** [comment]
https://github.com/yt-dlp/yt-dlp/issues/4978 was locked because you kept spamming. Opening duplicates isn't helping
