### ISSUE TITLE
yt-dlp seems to download whole video, instead of specified part.

### ISSUE THREAD

**Issue by rafaleo** [yt-dlp/yt-dlp#6273]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2023.02.17** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Hi. I found `yt-dlp` works in unexpected way while downloading a part of video. The below link uses `ffmpeg` to cut 2 second fragment from video.
```
yt-dlp -i https://www.youtube.com/watch?v=JS4itxO3G7Q --external-downloader ffmpeg --external-downloader-args "-ss 00:47:36 -t 00:02" -o "c:\Users\cp\Downloads\NET\x.mp4"
```
Literally, the program is not searching for that fragment, but instead, it buffers everything up to that place (downloads all fragments preceding). So, when I need some ending fragment, I need to wait. In contrast, `youtube-dl` works as expected - despite it downloads slower overall, it jumps to desired time, so downloading 2 seconds from the end is immediate. It applies to most videos, maybe everyone; it's good when you search for the beginning parts, but not ending.

When I see the time or current frame, it shows zeros - in contrast, `youtube-dl` shows correct time:
```
frame=    0 fps=0.0 q=-1.0 Lsize=       1kB time=00:00:00.00 bitrate=N/A speed=   0x
```
If I pause the process and resume it, internet usage chart shows the difference in downloading speed.

The issue I observed long time ago, but now I just mention it. Can you fix this please? Do you need more info?
Finally, the part is there, on disk, but the waiting time and transfer consumed may be dramatic,.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '-i', 'https://www.youtube.com/watch?v=JS4itxO3G7Q', '--external-downloader', 'ffmpeg', '--external-downloader-args', '-ss
00:47:36 -t 00:02', '-o', 'c:\\Users\\cp\\Downloads\\NET\\x1.mp4']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8 (No VT), error utf-8 (No VT), screen utf-8 (No VT)
[debug] yt-dlp version 2023.02.17 [a0a7c01] (pip)
[debug] Python 3.7.4 (CPython AMD64 64bit) - Windows-7-6.1.7601-SP1 (OpenSSL 1.1.1d  10 Sep 2019)
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1
[debug] Optional libraries: Cryptodome-3.12.0, brotlicffi-1.0.9.2, certifi-2019.09.11, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.1
[debug] Proxy map: {}
WARNING: External Downloader arguments given without specifying name. The arguments will be given to ffmpeg
[debug] Loaded 1782 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2023.02.17, Current version: 2023.02.17
yt-dlp is up to date (2023.02.17)
```

**Comment by pukkandan** [comment]
That is correct behavior given the options you are passing due to how ffmpeg's input and output arguments work. See https://github.com/yt-dlp/yt-dlp/issues/686 for discussion.

But yt-dlp now has built-in option `--downloaad-sections`. So why are u manually passing args?
