### ISSUE TITLE
Youtube subtitles duplicated 

### ISSUE THREAD

**Issue by matheustanaka** [yt-dlp/yt-dlp#6274]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.02.17** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I'm trying to download youtube subtitles, but it seems that subs are being duplicated during extraction

Duplicate example below:
![image](https://user-images.githubusercontent.com/59452094/219813039-57e0e747-fcd7-44a6-a1e9-b81fda715970.png)

I converted the format to .srt but even if I use .vtt format, they will be duplicated.

I would like to know if it's possible to extract the subtitles without duplicate them, if we compare yt-dlp extraction with other websites like [downsub](https://downsub.com/), you will see downsub didn't duplicate .

There's some way to solve it? Do you know what downsub uses to extract subtitles without duplicating them?

Expected result:
![image](https://user-images.githubusercontent.com/59452094/219813706-9adef3fa-5b18-42ef-a16f-712fc5b350eb.png)

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp --write-auto-sub --sub-lang en -S ext:mp4:m4a https://www.youtube.com/watch\?v\=TTjYjSEGHek\&ab_channel\=ThePrimeagen
[youtube] Extracting URL: https://www.youtube.com/watch?v=TTjYjSEGHek&ab_channel=ThePrimeagen
[youtube] TTjYjSEGHek: Downloading webpage
[youtube] TTjYjSEGHek: Downloading android player API JSON
[info] TTjYjSEGHek: Downloading subtitles: en
[info] TTjYjSEGHek: Downloading 1 format(s): 137+140
[info] Writing video subtitles to: JSON, I hardly know 'er [TTjYjSEGHek].en.vtt
[download] Destination: JSON, I hardly know 'er [TTjYjSEGHek].en.vtt
[download] 100% of   24.77KiB in 00:00:00 at 145.18KiB/s
[download] Destination: JSON, I hardly know 'er [TTjYjSEGHek].f137.mp4
[download] 100% of    7.72MiB in 00:00:00 at 15.15MiB/s
[download] Destination: JSON, I hardly know 'er [TTjYjSEGHek].f140.m4a
[download] 100% of    2.66MiB in 00:00:00 at 11.40MiB/s
[Merger] Merging formats into "JSON, I hardly know 'er [TTjYjSEGHek].mp4"
Deleting original file JSON, I hardly know 'er [TTjYjSEGHek].f140.m4a (pass -k to keep)
Deleting original file JSON, I hardly know 'er [TTjYjSEGHek].f137.mp4 (pass -k to keep)
```

**Comment by pboettcher** [comment]
This is a long known issue and as I understabd, nobody is going to fix it. They always say, it it YouTube who duplicates subtitles, although I can download subtitles manually using browser debug console and finding out an appropriate URL, and these subtitles are not duplicated.

**Comment by matheustanaka** [comment]
I didn't know about it. I also tried to extract directly with ffmpeg but it doesn't work, I know that is possible to use browser debug but with my app I will need to make a over-engineering to handle with subtitles. 

Thank you for your answer!

**Comment by pukkandan** [comment]
https://github.com/yt-dlp/yt-dlp/issues/1734
