### ISSUE TITLE
Can Not Upgrade With Package Manager or Apt

### ISSUE THREAD

**Issue by caltrop2075** [yt-dlp/yt-dlp#6280]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2023.02.17** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

can not upgrade using package manager

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp
---------------------------------------
system

        OS   Linux Mint 20.1 ulyssa
    Kernel   GNU/Linux 5.4.0-139-generic x86_64
Kernel ver   #156-Ubuntu SMP Fri Jan 20 17:27:18 UTC 2023
   Desktop   MATE Desktop Environment 1.24.0
      Bash   5.0.17(1)-release x86_64-pc-linux-gnu

---------------------------------------
command line

$ yt-dlp -vU
[debug] Command-line config: ['-vU']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.03.08.1 [c0c2c57d3]
[debug] Python version 3.8.10 (CPython 64bit) - Linux-5.4.0-139-generic-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.7, ffprobe 4.2.7, rtmpdump 2.4
[debug] Optional libraries: brotli, Cryptodome, secretstorage, mutagen, sqlite, websockets
[debug] Proxy map: {}
Usage: yt-dlp [OPTIONS] URL [URL...]

yt-dlp: error: yt-dlp's self-update mechanism is disabled on Debian.
Please update yt-dlp using apt(8).
See https://packages.debian.org/sid/yt-dlp for the latest packaged version.



$ sudo add-apt-repository ppa:yt-dlp/stable
[sudo] password for caltrop:
Cannot add PPA: ''This PPA does not support focal''.


---------------------------------------
linux mint synaptic

ppa:yt-dlp/stable
this PPA does not support focal

---------------------------------------
```

**Comment by Grub4K** [comment]
External packages are not maintained by us. Please file an issue with their respective issue trackers. Does `sudo apt install yt-dlp` not work for you?

**Comment by caltrop2075** [comment]
not a repository issue

trying to install from YT-DLP SITE

synaptic package manager is already SUDO
will not accept YT-DLP PPA, as stated above

**Comment by Lesmiscore** [comment]
We don't provide package files for package managers...
![image](https://user-images.githubusercontent.com/10355528/220390989-59298e92-f6d2-47bc-bb04-413f01400784.png)

**Comment by caltrop2075** [comment]
why is not APT working with the PPA?

synaptic is just a GUI for APT

**Comment by pukkandan** [comment]
https://github.com/yt-dlp/yt-dlp/wiki/FAQ#the-yt-dlp-in-my-package-manager-is-outdatedbroken
