### ISSUE TITLE
yt-dlp 2023.02.17 broke my app

### ISSUE THREAD

**Issue by Catishere** [yt-dlp/yt-dlp#6282]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2023.02.17** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

The app doesnt work since this version

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
.\yt-dlp.exe  -x --extract-audio --audio-format wav "ytsearch: shaboom the chords" --ppa "ffmpeg: -bitexact -ac 1 -ab 352k -ar 22050" --verbose
[debug] Command-line config: ['-x', '--extract-audio', '--audio-format', 'wav', 'ytsearch: shaboom the chords', '--ppa', 'ffmpeg: -bitexact -ac 1 -ab 352k -ar 22050', '--verbose']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, err utf-8, pref cp1252
[debug] yt-dlp version 2022.01.21 [f20d607] (win_exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19044-SP0
[debug] exe versions: ffmpeg 4.0.2, ffprobe 4.0.2
[debug] Optional libraries: Cryptodome, mutagen, sqlite, websockets
[debug] Proxy map: {}
[debug] [youtube:search] Extracting URL: ytsearch: shaboom the chords
[download] Downloading playlist:  shaboom the chords
[youtube:search] query " shaboom the chords" page 1: Downloading API JSON
[youtube:search] playlist  shaboom the chords: Downloading 1 videos
[download] Downloading video 1 of 1
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=SBgQezOF8kY
[youtube] SBgQezOF8kY: Downloading webpage
[youtube] SBgQezOF8kY: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, codec:vp9.2, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
ERROR: [youtube] SBgQezOF8kY: Unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
  File "yt_dlp\extractor\common.py", line 612, in extract
  File "yt_dlp\extractor\youtube.py", line 3331, in _real_extract
  File "yt_dlp\extractor\common.py", line 1186, in _search_regex

[download] Finished downloading playlist:  shaboom the chords
```

**Comment by bashonly** [comment]
> [debug] yt-dlp version 2022.01.21 [f20d607] (win_exe)

that is not 2023.02.17
