### ISSUE TITLE
Any Video Converter Ultimate is NOT downloading YouTube videos

### ISSUE THREAD

**Issue by RandoNerd2023** [yt-dlp/yt-dlp#6285]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2023.02.17** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Canada

### Provide a description that is worded well enough to be understood

I'm attempting to download videos off of YouTube with Any Video Converter Ultimate and it was working perfectly fine up until a few days ago when suddenly it wouldn't work and all I got was "Analyzing failed" and "Unable to extract uploader id".

When I try to download literally anywhere else such as Instagram and DailyMotion it works perfectly fine, but for YouTube it still DOESN'T work.

I've tried uninstalling and restarting and reinstalling the program on my Windows PC and I've tried Python as best as I can as well but it still doesn't work (issuing commands, attempting to use yt-dlp, etc).

I'm a simple video editor and I know very little about this command code mumbo jumbo, I'm trying to get this program fixed so I can download and get footage to use in my videos so can someone PLEASE tell me what the heck to do to get this fixed?

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
python3 -m pip install -U pip setuptools wheel
python3 -m pip install --force-reinstall https://github.com/yt-dlp/yt-dlp/archive/master.tar.gz
```

**Comment by Lesmiscore** [comment]
Okay.

**Comment by RandoNerd2023** [comment]
> 

It told me to report it here though. Gave me a site link and everything.

**Comment by pukkandan** [comment]
They must be using yt-dlp in it's backend. But unless you are directly using yt-dlp, report to them

**Comment by gamer191** [comment]
> It told me to report it here though. Gave me a site link and everything.

Tell them to update their yt-dlp version, since every version of yt-dlp, except the latest version, is broken
