### ISSUE TITLE
[youtube:tab] recommended: Unable to recognize tab page

### ISSUE THREAD

**Issue by iBicha** [yt-dlp/yt-dlp#6289]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2023.02.17** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Reading home page works, but reading home page with cookies does not.
This works
```
yt-dlp -vU https://www.youtube.com --flat-playlist --lazy-playlist --print '%(id)s'
```
And this doesn't
```
yt-dlp -vU https://www.youtube.com --flat-playlist --lazy-playlist --print '%(id)s' --cookies-from-browser chrome
```

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.youtube.com', '--flat-playlist', '--lazy-playlist', '--print', '%(id)s', '--cookies-from-browser', 'chrome']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2023.02.17 [a0a7c01] (pip)
[debug] Python 3.11.2 (CPython x86_64 64bit) - macOS-12.6.2-x86_64-i386-64bit (OpenSSL 1.1.1t  7 Feb 2023)
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[Cookies] Extracting cookies from chrome
[debug] Extracting cookies from: "/Users/brahim/Library/Application Support/Google/Chrome/Default/Cookies"
[debug] using find-generic-password to obtain password from OSX keychain
[Cookies] Extracted 3189 cookies from chrome
[debug] cookie version breakdown: {'v10': 3168, 'other': 0, 'unencrypted': 21}
[debug] Proxy map: {}
[debug] Loaded 1782 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2023.02.17, Current version: 2023.02.17
yt-dlp is up to date (2023.02.17)
[youtube:recommended] Extracting URL: https://www.youtube.com
[youtube:tab] Extracting URL: https://www.youtube.com/feed/recommended
[youtube:tab] recommended: Downloading webpage
WARNING: [youtube:tab] Incomplete yt initial data received. Retrying (1/3)...
[youtube:tab] recommended: Downloading webpage
WARNING: [youtube:tab] Incomplete yt initial data received. Retrying (2/3)...
[youtube:tab] recommended: Downloading webpage
WARNING: [youtube:tab] Incomplete yt initial data received. Retrying (3/3)...
[youtube:tab] recommended: Downloading webpage
WARNING: [youtube:tab] Incomplete yt initial data received; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U. Giving up after 3 retries
ERROR: [youtube:tab] recommended: Unable to recognize tab page; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/usr/local/Cellar/yt-dlp/2023.2.17/libexec/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 693, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/yt-dlp/2023.2.17/libexec/lib/python3.11/site-packages/yt_dlp/extractor/youtube.py", line 4454, in wrapper
    info_dict = func(self, url, smuggled_data)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/yt-dlp/2023.2.17/libexec/lib/python3.11/site-packages/yt_dlp/extractor/youtube.py", line 6305, in _real_extract
    raise ExtractorError('Unable to recognize tab page')
```

**Comment by pukkandan** [comment]
I can't repro. Could you add `--dump-pages` and attach the resulting `.dump` files?

**Comment by iBicha** [comment]
```
yt-dlp -vU https://www.youtube.com --flat-playlist --lazy-playlist --print '%(id)s' --cookies-from-browser chrome --write-pages --dump-pages 2> page-dumps
```
[Archive.zip](https://github.com/yt-dlp/yt-dlp/files/10777378/Archive.zip)

**Comment by coletdjnz** [comment]
Pretty sure this is supposed to fallback to the API.

Seems like YouTube is not giving the full browse response as part of the webpage and getting it from the API after the fact.  We've seen it before but taking we never implemented support for it.

```
window['ytCommand'] = {"clickTrackingParams":"XXX","commandMetadata":{"webCommandMetadata":{"url":"/","webPageType":"WEB_PAGE_TYPE_BROWSE","rootVe":3854,"apiUrl":"/youtubei/v1/browse"}},"browseEndpoint":{"browseId":"FEwhat_to_watch"}}
```

```
var ytInitialData = {"responseContext":{"webResponseContextExtensionData":{"ytConfigData":{"visitorData":"XXX%3D%3D","sessionIndex":0,"rootVisualElementType":3854}}}}
```

**Comment by tzarebczan** [comment]
Here's another scenario where we get incomplete data received, but then it returns a few video ids. Can we safely ignore, or does it need a patch?

```
yt-dlp --skip-download https://www.youtube.com/channel/UCI197iM3KpFWEqef07Owfbw/streams --get-id --flat-playlist
```

**Comment by pukkandan** [comment]
See how it keeps loading infinitely on the webpage. 
![image](https://user-images.githubusercontent.com/6623388/230617630-c3b9bb60-0fa0-4f28-80a3-d076aaee0f90.png)

That is what causes the "incomplete data" error. It is issue on youtube's side and we can't do anything. The video ids yt-dlp returns are whatever is above that point.
