### ISSUE TITLE
[youtube] comments downloader goes into a loop, never stops on some videos

### ISSUE THREAD

**Issue by ivan** [yt-dlp/yt-dlp#6290]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2023.02.17** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

With `yt-dlp --write-comments` on https://www.youtube.com/watch?v=kOHXmlRaTqU (which has just a few hundred comments), yt-dlp goes into some kind of download loop and never stops downloading comments.

I noticed that this also happened with https://www.youtube.com/watch?v=6u2IcdAE2ms and https://www.youtube.com/watch?v=XZqRYNbdB0g earlier, but now it does not, so it may stop happening on https://www.youtube.com/watch?v=kOHXmlRaTqU as the comments thread or YouTube's caches are updated.

This could be fixed by detecting whatever condition is causing it to loop, or by stopping when the number of comments downloaded far exceeds the estimated number of comments.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-v', '--write-comments', 'https://www.youtube.com/watch?v=kOHXmlRaTqU']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2023.02.17 [a0a7c0154] (source)
[debug] Lazy loading extractors is disabled
[debug] Git HEAD: 18d295c9e
[debug] Python 3.10.9 (CPython x86_64 64bit) - Linux-5.15.93-x86_64-with-glibc2.35 (OpenSSL 3.0.8 7 Feb 2023, glibc 2.35)
[debug] exe versions: ffmpeg 5.1.2 (fdk,setts), ffprobe 5.1.2
[debug] Optional libraries: sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Loaded 1782 extractors
[youtube] Extracting URL: https://www.youtube.com/watch?v=kOHXmlRaTqU
[youtube] kOHXmlRaTqU: Downloading webpage
[youtube] kOHXmlRaTqU: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[youtube] Downloading comment section API JSON
[youtube] Downloading ~219 comments
[youtube] Sorting comments by newest first
[youtube] Downloading comment API JSON page 1 (0/219)
[youtube] Downloading comment API JSON page 2 (20/219)
[youtube] Downloading comment API JSON page 3 (39/219)
[youtube]     Downloading comment API JSON reply thread 1 (52/219)
[youtube] Downloading comment API JSON page 4 (57/219)
[youtube] Downloading comment API JSON page 5 (57/219)
[youtube] Downloading comment API JSON page 6 (77/219)
[youtube] Downloading comment API JSON page 7 (96/219)
[youtube]     Downloading comment API JSON reply thread 1 (109/219)
[youtube] Downloading comment API JSON page 8 (114/219)
[youtube] Downloading comment API JSON page 9 (114/219)
[youtube] Downloading comment API JSON page 10 (134/219)
[youtube] Downloading comment API JSON page 11 (153/219)

[...]

[youtube]     Downloading comment API JSON reply thread 1 (316220/219)
[youtube] Downloading comment API JSON page 25520 (316225/219)
[youtube] Downloading comment API JSON page 25521 (316225/219)
```

**Comment by pukkandan** [comment]
Workaround, press `ctrl+c` to stop comment extraction

**Comment by coletdjnz** [comment]
Seems to be a youtube issue but we'll try to workaround it.

There's only 78 unique comments being extracted from kOHXmlRaTqU even though it says there is 241 est. comments.
