### ISSUE TITLE
Can't update from -U

### ISSUE THREAD

**Issue by rmbeer** [yt-dlp/yt-dlp#6293]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2023.02.17** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

give error from -U

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
$ ./yt-dlp -vU
[debug] Command-line config: ['-vU']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.09.01 [5d7c7d656] (linux_exe)
[debug] Python 3.10.5 (CPython 32bit) - Linux-5.15.44-1.1-lts-i686-with-glibc2.35 (glibc 2.35)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 5.0 (setts), ffprobe 5.0
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1674 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2023.02.17, Current version: 2022.09.01
[debug] Downloading _update_spec from https://github.com/yt-dlp/yt-dlp/releases/download/2023.02.17/_update_spec
Current Build Hash 289d9c344860842795041cf93cfe53d21d962e632374282265b9f2bd1ce92da3
Updating to version 2023.02.17 ...
ERROR: Unable to fetch updates; Visit  https://github.com/yt-dlp/yt-dlp/releases/latest
```

**Comment by pukkandan** [comment]
Pls try again. And verify that it's not a network issue

```
❯ "D:\TRASH\Downloads\yt-dlp (2).exe" --ignore-config -vU
[debug] Command-line config: ['--ignore-config', '-vU']
[debug] Encodings: locale cp65001, fs utf-8, pref cp65001, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.09.01 [5d7c7d6] (win32_exe)
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.22000-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg n5.1.2-8-g5746987bad-20221204 (fdk,setts), ffprobe N-109332-g45ab5307a6-20221201, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1670 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2023.02.17, Current version: 2022.09.01
[debug] Downloading _update_spec from https://github.com/yt-dlp/yt-dlp/releases/download/2023.02.17/_update_spec
Current Build Hash fc932a7478e536945895185abe529ad94d2385862df6e1b41fb970568dce7f7a
Updating to version 2023.02.17 ...
[debug] Downloading yt-dlp.exe from https://github.com/yt-dlp/yt-dlp/releases/download/2023.02.17/yt-dlp.exe
[debug] Downloading SHA2-256SUMS from https://github.com/yt-dlp/yt-dlp/releases/download/2023.02.17/SHA2-256SUMS
Updated yt-dlp to version 2023.02.17
```

**Comment by bashonly** [comment]
Can't reproduce the issue with yt-dlp_linux 2022.09.01 downloaded from github
```
[debug] Command-line config: ['-vU']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8 (No ANSI), error utf-8 (No ANSI), screen utf-8 (No ANSI)
[debug] yt-dlp version 2022.09.01 [5d7c7d6] (linux_exe)
[debug] Python 3.10.5 (CPython 64bit) - Linux-5.10.0-20-amd64-x86_64-with-glibc2.31 (glibc 2.31)
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg 4.3.5-0, ffprobe 4.3.5-0
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, secretstorage-3.3.3, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1670 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2023.02.17, Current version: 2022.09.01
[debug] Downloading _update_spec from https://github.com/yt-dlp/yt-dlp/releases/download/2023.02.17/_update_spec
Current Build Hash 2929d03b1c7abc575d2d0656312868e2dac59ef10435c332d9541537377eb181
Updating to version 2023.02.17 ...
[debug] Downloading yt-dlp_linux from https://github.com/yt-dlp/yt-dlp/releases/download/2023.02.17/yt-dlp_linux
[debug] Downloading SHA2-256SUMS from https://github.com/yt-dlp/yt-dlp/releases/download/2023.02.17/SHA2-256SUMS
Updated yt-dlp to version 2023.02.17
```

**Comment by pukkandan** [comment]
> ```shell
> 
> Current Build Hash 289d9c344860842795041cf93cfe53d21d962e632374282265b9f2bd1ce92da3
> ```

This doesn't match the expected value, which means the build you are using is not a release made by us. Did you build it yourself? If so, you'll need to provide your compilation steps to reproduce

**Comment by gamer191** [comment]
This may be a dumb question, but isn't the update command supposed to be run using sudo?

**Comment by rmbeer** [comment]
yes, it's compiled with source of github, from https://github.com/yt-dlp/yt-dlp
i don't remeber the exactly steps, but is from pip sequence command:

## COMPILE

### Standalone PyInstaller Builds
To build the standalone executable, you must have Python and `pyinstaller` (plus any of yt-dlp's [optional dependencies](#dependencies) if needed). Once you have all the necessary dependencies installed, simply run `pyinst.py`. The executable will be built for the same architecture (x86/ARM, 32/64 bit) as the Python used.

    python3 -m pip install -U pyinstaller -r requirements.txt
    python3 devscripts/make_lazy_extractors.py
    python3 pyinst.py

and i use the yt-dlp builded.

**Comment by bashonly** [comment]
I think I've found why this was happening. Note that OP built with 32-bit python:

> [debug] Python 3.10.5 (CPython ***32bit***) - Linux-5.15.44-1.1-lts-i686-with-glibc2.35 (glibc 2.35)

Here's where the updater is raising (`'fetch updates'`):
https://github.com/yt-dlp/yt-dlp/blob/da4db748fa813a8de684d5ab699b8f561b982e35/yt_dlp/update.py#L226-L231

First let's look at `release_name()`:
https://github.com/yt-dlp/yt-dlp/blob/da4db748fa813a8de684d5ab699b8f561b982e35/yt_dlp/update.py#L161-L164

Then the code path of `_FILE_SUFFIXES[detect_variant()] `:
https://github.com/yt-dlp/yt-dlp/blob/da4db748fa813a8de684d5ab699b8f561b982e35/yt_dlp/update.py#L51-L52
https://github.com/yt-dlp/yt-dlp/blob/da4db748fa813a8de684d5ab699b8f561b982e35/yt_dlp/update.py#L29-L40
https://github.com/yt-dlp/yt-dlp/blob/da4db748fa813a8de684d5ab699b8f561b982e35/yt_dlp/update.py#L68-L75

So we end up with `_linux`. But then looking at the rest of `release_name()`, we can see it returns `yt-dlp_x86_linux` instead of `yt-dlp_linux` because of the 32-bit build:
https://github.com/yt-dlp/yt-dlp/blob/da4db748fa813a8de684d5ab699b8f561b982e35/yt_dlp/update.py#L161-L167

Then in `_download()`, the traversal filters for `yt-dlp_x86_linux` in the JSON response, and since we do not offer 32-bit x86 linux builds, it returns `None`, which raises the `Exception` here (and is caught by `except Exception` from the first code block I posted):
https://github.com/yt-dlp/yt-dlp/blob/da4db748fa813a8de684d5ab699b8f561b982e35/yt_dlp/update.py#L153-L159

And although the updater code has changed since 2022.09.01, this problem still exists. A 32-bit x86 linux build will raise a `KeyError` in master (which will similarly be caught and raised as `Unable to fetch updates`). @pukkandan is this something we should fix in #6220 by raising a more appropriate error?

**Comment by pukkandan** [comment]
> . @pukkandan is this something we should fix in #6220 by raising a more appropriate error?

Sure, but idk if it's in scope of that PR. I could fix it separately if that's more convenient.  Let me know

**Comment by bashonly** [comment]
> Sure, but idk if it's in scope of that PR. I could fix it separately if that's more convenient. Let me know

Something like this could be a simple addition to the PR:
```diff
diff --git a/yt_dlp/update.py b/yt_dlp/update.py
index d36137d08..0f1e9a24f 100644
--- a/yt_dlp/update.py
+++ b/yt_dlp/update.py
@@ -210,7 +210,11 @@ def _download(self, name, tag):
     @functools.cached_property
     def release_name(self):
         """The release filename"""
-        return f'yt-dlp{_FILE_SUFFIXES[detect_variant()]}'
+        variant = detect_variant()
+        label = _FILE_SUFFIXES.get(variant)
+        if not label:
+            raise Exception(f'{variant} builds are not available')
+        return f'yt-dlp{label}'
 
     @functools.cached_property
     def release_hash(self):
@@ -274,8 +278,8 @@ def update(self):
             newcontent = self._download(self.release_name, self._tag)
         except OSError:
             return self._report_network_error('download latest version')
-        except Exception:
-            return self._report_network_error('fetch updates')
+        except Exception as err:
+            return self._report_network_error(f'fetch updates: {err}')
 
         try:
             expected_hash = self.release_hash
```
so a 32bit x86 linux build would get an error message like this:
`ERROR: Unable to fetch updates: linux_x86_exe builds are not available; Visit  https://github.com/yt-dlp/yt-dlp/releases/latest`

**Comment by pukkandan** [comment]
> A 32-bit x86 linux build will raise a `KeyError` in master (which will similarly be caught and raised as `Unable to fetch updates`)

No, @bashonly . Since 17fc3dc48af968e28c23197ed06542fdb47aba2b, 32bit linux exe will be correctly labeled as `linux_x86_exe` and raises `You are using an unofficial build of yt-dlp; Build the executable again` from `is_non_updateable`
