### ISSUE TITLE
Rejecting titles from a playlist or channel causes EntryNotInPlaylist error when using extract_info and process_ie_result

### ISSUE THREAD

**Issue by zxjinn** [yt-dlp/yt-dlp#6296]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2023.02.17** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Description (though the code below probably gives a better explanation):

I am using yt-dlp via the 'embedded' method in Python

- Select a YouTube channel or playlist to download from
- Use the `extract_info` function with the flag `download=False`
- In the options dict reject one or more of the videos in the playlist with `rejecttitle` option
- Try to download with `process_ie_result` using input from the `extract_info`'s output
- an error about not being able to find the next correct entry, no downloads start

See code for a short example of how to replicate the problem:
```python
import yt_dlp

ydl_opts = {
  'rejecttitle': 'bone',
  'playlist_items': '1-3'
}
ydl = yt_dlp.YoutubeDL(ydl_opts)

# a youtube channel OR a playlist both don't work
url = 'https://www.youtube.com/@Netflix/videos'

pre_info = ydl.extract_info(url, download=False)

post_info = ydl.process_ie_result(pre_info, download=True)
```

Not sure that all of this matters, but here is some info about the system running that code:
``` shell
$ python --version
Python 3.10.10
$ pip list | grep yt-dlp
yt-dlp             2023.2.17
$ cat /etc/os-release | grep PRETTY
PRETTY_NAME="Alpine Linux v3.17"
```

I also confirmed the same problem is exhibited on an Ubuntu 22.04 machine.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[youtube:tab] Extracting URL: https://www.youtube.com/@Netflix/videos
[youtube:tab] @Netflix/videos: Downloading webpage
[download] Downloading playlist: Netflix - Videos
[youtube:tab] Playlist Netflix - Videos: Downloading 3 items
[download] Downloading item 1 of 3
[youtube] Extracting URL: https://www.youtube.com/watch?v=LnvcIAINqHo
[youtube] LnvcIAINqHo: Downloading webpage
[youtube] LnvcIAINqHo: Downloading android player API JSON
[download] "Shadow and Bone: Season 2 | Official Trailer | Netflix" title matched reject pattern "bone"
[download] Downloading item 3 of 3
[youtube] Extracting URL: https://www.youtube.com/watch?v=tf3Y3R_eo5w
[youtube] tf3Y3R_eo5w: Downloading webpage
[youtube] tf3Y3R_eo5w: Downloading android player API JSON
[download] Finished downloading playlist: Netflix - Videos
[download] Downloading playlist: Netflix - Videos
Traceback (most recent call last):
  File "/code/bug-process_ie_resultp.py", line 14, in <module>
    post_info = ydl.process_ie_result(pre_info, download=True)
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1728, in process_ie_result
    return self.__process_playlist(ie_result, download)
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1803, in __process_playlist
    entries = resolved_entries = list(entries)
  File "/usr/lib/python3.10/site-packages/yt_dlp/utils.py", line 788, in _iter
    for x in iterable:
  File "/usr/lib/python3.10/site-packages/yt_dlp/utils.py", line 3017, in get_requested_items
    for i, entry in self[index]:
  File "/usr/lib/python3.10/site-packages/yt_dlp/utils.py", line 3077, in __getitem__
    entry = self._getter(i)
  File "/usr/lib/python3.10/site-packages/yt_dlp/utils.py", line 3045, in get_entry
    raise EntryNotInPlaylist(f'Entry {i + 1} cannot be found')
yt_dlp.utils.EntryNotInPlaylist: Entry 2 cannot be found
```

**Comment by pukkandan** [comment]
> pre_info = ydl.extract_info(url, download=False)

This step has already processed the result. Perhaps you meant `process=False`?

**Comment by zxjinn** [comment]
Thanks for your reply @pukkandan.

The reason I was using the `extract_info` then later downloading using `process_ie_result` was because I want to manipulate the `pre_info` dict generated by `extract_info` before passing it to the `process_ie_result` function.

I realize that's probably not a "supported" operation, but in the original code example given I am not manipulating the `pre_info` dict at all. The `extract_info` function, in conjunction with the `rejecttitle` option is doing some manipulation to make the `pre_info` dict no longer valid all by itself. That's where I think an actual bug lies.

---

I tried your suggestion of using `extract_info` with `download=False` and `process=False` and that doesn't solve the particular problem I am looking at (I need the contents of `entries`, which when `process=False` the `entries` list is just an object that looks like this:
```
"entries": "<generator object YoutubeTabBaseInfoExtractor._entries at 0x7efdc826f220>",
```
Which doesn't work for what I am trying to do. **However**, after digging around the code some more I think I found a more native way to accomplish the manipulation I was trying, by twisting `match_filter` into ways I hadn't tried before. I'll keep going down that path.

Regardless, I still think I've ran into a, probably not that important, bug.

**Comment by pukkandan** [comment]
> The reason I was using the `extract_info` then later downloading using `process_ie_result` was because I want to manipulate the `pre_info` dict generated by `extract_info` before passing it to the `process_ie_result` function.

That is a supported use, but that's not what u were doing. By using `process=True`, you were trying to process the infodict twice, which is not supported since infodict before and after processing have slightly different constraints on them.

---

If you want to modify the infodict before download, a registering pre-processor is probably what you want. If you explain your exact use case, I can help more

**Comment by zxjinn** [comment]
> since infodict before and after processing have slightly different constraints on them
OK that makes a ton of sense! I noticed they were different, but didn't dig into it very far.

---

The problem I am trying to solve: 
I had a bash script that I ran yt-dlp in where it would grab files from a channel, but I wanted to ignore certain tags since other metadata couldn't easily differentiate the desired vs undesirable content. I tried a few different ways and googled around a bit and always ran into the same problem: it was trying to compare a **string** (passed via `--match-filter`) and a **list** of tags and would throw some kind of type error, so it would just blow up. I never filed an issue for that particular problem. I gave up trying to make the tag thing work and ended up hand-picking the things to download, which is fine since it's just for my personal use. 

Fast forward to this week and I decided to rewrite the bash script into a more dynamic language and since I'd banged my head against the wall with the tag thing I assumed that it was still a problem but I never actually checked it in my Python edition of the script. 
So I was using `extract_info`, parsing the info dict for the undesirable tags, removing the entry from the `entries`, and then after all my Python dict processing it would move on to `process_ie_result` and download the videos that I wanted, and leave out the videos I didn't. It a good plan: until I ran into this problem.

Long story short: either the Python way of match-filtering is better at finding and ignoring tags, or the bug I saw five months ago was fixed. Either way I think my original problem of trying to filter based on tags is easily solved with
 `'match_filter': yt_dlp.utils.match_filter_func(['tag != ignorethistag'])`

This was a pretty intractable problem without your help. I thank you. 🙇‍♂️

I guess maybe I have two suggestions for this issue then
* is there some documentation that talks about the double-processing problem that would have helped me avoid running into it?
* or is there some kind of limitation that could be added on the `process_ie_result`/`download_with_info_file`, and other related functions, that would prevent the double processing from ever happening?

Thank you for your time pukkandan!

**Comment by pukkandan** [comment]
> Either way I think my original problem of trying to filter based on tags is easily solved with
> `'match_filter': yt_dlp.utils.match_filter_func(['tag != ignorethistag'])`

It would be either `match_filter_func(['tags!*="ignore"'])` or

    lambda info, _: 'ignore' not in (info.get('tags') or [])

---



> I guess maybe I have two suggestions for this issue then
> 
> * is there some documentation that talks about the double-processing problem that would have helped me avoid running into it?
> * or is there some kind of limitation that could be added on the `process_ie_result`/`download_with_info_file`, and other related functions, that would prevent the double processing from ever happening?

No. It's not a problem I've ever expected anyone to run into. I'd say it's normal for `process_ie_result` to be not reentrant. Honestly, I don't even think it should be a public method - but youtube-dl has it as such, so I won't change it.

An infojson with playlist entry actually missing[^1] and one with entries removed by match-filter are not distinguishable as far as I can tell. So I can't think of a way to detect this situation reliably

[^1]: For example, when using `--load-info`

**Comment by zxjinn** [comment]
Perfect. Thanks again for the answers and guidance.
