### ISSUE TITLE
I get private video error even when I use cookies. why and can it be fixed?

### ISSUE THREAD

**Issue by emilyexa** [yt-dlp/yt-dlp#6299]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.02.17** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood
```
ERROR: [youtube] a07iwuDWhys: Video unavailable. This video is private
```
no matter what I do I get video is private error. how do I fix this?

my config.txt says:
```
--cookies-from-browser firefox
```
or
```
--cookies-from-browser chrome
```
I still get **this video is private error**
the other questions answered say use cookies so I did but it didn't fix anything.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['a07iwuDWhys', '-vU']
[debug] User config "C:\Users\mohsentux\AppData\Roaming\yt-dlp\config.txt": ['--force-ipv4', '--concurrent-fragments', '32', '--retries', 'infinite', '--fragment-retries', 'infinite', '--buffer-size', '8K', '--hls-prefer-native', '--format', 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best', '--download-archive', 'C:\\Users\\mohsentux\\AppData\\Roaming\\yt-dlp\\archive.txt', '--embed-subs', '--embed-thumbnail', '--embed-metadata', '--write-playlist-metafiles', '--add-chapters', '--merge-output-format', 'mkv', '--output', 'G:\\yt-dlp\\%(playlist)s\\%(playlist_index)s - %(title)s.%(ext)s', '--external-downloader', 'aria2c', '--cookies-from-browser', 'firefox']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2023.02.17 [a0a7c01] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-109856-gf8d6d0fbf1-20230213 (setts), ffprobe N-109856-gf8d6d0fbf1-20230213, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[Cookies] Extracting cookies from firefox
[debug] Extracting cookies from: "C:\Users\mohsentux\AppData\Roaming\Mozilla\Firefox\Profiles\kar4m7qm.default-release\cookies.sqlite"
[Cookies] Extracted 710 cookies from firefox
[debug] Proxy map: {}
[debug] Loaded 1782 extractors
[debug] Loading archive file 'C:\\Users\\mohsentux\\AppData\\Roaming\\yt-dlp\\archive.txt'
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2023.02.17, Current version: 2023.02.17
yt-dlp is up to date (2023.02.17)
[youtube] Extracting URL: a07iwuDWhys
[youtube] a07iwuDWhys: Downloading webpage
[debug] [youtube] Extracted SAPISID cookie
[youtube] a07iwuDWhys: Downloading android player API JSON
ERROR: [youtube] a07iwuDWhys: Video unavailable. This video is private
  File "yt_dlp\extractor\common.py", line 693, in extract
  File "yt_dlp\extractor\youtube.py", line 4034, in _real_extract
  File "yt_dlp\extractor\common.py", line 1171, in raise_no_formats
```

**Comment by pukkandan** [comment]
>  Make sure you are **only** asking a question and not reporting a bug or requesting a feature.
> If your question contains "isn't working" or "can you add", this is most likely the wrong template.
> If you are in doubt whether this is the right template, **USE ANOTHER TEMPLATE**!

??

---

Are you sure you have access to the video with the same account? Unless you are willing to share account details, it would be hard for us to check anything

**Comment by 512banque** [comment]
OP is correct, I get the exact same problem since one week. Also I get "WARNING: skipping cookie file entry due to invalid length 8:" although I didn't change a thing and am still using the same getcookies chrome extension since the beginning.

**Comment by YuenSzeHong** [comment]
I guess @emilyexa had multiple accounts logged in in his browser, and the account with the video access wasn't the default account, causing this error, the way is to check to visit google.com, then look at the address bar, if `?authuser=0` is shown with the account with access, that should be a yt-dlp issue, if `authuser` is not 0, make that account default by signing off all accounts then log that account in first then other accounts
