### ISSUE TITLE
[Feature Request] Output Template: support for new fields (height, width, chosen_format_id) and/or support for IF comparisons/qualifiers

### ISSUE THREAD

**Issue by mikkovedru** [yt-dlp/yt-dlp#6300]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.02.17** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

## Problem/Need
I want to have the dimensions of the video (height e.g. 480p, 1080p, etc) included in the name of the downloaded file. Example of the wanted final result:
`/home/mikko/Downloads/Videos/Youtube/Lex Clips/2023-02-07_Narcissism Explained： It's the main cause of evil in the world ｜ Paul Conti and Lex Fridman_By Lex Clips @ Youtube_mJ7nEOZzJ8I_480p.mkv`

I used the following Output Template:
`-o '/home/mikko/Downloads/Videos/%(extractor_key|extractor)s/%(channel|uploader)s/%(release_date>%Y-%m-%d,upload_date>%Y-%m-%d)s_%(title)s_By %(channel|uploader)s at %(extractor_key|extractor)s_%(id)s_%(XXX)sp.%(ext)s'` (if anyone has good suggestions, I will gladly receive them).

Everything works fine with the exception of getting the dimensions of the video (marked as `%(XXX)sp` ).

## How I tried to solve it
1. Extensive reading of the documentation and active googling. I found out that there is [no ready field](https://github.com/yt-dlp/yt-dlp#output-template) that has the dimensions of the video. A bummer!

2. I can't really compare the formats fields with the current choice of video format/quality.
- `%(formats.:.height)s` gives:
[27, 45, 90, 144, 144, 144, 144, 144, 144, 240, 240, 240, 360, 360, 360, 360, 480, 480, 480, 720, 720, 720, 720, 1080, 1080, 1080]
Very confusing as to which one is the one I downloaded... Also, there is no way to choose the one I need.

- `%(formats.:.{format_id,height,format_note})s`  gives:
```
[{'format_id'： 'sb2', 'height'： 27, 'format_note'： 'storyboard'}, {'format_id'： 'sb1', 'height'： 45, 'format_note'： 'storyboard'}, {'format_id'： 'sb0', 'height'： 90, 'format_note'： 'storyboard'}, {'format_id'： '599', 'format_note'： 'ultralow'}, {'format_id'： '600', 'format_note'： 'ultralow'}, {'format_id'： '139', 'format_note'： 'low'}, {'format_id'： '249', 'format_note'： 'low'}, {'format_id'： '250', 'format_note'： 'low'}, {'format_id'： '140', 'format_note'： 'medium'}, {'format_id'： '251', 'format_note'： 'medium'}, {'format_id'： '17', 'height'： 144, 'format_note'： '144p'}, {'format_id'： '597', 'height'： 144, 'format_note'： '144p'}, {'format_id'： '598', 'height'： 144, 'format_note'： '144p'}, {'format_id'： '394', 'height'： 144, 'format_note'： '144p'}, {'format_id'： '160', 'height'： 144, 'format_note'： '144p'}, {'format_id'： '278', 'height'： 144, 'format_note'： '144p'}, {'format_id'： '395', 'height'： 240, 'format_note'： '240p'}, {'format_id'： '133', 'height'： 240, 'format_note'： '240p'}, {'format_id'： '242', 'height'： 240, 'format_note'： '240p'}, {'format_id'： '396', 'height'： 360, 'format_note'： '360p'}, {'format_id'： '134', 'height'： 360, 'format_note'： '360p'}, {'format_id'： '18', 'height'： 360, 'format_note'： '360p'}, {'format_id'： '243', 'height'： 360, 'format_note'： '360p'}, {'format_id'： '397', 'height'： 480, 'format_note'： '480p'}, {'format_id'： '135', 'height'： 480, 'format_note'： '480p'}, {'format_id'： '244', 'height'： 480, 'format_note'： '480p'}, {'format_id'： '22', 'height'： 720, 'format_note'： '720p'}, {'format_id'： '398', 'height'： 720, 'format_note'： '720p'}, {'format_id'： '136', 'height'： 720, 'format_note'： '720p'}, {'format_id'： '247', 'height'： 720, 'format_note'： '720p'}, {'format_id'： '399', 'height'： 1080, 'format_note'： '1080p'}, {'format_id'： '137', 'height'： 1080, 'format_note'： '1080p'}, {'format_id'： '248', 'height'： 1080, 'format_note'： '1080p'}]
```
But once again, how do I choose the one I need (the one that has just been downloaded)?

- Perhaps like this: `%(formats.:.{format_id[247],height})s`. But no, it gives `NA`. 
So it doesn't even work if I hardcode the used `format_id`, let alone want it to be flexible (dynamic) and give the info on the exact one video which was downloaded.

## Possible solutions (based on my limited understanding)
1. Add new available fields like `height`, `width`.
2. Add a new available field like `chosen_format_id` (I am sure there can be a better name).
3. Allow comparison/qualifier (some sort of if-statements) inside the Output Template format. It would give a lot of new opportunities including the one allowing to choose the `height` based on `chosen_format_id`.
4. Combination of the above or something new entirely. Or a solution that already exists, but I just didn't know about (despite extensive research).

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
> Add new available fields like height, width.
> Add a new available field like chosen_format_id (I am sure there can be a better name).

`height`, `width`, `format_id` already exist

https://github.com/yt-dlp/yt-dlp/blob/17ca19ab60a6a13eb8a629c51442b5248b0d8394/README.md#L1293
https://github.com/yt-dlp/yt-dlp/blob/17ca19ab60a6a13eb8a629c51442b5248b0d8394/README.md#L1466-L1467
https://github.com/yt-dlp/yt-dlp/blob/17ca19ab60a6a13eb8a629c51442b5248b0d8394/README.md#L1487

---





> 3\. Allow comparison/qualifier (some sort of if-statements) inside the Output Template format. It would give a lot of new opportunities

I don't quite understand. `%(a&b|c)s` is kinda like `if a, "b" else "c"`. Are you proposing something else?
