### ISSUE TITLE
yt-dlp output file has apostrophe(') at the starting and begining

### ISSUE THREAD

**Issue by manikaran1993** [yt-dlp/yt-dlp#6307]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.02.17** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

The yt-dlp output file has apostrophe(') at the starting and begining.
I am using yt-dlp in termux and getting below output.

.../vids/test $ ls
.../vids/test $ yt-dlp https://www.youtube.com/watch?v=LPGr0XArk6s
[youtube] Extracting URL: https://www.youtube.com/watch?v=LPGr0XArk6s
[youtube] LPGr0XArk6s: Downloading webpage
[youtube] LPGr0XArk6s: Downloading android player API JSON
[info] LPGr0XArk6s: Downloading 1 format(s): 248+251
[download] Destination: Replace youtube-dl with yt-dlp [LPGr0XArk6s].f248.webm
[download] 100% of   10.78MiB in 00:00:02 at 5.05MiB/s
[download] Destination: Replace youtube-dl with yt-dlp [LPGr0XArk6s].f251.webm
[download] 100% of    6.72MiB in 00:00:01 at 5.42MiB/s
[Merger] Merging formats into "Replace youtube-dl with yt-dlp [LPGr0XArk6s].webm"
Deleting original file Replace youtube-dl with yt-dlp [LPGr0XArk6s].f251.webm (pass -k to keep)
Deleting original file Replace youtube-dl with yt-dlp [LPGr0XArk6s].f248.webm (pass -k to keep)
.../vids/test $ ls
'Replace youtube-dl with yt-dlp [LPGr0XArk6s].webm'

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2023.02.17 [a0a7c01] (pip)
[debug] Python 3.10.4 (CPython aarch64 64bit) - Linux-5.10.107-android13-4-00020-g02b5dfab573c-ab9358130-aarch64-with-libc (OpenSSL 3.0.2 15 Mar 2022, libc)
[debug] exe versions: ffmpeg 5.0 (setts), ffprobe 5.0
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1782 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2023.02.17, Current version: 2023.02.17
yt-dlp is up to date (2023.02.17)
```

**Comment by bashonly** [comment]
`ls` prints the filename in single-quotes because the filename has spaces in it. The single-quotes are not actually a part of the filename

```bash
$ touch nospaces.txt
$ ls
nospaces.txt
$ touch "file with spaces.txt"
$ ls
'file with spaces.txt'
nospaces.txt
```

**Comment by manikaran1993** [comment]
Thanks for the quick response.
I asked the dumbest question.
Can you also help to remove the random string in [] before extension

**Comment by gamer191** [comment]
> Can you also help to remove the random string in [] before extension

That's the last bit of the youtube url, and can be used if you ever want to know the video's url, or if you wanna re-download it. If, however, you don't plan on doing that, add `-o "%(title)s.%(ext)s"` to your command, or to your [config file](%(title)s [%(id)s].%(ext)s)
