### ISSUE TITLE
Occasional fatal error when downloading videos from Twitch

### ISSUE THREAD

**Issue by ghost** [yt-dlp/yt-dlp#6308]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2023.02.17** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Provide a description that is worded well enough to be understood

I've been running into an error when downloading videos from Twitch. It doesn't happen every time, but it does occur often enough to be a nuisance.

I'm fairly certain that it only occurs if you use the "--datebefore" option and the video that you're trying to download falls outside of the designated range, but it's difficult to be absolutely certain since the error does not occur on every download.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--datebefore', 'now-10days', 'https://www.twitch.tv/videos/1742266892']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8 (No ANSI), error utf-8 (No ANSI), screen utf-8 (No ANSI)
[debug] yt-dlp version 2023.02.17 [a0a7c01] (pip)
[debug] Python 3.9.2 (CPython x86_64 64bit) - Linux-5.10.0-20-amd64-x86_64-with-glibc2.31 (OpenSSL 1.1.1n  15 Mar 2022, glibc 2.31)
[debug] exe versions: ffmpeg 4.3.5-0, ffprobe 4.3.5-0
[debug] Optional libraries: Cryptodome-3.14.1, brotli-1.0.9, certifi-2020.06.20, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.2
[debug] Proxy map: {}
[debug] Loaded 1782 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2023.02.17, Current version: 2023.02.17
yt-dlp is up to date (2023.02.17)
[twitch:vod] Extracting URL: https://www.twitch.tv/videos/1742266892
[twitch:vod] 1742266892: Downloading stream metadata GraphQL
ERROR: 'NoneType' object does not support item assignment
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/yt_dlp/YoutubeDL.py", line 1502, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/yt_dlp/YoutubeDL.py", line 1578, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.9/dist-packages/yt_dlp/extractor/common.py", line 693, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.9/dist-packages/yt_dlp/extractor/twitch.py", line 516, in _real_extract
    video = self._download_info(vod_id)
  File "/usr/local/lib/python3.9/dist-packages/yt_dlp/extractor/twitch.py", line 384, in _download_info
    video['moments'] = traverse_obj(data, (1, 'data', 'video', 'moments', 'edges', ..., 'node'))
TypeError: 'NoneType' object does not support item assignment
```

**Comment by funky-d** [comment]
I've been having issues downloading from Twitch lately as well, using the --wait-for-video flag. This started late last week. I receive the below error before the stream even begins... sometimes it happens after a few minutes of retries, other times it can take 30min or more, but it appears to be easily reproduceable on any channel that isn't live by using the --wait-for-video flag:

```
[debug] Command-line config: ['--cookies-from-browser', 'firefox', '--wait-for-video', '120', 'https://www.twitch.tv/twitch', '-vU']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2023.02.17 [a0a7c01] (pip)
[debug] Python 3.10.6 (CPython x86_64 64bit) - Linux-5.19.0-32-generic-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2020.06.20, mutagen-1.46.0, secretstorage-3.3.1, sqlite3-2.6.0, websockets-10.3
[Cookies] Extracting cookies from firefox
[debug] Extracting cookies from: "/home/user/.mozilla/firefox/mdlwcris.default-release/cookies.sqlite"
[Cookies] Extracted 121 cookies from firefox
[debug] Proxy map: {}
[debug] Loaded 1782 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2023.02.17, Current version: 2023.02.17
yt-dlp is up to date (2023.02.17)
[twitch:stream] Extracting URL: https://www.twitch.tv/twitch
[twitch:stream] twitch: Downloading stream GraphQL
WARNING: [twitch:stream] twitch: The channel is not currently live
[wait] Waiting for 00:02:00 - Press Ctrl+C to try now
[wait] Wait period ended; Re-extracting data
<snip>
[twitch:stream] Extracting URL: https://www.twitch.tv/twitch
[twitch:stream] twitch: Downloading stream GraphQL
ERROR: twitch: An extractor error has occurred. (caused by KeyError('data')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/home/user/.local/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 693, in extract
    ie_result = self._real_extract(url)
  File "/home/user/.local/lib/python3.10/site-packages/yt_dlp/extractor/twitch.py", line 974, in _real_extract
    user = gql[0]['data']['user']
KeyError: 'data'
```

**Comment by elyse0** [comment]
@funky-d  Can you give some channels that are going to be live today?

**Comment by funky-d** [comment]
@elyse0 I received the above error without the channel ever going live (or at least the channel didn't appear to go live). However, I pulled that error yesterday... I tried again after creating my post and it ran for over an hour without any error, so I'm wondering if my issue was an issue with Twitch over the weekend? Looking at my history, I first ran into the issue Friday night.

As for some channels that may be going live a few hours: willneff, fanfan, jakenbakelive or waterlynn

If you need any other info just let me know, and I'll continue to test here and will let you know if I experience my issue again.

**Comment by Hunter-100** [comment]
https://www.twitch.tv/videos/1745224952
https://www.twitch.tv/videos/1740427160
https://www.twitch.tv/videos/1739499778

With all 3 I'm getting "ERROR: 'NoneType' object does not support item assignment" with Windows 2023.02.17 exe however the download starts.

Could be related, original youtube-dl 2021 exe returns the error;
"ERROR: An extractor error has occurred. (caused by KeyError('data',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output."

Verbose does not include extra information.
Error is not always thrown on original youtube-dl but if you try all 3 you eventually get it.

**Comment by Mert-Y** [comment]
> https://www.twitch.tv/videos/1745224952 https://www.twitch.tv/videos/1740427160 https://www.twitch.tv/videos/1739499778
> 
> With all 3 I'm getting "ERROR: 'NoneType' object does not support item assignment" with Windows 2023.02.17 exe however the download starts.
> 
> Could be related, original youtube-dl 2021 exe returns the error; "ERROR: An extractor error has occurred. (caused by KeyError('data',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output."
> 
> Verbose does not include extra information. Error is not always thrown but if you try all 3 you eventually get it.

I think download starting might be a bit misleading because i query video information first and the run the command again to download. So it probably throws the error on the first command and then doesn't when downloading. Just a coincidence that happened 3 times in a row because after i tried a couple more times it did not download a couple more times, it downloads again.

**Comment by Hunter-100** [comment]
> https://www.twitch.tv/videos/1745224952 https://www.twitch.tv/videos/1740427160 https://www.twitch.tv/videos/1739499778
> 
> With all 3 I'm getting "ERROR: 'NoneType' object does not support item assignment" with Windows 2023.02.17 exe however the download starts.
> 
> Could be related, original youtube-dl 2021 exe returns the error; "ERROR: An extractor error has occurred. (caused by KeyError('data',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output."
> 
> Verbose does not include extra information. Error is not always thrown but if you try all 3 you eventually get it.

I think download starting might be a bit misleading because i query video information first and the run the command again to download. So it probably throws the error on the first command and then doesn't when downloading. Just a coincidence that happened 3 times in a row because after i tried a couple more times it did not download a couple more times, it downloads again.

**Comment by elyse0** [comment]
Yep, I could reproduce it and the linked PR will fix it

**Comment by funky-d** [comment]
My issue has not reappeared, so it was likely an issue with Twitch last weekend and not related to OP's issue.
