### ISSUE TITLE
Subtitle file with a lot of repeated lines, and very offset timings.

### ISSUE THREAD

**Issue by larsk2** [yt-dlp/yt-dlp#631]
## Checklist

- [X ] I'm reporting a broken site support issue
- [ X] I've verified that I'm running yt-dlp version **2021.08.02**
- [ X] I've checked that all provided URLs are alive and playable in a browser
- [ X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ X] I've searched the bugtracker for similar bug reports including closed ones
- [ X] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE

```

## Description

WRITE DESCRIPTION HERE

For some reason, the subtitles (xml is repeating itself several times, and the timing is also way offset. A clip of 27 minutes, ends up subtitle-length of 66 hrs. Video and audio downloads normally. 

yt-dlp doesn not give any error messages, so there's nothing to post in that regard.

Link for the manifest is here: https://e.s.sumo.prod.streampilot.tv/isi_mp4_1/2021-06-10/whlucncroxb(1662806_ISMUSP)_v3.ism/whlucncroxb(1662806_ISMUSP)_v3.mpd

![SE-screenshot](https://user-images.githubusercontent.com/88277503/128291997-1ddc9e2e-4f9e-4436-9d07-52f49315b90f.PNG)

**Comment by fstirlitz** [comment]
As per #247, downloading subtitles found in DASH and ISM manifests is somewhat experimental. If you could find a m3u8 manifest with a WebVTT subtitle stream, it should work much more reliably.

That said, this one probably isn’t our fault. The timing problem seems to be that the program you opened the subtitle in adds the cue timestamp found in the fragment XML to the container timestamp of the segment, expecting the former to be relative to the segment timestamp (where in fact, they are relative to the whole media stream).

According to <https://www.w3.org/community/texttracks/2013/09/11/carriage-of-webvtt-and-ttml-in-mp4-files/>:

> Regarding timing, each TTML document contains the elements to be presented during the sample validity, but the time values used in the document are relative to the start of the track. In other words, 00:00:00 in the XML does not mean the start of the sample in which the document is carried. So in the example below, the document describes rendering between times 00:31:00 and 00:32:00 but the sample may have a start time before the time 00:31:00 and may last after 00:32:00. Authors should be careful, that elements associated with times outside the sample validity will not be rendered.

This is not an authoritative standards document, but I presume it agrees with the actual standard text, so it would appear that this is a bug in your subtitle editor.

But given how poorly TTML-in-MP4 tends to be supported, it might be warranted for us to extract such subtitle streams into stand-alone TTML files.

(The duplication issue stems from the fact that some subtitles appear in multiple DASH segments. When the timestamp issue is resolved, the duplicates should have their timestamps align exactly, reducing this to a mere annoyance. Though sure, it would be nice to merge them too.)

**Comment by nyuszika7h** [comment]
Yeah, I’ve dealt dealt with the TTML-in-MP4 duplication issue before. The solution is to check if the current segment’s start timestamp is equal to the previous segment’s end timestamp (possibly also check if the text is equal just to make sure), and if so, set the previous segment’s end timestamp to the current segment’s end timestamp instead of appending the current segment to the list.

**Comment by larsk2** [comment]
Thanks for your comments and feedback.

I was aware is was a long-shot, but maybe it's something that can/will be implemented in a later version. As for the subtitle editor, I will argue against it being bugged, since the original .xml file (downloaded and merged with yt-dlp (opened in notepad)) also contains several lines with the same text. I've tried looking it up on other websites, to get a better understanding about how the cue's/timestamps work. I was trying to look for a script that could look for copied lines in consecutive fragments, and merge them properly. I'm afraid it's out my league to do anything about it myself, as I lack the coding skills to do so.

Hopefully someone more knowledgeable is able to do something about it in the future.

**Comment by fstirlitz** [comment]
Wait, yt-dlp doesn’t download an XML file. It downloads an MP4 file with XML fragments in it. Where did you get the XML file from?

**Comment by larsk2** [comment]
Sorry about that, my bad in explaining properly. I renamed the file into .xml as I was reading about it in another forum. You are correct that the original output from yt-dlp is a .mp4 file.

**Comment by fstirlitz** [comment]
Okay. I don’t know who told you to rename the file, but they didn’t know what they were talking about. Obtaining a proper stand-alone XML subtitle requires a bit more processing that just renaming the MP4 file.

Fortunately, the subtitle editor seems to have called your bluff, and is able to parse the MP4 container and extract the XML fragments. It is correct in showing multiple cues with the same content, since those are present in the original stream. It is incorrect in adjusting the cue timestamps (apparently relative to individual segment boundaries). If you looked at the file in Notepad, you might have noticed that the `end=` timestamps match the `begin=` timestamps of their later duplicates:

```
<p begin="00:00:06.080" end="00:00:08.000" region="bottom">
                <span>BORTKASTET PINGUS</span>
            </p>
```

```
<p begin="00:00:08.000" end="00:00:08.840" region="bottom">
                <span>BORTKASTET PINGUS</span>
            </p>
```

If the file were correctly read, it would have the starting and ending timestamps align likewise in the editor.

Is this <https://github.com/SubtitleEdit/subtitleedit/>? Maybe we could ping @niksedk.

**Comment by fstirlitz** [comment]
In the meantime, you can try downloading subtitles from <https://e.s.sumo.prod.streampilot.tv/isi_mp4_1/2021-06-10/whlucncroxb(1662806_ISMUSP)_v3.ism/whlucncroxb(1662806_ISMUSP)_v3.m3u8>, which is WebVTT over HLS. Those are much better supported.

**Comment by larsk2** [comment]
@fstirlitz correct indeed. I have also sent him a feature request/suggestion via mail. I'm new to this with subs contained in a mp4 stream, so i just experimented with various suggestions from other forums. Thanks again for taking the time, much appreciated.

**Comment by larsk2** [comment]
Also, tried getting the vtt earlier, and ended up with this error message:

[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 279
[download] Destination: whlucncroxb(1662806_ISMUSP)_v3 [whlucncroxb(1662806_ISMUSP)_v3].no.vtt
[download]   1.4% of ~33.58KiB at Unknown speed ETA Unknown ETAERROR: Parse error at position 184 (near '00:00:22.200 --> 00:')
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1179, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1217, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1261, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2280, in process_video_result
  File "yt_dlp\YoutubeDL.py", line 2534, in process_info
  File "yt_dlp\YoutubeDL.py", line 2417, in dl
  File "yt_dlp\downloader\common.py", line 386, in download
  File "yt_dlp\downloader\hls.py", line 322, in real_download
  File "yt_dlp\downloader\fragment.py", line 421, in download_and_append_fragments
  File "yt_dlp\downloader\fragment.py", line 399, in append_fragment
  File "yt_dlp\downloader\hls.py", line 257, in pack_fragment
  File "yt_dlp\webvtt.py", line 377, in parse_fragment
yt_dlp.webvtt.ParseError: Parse error at position 184 (near '00:00:22.200 --> 00:')

**Comment by fstirlitz** [comment]
Yes, I just noticed that too. You should file that one separately, though. Best to follow the template fully this time.

I appreciated the report, by the way, even if this is not our bug. If nothing else, it gives us a little more confidence that TTML-over-DASH downloading works correctly, by the fact that this subtitle editor can read the subtitles fine (other than mangling the timestamps); the maintainer and I were somewhat worried about this in #247.

(While we’re at it, there is also <https://e.s.sumo.prod.streampilot.tv/isi_mp4_1/2021-06-10/whlucncroxb(1662806_ISMUSP)_v3.ism/Manifest> serving TTML over Smooth Streaming, which I am even less sure about. Can you read this one? If not, please also file it, in another issue.)

**Comment by larsk2** [comment]
I will file properly this evening. Thanks again.
