### ISSUE TITLE
AttributeError: 'Popen' object has no attribute 'text_mode'

### ISSUE THREAD

**Issue by Brodan** [yt-dlp/yt-dlp#6317]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2023.02.17** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

upgraded to the latest yt-dlp because i was starting to see the `Unable to extract uploader id` error. i was previously using `yt-dlp==2022.05.18` just fine up until this past week when errors started to appear

```
$ python -V 
Python 3.10.10
$ pip freeze | grep -i yt-dlp 
yt-dlp==2023.2.17
$ pip -V
pip 22.3.1 from /.../src/python/gce-api/venv/lib/python3.10/site-packages/pip (python 3.10)
```

this is happening on both my M1 mac and inside of a docker image based off of `python:3.10.10-buster` so i dont think its a mac issue

i've installed yt-dlp via `pip install -r requirements`.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[youtube] Extracting URL: https://www.youtube.com/watch?v=zf1aZHSXFNU
[youtube] zf1aZHSXFNU: Downloading webpage
[youtube] zf1aZHSXFNU: Downloading android player API JSON
[youtube] zf1aZHSXFNU: Downloading MPD manifest
Traceback (most recent call last):
  File "/usr/src/app/./app.py", line 715, in download_url
    extracted_info = ydl.extract_info(url)
  File "/usr/local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1491, in extract_info
    return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
  File "/usr/local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1502, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1599, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1658, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/usr/local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 2697, in process_video_result
    req_format = self._default_format_spec(info_dict, download=download)
  File "/usr/local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 2007, in _default_format_spec
    not can_merge()
  File "/usr/local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 2001, in can_merge
    return merger.available and merger.can_merge()
  File "/usr/local/lib/python3.10/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 205, in available
    return self.basename is not None
  File "/usr/local/lib/python3.10/functools.py", line 981, in __get__
    val = self.func(instance)
  File "/usr/local/lib/python3.10/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 172, in basename
    self._version  # run property
  File "/usr/local/lib/python3.10/functools.py", line 981, in __get__
    val = self.func(instance)
  File "/usr/local/lib/python3.10/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 197, in _version
    return self._get_version('ffmpeg')
  File "/usr/local/lib/python3.10/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 184, in _get_version
    basename, version, features = next(filter(
  File "/usr/local/lib/python3.10/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 185, in <genexpr>
    lambda x: x[1], ((p, *self._get_ffmpeg_version(p)) for p in executables)), (None, None, {}))
  File "/usr/local/lib/python3.10/site-packages/yt_dlp/postprocessor/ffmpeg.py", line 141, in _get_ffmpeg_version
    out = _get_exe_version_output(path, ['-bsfs'])
  File "/usr/local/lib/python3.10/site-packages/yt_dlp/utils.py", line 2720, in _get_exe_version_output
    stdout, _, ret = Popen.run([encodeArgument(exe)] + args, text=True,
  File "/usr/local/lib/python3.10/site-packages/yt_dlp/utils.py", line 903, in run
    default = '' if proc.text_mode else b''
AttributeError: 'Popen' object has no attribute 'text_mode'
```

**Comment by bashonly** [comment]
>  File "/usr/src/app/./app.py", line 715, in download_url
>    extracted_info = ydl.extract_info(url)

looks like you are running your own script? does yt-dlp work if you run it by itself?

**Comment by Brodan** [comment]
closing because i figured out the issue. i was calling yt-dlp from within a `gevent` worker but i had recently removed the `enable-threads = true` line from my uswgi conf.ini and that line was needed for gevent to work properly

**Comment by Grub4K** [comment]
I am not so sure why it would cause this and would be careful with closing this ahead of time. I just cannot see why changing the setup like this would cause this code to break.

It might make sense to shim the undocumented `text_mode` (not mentioned in [docs](https://docs.python.org/3/library/subprocess.html)) instead using the CPython implementation and then use that instead:
```diff
diff --git a/yt_dlp/utils.py b/yt_dlp/utils.py
index 458239a12..00dce25bc 100644
--- a/yt_dlp/utils.py
+++ b/yt_dlp/utils.py
@@ -879,6 +879,7 @@ def __init__(self, *args, env=None, text=False, **kwargs): 
             env = os.environ.copy()
         self._fix_pyinstaller_ld_path(env)

+        self.__text_mode = kwargs.get('encoding') or kwargs.get('errors') or text or kwargs.get('universal_newlines')
         if text is True:
             kwargs['universal_newlines'] = True  # For 3.6 compatibility      
             kwargs.setdefault('encoding', 'utf-8')
@@ -900,7 +901,7 @@ def kill(self, *, timeout=0):
     @classmethod
     def run(cls, *args, timeout=None, **kwargs):
         with cls(*args, **kwargs) as proc:
-            default = '' if proc.text_mode else b''
+            default = '' if proc.__text_mode else b''
             stdout, stderr = proc.communicate_or_kill(timeout=timeout)        
             return stdout or default, stderr or default, proc.returncode
```
When applying those changes, does the error happen with an incorrectly configured app?

**Comment by gamer191** [comment]
related (possible duplicate) #6314

**Comment by Brodan** [comment]
@Grub4K you are right and I spoke too soon. I'm still seeing this issue on my setup.

**Comment by Grub4K** [comment]
Please try doing an editable source install and running it with and without the suggested fix. That way we can see if this code is the issue or something else, potentially external.

**Comment by Brodan** [comment]
> Please try doing an editable source install and running it with and without the suggested fix. That way we can see if this code is the issue or something else, potentially external.

hey, just tested this by forking, updating the code, and updating my `requirements.txt` to use that fork. your suggested fix seems to have worked.

**Comment by Grub4K** [comment]
cc @pukkandan since the code was originally added by him.

**Comment by pukkandan** [comment]
I assumed it's public due to the naming. Your patch makes sense. You can push

I am still curious why this issue happens though. The property is [set in 3.10](https://github.com/python/cpython/blob/3.10/Lib/subprocess.py#L851)

**Comment by rtaylo45** [comment]
I am also running into this error and would love to see this patched and released.
