### ISSUE TITLE
Is TVer slow downloading due to yt-dlp or is it on their side?

### ISSUE THREAD

**Issue by GT2000byte** [yt-dlp/yt-dlp#6320]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2023.02.17** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Japan

### Provide a description that is worded well enough to be understood

I've noticed recently that after updating to the most recent yt-dlp version (2023.02.17) TVer downloads have become way slower to the point of taking me over 6 hours to download a file I used to get within an hour or so. Makes me wonder if TVer has changed stuff up so yt-dlp takes way longer to download videos or is it just me. I've also tried plenty of GUI's and didn't made any change in speed (not that I expected to).

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'test:tver']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2023.01.06 [6becd25] (zip)
[debug] Python 3.10.6 (CPython x86_64 64bit) - Linux-6.0.12-76060006-generic-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.11.0, brotli-1.0.9, certifi-2020.06.20, mutagen-1.45.1, pyxattr-0.7.2, secretstorage-3.3.1, sqlite3-2.6.0, websockets-9.1
[debug] Proxy map: {}
[debug] Loaded 1760 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2023.02.17, Current version: 2023.01.06
[debug] Downloading _update_spec from https://github.com/yt-dlp/yt-dlp/releases/download/2023.02.17/_update_spec
Current Build Hash 446d77c224738bb5bc8e8711014b5df3ca096997eaeeb61f7d8c10c425658255
Updating to version 2023.02.17 ...
ERROR: Unable to write to /usr/local/bin/yt-dlp; Try running as administrator
[TestURL] Extracting URL: test:tver
[TestURL] Test URL: https://tver.jp/episodes/ep83nf3w4p
[TVer] Creating session
[TVer] Extracting URL: https://tver.jp/episodes/ep83nf3w4p
[TVer] ep83nf3w4p: Downloading JSON metadata
WARNING: [TVer] Unable to download JSON metadata: HTTP Error 404: Not Found
[TVer] ep83nf3w4p: Downloading JSON metadata
[brightcove:new] Extracting URL: http://players.brightcove.net/4394098883001/default_default/index.html?videoId=ref:3363_3362_33252#__youtubedl_smuggle=%7B%22geo_countries%22%3A+%5B%22JP%22%5D%7D
[debug] Using fake IP 133.170.110.43 (JP) as X-Forwarded-For
[brightcove:new] ref:3363_3362_33252: Downloading JSON metadata
[debug] Saving brightcove.4394098883001_default to cache
[brightcove:new] ref:3363_3362_33252: Downloading JSON metadata
ERROR: [brightcove:new] None: The policy key provided does not permit this account or video, or the requested resource is inactive.
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 680, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/brightcove.py", line 925, in _real_extract
    raise ExtractorError(message, expected=True)
```

**Comment by pukkandan** [comment]
1. You are on older version
2. The log shows that you don't have access to the video, not that the download is slow as you report

**Comment by GT2000byte** [comment]
> 1. You are on older version
> 
>     2. The log shows that you don't have access to the video, not that the download is slow as you report

Funny enough Tartube claimed to have updated yt-dlp so at first I thought it actually did so until you just pointed out I was still on the January version. With that being said it seems to stern from my VPN servers rather than yt-dlp itself as one of them is disliked by TVer and the other has gone down speed wise. Will check tomorrow again to see if anything got better.

**Comment by pukkandan** [comment]
> With that being said it seems to stern from my VPN servers rather than yt-dlp itself as one of them is disliked by TVer and the other has gone down speed wise. Will check tomorrow again to see if anything got better.


> * [x]  I've checked that all provided URLs are playable in a browser with the same IP and same login details

Check if it's throttled on browser with same VPN

**Comment by GT2000byte** [comment]
> Check if it's throttled on browser with same VPN

It seems my VPN's Japanese servers aren't working too well, couldn't even get into a video as TVer often timed out. I did made a test with a YouTube video without a VPN and sure enough downloaded pretty fast.

**Comment by GT2000byte** [comment]
Just a quick update: I waited until today and the TVer download itself is still slow. However I noticed that using Video DownloadHelper and extracting the m3u8 manifests will result in faster downloads, although you'll need to put video and audio together through a video editing software. It does seem like something changed in TVer itself streaming wise or something.

**Comment by pukkandan** [comment]
> However I noticed that using Video DownloadHelper and extracting the m3u8 manifests will result in faster downloads

Can reopen if you provide verbose logs from both, demonstrating the speed difference
