### ISSUE TITLE
Does not support sf.tradepub.com

### ISSUE THREAD

**Issue by srikk73** [yt-dlp/yt-dlp#6323]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2023.02.17** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

India

### Provide a description that is worded well enough to be understood

I tried to download a video from https://sf.tradepub.com/. It returned an error: Unsupported URL. 
I am using the latest version of yt-dlp.
I believe the video is not DRM protected, so it can be downloaded.
The debug output is given below.

Will this site be supported?

Regards,
Srikanth

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
% yt-dlp -vU https://sf.tradepub.com/\?p\=w_myex05\&w\=d\&email\=bfa59bba672b495d11b26333b79fff5b\&key\=eCXtfPeeIofG9FFUYylF\&ts\=62479\&u\=1570450692331645962214\&e\=c3Jpa2FudGgua2FzdHVyaS43M0BnbWFpbC5jb20\=\&secure\=1\&_afn\=0
WARNING: Could not read zip file /usr/lib/python3.10/site-packages/websocket_client-1.4.2-py3.10.egg: [Errno 21] Is a directory: '/usr/lib/python3.10/site-packages/websocket_client-1.4.2-py3.10.egg'

[debug] Command-line config: ['-vU', 'https://sf.tradepub.com/?p=w_myex05&w=d&email=bfa59bba672b495d11b26333b79fff5b&key=eCXtfPeeIofG9FFUYylF&ts=62479&u=1570450692331645962214&e=c3Jpa2FudGgua2FzdHVyaS43M0BnbWFpbC5jb20=&secure=1&_afn=0']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2023.02.17 [a0a7c01] (pip)
[debug] Python 3.10.8 (CPython x86_64 64bit) - Linux-5.15.78-1-MANJARO-x86_64-with-glibc2.36 (OpenSSL 3.0.7 1 Nov 2022, glibc 2.36)
[debug] exe versions: ffmpeg 5.1.2 (setts), ffprobe 5.1.2, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.12.0, brotlicffi-1.0.9.2, certifi-2022.09.24, mutagen-1.46.0, secretstorage-3.3.3, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1782 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2023.02.17, Current version: 2023.02.17
yt-dlp is up to date (2023.02.17)
[generic] Extracting URL: https://sf.tradepub.com/?p=w_myex05&w=d&email=bfa59bba672b495d11b26333b79fff5b&key=eCXtfPeeIofG9FFUYylF&ts=62479&u=1570450692331645962214&e=c3Jpa2FudGgua2FzdHVyaS43M0BnbWFpbC5jb20=&secure=1&_afn=0
[generic] ?p=w_myex05&w=d&email=bfa59bba672b495d11b26333b79fff5b&key=eCXtfPeeIofG9FFUYylF&ts=62479&u=1570450692331645962214&e=c3Jpa2FudGgua2FzdHVyaS43M0BnbWFpbC5jb20=&secure=1&_afn=0: Downloading webpage
[redirect] Following redirect to https://sf.tradepub.com/free/w_myex05/
[generic] Extracting URL: https://sf.tradepub.com/free/w_myex05/
[generic] w_myex05: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] w_myex05: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://sf.tradepub.com/free/w_myex05/
Traceback (most recent call last):
  File "/home/newuser/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1502, in wrapper
    return func(self, *args, **kwargs)
  File "/home/newuser/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1578, in __extract_info
    ie_result = ie.extract(url)
  File "/home/newuser/.local/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 693, in extract
    ie_result = self._real_extract(url)
  File "/home/newuser/.local/lib/python3.10/site-packages/yt_dlp/extractor/generic.py", line 2509, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://sf.tradepub.com/free/w_myex05/
```

**Comment by gamer191** [comment]
> The link to 'Pivot Table Training - Free Excel Webinar' has expired.

please provide a new example url
