### ISSUE TITLE
Please add socks5h proxy support

### ISSUE THREAD

**Issue by beavailable** [yt-dlp/yt-dlp#6325]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.02.17** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Currently, `yt-dlp` can not recognize `socks5h` proxy, if I provide a `socks5h` proxy environment variable, then it will exit with error "Unable to download API page: <urlopen error [Errno 104] Connection reset by peer> (caused by URLError(ConnectionResetError(104, 'Connection reset by peer')))".

I know that even if I set a `socks5` proxy environment variable it will work fine, but it's a little troublesome for me. Because I use a bash alias like this:
```
alias start-proxy='export ALL_PROXY="socks5h://address:port" HTTP_PROXY="socks5h://address:port" HTTPS_PROXY="socks5h://address:port" all_proxy="socks5h://address:port" http_proxy="socks5h://address:port" https_proxy="socks5h://address:port"'
```
to set proxy environment variable, so that I can set proxy for all commands.

The question is, some commands (such as `curl`) will not resolve hostname through socks server if I provided a `socks5` proxy, I have to provide a `socks5h` proxy, but if so, I can't set proxy for `yt-dlp`.

So I hope `yt-dlp` could accept `socks5h` proxy without error, even by simply replacing "socks5h" string with "socks5".

### Provide verbose output that clearly demonstrates the problem

- [x] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2023.02.17 [a0a7c0154] (debian*)
[debug] Python 3.9.2 (CPython x86_64 64bit) - Linux-5.10.0-21-amd64-x86_64-with-glibc2.31 (OpenSSL 1.1.1n  15 Mar 2022, glibc 2.31)
[debug] exe versions: ffmpeg 4.3.5-0, ffprobe 4.3.5-0, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.9.7, brotli-1.0.9, certifi-2020.06.20, mutagen-1.45.1, pyxattr-0.7.2, sqlite3-2.6.0, websockets-8.1
[debug] Proxy map: {}
[debug] Loaded 1782 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2023.02.17, Current version: 2023.02.17
yt-dlp is up to date (2023.02.17)
```

**Comment by pukkandan** [comment]
You could use `--proxy`

**Comment by coletdjnz** [comment]
`socks5` is treated as `socks5h` in yt-dlp.

**Comment by beavailable** [comment]
> You could use `--proxy`

Yes, I tried to use this option, but there was another question: I have both a desktop system and a server (which do not need proxy), they share a single `bashrc`, if I use `alias yt-dlp="yt-dlp --proxy xxx"` then `yt-dlp` will not work on my server.

Of course I can just not use alias, but it's inconvenient.

> Also: `socks5` is treated as `socks5h` in yt-dl/p.

Thanks for your message, I have already know that.

**Comment by bashonly** [comment]
Add `--proxy xxx` to your desktop [yt-dlp config file](https://github.com/yt-dlp/yt-dlp#configuration)

**Comment by beavailable** [comment]
> Add `--proxy xxx` to your desktop [yt-dlp config file](https://github.com/yt-dlp/yt-dlp#configuration)

Thank you, this works in my situation, and this issue could be closed if no one want to discuss it anymore.

But for me, if `yt-dlp` could support `socks5h` proxy, it will be a better solution.

**Comment by coletdjnz** [comment]
We could add support for `socks5h://` as an alias of `socks5://` if it helps avoid issues with other applications. But we can't change our `socks5://` implementation to what it should be for compatibility reasons.

Related: https://github.com/ytdl-org/youtube-dl/pull/28093/, https://github.com/ytdl-org/youtube-dl/issues/22618

**Comment by beavailable** [comment]
> We could add support for `socks5h://` as basically an alias of `socks5://` if it helps avoid issues with other applications. 

That's exactly what I want.

> But we can't change our `socks5://` behaviour to what it should be for compatibility reasons.

Totally understand.
