### ISSUE TITLE
Can't download youtube private videos even using cookies

### ISSUE THREAD

**Issue by iron-heart-x** [yt-dlp/yt-dlp#6326]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2023.02.17** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

I tried to download youtube private video using coockies.txt file but it not downloaded.
It shows this error
```
[youtube] Extracting URL: https://youtu.be/LSYiMEU71W8
[youtube] LSYiMEU71W8: Downloading webpage
[youtube] LSYiMEU71W8: Downloading android player API JSON
ERROR: [youtube] LSYiMEU71W8: Private video. Sign in if you've been granted access to this video
```

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['--cookies', 'cookies.txt', 'https://youtu.be/LSYiMEU71W8', '-vU']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2023.02.17 [a0a7c01] (pip)
[debug] Python 3.10.6 (CPython aarch64 64bit) - Linux-5.15.0-1029-oracle-aarch64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2020.06.20, mutagen-1.46.0, secretstorage-3.3.1, sqlite3-2.6.0, websockets-10.4
(redacted by Lesmiscore)
[debug] Proxy map: {}
[debug] Loaded 1782 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2023.02.17, Current version: 2023.02.17
yt-dlp is up to date (2023.02.17)
[youtube] Extracting URL: https://youtu.be/LSYiMEU71W8
[youtube] LSYiMEU71W8: Downloading webpage
[youtube] LSYiMEU71W8: Downloading android player API JSON
ERROR: [youtube] LSYiMEU71W8: Private video. Sign in if you've been granted access to this video
  File "/usr/local/lib/python3.10/dist-packages/yt_dlp/extractor/common.py", line 693, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.10/dist-packages/yt_dlp/extractor/youtube.py", line 4034, in _real_extract
    self.raise_no_formats(reason, expected=True)
  File "/usr/local/lib/python3.10/dist-packages/yt_dlp/extractor/common.py", line 1171, in raise_no_formats
    raise ExtractorError(msg, expected=expected, video_id=video_id)
```

**Comment by Lesmiscore** [comment]
Export cookies.txt again from your browser, and try with it

**Comment by iron-heart-x** [comment]
How to export cookies.txt from browser?
I used cookies.txt extension.

**Comment by Lesmiscore** [comment]
Do the same procedure as you did when you get cookies.txt file

**Comment by goodysmarts** [comment]
use cookies or create a .netrc file in you home folder and place youtube and your account info in it.

Example:

.netrc

machine [www.website.com](http://www.website.com/) login [myenailaddress@whatever.com](mailto:myenailaddress@whatever.com) password my-password

**Comment by pukkandan** [comment]
The logs indicate that your cookie file doesn't contain any authentication information. If you are having difficulty exploring cookies correctly, try using `--cookies-from-browser` instead. If you are sure this is not a user error, you can share the cookie file (potentially giving me access to your account) to debug

**Comment by iron-heart-x** [comment]
> --cookies-from-browser

I used this method it downloading. but using cookies.txt file not working.
I used this extension https://chrome.google.com/webstore/detail/get-cookiestxt/bgaddhkoddajcdgocldbbfleckgcbcid?hl=en to get cookies

**Comment by iron-heart-x** [comment]
Is that possible to get cookies.txt using ytdlp ?

**Comment by pukkandan** [comment]
> Is that possible to get cookies.txt using ytdlp ?

    yt-dlp --cookies-from-browser chrome --cookies cookies.txt -s test:

will extract cookies from chrome and save it in cookies.txt. Note that unlike most extensions, this extracts ALL cookies, not just of the current site

**Comment by pukkandan** [comment]
> > 
> 
> I used this method it downloading. but using cookies.txt file not working. I used this extension [chrome.google.com/webstore/detail/get-cookiestxt/bgaddhkoddajcdgocldbbfleckgcbcid?hl=en](https://chrome.google.com/webstore/detail/get-cookiestxt/bgaddhkoddajcdgocldbbfleckgcbcid?hl=en) to get cookies

The it's either user error, or problem with extension

**Comment by chocmake** [comment]
> > --cookies-from-browser
> 
> I used this method it downloading. but using cookies.txt file not working. I used this extension https://chrome.google.com/webstore/detail/get-cookiestxt/bgaddhkoddajcdgocldbbfleckgcbcid?hl=en to get cookies

Just btw the Get Cookies.txt addon was [found recently](https://reddit.com/r/youtubedl/comments/11i5vyq/psa_the_get_cookiestxt_extension_is_now_actively/) to be uploading user cookies directly to the dev, along with browser history. It's been reported to Google but in the meantime would be best removed if you have it installed.

Bit of  an unfortunate turn of events give youtube-dl still recommends it in their readme, which many yt-dlp users migrated from.
