### ISSUE TITLE
How or where do I put the config for the ytdl-patched one

### ISSUE THREAD

**Issue by BLSTR13** [yt-dlp/yt-dlp#6327]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.02.17** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I already made a config a long time ago for yt-dlp, but Im having some problems creating with ytdl-patched, Idk if its the folder name or something that has some problems
![image](https://user-images.githubusercontent.com/95217152/220663888-501cb314-f371-4121-b2d5-f757d2957076.png)
like this one

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by Lesmiscore** [comment]
You meant this one? https://github.com/ytdl-patched/yt-dlp
Same

**Comment by BLSTR13** [comment]
Same folder?

**Comment by BLSTR13** [comment]
-o D:/ytdl/%(title)s.%(ext)s
the above one is for the naming of the file right, its for not showing the link on yt on the file name right? it works on yt-dlp but on the patched one it still shows

**Comment by goodysmarts** [comment]
You can either name the config file ytdl-patched.conf and place it in the same folder as the ytdl-patched executable file. or if you are on windows just create a folder name ytdl-patched in you roaming folder and place the config file in that folder

**Comment by pukkandan** [comment]
> ### Provide verbose output that clearly demonstrates the problem
> * [ ]  Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
> * [ ]  Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below
