### ISSUE TITLE
Sibnet streaming website

### ISSUE THREAD

**Issue by trimechee** [yt-dlp/yt-dlp#6328]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2023.02.17** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

World

### Example URLs

https://video.sibnet.ru/day/20230223/video5054979-K_2023_gotov/?utm_source=main_page&utm_medium=video_block_day&utm_cmpaign=main_page_may

https://video.sibnet.ru/

### Provide a description that is worded well enough to be understood

Hello, thank you for this great dowloader ! I discover Sibnet streaming website and it will be great and awesome to add support of this wonrderful website that has many interesting videos ! Thank you so much !

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
18:37:23, yt-dlp (external): 2023.2.17
18:37:23, libcurl (internal): libcurl/7.68.0 Schannel zlib/1.2.11 brotli/1.0.7 nghttp2/1.40.0
18:37:23, ffmpeg (internal): lavf 58.29.100, lavc 58.54.100, lavu 56.31.100
18:37:23, #01, Analysis, https://video.sibnet.ru/day/20230223/video5054979-K_2023_gotov?utm_source=main_page&utm_medium=video_block_day&utm_cmpaign=main_page_may
18:37:23, #01, Opening given  URL...
18:37:38, [warning] yt-dlp : WARNING: [generic] Falling back on generic information extractor
18:37:38, skipped results from 'generic' youtube-dl extractor: analyzing URLs from unsupported sites is disallowed
18:37:38, [error] #01, Analysis, unsupported site URL
18:37:38, #01, Ready
```

**Comment by pukkandan** [comment]
https://github.com/yt-dlp/yt-dlp/issues/1094
