### ISSUE TITLE
Why is 'thumbnails' property in metadata a string? [Question]

### ISSUE THREAD

**Issue by Xan-Kun** [yt-dlp/yt-dlp#633]
## Checklist
- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question
I'm coming from youtube-dl and when trying to parse the metadata json, it broke my old code, because from youtube-dl the field `thumbnails `is a list, but in yt-dlp it is a string.
Just curious about why that is, as the string still contains a valid json list.

Thanks for the great tool!

**Comment by pukkandan** [comment]
Sorry, it's a bug and is closed by https://github.com/yt-dlp/yt-dlp/commit/8012d892bd38af731357a61e071e0a0d01bc41b4
