### ISSUE TITLE
Download last 3 weeks of subscriptions / restrict youtube search by date: ytsubs ytsearchdate

### ISSUE THREAD

**Issue by igorzhilin** [yt-dlp/yt-dlp#6335]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.02.17** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Going back to the topic of
ytsearch
:ytsubs
ytsearchdate

Which I did not understand from https://github.com/yt-dlp/yt-dlp/issues/6035

Here is my goal:
* download my subscrrptions 
* for last 2 weeks

OR
* download a channel's videos
* for last X days

➡ this means, I need to understand how to use a combination of `:ytsubs` and `ytsearchdate` and maybe something else too.

**Problem:**
If I just run `yt-dlp --cookies-from-browser firefox :ytsubs`, it starts to download 13000 videos! That's my total number of subscriptions. That's too many, I need to filter them somehow. Ideally by date, by channel.

**Questions:**
1. What should be the command line to filter my subscriptions to last 14 days?
2. What should the date format be for ytsearchdate? Could you please give the example, how to download videos between x dates or just for last x days?
3. How to combine ytsearchdate with ytsearch and/or ytsubs.
4. Please provide some full command line examples to illustrate the usage.

I know these search things are not documented. Nor was I able to understand the search URLs from the explanation provided in here: https://github.com/yt-dlp/yt-dlp/issues/6035. 

Could you please provide some examples, and I will document them in simple words for future generations and users like me.

Thanks.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
> 1. What should be the command line to filter my subscriptions to last 14 days?

Use `--date-after` along with `--lazy-playlist --break-on-reject`


> What should the date format be for ytsearchdate? Could you please give the example, how to download videos between x dates or just for last x days?
> How to combine ytsearchdate with ytsearch and/or ytsubs.

ytsearchdate is for "Youtube **search** (not subs), **sorted** (not filtered) by date" and unrelated to what you want to achieve

**Comment by igorzhilin** [comment]
Nice, I managed to get last 14 days of my subs using the following:
```
yt-dlp 
  :ytsubs 
  --lazy-playlist 
  --dateafter today-14day 
  --break-on-reject 
  --cookies-from-browser firefox 
  -o "%(webpage_url_domain)s/%(playlist)s/%(upload_date)s %(playlist_index)03d%(playlist_index& - )s%(uploader)s - %(title)s.%(ext)s"
```

Where:
- `:ytsubs` - special keyword corresponding to subs, requires cookies
- `--lazy-playlist` - do not wait for completion of download of full playlist metadata, start download as soon as video with criteria is found
- `--dateafter today-14day` - filter the selection by date after today minus 14 days, i.e. last 15 days
- `--break-on-reject` - stop looping over videos as soon as a video not fulfilling the filter criteria is found (in this case, the `--dateafter` filter)
- `--cookies-from-browser firefox` - getting my subscriptions from firefox, where I am logged in

Also interesting for me is to **restrict the subs by keywords/regex**. This requires another type of break, because `--break-on-reject` stops the process as soon as it finds a non-matching video, even if it has not reached the end of the date filter yet.

**Here is a command line to get my subs over last 15 days with keyword "atomic" in the title:**
```
yt-dlp 
  :ytsubs 
  --lazy-playlist  
  --dateafter today-14days  
  --match-filter "title~='(?i)atomic'"
  --playlist-end 300  
  -o "%(webpage_url_domain)s/%(playlist)s/%(upload_date)s %(playlist_index)03d%(playlist_index& - )s%(uploader)s - %(title)s.%(ext)s" 
```

The main difference is, that in addition to `--dateafter today-14days` I set a cap on the count of videos in the playlist, after which the process stops: `--playlist-end 300`. I take the number 300 because I know that my subscriptions would contain less than 300 videos over last 15 days. So 300 videos would be enough to cover last 15 days, and then I can filter those videos further by `--match-filter "title~='(?i)atomic'"` and the `--dateafter today-14days`.

Very cool.

@pukkandan 👉 Is there a more robust way to get last 15 days of subscriptions filtered with `--match-filter`? 
Or is `--playlist-end X` is a good enough approximation that allows the process to halt at some point?

**Comment by pukkandan** [comment]
> Also interesting for me is to **restrict the subs by keywords/regex**. This requires another type of break, because `--break-on-reject` stops the process as soon as it finds a non-matching video, even if it has not reached the end of the date filter yet.

#5962 + https://github.com/yt-dlp/yt-dlp/issues/4988 would make this possible

**Comment by AtomicNess123** [comment]
Can you add the upload date into the name of the file?
