### ISSUE TITLE
using spotdl and getting a yt-dlp error

### ISSUE THREAD

**Issue by LaGrabow** [yt-dlp/yt-dlp#6336]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.02.17** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I am using an app called spotdl to download from www.spotify.com
I am getting an error when I try to download.
The error refers to yt-dlp.
**Exception: ERROR:  jZGwbfVSNn0: Unable to extract uploader id; please report this issue on  
https://github.com/yt-dlp/yt-dlp , filling out the "Broken site" issue template properly. Confirm 
you are on the latest version using  yt-dlp -U**

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] I cannot run this debug as I am not using yt-dlp, although I am getting an error for yt-dlp.
```

**Comment by gamer191** [comment]
1. Spotdl is scamming you, because that error only shows for Youtube videos
2. That issue can be fixed by updating yt-dlp. If you installed spotdl using pip, just run `pip install --no-deps --update yt-dlp`. Otherwise you'll have to wait for the next spotdl update. If you send me a link to their repo, I'd be happy to open a bug report

**Comment by LaGrabow** [comment]
https://github.com/spotDL/spotify-downloader/issues

**Comment by LaGrabow** [comment]
@gamer191 
Thank you
https://github.com/spotDL/spotify-downloader/issues

**Comment by pukkandan** [comment]
> 1. Spotdl is scamming you, because that error only shows for Youtube videos

They don't claim to download from spotify. It downloads from youtube music and adds metadata from spotify

**Comment by LaGrabow** [comment]
@pukkandan  
Thanks for clearing that up for me. re:spotdl.
Does spotify_dl do the same thing?

**Comment by pukkandan** [comment]
Probably. You should ask them
