### ISSUE TITLE
Prevent unnecessary remuxing when embedding thumbnails

### ISSUE THREAD

**Issue by unami-tacos** [yt-dlp/yt-dlp#6340]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [x] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.02.17** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

When using the ```--embed-thumbnail``` option, the console will send: ```WARNING: webm doesn't support embedding a thumbnail, mkv will be used```. As far as I can tell, it remuxes the video to support the thumbnail.

I'm running a command similar to this: ```yt-dlp --recode-video mp4 --embed-thumbnail [url]``` which I was hoping would recode the video to mp4, and then embed the thumbnail. However it seems to remux to mkv regardless, unneccesarily bloating the file.

Running encoding before thumbnail embedding, and not remuxing to mkv when unnecessary would save a lot of drive space.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2023.02.17 [a0a7c01] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22621-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 2023-02-22-git-d5cc7acff1-essentials_build-www.gyan.dev (setts), ffprobe 2023-02-22-git-d5cc7acff1-essentials_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1782 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2023.02.17, Current version: 2023.02.17
yt-dlp is up to date (2023.02.17)
```

**Comment by pukkandan** [comment]
It's not remusing to mkv, but merging to it. Use `--merge-output-format` to control it

The log you have provided does not demonstrate any problem

**Comment by unami-tacos** [comment]
Ah, thanks. I stand corrected.
