### ISSUE TITLE
Subtitle Option "sub-langs" and regex

### ISSUE THREAD

**Issue by Stepan-H** [yt-dlp/yt-dlp#6348]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.02.17** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Hi,
I am not successfull to use Subtitle Options the --sub-langs LANGS with regex as written in readme.md "Languages of the subtitles to download (can be regex)..."

Commonly I use 
`--write-subs --sub-langs "cs,sk,en, -live_chat"`

but in YT there in some videos subtitles like this

Language|Name|Formats
---|---|---
en-nP7-2PuUl7o|English - en|vtt, ttml, srv3, srv2, srv1, json3

so I tried as readme.md shows example "en.*,ja"
and add asterix * after "en"
`--write-subs --sub-langs "cs,sk,en*, -live_chat"`

but it does not work.

Please, how can I set it for download all variants of some language subtitles?

Thank you very much.

**Comment by xpalidotious** [comment]
You need to use the correct format for regular expressions, so copy the example of "en.*" which will match "en" and anything that starts with "en".

Your use of "en*" will only match "en", "enn", "ennn", etc.

**Comment by pukkandan** [comment]
> I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

> Make sure you are **only** asking a question and not reporting a bug or requesting a feature.
        If your question contains "isn't working" or "can you add", this is most likely the wrong template.
        If you are in doubt whether this is the right template, **USE ANOTHER TEMPLATE**!


Do you think these instructions are there as joke?

**Comment by Stepan-H** [comment]
I don't understant, where I made mistake.

"Make sure you are only asking a question and not reporting a bug or requesting a feature."
Yes, I was onyl ask. Thist "issue" is just only question. WHAT IS WRONG?

"If your question contains "isn't working" or "can you add", this is most likely the wrong template."
In my text, there are nothing about "isn't working" or "can you add".
Thist "issue" is just only question. WHAT IS WRONG?

"If you are in doubt whether this is the right template, USE ANOTHER TEMPLATE!"
I used template " Ask question Ask yt-dlp related question". 
WHAT IS WRONG?

**I did everything I could, to the best of my ability, to comply. I don't know what more I could have done. If I've misspelled a comma or a period somewhere, I'm so sorry. I'm not a robot, I'm just a poor human being...**

**Comment by pukkandan** [comment]
You were trying a yt-dlp command that didn't work[^2] as you expected - so you should have given the verbose log[^1]. My comment was too harsh though - sorry about that.

Anyway, since you got an answer, I assume this doesn't need to be be re-opened?

[^2]: I hope you agree "does not work" belongs in the same category as "isn't working"
[^1]: Which other templates would have marked as mandatory
