### ISSUE TITLE
Cannot download with URL have auth:pass 

### ISSUE THREAD

**Issue by jazz1611** [yt-dlp/yt-dlp#6352]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2023.02.17** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Hello,

yt-dlp cannot download URL when have already username:password in URL

Demo: https://u332871:7vhK0Yb0FrB7uRsV@u332871.your-storagebox.de/anime/tmdb/Tv/30984/seasons/1/010.mkv

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
C:\Users\MASTERX>youtube-dl -Uv "https://u332871:7vhK0Yb0FrB7uRsV@u332871.your-storagebox.de/anime/tmdb/Tv/30984/seasons/1/010.mkv"
[debug] Command-line config: ['-Uv', 'https://u332871:7vhK0Yb0FrB7uRsV@u332871.your-storagebox.de/anime/tmdb/Tv/30984/seasons/1/010.mkv']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2023.02.17 [a0a7c01] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-109620-gcc7e984a05-20230117 (setts), ffprobe N-109620-gcc7e984a05-20230117
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1782 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2023.02.17, Current version: 2023.02.17
yt-dlp is up to date (2023.02.17)
[generic] Extracting URL: https://u332871:7vhK0Yb0FrB7uRsV@u332871.your-storagebox.de/anime/tmdb/Tv/30984/seasons/1/010.mkv
[generic] 010: Downloading webpage
[redirect] Following redirect to https://u332871.your-storagebox.de/anime/tmdb/Tv/30984/seasons/1/010.mkv
[generic] Extracting URL: https://u332871.your-storagebox.de/anime/tmdb/Tv/30984/seasons/1/010.mkv
[generic] 010: Downloading webpage
ERROR: [generic] None: Unable to download webpage: HTTP Error 401: Unauthorized (caused by <HTTPError 401: 'Unauthorized'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 693, in extract
  File "yt_dlp\extractor\generic.py", line 2370, in _real_extract
  File "yt_dlp\extractor\common.py", line 838, in _request_webpage

  File "yt_dlp\extractor\common.py", line 820, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 3726, in urlopen
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 401: Unauthorized
```

**Comment by dirkf** [comment]
The Generic extractor doesn't recognise that the response URL in the redirection test is actually the same as the original, because the u:p@ part is missing. The problem is reproduced in yt-dl once the necessary functionality is pulled in. If the `Request` used for the test was available (it is in yt-dl), the test could be made using its `.get_full_url()`. Also, if there actually had been a redirection, the u:p@ part ought to be copied into the redirected URL.

Handling u:p@ in general is a bit tricky, since such URLs won't match the `_VALID_URL`. They could be massaged for `suitable()`, `_match_id()` and `_match_valid_url()` but an extractor using `re.match()` would fail. Possibly the Generic extractor could use `smuggle_url()` to pass the u:p@ part to a redirected URL, and `sanitized_Request()` could recognise and extract such smuggled data, as the yt-dlp version does with the u:p@ part. Currently a URL that would be `suitable()` for some IE if not for its u:p@ part won't be passed to that IE..

**Comment by pukkandan** [comment]
I don't know of any extractor that uses it. For now, I've fixed the reported issue. We can deal with the rest if/when examples arise
