### ISSUE TITLE
ERROR: [youtube] VvpQu2rsH3A: Unable to extract uploader id;

### ISSUE THREAD

**Issue by n3ovo** [yt-dlp/yt-dlp#6353]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2023.02.17** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

usa

### Provide a description that is worded well enough to be understood

downloading from Nextcloud NCDownloader V1.0.2 

Trying to download and 3D printer Help File and got this message back.

ERROR: [youtube] VvpQu2rsH3A: Unable to extract uploader id; please report this issue on https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using yt-dlp -U

Hope that i have done this the way that is helpful. I have used this in the PAST and  it work just fine ,, Thanks for all the help and look forward to more .. THANKs

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
Cant do this as it is running as a APP on nextcloud:
Here is what O could get:

[ncdownloader] Error: ERROR: [youtube] VvpQu2rsH3A: Unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U


POST /apps/ncdownloader/ytdl/new
from 192.168.1.1 by john at 2023-02-25T08:03:34+00:00
```

**Comment by Lesmiscore** [comment]
Update yt-dlp
