### ISSUE TITLE
Getting an error "Output file #0 does not contain any stream"

### ISSUE THREAD

**Issue by Veneiro** [yt-dlp/yt-dlp#6355]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.02.17** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I recently migrated my personal discord music bot from using the youtube-dl library to this library. I tried to play a song but whenever the bot download the song and tries to play it I get the error "Output file #0 does not contain any stream" on console. The bot was working perfectly with the youtube-dl library so ¿is there any important thing I should change to make yt-dlp workwith my code? I didn't find anyone with this problem on the issues so I really apreciate if someone know what can be the problem.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
Can you show the relevant code from your bot?

**Comment by Veneiro** [comment]
Yes, here is the code of the python class where I have all the code for the music commands, and sorry if it is a bit messy it's my first discord bot.

https://pastebin.com/HcFW0me9

**Comment by bashonly** [comment]
Your current code is most likely passing the storyboard URL to the bot. You could try this change:
```diff
     # searching the item on youtube
     def search_yt(self, item):
         with YoutubeDL(self.YDL_OPTIONS) as ydl:
             try:
                 info = ydl.extract_info("ytsearch:%s" % item,
                                         download=False)['entries'][0]
             except Exception:
                 return False
         info = ydl.sanitize_info(info)
-        url = info['formats'][0]['url']
+        url = info['requested_formats'][0]['url']
         title = info['title']
         return {
             'title': title,
             'source': url
         }
```

**Comment by Veneiro** [comment]
When trying this change after using the play command I get the following by console, it throws a KeyError
```
Ignoring exception in command play:
Traceback (most recent call last):
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/ext/commands/core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/runner/Captain-Alex-Discord-Bot/music_cog.py", line 107, in play
    song = self.search_yt(query)
  File "/home/runner/Captain-Alex-Discord-Bot/music_cog.py", line 46, in search_yt
    url = info['requested_formats'][0]['url']
KeyError: 'requested_formats'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/ext/commands/core.py", line 863, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/ext/commands/core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: KeyError: 'requested_formats'
```

**Comment by bashonly** [comment]
oh my bad, I didn't account for your format selection (`m4a/bestaudio/best`)

in that case you should be able to just use:
```py
        url = info['url']
```

**Comment by Veneiro** [comment]
Oh, thank you so much! Now it's working as expected

**Comment by irevlix990** [comment]
i'm have same the trouble, but with different python code

how to fix it ?

import discord
from discord.ext import commands
import yt_dlp as ytdl
import asyncio
from discord import FFmpegPCMAudio
import os
from collections import deque
import json

# Token bot
TOKEN = '****'

# Membuat Intents untuk bot
intents = discord.Intents.default()
intents.message_content = True  # Agar bot bisa membaca pesan
intents.members = True  # Agar bot bisa mendeteksi kehadiran anggota

# Prefix command bot
bot = commands.Bot(command_prefix="!", intents=intents)

# Lokasi file cookies (ubah path sesuai file cookies Anda)
# COOKIES_FILE = 'cookies.json'

# Pengaturan untuk yt-dlp
#ytdl_opts = {
#    'format': 'bestaudio/best',
#    'extractaudio': True,
#    'audioquality': 1,
#    'outtmpl': 'downloads/%(id)s.%(ext)s',
#    'restrictfilenames': True,
#    'noplaylist': True,
#    'quiet': True,
#    'cookiefile': 'cookies.txt',
#    'logtostderr': False,
#}

ytdl_opts = {
    'format': "bestvideo[vcodec^=avc1][filesize<?100M][ext=mp4]+bestaudio[acodec^=mp4a]/best",  # Ambil audio terbaik
    'cookiefile': 'cookies.txt',  # Gunakan cookies Netscape
    'quiet': True,  # Nonaktifkan output verbose
    "restrictfilenames": true,
    "outtmpl": "downloads/%(uploader)s-%(title)s.%(ext)s",
    "writedescription": true,
    'postprocessors': [{
        'key': 'FFmpegExtractAudio',
        'preferredcodec': 'mp3',  # Ekstrak audio sebagai mp3
        'preferredquality': '192',  # Kualitas audio 192kbps
    }],
}


# Cek dan baca file cookies jika ada
#if os.path.exists(COOKIES_FILE):
#    with open(COOKIES_FILE, 'r') as f:
#       cookies = json.load(f)
#       ytdl_opts['cookiefile'] = COOKIES_FILE

ffmpeg_opts = {
    'before_options': '-reconnect 1 -reconnect_streamed 1 -reconnect_delay_max 5',
    'options': '-vn'
}

# Antrian lagu
queue = deque()

# Fungsi untuk mengunduh dan memutar audio dari YouTube
async def play_audio(ctx, url, filter_type=None):
    try:
        # Cek apakah bot sudah terhubung ke voice channel
        voice_client = ctx.guild.voice_client
        if voice_client is None:
            # Bot belum terhubung, jadi kita hubungkan bot ke channel suara
            voice_channel = ctx.author.voice.channel
            voice_client = await voice_channel.connect()

        # Mengunduh informasi dari URL menggunakan yt-dlp
        with ytdl.YoutubeDL(ytdl_opts) as ydl:
            info = ydl.extract_info(url, download=False)
            url2 = info['formats'][0]['url']
            song_title = info.get('title', 'Unknown')

        # Menentukan filter audio yang diterapkan
        filter_options = ''
        if filter_type == "bassboost":
            filter_options = 'bass=g=10'
        elif filter_type == "nightcore":
            filter_options = 'atempo=1.25, asetrate=44100*1.25'

        # Putar audio menggunakan FFmpegPCMAudio
        source = discord.FFmpegPCMAudio(url2, **ffmpeg_opts)
        voice_client.play(source, after=lambda e: print(f"Finished playing {song_title}"))

        # Menggabungkan filter dengan opsi FFmpeg
        #voice_client.play(FFmpegPCMAudio(url2, **ffmpeg_opts, options=f'-filter:a "{filter_options}"'),
        #                 after=lambda e: asyncio.run_coroutine_threadsafe(after_play(ctx), bot.loop))

        await ctx.send(f"Now playing: {song_title} with {filter_type if filter_type else 'no filter'}")

        # Menunggu hingga selesai
        while voice_client.is_playing():
            await asyncio.sleep(1)

        await voice_client.disconnect()

    except Exception as e:
        await ctx.send(f"Error occurred: {e}")
        print(f"Error: {e}")

# Fungsi setelah lagu selesai
async def after_play(ctx):
    if len(queue) > 0:
        # Ambil lagu berikutnya dari antrian
        next_song = queue.popleft()
        await play_audio(ctx, next_song[0], next_song[1])
    else:
        print("No more songs in queue.")

# Command untuk mencari dan memutar musik berdasarkan judul
@bot.command(name="search")
async def search(ctx, *, query):
    search_url = f"ytsearch:{query}"
    await play(ctx, search_url)

# Command untuk memutar musik
@bot.command(name="play")
async def play(ctx, url, filter_type=None):
    # Cek apakah pengguna berada di channel suara
    if ctx.author.voice:
        voice_channel = ctx.author.voice.channel
        # Cek apakah bot sudah terhubung ke voice channel
        if ctx.guild.voice_client is None:
            # Bot tidak terhubung, jadi kita hubungkan bot ke channel suara
            await voice_channel.connect()

        queue.append((url, filter_type))  # Tambahkan URL dan filter ke antrian
        if len(queue) == 1:  # Jika ini adalah lagu pertama, mulai memutar
            await play_audio(ctx, url, filter_type)
        else:
            await ctx.send("Song added to queue!")
    else:
        await ctx.send("You need to join a voice channel first!")

# Command untuk skip lagu
@bot.command(name="skip")
async def skip(ctx):
    voice_client = ctx.guild.voice_client
    if voice_client.is_playing():
        voice_client.stop()
        await ctx.send("Skipped the current song!")
    else:
        await ctx.send("No song is currently playing.")

# Command untuk berhenti
@bot.command(name="stop")
async def stop(ctx):
    voice_client = ctx.guild.voice_client
    if voice_client.is_playing():
        voice_client.stop()
        await ctx.send("Stopped the music.")
    else:
        await ctx.send("No song is currently playing.")
    
    # Kosongkan antrian setelah berhenti
    queue.clear()

# Command untuk disconnect
@bot.command(name="leave")
async def leave(ctx):
    voice_client = ctx.guild.voice_client
    if voice_client.is_playing():
        voice_client.stop()
    await voice_client.disconnect()

# Command untuk bergabung ke voice channel
@bot.command(name="join")
async def join(ctx):
    channel = ctx.author.voice.channel
    await channel.connect()

# Command untuk bass boost
@bot.command(name="bassboost")
async def bassboost(ctx, *, query):
    await play(ctx, query, filter_type="bassboost")

# Command untuk nightcore
@bot.command(name="nightcore")
async def nightcore(ctx, *, query):
    await play(ctx, query, filter_type="nightcore")

# Menjalankan bot
bot.run(TOKEN)
