### ISSUE TITLE
Quickies on Xvideos

### ISSUE THREAD

**Issue by FlashFried** [yt-dlp/yt-dlp#6356]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a site-specific feature
- [X] I've verified that I'm running yt-dlp version **2023.02.17** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Worldwide

### Example URLs

https://www.xvideos.com/profiles/firolix#quickies/a/51392867
https://www.xvideos.com/profiles/firolix#quickies/a/63386619

### Provide a description that is worded well enough to be understood

Quickies, the version of shorts on Xvideos, aren't currently downloadable. Can you add support for them?

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '-f', 'mp4', 'https://www.xvideos.com/profiles/firolix#quickies/a/51392867']
[debug] User config "C:\Users\Noah Bangs\yt-dlp.conf": ['-o', 'H:\\youtube-dl\\Export\\%(webpage_url_domain)s\\%(title)s - %(channel,artist - album)s.%(ext)s', '--retries', 'infinite', '--download-archive', 'registry.txt']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2023.02.17 [a0a7c01] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19044-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg git-2020-04-03-52523b6, ffprobe git-2020-04-03-52523b6
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1782 extractors
[debug] Loading archive file 'registry.txt'
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2023.02.17, Current version: 2023.02.17
yt-dlp is up to date (2023.02.17)
[generic] Extracting URL: https://www.xvideos.com/profiles/firolix#quickies/a/51392867
[generic] 51392867: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] 51392867: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://www.xvideos.com/profiles/firolix#quickies/a/51392867
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1502, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1578, in __extract_info
  File "yt_dlp\extractor\common.py", line 693, in extract
  File "yt_dlp\extractor\generic.py", line 2509, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.xvideos.com/profiles/firolix#quickies/a/51392867
```

**Comment by BlastoiseVeteran** [comment]
put a "quickie" from the front page or something at least man. you didn't have to expose yourself like that

**Comment by OfficeGeek888** [comment]
> put a "quickie" from the front page or something at least man. you didn't have to expose yourself like that

What for? I'm not ashamed of what I am.

**Comment by Yakabuff** [comment]
Currently investigating.  From what I've seen, it should work the same way; just a different URL scheme and metadata location

**Comment by Yakabuff** [comment]
Quickie video urls can be translated to a regular video url 

eg: https://www.xvideos.com/profiles/firolix#quickies/a/51392867 -> https://www.xvideos.com/video51392867/<title>

Everything from the XVideosIE can be reused as long as we create a wrapper to convert the URL

Side note: There's an API to fetch all quickies from any given user

https://www.xvideos.com/quickies-api/profileinfos/all/straight/N/<uuid>

**Comment by Yakabuff** [comment]
Making a PR

**Comment by OfficeGeek888** [comment]
> Quickie video urls can be translated to a regular video url
> 
> eg: https://www.xvideos.com/profiles/firolix#quickies/a/51392867 -> https://www.xvideos.com/video51392867/<title>
> 
> Everything from the XVideosIE can be reused as long as we create a wrapper to convert the URL
> 
> Side note: There's an API to fetch all quickies from any given user
> 
> eg: https://www.xvideos.com/quickies-api/profileinfos/all/straight/N/ id

Hot diggety, It worked!

Thanks!

**Comment by gom3sr** [comment]
Quickies can not be downloaded with yt-dlp. I've tested with both yt-dlp 2023.09.24 and the latest nightly [2023.10.03.093359](https://github.com/yt-dlp/yt-dlp-nightly-builds/releases/tag/2023.10.03.093359)

Links: 
https://www.xvideos.com/profiles/cgr082395#quickies/a/54114693
https://www.xvideos.com/profiles/zikazsulsp#quickies/a/61358657

C:\testfolder>yt-dlp -vU https://www.xvideos.com/profiles/zikazsulsp#quickies/a/61358657
[debug] Command-line config: ['-vU', 'https://www.xvideos.com/profiles/zikazsulsp#quickies/a/61358657']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.09.24 [088add956] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-110533-g2d43c23b81-20230508 (setts), ffprobe N-110533-g2d43c23b81-20230508, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.07.22, mutagen-1.47.0, sqlite3-3.35.5, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1886 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.09.24, Current version: stable@2023.09.24
Current Build Hash: 125465ac4416bcd4bf1632b899630ceecc08b341e83fdf10bd34700c58ea5152
yt-dlp is up to date (stable@2023.09.24)
[generic] Extracting URL: https://www.xvideos.com/profiles/zikazsulsp#quickies/a/61358657
[generic] 61358657: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] 61358657: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://www.xvideos.com/profiles/zikazsulsp#quickies/a/61358657
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1567, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1702, in __extract_info
  File "yt_dlp\extractor\common.py", line 715, in extract
  File "yt_dlp\extractor\generic.py", line 2568, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.xvideos.com/profiles/zikazsulsp#quickies/a/61358657

**Comment by bashonly** [comment]
```diff
diff --git a/yt_dlp/extractor/xvideos.py b/yt_dlp/extractor/xvideos.py
index 5df071503..527dcf92e 100644
--- a/yt_dlp/extractor/xvideos.py
+++ b/yt_dlp/extractor/xvideos.py
@@ -161,4 +161,4 @@ def _real_extract(self, url):
 
 class XVideosQuickiesIE(InfoExtractor):
     IE_NAME = 'xvideos:quickies'
-    _VALID_URL = r'https?://(?P<domain>(?:[^/]+\.)?xvideos2?\.com)/amateur-channels/[^#]+#quickies/a/(?P<id>\d+)'
+    _VALID_URL = r'https?://(?P<domain>(?:[^/?#]+\.)?xvideos2?\.com)/(?:profiles|amateur-channels)/[^#]+#quickies/a/(?P<id>\d+)'
```

**Comment by gibigate** [comment]
Apologies, could someone please create a new ticket? Several days ago, Xvideos altered all of their video URLs, resulting in this library no longer recognizing the video formats.

**Comment by JakeFinley96** [comment]
XVideos seems to have updated their URL again.

**Changes:**
- IDs can have letters in them now _(so the current quickies URL check of: must have an ID consisting of only numbers is invalid)_.
- The correct quickies to video translation URL is now: `https://www.xvideos.com/video.QUICKIES_ID/_`

It's fairly easy to just dump all the quickies in a batch file and manually change the URLs, but would still be nice if it got updated.

**Comment by mo-han** [comment]
@JakeFinley96 
so the extractor is able to:
- download video url
- download quickies video url
but is unable to:
- fetch video urls from a channel/model
- fetch quickies urls from a channel/model

**Comment by JakeFinley96** [comment]
@mo-han this issue was specifically about fixing quickies being broken in the XVideos extractor. But looking at the core extractor it doesn't seem to support fetching multiple videos automatically, so you'd have to use a batch file for it and use the `--batch-file` argument.
