### ISSUE TITLE
[Enhancement] DRM errors should raise appropriate error

### ISSUE THREAD

**Issue by pukkandan** [yt-dlp/yt-dlp#636]
Maybe yt-dlp should display a warning when DRM-encumbered streams are detected instead of ignoring them silently? This way you can avoid spurious reports like this in the future.

_Originally posted by @fstirlitz in https://github.com/yt-dlp/yt-dlp/issues/609#issuecomment-891654324_

**Comment by pukkandan** [comment]
It is easily possible to print a warning whenever a DRM format is encountered. But a lot of extractors have videos with both DRM and non-DRM formats. So we cannot simply raise an error. Also, even if there is a warning, if the error message itself asks the user to "report the bug", we will keep getting these reports.

Due to the way the extractor code is structured, I cannot think of any clean way to record whether the "No formats found" is caused due to a DRM or not. Here is a somewhat hacky solution I came up with: https://github.com/pukkandan/yt-dlp-dev/commit/de3ce5f3e61ef100df95a396b3b0306d1b5e70f7

I would like to hear if you have any better ideas on how to approach this

**Comment by fstirlitz** [comment]
We could *always* extract DRM-restricted streams into the `formats` list, but mark them with a special key, and have selectors ignore them unless `--allow-unplayable-formats` is passed.
