### ISSUE TITLE
Please someone help me .   Error: not found: YoutubeDL

### ISSUE THREAD

**Issue by NabiiBux** [yt-dlp/yt-dlp#6361]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.02.17** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Hello, I am Installing ytdlp on windows 10.
I am trying to transcribe audio with this repo . https://github.com/mayeaux/generate-subtitles
In the documentation mentioned I properly installed ytdlp you can the verbose outputs.
When i run npm start with https://github.com/mayeaux/generate-subtitles this repo I am failing and getting error 

Error: not found: YoutubeDL  . The screenshot is Attached Please Check. [https://github.com/NabiiBux/errors/blob/main/problem.JPG] (url)

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2023.02.17 [a0a7c01] (pip)
[debug] Python 3.10.1 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1l  24 Aug 2021)
[debug] exe versions: ffmpeg 2022-06-09-git-5d5a014199-full_build-www.gyan.dev (setts), ffprobe 2022-06-09-git-5d5a014199-full_build-www.gyan.dev
[debug] Optional libraries: certifi-2021.10.08, sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Loaded 1782 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2023.02.17, Current version: 2023.02.17
yt-dlp is up to date (2023.02.17
```

**Comment by bashonly** [comment]
See: https://github.com/mayeaux/generate-subtitles/issues/51

Since you are able to run yt-dlp by itself without problems, this is not a yt-dlp issue.
