### ISSUE TITLE
support for xcadr.tv 

### ISSUE THREAD

**Issue by estatistics** [yt-dlp/yt-dlp#6362]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2023.02.17** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

greece

### Example URLs

single video can be downloaded, not playlists 
playlists: https://xcadr.tv/celebs/golaya-angelina-strechina/

### Provide a description that is worded well enough to be understood
to download whole playlists from xcadr.tv

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
`yt-dlp -vU https://xcadr.tv/celebs/golaya-angelina-strechina/
WARNING: Could not read zip file /usr/local/lib/python3.9/dist-packages/instaloader-4.9.5-py3.9.egg: [Errno 21] Is a directory: '/usr/local/lib/python3.9/dist-packages/instaloader-4.9.5-py3.9.egg'
[debug] Command-line config: ['-vU', 'https://xcadr.tv/celebs/golaya-angelina-strechina/']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2023.02.17 [a0a7c01] (pip)
[debug] Python 3.9.4 (CPython x86_64 64bit) - Linux-5.11.0-18-generic-x86_64-with-glibc2.33 (OpenSSL 1.1.1n  15 Mar 2022, glibc 2.33)
[debug] exe versions: ffmpeg 4.3.5-0, ffprobe 4.3.5-0
[debug] Optional libraries: Cryptodome-3.16.0, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, secretstorage-3.3.1, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1782 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2023.02.17, Current version: 2023.02.17
yt-dlp is up to date (2023.02.17)
[generic] Extracting URL: https://xcadr.tv/celebs/golaya-angelina-strechina/
[generic] golaya-angelina-strechina: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] golaya-angelina-strechina: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://xcadr.tv/celebs/golaya-angelina-strechina/
Traceback (most recent call last):
  File "/home/elias/.local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1502, in wrapper
    return func(self, *args, **kwargs)
  File "/home/elias/.local/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1578, in __extract_info
    ie_result = ie.extract(url)
  File "/home/elias/.local/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 693, in extract
    ie_result = self._real_extract(url)
  File "/home/elias/.local/lib/python3.9/site-packages/yt_dlp/extractor/generic.py", line 2509, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://xcadr.tv/celebs/golaya-angelina-strechina/
`
```

**Comment by bashonly** [comment]
> - [x] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) ... to the best of my knowledge

Looks like a piracy site. Explain your reason to believe otherwise

**Comment by estatistics** [comment]
i dont know for other videos... but videos of golaya-angelina-strechina I have found them only here - i dont know. Youtube also can be theorized a piracy site (films, cut scenes, even sensual / sex videos).... or xhamster. It seems to contains only "short videos", cut scenes of films. I think it is "much more legal" than some other sites :)
