### ISSUE TITLE
How do I dl highest bitrate/merge like original youtube-dl using yt-dlp?

### ISSUE THREAD

**Issue by goodstuff626** [yt-dlp/yt-dlp#6363]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.02.17** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I would like to download the same way original youtube-dl would choose the highest bitrate video+ audio, then merge using yt-dlp. Is there a command line I can use to achieve this?

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
> download the same way original youtube-dl would choose the highest bitrate video+ audio

https://github.com/yt-dlp/yt-dlp#differences-in-default-behavior
`--compat-options format-sort`

> then merge using yt-dlp

Merging is done with ffmpeg when using youtube-dl or yt-dlp. Make sure [ffmpeg](https://github.com/yt-dlp/FFmpeg-Builds#downloads) is installed in and in your PATH. (If you're on windows, the easiest way to ensure this is to copy `ffmpeg.exe` and `ffprobe.exe` into the same folder as `yt-dlp.exe`)
