### ISSUE TITLE
I don't want to download videos, I want to get the IDs of all videos uploaded to youtube today. But my command isn't working.

### ISSUE THREAD

**Issue by HTneko** [yt-dlp/yt-dlp#6365]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.02.17** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I don't want to download videos, I want to get the IDs of all videos uploaded to youtube today. But my command isn't working.

my command:
yt-dlp "ytsearchdate:today" --get-id

I ran the command, but it only returned one video ID, which is obviously incorrect.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'ytsearchdate:today', '--get-id']
[debug] Encodings: locale cp936, fs utf-8, pref cp936, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2023.02.17 [a0a7c01] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19044-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {'http': 'http://127.0.0.1:7890', 'https': 'https://127.0.0.1:7890', 'ftp': 'ftp://127.0.0.1:7890'}
[debug] Loaded 1782 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2023.02.17, Current version: 2023.02.17
yt-dlp is up to date (2023.02.17)
[youtube:search:date] Extracting URL: ytsearchdate:today
[download] Downloading playlist: today
[youtube:search:date] query "today": Downloading web client config
[youtube:search:date] query "today" page 1: Downloading API JSON
[youtube:search:date] Playlist today: Downloading 1 items of 1
[download] Downloading item 1 of 1
[youtube] Extracting URL: https://www.youtube.com/watch?v=RjkPy3MSh2U
[youtube] RjkPy3MSh2U: Downloading webpage
[youtube] RjkPy3MSh2U: Downloading android player API JSON
[youtube] RjkPy3MSh2U: Downloading m3u8 information
[youtube] RjkPy3MSh2U: Downloading MPD manifest
[youtube] RjkPy3MSh2U: Downloading m3u8 information
[youtube] RjkPy3MSh2U: Downloading MPD manifest
[debug] [youtube] RjkPy3MSh2U: Video is in Post-Live Manifestless mode
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] RjkPy3MSh2U: Downloading 1 format(s): 301
RjkPy3MSh2U
[download] Finished downloading playlist: today
```

**Comment by coletdjnz** [comment]
try `yt-dlp ytsearchdateall:today --print id --flat-playlist`

(note youtube only shows a small subset of "videos uploaded today" in the search feed)

**Comment by HTneko** [comment]
> try `yt-dlp ytsearchdateall:today --print id --flat-playlist`
> 
> (note youtube only shows a small subset of "videos uploaded today" in the search feed)

Thank you! Your command was able to produce a result. However, the problem is that when I stored the result through a pipeline in a txt file:
`yt-dlp ytsearchdateall:today --print id --flat-playlist > 1.txt`
I found that the obtained results were not entirely videos published today when I crawled the video release dates. Can you please tell me why this is happening?

![image](https://user-images.githubusercontent.com/65443985/221546596-e079faac-9cf5-43b7-991d-91a0e041ecaa.png)

**Comment by pukkandan** [comment]
`ytsearchdateall:abcd` means search youtube for "abcd", sorted by date, which is just equivalent to https://www.youtube.com/results?search_query=abcd&sp=CAI%253D

Unless you know of a link where youtube lists "all videos uploaded today", what you want cannot be done. We can only download data youtube actually provides

**Comment by pukkandan** [comment]
https://www.youtube.com/results?search_query=&sp=EgIIAg%253D%253D is the closest I found. About a million videos get uploaded to youtube every day - you are not going to get the full list

**Comment by HTneko** [comment]
> https://www.youtube.com/results?search_query=+&sp=EgIIAg%253D%253D is the closest I found. About a million videos get uploaded to youtube every day - you are not going to get the full list

I got it! Thank you for your patience!
