### ISSUE TITLE
How to add a supported website ?

### ISSUE THREAD

**Issue by Menard01** [yt-dlp/yt-dlp#6368]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.02.17** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Hello
How to add supported websites we ve personnaly found, to your list of supported websites ? 

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp -vU
[debug] Command-line config: ['-vU']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.05.18 [b14d52355]
[debug] Python version 3.8.10 (CPython 64bit) - Linux-5.15.0-46-generic-x86_64-with-glibc2.29
[debug] Checking exe version: ffprobe -bsfs
[debug] Checking exe version: ffmpeg -bsfs
[debug] exe versions: ffmpeg 4.2.7, ffprobe 4.2.7
[debug] Optional libraries: Cryptodome-3.14.1, brotli-1.0.9, certifi-2019.11.28, mutagen-1.45.1, secretstorage-2.3.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
Latest version: 2023.02.17, Current version: 2022.05.18
ERROR: It looks like you installed yt-dlp with a package manager, pip or setup.py; Use that to update
```

**Comment by Menard01** [comment]
Concerning the result of this command, that has nothon to do with the subject of this topic, my current version is really the last one when I execute the command sudo yt-dlp -U

**Comment by Menard01** [comment]
Concerning the result of this command, that has nothing to do with the subject of this topic, my current version is really the last one when I execute the command sudo yt-dlp -U

**Comment by pukkandan** [comment]
Your question is unclear. Are you asking about a site you own? Or how to write an extractor? Or how to request for a site support?

**Comment by Menard01** [comment]
No, it is incredible, I only want to add a supported site, it simple, very clear

**Comment by Menard01** [comment]
It is none of your proposals, don't make things complicated
If I could download videos from one website, that proves it works though it is not in the supported sites list

**Comment by pukkandan** [comment]
Many sites work "magically" without being actually supported. See [this wiki entry](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-can-i-detect-whether-a-given-url-is-supported-by-yt-dlp). They will not be added to the list
