### ISSUE TITLE
Facebook Unsupported URL

### ISSUE THREAD

**Issue by RfadnjdExt** [yt-dlp/yt-dlp#6370]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a broken site
- [X] I've verified that I'm running yt-dlp version **2023.02.17** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [ ] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Indonesia

### Provide a description that is worded well enough to be understood

Hi, I'm trying to download [facebook video](https://m.facebook.com/story.php?story_fbid=pfbid024vUxjBfj1e47XgDEcKzZVyYkMcSPkG5djVberxqBZd7fAfRczyNT14NWqZZjuDjil&id=533735689&sfnsn=wiwspwa&mibextid=RUbZ1f) but I got yt_dlp.utils.UnsupportedError instead. I think the genereic redirect to the wrong URL? (Maybe because the desktop User-Agent) I try to open it without login and it play the video.

yt-dlp redirect: https://www.facebook.com/login/?next=https%3A%2F%2Fwww.facebook.com%2Fstory.php%3Fstory_fbid%3Dpfbid024vUxjBfj1e47XgDEcKzZVyYkMcSPkG5djVberxqBZd7fAfRczyNT14NWqZZjuDjil%26id%3D533735689%26sfnsn%3Dwiwspwa%26mibextid%3DRUbZ1f
browser location headers: https://www.facebook.com/story.php?story_fbid=pfbid024vUxjBfj1e47XgDEcKzZVyYkMcSPkG5djVberxqBZd7fAfRczyNT14NWqZZjuDjil&id=533735689&sfnsn=wiwspwa&mibextid=RUbZ1f&_rdr

I have try to use the redirected URL instead bot no luck, same error. So my current workaround is parsing the MPD myself. Maybe I'm gonna lookaround at the generic/facebook extractor for a moment.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://m.facebook.com/story.php?story_fbid=pfbid024vUxjBfj1e47XgDEcKzZVyYkMcSPkG5djVberxqBZd7fAfRczyNT14NWqZZjuDjil&id=533735689&sfnsn=wiwspwa&mibextid=RUbZ1f']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2023.02.17 [a0a7c0154] (source)
[debug] Lazy loading extractors is disabled
[debug] Git HEAD: 8e9fe43cd
[debug] Python 3.10.4 (CPython x86_64 64bit) - Linux-5.4.0-1103-azure-x86_64-with-glibc2.31 (OpenSSL 1.1.1f  31 Mar 2020, glibc 2.31)
[debug] exe versions: none
[debug] Optional libraries: certifi-2022.12.07, sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Loaded 1782 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2023.02.17, Current version: 2023.02.17
yt-dlp is up to date (2023.02.17)
[generic] Extracting URL: https://m.facebook.com/story.php?story_fbid=pfbid024vUxjBfj1e47XgDEcKzZVyYkMcSPkG5djVberxqBZd7fAfRczyNT14NWqZZjuDjil&id=533735689&sfnsn=wiwspwa&mibextid=RUbZ1f
[generic] story: Downloading webpage
[redirect] Following redirect to https://www.facebook.com/login/?next=https%3A%2F%2Fwww.facebook.com%2Fstory.php%3Fstory_fbid%3Dpfbid024vUxjBfj1e47XgDEcKzZVyYkMcSPkG5djVberxqBZd7fAfRczyNT14NWqZZjuDjil%26id%3D533735689%26sfnsn%3Dwiwspwa%26mibextid%3DRUbZ1f
[generic] Extracting URL: https://www.facebook.com/login/?next=https%3A%2F%2Fwww.facebook.com%2Fstory.php%3Fstory_fbid%3Dpfbid024vUxjBfj1e47XgDEcKzZVyYkMcSPkG5djVberxqBZd7fAfRczyNT14NWqZZjuDjil%26id%3D533735689%26sfnsn%3Dwiwspwa%26mibextid%3DRUbZ1f
[generic] ?next=https://www.facebook.com/story: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] ?next=https://www.facebook.com/story: Extracting information
[debug] Looking for embeds
[redirect] Following redirect to https://www.facebook.com/login/?next=https%3A%2F%2Fwww.facebook.com%2Fstory.php%3Fstory_fbid%3Dpfbid024vUxjBfj1e47XgDEcKzZVyYkMcSPkG5djVberxqBZd7fAfRczyNT14NWqZZjuDjil%26id%3D533735689%26sfnsn%3Dwiwspwa%26mibextid%3DRUbZ1f&_fb_noscript=1
[generic] Extracting URL: https://www.facebook.com/login/?next=https%3A%2F%2Fwww.facebook.com%2Fstory.php%3Fstory_fbid%3Dpfbid024vUxjBfj1e47XgDEcKzZVyYkMcSPkG5djVberxqBZd7fAfRczyNT14NWqZZjuDjil%26id%3D533735689%26sfnsn%3Dwiwspwa%26mibextid%3DRUbZ1f&_fb_noscript=1
[generic] ?next=https://www.facebook.com/story: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] ?next=https://www.facebook.com/story: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://www.facebook.com/login/?next=https%3A%2F%2Fwww.facebook.com%2Fstory.php%3Fstory_fbid%3Dpfbid024vUxjBfj1e47XgDEcKzZVyYkMcSPkG5djVberxqBZd7fAfRczyNT14NWqZZjuDjil%26id%3D533735689%26sfnsn%3Dwiwspwa%26mibextid%3DRUbZ1f&_fb_noscript=1
Traceback (most recent call last):
  File "/workspaces/codespaces-blank/yt-dlp/yt_dlp/YoutubeDL.py", line 1502, in wrapper
    return func(self, *args, **kwargs)
  File "/workspaces/codespaces-blank/yt-dlp/yt_dlp/YoutubeDL.py", line 1578, in __extract_info
    ie_result = ie.extract(url)
  File "/workspaces/codespaces-blank/yt-dlp/yt_dlp/extractor/common.py", line 693, in extract
    ie_result = self._real_extract(url)
  File "/workspaces/codespaces-blank/yt-dlp/yt_dlp/extractor/generic.py", line 2509, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.facebook.com/login/?next=https%3A%2F%2Fwww.facebook.com%2Fstory.php%3Fstory_fbid%3Dpfbid024vUxjBfj1e47XgDEcKzZVyYkMcSPkG5djVberxqBZd7fAfRczyNT14NWqZZjuDjil%26id%3D533735689%26sfnsn%3Dwiwspwa%26mibextid%3DRUbZ1f&_fb_noscript=1
```

**Comment by october262** [comment]
right click on the 3 dots ... next to where it says FOLLOW and select
copy link address and feed it into yt-dlp to download the video.

**Comment by RfadnjdExt** [comment]
Sorry, i forgot had a different IP, I'm trying to use my VPS to download the video and checked in my local browser (Idk why it's different, due to different region?). Thank you btw. Closing.
