### ISSUE TITLE
There is a problem after downloading the video

### ISSUE THREAD

**Issue by senanoguz** [yt-dlp/yt-dlp#6372]
my command: yt-dlp -x --audio-format mp3 {youtube_link} -o 'downloads/{youtube_id}.mp3

output:
web_1  | [youtube] Extracting URL: https://www.youtube.com/watch?v=vHX4i1YlvEo
web_1  | [youtube] vHX4i1YlvEo: Downloading webpage
web_1  | [youtube] vHX4i1YlvEo: Downloading android player API JSON
web_1  | [info] vHX4i1YlvEo: Downloading 1 format(s): 251
web_1  | [download] Destination: downloads/vHX4i1YlvEo.webm

It stays like the last post for 3 days.
What could be the reason for this?
I've never had a problem before

**Comment by Mutty99** [comment]
I suppose you already have ffmpeg installed and in the path variable?

**Comment by senanoguz** [comment]
yes ffmpeg is installed.

It has already worked
output:
web_1 | https://www.youtube.com/watch?v=LWZolIvzAPk
web_1 | [youtube] Extracting URL: https://www.youtube.com/watch?v=LWZolIvzAPk
web_1 | [youtube] LWZolIvzAPk: Downloading webpage
web_1 | [youtube] LWZolIvzAPk: Downloading android player API JSON
web_1 | [info] LWZolIvzAPk: Downloading 1 format(s): 251
web_1 | [download] Destination: downloads/LWZolIvzAPk.webm
[download] 100% of 3.34MiB in 00:00:00 at 47.65MiB/s
web_1 | [ExtractAudio] Destination: downloads/LWZolIvzAPk.mp3
web_1 | Deleting original file downloads/LWZolIvzAPk.webm (pass -k to keep)

**Comment by senanoguz** [comment]
i DockerFile is down code
FROM nikolaik/python-nodejs:python3.9-nodejs16
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
RUN apt-get update -y && apt-get upgrade -y \
    && apt-get install -y --no-install-recommends ffmpeg \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
RUN mkdir /code
WORKDIR /code

ENTRYPOINT ["sh", "./docker_entrypoint.sh"]

RUN pip install --upgrade pip

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY . .

and have requirements.txt in 
yt-dlp
ffmpeg-python

**Comment by pukkandan** [comment]
Learn to follow instructions
