### ISSUE TITLE
Hello, my download is very slow when I download from YouTube, but it is very fast on other websites 

### ISSUE THREAD

**Issue by x72x** [yt-dlp/yt-dlp#6374]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.02.17** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Is this considered normal?

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[youtube] Extracting URL: https://youtu.be/JQ51XBDXujU
[youtube] JQ51XBDXujU: Downloading webpage                         [youtube] JQ51XBDXujU: Downloading android player API JSON
[download] Destination: Ragheb Alama - Elli Baana  (Official Lyrics Video) ⧸ راغب ع�ا�
                   ة - ا���باع�� [JQ51XBDXujU].m4a
[download]  15.1% of    4.17MiB at   31.37KiB/s ETA 01:55
```

**Comment by pukkandan** [comment]
https://github.com/yt-dlp/yt-dlp/issues/6369
