### ISSUE TITLE
Is there a way to replace "|" in Youtube filenames with "-" (or any other separater)

### ISSUE THREAD

**Issue by tinglycraniumplacidly** [yt-dlp/yt-dlp#6380]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.02.17** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

When I download a video from youtube like
https://www.youtube.com/watch?v=3gg1OS435UE

the filename comes out to:

> Dr. Becky - Evidence for black holes being dark energy？! ｜ Night Sky News February 2023.webm

I'm currently using 
`-o '%(uploader,creator,channel,webpage_url_basename)s - %(title)s.%(ext)s'` to format the filename, and I didn't see any way to manipulate individual fields like title.

I really hate the | separater that seems to be new to Youtube video names because it affects line height with a lot of fonts. Is there a way that yt-dlp can replace them with a - ? or does it need to be processed afterwards via another mechanism.

Thanks!

### Provide verbose output that clearly demonstrates the problem

- [x] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [x] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

> yt-dlp -vU -o '%(uploader,creator,channel,webpage_url_basename)s - %(title)s.%(ext)s' https://www.youtube.com/watch?v=3gg1OS435UE
> [debug] Command-line config: ['-vU', '-o', '%(uploader,creator,channel,webpage_url_basename)s - %(title)s.%(ext)s', 'https://www.youtube.com/watch?v=3gg1OS435UE']
> [debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
> [debug] yt-dlp version 2023.02.17 [a0a7c01] (pip)
> [debug] Python 3.10.7 (CPython x86_64 64bit) - Linux-5.19.0-1017-lowlatency-x86_64-with-glibc2.36 (OpenSSL 3.0.5 5 Jul 2022, glibc 2.36)
> [debug] exe versions: ffmpeg 5.1.1 (setts), ffprobe 5.1.1, rtmpdump 2.4
> [debug] Optional libraries: Cryptodome-3.11.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, pyxattr-0.7.2, secretstorage-3.3.3, sqlite3-2.6.0, websockets-10.2
> [debug] Proxy map: {}
> [debug] Loaded 1782 extractors
> [debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
> Latest version: 2023.02.17, Current version: 2023.02.17
> yt-dlp is up to date (2023.02.17)
> [youtube] Extracting URL: https://www.youtube.com/watch?v=3gg1OS435UE
> [youtube] 3gg1OS435UE: Downloading webpage
> [youtube] 3gg1OS435UE: Downloading android player API JSON
> [debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
> [debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
> [debug] Default format spec: bestvideo*+bestaudio/best
> [info] 3gg1OS435UE: Downloading 1 format(s): 248+251
> [debug] Invoking http downloader on "https://rr5---sn-vgqsknze.googlevideo.com/videoplayback?expire=1677626254&ei=Ljf-Y4vHFMS0lu8PusW-mAg&ip=68.235.43.101&id=o-AIQmX3RPrpZuKiFWoTESumbhEh01C-2w1y4sjn9JlHQW&itag=248&source=youtube&requiressl=yes&mh=Dm&mm=31%2C29&mn=sn-vgqsknze%2Csn-vgqsrnsr&ms=au%2Crdu&mv=m&mvi=5&pl=24&initcwndbps=311250&spc=H3gIhmlc9oRm_CXnYicdxx6VpsPqK78&vprv=1&svpuc=1&mime=video%2Fwebm&gir=yes&clen=306086810&dur=2307.833&lmt=1677307629764028&mt=1677604160&fvip=2&keepalive=yes&fexp=24007246&c=ANDROID&txp=5535434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRAIgcUkgfrzjBYtE_Eq0UrzXRa4duiIPb8jQwNF2kvnQyqMCIGpT5cRXrECKsPSKYknCE60-kYigD2S0Qj6QO9ZIsa6s&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhAO930f69eDWNfC5Tt_F6YXhGzwkflsJPUc3z38GkuY5DAiASxstj3nzUiRFZtcIcd9QfKJksfRFk0O8e9gNYfS0TaQ%3D%3D"
> [download] Destination: Dr. Becky - Evidence for black holes being dark energy？! ｜ Night Sky News February 2023.f248.webm

**Comment by pukkandan** [comment]
--replace-in-metadata title "[|]" "-"

**Comment by tinglycraniumplacidly** [comment]
awesome thank you!
