### ISSUE TITLE
[VIMEO] The embbed video display with joined audio and video but links referes to splitted audio and video 

### ISSUE THREAD

**Issue by faylong** [yt-dlp/yt-dlp#6382]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.02.17** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

How do i download audio and video ? 

Instead they give just one file with mp4 it appear trimmed audio and video. The embbed video plays audio and video together, but when inspected it splits in two.

https://190vod-adaptive.akamaized.net/exp=1677706902~acl=/d09fdbc0-929c-49a3-b6fc-ef5e302ff2bd/*~hmac=10d0436ab413f5d0c4efe258deada8d064bb174d8f8df44fe14089aa333373c2/d09fdbc0-929c-49a3-b6fc-ef5e302ff2bd/parcel/**video**/xxxxxxx.mp4 

 https://190vod-adaptive.akamaized.net/exp=1677706902~acl=/d09fdbc0-929c-49a3-b6fc-ef5e302ff2bd/*~hmac=10d0436ab413f5d0c4efe258deada8d064bb174d8f8df44fe14089aa333373c2/d09fdbc0-929c-49a3-b6fc-ef5e302ff2bd/parcel/**audio**/yyyyyyy.mp4.

I'm lost about what to do. How do i download the same single file is displayed in embbed video ?

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
View the source of the webpage where it's embedded and find the `player.vimeo.com` URL. Run yt-dlp like this:

`yt-dlp "https://player.vimeo.com/..." --referer "https://website-where-it-is-embedded.com/page.html"`

Don't bother asking for additional help unless you will share a verbose log, or at least the webpage/player URLs

**Comment by faylong** [comment]
Hello bashonly thanks for returning.

The video is privated:
https://player.vimeo.com/video/798516789

When u try to access u get the message:
Sorry 
Because of its privacy settings, this video cannot be played here.

**Comment by bashonly** [comment]
`yt-dlp "https://player.vimeo.com/video/798516789?h=a805ea259f" --referer "WEBPAGE"`

replace `WEBPAGE` with the URL of the webpage where this video is embedded (NOT a vimeo.com URL)

if you need any additional help you will need to share the webpage URL and show a log of what you have tried

**Comment by faylong** [comment]
![image](https://user-images.githubusercontent.com/126632365/222024975-5f5440bf-1418-4726-b635-1b4691f31faf.png)

I think it's downloading with this command you shared. But it seem will take so much time

**Comment by observeroftime01** [comment]
It appears you don't have ffmpeg installed, or not added to your PATH correctly, hence the issues with merging the two formats.

**Comment by pukkandan** [comment]
As for speed, use `-N`

**Comment by papsphilip** [comment]
> URL of the webpage where this video is embedded (NOT a vimeo.com URL)

how can i get that?
