### ISSUE TITLE
urlopen error EOF occurred in violation of protocol (_ssl.c:1131)

### ISSUE THREAD

**Issue by bjm1948** [yt-dlp/yt-dlp#6388]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2023.02.17** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

I am getting the following error:

urllib.error.URLError: <urlopen error EOF occurred in violation of protocol (_ssl.c:1131)

The error occurs on all sites that I have tried.

The error started after the 2022.11.11 update and continues with the latest update (2023.02.17)

The 2022.10.04 release still works on some sites, eg. DailyMotion and Vimeo, but no longer on YouTube.

From earlier issues on the bugtracker it seems that this error is proxy related. But how would this explain the fact that it works on one version but not on the next using the same proxy. Could it be that the version update made the program less forgiving of proxy configuration or mis-configuration? Unfortunately I do not have the option of changing to a different proxy.
 

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['--proxy', 'https://xxxx:xxxx@xxx.xx.xxx.xxx:xxx', '-v', '--no-check-certificates', 'https://www.dailymotion.com/video/x8ipstv']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out cp1252 (No ANSI), error utf-8, screen cp1252 (No ANSI)
[debug] yt-dlp version 2023.02.17 [a0a7c01] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg git-2019-12-26-b0d0d7e, ffprobe 4.0.2
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {'http': 'https://xxxx:xxxx@xxx.xx.xxx.xxx:xxx', 'https': 'https://xxxx:xxxx@xxx.xx.xxx.xxx:xxx'}
[debug] Loaded 1782 extractors
ERROR: [dailymotion] x8ipstv: Unable to download JSON metadata: <urlopen error EOF occurred in violation of protocol (_ssl.c:1131)> (caused by URLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
  File "yt_dlp\extractor\common.py", line 693, in extract
  File "yt_dlp\extractor\dailymotion.py", line 231, in _real_extract
  File "yt_dlp\extractor\dailymotion.py", line 66, in _call_api
  File "yt_dlp\extractor\common.py", line 1047, in download_content
  File "yt_dlp\extractor\common.py", line 1011, in download_handle
  File "yt_dlp\extractor\common.py", line 881, in _download_webpage_handle
  File "yt_dlp\extractor\common.py", line 838, in _request_webpage

  File "urllib\request.py", line 1354, in do_open
  File "http\client.py", line 1252, in request
  File "http\client.py", line 1298, in _send_request
  File "http\client.py", line 1247, in endheaders
  File "http\client.py", line 1007, in _send_output
  File "http\client.py", line 947, in send
  File "http\client.py", line 1421, in connect
  File "ssl.py", line 500, in wrap_socket
  File "ssl.py", line 1040, in _create
  File "ssl.py", line 1309, in do_handshake
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\extractor\common.py", line 820, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 3726, in urlopen
  File "urllib\request.py", line 525, in open
  File "urllib\request.py", line 542, in _open
  File "urllib\request.py", line 502, in _call_chain
  File "yt_dlp\utils.py", line 1532, in https_open
  File "urllib\request.py", line 1357, in do_open
urllib.error.URLError: <urlopen error EOF occurred in violation of protocol (_ssl.c:1131)>

-----------

Here is the -v output using 2022.10.04 release

[debug] Command-line config: ['--proxy', 'https://xxxx:xxxx@xxx.xx.xxx.xxx:xxx', '-v', '--no-check-certificates', 'https://www.dailymotion.com/video/x8ipstv']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2022.10.04 [4e0511f] (win32_exe)
[debug] Python 3.8.10 (CPython 64bit) - Windows-10-10.0.19045-SP0
[debug] Checking exe version: ffmpeg -bsfs
[debug] Checking exe version: ffprobe -bsfs
[debug] exe versions: ffmpeg git-2019-12-26-b0d0d7e, ffprobe 4.0.2
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {'http': 'https://xxxx:xxxx@xxx.xx.xxx.xxx:xxx', 'https': 'https://xxxx:xxxx@xxx.xx.xxx.xxx:xxx'}
[debug] Loaded 1690 extractors
[debug] [dailymotion] Extracting URL: https://www.dailymotion.com/video/x8ipstv
[dailymotion] Downloading Access Token
[dailymotion] x8ipstv: Downloading media JSON metadata
[dailymotion] x8ipstv: Downloading metadata JSON
[dailymotion] x8ipstv: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] x8ipstv: Downloading 1 format(s): http-1080-1
[debug] Invoking http downloader on "https://proxy-26.sv4.dailymotion.com/sec(Fv_fkf_PGuaIxoIb3TIJoP-gWqBuoFNyMwgGEjYuSwW_EfQhd90qza7Rr6QnM-mYahHpAs5yigzLkywZrPWy5w)/video/952/661/515166259_mp4_h264_aac_fhd_1.mp4"
[download] Former CBS Broadcaster and NFL Star Irv Cross Posthumously Diagnosed With CTE [x8ipstv].mp4 has already been downloaded
[download] 100% of   36.39MiB
```

**Comment by coletdjnz** [comment]
Is your proxy https only? yt-dlp does not currently support https proxies (see https://github.com/yt-dlp/yt-dlp/issues/1890)

**Comment by bjm1948** [comment]
As far as I know the proxy is not HTTPS only. It is given to me as HTTP://url:port.
The question is why would it work (and still work right now on some sites) using the 2022.10.04
release and not work with subsequent releases.

**Comment by coletdjnz** [comment]
> As far as I know the proxy is not HTTPS only. It is given to me as [HTTP://url:port](HTTP://url:port). The question is why would it work (and still work right now on some sites) using the 2022.10.04 release and not work with subsequent releases.

I misread, sorry. Try passing the proxy as `http` instead of `https`?

I'll try have a look at what relevant changes there might have been between those versions.

**Comment by coletdjnz** [comment]
Try using `--legacy-server-connect`?

It that works, it could possibly be due to [this](https://github.com/yt-dlp/yt-dlp/commit/5b9f253fa0aee996cf1ed30185d4b502e00609c4), which would suggest if you ran 2022.10.04 on python 3.10 you would encounter the same issue. 

In this case it's *probably* an issue with your proxy server. I'm guessing by you using `--no-check-certificate` it is inspecting your traffic (MITM), and part of that process is probably causing issues with the more modern ciphers (or something along those lines)

**Comment by bjm1948** [comment]
Thanks a  lot, `--legacy-server-connect` handled it.
