### ISSUE TITLE
How can I generate a text file containing the urls of videos that didn't get downloaded ?

### ISSUE THREAD

**Issue by Obika1871** [yt-dlp/yt-dlp#6389]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.02.17** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Hi,

I am on windows. Here's the command that I am currently using :
`yt-dlp --output "E:\My\Path\%(uploader)s\%(id)s.%(ext)s" -a "E:\My\Path\URLs.txt" --format "bv*+ba/b" --download-archive "E:\My\Path\download-archive.txt"`

I am downloading thousands of videos at a time, and dozens of them don't get downloaded (errors). That's fine and expected. But after that, I would like to have a list of the urls of videos that didn't get downloaded.

Basically, I would like yt-dlp to behave that way : If a video can be downloaded from the URL, download it. If a video cannot be downloaded from a URL, then write that URL to a text file.

Other solutions, such as printing the list of urls that didn't get downloaded at the end of program (which I would then just copy and paste to a text file myself), would be fine too. I am just trying to get a list that contains **only** the urls that didn't get downloaded, with one url per line or separated by a space.

I combed the readme and tried to use `--print-to-file` but, either I didn't use it right, or that's not adapted for what I am trying to do. Either way I am a complete novice so I might have missed a very obvious way to do what I am trying to do... sorry if that's the case.

I tried to see if someone had asked a similar question but I couldn't find any. I did find this [reddit thread](https://www.reddit.com/r/youtubedl/comments/jlda14/how_would_you_make_ytdl_give_you_a_text_file_of/) on r/youtubedl of someone trying to do something really similar, but the responses didn't give a solution (adding `2>> output.err` to the command is one step closer but still not what I'm trying to do).

So my question is, can yt-dlp do this ? If so, how ?

Edit : Also, since I am using `--download-archive` in my command, I thought of running the program twice. First time to download everything that can be downloaded, and then a second time, with parameters that would hide all of the "has already been recorded in the archive", "WARNING" and "ERROR" messages, leaving me with only the URLs that are trying to be extracted again, which would be pretty much a list of the urls that didn't get downloaded. But I couldn't find the right parameters combination to do that.

**Comment by pukkandan** [comment]
> So my question is, can yt-dlp do this ? If so, how ?

Not directly possible, no

> Edit : Also, since I am using `--download-archive` in my command, I thought of running the program twice. First time to download everything that can be downloaded, and then a second time, with parameters that would hide all of the "has already been recorded in the archive", "WARNING" and "ERROR" messages, leaving me with only the URLs that are trying to be extracted again, which would be pretty much a list of the urls that didn't get downloaded. But I couldn't find the right parameters combination to do that.

This is possible, but easier to use `--print-to-file` instead. Use `yt-dlp --print-to-file original_url downloaded.txt -a URLs.txt` to download and record all successful URLs. Then you can diff `downloaded.txt` with `URLs.txt` to find missing URLs

**Comment by Obika1871** [comment]
Perfect, that works. Thank you very much. After running your command I use `findstr /V /G:downloaded.txt URLs.txt >MissingURLs.txt` and it gives me exactly what I wanted : a text file containing the urls that didn't get downloaded, with one url per line, and no other header or data.

I'm glad that works, but a little bit surprised there is no "errored_url" value for --print-to-file, which would make this a lot easier. Would it be appropriate to transform this issue into a feature request ?

**Comment by pukkandan** [comment]
https://github.com/yt-dlp/yt-dlp/issues/1761
