### ISSUE TITLE
Error message when using the "-j" option

### ISSUE THREAD

**Issue by Jamu2800** [yt-dlp/yt-dlp#6404]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.02.17** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

This is about entering a URL that is not supported by the current version.
For example, suppose you execute the following command
`.\yt-dlp.exe -j https://google.com`

At this time, the error message displayed is as follows
```PowerShell
WARNING: [generic] Falling back on generic information extractor
ERROR: Unsupported URL: https://www.google.com/
```

The "-j" option is used to request output in Json format, but it does not seem to output in Json format if the URL does not support it.
My request would be to output the following when the "-j" option is used, but what do you think?
```json
{
    error: true
}
```

I have looked through the README.md and am sorry if there are any options I missed.
Also, I am not a good English speaker so I am using the help of a translation tool.
I apologize if I have written rude English.
Thank you for reading this far.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
https://github.com/yt-dlp/yt-dlp/issues/1659
