### ISSUE TITLE
How to downloads udemy resources, article and other files along video ?

### ISSUE THREAD

**Issue by iron-heart-x** [yt-dlp/yt-dlp#6405]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.02.17** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### How to downloads udemy resources, article and other files along video ?
I want to downloads udemy resources, article and other files with video. Is that possible ?
![image](https://user-images.githubusercontent.com/100769932/222746987-03b617e8-584e-46c9-815d-ce4e8d446fd9.png)

- I - Article
- II - Video
- III - Resources

No I Use ``` yt-dlp -c cookies.txt -o "%(playlist)s/%(chapter_number)s - %(chapter)s/%(title)s.%(ext)s" "some url" ``` cmd

Thanks In Advance **:)**

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
No, yt-dlp only downloads audio/video and their metadata. Anything else is out of scope
