### ISSUE TITLE
Tiktok, Qtweb for web extractor

### ISSUE THREAD

**Issue by zone559** [yt-dlp/yt-dlp#6409]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.02.17** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Hi there, I have a suggestion. I'm wondering if it's possible to use the QTweb engine to download TikTok videos. It appears that the extractor you're using may not extract TikTok profiles because it doesn't load all the necessary requirements to scrape the website. I've heard that 4ktokkit uses the QTengine to download TikTok videos, so maybe you could try incorporating it into yt-dlp.

Also, it would be great to have an option to download videos without the watermark and in an uncompressed format, similar to how it's done on this website: https://musicaldown.com/en.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
#4996
