### ISSUE TITLE
No such file or directory - completions/bash/yt-dlp

### ISSUE THREAD

**Issue by Goooler** [yt-dlp/yt-dlp#6411]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2023.03.03** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Updating via brew:

```sh
brew upgrade


==> Upgrading yt-dlp/taps/yt-dlp
  2023.2.17 -> 2023.3.3

==> python3.10 -m venv --system-site-packages /opt/homebrew/Cellar/yt-dlp/2023.3
==> /opt/homebrew/Cellar/yt-dlp/2023.3.3/libexec/bin/pip install -v --no-deps --
==> /opt/homebrew/Cellar/yt-dlp/2023.3.3/libexec/bin/pip install -v --no-deps --
==> /opt/homebrew/Cellar/yt-dlp/2023.3.3/libexec/bin/pip install -v --no-deps --
==> /opt/homebrew/Cellar/yt-dlp/2023.3.3/libexec/bin/pip install -v --no-deps --
==> /opt/homebrew/Cellar/yt-dlp/2023.3.3/libexec/bin/pip install -v --no-deps --
==> /opt/homebrew/Cellar/yt-dlp/2023.3.3/libexec/bin/pip install -v --no-deps --
Error: An exception occurred within a child process:
  Errno::ENOENT: No such file or directory - completions/bash/yt-dlp
```

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp -vU
[debug] Command-line config: ['-vU']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2023.02.17 [a0a7c01] (pip)
[debug] Python 3.10.10 (CPython arm64 64bit) - macOS-13.2.1-arm64-arm-64bit (OpenSSL 1.1.1t  7 Feb 2023)
[debug] exe versions: ffmpeg 5.1.2 (setts), ffprobe 5.1.2
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {'http': 'http://127.0.0.1:7890', 'https': 'http://127.0.0.1:7890'}
[debug] Loaded 1782 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2023.03.03, Current version: 2023.02.17
[debug] Downloading _update_spec from https://github.com/yt-dlp/yt-dlp/releases/download/2023.03.03/_update_spec
ERROR: You installed yt-dlp with pip or using the wheel from PyPi; Use that to update
```

**Comment by iF2007** [comment]
same issue

**Comment by pukkandan** [comment]
We will make a new release soon with the fix. It will also resolve https://github.com/Homebrew/homebrew-core/pull/124757

**Comment by pukkandan** [comment]
btw, @Lesmiscore Is it normal for brew to show as pip in identifier? Is there any way we can give it a custom name using `devscripts/set-variant.py`?

**Comment by Lesmiscore** [comment]
Yes, because it's literally installed via pip
You want it to be like this? Then this is what I'm doing: https://github.com/ytdl-patched/ytdl-patched/blob/ytdlp/setup.py#L177
```
$ ytdl -v
[debug] Command-line config: ['-v']
[debug] User config "/home/lesmi/.config/ytdl-patched/config": [(snip)]
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] ytdl-patched version 2023.03.01.1677694228 [e884b4e] (homebrew)
[debug]      from commit e884b4e2a
[debug]      based on b38cae49e
[debug] ** The command you are running is not yt-dlp.
[debug] ** Please make bug reports at https://github.com/ytdl-patched/ytdl-patched/issues/new/choose instead.
```

**Comment by pukkandan** [comment]
nvm. I was just wondering if it's easily possible. Doesn't seem worth the hassle. Especially since the official brew will keep showing as pip

**Comment by Goooler** [comment]
It works for now 🚀 .

https://github.com/yt-dlp/yt-dlp/releases/tag/2023.03.04
