### ISSUE TITLE
challenge to capture the real m3u8

### ISSUE THREAD

**Issue by ericsia** [yt-dlp/yt-dlp#6412]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.03.03** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

so today I tried to download the m3u8 from this website using yt-dlp but it failed
https://xue.51zhy.cn/p/t_pc/course_pc_detail/video/v_60a35f8ae4b0adb2d86529f1?product_id=p_609dd95be4b0fe3220131618&content_app_id=&type=6

someone previously extracted the website url as this:
https://encrypt-k-vod.xet.tech/9764a7a5vodtransgzp1252524126/8e4537075285890818525381301/drm/v.f421220.m3u8?start=0&end=176543&type=mpegts&sign=bc9f51546b3006b5e16950c515999062&t=6402ab05&us=tpGxJrdCHm

but now it's expired. I don't know how he extracted it. Anyone know how?

**Comment by pukkandan** [comment]
https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-your-question-about-yt-dlp
