### ISSUE TITLE
Cannot download video from udemy 

### ISSUE THREAD

**Issue by aloetk** [yt-dlp/yt-dlp#6413]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.03.03** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I tried all the ways and they all give me the same error

yt-dlp  --user-agent 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:105.0) Gecko/20100101 Firefox/105.0' --cookies-from-browser firefox -P . -o "%(playlist)s/%(chapter_number)s - %(chapter)s/%(title)s.%(ext)s" "https://www.udemy.com/course/docker-mastery"

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[Cookies] Extracting cookies from firefox
[Cookies] Extracted 2667 cookies from firefox
[generic] Extracting URL: (Windows
ERROR: [generic] None: '(Windows' is not a valid URL. Set --default-search "ytsearch" (or run  yt-dlp "ytsearch:(Windows" ) to search YouTube
[generic] Extracting URL: NT
ERROR: [generic] None: 'NT' is not a valid URL. Set --default-search "ytsearch" (or run  yt-dlp "ytsearch:NT" ) to search YouTube
[generic] Extracting URL: 10.0;
ERROR: [generic] None: '10.0;' is not a valid URL. Set --default-search "ytsearch" (or run  yt-dlp "ytsearch:10.0;" ) to search YouTube
[generic] Extracting URL: Win64;
ERROR: [generic] None: 'Win64;' is not a valid URL. Set --default-search "ytsearch" (or run  yt-dlp "ytsearch:Win64;" ) to search YouTube
[generic] Extracting URL: x64;
ERROR: [generic] None: 'x64;' is not a valid URL. Set --default-search "ytsearch" (or run  yt-dlp "ytsearch:x64;" ) to search YouTube
[generic] Extracting URL: rv:105.0)
[generic] rv:105: Downloading webpage
ERROR: [generic] None: Unable to download webpage: <urlopen error unknown url type: rv> (caused by URLError('unknown url type: rv'))
[generic] Extracting URL: Gecko/20100101
ERROR: [generic] None: 'Gecko/20100101' is not a valid URL. Set --default-search "ytsearch" (or run  yt-dlp "ytsearch:Gecko/20100101" ) to search YouTube
[generic] Extracting URL: Firefox/105.0'
ERROR: [generic] None: "Firefox/105.0'" is not a valid URL. Set --default-search "ytsearch" (or run  yt-dlp "ytsearch:Firefox/105.0'" ) to search YouTube
[udemy:course] Extracting URL: https://www.udemy.com/course/docker-mastery
[udemy:course] course: Downloading webpage
[udemy:course] 1035000: Downloading course curriculum
ERROR: [udemy:course] course: Unable to download JSON metadata: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

**Comment by pukkandan** [comment]
1. Quote your arguments properly.
2. That is not verbose log
3. Use "broken site" template
