### ISSUE TITLE
tsn.ca/video error - 9c9media extractor

### ISSUE THREAD

**Issue by mokahless** [yt-dlp/yt-dlp#6423]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that a **supported** site is broken
- [X] I've verified that I'm running yt-dlp version **2023.03.03** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Canada

### Provide a description that is worded well enough to be understood

yt-dlp seems to be attempting the download so I'm running under the assumption tsn.ca is supported under the 9c9media extractor but if this assumption is false, my apologies and I'll instead open a new site support request.

Anyway, I run into the error in the next section with any video on tsn.ca/video, whereby it says video is DRM protected, then doesn't download.

Example:
https://www.tsn.ca/video/strength-in-numbers-bruins-get-richer-at-deadline~2639214
https://www.tsn.ca/video/gane-vs-jones-upset-alert-or-fool-s-gold~2639887

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.tsn.ca/video/strength-in-numbers-bruins-get-richer-at-deadline~2639214']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2023.03.03 [934496428] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-109165-g9f5a9a7499-20221122 (setts), ffprobe N-109165-g9f5a9a7499-20221122
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1782 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.03, Current version: stable@2023.03.03
Current Build Hash: e46f99d497641d7bdb9180691e78a9d4a3525b964ed918c1a0a3a66a97b11ae1
yt-dlp is up to date (stable@2023.03.03)
[BellMedia] Extracting URL: https://www.tsn.ca/video/strength-in-numbers-bruins-get-richer-at-deadline~2639214
[debug] Using fake IP 99.249.145.44 (CA) as X-Forwarded-For
[9c9media] Extracting URL: 9c9media:tsn_web:2639214
[9c9media] 2639214: Downloading JSON metadata
[9c9media] 2639214: Downloading JSON metadata
ERROR: [9c9media] 2639214: This video is DRM protected
  File "yt_dlp\extractor\common.py", line 694, in extract
  File "yt_dlp\extractor\ninecninemedia.py", line 33, in _real_extract
  File "yt_dlp\extractor\common.py", line 1128, in report_drm
  File "yt_dlp\extractor\common.py", line 1172, in raise_no_formats
```

**Comment by pukkandan** [comment]
Do you have any reason to believe the video is actually not DRM protected?

**Comment by mokahless** [comment]
I don't. If it's not something that is possible to bypass, that's fine - feel free to close the issue.

**Comment by pukkandan** [comment]
Sadly, bypassing DRM is illegal in most countries and will be supported - https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy
