### ISSUE TITLE
2023.03.04 for macOS seems to be unsigned/not notarized

### ISSUE THREAD

**Issue by section83** [yt-dlp/yt-dlp#6432]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Have downloaded version 2023.03.04 and tried to use.  macOS bangs this error:

<img width="260" alt="Cannot open" src="https://user-images.githubusercontent.com/7471595/222942790-fd49233d-2c49-423d-9f7e-5414d762b8e2.png">

Version 2023.03.03 works.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
Version 2023.03.04:
>/usr/local/bin/yt-dlp --version
>zsh: killed     /usr/local/bin/yt-dlp --version

Version 2023.03.03:
>/usr/local/bin/yt-dlp-works --version
>2023.03.03
```

**Comment by Grub4K** [comment]
We have never notarized or stapled MacOS applications[^1] and probably never will with regards to the 100$ fee that apple charges annually[^2].
I believe this error can be counteracted by locating the application in Finder, control clicking and then selecting "Open" from the menu[^3].

Possibly the previous application was saved as an exception by you once before. We cannot change Apples behavior, even with signed binaries. Please close this if you think this was satisfactory.

[^1]: https://developer.apple.com/documentation/security/notarizing_macos_software_before_distribution
[^2]: https://developer.apple.com/support/enrollment/
[^3]: https://support.apple.com/guide/mac-help/apple-cant-check-app-for-malicious-software-mchleab3a043/mac

**Comment by section83** [comment]
Thanks.

> I believe this error can be counteracted by locating the application in Finder, control clicking and then selecting "Open" from the menu

That does work but, is not suited to my applet which is a GUI front end for YT-DLP.  Currently, the applet does not package YT-DLP but downloads the latest version separately. It has been working since 2017 so, I'm puzzled as to why it no longer works. I need to do more research.

I will close for now.
