### ISSUE TITLE
aria2c split error code 28

### ISSUE THREAD

**Issue by emilyexa** [yt-dlp/yt-dlp#6434]
- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

hi I'm trying to download this playlist and it's contents are around 5-10 MB size and I didn't have this issue with bigger sized files but my download is very slow so I changed aria2c's -k argument from 1M to 512K and got this error:

if fact any values less than 1M gives me this error and I need aria2c to split the file in much lower sizes so my download rate goes up but I don't know how to do that

> --downloader-args aria2c:"-c --file-allocation=prealloc -j 16 -x 16 -k 1M --max-tries=0"

- [x] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

> [download] Destination: G:\yt-dlp\Theory of Computation & Automata Theory\024 - Minimization of DFA (With Unreachable States).f140.m4a
> Exception: [AbstractOptionHandler.cc:69] errorCode=28 We encountered a problem while processing the option '--min-split-size'.
>   -> [OptionHandlerImpl.cc:184] errorCode=1 min-split-size must be between 1048576 and 1073741824.
> Usage:
>  -k, --min-split-size=SIZE    aria2 does not split less than 2*SIZE byte range.
>                               For example, let's consider downloading 20MiB
>                               file. If SIZE is 10M, aria2 can split file into 2
>                               range [0-10MiB) and [10MiB-20MiB) and download it
>                               using 2 sources(if --split >= 2, of course).
>                               If SIZE is 15M, since 2*15M > 20MiB, aria2 does
>                               not split file and download it using 1 source.
>                               You can append K or M(1K = 1024, 1M = 1024K).
> 
>                               Possible Values: 1048576-1073741824
>                               Default: 20M
>                               Tags: #basic, #http, #ftp
> 
> 
> 
> ERROR: aria2c exited with code 28

**Comment by gamer191** [comment]
Is that the full verbose log?

**Comment by emilyexa** [comment]
changing aria2c's arguments to `--downloader-args aria2c:"-c --max-tries=0 -k 1M -j 16 --enable-http-pipelining --stream-piece-selector=geom"` I now have a higher download rate

**Comment by emilyexa** [comment]
> Is that the full verbose log?

must've gotten cropped when I copied it. sorry

**Comment by emilyexa** [comment]
with the new aria2c I'm comfortable with the results so I'm closing this issue
