### ISSUE TITLE
How to pass ffmpeg-location parameter in code ?

### ISSUE THREAD

**Issue by kapildhiman** [yt-dlp/yt-dlp#6439]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

where to add ffmpeg-location parameter

e.g. Below one is incorrect so want to know the correct place ? 

![image](https://user-images.githubusercontent.com/58678719/222970854-5a13f723-993a-41b9-8cdb-0274a8939c38.png)

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
```py
from yt_dlp.postprocessor import FFmpegPostProcessor
FFmpegPostProcessor._ffmpeg_location.set(R'C:\...')
```

**Comment by kapildhiman** [comment]
Hi @pukkandan , I tried this but not working sending you complete code

import yt_dlp
from yt_dlp.postprocessor import FFmpegPostProcessor
FFmpegPostProcessor._ffmpeg_location.set(R'C:\users\kapil dhiman\appdata\roaming\python\python311\site-packages')

URLS = ['https://www.youtube.com/watch?v=ScMzIvxBSi4']

ydl_opts = {
    'format': 'm4a/bestaudio/best',
    # ℹ️ See help(yt_dlp.postprocessor) for a list of available Postprocessors and their arguments
    'postprocessors': [{  # Extract audio using ffmpeg
        'key': 'FFmpegExtractAudio',
        'preferredcodec': 'm4a',
    }]
}

with yt_dlp.YoutubeDL(ydl_opts) as ydl:
    error_code = ydl.download(URLS)

**Comment by pukkandan** [comment]
You have an ffmpeg.exe inside site-packages? That seems weird

**Comment by kapildhiman** [comment]
![image](https://user-images.githubusercontent.com/58678719/222976319-ac80ecfe-d2b2-4c72-84d5-b7dcb45b2807.png)

**Comment by pukkandan** [comment]
Can't reproduce

```
In [11]: import yt_dlp
    ...: from yt_dlp.postprocessor import FFmpegPostProcessor
    ...: FFmpegPostProcessor._ffmpeg_location.set(R'D:\Programs\Terminal')
    ...:
    ...: URLS = ['https://www.youtube.com/watch?v=ScMzIvxBSi4']
    ...:
    ...: ydl_opts = {
    ...:     'format': 'm4a/bestaudio/best',
    ...:     'postprocessors': [{  # Extract audio using ffmpeg
    ...:         'key': 'FFmpegExtractAudio',
    ...:         'preferredcodec': 'm4a',
    ...:     }]
    ...: }
    ...:
    ...: with yt_dlp.YoutubeDL(ydl_opts) as ydl:
    ...:     error_code = ydl.download(URLS)
    ...:
[youtube] Extracting URL: https://www.youtube.com/watch?v=ScMzIvxBSi4
[youtube] ScMzIvxBSi4: Downloading webpage
[youtube] ScMzIvxBSi4: Downloading android player API JSON
[info] ScMzIvxBSi4: Downloading 1 format(s): 140
[dashsegments] Total fragments: 1
[download] Destination: Placeholder Video [ScMzIvxBSi4].m4a
[download] 100% of    1.46MiB in 00:00:00 at 2.13MiB/s
[FixupM4a] Correcting container of "Placeholder Video [ScMzIvxBSi4].m4a"
[ExtractAudio] Not converting audio Placeholder Video [ScMzIvxBSi4].m4a; file is already in target format m4a
```

**Comment by kapildhiman** [comment]
Do you also have this file "ffplay.exe" under D:\Programs\Terminal?

**Comment by pukkandan** [comment]
Doesn't matter

**Comment by kapildhiman** [comment]
To make this working I have manually copied the exe files in root directory and it's working.
Thanks for your help

**Comment by Mohammad9760** [comment]
why is this issue closed as complete? there is no answer to the question of how to specify the ffmpeg location in code.
I tried 
```
    ydl_opts = {
        'format': 'bestaudio/best',
        'ffmpeg_location': './ffmpeg',
        'postprocessors': [{
            'key': 'FFmpegExtractAudio',
            'preferredcodec': 'mp3',
            'preferredquality': '192',
        }],
        'outtmpl': '%(title)s.%(ext)s',
        'cookiefile': 'cookies.txt',
    }

```

and it didn't work.
I have an executable ffmpeg file in the same dir as the main.py

**Comment by bashonly** [comment]
Reopening this to track the current jankiness of `ffmpeg_location` in API.

Ref:
- 9f77e04c76e36e1cbbf49bc9eb385fa6ef804b67
- 0eed3fe530d6ff4b668494c5b1d4d6fc1ade96f7

**Comment by bashonly** [comment]
@Mohammad9760 https://github.com/yt-dlp/yt-dlp/issues/6439#issuecomment-1455130033
