### ISSUE TITLE
[youtube] Trying to fix `translated_subs` and `automatic_captions` in codes.

### ISSUE THREAD

**Issue by NewUserHa** [yt-dlp/yt-dlp#6443]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that a **supported** site is broken
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Provide a description that is worded well enough to be understood

https://github.com/yt-dlp/yt-dlp/blob/c459d45dd4d417fb80a52e1a04e607776a44baa4/yt_dlp/extractor/youtube.py#L4137-L4145

For this video, `captions` has 1 item `en`, `translation_languages` has 125 items.
But with 'youtube:skip=translated_subs', the result it returned is `en, ja, en-orig` and all of them are actually auto-translated content by humans confirmed, so the returned result should not be correct.

Shall we fix this by removing `automatic_captions`, OR 
by using an new extractor-args `automatic_subs` for keeping back compatibility (except the items in `captions` since which is the real closed-caption)?

This will also resolve some other issues related to the auto-subs.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['--write-sub', '--sub-lang', 'en*,ja*,zh*', '--extractor-args', 'youtube:skip=translated_subs', '--convert-subs', 'srt', 'dcrY59nGxBg', '--write-auto-sub', '--sub-lang', '.*-orig', '-vU']
[debug] Encodings: locale cp936, fs utf-8, pref cp936, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2023.03.03 [934496428] (pip)
[debug] Python 3.11.2 (CPython AMD64 64bit) - Windows-10-10.0.17134-SP0 (OpenSSL 1.1.1s  1 Nov 2022)
[debug] exe versions: ffmpeg 5.1.2-full_build-www.gyan.dev (setts), ffprobe 5.1.2-full_build-www.gyan.dev, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1782 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
[debug] Downloading _update_spec from https://github.com/yt-dlp/yt-dlp/releases/latest/download/_update_spec
ERROR: You installed yt-dlp with pip or using the wheel from PyPi; Use that to update
[youtube] Extracting URL: dcrY59nGxBg
[youtube] dcrY59nGxBg: Downloading webpage
[youtube] dcrY59nGxBg: Downloading android player API JSON
[info] dcrY59nGxBg: Downloading subtitles: en, ja, en-orig
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] dcrY59nGxBg: Downloading 1 format(s): 247+251
...
```

**Comment by pukkandan** [comment]
Why don't you explain the problem first before suggesting a solution?

**Comment by NewUserHa** [comment]
The problem has been in the post:
With the 'skip=translated_subs' option, in the results, it returns **translated subs**.

The expected result is that it will not contain **any auto-translated content** when with 'youtube:skip=translated_subs'.
Therefore want to discuss whether there's a better way.

**Comment by pukkandan** [comment]
The current behavior is correct. Perhaps you are misunderstanding the option? https://github.com/yt-dlp/yt-dlp/issues/3875

**Comment by NewUserHa** [comment]
I checked the thread you post.
> `skip=translated_subs` hides subs that are auto-translated from normal subtitles. These are just auto-generated subs of different languages. Use `--list-subs` to see all the available subs
// quoted from https://github.com/yt-dlp/yt-dlp/issues/3875#issuecomment-1138747833

Based on the quoted replay, that option should hide them from normal subtitles.
I carefully checked the final downloaded subs with that option, But their content indeed is "auto-translated" instead.

There's a real use case from that and similar issues, 
can probably add a new extractor-args to solve all that kinds issues?

**Comment by pukkandan** [comment]
> There's a real use case from that and similar issues,

Yet, you don't care to elaborate what that is...


See https://github.com/yt-dlp/yt-dlp/issues/3875#issuecomment-1320430104 for the breakdown of what subs are what.


> I carefully checked the final downloaded subs with that option, But their content indeed is "auto-translated" instead.

Doesn't matter. The point is that it is different from the auto-translation feature offered by youtube. The extractor arg's only purpose is to disable them. It is not a substitute for filtering subs with the other options.

**Comment by NewUserHa** [comment]
> See https://github.com/yt-dlp/yt-dlp/issues/3875#issuecomment-1320430104 for the breakdown of what subs are what.
> Doesn't matter how you think youtube is generating the content. The point is that it is different from the auto-translation feature offered by youtube. The extractor arg's only purpose is to disable enumerating them. It is not a substitute for filtering subs with the other options.

OK. just cheeked the code, "skip=translated_subs" is used at only:
https://github.com/yt-dlp/yt-dlp/blob/c459d45dd4d417fb80a52e1a04e607776a44baa4/yt_dlp/extractor/youtube.py#L4177-L4180 
For the test video, the `caption_track.get('kind')!=asr` is always `False`, therefore `if not get_translated_subs:` never get run, so the "skip=translated_subs" never worked. ( the caption_track is from the `caption` variable which = 'English (auto-generated)')
(and 'asr' stands for Automatic Speech Recognition from https://support.google.com/youtube/answer/7296221)

Based on this, I guess "skip=translated_subs" is for "caption_track.get('kind') == 'asr'", then since `captions` variable has only 'English (auto-generated)' (maybe plus user uploaded?), and translation_languages has its own variable storing translation_languages. So I guess the True/working situation for "skip=translated_subs" is when auto_translated un-asr subtitles are in the `captions` variable.

---
> Yet, you don't care to elaborate what that is...

As like the comment at https://github.com/yt-dlp/yt-dlp/issues/3875#issuecomment-1140292808, the use case is "to download all non auto-subs + English (auto-generated)." without running yt-dlp 2 times.

e.g: For the non-native speakers, they may want to download the video creator's uploaded subtitles if there's one, plus the Automatic Speech Recognition one which may be useful too.
Besides, normally, most viewers probably would not want the low-quality and unreadable auto-translated-from-asr-by-machine subs.

If the current behavior of skip=translated_subs is correct, however, I wonder if I could make a "skip=automatic" extractor-args in a PR to help the users.

**Comment by pukkandan** [comment]
> "to download all non auto-subs + English (auto-generated)." without running yt-dlp 2 times.

Gotcha. This use-case is currently being blocked by https://github.com/yt-dlp/yt-dlp/issues/2262


Which reminds me, I forgot to reply to https://github.com/yt-dlp/yt-dlp/pull/6264, which I should do asap 😓
