### ISSUE TITLE
[Question] Merging multiple streams

### ISSUE THREAD

**Issue by Runisco** [yt-dlp/yt-dlp#645]
## Checklist

- [x ] I'm asking a question
- [x ] I've looked through the README and FAQ for similar questions
- [x ] I've searched the bugtracker for similar questions including closed ones

## Question

I was trying to download a video with multiple audio streams using youtube-dl and the following command 
`.\youtube-dl.exe -f "bestvideo+audio_0-Ambient_Sound,audio_0-English" --user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:90.0) Gecko/20100101 Firefox/90.0" m3u8link here.`
This downloads the video and only one audio stream into one well-formed file.

When asked how to download multiple audio streams, I was told to try yt.dlp, and I tried the following cmd:
`.\yt-dlp.exe -f "all[vcodec=none],bestvideo" --audio-multistreams -o "recon.mp4" --user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:90.0) Gecko/20100101 Firefox/90.0" m3u8 here`

However with this command all I get is this:

[info] index.m3u8?aws: Downloading 3 format(s): audio_0-Ambient_Sound, audio_0-English, 6191
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 727  
[download] Destination: recon.mp4  
[download] 100% of 66.55MiB in 01:29
[FixupM3u8] Fixing malformed AAC bitstream of "recon.mp4"
[download] recon.mp4 has already been downloaded
WARNING: index.m3u8?aws: malformed AAC bitstream detected
[download] recon.mp4 has already been downloaded
WARNING: index.m3u8?aws: malformed AAC bitstream detected

and obviously the file is much larger than 66mb.

**Comment by Ashish0804** [comment]
`-o "recon.mp4"`
U have hardcoded the name therefore it won't overwrite

use a better output template

**Comment by pukkandan** [comment]
If you are trying to download all the streams into a single file, it should be `-f "bv+all[vcodec=none]"`. Note the `+`, not `,`

If instead you want multiple files, like Ashish said, use an output template that gives different names to the different files

**Comment by Runisco** [comment]
With two audio streams, ambient and english this is what I got
`.\yt-dlp.exe -f "bv+all[vcodec=none]" --audio-multistreams --user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:90.0) Gecko/20100101 Firefox/90.0"`
resulted in one video file with with ambient, and a standalone audio with ambient.

`.\yt-dlp.exe -f "bv+all[vcodec=none]" --audio-multistreams -o "%(format_id)s.%(ext)s" --user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:90.0) Gecko/20100101 Firefox/90.0"`
resulted in two videos, both with ambient

**Comment by Ashish0804** [comment]
Send output of -F

**Comment by Runisco** [comment]
ID                    EXT RESOLUTION FPS |   TBR PROTO  | VCODEC        VBR ACODEC  MORE INFO
--------------------- --- ---------- --- - ----- ------ - ----------- ----- ------- --------------------
audio_0-Ambient_Sound mp4 audio only     |       m3u8_n |                   unknown [qis], Ambient Sound
audio_0-English       mp4 audio only     |       m3u8_n |                   unknown [eng], English
352                   mp4 416x240    25  |  352k m3u8_n | avc1.42C01E  352k
471                   mp4 416x240    25  |  471k m3u8_n | avc1.4D401F  471k
669                   mp4 640x360    25  |  669k m3u8_n | avc1.64001F  669k
1127                  mp4 640x360    25  | 1127k m3u8_n | avc1.64001F 1127k
1549                  mp4 640x360    25  | 1549k m3u8_n | avc1.64001F 1549k
1831                  mp4 960x540    25  | 1831k m3u8_n | avc1.64001F 1831k
2394                  mp4 1280x720   25  | 2394k m3u8_n | avc1.640029 2394k
3716                  mp4 1280x720   50  | 3716k m3u8_n | avc1.640029 3716k
6191                  mp4 1920x1080  50  | 6191k m3u8_n | avc1.64002A 6191k

**Comment by pukkandan** [comment]
> resulted in one video file with with ambient, and a standalone audio with ambient.

it should be `mergeall`, not `all`. Updated my above comment
