### ISSUE TITLE
Empty field recognized as existing

### ISSUE THREAD

**Issue by pjammo** [yt-dlp/yt-dlp#6460]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Command:
```
yt-dlp -vU --replace-in-metadata "description" "^Provided to YouTube by ([^\n]*)\n+([^\n]+)\n+([^\n]+)\n+(?:([^\n]+)\n+)?(?:Released on: ([^\n]+)\n+)?(?s:(.*?))\n+Auto-generated by YouTube\.$" "\5" --print "%(id)s %(description,release_date>%Y-%m-%d,upload_date>%Y-%m-%d,release_year)s" Hx4nWW9z0ig gb1DCvjaf6k
```

Output of the command:
```
Hx4nWW9z0ig
gb1DCvjaf6k 2023-02-20
```

Expected output:
```
Hx4nWW9z0ig 2019-08-07
gb1DCvjaf6k 2023-02-20
```

Output removing `description` from `--print`:
```
Hx4nWW9z0ig 2019-08-07
gb1DCvjaf6k 2023-03-06
```

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--replace-in-metadata', 'description', '^Provided to YouTube by ([^\\n]*)\\n+([^\\n]+)\\n+([^\\n]+)\\n+(?:([^\\n]+)\\n+)?(?:Released on: ([^\\n]+)\\n+)?(?s:(.*?))\\n+Auto-generated by YouTube\\.$', '\\5', '--print', '%(id)s %(description,release_date>%Y-%m-%d,upload_date>%Y-%m-%d,release_year)s', 'Hx4nWW9z0ig', 'gb1DCvjaf6k']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2023.02.17 [a0a7c01] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 6.0-full_build-www.gyan.dev (setts), ffprobe 6.0-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1782 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2023.03.04, Current version: 2023.02.17
[debug] Downloading _update_spec from https://github.com/yt-dlp/yt-dlp/releases/download/2023.03.04/_update_spec
Current Build Hash 351777b6fa3cf2d375e11b6840995132fd0d91f1b377f8ca8fe4252bc7135e7b
Updating to version 2023.03.04 ...
[debug] Downloading yt-dlp.exe from https://github.com/yt-dlp/yt-dlp/releases/download/2023.03.04/yt-dlp.exe
[debug] Downloading SHA2-256SUMS from https://github.com/yt-dlp/yt-dlp/releases/download/2023.03.04/SHA2-256SUMS
Updated yt-dlp to version 2023.03.04
[debug] Restarting: yt-dlp -vU --replace-in-metadata description "^Provided to YouTube by ([^\n]*)\n+([^\n]+)\n+([^\n]+)\n+(?:([^\n]+)\n+)?(?:Released on: ([^\n]+)\n+)?(?s:(.*?))\n+Auto-generated by YouTube\.$" "\5" --print "%(id)s %(description,release_date>%Y-%m-%d,upload_date>%Y-%m-%d,release_year)s" Hx4nWW9z0ig gb1DCvjaf6k
[debug] Command-line config: ['-vU', '--replace-in-metadata', 'description', '^Provided to YouTube by ([^\\n]*)\\n+([^\\n]+)\\n+([^\\n]+)\\n+(?:([^\\n]+)\\n+)?(?:Released on: ([^\\n]+)\\n+)?(?s:(.*?))\\n+Auto-generated by YouTube\\.$', '\\5', '--print', '%(id)s %(description,release_date>%Y-%m-%d,upload_date>%Y-%m-%d,release_year)s', 'Hx4nWW9z0ig', 'gb1DCvjaf6k']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 6.0-full_build-www.gyan.dev (setts), ffprobe 6.0-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
Current Build Hash: 5590c57bd0433ed239a2deaaf92e2ad6f37fe50f53664c821575cafe106a9421
yt-dlp is up to date (stable@2023.03.04)
[youtube] Extracting URL: Hx4nWW9z0ig
[youtube] Hx4nWW9z0ig: Downloading webpage
[youtube] Hx4nWW9z0ig: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[debug] Replacing all '^Provided to YouTube by ([^\\n]*)\\n+([^\\n]+)\\n+([^\\n]+)\\n+(?:([^\\n]+)\\n+)?(?:Released on: ([^\\n]+)\\n+)?(?s:(.*?))\\n+Auto-generated by YouTube\\.$' in description with '\\5'
[MetadataParser] Changed description to:
[debug] Default format spec: bestvideo*+bestaudio/best
[info] Hx4nWW9z0ig: Downloading 1 format(s): 248+251
Hx4nWW9z0ig
[youtube] Extracting URL: gb1DCvjaf6k
[youtube] gb1DCvjaf6k: Downloading webpage
[youtube] gb1DCvjaf6k: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[debug] Replacing all '^Provided to YouTube by ([^\\n]*)\\n+([^\\n]+)\\n+([^\\n]+)\\n+(?:([^\\n]+)\\n+)?(?:Released on: ([^\\n]+)\\n+)?(?s:(.*?))\\n+Auto-generated by YouTube\\.$' in description with '\\5'
[MetadataParser] Changed description to: 2023-02-20
[debug] Default format spec: bestvideo*+bestaudio/best
[info] gb1DCvjaf6k: Downloading 1 format(s): 248+251
gb1DCvjaf6k 2023-02-20
```

**Comment by pukkandan** [comment]
The current behavior is intentional, but we can discuss whether it should be.

Unlike `description=None` (which means site doesn't give the data, or we failed to extract it), `description=''` implies that the description of the video was successfully extracted, but it ended up being an empty string. Let's see how the other options treat this:

1. `--match-filter description` skips the video
2. `--write-description` writes an empty .description file
3. `--print/-o %(description)s` does not replace it with `NA`
4. `%(description,xxx)s` does not fall back to xxx (case in OP)
5. `%(description|false&true)s` returns `true`

(1) is the only option that does not consider it truthy and I think it makes sense there. Behavior of (2) and (3) are intentionally/explicitly defined in code and so cannot be changed. This leaves us with only (4)/(5) that we have flexibility over. While I personally don't mind changing them to how you expect, I don't think it is a good idea to make it inconsistent with (3).

**Comment by pukkandan** [comment]
> While I personally don't mind changing them to how you expect

On further thought, I changed my mind. The behavior you want is problematic for boolean fields. Consider the example of `%(is_live|xxx)s` and `%(is_live,xxx)s`. When `is_live=False`, these are expected to return `False`, not `xxx`.

Considering this, I cannot change the current behavior

**Comment by pukkandan** [comment]
OP's specific requirement could be handled by:
```
❯ yt-dlp --replace-in-metadata "description" "^Provided to YouTube by ([^\n]*)\n+([^\n]+)\n+([^\n]+)\n+(?:([^\n]+)\n+)?(?:Released on: ([^\n]+)\n+)?(?s:(.*?))\n+Auto-generated by YouTube\.$" "\5" --print "%(id)s %(description)s" --parse-metadata "%(description|)s@%(release_date>%Y-%m-%d,upload_date>%Y-%m-%d,release_year)s:^@(?P<description>.+)" Hx4nWW9z0ig gb1DCvjaf6k
Hx4nWW9z0ig 2019-08-07
gb1DCvjaf6k 2023-02-20
```

**Comment by pjammo** [comment]
Thanks for your answer and for all your work.

> The current behavior is intentional

I thought so, that's fine.

> OP's specific requirement could be handled by

It works. Looking into the docs and into [python regular expressions](https://docs.python.org/3/library/re.html), I couldn't figure out the meaning of `@` and `^@` in the following argument. Could you explain it?
```
--parse-metadata "%(description.0|)s@%(release_date>%Y-%m-%d,upload_date>%Y-%m-%d,release_year)s:^@(?P<description>\d.+)"
```

**Comment by pukkandan** [comment]
`^` = Match start of string
`@` has no special meaning. We want some delimiter so that the right side can separate description from date. I just used `@`. You can use anything that's not `\d-`

The command basically reads "if `description@date` starts with `@` (i.e. description is empty), copy the date into description". The `.0` and `\d` handles the special case when description itself may start with @

**Comment by pjammo** [comment]
Flawless, thank you.
