### ISSUE TITLE
maybe youtube make some change,can not download anymore

### ISSUE THREAD

**Issue by baalkyo** [yt-dlp/yt-dlp#6461]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

[youtube:tab] Extracting URL: https://www.youtube.com/playlist?list=PLGnjPtt6DJXTU-Fq_dpxlxgOOcLC24bpn
[youtube:tab] PLGnjPtt6DJXTU-Fq_dpxlxgOOcLC24bpn: Downloading webpage
WARNING: [youtube:tab] IncompleteRead(24847 bytes read). Retrying (1/3)...
[youtube:tab] PLGnjPtt6DJXTU-Fq_dpxlxgOOcLC24bpn: Downloading webpage
WARNING: [youtube:tab] IncompleteRead(2864 bytes read). Retrying (2/3)...
[youtube:tab] PLGnjPtt6DJXTU-Fq_dpxlxgOOcLC24bpn: Downloading webpage
WARNING: [youtube:tab] IncompleteRead(30602 bytes read). Retrying (3/3)...
[youtube:tab] PLGnjPtt6DJXTU-Fq_dpxlxgOOcLC24bpn: Downloading webpage
WARNING: [youtube:tab] Unable to download webpage: IncompleteRead(17666 bytes read) (caused by IncompleteRead(17666 bytes read)); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U. Giving up after 3 retries
[youtube:tab] PLGnjPtt6DJXTU-Fq_dpxlxgOOcLC24bpn: Downloading API parameters API JSON
[youtube:tab] PLGnjPtt6DJXTU-Fq_dpxlxgOOcLC24bpn: Downloading API JSON
WARNING: [youtube:tab] IncompleteRead(6502 bytes read, 11501 more expected). Retrying (1/3)...
[youtube:tab] PLGnjPtt6DJXTU-Fq_dpxlxgOOcLC24bpn: Downloading API JSON
WARNING: [youtube:tab] IncompleteRead(990 bytes read, 17579 more expected). Retrying (2/3)...
[youtube:tab] PLGnjPtt6DJXTU-Fq_dpxlxgOOcLC24bpn: Downloading API JSON
WARNING: [youtube:tab] Remote end closed connection without response. Retrying (3/3)...
[youtube:tab] PLGnjPtt6DJXTU-Fq_dpxlxgOOcLC24bpn: Downloading API JSON
ERROR: [youtube:tab] PLGnjPtt6DJXTU-Fq_dpxlxgOOcLC24bpn: Unable to download API page: IncompleteRead(5124 bytes read, 13445 more expected) (caused by IncompleteRead(5124 bytes read, 13445 more expected)); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Conf

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
PS F:\work\youtube-dl\dixian> yt-dlp -vU --proxy 127.0.0.1:10809 --no-playlist https://www.youtube.com/playlist?list=PLG
njPtt6DJXTU-Fq_dpxlxgOOcLC24bpn
[debug] Command-line config: ['-vU', '--proxy', '127.0.0.1:10809', '--no-playlist', 'https://www.youtube.com/playlist?list=PLGnjPtt6DJXTU-Fq_dpxlxgOOcLC24bpn']
[debug] Encodings: locale cp936, fs utf-8, pref cp936, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.17134-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {'http': '127.0.0.1:10809', 'https': '127.0.0.1:10809'}
[debug] Loaded 1786 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
Current Build Hash: 5590c57bd0433ed239a2deaaf92e2ad6f37fe50f53664c821575cafe106a9421
yt-dlp is up to date (stable@2023.03.04)
[youtube:tab] Extracting URL: https://www.youtube.com/playlist?list=PLGnjPtt6DJXTU-Fq_dpxlxgOOcLC24bpn
[youtube:tab] PLGnjPtt6DJXTU-Fq_dpxlxgOOcLC24bpn: Downloading webpage
WARNING: [youtube:tab] IncompleteRead(2876 bytes read). Retrying (1/3)...
[youtube:tab] PLGnjPtt6DJXTU-Fq_dpxlxgOOcLC24bpn: Downloading webpage
WARNING: [youtube:tab] IncompleteRead(17656 bytes read). Retrying (2/3)...
[youtube:tab] PLGnjPtt6DJXTU-Fq_dpxlxgOOcLC24bpn: Downloading webpage
WARNING: [youtube:tab] IncompleteRead(2874 bytes read). Retrying (3/3)...
[youtube:tab] PLGnjPtt6DJXTU-Fq_dpxlxgOOcLC24bpn: Downloading webpage
WARNING: [youtube:tab] Unable to download webpage: IncompleteRead(12781 bytes read) (caused by IncompleteRead(12781 bytes read)); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U. Giving up after 3 retries
[youtube:tab] PLGnjPtt6DJXTU-Fq_dpxlxgOOcLC24bpn: Downloading API parameters API JSON
WARNING: [youtube:tab] Remote end closed connection without response. Retrying (1/3)...
[youtube:tab] PLGnjPtt6DJXTU-Fq_dpxlxgOOcLC24bpn: Downloading API parameters API JSON
WARNING: [youtube:tab] Remote end closed connection without response. Retrying (2/3)...
[youtube:tab] PLGnjPtt6DJXTU-Fq_dpxlxgOOcLC24bpn: Downloading API parameters API JSON
[youtube:tab] PLGnjPtt6DJXTU-Fq_dpxlxgOOcLC24bpn: Downloading API JSON
WARNING: [youtube:tab] IncompleteRead(5124 bytes read, 12967 more expected). Retrying (1/3)...
[youtube:tab] PLGnjPtt6DJXTU-Fq_dpxlxgOOcLC24bpn: Downloading API JSON
WARNING: [youtube:tab] <urlopen error EOF occurred in violation of protocol (_ssl.c:1131)>. Retrying (2/3)...
[youtube:tab] PLGnjPtt6DJXTU-Fq_dpxlxgOOcLC24bpn: Downloading API JSON
WARNING: [youtube:tab] Remote end closed connection without response. Retrying (3/3)...
[youtube:tab] PLGnjPtt6DJXTU-Fq_dpxlxgOOcLC24bpn: Downloading API JSON
ERROR: [youtube:tab] PLGnjPtt6DJXTU-Fq_dpxlxgOOcLC24bpn: Unable to download API page: Remote end closed connection without response (caused by RemoteDisconnected('Remote end closed connection without response')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 694, in extract
  File "yt_dlp\extractor\youtube.py", line 4438, in wrapper
  File "yt_dlp\extractor\youtube.py", line 6209, in _real_extract
  File "yt_dlp\extractor\youtube.py", line 5098, in _extract_data
  File "yt_dlp\extractor\youtube.py", line 5110, in _extract_tab_endpoint
  File "yt_dlp\extractor\youtube.py", line 908, in _extract_response
  File "yt_dlp\utils.py", line 6141, in __iter__
  File "yt_dlp\extractor\common.py", line 3728, in _error_or_warning
  File "yt_dlp\utils.py", line 6149, in report_retry
  File "yt_dlp\extractor\youtube.py", line 910, in _extract_response
  File "yt_dlp\extractor\youtube.py", line 586, in _call_api
  File "yt_dlp\extractor\common.py", line 1048, in download_content
  File "yt_dlp\extractor\common.py", line 1012, in download_handle
  File "yt_dlp\extractor\common.py", line 882, in _download_webpage_handle
  File "yt_dlp\extractor\common.py", line 839, in _request_webpage

  File "yt_dlp\extractor\common.py", line 821, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 3742, in urlopen
  File "urllib\request.py", line 525, in open
  File "urllib\request.py", line 542, in _open
  File "urllib\request.py", line 502, in _call_chain
  File "yt_dlp\utils.py", line 1555, in https_open
  File "urllib\request.py", line 1358, in do_open
  File "http\client.py", line 1344, in getresponse
  File "http\client.py", line 307, in begin
  File "http\client.py", line 276, in _read_status
http.client.RemoteDisconnected: Remote end closed connection without response
```

**Comment by pukkandan** [comment]
Issue with your proxy.

**Comment by baalkyo** [comment]
I test it ,only some proxy do it, thanks
