### ISSUE TITLE
Unable to backup MPD when token for media varies

### ISSUE THREAD

**Issue by l375cd** [yt-dlp/yt-dlp#6462]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

As far as I understand the **secure** http parameter changes across files and this must be the problem. Everything works fine manually downloading files...

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [x] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
Available version: stable@2023.03.04, Current version: stable@2023.03.04
yt-dlp is up to date (stable@2023.03.04)
[generic] Extracting URL: https://1104682167.rsc.cdn77.org/r/kdvod/2021/AMAZONIA._PRZYGODY_MALPKI_SAI/25_03_22_1450_6kh/h264.mpd?secure=xB8QjhSF0nO3MAr7Ygg3dQ==,1678201203947
[generic] h264: Downloading webpage
[generic] h264: Extracting information
[info] h264: Downloading 1 format(s): 5+2
[dashsegments] Total fragments: 794
[download] Destination: h264 [h264].f5.mp4
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (1/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (2/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (3/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (4/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (5/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (6/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (7/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (8/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (9/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (10/10)...

[dashsegments] Total fragments: 795
[download] Destination: h264 [h264].f2.m4a
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (1/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (2/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (3/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (4/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (5/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (6/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (7/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (8/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (9/10)...
[download] Got error: HTTP Error 403: Forbidden. Retrying fragment 1 (10/10)...
```

**Comment by pukkandan** [comment]
```
❯ yt-dlp "https://1104682167.rsc.cdn77.org/r/kdvod/2021/AMAZONIA._PRZYGODY_MALPKI_SAI/25_03_22_1450_6kh/h264.mpd?secure=xB8QjhSF0nO3MAr7Ygg3dQ==,1678201203947"
[generic] Extracting URL: https://1104682167.rsc.cdn77.org/r/kdvod/2021/AMAZONIA._PRZYGODY_MALPKI_SAI/25_03_22_1450_6kh/h26...g3dQ==,1678201203947
[generic] h264: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] h264: Extracting information
ERROR: [generic] h264: This video is DRM protected
```

I will not tolerate your intentional attempt to hide this fact
