### ISSUE TITLE
multi downloading video info_dict

### ISSUE THREAD

**Issue by metalalchemist** [yt-dlp/yt-dlp#6464]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

is there any way to download multi json of a playlist?
for example i've 200 videos in a playlist
and i want to download only the info.json of all videos with n threads
it's posible it?
ps: how many requests can i do in youtube before my ip is blocked?
sorry my english no is good

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
Use `-J` to get full json, but it will not be multithreaded.

> ps: how many requests can i do in youtube before my ip is blocked?

You'd have to ask google to get an actual answer. I have personally never gotten 429'd with `--sleep-requests 0.3`.

**Comment by metalalchemist** [comment]
why dont add multiprosesing download?
i think that add with an argument and then you can check if a thread finished the work
with concurrent.futures
