### ISSUE TITLE
Some YT videos lack audio after 2023.03.03 update

### ISSUE THREAD

**Issue by Svetloslav** [yt-dlp/yt-dlp#6466]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that a **supported** site is broken
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Ecuador/Latin America

### Provide a description that is worded well enough to be understood

I have stumbled on many videos on youtube, which in version 2023.02.27 were working absolutely fine with all defaults (picking best video & audio stream), those were reporting in the API: Format/Protocol: multi/mkv. Then, after the update to 2023.03.03, yt-dlp.exe was still picking the best video stream, but was reporting no audio stream and the API recognizes the very same video as: Format/Protocol: multi/edl. Updating to 2023.03.04 does not fix the problem. However returning to 2023.02.27 resolves the issue. Following are some examples of such videos on youtube (all those videos work correctly with version 2023.02.27 and report as Format/Protocol: multi/mkv) : 
https://www.youtube.com/watch?v=9vfNDed835A (Format/Protocol: multi/edl) 4k res no audio (yt-dlp.exe v2023.03.03 and v2023.03.04)
https://www.youtube.com/watch?v=VZUxhsEijIc (Format/Protocol: multi/edl) 4k res no audio (yt-dlp.exe v2023.03.03 and v2023.03.04)
https://www.youtube.com/watch?v=hMU2OamWMvU (Format/Protocol: multi/edl) 4k res no audio (yt-dlp.exe v2023.03.03 and v2023.03.04)
https://www.youtube.com/watch?v=QND7bEk14-M (Format/Protocol: multi/edl) 4k res no audio (yt-dlp.exe v2023.03.03 and v2023.03.04)
https://www.youtube.com/watch?v=FvlP3KNXZ6s (Format/Protocol: multi/edl) 4k res no audio (yt-dlp.exe v2023.03.03 and v2023.03.04)
https://www.youtube.com/watch?v=TMOHHraCY8s (Format/Protocol: multi/edl) 1080p res no audio (yt-dlp.exe v2023.03.03 and v2023.03.04)
https://www.youtube.com/watch?v=xTANWIJcSIM (Format/Protocol: multi/edl) 1080p res no audio (yt-dlp.exe v2023.03.03 and v2023.03.04)
https://www.youtube.com/watch?v=qEvL8hD09GY (Format/Protocol: multi/edl) 1080p res no audio (yt-dlp.exe v2023.03.03 and v2023.03.04)

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest Latest version: 2023.03.04, Current version: 2023.03.04
```

**Comment by coletdjnz** [comment]
>  Copy the WHOLE output (starting with [debug] Command-line config) and insert it below

**Comment by pukkandan** [comment]
> (Format/Protocol: multi/edl)

Sounds like you are using mpv. There was a bug in mpv that's just been fixed that made it not play well with the new formats. Perhaps what you are seeing is a side effect of that?

**Comment by minusf** [comment]
latest `yt-dlp` works.  latest mpv (0.35.1), iina (1.3.1) using latest `yt-dlp` does not. if the video is downloaded first, all players have audio.  streaming using `yt-dlp` have no audio streams for some reason...

**Comment by Svetloslav** [comment]
> > Provide verbose output that clearly demonstrates the problem

I am sorry but I can't, since it is a program for windows, which does not give output other, than what I gave already.

**Comment by Svetloslav** [comment]
> > (Format/Protocol: multi/edl)
> 
> Sounds like you are using mpv. There was a bug in mpv that's just been fixed that made it not play well with the new formats. Perhaps what you are seeing is an effect of that bug?

Yes, it is mpv

**Comment by pukkandan** [comment]
If you are unable to provide verbose log, you shouldn't be reporting issue here. You can try reporting to mpv, but as I said above, I suspect this is a bug that has already been fixed - just not released.

**Comment by Svetloslav** [comment]
> latest `yt-dlp` works. latest mpv (0.35.1), iina (1.3.1) using latest `yt-dlp` does not. if the video is downloaded first, all players have audio. streaming using `yt-dlp` have no audio streams for some reason...
> 
> an example would be monday's colbert: https://www.youtube.com/watch?v=2YVZbbWGkYo

So, which version of mpv does not cause that behavior? Also that does not explain, why version 2023.02.27 works absolutely fine together with a recent version of mpv (from 2 weeks ago), while as soon as I update to version 2023.03.03 it breaks down audio for streaming for some YT videos, but not for other videos, like the one to follow, where both audio and video are recognized correctly as Format/Protocol: multi/mkv. When I check in terminal the streams reported to yt-dlp.exe, they all look exactly the same, when comparing between following correctly working video and the initial examples I posted.
https://www.youtube.com/watch?v=LPgZ4lKfBPw
Other users of the same windows program, have all confirmed the problem appearing as of version 2023.03.03.

**Comment by Svetloslav** [comment]
> 

I reported here, because the change from version 2023.02.27 to 2023.03.03 caused the break in functionality, while mpv has not been changed and is recent. As a matter of a fact all previous versions to 2023.03.03 work absolutely fine with that recent mpv version, therefore I disagree and it can not be automatically labeled a problem of mpv.

**Comment by pukkandan** [comment]
More details https://github.com/yt-dlp/yt-dlp/issues/6496
