### ISSUE TITLE
How do you extract the audio codec "value" given a video id without downloading?

### ISSUE THREAD

**Issue by blockbabak** [yt-dlp/yt-dlp#6468]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Also, can you search or list videos where audio codec=mp3

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by gamer191** [comment]
does `--list-formats` answer your question?

**Comment by pukkandan** [comment]
Thanks for the elaborate and clear question, and for actually doing the things you have ticked. So many people doesn't even have the basic decency to read what they are ticking, it is nice to know there are still some people that do.

---

The same video can have multiple `acodec`s available. You want the selected codec? All codecs? Try these commands

    yt-dlp -O acodec "URL"

.

    yt-dlp -O "%(formats.:.acodec)s" "URL"

---

> Also, can you search or list videos where audio codec=mp3

    yt-dlp --match-filter "acodec=mp3" "URL"


but assuming youtube, there is no such video

**Comment by pukkandan** [comment]
> Yes, I know that different codecs can be available for the same video_id but I was talking about the original audio codec of the original file uploaded that will presumably always be available.

Most sites do not provide the original uploaded video

> So, does this: yt-dlp -O acodec "URL" return all the available ones or the original acodec?

Why don't you try the commands I gave and see for yourself?

**Comment by blockbabak** [comment]
Sorry, I am not quite sure how this can work unless the URL is the domain youtube.com

yt-dlp --match-filter "acodec=mp3" "URL"        youtube.com

So that you get a listing of vidoes with certain codec and a number so we don’t want a huge list of urls?
Or are at cross purpose?
And what did you mean by “but assuming youtube, there is no such video”?

Surely there are videos uploaded in different acodecs, including mp3. The issue is that if the acodec is mp3 then your can’t put it WebM container so you want to chose MKV for example. 
I know there are different ways of doing it. But I want to have an If that compares the acodec with a value and set the container value to specific. It reads better and there is not need for preference setting involved so there is no best or worst stuff in defining the download parameter.

Finally if you could give me the command line switched then I can just demo it to the programmers straight away rather that writing a script. I knew there was a way.

Thank you once again and,

Best regards

Babak

**Comment by pukkandan** [comment]
It's exactly what I said. Youtube does not serve any video as mp3, nor do they give us access to the original file that was uploaded.

**Comment by blockbabak** [comment]
I tried 
yt-dlp --match-filter "acodec=m4a" "URL" and instead of URL I put https://youtube.com but didn't work. It extracted every video_id of its audio and for some reason started downloading some of them but their audio codecs were opus. So, I don't know what it was doing. 
Then I tried yt-dlp --no-download "ytsearch:acodec=m4a" https://www.youtube.com/ But none of the URL outputs had m4a codec. But it kept extracting the audio made it really slow.
it also printed a lot of messages about downloading webpages and android player API although I didn't see any downloads.
I just want a list of 10 youtube URLs where their acodec="m4a". 
That is when you play them in nerd statistics show m4a or mp4a as audio codec.
The other response yt-dlp -O acodec "URL" is great because it just returns to codec, the same as it is shown in nerd statistics.

**Comment by blockbabak** [comment]
I have been through the manual but can't find anything.

**Comment by blockbabak** [comment]
Hi, 

I am not quite sure what you said but I do know that the command you said didn’t do what I wanted.

This is the command that did what I wanted:
yt-dlp "ytsearch10:m4a" --get-id, i.e., gave me a list of video ids whose audio codec of format id 17 are m4a.
Maybe you should publish it for others benefit.

However, when I tried this:
yt-dlp "ytsearch10:mp3" --get-id, 

it still gave me a list of videoids whose audio codec for format 1d 17 are still m4a but not the same list.

If there are no mp3s left in Youtube then why do I get a list as such? It does require explanation, doesn’t it? 

If it doesn’t cover your expertise, I would beg grateful if you either pass it on or give me the contact detail of some one who can explain it.

Beyond that I would also be grateful if you could show me how to get a list of say 10 video ids that are banned in a given region. I have tried the followings without success:

1.	yt-dlp "ytsearch10:. mt=mt" --get-id 
2.	yt-dlp "ytsearch10:no_stream_malta" --get-id

 

Again, if you don’t know please send me contact details of someone who can help.

Finally, why are you so quick to close the case? Again, if you are too busy maybe you can give me the contact details of some one who has the time.

Awaiting your response impatiently please accept my

 

Best regards

Babak Kamali
