### ISSUE TITLE
Actual Website?

### ISSUE THREAD

**Issue by kkarhan** [yt-dlp/yt-dlp#6470]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I'd like to ask if there's any website planned, as discord is not indexable or in any shape or form accessible without any account.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
Are you asking for a forum? At most, we may create a landing page similar to https://youtube-dl.org, but beyond that there will be no website. While not maintained by me, the [r/youtube-dl](https://www.reddit.com/r/youtubedl) subreddit is the closest to a forum you will get.

> in any shape or form accessible without any account.

Our matrix server https://matrix.to/#/#yt-dlp:matrix.org is bridged to discord. Besides, unless your IP has been flagged, all you need to make a discord account is a throwaway email id.
