### ISSUE TITLE
New Site support request: fmovies

### ISSUE THREAD

**Issue by 31393939** [yt-dlp/yt-dlp#6471]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Worldwide

### Example URLs

- Single Video: https://fmovies.to/movie/missing-yjxlz/1-full
- Playlist or Series: https://fmovies.to/series/family-guy-j20r8/1-1 

### Provide a description that is worded well enough to be understood

I hope this website can be added to the supported websites from which I can download movies, TV shows, or series, as it is filled with all old and new movies, series, and programs and has many translations. I hope the website can be added to the other supported websites, so I can download any video with the translation I want, whether it's in Arabic, English, or any different language available in the translation of each movie, series, or program. Thanks to all those who work on yt-dlp, as they provide all of this for free without any financial cost

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://fmovies.to/movie/missing-yjxlz/1-full']
[debug] User config "C:\Users\userx\AppData\Roaming\yt-dlp\config.txt": ['-o', 'C:\\Users\\userx\\Downloads\\Youtube-Dl/%(title)s.%(ext)s', '-f', 'bestvideo[height<=1080][fps>=0]+bestaudio[ext=m4a]/bestvideo[height<=720][fps>=0]+bestaudio[ext=m4a]/bestvideo[height<=480][fps>=0]+bestaudio[ext=m4a]/bestvideo[height<=360][fps>=0]+bestaudio[ext=m4a]/bestvideo[height<=240][fps>=0]+bestaudio[ext=m4a]/bestvideo[height<=144][fps>=0]+bestaudio[ext=m4a]/best', '--yes-playlist', '-ciw', '--no-overwrites', '--embed-thumbnail', '--no-mtime', '--merge-output-format', 'mp4']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22621-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-109686-ged519a3690-20230128 (setts), ffprobe N-109686-ged519a3690-20230128, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
Current Build Hash: 5590c57bd0433ed239a2deaaf92e2ad6f37fe50f53664c821575cafe106a9421
yt-dlp is up to date (stable@2023.03.04)
[generic] Extracting URL: https://fmovies.to/movie/missing-yjxlz/1-full
[generic] 1-full: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] 1-full: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://fmovies.to/movie/missing-yjxlz/1-full
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1518, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1594, in __extract_info
  File "yt_dlp\extractor\common.py", line 694, in extract
  File "yt_dlp\extractor\generic.py", line 2510, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://fmovies.to/movie/missing-yjxlz/1-full
```

**Comment by coletdjnz** [comment]
piracy site, we will not support it
