### ISSUE TITLE
It's possible use "--audio-quality" if exists one specific quality?

### ISSUE THREAD

**Issue by chriskryon** [yt-dlp/yt-dlp#6472]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

For example
I was downloading the best audio quality but the files were getting too heavy.
I would like to know if this is possible:
If 128K is available I download, if not I download best (as it means best will be < 128K).

I could use `--audio-quality 128`, but for audios that are < 128 I don't know if the conversion would "spoil" the quality.

### Provide verbose output that clearly demonstrates the problem

- [] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
> If 128K is available I download, if not I download best (as it means best will be < 128K).

As you are describing, this has nothing to do with audio-quality. `-x -S abr:128k` sounds like what you want.

If not, elaborate, actually following the instructions you blindly ticked

**Comment by chriskryon** [comment]
> > Se 128K estiver disponível, eu faço o download, caso contrário, eu faço o download do melhor (pois significa que o melhor será < 128K).
> 
> Como você está descrevendo, isso não tem nada a ver com qualidade de áudio. `-x -S abr:128k`soa como o que você quer.
> 
> Caso contrário, elabore, seguindo as instruções que você marcou cegamente

Yes, I am visually impaired.
Thank you for the solution.
