### ISSUE TITLE
[youtube.com] "--match-filter '!live_status'" stopped working as expected. 

### ISSUE THREAD

**Issue by cutrus** [yt-dlp/yt-dlp#6475]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that a **supported** site is broken
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Poland

### Provide a description that is worded well enough to be understood

After the latest update of youtube.com, which broke a few things in yt-dlp, I also noticed that the live_status filter stopped working as expected. 

I used the `--match-filter '!live_status'` option on the server to backup videos from channels, excluding ongoing and archived livestreams. I noticed that for the past few days, this option has been filtering out random videos that were never livestreams.

Here are a few examples:
```
yt-dlp --match-filter '!live_status' 'https://www.youtube.com/watch?v=i1J_Sd7gtSM'  
yt-dlp --match-filter '!live_status' 'https://www.youtube.com/watch?v=WH03ht2fVqI' 
yt-dlp --match-filter '!live_status' 'https://www.youtube.com/watch?v=jD7zJDF-kac'
```

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--match-filter', '!live_status', 'https://www.youtube.com/watch?v=i1J_Sd7gtSM']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (debian*)
[debug] Python 3.10.6 (CPython x86_64 64bit) - Linux-5.19.0-28-generic-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.11.0, brotli-1.0.9, certifi-2020.06.20, mutagen-1.45.1, pyxattr-0.7.2, secretstorage-3.3.1, sqlite3-2.6.0, websockets-9.1
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
yt-dlp is up to date (stable@2023.03.04)
[youtube] Extracting URL: https://www.youtube.com/watch?v=i1J_Sd7gtSM
[youtube] i1J_Sd7gtSM: Downloading webpage
[youtube] i1J_Sd7gtSM: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[download] The Vintage Barbie Camcorder does not pass filter (!live_status), skipping ..
```

**Comment by pukkandan** [comment]
> I used the `--match-filter '!live_status'` option on the server to backup videos from channels, excluding ongoing and archived livestreams.

This is wrong command for what you are trying to do, and would not have worked even in prior versions. Can you show logs from an earlier version where it worked?

**Comment by pukkandan** [comment]
What you want is `--match-filter live_status=?not_live`

**Comment by cutrus** [comment]
@pukkandan  Ok, I see and probably understand why this isn't working. This !live_status will always be false because if a video is not a livestream, live_status returns the string "not_live".

I am confused because this was working for me for a few months. I can't share the logs now, but for example, this was working on the 2023.01.06 version.

I have checked the solution you provided and it works correctly. Thank you for your help, I am closing the issue.
