### ISSUE TITLE
Escapist Magazine V2

### ISSUE THREAD

**Issue by FakeShemp** [yt-dlp/yt-dlp#6477]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that a **supported** site is broken
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

World?

### Provide a description that is worded well enough to be understood

The Escapist Magazine mainly use YouTube for it's video content nowadays, but Zero Punctuation uses some [brid.tv](https://brid.tv) solution. I'm looking at the page source and it looks like a quite simple embedded mp4 link, but I'm not knowledgeable enough to implement it myself.

The current implementation only supports the v1 protocol of Escapist (v1.escapistmagazine.com) which this is not.

Example link https://www.escapistmagazine.com/dead-space-remake-2023-zero-punctuation/

Thank you!

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.escapistmagazine.com/dead-space-remake-2023-zero-punctuation/']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (pip)
[debug] Python 3.11.2 (CPython x86_64 64bit) - Linux-6.1.14-200.fc37.x86_64-x86_64-with-glibc2.36 (OpenSSL 3.0.8 7 Feb 2023, glibc 2.36)
[debug] exe versions: ffmpeg 5.1.2 (setts), ffprobe 5.1.2
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, secretstorage-3.3.3, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
yt-dlp is up to date (stable@2023.03.04)
[generic] Extracting URL: https://www.escapistmagazine.com/dead-space-remake-2023-zero-punctuation/
[generic] dead-space-remake-2023-zero-punctuation: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] dead-space-remake-2023-zero-punctuation: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://www.escapistmagazine.com/dead-space-remake-2023-zero-punctuation/
Traceback (most recent call last):
  File "/home/rebecca/.local/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1518, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rebecca/.local/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1594, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "/home/rebecca/.local/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 694, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rebecca/.local/lib/python3.11/site-packages/yt_dlp/extractor/generic.py", line 2510, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.escapistmagazine.com/dead-space-remake-2023-zero-punctuation/
```

**Comment by bashonly** [comment]
It looks like the extractor needs a complete rewrite. `v1.escapistmagazine.com` redirects to the current `www.escapistmagazine.com` site and all the extractor test URLs give 404 (and their content can no longer be found on the site)

**Comment by FakeShemp** [comment]
Going back to it now it seems they entirely dropped anything but Youtube embeds.

https://www.escapistmagazine.com/zero-punctuation-dropping-video-player-for-youtube-embeds-same-day-post-zp/

The old content is still hosted on Brid and can be downloaded, but I guess it's only a matter of time before it's all removed.
