### ISSUE TITLE
UFC-16 (Cyrillic) title name are seemingly having extra spaces (at least with colons and question marks)

### ISSUE THREAD

**Issue by mikkovedru** [yt-dlp/yt-dlp#6480]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

## How to reproduce
1. Check the title of [this video](https://www.youtube.com/watch?v=Ghl9GhyK5XI). We get: `ФИЛОЛОГ Исаев: Как звучит язык? Феминитивы и Мат`. This is Cyrillic. No problems with spacing around the colon and question mark.
2. Check the same readings (`title`/`fulltitle`) from inside the yt-dlp. Run `yt-dlp -j https://www.youtube.com/watch\?v\=Ghl9GhyK5XI | grep -oP '(?<="fulltitle": ")[^"]*'` to get the `\u0424\u0418\u041b\u041e\u041b\u041e\u0413 \u0418\u0441\u0430\u0435\u0432: \u041a\u0430\u043a \u0437\u0432\u0443\u0447\u0438\u0442 \u044f\u0437\u044b\u043a? \u0424\u0435\u043c\u0438\u043d\u0438\u0442\u0438\u0432\u044b \u0438 \u041c\u0430\u0442`. This is text in UTF-16 format.
3. Go [to converter](https://convertcodes.com/unicode-converter-encode-decode-utf/), paste the content into the `UTF-16` field and get the result in the first `Unicode` field. Notice how the colon and question mark look totally normal, without any extra spaces.
![image](https://user-images.githubusercontent.com/2521942/223859220-a44dc500-ed3a-4344-a24e-21784ff09f0d.png)
4. Use yt-dlp to download the youtube video and name it using the title/fulltitle. Run: `yt-dlp -o '%(title)s_%(fulltitle)s.%(ext)s' -f "bv*[height=480]+ba" --merge-output-format mkv --progress --concurrent-fragments 10 -R infinite -vU https://www.youtube.com/watch\?v\=Ghl9GhyK5XI`
5. Check how the name of the file looks. 
![image](https://user-images.githubusercontent.com/2521942/223859642-88565abc-e29b-4a99-acdf-9db87a835506.png)
It looks weird and seemingly has extra space in there. That's not how I want my file names to look; not in the ideal world.
6. Initially I thought that it was a buggy 2 bytes (UTF-16) -> 1 byte (UTF-8) conversion. But then I noticed that the name doesn't have any extra space characters in it and all the seemingly extra spacing is part of the characters used in the name. To illustrate, I edited the name and added the normal colon/question marks to both sides of the initial problematic characters. You can see that they are indeed somewhat different looking even visually.
![image](https://user-images.githubusercontent.com/2521942/223861183-7a093add-b3c8-4d22-bca6-8f1fcceadac7.png)
![image](https://user-images.githubusercontent.com/2521942/223861545-26076cf6-e423-4de9-bdb2-57871edda937.png)

## Verdict
It would be good to use the normal colons/question marks (and whatever other special characters) with normal width.

I don't know how to implement that or even where exactly is the problem. At this point, I can only draw your attention to the fact that the UTF-16 text (`\u0424\u0418\u041b\u041e\u041b\u041e\u0413 \u0418\u0441\u0430\u0435\u0432: \u041a\u0430\u043a \u0437\u0432\u0443\u0447\u0438\u0442 \u044f\u0437\u044b\u043a? \u0424\u0435\u043c\u0438\u043d\u0438\u0442\u0438\u0432\u044b \u0438 \u041c\u0430\u0442`) does not use some kind of fancy UTF code for colon and question mark, but is using these characters directly. So I assume that the issue lies in the way yt-dlp decides to convert these punctuation characters into something much fancier than needed. This is just my amateur observation.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
`yt-dlp -o '%(title)s_%(fulltitle)s.%(ext)s' -f "bv*[height=480]+ba" --merge-output-format mkv --progress --concurrent-fragments 10 -R infinite -vU https://www.youtube.com/watch\?v\=Ghl9GhyK5XI`

[debug] Command-line config: ['-o', '%(title)s_%(fulltitle)s.%(ext)s', '-f', 'bv*[height=480]+ba', '--merge-output-format', 'mkv', '--progress', '--concurrent-fragments', '10', '-R', 'infinite', '-vU', 'https://www.youtube.com/watch?v=Ghl9GhyK5XI']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (linux_exe)
[debug] Python 3.10.9 (CPython x86_64 64bit) - Linux-5.15.0-60-generic-x86_64-with-glibc2.35 (OpenSSL 3.0.8 7 Feb 2023, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2, phantomjs broken, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.16.0, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
Current Build Hash: 7494af600c4389d19961b44e406472bba7c54c28dc1f62bb72bdde7181708a9a
yt-dlp is up to date (stable@2023.03.04)
[youtube] Extracting URL: https://www.youtube.com/watch?v=Ghl9GhyK5XI
[youtube] Ghl9GhyK5XI: Downloading webpage
[youtube] Ghl9GhyK5XI: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[info] Ghl9GhyK5XI: Downloading 1 format(s): 244+251
[debug] Invoking dashsegments downloader on "https://rr2---sn-qo5-2vgz.googlevideo.com/videoplayback?expire=1678333407&ei=fwEJZKOmL4y1yQXEhIO4Cg&ip=2001%3A14ba%3Aa488%3Ab400%3Aa406%3Abe0e%3A9066%3Ad560&id=o-AFaDs8c_VdGBV430XuUwC6bFvsF1WkUS8BoWcXpCLj2l&itag=244&source=youtube&requiressl=yes&mh=p4&mm=31%2C29&mn=sn-qo5-2vgz%2Csn-ixh7rn76&ms=au%2Crdu&mv=m&mvi=2&pl=41&initcwndbps=1503750&spc=H3gIhifSpsHPicbWlIM8nlqLxKjj8OY&vprv=1&svpuc=1&mime=video%2Fwebm&gir=yes&clen=243186051&dur=5956.184&lmt=1676324883493431&mt=1678311434&fvip=4&keepalive=yes&fexp=24007246&c=ANDROID&txp=5537434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIgbq-dk_3m1XWQ6Pw3WJgfsDx7_ZBVt1dTWP_95xTjupUCIQCxfNjA74EaIoSqim6KmDj_BoHzLXuiJo3BYI0ZR_waug%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgJ9AmNQarjggOunSOWYmxzehDjGaSyAkPifeuhXl00l0CIEAXV80xKUhEpEdaCIn6tgtVIKpJNGmHRsMxFdtq5fR6"
[dashsegments] Total fragments: 24
[download] Destination: ФИЛОЛОГ Исаев： Как звучит язык？ Феминитивы и Мат_ФИЛОЛОГ Исаев： Как звучит язык？ Феминитивы и Мат.f244.webm
WARNING: The download speed shown is only of one thread. This is a known issue
[download] 100% of  231.92MiB in 00:00:44 at 5.22MiB/s
[debug] Invoking dashsegments downloader on "https://rr2---sn-qo5-2vgz.googlevideo.com/videoplayback?expire=1678333407&ei=fwEJZKOmL4y1yQXEhIO4Cg&ip=2001%3A14ba%3Aa488%3Ab400%3Aa406%3Abe0e%3A9066%3Ad560&id=o-AFaDs8c_VdGBV430XuUwC6bFvsF1WkUS8BoWcXpCLj2l&itag=251&source=youtube&requiressl=yes&mh=p4&mm=31%2C29&mn=sn-qo5-2vgz%2Csn-ixh7rn76&ms=au%2Crdu&mv=m&mvi=2&pl=41&initcwndbps=1503750&spc=H3gIhifSpsHPicbWlIM8nlqLxKjj8OY&vprv=1&svpuc=1&mime=audio%2Fwebm&gir=yes&clen=77023010&dur=5956.221&lmt=1676270744258170&mt=1678311434&fvip=4&keepalive=yes&fexp=24007246&c=ANDROID&txp=5532434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIgLGw-jN12WIEPXFlxtk50MmKKCnmp7uVu2HRd9-g4YBcCIQDvFAjU6wBl-OlneUbPW79W2BCFzJFqbcrwTtldubL2zg%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgJ9AmNQarjggOunSOWYmxzehDjGaSyAkPifeuhXl00l0CIEAXV80xKUhEpEdaCIn6tgtVIKpJNGmHRsMxFdtq5fR6"
[dashsegments] Total fragments: 8
[download] Destination: ФИЛОЛОГ Исаев： Как звучит язык？ Феминитивы и Мат_ФИЛОЛОГ Исаев： Как звучит язык？ Феминитивы и Мат.f251.webm
WARNING: The download speed shown is only of one thread. This is a known issue
[download] 100% of   73.45MiB in 00:00:13 at 5.37MiB/s
[Merger] Merging formats into "ФИЛОЛОГ Исаев： Как звучит язык？ Феминитивы и Мат_ФИЛОЛОГ Исаев： Как звучит язык？ Феминитивы и Мат.mkv"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:ФИЛОЛОГ Исаев： Как звучит язык？ Феминитивы и Мат_ФИЛОЛОГ Исаев： Как звучит язык？ Феминитивы и Мат.f244.webm' -i 'file:ФИЛОЛОГ Исаев： Как звучит язык？ Феминитивы и Мат_ФИЛОЛОГ Исаев： Как звучит язык？ Феминитивы и Мат.f251.webm' -c copy -map 0:v:0 -map 1:a:0 -movflags +faststart 'file:ФИЛОЛОГ Исаев： Как звучит язык？ Феминитивы и Мат_ФИЛОЛОГ Исаев： Как звучит язык？ Феминитивы и Мат.temp.mkv'
Deleting original file ФИЛОЛОГ Исаев： Как звучит язык？ Феминитивы и Мат_ФИЛОЛОГ Исаев： Как звучит язык？ Феминитивы и Мат.f251.webm (pass -k to keep)
Deleting original file ФИЛОЛОГ Исаев： Как звучит язык？ Феминитивы и Мат_ФИЛОЛОГ Исаев： Как звучит язык？ Феминитивы и Мат.f244.webm (pass -k to keep)
```

**Comment by pukkandan** [comment]
Issue is same as https://github.com/yt-dlp/yt-dlp/issues/4547

**Comment by mikkovedru** [comment]
https://stackoverflow.com/questions/1976007/what-characters-are-forbidden-in-windows-and-linux-directory-names/31976060#31976060

Why can't the program simply detect if it is running in Windows/Linux/Mac and act accordingly?

It's Windows that has a lot of limitations and edge cases, which makes it tricky. But with Linux it's easy-peasy. With Linux out of all the possibilities, there are only `/` (forward slash) and 0 (Null) forbidden. Very easy to filter that out. There is not even a need to convert characters to upper/lowercase.

**Comment by deanishe** [comment]
> The issue is that we have no mechanism to detect what are the supported characters in the filesystem and so sanitize characters conservatively, which includes replacing :?|

For me, the issue is the use of Unicode lookalikes in filenames. That's the kind of thing hackers do. I really don't want my own programs creating such misleading filenames.

Even if sanitisation continues to be conservative, please at least add an option to disable that behaviour.

**Comment by pukkandan** [comment]
> For me, the issue is the use of Unicode lookalikes in filenames
> ... please at least add an option to disable that behaviour.

https://github.com/yt-dlp/yt-dlp/issues/6480#issuecomment-2029131909

**Comment by deanishe** [comment]
> [#5014 (comment)](https://github.com/yt-dlp/yt-dlp/issues/5014#issuecomment-1256928588)

Thanks for the suggestion @pukkandan, but it doesn't help. Like I said, the problem is the lookalike characters. Removing *all* Unicode characters is a no-go because that mangles non-English. I similarly don't want to mangle the metadata.

I would just like to have normal filenames that haven't been mutilated for a filesystem I don't have.

> we have no mechanism to detect what are the supported characters in the filesystem

Create a temporary file whose name contains the problematic characters? If it works, no need to mangle the filenames.

**Comment by pukkandan** [comment]
> > we have no mechanism to detect what are the supported characters in the filesystem

That is an outdated comment and this is a duplicate issue. See https://github.com/yt-dlp/yt-dlp/issues/4547 and linked PR for current status
