### ISSUE TITLE
Optional dependencies enforced via `setup.py`

### ISSUE THREAD

**Issue by icp1994** [yt-dlp/yt-dlp#6484]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

The README mentions all dependencies apart from python itself being optional. But the `setup.py` pulls in everything from `requirements.txt` under `install_requires`. Does this mean downstream distributors who builds from source are recommended to patch the `setup.py` itself for a dependency-free installation?

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by icp1994** [comment]
Hi, thanks for the pointers. I don't have any suggestions, was just curious why those optional deps were "default".

**Comment by RuRo** [comment]
@pukkandan Hi. Do you think, you can revisit this issue? Please, either declare these dependencies as non-optional or (preferably, imho) remove the optional dependencies from `install_requires` in `setup.py` (at least by default, you can re-enable them when building the wheels for PyPI for example).

Currently, the package metadata is wrong and asking downstream distributors to patch it is kind of weird. I submitted a bug report to the Arch Linux maintainers asking to patch the `requirements.txt` like you are suggesting, and they (very understandably) refused.

Thanks.

**Comment by pukkandan** [comment]
Sorry, but we want **default** installs (from pip or source) to have these dependencies included. Unless some way to do https://github.com/pypa/setuptools/issues/1139 becomes available, it is not feasible to remove them.
