### ISSUE TITLE
Why did the new version of the 1080p webm format disappear?

### ISSUE THREAD

**Issue by DDRRINON** [yt-dlp/yt-dlp#6487]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Is this a youtube limitation issue?

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
C:\Tools\yt-dlp>yt-dlp --list-formats --proxy socks5://127.0.0.1:1080/ https://www.youtube.com/watch?v=UAXS7X6VjWo
[youtube] Extracting URL: https://www.youtube.com/watch?v=UAXS7X6VjWo
[youtube] UAXS7X6VjWo: Downloading webpage
[youtube] UAXS7X6VjWo: Downloading android player API JSON
[info] Available formats for UAXS7X6VjWo:
ID  EXT   RESOLUTION FPS CH │  FILESIZE   TBR PROTO │ VCODEC        VBR ACODEC      ABR ASR MORE INFO
─────────────────────────────────────────────────────────────────────────────────────────────────────────────
sb2 mhtml 48x27        1    │                 mhtml │ images                                storyboard
sb1 mhtml 80x45        1    │                 mhtml │ images                                storyboard
sb0 mhtml 160x90       1    │                 mhtml │ images                                storyboard
139 m4a   audio only      2 │   1.15MiB   49k dash  │ audio only        mp4a.40.5   49k 22k low, m4a_dash
140 m4a   audio only      2 │   3.05MiB  129k dash  │ audio only        mp4a.40.2  129k 44k medium, m4a_dash
251 webm  audio only      2 │   3.07MiB  130k dash  │ audio only        opus       130k 48k medium, webm_dash
17  3gp   176x144      7  1 │   1.73MiB   73k https │ mp4v.20.3     73k mp4a.40.2    0k 22k 144p
160 mp4   256x144     30    │   2.77MiB  118k dash  │ avc1.4d400c  118k video only          144p, mp4_dash
134 mp4   640x360     30    │  13.61MiB  579k dash  │ avc1.4d401e  579k video only          360p, mp4_dash
18  mp4   640x360     30  2 │  15.88MiB  675k https │ avc1.42001E  675k mp4a.40.2    0k 44k 360p
243 webm  640x360     30    │   8.28MiB  352k dash  │ vp9          352k video only          360p, webm_dash
22  mp4   1280x720    30  2 │ ~50.03MiB 2081k https │ avc1.64001F 2081k mp4a.40.2    0k 44k 720p
136 mp4   1280x720    30    │  45.89MiB 1952k dash  │ avc1.64001f 1952k video only          720p, mp4_dash
137 mp4   1920x1080   30    │  80.24MiB 3413k dash  │ avc1.640028 3413k video only          1080p, mp4_dash

C:\Tools\yt-dlp>
```

**Comment by pukkandan** [comment]
Unless you have reason to believe the format is available in browser, the only answer I can give you is "ask youtube". If they don't make it available, we can't get it...
