### ISSUE TITLE
[AfreecaTV] Ability to switch between servers with options

### ISSUE THREAD

**Issue by chorong761** [yt-dlp/yt-dlp#6497]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a site-specific feature
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Most parts of the world

### Example URLs

https://play.afreecatv.com/m0m099/live

### Provide a description that is worded well enough to be understood

AfreecaTV has more than one server/CDN and I would like to have the ability to use options in the command line to switch between them.

To what I know, yt-dlp uses "gcp_cdn" and streamlink uses "gs_cdn_pc_web".

The reason why I want this feature is that gcp is giving me some issues where it would be very unstable at a certain day/time and streamlink doesn't have the --no-hls-use-mpegts command that I use with yt-dlp.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://play.afreecatv.com/m0m099/live']
[debug] Encodings: locale cp950, fs utf-8, pref cp950, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22621-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-107944-g4fce3bab64-20220830 (setts), ffprobe N-107944-g4fce3bab64-20220830
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
Current Build Hash: 5590c57bd0433ed239a2deaaf92e2ad6f37fe50f53664c821575cafe106a9421
yt-dlp is up to date (stable@2023.03.04)
[afreecatv:live] Extracting URL: https://play.afreecatv.com/m0m099/live
[afreecatv:live] m0m099: Downloading JSON metadata
[afreecatv:live] 245401012: Downloading access token for sd stream
[afreecatv:live] 245401012: Downloading metadata for sd stream
[afreecatv:live] 245401012: Downloading access token for hd stream
[afreecatv:live] 245401012: Downloading metadata for hd stream
[afreecatv:live] 245401012: Downloading access token for hd2k stream
[afreecatv:live] 245401012: Downloading metadata for hd2k stream
[afreecatv:live] 245401012: Downloading access token for original stream
[afreecatv:live] 245401012: Downloading metadata for original stream
[afreecatv:live] 245401012: Downloading channel metadata
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: best/bestvideo+bestaudio
[info] 245401012: Downloading 1 format(s): original
[debug] Invoking ffmpeg downloader on "https://live-global-cdn-v02.afreecatv.com/live-stm-01/auth_playlist.m3u8?aid=.A32.7bbT56vyHM9fKZk.Jd0P35RgmksLW32apUsJiTT30jbEaCSkVevKEMukEgl4XtdqRQ2jltIS4uxOnlUy-k3UtdZAj3AnSYmvOp8VNzG9hTskKMuLvgSww_QBvWE"
[download] Destination: 항공캠 궁금하지않앙？..ㅎ♥ 2023-03-09 20_08 [245401012].mp4
[debug] ffmpeg command line: ffmpeg -y -loglevel verbose -headers "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.17 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-us,en;q=0.5
Sec-Fetch-Mode: navigate
```

**Comment by bashonly** [comment]
As of 9073ae6458f4c6a832aa832c67174c61852869be, yt-dlp is using `gs_cdn_pc_app`

This could easily be added as an extractor-arg though
