### ISSUE TITLE
M3u8 file inside of blob: link

### ISSUE THREAD

**Issue by hasnogaems** [yt-dlp/yt-dlp#6506]
If an m3u8 playlist is hidden inside blob: link that have no extension, for example:
`blob:https://www.sitename.com/73b54781-4ffb-4f2b-b476-f0eas0c343b4`
If you open this link there will be valid m3u8, but yt-dlp do not recognise it by default. Can I force it?

**Comment by pukkandan** [comment]
https://stackoverflow.com/questions/30864573/what-is-a-blob-url-and-why-it-is-used
