### ISSUE TITLE
[help]after the download is complete, what command is used to let "cmd" exit by itself?

### ISSUE THREAD

**Issue by dodolook8** [yt-dlp/yt-dlp#6508]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

after the download is complete, what command is used to let "cmd" exit by itself?

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
after the download is complete, what command is used to let "cmd" exit by itself?

It's a bit of a hassle to click to close each time.
thx！
```

**Comment by bashonly** [comment]
Add `&& exit` to the end of your command
e.g.
```
yt-dlp "URL" && exit
```

**Comment by gamer191** [comment]
or `--exec exit`

**Comment by gamer191** [comment]
NOTE: my above answer only works on Windows. Also, it doesn't work with playlists, and will exit after the first video

**Comment by dirkf** [comment]
You could just leave the _cmd_, or shell, window open but minimised. Then for the next download just restore the window, use up-arrow to recall the last (or a similar) _yt-dlp_ command, edit the URL part, and go. But _[de gustibus](https://en.wikipedia.org/wiki/De_gustibus_non_est_disputandum)_ ...

**Comment by pukkandan** [comment]
> or `--exec exit`

Doesn't work. It just opens a new cmd and exits it. Programs[^1] like yt-dlp cannot close the parent shell without either killing the process or using the windows API 

[^1]: As opposed to shell builtins and batch files

**Comment by MarcinNaGicie** [comment]
The thread is a bit old, but maybe it will be helpful.
It works for me.
```batchfile
@echo off
echo.
echo Paste the url address and confirm. [ENTER]
set /p "InputURL=URL: "
rem yt-dlp -v -F --buffer-size 8192 -N 16 %InputURL%
call :yt-dlp_processing
cls
color 06
echo Download completed successfully.
timeout 5
exit
rem ------------------------------------------------------------------
:yt-dlp_processing
@echo off
yt-dlp -v -f "bestvideo[height=1080]+bestaudio/best[height<=1080]/best" -S ext:mp4:m4a,res:1080 --buffer-size 8192 -N 16 "%InputURL%"
exit /b
```
