### ISSUE TITLE
[SpankBang] Broken in Telegram Bot

### ISSUE THREAD

**Issue by pegasusdamorte** [yt-dlp/yt-dlp#6509]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that a **supported** site is broken
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Brazil

### Provide a description that is worded well enough to be understood

ERROR: [SpankBang] 4qk72: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); 

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
ERROR: [SpankBang] 4qk72: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>);
```

**Comment by bashonly** [comment]
> I've checked that **all provided URLs are playable in a browser with the same IP** and same login details

Did you actually do this? Where is the example URL? 

Is it only the telegram bot that is broken? Does the link work with yt-dlp? 

Don't just copy/paste a 1 line error message; explain the issue and post complete logs.

**Comment by 54m4d** [comment]
I get a different error for profile pages, like this one:

```python
yt-dlp is up to date (stable@2023.03.04)
[generic] Extracting URL: https://spankbang.com/profile/entand
[generic] entand: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] entand: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://spankbang.com/profile/entand
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1518, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1594, in __extract_info
  File "yt_dlp\extractor\common.py", line 694, in extract
  File "yt_dlp\extractor\generic.py", line 2510, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://spankbang.com/profile/entand
```

**Comment by pukkandan** [comment]
@54m4d https://github.com/yt-dlp/yt-dlp/issues/5156
