### ISSUE TITLE
ERROR: Fixed output name but more than one file to download: with --exec 'post_process' only, on Windows only. Intermittent problem.

### ISSUE THREAD

**Issue by Fohsap** [yt-dlp/yt-dlp#6511]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Windows-Specific problem.
Videos that merge into webm format are ween as "more than one file" by the --exec flag, intermittently.

About 80% of the time, my command succeeds; however, about 20% of the time, my command fails. I cannot figure out why, and I cannot correct this. This issue occurs in CMD and PowerShell and has persisted across multiple versions (including fully updated 2023.03.04).

On Linux, this problem does not seem to exist, as I have never encountered it on my linux box and have tested failure urls on the same device in a Debian WSL (albeit, software-emulated--there is no raw metal virtualization available on this device); also, I have tested failure urls on other linux devices and succeeded consistently--I have never encountered this problem in Linux.

Command with broken url (same command, different values):
` yt-dlp "https://youtu.be/mxIYzZEMcBI" -f "bv[height<360]+ba" --no-playlist --merge-output-format "webm" --output "./tmp/rotations 2dltmp"`
` yt-dlp "https://www.youtube.com/watch?v=fRgWBN8yt_E" -f "bv[height<360]+ba" --no-playlist --merge-output-format "webm" --output "./tmp/georgiadltmp" --exec 'post_process:ffmpeg -hide_banner -i "%(filepath)q" -c:v libx264 -r 25 -preset fast -crf 22 -vf format=yuv420p,scale=480:360 -strict -2 -profile:v high "./georgia-_-ray charles.mov"'` 

*Please note: these commands do not include grave tics.

I've searched exhaustively for this issue in the bug tracker, on stack exchange, and in the known issue list and seen nothing similar.

**Here's a command and output without verbose output (the verbose output is in the next field):**
ERROR: Fixed output name but more than one file to download: ./tmp/rotations 2dltmp`

**I can prove that the output file is ONE file:**
Command and output without --exec:

`yt-dlp "https://youtu.be/mxIYzZEMcBI" -f "bv[height<360]+ba" --no-playlist --merge-output-format "webm" --output "./tmp/rotations 2dltmp"
[youtube] Extracting URL: https://youtu.be/mxIYzZEMcBI
[youtube] mxIYzZEMcBI: Downloading webpage
[youtube] mxIYzZEMcBI: Downloading android player API JSON
[youtube] mxIYzZEMcBI: Downloading MPD manifest
[info] mxIYzZEMcBI: Downloading 1 format(s): 242+251
[dashsegments] Total fragments: 35
[download] Destination: tmp\rotations 2dltmp.f242.webm
[download] 100% of    2.07MiB in 00:01:49 at 19.41KiB/s
[download] Destination: tmp\rotations 2dltmp.f251.webm
[download] 100% of    2.75MiB in 00:00:05 at 476.11KiB/s
[Merger] Merging formats into "tmp\rotations 2dltmp.webm"
Deleting original file tmp\rotations 2dltmp.f251.webm (pass -k to keep)
Deleting original file tmp\rotations 2dltmp.f242.webm (pass -k to keep)`

Then I can run ffmpeg properly.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
`yt-dlp -vU "https://youtu.be/mxIYzZEMcBI" -f "bv[height<360]+ba" --no-playlist --merge-output-format "webm" --output "./tmp/rotations 2dltmp" --exec 'post_process:ffmpeg -hide_banner -i "%(filepath)q" -c:v libx264 -r 25 -preset fast -crf 22 -vf format=yuv420p,scale=480:360 -strict -2 -profile:v high "./rotations 2-_-Jack Elphick.mov"'
[debug] Command-line config: ['-vU', 'https://youtu.be/mxIYzZEMcBI', '-f', 'bv[height<360]+ba', '--no-playlist', '--merge-output-format', 'webm', '--output', './tmp/rotations 2dltmp', '--exec', 'post_process:ffmpeg -hide_banner -i %(filepath)q -c:v libx264 -r 25 -preset fast -crf 22 -vf format=yuv420p,scale=480:360 -strict -2 -profile:v high ./rotations', '2-_-Jack', 'Elphick.mov']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (pip)
[debug] Python 3.7.3 (CPython AMD64 64bit) - Windows-10-10.0.19041-SP0 (OpenSSL 1.1.0j  20 Nov 2018)
[debug] exe versions: ffmpeg N-93986-gd3f236b300, ffprobe N-93986-gd3f236b300
[debug] Optional libraries: Cryptodome-3.14.1, brotli-1.0.9, certifi-2019.03.09, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.2
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
yt-dlp is up to date (stable@2023.03.04)
ERROR: Fixed output name but more than one file to download: ./tmp/rotations 2dltmp`
```

**Comment by pukkandan** [comment]
> [debug] Command-line config: ['-vU', 'https://youtu.be/mxIYzZEMcBI', ..., '2-_-Jack', 'Elphick.mov']

Single quotes don't work on windows, causing yt-dlp to think you are passing 3 URLs `https://youtu.be/mxIYzZEMcBI`, `2-_-Jack`, `Elphick.mov`. You'll need to fix your quoting
