### ISSUE TITLE
Add option to pass/filter filenames through an arbitrary external program

### ISSUE THREAD

**Issue by jtru** [yt-dlp/yt-dlp#6521]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Plenty of open (and resolved :)) yt-dlp issues deal with problems regarding filenames, and how yt-dlp should mangle them under specific, yet varying, circumstances.

To give users so inclined a universal escape hatch that can satisfy everyone's needs, a new option should be introduced that takes the path to another executable as its argument. If set, for each file that yt-dlp is going to write to disk, it should invoke that executable as a subprocess, feed yt-dlp's notion of the `YoutubeDL` object's `filename` into that process's standard input, and read the resulting, final `filename` it shall use to store the downloaded content in on that process's standard output.

With this mechanism, users could implement their own "filename policy engines", with conceivable implementations ranging from something as trivial as a one-line shell script to elaborate programs that are centrally coordinated by blockchain-backed AI voodoo. (As far as I understand the documentation of `--exec`, this would be similar in methodology, but cannot actually be achieved using `--exec`.)

If this seems like a worthwhile feature to have, I'd be wiling to try to provide patches implementing it.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
Can you give a concrete use-case? I don't think this is a useful enough feature. Instead of writing such a "filename engine", it'd be easier imo to `--write-info`, build the filename, and `--load-info` back with appropriate `-o`. Or, if u don't mind re-extraction, just do 2 passes. Unlike your proposal, both these methods get access to the full info-dict, not just the filename, making it much more powerful too.

**Comment by jtru** [comment]
Thanks for weighing in! :) My _concrete_ use case is this: I use a command line like `yt-dlp --trim-filenames=120 url1 url2 url3` to download a number of files that, despite the requested trimming, (in part) result in filenames that are too long for the Linux VFS layer to be able to be stored, with the download process failing because of that.

Now if I could do something like `yt-dlp --filename-mangle-script=~/myNeatScript url1 url2 url3` that would work in the described way, and the script looking something (I am only making this up; the real thing would have to be more elaborate to be generally useful) like this:

```bash
#!/usr/bin/env
cut -c 1:120 | tr -d \\n; echo ".mp4"
```

... I would achieve pretty much the desired effect. And if someone were to come along with a much more sophisticated need to deal with the resulting filenames, that would also be possible.

**Comment by numpad0** [comment]
IIRC, `--trim-filenames` only affect final output filename and not temp files whereas  `-o` option with e.g. `-o "%(title).150B [%(id)s].%(ext)s"` works on both, or something along that.  

> Can you give a concrete use-case?  

> To give users so inclined a universal escape hatch that can satisfy everyone's needs, 

I think it's just that people are frustrated by yt-dlp slamming the floor face first just because the filename just so happens to be just too long, and the needs is just that people just want it to just not happening, and it so seems that the author is proposing a way that is not `.150B` because that suggestion was not accepted previously.

btw, isn't it just a 5 byte addition to [utils.py:3454](https://github.com/yt-dlp/yt-dlp/blob/master/yt_dlp/utils.py#L3454) ?

**Comment by chapmanjacobd** [comment]
> frustrated by yt-dlp slamming the floor face first just because the filename just so happens to be just too long, and the needs is just that people just want it to just not happening

The 255 bytes / 255 (UTF-16, ASCII, ?) char filename limit is pretty common across platforms: 

- Windows: NTFS 255 char (UTF-16?) [also has directory fragment limitation but pretty high: 
- Mac OS: HFS+ 255 UTF-16; 
- Linux: ext4/Btrfs 255 Bytes

https://en.wikipedia.org/wiki/Comparison_of_file_systems#Limits

    [Errno 36] File name too long: '/path/redacted/long_filename.....[id].mp4.ytdl'

I wonder if the an acceptable solution here would be to make --trim-filenames a little more smart by making it less likely to remove interesting stuff perhaps by removing the middle blindly:

```
    fs_limit = max_name_len - len(ext.encode()) - len("...") - 1
    if len(stem.encode()) > fs_limit:
        start = stem[: fs_limit // 2]
        end = stem[-fs_limit // 2 :]
        while len(start.encode()) > fs_limit // 2:
            start = start[:-1]
        while len(end.encode()) > fs_limit // 2:
            end = end[1:]
        stem = start + "..." + end
```

The length of the temporary extensions also needs to be considered...

**Comment by dirkf** [comment]
When considering possible tactics to overcome filename limits, it may be helpful to review the [T-shirt](https://github.com/ytdl-org/youtube-dl/issues/29912) and related links.
