### ISSUE TITLE
Chaturbate Extractor Returns a 403 error

### ISSUE THREAD

**Issue by trdrdtrded** [yt-dlp/yt-dlp#6546]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that a **supported** site is broken
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United States

### Provide a description that is worded well enough to be understood

When running yt-dlp with Chaturbate, the site now returns a 403 error. It was working a couple of weeks ago with the command shown below.

It seems as though Chaturbate updated something and the Extractor now needs updating too. 

Happy to provide more information if needed.

```
$ yt-dlp -vU https://chaturbate.com/siswet19/
```

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://chaturbate.com/siswet19/']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (pip)
[debug] Python 3.10.6 (CPython x86_64 64bit) - Linux-5.15.0-58-generic-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2, phantomjs 1.9.8
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.45.1, secretstorage-3.3.1, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
yt-dlp is up to date (stable@2023.03.04)
[Chaturbate] Extracting URL: https://chaturbate.com/siswet19/
[Chaturbate] siswet19: Downloading webpage
ERROR: [Chaturbate] siswet19: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/home/computer/.local/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 694, in extract
    ie_result = self._real_extract(url)
  File "/home/computer/.local/lib/python3.10/site-packages/yt_dlp/extractor/chaturbate.py", line 39, in _real_extract
    webpage = self._download_webpage(
  File "/home/computer/.local/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 1097, in _download_webpage
    return self.__download_webpage(url_or_request, video_id, note, errnote, None, fatal, *args, **kwargs)
  File "/home/computer/.local/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 1048, in download_content
    res = getattr(self, download_handle.__name__)(url_or_request, video_id, **kwargs)
  File "/home/computer/.local/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 882, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query, expected_status=expected_status)
  File "/home/computer/.local/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 839, in _request_webpage
    raise ExtractorError(errmsg, cause=err)

  File "/home/computer/.local/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 821, in _request_webpage
    return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query))
  File "/home/computer/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3742, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/usr/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

**Comment by bashonly** [comment]
Are you sure about this:

> I've checked that all provided URLs are playable in a browser with the same IP and same login details

I can't reproduce the issue:
```
$ yt-dlp -F "https://chaturbate.com/siswet19/"
[Chaturbate] Extracting URL: https://chaturbate.com/siswet19/
[Chaturbate] siswet19: Downloading webpage
[Chaturbate] siswet19: Downloading m3u8 information
[info] Available formats for siswet19:
ID EXT RESOLUTION │   TBR PROTO │ VCODEC        VBR ACODEC    ABR
─────────────────────────────────────────────────────────────────
0  mp4 426x240    │  488k m3u8  │ avc1.42c015  488k mp4a.40.2  0k
1  mp4 854x480    │ 1258k m3u8  │ avc1.4d401f 1258k mp4a.40.2  0k
2  mp4 1280x720   │ 3396k m3u8  │ avc1.4d401f 3396k mp4a.40.2  0k
3  mp4 1280x720   │ 5046k m3u8  │ avc1.4d4020 5046k mp4a.40.2  0k
4  mp4 1920x1080  │ 7828k m3u8  │ avc1.64002a 7828k mp4a.40.2  0k
```

**Comment by trdrdtrded** [comment]
@bashonly Thank you for providing feedback.

I operate behind a VPN and tried multiple VPN locations with no success before submitting this ticket. I have further tested more VPN locations and found one that is working. So it has something to do with Chaturbate blocking the IP address of the specific VPN servers. Therefore yt-dlp has no issues here.

It is worth noting, in both cases, the browser had no problems and the video was playable.

**Comment by cv1618** [comment]
I've been having the same problem, I have to keep trying different vpn ip's until one works. They must be trying to crack down on shows getting recorded and uploaded to recurbate and rectube.

**Comment by biggestsonicfan** [comment]
Getting it due to cloudflare. Remember, you can always search the page's source for the `playlist.m3u8` url and [decode it](https://www.w3docs.com/tools/html-encoder/) and use that instead of the room url.

**Comment by gamer191** [comment]
@biggestsonicfan I can't reproduce

If you're on the latest version of yt-dlp, can you please run it with `--dump-pages --verbose --print-traffic` and send me both a verbose log and the page dumps

You can find me on discord `gamer.191`, although you might need to first join the [yt-dlp discord server](https://discord.gg/H5MNcFW63r)

**Comment by biggestsonicfan** [comment]
I can't get it to 403 again at the moment lol :shrug:

**Comment by insanity54** [comment]
I don't think this is a yt-dlp issue. I think this is an issue of blocked networks, as carried out by Chaturbate's Cloudflare protections. 

Run yt-dlp on a residential network, you'll likely get through.

Run yt-dlp behind a known VPN, or on a VPS, and you'll get blocked (403).

**Comment by gamer191** [comment]
> I can't get it to 403 again at the moment lol 🤷

Don't worry about it

> I don't think this is a yt-dlp issue.
> The cloud server is being served a Cloudflare challenge

The fact that yt-dlp can't solve Cloudflare captchas is a known issue, and one that will hopefully be solved by #7595

In the mean time, see https://github.com/yt-dlp/yt-dlp/wiki/FAQ#im-getting-http-error-403-and-the-site-has-an-open-issue-on-the-tracker-thats-labeled-cloudflare-related-what-can-i-do

On a side note, the curl command will most likely work if you use `--user-agent "jhgfdcsfvgbhjnuikjytgfdcfvgbhju"` (replace that string with whatever you want). Can you please test if it does

**Comment by twist3dimages** [comment]
Interesting. Mine stopped working like 2 weeks ago

**Comment by twist3dimages** [comment]
Also as I said, it still works, the method here still works, on the same network. [https://sleazyfork.org/en/scripts/441079-chaturbate-enhancer](url)

**Comment by biggestsonicfan** [comment]
> Also as I said, the method here still works, on the same network. [https://sleazyfork.org/en/scripts/441079-chaturbate-enhancer](url)

Why would you hotlink `https://sleazyfork.org/en/scripts/441079-chaturbate-enhancer` to the url `https://github.com/yt-dlp/yt-dlp/issues/url`, that makes absolutely no sense...

**Comment by pukkandan** [comment]
It's a common mistake people make due to GH's comment editor UI

**Comment by twist3dimages** [comment]
> > Also as I said, the method here still works, on the same network. [https://sleazyfork.org/en/scripts/441079-chaturbate-enhancer](url)
> 
> Why would you hotlink `https://sleazyfork.org/en/scripts/441079-chaturbate-enhancer` to the url `https://github.com/yt-dlp/yt-dlp/issues/url`, that makes absolutely no sense...

I don't normally post issues, didn't realize it was a big deal ¯\_(ツ)_/¯

**Comment by biggestsonicfan** [comment]
To get back on track, you said "Also as I said, the method here still works, on the same network"

What did you mean "Also as I said" as your only previous comment was "Interesting. Mine stopped working like 2 weeks ago". I am trying to understand how Chaturbate Enhancer relates to the 403 error issue or is a workaround?

Analyzing the code, it uses the `getVideo()` function to grab the first indexed element within that object and passes it to `captureStream()`, which just returns the [captureSream() method](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/captureStream) of the video streaming object.

So it's a simple script that taps into the already playing html5 element's player to use a baked-in routine to save data. Alright.

Looking a little further, it still seems to analyze whether or not `hls_source` exists in the json metadata,[ which is exactly what yt-dlp already does](https://github.com/yt-dlp/yt-dlp/blob/9073ae6458f4c6a832aa832c67174c61852869be/yt_dlp/extractor/chaturbate.py#L51C46-L51C56).

So it appears the browser, when using Chaturbate normally, gets around the 403 errors, and the Enhancer simply injects scripts into already existing html5 elements. That won't be helpful to yt-dlp which is establishing a new, headless, connection. Especially when their methods for obtaining the video data url are identical

**Comment by twist3dimages** [comment]
BTW - using --force-ipv4 makes it work

**Comment by biggestsonicfan** [comment]
Oh hey, that's a new one, will give that a try next time it fails. Hadn't thought of that.

**Comment by m-kozlowski** [comment]
I also recently started getting occasional 403 errors. --force-ipv4 did not help. 
What did help, however, was switching to the new api (issues/10359) *and* removing Sec-Fetch-Mode from std_headers.

here's quick and dirty patch
```diff
diff --git a/yt_dlp/extractor/chaturbate.py b/yt_dlp/extractor/chaturbate.py
index 864d61f9c..263265d93 100644
--- a/yt_dlp/extractor/chaturbate.py
+++ b/yt_dlp/extractor/chaturbate.py
@@ -46,30 +46,18 @@ def _real_extract(self, url):
         video_id, tld = self._match_valid_url(url).group('id', 'tld')

         webpage = self._download_webpage(
-            f'https://chaturbate.{tld}/{video_id}/', video_id,
-            headers=self.geo_verification_headers())
+            f'https://chaturbate.{tld}/get_edge_hls_url_ajax/', video_id,
+            data=f'room_slug={video_id}'.encode(),
+            headers=self.geo_verification_headers()|{"X-Requested-With": "XMLHttpRequest"})

         found_m3u8_urls = []

-        data = self._parse_json(
-            self._search_regex(
-                r'initialRoomDossier\s*=\s*(["\'])(?P<value>(?:(?!\1).)+)\1',
-                webpage, 'data', default='{}', group='value'),
-            video_id, transform_source=lowercase_escape, fatal=False)
-        if data:
-            m3u8_url = url_or_none(data.get('hls_source'))
+        data = self._parse_json(webpage, 'data')
+        if data and data["success"]:
+            m3u8_url = url_or_none(data.get('url'))
             if m3u8_url:
-                found_m3u8_urls.append(m3u8_url)
-
-        if not found_m3u8_urls:
-            for m in re.finditer(
-                    r'(\\u002[27])(?P<url>http.+?\.m3u8.*?)\1', webpage):
-                found_m3u8_urls.append(lowercase_escape(m.group('url')))
-
-        if not found_m3u8_urls:
-            for m in re.finditer(
-                    r'(["\'])(?P<url>http.+?\.m3u8.*?)\1', webpage):
-                found_m3u8_urls.append(m.group('url'))
+                found_m3u8_urls.append(data["url"])
+

         m3u8_urls = []
         for found_m3u8_url in found_m3u8_urls:
@@ -84,8 +72,7 @@ def _real_extract(self, url):
                  r'<div[^>]+id=(["\'])defchat\1[^>]*>\s*<p><strong>(?P<error>[^<]+)<'],
                 webpage, 'error', group='error', default=None)
             if not error:
-                if any(p in webpage for p in (
-                        self._ROOM_OFFLINE, 'offline_tipping', 'tip_offline')):
+                if data.get('room_status') == 'offline':
                     error = self._ROOM_OFFLINE
             if error:
                 raise ExtractorError(error, expected=True)
diff --git a/yt_dlp/utils/networking.py b/yt_dlp/utils/networking.py
index 933b164be..9554ea281 100644
--- a/yt_dlp/utils/networking.py
+++ b/yt_dlp/utils/networking.py
@@ -83,7 +83,6 @@ def __contains__(self, key):
     'User-Agent': random_user_agent(),
     'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
     'Accept-Language': 'en-us,en;q=0.5',
-    'Sec-Fetch-Mode': 'navigate',
 })

```

**Comment by m-kozlowski** [comment]
looks like it does:)
