### ISSUE TITLE
iwara.tv update broke downloading

### ISSUE THREAD

**Issue by bobbbob98** [yt-dlp/yt-dlp#6549]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that a **supported** site is broken
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Provide a description that is worded well enough to be understood

iwara.tv updated their ui which changed how videos are served, making video and channel downloading not work. Probably everything for the site needs to be updated.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
~$ yt-dlp -vU https://ecchi.iwara.tv/video/1KR8Z8OI4sG1Qb
[debug] Command-line config: ['-vU', 'https://ecchi.iwara.tv/video/1KR8Z8OI4sG1Qb']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d]
[debug] Lazy loading extractors is disabled
[debug] Python 3.11.2 (CPython x86_64 64bit) - Linux-6.1.18-200.fc37.x86_64-x86_64-with-glibc2.36 (OpenSSL 3.0.8 7 Feb 2023, glibc 2.36)
[debug] exe versions: ffmpeg 5.1.2 (setts), ffprobe 5.1.2
[debug] Optional libraries: Cryptodome-3.17.0, brotli-1.0.9, certifi-2021.10.08, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
yt-dlp is up to date (stable@2023.03.04)
[generic] Extracting URL: https://ecchi.iwara.tv/video/1KR8Z8OI4sG1Qb
[generic] 1KR8Z8OI4sG1Qb: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] 1KR8Z8OI4sG1Qb: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://ecchi.iwara.tv/video/1KR8Z8OI4sG1Qb
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1518, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1594, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 694, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/extractor/generic.py", line 2510, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://ecchi.iwara.tv/video/1KR8Z8OI4sG1Qb

~$ yt-dlp -vU https://ecchi.iwara.tv/profile/mmdnecrox
[debug] Command-line config: ['-vU', 'https://ecchi.iwara.tv/profile/mmdnecrox']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d]
[debug] Lazy loading extractors is disabled
[debug] Python 3.11.2 (CPython x86_64 64bit) - Linux-6.1.18-200.fc37.x86_64-x86_64-with-glibc2.36 (OpenSSL 3.0.8 7 Feb 2023, glibc 2.36)
[debug] exe versions: ffmpeg 5.1.2 (setts), ffprobe 5.1.2
[debug] Optional libraries: Cryptodome-3.17.0, brotli-1.0.9, certifi-2021.10.08, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
yt-dlp is up to date (stable@2023.03.04)
[generic] Extracting URL: https://ecchi.iwara.tv/profile/mmdnecrox
[generic] mmdnecrox: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] mmdnecrox: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://ecchi.iwara.tv/profile/mmdnecrox
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1518, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1594, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 694, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/extractor/generic.py", line 2510, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://ecchi.iwara.tv/profile/mmdnecrox
```

**Comment by toomyzoom** [comment]
I took a look and so far, this is what changed:
Old api:
`https://www.iwara.tv/api/video/**<video_id>**`
=> this used to return JSON with links in 3 resolutions: Source, 540p, and 360p. There was no video information
New api:
`https://api.iwara.tv/video/**<video_id>**`
=> this now return full video information: title, user, tag, private, likes, createdAt, updatedAt, etc.... There is one field should be paid attention to: **fileUrl**.
It's in this format:
`https://files.iwara.tv/file/**<uuid>**?expires=**<epoch_timestamp>**&hash=**<some arbitrary hash>**`
If you do a http request using what fileUrl value, it will return JSON with 3 resolutions video links. However, the HTTP request needs field "**X-Version**". which is an arbitrary string calculated in main.js. I'm not sure how it was generated looking at that javascript code. The script look like generated code. Without that header, files.iwara.tv will return empty JSON.

**Comment by Lesmiscore** [comment]
I've tried accessing the site just now, but it looks like the site is doing some work, possibly maintenance
![image](https://user-images.githubusercontent.com/10355528/225897963-bd3d5fd3-57a1-4805-978c-309aa0ce3bea.png)

Do you know anything about it?

**Comment by Lesmiscore** [comment]
I got a solution for how to calculate the `X-Version` header


Here's the excerpt of the code that sends the request to `https://files.iwara.tv/file/<uuid>?expires=<epoch_timestamp>&hash=<some arbitrary hash>` endpointc
```
return d().wrap((function (e) {
  for (; ; ) switch (e.prev = e.next) {
    case 0:
      return r = new URL(t),
      a = (0, m.O5) (r.search),
      i = r.pathname.split('/'),
      l = null !== (n = i[i.length - 1]) && void 0 !== n ? n : '',
      c(!0),
      e.next = 7,
      (0, m.q4) (l + '_' + a.expires + '_5nFp9kmbNnHdAFhaqMvt');
    case 7:
      return s = e.sent,
      e.next = 10,
      fetch(t, {
        headers: {
          'X-Version': s
        }
      });
```
Where:
- `m.O5` is the function to turn string representation of a query string to a Javascript object, much like `parse_qs` that we use normally in extractors
- `m.q4` is a _complex_ function, looks like this:
```
// this function is assigned as m.q4
function $(t) {
    return D.apply(this, arguments)
}

function D() {
    return (D = (0, r.Z) (l().mark((function t(e) {
        var n,
        r,
        a,
        o;
        return l().wrap((function (t) {
        for (; ; ) switch (t.prev = t.next) {
            case 0:
                return n = (new TextEncoder).encode(e),
                t.next = 3,
                crypto.subtle.digest('SHA-1', n);
            case 3:
                return r = t.sent,
                a = Array.from(new Uint8Array(r)),
                o = a.map((function (t) {
                    return t.toString(16).padStart(2, '0')
                })).join(''),
                t.abrupt('return', o);
            case 7:
            case 'end':
                return t.stop()
        }
        }), t)
    })))).apply(this, arguments)
}
```
It looks it's a complicate, but I know this form of function; transpiled async function
Some of you may notice that it's just calculating a SHA-1 hash, without doing any transformation in byte sequence!

So basically here's how it's calculated:
- Get the `expires` query value from the link
- Get the last component of the path (which is an UUID)
- Concatenate these strings in: `<last component> + '_' + <expires> + '_5nFp9kmbNnHdAFhaqMvt'`
- Calculate the SHA-1 hash of the concatenated string

-------

Let's do this in hand, the example link is `https://files.iwara.tv/file/2d8d2429-734a-4dd3-8000-5bcf6d90b509?expires=1679059459174&hash=64ef070cde730427344d16b27d06f03555d86ea08bd47a6d7a6625ef3ca5a326`
- expires = `1679059459174`
- last component of path = `2d8d2429-734a-4dd3-8000-5bcf6d90b509`
- concatenated string = `2d8d2429-734a-4dd3-8000-5bcf6d90b509_1679059459174_5nFp9kmbNnHdAFhaqMvt`
- hash = `3ccbdb8beebba0bd358e7ef710c875fbf95f5605`

And I can confirm it matches with what's being used as the `X-Version` header:
![image](https://user-images.githubusercontent.com/10355528/225906867-60a29703-0bdd-4f7e-a961-48bed2f16e8e.png)
