### ISSUE TITLE
Kick.com 403 forbidden

### ISSUE THREAD

**Issue by BiRooT** [yt-dlp/yt-dlp#6553]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Hello,

I have a problem recording streams for kick.com site.
I get 403 forbidden error, I tried to curl the site to get the return, I see the following content:
"Kick.com needs to review the security of your connection before proceeding."
I tried to export my cookies in netscape format, add a user-agent but nothing works.
Sometimes it works, but the 403 error comes back very quickly.
I have the same problem with 2 different servers.
Do you have any idea how to get around this ? 

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
$ yt-dlp --cookies kick_cookies.txt --user-agent 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36'  -vU -o `(date +%Y.%m.%d_%H.%M)`.mp4 https://kick.com/roshtein
[debug] Command-line config: ['--cookies', 'kick_cookies.txt', '--user-agent', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36', '-vU', '-o', '2023.03.17_15.25.mp4', 'https://kick.com/roshtein']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (zip)
[debug] Python 3.10.6 (CPython x86_64 64bit) - Linux-5.15.0-67-generic-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2, rtmpdump 2.4
[debug] Optional libraries: certifi-2020.06.20, pycrypto-3.15.0, secretstorage-3.3.1, sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
Current Build Hash: 91cad9f121c1f6f0a81b747415c46ecba0ff331ed38cc6433040b4ac7b6e15ca
yt-dlp is up to date (stable@2023.03.04)
[Kick] Setting up session
ERROR: [Kick] roshtein: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 691, in extract
    self.initialize()
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 600, in initialize
    self._real_initialize()
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/kick.py", line 17, in _real_initialize
    self._request_webpage(HEADRequest('https://kick.com/'), None, 'Setting up session')
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 839, in _request_webpage
    raise ExtractorError(errmsg, cause=err)

  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 821, in _request_webpage
    return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query))
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3742, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/usr/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

**Comment by bashonly** [comment]
Seems like Kick has an IP address blacklist

I cannot reproduce the issue from a residential IP:
```
$ yt-dlp -F 'https://kick.com/roshtein'
[Kick] Setting up session
[Kick] Extracting URL: https://kick.com/roshtein
[Kick] roshtein: Downloading API JSON
[Kick] roshtein: Downloading m3u8 information
[info] Available formats for c54ae-w-with-capital-w-bonus-buy-weekly-buy-bonus-opening-daily-raffles:
ID EXT RESOLUTION FPS │   TBR PROTO │ VCODEC        VBR ACODEC    ABR
─────────────────────────────────────────────────────────────────────
0  mp4 284x160     30 │  230k m3u8  │ avc1.4D401F  230k mp4a.40.2  0k
1  mp4 640x360     30 │  630k m3u8  │ avc1.4D401F  630k mp4a.40.2  0k
2  mp4 852x480     30 │ 1428k m3u8  │ avc1.4D401F 1428k mp4a.40.2  0k
3  mp4 1280x720    60 │ 3423k m3u8  │ avc1.4D401F 3423k mp4a.40.2  0k
4  mp4 1920x1080   60 │ 8049k m3u8  │ avc1.64002A 8049k mp4a.40.2  0k
```

If you are also being blocked when requesting via curl this does not seem like an issue specific to yt-dlp and I'm not sure what we can do.

**Comment by Pentaphon** [comment]
Website works but yt-dlp gets 403'd with the latest nightly.

**Comment by bashonly** [comment]
```bash
< Location: https://kick.com/
< Set-Cookie: __cf_bm=65Uxy7fjdsu46KgBN1QSqZX.tQjWkOsxjAerjMKK0go-1680375571-0-AVVx+ypOfj6SDAX4xtjL/J5755+Tlw45QfVrve8BksCZ2qEWpL/pIfRv1gExEm72W6h8PPvv4g0Ow2FFW2o1plE=; path=/; expires=Sat, 01-Apr-23 19:29:31 GMT; domain=.kick.com; HttpOnly; SameSite=None
< Server: cloudflare
```
It looks like Kick may be selectively applying cloudflare fingerprinting to certain IP ranges (which is why website loads in browser but not with yt-dlp), and in that case there is nothing we can do currently. Also, I still can't reproduce the 403 response

**Comment by FruitCo** [comment]
> @BiRooT @nikitalocalhost @pukkandan Website works but yt-dlp gets 403'd with the latest nightly.
> 
> However, you can still download the VOD by getting the master m3u8 and plugging that into yt-dlp as described in this video guide.
> 
> https://streamable.com/xbel1y

This is happening again with stable and nightly. Did not know about this method, I learned something and fixed my issue! Thanks!

**Comment by pukkandan** [comment]
See #6748
