### ISSUE TITLE
`--trim-filenames` does not work with custom filename `-o`

### ISSUE THREAD

**Issue by AlttiRi** [yt-dlp/yt-dlp#6554]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

`--trim-filenames` does not work with custom filenames — when I use `-o` option.

I just want to use `--trim-filenames 240` in order to my custom filename works fine on sites with unlimited `fulltitle` (reddit, tiktok).

---

For example for `https://www.youtube.com/watch?v=9NUbUWF_6iw` with `--trim-filenames 100` I expect the follow name:
```
[youtube.com] Keendify—2021.01.30—9NUbUWF_6iw—This amazing video has the longest title in all of.mp4
```
but it produces the unlimited one:
```
[youtube.com] Keendify—2021.01.30—9NUbUWF_6iw—This amazing video has the longest title in all of youtube I think!It is 100 characters long!!!!!!!!.mp4
```

---
_My `.bashrc` aliases (with `240` chars limit):_
```bash
alias yt='yt-dlp --trim-filenames 240 --write-thumbnail --write-description \
-o "[%(webpage_url_domain)s] %(uploader,creator,playlist_title)s—%(upload_date>%Y.%m.%d)s—%(id)s—%(fulltitle|)s.%(ext)s" \
-o "pl_thumbnail:[%(webpage_url_domain)s][thumbnail] %(uploader,creator,playlist_title)s—%(upload_date>%Y.%m.%d)s—%(playlist_id,id)s—%(fulltitle|)s.%(ext)s"'
alias ytf='yt -F '
```

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
$ yt https://www.youtube.com/watch?v=9NUbUWF_6iw -vU

[debug] Command-line config: ['--trim-filenames', '100', '--write-thumbnail', '--write-description', '-o', '[%(webpage_url_domain)s] %(uploader,creator,playlist_title)s—%(upload_date>%Y.%m.%d)s—%(id)s—%(fulltitle|)s.%(ext)s', '-o', 'pl_thumbnail:[%(webpage_url_domain)s][thumbnail] %(uploader,creator,playlist_title)s—%(upload_date>%Y.%m.%d)s—%(playlist_id,id)s—%(fulltitle|)s.%(ext)s', 'https://www.youtube.com/watch?v=9NUbUWF_6iw', '-vU']

[debug] yt-dlp version stable@2023.03.04 [392389b7d]

[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
yt-dlp is up to date (stable@2023.03.04)

[youtube] Extracting URL: https://www.youtube.com/watch?v=9NUbUWF_6iw

[info] Writing video description to: [youtube.com] Keendify—2021.01.30—9NUbUWF_6iw—This amazing video has the longest title in all of youtube I think!It is 100 characters long!!!!!!!!.description

[info] Writing video thumbnail 37 to: [youtube.com] Keendify—2021.01.30—9NUbUWF_6iw—This amazing video has the longest title in all of youtube I think!It is 100 characters long!!!!!!!!.webp

[download] Destination: [youtube.com] Keendify—2021.01.30—9NUbUWF_6iw—This amazing video has the longest title in all of youtube I think!It is 100 characters long!!!!!!!!.mp4
```

**Comment by AlttiRi** [comment]
Although, _in my case_ I just can use `%(fulltitle.:180|)s` instead of `%(fulltitle|)s`. [*](https://github.com/yt-dlp/yt-dlp#output-template)

However, `--trim-filenames` should work too, I think.

**Comment by october262** [comment]
try again with yt-dlp -o '%(title).20s' "https://www.youtube.com/watch?v=9NUbUWF_6iw"

**Comment by pukkandan** [comment]
https://github.com/yt-dlp/yt-dlp/issues/2314

**Comment by AlttiRi** [comment]
> #2314

The linked issue is closed to comment.

---

For me, it seems to be OK if `--trim-filenames` will work the follow way with `-o`:
- if `-o` ends with `.ext` trim the filename with keeping the `.ext`,
- in other case just trim the filename with no extra logic.

Something like this JS example code:
```js
function get_trimmed_filename(filename, limit, ext) {
    const ends_with_ext = filename.endsWith("." + ext);
    const end_length = ext ? ext.length + 1 : 0;
    if (ends_with_ext) {
        limit = limit - end_length;
    }
    if (limit < 0) {
        limit = 255 - end_length;
    }
    if (ends_with_ext) {
        return filename.slice(0, limit) + "." + ext;
    }
    return filename.slice(0, limit);
}


const filename = `[youtube.com] Keendify—2021.01.30—9NUbUWF_6iw—This amazing video has the longest title in all of `
               + `youtube I think!It is 100 characters long!!!!!!!!.mp4`;
const filename_trimmed = get_trimmed_filename(filename, 80, "mp4");
console.log(filename_trimmed);

```

---

BTW, there is no file system with allowed filename length is more than 255 chars, or bytes, see [`Comparison of filename limitations` table](https://en.wikipedia.org/wiki/Filename)
