### ISSUE TITLE
--progress-template shows "N/A" for  value of "%(progress._total_bytes_str)s"

### ISSUE THREAD

**Issue by mhogomchungu** [yt-dlp/yt-dlp#6555]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

When downloading, i use a template argument of ```"--progress-template" "download:[download] %(progress._percent_str)s of %(progress._total_bytes_str)s at %(progress._speed_str)s ETA %(progress._eta_str)s"``` and the value for ```%(progress._percent_str)s``` shows up as "N/A" instead of the expected value. The value shows up correctly when downloading without using the progress template.

Below output also shows there are extra space characters added to the template output.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
"yt-dlp" --newline -Uv -f worstaudio "--progress-template" "download:[download] %(progress._percent_str)s of %(progress._total_bytes_str)s at %(progress._speed_str)s ETA %(progress._eta_str)s" "https://www.youtube.com/watch?v=gutG3m6OTJY"
[debug] Command-line config: ['--newline', '-Uv', '-f', 'worstaudio', '--progress-template', 'download:[download] %(progress._percent_str)s of %(progress._total_bytes_str)s at %(progress._speed_str)s ETA %(progress._eta_str)s', 'https://www.youtube.com/watch?v=gutG3m6OTJY']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (zip)
[debug] Python 3.10.8 (CPython x86_64 64bit) - Linux-6.0.14-pclos1-x86_64-with-glibc2.36 (OpenSSL 1.1.1t  7 Feb 2023, glibc 2.36)
[debug] exe versions: ffmpeg 4.4.1 (fdk,setts), ffprobe 4.4.1
[debug] Optional libraries: Cryptodome-3.14.1, brotli-1.0.7, certifi-2021.10.08, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.1
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
Current Build Hash: 91cad9f121c1f6f0a81b747415c46ecba0ff331ed38cc6433040b4ac7b6e15ca
yt-dlp is up to date (stable@2023.03.04)
[youtube] Extracting URL: https://www.youtube.com/watch?v=gutG3m6OTJY
[youtube] gutG3m6OTJY: Downloading webpage
[youtube] gutG3m6OTJY: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[info] gutG3m6OTJY: Downloading 1 format(s): 599
[debug] Invoking dashsegments downloader on "https://rr1---sn-8vq5jvhu1-q5ge.googlevideo.com/videoplayback?expire=1679089192&ei=yIkUZMz-EITh1gaOuouoCg&ip=197.250.227.5&id=o-AP-5uGOxxJRx8d4yfcLyzUiTTJAqGqjq6qV_ntk9tbZ0&itag=599&source=youtube&requiressl=yes&mh=Rg&mm=31%2C29&mn=sn-8vq5jvhu1-q5ge%2Csn-woc7ln7y&ms=au%2Crdu&mv=m&mvi=1&pl=18&initcwndbps=161250&spc=H3gIhvyfaTZkd6EId8xMDlqIc5PivT8&vprv=1&svpuc=1&mime=audio%2Fmp4&gir=yes&clen=168100&dur=43.421&lmt=1679028794692189&mt=1679067178&fvip=2&keepalive=yes&fexp=24007246&c=ANDROID&txp=6318224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRgIhAMahJs-KmEhArL3IdHMC4n6x7YcjzgKBX46yoFFQsm0fAiEA3kZzg4cOQqIVgCdwln20cO_xLA826XHhQ23cwlzyEbs%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAMjjJPSQAii3b6ULfmegHsy6YNhxb2Hwy2yECPFfYid-AiEA4sK_M7_CcxGcksc3o0OqApMcmDLMiO5oYMfRXVTi6qw%3D"
[dashsegments] Total fragments: 1
[download] Destination: Markelle Fultz unties Terrence Ross' shoelace before late-game free throws ｜ NBA on ESPN [gutG3m6OTJY].m4a
[download]   0.6% of        N/A at    626.52B/s ETA 04:26
[download]   1.8% of        N/A at    1.83KiB/s ETA 01:27
[download]   4.3% of        N/A at    4.27KiB/s ETA 00:36
[download]   9.1% of        N/A at    9.15KiB/s ETA 00:16
[download]  18.9% of        N/A at   18.12KiB/s ETA 00:07
[download]  38.4% of        N/A at   33.87KiB/s ETA 00:02
[download]  77.4% of        N/A at   65.08KiB/s ETA 00:00
[download] 100.0% of        N/A at   82.98KiB/s ETA 00:00
[download] 100.0% of        N/A at   82.88KiB/s ETA 00:00
[download] 100.0% of  164.16KiB at 82.64KiB/s ETA NA
[FixupM4a] Correcting container of "Markelle Fultz unties Terrence Ross' shoelace before late-game free throws ｜ NBA on ESPN [gutG3m6OTJY].m4a"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:Markelle Fultz unties Terrence Ross'"'"' shoelace before late-game free throws ｜ NBA on ESPN [gutG3m6OTJY].m4a' -map 0 -dn -ignore_unknown -c copy -f mp4 -movflags +faststart 'file:Markelle Fultz unties Terrence Ross'"'"' shoelace before late-game free throws ｜ NBA on ESPN [gutG3m6OTJY].temp.m4a'
```

**Comment by Grub4K** [comment]
`_<name>_str` is an internal value, prepared with color formatting and padding. To get the raw, unformatted values without padding use just `<name>` (in this case `total_size`). What exactly do you consider a bug with this behavior? Why do you want unpadded output specifically?

Additionally the total size may not be known in advance, which is where `total_size_estimate` comes in. It contains a rough estimation of the expected size calculated from parts in advance. Since its an estimate it might not be accurate and can change while downloading. The default template chooses between those and falls back to the estimate, which is why the default template works in this case but yours does not.

Hope this cleared up the confusion.

**Comment by mhogomchungu** [comment]
I was introduced to available options of --progress-template [here](https://www.reddit.com/r/youtubedl/comments/r61y4c/ytdlp_release_20211201/hn6vxg7/) and [this](https://github.com/yt-dlp/yt-dlp/issues/1170#issuecomment-938202905) link shows there was no padding at some point in the past.

Looking again at available options and i see there is another field named "_total_bytes_estimate_str" in addition to "_total_bytes_str".

It makes sense now and i need to monitor for both of these options before deciding which one to use.

**Comment by pukkandan** [comment]
I'm still curious why you don't use `%(total_bytes,total_bytes_estimate)s` and use the _str version sinstead

**Comment by mhogomchungu** [comment]
Because they do not require local processing to make the output human readable and similar to what is produced by yt-dlp.

Will switch to those values without _str and convert them locally.
