### ISSUE TITLE
yt-dlp wont download youtube videos from certain channels

### ISSUE THREAD

**Issue by mrbobo509** [yt-dlp/yt-dlp#6556]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that a **supported** site is broken
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Provide a description that is worded well enough to be understood

right now its not accepting any videos from napalm records. not sure if its a copyright thing or something else

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU']
[debug] User config "C:\Users\09515\AppData\Roaming\yt-dlp\config.txt": ['-x', '--audio-format', 'mp3', '-o', 'E:/download/%(uploader)s/%(playlist)s/%(title)s.%(ext)s', '--no-mtime', '--add-metadata', '--embed-thumbnail', '--batch-file', 'list.txt', '-i', '--parse-metadata', 'playlist_title:(?s)(?P<album>.+)']
[debug] Batch file urls: ['https://www.youtube.com/watch?v=cJ5XN2P4oCI&list=OLAK5uy_nMSCzd00JUPIlSxFybgzkabo-Z1pxfYWE&index=1']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2023.01.02 [d83b0ad80]
[debug] Lazy loading extractors is disabled
[debug] Python 3.9.5 (CPython AMD64 64bit) - Windows-10-10.0.22621-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-101865-g3e16d1c8a6 (setts), ffprobe N-101865-g3e16d1c8a6
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1754 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: 2023.03.04, Current version: 2023.01.02
[debug] Downloading _update_spec from https://github.com/yt-dlp/yt-dlp/releases/download/2023.03.04/_update_spec
ERROR: You installed yt-dlp with a package manager or setup.py; Use that to update
[youtube:tab] Extracting URL: https://www.youtube.com/watch?v=cJ5XN2P4oCI&list=OLAK5uy_nMSCzd00JUPIlSxFybgzkabo-Z1pxfYWE&index=1
[youtube:tab] Downloading playlist OLAK5uy_nMSCzd00JUPIlSxFybgzkabo-Z1pxfYWE - add --no-playlist to download just the video cJ5XN2P4oCI
[youtube:tab] OLAK5uy_nMSCzd00JUPIlSxFybgzkabo-Z1pxfYWE: Downloading webpage
[youtube:tab] Extracting URL: https://www.youtube.com/playlist?list=OLAK5uy_nMSCzd00JUPIlSxFybgzkabo-Z1pxfYWE
[youtube:tab] OLAK5uy_nMSCzd00JUPIlSxFybgzkabo-Z1pxfYWE: Downloading webpage
[youtube:tab] OLAK5uy_nMSCzd00JUPIlSxFybgzkabo-Z1pxfYWE: Redownloading playlist API JSON with unavailable videos
[download] Downloading playlist: Fly Away
[debug] Skipping writing playlist thumbnail
[youtube:tab] Playlist Fly Away: Downloading 1 items of 1
[download] Downloading item 1 of 1
[youtube] Extracting URL: https://www.youtube.com/watch?v=cJ5XN2P4oCI
[youtube] cJ5XN2P4oCI: Downloading webpage
[youtube] cJ5XN2P4oCI: Downloading android player API JSON
ERROR: [youtube] cJ5XN2P4oCI: Unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "E:\programs\yt_dlp\extractor\common.py", line 680, in extract
    ie_result = self._real_extract(url)
  File "E:\programs\yt_dlp\extractor\youtube.py", line 4048, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "E:\programs\yt_dlp\extractor\common.py", line 1228, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)

[download] Finished downloading playlist: Fly Away
```

**Comment by Lesmiscore** [comment]
> [x] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)

> `[debug] yt-dlp version 2023.01.02 [d83b0ad80]`

You're running old yt-dlp, update it

**Comment by TheSnoozer** [comment]
Bumped into the same issue with ```yt-dlp version 2023.01.06 [6becd25] (pip)```.

Please note that a ``` yt-dlp -U```
could also fail with:
```
Latest version: 2023.03.04, Current version: 2023.01.06
ERROR: You installed yt-dlp with pip or using the wheel from PyPi; Use that to update
```

in the above error log you can also see a similar problem:
```
ERROR: You installed yt-dlp with a package manager or setup.py; Use that to update
```

In my case using ```python -m pip install -U yt-dlp``` helped in my case to install `2023.1.6` and fixed the issue for me.

Perhaps this error message should be fatal (maybe it is already in newer versions?) instead of silently ignoring it.

**Comment by JackDinn** [comment]
same error but i am up to date?

how do i update other than pacman -S yt-dlp as i use manjaro?

according to pacman its already up to date

```
❱yay -S yt-dlp
[sudo] password for greg:
warning: yt-dlp-2023.01.06-1 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...

Packages (1) yt-dlp-2023.01.06-1

Total Installed Size:  21.56 MiB
Net Upgrade Size:       0.00 MiB
```

**Comment by TheSnoozer** [comment]
```
Latest version: 2023.03.04, Current version: 2023.01.06
```
so no `2023.01.06` is not the latest.

**Comment by JackDinn** [comment]
Well, i don't know then. I tried `aur/yt-dlp-git 2023.03.03.r6.g283a0b5bc-1` but i get a whole wall/page of Haskell dependencies, hundreds of them. I'm not going down that road.
I suppose i have to wait for manajro/arch sources to update themselves :(
 
Ok well thx for the reply.

**Comment by seproDev** [comment]
@JackDinn You can use the binary or pip release instead. See: https://github.com/yt-dlp/yt-dlp/wiki/FAQ#the-yt-dlp-in-my-package-manager-is-outdatedbroken

**Comment by JackDinn** [comment]
Great, the binary works and will do until there is an update. 

So many package managers that im going to make a mess of my system sooner or later ^^ so i shall stick with pacman as much as possible.

Thank you :smile:

**Comment by rijotech** [comment]
Yep, I'm facing the same problem.

**Comment by Lesmiscore** [comment]
Update, update, update!
