### ISSUE TITLE
yt-dlp not detecting subtitles from an MPD

### ISSUE THREAD

**Issue by VXsz** [yt-dlp/yt-dlp#656]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running yt-dlp version **2021.08.02**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
[debug] Command-line config: ['-v', '--allow-unplayable-formats', '--list-subs', 'https://cdxaws-ak.akamaized.net/out/v1/f10734629e3b4e8c8864c2b56b0821ba/c96d37fedb44465f8a19c65563004303/2702b4dd304c43e88bcfa4f04f464736/manifest.mpd?aws.manifestfilter=video_height:144-1080']
[debug] Encodings: locale cp1256, fs utf-8, out utf-8, pref cp1256
[debug] yt-dlp version 2021.08.02 (exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19042-SP0
[debug] exe versions: none
[debug] Proxy map: {}
[debug] [generic] Extracting URL: https://cdxaws-ak.akamaized.net/out/v1/f10734629e3b4e8c8864c2b56b0821ba/c96d37fedb44465f8a19c65563004303/2702b4dd304c43e88bcfa4f04f464736/manifest.mpd?aws.manifestfilter=video_height:144-1080
[generic] manifest.mpd?aws: Requesting header
WARNING: [generic] Falling back on generic information extractor.
[generic] manifest.mpd?aws: Downloading webpage
[generic] manifest.mpd?aws: Extracting information
WARNING: [generic] Unknown MIME type application/mp4 in DASH manifest
WARNING: [generic] Unknown MIME type application/mp4 in DASH manifest
WARNING: [generic] Unknown MIME type application/mp4 in DASH manifest
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
manifest.mpd?aws has no subtitles
```

## Description

yt-dlp works nicely with the video & audio of this MPD (taken from Shahid-VIP show): https://cdxaws-ak.akamaized.net/out/v1/f10734629e3b4e8c8864c2b56b0821ba/c96d37fedb44465f8a19c65563004303/2702b4dd304c43e88bcfa4f04f464736/manifest.mpd?aws.manifestfilter=video_height:144-1080, but as for subtitles, it doesn't seem to detect them and always throws this error `manifest.mpd?aws has no subtitles`, I tried everything but I couldn't really grab them using this tool (**_or any other tool_**), I scoured the web and looked everywhere to automatically (and reliably) download the segmented subtitles but couldn't find a single way other than downloading each segment with a hacky python script and merging them (which is really unreliable and I'm not really that good with coding, also veryy slow) so this is my last hope to rip the subtitle, any help is appreciated & let me know if you need more info

BTW, I looked for the other open & locked issues but found non that are similar to this problem

**Comment by pukkandan** [comment]
The URL you have given is DRM protected

But even that aside, I don't think it is possible to detect the AdaptationSet as a subtitle

```xml
    <AdaptationSet mimeType="application/mp4" codecs="stpp" segmentAlignment="true" startWithSAP="1" bitstreamSwitching="true" lang="fr">
      <Label>fr</Label>
      <Representation id="12" bandwidth="0">
        <SegmentTemplate timescale="90000" media="../b7de9dd3b6ec4869a4bbf06b3e6b64f2/4c04893927dd4a5693635b46b6558c3d/index_subtitles_12_0_$Number$.mp4" initialization="../b7de9dd3b6ec4869a4bbf06b3e6b64f2/4c04893927dd4a5693635b46b6558c3d/index_subtitles_12_0_init.mp4" startNumber="1" presentationTimeOffset="0">
          <SegmentTimeline>
            <S t="3000" d="540000" r="229"/>
            <S t="124203000" d="140400"/>
          </SegmentTimeline>
        </SegmentTemplate>
      </Representation>
    </AdaptationSet>
```

`application/mp4` does not have to be subtitle according to [rfc4337.2](https://datatracker.ietf.org/doc/html/rfc4337#section-2) and as such I an wary of treating it as such without more information - especially if this happens only inside DRM encumbered manifests. If you can provide a non-DRM example where this happens, then we can consider it.

@fstirlitz, what so u think?

**Comment by VXsz** [comment]
> The URL you have given is DRM protected
> 
> But even that aside, I don't think it is possible to detect the AdaptationSet as a subtitle
> 
> ```
>     <AdaptationSet mimeType="application/mp4" codecs="stpp" segmentAlignment="true" startWithSAP="1" bitstreamSwitching="true" lang="fr">
>       <Label>fr</Label>
>       <Representation id="12" bandwidth="0">
>         <SegmentTemplate timescale="90000" media="../b7de9dd3b6ec4869a4bbf06b3e6b64f2/4c04893927dd4a5693635b46b6558c3d/index_subtitles_12_0_$Number$.mp4" initialization="../b7de9dd3b6ec4869a4bbf06b3e6b64f2/4c04893927dd4a5693635b46b6558c3d/index_subtitles_12_0_init.mp4" startNumber="1" presentationTimeOffset="0">
>           <SegmentTimeline>
>             <S t="3000" d="540000" r="229"/>
>             <S t="124203000" d="140400"/>
>           </SegmentTimeline>
>         </SegmentTemplate>
>       </Representation>
>     </AdaptationSet>
> ```
> 
> `application/mp4` does not have to be subtitle according to [rfc4337.2](https://datatracker.ietf.org/doc/html/rfc4337#section-2) and so I an wary of treating it as one without more information - especially if this happens only inside DRM encumbered manifests. If you can provide a non-DRM example where this happens, then we can consider it.
> 
> @fstirlitz, what so u think?

Only place where I had this issue is on Shahid sadly, I've downloaded the subtitle and merged it (through a hacky way which was painful) but couldn't figure out what format it even is, MediaInfo shows `codec = stpp` which I think is related to this doc from apple : https://developer.apple.com/documentation/http_live_streaming/hls_authoring_specification_for_apple_devices section 5.10, 

Anyways since it's maybe TTML I thought about using ttml2srt tools but they are crash saying the XML isn't well formed or something, I already spent days looking (waking up and sleeping on it) and trying everything, even making sure if there is a URL from shahid which gives the a full .vtt subtitle file, but to no avail


is it okay if I attach my downloaded subtitle file? so you see what's going on their since it's maybe corrupt due to the downloading method
Maybe fstirlitz could help identify the issue, looking forward to this ❤

**Comment by pukkandan** [comment]
The subs inside dash is ttml, but packed in mp4. See https://github.com/yt-dlp/yt-dlp/issues/631#issuecomment-893329480

**Comment by VXsz** [comment]
> The subs inside dash is ttml, but packed in mp4. See [#631 (comment)](https://github.com/yt-dlp/yt-dlp/issues/631#issuecomment-893329480), #247, [be6202f](https://github.com/yt-dlp/yt-dlp/commit/be6202f12b97858b9d716e608394b51065d0419f)

but with that being said, why won't any converter accept the file? they either crash or reject it

Also in that case, can I force yt-dlp to download the subs even tho it's thinking they are mp4? perhaps that way I can make sure it's downloaded correctly (which is why I opened the issue)

**Comment by pukkandan** [comment]
See https://github.com/yt-dlp/yt-dlp/commit/be6202f12b97858b9d716e608394b51065d0419f

```
* The fragmented TTML subtitles extracted from DASH/ISM are valid, but are unsupported by `ffmpeg` and most video players
    * Their XML fragments can be dumped using `ffmpeg -i in.mp4 -f data -map 0 -c copy out.ttml`.
        Once the unnecessary headers are stripped out of this, it becomes a valid self-contained ttml file
    * The ttml subs downloaded from DASH manifests can also be directly opened with <@SubtitleEdit>
```

**Comment by VXsz** [comment]
> See [be6202f](https://github.com/yt-dlp/yt-dlp/commit/be6202f12b97858b9d716e608394b51065d0419f)
> 
> ```
> * The fragmented TTML subtitles extracted from DASH/ISM are valid, but are unsupported by `ffmpeg` and most video players
>     * Their XML fragments can be dumped using `ffmpeg -i in.mp4 -f data -map 0 -c copy out.ttml`.
>         Once the unnecessary headers are stripped out of this, it becomes a valid self-contained ttml file
>     * The ttml subs downloaded from DASH manifests can also be directly opened with <@SubtitleEdit>
> ```

I see, I will look into that & understand the command parameters so I can play with it and get a better idea, hopefully it works, thanks for the help so far

**Comment by VXsz** [comment]
I tried and searched around using ffmpeg but it seems it can only see actual video streams, it doesn't see any of the subtitles streams so I can't dump the subtitles (maybe I'm missing something?)

**Comment by fstirlitz** [comment]
`codecs="stpp"` pretty unambiguously indicates a subtitle. Although IIRC `stpp` is not exactly a codec in itself, just an MP4 box type in which subtitle codec metadata is to be found. Compare:

<https://github.com/yt-dlp/yt-dlp/blob/b6a35ad83bbe2cbb9cda17052fd68e2dff16e99b/yt_dlp/downloader/ism.py#L175-L180>

I guess `stpp` means XML-based subtitles; I think knowing that it’s specifically TTML requires looking at the namespace in the `stpp` box. Is there a spec somewhere that explains what `codecs=` is supposed to contain?

> I tried and searched around using ffmpeg but it seems it can only see actual video streams, it doesn't see any of the subtitles streams so I can't dump the subtitles (maybe I'm missing something?)

You need to download all the fragments and concatenate them into a standalone file first (like the downloader ordinarily would). And FFmpeg doesn’t support TTML decoding anyway, it will only indicate the presence of a ‘data’ stream from which you can extract XML segments and then combine them into a stand-alone `.ttml` file, manually or with another tool. Alternatively, you can try opening the concatenated MP4 file with SubtitleEdit, but #631 indicates the timestamps will be likely misread.

**Comment by fstirlitz** [comment]
Okay, the link to the DASH spec in our source code is dead now. (Fuck ISO.)

The closest thing to an authoritative reference I found is <https://dvb.org/wp-content/uploads/2019/10/a168_DVB_MPEG-DASH_Nov_2017.pdf>, page 42:

> The <span>@</span>codecs attribute shall begin with 'stpp' to indicate the use of XML subtitles. The attribute should indicate the profile according to the W3C TTML profile registry [i.4]. If 'stpp' alone is used, with no profile specified, 'stpp.ttml.etd1' shall be assumed, for backwards compatibility.

This describes a profile of DASH for IPTV by the DVB forum, but I doubt it outright contradicts the main specification. It pretty much confirms my guess above.

**Comment by pukkandan** [comment]
Thanks, I wasn't able to find any specs explaining sttp and so though it would be ambigious as well.

Does this mean we should relax the subtitle detection to include `sttp` and assume it is ttml unless specified otherwise?

**Comment by fstirlitz** [comment]
As a quick-and-dirty hack,

```
codecs = representation_attrib.get('codecs')
if codecs == 'stpp' or codecs.startswith('stpp.'):
    content_type = 'text'
```

in `_parse_mpd_formats_and_subtitles` should be enough. More long-term, the `codecs=` attribute is later parsed with `parse_codecs` from `utils`, so we may just move this earlier, infer media stream type from the result as a fallback, and generalise it to cover subtitle codecs too.

**Comment by Essam3152** [comment]
@VXsz https://pastebin.com/kheWNHqC

**Comment by dirkf** [comment]
> Okay, the link to the DASH spec in our source code is dead now. (Fuck ISO.)
> ...
Actually, only fuck ISO slightly.

The standard was updated: https://standards.iso.org/ittf/PubliclyAvailableStandards/c079329_ISO_IEC_23009-1_2019(E).zip

For the latest version of any of the PAS, search at https://standards.iso.org/ittf/PubliclyAvailableStandards/
