### ISSUE TITLE
cbsnews.com Most canged something in the last 7 days.

### ISSUE THREAD

**Issue by michaelcrossland1979** [yt-dlp/yt-dlp#6565]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that a **supported** site is broken
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

USA

### Provide a description that is worded well enough to be understood

I went to cbsnews.com to try to get the latest 48 Hours from there because CBS .com has paid walled there CBS site for 48 Hours.
And I was  greeted by this.
![Screenshot 2023-03-19 132953](https://user-images.githubusercontent.com/43523698/226199184-807378b6-5d0e-4f0b-a289-9c049a398011.png)
As you can see I did try other shows as will and each one them does the something but yet if I goto them in Firefox or google chrome I's able to load and play the videos. So have no clue what CBS has done to the site in the last 7 days because last Sunday it worked just fine. Now I'll be forced to have to use PlayOn to screen recoad those shows. I hope that this can be figured out and fix done for it. I just wish I was better at Python coding, otherwise I would try to see if I could make a patch.
![Screenshot 2023-03-19 132953](https://user-images.githubusercontent.com/43523698/226199760-2a5c923a-1dcc-4a03-81be-5396a15f2526.png)
![Screenshot 2023-03-19 134212](https://user-images.githubusercontent.com/43523698/226199761-f94024a0-8daf-4857-b6b5-10920e3b17b0.png)
![Screenshot 2023-03-19 134400](https://user-images.githubusercontent.com/43523698/226199762-cd687a48-804a-4caa-9962-c75d5dd437de.png)
Sorry my bad about adding those last did not see the part about running it with that -uV command.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
C:\Users\micha\Downloads>yt-dlp.exe -vU https://www.cbsnews.com/video/319-costa-warren-mchenry/
[debug] Command-line config: ['-vU', 'https://www.cbsnews.com/video/319-costa-warren-mchenry/']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22621-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-100610-gb381903178-ga0acc44106 (fdk), ffprobe N-92043-g0f36ad514c
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
Current Build Hash: 5590c57bd0433ed239a2deaaf92e2ad6f37fe50f53664c821575cafe106a9421
yt-dlp is up to date (stable@2023.03.04)
[cbsnews] Extracting URL: https://www.cbsnews.com/video/319-costa-warren-mchenry/
[cbsnews] 319-costa-warren-mchenry: Downloading webpage
[cbsnews] ygTig8PoQvtUrMOEWwhnVefn0tAJbTRj: Downloading XML
ERROR: [cbsnews] 319-costa-warren-mchenry: ygTig8PoQvtUrMOEWwhnVefn0tAJbTRj: Failed to parse XML (caused by ParseError('no element found: line 1, column 0')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 694, in extract
  File "yt_dlp\extractor\cbsnews.py", line 105, in _real_extract
  File "yt_dlp\extractor\cbs.py", line 123, in _extract_video_info
  File "yt_dlp\extractor\common.py", line 1048, in download_content
  File "yt_dlp\extractor\common.py", line 1018, in download_handle
  File "yt_dlp\extractor\common.py", line 1008, in parse
  File "yt_dlp\extractor\common.py", line 988, in _parse_xml
  File "yt_dlp\extractor\common.py", line 978, in __print_error

  File "yt_dlp\extractor\common.py", line 986, in _parse_xml
  File "yt_dlp\compat\__init__.py", line 27, in compat_etree_fromstring
  File "xml\etree\ElementTree.py", line 1321, in XML
xml.etree.ElementTree.ParseError: no element found: line 1, column 0


C:\Users\micha\Downloads>
```

**Comment by bashonly** [comment]
As a workaround for now you can add `--force-generic` to your command

**Comment by michaelcrossland1979** [comment]
Okay thank you for that work around I'll see if it will work for me and get
back with anything else that might show up.

**Comment by michaelcrossland1979** [comment]
Just a follow up your work around does work thank you very much.

**Comment by bonacker1** [comment]
Thanks a lot! The workaround worked for me too, but just out of curiousity if the generic extractor works for CBS News, why is there a specific extractor for it? What's the advantage of a special extractor?

Now I'll automatically try the generic extractor when something fails, so this may help in the future with other sites as well.

**Comment by bashonly** [comment]
cbsnews redesigned their website sometime last year and now the m3u8 URL is almost always present in the JSON LD in each page. This was not the case before the redesign, thus the dedicated extractor was necessary

**Comment by kpuc** [comment]
Greetings.
This workaround doesn't seem to work for CBSs' 60 Minutes:
[generic] Extracting URL: https://www.cbs.com/shows/video/AaCrJBUb9IjGfGNwtwTY0HiUfI9JZW5c/
[generic] AaCrJBUb9IjGfGNwtwTY0HiUfI9JZW5c: Downloading webpage
WARNING: [generic] Forcing generic information extractor
[generic] AaCrJBUb9IjGfGNwtwTY0HiUfI9JZW5c: Extracting information
ERROR: Unsupported URL: https://www.cbs.com/shows/video/AaCrJBUb9IjGfGNwtwTY0HiUfI9JZW5c/
child exited with value 1

**Comment by bashonly** [comment]
the workaround is for cbsnews.com not cbs.com

**Comment by kpuc** [comment]
D'oh!  Perhaps I assumed they would function the same.

In that case, I get the same "failed to parse XML" error as above with https://www.cbs.com/shows/video/AaCrJBUb9IjGfGNwtwTY0HiUfI9JZW5c/ without using --force-generic, and using --force-generic doesn't help. :/

**Comment by michaelcrossland1979** [comment]
Yeah I got that same thing on there just didn't add it to it seeing as if
one there sites are acting up then more then likely once they got around to
trying to figure out how to fix they would also check cbs.com as well. But
just to let you know cbs.com has pay walled 60 minutes and 48 hours over on
cbs.com almost 6 to 12 months ago now. And as far as I am aware there
Paramount Plus login stuff doesn't use the Adobe authenticator stuff like
so many other sites us they use there own hom brewed one. That's why if you
get a plus subscription on say Amazon video or throw Google TV or Roku you
can only access Paramount Plus through that platform only.

**Comment by tsrmoz** [comment]
The workaround works for me too, but subtitles are no longer downloadable after this issue started in the week of March 13. Now `--list-subs` returns "no subtitles" even though subtitle is there on the site video. Any idea?

**Comment by clocke125** [comment]
The work around only partially worked for me it gave me video only

clocke125@expirion:~$ yt-dlp -F https://www.cbsnews.com/video/sunday-morning-full-episode-3-26-2023/#x

[cbsnews] Extracting URL: https://www.cbsnews.com/video/sunday-morning-full-episode-3-26-2023/#x
[cbsnews] sunday-morning-full-episode-3-26-2023: Downloading webpage
[cbsnews] koz9MU_KlvU3mnhOKQH8JsW5KYCKf9X3: Downloading XML
ERROR: [cbsnews] sunday-morning-full-episode-3-26-2023: koz9MU_KlvU3mnhOKQH8JsW5KYCKf9X3: Failed to parse XML (caused by ParseError('no element found: line 1, column 0')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

clocke125@expirion:~$ yt-dlp -F --force-generic https://www.cbsnews.com/video/sunday-morning-full-episode-3-26-2023/#x

[generic] Extracting URL: https://www.cbsnews.com/video/sunday-morning-full-episode-3-26-2023/#x
[generic] #x: Downloading webpage
WARNING: [generic] Forcing generic information extractor
[generic] #x: Extracting information
[generic] Extracting URL: https://prod.vodvideo.cbsnews.com/cbsnews/vr/hls/2023/03/14/2182070851575/1828850_hls/master.m3u8...2023%2F%23x%22%7D%7D
[generic] #x: Downloading webpage
[generic] #x: Downloading m3u8 information
[info] Available formats for #x:
ID                EXT RESOLUTION FPS │    FILESIZE   TBR PROTO │ VCODEC        VBR ACODEC     MORE INFO
─────────────────────────────────────────────────────────────────────────────────────────────────────────────
audio_aac-English mp4 audio only     │                   m3u8  │ audio only        unknown    [en-US] English
517               mp4 640x360     30 │ ~ 237.11MiB  517k m3u8  │ avc1.640028  517k video only
886               mp4 768x432     30 │ ~ 406.69MiB  887k m3u8  │ avc1.640028  887k video only
1630              mp4 960x540     30 │ ~ 747.93MiB 1631k m3u8  │ avc1.640028 1631k video only
2230              mp4 1280x720    30 │ ~1023.14MiB 2231k m3u8  │ avc1.640028 2231k video only
3087              mp4 1920x1080   30 │ ~   1.38GiB 3087k m3u8  │ avc1.640028 3087k video only

clocke125@expirion:~$

**Comment by bashonly** [comment]
@clocke125 the first format listed is the audio format

the m3u8 that generic extracts is the same m3u8 that the site uses for playback

**Comment by michaelcrossland1979** [comment]
That is normal when you look at the information that's why at the end of
the download it says that it's doing some extra stuff. One those things is
taking and time matching the audio that it downloaded with the video so
that everyone matches up. You see that on YouTube and a whole lot of sites
because they have no clue what bitrate of video will play right for you. So
they leave the audio in it's own separate feed and that let's them to shift
from a higher to lower or vice versa bitrate video stream without losing
audio synchronization.

**Comment by clocke125** [comment]
@bashonly  I realize that but the problem is now you have to download two separate files one audio and one video

yt-dlp -f 1630 https://www.cbsnews.com/video/sunday-morning-full-episode-3-26-2023/#x - gives video only

where before you got both in one file

**Comment by bashonly** [comment]
@clocke125
`yt-dlp -S res:540` (or `yt-dlp -f "1630+audio_aac-English"`)
it would work this way with a dedicated extractor too

**Comment by michaelcrossland1979** [comment]
Try not forcing the stream just let it pick.

**Comment by michaelcrossland1979** [comment]
Because I downloaded last night 48 hours and the Sunday political talking
head's show and they both come out fine.

**Comment by clocke125** [comment]
yt-dlp -s "res:540" https://www.cbsnews.com/video/sunday-morning-full-episode-3-26-2023/#x 
[generic] Extracting URL: res:540
[generic] res:540: Downloading webpage
ERROR: [generic] None: Unable to download webpage: <urlopen error unknown url type: res> (caused by URLError('unknown url type: res'))
[cbsnews] Extracting URL: https://www.cbsnews.com/video/sunday-morning-full-episode-3-26-2023/#x
[cbsnews] sunday-morning-full-episode-3-26-2023: Downloading webpage
[cbsnews] koz9MU_KlvU3mnhOKQH8JsW5KYCKf9X3: Downloading XML
ERROR: [cbsnews] sunday-morning-full-episode-3-26-2023: koz9MU_KlvU3mnhOKQH8JsW5KYCKf9X3: Failed to parse XML (caused by ParseError('no element found: line 1, column 0')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

**Comment by bashonly** [comment]
@clocke125 you still need to add `--force-generic`, and it's an uppercase `-S`

`yt-dlp --force-generic -S "res:540" "https://www.cbsnews.com/video/sunday-morning-full-episode-3-26-2023/"`

anyways, yt-dlp format selection/sorting is unrelated to this issue. please [see the README](https://github.com/yt-dlp/yt-dlp#format-selection) or open a separate question issue if it's unclear

**Comment by clocke125** [comment]
@bashonly 

yt-dlp --force-generic -S "res:540" "https://www.cbsnews.com/video/sunday-morning-full-episode-3-26-2023/"

That seems to have done the trick - Thank You

**Comment by PacoH** [comment]
Had same problem today ` --force-generic` worked. Thanks.

**Comment by metafo** [comment]
Both sounds and videos can be downloaded by added `--force-generic` commands but subtitles can't.

Here's the result:
`PS C:\Users\Ho> yt-dlp --force-generic --list-subs https://www.cbsnews.com/video/032823-cbs-evening-news/
[generic] Extracting URL: https://www.cbsnews.com/video/032823-cbs-evening-news/
[generic] 032823-cbs-evening-news: Downloading webpage
WARNING: [generic] Forcing generic information extractor
[generic] 032823-cbs-evening-news: Extracting information
[generic] Extracting URL: https://prod.vodvideo.cbsnews.com/cbsnews/vr/hls/2023/03/21/2185048131601/1835779_hls/master.m3u8...ing-news%2F%22%7D%7D
[generic] 032823-cbs-evening-news: Downloading webpage
[generic] 032823-cbs-evening-news: Downloading m3u8 information
032823-cbs-evening-news has no subtitles
PS C:\Users\Ho>
PS C:\Users\Ho>
`

**Comment by michaelcrossland1979** [comment]
I'm not sure if they actually do have CC for the news programs there self
or if that's something that's added like what Google does on the fly. As
for programming like 48 hours or 60 minutes then yes I do know that have CC
done up for those but also part of why those take sometimes more then 5
hours after the program airs for it to show up online.

**Comment by dirkf** [comment]
Looking at https://www.cbsnews.com/video/032823-cbs-evening-news/, the ld+json `VideoObject` has a `.contentUrl` whose value is the manifest https://prod.vodvideo.cbsnews.com/cbsnews/vr/hls/2023/03/21/2185048131601/1835779_hls/master.m3u8. Its streams are marked `CLOSED-CAPTIONS=NONE`. There is a full transcript in the `.transcript` but no way to synchronise it to the video.

The page assigns JSON to `CBSNEWS.defaultPayload` that contains a `.items` list with one element, an object with `.video` and `.video2` members. Both have the same value, the manifest above. There is also a `.captions` member https://assets2.cbsnewsstatic.com/hub/i/captions/_2wuO7hD9LwtyM_TwSnVwnKp6kxlcXgE.adb_xml containing TTML subtitles.

The extractor pulls values from this JSON and tries to get the `CBSIE` to perform the extraction from these values, but the API URL used there returns an empty XML result.

This block, added just before that final line of the `CBSNewsIE._real_extract()` method, together with the necessary additional imports (`determine_ext`, `traverse_obj`, `url_or_none`),
```py
        info = self._search_json_ld(webpage, display_id, expected_type='VideoObject', fatal=False) or {}
        info['id'] = item['mpxRefId']        
        if not url_or_none(info.get('url')):
            info['url'] = traverse_obj(item, 'video', 'video2', expected_type=url_or_none)
        if info.get('url'):
            subtitles = traverse_obj(item, 'captions', expected_type=url_or_none)
            if subtitles:
                info['subtitles'] = {'en': [{'url': subtitles, 'ext': 'ttml'}]}
            v_url = info.pop('url')
            ext = determine_ext(v_url)
            if ext == 'm3u8':
                info['formats'], sttls = self._extract_m3u8_formats_and_subtitles(
                    v_url, display_id, 'mp4', 'm3u8_native',
                    m3u8_id='hls', fatal=False)
                info['subtitles'] = self._merge_subtitles(sttls, info.get('subtitles') or {})
            else:
                info['url'] = v_url
            return info
```
fixes the extraction on this test URL and the original problem URL.

**Comment by rgiuffre** [comment]
I'm willing to learn Python just to get CBS.com working... :-)
