### ISSUE TITLE
Confusing options/switches on homepage

### ISSUE THREAD

**Issue by dobbelina** [yt-dlp/yt-dlp#6569]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [x] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Some options/switches have an added "s" which makes the instructions confusing on your homepage.
I found these 2:
**--no-check-certificates** & **--config-locations**
Should be:
**--no-check-certificate** & **--config-location**
Might be more, see images below for explanation.
![bild](https://user-images.githubusercontent.com/46063764/226253409-fccf2802-3f1e-4d81-9323-56aa43d6bf71.png)

![bild](https://user-images.githubusercontent.com/46063764/226253555-9ad221b9-3dc8-45f2-af64-86357f9dbe3d.png)

![bild](https://user-images.githubusercontent.com/46063764/226253643-85e21411-ec75-4064-820c-ab448a66868b.png)

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by Grub4K** [comment]
Switches can be shortened when not causing ambiguity, so you may use either of the switch variations (`--config-locations`, `--config-location`, `--config-loc`, ...) as long as it doesnt conflict with other switches. Are you saying the documentation should be adjusted to use the longer variation?

Imo a trailing `s` implies that the switch can be passed multiple locations at once while not having it implies that only one path may be used, and so it is easier to understand this way around. Also keep in mind that changing the name of the switches is not really plausible anymore due to compatibility.

**Comment by dobbelina** [comment]
For me it's confusing because it's ambiguous, especially when we are talking switches.
Please see the youtube-dl documentation:
[youtube-dl](https://github.com/ytdl-org/youtube-dl)

**Comment by dobbelina** [comment]
I don't have an issue with the added "s", and it's great that both varieties
work.
However it would be nice with a more explanatory description.
If I would have seen something like:  
**--config-location/s** (either single or multiple locations)

**Comment by pukkandan** [comment]
* The `s` is not going to be removed.
* We are also not going to list the possible shortenings of each option.
* A PR to make the entire readme consistently use the full option name is welcome.
* While this shortening is a feature of many command line programs, we could still mention it somewhere. Any suggestions?

**Comment by pukkandan** [comment]
Can re-open if anyone follows up
