### ISSUE TITLE
privat videos

### ISSUE THREAD

**Issue by khk58** [yt-dlp/yt-dlp#6576]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Dear all,
first I beg pardon for my poor english.
On downloading playlists 
(yt-dlp  --ignore-errors   --cookies-from-browser firefox --download-archive ..\archive.txt  -i --geo-bypass -o "%(title)s.%(ext)s"  https://www.youtube.com/playlist?list=PLE8Tj3_cWP6inKzBHVkjOVfyctP86y50a)
I get the following message
'[youtube] Extracting URL: https://www.youtube.com/watch?v=65sbzMV7Bjs
[youtube] 65sbzMV7Bjs: Downloading webpage
[youtube] 65sbzMV7Bjs: Downloading android player API JSON
ERROR: [youtube] 65sbzMV7Bjs: Private video. Sign in if you've been granted access to this video'

My questions are:

1) How to get in contact with the people putting these videos to 'Youtube' ?

or

2) How to skip downloading these videos ?

Kind regards and thanx in advance

Kurt (Austria) - khk58@gmx.at

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by Feathered-Serpent** [comment]
1. in your case I would say it's going to the Youtube channel from the playlist and check the info there and hope for a contact address:
https://www.youtube.com/@wocomoLIVING/about

2. It does so automatically, it just continues with the next video.

**Comment by khk58** [comment]
How to skip downloading these videos ? My question in this point is, how to skip **without** trying to download

**Comment by Feathered-Serpent** [comment]
I don't think yt-dlp can know it's private before trying to download it. Why do these 2 seconds matter?

**Comment by khk58** [comment]
Because in playlists are often lots of privat videos.

**Comment by pukkandan** [comment]
> don't think yt-dlp can know it's private before trying to download it
