### ISSUE TITLE
implement ability to stop playlist downloading after first already downloaded file encountered 

### ISSUE THREAD

**Issue by sss123next** [yt-dlp/yt-dlp#6580]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

if `--download-archive` is used, it would be nice to have ability to stop downloading from playlist if file which is already in download archive is seen.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
Is this what you're looking for?
```
--break-on-existing             Stop the download process when encountering
                                a file that is in the archive
```

**Comment by pukkandan** [comment]
> `--break-on-existing` - aborts whole process (exit from `yt-dlp`), but in my case i have list of playlists loaded via `-a` , so i want to be able to stop download from each playlist if file which is in download archive is encountered

Use it with `--break-per-input`

**Comment by sss123next** [comment]
thx for help.
looks like `--break-on-existing` + `--break-per-input` + `--lazy-playlist`  does exactly what i want, maybe such use case should be described in README ?

also, it seems like `--lazy-playlist` should be enabled by default (i have set it on in global config), or  it may be harmful in some cases ?

**Comment by pukkandan** [comment]
It's difficult to detect whether `n_entries` is being used in any of the template options (--output/--print etc) so it can't be enabled by default without breaking compat.

> maybe such use case should be described in README ?

Readme is for documentation, not tips. You are welcome to contribute to the https://github.com/yt-dlp/yt-dlp/wiki though
