### ISSUE TITLE
[twitter] incorrect tweet ID is saved to the filename.

### ISSUE THREAD

**Issue by jadedgnome** [yt-dlp/yt-dlp#6583]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

saved this tweet and expected the tweet ID 1637539564087660546 to be saved to the filename but instead it shows 1637537948768845826 .

https://twitter.com/markets/status/1637539564087660546

I depend on the correct twitter ID to be able to go back to the source at a later date.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp --no-mtime --ffmpeg-location=C:\Tools\  https://twitter.com/markets/status/1637539564087660546 -vU
[debug] Command-line config: ['--no-mtime', '--ffmpeg-location=C:\\Tools\\', 'https://twitter.com/markets/status/1637539564087660546', '-vU']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (pip)
[debug] Python 3.8.3 (CPython AMD64 64bit) - Windows-10-10.0.17763-SP0 (OpenSSL 1.1.1f  31 Mar 2020)
[debug] exe versions: ffmpeg git-2020-05-22-38490cb
[debug] Optional libraries: Cryptodome-3.12.0, brotli-1.0.9, certifi-2022.12.07, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.1
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
yt-dlp is up to date (stable@2023.03.04)
[twitter] Extracting URL: https://twitter.com/markets/status/1637539564087660546
[twitter] 1637539564087660546: Downloading guest token
[twitter] 1637539564087660546: Downloading JSON metadata
[debug] [twitter] Extracting from video info: 1637537948768845826
[twitter] 1637539564087660546: Downloading m3u8 information
[debug] Sort order given by extractor: res, br, size, proto
[debug] Formats sorted by: hasvid, ie_pref, res, tbr, vbr, abr, filesize, fs_approx, proto, lang, quality, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, asr, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 1637537948768845826: Downloading 1 format(s): http-2176
[debug] Invoking http downloader on "https://video.twimg.com/amplify_video/1637537948768845826/vid/1280x720/kizVAYFHCl7pPQp7.mp4?tag=16"
[download] Bloomberg Markets - A reporter asks Credit Suisse Chairman Axel Lehmann： ＂Who is responsible for this disaster？＂ [1637537948768845826].mp4 has already been downloaded
[download] 100% of    6.59MiB
```

**Comment by Grub4K** [comment]
See `display_id` vs `id`. The display id is the id of the tweet and the regular id is now the internal media id. This had to be done to support multi-video posts. If you want to get the id of the tweet use `display_id` instead.

**Comment by pukkandan** [comment]
Note that the multiple videos in same tweet will have same display_id
