### ISSUE TITLE
Hotstar HTTP Error 404

### ISSUE THREAD

**Issue by bibsp** [yt-dlp/yt-dlp#6587]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that a **supported** site is broken
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

India

### Provide a description that is worded well enough to be understood

https://www.hotstar.com/in/shows/mahabharat/435/bhishma-saves-vichitravirya/1000011770/

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.hotstar.com/in/shows/mahabharat/435/bhishma-saves-vichitravirya/1000011770/']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 6.0-essentials_build-www.gyan.dev (setts), ffprobe 6.0-essentials_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
Current Build Hash: 5590c57bd0433ed239a2deaaf92e2ad6f37fe50f53664c821575cafe106a9421
yt-dlp is up to date (stable@2023.03.04)
[generic] Extracting URL: https://www.hotstar.com/in/shows/mahabharat/435/bhishma-saves-vichitravirya/1000011770/
[generic] 1000011770: Downloading webpage
ERROR: [generic] None: Unable to download webpage: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 694, in extract
  File "yt_dlp\extractor\generic.py", line 2371, in _real_extract
  File "yt_dlp\extractor\common.py", line 839, in _request_webpage

  File "yt_dlp\extractor\common.py", line 821, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 3742, in urlopen
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found
```

**Comment by pukkandan** [comment]
> * 
> * [x]  I've checked that all provided URLs are playable in a browser with the same IP and same login details

It is not!

**Comment by bibsp** [comment]
Yes it is playable.

https://user-images.githubusercontent.com/98865389/226649322-7bb7a4ce-591f-443d-885c-d2f508fede0f.mp4

**Comment by pukkandan** [comment]
Are you logged in on browser? Have you tried passing cookies? Looks like duplicate of https://github.com/yt-dlp/yt-dlp/issues/6463

**Comment by pukkandan** [comment]
That's so weird. I get 404 on browser for your URL, similar to what happens in https://github.com/yt-dlp/yt-dlp/issues/6463. Another random URL like https://www.hotstar.com/in/tv/iss-pyar-ko-kya-naam-doon/423/payals-wedding-preparations/1000007604 does not give the error either in yt-dlp or in browser...

**Comment by bibsp** [comment]
> Another random URL like https://www.hotstar.com/in/tv/iss-pyar-ko-kya-naam-doon/423/payals-wedding-preparations/1000007604 does not give the error either in yt-dlp

But here it is also giving same error it yt-dlp. Browser is okay.

**Comment by bibsp** [comment]
> That's so weird. I get 404 on browser for your URL

I can reproduce this if I open the link in mobile browser. But desktop is okay.

Then searched the same video in mobile browser and copied the link. That link works fine in yt-dlp.


> https://www.hotstar.com/in/shows/mahabharat/435/bhishma-saves-vichitravirya/1000011770/

https://www.hotstar.com/in/tv/mahabharat/435/bhishma-saves-vichitravirya/1000011770
Same video link taken from mobile browser. This link works.
