### ISSUE TITLE
Parallell downloading of video fragments + gauging site d/l limitations

### ISSUE THREAD

**Issue by HalvorRaknes** [yt-dlp/yt-dlp#6588]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Would it be possible for yt-dlp to download fragmented video streams in parallell?

Aside from the technical issues of implementing such ability (I have glanced https://github.com/yt-dlp/yt-dlp/issues/1918 but most all of the discussion there is above my head) there is the issue of the video site's reaction to demand for increased bandwidth use. To be able to negotiate optimal behavior yt-dlp could somehow gauge the site's behavior so that parallell fragment downloads would only be requested where this would in actuality result in reduced download time in total.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
----
```

**Comment by pukkandan** [comment]
Out of scope

**Comment by Grub4K** [comment]
What about `-N` (`--concurrent-fragments`)? How does that not fit your criteria?

**Comment by HalvorRaknes** [comment]
> @Grub4K As I understand, they want us to somehow determine the optimal -N automatically

What I have noticed on some sites is that if you download two videos concurrently (in separate terminal windows) the download rate for the first one halves. Other sites don't mind.
