### ISSUE TITLE
Skip DRM/errored out links?

### ISSUE THREAD

**Issue by EndDragon438** [yt-dlp/yt-dlp#6592]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I'm running yt-dlp v2023.03.04 via Gooey to download YT video/audio. I ran into a problem while downloading a playlist, where it would download everything up to a certain link. After some trial and error, I found that it only stopped on specific links, and I'm assuming they're DRM links. Is there a way I can skip links that error out, or that have DRM embedded?

My copy-pasted output probably doesn't follow the typical format, as I'm using Gooey rather than command line. Once it gets to the final shown line it runs endlessly, and makes no progress and doesn't move on to the next link.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [x] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-P', 'C:\\Users\\End\\Music\\8-0', '--audio-format', 'mp3', '--audio-quality', '1', '--no-mtime', '-vU', '--yes-playlist', '--extract-audio', '--', 'https://www.youtube.com/playlist?list=PLuKSvOT6cUeQaxUdAw10NZFq-0kgyFZJQ']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out cp1252 (No ANSI), error cp1252 (No ANSI), screen cp1252 (No ANSI)
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 6.0-essentials_build-www.gyan.dev (setts)
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
Current Build Hash: 5590c57bd0433ed239a2deaaf92e2ad6f37fe50f53664c821575cafe106a9421
yt-dlp is up to date (stable@2023.03.04)
[youtube:tab] Extracting URL: https://www.youtube.com/playlist?list=PLuKSvOT6cUeQaxUdAw10NZFq-0kgyFZJQ
[youtube:tab] PLuKSvOT6cUeQaxUdAw10NZFq-0kgyFZJQ: Downloading webpage
[youtube:tab] PLuKSvOT6cUeQaxUdAw10NZFq-0kgyFZJQ: Redownloading playlist API JSON with unavailable videos
[download] Downloading playlist: Down
[youtube:tab] PLuKSvOT6cUeQaxUdAw10NZFq-0kgyFZJQ page 1: Downloading API JSON
[youtube:tab] Playlist Down: Downloading 114 items of 114
[download] Downloading item 1 of 114
[youtube] Extracting URL: https://www.youtube.com/watch?v=DOOk4oCmQuk
[youtube] DOOk4oCmQuk: Downloading webpage
[youtube] DOOk4oCmQuk: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[info] DOOk4oCmQuk: Downloading 1 format(s): 251
```

**Comment by pukkandan** [comment]
The given log doesn't seem to demonstrate your issue

**Comment by EndDragon438** [comment]
> 

I have another log from cmd:
```
Exception in thread Thread-1 (_forward_stdout):
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Program Files\Python310\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\End\AppData\Roaming\Python\Python310\site-packages\gooey\gui\processor.py", line 70, in _forward_stdout
    _progress = self._extract_progress(line)
  File "C:\Users\End\AppData\Roaming\Python\Python310\site-packages\gooey\gui\processor.py", line 84, in _extract_progress
    find = partial(re.search, string=text.strip().decode(self.encoding))
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x96 in position 43: invalid start byte
```
This may or may not be more useful. It seems to show the actual issue, rather than being stuck in one spot forever.

These are my config settings:
--audio-format mp3
--audio-quality 1
--no-mtime
--yes-playlist
--extract-audio

**Comment by pukkandan** [comment]
The error is coming from the GUI. Verify if the issue exists on CLI and report to the GUI devs if not.

**Comment by EndDragon438** [comment]
> The error is coming from the GUI. Verify if the issue exists on CLI and report to the GUI devs if not.

It did work via CLI, and eventually I found that the issue was that python was running without UTF-8 enabled by default. I fixed it by adding
```
set PYTHONUTF8=1
```
to the start of my launch script. All working now!
