### ISSUE TITLE
t.me: cannot use --write-info-json with default file name if the description is too long

### ISSUE THREAD

**Issue by tkzv** [yt-dlp/yt-dlp#6594]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that a **supported** site is broken
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Provide a description that is worded well enough to be understood

When a video is saved from t.me, and it has a text description, its description is used as the auto-generated file name. If it's too long, it's shortened to fit the OS limit minus the length of ".mp4" extension minus the length of the page ID number in square brackets.
When `--write-info-json` is used, a temporary file is saved under the same name, but with ".info.json.<8-letter hash>.tmp" extension.
If this file name is too long, yt-dlp stops with "OSError: [Errno 36] File name too long".

If a shorter name is set manually (with `-o`), yt-dlp works correctly.

This problem may manifest for other sites and other files (e.g. subtitles), but I only saw it for t.me and JSON.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://t.me/boris_rozhin/81022', '--write-info-json']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d]
[debug] Python 3.10.10 (CPython x86_64 64bit) - Linux-5.15.32-gentoo-r1-x86_64-AMD_FX-tm-8300_Eight-Core_Processor-with-glibc2.36 (OpenSSL 1.1.1t  7 Feb 2023, glibc 2.36)
[debug] exe versions: ffmpeg 4.4.3 (fdk,setts), ffprobe 4.4.3, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-3021.03.16, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
yt-dlp is up to date (stable@2023.03.04)
[telegram:embed] Extracting URL: https://t.me/boris_rozhin/81022
[telegram:embed] 81022: Downloading embed frame
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 81022: Downloading 1 format(s): 0
[info] Writing video metadata as JSON to: А в это время в Лионе, французы воплощают в жизнь известную картину ＂Its Fine＂ с собакой в горящей комнате. Францию охватили масштабные протесты и забастовки, так как Макрон отказался отменить пенсионную реформу и не допустил отставки правительства страны. [81022].info.json
ERROR: Cannot write video metadata to JSON file А в это время в Лионе, французы воплощают в жизнь известную картину ＂Its Fine＂ с собакой в горящей комнате. Францию охватили масштабные протесты и забастовки, так как Макрон отказался отменить пенсионную реформу и не допустил отставки правительства страны. [81022].info.json
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3947, in _write_info_json
    write_json_file(self.sanitize_info(ie_result, self.params.get('clean_infojson', True)), infofn)
  File "/usr/lib/python3.10/site-packages/yt_dlp/utils.py", line 263, in write_json_file
    tf = tempfile.NamedTemporaryFile(
  File "/usr/lib/python3.10/tempfile.py", line 559, in NamedTemporaryFile
    file = _io.open(dir, mode, buffering=buffering,
  File "/usr/lib/python3.10/tempfile.py", line 556, in opener
    fd, name = _mkstemp_inner(dir, prefix, suffix, flags, output_type)
  File "/usr/lib/python3.10/tempfile.py", line 256, in _mkstemp_inner
    fd = _os.open(file, flags, 0o600)
OSError: [Errno 36] File name too long: '/home/oleg/А в это время в Лионе, французы воплощают в жизнь известную картину ＂Its Fine＂ с собакой в горящей комнате. Францию охватили масштабные протесты и забастовки, так как Макрон отказался отменить пенсионную реформу и не допустил отставки правительства страны. [81022].info.json.fn02ndho.tmp'
```

**Comment by pukkandan** [comment]
Read pins

**Comment by brauliobo** [comment]
The use of `-o` is mandatory with `--write-info-json` in the case of twitter and other sources, as the filename will fail to write, for example:
```
ERROR: Cannot write video metadata to JSON file /tmp/mdb-20240104-1100734-sqfwle/input-20240104-1100734-mqzdgg/Los Herederos de Alberdi - Periodista kirchnerista： Milei quiere llevarse puesto todo lo que tanto nos costó conseguir 😡😤  Adorni： eso que tanto nos costó conseguir está en esta habitación con nosotros？ [1742912944533577728].info.json
```

A better solution is desirable

**Comment by tkzv** [comment]
> The use of `-o` is mandatory with `--write-info-json` in the case of twitter and other sources

> A better solution is desirable

For now, try the workaround from https://github.com/yt-dlp/yt-dlp/issues/7000 — add an alias to your configuration file that would automatically generate a name, add `--write-info-json` and do more boilerplate work, if necessary.
