### ISSUE TITLE
How to merge previously downloaded video only and audio only file for a youtube video

### ISSUE THREAD

**Issue by dsoum** [yt-dlp/yt-dlp#6595]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Suppose I dowloaded a video only file and a audio only file separately (in different time) for a particular Youtube video. Now I want to merge these files. Can I do that? How?

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
Use ffmpeg with `-c copy`

The exact command yt-dlp uses internally is:

```
ffmpeg -y -loglevel "repeat+info" -i "file:video.f248.webm" -i "file:video.f251.webm" -c copy -map "0:v:0" -map "1:a:0" -movflags "+faststart" "file:video.temp.mkv"
```

**Comment by flolu** [comment]
This worked for me:

```
ffmpeg -i audio.mp3 -i video.mp4 -c:v copy -c:a aac -strict experimental output.mkv
```
