### ISSUE TITLE
Why does yt-dlp spawn 2 processes? [Question]

### ISSUE THREAD

**Issue by sdan41517** [yt-dlp/yt-dlp#661]
Hi,

So I've switched from youtube-dl to yt-dlp and everything is great except one thing. I am using it in an Electron program and I've noticed that every time yt-dlp binary is executed, it spawns two processes whereas youtube-dl creates a single process. Due to this, it is not possible to pause downloads because I can pause the first process but not the second as I don't get the process ID for that.

Is there any way to force yt-dlp to spawn a single process?

**Comment by pukkandan** [comment]
I didnt know this :o

I assume it is a quirk of pyinstaller. I'll have to investigate more to see if there is a way around it.

**Comment by pukkandan** [comment]
https://github.com/blackjack4494/yt-dlc/issues/203
https://github.com/pyinstaller/pyinstaller/issues/2483

**Comment by nao20010128nao** [comment]
~~Compiling yt-dlp binary with other tools like Nuikta may "fix" the problem, but it takes unreasonable time to finish on Windows~~

**Comment by blackjack4494** [comment]
https://pyinstaller.readthedocs.io/en/stable/advanced-topics.html#bootloader

PyInstaller is instructed to use one-file which will bundle the app into one single executable. Usually you will have a folder with all dependencies etc. needed to run the actual program. The one-file option will simply put everything together and when you run the script first the loader will be called. The loader is a process that creates a temporary folder with all the needed stuff and will the delete it when it's not needed anymore (should be when the main program is started successful).
Then the actual script is invoked (alongside with a console window host but that doesn't matter).
The script is actually a child process of the loader. So if you look for any child processes (with the same name as the parent process of yt-dlp) you will find the right process to pause.
To accomplish this you could use for example psutil to find the child process.

**Comment by pukkandan** [comment]
How are you pausing the process? If you are sending a `SIGSTOP`, it should correctly pause the subprocess. If that is not an option, can't you query the child processes? I don't know how to do it in electron, but there is windows API to do it

**Comment by digitalheir** [comment]
The second process functions oddly, I return immediately to the command line. Could you please make everything in a single process? I believe it used to be like that.
