### ISSUE TITLE
can youtube dlp download youtube music related artists?

### ISSUE THREAD

**Issue by cruix89** [yt-dlp/yt-dlp#6628]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

greetings. 

Its possible youtube dlp download the related artists of a youtube music artist?
like a automatic library downloader?

thanks

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
Is there a youtube URL for it? If not, no.

**Comment by cruix89** [comment]
yes youtube music is a youtube normal URL, example:

https://music.youtube.com/channel/UCxpotETWMuwoi8Te_zw-VMQ

i use youtube dlp downloading this URL and extracting only audio, work well
but i suggest if would possible,  download the related artists of this page

![image](https://user-images.githubusercontent.com/73088019/227720103-6bb93ae0-1570-4efd-8593-5b2a2e90d8cc.png)

in the end of the artist channel have related artist is youtube normal URL also and is possible download them
but is necessary manual download one by one, my suggest is download automatic, its possible?

**Comment by pukkandan** [comment]
We currently cannot extract anything from youtube music directly, only from their youtube.com counterparts. See https://github.com/yt-dlp/yt-dlp/issues/6351
