### ISSUE TITLE
GLOBOPLAY don't work with YT-DLP

### ISSUE THREAD

**Issue by guiworldtv2** [yt-dlp/yt-dlp#6632]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

[Globo] Extracting URL: https://globoplay.globo.com/v/11423564/
[Globo] 11423564: Getting cookies
[Globo] 11423564: Downloading JSON metadata
[Globo] 11423564: Downloading security hash for 11423564

ERROR: [Globo] 11423564: Unable to download JSON metadata: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

---------------------------------------------------------------------------

HTTPError                                 Traceback (most recent call last)

[/usr/local/lib/python3.9/dist-packages/yt_dlp/extractor/common.py](https://localhost:8080/#) in _request_webpage(self, url_or_request, video_id, note, errnote, fatal, data, headers, query, expected_status)
    820         try:
--> 821             return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query))
    822         except network_exceptions as err:

20 frames

HTTPError: HTTP Error 403: Forbidden

During handling of the above exception, another exception occurred:

ExtractorError                            Traceback (most recent call last)

ExtractorError: [Globo] 11423564: Unable to download JSON metadata: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

During handling of the above exception, another exception occurred:

DownloadError                             Traceback (most recent call last)

[/usr/local/lib/python3.9/dist-packages/yt_dlp/YoutubeDL.py](https://localhost:8080/#) in trouble(self, message, tb, is_error)
    953             else:
    954                 exc_info = sys.exc_info()
--> 955             raise DownloadError(message, exc_info)
    956         self._download_retcode = 1
    957 

DownloadError: ERROR: [Globo] 11423564: Unable to download JSON metadata: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out UTF-8 (No ANSI), error UTF-8 (No ANSI), screen UTF-8 (No ANSI)
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (pip) API
[debug] params: {'format': 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best', 'outtmpl': '/content/drive/MyDrive/TEVE/GLOBO/%(title)s.%(ext)s', 'write_all_thumbnails': False, 'youtube_include_dash_manifest': False, 'youtube_include_hls_manifest': True, 'verbose': True, 'compat_opts': set()}
[debug] Python 3.9.16 (CPython x86_64 64bit) - Linux-5.10.147+-x86_64-with-glibc2.31 (OpenSSL 1.1.1f  31 Mar 2020, glibc 2.31)
[debug] exe versions: ffmpeg 4.2.7, ffprobe 4.2.7
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1786 extractors

[Globo] Extracting URL: https://globoplay.globo.com/v/11423564/
[Globo] 11423564: Getting cookies
[Globo] 11423564: Downloading JSON metadata
[Globo] 11423564: Downloading security hash for 11423564

ERROR: [Globo] 11423564: Unable to download JSON metadata: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/usr/local/lib/python3.9/dist-packages/yt_dlp/extractor/common.py", line 694, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.9/dist-packages/yt_dlp/extractor/globo.py", line 99, in _real_extract
    security = self._download_json(
  File "/usr/local/lib/python3.9/dist-packages/yt_dlp/extractor/common.py", line 1048, in download_content
    res = getattr(self, download_handle.__name__)(url_or_request, video_id, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/yt_dlp/extractor/common.py", line 1012, in download_handle
    res = self._download_webpage_handle(
  File "/usr/local/lib/python3.9/dist-packages/yt_dlp/extractor/common.py", line 882, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query, expected_status=expected_status)
  File "/usr/local/lib/python3.9/dist-packages/yt_dlp/extractor/common.py", line 839, in _request_webpage
    raise ExtractorError(errmsg, cause=err)

  File "/usr/local/lib/python3.9/dist-packages/yt_dlp/extractor/common.py", line 821, in _request_webpage
    return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query))
  File "/usr/local/lib/python3.9/dist-packages/yt_dlp/YoutubeDL.py", line 3742, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/usr/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

---------------------------------------------------------------------------

HTTPError                                 Traceback (most recent call last)

/usr/local/lib/python3.9/dist-packages/yt_dlp/extractor/common.py in _request_webpage(self, url_or_request, video_id, note, errnote, fatal, data, headers, query, expected_status)
    820         try:
--> 821             return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query))
    822         except network_exceptions as err:

20 frames

HTTPError: HTTP Error 403: Forbidden


During handling of the above exception, another exception occurred:

ExtractorError                            Traceback (most recent call last)

ExtractorError: [Globo] 11423564: Unable to download JSON metadata: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U


During handling of the above exception, another exception occurred:

DownloadError                             Traceback (most recent call last)

/usr/local/lib/python3.9/dist-packages/yt_dlp/YoutubeDL.py in trouble(self, message, tb, is_error)
    953             else:
    954                 exc_info = sys.exc_info()
--> 955             raise DownloadError(message, exc_info)
    956         self._download_retcode = 1
    957 

DownloadError: ERROR: [Globo] 11423564: Unable to download JSON metadata: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

**Comment by pukkandan** [comment]
> * [x]  I've checked that all provided URLs are playable in a browser with the same IP and same login details

The video does not seem to be accessible without login details - which you are not passing to yt-dlp
