### ISSUE TITLE
Is there a way to format output to remove "(Official Video)" and "(Audio)" from title?

### ISSUE THREAD

**Issue by famewolf** [yt-dlp/yt-dlp#6634]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Is there a way to format output so that the words (Official Video) and (Audio) in content downloaded from youtube and being converted to mp3 from both the filename and metadata?

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
See https://github.com/yt-dlp/yt-dlp#modifying-metadata

**Comment by famewolf** [comment]
so is '--replace-in-metadata  " \(Official Video\)|\(Audio\)" "" '   sufficient?   I'll be adding to the command line parms in the metube docker container.

**Comment by chrizilla** [comment]
@famewolf asked "Is there a way to format output […] from **both** the filename and metadata" ?

Is there a way to only change the filename without changing the metadata ?
Should I open a new issue for this related question ?
