### ISSUE TITLE
PLUTO TV UPDATE?

### ISSUE THREAD

**Issue by Ivoyko** [yt-dlp/yt-dlp#6639]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that a **supported** site is broken
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

SPAIN

### Provide a description that is worded well enough to be understood

Until no a lot ago i was downloading stuff from Pluto tv and the episode was downloaded perfect without ads.
Now every time i try this appear:
C:\Users\pc>C:\Users\pc\Downloads\Herramientas\VIDEOS\yt-dlp.exe https://pluto.tv/es/on-demand/series/teenage-mutant-ninja-turtles-es-ptv3/season/1/episode/el-ascenso-de-las-tortugas-parte-2-2011-1-102 -F
[PlutoTV] Extracting URL: https://pluto.tv/es/on-demand/series/teenage-mutant-ninja-turtles-es-ptv3/season/1/episode/el-asc...s-parte-2-2011-1-102
[PlutoTV] teenage-mutant-ninja-turtles-es-ptv3: Downloading JSON metadata
[PlutoTV] 60224e9e18a184001affbb69: Downloading m3u8 information
[PlutoTV] 60224e9e18a184001affbb69: Downloading m3u8 playlist
[PlutoTV] 60224e9e18a184001affbb69: Downloading m3u8 playlist
[PlutoTV] 60224e9e18a184001affbb69: Downloading m3u8 playlist
[PlutoTV] 60224e9e18a184001affbb69: Downloading m3u8 playlist
[PlutoTV] 60224e9e18a184001affbb69: Downloading m3u8 playlist
[PlutoTV] 60224e9e18a184001affbb69: Downloading m3u8 information
WARNING: [PlutoTV] Failed to download m3u8 information: HTTP Error 403: Forbidden
WARNING: [PlutoTV] Unable to find ad-free formats
That warnings are new and i dont know if u can update it to bypass that or pluto tv its fucked now.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
C:\Users\pc>C:\Users\pc\Downloads\Herramientas\VIDEOS\yt-dlp.exe https://pluto.tv/es/on-demand/series/teenage-mutant-ninja-turtles-es-ptv3/season/1/episode/el-ascenso-de-las-tortugas-parte-2-2011-1-102 -F
[PlutoTV] Extracting URL: https://pluto.tv/es/on-demand/series/teenage-mutant-ninja-turtles-es-ptv3/season/1/episode/el-asc...s-parte-2-2011-1-102
[PlutoTV] teenage-mutant-ninja-turtles-es-ptv3: Downloading JSON metadata
[PlutoTV] 60224e9e18a184001affbb69: Downloading m3u8 information
[PlutoTV] 60224e9e18a184001affbb69: Downloading m3u8 playlist
[PlutoTV] 60224e9e18a184001affbb69: Downloading m3u8 playlist
[PlutoTV] 60224e9e18a184001affbb69: Downloading m3u8 playlist
[PlutoTV] 60224e9e18a184001affbb69: Downloading m3u8 playlist
[PlutoTV] 60224e9e18a184001affbb69: Downloading m3u8 playlist
[PlutoTV] 60224e9e18a184001affbb69: Downloading m3u8 information
WARNING: [PlutoTV] Failed to download m3u8 information: HTTP Error 403: Forbidden
WARNING: [PlutoTV] Unable to find ad-free formats
```

**Comment by joaquinito2070** [comment]
@Ivoyko @pukkandan It seems that Pluto TV is protecting the contents to prevent piracy, there is nothing to do, the only thing we could do is change the domain to https://silo-hybrik.s3.amazonaws.com/, which is the origin server where are the files
