### ISSUE TITLE
Change APT installation instructions in Wiki

### ISSUE THREAD

**Issue by nicolaasjan** [yt-dlp/yt-dlp#6648]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

It seems the [APT instructions in the Wiki](https://github.com/yt-dlp/yt-dlp/wiki/Installation#apt) to install yt-dlp for Ubuntu and other related Debian-based distributions by adding the stable or unstable PPA are not working any more.
The relevant Launchpad pages for [Stable](https://launchpad.net/~yt-dlp/%2Barchive/ubuntu/stable) and [Unstable](https://launchpad.net/~yt-dlp/%2Barchive/ubuntu/unstable) by "yt-dlp Team" are gone.
Trying to add it via apt gives:

```bash
sudo add-apt-repository ppa:yt-dlp/stable
Cannot add PPA: "No supported PPA of this name was found".
```

This repo provided a really old version (2021.12.27), [according](https://web.archive.org/web/20230322215928/https://launchpad.net/~yt-dlp/+archive/ubuntu/stable) to the Wayback Archive (capture 2023-03-22).

Maybe replace it with the up to date repo:
https://launchpad.net/%7Etomtomtom/+archive/ubuntu/yt-dlp
(no "unstable" variant)

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by nicolaasjan** [comment]
I see now that this old repo didn't even provide a release for my particular distribution (Ubuntu Focal derived).
But it did provide yt-dlp for Ubuntu Jammy (22.04) and that also didn't work any more.
See [this Reddit thread](https://old.reddit.com/r/youtubedl/comments/123cqgk/error_ppa_ytdlpstable_not_found/).

**Comment by pukkandan** [comment]
Pls open a PR against the wiki - https://github.com/yt-dlp/yt-dlp/wiki#contributing-to-the-wiki

**Comment by nicolaasjan** [comment]
See:
https://github.com/yt-dlp/yt-dlp-wiki/pull/19
