### ISSUE TITLE
Does video ID in archive reflect changes in the video?

### ISSUE THREAD

**Issue by MasterMach50** [yt-dlp/yt-dlp#6650]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I see that each downloaded video's ID can be put in an archive file.

Is this 'ID' just the literal video ID (eg: `wnGAFF882tk`) or is it something made from the details of the video so as to reflect any changes that occurred to the the video on youtube after downloading it (eg: changing title, description etc).

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
No, it's the literal video id.

PS: The archive file is just plain text - you can read it if u want.

**Comment by MasterMach50** [comment]
Is there any chance it might change in the future, so that I can update the videos stored locally to the latest version?

**Comment by MasterMach50** [comment]
Something like video ID + hash of title+description+.. etc

**Comment by Grub4K** [comment]
No, download archive is very strict in the implementation and will most likely not change at all. To reflect changes you can either create your own archive object or rewrite the archive logic to fit your specific needs. Both have to be done in Python though.

**Comment by MasterMach50** [comment]
@Grub4K I can try do that but I am not familiar with the source, so if someone can point out the archiving logic I can try to modify it.
