### ISSUE TITLE
[archive.org] can the archive.org extractor be enhanced to use extractors for the archived web page ?

### ISSUE THREAD

**Issue by chrizilla** [yt-dlp/yt-dlp#6656]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a site-specific feature
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Example URLs

https://web.archive.org/web/20230316000347/https://tvthek.orf.at/profile/Dok-1/13844820/Dok-1-Zeit-sparen-Geld-sparen-Leichter-leben-mit-Lifehacks/14171617

### Provide a description that is worded well enough to be understood

I am sure this has been asked before, but I couldn't find an issue covering this question:

**Can the archive.org extractor be enhanced to use extractors for the archived web page ?**

**Example 1:**
In this example, the [orf.at video webpage](https://tvthek.orf.at/profile/Dok-1/13844820/Dok-1-Zeit-sparen-Geld-sparen-Leichter-leben-mit-Lifehacks/14171617) does not exist anymore but has been [archived on archive.org](https://web.archive.org/web/20230316000347/https://tvthek.orf.at/profile/Dok-1/13844820/Dok-1-Zeit-sparen-Geld-sparen-Leichter-leben-mit-Lifehacks/14171617). The video is playable there (although my browser stopped after the first 10 seconds, I don't know if this is a issue with my browser).
So the idea would be that the extractor for orf.at is used for the archive.org URL.

My feature request is not specific to orf.at but is meant as a general enhancement for the archive.org extractor regardless of the archived webpage. So the archive.org extractor should check if there is an extractor for the archived webpage --> if yes: use this extractor --> if no: try the generic extractor.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
n/a
```

**Comment by Lesmiscore** [comment]
> - [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
> - [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
> - [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below



I don't see your any actual attempt running yt-dlp, so you never tried it at all?

**Comment by pukkandan** [comment]
It is not possible to use a site's extractor for the archive page since the API call etc won't work.

**Comment by chrizilla** [comment]
@Lesmiscore: Please remove the invalid label, which apparently you added just for this missing log. Have you understood my request? This is a general enhancement idea, so there no log output is possible!

**Comment by chrizilla** [comment]
@pukkandan 
> It is not possible to use a site's extractor for the archive page since the API call etc won't work.

Thank you for your reply.
Can you explain to me in simple terms why it would not work?

Archive.org should normally archive all resources. I know this is not a 100% exact science and it may not work in every case, but I think in most cases, the archived website should be a 1:1 copy from the original. So all the resources should be there. And if the extractor is told about the new location to find the resources (archive.org/web/....), then the extractor should work, no?

What may be of help in this context are the different output format modifiers of the archived page on archive.org as enumerated here: https://webapps.stackexchange.com/questions/40911/web-archive-links-without-header/155393#155393
and here: https://en.wikipedia.org/wiki/Help:Using_the_Wayback_Machine#Specific_archive_copy

For example `id_` returns the original resource as it was archived.

**Comment by seproDev** [comment]
There are multiple problems at play here:
- Extractors have hard coded API requests. Afaik there is no easy way to modify all outgoing requests without some core changes.
- The Wayback Machine can't replay POST requests which are required by some sites.
- With sites changing and extractors getting updated, any significantly older page from the Wayback Machine likely wouldn't work anyway.
- Especially segmented media, like is used by most streaming sites, is rarely archived in full. This is the case for the example you posted. Only the init and first segment of the lowest resolution version are archived. Any regular extractor code would fail with this.
- Even if sites are fully archived, like was the case with [vlive](https://github.com/yt-dlp/yt-dlp/pull/6196), there are often still code changes needed to make things work.

**Comment by chrizilla** [comment]
@seproDev : Wow, thank you so much for this excellent, in-depth layout of the facts. That's extremely helpful to understand the problem at hand.

Ok, so sadly that doesn't seem like a useable idea. Sad because it would have been awesome to retrieve old archived videos that have disappeared from the web ...

**Comment by dirkf** [comment]
In the original case, illustrating the issues listed by @seproDev, the archived ORF page does contain the entire playlist information that the ORF extractor (of the time) should have used, like https://apasfiis.sf.apa.at/ipad/cms-worldwide/2023-03-15_2015_sd_01_Dok-1--Zeit-spa_____14171617__o__6349002656__s15358383_3__ORF1HD_20150113P_21002818P_Q1A.3gp/playlist.m3u8: but the media files weren't archived along with the programme page. The playlist links (10 combinations of different resolutions in HLS, HDS, and DASH) give me a little video saying that the selected show is being processed ("noch in Bearbeitung") and I should try again in a few minutes. However I'm fairly certain that the same result will occur whenever one does so and that the message should really say that the media is no longer available (and hasn't been for years), because such ancient (last media update 2018) links confuse the media server.

**Comment by pukkandan** [comment]
Closing since it is impossible to implement

**Comment by chrizilla** [comment]
@dirkf @seproDev @pukkandan : Thank you everyone for looking into this idea. Obviously not the outcome I had hoped for, but I am really glad and grateful, you have been investigating in detail whether it could work!
