### ISSUE TITLE
[Iwara] Incorrect redirect url

### ISSUE THREAD

**Issue by toomyzoom** [yt-dlp/yt-dlp#6669]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Redirected link is incomplete. Only hostname got redirected. The '/videos/' in the path also need to be changed to '/video/'.
Http request only does the host redirect and seem like the site uses javascript to change '/videos/' to '/video/'.
Input link: [https://**_ecchi_**.iwara.tv/**_videos_**/9rqzjcqq5otz9ovge](url)
Redirected link: [https://**_www_**.iwara.tv/**_videos_**/9rqzjcqq5otz9ovge](url)
Actual link: [https://www.iwara.tv/**_video_**/9rqzjcqq5otz9ovge](url)

I'm using 0f0875e

@Lesmiscore: may you take a look at this as your name was on the recent commits relating to this.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://ecchi.iwara.tv/videos/9rqzjcqq5otz9ovge']
[debug] User config "C:\Users\Nobita\AppData\Roaming\yt-dlp\config.txt": ['--compat-options', 'filename', '--cookies-from-browser', 'firefox', '--retries', 'infinite', '--retry-sleep', '2', '--extractor-args', 'youtube:skip=dash']
[debug] Encodings: locale cp932, fs utf-8, pref cp932, out cp932 (No VT), error cp932 (No VT), screen cp932 (No VT)
[debug] yt-dlp version stable@2023.03.04 [392389b7d]
[debug] Lazy loading extractors is disabled
[debug] Compatibility options: filename
[debug] Python 3.8.5 (CPython AMD64 32bit) - Windows-7-6.1.7601-SP1 (OpenSSL 1.1.1g  21 Apr 2020)
[debug] exe versions: ffmpeg N-106355-ga24e6ca8bf-20220320 (setts), ffprobe N-106355-ga24e6ca8bf-20220320
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[Cookies] Extracting cookies from firefox
[debug] Extracting cookies from: "C:\Users\Nobita\AppData\Roaming\Mozilla\Firefox\Profiles\jdltat92.dev-edition-default-1663626297735\cookies.sqlite"
[Cookies] Extracted 1766 cookies from firefox
[debug] Proxy map: {}
[debug] Loaded 1793 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
yt-dlp is up to date (stable@2023.03.04)
[generic] Extracting URL: https://ecchi.iwara.tv/videos/9rqzjcqq5otz9ovge
[generic] 9rqzjcqq5otz9ovge: Downloading webpage
[redirect] Following redirect to https://www.iwara.tv/videos/9rqzjcqq5otz9ovge
[generic] Extracting URL: https://www.iwara.tv/videos/9rqzjcqq5otz9ovge
[generic] 9rqzjcqq5otz9ovge: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] 9rqzjcqq5otz9ovge: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://www.iwara.tv/videos/9rqzjcqq5otz9ovge
Traceback (most recent call last):
  File "C:\Users\Nobita\AppData\Local\Programs\Python\Python38-32\lib\site-packages\yt_dlp\YoutubeDL.py", line 1518, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\Nobita\AppData\Local\Programs\Python\Python38-32\lib\site-packages\yt_dlp\YoutubeDL.py", line 1594, in __extract_info
    ie_result = ie.extract(url)
  File "C:\Users\Nobita\AppData\Local\Programs\Python\Python38-32\lib\site-packages\yt_dlp\extractor\common.py", line 694, in extract
    ie_result = self._real_extract(url)
  File "C:\Users\Nobita\AppData\Local\Programs\Python\Python38-32\lib\site-packages\yt_dlp\extractor\generic.py", line 2523, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.iwara.tv/videos/9rqzjcqq5otz9ovge
```

**Comment by Lesmiscore** [comment]
2-characters fix: just add `s?` after `video` in `_VALID_URL`, will do
