### ISSUE TITLE
Add support for tradingview videos

### ISSUE THREAD

**Issue by superclarkk** [yt-dlp/yt-dlp#6672]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

It would be good to be able to download videos, like the one on [this page](https://www.tradingview.com/chart/ES1!/XsMim4m1-Systemic-Risks-Alert-the-3-De-couplings/).

I tried the following:
```
yt-dlp -vU https://www.tradingview.com/chart/ES1!/XsMim4m1-Systemic-Risks-Alert-the-3-De-couplings/
bash: !/XsMim4m1: event not found
```

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by denaunistic** [comment]
btw it looks like yt-dlp can download videos from this site using the generic extractor

**Comment by superclarkk** [comment]
Thanks. Quoting with single quotes fixed it.
