### ISSUE TITLE
videos included in a compiled and/or authored playlist and as single video ...

### ISSUE THREAD

**Issue by Albretch** [yt-dlp/yt-dlp#6675]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

 videos included by an "uploader" in a playlist may not necessarily be authored by him/herself, so using the output format:

 --output "%(uploader)s/%(playlist)s/%(playlist_index)s_%(title)s_%(id)s.%(ext)s" 

 does not work because you would be saving the same video many times.

 You may also find a video listed within a playlist and also as a single video within the same account, for example:

 https://www.youtube.com/watch?v=yDNVPDwrKmE&list=PLuBXqtS2jaLMu81JnF6AOnRHzG6Csbd6y&index=2

 and 

 https://www.youtube.com/watch?v=yDNVPDwrKmE

 Sure! You want to save the information in the compiled playlist because they contain important categorization criteria by the owner of the account, but it doesn't make any sense to download the same video more than once.

 The best option I can think of about how to work around that problematic would be:

 1) download all videos within the account of the author:

 --output "%(uploader)s/%(title)s_%(id)s.%(ext)s" 

 2) download the list of videos in the order they were listed by whomever compiles a playlist (which I think is included in the json file of the list, right?) so that file should be downloaded into:

 --output "%(uploader)s/%(playlist)s" 

 I have these kinds of problems because as a teacher I need to download videos about a certain topic from different playlists of people who already have taken the time to check out what is out there.

 I am sure some of you may have had the same problem.

 Can you, as subject matter experts, think of a better way to do this? and/or share some tips?

 lbrtchx

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by Albretch** [comment]
I noticed you suggested the same option at reddit: https://www.reddit.com/r/youtubedl/comments/tpgcf4/ytdlp_how_to_generate_an_archive_file/
 I didn't exactly get my cake how I wanted it, I will have to parse that file, but I have another question. How do you get the json file of the playlist only (not of every single json of every video dumped into one)?

 _DT=$(date +%Y%m%d%H%M%S)
 _YT_PL=PLuBXqtS2jaLMu81JnF6AOnRHzG6Csbd6y
 _ARCH_LOG="${_YT_PL}_${_DT}_archive.log"
 _INFO_JSON="${_YT_PL}_${_DT}.info.json"
###
# ./yt-dlp --skip-download --dump-single-json --no-simulate "https://www.youtube.com/playlist?list=${_YT_PL}" >> "${_INFO_JSON}" 2>&1 
 ./yt-dlp --force-write-archive -s --download-archive "${_ARCH_LOG}" "${_YT_PL}" >> "${_ARCH_LOG}" 2>&1
 ls -l "${_YT_PL}"*.*
 wc -l "${_YT_PL}"*.*
 file "${_YT_PL}"*.*

**Comment by pukkandan** [comment]
> I didn't exactly get my cake how I wanted it, I will have to parse that file

Care to explain? Your requirement in OP doesn't indicate to me why you'd want to parse it back



> How do you get the json file of the playlist only (not of every single json of every video dumped into one)?

`--write-info-json` writes playlist info.json too. Is that not what u want?

> _DT=$(date +%Y%m%d%H%M%S)
> _YT_PL=PLuBXqtS2jaLMu81JnF6AOnRHzG6Csbd6y
> _ARCH_LOG="${_YT_PL}_${_DT}_archive.log"

Use same archive file for all yt-dlp runs. Otherwise how will it know what has been downloaded before?

**Comment by Albretch** [comment]
>> I didn't exactly get my cake how I wanted it, I will have to parse that file
> Care to explain? Your requirement in OP doesn't indicate to me why you'd want to parse it back

 the "--download-archive" option did give me a list of the included yt URIs (in the order listed in the playlist, I guess), but yt-dlp still dumped its inner working on the standard error pipe (I work on Linux), which is fine because, since yt-dlp does its work serially, you can redirected it into the same file, as I did. Some post-processing parsing will get me exactly what I want. However, I would like to:

 1) get the json of the playlist itself (not the json of every video appended into one large json, which in this case was an 18Mb file!);
 2) be able to use an output template to place that archive file in a directory of my choosing
 3) optimally, once the json file of the playlist has been downloaded just keep some of its metadata information (and remove the rest)

 How would you do this with yt-dlp?

 I think the best way to do §3 is by converting the json into an xml file and then extract what you need and keep it as xml in order to have it ready to imported into a DB if it comes to that. Does yt-dlp have a xml output option?

 I know some of what I am asking for isn’t really part of yt-dlp’s core functionality, but you may know of what other people have done while dealing with that kind of problematic and as John Lennon used to sing, I am sure "I am not the only one" who has dealt with such issues.

**Comment by pukkandan** [comment]
I'm getting more and more confused about your requirement. What I understood from OP is that you simply want to prevent the ame video from downloading multiple times. For that, all you need to do is use a **single archive file** for all your downloads. Do not use multiple archive files, no need to parse anything or mess with info-json. If that doesn't do what you want, pls explain better **with example verbose logs** of how what I suggested do not work.
