### ISSUE TITLE
[zoom.us] Fails with No video formats found!

### ISSUE THREAD

**Issue by someziggyman** [yt-dlp/yt-dlp#6677]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that a **supported** site is broken
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

anywhere

### Provide a description that is worded well enough to be understood

Test link:
https://ffgolf.zoom.us/rec/play/dJy6QRkm1fsfZCx2h8cHNJh7N1P0NP2alj-0XDL3c2cPdtAO8KK7lFdcmRod1fNxqIdzbPK3fLnMoi_w.HrmfpuxLVWa26JCt

No geo restriction or password needed.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
./yt-dlp -vU -F "https://ffgolf.zoom.us/rec/play/dJy6QRkm1fsfZCx2h8cHNJh7N1P0NP2alj-0XDL3c2cPdtAO8KK7lFdcmRod1fNxqIdzbPK3fLnMoi_w.HrmfpuxLVWa26JCt"
[debug] Command-line config: ['-vU', '-F', 'https://ffgolf.zoom.us/rec/play/dJy6QRkm1fsfZCx2h8cHNJh7N1P0NP2alj-0XDL3c2cPdtAO8KK7lFdcmRod1fNxqIdzbPK3fLnMoi_w.HrmfpuxLVWa26JCt']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.03 [934496428] (zip)
[debug] Python 3.11.2 (CPython arm64 64bit) - macOS-13.2.1-arm64-arm-64bit (OpenSSL 1.1.1t  7 Feb 2023)
[debug] exe versions: phantomjs 2.1.1
[debug] Optional libraries: sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Extractor Plugins: SamplePluginIE
[debug] Post-Processor Plugins: SamplePluginPP
[debug] Loaded 1850 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.03
Current Build Hash: c3b48730357dee54f39c679566261eb2bbfd96c32a1d25513efd04b76a9ecf42
[debug] Downloading _update_spec from https://github.com/yt-dlp/yt-dlp/releases/latest/download/_update_spec
Updating to stable@2023.03.04 ...
[debug] Downloading yt-dlp from https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp
[debug] Downloading SHA2-256SUMS from https://github.com/yt-dlp/yt-dlp/releases/latest/download/SHA2-256SUMS
Updated yt-dlp to stable@2023.03.04
[debug] Restarting: /opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/Resources/Python.app/Contents/MacOS/Python ./yt-dlp -vU -F https://ffgolf.zoom.us/rec/play/dJy6QRkm1fsfZCx2h8cHNJh7N1P0NP2alj-0XDL3c2cPdtAO8KK7lFdcmRod1fNxqIdzbPK3fLnMoi_w.HrmfpuxLVWa26JCt
[debug] Command-line config: ['-vU', '-F', 'https://ffgolf.zoom.us/rec/play/dJy6QRkm1fsfZCx2h8cHNJh7N1P0NP2alj-0XDL3c2cPdtAO8KK7lFdcmRod1fNxqIdzbPK3fLnMoi_w.HrmfpuxLVWa26JCt']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (zip)
[debug] Python 3.11.2 (CPython arm64 64bit) - macOS-13.2.1-arm64-arm-64bit (OpenSSL 1.1.1t  7 Feb 2023)
[debug] exe versions: phantomjs 2.1.1
[debug] Optional libraries: no_Cryptodome-None, sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Extractor Plugins: SamplePluginIE
[debug] Post-Processor Plugins: SamplePluginPP
[debug] Loaded 1787 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
Current Build Hash: 91cad9f121c1f6f0a81b747415c46ecba0ff331ed38cc6433040b4ac7b6e15ca
yt-dlp is up to date (stable@2023.03.04)
[zoom] Extracting URL: https://ffgolf.zoom.us/rec/play/dJy6QRkm1fsfZCx2h8cHNJh7N1P0NP2alj-0XDL3c2cPdtAO8KK7lFdcmRod1fNxqIdzbPK3fLnMoi_w.HrmfpuxLVWa26JCt
[zoom] dJy6QRkm1fsfZCx2h8cHNJh7N1P0NP2alj-0XDL3c2cPdtAO8KK7lFdcmRod1fNxqIdzbPK3fLnMoi_w.HrmfpuxLVWa26JCt: Downloading webpage
WARNING: Extractor failed to obtain "title". Creating a generic title instead
ERROR: [zoom] dJy6QRkm1fsfZCx2h8cHNJh7N1P0NP2alj-0XDL3c2cPdtAO8KK7lFdcmRod1fNxqIdzbPK3fLnMoi_w.HrmfpuxLVWa26JCt: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "./yt-dlp/yt_dlp/YoutubeDL.py", line 1518, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "./yt-dlp/yt_dlp/YoutubeDL.py", line 1615, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "./yt-dlp/yt_dlp/YoutubeDL.py", line 1674, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "./yt-dlp/yt_dlp/YoutubeDL.py", line 2615, in process_video_result
    self.raise_no_formats(info_dict)
  File "./yt-dlp/yt_dlp/YoutubeDL.py", line 1046, in raise_no_formats
    raise ExtractorError(msg, video_id=info['id'], ie=info['extractor'],
yt_dlp.utils.ExtractorError: [zoom] dJy6QRkm1fsfZCx2h8cHNJh7N1P0NP2alj-0XDL3c2cPdtAO8KK7lFdcmRod1fNxqIdzbPK3fLnMoi_w.HrmfpuxLVWa26JCt: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

**Comment by branliu0** [comment]
+1 I'm running into this too now. I think something changed earlier this week.

```
$ yt-dlp -vU https://us02web.zoom.us/rec/share/hkUk5Zxcga0nkyNGhVCRfzkA2gX_mzgS3LpTxEEWJz9Y_QpIQ4mZFOUx7KZRZDQA.9LGQBdqmDAYgiZ_8
[debug] Command-line config: ['-vU', 'https://us02web.zoom.us/rec/share/hkUk5Zxcga0nkyNGhVCRfzkA2gX_mzgS3LpTxEEWJz9Y_QpIQ4mZFOUx7KZRZDQA.9LGQBdqmDAYgiZ_8']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (pip)
[debug] Python 3.9.7 (CPython x86_64 64bit) - macOS-13.2.1-x86_64-i386-64bit (OpenSSL 1.1.1t  7 Feb 2023)
[debug] exe versions: ffmpeg 5.1.2 (setts), ffprobe 5.1.2
[debug] Optional libraries: Cryptodome-3.14.0, brotli-1.0.9, certifi-2021.10.08, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
yt-dlp is up to date (stable@2023.03.04)
[zoom] Extracting URL: https://us02web.zoom.us/rec/share/hkUk5Zxcga0nkyNGhVCRfzkA2gX_mzgS3LpTxEEWJz9Y_QpIQ4mZFOUx7KZRZDQA.9LGQBdqmDAYgiZ_8
[zoom] hkUk5Zxcga0nkyNGhVCRfzkA2gX_mzgS3LpTxEEWJz9Y_QpIQ4mZFOUx7KZRZDQA.9LGQBdqmDAYgiZ_8: Downloading webpage
WARNING: Extractor failed to obtain "title". Creating a generic title instead
ERROR: [zoom] hkUk5Zxcga0nkyNGhVCRfzkA2gX_mzgS3LpTxEEWJz9Y_QpIQ4mZFOUx7KZRZDQA.9LGQBdqmDAYgiZ_8: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "/Users/brandonliu/.pyenv/versions/3.9.7/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1518, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/brandonliu/.pyenv/versions/3.9.7/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1615, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/Users/brandonliu/.pyenv/versions/3.9.7/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1674, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/Users/brandonliu/.pyenv/versions/3.9.7/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 2615, in process_video_result
    self.raise_no_formats(info_dict)
  File "/Users/brandonliu/.pyenv/versions/3.9.7/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1046, in raise_no_formats
    raise ExtractorError(msg, video_id=info['id'], ie=info['extractor'],
yt_dlp.utils.ExtractorError: [zoom] hkUk5Zxcga0nkyNGhVCRfzkA2gX_mzgS3LpTxEEWJz9Y_QpIQ4mZFOUx7KZRZDQA.9LGQBdqmDAYgiZ_8: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

**Comment by shreyasminocha** [comment]
It looks like previously the `viewMp4Url` field was included within `window.__data__`, but now zoom makes an HTTP request to `/nws/recording/1.0/play/info/${window.__data__.fileId}` to get that information.

**Comment by shreyasminocha** [comment]
I've made some progress on this. I'm now able to get it to download the recording, but I still need to fix the metadata extraction. Also, it's unclear if this change has been rolled out everywhere or if it's something they're A/B testing. I'll try to make a pull request over the weekend.

**Comment by someziggyman** [comment]
@pukkandan  Thanks a lot for the latest zoom fix, and the initially reported link seems to work just fine now. But another link of the same type seems to fail. strange. 

Link:
https://ffgolf.zoom.us/rec/share/0K6STMS-NVFAAo0_s171kQvy3-dBbZd5eYQoyLBTnVsXzA3iCNvUBsrkgEAQdOFs.yNdOGCuEK0YyqyVy

BTW this one also fails (reported by @branliu0):
https://us02web.zoom.us/rec/share/hkUk5Zxcga0nkyNGhVCRfzkA2gX_mzgS3LpTxEEWJz9Y_QpIQ4mZFOUx7KZRZDQA.9LGQBdqmDAYgiZ_8


**Log below:**
./yt-dlp -Uv -F "https://us02web.zoom.us/rec/share/hkUk5Zxcga0nkyNGhVCRfzkA2gX_mzgS3LpTxEEWJz9Y_QpIQ4mZFOUx7KZRZDQA.9LGQBdqmDAYgiZ_8"
[debug] Command-line config: ['-Uv', '-F', 'https://us02web.zoom.us/rec/share/hkUk5Zxcga0nkyNGhVCRfzkA2gX_mzgS3LpTxEEWJz9Y_QpIQ4mZFOUx7KZRZDQA.9LGQBdqmDAYgiZ_8']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (zip)
[debug] Python 3.11.3 (CPython arm64 64bit) - macOS-13.3-arm64-arm-64bit (OpenSSL 1.1.1t  7 Feb 2023)
[debug] exe versions: phantomjs 2.1.1
[debug] Optional libraries: no_Cryptodome-None, sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Extractor Plugins: SamplePluginIE
[debug] Post-Processor Plugins: SamplePluginPP
[debug] Loaded 1787 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
Current Build Hash: 91cad9f121c1f6f0a81b747415c46ecba0ff331ed38cc6433040b4ac7b6e15ca
yt-dlp is up to date (stable@2023.03.04)
[zoom] Extracting URL: https://us02web.zoom.us/rec/share/hkUk5Zxcga0nkyNGhVCRfzkA2gX_mzgS3LpTxEEWJz9Y_QpIQ4mZFOUx7KZRZDQA.9LGQBdqmDAYgiZ_8
[zoom] hkUk5Zxcga0nkyNGhVCRfzkA2gX_mzgS3LpTxEEWJz9Y_QpIQ4mZFOUx7KZRZDQA.9LGQBdqmDAYgiZ_8: Downloading webpage
WARNING: Extractor failed to obtain "title". Creating a generic title instead
ERROR: [zoom] hkUk5Zxcga0nkyNGhVCRfzkA2gX_mzgS3LpTxEEWJz9Y_QpIQ4mZFOUx7KZRZDQA.9LGQBdqmDAYgiZ_8: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "./yt-dlp/yt_dlp/YoutubeDL.py", line 1518, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "./yt-dlp/yt_dlp/YoutubeDL.py", line 1615, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "./yt-dlp/yt_dlp/YoutubeDL.py", line 1674, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "./yt-dlp/yt_dlp/YoutubeDL.py", line 2615, in process_video_result
    self.raise_no_formats(info_dict)
  File "./yt-dlp/yt_dlp/YoutubeDL.py", line 1046, in raise_no_formats
    raise ExtractorError(msg, video_id=info['id'], ie=info['extractor'],
yt_dlp.utils.ExtractorError: [zoom] hkUk5Zxcga0nkyNGhVCRfzkA2gX_mzgS3LpTxEEWJz9Y_QpIQ4mZFOUx7KZRZDQA.9LGQBdqmDAYgiZ_8: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

**Comment by bashonly** [comment]
@someziggyman That log is from version 2023.03.04 (without the patch). But I can confirm that with the patch, the extractor does not work for those links: the API requests return 404 errors. Since the error and reason for the error are different, it's best to open a new issue with correct log(s)

**Comment by someziggyman** [comment]
I added the patch manually. will submit a new issue then.

**Comment by shreyasminocha** [comment]
Interesting. Just confirmed that downloading these:

- `https://us02web.zoom.us/rec/play/WGmuDIzMwUHROmG8_dYyHQkyiDbGJ9BxnLHVbtfOqOU4AaUKePJ2tQBidyHJwkVtfy_8a6-965_SVv7Q.xxvHpioqTT2SW0Mw`
- `https://ffgolf.zoom.us/rec/play/9784A_cApJW-x88Xc2sTm9B2LdIKip86b0zEVO9VF_AqJpbKIV1A0TG9A-xhBLmVyRb8UPyEsOHceO7f.nL_zCsux5fCEvx85`

…works with the patch. So it looks like we have `/rec/play` URLs working, but we'll need to look into what's up with the `/rec/share` ones.

**Comment by bashonly** [comment]
> I added the patch manually. will submit a new issue then.

@someziggyman Not necessary now, I have opened a PR to fix it
