### ISSUE TITLE
[instagram] /reels/ URLs unsupported

### ISSUE THREAD

**Issue by thomco** [yt-dlp/yt-dlp#6689]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a site-specific feature
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United States

### Example URLs

https://www.instagram.com/reels/Cop84x6u7CP/

### Provide a description that is worded well enough to be understood
Repros with any of the reels found on the [instagram reels page](https://www.instagram.com/reels page) 

extractor falls back to generic and then gives Unsupported URL error.

The description and debug output looks the same as #4743 
However, that issue appears to be limited to audio reels.   My issue repros for all reels.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--cookies-from-browser', 'chrome', 'https://www.instagram.com/reels/Cop84x6u7CP/']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22624-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[Cookies] Extracting cookies from chrome
[debug] Extracting cookies from: "C:\Users\Thomas\AppData\Local\Google\Chrome\User Data\Default\Network\Cookies"
[debug] Found local state file at "C:\Users\Thomas\AppData\Local\Google\Chrome\User Data\Local State"
[Cookies] Extracted 3315 cookies from chrome
[debug] cookie version breakdown: {'v10': 3315, 'other': 0, 'unencrypted': 0}
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
Current Build Hash: 5590c57bd0433ed239a2deaaf92e2ad6f37fe50f53664c821575cafe106a9421
yt-dlp is up to date (stable@2023.03.04)
[generic] Extracting URL: https://www.instagram.com/reels/Cop84x6u7CP/
[generic] Cop84x6u7CP: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] Cop84x6u7CP: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://www.instagram.com/reels/Cop84x6u7CP/
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1518, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1594, in __extract_info
  File "yt_dlp\extractor\common.py", line 694, in extract
  File "yt_dlp\extractor\generic.py", line 2510, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.instagram.com/reels/Cop84x6u7CP/
```

**Comment by bashonly** [comment]
Workaround:
Use this URL `https://www.instagram.com/p/Cop84x6u7CP/`
(change `reels` to `p`)

Try it without cookies first. (Passing cookies for instagram is risky and should be avoided if possible)

The IG extractor's `_VALID_URL` needs to updated

**Comment by scrutinizer11** [comment]
I don't have issues downloading reels, however getting the right link is a real challenge. I wrote a script that automates certain aspects of yt-dlp usage but it falters when it comes to such videos. The reason for that is the way the presentation of the reels is implemented in the so-called "theatrical mode" where switching back and forth won't update either the page source or the visible URL unless you exit the mode and click on another reel.

**Comment by mon-jai** [comment]
> Workaround: Use this URL `https://www.instagram.com/p/Cop84x6u7CP/` (change `reels` to `p`)

It doesn't work too.

```
yt-dlp https://www.instagram.com/p/Cop84x6u7CP/
[Instagram] Cop84x6u7CP: Downloading webpage
WARNING: [Instagram] unable to extract username; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
ERROR: [Instagram] Cop84x6u7CP: Unable to extract video url; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

**Comment by bashonly** [comment]
@mon-jai that does not look like the current version of yt-dlp. Update yt-dlp or post a verbose log

**Comment by mon-jai** [comment]
@bashonly You are right. Turns out there is an old version of yt-dlp which takes priority over the version installed with pip.

**Comment by BrianAllred** [comment]
Still having this issue on the latest yt-dlp.

```
root@ebf8668b5f6d:/app# yt-dlp --version
2023.03.04
root@ebf8668b5f6d:/app# yt-dlp -U
Available version: stable@2023.03.04, Current version: stable@2023.03.04
yt-dlp is up to date (stable@2023.03.04)
root@ebf8668b5f6d:/app# yt-dlp 'https://www.instagram.com/p/CqKotZjjjJs/?igshid=MTc4MmM1YmI2Ng=='
[Instagram] Extracting URL: https://www.instagram.com/p/CqKotZjjjJs/?igshid=MTc4MmM1YmI2Ng==
[Instagram] CqKotZjjjJs: Setting up session
[Instagram] CqKotZjjjJs: Downloading JSON metadata
[info] CqKotZjjjJs: Downloading 1 format(s): 0
ERROR: unable to download video data: HTTP Error 404: Not Found
root@ebf8668b5f6d:/app# yt-dlp 'https://www.instagram.com/p/CqKotZjjjJs'
[Instagram] Extracting URL: https://www.instagram.com/p/CqKotZjjjJs
[Instagram] CqKotZjjjJs: Setting up session
[Instagram] CqKotZjjjJs: Downloading JSON metadata
[info] CqKotZjjjJs: Downloading 1 format(s): 0
ERROR: unable to download video data: HTTP Error 404: Not Found
```

**Comment by bashonly** [comment]
@BrianAllred Your log is demonstrating a different issue: 404 error when downloading a supported URL. Can you open a new issue with a **verbose** log?

**Comment by iatsiuk** [comment]
Having same issue:

```
yt-dlp -U
Available version: stable@2023.07.06, Current version: stable@2023.07.06
yt-dlp is up to date (stable@2023.07.06)
```
```
❯ yt-dlp "https://www.instagram.com/reel/CuhF3zyufWw/?igshid=YWYwM2I1ZDdmOQ=="
[Instagram] Extracting URL: https://www.instagram.com/reel/CuhF3zyufWw/?igshid=YWYwM2I1ZDdmOQ==
[Instagram] CuhF3zyufWw: Setting up session
[Instagram] CuhF3zyufWw: Downloading JSON metadata
WARNING: [Instagram] unable to extract username; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
ERROR: [Instagram] CuhF3zyufWw: Unable to extract video url; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```
```
❯ yt-dlp "https://www.instagram.com/p/CuhF3zyufWw/"
[Instagram] Extracting URL: https://www.instagram.com/p/CuhF3zyufWw/
[Instagram] CuhF3zyufWw: Setting up session
[Instagram] CuhF3zyufWw: Downloading JSON metadata
WARNING: [Instagram] unable to extract username; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
ERROR: [Instagram] CuhF3zyufWw: Unable to extract video url; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

**Comment by Canowyrms** [comment]
> Passing cookies for instagram is risky and should be avoided if possible

@bashonly Can you expand on this, please? Risky how?

**Comment by bashonly** [comment]
instagram can detect yt-dlp usage and they will happily ban your account

**Comment by Canowyrms** [comment]
Oof, thanks for the heads up.

**Comment by mikemykhaylov** [comment]
When using `ytd-rs` wrapper from Docker, I'm getting this error:

```
WARNING: [Instagram] unable to extract shared data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
youtube-dl exited with: WARNING: [Instagram] Cwx81Evv6jg: General metadata extraction failed (some metadata might be missing).
WARNING: [Instagram] Main webpage is locked behind the login page. Retrying with embed webpage (some metadata might be missing).
WARNING: [Instagram] unable to extract additional data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
ERROR: [Instagram] Cwx81Evv6jg: Requested content is not available, rate-limit reached or login required. Use --cookies, --cookies-from-browser, --username and --password, --netrc-cmd, or --netrc (instagram) to provide account credentials
```

**Comment by bashonly** [comment]
@mikemykhaylov unrelated to this issue. but IG blocks data center IPs, if that's applicable to your docker run

**Comment by mikemykhaylov** [comment]
Likely, good to know, thanks

**Comment by pukkandan** [comment]
> instagram can detect yt-dlp usage and they will happily ban your account

Should the IE issue a warning for this? Lot of people don't seem to be aware this is a thing

**Comment by bashonly** [comment]
I suppose we could add it to the `raise_login_required()` msg

**Comment by Bratzmeister** [comment]
`yt-dlp -vU https://www.instagram.com/reel/Cv1qz-vIuVq/?utm_source=ig_web_copy_link
[debug] Command-line config: ['-vU', 'https://www.instagram.com/reel/Cv1qz-vIuVq/?utm_source=ig_web_copy_link']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.12.30 from yt-dlp/yt-dlp [f10589e34]
[debug] Python 3.11.8 (CPython x86_64 64bit) - Linux-6.7.7-gentoo-dist-x86_64-AMD_Ryzen_9_7950X_16-Core_Processor-with-glibc2.38 (OpenSSL 3.0.13 30 Jan 2024, glibc 2.38)
[debug] exe versions: ffmpeg 6.0.1 (fdk,setts), ffprobe 6.0.1, rtmpdump 2.4
[debug] Optional libraries: brotlicffi-1.1.0.0, certifi-3021.03.16, mutagen-1.47.0, pycrypto-3.20.0, requests-2.31.0, secretstorage-3.3.3, sqlite3-3.45.1, urllib3-2.1.0
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests
[debug] Loaded 1798 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Latest version: stable@2023.12.30 from yt-dlp/yt-dlp
yt-dlp is up to date (stable@2023.12.30 from yt-dlp/yt-dlp)
[Instagram] Extracting URL: https://www.instagram.com/reel/Cv1qz-vIuVq/?utm_source=ig_web_copy_link
[Instagram] Cv1qz-vIuVq: Setting up session
WARNING: [Instagram] Cv1qz-vIuVq: No csrf token set by Instagram API
[Instagram] Cv1qz-vIuVq: Downloading JSON metadata
WARNING: [Instagram] unable to extract username; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
ERROR: [Instagram] Cv1qz-vIuVq: Unable to extract video url; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/usr/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 718, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/extractor/instagram.py", line 487, in _real_extract
    video_url = self._og_search_video_url(webpage, secure=False)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 1409, in _og_search_video_url
    return self._html_search_regex(regexes, html, name, **kargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 1302, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 1266, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
`

**Comment by bashonly** [comment]
@Bratzmeister #5967
