### ISSUE TITLE
Add Support for https://ronemo.com

### ISSUE THREAD

**Issue by ht990332** [yt-dlp/yt-dlp#6693]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Lebanon

### Example URLs

- Single video https://ronemo.com/video/nOZhtCJk6YB

### Provide a description that is worded well enough to be understood

Kindly add support for ronemo.com. At the moment with the latest yt-dlp, movies do not download.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[generic] Extracting URL: https://ronemo.com/video/nOZhtCJk6YB
[generic] nOZhtCJk6YB: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] nOZhtCJk6YB: Extracting information
[generic] Extracting URL: https://ronemo.com/embed/nOZhtCJk6YB
[generic] nOZhtCJk6YB: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] nOZhtCJk6YB: Extracting information
ERROR: Unsupported URL: https://ronemo.com/embed/nOZhtCJk6YB
[hussam@hades Downloads]$ yt-dlp -vU https://ronemo.com/video/nOZhtCJk6YB
[debug] Command-line config: ['-vU', 'https://ronemo.com/video/nOZhtCJk6YB']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (pip)
[debug] Python 3.10.10 (CPython x86_64 64bit) - Linux-6.1.22-1-lts-x86_64-with-glibc2.35 (OpenSSL 3.0.8 7 Feb 2023, glibc 2.35)
[debug] exe versions: ffmpeg 5.1.3 (setts), ffprobe 5.1.3
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
yt-dlp is up to date (stable@2023.03.04)
[generic] Extracting URL: https://ronemo.com/video/nOZhtCJk6YB
[generic] nOZhtCJk6YB: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] nOZhtCJk6YB: Extracting information
[debug] Looking for embeds
[debug] Identified a twitter:player iframe
[generic] Extracting URL: https://ronemo.com/embed/nOZhtCJk6YB
[generic] nOZhtCJk6YB: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] nOZhtCJk6YB: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://ronemo.com/embed/nOZhtCJk6YB
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1518, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1594, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 694, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.10/site-packages/yt_dlp/extractor/generic.py", line 2510, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://ronemo.com/embed/nOZhtCJk6YB
```

**Comment by bashonly** [comment]
Looks like the site is primarily used for piracy, so it will not be supported. Provide evidence to the contrary if you believe otherwise
