### ISSUE TITLE
HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by Jeminko** [yt-dlp/yt-dlp#6702]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I am not able to download this video: https://vz-c8dfe676-56e.b-cdn.net/ad337427-4965-4842-8fe1-ca6d53520722/1920x1080/video.m3u8
Is there any solution to download it?
Thank you in advance.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by miyurusankalpa** [comment]
Add correct referrer to b-cdn urls and it will work. for yours following will work.

`--add-header 'Referer: https://b-cdn.net/' `

**Comment by Jeminko** [comment]
> 



> Add correct referrer to b-cdn urls and it will work. for yours following will work.
> 
> `--add-header 'Referer: https://b-cdn.net/' `

It works! Thank you very very very much! You saved my life! I was trying to solve it almost a year.
