### ISSUE TITLE
[Bilibili] Channel does not download does not include series tab (合集和列表) | Series playlist url errors and cannot be downloaded

### ISSUE THREAD

**Issue by dfgyuri** [yt-dlp/yt-dlp#6719]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that a **supported** site is broken
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Provide a description that is worded well enough to be understood

Currently, feeding a bilibili channel URL only downloads videos under the video tab (space.bilibili.com/channelid/video) and does not download items under the series tab (space.bilibili.com/channelid/channel/series). Attempting to feed the series tab URL directly or a series playlist URL results in yt-dlp erroring out with unsupported URL. The videos are downloadable if their direct URL is used but there does not seem to be a way to download the playlist.

This is the output for the direct playlist url, the output for the channel series tab is in the complete verbose output section.
```shell
yt-dlp -vU --ignore-config "https://www.bilibili.com/list/4947340?sid=549922"
[debug] Command-line config: ['-vU', '--ignore-config', 'https://www.bilibili.com/list/4947340?sid=549922']
[debug] Encodings: locale cp932, fs utf-8, pref cp932, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19044-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 2022-08-03-git-d3f48e68b3-full_build-www.gyan.dev (setts), ffprobe 2022-08-03-git-d3f48e68b3-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
Current Build Hash: 5590c57bd0433ed239a2deaaf92e2ad6f37fe50f53664c821575cafe106a9421
yt-dlp is up to date (stable@2023.03.04)
[generic] Extracting URL: https://www.bilibili.com/list/4947340?sid=549922
[generic] 4947340?sid=549922: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] 4947340?sid=549922: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://www.bilibili.com/list/4947340?sid=549922
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1518, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1594, in __extract_info
  File "yt_dlp\extractor\common.py", line 694, in extract
  File "yt_dlp\extractor\generic.py", line 2510, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.bilibili.com/list/4947340?sid=549922
```

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp -vU --ignore-config "https://space.bilibili.com/4947340/channel/seriesdetail?sid=549922&ctype=0"
[debug] Command-line config: ['-vU', '--ignore-config', 'https://space.bilibili.com/4947340/channel/seriesdetail?sid=549922&ctype=0']
[debug] Encodings: locale cp932, fs utf-8, pref cp932, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19044-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 2022-08-03-git-d3f48e68b3-full_build-www.gyan.dev (setts), ffprobe 2022-08-03-git-d3f48e68b3-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
Current Build Hash: 5590c57bd0433ed239a2deaaf92e2ad6f37fe50f53664c821575cafe106a9421
yt-dlp is up to date (stable@2023.03.04)
[generic] Extracting URL: https://space.bilibili.com/4947340/channel/seriesdetail?sid=549922&ctype=0
[generic] seriesdetail?sid=549922&ctype=0: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] seriesdetail?sid=549922&ctype=0: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://space.bilibili.com/4947340/channel/seriesdetail?sid=549922&ctype=0
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1518, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1594, in __extract_info
  File "yt_dlp\extractor\common.py", line 694, in extract
  File "yt_dlp\extractor\generic.py", line 2510, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://space.bilibili.com/4947340/channel/seriesdetail?sid=549922&ctype=0
```

**Comment by october262** [comment]
click the play all button, you see the word "official"on the right hand side of the webpage,  right click and copy link address the playlist will now download.

**Comment by dfgyuri** [comment]
the field with "official" is just a part of the channel name, it just links to the channel page which when fed to yt-dlp will only download videos under the video tab and not the series tab. 

for example feeding the main channel page https://space.bilibili.com/4947340 will only download 127 videos that are here https://space.bilibili.com/4947340/video but not the 190 which are here https://space.bilibili.com/4947340/channel/series

**Comment by c-basalt** [comment]
Currently, the extractor seems to support only collection playlists, which uses urls like:
- https://space.bilibili.com/84912/channel/collectiondetail?sid=923750

I think it would be nice if we can add support for playlist urls like:
- https://www.bilibili.com/list/4947340?sid=549922&desc=1&oid=400520796&bvid=BV18o4y1L75a
- https://space.bilibili.com/4947340/channel/seriesdetail?sid=549922&ctype=0
- https://space.bilibili.com/4947340/channel/series
