### ISSUE TITLE
[Hidive] Download all episodes of a show from its main URL

### ISSUE THREAD

**Issue by acc029** [yt-dlp/yt-dlp#6725]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a site-specific feature
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United States

### Example URLs

https://www.hidive.com/tv/ahiru-no-sora

### Provide a description that is worded well enough to be understood

yt-dlp can't use the main page of a show to download all the episodes linked from it, it can only use the generic extractor to download the trailer if it exists.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-u', 'PRIVATE', '-p', 'PRIVATE', '-vU', 'https://www.hidive.com/tv/ahiru-no-sora']
[debug] Encodings: locale cp932, fs utf-8, pref cp932, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2023.04.06.074452 [141a8dff9] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22000-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 5.0.1-full_build-www.gyan.dev (setts), ffprobe 5.0.1-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.1
[debug] Proxy map: {}
[debug] Loaded 1791 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Available version: nightly@2023.04.06.074452, Current version: nightly@2023.04.06.074452
Current Build Hash: 2e4ba37c2958203b7326e04fd2f73ee4cc326ea1ba863b53e4bf03ffb6d5d754
yt-dlp is up to date (nightly@2023.04.06.074452)
[generic] Extracting URL: https://www.hidive.com/tv/ahiru-no-sora
[generic] ahiru-no-sora: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] ahiru-no-sora: Extracting information
[debug] Looking for embeds
[debug] Identified a html5 embed
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] ahiru-no-sora-1: Downloading 1 format(s): 0
[debug] Invoking http downloader on "http://static.hidive.com/trailers/A/ANS_Action_Trailer_ForMix_NotFinal_1200x450_v2_PremiereCrop.mp4"
[debug] File locking is not supported. Proceeding without locking
[download] Destination: Stream Ahiru no Sora on HIDIVE (1) [ahiru-no-sora-1].mp4
[download] 100% of   53.10MiB in 00:00:14 at 3.73MiB/s
```

**Comment by quamt** [comment]
@acc029 
Are you downloading each episode one by one now?
I looked at the page. As a temporary workaround, you can copy the link from the first episode and check how many episodes there are.
Use any program that can handle tables, for example, OpenOffice etc.
Paste the link, drag and drop in the first column, and pull down until the episode count matches.
Copy into a txt file and use yt-dlp with batch downloading.

**Comment by Jules-A** [comment]
![image](https://github.com/yt-dlp/yt-dlp/assets/1760158/165ecad1-ad88-4ee7-913d-6386ba880651)

Just subbed to HiDive and found out there's no playlist extractor :(

I'm just doing this in a Tampermonkey script to get the season's urls: 
```
function commaKeyUp(e) {

    if (e.keyCode == 188) {
        let y = document.querySelectorAll('[data-playurl]');
        let toString = "";
        for (let i = 0; i < y.length; i++) {
            toString += "https://www.hidive.com/" + y[i].getAttribute("data-playurl") + "\n";
        }
        navigator.clipboard.writeText(toString.trim());
    }
}

document.addEventListener('keyup', commaKeyUp, false);
```

**Comment by bashonly** [comment]
Closing due to #9385
