### ISSUE TITLE
cannot download music album

### ISSUE THREAD

**Issue by superislam** [yt-dlp/yt-dlp#6743]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

cannot download music album Eminem - Musiv to be murdered by

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '-f', 'ba', '-x', '--audio-quality', '0', '--add-metadata', '--embed-thumbnail', '--convert-thumbnails', 'jpg', '--exec-before-download', 'ffmpeg -i %(thumbnails.-1.filepath)q -vf crop="\'if(gt(ih,iw),iw,ih)\':\'if(gt(iw,ih),ih,iw)\'" _%(thumbnails.-1.filepath)q', '--exec-before-download', 'del %(thumbnails.-1.filepath)q', '--exec-before-download', 'move _%(thumbnails.-1.filepath)q %(thumbnails.-1.filepath)q', '--output', '%(artist)s - %(title)s.%(ext)s', 'https://music.youtube.com/playlist?list=OLAK5uy_nF7ZsH9d0wbgH1jqzFHNvRp3MBKpBb2rw']
[debug] Encodings: locale cp1256, fs utf-8, pref cp1256, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19044-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 2022-11-03-git-5ccd4d3060-full_build-www.gyan.dev (setts), ffprobe 2022-11-03-git-5ccd4d3060-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
Current Build Hash: 5590c57bd0433ed239a2deaaf92e2ad6f37fe50f53664c821575cafe106a9421
yt-dlp is up to date (stable@2023.03.04)
[youtube:tab] Extracting URL: https://music.youtube.com/playlist?list=OLAK5uy_nF7ZsH9d0wbgH1jqzFHNvRp3MBKpBb2rw
WARNING: [youtube:tab] YouTube Music is not directly supported. Redirecting to https://www.youtube.com/playlist?list=OLAK5uy_nF7ZsH9d0wbgH1jqzFHNvRp3MBKpBb2rw
[youtube:tab] OLAK5uy_nF7ZsH9d0wbgH1jqzFHNvRp3MBKpBb2rw: Downloading webpage
WARNING: [youtube:tab] YouTube said: INFO - 20 unavailable videos are hidden
[youtube:tab] OLAK5uy_nF7ZsH9d0wbgH1jqzFHNvRp3MBKpBb2rw: Redownloading playlist API JSON with unavailable videos
[download] Downloading playlist: Album - Music To Be Murdered By
[debug] Skipping writing playlist thumbnail
[youtube:tab] Playlist Album - Music To Be Murdered By: Downloading 0 items of 20
[download] Finished downloading playlist: Album - Music To Be Murdered By
```

**Comment by pukkandan** [comment]
Can't reproduce:

```
❯ yt-dlp https://www.youtube.com/playlist?list=OLAK5uy_nF7ZsH9d0wbgH1jqzFHNvRp3MBKpBb2rw -v
[debug] Command-line config: ['--ignore-config', 'https://www.youtube.com/playlist?list=OLAK5uy_nF7ZsH9d0wbgH1jqzFHNvRp3MBKpBb2rw', '-v']
[debug] Encodings: locale cp65001, fs utf-8, pref cp65001, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (source)
[debug] Lazy loading extractors is disabled
[debug] Git HEAD: 68be95bd0
[debug] Python 3.11.0 (CPython AMD64 64bit) - Windows-10-10.0.22000-SP0 (OpenSSL 1.1.1q  5 Jul 2022)
[debug] exe versions: ffmpeg n5.1.2-8-g5746987bad-20221204 (fdk,setts), ffprobe N-109332-g45ab5307a6-20221201, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1791 extractors
[youtube:tab] Extracting URL: https://www.youtube.com/playlist?list=OLAK5uy_nF7ZsH9d0wbgH1jqzFHNvRp3MBKpBb2rw
[youtube:tab] OLAK5uy_nF7ZsH9d0wbgH1jqzFHNvRp3MBKpBb2rw: Downloading webpage
[youtube:tab] OLAK5uy_nF7ZsH9d0wbgH1jqzFHNvRp3MBKpBb2rw: Redownloading playlist API JSON with unavailable videos
[download] Downloading playlist: Album - Music To Be Murdered By
[youtube:tab] Playlist Album - Music To Be Murdered By: Downloading 20 items of 20
[download] Downloading item 1 of 20
[youtube] Extracting URL: https://www.youtube.com/watch?v=aQnC2O_-AZA
[youtube] aQnC2O_-AZA: Downloading webpage
[youtube] aQnC2O_-AZA: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
```

Did you remove some lines from your log?

**Comment by superislam** [comment]
> Can't reproduce:
> 
> ```
> ❯ yt-dlp https://www.youtube.com/playlist?list=OLAK5uy_nF7ZsH9d0wbgH1jqzFHNvRp3MBKpBb2rw -v
> [debug] Command-line config: ['--ignore-config', 'https://www.youtube.com/playlist?list=OLAK5uy_nF7ZsH9d0wbgH1jqzFHNvRp3MBKpBb2rw', '-v']
> [debug] Encodings: locale cp65001, fs utf-8, pref cp65001, out utf-8, error utf-8, screen utf-8
> [debug] yt-dlp version stable@2023.03.04 [392389b7d] (source)
> [debug] Lazy loading extractors is disabled
> [debug] Git HEAD: 68be95bd0
> [debug] Python 3.11.0 (CPython AMD64 64bit) - Windows-10-10.0.22000-SP0 (OpenSSL 1.1.1q  5 Jul 2022)
> [debug] exe versions: ffmpeg n5.1.2-8-g5746987bad-20221204 (fdk,setts), ffprobe N-109332-g45ab5307a6-20221201, phantomjs 2.1.1
> [debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
> [debug] Proxy map: {}
> [debug] Loaded 1791 extractors
> [youtube:tab] Extracting URL: https://www.youtube.com/playlist?list=OLAK5uy_nF7ZsH9d0wbgH1jqzFHNvRp3MBKpBb2rw
> [youtube:tab] OLAK5uy_nF7ZsH9d0wbgH1jqzFHNvRp3MBKpBb2rw: Downloading webpage
> [youtube:tab] OLAK5uy_nF7ZsH9d0wbgH1jqzFHNvRp3MBKpBb2rw: Redownloading playlist API JSON with unavailable videos
> [download] Downloading playlist: Album - Music To Be Murdered By
> [youtube:tab] Playlist Album - Music To Be Murdered By: Downloading 20 items of 20
> [download] Downloading item 1 of 20
> [youtube] Extracting URL: https://www.youtube.com/watch?v=aQnC2O_-AZA
> [youtube] aQnC2O_-AZA: Downloading webpage
> [youtube] aQnC2O_-AZA: Downloading android player API JSON
> [debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
> [debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
> [debug] Default format spec: bestvideo*+bestaudio/best
> ```
> 
> Did you remove some lines from your log?

![image](https://user-images.githubusercontent.com/26907307/230692024-38bf1f1d-2f0c-4d77-a057-a08692812148.png)
no

**Comment by pukkandan** [comment]
I just noticed a difference in our logs.

> WARNING: [youtube:tab] YouTube said: INFO - 20 unavailable videos are hidden

I don't have this. Are you sure the videos are available in your region?

**Comment by superislam** [comment]
> I just noticed a difference in our logs.
> 
> > WARNING: [youtube:tab] YouTube said: INFO - 20 unavailable videos are hidden
> 
> I don't have this. Are you sure the videos are available in your region?

yes 
![image](https://user-images.githubusercontent.com/26907307/230694343-d0f31e5c-8dbc-4ef3-8b53-562ba6897643.png)

**Comment by pukkandan** [comment]
hm.. what do you see if you go to https://www.youtube.com/playlist?list=OLAK5uy_nF7ZsH9d0wbgH1jqzFHNvRp3MBKpBb2rw in incognito?

**Comment by superislam** [comment]
> hm.. what do you see if you go to https://www.youtube.com/playlist?list=OLAK5uy_nF7ZsH9d0wbgH1jqzFHNvRp3MBKpBb2rw in incognito?

oh in the youtube(not music) it shows me hidden videos but its normal in music yt

**Comment by pukkandan** [comment]
As the first warning in your log says, we only redirect yt-music to youtube.com and don't directly support it. See pinned issues for the issue tracking this.

**Comment by superislam** [comment]
> As the first warning in your log says, we only redirect yt-music to youtube.com and don't directly support it. See pinned issues for the issue tracking this.

so no solution

**Comment by pahool** [comment]
Can someone provide a link to the pinned issue that is tracking this? I can't seem to find it.

**Comment by bashonly** [comment]
- https://github.com/yt-dlp/yt-dlp/issues/622

which is found in:
- https://github.com/yt-dlp/yt-dlp/issues/3766
