### ISSUE TITLE
How to speed up downloading long videos from any site using multiple connections

### ISSUE THREAD

**Issue by Rushikesh-Malave-175** [yt-dlp/yt-dlp#6745]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Yo . so, I was downloading a long video file from zee5 using ytdlp. the download speed is much slower that my bandwidth is capable of and its unstable too. 
so, is there a way to increase the download speed using multiple connection (using aria2c maybe?) Is there any way to specify the no. of connections for aria2c? (Maybe using --downloader-args?)

this was the code i used
yt-dlp -f 'bv*+wa' --downloader aria2c --merge-output-format mkv https://zee5.onelink.me/RlQq/7ub15e8f

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[generic] Extracting URL: https://zee5.onelink.me/RlQq/7ub15e8f
[generic] 7ub15e8f: Downloading webpage
[redirect] Following redirect to https://www.zee5.com/global/tv-shows/details/ramayan-jeevan-ka-aadhar/0-6-214/ramayan-episode-2-full-episode/0-1-49698?scheme_url=https://www.zee5.com&desktop_url=https://www.zee5.com/tvshows/details/ramayan-jeevan-ka-aadhar/0-6-214/ramayan-episode-2-full-episode/0-1-49698&source_caller=api&pid=SHARE_CTA_CONTENT_CONSUMPTION&is_retargeting=true&shortlink=7ub15e8f&deep_link_value=https%3A%2F%2Fwww.zee5.com%2Ftvshows%2Fdetails%2Framayan-jeevan-ka-aadhar%2F0-6-214%2Framayan-episode-2-full-episode%2F0-1-49698&af_channel=my_channel&c=SHARE_CTA_CONTENT_CONSUMPTION
[Zee5] Extracting URL: https://www.zee5.com/global/tv-shows/details/ramayan-jeevan-ka-aadhar/0-6-214/ramayan-episode-2-f..._CONTENT_CONSUMPTION
[Zee5] 0-1-49698: Downloading access token
[Zee5] 0-1-49698: Downloading JSON metadata
[Zee5] 0-1-49698: Downloading m3u8 information
[info] 0-1-49698: Downloading 1 format(s): 3222+audio_aac-हिन्दी
[hlsnative] Downloading m3u8 manifest
[hlsnative] Fragment downloads will be delegated to aria2c
[hlsnative] Total fragments: 429
[download] Destination: Ramayan - Episode 2 - Full Episode [0-1-49698].f3222.mp4
[download] 100% of  946.44MiB in 00:00:25 at 36.60MiB/s
[hlsnative] Downloading m3u8 manifest
[hlsnative] Fragment downloads will be delegated to aria2c
[hlsnative] Total fragments: 428
[download] Destination: Ramayan - Episode 2 - Full Episode [0-1-49698].faudio_aac-हिन्दी.mp4
[download] 100% of   20.68MiB in 00:00:08 at 2.44MiB/s
```

**Comment by Lesmiscore** [comment]
Answered in Discord, closing
