### ISSUE TITLE
How to fix "UnsupportedError" when downloading from login protected site?

### ISSUE THREAD

**Issue by alex4200** [yt-dlp/yt-dlp#6747]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Trying to download from the URL `https://video.prosieben.de/serien/germanys-next-topmodel-by-heidi-klum/videos/surprise-die-neuen-sind-da` I tried

`yt-dlp  -vUf 'bv+ba/b'  https://video.prosieben.de/serien/germanys-next-topmodel-by-heidi-klum/videos/surprise-die-neuen-sind-da`

and 

`yt-dlp  -vUf 'bv+ba/b' -u my.email@email.com -p MyPassword https://video.prosieben.de/serien/germanys-next-topmodel-by-heidi-klum/videos/surprise-die-neuen-sind-da`

but I get the error `UnsupportedError`.  I suspect the error is related to authentification (you have to login to watch the video), but unsure how to fix/workaround this problem.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vUf', 'bv+ba/b', '-u', 'PRIVATE', '-p', 'PRIVATE', 'https://video.prosieben.de/serien/germanys-next-topmodel-by-heidi-klum/videos/surprise-die-neuen-sind-da']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (pip)
[debug] Python 3.9.6 (CPython x86_64 64bit) - macOS-13.1-x86_64-i386-64bit (LibreSSL 2.8.3)
[debug] exe versions: ffmpeg 5.1.2 (setts), ffprobe 5.1.2
[debug] Optional libraries: Cryptodome-3.16.0, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
yt-dlp is up to date (stable@2023.03.04)
[generic] Extracting URL: https://video.prosieben.de/serien/germanys-next-topmodel-by-heidi-klum/videos/surprise-die-neuen-sind-da
[generic] surprise-die-neuen-sind-da: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] surprise-die-neuen-sind-da: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://video.prosieben.de/serien/germanys-next-topmodel-by-heidi-klum/videos/surprise-die-neuen-sind-da
Traceback (most recent call last):
  File "/Users/alex/Library/Python/3.9/lib/python/site-packages/yt_dlp/YoutubeDL.py", line 1518, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/alex/Library/Python/3.9/lib/python/site-packages/yt_dlp/YoutubeDL.py", line 1594, in __extract_info
    ie_result = ie.extract(url)
  File "/Users/alex/Library/Python/3.9/lib/python/site-packages/yt_dlp/extractor/common.py", line 694, in extract
    ie_result = self._real_extract(url)
  File "/Users/alex/Library/Python/3.9/lib/python/site-packages/yt_dlp/extractor/generic.py", line 2510, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://video.prosieben.de/serien/germanys-next-topmodel-by-heidi-klum/videos/surprise-die-neuen-sind-da
```

**Comment by gamer191** [comment]
log in with your browser, then use `--cookies-from-browser chrome` (replace chrome with the name of your browser)
By the way, the command you want is probably `-f bv*+ba/b` (the default, since you have ffmpeg installed)

**Comment by alex4200** [comment]
I tried using the `safari` browser, but I get the same error.

**Comment by bashonly** [comment]
`-u`/`-p` have no effect on the generic extractor; only a dedicated extractor will make use of credentials.

`--cookies-from-browser` or `--cookies` do have an effect, but the generic extractor will only be able to extract video if the site uses a standard method of embedding videos in the webpage HTML that yt-dlp knows to look for. This doesn't seem to be the case, so the error persists.

The problem is that the [prosieben extractor](https://github.com/yt-dlp/yt-dlp/blob/master/yt_dlp/extractor/prosiebensat1.py) needs to be fixed, since it is not recognizing the URL you're passing: 
#2010
#5593
