### ISSUE TITLE
Unable to extract uploader id

### ISSUE THREAD

**Issue by louisdoe** [yt-dlp/yt-dlp#6749]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Hey

I get this error "Unable to extract uploader id", whereas it seems to have been fixed in a previous release, when I run  : 
$ yt-dlp --extract-audio --audio-format mp3 -o "%(playlist_index)s%(title)s.%(ext)s" https://www.youtube.com/playlist?list=PL64A034E9B0579F97

my version is 
$ yt-dlp --version
2022.03.08.1

Linux

Thanks

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
$ yt-dlp -vU --extract-audio --audio-format mp3 -o "%(playlist_index)s%(title)s.%(ext)s" https://www.youtube.com/playlist?list=PL64A034E9B0579F97
[debug] Command-line config: ['-vU', '--extract-audio', '--audio-format', 'mp3', '-o', '%(playlist_index)s%(title)s.%(ext)s', 'https://www.youtube.com/playlist?list=PL64A034E9B0579F97']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, err utf-8, pref UTF-8
[debug] yt-dlp version 2022.03.08.1 [c0c2c57d3]
[debug] Python version 3.8.10 (CPython 64bit) - Linux-5.15.0-60-generic-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.7, ffprobe 4.2.7, rtmpdump 2.4
[debug] Optional libraries: brotli, Cryptodome, secretstorage, mutagen, sqlite, websockets
[debug] Proxy map: {}
Usage: yt-dlp [OPTIONS] URL [URL...]

yt-dlp: error: yt-dlp's self￼-update mechanism is disabled on Debian.
Please update yt-dlp using apt(8).
See https://packages.debian.org/sid/yt-dlp for the latest packaged version.
```

**Comment by Lesmiscore** [comment]
https://github.com/yt-dlp/yt-dlp/wiki/FAQ#the-yt-dlp-in-my-package-manager-is-outdatedbroken

**Comment by gartha1** [comment]
It looks to me like maybe ytdlp is completely broken and has been for maybe  since around March 2023.

I had a similar issue.

https://github.com/ytdl-org/youtube-dl/issues/31862

And as you can see it got a comment indicating that it has been asked before.

Maybe Youtube  made it harder to download videos by only offering a download option to subscribers and making it harder for people to download videos generally.

If this is the case, which I think it is,  then I think this could be better explained on the ytdlp readme page. Or as a sticky post on the issues forum if that's possible.

**Comment by gartha1** [comment]
@Lesmiscore    You suggest his package manager isn't getting the latest version, but didn't he say his version is  March 4th 2023, and that's the latest ytdlp release "[yt-dlp 2023.03.04]"

**Comment by bashonly** [comment]
the OP's version is over a year old
their linux distro's package is outdated
follow [the installation instructions on the wiki](https://github.com/yt-dlp/yt-dlp/wiki/Installation) to update
