### ISSUE TITLE
ServusTV, only slow download will be possible

### ISSUE THREAD

**Issue by Gloster10** [yt-dlp/yt-dlp#6752]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a site-specific feature
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Germany

### Example URLs

https://www.servustv.com/unterhaltung/v/aa-2732528sn2111/

https://www.pm-wissen.com/umwelt/v/aab9ybvtd957a17ctgb8/ (it is a link of ServusTV, but all other URL's of ServusTV with the same behaviour)

### Provide a description that is worded well enough to be understood

Use :Ubuntu Mate 22.04.03
The download time of a Film of 40min will be greater then 40 minutes, the audio part, if not pre merged will have the same download time.
I did check the transfer rate with the System-Monitor (Send/receive) and only approximately every 5-6
![Bildschirmfoto zu 2023-04-09 11-01-38](https://user-images.githubusercontent.com/87351612/230764306-b6e10709-0a3b-4dc5-af68-12bb6acf20fa.png)
sec there will be a Send/receive cycle.
Normally I have a download rate of 7MB/sec.

Please refer to the added picture, to see the transfer rate.

It is a minor issue, I can download the films over night.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '-f', 'hls-6092+hls-audio-stereo-aac-English', '-o', '%(title)s.%(ext)s', '--no-playlist', 'https://www.pm-wissen.com/umwelt/v/aab9ybvtd957a17ctgb8/']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d]
[debug] Lazy loading extractors is disabled
[debug] Python 3.10.6 (CPython x86_64 64bit) - Linux-5.15.0-69-generic-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, pyxattr-0.7.2, secretstorage-3.3.1, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1788 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
yt-dlp is up to date (stable@2023.03.04)
[Servus] Extracting URL: https://www.pm-wissen.com/umwelt/v/aab9ybvtd957a17ctgb8/
[Servus] AAB9YBVTD957A17CTGB8: Downloading video JSON
[Servus] AAB9YBVTD957A17CTGB8: Downloading m3u8 information
[Servus] AAB9YBVTD957A17CTGB8: Downloading JSON metadata
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[info] AAB9YBVTD957A17CTGB8: Downloading 1 format(s): hls-6092+hls-audio-stereo-aac-English
[debug] Invoking hlsnative downloader on "https://dms.redbull.tv/v5/dms/media/vod/stv/AAB9YBVTD957A17CTGB8/1920x1080@7139353/personal_computer/http/de/playlist.m3u8"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 116
[download] Destination: KI gegen Pflanzen？.fhls-6092.mp4
[download]  33.6% of ~ 243.86MiB at  343.63KiB/s ETA 07:12 (frag 39/116)^C
ERROR: Interrupted by user
```

**Comment by flashdagger** [comment]
Cannot confirm. Maybe server-side throttling?

**Comment by pukkandan** [comment]
Pls try with `-N`/`aria2c`

**Comment by Gloster10** [comment]
@pukkandan : I did try -N 8 (as I understand, number of possible threads). It works fine, now I get an average download rate at 2.95MiB/s.

**Comment by Gloster10** [comment]
An additional hint, perhaps superfluous, but the parameter "-N 8" speed up also the download on perhaps every side. 
I did test it, without -N 8 : at 5.55MiB/s and with "-N 8" to : at 6.86MiB/s, which It is my max. download rate (data file 3.6GB).
