### ISSUE TITLE
[Niconico] How to download Anime danmaku on Niconico?

### ISSUE THREAD

**Issue by Lywzc** [yt-dlp/yt-dlp#6760]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I am using the following command with my own username and password.
yt-dlp --write-info-json --get-comments --write-sub --all-subs --username <USERNAME> --password <PASSWORD> https://www.nicovideo.jp/watch/so42039588
However, the result comments.json is only several KBs with almost nothing in it. The video itself is correctly downloaded though.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--write-info-json', '--get-comments', '--write-sub', '--all-subs', '--username', 'PRIVATE', '--password', 'PRIVATE', 'https://www.nicovideo.jp/watch/so42039588']
[debug] Portable config "D:\Tools\yt-dlp.conf": ['-N', '8', '--proxy', 'socks5://127.0.0.1:8187/', '-R', '1000', '--file-access-retries', '10', '--fragment-retries', '1000', '--extractor-retries', '10']
[debug] Encodings: locale cp936, fs utf-8, pref cp936, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg git-2020-05-19-74dfc88, ffprobe git-2020-05-19-74dfc88
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {'http': 'socks5://127.0.0.1:8187/', 'https': 'socks5://127.0.0.1:8187/'}
[debug] Loaded 1786 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
Current Build Hash: 5590c57bd0433ed239a2deaaf92e2ad6f37fe50f53664c821575cafe106a9421
yt-dlp is up to date (stable@2023.03.04)
[niconico] Acquiring Login session
[niconico] Logging in
[niconico] Extracting URL: https://www.nicovideo.jp/watch/so42039588
[niconico] so42039588: Downloading webpage
[niconico] so42039588: Downloading comments
[info] so42039588: Downloading subtitles: comments
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] so42039588: Downloading 1 format(s): h264_360p-aac_64kbps-http
[info] Writing video subtitles to: ちびゴジラの逆襲 第1話「怪獣島のちびゴジラ」 [so42039588].comments.json
[info] Writing video metadata as JSON to: ちびゴジラの逆襲 第1話「怪獣島のちびゴジラ」 [so42039588].info.json
[debug] Invoking niconico_dmc downloader on "niconico_dmc:so42039588/archive_h264_360p/archive_aac_64kbps"
[niconico_dmc] Downloading from DMC
[niconico] so42039588: Downloading JSON metadata for h264_360p-aac_64kbps-http
[niconico] so42039588: Acquiring permission for downloading video
[niconico_dmc] Heartbeat with 40 second interval ...
[debug] File locking is not supported. Proceeding without locking
[download] Destination: ちびゴジラの逆襲 第1話「怪獣島のちびゴジラ」 [so42039588].mp4
[download] 100% of    8.25MiB in 00:01:04 at 130.84KiB/s
```

**Comment by Lesmiscore** [comment]
These comments are recognized as subtitles
Try `--write-sub --sub-lang comments`

**Comment by Lywzc** [comment]
> These comments are recognized as subtitles Try `--write-sub --sub-lang comments`
Still nothing is downloaded
[ちびゴジラの逆襲 第1話「怪獣島のちびゴジラ」 [so42039588].comments.zip](https://github.com/yt-dlp/yt-dlp/files/11199094/1.so42039588.comments.zip)
This is the resulting file.
However, it works for https://www.nicovideo.jp/watch/sm42014388 which is user uploaded.

**Comment by Lesmiscore** [comment]
Looks like these comments are served on a separate endpoint

**Comment by Lywzc** [comment]
> Looks like these comments are served on a separate endpoint

Then is this a bug? Should I open a new issue?

**Comment by Lesmiscore** [comment]
Nope, that's fine with this issue

**Comment by Lesmiscore** [comment]
From the next version, you'll see the comments from official anime with `--write-subs --sub-lang comments --sub-format json`
