### ISSUE TITLE
[DW] "An extractor error has occurred caused by KeyError('media_title')"

### ISSUE THREAD

**Issue by chrizilla** [yt-dlp/yt-dlp#6764]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that a **supported** site is broken
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

no geoblock (to my knowledge)

### Provide a description that is worded well enough to be understood

Video plays in browser, but yt-dlp doesn't find it.

URL:
https://p.dw.com/p/4JfQ6 redirects to https://www.dw.com/de/bleibt-das-covid-19-virus-in-unserem-k%C3%B6rper/av-63792798
Both URLs fail in yt-dlp.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**DW extractor doesn't find the video:**

```shell
yt-dlp https://p.dw.com/p/4JfQ6 --ignore-config -F -v
[debug] Command-line config: ['https://p.dw.com/p/4JfQ6', '--ignore-config', '-F', '-v']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
[generic] Extracting URL: https://p.dw.com/p/4JfQ6
[generic] 4JfQ6: Downloading webpage
[redirect] Following redirect to https://www.dw.com/de/bleibt-das-covid-19-virus-in-unserem-k%C3%B6rper/av-63792798
[dw] Extracting URL: https://www.dw.com/de/bleibt-das-covid-19-virus-in-unserem-k%C3%B6rper/av-63792798
[dw] 63792798: Downloading webpage
ERROR: 63792798: An extractor error has occurred. (caused by KeyError('media_title')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 694, in extract
  File "yt_dlp\extractor\dw.py", line 53, in _real_extract
KeyError: 'media_title'
```

**generic extractor also doesn't find the video:**
```shell
yt-dlp https://p.dw.com/p/4JfQ6 --ignore-config -F -v --use-extractors generic
[debug] Command-line config: ['https://p.dw.com/p/4JfQ6', '--ignore-config', '-F', '-v', '--use-extractors', 'generic']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1 extractors
[generic] Extracting URL: https://p.dw.com/p/4JfQ6
[generic] 4JfQ6: Downloading webpage
[redirect] Following redirect to https://www.dw.com/de/bleibt-das-covid-19-virus-in-unserem-k%C3%B6rper/av-63792798
[generic] Extracting URL: https://www.dw.com/de/bleibt-das-covid-19-virus-in-unserem-k%C3%B6rper/av-63792798
[generic] av-63792798: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] av-63792798: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://www.dw.com/de/bleibt-das-covid-19-virus-in-unserem-k%C3%B6rper/av-63792798
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1518, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1594, in __extract_info
  File "yt_dlp\extractor\common.py", line 694, in extract
  File "yt_dlp\extractor\generic.py", line 2510, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.dw.com/de/bleibt-das-covid-19-virus-in-unserem-k%C3%B6rper/av-63792798
```

### related issues

* #830
* #4944

**Comment by dirkf** [comment]
The extractor needs to target this HTML element in the non-JS page:
```html
<video-js
class="dw-player video-js vjs-fill"
preload="auto"
controls
playsinline
data-options='{ "setup": { "fluid": true, "liveui": true, "controlBar": { "children": [ "playToggle", "volumePanel", "progressControl", "remainingTimeDisplay", "seekToLive", "pictureInPictureToggle", "qualitySelector", "fullscreenToggle" ] }, "plugins": { "qualityLevels": {}, "hlsQualitySelector": { "displayCurrentQuality": true } }, "html5": { "nativeTextTracks": false } }, "translations": { }, "trackingInfo": { "duration": 169, "contentDate": "20221117", "mediaTitle": "Bleibt das Covid-19 Virus in unserem Körper?", "linkedTitle": "DW Nachrichten", "isLiveStream": false, "playerType": "video" } , "advertisement": { "adEnabled": false, "adTagUrl": "https://pubads.g.doubleclick.net/gampad/ads?iu=/228556409/DW_Videos&description_url={encodedDescriptionUrl}&url={encodedDescriptionUrl}&env=vp&impl=s&correlator=&tfcd=0&npa=0&gdfp_req=1&output=vast&sz=640x480|300x168&unviewed_position_start=1&cust_params=language%3Dde%26mediaId%3D63792798%26navigationIds%3D3230%26categories%3D19990007,19990033" }, "einbliqio": { "mediaId": "63792798", "mediaTitle": "Bleibt das Covid-19 Virus in unserem Körper?", "applicationVersion": "6.96.0" } }'
poster="https://tvdownloaddw-a.akamaihd.net/stills/images/c19de/c19de20221117_Koerper_image_1024x576_3.jpg"
>
<source src="https://hlsvod.dw.com/i/dwtv_video/flv/c19de/c19de20221117_Koerper_,AVC_1920x1080,AVC_1280x720,AVC_960x540,AVC_640x360,AVC_512x288,AVC_480x270,.mp4.csmil/master.m3u8" type="application/x-mpegURL" >
</video-js>
```
A change in the HTML5 extraction routine enables the generic extractor to handle this
```diff
-       _MEDIA_TAG_NAME_RE = r'(?:(?:amp|dl8(?:-live)?)-)?(video|audio)'
+       _MEDIA_TAG_NAME_RE = r'(?:(?:amp|dl8(?:-live)?)-)?(video(?:-js)?|audio)'
```
Alternatively the DW extractor could change `<video-js\b` to `<video\b` before running HTML5 extraction on the page, if the currently implemented tactics fail. Also, the DW extractor could be taught about the permalink URLs, like https://p.dw.com/p/4JfQ6, to avoid redirecting through the generic extractor, and to extract additional metadata from the attributes of the `<video-js>` element.

**Comment by bashonly** [comment]
> probably duplicate of #4944 ?

yep, same patch from dirkf even
