### ISSUE TITLE
Tiktok JSONDecoder, anyone wanna explain what broken?

### ISSUE THREAD

**Issue by zone559** [yt-dlp/yt-dlp#6766]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Before anyone closes the case, can someone explain what is causing the JSONDecoder issue? I want to understand what is going on so that I can try to figure out a solution or something. I don't know how to program, but I want to understand what is going on. If someone is willing to explain things, maybe I can gain some understanding of what is going on exactly.

I created something in Python using ChatGPT. It was able to pull the first 30 video IDs from a user's page, but I'm sure that's not the solution you were looking for. I don't know a way to scroll down to load more videos or anything like that. It seems that their API is always changing after "&bogusxxxxx&dsignatureXXXXX".

You guys are more knowledgeable than me, lol. I'm hoping you can help out a script kiddie like me.
[jsonz.zip](https://github.com/yt-dlp/yt-dlp/files/11196939/jsonz.zip)

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
py jsonz.py
{
    "ItemList": {
        "user-post": {
            "list": [
                "7213089010359504171",
                "7211565690644352299",
                "7210075193492901163",
                "7208338489413455150",
                "7208257341563637034",
                "7207555515981974830",
                "7206386216718191915",
                "7200103853415746862",
                "7199860888101211434",
                "7199814185159527722",
                "7199803365071555882",
                "7198261370897304875",
                "7195333639134137642",
                "7194846990650330410",
                "7194597232342043946",
                "7193457676028775723",
                "7190818743277112622",
                "7190093703703432494",
                "7187491377100393770",
                "7187135260516453678",
                "7185661715432983851",
                "7184499912527138090",
                "7181155506357275950",
                "7169014028428266794",
                "7167459637627784490",
                "7167058664824524075",
                "7166739668887751978",
                "7165608114039868714",
                "7165198296640802090",
                "7164531467605888298"
```

**Comment by bashonly** [comment]
the only way to get more than 30 results is via the API, and the web API has multiple security layers including fingerprinting

JSON parse error happens because the API is sending an empty response, which is what it does when the request fails to pass their security measures

see discussion in #3776, #4996
