### ISSUE TITLE
[youtube] 1080p Premium support

### ISSUE THREAD

**Issue by joaquinito2070** [yt-dlp/yt-dlp#6769]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Hello!!!
Check this official blog for the new feature:
https://blog.youtube/news-and-events/5-premium-features-to-up-your-youtube-game/
Thank you.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by Lesmiscore** [comment]
Someone tested that yt-dlp finds out these formats once you have Premium subscription. Period.

**Comment by joaquinito2070** [comment]
@Lesmiscore this has been added???

**Comment by joaquinito2070** [comment]
@Lesmiscore and I have Premium subscription.

**Comment by Lesmiscore** [comment]
https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp

**Comment by joaquinito2070** [comment]
but I tried and does not show me 1080p Premium @Lesmiscore

**Comment by Lesmiscore** [comment]
It depends on video
Not all videos have these formats

**Comment by joaquinito2070** [comment]
@Lesmiscore you have tried it???

**Comment by Lesmiscore** [comment]
No I don't have Premium
And don't ping me or I'll shut this issue

**Comment by joaquinito2070** [comment]
ok, sorry @Lesmiscore

**Comment by pukkandan** [comment]
If you can see the premium video format on youtube but not on yt-dlp with cookies for the same video, feel free to open a "broken site" report with relevant details
