### ISSUE TITLE
YouTube Live Broken

### ISSUE THREAD

**Issue by gildasio** [yt-dlp/yt-dlp#6771]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that a **supported** site is broken
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Brazil

### Provide a description that is worded well enough to be understood

When trying to get any information about an YouTube livestream it does not works anymore:

- A *not* livestream:

```
~> yt-dlp --print title 'https://www.youtube.com/watch?v=9vO_J8a0avo'
lofi hip hop radio ~ beats to relax/study to 💖 Lofi playlist for study, Relax, Stress Relief
```

- A livestream:

```
~> yt-dlp --print title 'https://www.youtube.com/watch?v=jfKfPfyJRdk'
WARNING: [youtube] Failed to download m3u8 information: <urlopen error [Errno 99] Cannot assign requested address>
WARNING: [youtube] Failed to download m3u8 information: <urlopen error [Errno 99] Cannot assign requested address>
ERROR: [youtube] jfKfPfyJRdk: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

I tested it using others livestreams as well. Also both videos are available in browser without login too.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
~> yt-dlp -vU --print title 'https://www.youtube.com/watch?v=jfKfPfyJRdk'
[debug] Command-line config: ['-vU', '--print', 'title', 'https://www.youtube.com/watch?v=jfKfPfyJRdk']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d]
[debug] Python 3.10.10 (CPython x86_64 64bit) - Linux-6.1.8-arch1-1-x86_64-with-glibc2.37 (OpenSSL 3.0.8 7 Feb 2023, glibc 2.37)
[debug] exe versions: ffmpeg 6.0 (setts), ffprobe 6.0, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.12.0, certifi-2022.12.07, secretstorage-3.3.3, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
yt-dlp is up to date (stable@2023.03.04)
[youtube] Extracting URL: https://www.youtube.com/watch?v=jfKfPfyJRdk
[youtube] jfKfPfyJRdk: Downloading webpage
[youtube] jfKfPfyJRdk: Downloading android player API JSON
[youtube] jfKfPfyJRdk: Downloading m3u8 information
WARNING: [youtube] Failed to download m3u8 information: <urlopen error [Errno 99] Cannot assign requested address>
[youtube] jfKfPfyJRdk: Downloading m3u8 information
WARNING: [youtube] Failed to download m3u8 information: <urlopen error [Errno 99] Cannot assign requested address>
ERROR: [youtube] jfKfPfyJRdk: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1518, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1615, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1674, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 2615, in process_video_result
    self.raise_no_formats(info_dict)
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1046, in raise_no_formats
    raise ExtractorError(msg, video_id=info['id'], ie=info['extractor'],
yt_dlp.utils.ExtractorError: [youtube] jfKfPfyJRdk: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

**Comment by pukkandan** [comment]
Can't reproduce. The error is coming from the network stack anyway. Could be issue with proxy/dns/firewall etc.

PS: If you only want title, `--ignore-no-formats` may help.

**Comment by gildasio** [comment]
Thanks @pukkandan , I'll try to reproduce it in others computers/network as well. Already tryied in another PC in my same network and the same problem happens.

Actually I want the url (`--print url` or `-g`), the title was just an example.

**Comment by gildasio** [comment]
Confirmed it is a network stack problem. Changed the network and it works.
I still need to find what is happening, but it's in my arm now.

Thanks @pukkandan
