### ISSUE TITLE
ERROR: Unsupported URL: https://www.youtube.com/playlist

### ISSUE THREAD

**Issue by vedanta28** [yt-dlp/yt-dlp#6772]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that a **supported** site is broken
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

India

### Provide a description that is worded well enough to be understood

`yt-dlp "https://youtube.com/playlist\?list\=PLyqSpQzTE6M-xymXgqewlzcC3U4cdRoSu" -I 33:41`

I am getting the following response after running the command above:
```
[generic] Extracting URL: https://youtube.com/playlist\?list\=PLyqSpQzTE6M-xymXgqewlzcC3U4cdRoSu
[generic] playlist\?list\=PLyqSpQzTE6M-xymXgqewlzcC3U4cdRoSu: Downloading webpage
[redirect] Following redirect to https://www.youtube.com/playlist%5C?list%5C=PLyqSpQzTE6M-xymXgqewlzcC3U4cdRoSu
[generic] Extracting URL: https://www.youtube.com/playlist%5C?list%5C=PLyqSpQzTE6M-xymXgqewlzcC3U4cdRoSu
[generic] playlist\?list\=PLyqSpQzTE6M-xymXgqewlzcC3U4cdRoSu: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] playlist\?list\=PLyqSpQzTE6M-xymXgqewlzcC3U4cdRoSu: Extracting information
ERROR: Unsupported URL:
```

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://youtube.com/playlist\\?list\\=PLyqSpQzTE6M-xymXgqewlzcC3U4cdRoSu', '-I', '33:41']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (pip)
[debug] Python 3.11.3 (CPython arm64 64bit) - macOS-13.3-arm64-arm-64bit (OpenSSL 1.1.1t  7 Feb 2023)
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
yt-dlp is up to date (stable@2023.03.04)
[generic] Extracting URL: https://youtube.com/playlist\?list\=PLyqSpQzTE6M-xymXgqewlzcC3U4cdRoSu
[generic] playlist\?list\=PLyqSpQzTE6M-xymXgqewlzcC3U4cdRoSu: Downloading webpage
[redirect] Following redirect to https://www.youtube.com/playlist%5C?list%5C=PLyqSpQzTE6M-xymXgqewlzcC3U4cdRoSu
[generic] Extracting URL: https://www.youtube.com/playlist%5C?list%5C=PLyqSpQzTE6M-xymXgqewlzcC3U4cdRoSu
[generic] playlist\?list\=PLyqSpQzTE6M-xymXgqewlzcC3U4cdRoSu: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] playlist\?list\=PLyqSpQzTE6M-xymXgqewlzcC3U4cdRoSu: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://www.youtube.com/playlist%5C?list%5C=PLyqSpQzTE6M-xymXgqewlzcC3U4cdRoSu
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/yt-dlp/2023.3.4/libexec/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1518, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/yt-dlp/2023.3.4/libexec/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1594, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/yt-dlp/2023.3.4/libexec/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 694, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/yt-dlp/2023.3.4/libexec/lib/python3.11/site-packages/yt_dlp/extractor/generic.py", line 2510, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.youtube.com/playlist%5C?list%5C=PLyqSpQzTE6M-xymXgqewlzcC3U4cdRoSu
```

**Comment by vedanta28** [comment]
It seems the problem was from my end. I recently switched to iTerm. It had a weird option `Terminal may enable paste bracketing` enabled by default, that caused some \ to appear at some places which broke down the link.

**Comment by pukkandan** [comment]
Your terminal is pasting in such a way that the quotes are not needed. So removing the quotes will also work instead of fixing the escapes.
