### ISSUE TITLE
Option to suppress 'advisory' warning messages

### ISSUE THREAD

**Issue by xpalidotious** [yt-dlp/yt-dlp#6785]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

I use yt-dlp to download YouTube videos via a custom script and almost always will download at least one audio stream in m4a format (usually format 140) which generates a warning message along the lines of:

WARNING: [video id]: writing DASH m4a. Only some players support this container

Now I'm perfectly happy with the way the program is operating, I actually want to save the audio in the original m4a format, I just don't want to have to see that unwanted 'advisory' warning on every single download.

I can't see any options relating to program verbosity or warning output that would suppress this unwanted advisory warning without potentially preventing other warning messages which may actually be relevant or important.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
Is `--fixup never` what you want?

**Comment by pukkandan** [comment]
> I just don't want to have to see that unwanted 'advisory' warning on every single download.
> 
> I can't see any options relating to program verbosity or warning output that would suppress this unwanted advisory warning without potentially preventing other warning messages which may actually be relevant or important.

It is not viable for us to provide that kind of granular control over the log. You can process the output with your own script to get desired output.

**Comment by Grub4K** [comment]
Output rework could do it, if wanted. Some sort of regex filter to exclude or something like "tutorial messages" that get a specific handling?

**Comment by xpalidotious** [comment]
> Is --fixup never what you want?

Not exactly, I'm currently using `--fixup warn` since I don't want the original audio to be modified but I'd still like to know if there were potential errors detected in the format. But if `--fixup never` will also prevent the warning I'm complaining about I'll certainly consider using it as the lesser of two evils.

> You can process the output with your own script to get desired output.

Yes I'd thought of that however I'm running under Windows which doesn't have true pipes so any such processing will prevent live console output from yt-dlp.

I guess I was hoping that warnings could be sorted into a few different categories that could be filtered with a user specified verbosity level and that one such category would include warnings that represent user advice only rather than actual errors or unexpected results.

Anyway I'll leave it with you as a possible consideration for the future since it's hardly an urgent issue :)

**Comment by pukkandan** [comment]
> Not exactly, I'm currently using `--fixup warn` since I don't want the original audio to be modified but I'd still like to know if there were potential errors detected in the format. But if `--fixup never` will also prevent the warning I'm complaining about I'll certainly consider using it as the lesser of two evils.

You want the warnings for fixup, but also don't want the warnings for fixup?? Are you perhaps trying to hide only specific fixup warnings while showing others?

All the fixup warnings would come under the "advisory warnings" category. So such a new categorization will not help you in that case. Only way for yt-dlp to support it natively is to allow using a 'regex based logging filter' like Grub4k suggested. I am not completely against the idea, but also not sure if such a feature is worth it.

**Comment by xpalidotious** [comment]
> Are you perhaps trying to hide only specific fixup warnings while showing others?

The only warning that I'd like to hide (that I'm aware of) is the specific warning mentioned in this thread. It's annoying enough to get one unnecessary warning every time you download a video but on some recent downloads I was saving 6 different audio formats and 5 of them were saved as m4a files that each gave a warning.

The warnings that I'd like to keep are when yt-dlp (or is it ffmpeg?) detects a "known fault" with the downloaded file but doesn't automatically try to fix it because I'm using `--fixup warn` rather than the default. Must admit I haven't seen any of these warnings in a long time but I used to get them fairly often in the past.

> All the fixup warnings would come under the "advisory warnings" category.

I suppose I just assumed that 'hey we've identified a known fault with the audio file you just downloaded' would come under a different category than 'the audio file you've just downloaded is in a less common format and some players won't be able to play it'.

Anyway for now I think I'll try using `--fixup never` as you suggested and if I want to detect any format faults I can always add some sort of additional check with ffmpeg.

**Comment by pukkandan** [comment]
> I suppose I just assumed that 'hey we've identified a known fault with the audio file you just downloaded' would come under a different category than 'the audio file you've just downloaded is in a less common format and some players won't be able to play it'.

All the fixups are just reading the file in ffmpeg and writing it back with a corrected container. So in case of any fixup, since ffmpeg can read it, some (theoretical) player will always be able to play it. Examples of other fixups are, correcting ts saved as mp4, correcting dts in aac, removing duplicate moov atom etc.
