### ISSUE TITLE
don't create corrupt files by default without explicit user consent (except for live streams)

### ISSUE THREAD

**Issue by chrizilla** [yt-dlp/yt-dlp#6794]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

I noticed that yt-dlp's current behaviour creates corrupt files with missing parts BY DEFAULT (i.e. without explicit user consent).

I don't think this is reasonable. The program should never create corrupt files without explicit user-consent. So this should not be the default behaviour out-of-the-box.

There are at least 2 scenarios (there might be more) where this occurs:

1.  **network connection error**: the default setting `--skip-unavailable-fragments` creates a file with missing parts
2.  **write error**: apparently this too triggers the default setting `--skip-unavailable-fragments` and creates a file with missing parts (example: [#6757](#6757))

With the possible exception of live streams, I think the majority of users want to download a 100% faithful copy of the video on the server. Other users agree [here](https://github.com/yt-dlp/yt-dlp/issues/6078#issuecomment-1415181159):
> _I doubt anyone ever wants to do this as it causes video/audio/subtitles to be out of sync._

So please take whatever steps are necessary to assure faithful downloads and avoid corrupt files with missing parts.

### related issues
* #3730 
* #6757
* #6793 
* #6078

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

Of the 2 abovementioned examples, a write error log is [here](https://github.com/yt-dlp/yt-dlp/issues/6757#issuecomment-1501349837) and I don't have a network connection error log handy.

**Comment by pukkandan** [comment]
As I have already explained in the linked issues, the default behavior is not going to be changed and you can simply use `--abort-on-unavailable-fragment`. Opening a new issue does not change my answer

**Comment by pukkandan** [comment]
FYI, Youtube VODs are expected to often have missing fragments.

**Comment by pukkandan** [comment]
> I created this issue BEFORE your [comment](https://github.com/yt-dlp/yt-dlp/issues/6757#issuecomment-1506136100) in which BTW you don't _"explain"_ why the default behaviour is not going to be changed. You merely said: _"Won't be done"_ without giving any explanation.

I thought I had already explained this before. If not, sorry. I might have been thinking of one of the other "change in default" that you have been recommending.


---

Rest is answered in https://github.com/yt-dlp/yt-dlp/issues/6757. Since that issue ha already devolved into a discussion on related points, let's pls keep everything there - at least till we come to a consensus.
