### ISSUE TITLE
mitigating the side effects of `--print`

### ISSUE THREAD

**Issue by chrizilla** [yt-dlp/yt-dlp#6796]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I would like to print to screen some stuff (information about the video) before downloading, but unfortunately this has some unwanted side effects: According to README, it forces both `--quiet` and `--simulate`.

Why is that ?

I am trying to mitigate these unwanted side effects by using `--no-simulate --no-quiet` but unfortunately the latter does not exist:
`yt-dlp: error: no such option: --no-quiet`

So I have to work around that some other way.

All I can do now is trying to make visible what `--quiet` hides.
I am missing the progress bar and have restored it via `--progress # Show progress bar, even if in quiet mode`.
But I don't know what else I am missing? Is there more?

I am bewildered that a simple print-to-screen command triggers such a cascade of unwanted side effects.

Why can't we just print something to screen without triggering so many heavy config changes ?

It really would be nice if `--print` would just do that: print something to screen.
All this other unrelated side-stuff could be controlled manually by explicitly setting the other parameters manually.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
> I am bewildered that a simple print-to-screen command triggers such a cascade of unwanted side effects.

`--print` is designed to do "print only this and do nothing else" by default similar to the options it replaces (`--get-title`, `--get-format`, `--get-url` etc) - hence the default. And, this is the way I have seen most people use it too.


> but unfortunately the latter does not exist:
> `yt-dlp: error: no such option: --no-quiet`

I will add it. For the time-being, use `--verbose` to reverse the `--quiet` (caveat being that it produces even more log)
