### ISSUE TITLE
[Niconico] Anime danmaku is still broken on Niconico

### ISSUE THREAD

**Issue by Lywzc** [yt-dlp/yt-dlp#6797]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that a **supported** site is broken
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Japan

### Provide a description that is worded well enough to be understood

After the previous issue, I updated the program to the newest Nightly and tried several times. Still no success. Below is the result file. And https://www.nicovideo.jp/watch/sm42014388 still works fine.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--write-subs', '--sub-lang', 'comments', '--sub-format', 'json', 'https://www.nicovideo.jp/watch/so42039588']
[debug] Portable config "D:\Tools\yt-dlp.conf": ['-N', '8', '--proxy', 'http://127.0.0.1:8188/', '-R', '1000', '--file-access-retries', '10', '--fragment-retries', '1000', '--extractor-retries', '10']
[debug] Encodings: locale cp936, fs utf-8, pref cp936, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2023.04.13.071052 [d1483ec69] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg git-2020-05-19-74dfc88, ffprobe git-2020-05-19-74dfc88
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.1
[debug] Proxy map: {'http': 'http://127.0.0.1:8188/', 'https': 'http://127.0.0.1:8188/'}
[debug] Loaded 1797 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Available version: nightly@2023.04.13.071052, Current version: nightly@2023.04.13.071052
Current Build Hash: 91885a766c0c2b76aed2664df7539036786829dafd87fa8cf66ec3ababb5fc35
yt-dlp is up to date (nightly@2023.04.13.071052)
[niconico] Extracting URL: https://www.nicovideo.jp/watch/so42039588
[niconico] so42039588: Downloading webpage
[niconico] so42039588: Downloading comments
[niconico] so42039588: Downloading comments (new)
[info] so42039588: Downloading subtitles: comments
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] so42039588: Downloading 1 format(s): h264_360p-aac_64kbps-http
[info] Writing video subtitles to: ちびゴジラの逆襲 第1話「怪獣島のちびゴジラ」 [so42039588].comments.json
[debug] Invoking niconico_dmc downloader on "niconico_dmc:so42039588/archive_h264_360p/archive_aac_64kbps"
[download] ちびゴジラの逆襲 第1話「怪獣島のちびゴジラ」 [so42039588].mp4 has already been downloaded
[download] 100% of    8.25MiB
```

**Comment by pukkandan** [comment]
> ```shell
> 
> [info] Writing video subtitles to: ちびゴジラの逆襲 第1話「怪獣島のちびゴジラ」 [so42039588].comments.json
> ```

It appears to have been downloaded?

**Comment by Lywzc** [comment]
[ちびゴジラの逆襲 第1話「怪獣島のちびゴジラ」 [so42039588].comments.zip](https://github.com/yt-dlp/yt-dlp/files/11221172/1.so42039588.comments.zip)
I forgot to include the result file.
The result is less than 1K while this episode has thousands of comments.

**Comment by pukkandan** [comment]
@Lesmiscore

**Comment by Lesmiscore** [comment]
I was forgetting that there are 2 threads for Japanese and English comments
Try with `--header accept-language:ja`, then I'll see all the comments downloaded

**Comment by Lywzc** [comment]
Usage: yt-dlp [OPTIONS] URL [URL...]

yt-dlp: error: no such option: --header

**Comment by Lesmiscore** [comment]
:facepalm: That's `--add-header`, sorry

**Comment by Lywzc** [comment]
Thanks. It now works! Why is it not default for Niconico though since almost all comments are in Japanese anyway.

**Comment by Lesmiscore** [comment]
Looks like it's getting easier with the new API, might worth working with it later
Closing as the OP's topic is resolved
