### ISSUE TITLE
[Broken] Pornhub playlist only download first 36 videos

### ISSUE THREAD

**Issue by snwefly** [yt-dlp/yt-dlp#680]
## Checklist

- [ ✅] I'm reporting a broken site support
- [ ✅] I've verified that I'm running yt-dlp version **2021.08.10**
- [ ✅] I've checked that all provided URLs are alive and playable in a browser
- [ ✅] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ ✅] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
yt-dlp -v https://www.pornhub.com/playlist/95816161
[debug] Command-line config: ['-v', 'https://www.pornhub.com/playlist/95816161']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] yt-dlp version 2021.08.10 (exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19042-SP0
[debug] exe versions: ffmpeg N-102564-g2261cc6d8a, ffprobe N-102564-g2261cc6d8a
[debug] Optional libraries: mutagen, pycryptodome, sqlite, websockets
[debug] Proxy map: {}
[debug] [PornHubPagedVideoList] Extracting URL: https://www.pornhub.com/playlist/95816161
[download] Downloading playlist: playlist/95816161
[PornHubPagedVideoList] playlist/95816161: Downloading page 1
[PornHubPagedVideoList] playlist playlist/95816161: Downloading 36 videos
[download] Downloading video 1 of 36
[debug] [PornHub] Extracting URL: http://www.pornhub.com/view_video.php?viewkey=ph5c0a6ab9a71b1&pkey=95816161
[PornHub] ph5c0a6ab9a71b1: Downloading pc webpage
[PornHub] ph5c0a6ab9a71b1: Downloading JSON metadata
[PornHub] ph5c0a6ab9a71b1: Downloading m3u8 information
[PornHub] ph5c0a6ab9a71b1: Downloading m3u8 information
[PornHub] ph5c0a6ab9a71b1: Downloading m3u8 information
[PornHub] ph5c0a6ab9a71b1: Downloading m3u8 information
[PornHub] ph5c0a6ab9a71b1: Downloading m3u8 information
```

## Description

yt-dlp scrap only the first 36 videos from pornhub playlists, this issue on the youtube-dl as well, let's hope someone fix it on this fork.

Thanks

**Comment by zackmark29** [comment]
Isn't 1 video enough? haha JK

**Comment by snwefly** [comment]
> 1 video Isn't enough? haha JK

Lots of videos and channels goes down everyday so it's better to backup them for educational purposes 😜

**Comment by github-userx** [comment]
@snwefly On a different Note, do you have made experiences with ytdlp and 1080p downloads from PornHub? I always used yt-dl and in the past 6 months YouTube-dl often downloaded only the 720p version of videos that were available in 1080p on PornHub. I had to first use -F and find the specific version which I then had to use with the -f flag, something like: -f hls-5321-1080p   But for another video it then would be something like hls-8913-1080p

**Comment by github-userx** [comment]
To add to my original comment: I am not a programmer and can’t code but i assume this particular ytdlp commit fixed the 720p/1080p resolution issue with the PornHub extractor? https://github.com/yt-dlp/yt-dlp/blob/master/yt_dlp/extractor/pornhub.py
