### ISSUE TITLE
this channel does not have a video tab - but it exists 

### ISSUE THREAD

**Issue by estatistics** [yt-dlp/yt-dlp#6800]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

https://www.youtube.com/@Dior/videos

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp  -vU --cookies-from-browser firefox https://www.youtube.com/@Dior/videos
[debug] Command-line config: ['-vU', '--cookies-from-browser', 'firefox', 'https://www.youtube.com/@Dior/videos']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (debian*)
[debug] Python 3.11.2 (CPython x86_64 64bit) - Linux-5.11.0-18-generic-x86_64-with-glibc2.36 (OpenSSL 3.0.8 7 Feb 2023, glibc 2.36)
[debug] exe versions: ffmpeg 5.1.2-3 (setts), ffprobe 5.1.2-3, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.11.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.46.0, pyxattr-0.8.0, secretstorage-3.3.3, sqlite3-2.6.0, websockets-10.4
[Cookies] Extracting cookies from firefox
[debug] Extracting cookies from: "/home/elias/.mozilla/firefox/jafshm4s.default-esr-2/cookies.sqlite"
[Cookies] Extracted 5114 cookies from firefox
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
yt-dlp is up to date (stable@2023.03.04)
[youtube:tab] Extracting URL: https://www.youtube.com/@Dior/videos
[youtube:tab] @Dior/videos: Downloading webpage
[debug] [youtube:tab] Selected tab: 'featured' (home), Requested tab: 'videos'
ERROR: [youtube:tab] @Dior: This channel does not have a videos tab
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/common.py", line 694, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/youtube.py", line 4438, in wrapper
    info_dict = func(self, url, smuggled_data)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/yt_dlp/extractor/youtube.py", line 6264, in _real_extract
    raise ExtractorError(f'This channel does not have a {original_tab_id} tab', expected=True)
```

**Comment by bashonly** [comment]
This is due to a bug in youtube's backend with the new `@handle` URLs.

See description of issue: https://github.com/yt-dlp/yt-dlp/issues/6305#issuecomment-1437438120

Same problem is happening here: the site redirects `/@Dior/videos` to `/user/dior/home/videos`, which is not valid

workaround:
get the `channel_url` from one of the channel's videos
```bash
$ yt-dlp -O channel_url "https://www.youtube.com/watch?v=ftWdAeIZFIQ"
https://www.youtube.com/channel/UC6xD-jKli-_qIYXDTsNv4dw
```
then you can append `/videos` to it:
```
yt-dlp "https://www.youtube.com/channel/UC6xD-jKli-_qIYXDTsNv4dw/videos"
```
