### ISSUE TITLE
How to name Files with Channel Name and Video Title?

### ISSUE THREAD

**Issue by heirofsihgma** [yt-dlp/yt-dlp#6801]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [x] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

How can I use yt-dlp to create video/audio files with the following name format:

Channel Name - Video Title

I am sorry, I have tried but I am really not good with coding, at all.
Some help would be greatly appreciated.

P.S: I don't want folders, just the individual file names, that's all.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
This will work if you are downloading from youtube:
`yt-dlp -o "%(channel)s - %(title)s.%(ext)s" "URL"`

(replace `URL` with the actual URL you want to download)

But each site's extractor uses the metadata fields differently, so `channel` may not be what you want to use for another site, e.g. tiktok

The relevant sections of the README:
https://github.com/yt-dlp/yt-dlp#output-template
https://github.com/yt-dlp/yt-dlp#output-template-examples

**Comment by heirofsihgma** [comment]
> This will work if you are downloading from youtube: `yt-dlp -o "%(channel)s - %(title)s.%(ext)s" "URL"`
> 
> (replace `URL` with the actual URL you want to download)
> 
> But each site's extractor uses the metadata fields differently, so `channel` may not be what you want to use for another site, e.g. tiktok
> 
> The relevant sections of the README: https://github.com/yt-dlp/yt-dlp#output-template https://github.com/yt-dlp/yt-dlp#output-template-examples

Hey thanks! That worked like a charm!

I use this command to download several videos and convert them in MP3 files:

`yt-dlp -o "%(channel)s - %(title)s.%(ext)s" -x --audio-format mp3 youtubeurl`

Works with both single videos and playlists alike.
Thanks a lot!
