### ISSUE TITLE
Is it possible  post process a video formats by youtube prior to download using flags like --postprocessing without ffmpeg or any other converter?

### ISSUE THREAD

**Issue by blockbabak** [yt-dlp/yt-dlp#6802]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I came across a flag   "--post-processing"
I want to do this after downloading using ffmpeg or an aconvertor.
Is this possible, i.e. youtube reformat videos with ma4 audio dec to put them in MKV jacket and then download them, rader that transcoding  the m40

I will be most grateful for a prompt response

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by blockbabak** [comment]
[Is it possible post process a video formats by youtube prior to download using flags like --postprocessing without ffmpeg or any other converter?](https://github.com/yt-dlp/yt-dlp/issues/6802#top)
#6802
[blockbabak](https://github.com/blockbabak)

I had to change the question because your interpreter said with ffmpeg....., when I had said without.

the ultimate mission is to download those who don't fit in Webm like the ones with m4a audio codec in 'NKV'

**Comment by blockbabak** [comment]
> [Is it possible post process a video formats by youtube prior to download using flags like --postprocessing without ffmpeg or any other converter?](https://github.com/yt-dlp/yt-dlp/issues/6802#top) #6802 [blockbabak](https://github.com/blockbabak)
> 
> I had to change the question because your interpreter said with ffmpeg....., when I had said without.
> 
> The ultimate mission is to download those who don't fit in Webm like the ones with m4a audio codec in 'MKV'

Why blockBaback?

**Comment by blockbabak** [comment]
I had filled the because you interpreter got it wrong and I get blocked

**Comment by blockbabak** [comment]
I had filled the damn templates.
You are blind or a liar.
I understand that I will be blocked if I intentionally remove or skip any mandatory* field
Checklist
 I'm asking a question and not reporting a bug or requesting a feature
 I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
 I've verified that I'm running yt-dlp version 2023.03.04 ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
 I've searched https://github.com/yt-dlp/yt-dlp/issues/3766 and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions including closed ones. DO NOT post duplicates
 I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

**Comment by bashonly** [comment]
Without ffmpeg or another external program, no it is not possible to convert to mkv.

`yt-dlp --remux-video mkv --merge-output-format mkv "URL"` will do what you want *with* ffmpeg. It will remux the download to mkv *without* re-encoding.

**Comment by blockbabak** [comment]
So what is –postprcessing flag is for?

**Comment by blockbabak** [comment]
Or this one:

 

-remux-video FORMAT            Remux the video into another container if

                                necessary (currently supported: avi, flv,

                                gif, mkv, mov, mp4, webm, aac, aiff, alac,

                                flac, m4a, mka, mp3, ogg, opus, vorbis,

                                wav). If target container does not support

                                the video/audio codec, remuxing will fail.

                                You can specify multiple rules; e.g.

                                "aac>m4a/mov>mp4/mkv" will remux aac to m4a,

                                mov to mp4 and anything else to mkv

**Comment by pukkandan** [comment]
> So what is –postprcessing flag is for?

There is no such switch

> Is this possible, i.e. youtube reformat videos with ma4 audio dec to put them in MKV jacket and then download them, rader that transcoding the m40

No, we obviously cannot modify the file **before** downloading them!

**Comment by blockbabak** [comment]
I copied that direct from Github. So, it must have some formats.

At least clarify it because I swear that there is such a thing. 

I can send you a screen shot if you want. But a simple search on you part could prove that it is real along with other things that indicated ability of motorcading. There is definitely not need to keep copy of them.


And on your hypothetic reasoning but why then why does Youtube keep in so many formats?

could you actually explain what postprocessing exists.

**Comment by blockbabak** [comment]
I am happy with transcoding.

**Comment by pukkandan** [comment]
I do not understand your question or the follow ups clearly, possibly due to a language barrier. https://github.com/yt-dlp/yt-dlp/issues/6802#issuecomment-1507967617 was the answer for my best attempt at interpreting your question. But your following comments are making less and less sense to me. Sorry I will not be able to help you.

**Comment by dirkf** [comment]
Is some short "Operational Overview" is needed in the documentation (yt-dl too)? Terms like `extractor` and `postprocessor` are used without really being defined. This might help with problems like OP's, which TBH seemed to answered by [bashonly](https://github.com/yt-dlp/yt-dlp/issues/6802#issuecomment-1507854500).

An overview could cover the flow through Extraction, Core Processing (playlist recursion, format selection, output pathname construction), Downloading, and Postprocessing. This could clarify that, except for placing fragment-based streams in a file container, media transformations rely on postprocessing with _ffmpeg_ or other external programs.
