### ISSUE TITLE
(url not supported) [generic] None: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403:

### ISSUE THREAD

**Issue by mrkapqa** [yt-dlp/yt-dlp#6807]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

hello ,

getting error with yt-dlp,
can you please tell me where the error lies'?

thanks!

`[generic] Extracting URL: https://rr2---sn-4g5e6nss.googlevideo.com/videoplayback?expire=1681521561
[generic] videoplayback?expire=1681521561: Downloading webpage
ERROR: [generic] None: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
`

the url provided is

`yt-dlp https://rr2---sn-4g5e6nss.googlevideo.com/videoplayback?expire=1681521561&ei=Oac5ZO_DC92jgQfIvYLQBA&ip=2a0d%3A3344%3A1b58%3Aa200%3A7c05%3Aefd%3A5169%3Aab03&id=o-AI7gHy1FXqDKhaTLG0caU8BJd3p3ADPBH3GutFX398X_&itag=22&source=youtube&requiressl=yes&mh=a3&mm=31%2C26&mn=sn-4g5e6nss%2Csn-f5f7kn7z&ms=au%2Conr&mv=m&mvi=2&pl=42&initcwndbps=692500&spc=99c5CSd2g2D6OWYAjGPSMTk5a30qNffTFz3gP3PcHw&vprv=1&mime=video%2Fmp4&ns=6aGMmdy5V6CLYgipeKbcDOoM&cnr=14&ratebypass=yes&dur=5229.226&lmt=1681071615497209&mt=1681499574&fvip=3&fexp=24007246&c=WEB&txp=5318224&n=4j70U_2kyDCa5w&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Cmime%2Cns%2Ccnr%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRAIgJgFWtj-XINQOyAJEYLCbxG5KxfPiGvhH9_Q7b2lbxQACIGZ3yROdzTYkC5y35wxU_jTqE7hvptuO2zVQC9RyLBVl&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAJnEKSvOajF3ufwomcQKvWIwkKYeK98GujtDl0OPV3o1AiEA6vJxqyhAXJ4r-sHMyaqjunfmMpCxJCDFDamAxRkaWu4%3D

`

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://rr2---sn-4g5e6nss.googlevideo.com/videoplayback?expire=1681521561']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (zip)
[debug] Python 3.8.10 (CPython x86_64 64bit) - Linux-5.4.0-146-generic-x86_64-with-glibc2.29 (OpenSSL 1.1.1f  31 Mar 2020, glibc 2.31)
[debug] exe versions: ffmpeg 4.2.7, ffprobe 4.2.7, rtmpdump 2.4
[debug] Optional libraries: Crypto-broken 2.6.1, certifi-2019.11.28, pyxattr-0.6.1, secretstorage-2.3.1, sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
Current Build Hash: 91cad9f121c1f6f0a81b747415c46ecba0ff331ed38cc6433040b4ac7b6e15ca
yt-dlp is up to date (stable@2023.03.04)
[generic] Extracting URL: https://rr2---sn-4g5e6nss.googlevideo.com/videoplayback?expire=1681521561
[generic] videoplayback?expire=1681521561: Downloading webpage
ERROR: [generic] None: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 694, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/generic.py", line 2371, in _real_extract
    full_response = self._request_webpage(url, video_id, headers={
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 839, in _request_webpage
    raise ExtractorError(errmsg, cause=err)

  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 821, in _request_webpage
    return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query))
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3742, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

**Comment by pukkandan** [comment]
Quote the URL

**Comment by mrkapqa** [comment]
qutoing the URL leads to another error message

`[generic] None: '“https://rr2---sn-4g5e6nss.googlevideo.com/videoplayback?expire=1681521561' is not a valid URL. Set --default-search "ytsearch" (or run  yt-dlp "ytsearch:“https://rr2---sn-4g5e6nss.googlevideo.com/videoplayback?expire=1681521561" ) to search YouTube`

**Comment by bashonly** [comment]
the leading quote you used was `“`, which is the unicode "left double quotation mark" (`U+201C`)

just use plain ascii quotes, `"`

**Comment by bennettjw** [comment]
Experienced same 403 error this morning. I ran into an identical problem with (https://github.com/Nandaka/PixivUtil2). The solution to both was adding: --user-agent "Mozilla/5.0"
Use only "Mozilla/5.0" as user-agent.

**Comment by mrkapqa** [comment]
thank, but this would not function nvtlss,

even with user-agent as suggested,


`yt-dlp --user-agent "Mozilla/5.0" "https://rr2---sn-4g5e6nss.googlevideo.com/videoplayback?expire=1681521561&ei=Oac5ZO_DC92jgQfIvYLQBA&ip=2a0d%3A3344%3A1b58%3Aa200%3A7c05%3Aefd%3A5169%3Aab03&id=o-AI7gHy1FXqDKhaTLG0caU8BJd3p3ADPBH3GutFX398X_&itag=22&source=youtube&requiressl=yes&mh=a3&mm=31%2C26&mn=sn-4g5e6nss%2Csn-f5f7kn7z&ms=au%2Conr&mv=m&mvi=2&pl=42&initcwndbps=692500&spc=99c5CSd2g2D6OWYAjGPSMTk5a30qNffTFz3gP3PcHw&vprv=1&mime=video%2Fmp4&ns=6aGMmdy5V6CLYgipeKbcDOoM&cnr=14&ratebypass=yes&dur=5229.226&lmt=1681071615497209&mt=1681499574&fvip=3&fexp=24007246&c=WEB&txp=5318224&n=4j70U_2kyDCa5w&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Cmime%2Cns%2Ccnr%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRAIgJgFWtj-XINQOyAJEYLCbxG5KxfPiGvhH9_Q7b2lbxQACIGZ3yROdzTYkC5y35wxU_jTqE7hvptuO2zVQC9RyLBVl&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAJnEKSvOajF3ufwomcQKvWIwkKYeK98GujtDl0OPV3o1AiEA6vJxqyhAXJ4r-sHMyaqjunfmMpCxJCDFDamAxRkaWu4%3D" 

[generic] Extracting URL: https://rr2---sn-4g5e6nss.googlevideo.com/videoplayback?expire=1681521561&ei=Oac5ZO_DC92jgQfIvYLQ...CxJCDFDamAxRkaWu4%3D
[generic] videoplayback?expire=1681521561&ei=Oac5ZO_DC92jgQfIvYLQBA&ip=2a0d:3344:1b58:a200:7c05:efd:5169:ab03&id=o-AI7gHy1FXqDKhaTLG0caU8BJd3p3ADPBH3GutFX398X_&itag=22&source=youtube&requiressl=yes&mh=a3&mm=31,26&mn=sn-4g5e6nss,sn-f5f7kn7z&ms=au,onr&mv=m&mvi=2&pl=42&initcwndbps=692500&spc=99c5CSd2g2D6OWYAjGPSMTk5a30qNffTFz3gP3PcHw&vprv=1&mime=video/mp4&ns=6aGMmdy5V6CLYgipeKbcDOoM&cnr=14&ratebypass=yes&dur=5229: Downloading webpage
ERROR: [generic] None: Unable to download webpage: **HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>**); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U`

**Comment by bashonly** [comment]
> videoplayback?**expire=1681521561**

```bash
$ date -u -d@1681521561
Sat Apr 15 01:19:21 AM UTC 2023

$ date -u
Sat Apr 15 03:05:39 PM UTC 2023
```

the URL expired over 12 hours ago. you'll need to fetch a new one from youtube

**Comment by mrkapqa** [comment]
thank you very much for the help,

with updated link getting another error

`yt-dlp "https://rr2---sn-4g5lznls.googlevideo.com/videoplayback?expire=1681690683&ei=2zs8ZLr6BtPF1gL-opyACQ&ip=2a0d%3A3344%3A1b58%3Aa200%3Adcaa%3Ad20%3Ac11e%3Ac8a5&id=o-AIpbFk4wDX16ZXSMu4Fuv-2qFCmBMtJqPPTUWVsDzqwl&itag=22&source=youtube&requiressl=yes&mh=jD&mm=31%2C29&mn=sn-4g5lznls%2Csn-4g5edn6r&ms=au%2Crdu&mv=m&mvi=2&pl=42&initcwndbps=805000&spc=99c5CeBSB-DRqCTKOCZCVYo4JgVU6C3BGuxO3dQCtg&vprv=1&mime=video%2Fmp4&ns=bQGimaAT9vhDMeoHiKcbOKUM&cnr=14&ratebypass=yes&dur=3097.797&lmt=1681645662949386&mt=1681668772&fvip=2&fexp=24007246&c=WEB&txp=5432434&n=VuW6VLXUb1bo0w&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Cmime%2Cns%2Ccnr%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRQIgYETXZbw_nz6lwcssK7IHprZkwFFqOEtiiFAkLXMYTlMCIQDMqRjmL7GnFxE8ec3_chxVu0fWd3mLk5kwTNc_0wr7kA%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhANfPAxBVHXuZOXTmOBrIKpaBJq33WHuzysshV9eSR1cTAiBx0UEhKnfUoICSFBUYOgvmVm6FaK4K1W8WJrjE3SiBNQ%3D%3D"
[generic] Extracting URL: https://rr2---sn-4g5lznls.googlevideo.com/videoplayback?expire=1681690683&ei=2zs8ZLr6BtPF1gL-opyA...1W8WJrjE3SiBNQ%3D%3D
[generic] videoplayback?expire=1681690683&ei=2zs8ZLr6BtPF1gL-opyACQ&ip=2a0d:3344:1b58:a200:dcaa:d20:c11e:c8a5&id=o-AIpbFk4wDX16ZXSMu4Fuv-2qFCmBMtJqPPTUWVsDzqwl&itag=22&source=youtube&requiressl=yes&mh=jD&mm=31,29&mn=sn-4g5lznls,sn-4g5edn6r&ms=au,rdu&mv=m&mvi=2&pl=42&initcwndbps=805000&spc=99c5CeBSB-DRqCTKOCZCVYo4JgVU6C3BGuxO3dQCtg&vprv=1&mime=video/mp4&ns=bQGimaAT9vhDMeoHiKcbOKUM&cnr=14&ratebypass=yes&dur=3097: Downloading webpage
[info] videoplayback?expire=1681690683&ei=2zs8ZLr6BtPF1gL-opyACQ&ip=2a0d:3344:1b58:a200:dcaa:d20:c11e:c8a5&id=o-AIpbFk4wDX16ZXSMu4Fuv-2qFCmBMtJqPPTUWVsDzqwl&itag=22&source=youtube&requiressl=yes&mh=jD&mm=31,29&mn=sn-4g5lznls,sn-4g5edn6r&ms=au,rdu&mv=m&mvi=2&pl=42&initcwndbps=805000&spc=99c5CeBSB-DRqCTKOCZCVYo4JgVU6C3BGuxO3dQCtg&vprv=1&mime=video/mp4&ns=bQGimaAT9vhDMeoHiKcbOKUM&cnr=14&ratebypass=yes&dur=3097: Downloading 1 format(s): fmp4
**ERROR: unable to open for writing: [Errno 36] File name too long:** 'videoplayback [videoplayback？expire=1681690683&ei=2zs8ZLr6BtPF1gL-opyACQ&ip=2a0d：3344_1b58：a200：dcaa：d20：c11e：c8a5&id=o-AIpbFk4wDX16ZXSMu4Fuv-2qFCmBMtJqPPTUWVsDzqwl&itag=22&source=youtube&requiressl=yes&mh=jD&mm=31,29&mn=sn-4g5lznls,sn-4g5edn6r&ms=au,rdu&mv=m&mvi=2&pl=42&initcwndbps=805000&spc=99c5CeBSB-DRqCTKOCZCVYo4JgVU6C3BGuxO3dQCtg&vprv=1&mime=video⧸mp4&ns=bQGimaAT9vhDMeoHiKcbOKUM&cnr=14&ratebypass=yes&dur=3097].unknown_video.part'
`

**Comment by bashonly** [comment]
> [Errno 36] File name too long

use `--output` or `-o` to specify an output template / shorter filename, e.g.:
`yt-dlp -o "%(epoch)s.%(ext)s" "URL"`

**Comment by mrkapqa** [comment]
well, thanks, this has worked out,
but download is unusually slow , as if with youtube-dl, only around 50kbps;
can live with that, but its not optimal.

**Comment by bashonly** [comment]
try adding `--http-chunk-size 10M`

**Comment by pukkandan** [comment]
Why are you doing it like this anyway?
