### ISSUE TITLE
How to create video fact sheets ?

### ISSUE THREAD

**Issue by chrizilla** [yt-dlp/yt-dlp#6808]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I use `--print-to-file` to create a [fact sheet](https://github.com/yt-dlp/yt-dlp/issues/2372#issuecomment-1019576344) for each downloaded video.

Is there currently any more efficient way to achieve this than repeating the "really-long-filename-template" over and over ?

```
--print-to-file "title:                  %(title)s" ".\%(playlist|)s\%(playlist_index|)02d%(playlist_index& = |)s%(release_date>%Y-%m-%d,release_timestamp>%Y-%m-%d,upload_date>%Y-%m-%d,timestamp>%Y-%m-%d|#nodate#)s %(alt_title,title)s\!nfo\%(title)s [%(extractor)s.%(extractor_key)s.%(id)s] [%(format_id)s].factsheet.nfo"
--print-to-file "fulltitle:              %(fulltitle)s" ".\%(playlist|)s\%(playlist_index|)02d%(playlist_index& = |)s%(release_date>%Y-%m-%d,release_timestamp>%Y-%m-%d,upload_date>%Y-%m-%d,timestamp>%Y-%m-%d|#nodate#)s %(alt_title,title)s\!nfo\%(title)s [%(extractor)s.%(extractor_key)s.%(id)s] [%(format_id)s].factsheet.nfo"
--print-to-file "alt_title:              %(alt_title)s" ".\%(playlist|)s\%(playlist_index|)02d%(playlist_index& = |)s%(release_date>%Y-%m-%d,release_timestamp>%Y-%m-%d,upload_date>%Y-%m-%d,timestamp>%Y-%m-%d|#nodate#)s %(alt_title,title)s\!nfo\%(title)s [%(extractor)s.%(extractor_key)s.%(id)s] [%(format_id)s].factsheet.nfo"
--print-to-file "format:                 %(format)s" ".\%(playlist|)s\%(playlist_index|)02d%(playlist_index& = |)s%(release_date>%Y-%m-%d,release_timestamp>%Y-%m-%d,upload_date>%Y-%m-%d,timestamp>%Y-%m-%d|#nodate#)s %(alt_title,title)s\!nfo\%(title)s [%(extractor)s.%(extractor_key)s.%(id)s] [%(format_id)s].factsheet.nfo"
--print-to-file "vcodec:                 %(vcodec)s" ".\%(playlist|)s\%(playlist_index|)02d%(playlist_index& = |)s%(release_date>%Y-%m-%d,release_timestamp>%Y-%m-%d,upload_date>%Y-%m-%d,timestamp>%Y-%m-%d|#nodate#)s %(alt_title,title)s\!nfo\%(title)s [%(extractor)s.%(extractor_key)s.%(id)s] [%(format_id)s].factsheet.nfo"
--print-to-file "resolution:             %(resolution)s" ".\%(playlist|)s\%(playlist_index|)02d%(playlist_index& = |)s%(release_date>%Y-%m-%d,release_timestamp>%Y-%m-%d,upload_date>%Y-%m-%d,timestamp>%Y-%m-%d|#nodate#)s %(alt_title,title)s\!nfo\%(title)s [%(extractor)s.%(extractor_key)s.%(id)s] [%(format_id)s].factsheet.nfo"
--print-to-file "duration:               %(duration>%H:%M:%S)s" ".\%(playlist|)s\%(playlist_index|)02d%(playlist_index& = |)s%(release_date>%Y-%m-%d,release_timestamp>%Y-%m-%d,upload_date>%Y-%m-%d,timestamp>%Y-%m-%d|#nodate#)s %(alt_title,title)s\!nfo\%(title)s [%(extractor)s.%(extractor_key)s.%(id)s] [%(format_id)s].factsheet.nfo"
--print-to-file "filesize:               %(filesize)s" ".\%(playlist|)s\%(playlist_index|)02d%(playlist_index& = |)s%(release_date>%Y-%m-%d,release_timestamp>%Y-%m-%d,upload_date>%Y-%m-%d,timestamp>%Y-%m-%d|#nodate#)s %(alt_title,title)s\!nfo\%(title)s [%(extractor)s.%(extractor_key)s.%(id)s] [%(format_id)s].factsheet.nfo"
etc.
etc.
...
```

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

n/a

**Comment by pukkandan** [comment]
1. You could combine them into a single command.
```conf
--print-to-file 'title:                  %(title)s
...
filesize:               %(filesize)s' ".\%(playlist|)s...].factsheet.nfo"
```

2. Or, you could save the filename template in an alias
```
--alias meta-name ".\%(playlist|)s...].factsheet.nfo"

--print-to-file "title:                  %(title)s" --meta-name
...
```

**Comment by pukkandan** [comment]
Config files are parsed like a POSIX shell. So the same syntax for continuations work.

The extra new lines look like some issue with CRLF settings. Difficult to say exactly without access to the files.

**Comment by bashonly** [comment]
alternatively you could do:

```
--alias print-meta '--print-to-file {} ".\%(playlist|)s\%(playlist_index|)02d%(playlist_index& = |)s%(release_date>%Y-%m-%d,release_timestamp>%Y-%m-%d,upload_date>%Y-%m-%d,timestamp>%Y-%m-%d|#nodate#)s %(alt_title,title)s\!nfo\%(title)s [%(extractor)s.%(extractor_key)s.%(id)s] [%(format_id)s].factsheet.nfo"'
--print-meta "title:                  %(title)s"
--print-meta "fulltitle:              %(fulltitle)s"
# etc...
```

**Comment by pukkandan** [comment]
Ah, my bad. Aliases are not parsed inside the arguments. Use bashonly's solution

**Comment by pukkandan** [comment]
https://github.com/yt-dlp/yt-dlp/issues/6808#issuecomment-1509361107 I can't seem to reproduce this.



> > Aliases are not parsed inside the arguments.
> 
> Does that mean, that aliases can only be used at the start of an instruction, i.e. at the beginning of a line ?

Yes. Once defined, an alias is just like any other switch.

**Comment by pukkandan** [comment]
> [#6808 (comment)](https://github.com/yt-dlp/yt-dlp/issues/6808#issuecomment-1509361107) I can't seem to reproduce this.

nvm, I can repro and I'll push a fix.

**Comment by pukkandan** [comment]
You could use `--parse-metadata` to save it into a field, but that won't work for `-o` with subdirs

**Comment by pukkandan** [comment]
That is not a supported `%()` syntax. I think this is what you want:
```
"%(playlist_title&playlist_title:         |)s%(playlist_title)s
%(playlist&playlist                |)s%(playlist)s
%(playlist_id&playlist_id:            |)s%(playlist_id)s"
```

**Comment by pukkandan** [comment]
The problem is not the new lines, but that what you are giving is not a valid output template. There is no support for nested `%(... %(...)s)s`

**Comment by pukkandan** [comment]
I can't test atm. But I think this should work?

```
%(playlist&
playlist:          |)s%(playlist)s
```

**Comment by pukkandan** [comment]
You still need to do line by line, but now newlines can be properly removed. Something like:
```
%(playlist_index&--------------- PLAYLIST -------------------------------|)s
%(playlist&
playlist title:        {}|)s
...
```

**Comment by bashonly** [comment]
> a) I have not changed the right column, so why all of a sudden the `~~` occur unexpectedly in the second setup, while they don't appear in the first? I would expect null output ("") in both setups due to the `|` override.

the `~~` appears in the second example because the left column does not have a `|` override:
`%(playlist&playlist_title:       )s`

> b) In the second setup in the last 2 lines, why are the `~~` before the slash `/` but not after ?

same reason

**Comment by bashonly** [comment]
try this
```
--print "%(playlist&--------------- PLAYLIST -------------------------------|)s%(playlist&
playlist:             {}|)s%(playlist_id&
playlist_id:          {}|)s%(playlist_uploader&
playlist uploader:    {}|)s%(playlist_uploader_id&
playlist uploader id: {}|)s%(playlist_index&
playlist index:       {}|)s%(playlist_count& / {}|)s%(playlist_autonumber&
playlist autonumber:  {}|)s%(n_entries& / {}|)s%(playlist&
---------------------------------------------------------|)s"
```
