### ISSUE TITLE
Rewrite YouTube docs to deal with shorts

### ISSUE THREAD

**Issue by jidanni** [yt-dlp/yt-dlp#6810]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that a **supported** site is broken
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Provide a description that is worded well enough to be understood

On the man page we see
```
  Filter videos
              import yt_dlp

              URLS = ['https://www.youtube.com/watch?v=BaW_jenozKc']

              def longer_than_a_minute(info, *, incomplete):
                  """Download only videos longer than a minute (or with unknown duration)"""
                  duration = info.get('duration')
                  if duration and duration < 60:
                      return 'The video is too short'

              ydl_opts = {
                  'match_filter': longer_than_a_minute,
              }

              with yt_dlp.YoutubeDL(ydl_opts) as ydl:
                  error_code = ydl.download(URLS)
```
Alas, this might need to be rewritten, as currently shorts get `"duration" : null`.
(Proof: `yt-dlp --dump-json --flat-playlist youtube.com/@jidanni2`)
Thus the above test to filter out shorts is no longer valid.

Also in extractor/youtube.py,
```
 _TESTS = [
        {
            'url': 'https://www.youtube.com/watch?v=BaW_jenozKc&t=1s&end=9',
...
                'duration': 10,
```
Please also add a real short, not just a `&t=1s&end=9` "long short"!
That should trigger the null. So one artificial short and one real short are needed for proper testing.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
Documentation as quoted above.
```

**Comment by pukkandan** [comment]
There is a reason verbose logs are mandatory. Next time, do not skip them.

--flat-playlist is expected to give incomplete metadata. Remove it to get full data.

**Comment by jidanni** [comment]
All I know is the manual says
```
       --flat-playlist
              Do not extract the videos of a playlist, only list them

       --no-flat-playlist
              Extract the videos of a playlist

```
It should also mention metadata.

And how to get the metadata without getting the videos.

**Comment by Lesmiscore** [comment]
The sentence "Do not extract" implies that some (or all on most websites) metadata will be missing, as yt-dlp works by "extract"ing metadata from websites

**Comment by jidanni** [comment]
OK, as I am still worried that "extract" might mean "download", I'll use `--skip-download` instead, and indeed I get forty times as much details:
```
$ wc *
     64    7467  119279 --no-playlist.json
     64  160921 4612997 --skip-download.json
```

**Comment by jidanni** [comment]
OK, one indeed does get full short details using `--dump-json --skip-download`, however [playlist_id are still broken](https://www.reddit.com/r/youtubedl/comments/12moroc/youtube_different_playlists_but_same_id/).

**Comment by pukkandan** [comment]
While we could look into improving it, playlist_id is not designed to be necessarily unique - so it's not really broken

**Comment by pukkandan** [comment]
> however [playlist_ids are still broken](https://www.reddit.com/r/youtubedl/comments/12moroc/youtube_different_playlists_but_same_id/).

Could you pls open a new site enhancement request for this? I originally assigned myself without asking for a proper issue report thinking it is a simple change, but now looking into it, I am no longer sure it is.

**Comment by pukkandan** [comment]
Closing since original question is answered and you've already opened a new issue for doc changes
