### ISSUE TITLE
--print-traffic doesn't print any traffic

### ISSUE THREAD

**Issue by jidanni** [yt-dlp/yt-dlp#6815]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Wishing to see if my cookies are really getting sent or not, I tried
I used `--print-traffic`, alas, no traffic is printed.

Alas, no traffic got printed.

So, I can't tell if `--cookies-from-browser` really sends cookies or not.

Sure, you might say, "Well, if your private videos show up in the
results, that's all the proof you need."

Well they don't. So maybe no cookies are being sent. Alas,
`--print-traffic `doesn't work, so we can't tell.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['--verbose', '--update', '--dump-json', '--flat-playlist', '--print-traffic', '--no-color', '--cookies-from-browser', 'chrome:/home/jidanni/.config/google-chrome-unstable/Default', 'https://www.youtube.com/@jidanni2']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8 (No ANSI), error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (debian*)
[debug] Python 3.11.2 (CPython x86_64 64bit) - Linux-6.1.0-7-amd64-x86_64-with-glibc2.36 (OpenSSL 3.0.8 7 Feb 2023, glibc 2.36)
[debug] exe versions: ffmpeg 5.1.3-1 (setts), ffprobe 5.1.3-1
[debug] Optional libraries: Cryptodome-3.11.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[Cookies] Extracting cookies from chrome
[debug] Extracting cookies from: "/home/jidanni/.config/google-chrome-unstable/Default/Cookies"
[debug] detected desktop environment: OTHER
[debug] Chosen keyring: BASICTEXT
[Cookies] Extracted 3125 cookies from chrome
[debug] cookie version breakdown: {'v10': 3109, 'v11': 0, 'other': 0, 'unencrypted': 16}
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
yt-dlp is up to date (stable@2023.03.04)
[youtube:tab] Extracting URL: https://www.youtube.com/@jidanni2
[youtube:tab] @jidanni2: Downloading webpage
[debug] [youtube:tab] Selected tab: 'videos' (videos), Requested tab: ''
[youtube:tab] Downloading all uploads of the channel. To download only the videos in a specific tab, pass the tab's URL
[youtube:tab] @jidanni2/shorts: Downloading webpage
[debug] [youtube:tab] Selected tab: 'shorts' (shorts), Requested tab: 'shorts'
[youtube:tab] Downloading as multiple playlists, separated by tabs. To download as a single playlist instead, pass https://www.youtube.com/playlist?list=UUu1NBeZA_KwhPyXJKLAfDsQ
[download] Downloading playlist: 積丹尼 Dan Jacobson
[youtube:tab] Playlist 積丹尼 Dan Jacobson: Downloading 2 items of 2
[debug] The information of all playlist entries will be held in memory
[download] Downloading item 1 of 2
[download] Downloading playlist: 積丹尼 Dan Jacobson - Videos
[youtube:tab] Playlist 積丹尼 Dan Jacobson - Videos: Downloading 27 items of 27
[debug] The information of all playlist entries will be held in memory
[download] Downloading item 1 of 27
...
[download] Downloading item 27 of 27
[download] Finished downloading playlist: 積丹尼 Dan Jacobson - Videos
[download] Downloading item 2 of 2
[download] Downloading playlist: 積丹尼 Dan Jacobson - Shorts
[youtube:tab] Playlist 積丹尼 Dan Jacobson - Shorts: Downloading 37 items of 37
[debug] The information of all playlist entries will be held in memory
[download] Downloading item 1 of 37
...
[download] Downloading item 37 of 37
[download] Finished downloading playlist: 積丹尼 Dan Jacobson - Shorts
[download] Finished downloading playlist: 積丹尼 Dan Jacobson
```

**Comment by coletdjnz** [comment]
I believe your output appears to be of only `stderr` only? If so, this is expected.

`--dump-json`: all yt-dlp output is sent to stderr instead of stdout.

`--print-traffic`: traffic output is always sent to `stdout` regardless of the above (This output comes internally from Python core networking code and not us)

**Comment by jidanni** [comment]
Yes, but my STDOUT didn't increase by single byte using the aforementioned option.

**Comment by coletdjnz** [comment]
> Yes, but my STDOUT didn't increase by single byte using the aforementioned option.

This is likely an issue on your end. The debug output is sent to stdout internally by CPython, not yt-dlp[^1]. The debug traffic shows for me in stdout with your command.

[^1]: https://docs.python.org/3/library/http.client.html#http.client.HTTPConnection.set_debuglevel

**Comment by pukkandan** [comment]
You are supposed to post the combined stdout and stderr in verbose log, not discard one! Please do that if you are still having issue
