### ISSUE TITLE
How do you search all youtube for 10 videos whose audio codec is m4a

### ISSUE THREAD

**Issue by blockbabak** [yt-dlp/yt-dlp#6821]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

It gives me the right answer but in the wrong format. I just want the list of ids
The ids in verbose are right.

yt-dlp -vU "ytsearch10:acodec" --match-filter "acodec=m4a" --get-url --skip-download
[debug] Command-line config: ['-vU', 'ytsearch10:acodec', '--match-filter', 'acodec=m4a', '--get-url', '--skip-download']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2023.03.03 [934496428] (pip)
[debug] Python 3.11.1 (CPython AMD64 64bit) - Windows-10-10.0.19041-SP0 (OpenSSL 1.1.1q  5 Jul 2022)
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1782 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.03
[debug] Downloading _update_spec from https://github.com/yt-dlp/yt-dlp/releases/latest/download/_update_spec
ERROR: You installed yt-dlp with pip or using the wheel from PyPi; Use that to update
[youtube:search] Extracting URL: ytsearch10:acodec
[download] Downloading playlist: acodec
[youtube:search] query "acodec": Downloading web client config
[youtube:search] query "acodec" page 1: Downloading API JSON
[youtube:search] Playlist acodec: Downloading 10 items of 10
[download] Downloading item 1 of 10
[youtube] Extracting URL: https://www.youtube.com/watch?v=RqxeNmg4Wbo
[youtube] RqxeNmg4Wbo: Downloading webpage
[youtube] RqxeNmg4Wbo: Downloading android player API JSON
[debug] [youtube] Extracting signature function js_36754c51_107
[debug] Loading youtube-sigfuncs.js_36754c51_107 from cache
[debug] Loading youtube-nsig.36754c51 from cache
[debug] [youtube] Decrypted nsig ZSWInYB3-8k0JrP1de0 => JjmGGE3YTOfTFw
[debug] [youtube] Extracting signature function js_36754c51_103
[debug] Loading youtube-sigfuncs.js_36754c51_103 from cache
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] RqxeNmg4Wbo: Downloading 1 format(s): 303+251
[download] What is a Codec and What Does it Do? does not pass filter (acodec=m4a), skipping ..
[download] Downloading item 2 of 10
[youtube] Extracting URL: https://www.youtube.com/watch?v=GhWki9a7s18
[youtube] GhWki9a7s18: Downloading webpage
[youtube] GhWki9a7s18: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] GhWki9a7s18: Downloading 1 format(s): 248+251
[download] What is a Codec as Fast As Possible does not pass filter (acodec=m4a), skipping ..
[download] Downloading item 3 of 10
[youtube] Extracting URL: https://www.youtube.com/watch?v=z-GGg9Y7yVg
[youtube] z-GGg9Y7yVg: Downloading webpage
[youtube] z-GGg9Y7yVg: Downloading android player API JSON
[debug] Loading youtube-nsig.36754c51 from cache
[debug] [youtube] Decrypted nsig UnCrxxVzzG9TWF6pDgW => stF6OE-mGjEfrQ
[youtube] z-GGg9Y7yVg: Downloading MPD manifest
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] z-GGg9Y7yVg: Downloading 1 format(s): 303+251
[download] ACODEC شهادة : الوكيلي بوعزاوي - جمعية does not pass filter (acodec=m4a), skipping ..
[download] Downloading item 4 of 10
[youtube] Extracting URL: https://www.youtube.com/watch?v=kdKnddqCJbY
[youtube] kdKnddqCJbY: Downloading webpage
[youtube] kdKnddqCJbY: Downloading android player API JSON
[debug] Loading youtube-nsig.36754c51 from cache
[debug] [youtube] Decrypted nsig dfqca9YbLPBcBl2YVou => d2OpZkH_E7jm5Q
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] kdKnddqCJbY: Downloading 1 format(s): 308+251
[download] How to play MP3 files without a codec chip on the ESP32 does not pass filter (acodec=m4a), skipping ..
[download] Downloading item 5 of 10
[youtube] Extracting URL: https://www.youtube.com/watch?v=P5Vs7BgeQog
[youtube] P5Vs7BgeQog: Downloading webpage
[youtube] P5Vs7BgeQog: Downloading android player API JSON
[debug] Loading youtube-nsig.36754c51 from cache
[debug] [youtube] Decrypted nsig HxI5bQrUnqkVl0aJk_O => 6RHagKdlnnrPpA
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] P5Vs7BgeQog: Downloading 1 format(s): 137+251
[download] What Is a Codec? does not pass filter (acodec=m4a), skipping ..
[download] Downloading item 6 of 10
[youtube] Extracting URL: https://www.youtube.com/watch?v=V2P2waAOabA
[youtube] V2P2waAOabA: Downloading webpage
[youtube] V2P2waAOabA: Downloading android player API JSON
[debug] Loading youtube-nsig.36754c51 from cache
[debug] [youtube] Decrypted nsig iUH0BsU5iIpApErLFbf => 1vyc2ST_sC0FAg
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] V2P2waAOabA: Downloading 1 format(s): 137+251
[download] Jordan Peterson vs Naked Snake From Metal Gear On A Codec Call does not pass filter (acodec=m4a), skipping ..
[download] Downloading item 7 of 10
[youtube] Extracting URL: https://www.youtube.com/watch?v=AoXMpGmihms
[youtube] AoXMpGmihms: Downloading webpage
[youtube] AoXMpGmihms: Downloading android player API JSON
[debug] Loading youtube-nsig.36754c51 from cache
[debug] [youtube] Decrypted nsig 4XycLThranc5m0MRxyc => dOriv9GQJaskKA
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] AoXMpGmihms: Downloading 1 format(s): 136+251
[download] Yaser Sheikh - What is a Codec Avatar? does not pass filter (acodec=m4a), skipping ..
[download] Downloading item 8 of 10
[youtube] Extracting URL: https://www.youtube.com/watch?v=kVh4ArkzzRo
[youtube] kVh4ArkzzRo: Downloading webpage
[youtube] kVh4ArkzzRo: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] kVh4ArkzzRo: Downloading 1 format(s): 313+251
[download] Panasonic Camcorder - How to Select a CODEC does not pass filter (acodec=m4a), skipping ..
[download] Downloading item 9 of 10
[youtube] Extracting URL: https://www.youtube.com/watch?v=7s2wZORdy1Q
[youtube] 7s2wZORdy1Q: Downloading webpage
[youtube] 7s2wZORdy1Q: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 7s2wZORdy1Q: Downloading 1 format(s): 271+251
[download] ffmpeg -i DJI_0069.MOV -vcodec copy  -acodec copy Nignt.mp4 does not pass filter (acodec=m4a), skipping ..
[download] Downloading item 10 of 10
[youtube] Extracting URL: https://www.youtube.com/watch?v=7AiHVcwrN4A
[youtube] 7AiHVcwrN4A: Downloading webpage
[youtube] 7AiHVcwrN4A: Downloading android player API JSON
[youtube] 7AiHVcwrN4A: Downloading MPD manifest
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 7AiHVcwrN4A: Downloading 1 format(s): 247+251
[download] how to play avi and any type of video files and what is a codec! does not pass filter (acodec=m4a), skipping ..
[download] Finished downloading playlist: acodec

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by october262** [comment]
see here under sorting formats aext - https://github.com/yt-dlp/yt-dlp#filtering-formats

**Comment by pukkandan** [comment]
All youtube videos have m4a available which you can access by `-f m4a`

**Comment by blockbabak** [comment]
Have you  at least tried -f 4ma?
And who told you that Youtube has m4a version for all videos? I think they were kidding you

Anyway, this is ERROR you get when -f m4a

 

\Users\bbkma\Documents\LocalPython>-f m4a

'-f' is not recognized as an internal or external command,

operable program or batch file.

**Comment by bashonly** [comment]
> yt-dlp -vU "ytsearch10:acodec"

when you use `yt-dlp ytsearch10:PHRASE`, `PHRASE` is your search terms, the same as if you were to search on the youtube website. example: `yt-dlp ytsearch10:puppies`

searching youtube for `acodec` is probably not what you want

> who told you that Youtube has m4a version for all videos? I think they were kidding you

youtube does have m4a formats for all videos. But they will not be selected by default, you need to do that, with `-f m4a`

> \Users\bbkma\Documents\LocalPython>-f m4a

you need to use it like `yt-dlp -f m4a "https://www.youtube.com/watch?v=RqxeNmg4Wbo"`

**Comment by blockbabak** [comment]
Searching videos codecs for m4a is exactly what I want. I want 10 videos whose audio code is m4a. I want them to test an application.



Mine provides 10 videos whose audio codec are m4a but only with vU option. Please read the uV output.

 

In fact, could you please send it back to me as I didn’t save it again anticipating you would know how to get rid of the verbose part.

If you can get the 10 video ids as part of the output without all the verbose stuff, then that is exactly what I want.


[Search10:] only accepts query terms regarding the content of videos and not the properties of the video.I did it once but I didn’t write it down.

You didn’t test your advice again, did you?. 1st of all I want 10 video ids. So that is not what I want.

 

C:\Users\bbkma\Documents\LocalPython>yt-dlp -f m4a "https://www.youtube.com/watch?v=RqxeNmg4Wbo"

[youtube] Extracting URL: https://www.youtube.com/watch?v=RqxeNmg4Wbo

[youtube] RqxeNmg4Wbo: Downloading webpage

[youtube] RqxeNmg4Wbo: Downloading android player API JSON

[info] RqxeNmg4Wbo: Downloading 1 format(s): 140

[dashsegments] Total fragments: 1

[download] Destination: What is a Codec and What Does it Do？ [RqxeNmg4Wbo].m4a

[download] 100% of    2.38MiB in 00:00:01 at 1.35MiB/s

WARNING: RqxeNmg4Wbo: writing DASH m4a. Only some players support this container. Install ffmpeg to fix this automatically If you look my uV output, you will find 10 video id and if you check the audio codec of them are all m4a. All I want are those verbose stuff around.

In fact, could you please send it back to me as I didn’t save it again anticipating you would know how to get rid of the verbose part. 

 

If you want to see the [search:10] works. Then change the 10 to 3 and with verbose option I bet you anything you like that it will give you three video ids that have audio codec=m4a. 

 

Besides if I knew the video ids with audio codec m4a why would I want to check its audio codec?
I would just do this:
 
yt-dlp --list-formats https://www.youtube.com/watch?v=oHg5SJYRHA0 that lists you all the formats that you can download for that video. Youtube converts audio codec to opus on streaming. I wish it could do that on all downloads as well. That would make my life a lot easier.

 


If you don’t know how to do it, then please pass it someone else. There is nothing to prove here. I wouldn’t know if the sender was some else, would I?

**Comment by garret1317** [comment]
> 1st of all I want 10 video ids.

go to the youtube homepage and select 10 videos at random
then get rid of the https://www.youtube.com/watch?v= bit
👍

**Comment by pukkandan** [comment]
Please read the suggestions again carefully and try them out. If you still have issue while running the suggestions, post new verbose log.

**Comment by blockbabak** [comment]
You missed half the sentence: 10 video ids with m4a audio codes

The way I did it with vU,

I would like to complain. You guys hide your ignorance too much.

So, you know jack shit. You wll see you emails in reviews,

**Comment by gamer191** [comment]
> You missed half the sentence: 10 video ids with m4a audio codes

All of them have m4a audio codes, just use `--list-formats`

**Comment by gamer191** [comment]
> I would like to complain

This is a volunteer run forum, not a commercial support service!

**Comment by blockbabak** [comment]
I think we are at cross-purpose’s, your previous misinterpreted me because they didn’t consider it within the context which was, I want 10 video ids whose audio codes is m4a because m4a doesn’t fit webm container with V9b video codec.

 

Please correct me if I am wrong. This is what I understood from your last email:

Your email instructed me to go to Youtube home page and select 10 videos regardless of their audio codec, right?

Then extract the video ids from the 10 URL. And then what?

Will their audio codec magically turn to m4a?
Or you tube will trans process them to m4a? If I could pass the post processing to Youtube that would be. Then I wouldn’t even need to find F17 versions with audio codec=m4a.

 

I am searching for 10 videos ids whose acodec=m4a.

My command runs but doesn’t output anything unless it has -vU option. With -vU option it does contain 10 video ids that meet the criteria of having m4a as audio codec when you list format 17.
Youtube converts it to opus on streaming it. But when downloading F 17 version it will have its native audio codec which mean port processing them to m4a to suit my search criteria. But then why would I do that. I don’t want to use post processing on my side. It slows things up and increases the cost on a Google Engine app.

2ndly you don’t try your recommendation before sending the despite having asked for it several times. So far none of them have worked except the one which was you don’t that, you want this.

As if I was asking builder for an estimate and he was trying to sell me something more expensive like in one of Harry Enfield sketches.


That is either unprofessional or taking the piss of the person who has asked you for help.

What is the point of listing available format of 10 known video ids?

**Comment by Lesmiscore** [comment]
You were already told that YouTube does provide m4a files for all the videos as always, so 10 of any 10 YouTube videos has m4a.
You were also told that you can get one with `-f m4a`.
No postprocessing will take place with `-f m4a`.
Use of `-vU` does not matter.
What do you want any more than that?

**Comment by gamer191** [comment]
> That is either unprofessional

Again, this is a volunteer run forum. We don’t try to be professional

**Comment by blockbabak** [comment]
I have sent you the:  -vU log.
You don’t try your command 1st on your side before sending them to me.

**Comment by Lesmiscore** [comment]
```
[TestURL] Extracting URL: test:youtube_3
[TestURL] Test URL: https://www.youtube.com/watch?v=a9LDPn-MO4I
[youtube] Extracting URL: https://www.youtube.com/watch?v=a9LDPn-MO4I
[youtube] a9LDPn-MO4I: Downloading webpage
[youtube] a9LDPn-MO4I: Downloading android player API JSON
[info] a9LDPn-MO4I: Downloading 1 format(s): 140
[download] Destination: UHDTV TEST 8K VIDEO.mp4 [a9LDPn-MO4I].m4a
[download] 100% of 942.10KiB in 00:01 at 508.22KiB/s
[FixupM4a] Correcting container of "UHDTV TEST 8K VIDEO.mp4 [a9LDPn-MO4I].m4a"
[VideoRemuxer] Not remuxing media file "UHDTV TEST 8K VIDEO.mp4 [a9LDPn-MO4I].m4a"; could not find a mapping for m4a
```

I have tried. I get the result you expect. I bet you did not test it.

**Comment by bashonly** [comment]
```sh
$ yt-dlp --print id ytsearch10:cats
HEtjKEW59uU
S9hDCskzWSM
6pbreU5ChmA
eBEn2zxgtQ4
xbs7FT7dXYc
DvjmOTaQGJ4
RzP2PaEDDHU
_yqSbnbUsj4
nHTuud_pFLE
878435bD4wE

$ yt-dlp -f m4a HEtjKEW59uU S9hDCskzWSM 6pbreU5ChmA eBEn2zxgtQ4 xbs7FT7dXYc DvjmOTaQGJ4 RzP2PaEDDHU _yqSbnbUsj4 nHTuud_pFLE 878435bD4wE
[youtube+NSigDeno] Extracting URL: HEtjKEW59uU
[youtube+NSigDeno] HEtjKEW59uU: Downloading webpage
[youtube+NSigDeno] HEtjKEW59uU: Downloading android player API JSON
[info] HEtjKEW59uU: Downloading 1 format(s): 140
[download] Destination: 20230417_@meowthemall3318_HEtjKEW59uU_FUNNY_CAT_MEMES_COMPILATION_OF_2023_V16.m4a
[download] 100% of    9.90MiB in 00:00:00 at 24.76MiB/s
[FixupM4a] Correcting container of "20230417_@meowthemall3318_HEtjKEW59uU_FUNNY_CAT_MEMES_COMPILATION_OF_2023_V16.m4a"
[youtube+NSigDeno] Extracting URL: S9hDCskzWSM
[youtube+NSigDeno] S9hDCskzWSM: Downloading webpage
[youtube+NSigDeno] S9hDCskzWSM: Downloading android player API JSON
[info] S9hDCskzWSM: Downloading 1 format(s): 140
[download] Destination: 20230405_@BirderKing_S9hDCskzWSM_Cat_TV_for_Cats_to_Watch_Fascinating_Birds_and_Their_Squirrel_Fr.m4a
[download]  32.8% of  445.16MiB at    1.33MiB/s ETA 03:44^C
ERROR: Interrupted by user
```

**Comment by pukkandan** [comment]
> Please read the suggestions again carefully and try them out. If you still have issue while running the suggestions, post new verbose log.

Unless you can do this, I will be forced to treat further comments as spam

**Comment by blockbabak** [comment]
Attached is a screen shot of your email.
Pleas point out the part that I missed. I am presuming you are referring to:
But you are right but wasn’t before 21/03/2023.
Now all format id 17 have m4a audio codes, just use --list-formats 17 


This must be new because I have idtag 17 webm files downloaded only the 21/03/2023. Now the same format 17 is 3gp.

How could I have downloaded a file in WebM container when its video codec was V9B? You can’t have m4a and V9B is a WebM.


So Youtube must have changed all the audio codecs for idtg 17s to m4a so the download is in 3gp container.

Do they annonce this thing. I can prove it the audio codec was not always m4a,

Also Why?


I have tried that

**Comment by pukkandan** [comment]
There is no screenshot or verbose log attached in your message. I would recommend you try using the Github webpage instead of answering through mail and see what you are actually posting here.

**Comment by blockbabak** [comment]
As I explained I wasn’t aware of recent changes. This id 17 format is in m4a was not the case before the21/03/2023. And I can prove it.

If someone told me of recent change in YouTube, I wouldn’t have pursued the matter. So, the commands you sent were never complete .

One of you should have told me that Youtube has change it available for download such that Format id 17 is aways in m4a.

So, I won’t apologise because none of your response was complete. 21/03/2023 is less than month ago.

But, I agree that you can close this down.
