### ISSUE TITLE
current_time variable

### ISSUE THREAD

**Issue by chrizilla** [yt-dlp/yt-dlp#6828]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

I thought I could do the following to see how much time the different stages take:

```python
 --print-to-file pre_process:"pre_process:  %(epoch>%Y-%m-%d %H:%M:%S)s" "timestamps.txt"
--print-to-file after_filter:"after_filter: %(epoch>%Y-%m-%d %H:%M:%S)s" "timestamps.txt"
       --print-to-file video:"video:        %(epoch>%Y-%m-%d %H:%M:%S)s" "timestamps.txt"
   --print-to-file before_dl:"before_dl:    %(epoch>%Y-%m-%d %H:%M:%S)s" "timestamps.txt"
--print-to-file post_process:"post_process: %(epoch>%Y-%m-%d %H:%M:%S)s" "timestamps.txt"
  --print-to-file after_move:"after_move:   %(epoch>%Y-%m-%d %H:%M:%S)s" "timestamps.txt"
 --print-to-file after_video:"after_video:  %(epoch>%Y-%m-%d %H:%M:%S)s" "timestamps.txt"
``` 

But the result is:
```shell
pre_process:  2023-04-16 06:08:39
after_filter: 2023-04-16 06:08:39
video:        2023-04-16 06:08:39
before_dl:    2023-04-16 06:08:39
post_process: 2023-04-16 06:08:39
after_move:   2023-04-16 06:08:39
after_video:  2023-04-16 06:08:39
``` 

I suspect this doesn't work because epoch is not the current time.
README:
`epoch (numeric): Unix epoch of when the information extraction was completed`

Can we have a current_time variable to make the above work ?

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
Use shell scripts for it. It doesn't make sense to have a field that keeps changing.
