### ISSUE TITLE
empty `container` field

### ISSUE THREAD

**Issue by chrizilla** [yt-dlp/yt-dlp#6830]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

The `container` field seems unavailable. Is this a bug?

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp gr51aVj-mLg --print after_move:"container: %(container)s" --no-config --no-simulate -v

[debug] Command-line config: ['gr51aVj-mLg', '--print', 'after_move:container: %(container)s', '--no-config', '--no-simulate', '-v']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2023.04.16.034742 [9874e82b5] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.1
[debug] Proxy map: {}
[debug] Loaded 1797 extractors
[youtube] Extracting URL: gr51aVj-mLg
[youtube] gr51aVj-mLg: Downloading webpage
[youtube] gr51aVj-mLg: Downloading android player API JSON
[youtube] gr51aVj-mLg: Downloading MPD manifest
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[debug] Default format spec: best/bestvideo+bestaudio
[info] gr51aVj-mLg: Downloading 1 format(s): 18
[debug] Invoking http downloader on "https://rr5---sn-h0jeener.googlevideo.com/videoplayback?expire=1681652400&ei=UKY7ZPGkC4LW1wLY8YnYBw&ip=91.118.143.91&id=o-AINmB6lh8MHEy_ylclaVGeZEI-xwOCcEjna2ncbn7xDH&itag=18&source=youtube&requiressl=yes&mh=-9&mm=31%2C29&mn=sn-h0jeener%2Csn-h0jeln7l&ms=au%2Crdu&mv=m&mvi=5&pl=16&initcwndbps=2547500&spc=99c5CRCTA-Q3srUuh63RMD7ZGgBgHzY&vprv=1&svpuc=1&mime=video%2Fmp4&cnr=14&ratebypass=yes&dur=10.100&lmt=1636675987407441&mt=1681630389&fvip=2&fexp=24007246&c=ANDROID&txp=1218224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Ccnr%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRQIgMG-hN2dzDV0pTa1aJ6A6NsfjvuzJk7cWVEcORzZxXnECIQC-9wF8AlkYYlMfESx0wFsxbk9bj4mzZ38gGjL3keOr2w%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgC2ziAIR3XgpGoQPkUsJIpM01UJbk9wFVP33arHKORSQCIBd6IaVdVhR1G76rhqxaeoIN7ClFHIS2T30hHetdLvMM"
[debug] File locking is not supported. Proceeding without locking
[download] Destination: Youtube-dl Annotation Test [gr51aVj-mLg].mp4
[download] Download completed
container: NA
```

**Comment by pukkandan** [comment]
No, because the format doesn't have a different container. What did you expect it to give?

**Comment by pukkandan** [comment]
The only example I know off the top of my head is `m4a_dash`. You can see the container in `-F` (in more info) if present.

**Comment by pukkandan** [comment]
> I would have expected it to always have a value.

`id`, `url`, `ext` are the only fields guaranteed to have a value.

**Comment by dirkf** [comment]
19 specific extractor modules mention `'container'`, though sometimes this may be a page string rather than the format metadata item, or both, as in Brightcove.

**Comment by pukkandan** [comment]
The main use of the field afaik is only to detect m4a_dash apart from other m4a so we know whether to apply fixup or not. Idk why it's even exposed to user tbh.

**Comment by dirkf** [comment]
Indeed: https://github.com/ytdl-org/youtube-dl/commit/1394ce65b4

But the PR/issue linked from there is obviously not right.
