### ISSUE TITLE
download auto-generated subtitles automatically every time I play a Youtube video through MPV

### ISSUE THREAD

**Issue by tXJtqlb3bbeKD1yW8SV7** [yt-dlp/yt-dlp#6836]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

How can I download auto-generated subtitles automatically every time I play a Youtube video through MPV and save them to a desired destination?

I try add this to my conf file:
```
--write-auto-sub 
--sub-langs=en
--skip-download  
-o "%USERPROFILE%\Downloads\%(title)s-%(id)s.%(ext)s"
```
Didn't work though.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
IMO it's better to do this in your `mpv.conf`, add this line:
```
ytdl-raw-options="no-simulate=,skip-download=,write-auto-sub=,sub-langs=en,output=[%USERPROFILE%\Downloads\%(title)s-%(id)s.%(ext)s]"
```

**Comment by tXJtqlb3bbeKD1yW8SV7** [comment]
It worked. Thank you very much!!!
