### ISSUE TITLE
[wikimedia.org] Remove GeoIP cookie from info.json when cleaning info.json

### ISSUE THREAD

**Issue by gabldotink** [yt-dlp/yt-dlp#6837]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a site-specific feature
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

worldwide

### Example URLs

https://commons.wikimedia.org/wiki/File:Hannah_Montana_vs._5000_volts.ogv

### Provide a description that is worded well enough to be understood

When info.json personal data is cleaned — using the `--clean-info-json` switch or by default — `"http_headers": "Cookie": "GeoIP=[value]"` should be removed, as it contains the full name of the city, as well as the country and region codes, the request comes from. This is the header's value from Proton VPN's "NL-FREE#102135" server: `NL:NH:Amsterdam:52.38:4.90:v4`. The full output can be found in the log below.

A lot of improvements could be made to this extractor, but those are other issues.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
$ yt-dlp -vU --simulate --dump-json --clean-info-json --no-config https://commons.wikimedia.org/wiki/File:Hannah_Montana_vs._5000_volts.ogv
[debug] Command-line config: ['-vU', '--simulate', '--dump-json', '--clean-info-json', '--no-config', 'https://commons.wikimedia.org/wiki/File:Hannah_Montana_vs._5000_volts.ogv']
[debug] Encodings: locale utf-8, fs utf-8, pref utf-8, out utf-8 (No ANSI), error utf-8 (No ANSI), screen utf-8 (No ANSI)
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (pip)
[debug] Python 3.11.3 (CPython aarch64 64bit) - Linux-5.4.210-moto-g1ee30c0b9c3a-aarch64-with-libc (OpenSSL 3.1.0 14 Mar 2023, libc)
[debug] exe versions: ffmpeg 6.0 (setts), ffprobe 6.0
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
yt-dlp is up to date (stable@2023.03.04)
[wikimedia.org] Extracting URL: https://commons.wikimedia.org/wiki/File:Hannah_Montana_vs._5000_volts.ogv
[wikimedia.org] Hannah_Montana_vs._5000_volts: Downloading webpage
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] Hannah_Montana_vs._5000_volts: Downloading 1 format(s): 0
{"id": "Hannah_Montana_vs._5000_volts", "url": "https://upload.wikimedia.org/wikipedia/commons/transcoded/1/1a/Hannah_Montana_vs._5000_volts.ogv/Hannah_Montana_vs._5000_volts.ogv.240p.vp9.webm", "description": "English:  A lineman demonstrating electric transmission line safety using a mylar balloon and lines charged with 5000 volts. See also this photo of the balloon being after it was shocked.", "title": "Hannah Montana vs. 5000 volts.ogv - Wikimedia Commons", "license": "Creative Commons Attribution-Share Alike 3.0 Unported", "uploader": null, "subtitles": {}, "webpage_url": "https://commons.wikimedia.org/wiki/File:Hannah_Montana_vs._5000_volts.ogv", "original_url": "https://commons.wikimedia.org/wiki/File:Hannah_Montana_vs._5000_volts.ogv", "webpage_url_basename": "File:Hannah_Montana_vs._5000_volts.ogv", "webpage_url_domain": "commons.wikimedia.org", "extractor": "wikimedia.org", "extractor_key": "Wikimedia", "playlist": null, "playlist_index": null, "display_id": "Hannah_Montana_vs._5000_volts", "fulltitle": "Hannah Montana vs. 5000 volts.ogv - Wikimedia Commons", "requested_subtitles": null, "_has_drm": null, "ext": "webm", "protocol": "https", "resolution": null, "dynamic_range": "SDR", "aspect_ratio": null, "http_headers": {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.19 Safari/537.36", "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8", "Accept-Language": "en-us,en;q=0.5", "Sec-Fetch-Mode": "navigate", "Cookie": "GeoIP=NL:NH:Amsterdam:52.38:4.90:v4"}, "video_ext": "webm", "audio_ext": "none", "format_id": "0", "format": "0 - unknown", "epoch": 1681678733, "_filename": "Hannah Montana vs. 5000 volts.ogv - Wikimedia Commons [Hannah_Montana_vs._5000_volts].webm", "filename": "Hannah Montana vs. 5000 volts.ogv - Wikimedia Commons [Hannah_Montana_vs._5000_volts].webm", "urls": "https://upload.wikimedia.org/wikipedia/commons/transcoded/1/1a/Hannah_Montana_vs._5000_volts.ogv/Hannah_Montana_vs._5000_volts.ogv.240p.vp9.webm", "_type": "video", "_version": {"version": "2023.03.04", "current_git_head": null, "release_git_head": "392389b7df7b818f794b231f14dc396d4875fbad", "repository": "yt-dlp/yt-dlp"}}
```

**Comment by bashonly** [comment]
see concurrent discussion in https://github.com/yt-dlp/yt-dlp/issues/5773#issuecomment-1510242833

> "private" is used here in a programing sense and refers to the various book-keeping fields that we add to the infodict. It has nothing to do with privacy.

you can manually remove fields from your info json, e.g. `--parse-metadata "video::(?P<http_headers>)"`

**Comment by pukkandan** [comment]
Note that if http_headers are redacted, it may not be possible to ue the file with `--load-info-json`
