### ISSUE TITLE
Extract 2 audio streams from the 4 contained in a resource

### ISSUE THREAD

**Issue by pavel167** [yt-dlp/yt-dlp#6841]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Some videos contain multiple audio streams that are identical.
Here is such case:
``` 
yt-dlp -F https://www.france.tv/films/4800295-la-dame-de-fer.html
[FranceTVSite] Extracting URL: https://www.france.tv/films/4800295-la-dame-de-fer.html
[FranceTVSite] 4800295-la-dame-de-fer: Downloading webpage
[FranceTV] Extracting URL: francetv:b6d906f0-3a35-41f5-b461-ac388c3c13e7
[FranceTV] b6d906f0-3a35-41f5-b461-ac388c3c13e7: Downloading desktop video JSON
[FranceTV] b6d906f0-3a35-41f5-b461-ac388c3c13e7: Downloading mobile video JSON
[FranceTV] b6d906f0-3a35-41f5-b461-ac388c3c13e7: Downloading signed dash manifest URL
[FranceTV] b6d906f0-3a35-41f5-b461-ac388c3c13e7: Downloading MPD manifest
[FranceTV] b6d906f0-3a35-41f5-b461-ac388c3c13e7: Downloading signed hls manifest URL
[FranceTV] b6d906f0-3a35-41f5-b461-ac388c3c13e7: Downloading m3u8 information
[info] Available formats for b6d906f0-3a35-41f5-b461-ac388c3c13e7:
ID                                EXT RESOLUTION FPS │   FILESIZE   TBR PROTO │ VCODEC        VBR ACODEC     ABR ASR MORE INFO
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
hls-audio-aacl-96-Audio_Français  mp4 audio only     │                  m3u8  │ audio only        unknown            [fr] Audio Français
hls-audio-aacl-96-Audio_Originale mp4 audio only     │                  m3u8  │ audio only        unknown            [qaa] Audio Originale
dash-audio_fre=96000              m4a audio only     │ ~ 70.66MiB   96k dash  │ audio only        mp4a.40.2  96k 48k [fr] DASH audio, m4a_dash
dash-audio_qaa=96000              m4a audio only     │ ~ 70.66MiB   96k dash  │ audio only        mp4a.40.2  96k 48k [qaa] DASH audio, m4a_dash
dash-video=400000                 mp4 384x216     25 │ ~294.43MiB  400k dash  │ avc1.42C01E  400k video only         DASH video, mp4_dash
hls-522                           mp4 384x216     25 │ ~384.24MiB  522k m3u8  │ avc1.42C01E  522k video only
dash-video=950000                 mp4 640x360     25 │ ~699.28MiB  950k dash  │ avc1.4D401F  950k video only         DASH video, mp4_dash
hls-1105                          mp4 640x360     25 │ ~813.37MiB 1105k m3u8  │ avc1.4D401F 1105k video only
dash-video=1400000                mp4 960x540     25 │ ~  1.01GiB 1400k dash  │ avc1.4D401F 1400k video only         DASH video, mp4_dash
hls-1582                          mp4 960x540     25 │ ~  1.14GiB 1582k m3u8  │ avc1.4D401F 1582k video only
dash-video=2000000                mp4 1280x720    25 │ ~  1.44GiB 2000k dash  │ avc1.64001F 2000k video only         DASH video, mp4_dash
hls-2218                          mp4 1280x720    25 │ ~  1.59GiB 2218k m3u8  │ avc1.64001F 2218k video only
```
There are 4 audiostreams and audio streams (3, 4) are identical to audio streams (1, 2).
How to build a command that takes only 2 of 4 audiostreams:

- using streams numeration (i.e. audiostreams 1, 2)
- using patterns, i.e. streams that match **hls-audio-aacl-96-Audio_*** pattern

Thanks.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
Assuming you want them both in a single file,

    -f "mergeall[acodec!=none][protocol*=dash]" --audio-multistreams

of, if you want them separate,

    -f "all[acodec!=none][protocol*=dash]" -o "... %(format_id)s.%(ext)s"

See "filtering formats" section of readme for more details.

**Comment by pavel167** [comment]
Sorry, I missed in my request that I also need video merged with 2 audiotracks.
I tried this ...
`yt-dlp -s -f "mergeall bv*[acodec!=none][protocol*=dash]" --audio-multistreams https://www.france.tv/films/4800295-la-dame-de-fer.html`
but it didn't work

**Comment by pavel167** [comment]
Thanks, works.
As I understood, the number of audio threads specified by number after **w.** ?
So, if I wanted to take 3rd and 4th threads, the option would be `-f bv+wa.3+wa.4 --audio-multistreams`, correct ?
Also is it possible to name the audio streams, so that is instead of "Track 1", "Track 2", VLC player displays "English", "French" ?

**Comment by pavel167** [comment]
Ok, thanks

**Comment by pukkandan** [comment]
> but it didn't work

I can't see your screen!

> ### Provide verbose output that clearly demonstrates the problem
> * [x]  Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
> * [x]  Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

But seems your issue is solved. In that case, ignore

---

> > Also is it possible to name the audio streams, so that is instead of "Track 1", "Track 2", VLC player displays "English", "French" ?
> 
> I defer to the pros here on that.

`--embed-metadata` will add language codes. But idk if VLC reads from it.

**Comment by pavel167** [comment]
> --embed-metadata will add language codes. But idk if VLC reads from it.

If I want to add my proper names, not those metadata provides. For example using MKVToolNIX I can rename audio tracks and VLC recognize these names.

**Comment by pukkandan** [comment]
See https://github.com/yt-dlp/yt-dlp#modifying-metadata, specifically

> To modify the metadata of individual streams, use the `meta<n>_` prefix (e.g. `meta1_language`).

**Comment by pukkandan** [comment]
> > Any value set to the `meta_` field will overwrite all default values.
> 
> Changing only 1 field, for example `meta_description` will erase all values in the table above ?

No, it's talking about the field `meta_` literally. Setting `--parse-metadata " hi: %(meta_)s"` will change all those fields to "hi". The main use for this feature is to remove the defaults. E.g.

    --parse-meta ":(?P:meta_)" --parse-meta "my name:%(meta_artist)s" --embed_metadata


will set only artist and no other field.

**Comment by pavel167** [comment]
Hello,
I faced a new use case related to this problem.
Here are stream info from 2 files:
1st:
```
ID                                EXT RESOLUTION FPS │   FILESIZE   TBR PROTO │ VCODEC        VBR ACODEC     ABR ASR MORE INFO
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
hls-audio-aacl-96-Audio_Français  mp4 audio only     │                  m3u8  │ audio only        unknown            [fr] Audio Français
hls-audio-aacl-96-Audio_Originale mp4 audio only     │                  m3u8  │ audio only        unknown            [qaa] Audio Originale
dash-audio_fre=96000              m4a audio only     │ ~ 59.13MiB   96k dash  │ audio only        mp4a.40.2  96k 48k [fr] DASH audio, m4a_dash
dash-audio_qaa=96000              m4a audio only     │ ~ 59.13MiB   96k dash  │ audio only        mp4a.40.2  96k 48k [qaa] DASH audio, m4a_dash
dash-video=400000                 mp4 384x216     25 │ ~246.39MiB  400k dash  │ avc1.42C01E  400k video only         DASH video, mp4_dash
hls-522                           mp4 384x216     25 │ ~321.53MiB  522k m3u8  │ avc1.42C01E  522k video only
dash-video=950000                 mp4 640x360     25 │ ~585.17MiB  950k dash  │ avc1.4D401F  950k video only         DASH video, mp4_dash
hls-1105                          mp4 640x360     25 │ ~680.64MiB 1105k m3u8  │ avc1.4D401F 1105k video only
dash-video=1400000                mp4 960x540     25 │ ~862.35MiB 1400k dash  │ avc1.4D401F 1400k video only         DASH video, mp4_dash
hls-1582                          mp4 960x540     25 │ ~974.46MiB 1582k m3u8  │ avc1.4D401F 1582k video only
dash-video=2000000                mp4 1280x720    25 │ ~  1.20GiB 2000k dash  │ avc1.64001F 2000k video only         DASH video, mp4_dash
hls-2218                          mp4 1280x720    25 │ ~  1.33GiB 2218k m3u8  │ avc1.64001F 2218k video only
```
2nd:
```
ID                                    EXT   RESOLUTION FPS │   FILESIZE   TBR PROTO │ VCODEC        VBR ACODEC     MORE INFO
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
spritesheets                          mhtml unknown        │                  mhtml │ images                       storyboard
hls-audio-AACL-96-Audio_Description-0 mp4   audio only     │                  m3u8  │ audio only        unknown    [qad] audio description, Audio Description
hls-audio-AACL-96-Audio_Description-1 mp4   audio only     │                  m3u8  │ audio only        unknown    [qad] audio description, Audio Description
hls-audio-AACL-96-Francais-0          mp4   audio only     │                  m3u8  │ audio only        unknown    [fr] Francais
hls-audio-AACL-96-Francais-1          mp4   audio only     │                  m3u8  │ audio only        unknown    [fr] Francais
hls-audio-AACL-96-Version_Originale-0 mp4   audio only     │                  m3u8  │ audio only        unknown    [qaa] Version Originale
hls-audio-AACL-96-Version_Originale-1 mp4   audio only     │                  m3u8  │ audio only        unknown    [qaa] Version Originale
hls-232-0                             mp4   256x144     25 │ ~172.41MiB  232k m3u8  │ avc1.42801e  232k video only
hls-232-1                             mp4   256x144     25 │ ~172.41MiB  232k m3u8  │ avc1.42801e  232k video only
hls-530-0                             mp4   384x216     25 │ ~394.52MiB  531k m3u8  │ avc1.42801e  531k video only
hls-530-1                             mp4   384x216     25 │ ~394.52MiB  531k m3u8  │ avc1.42801e  531k video only
hls-1113-0                            mp4   640x360     25 │ ~827.72MiB 1114k m3u8  │ avc1.4d401e 1114k video only
hls-1113-1                            mp4   640x360     25 │ ~827.72MiB 1114k m3u8  │ avc1.4d401e 1114k video only
hls-1590-0                            mp4   960x540     25 │ ~  1.15GiB 1591k m3u8  │ avc1.4d401f 1591k video only
hls-1590-1                            mp4   960x540     25 │ ~  1.15GiB 1591k m3u8  │ avc1.4d401f 1591k video only
hls-2756-0                            mp4   1280x720    25 │ ~  2.00GiB 2757k m3u8  │ avc1.64001f 2757k video only
hls-2756-1                            mp4   1280x720    25 │ ~  2.00GiB 2757k m3u8  │ avc1.64001f 2757k video only
hls-5406-0                            mp4   1920x1080   25 │ ~  3.92GiB 5407k m3u8  │ avc1.640029 5407k video only
hls-5406-1                            mp4   1920x1080   25 │ ~  3.92GiB 5407k m3u8  │ avc1.640029 5407k video only
```
The option (for using with Python) that I currently use is:
ydl_opts = {'format': 'bv+hls-audio-aacl-96-Audio_Français+hls-audio-aacl-96-Audio_Originale', 'allow_multiple_audio_streams': True}
It works for 1st file, but not for 2nd. How to adapt this option to work for both files (for 2nd file take only 1 French and 1 Original) ?
Thanks.

**Comment by pavel167** [comment]
The option format should meet these requirements:

- if link contains audio streams "hls-audio-aacl-96-Audio_Français" and "hls-audio-aacl-96-Audio_Originale" pick them and merge with video
- if link contains audio streams "hls-audio-aacl-96-Audio_Français-0",  "hls-audio-aacl-96-Audio_Français-1", "hls-audio-aacl-96-Audio_Originale-0", "hls-audio-aacl-96-Audio_Originale-1", pick only "hls-audio-aacl-96-Audio_Français-0" and "hls-audio-aacl-96-Audio_Originale-0" and merge them with video

Or shortly ... regardless of the number of French or Original audio streams of the link, pick only one French stream and only one  Original stream and merge these 2 audio streams with the video stream

**Comment by pukkandan** [comment]
> Or shortly ... regardless of the number of French or Original audio streams of the link, pick only one French stream and only one Original stream and merge these 2 audio streams with the video stream

is not the same as this!

> * if link contains audio streams "hls-audio-aacl-96-Audio_Français" and "hls-audio-aacl-96-Audio_Originale" pick them and merge with video
> * if link contains audio streams "hls-audio-aacl-96-Audio_Français-0",  "hls-audio-aacl-96-Audio_Français-1", "hls-audio-aacl-96-Audio_Originale-0", "hls-audio-aacl-96-Audio_Originale-1", pick only "hls-audio-aacl-96-Audio_Français-0" and "hls-audio-aacl-96-Audio_Originale-0" and merge them with video

---

You are assuming the format codes are always in this format. Why not just use the language field instead? Try what I suggested above.

**Comment by teadrinker2015** [comment]
> Setting --parse-metadata " hi: %(meta_)s" will change all those fields to "hi".

@pukkandan Apologize maybe a bit of off-topic, I still can't understand the usage of `--parse-metadata`. Is the string before ":" considered to be a literal string if it is not a predefined field (e.g. "description")?

What I want to achieve is to give audio streams name (or language) as "original", "DRC"

I tried:
- `--parse-metadata "original:%(meta1_language)s" --parse-metadata "DRC:%(meta2_language)s"`
it outputs NA for both tracks
- `--replace-in-metadata "meta1_language" ".*" "original" --replace-in-metadata "meta2_language" ".*" "DRC"`
seems ignored, track name still "English"

related #4854 #9555

**Comment by bashonly** [comment]
@teadrinker2015 if you want the lefthand value to be interpreted as a literal string, it needs to contain a space (or else yt-dlp will interpret it as an info dict field name and attempt expansion). If the string you want to use does not have a space, you can add a leading space on both sides of the separator, e.g.:

```
--parse-metadata " original: %(meta1_language)s" --parse-metadata " DRC: %(meta2_language)s"
```

**Comment by teadrinker2015** [comment]
@bashonly Thanks. Works great. FWIW, I think the README doesn't mention this. (if this is the an unconscious documentaion bug)
