### ISSUE TITLE
[outtmpl] Support %s formatting inside replacements

### ISSUE THREAD

**Issue by chrizilla** [yt-dlp/yt-dlp#6843]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

> @pukkandan [commented](https://github.com/yt-dlp/yt-dlp/issues/6300#issuecomment-1436181445):
> `%(a&b|c)s` is kinda like `if a, "b" else "c"`. 

I can't get this to work. In my tests the field names are printed instead of the field values:

```shell
yt-dlp ZYlALC1Pmv4 --ignore-config --print "filesize_approx"
468853974 # ok this works

yt-dlp ZYlALC1Pmv4 --ignore-config --print "%(filesize_approx&id)s"
id

yt-dlp ZYlALC1Pmv4 --ignore-config --print "%(filesize_approx&url)s"
url

yt-dlp ZYlALC1Pmv4 --ignore-config --print "%(filesize_approx&filesize_approx)s"
filesize_approx

yt-dlp ZYlALC1Pmv4 --ignore-config --print "%(filesize_approx&filesize_approx|filesize_approx)s"
filesize_approx
``` 

Does that mean in the syntax above, `a` is a field name whereas `b` and `c` are only strings in which field names are not recognized ?

So is there no possibility to say:
**If field a exists, output field b, else field c ?**

I am trying to learn the syntax rules, but the link in README
> The special sequences may be formatted according to [Python string formatting operations](https://docs.python.org/3/library/stdtypes.html#printf-style-string-formatting)

didn't mention the replacement rules. I have tried to search on the net, but I don't even know the search term I would have to use. I tried _"printf style string formatting"_ and _"special sequences in Python"_ and _"Python string formatting operations"_ but I didn't come anywhere close to the syntax that is in use here apparently. So despite my best efforts, I am sorry to have to ask. Any advice where I could study the correct syntax would be most welcome.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
> Does that mean in the syntax above, `a` is a field name whereas `b` and `c` are only strings in which field names are not recognized ?

Yes, as denoted by `""` in my explanation


> I am trying to learn the syntax rules, but the link in README
> didn't mention the replacement rules.

This is not using Python syntax, but our customized mini-language. See "Default" and "Replacement" in https://github.com/yt-dlp/yt-dlp#output-template


> So is there no possibility to say: **If field a exists, output field b, else field c ?**

Not exactly, but you can say 'if a, a, else c' using `%(a,c)s` - see "Alternate" in output template doc for details.

Technically, what you want can be achieved by some smart use of `--parse-metadata`, but I would need to see exact use-case and example to help.

**Comment by pukkandan** [comment]
> Could I have known that from README or isn't it mentioned there yet ?

this

> See "Default" and "Replacement" in [yt-dlp/yt-dlp#output-template](https://github.com/yt-dlp/yt-dlp#output-template)

---

> so I have to use something bulky like `--print "%(filesize_approx&~)s%(filesize_approx|)s%(filesize_approx& bytes)s"`.

Yes

---

> > what you want can be achieved by some smart use of `--parse-metadata`
> 
> Thank you. I'll see first if I can work it out with what's available to me. But could you give me a hint what idea you had in mind regarding `--parse-metadata` because that parameter doesn't allow if/then/else/and/or/not/etc. either, no ?

Similar to bashonly's suggestion in #6848

**Comment by pukkandan** [comment]
No, similar to `-f`'s mini-language, it's a language we built for this specific use-case. Full documentation is in readme. It is extended from printf-style formatting, hence why we reference its docs for relevant parts.

**Comment by pukkandan** [comment]
That is not an intended use and just happens to work due to a quirk of `>`. Don't blame me if it breaks in future.

**Comment by pukkandan** [comment]
> > Pukkandan [commented](https://github.com/yt-dlp/yt-dlp/issues/6848#issuecomment-1512427900): We'd have to look into adding a new operator if this is needed.
> 
> ... because as you can see from the above, this has obvious advantages.

That comment is not related to this issue 😕. I am not going to add a new operator for this since it can already be achieved, even though in a bit lengthier form.

**Comment by pukkandan** [comment]
> Is there really no easy way of saying _"just take everything from the field as string"_ (like: `%(filesize_approx>~%S bytes)s` ) ?

Would be possible, but probably confusing since `>` is specifically intended for date time formatting. And if we are doing it, I'd want %d, %f etc to also work, which would conflict with some of the existing operators. Maybe we could instead implement `%(filesize&%s bytes|)s`? That would be much less ambiguous.


> 1. **Date/time Formatting**: Date/time fields can be formatted according to [strftime formatting](https://docs.python.org/3/library/datetime.html#strftime-and-strptime-format-codes) by specifying it separated from the field name using a `>`. E.g. `%(duration>%H-%M-%S)s`, `%(upload_date>%Y-%m-%d)s`, `%(epoch-3600>%H-%M-%S)s`

**Comment by pukkandan** [comment]
> > `>%s` means epoch of the datetime.
> 
> ok thanks. Why isn't it menioned [here](https://docs.python.org/3/library/datetime.html#strftime-and-strptime-format-codes) ?

I am not sure. Maybe because it's support is OS dependent? (We do some extra magic to support it on all OSes)


> ```
> --print "%(epoch>%Y is a good year)s"
> 2023 is a good year
> ```
> 
> ... I thought it would be much easier to slightly enhance this than the _"full rewrite"_ with the _"tokenizer/parser"_ thing you talked about above. Or would it be needed either way?

No, this should be easier. What we cannot implement without rewrite is nesting brackets - like `%(a& %(b)s)s` because python regex has no way to keep proper track of bracket counts.

**Comment by pukkandan** [comment]
I decided to use the [`str.format` syntax](https://docs.python.org/3/library/string.html#format-specification-mini-language) instead of `%s` as it provides more flexibility. So now you can do `%(filesize_approx>~{} bytes|)s`

**Comment by pukkandan** [comment]
Was a typo. Updated https://github.com/yt-dlp/yt-dlp/issues/6843#issuecomment-1520143696
