### ISSUE TITLE
add "live" string to filename template if `is_live=true` ?

### ISSUE THREAD

**Issue by chrizilla** [yt-dlp/yt-dlp#6848]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

How can we mark livestream filenames as such?

More specifically: How can we use the `is_live` field in the filename template to add a string (e.g. "live") to the filename ?

I want to:
- if `is_live=true` : add "live" to the filename
- if` is_live=false`: add nothing to the filename

I tried, but apparently `______&` only checks if the variable exists and is true even when a boolean variable is false:

```sh
yt-dlp TSNbCSF13Zo --skip-download --no-config --print is_live
False

yt-dlp TSNbCSF13Zo --skip-download --no-config --print "%(is_live&live|notlive)s"
live    # I would have hoped for "notlive" output here because is_live=false

yt-dlp TSNbCSF13Zo --skip-download --no-config --print "%(is_live=true&live|notlive)s"
NA      # I tried that just in case, but logical operators seem unsupported
```

Could you change the functionality so that for boolean variables not the existence is checked but its true/false value (so that `boolean_variable_with_value_false& = false`) ?

If not, is there another solution ?

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
`--parse-metadata` can help with this:

```sh
$ yt-dlp --parse-metadata "%(is_live)s:(?P<live>True)" -o "%(id)s_%(live&live|)s.%(ext)s" --get-filename kgx4WGK0oNU
kgx4WGK0oNU_live.mp4

$ yt-dlp --parse-metadata "%(is_live)s:(?P<live>True)" -o "%(id)s_%(live&live|)s.%(ext)s" --get-filename TSNbCSF13Zo
TSNbCSF13Zo_.mkv
```

or you could use `live_status` instead, e.g.:
```sh
$ yt-dlp --parse-metadata "%(live_status)s:is_(?P<live>live)" -o "%(id)s_%(live|)s.%(ext)s" --get-filename kgx4WGK0oNU
kgx4WGK0oNU_live.mp4

$ yt-dlp --parse-metadata "%(live_status)s:is_(?P<live>live)" -o "%(id)s_%(live|)s.%(ext)s" --get-filename TSNbCSF13Zo
TSNbCSF13Zo_.mkv
```

**Comment by bashonly** [comment]
> You basically say: If is_live=true then create a new variable "live" and set it to true, so that the existence of this new variable can be utilized in the filename template, right ?

```
--parse-metadata [WHEN:]FROM:TO

--parse-metadata "%(is_live)s:(?P<live>True)"
```
We're using a regex pattern as the `TO` in this argument, so it will be used to search the value of `is_live`
The regex will only capture "True", so `live` will not have a value if `is_live` == "False"

```
-o "%(id)s_%(live&live|)s.%(ext)s"
```
if `live` has a value, then "live" or empty

---
```
--parse-metadata "%(live_status)s:is_(?P<live>live)"
```
Same idea here, but this is searching the value of `live_status` for "is_live" and then only capturing "live" as the value of `live`
```
-o "%(id)s_%(live|)s.%(ext)s"
```
then we use the value of `live` if it has one, or else empty

**Comment by pukkandan** [comment]
> I tried, but apparently `______&` only checks if the variable exists and is true even when a boolean variable is false:

`|` was designed to only replace `NA` values (i.e `None`). We'd have to look into adding a new operator if this is needed.

**Comment by pukkandan** [comment]
> For me the `|` was not the problem, but `&`:

They are just opposites
