### ISSUE TITLE
"Conversion Failed" Converting MPEG-TS

### ISSUE THREAD

**Issue by HDark15** [yt-dlp/yt-dlp#6849]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Had "conversion failed" when downloading Twitch video in MKV container and it's still MPEG-TS. Trying to convert it with FFMPEG 
```
ffmpeg -i test1.mkv test2.mkv
```
But this take a long time since it's trying to convert it. Trying just copy vcodec and acodec seems works, but I don't know if this is a proper way
```
ffmpeg -y -i your_file.mkv -vcodec copy -acodec copy -map 0:v -map 0:a your_file.mkv
```
What's the proper command with FFMPEG to do it?

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-your-question-about-yt-dlp
https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-there-enough-context-in-your-bug-report

**Comment by pukkandan** [comment]
> Make sure you are **only** asking a question and not reporting a bug or requesting a feature.
> If your question contains "isn't working" or "can you add", this is most likely the wrong template.
> If you are in doubt whether this is the right template, **USE ANOTHER TEMPLATE**!

Do not abuse the "Question" template to post incomplete issues.

Properly fill out an appropriate issue form. Or at bare minimum, post a verbose log!

**Comment by pukkandan** [comment]
> If it is fixup, add `-f mp4 -bsf:a aac_adtstoasc` to your above command with codec copies.

Try this. My confusion is mainly because the input file is mkv in your example commands, which should not be possible. I cannot help further without knowing what happened. You'll just have to try it and see.

**Comment by pukkandan** [comment]
Did my above suggestion not work?

**Comment by pukkandan** [comment]
> It was this, I should just test it with -vU if it gives me the cm, my bad
> 
> ```
> [FixupM3u8] Fixing MPEG-TS in MP4 container of "test360p.mkv"
> [debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:test360p.mkv" -map 0 -dn -ignore_unknown -c copy -f mp4 "-bsf:a" aac_adtstoasc -movflags "+faststart" "file:test360p.temp.mkv"
> ```

Which is what I suggested too. Sorry if it wasn't clear.

> > My confusion is mainly because the input file is mkv in your example commands, which should not be possible.
> 
> I don't understand this

Nvm it. The confusion happened coz you hardcoded the `.mkv` extension. So the downloaded file is actually a `ts` file, just forcibly renamed into `mkv`

---

Closing since your issue seems to be resolved.
