### ISSUE TITLE
safety measure: add epoch to `-o` if `is_live=true` OR generic filename

### ISSUE THREAD

**Issue by chrizilla** [yt-dlp/yt-dlp#6852]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

For better a better overview and organization of the download folder and also in order to avoid [data loss by unwanted overwriting](https://github.com/yt-dlp/yt-dlp/issues/6740), I would like to create unique filenames by [adding the current time (`epoch`)](https://github.com/yt-dlp/yt-dlp/issues/6705#issuecomment-1495434210) as a safety measure in those situations where unintentional overwriting could occur:
* [live streams](https://github.com/yt-dlp/yt-dlp/issues/6705)
* untitled downloads where no metadata is available, e.g. chunklist.m3u8 ([URL](https://apasfiis.sf.apa.at/cms-worldwide_nas/_definst_/nas/cms-worldwide/online/2023-04-17_2229_tl_02_kulturMontag_-Ophelia-s-got-__14175554__o__2114260042__s15377517_7__ORF2HD_23161816P_23223208P_Q4A.mp4/playlist.m3u8)) resulting in generic filenames such as:
`playlist\playlist [generic.playlist].mp4.part` https://github.com/yt-dlp/yt-dlp/issues/6740#issuecomment-1500724964

Thanks to #6848 I know how to add `epoch` to `-o` in case `is_live=true`. So I can handle the first case.
But how can I detect the second case ?
And how can I add `epoch` if EITHER one of those cases is true ?

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
> * [live streams](https://github.com/yt-dlp/yt-dlp/issues/6705)

The default behavior is to add epoch to livestreams. Your linked issue is already solved!


> * untitled downloads where no metadata is available, e.g. chunklist.m3u8 ([URL](https://apasfiis.sf.apa.at/cms-worldwide_nas/_definst_/nas/cms-worldwide/online/2023-04-17_2229_tl_02_kulturMontag_-Ophelia-s-got-__14175554__o__2114260042__s15377517_7__ORF2HD_23161816P_23223208P_Q4A.mp4/playlist.m3u8)) resulting in generic filenames such as:
>   `playlist\playlist [generic.playlist].mp4.part` [[data loss] METABUG: don't overwrite files #6740 (comment)](https://github.com/yt-dlp/yt-dlp/issues/6740#issuecomment-1500724964)

> But how can I detect the second case ?

What exactly is this second case? It looks like an arbitrary human choice to me of what is considered "generic filename". For the program, that is just the title and id like any other video. It has no way of knowing what names you consider "generic"

**Comment by dissona** [comment]
Here is a solution i have used in the past:

fragmented downloads from twitch are like this /chunked/0.ts then increment by 1

add option `--seg-start 200` loop through fragment list until it finds /chunked/200.ts, start download

even if site does not use generic increment, it should still find the correct fragment it is up to

Another note:
Current downloader without arg --download-sections creates a .ytdl file what contains index:

`{"downloader": {"current_fragment": {"index": 2}, "extra_state": {}}}`

index can be found from the downloader .m3u8 and logged, not sure why this is not used for all fragmented downloads?

**Comment by pukkandan** [comment]
`--download-sections` use ffmpeg, not native downloader. So we cannot resume or keep fragment count.

**Comment by dissona** [comment]
is there a way to download without ffmpeg? appending .ts files together works fine but file is bigger and can be processed by ffmpeg after download is completed

**Comment by pukkandan** [comment]
No, because we have no way to determine what timestamp corresponds to what fragment. There is also need to deal with initialization fragment (for dash), which would be difficult since yt-dlp doesn't actually know how to distinguish headers from video stream.

**Comment by dissona** [comment]
`ffprobe -i video.mp4 -show_entries format=duration`

user start duration + ffprobe duration IF .part exists

could be a solution. seems to work ok
