### ISSUE TITLE
`--print-to-file` field IF field exists to prevent empty file from being written ?

### ISSUE THREAD

**Issue by chrizilla** [yt-dlp/yt-dlp#6857]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Is it possible to `--print-to-file` a field only IF it exists ?
example: `--print-to-file "%(chapters|)j" chapters.json"`
So I am looking for something like: `IF chapters exist THEN print`.

I want to avoid empty files if `chapters` doesn't exist.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
It is not directly possible. You can use `--exec` to either conditionally write the file, or to delete the zero-size files

**Comment by pukkandan** [comment]
Untested, but the batch file could look something like this:

```bat
if ["%~1"]==[""] (
  echo %1 > file.txt
)
```

However, you are asking generic scripting questions now. Please direct follow up questions to appropriate forums

**Comment by pukkandan** [comment]
> Aside from that, would you see a simple way of implementing this inside yt-dlp ?

Implementation is likely not difficult if we come up with a syntax. But I'd honestly consider this out of scope.



> But how can the parameter from OP `--print-to-file "%(chapters|)j" chapters.json"` be converted to `--exec something` ?

    --exec something "%(chapters|)q"

**Comment by bashonly** [comment]
> I have not found a batch file solution in Windows to conditionally write the file if the content is not this exact byte sequence.

have you tried this?
```batchfile
if not "%~1"=="" (
  echo %1 > file.txt
)
```
pukkandan basically [suggested this above](https://github.com/yt-dlp/yt-dlp/issues/6857#issuecomment-1520840248)
