### ISSUE TITLE
is it possible to download thumbnails of youtube videos + soundcloud songs along with the video/song itself

### ISSUE THREAD

**Issue by Percah** [yt-dlp/yt-dlp#6861]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

ive been trying to archive some deleted soundcloud songs and it really sucks to not have the og cover, same with youtube videos. i was just wondering if this was possible z

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by Johir-islam** [comment]
You [Download Online YouTube Thumbnail](https://youtube-thumbnail-dl.com/)

**Comment by Fuwiz** [comment]
> add `--write-thumbnail` and/or `--embed-thumbnail` to your command
> 
> or `--write-all-thumb` if you want to get all available thumbs

It download video too. Can i just grab thumbnail?
