### ISSUE TITLE
Get output from print as JSON

### ISSUE THREAD

**Issue by mazznoer** [yt-dlp/yt-dlp#6865]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Can I get this output of titles and urls from playlist in JSON format?

```shell
$ python3 -m yt_dlp 'https://www.youtube.com/playlist?list=PLwT6SNxZ9XVHFXtG4AtyRnw9Kl_kLi24z' --print title --print webpage_url
stan twitter @camilacabello  : i’ll be home for cquismoise
https://www.youtube.com/watch?v=Zjd_Xo8Xd-c
maow
https://www.youtube.com/watch?v=s1TsnnqgkoY
mrrp mrrp meow mrrp meow
https://www.youtube.com/watch?v=rdVcT09dEf8
Stupid Sheep
https://www.youtube.com/watch?v=TOsyAMiXCSA
Cat Meows into door camera meme but famous phone ringtones
https://www.youtube.com/watch?v=lPdF0HOJg_g
Mao-
https://www.youtube.com/watch?v=K9KOLM84wwA
Stan twitter: two girls laughing in 5 different voice changers
https://www.youtube.com/watch?v=aoldMYeGM6E
Kitten Train
https://www.youtube.com/watch?v=QS47v1j29ec
```

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
See https://github.com/yt-dlp/yt-dlp#output-template

    --print "%(.{title,webpage_url})j"
