### ISSUE TITLE
Wait for a live stream

### ISSUE THREAD

**Issue by qo4on** [yt-dlp/yt-dlp#6871]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Is there a workaround to wait for the channel to have a live stream available for download? At the moment yt-dlp throws an error `This live event will begin in 2 hours.`.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
```
--wait-for-video MIN[-MAX]      Wait for scheduled streams to become
                                available. Pass the minimum number of
                                seconds (or range) to wait between retries
```
e.g.
`--wait-for-video 30`
`--wait-for-video 15-60`

**Comment by bashonly** [comment]
use `https://www.youtube.com/@channel/live` as the URL

**Comment by qo4on** [comment]
Thank you. But for some reason it doesn't always work, like for this channel:
`yt-dlp --live-from-start --wait-for-video 300 https://www.youtube.com/@Novik_S/live`
It redirects to `https://www.youtube.com/NovikStream/live` which does not exists. But it exists, the same channel:
`yt-dlp --live-from-start --wait-for-video 300 https://www.youtube.com/channel/UCgjyvsNfStZbZ_6sfdbnmhg/live`
Click on the live tab on this page and see how the url changes to  `https://www.youtube.com/@Novik_S/streams`.

**Comment by gamer191** [comment]
https://www.youtube.com/@Novik_S doesn't work in a browser either

And if you click any of that youtuber's videos (such as https://www.youtube.com/watch?v=hGvBN9CyUtY), then click his channel name, and then refresh the page, you also get a 404 error :facepalm:

**Comment by pukkandan** [comment]
> [youtube.com/@Novik_S](https://www.youtube.com/@Novik_S) doesn't work in a browser either
> 
> And if you click any of that youtuber's videos (such as [youtube.com/watch?v=hGvBN9CyUtY](https://www.youtube.com/watch?v=hGvBN9CyUtY)), then click his channel name, and then refresh the page, you also get a 404 error 🤦

Yip, it's a known bug from YT. Nothing we can do.

**Comment by marcmerlin** [comment]
May I suggest that 
--wait-for-video 60 
should be a default option in the code?

**Comment by bashonly** [comment]
I don't launching into a potentially endless loop should be the default behavior

**Comment by GUUser91** [comment]
You can use this cheat sheet
>while ! yt-dlp -f 139 -o "%(uploader)s - %(title)s - %(id)s.%(ext)s" --live-from-start --abort-on-unavailable-fragment [url] --socket-timeout 5; do echo DISCONNECTED; sleep 10; done

**Comment by tphil99** [comment]
@GUUser91 please explain what is the benefit of this command over a plain `yt-dlp --live-from-start --wait-for-video 300 [url]`

**Comment by GUUser91** [comment]
This command is used for downloading a future livestream and it can restart if it fails to download a fragment.

**Comment by tphil99** [comment]
@GUUser91 I see, thanks. Btw, suppose I want to record all livestreams on a yt channel, but I cannot predict when they occur. What is the recommended way to ensure I always have yt-dlp "waiting" for a potential new stream to start. I'm not sure what's possible, but one strategy I can think of is: make cron run yt-dlp every 20 mins, where yt-dlp aborts if "The channel is not currently live", but continues if "This live event will begin in <N> minutes" or if the stream is live. Any recommendations?

**Comment by GUUser91** [comment]
You mean like this? Just add live in the url after the channel name. I've done this to livestreams that wouldn't start until 1-3 days later.
```
while ! yt-dlp -f 139 -o "%(uploader)s - %(title)s - %(id)s.%(ext)s" --live-from-start --abort-on-unavailable-fragment https://youtube.com/@PipkinPippa/live --socket-timeout 5; do echo DISCONNECTED; sleep 10; done
```

**Comment by GUUser91** [comment]
I found a alias function command for scheduling youtube livestream in audio only with the help of microsoft copilot:
```
ytl() {
  while ! yt-dlp \
    -f 140 \
    -o "%(uploader)s-%(title)s - %(id)s.%(ext)s" \
    --cookies /home/user/Cookies/cookies.txt \
    --extractor-args "youtube:player-client=default,mweb;po_token=mweb.gvs+XXXXXXXXXXXXXXXXXXXXXXX" \
    --embed-metadata \
    --live-from-start \
    --no-skip-unavailable-fragments \
    --abort-on-unavailable-fragments \
    --extractor-retries 15 \
    --retry-sleep 2 \
    --socket-timeout 5 \
    "$@"
  do
    echo "DISCONNECTED"
    sleep 120
  done
}
```
