### ISSUE TITLE
为何无法列出这个网址的视频格式 Why can't list the video formats for this URL

### ISSUE THREAD

**Issue by DOSforever** [yt-dlp/yt-dlp#6879]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

无法列出该网址的视频格式
The video format for this URL cannot be listed
See the URL below

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
ytdlpf -vF TXtyYZIiWcg
[debug] Command-line config: ['--proxy', 'https://127.0.0.1:8580', '-vF', 'TXtyYZIiWcg']
[debug] Portable config "D:\X64\yt-dlp\yt-dlp.conf": ['--progress', '--buffer-size', '8M', '--no-overwrites', '--write-l
ink', '--write-subs', '--write-auto-subs', '--sub-langs', 'en,en-en,en-orig,cn,zh-cn,zh-hans,zh-Hans-zh-CN,zh-Hans-zh-Ha
ns,zh-hans-en', '--write-description', '--ffmpeg-location', 'D:/X64/ffmpeg-N-109406-gc3e20f78b0-win64-gpl-shared/bin', '
--retry-sleep', '1']
[debug] Encodings: locale cp936, fs utf-8, pref cp936, out utf-8 (No VT), error utf-8 (No VT), screen utf-8 (No VT)
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-7-6.1.7601-SP1 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-109406-gc3e20f78b0-20221212 (setts), ffprobe N-109406-gc3e20f78b0-20221212, phantomjs 2.1
.1
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets
-10.4
[debug] Proxy map: {'http': 'https://127.0.0.1:8580', 'https': 'https://127.0.0.1:8580'}
[debug] Loaded 1786 extractors
[youtube] Extracting URL: TXtyYZIiWcg
[youtube] TXtyYZIiWcg: Downloading webpage
[youtube] TXtyYZIiWcg: Downloading android player API JSON
ERROR: [youtube] TXtyYZIiWcg: Video unavailable
  File "yt_dlp\extractor\common.py", line 694, in extract
  File "yt_dlp\extractor\youtube.py", line 4018, in _real_extract
  File "yt_dlp\extractor\common.py", line 1172, in raise_no_formats
```

**Comment by pukkandan** [comment]
![image](https://user-images.githubusercontent.com/6623388/233626319-9235c42a-3dbb-45de-b438-29ef945fa0ac.png)

**Comment by DOSforever** [comment]
哦！太奇怪了，我是在能播放时就提取信息的，怎么会不可用呢？
哦！原来是少一个  "-" 符号，当我双击地址时自动选择的是无连字符的字符串。正确的字符串应该是 "-TXtyYZIiWc" 。
非常感谢提醒！
Oh! It's so strange, I extracted the information when I could play it, how could it not be used?
Oh! It turned out to be one less "-" symbol, and when I double-clicked on the address,The string that automatically selected is without hyphens. The correct string should be "-TXtyYZIiWc".
Thanks a lot for the reminder!
