### ISSUE TITLE
Specifying where to save temporary and final files

### ISSUE THREAD

**Issue by raki-can** [yt-dlp/yt-dlp#6883]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I don't have English as my first language, and even after reading the README instructions, I couldn't figure out how to write the settings in the config file to do exactly the behavior I am actually looking for in yt-dlp.
Perhaps this is a rather silly question, but please help.

I currently use only the "-o" option and simply specify where to save the file and its title.
However, it specifies the HDD for the archive, which I believe limits the speed of the download process.
So I am trying to designate the SSD as the destination for the temporary files, but could not figure out how to write to designate the two destinations.

Can someone please provide me with the code text in a state that I can just copy and paste into the config file?

Current "-o" options:
` -o "F:\Nico-down\temp\%(upload_date)s - %(title)s.%(ext)s" `
(The "temp" folder used here indicates that when I download various videos, this is the work area where I store all new videos before moving them to a suitable folder to archive and classify them.)

Expected behavior:
- Maintains the destination and file name of the final file
- Sets the temporary file destination to "c:\yt-dlp_temp\"

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
I think you want to use the `-P`/`--paths` option. It accepts a `temp:` prefix

You can use this in your config file:
```
# filename template
-o "%(upload_date)s - %(title)s.%(ext)s"

# temporary path (SSD)
-P "temp:C:\yt-dlp_temp"

# final path (HDD)
-P "F:\Nico-down\temp"
```

**Comment by raki-can** [comment]
Thanks so much for the quick response.
This worked very well.
(I saw that the files were created in the temporary files folder on the SSD and then deleted after the merge and at the same time the final file was created in the correct path.)
