### ISSUE TITLE
Youtube can be used normally, but youtube cannot be downloaded in system proxy mode, and there is no problem in Tun mode

### ISSUE THREAD

**Issue by suger520HT** [yt-dlp/yt-dlp#6885]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that a **supported** site is broken
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Provide a description that is worded well enough to be understood

youtube can't download using proxy

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
C:\Users\Administrator>yt-dlp -v https://www.youtube.com/watch?v=NKIydLLjFAA&ab_channel=%E9%9B%B6%E5%BA%A6%E8%A7%A3%E8%AF%B4 --proxy socks5://127.0.0.1:10809
[debug] Command-line config: ['-v', 'https://www.youtube.com/watch?v=NKIydLLjFAA']
[debug] Portable config "E:\Tencent\Mplayer\yt-dlp.conf": ['--output', 'E:\\Tencent\\N_m3u8DL-CLI\\Downloads\\%(title)s-%(section_number)s-%(section_title)s.%(ext)s', '--console-title', '--progress-template', 'download-title:%(info.id)s-%(progress.eta)s', '--merge-output-format', 'mp4', '--no-write-subs', '--external-downloader', 'aria2c', '--cookies-from-browser', 'edge', '--embed-thumbnail', '--embed-metadata']
[debug] Encodings: locale cp936, fs utf-8, pref cp936, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (win_exe)
[debug] Python 3.11.2 (CPython AMD64 64bit) - Windows-10-10.0.19044-SP0 (OpenSSL 1.1.1s  1 Nov 2022)
[debug] exe versions: ffmpeg 2023-03-05-git-912ac82a3c-full_build-www.gyan.dev (setts), ffprobe 2023-03-05-git-912ac82a3c-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[Cookies] Extracting cookies from edge
[debug] Extracting cookies from: "C:\Users\Administrator\AppData\Local\Microsoft\Edge\User Data\Default\Network\Cookies"
[debug] Found local state file at "C:\Users\Administrator\AppData\Local\Microsoft\Edge\User Data\Local State"
[Cookies] Extracted 641 cookies from edge
[debug] cookie version breakdown: {'v10': 641, 'other': 0, 'unencrypted': 0}
[debug] Proxy map: {'http': 'http://127.0.0.1:10809', 'https': 'http://127.0.0.1:10809', 'ftp': 'http://127.0.0.1:10809'}
[debug] Loaded 1802 extractors
[youtube] Extracting URL: https://www.youtube.com/watch?v=NKIydLLjFAA
[youtube] NKIydLLjFAA: Downloading webpage
WARNING: [youtube] Unable to download webpage: <urlopen error [WinError 10061] 由于目标计算机积极拒绝，无法连接。>
[debug] [youtube] Extracted SAPISID cookie
[youtube] NKIydLLjFAA: Downloading android player API JSON
WARNING: [youtube] <urlopen error [WinError 10061] 由于目标计算机积极拒绝，无法连接。>. Retrying (1/3)...
[youtube] NKIydLLjFAA: Downloading android player API JSON
WARNING: [youtube] <urlopen error [WinError 10061] 由于目标计算机积极拒绝，无法连接。>. Retrying (2/3)...
[youtube] NKIydLLjFAA: Downloading android player API JSON
WARNING: [youtube] <urlopen error [WinError 10061] 由于目标计算机积极拒绝，无法连接。>. Retrying (3/3)...
[youtube] NKIydLLjFAA: Downloading android player API JSON
[youtube] NKIydLLjFAA: Downloading iframe API JS
WARNING: [youtube] Unable to download webpage: <urlopen error [WinError 10061] 由于目标计算机积极拒绝，无法连接。>
[youtube] NKIydLLjFAA: Downloading web player API JSON
WARNING: [youtube] <urlopen error [WinError 10061] 由于目标计算机积极拒绝，无法连接。>. Retrying (1/3)...
[youtube] NKIydLLjFAA: Downloading web player API JSON
WARNING: [youtube] <urlopen error [WinError 10061] 由于目标计算机积极拒绝，无法连接。>. Retrying (2/3)...
[youtube] NKIydLLjFAA: Downloading web player API JSON
WARNING: [youtube] <urlopen error [WinError 10061] 由于目标计算机积极拒绝，无法连接。>. Retrying (3/3)...
[youtube] NKIydLLjFAA: Downloading web player API JSON
WARNING: [youtube] Unable to download API page: <urlopen error [WinError 10061] 由于目标计算机积极拒绝，无法连接。> (caused by URLError(ConnectionRefusedError(10061, '由于目标计算机积极拒绝，无法连接。', None, 10061, None)))
ERROR: [youtube] NKIydLLjFAA: Unable to download API page: <urlopen error [WinError 10061] 由于目标计算机积极拒绝，无法 连接。> (caused by URLError(ConnectionRefusedError(10061, '由于目标计算机积极拒绝，无法连接。', None, 10061, None)))
  File "yt_dlp\extractor\common.py", line 694, in extract
  File "yt_dlp\extractor\youtube.py", line 3963, in _real_extract
  File "yt_dlp\extractor\youtube.py", line 3931, in _download_player_responses
  File "yt_dlp\extractor\youtube.py", line 3648, in _extract_player_responses
  File "yt_dlp\extractor\youtube.py", line 3613, in _extract_player_responses
  File "yt_dlp\extractor\youtube.py", line 3533, in _extract_player_response
  File "yt_dlp\extractor\youtube.py", line 932, in _extract_response
  File "yt_dlp\utils.py", line 6155, in __iter__
  File "yt_dlp\extractor\common.py", line 3734, in _error_or_warning
  File "yt_dlp\utils.py", line 6163, in report_retry
  File "yt_dlp\extractor\youtube.py", line 934, in _extract_response
  File "yt_dlp\extractor\youtube.py", line 610, in _call_api
  File "yt_dlp\extractor\common.py", line 1048, in download_content
  File "yt_dlp\extractor\common.py", line 1012, in download_handle
  File "yt_dlp\extractor\common.py", line 882, in _download_webpage_handle
  File "yt_dlp\extractor\common.py", line 839, in _request_webpage

  File "urllib\request.py", line 1348, in do_open
  File "http\client.py", line 1282, in request
  File "http\client.py", line 1328, in _send_request
  File "http\client.py", line 1277, in endheaders
  File "http\client.py", line 1037, in _send_output
  File "http\client.py", line 975, in send
  File "http\client.py", line 1447, in connect
  File "http\client.py", line 941, in connect
  File "socket.py", line 851, in create_connection
  File "socket.py", line 836, in create_connection
ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\extractor\common.py", line 821, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 3743, in urlopen
  File "urllib\request.py", line 519, in open
  File "urllib\request.py", line 536, in _open
  File "urllib\request.py", line 496, in _call_chain
  File "yt_dlp\utils.py", line 1555, in https_open
  File "urllib\request.py", line 1351, in do_open
urllib.error.URLError: <urlopen error [WinError 10061] 由于目标计算机积极拒绝，无法连接。>

'ab_channel' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
```

**Comment by coletdjnz** [comment]
Quote your URL. your shell is not padding everything after the first & to yt-dlp

**Comment by suger520HT** [comment]
![image](https://user-images.githubusercontent.com/106970209/233777081-e34dd0a5-8c6f-4fab-b848-d7ffd616e3cd.png)

**Comment by suger520HT** [comment]
![image](https://user-images.githubusercontent.com/106970209/233777176-c0b7b06b-c452-40c6-afbb-21cb100d5f4c.png)

**Comment by gamer191** [comment]
@suger520HT please send a new verbose log

**Comment by suger520HT** [comment]
[log.log](https://github.com/yt-dlp/yt-dlp/files/11301054/log.log)

**Comment by suger520HT** [comment]
PS C:\Users\Administrator> yt-dlp -vU "https://www.youtube.com/watch?v=BwH-qeAUt3g&list=PLk2gvyPpHLRe_7bNeeHyCCWyz-KeEH3Mn&ab_channel=GTVDRAMA%E5%85%AB%E5%A4%A7%E5%8A%87%E6%A8%82%E9%83%A8"
[debug] Command-line config: ['-vU', 'https://www.youtube.com/watch?v=BwH-qeAUt3g&list=PLk2gvyPpHLRe_7bNeeHyCCWyz-KeEH3Mn&ab_channel=GTVDRAMA%E5%85%AB%E5%A4%A7%E5%8A%87%E6%A8%82%E9%83%A8']
[debug] Encodings: locale cp936, fs utf-8, pref cp936, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (win_exe)
[debug] Python 3.11.2 (CPython AMD64 64bit) - Windows-10-10.0.19044-SP0 (OpenSSL 1.1.1s  1 Nov 2022)
[debug] exe versions: ffmpeg 2023-03-05-git-912ac82a3c-full_build-www.gyan.dev (setts), ffprobe 2023-03-05-git-912ac82a3c-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {'http': 'http://127.0.0.1:10809', 'https': 'http://127.0.0.1:10809', 'ftp': 'http://127.0.0.1:10809'}
[debug] Loaded 1802 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
Current Build Hash: 42056575b2fb1dfccb36e9b1404b364e7b3f263baccaccedcc45c173042bf9e3
yt-dlp is up to date (stable@2023.03.04)
[youtube:tab] Extracting URL: https://www.youtube.com/watch?v=BwH-qeAUt3g&list=PLk2gvyPpHLRe_7bNeeHyCCWyz-KeEH3Mn&ab_channel=GTVDRAMA%E5%85%AB%E5%A4%A7%E5%8A%87%E6%A8%82%E9%83%A8
[youtube:tab] Downloading playlist PLk2gvyPpHLRe_7bNeeHyCCWyz-KeEH3Mn - add --no-playlist to download just the video BwH-qeAUt3g
[youtube:tab] PLk2gvyPpHLRe_7bNeeHyCCWyz-KeEH3Mn: Downloading webpage
WARNING: [youtube:tab] <urlopen error [WinError 10061] 由于目标计算机积极拒绝，无法连接。>. Retrying (1/3)...
[youtube:tab] PLk2gvyPpHLRe_7bNeeHyCCWyz-KeEH3Mn: Downloading webpage
WARNING: [youtube:tab] <urlopen error [WinError 10061] 由于目标计算机积极拒绝，无法连接。>. Retrying (2/3)...
[youtube:tab] PLk2gvyPpHLRe_7bNeeHyCCWyz-KeEH3Mn: Downloading webpage
WARNING: [youtube:tab] <urlopen error [WinError 10061] 由于目标计算机积极拒绝，无法连接。>. Retrying (3/3)...
[youtube:tab] PLk2gvyPpHLRe_7bNeeHyCCWyz-KeEH3Mn: Downloading webpage
WARNING: [youtube:tab] Unable to download webpage: <urlopen error [WinError 10061] 由于目标计算机积极拒绝，无法连接。> (caused by URLError(ConnectionRefusedError(10061, '由于目标计算机积极拒绝，无法连接。', None, 10061, None))). Giving up after 3 retries
[youtube:tab] PLk2gvyPpHLRe_7bNeeHyCCWyz-KeEH3Mn: Downloading API parameters API JSON
WARNING: [youtube:tab] <urlopen error [WinError 10061] 由于目标计算机积极拒绝，无法连接。>. Retrying (1/3)...
[youtube:tab] PLk2gvyPpHLRe_7bNeeHyCCWyz-KeEH3Mn: Downloading API parameters API JSON
WARNING: [youtube:tab] <urlopen error [WinError 10061] 由于目标计算机积极拒绝，无法连接。>. Retrying (2/3)...
[youtube:tab] PLk2gvyPpHLRe_7bNeeHyCCWyz-KeEH3Mn: Downloading API parameters API JSON
WARNING: [youtube:tab] <urlopen error [WinError 10061] 由于目标计算机积极拒绝，无法连接。>. Retrying (3/3)...
[youtube:tab] PLk2gvyPpHLRe_7bNeeHyCCWyz-KeEH3Mn: Downloading API parameters API JSON
ERROR: [youtube:tab] PLk2gvyPpHLRe_7bNeeHyCCWyz-KeEH3Mn: Unable to download API page: <urlopen error [WinError 10061] 由于目标计算机积极拒绝，无法连接。> (caused by URLError(ConnectionRefusedError(10061, '由于目标计算机积极拒绝，无法连接。', None, 10061, None)))
  File "yt_dlp\extractor\common.py", line 694, in extract
  File "yt_dlp\extractor\youtube.py", line 4490, in wrapper
  File "yt_dlp\extractor\youtube.py", line 6273, in _real_extract
  File "yt_dlp\extractor\youtube.py", line 5171, in _extract_data
  File "yt_dlp\extractor\youtube.py", line 5176, in _extract_tab_endpoint
  File "yt_dlp\extractor\youtube.py", line 932, in _extract_response
  File "yt_dlp\utils.py", line 6155, in __iter__
  File "yt_dlp\extractor\common.py", line 3734, in _error_or_warning
  File "yt_dlp\utils.py", line 6163, in report_retry
  File "yt_dlp\extractor\youtube.py", line 934, in _extract_response
  File "yt_dlp\extractor\youtube.py", line 610, in _call_api
  File "yt_dlp\extractor\common.py", line 1048, in download_content
  File "yt_dlp\extractor\common.py", line 1012, in download_handle
  File "yt_dlp\extractor\common.py", line 882, in _download_webpage_handle
  File "yt_dlp\extractor\common.py", line 839, in _request_webpage

  File "urllib\request.py", line 1348, in do_open
  File "http\client.py", line 1282, in request
  File "http\client.py", line 1328, in _send_request
  File "http\client.py", line 1277, in endheaders
  File "http\client.py", line 1037, in _send_output
  File "http\client.py", line 975, in send
  File "http\client.py", line 1447, in connect
  File "http\client.py", line 941, in connect
  File "socket.py", line 851, in create_connection
  File "socket.py", line 836, in create_connection
ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\extractor\common.py", line 821, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 3743, in urlopen
  File "urllib\request.py", line 519, in open
  File "urllib\request.py", line 536, in _open
  File "urllib\request.py", line 496, in _call_chain
  File "yt_dlp\utils.py", line 1555, in https_open
  File "urllib\request.py", line 1351, in do_open
urllib.error.URLError: <urlopen error [WinError 10061] 由于目标计算机积极拒绝，无法连接。>

PS C:\Users\Administrator>

**Comment by gamer191** [comment]
um, do you have internet? Is your proxy online?

**Comment by lhs55502002** [comment]
I have the same problem,too.I can open the website of the youtuber,but just have the above problem.

**Comment by suger520HT** [comment]
Only youtube can't use proxy to download other websites yt-dlp is normal

**Comment by suger520HT** [comment]
Both v2ray and clash for windows cannot be downloaded in the proxy mode. The tun mode can be used normally. Only youtube yt-dlp can’t go to proxy other websites. There is no problem.

**Comment by suger520HT** [comment]
Youtube just can't use yt-dlp to download but can use the webpage normally

**Comment by suger520HT** [comment]
The proxy software I use now is v2rayn, but I can’t use yt-dlp to download youtube in the system proxy mode if I switch to Clash

**Comment by suger520HT** [comment]
Using tun mode does not have the above problems

**Comment by suger520HT** [comment]
![image](https://user-images.githubusercontent.com/106970209/233785408-c0b63ba5-473e-41c0-a02d-6bf81fe3a050.png)

**Comment by coletdjnz** [comment]
The issue now is with your proxy, or the proxy URL you provided

**Comment by suger520HT** [comment]
I don’t know what’s the problem today, as long as I use the system proxy, I can’t download the tun mode, but I have tried other websites without any problems, only youtube can’t be downloaded but can be accessed normally

**Comment by pukkandan** [comment]
The issue with proxy will have to be figured out by you. We cannot solve it.

**Comment by tinybug** [comment]
Hi, @pukkandan is there a way to make urllib.request DNS over http? www.youtube.com DNS is hijacked in some places

**Comment by tinybug** [comment]
it's weird that the curl can download the page if I set the same proxy: 

![image](https://user-images.githubusercontent.com/3439875/235188779-40ac19be-40c4-4f99-ba34-68a0ce0f9ab7.png)

in python, I will get 127.0.0.1 whatever I do, it make yt-dlp get the wrong IP too.

![image](https://user-images.githubusercontent.com/3439875/235189840-51480d32-41db-4ef7-b6d9-9fc97b154122.png)

if I use nslookup -vc www.youtube.com (TCP mode), I will get the right IP

![image](https://user-images.githubusercontent.com/3439875/235190465-e8fb4d23-3951-4c7f-96f3-625a029166a5.png)

if I use nslookup www.youtube.com (UDP mode), I will get the wrong IP

![image](https://user-images.githubusercontent.com/3439875/235190677-b7ba6119-f60c-438b-8ef0-1b6aa15b6b81.png)

@pukkandan  can yt-dlp perform as curl?

**Comment by wanghao14** [comment]
> @suger520HT please try to ping [www.youtube.com](http://www.youtube.com), you may get the wrong ip like this
> 
> ![image](https://user-images.githubusercontent.com/3439875/234929307-d68d9d16-6b94-4f43-90c5-22e2c1425760.png)

Thank you very much!

**Comment by doglex** [comment]
solved by setting “Internet  Options” of IE. Keep empty  of  Exclude address（例外）, then everything is ok.

![image](https://github.com/yt-dlp/yt-dlp/assets/7918755/f471d3a3-b8ff-43d2-a909-3180b76879d4)

![image](https://github.com/yt-dlp/yt-dlp/assets/7918755/8ce32d1c-d359-4ce2-a95f-aeb8bbd900ef)
