### ISSUE TITLE
Possible download failure due to large video file size, requesting segmented download function

### ISSUE THREAD

**Issue by TeemoZhang-ice** [yt-dlp/yt-dlp#6886]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

When I downloaded a large file, I received a prohibited error message. The maximum download time was 30%, but it failed. I have tried many times.
For example, link: https://www.youtube.com/watch?v=hlfYAWRq2Ig

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
> ###
> When I downloaded a large file, I received a prohibited error message. The maximum download time was 30%, but it failed. I have tried many times. For example, link: [youtube.com/watch?v=hlfYAWRq2Ig](https://www.youtube.com/watch?v=hlfYAWRq2Ig)

Wrong template? That sounds like a bug report! Show verbose log

**Comment by gamer191** [comment]
> requesting segmented download function
I hardly understand your question, but if you use `--extractor-args "youtube:include_duplicate_formats"` it will enable segmented "dashy" formats

**Comment by TeemoZhang-ice** [comment]
@Pukkandan, okay, I will try to join the log

**Comment by TeemoZhang-ice** [comment]
![image](https://user-images.githubusercontent.com/64951564/233777217-d3e61121-a591-4488-919d-f1931cf96be9.png)

I couldn't find a file similar to the log. I tried to submit this feedback information, please don't mind. I'm not very familiar with the usage of the software. Thank you very much for the author's prompt feedback

**Comment by pukkandan** [comment]
The instructions are right there on the template...

> ### Provide verbose output that clearly demonstrates the problem
> * [ ]  Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
> * [ ]  Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by TeemoZhang-ice** [comment]
Okay, I'll do it again right away, thank you.

**Comment by TeemoZhang-ice** [comment]
Hello author! It seems to be running normally. Just now, after I ran a command with - vU, it automatically downloaded a new yt dlp.exe program, and so far, there have been no error messages.
Currently, the download is ongoing. Thank you very much for your reply, as well as this enthusiastic netizen @ gamer191. Thank you for your help. Next time, I will provide more formal bug feedback. This is my first time providing feedback and I am not very proficient.

**Comment by gamer191** [comment]
> it automatically downloaded a new yt dlp.exe program

Makes sense, yt-dlp automatically updates when you run that command :)
