### ISSUE TITLE
Option to not use ffmpeg downloader

### ISSUE THREAD

**Issue by nobl2** [yt-dlp/yt-dlp#6891]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Hi.

Everytime i use this program not on youtube its using the ffmpeg downloader and my internet drops out or my pc crashes i cannot use any of the video downloaded.. and restart whole download....

mpv video player shows when i try to play:
`[ffmpeg/demuxer] mov,mp4,m4a,3gp,3g2,mj2: moov atom not found
[lavf] avformat_open_input() failed
[ffmpeg/demuxer] mov,mp4,m4a,3gp,3g2,mj2: moov atom not found
[lavf] avformat_open_input() failed
Failed to recognize file format.`

how do i not use ffmpeg downloader? always this problem...

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
> Everytime i use this program not on youtube

What sites? Are they livestreams? You did not provide any example URLs or a log.

Currently, some content can only be downloaded with ffmpeg, such a live HLS streams

**Comment by nobl2** [comment]
some are livestream.. others ok to resume

file is .ts TS livestream fragment

how can i extractor HLS livestream link for later? on other downloader

**Comment by pukkandan** [comment]
> how can i extractor HLS livestream link for later?

    --print urls
