### ISSUE TITLE
[Youtube] cannot read "Releases" tab

### ISSUE THREAD

**Issue by qwrwed** [yt-dlp/yt-dlp#6893]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that a **supported** site is broken
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United Kingdom

#### Issue:
yt-dlp cannot read the (possibly new to Youtube) _Releases_ tab for music artists.

Example: https://www.youtube.com/@daftpunk/releases has a page with a few dozen playlists, but nothing is downloaded when providing that URL to yt-dlp.

I have tried investigating by modifying the python code and found the following cause and solution:

#### Cause:
- Adding a `breakpoint()` to `YoutubeTabBaseInfoExtractor`'s [_extract_entries()](https://github.com/yt-dlp/yt-dlp/blob/2023.03.04/yt_dlp/extractor/youtube.py#L4667) shows that each of the contents of the _Releases_ tab is a `richItemRenderer` containing some amount of playlists.
- This causes us to run [_rich_entries()](https://github.com/yt-dlp/yt-dlp/blob/2023.03.04/yt_dlp/extractor/youtube.py#L4578-L4584) on that renderer, which specifically looks for videos and only videos, missing the playlists.

#### Proposed solution:
Update `YoutubeTabBaseInfoExtractor._rich_entries()` to attempt to extract playlists (using the playlist code from `YoutubeTabBaseInfoExtractor._grid_entries()`).

I tried making this change locally, and it seemed to work. This is the new function:
```
    def _rich_entries(self, rich_grid_renderer):
        # video
        renderer = traverse_obj(rich_grid_renderer, ('content', ('videoRenderer', 'reelItemRenderer')), get_all=False) or {}
        video_id = renderer.get('videoId')
        if video_id:
            yield self._extract_video(renderer)
        # playlist
        renderer = traverse_obj(rich_grid_renderer, ('content', ('playlistRenderer')), get_all=False) or {}
        title = self._get_text(renderer, 'title')
        playlist_id = renderer.get('playlistId')
        if playlist_id:
            yield self.url_result(
                'https://www.youtube.com/playlist?list=%s' % playlist_id,
                ie=YoutubeTabIE.ie_key(), video_id=playlist_id,
                video_title=title)
```
This is the output from before the change:
```
(venv) PS G:\Documents\Projects\_own\yt-dlq> python -c "import yt_dlp; yt_dlp.YoutubeDL({'extract_flat': True}).extract_info('https://www.youtube.com/@daftpunk/releases')"   
[youtube:tab] Extracting URL: https://www.youtube.com/@daftpunk/releases 
[youtube:tab] @daftpunk/releases: Downloading webpage 
[download] Downloading playlist: Daft Punk - Releases 
[youtube:tab] UC_kRDKYrUlrbtrSiyu5Tflg page 1: Downloading API JSON 
[youtube:tab] Playlist Daft Punk - Releases: Downloading 0 items of 0 
[download] Finished downloading playlist: Daft Punk - Releases 
```
And this is the output from after:
```
(venv) PS G:\Documents\Projects\_own\yt-dlq> python -c "import yt_dlp; yt_dlp.YoutubeDL({'extract_flat': True}).extract_info('https://www.youtube.com/@daftpunk/releases')"   
[youtube:tab] Extracting URL: https://www.youtube.com/@daftpunk/releases 
[youtube:tab] @daftpunk/releases: Downloading webpage 
[download] Downloading playlist: Daft Punk - Releases 
[youtube:tab] UC_kRDKYrUlrbtrSiyu5Tflg page 1: Downloading API JSON 
[youtube:tab] Playlist Daft Punk - Releases: Downloading 36 items of 36 
[download] Downloading item 1 of 36 
[download] Downloading item 2 of 36 
<this repeats for items 3 through 35>
[download] Downloading item 36 of 36
[download] Finished downloading playlist: Daft Punk - Releases
```

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
(venv) PS G:\Documents\Projects\_own\yt-dlq> yt-dlp https://www.youtube.com/@daftpunk/releases -vU
[debug] Command-line config: ['https://www.youtube.com/@daftpunk/releases', '-vU']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8 
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (pip) 
[debug] Python 3.10.5 (CPython AMD64 64bit) - Windows-10-10.0.19044-SP0 (OpenSSL 1.1.1n  15 Mar 2022) 
[debug] exe versions: none 
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.2
[debug] Proxy map: {} 
[debug] Loaded 1786 extractors 
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest 
Available version: stable@2023.03.04, Current version: stable@2023.03.04 
yt-dlp is up to date (stable@2023.03.04) 
[youtube:tab] Extracting URL: https://www.youtube.com/@daftpunk/releases 
[youtube:tab] @daftpunk/releases: Downloading webpage 
[debug] [youtube:tab] Selected tab: 'releases' (releases), Requested tab: 'releases' 
[download] Downloading playlist: Daft Punk - Releases 
[youtube:tab] UC_kRDKYrUlrbtrSiyu5Tflg page 1: Downloading API JSON 
[youtube:tab] Playlist Daft Punk - Releases: Downloading 0 items of 0 
[download] Finished downloading playlist: Daft Punk - Releases
```

**Comment by dirkf** [comment]
Similar code, in the `YoutubeTabIE._rich_grid_entries()` method, to that proposed here gets the Daft releases playlist in yt-dl.
