### ISSUE TITLE
JioSaavn

### ISSUE THREAD

**Issue by nitin2953** [yt-dlp/yt-dlp#6894]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [x] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [x] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

India

### Example URLs

Song: https://www.jiosaavn.com/song/masakali/BF80RTVdfUU
Song: https://www.jiosaavn.com/song/genda-phool/IzJGBxl4eGI
Album: https://www.jiosaavn.com/album/delhi-6/N,RbkHcwcIc_
Artist: https://www.jiosaavn.com/artist/arijit-singh-songs/LlRWpHzy3Hk_

### Provide a description that is worded well enough to be understood

The site just fetch mp4/m4a files,
I can download them with help of browser's devtools.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.jiosaavn.com/song/masakali/BF80RTVdfUU']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (pip)
[debug] Python 3.11.1 (CPython AMD64 64bit) - Windows-10-10.0.22621-SP0 (OpenSSL 1.1.1q  5 Jul 2022)
[debug] exe versions: ffmpeg 5.1.2-full_build-www.gyan.dev (setts), ffprobe 5.1.2-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.2
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
yt-dlp is up to date (stable@2023.03.04)
[generic] Extracting URL: https://www.jiosaavn.com/song/masakali/BF80RTVdfUU
[generic] BF80RTVdfUU: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] BF80RTVdfUU: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://www.jiosaavn.com/song/masakali/BF80RTVdfUU
Traceback (most recent call last):
  File "C:\Users\nitin\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\YoutubeDL.py", line 1518, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nitin\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\YoutubeDL.py", line 1594, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "C:\Users\nitin\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\extractor\common.py", line 694, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nitin\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\extractor\generic.py", line 2510, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.jiosaavn.com/song/masakali/BF80RTVdfUU
```

**Comment by sqrtNOT** [comment]
Do you have any examples that don't require a pro subscription to listen to? I'm clicking around but everything seems to require one.

**Comment by pukkandan** [comment]
Seems to be geo-restriction at play. I can play OP's URL without account.

**Comment by bashonly** [comment]
Support for `/song/` and `/album/` URLs was added in b530118e7f48232cacf8050d79a6b20bdfcf5468. Update to the latest version

`/artist/` URLs are not yet supported. @nitin2953 do you wish to keep this issue open to request support for these?

**Comment by aryanchoudharypro** [comment]
will the support for artests be added? or any way to acheev the downloads

**Comment by bashonly** [comment]
@aryanchoudharypro could you open a new "site feature request" issue for this, please? and be sure to include working example links (at least two)

**Comment by aryanchoudharypro** [comment]
Will surely do it, thanks
