### ISSUE TITLE
[iwara.tv] Can't download only some videos

### ISSUE THREAD

**Issue by Rektis** [yt-dlp/yt-dlp#6899]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that a **supported** site is broken
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Provide a description that is worded well enough to be understood

# Problem:
yt-dlp can download **most** videos off iwara, but **not some**. 
Iwara says: `errors.notFound;`

# Additional info:
I'm not seeing the pattern of which ones don't work, but here are some examples:

Videos that can be downloaded:
```
https://www.iwara.tv/video/GXzAR1D4Vhtj9T/tentacle11
https://www.iwara.tv/video/vdmg0t5ljoueylmob/gyaru-rin-strip-club-gangbang
https://www.iwara.tv/video/ye0UdtouHxwKz4/mmd-r18gee
```

Videos that **can't** be downloaded:
```
https://www.iwara.tv/video/25qsaIn2qhH5nU
https://www.iwara.tv/video/bwjxrie4j2fe6lkwa/kangxi-fuckin-ankha-zone
https://www.iwara.tv/video/3g9NZd4wQubxSu/mmd-breath-of-life-lo-chan
```

iwara.tv recently (~1 month ago) changed their URL format from just the ID to it also including part of the video title, so
`https://www.iwara.tv/video/bwjxrie4j2fe6lkwa` (the old format)
turned into
`https://www.iwara.tv/video/bwjxrie4j2fe6lkwa/kangxi-fuckin-ankha-zone` (the new format)

Some videos are using the new format, some the old format.
So far, I haven't been able to download any videos using the old format.

These videos are all playable in the browser, so they are not part of the videos that are being converted and thus not downloadable.

# How it could be fixed; Proposed Solution
I don't know, sorry. But since some videos are downloadable just fine, it can't be totally broken.

# Version
using latest nightly version: 
`2023.04.22.232519`

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.iwara.tv/video/bwjxrie4j2fe6lkwa']
[debug] Encodings: locale cp932, fs utf-8, pref cp932, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2023.04.22.232519 [80b732b7a] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 5.0-full_build-www.gyan.dev (setts), ffprobe 5.0-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.2
[debug] Proxy map: {}
[debug] Loaded 1802 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Available version: nightly@2023.04.22.232519, Current version: nightly@2023.04.22.232519
Current Build Hash: b4672ce52a8bd58011f0fbd84faf9ac6a2ecb2475b40e17de8f4f555a0f4d790
yt-dlp is up to date (nightly@2023.04.22.232519)
[iwara] Extracting URL: https://www.iwara.tv/video/bwjxrie4j2fe6lkwa
[iwara] bwjxrie4j2fe6lkwa: Downloading JSON metadata
ERROR: [iwara] bwjxrie4j2fe6lkwa: Iwara says: errors.notFound; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 694, in extract
  File "yt_dlp\extractor\iwara.py", line 88, in _real_extract
```

**Comment by Lesmiscore** [comment]
How did you know these videos do exist?
![image](https://user-images.githubusercontent.com/10355528/233917673-e692a19a-24a5-4eca-a77c-6abf9009c51a.png)

**Comment by user1872372839** [comment]
Iwara is currently hiding videos with certain "problematic" tags (e;g: pee), and only registered accounts can see them (and there's also an option to blacklist them).

Currently, the nightly version of yt-dlp does not work with either private videos, nor these "hidden" videos.
