### ISSUE TITLE
download subtitle commands in the conf file

### ISSUE THREAD

**Issue by tXJtqlb3bbeKD1yW8SV7** [yt-dlp/yt-dlp#6906]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Hi. I've been using https://gpodder.github.io/ to fetch YouTube videos and download them (the application uses Yt-dlp to do that). But I want to download the auto-generated subtitles as well every time the video is downloaded and store them in a specific folder. I tried the write the following to my yt-dlp.conf, but it didn't work. Appreciate any help.

```
--write-auto-subs 
--sub-lang en
-o %USERPROFILE%\Downloads\Youtube Subtitles\%(title)s-%(id)s.%(ext)s

```

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by gamer191** [comment]
1. filepaths should be quoted:
```
-o "%USERPROFILE%\Downloads\Youtube Subtitles\%(title)s-%(id)s.%(ext)s"
```
2. add `subtitle:` to the start of the output template, if you want it to only apply for subtitles (and not videos):
```
-o "subtitle:%USERPROFILE%\Downloads\Youtube Subtitles\%(title)s-%(id)s.%(ext)s"
```
3. unless you specifically want to only download auto-subs, I'd suggest adding `--write-subs` to your config (although I don't know what will happen if both types of subs are available)

**Comment by gamer191** [comment]
4. if you want further support, please post a verbose output (add `--verbose` to your config and send yt-dlp's full output)

**Comment by bashonly** [comment]
@tXJtqlb3bbeKD1yW8SV7 Are you asking about using your yt-dlp.conf with gpodder?

gpodder embeds yt-dlp and uses its python API, so it will not load your config file, and they hardcode the options:
https://github.com/gpodder/gpodder/blob/master/share/gpodder/extensions/youtube-dl.py#L336

It looks like you've already raised this issue with the gpodder devs, but they don't want to implement this feature
https://github.com/gpodder/gpodder/issues/1501

So if you are asking specifically about using gpodder, then your choices are:
 - use standalone yt-dlp instead and heed gamer191's advice
 - wait for gpodder devs to change their minds
 - fork gpodder and implement it yourself

**Comment by tXJtqlb3bbeKD1yW8SV7** [comment]
I thought, since the gpodder uses yt-dlp to download the videos, the config file would apply to the download too, didn't know about the embedding thing. Thanks for the fast answers anyways.
