### ISSUE TITLE
How to call aria2 inside the container, I want to use the --downloader parameter, but aria2 is in the container.

### ISSUE THREAD

**Issue by himonster1** [yt-dlp/yt-dlp#6916]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

How to call aria2 inside the container, I want to use the --downloader parameter, but aria2 is in the container, using this project: https://github.com/P3TERX/Aria2-Pro-Docker

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
How would you use it without yt-dlp?

**Comment by himonster1** [comment]
> How would you use it without yt-dlp?

Previously I was using webui directly with ariang to access the operation, and yt-dlp is no webui, so I want to know how to add the task to aria2-pro

**Comment by pukkandan** [comment]
Unless you can access it via CLI, you can't use it with yt-dlp
