### ISSUE TITLE
Removing the --write-annotations option

### ISSUE THREAD

**Issue by Zirro** [yt-dlp/yt-dlp#692]
The `--write-annotations` option was created for the purpose of saving the overlaid annotations that used to exist on YouTube videos in an `.annotations.xml` file. However, YouTube deprecated their annotations feature in 2017 and later removed annotations from all existing videos in [early 2019](https://mashable.com/article/the-death-of-youtube-annotations).

To my knowledge the option serves no purpose today, so it should be okay to either deprecate it or remove it outright. This would allow for some cleanup throughout the code and documentation where annotations are currently mentioned.

**Comment by pukkandan** [comment]
> This would allow for some cleanup throughout the code and documentation where annotations are currently mentioned.

There really isn't much cleanup that can be done in the code by deprecating this. The only thing that changes is that it will no longer appear in the docs
