### ISSUE TITLE
[youtube] weird language codes for some subtitles

### ISSUE THREAD

**Issue by chrizilla** [yt-dlp/yt-dlp#6926]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that a **supported** site is broken
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Provide a description that is worded well enough to be understood

I get weird language codes for this youtube video:
https://www.youtube.com/watch?v=gk1BViilFFk

```
SpaceX Starship explodes on first launch attempt [youtube.gk1BViilFFk] {597+599}.en.ttml
SpaceX Starship explodes on first launch attempt [youtube.gk1BViilFFk] {597+599}.en-JkeT_87f4cc.ttml
SpaceX Starship explodes on first launch attempt [youtube.gk1BViilFFk] {597+599}.en-uYU-mmqFLq8.ttml
```

The codes don't correspond to the screenshot:

![subs](https://user-images.githubusercontent.com/43895159/234712077-9e42545d-1996-4f61-ba6b-6066a64af2f5.png)

From the log below, this is apparently how the language codes are provided by youtube, but maybe this could be improved by taking the name from the (more meaningful) "name" column ?

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[info] Available subtitles for gk1BViilFFk:
Language       Name             Formats
en             English          vtt, ttml, srv3, srv2, srv1, json3
en-uYU-mmqFLq8 English - CC1    vtt, ttml, srv3, srv2, srv1, json3
en-JkeT_87f4cc English - DTVCC1 vtt, ttml, srv3, srv2, srv1, json3
```

**Comment by pukkandan** [comment]
No. code is for unique identification, name is for human readability.
