### ISSUE TITLE
yt-dlp works for videos in section 1, but when it reaches section 2, it does a redirect to the section 1 (kodekloud)

### ISSUE THREAD

**Issue by joseeden** [yt-dlp/yt-dlp#6927]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that a **supported** site is broken
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Singapore

### Provide a description that is worded well enough to be understood

I've tried yt-dlp on a course I've paid for in Kodekloud.. I'm able to play all videos while signed in to Kodekloud.
When I try to download all videos, I can only download the videos in section 1.  When I specify a video in section 2, it redirects to page on sectino 1.

URL for Section 1: https://kodekloud.com/courses/devsecops/
URL for Section 2: https://kodekloud.com/topic/section-2-topics-2/

This can be seen from the output logs below.
I've tried this on all videos in other sections, the problems occurs in all of them except those videos in section 1.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://kodekloud.com/topic/section-2-topics-2/']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (zip)
[debug] Python 3.8.10 (CPython x86_64 64bit) - Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.29 (OpenSSL 1.1.1f  31 Mar 2020, glibc 2.31)
[debug] exe versions: ffmpeg 4.2.7, ffprobe 4.2.7
[debug] Optional libraries: certifi-2019.11.28, no_Cryptodome-None, secretstorage-2.3.1, sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
Current Build Hash: 91cad9f121c1f6f0a81b747415c46ecba0ff331ed38cc6433040b4ac7b6e15ca
yt-dlp is up to date (stable@2023.03.04)
[generic] Extracting URL: https://kodekloud.com/topic/section-2-topics-2/
[generic] section-2-topics-2: Downloading webpage
[redirect] Following redirect to https://kodekloud.com/courses/devsecops/
[generic] Extracting URL: https://kodekloud.com/courses/devsecops/
[generic] devsecops: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] devsecops: Extracting information
[debug] Looking for embeds
[debug] Identified a vimeo embed
[vimeo] Extracting URL: https://player.vimeo.com/video/736115002?h=460ea4b6cc&dnt=1&app_id=122963#__youtubedl_smuggle=%7B%22http_headers%22%3A+%7B%22Referer%22%3A+%22https%3A%2F%2Fkodekloud.com%2Fcourses%2Fdevsecops%2F%22%7D%7D
[vimeo] 736115002: Downloading webpage
[vimeo] 736115002: Downloading akfire_interconnect_quic m3u8 information
[vimeo] 736115002: Downloading akfire_interconnect_quic m3u8 information
[vimeo] 736115002: Downloading fastly_skyfire m3u8 information
[vimeo] 736115002: Downloading fastly_skyfire m3u8 information
[vimeo] 736115002: Downloading akfire_interconnect_quic MPD information
[vimeo] 736115002: Downloading akfire_interconnect_quic MPD information
[vimeo] 736115002: Downloading fastly_skyfire MPD information
[vimeo] 736115002: Downloading fastly_skyfire MPD information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, lang, vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 736115002: Downloading 1 format(s): dash-fastly_skyfire_sep-video-3907c518+dash-fastly_skyfire_sep-audio-540d1528
[download] 010-000-welcome-and-course-introductio [736115002].mp4 has already been downloaded
```

**Comment by bashonly** [comment]
Without being logged in, my browser redirects me to the "section 1" URL when I try to navigate to your "section 2" URL. So you should try passing cookies to yt-dlp:

add `--cookies-from-browser chrome` to your command (or replace `chrome` with whatever browser you are logged in with)

If that fails, then the generic extractor isn't capable of finding all the Vimeo embeds in the pages, and the site needs a dedicated extractor (which will only be possible if someone is willing to share their account credentials)

**Comment by gamer191** [comment]
this issue will be reopened once someone provides a log with `--cookies-from-browser`, following @bashonly's instructions
