### ISSUE TITLE
cann't download  vip audio file from ximalay web use --cookies

### ISSUE THREAD

**Issue by xyx361100238** [yt-dlp/yt-dlp#6928]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

I am a VIP member of the www.ximalya.com and can log in to listen to VIP audio. Then, use the [Get cookies.txt LOCALLY](https://chrome.google.com/webstore/detail/get-cookiestxt-locally/cclelndahbckbenkjhflpdbgdldlbecc) tool to obtain cookies using the command 
`yt dlp -- cookies www.ximalaya.com_cookies.txt https://www.ximalaya.com/sound/454636484 `
Error prompt: [ximalaya] 454636484: No video formats found!; 
Using
` yt dlp -- cookies www.ximalaya.com_cookies.txt https://www.ximalaya.com/sound/18556415` 
Can complete audio download (non VIP)

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp -vU --cookies www.ximalaya.com_cookies.txt https://www.ximalaya.com/sound/454636484
[debug] Command-line config: ['-vU', '--cookies', 'www.ximalaya.com_cookies.txt', 'https://www.ximalaya.com/sound/454636484']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (pip)
[debug] Python 3.8.16 (CPython x86_64 64bit) - Linux-4.15.0-197-generic-x86_64-with-glibc2.17 (OpenSSL 1.1.1t  7 Feb 2023, glibc 2.31)
[debug] exe versions: ffmpeg 4.2.7, ffprobe 4.2.7
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2021.10.08, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.2
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
ERROR: Unable to obtain version info; Please try again later or visit  https://github.com/yt-dlp/yt-dlp/releases/latest
[debug] Using fake IP 36.178.225.248 (CN) as X-Forwarded-For
[ximalaya] Extracting URL: https://www.ximalaya.com/sound/454636484
[ximalaya] 454636484: Downloading info json https://m.ximalaya.com/tracks/454636484.json
ERROR: [ximalaya] 454636484: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "/home/youxixie/anaconda3/envs/videoEnv/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 1518, in wrapper
    return func(self, *args, **kwargs)
  File "/home/youxixie/anaconda3/envs/videoEnv/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 1615, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/home/youxixie/anaconda3/envs/videoEnv/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 1674, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/home/youxixie/anaconda3/envs/videoEnv/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 2615, in process_video_result
    self.raise_no_formats(info_dict)
  File "/home/youxixie/anaconda3/envs/videoEnv/lib/python3.8/site-packages/yt_dlp/YoutubeDL.py", line 1046, in raise_no_formats
    raise ExtractorError(msg, video_id=info['id'], ie=info['extractor'],
yt_dlp.utils.ExtractorError: [ximalaya] 454636484: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

**Comment by mingzhang96** [comment]
Hi @xyx361100238 Same issue here. Do you have any idea on this problem?

**Comment by xingchensong** [comment]
fixed in https://github.com/yt-dlp/yt-dlp/pull/10832
