### ISSUE TITLE
[Q] are there really no other transcodes on odysee.com?

### ISSUE THREAD

**Issue by toscompliantname** [yt-dlp/yt-dlp#693]
I'm not familiar with how this tool or odysee.com works.
Do odysee really not transcode videos to other resolutions or is it just a yt-dlp related limitation that you can't choose other formats? - when I run "yt-dlp -F https://odysee.com/@iamRucka:0/Like-a-Cop-Small:3" i get the following:
```
[lbry] @iamRucka#0/Like-a-Cop-Small#3: Downloading stream JSON metadata
[lbry] 3dd033ae623974565bf3900334bcd7828845683a: Downloading streaming url JSON metadata
[lbry] @iamRucka#0/Like-a-Cop-Small#3: Downloading streaming redirect url info
ERROR: No video formats found
```

**Comment by october262** [comment]
youtube-dl reports it as format code 0  
which there is no fix yet.

**Comment by pukkandan** [comment]
lbry should have 1 format. yt-dlp not showing it in -F is a bug

> Do odysee really not transcode videos to other resolutions

Not afaik

**Comment by pukkandan** [comment]
I assume the question has been answered
