### ISSUE TITLE
missing print output at some stages

### ISSUE THREAD

**Issue by chrizilla** [yt-dlp/yt-dlp#6937]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

To clarify how yt-dlp's stages work, I'd like to ask why I don't get a print output in some stages with this config:
<details>
<summary>config</summary>

```
--print pre_process:"
========================================================= %(epoch>%Y-%m-%d [%H:%M:%S])s ========== stage: pre_process ===================================================================
"
--print after_filter:"
========================================================= %(epoch>%Y-%m-%d [%H:%M:%S])s ========== stage: after_filter ===================================================================
"
--print video:"
========================================================= %(epoch>%Y-%m-%d [%H:%M:%S])s ========== stage: video ===================================================================
"
--print before_dl:"
========================================================= %(epoch>%Y-%m-%d [%H:%M:%S])s ========== stage: before_dl ===================================================================
"
--print post_process:"
========================================================= %(epoch>%Y-%m-%d [%H:%M:%S])s ========== stage: post_process ===================================================================
"
--print after_move:"
========================================================= %(epoch>%Y-%m-%d [%H:%M:%S])s ========== stage: after_move ===================================================================
"
--print after_video:"
========================================================= %(epoch>%Y-%m-%d [%H:%M:%S])s ========== stage: after_video ===================================================================
"
--print playlist:"
========================================================= %(epoch>%Y-%m-%d [%H:%M:%S])s ========== stage: playlist ===================================================================
"
``` 

</details>

I don't get a print output for these stages: `pre_process , after_move , playlist `

The `playlist` stage is probably not entered because it is not a playlist.
But what about the other stages? Do all of them occur one-by-one, or ONLY if something happens at that stage ?

If that's unrelated to the missing print output, what else could be the reason ?

In #6920 I got print output for all stages (except playlist).

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

I omit the full log for the time being because I think it would be too complicated to investigate.

**Comment by pukkandan** [comment]
> ### Provide verbose output that clearly demonstrates the problem
> * [ ]  Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
> * [ ]  Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below
> 
> ### Complete Verbose Output
> _No response_

**Comment by pukkandan** [comment]
When a pre_processor errors, yt-dlp skips all further processing in that stage. Whether printing should be treated as part of that "processing" is arguable, but in general, if you don't want this to happen, ue `-i`

**Comment by pukkandan** [comment]
Now print bypasses errors
