### ISSUE TITLE
[debug] Testing thumbnail 41 (FREEZE)

### ISSUE THREAD

**Issue by GabenCrying** [yt-dlp/yt-dlp#694]
```
[download] Downloading video 3 of 212
[debug] [youtube] Extracting URL: vaTa14fmNnM
[youtube] vaTa14fmNnM: Downloading webpage
[youtube] vaTa14fmNnM: Downloading android player API JSON
[debug] Sort order given by extractor: quality, height, fps, source
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, height, fps, source, res, vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, id
[debug] Testing thumbnail 41


```

Any way to get around this hang? Just sticks forever. 

I have tried adding ```--no-write-thumbnail``` but does not fix. Any ideas are appreciated!

**Comment by pukkandan** [comment]
Use `--no-check-formats` to disable the checks. Note that this will write wrong thumbnail data to infojson.

Or, if you want the checking, but just want to make it timeout faster, set a small value for `--socket-timeout`
