### ISSUE TITLE
yt-dlp w Sinusbot error

### ISSUE THREAD

**Issue by DAIIIIIIIIIIIIII** [yt-dlp/yt-dlp#6942]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I just resumed my TS3 bot for listening to music (Sinusbot x Windows). But I realized it wasn't working because youtube-dl wasn't working. So I went to the official website to download the latest version, noticing precisely that it was dated 17/02/2021. I still tried to download it but it doesn't work (obviously). Reading through several forums I precisely learned about this fork that precisely took over the functionality of youtube-dl, but continuously updated it. intrigued I first checked on the Sinusbot forum that precisely this "new version was supported by the bot, noting that some users were able to install it and make it work as if nothing was wrong, quietly. So I went to the official github page of yt-dlp and downloaded the 64-bit .exe file. I pasted the file into the right repository and edited the config.ini file to update the pointer to the new file. The file was read and configured correctly, but when I did to test it, I went to the "load" section of the bot gui, and pasted the URL of any song copied from youtube, seeing that I got back a strange error that I had never seen before:

could not decode downloader output: json: cannot unmarshal numeber 30.84 into Go struct field YTDLFormat.abr or type int

I tried on the FAQ and Issue to see if there was any similar error, but I couldn't find anything; neither on the yt-dlp page, nor on the Sinusbot page.
Can anyone help me and tell me how I can fix this error?

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
You would have to ask Sinusbot community

https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md##is-your-question-about-yt-dlp

**Comment by DAIIIIIIIIIIIIII** [comment]
so the error is not from yt-dlp but from sinusbot according to what you say.
Out of curiosity, does yt-dlp ulilize the same commands that youtube-dlp used? does it use the same language? does it have the ability to be used on sinusbot? or is this not your field and so sinusbot has to adapt?

> You would have to ask Sinusbot devs/community
> 
> https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-your-question-about-yt-dlp

so the error is not from yt-dlp but from sinusbot according to what you say.
Out of curiosity, does yt-dlp ulilize the same commands that youtube-dlp used? does it use the same language? does it have the ability to be used on sinusbot? or is this not your field and so sinusbot has to adapt?

**Comment by pukkandan** [comment]
> Out of curiosity, does yt-dlp ulilize the same commands that youtube-dlp used? does it use the same language?

Yes, though there are some differences.

> does it have the ability to be used on sinusbot?

I wouldn't know. Ask them...

**Comment by DAIIIIIIIIIIIIII** [comment]
> > Out of curiosity, does yt-dlp ulilize the same commands that youtube-dlp used? does it use the same language?
> 
> Yes, though there are some differences.
> 
> > does it have the ability to be used on sinusbot?
> 
> I wouldn't know. Ask them...

thank you very much for your help
