### ISSUE TITLE
[site request] gracieuniversity.com

### ISSUE THREAD

**Issue by m1karii** [yt-dlp/yt-dlp#6945]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Worldwide (afaik)

### Example URLs

- course / playlist: https://www.gracieuniversity.com/Pages/Public/Course?se=52
- course / playlist: https://www.gracieuniversity.com/Pages/Public/Course?enc=KuNLpG9DbyfWs%2fQyRRJYjA%3d%3d
- course / playlist: https://www.gracieuniversity.com/Pages/Public/Course?se=45
- course / playlist: https://www.gracieuniversity.com/Pages/Public/Course?enc=vsGdmSaTikLU4BRiE%2fqMwA%3d%3d
- lesson / video: https://www.gracieuniversity.com/Pages/Public/Lesson.aspx?sh=269&se=52
- lesson / video: https://www.gracieuniversity.com/Pages/Players/FVLessonPlayerBC?enc=kc1WA%2fRGzNmcB4EPDxYGax0zQvDIrlsTrctcEbiqe1QIO%2bY%2fsU9pjS7HZ%2bA6Tgrd
- lesson / video: https://www.gracieuniversity.com/Pages/Public/Lesson.aspx?sh=222&se=45

### Provide a description that is worded well enough to be understood

- the website provides instructional courses (basically playlists with additional stuff / resources)
- following URL is course including free lessons (videos): https://www.gracieuniversity.com/Pages/Public/Course?se=52
- following URL is course including free lessons which require registration: https://www.gracieuniversity.com/Pages/Public/Course?se=45
- the URL referencing the page and the URL itself is different e.g.:
this is reference URL to 1st lesson of 1st course i mentioned above: https://www.gracieuniversity.com/Pages/Public/Lesson.aspx?sh=269&se=52
this is URL i actually get in my browser: https://www.gracieuniversity.com/Pages/Public/Lesson?enc=09U99ICUQPooiq3RkHcZhA%3d%3d
after i click on "view lesson" i get: https://www.gracieuniversity.com/Pages/Players/FVLessonPlayerBC?enc=kc1WA%2fRGzNmcB4EPDxYGax0zQvDIrlsTrctcEbiqe1QIO%2bY%2fsU9pjS7HZ%2bA6Tgrd

- [ ] the videos also contain chapters. i d like to be able to embed those

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.gracieuniversity.com/Pages/Players/FVLessonPlayerBC?enc=kc1WA%2fRGzNmcB4EPDxYGax0zQvDIrlsTrctcEbiqe1QIO%2bY%2fsU9pjS7HZ%2bA6Tgrd']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d]
[debug] Python 3.10.10 (CPython x86_64 64bit) - Linux-6.1.25-1-lts-x86_64-with-glibc2.37 (OpenSSL 3.0.8 7 Feb 2023, glibc 2.37)
[debug] exe versions: ffmpeg 6.0 (setts), ffprobe 6.0, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.12.0, brotlicffi-1.0.9.2, certifi-2022.12.07, secretstorage-3.3.3, sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
yt-dlp is up to date (stable@2023.03.04)
[generic] Extracting URL: https://www.gracieuniversity.com/Pages/Players/FVLessonPlayerBC?enc=kc1WA%2fRGzNmcB4EPDxYGax0zQvDIrlsTrctcEbiqe1QIO%2bY%2fsU9pjS7HZ%2bA6Tgrd
[generic] FVLessonPlayerBC?enc=kc1WA/RGzNmcB4EPDxYGax0zQvDIrlsTrctcEbiqe1QIO+Y/sU9pjS7HZ+A6Tgrd: Downloading webpage
ERROR: [generic] None: Unable to download webpage: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)> (caused by URLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)')))
  File "/usr/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 694, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.10/site-packages/yt_dlp/extractor/generic.py", line 2371, in _real_extract
    full_response = self._request_webpage(url, video_id, headers={
  File "/usr/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 839, in _request_webpage
    raise ExtractorError(errmsg, cause=err)

  File "/usr/lib/python3.10/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/lib/python3.10/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1037, in _send_output
    self.send(msg)
  File "/usr/lib/python3.10/http/client.py", line 975, in send
    self.connect()
  File "/usr/lib/python3.10/http/client.py", line 1454, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/usr/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.10/ssl.py", line 1071, in _create
    self.do_handshake()
  File "/usr/lib/python3.10/ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 821, in _request_webpage
    return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query))
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3742, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/usr/lib/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/site-packages/yt_dlp/utils.py", line 1555, in https_open
    return self.do_open(
  File "/usr/lib/python3.10/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)>
```

**Comment by cernekj** [comment]
Hi @m1karii, Is it still a problem? I have tested it now, and it is OK for me.
BTW, did you try `--no-check-certificates` argument? like `yt-dlp --no-check-certificates "https://www.gracieuniversity.com/Pages/Public/Lesson.aspx?sh=269&se=52"`
