### ISSUE TITLE
Error downloading from OpenRec

### ISSUE THREAD

**Issue by marlouz** [yt-dlp/yt-dlp#6946]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

I get an error downloading a video from Openrec (membership video). I am a member to the site, the previous streams (4 so far) I have downloaded without issues. If I retry those now, I get the same error as with this new video. Thanks for your help! 

Kind regards, 
Marloes

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['--cookies-from-browser', 'chrome', '-vU', 'https://www.openrec.tv/live/wez9mp0158l']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 2023-02-16-git-aeceefa622-full_build-www.gyan.dev (setts), ffprobe 2023-02-16-git-aeceefa622-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[Cookies] Extracting cookies from chrome
[debug] Extracting cookies from: "C:\Users\marlo\AppData\Local\Google\Chrome\User Data\Default\Network\Cookies"
[debug] Found local state file at "C:\Users\marlo\AppData\Local\Google\Chrome\User Data\Local State"
[Cookies] Extracted 3212 cookies from chrome
[debug] cookie version breakdown: {'v10': 3221, 'other': 0, 'unencrypted': 0}
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
Current Build Hash: 5590c57bd0433ed239a2deaaf92e2ad6f37fe50f53664c821575cafe106a9421
yt-dlp is up to date (stable@2023.03.04)
[openrec] Extracting URL: https://www.openrec.tv/live/wez9mp0158l
[openrec] wez9mp0158l: Downloading webpage
[openrec] wez9mp0158l: Downloading JSON metadata
[openrec] wez9mp0158l: Downloading m3u8 information
ERROR: [openrec] wez9mp0158l: Failed to download m3u8 information: HTTP Error 401: Unauthorized (caused by <HTTPError 401: 'Unauthorized'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 694, in extract
  File "yt_dlp\extractor\openrec.py", line 81, in _real_extract
  File "yt_dlp\extractor\openrec.py", line 50, in _extract_movie
  File "yt_dlp\extractor\openrec.py", line 23, in _expand_media
  File "yt_dlp\extractor\common.py", line 1919, in _extract_m3u8_formats
  File "yt_dlp\extractor\common.py", line 1941, in _extract_m3u8_formats_and_subtitles
  File "yt_dlp\extractor\common.py", line 882, in _download_webpage_handle
  File "yt_dlp\extractor\common.py", line 839, in _request_webpage

  File "yt_dlp\extractor\common.py", line 821, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 3742, in urlopen
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 401: Unauthorized
```

**Comment by bashonly** [comment]
Have you tried opening the site in your browser to refresh your login session?

**Comment by marlouz** [comment]
Hi,

Yes, I can watch the video just fine in my browser. I even rebooted :)
This channel now has 5 video's (1 per month). Before I knew yt-dlp could
also download from OpenRec, I used another tool on Github, openrec. I don't
think this one is still supported but I tried using that tool just now, and
from them I get a 'no public playlist found' error. Maybe OpenRec has
changed something?
[image: image.png]

**Comment by Lesmiscore** [comment]
Have you tried exporting cookies again after refreshing cookies on browser?

P.S. Please try to use GitHub website for replies. We can't see your attachments

**Comment by marlouz** [comment]
I'm sorry, I will reply using the website! I have tried both the --cookies-from-browser and the --cookies command with a freshly generated cookies file using the get cookies.txt locally extension. 
The screenshot I wanted to attach in the previous reply:
![image](https://user-images.githubusercontent.com/44909805/235306226-0be57484-ddbb-4d1e-ba52-8545c7d41744.png)

**Comment by pukkandan** [comment]
Well, do what it says and change your format selector!

**Comment by marlouz** [comment]
Hi, the command won't work at all, but it's another tool, it was just to inform that other tools than yt-dlp seem to have troubles downloading from OpenRec too. The complete verbose log for the yt-dlp download command is in the first post.
Openrec has 2 'types' of links: 'live' (https://www.openrec.tv/live/wez9mp0158l) and ' movie' (https://www.openrec.tv/movie/n9ze7nqqxr4). Both links from the same channel. I can download the Movie link, just not the Live links. Last month is was the other way around :) The fixed the Movie link, but now the Live link is broken?

**Comment by pukkandan** [comment]
> The complete verbose log for the yt-dlp download command is in the first post.

Pls provide new log after cookies were refreshed. I can see from screenshot that error is now different

**Comment by marlouz** [comment]
Hi,

First I tried the 'live' video, the type that raises the error. After that I tried the 'movie' video, from the same channel. That works just fine:

[debug] Command-line config: ['--cookies-from-browser', 'chrome', '-vU', 'https://www.openrec.tv/live/wez9mp0158l']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 2023-02-16-git-aeceefa622-full_build-www.gyan.dev (setts), ffprobe 2023-02-16-git-aeceefa622-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[Cookies] Extracting cookies from chrome
[debug] Extracting cookies from: "C:\Users\marlo\AppData\Local\Google\Chrome\User Data\Default\Network\Cookies"
[debug] Found local state file at "C:\Users\marlo\AppData\Local\Google\Chrome\User Data\Local State"
[Cookies] Extracted 3270 cookies from chrome
[debug] cookie version breakdown: {'v10': 3280, 'other': 0, 'unencrypted': 0}
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
Current Build Hash: 5590c57bd0433ed239a2deaaf92e2ad6f37fe50f53664c821575cafe106a9421
yt-dlp is up to date (stable@2023.03.04)
[openrec] Extracting URL: https://www.openrec.tv/live/wez9mp0158l
[openrec] wez9mp0158l: Downloading webpage
[openrec] wez9mp0158l: Downloading JSON metadata
[openrec] wez9mp0158l: Downloading m3u8 information
ERROR: [openrec] wez9mp0158l: Failed to download m3u8 information: HTTP Error 401: Unauthorized (caused by <HTTPError 401: 'Unauthorized'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 694, in extract
  File "yt_dlp\extractor\openrec.py", line 81, in _real_extract
  File "yt_dlp\extractor\openrec.py", line 50, in _extract_movie
  File "yt_dlp\extractor\openrec.py", line 23, in _expand_media
  File "yt_dlp\extractor\common.py", line 1919, in _extract_m3u8_formats
  File "yt_dlp\extractor\common.py", line 1941, in _extract_m3u8_formats_and_subtitles
  File "yt_dlp\extractor\common.py", line 882, in _download_webpage_handle
  File "yt_dlp\extractor\common.py", line 839, in _request_webpage

  File "yt_dlp\extractor\common.py", line 821, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 3742, in urlopen
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 401: Unauthorized


C:\Users\marlo>yt-dlp --cookies-from-browser chrome -vU https://www.openrec.tv/movie/n9ze7nqqxr4
[debug] Command-line config: ['--cookies-from-browser', 'chrome', '-vU', 'https://www.openrec.tv/movie/n9ze7nqqxr4']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 2023-02-16-git-aeceefa622-full_build-www.gyan.dev (setts), ffprobe 2023-02-16-git-aeceefa622-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[Cookies] Extracting cookies from chrome
[debug] Extracting cookies from: "C:\Users\marlo\AppData\Local\Google\Chrome\User Data\Default\Network\Cookies"
[debug] Found local state file at "C:\Users\marlo\AppData\Local\Google\Chrome\User Data\Local State"
[Cookies] Extracted 3270 cookies from chrome
[debug] cookie version breakdown: {'v10': 3280, 'other': 0, 'unencrypted': 0}
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
Current Build Hash: 5590c57bd0433ed239a2deaaf92e2ad6f37fe50f53664c821575cafe106a9421
yt-dlp is up to date (stable@2023.03.04)
[openrec:movie] Extracting URL: https://www.openrec.tv/movie/n9ze7nqqxr4
[openrec:movie] n9ze7nqqxr4: Downloading webpage
[openrec:movie] n9ze7nqqxr4: Downloading JSON metadata
[openrec:movie] n9ze7nqqxr4: Downloading m3u8 information
[openrec:movie] n9ze7nqqxr4: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] n9ze7nqqxr4: Downloading 1 format(s): url_audio-1660
[debug] Invoking hlsnative downloader on "https://dco4urblvsasc.cloudfront.net/28682/2868173_vBngtZpZ/game/96kbps.m3u8"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 133
[download] Destination: 廣瀬大介のゲーム部屋#03[未公開特別編] [n9ze7nqqxr4].mp4
[debug] File locking is not supported. Proceeding without locking
[download]   8.3% of ~ 224.21MiB at    3.40MiB/s ETA 00:57 (frag 11/133)

**Comment by marlouz** [comment]
Hello,

I'm sorry but I'm not familiar with the way things work on Github, so if I'm being rude or impatient, I apologize! But how do I proceed from here? After posting an issue, you just wait untill someone picks it up (which is of course fine, I understand all of you are just volunteering!), or do I have to make a request somewhere? I've tried several things and my conclusion is that openrec.tv/MOVIE/xxx now works (which didn't in the past) and openrec.tv/LIVE/xxx does not work anymore (it used to). On this channel I've downloaded the LIVE links in the past, got the new openrec.py file a while ago (when I tried to download a MOVIE link for the first time on this channel) and since then I can download the MOVIE link, but now the LIVE links don't work anymore (not the new LIVE links, nor the older LIVE links I've tried to download again).
Please help? Thanks!

**Comment by bashonly** [comment]
@marlouz Are you willing to share your account details if a dev wants to work on this?

This is not to say that I am able to work on it. But if we can label this issue as "can share account" it would be more likely to get picked up by somebody.

**Comment by marlouz** [comment]
@bashonly Hmm, that is a good question, I hadn't thought about that. I'm going to have to think about that one. Thanks for responding!

**Comment by rivke41levp656** [comment]
Simply adding `--referer 'https://www.openrec.tv'` to the command makes it work for me.
