### ISSUE TITLE
Reddit login support

### ISSUE THREAD

**Issue by denaunistic** [yt-dlp/yt-dlp#6949]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a site-specific feature
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United states

### Example URLs

https://old.reddit.com/r/GenZedong/comments/12fujy3/based_hasan/

### Provide a description that is worded well enough to be understood

Currently the site lacks of login option for downloading private/quarantined videos

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--username', 'PRIVATE', '--password', 'PRIVATE', 'https://old.reddit.com/r/GenZedong/comments/12fujy3/based_hasan/']
[debug] User config "C:\Users\japri\AppData\Roaming\yt-dlp\config.txt": ['--downloader', 'aria2c']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2023.04.28.213731 [17ba4343c] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg n6.0-7-gadb4688bfb-20230316 (setts), ffprobe n6.0-7-gadb4688bfb-20230316
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.2
[debug] Proxy map: {}
[debug] Loaded 1810 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Available version: nightly@2023.04.28.213731, Current version: nightly@2023.04.28.213731
Current Build Hash: c6e73ff15a5c05d8938eb5d9bf1f38089f67b13671be1b4fa637fead35f217cd
yt-dlp is up to date (nightly@2023.04.28.213731)
WARNING: [Reddit] Login with password is not supported for this website. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies
[Reddit] Extracting URL: https://old.reddit.com/r/GenZedong/comments/12fujy3/based_hasan/
[Reddit] 12fujy3: Downloading JSON metadata
ERROR: [Reddit] 12fujy3: Quarantined subreddit; an account that has opted in is required. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies
  File "yt_dlp\extractor\common.py", line 694, in extract
  File "yt_dlp\extractor\reddit.py", line 193, in _real_extract
  File "yt_dlp\extractor\common.py", line 1154, in raise_login_required
```

**Comment by pukkandan** [comment]
> Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies

Or are you specifically asking for username/password support?
