### ISSUE TITLE
Twitter login support

### ISSUE THREAD

**Issue by denaunistic** [yt-dlp/yt-dlp#6951]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

twitter currently does not have specific support for credential authentication.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--username', 'PRIVATE', '--password', 'PRIVATE', 'https://twitter.com/ShitpostGate/status/1651904099749699590']
[debug] User config "C:\Users\japri\AppData\Roaming\yt-dlp\config.txt": ['--downloader', 'aria2c']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2023.04.29.181950 [4d9280c9c] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg n6.0-7-gadb4688bfb-20230316 (setts), ffprobe n6.0-7-gadb4688bfb-20230316
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.2
[debug] Proxy map: {}
[debug] Loaded 1810 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Available version: nightly@2023.04.29.181950, Current version: nightly@2023.04.29.181950
Current Build Hash: 5f6363a11a63e1ed08553785fa7704f5207bfb1be4639a80f05f67cc4f4e4976
yt-dlp is up to date (nightly@2023.04.29.181950)
WARNING: [twitter] Login with password is not supported for this website. Use --cookies-from-browser or --cookies for the authentication. See  https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp  for how to manually pass cookies
[twitter] Extracting URL: https://twitter.com/ShitpostGate/status/1651904099749699590
[twitter] 1651904099749699590: Downloading guest token
[twitter] 1651904099749699590: Downloading JSON metadata
[debug] [twitter] Extracting from video info: 1651747074675703809
[twitter] 1651904099749699590: Downloading m3u8 information
[debug] Sort order given by extractor: res, br, size, proto
[debug] Formats sorted by: hasvid, ie_pref, res, tbr, vbr, abr, filesize, fs_approx, proto, lang, quality, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, asr, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 1651747074675703809: Downloading 1 format(s): http-950
[debug] Invoking aria2c downloader on "https://video.twimg.com/ext_tw_video/1651747074675703809/pu/vid/480x600/-yNzlUc4KXyR40kE.mp4?tag=12"
[download] ShitpostGateway - https：⧸⧸t.co⧸uvHY9r5noW [1651747074675703809].mp4 has already been downloaded
[download] 100% of  226.24KiB
```

**Comment by bashonly** [comment]
This one's a lot harder to implement than Reddit's login. The website uses a multi-step login flow, and the 2nd step requires POST JSON data with multiple parameters (I am assuming are generated by the javascript) looking like this:
```json
"response": {
  "rf": {
    "e5ba13d8c9a2c1de100f11e8dc7b3d08a5a77ac8f485b1a3fdbb9b3e969b2d5e": -62,
    "ca7b4cc404b09126894cd257f10ca0be610a769d23c568a3de19dad7163836c3": -10,
    "a1a33537de11bf80c8e2a77cb08e71de90e694ac9d14e2681182527025d88f56": -11,
    "ad66f8a765857badba52d26ac4f38c637fd170b1e1d29e6af022697ab265790d": 8
  },
  "s": "MlsKpre5bmN65UMb5tB078IAZ6PN8eOp_MgnTy4mnQUOZWwMw-4qQkus0NGgPmLj8PHxasopFX2_2ndeqdPliz3eODvKdZXaqUanwFHOwIdoZKus6WtzoN9fPY5tP7rGkU7M-xuUmc9Wieof0a_b1UyYrvnGkPJbv56PtjZHlV8gtnqonkbw68gvRdH3DkJaMtTo4FZL4ydpVAPk1cSQQC1PoNDrpPJDjGq3JVhfWKZe7yukyGwmXBcFo-XT_WtdfafeRoIdjOH15YOjkp9We9Sq9f0aBQ2Xl0LJepJAvg9lXsjNT7tfEPztwVFnoNXkPJCw3ADCRT6hgfM1ij6fNi9ntQawUt5K"
}
```
Since this would require some experimentation and a lot could go wrong, I don't want to risk my personal acct. If I had a burner/throwaway account to play around with, I might be up for digging deeper into it. But Twitter requires phone # for new accounts now

**Comment by denaunistic** [comment]
I have an old account that i don't longer use, can i pass you the credentials?

**Comment by bashonly** [comment]
Sure, DM on discord: bashonly#4457

**Comment by Deer-Spangle** [comment]
This would be a really handy feature to have!

Not sure whether it helps or not to point out that [gallery-dl](https://github.com/mikf/gallery-dl/) does already implement [twitter auth with username and password](https://github.com/mikf/gallery-dl/blob/master/gallery_dl/extractor/twitter.py#L1831)?
Not sure the licensing situation there though

**Comment by bashonly** [comment]
I wrote a plugin for twitter login before I knew gallery-dl had implemented it
https://github.com/bashonly/yt-dlp-TwitterLogin

I was hesitating to PR it proper because there was some anti-bot junk that made the code really ugly/messy, but my takeaway from gallery-dl's implementation is that a simple `'{}'` can be passed in place of the anti-bot parameters. (I see the new owner is really "taking care of the bot problem"). So I'll see about cleaning up the code some more and opening a PR for this
