### ISSUE TITLE
YouTube extractor: unable to extract uploader id

### ISSUE THREAD

**Issue by thegttreasure** [yt-dlp/yt-dlp#6953]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that a **supported** site is broken
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Provide a description that is worded well enough to be understood

I am not able to download YouTube videos using yt-dlp

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[youtube] qPn9cNFVAc0: Downloading webpage
[youtube] qPn9cNFVAc0: Downloading android player API JSON
ERROR: [youtube] qPn9cNFVAc0: Unable to extract uploader id; please report this issue on https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using yt-dlp -U
```

**Comment by reubznz** [comment]
Without being considered spam - just dropping my "me too" here. 

I've also tested on different variants of yt-dl and they all have the same issue. It appears that there's been a change on the YT end.

**Comment by bashonly** [comment]
read the checklist you are checking off:

> Run your yt-dlp command with`-vU` flag added (`yt-dlp -vU <your command line>`)

read the error message:

> Confirm you are on the latest version using `yt-dlp -U`

update!

see also:

https://github.com/yt-dlp/yt-dlp/wiki/FAQ#the-yt-dlp-in-my-package-manager-is-outdatedbroken

**Comment by Bigpet** [comment]
For the people running ubuntu and landing here the 22.04 official packet sources contain an outdated version. There's a PPA with newer version

```
sudo apt-add-repository -r ppa:tomtomtom/yt-dlp
sudo apt-get update
sudo apt-get install yt-dlp
yt-dlp --version
# should print something new like "2023.03.04", instead of the old 2022.04.08-1

```
