### ISSUE TITLE
HEI Network - 403 Error

### ISSUE THREAD

**Issue by AaronTank** [yt-dlp/yt-dlp#6954]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

USA

### Example URLs

https://www.heinetwork.tv/episode/10th-annual-on-cinema-oscar-special/
"https://92vod-adaptive.akamaized.net/exp=1682858609~acl=%2F92993782-e53f-4199-9851-6cd920ae020b%2F%2A~hmac=1d2cc7d1818977afb681ee8f380bedd3cab2844afbf74714bc9e847172fc9b0b/92993782-e53f-4199-9851-6cd920ae020b/parcel/audio/0fb34748.mp4?r=dXMtZWFzdDE%3D\u0026range=833-20328"

https://www.heinetwork.tv/episode/halloween-kills-the-last-duel/
"https://121vod-adaptive.akamaized.net/exp=1682822634~acl=%2F72d478e3-ec87-4b06-ae99-9f5a062c3330%2F%2A~hmac=7605450bcf6ecb6293ed48e0c6260c6c34ebfd251dfc6a059b9856415f10c9d1/72d478e3-ec87-4b06-ae99-9f5a062c3330/parcel/audio/07b6e82d.mp4?r=dXM%3D\u0026range=833-2208"

### Provide a description that is worded well enough to be understood

Hey guys,

I'm subscribed to the HEI Network (Tim Heidecker's service for the On Cinema series) and want to download the latest seasons to put on my personal Plex server so my chronological playlist can be up to date. The first ~11 seasons are all on YouTube and easy to download, but the latest are only on the HEI website.

I'm pretty new to using this tool, but I've tried just about everything I can to get yt-dlp to work with the site and just keep running into a wall, getting either a 403 or Site Unsupported error no matter what. I've tried [every step in this FAQ for the error](https://www.reddit.com/r/youtubedl/wiki/errors-403forbidden) with no result. The only thing I've been able to have reliable success with is the browser extension Video Download Helper - it will detect the DASH stream and download it just fine, but this isn't optimal because this particular extension watermarks everything with a giant QR code, can't queue files easily, and takes absolutely forever to aggregate the streams after downloading (about 2 hours for a 15-minute episode, probably since it has to add that watermark onto everything).

I've tried using the Firefox addon Stream Detector, but it won't detect anything when videos are playing; I can manually pull the .mp4 files out of the console but these won't work either. I've tried using the URLs and headers that the working Video Download Helper hits point to without success. I've tried exporting my cookies to a text file, importing cookies directly from the browser, and every other tip I've been able to find online. I've looked for a playlist/m3u8 file in the console output with no luck; I've been able to get the URLs I'm using by getting a random mp4 from the console and appending the index segment from the master JSON to the end; this plays in a browser tab but still won't download.

Is anyone able to help me troubleshoot why I am not able to use yt-dlp on this particular site? Thanks in advance!!

The latest yt-dlp commands I have tried:

yt-dlp -vU --user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36" --referer "https://www.heinetwork.tv/episode/mass-no-time-to-die/" --cookies-from-browser Chrome --add-header "Origin: https://player.vimeo.com" "https://129vod-adaptive.akamaized.net/exp=1682821899~acl=%2Fdadd0cce-bbf6-41ff-a344-488ce7ac1ec0%2F%2A~hmac=55513e5ee1ffb112652290d24ffee8c8a80e0080399c3722a3267873a1435548/dadd0cce-bbf6-41ff-a344-488ce7ac1ec0/sep/video/025b702a,5cb29151,87fc5914,c17feed3,c3c7632b/audio/1d0ffb97,f0d0f7cf/dash-video.mp4"

yt-dlp -vU --user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/109.0" --referer "https://www.heinetwork.tv/episode/10th-annual-on-cinema-oscar-special/" --cookies-from-browser firefox --add-header "Origin: https://player.vimeo.com" "https://92vod-adaptive.akamaized.net/exp=1682483913~acl=%2F92993782-e53f-4199-9851-6cd920ae020b%2F%2A~hmac=e02707898b0409f983531cb1057f33b6bf979cb86ed47eda926335a74c92ec0a/92993782-e53f-4199-9851-6cd920ae020b/sep/video/0fb34748,2f36f2aa,48758741,b3c3b90d,bb6d6ac3/audio/606891a8,74701809,9ad97ae6/dash-video.mp4"

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
I:\Download>yt-dlp -vU --user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36" --referer "https://www.heinetwork.tv/episode/halloween-kills-the-last-duel/" --cookies-from-browser Chrome --add-header "Origin: https://player.vimeo.com" "https://121vod-adaptive.akamaized.net/exp=1682822634~acl=F72d478e3-ec87-4b06-ae99-9f5a062c3330FA~hmac=7605450bcf6ecb6293ed48e0c6260c6c34ebfd251dfc6a059b9856415f10c9d1/72d478e3-ec87-4b06-ae99-9f5a062c3330/parcel/audio/07b6e82d.mp4?r=dXMD\u0026range=833-2208"
[debug] Command-line config: ['-vU', '--user-agent', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36', '--referer', 'https://www.heinetwork.tv/episode/halloween-kills-the-last-duel/', '--cookies-from-browser', 'Chrome', '--add-header', 'Origin: https://player.vimeo.com', 'https://121vod-adaptive.akamaized.net/exp=1682822634~acl=F72d478e3-ec87-4b06-ae99-9f5a062c3330FA~hmac=7605450bcf6ecb6293ed48e0c6260c6c34ebfd251dfc6a059b9856415f10c9d1/72d478e3-ec87-4b06-ae99-9f5a062c3330/parcel/audio/07b6e82d.mp4?r=dXMD\\u0026range=833-2208']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-108018-g2ed5925e26-20220905 (setts), ffprobe N-108018-g2ed5925e26-20220905
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[Cookies] Extracting cookies from chrome
[debug] Extracting cookies from: "C:\Users\Aaron\AppData\Local\Google\Chrome\User Data\Default\Network\Cookies"
[debug] Found local state file at "C:\Users\Aaron\AppData\Local\Google\Chrome\User Data\Local State"
[Cookies] Extracted 2031 cookies from chrome
[debug] cookie version breakdown: {'v10': 2031, 'other': 0, 'unencrypted': 0}
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
Current Build Hash: 5590c57bd0433ed239a2deaaf92e2ad6f37fe50f53664c821575cafe106a9421
yt-dlp is up to date (stable@2023.03.04)
[generic] Extracting URL: https://121vod-adaptive.akamaized.net/exp=1682822634~acl=F72d478e3-ec87-4b06-ae99-9f5a062c3330FA~hmac=7605450bcf6ecb6293ed48e0c6260c6c34ebfd251dfc6a059b9856415f10c9d1/72d478e3-ec87-4b06-ae99-9f5a062c3330/parcel/audio/07b6e82d.mp4?r=dXMD\u0026range=833-2208
[generic] 07b6e82d.mp4?r=dXMD\u0026range=833-2208: Downloading webpage
ERROR: [generic] None: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 694, in extract
  File "yt_dlp\extractor\generic.py", line 2371, in _real_extract
  File "yt_dlp\extractor\common.py", line 839, in _request_webpage

  File "yt_dlp\extractor\common.py", line 821, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 3742, in urlopen
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden


I:\Download>yt-dlp -vU --user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/109.0" --referer "https://www.heinetwork.tv/episode/10th-annual-on-cinema-oscar-special/" --cookies-from-browser firefox --add-header "Origin: https://player.vimeo.com" "https://92vod-adaptive.akamaized.net/exp=1682858609~acl=F92993782-e53f-4199-9851-6cd920ae020bFA~hmac=1d2cc7d1818977afb681ee8f380bedd3cab2844afbf74714bc9e847172fc9b0b/92993782-e53f-4199-9851-6cd920ae020b/parcel/audio/0fb34748.mp4?r=dXMtZWFzdDED\u0026range=833-20328"
[debug] Command-line config: ['-vU', '--user-agent', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/109.0', '--referer', 'https://www.heinetwork.tv/episode/10th-annual-on-cinema-oscar-special/', '--cookies-from-browser', 'firefox', '--add-header', 'Origin: https://player.vimeo.com', 'https://92vod-adaptive.akamaized.net/exp=1682858609~acl=F92993782-e53f-4199-9851-6cd920ae020bFA~hmac=1d2cc7d1818977afb681ee8f380bedd3cab2844afbf74714bc9e847172fc9b0b/92993782-e53f-4199-9851-6cd920ae020b/parcel/audio/0fb34748.mp4?r=dXMtZWFzdDED\\u0026range=833-20328']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-108018-g2ed5925e26-20220905 (setts), ffprobe N-108018-g2ed5925e26-20220905
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[Cookies] Extracting cookies from firefox
[debug] Extracting cookies from: "C:\Users\Aaron\AppData\Roaming\Mozilla\Firefox\Profiles\pamjlz7i.default\cookies.sqlite"
[Cookies] Extracted 98 cookies from firefox
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
Current Build Hash: 5590c57bd0433ed239a2deaaf92e2ad6f37fe50f53664c821575cafe106a9421
yt-dlp is up to date (stable@2023.03.04)
[generic] Extracting URL: https://92vod-adaptive.akamaized.net/exp=1682858609~acl=F92993782-e53f-4199-9851-6cd920ae020bFA~hmac=1d2cc7d1818977afb681ee8f380bedd3cab2844afbf74714bc9e847172fc9b0b/92993782-e53f-4199-9851-6cd920ae020b/parcel/audio/0fb34748.mp4?r=dXMtZWFzdDED\u0026range=833-20328
[generic] 0fb34748.mp4?r=dXMtZWFzdDED\u0026range=833-20328: Downloading webpage
ERROR: [generic] None: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 694, in extract
  File "yt_dlp\extractor\generic.py", line 2371, in _real_extract
  File "yt_dlp\extractor\common.py", line 839, in _request_webpage

  File "yt_dlp\extractor\common.py", line 821, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 3742, in urlopen
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

**Comment by bashonly** [comment]
Have you tried
`yt-dlp --cookies-from-browser chrome "https://www.heinetwork.tv/episode/mass-no-time-to-die/"`
?
often times Vimeo embeds can be detected if you have yt-dlp try to extract the actual webpage (and it needs your cookies to do that)

Otherwise, try viewing the page source and finding the full `player.vimeo.com` URL, and passing it like this:
`yt-dlp "VIMEO_PLAYER_URL" --referer "https://www.heinetwork.tv/episode/mass-no-time-to-die/"`
(replace `VIMEO_PLAYER_URL` with the actual URL you found in the page's source)

**Comment by AaronTank** [comment]
Ha! Welp, I feel pretty dumb because I basically tried every possible combination except just cookies and the plain URL. Looks like that is working so far; Classic case of overthinking it I guess. Thank you so much!

Also curiously, I checked the Mass/No Time to Die episode, and it worked for me as well just with the plain URL and no cookies while the rest do seem to be requiring them. I guess Gregg couldn't bear to put Bond behind a paywall.
