### ISSUE TITLE
[Zee5] Login with cookies

### ISSUE THREAD

**Issue by navinas33** [yt-dlp/yt-dlp#6968]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that a **supported** site is broken
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Provide a description that is worded well enough to be understood

list format (-F) and download is not able to do for 1080P format in zee5 site. Same url when i play in browser its able to play in 1080P

<img width="965" alt="image" src="https://user-images.githubusercontent.com/19791213/235650575-3ea3f1ef-3a09-4de4-941a-28cd79d3ee78.png">

is there any way to check whether cookies are used and it's able to login ?

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
(base) ➜  ~ yt-dlp -i "https://www.zee5.com/movies/details/ala-modalaindi/0-0-alamodalaindi" --cookies-from-browser chrome -vU -F
[debug] Command-line config: ['-i', 'https://www.zee5.com/movies/details/ala-modalaindi/0-0-alamodalaindi', '--cookies-from-browser', 'chrome', '-vU', '-F']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (pip)
[debug] Python 3.10.6 (CPython arm64 64bit) - macOS-13.3.1-arm64-arm-64bit (OpenSSL 3.0.7 1 Nov 2022)
[debug] exe versions: ffmpeg 5.1.2 (setts), ffprobe 5.1.2, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.16.0, brotli-None, certifi-2022.09.24, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[Cookies] Extracting cookies from chrome
[debug] Extracting cookies from: "/Users/navin/Library/Application Support/Google/Chrome/Default/Cookies"
[debug] using find-generic-password to obtain password from OSX keychain
[Cookies] Extracted 1277 cookies from chrome
[debug] cookie version breakdown: {'v10': 1270, 'other': 0, 'unencrypted': 7}
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
yt-dlp is up to date (stable@2023.03.04)
[debug] Using fake IP 117.232.165.101 (IN) as X-Forwarded-For
[Zee5] Extracting URL: https://www.zee5.com/movies/details/ala-modalaindi/0-0-alamodalaindi
[Zee5] 0-0-alamodalaindi: Downloading access token
[Zee5] 0-0-alamodalaindi: Downloading JSON metadata
[Zee5] 0-0-alamodalaindi: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[info] Available formats for 0-0-alamodalaindi:
ID   EXT RESOLUTION FPS │   FILESIZE   TBR PROTO │ VCODEC        VBR ACODEC    ABR
──────────────────────────────────────────────────────────────────────────────────
157  mp4 170x96      25 │ ~149.31MiB  157k m3u8  │ avc1.4d401f  157k mp4a.40.2  0k
189  mp4 256x144     25 │ ~180.26MiB  190k m3u8  │ avc1.4d401f  190k mp4a.40.2  0k
320  mp4 428x240     25 │ ~304.33MiB  321k m3u8  │ avc1.4d401f  321k mp4a.40.2  0k
526  mp4 640x360     25 │ ~500.23MiB  527k m3u8  │ avc1.4d401f  527k mp4a.40.2  0k
724  mp4 854x480     25 │ ~687.44MiB  724k m3u8  │ avc1.4d401f  724k mp4a.40.2  0k
882  mp4 1024x576    25 │ ~837.84MiB  883k m3u8  │ avc1.4d401f  883k mp4a.40.2  0k
1458 mp4 1280x720    25 │ ~  1.35GiB 1458k m3u8  │ avc1.4d401f 1458k mp4a.40.2  0k
1536 mp4 1280x720    25 │ ~  1.42GiB 1536k m3u8  │ avc1.4d401f 1536k mp4a.40.2  0k
(base) ➜  ~ 
(base) ➜  ~
```

**Comment by bashonly** [comment]
Does the 1080p stream play in Firefox with DRM disabled? yt-dlp only extracts the non-DRM m3u8, and its resolution tops out at 720p

**Comment by navinas33** [comment]
yes, it's able to play in browser with DRM disabled

<img width="965" alt="image" src="https://user-images.githubusercontent.com/19791213/235675120-2fdf66ed-17a4-4cd3-987b-c7f1c1bd0625.png">

tried with firefox cookie 

(base) ➜  ~ yt-dlp -i "https://www.zee5.com/movies/details/ala-modalaindi/0-0-alamodalaindi" --cookies-from-browser firefox -vU -F
[debug] Command-line config: ['-i', 'https://www.zee5.com/movies/details/ala-modalaindi/0-0-alamodalaindi', '--cookies-from-browser', 'firefox', '-vU', '-F']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (pip)
[debug] Python 3.10.6 (CPython arm64 64bit) - macOS-13.3.1-arm64-arm-64bit (OpenSSL 3.0.7 1 Nov 2022)
[debug] exe versions: ffmpeg 5.1.2 (setts), ffprobe 5.1.2, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.16.0, brotli-None, certifi-2022.09.24, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[Cookies] Extracting cookies from firefox
[debug] Extracting cookies from: "/Users/navin/Library/Application Support/Firefox/Profiles/o14djhyz.default-release/cookies.sqlite"
[Cookies] Extracted 1667 cookies from firefox
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
yt-dlp is up to date (stable@2023.03.04)
[debug] Using fake IP 117.245.170.230 (IN) as X-Forwarded-For
[Zee5] Extracting URL: https://www.zee5.com/movies/details/ala-modalaindi/0-0-alamodalaindi
[Zee5] 0-0-alamodalaindi: Downloading access token
[Zee5] 0-0-alamodalaindi: Downloading JSON metadata
[Zee5] 0-0-alamodalaindi: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[info] Available formats for 0-0-alamodalaindi:
ID   EXT RESOLUTION FPS │   FILESIZE   TBR PROTO │ VCODEC        VBR ACODEC    ABR
──────────────────────────────────────────────────────────────────────────────────
157  mp4 170x96      25 │ ~149.31MiB  157k m3u8  │ avc1.4d401f  157k mp4a.40.2  0k
189  mp4 256x144     25 │ ~180.26MiB  190k m3u8  │ avc1.4d401f  190k mp4a.40.2  0k
320  mp4 428x240     25 │ ~304.33MiB  321k m3u8  │ avc1.4d401f  321k mp4a.40.2  0k
526  mp4 640x360     25 │ ~500.23MiB  527k m3u8  │ avc1.4d401f  527k mp4a.40.2  0k
724  mp4 854x480     25 │ ~687.44MiB  724k m3u8  │ avc1.4d401f  724k mp4a.40.2  0k
882  mp4 1024x576    25 │ ~837.84MiB  883k m3u8  │ avc1.4d401f  883k mp4a.40.2  0k
1458 mp4 1280x720    25 │ ~  1.35GiB 1458k m3u8  │ avc1.4d401f 1458k mp4a.40.2  0k
1536 mp4 1280x720    25 │ ~  1.42GiB 1536k m3u8  │ avc1.4d401f 1536k mp4a.40.2  0k
(base) ➜  ~

**Comment by justarish** [comment]
I'm willing to give my account (only for fixing). I'm having the same issue.

**Comment by bashonly** [comment]
> The login/user token is not stored in cookies, which is why the extractor currently cannot authenticate with them. However, if we want to improve the extractor, there is a "refresh token" cookie, which could potentially be used by the extractor to request a new login token from the API. The problem is that the login tokens only expire every 30 days, so I haven't yet been able to observe how a token is refreshed.

Have had 2 tokens expire now and neither were refreshed using the "refresh token" -- the site required a new login after expiration. I don't think login with cookies will be possible

**Comment by pukkandan** [comment]
@bashonly If you are reasonably sure it's impossible, issue can be closed.

**Comment by bashonly** [comment]
> Does browser also ask for re-login?

Yeah. The site seemingly doesn't do anything with its "refresh token"

> If you are reasonably sure it's impossible, issue can be closed.

:+1:
