### ISSUE TITLE
support for usnewson.com livestreams

### ISSUE THREAD

**Issue by chrizilla** [yt-dlp/yt-dlp#6985]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

no geo-block

### Example URLs

live streams are here: https://usnewson.com/watch/

examples:

* CNN: https://usnewson.com/watch/cnn-live
* MSNBC : https://usnewson.com/watch/msnbc-live
* Fox News: https://usnewson.com/watch/fox-news-live
* OAN: https://usnewson.com/watch/oann-live-stream

### Provide a description that is worded well enough to be understood

https://usnewson.com/watch/ provides high-quality livestreams of major US news networks.

From visual/aural inspection, it's a feed of considerably better quality (both audio and video quality) than https://www.livenewsnow.com/american/cnn-live.html which yt-dlp is able to download live streams from using generic extractor.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp https://usnewson.com/watch/cnn-live --no-config -v
[debug] Command-line config: ['https://usnewson.com/watch/cnn-live', '--no-config', '-v']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2023.05.03.204705 [2f07c4c1d] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.2
[debug] Proxy map: {}
[debug] Loaded 1813 extractors
[generic] Extracting URL: https://usnewson.com/watch/cnn-live
[generic] cnn-live: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] cnn-live: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://usnewson.com/watch/cnn-live
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1532, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1608, in __extract_info
  File "yt_dlp\extractor\common.py", line 694, in extract
  File "yt_dlp\extractor\generic.py", line 2568, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://usnewson.com/watch/cnn-live
```

**Comment by bashonly** [comment]
Despite the "About Us" section of that website claiming that their streams are legit, I'm not so sure :thinking:

The livestreams on the actual websites for CNN, MSNBC and FOX News are provider-locked (AdobePass MSO sign-in required). It seems highly unlikely that there would also be legitimate unlocked streams available elsewhere

> Disclaimer
>
> USNewsON is not in anyway associated with any sites. We do not host any streams & videos on USNewsON itself. USNewsON is absolutely legal and embeds only links from other third party websites like Youtube, Dailymotion,… and many more on the internet which actually host streams & videos.
>
> USNewsON haven’t any responsibility for the compliance, copyright, legality, decency, or any other aspect of the content of other linked sites. If you have any legal issues please contact the appropriate media file owners or linked hosting websites.
>
> USNewsON only provides links to third party video/stream hosting sites which streams & videos are uploaded by third party users. USNewsON in no way affiliated with them nor intend to do that.

if you can find these "third party websites" where this site's streams for CNN, MSNBC and FOX News originate from, then yt-dlp could support those if they are indeed legit

**Comment by gamer191** [comment]
> Despite the "About Us" section of that website claiming that their streams are legit, I'm not so sure 🤔

Me neither. Correct me if I'm wrong, but if they truly "embed only links from other third party websites like Youtube, Dailymotion", wouldn't you be able to find the original source in the network traffic (assuming they don't proxy it)
