### ISSUE TITLE
run a postproccesor plugin in with --skip-download

### ISSUE THREAD

**Issue by bindestriche** [yt-dlp/yt-dlp#6986]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

To address the issue [with odd subtitles](https://github.com/yt-dlp/yt-dlp/issues/1734) when you convert auto generated subtitles from YouTube to SRT , I wrote [srt_fix](https://github.com/bindestriche/srt_fix). A postprocessor plug-in. It works so far, but I am stuck as to how to make the plugin run when the flag `--skip-download` is passed. e.g. when one wants only the SRT files and not the videos.  

@pukkandan suggested this:
```
from yt_dlp.postprocessor import FFmpegSubtitlesConvertorPP
info, files_to_delete = FFmpegSubtitlesConvertorPP(self._downloader, 'srt').run()
# Do your stuff
return info, files_to_delete
```

But I don't understand where to add these lines in my code. Inside the PP class of my plugin or the head of the file did not work.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
`--use-postprocessor srt_fix:when=before_dl` is what you need

The problem is, at least via CLI, this will run before the subtitles converter PP runs. I think this is where pukkandan's suggestion comes in.

This works for me
```
yt-dlp -v --skip-download --use-postprocessor srt_fix:when=before_dl --write-sub test:youtube
```
if I make these changes
```diff
diff --git a/yt_dlp_plugins/postprocessor/srt_fix.py b/yt_dlp_plugins/postprocessor/srt_fix.py
index 3cf7d96..4370ffd 100644
--- a/yt_dlp_plugins/postprocessor/srt_fix.py
+++ b/yt_dlp_plugins/postprocessor/srt_fix.py
@@ -1,4 +1,5 @@
 #  Don't use relative imports
+from yt_dlp.postprocessor import FFmpegSubtitlesConvertorPP
 from yt_dlp.postprocessor.common import PostProcessor
 
 # start
@@ -216,6 +217,7 @@ class srt_fixPP(PostProcessor):
 
     # ℹ️ See docstring of yt_dlp.postprocessor.common.PostProcessor.run
     def run(self, info):
+        files_to_delete, info = FFmpegSubtitlesConvertorPP(self._downloader, 'srt').run(info)
         subtitles = info.get('requested_subtitles')
         if not subtitles:
             self.to_screen('There aren\'t any subtitles to process')
@@ -261,21 +263,6 @@ class srt_fixPP(PostProcessor):
         #files_to_move = info['__files_to_move']
         #self.to_screen(f'Initial files_to_move: {files_to_move}')
 
-        # HACK: The replacement set of subtitles is never written. We proably are called too late. Do it ourselves for now.
-        for lang, sub_info in subtitles.items():
-            new_file_path = sub_info.get('filepath')
-            text = sub_info.get('data')
-
-            with open(new_file_path, "w", encoding="utf8") as new_file:
-                new_file.write(text)
-
-            info['__files_to_move'][new_file.name] = os.path.basename(new_file_path)
-            #self.to_screen(f'Wrote postprocessed {lang}')
-
-        #files_to_move = info['__files_to_move']
-        #self.to_screen(f'Modified files_to_move: {files_to_move}')
-
-        '''
         filepath = info.get('filepath')
 
         if filepath:  # PP was called after download (default)
@@ -286,6 +273,5 @@ class srt_fixPP(PostProcessor):
             filepath = info.get('_filename')
             self.to_screen(f'Pre-processed {filepath!r} with {self._kwargs}')
             self.process_all(filepath)
-        '''
 
-        return [], info  # return list_of_files_to_delete, info_dict
+        return files_to_delete, info
```

**Comment by UlyssesZh** [comment]
> `--use-postprocessor srt_fix:when=before_dl` is what you need

Where is the documentation about how to pass parameters to postprocessors?

**Comment by bashonly** [comment]
https://github.com/yt-dlp/yt-dlp#post-processing-options
```
--use-postprocessor NAME[:ARGS]
                                The (case sensitive) name of plugin
                                postprocessors to be enabled, and
                                (optionally) arguments to be passed to it,
                                separated by a colon ":". ARGS are a
                                semicolon ";" delimited list of NAME=VALUE.
                                The "when" argument determines when the
                                postprocessor is invoked. It can be one of
                                "pre_process" (after video extraction),
                                "after_filter" (after video passes filter),
                                "video" (after --format; before
                                --print/--output), "before_dl" (before each
                                video download), "post_process" (after each
                                video download; default), "after_move"
                                (after moving video file to it's final
                                locations), "after_video" (after downloading
                                and processing all formats of a video), or
                                "playlist" (at end of playlist). This option
                                can be used multiple times to add different
                                postprocessors
```
