### ISSUE TITLE
format selection: `allaudio` selects all audio formats

### ISSUE THREAD

**Issue by chrizilla** [yt-dlp/yt-dlp#6990]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

AFAIK downloading 1 video format and all audio formats currently can only(?) be done via: `bv+all[vcodec=none]`

In addition to the [currently available](https://github.com/yt-dlp/yt-dlp#format-selection) shorthands:

     all:      Select all formats separately
     mergeall: Select and merge all formats

... I'd like to propose the following new shorthands to make life easier:

* `allaudio`
* `allvideo` (just so that the equivalent is not missing, although `allaudio` will probably be used more often)

The idea would be to be able to use `bv+allaudio` (instead of `bv+all[vcodec=none]` ).

<hr>

Considering however how `all` and `mergeall` are defined and if we expect `allaudio` and `allvideo` to behave similarly, consistency may require `allaudio`, `allvideo`, `mergeallaudio`, `mergeallvideo`.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
Example: formats from https://www.arte.tv/de/videos/112352-003-A/tracks-east :

ID                                 EXT RESOLUTION FPS │   FILESIZE   TBR PROTO │ VCODEC        VBR ACODEC     MORE INFO
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
VF-STF-program_audio_0-VF          mp4 audio only     │                  m3u8  │ audio only        unknown    [fr] Französisch [FR]
VE_RUS_-program_audio_0-VE-RUS     mp4 audio only     │                  m3u8  │ audio only        unknown    [ru] Russisch [OmU-RUS]
VOEU-STE_ANG_-program_audio_0-VOEU mp4 audio only     │                  m3u8  │ audio only        unknown    [de] UT Englisch [OmU-ANG]
VOA-program_audio_0-VOA            mp4 audio only     │                  m3u8  │ audio only        unknown    [de] Deutsch [DE]
VOA-433                            mp4 384x216     25 │ ~ 90.03MiB  434k m3u8  │ avc1.42e00d  434k video only Deutsch [DE]
VOA-751                            mp4 640x360     25 │ ~156.05MiB  752k m3u8  │ avc1.4d401e  752k video only Deutsch [DE]
VOA-1170                           mp4 768x432     25 │ ~242.81MiB 1170k m3u8  │ avc1.4d401e 1170k video only Deutsch [DE]
VOA-2069                           mp4 1280x720    25 │ ~429.44MiB 2069k m3u8  │ avc1.4d401f 2069k video only Deutsch [DE]
VOA-2359                           mp4 1920x1080   25 │ ~489.68MiB 2360k m3u8  │ avc1.4d0028 2360k video only Deutsch [DE]
```

**Comment by pukkandan** [comment]
This is already planned. See #4846 and related issues

**Comment by pukkandan** [comment]
Specifically https://github.com/yt-dlp/yt-dlp/pull/3562
