### ISSUE TITLE
modifying `format_id`

### ISSUE THREAD

**Issue by chrizilla** [yt-dlp/yt-dlp#6991]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

The audio streams for the [ArteTV] extractor seem to follow the following ID name patterns:

`language code` + `-program_audio_0-` + `language code abbreviated`

See example in log below.

## questions

* How can I remove the 2nd and 3rd part from `format_id` – i.e. only keep the 1st part (the language code) ?
  So I want to rename `VOEU-STE_ANG_-program_audio_0-VOEU` to `VOEU-STE_ANG`
  (I read [this](https://github.com/yt-dlp/yt-dlp#modifying-metadata) and searched through the issues, but was unsuccessful.)
* And how can I do this only on condition that extractor = ArteTV (since it applies only to this extractor) ?

## use case
This is to avoid the manual cleanup of my filenames after download and also not to exceed the [OS char limit](https://github.com/yt-dlp/yt-dlp/issues/6974) during download since `format_id` is part of my `-o` template (which is fine for most cases like `{249+889}` but becomes unwieldy here: {`VOA-2359+VOA-program_audio_0-VOA+VOEU-STE_ANG_-program_audio_0-VOEU+VE_RUS_-program_audio_0-VE-RUS+VOA-2359+VF-STF-program_audio_0-VF`}.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
ID                                 EXT RESOLUTION FPS │   FILESIZE   TBR PROTO │ VCODEC        VBR ACODEC     MORE INFO
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
VF-STF-program_audio_0-VF          mp4 audio only     │                  m3u8  │ audio only        unknown    [fr] Französisch [FR]
VE_RUS_-program_audio_0-VE-RUS     mp4 audio only     │                  m3u8  │ audio only        unknown    [ru] Russisch [OmU-RUS]
VOEU-STE_ANG_-program_audio_0-VOEU mp4 audio only     │                  m3u8  │ audio only        unknown    [de] UT Englisch [OmU-ANG]
VOA-program_audio_0-VOA            mp4 audio only     │                  m3u8  │ audio only        unknown    [de] Deutsch [DE]
VOA-433                            mp4 384x216     25 │ ~ 90.03MiB  434k m3u8  │ avc1.42e00d  434k video only Deutsch [DE]
VOA-751                            mp4 640x360     25 │ ~156.05MiB  752k m3u8  │ avc1.4d401e  752k video only Deutsch [DE]
VOA-1170                           mp4 768x432     25 │ ~242.81MiB 1170k m3u8  │ avc1.4d401e 1170k video only Deutsch [DE]
VOA-2069                           mp4 1280x720    25 │ ~429.44MiB 2069k m3u8  │ avc1.4d401f 2069k video only Deutsch [DE]
VOA-2359                           mp4 1920x1080   25 │ ~489.68MiB 2360k m3u8  │ avc1.4d0028 2360k video only Deutsch [DE]
```

**Comment by bashonly** [comment]
`--replace-in-metadata "video:format_id" "-program_audio_\d-" "-"`

> And how can I do this only on condition that extractor = ArteTV (since it applies only to this extractor) ?

A "program_audio_x" format_id could occur in other extractors that extract m3u8s with audio-only formats. But is it even really a problem to apply this to all extractors?

**Comment by bashonly** [comment]
you could use a plugin to limit format_id modification to this extractor (and then you don't need to add anything to your config file either)

```py
from yt_dlp.extractor.arte import ArteTV


class ArteTV_Clean(ArteTVIE, plugin_name='ArteClean'):

    def _real_extract(self, url):
        info = super()._real_extract(url)

        for fmt in info['formats']:
            format_id = fmt.get('format_id')
            if format_id and '-program_audio' in format_id:
                fmt['format_id'] = format_id.split('-program_audio')[0]

        return info


__all__ = []
```

just copy/paste/save this as `%APPDATA%\yt-dlp\plugins\arteclean\yt_dlp_plugins\extractor\arteclean.py`

**Comment by bashonly** [comment]
> I thought I recently have read an issue in which someone asked the same or a very similar question, but despite searching all over the place, I couldn't find it anymore.

Maybe it was this:
https://github.com/yt-dlp/yt-dlp/issues/1651#issuecomment-968108645

You could probably use that approach to get your desired result somehow

**Comment by bashonly** [comment]
It's a bit more complicated, I think you would have to do this:
```
--parse-metadata "video:%(format_id)s:%(final_format_id)s"
--parse-metadata "video:%(format_id)s:%(modified_format_id)s"
--replace-in-metadata "video:modified_format_id" "-program_audio_\d-[^+]+" ""
--parse-metadata "before_dl:%(extractor)s-%(modified_format_id)s:ArteTV-%(final_format_id)s"
```
and then use `final_format_id` in your output template(s) instead of `format_id`

**Comment by bashonly** [comment]
> Why is it necessary to transfer the content of `format_id` to `modified_format_id` and modify the latter rather than manipulating the former directly ?

The point of doing this was to only modify the `format_id` for the `ArteTV` extractor, yeah?
Then we need to clone `format_id` as `modified_format_id`, modify it, and then parse it back with the extractor-filter hack from the issue that I linked
