### ISSUE TITLE
Saving to a file a fragment from the previous 2 hours of round-the-clock broadcast on YouTube

### ISSUE THREAD

**Issue by FiLinX** [yt-dlp/yt-dlp#6998]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a site-specific feature
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Russia

### Example URLs

https://www.youtube.com/watch?v=itdpuGHAcpg

### Provide a description that is worded well enough to be understood

Can you tell me if there is at least some way to get a piece of video to your disk as a file - for example, from the previous couple of hours with a round-the-clock YouTube broadcast?? 
Now only a Bandicam has to do everything from the browser player (there you can unscrew up to 12 hours) and write it all for the entire required period of time. 
But I would like to somehow pick it up faster, how is it possible to command it via yt-dlp?

-----------------------------------------------------------------

in Russian
Подскажите, есть ли хоть какой способ получить себе на диск файлом кусок видео  -  из например предыдущих пары часов с круглосуточной ютуб трансляции?? 
Сейчас лишь Бандикамом приходится захват делать из браузерного плеера (там до 12-ти часов можно откручивать) и весь необходимый промежуток по времени писать это всё. 
Но хотелось бы как-то это забирать побыстрее, как-нить через yt-dlp это возможно закоммандить?

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '-o', '-', 'https://www.youtube.com/watch?v=itdpuGHAcpg']
[debug] Encodings: locale cp1251, fs utf-8, pref cp1251, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2023.04.30.175041 [b079c26f0] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.17763-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 2022-02-17-git-2812508086-full_build-www.gyan.dev (setts), ffprobe 2022-02-17-git-2812508086-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.2
[debug] Proxy map: {}
[debug] Loaded 1810 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Available version: nightly@2023.05.05.055923, Current version: nightly@2023.04.30.175041
Current Build Hash: cadb7b2a28baf48d018e06e68c5d78d809ed55a0e87ca4f5e476d8476494f28f
[debug] Downloading _update_spec from https://github.com/yt-dlp/yt-dlp-nightly-builds/releases/latest/download/_update_spec
Updating to nightly@2023.05.05.055923 ...
[debug] Downloading yt-dlp.exe from https://github.com/yt-dlp/yt-dlp-nightly-builds/releases/latest/download/yt-dlp.exe
[debug] Downloading SHA2-256SUMS from https://github.com/yt-dlp/yt-dlp-nightly-builds/releases/latest/download/SHA2-256SUMS
Updated yt-dlp to nightly@2023.05.05.055923
[debug] Restarting: yt-dlp.exe -vU -o - "https://www.youtube.com/watch?v=itdpuGHAcpg"
[debug] Command-line config: ['-vU', '-o', '-', 'https://www.youtube.com/watch?v=itdpuGHAcpg']
[debug] Encodings: locale cp1251, fs utf-8, pref cp1251, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2023.05.05.055923 [ddae33754] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.17763-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 2022-02-17-git-2812508086-full_build-www.gyan.dev (setts), ffprobe 2022-02-17-git-2812508086-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.2
[debug] Proxy map: {}
[debug] Loaded 1813 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Available version: nightly@2023.05.05.055923, Current version: nightly@2023.05.05.055923
Current Build Hash: 2cab78434aaa749ed9a8a2bb87585fd233a33a8940f521efcc26a4b2c5e55d0f
yt-dlp is up to date (nightly@2023.05.05.055923)
```

**Comment by sheerluck** [comment]
Попробуй вот так: `yt-dlp --external-downloader 'ffmpeg' 'https://www.youtube.com/watch?v=itdpuGHAcpg'`
Пару часов попишешь и нажмёшь `Ctrl-C`

**Comment by sheerluck** [comment]
Оказалось, решение существует! В https://github.com/yt-dlp/yt-dlp/issues/3451 есть ссылка на https://github.com/yt-dlp/yt-dlp/pull/6498/files и когда я применил эти измения (поправив файлы `YoutubeDL.py` `__init__.py` `downloader/dash.py` `extractor/common.py` `extractor/youtube.py` `options.py` `utils.py`)  я смог скачать из **URL** https://www.youtube.com/watch?v=itdpuGHAcpg:

- 5 последних минут: `you --live-from-start --download-sections "*-5mins - 0"` **URL**
- 10 минут с -15 до -5:  `you --live-from-start --download-sections "*-15mins - -5mins"` **URL**
- Последние два часа: `you --live-from-start --download-sections "*-2hours - 0"` **URL**
- Два часа с -6 до -4: `you --live-from-start --download-sections "*-6hours - -4hours"` **URL**

Для того, чтобы качалось быстрее, я использовал `-N8`

**Comment by bashonly** [comment]
Closing as duplicate of #3451

**Comment by sheerluck** [comment]
Разработчик `yt-dlp` @gamer191 обратил внимание, что @FiLinX использует Windows и подготовил для него специальную сборку https://github.com/gamer191/yt-dlp/suites/12718991935/artifacts/683049369 в которой, как я понимаю, поддержка `you --live-from-start --download-sections "*-2hours - 0"` уже включена. @FiLinX попробуй эту сборку и отпишись, помогла ли она тебе

**Comment by FiLinX** [comment]
[sheerluck](https://github.com/sheerluck) - [bashonly](https://github.com/bashonly) - [gamer191](https://github.com/gamer191)
Благодарю!  В предложенной спец-сборке всё отрабатывает идеально!
Но остаётся непонимание  -  а почему данный функционал так и не включён в стабильные и ночные сборки?
На них увы у меня не вышло применить это..
Сам я совсем не продвинутый в этих делах, и подобное  "(поправив файлы YoutubeDL.py __init__.py downloader/dash.py extractor/common.py extractor/youtube.py options.py utils.py)"  увы даже не представляю как исполнять для патчевания свежих версий((
То есть - какие есть варианты, чтобы мне неучу как-то можно стало это исполнять самому, без постоянного обращения сюда с данной просьбой ? )

**Comment by sheerluck** [comment]
1) https://github.com/yt-dlp/yt-dlp/pull/6498/files не включён в стабильные и ночные сборки, потому что над ним всё ещё идёт работа, надо ждать
2) никаких вариантов кроме как дождаться завершения работ нет
3) я пробовал плеер `mpv`, но как только я добавлял `--live-from-start --download-sections "*-6hours - 0"` в `~/.config/yt-dlp/config`, `mpv` мне начинал говорить `EDL: Could not open source file 'https://manifest.googlevideo.com/api/manifest/dash/` так что это от плеера зависит, а не от `yt-dlp`
