### ISSUE TITLE
Different default configurations for different extractors

### ISSUE THREAD

**Issue by tkzv** [yt-dlp/yt-dlp#7000]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Is there a simple way to use different defaults for different extractors? What do I need to write in yt-dlp.conf?
For example, I want to add `--write-info-json -o '%(channel)s[%(id)s].%(ext)s'` if the extractor is telegram:embed and use default settings for all other extractors. Does yt-dlp allow that?

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by gamer191** [comment]
unfortunately, that's not currently possible, see https://github.com/yt-dlp/yt-dlp/issues/4680
It may be possible to do that for the specific options you mentioned though, so I'm leaving this question open for now

On a side note, congratulations on opening the 7000th issue! [Click here to win a free iPad Pro mini 7](https://youtube.com/watch?v=dQw4w9WgXcQ)
![It's a scam!](https://user-images.githubusercontent.com/83270075/236589412-5b97088f-10bc-4a8c-aba2-a4a3268989d6.jpeg)

**Comment by bashonly** [comment]
one workaround for time being would be to set an alias in your config file
```
--alias tele '--write-info-json -o "%(channel)s[%(id)s].%(ext)s"'
```
then you could just add `--tele` to your command when downloading from telegram
