### ISSUE TITLE
[Dropbox] Unable to extract mountComponent

### ISSUE THREAD

**Issue by ghost** [yt-dlp/yt-dlp#7005]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that a **supported** site is broken
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Provide a description that is worded well enough to be understood

hello,
cannot extract from dropbox.com. demo link [NSFW]: REDACTED

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
C:\Users\MASTERX>youtube-dl "REDACTED" -FUv
[debug] Command-line config: ['REDACTED', '-FUv']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-110072-g073ec3b9da-20230325 (setts), ffprobe N-110072-g073ec3b9da-20230325
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
Current Build Hash: 5590c57bd0433ed239a2deaaf92e2ad6f37fe50f53664c821575cafe106a9421
yt-dlp is up to date (stable@2023.03.04)
[Dropbox] Extracting URL: REDACTED
[Dropbox] q9n7yl55jdub33o: Downloading webpage
ERROR: [Dropbox] q9n7yl55jdub33o: Unable to extract mountComponent; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 694, in extract
  File "yt_dlp\extractor\dropbox.py", line 56, in _real_extract
  File "yt_dlp\extractor\common.py", line 1256, in _search_json
  File "yt_dlp\extractor\common.py", line 1242, in _search_regex
```

**Comment by pukkandan** [comment]
Provide non-pirated example URL

**Comment by dirkf** [comment]
The target items are in the browser page but yt-dl (and _wget_, probably yt-dlp too) is served a CloudFlare interstitial bouncer page (as in "your name's not on the door - you're not getting in").

The existing yt-dl extractor just toggles the `dl` URL query parameter without looking at the page, which happens to work for the problem page (anonymous sharing enabled), perhaps not for the REDACTED URL. The yt-dlp extractor can do this too, but the bad webpage wouldn't pass its test even if the crash hadn't already occurred.

**Comment by skittlesv1** [comment]
Just wanted to say my version is up to date and I also have this same issue with dropbox on a password protected video. When I try with no arguments I get the message use --video-password, when I use --video-password the download starts to progress and then I get the "Unable to extract mountComponent" error.

**Comment by denhotte** [comment]
I have the same problem and couldn't find a single dropbox-link where the download works with the current `DropboxIE`. I took a deeper look into it and figured out that the json-information (or at least parts of it) is not provided in raw text but in base64-encoded strings.

I also came up with a quick-fix for the problem, which works for me (with the current version `2023.06.22`):

I only changed the [`dropbox.py`](https://github.com/yt-dlp/yt-dlp/blob/master/yt_dlp/extractor/dropbox.py) file:

```python
# Additional import
import base64


class DropboxIE(InfoExtractor):
    # Defining constants...

    def _real_extract(self, url):
        # Extracting webpage...

        # method call to get m3u8-urls ---------------------
        links = self._extract_m3u8_url(webpage)
        # --------------------------------------------------

        #info_json = self._search_json(r'InitReact\.mountComponent\(.*?,', webpage, 'mountComponent', video_id,
        #                              contains_pattern=r'{.+?"preview".+?}', end_pattern=r'\)')['props']
        #transcode_url = traverse_obj(info_json, ((None, 'preview'), 'file', 'preview', 'content', 'transcode_url'), get_all=False)
        formats, subtitles = self._extract_m3u8_formats_and_subtitles(links['1080p'], video_id, ext='mp4')

        # downloads enabled we can get the original file
        #if 'anonymous' in (try_get(info_json, lambda x: x['sharePermission']['canDownloadRoles']) or []):
        #    video_url = re.sub(r'[?&]dl=0', '', url)
        #    video_url += ('?' if '?' not in video_url else '&') + 'dl=1'
        #    formats.append({'url': video_url, 'format_id': 'original', 'format_note': 'Original', 'quality': 1})

        return {
            'id': video_id,
            'title': title,
            'formats': formats,
            'subtitles': subtitles
        }
    
    # new extraction of m3u8-url
    def _extract_m3u8_url(self, webpage):
        regexFound = re.findall(r'registerStreamedPrefetch\(\"[^()]*\)', webpage)
        possibleStrings = []
        for method in regexFound:
            possibleStrings.append(re.findall(r',.*".*",', method)[0].split('"')[1])
        possibleStrings = [s for s in possibleStrings if s.strip(' ') != '']
        links = {}
        for s in possibleStrings:
            decoded = base64.b64decode(s).decode('utf-8', 'ignore')
            if 'm3u8' in decoded:
                slist = decoded.split('\n')
                for s in slist:
                    link = re.findall(r'[0-9]*p.*http.*/p\.m3u8', s)
                    for l in link:
                        resolution = re.findall('[0-9]*p', l)[0]
                        links[resolution] = l[l.index('http'):]
        return links # format: {'720p': 'https://<...>.m3u8', '1080p': 'https://<...>.m3u8', ...} for different resolutions
```

In my tested videos, m3u8-urls for specific resolutions are also provided in the webpage (base64-encoded) even when the resolution for the video doesn't exist. The http-request on those urls only returns a `Bad Request` (400). Therefore the `'1080p'` inside
```python
formats, subtitles = self._extract_m3u8_formats_and_subtitles(links['1080p'], video_id, ext='mp4')
```
has to be changed if the video is not available in 1080p.


Most likely there is a better way to implement this, but I hope it helps to understand the problem and gives some ideas for the solution.

**Comment by JimmyCushnie** [comment]
Thanks for sharing your patch @denhotte , it worked for me :)
