### ISSUE TITLE
Merge/combine/download multiple audios and one video from multiple m3u8 URLs

### ISSUE THREAD

**Issue by LarLei** [yt-dlp/yt-dlp#7010]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Hello,

I'm trying to download a streaming video and multiple audios from a site (prefer not to say) with the following streaming characteristics:
1. Video.m3u8 (*.ts fragments; mp2t)
2. Audio1.m3u8, Audio2.m3u8, Audio3,m3u8, etc (*.aac fragments; x-aac).  The different audios are of different languages and user select-able from the playback interface.

This is what shown when using `yt-dlp.exe -F` for either Video.m3u8 or any of the Audio.m3u8:

ID EXT RESOLUTION │ PROTO │ VCODEC  ACODEC
────────────────────────────────
0  mp4 unknown    │ m3u8  │ unknown unknown

With yt-dlp.exe I can download the video and all of its respective audios, then merge/combine them with ffmpeg.exe.

However, I'm looking for a way to simplify/automate this download of a video and multiple/all audios (prefer not to get into scripting for now), and would like to verify if yt-dlp.exe can help with this goal.

Thanks,

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by october262** [comment]
try with --audio-multistreams -f bestvideo+audio_id1+audio_id2+etc

**Comment by pukkandan** [comment]
That works if you have a master URL. yt-dlp cannot merge from two separate URLs

**Comment by LarLei** [comment]
> try with --audio-multistreams -f bestvideo+audio_id1+audio_id2+etc

Every m3u8 URL doesn't seem to have any usable format as shown with the -F and there is only one ID, which is 0.

> That works if you have a master URL. yt-dlp cannot merge from two separate URLs

Unfortunately, there is no master URL that I could tell from the site.  There are just separate m3u8 URL for video and separate m3u8 URLs for audios for each language.

Thanks for the responses!

**Comment by gamer191** [comment]
@LarLei feel free to request a site-specific extractor, if you want
