### ISSUE TITLE
Is there a hls overhead ?

### ISSUE THREAD

**Issue by chrizilla** [yt-dlp/yt-dlp#7011]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I noticed that there are differences in file size for different formats of the same video content.

# example 1

Formats from this [URL](https://github.com/yt-dlp/yt-dlp/issues/6977):

```
ID         EXT RESOLUTION FPS │  FILESIZE   TBR PROTO │ VCODEC        VBR ACODEC    ABR
───────────────────────────────────────────────────────────────────────────────────────
hls-162    mp4 136x240     30 │ ~ 7.97MiB  162k m3u8  │ avc1.64000c  162k mp4a.40.2  0k
240p-400k  mp4 240p           │   8.20MiB  400k https │ unknown      400k unknown    0k
hls-340    mp4 270x480     30 │ ~16.73MiB  340k m3u8  │ avc1.640015  340k mp4a.40.2  0k
hls-726    mp4 406x720     30 │ ~35.76MiB  727k m3u8  │ avc1.64001e  727k mp4a.40.2  0k
480p-2000k mp4 480p           │  16.77MiB 2000k https │ unknown     2000k unknown    0k
720p-4000k mp4 720p           │  35.36MiB 4000k https │ unknown     4000k unknown    0k
``` 

* `720p-4000k` results in a **36.855.714** byte mkv* file, from which mkvextract extracts a raw video track of **33.415.893** bytes
* `   hls-726` results in a **36.934.094** byte mkv* file, from which mkvextract extracts a raw video track of **33.494.484** bytes

\* _(because I use --remux-video mkv)_

The difference between the mkv files is **78.380** bytes.
The difference between the raw video tracks is **78.591** bytes.

Although it's not a huge difference, if it's just useless overhead for the hls format, we probably rather want to avoid it.

To make sure, we are not talking about 2 different videos here: I compared the videos, they are identical on a pixel-level. In addition, here are binary diff screenshots to show that the video stream is the same (with just different container overhead):

![Clipboard01+](https://user-images.githubusercontent.com/43895159/236707836-98e35014-d5ef-4d2b-a2e6-920412a932e0.png)

![Clipboard02](https://user-images.githubusercontent.com/43895159/236707845-d03b840c-e42b-450e-9498-b69c546b2ed4.png)

# example 2

Formats from this [URL](https://www.ardmediathek.de/video/Y3JpZDovL3JhZGlvYnJlbWVuLmRlL3JhZGlvYnJlbWVuLmRlL29wZW5tZWRpYS8zXzI0NTE4Mi9zZWN0aW9uL3VybjphcmQ6ZXBpc29kZTozMTIzN2NmN2ZlYTQwYzVk):

```
[info] Available formats for 12654831:
ID       EXT RESOLUTION FPS │  FILESIZE   TBR PROTO │ VCODEC        VBR ACODEC    ABR
─────────────────────────────────────────────────────────────────────────────────────
a0-mp4-0 mp4 unknown        │                 https │ unknown           unknown
a0-mp4-1 mp4 unknown        │                 https │ unknown           unknown
a0-mp4-2 mp4 unknown        │                 https │ unknown           unknown
a0-mp4-3 mp4 unknown        │                 https │ unknown           unknown
hls-290  mp4 480x272     25 │ ~ 2.17MiB  291k m3u8  │ avc1.42c01e  291k mp4a.40.2  0k
hls-1057 mp4 640x360     25 │ ~ 7.87MiB 1057k m3u8  │ avc1.4d401e 1057k mp4a.40.2  0k
hls-1558 mp4 960x540     25 │ ~11.60MiB 1558k m3u8  │ avc1.4d401f 1558k mp4a.40.2  0k
hls-4383 mp4 1280x720    25 │ ~32.64MiB 4383k m3u8  │ avc1.640020 4383k mp4a.40.2  0k
``` 

* `a0-mp4-3` results in a **34.240.626** byte mkv file, from which mkvextract extracts a raw video track of **32.250.769** bytes
* `hls-4383` results in a **34.252.389** byte mkv file, from which mkvextract extracts a raw video track of **32.262.768** bytes

The difference between the mkv files is **11.763** bytes.
The difference between the raw video tracks is **11.999** bytes.

So this time, the difference is much smaller. But still hls seems to have a small overhead.

# question

Does hls always come with an overhead and therefore should be avoided if another format for the same raw video content is available ?

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
The question does not seem to be about yt-dlp but about how the site stores formats.

**Comment by bashonly** [comment]
> Rather this question is about yt-dlp's download mechanism and/or about the hls protocol generally (I don't know if the former or the latter is responsible for the overhead).

It's the latter. More specifically, it's most likely due to the very high container overhead of MPEG-Transport Streams (`.ts` fragments). ffmpeg does the remuxing from MPEG-TS to MP4, not yt-dlp, so I think this question is a bit out of scope for a yt-dlp issue tracker.

**Comment by gamer191** [comment]
> considerable file size difference of 78.380 bytes

On an off-topic note, given you care so much about storage, I'd suggest clearing your browser's cache of https://github.com, given how active you are on that site :trollface:
