### ISSUE TITLE
Metadata fields changed on Spankbang like, [uploader] => Name Changes

### ISSUE THREAD

**Issue by kvs674** [yt-dlp/yt-dlp#7016]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that a **supported** site is broken
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Provide a description that is worded well enough to be understood

the following metadata has changed on site [extractor] => SpankBang

[uploader] =>
[view_count] =>

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'spankbang\\.com/\828n7/video/\anna+belle+fucking+sweet+teen+stepson#']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (zip)
[debug] Python 3.10.6 (CPython x86_64 64bit) - Linux-5.15.85-1-pve-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2
[debug] Optional libraries: no_Cryptodome-None, secretstorage-3.3.1, sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
Current Build Hash: 91cad9f121c1f6f0a81b747415c46ecba0ff331ed38cc6433040b4ac7b6e15ca
yt-dlp is up to date (stable@2023.03.04)
[SpankBang] Extracting URL: spankbang\\.com/\828n7/video/anna+belle+fucking+sweet+teen+stepson#
[SpankBang] 828n7: Downloading webpage
[SpankBang] 828n7: Downloading stream JSON
[SpankBang] 828n7: Downloading m3u8 information
[SpankBang] 828n7: Downloading m3u8 information
[SpankBang] 828n7: Downloading m3u8 information
[SpankBang] 828n7: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 828n7: Downloading 1 format(s): hls-1733-1
[debug] Invoking hlsnative downloader on "hls-uranus.sb-cd.com/hls/1/3/13541443-720p.mp4/index-v1-a1.m3u8?_tid=13541443&d=1&m=44&secure=A2g0eo4lf0L0F1DzqmuVoQ,1683658042"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 184
[download] Destination: Anna Belle Fucking Sweet Teen Stepson [828n7].mp4
[download] 100% of  231.85MiB in 00:01:19 at 2.92MiB/s
[debug] ffprobe command line: ffprobe -hide_banner -show_format -show_streams -print_format json 'file:Anna Belle Fucking Sweet Teen Stepson [828n7].mp4'
[FixupM3u8] Fixing MPEG-TS in MP4 container of "Anna Belle Fucking Sweet Teen Stepson [828n7].mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:Anna Belle Fucking Sweet Teen Stepson [828n7].mp4' -map 0 -dn -ignore_unknown -c copy -f mp4 -bsf:a aac_adtstoasc -movflags +faststart 'file:Anna Belle Fucking Sweet Teen Stepson [828n7].temp.mp4'
```

**Comment by dirkf** [comment]
The target items are in the browser page and the extraction looks right. However I get this 403 (not repeatable with yt-dl, where the same code is used up to the error):
```console
$ python3.9 -m yt_dlp -v -F 'https://spankbang.com/828n7/video/anna+belle+fucking+sweet+teen+stepson#'
[debug] Command-line config: ['-v', '-F', 'https://spankbang.com/828n7/video/anna+belle+fucking+sweet+teen+stepson#']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (source)
[debug] Lazy loading extractors is disabled
[debug] Git HEAD: d4e6ef407
[debug] Python 3.9.16 (CPython i686 32bit) - Linux-4.4.0-210-generic-i686-with-glibc2.23 (OpenSSL 1.1.1t  7 Feb 2023, glibc 2.23)
[debug] exe versions: ffmpeg 4.3, ffprobe 4.3
[debug] Optional libraries: Cryptodome-3.11.0, certifi-2019.11.28, secretstorage-3.2.0, sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Loaded 1788 extractors
[SpankBang] Extracting URL: https://spankbang.com/828n7/video/anna+belle+fucking+sweet+teen+stepson#
[SpankBang] 828n7: Downloading webpage
ERROR: [SpankBang] 828n7: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/home/df/Documents/src/yt-dlp/yt_dlp/extractor/common.py", line 694, in extract
    ie_result = self._real_extract(url)
  File "/home/df/Documents/src/yt-dlp/yt_dlp/extractor/spankbang.py", line 74, in _real_extract
    webpage = self._download_webpage(
  File "/home/df/Documents/src/yt-dlp/yt_dlp/extractor/common.py", line 1097, in _download_webpage
    return self.__download_webpage(url_or_request, video_id, note, errnote, None, fatal, *args, **kwargs)
  File "/home/df/Documents/src/yt-dlp/yt_dlp/extractor/common.py", line 1048, in download_content
    res = getattr(self, download_handle.__name__)(url_or_request, video_id, **kwargs)
  File "/home/df/Documents/src/yt-dlp/yt_dlp/extractor/common.py", line 882, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query, expected_status=expected_status)
  File "/home/df/Documents/src/yt-dlp/yt_dlp/extractor/common.py", line 839, in _request_webpage
    raise ExtractorError(errmsg, cause=err)

  File "/home/df/Documents/src/yt-dlp/yt_dlp/extractor/common.py", line 821, in _request_webpage
    return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query))
  File "/home/df/Documents/src/yt-dlp/yt_dlp/YoutubeDL.py", line 3742, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/usr/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

$
```
OP's log doesn't explicitly show the problem. If it occurs when running with (eg) `-O "view_count="`, that would be consistent with a lesser CDN block that redirects to an interstitial page instead of 403.

Using the same code in yt-dl with Py3.9:
```console
$ python3.9 -m youtube_dl -o '%(uploader)s-%(uploader_id)s-%(view_count)d' --get-filename 'https://spankbang.com/828n7/video/anna+belle+fucking+sweet+teen+stepson'
gegekajerasa-gegekajerasa-62
$
```
But with Py2.7 (Py3.5, too) it's the same as yt-dlp:
```console
$ python -m youtube_dl -o '%(uploader)s-%(uploader_id)s-%(view_count)d' --get-filename 'https://spankbang.com/828n7/video/anna+belle+fucking+sweet+teen+stepson'
ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
$
```
Probably the idiots are looking at some TLS traits or order of headers, etc.

**Comment by bashonly** [comment]
> OP's log doesn't explicitly show the problem.

@kvs674 can you show the output of `yt-dlp -v -O uploader,view_count= "URL"` ?

**Comment by dirkf** [comment]
403s that I reported are the same issue and solution as #7025, which OP may need to check if the above test starts misbehaving:
```console
$ python3.9 -m yt_dlp -O 'uploader,uploader_id,view_count=' 'https://spankbang.com/828n7/video/anna+belle+fucking+sweet+teen+stepson' --legacy-server-connect
uploader = "gegekajerasa"
uploader_id = "gegekajerasa"
view_count = 62
$ 
```

**Comment by ArecoJoselie458** [comment]
" Success! Your content has been successfully fixed! 🛠️ https://fixerrorsuccessful.netlify.app/

▇▇ ➤►✅✅🔵🔴👉👉 https://fixerrorsuccessful.netlify.app/  ==> ஜ۩۞۩ஜ  ➤► ✅✅🔵🔴👉👉 https://fixerrorsuccessful.netlify.app/ -
We're thrilled to announce that the issues have been addressed, and your content is now error-free. Thank you for your patience and cooperation throughout this process. https://fixerrorsuccessful.netlify.app/

To ensure you're fully informed about the changes and how to maintain this standard moving forward, we encourage you to check out our detailed guide on the fixes made. This guide provides step-by-step instructions and helpful tips to help you understand the adjustments and implement them effectively.

📖 Click here https://fixerrorsuccessful.netlify.app/  to access the comprehensive guide and learn more about the improvements made.

Your commitment to quality and attention to detail are greatly appreciated. By following the guidelines outlined in the guide, you'll continue to produce content of the highest caliber.

If you have any questions or need further assistance, don't hesitate to reach out. We're here to support you every step of the way.

Thank you for your dedication to excellence!┣▇▇ ➤►✅✅🔵🔴👉👉 https://fixerrorsuccessful.netlify.app/  ==> ஜ۩۞۩ஜ  ➤► ✅✅🔵🔴👉👉 https://fixerrorsuccessful.netlify.app/ -"
