### ISSUE TITLE
a way to embed metadata in an existing download when the video is no longer available

### ISSUE THREAD

**Issue by garret1317** [yt-dlp/yt-dlp#7018]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Alternative title: `--ignore-no-formats-error` doesn't
re: checklist: I'm on yt-dlp nightly@2023.05.08.234549

not sure whether this should be a bug or a feature request, so I'll stay on the safe side and go for feature

I've got a few years' worth of japanese radio programmes that I downloaded with another tool. That tool doesn't download any metadata, just the audio.
I've recently written [an extractor that extracts metadata as well](https://github.com/garret1317/yt-dlp-rajiko), and I'd like to use it to add metadata to my old downloads. 
The service only keeps episodes up for a week after they've aired, so I can't go back and download them all again. The metadata API keeps working, though.

In light of this, I'd like a way to add metadata to an existing file when the video is not available, but metadata is.

My first instinct was just to do nothing - my filenames follow the format I've specified, so it'll see that the file's already there and, in theory, not bother downloading - it'll just write the metadata to the existing file, like it does if formats are still available.
That didn't work - it threw a no formats error - fair enough.

I looked for something relevant in the `--help`, and found:
> **--ignore-no-formats-error**
> Ignore "No video formats" error. Useful for extracting metadata even if the videos are not actually available for download (experimental)

Perfect, that's exactly what I want!
I added it to my command, but it still throws the format error.
Tried `--skip-download`, but it didn't write the metadata. Same with `--simulate`, though I guess that was to be expected.
`--dump-json` gives me the metadata just fine, so I suppose I could write a script that uses that, but I'd much rather not reinvent the wheel and just have yt-dlp add it for me.

Possible solutions could be:

- Check if the file already exists _before_ selecting a format
- Make sure `--ignore-no-formats-error` applies to every error

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['https://radiko.jp/#!/ts/NORTHWAVE/20221120173000', '-o', '角松敏生 My BLUES LIFE 2022-11-20_1730 NORTHWAVE.aac', '--ignore-no-formats-error', '-vU']
[debug] User config "/home/g/.config/yt-dlp/config": ['--no-colors', '--alias', 'nhk', '--config-location "/home/g/.config/yt-dlp/nhkradio"', '--alias', 'radiko', '--config-location "/home/g/.config/yt-dlp/radiko"', '--embed-thumbnail', '--embed-metadata']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2023.05.08.234549 [ef8fb7f02] (zip)
[debug] Python 3.10.6 (CPython x86_64 64bit) - Linux-5.15.0-69-generic-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, secretstorage-3.3.1, sqlite3-2.6.0, websockets-11.0.2
[debug] Proxy map: {'no': 'localhost,127.0.0.0/8,::1'}
[debug] Extractor Plugins: RadikoLiveIE, RadikoTimeFreeIE
[debug] Plugin directories: ['/home/g/.config/yt-dlp/plugins/yt-dlp-rajiko/yt_dlp_plugins', '/home/g/.local/lib/python3.10/site-packages/yt_dlp_plugins']
[debug] Loaded 1815 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Available version: nightly@2023.05.08.234549, Current version: nightly@2023.05.08.234549
Current Build Hash: 3cfd5e8c501b5098b4d8bc166c6392417a3e80a8469824791d33a230e77a7013
yt-dlp is up to date (nightly@2023.05.08.234549)
[RadikoTimeFree] Extracting URL: https://radiko.jp/#!/ts/NORTHWAVE/20221120173000
[RadikoTimeFree] NORTHWAVE: Downloading programme data
[debug] Loading rajiko.region_index from cache
[RadikoTimeFree] JP1: Downloading station listings
[debug] Loading rajiko-tokens.JP1 from cache
[debug] [RadikoTimeFree] {'token': {'X-Radiko-AreaId': 'JP1', 'X-Radiko-AuthToken': 'redacted'}, 'user': 'redacted'}
[RadikoTimeFree] JP1: Checking cached token
[debug] [RadikoTimeFree] OK
[RadikoTimeFree] NORTHWAVE: Downloading stream information
[RadikoTimeFree] NORTHWAVE: Downloading m3u8 information from radiko.jp
WARNING: [RadikoTimeFree] Failed to download m3u8 information: HTTP Error 403: Forbidden
WARNING: [RadikoTimeFree] NORTHWAVE-20221120173000: Programme is no longer available.
WARNING: No video formats found!
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
WARNING: Requested format is not available
[info] Downloading video thumbnail 0 ...
[info] Writing video thumbnail 0 to: 角松敏生 My BLUES LIFE 2022-11-20_1730 NORTHWAVE.jpg
ERROR: [RadikoTimeFree] NORTHWAVE-20221120173000: No video formats found!
Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1532, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1629, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1688, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 2793, in process_video_result
    self.process_info(new_info)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3257, in process_info
    success, real_download = self.dl(temp_filename, info_dict)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 2949, in dl
    self.raise_no_formats(info, True)
  File "/usr/local/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1046, in raise_no_formats
    raise ExtractorError(msg, video_id=info['id'], ie=info['extractor'],
yt_dlp.utils.ExtractorError: [RadikoTimeFree] NORTHWAVE-20221120173000: No video formats found!
```

**Comment by pukkandan** [comment]
Filename cannot necessarily be determined without formats. In your specific case, you are passing a fixed filename and so it is not a problem, but it is not possible in general. It also doesn't really make sense to look for existing files when there is nothing to download imo.

Since the extractor code is your own, a quick workaround would be to return a format with some random URL and the correct `ext`. Then yt-dlp will detect the file. Another solution would be to do the same modification in `--write-info-json` and loading it back. A workaround with `--parse-metadata` may be possible too, but I'd have to look into it. Let me know if I should.

Overall, the feature seems out of scope for the core project, but I hope one of these solutions work for you. What do you think?

**Comment by garret1317** [comment]
yeah, giving garbage formats works 👍
`--write-info-json` with `--ignore-no-formats-error` works, but i can't load it back without getting the error.
oh well, i think i'll go with garbage formats anyway, it does it all in one go
thanks!
