### ISSUE TITLE
ivi.ru not working

### ISSUE THREAD

**Issue by qzmtch** [yt-dlp/yt-dlp#7021]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that a **supported** site is broken
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

russia

### Provide a description that is worded well enough to be understood

yt-dlp does not download videos that are available on the site and does not require a subscription
like those that require a subscription are also not downloaded, but I did not check
https://www.ivi.ru/watch/darya/462280 this video is not downloadable although it is available on the site without a subscription
at the same time, it takes a very long time and heavily loads the processor at this stage before the error **[ivi] 462280: Downloading webpage**

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.ivi.ru/watch/darya/462280']
[debug] Encodings: locale cp1251, fs utf-8, pref cp1251, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (pip)
[debug] Python 3.10.8 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1q  5 Jul 2022)
[debug] exe versions: ffmpeg 2023-03-05-git-912ac82a3c-full_build-www.gyan.dev (setts), ffprobe 2023-03-05-git-912ac82a3c-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.09.24, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.2
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
yt-dlp is up to date (stable@2023.03.04)
[ivi] Extracting URL: https://www.ivi.ru/watch/darya/462280
[ivi] 462280: Downloading timestamp JSON
[ivi] 462280: Downloading video JSON
[ivi] 462280: Downloading webpage
ERROR: [ivi] 462280: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "C:\Python\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 1518, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Python\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 1615, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "C:\Python\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 1674, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "C:\Python\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 2615, in process_video_result
    self.raise_no_formats(info_dict)
  File "C:\Python\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 1046, in raise_no_formats
    raise ExtractorError(msg, video_id=info['id'], ie=info['extractor'],
yt_dlp.utils.ExtractorError: [ivi] 462280: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

**Comment by dirkf** [comment]
The test videos for site are only available in Russia. The extractor checks this in the API result from the site, but the site's web pages just fail to have a playable link.

The problem show is from notorious DRM-fiends Paramount. If `-F --allow-unplayable-formats` lists formats that aren't shown with just `-F`, your Darya viewing will have to be done in some other way.

**Comment by qzmtch** [comment]
```
C:\Users\QZMTCH\Desktop>yt-dlp -F --allow-unplayable-formats https://www.ivi.ru/watch/darya/462280
WARNING: You have asked for UNPLAYABLE formats to be listed/downloaded. This is a developer option intended for debugging.
         If you experience any issues while using this option, DO NOT open a bug report
[ivi] Extracting URL: https://www.ivi.ru/watch/darya/462280
[ivi] 462280: Downloading timestamp JSON
[ivi] 462280: Downloading video JSON
[ivi] 462280: Downloading webpage
[info] Available formats for 462280:
ID                  EXT  RESOLUTION │   FILESIZE PROTO │ VCODEC  ACODEC
────────────────────────────────────────────────────────────────────────
VODHLS-FPS-lo       m3u8 unknown    │   95.50MiB m3u8  │ unknown unknown
VODDASH-MDRM-lo     mpd  unknown    │   95.50MiB https │ unknown unknown
VODHLS-FPS-hi       m3u8 unknown    │  189.88MiB m3u8  │ unknown unknown
VODDASH-MDRM-hi     mpd  unknown    │  189.88MiB https │ unknown unknown
VODHLS-FPS-ABRSHQ   m3u8 unknown    │  269.25MiB m3u8  │ unknown unknown
VODHLS-FPS-SHQ      m3u8 unknown    │  269.25MiB m3u8  │ unknown unknown
VODDASH-MDRM-ABRSHQ mpd  unknown    │  269.25MiB https │ unknown unknown
VODDASH-MDRM-SHQ    mpd  unknown    │  269.25MiB https │ unknown unknown
```


formats available

**Comment by dirkf** [comment]
I'm afraid that confirms the diagnosis. To be quite sure, you could try playing the show in your browser with [DRM disabled](https://github.com/yt-dlp/yt-dlp/issues/4062#issuecomment-1153474056).

**Comment by qzmtch** [comment]
https://i.imgur.com/OOnXt8l.png 
there are applications for android https://play.google.com/store/apps/details?id=ru.ivi.client and tv boxes https://www.ivi.ru/devices
while there is no way to check the application in the emulator, but most likely they will also not be played without drm

downloaded this file m3u8
`yt-dlp -f VODHLS-FPS-SHQ --allow-unplayable-formats https://www.ivi.ru/watch/darya/462280`
there is a beginning
```
#EXTM3U
#EXT-X-TARGETDURATION:4
#EXT-X-ALLOW-CACHE:YES
#EXT-X-PLAYLIST-TYPE:VOD
#EXT-X-KEY:METHOD=SAMPLE-AES,URI="skd://ivifairplay",KEYFORMAT="com.apple.streamingkeydelivery",KEYFORMATVERSIONS="1"
#EXT-X-VERSION:5
#EXT-X-MEDIA-SEQUENCE:1
```

ok, if it can't be fixed in ut-dlp, then we should close the topic?

**Comment by october262** [comment]
the Daria test video is downloadable - https://ivi-vod-world.servicecdn.ru/mp4-hd720/7Fe6I_qZm18Maf7g_jXP2A,1683693427/storage2/contents/b/f/ceb8427d91d507ed055b6462c80375.mp4  found via dev tools

**Comment by qzmtch** [comment]
> the Daria test video is downloadable - https://ivi-vod-world.servicecdn.ru/mp4-hd720/7Fe6I_qZm18Maf7g_jXP2A,1683693427/storage2/contents/b/f/ceb8427d91d507ed055b6462c80375.mp4 found via dev tools

this is trailer https://i.imgur.com/Z1hzKhw.png

**Comment by dirkf** [comment]
The extractor thinks, and your browser test confirms, that the formats with non-null `DRM` fields are DRM-protected. You can download one using `--allow-unplayable-formats` and perhaps if you leave it on your hard disk for long enough it will magically be transformed into a playable video. Or search (maybe in the Internet Archive) for another source of this excellent content, and for RU subs if needed.

**Comment by gamer191** [comment]
I can't figure out what `mdrm` means. Could be microsoft DRM, or mobile DRM, but both wouldn't make sense, because there's only 2 possible values for DRM, `mdrm` and `fps`, the latter of which is likely Apple's fairplay streaming DRM. Chrome can only use Google's DRM, so something doesn't add up!

**Comment by dirkf** [comment]
Maybe an internal designation from some playout DRM management system: suppose they started with FP and then upgraded their system to "multi-DRM" capability and used `MDRM` to designate the newly <strike>crippled</strike>added streams.

**Comment by gamer191** [comment]
> Maybe an internal designation from some playout DRM management system: suppose they started with FP and then upgraded their system to "multi-DRM" capability and used `MDRM` to designate the newly crippledadded streams.

Doubt it. If it were the case, how would the browser know which streams contain Widevine (see https://github.com/yt-dlp/yt-dlp/issues/7021#issuecomment-1540823499)
On 2nd thought, the license url is w.ivi.ru, so that hints at it being Widevine

**Comment by qzmtch** [comment]
> On 2nd thought, the license url is w.ivi.ru, so that hints at it being Widevine

and this means that it is impossible to add decryption to yt-dlp?

**Comment by gamer191** [comment]
> and this means that it is impossible to add decryption to yt-dlp?

Unfortunately, Widevine and FairPlay decryption both can't be supported, for legal reasons :(

Out of interest, are there any values of `licence_server_url`, or `licence_cert_host` (I don't know the difference) that don't start with `fairplay.ivi.ru` or `w.ivi.ru`

**Comment by qzmtch** [comment]
> More importantly, are there any formats that don't contain `licence_server_url` and `licence_cert_host`?

unfortunately there are no other addresses

and if you get the decryption key, can you decrypt it in ffmpeg? 
`ffmpeg -decryption_key KEY -i encrypted_media.mp4 -codec copy decrypted_media.mp4`
is it possible to add to post-processing yt-dlp?

**Comment by qzmtch** [comment]
`yt-dlp --allow-unplayable-formats --ppa "ffmpeg_i:-decryption_key KEY -codec copy" https://www.ivi.ru/watch/darya/462280`
so can i do it?

**Comment by bashonly** [comment]
No. Breaking DRM is not something that will be supported by yt-dlp.

**Comment by qzmtch** [comment]
found a solution, quite old but working
python script
```
import requests
 
id_film = input('\nURL: ').strip()
id_film = ''.join(id_film.split('/')[-1:])
 
sessivi = 'its value, leave single quotes'
 
IVIheaders = {
    'User-Agent': 'Mozilla/5.0 (X11; GNU/Linux) AppleWebKit/601.1 (KHTML, like Gecko) Tesla QtCarBrowser Safari/601.1'
}
 
stream = requests.post(url='https://api.ivi.ru/light/', json={'params': [id_film, {'app_version': 3806, 'session': sessivi}], 'method': 'da.content.get'}, headers=IVIheaders)
stream.close()
print(stream.text)
```

you need to enter "sessivi" value from the browser cookie into it
will return json with unencrypted mp4 direct links (in some videos quality 1080 by subscription, and the rest are available via direct links)
```
"result": {
        "allow_download": true,
        "caption_card_files": null,
        "category_ids": [16],
        "compilation": "\u041e\u0434\u0438\u043d\u043e\u0447\u0435\u0441\u0442\u0432\u043e \u0432 \u0441\u0435\u0442\u0438",
        "compilation_hru": "odinochestvo-v-seti",
        "compilation_id": 15159,
        "content_formats_require_subscription": ["MP4-HD1080"],
        "copyright_overlay": "",
        "credits_begin_time": 2367,
        "delete_after": "2025-05-31",
        "duration": 2378,
        "external_values": {},
        "files": [{
                "content_format": "MP4-HD720",
                "height": "720",
                "id": 17726015,
                "size_in_bytes": 837025792,
                "url": "http://region.dfs.ivi.ru/jW1HMTy4DSN4hUGpQHfXlz9m6faiY1dWwcyZ6M1DyKM7jiHxOzvx11609/mp4-hd720/o6YE2BNmDiP0HKWjW8GMAg,1683866769/storage9/contents/6/0/6d92215e7fca35129306423e9d6bf6.mp4",
                "width": "1280"
            }, {
                "content_format": "MP4-SHQ",
                "height": "540",
                "id": 17726028,
                "size_in_bytes": 571473920,
                "url": "http://region.dfs.ivi.ru/jW1HMTy4DSN4hUGpQHfXlz9m6faiY1dWwcyZ6M1DyKM7jiHxOzvx11609/mp4-shq/pDLGgCOzhFehDXjRdBwnoQ,1683866769/storage9/contents/c/e/cd51e665dd36b7d80a2c4b2f489ac2.mp4",
                "width": "960"
            }, {
                "content_format": "MP4-hi",
                "height": "404",
                "id": 17726018,
                "size_in_bytes": 366608384,
                "url": "http://region.dfs.ivi.ru/jW1HMTy4DSN4hUGpQHfXlz9m6faiY1dWwcyZ6M1DyKM7jiHxOzvx11609/mp4-hi/cJbASlESSDfPrbFUgC2doA,1683866769/storage9/contents/7/0/8c7035d60823471fa82c178503ccf4.mp4",
                "width": "720"
            }, {
                "content_format": "MP4-lo",
                "height": "270",
                "id": 17726020,
                "size_in_bytes": 184549376,
                "url": "http://region.dfs.ivi.ru/jW1HMTy4DSN4hUGpQHfXlz9m6faiY1dWwcyZ6M1DyKM7jiHxOzvx11609/mp4-lo/DM0RDkN3f17I47MXN2p8Mg,1683866769/storage9/contents/0/b/9b34c353a28a11c9fbe5c8a17780fe.mp4",
                "width": "480"
            }
        ]
```
can you add this to yt-dlp?

**Comment by gamer191** [comment]
@qzmtch out of interest, how did you find that?

**Comment by gamer191** [comment]
Hmm, so theoretically yt-dlp should already be using the "light" api

Can you please run it with `--print-traffic`, and then send the log to me on Discord (shadowkirby13#6120), or by email (cxl9p7xa@duck.com)

**Comment by gamer191** [comment]
Actually nevermind, I missed your part about needing to pass the sessivi cookie

**Comment by qzmtch** [comment]
> out of interest, how did you find that?

<details>
  <summary>.</summary>
"IVI_Support" user on one torrent tracker left a post "Get DRM-free with IVI" there is no post now, but it was copied on another forum in 2021
</details>

**Comment by peachyoon** [comment]
Не знаю, может, кто снова ищет инфу
Покупаете подписку, скачиваете кукки (или указываете, что брать нужно с такого-то сайта). Указываете рефер ivi.py\сайт. Затем выбираете сериал\фильм, проигрываете, обновляете страницу и выбираете качество. В фильтрах ищите ссылку на mpd. Удаляете всё после ".mpd". Скачаете без проблем. На Иви нет защиты

**Comment by 0xvd** [comment]
> Не знаю, может, кто снова ищет инфу Покупаете подписку, скачиваете кукки (или указываете, что брать нужно с такого-то сайта). Указываете рефер ivi.py\сайт. Затем выбираете сериал\фильм, проигрываете, обновляете страницу и выбираете качество. В фильтрах ищите ссылку на mpd. Удаляете всё после ".mpd". Скачаете без проблем. На Иви нет защиты

Are U doing that much stuff ? 
Mbega Ukora ibintu vyinshi gutyo ?

**Comment by peachyoon** [comment]
> > Не знаю, может, кто снова ищет инфу Покупаете подписку, скачиваете кукки (или указываете, что брать нужно с такого-то сайта). Указываете рефер ivi.py\сайт. Затем выбираете сериал\фильм, проигрываете, обновляете страницу и выбираете качество. В фильтрах ищите ссылку на mpd. Удаляете всё после ".mpd". Скачаете без проблем. На Иви нет защиты
> 
> Are U doing that much stuff ? Mbega Ukora ibintu vyinshi gutyo ?

Нет 🫩 У меня расширение автоматически выдаёт строку. Точно так же и с drm видосами. Я просто вставляю и скачиваю. Я слишком ленива для всего этого
