### ISSUE TITLE
Using cookies without file in API

### ISSUE THREAD

**Issue by DanilaParakhnevich** [yt-dlp/yt-dlp#7022]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

How to use cookie data as json object in python for using ytdlp? May be exists some way to add them to headers?

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
I have no problems with compiling
```

**Comment by dirkf** [comment]
1. Construct the cookies string `xxx` from your JSON data according to RFCs.
2. Pass the cookies string as the value of a `Cookie` header. CLI: `--add-headers "Cookie: xxx"`.

See https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cookie.

**Comment by pukkandan** [comment]
dirkf's solution has the problem that the cookies are sent to all domains. A better method is to transform it into a Netscape format textstream that http.cookiejar.MozillaCookieJar can read.

Ref:

https://github.com/yt-dlp/yt-dlp/blob/ddae33754ae1f32dd9c64cf895c47d20f6b5f336/yt_dlp/YoutubeDL.py#L305
https://curl.haxx.se/docs/http-cookies.html
https://docs.python.org/3/library/http.cookiejar.html#http.cookiejar.MozillaCookieJar

**Comment by dirkf** [comment]
It really depends on OP's unspecified requirements: is this a quick one-off for some URL, or a production script that will be used with multiple sites?

While you probably don't care (and the server probably doesn't either) if you send cookies for videos.some.site to other.some.site or media.somesite.cdn, you shouldn't add a [prepared cookie header option](https://github.com/yt-dlp/yt-dlp/issues/7022#issuecomment-1543916013) to a general-purpose config file or download script.
