### ISSUE TITLE
[extractor/tvp] better hints for geoblock

### ISSUE THREAD

**Issue by selfisekai** [yt-dlp/yt-dlp#7023]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a site-specific feature
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Netherlands

### Example URLs

https://vod.tvp.pl/filmy-dokumentalne,163/krzysztof-krawczyk--cale-moje-zycie,332512

### Provide a description that is worded well enough to be understood

turns out at least some geo-restricted videos play in browser if logged in to a free account (might be EU only). the geoblock error message I'm getting when not logged in is this:
>Z powodów licencyjnych materiał jest niedostępny w Twoim kraju.
>
>Przepisy UE pozwalają abonentom, którzy w kraju zamieszkania (w tym przypadku w PL) zakupili pakiet TVP + utrzymać dostęp do materiałów wchodzących w skład pakietu, w czasie wizyty w innym kraju UE.

so I guess they wanted to implement this as it says but made an assumption that an account logged in means SVOD and not logged in means AVOD? login is by cookies and `--cookies-from-browser firefox` works for me on yt-dlp master

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

not logged in:

```shell
[debug] Command-line config: ['https://vod.tvp.pl/filmy-dokumentalne,163/krzysztof-krawczyk--cale-moje-zycie,332512', '-v', '--skip-download']
[debug] User config "/home/lauren/.config/yt-dlp/config": ['--concurrent-fragments', '8', '--netrc', '--trim-filenames', '64', '--sub-langs', 'all,-live_chat', '--embed-subs']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (source)
[debug] Lazy loading extractors is disabled
[debug] Git HEAD: ef8fb7f02
[debug] Python 3.11.3 (CPython x86_64 64bit) - Linux-6.1.27-1-lts-x86_64-with (OpenSSL 3.1.0 14 Mar 2023)
[debug] exe versions: ffmpeg 6.0 (setts), ffprobe 6.0
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, secretstorage-3.3.3, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1813 extractors
[tvp:vod] Extracting URL: https://vod.tvp.pl/filmy-dokumentalne,163/krzysztof-krawczyk--cale-moje-zycie,332512
[tvp:vod] 332512: Downloading JSON metadata
[tvp:vod] 332512: Downloading JSON metadata
ERROR: [tvp:vod] 332512: Woronicza said: GEOIP_FILTER_FAILED (HTTP 403); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/home/lauren/yt-dlp/yt_dlp/extractor/common.py", line 694, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lauren/yt-dlp/yt_dlp/extractor/tvp.py", line 570, in _real_extract
    playlist = self._call_api(f'{video_id}/videos/playlist', video_id, query={'videoType': 'MOVIE'})
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lauren/yt-dlp/yt_dlp/extractor/tvp.py", line 493, in _call_api
    raise ExtractorError(f'Woronicza said: {document.get("code")} (HTTP {urlh.status})')
```

browser cookies:
```shell
[debug] Command-line config: ['https://vod.tvp.pl/filmy-dokumentalne,163/krzysztof-krawczyk--cale-moje-zycie,332512', '-v', '--cookies-from-browser', 'firefox', '--skip-download']
[debug] User config "/home/lauren/.config/yt-dlp/config": ['--concurrent-fragments', '8', '--netrc', '--trim-filenames', '64', '--sub-langs', 'all,-live_chat', '--embed-subs']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (source)
[debug] Lazy loading extractors is disabled
[debug] Git HEAD: ef8fb7f02
[debug] Python 3.11.3 (CPython x86_64 64bit) - Linux-6.1.27-1-lts-x86_64-with (OpenSSL 3.1.0 14 Mar 2023)
[debug] exe versions: ffmpeg 6.0 (setts), ffprobe 6.0
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, secretstorage-3.3.3, sqlite3-2.6.0, websockets-10.4
[Cookies] Extracting cookies from firefox
[debug] Extracting cookies from: "/home/lauren/.mozilla/firefox/[redacted]/cookies.sqlite"
[Cookies] Extracted [redacted] cookies from firefox
[debug] Proxy map: {}
[debug] Loaded 1813 extractors
[tvp:vod] Extracting URL: https://vod.tvp.pl/filmy-dokumentalne,163/krzysztof-krawczyk--cale-moje-zycie,332512
[tvp:vod] 332512: Downloading JSON metadata
[tvp:vod] 332512: Downloading JSON metadata
[tvp:vod] 332512: Downloading m3u8 information
[tvp:vod] 332512: Downloading MPD manifest
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 332512: Downloading 1 format(s): 5128+f1-a1-x3
[info] There's no subtitles for the requested languages
```

**Comment by gamer191** [comment]
Given this site is clearly bad at enforcing geo-restrictions, can you please check if `--geo-bypass-country CODE` works
NOTE: `--geo-bypass-country CODE` has been replaced with `--xff CODE` in master

**Comment by selfisekai** [comment]
no, that works correctly:
```
[debug] Using fake IP 83.5.107.173 (PL) as X-Forwarded-For
[tvp:vod] Extracting URL: https://vod.tvp.pl/filmy-dokumentalne,163/krzysztof-krawczyk--cale-moje-zycie,332512
[tvp:vod] 332512: Downloading JSON metadata
[tvp:vod] 332512: Downloading JSON metadata
ERROR: [tvp:vod] 332512: Woronicza said: GEOIP_FILTER_FAILED (HTTP 403)
```

**Comment by dirkf** [comment]
I expect that actually constructing a valid free account cookie is too hard, though ofc one never knows.

Is the suggestion that the extractor should include a free account and perform login with it?

Otherwise, if affected shows can be [detected](https://github.com/ytdl-org/youtube-dl/pull/32028#issuecomment-1541281027), the geo-restriction message could be changed to suggest the free account work-around when applicable.

**Comment by selfisekai** [comment]
the exact cookie that makes this work is `session_uuid`, which is just an UUID v4. sending a random one does not work.

the suggestion was that instead of just showing the user `GEOIP_FILTER_FAILED` we can say "btw you might be able to workaround this with a free account and --cookies-from-browser"

also noticed: sessions for vod.tvp.pl only last half an hour, but user.tvp.pl sessions last longer. I'm gonna look into renewing them

**Comment by selfisekai** [comment]
nevermind, this doesn't work anymore. I wonder if they are reading this
