### ISSUE TITLE
Monitoring the specified channel for new live streams and then automatically recording from the first second

### ISSUE THREAD

**Issue by zone559** [yt-dlp/yt-dlp#7027]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Monitoring the specified channel for new live streams and then automatically recording from the first second

this github project use to be able to do it, but it seem abandon 
https://github.com/rytsikau/ee.Yrewind

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
You can use `--wait-for-video` and `--live-from-start`

```
--wait-for-video MIN[-MAX]      Wait for scheduled streams to become
                                available. Pass the minimum number of
                                seconds (or range) to wait between retries
```
```
--live-from-start               Download livestreams from the start.
                                Currently only supported for YouTube
                                (Experimental)
```

**Comment by pukkandan** [comment]
This won't work for channels that have multiple lives running simultaneously. There is no way to handle that case except to scan the entire /live page each time.
