### ISSUE TITLE
ipv4 vs ipv6: prioritise faster connection

### ISSUE THREAD

**Issue by mpwg** [yt-dlp/yt-dlp#7032]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

I've tried to download some files from ardmediathek.de and noticed it was extremely slow. after some testing I noticed that the server answered my IPv6 calls much slower than IPv4. (so adding "-4" fixed my immediate issue)

I'd like a feature where yt-dlp tests both IPv4 and IPv6 and uses the *faster* connection.

(I've added the first lines from the IPv6 connection, the lines where it started to download took 20-30s per line.)

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp -vU  https://www.ardmediathek.de/sendung/ein-fall-fuer-die-erdmaennchen/Y3JpZDovL25kci5kZS80NDQ4/
[debug] Command-line config: ['-vU', 'https://www.ardmediathek.de/sendung/ein-fall-fuer-die-erdmaennchen/Y3JpZDovL25kci5kZS80NDQ4/']
[debug] System config "/etc/yt-dlp.conf": ['-f', 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/mp4']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (pip)
[debug] Python 3.11.3 (CPython x86_64 64bit) - macOS-13.3.1-x86_64-i386-64bit (OpenSSL 1.1.1t  7 Feb 2023)
[debug] exe versions: ffmpeg 6.0 (setts), ffprobe 6.0
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
yt-dlp is up to date (stable@2023.03.04)
[debug] Using fake IP 53.244.63.161 (DE) as X-Forwarded-For
[ARDBetaMediathek] Extracting URL: https://www.ardmediathek.de/sendung/ein-fall-fuer-die-erdmaennchen/Y3JpZDovL25kci5kZS80NDQ4/
[ARDBetaMediathek] [Playlist] ein-fall-fuer-die-erdmaennchen: Downloading JSON metadata
[ARDBetaMediathek] [Playlist] ein-fall-fuer-die-erdmaennchen: Downloading JSON metadata
[download] Downloading playlist: ein-fall-fuer-die-erdmaennchen
[ARDBetaMediathek] Playlist ein-fall-fuer-die-erdmaennchen: Downloading 96 items of 96
[download] Downloading item 1 of 96
[ARDBetaMediathek] Extracting URL: https://www.ardmediathek.de/ard/video/ein-fall-fuer-die-erdmaennchen/62-der-vulkanausbruch/Y3JpZDovL25kci5kZS82MjJlM2IzYy05NGY5LTQ1NjAtYTgwZC0yMTdjYmQwMGRiOTc
[ARDBetaMediathek] ein-fall-fuer-die-erdmaennchen/62-der-vulkanausbruch: Downloading JSON metadata
[ARDBetaMediathek] 12121965: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[info] 12121965: Downloading 1 format(s): hls-2378
[debug] Invoking hlsnative downloader on "https://adaptive.ndr.de/i/ndr/2022/1117/TV-20221117-1154-4500.,hq,hd,ln,mn,ao,.mp4.csmil/index-f2-v1-a1.m3u8"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 125
[download] Destination: 62. Der Vulkanausbruch [12121965].mp4
[download]   0.8% of ~  72.48MiB at   30.43KiB/s ETA 40:19 (frag 1/125)AtYTgwZC0yMTdjYmQwMGRiOTc
[ARDBetaMediathek] ein-fall-fuer-die-erdmaennchen/62-der-vulkanausbruch: Downloading JSON metadata
[ARDBetaMediathek] 12121965: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[info] 12121965: Downloading 1 format(s): hls-2378
[debug] Invoking hlsnative downloader on "https://adaptive.ndr.de/i/ndr/2022/1117/TV-20221117-1154-4500.,hq,hd,ln,mn,ao,.mp4.csmil/index-f2-v1-a1.m3u8"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 125
[download]   1.6% of ~ 171.98MiB at  190.88KiB/s ETA 31:56 (frag 2/125)
```

**Comment by Lesmiscore** [comment]
yt-dlp isn't a all-in-one solution....
Isn't it enough to add the `-4` option to your config?

**Comment by coletdjnz** [comment]
There is unlikely to be a difference that big between IP versions so don't think that is the issue.

What happens if you use `--force-ipv6`? If it doesn't work at all then your IPv6 configuration is broken (could be your ISP). yt-dlp tries IPv6 first by default and fallsback to IPv4 if that fails hence the long delay.

**Comment by mpwg** [comment]
it tells me 'Network is unreachable' but sites like https://test-ipv6.com say, my IPv6 works.

Anyway, looks like my issue.

**Comment by gamer191** [comment]
> it tells me 'Network is unreachable'

can you reproduce that on other sites with --force-ipv6

**Comment by gamer191** [comment]
> yt-dlp tries IPv6 first by default and fallsback to IPv4 if that fails after ~20s hence the long delay.

Perhaps yt-dlp could issue a warning in that case (and suggest adding -4 to your config)

Also, why 20 seconds? Google Chrome only waits 0.3 seconds (according to https://test-ipv6.com/faq_avoids_ipv6.html, although it's slightly wrong, since it's reference says 300ms, instead of 333ms)

**Comment by mpwg** [comment]
I think my IPv6 is just broken now and I didn't noticed it because other systems have a faster fall-back to IPv4
```
traceroute6 google.com
traceroute6 to google.com (2a00:1450:4001:808::200e) from 2a01:aea0:dd4:5a3c:fdb7:1319:ca4:7e05, 64 hops max, 12 byte packets
 1  fritz.box  1.411 ms  0.658 ms  0.606 ms
 2  2a01:aea0:df4:1::87f4  4004.617 ms !A  1003.483 ms !A  4003.301 ms !A
```

vs
```
traceroute google.com 
traceroute to google.com (172.217.16.142), 64 hops max, 52 byte packets
 1  fritz.box (192.168.0.1)  1.009 ms  1.014 ms  0.563 ms
 2  static-144-208-194-1.dsl.telematica.at (144.208.194.1)  7.222 ms  6.815 ms  6.527 ms
 3  lt0-3-0-1.mpr01.anx04.vie.at.anexia-it.net (144.208.208.190)  6.151 ms  27.724 ms  6.494 ms
 4  ae5-0.bbr02.anx04.vie.at.anexia-it.net (144.208.208.188)  19.983 ms
    ae6-0.bbr01.anx04.vie.at.anexia-it.net (144.208.208.186)  18.475 ms  18.175 ms
 5  ae2-0.bbr01.anx82.fra.de.anexia-it.net (144.208.208.150)  18.629 ms  18.002 ms  19.826 ms
 6  ae1-0.bbr02.anx84.nue.de.anexia-it.net (144.208.208.137)  18.773 ms
    ae1-0.bbr01.anx25.fra.de.anexia-it.net (144.208.208.144)  18.349 ms  18.503 ms
 7  r01-at-klu.lucesem.at (144.208.211.75)  19.739 ms  20.288 ms  20.365 ms
 8  ae2-0.bbr02.anx25.fra.de.anexia-it.net (144.208.208.141)  19.793 ms  21.361 ms  24.937 ms
 9  142.250.214.202 (142.250.214.202)  19.207 ms
    142.250.214.200 (142.250.214.200)  18.411 ms
    142.250.214.202 (142.250.214.202)  20.251 ms
10  * 66.249.95.169 (66.249.95.169)  28.017 ms *
11  142.250.214.196 (142.250.214.196)  20.637 ms
    zrh04s06-in-f142.1e100.net (172.217.16.142)  18.592 ms  18.292 ms
```

**Comment by coletdjnz** [comment]
> > yt-dlp tries IPv6 first by default and fallsback to IPv4 if that fails after ~20s hence the long delay.
> 
> Perhaps yt-dlp could issue a warning in that case (and suggest adding -4 to your config)
> 
> Also, why 20 seconds? Google Chrome only waits 0.3 seconds (according to https://test-ipv6.com/faq_avoids_ipv6.html, although it's slightly wrong, since it's reference says 300ms, instead of 333ms)


> > yt-dlp tries IPv6 first by default and fallsback to IPv4 if that fails after ~20s hence the long delay.
> 
> Perhaps yt-dlp could issue a warning in that case (and suggest adding -4 to your config)

It is done under the hood so I don't think we can.

**Comment by gamer191** [comment]
> nvm we can for urllib since we re-implement the source address connection functionality

Are you talking about adding a warning or reducing the delay?
