### ISSUE TITLE
[iwara.tv] Videos with "blocked" tags don't appear in profile list

### ISSUE THREAD

**Issue by bobbbob98** [yt-dlp/yt-dlp#7035]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that a **supported** site is broken
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Provide a description that is worded well enough to be understood

With the new commit videos with blocked tags can now be downloaded when logged in (this doesn't seem to work with extracted cookies but does work with --username and --password). However when you try to download a profile yt-dlp doesn't find videos with blocked tags, even with the user/pass options. In the output below, yt-dlp only finds one video even though there's 10 videos on the profile when logged in. Seems like yt-dlp isn't logging in when fetching the video list?

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--username', 'PRIVATE', '--password', 'PRIVATE', 'https://www.iwara.tv/profile/lumymmd']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2023.05.11.094900 [21b9413cf] (zip)
[debug] Python 3.11.3 (CPython x86_64 64bit) - Linux-6.2.14-200.fc37.x86_64-x86_64-with-glibc2.36 (OpenSSL 3.0.8 7 Feb 2023, glibc 2.36)
[debug] exe versions: ffmpeg 5.1.3 (setts), ffprobe 5.1.3
[debug] Optional libraries: Cryptodome-3.17.0, brotli-1.0.9, certifi-2021.10.08, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1813 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Available version: nightly@2023.05.11.094900, Current version: nightly@2023.05.11.094900
Current Build Hash: 68cfb85d91da7da1a1c6f0d01b0f488b89c3275ca89fb893d6e573ba07a30d9d
yt-dlp is up to date (nightly@2023.05.11.094900)
[iwara:user] Extracting URL: https://www.iwara.tv/profile/lumymmd
[iwara:user] lumymmd: Requesting user info
[download] Downloading playlist: Lumy MMD
[iwara:user] lumymmd: Downloading page 0
[iwara:user] Playlist Lumy MMD: Downloading 1 items of 1
[download] Downloading item 1 of 1
[debug] Loading iwara.throw345313 from cache
[debug] Loading iwara.throw345313 from cache
[iwara] Fetching media token
[debug] [iwara] Skipping logging in
[iwara] Extracting URL: https://iwara.tv/video/m3wozcpykc3eap0w
[iwara] m3wozcpykc3eap0w: Downloading JSON metadata
[iwara] m3wozcpykc3eap0w: Downloading JSON metadata
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] m3wozcpykc3eap0w: Downloading 1 format(s): Source
[debug] Invoking http downloader on "https://mikoto.iwara.tv/view?filename=1675934383_M3WOZCpyKC3eap0W_Source.mp4&path=2023%2F02%2F09&expires=1683831320&hash=2e96e96c4da46083979e12832f310fcac7f76c4941404e44156f22b332d75f26"
[download] Destination: Deep Blue Song - Keqing [m3wozcpykc3eap0w].mp4
[download] 100% of  172.25MiB in 00:00:36 at 4.66MiB/s
[download] Finished downloading playlist: Lumy MMD
```

**Comment by pukkandan** [comment]
> Seems like yt-dlp isn't logging in when fetching the video list?

Can confirm

**Comment by toomyzoom** [comment]
Same as #6671. Need to send access token with the request.

**Comment by toomyzoom** [comment]
I think this shouldn't be closed. The change should be the same in #6671 but the same access token is needed for user's profile (IwaraUserIE) and playlist (IwaraPlaylistIE) request in their respective classes.
