### ISSUE TITLE
All southpark sites broken (easy fix)

### ISSUE THREAD

**Issue by xypwn** [yt-dlp/yt-dlp#7037]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that a **supported** site is broken
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Germany

### Provide a description that is worded well enough to be understood

South Park sites seem to be broken (tested on southpark.de, southpark.cc.com, southparkstudios.com via VPN). I don't know this codebase and python very well, but I understand how the site works, so I think I should be able to provide all info necessary to fix this.

## Here is the pipeline of how yt-dlp currently tries to obtain an episode's HLS stream
- Get the episode's HTML and extract the `__DATA__` JS constant.
- From the `__DATA__`, get the episode's `MGID` (MTV internal URI)
- Make a request to `http://media.mtvnservices.com/pmt/e1/access/index.html?uri={MGID}&configtype=edge&ref={Episode URL}`, response is JSON
- From the JSON response, extract `feedWithQueryParams`. This is _**supposed to**_ give you the 'MediaGen' URL (a document containing the RTMP/HLS master stream). It seems, however, that the `feedWithQueryParams` URL has been invalidated/removed.

## Here's the solution:
**You don't actually need to make a request to the `feedWithQueryParams` URL!**
The RTMP/HLS master stream URLs are actually contained within the media.mtvnservices.com JSON response.
The JSON looks something like this (I took out some irrelevant parts):
```json
{
  "feed": {
    "title": "The Pandemic Special",
    "link": "",
    "description": "Randy comes to terms with his role in the COVID-19 outbreak as the on-going pandemic presents continued challenges to the citizens of South Park.",
    "image": {
      "title": {},
      "link": "",
      "url": "https://playplex.mtvnimages.com/uri/mgid:arc:content:southpark.intl:230a4f02-f583-11ea-834d-70df2f866ace?stage=staging&ep=shared.southpark.gsa.de"
    },
    "items": [
      {
        "group": {
          "content": "https://media-utils.mtvnservices.com/services/MediaGenerator/mgid:arc:video:southpark.intl:d514e26e-2d28-11ec-9b1b-0e40cf2fc285?arcStage=staging&accountOverride=intl.mtvi.com&billingSection=intl&device={device}&ep=20476225"
        },
        "title": "South Park"
      }
    ]
  },
}
```
This means that all of the feed information is contained within this JSON.
Now, to get the HLS master streams, you simply extract all `feed.items[i].group.content` (you iterate over them to get all segments' URLs).
Now, for each URL you obtain, you remove the `&device={device}` and add `&acceptMethods=hls`, and **BAM**, you get you MediaGen URL, and from there the HLS master stream.

The bonus of this solution is also that you make one HTTP request less.

---

I hope my response makes it easy to fix this issue.
Feel free to comment if you have any further questions.

---

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.southpark.de/en/episodes/2dhgcd/south-park-cupid-ye-season-26-ep-1']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (source)
[debug] Lazy loading extractors is disabled
[debug] Git HEAD: 21b9413cf
[debug] Python 3.10.10 (CPython x86_64 64bit) - Linux-6.1.26-1-MANJARO-x86_64-with-glibc2.37 (OpenSSL 3.0.8 7 Feb 2023, glibc 2.37)
[debug] exe versions: ffmpeg 6.0 (setts), ffprobe 6.0, rtmpdump 2.4
[debug] Optional libraries: certifi-2022.12.07, sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Loaded 1813 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
yt-dlp is up to date (stable@2023.03.04)
[southpark.de] Extracting URL: https://www.southpark.de/en/episodes/2dhgcd/south-park-cupid-ye-season-26-ep-1
[southpark.de] south-park-cupid-ye-season-26-ep-1: Downloading webpage
[southpark.de] 94ad0b35-9036-11ed-ad8e-0e40cf2fc285: Downloading JSON metadata
[southpark.de] 94ad0b35-9036-11ed-ad8e-0e40cf2fc285: Downloading info
ERROR: [southpark.de] 2dhgcd/south-park-cupid-ye-season-26-ep-1: Unable to download XML: HTTP Error 500: Internal Server Error (caused by <HTTPError 500: 'Internal Server Error'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/tmp/tmp.FkXxtckmjP/yt-dlp/yt_dlp/extractor/common.py", line 694, in extract
    ie_result = self._real_extract(url)
  File "/tmp/tmp.FkXxtckmjP/yt-dlp/yt_dlp/extractor/mtv.py", line 323, in _real_extract
    videos_info = self._get_videos_info(mgid, url=url)
  File "/tmp/tmp.FkXxtckmjP/yt-dlp/yt_dlp/extractor/mtv.py", line 227, in _get_videos_info
    return self._get_videos_info_from_url(info_url, video_id, use_hls)
  File "/tmp/tmp.FkXxtckmjP/yt-dlp/yt_dlp/extractor/mtv.py", line 230, in _get_videos_info_from_url
    idoc = self._download_xml(
  File "/tmp/tmp.FkXxtckmjP/yt-dlp/yt_dlp/extractor/common.py", line 1048, in download_content
    res = getattr(self, download_handle.__name__)(url_or_request, video_id, **kwargs)
  File "/tmp/tmp.FkXxtckmjP/yt-dlp/yt_dlp/extractor/common.py", line 1012, in download_handle
    res = self._download_webpage_handle(
  File "/tmp/tmp.FkXxtckmjP/yt-dlp/yt_dlp/extractor/common.py", line 882, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query, expected_status=expected_status)
  File "/tmp/tmp.FkXxtckmjP/yt-dlp/yt_dlp/extractor/common.py", line 839, in _request_webpage
    raise ExtractorError(errmsg, cause=err)

  File "/tmp/tmp.FkXxtckmjP/yt-dlp/yt_dlp/extractor/common.py", line 821, in _request_webpage
    return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query))
  File "/tmp/tmp.FkXxtckmjP/yt-dlp/yt_dlp/YoutubeDL.py", line 3753, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/usr/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 500: Internal Server Error
```

**Comment by dirkf** [comment]
The SP sites are aggressively regional, so that a test show URL https://southpark.there/path is redirected to https://southpark.here/path, where `there` is the domain of the test URL and `here` is the domain that the site thinks you should be using based on what it believes to be your location. Typically the redirected URL will be invalid, giving 404 instead of a geo-block error. API URLs using mtvnservices.com don't behave in this way. 

The first test URL from the extractor exists in both US and UK SP sites. The JSON fetched according to the suggested scheme from http://media.mtvnservices.com/pmt/e1/access/index.html?uri=mgid%3Aarc%3Avideo%3Asouthpark.intl%3A31929ad5-8269-11eb-8774-70df2f866ace&configtype=edge&ref=https%3A%2F%2Fsouthpark.cc.com%2Fvideo-clips%2Fd7wr06%2Fsouth-park-you-all-agreed-to-counseling looks like this:
```py
{'acceptMethods': '',
 ...
 'brightcove_mediagenRootURL': '',
 'brightcove_version': '',
 ...
 'ccEnabled': False,
 ...
 'configURL': '/pmt-arc/e1/players/mgid:arc:video:southpark.intl:/config.js?uri=mgid:arc:video:southpark.intl:31929ad5-8269-11eb-8774-70df2f866ace&type=network&ref=southpark.cc.com&geo=GB&group=intl&network=None&device=Other&networkConnectionType=None&timezone=GMT&throughput=vhigh&bw=5000&name=ISP_REDACTED&city=CITY_REDACTED&state=EN&originalRef=https%3a%2f%2fsouthpark.cc.com%2fvideo-clips%2fd7wr06%2fsouth-park-you-all-agreed-to-counseling&fasLogic=true',
 'contentType': 'clip',
 ...
 'feed': {},
 'feedLoaderEndTime': 1683889494,
 'feedLoaderStartTime': 1683889494,
 'feedWithQueryParams': 'None',
 'flashHLSEnabled': True,
 ...
 'geo': 'GB',
 'group': 'intl',
 'hideScrubberThumbnail': False,
 'html5playerVersion': '1.30.5',
 'jsHLSEnabled': True,
 ...
 'mediaGen': 'http://media.mtvnservices.com/player/html5/mediagen/?uri={uri}&device={device}',
 ...
 'viewabilityEnabled': False,
 ...
}
```
The `configURL` says 404. The URL generated from `mediaGen` as suggested returns XML with a geo-block message.

Test URL 2 has the redirect issue.

Test URL 3 behaves better. <details><summary>Applying roughly the suggested scheme in yt-dl gives this:</summary>

```console
$ python3.9 -m youtube_dl -v -F test:southpark.cc.com_2
[debug] System config: ['--prefer-ffmpeg']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-F', 'test:southpark.cc.com_2']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Git HEAD: d1c6c5c4d
[debug] Python 3.9.16 (CPython 32bit) - Linux-4.4.0-210-generic-i686-with-glibc2.23 (OpenSSL 1.1.1t  7 Feb 2023, glibc 2.23)
[debug] exe versions: avconv 4.3, avprobe 4.3, ffmpeg 4.3, ffprobe 4.3
[debug] Proxy map: {}
[TestURL] Test URL: https://www.southparkstudios.com/episodes/h4o269/south-park-stunning-and-brave-season-19-ep-1
[southpark.cc.com] south-park-stunning-and-brave-season-19-ep-1: Downloading webpage
[southpark.cc.com] ed0508ac-1708-4865-835f-34d33e64a32f: Downloading JSON metadata
[download] Downloading playlist: Stunning and Brave
[southpark.cc.com] f1a6bb46-5c43-4dc8-b4aa-ebf10a8e287a: Downloading video urls
[southpark.cc.com] f1a6bb46-5c43-4dc8-b4aa-ebf10a8e287a: Downloading m3u8 information
[southpark.cc.com] 9baf1095-d8ee-4a54-bdf2-2954ff1f2070: Downloading video urls
[southpark.cc.com] 9baf1095-d8ee-4a54-bdf2-2954ff1f2070: Downloading m3u8 information
[southpark.cc.com] 40c01eed-7ad5-43ed-8f7e-110bd78bd4ae: Downloading video urls
[southpark.cc.com] 40c01eed-7ad5-43ed-8f7e-110bd78bd4ae: Downloading m3u8 information
[southpark.cc.com] 2f2050a9-bd3f-4614-a9b7-278474e0e86d: Downloading video urls
[southpark.cc.com] 2f2050a9-bd3f-4614-a9b7-278474e0e86d: Downloading m3u8 information
[southpark.cc.com] e8c2d6cc-17ba-47c4-a8af-f47773122113: Downloading video urls
[southpark.cc.com] e8c2d6cc-17ba-47c4-a8af-f47773122113: Downloading m3u8 information
[southpark.cc.com] playlist Stunning and Brave: Downloading 5 videos
[download] Downloading video 1 of 5
[info] Available formats for f1a6bb46-5c43-4dc8-b4aa-ebf10a8e287a:
format code  extension  resolution note
hls-336      mp4        384x216     336k , avc1.4D401E, 23.976fps, mp4a.40.2
hls-530      mp4        512x288     530k , avc1.4D401F, 23.976fps, mp4a.40.2
hls-967      mp4        640x360     967k , avc1.4D401F, 23.976fps, mp4a.40.2
hls-1227     mp4        768x432    1227k , avc1.4D401F, 23.976fps, mp4a.40.2
hls-1818     mp4        960x540    1818k , avc1.4D401F, 23.976fps, mp4a.40.2
hls-2653     mp4        1280x720   2653k , avc1.640028, 23.976fps, mp4a.40.2
hls-4431     mp4        1920x1080  4431k , avc1.640028, 23.976fps, mp4a.40.2 (best)
[download] Downloading video 2 of 5
[info] Available formats for 9baf1095-d8ee-4a54-bdf2-2954ff1f2070:
format code  extension  resolution note
hls-317      mp4        384x216     317k , avc1.4D401E, 23.976fps, mp4a.40.2
hls-377      mp4        512x288     377k , avc1.4D401F, 23.976fps, mp4a.40.2
hls-544      mp4        640x360     544k , avc1.4D401F, 23.976fps, mp4a.40.2
hls-644      mp4        768x432     644k , avc1.4D401F, 23.976fps, mp4a.40.2
hls-889      mp4        960x540     889k , avc1.4D401F, 23.976fps, mp4a.40.2
hls-1338     mp4        1280x720   1338k , avc1.640028, 23.976fps, mp4a.40.2
hls-2748     mp4        1920x1080  2748k , avc1.640028, 23.976fps, mp4a.40.2 (best)
[download] Downloading video 3 of 5
[info] Available formats for 40c01eed-7ad5-43ed-8f7e-110bd78bd4ae:
format code  extension  resolution note
hls-311      mp4        384x216     311k , avc1.4D401E, 23.976fps, mp4a.40.2
hls-394      mp4        512x288     394k , avc1.4D401F, 23.976fps, mp4a.40.2
hls-580      mp4        640x360     580k , avc1.4D401F, 23.976fps, mp4a.40.2
hls-686      mp4        768x432     686k , avc1.4D401F, 23.976fps, mp4a.40.2
hls-938      mp4        960x540     938k , avc1.4D401F, 23.976fps, mp4a.40.2
hls-1386     mp4        1280x720   1386k , avc1.640028, 23.976fps, mp4a.40.2
hls-2794     mp4        1920x1080  2794k , avc1.640028, 23.976fps, mp4a.40.2 (best)
[download] Downloading video 4 of 5
[info] Available formats for 2f2050a9-bd3f-4614-a9b7-278474e0e86d:
format code  extension  resolution note
hls-321      mp4        384x216     321k , avc1.4D401E, 23.976fps, mp4a.40.2
hls-428      mp4        512x288     428k , avc1.4D401F, 23.976fps, mp4a.40.2
hls-675      mp4        640x360     675k , avc1.4D401F, 23.976fps, mp4a.40.2
hls-845      mp4        768x432     845k , avc1.4D401F, 23.976fps, mp4a.40.2
hls-1167     mp4        960x540    1167k , avc1.4D401F, 23.976fps, mp4a.40.2
hls-1722     mp4        1280x720   1722k , avc1.640028, 23.976fps, mp4a.40.2
hls-3284     mp4        1920x1080  3284k , avc1.640028, 23.976fps, mp4a.40.2 (best)
[download] Downloading video 5 of 5
[info] Available formats for e8c2d6cc-17ba-47c4-a8af-f47773122113:
format code  extension  resolution note
hls-380      mp4        384x216     380k , avc1.4D401E, 23.976fps, mp4a.40.2
hls-601      mp4        512x288     601k , avc1.4D401F, 23.976fps, mp4a.40.2
hls-1118     mp4        640x360    1118k , avc1.4D401F, 23.976fps, mp4a.40.2
hls-1469     mp4        768x432    1469k , avc1.4D401F, 23.976fps, mp4a.40.2
hls-1970     mp4        960x540    1970k , avc1.4D401F, 23.976fps, mp4a.40.2
hls-2759     mp4        1280x720   2759k , avc1.640028, 23.976fps, mp4a.40.2
hls-4400     mp4        1920x1080  4400k , avc1.640028, 23.976fps, mp4a.40.2 (best)
[download] Finished downloading playlist: Stunning and Brave
$
```

</details>
The part URLs return HTML5-like XML, which the extractor can handle using the `_extract_video_formats()` and `_extract_subtitles()` methods of `MTVServicesInfoExtractor`.

**Comment by xypwn** [comment]
It's been a few days. Any progress on implementing the fix? There are multiple repositories that are affected by this breakage, and it should be relatively easy to fix for someone familiar with the codebase.

> The SP sites are aggressively regional, so that a test show URL https://southpark.there/path is redirected to https://southpark.here/path, where `there` is the domain of the test URL and `here` is the domain that the site thinks you should be using based on what it believes to be your location. Typically the redirected URL will be invalid, giving 404 instead of a geo-block error. API URLs using mtvnservices.com don't behave in this way.

I fail to see how the regional aspect of SP holds significant relevance to this specific issue. I have implemented the exact algorithm I outlined in my initial comment in my own SP downloader project, which seems to work across all supported regions. By the way, you are welcome to examine my code on my GitHub repository [here](https://github.com/xypwn/southpark-downloader-ui). While it is licensed under MIT, I grant you permission to utilize it for yt-dlp if needed.

Please let me know if you have any further questions or if I can be of any further assistance

**Comment by xypwn** [comment]
So it seems SP just re-added `feedWithQueryParams`, meaning yt-dlp's method works again without any source code modification. I tested this in multiple locations and episodes seem to download just fine. Thanks to everyone for their comments.
