### ISSUE TITLE
[Site Request] iq.com

### ISSUE THREAD

**Issue by dausruddin** [yt-dlp/yt-dlp#704]
## Checklist

- [x] I'm reporting a new site support request
- [x] I've verified that I'm running yt-dlp version **2021.08.10**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that none of provided URLs violate any copyrights
- [x] The provided URLs do not contain any DRM to the best of my knowledge
- [x] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

- Single video: https://www.iq.com/play/sword-art-online--alicization-1vce688smhx
- Single video: https://www.iq.com/play/innocent-witness-16a8stvdupw
- Single video: https://www.iq.com/play/【free】a-werewolf-boy-217dear3u90
- Playlist: https://www.iq.com/play/sword-art-online--alicization-1vce688smhx

## Description

iq.com is similar to iqiyi.com, which is supported by yt-dlp. I am not sure if the extracting method will be similar or not.
I am hoping for playlist extractor as well.

Thank you!

**Comment by Ashish0804** [comment]
An update on this:
The parameters to api are confusing af

Here's what i was able to find so far

```
tvid: initialState, play, curVideoInfo,
bid: MISSING,
vid: initialState, play, curVideoInfo,
src: initialProps, pageProps, ptid,
vt: 0,
rs: 1,
uid: 0,
ori: "pcw",
ps: 0,
k_uid: cookies,
pt: 0,
d: 0,
s: "",
lid: "",
slid: 0,
cf: "",
ct: "",
authKey: MISSING,
k_tag: 1,
ost: 0,
ppt: 0,
dfp: cookies,
prio: '%7B%22ff%22%3A%22f4v%22%2C%22code%22%3A2%7D',
k_err_retries: D,
up: '',
su: 2,
applang: 'en_us',
sver: 2,
qd_v:2,
tm:MISSING
qdy:a
qds:0
k_ft1:141287244169348
k_ft4:34359746564
k_ft5:1
bop:'{"version":"10.0","dfp":"a06022a452f986573bbc43839c6a62294ac9f122554d02a44d91523e0713e060ef"}'.encode()
ut:0
vf:MISSING

```
tvid,vid and src are from json in webpage

I can't figure out how these are being generated 
`bid, authKey, tm, vf`

**Comment by dausruddin** [comment]
I got no skill to crack that. Hopefully someone can.

BTW, iq.com and iqiyi.com seems to be related, aren't they the same?

**Comment by dausruddin** [comment]
found this in https://stc.iqiyipic.com/_next/static/chunks/88.0f96b55c4bf5dfc0478b.js

```
M.vmsXhrRequest = o.a[r]({
  url: e,
  params: I,
  memory: !0,
  timeout: 1e4,
  beforeSend: function (e) {
    var t = a.a.parse(e.url).host;
    k.forEach(function (t) {
      (e.url += "&ut=" + t),
        d.a.isArray(I.ut) || (I.ut = []),
        I.ut.push(parseInt(t, 10));
    });
    var n = "iloveiqiyi";
    try {
      var r = e.url.replace(new RegExp("^(http|https)://" + t, "ig"), "");
      if (R) {
        var i = e.url.split("/dash");
        (r = "/dash" + i[1]), (e.url = i[0] + r);
      }
      n = f.a.cmd5x(r);
    } catch (e) {
      T.error("cmd5x: " + (e.message ? e.message : e));
    }
    return (
      (e.url += "&vf=" + n),
      T.log(
        "start vms request, params: k_err_retries = " +
          I.k_err_retries +
          ",useip =" +
          R +
          ", url = " +
          e.url
      ),
      e
    );
  },
  success: function (e, r) {
    M.requestIsAbandoned
      ? T.log("start vms request success callback is abandoned!!!")
      : e && Object.prototype.hasOwnProperty.call(e, "code")
      ? "A00000" === e.code
        ? t(e)
        : (T.log(
            "start vms request success but code error, data->".concat(
              JSON.stringify(e)
            )
          ),
          "A00020" === e.code && e.tm && (A = parseInt(e.tm)),
          n(e))
      : (T.error(
          "start vms request failed, code is null, data->"
            .concat(JSON.stringify(e), ", ")
            .concat(r)
        ),
        n({
          code: v.a.P00002,
        }));
  },
  failure: function (e, t) {
    M.requestIsAbandoned
      ? T.log("start vms request failure callback is abandoned!!!")
      : (T.error(
          "start vms request failed, data = "
            .concat(JSON.stringify(e), ", ")
            .concat(t)
        ),
        n({
          code: v.a.P00001,
        }));
  },
});
```

And found [this blog post](https://translate.google.com/translate?hl=en&sl=zh-CN&u=https://zsaim.github.io/2019/08/23/Iqiyi-cmd5x-Analysis/&prev=search&pto=aue) regarding `cmd5x`

**Comment by llacb47** [comment]
May be helpful?
https://github.com/iawia002/annie/blob/master/extractors/iqiyi/iqiyi.go
https://github.com/soimort/you-get/blob/develop/src/you_get/extractors/iqiyi.py

**Comment by dausruddin** [comment]
This too

https://github.com/SeaHOH/ykdl/tree/8316551b768a728a4b0f81c7e41b6d38a488bced/ykdl/extractors/iqiyi

**Comment by Ashish0804** [comment]
Thanks
I'll look at all of them

**Comment by Ashish0804** [comment]
Okay seems like `cmd5x` is the only function stopping us from writing an extractor for this.
I personally do not know js enough to rewrite it in python therefore am marking this as help needed.

**Comment by Sparh4wk** [comment]
I would love to see this feature as well. Hopefully someone can help you with this one.

**Comment by zackmark29** [comment]
> Okay seems like `cmd5x` is the only function stopping us from writing an extractor for this.
> I personally do not know js enough to rewrite it in python therefore am marking this as help needed.

You don't need to rewrite js to  python. Just use some py package that can run js using node.js or other

**Comment by MinePlayersPE** [comment]
> > Okay seems like `cmd5x` is the only function stopping us from writing an extractor for this.
> > I personally do not know js enough to rewrite it in python therefore am marking this as help needed.
> 
> You don't need to rewrite js to python. Just use some python javascript interpreter

1. There already is a JS interpreter on yt-dlp: https://github.com/yt-dlp/yt-dlp/blob/master/yt_dlp/jsinterp.py but
2. It's really lacking and probably won't work here. There is a PhantomJS wrapper tho so we can probably use that if we have no other choice

**Comment by zackmark29** [comment]
> > > Okay seems like `cmd5x` is the only function stopping us from writing an extractor for this.
> > > I personally do not know js enough to rewrite it in python therefore am marking this as help needed.
> > 
> > 
> > You don't need to rewrite js to python. Just use some python javascript interpreter
> 
> 1. There already is a JS interpreter on yt-dlp: https://github.com/yt-dlp/yt-dlp/blob/master/yt_dlp/jsinterp.py but
> 2. It's really lacking and probably won't work here. There is a PhantomJS wrapper tho so we can probably use that if we have no other choice

Yeah. but I think ydlp don't use any package. So they might rewrite the current interpreter

**Comment by MinePlayersPE** [comment]
Then related issue: https://github.com/yt-dlp/yt-dlp/issues/923

**Comment by Sparh4wk** [comment]
dunno if someone can do something with this, or if it can help, but thanks for it to @zackmark29 

https://github.com/zackmark29/iqiyi-cmd5x-modified

**Comment by zackmark29** [comment]
> An update on this: The parameters to api are confusing af
> 
> Here's what i was able to find so far
> 
> ```
> tvid: initialState, play, curVideoInfo,
> bid: MISSING,
> vid: initialState, play, curVideoInfo,
> src: initialProps, pageProps, ptid,
> vt: 0,
> rs: 1,
> uid: 0,
> ori: "pcw",
> ps: 0,
> k_uid: cookies,
> pt: 0,
> d: 0,
> s: "",
> lid: "",
> slid: 0,
> cf: "",
> ct: "",
> authKey: MISSING,
> k_tag: 1,
> ost: 0,
> ppt: 0,
> dfp: cookies,
> prio: '%7B%22ff%22%3A%22f4v%22%2C%22code%22%3A2%7D',
> k_err_retries: D,
> up: '',
> su: 2,
> applang: 'en_us',
> sver: 2,
> qd_v:2,
> tm:MISSING
> qdy:a
> qds:0
> k_ft1:141287244169348
> k_ft4:34359746564
> k_ft5:1
> bop:'{"version":"10.0","dfp":"a06022a452f986573bbc43839c6a62294ac9f122554d02a44d91523e0713e060ef"}'.encode()
> ut:0
> vf:MISSING
> ```
> 
> tvid,vid and src are from json in webpage
> 
> I can't figure out how these are being generated `bid, authKey, tm, vf`

Just helping a little because I see many users want this to support by ydlp.

For authKey,

```python
def get_auth_key(self, tm, tvid):
    return hashlib.md5(compactBytes(str(tm) + str(tvid), 'utf-8')).hexdigest()
 ```
 
 BID:
 ```python
BID = {
      'uhd'   : 800, #not available already
      'fhd'    : 600, 
      'hd'     : 500, 
      'sd'     : 300, 
      'ld'      : 200, 
      'worst': 100
  }.get(self.quality, 600) 
```

TM: 
```python
int(time.time() * 1000)
```

VF:
https://github.com/zackmark29/iqiyi-cmd5x-modified
or 
https://zsaim.github.io/2019/08/23/Iqiyi-cmd5x-Analysis/

Hope that can help a little :)

**Comment by Ashish0804** [comment]
@zackmark29 Thanks for finding out that info mate. Unfortunately I'm a little to busy to work on new extractors for now so feel free to make a PR if u want to.

**Comment by zackmark29** [comment]
> @zackmark29 Thanks for finding out that info mate. Unfortunately I'm a little to busy to work on new extractors for now so feel free to make a PR if u want to.

Oh that's my problem also. I'm busy with my work. That's why I just give some important codes

**Comment by dirkf** [comment]
https://github.com/ytdl-org/youtube-dl/issues/30500

Shouldn't the same extraction as IqiyiIE work after getting `vid`, `tvid` from the page, since those are the only parameters used there?

**Comment by MinePlayersPE** [comment]
https://gist.github.com/MinePlayersPE/589edb2e424f272bf82e3eaa4beb6130 made an extractor plugin for this, tho it requires phantomJS to run the `cmd5x` signer
i'll probably polish it up and make a proper PR soon™

**Comment by MinePlayersPE** [comment]
@dirkf I have no clue what the proper params are for `cache-m.iq.com`'s raw_data endpoint, since using the same params as iqiyi.com returns `var tvInfoJs=invalid service url: /rule/tmts/...`

**Comment by jazz1611** [comment]
hello, i'm get this error

```
[iq.com] 1fj6iypksgg: Downloading webpage
[iq.com] 1fj6iypksgg: Downloading webpack JS
ERROR: 'dict_keys' object is not reversible
```

**Comment by MinePlayersPE** [comment]
@jazz1611 Fixed in https://github.com/yt-dlp/yt-dlp/commit/ed40877833d401808a29a7998a28c52871cc2e3f

**Comment by jazz1611** [comment]
> @jazz1611 Fixed in [ed40877](https://github.com/yt-dlp/yt-dlp/commit/ed40877833d401808a29a7998a28c52871cc2e3f)

hello, after export "Netscape HTTP Cookie File" to "cookies.txt" and try it. we get this error

```
[iq.com] 1e51dyjjtr0: Downloading webpage
[iq.com] 1e51dyjjtr0: Executing signature code
[iq.com] 1e51dyjjtr0: Downloading initial video format info
ERROR: [iq.com] 1e51dyjjtr0: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.

Latest version: 2022.01.21, Current version: 2022.01.21
yt-dlp is up to date (2022.01.21)
```

**Comment by Sparh4wk** [comment]
> > @jazz1611 Fixed in [ed40877](https://github.com/yt-dlp/yt-dlp/commit/ed40877833d401808a29a7998a28c52871cc2e3f)
> 
> hello, after export "Netscape HTTP Cookie File" to "cookies.txt" and try it. we get this error
> 
> ```
> [iq.com] 1e51dyjjtr0: Downloading webpage
> [iq.com] 1e51dyjjtr0: Executing signature code
> [iq.com] 1e51dyjjtr0: Downloading initial video format info
> ERROR: [iq.com] 1e51dyjjtr0: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
> 
> Latest version: 2022.01.21, Current version: 2022.01.21
> yt-dlp is up to date (2022.01.21)
> ```

VIP function was added 2 days ago and new version wasnt released. so if u want to use it before new release of yt-dlp u need to build your version

**Comment by jazz1611** [comment]
> > > @jazz1611 Fixed in [ed40877](https://github.com/yt-dlp/yt-dlp/commit/ed40877833d401808a29a7998a28c52871cc2e3f)
> > 
> > 
> > hello, after export "Netscape HTTP Cookie File" to "cookies.txt" and try it. we get this error
> > ```
> > [iq.com] 1e51dyjjtr0: Downloading webpage
> > [iq.com] 1e51dyjjtr0: Executing signature code
> > [iq.com] 1e51dyjjtr0: Downloading initial video format info
> > ERROR: [iq.com] 1e51dyjjtr0: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
> > 
> > Latest version: 2022.01.21, Current version: 2022.01.21
> > yt-dlp is up to date (2022.01.21)
> > ```
> 
> VIP function was added 2 days ago and new version wasnt released. so if u want to use it before new release of yt-dlp u need to build your version
> 
> And cant reproduce it, cause ID 1e51dyjjtr0 is not available in my region :(

hello, i use this command for update latest version
`python3 -m pip install -U https://github.com/yt-dlp/yt-dlp/archive/master.zip`

without cookies parameter
```
yt-dlp -F "https://www.iq.com/play/attack-on-titan-final-season-episode-1-23e9oqaqyd4?lang=en_us"
[iq.com] 23e9oqaqyd4: Downloading webpage
[iq.com] 23e9oqaqyd4: Executing signature code
[iq.com] 23e9oqaqyd4: Downloading initial video format info
ERROR: [iq.com] 23e9oqaqyd4: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
```

**Comment by Sparh4wk** [comment]
> > > > @jazz1611 Fixed in [ed40877](https://github.com/yt-dlp/yt-dlp/commit/ed40877833d401808a29a7998a28c52871cc2e3f)
> > > 
> > > 
> > > hello, after export "Netscape HTTP Cookie File" to "cookies.txt" and try it. we get this error
> > > ```
> > > [iq.com] 1e51dyjjtr0: Downloading webpage
> > > [iq.com] 1e51dyjjtr0: Executing signature code
> > > [iq.com] 1e51dyjjtr0: Downloading initial video format info
> > > ERROR: [iq.com] 1e51dyjjtr0: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
> > > 
> > > Latest version: 2022.01.21, Current version: 2022.01.21
> > > yt-dlp is up to date (2022.01.21)
> > > ```
> > 
> > 
> > VIP function was added 2 days ago and new version wasnt released. so if u want to use it before new release of yt-dlp u need to build your version
> > And cant reproduce it, cause ID 1e51dyjjtr0 is not available in my region :(
> 
> hello, i use this command for update latest version `python3 -m pip install -U https://github.com/yt-dlp/yt-dlp/archive/master.zip`
> 
> without cookies parameter
> 
> ```
> yt-dlp -F "https://www.iq.com/play/attack-on-titan-final-season-episode-1-23e9oqaqyd4?lang=en_us"
> [iq.com] 23e9oqaqyd4: Downloading webpage
> [iq.com] 23e9oqaqyd4: Executing signature code
> [iq.com] 23e9oqaqyd4: Downloading initial video format info
> ERROR: [iq.com] 23e9oqaqyd4: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
> ```

its the same for me.. but its not available in my region

![image](https://user-images.githubusercontent.com/7014826/151204253-fe2caad8-cd8f-4383-8afc-7c522fdbf4a7.png)

**Comment by jazz1611** [comment]
@Sparh4wk can you share the id video you can watch in your region? then i can easy more test

**Comment by Sparh4wk** [comment]
> @Sparh4wk can you share the id video you can watch in your region? then i can easy more test

https://www.iq.com/play/bad-and-crazy-episode-1-1fj6iypksgg?lang=en_us

**Comment by jazz1611** [comment]
@Sparh4wk it working now. thank you. look like some video restricted in US (sandbox VPS).

**Comment by jazz1611** [comment]
@Sparh4wk hello, it not work again. tried both cookie and without cookie. it always show error
`ERROR: [iq.com] 1e51dyjjtr0: No video formats found!;`

**Comment by Sparh4wk** [comment]
> @Sparh4wk hello, it not work again. tried both cookie and without cookie. it always show error. maybe they have limit request? `ERROR: [iq.com] 1e51dyjjtr0: No video formats found!;`

ye same problem with region lock 

![image](https://user-images.githubusercontent.com/7014826/151211997-f0d43bdc-21c9-487c-8938-6786104177a3.png)

**Comment by jazz1611** [comment]
> > @Sparh4wk hello, it not work again. tried both cookie and without cookie. it always show error. maybe they have limit request? `ERROR: [iq.com] 1e51dyjjtr0: No video formats found!;`
> 
> ye same problem with region lock
> 
> ![image](https://user-images.githubusercontent.com/7014826/151211997-f0d43bdc-21c9-487c-8938-6786104177a3.png)

what should we do now? try with proxy/socks to prevent block IP ?

**Comment by jazz1611** [comment]
@MinePlayersPE hello, if i use command `--downloader ffmpeg` instead of `-N (4 or 8) (prevent block too many request by iq.com)` and get this error 
in Windows 
```
[download] Destination: a.mp4
ERROR: unable to download video data: [WinError 206] The filename or extension is too long
```
in Linux (CentOS7)
```
[download] Destination: a.mp4
ERROR: unable to download video data: [Errno 7] Argument list too long: 'ffmpeg'
```

**Comment by pukkandan** [comment]
Why are you using `--downloader ffmpeg`? If you don't want multithreaded download, just don't use `-N`. This download is not supported through ffmpeg

**Comment by jazz1611** [comment]
> Why are you using `--downloader ffmpeg`? If you don't want multithreaded download, just don't use `-N`. This download is not supported through ffmpeg

use ffmpeg for better. with -N should use less 4. Also i found the problem when url have ?lang=xxxx with cookie or without cookie. if input url without ?lang=xxxx, it work perfectly.

**Comment by jazz1611** [comment]
hello, there is new bug. look like phantomjs work not stable!
```

[root@we ~]# youtube-dl -F "https://www.iq.com/play/the-sweetest-secret-episode-23-1b0npva9yxw" --cookies "cookies.txt"
[iq.com] 1b0npva9yxw: Downloading webpage
[iq.com] 1b0npva9yxw: Downloading VIP data
[iq.com] 1b0npva9yxw: Executing signature code
[iq.com] 1b0npva9yxw: Downloading initial video format info
[iq.com] 1b0npva9yxw: Downloading format data for 240P
[iq.com] 1b0npva9yxw: Downloading format data for 1080P
[iq.com] 1b0npva9yxw: Downloading format data for 720P
[iq.com] 1b0npva9yxw: Downloading format data for 360P
[iq.com] 1b0npva9yxw: Downloading format data for 480P
[info] Available formats for 1b0npva9yxw:
ID  EXT RESOLUTION │ PROTO  │ VCODEC  ACODEC  MORE INFO
────────────────────────────────────────────────────────
                                                        100 mp4 384x216    │ m3u8_n │ unknown unknown 240P
200 mp4 640x360    │ m3u8_n │ unknown unknown 360P
300 mp4 896x504    │ m3u8_n │ unknown unknown 480P
500 mp4 1280x720   │ m3u8_n │ unknown unknown 720P
600 mp4 1920x1080  │ m3u8_n │ unknown unknown 1080P
[root@we ~]# youtube-dl -f 200,500,600 "https://www.iq.com/play/the-sweetest-secret-episode-23-1b0npva9yxw" --cookies "cookies.txt"
[iq.com] 1b0npva9yxw: Downloading webpage
[iq.com] 1b0npva9yxw: Downloading VIP data
[iq.com] 1b0npva9yxw: Executing signature code
[iq.com] 1b0npva9yxw: Downloading initial video format info
ERROR: [iq.com] 1b0npva9yxw: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
[root@we ~]#
```

**Comment by someziggyman** [comment]
@pukkandan Hey guys! Have been testing out iq.com extractor on MacOS (M1 architecture) and could not make phantomjs work properly. It just crashes all the time... Downloaded its latest version from 2016 (the project seems to be dead): 
https://phantomjs.org/download.html

Here's my log:
Command-line config: ['-v', '-J', 'https://www.iq.com/play/bad-and-crazy-episode-1-1fj6iypksgg?lang=en_us']
Encodings: locale US-ASCII, fs utf-8, out ascii (No ANSI), err ascii (No ANSI), pref US-ASCII
yt-dlp version 2022.02.03 [28469edd7] (mac_dir)
 Python version 3.10.2 (CPython 64bit) - macOS-11.6.3-arm64-64bit
 exe versions: phantomjs 2.1.1
 Optional libraries: sqlite
Proxy map: {}
[iq.com] Extracting URL: https://www.iq.com/play/bad-and-crazy-episode-1-1fj6iypksgg?lang=en_us
[iq.com] 1fj6iypksgg: Downloading webpage
 Loading iq.player_js from cache
Loading iq.player_js from cache
[iq.com] 1fj6iypksgg: Executing signature code
ERROR: [iq.com] 1fj6iypksgg: Executing JS failed
:1   0x10521bc59
2   0x1050207c5
3   0x1050202eb
4   0x105140e82
5   0x7fff2061b1e1
6   0x7fff206615c6
7   0x7fff2061b18f
8   0x10412c259
9   0x1040fe8c3
10  0x1040e8bc2
11  0x1040605df
12  0x104062059
13  0x10408190c
14  0x10405fe34
15  0x3
PhantomJS has crashed. Please read the bug reporting guide at
<http://phantomjs.org/bug-reporting.html> and file a bug report.
; please report this issue on  https://github.com/yt-dlp/yt-dlp , filling out the "Broken site" issue template properly. Confirm you are on the latest version using -U; please report this issue on  https://github.com/yt-dlp/yt-dlp , filling out the "Broken site" issue template properly. Confirm you are on the latest version using -U
  File "yt_dlp/extractor/common.py", line 612, in extract
  File "yt_dlp/extractor/iqiyi.py", line 601, in _real_extract
  File "yt_dlp/extractor/openload.py", line 231, in get


 https://www.iq.com/play/bad-and-crazy-episode-1-1fj6iypksgg?lang=en_us
