### ISSUE TITLE
Specific bad YouTube URL redirect to YT homepage and dl all recommended videos

### ISSUE THREAD

**Issue by emilejanssens** [yt-dlp/yt-dlp#7041]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

As part of a testing project for our university, we found by fuzzing test some youtube URL type that automatically redirects to the homepage. yt-dlp follows this redirection and downloads all recommended videos. 

The problem occurs when you replace/delete the 'v=' characters after the 'watch?' with any other character.
For example : https://www.youtube.com/watch?w=7aOpiAP9El0

Potential solution:
Shouldn't we detect this character error in the URL passed to yt-dlp and not follow the YouTube redirection in this kind of case?

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
.\yt-dlp.exe -vU https://www.youtube.com/watch?w=7aOpiAP9El0 -P .\trash\
[debug] Command-line config: ['-vU', 'https://www.youtube.com/watch?w=7aOpiAP9El0', '-P', '.\\trash\\']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8 
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (win_exe) 
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021) 
[debug] exe versions: none 
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {} 
[debug] Loaded 1786 extractors 
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest 
Available version: stable@2023.03.04, Current version: stable@2023.03.04 
Current Build Hash: 5590c57bd0433ed239a2deaaf92e2ad6f37fe50f53664c821575cafe106a9421 
yt-dlp is up to date (stable@2023.03.04) 
[generic] Extracting URL: https://www.youtube.com/watch?w=7aOpiAP9El0 
[generic] watch?w=7aOpiAP9El0: Downloading webpage 
[redirect] Following redirect to https://www.youtube.com/ 
[youtube:recommended] Extracting URL: https://www.youtube.com/ 
[youtube:tab] Extracting URL: https://www.youtube.com/feed/recommended
[youtube:tab] recommended: Downloading webpage 
[download] Downloading playlist: recommended 
[youtube:tab] recommended page 1: Downloading API JSON 
[youtube:tab] recommended page 2: Downloading API JSON 
[youtube:tab] recommended page 3: Downloading API JSON 
[youtube:tab] recommended page 4: Downloading API JSON 
[youtube:tab] recommended page 5: Downloading API JSON 
[youtube:tab] recommended page 6: Downloading API JSON 
[youtube:tab] recommended page 7: Downloading API JSON 
[youtube:tab] recommended page 8: Downloading API JSON 
[youtube:tab] recommended page 9: Downloading API JSON 
[youtube:tab] recommended page 10: Downloading API JSON 
[youtube:tab] recommended page 11: Downloading API JSON 
[youtube:tab] recommended page 12: Downloading API JSON 
[youtube:tab] Playlist recommended: Downloading 302 items of 302 
[download] Downloading item 1 of 302 
[youtube] Extracting URL: https://www.youtube.com/watch?v=j-nS_8ekjVE
[youtube] j-nS_8ekjVE: Downloading webpage
[youtube] j-nS_8ekjVE: Downloading android player API JSON 
[debug] [youtube] Extracting signature function js_cfa9e7cb_107 
[youtube] j-nS_8ekjVE: Downloading player cfa9e7cb 

ERROR: Interrupted by user
```

**Comment by pukkandan** [comment]
No, this is clearly user error as the passed URL is not valid. We cannot hope to detect all such cases.
