### ISSUE TITLE
How do I download new videos from a playlist?

### ISSUE THREAD

**Issue by JacobDreiling** [yt-dlp/yt-dlp#7049]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

If I previously downloaded a playlist, then added some more videos to it, how do I download only those videos? The number of new videos is: new length - old length. If I saved the old length of the playlist as `old_length`, I figured I could use `yt-dlp $favorites --playlist-end "%(playlist_count-$old_length)d"` where `favorites` is the playlist. What is the correct syntax for this?

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp -vU $favorites --playlist-end "%(playlist_count-286)d"

Usage: yt-dlp [OPTIONS] URL [URL...]

yt-dlp: error: option --playlist-end: invalid integer value: '%(playlist_count-286)d'
```

**Comment by gamer191** [comment]
I don't know the answer to your question, or if it's even possible, but may I suggest using `--download-archive` and `--break-on-existing`?

**Comment by JacobDreiling** [comment]
Yes that works much better. Forgive me, I knew about the archive option but not `--break-on-existing`. Thank you!

Note to self: if new videos are added to the **end** of a playlist, you can use `--playlist-start $old_length`.
