### ISSUE TITLE
Can you release a version without the --onefile pyinstaller argument? [Question]

### ISSUE THREAD

**Issue by ahm750** [yt-dlp/yt-dlp#705]
Hi,

When compiling the binary for Windows to be released, can you also include a version for x64 and x32 where the pyinstaller --onefile argument is not used? This will be useful for people, including myself, who don't want the binary to spawn two processes with each execution.

I'd really appreciate it.

**Comment by pukkandan** [comment]
Related #661

Without `--onefile`, you get a directory full of files, all of which is needed for it to run

```sh
15-08-21  19:30           782,172 base_library.zip
15-08-21  19:30    <DIR>          Crypto
31-07-21  04:13         1,173,184 libcrypto-1_1.dll
31-07-21  04:13            24,088 libffi-7.dll
31-07-21  04:13           202,432 libssl-1_1.dll
31-07-21  04:12            83,688 pyexpat.pyd
31-07-21  04:11         1,514,728 python39.dll
31-07-21  04:12            22,760 select.pyd
31-07-21  04:13           643,304 sqlite3.dll
31-07-21  04:12           292,584 unicodedata.pyd
31-07-21  04:11            97,160 VCRUNTIME140.dll
15-08-21  19:30    <DIR>          websockets
15-08-21  19:30         5,032,687 yt-dlp.exe
15-08-21  19:30             1,494 yt-dlp.exe.manifest
31-07-21  04:12            33,512 _asyncio.pyd
31-07-21  04:13            47,848 _bz2.pyd
31-07-21  04:13            58,088 _ctypes.pyd
31-07-21  04:12           111,336 _decimal.pyd
31-07-21  04:13            78,568 _elementtree.pyd
31-07-21  04:12            33,512 _hashlib.pyd
31-07-21  04:12            86,760 _lzma.pyd
31-07-21  04:12            23,272 _multiprocessing.pyd
31-07-21  04:12            28,904 _overlapped.pyd
31-07-21  04:12            22,760 _queue.pyd
31-07-21  04:12            41,192 _socket.pyd
31-07-21  04:13            44,264 _sqlite3.pyd
31-07-21  04:12            59,112 _ssl.pyd
31-07-21  04:13            20,200 _uuid.pyd
```

Needing this is such a niche use-case and officially supporting it (with updates and everything) is a pain, that I am not really willing to work on it.

If this is in fact what you want, I suggest that you build a copy  yourself. You only need to remove the `--onefile` option, from pyinst.py and then run it. You may also want to disable the auto-updater

**Comment by pukkandan** [comment]
Due to more people demanding it, #880 will add a zip with `--onedir` version. Here's a test release: https://github.com/pukkandan/yt-dlp-dev/releases/tag/2021.09.19.2
