### ISSUE TITLE
download link archiver

### ISSUE THREAD

**Issue by LovelyBloom** [yt-dlp/yt-dlp#7056]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

this feature will tremendously help people with various backgrounds and needs, for example I have to make my downloads through a VPN because YouTube is blocked and this will help me a lot. and that's just one example.

we add a **batch URL grab** to yt-dlp like: `yt-dlp -grab https://www.youtube.com/@freecodecamp -grab-file C:\links.txt`
and just in the same manner that it records all downloaded videos in a txt file using download-archive, it will make a complete list of all the videos in the txt file and we'll be able to use it using the -r arg functionality.

we can also add the `yt-dlp -grab https://www.youtube.com/@freecodecamp -grab-file C:\links.txt -grab-update`
to refresh all the files.

this will help a lot of people especially with **limited functionality** to the internet.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU']
[debug] User config "C:\Users\father\AppData\Roaming\yt-dlp\config": ['--ignore-errors', '--no-abort-on-error', '--no-live-from-start', '--force-ipv4', '--file-access-retries', 'infinite', '--xattr-set-filesize', '--downloader', 'aria2c', '--downloader-args', 'aria2c:-c -j 6 -x 6 -s 6 -k 1M', '--continue', '--write-description', '--write-info-json', '--write-playlist-metafiles', '--write-thumbnail', '--progress', '-f', 'bestvideo[ext=mp4][width<2000][height<=1200]+bestaudio[ext=m4a]/bestvideo[ext=webm][width<2000][height<=1200]+bestaudio[ext=webm]/bestvideo[width<2000][height<=1200]+bestaudio/best[width<2000][height<=1200]/best', '--audio-multistreams', '--write-subs', '--remux-video', 'mkv', '--embed-subs', '--embed-thumbnail', '--embed-metadata', '--embed-chapters', '--embed-info-json', '--xattrs', '-o', 'G:/yt_videos/%(uploader)s/%(playlist)s/%(title)s.%(ext)s']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 2023-05-11-git-ceb050427c-full_build-www.gyan.dev (setts), ffprobe 2023-05-11-git-ceb050427c-full_build-www.gyan.dev, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
Current Build Hash: 5590c57bd0433ed239a2deaaf92e2ad6f37fe50f53664c821575cafe106a9421
yt-dlp is up to date (stable@2023.03.04)
```

**Comment by bashonly** [comment]
> we add a batch URL grab to yt-dlp like: `yt-dlp -grab https://www.youtube.com/@freecodecamp -grab-file C:\links.txt`

Can't this already be done with `yt-dlp "https://www.youtube.com/@freecodecamp" --flat-playlist --print-to-file webpage_url "C:\links.txt"` ? Or am I misunderstanding what you want?

> we'll be able to use it using the -r arg functionality.

Do you mean `--rate-limit` ? Why is a list of URLs needed for this?

**Comment by LovelyBloom** [comment]
okay first my apologies for my lack of knowledge over those command lines
but the issue isn't completely resolved. it rewrites already written links again and again.
for example the freecodecamp channel updates its videos regularly. to maintain this would be extremely cumbersome.
wouldn't it better if it wrote it new links only either at the end of it file (or beginning) or in a new file, if the older one was passed as argument?

PS: about the --rate-limit. I mean the -a --batch-file argument for using a file as input.

**Comment by pukkandan** [comment]
Perhaps what you want is:

    yt-dlp --flat-playlist --download-archive archive.txt --break-on-existing --lazy-playlist --print-to-file webpage_url links.txt "CHANNEL URL"

**Comment by nom4d72** [comment]
i have a problem: before using this method my downloads went into these directories:
```
G:\yt_videos\freeCodeCamp.org\freeCodeCamp.org
G:\yt_videos\freeCodeCamp.org\freeCodeCamp.org\freeCodeCamp.org - Live
G:\yt_videos\freeCodeCamp.org\freeCodeCamp.org - Shorts
```
but now everything goes into:
`G:\yt_videos\freeCodeCamp.org\NA`

if I remove --flat-playlist argument, will that solve the issue?

**Comment by pukkandan** [comment]
No, that is because you are writing the links and then downloading them later (which is what you asked for), therefore losing playlist information.

Maybe what you really want is just `--write/load-info-json` with `--no-clean-info`

**Comment by shimiaoyerin** [comment]
`yt-dlp --playlist-items 1:200 --no-warnings --lazy-playlist --flat-playlist --print "/watch?v=%(id)s" --print "/shorts/%(id)s" "https://www.youtube.com/playlist?list=PLj1kwHPhQ6Tan6gUKk2RvwA5LU_oDPUkv" *>&1 | ForEach-Object {if($_ -notin (Get-Content links.txt)){Add-Content links.txt $_ -Encoding utf8; $_}}`
Maybe you need such a feature? This is what I wrote in powershell, compare the list of videos in the channel, if not then join
