### ISSUE TITLE
Low video quality downloaded by default on Pokémon TV

### ISSUE THREAD

**Issue by GeorgeHamp** [yt-dlp/yt-dlp#7059]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [x] I'm reporting that a **supported** site is broken
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Germany

### Provide a description that is worded well enough to be understood

It seems that for Pokémon TV, despite being "bestvideo*+bestaudio" being the default, yt-dlp uses a medium quality option (here "BANDWIDTH=736000" instead of the "BANDWIDTH=1725000" ), resulting in lower video quality than one would expect.

Issue could be related to the fact that Pokémon TV offers higher framerates for those low bitrate variants (which is kinda useless, given the way lower quality)

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp.exe -vU https://watch.pokemon.com/de-de/#/player?id=ba665eef61234145a04ad5d8686cd710&channelId=pokemon-meister-reisen-die-serie&cameFromHome=false
[debug] Command-line config: ['-vU', 'https://watch.pokemon.com/de-de/#/player?id=ba665eef61234145a04ad5d8686cd710']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-86911-gb664d1f, ffprobe N-86911-gb664d1f, phantomjs 2.1.1, rtmpdump 2.3
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
Current Build Hash: 5590c57bd0433ed239a2deaaf92e2ad6f37fe50f53664c821575cafe106a9421
yt-dlp is up to date (stable@2023.03.04)
[PokemonWatch] Extracting URL: https://watch.pokemon.com/de-de/#/player?id=ba665eef61234145a04ad5d8686cd710
[PokemonWatch] ba665eef61234145a04ad5d8686cd710: Downloading webpage
[PokemonWatch] ba665eef61234145a04ad5d8686cd710: Downloading JSON metadata
[limelight] Extracting URL: limelight:media:ba665eef61234145a04ad5d8686cd710
[limelight] ba665eef61234145a04ad5d8686cd710: Downloading PlaylistService getPlaylistByMediaId JSON
[limelight] ba665eef61234145a04ad5d8686cd710: Downloading PlaylistService getMobilePlaylistByMediaId JSON
[limelight] ba665eef61234145a04ad5d8686cd710: Checking http-832 URL
[limelight] ba665eef61234145a04ad5d8686cd710: Checking http URL
[limelight] ba665eef61234145a04ad5d8686cd710: Checking http URL
[limelight] ba665eef61234145a04ad5d8686cd710: Checking http-472 URL
[limelight] ba665eef61234145a04ad5d8686cd710: Checking http-1328 URL
[limelight] ba665eef61234145a04ad5d8686cd710: Checking http-128 URL
[limelight] ba665eef61234145a04ad5d8686cd710: Checking http-322 URL
[limelight] ba665eef61234145a04ad5d8686cd710: Checking http-1072 URL
[limelight] ba665eef61234145a04ad5d8686cd710: Checking http-1600 URL
[limelight] ba665eef61234145a04ad5d8686cd710: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] ba665eef61234145a04ad5d8686cd710: Downloading 1 format(s): HttpLiveStreaming-736
```

**Comment by gamer191** [comment]
> BANDWIDTH=1725000

What makes you say that a format with `BANDWIDTH=1725000` is available?
