### ISSUE TITLE
Upgrade downloading speed

### ISSUE THREAD

**Issue by phanluchoaofficial20** [yt-dlp/yt-dlp#706]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running yt-dlp version **2021.08.10**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description

WRITE DESCRIPTION HERE
Hi,

Can you update your tool can download faster ? When I use your tool to download videos, I see that the speed so slow although my network is very fast! Can you improve your download module ?

I use project "yt-dlc" download so fast but your project i think is so slow!

![Untitled](https://user-images.githubusercontent.com/86090065/129482236-6a1975a0-7f6f-44cc-8664-0c6cd766689c.png)

Thanks!

**Comment by MinePlayersPE** [comment]
Please properly write the description?

**Comment by phanluchoaofficial20** [comment]
> Please properly write the description?

I have updated!

**Comment by phanluchoaofficial20** [comment]
@MinePlayersPE I use my own tool i have code to download videos by using your tool yt-dlp but i see it download very slow, although my network is over 300mbps but your tool cannot download in max speed!

Thanks!

**Comment by Ashish0804** [comment]
use aria2 as external downloader or download multiple fragments using `-N`

**Comment by pukkandan** [comment]
> I use project "yt-dlc" download so fast but your project i think is so slow!

Don't make baseless claims, provide verbose outputs of both if you do in fact observe this

Or, if you are just asking how to speed up the downloads, look at the `--concurrent-fragments` and `--downloader aria2c` options. If neither of these help, the server may be throttling you and there is nothing we can do to help

**Comment by phanluchoaofficial20** [comment]
> sử dụng aria2 làm trình tải xuống bên ngoài hoặc tải xuống nhiều đoạn bằng cách sử dụng `-N`

![Untitled](https://user-images.githubusercontent.com/86090065/129482545-e7dea757-92e2-43ca-ade3-efa0cc0b714c.png)

Like this ?
