### ISSUE TITLE
Download issue mtv.it 

### ISSUE THREAD

**Issue by AnimatorTao** [yt-dlp/yt-dlp#7066]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that a **supported** site is broken
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Italy

### Provide a description that is worded well enough to be understood

Got an error when trying to download from mtv.it despite being able to play it in browser

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.mtv.it/episodi/2oeblw/il-testimone-la-vocazione-stagione-1-e-2']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19044-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 2022-11-23-git-c8e9cc8d20-full_build-www.gyan.dev (setts), ffprobe 2022-11-23-git-c8e9cc8d20-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
Current Build Hash: 5590c57bd0433ed239a2deaaf92e2ad6f37fe50f53664c821575cafe106a9421
yt-dlp is up to date (stable@2023.03.04)
[debug] Using fake IP 79.59.40.109 (IT) as X-Forwarded-For
[mtv.it] Extracting URL: https://www.mtv.it/episodi/2oeblw/il-testimone-la-vocazione-stagione-1-e-2
[mtv.it] il-testimone-la-vocazione-stagione-1-e-2: Downloading webpage
[mtv.it] 59495aef-927b-11ed-ad8e-0e40cf2fc285: Downloading info
[mtv.it] 59e991ea-927b-11ed-ad8e-0e40cf2fc285: Extracting information
[mtv.it] 59e991ea-927b-11ed-ad8e-0e40cf2fc285: Downloading video urls
ERROR: [mtv.it] 2oeblw: mtv.it returned error: not_found -
      Sorry, this video is not found or no longer available due to date or rights restrictions.

  File "yt_dlp\extractor\common.py", line 694, in extract
  File "yt_dlp\extractor\mtv.py", line 323, in _real_extract
  File "yt_dlp\extractor\mtv.py", line 227, in _get_videos_info
  File "yt_dlp\extractor\mtv.py", line 239, in _get_videos_info_from_url
  File "yt_dlp\extractor\mtv.py", line 150, in _get_video_info
```

**Comment by bashonly** [comment]
Duplicate of #5249
