### ISSUE TITLE
[generic] fails to extract title

### ISSUE THREAD

**Issue by barsnick** [yt-dlp/yt-dlp#7067]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that a **supported** site is broken
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

World

### Provide a description that is worded well enough to be understood

While the generic extractor fetches the audio file from "In the Studio" podcacsts just fine, it fails to extract the title. Looking at the dumped web page, the title is as easy as it gets: Within a `<title>` / `</title>` tag.

I haven't managed to figure out why the given title regex search doesn't match this.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--get-title', 'https://www.inthestudio.net/online-on-demand/rolling-stones-some-girls/']
[debug] User config "/home/barsnick/.config/yt-dlp/config": ['-o', '%(title)s [%(extractor)s %(id)s].%(ext)s']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (source)
[debug] Lazy loading extractors is disabled
[debug] Git HEAD: 21b9413cf
[debug] Python 3.11.3 (CPython x86_64 64bit) - Linux-6.2.14-300.fc38.x86_64-x86_64-with-glibc2.37 (OpenSSL 3.0.8 7 Feb 2023, glibc 2.37)
[debug] exe versions: ffmpeg 6.0 (setts), ffprobe 6.0, phantomjs 1.9.8
[debug] Optional libraries: Cryptodome-3.17.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1813 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
yt-dlp is up to date (stable@2023.03.04)
[generic] Extracting URL: https://www.inthestudio.net/online-on-demand/rolling-stones-some-girls/
[generic] rolling-stones-some-girls: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] rolling-stones-some-girls: Extracting information
[debug] Looking for embeds
[debug] Identified a JW Player data
WARNING: Extractor failed to obtain "title". Creating a generic title instead
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] rolling-stones-some-girls: Downloading 1 format(s): 0
generic video #rolling-stones-some-girls
```

**Comment by dirkf** [comment]
yt-dlp: `generic video #rolling-stones-some-girls`
yt-dl: `Rolling Stones- Some Girls 45th- Mick Jagger, Keith Richards, Ron Wood` (ie, the page title).

Arguably yt-dlp is misleading since it's an audio (mp3) download.

**Comment by barsnick** [comment]
After git bisect, I figured out:

Regression in ade1fa70cbaaaadaa4772e5f0564870cea3167ef

**Comment by barsnick** [comment]
> Arguably yt-dlp is misleading since it's an audio (mp3) download.

Indeed, but that's purely cosmetic, and I couldn't care less. ;-)
`s/video/media/`

**Comment by dirkf** [comment]
It looks like this change to the generic extractor around l.2834->2840 means that the page title isn't being passed through to the JWPlayer extraction:
```diff
                     self.report_detected('JW Player data')
-                    return merge_dicts(info, info_dict)
+                    return [info]
             except ExtractorError:
```
