### ISSUE TITLE
YouTube share links doesn't work: unsupported URL

### ISSUE THREAD

**Issue by bkdwt** [yt-dlp/yt-dlp#7068]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

When I try to download any video from Youtube using the link generated from the YouTube app to share, I receive the "unsupported url" error.

What I do to get around this problem? I put the link on Chrome, select the option to "view in desktop mode", copy the link (now changes from youtu.be/xxxx for youtube.com/xxxx) and put on termux again. Only works on this manner.

I using yt-dlp + termux on Android 13.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
$ yt-dlp https://youtu.be/0qt4BzlGap -vU           [debug] Command-line config: ['https://youtu.be/0qt4BzlGap', '-vU']                                       [debug] Encodings: locale utf-8, fs utf-8, pref utf-8, out utf-8, error utf-8, screen utf-8               [debug] yt-dlp version stable@2023.03.04 [392389b7d]
[debug] Lazy loading extractors is disabled          [debug] Python 3.11.3 (CPython aarch64 64bit) - Linux-5.4.147-25489110-abG996BXXS6DWB2-aarch64-with-libc (OpenSSL 3.1.0 14 Mar 2023, libc)                     [debug] exe versions: ffmpeg 6.0 (setts), ffprobe 6.0
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.2                                [debug] Proxy map: {}
[debug] Loaded 1810 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest                 Available version: stable@2023.03.04, Current version: stable@2023.03.04
yt-dlp is up to date (stable@2023.03.04)
[generic] Extracting URL: https://youtu.be/0qt4BzlGap
[generic] 0qt4BzlGap: Downloading webpage            [redirect] Following redirect to https://www.youtube.com/watch?v=0qt4BzlGap&feature=youtu.be
[generic] Extracting URL: https://www.youtube.com/watch?v=0qt4BzlGap&feature=youtu.be
[generic] watch?v=0qt4BzlGap&feature=youtu: Downloading webpage                                           WARNING: [generic] Falling back on generic information extractor
[generic] watch?v=0qt4BzlGap&feature=youtu: Extracting information                                        [debug] Looking for embeds
ERROR: Unsupported URL: https://www.youtube.com/watch?v=0qt4BzlGap&feature=youtu.be
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1532, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1608, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 694, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/yt_dlp/extractor/generic.py", line 2568, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.youtube.com/watch?v=0qt4BzlGap&feature=youtu.be
```

**Comment by coletdjnz** [comment]
that URL does not point to any video (invalid video ID - too short)

**Comment by bkdwt** [comment]
> that URL does not point to any video (invalid video ID - it's missing a character at the end)

Try now: https://youtu.be/0qt4BzlGapA

**Comment by bashonly** [comment]
```
$ yt-dlp -F "https://youtu.be/0qt4BzlGapA"
[youtube] Extracting URL: https://youtu.be/0qt4BzlGapA
[youtube] 0qt4BzlGapA: Downloading webpage
[youtube] 0qt4BzlGapA: Downloading android player API JSON
[info] Available formats for 0qt4BzlGapA:
ID  EXT   RESOLUTION FPS CH │  FILESIZE   TBR PROTO │ VCODEC        VBR ACODEC      ABR ASR MORE INFO
───────────────────────────────────────────────────────────────────────────────────────────────────────────────
sb2 mhtml 48x27        0    │                 mhtml │ images                                storyboard
sb1 mhtml 80x45        0    │                 mhtml │ images                                storyboard
sb0 mhtml 160x90       0    │                 mhtml │ images                                storyboard
599 m4a   audio only      2 │   2.02MiB   31k https │ audio only        mp4a.40.5   31k 22k ultralow, m4a_dash
600 webm  audio only      2 │   2.31MiB   35k https │ audio only        opus        35k 48k ultralow, webm_dash
139 m4a   audio only      2 │   3.19MiB   49k https │ audio only        mp4a.40.5   49k 22k low, m4a_dash
249 webm  audio only      2 │   3.37MiB   51k https │ audio only        opus        51k 48k low, webm_dash
250 webm  audio only      2 │   4.91MiB   75k https │ audio only        opus        75k 48k low, webm_dash
140 m4a   audio only      2 │   8.48MiB  129k https │ audio only        mp4a.40.2  129k 44k medium, m4a_dash
251 webm  audio only      2 │   9.56MiB  146k https │ audio only        opus       146k 48k medium, webm_dash
17  3gp   176x144     12  1 │   5.09MiB   78k https │ mp4v.20.3     78k mp4a.40.2    0k 22k 144p
597 mp4   256x144     12    │   2.03MiB   31k https │ avc1.4d400b   31k video only          144p, mp4_dash
598 webm  256x144     12    │   1.44MiB   22k https │ vp9           22k video only          144p, webm_dash
160 mp4   256x144     24    │   2.98MiB   45k https │ avc1.4d400c   45k video only          144p, mp4_dash
278 webm  256x144     24    │   3.99MiB   61k https │ vp9           61k video only          144p, webm_dash
133 mp4   426x240     24    │   6.24MiB   95k https │ avc1.4d4015   95k video only          240p, mp4_dash
242 webm  426x240     24    │   5.95MiB   91k https │ vp9           91k video only          240p, webm_dash
134 mp4   640x360     24    │  11.56MiB  177k https │ avc1.4d401e  177k video only          360p, mp4_dash
18  mp4   640x360     24  2 │  30.23MiB  462k https │ avc1.42001E  462k mp4a.40.2    0k 44k 360p
243 webm  640x360     24    │  13.14MiB  201k https │ vp9          201k video only          360p, webm_dash
135 mp4   854x480     24    │  19.41MiB  297k https │ avc1.4d401e  297k video only          480p, mp4_dash
244 webm  854x480     24    │  19.55MiB  299k https │ vp9          299k video only          480p, webm_dash
22  mp4   1280x720    24  2 │ ~42.87MiB  640k https │ avc1.64001F  640k mp4a.40.2    0k 44k 720p
136 mp4   1280x720    24    │  33.42MiB  511k https │ avc1.4d401f  511k video only          720p, mp4_dash
247 webm  1280x720    24    │  35.75MiB  546k https │ vp9          546k video only          720p, webm_dash
137 mp4   1920x1080   24    │  85.79MiB 1311k https │ avc1.640028 1311k video only          1080p, mp4_dash
248 webm  1920x1080   24    │  64.69MiB  988k https │ vp9          988k video only          1080p, webm_dash
```

**Comment by bkdwt** [comment]
> ```
> $ yt-dlp -F "https://youtu.be/0qt4BzlGapA"
> [youtube] Extracting URL: https://youtu.be/0qt4BzlGapA
> [youtube] 0qt4BzlGapA: Downloading webpage
> [youtube] 0qt4BzlGapA: Downloading android player API JSON
> [info] Available formats for 0qt4BzlGapA:
> ID  EXT   RESOLUTION FPS CH │  FILESIZE   TBR PROTO │ VCODEC        VBR ACODEC      ABR ASR MORE INFO
> ───────────────────────────────────────────────────────────────────────────────────────────────────────────────
> sb2 mhtml 48x27        0    │                 mhtml │ images                                storyboard
> sb1 mhtml 80x45        0    │                 mhtml │ images                                storyboard
> sb0 mhtml 160x90       0    │                 mhtml │ images                                storyboard
> 599 m4a   audio only      2 │   2.02MiB   31k https │ audio only        mp4a.40.5   31k 22k ultralow, m4a_dash
> 600 webm  audio only      2 │   2.31MiB   35k https │ audio only        opus        35k 48k ultralow, webm_dash
> 139 m4a   audio only      2 │   3.19MiB   49k https │ audio only        mp4a.40.5   49k 22k low, m4a_dash
> 249 webm  audio only      2 │   3.37MiB   51k https │ audio only        opus        51k 48k low, webm_dash
> 250 webm  audio only      2 │   4.91MiB   75k https │ audio only        opus        75k 48k low, webm_dash
> 140 m4a   audio only      2 │   8.48MiB  129k https │ audio only        mp4a.40.2  129k 44k medium, m4a_dash
> 251 webm  audio only      2 │   9.56MiB  146k https │ audio only        opus       146k 48k medium, webm_dash
> 17  3gp   176x144     12  1 │   5.09MiB   78k https │ mp4v.20.3     78k mp4a.40.2    0k 22k 144p
> 597 mp4   256x144     12    │   2.03MiB   31k https │ avc1.4d400b   31k video only          144p, mp4_dash
> 598 webm  256x144     12    │   1.44MiB   22k https │ vp9           22k video only          144p, webm_dash
> 160 mp4   256x144     24    │   2.98MiB   45k https │ avc1.4d400c   45k video only          144p, mp4_dash
> 278 webm  256x144     24    │   3.99MiB   61k https │ vp9           61k video only          144p, webm_dash
> 133 mp4   426x240     24    │   6.24MiB   95k https │ avc1.4d4015   95k video only          240p, mp4_dash
> 242 webm  426x240     24    │   5.95MiB   91k https │ vp9           91k video only          240p, webm_dash
> 134 mp4   640x360     24    │  11.56MiB  177k https │ avc1.4d401e  177k video only          360p, mp4_dash
> 18  mp4   640x360     24  2 │  30.23MiB  462k https │ avc1.42001E  462k mp4a.40.2    0k 44k 360p
> 243 webm  640x360     24    │  13.14MiB  201k https │ vp9          201k video only          360p, webm_dash
> 135 mp4   854x480     24    │  19.41MiB  297k https │ avc1.4d401e  297k video only          480p, mp4_dash
> 244 webm  854x480     24    │  19.55MiB  299k https │ vp9          299k video only          480p, webm_dash
> 22  mp4   1280x720    24  2 │ ~42.87MiB  640k https │ avc1.64001F  640k mp4a.40.2    0k 44k 720p
> 136 mp4   1280x720    24    │  33.42MiB  511k https │ avc1.4d401f  511k video only          720p, mp4_dash
> 247 webm  1280x720    24    │  35.75MiB  546k https │ vp9          546k video only          720p, webm_dash
> 137 mp4   1920x1080   24    │  85.79MiB 1311k https │ avc1.640028 1311k video only          1080p, mp4_dash
> 248 webm  1920x1080   24    │  64.69MiB  988k https │ vp9          988k video only          1080p, webm_dash
> ```

It works to get the video information, but it gives error when downloading as I showed in the log.
