### ISSUE TITLE
[Broken] YourPorn extractor. (working only in very old version and in youtube-dl)

### ISSUE THREAD

**Issue by magneto261290** [yt-dlp/yt-dlp#707]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running yt-dlp version **2021.08.10**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] Command-line config: ['-F', 'https://sxyprn.com/post/57ffcb2e1179b.html', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] yt-dlp version 2021.08.10 
[debug] Python version 3.7.11 (CPython 64bit) - Linux-5.4.104+-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.8, ffprobe 3.4.8
[debug] Optional libraries: mutagen, pycryptodome, sqlite, websockets
[debug] Proxy map: {}
[debug] [YourPorn] Extracting URL: https://sxyprn.com/post/57ffcb2e1179b.html
[YourPorn] 57ffcb2e1179b: Downloading webpage
ERROR: No video formats found
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/yt_dlp/YoutubeDL.py", line 1199, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/yt_dlp/YoutubeDL.py", line 1237, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/lib/python3.7/dist-packages/yt_dlp/YoutubeDL.py", line 1281, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/usr/local/lib/python3.7/dist-packages/yt_dlp/YoutubeDL.py", line 2235, in process_video_result
    raise ExtractorError('No video formats found', expected=True)
yt_dlp.utils.ExtractorError: No video formats found

```

## Description

YourPorn extractor giving error. It is working fine in yt-dlp very old version (march 2021 month's versions) and it is working in youtube-dl also but not working in yt-dlp latest version.
I tested the link which is written in extractor of yourporn.

**Comment by pukkandan** [comment]
There was a bug in -F which has been fixed by 86c66b2d3edfa973818e9384777382c026fc14fb. The actual download should work correctly even in the release. Only -F is affected by the bug
