### ISSUE TITLE
Why doesn't '-f mp4' doesn't download highest avalible resolution

### ISSUE THREAD

**Issue by matgaj** [yt-dlp/yt-dlp#7072]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I tried it on a few videos. When I leave the format blank, I get the best quality file which is usually webm. When I specify by format id (eg. avc video and aac audio) it works fine. But when I do '-f mp4' it suddenly downloads 720p intstead of 1080, even tho there is avc or av1 avalible in 1080. Is it because specifying the extension only gives a pre-merged file? How do I make it give me the best quality but in a specified container?

For example:

`yt-dlp 'https://www.youtube.com/watch?v=DXiCrL4j9Iw' -f mp4` downloads ID 22 despite there being ID 299 which is AVC 1080/60.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['https://www.youtube.com/watch?v=DXiCrL4j9Iw', '-f', 'mp4', '-vU']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (pip)
[debug] Python 3.11.3 (CPython arm64 64bit) - macOS-13.3.1-arm64-arm-64bit (OpenSSL 1.1.1t  7 Feb 2023)
[debug] exe versions: ffmpeg 6.0 (setts), ffprobe 6.0
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
yt-dlp is up to date (stable@2023.03.04)
[youtube] Extracting URL: https://www.youtube.com/watch?v=DXiCrL4j9Iw
[youtube] DXiCrL4j9Iw: Downloading webpage
[youtube] DXiCrL4j9Iw: Downloading android player API JSON
[debug] Loading youtube-nsig.90a441fd from cache
[debug] [youtube] Decrypted nsig Z4PsWljp1OUKqbxcJh => ocIcyT6L2KPcLg
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[info] DXiCrL4j9Iw: Downloading 1 format(s): 22
[debug] Invoking http downloader on "https://rr2---sn-u2oxu-fgvz.googlevideo.com/videoplayback?expire=1684449713&ei=UVVmZN3wENvYyAXgyYnYBg&ip=83.27.143.135&id=o-AEWcfheI3tFcPqo5OYYiu4DtxbrFTn8t-2JCVwsqP3Y8&itag=22&source=youtube&requiressl=yes&mh=FF&mm=31%2C29&mn=sn-u2oxu-fgvz%2Csn-u2oxu-f5fe6&ms=au%2Crdu&mv=m&mvi=2&pl=24&initcwndbps=1326250&spc=qEK7B4LKv3HZRYsJTaY2YCEliUpdIxc&vprv=1&svpuc=1&mime=video%2Fmp4&cnr=14&ratebypass=yes&dur=1081.213&lmt=1684393097696618&mt=1684427835&fvip=4&fexp=24007246%2C51000024&c=ANDROID&txp=3318224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Ccnr%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRgIhAKH3Xi4d2fzr49JNMdOjHjruGd6IANVC4rU0-aWLVJZPAiEAtZRvCgvvrdFhJy9euuc-8I8uySdCUKiVgVxtE1j8YRU%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAPco1IEU1VgmP7znchqUY5DKKM0kK_XJIJ6u43E9u-FiAiEAu-ndpS8q2F3ZyToS9xgbRSZt1Bdm60_zeGVNL1Pagss%3D"
[download] Destination: The Worst Garry's Mod Server [DXiCrL4j9Iw].mp4
[download] 100% of  112.90MiB in 00:00:26 at 4.26MiB/s
```

**Comment by bashonly** [comment]
Alternatively, you can use format sorting. `-S "ext"` will prioritize sorting formats by extension, and mp4 is first in the order of extensions:
```
$ yt-dlp -S "ext" "DXiCrL4j9Iw" --get-format
299 - 1920x1080 (1080p60)+140 - audio only (medium)
```
