### ISSUE TITLE
NRL.com doesnt't work

### ISSUE THREAD

**Issue by danderson500** [yt-dlp/yt-dlp#7080]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that a **supported** site is broken
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

USA

### Provide a description that is worded well enough to be understood

Every time i try to download from NRL.com, it says error 403, can someone fix this?

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [x] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
C:\Users\danie> E:\yt-dlp.exe vu  https://www.nrl.com/watch/matches/telstra-premiership/2012/round-20/full-match-replay-titans-v-broncos---round-20-2012/
[generic] Extracting URL: vu
ERROR: [generic] None: 'vu' is not a valid URL. Set --default-search "ytsearch" (or run  yt-dlp "ytsearch:vu" ) to search YouTube
[generic] Extracting URL: https://www.nrl.com/watch/matches/telstra-premiership/2012/round-20/full-match-replay-titans-v-broncos---round-20-2012/
[generic] full-match-replay-titans-v-broncos---round-20-2012: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] full-match-replay-titans-v-broncos---round-20-2012: Extracting information
[generic] Extracting URL: https://vcdn2.nrl.com/1e53c8e7-0b38-4c6e-93fe-ecb68b96254d/manifest.ism/manifest(format=m3u8-aapl...-20-2012%2F%22%7D%7D
[generic] full-match-replay-titans-v-broncos---round-20-2012: Downloading webpage
ERROR: [generic] None: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

**Comment by october262** [comment]
website requires a login / account to watch

**Comment by october262** [comment]
this video - https://www.nrl.com/watch/matches/telstra-premiership/2012/round-20/full-match-replay-titans-v-broncos---round-20-2012/  requires an account / login to watch,
did you try using a cookies.txt file.

**Comment by gamer191** [comment]
Even easier, just login in a browser and use `--cookies-from-browser chrome` (replace chrome with your browser)
