### ISSUE TITLE
[Bilibili.com]An error occurred downloading the user channel:An extractor error has occurred. (caused by KeyError('data'))

### ISSUE THREAD

**Issue by TeoZler** [yt-dlp/yt-dlp#7081]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that a **supported** site is broken
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

China / US

### Provide a description that is worded well enough to be understood

I used a windows machine in China and an ubuntu machine in the US for testing and both had the same error.
An attempt was made to download a single bilibili video and the download worked fine, but this error occurred when downloading the video for the entire user channel.

(I used machine translation, not sure if the translation is accurate, sorry)

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[DebugInfo on US's mechine]
[debug] Command-line config: ['-vU', 'https://space.bilibili.com/690608703/video', '--cookies', 'cookies.txt']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (pip)
[debug] Python 3.8.10 (CPython x86_64 64bit) - Linux-5.4.0-124-generic-x86_64-with-glibc2.29 (OpenSSL 1.1.1f  31 Mar 2020, glibc 2.31)
[debug] exe versions: ffmpeg 4.2.7, ffprobe 4.2.7
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.06.15, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
yt-dlp is up to date (stable@2023.03.04)
[BilibiliSpaceVideo] Extracting URL: https://space.bilibili.com/690608703/video
[BilibiliSpaceVideo] 690608703: Downloading page 0
ERROR: 690608703: An extractor error has occurred. (caused by KeyError('data')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/extractor/common.py", line 694, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/extractor/bilibili.py", line 491, in _real_extract
    metadata, paged_list = self._extract_playlist(fetch_page, get_metadata, get_entries)
  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/extractor/bilibili.py", line 438, in _extract_playlist
    first_page = fetch_page(0)
  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/extractor/bilibili.py", line 477, in fetch_page
    return response['data']
KeyError: 'data'

----------------------------------

[DebugInfo on China's mechine]
[debug] Command-line config: ['-vU', 'https://space.bilibili.com/690608703/video', '--cookies', 'cookies.txt']
[debug] Encodings: locale cp936, fs utf-8, pref cp936, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (pip)
[debug] Python 3.8.9 (CPython AMD64 64bit) - Windows-10-10.0.19041-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 2022-08-18-git-48be6616d0-full_build-www.gyan.dev (setts), ffprobe 2022-08-18-git-48be6616d0-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2023.05.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
ERROR: Unable to obtain version info; Please try again later or visit  https://github.com/yt-dlp/yt-dlp/releases/latest
[BilibiliSpaceVideo] Extracting URL: https://space.bilibili.com/690608703/video
[BilibiliSpaceVideo] 690608703: Downloading page 0
ERROR: 690608703: An extractor error has occurred. (caused by KeyError('data')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "c:\users\wen_he\appdata\local\programs\python\python38\lib\site-packages\yt_dlp\extractor\common.py", line 694, in extract
    ie_result = self._real_extract(url)
  File "c:\users\wen_he\appdata\local\programs\python\python38\lib\site-packages\yt_dlp\extractor\bilibili.py", line 491, in _real_extract
    metadata, paged_list = self._extract_playlist(fetch_page, get_metadata, get_entries)
  File "c:\users\wen_he\appdata\local\programs\python\python38\lib\site-packages\yt_dlp\extractor\bilibili.py", line 438, in _extract_playlist
    first_page = fetch_page(0)
  File "c:\users\wen_he\appdata\local\programs\python\python38\lib\site-packages\yt_dlp\extractor\bilibili.py", line 477, in fetch_page
    return response['data']
KeyError: 'data'
```

**Comment by Dr-Bluemond** [comment]
你好，你提供的这个链接并不是一个视频链接，而是一个用户的主页。现在的工具应该还不能下载一个人主页的全部视频，请进入具体视频再下载。

Hello, the link you provided is not a video link, but a user's homepage. Currently, tools cannot download all videos on a user's homepage. Please enter a specific video and download it.

**Comment by ZYinMD** [comment]
Not sure why @Dr-Bluemond 's answer was marked "outdated" - was his comment true? I have the same issue too, and I really want to know if it's possible to download all videos from a channel.

**Comment by bashonly** [comment]
> Not sure why @Dr-Bluemond 's answer was marked "outdated" - was his comment true? 

The extractor is ***supposed*** to be able to download all videos from a channel, so the comment was incorrect/outdated. But as the OP has demonstrated, it is broken.
