### ISSUE TITLE
Nothing I give --recode-video option will work, and none are described in the README

### ISSUE THREAD

**Issue by jadenquinn** [yt-dlp/yt-dlp#7088]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I know this is probably a "I'm a dumb dumb" kind of issue, I don't use CLIs unless there's no other option, and I don't really know what I'm doing.

I'm trying to get yt-dlp to download the highest quality video/audio file it can from YouTube, then convert the video part to 265, and the audio to AAC, and stuff it into an MP4 container, but I have no idea what to give the option that looks like it should do what I'm trying to do, which is --recode-video. I've given it "1", "h265", "265", "x265", "codec:h265", among some other variations of those. Nothing I give it makes it happy.
Here:

bash-3.2$ ./yt-dlp_macos --audio-quality 0 --audio-format aac --no-simulate --remux-video mp4 --recode-video 1 --ffmpeg-location ./ffmpeg https://www.youtube.com/watch?v=UwVj-ifpyyc

Usage: yt-dlp_macos [OPTIONS] URL [URL...]

yt-dlp_macos: error: invalid recode video format "1" given
bash-3.2$ 

I have no idea what to give it, and for some reason you didn't put this required information in the README. the README isn't full documentation then, it's still partial. Not everyone knows everything.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
Answered on discord, summary:

 * `--recode-video` takes an extension as an argument, not a codec

 * Simplest solution is to use `--exec` instead

 * OP has premium, wants 256k bitrate audio format: pass cookies with `--cookies-from-browser firefox`

```
./yt-dlp --ffmpeg-location ./ffmpeg --cookies-from-browser firefox --exec "./ffmpeg -i {} -c:v libx265 -c:a copy {}.h265.mp4" "https://music.youtube.com/watch?v=UwVj-ifpyyc"
```

**Comment by pukkandan** [comment]
Making --recode accept decoders (`--recode libx265`) too is a sensible feature request. Similar questions have been asked before, but I don't remember whether there is a feature request open.
