### ISSUE TITLE
fix yt-dlp m3u8 fragment to mp4

### ISSUE THREAD

**Issue by dokomade1111** [yt-dlp/yt-dlp#7089]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I'm trying to record the m3u8 link to mp4, it happens that this m3u8 link has a fragment (1/6) , so after (6/6) or 1 minute the yt-dlp stops processing?

why is this happening? what command should i add? I want after 6/6 will continue to record

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
Try adding `--downloader ffmpeg --hls-use-mpegts` to your command

If you need further help, show a verbose log

**Comment by dokomade1111** [comment]
@bashonly not work

 ```
     encoder         : Lavc58.54.100 aac
[http @ 0x571b40d86440] HTTP error 509 61 bitrate=2133.3kbits/s speed=0.992x    
[hls @ 0x571b40b09900] Failed to reload playlist 0
[http @ 0x571b40d64a00] HTTP error 509 :08.98 bitrate=4176.2kbits/s speed=0.838x    
[hls @ 0x571b40b09900] Failed to reload playlist 0
frame=  225 fps= 21 q=-1.0 Lsize=    4581kB time=00:00:08.98 bitrate=4178.6kbits/s speed=0.819x    
video:4079kB audio:141kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 8.562884%
[download] 100% in 00:00:12B time=00:00:08.87 bitrate=2126.8kbits/s speed=0.963x    
[flv @ 0x5ba11c80a640] Failed to update header with correct duration.
[flv @ 0x5ba11c80a640] Failed to update header with correct filesize.
frame=  225 fps= 24 q=25.0 Lsize=    2369kB time=00:00:09.01 bitrate=2153.6kbits/s speed=0.97x    
video:2181kB audio:177kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.478257%
[aac @ 0x5ba11c80ae80] Qavg: 175.992


```

i was always smooth with aria2c but after fragment 6 it always finished. how to keep aria2c ?

**Comment by bashonly** [comment]
If you want help:

> Run your yt-dlp command with `-vU` flag added (`yt-dlp -vU <your command line>`)
> Copy the **WHOLE** output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
Closing, can reopen if OP responds with full log
