### ISSUE TITLE
Site support https://seeautumn.com 

### ISSUE THREAD

**Issue by Theo1996** [yt-dlp/yt-dlp#7103]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Europe/greece

### Example URLs

https://seeautumn.com/chu%e2%86%92boh-vol-18-manako-kobayashi-rina-koike-hikari-yamaguchi-mai-yamaguchi-sakuna-kuwae-ai-shinozaki/

### Provide a description that is worded well enough to be understood

I would like to suggest site support for https://seeautumn.com/ and specifically the player that they use which I think is linked to the site or videohost "Netu.ac" although I am not sure

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
E:\Desktop>yt-dlp -vU https://seeautumn.com/chu%e2%86%92boh-vol-18-manako-kobayashi-rina-koike-hikari-yamaguchi-mai-yamaguchi-sakuna-kuwae-ai-shinozaki/
[debug] Command-line config: ['-vU', 'https://seeautumn.com/chu%e2%86%92boh-vol-18-manako-kobayashi-rina-koike-hikari-yamaguchi-mai-yamaguchi-sakuna-kuwae-ai-shinozaki/']
[debug] Encodings: locale cp932, fs utf-8, pref cp932, out utf-8 (No VT), error utf-8 (No VT), screen utf-8 (No VT)
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-7-6.1.7601-SP1 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 6.0-full_build-www.gyan.dev (setts), ffprobe 6.0-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
Current Build Hash: 5590c57bd0433ed239a2deaaf92e2ad6f37fe50f53664c821575cafe106a9421
yt-dlp is up to date (stable@2023.03.04)
[generic] Extracting URL: https://seeautumn.com/chu%e2%86%92boh-vol-18-manako-kobayashi-rina-koike-hikari-yamaguchi-mai-yamaguchi-sakuna-kuwae-ai-shinozaki/
[generic] chu→boh-vol-18-manako-kobayashi-rina-koike-hikari-yamaguchi-mai-yamaguchi-sakuna-kuwae-ai-shinozaki: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] chu→boh-vol-18-manako-kobayashi-rina-koike-hikari-yamaguchi-mai-yamaguchi-sakuna-kuwae-ai-shinozaki: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://seeautumn.com/chu%e2%86%92boh-vol-18-manako-kobayashi-rina-koike-hikari-yamaguchi-mai-yamaguchi-sakuna-kuwae-ai-shinozaki/
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1518, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1594, in __extract_info
  File "yt_dlp\extractor\common.py", line 694, in extract
  File "yt_dlp\extractor\generic.py", line 2510, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://seeautumn.com/chu%e2%86%92boh-vol-18-manako-kobayashi-rina-koike-hikari-yamaguchi-mai-yamaguchi-sakuna-kuwae-ai-shinozaki/
```

**Comment by sqrtNOT** [comment]
It's a pirate site. I looked up the catalog number of something from the front page https://seeautumn.com/tsdv-41571-hoshizaki-kurumi-星咲くるみ-くるみるく/ and it's for sale on DMM https://www.dmm.com/mono/dvd/-/detail/=/cid=n_701tsdv41571/

**Comment by bashonly** [comment]
> It's a pirate site.

Closing as such. OP, if you believe otherwise, you are free to provide evidence to the contrary.
