### ISSUE TITLE
The uploader always output as "NA" if using "--flat-playlist"

### ISSUE THREAD

**Issue by MarioMS08** [yt-dlp/yt-dlp#7104]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [ ] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

The `uploader` always output as `NA` if using `--flat-playlist`. It shows the uploader correctly when using the `--skip-download`, which is very slow. Works ok when using `youtube-dl` instead of `yt-dlp`.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '-o', 'uploader="%(uploader)s"|title="%(title)s"|duration="%(duration)s"', '--get-filename', '--flat-playlist', 'https://www.youtube.com/playlist?list=PL8dPuuaLjXtP-27rLI2VIjVJ5bYHZajS1']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8 (No ANSI), error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (pip)
[debug] Python 3.10.6 (CPython x86_64 64bit) - Linux-5.15.0-72-generic-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.11.0, brotli-1.0.9, certifi-2020.06.20, mutagen-1.45.1, pyxattr-0.7.2, secretstorage-3.3.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
yt-dlp is up to date (stable@2023.03.04)
[youtube:tab] Extracting URL: https://www.youtube.com/playlist?list=PL8dPuuaLjXtP-27rLI2VIjVJ5bYHZajS1
[youtube:tab] PL8dPuuaLjXtP-27rLI2VIjVJ5bYHZajS1: Downloading webpage
[youtube:tab] PL8dPuuaLjXtP-27rLI2VIjVJ5bYHZajS1: Redownloading playlist API JSON with unavailable videos
[download] Downloading playlist: Office Hours
[youtube:tab] Playlist Office Hours: Downloading 3 items of 3
[debug] The information of all playlist entries will be held in memory
[download] Downloading item 1 of 3
[download] Downloading item 2 of 3
[download] Downloading item 3 of 3
[download] Finished downloading playlist: Office Hours
```

**Comment by coletdjnz** [comment]
Hmm, should be available as `channel` is. `uploader` is set to the same as `channel` so you can use that as a workaround.

**Comment by MarioMS08** [comment]
Ok, thanks!
