### ISSUE TITLE
Trying to download certain Youtube videos through tor produces "Video not available" error in some cases. Might this be addressed from the yt-dlp side?

### ISSUE THREAD

**Issue by johnahnase** [yt-dlp/yt-dlp#7110]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Attempting to download certain videos on youtube through tor through Invidous .onion frontends persistently fails with the following message:

ERROR: [youtube] [whateverVideoID]: This video is not available

I have failed to download certain videos like this over the course of a couple of months or so. I've tested downloading some videos where this issue occurs without going through tor, and it has always worked.

So, I am wondering if this is a an issue that cannot be resolved as far as yt-dlp is concerned, or not.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '-f', 'ba', '-x', '--audio-format', 'flac', '--audio-quality', '0', '--prefer-free-formats', 'http://grwp24hodrefzvjjuccrkw3mjq4tzhaaq32amf33dzpmuxe7ilepcmad.onion/playlist?list=PLycVTiaj8OI9COuVDJdw_RdBWy11ALc4T']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d]
[debug] Lazy loading extractors is disabled
[debug] Python 3.10.6 (CPython x86_64 64bit) - Linux-6.2.6-76060206-generic-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, secretstorage-3.3.1, sqlite3-2.6.0, websockets-11.0.2
[debug] Proxy map: {}
[debug] Loaded 1801 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
yt-dlp is up to date (stable@2023.03.04)
[youtube:tab] Extracting URL: http://grwp24hodrefzvjjuccrkw3mjq4tzhaaq32amf33dzpmuxe7ilepcmad.onion/playlist?list=PLycVTiaj8OI9COuVDJdw_RdBWy11ALc4T
[youtube:tab] PLycVTiaj8OI9COuVDJdw_RdBWy11ALc4T: Downloading webpage
WARNING: [youtube:tab] Unable to download webpage: HTTP Error 429: Too Many Requests (caused by <HTTPError 429: 'Too Many Requests'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[youtube:tab] PLycVTiaj8OI9COuVDJdw_RdBWy11ALc4T: Downloading API parameters API JSON
[youtube:tab] PLycVTiaj8OI9COuVDJdw_RdBWy11ALc4T: Downloading API JSON
WARNING: [youtube:tab] YouTube said: INFO - 14 unavailable videos are hidden
[youtube:tab] PLycVTiaj8OI9COuVDJdw_RdBWy11ALc4T: Redownloading playlist API JSON with unavailable videos
[download] Downloading playlist: 01-The Beatles - Please Please me (full album)
[youtube:tab] Playlist 01-The Beatles - Please Please me (full album): Downloading 14 items of 14
[download] Downloading item 1 of 14
[youtube] Extracting URL: https://www.youtube.com/watch?v=oxwAB3SECtc
[youtube] oxwAB3SECtc: Downloading webpage
WARNING: [youtube] Unable to download webpage: HTTP Error 429: Too Many Requests
[youtube] oxwAB3SECtc: Downloading android player API JSON
[youtube] oxwAB3SECtc: Downloading iframe API JS
WARNING: [youtube] Unable to download webpage: HTTP Error 429: Too Many Requests
[youtube] oxwAB3SECtc: Downloading web player API JSON
ERROR: [youtube] oxwAB3SECtc: This video is not available
  File "/home/mruser/.local/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 694, in extract
    ie_result = self._real_extract(url)
  File "/home/mruser/.local/lib/python3.10/site-packages/yt_dlp/extractor/youtube.py", line 4066, in _real_extract
    self.raise_no_formats(reason, expected=True)
  File "/home/mruser/.local/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 1172, in raise_no_formats
    raise ExtractorError(msg, expected=expected, video_id=video_id)
```

**Comment by gamer191** [comment]
Invidious URLs aren’t supported and are redirected to YouTube.
I am curious about the 429 errors though. Is YouTube blocked in your country or something?
> I've tested downloading some videos where this issue occurs without going through tor, and it has always worked.

Are you sure? Do they work if you just use YouTube.com?

**Comment by gamer191** [comment]
(Please post a verbose log regarding my 2nd question)

**Comment by coletdjnz** [comment]
The issue here is the content is not available in the country of your TOR exit IP. 

As gamer191 mentioned, invidious urls are treated as normal `youtube.com` urls.

The TOR Ip you are using is blocked from `youtube.com`. This is common on TOR exit IPs.  But this shouldn't affect yt-dlp in this case as we have fallbacks which are being used here.

**Comment by gamer191** [comment]
> As for the 429, The TOR exit IP you are using is blocked from `youtube.com`. This is common on TOR. But this shouldn't affect yt-dlp in this case as we have fallbacks which are being used here.

Are you sure? I've definitely accessed Youtube from tor before. Perhaps it's fingerprinting tor users?



> But this shouldn't affect yt-dlp in this case as we have fallbacks which are being used here.

Um, the fallbacks must be broken, since the log shows `ERROR: [youtube] oxwAB3SECtc: This video is not available`

**Comment by coletdjnz** [comment]
> > As for the 429, The TOR exit IP you are using is blocked from `youtube.com`. This is common on TOR. But this shouldn't affect yt-dlp in this case as we have fallbacks which are being used here.
> 
> Are you sure? I've definitely accessed Youtube from tor before. Perhaps it's fingerprinting tor users?
> 
> 
> 
> > But this shouldn't affect yt-dlp in this case as we have fallbacks which are being used here.
> 
> Um, the fallbacks must be broken, since the log shows `ERROR: [youtube] oxwAB3SECtc: This video is not available`

I think you're getting mixed up between the 429 on the webpage (the IP is blocked *from* YouTube) and the video availability itself *on* YouTube (likely due to geo restrictions)

The 429s come and go and Tor has multiple exit IPs. It is irrelevant here since we use Innertuje API as a fallback to get the same data the webpage does when it fails.

**Comment by gamer191** [comment]
@johnahnase um, both logs demonstrate identical failures

**Comment by gamer191** [comment]
> I think you're getting mixed up between the 429 on the webpage (the IP is blocked _from_ YouTube) and the video availability itself _on_ YouTube (likely due to geo restrictions)

right, I didn't realise that `Video unavailable` meant the video was geo-blocked. Is that expected behaviour?

**Comment by johnahnase** [comment]
> @johnahnase um, both logs demonstrate identical failures

Whoops. Fixed.

**Comment by pukkandan** [comment]
> ```
> $ yt-dlp -vU -f ba -x --audio-format flac --audio-quality 0 --prefer-free-formats https://www.youtube.com/watch?v=czw8eqepir8
> ```
> **success -->*

Is this without tor?

**Comment by johnahnase** [comment]
> Is this without tor?

Yes. I only use tor by including 'torsocks' at the start of the command.

**Comment by pukkandan** [comment]
Then it's the tor endpoint being blocked by youtube. We can't actually extract from the onion site, only forwards it to youtube.com
