### ISSUE TITLE
add this website https://weyyak.com/

### ISSUE THREAD

**Issue by Job0115** [yt-dlp/yt-dlp#7118]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Algeria

### Example URLs

https://weyyak.com/
https://weyyak.com/en/player/episode/1341952/Ribat-Al-Hob-Episode49
https://weyyak.com/en/player/movie/233040/Pyaar-Kiya-toh-Darna-Kya

### Provide a description that is worded well enough to be understood

this is my favorite site to watch movies and series And I will be grateful to you if it is supported by you

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
C:\ytdl>yt-dlp.exe https://weyyak.com/ar/player/episode/1341952/
[generic] Extracting URL: https://weyyak.com/ar/player/episode/1341952/
[generic] 1341952: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] 1341952: Extracting information
ERROR: Unsupported URL: https://weyyak.com/ar/player/episode/1341952/
```

**Comment by ItzMaxTV** [comment]
Currently working on it..

**Comment by ItzMaxTV** [comment]
Made the extractor, let's wait for the PR
https://github.com/yt-dlp/yt-dlp/pull/7124

**Comment by Job0115** [comment]
My friend let me know when it's ready ok, im so excited

**Comment by ItzMaxTV** [comment]
> My friend let me know when it's ready ok, im so excited

Reviewers will hopefully release it soon, it won't take long..

**Comment by Job0115** [comment]
My friend told me did you finish work

**Comment by bashonly** [comment]
@Job0115 run `yt-dlp --update-to nightly`

**Comment by Job0115** [comment]
thank you so much bro for your effort
