### ISSUE TITLE
Visual artifacts in this specific downloaded YouTube video with AVC codec

### ISSUE THREAD

**Issue by Jeremy5762** [yt-dlp/yt-dlp#7120]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Worldwide

### Provide a description that is worded well enough to be understood

I came across this YouTube video (oGTTlV_4ps), when downloaded, has some visual artifacts (at 2:00-2:15 in the video).

![oGTTlV_4psQ   137, avc1 640028](https://github.com/yt-dlp/yt-dlp/assets/69150334/76be4703-1248-4afc-a304-f4a05fe8d993)

These visual artifacts aren't present when [watching the video on YouTube](https://youtu.be/oGTTlV_4psQ?t=120) (in any quality). Tried multiple different video players (VLC, Windows Media Player, etc.), they all show it.

Downloading this video in any other format doesn't contain these artifacts, only those that use the AVC codec.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '-f', '137', 'oGTTlV_4psQ']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19044-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-110759-gd815584755-20230524 (setts), ffprobe N-110759-gd815584755-20230524, phantomjs 2.1.1, rtmpdump 2.3
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
Current Build Hash: 5590c57bd0433ed239a2deaaf92e2ad6f37fe50f53664c821575cafe106a9421
yt-dlp is up to date (stable@2023.03.04)
[youtube] Extracting URL: oGTTlV_4psQ
[youtube] oGTTlV_4psQ: Downloading webpage
[youtube] oGTTlV_4psQ: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[info] oGTTlV_4psQ: Downloading 1 format(s): 137
[debug] Invoking dashsegments downloader on "https://rr3---sn-jvhj5nu-cvnd.googlevideo.com/videoplayback?expire=1684978064&ei=MGVuZP-tIM718gSYmJeIAg&ip=32.179.55.108&id=o-AOOLmR2sva6t4xmOFh0ljiver-n08rj4T6qbM8xAOGp3&itag=137&source=youtube&requiressl=yes&mh=bL&mm=31%2C29&mn=sn-jvhj5nu-cvnd%2Csn-ab5sznzl&ms=au%2Crdu&mv=m&mvi=3&pcm2cms=yes&pl=24&initcwndbps=1907500&spc=qEK7ByvQb9BsiscdJD7oUkkC9VgAVEM&vprv=1&svpuc=1&mime=video%2Fmp4&gir=yes&clen=252380899&dur=656.122&lmt=1535430888169531&mt=1684956065&fvip=2&keepalive=yes&fexp=24007246%2C51000012%2C51000023&c=ANDROID&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIhAJFXbgnmNqt24RnCBNjK5GWu-8zGaP0wwEOjWOW6NQBFAiBd4CT4JpaO_u9zhNPFvmb58BZPMeMczjLxi9xhH0941w%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIhAMm5F0MMyGlRdDP-ncamRyml5W3bebvRJco4nl1oiENRAiAQ8hgO3B5Zoml2xvX6XTQWKcdC9c4MzZoWOKqp9UAh_g%3D%3D"
[dashsegments] Total fragments: 25
[download] Destination: I RIPPED MY BOXERS IN WALMART!! [oGTTlV_4psQ].mp4
[debug] File locking is not supported. Proceeding without locking
[download] 100% of  240.69MiB in 00:01:49 at 2.20MiB/s
```

**Comment by pukkandan** [comment]
Can't reproduce. And ince your log is not of the actual download, it's impossible to say if some issue happened during it. Try deleting and redownloading the file.

**Comment by pukkandan** [comment]
> How so? I did it like instructed.

My bad. I misread the logs.

> and view at 2:00 timestamp:

Ah, I see. Since you didn't mention timestamp before, I assumed you are having issue throughout. I can reproduce at 2:00

Youtube refuses to play the h264 formats for me by default so I can't compare with browser easily. Let me try forcing h264 with a script and I'll get back to you.

**Comment by pukkandan** [comment]
When forcing h264, I can reproduce on site. So issue is on youtube's side and there's nothing we can do

![image](https://github.com/yt-dlp/yt-dlp/assets/6623388/e32e9064-0504-4970-ad0a-98f8de4fd613)
