### ISSUE TITLE
Request hotleak.vip

### ISSUE THREAD

**Issue by MrSmite** [yt-dlp/yt-dlp#7121]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Example URLs

https://hotleak.vip/belledelphine/video
https://hotleak.vip/belledelphine/video/9639246

### Provide a description that is worded well enough to be understood

Click on any creator, then click their "videos" tab

1. Use this URL (like a playlist) to download all videos and get 403 forbidden
2. Click on an individual video, copy the URL in the address bar to yt-dlp and get 403 forbidden

Don't know if this is relevant but the website can detect if firefox devtools are open and redirects to the homepage

* Side request: If possible, can we also download the images tab for the creators?

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['--cache-dir', 'N:\\media', '--downl
oad-archive', 'N:\\media\\v.txt', '-f', '(bestvideo[ext=webm][height=1080]+best
audio[ext=webm]) / (bestvideo[ext=webm][height=720]+bestaudio[ext=webm]) / (bestvideo[ext=webm][height=480]+bestaudio[ex
t=webm]) / best', '-vU', '--no-abort-on-error', '--buffer-size', '4096K', '--no-call-home', '--embed-chapters', '--no-em
bed-thumbnail', '--no-embed-metadata', '--no-embed-info-json', '--cookies
', 'cookies.txt', '--concurrent-fragments', '5', '--fragment-retries', '20', '--retries', '20', '-o', 'N:\\media\\v\\%(title)s_%(id)s.%(ext)s', 'https://hotleak.vip/belledelphine/v
ideo/9639246']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8 (No VT), error utf-8 (No VT), screen utf-8 (No VT)
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-7-6.1.7601-SP1 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-108651-gd2fd0ea1d7-20221015 (setts), ffprobe N-108651-gd2fd0ea1d7-20221015
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets
-10.4
[debug] Loaded 1786 extractors
[debug] Loading archive file 'N:\\media\\v.txt'
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
Current Build Hash: 5590c57bd0433ed239a2deaaf92e2ad6f37fe50f53664c821575cafe106a9421
yt-dlp is up to date (stable@2023.03.04)
[generic] Extracting URL: https://hotleak.vip/belledelphine/video/9639246
[generic] 9639246: Downloading webpage
ERROR: [generic] None: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); p
lease report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Con
firm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 694, in extract
  File "yt_dlp\extractor\generic.py", line 2371, in _real_extract
  File "yt_dlp\extractor\common.py", line 839, in _request_webpage

  File "yt_dlp\extractor\common.py", line 821, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 3742, in urlopen
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden


Finished
```

**Comment by CHJ85** [comment]
Just because they won't make it into yt-dlp, doesn't mean you have to delete the PR. 
What site was it btw?
