### ISSUE TITLE
"Unable to download video subtitles for 'en': HTTP Error 429: Too Many Requests" Even When Using "--sleep-subtitles 60"

### ISSUE THREAD

**Issue by christantoan** [yt-dlp/yt-dlp#7123]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Indonesia

### Provide a description that is worded well enough to be understood

I have checked https://github.com/yt-dlp/yt-dlp/issues/2706 and https://github.com/yt-dlp/yt-dlp/issues/2212 and have tried adding `--sleep-subtitles` with 1s, 10s, and 60s but it still gave me error 429.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
PS D:\Downloads\Software\yt-dlp> .\yt-dlp.exe -vU --verbose --cookies ".\cookies-youtube.com.txt" --format bestvideo*+bestaudio --write-sub --write-auto-sub --sub-langs en.*,id.* --embed-thumbnail --remux-video mkv --add-metadata --extractor-args "youtube:player_client=ios" "RKtoreimcQ8" --sleep-subtitles 60
[debug] Command-line config: ['-vU', '--verbose', '--cookies', '.\\cookies-youtube.com.txt', '--format', 'bestvideo*+bestaudio', '--write-sub', '--write-auto-sub', '--sub-langs', 'en.*,id.*', '--embed-thumbnail', '--remux-video', 'mkv', '--add-metadata', '--extractor-args', 'youtube:player_client=ios', 'RKtoreimcQ8', '--sleep-subtitles', '60']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22621-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 4.3.2-2021-02-02-full_build-www.gyan.dev, ffprobe 4.3.2-2021-02-02-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
Current Build Hash: 5590c57bd0433ed239a2deaaf92e2ad6f37fe50f53664c821575cafe106a9421
yt-dlp is up to date (stable@2023.03.04)
[youtube] Extracting URL: RKtoreimcQ8
[youtube] RKtoreimcQ8: Downloading webpage
[debug] [youtube] Extracted SAPISID cookie
[youtube] RKtoreimcQ8: Downloading ios player API JSON
[youtube] RKtoreimcQ8: Downloading m3u8 information
[info] RKtoreimcQ8: Downloading subtitles: en, en-zh-Hans, en-zh-TW, en-en, en-orig, en-de, en-id, en-it, en-ja, en-ko, en-pt-BR, en-ru, en-es-ES, en-th, en-vi, id, id-zh-Hans, id-zh-TW, id-en, id-de, id-id, id-it, id-ja, id-ko, id-pt-BR, id-ru, id-es-ES, id-th, id-vi
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[info] RKtoreimcQ8: Downloading 1 format(s): 616+140
[info] Writing video subtitles to: 【初音ミク】 Hand in Hand (Magical Mirai ver.) 【マジカルミライ 2015】 [RKtoreimcQ8].en.vtt
[debug] Invoking http downloader on "https://www.youtube.com/api/timedtext?v=RKtoreimcQ8&caps=asr&opi=112496729&xoaf=5&hl=en&ip=0.0.0.0&ipbits=0&expire=1685048292&sparams=ip%2Cipbits%2Cexpire%2Cv%2Ccaps%2Copi%2Cxoaf&signature=6A190857B61C398B008E807DEB47228F00F24D65.E2491CECAA51D3F480343D3D548E2D3C28D69CBE&key=yt8&lang=en&fmt=vtt"
[download] Sleeping 60.00 seconds ...
ERROR: Unable to download video subtitles for 'en': HTTP Error 429: Too Many Requests
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 4021, in _write_subtitles
  File "yt_dlp\YoutubeDL.py", line 2970, in dl
  File "yt_dlp\downloader\common.py", line 444, in download
  File "yt_dlp\downloader\http.py", line 376, in real_download
  File "yt_dlp\downloader\http.py", line 129, in establish_connection
  File "yt_dlp\YoutubeDL.py", line 3742, in urlopen
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 429: Too Many Requests

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1518, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1615, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1674, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2779, in process_video_result
  File "yt_dlp\YoutubeDL.py", line 3037, in process_info
  File "yt_dlp\YoutubeDL.py", line 4029, in _write_subtitles
yt_dlp.utils.DownloadError: Unable to download video subtitles for 'en': HTTP Error 429: Too Many Requests
```

**Comment by gamer191** [comment]
Can you access youtube.com, without getting one of these pages? Have you ever gotten one of those pages or needed to solve a captcha to access youtube?

![unusual traffic from your computer network](https://htopskills.com/wp-content/uploads/2020/07/unusual-traffic-from-your-computer-network.jpg)

Ignore the red text, I copied this from google images

**Comment by gamer191** [comment]
also, does that error occur if you don't pass cookies?

**Comment by christantoan** [comment]
> also, does that error occur if you don't pass cookies?

It works. And also, it works as well even when I pass my cookies.
Thank you so much!
