### ISSUE TITLE
One URL out of many did not produce a playable file and should give a graceful error message

### ISSUE THREAD

**Issue by ClioCJS** [yt-dlp/yt-dlp#7128]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Specific youtube video is consistently unplayable with set of command line options, even though 25+ other videos downloaded the same day with the same option worked just fine.

VLCplayer info on output file looks like this:
![image](https://github.com/yt-dlp/yt-dlp/assets/789591/beed8208-0b17-4c2e-a8f8-72e134d376c6)

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp -vU --verbose --write-description --compat-options filename-sanitization -f bestaudio --audio-quality best --embed-chapters --add-metadata --embed-metadata --embed-subs --embed-info-json --sub-langs en "KJy7T24rhg0"
[debug] Command-line config: ['-vU', '--verbose', '--write-description', '--compat-options', 'filename-sanitization', '-f', 'bestaudio', '--audio-quality', 'best', '--embed-chapters', '--add-metadata', '--embed-metadata', '--embed-subs', '--embed-info-json', '--sub-langs', 'en', 'KJy7T24rhg0']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (win_exe)
[debug] Compatibility options: filename-sanitization
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 6.0-essentials_build-www.gyan.dev (setts), ffprobe 6.0-essentials_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
Current Build Hash: 5590c57bd0433ed239a2deaaf92e2ad6f37fe50f53664c821575cafe106a9421
yt-dlp is up to date (stable@2023.03.04)
[youtube] Extracting URL: KJy7T24rhg0
[youtube] KJy7T24rhg0: Downloading webpage
[youtube] KJy7T24rhg0: Downloading android player API JSON
[info] KJy7T24rhg0: Downloading subtitles: en
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[info] KJy7T24rhg0: Downloading 1 format(s): 251
[info] Writing video description to: HELLUVA BOSS - WESTERN ENERGY _ S2 - Episode 4 [KJy7T24rhg0].description
[info] Writing video subtitles to: HELLUVA BOSS - WESTERN ENERGY _ S2 - Episode 4 [KJy7T24rhg0].en.vtt
[debug] Invoking http downloader on "https://www.youtube.com/api/timedtext?v=KJy7T24rhg0&caps=asr&opi=112496729&xoaf=4&hl=en&ip=0.0.0.0&ipbits=0&expire=1685120793&sparams=ip%2Cipbits%2Cexpire%2Cv%2Ccaps%2Copi%2Cxoaf&signature=9CC2E69E0BA1B4978287C8B106479AAC13B969A4.8A1046E617EABAEEFDFB5DB5937372DBFCBCF011&key=yt8&lang=en&fmt=vtt"
[debug] File locking is not supported. Proceeding without locking
[download] Destination: HELLUVA BOSS - WESTERN ENERGY _ S2 - Episode 4 [KJy7T24rhg0].en.vtt
[download] 100% of   18.43KiB in 00:00:00 at 207.12KiB/s
[debug] Invoking dashsegments downloader on "https://rr5---sn-p5qs7nzr.googlevideo.com/videoplayback?expire=1685117193&ei=qYRwZOeSIPeN_9EPg6eE6Ag&ip=2600%3A8806%3A2305%3Ac800%3A99cf%3A572%3A8133%3Abc95&id=o-ABUr7DxHbY6FJ-h6L1snX6Oaa4JcuuGdKwGELxWNGTxG&itag=251&source=youtube&requiressl=yes&mh=pq&mm=31%2C26&mn=sn-p5qs7nzr%2Csn-ab5l6nr6&ms=au%2Conr&mv=m&mvi=5&pl=38&initcwndbps=1843750&spc=qEK7B17HxE_YRVPI0xREHPD3toFIb9o&vprv=1&svpuc=1&mime=audio%2Fwebm&gir=yes&clen=18732609&dur=1165.061&lmt=1684666564232052&mt=1685095254&fvip=3&keepalive=yes&fexp=24007246%2C24363392%2C51000014&beids=24350018&c=ANDROID&txp=5532434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRgIhALfAk9yv2wQOgbtQhaF6LAc5Jqfw7fNr2LyNPt3ljMkkAiEA9gEeZdsoANeF_L8d1YRVy_ZWtbzoBIyMi3sUYyuyy9s%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgVWZz3X8i8TcNBZwYtnoY4-m636p6x3kyD16E1-Pp1hQCIQDSTg9BmD69u0pf8PKC8XwENnMIj-Hi4ofbCs0so3p55A%3D%3D"
[dashsegments] Total fragments: 2
[download] Destination: HELLUVA BOSS - WESTERN ENERGY _ S2 - Episode 4 [KJy7T24rhg0].webm
[download] 100% of   17.86MiB in 00:00:01 at 14.85MiB/s
[EmbedSubtitle] Embedding subtitles in "HELLUVA BOSS - WESTERN ENERGY _ S2 - Episode 4 [KJy7T24rhg0].webm"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:HELLUVA BOSS - WESTERN ENERGY _ S2 - Episode 4 [KJy7T24rhg0].webm" -i "file:HELLUVA BOSS - WESTERN ENERGY _ S2 - Episode 4 [KJy7T24rhg0].en.vtt" -map 0 -dn -ignore_unknown -c copy -map "-0:s" -map "1:0" "-metadata:s:s:0" "language=eng" "-metadata:s:s:0" "handler_name=English" "-metadata:s:s:0" "title=English" -movflags "+faststart" "file:HELLUVA BOSS - WESTERN ENERGY _ S2 - Episode 4 [KJy7T24rhg0].temp.webm"
Deleting original file HELLUVA BOSS - WESTERN ENERGY _ S2 - Episode 4 [KJy7T24rhg0].en.vtt (pass -k to keep)
[Metadata] The info-json can only be attached to mkv/mka files
[Metadata] Adding metadata to "HELLUVA BOSS - WESTERN ENERGY _ S2 - Episode 4 [KJy7T24rhg0].webm"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:HELLUVA BOSS - WESTERN ENERGY _ S2 - Episode 4 [KJy7T24rhg0].webm" -map 0 -dn -ignore_unknown -c copy -write_id3v1 1 -metadata "title=HELLUVA BOSS - WESTERN ENERGY // S2: Episode 4" -metadata "date=20230520" -metadata "description=Striker exists and things sure do happen.

WARNING: for Comically large needles.
HELLUVA BOSS MERCH AVAILABLE ► https://sharkrobot.com/vivziepop

WANT MORE? WATCH OUR OTHER EPISODES!

Pilot Episode ► https://www.youtube.com/watch?v=OlahNrlcgS4
S1 Episode One ► https://www.youtube.com/watch?v=el_PChGfJN8
S1 Episode Two ► https://www.youtube.com/watch?v=kpnwRg268FQ
S1 Episode Three ►  https://www.youtube.com/watch?v=RghsgkZKedg
S1 Episode Four ► https://www.youtube.com/watch?v=1ZFseYPmkAk
S1 Episode Five ► https://www.youtube.com/watch?v=h2ZmVAdezF8
S1 Episode Six ► https://youtu.be/yXErLiSbxXQ
S1 Episode Seven ► https://youtu.be/8zyGQquL8VM
S2 Episode One ► https://youtu.be/_spuxXnul0U
S2 Episode Two ► https://youtu.be/4J0xFUyz1nw
S2 Episode Three ► https://youtu.be/j1BfO7VlIw4

Or Support on Patreon!
http://www.patreon.com/VivienneMedrano

Thumbnail by https://twitter.com/GasuGuma

#HelluvaBoss #HelluvaBossSeason2 #SEASONTWO" -metadata "synopsis=Striker exists and things sure do happen.

WARNING: for Comically large needles.
HELLUVA BOSS MERCH AVAILABLE ► https://sharkrobot.com/vivziepop

WANT MORE? WATCH OUR OTHER EPISODES!

Pilot Episode ► https://www.youtube.com/watch?v=OlahNrlcgS4
S1 Episode One ► https://www.youtube.com/watch?v=el_PChGfJN8
S1 Episode Two ► https://www.youtube.com/watch?v=kpnwRg268FQ
S1 Episode Three ►  https://www.youtube.com/watch?v=RghsgkZKedg
S1 Episode Four ► https://www.youtube.com/watch?v=1ZFseYPmkAk
S1 Episode Five ► https://www.youtube.com/watch?v=h2ZmVAdezF8
S1 Episode Six ► https://youtu.be/yXErLiSbxXQ
S1 Episode Seven ► https://youtu.be/8zyGQquL8VM
S2 Episode One ► https://youtu.be/_spuxXnul0U
S2 Episode Two ► https://youtu.be/4J0xFUyz1nw
S2 Episode Three ► https://youtu.be/j1BfO7VlIw4

Or Support on Patreon!
http://www.patreon.com/VivienneMedrano

Thumbnail by https://twitter.com/GasuGuma

#HelluvaBoss #HelluvaBossSeason2 #SEASONTWO" -metadata "purl=https://www.youtube.com/watch?v=KJy7T24rhg0" -metadata "comment=https://www.youtube.com/watch?v=KJy7T24rhg0" -metadata "artist=Vivziepop" -movflags "+faststart" "file:HELLUVA BOSS - WESTERN ENERGY _ S2 - Episode 4 [KJy7T24rhg0].temp.webm"
```

**Comment by pukkandan** [comment]
* The exact same command gave a playable file for me. Perhaps try using a different player? Trying a different ffmpeg version may also help.
* Assuming the issue is not with the player, yt-dlp didn't encounter any error and hence no way of identifying the file ended up being "unplayable"

**Comment by ClioCJS** [comment]
> * The exact same command gave a playable file for me. Perhaps try using a different player? Trying a different ffmpeg version may also help.


Are you 100% sure you're using the exact same command?  I just pasted it directly from my own comment, and got the exact same file that I got before: The one from which I  shared my screenshot that indicates that the file does not even contain a video stream. 

I'm using VLCplayer 3.0.18 Vetinari which is the latest version of the greatest player.

So from where I'm sitting --

This command still results in an unplayable file containing no video stream, for the latest version of the most popular video player, and this command still results in playable files for, well, literally every video i've downloaded this week (over 100).

All with the same player. I keep my VLC up to date

**Comment by pukkandan** [comment]
> that indicates that the file does not even contain a video stream.

You never said that was your issue. You aid the file is "unplayable" 🤦, which I assumed means that the file refuses to play...

> -f bestaudio

Why would there be a video stream when you are asking it to download only audio? 😕

**Comment by ClioCJS** [comment]
It's never been clear to me that -f means i'm only downloading audio, and it's still producing a video file without a stream which is a cause for a graceful error message that would have directed me in the right direction yesterday.

**Comment by pukkandan** [comment]
There is no error to show message for! The option is working exactly as you asked it to.

**Comment by ClioCJS** [comment]
I think now your ego may be taking over your ability to have a logical conversation, or maybe I just don't understand your sense of humor.

I don't think anybody on the planet wants to make video files with no video track.

Nor should an option that only mentions audio somehow have a hidden unexpected behavior of suppressing video.  That's just not a good practice.

**Comment by ClioCJS** [comment]
It's utterly laughable that "creating a video file with an option to use the best audio" would have a hidden side effect of creating no video at all.

But not just that -- ONLY for this ONE youtube video. Not for any others.

Why is it only doing it for this one video?   

You have inconsistent application behavior that needs to be addressed with consistent behavior and proper error messages.

**Comment by ClioCJS** [comment]
This is most definitely a bug because it is not consistent behavior.

**Comment by pukkandan** [comment]
> Not for any others.

Pls show logs

> "creating a video file with an option to use the best audio"

You are just blindly assuming that is what the option says, when it clearly says download the `--format bestaudio`

https://github.com/yt-dlp/yt-dlp/blob/66468bbf49562ff82670cbbd456c5e8448a6df34/README.md?plain=1#L1474

> I don't think anybody on the planet wants to make video files with no video track.

Feel free to ask youtube why they provide the audio in `.webm` instead of a `.opus` container - we are simply downloading what they provide. Or, if you'd like it to be remuxed into a common audio format, use `-x`

**Comment by ClioCJS** [comment]
Alas, I must have walked with a misunderstanding of the docs when I read them.

Ten i copied some options from one script to another to see how they would work. 

Clearly, they didn't. 


A yellow warning saying "Hey: You're creating a video file with no video in it because of <this option>" would have solved the problem for me instantly with having to create a github thread.

I think warnings can save you support time -- every single one likely prevents a thread like this from popping up.

Thank you for your help!

**Comment by ClioCJS** [comment]
And as for the inconsistent behavior.... Shoot, i may have mis-remembered because other moving parts were in action too. It seems to work now. Sorry, my bad.
