### ISSUE TITLE
Confusion about "vcodec" in format sorting 

### ISSUE THREAD

**Issue by fireattack** [yt-dlp/yt-dlp#7130]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I was reading documentation about format sorting but the examples below confused me. 

From the doc:
```
vcodec: Video Codec (av01 > vp9.2 > vp9 > h265 > h264 > vp8 > h263 > theora > other)
```

```
 For codec and ext, you can provide two preferred values, the first for video and the second for audio. E.g. +codec:avc:m4a (equivalent to +vcodec:avc,+acodec:m4a) sets the video codec preference to h264 > h265 > vp9 > vp9.2 > av01 > vp8 > h263 > theora and audio codec preference to mp4a > aac > vorbis > opus > mp3 > ac3 > dts.
```

and also

```
Note that the default has vcodec:vp9.2; i.e. av1 is not preferred
```
So the example here, `+vcodec:avc` results in `h264 > h265 > vp9 > vp9.2 > av01 > vp8 > h263 > theora`, makes no sense to me.

When using "preferred value", is it added to the front before or after the "reversal" (+)? I.e., if you use `+vcodec:avc`, it will prefer avc or put it in the end? My testing says the former, so this part matches the example.

But then since the example uses `+`, it should reverse the rest of the list. So the result of it should be, `other > theora > h263 > ... >av01` and then you preppend `h264`, which should be `h264 > other >  theora > ... > av01`.

Even if it's not reversed, it still doesn't match the order listed above. I'm aware we de-prioritized av1 by default, but if you manually use `vocodec`, it should overwrite that. And `h265` is at the different place in the list too.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
It reverses the list from the point of preference. Imagine splitting at the preference point and then stitching the lists back together. `A:x` can be roughly read as "A is x or worse or the worst available" and `+A:x` as "A is x or better or the best available". It's easier to explain with numbers, so take `res` as example:

    res => 4k > 2k > 1080 > 720 > 480 > 360 > 144
    res:720 => 720 > or worse (480 > 360 > 144) > or worst available (1080 > 2k > 4k)
    +res:720 => 720 > or better (1080 > 2k > 4k) > or best available (480 > 360 > 144)

So, similarly, 

    vcodec => av01 > vp9.2 > vp9 > h265 > h264 > vp8 > h263 > theora
    vcodec:avc => h264 > or worse (vp8 > h263 > theora) > or worst available (h265 > vp9.2 > vp9 > av1)
    +vcodec:avc => h264 > or better (h265 > vp9 > vp9.2 > av01) > or best available (vp8 > h263 > theora)

Hope that clarifies.

**Comment by fireattack** [comment]
Thanks, that explains it.

**Comment by pukkandan** [comment]
There are plans to completely rewrite the format selection/sorting docs in (not too near) future. Do you have any suggestions for improvement for this specific part?

**Comment by fireattack** [comment]
After your explanation, I think it actually makes sense, just need to be more clearly stated.  

Or maybe add ways to add more than one preferred codec.
