### ISSUE TITLE
Publishing date and time missing from metadata json

### ISSUE THREAD

**Issue by whatdoeslunasay** [yt-dlp/yt-dlp#7136]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Provide a description that is worded well enough to be understood

I have a large number of .info.json files without the video itself downloaded as part of an archiving project. I need to add information for each video to a spreadsheet. However, there is no key listing the date and time when the video was published. I am also unable to read the mtime from the file since it is not set for the .info.json files.

In the command below I'm assuming the key would be called `published_at` since the YouTube API key is called `publishedAt`. I did check that the key didn't exist under any other name.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--skip-download', '--print', 'published_at', 'https://www.youtube.com/watch?v=eYvAyFwklc4']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d]
[debug] Python 3.11.3 (CPython x86_64 64bit) - Linux-6.3.4-arch1-1-x86_64-with-glibc2.37 (OpenSSL 3.0.8 7 Feb 2023, glibc 2.37)
[debug] exe versions: ffmpeg 6.0 (setts), ffprobe 6.0, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.12.0, brotlicffi-1.0.9.2, certifi-2023.05.07, mutagen-1.46.0, secretstorage-3.3.3, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
yt-dlp is up to date (stable@2023.03.04)
[youtube] Extracting URL: https://www.youtube.com/watch?v=eYvAyFwklc4
[youtube] eYvAyFwklc4: Downloading webpage
[youtube] eYvAyFwklc4: Downloading android player API JSON
[debug] Loading youtube-nsig.bbe1b497 from cache
[debug] [youtube] Decrypted nsig K7JXzLbylYGFyH7901 => 8fx4QaHs1aQMhg
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] eYvAyFwklc4: Downloading 1 format(s): 303+251
NA
```

**Comment by bashonly** [comment]
The info json uses [yt-dlp's own fields/key names](https://github.com/yt-dlp/yt-dlp/blob/master/yt_dlp/extractor/common.py#L109), not those of the site that the info was extracted from. yt-dlp also does not use the Youtube Data API, so it is not able to get the exact publish date. It does extract an `upload_date`, the date (but not time) when the video was published

**Comment by whatdoeslunasay** [comment]
I see, thank you. The naming confused me because YouTube videos can have different upload and published dates but I think YouTube is one of the only site that has that.
