### ISSUE TITLE
[Kick.com] multi-thread

### ISSUE THREAD

**Issue by TheHellTower** [yt-dlp/yt-dlp#7138]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Hello,

I'm trying to download a VOD from Kick.com but sadly it's very long to just do: `yt-dlp.exe -f 720p60 https://stream.kick.com/.../master.m3u8` like you might now !

I was wondering if there was a way to multi-thread that from the cli or if I need to open a feature suggestion ?

Thanks !

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by gamer191** [comment]
does `--concurrent-fragments 16` (or whatever number) work?

**Comment by gamer191** [comment]
if not, please post a verbose output

**Comment by TheHellTower** [comment]
> -concurrent-fragments 16

There the verbose output for:
> yt-dlp.exe -f 720p60 https://stream.kick.com/ivs/v1/196233775518/u2Tc00FhozOp/2023/5/26/19/52/gt7idvnDeh2T/media/hls/master.m3u8 -concurrent-fragments 16 -v
```
> 
[debug] Command-line config: ['-f', '720p60', 'https://stream.kick.com/ivs/v1/196233775518/u2Tc00FhozOp/2023/5/26/19/52/gt7idvnDeh2T/media/hls/master.m3u8', '-concurrent-fragments', '16', '-v']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 6.0-full_build-www.gyan.dev (setts), ffprobe 6.0-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
ERROR: Fixed output name but more than one file to download: ncurrent-fragments
```

**Comment by bashonly** [comment]
> `-concurrent-fragments`
 
 needs to be `--concurrent-fragments`

**Comment by TheHellTower** [comment]
> > `-concurrent-fragments`
> 
> needs to be `--concurrent-fragments`

Oh yeah sorry I failed in a simple copy paste !
![brave_a0mB5Jj72X](https://github.com/yt-dlp/yt-dlp/assets/119943599/98e30219-29e1-4243-bc54-283ed573ba13)
It's way better thanks !
