### ISSUE TITLE
Unable to DL specific PBS video - error 'caused by KeyError('title')'

### ISSUE THREAD

**Issue by phhowe17** [yt-dlp/yt-dlp#7139]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

USA

### Provide a description that is worded well enough to be understood

Link: https://www.pbs.org/show/gregorian-pure-chants-concert/ or specifically https://www.pbs.org/video/gregorian-pure-chants-in-concert-HmNkuC/

Also fails in Jdownloader2.

In Firefox developer tools, there are m3u8 links which work if manually passed to yt-dlp
.
Video - https://ga.video.cdn.pbs.org/videos/gregorian-pure-chants-concert/ed32670b-0ceb-40d3-956e-317632859d05/2000339757/hd-16x9-mezzanine-1080p/gcha_000_hd-base_rev001_20230124133235090_mm1080p-hls-16x9-1080p-432p-1100k.m3u8

and subtitles (vtt) - https://ga.video.cdn.pbs.org/videos/gregorian-pure-chants-concert/ed32670b-0ceb-40d3-956e-317632859d05/2000339757/hd-16x9-mezzanine-1080p/gcha_000_hd-base_rev001_20230124133235090_mm1080p_en-captions.m3u8

Other PBS links function correctly e. g. https://www.pbs.org/video/your-brain-whos-in-control-q6suyy/

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
D:\DL\pbs>yt-dlp  -vU "https://www.pbs.org/video/gregorian-pure-chants-in-concert-HmNkuC/"
[debug] Command-line config: ['-vU', 'https://www.pbs.org/video/gregorian-pure-chants-in-concert-HmNkuC/']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22621-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 6.0-essentials_build-www.gyan.dev (setts), ffprobe 6.0-essentials_build-www.gyan.dev, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
Current Build Hash: 5590c57bd0433ed239a2deaaf92e2ad6f37fe50f53664c821575cafe106a9421
yt-dlp is up to date (stable@2023.03.04)
[debug] Using fake IP 6.190.57.133 (US) as X-Forwarded-For
[pbs] Downloading JSON metadata
[pbs] Extracting URL: https://www.pbs.org/video/gregorian-pure-chants-in-concert-HmNkuC/
[pbs] gregorian-pure-chants-in-concert-HmNkuC: Downloading webpage
[pbs] gregorian-pure-chants-in-concert-HmNkuC: Downloading widget/partnerplayer page
[pbs] gregorian-pure-chants-in-concert-HmNkuC: Downloading portalplayer page
ERROR: An extractor error has occurred. (caused by KeyError('title')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 694, in extract
  File "yt_dlp\extractor\pbs.py", line 689, in _real_extract
KeyError: 'title'
```

**Comment by bashonly** [comment]
Are you sure about this?
>  I've checked that all provided URLs are playable in a browser with the same IP and same login details

When I load https://www.pbs.org/video/gregorian-pure-chants-in-concert-HmNkuC/ in my browser, I get this:
> We're sorry, but this video is not available.

**Comment by phhowe17** [comment]
It is a Passport member only video.  I'm logged in as a member in the browser.
If I used a different browser where I'm not logged in and the link, I get [https://imgur.com/a/lPEN6yz] "donate to start watching"

This video is is also for members - https://www.pbs.org/video/is-this-music-0qM8vp/ but works with yt-dlp.

D:\DL\pbs>yt-dlp -vU "https://www.pbs.org/video/is-this-music-0qM8vp/"
[debug] Command-line config: ['-vU', 'https://www.pbs.org/video/is-this-music-0qM8vp/']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22621-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 6.0-essentials_build-www.gyan.dev (setts), ffprobe 6.0-essentials_build-www.gyan.dev, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
Current Build Hash: 5590c57bd0433ed239a2deaaf92e2ad6f37fe50f53664c821575cafe106a9421
yt-dlp is up to date (stable@2023.03.04)
[debug] Using fake IP 6.94.20.59 (US) as X-Forwarded-For
[pbs] Downloading JSON metadata
[pbs] Extracting URL: https://www.pbs.org/video/is-this-music-0qM8vp/
[pbs] is-this-music-0qM8vp: Downloading webpage
[pbs] is-this-music-0qM8vp: Downloading widget/partnerplayer page
[pbs] is-this-music-0qM8vp: Downloading portalplayer page
[pbs] is-this-music-0qM8vp: Downloading 0 video url info
[pbs] is-this-music-0qM8vp: Downloading m3u8 information
[pbs] is-this-music-0qM8vp: Downloading 1 video url info
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 3066498125: Downloading 1 format(s): hls-6844
[debug] Invoking hlsnative downloader on "https://ga.video.cdn.pbs.org/videos/fall-love-music/1d76eb81-ebd5-47a0-a65e-beaf9ab16c8b/2000289632/hd-16x9-mezzanine-1080p/famu_103_hd-base_rev002_20220408101516215_mm1080p-hls-16x9-1080p-1080p-6500k.m3u8"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 268
[download] Destination: Fall in Love with Music - Is This Music？ [3066498125].mp4
[debug] File locking is not supported. Proceeding without locking
[download]   3.0% of ~   1.30GiB at  218.09KiB/s ETA 06:07 (frag 8/268)

**Comment by bashonly** [comment]
Try passing your logged-in browser cookies to yt-dlp

**Comment by phhowe17** [comment]
Resolved.  This may be a PBS issue.  If I add "--cookies-from-browser firefox" it works.   This is the first Passport member's video I've had this required.

D:\DL\pbs>yt-dlp "https://www.pbs.org/video/gregorian-pure-chants-in-concert-HmNkuC/" --cookies-from-browser firefox
[Cookies] Extracting cookies from firefox
[Cookies] Extracted 633 cookies from firefox
[pbs] Downloading JSON metadata
[pbs] Extracting URL: https://www.pbs.org/video/gregorian-pure-chants-in-concert-HmNkuC/
[pbs] gregorian-pure-chants-in-concert-HmNkuC: Downloading webpage
[pbs] gregorian-pure-chants-in-concert-HmNkuC: Downloading widget/partnerplayer page
[pbs] gregorian-pure-chants-in-concert-HmNkuC: Downloading portalplayer page
[pbs] gregorian-pure-chants-in-concert-HmNkuC: Downloading 0 video url info
[pbs] gregorian-pure-chants-in-concert-HmNkuC: Downloading m3u8 information
[pbs] gregorian-pure-chants-in-concert-HmNkuC: Downloading 1 video url info
[info] 3077368389: Downloading 1 format(s): hls-6845
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 574
[download] Destination: Gregorian： Pure Chants in Concert - Gregorian： Pure Chants in Concert [3077368389].mp4
[download]   0.9% of ~   2.81GiB at  135.81KiB/s ETA 14:20 (frag 5/574)

**Comment by phhowe17** [comment]
Thanks for quick support.

**Comment by bashonly** [comment]
we could maybe do something like this
```diff
diff --git a/yt_dlp/extractor/pbs.py b/yt_dlp/extractor/pbs.py
index 5bdf561db..0c02f3e9d 100644
--- a/yt_dlp/extractor/pbs.py
+++ b/yt_dlp/extractor/pbs.py
@@ -595,6 +595,9 @@ def extract_redirect_urls(info):
                             'title': chapter.get('title'),
                         })
 
+        if not info and player and 'this video is not available' in player:
+            self.raise_login_required()
+
         formats = []
         http_url = None
         hls_subs = {}
```
