### ISSUE TITLE
Youtube downloads wrong date using `%(upload_date)s`? (Only occurs when video was just uploaded)

### ISSUE THREAD

**Issue by Wilann** [yt-dlp/yt-dlp#7144]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I'm downloading a playlist where live videos are being added as they're finished using the following command:
```
yt-dlp -P temp:/tmp/yt-dlp -P home:<some-path> -i <playlist-url> -o "%(playlist_title)s/%(upload_date)s - %(title)s" --download-archive "archive.txt" --config-location config_video.txt
```

`config_video.txt`:
```
--match-filter "!is_live"

--format "bestvideo[ext=mp4]+bestaudio[ext=m4a]/bestvideo[vcodec!=vp9]+bestaudio[ext=m4a]/best"
--merge-output-format mp4

--add-metadata

--embed-thumbnail
--write-thumbnail
```

I noticed a video was downloaded and named with the date from 5 days ago: `20230522 - PERODUA Malaysia Masters 2023 ｜ Akane Yamaguchi (JPN) [1] vs. Han Yue (CHN) [4] ｜ SF.mp4`
The video clearly says streamed 1h ago: https://www.youtube.com/watch?v=KdeybFRCHlU&list=PLA7ZcagI0frCmioJtroibRkM3veytYwfI&index=1

Regrettably, I can't reproduce nor get the verbose output since it only happened once. Running it again does give me the correct upload date: `20230527 - PERODUA Malaysia Masters 2023 ｜ Akane Yamaguchi (JPN) [1] vs. Han Yue (CHN) [4] ｜ SF.mp4`

Not sure if this is correct template I should use. Tried to use the "Broken site support" but can't submit due to not having the verbose output. Apologies if this is the wrong one. 

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by coletdjnz** [comment]
I believe this is expected. Before (and while?) the video is live the upload date we get is the real upload date. But once the video is published/post-live YouTube changes it to when the stream started.

Some observations showcasing this: https://github.com/yt-dlp/yt-dlp/pull/2223#issuecomment-1008485139

**Comment by pukkandan** [comment]
> I used the `--match-filter "!is_live"` filter in an attempt to skip to live videos before they're complete. Am I using the parameter incorrectly or is there any other way to achieve this?

That is correct.

**Comment by pukkandan** [comment]
No
