### ISSUE TITLE
[youtube] - Extra filtering arguments for comment fetching.

### ISSUE THREAD

**Issue by mmarquezs** [yt-dlp/yt-dlp#7166]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a site-specific feature
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

N/A

### Example URLs

Does not apply, any youtube video would be applicable for this.

### Provide a description that is worded well enough to be understood

I wish there was a more fine grained way to filter which comments are downloaded with the --write-comments feature already available.
Like being honest here, 99% of youtube comments are useless, so I don't care about archiving all of them. 
But, there is some exceptions, some Youtubers use the comments sections to add additional info, that it should be in the description but they put it in comments. They are usually pinned so they appear at the top, but not always. They also reply to some comments adding extra info related to the video, not always but sometimes.

So basically what I would like to be able to do, or at least some of it:
- Filter by users. Like I want to save only the author comments for example. Basically a whitelist.
- Filter by all the comments involving a user and the related comments. So if the user gets replies to his comments that thread is archived, if the user replies to somebody that thread gets archived, etc. So we get the user comments and the related context.
- Filter by pinned, so only the pinned comment (not sure if there can be multiple) are fetched.
- Inverse filters, like all comments except the ones from these users, like a blacklist, or other situations where an inverse filter would make sense.
- Filter by age, so only download comments from the last two months, or only the first comments on the video (as in the oldests ones)... etc
- Filter by content, like be able to filter comments by their content, some regex would be fine.  So be able to filter short comments like "Great", "Thanks for the video", etc.. 
- Any other option.

This can be done after the comments are downloaded, with a script to process the downloaded data file, so I don't expect here to have a perfect solution with lot of filters possible, but I feel like some extra filtering could added, maybe the simplest ones like download the pinned comment. 

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
N/A
```

**Comment by pukkandan** [comment]
We can only extract comments in order. You can use an external script to filter it as you want after the extraction is done.

**Comment by mmarquezs** [comment]
> This is out of the project's scope. Besides, we can only extract comments in order anyway. It's best to just use an external script to filter it as you want after the extraction is done.

Ok, I understand I was hoping for something at least but I understand.
Hopefully we can get the "pinned" status in the output, it seems in the code is already being tracked (to avoid some kind of loop it seems), https://github.com/yt-dlp/yt-dlp/blob/6f10cdcf7eeaeae5b75e0a4428cd649c156a2d83/yt_dlp/extractor/youtube.py#L3352 ,  but it's not in the output and I was hoping to use it. But in any case I saw there is a related issue open already for it so I will not open a new one: #5411
