### ISSUE TITLE
[nitter] fetching a video doesn't work

### ISSUE THREAD

**Issue by l29ah** [yt-dlp/yt-dlp#7167]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Provide a description that is worded well enough to be understood

yt-dlp  cannot fetch the video even though it plays fine in qutebrowser.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://nitter.lacontrevoie.fr/Babkin_Oladush/status/1663251590076039176']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.05.29 [6f10cdcf7]
[debug] Python 3.11.3 (CPython x86_64 64bit) - Linux-6.2.5+-x86_64-with-glibc2.37 (OpenSSL 1.1.1t  7 Feb 2023, glibc 2.37)
[debug] exe versions: ffmpeg 4.4.4 (fdk,setts), ffprobe 4.4.4, rtmpdump 2.4
[debug] Optional libraries: brotli-1.0.9, certifi-3021.03.16, mutagen-1.46.0, pycrypto-3.18.0, sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Loaded 1839 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.05.29
yt-dlp is up to date (stable@2023.05.29)
[Nitter] Extracting URL: https://nitter.lacontrevoie.fr/Babkin_Oladush/status/1663251590076039176
[Nitter] 1663251590076039176: Downloading webpage
ERROR: [Nitter] 1663251590076039176: Unable to extract video url; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/usr/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 698, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/extractor/nitter.py", line 283, in _real_extract
    video_url = '%s%s' % (base_url, self._html_search_regex(
                                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 1282, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 1246, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
```

**Comment by bashonly** [comment]
if you pass the URL of the tweet that actually contains the video, it will work:

```
$ yt-dlp -F 'https://nitter.lacontrevoie.fr/tacticalturist/status/1663168128837206016'
[Nitter] Extracting URL: https://nitter.lacontrevoie.fr/tacticalturist/status/1663168128837206016
[Nitter] 1663168128837206016: Downloading webpage
[Nitter] 1663168128837206016: Downloading m3u8 information
[info] Available formats for 1663168128837206016:
ID  EXT RESOLUTION │  TBR PROTO │ VCODEC       VBR ACODEC
────────────────────────────────────────────────────────────
256 mp4 582x270    │ 256k m3u8  │ avc1.4d001e 256k mp4a.40.2
832 mp4 640x296    │ 832k m3u8  │ avc1.4d001f 832k mp4a.40.2
```

in your log you are passing the URL for a reply tweet
