### ISSUE TITLE
Version update

### ISSUE THREAD

**Issue by benoon** [yt-dlp/yt-dlp#7175]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Why there is no updated version yet?
Current one has 3 months.
Is there any other way to obtain the most updated yt-dl file?

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
https://github.com/yt-dlp/yt-dlp#update

> There are currently two release channels for binaries, `stable` and `nightly`. `stable` is the default channel, and many of its changes have been tested by users of the `nightly` channel. The `nightly` channel has releases built after each push to the master branch, and will have the most recent fixes and additions, but also have more risk of regressions. They are available in [their own repo](https://github.com/yt-dlp/yt-dlp-nightly-builds/releases).

> When using `--update`/`-U`, a release binary will only update to its current channel. `--update-to CHANNEL` can be used to switch to a different channel when a newer version is available. `--update-to [CHANNEL@]TAG` can also be used to upgrade or downgrade to specific tags from a channel.

> Example usage:

  `yt-dlp --update-to nightly`
>  change to nightly channel and update to its latest release

or

https://github.com/yt-dlp/yt-dlp/wiki/Installation#with-pip

> If you want to be on the cutting edge, you can also install the master branch with:

```
python3 -m pip install -U pip setuptools wheel
python3 -m pip install --force-reinstall https://github.com/yt-dlp/yt-dlp/archive/master.tar.gz
```

**Comment by pukkandan** [comment]
There is no fixed release schedule. And due to the existence of nightly builds now, I am treating stable releases as low priority.

**Comment by macserv** [comment]
@bashonly Apologies for any confusion on my part, but the "cutting edge" `pip install` commands above seem to put me on the `stable` channel.

```zsh
% pip install --force-reinstall https://github.com/yt-dlp/yt-dlp/archive/master.tar.gz
Successfully installed brotli-1.0.9 certifi-2023.5.7 mutagen-1.46.0 pycryptodomex-3.18.0 websockets-11.0.3 yt-dlp-2023.3.4

% yt-dlp --version
2023.03.04

% yt-dlp --update-to nightly
Available version: nightly@2023.06.05.155301, Current version: stable@2023.03.04
```

How do I get to the nightly channel via `pip`?

**Comment by bashonly** [comment]
@macserv

The source code's version doesn't update until the next stable release, only the nightly builds'/binaries' do.
Master `version.py`: https://github.com/yt-dlp/yt-dlp/blob/master/yt_dlp/version.py

If you run `yt-dlp -v` and see `[debug] Loaded 1840 extractors` (or really any number greater than `1788`) that means you're ahead of the last stable release.

**Comment by macserv** [comment]
Ah, understood!  Thank you for the clarification.

**Comment by tomwojcik** [comment]
> There is no fixed release schedule. And due to the existence of nightly builds now, I am treating stable releases as low priority.


@pukkandan I'd appreciate if a new version was released. The diff is overwhelming as-is. Some tools that depend on the latest stable `yt-dlp` don't allow for a simple nightly bump. 

![image](https://github.com/yt-dlp/yt-dlp/assets/11278746/5170af5a-df30-4420-94c7-72f791b22fcf)

**Comment by fenopa** [comment]
Yeah a new release would be nice. Some tools use latest stable and it's not really possible to simply switch to nightly.
