### ISSUE TITLE
Report 404 errors at the end of the download

### ISSUE THREAD

**Issue by guy-teube** [yt-dlp/yt-dlp#7181]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

While yt-dlp downloads fragments, it may happen some 404 errors. But they are drowned under all the others segments, particularly on big videos with a lot of segments, or when the speed is fast (and all cannot be read).
Sometimes, fragments are downloaded in a single line (with only the percent updated) and the 404 error are much more visible.
I wonder if there should be a solution to report the 404 errors at the end of the download, for example before the merge between video and audio, to alert the user some part of the file could be corrupted and he has to be downloaded again.

I haven't recent downloads with 404 errors so I cannot copy logs here. But I took a screenshot last time:
https://postimg.cc/k6C1rqx4 (multiple fragments here, the error can be easily missed)
https://postimg.cc/4718sq51 (error is really visible here, no way to escape it)
Sorry I didn't think to copy the whole log, but 404 errors happen randomly and cannot be force (or I don't know how).

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
Those are messages from ffmpeg. We do not control them.

**Comment by guy-teube** [comment]
Ok, I thought it was maybe possible to grab them (as a kind of the grep command).
Thank you for your reponse.
