### ISSUE TITLE
Output Template option `filepath` should be mentioned in the list beside `filename`

### ISSUE THREAD

**Issue by hasezoey** [yt-dlp/yt-dlp#7197]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Currently option `filepath` is only mentioned in [this note](https://github.com/yt-dlp/yt-dlp#outtmpl-postprocess-note) and not in any of the lists like `filename` is, this issue asks that this option be mentioned in the list and in which stages it is available

PS: is it correct that `filepath` is not available in a later stage like `after_video` (which is seemingly after `after_move`)?

Command used: `yt-dlp -v -x -f bestaudio/best -o "'%(extractor)s'-'%(id)s'-%(title).150B.%(ext)s" --print "after_video:TESTVIDEO %(filepath)s %(filename)s" --print "after_move:TESTMOVE %(filepath)s %(filename)s" https://www.youtube.com/watch\?v\=ygsdfe-cjH4`

relevant output (stage, filepath, filename):
```txt
TESTMOVE /tmp/test/'youtube'-'ygsdfe-cjH4'-Just Ghost Recon. ｜ Ghost Recon Wildlands.opus NA
TESTVIDEO NA NA
```

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-v', '-x', '-f', 'bestaudio/best', '-o', "'%(extractor)s'-'%(id)s'-%(title).150B.%(ext)s", '--print', 'after_video:TESTVIDEO %(filepath)s %(filename)s', '--print', 'after_move:TESTMOVE %(filepath)s %(filename)s', 'https://www.youtube.com/watch?v=ygsdfe-cjH4']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d]
[debug] Python 3.10.10 (CPython x86_64 64bit) - Linux-6.3.4-2-MANJARO-x86_64-with-glibc2.37 (OpenSSL 3.0.8 7 Feb 2023, glibc 2.37)
[debug] exe versions: ffmpeg 6.0 (setts), ffprobe 6.0, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
[youtube] Extracting URL: https://www.youtube.com/watch?v=ygsdfe-cjH4
[youtube] ygsdfe-cjH4: Downloading webpage
[youtube] ygsdfe-cjH4: Downloading android player API JSON
[youtube] ygsdfe-cjH4: Downloading MPD manifest
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[info] ygsdfe-cjH4: Downloading 1 format(s): 251
[debug] Invoking dashsegments downloader on "https://rr3---sn-4g5ednd7.googlevideo.com/videoplayback?expire=1685646069&ei=lZZ4ZN6eOo691gKQ06CIDw&ip=2003%3Ad5%3Abf20%3Acd92%3Abd7d%3Ab67a%3Aaefa%3A23b5&id=o-AGD7TN0BGx-0sDjqBZQEA3mlhoBkB3GqceS1rQtUBeIr&itag=251&source=youtube&requiressl=yes&mh=AS&mm=31%2C26&mn=sn-4g5ednd7%2Csn-5hnednss&ms=au%2Conr&mv=m&mvi=3&pl=37&initcwndbps=1783750&spc=qEK7B1vVrDRAzxPbNGv880NNRzrWn-A&vprv=1&svpuc=1&mime=audio%2Fwebm&gir=yes&clen=4390&dur=9.101&lmt=1564297005054889&mt=1685624254&fvip=2&keepalive=yes&fexp=24007246%2C51000014&c=ANDROID&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIgP59S0H_r4qa12-u0UrWJaLyLVY-ew-mjksu4EV_OCooCIQCIsHxtbiIb7yyGZ6Vsk7PNBXr4y5Ljs7gQhxSeZzMkbw%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgTFwOdIepZSi6Y-_f4GAYpz4IPXdnapJnyIoUznARsagCIE3zk-l3cdNcIRz-nLjN6TuElqqLJWeoVmic-gvQMTi_"
[dashsegments] Total fragments: 1
[download] Destination: 'youtube'-'ygsdfe-cjH4'-Just Ghost Recon. ｜ Ghost Recon Wildlands.webm
[download] Download completed
[debug] ffmpeg command line: ffprobe -show_streams 'file:'"'"'youtube'"'"'-'"'"'ygsdfe-cjH4'"'"'-Just Ghost Recon. ｜ Ghost Recon Wildlands.webm'
[ExtractAudio] Destination: 'youtube'-'ygsdfe-cjH4'-Just Ghost Recon. ｜ Ghost Recon Wildlands.opus
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:'"'"'youtube'"'"'-'"'"'ygsdfe-cjH4'"'"'-Just Ghost Recon. ｜ Ghost Recon Wildlands.webm' -vn -acodec copy -movflags +faststart 'file:'"'"'youtube'"'"'-'"'"'ygsdfe-cjH4'"'"'-Just Ghost Recon. ｜ Ghost Recon Wildlands.opus'
Deleting original file 'youtube'-'ygsdfe-cjH4'-Just Ghost Recon. ｜ Ghost Recon Wildlands.webm (pass -k to keep)
TESTMOVE /tmp/test/'youtube'-'ygsdfe-cjH4'-Just Ghost Recon. ｜ Ghost Recon Wildlands.opus NA
TESTVIDEO NA NA
```

**Comment by pukkandan** [comment]
The field is documented in `--exec`, but I get your point. Documenting it there made sense when it was written and `--print WHEN:` didn't yet exist. I'll move it.



> PS: is it correct that `filepath` is not available in a later stage like `after_video`

`after_video` and `playlist` stages do not correspond 1-1 with other stages and have different infodict structures. Documenting them would be difficult - I suggest studying the shape from `%()#j`. To answer your question, it's in `%(requested_downloads.0.filepath)s`
