### ISSUE TITLE
Don't download entire channel history when all you want is a recent video

### ISSUE THREAD

**Issue by pbienst** [yt-dlp/yt-dlp#7203]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

I'm using dateafter, match-title and max-downloads=1 to download the latest video of a channel with a certain keyword. However, yt-dlp insists on slowly downloading the entire channel history first (more than 100 pages in my case) and only then searching for the video. It would be more efficient to check after downloading each page if we have enough data to fulfil the request.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['--extract-audio', '--audio-format', 'mp3', '--ignore-config', '--no-progress', '-vU', '-o', 'input/youtube-%(id)s.%(ext)s', 'https://www.youtube.com/@aljazeera/videos', '--match-title', 'موجز الأخبار', '--dateafter', 'now-1day', '--max-downloads', '1']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8 
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (pip)
[debug] Python 3.11.0 (CPython AMD64 64bit) - Windows-10-10.0.22621-SP0 (OpenSSL 1.1.1q  5 Jul 2022) 
[debug] exe versions: ffmpeg 4.2.1, ffprobe 4.2.1 
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {} 
[debug] Loaded 1786 extractors 
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04 
yt-dlp is up to date (stable@2023.03.04)
[youtube:tab] Extracting URL: https://www.youtube.com/@aljazeera/videos 
[youtube:tab] @aljazeera/videos: Downloading webpage
[debug] [youtube:tab] Selected tab: 'videos' (videos), Requested tab: 'videos' 
[download] Downloading playlist: AlJazeera Arabic  قناة الجزيرة - Videos
[youtube:tab] UCfiwzLy-8yKzIbsmZTzxDgw page 1: Downloading API JSON 
[youtube:tab] UCfiwzLy-8yKzIbsmZTzxDgw page 2: Downloading API JSON 
[youtube:tab] UCfiwzLy-8yKzIbsmZTzxDgw page 3: Downloading API JSON 
[youtube:tab] UCfiwzLy-8yKzIbsmZTzxDgw page 4: Downloading API JSON 
[youtube:tab] UCfiwzLy-8yKzIbsmZTzxDgw page 5: Downloading API JSON 
[youtube:tab] UCfiwzLy-8yKzIbsmZTzxDgw page 6: Downloading API JSON 
[youtube:tab] UCfiwzLy-8yKzIbsmZTzxDgw page 7: Downloading API JSON 
[youtube:tab] UCfiwzLy-8yKzIbsmZTzxDgw page 8: Downloading API JSON 
[youtube:tab] UCfiwzLy-8yKzIbsmZTzxDgw page 9: Downloading API JSON 
[youtube:tab] UCfiwzLy-8yKzIbsmZTzxDgw page 10: Downloading API JSON 
[youtube:tab] UCfiwzLy-8yKzIbsmZTzxDgw page 11: Downloading API JSON 
[youtube:tab] UCfiwzLy-8yKzIbsmZTzxDgw page 12: Downloading API JSON 
[youtube:tab] UCfiwzLy-8yKzIbsmZTzxDgw page 13: Downloading API JSON 
[youtube:tab] UCfiwzLy-8yKzIbsmZTzxDgw page 14: Downloading API JSON 
[youtube:tab] UCfiwzLy-8yKzIbsmZTzxDgw page 15: Downloading API JSON 
[youtube:tab] UCfiwzLy-8yKzIbsmZTzxDgw page 16: Downloading API JSON 
----
```

**Comment by coletdjnz** [comment]
try `--lazy-playlist`

**Comment by pbienst** [comment]
Does the job perfectly, thanks!
