### ISSUE TITLE
Iwara login cache expires

### ISSUE THREAD

**Issue by user1872372839** [yt-dlp/yt-dlp#7207]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Provide a description that is worded well enough to be understood

Ever since today, 2th June 2023 (yesterday it was working perfectly), the login API for yt-dlp on Iwara is not working anymore. 

If you try to login using --username --password, all downloads (even those that are not privated/hidden) will fail. 

It will still work on most of the videos if you remove the username/login, but then private/blocked tags videos will not download.

Example: yt-dlp.exe -f b* --username $userhere --password $passwordhere $downloadlink

Result:
[iwara]: Unable to download JSON metadata: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using yt-dlp -U

Using cookies does not work to login on Iwara. Using cookies didn't work on the previous version of yt-dlp either.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '-f', 'b*', '--username', 'PRIVATE', '--password', 'PRIVATE', 'PRIVATE']
[debug] User config "C:\Users\user\AppData\Roaming\yt-dlp\config.txt": ['-i', '--match-filter', '!is_live', '--download-archive', 'T:/youtube_channel_archiver-master/youtube-dl-archive.txt', '-f', 'bestvideo+bestaudio', '-o', '(%(playlist)s) (%(playlist_id)s)/%(uploader)s (%(uploader_id)s)/%(title)s - [%(resolution)s] [%(id)s] [AGE%(age_limit)s].%(ext)s', '--cookies-from-browser', 'firefox', '--no-check-certificate']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2023.06.02.150213 [55ed4ff73] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.05.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[Cookies] Extracting cookies from firefox
[debug] Extracting cookies from: "C:\Users\user\AppData\Roaming\Mozilla\Firefox\Profiles\user\cookies.sqlite"
[Cookies] Extracted 683 cookies from firefox
[debug] Proxy map: {}
[debug] Loaded 1842 extractors
[debug] Loading archive file 'T:/youtube_channel_archiver-master/youtube-dl-archive.txt'
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Available version: nightly@2023.06.02.150213, Current version: nightly@2023.06.02.150213
Current Build Hash: 6e916b853695926f9009ae84589467f372ea9990a0cf4ae4a101ae15aab338c3
yt-dlp is up to date (nightly@2023.06.02.150213)
[debug] Loading iwara.PRIVATEUSERNAME from cache
[debug] Loading iwara.PRIVATEUSERNAME from cache
[iwara] Fetching media token
ERROR: [iwara] PRIVATEVIDEOID: Unable to download JSON metadata: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 700, in extract
  File "yt_dlp\extractor\common.py", line 606, in initialize
  File "yt_dlp\extractor\iwara.py", line 185, in _perform_login
  File "yt_dlp\extractor\iwara.py", line 49, in _get_media_token
  File "yt_dlp\extractor\common.py", line 1057, in download_content
  File "yt_dlp\extractor\common.py", line 1021, in download_handle
  File "yt_dlp\extractor\common.py", line 891, in _download_webpage_handle
  File "yt_dlp\extractor\common.py", line 848, in _request_webpage

  File "yt_dlp\extractor\common.py", line 830, in _request_webpage
  File "yt_dlp\YoutubeDL.py", line 3776, in urlopen
  File "urllib\request.py", line 531, in open
  File "urllib\request.py", line 640, in http_response
  File "urllib\request.py", line 569, in error
  File "urllib\request.py", line 502, in _call_chain
  File "urllib\request.py", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

**Comment by bashonly** [comment]
Have you tried with `--no-cache-dir` ?

**Comment by user1872372839** [comment]
> Have you tried with `--no-cache-dir` ?

Wow, that worked. Why? Is there a problem with my configurations?

**Comment by bashonly** [comment]
The extractor caches some auth information. It seems that some of it expires.

Try clearing your yt-dlp cache dir, either manually (`~/.cache/yt-dlp/iwara`), or with `--rm-cache-dir` (this will clear it for all sites)

We should probably have the extractor determine if the cached info is expired if possible, so don't close this issue just yet

**Comment by bashonly** [comment]
cc @toomyzoom

**Comment by user1872372839** [comment]
> We should probably have the extractor determine if the cached info is expired (if possible), so don't close this issue just yet

Thank you for the help! I'll wait until further instructions to close the issue.

**Comment by toomyzoom** [comment]
> The extractor caches some auth information. It seems that some of it expires.
> 
> Try clearing your yt-dlp cache dir, either manually (`~/.cache/yt-dlp/iwara`), or with `yt-dlp --rm-cache-dir` (this will clear it for all sites)
> 
> We should probably have the extractor determine if the cached info is expired (if possible), so don't close this issue just yet
> 
> cc @toomyzoom

Pull request #7137 has the fix for the cache expire included.
