### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by larsk2** [yt-dlp/yt-dlp#721]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

Using latest version of yt-dlp
Is there any way to not remux the audio and video after they are downloaded and defragmented?

I would just like to end up with one .mp4 videofile and one .m4a audio file.

**Comment by pukkandan** [comment]
You mean you don't want them merged? Use `-f bv,ba` with `,` instead of `+`

**Comment by larsk2** [comment]
thanks, i will try it
