### ISSUE TITLE
m4uhd.tv

### ISSUE THREAD

**Issue by WoodpeckerBaby** [yt-dlp/yt-dlp#7210]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

Canada

### Example URLs

https://m4uhd.tv/watch-movie-the-bad-seed-returns-2022-271362.html

### Provide a description that is worded well enough to be understood

Unsupported URL, generic downloader failed.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://m4uhd.tv/watch-movie-the-bad-seed-returns-2022-271362.html']
[debug] User config "/Users/williamzwang/.config/yt-dlp/config": ['--downloader', 'aria2c', '--downloader-args', '-s 16 -x 16 -j 4 -k 1M', '--download-archive', 'archive.txt', '--ignore-errors', '--ffmpeg-location', '/usr/local/bin/ffmpeg', '--add-metadata', '--embed-thumbnail', '--xattrs', '--embed-subs', '--console-title', '--merge-output-format', 'mkv', '--sponsorblock-remove', 'all']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (pip)
[debug] Python 3.10.11 (CPython x86_64 64bit) - macOS-13.4-x86_64-i386-64bit (OpenSSL 1.1.1u  30 May 2023)
[debug] exe versions: ffmpeg 6.0 (setts), ffprobe 6.0
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2022.06.15, mutagen-1.45.1, sqlite3-2.6.0, websockets-10.3
[debug] Proxy map: {}
WARNING: External Downloader arguments given without specifying name. The arguments will be given to aria2c
[debug] Loaded 1786 extractors
[debug] Loading archive file 'archive.txt'
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
yt-dlp is up to date (stable@2023.03.04)
[generic] Extracting URL: https://m4uhd.tv/watch-movie-the-bad-seed-returns-2022-271362.html
[generic] watch-movie-the-bad-seed-returns-2022-271362: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] watch-movie-the-bad-seed-returns-2022-271362: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://m4uhd.tv/watch-movie-the-bad-seed-returns-2022-271362.html
Traceback (most recent call last):
  File "/usr/local/Cellar/yt-dlp/2023.3.4/libexec/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1518, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/Cellar/yt-dlp/2023.3.4/libexec/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1594, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/Cellar/yt-dlp/2023.3.4/libexec/lib/python3.10/site-packages/yt_dlp/extractor/common.py", line 694, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/Cellar/yt-dlp/2023.3.4/libexec/lib/python3.10/site-packages/yt_dlp/extractor/generic.py", line 2510, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://m4uhd.tv/watch-movie-the-bad-seed-returns-2022-271362.html
```

**Comment by bashonly** [comment]
That is a piracy site, won't be supported
