### ISSUE TITLE
Can I record to the network drive?

### ISSUE THREAD

**Issue by alihamas575** [yt-dlp/yt-dlp#7230]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Hello, I have a file server on the network. I have a 465 gb disk plugged into the modem, and I created a TV, computer, and a media center using vlc player on my phone using smb.
Using yt-dlp -P file path property, I want to download files in z:\youtube, which is defined as network drive, but it gives an error.

![image](https://github.com/yt-dlp/yt-dlp/assets/54097193/f2e6a8c3-ae7f-45e6-bf34-698ab67efd9e)

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
PS C:\Users\halim> yt-dlp -vU -P "Z:\upload\Youtube Videoları" -f "best[height=360]" https://www.youtube.com/watch?v=ws694xrKopA"&"ab_channel=MrBeast
[debug] Command-line config: ['-vU', '-P', 'Z:\\upload\\Youtube Videoları', '-f', 'best[height=360]', 'https://www.youtube.com/watch?v=ws694xrKopA&ab_channel=MrBeast']
[debug] Encodings: locale cp1254, fs utf-8, pref cp1254, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22621-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
Current Build Hash: 5590c57bd0433ed239a2deaaf92e2ad6f37fe50f53664c821575cafe106a9421
yt-dlp is up to date (stable@2023.03.04)
[youtube] Extracting URL: https://www.youtube.com/watch?v=ws694xrKopA&ab_channel=MrBeast
[youtube] ws694xrKopA: Downloading webpage
[youtube] ws694xrKopA: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, filesize, fs_approx, tbr, vbr, abr, asr, vext, aext, hasaud, id
[info] ws694xrKopA: Downloading 1 format(s): 18
ERROR: unable to create directory [WinError 3] Sistem belirtilen yolu bulamıyor: 'Z:\\'
Traceback (most recent call last):
  File "yt_dlp\utils.py", line 5419, in make_dir
  File "os.py", line 213, in makedirs
  File "os.py", line 213, in makedirs
  File "os.py", line 223, in makedirs
FileNotFoundError: [WinError 3] Sistem belirtilen yolu bulamıyor: 'Z:\\'
```

**Comment by pukkandan** [comment]
Use the actual UNC path https://stackoverflow.com/questions/21482825/find-unc-path-of-a-network-drive

**Comment by pukkandan** [comment]
Also, could you confirm yt-dlp is being run as the same user that mapped the drive and with and with same privileges?

**Comment by skykiller30** [comment]
@pukkandan are you saying just type in "-P \\servername\sharename\folder" ? because when i try to do that i just creates a new folder structure on my local machine how else could i specify a UNC path. How do i get the yt-dlp.conf file to correctly recognize the UNC path?

**Comment by bashonly** [comment]
@skykiller30 it could be a quoting issue. share a verbose log

**Comment by skykiller30** [comment]
Here is my yt-dlp.conf file and verbose logs ( im new to github so appologies if this is not the correct way to share logs)

> #file format
-S "ext"
-f "bv[height<=?720][tbr>500]"
#download location
-P "\\\TOWER\Media\YouTube" -P "temp:E:\Videos\yt-dlp\videos"
#restrict filenames
-o "%(uploader)s - %(title)s.%(ext)s" --restrict-filenames

and verbose logs ( im new to github so apologies if this is not the correct way to share logs)

> E:\Videos\yt-dlp>yt-dlp.exe https://www.youtube.com/watch?v=UAgQB4y-9go --verbose
[debug] Command-line config: ['https://www.youtube.com/watch?v=UAgQB4y-9go', '--verbose']
[debug] Portable config "E:\Videos\yt-dlp\yt-dlp.conf": ['-S', 'ext', '-f', 'bv[height<=?720][tbr>500]', '-P', '\\TOWER\\Media\\YouTube', '-P', 'temp:E:\\Videos\\yt-dlp\\videos', '-o', '%(uploader)s - %(title)s.%(ext)s', '--restrict-filenames']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2024.10.22 from yt-dlp/yt-dlp [67adeb7ba] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.22631-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-117623-g3565903c63-20241022 (setts), ffprobe N-117623-g3565903c63-20241022
[debug] Optional libraries: Cryptodome-3.21.0, brotli-1.1.0, certifi-2024.08.30, curl_cffi-0.5.10, mutagen-1.47.0, requests-2.32.3, sqlite3-3.35.5, urllib3-2.2.3, websockets-13.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets, curl_cffi
[debug] Loaded 1839 extractors
[youtube] Extracting URL: https://www.youtube.com/watch?v=UAgQB4y-9go
[youtube] UAgQB4y-9go: Downloading webpage
[youtube] UAgQB4y-9go: Downloading ios player API JSON
[youtube] UAgQB4y-9go: Downloading mweb player API JSON
[debug] Loading youtube-nsig.a62d836d from cache
[debug] [youtube] Decrypted nsig dUbS0UKWzvVctp-Om => 2oJy4dSiyVpWrg
[debug] Loading youtube-nsig.a62d836d from cache
[debug] [youtube] Decrypted nsig DxsDPLJ1BPlGd_RwZ => xsk2mSLQlpXPhA
[youtube] UAgQB4y-9go: Downloading m3u8 information
[debug] Sort order given by user: ext
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, vext, aext, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, hasaud, id
[info] Testing format 612
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 259
[download] Destination: E:\Videos\yt-dlp\videos\tmpq_we_790.tmp
[debug] File locking is not supported. Proceeding without locking
[download] 100% of    712.00B in 00:00:00 at 9.73KiB/s
[info] UAgQB4y-9go: Downloading 1 format(s): 612
[download] \TOWER\Media\YouTube\RetroRGB - Weekly_Roundup_432_-_October_23rd_2024.mp4 has already been downloaded

**Comment by bashonly** [comment]
in your config file, the `\\` is interpreted as `\`. try `-P "\\\\TOWER\\Media\\YouTube"`

**Comment by skykiller30** [comment]
bingo that did the trick, thank you. I assumed something was being interpreted incorrectly
