### ISSUE TITLE
Update rule34video extractor to return uploader's name as well as upload date.

### ISSUE THREAD

**Issue by omfgntsa** [yt-dlp/yt-dlp#7233]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a site-specific feature
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Asia

### Example URLs

https://rule34video.com/videos/3113700/ankha-animation-test/

### Provide a description that is worded well enough to be understood

The current extractor will not return fields uploader or upload_date, and using those in your config file when downloading from the site will return "NA" instead.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--print', 'uploader,upload_date=', 'https://rule34video.com/videos/3113700/ankha-animation-test']
[debug] User config "C:\Users\USERNAME\AppData\Roaming\yt-dlp\config.txt": ['--merge-output-format', 'mkv', '--no-mtime', '-o', '[%(uploader)s] %(upload_date>%Y-%m-%d)s %(title)s [%(id)s].%(ext)s']
[debug] Encodings: locale cp932, fs utf-8, pref cp932, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 4.2.3, ffprobe 6.0-essentials_build-www.gyan.dev, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
Current Build Hash: 5590c57bd0433ed239a2deaaf92e2ad6f37fe50f53664c821575cafe106a9421
yt-dlp is up to date (stable@2023.03.04)
[Rule34Video] Extracting URL: https://rule34video.com/videos/3113700/ankha-animation-test
[Rule34Video] 3113700: Downloading webpage
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 3113700: Downloading 1 format(s): 2
uploader = "NA"
upload_date = "NA"
```

**Comment by oltodosel** [comment]
The site has changed, so this data is no longer extracted correctly:
https://github.com/yt-dlp/yt-dlp/blob/4f8448896e6a664956ec2aa3d9fe932a931fb711/yt_dlp/extractor/rule34video.py#L84-L92

**Comment by bashonly** [comment]
@oltodosel open a new issue please
