### ISSUE TITLE
[gofile.io] download needs cookies

### ISSUE THREAD

**Issue by art-losangeles** [yt-dlp/yt-dlp#7235]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

US for me, assume not geo-blocked

### Provide a description that is worded well enough to be understood

Last used to download from gofile.io a few weeks ago (April 23). Now getting an authorization error. Links are public to be accessed via a guest account.

My workflow is to first get the playlist then download the item I want off the playlist but the first step is failing. When I try to download the first item on the playlist (assuming there is a first item) I get the same error ("Unable to download JSON metadata"). So, I assume there is a new problem creating and using the guest account to get the playlist. The link used below will expire in a few days.

In the output below I have anonymized my seedbox details.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
youtube -vU --list-formats https://gofile.io/d/Vjt6PT
[debug] Command-line config: ['-vU', '--list-formats', 'https://gofile.io/d/Vjt6PT']
[debug] User config "/media/XXXX/X/.config/yt-dlp/config": ['--format', 'bestvideo[height<=1080]+bestaudio/best[height<=1080]', '--format-sort', 'vcodec:h264', '--compat-options', 'format-sort', '-o', '~/private/youtube/%(title)s.%(ext)s', '--no-mtime', '--merge-output-format', 'mkv', '--remux-video', 'mkv']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (zip)
[debug] Compatibility options: format-sort
[debug] Python 3.9.7 (CPython x86_64 64bit) - Linux-4.19.123-feral-x86_64-with-glibc2.24 (OpenSSL 1.1.0l  10 Sep 2019, glibc 2.24)
[debug] exe versions: ffmpeg 3.2.16-1, ffprobe 3.2.16-1
[debug] Optional libraries: certifi-2022.12.07, no_Cryptodome-None, sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
Current Build Hash: 91cad9f121c1f6f0a81b747415c46ecba0ff331ed38cc6433040b4ac7b6e15ca
yt-dlp is up to date (stable@2023.03.04)
[Gofile] Getting a new guest account
[Gofile] Extracting URL: https://gofile.io/d/Vjt6PT
[download] Downloading playlist: Vjt6PT
[Gofile] Vjt6PT: Getting filelist
ERROR: Unable to download JSON metadata: HTTP Error 401: Unauthorized (caused by <HTTPError 401: 'Unauthorized'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "/media/XXXX/X/bin/yt-dlp/yt_dlp/extractor/common.py", line 821, in _request_webpage
    return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query))
  File "/media/XXXX/X/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 3742, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/media/XXXX/X/python/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/media/XXXX/X/python/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/media/XXXX/X/python/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/media/XXXX/X/python/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/media/XXXX/X/python/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 401: Unauthorized

[Gofile] Playlist Vjt6PT: Downloading 1 items of 0
[download] Finished downloading playlist: Vjt6PT
```

**Comment by erickyun** [comment]
Did you find any fix for this?

**Comment by art-losangeles** [comment]
No.

I did find reference to people describing a change in how gofile.io operates that may be related. They reported that the token to access the gofile.io API had changed several times in recent months and I suspect that might be the source of the problem. 

[https://gist.github.com/shawnli87/d416b7c9030293cabfcf4c225cdc5a15](https://gist.github.com/shawnli87/d416b7c9030293cabfcf4c225cdc5a15)

But, I am not sophisticated enough to change the "websiteToken" in gofile.py and recompile.

**Comment by erickyun** [comment]
> No.
> 
> I did find reference to people describing a change in how gofile.io operates that may be related. They reported that the token to access the gofile.io API had changed several times in recent months and I suspect that might be the source of the problem.
> 
> But, I am not sophisticated enough to change the "websiteToken" in gofile.py and recompile.

I did found a workaround 
just use --cookie file and instead of sharelink `https://gofile.io/d/xxxxx` use the direct download link `https://file10.gofile.io/download/gghjjhhhfblabla/example.mkv`

cmd: `yt-dlp "https://file10.gofile.io/download/gghjjhhhfblabla/example.mkv" --cookies "gofile.io_cookies.txt"`

**Comment by art-losangeles** [comment]
Thanks!!

That worked with a minor modification. For some reason I had to specify the file type with "-f mp4" for an mp4 file (since there was only 1 version of the file this didn't seem required but it was). For Firefox I used the "cookies.txt" Mozilla addon to export the cookies from the GoFile.io sharelink page (https://gofile.io/d/xxxxx).

This workaround is actually better than my previous workflow: I had to get the list of files then run yt-dlp with "--playlist-items N" with "N" representing the playlist-item identifier. In the playlist listing there were no filenames, only file sizes so I had to guess which playlist item was the one I wanted.

**I've left this as OPEN because the requirement to use cookies needs to be added to the list of known bugs in the FAQ so others will see it (previously, cookies were not required). Once that is done it can be closed.**

**Comment by Jertzukka** [comment]
> ```diff
> diff --git a/yt_dlp/extractor/gofile.py b/yt_dlp/extractor/gofile.py
> index ddbce2ee8..f7c47b47e 100644
> --- a/yt_dlp/extractor/gofile.py
> +++ b/yt_dlp/extractor/gofile.py
> @@ -66,7 +66,7 @@ def _entries(self, file_id):
>          query_params = {
>              'contentId': file_id,
>              'token': self._TOKEN,
> -            'websiteToken': 12345,
> +            'websiteToken': '7fd94ds12fds4',  # From https://gofile.io/dist/js/alljs.js
>          }
>          password = self.get_param('videopassword')
>          if password:
> ```

This seems to fix the Unauthorized issue for me, couldn't this be pushed to master to get the fix to everyone?

Although these fixes might be just temprary as they seem to be making changes to their API. Atleast at https://gofile.io/api, the "getContents" end point is marked with Premium Account -only, so it's possible that it'll be restricted from guest accounts at some point in the future.

**Comment by bashonly** [comment]
@jazz1611 Seems like an aria2c bug where it's not parsing cookie scope correctly. This patch works around the aria2c bug:

```diff
diff --git a/yt_dlp/extractor/gofile.py b/yt_dlp/extractor/gofile.py
index 898390583..a3c9109d7 100644
--- a/yt_dlp/extractor/gofile.py
+++ b/yt_dlp/extractor/gofile.py
@@ -1,8 +1,10 @@
 import hashlib
+import urllib.parse
 
 from .common import InfoExtractor
 from ..utils import (
     ExtractorError,
+    try_call,
     try_get
 )
 
@@ -81,6 +83,7 @@ def _entries(self, file_id):
         elif status != 'ok':
             raise ExtractorError(f'{self.IE_NAME} said: status {status}', expected=True)
 
+        account_token = try_call(lambda: self._get_cookies('https://gofile.io')['accountToken'].value)
         found_files = False
         for file in (try_get(files, lambda x: x['data']['contents'], dict) or {}).values():
             file_type, file_format = file.get('mimetype').split('/', 1)
@@ -90,6 +93,8 @@ def _entries(self, file_id):
             found_files = True
             file_url = file.get('link')
             if file_url:
+                if account_token:
+                    self._set_cookie(urllib.parse.urlparse(file_url).hostname, 'accountToken', account_token)
                 yield {
                     'id': file['id'],
                     'title': file['name'].rsplit('.', 1)[0],
```

But only 1 of aria2c's download connections succeeds; all the others fail.
The site does not allow multiple concurrent download connections.
So there is no benefit to using aria2c with gofile.

**Comment by bashonly** [comment]
@jazz1611 Fixed by 0730d5a966fa8a937d84bfb7f68be5198acb039b (run `yt-dlp --update-to nightly`)

But it seems the site doesn't allow multiple connections anyways, so downloading with aria2c offers no benefit

**Comment by Wamy-Dev** [comment]
Im still having this problem, any fixes?

**Comment by bashonly** [comment]
@Wamy-Dev post a verbose log please

**Comment by Wamy-Dev** [comment]
> @Wamy-Dev post a verbose log please

I am running it embedded, so this is what I get:
```
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8 (No ANSI), error utf-8 (No ANSI), screen utf-8 (No ANSI)
[debug] yt-dlp version stable@2023.10.07 [377e85a17] (pip) API
[debug] params: {'merge_output_format': 'mp4', 'progress_hooks': [<bound method HookHandler.ytdlpHook of <functions.webDownloadFunctions.HookHandler object at 0x7f9593a7e5e0>>], 'outtmpl': '/downloads/%(title)s/%(title)s.%(ext)s', 'restrictfilenames': True, 'no_overwrites': False, 'windowsfilenames': True, 'trim_file_name': True, 'verbose': True, 'compat_opts': set(), 'http_headers': {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.17 Safari/537.36', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'Accept-Language': 'en-us,en;q=0.5', 'Sec-Fetch-Mode': 'navigate'}}
[debug] Python 3.8.18 (CPython x86_64 64bit) - Linux-5.4.0-147-generic-x86_64-with (OpenSSL 3.1.3 19 Sep 2023)
[debug] exe versions: ffmpeg 6.0 (setts), ffprobe 6.0
[debug] Optional libraries: Cryptodome-3.19.0, brotli-1.1.0, certifi-2023.07.22, mutagen-1.47.0, sqlite3-3.41.2, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1886 extractors
[Gofile] Getting a new guest account
[Gofile] Extracting URL: https://gofile.io/d/r5hjRG
[download] Downloading playlist: r5hjRG
[Gofile] r5hjRG: Getting filelist
[Gofile] Playlist r5hjRG: Downloading 2 items of 2
[debug] The information of all playlist entries will be held in memory
[download] Downloading item 1 of 2
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 71f754c5-36c1-4366-91be-1683a80fcb9b: Downloading 1 format(s): 0
[debug] Invoking http downloader on "https://store7.gofile.io/download/71f754c5-36c1-4366-91be-1683a80fcb9b/50%E7%89%B9%E5%85%B8_%E6%9C%AA%E5%85%AC%E9%96%8B%E5%8B%95%E7%94%BB%E3%80%90%E3%82%B3%E3%82%B9%E3%83%97%E3%83%AC%E3%81%8D%E3%81%9E%E3%81%8F%E3%80%91Vtuber%E3%81%95%E3%81%8F%E3%82%89%E3%81%BF%E3%81%93%E3%80%81%E3%82%8A%E3%81%AA%E3%81%A1%E3%82%83%E3%82%93.mp4"
[download] Destination: /.mp4
```
These are my options:
```py
ydl_opts = {
        'merge_output_format': 'mp4',
        'progress_hooks': [handler.ytdlpHook],
        'outtmpl': '/downloads/%(title)s/%(title)s.%(ext)s',
        'restrictfilenames': True,
        'no_overwrites': False,
        'windowsfilenames': True,
        'trim_file_name': True,
        'verbose': True,
    }
```

**Comment by bashonly** [comment]
@Wamy-Dev remove `'trim_file_name': True`

**Comment by Wamy-Dev** [comment]
> @Wamy-Dev remove `'trim_file_name': True`

still fails:

```
[info] 71f754c5-36c1-4366-91be-1683a80fcb9b: Downloading 1 format(s): 0
[debug] Invoking http downloader on "https://store7.gofile.io/download/71f754c5-36c1-4366-91be-1683a80fcb9b/50%E7%89%B9%E5%85%B8_%E6%9C%AA%E5%85%AC%E9%96%8B%E5%8B%95%E7%94%BB%E3%80%90%E3%82%B3%E3%82%B9%E3%83%97%E3%83%AC%E3%81%8D%E3%81%9E%E3%81%8F%E3%80%91Vtuber%E3%81%95%E3%81%8F%E3%82%89%E3%81%BF%E3%81%93%E3%80%81%E3%82%8A%E3%81%AA%E3%81%A1%E3%82%83%E3%82%93.mp4"
[download] Destination: /downloads/50___Vtuber/50___Vtuber.mp4
```

that's it

**Comment by Wamy-Dev** [comment]
For some reason, the downloader hook is the problem. My bad, Ill have to investigate it further.

**Comment by Wamy-Dev** [comment]
Gofile apparently doesn't have the `total_bytes_estimate`
