### ISSUE TITLE
[ZDF] wrong sort order for `quality`

### ISSUE THREAD

**Issue by chrizilla** [yt-dlp/yt-dlp#7240]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Germany

### steps to reproduce this issue:
1. run `yt-dlp https://www.zdf.de/dokumentation/zdfzeit/tatort-ukraine-128.html --no-config -v -f- --format-sort quality`

### expected results
`fhd` should be listed below `hd`

### actual results
`fhd` is listed right at the top

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp https://www.zdf.de/dokumentation/zdfzeit/tatort-ukraine-128.html --no-config -v -f- --format-sort quality
[debug] Command-line config: ['https://www.zdf.de/dokumentation/zdfzeit/tatort-ukraine-128.html', '--no-config', '-v', '-f-', '--format-sort', 'quality']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2023.06.04.142854 [c2a1bdb00] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.05.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1840 extractors
[debug] Using fake IP 53.245.109.201 (DE) as X-Forwarded-For
[ZDF] Extracting URL: https://www.zdf.de/dokumentation/zdfzeit/tatort-ukraine-128.html
[ZDF] tatort-ukraine-128: Downloading webpage
[ZDF] tatort-ukraine-128: Downloading JSON content
[ZDF] tatort-ukraine-128: Downloading JSON metadata
[ZDF] 230620_0245_sendung_zei: Downloading m3u8 information
[ZDF] 230620_0245_sendung_zei: Downloading m3u8 information
[ZDF] 230620_0245_sendung_zei: Downloading m3u8 information
[ZDF] 230620_0245_sendung_zei: Downloading m3u8 information
[debug] Sort order given by user: quality
[debug] Sort order given by extractor: tbr, res, quality, language_preference
[debug] Formats sorted by: hasvid, ie_pref, quality, tbr, res, lang, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[info] Available formats for 230620_0245_sendung_zei:
ID                                      EXT  RESOLUTION FPS │   FILESIZE   TBR PROTO │ VCODEC        VBR ACODEC    MORE INFO
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
http-vp9_opus_webm_http_na_na-fhd       webm unknown        │ ~  1.39GiB 4328k https │ vp9         4328k opus      [deu] fhd, main
http-h264_aac_mp4_http_na_na-fhd        mp4  unknown        │ ~  2.13GiB 6628k https │ h264        6628k aac       [deu] fhd, main
hls-313-0                               mp4  480x270     25 │ ~103.29MiB  313k m3u8  │ avc1.4d401f  313k mp4a.40.2 [deu] auto, main
hls-541-0                               mp4  640x360     25 │ ~178.54MiB  542k m3u8  │ avc1.4d401f  542k mp4a.40.2 [deu] auto, main
hls-1174-0                              mp4  960x540     25 │ ~386.94MiB 1174k m3u8  │ avc1.4d401f 1174k mp4a.40.2 [deu] auto, main
hls-2536-0                              mp4  1280x720    50 │ ~835.90MiB 2536k m3u8  │ avc1.640028 2536k mp4a.40.2 [deu] auto, main
hls-5136-0                              mp4  1920x1080   50 │ ~  1.65GiB 5136k m3u8  │ avc1.64002a 5136k mp4a.40.2 [deu] auto, main
hls-313-1                               mp4  480x270     25 │ ~103.29MiB  313k m3u8  │ avc1.4d401f  313k mp4a.40.2 [deu] low, main
http-h264_aac_mp4_http_na_na-low        mp4  unknown        │ ~167.43MiB  508k https │ h264         508k aac       [deu] low, main
hls-541-1                               mp4  640x360     25 │ ~178.54MiB  542k m3u8  │ avc1.4d401f  542k mp4a.40.2 [deu] low, main
hls-313-2                               mp4  480x270     25 │ ~103.29MiB  313k m3u8  │ avc1.4d401f  313k mp4a.40.2 [deu] med, main
hls-541-2                               mp4  640x360     25 │ ~178.54MiB  542k m3u8  │ avc1.4d401f  542k mp4a.40.2 [deu] med, main
hls-1174-1                              mp4  960x540     25 │ ~386.94MiB 1174k m3u8  │ avc1.4d401f 1174k mp4a.40.2 [deu] med, main
http-vp9_opus_webm_http_na_na-high      webm unknown        │ ~121.29MiB  368k https │ vp9          368k opus      [deu] high, main
http-h264_aac_mp4_http_na_na-high-0     mp4  unknown        │ ~266.31MiB  808k https │ h264         808k aac       [deu] high, main
http-h264_aac_mp4_http_na_na-high-1     mp4  unknown        │ ~266.31MiB  808k https │ h264         808k aac       [deu] high, main
http-vp9_opus_webm_http_na_na-veryhigh  webm unknown        │ ~371.78MiB 1128k https │ vp9         1128k opus      [deu] veryhigh, main
hls-1174-2                              mp4  960x540     25 │ ~386.94MiB 1174k m3u8  │ avc1.4d401f 1174k mp4a.40.2 [deu] veryhigh, main
http-h264_aac_mp4_http_na_na-veryhigh-0 mp4  unknown        │ ~536.57MiB 1628k https │ h264        1628k aac       [deu] veryhigh, main
http-h264_aac_mp4_http_na_na-veryhigh-1 mp4  unknown        │ ~536.57MiB 1628k https │ h264        1628k aac       [deu] veryhigh, main
hls-2536-1                              mp4  1280x720    50 │ ~835.90MiB 2536k m3u8  │ avc1.640028 2536k mp4a.40.2 [deu] veryhigh, main
hls-5136-1                              mp4  1920x1080   50 │ ~  1.65GiB 5136k m3u8  │ avc1.64002a 5136k mp4a.40.2 [deu] veryhigh, main
http-vp9_opus_webm_http_na_na-hd        webm unknown        │ ~701.37MiB 2128k https │ vp9         2128k opus      [deu] hd, main
http-h264_aac_mp4_http_na_na-hd         mp4  unknown        │ ~  1.07GiB 3328k https │ h264        3328k aac       [deu] hd, main
```

**Comment by pukkandan** [comment]
> [debug] Sort order given by extractor: tbr, res, quality, language_preference

This extactor treats quality as the relative quality within the resolution, hence why it explicitly sorts it by resolution first. Your blind assumption that sorting only by quality should prioritize higher resolution is wrong.

**Comment by pukkandan** [comment]
> > it explicitly sorts it by resolution first
> 
> The format list above in the log above, is **NOT** sorted by resolution first, as you can see.

You are overriding it

**Comment by gamer191** [comment]
> --format-sort quality

Don't use this! YT-DLP downloads the best (ie highest quality) format by default. Don't override it unless you don't want yt-dlp to download the format it considers the highest quality, in which case why would you ask yt-dlp to download the highest quality?

**Comment by gamer191** [comment]
> This is the sortorder if sorted by quality (excerpt of the log above):

that's actually true-according to the current sort order hd will be prioritised over fhd if fhd is has a lower bitrate (because the fhd formats have resolution `unknown`)

I'm not sure if that would ever happen though

**Comment by bashonly** [comment]
can we just do this?
```diff
diff --git a/yt_dlp/extractor/zdf.py b/yt_dlp/extractor/zdf.py
index c863c46ed..6e16a7e97 100644
--- a/yt_dlp/extractor/zdf.py
+++ b/yt_dlp/extractor/zdf.py
@@ -24,7 +24,7 @@
 
 class ZDFBaseIE(InfoExtractor):
     _GEO_COUNTRIES = ['DE']
-    _QUALITIES = ('auto', 'low', 'med', 'high', 'veryhigh', 'hd', 'uhd')
+    _QUALITIES = ('auto', 'low', 'med', 'high', 'veryhigh', 'hd', 'fhd', 'uhd')
 
     def _call_api(self, url, video_id, item, api_token=None, referrer=None):
         headers = {}
```

**Comment by gamer191** [comment]
> if I understand correctly, according to the current sort order hd will be prioritised over fhd if fhd is has a lower bitrate (because the fhd formats have resolution `unknown`)

lol, I just realised that that will happen either way, because tbr is prioritised over `quality` 🤦
