### ISSUE TITLE
Same IP on Youtube an error

### ISSUE THREAD

**Issue by Elmar1991** [yt-dlp/yt-dlp#7245]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

When making more requests over the same IP on Youtube, an error like this occurs, what could be the solution?

ERROR: [youtube] ty5stpJiApE: Unable to download API page: <urlopen error [Errno 111] Connection refused> (caused by URLError(ConnectionRefusedError(111, 'Connection refused')))

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
ERROR: [youtube] ty5stpJiApE: Unable to download API page: <urlopen error [Errno 111] Connection refused> (caused by URLError(ConnectionRefusedError(111, 'Connection refused')))
```

**Comment by Elmar1991** [comment]
ERROR: [youtube] hIrnk8yaVVo: Requested format is not available. Use --list-formats for a list of available formats
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/YoutubeDL.py", line 1518, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/YoutubeDL.py", line 1615, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/YoutubeDL.py", line 1674, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/usr/local/lib/python3.8/dist-packages/yt_dlp/YoutubeDL.py", line 2743, in process_video_result
    raise ExtractorError(
yt_dlp.utils.ExtractorError: [youtube] hIrnk8yaVVo: Requested format is not available. Use --list-formats for a list of available formats

Download error occurred: ERROR: [youtube] hIrnk8yaVVo: Requested format is not available. Use --list-formats for a list of available formats

**Comment by bashonly** [comment]
> Copy the **WHOLE** output (starting with `[debug] Command-line config`) and insert it below

You didn't do this ^. You also didn't bother to elaborate on your issue any further.

It is most likely a network/connection issue on your end, or a problem with VPN/proxy if you are using one. But I wouldn't know, because you are not providing enough information.

Closing, can reopen if valid reporting information is provided
