### ISSUE TITLE
Playsuisse extractor: No video formats found!

### ISSUE THREAD

**Issue by pahlse** [yt-dlp/yt-dlp#7246]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Switzerland

### Provide a description that is worded well enough to be understood

It seems like the PlaySuisse extractor fails to download the m3u8 information giving me the error below. I tried it using my browsers cookies for the login but no success. Is this my fault, or something wrong with the code?

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--cookies-from-browser', 'brave', 'https://www.playsuisse.ch/watch/940572?locale=de']
[debug] User config "/home/elias/.config/yt-dlp/config": ['--no-mtime', '--add-metadata', '-o', '~/downloads/%(uploader|Unknown)s/%(title)s.%(ext)s']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (source)
[debug] Lazy loading extractors is disabled
[debug] Git HEAD: 59d9fe083
[debug] Python 3.10.10 (CPython x86_64 64bit) - Linux-6.2.12-arch1-1-x86_64-with-glibc2.37 (OpenSSL 3.0.8 7 Feb 2023, glibc 2.37)
[debug] exe versions: ffmpeg 6.0 (setts), ffprobe 6.0
[debug] Optional libraries: Cryptodome-3.12.0, certifi-2022.12.07, mutagen-1.46.0, secretstorage-3.3.3, sqlite3-2.6.0, websockets-10.4
[Cookies] Extracting cookies from brave
[debug] Extracting cookies from: "/home/elias/.config/BraveSoftware/Brave-Browser/Default/Cookies"
[Cookies] Extracted 372 cookies from brave
[debug] cookie version breakdown: {'v10': 365, 'v11': 0, 'other': 0, 'unencrypted': 7}
[debug] Proxy map: {}
[debug] Loaded 1840 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
yt-dlp is up to date (stable@2023.03.04)
[PlaySuisse] Extracting URL: https://www.playsuisse.ch/watch/940572?locale=de
[PlaySuisse] 940572: Downloading JSON metadata
[PlaySuisse] 940572: Downloading m3u8 information
WARNING: [PlaySuisse] Failed to download m3u8 information: HTTP Error 400: Bad Request
ERROR: [PlaySuisse] 940572: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "/home/elias/git/yt-dlp/yt_dlp/YoutubeDL.py", line 1552, in wrapper
    return func(self, *args, **kwargs)
  File "/home/elias/git/yt-dlp/yt_dlp/YoutubeDL.py", line 1649, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/home/elias/git/yt-dlp/yt_dlp/YoutubeDL.py", line 1708, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/home/elias/git/yt-dlp/yt_dlp/YoutubeDL.py", line 2650, in process_video_result
    self.raise_no_formats(info_dict)
  File "/home/elias/git/yt-dlp/yt_dlp/YoutubeDL.py", line 1066, in raise_no_formats
    raise ExtractorError(msg, video_id=info['id'], ie=info['extractor'],
yt_dlp.utils.ExtractorError: [PlaySuisse] 940572: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template.
Confirm you are on the latest version using  yt-dlp -U
```

**Comment by bashonly** [comment]
This is in the error response I get from the m3u8 request:
```json
{"message":"id_token not found","event":{"resource":"/akamaiMediaUrlCallback","path":"/akamaiMediaUrlCallback","httpMethod":"GET","headers":
```
Looks like the site now may add some query param/tokenize the URL/add an `id_token` header for the m3u8 request. Didn't see any relevant values in the JSON metadata. I don't have an account so I can't investigate further

**Comment by sbor23** [comment]
should be fixed by https://github.com/yt-dlp/yt-dlp/pull/9077

**Comment by pukkandan** [comment]
@pahlse Pls confirm

**Comment by pukkandan** [comment]
Dup of https://github.com/yt-dlp/yt-dlp/issues/7974. Fixed in https://github.com/yt-dlp/yt-dlp/commit/cae6e461073fb7c32fd32052a3e6721447c469bc
