### ISSUE TITLE
[twitter] poor file size estimates

### ISSUE THREAD

**Issue by 2011** [yt-dlp/yt-dlp#7255]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

global

### Provide a description that is worded well enough to be understood

Sorry to keep filing size estimate issues. I know that some of these fall into the difficult (or even impossible) to fix category., but this one comes in off by an order of magnitude. I will stick the output of yt-dlp with the -F and -v options in the section below.

When I actually run the command to download the video, I get:

```
[info] 1666201139119894528: Downloading 1 format(s): http-10368
[download] Destination: Tucker_Carlson_-_Ep._1-1666201139119894528-Tucker_Carlson.mp4
[download] 100% of   49.66MiB in 00:00:03 at 12.83MiB/s
```

Running mediainfo on the video gives:

```
[...]
Overall bit rate                         : 664 kb/s
[...]
Video
[...]
Bit rate                                 : 530 kb/s
[...]
Audio
Bit rate                                 : 130 kb/s
```

This comes close to the bitrate of the highest resolution hls video.

While the video mentioned above represents a bit of an outlier, a similar problem exists for the typical twitter video (which has the following formats available).

```
$ yt-dlp -F 'https://twitter.com/JamesOKeefeIII/status/1665757055016214530'
[twitter] Extracting URL: https://twitter.com/JamesOKeefeIII/status/1665757055016214530
[twitter] 1665757055016214530: Downloading guest token
[twitter] 1665757055016214530: Downloading JSON metadata
[twitter] 1665757055016214530: Downloading m3u8 information
[info] Available formats for 1665756645710807040:
ID        EXT RESOLUTION │  FILESIZE   TBR PROTO │ VCODEC        VBR ACODEC    ABR
──────────────────────────────────────────────────────────────────────────────────
hls-288   mp4 480x270    │ ~10.59MiB  288k m3u8  │ avc1.4d001e  288k mp4a.40.2  0k
http-288  mp4 480x270    │ ~10.59MiB  288k https │ unknown      288k unknown    0k
hls-832   mp4 640x360    │ ~30.61MiB  832k m3u8  │ avc1.4d001f  832k mp4a.40.2  0k
http-832  mp4 640x360    │ ~30.61MiB  832k https │ unknown      832k unknown    0k
hls-2176  mp4 1280x720   │ ~80.04MiB 2176k m3u8  │ avc1.640020 2176k mp4a.40.2  0k
http-2176 mp4 1280x720   │ ~80.04MiB 2176k https │ unknown     2176k unknown    0k
```

When actually downloaded (and yt-dlp picks up the exact size right away):

```
$ yt-dlp 'https://twitter.com/JamesOKeefeIII/status/1665757055016214530'
[twitter] Extracting URL: https://twitter.com/JamesOKeefeIII/status/1665757055016214530
[twitter] 1665757055016214530: Downloading guest token
[twitter] 1665757055016214530: Downloading JSON metadata
[twitter] 1665757055016214530: Downloading m3u8 information
[info] 1665756645710807040: Downloading 1 format(s): http-2176
[download] Destination: James_O_Keefe_-_WATCH_-_a_portion_of_my_hour-long_conversation_with_Robert_F._Kennedy_Jr._RFKJr_Access_to_FULL_VIDEO_for_those_subscribed_at-1665756645710807040-James_O_Keefe.mp4
[download] 100% of   15.66MiB in 00:00:02 at 6.70MiB/s
```

Both of the 1280x720 videos have bitrates (according to mediainfo) of approximately 304 kb/s (video), 130 kb/s (audio), and 436 kb/s (total).

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['--restrict-filenames', '-o', '%(title)s-%(id)s-%(uploader)s.%(ext)s', '-w', '-F', '-v', 'https://twitter.com/TuckerCarlson/status/1666203439146172419']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d]
[debug] Python 3.11.3 (CPython x86_64 64bit) - Linux-6.1.28-with-glibc2.36 (OpenSSL 1.1.1u  30 May 2023, glibc 2.36)
[debug] exe versions: ffmpeg 4.4.4 (setts), ffprobe 4.4.4
[debug] Optional libraries: certifi-3021.03.16, pycrypto-3.17
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
[twitter] Extracting URL: https://twitter.com/TuckerCarlson/status/1666203439146172419
[twitter] 1666203439146172419: Downloading guest token
[twitter] 1666203439146172419: Downloading JSON metadata
[debug] [twitter] Extracting from video info: 1666201139119894528
[twitter] 1666203439146172419: Downloading m3u8 information
[debug] Sort order given by extractor: res, br, size, proto
[debug] Formats sorted by: hasvid, ie_pref, res, tbr, vbr, abr, filesize, fs_approx, proto, lang, quality, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, asr, vext, aext, hasaud, source, id
[info] Available formats for 1666201139119894528:
ID         EXT RESOLUTION │   FILESIZE    TBR PROTO │ VCODEC         VBR ACODEC    ABR
──────────────────────────────────────────────────────────────────────────────────────
hls-66     mp4 480x270    │ ~  5.12MiB    67k m3u8  │ avc1.4d001e    67k mp4a.40.2  0k
http-288   mp4 480x270    │ ~ 22.06MiB   288k https │ unknown       288k unknown    0k
hls-160    mp4 640x360    │ ~ 12.26MiB   160k m3u8  │ avc1.4d001f   160k mp4a.40.2  0k
http-832   mp4 640x360    │ ~ 63.72MiB   832k https │ unknown       832k unknown    0k
hls-392    mp4 1280x720   │ ~ 30.09MiB   393k m3u8  │ avc1.640020   393k mp4a.40.2  0k
http-2176  mp4 1280x720   │ ~166.64MiB  2176k https │ unknown      2176k unknown    0k
hls-660    mp4 1920x1080  │ ~ 50.58MiB   660k m3u8  │ avc1.64002a   660k mp4a.40.2  0k
http-10368 mp4 1920x1080  │ ~794.00MiB 10368k https │ unknown     10368k unknown    0k
```

**Comment by bashonly** [comment]
I'm not seeing a general pattern that we can use to fix this. In your verbose log example, the m3u8 bitrates are correct, and the http format bitrates are ~15x too high. While in the other example, the m3u8 and http bitrates are the same, and both are ~5x too high.

**Comment by pukkandan** [comment]
The approximate size is often simply calculated as `tbr * duration`. If they report wrong bitrate, nothing we can do about it. Unless you can see better size estimate or bitrate the site, this is not addressable.

> When actually downloaded (and yt-dlp picks up the exact size right away):

This requires a request to be sent to the download URL. Doing so for every format in extractor process is not a viable solution.

**Comment by dirkf** [comment]
The Twitter extractor gets formats in various ways, so it's possible that some of those paths are misinterpreting, or being lied to by, the site data.

**Comment by gamer191** [comment]
> > When actually downloaded (and yt-dlp picks up the exact size right away):
> 
> This requires a request to be sent to the download URL. Doing so for every format in extractor process is not a viable solution.

In that case, shouldn't `--check-all-formats` show the correct filesizes?

**Comment by pukkandan** [comment]
> In that case, shouldn't `--check-all-formats` show the correct filesizes?

That would be possible to implement

**Comment by gamer191** [comment]
> > In that case, shouldn't `--check-all-formats` show the correct filesizes?
> 
> That would be possible to implement

Right, but then what happens if `--check-formats` (not `--check-all-formats`) is passed, it detects a different filesize, and as a result the video it checked is no longer the "best" format (since `size` is one of the format sorters)
