### ISSUE TITLE
vrt.be kan niet gedownload worden

### ISSUE THREAD

**Issue by Dreutel** [yt-dlp/yt-dlp#7256]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

België

### Provide a description that is worded well enough to be understood

https://www.vrt.be/vrtnu/a-z/muhammad-ali/1/muhammad-ali-s1a1/  kan niet gedownload worden

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
https://www.vrt.be/vrtnu/a-z/muhammad-ali/1/muhammad-ali-s1a1/
```

**Comment by bashonly** [comment]
Try running `yt-dlp --update-to nightly`

Then:
> Run your yt-dlp command with `-vU` flag added (`yt-dlp -vU <your command line>`)
> Copy the **WHOLE** output (starting with `[debug] Command-line config`) and insert it below

**Comment by Dreutel** [comment]
I'm sorry but I don't understand this. I get a message that I must report this on Github.
I don't not know very much of computers, I only used it

**Comment by bashonly** [comment]
Voer deze opdracht uit: `yt-dlp --update-to nightly`
En probeer opnieuw te downloaden

Als dat niet lukt, voeg dan dit toe: `-v`
`yt-dlp -v -u "USERNAME" -p "PASSWORD" https://www.vrt.be/vrtnu/a-z/muhammad-ali/1/muhammad-ali-s1a1/`

Kopieer en plak de uitvoer

**Comment by Dreutel** [comment]
Helaas dit wil ook niet lukken, als ik dit invoer gaat Streamfab naar YouTube   Van: bashonlyVerzonden: woensdag 7 juni 2023 16:38Aan: yt-dlp/yt-dlpCC: Dreutel; AuthorOnderwerp: Re: [yt-dlp/yt-dlp] vrt.be kan niet gedownload worden (Issue #7256) Voer deze opdracht uit: yt-dlp --update-to nightlyEn probeer opnieuw te downloadenAls dat niet lukt, voeg dan dit toe: -vyt-dlp -v -u "USERNAME" -p "PASSWORD" https://www.vrt.be/vrtnu/a-z/muhammad-ali/1/muhammad-ali-s1a1/Kopieer en plak de uitvoer—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
