### ISSUE TITLE
[Site Request] holodex.net

### ISSUE THREAD

**Issue by creeperkafasi** [yt-dlp/yt-dlp#726]
## Checklist

- [x] I'm reporting a new site support request
- [x] I've verified that I'm running yt-dlp version **2021.08.10**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that none of provided URLs violate any copyrights
- [x] The provided URLs do not contain any DRM to the best of my knowledge
- [x] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

- Single video: https://holodex.net/watch/8ZdLXELdF9Q
- Single video (dev branch): https://staging.holodex.net/watch/MiuFIzr8bR0
- Playlist (dev branch): https://staging.holodex.net/watch/9kQ2GtvDV3s?playlist=239 
- Playlist: https://holodex.net/watch/9kQ2GtvDV3s?playlist=239 (The site doesn't currently have a page for playlists specifically, more info in description)

## Description

Holodex fetches VTuber-related content from Youtube and displaying the watch url contains the Youtube video id, so pretty much everything about the watch page should be the same as Youtube.
Holodex has 2 url's; "holodex.net" and "staging.holodex.com". The second one is just the development branch, so the both urls should use the same methods.

About Playlists: Holodex currently doesn't have a page for viewing a whole playlist, the url for playlists is just the watch url with `?playlist=playlist_id` at the end. 
You can get the video list for a playlist using the `https://holodex.net/api/v2/playlist/playlist_id` (`https://holodex.net/api/v2/playlist/239`) url.

**Comment by nao20010128nao** [comment]
Please dismiss this comment. Sorry for dumb message.

Unless it's deleted on YouTube, "Single video" URLs can be fed into YoutubeIE.
on holodex: https://holodex.net/watch/8ZdLXELdF9Q
corresponds to: https://www.youtube.com/watch?v=8ZdLXELdF9Q

**Comment by pukkandan** [comment]
does the website have any self-hosted content? or is everything youtube embeds?

**Comment by nao20010128nao** [comment]
> does the website have any self-hosted content? or is everything youtube embeds?

Yes, Hololive is a group of VTubers (Virtual youTubers) and everything in this website is YouTube embed except playlists.

**Comment by sqrtNOT** [comment]
Some vtubers also post to niconico https://www.nicovideo.jp/user/80420947/video?ref=pc_userpage_menu and bilibili https://space.bilibili.com/436596836/ but Holodex doesn't have a single channel url that points to either of those websites. The graphics on site for channels are also youtube logos so I doubt non-youtube support is going to be an issue.
