### ISSUE TITLE
[bandcamp.com] add release_year metadata field

### ISSUE THREAD

**Issue by azumukupoe** [yt-dlp/yt-dlp#7263]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

yt-dlp should parse release_year of each bandcamp albums from their release date as it would be useful for naming the output folders/files

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
As a workaround for now you can use `--parse-metadata "%(release_timestamp>%Y)s:%(release_year)s"`

**Comment by h-2** [comment]
I don't get any ID3 tags bandcamp downloads... is this a known bug?

**Comment by bashonly** [comment]
@h-2 are you using `--embed-metadata` in your command?

If yes, and it's not working, and you're not getting *any* metadata tags, then open a new issue and include a full verbose log

**Comment by bashonly** [comment]
> any reason this is not the default?

a big reason is because then the file needs to be written to disk an additional time for the embedding, which is undesirable for large GB+ video downloads
