### ISSUE TITLE
[orf:tvthek] `--write-link ` writes `.../part/15408251#__youtubedl_smuggle=%7B%22force_noplaylist%22%3A+true%7D`

### ISSUE THREAD

**Issue by chrizilla** [yt-dlp/yt-dlp#7266]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

AFAIK worldwide. (Any geo-blocking would be limited to Austria.)

## steps to reproduce this issue

1. `yt-dlp --write-link` "https://tvthek.orf.at/profile/Weltjournal/5298609/WELTjournal-Edward-Snowden-alles-fuer-die-Wahrheit/14181784"

## expected result
The URL above should be written into the link file.

## actual result
This URL is written into the link file:
https://tvthek.orf.at/profile/Weltjournal/5298609/WELTjournal-Edward-Snowden-alles-fuer-die-Wahrheit/14181784/part/15408251#__youtubedl_smuggle=%7B%22force_noplaylist%22%3A+true%7D

## note
Almost all ORF.at URLs expire within 7 days after broadcast so new URLs might be required.

## related
other issues mentioning "youtubedl_smuggle": #1032, #3025, #6543

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

<details closed>
<summary>log</summary>

```shell
yt-dlp --write-link -v --no-config --test "https://tvthek.orf.at/profile/Weltjournal/5298609/WELTjournal-Edward-Snowden-alles-fuer-die-Wahrheit/14181784"
[debug] Command-line config: ['--write-link', '-v', '--no-config', '--test', 'https://tvthek.orf.at/profile/Weltjournal/5298609/WELTjournal-Edward-Snowden-alles-fuer-die-Wahrheit/14181784']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2023.06.05.155301 [59d9fe083] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.05.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1840 extractors
[orf:tvthek] Extracting URL: https://tvthek.orf.at/profile/Weltjournal/5298609/WELTjournal-Edward-Snowden-alles-fuer-die-Wahrheit/14181784
[orf:tvthek] 14181784: Downloading webpage
[download] Downloading playlist: 14181784
[orf:tvthek] 15408251: Downloading hls-Q1A-Niedrig m3u8 manifest
[orf:tvthek] 15408251: Downloading hls-Q4A-Mittel m3u8 manifest
[orf:tvthek] 15408251: Downloading hls-Q6A-Hoch m3u8 manifest
[orf:tvthek] 15408251: Downloading hls-Q8C-Sehr hoch m3u8 manifest
[orf:tvthek] 15408251: Downloading hls-QXB-Adaptiv m3u8 manifest
[orf:tvthek] 15408251: Downloading f4m manifest
[orf:tvthek] 15408251: Downloading f4m manifest
[orf:tvthek] 15408251: Downloading f4m manifest
[orf:tvthek] 15408251: Downloading f4m manifest
[orf:tvthek] 15408251: Downloading f4m manifest
[orf:tvthek] 15408251: Downloading dash-Q1A-Niedrig mpd manifest
[orf:tvthek] 15408251: Downloading dash-Q4A-Mittel mpd manifest
[orf:tvthek] 15408251: Downloading dash-Q6A-Hoch mpd manifest
[orf:tvthek] 15408251: Downloading dash-Q8C-Sehr hoch mpd manifest
[orf:tvthek] 15408251: Downloading dash-QXB-Adaptiv mpd manifest
[orf:tvthek] Playlist 14181784: Downloading 1 items of 1
[download] Downloading item 1 of 1
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: best/bestvideo+bestaudio
[info] 15408251: Downloading 1 format(s): hls-Q8C-Sehr_hoch-3576
[info] Internet shortcut (.url) is already present
[debug] Invoking hlsnative downloader on "https://apasfiis.sf.apa.at/cms-worldwide_nas/_definst_/nas/cms-worldwide/online/2023-06-07_2328_tl_02_WELTjournal---E_____14181784__o__5455949046__s15408251_1__ORF2HD_23275515P_00170811P_Q8C.mp4/chunklist.m3u8"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 296
[download] Destination: WELTjournal +： Edward Snowden - alles für die Wahrheit [15408251].mp4
[debug] File locking is not supported. Proceeding without locking
[download] 100% of    3.86MiB in 00:00:20 at 190.76KiB/s
WARNING: 15408251: Possible MPEG-TS in MP4 container or malformed AAC timestamps. Install ffmpeg to fix this automatically
[download] Finished downloading playlist: 14181784
```

</details>

**Comment by bashonly** [comment]
The extractor is intentionally appending the URL #fragment to the `webpage_url`, because then when this URL is passed back to yt-dlp, the extractor parses the fragment's "smuggled data" to determine that only this specific video should be downloaded, not the entire playlist. It's a sly way of forcing `--no-playlist`.

URL fragments are not sent with requests to the host, so this is purely a cosmetic concern.

**Comment by bashonly** [comment]
What I'm saying is that it has function being in the output. Passing that URL with the fragment back to yt-dlp will force `--no-playlist`. If you strip the fragment, it will not force `--no-playlist`

**Comment by bashonly** [comment]
> use `original_url` rather than `webpage_url` for --write-link

Maybe this would be a feasible way of solving this problem generally? Although if I run `yt-dlp --print original_url` with the OP's example URL, I get `NA` as the output. And there are probably other cases where this would be undesirable, not to mention the potential compat implications

> but use something like `smuggle_url` to accomplish this task

that's what is being used by the extractor. `smuggle_url` works by smuggling data in a url fragment

**Comment by gamer191** [comment]
> use `original_url` rather than `webpage_url` for --write-link

this is what you're asking for, but I don't know if it would be the expected behaviour



> or (even better if possible) don't smuggle anything into `original_url` and `webpage url`, but use something like `smuggle_url` to accomplish this task

`webpage url` is documented as
> `webpage_url` (string): A URL to the video webpage which if given to yt-dlp should allow to get the same result again

I would presume that including the`youtubedl_smuggle` would be the expected behaviour for that

**Comment by pukkandan** [comment]
If you just want to make a link with original url, why even use yt-dlp? The point is to make link with the final video webpage URL, which cannot be represented properly without the smuggled data. This will not be changed.

**Comment by pukkandan** [comment]
PS: `--write-link` etc are kind of redundant now since you can achieve the same, and more (including what you asked) with `--print-to-file`
