### ISSUE TITLE
[orf:tvthek] treat single videos as single videos rather than playlists with only 1 playlist item

### ISSUE THREAD

**Issue by chrizilla** [yt-dlp/yt-dlp#7268]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Austria:yes, worldwide:maybe

### note

Almost all URLs expire within 7 days after broadcast so new URLs might be required.

### Provide a description that is worded well enough to be understood

From my experience, the [orf:tvthek] extractor always treats downloads as playlists.
In other words, single videos (example [URL](https://tvthek.orf.at/profile/Weltjournal/5298609/WELTjournal-Edward-Snowden-alles-fuer-die-Wahrheit/14181784)) are treated as playlists with only 1 playlist item.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp --no-config -v -f w --test --paths "c:\#" "https://tvthek.orf.at/profile/Weltjournal/5298609/WELTjournal-Edward-Snowden-alles-fuer-die-Wahrheit/14181784"
[debug] Command-line config: ['--no-config', '-v', '-f', 'w', '--test', '--paths', 'c:\\#', 'https://tvthek.orf.at/profile/Weltjournal/5298609/WELTjournal-Edward-Snowden-alles-fuer-die-Wahrheit/14181784']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2023.06.05.155301 [59d9fe083] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.05.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1840 extractors
[orf:tvthek] Extracting URL: https://tvthek.orf.at/profile/Weltjournal/5298609/WELTjournal-Edward-Snowden-alles-fuer-die-Wahrheit/14181784
[orf:tvthek] 14181784: Downloading webpage
[download] Downloading playlist: 14181784
[orf:tvthek] 15408251: Downloading hls-Q1A-Niedrig m3u8 manifest
[orf:tvthek] 15408251: Downloading hls-Q4A-Mittel m3u8 manifest
[orf:tvthek] 15408251: Downloading hls-Q6A-Hoch m3u8 manifest
[orf:tvthek] 15408251: Downloading hls-Q8C-Sehr hoch m3u8 manifest
[orf:tvthek] 15408251: Downloading hls-QXB-Adaptiv m3u8 manifest
[orf:tvthek] 15408251: Downloading f4m manifest
[orf:tvthek] 15408251: Downloading f4m manifest
[orf:tvthek] 15408251: Downloading f4m manifest
[orf:tvthek] 15408251: Downloading f4m manifest
[orf:tvthek] 15408251: Downloading f4m manifest
[orf:tvthek] 15408251: Downloading dash-Q1A-Niedrig mpd manifest
[orf:tvthek] 15408251: Downloading dash-Q4A-Mittel mpd manifest
[orf:tvthek] 15408251: Downloading dash-Q6A-Hoch mpd manifest
[orf:tvthek] 15408251: Downloading dash-Q8C-Sehr hoch mpd manifest
[orf:tvthek] 15408251: Downloading dash-QXB-Adaptiv mpd manifest
[orf:tvthek] Playlist 14181784: Downloading 1 items of 1
[download] Downloading item 1 of 1
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[info] 15408251: Downloading 1 format(s): hds-Q1A-Niedrig-431
[debug] Invoking f4m downloader on "https://apasfiis.sf.apa.at/cms-worldwide_nas/_definst_/nas/cms-worldwide/online/2023-06-07_2328_tl_02_WELTjournal---E_____14181784__o__5455949046__s15408251_1__ORF2HD_23275515P_00170811P_Q1A.3gp/manifest.f4m"
[download] c:\#\WELTjournal +： Edward Snowden - alles für die Wahrheit [15408251].flv has already been downloaded
[download] 100% of  570.98KiB
[download] Finished downloading playlist: 14181784
```

### related
* #7065
* #6486
* #6984

**Comment by bashonly** [comment]
I posted a patch for this in https://github.com/yt-dlp/yt-dlp/issues/6984#issuecomment-1577398508

**Comment by seproDev** [comment]
The tvthek is no longer available. I believe this is no longer an issue with the new orf:on extractor.
