### ISSUE TITLE
How to download audio in formats other than .webm in youtube

### ISSUE THREAD

**Issue by Lancer498** [yt-dlp/yt-dlp#7269]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Using the command "yt-dlp -f (format) [video URL]" tells me that the format is not available. I have ffmpeg installed AND in the same folder as ty-dlp.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '-f', 'flac', 'https://youtu.be/Nuc1eXMPxkU
']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8 (No VT), erro
r utf-8 (No VT), screen utf-8 (No VT)
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-7-6.1.7601-SP1 (OpenSSL 1.
1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 4.3, ffprobe git-2020-06-17-0b3bd00
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, m
utagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releas
es/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
Current Build Hash: 5590c57bd0433ed239a2deaaf92e2ad6f37fe50f53664c821575cafe106a
9421
yt-dlp is up to date (stable@2023.03.04)
[youtube] Extracting URL: https://youtu.be/Nuc1eXMPxkU
[youtube] Nuc1eXMPxkU: Downloading webpage
[youtube] Nuc1eXMPxkU: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec
:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source
, vcodec:vp9.2(10), channels, acodec, lang, proto, filesize, fs_approx, tbr, vbr
, abr, asr, vext, aext, hasaud, id
ERROR: [youtube] Nuc1eXMPxkU: Requested format is not available. Use --list-form
ats for a list of available formats
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1518, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1615, in __extract_info
  File "yt_dlp\YoutubeDL.py", line 1674, in process_ie_result
  File "yt_dlp\YoutubeDL.py", line 2743, in process_video_result
yt_dlp.utils.ExtractorError: [youtube] Nuc1eXMPxkU: Requested format is not avai
lable. Use --list-formats for a list of available formats
```

**Comment by Lancer498** [comment]
The answer was in the --list-formats command, I was using it incorrectly. Apologies

**Comment by gamer191** [comment]
`--extract-audio --audio-format flac`
Although I'm not sure if you'd get any of the benefts of flac, since youtube stores videos in a lossy format :(

**Comment by Lancer498** [comment]
> `--extract-audio --audio-format flac` Although I'm not sure if you'd get any of the benefts of flac, since youtube stores videos in a lossy format :(

Thank you for your reply, that also helps. Yeah, you're completely correct. I was mostly using .flac as an example.
