### ISSUE TITLE
[Question] original_url global saved if generic extractor was used?

### ISSUE THREAD

**Issue by kr4ssi** [yt-dlp/yt-dlp#727]
```py
#!/usr/bin/env python

from __future__ import unicode_literals
import sys
import json
import struct
import yt_dlp

class MyLogger:
    def __init__(self, data):
        self.data = data
    def message(self, level, msg):
        print (msg)
    def debug(self, msg):
        pass
    def warning(self, msg):
        pass
    def error(self, msg):
        pass

def getMessage(msg = None):
    if msg is None:
        rawLength = sys.stdin.buffer.read(4)
        if len(rawLength) == 0:
            sys.exit(0)
        length = struct.unpack('@I', rawLength)[0]
        msg = json.loads(sys.stdin.buffer.read(length).decode('utf-8'))
    logger = MyLogger(msg)
    action = msg.get('action')
    {
        'youtube-dl': lambda: ytDL(msg.get('url'), logger),
    }.get(action, lambda: logger.error(f'there is no such an action {action}'))()

def ytDL(url, logger):
    with yt_dlp.YoutubeDL({
        'logger': logger,
        'ignoreerrors': True
    }) as ydl:
        info = ydl.extract_info(url, False)
        if info is not None:
            #logger.message('info', ydl.sanitize_info(info))
            logger.message('info', ydl.sanitize_info(info).get('original_url'))

getMessage({'action': 'youtube-dl', 'url': 'https://www.youtube.com/watch?v=BaW_jenozKc'})
getMessage({'action': 'youtube-dl', 'url': 'https://www.google.com'})
getMessage({'action': 'youtube-dl', 'url': 'https://www.youtube.com/watch?v=xcJtL7QggTI'})
```

ignore the mess, but this prints:
> https://www.youtube.com/watch?v=BaW_jenozKc
> https://www.google.com

Mind that the *second* line doesn't print anything at all.

**Comment by pukkandan** [comment]
works for me
```py
>>> #!/usr/bin/env python
>>>
>>> from __future__ import unicode_literals
>>> import sys
>>> import json
>>> import struct
>>> import yt_dlp
>>>
>>> class MyLogger:
...     def __init__(self, data):
...         self.data = data
...     def message(self, level, msg):
...         print (msg)
...     def debug(self, msg):
...         pass
...     def warning(self, msg):
...         pass
...     def error(self, msg):
...         pass
...
>>> def getMessage(msg = None):
...     if msg is None:
...         rawLength = sys.stdin.buffer.read(4)
...         if len(rawLength) == 0:
...             sys.exit(0)
...         length = struct.unpack('@I', rawLength)[0]
...         msg = json.loads(sys.stdin.buffer.read(length).decode('utf-8'))
...     logger = MyLogger(msg)
...     action = msg.get('action')
...     {
...         'youtube-dl': lambda: ytDL(msg.get('url'), logger),
...     }.get(action, lambda: logger.error(f'there is no such an action {action}'))()
...
>>> def ytDL(url, logger):
...     with yt_dlp.YoutubeDL({
...         'logger': logger,
...         'ignoreerrors': True
...     }) as ydl:
...         info = ydl.extract_info(url, False)
...         if info is not None:
...             #logger.message('info', ydl.sanitize_info(info))
...             logger.message('info', ydl.sanitize_info(info).get('original_url'))
...
>>> getMessage({'action': 'youtube-dl', 'url': 'https://www.youtube.com/watch?v=BaW_jenozKc'})
https://www.youtube.com/watch?v=BaW_jenozKc
>>> getMessage({'action': 'youtube-dl', 'url': 'https://www.google.com'})
>>> getMessage({'action': 'youtube-dl', 'url': 'https://www.youtube.com/watch?v=xcJtL7QggTI'})
https://www.youtube.com/watch?v=xcJtL7QggTI
```

**Comment by kr4ssi** [comment]
Exactly the same code prints for me the above. Just did a pull, still the same.

**Comment by pukkandan** [comment]
Is this the only code you are running? Set your logger to print all the messages, run this is a fresh instance of python interpretter and show me the outputs

**Comment by kr4ssi** [comment]
'''
Python 3.8.10 (default, Jun  2 2021, 10:49:15)
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from __future__ import unicode_literals
>>> import sys
>>> import json
>>> import struct
>>> import yt_dlp
>>>
>>> class MyLogger:
...     def __init__(self, data):

...         self.data = data
...     def message(self, level, msg):
...         print (level, msg)
...     def debug(self, msg):
...         self.message('debug', msg)
...     def warning(self, msg):
...         self.message('debug', msg)
...     def error(self, msg):
...         self.message('debug', msg)
...
>>> def getMessage(msg = None):
...     if msg is None:
...         rawLength = sys.stdin.buffer.read(4)
...         if len(rawLength) == 0:
...             sys.exit(0)
...         length = struct.unpack('@I', rawLength)[0]
...         msg = json.loads(sys.stdin.buffer.read(length).decode('utf-8'))
...     logger = MyLogger(msg)
...     action = msg.get('action')
...     {
...         'youtube-dl': lambda: ytDL(msg.get('url'), logger),
...     }.get(action, lambda: logger.error(f'there is no such an action {action}'))()
...
>>> def ytDL(url, logger):
...     with yt_dlp.YoutubeDL({
...         'logger': logger,
...         'ignoreerrors': True
...     }) as ydl:
...         info = ydl.extract_info(url, False)
...         if info is not None:
...             #logger.message('info', ydl.sanitize_info(info))
...             logger.message('info', ydl.sanitize_info(info).get('original_url'))
...
>>> getMessage({'action': 'youtube-dl', 'url': 'https://www.youtube.com/watch?v=BaW_jenozKc'})
debug [youtube] BaW_jenozKc: Downloading webpage
debug [youtube] BaW_jenozKc: Downloading android player API JSON
info https://www.youtube.com/watch?v=BaW_jenozKc
>>> getMessage({'action': 'youtube-dl', 'url': 'https://www.google.com'})
debug [generic] www.google: Requesting header
debug [generic] Falling back on generic information extractor.
debug [generic] www.google: Downloading webpage
debug [generic] www.google: Extracting information
debug [redirect] Following redirect to https://www.google.com/?output=search&gbv=1&sei=aFkdYeeLO6SNxc8P_Z6f6AU
debug [generic] ?output=search&gbv=1&sei=aFkdYeeLO6SNxc8P_Z6f6AU: Requesting header
debug [generic] Falling back on generic information extractor.
debug [generic] ?output=search&gbv=1&sei=aFkdYeeLO6SNxc8P_Z6f6AU: Downloading webpage
debug [generic] ?output=search&gbv=1&sei=aFkdYeeLO6SNxc8P_Z6f6AU: Extracting information
debug ERROR: Unsupported URL: https://www.google.com/?output=search&gbv=1&sei=aFkdYeeLO6SNxc8P_Z6f6AU
>>> getMessage({'action': 'youtube-dl', 'url': 'https://www.youtube.com/watch?v=xcJtL7QggTI'})
debug [youtube] xcJtL7QggTI: Downloading webpage
debug [youtube] xcJtL7QggTI: Downloading android player API JSON
info https://www.google.com
'''

**Comment by pukkandan** [comment]
ok, found the issue. It only happens when there is a redirect, hence why I couldn't reproduce

**Comment by kr4ssi** [comment]
Is it generally save to run it like this in a server-like program, or can there be any memoryleaks?

This is my whole code so far:
```
#!/usr/bin/env python

from __future__ import unicode_literals
import sys
import json
import struct
import yt_dlp

class MyLogger:
    def __init__(self, data):
        self.data = data
    def message(self, level, msg):
        encodedContent = json.dumps({
            'action': self.data.get('action'),
            'url': self.data.get('url'),
            'level': level,
            'msg': msg
        }).encode('utf-8')
        encodedLength = struct.pack('@I', len(encodedContent))
        sys.stdout.buffer.write(encodedLength)
        sys.stdout.buffer.write(encodedContent)
        sys.stdout.buffer.flush()
    def debug(self, msg):
        self.message('debug', msg)
    def warning(self, msg):
        self.message('warning', msg)
    def error(self, msg):
        self.message('error', msg)

def getMessage(msg = None):
    if msg is None:
        rawLength = sys.stdin.buffer.read(4)
        if len(rawLength) == 0:
            sys.exit(0)
        length = struct.unpack('@I', rawLength)[0]
        msg = json.loads(sys.stdin.buffer.read(length).decode('utf-8'))
    logger = MyLogger(msg)
    action = msg.get('action')
    {
        'youtube-dl': lambda: ytDL(msg.get('url'), logger),
    }.get(action, lambda: logger.error(f'there is no such an action {action}'))()

def ytDL(url, logger):
    with yt_dlp.YoutubeDL({
        'logger': logger,
        'ignoreerrors': True
    }) as ydl:
        info = ydl.extract_info(url, False)
        if info is not None:
            logger.message('info', ydl.sanitize_info(info))

getMessage({'action': 'youtube-dl', 'url': 'https://www.youtube.com/watch?v=BaW_jenozKc'})

while True:
    getMessage()

```

Still new to python, will gladly use any hints.

**Comment by pukkandan** [comment]
All the normal yt-dlp messages go to "verbose", not "message". Idk why, but that is how ytdl works

**Comment by kr4ssi** [comment]
You mean "debug"?

**Comment by pukkandan** [comment]
yeah, `debug`, sorry

**Comment by kr4ssi** [comment]
In case anyone wonders what I'm trying:
https://github.com/mdn/webextensions-examples/tree/master/native-messaging
```
const port = browser.runtime.connectNative("ping_pong")

port.onMessage.addListener((response) => {
  console.log('Received:', response)
})

browser.browserAction.onClicked.addListener(() => {
  browser.tabs.query({
    currentWindow: true, active: true
  }).then(([{ url }]) => {
    console.log('Sending:', url)
    port.postMessage({
      action: 'youtube-dl',
      url
    })
  }).catch(console.error)
})
```
![grafik](https://user-images.githubusercontent.com/44404263/129960193-d047be54-4204-4e12-905f-0f8b0fd76a23.png)

**Comment by pukkandan** [comment]
Seems this has not been fully resolved
