### ISSUE TITLE
[Feature Request] Grab files based on user-specified extension?

### ISSUE THREAD

**Issue by barkoder** [yt-dlp/yt-dlp#7270]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

I know that this is technically outside the scope of yt-dlp's intended usage but how do I select and download "non-video" files?

For example, yt-dlp's hitherto(#7267) generic extractor is able to grab the [video from this link](https://pixeldrain.com/u/VFjemoqC) .
But this `.rar` [link containing the same video on the same website](https://pixeldrain.com/u/dPhwDLsX) doesn't get grabbed by yt-dlp.

I understand that `.rar` files are not videos so yt-dlp omits them. 

But...it's just that...yt-dlp does such a good job parsing the javascript on the webpage and picking up on what it needs to download, it hurts so much to watch yt-dlp fail when downloading a regular file instead of a video(especially on the same website), just because yt-dlp doesn't consider those type of files "downloadable". Then I have to open a webpage on my high-memory-usage web browser, and download that file manually(painfully).

I would greatly appreciate it if there were some way to get yt-dlp to grab that file, by say, specifying an additional flag like `--non-video-extension rar` along with `-F` so yt-dlp would list all rar files on a given webpage, and I could use `-f` to specify which `.rar` file I want.
It doesn't just have to be rar either. It could be anything - `.7z` , `.zip` , `.whatever` .
Also obviously such a flag should invalidate `--remux-video` , `--add-metadata` and other post-processing arguments, if specified.

Or maybe there is some way to use `--match-filters` so that yt-dlp picks up `.zip` or `.rar` or `.7z` files? idk.

Again I understand that this is outside the scope of yt-dlp, but this feature would *so* **so** useful.

Thank you so much for all your work!

PS: I didn't know if I should tag this under "Question" or "Feature Request". But as the "Feature Request" checklist doesn't have the "Make sure your feature request isn't a question" item on it, and as the "Ask a Question" checklist *does* have a "make sure your question isn't a feature request" item on it, I thought I'd file this ticket as a Feature Request. Apologies if this ticket doesn't belong here 

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
THIS WORKS

$ yt-dlp -wv --no-cache-dir --geo-bypass https://pixeldrain.com/u/VFjemoqC -F
[debug] Command-line config: ['-wv', '--no-cache-dir', '--geo-bypass', 'https://pixeldrain.com/u/VFjemoqC', '-F']
[debug] yt-dlp version nightly@2023.06.08.184733 [d1795f4a6] (zip)
[debug] Python 3.10.9 (CPython x86_64 64bit) - Linux
[debug] exe versions: ffmpeg 5.1.2-1 (setts), ffprobe 5.1.2-1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.11.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.46.0, pyxattr-0.7.2, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1841 extractors
[generic] Extracting URL: https://pixeldrain.com/u/VFjemoqC
[generic] VFjemoqC: Downloading webpage
[generic] VFjemoqC: Extracting information
[debug] Looking for embeds
[debug] Identified a twitter:player iframe
[generic] Extracting URL: https://pixeldrain.com/api/file/VFjemoqC
[generic] VFjemoqC: Downloading webpage
[debug] Identified a direct video link
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[info] Available formats for VFjemoqC:
ID   EXT           RESOLUTION │ PROTO │ VCODEC  ACODEC
───────────────────────────────────────────────────────
fmp4 unknown_video unknown    │ https │ unknown unknown


---------------------------------------------------------------------------------

BUT THIS FAILS. SAD :(

$ yt-dlp -wv --no-cache-dir --geo-bypass https://pixeldrain.com/u/dPhwDLsX -F
[debug] Command-line config: ['-wv', '--no-cache-dir', '--geo-bypass', 'https://pixeldrain.com/u/dPhwDLsX', '-F']
[debug] yt-dlp version nightly@2023.06.08.184733 [d1795f4a6] (zip)
[debug] Python 3.10.9 (CPython x86_64 64bit) - Linux
[debug] exe versions: ffmpeg 5.1.2-1 (setts), ffprobe 5.1.2-1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.11.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.46.0, pyxattr-0.7.2, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1841 extractors
[generic] Extracting URL: https://pixeldrain.com/u/dPhwDLsX
[generic] dPhwDLsX: Downloading webpage
[generic] dPhwDLsX: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://pixeldrain.com/u/dPhwDLsX
Traceback (most recent call last):
  File "/usr/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1552, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/bin/yt-dlp/yt_dlp/YoutubeDL.py", line 1628, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/bin/yt-dlp/yt_dlp/extractor/common.py", line 704, in extract
    ie_result = self._real_extract(url)
  File "/usr/bin/yt-dlp/yt_dlp/extractor/generic.py", line 2568, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://pixeldrain.com/u/dPhwDLsX
```

**Comment by bashonly** [comment]
> this is technically outside the scope of yt-dlp's intended usage

Fully out of scope IMO, not just technically

**Comment by gamer191** [comment]
Just replace the `/u/` in the URL with `/api/file/` (eg `https://pixeldrain.com/api/file/dPhwDLsX`)

**Comment by barkoder** [comment]
Thanks @gamer191 that is certainly a more convenient way to use pixeldrain.
