### ISSUE TITLE
Error when downloading a playlist from Youtube!

### ISSUE THREAD

**Issue by ritesh-29** [yt-dlp/yt-dlp#7275]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Provide a description that is worded well enough to be understood

While trying to download a playlist from YouTube the program shows an error "ERROR: Unsupported URL: <playlist URL>".
The program works fine when downloading a single video or manually downloading the video from the playlist.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [x] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://youtube.com/playlist\\?list\\=PLLy_2iUCG87CNafffzNZPVa9rW-QmOmEv']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (pip)
[debug] Python 3.11.3 (CPython x86_64 64bit) - macOS-13.4-x86_64-i386-64bit (OpenSSL 1.1.1u  30 May 2023)
[debug] exe versions: rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
yt-dlp is up to date (stable@2023.03.04)
[generic] Extracting URL: https://youtube.com/playlist\?list\=PLLy_2iUCG87CNafffzNZPVa9rW-QmOmEv
[generic] playlist\?list\=PLLy_2iUCG87CNafffzNZPVa9rW-QmOmEv: Downloading webpage
[redirect] Following redirect to https://www.youtube.com/playlist%5C?list%5C=PLLy_2iUCG87CNafffzNZPVa9rW-QmOmEv
[generic] Extracting URL: https://www.youtube.com/playlist%5C?list%5C=PLLy_2iUCG87CNafffzNZPVa9rW-QmOmEv
[generic] playlist\?list\=PLLy_2iUCG87CNafffzNZPVa9rW-QmOmEv: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] playlist\?list\=PLLy_2iUCG87CNafffzNZPVa9rW-QmOmEv: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://www.youtube.com/playlist%5C?list%5C=PLLy_2iUCG87CNafffzNZPVa9rW-QmOmEv
Traceback (most recent call last):
  File "/usr/local/Cellar/yt-dlp/2023.3.4/libexec/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1518, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/yt-dlp/2023.3.4/libexec/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1594, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/yt-dlp/2023.3.4/libexec/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 694, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/yt-dlp/2023.3.4/libexec/lib/python3.11/site-packages/yt_dlp/extractor/generic.py", line 2510, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.youtube.com/playlist%5C?list%5C=PLLy_2iUCG87CNafffzNZPVa9rW-QmOmEv
```

**Comment by bashonly** [comment]
Your shell is auto-escaping the special characters in the URL by adding backslashes, and then you must be quoting the URL on top of that, which causes it not to be parsed/matched properly. Either pass the URL to yt-dlp with special characters escaped, or quote the URL, don't do both

**Comment by ritesh-29** [comment]
Understood, thanks for help!!!
