### ISSUE TITLE
Pls add function: Auto save info of videos

### ISSUE THREAD

**Issue by downleak** [yt-dlp/yt-dlp#7276]
Pls add a function: 
Auto save info of all downloaded videos in one log file, 
or in diff .txt file for each video.
.
Need infos: The video link & title, Uploader link & name, Video Uploaded timestamp, Video Duration, 
the files I saved for the link (filetype, resolution, filesize), for example, mp4 3840x2160 1.00G, aac 128k 30.00M, srt en 25.00K

**Comment by bashonly** [comment]
```
--write-info-json               Write video metadata to a .info.json file
                                (this may contain personal information)

--print-to-file [WHEN:]TEMPLATE FILE
                                Append given template to the file. The
                                values of WHEN and TEMPLATE are same as that
                                of --print. FILE uses the same syntax as the
                                output template. This option can be used
                                multiple times
```

Do not remove the issue template!!
>  [x] I understand that I will be blocked if I intentionally remove or skip any mandatory* field
