### ISSUE TITLE
[iqiyi] No video formats found!

### ISSUE THREAD

**Issue by Ciara-Aa** [yt-dlp/yt-dlp#7284]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Việt Nam

### Provide a description that is worded well enough to be understood

After downloading 2 videos (requires VIP) this error appeared and after waiting some time I ran the command again I downloaded the next 2 videos and this error appeared again

This error does not appear on free videos

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-Uv', '--downloader', 'aria2c', '--cookies', 'C:\
\Users\\Administrator\\Documents\\iq.com_cookies.txt', '--download-archive', 'do
w.txt', 'https://www.iq.com/album/van-tuong-truyen-2023-1jdppwp8q1d?lang=vi_vn']

[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8 (No VT), erro
r utf-8 (No VT), screen utf-8 (No VT)
[debug] yt-dlp version stable@2023.03.04 [392389b7d]
[debug] Lazy loading extractors is disabled
[debug] Python 3.11.3 (CPython AMD64 64bit) - Windows-2012ServerR2-6.3.9600-SP0
(OpenSSL 1.1.1t  7 Feb 2023)
[debug] exe versions: ffmpeg N-110612-g2953ebe7b6-20230515 (setts), ffprobe N-11
0612-g2953ebe7b6-20230515, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.18.0, certifi-2023.05.07, mutagen-1.46.
0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1840 extractors
[debug] Loading archive file 'dow.txt'
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releas
es/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
yt-dlp is up to date (stable@2023.03.04)
[iq.com:album] Extracting URL: https://www.iq.com/album/van-tuong-truyen-2023-1j
dppwp8q1d?lang=vi_vn
[iq.com:album] 1jdppwp8q1d: Downloading webpage
[download] Downloading playlist: Vân Tuong Truy?n
[iq.com:album] 1jdppwp8q1d: Downloading video list episodes 1-24
[iq.com:album] 1jdppwp8q1d: Downloading video list episodes 25-36
[iq.com:album] Playlist Vân Tuong Truy?n: Downloading 36 items of 36
[download] Vân Tuong Truy?n has already been recorded in the archive
[download] The Ingenious One - Episode 2 has already been recorded in the archiv
e
[download] The Ingenious One - Episode 3 has already been recorded in the archiv
e
[download] The Ingenious One - Episode 4 has already been recorded in the archiv
e
[download] The Ingenious One - Episode 5 has already been recorded in the archiv
e
[download] Downloading item 6 of 36
[iq.com] Extracting URL: https://www.iq.com/play/van-tuong-truyen-tap-6-mf4357z4
fg?lang=vi_vn
[iq.com] mf4357z4fg: Downloading webpage
[debug] Loading iq.player_js from cache
[iq.com] mf4357z4fg: Downloading VIP data
[debug] Loading iq.player_js from cache
[iq.com] mf4357z4fg: Executing signature code (this may take a couple minutes)
[debug] [iq.com] PhantomJS command line: phantomjs "--ssl-protocol=any" "C:\User
s\ADMINI~1\AppData\Local\Temp\2\tmpvekoz452"
[iq.com] mf4357z4fg: Downloading initial video format info
ERROR: [iq.com] mf4357z4fg: No video formats found!; please report this issue on
  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue
 template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-
packages\yt_dlp\YoutubeDL.py", line 1552, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-
packages\yt_dlp\YoutubeDL.py", line 1649, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-
packages\yt_dlp\YoutubeDL.py", line 1708, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-
packages\yt_dlp\YoutubeDL.py", line 2650, in process_video_result
    self.raise_no_formats(info_dict)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-
packages\yt_dlp\YoutubeDL.py", line 1066, in raise_no_formats
    raise ExtractorError(msg, video_id=info['id'], ie=info['extractor'],
yt_dlp.utils.ExtractorError: [iq.com] mf4357z4fg: No video formats found!; pleas
e report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out
 the appropriate issue template. Confirm you are on the latest version using  yt
-dlp -U
```

**Comment by bashonly** [comment]
`iq.com` has a very similar (the same?) issue, and here is the explanation (from https://github.com/yt-dlp/yt-dlp/issues/5702#issuecomment-1384245060):

>>> Iqiyi appears to check if the simultaneous stream limit is hit periodically. If it senses it's been hit, it will block the entire account from streaming until a stream has been closed + 10 minute penalty. Users can see the 10 minute message if they try to stream something on a browser. Downloading full videos minutes within each other apparently counts as a simultaneous stream.

>>> The standard account allows 2 simultaneous streams, and the premium one allows for 4. ... I hit [this] problem after 4 downloads, and I have the premium one.

>>> I set my script to put a 15 minute interval between every 4 downloads(so the penalty time expires before it tries to download new episodes), but it's not a great solution. Would probably be better if yt-dlp could detect the error message and set the timeout internally.

As I wrote in https://github.com/yt-dlp/yt-dlp/issues/2813#issuecomment-1385397993, I don't think there is anything we can really do about the rate limit other than output a more descriptive/accurate error message
