### ISSUE TITLE
yt-dlp as tool generate a list of yt video titels

### ISSUE THREAD

**Issue by blub4747** [yt-dlp/yt-dlp#7296]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Hello yt-dlp,
Just a quick question.
I am trying to generate a list of video titles from a youtube channel and I want to be able to edit the list in some text editor.

Can I use yt-dlp for this purpose ? if yes how do I that please ?
Thx, blub4747

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
`yt-dlp --flat-playlist --print-to-file title "list.txt" "https://www.youtube.com/@LinusTechTips/videos"`

**Comment by blub4747** [comment]
That was spot on! Thank you very much!!!
