### ISSUE TITLE
[TF1] "This video is DRM protected" for videos download attempts

### ISSUE THREAD

**Issue by Totorrr** [yt-dlp/yt-dlp#7299]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

France

### Provide a description that is worded well enough to be understood

Hello, 

it seems that as of today, the tf1 (TF1) website has moved to a DRM protected streaming platform. `yt-dlp` cannot download videos there any more. 

Example: 
```
yt-dlp 'https://www.tf1.fr/lci/le-temps-de-linfo/videos/mort-de-silvio-berlusconi-une-vie-de-succes-daffaires-et-de-polemiques-52186276.html'
[TF1] Extracting URL: https://www.tf1.fr/lci/le-temps-de-linfo/videos/mort-de-silvio-berlusconi-une-vie-de-succes-daffa...miques-52186276.html
[TF1] mort-de-silvio-berlusconi-une-vie-de-succes-daffaires-et-de-polemiques-52186276: Downloading JSON metadata
[wat.tv] Extracting URL: wat:13994339
[wat.tv] 13994339: Downloading JSON metadata
[wat.tv] 13994339: Downloading MPD manifest
ERROR: [wat.tv] 13994339: This video is DRM protected
```

I am opening this issue to ask if there could be a workaround to implement for yt-dlp since this website change. 

Thank you, 

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.tf1.fr/lci/le-temps-de-linfo/videos/mort-de-silvio-berlusconi-une-vie-de-succes-daffaires-et-de-polemiques-52186276.html']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (debian*)
[debug] Python 3.9.2 (CPython x86_64 64bit) - Linux-5.18.0-0.deb11.4-amd64-x86_64-with-glibc2.31 (OpenSSL 1.1.1n  15 Mar 2022, glibc 2.31)
[debug] exe versions: ffmpeg 5.0.1-1 (fdk,setts), ffprobe 5.0.1-1
[debug] Optional libraries: Cryptodome-3.9.7, brotli-1.0.9, certifi-2020.06.20, mutagen-1.45.1, sqlite3-2.6.0, websockets-8.1
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
yt-dlp is up to date (stable@2023.03.04)
[TF1] Extracting URL: https://www.tf1.fr/lci/le-temps-de-linfo/videos/mort-de-silvio-berlusconi-une-vie-de-succes-daffaires-et-de-polemiques-52186276.html
[TF1] mort-de-silvio-berlusconi-une-vie-de-succes-daffaires-et-de-polemiques-52186276: Downloading JSON metadata
[wat.tv] Extracting URL: wat:13994339
[wat.tv] 13994339: Downloading JSON metadata
[wat.tv] 13994339: Downloading MPD manifest
ERROR: [wat.tv] 13994339: This video is DRM protected
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/yt_dlp/YoutubeDL.py", line 1518, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/yt_dlp/YoutubeDL.py", line 1615, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/lib/python3/dist-packages/yt_dlp/YoutubeDL.py", line 1727, in process_ie_result
    return self.process_ie_result(
  File "/usr/lib/python3/dist-packages/yt_dlp/YoutubeDL.py", line 1674, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/usr/lib/python3/dist-packages/yt_dlp/YoutubeDL.py", line 2615, in process_video_result
    self.raise_no_formats(info_dict)
  File "/usr/lib/python3/dist-packages/yt_dlp/YoutubeDL.py", line 1046, in raise_no_formats
    raise ExtractorError(msg, video_id=info['id'], ie=info['extractor'],
yt_dlp.utils.ExtractorError: [wat.tv] 13994339: This video is DRM protected
```

**Comment by bashonly** [comment]
See https://github.com/ytdl-org/youtube-dl/issues/32299#issuecomment-1587425785

**Comment by bashonly** [comment]
per the [upstream issue's findings](https://github.com/ytdl-org/youtube-dl/issues/32299#issuecomment-1596234196), everything seems to now be DRM-protected besides short clips/previews. Closing as DRM/wontfix, if someone wants to fix the extractor for non-DRM content, that can be tracked in #7303

**Comment by gamer191** [comment]
I feel like it's a bit early to say that the DRM-free streams aren't available, given I found a workaround very recently. I'm going to investigate @vangelis66's message sometime soon, and see if my workaround is truly broken.

I'm not gonna reopen this issue though, because I think it's better to close this for now, and reopen if we manage to find a working workaround in the upstream issue
