### ISSUE TITLE
[Feature request] Detect subs tracks from MPD/ISM manifests

### ISSUE THREAD

**Issue by DarbyCrash** [yt-dlp/yt-dlp#73]
## Checklist

- [ ] I'm reporting a broken site support issue
- [X] I've verified that I'm running yt-dlp version **2021.02.09**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar bug reports including closed ones
- [X] I've read bugs section in FAQ

## Verbose log

```
PASTE VERBOSE LOG HERE

```

## Description

Hello! YTDLC cannot detect subtitle tracks from MPD/ISM manifests.

I leave a example of MPD manifest (need italian ip):

`https://voddashhttps.cb.ticdn.it/videoteca2/V3/SingleTitle/2019/12/60015354/DASH/20167939/20167939_HD_ANSN.mpd`

**Comment by shirt-dev** [comment]
This is not a bug, this is a feature request.

**Comment by DarbyCrash** [comment]
> This is not a bug, this is a feature request.

I think it's a bug because subtitles are tracks like video and audio and must to be available.

**Comment by shirt-dev** [comment]
Subtitles in DASH/ISM exist inside MP4 files and require additional processing. If you want to implement this feature, open a pull request.

**Comment by pukkandan** [comment]
Yes, this is a feature request. But no need to close and reopen. I'll look into it

**Comment by DarbyCrash** [comment]
I'll take a look to the code, maybe I can give a hand about this.

**Comment by anaveem** [comment]
If it helps, from a reverse engineering standpoint, perhaps look at how these subtitle tracks are implemented in the shaka-packager used by all CBS/Paramount+ streams: https://github.com/google/shaka-packager
