### ISSUE TITLE
Is it possible: Embed into a video's "metadata" field the info that we can get with `print-to-file`

### ISSUE THREAD

**Issue by phere-x** [yt-dlp/yt-dlp#7302]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

---
Is it possible to have info that we can get with `print-to-file` embedded into the video file in the metadata field? I don't want to always have an extra file and having the info inside the video container works just as well.

**Comment by bashonly** [comment]
also maybe https://github.com/yt-dlp/yt-dlp#modifying-metadata

**Comment by phere-x** [comment]
I've found this adds the info I need into description. But it maxes out at 255 characters. 
`yt-dlp C0DPdy98e4c --embed-metadata --parse-metadata "%(title)s %(id)s %(duration_string)s %(upload_date)s %(format_note)s %(filesize_approx)s %(vcodec)s %(webpage_url)s %(thumbnail)s %(channel)s %(uploader)s %(uploader_id)s %(uploader_url)s %(is_live)s %(live_status)s %(ext)s %(duration)s %(aspect_ratio)s %(resolution)s %(fps)s %(format)s %(format_id)s %(width)s %(height)s %(tbr)s %(dynamic_range)s %(vbr)s %(acodec)s %(abr)s %(asr)s %(audio_channels)s %(display_id)s %(fulltitle)s %(description)s %(age_limit)s %(availability)s %(was_live)s %(categories)s %(tags)s %(playable_in_embed)s %(extractor)s %(extractor_key)s %(epoch)s:%(description)s"`

I've manually added data to `description` field & it has successfully included all the data so it is possible. Is this a YT-DLP limit?
(this is the manual cmd I used `exiftool -overwrite_original -Description="description_data" "input_video"`)

**Comment by pukkandan** [comment]
We use ffmpeg, not exiftool. Try with ffmpeg and if disaparity still exists, post verbose log.

**Comment by phere-x** [comment]
Set description info manually with ffmpeg & all the data managed to show up.

Here is verbose log https://pastebin.com/Urqmw8hr

Output data of `--print-to-file`: https://pastebin.com/agh3S3TE

Running `ffprobe -hide_banner "TEST VIDEO [C0DPdy98e4c].webm"`: https://pastebin.com/9mMy2ckU

Some values in DESCRIPTION show up as `NA`, but these values are present in the file I produced with `--print-to-file`

**Comment by pukkandan** [comment]
> Set description info manually with ffmpeg & all the data managed to show up.

Could you show me the command you used for that? I can't reproduce.



> Some values in DESCRIPTION show up as `NA`, but these values are present in the file I produced with `--print-to-file`

parse-metadata happens before format selection by default and so format-specific fields don't exist yet. Change it to `--parse-metadata video:"%(title)s ...`

**Comment by phere-x** [comment]
> Could you show me the command you used for that? I can't reproduce.

```
#!/bin/bash

input_video=$1
metadata_file=$2

description=$(cat "$metadata_file")

ffmpeg -i "$input_video" -metadata DESCRIPTION="$description" some_metadata.mp4
```

**Comment by pukkandan** [comment]
You are re-coding it to mp4, while in original, it's webm. This is what's causing the disparity. It appears webm has limited size for the metadata fields.

**Comment by phere-x** [comment]
Ran the command again with `-S ext` to download it in mp4 (verbose logs: https://pastefs.com/pid/500130), the description field has same data as https://pastebin.com/9mMy2ckU.
