### ISSUE TITLE
Stripchat: Error: No active streams found

### ISSUE THREAD

**Issue by pro-ject143** [yt-dlp/yt-dlp#7305]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

UK

### Provide a description that is worded well enough to be understood

I've been trying all day to download streams but none are downloading.

C:\Program Files (x86)\WM Recorder-2\WM Recorder YT-2>TITLE WMDownload (1) 3

C:\Program Files (x86)\WM Recorder-2\WM Recorder YT-2>"C:\Users\User\AppData\Roaming\WM Recorder YT-DLP"\youtube-dl -o "C:\Users\User\Videos\WMR Recordings\Playlist Folders\WMR Recordings\13-%(title)s.%(ext)s"  --no-part --no-check-certificate -f best  --ignore-errors --ffmpeg-location "C:\Program Files (x86)\WM Recorder-2\WM Recorder YT-2\WM Converter Pro" "https://stripchat.com/Sunshine_Girll"
WARNING: "-f best" selects the best pre-merged format which is often not the best option.
         To let yt-dlp download and merge the best available formats, simply do not pass any format selection.
         If you know what you are doing and want only the best pre-merged format, use "-f b" instead to suppress this warning
[Stripchat] Extracting URL: https://stripchat.com/Sunshine_Girll
[Stripchat] Sunshine_Girll: Downloading webpage
ERROR: [Stripchat] Sunshine_Girll: Unable to find configuration for stream.; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

C:\Program Files (x86)\WM Recorder-2\WM Recorder YT-2>pause
Press any key to continue . . .

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
C:\Program Files (x86)\WM Recorder-2\WM Recorder YT-2>TITLE WMDownload (1) 3

C:\Program Files (x86)\WM Recorder-2\WM Recorder YT-2>"C:\Users\User\AppData\Roaming\WM Recorder YT-DLP"\youtube-dl -o "C:\Users\User\Videos\WMR Recordings\Playlist Folders\WMR Recordings\13-%(title)s.%(ext)s"  --no-part --no-check-certificate -f best  --ignore-errors --ffmpeg-location "C:\Program Files (x86)\WM Recorder-2\WM Recorder YT-2\WM Converter Pro" "https://stripchat.com/Sunshine_Girll"
WARNING: "-f best" selects the best pre-merged format which is often not the best option.
         To let yt-dlp download and merge the best available formats, simply do not pass any format selection.
         If you know what you are doing and want only the best pre-merged format, use "-f b" instead to suppress this warning
[Stripchat] Extracting URL: https://stripchat.com/Sunshine_Girll
[Stripchat] Sunshine_Girll: Downloading webpage
ERROR: [Stripchat] Sunshine_Girll: Unable to find configuration for stream.; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

C:\Program Files (x86)\WM Recorder-2\WM Recorder YT-2>pause
Press any key to continue . . .
```

**Comment by bashonly** [comment]
your log and your title are reporting 2 different errors. please add `-v` to your command and run again and post the complete output here

**Comment by gamer191** [comment]
Also, you posted a tiny incomplete log, and still didn't even bother reading it 🤦

**Comment by foreignBlade** [comment]
Fix in https://github.com/yt-dlp/yt-dlp/pull/7306

You can test by cloning and then doing `pip install -e /path/to/local/yt-dlp`

**Comment by pro-ject143** [comment]
Sorry, after filling out form, was not able to check back in immediately, had things to do.  It is difficult to perform the tasks you are requesting, not technically skilled. Just wanted to report it to try and get downloading streams to work again.

**Comment by bashonly** [comment]
@pro-ject143 run `yt-dlp --update-to nightly`

**Comment by pro-ject143** [comment]
okay

**Comment by pro-ject143** [comment]
Sorry, how do you run yt-dlp --update-to nightly? I have been checking this page and downloaded yt-dlp https://github.com/yt-dlp/yt-dlp#installation

Many thanks

**Comment by bashonly** [comment]
in your console, type `yt-dlp --update-to nightly` and press enter

**Comment by bashonly** [comment]
@pro-ject143 yes. and if it errors with `no such option: --update-to` you will have to run `yt-dlp -U` first, followed by `yt-dlp --update-to nightly`

**Comment by pro-ject143** [comment]
Many thanks

I updated in Windows Explorer. Unfortunately I am still getting the error message when I try to download a stream on WM Recorder YT 2.  Am I missing a step somewhere?

![Screenshot (67)](https://github.com/yt-dlp/yt-dlp/assets/112349169/2dcee23e-95b0-4b68-be86-23fee9a2e2ee)

**Comment by bashonly** [comment]
Don't use WM Recorder then. It probably has its own yt-dlp exe that it runs. Since WM Recorder is not open source and I don't see any sort of documentation or support for it besides a "customer support executable" for download on the site(!), I wouldn't know if it's even possible to update its copy of yt-dlp to nightly. This is going well beyond support for yt-dlp usage and getting off-topic now, sorry
