### ISSUE TITLE
How to entirely disable the 'output-na-placeholder' functionality?

### ISSUE THREAD

**Issue by 07416** [yt-dlp/yt-dlp#7307]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

>        --output-na-placeholder TEXT
>              Placeholder for unavailable fields in "OUTPUT TEMPLATE" (default: "NA")

I prefer using the `playlist_autonumber` output template by default. The feature is not supported on many sites, by default yt-dlp adds the `NA` string at its place in the filename.

Setting a blank "placeholder" `yt-dlp --output-na-placeholder ''` prefixes the downloaded files with a dot `.` , making them hidden on Linux. How to use no placeholder whatsoever?

additional information (reproduced in a Docker container):

```
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8 (No ANSI), error utf-8, screen utf-8 (No ANSI)
[debug] yt-dlp version stable@2023.03.04 [392389b7d]
[debug] Lazy loading extractors is disabled
[debug] Python 3.11.2 (CPython x86_64 64bit) - Linux-6.3.6-200.fc38.x86_64-x86_64-with-glibc2.37 (OpenSSL 3.0.8 7 Feb 2023, glibc 2.37)
[debug] exe versions: ffmpeg 6.0 (fdk,setts), ffprobe 6.0
[debug] Optional libraries: Cryptodome-3.17.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
```

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
There is too little information to reproduce this. Post a verbose log

**Comment by 07416** [comment]
> There is too little information to reproduce this. Post a verbose log

@bashonly Sorry, occurs due to the output template -- presumably intended behavior.

    /%(playlist_autonumber)s.%(title)s-%(id)s.%(ext)s 

When  `(playlist_autonumber)` doesn't apply yt-dlp starts the naming from `s.%(title)s-%(id)s.%(ext)s`, I suppose.

**Comment by bashonly** [comment]
you could do this
`%(playlist_autonumber|)s%(playlist_autonumber&.)s%(title)s-%(id)s.%(ext)s`
