### ISSUE TITLE
bash: /home/[user]/.local/bin/yt-dlp: No such file or directory

### ISSUE THREAD

**Issue by Menard01** [yt-dlp/yt-dlp#7310]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Installation on Linux Mint 21.1 without apparent issue with wget
when I run sudo yt-dlp -U the answer is good 
but if I try to download with any URL it returns this 
(bash: /home/[user]/.local/bin/yt-dlp: No such file or directory)
What can I do ? 

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
How did you install it exactly? from github? linux mint's package manager? pip?

can you show output of the following commands:
```
which yt-dlp
realpath "$(which yt-dlp)"
sudo which yt-dlp
sudo realpath "$(which yt-dlp)"
```

**Comment by Menard01** [comment]
The process was with wget as it is the one of Github how to ... here

sudo wget https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -O /usr/local/bin/yt-dlp
sudo chmod a+rx /usr/local/bin/yt-dlp

-------
which yt-dlp
/usr/local/bin/yt-dlp
realpath "$(which yt-dlp)"
/usr/local/bin/yt-dlp
sudo which yt-dlp
/usr/local/bin/yt-dlp
sudo realpath "$(which yt-dlp)"

Notice, I discovered that the download works when using sudo in front of the yt-dlp command

**Comment by bashonly** [comment]
You could try this, which I'd think is the easiest solution:
```shell
sudo mv /usr/local/bin/yt-dlp ~/.local/bin/yt-dlp
sudo chown username: ~/.local/bin/yt-dlp
```
(replace `username` with your username, but keep the `:` at the end)

and then only run yt-dlp under your user (not sudo/root), including when updating.

I think we should consider improving & merging https://github.com/yt-dlp/yt-dlp-wiki/pull/10

**Comment by Menard01** [comment]
What I can say is from this point of view, I had previously yt-dlp and it needed sudo only when updating, sudo yt-dlp -U so I wonder why something has changed, I copied Linux system 21.1 (without the home partition) with Timeshift from another external USB drive and at boot it failed to install a swap, is this the same issue with rights (?) 
I ll try your fix now

**Comment by Menard01** [comment]
I ve just checked that on Linux Mint 20.3 where yt-dlp was functionning well, I had the yt-dlp file in the /usr/local/bin folder, but I am going to see what was in the home/[user]/.local/bin

**Comment by Menard01** [comment]
Yes, it had allready the yt-dlp file in the user/.local ... I do

**Comment by bashonly** [comment]
did you try my suggestion though?

**Comment by Menard01** [comment]
I ve just done it and it works now as before $ yt-dlp :)
