### ISSUE TITLE
Will there be official 'Releases' again in the future?

### ISSUE THREAD

**Issue by humdingerb** [yt-dlp/yt-dlp#7329]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Last release was March 4th 2023. The releases were very frequent in the past...
Will there be releases in the future?

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by humdingerb** [comment]
Thanks, I didn't find that ticket when I was looking around.
A +1 on doing stable releases now and then. The Haiku operating system mounts software packages 'read-only', so yt-dlp cannot be self-updated via `--update`.

**Comment by gamer191** [comment]
@humdingerb nightly builds can be manually downloaded from https://github.com/yt-dlp/yt-dlp-nightly-builds/releases/latest

**Comment by humdingerb** [comment]
Thanks for that hint! That's workable to package a newer version from time to time. I hope there aren't too many breakages and regressions usually in nightlies... Stable releases are still very much appreciated. :)
