### ISSUE TITLE
I cannot install yt-dlp using any method on Linux Mint 19.3 - I am doing something wrong?

### ISSUE THREAD

**Issue by KyleRickards** [yt-dlp/yt-dlp#7343]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Hi

I am asking a question and I hope this is the best place as I don't think it appears anywhere else after going through all the other sections. I cannot confirm I am on 2023.03.04 as I cannot get to it. I have been trying for months. I have tried every combination of binaries and allowing running as  a program. I am a Linux Mint 19.3 user. I cannot use APT to add the nightly build. I am stuck. I have updated Python to 3.7 and it now says after downloading the binary again "You are using an unsupported version of Python. Only Python versions 3.7 and above are supported by yt-dlp" 

I am so confused and do not know what I am doing wrong. I know that dlp works fine and I cannot see any known issues or anything in the bug tracker.

Thank you in advance if anyone can help me (I did the step below as said but it doesn't show me DEBUG?)

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
Traceback (most recent call last):
  File "/usr/local/bin/yt-dlp/yt_dlp/__init__.py", line 2, in <module>
ModuleNotFoundError: No module named 'contextvars'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/bin/yt-dlp/__main__.py", line 14, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/usr/local/bin/yt-dlp/yt_dlp/__init__.py", line 5, in <module>
Exception: You are using an unsupported version of Python. Only Python versions 3.7 and above are supported by yt-dlp
```

**Comment by gamer191** [comment]
Does deleting the yt-dlp binary and running `pip install yt-dlp` work?

**Comment by bashonly** [comment]
Don't install with pip. You have a python 3.6 installation still on your system 

You could try these steps:

 1. uninstall **all** versions of yt-dlp:
      1. `sudo apt remove yt-dlp`
      2. find+delete any binaries you downloaded

 2. there is still an installation of python 3.6 on your system:
     1. `sudo apt update`
     2. `sudo apt full-upgrade`
     3. after restarting, run `python3 --version` to make sure 3.7 or higher is installed
   
 3. do **not** reinstall yt-dlp with `apt`:
     1. download https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp
     2. move downloaded binary to `~/.local/bin`
     3. if you get `bash: yt-dlp: command not found` when running `yt-dlp`, then do this:
         - `echo 'export PATH=~/.local/bin:$PATH' >> ~/.bashrc`
     4. close/re-open terminal and try again

**Comment by gamer191** [comment]
Actually, even easier, just use the `yt-dlp_linux` binary (after deleting all copies of yt-dlp from your system)

**Comment by bashonly** [comment]
they would still need to follow all the above steps

**Comment by gamer191** [comment]
no, they'd only need to follow step 1, because `yt-dlp_linux` is a standalone binary that includes python



> well not 2, but it would fix a broken python installation for them

perhaps, but python 3.6 is likely installed on their system for a reason, and I don't want to cause them dependency hell (although I'm unfamiliar with apt full-upgrade, so I dunno)

**Comment by gamer191** [comment]
> and a full-upgrade is never a bad thing

nevermind then

**Comment by bashonly** [comment]
maybe stick to what you are familiar with?

they need to move the binary into their PATH, which is what step 3 is doing

**Comment by KyleRickards** [comment]
Thank you for this help! This is where I am at



    uninstall all versions of yt-dlp: Done
        
        find+delete any binaries you downloaded - Done

    there is still an installation of python 3.6 on your system:
        sudo apt update - Nothing to update it said apart from Skype which was disabled
        sudo apt full-upgrade - Nothing to upgrade
        after restarting, run python3 --version to make sure 3.7 or higher is installed - Version is showing 3.6.9, but if I type python3.7 -V I get Python 3.7.9 back in the Command Line - I am worried about breaking something with my IDJC though? Will all that still work?


Thank you again for the help so far

**Comment by bashonly** [comment]
if you still need python 3.6 for some reason, then do follow gamer191's advice and download this binary instead:
https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp_linux
but follow the rest of the instructions in step 3

**Comment by KyleRickards** [comment]
Sorry, I don't mean to take up all your time. 

So I renamed the file and copied it to /home/studio/.local/bin - I allowed executing as a file.

All the other files in there are Python scripts but this is saying it's a shared library? It also said permission denied when I tried to run it initially but I think that was because I hadn't changed the permission. Now I get there is no application installed for shared library files - do you want to search for an application?

**Comment by gamer191** [comment]
are you using `yt-dlp_linux`?

**Comment by KyleRickards** [comment]
I used that download but renamed the file - I can redownload or change it back?

**Comment by KyleRickards** [comment]
![image](https://github.com/yt-dlp/yt-dlp/assets/21976755/b1c6bbc9-71c4-4f03-984c-b474ec77d1b7)

**Comment by bashonly** [comment]
> there is no application installed for shared library files

is this what what happens when you try to run it by clicking on it? or also when you run it from command line?

**Comment by KyleRickards** [comment]
Ah! So clicking gives that error but running in command line seems to work - I gave it a URL from YT and it seemed to do something. I'm not sure where it's saved it but it looked promising!

**Comment by bashonly** [comment]
By default it will save downloads into the current working directory of your terminal session.
You can change this by passing the `--paths` or `-P` option, e.g. `yt-dlp -P ~/studio/Downloads "URL"`
or you could set that in a config file
or open the terminal in / `cd` to the folder you want to download to

**Comment by KyleRickards** [comment]
Thank you for all your help - my last question (I am going through the manual, not used to command line) - do I have to specify a location for saving the file, after I've entered the URL?
