### ISSUE TITLE
[YouTube] Can't download age restricted video anymore

### ISSUE THREAD

**Issue by Rocket3192** [yt-dlp/yt-dlp#7349]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Switzerland

### Provide a description that is worded well enough to be understood

Hello, 
Youtube-dl used to be the best way to watch / download age restricted videos on YouTube without giving your ID card to Google to verify your account

But since recently it stopped working and we get this error : Sign in to confirm your age. This video may be inappropriate for some users.

Thank you if you can do anything about this :)

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://www.youtube.com/watch?v=34V97ameTe8', '--list-formats']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (win32_dir)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19044-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 6.0-full_build-www.gyan.dev (setts), ffprobe 6.0-full_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
yt-dlp is up to date (stable@2023.03.04)
[youtube] Extracting URL: https://www.youtube.com/watch?v=34V97ameTe8
[youtube] 34V97ameTe8: Downloading webpage
[youtube] 34V97ameTe8: Downloading android player API JSON
[youtube] 34V97ameTe8: Downloading tv embedded player API JSON
[youtube] 34V97ameTe8: Downloading web embedded client config
[youtube] 34V97ameTe8: Downloading player 6ed0d907
[youtube] 34V97ameTe8: Downloading web embedded player API JSON
[debug] [youtube] Extracting signature function js_6ed0d907_110
WARNING: [youtube] 34V97ameTe8: Signature extraction failed: Some formats may be missing
[debug] [youtube] Traceback (most recent call last):
  File "yt_dlp\extractor\youtube.py", line 2997, in inner
  File "yt_dlp\extractor\youtube.py", line 2922, in _extract_signature_function
  File "yt_dlp\extractor\youtube.py", line 2991, in <lambda>
  File "yt_dlp\utils.py", line 6072, in __call__
  File "yt_dlp\jsinterp.py", line 841, in resf
  File "yt_dlp\jsinterp.py", line 180, in interpret_statement
  File "yt_dlp\jsinterp.py", line 331, in interpret_statement
  File "yt_dlp\jsinterp.py", line 180, in interpret_statement
  File "yt_dlp\jsinterp.py", line 747, in interpret_statement
  File "yt_dlp\jsinterp.py", line 739, in eval_method
KeyError: 'QV'
 (caused by KeyError('QV')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[debug] [youtube] Extracting signature function js_6ed0d907_106
ERROR: [youtube] 34V97ameTe8: Sign in to confirm your age. This video may be inappropriate for some users.
  File "yt_dlp\extractor\common.py", line 694, in extract
  File "yt_dlp\extractor\youtube.py", line 4018, in _real_extract
  File "yt_dlp\extractor\common.py", line 1172, in raise_no_formats
```

**Comment by bashonly** [comment]
run `yt-dlp --update-to nightly`

see pinned issues
