### ISSUE TITLE
It's real to make plugin for dowload crypted video (need decryption on postproduction) ?

### ISSUE THREAD

**Issue by minzak** [yt-dlp/yt-dlp#7357]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I know a lot sites (mostly educations) where with m3u files in some data (for each m3u own key) present key (as usual it is aes128) for decryption stream video files, and player on the fly decode it.
Also time to time present protection on the userAgent, Referer, Origin and etc.

As example I have this worked JS code, where need just add parsed m3u links and key:

```
const crypto = require("crypto"),
	fs = require('fs'),
	request = require('request'),
	Url = require("url"),
	path = require("path");

const Algorithm = "aes128",
	iv = Buffer.alloc(16);

iv.fill(0);

process.on('uncaughtException', function(error) {
    console.log(error);
});

const m3u8Regex = {
	key: /#EXT-X-KEY.*URI="([^"]+)".*/is,
	episode: /^(.+\.ts)$/is
}

const userAgent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:80.0) Gecko/20100101 Firefox/80.0",
	playlist = "data/1.m3u8";
	dkey = "yQACoSNtCSsyeD8e";

function parsePl(data){
	let result = [], current=null, match;

	let rows = data.split(/\r?\n/);

	rows.forEach((element, i) => {
		if(element){
			if(match = element.match(m3u8Regex.episode)){
				result.push(match[1]);
			}
		}
	});

	return result;
}

const download = (url, dest, cb) => {
    const file = fs.createWriteStream(dest);
    const sendReq = request.get({
		"url": url,
		headers: {
			'User-Agent': userAgent,
			//'Cookie': gCookie,
			'Accept': '/',
			'Connection': 'keep-alive',
			'Accept-Language': "uk-UA,uk;q=0.8,en-US;q=0.5,en;q=0.3",
			'Accept-Encoding': "gzip, deflate, br",
			'Referer': "https://play.domain.com/zk3ORD1t?title=0",
			'Origin': "https://play.domain.com"
		}
	});

    // verify response code
    sendReq.on('response', (response) => {
        if (response.statusCode !== 200) {
            return cb('Response status was ' + response.statusCode);
        }

        sendReq.pipe(file);
    });

    // close() is async, call cb after close completes
    file.on('finish', () => file.close(cb));

    // check for request errors
    sendReq.on('error', (err) => {
        fs.unlink(dest);
        return cb(err.message);
    });

    file.on('error', (err) => { // Handle errors
        fs.unlink(dest); // Delete the file async. (But we don't check the result)
        return cb(err.message);
    });
};

async function decryptFile(key, inputFile, outputFile, callback) {
    const inputData = fs.readFileSync(inputFile);
	let cipher = null;
    try{
		cipher = crypto.createDecipheriv(Algorithm, key, iv);
    }catch(e){
		console.log(e);
		console.log("Key: ", key, "File:", inputFile);
		return false;
    }
    if(cipher){
		const output = Buffer.concat([cipher.update(inputData) , cipher.final()]);
		fs.writeFileSync(outputFile, output);
		callback(inputFile, output);
		return true;
    }
}

fs.readFile(playlist, 'utf8', (err, data) => {
	let pl = parsePl(data);
	
	pl.forEach((item, ii) => {
		setTimeout(function(){
			let filename = Url.parse(item);
			filename = path.basename(filename.pathname);
			console.log(item);
			console.log(filename);
			
			download(item, "data/temp/" + filename, function(){
				decryptFile(dkey, "data/temp/" + filename, "data/ts/" + filename, function(){
					fs.unlink("data/temp/" + filename, () => {});
				});
			});
			fs.appendFileSync('data/ts/pl.txt', "file '" + filename + "'\r\n");
		}, 500*ii);
	});
});
```

It is real to do?
Thanks.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
if the key URI in the m3u8 playlist is a standard/valid URL, yt-dlp or ffmpeg will handle this automatically

if you need to manually pass the key because the key URI in the m3u8 has a custom scheme or the site is using some other non-standard method of providing the key, then you can use the `hls_key` generic extractor argument, e.g.:
```
yt-dlp --extractor-args "generic:hls_key=HEX" "https://www.example.com/playlist.m3u8"
```
replacing `HEX` with the actual key as hex

see https://github.com/yt-dlp/yt-dlp#generic
