### ISSUE TITLE
DiscoveryPlus requires --cookies when cookies are supplied

### ISSUE THREAD

**Issue by pete2583** [yt-dlp/yt-dlp#7359]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

UK

### Provide a description that is worded well enough to be understood

Trying to download from DiscoveryPlus UK and have downloaded the cookies for that site from Get Cookies.txt locally and have used the line --cookies yet it errors out that the video is for registered users only and I should use --cookies. 

Here's the exact command I used:

yt-dlp --cookies auth.discoveryplus.com_cookies.txt https://www.discoveryplus.com/gb/video/sport/dplus-sport-dplus-sport-sport/uci-downhill-world-cup-leogang --verbose --geo-bypass-country GB

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp -vU --cookies auth.discoveryplus.com_cookies.txt https://www.discoveryplus.com/gb/video/sport/dplus-sport-dplus-sport-sport/uci-downhill-world-cup-leogang --geo-bypass-country GB
[debug] Command-line config: ['-vU', '--cookies', 'auth.discoveryplus.com_cookies.txt', 'https://www.discoveryplus.com/gb/video/sport/dplus-sport-dplus-sport-sport/uci-downhill-world-cup-leogang', '--geo-bypass-country', 'GB']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (pip)
[debug] Python 3.10.6 (CPython x86_64 64bit) - Linux-6.3.3-060303-generic-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.05.07, mutagen-1.46.0, secretstorage-3.3.1, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
yt-dlp is up to date (stable@2023.03.04)
[debug] Using fake IP 25.17.166.16 (GB) as X-Forwarded-For
[DiscoveryPlus] Extracting URL: https://www.discoveryplus.com/gb/video/sport/dplus-sport-dplus-sport-sport/uci-downhill-world-cup-leogang
[DiscoveryPlus] sport/dplus-sport-dplus-sport-sport: Downloading JSON metadata
ERROR: [DiscoveryPlus] sport/dplus-sport-dplus-sport-sport: This video is only available for registered users. You may want to use --cookies.
  File "/usr/local/lib/python3.10/dist-packages/yt_dlp/extractor/common.py", line 694, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.10/dist-packages/yt_dlp/extractor/dplay.py", line 366, in _real_extract
    return self._get_disco_api_info(url, self._match_id(url), **self._DISCO_API_PARAMS)
  File "/usr/local/lib/python3.10/dist-packages/yt_dlp/extractor/dplay.py", line 90, in _get_disco_api_info
    self._process_errors(e, geo_countries)
  File "/usr/local/lib/python3.10/dist-packages/yt_dlp/extractor/dplay.py", line 48, in _process_errors
    raise ExtractorError(
```

**Comment by dirkf** [comment]
This message "... only available for registered users ..." means that D+ returned an error: either `access.denied.missingpackage` or `invalid.token`.

If your cookie file does contain the required cookies, it's possible that the cookies are very short-lived and a required cookie has expired.

Alternatively, the cookies may be linked to your browser fingerprint in some way, the simplest being the `User-Agent` header, which you can masquerade with _yt-dlp_.

But your diagnostic matches long-standing issue #2318, where the latest report says that sport videos are encrypted, further blocking your downhill biking enjoyment. Similar content may be available from less fastidious sources.

**Comment by pete2583** [comment]
Well that would suck if I can't download from them lol. 

I have tried on regular programs from d+ too and I get the same error. 

The cookies text for was made right after logging in again so I doubt it's expired. How would I masquerade the user-agent with yt-dlp? 

I guess that's worth a try if I can figure it out

**Comment by pete2583** [comment]
I think I may have worked out the issue, but I'd need to pick your brains to see if I'm right...

So I use Discover+ in the uk and the address for this is: https://www.discoveryplus.com/gb

So when I use yt-dlp it seems to strip the /gb part of the url away meaning that is is trying to connect to the us site, where my cookies would be invalid as I don't have a login with them. 

I've even used --geo-bypass-country GB and it still doesn't work. 

Could the issue actually be that simple?!

**Comment by dirkf** [comment]
See https://github.com/yt-dlp/yt-dlp/issues/2138#issuecomment-1598680425.
