### ISSUE TITLE
[ODYSEE] Extractor error has occured

### ISSUE THREAD

**Issue by kotaruTWK** [yt-dlp/yt-dlp#7362]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United States

### Provide a description that is worded well enough to be understood

When trying to download from Odysee.com an extractor error occurs after fetching JSON metadata.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://odysee.com/@IsekaiAudioTales:3/i809m-the-evil-lord-of-an-17:f?lid=2e974393a28e50cd47812cd2f3227d2cce79e4c0']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-110654-g63767b79a5-20230518 (setts), ffprobe N-110654-g63767b79a5-20230518
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.03.04, Current version: stable@2023.03.04
Current Build Hash: 5590c57bd0433ed239a2deaaf92e2ad6f37fe50f53664c821575cafe106a9421
yt-dlp is up to date (stable@2023.03.04)
[lbry] Extracting URL: https://odysee.com/@IsekaiAudioTales:3/i809m-the-evil-lord-of-an-17:f?lid=2e974393a28e50cd47812cd2f3227d2cce79e4c0
[lbry] @IsekaiAudioTales#3/i809m-the-evil-lord-of-an-17#f: Downloading stream JSON metadata
ERROR: @IsekaiAudioTales:3/i809m-the-evil-lord-of-an-17:f: An extractor error has occurred. (caused by KeyError('value')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 694, in extract
  File "yt_dlp\extractor\lbry.py", line 228, in _real_extract
KeyError: 'value'
```

**Comment by bashonly** [comment]
> I've checked that all provided URLs are playable in a browser

Can you double check that?

**Comment by kotaruTWK** [comment]
> > I've checked that all provided URLs are playable in a browser with the same IP and same login details
> 
> Can you double check that?

Ok i see your point but that brings a weirder issue. the video uses ’ instead of ' and so when i copy and pasted the url into my command it turned the ’ into the code for that character. however after going through all that, and finally getting it to accept the weird apostrophe into my bat command that just gave me this
`[lbry] Extracting URL: https://odysee.com/@IsekaiAudioTales:3/i\ΓÇÖm-the-evil-lord-of-an-17:f?lid=2e974393a28e50cd47812cd2f3227d2cce79e4c0`
but if i copy and paste the command from my bat it runs just fine.

my bat:
`yt-dlp.exe -vU "https://odysee.com/@IsekaiAudioTales:3/i'm-the-evil-lord-of-an-17:f?lid=2e974393a28e50cd47812cd2f3227d2cce79e4c0"`

**Comment by bashonly** [comment]
use this url:
`https://odysee.com/@IsekaiAudioTales:3/i%E2%80%99m-the-evil-lord-of-an-17:f`

**Comment by kotaruTWK** [comment]
> use this url: `https://odysee.com/@IsekaiAudioTales:3/i%E2%80%99m-the-evil-lord-of-an-17:f`
> 
> or if using in batch script: `https://odysee.com/@IsekaiAudioTales:3/i%%E2%%80%%99m-the-evil-lord-of-an-17:f`

Throwing the second url into my batch script works. thanks for helping. thats gonna suck for all the future downloads using that broken apostrophe.

**Comment by bashonly** [comment]
Instead of copying the url from a hyperlink, If you enter the url into your browser's address bar, press enter, and then copy it from the address bar, your browser should percent-encode the url for you.

However, if you are putting the url in a batch script then you'll still have to double the `%`s. In that case, couldn't you have your bat take an argument for the url instead of hardcoding it?
