### ISSUE TITLE
[Niconico] niconico_dmc download speed throttles and disconnects after a while

### ISSUE THREAD

**Issue by fireattack** [yt-dlp/yt-dlp#7365]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.03.04** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Provide a description that is worded well enough to be understood

When downloading a video (not livestream) from niconico, the download speed seems to be throttled to less than 200 KB/s and the server will disconnect you after a while.

I tried it on multiple servers, and tried it with cookies (with my premium account) and the problem persists. I don't have residential Internet in Japan to try though.  

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['https://www.nicovideo.jp/watch/sm39503617', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out UTF-8, error UTF-8, screen UTF-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d] (zip)
[debug] Python 3.7.3 (CPython x86_64 64bit) - Linux-5.10.0-0.deb10.16-amd64-x86_64-with-debian-10.13 (OpenSSL 1.1.1n  15 Mar 2022, glibc 2.28)
[debug] exe versions: none
[debug] Optional libraries: Crypto-broken 2.6.1, certifi-2018.08.24, secretstorage-2.3.1, sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Loaded 1786 extractors
[niconico] Extracting URL: https://www.nicovideo.jp/watch/sm39503617
[niconico] sm39503617: Downloading webpage
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: best/bestvideo+bestaudio
[info] sm39503617: Downloading 1 format(s): h264_360p-aac_128kbps-http
[debug] Invoking niconico_dmc downloader on "niconico_dmc:sm39503617/archive_h264_360p/archive_aac_128kbps"
[niconico_dmc] Downloading from DMC
[niconico] sm39503617: Downloading JSON metadata for h264_360p-aac_128kbps-http
[niconico] sm39503617: Acquiring permission for downloading video
[niconico_dmc] Heartbeat with 40 second interval ...
[download] Resuming download at byte 17096192
[download] Destination: 夏川椎菜のCultureZ 2021年10月18日#23（ゲスト：相良茉優・内田秀） [sm39503617].mp4
[download]   4.1% of  604.31MiB at  146.02KiB/s ETA 01:07:43[download] Got error: Downloaded 26067748 bytes, expected 633665978 bytes. Retrying (1/10)...
[download] Destination: 夏川椎菜のCultureZ 2021年10月18日#23（ゲスト：相良茉優・内田秀） [sm39503617].mp4
[download]   5.5% of  604.31MiB at  146.02KiB/s ETA 01:06:43[download] Got error: Downloaded 35039304 bytes, expected 633665978 bytes. Retrying (2/10)...
[download] Destination: 夏川椎菜のCultureZ 2021年10月18日#23（ゲスト：相良茉優・内田秀） [sm39503617].mp4
[download]   6.9% of  604.31MiB at  146.02KiB/s ETA 01:05:43[download] Got error: Downloaded 44010860 bytes, expected 633665978 bytes. Retrying (3/10)...
[download] Destination: 夏川椎菜のCultureZ 2021年10月18日#23（ゲスト：相良茉優・内田秀） [sm39503617].mp4
[download]   8.4% of  604.31MiB at  146.02KiB/s ETA 01:04:43[download] Got error: Downloaded 52982416 bytes, expected 633665978 bytes. Retrying (4/10)...
[download] Destination: 夏川椎菜のCultureZ 2021年10月18日#23（ゲスト：相良茉優・内田秀） [sm39503617].mp4
[download]   9.8% of  604.31MiB at  146.02KiB/s ETA 01:03:43[download] Got error: Downloaded 61953972 bytes, expected 633665978 bytes. Retrying (5/10)...
[download] Destination: 夏川椎菜のCultureZ 2021年10月18日#23（ゲスト：相良茉優・内田秀） [sm39503617].mp4
[download]  11.2% of  604.31MiB at  146.02KiB/s ETA 01:02:43[download] Got error: Downloaded 70925528 bytes, expected 633665978 bytes. Retrying (6/10)...
[download] Destination: 夏川椎菜のCultureZ 2021年10月18日#23（ゲスト：相良茉優・内田秀） [sm39503617].mp4
[download]  12.6% of  604.31MiB at  146.02KiB/s ETA 01:01:43[download] Got error: Downloaded 79897084 bytes, expected 633665978 bytes. Retrying (7/10)...
[download] Destination: 夏川椎菜のCultureZ 2021年10月18日#23（ゲスト：相良茉優・内田秀） [sm39503617].mp4
[download]  14.0% of  604.31MiB at  146.02KiB/s ETA 01:00:43[download] Got error: Downloaded 88868640 bytes, expected 633665978 bytes. Retrying (8/10)...
[download] Destination: 夏川椎菜のCultureZ 2021年10月18日#23（ゲスト：相良茉優・内田秀） [sm39503617].mp4
```

**Comment by pukkandan** [comment]
cc @CXwudi, @tsukumijima, @lesmiscore

**Comment by CXwudi** [comment]
The trolling in niconico always exists, even before @tsukumijima's fix was implemented in yt-dlp back in 2021. Usually the workaround is either using an `--external-downloader` with multi-thread downloading supports like aria2c (recommended), or using `--http-chunk-size XM` to reconnect every `X` MB downloaded.

Looks like the trolling in this issue is even worse, usually I can get full speed constantly with aria2c, but now only 1.5mb/s on the video you test. I tried other videos from 夏川椎菜のCultureZ series and experienced the same. So I guess niconico has more trolling when downloading long (like 1hr) videos. Now, I am just not sure how long would consider long enough to get this type of trolling. (At least I know 10 minutes won't get this trolling). And not sure if it is fixable, since it looks like a restriction from the server side.

Fortunately, I was able to finish downloading the 1hr video with aria2c, even with only 1.5mb/s...

**Comment by gamer191** [comment]
> the server will disconnect you after a while

related discussion: https://github.com/yt-dlp/yt-dlp/issues/7241

**Comment by RisingFog** [comment]
> The trolling in niconico always exists, even before @tsukumijima's fix was implemented in yt-dlp back in 2021. Usually the workaround is either using an `--external-downloader` with multi-thread downloading supports like aria2c (recommended), or using `--http-chunk-size XM` to reconnect every `X` MB downloaded.

I've tried to use --external-downloader aria2c for a niconico live timeshift, but it still reverts to using ffmpeg instead. Is aria2c supported with niconico live content?

**Comment by bashonly** [comment]
> Is aria2c supported with niconico live content?

no, aria2c cannot handle any livestream downloads

**Comment by pzhlkj6612** [comment]
Hi there! After applying #9282 , we are able to download [sm39503617 (117' 55") - 夏川椎菜のCultureZ 2021年10月18日#23（ゲスト：相良茉優・内田秀） - ニコニコ](https://www.nicovideo.jp/watch/sm39503617) from the DMS server in stable speed:

```
[info] Available formats for sm39503617:
ID                             EXT RESOLUTION FPS │   FILESIZE  TBR PROTO │ VCODEC       VBR ACODEC      ABR ASR MORE INFO
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
audio-aac-64kbps               m4a audio only     │ ~ 72.36MiB  84k m3u8  │ audio only       aac         84k 44k Main Audio
audio-aac-128kbps              m4a audio only     │ ~ 99.89MiB 116k m3u8  │ audio only       aac        116k 44k Main Audio
h264_360p_low-aac_64kbps-hls   mp4 640x360        │ ~314.37MiB 364k dmc   │ h264        300k aac         64k 44k DMC Low-Quality HLS
h264_360p_low-aac_64kbps-http  mp4 640x360        │ ~314.37MiB 364k dmc   │ h264        300k aac         64k 44k DMC Low-Quality HTTP
h264_360p_low-aac_128kbps-hls  mp4 640x360        │ ~369.64MiB 428k dmc   │ h264        300k aac        128k 44k DMC Low-Quality HLS
h264_360p_low-aac_128kbps-http mp4 640x360        │ ~369.64MiB 428k dmc   │ h264        300k aac        128k 44k DMC Low-Quality HTTP
h264_360p-aac_64kbps-hls       mp4 640x360        │ ~573.46MiB 664k dmc   │ h264        600k aac         64k 44k DMC 360p HLS
h264_360p-aac_64kbps-http      mp4 640x360        │ ~573.46MiB 664k dmc   │ h264        600k aac         64k 44k DMC 360p HTTP
h264_360p-aac_128kbps-hls      mp4 640x360        │ ~628.74MiB 728k dmc   │ h264        600k aac        128k 44k DMC 360p HLS
h264_360p-aac_128kbps-http     mp4 640x360        │ ~628.74MiB 728k dmc   │ h264        600k aac        128k 44k DMC 360p HTTP
video-302                      mp4 640x360     30 │ ~260.79MiB 302k m3u8  │ avc1.42c01e 302k video only
video-601                      mp4 640x360     30 │ ~519.16MiB 601k m3u8  │ avc1.4d401e 601k video only
[debug] Default format spec: bestvideo*+bestaudio/best 
[info] sm39503617: Downloading 1 format(s): video-601+audio-aac-128kbps
...
[debug] Invoking hlsnative downloader on "https://delivery.domand.nicovideo.jp/hlsbid/..."
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 1180 
[download] Destination: <name>.fvideo-601.mp4
[debug] File locking is not supported. Proceeding without locking
[download] 100% of  507.11MiB in 00:01:57 at 4.30MiB/s
[debug] Invoking hlsnative downloader on "https://delivery.domand.nicovideo.jp/hlsbid/..."
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 1180 
[download] Destination: <name>.faudio-aac-128kbps.m4a
[download] 100% of   97.43MiB in 00:01:35 at 1.02MiB/s
[debug] ffmpeg command line: ...
[Merger] Merging formats into "<name>.mp4" 
[debug] ffmpeg command line: ...
Deleting original file <name>.faudio-aac-128kbps.m4a (pass -k to keep) 
Deleting original file <name>.fvideo-601.mp4 (pass -k to keep)

```

.

**Comment by CXwudi** [comment]
Impressive PR, I will have to learn what is the extraction logic behind it
