### ISSUE TITLE
Authentication regression in latest release

### ISSUE THREAD

**Issue by tntmod54321** [yt-dlp/yt-dlp#7368]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2023.06.21** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Hi, this latest release broke the soundcloud extractor for me (the previous release still works), I'm filing this as a generic bug because this error occurs in extractor/common, and could perhaps be present in other extractors, I hope that's forgivable.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '-F', 'https://soundcloud.com/user-352956556/my-home-is-a-prison']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.06.21 [42f2d40b4] (pip)
[debug] Python 3.10.8 (CPython AMD64 64bit) - Windows-10-10.0.19044-SP0 (OpenSSL 1.1.1q  5 Jul 2022)
[debug] exe versions: ffmpeg 4.4-essentials_build-www.gyan.dev (setts), ffprobe 4.4-essentials_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.15.0, brotli-1.0.9, certifi-2018.04.16, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1848 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.06.21, Current version: stable@2023.06.21
yt-dlp is up to date (stable@2023.06.21)
ERROR: 'NoneType' object has no attribute 'format'
Traceback (most recent call last):
  File "C:\Users\tntmo\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 1555, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\tntmo\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\YoutubeDL.py", line 1631, in __extract_info
    ie_result = ie.extract(url)
  File "C:\Users\tntmo\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\extractor\common.py", line 705, in extract
    self.initialize()
  File "C:\Users\tntmo\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\extractor\common.py", line 609, in initialize
    username, password = self._get_login_info()
  File "C:\Users\tntmo\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\extractor\common.py", line 1335, in _get_login_info
    username, password = self._get_netrc_login_info(netrc_machine)
  File "C:\Users\tntmo\AppData\Local\Programs\Python\Python310\lib\site-packages\yt_dlp\extractor\common.py", line 1300, in _get_netrc_login_info
    cmd = self.get_param('netrc_cmd', '').format(netrc_machine)
AttributeError: 'NoneType' object has no attribute 'format'
```

**Comment by tntmod54321** [comment]
I was right, yikes, twitch is also broken.

**Comment by pukkandan** [comment]
https://github.com/yt-dlp/yt-dlp/issues/3766
