### ISSUE TITLE
Handling Youtube videos with duplicate titles, but different URLs

### ISSUE THREAD

**Issue by djbldjbl** [yt-dlp/yt-dlp#737]
## Checklist

- [X] I'm reporting a broken site support
- [X] I've verified that I'm running yt-dlp version **2021.08.10**
- [X] I've checked that all provided URLs are alive and playable in a browser
- [X] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [X] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
yt-dlp_x86 -v https://www.youtube.com/watch?v=rV1JWwQJqH0 --cookies "c:/cookies/cookies.txt" -o "c:/tiktoktub/%(title)s.%(ext)s"
[debug] Command-line config: ['-v', 'https://www.youtube.com/watch?v=rV1JWwQJqH0', '--cookies', 'c:/cookies/cookies.txt', '-o', 'c:/tiktoktub/%(title)s.%(ext)s']
WARNING: Support for Python version 3.4 have been deprecated and will break in future versions of yt-dlp! Update to Python 3.6 or above
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] yt-dlp version 2021.06.09 (exe)
[debug] Python version 3.4.4 (CPython 32bit) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg git-2020-04-03-52523b6, ffprobe git-2020-04-03-52523b6
[debug] Proxy map: {}
[debug] [youtube] Extracting URL: https://www.youtube.com/watch?v=rV1JWwQJqH0
[youtube] rV1JWwQJqH0: Downloading webpage
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] rV1JWwQJqH0: Downloading 1 format(s): 303+251
[download] c:\tiktoktub\TikTok Girls Warming Up For The Hub.webm has already been downloaded

```

## Description

if I try to download a video from youtube that has the same title as a previously downloaded video, it will report that it has already been downloaded. This might be expected behavior, but unfortunately sometimes it results in missing videos from channels that for some reason decide to use duplicate names for different videos. Is there some work around where I can append the youtube video ID from the URL into the filename to prevent this from happening?

**Comment by Ashish0804** [comment]
This is not an issue. 
You are using custom output template, the default one already adds video id to the filename to not have false matches.
Modify your output template.
See: https://github.com/yt-dlp/yt-dlp#output-template
