### ISSUE TITLE
slow loading of videos from youtube

### ISSUE THREAD

**Issue by xxkillaxx** [yt-dlp/yt-dlp#7377]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.06.21** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

it worked without errors. Slow video loading started today. Does not even exceed 1 mbit/sec. How to fix it?

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by gamer191** [comment]
please add a verbose output!

**Comment by gamer191** [comment]
Also, after testing it again to make sure it hasn't just randomly resolved itself, try running `--update-to nightly@latest` and see if it fixes it

**Comment by meoyawn** [comment]
Version **2023.06.22**: I have the same issue. Downloading with `yt-dlp` itself is very fast
```sh
yt-dlp https://www.youtube.com/watch\?v\=yKDWtJt5qyw -x -f 140
```

but external downloader is throttled

```sh
yt-dlp https://www.youtube.com/watch\?v\=yKDWtJt5qyw -f 140 -J | jq .url
```

Version **2023.03.04** exposed `.fragments` with `.url`s that had `&range=` in them, it was great for external downloaders.

Is the lack of `.fragments` a bug or a feature of **2023.06.22**?

Thanks

**Comment by bashonly** [comment]
> but external downloader is throttled

Youtube http formats need to be downloaded with an http chunk size of 10M, or else yt will throttle. yt-dlp's native http downloader does this; you'll need to configure your external downloader to do the same (if possible).

> Version 2023.03.04 exposed .fragments with .urls that had &range= in them, it was great for external downloaders.
> Is the lack of .fragments a bug or a feature of 2023.06.22?

DASH-ifying http formats is no longer necessary to natively mitigate youtube speed throttling, so the default behavior was reverted. `fragments` will still be available with "dashy" formats, which you could select by passing something like this:
`--extractor-arg "youtube:include_duplicate_formats" -f "ba[format_id*=140-dashy]"`

**Comment by meoyawn** [comment]
are we back to `Range` headers? Or is `&range=` URL query still required to avoid throttling?

**Comment by bashonly** [comment]
> are we back to Range headers? Or is &range= URL query still required to avoid throttling?

No, the range query param is NOT required anymore, which is why the default behavior was reverted back to NOT splitting up http formats into dash fragments.

**Comment by gamer191** [comment]
This can be fixed using `--extractor-args youtube:include_duplicate_formats -S proto:dash`, although imo include_duplicate_formats is overloaded currently, and there should be a separate extractor arg for dashy formats

**Comment by gamer191** [comment]
Also, this isn't just an external issue, because it also prevents users getting the benefits of `--concurrent-fragments`

**Comment by pukkandan** [comment]
We donot and cannot guarantee the presence of any format for any site. So this is not a regression.

> imo include_duplicate_formats is overloaded currently, and there should be a separate extractor arg for dashy formats

We can do that, but can you provide a use case that would be significantly simplified by that option as compared to by `include_duplicate_formats`?
