### ISSUE TITLE
Slow when VPN is active even when should not be routing through it.

### ISSUE THREAD

**Issue by Quackdoc** [yt-dlp/yt-dlp#7378]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2023.06.21** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

On linux, I have a wireguard VPN active running in the background that I use for various things, I have the metrics set as low priority as they can go and no other application attempts to route over it unless the application is explicitly set to. IPV6 does not get routed over the vpn at all. 

typically when the VPN is disabled, YT-DLP takes about 2-5 seconds (usually 2) to query the video in question. when it is active it takes anywhere from 15s to a minute to query the video. I have confirmed the behavior using twitch too.

I am unsure if yt-dlp is attempting to route through the VPN, or if it is getting hung up somewhere else, I am unsure how to check this atm

cmdline : time yt-dlp -vU -4 -F 
yt-dlp version: stable@2023.06.21 [42f2d40b4]

an example URL is `https://www.youtube.com/watch?v=aTf7AMVOoDY&pp=ygUFbWtiaGQ%3D` however it occurs on all youtube videos and streams as well as at least twitch streams.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '-4', '-F', 'https://www.youtube.com/watch?v=aTf7AMVOoDY&pp=ygUFbWtiaGQ%3D']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.06.21 [42f2d40b4]
[debug] Lazy loading extractors is disabled
[debug] Python 3.11.3 (CPython x86_64 64bit) - Linux-6.3.8-zen1-1-zen-x86_64-with-glibc2.37 (OpenSSL 3.1.1 30 May 2023, glibc 2.37)
[debug] exe versions: ffmpeg N-111014-g141d11cb3c (fdk,setts), ffprobe N-111014-g141d11cb3c, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.12.0, certifi-2023.05.07, mutagen-1.46.0, secretstorage-3.3.3, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1848 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.06.21, Current version: stable@2023.06.21
yt-dlp is up to date (stable@2023.06.21)
[youtube] Extracting URL: https://www.youtube.com/watch?v=aTf7AMVOoDY&pp=ygUFbWtiaGQ%3D
[youtube] aTf7AMVOoDY: Downloading webpage
[youtube] aTf7AMVOoDY: Downloading android player API JSON
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[info] Available formats for aTf7AMVOoDY:
ID  EXT   RESOLUTION FPS CH │   FILESIZE   TBR PROTO │ VCODEC        VBR ACODEC      ABR ASR MORE INFO
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
sb2 mhtml 48x27        0    │                  mhtml │ images                                storyboard
sb1 mhtml 89x45        0    │                  mhtml │ images                                storyboard
sb0 mhtml 179x90       0    │                  mhtml │ images                                storyboard
599 m4a   audio only      2 │    2.87MiB   31k https │ audio only        mp4a.40.5   31k 22k [en] ultralow, ANDR, m4a_dash
600 webm  audio only      2 │    3.24MiB   35k https │ audio only        opus        35k 48k [en] ultralow, ANDR, webm_dash
139 m4a   audio only      2 │    4.55MiB   49k https │ audio only        mp4a.40.5   49k 22k [en] low, ANDR, m4a_dash
249 webm  audio only      2 │    4.76MiB   51k https │ audio only        opus        51k 48k [en] low, ANDR, webm_dash
250 webm  audio only      2 │    6.35MiB   68k https │ audio only        opus        68k 48k [en] low, ANDR, webm_dash
140 m4a   audio only      2 │   12.07MiB  129k https │ audio only        mp4a.40.2  129k 44k [en] medium, ANDR, m4a_dash
251 webm  audio only      2 │   11.47MiB  123k https │ audio only        opus       123k 48k [en] medium, ANDR, webm_dash
17  3gp   176x144      8  1 │    7.53MiB   81k https │ mp4v.20.3         mp4a.40.2       22k [en] 144p, ANDR
597 mp4   256x128     15    │    2.82MiB   30k https │ avc1.4d400b   30k video only          144p, ANDR, mp4_dash
598 webm  256x128     15    │    1.96MiB   21k https │ vp9           21k video only          144p, ANDR, webm_dash
160 mp4   256x128     30    │    3.22MiB   35k https │ avc1.4d400c   35k video only          144p, ANDR, mp4_dash
278 webm  256x128     30    │    6.12MiB   66k https │ vp9           66k video only          144p, ANDR, webm_dash
133 mp4   426x214     30    │    6.40MiB   69k https │ avc1.4d400d   69k video only          240p, ANDR, mp4_dash
242 webm  426x214     30    │    8.15MiB   87k https │ vp9           87k video only          240p, ANDR, webm_dash
134 mp4   640x320     30    │   10.47MiB  112k https │ avc1.4d401e  112k video only          360p, ANDR, mp4_dash
18  mp4   640x320     30  2 │   34.87MiB  374k https │ avc1.42001E       mp4a.40.2       44k [en] 360p, ANDR
243 webm  640x320     30    │   16.90MiB  181k https │ vp9          181k video only          360p, ANDR, webm_dash
135 mp4   854x428     30    │   16.53MiB  177k https │ avc1.4d401f  177k video only          480p, ANDR, mp4_dash
244 webm  854x428     30    │   26.35MiB  283k https │ vp9          283k video only          480p, ANDR, webm_dash
22  mp4   1280x640    30  2 │ ~ 37.85MiB  396k https │ avc1.64001F       mp4a.40.2       44k [en] 720p, ANDR
136 mp4   1280x640    30    │   24.94MiB  267k https │ avc1.4d401f  267k video only          720p, ANDR, mp4_dash
247 webm  1280x640    30    │   47.98MiB  515k https │ vp9          515k video only          720p, ANDR, webm_dash
137 mp4   1920x960    30    │   86.21MiB  925k https │ avc1.640028  925k video only          1080p, ANDR, mp4_dash
248 webm  1920x960    30    │   85.53MiB  917k https │ vp9          917k video only          1080p, ANDR, webm_dash
271 webm  2560x1280   30    │  217.98MiB 2338k https │ vp9         2338k video only          1440p, ANDR, webm_dash
313 webm  3840x1920   30    │  716.94MiB 7690k https │ vp9         7690k video only          2160p, ANDR, webm_dash
```

**Comment by pukkandan** [comment]
The issue must be somewhere in your VPN or other network configuration. yt-dlp, like all other programs, doesn't know about the VPN and relies on OS to route it to the right place.

**Comment by Quackdoc** [comment]
I thought so too, but I have tested a large plethora of applications, Curl, P2P games like xonotic, ffmpeg, chrome and firefox etc. I have even checked python using requests's get. not a single other program exhibited strange behavior, all of them properly ignored the vpn without any increases in latency.

im really not sure what else to check at this point
