### ISSUE TITLE
Download YouTube subtitles

### ISSUE THREAD

**Issue by vega69-ux** [yt-dlp/yt-dlp#7381]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.06.21** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I have a YouTube video that has 3 subtitles. 

- English - CC1
- English - en 
- English - (auto-generated)

I would like to download all 3 subtitles and have all 3 subtitles embedded in a mkv file. 

I have tried --sub-lang en --write-auto-sub --embed-subs --recode-video mkv but I can't seem to download all 3 subtitles.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
> --sub-lang en

You only asked for one. Check the code for others in `--list-sub`

**Comment by vega69-ux** [comment]
Language                 Name              Formats
en-uYU-mmqFLq8   English - CC1   vtt, ttml, srv3, srv2, srv1, json3
en-nP7-2PuUl7o      English - en      vtt, ttml, srv3, srv2, srv1, json3

Not sure how I would download these two subtitles including the auto-generated English subtitle individually and --embed-subs to mkv?

**Comment by pukkandan** [comment]
You can use the language codes, or easier, just `--sub-langs en.*`.

**Comment by gamer191** [comment]
also, add `--write-subs` to your command, because `--sub-langs` doesn't imply it

**Comment by mazznoer** [comment]
Add `--write-auto-subs`, to download auto-generated captions.
