### ISSUE TITLE
[Broken] hearthis.at

### ISSUE THREAD

**Issue by DunnesH** [yt-dlp/yt-dlp#740]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running yt-dlp version **2021.08.10**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
C:\Users\adm\Music>yt-dlp https://hearthis.at/kyutatsuki/sharpen-cube/ -v
[debug] Command-line config: ['https://hearthis.at/kyutatsuki/sharpen-cube/', '-v']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] yt-dlp version 2021.08.10 (exe)
[debug] Python version 3.8.10 (CPython 64bit) - Windows-10-10.0.19043-SP0
[debug] exe versions: ffmpeg 4.3.1-2020-11-19-full_build-www.gyan.dev, ffprobe 4.3.1-2020-11-19-full_build-www.gyan.dev
[debug] Optional libraries: mutagen, pycryptodome, sqlite, websockets
[debug] Proxy map: {}
[debug] [HearThisAt] Extracting URL: https://hearthis.at/kyutatsuki/sharpen-cube/
[HearThisAt] kyutatsuki - sharpen-cube: Downloading webpage
[HearThisAt] 2407871: Downloading playlist
WARNING: [HearThisAt] unable to extract like count; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 2407871: Downloading 1 format(s): mp3
[debug] Invoking downloader on "https://hearthis.app/hearthisat/untitled/stream.mp3?s=vD6&t=1629398545"
[download] Destination: Kyutatsuki - Sharpen Cube [2407871].mp3
[download] 100% of 57.96KiB in 00:00

```

## Description

For many songs on hearthis.at yt-dlp downloads a blank 4-second long mp3 file instead of the actual audio.
Example song: https://hearthis.at/kyutatsuki/sharpen-cube/
yt-dlp grabs this audio: https://hearthis.app/hearthisat/untitled/stream.mp3?s=vD6&t=1629398545 which is just 4 seconds of silence
However this is the audio link it should (I think) grab: https://hearthis.at/kyutatsuki/sharpen-cube/stream.mp3?s=A6g&t=1629397021

**Comment by Ashish0804** [comment]
The website changed it seems and the mp3 regex now has false matches.
Other info seems okay.
Will make a PR soon

**Comment by marburger93** [comment]
I think it makes sense to solve it without regex. 
Add "api-v2" as a subdomain and use the `stream_url` parameter from the JSON response. 😉

https://hearthis.at/kyutatsuki/sharpen-cube/
to
https://api-v2.hearthis.at/kyutatsuki/sharpen-cube/

**Comment by Ashish0804** [comment]
@marburger93 i have no idea about this site. How stable is this api url?
Does it work for all songs? Are there any restrictions?

**Comment by marburger93** [comment]
@Ashish0804 I have been using the (open) api for more than 2 years. I don't know any restrictions so far. If only a few people know/use the api, then there will probably be restrictions like api key or similar soon. I have not found any api documentation.

**Comment by Ashish0804** [comment]
I didn't see it being used on the website. Does this site has an app or something where the api is being used?

**Comment by marburger93** [comment]
@Ashish0804 I don't remember how I found the API in the past but I just found a public documentation:
https://hearthis.at/api-v2/

**Comment by Ashish0804** [comment]
Nice
Thanks for the api endpoint @marburger93 
I'll convert it to using api now
btw it seems using `download_url` is better if present since it gives raw file, `stream_url` only seems to be giving mp3

**Comment by marburger93** [comment]
I am happy to help 🤗
Please note `stream_url` always exists, `download_url` doesn't always exist see example above.
