### ISSUE TITLE
Can't download videos which need cookies from bilibili

### ISSUE THREAD

**Issue by Thalia500** [yt-dlp/yt-dlp#7400]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.06.22** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

China

### Provide a description that is worded well enough to be understood

The video don't need cookies can be download successfully but it can't work on the video need cookies. Such as the RUL https://www.bilibili.com/bangumi/play/ep741399

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp -vU -F --cookies-from-browser edge  https://www.bilibili.com/bangumi/play/ep741399
[debug] Command-line config: ['-vU', '-F', '--cookies-from-browser', 'edge', 'https://www.bilibili.com/bangumi/play/ep741399']
[debug] Encodings: locale cp936, fs utf-8, pref cp936, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.06.22 [812cdfa06] (pip)
[debug] Python 3.10.9 (CPython AMD64 64bit) - Windows-10-10.0.22621-SP0 (OpenSSL 1.1.1t  7 Feb 2023)
[debug] exe versions: ffmpeg N-110972-gbaa9fccf8d-20230601 (setts), ffprobe N-110972-gbaa9fccf8d-20230601, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.18.0, brotli-None, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[Cookies] Extracting cookies from edge
[debug] Extracting cookies from: "C:\Users\xwj\AppData\Local\Microsoft\Edge\User Data\Default\Network\Cookies"
[debug] Found local state file at "C:\Users\xwj\AppData\Local\Microsoft\Edge\User Data\Local State"
[Cookies] Extracted 2909 cookies from edge
[debug] cookie version breakdown: {'v10': 2909, 'other': 0, 'unencrypted': 0}
[debug] Proxy map: {'http': 'http://127.0.0.1:1080', 'https': 'http://127.0.0.1:1080', 'ftp': 'http://127.0.0.1:1080'}
[debug] Loaded 1851 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.06.22, Current version: stable@2023.06.22
yt-dlp is up to date (stable@2023.06.22)
[BiliBiliBangumi] Extracting URL: https://www.bilibili.com/bangumi/play/ep741399
[BiliBiliBangumi] ep741399: Downloading webpage
ERROR: [BiliBiliBangumi] ep741399: This video is restricted
You might want to use a VPN or a proxy server (with --proxy) to workaround.
Traceback (most recent call last):
  File "C:\python_conda_package\Anaconda3\lib\site-packages\yt_dlp\YoutubeDL.py", line 1555, in wrapper
    return func(self, *args, **kwargs)
  File "C:\python_conda_package\Anaconda3\lib\site-packages\yt_dlp\YoutubeDL.py", line 1631, in __extract_info
    ie_result = ie.extract(url)
  File "C:\python_conda_package\Anaconda3\lib\site-packages\yt_dlp\extractor\common.py", line 708, in extract
    ie_result = self._real_extract(url)
  File "C:\python_conda_package\Anaconda3\lib\site-packages\yt_dlp\extractor\bilibili.py", line 435, in _real_extract
    raise GeoRestrictedError('This video is restricted')
yt_dlp.utils.GeoRestrictedError: [BiliBiliBangumi] ep741399: This video is restricted
```

**Comment by bashonly** [comment]
I think this may be fixed by #7337

**Comment by Thalia500** [comment]
> I think this may be fixed by #7337

But it can't work and show:
yt-dlp -vU -F --cookies-from-browser edge "https://www.bilibili.com/bangumi/play/ep741399"
[debug] Command-line config: ['-vU', '-F', '--cookies-from-browser', 'edge', 'https://www.bilibili.com/bangumi/play/ep741399']
[debug] Encodings: locale cp936, fs utf-8, pref cp936, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.06.22 [812cdfa06] (pip)
[debug] Python 3.10.9 (CPython AMD64 64bit) - Windows-10-10.0.22621-SP0 (OpenSSL 1.1.1t  7 Feb 2023)
[debug] exe versions: ffmpeg N-110972-gbaa9fccf8d-20230601 (setts), ffprobe N-110972-gbaa9fccf8d-20230601, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.18.0, brotli-None, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[Cookies] Extracting cookies from edge
[debug] Extracting cookies from: "C:\Users\xwj\AppData\Local\Microsoft\Edge\User Data\Default\Network\Cookies"
[debug] Found local state file at "C:\Users\xwj\AppData\Local\Microsoft\Edge\User Data\Local State"
[Cookies] Extracted 2913 cookies from edge
[debug] cookie version breakdown: {'v10': 2913, 'other': 0, 'unencrypted': 0}
[debug] Proxy map: {'http': 'http://127.0.0.1:1080', 'https': 'http://127.0.0.1:1080', 'ftp': 'http://127.0.0.1:1080'}
[debug] Loaded 1851 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.06.22, Current version: stable@2023.06.22
yt-dlp is up to date (stable@2023.06.22)
WARNING: Falling back to normal extractor since lazy extractor BiliBiliBangumiIE does not have attribute real_class; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
Traceback (most recent call last):
  File "C:\python_conda_package\Anaconda3\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\python_conda_package\Anaconda3\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\python_conda_package\Anaconda3\Scripts\yt-dlp.exe\__main__.py", line 7, in <module>
  File "C:\python_conda_package\Anaconda3\lib\site-packages\yt_dlp\__init__.py", line 1008, in main
    _exit(*variadic(_real_main(argv)))
  File "C:\python_conda_package\Anaconda3\lib\site-packages\yt_dlp\__init__.py", line 998, in _real_main
    return ydl.download(all_urls)
  File "C:\python_conda_package\Anaconda3\lib\site-packages\yt_dlp\YoutubeDL.py", line 3409, in download
    self.__download_wrapper(self.extract_info)(
  File "C:\python_conda_package\Anaconda3\lib\site-packages\yt_dlp\YoutubeDL.py", line 3384, in wrapper
    res = func(*args, **kwargs)
  File "C:\python_conda_package\Anaconda3\lib\site-packages\yt_dlp\YoutubeDL.py", line 1544, in extract_info
    return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
  File "C:\python_conda_package\Anaconda3\lib\site-packages\yt_dlp\YoutubeDL.py", line 816, in get_info_extractor
    ie = get_info_extractor(ie_key)()
  File "C:\python_conda_package\Anaconda3\lib\site-packages\yt_dlp\extractor\lazy_extractors.py", line 37, in __new__
    instance = cls.real_class.__new__(cls.real_class)
  File "C:\python_conda_package\Anaconda3\lib\site-packages\yt_dlp\extractor\lazy_extractors.py", line 26, in __getattr__
    return getattr(cls.real_class, name)
  File "C:\python_conda_package\Anaconda3\lib\site-packages\yt_dlp\extractor\lazy_extractors.py", line 26, in __getattr__
    return getattr(cls.real_class, name)
  File "C:\python_conda_package\Anaconda3\lib\site-packages\yt_dlp\extractor\lazy_extractors.py", line 26, in __getattr__
    return getattr(cls.real_class, name)
  [Previous line repeated 975 more times]
  File "C:\python_conda_package\Anaconda3\lib\site-packages\yt_dlp\utils\_utils.py", line 5547, in __get__
    return self.func(cls)
  File "C:\python_conda_package\Anaconda3\lib\site-packages\yt_dlp\extractor\lazy_extractors.py", line 33, in real_class
    cls._real_class = getattr(importlib.import_module(cls._module), cls.__name__)
  File "C:\python_conda_package\Anaconda3\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1024, in _find_and_load
  File "<frozen importlib._bootstrap>", line 170, in __enter__
  File "<frozen importlib._bootstrap>", line 196, in _get_module_lock
  File "<frozen importlib._bootstrap>", line 72, in __init__
RecursionError: maximum recursion depth exceeded while calling a Python object

**Comment by Thalia500** [comment]
> I think this may be fixed by #7337

I changed the recursion depth to 3000 and then it's:
`yt-dlp -vU -F --cookies-from-browser edge "https://www.bilibili.com/bangumi/play/ep741399"
[debug] Command-line config: ['-vU', '-F', '--cookies-from-browser', 'edge', 'https://www.bilibili.com/bangumi/play/ep741399']
[debug] Encodings: locale cp936, fs utf-8, pref cp936, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.06.22 [812cdfa06] (pip)
[debug] Python 3.10.9 (CPython AMD64 64bit) - Windows-10-10.0.22621-SP0 (OpenSSL 1.1.1t  7 Feb 2023)
[debug] exe versions: ffmpeg N-110972-gbaa9fccf8d-20230601 (setts), ffprobe N-110972-gbaa9fccf8d-20230601, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.18.0, brotli-None, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[Cookies] Extracting cookies from edge
[debug] Extracting cookies from: "C:\Users\xwj\AppData\Local\Microsoft\Edge\User Data\Default\Network\Cookies"
[debug] Found local state file at "C:\Users\xwj\AppData\Local\Microsoft\Edge\User Data\Local State"
[Cookies] Extracted 2921 cookies from edge
[debug] cookie version breakdown: {'v10': 2921, 'other': 0, 'unencrypted': 0}
[debug] Proxy map: {'http': 'http://127.0.0.1:1080', 'https': 'http://127.0.0.1:1080', 'ftp': 'http://127.0.0.1:1080'}
[debug] Loaded 1851 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.06.22, Current version: stable@2023.06.22
yt-dlp is up to date (stable@2023.06.22)
WARNING: Falling back to normal extractor since lazy extractor BiliBiliBangumiIE does not have attribute real_class; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U`

**Comment by bashonly** [comment]
Did you manually modify `bilibili.py` in the pip installation? This doesn't work because the PR changes the extractor name (which it shouldn't; I will review the PR later). You need to install from the PR branch with pip (or actually build/run from source)

**Comment by Thalia500** [comment]
> 

I've replaced the bilibili.py with the file in #7337. And that's what you see.

**Comment by bashonly** [comment]
Right. And I'm saying that doesn't work because the PR changes the extractor name.

You also need to patch `yt_dlp/extractors/_extractors.py` and disable lazy loading extractors

or, even better, do what I said in my last comment:
> You need to install from the PR branch with pip (or actually build/run from source)

**Comment by Thalia500** [comment]
> Right. And I'm saying that doesn't work because the PR changes the extractor name.
> 
> You would also need to patch `yt_dlp/extractor/_extractors.py` and disable lazy loading extractors
> 
> But, don't modify the pip installation manually. Do what I said in my last comment:
> 
> > You need to install from the PR branch with pip (or actually build/run from source)

I think I indeed download the two files in #7337 but the same

**Comment by bashonly** [comment]
no, I'm saying manually modifying your pip installation is a bad idea (and you still haven't done enough to make it work)

if you want to try the PR, do this
```
python3 -m pip install -U pip setuptools wheel
python3 -m pip install --force-reinstall https://github.com/GD-Slime/yt-dlp/archive/master.tar.gz
```

**Comment by Thalia500** [comment]
> 

Oh / thank you so much . But I found another problem that it can't support the paid content.

**Comment by Thalia500** [comment]
> 

oh thank you very much , and sometimes it may depend on a right and simple URL even though I can't exactly tell the reason. you are so kind and patient. thank u!!!
