### ISSUE TITLE
[Feature Request] [Youtube] Allow users to add to Invidious instances

### ISSUE THREAD

**Issue by 264-bit** [yt-dlp/yt-dlp#7403]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a site-specific feature
- [X] I've verified that I'm running yt-dlp version **2023.06.22** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Example URLs

https://piped-material.ftp.sh/

### Provide a description that is worded well enough to be understood

Please consider allowing users to add to the list of known invidious instances, via a command line arg, config file or similar.
This will help with niche youtube frontends such as piped-material.  It also helps with the sometimes rapid pace of new instances, now users don't have to wait for yt-dlp to be updated with every new instance.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp -vU 'https://piped-material.ftp.sh/watch?v=6IxqZOK_dpU'
[debug] Command-line config: ['-vU', 'https://piped-material.ftp.sh/watch?v=6IxqZOK_dpU']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.06.22 [812cdfa06]
[debug] Python 3.11.4 (CPython x86_64 64bit) - Linux-6.3.8-1-cachyos-x86_64-with-glibc2.37 (OpenSSL 3.1.1 30 May 2023, glibc 2.37)
[debug] exe versions: ffmpeg 6.0 (setts), ffprobe 6.0, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.12.0, brotli-1.0.9, certifi-2023.05.07, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Post-Processor Plugins: YoutubeDashGeneratorPP
[debug] Plugin directories: ['/home/user/.config/yt-dlp/plugins/ytdashgen/yt_dlp_plugins']
[debug] Loaded 1851 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.06.22, Current version: stable@2023.06.22
yt-dlp is up to date (stable@2023.06.22)
[generic] Extracting URL: https://piped-material.ftp.sh/watch?v=6IxqZOK_dpU
[generic] watch?v=6IxqZOK_dpU: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] watch?v=6IxqZOK_dpU: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://piped-material.ftp.sh/watch?v=6IxqZOK_dpU
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1555, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1631, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 708, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/extractor/generic.py", line 2568, in _real_extract
    raise UnsupportedError(url)
yt_dlp.utils.UnsupportedError: Unsupported URL: https://piped-material.ftp.sh/watch?v=6IxqZOK_dpU
```

**Comment by gamer191** [comment]
yt-dlp doesn't support invidious anyway, it just redirects to youtube

**Comment by 264-bit** [comment]
Yes, I understand it redirects invidious instances to youtube.  I want to be able to add to the instances that it redirects to youtube, for example piped-material.ftp.sh, so I don't have to manually rewrite links myself.

**Comment by coletdjnz** [comment]
Unless it goes through generic, It's not really feasible with an extractor arg as the valid url checking is done before the extractor is initialized. 

I would say this is a job is best suited for a plugin.

Example plugin:
```py
from yt_dlp.extractor.youtube import InfoExtractor


class YoutubeInvidiousRedirectIE(InfoExtractor):
    INVIDIOUS_URLS = (r'(?:www\.)?piped-material\.ftp\.sh',)
    _VALID_URL = r'https?://(?P<invidious_base>{})'.format('|'.join(INVIDIOUS_URLS))

    def _real_extract(self, url):
        invidious_base = self._match_valid_url(url).group('invidious_base')
        return self.url_result(url.replace(invidious_base, 'www.youtube.com'))
```
