### ISSUE TITLE
Disable loading of the aria2.conf file by default in yt-dlp

### ISSUE THREAD

**Issue by candrapersada** [yt-dlp/yt-dlp#7404]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.06.22** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Disable loading aria2.conf file. from `~/.aria2/aria2.aria2.conf` so it doesn't get overwritten by the `dir=~/Downloads` and others setting in `aria2.conf` inside `yt-dlp`

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by sergeevabc** [comment]
I totally don't get it. If a user wants to run aria2 without aria2.conf, then there is aria2c's `--no-conf` switch for that. So it should be as follows `yt-dlp --external-downloader aria2c --external-downloader-args "--no-conf" URL`. And if that switch is not specified, then aria2.conf should be respected. Hey, I want it to be respected!
