### ISSUE TITLE
Download Video From vidio.com

### ISSUE THREAD

**Issue by juannine00** [yt-dlp/yt-dlp#7411]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.06.22** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Hello, can I request can do download Premium Video from vidio.com?

I've tried using it with Streamfab, it can't download premium video

Notification
https://prnt.sc/mdP-9B6TPIZk

Link to Download
https://www.vidio.com/watch/2102937-ep-03-perasaan-yang-dipaksa

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
Show a log of an attempt to download it with yt-dlp

> Run your yt-dlp command with `-vU` flag added (`yt-dlp -vU <your command line>`)
> Copy the WHOLE output (starting with `[debug] Command-line config)` and insert it below

If it's premium content, pass cookies by adding `--cookies-from-browser chrome` to your command (or replace `chrome` with the browser you are logged into the site with)
