### ISSUE TITLE
No module named 'yt_dlp' ????

### ISSUE THREAD

**Issue by JovieLynne** [yt-dlp/yt-dlp#7412]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.06.22** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I copied and pasted the "Extract audio" snippet under the Embedding examples in the README into a python file, but when I try to run it I keep getting "ModuleNotFoundError: No module named 'yt_dlp'" from the very first line in the snippet (import yt_dlp). 

I am on Windows and installed yt-dlp using Chocolatey, but it still says the module can't be found. I also tried restarting in case that would make a difference somehow.

I feel like I am missing something obvious here so I apologize if this is a very stupid question (I'm not really a Python person).

Anyone know how I could be screwing this up?

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.06.22 [812cdfa06] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 6.0-essentials_build-www.gyan.dev (setts), ffprobe 6.0-essentials_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.05.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1851 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.06.22, Current version: stable@2023.06.22
Current Build Hash: 37e7ffe204309357cfd1388b0e2c782a30e293ddd0f2761a9a8f6afa185b3566
yt-dlp is up to date (stable@2023.06.22)
```

**Comment by pukkandan** [comment]
> I am on Windows and installed yt-dlp using Chocolatey

You obviously cannot use the executable as a library! Install using pip of the python you are running

**Comment by gamer191** [comment]
Are you really wanting to embed yt-dlp? Otherwise, just use the command line interface. To extract audio, run `yt-dlp URL --extract-audio`

**Comment by JovieLynne** [comment]
> > I am on Windows and installed yt-dlp using Chocolatey
> 
> You obviously cannot use the executable as a library! Install using pip of the python you are running

Ah!! Thank you! I didn't realize that the various installation options resulted in different things - I knew I was missing something obvious!

Got it working now, yea!!
