### ISSUE TITLE
Please give me an option to log at the same time as mp4

### ISSUE THREAD

**Issue by suzumiyabi** [yt-dlp/yt-dlp#7413]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.06.22** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I was recording with the --live-from-start option, and there was a connection error in the middle of the recording, and the file was from the restart point.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
Consider elaborating

**Comment by gamer191** [comment]
> I was recording with the --live-from-start option, and there was a connection error in the middle of the recording, and the file was from the restart point.

What? If there's a connection error, re-running it would resume the download, no?

**Comment by gamer191** [comment]
> However, the file was recorded from after the connection error.

So the first part of the video was lost?

**Comment by pukkandan** [comment]
> Make sure you are **only** asking a question and not reporting a bug or requesting a feature.
> If your question contains "isn't working" or "can you add", this is most likely the wrong template.
> If you are in doubt whether this is the right template, **USE ANOTHER TEMPLATE**!

Do not abuse the "Question" template to post incomplete issues/feature requests.

Properly fill out an appropriate issue form. Or at bare minimum, post a verbose log! Repeated abuse will be treated as spam
