### ISSUE TITLE
yt-dlp find no videos in youtube/user/videos url while they exists 

### ISSUE THREAD

**Issue by estatistics** [yt-dlp/yt-dlp#7422]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.06.22** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

while there are many videos in the following [https://www.youtube.com/@AmstelGreece/videos](url), yt-dlp founds none. 
What i am doing wrong?

```/usr/local/bin/yt-dlp -vU --limit-rate 1M --downloader aria2c -N 5  --cookies-from-browser firefox  --write-info-json   https://www.youtube.com/@AmstelGreece/videos```

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--limit-rate', '1M', '--downloader', 'aria2c', '-N', '5', '--cookies-from-browser', 'firefox', '--write-info-json', 'https://www.youtube.com/@AmstelGreece/videos']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.06.22 [812cdfa06] (zip)
[debug] Python 3.11.2 (CPython x86_64 64bit) - Linux-5.11.0-18-generic-x86_64-with-glibc2.36 (OpenSSL 3.0.9 30 May 2023, glibc 2.36)
[debug] exe versions: ffmpeg 5.1.3-1 (setts), ffprobe 5.1.3-1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.11.0, brotli-1.0.9, certifi-2022.09.24, mutagen-1.46.0, pyxattr-0.8.1, secretstorage-3.3.3, sqlite3-2.6.0, websockets-10.4
[Cookies] Extracting cookies from firefox
[debug] Extracting cookies from: "/home/elias/.mozilla/firefox/jafshm4s.default-esr-2/cookies.sqlite"
[Cookies] Extracted 3629 cookies from firefox
[debug] Proxy map: {}
[debug] Loaded 1851 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.06.22, Current version: stable@2023.06.22
Current Build Hash: 924464eb831bdb99d854b9d47ff9e1c0870eab276113adaf8a74a8561ad332b9
yt-dlp is up to date (stable@2023.06.22)
[youtube:tab] Extracting URL: https://www.youtube.com/@AmstelGreece/videos
[youtube:tab] @AmstelGreece/videos: Downloading webpage
[debug] [youtube:tab] Selected tab: '' (), Requested tab: 'videos'
[download] Downloading playlist: @AmstelGreece
[info] Writing playlist metadata as JSON to: @AmstelGreece [@AmstelGreece].info.json
[youtube:tab] Playlist @AmstelGreece: Downloading 0 items
[info] Writing updated playlist metadata as JSON to: @AmstelGreece [@AmstelGreece].info.json
[download] Finished downloading playlist: @AmstelGreece
```

**Comment by estatistics** [comment]
Debian GNU/Linux 12 (bookworm)

**Comment by estatistics** [comment]
note that it finds no tabs...

**Comment by pukkandan** [comment]
Cannot reproduce. What happens if you open the link in browser with same IP and cookies? If issue is not present in browser, pls add a `--write-pages` of a failing yt-dlp run and attach the `.dump` files so we can debug. You can send the file to discord (pukkandan#4207) / reddit (/u/pukkandan) / email (pukkandan.ytdlp@gmail.com)

**Comment by estatistics** [comment]
sent to your email by estatisticseu@gmail.com . Note that i have two independent machines - one have clean install of bookworm and the other bookworm too but not so clean. Both report same behavior. How i can find what "tabs" finds?

**Comment by estatistics** [comment]
okay, my wrong doing, it needed cookies. it searched wrong profile. sorry.
