### ISSUE TITLE
[YouTube] Channel playlist link in UU format doesn't download any videos

### ISSUE THREAD

**Issue by SlipperySlimes** [yt-dlp/yt-dlp#7424]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.06.22** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

United States

### Provide a description that is worded well enough to be understood

For many months, I have been downloading entire YouTube channels using the playlist link, such as [this](https://www.youtube.com/playlist?list=UU6nSFpj9HTCZ5t-N3Rm3-HA).

However, now it works on some channels but doesn't on others. When it doesn't work, it displays a new layout on the webpage and all I see in the output is "Downloading 0 items out of X" and it doesn't download anything. Instead of being the typical list of uploaded videos, this new webpage is a grid of rectangles that look like Shorts. For example, passing [this link](https://www.youtube.com/playlist?list=UUxqPAgubo4coVn9Lx1FuKcg) doesn't work for me. It says "Downloading 0 items out of 18057".

I guess this is some sort of new A/B testing. Some channels work and then stop working later in the day, and for others it's the other way around.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--ignore-config', 'https://www.youtube.com/playlist?list=UUxqPAgubo4coVn9Lx1FuKcg']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.06.22 [812cdfa06] (pip)
[debug] Python 3.10.11 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1t  7 Feb 2023)
[debug] exe versions: ffmpeg 5.1.2-essentials_build-www.gyan.dev (setts), ffprobe 5.1.2-essentials_build-www.gyan.dev, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.1
[debug] Proxy map: {}
[debug] Loaded 1851 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.06.22, Current version: stable@2023.06.22
yt-dlp is up to date (stable@2023.06.22)
[youtube:tab] Extracting URL: https://www.youtube.com/playlist?list=UUxqPAgubo4coVn9Lx1FuKcg
[youtube:tab] UUxqPAgubo4coVn9Lx1FuKcg: Downloading webpage
[youtube:tab] UUxqPAgubo4coVn9Lx1FuKcg: Redownloading playlist API JSON with unavailable videos
[download] Downloading playlist: Uploads from Bangy Shorts
[youtube:tab] Playlist Uploads from Bangy Shorts: Downloading 0 items of 18057
[download] Finished downloading playlist: Uploads from Bangy Shorts
```
```

**Comment by coletdjnz** [comment]
For https://www.youtube.com/playlist?list=UUxqPAgubo4coVn9Lx1FuKcg it seems like YouTube is only giving 1 page worth of shorts. So fixing support for this view on our side will only yield 100 videos :confused: 

I suggest you pass the channel url (`https://www.youtube.com/channel/UCxqPAgubo4coVn9Lx1FuKcg`) if you need more since that will get you all the channels uploads too.
