### ISSUE TITLE
videa.hu is broken

### ISSUE THREAD

**Issue by ualaa1** [yt-dlp/yt-dlp#7427]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.06.22** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Provide a description that is worded well enough to be understood

Gives out element error

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp -vU https://videa.hu/videok/nool/emberek-vlogok/immar-tizenkettedik-alkalommal-rendeztek-meg-NfwjOpsodVL6NJ9H
[debug] Command-line config: ['-vU', 'https://videa.hu/videok/nool/emberek-vlogok/immar-tizenkettedik-alkalommal-rendeztek-meg-NfwjOpsodVL6NJ9H']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.06.22 [812cdfa06] (pip)
[debug] Python 3.11.2 (CPython x86_64 64bit) - macOS-10.11.6-x86_64-i386-64bit (OpenSSL 1.1.1s  1 Nov 2022)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1851 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.06.22, Current version: stable@2023.06.22
yt-dlp is up to date (stable@2023.06.22)
[Videa] Extracting URL: https://videa.hu/videok/nool/emberek-vlogok/immar-tizenkettedik-alkalommal-rendeztek-meg-NfwjOpsodVL6NJ9H
[Videa] NfwjOpsodVL6NJ9H: Downloading webpage
[Videa] NfwjOpsodVL6NJ9H: Downloading webpage
[Videa] NfwjOpsodVL6NJ9H: Downloading webpage
ERROR: [Videa] NfwjOpsodVL6NJ9H: <Element 'error' at 0x1053b05e0>
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/yt_dlp/extractor/common.py", line 708, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/yt_dlp/extractor/videa.py", line 137, in _real_extract
    raise ExtractorError(xpath_element(
```

**Comment by torontal7** [comment]
The same error for youtube-dl. I tried with a lot of GNU/Linux systems, in no one works the download now:
`ERROR: [Videa] iCgK7uTgVIBLCypm: <Element 'error' at 0xf63746e0>`
This is very annoying because Videa is the most popular Hungarian video sharing site, some videos you can find only there. Nobody from yt-dlp developers is interested to fix this issue???

**Comment by abalage** [comment]
Digging into the code shows that the returned XML contains `Paraméter hiba! (302)` as string, meaning "parameter error" in English.
Probably the query params has changed on their side.
https://github.com/yt-dlp/yt-dlp/blob/7cccab79e7d00ed965b48b8cefce1da8a0513409/yt_dlp/extractor/videa.py#L127

I have no more resources to continue with this, I was just passing by.
