### ISSUE TITLE
How do I reconnect my disconnected segments on a noisy poor quality ADSL2+ ?

### ISSUE THREAD

**Issue by nom4d72** [yt-dlp/yt-dlp#7429]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.06.22** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I have a bad connection and since I'm sanctioned I have use VPN to connect to youtube.
this is my config:
```
-f "bestvideo[ext=mp4][height=1080]+bestaudio[ext=m4a]/bestvideo+bestaudio/best"
--embed-chapters
--embed-thumbnail
--embed-subs
--downloader aria2c
--downloader-args aria2c:"-m 0 -k 1M"
--download-archive F:\yt-dlp_history.txt
--fragment-retries', "infinite"
-R "infinite"
```
both aria2c and --fragment-retries are set to infinite and aria2c by default starts the download with 16 threads so there was no need for further adjusts

When download starts I have 16 connections after a while I keep losing my connection and eventually the last connection drops and yt-dlp moves on to the next link

is there a way if 16 links turned to 15, It would immediately try to connect and go back to 16 links?

PS: my internet has a lot noise and can't be fixed, so I can't do anything about it.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU']
[debug] User config "C:\Users\sakur\AppData\Roaming\yt-dlp\config": ['-f', 'bestvideo[ext=mp4][height=1080]+bestaudio[ext=m4a]/bestvideo+bestaudio/best', '--embed-chapters', '--embed-thumbnail', '--embed-subs', '--downloader', 'aria2c', '--downloader-args', 'aria2c:-m 0 -k 1M', '--download-archive', 'F:yt-dlp_history.txt', '-R', 'infinite', '--fragment-retries', 'infinite']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.03.04 [392389b7d]
[debug] Lazy loading extractors is disabled
[debug] Python 3.11.3 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1t  7 Feb 2023)
[debug] exe versions: ffmpeg 6.0-essentials_build-www.gyan.dev (setts), ffprobe 6.0-essentials_build-www.gyan.dev, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.05.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1840 extractors
[debug] Loading archive file 'F:yt-dlp_history.txt'
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.06.22, Current version: stable@2023.03.04
[debug] Downloading _update_spec from https://github.com/yt-dlp/yt-dlp/releases/latest/download/_update_spec
ERROR: You installed yt-dlp with a package manager or setup.py; Use that to update
```

**Comment by pukkandan** [comment]
Ue -N instead of aria2c. We cannot control the behavior of aria2c like you want.
