### ISSUE TITLE
Simpler "format" output for scripting?

### ISSUE THREAD

**Issue by Shohreh** [yt-dlp/yt-dlp#7433]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.06.22** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Hello,

For use in a script, is there a way to get a simplified list of formats a video is available? "--help" didn't… help.

When running "youtube-dlp -F myurl", I'd like to just get this:
```
ID        EXT RESOLUTION
hls-288   mp4 480x270
etc.
```

Thank you.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '-F', 'https://twitter.com/blah/status/123456']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8 (No VT), error utf-8 (No VT), screen utf-8 (No VT)
[debug] yt-dlp version stable@2023.06.22 [812cdfa06] (win_x86_exe)
[debug] Python 3.7.9 (CPython x86 32bit) - Windows-7-6.1.7601-SP1 (OpenSSL 1.1.1g  21 Apr 2020)
[debug] exe versions: ffmpeg N-109165-g9f5a9a7499-20221122 (setts), ffprobe N-109165-g9f5a9a7499-20221122
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.05.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1851 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.06.22, Current version: stable@2023.06.22
Current Build Hash: 058e24eca675aa0c9d6990c85fe214e52970b8f265a695a80d1142c6c0118627
yt-dlp is up to date (stable@2023.06.22)
[twitter] Extracting URL: https://twitter.com/blah/status/123456
[twitter] 123456: Downloading guest token
[twitter] 123456: Downloading GraphQL JSON
[debug] [twitter] Extracting from video info: 123456
[twitter] 123456: Downloading m3u8 information
[debug] Sort order given by extractor: res, br, size, proto
[debug] Formats sorted by: hasvid, ie_pref, res, br, size, proto, lang, quality, fps, hdr:12(7), vcodec:vp9.2(10), channels, acode
c, asr, vext, aext, hasaud, source, id
[info] Available formats for 123456:
ID        EXT RESOLUTION |  FILESIZE   TBR PROTO | VCODEC      ACODEC
------------------------------------------------------------------------
hls-288   mp4 480x270    | ~ 3.28MiB  288k m3u8  | avc1.4d001e mp4a.40.2
http-288  mp4 480x270    | ˜ 3.28MiB  288k https | unknown     unknown
hls-832   mp4 640x360    | ~ 9.47MiB  832k m3u8  | avc1.4d001f mp4a.40.2
http-832  mp4 640x360    | ˜ 9.47MiB  832k https | unknown     unknown
hls-2176  mp4 854x480    | ~24.78MiB 2176k m3u8  | avc1.64001f mp4a.40.2
http-2176 mp4 854x480    | ˜24.78MiB 2176k https | unknown     unknown
```

**Comment by pukkandan** [comment]
Not really. Use `--print %(formats)j` or similar and parse it into whatever form you need.

**Comment by Shohreh** [comment]
Thank you.

**Comment by Shohreh** [comment]
Thank you.
