### ISSUE TITLE
How to compile standalone binary?

### ISSUE THREAD

**Issue by HackerShohag** [yt-dlp/yt-dlp#7437]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.06.22** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I am trying to understand how this project has been compiled to standalone binaries, "yt-dlp_linux", "yt-dlp_linux_aarch64". I also want to compile like this. But I don't know how. In the description there's a different method of compilation which doesn't explain this process afaik. Please, help me.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by Grub4K** [comment]
You can look into `.github/workflows/build.yml`. Those are building the artifacts using GitHub Workflows. The easiest way to build these yourself is to fork the repository and run the build workflow. If that is not an option, try and follow the commands in the respective build workflow. For that, see the Makefile for more info.

`pyinstaller` is used to bundle a binary.
The `yt-dlp_linux` build uses mamba (conda) to create an agnostic build and bundles python with it. The aarch64 build is using the `run-on-arch` action to build the binary the same way on the respective system.

**Comment by pukkandan** [comment]
https://github.com/yt-dlp/yt-dlp#compile
