### ISSUE TITLE
Requesting support for axs.tv

### ISSUE THREAD

**Issue by coolelbow** [yt-dlp/yt-dlp#7451]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a new site support request
- [X] I've verified that I'm running yt-dlp version **2023.06.22** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that none of provided URLs [violate any copyrights](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#is-the-website-primarily-used-for-piracy) or contain any [DRM](https://en.wikipedia.org/wiki/Digital_rights_management) to the best of my knowledge
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and am willing to share it if required

### Region

USA

### Example URLs

https://www.axs.tv/video/5f2a2ee9b70e4fe321f59c49/

### Provide a description that is worded well enough to be understood

I would like to be able to download videos from this site. I don't know how to check for DRM but I ticked the box saying I did anyhow. So that isn't actually confirmed. Sorry about that.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
C:\Users\coolelbow\Downloads>yt-dlp.exe -vU https://www.axs.tv/video/5f2a2ee9b70e4fe321f59c49/
[debug] Command-line config: ['-vU', 'https://www.axs.tv/video/5f2a2ee9b70e4fe321f59c49/']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.06.22 [812cdfa06] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19041-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: none
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.05.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1851 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.06.22, Current version: stable@2023.06.22
Current Build Hash: 37e7ffe204309357cfd1388b0e2c782a30e293ddd0f2761a9a8f6afa185b3566
yt-dlp is up to date (stable@2023.06.22)
[generic] Extracting URL: https://www.axs.tv/video/5f2a2ee9b70e4fe321f59c49/
[generic] 5f2a2ee9b70e4fe321f59c49: Downloading webpage
WARNING: [generic] Falling back on generic information extractor
[generic] 5f2a2ee9b70e4fe321f59c49: Extracting information
[debug] Looking for embeds
ERROR: Unsupported URL: https://www.axs.tv/video/5f2a2ee9b70e4fe321f59c49/
Traceback (most recent call last):
  File "yt_dlp\YoutubeDL.py", line 1555, in wrapper
  File "yt_dlp\YoutubeDL.py", line 1631, in __extract_info
  File "yt_dlp\extractor\common.py", line 708, in extract
  File "yt_dlp\extractor\generic.py", line 2568, in _real_extract
yt_dlp.utils.UnsupportedError: Unsupported URL: https://www.axs.tv/video/5f2a2ee9b70e4fe321f59c49/
```

**Comment by barsnick** [comment]
Wow, I recently felt the need for such an extractor as well. So I crafted my own. I wasn't sure whether to create a pull request (since I figured out how to use it as a plugin), but as I notice your issue now, I will just do so, as I believe my code to be pretty un-hackish.

Cheers!

(Note: no geo-restriction, for all the videos I found, no DRM.)
