### ISSUE TITLE
Update downloaded files with newly requested options

### ISSUE THREAD

**Issue by 424778940z** [yt-dlp/yt-dlp#7457]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.06.22** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Is it possible to let yt-dlp be aware of what's already downloaded while downloading the same URL but with different options?

Let's say I downloaded a YouTube video with live chat but without comments, and later I want to download the same video with comments as well. Currently, I have to remove it from the archived list and then download it again, which seems to pulling the same video again, not just the metadata. (I understand there are options for download few type of metadata only, but it still have to be merged manually)

This may seem unnecessary for a single video, but it's really useful when archiving a whole channel and keeping everything updated with the same standards without download everything again.

I'm aware of the `--fixup` option, but the help message sounds like it is meant to actually fix broken files instead of making changes to downloaded files.

Am I missing something? Or could this be a new feature?

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
> Is it possible to let yt-dlp be aware of what's already downloaded while downloading the same URL but with different options?

No, and out of scope

**Comment by pukkandan** [comment]
> which seems to pulling the same video again, not just the metadata.

If the video file exists with same name, yt-dlp will use it and not redownload.
