### ISSUE TITLE
Unable to download webpage: HTTP Error 404: Not Found

### ISSUE THREAD

**Issue by phj-555** [yt-dlp/yt-dlp#7466]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2023.06.22** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

I try to use yt-dlp with the link and it does not work to download. 

But I can use Xtreme Download Manager and it works - video download and play. I get the link from Xtreme that it uses, and it does not work with yt-dlp. 

I try different links to new videos, same thing. 

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', 'https://ojzx.mcloud.to/1aa38422f30a4f42a6d16218ceb9aa408d6ef6164abab3b5554472abfa7dc0ca2543d210103e63b3aa76d45da94aec83ff8ccf1f8a7cd2fed3e5f16a1025af83658a46f40905bb5f458ea3bf7c44222f58268f2f101f3296d99abc008cf941cc327ceb140169bd12bb/r/hls/720/720.m3u8']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.06.22 [812cdfa06] (pip)
[debug] Python 3.11.3 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1t  7 Feb 2023)
[debug] exe versions: ffmpeg N-110422-g7b2851b290-20230430 (setts), ffprobe N-110422-g7b2851b290-20230430
[debug] Optional libraries: Cryptodome-3.17, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.2
[debug] Proxy map: {}
[debug] Loaded 1851 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.06.22, Current version: stable@2023.06.22
yt-dlp is up to date (stable@2023.06.22)
[generic] Extracting URL: https://ojzx.mcloud.to/1aa38422f30a4f42a6d16218ceb9aa408d6ef6164abab3b5554472abfa7dc0ca2543d210103e63b3aa76d45da94aec83ff8ccf1f8a7cd2fed3e5f16a1025af83658a46f40905bb5f458ea3bf7c44222f58268f2f101f3296d99abc008cf941cc327ceb140169bd12bb/r/hls/720/720.m3u8
[generic] 720: Downloading webpage
ERROR: [generic] None: Unable to download webpage: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "C:\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\extractor\common.py", line 708, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\extractor\generic.py", line 2430, in _real_extract
    full_response = self._request_webpage(url, video_id, headers={
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\extractor\common.py", line 853, in _request_webpage
    raise ExtractorError(errmsg, cause=err)

  File "C:\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\extractor\common.py", line 835, in _request_webpage
    return self._downloader.urlopen(self._create_request(url_or_request, data, headers, query))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AppData\Local\Programs\Python\Python311\Lib\site-packages\yt_dlp\YoutubeDL.py", line 3786, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 525, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 634, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "C:\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 563, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "C:\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```

**Comment by dirkf** [comment]
>[x] I've checked that all provided URLs are playable in a browser with the same IP and same login details

404 in browser ! Is the URL in the log the same as used in the browser, or is there an actual video page from which the problem URL was captured?

Maybe the problem URL expires before it can be pasted into the console for yt-dlp?

**Comment by phj-555** [comment]
> > [x] I've checked that all provided URLs are playable in a browser with the same IP and same login details
> 
> 404 in browser ! Is the URL in the log the same as used in the browser, or is there an actual video page from which the problem URL was captured?
> 
> Maybe the problem URL expires before it can be pasted into the console for yt-dlp?

URL in log is same in Xtreme - Xtreme use this URL to download. I paste URL in my browser & it download the .m3u8 file

**Comment by dirkf** [comment]
Still 404:
```console
$ wget 'https://ojzx.mcloud.to/1aa38422f30a4f42a6d16218ceb9aa408d6ef6164abab3b5554472abfa7dc0ca2543d210103e63b3aa76d45da94aec83ff8ccf1f8a7cd2fed3e5f16a1025af83658a46f40905bb5f458ea3bf7c44222f58268f2f101f3296d99abc008cf941cc327ceb140169bd12bb/r/hls/720/720.m3u8'
--2023-06-30 17:20:27--  https://ojzx.mcloud.to/1aa38422f30a4f42a6d16218ceb9aa408d6ef6164abab3b5554472abfa7dc0ca2543d210103e63b3aa76d45da94aec83ff8ccf1f8a7cd2fed3e5f16a1025af83658a46f40905bb5f458ea3bf7c44222f58268f2f101f3296d99abc008cf941cc327ceb140169bd12bb/r/hls/720/720.m3u8
Resolving ojzx.mcloud.to (ojzx.mcloud.to)... 109.236.80.41
Connecting to ojzx.mcloud.to (ojzx.mcloud.to)|109.236.80.41|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2023-06-30 17:20:28 ERROR 404: Not Found.

$
```

**Comment by bashonly** [comment]
It looks like Xtreme Download Manager integrates with the web browser, so it is likely grabbing some necessary http headers from your browser and sending them with the request

**Comment by dirkf** [comment]
If so, this is actually a site support request in disguise. As I previously asked:
>... is there an actual video page from which the problem URL was captured?
