### ISSUE TITLE
Regression: “Incomplete data received” when downloading YouTube comments sorted by top

### ISSUE THREAD

**Issue by emphoeller** [yt-dlp/yt-dlp#7474]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.06.22** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Provide a description that is worded well enough to be understood

For some YouTube videos, the download of the comments consistently fails relatively early with the error “Incomplete data received” if (and only if) the comments are sorted by top. This is not caused by some error on YouTube’s side¹ because it actually works with an earlier release of yt-dlp. The regression was apparently introduced with release 2023.06.21 (tested with [this video](https://www.youtube.com/watch?v=dQw4w9WgXcQ)):

| Sorting | 2023.03.04 | 2023.06.21 | 2023.06.22 |
|--------:|:----------:|:----------:|:----------:|
| new     | succeeds   | succeeds   | succeeds   |
| top     | succeeds   | fails      | fails      |

(I didn’t download all of the two million comments to Never Gonna Give You Up, so I can’t actually say for sure that the download doesn’t fail later down the line.)

¹ Some issues were closed because “Incomplete data received” was interpreted to point to a server-side issue, but this shows that that isn’t always the case. Maybe they should be revisited? These were the ones I came across during my (brief) research: [1](https://github.com/yt-dlp/yt-dlp/issues/1787), [2](https://github.com/yt-dlp/yt-dlp/issues/3827), [3](https://github.com/yt-dlp/yt-dlp/issues/4669)

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '--skip-download', '--write-info-json', '--write-comments', '--extractor-args', 'youtube:comment_sort=top', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.06.22 [812cdfa06]
[debug] Lazy loading extractors is disabled
[debug] Python 3.10.6 (CPython x86_64 64bit) - Linux-5.19.0-46-generic-x86_64-with-glibc2.35 (OpenSSL 3.0.2 15 Mar 2022, glibc 2.35)
[debug] exe versions: ffmpeg 4.4.2 (setts), ffprobe 4.4.2
[debug] Optional libraries: pyxattr-0.7.2, secretstorage-3.3.1, sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Loaded 1851 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.06.22, Current version: stable@2023.06.22
yt-dlp is up to date (stable@2023.06.22)
[youtube] Extracting URL: https://www.youtube.com/watch?v=dQw4w9WgXcQ
[youtube] dQw4w9WgXcQ: Downloading webpage
[youtube] dQw4w9WgXcQ: Downloading ios player API JSON
[youtube] dQw4w9WgXcQ: Downloading android player API JSON
[youtube] dQw4w9WgXcQ: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[youtube] Downloading comment section API JSON
[youtube] Downloading ~2263496 comments
[youtube] Sorting comments by top comments
[youtube] Downloading comment API JSON page 1 (0/~2263496)
[youtube]     Downloading comment API JSON reply thread 1 (1/~2263496)
[youtube]        Downloading comment replies API JSON page 1 (11/~2263496)
[youtube]        Downloading comment replies API JSON page 2 (61/~2263496)
[youtube]        Downloading comment replies API JSON page 3 (110/~2263496)
[youtube]        Downloading comment replies API JSON page 4 (160/~2263496)
[youtube]        Downloading comment replies API JSON page 5 (207/~2263496)
[youtube]        Downloading comment replies API JSON page 6 (256/~2263496)
[youtube]        Downloading comment replies API JSON page 7 (306/~2263496)
[youtube]        Downloading comment replies API JSON page 8 (355/~2263496)
[youtube]        Downloading comment replies API JSON page 9 (403/~2263496)
[youtube]        Downloading comment replies API JSON page 10 (452/~2263496)
[youtube]     Downloading comment API JSON reply thread 2 (490/~2263496)
[youtube]        Downloading comment replies API JSON page 1 (500/~2263496)
[youtube]        Downloading comment replies API JSON page 2 (549/~2263496)
[youtube]        Downloading comment replies API JSON page 3 (596/~2263496)
[youtube]        Downloading comment replies API JSON page 4 (645/~2263496)
[youtube]        Downloading comment replies API JSON page 5 (693/~2263496)
[youtube]        Downloading comment replies API JSON page 6 (742/~2263496)
[youtube]        Downloading comment replies API JSON page 7 (792/~2263496)
[youtube]        Downloading comment replies API JSON page 8 (839/~2263496)
[youtube]        Downloading comment replies API JSON page 9 (889/~2263496)
[youtube]        Downloading comment replies API JSON page 10 (937/~2263496)
[youtube]     Downloading comment API JSON reply thread 3 (971/~2263496)
[youtube]        Downloading comment replies API JSON page 1 (981/~2263496)
[youtube]     Downloading comment API JSON reply thread 4 (1018/~2263496)
[youtube]     Downloading comment API JSON reply thread 5 (1026/~2263496)
[youtube]     Downloading comment API JSON reply thread 6 (1037/~2263496)
[youtube]        Downloading comment replies API JSON page 1 (1046/~2263496)
[youtube]        Downloading comment replies API JSON page 2 (1094/~2263496)
[youtube]        Downloading comment replies API JSON page 3 (1141/~2263496)
[youtube]        Downloading comment replies API JSON page 4 (1186/~2263496)
[youtube]        Downloading comment replies API JSON page 5 (1227/~2263496)
[youtube]        Downloading comment replies API JSON page 6 (1263/~2263496)
[youtube]        Downloading comment replies API JSON page 7 (1307/~2263496)
[youtube]        Downloading comment replies API JSON page 8 (1350/~2263496)
[youtube]        Downloading comment replies API JSON page 9 (1383/~2263496)
[youtube]        Downloading comment replies API JSON page 10 (1433/~2263496)
[youtube]     Downloading comment API JSON reply thread 7 (1461/~2263496)
[youtube]     Downloading comment API JSON reply thread 8 (1465/~2263496)
[youtube]     Downloading comment API JSON reply thread 9 (1468/~2263496)
[youtube]        Downloading comment replies API JSON page 1 (1477/~2263496)
[youtube]        Downloading comment replies API JSON page 2 (1523/~2263496)
[youtube]        Downloading comment replies API JSON page 3 (1566/~2263496)
[youtube]        Downloading comment replies API JSON page 4 (1610/~2263496)
[youtube]        Downloading comment replies API JSON page 5 (1653/~2263496)
[youtube]        Downloading comment replies API JSON page 6 (1701/~2263496)
[youtube]        Downloading comment replies API JSON page 7 (1747/~2263496)
[youtube]        Downloading comment replies API JSON page 8 (1795/~2263496)
[youtube]        Downloading comment replies API JSON page 9 (1840/~2263496)
[youtube]        Downloading comment replies API JSON page 10 (1887/~2263496)
[youtube]     Downloading comment API JSON reply thread 10 (1924/~2263496)
[youtube]     Downloading comment API JSON reply thread 11 (1926/~2263496)
[youtube]     Downloading comment API JSON reply thread 12 (1930/~2263496)
[youtube]     Downloading comment API JSON reply thread 13 (1932/~2263496)
[youtube]        Downloading comment replies API JSON page 1 (1941/~2263496)
[youtube]        Downloading comment replies API JSON page 2 (1988/~2263496)
[youtube]        Downloading comment replies API JSON page 3 (2037/~2263496)
[youtube]        Downloading comment replies API JSON page 4 (2086/~2263496)
[youtube]        Downloading comment replies API JSON page 5 (2135/~2263496)
[youtube]        Downloading comment replies API JSON page 6 (2184/~2263496)
[youtube]        Downloading comment replies API JSON page 7 (2232/~2263496)
[youtube]        Downloading comment replies API JSON page 8 (2280/~2263496)
[youtube]        Downloading comment replies API JSON page 9 (2322/~2263496)
[youtube]        Downloading comment replies API JSON page 10 (2367/~2263496)
[youtube] Downloading comment API JSON page 2 (2403/~2263496)
[youtube]     Downloading comment API JSON reply thread 1 (2404/~2263496)
WARNING: [youtube] Incomplete data received. Retrying (1/3)...
[youtube]     Downloading comment API JSON reply thread 1 (2404/~2263496)
WARNING: [youtube] Incomplete data received. Retrying (2/3)...
[youtube]     Downloading comment API JSON reply thread 1 (2404/~2263496)
WARNING: [youtube] Incomplete data received. Retrying (3/3)...
[youtube]     Downloading comment API JSON reply thread 1 (2404/~2263496)
ERROR: Incomplete data received
Traceback (most recent call last):
  File "<path>/yt_dlp/YoutubeDL.py", line 1555, in wrapper
    return func(self, *args, **kwargs)
  File "<path>/yt_dlp/YoutubeDL.py", line 1652, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "<path>/yt_dlp/YoutubeDL.py", line 1711, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "<path>/yt_dlp/YoutubeDL.py", line 2728, in process_video_result
    self.post_extract(info_dict)
  File "<path>/yt_dlp/YoutubeDL.py", line 3496, in post_extract
    actual_post_extract(info_dict or {})
  File "<path>/yt_dlp/YoutubeDL.py", line 3494, in actual_post_extract
    info_dict.update(post_extractor())
  File "<path>/yt_dlp/extractor/common.py", line 3590, in extractor
    comments.append(next(generator))
  File "<path>/yt_dlp/extractor/youtube.py", line 3563, in _real_comment_extract
    yield from self._comment_entries(renderer, ytcfg, video_id)
  File "<path>/yt_dlp/extractor/youtube.py", line 3536, in _comment_entries
    for entry in extract_thread(continuation_items):
  File "<path>/yt_dlp/extractor/youtube.py", line 3447, in extract_thread
    yield from itertools.islice(comment_entries_iter, min(
  File "<path>/yt_dlp/extractor/youtube.py", line 3512, in _comment_entries
    response = self._extract_response(
  File "<path>/yt_dlp/extractor/youtube.py", line 951, in _extract_response
    for retry in self.RetryManager():
  File "<path>/yt_dlp/utils/_utils.py", line 5628, in __iter__
    self.error_callback(self.error, self.attempt, self.retries)
  File "<path>/yt_dlp/extractor/common.py", line 3751, in _error_or_warning
    RetryManager.report_retry(
  File "<path>/yt_dlp/utils/_utils.py", line 5636, in report_retry
    raise e
yt_dlp.utils.ExtractorError: Incomplete data received
```

**Comment by coletdjnz** [comment]
Hmm. There was a change in the recent version to handle a case where YouTube would give no comments and send us in an infinite loop.

However this doesn't seem to be the case here. 🤔 Seems to be failing on a particular comment thread that may only have one page? And even if the incomplete data error was true it shouldn't be killing the entire comment download there.

**Comment by coletdjnz** [comment]
Actually, looking into it, this appears to be expected. YouTube is providing empty comment reply threads (Incomplete Data) and the older version was failing to identify it.

Pass `--ignore-errors` for it to safely continue with getting the rest of the comments. I may make this so it also continues if ignore errors is `only_download` (default for cli) until we have more precise incomplete data error control exposed.

There is quite a few more other cases of this happening when passing that with this video, including some looping threads.

**Comment by pukkandan** [comment]
> If I understand correctly, even with the future change that you suggest, we would have to choose whether we want to ignore all incomplete data errors or none

In the PR, this error will be ignored unless `--abort-on-error` is explicitly passed

>  but we can’t only ignore them in this one specific circumstance in which we actually should expect them.

What other circumstance is there? "Incomplete data" is always given due to bug in YouTube and always reflects the same behavior in browser. Whether the bug is temporary or permanent on their side, we have no way of knowing.

**Comment by coletdjnz** [comment]
The "empty" reply thread in this case is considered incomplete, as YouTube is saying there are more replies and gives us a continuation token to request the response.. which contains no replies.

This may or may not be a one time error and may differ b/w videos, it's just the nature of Youtube's backend.

The PR just raises a warning when this happens by default - which is closer to what we want. More fine grained control over the incomplete data errors would be a nice and that can maybe be a future improvement.

**Comment by ddawson** [comment]
> This may or may not be a one time error and may differ b/w videos.

I don't think it's an error at all. At least, not in most cases. YouTube regularly shadow-hides comments it deems unacceptable (according to whatever petty criteria it has in place). However, for whatever reason, it appears to count the true number of comments instead of the number of *visible* comments, which, in particular, can make it easy to see how many replies to visible comments have been hidden (well, more or less; if it's been a while since you loaded the main comments, new replies may have been posted, which makes the shown count inaccurate in its own way).

The example in the screenshot is most likely one where the only reply got hidden. It gives the true count of 1, but when you request the replies, it has none to show. (I guess it's also possible, the reply just happened to have been deleted before you requested it, but I think shadow-hiding is the more likely reason.)
