### ISSUE TITLE
cannot support vlive channel download

### ISSUE THREAD

**Issue by ashoffire** [yt-dlp/yt-dlp#748]
D:\Desktop>yt-dlp https://www.vlive.tv/channel/EDBF/board/3484

[vlive:channel] EDBF: Downloading decode channel code
ERROR: Unable to download JSON metadata: HTTP Error 401: Unauthorized (caused by <HTTPError 401: 'Unauthorized'>); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.

**Comment by pukkandan** [comment]
### IGNORING THE ISSUE TEMPLATE WILL RESULT IN ISSUE CLOSED AS INCOMPLETE

Create a new issue using the correct template with all necessary information including the `--verbose` output
