### ISSUE TITLE
Smotrim.ru extractor failing on particular video

### ISSUE THREAD

**Issue by nicolaasjan** [yt-dlp/yt-dlp#7481]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.06.22** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

The Netherlands

### Provide a description that is worded well enough to be understood

As user @qzmtch mentioned in [comment](https://github.com/yt-dlp/yt-dlp/pull/5015#issuecomment-1522119738) on pull request #5015 yt-dlp fails on the video on this page:
https://smotrim.ru/brand/58339

`ERROR: [Smotrim] 58339: There are no video in this page.`

`playlist.m3u8` URL obtained by "[The Stream Detector](https://addons.mozilla.org/en-US/firefox/addon/hls-stream-detector/)" given to yt-dlp works fine.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp -vU --ignore-config https://smotrim.ru/brand/58339
[debug] Command-line config: ['-vU', '--ignore-config', 'https://smotrim.ru/brand/58339']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2023.07.01 [af1fd12f6] (zip)
[debug] Python 3.8.10 (CPython x86_64 64bit) - Linux-5.4.0-153-generic-x86_64-with-glibc2.29 (OpenSSL 1.1.1f  31 Mar 2020, glibc 2.31)
[debug] exe versions: ffmpeg N-110521-g2dd9b4071c-Nico-20230508 (fdk,setts), ffprobe N-110521-g2dd9b4071c-Nico-20230508, phantomjs 2.1.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.05.07, mutagen-1.46.0, secretstorage-3.3.3, sqlite3-2.6.0, websockets-11.0.3, xattr-0.9.6
[debug] Proxy map: {}
[debug] Loaded 1854 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp-nightly-builds/releases/latest
Available version: nightly@2023.06.30.182724, Current version: nightly@2023.07.01
Current Build Hash: 36b1577fb78dac4f06d465f6629cd3e9412a002ab469f36063ddbdf61e5f44f4
yt-dlp is up to date (nightly@2023.07.01)
[Smotrim] Extracting URL: https://smotrim.ru/brand/58339
[Smotrim] 58339: Resolving brand link
ERROR: [Smotrim] 58339: There are no video in this page.
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/common.py", line 708, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/yt-dlp/yt_dlp/extractor/smotrim.py", line 61, in _real_extract
    raise ExtractorError('There are no video in this page.', expected=True)
```

**Comment by nicolaasjan** [comment]
Hmm...
For some reason this particular video now downloaded fine.

Closing.

**Comment by zubrRB** [comment]
Stopped downloading videos because it gives a link to a blocked server.

`cdn-v.smotrim.ru/` — 403 Forbidden
https://cdn-v.smotrim.ru/_cdn_auth/secure/v/vh/mp4/fhd-wide/002/946/936.mp4?auth=mh&vid=2946936 

`cdn-v.rtr-vesti.ru` — download available
https://cdn-v.rtr-vesti.ru/_cdn_auth/secure/v/vh/mp4/fhd-wide/002/946/936.mp4?auth=mh&vid=2946936

**Comment by qzmtch** [comment]
> Stopped downloading videos because it gives a link to a blocked server.
> 
> `cdn-v.smotrim.ru` — 403 Forbidden https://cdn-v.smotrim.ru/_cdn_auth/secure/v/vh/mp4/fhd-wide/002/946/936.mp4?auth=mh&vid=2946936
> 
> `cdn-v.rtr-vesti.ru` — download available https://cdn-v.rtr-vesti.ru/_cdn_auth/secure/v/vh/mp4/fhd-wide/002/946/936.mp4?auth=mh&vid=2946936

This domain change does not work with all videos. This only works with videos that are on the vesti.ru website

On the site smotrim.ru videos are now available only via the m3u8 link

**Comment by qzmtch** [comment]
The API gives out such links https://i.imgur.com/V6DC1L3.png  
that’s why yt-dlp uses them, the problem is on the side of the smotrim site

**Comment by zubrRB** [comment]
Smotrim has made a number of changes in recent months, including to the player code, to make it impossible to obtain direct links to MP4 videos. A month ago they blocked access to their server, but changing the server returns the ability to download, including their own content with the site logo.  This service also provides working MP4 links. https://savevideo.me
https://smotrim.ru/brand/62417  
https://smotrim.ru/brand/67561

**Comment by qzmtch** [comment]
> Smotrim has made a number of changes in recent months, including to the player code, to make it impossible to obtain direct links to MP4 videos. A month ago they blocked access to their server, but changing the server returns the ability to download, including their own content with the site logo. This service also provides working MP4 links. https://savevideo.me https://smotrim.ru/brand/62417 https://smotrim.ru/brand/67561

this only works for videos that are also on the vesti.ru website, but not for all videos on the site smotrim.ru

**Comment by zubrRB** [comment]
Vesti.ru is a news site with content on this topic. Smotrim as a service uses its server, although old videos that were previously available from its own server are available, and now they can be downloaded to MP4 only by changing the domain. cdn-v.smotrim.ru in this case acts as a means of deception.

**Comment by nicolaasjan** [comment]
> https://smotrim.ru/brand/65619 for more videos from the site this does not work

That video downloads here:

```bash
yt-dlp -v --ignore-config https://smotrim.ru/brand/65619
[debug] Command-line config: ['-v', '--ignore-config', 'https://smotrim.ru/brand/65619']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version local@2024.03.05 [cf91400a1] (zip)
[debug] Python 3.8.10 (CPython x86_64 64bit) - Linux-5.4.0-172-generic-x86_64-with-glibc2.29 (OpenSSL 1.1.1f  31 Mar 2020, glibc 2.31)
[debug] exe versions: ffmpeg N-113699-g0c8e64e268-20240219 (setts), ffprobe N-113699-g0c8e64e268-20240219, phantomjs 2.1.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.20.0, brotli-1.1.0, certifi-2024.02.02, mutagen-1.47.0, requests-2.31.0, secretstorage-3.3.3, sqlite3-3.31.1, urllib3-2.2.0, websockets-12.0, xattr-0.9.6
[debug] Proxy map: {}
[debug] Request Handlers: urllib, requests, websockets
[debug] Loaded 1835 extractors
[Smotrim] Extracting URL: https://smotrim.ru/brand/65619
[Smotrim] 65619: Resolving brand link
[RUTV] Extracting URL: https://player.vgtrk.com/iframe/video/id/2246408
[RUTV] 2246408: Downloading JSON
[RUTV] 2246408: Downloading m3u8 information
[debug] Sort order given by extractor: source
[debug] Formats sorted by: hasvid, ie_pref, source, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 2246408: Downloading 1 format(s): hls-1200
[debug] Invoking hlsnative downloader on "https://cdn-v.smotrim.ru/_cdn_auth/secure/v/vh/vod_hls/definst/smil:vh/smil/002/356/578_d20201202180625.smil/chunklist_b1200000_pd6413000.m3u8"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 668
[download] Destination: Остров сокровищ. Фильм-мюзикл [2246408].mp4
[download]   2.4% of ~ 735.68MiB at    1.63MiB/s ETA 07:09 (frag 16/668)^C
ERROR: Interrupted by user
```

**Comment by bashonly** [comment]
@zubrRB open a new issue with a verbose log. The OP is unrelated to your issue

**Comment by zubrRB** [comment]
https://github.com/yt-dlp/yt-dlp/issues/9372

**Comment by qzmtch** [comment]
> That video downloads here:

yes, I wrote about this above that only HLS streams work
and mp4 gives error 403, and works with a changed domain only for those videos that are on the vesti.ru website

**Comment by zubrRB** [comment]
The site deliberately provides a broken link so that it cannot be downloaded.

**Comment by qzmtch** [comment]
> The site deliberately provides a broken link so that it cannot be downloaded.

Do you understand that for many videos changing the domain does not work? what's the point of this if there are HLS links? on which the same video is broadcast
