### ISSUE TITLE
"Open Video Downloader" won't work

### ISSUE THREAD

**Issue by RoscoeD** [yt-dlp/yt-dlp#7486]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.06.22** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I'm not a programmer so the vast majority of the information in this site might as well be in a foreign language.

I paid a company to provide me a video.  They do that by posting it on YouTube and then directing me to software called "Open Video Downloader" that apparently is a fancy name front end for yt-dlp. However it's not working as described and I'm lost. I'm getting errors that I can't decipher.  Here's what it says "ERROR: [youtube] yUfoCbmrHUI: Unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; type  yt-dlp -U  to update. Be sure to call yt-dlp with the --verbose flag and include its complete output."

1) I just downloaded the program so I assume it's the most current (listed as 2.4.0...nothing like the 2023.06.22 that described above
2) Just in case I needed to update the software I went to the update instructions page above and clicked on the macOS button...and a file downloaded that was completely unreadable by my computer
3) The first attempt to run the software on the YouTube link failed, and told me to install some toolbox. So I did
4) Next attempt went a little longer before failing...then presented the error I pasted above.
5) I keep seeing instructions on how to run the code with "flags"  like verbose and debug but I have no clue how I'm supposed to do that....I'm just trying to paste the video URL into the box as I was instructed and it's not working (Note I have virtually no experience in command like work on Macs).

If someone can help me with easy to understand instructions (I'm not an idiot but I'm also not a coder so...).  I paid good money for the video and would like to be able to download my copy.

Thanks!!

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
I have no idea how to generate this.  Like I said above I'm not experienced in using the command line in macOS.
```

**Comment by coletdjnz** [comment]
Report it to the developer of Open Video Downloader, not us.

The error is because it is using an old version of youtube-dl/p.
