### ISSUE TITLE
--download-archive,  seems exits max items quantity, old record will be override if more than 378

### ISSUE THREAD

**Issue by libiao7** [yt-dlp/yt-dlp#7489]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2023.06.22** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

"--download-archive"  has no effect when items quantity in archive.txt more than 378

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
yt-dlp.exe  --download-archive ~\archive.txt   url
```

**Comment by bashonly** [comment]
I can't reproduce the issue
```shellsession
$ yt-dlp --flat-playlist --lazy-playlist -O "youtube %(id)s" -I1-379 "https://www.youtube.com/@LinusTechTips/videos" > a.txt
$ wc -l a.txt
379 a.txt
$ head -n1 a.txt
youtube yI7fV88T8A0
$ yt-dlp --download-archive a.txt yI7fV88T8A0
[Youtube] yI7fV88T8A0: has already been recorded in the archive
```

Show a verbose log demonstrating your issue

**Comment by libiao7** [comment]
> I can't reproduce the issue
> 
> ```
> $ yt-dlp --flat-playlist --lazy-playlist -O "youtube %(id)s" -I1-379 "https://www.youtube.com/@LinusTechTips/videos" > a.txt
> $ wc -l a.txt
> 379 a.txt
> $ head -n1 a.txt
> youtube yI7fV88T8A0
> $ yt-dlp --download-archive a.txt yI7fV88T8A0
> [Youtube] yI7fV88T8A0: has already been recorded in the archive
> ```
> 
> Show a verbose log demonstrating your issue

idk -I1-379 means

if your a.txt has 378 items, then you download a new video with '--download-archive a.txt', a new record will add to a.txt's end line successfully ,but first line will be override, a.txt can't hold 379 items.

**Comment by bashonly** [comment]
Again, show a verbose log!! It's likely that something else is causing your issue, and we can only diagnose what that is if you show a proper log.

I can't reproduce the issue; I am demonstrating that `--download-archive` works beyond when 378 entries are recorded:
```shellsession
$ wc -l a.txt  # how many items are in my download archive:
379 a.txt
$ yt-dlp --ignore-config --download-archive a.txt BaW_jenozKc
[youtube] Extracting URL: BaW_jenozKc
[youtube] BaW_jenozKc: Downloading webpage
[youtube] BaW_jenozKc: Downloading ios player API JSON
[youtube] BaW_jenozKc: Downloading android player API JSON
[youtube] BaW_jenozKc: Downloading m3u8 information
[info] BaW_jenozKc: Downloading 1 format(s): 248+251
[download] Destination: youtube-dl test video ＂'⧸⧹ä↭𝕐 [BaW_jenozKc].f248.webm
[download] 100% of  965.31KiB in 00:00:00 at 4.16MiB/s
[download] Destination: youtube-dl test video ＂'⧸⧹ä↭𝕐 [BaW_jenozKc].f251.webm
[download] 100% of  138.96KiB in 00:00:00 at 740.93KiB/s
[Merger] Merging formats into "youtube-dl test video ＂'⧸⧹ä↭𝕐 [BaW_jenozKc].webm"
Deleting original file youtube-dl test video ＂'⧸⧹ä↭𝕐 [BaW_jenozKc].f251.webm (pass -k to keep)
Deleting original file youtube-dl test video ＂'⧸⧹ä↭𝕐 [BaW_jenozKc].f248.webm (pass -k to keep)
$ tail -n1 a.txt  # what is the last entry in my download archive:
youtube BaW_jenozKc
$ yt-dlp --ignore-config --download-archive a.txt BaW_jenozKc
[Youtube] BaW_jenozKc: has already been recorded in the archive
```

**Comment by libiao7** [comment]
> Again, show a verbose log!! It's likely that something else is causing your issue, and we can only diagnose what that is if you show a proper log.
> 
> I can't reproduce the issue; I am demonstrating that `--download-archive` works beyond when 378 entries are recorded:
> 
> ```
> $ wc -l a.txt  # how many items are in my download archive:
> 379 a.txt
> $ yt-dlp --ignore-config --download-archive a.txt BaW_jenozKc
> [youtube] Extracting URL: BaW_jenozKc
> [youtube] BaW_jenozKc: Downloading webpage
> [youtube] BaW_jenozKc: Downloading ios player API JSON
> [youtube] BaW_jenozKc: Downloading android player API JSON
> [youtube] BaW_jenozKc: Downloading m3u8 information
> [info] BaW_jenozKc: Downloading 1 format(s): 248+251
> [download] Destination: youtube-dl test video ＂'⧸⧹ä↭𝕐 [BaW_jenozKc].f248.webm
> [download] 100% of  965.31KiB in 00:00:00 at 4.16MiB/s
> [download] Destination: youtube-dl test video ＂'⧸⧹ä↭𝕐 [BaW_jenozKc].f251.webm
> [download] 100% of  138.96KiB in 00:00:00 at 740.93KiB/s
> [Merger] Merging formats into "youtube-dl test video ＂'⧸⧹ä↭𝕐 [BaW_jenozKc].webm"
> Deleting original file youtube-dl test video ＂'⧸⧹ä↭𝕐 [BaW_jenozKc].f251.webm (pass -k to keep)
> Deleting original file youtube-dl test video ＂'⧸⧹ä↭𝕐 [BaW_jenozKc].f248.webm (pass -k to keep)
> $ tail -n1 a.txt  # what is the last entry in my download archive:
> youtube BaW_jenozKc
> $ yt-dlp --ignore-config --download-archive a.txt BaW_jenozKc
> [Youtube] BaW_jenozKc: has already been recorded in the archive
> $ wc -l a.txt  # how many items are in my download archive now:
> 380 a.txt
> ```
Sorry for submitting an unverified issue.
I can't reproduce the issue too, I don't know how the previous records disappeared, may be my mistake. this issue can be closed.
