### ISSUE TITLE
documentation inconsistencies, mainly codec sorting order.

### ISSUE THREAD

**Issue by mirror176** [yt-dlp/yt-dlp#750]
## Checklist

- [x] I'm reporting a bug unrelated to a specific site
- [ ] I've verified that I'm running yt-dlp version **2021.08.10**
    I've got 2021.08.02 installed but the issue can be confirmed on the github repository pages directly.
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] The provided URLs do not contain any DRM to the best of my knowledge
- [ ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [ ] I've read bugs section in FAQ

## Verbose log

Skipping as this is a documentation inconsistency that is visible without executing yt-dlp.

```
PASTE VERBOSE LOG HERE

```

## Description

  https://github.com/yt-dlp/yt-dlp#sorting-formats mentions av01 comes first while https://github.com/yt-dlp/yt-dlp/blob/5a64127f9422170747313004f9a1fd669e0b47f1/Changelog.md 2021.02.04 says vp9 is still the most preferred and 2021.01.07 says av01 is removed from the preferred sorting due to many devices not supporting it. My copy 2021.08.02 didn't download av01 when expected and I thought I tried the newer 2021/08/10 on another machine with the same results which lead me to dig through more documentation. If it is still recommended but disabled for now due to available, it would be good to have the primary readme clarify that with override instructions. Once it changes, documenting the override to disable would likely be worthwhile too.
  The Sorting Formats section of the readme also lists that h264 > h265 > vp9 > vp9.2 > av01... instead of av01 > vp9.2 > vp9 > h265 > h264... when describing how the fields work. It is saying to override h264 to be preferred but does it really resort these others, but not the ones following?
  I presume '-S res,codec:av1' is the fix to restore this now to how the documentation implies is preferred (if hardware supports it). I went down the rabbit hole of options from github.com/TheFrenchGhosty which lead to a very long format command too but wonder what the differences may be. Is there a way to have yt-dlp display the intended sorting rules so users could easily compare the defaults they didn't type vs the overrides they have typed so the user can always know what will be happening?
  Any way to easily have yt-dlp revisit the downloads to see if a new format of the video is available based on newer coding from server or changes in yt-dlp defaults/user overrides? I know there is the --download-archive feature to keep track of which videos were downloaded but it doesn't track what was written (codec/data format, filename written, metadata, subtitles, etc.). A similar issue would relate to sponsorblock encoding but could probably be handled with external spoonskrub passes.
  --help also refers user to Filtering formats and Sorting Formats (yes, different cases) but doesn't mention to see the readme on the web for that information. On FreeBSD there is no manpage and Windows users are directed to get the executable only. I did look further but it may be good to clarify that users have to leave the nearly 1400 line help file and go to another document to find those details.
  New to this fork and noticed the filename changed with instructions to restore; I've not been a fan of spaces in names from command line work but will try the default 'for now' before overriding that it always adds a space and 3 total characters instead of 1 and a safer character to isolate ID. Thanks for the program.

**Comment by pukkandan** [comment]
> yt-dlp/yt-dlp#sorting-formats mentions av01 comes first while 5a64127/Changelog.md 2021.02.04 says vp9 is still the most preferred and 2021.01.07 says av01 is removed from the preferred sorting due to many devices not supporting it. My copy 2021.08.02 didn't download av01 when expected and I thought I tried the newer 2021/08/10 on another machine with the same results which lead me to dig through more documentation.

The documentation is correct, but I do understand how it may be confusing

> `vcodec`: Video Codec (`av01` > `vp9.2` > `vp9` > `h265` > `h264` > `vp8` > `h263` > `theora` > other > unknown)

This states that if you use `vcodec` in `-S`, this is the order used
Later the docs explain:

> the default order used is: `quality,res,fps,codec:vp9.2,size,br,asr,proto,ext,hasaud,source,id`

Note the `codec:vp9.2`. This is the part that prevents av1 from being prefered

I'll see how I can make the documentation clearer

---

> The Sorting Formats section of the readme also lists that h264 > h265 > vp9 > vp9.2 > av01... instead of av01 > vp9.2 > vp9 > h265 > h264... when describing how the fields work. It is saying to override h264 to be preferred but does it really resort these others, but not the ones following?

I dont understand what u mean


> I presume '-S res,codec:av1' is the fix to restore this now to how the documentation implies is preferred (if hardware supports it). 


Yes

> I went down the rabbit hole of options from github.com/TheFrenchGhosty which lead to a very long format command too but wonder what the differences may be.

In general, it is equivalent to `-S res,vcodec:av1`; except that @TheFrenchGhosty has some custom logic for 144p videos

Is there a way to have yt-dlp display the intended sorting rules so users could easily compare the defaults they didn't type vs the overrides they have typed so the user can always know what will be happening?

It is shown in the `--verbose` log

---

> Any way to easily have yt-dlp revisit the downloads to see if a new format of the video is available based on newer coding from server or changes in yt-dlp defaults/user overrides?

There is no direct way to do this. You could record the format in the filename (`-o`) or in the infojson (`--no-clean-infojson`) and use that data to decide

> --help also refers user to Filtering formats and Sorting Formats (yes, different cases) but doesn't mention to see the readme on the web for that information. On FreeBSD there is no manpage and Windows users are directed to get the executable only. I did look further but it may be good to clarify that users have to leave the nearly 1400 line help file and go to another document to find those details.

good idea


> New to this fork and noticed the filename changed with instructions to restore; I've not been a fan of spaces in names from command line work but will try the default 'for now' before overriding that it always adds a space and 3 total characters instead of 1 and a safer character to isolate ID.

I wasn't originally expecting so many people to move to this fork. I had initially changed the naming scheme coz that was what I was personally using. And by the time a ton of users started using the project, I couldn't change it back since some may have already started depending on this new naming scheme. If you prefer the old scheme, you can just put `-o '%(title)s.%(id)s.%(ext)s'` or `--compat-options filename` in a config file and forget about it

---

Next time, please open an issue per topic instead of bundling all your questions in one

**Comment by pukkandan** [comment]
Closed due to inactivity. Can re-open if you have more questions
