### ISSUE TITLE
Is there a way to specify output filenames of multiple videos downloaded from a playlist?

### ISSUE THREAD

**Issue by cangyuyao** [yt-dlp/yt-dlp#7502]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.06.22** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Unrelated to the output template variables. Specifically, when download a tweet containing multiple videos, by default the filenames are title + id at the end. I would like to rename them with `SomeCustomNameA`, `SomeCustomNameB`, etc. (to match with Twitter's medium.media_key). 

Is there a way to rename the videos based on a list of custom filenames, other than specify the media id to download each video one by one?

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
> Is there a way to rename the videos based on a list of custom filenames, other than specify the media id to download each video one by one?

A list of fixed filenames? Not possible without an external script.

> (to match with Twitter's medium.media_key)

Twitter's `media_key` value is almost always the video's `id` prefixed with `7_`
So couldn't you could just do `-o "7_%(id)s.%(ext)s"` ?

**Comment by cangyuyao** [comment]
> > Is there a way to rename the videos based on a list of custom filenames, other than specify the media id to download each video one by one?
> 
> A list of fixed filenames? Not possible without an external script.
> 
> > (to match with Twitter's medium.media_key)
> 
> Twitter's `media_key` value is almost always the video's `id` prefixed with `7_` So couldn't you could just do `-o "7_%(id)s.%(ext)s"` ?

I misunderstood the meaning of id (string): Video identifier. Thanks!
