### ISSUE TITLE
[2FA] Way to fill the field automatically?

### ISSUE THREAD

**Issue by Shohreh** [yt-dlp/yt-dlp#7503]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.06.22** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

Hello,

Now that Twitter limits downloads to registered and authenticated users, I need to edit the script I use for that purpose.

The following works, but it requires that I 1) grab my phone,, 2) run the FreeOTP app to generate a token, and 3) type it into the script:

`youtube-dlp.exe --twofactor 123456 --username me --password blah --abort-on-error -f worst -o test.mp4 https://twitter.com/blah/status/9876543210`

In Windows scripts, is there a way to a get a token from a script?

Thank you.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8 (No VT), error utf-8 (No VT), screen utf-8 (No VT)
[debug] yt-dlp version stable@2023.06.22 [812cdfa06] (win_x86_exe)
[debug] Python 3.7.9 (CPython x86 32bit) - Windows-7-6.1.7601-SP1 (OpenSSL 1.1.1g  21 Apr 2020)
[debug] exe versions: ffmpeg N-109165-g9f5a9a7499-20221122 (setts), ffprobe N-109165-g9f5a9a7499-20221122
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.05.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1851 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.06.22, Current version: stable@2023.06.22
Current Build Hash: 058e24eca675aa0c9d6990c85fe214e52970b8f265a695a80d1142c6c0118627
yt-dlp is up to date (stable@2023.06.22)
```

**Comment by pukkandan** [comment]
With just yt-dlp, there is currently no way. It would be possible to implement an option to pass token and generate TOTP, but idk if it's useful enough. Do you want me to turn this into a feature request?


> In Windows scripts, is there a way to a get a token from a script?

Our issue tracker is not a substitute for google - https://www.google.com/search?q=totp%20windows%20cli

**Comment by bashonly** [comment]
If this is not a feature request, then alternatively you could

 - [pass cookies to yt-dlp](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp) instead of logging in with credentials
 
 - use [this pre-release build of yt-dlp](https://github.com/bashonly/yt-dlp/releases/tag/2023.07.02.222359) with the patch applied from #7476

**Comment by gamer191** [comment]
> It would be possible to implement an option to pass token and generate TOTP

wouldn't logging in with your 2fa token completely defeat the purpose of time-based 2fa? You may as well just disable 2fa and make the token your passwork

**Comment by Shohreh** [comment]
Thanks for the infos.
