### ISSUE TITLE
Missing clarification on standalone filters in README.md

### ISSUE THREAD

**Issue by Pr0xym3** [yt-dlp/yt-dlp#7515]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2023.06.22** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

If you do not provide any format selector(s), but only filter(s), in format selection, for example: `-f [height=720]`, it defaults to `-f best[height=720]`. Here is a reference to the source code where this default behaviour is hardcoded: https://github.com/yt-dlp/yt-dlp/blob/1cffd621cb371f1563563cfb2fe37d137e8a7bee/yt_dlp/YoutubeDL.py#L2162-L2166

But this default behaviour is not documented in the `README.md`. The only thing that is documented about standalone filters is that they select/filter based on the given filters. Here is a reference to the particular line in the `README.md` where it is documented: https://github.com/yt-dlp/yt-dlp/blob/1cffd621cb371f1563563cfb2fe37d137e8a7bee/README.md?plain=1#L1548

And one would assume/infer that all those filtered videos/audios will be downloaded, if only the filters are specified. But in actuality, it downloads only the `best` format among those filtered videos/audios.

I think it will be helpful to clarify this default behaviour in the documentation. It certainly was a big suprise to me when my assumption about the standalone filters, based on the current documentation, was wrong. It took me a while to figure out this default behaviour.

PS Can we also apply this to the [youtube-dl](https://github.com/ytdl-org/youtube-dl) `README.md`.

### Testing:
The youtube video with the id=`j-3nl88O7uI` has multiple 720p video formats available (`video-only` and `video+audio`). And using the format selection `-f [height=720]` only downloads the `best` format (the best quality format that contains both video and audio) with the height of 720p (video with the format code `22`), as shown in the output below.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vU', '-f', '[height=720]', '-o', '%(title)s [%(id)s]-%(format_id)s.%(ext)s', 'https://www.youtube.com/watch?v=j-3nl88O7uI']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.06.22 [812cdfa06] (pip)
[debug] Python 3.11.4 (CPython AMD64 64bit) - Windows-10-10.0.19045-SP0 (OpenSSL 1.1.1u  30 May 2023)
[debug] exe versions: ffmpeg 2023-07-02-git-50f34172e0-full_build-www.gyan.dev (setts), ffprobe 2023-07-02-git-50f34172e0-full_build-www.gyan.dev
[debug] Optional libraries: sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Loaded 1851 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.06.22, Current version: stable@2023.06.22
yt-dlp is up to date (stable@2023.06.22)
[youtube] Extracting URL: https://www.youtube.com/watch?v=j-3nl88O7uI
[youtube] j-3nl88O7uI: Downloading webpage
[youtube] j-3nl88O7uI: Downloading ios player API JSON
[youtube] j-3nl88O7uI: Downloading android player API JSON
[youtube] j-3nl88O7uI: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[info] j-3nl88O7uI: Downloading 1 format(s): 22
[debug] Invoking http downloader on "https://rr5---sn-u5a3u5a3-cimd.googlevideo.com/videoplayback?expire=1688595179&ei=i5alZP2SK5GvxN8PkIKegAQ&ip=***.***.***.***&id=o-AHWkqNn6ZQg7Ey413Id00-Y4EKQGrFnL8ZX2fh-TmKOM&itag=22&source=youtube&requiressl=yes&mh=X2&mm=31%2C29&mn=sn-u5a3u5a3-cimd%2Csn-aigzrnsz&ms=au%2Crdu&mv=m&mvi=5&pl=21&initcwndbps=1687500&spc=Ul2Sq92l9eoiBKCncbYfr249p-EoMUI&vprv=1&svpuc=1&mime=video%2Fmp4&cnr=14&ratebypass=yes&dur=639.315&lmt=1670014548745278&mt=1688573342&fvip=5&fexp=24007246%2C24362685&beids=24350018&c=ANDROID&txp=5311224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Ccnr%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRQIgUoa3luTXiTauePM8y6Wh4HSWeFuHef_6Zhez1XJ3nj0CIQCDmi70QNMH-Z96a8Nxqa5gSrK2T5hOuETS8v209RtE2Q%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAL6yAWsQGhnDUdJBKjLSB8v-3XjXBa3z93zVy6dwUGoEAiEAlfhpsq4cXiMV1Z_OnVF6uzQK4WnP478DjqsGeWlDuCo%3D"
[debug] File locking is not supported. Proceeding without locking
[download] Destination: 4K Stock Footage ｜ No Copyright Videos ｜ Drone Aerial View ｜ Royalty Free [j-3nl88O7uI]-22.mp4
[download] 100% of  134.44MiB in 00:00:32 at 4.15MiB/s
```

**Comment by pukkandan** [comment]
Do you have any specific suggestion for the doc change?

**Comment by Pr0xym3** [comment]
Yes, just add that the standalone filters, such as `-f "[height<=?720][tbr>500]"`, default to `-f "best[height<=?720][tbr>500]"`.

**Comment by pukkandan** [comment]
I was more so asking for opinions on the the specific location and wording 😅

**Comment by Pr0xym3** [comment]
Sry 😅. Well it does not have to be verbose. May be just add a short note in brackets, like (note that, standalone filters, such as `-f "[height<=?720][tbr>500]"`, default to `-f "best[height<=?720][tbr>500]"`).

**Comment by dirkf** [comment]
If saying that, it might be appropriate to explain how to specify such a filter **without** overriding the default format selection, even if that might be clear from the doc as a whole.
