### ISSUE TITLE
ValueError: could not find firefox container "XYZ" in containers.json

### ISSUE THREAD

**Issue by gamer191** [yt-dlp/yt-dlp#7520]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2023.06.22** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Firefox container support seems to be broken in Linux

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['--cookies-from-browser', 'firefox::Gmail at Home', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version nightly@2023.07.06.133255 [90db9a3c0] (linux_exe)
[debug] Python 3.10.12 (CPython x86_64 64bit) - Linux-6.2.12-surface-x86_64-with-glibc2.36 (OpenSSL 3.1.1 30 May 2023, glibc 2.36)
[debug] exe versions: ffmpeg 5.1.1 (setts), ffprobe 5.1.1, rtmpdump 2.4
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.05.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[Cookies] Extracting cookies from firefox
[debug] Extracting cookies from: "/home/jay/.mozilla/firefox/xpzt0btw.default-release/cookies.sqlite"
Traceback (most recent call last):
  File "yt_dlp/__main__.py", line 17, in <module>
  File "yt_dlp/__init__.py", line 1008, in main
  File "yt_dlp/__init__.py", line 962, in _real_main
  File "yt_dlp/YoutubeDL.py", line 674, in __init__
  File "yt_dlp/YoutubeDL.py", line 3876, in print_debug_header
  File "yt_dlp/YoutubeDL.py", line 3920, in _setup_opener
  File "yt_dlp/cookies.py", line 106, in load_cookies
  File "yt_dlp/cookies.py", line 123, in extract_cookies_from_browser
  File "yt_dlp/cookies.py", line 163, in _extract_firefox_cookies
ValueError: could not find firefox container "Gmail at Home" in containers.json
[11419] Failed to execute script '__main__' due to unhandled exception!
```

**Comment by pukkandan** [comment]
Has the container been just created? If so, try closing firefox so we can be sure it write the data to disk.

Can you show contents of `/home/jay/.mozilla/firefox/xpzt0btw.default-release/containers.json`?

**Comment by gamer191** [comment]
> /home/jay/.mozilla/firefox/xpzt0btw.default-release/containers.json

`{"version":4,"lastUserContextId":5,"identities":[{"userContextId":1,"public":true,"icon":"fingerprint","color":"blue","l10nID":"userContextPersonal.label","accessKey":"userContextPersonal.accesskey","telemetryId":1},{"userContextId":2,"public":true,"icon":"briefcase","color":"orange","l10nID":"userContextWork.label","accessKey":"userContextWork.accesskey","telemetryId":2},{"userContextId":3,"public":true,"icon":"dollar","color":"green","l10nID":"userContextBanking.label","accessKey":"userContextBanking.accesskey","telemetryId":3},{"userContextId":4,"public":true,"icon":"cart","color":"pink","l10nID":"userContextShopping.label","accessKey":"userContextShopping.accesskey","telemetryId":4},{"userContextId":5,"public":false,"icon":"","color":"","name":"userContextIdInternal.thumbnail","accessKey":""},{"userContextId":4294967295,"public":false,"icon":"","color":"","name":"userContextIdInternal.webextStorageLocal","accessKey":""}]}`



> Has the container been just created?

I created it ages ago, although I'm starting to wonder if yt-dlp is pointing to the wrong installation :thinking:

**Comment by gamer191** [comment]
It's not, it's `/home/jay/snap/firefox/common/.mozilla/firefox/xpzt0btw.default-release`

So this is a duplicate of https://github.com/yt-dlp/yt-dlp/issues/5175. Although I'd argue that that issue should be reopened since:
1. the Firefox snap is the official way to use Firefox in Ubuntu
2. yt-dlp currently seems to detect leftover files from before Firefox was a snap (hence why I thought that only container support was broken). This could potentially result in people falsely reporting that a site is broken when in reality yt-dlp is just using the wrong cookies file (I actually was about to report that the google drive extractor was broken, but then I realised that it was probably related to this)

**Comment by gamer191** [comment]
Actually, can anyone confirm my 2nd point? It's possible that it's actually my fault and I've forgotten (such as if I installed an unofficial Firefox package at some point)

**Comment by bashonly** [comment]
@gamer191 you are correct on both points
