### ISSUE TITLE
Uploader ID and Uploader URL returns null for infojsons from Auto-generated by YouTube music videos

### ISSUE THREAD

**Issue by NutchapolSal** [yt-dlp/yt-dlp#7521]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.06.22** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [ ] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Provide a description that is worded well enough to be understood

when getting infojson using `-J` for an "Auto-generated by YouTube" music video, the `uploader_id` and `uploader_url` fields returns null. note that the `channel_url` and `channel_id` fields returns the autogenerated topic channel and i think topic channels do not have an @ handle which is now used for `uploader_id` and `uploader_url` fields. also note that some artists have Official Artist Channels which is shown as the uploader on the videos instead of the topic channel when viewing on web or app.

on 2023.03.04 it returns the same values as `channel_id` and `channel_url` fields

some links with the problem:
```
https://www.youtube.com/watch?v=pwxoSC2-irk
https://www.youtube.com/watch?v=Lrqn8-uh-Mo
https://www.youtube.com/watch?v=Yrj9H5WGi7k
https://www.youtube.com/watch?v=fhDo954jzIc
https://www.youtube.com/watch?v=B2FsAJabSSI
https://www.youtube.com/watch?v=4zsVKROnQfY
https://www.youtube.com/watch?v=2Kff0U8w-aU
```
the verbose output is from `https://www.youtube.com/watch?v=Lrqn8-uh-Mo` (siqlo - ρars/ey). `formats`, `thumbnails`, `requested_downloads` and `requested_formats` removed to fit within limit

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['-vUJ', 'https://www.youtube.com/watch?v=Lrqn8-uh-Mo']
[debug] Encodings: locale cp874, fs utf-8, pref cp874, out cp874 (No VT), error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.06.22 [812cdfa06] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.25357-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg 2022-05-23-git-6076dbcb55-essentials_build-www.gyan.dev (setts), ffprobe 2022-05-23-git-6076dbcb55-essentials_build-www.gyan.dev
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.05.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1851 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.06.22, Current version: stable@2023.06.22
Current Build Hash: 37e7ffe204309357cfd1388b0e2c782a30e293ddd0f2761a9a8f6afa185b3566
yt-dlp is up to date (stable@2023.06.22)
[youtube] Extracting URL: https://www.youtube.com/watch?v=Lrqn8-uh-Mo
[youtube] Lrqn8-uh-Mo: Downloading webpage
[youtube] Lrqn8-uh-Mo: Downloading ios player API JSON
[youtube] Lrqn8-uh-Mo: Downloading android player API JSON
[youtube] Lrqn8-uh-Mo: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] Lrqn8-uh-Mo: Downloading 1 format(s): 248+251
{"id":"Lrqn8-uh-Mo","title":"ρars/ey","formats":[],"thumbnails":[],"thumbnail":"https://i.ytimg.com/vi_webp/Lrqn8-uh-Mo/maxresdefault.webp","description":"Provided to YouTube by Repost Network\n\nρars/ey · siqlo\n\nρars/ey\n\n℗ siqlo\n\nReleased on: 2020-03-09\n\nAuto-generated by YouTube.","channel_id":"UCpLxtNBg-FZV-VO6YSrVSlg","channel_url":"https://www.youtube.com/channel/UCpLxtNBg-FZV-VO6YSrVSlg","duration":124,"view_count":27545,"average_rating":null,"age_limit":0,"webpage_url":"https://www.youtube.com/watch?v=Lrqn8-uh-Mo","categories":["Music"],"tags":["siqlo","ρars/ey"],"playable_in_embed":true,"live_status":"not_live","release_timestamp":null,"_format_sort_fields":["quality","res","fps","hdr:12","source","vcodec:vp9.2","channels","acodec","lang","proto"],"automatic_captions":{},"subtitles":{},"album":"ρars/ey","artist":"siqlo","track":"ρars/ey","release_date":null,"release_year":null,"comment_count":5,"chapters":null,"heatmap":null,"like_count":459,"channel":"siqlo","channel_follower_count":2010,"channel_is_verified":true,"uploader":"siqlo","uploader_id":null,"uploader_url":null,"upload_date":"20200308","creator":"siqlo","alt_title":"ρars/ey","availability":"public","original_url":"https://www.youtube.com/watch?v=Lrqn8-uh-Mo","webpage_url_basename":"watch","webpage_url_domain":"youtube.com","extractor":"youtube","extractor_key":"Youtube","playlist":null,"playlist_index":null,"display_id":"Lrqn8-uh-Mo","fulltitle":"ρars/ey","duration_string":"2:04","is_live":false,"was_live":false,"requested_subtitles":null,"_has_drm":null,"epoch":1688651137,"requested_downloads":[],"requested_formats":[],"format":"248 - 1080x1080 (1080p, IOS)+251 - audio only (medium, ANDR)","format_id":"248+251","ext":"webm","protocol":"https+https","language":null,"format_note":"1080p, IOS+medium, ANDR","filesize_approx":2718379,"tbr":175.357,"width":1080,"height":1080,"resolution":"1080x1080","fps":25,"dynamic_range":"SDR","vcodec":"vp09.00.40.08","vbr":45.737,"stretched_ratio":null,"aspect_ratio":1.0,"acodec":"opus","abr":129.62,"asr":48000,"audio_channels":2,"_type":"video","_version":{"version":"2023.06.22","current_git_head":null,"release_git_head":"812cdfa06c33a40e73a8e04b3e6f42c084666a43","repository":"yt-dlp/yt-dlp"}}
```

**Comment by NutchapolSal** [comment]
[parsleyDebug.txt](https://github.com/yt-dlp/yt-dlp/files/11969196/parsleyDebug.txt)
verbose output log with full infojson

**Comment by pukkandan** [comment]
> i think topic channels do not have an @ handle which is now used for `uploader_id` and `uploader_url` fields

Then the fields being None is correct behavior

**Comment by pukkandan** [comment]
Neither the webpage nor the player response contains the @ handle. Not sure this is fixable

cc @coletdjnz

**Comment by dirkf** [comment]
FWIW yt-dl (test with the first problem URL) gives uploader_id == channel_id == UCf2vkRYzZGU6hAOO6bRTlZg; similarly uploader_url == channel_url == http://www.youtube.com/channel/UCf2vkRYzZGU6hAOO6bRTlZg. I'd have been happy to get usefully different uploader_id and uploader_url in these cases but seem to recall that nothing was available in the page.

**Comment by coletdjnz** [comment]
> Neither the webpage nor the player response contains the @ handle. Not sure this is fixable
> 
> cc @coletdjnz

This is expected. Uploader id and uploader url is strictly handle only, and if the channel doesn't have one or Youtube doesn't provide one for the video then it is set to None.

Use channel id/channel url if you always need a url.

We changed this from the old behaviour to make it more predictable.

**Comment by pukkandan** [comment]
@coletdjnz Sometimes handle exists, but isn't available on video webpage

See
https://www.youtube.com/@siqlo_official
https://www.youtube.com/watch?v=Lrqn8-uh-Mo

**Comment by coletdjnz** [comment]
> @coletdjnz Sometimes handle exists, but just isn't available on video webpage
> 
> See https://www.youtube.com/@siqlo_official https://www.youtube.com/watch?v=Lrqn8-uh-Mo

Yeah there isn't really anything we can do about that :/

Also depending on if you hover over the profile pic or channel name you get a different channel id. Topic/official artist channels are a mess on youtube

**Comment by NutchapolSal** [comment]
i kinda expected a wontfix for this, which is fine but i think it would be better to fill in `uploader_id` with `channel_id` as fallback.
