### ISSUE TITLE
Dedicated file for custom extractors

### ISSUE THREAD

**Issue by CHJ85** [yt-dlp/yt-dlp#7522]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.06.22** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Where I add custom extractors to make sure they still work after a yt-dlp upgrade?
At first I know about adding them to the __init_.py file. But even that one could get overwritten by an update in the future. And then I'd have to start adding again. 
Which leads me to my feature request.
You guys should set up a dedicated file for custom that'll be recognized by yt-dlp but won't even see an updat

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
https://github.com/yt-dlp/yt-dlp#plugins

**Comment by CHJ85** [comment]
I'm confused, because I'm referring to website extractors. The built in extractors are placed inside the /yt-dlp/extractor/_extractors.py file.
What I'm saying is, you should set up a dedicated file where we can place custom ones so they don't get overwritten.

**Comment by pukkandan** [comment]
Custom extractors which are not merged to the main project, correct? That's what extractor plugins are.

**Comment by CHJ85** [comment]
Thanks for your help. I figured it out.

**Comment by CHJ85** [comment]
Btw. I gotta say. Once I got the hang of it, this plugin system is streamlined well. Nice job. And thanks again.
