### ISSUE TITLE
How to compress a video while downloading it?

### ISSUE THREAD

**Issue by BarbzYHOOL** [yt-dlp/yt-dlp#7524]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

How can I compress a video while downloading it (to make it smaller size)? thanks

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by megapro17** [comment]
`--downloader ffmpeg --downloader-args ffmpeg:-c:v libx264 -crf 30 -preset medium`

**Comment by BarbzYHOOL** [comment]
> `--downloader ffmpeg --downloader-args ffmpeg:-c:v libx264 -crf 30 -preset medium`

it does not work

https://github.com/mhogomchungu/media-downloader/issues/301#issuecomment-1657249278

**Comment by bashonly** [comment]
add `-c:a aac`:
`--downloader ffmpeg --downloader-args ffmpeg:-c:v libx264 -c:a aac -crf 30 -preset medium`

**Comment by megapro17** [comment]
Why do you want to convert anyway? You're doing something wrong
But to fix that error you need to add another option `%(title)s [%(id)s].mp4`.

**Comment by BarbzYHOOL** [comment]
because when i download the video and then put it into handbrake, i can clearly reduce its size

but to be fair, i think my issues came from a bug from the app I was using, not taking into account any option (so never compressing), i made your command work once, i just dunno how to tweak it

**Comment by MangaD** [comment]
> `--downloader ffmpeg --downloader-args ffmpeg:-c:v libx264 -crf 30 -preset medium`

Needs quotes for the arguments, such as:
`--downloader ffmpeg --downloader-args ffmpeg:"-c:v libx264 -crf 30 -preset medium"`
