### ISSUE TITLE
ERROR: Download failed: 'YoutubeDL' object has no attribute '_allow_colors'

### ISSUE THREAD

**Issue by sudaraka** [yt-dlp/yt-dlp#7528]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

I'm using yt-dlp as a plugin for Gpodder, and since the 2023.06.21 update getting the error mentioned on the title when I try to download a media.

I have tracked down the cause of the error to following line:
[`self.report_warning('Overwriting params from "color" with "no_color"')`](https://github.com/yt-dlp/yt-dlp/blob/92315c03774cfabb3a921884326beb4b981f786b/yt_dlp/YoutubeDL.py#L617)

It appears down the call chain of `report_warning` function it is using `self._allow_colors` before it is initialized.
Note: initialization of `self._allow_colors` happens on the [line 630](https://github.com/yt-dlp/yt-dlp/blob/92315c03774cfabb3a921884326beb4b981f786b/yt_dlp/YoutubeDL.py#L630).

I was able to solved the my issues by changing the `report_warning` to `write_debug`, but didn't want to send a patch for this since I am not sure if that was the correct way to solve this issue.

P.S.
I acknowledge to have checked some options on the issue template to get it to go through, but the results provided is not exactly by following the steps mentioned.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
1688712184.665647 [gpodder.download] ERROR: Download failed: 'YoutubeDL' object has no attribute '_allow_colors'
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/gpodder/download.py", line 910, in run
    headers, real_url = downloader.retrieve_resume(self.tempname, self.status_updated)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/gpodder/extensions/youtube-dl.py", line 116, in retrieve_resume
    res = self._ytdl.fetch_video(info, opts)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/gpodder/extensions/youtube-dl.py", line 355, in fetch_video
    with youtube_dl.YoutubeDL(opts) as ydl:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 618, in __init__
    self.report_warning('Overwriting params from "color" with "no_color"')
  File "/usr/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1027, in report_warning
    self.to_stderr(f'{self._format_err("WARNING:", self.Styles.WARNING)} {message}', only_once)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1015, in _format_err
    return self._format_text(self._out_files.error, self._allow_colors.error, *args, **kwargs)
                                                    ^^^^^^^^^^^^^^^^^^
AttributeError: 'YoutubeDL' object has no attribute '_allow_colors'
```

**Comment by pukkandan** [comment]
I'll fix this, but why are you passing both `color` and `no_color` anyway?

**Comment by sudaraka** [comment]
Thanks for looking into this.

> I'll fix this, but why are you passing both `color` and `no_color` anyway?

This happens when I use yt-dlp as extension for Gpodder, not sure what's reason behind it sending the color parameters.
