### ISSUE TITLE
[Question] Avoiding "latency" when starting yt-dlp?

### ISSUE THREAD

**Issue by triplesixman** [yt-dlp/yt-dlp#753]
## Checklist

- [*] I'm asking a question
- [*] I've looked through the README and FAQ for similar questions
- [*] I've searched the bugtracker for similar questions including closed ones

## Question

Hello, I notice that when launching yt-dlp on Debian 9 it takes 2-4 seconds before the program starts (between the moment I execute the command and the moment the first line with "[youtube]..." appears). I compared with youtube-dl and there is no such latency. Do we have a way to make it launch that fast?

**Comment by Ashish0804** [comment]
do a `time` on both and paste the result

**Comment by triplesixman** [comment]
> do a `time` on both and paste the result

```
root@server:~/test# time youtube-dl https://www.youtube.com/watch?v=6Dh-RL__uN4
WARNING: Assuming --restrict-filenames since file system encoding cannot encode all characters. Set the LC_ALL environment variable to fix this.
[youtube] 6Dh-RL__uN4: Downloading webpage
WARNING: Requested formats are incompatible for merge and will be merged into mkv.
[download] Destination: bitch_lasagna-6Dh-RL__uN4.f137.mp4
[download] 100% of 45.16MiB in 00:01
[download] Destination: bitch_lasagna-6Dh-RL__uN4.f251.webm
[download] 100% of 2.16MiB in 00:00
[ffmpeg] Merging formats into "bitch_lasagna-6Dh-RL__uN4.mkv"
Deleting original file bitch_lasagna-6Dh-RL__uN4.f137.mp4 (pass -k to keep)
Deleting original file bitch_lasagna-6Dh-RL__uN4.f251.webm (pass -k to keep)

real    0m3.717s
user    0m0.992s
sys     0m0.180s
```


```
root@server:~/test# time yt-dlp https://www.youtube.com/watch?v=6Dh-RL__uN4
[youtube] 6Dh-RL__uN4: Downloading webpage
[youtube] 6Dh-RL__uN4: Downloading android player API JSON
[info] 6Dh-RL__uN4: Downloading 1 format(s): 248+251
[download] Destination: bitch lasagna [6Dh-RL__uN4].f248.webm
[download] 100% of 33.29MiB in 00:01
[download] Destination: bitch lasagna [6Dh-RL__uN4].f251.webm
[download] 100% of 2.16MiB in 00:00
[Merger] Merging formats into "bitch lasagna [6Dh-RL__uN4].webm"
Deleting original file bitch lasagna [6Dh-RL__uN4].f251.webm (pass -k to keep)
Deleting original file bitch lasagna [6Dh-RL__uN4].f248.webm (pass -k to keep)

real    0m5.285s
user    0m3.032s
sys     0m0.140s

```

**Comment by pukkandan** [comment]
Are you sure the issue is with "starting yt-dlp" and not the same as #725?
Try running just `yt-dlp` without any URL and compare with `youtube-dl` to see if there is actually a delay at startup

**Comment by Ashish0804** [comment]
@triplesixman do `time` on `youtube-dl -v` and `yt-dlp -v`
2 sec can be explained by py2 vs py3

**Comment by triplesixman** [comment]
> Are you sure the issue is with "starting yt-dlp" and not the same as #725?
> Try running just `yt-dlp` without any URL and compare with `youtube-dl` to see if there is actually a delay at startup

I just did the test, the slowness is reproduced even without URL:

```
root@server:~# time youtube-dl
WARNING: Assuming --restrict-filenames since file system encoding cannot encode all characters. Set the LC_ALL environment variable to fix this.
Usage: youtube-dl [OPTIONS] URL [URL...]

youtube-dl: error: You must provide at least one URL.
Type youtube-dl --help to see a list of all options.

real    0m0.176s
user    0m0.156s
sys     0m0.016s
```

```
root@server:~# time yt-dlp
Usage: yt-dlp [OPTIONS] URL [URL...]

yt-dlp: error: You must provide at least one URL.
Type yt-dlp --help to see a list of all options.

real    0m2.113s
user    0m2.036s
sys     0m0.052s
```

I don't know if this has anything to do with it, but isn't it related to the size of the file being run? The file /usr/local/bin/youtube-dl is 212 bytes, and /usr/local/bin/yt-dlp is 2.1 MB. It's a pretty powerful server so I don't know if it has a link or not.

**Comment by triplesixman** [comment]
> @triplesixman do `time` on `youtube-dl -v` and `yt-dlp -v`
> 2 sec can be explained by py2 vs py3

Does that mean that python version 3.9.6 (used by yt-dlp on my server) is slower than version 2.7.13 for youtube-dl according to you? Is there any way to avoid this latency?

```
root@server:~# time youtube-dl -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v']
WARNING: Assuming --restrict-filenames since file system encoding cannot encode all characters. Set the LC_ALL environment variable to fix this.
[debug] Encodings: locale ANSI_X3.4-1968, fs ANSI_X3.4-1968, out ANSI_X3.4-1968, pref ANSI_X3.4-1968
[debug] youtube-dl version 2021.06.06
[debug] Python version 2.7.13 (CPython) - Linux-4.9.0-16-amd64-x86_64-with-debian-9.13
[debug] exe versions: ffmpeg 4.1.2, ffprobe 4.1.2, phantomjs 2.1.1
[debug] Proxy map: {}
Usage: youtube-dl [OPTIONS] URL [URL...]

youtube-dl: error: You must provide at least one URL.
Type youtube-dl --help to see a list of all options.

real    0m0.286s
user    0m0.216s
sys     0m0.052s
```


```
root@server:~# time yt-dlp -v
[debug] Command-line config: ['-v']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] yt-dlp version 2021.08.02 (zip)
[debug] Python version 3.9.6 (CPython 64bit) - Linux-4.9.0-16-amd64-x86_64-with-glibc2.24
[debug] exe versions: ffmpeg 4.1.2, ffprobe 4.1.2, phantomjs 2.1.1
[debug] Proxy map: {}
Usage: yt-dlp [OPTIONS] URL [URL...]

yt-dlp: error: You must provide at least one URL.
Type yt-dlp --help to see a list of all options.

real    0m1.816s
user    0m1.736s
sys     0m0.048s
```

**Comment by Ashish0804** [comment]
yeah imo it's bcoz of py3.
You can either fork yt-dlp, rewrite py3 code to work with py2.
Or simply live with 2sec delay(it's negligible practically)

**Comment by 89z** [comment]
> yeah imo it's bcoz of py3.
> You can either fork yt-dlp, rewrite py3 code to work with py2.
> Or simply live with 2sec delay(it's negligible practically)

With all due respect to @Ashish0804, I dont think this is an acceptable answer, when other options are available:

~~~
PS C:\> Measure-Command { youtube }
Milliseconds      : 10

PS C:\> Measure-Command { youtube -v -1 6Dh-RL__uN4 }
Milliseconds      : 531
~~~

https://github.com/89z/mech

**Comment by triplesixman** [comment]
> > yeah imo it's bcoz of py3.
> > You can either fork yt-dlp, rewrite py3 code to work with py2.
> > Or simply live with 2sec delay(it's negligible practically)
> 
> With all due respect to @Ashish0804, I dont think this is an acceptable answer, when other options are available:
> 
> ```
> PS C:\> Measure-Command { youtube }
> Milliseconds      : 10
> 
> PS C:\> Measure-Command { youtube -v -1 6Dh-RL__uN4 }
> Milliseconds      : 531
> ```
> 
> https://github.com/89z/mech

Do you think it's not related to the version of python? Do you have any idea where the slowness comes from?

**Comment by 89z** [comment]
> Do you think it's not related to the version of python? Do you have any idea where the slowness comes from?

Python isnt a compiled language, so every single time you start a Python program, you have to load the interpreter, which comes with a latency cost. Obviously with Python 3 that is significantly higher than with Python 2, but it seems the Python developers thought that was an acceptable tradeoff.

It could be that Python 3 has some setting, or maybe a different way to write the code, to minimize this difference. I dont know. My preference to deal with the problem, is to just not use an interpreted language. Regardless of what you choose to do, you will have cost/benefit tradeoffs.

**Comment by pukkandan** [comment]
After some searching, it seems the lower performance of py3 as opposed to py2 is a well known issue. But I agree with @Ashish0804 that it is a negligible difference. If you want, you could try building yt-dlp with lazy extractors enabled, which would give some speed increase. Keep in mind that this is an experimental feature though

**Comment by 89z** [comment]
> After some searching, it seems the lower performance of py3 as opposed to py2 is a well known issue. But I agree with @Ashish0804 that it is a negligible difference.

Just because its a well known issue, doesnt mean its acceptable. Quoting OPs last test with YouTube-DL:

> real    0m0.286s

and with YT-DLP:

> real    0m1.816s

thats 6 times longer. Thats not negligible. I can understand the motivation to make comments like that, as youve likely put many hours into the current YT-DLP implementation, and helped many people along the way, and I respect that. But you have to be careful to not fall into the trap of rationalization. You have to recognize when something is "a little worse" versus "a lot worse". And in this case, its a lot worse.

Now, is it a hard problem to fix? Yes of course. It the root cause even anything to do with YT-DLP? Not really, fixing it is more working around the shortcomings of Python 3 itself. But simply stating that the difference is "negligible", is rationalizing at best, and just lying at worst. I mean this in a respectful tone, but I think its important to recognize problems when they exist.

**Comment by triplesixman** [comment]
Agree with 89z. Anyway, thank you all for your messages. I'll go with it in the meantime (because I'd rather have 2-3 seconds on each launch than have to totally restart youtube-dl because of the random 70kb/s youtube limit). I hope there will be a solution in the future for those few seconds of latency.

**Comment by blackjack4494** [comment]
```bash
root@htznr-nbg1:~# time yt-dlp -v
[debug] Command-line config: ['-v']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] yt-dlp version 2021.08.10
[debug] Python version 3.8.10 (CPython 64bit) - Linux-5.4.0-47-generic-x86_64-with-glibc2.29
[debug] exe versions: none
[debug] Optional libraries: mutagen, pycryptodome, sqlite, websockets
[debug] Proxy map: {}
Usage: yt-dlp [OPTIONS] URL [URL...]

yt-dlp: error: You must provide at least one URL.
Type yt-dlp --help to see a list of all options.

real    0m0.552s
user    0m0.462s
sys     0m0.085s

root@htznr-nbg1:~# time yt-dlp -v
[debug] Command-line config: ['-v']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] yt-dlp version 2021.08.10
[debug] Python version 3.8.10 (CPython 64bit) - Linux-5.4.0-47-generic-x86_64-with-glibc2.29
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4
[debug] Optional libraries: mutagen, pycryptodome, sqlite, websockets
[debug] Proxy map: {}
Usage: yt-dlp [OPTIONS] URL [URL...]

yt-dlp: error: You must provide at least one URL.
Type yt-dlp --help to see a list of all options.

real    0m0.641s
user    0m0.515s
sys     0m0.119s
```

```ps
PS C:\Users\theidel> Measure-Command {yt-dlp -v}
[debug] Command-line config: ['-v']
[debug] Encodings: locale cp1252, fs utf-8, out cp1252, pref cp1252
[debug] yt-dlp version 2021.08.10
[debug] Python version 3.7.1 (CPython 32bit) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg 4.4-full_build-www.gyan.dev, ffprobe 4.4-full_build-www.gyan.dev
[debug] Optional libraries: mutagen, pycryptodome, sqlite, websockets
[debug] Proxy map: {}
Usage: yt-dlp [OPTIONS] URL [URL...]

yt-dlp: error: You must provide at least one URL.
Type yt-dlp --help to see a list of all options.

Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 1
Milliseconds      : 293
Ticks             : 12936355
TotalDays         : 1,49726331018519E-05
TotalHours        : 0,000359343194444444
TotalMinutes      : 0,0215605916666667
TotalSeconds      : 1,2936355
TotalMilliseconds : 1293,6355

PS C:\Users\theidel> Measure-Command {youtube-dlc -v}
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v']
[debug] Encodings: locale cp1252, fs utf-8, out cp1252, pref cp1252
[debug] youtube-dlc version 2020.11.11-3
[debug] Python version 3.7.1 (CPython) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg 4.4-full_build-www.gyan.dev, ffprobe 4.4-full_build-www.gyan.dev
[debug] Proxy map: {}
Usage: youtube-dlc [OPTIONS] URL [URL...]

youtube-dlc: error: You must provide at least one URL.
Type youtube-dlc --help to see a list of all options.

Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 1
Milliseconds      : 142
Ticks             : 11420873
TotalDays         : 1,32186030092593E-05
TotalHours        : 0,000317246472222222
TotalMinutes      : 0,0190347883333333
TotalSeconds      : 1,1420873
TotalMilliseconds : 1142,0873

PS C:\Users\theidel> Measure-Command {youtube-dl -v}
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v']
[debug] Encodings: locale cp1252, fs utf-8, out cp1252, pref cp1252
[debug] youtube-dl version 2020.11.12
[debug] Python version 3.7.1 (CPython) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg 4.4-full_build-www.gyan.dev, ffprobe 4.4-full_build-www.gyan.dev
[debug] Proxy map: {}
Usage: youtube-dl [OPTIONS] URL [URL...]

youtube-dl: error: You must provide at least one URL.
Type youtube-dl --help to see a list of all options.

Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 1
Milliseconds      : 144
Ticks             : 11442319
TotalDays         : 1,32434247685185E-05
TotalHours        : 0,000317842194444444
TotalMinutes      : 0,0190705316666667
TotalSeconds      : 1,1442319
TotalMilliseconds : 1144,2319
```
Do note that I have several python versions on my machine (laptop right now) and that installed versions are running under 32Bit Version of Python but that shouldn't have much of an impact. 
On a test server I only installed yt-dlp to see performance. First run is without ffmpeg installed and second one with.
```bash
root@htznr-nbg1:~# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.3 LTS
Release:        20.04
Codename:       focal
```

You _may_ can tweak startup by removing not used extractors which I haven't tried but can think of maybe working.
