### ISSUE TITLE
[ytdl_hook] ERROR: [youtube] sOhlszo8qLw: Unable to extract uploader id

### ISSUE THREAD

**Issue by fsociety343** [yt-dlp/yt-dlp#7535]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

Please help, I have done the correct installation according to the provisions, but there is still an error when I execute the title search, I am using Ubuntu 22.04 and I have installed all additional installations too, thank you

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
Scraping YouTube (with https://invidious.protokolla.fi) (bondan, pg: 1)
/usr/local/bin/ytfzf: 504: [: Illegal number: no
/usr/local/bin/ytfzf: 1202: [: Illegal number: yes
[ytdl_hook] ERROR: [youtube] sOhlszo8qLw: Unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U 
[ytdl_hook] youtube-dl failed: unexpected error occurred 
Failed to recognize file format.

Exiting... (Errors when loading file)
```

**Comment by bashonly** [comment]
It looks like you're using... [ytfzf](https://github.com/pystardust/ytfzf) on top of `mpv` on top of `yt-dlp`?

Anyways, it's because your yt-dlp is outdated, possibly because the yt-dlp package in your distro's repo is outdated. You need to update it.

https://github.com/yt-dlp/yt-dlp/wiki/FAQ#the-yt-dlp-in-my-package-manager-is-outdatedbroken

https://github.com/yt-dlp/yt-dlp/wiki/Installation
