### ISSUE TITLE
[Site Request] Please provide a bottle/formula for homebrew (macOS)

### ISSUE THREAD

**Issue by thekryz** [yt-dlp/yt-dlp#754]
- [X] I'm reporting a site feature request
- [X] I've verified that I'm running yt-dlp version **2021.08.10**
- [X] I've searched the bugtracker for similar site feature requests including closed ones

## Description

As a macOS-user, I would love to see yt-dlp being provided as a [homebrew bottle](https://docs.brew.sh/Bottles) / Formula. This would make updating my apps more convenient. [youtube-dl](https://formulae.brew.sh/formula/youtube-dl#default) and [youtube-dlc](https://formulae.brew.sh/formula/youtube-dlc#default) (and even [haruhi-dl](https://formulae.brew.sh/formula/haruhi-dl#default)!) hava a bottle, but are outdated with speed issues at the moment and I'm pretty sure yt-dlp would gain some more users if a homebrew bottle would be provided.

**Comment by Ashish0804** [comment]
Isn't this a homebrew side problem?(similar to scoop and choco)

**Comment by thekryz** [comment]
To be honest, I don't know.

**Comment by pukkandan** [comment]
> Bottles are created using the Brew Test Bot, usually when people submit pull requests to Homebrew

I don't have a mac - making it not possible for me to make a bottle and test it. Even if I did, I will need to manually keep updating it. Similar to #330 and #368, I am not interested in maintaining packages that I need to keep manually updating. Any third party is free to make a bottle and put in the effort to keep it up to date

**Comment by meeDamian** [comment]
FWIW once formula is created, it's often updated by PRs from community

**Comment by unbeatable-101** [comment]
I'll try making a formula

**Comment by chenrui333** [comment]
FYI, I have just merged the formula, it can be installed as `brew install yt-dlp` now. 🎉

**Comment by pukkandan** [comment]
@chenrui333 Will it be auto-updated? @nao20010128nao had also just made a PR #827 to maintain our own taps. I am wondering if it is needed now

**Comment by chenrui333** [comment]
it can be automated pretty easily with something like [this](https://github.com/mislav/bump-homebrew-formula-action)

**Comment by iFloris** [comment]
Thank you! https://formulae.brew.sh/formula/yt-dlp#default
