### ISSUE TITLE
WARNING: Cannot update utime of file

### ISSUE THREAD

**Issue by cruix89** [yt-dlp/yt-dlp#7542]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

hello, my downloads retry a warning:

[Merger] Merging formats into "/downloads/TV Mundo Maior - Seu canal espírita #/[2017-11-21] - [Saúde no Terceiro Milênio ｜ RBN (21⧸11⧸2017)]/y-hy2_aogKA.mp4"
WARNING: Cannot update utime of file
Deleting original file /downloads/TV Mundo Maior - Seu canal espírita #/[2017-11-21] - [Saúde no Terceiro Milênio ｜ RBN (21⧸11⧸2017)]/y-hy2_aogKA.f247.webm (pass -k to keep)
Deleting original file /downloads/TV Mundo Maior - Seu canal espírita #/[2017-11-21] - [Saúde no Terceiro Milênio ｜ RBN (21⧸11⧸2017)]/y-hy2_aogKA.f251.webm (pass -k to keep)
[EmbedSubtitle] There aren't any subtitles to embed
[Metadata] Adding metadata to "/downloads/TV Mundo Maior - Seu canal espírita #/[2017-11-21] - [Saúde no Terceiro Milênio ｜ RBN (21⧸11⧸2017)]/y-hy2_aogKA.mp4"
WARNING: Cannot update utime of file
[ThumbnailsConvertor] Converting thumbnail "/downloads/TV Mundo Maior - Seu canal espírita #/[2017-11-21] - [Saúde no Terceiro Milênio ｜ RBN (21⧸11⧸2017)]/y-hy2_aogKA.webp" to png
WARNING: Cannot update utime of file
[EmbedThumbnail] mutagen: Adding thumbnail to "/downloads/TV Mundo Maior - Seu canal espírita #/[2017-11-21] - [Saúde no Terceiro Milênio ｜ RBN (21⧸11⧸2017)]/y-hy2_aogKA.mp4"
WARNING: Cannot update utime of file

How i can solve this warning?

Thank you.

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by bashonly** [comment]
please add a full verbose log

>>>  Run your yt-dlp command with `-vU` flag added (`yt-dlp -vU <your command line>`)
If using API, add `'verbose': True` to YoutubeDL params instead
Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

**Comment by pukkandan** [comment]
> Make sure you are **only** asking a question and not reporting a bug or requesting a feature.
> If your question contains "isn't working" or "can you add", this is most likely the wrong template.
> If you are in doubt whether this is the right template, **USE ANOTHER TEMPLATE**!

Do not abuse the "Question" template to post incomplete issues/feature requests. At bae minimum, post a verbose log! Repeated abuse will be treated as spam
