### ISSUE TITLE
FEATURE REQUEST: Allow --output <dir>

### ISSUE THREAD

**Issue by arbitrary-dev** [yt-dlp/yt-dlp#7548]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm requesting a feature unrelated to a specific site
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Provide a description that is worded well enough to be understood

I would like to do this:

```
yt-dlp -o ~/Videos/ https://www.youtube.com/watch?v=QaeRj-ApktY
```

### Provide verbose output that clearly demonstrates the problem

- [ ] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [ ] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [ ] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

But what I get is this:

```shell
[youtube] Extracting URL: https://www.youtube.com/watch?v=QaeRj-ApktY
[youtube] QaeRj-ApktY: Downloading webpage
[youtube] QaeRj-ApktY: Downloading ios player API JSON
[youtube] QaeRj-ApktY: Downloading android player API JSON
[youtube] QaeRj-ApktY: Downloading m3u8 information
[info] QaeRj-ApktY: Downloading 1 format(s): 134+139
[download] Destination: /home/user/Videos/.mp4.f134.mp4
[download] 100% of   96.46MiB in 00:01:15 at 1.28MiB/s
[download] Destination: /home/user/Videos/.mp4.f139.m4a
[download] 100% of   31.09MiB in 00:00:21 at 1.46MiB/s
[Merger] Merging formats into "/home/dolf/Videos/_unsorted/.mp4"
ERROR: Postprocessing: file:/home/user/Videos/.mp4.temp: Invalid argument
```

**Comment by bashonly** [comment]
the functionality you want already exists as the `-P`/`--paths` option

**Comment by arbitrary-dev** [comment]
That's counter intuitive, to be honest.

**Comment by arbitrary-dev** [comment]
As a user I expect `--output` to specify where to download files in (as all the other programs do). But the current option should be rather named as `--template`.

**Comment by arbitrary-dev** [comment]
Or at least would be nice to have a reference to `--paths` in manual for `--output`, so that people like me, who get used to other namings, are not lost.

**Comment by arbitrary-dev** [comment]
But my proposal will be to just merge `--paths` & `--output`, and just leave the later.

**Comment by bashonly** [comment]
> would be nice to have a reference to `--paths` in manual for `--output`

Not a bad idea IMO

> But my proposal will be to just merge `--paths` & `--output`, and just leave the later.

You can specify path in `--output`, you just also have to specify output template/filename

**Comment by coletdjnz** [comment]
> Or at least would be nice to have a reference to `--paths` in manual for `--output`, so that people like me, who get used to other namings, are not lost.

Already there. From [OUTPUT TEMPLATE](https://github.com/yt-dlp/yt-dlp#output-template):

> The -o option is used to indicate a template for the output file names while -P option is used to specify the path each type of file should be saved to.

**Comment by pukkandan** [comment]
> But my proposal will be to just merge `--paths` & `--output`, and just leave the later.

That is ambiguous. If you do `C:\xxx`, do you want a file named `xxx` in `C:\`, or a file inside `C:\xxx`? The options will be kept separate

**Comment by arbitrary-dev** [comment]
>That is ambiguous. If you do `C:\xxx`, do you want a file named `xxx` in `C:\`, or a file inside `C:\xxx`?

No, it's not ambiguous. If the directory `C:\xxx` exists we create a file with a default template `C:\xxx\%(title)s.%(ext)s`. On the other hand, if `C:\xxx` doesn't exist or a file, we create it, possibly asking for a permission to overwrite.

**Comment by arbitrary-dev** [comment]
>The options will be kept separate

Then I'd propose to rename them to be inline with other software out there:

`--output` → `--template`
`--paths` → `--output`

**Comment by Grub4K** [comment]
They cannot be renamed due to compatibility. `--output` could at most get an alias with `--template`, but I even doubt that
