### ISSUE TITLE
Need help with a format selection not shown in Examples doc

### ISSUE THREAD

**Issue by BlohoJo** [yt-dlp/yt-dlp#7561]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm asking a question and **not** reporting a bug or requesting a feature
- [X] I've looked through the [README](https://github.com/yt-dlp/yt-dlp#readme)
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar questions **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)

### Please make sure the question is worded well enough to be understood

I need help with a format selection, as it is not listed in format examples, and I am not knowledgeable enough to be able to figure it out on my own.

I need help with the following from the [format examples](https://github.com/yt-dlp/yt-dlp#format-selection-examples):
```
# Download the best video with either h264 or h265 codec,
# or the best video if there is no such video
$ yt-dlp -f "(bv*[vcodec~='^((he|a)vc|h26[45])']+ba) / (bv*+ba/b)"
```
The above example works very well for the video codec if I want it to select the best h264:
```
$ yt-dlp -f "(bv*[vcodec~='^((he|a)vc|h264])']+ba) / (bv*+ba/b)"
```
However, I also want it to work for the audio codec. I want the best m4a codec, which I believe for yt-dlp is called mp4a. So, I want to replace the `+ba)` part in the line above with a specification for the best available mp4a codec instead of `ba`. However, everything I've tried so far either downloads the wrong codec or gives a syntax error. I just don't know how to write the expression. I've spent a lot of time searching, maybe the answer is out there but unfortunately I'm unable to find it.

(The reason I need to do this is because the latest version of yt-dlp has additional formats on YouTube that makes the old way of doing it - `-f "bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best"` - no longer work properly, as it can end up downloading vp9 or opus instead of h264 and m4a now by doing it that way.)

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
One of the different attempts I tried; this downloads the wrong codec (251 - opus) instead of mp4a (140 - m4a):

E:\USER\temp_ytdl>yt-dlp.exe -vU -f "(bv*[vcodec~='^((he|a)vc|h264])']+ba*[acode
c~='^(mp4a])']) / (bv*+ba/b)" "https://www.youtube.com/watch?v=PxkNilHB9hc"
[debug] Command-line config: ['-vU', '-f', "(bv*[vcodec~='^((he|a)vc|h264])']+ba
*[acodec~='^(mp4a])']) / (bv*+ba/b)", 'https://www.youtube.com/watch?v=PxkNilHB9
hc']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8 (No VT), erro
r utf-8 (No VT), screen utf-8 (No VT)
[debug] yt-dlp version stable@2023.07.06 [b532a3481] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-2008ServerR2-6.1.7601-SP1
(OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-93824-g479a5f644f (fdk), ffprobe N-89595-g40d4b13
228, rtmpdump 2.4-20151223-gfa8646d-OpenSSL_1.0.2n-x86_64-static
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.05.07,
 mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releas
es/latest
Available version: stable@2023.07.06, Current version: stable@2023.07.06
Current Build Hash: 5ff3e702171a50175c34397494e2d18ce35d771c2110b1e59bd173ec2fb3
52aa
yt-dlp is up to date (stable@2023.07.06)
[youtube] Extracting URL: https://www.youtube.com/watch?v=PxkNilHB9hc
[youtube] PxkNilHB9hc: Downloading webpage
[youtube] PxkNilHB9hc: Downloading ios player API JSON
[youtube] PxkNilHB9hc: Downloading android player API JSON
[debug] Loading youtube-nsig.1dda5629 from cache
[debug] [youtube] Decrypted nsig WqDgfcRArXYWxIXY => RZIoIiBuiyc1GA
[youtube] PxkNilHB9hc: Downloading m3u8 information
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec
:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source
, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, ha
saud, id
[info] PxkNilHB9hc: Downloading 1 format(s): 315+251
[debug] Invoking http downloader on "https://rr3---sn-n4v7sns7.googlevideo.com/v
ideoplayback?expire=1688967531&ei=C0WrZJGlLau3sfIPvumByAM&ip=2001%3A470%3A1f04%3
A333%3A%3A2&id=o-AB01euYx8Pu0CTrx4-77HNiHPD3CNAYlc22i59u-8K0C&itag=315&source=yo
utube&requiressl=yes&mh=MP&mm=31%2C29&mn=sn-n4v7sns7%2Csn-o097znze&ms=au%2Crdu&m
v=u&mvi=3&pl=57&vprv=1&svpuc=1&mime=video%2Fwebm&gir=yes&clen=3033494746&dur=113
6.885&lmt=1688426372598160&mt=1688945517&fvip=1&keepalive=yes&fexp=24007246%2C24
362686&beids=24350018&c=IOS&txp=4432434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Cs
ource%2Crequiressl%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQ
IgA594p9pwl9czwOLUGYITHKQ9YzQ-W9fNRZaBJFOShIYCIQCF-TlJClWizsoNT0Zu7K5nJScnXD8sBC
az7mjVAYcI0w%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl&lsig=AG3C_xAwRgIhA
Puw35QnE7YkBz9xHX_TVJcXCjd3NZmAVwTAOq4-tLg1AiEA2RuaR6h31V2NWwH4fm8KMUzWpQY4KggnD
wjbjFMaaR8%3D"
[debug] File locking is not supported. Proceeding without locking
[download] Destination: Japan's 1980s 3D Videodisc system - 3D VHD [PxkNilHB9hc]
.f315.webm
[download] 100% of    2.83GiB in 00:01:17 at 37.24MiB/s
[debug] Invoking http downloader on "https://rr3---sn-n4v7sns7.googlevideo.com/v
ideoplayback?expire=1688967532&ei=DEWrZOIUhIqx8g-ihKOYBw&ip=2001%3A470%3A1f04%3A
333%3A%3A2&id=o-AJRF-WzUH2seYMoShxQmCD6P9QPccY-Y0VoIHG92ymcw&itag=251&source=you
tube&requiressl=yes&mh=MP&mm=31%2C29&mn=sn-n4v7sns7%2Csn-o097znze&ms=au%2Crdu&mv
=u&mvi=3&pl=57&spc=Ul2Sq_H5h8-yPezzT6yiGqkSqY37xdo&vprv=1&svpuc=1&mime=audio%2Fw
ebm&gir=yes&clen=15368187&dur=1136.921&lmt=1688421567150927&mt=1688945517&fvip=1
&keepalive=yes&fexp=24007246&c=ANDROID&txp=4432434&sparams=expire%2Cei%2Cip%2Cid
%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Cl
mt&sig=AOq0QJ8wRQIhAJPsc1PCxBkgZohXD9vna6QAYlrWNSaXU5kb-dq4qQGaAiBalbJCzq0or5z4l
3dNfgj5dr9c37oK0lG_ulbAmb3QGg%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl&l
sig=AG3C_xAwRQIhAM4Y6CDvtsXN0RQdP7o_Rm-7pbNf6By7699MKCCrF5RKAiAQOWsPlDiPpTjvdLh0
KC_KthbJ1jbkhpNC2TzHRexw6g%3D%3D"
[download] Destination: Japan's 1980s 3D Videodisc system - 3D VHD [PxkNilHB9hc]
.f251.webm
[download] 100% of   14.66MiB in 00:00:00 at 33.25MiB/s
[Merger] Merging formats into "Japan's 1980s 3D Videodisc system - 3D VHD [PxkNi
lHB9hc].webm"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:Japan's
1980s 3D Videodisc system - 3D VHD [PxkNilHB9hc].f315.webm" -i "file:Japan's 198
0s 3D Videodisc system - 3D VHD [PxkNilHB9hc].f251.webm" -c copy -map "0:v:0" -m
ap "1:a:0" -movflags "+faststart" "file:Japan's 1980s 3D Videodisc system - 3D V
HD [PxkNilHB9hc].temp.webm"
Deleting original file Japan's 1980s 3D Videodisc system - 3D VHD [PxkNilHB9hc].
f315.webm (pass -k to keep)
Deleting original file Japan's 1980s 3D Videodisc system - 3D VHD [PxkNilHB9hc].
f251.webm (pass -k to keep)
```

**Comment by bashonly** [comment]
> `-f "(bv*[vcodec~='^((he|a)vc|h26[45])']+ba) / (bv*+ba/b)"`

Not applicable to youtube, but this ^ will also select h265/hevc if available

> `-f "(bv*[vcodec~='^((he|a)vc|h264])']+ba) / (bv*+ba/b)"`

And in this ^ one, you've left an extra `]` bracket in the pattern after `h264`, which is probably why your attempts at recreating the pattern for audio codec are failing.

&nbsp;
IMO it's much simpler to just use format sorting instead of format selection; ditch the `-f` arg altogether and use this:
`-S "vcodec:h264,res,acodec:mp4a"`

&nbsp;
But if you prefer to select with `-f`, here's what you could use:
`-f "(bv*[vcodec~='^(avc|h264)']+ba[acodec~='^(mp?4a|aac)']) / (bv*+ba/b)"`

**Comment by BlohoJo** [comment]
Sorry for the late reply, life got in the way.

Thanks very much for your help.

With the new formats, I've found that the m3u8 format 270 is slightly better than 137, but I can't figure out a way to select it with `-f`. I can do it with -S using `-S "vcodec:h264,res,br,acodec:mp4a"`.

But, there's also a slightly better m4a audio available as format 234, which shows as an `unknown` m3u8 stream. (`234 mp4   audio only        |                  m3u8  | audio only          unknown             [en] Default`)

I've been working on it for a couple of hours but I can't figure out how to get either `-S` or `-f` to give me format 270 by selecting it (either through `-S "vcodec:h264,res,br"` or `-f "(bv*[vcodec~='^(avc|h264)']`; `-S "vcodec:h264,res,br"` does download format 140 (best m4a) for audio), and then format 234 by specifying it. Only way is manually it seems!

**Comment by pukkandan** [comment]
-f (bv+(234/ba))/b
