### ISSUE TITLE
Twitter spaces download not merging

### ISSUE THREAD

**Issue by qayyumabro** [yt-dlp/yt-dlp#7563]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting that yt-dlp is broken on a **supported** site
- [X] I've verified that I'm running yt-dlp version **2023.07.06** ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#video-url-contains-an-ampersand--and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched [known issues](https://github.com/yt-dlp/yt-dlp/issues/3766) and the [bugtracker](https://github.com/yt-dlp/yt-dlp/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#opening-an-issue)
- [X] I've read about [sharing account credentials](https://github.com/yt-dlp/yt-dlp/blob/master/CONTRIBUTING.md#are-you-willing-to-share-account-details-if-needed) and I'm willing to share it if required

### Region

Pakistan

### Provide a description that is worded well enough to be understood

This is the command I'm trying:

 --cookies "C:\Users\Name\Downloads\twitter.com_cookies.txt"  --concurrent-fragments 20 https://twitter.com/i/spaces/1rmGPkznZeMKN?s=20

It only produces 2KB file at the end.

### Provide verbose output that clearly demonstrates the problem

- [X] Run **your** yt-dlp command with **-vU** flag added (`yt-dlp -vU <your command line>`)
- [X] If using API, add `'verbose': True` to `YoutubeDL` params instead
- [X] Copy the WHOLE output (starting with `[debug] Command-line config`) and insert it below

### Complete Verbose Output

```shell
[debug] Command-line config: ['--cookies', 'C:\\Users\\Name\\Downloads\\twitter.com_cookies.txt', '-vU', '--concurrent-fragments', '20', 'https://twitter.com/i/spaces/1rmGPkznZeMKN?s=20']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481] (win_x86_exe)
[debug] Python 3.7.9 (CPython AMD64 32bit) - Windows-10-10.0.22621-SP0 (OpenSSL 1.1.1g  21 Apr 2020)
[debug] exe versions: ffmpeg N-87027-gd826951, ffprobe N-87353-g183fd30
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.05.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.07.06, Current version: stable@2023.07.06
Current Build Hash: 7ce646283f2c437e2dc28e3008c892702824b6174f381d82b8e68c5bdb6be3b2
yt-dlp is up to date (stable@2023.07.06)
[twitter:spaces] Extracting URL: https://twitter.com/i/spaces/1rmGPkznZeMKN?s=20
[twitter:spaces] 1rmGPkznZeMKN: Downloading GraphQL JSON
[twitter:spaces] 28_1672002056633335808: Downloading legacy API JSON
[twitter:spaces] 28_1672002056633335808: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 1rmGPkznZeMKN: Downloading 1 format(s): 0
[debug] Invoking hlsnative downloader on "https://prod-fastly-us-west-1.video.pscp.tv/Transcoding/v1/hls/zh-C_L-JKRiIZ0pFnaJNyWfC2OS4Pr6gW2CtziuUJxZbLs0-XUOSRQEHez1ZNFtJ7YSTmNq-lox_LXupV9X9Jw/non_transcode/us-west-1/periscope-replay-direct-prod-us-west-1-public/audio-space/playlist_16759189408181239545.m3u8?type=replay"
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 2593
[download] Destination: 🟧 Ordinal Architects 🟧 - Saint x OnChainMonkey [1rmGPkznZeMKN].m4a
[debug] File locking is not supported. Proceeding without locking
WARNING: The download speed shown is only of one thread. This is a known issue
[download]  72.5% of ~  96.95MiB at   90.02KiB/s ETA 05:03 (frag 1880/2593)[download] Got error: <urlopen error timed out>. Retrying (1/10)...
[download] Got error: <urlopen error timed out>. Retrying (1/10)...
[download] Got error: <urlopen error timed out>. Retrying (1/10)...
[download] Got error: <urlopen error timed out>. Retrying (1/10)...
[download] Got error: <urlopen error timed out>. Retrying (1/10)...
[download] Got error: <urlopen error timed out>. Retrying (1/10)...
[download] Got error: <urlopen error timed out>. Retrying (1/10)...
[download] Got error: <urlopen error timed out>. Retrying (1/10)...
[download] Got error: <urlopen error timed out>. Retrying (1/10)...
[download]  72.5% of ~  96.95MiB at   35.96KiB/s ETA 12:38 (frag 1881/2593)[download] Got error: <urlopen error timed out>. Retrying (1/10)...
[download] Got error: <urlopen error timed out>. Retrying (1/10)...
[download] Got error: <urlopen error timed out>. Retrying (1/10)...
[download] Got error: <urlopen error timed out>. Retrying (1/10)...
[download] Got error: <urlopen error timed out>. Retrying (1/10)...
[download]  72.7% of ~  96.96MiB at  393.88KiB/s ETA 01:08 (frag 1885/2593)[download] Got error: <urlopen error timed out>. Retrying (1/10)...
[download] Got error: <urlopen error timed out>. Retrying (1/10)...
[download]  72.8% of ~  96.96MiB at  404.14KiB/s ETA 01:06 (frag 1887/2593)[download] Got error: <urlopen error timed out>. Retrying (1/10)...
[download] 100% of   98.13MiB in 00:02:43 at 613.49KiB/s
[FixupM4a] Correcting container of "🟧 Ordinal Architects 🟧 - Saint x OnChainMonkey [1rmGPkznZeMKN].m4a"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:🟧 Ordinal Architects 🟧 - Saint x OnChainMonkey [1rmGPkznZeMKN].m4a" -map 0 -dn -ignore_unknown -c copy -f mp4 -movflags "+faststart" "file:🟧 Ordinal Architects 🟧 - Saint x OnChainMonkey [1rmGPkznZeMKN].temp.m4a"
[debug] ffprobe command line: ffprobe -hide_banner -show_format -show_streams -print_format json "file:🟧 Ordinal Architects 🟧 - Saint x OnChainMonkey [1rmGPkznZeMKN].m4a"
```

**Comment by qayyumabro** [comment]
Still produces 2Kb files.

I have tried with --ffmpeg-location and --downloader ffmpeg both. It throws error for the later.

 .\youtube-dl.exe  --cookies "C:\Users\Name\Downloads\twitter.com_cookies.txt"  -vU --downloader ffmpeg https://twitter.com/i/spaces/1rmGPkznZeMKN?s=20

[debug] Command-line config: ['--cookies', 'C:\\Users\\Name\\Downloads\\twitter.com_cookies.txt', '-vU', '--downloader', 'ffmpeg', 'https://twitter.com/i/spaces/1rmGPkznZeMKN?s=20']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version stable@2023.07.06 [b532a3481] (win_x86_exe)
[debug] Python 3.7.9 (CPython AMD64 32bit) - Windows-10-10.0.22621-SP0 (OpenSSL 1.1.1g  21 Apr 2020)
[debug] exe versions: ffmpeg N-87027-gd826951, ffprobe N-87353-g183fd30
[debug] Optional libraries: Cryptodome-3.18.0, brotli-1.0.9, certifi-2023.05.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-11.0.3
[debug] Proxy map: {}
[debug] Loaded 1855 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
Available version: stable@2023.07.06, Current version: stable@2023.07.06
Current Build Hash: 7ce646283f2c437e2dc28e3008c892702824b6174f381d82b8e68c5bdb6be3b2
yt-dlp is up to date (stable@2023.07.06)
[twitter:spaces] Extracting URL: https://twitter.com/i/spaces/1rmGPkznZeMKN?s=20
[twitter:spaces] 1rmGPkznZeMKN: Downloading GraphQL JSON
[twitter:spaces] 28_1672002056633335808: Downloading legacy API JSON
[twitter:spaces] 28_1672002056633335808: Downloading m3u8 information
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[info] 1rmGPkznZeMKN: Downloading 1 format(s): 0
[debug] Invoking ffmpeg downloader on "https://prod-fastly-us-west-1.video.pscp.tv/Transcoding/v1/hls/zh-C_L-JKRiIZ0pFnaJNyWfC2OS4Pr6gW2CtziuUJxZbLs0-XUOSRQEHez1ZNFtJ7YSTmNq-lox_LXupV9X9Jw/non_transcode/us-west-1/periscope-replay-direct-prod-us-west-1-public/audio-space/playlist_16759189408181239545.m3u8?type=replay"
[download] Destination: 🟧 Ordinal Architects 🟧 - Saint x OnChainMonkey [1rmGPkznZeMKN].m4a
[debug] ffmpeg command line: ffmpeg -y -loglevel verbose -headers "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-us,en;q=0.5
Sec-Fetch-Mode: navigate
" -i "https://prod-fastly-us-west-1.video.pscp.tv/Transcoding/v1/hls/zh-C_L-JKRiIZ0pFnaJNyWfC2OS4Pr6gW2CtziuUJxZbLs0-XUOSRQEHez1ZNFtJ7YSTmNq-lox_LXupV9X9Jw/non_transcode/us-west-1/periscope-replay-direct-prod-us-west-1-public/audio-space/playlist_16759189408181239545.m3u8?type=replay" -c copy -f mp4 "file:🟧 Ordinal Architects 🟧 - Saint x OnChainMonkey [1rmGPkznZeMKN].m4a.part"
ffmpeg version N-87027-gd826951 Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 7.1.0 (GCC)
  configuration: --enable-gpl --enable-version3 --enable-cuda --enable-cuvid --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-nvenc --enable-avisynth --enable-bzlib --enable-fontconfig --enable-frei0r --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libfreetype --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libzimg --enable-lzma --enable-zlib
  libavutil      55. 74.100 / 55. 74.100
  libavcodec     57.103.100 / 57.103.100
  libavformat    57. 76.100 / 57. 76.100
  libavdevice    57.  7.100 / 57.  7.100
  libavfilter     6.100.100 /  6.100.100
  libswscale      4.  7.102 /  4.  7.102
  libswresample   2.  8.100 /  2.  8.100
  libpostproc    54.  6.100 / 54.  6.100
[tls @ 03e7d600] Server closed the connection
[hls,applehttp @ 03e78000] HLS request for url 'https://prod-fastly-us-west-1.video.pscp.tv/Transcoding/v1/hls/zh-C_L-JKRiIZ0pFnaJNyWfC2OS4Pr6gW2CtziuUJxZbLs0-XUOSRQEHez1ZNFtJ7YSTmNq-lox_LXupV9X9Jw/non_transcode/us-west-1/periscope-replay-direct-prod-us-west-1-public/audio-space/chunk_1687546882773029679_0_a.aac', offset 0, playlist 0
[hls,applehttp @ 03e78000] Opening 'https://prod-fastly-us-west-1.video.pscp.tv/Transcoding/v1/hls/zh-C_L-JKRiIZ0pFnaJNyWfC2OS4Pr6gW2CtziuUJxZbLs0-XUOSRQEHez1ZNFtJ7YSTmNq-lox_LXupV9X9Jw/non_transcode/us-west-1/periscope-replay-direct-prod-us-west-1-public/audio-space/chunk_1687546882773029679_0_a.aac' for reading
Input #0, hls,applehttp, from 'https://prod-fastly-us-west-1.video.pscp.tv/Transcoding/v1/hls/zh-C_L-JKRiIZ0pFnaJNyWfC2OS4Pr6gW2CtziuUJxZbLs0-XUOSRQEHez1ZNFtJ7YSTmNq-lox_LXupV9X9Jw/non_transcode/us-west-1/periscope-replay-direct-prod-us-west-1-public/audio-space/playlist_16759189408181239545.m3u8?type=replay':
  Duration: 02:09:42.89, start: 45909.068111, bitrate: 0 kb/s
  Program 0
    Metadata:
      variant_bitrate : 0
    Stream #0:0: Audio: aac (LC), 48000 Hz, stereo, fltp, 96 kb/s
    Metadata:
      variant_bitrate : 0
Output #0, mp4, to 'file:≡ƒƒº Ordinal Architects ≡ƒƒº - Saint x OnChainMonkey [1rmGPkznZeMKN].m4a.part':
  Metadata:
    encoder         : Lavf57.76.100
    Stream #0:0: Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 96 kb/s
    Metadata:
      variant_bitrate : 0
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
Press [q] to stop, [?] for help
Automatically inserted bitstream filter 'aac_adtstoasc'; args=''
https://prod-fastly-us-west-1.video.pscp.tv/Transcoding/v1/hls/zh-C_L-JKRiIZ0pFnaJNyWfC2OS4Pr6gW2CtziuUJxZbLs0-XUOSRQEHez1ZNFtJ7YSTmNq-lox_LXupV9X9Jw/non_transcode/us-west-1/periscope-replay-direct-prod-us-west-1-public/audio-space/playlist_16759189408181239545.m3u8?type=replay: Invalid data found when processing input
No more output streams to write to, finishing.
size=       2kB time=00:00:00.06 bitrate= 224.0kbits/s speed=98.9x
video:0kB audio:1kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 75.000000%
Input file #0 (https://prod-fastly-us-west-1.video.pscp.tv/Transcoding/v1/hls/zh-C_L-JKRiIZ0pFnaJNyWfC2OS4Pr6gW2CtziuUJxZbLs0-XUOSRQEHez1ZNFtJ7YSTmNq-lox_LXupV9X9Jw/non_transcode/us-west-1/periscope-replay-direct-prod-us-west-1-public/audio-space/playlist_16759189408181239545.m3u8?type=replay):
  Input stream #0:0 (audio): 4 packets read (1024 bytes);
  Total: 4 packets (1024 bytes) demuxed
Output file #0 (file:≡ƒƒº Ordinal Architects ≡ƒƒº - Saint x OnChainMonkey [1rmGPkznZeMKN].m4a.part):
  Output stream #0:0 (audio): 4 packets muxed (1024 bytes);
  Total: 4 packets (1024 bytes) muxed
[download] 100% of    1.75KiB in 00:00:05 at 303.27B/s
[FixupM4a] Correcting container of "🟧 Ordinal Architects 🟧 - Saint x OnChainMonkey [1rmGPkznZeMKN].m4a"
[debug] ffmpeg command line: ffmpeg -y -loglevel "repeat+info" -i "file:🟧 Ordinal Architects 🟧 - Saint x OnChainMonkey [1rmGPkznZeMKN].m4a" -map 0 -dn -ignore_unknown -c copy -f mp4 -movflags "+faststart" "file:🟧 Ordinal Architects 🟧 - Saint x OnChainMonkey [1rmGPkznZeMKN].temp.m4a"

**Comment by bashonly** [comment]
upgrade your ffmpeg (the build is from 2017) and add `--fixup never` to the command

**Comment by qayyumabro** [comment]
Yup this fixes the issue. I hope we will have **--concurrent-fragments** soon for this as well. 
Thank you.
